[quote.epigraph, , Rev. 1:11]
____
What thou seest, write in a book, and send it into the seven churches.
____

[quote.epigraph, , 2 Cor. 1:11]
____
For we write none other things unto you than what you have read and acknowledged,
and I trust you shall acknowledge even unto the end.
____

== An Epistle, By Way of Preface,

To all truth`'s friends and all friendly readers, greeting:
in the dear and tender love of my heavenly Father,
which by his dear son and blessed spirit,
he hath plentifully shed abroad in many hearts in this glorious gospel day:
glory to his worthy name and excellent power forever.

Dear Friends,--I am concerned to recommend the serious
reading and perusal of the ensuing collection,
unto all who sincerely desire the promotion of Christ`'s kingdom,
and prosperity of his church and Zion, in true love, union, and order,
in and by Christ Jesus himself, the head and foundation thereof.

And that none of you would think the perusal of these Epistles wearisome or tedious,
because the same words and things in many of them may seem frequently repeated,
there being numerous evangelical truths, and variety of good and wholesome matter,
as well as diversities of epistles,
containing much christian counsel to many various states and conditions
of enlightened and enlivened souls travelling and breathing to God;
so that the frequent intermixed repetitions of the same necessary
truths may be the better allowed and borne with in the reading.
However, the moderate and ingenuous reader will not be offended thereat,
it being a thing frequent in the holy scriptures,
to have the same gospel truths often repeated;
for many dull and forgetful persons have need to be often told of such matters,
of so great importance.
The author`'s epistles and matters of most general concern are here collected,
so as to avoid prolixity and unnecessary repetitions, as much as could be.

The simplicity and plainness of the author`'s style is not to be despised,
he being more in life and substance than in the wisdom of words, or eloquence of speech.
And the Lord being pleased in his day to make great use of him,
and to do great things by him, for his name and seed`'s sake;
of which there yet remain clouds of witnesses,
even to that divine power and hidden wisdom of God,
(in the mystery of Christ,) which was with him, and supported him,
and lifted up his head through many great fights of afflictions and trials.

I confess, I have not read or heard all the epistles in the ensuing collection;
but many of them, which I know to be very seasonable, weighty and necessary;
and therefore have cause to believe so of the rest, which I have not read.
But, by our long and frequent conversation, knowledge, and intimacy,
(together with his living and revived testimonies,
his godly care and zeal for truth`'s honour and prosperity,)
I have deeply read and known the author,
his unfeigned love, innocency, and integrity in the blessed living truth,
whose christian care, (among many other things, relating to the churches of Christ,
the union, good order and discipline thereof,) greatly was,
that no offence in any thing might be given; that the ministry might not be blamed;
well knowing what trials and proofs attended Christ`'s
ministers and ministry in these latter days,
(in some degree,) as in the primitive christians`' times; namely, that he,
with many others in his day, approved himself, and themselves,
as the ministers of Christ, in much patience, in deep afflictions, in necessities,
in distresses, (and some in stripes and cruel beatings,) in prisons, in tumults,
in labours, by watchings and by fastings, by purity, by knowledge, by long suffering,
by kindness, by the holy ghost, by love unfeigned, by the word of truth,
by the power of God, by the armour of righteousness, on the right hand, and on the left,
by honour and dishonour, by evil report and good report; as deceivers, and yet true, etc.
2 Cor.
6+++.+++ In which proofs of God`'s ministers, this his ancient servant had a deep share,
and the true root of the matter was in him, far beyond his expressions.

And though many false predictions, prophecies,
and cruel threats were early breathed out by persecutors and envious spirits against him,
and us his friends and brethren, whom he unfeignedly loved,
and against his and our holy profession, way, and testimony,
as if in a very short time all would come to nought, and be laid waste;
yet they have all been disappointed, and proved false,
and his christian living testimony and work further manifested to be of God,
and not of men, nor of the will of man.
For truth, that is strongest of all, hath still prevailed, and must prevail.
And though the memory of this our deceased brother and faithful servant of Jesus Christ,
be still greatly envied, and be most grossly defamed, by some implacable adversaries,
and hardened apostates,
who could not obtain their evil ends and destructive
designs against him in his life time;
yet his memory is truly precious to many thousands,
who truly fear God and love his truth, who have a true inward sense,
that such a divine power and providence attended him in his innocent christian testimony,
ministry, labours, and sufferings, that the devil and all persecuting agents,
could never stop nor frustrate his testimony or service,
in turning many to righteousness, even from darkness unto light,
and from the power of Satan unto God.

In many of the ensuing epistles, he often mentions the seed, the life, the power of God,
and the like;
whereby he intends no other than what the holy scriptures testify of Christ; which,
we know, he truly loved and esteemed, and was often conversant in reading of them,
and had an excellent memory and spiritual sense thereof given him of the Lord.
By the pure holy seed, he meant and declared Christ, the promised seed;
wherein all the promises of God are yea and amen.
And as Christ is the word of God, the word of life, the word of faith,
he is that immortal and incorruptible seed, of which all true and spiritual believers,
and children of the light are begotten to God, and born again; and which seed,
or word of eternal life, abideth in him that is born of God,
and sinneth not because thereof.
1 John 3. And as the generation of God, and children of his kingdom, and of the promise,
they are called the good seed, and counted for the seed,
being born of that incorruptible seed, or word of life, which endureth forever,
1 Peter 23.15; and being that blessed seed and holy generation,
which was foretold Christ should see, and for which the travail of his soul was.
Isa. 53.

This our deceased friend and servant of Jesus Christ truly testified of him in all respects,
both as come in the flesh and in the spirit,
both as Christ was and is our only mediator and advocate,
and as he was and is God over all, blessed forever;
whom he so dearly loved and honoured, that he often offered up his life,
and deeply suffered for him; and that in dear and constant love to his seed,
that a holy generation might be raised, strengthened,
and increased in the earth among the children of men.
And his knowledge and ministry of our Lord Jesus Christ, being after the spirit,
in life and power, did no ways imply any lessening of the dignity or glory of Christ,
nor any defect of faith or love to Christ,
as he came and suffered in the flesh for mankind,
as some adversaries have injuriously misrepresented and aspersed him;
for he highly esteemed Christ`'s sufferings, death, resurrection, and glory;
and powerfully testified of the virtue, power, blessed and spiritual design, fruit,
and effects thereof, as revealed and witnessed by his holy spirit.
And as we have no cause to question, but that with this innocent and good man,
"`to live was Christ;`" so, "`to die was gain;`" in both which he glorified God.

Christ Jesus being our spiritual rock, foundation, and head,
he is truly precious to us and all true believers, in all states and conditions,
both of his humiliation, glory, and dominion;
his great grace and goodness appearing in those precious ministerial gifts given by him,
(when he ascended up on high,) for his ministry and church.

And it is very observable,
that though to express Christ`'s lowly condition and appearance in the world,
he is sometimes in holy scripture termed the seed,
his name also is called "`wonderful counsellor, the mighty God, the everlasting Father,
the prince of peace; upon whose shoulders the government is laid:
and of the increase of his government and peace there shall be no end.`"
Isaiah 9. And it is most suitable to Christ`'s low, humble, and suffering condition,
to make use of such instruments as are most like
himself in humility and lowliness of mind;
although they be but low and mean in the world`'s eye and esteem.
God is pleased to make choice of low, mean, and weak things,
and of instruments contemptible in the eyes of the high and lofty ones of this world,
to confound the wisdom of the world, according to 1 Cor.
1+++.+++ He chose poor shepherds to divulge that great evangelical truth of Christ`'s birth;
and certain women to preach that gospel truth of his resurrection.
Luke 2. and 24. And both from angelical testimony, and from their sight of Christ himself.
Truth must not be rejected because of such instruments which
God in his wisdom is pleased to employ in his work;
nor the day of small things despised.
From small beginnings of good matters, great things,
glorious attainments and perfections spring.
Glory, honour, and dominion to our most gracious God, and to the Lamb on his throne,
forever and ever.

Now, dear and well beloved friends, all live in love and peace, following the true faith,
peaceable and good example of the faithful in Christ,
and the God of love and peace will be with you.

Your true friend and brother in Christ Jesus,

GEORGE WHITEHEAD.

London, 1698.
