== Letters 1 &#8212; 31

[.centered]
=== Letter 1.

Friends,

Forsake the company of wild people, and choose the company of sober men,
and that will be creditable in the end.
And choosing the company of wild and light people,
who delight in vain fashions and ill courses, is dangerous,
and of a bad report among sober people; for the eyes of such will be upon you:
and if they see, ye are wild, ye will come under their censure.
Therefore love gravity, and soberness, and wisdom, that doth preserve.

G+++.+++ F.

[.centered]
=== Letter 2.

Friends,

The children of the devil, how expert are they in evil, in all deceit in his kingdom;
and yet they may speak of the things of God:
but no vulturous eye or venomous beast ever trod in the steps of the just,
though they may talk of the way.
For who have their conversation in this world, and only mind the things of this world,
in vain do they profess godliness.

But the children of God, who are conceived and begotten of him, are not of this world,
neither do they mind only the things of this world, but the things which are eternal.
But the children of this world do mostly mind the external things,
and their love is in them, and the other live by faith;
the one is sanctified by the word, the other painted with the words.
The children of God are pure in heart, not looking only at the outside.
The favour of the world and friendship thereof is enmity to God,
man may soon be stained with it.
Oh! love the stranger, and be as strangers in the world, and to the world!
For they that followed Christ in his cross, they were strangers in the world,
and wonders to the world, and condemned by the world and the world knew him not,
neither doth it them that follow him now.
So, marvel not if the world hate you; for the world lieth in hatred and wickedness.
Who love this world, are enemies to Christ; and who love the Lord Jesus Christ,
and have him for their Lord over them, they are redeemed out of the world.
The world would have a Christ, but not to rule over them;
the nature of the world is above Christ in man,
until Christ hath subdued that nature in man.
While the nature of the world doth rule in man, Oh the deaf ears and blind eyes,
and the understandings, that are all shut up amongst them, with which they judge!
But who love the Lord Jesus Christ, do not mind the world`'s judgment,
nor are troubled at it; but consider all our brethren, who have gone before us.

When ye think ye are past all crosses, when the trial doth come,
ye will find a cross to that will which doth meddle with the things of God presumptuously;
that man may live in joy, but the spirit is in bondage.
Rejoice not in the flesh, but in the spirit, which crucifieth all fleshly boastings:
if the fleshly will be fed, then carelessness cometh up, and they fall into flatness,
(from the spirit,) and are mindless of the Lord God; such are soon up and down.
The serpent tempted Eve to eat of the forbidden fruit,
and she took and gave to her husband, and so they fell under the serpent`'s power,
and the creatures, out of the power of God, which would have kept them in dominion.
And so, Adam and Eve, and the serpent, all went out of truth.
And Eve eating of the tree of knowledge, she had knowledge and wisdom after the fall,
but not in the dominion, in the power of God.
But the seed Christ, which was in the beginning, bruiseth the serpent`'s head,
and he is the wisdom of God.

G+++.+++ F.

[.centered]
=== Letter 3.

[.blurb]
==== A little note to Friends at first.

Friends,

There is an eye, that hath looked to see the good seed, that was sown, and queried,
from whence came these tares?
The answer was and is; "`The wicked one hath sown them.`"
Now read the tares, and what is the effect of them, and their work?
And what they do, and have done?
How they hang amongst the wheat?
But now is the time of harvest, that both wheat and tares are seen,
and each distinguished, the one from the other.

G+++.+++ F.

[.centered]
=== Letter 4.

All Friends, mind that which is pure in you to guide you to God, out of Babylon,
out of confusion: there all the world is; there is the seat of the beast;
there are the false prophets and deceivers, as well within as without.
One voice of deceit knows not another, nor any of them the voice of the living God.
But, dear friends, mind the light of God in your consciences,
which will show you all deceit; dwelling in it,
guides out of the many things into one spirit, which cannot lie, nor deceive.
They that are guided by it, are one, who have been made to drink into one spirit;
and the spirits of the prophets are subject to the prophets.
God is not the author of confusion, but of peace.
All jarrings, all schisms, all rents are out of the spirit,
for God hath tempered the body together, that there should be no schism in the body,
but all worship him with one consent.
And as the power and life of truth are made manifest,
watch in the discerning one over another.

And beware of discouraging any in the work of God: the labourers are few,
that are faithful for God.
Take heed of hurting the gift, which God hath given to profit withal,
whereby ye have received life through death,
and a measure of peace by the destruction of evil.
Pray, that peace may be multiplied, and the ministration of life,
to the raising of the dead,
that "`the seed of the woman may bruise the serpent`'s head,`" discover all deceit,
and rend all veils and coverings, that the pure may come to life,
which deceit hath trampled upon.

And all take heed to your spirits; that which is hasty, discerns not the good seed.
Take heed of being corrupted by flatteries; they that know their God, shall be strong.
But take heed of labouring to turn the just aside for a thing of nought,
but know the precious from the vile, the clean from the unclean;
"`These shall be as my mouth,`" saith the Lord, for his work is great,
and his gifts diverse.
And therefore all mind your gift, mind your measure; mind your calling and your work.
Some speak to the conscience; some plough and break the clods; some weed out,
and some sow; some wait, that fowls devour not the seed.
But wait all for the gathering of the simple-hearted ones;
for "`they that turn many to righteousness, shall shine forever.`"

Mind the light, that all may be refreshed one in another, and all in one.
And the God of power and love keep all Friends in power, in love,
that there be no surmisings, but pure refreshings in the unlimited love of God,
which makes one another known in the conscience, to read one another`'s hearts:
being comprehended into this love, it is inseparable, and all are here one.
And keep in the oneness, and note them that cause dissention,
contrary to the gospel ye have received; that one pure faith may be held in all,
to guide and preserve all in the unity of the spirit and bond of peace;
all one family of love, children of one father, and of the household of God.

G+++.+++ F.

[.centered]
=== Letter 5.

[.blurb]
==== To his Parents.

Dear father and mother in the flesh, but not of that birth which speaks to you:
for like to that which doth beget, is that which is begotten.
Praises, praises be given to my heavenly Father,
who hath begotten me again by the immortal word.

To that of God in you both I speak, and do beseech you both for the Lord`'s sake,
to return within, and wait to hear the voice of the Lord there; and waiting there,
and keeping close to the Lord, a discerning will grow,
that ye may distinguish the voice of the stranger, when ye hear it.
Oh! be faithful, be faithful to the Lord in that ye know;
for in the backslider the Lord hath no pleasure, neither shall their damnation slumber.
Oh! be faithful!
Look not back, nor be too forward, further than ye have attained; for ye have no time,
but this present time: therefore prize your time for your souls`' sake.
And so, grow up in that which is pure, and keep to the oneness; then shall my joy be full.
So fare ye well!
And the Lord God of power keep you in his power!
To him be praises forevermore.

G+++.+++ F.

[.centered]
=== Letter 6.

[.blurb]
==== To Friends.

Friends,

No one is justified, breaking the commands of Christ; no one is justified,
living in iniquity; and no one is justified in professing only Christ`'s words,
and the prophets`', and the apostles`' words, and living out of their lives:
and no one is justified living in the first birth and nature, and false faith and hope,
which doth not purify, as God is pure.
No man is justified not believing in the light, as Christ commands,
but with the light is condemned;
for the light is the condemnation of all them that walk contrary to it:
therefore the power of God mind.
No man is justified, acting contrary to that spirit which doth convince them.

G+++.+++ F.

[.centered]
=== Letter 7.

[.blurb]
==== To Friends at Swarthmore.

Friends,

Love that which judgeth the carnal mind, and crosseth it,
which maketh an entrance to God, and keepeth you open;
and then refreshment will come into your souls from the Lord.
Dwell in the power, and know the power of words in one another; and take heed of deceit.
Farewell: and the God of love and power keep you to himself!

G+++.+++ F.

[.centered]
=== Letter 8.

Dear Friends,

Those that will live godly in Christ Jesus, must suffer persecution.
God is righteous, God is pure, holy, and just; God is clean.
He that is godly and holy, suffereth by the ungodly, and unrighteous, and unclean,
and unjust, and filthy.
And so the just suffereth by the unjust; and he that is born of the flesh,
persecutes him that is born of the spirit.

G+++.+++ F.

[.centered]
=== Letter 9.

Friends,

That which is set up by the sword, is held up by the sword;
and that which is set up by spiritual weapons, is held up by spiritual weapons,
and not by carnal weapons.
The peacemaker hath the kingdom, and is in it;
and hath the dominion over the peace-breaker, to calm him in the power of God.

And friends, let the waves break over your heads.
There is rising a new and living way out of the north,
which makes the nations like waters.
Hurt not the vines, nor the oil, nor such as know that "`the earth is the Lord`'s,
and the fulness thereof.`"
The days of virtue, love, and peace, are come and coming,
and the Lamb had and hath the kings of the earth to war withal, and to fight withal,
who will overcome with the sword of the spirit, the word of his mouth;
for the Lamb shall have the victory.

And are not some like Ephraim, with a miscarrying womb?
which have not brought forth the substance, the birth from above;
but have brought forth children to murder?

G+++.+++ F.

[.centered]
=== Letter 10.

[.blurb]
==== To Friends, to stand still in trouble, and see the strength of the Lord.

Friends,

Whatever ye are addicted to, the tempter will come in that thing;
and when he can trouble you, then he gets advantage over you, and then ye are gone.
Stand still in that which is pure, after ye see yourselves; and then mercy comes in.
After thou seest thy thoughts, and the temptations, do not think, but submit;
and then power comes.
Stand still in that which shows and discovers; and there doth strength immediately come.
And stand still in the light, and submit to it, and the other will be hushed and gone;
and then content comes.
And when temptations and troubles appear, sink down in that which is pure,
and all will be hushed, and fly away.
Your strength is to stand still, after ye see yourselves;
whatsoever ye see yourselves addicted to, temptations, corruption, uncleanness,
etc. then ye think ye shall never overcome.
And earthly reason will tell you, what ye shall lose; hearken not to that,
but stand still in the light that shows them to you,
and then strength comes from the Lord, and help contrary to your expectation.
Then ye grow up in peace, and no trouble shall move you.
David fretted himself, when he looked out; but when he was still,
no trouble could move him.
When your thoughts are out, abroad, then troubles move you.
But come to stay your minds upon that spirit which was before the letter;
here ye learn to read the scriptures aright.
If ye do any thing in your own wills, then ye tempt God;
but stand still in that power which brings peace.

G+++.+++ F.

[.centered]
=== Letter 11.

Dear hearts, brethren, and babes of Christ, wait to feed on the immortal food,
and walk in the truth, and God Almighty be among you!
And in it ye will see him; stand all naked, bare, and uncovered before the Lord.
And take heed of your wills, for that (as Herod) slayeth the just,
and shipwrecks the faith, and runs you into the flesh.
Return back, and stay yourselves upon the Lord every particular,
to have your minds guided by his spirit;
growing up in that which is precious and immortal, there is no feigned love.
So, the eternal God keep you in his eternal love pure unto himself, and naked,
and knit your hearts together!
God Almighty bless you, and water you with the showers of his mercy,
and with the dew of heaven!

G+++.+++ F.

[.centered]
=== Letter 12.

Friends,

If ye love the light, and walk in it, ye love Christ, and will all walk in unity together.
And if ye hate the light, ye hate Christ.
Here is your teacher, who love it; here is your condemnation, who hate the light.
And the conscience being seared, there is a returning to teachers without.
For the carnal will have its vain invented form;
but the spirit`'s form stands in the power.
Prove yourselves where ye are.

G+++.+++ F.

[.centered]
=== Letter 13.

[.blurb]
==== To the flock of God about Sedburgh.

Every one in your measure wait upon God, who is the true shepherd,
and leads his flock into the green pastures, and fresh springs he opens daily;
this ye will see and experience.
And mind that which is pure in one another, which joins you together;
for nothing will join, or make fit, but what is pure; nor unite, nor build,
but what is pure.
Therefore every particular, fear God;
for whatsoever ye build of yourselves will not stand, but will tumble down again;
although it be as gold, or silver, or brass, or iron, the strength of all these things,
which is above the pure in you, will come to nothing,
and this will not unite with the pure.
Therefore wait every one in the measure which God hath given you;
and none of you be sayers only, but doers of the word.
And so, walk in the truth, and be ye all servants to it,
and it will lead you out of the world.
The world would have the truth to serve them to talk of, to trade withal,
and to contend withal; these are the wells without water,
these are the trees without fruit.
But they who dwell in the spirit of the Lord, (which is pure, which joins together,
and unites and builds up all in one spirit,) see all these things,
and are separated from them.
So if ye live in the spirit, and walk in it, ye will not fulfill the lusts of the flesh,
which will lead into uncleanness, and into adultery,
and into that which despiseth dignity, which defiles the flesh, and goes from the pure.
Therefore the pure faith is to be contended for;
and those who were sanctified by God the Father, did contend for it,
and were preserved by it in Christ Jesus.
Therefore wait upon God for the living bread, that never fades away;
which he that eats of, lives forever.
So God Almighty bless you, and keep you in the measure of his gift, faithful to himself!

Dear hearts! to that which is pure in you I speak,
(which the presumptuous mind would veil,) that God alone may be exalted,
and all flesh shattered down.
And all are to take warning, and not one to exalt himself above another;
but that God alone may be exalted among you all, and in you all,
who alone is blessed forever.
And ye may see, from whence your heavenly food comes alone, and grow up by it;
for God hath done great things in these northern parts,
and the Lord is doing great things to the exaltation of his great name,
and astonishing the heathen; notwithstanding the raging of the beast,
and the opening of his mouth, to the blaspheming of God and his temple.
Therefore all be valiant in the Lord God; and so fare ye well!
And the Lord God of power keep you.

G+++.+++ F.

[.centered]
=== Letter 14.

[.blurb]
==== A word from the Lord to Friends.

All Friends, that are grown up in the life and power of the truth,
see that when ye appoint your meetings in any open place, in the fields, on the moors,
or on the mountains, that none appoint meetings in your own wills;
for that lets in the wills of the world upon the life of Friends,
and so ye come to suffer by the world.
But at such meetings let the wisdom of God guide you,
that some may be there to preserve the truth from suffering by the world;
that all burdens may be kept off, and taken away.
So will ye grow pure and strong.
And when there are any meetings in unbroken places, ye that go to minister to the world,
take not the whole meeting of Friends with you thither,
to suffer with and by the world`'s spirit; but let Friends keep together,
and wait in their own meeting place.
So will the life, (in the truth,) be preserved and grow.
And let three, or four, or six, that are grown up strong, and are in the truth,
go to such unbroken places, and thresh the heathenish nature;
and there is true service for the Lord.
And to you all this is the counsel of the Lord.
The grace of God, the Father of our Lord Jesus Christ, be with your spirits!
Amen.

G+++.+++ F.

[.centered]
=== Letter 15.

[.blurb]
==== To the Church of God in Lancashire.

Friends, Every one in particular, who are of God, and not of the world,
walk out of the world`'s vain customs, ordinances, and commands;
and stand a witness against them all, in the testimony of Jesus,
and witness him the substance of all, waiting in the light of God, and walking in it,
then will ye have unity one with another,
and the blood of Jesus Christ will cleanse you from all sin;
for through it and by it we do overcome; which blood of the new covenant is but one.
There shall ye witness the lamb of God, that takes away the sins of the world.
Oh!--wait all in that which is pure, to be fed alone of God with the eternal, living food!
Go not out among the swine, who feed upon the outside, the husk,
among the merchants of Babylon, and so forsake the living bread;
but as ye have received Christ Jesus, in him walk,
that ye may all honour the Lord Jesus Christ, and adorn his gospel.
And be famous in his light, and bold in his strength,
which will carry you above the world, and above all the deceits of it.
Oh! in love watch over one another for good, and for the better, and not for the worse!
And dwell in that which is pure of God in you, lest your thoughts get forth;
and then evil thoughts get up, and surmising one against another,
which ariseth out of the veiled mind, which darkens the pure discerning.
But as ye dwell in that which is of God, it guides you up out of the elementary life,
and out of the mortal into the immortal,
(which is hid from all the fleshly ones,) where is peace
and joy eternal to all that can witness the new birth.
Babes in Christ, born again of the immortal seed, in it wait,
my life is with you in perfect unity; bow down to nothing but the Lord God.
Satan would have had Christ to have bowed down, but he would not; the same seed now,
the same birth born in you now, which is the same today, yesterday, and forever.
The tempter will come to you; and if ye look forth, and hearken to his words,
and let them in, then ye bow down under him, and worship him.
But I say unto you, and charge you in the presence of the Lord,
mind the pure seed of God in you,
and the mighty power of God will cherish you up to the Lord God above all temptations,
not to bow down to any thing; but feeding upon the immortal food,
ye will feel yourselves supported, and carried over him by your Father and your God,
who is over all, blessed forever!
Who is the virtue of all creatures, the wisdom of all things;
all holy praises be unto the holy, glorious Lord God forever!

G+++.+++ F.

[.centered]
=== Letter 16.

To all you, my dear friends, who have tasted of the immediate, working power of the Lord,
and do find an alteration in your minds, and do see from whence virtue doth come,
and strength, that doth renew the inward man, and doth refresh you;
which draws you in love to forsake the world,
and that which hath form and beauty in it to the eye of the world;
and hath turned your minds within, who see your houses foul, and corruptions strong,
and the way narrow and straight, which leads to life eternal; to you all I say,
wait upon God in that which is pure.
Though you see little, and know little, and have little, and see your emptiness,
and see your nakedness, and barrenness, and unfruitfulness,
and see the hardness of your hearts, and your own unworthiness; it is the light,
that discovers all this, and the love of God to you, and it is that which is immediate,
but the dark understanding cannot comprehend it.
So, wait upon God in that which is pure, in your measure,
and stand still in it every one, to see your saviour,
to make you free from that which the light doth discover to you to be evil.
For the voice of the bridegroom is heard in our land;
and Christ is come amongst the prisoners, to visit them in the prison houses;
they have all hopes of releasement and free pardon, and to come out freely,
for the debt is paid; wait for the manifestation of it,
and he that comes out of prison shall reign.

So, meet together all ye that fear the Lord God, and think upon his name,
his mercies endure forever; his mercies are in temptations and troubles,
his mercies are in afflictions, in reproaches, and in scorns.
Therefore rejoice, ye simple ones, who love simplicity,
and meet and wait together to receive strength and wisdom from the Lord God;
and in departing from sin and evil, ye will be able to speak to the praise of the Lord.
And meeting and waiting in his power, which ye have received,
in it all to improve your measure that God hath given you;
for ye never improve your measure, so long as ye rely upon any visible thing without you;
but when ye come alone to wait upon God,
ye shall every one have a reward according to your deserts, and every one your penny,
who are called into the vineyard to labour.
Therefore be faithful to God, and mind that which is committed to you,
as faithful servants, labouring in love; some threshing, and some ploughing,
and some to keep the sheep.
He that can receive this let him.
And all to watch over one another in the spirit of God.
So God Almighty bless, guide, and prosper you unto his kingdom,
where there is no tribulation.
When your minds run into any thing outwardly, without the power,
it covers and veils the pure in you.

G+++.+++ F.

[.centered]
=== Letter 17.

Dear Friends,

Prize your time, and the love of the Lord to your souls above all things;
and mind that light in you, that shows you sin and evil.
Which checks you, when you speak an evil word, and tells you,
that ye should not be proud, nor wanton, nor fashion yourselves like unto the world;
for the fashion of this world passeth away.
And if ye hearken to that, it will keep you in humbleness of mind,
and lowliness of heart, and turn your minds within, to wait upon the Lord,
to be guided by it; and bring you to lay aside all sin and evil,
and keep you faithful to the Lord; and bring you to wait on him for teaching,
till an entrance thereof be made to your souls,
and refreshment come to them from the presence of the Lord.
There is your teacher, the light, obeying it; there is your condemnation, disobeying it.
If ye hearken to the light in you, it will not suffer you to conform to the evil ways,
customs, fashions, delights, and vanities of the world; but lead you to purity,
to holiness, to uprightness, even up to the Lord.
Dear hearts, hearken to it, to be guided by it.
For if ye love the light, ye love Christ; if ye hate that, ye hate Christ.
Therefore in the name of the Lord Jesus Christ consider of it;
and the Lord open your understandings to know him.

G+++.+++ F.

[.centered]
=== Letter 18.

All dear Friends everywhere, who have tasted of the everlasting power,
and are made partakers of his divine nature, be faithful,
and dwell in that which is pure.
And take heed of the world`'s evil ways, words, worships, customs, and fashions;
neither let fair speeches draw you out,
nor hard speeches trouble you and make you afraid:
but fear the Lord God of heaven and earth, who by his mighty power upholds all things.
And be bold in the power of truth, and valiant for it upon the earth; treading,
triumphing over, and trampling all deceit under foot, inward and outward;
having done it in yourselves in particular, ye have power over the world in general.
And meet together everywhere, and keep the unity of the spirit,
which is the bond of peace; which circumciseth inwardly, and puts off the body of sin,
and baptizeth all into one body with one spirit.
And being written all in one another`'s hearts, have all one voice,
and the pure language of truth, where in all plainness of speech,
things may be spoken in nakedness of heart one unto another,
in the eternal unity in the one spirit, which draws off and weans you from all things,
that are created and external, (which fade and pass away,) up to God,
the fountain of life, and head of all things; to whom be glory, wisdom, riches,
and honour, God blessed forever!
Who hath blessed us, and given to us eternal life, and this life is in his son;
and he that hath the son, hath the Father also.
And that which the world doth profess and make a trade withal,
the saints do enjoy and possess; which the world doth not know, but in the letter.

And all Friends and brethren, in what ye know, be faithful,
rejoicing and praising the Lord with all thankfulness, that the wise God should call you,
and elect you.
Oh! dwell in love in your hearts to God, and one to another!
And the God of love and life keep you all in his power, and love, and spirit to himself,
that ye may all be kept pure, and stand pure and clean before him.
The work and harvest of the Lord is great.
My prayers to God are for you, that ye may be faithful, and be kept faithful in the work.

G+++.+++ F.

[.centered]
=== Letter 19.

Dear and tender Friends,

My love is to you all in the truth of God; and my prayers and soul`'s desire are to God,
that ye may he kept in the simplicity of the truth in Christ Jesus,
growing up in the power of his resurrection, and be made conformable to his death,
and have fellowship with him in his sufferings;
and that all your hearts may be knit together in love, and in one spirit to God,
and be kept out of all the world`'s evil customs, fashions, words, works, manners,
ordinances, and commandments, which will all perish,
which the world holdeth up in the carnal mind, and the carnal man doth act them.
For whatsoever is seen with a carnal eye, is carnal.
See, if ye do find something in your understandings made manifest, which is eternal,
to guide your minds out of all external things, which wither away, and fade.
For the cross is to the carnal mind;
your carnal minds going into the carnal and earthly things,
or your eyes and lusts into the earth, where lightness, rashness, crossness, bitterness,
and presumption are, then the tongue will run at random, and is at liberty;
and he that hath not power over his own tongue, his religion is vain,
and the light mind ruleth.
But the light within, which doth convince thee, will show thee,
when the mind goeth forth; and show thee the daily cross,
which is to crucify that carnal mind; for the carnal mind minds carnal things;
and the cross is to the will of man, for it shall never enter.

Therefore give not way to your wills,
nor busy yourselves nor minds with needless and careless words, or such things,
for they will veil you, and draw your minds from God.
But keep within.
And when they shall say, "`lo here,`" or "`lo there is Christ,`" go not forth;
for Christ is within you.
And they are seducers and antichrists,
which draw your minds out from the teaching within you.
For the measure is within, and the light of God is within, and the pearl is within you,
which is hid; and the word of God is within you, and ye are the temples of God;
and God hath said, he will dwell in you, and walk in you.
And then what need ye go to the idols`' temples without you?
The true church (the saints) is in God; but the imitation of the church is in the world,
without God.
The seducers are in the world; antichrists and deceivers are in the world,
and false prophets are in the world; and covetousness is in the world; and all hypocrisy,
and all heresy, and dissimulation, and all pride, and looking for honour is in the world;
and he that seeketh for it, is of the devil.
And all idle, foolish jesting, and all light, vain talking,
which are not seemly nor convenient, are in the world.

Therefore lay aside all filthiness and superfluity of naughtiness, and fear God,
and give glory to him, and worship not the beast;
for the beast and the false prophet must be cast into the lake of fire.
The true figures and types were outward, and visible to the outward eye and mind;
but the carnal mind is to be taken away, and destroyed.
For the figures did type forth the substance; when the substance was come,
the figures were taken away, and types were ended.
And the (false) imitations of Christ and of God are in the world;
and the vain worships of the world are the worships of the beast, and are not of God.
For "`God is a spirit; and he that worships him, must worship him in spirit and truth.`"
The beastly nature in man and woman holdeth up the beast, and his customs and worships;
and the plagues of God are to be poured upon the beast,
and all them that worship the beast and false prophet.
And they that abide in the truth, worship not the beast inwardly, nor outwardly,
but deny all the beast`'s worships and false prophets`',
and worship God in spirit and truth.
And they which do not abide in the truth, hold up the beast`'s worship,
and the false prophets`'; and they that do so, shall have their portion together.
Plagues will be poured upon such.

And ye that know God, dwell in the truth, and tread upon the deceit;
for God will be glorified alone.
To whom be glory and honour forever!
Amen.

G+++.+++ F.

[.centered]
=== Letter 20.

To all my dear brethren, whom the God of power hath enlightened with his eternal light,
and discovered unto you his way of truth, and brought you out of the dark ways,
wherein ye have walked; which dark ways all the world walk in.
But where the pure light of God is witnessed, it guides to himself.
The light is but one, which leads out of darkness and the dark world,
into the world which is without end.
Therefore all Friends and brethren in the eternal truth of God, walk in it up to God,
and be not sayers only, nor backsliders; for the backslider is a sayer, and not a doer,
and there ariseth ambition, pride and presumption out of that nature.
But dwell in the pure light, which God hath made manifest to you in your understanding,
and turn your minds to him, and walk as children of the light, and of the day,
and be not drunken in any thing, nor run to extremes in any thing;
but be moderate and patient.
Wait for the presence of the great God, and our Lord and saviour Jesus Christ;
and he not so childish as to be tossed with men`'s words without life.
And run not out after others`' liberties, which they have got in their notions;
for thou that dost so, wilt not abide in the truth; and so thou mayst come to be shaken,
and shake others, who look at words.
But wait every one in particular, (in the measure that God hath given you,) upon God,
in the fear of God, then your hearts will be kept clean; and this is the sure way.
And wait all to have the son made manifest in you,
and the son alone to set you free in yourselves in particular;
and all that are made free by the son, are one.
But the first nature, that would have liberty, must go into captivity;
which they that live in their carnal reasoning, seek freedom for.
But here is man deceived in his first birth.

But ye all, in whom the immortal seed is brought to light,
who are raised up to sit in heavenly places with Christ Jesus,
and are become children of the day, walk as children of the day,
and as children of the light, and "`let your light so shine before men,
that they may glorify your Father, which is in heaven.`"
All loving the light, ye love the one thing,
which gathers your hearts together to the fountain of light and life; and walking in it,
ye have unity one with another,
and the "`blood of Jesus Christ cleanseth you from all sin.`"
The knowledge of the letter, which you formerly got into your notions and comprehensions,
the dark mind gave dark meanings to it, and so kept you in the broad way;
but now wait all to have the same spirit manifested in your understandings,
which was in them who gave forth the scriptures, who were come out of the broad way,
holy men of God, who had escaped the pollutions of the world.
And if every particular of you know not a principle within, which is of God,
to guide you to wait upon God, ye are still in your own knowledge,
which is brutish and sensual.
But waiting all upon God in that which is of God,
ye are kept open to receive the teachings of God.
And the pure wisdom and knowledge is that, which comes from above, which is to know God,
and Jesus Christ, the way, which is hidden from the world;
and to walk out of your own ways, and out of your own thoughts.
And dwelling in that which is pure, up to God,
it commands your own reason to keep silent, and to cast your own thoughts out:
and dwelling in that which is pure, it discovereth all this.
So dwelling in the spirit, it keepeth all your hearts to God.
To whom be all praise, honour, and glory forever!

G+++.+++ F.

From Judge Fell`'s in Lancashire, the 31st of 11th month, 1652.

[.centered]
=== Letter 21.

[.blurb]
==== To Friends at Kendal.

To that of God in you I speak, that ye may watch over the weak,
and see how the plants of the Lord grow.
And walk in the joy and love of the truth, serving God with joyfulness of heart;
and to you this is the word of the Lord.
And keep all that is bad, down and out with the light, which condemns all ungodliness;
so keep all that out, which is for condemnation; that ye may be preserved clean and pure,
that out of condemnation ye may be kept, and walk in the living light.
So God Almighty be with you all!
And I charge you to read this among the brethren, and these words mind with the light,
that no looseness be amongst you; but own and be obedient to the commands of the Lord,
that ye may stand out of, and above all the contrary commands of man.
And so farewell.

G+++.+++ F.

[.centered]
=== Letter 22.

O Friends! keep close to the light in you,
and do not look forth at words that proceed from a vain and light mind;
but at the power of words.
For the words of God, that proceed from him, are powerful and mighty in operation,
to the throwing down of all the strong holds of the man of sin.
The Lord is coming in power, to gather his chosen ones to himself,
and to judge and condemn the wicked one forevermore.
He will plague the beast, and burn the whore, and plague and torment the disobedient,
and rebellious, and backsliders very sore.
Therefore, ye that know the voice of the Lord, hearken to it,
and see how ye stand in his fear, and how ye are brought into the obedience of the truth.
And take heed of looking forth at man; but keep close to the light in you,
and see that your minds be kept close to that, and guided by that;
and being guided by that,
it will keep you clear and pure to receive the teaching of the Lord.
Have salt in yourselves, and let your words be few and seasoned, that they may be savoury.
And watch over one another in love, and walk in wisdom, and sobriety, and gravity,
and sincerity, in purity, and cleanness.
And keep free from deceit, and have no fellowship with the unfruitful words of darkness,
but rather reprove them.
And be faithful to the Lord; walk so that the world may be confounded and ashamed,
when they speak evil of you, as evil doers; walking in humbleness, lowliness,
and uprightness before them,
it will take away all just occasion of speaking evil against the truth.
And be bold and valiant for the truth, and press forward,
towards the mark of the prize of the high calling of God in Christ Jesus,
and let no man take your crown.

Dear Friends, watch over one another in love,
and stir up that which is pure in one another, and exhort one another daily.
And the Lord keep you all in his fear, and in his obedience now and evermore!

G+++.+++ F.

[.centered]
=== Letter 23.

Friends,

Fear not the powers of darkness, but keep your meetings,
and meet in that which keeps you over them; and in the power of God ye will have unity.

And dwell in love and unity one with another,
and know one another in the power of an endless life, which doth not change.
And know the second Adam, the Lord from heaven, which is above the first Adam,
the earthly, where all strife and transgression is.
And all Friends everywhere, be faithful in the life and power of God,
and keep your meetings (above all the world) in that which changes not,
that nothing but Christ may reign among you, the power of God, and wisdom of God,
the sanctification and redemption; that the just over all may reign,
and the seed of God may have the dominion in you all;
that with that ye may all be ordered to the glory of God, and kept in the bond of peace,
and reign in the love of God, (which is out of the iniquity,
and rejoiceth not in it,) which thinks no evil.
And have this love shed abroad in all your hearts, and feel it abiding in you;
which love of God edifies the body.
And know the word of God abiding in you, which was in the beginning,
and brings to the beginning; which word being ingrafted, it saves the soul,
and hammers down, and throws down, and burns up that which wars against it.

G+++.+++ F.

[.centered]
=== Letter 24.

To all Friends everywhere, dwell in the truth, and walk in the love of the truth,
in patience, and every one in your measure keep your habitations,
and learn that good lesson of Jesus Christ, to be low and meek in heart,
giving no occasion to the adversary by evil doing.
But walk all honestly and uprightly; for the upright and meek in heart know God,
and God delights in the upright and righteous.
And walking in uprighteousness, ye will be bold as lions,
resisting the wicked with your spiritual weapons, not by bloody hands,
as the wicked are tearing and rending the just that dwell in the truth.
For the lions want, and hunger, and rage; but ye that fear the Lord,
shall want no good thing; and they that wait upon the Lord,
he will` give them their hearts desire.
I witness the words of the Lord to be true, praised be his name!
Oh! Friends, dwell in the fear of the Lord, and take heed of presumption,
that your minds run not out into vanity and lightness,
that the world may not take occasion, and the truth suffer.
But every one keep your habitation where God hath called you; and take heed of deceit,
and form nothing in your own wills or minds, but grow up in the inner man,
(putting off the old man with his deeds,) as trees of righteousness,
which the Lord hath planted, growing in wisdom and understanding to do the will of God,
and not your own wills.
He that doth the will of God, abideth in that which endureth forever,
and seeth all flesh to be as grass, and the glory of the world to pass away.
Woe unto you proud men, who compass the earth,
to set your nests on high! all your gods of gold and silver must perish,
and that mind that holds them up must perish.
But all Friends, mind that which is eternal,
which gathers your hearts together up to the Lord,
and lets you see that ye are written in one another`'s hearts; meet together everywhere,
growing up in the spirit to the Lord, the fountain of life, the head of all things,
God blessed forever!
Let not hard words trouble you,
nor fair speeches win you but dwell in the power of truth, in the mighty God,
and have salt in yourselves to savour all words,
and to stand against all the wiles of the devil, in the mighty power of God.

For God hath raised up his own seed in his saints, which seed, Christ, is but one in all,
and spreads over all, and throughout all;
and we now are through him come to have dominion and power over the evil one,
and to tread upon that which hath been too strong for us, the enemy of our peace,
and the enemy of our unity with God and one with another.
So in that, which is raised up in us, which trampleth upon the earthly, dark power,
have we unity with God, and fellowship with his son, and unity one with another;
so are known to one another in that, which none, who are of the world, knoweth.
So our life is hid, and our happiness, joy, and delight hid from all,
who are ruled and governed by the prince of the air,
from under whose dominion and government we are redeemed
by the only redeemer Christ Jesus,
not with corruptible things, neither is our redemption of man, nor by man,
nor according to the will of man, but contrary to man`'s will.
And so, our unity and fellowship with vain man are lost,
and all his evil ways are now turned into enmity;
and all his profession is now found to be deceit,
and in all his fairest pretences lodgeth cruelty;
and the bottom and ground of all his knowledge of God and Christ is found sandy,
and cannot endure the tempest.
For being brought off from that foundation, and having suffered the loss of all,
which seemed beautiful upon the sand,
(which was there builded according to that wisdom which was not eternal, but was earthly,
upon which the curse of God was, and yet doth remain,
where it is standing,) we declare against that bottom and foundation,
by the power of God, in that light of Christ, which discovers all false foundations,
and makes manifest all sandy bottoms, which man hath builded upon.
For where the only true seed takes root,
there all man`'s plants and plantations are plucked up; for there the earth,
in which the earthly plants grow, is broken up, ploughed up, and ripped up,
and all things made manifest, which have lain hid in it.
For in the earth dwell all the noisome creatures, and the evil beasts,
which are hurtful to the creation: for in the earth the devil dwells and walks;
but the earth being ploughed up, he is made manifest,
and the seat of his dwelling is broken up.
That mind, which doth speak of God, but lives not, dwells not,
nor abides in the fear of God, that mind must suffer, and pass under the judgment of God,
for the curse of God is upon that mind: for that mind is earthly, and of the earth,
upon which the curse of God is.
And that mind may talk of God, and speak of God, but not in union with God,
nor from enjoyment of God in the spirit,
nor from having purchased the knowledge of him through death and sufferings;
but from hear-say of him, and from custom and tradition.
But the true fear of God doth destroy that mind, which speaks of him,
but doth not live in his fear: and that mind is raised up, which doth abide in his fear;
and this is acceptable sacrifice, which is pure, clean, holy, and without spot.
Then that which knows God, speaks of him,
which hath purchased the true knowledge of him through suffering;
and to such there is no condemnation, but joy and peace.
And this mind sings true praises to God, the other in hypocrisy;
and therefore the woe is unto it.
And this mind is stayed upon God, the other is gadding after the creatures,
committing fornication with other lovers; and speaks of God, but is not subject to God,
and must pass through condemnation.

G+++.+++ F.

[.centered]
=== Letter 25.

[.blurb]
==== To Friends in the Truth.

Friends, the love of God is to you, the springs are opening,
and the plants are refreshing with the living waters.
Now friends, walk in the truth, as ye have received it;
and wait in that which keeps you in the yea and nay, in the pure communication,
in the good manners.
In the pure conversation over all the world ye will reign,
whose conversation is in heaven; and here the world ye will judge, walking in the life.
And ye which turn from the light, which Jesus Christ hath enlightened you withal,
here are the corrupt manners, the evil communication, the filthy conversation,
which with the light are all to be condemned.
Ye which turn from the light, are in Esau`'s nature, and choosing the earth,
there is profaneness: therefore take heed to the light,
and wait to receive power from God,
to stand against that which the light discovers to be evil.
And ye who are turned from the light, which Jesus Christ hath enlightened you withal,
and do turn to the hireling priests who are changeable,
from the priest who never changes, ye walk in Judas`' steps, and woe will be your end;
ye had better never have been born, ye are betrayers of the just.
Ye that turn from the light, ye turn from Christ, as Judas did;
and ye that walk in the light, ye walk after Christ, and he is your way;
but ye that turn from it to the hireling priests, Judas is your way,
which is destruction.
And ye that turn from the light, turn from the command of God; Cain is your way.
And ye that turn from the spirit, Balaam is your way.
And ye that get up into presumption, Korah is your way, which leads into self-separation.
And this fruit will wither, which is natural knowledge, which is seen with the light,
and is to be condemned with the light, which never withers,
which is the condemnation of the world; which all the children of the light walk in.
Walking in which light, it will bring you to receive Christ, from whence it comes.
Here is the way to salvation; and as many as receive him,
to them he gives power to become the sons of God.
And the son of God is but one in all, male and female; and the light of God is but one.
So all walk in it, to receive the son; in which light is the unity,
which brings to fellowship with the Father and the son.
And the oneness is in the light, as the Father and the son are one,
and brings you to where he is, out of the world, from the world,
and not to be of the world.
Therefore walk in the light, which is all the world`'s condemnation,
even them of the highest religion, who act contrary to the light.
And to you this is given forth from the word of the living God.
And thou that lovest thy soul, love the light, to wait for Christ,
the saviour of thy soul: and ye that hear the word, wait in the light,
which comes from the word, which leads up to the word which was in the beginning,
which breaks the world to pieces that lies in wickedness, and burns it as with a fire;
and divides asunder the precious from the vile.
This is the word, which makes all clean, which is received into the heart;
and this is the word of faith which we preach: and the world preaches the words without,
being out of the life, and in the brutish knowledge, which is condemned of God,
and by all who are of God, that have (and are in) the life of the holy scriptures.
Therefore I charge you all in the presence of the living God,
to wait in the light which comes from Christ, that with it ye may receive the life;
that with the light and life, which are one,
ye may come to have the scriptures opened to you, which were given forth from the light.
And so all the world, who have not the light guiding their understandings, nor the life,
but are strangers to it, there are the sects, there are the many opinions,
there is the heresy, which makes a profession of the letter declared from the night,
but are out of the life; with the light all this is condemned:
and the children of light are in unity, in that which gave forth the holy scriptures.
And so to you all this testimony is from the word of God.

This is to be read among all Friends everywhere; for this was I moved to send among you.

G+++.+++ F.

[.centered]
=== Letter 26.

[.blurb]
==== Concerning Marriages.

Friends,

All they who act contrary to the light which comes from Christ Jesus, and hate it,
whose deeds are evil, and live in strife about words,
and their minds are in earthly things, defrauding and wronging one another,
they know when they do so, with the light which comes from Christ Jesus.
So this light, which lets them see and know, when they act contrary to it,
with this light are they condemned.
And all that do act contrary to the light,
and do join together in marriage contrary to the light,
and are joined with that which is contrary to the light, this is their condemnation,
the light, which leads to God.
But who are joined together with the light, are joined together in God;
and let no man put them asunder.
Here is the true joining; and there will be a clear testimony unto them,
that God did move and command, and join them with his light,
among all the children of light; and this marriage is honourable,
and the bed not defiled.
And whom God doth move, and command, and join together, it was and is by his power.

G+++.+++ F.

[.centered]
=== Letter 27.

To all my dear Friends and brethren everywhere.
He that hath the son of God, hath life; all that have not the son of God, have not life.
The son of God is he which makes free from all sin,
and is come to destroy the works of the devil, and to make us conformable to his image,
and the image of the devil to deface and destroy, and the image of God to renew us up in;
and so to bring us to walk in righteousness.
Praises be unto the glorious God forever, who has sent his son into the world,
to take away the sins of the world.
The lamb of God, the son of God, is but one in all his males and females,
sons and daughters, and they all are one in Christ and Christ one in them all.
And all Friends, walk worthy of your calling in all holiness,
for holiness becomes the saints; without holiness no man shall see the Lord.
And every one improve your talents, labouring in the vineyard,
dressing the Lord`'s vineyard, that ye may be found the faithful servants,
who are as good servants, and walking all in love to God, and one to another.
And know one another in the spirit which is immortal;
for all other knowledge in the flesh veils the pure, and hinders your discerning.
There will arise tares out of that ground, whence that love springs.
Therefore dwell all in the pure spirit of God, and walking therein,
it will teach you every one in particular, to know God the Father of spirits,
and all to stand naked and bare, and uncovered before the living Lord God.
For woe is to every one, that is covered, but not with the spirit of the Lord;
and who are covered, and not with his spirit, will not stand in his counsel.
But all ye who are uncovered, walking in the spirit of the Lord God,
it will keep you all in his counsel to stand uncovered before the Lord, bare and naked,
to receive instruction and counsel from him.
So God Almighty be with you all!
The dew of heaven is falling upon you to water the tender plants;
and the blessing of God be amongst you, which showers down amongst you!
The heavenly joy fill your hearts, and comfort you in the inward man in all tribulations.
The glorious light is shining, the immortal is bringing forth out of death,
the prisoners have hope of their pardon, the debt being paid,
and they freely purchased by Christ`'s blood, and he into the prison houses is come,
that the prisoners begin to sing in hope of their eternal freedom,
for joy of heart leaping, and the dumb tongue shall sing praises.
And the arrows of the Almighty are shooting against the wicked.
Therefore be bold and valiant for the truth, triumph over all the deceivers,
and trample upon their deceits.

G+++.+++ F.

[.centered]
=== Letter 28.

To all you, that are enlightened with the light that comes from Jesus, to it take heed,
which leads into the right course of nature, which who act contrary to it,
go out of the right course of nature into drunkenness, rashness, lying, blaspheming,
deceit, and uncleanness.
All this is out of the right course of nature,
and leads out of the right course of nature, and destroys it,
and is to be condemned with that which leads to the glory of the first body,
and leads nature into its right course and right being, which man was in before he fell.

G+++.+++ F.

[.centered]
=== Letter 29.

[.blurb]
==== Concerning Tithes.

Friends,

The counsel of the living God to you all is,
that ye may come to discern the ministers of God
and Christ from the ministers of the world,
that have gotten the scriptures for their cloak, and with them make a colour to deceive,
and tell you, "`that they are the ministers of Jesus Christ,
and Christ hath sent them;`" who sue you at the law,
and hale you before magistrates for tithes and maintenance, when they do you no work,
nor have ye hired them.
Yet they come and tell you, "`the workman is worthy of his meat,
and the labourer is worthy of his hire.`"
Here the custom of sin hath taken away the sense; they are so accustomed to it.
But praised be the Lord God, who hath given us his light, and with it all such are seen,
comprehended, and judged; and to such we cannot give tithes, nor hire, who do us no work,
whom we have not hired; for it is contrary to scripture and Christ`'s doctrine,
and to that of God in our consciences.
It is not for the saving of the earth (for it is the Lord`'s,
and the fulness of it) that we do not pay the priests`' tithes; for if we should,
we should uphold the first priesthood, and its office, who had their storehouses,
to put the tithes into that were given them; and then all the widows, fatherless,
and strangers came, and were to be filled in the priest`'s gate,
and the priests were to minister it out of the storehouse;
as ye may read in Malachi and the book of Moses, who received a law from God,
and gave it forth to the priests to receive tithes.
So with the light, which Christ Jesus hath given us, with it we come to witness him,
the unchangeable priest, and see the change of the first priesthood,
and the change of the law also, by which the priest received the tithes;
as ye may read Heb.
vii. So we do witness the new testament, and the new covenant,
and the everlasting priest,
(praised be God!) and do confess Christ Jesus come in the flesh.
And all ye that would have us to give priests`' tithes, and would compel us so to do,
ye are they that do oppose Christ`'s doctrine and commands to his disciples,
"`Freely ye have received,
freely give;`" and do not own the unchangeable priest`'s being come to teach his people:
ye are against the unchangeable priest`'s office; ye are against the new covenant,
and new testament.
And so we cannot uphold tithes, and such as take tithes,
who act against Christ Jesus`' commands, and deny him to be come in the flesh, in life,
doctrine, and power.
So, we that suffer our goods to be spoiled joyfully, it is for Christ`'s sake,
the unchangeable priest, and for the new covenant`'s sake, and the new testament`'s sake.
As the Hebrews did, who suffered their goods to be spoiled joyfully,
and were a gazing-stock; and so we suffer now by the changeable priesthood,
which takes tithes, as the people of God did then.
But if we hire any man, and set him at work, we will give him his wages and his meat;
but such dissemblers, as say, the scripture is their rule for it,
and we neither hired nor set them at work, all such deceivers are denied,
who take the scripture words, and make a cloak of them for their covetous practices.
Nevertheless, if any minister of Jesus Christ, or son, or daughter, or servant,
which Jesus Christ sends forth, (who said, "`Freely ye have received,
freely give,`") comes to our houses, and ministers unto us spiritual things,
we will set before him our carnal things; and he that soweth unto us spiritual things,
it is the least, that we minister unto him of our carnal things.
But he that sueth us at the law for means, and calleth me before courts and sessions,
and telleth me, he is a minister of Christ, and Christ sent him,
all such evil beasts (as the apostle speaks of) we deny, who mind earthly things,
whose god is their belly, who serve not the Lord Jesus Christ, but their own bellies.
But if any one come into our houses, (as aforesaid,) to preach the gospel to us,
we shall set before them, and they shall eat freely, as Christ saith,
"`Whatsoever they set before you, that eat.`"
But to give tithes to such as do not preach to us spiritual things,
but deny Christ come in the flesh, and hold up things in the figure, all such we deny;
and for the truth`'s sake do we suffer by such.
And ye that have bought tithes to get gain thereby, to you we cannot pay tithes;
ye are as bad as the priests to hold up such things, as were acted in the figure,
and deny Christ come in the flesh.
And though ye may say, give Caesar his due, for a cloak, that cloak we deny.
Nevertheless, if we be owing any thing to Caesar, or to any ruler, or magistrate,
or minister, he shall have his due.
So, Caesar shall have his due in his place; and the figure we own in its place,
and Christ in his place.

G+++.+++ F.

[.centered]
=== Letter 30.

[.blurb]
==== To a suffering Friend.

Dear John, the everlasting arm of the Lord hold thee up, and break all thy bonds asunder,
and set thee upon the rock on thy feet, in which thou mayst know his presence,
and his everlasting, supreme power.
And so the God of life be with thee!
And pray for thy enemies, for the Lord to open them and their hearts,
and see themselves and thee.

G+++.+++ F.

[.centered]
=== Letter 31.

Dear Friends,

Mind the steadfast guide to the Lord, where we do all meet in the eternal spirit,
in oneness, all being baptized by it into one body, having one food,
the eternal bread of life, which the immortal feed upon,
and all made to drink into one spirit,
which is the cup of the communion of the blood of our Lord Jesus Christ,
which makes perfect, and redeems from all that is vain, fleshly, and earthly, up to God,
who is holy, pure, spiritual, and eternal.
And let not any of you in your desires wander from that which is pure in you;
then your conditions will be kept clear and pure to see all things as they are,
and a clear separation will be made from that which is of man, and of your own,
and that which is of God; and there will be a growing up in that which is pure.
And so, be low in your minds, waiting for the coming of our Lord Jesus Christ in you all,
who is Lord over all, to be Lord over all in you.
And so the Lord God of power keep you all!
Farewell.

G+++.+++ F.
