== Letters 107 &#8212; 132

[.centered]
=== Letter 107.

My dear friends,--In the power of the everlasting God,
which comprehends the power of darkness, and all the temptations in it,
in that power of God dwell,
which will keep and bring you to the word which was in the beginning,
which will keep you up to the life, and to feed upon the same,
over the power of darkness.
In that ye will find strength, and feel dominion and life, and that will let you see,
before the tempter was, and over him; and into that the tempter cannot come,
for the power and truth he is out of.
And in that life dwell, in which ye will know dominion.
And therefore, let your faith be in the power, and over the weakness and temptations,
and look not out at them; but look in the light and power of God at the Lord`'s strength,
which will be made perfect in your weakest state.
And look at the grace of God in all temptations, to bring your salvation,
which is your teacher to teach you; for when ye look or hearken to the temptations,
ye go from your teacher, the grace of God, and so are darkened.
The grace of God is sufficient in all temptations to lead out of them,
and to keep over them.

G+++.+++ F.

[.centered]
=== Letter 108.

Friends, wait in the light,
that with the light every one of you may come to see Christ to be your wisdom,
and your righteousness, and so come to see the body, his church, of which is the head:
and in the measure of life waiting on the Father of life,
ye may come to reign in the life.
All that are kept there, are in pure joy and love.
And in the light wait, that ye may see the harlots and idolaters,
etc. which are to be fed with judgment.
Spare not that which is for the sword, and for the fire;
let all fleshly-mindedness be trodden under your feet.
And standing in the power, ye will see the seed slaying the fat,
and chaining and binding the unruly, and succouring all the lambs and babes.
This is the word of the Lord to you.

G+++.+++ F.

[.centered]
=== Letter 109.

[.blurb]
==== Concerning judging.

Friends, keep to patience: this is the counsel of the Lord to you.
Do not judge one another behind one another`'s backs, nor speak evil one of another,
for that is that which soweth the enmity among brethren.
Nor judge one another before the world, for that is that which is in the extremes,
passion, and hastiness; and there ye let in the world`'s spirit to rejoice over you,
and that is out of the patience, and love, and wisdom, and fear of God and his truth.
And every one dwell in the seed and life of God, and in that know one another,
and meeting together in that ye may see the Lord Jesus in the midst of you.
And, friends, go not into the aggravating part to strive with it,
lest ye do hurt to your souls, and run into the same nature;
for patience must get the victory, and answers to that of God in every one,
which will bring every one from the contrary.
So let your moderation, and temperance, and patience be known to all,
for that which joins to the aggravating part, sets up the aggravating part,
and breeds confusion, and reaches not to the witness of God in every one.
And Friends, keep out of the worldly wise part,
for that will never let people join and unite together
(in truth) which enters into the earth,
and the apprehensions of words; but let innocency be the garment,
and truth and simplicity the covering.
Then in the innocency ye will have unity, where there is no evil thought,
but love that thinks no evil.
Therefore cover one another`'s nakedness; let all things be done in love,
and that will edify.
And let the weight and preciousness of truth be in your eye,
and esteemed above all things by you.
For here is my grief, when I hear any thing amongst Friends, that hinders their unity,
and makes a breach, (whereby the wrong gets ground,) who should live in the seed,
which breaks the bond of iniquity, and makes up all breaches; in which seed shine,
answering the witness of God in every one,
which bruises the earthly part under that brings forth briars and thorns,
and spreads over the world, and all the contrary.
Therefore all ye, which have known the power of the Lord God,
and have tasted of the seed of God, live in that in which ye come to have unity;
that that part may be kept down.
And the wrong eye, that looks out at one another`'s weaknesses, that must be kept under,
even that, where the heat, and the burnings, and the enmity is;
the seed of God atop of all that must be set, in which is the unity.
Therefore, if there be any nakedness in any, or among any, cover that,
and come all to the seed of God in your own selves; for in that is the virtue to heal,
yea, all nations.
Slaughterings, wounds, and cuttings are the other weapons in the other part,
which is out of the seed of God whose end is peace; in which is the unity,
which is the top-stone over all the enmity, and atop of it is laid,
and bruiseth it all down.

I am a lover of your souls`' eternal good, peace, and unity,
in the kingdom that stands in the power which hath no end.

G+++.+++ F.

[.centered]
=== Letter 110.

[.blurb]
==== To the prisoners at Exon.

Friends, mind that which keepeth you all meek and low, to be guided with it.
And all consider that which keepeth you in the way of peace;
that none of you may be puddling in your own carnal wisdom, which is to be confounded,
which is shut out of the kingdom of God.
All wait to have dominion over that, that ye may know peace and unity,
and the love of God, that doth not change.
And do not strive one with another, lest ye hurt one another;
for it is not the hasty spirit that gets the victory, but the lamb,
who must reign over the world, and was before it was.
And the mind which is forward, judge, and dwell in the peaceable way;
and that ye may be patterns in your imprisonments to them
which be out of the image of the son of God.

To the prisoners in Exon; written whilst J. N. was there, with many more in prison.

G+++.+++ F.

[.centered]
=== Letter 111.

[.blurb]
==== A warning from the Lord for plainness of speech to be used. (To go among Friends.)

Friends of God and brethren,

This is a warning to you all from the Lord God and Jesus Christ, that all that ye speak,
it may be in plainness of speech, according to that of God in all consciences,
and that it may proceed from that of God in you, the light of Christ;
that all your words be words of life to the life, and death to the death,
where it reigns above the light.
And that all words, which are spoken, be in plainness of speech;
that the light of Christ in all consciences, which he hath enlightened every one withal,
may witness your words to be the words of life: so that dwelling in the light,
to that of God ye may be made manifest in all consciences;
which shall be their condemnation that hate it.
Ye that dwell in the light, and walk in the light,
use plainness of speech and plain words, single words in the single life,
pure words from the pure life, seasoned words, seasoned with grace,
which teacheth to deny all ungodliness and worldly lusts.
They who live in ungodliness and worldly lusts,
turn from the grace of God into wantonness, who are light and vain,
whose words are unsavoury, not seasoned with grace, whose words edify not;
upon whom God will render vengeance in flames of fire,
who shall be separated from his presence and his angels.
Therefore, friends, in plainness of speech all dwell; for dwelling in the light,
it will bring you to plainness and few words, to live in the life,
which gave forth the scriptures, which was before the scriptures were given forth;
and with it ye will see their conditions that dwelt in the life,
and gave forth the scriptures.
And with this light ye will see their conditions who were testified
against (who were out of the life) by them who dwelt in the light;
and with it all that comes to be seen, read, and understood,
which was given forth with the life and from the life;
and all comes to be known in plainness, and is with plainness spoken forth again.
Which comes not by the will of man:
for no prophecy of the scripture came by the will of man;
all the prophecies in it were out of the will of man:
and they witnessed and prophesied of Christ, who was born not by the will of man;
who was supposed to be the son of Joseph, but was the son of God.
And all the apostles were made ministers by the will of God, and not by man, nor of man,
but by the will of God; and so they witnessed Christ,
who was not born by the will of man, who were made ministers not by the will of man:
and they witnessed that no prophecy of the scripture in old time came by the will of man,
neither was it of any private interpretation;
but holy men of God spake it as they were moved by the holy ghost, the holy mover,
which is but one.
And all who are in their own wills, and have the scripture,
and make a feigned profession of that,
(which came not by the will of man,) are in the presumption;
and with the light of Christ,
which he hath enlightened every one that comes into the world withal,
with that light shall they be condemned, even all that hate it,
and live in their own wills.
And so the unity of the saints is in that which condemns the world:
and all who live in their own wills, and yet make a profession of the scriptures,
there are the sects and opinions, and there is no unity,
and they have not unity amongst themselves; but only a oneness in nature,
though not in unity in their meanings of the letter.
That which comes not by the will of man, but is contrary to his will,
and contrary to all the world`'s evil ways, and overturns them,
which is according to that of God in all consciences, with that have unity;
which testifieth against every man, when he acts contrary to it,
and with it he shall be judged, and condemned in his own knowledge and understanding.
And ye all walking in this light,
it will bring you to all plainness and singleness of speech;
which will make the deceit to tremble, and the mystery of iniquity to shake,
which lodgeth in the temple and sits there, where it ought not to sit,
and is exalted above all that is called God: now,
with the brightness of his coming is he discovered,
and with the breath of his mouth he is to be consumed.
So dwell all in the eternal power of God, and in his pure light,
that ye may be a terror to all evil doers, and to all ungodliness,
and to all who act unrighteously, and live in uncleanness.
And so ye will come to use plain words and plainness of speech to them all,
and no flattery shall dwell in you, no enchanter nor witch shall live,
no hypocrisy shall stand before the judgment seat of God; but shall be as the chaff,
driven to and fro; that the scripture may be fulfilled upon them.
And all who are out of plainness, with the eternal light,
which Christ hath enlightened them withal,
shall they be condemned and confounded in time: for this light was before time,
and is in time, which lets every man and woman see all their actions done in time;
and hating this light, this is their condemnation.
But all loving this light, and walking in this light,
ye will come to walk in that which is the world`'s condemnation;
and it will bring you to see the world to be gone from God, from Christ,
and all who are of God.
And this is the counsel of God to you,
that in that which is contrary to your fleshly wills, ye may all wait and walk,
for that will lead you from all vain thoughts, and all evil desires; there wait,
and ye will witness the birth born, not by the will of man:
and this birth is heir of another world, and heir of the certain riches,
which is manifest to that of God in all consciences.
So to you all this is a warning from the Lord, who are in the light, and love the light,
which Christ Jesus hath enlightened you withal, which is contrary to your wills,
and all men`'s wills; that with it ye may use plainness of speech to all,
and so to be made manifest to that which they hate, which is their condemnation,
the light.
And abiding in Christ, who is the vine,
every one will come to witness yourselves to be as branches abiding in the vine,
and sitting under the vine.

This was I moved of the Lord to send out abroad among you,
as a message to all the plants of the Lord.

If ye speak any thing contrary to the light, which Christ hath enlightened you withal,
with the light ye are to be condemned.
And if any among you do speak of former experiences, and not dwell in the light,
but in hypocrisy, and presumption, and envy, without the fear of God,
ye are to be thrown down, and with the light condemned;
and woe upon thy head from God and Christ proceeds, and art to be turned out,
and judged with the light and with the life!
Therefore in the life dwell and walk every one in particular;
then ye will have unity one with another, and grow up to be trees of righteousness,
the planting of the Lord.

G+++.+++ F.

[.centered]
=== Letter 112.

All Friends, mind the light, and dwell in it, and it will keep you atop of all the world;
and the seed of God mind, and know it, and in it be content.

Dwell in the seed, which is heir of the promise of life eternal,
and dwell in the possession of that.
And in all your doings (and words) be faithful to the Lord, and to men;
let this be your daily exercise.

G+++.+++ F.

[.centered]
=== Letter 113.

[.blurb]
==== To a Friend in the ministry.

Dear brother, mind the Lord, and stand in his will and counsel.
Look not forth at time nor place, but at thy Father`'s house, wheresoever thou art.
And dwell in the pure measure of God in thee,
and there thou wilt see the Lord God present with thee.
For the bringing forth many out of prison, art thou there set; behold,
the word of the Lord cannot be bound.
The Lord God of power give thee wisdom, courage, manhood,
and boldness to thresh down all deceit.
Dear heart, be valiant, and mind the pure spirit of God in thee,
to guide thee up unto God, to thunder down all deceit within and without.
So farewell.
God Almighty keep you all.

G+++.+++ F.

[.centered]
=== Letter 114.

Dear brethren, in the mighty power of God go on,
to which power of the God of heaven and earth, all the powers of the earth must bow;
that to that of God in all consciences ye may be made manifest,
that that in them which is of God may witness that ye are sent of God.
Dwell in the life of God, that to the spirits in prison ye may minister,
and to it be made manifest, that ye are no deceivers, but saviours,
and such as are sent to lead from all deceivers, and to testify against them.
So, in the mighty power of God go on preaching the gospel to every creature,
and disciplining them in the name of the Father, son, and holy spirit.
In the name of Christ preach the mighty day of the Lord to all
the consciences of them who have lain long in darkness,
(and under its chain,) where the light shined, but the darkness could not comprehend it.
So, in the power of the Lord God go on,
and thresh that which hath been fed with the harlot`'s spirit, and the harlot famish,
which hath and doth prison the just.
I charge you in the presence of the living God, dwell in his power,
that with his power ye may be carried along to minister
to all the spirits imprisoned by the deceit.
As the life of God doth arise, it will lead you up to God, the Father of life;
in this your fruits shall never wither.
But go on to plant a vineyard, and to plough, that ye may eat the fruit thereof;
and to plant in hope, and to thresh in hope, that ye may be made partakers of your hope.
And to thresh out the corn, that the wind may scatter the chaff,
that the corn may be gathered into the barn.
So, in the power of the Lord Jesus Christ preach the everlasting gospel,
that by his power the sick may be healed, the leprous cleansed, the dead raised,
the blind eyes opened, and the devils cast out.
In the name of the Lord Jesus Christ go on,
that that of God in all consciences may witness, that ye are sent of God, and are of God;
and so according to that speak, to bring up all unto the head Christ,
and into the life which gave forth the scriptures; for there is the unity,
and out of it is the confusion.

G+++.+++ F.

[.centered]
=== Letter 115.

[.blurb]
==== To Friends, concerning the word of life.

Friends and brethren, the eternal word,
from which ye have both spoken and ministered to others, is the word of life,
the word of peace, the word of reconciliation, which makes of twain one new man;
and if ye do abide there,
there is no division but unity in the life which was before death was,
and before division was.
Therefore that which is divided is of the kingdom that cannot stand,
and is for condemnation by the life and word of reconciliation.
That which speaks the evil language I do deny;
for that which speaks so doth not see thoroughly.
Therefore in the light wait, where the unity is, where the peace is,
where the oneness with the Father and the son is, where there is no rent nor division;
but all one in Christ Jesus, the everlasting fountain of life and covenant of peace.
The son of man cometh not to be ministered unto, but to minister.
Where the life and fulness dwells it hides and covers from that to which the curse is;
that so it may minister forth to the seed`'s seed.

Sound, sound the trumpet abroad, ye valiant soldiers of Christ in his kingdom,
of which is no end!
All the antichrists in the kingdoms (of fallen men) are up in arms against Christ.

G+++.+++ F.

[.centered]
=== Letter 116.

[.blurb]
==== Concerning judging in Meetings.

Friends, do not judge one another in meetings, ye that do minister in the meetings;
for your so doing hath hurt the people, both within and without,
and yourselves under their judgment ye have brought.
And your judging one another in the meetings hath emboldened others to quarrel,
and judge you also in the meetings.
And this hath been all out of order, and the church order also.
Now, if ye have any thing to say to any, stay till the meeting be done,
and then speak to them in private between yourselves,
and do not lay open one another`'s weakness;
for that is weakness and not wisdom to do so.
For your judging one another in meetings hath almost destroyed some Friends,
and distracted them.
And this is for want of love that beareth all things; and therefore let it be amended.
No more, but my love.

Friends, if any amongst you have movings to do any service for the Lord,
when they have done it let them return again with speed to their habitation,
and there serve the Lord in their generation; that no slothfulness may be amongst you.
But all keep in diligence,
that no occasion may be given to any "`to speak evil of
the truth;`" but that ye may answer that of God in all.
So give no offence; for woe is to those by whom offences do come.
Yet quench not the spirit.

G+++.+++ F.

[.centered]
=== Letter 117.

My dear friends, keep your meetings, and ye will feel the seed to arise,
though never a word be spoken amongst you.
And be faithful, that ye may answer that of God in every one.
And do not neglect your talent, but in the life and power of God live,
which ye have received.
And, my dear friends, dwell in the life, and power, and love of God,
and one towards another.

Friends, dwell in the measure of the spirit of God, and to it take heed,
that in it ye may grow; for the true and lasting love proceeds from God, who is eternal.
And abiding in the measure of life, ye will have peace and love, that never changeth;
if from the measure you turn iniquity gets up, and so the love waxeth cold,
and in that lodge the evil thoughts, jealousies, evil will, and murmurings.
Wait in the light, which is of God, that ye may all witness the son of God,
and witness that which shall never wither; so ye will see and feel God near.

G+++.+++ F.

[.centered]
=== Letter 118.

Let no Friends go beyond their own measure given them of God,
nor rejoice in another man`'s line made ready to their hands; lest that get up,
and would be justified, which is to be condemned.
And that which will boast, and be justified in the sight of men,
is out of the kingdom excluded.
Therefore in the measure of life wait,
and with it be led to have power over your own wills,
(which are mortal and changeable,) that the way of righteousness may be found,
where your wills are shut out, which causeth the hastiness and the strife,
to run into words without the life, where judgment and condemnation do overtake you.
Wherefore delight in judgment, which leads to the door of mercy.

G+++.+++ F.

[.centered]
=== Letter 119.

Friends,

Wait in the life, which will keep you above words, and keep your minds up to God,
the Father of life,
and condemn and judge all them which would have words more than the life.
God Almighty be with you in the measure of life, that in it ye may grow;
and with it your minds may be kept up to him, the Father of life.

And that all strife may be kept down with the life,
and all light spirits judged down with that which comprehends the world, and judgeth it.
So God Almighty be with you all, and keep you in his mighty power up to himself,
and condemn all that which is contrary to him and his light.

G+++.+++ F.

To be read at meetings.

[.centered]
=== Letter 120.

My dear friends, dwell in the everlasting seed of God,
in which ye all will feel life eternal, that never hath an end;
and in that meet and keep your meetings.
And dwell together in the love and life of God, with which ye may all be filled,
through which love ye may cover the multitude of sins, and answer the life of God in all;
in which ye may feel the blessings of the Almighty God covering you as with a garment.
And so live in the possession of the life;
in which ye all will have unity and fellowship with God, and one with another.

Dear friends, exhort all your families at times and seasons,
whether they be servants or children, that they may be informed in the truth.
For when ye were professors, many of you did exhort and instruct them in the form,
when that ye had not the power.
And therefore now being brought into the truth, ye should be more diligent to exhort,
admonish, and instruct them.

G+++.+++ F.

[.centered]
=== Letter 121.

[.blurb]
==== To Friends, to take care of such, who suffer for owning the truth.

Friends,

Dwell in the wisdom and power of God, by which all things must be ordered to his glory,
in which ye may do all things to his glory;
and that with the wisdom of God ye may order and preserve the creation,
and everything that is good.
And if any servants be convinced, and turned from their places for truth`'s sake,
Friends to be tender to them, that they be not lost; but that they may be preserved.
And if any soldiers be put out of the army for truth`'s sake,
that they may be nourished and cherished; or any children be turned from their parents,
or believing wives from their unbelieving husbands,
that they may be admonished to walk wisely towards them.
And that all prisoners, that have but little of their own,
there may be care taken for them, and for the lame and sick.
And that if any Friends be oppressed any manner of way, others may take care to help them.
And that all may be as one family, building up one another, and helping one another.
And if any desire meetings any way for truth`'s service, Friends not to look out;
but to dwell in the life and power of God, and therein to answer it.

And all Friends everywhere, in the power, and life, and seed of God keep your meetings,
that over all the top-stone may be laid,
and ye all in the wisdom and patience may be preserved,
and as a sweet savour may be kept to God, and in the hearts of all people.
And every one be obedient to the life and power of the Lord God,
and that will keep you from being as a wilderness; but be faithful and still,
till the winds cease, and the storm be over.

G+++.+++ F.

[.centered]
=== Letter 122.

Friends,

To that which is pure, I speak, in which is unity, where no defiled thing shall enter.
Silence all flesh, who strive about words, in which is no profit;
who would draw you out of your conditions, and others out of their conditions.
Therefore be low, and mind that which is low, to draw you out of contention.
And strive not for mastery, and do not exercise lordship over one another;
but mind that which is pure, which keeps you in the fear of the Lord God.
For if your minds go from that which is pure, which leads to God,
your nakedness will appear to the world; and then ye go in your own wills and strength;
and there is the seat for mastery and pride, out of the will of God,
and that is out of the unity, out of the oneness, out of the way;
and instead of building, ye destroy; and instead of edifying,
ye draw back into the world.
Therefore all be low, and wait upon the Lord, and be swift to hear, slow to speak,
and slow to wrath; be low, and wait upon God, to receive the living food from God,
to nourish you in time, with that which was before time;
that God in all things may be glorified.
So the Lord God Almighty direct you and bring down all fleshly wills;
that the pure may be raised up.
So meet together and wait upon God, if there be not a word, I charge you.
Beware of contention, for there ye get above that of God in the conscience,
and so go out of the fear of the Lord.

G+++.+++ F.

[.centered]
=== Letter 123.

[.blurb]
==== Men in the fall are in the wars and strife, but truth restores and brings into peace.

Dear Friends,

My love is to you all in the everlasting seed of God, that never changes, nor falls,
nor gives itself to that which doth change, which is not of this world, but is over it,
and was before the world was; in which is the steadfastness, and stayedness,
and life eternal.
Which reigns over all the airy spirits, (and that which doth change,) and remains,
and is as the winter fruit, and stands when all the untimely figs are gone.
Mark, and the seed is not as the corn that grows upon the house top, that withers;
for the leaves that this seed brings forth, never fade nor fall;
for the leaves thereof heal the nations which are wounded.
The second Adam goes over Adam in the fall, and his quarrelling sons and daughters,
who war one with another with their carnal weapons, who remain in their carnal worships,
carnal fellowships, carnal teachings.
But who are in the noble and royal seed, are all in peace, and in love, and in life,
and in unity, and are in the spiritual worship, and spiritual fellowship,
and spiritual teaching, being in the seed, Christ, that never fell, nor never will fall,
nor never changed nor never will change.
In this seed, Christ, is peace and rest, out of all troubles, out of all whimsies,
foolish dreams, imaginations, fancies false visions, false revelations.
For the seed, in which the blessing is, is felt, and the life, and the light,
and the righteousness, and the truth,
that answers the witness of God in all men and women, whether they will hear or forbear.
And so, all that are in Adam in the fall, both men and women,
and there remaining in the fall, they never are in rest nor peace, but are in travails,
wars, strife, fightings; the lusts being the ground of all this.
And whimsies and imaginations, fancies, false visions, false dreams, arrogancy, pride,
ambition, swellings, puffed-upness, that brings shame and covers them with shame;
which they possess that are in the fall, out of Christ, the second Adam, that never fell.
For in Adam in the fall is all the (inward) foul weather, storms, tempests, winds,
strifes, the whole family of it in confusion,
being all gone from the spirit and the witness of God in themselves,
and the power and the light; in which power, light,
and spirit is the fellowship with God and one with another,
through which they come out of Adam in the fall, into the second Adam that never fell,
the quickener, who awakens old Adam`'s children in the fall out of their sleep of sin,
and brings them out of his ways up unto himself, the way,
Christ that never fell nor changed, and out of and from his teachers, and priests,
and shepherds, etc. that change and fall, to the priest, shepherd, and prophet,
that never fell nor ever changed, nor ever will fall or change,
nor leave the flock in the cold weather, nor in the winter, nor storms, nor tempests;
nor doth the voice of the wolf frighten him from his flock.
For the light, the power, the truth, the righteousness,
did it ever leave you in any weather, or in any storms or tempests?
And so his sheep know his voice and follow him, who gives them life eternal abundantly;
who saith to all that are dead in Adam, "`I am come,`" mark, I am come,
"`that ye (dead in Adam) might have life.`"
Christ, the second Adam is come, that the dead in the first Adam might have life,
and might be quickened, and might be awakened to righteousness,
who are asleep in the unrighteousness.
And so he doth invite all Adam`'s posterity to come to him,
that all through him might believe, and come to light, and come to life,
and come up into peace and rest; for in the second Adam ye have peace, ye have rest.
So they have no peace nor rest in the old Adam in the fall, but in the second Adam,
Christ, that never fell, are the rest, and the peace, and the life.
But in Adam in the fall is neither rest, nor peace, nor life; but darkness, and trouble,
and sorrow, and burdenings, and changings.
And this Adam`'s sons and daughters in the fall do inherit and possess in the world.
Therefore all come out of Adam in the fall, and haste to him that never fell,
nor ever changed; in whom ye have all both rest, and peace, and life,
that was with the Father before the world began.

And so, in the name of the Lord Jesus Christ, that never fell, keep your meetings,
ye who are gathered in his name;
and then ye will see over all the gatherings of old Adam`'s sons and daughters,
that are in the fall and out of his name.
But ye being gathered into his name, that never fell, Christ Jesus,
feel the seed of God set over all that that makes to suffer; which was before that was,
and will stand and remain when that is all gone.
So farewell.

G+++.+++ F.

[.centered]
=== Letter 124.

My Friends,

Be faithful and keep your meetings; and in that light wait, which comes from the head,
Christ, in whom are all your lives; from whence ye have your light,
which is the life in the son.
And ye, who do witness the high calling in Christ Jesus,
and are redeemed by him out of the world, and are become new creatures,
walk above the world, and be not hasty; but in the light and life wait,
that with it your minds may be directed, and guided,
and joined together with that which is immortal and undefiled, in one spirit,
up to the immortal God.
And that with the spirit which he hath given you,
ye may witness the one baptism into one body,
and ye all with the light may see the one faith,
which Christ is the author and the finisher of;
and that ye may all see the end of your faith, the salvation of your souls,
with that which gives you the victory over the world.
And fear the Lord, and take heed of strife, and live in peace and love one with another,
believing all in the light which maketh manifest;
that all ye may be the children of the light.
And this belief giveth the victory over the world.
He that is of this faith, is born of God;
and he that believeth in the light shall not abide in darkness,
nor shall ever be confounded.
For he believeth in that which manifesteth that,
which is to be confounded and trampled upon; and he shall not be condemned,
but shall have the light of life.
And he that believeth not in the light is with the light condemned already.
And he that heareth not the voice of the son of God doth not live, but is in death.
Therefore he that heareth not the light which comes from Christ the life,
heareth not the voice of the son of God, and he cometh not to life.
And the hour is come that they which have been in the graves,
have heard the voice of the son of God and do live;
and they that do not hear the voice of the son of God do not live,
but are in the death and the grave.
And they that come to, believe in the light hear the voice of the son of God and live,
and out of the condemnation are come; and live over death, and the grave, and hell,
and so come to life.

G+++.+++ F.

[.centered]
=== Letter 125.

Friends, to you all this is the word of the Lord.
Know the seed of God in one another, which seed is Christ.
Look not out; then ye will not wander, but will be atop of the wanderer.
The seed, which is Christ, being known in one another, which the promise of God is to,
every one of you know the promises fulfilled in you;
whereby ye all may witness the blessing of God fulfilled to you, and in you.
And so in this the Lord God Almighty preserve you all to his glory,
and that ye all may know the flesh of Christ your food, and know his reign.

And quench not the spirit, and stop not the power; but dwell in that,
which doth stop and quench the deceit.
And to you this is the word of the Lord God.

And all Friends, mind and heed the life and power of the Lord God;
for all that are out of it, are, and will be confounded.
Therefore dwell in that which condemns it, in which will be your peace.

G+++.+++ F.

[.centered]
=== Letter 126.

[.blurb]
==== For Friends, to dwell in love and unity.

The word of the Lord God to all Friends.
Dwell in peace and unity with God, and one with another,
that to the Lord ye may be a sweet savour, and to one another,
and also in them that hate the light; that ye may all come to witness the sonship,
and to be heirs of God, and in the spirit have unity, which is the bond of peace.
And the seed of God, and the life mind.

G+++.+++ F.

[.centered]
=== Letter 127.

All Friends everywhere, do not delight in apparel, do not delight in the creature,
more than the Creator.
Trust not in uncertain riches, which fade and pass away; but trust in the living God,
and love the riches that endure, and fade not away.
Delight not in the world that ends, but in the world that hath no end;
that there ye may all come to have an assurance of the endless life.

G+++.+++ F.

[.centered]
=== Letter 128.

[.blurb]
==== To all Friends, to keep in the power of God, out of the cares of the world.

All Friends, to that which is pure, take heed,
that with that all your minds may be kept up to God, who is pure;
that as the lily ye all may grow,
and receive wisdom from God how to use the creatures in their places,
to the glory of him that created them.
For woe is unto you, that lay up for the latter day with covetousness;
ye act in that nature contrary to the light,
taking thought for tomorrow "`what ye shall eat, and what ye shall drink,
and what ye shall put on.`"
Look at the life which is more than food, and the body which is more that raiment;
and consider the lilies and ravens, and who feedeth them, and clotheth the earth?
That in the faith ye may stand, and with it ye may come to see him who is invisible.
He who lays up for the latter day with covetousness, goes from that,
which should keep him out of days, up to God, the beginning of days;
here the Ancient of Days comes to be seen, and the life out of death springs,
and a diligent serving God is known, and every one for his family provides.
For he is worse than an infidel, that doth not.
That which was before days were, mind, which brings to be diligent, serving the Lord;
and that keeps down the destroyer.
And that keeps down the covetous and the fleshly principle,
and that which would run out into the observation of days.
And that keeps the life up, out of the earth,
and keeps from trusting in the riches that are uncertain, and brings to trust in God,
who is living, who is the condemner of all the gods, who have eyes, and see not;
who keep people under their dominion from the light.
But all who take heed to the light, see God, who is living, who seeth all things.

G+++.+++ F.

[.centered]
=== Letter 129.

My dear friends and brethren, keep in the seed of peace,
which was before the enmity and adversary were, in which ye will all have life and peace,
and unity and dominion; and in that ye will know Christ Jesus to reign,
who was before the world began; in whom ye may know your election,
and a sitting in the heavenly places in Christ Jesus, above all the earthly places below,
and men`'s evil traditions and vain customs; sitting in Christ Jesus keepeth out of them,
for he was before they were.

And let all Friends everywhere pray to the Lord, to exalt his truth to his glory,
and his kingdom which hath no end, but is from everlasting to everlasting.

G+++.+++ F.

[.centered]
=== Letter 130.

[.blurb]
==== To all Friends, to dwell in the truth, the life of God, the light, etc.

All Friends, dwell in the truth; in my Father`'s house there are many mansions,
said Christ.
And ye all, that know the life, go not from it.
Heed not words without life; but heed that which lets you see and know the Father.
For mountains will arise, and may arise.
But this is the word of the Lord God,
and a charge to you all in the presence of the Lord God, heed the power and life,
the power which ye have formerly known and tasted of; and that will keep you,
until the day of salvation,
and that brings you to know the kingdom of God to stand in righteousness,
etc. and that will bring you to comprehend deceit, and to fathom it,
and bring you to be over the deceit of the world.
So ye that know the power of the Lord God, heed it,
and it will remove questionings out of your minds;
it will remove that which causeth trouble to come into your minds.
But if ye go from the power, the formal part gets up in you,
and the wonders you will run into.
But the power of God is the gospel; and ye that have received the power of God,
ye have received the gospel; and he is cursed that preacheth any other, yea,
if an angel from heaven.
For Christ is the power of God, to whom the angels must bow.
And Christ Jesus, who was born (of a virgin,) crucified, and is ascended,
(and there is no other,) all of you, that are turned to the light,
wait to have him born in you, every one in particular.
"`I am the light of the world,`" saith Christ, by whom the world was made,
who doth enlighten "`every man, that cometh into the world.`"
Who is the "`bread of life, that came down from above; and who eateth of this bread,
lives forever.`"
Now, every one of you having a light from Christ, the bread of life, wait,
and with and from it you will see, know, and have your food in due season.
Now, every one that comes into the world, having a light from Christ Jesus,
who is not of the world, and being turned to this light which he is lighted withal,
he is turned to Jesus Christ, from whence it comes.
And here none shall say "`Lo, here is Christ,
or lo there is Christ;`" but every one with the light, which comes from him,
shall see Christ, (and shall see the Father,
through the spirit that proceeds from the Father and the son,)
and the glory that he had with the Father before the world began;
and shall have dominion over all the contrary in the male and in the female,
having a light from him, that gives the "`light of the knowledge of the glory of God,
in the face of Christ Jesus.`"
Which light shines in your hearts;
and there shall every one feel their treasure in the earthen vessel,
and the power which is of God.
Now, whosoever goes from the light, which they are enlightened withal,
they go into the darkness, and they go into the wonders; and run out gazing, and saying,
"`Lo he is here, lo he is there.`"
I am come a light into the world, (saith Christ,) which every one,
that cometh into the world, is lightened withal, which light is the covenant;
and every one who is in the light, is in the covenant with God.

And so Friends everywhere, keep your meetings,
(this is the word of the Lord God to you,) and do not heed the lo here`'s or lo there`'s,
neither be troubled; but heed everywhere the life of God,
and do not gad abroad from the truth within;
that ye may be kept out of all high swelling storms, bustlings, and tempests,
and with it ye may be kept over the world, to him and in him that is not of the world.
And take heed of denying the truth; whosoever do, they go from the light within them,
and so go into the darkness, and into the wonders.
And who go from the light within, go from the Emmanuel, from the saviour within,
Christ Jesus, and from the truth in the inward parts,
and from the mediator between you and God, and from the vine; and so,
ye bear not fruit to the glory of God.
And going from the light within, ye go from your peace, and from the covenant of God;
and going from the light within, ye go from the life,
where every one receives the light of life.
And who go from the light within, go from the increase of God;
who go from the light within, go from the anointing within them,
and so continue not in the son, nor in the Father.
All who go from the light within, go out of the covenant of eternal life.
But every one walking in the light within, which he hath received,
he shall there receive the bread of life, Christ, whom the light comes from.
And so, having your food within, ye shall not go forth to gather it;
but he that is in the light, and believes in it, comes to know the garner,
whereinto the wheat is gathered, and the chaff,
that is to be burned with unquenchable fire, and the floor thoroughly purged;
and the immortal crown is known.

Therefore all Friends, keep in the power, and know the power of God in one another,
and the life that stands in God;
that out of all dryness and barrenness ye may be brought,
and kept in the living and eternal spirit and power.
And so, the God of glory keep you from the evil that is in the world, in glory,
and in unity, every one in measures.
Now, the power of God will never be shaken; that which is to be shaken,
(or tossed,) is out of the power, and the power remains;
therefore dwell in the power which throws down all that which may be shaken,
(or tossed,) and raiseth up that which can never be thrown down nor shaken.
And to you this is the word of the Lord God.
And dwell in that, and keep in that,
which keeps you out of and above the knowledge of
that which entereth into the sensual part;
for both these will fail.
Therefore in the power and in the life of God dwell, which comprehends the world,
and reacheth and fathometh over it all, in that dwell and live, there will be your peace;
it will keep you out of the strife, and combustions, and heaps.
For this all comes to be fathomed, chained, and kept down by the eternal power,
and bound and bundled up for the fire, and judged down,
and all that which brancheth forth from it, that nothing may reign but life itself;
and all the contrary, the filth and dross,
with the unquenchable fire is to be consumed and burned.
Wait all this to know, here is the path of righteousness and purity;
and nothing shall stand but the mountain of the Lord.
Glory to the Lord in the beauty of holiness, which is felt and seen!
And all being kept in the light, and walking in that, which ye are enlightened withal,
ye cannot be in the strife; for the enmity is out of the light, and the vain boaster,
which comes to nothing, but is judged and condemned.
And when that ye are met together in the light, hearken to it,
that ye may feel the power of God in every one of you.
So here comes your ear to be opened to hear the counsel of the Lord God;
and here the eye comes to be opened to see the Lord Jesus Christ in the midst of you,
ye all sitting under your vines.
So, every particular wait on him, who received not honour of man,
neither glorified himself; but the light,
which enlighteneth every one that cometh into the world,
is a witness against all them that seek their own glory, or glorify themselves,
or bear witness of themselves.
Now they who receive honour from man, are from the light, both he that gives,
and he that takes it; and it is to be stained, and the light stains it, and condemns it.
So every particular of you, to you this is the word of the Lord God,
know the son of God to be revealed in you.
And know the seed, which is Christ, to which the promise of God is;
that ye may all witness the seed of the woman to
bruise the serpent`'s head in every one of you.
That you may all witness ye are come to him that was in the beginning;
and to the seed of the woman,
which bruiseth the serpent`'s head in every one of you in your own particulars.
Then ye all will come to feed on the bread of life, that comes from above.
And such are redeemed out of the transgression, who are here, that witness this.
But where the seed of the woman hath not bruised the serpent`'s head,
and that which abides not in the truth, reigns; there is the transgressor.
So, that which is out of the truth reigning, the serpent being head, he sows his seed,
his seed goes forth from him, and his food, his meat is dust;
for he could not feed upon life that abode not in the truth, which is the life.
He that abides not in the truth, which is the life, his food is dust;
and he it is that is tormented.
And who are out of the truth, are out of the worship of God;
for who are the worshippers of the Father, they must be in the truth and in the spirit.
And being in the spirit and in the truth, they are in that the devil abode not in,
but is out of; and all false ways, and seducers, and deceivers,
and false worshippers are out of.
And Jerusalem`'s worshippers, and Samaria`'s worshippers,
and the worship that is at the mountain, and the idolatrous worshippers,
and the worship of devils; all these are out of the truth,
and out of the spirit that changeth not.
But who are in the truth and in the spirit, they are atop of the world,
and atop of him that abode not in the truth; their feet are shod with it.
Therefore every one of you that are come into the world,
coming all to the light ye come to your armour, ye come to that which lets you see sin;
it is the armour against it; it is the eye,
with which ye see that which must be cut down and judged to death.
In which truth, which is the light, we have fellowship one with another.
And this is the counsel of the Lord God to you, dwell all in the power of God,
which is the gospel of peace.
And the power of God is the cross of Christ; and ye that feel the power of God,
ye feel Christ; for Christ is the power of God.
The power of God is but one, and the light is but one,
and the cross of Christ is but one, which is the power of God;
and the gospel of truth is but one, which is the power of God, and there is no other.
Ye that come to know these, look for no other.
And Christ is that one in the male and in the female, which is the seed,
which the promise of God is to; and there all wait to find him, and receive him.
"`Know ye not, that Christ Jesus is in you, except ye are reprobates,`" said the apostle;
so now, if ye are reprobates, ye are wonderers and gazers in Adam, in transgression,
out of the light, out of the life, out of the power, out of the truth, out of the way,
which is Christ.
But being in the life, ye are in the way, in the truth, in the power of God, in Christ,
out of transgression, in the second Adam, the Lord from heaven,
out of the transgression of the first Adam.
And if Christ Jesus be in you, the body of sin is dead, and ye are brought to God;
and the Emmanuel being known, "`God with us`" is witnessed by every one of you,
that are redeemed by him out of the transgression, who are in the second Adam.
So, if Christ Jesus be in you, and ye in him, the body is dead;
and ye are alive to righteousness, and death is brought into death.

Friends, dwell all in the light, and then ye will dwell in covenant with God,
and with God ye will have peace.
And friends, all dwell in the light, that ye may receive the wisdom of God,
by which all things were created;
with which wisdom ye may come to order all the creatures.
And be low, as babes and little children, for the little children receive the kingdom.
And so, all know the promise which is to the seed;
and know the seed of God in one another, that there be no master but Christ,
who bruiseth the serpent`'s head, where debate and enmity are,
which are the cause of strife.
So, let the seed be master in the male and in the female, that the ground of strife,
which would be master, may be kept under, and the seed,
which the grave could not hold under, be the ruler;
so that ye may witness the rock that the gates of hell cannot prevail against,
nor the temptations of the devil.

G+++.+++ F.

[.centered]
=== Letter 131.

Friends everywhere, dwell in the power of the Lord God, which is without end,
in which ye may all have unity.
And take heed of striving about earthly things, which is the unredeemed part,
that is out of the paradise and the garden of God;
but that with the wisdom of God ye may come to be ordered,
and order the creatures by that by which they were made and created,
that by it ye may know yourselves to be governed.
And after that riches increase, take heed of setting your hearts upon them,
lest they become a curse and a plague to you.
For when ye were faithful at the first, the world would refrain from you,
and not have commerce with you; but after,
when they saw ye were faithful and just in things,
and righteous and honest in your tradings and dealings,
then they came to have commerce and trade with you the more,
because they know ye will not cozen them, nor cheat them:
then ye came to have greater trading, double than ever ye had, and more than the world.
But there is the danger and temptation to you, of drawing your minds into your business,
and clogging them with it; so that ye can hardly do any thing to the service of God,
but there will be crying, my business, my business;
and your minds will go into the things, and not over the things;
and so therein ye do not come into the image of God, in which is dominion.
And so, when your minds are got into the riches, and cumbered therewith,
ye go back into that ye were in before: and then, if the Lord God cross you,
and stop you by sea and land, and take your goods and customers from you,
that your minds should not be cumbered; then that mind that is cumbered, will fret,
being out of the power of God.

And all Friends, take heed of jars and strife,
for that is it which will eat out the seed in you;
therefore let not that harbour in your bosoms, lest it eat out the good in you,
and ye come to suffer in your own particulars.
Therefore dwell in love and life, and in the power and seed of God,
which is the honourable, royal state.
And all that speak or preach abroad, see that ye be in the life, and power,
and seed of God, which will edify the body, and not in a brittle, peevish, hasty,
fretful mind; but dwell in that which keeps down the contrary,
that that may speak which edifies the body in love.
And all take heed of vain words, and tattling idle words, but everywhere stop such;
that love may continue in the body, and that the seed may spread over all,
that unity may be kept.
And all Friends everywhere, if Friends be poor, and in want, or in prison,
that ye may in wisdom relieve and cherish such.
And all Friends everywhere, stop the deceit, that would devour and destroy,
which is out of the truth, and true wisdom; which must be limited,
that transgresseth the spirit of God.
For since the days of the apostles, the true church hath been in the wilderness,
and the beast, false prophet, antichrist, and false church have ruled and reigned;
amongst whom have been the many names and horns amongst the apostate christians,
who have professed themselves to be elders.
Amongst this eldership have they had outward and earthly rulers,
which have got up since the days of the apostles: but who come to Christ,
who was and is the true christian`'s head, he is their ruler;
by whom all things were made.
And when the apostate christians went from the apostles`' doctrines into the world,
they set up many rulers amongst them, and many heads;
when they went from the seed of God in themselves, in the male and in the female,
then they forsook their head, Christ Jesus.
And so, whosoever go from the seed of God in themselves, and set up other heads,
they lose the one head, which is Christ Jesus; and then come to be covered with darkness,
and the seed comes to be loaden, as a cart with sheaves:
and then they break into the many ways, and set up the many heads,
when they go from the seed in the male and in the female, which is the one head.
And then come up the fightings about earthly things,
and warrings with carnal weapons about earthly things, and self-interest,
and man`'s honour and titles, and about their churches, and religions, and worships,
and ministry, which have been set up since the days of the apostles, and since the fall.
The Jews did kill with the outward sword the heathen, and one another; but Christ Jesus,
the prince of life, fulfils the law, and ends the outward Jews`' types, figures,
and shadows, ordinances and carnal weapons, who is the king of the whole earth,
who comes to save men`'s lives, yet slays and "`kills with the sword of the spirit,
which is the word of his mouth.`"
And the apostles, who followed Christ, wrestled not with flesh and blood; so all,
who come to witness Christ to reign and to rule, (who is the prince of life,
that saves men`'s lives,) and follow him, do not wrestle with flesh and blood,
nor seek to destroy men`'s lives.
And here comes the wisdom to be known, that is from above, that is pure and gentle,
and easy to be entreated, that is not sensual, carnal, and devilish.
So in the time of the law among the Jews there was fighting outwardly;
but in the time of the gospel of Christ Jesus, who came to end the law,
they were to love enemies, and not to kill them; and love them that hate them,
and not kill them.
But in the times since the days of the apostles, in the apostate christians`' time,
they are crying up the outward sword again;
and this is the dragon`'s and the beast`'s power, the prince of death,
which hath reigned since the apostles`' days.
But who come to follow Christ, they come to reign in spirit,
over all these fighters with carnal weapons,
that are got up since the days of the apostles.
Therefore who are come now into the power of the Lord God, and to the seed that is royal,
who was the elected, before the world began, keep your meetings,
and dwell in the power of God, in which ye may know his image, and come into it;
with which ye may spiritually reign, and have dominion over all the world,
and rule in it over them and their vanities, and work them down without a carnal weapon,
in the power of God.
So keep your meetings, both particular and in the general, in the power of the Lord God,
and dwell in the life, and power, and wisdom of the Lord,
that all uncleanness whatsoever may by the power
of the Lord be brought down and rooted out;
and that such have no rule nor authority amongst you,
though they be never so fair or excellent of speech:
but let all such be brought under by the power of the Lord God, who is to reign over it;
that in the sweetness and unity ye all may be brought
to be a sweet savour to the Lord God,
and in the hearts of one another, and let no uncleanness be amongst you.
And all Friends everywhere,
take heed of printing any thing more than ye are required of the Lord God.
And all Friends everywhere, take heed of wandering up and down about needless occasions,
for there is danger of getting into the careless words, out of seriousness, weightiness,
and savouriness.
And all Friends everywhere, take heed of wronging the world, or any one, in bargains,
or overreaching them; but dwell in the cool, sweet, and holy power of the Lord God,
and in righteousness, that it may run down amongst you; and that will keep you low.
And all Friends everywhere, take heed of slothfulness and sleeping in your meetings;
for in so doing ye will be bad examples to others, and hurt yourselves and them.
And all take heed of going up and down to minister, but as ye are moved of the Lord God,
or to speak in meetings, or any other places;
for travelling to such is dangerous to lift them up, going amongst settled meetings,
that are settled.
For there is difference betwixt Friends going into the world,
and of coming among them that are come to silent meetings, and to feed there;
for that which may be seasonable to the world, may not be to them.
Therefore let all live in the seed, and wisdom, and fear, and consider,
before they utter, that the light be up; whereby all may be settled,
and they themselves be washed.
And dwell in the seed, that ye all may know Christ come to reign in you;
so that all may be done and spoken by and in the power of the Lord God,
that is done and spoken, and not out of it:
and in that ye will all have unity in the record of life,
whereby the power of God and the seed of God may come up,
which is heir of the blessing and of the promise;
that ye may come to know the place where there is no curse, and the Lamb`'s power,
throne, life, and dominion.
And in the wisdom of God all dwell, that to him ye may be a sweet savour,
and a blessing in the hearts of all people; that nothing may rule nor reign amongst you,
but the seed itself, and the life of God.

G+++.+++ F.

Let this be read in your meetings.

[.centered]
=== Letter 132.

[.blurb]
==== An epistle to Friends, for all to keep in the light, and to watch over one another.

All Friends and brethren everywhere, walk in the truth,
and know one another in the measure of life,
that in it your minds may be guided up to the Father of life; and stand in his counsel,
that he alone may be loved with all your strength, with all your minds,
and with all your souls; so that ye may all know one another in the life and light,
that ye may all be kept from idols.
For if ye know one another in the flesh only,
that love which will rise out of that knowledge is feigned, and that will wither,
and under the condemnation of the light must come.
Therefore all wait in the measure of life, that with it your hearts may be knit together.
And none to be hasty, nor to will any thing;
there is not any thing received from God by him who willeth with his own will.
For "`no prophecy of the scripture came by the will of man;`" Peter,
that was not learned of man, but of Christ, saw this.
And the scripture is for the "`perfecting of the man of God,`" which is learned of God,
and came not by man`'s will.
So now mind your growth, and your perfecting, and your steadfastness in the light,
in which is the unity.
So every one wait in the light, which comes from Christ the head,
from whence nourishment comes, which nourishes the body and all the members;
from whence comes the bread of life, which is from above, and the water of life.
Therefore all wait in your measure, and walk after your line,
which is the light which comes from Christ who is your life;
that every one of you may have praise and comfort in the same,
and every one of you may be kept in the way of righteousness and peace up to the Lord,
who is righteousness and peace,
where the blessed hope is seen with the light that
comes from him by whom the world was made.
That so the covenant of light, life, and peace ye may all come to witness,
and every one come to have dominion and rule over your own spirits;
for the spirit of man lusteth to envy,
if it be not subdued by the spirit of the living God.
Therefore wait and take heed, lest any nakedness appear,
and that which is not justified in the sight of God.
And take heed of presumption, lest ye go from the living God; but in the spirit dwell,
that over all that ye may reign, and come to be recorded in the book of life,
which life was before the world was.
And this brings you to see and read one another,
as epistles written in one another`'s hearts, where in unity, love,
and peace ye will come to dwell, in the life of the spirit of the living God,
in which the saints had unity, which brought them to be taught of the living God;
and so they gave forth the scriptures, as they were moved by the holy ghost.
So no prophecy in the old time came by the will of man, but was learned of God.
So now ye waiting in the spirit every one, to be taught of God the Father of spirits,
your teacher is with you present, and one in you all, according to your measures.
Which spirit is given to every one of you to profit withal;
by which holy spirit the scripture was given forth.
Which scripture the world hath got, who are sensual, not having the spirit,
and there they are fighting about the outside and the languages.
And there is the sea, which the beast ariseth out of, which the world wonders after;
and there is the mother of harlots, with all her false colours,
whose eyes are out from the light which comes from him by whom the world was made;
there ye may go, and have a name to live, but are dead.
Now all be willing to wait in the measure of that which is eternal,
that no fornication be found amongst you, nor deceit;
that all may come to receive wisdom from Christ, who is the wisdom of God.
That this wisdom may be justified in you all, and ye all in the light preserved,
and that which is contrary condemned.
So that ye may all be kept from deadness and slothfulness, in the fear of the Lord God,
and therein your hearts kept clean.
And so the Lord God Almighty preserve you!

Friends, keep your meetings everywhere, waiting upon the Lord,
that to him ye may be a sweet savour.
And watch over one another with the measure of the spirit of the Lord.
The Lord God Almighty preserve you, and keep you in his will, wisdom, light, life,
and power.

G+++.+++ F.

Let this be read among Friends.
