== Letters 133 &#8212; 160

[.centered]
=== Letter 133.

[.salutation]
Friends,

Towards all men walk in wisdom, and be gentle to all men;
"`for the meek inherit the earth,`" and receive the blessing.
"`And they that thirst after righteousness shall inherit righteousness,`" and the blessing.
And the "`merciful do obtain mercy`" and the blessing.
And the "`pure in heart shall see God,`" and receive the blessing.
And "`Blessed are they that mourn, for they shall be comforted.`"
And "`Blessed are the peacemakers, for they are the children of God.`"
And "`Blessed are they that are persecuted for righteousness`' sake,
for theirs is the kingdom of God.`"
And "`Blessed are ye when men shall revile and persecute you,
and shall say all manner of evil against you falsely for Christ`'s sake.`"
And it is love that edifieth, and the edifying is in the most holy faith,
which faith is the gift of God, which giveth victory over the world;
and in this is the blessing, which purifieth the heart,
and this is it which bringeth to please God.
And that which edifieth is the living faith, and not the dead faith;
and love rejoiceth in the truth, and not in the iniquity, for that is not in love.
So ye that are the Lord`'s lot, (mark!) and are his inheritance,
and are in covenant with God, with him ye have peace;
which covenant is given to all the world.
But they that hate the light are out of covenant with God,
and by the light they are condemned;
and those which the light doth condemn are out of the covenant.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 134.

Live in peace, all my dear babes of God, one with another,
for patience obtains the crown, and hath the victory.
And in pureness live over the deceit, and answer the witness of the Lord God in every one.
And keep in the seed and life of the Lord God,
that ye may feel the blessing of the Lord God amongst you and upon you.

And that which doth let you see your sins, in that stand, and ye will see your saviour,
who was before the world was, him by whom the world was made,
"`glorified with the Father before the world began;`" he will be your stay and rest.

Dear friends, dwell in the seed of God, and know it in you all,
that ye may know it to reign, which is the heir of power; and in that live and dwell,
and in it keep your meetings.

And we must have the patience to bear all manner
of evil done or spoken against us for Christ`'s sake,
and rejoice at it.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 135.

[.blurb]
==== For Francis Howgil and Edward Burrough.

Dear friends and lambs, put on the armour of light, and the shield of truth,
and the breast-plate of righteousness,
that ye may stand in battle against all the Philistines, and the enemies of God,
being led and guided with the spirit up to God, the Father of spirits;
that what ye do beget may be to him and into his image, and that which ye do present,
it may be perfect.
And so mind this.
Sow not sparingly, for the Lord hath a seed that-aways.
So the Lord God Almighty preserve you!
And stir abroad whilst the door is open, and the light shineth;
and so go on in that which letteth you see the world, to comprehend it,
and to see what is imprisoned by it and suffereth by it.
So the Lord give you an understanding in all things, and his arm go along with you,
that ye may be to his glory.
And the blessing of the Lord be with you!

Dear Francis and Edward, in the life of God wait,
that ye may be with it led and kept to receive wisdom from God,
that ye may order all things there with it,
and be manifest to the witness of God in all that ye may beget to God;
that as good ploughmen, and good thresher-men ye may be, to bring out the wheat.
So the Lord God Almighty keep and preserve you.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 136.

[.blurb]
==== To Friends, to dwell in that which keeps peace.

[.salutation]
Dear friends,

Dwell in that which keeps your peace, and comprehends the deceit,
and answers that of God in every one.
And let Friends keep their meetings, and never hearken to tales, nor things without;
but keep their peace, and know the life and power, union and fellowship,
which stand in God, in and with which ye may stand over the world in the one power, life,
and wisdom, and therein be kept to the glory of the Lord God.
So, in that which is pure, the Lord God Almighty preserve you!

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 137.

[.salutation]
Friends,

Let God`'s wisdom have the stay of your minds, and let it be the end of all your words;
beware of that spirit, that leads out of it into any thing.
There is a day coming, wherein some may wish that they had walked in wisdom,
as touching the weaknesses one of another, or the failings one of another;
for what know ye, who may stand or who may fall in the day of God`'s trial?
Then many, that have been unstable,
may wish that they had kept their secrets in their bosoms,
and in God`'s wisdom sought to restore all, and not to scatter;
as that spirit doth which cannot bear and cover the
weaknesses one of another who are yet in the wilderness,
where the trials are many.
I have seen a great danger in this thing.
Wherefore beware of that spirit that cannot bear one with another,
or forgive one another; for that which cannot, will discover rather than cover,
and bring a cloud over many, wheresoever it is received, and raise the contrary in many,
and veil the just,
(it may be in whole meetings,) for want of wisdom to be stayed in the meek spirit,
which trys all spirits, and gives clear sight of things.
For want of this many may be cast by, and scarce ever restored again.

Therefore I say, tread over the dead, and that which works in that nature,
and reach to the witness in all; so will ye stand for God,
and God will bless you in the day of trial.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 138.

[.blurb]
==== To the prisoners.

[.salutation]
Friends,

Ye that are the prisoners of the Lord Jesus Christ in out-ward bonds,
who witness him by whom the world was made, who is the King of saints, and who are his,
and come under his dominion and government, ye are not your own;
but purchased with his blood, which washes and makes you clean, and justifies,
whose bodies are his temple.
Though he suffers you to be imprisoned, yet in his power your bodies are kept,
and your spirits also; ye standing witnesses for your master, for your king,
for your prophet, for your covenant of light, for your wisdom of God,
(him by whom all things were made,) for the word and power,
by which all things were made and upheld, against the powers of darkness,
who are out of the light, out of the truth, who cannot bind,
stop nor limit the unlimited power, which is over it, and comprehends it.
They who are born of the word, and in the power which upholds all things, over that,
(and the power of the evil one,) have victory, and sing over the false prophet.
For the devil was the deceiver, who abode not in the truth;
and there is the false prophet, who speaks of his own, and not from the Lord;
and there is the beast, that makes the war against the lamb and his saints,
who witness the testimony of Jesus, and the word of God.
Therefore mind the word of God, ye children of the light, who are in the light,
that comes from the word; mind the word of the Lord, which is as a hammer, and as a fire,
and sharper than a two-edged sword.
And ye who are the Lord`'s, are not your own; but they who are in their own time,
see not the time which is in the Father`'s hand; their time is always,
and they do their own works, and not the works of God, which the son of God did.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 139.

[.salutation]
Friends,

Know the praying in the spirit, and with the understanding;
then ye will come to know the sighs and groans that cannot be uttered.
For such as have not the spirit that gave forth the scriptures to guide them,
are as the Pharisees were, in the long prayers, and in the wrath, and in the doubting,
and do not lift up holy hands.
This makes a difference between praying in the spirit, and the Pharisees`' long prayers,
that devoured widows`' houses.

And none owns the light as it is Jesus,
but he that owns the light that Christ lighteth him withal.
And none owns the truth, but who owns the light that cometh from Christ, the truth.
And none cometh to the Father, but such who owns the light that cometh from Christ,
which leads to him.
Nor none owns the son, except he owns the light that cometh from him.

For all dwelling in the light that comes from Jesus, it leads out of wars,
leads out of strife, leads out of the occasion of wars,
and leads out of the earth up to God, out of earthly-mindedness to heavenly-mindedness,
and bringeth your minds to be in heaven.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 140.

[.blurb]
==== To Friends, concerning collecting their sufferings, etc.

All Friends everywhere, that do suffer for tithe,
and are served with writs to answer at London, take copies of your subpoenas and writs,
that ye may have them, when ye appear, to show them to the court;
whereby ye may be kept atop of the persecutors and evil doers.
And keep a copy of all your sufferings for tithes in every county,
that it may be laid on their heads that cause you to suffer.
And all Friends that suffer imprisonment, or are fined for not swearing,
keep a copy of your sufferings in every county,
and the men`'s names that cause you to suffer, for tithes, or for not swearing.
And all Friends that suffer for not giving money for repairing of steeple-houses,
keep copies of your sufferings, in every county, and by whom.
And as any are brought to suffer for these things,
or for not bowing to any deceit whatsoever,
let a true and a plain copy of such suffering be sent up to London.
And such as are moved of the Lord to go to steeple-houses, and are beat, knocked down,
or imprisoned; let a copy of all such sufferings be sent up as abovesaid,
that the things may be laid on the heads of them that caused the sufferings.
And if any be beaten or wounded in going to meetings,
or be struck or bruised in meetings, or taken out of meetings and imprisoned;
let copies of such things be taken, and sent as abovesaid,
under the hands of two or three witnesses; that the truth may be exalted,
and the power and life of God lived in.
And if any Friends be summoned up by writs,
or subpoenaed to appear personally to answer for tithes, let them do it,
that the truth may stand over the head of the liar;
which may answer the truth in every one.
And as ye are moved, be obedient to the truth, that nothing may reign but the truth.
They that say ye must appear personally, and when ye appear, say they do not mean so,
but that ye must appear by an attorney; this is not truth, this is made up of a lie,
and is to be judged by them that dwell in the truth.

If any Friends be moved to write to them who caused their sufferings, let them do it;
nevertheless let copies be sent of their sufferings as aforesaid.
And also any that suffer for not putting off their hats for conscience sake,
let copies be sent up of these things likewise.

[.signed-section-signature]
G+++.+++ F.

Let this be sent among all Friends in all counties in this nation.

[.centered]
=== Letter 141.

[.blurb]
==== To Friends, to gather up their sufferings and lay them before the judges.

All Friends everywhere, that are in any sufferings,
let your sufferings be gathered up together in every county,
ye that have suffered by justices, or constables, or bailiffs;
let your names be set to your sufferings, and a name or two to witness them,
and the names of them that caused you to suffer.
And after that ye have gathered up your sufferings in every county,
in the county where the judges come, let your sufferings be laid before them,
who are sent forth from the head and heads of the nation,
(which nation or nations is to be governed as a family, in justice and truth,
and judgment, and righteousness.) For he that is the head in the nation,
gives forth his charge to the judges; for they are all as his servants.
The judges come forth into the several counties, and the counties are as their families;
and they give forth their charge to the justices, sheriffs, juries, bailiffs, constables.
The justices and sheriffs of the counties,
they are to look to their places as to their families;
chief constables and other constables in their places, as to their families;
and the constable to look to his town as to his family.
The judges give charge to all in their places.
Now these not judging and doing justly, sheriffs, juries, constables not doing justly,
righteously, or equally; the sufferings being gathered together, short and true,
and their actions that have not been just and righteous,
who caused the righteous to suffer and truth to fall in the gates, and in the streets,
that equity cannot enter, (for equity cannot enter where truth is fallen;
for that which lets in equity is truth.) Gather up such your sufferings in every county,
that suffer by the unjust and unrighteous,
and deliver them to the judges that they may see it;
that they may judge justly and see what is done in
the family to whom they give their charge,
and what their master`'s servants have done, justices, sheriff, constables.
And if the judge that sits in the gate will not judge righteously,
nor plead the cause of the innocent, nor help the helpless,
nor break the jaws of the wicked that tear and rend the innocent,
(but is light and vain,) God, who is just, is ready to plead their cause,
and to judge and cast out the unjust judges.
For he that judgeth among the judges, (and relieves the oppressed,
and helps the helpless, and strengthens the weak hands and feeble knees,
and gives righteousness to every one that loves it,
to every one whose intents are upright and single,) gives
true judgment agreeable to that of himself in every one,
and crosses the ends and intents of every one that is from that,
and gives judgment upon the unjust.
And that a copy of all your sufferings,
which are delivered to the judges in every county be kept
and sent up to him that is the head in the nation,
(who sends forth the judges as his servants,) that he may see, measure, and weigh,
how unrighteously they have judged, and what his servants have done,
which cause the dividing of his family;
and through the want of judgment running down the streets,
equity cannot enter because truth is fallen.
So these things being laid upon the heads of the nation
that they may feel and see that God`'s judgments are just;
and will come upon them if they do not judge justly, and do not measure righteously,
and do not weigh truly.
So that in every circuit and assizes the sufferings of all
Friends being gathered and sent to every judge in his circuit,
a copy of the said sufferings,
(which were so laid before such a judge,) may be
afterwards brought and sent to the head of the nation;
that truth, righteousness and justice may reign,
and Friends be clear of the blood of all men.
That the seed of God may reign, which doth reign above all the wicked.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 142.

All my dear friends,

Keep up your heads above the waters and the sea, in which there is a tempest.
Fear not the devil, nor all his darts nor weapons,
nor all his soldiers and instruments that he keeps in league with;
but mind the power of God and the light of Jesus, and be clothed with,
and put on the armour of light, and the helmet of salvation,
and the breast-plate of righteousness, the shield of faith, in which ye have victory,
and unity, and access to God.
And dwell in patience and love to God, and one towards another;
for the lamb must have the victory over them all,
the wild beasts in the field or wilderness, who are in the fall from God.
And though these beasts`' horns be never so long, yet the lamb shall conquer them;
who gets the victory, and overcomes, and takes away the sin.
And the lamb hath wisdom, the lamb hath power; follow him, then ye shall have his mind,
wisdom, and patience; and in that ye follow the spirit of truth,
and are led by that (against which there is no law) in which there is life and peace,
and fellowship with the son and the Father, and all the saints, and their words.
Therefore live in the truth, and then ye live in Christ the way, that lives,
who was before the untruth was, in which the many ways in the wilderness are.
And living in the truth ye live in the love and unity, yea,
in that which was before the enmity was, and imperfection;
in which truth is all perfection of love, and life, and light, which light, life,
and truth is the way to God, in whom the church is which Christ is the head of.
And who come to this church they come into God the Father of our Lord Jesus Christ;
and who come to God, they must come into the light, life, and truth.
And that is the way in which people are renewed into
God`'s image of holiness and righteousness again,
in which God is seen.
Which way is out of the ways of man,
that is fallen from the image of God`'s righteousness and true holiness;
in which way are all the gadders abroad from God, out of the life.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 143.

All friends and brethren, in the noble seed of God live, which hath the promise of life,
which is the top and corner stone, Christ over all set,
in whom is life eternal and fulness for you all, and life, peace, and wisdom.
And the seed Christ destroyeth the devil and his works, which seed Christ lives forever.
Feel and know that in yourselves which will never have an end;
and then ye will know that which doth remain and abide when
the devil and his works are destroyed and gone.
The seed remaineth, Christ, the power of God, which goeth over the power of the devil,
in which is the saints unity that is everlasting;
which bringeth to the church that is in God.
And so all in the power of the Lord God and the seed live,
which is over all that which is not in his pure life;
in which ye all have unity that never hath an end.
My love is to you in the seed, in which there is life.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 144.

[.salutation]
Friends,

Get not knowledge in the unsanctified and unregenerated part;
for that which is not sanctified in your own particulars,
will not be to them that it is declared to.
Neither can ye feel your words that come from the unsanctified and unregenerated part,
go from you with joy and life; for that part will glory and boast,
and vaunt itself and say, this have I done, and that have I spoken,
and not glory in the Lord.
So this satisfies not, and the spirit in prison is not refreshed by those things.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 145.

[.salutation]
Friends,

Where there is strife among any of you, mind the light to judge it down and condemn it;
by which light your minds may be guided up to Christ, where there is no strife,
to learn of him, and to condemn all that with the light,
which would give the world a ground to reproach truth, and to see your nakedness.
For that which is out of the light will fall and confound itself.
So mind that which keeps your peace, and condemns that which leads into weakness;
and that which will let in prejudice, goes from the light.
All which is to be condemned with the light, which leads to Christ the covenant of peace.
And where there is strife which leads out into many words,
such will wither and bring themselves under condemnation at last.
Such must be silent and mind that which doth condemn them;
that the life in them may arise, wherein is no strife.
For where men`'s spirits are high, something is stirring that should be kept under;
take heed that get not up into rule.
So first learn the ministry of condemnation in yourselves, that life may arise,
before ministry in the spirit be known, which preacheth peace by Jesus Christ,
where there is no strife.
Therefore wait to know the time of silence.
And all Friends, let your patience and moderation be known to all men;
for nothing is attained to that is good by strife,
for that is out of Christ in the forward will, which is to be condemned with the light,
(where is the unity,) which cometh from Christ,
and leadeth up to Christ the covenant of life.
And take heed, all Friends,
of causing his name to be blasphemed through you among the heathen,
but mind and wait to receive the love of God which bears all things,
and suffers all things; and so comes to receive the armour of righteousness,
which quenches all the fiery darts of Satan,
that the patience that bears and suffers all things may be witnessed.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 146.

[.blurb]
==== To Friends in Ireland.

[.salutation]
Friends,

Feel all of you the power of the Lord God in yourselves to guide your minds up to God,
and to give you dominion over all weakness, and to strengthen and to heal you.
And look not out, but every one feel the power of God in your own particulars,
and let all your faith stand in that; then will ye have unity,
and in that ye will have dominion and victory, and it will keep you in order.
In which ye will have virtue, and in which ye will feel the spirit,
in which ye will have fellowship and comfort.
And be low and still in the life and power, and not hasty nor rash;
that ye may in the life and power answer that of God in every one,
that crieth for peace and rest.
So dwell in the love of God, this I warn you and charge every one of you;
your faith standing in this and in the power of God,
then ye will feel the presence of the Lord God among you.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 147.

[.blurb]
==== To Friends in Wales.

[.salutation]
Friends,

Live in the wisdom of the Lord, for that is it which doth preserve you pure, lively,
and gentle, above that which is below.
And in the increase of God live, and in his virtue, power, and love,
that through it your hearts may be established and filled with the same;
that justice and truth may in all things be amongst you,
and Christ Jesus known in the midst of you as a prophet, priest, and king,
(who hath gathered you in his name,) to open and reveal to you, and rule you,
who is the quickening spirit in whom the spiritual sacrifices are offered.
Therefore I say, know Christ, who is the substance of all the types, figures,
and shadows, by whom the world was made, who destroys the enmity among people,
and the devil the author of it; and in him is both life and peace.
The heave offering was a figure of Christ the one offering; the priests, and the law,
and the first covenant, were figures of the everlasting covenant, Christ Jesus.
Oaths which ended strife in the time of the law and before, were figures of Christ,
the oath of God, who sware by himself; which oath Christ Jesus endeth,
and destroys the devil the author of strife, and brings people to yea and nay,
who judges the false oath and ends the true.
For there were no oaths commanded before the fall;
so there are none to be in the restoration and redemption by Christ.
They see this doctrine that are renewed again (in measure) into God`'s image,
and are come into obedience to Christ`'s doctrine and the apostle`'s,
as in the primitive times; and see the ground of swearing among the Jews,
and see the ground of swearing got up since the apostles`' days,
among the apostates from the primitive practice in the church in the apostles`' days.
And they see that oaths were not given to man before the fall,
and see they are not to be in the restoration; nor were in the primitive times,
nor in the beginning according to the doctrine of Christ, who is the first and the last,
who is to be minded, and his doctrine, who is the top and corner stone.
And now is the bride his wife, coming up out of the wilderness,
where she hath been driven, and been fed of God in this time of the beast`'s, dragon`'s,
false church`'s, and whore`'s worship, which hath gotten up since the apostles`' days.
Therefore all walk in the light of the lamb, that by his blood ye may be washed;
that through it and the testimony of the Lord Jesus ye may overcome.
And meet in the power of God, and in that keep your meetings;
that ye and every one of you may inherit the power of God,
and so come into your own inheritances.
So live in love, peace, and unity, one with another;
for the body doth edify itself in love.
And the grace of our Lord Jesus Christ be with you, amen! to teach you,
and to season and to establish your hearts, and to bring you salvation;
and in that live which was before enmity was.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 148.

[.blurb]
==== An exhortation to fervent prayer and steadfast faith, in time of the greatest troubles and exercises.

O my dear friends and brethren everywhere! let all your
cries and prayers be to the Lord in singleness of heart,
in his spirit and power, and in belief in God through Christ,
to receive what ye pray for.
For the Lord`'s ears are open to the cries of his poor and afflicted ones.
So, day and night let your cries be to him, who will keep you in all distresses.
For in your afflictions Christ is afflicted, and in all your oppressions he is oppressed,
and in all your imprisonments he is imprisoned, and in all your sufferings he suffereth,
and in all your persecutions he is persecuted.
"`Saul, Saul, why persecutest thou me?`"
said Christ.
And all Friends, keep out of the vain fashions of the world in your apparel,
and run not after every new fashion the world inventeth and setteth up;
keep in your plain fashion,
that ye may judge the world`'s vanity and its spirit in its vain fashions,
and show a constant spirit in the truth and plainness.

And be moderate and chaste in all your families,
and in all your imprisonments keep in the fast to the Lord,
which breaks down the bond of iniquity, by which every one`'s health groweth.
And ye may also see, how Christ Jesus encourages to pray, Mark 13 "`Take ye heed,
watch and pray; and what I say unto one, I say unto all, watch.`"
And in Luke 11:5-13. wherein he further encourages to pray, where Christ saith,
"`Which of you shall have a friend, and shall go unto him at midnight, and say unto him,
friend, lend me three loaves, for a friend of mine in his journey is come to me,
and I have nothing to set before him.
And he from within shall answer and say; trouble me not, the door is now shut,
and my children are with me in bed, I cannot rise and give thee.
I say unto you, though he will not rise, and give him, because he is his friend,
yet because of his importunity he will rise, and give him as many as he needeth.
And I say unto you, ask, and it shall be given you; seek, and ye shall find; knock,
and it shall be opened unto you.
For every one that asketh, receiveth; and he that seeketh, findeth;
and to him that knocketh, it shall be opened.`"
And upon this Christ encourages to knock, pray, and seek.
"`For if a son shall ask bread of any of you, that is a Father, will he give him a stone?
Or if he ask a fish, will he for a fish give him a serpent?
Or if he shall ask an egg, will be give him a scorpion?
If ye then being evil, know how to give good gifts unto your children,
how much more shall your heavenly Father give the holy spirit to them that ask him.`"
And further he encourages to pray.
Luke 18 "`He spake a parable unto them, that men ought always to pray, and not faint,
saying, there was in a city a judge, that feared not God, neither regarded man.
And there was a widow in that city, and she came to him, and said,
avenge me of mine adversary; and he would not for awhile.
But afterwards he said within himself, though I fear not God, nor regard man;
yet because this widow troubleth me, I will avenge her,
lest by her continual coming she weary me.
And the Lord said, Hear what the unjust judge saith,
And shall not God avenge his own elect, which cry day and night unto him,
though he bear long with them?
I tell you, that he will avenge them speedily.`"
Here mind the promise of Christ, that doth not change, but will be fulfilled.

And Christ distinguishes in a parable of a Pharisee,
(who was a public praying man,) and of a Publican, that stood afar off,
and cried for mercy; who being in the fear, was more justified than the Pharisee,
who was in the public praying.
So, pray in the spirit and in the faith, nothing wavering nor doubting.
And seek and watch in the spirit, every one in your measures, that ye have received,
and therein to be preserved; and Christ the life will open to you,
and the spirit will give you an understanding,
and a distinction of the state of "`asking, and not receiving, and of seeking,
and not finding,
and the praying in the wavering and in the doubting,`" which is not in the spirit of God.
But such ask in that nature which doubts, and would consume it on their lusts.
So, ask in faith, that gives the victory over the wavering, doubting nature.
And whatsoever ye ask believing, it will be given unto you; it is Christ`'s promise. John 14:13-14.
For Christ saith, "`Whatsoever ye ask in my name, that will I do,
that the Father may be glorified in the son.
If ye shall ask any thing in my name, I will do it.
If ye love me, keep my commandments.`"
So, every one`'s prayers are assured unto them,
and their requests effectual in their obedience, and loving Christ,
and keeping his commandments.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 149.

[.blurb]
==== To Friends, to know one another in the light.

All Friends everywhere meet together, and in the measure of God`'s spirit wait,
that with it all your minds may be guided up to God, to receive wisdom from God;
that ye may all come to know how ye may walk up to him in his wisdom,
that it may be justified of you, and ye in it preserved up to God, and be glorified.
And Friends meet together, and know one another in that which is eternal,
which was before the world was.
For knowing one another only in the letter and flesh,
differs you little from the beasts of the field; for what they know they know naturally.
But all knowing one another in the light which was before the world was,
this differs you from the beasts of the field, and from the world`'s knowledge,
and brings you to know one another in the elect seed which was before the world was.
And if ye turn from this light ye grow strange; and so neglecting meetings ye grow cold,
and your minds run into the earth and grow weary and slothful, and careless, and heavy,
and sottish, and dull, and dead.
Ye may speak then of things which were opened once from the light,
though now ye be turned from it;
but with the light in which is the unity is all that condemned.
In which (light) is the fellowship with the son, from whence the light comes,
which keeps in the liveliness, which keeps from slothfulness,
and all those things before mentioned, which are contrary to the light;
which who turns from, turns into.
Therefore in the light wait and walk, that ye may have fellowship one with another.
I charge you all, in the presence of the living God,
that none boast yourselves above your measure of light; if ye do ye will be buffeted.
For such run into presumption, and so into reproof.
Which reproof that spirit will not take patiently, but gets up into presumption;
which is to be condemned with the light, in which is the unity,
which keeps from desperation and presumption.
They who go from the light, the enemy comes into them, and the envy,
and the manslayer gets up within and slays the man;
and no such one hath eternal life abiding in him,
for he is turned from the light which comes from Christ Jesus, the life.
All who dwell in the light which comes from Christ, come to receive the eternal life.
And here the love of God is shed abroad in the heart;
and dwelling in love ye dwell in God, and from the life the eternal love doth flow,
which life comes from the Father of life, whose love doth not change.
And so with the light (ye dwelling in it which leads to
the life) ye will come to witness the faith unfeigned,
and the humility unfeigned, and the faith which works by love, which purifies the heart;
waiting in the light which comes from Christ Jesus, this is received from him.
For with the light man sees himself; which (light) comes from Christ,
who is the author and finisher of his faith;
which faith gives him the victory over that which
he sees to be contrary to the light and to the word.
And this is the one faith;
and here the first Adam and the second Adam are known and seen.

[.signed-section-signature]
G+++.+++ F.

Let this be read amongst Friends everywhere.

[.centered]
=== Letter 150.

[.blurb]
==== To Friends, to live in love and unity together, in the power of God.

Friends all everywhere, in the life and power of God live and dwell,
and spread the truth abroad.
Quench not the spirit, but live in love and unity one with another;
that with the wisdom of God ye may all be ordered to God`'s glory.
And live all in patience one with another, and in the truth,
that ye may feel and see to the beginning, before the world and its foundation was,
in the faith which gives the victory;
that nothing may reign but the life and power amongst you.
And live all as the family of God in love, in life, in truth, in power,
having your house established atop of all the mountains and hills;
that ye may answer that of God in every man,
and the word of the Lord ye may witness to go forth among you and be among you.
So in this the Lord God Almighty preserve you and keep you.
And in the son of God`'s power live, for all power in heaven and earth is given to him;
who is to subdue all the powers of darkness,
and to make the kingdoms of the world his kingdom.
And none go beyond the measure of the spirit of God, nor quench it;
for where it is quenched it cannot try things.
So if any have any thing upon them to speak, in the life of God stand up and speak it,
if it be but two or three words, and sit down again; and keep in the life,
that ye may answer that of God in every man upon the earth.
To you this is the word of the Lord God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 151.

[.salutation]
Friends,

There was a time when the apostles preached Christ that died at Jerusalem;
and they witnessed him forth,
and brought (for proof) the prophets`' testimonies who prophesied of him.
And they that preached Christ`'s sufferings at Jerusalem,
showed the fulfilling of the prophets and the law, and all that was written of him.
And after,
the apostles preached Christ the substance (the end of the types
and figures) amongst them that had the prophets`' words,
and the law, and the outward temple; and they showed them out of the prophets`' words,
and out of the law, that that was the Christ that died at Jerusalem,
and suffered without the gate.

And then there was a time that the apostles preached Christ in them,
to them that did believe and had received him; "`Know ye not, that Christ is in you,
except ye be reprobates?`"
And, "`Christ in you, the hope of glory.`"
And, "`If Christ be in you, the body is dead.`"
And, "`They that are Christ`'s, have crucified the affections and lusts,
and all things are become new.`"
But this was spoken to them that believed, who where the saints,
to them Christ in them was preached, the substance of what the prophets prophesied of;
and to believe in him who was risen, the resurrection.
But to the world the apostles preached repentance, and to believe in Jesus Christ;
and taught faith towards God.
But to them who were redeemed out of the world,
in and to whom the son of God was made manifest, (who were brought to God,
the judge of all, and to the church in God, and to the innumerable company of angels,
and to the spirits of just men,
who were made perfect in him through faith towards God,)
preaching repentance and the doctrine of baptism was needless,
in whom it was fulfilled, to and in such as were brought to God.
He that can receive this may, for to it there is no private meaning.

There is a time of preaching faith towards God; and there is a time to be brought to God.
But such as are here deny the first priesthood,
and witness the second with the eternal spirit of God;
who witness him without father or mother, a priest forever,
after the order of Melchisedeck.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 152.

[.blurb]
==== To Friends, concerning openings, etc.

This is the word of the Lord God to you all.
In all openings and speakings let not the man be lifted up,
for that will not be the servant, but the master;
which is to be thrown down with that from whence the openings come.
Therefore keep down that which would he lifted up in the sight of the world,
for that doth (often) fall in the sight of the world;
but that being lifted up which answereth that of God in every man,
this is of the son of God, who is exalted above the world,
and was before it was made and created.

And every one dwell in the seed and life of God, and in that know one another.
And meet together, and keep your meetings,
that ye may see the Lord Jesus Christ in the midst of you.
G+++.+++ F.

[.centered]
=== Letter 153.

[.blurb]
==== To Friends beyond sea, that have Blacks and Indian Slaves.

[.salutation]
Dear friends,

I was moved to write these things to you in all those plantations.
God, that made the world, and all things therein, giveth life and breath to all,
and they all have their life and moving, and their being in him,
he is the God of the spirits of all flesh, and is no respecter of persons;
but "`whosoever feareth him and worketh righteousness, is accepted of him.`"
And he hath made all nations of one blood to dwell upon the face of the earth,
and his eyes are over all the works of his hands,
and seeth everything that is done under the whole heavens;
and the "`earth is the Lord`'s and the fulness thereof.`"
And he causeth the rain to fall upon the just and upon the unjust,
and also he causeth the sun to shine upon the just and the unjust;
and he commands "`to love all men,`" for Christ loved all,
so that he "`died for sinners.`"
And this is God`'s love to the world, in giving his son into the world;
"`that whosoever believeth in him should not perish.`"
And he doth "`enlighten every man that cometh into
the world,`" that they might believe in the son.
And the gospel is preached to every creature under heaven;
which is the power that giveth liberty and freedom,
and is glad tidings to every captivated creature under the whole heavens.
And the word of God is in the heart and mouth, to obey and do it,
and not for them to ascend or descend for it;
and this is the word of faith which was and is preached.
For Christ is given for a covenant to the people, and a light to the Gentiles,
and to enlighten them, who is the glory of Israel,
and God`'s "`salvation to the ends of the earth.`"
And so ye are to have the mind of Christ, and to be merciful,
as your heavenly Father is merciful.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 154.

O friends! keep out of that state, which is out of and below the chaste nature;
for all unchasteness, by the power of the Lord and his truth and light, is to be judged.
Therefore live in the truth and in the light of God, that keeps, you all chaste,
for in that is the unity, and out of that is the war.
For from the lusts are the wars and strife.
Oh! keep over that nature, that purity may flow, and righteousness spread,
and truth flourish, and love and peace abound in and amongst all the family of God.
Keep down the unchaste, keep down the adulterous eye,
and keep down the lust of the flesh, which is not of the Father but of the world;
and lust is against the spiritual fellowship, and spiritual union,
and spiritual dominion, for that would be as a lord, to lord above the spirit,
which the spirit of God is Lord over, and judges it.
Keep down the lustful heart and eye, for that leads from God,
and joins with the adulterate in any thing, or with any thing that is evil;
keep truth and a pure conscience, and there ye have an unspotted life,
in which ye may see over the spotted life, where no chastity nor purity is.
Therefore live in that which keeps you chaste, then ye follow Christ the Lamb;
for there are the holy joy, and peace, and comfort, and unity known,
in the life and fellowship with the God of life.
For what is the cause of all the lusting spirits to envy,
and of the wisdom that is sensual, earthly, and devilish,
but a living and a going out from the truth and the life?
Which (truth and life) is the mark of the high calling of God in Christ,
where the peace is.
And so the spirit of this world lusts to envy, it lusts to strife,
it lusts to contention, it lusts against the spirit of God; the lusts of the eye,
and the pride of life, and the lusts of the flesh, clothed with flesh,
covered with flesh, not with the spirit, such are unchaste, and follow the lust,
not the Lamb, and so live in that which the war proceeds from,
and in strife and contention.
And, therefore, mark that spirit with the eternal power of God,
for it judges with evil thoughts, being in the earth, and thinks all to be like itself,
being in the bad, and in the lust, and in the adultery; it judges all to be like itself.

Oh! therefore mind the holy life, the chaste life!
That is the bride`'s clothing, by which she adorns herself for her husband, Christ Jesus.
Therefore live in that which keeps your peace, there is your life and dominion;
that weeds may not grow, nor brambles, but that they all may be cut down and weeded out.
For those grow through the liberty of the flesh, and by that ye come to be darkened,
and lose your discerning and feeling; and there gets the beam into the eye,
by which ye come to judge with that judgment which is for judgment,
which should be judged down by the spirit of truth and peace.
And so live in the same peace with God, and one with another,
and have fellowship in the chaste life, and in the spirit and power of God.
And keep down that which lusts to envy, and strife, and contention, for that will not,
nor cannot bear true judgment, but will flatter and fawn, and sow dissention;
and so in the end will bring dishonour both to God and his people.
That can never abide true judgment or sound doctrine, for that adulterates from God,
and joins in marriage with that which is adulterated from God.
And so the unchaste follows the whore and the adulterer,
and goes to the marriage supper of the adulterer and the whore;
but the chaste virgin follows the Lamb, and goes to the marriage supper of the Lamb.
Therefore all live in the chaste life,
by which ye may follow the Lamb of God to his supper and marriage.
And keep ye all out of that from whence contentions, and strife, and wars arise,
which are the fruits of them that live in the lust,
which is seen with the everlasting power, the ground from whence strife, and contention,
and wars come, the unchaste, which live in the lust;
which lust will defile all that receive it.
Therefore, all Friends everywhere, your fellowship is to be in the gospel,
the power of God, and in the spirit, the fruits of which is peace;
in which ye all will be kept in dominion, pure and chaste to God,
and one towards another.
For all that come to the sabbath of rest must put off their old clothes,
which they have worn in their old works, labours, and travels.
For six days the Jews were to labour, but the seventh day was their rest,
which is perfection.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 155.

[.blurb]
==== Concerning the Light.

[.salutation]
Friends,

Ye that be turned to the light in it wait, in it meet together,
that with it your hearts may be joined together up to Christ, the head,
from whence the light doth come;
with which ye may see all the world and all the gatherings that are out of the light,
which are in the vanities of their minds, and in the rebelliousness of their hearts,
and stubbornness of it from the light.
But ye believing in the light and receiving it,
ye receive and come into the covenant with God, and peace with God;
and into that which gives the knowledge of his glory and of his image.
And this belief giveth the victory over the world, and brings unto God,
and into his likeness, and separates you from the world, and its likeness, and image,
and its fashion, which are out of the light; and its knowledge, and its wisdom,
and its honour, and its fear, and its love, and its rejoicing,
which are out of the light in the flesh, and in the iniquity, where the soul is in death.
But in the light rejoicing and walking,
ye receive the love of God shed abroad into your hearts,
which love rejoiceth in the truth, (mark,) in that which the devil abode not in.
With that ye know and will know the increase of God,
and know God and his law put in your minds, and in your hearts written,
where the fear is placed, where the secrets of the Lord are revealed, and the light,
which is the truth, comes to be walked in.
Here is a joy in the Lord where no flesh glories.
In this waiting, (in the light,) the world where there is no end it gives you to see;
and the power of the world which is to come, ye will come to see and be partakers of.
Which power ye receiving (who are in the light,) it brings you to become the sons of God,
and to be heirs of the world where there is no end,
and of the everlasting inheritance which fadeth not away,
and the riches which are durable, where no thief can come, nor nothing to rust or canker;
for that is out of the light that doth thieve, rust, or canker, and in the transgression.
Therefore, ye saints in the light of the most high God,
whose name is dreadful amongst you, and his power made manifest in measure,
and his glory appearing, walk worthy of the high calling!
Keep your dominion, keep your place of rest in the power and strength of the Almighty,
and meet together in the love, unity, and peace,
and know one another in this love that changeth not; which being received,
ye walk in that which condemns that which is changeable.
This love rejoiceth in the truth, and hath dominion over him that abode not in the truth,
but rejoiceth in that which the devil abode not in.
And here the spirit is received in which God is worshipped, the Father of spirits.
He that believeth here believes in the Lord, and shall never be confounded;
for he believes in that which doth confound and condemn those who are out of the light,
and gone from the word of God in the heart, and from the power of God,
and from the light of the glorious gospel, which is the power of God.
The God of the world hath blinded their eyes that abide not in the truth,
they are gone from the light which is the truth;
and all that are blinded by the god of the world,
these are out of the light and out of the truth.
Therefore ye being in the light, and to it turned,
(the light of the glorious gospel,) the image of God is seen,
and the glorious gospel received.
Therefore walk in the light as the children of the light,
and know the wisdom that is of her children justified;
that ye may answer the light in every one (that comes into the world) that hateth it.
And keep your habitations,
that ye may every one feel your spring in the light which comes from the Lord,
and feel your nourishment and refreshment;
which waters the plants and causeth them to grow up in the Lord, from whom the pure,
living springs come.
And here is the water which is the witness in the earth, which doth wash;
and here comes the spirit to be known, the witness which doth baptize,
and the witness the blood, which doth cleanse, which agrees with the witness in heaven.
So, he that believes hath the witness in himself.
(Mark and take notice.) And so, ye being in the light,
every one in particular feed upon the bread of life which comes from above,
which nourisheth up to eternal life; wherein as every one grows up,
here every one gives glory to the Father, and to the son,
and knows the light which is the way, the truth, and the life.
Every one of you that are turned to it, ye are in the one way, truth, light, and life,
feeding upon the one bread which comes from above;
which whosoever doth eat of lives forever, and shall never die.

Let this be read among all Friends everywhere, in this nation and elsewhere,
that to the light are turned and in it are kept, that in the unity they may all be kept.
And in it God Almighty preserve and keep you, that ye may feel his promises,
which are to the seed; and know the seed to which the blessing is,
and know the flesh of Christ, that ye may be flesh of his flesh.
And friends, live at peace among yourselves, waiting upon the Lord;
and the Lord God of life and peace be with you.

Let no Friends be discouraged; but walk in the truth and the love of it, and to it bend.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 156.

[.blurb]
==== To Friends, to keep in that which is savoury.

All Friends,

I do warn and charge you in the presence of the living God, in his wisdom and life keep,
that no ill savour be nor get up amongst you.
For ye are the salt of the earth, to season and to make savoury to God;
but if the salt have lost its savour, it is henceforth good for nothing.
Therefore I do warn you all, mind that which doth keep your peace;
whereby ye all may grow in love, and know Christ in you all, in whom is peace.
Ye are the light of the world to answer the light in every one,
that with the light they may see your good works, and by seeing them,
they may glorify your Father which is in heaven;
for all deceit is judged and condemned by it.
And every one keep in the measure of the life of God,
and see that there be no strife nor presumption among you;
but all serve one another in love, and let that of God guide every one of you,
in which ye may have unity one with another and with God.
And in his life wait to receive power to bind and
chain all down which is contrary to truth.
And so, in the life and power of God, the Lord God Almighty preserve you to his glory.
Amen.

The light is precious to him that believes in it, and walks according to its leading.
So, while ye have the light, walk in the light and live in the light, Christ the truth;
that ye may, through obedience to it, be the children of the light and of the day.
For the light and the truth were before darkness and deceit were.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 157.

[.salutation]
Friends,

By the wisdom of God were all things made,
and by the wisdom of God must all things be ordered again to God`'s glory.
Transgression and sin bring death and destruction;
but that wisdom is hid from all their eyes that live in sin,
by which wisdom all things were made and created; which was, before sin, death,
and destruction were.
And so, that is it, which the creatures and creation of God must be ordered by,
that wisdom which made them, and doth not change;
which is hid from death and destruction,
and from that which is in the transgression of life, and must not rule.
So Friends everywhere, be tender to those that have forsaken any thing for truth.
And if that their parents have put them out from them,
or their masters put them away for truth`'s sake,
and them that are put out of their places for truth`'s sake,
such in the truth receive and cherish;
that they may be kept in the service of the creation to God`'s glory,
answering that of God in all.
For every one is to abide in their places, and there to be faithful,
except they be put out, or put away, and be buffeted for no fault, and take it patiently;
that is thanksworthy.
And do good unto all, especially to them that are of the household of faith,
and be as the church of God, guided in the wisdom of the Most High,
who causeth his rain to fall upon the just and upon the unjust.
And so, be ye merciful as your heavenly Father is merciful.
And know the seed of God that is heir of the promise in every one of you, and the wisdom,
by which all things must be ordered to his glory,
who upholds all things by his word of power.
By which word of wisdom all things were created,
and must be ordered again to the glory of the Creator;
in which man will be kept clean unto God, and honour God with his substance,
and glorify God in his spirit.
Whereby every one`'s conversation will come to be ordered aright,
and ye come to set down in the heavenly places in Christ Jesus;
and to know the high calling of God in Christ Jesus,
who calls out of darkness into the light, out of death into life.
For he that calls, is holy, and calls into holiness,
without which none shall see the Lord.

And all Friends, be faithful in the seed and life of the Lord God;
that is it which abideth in the love of God forever,
where every one hath his bread which comes down from above.
That is the birth, which abideth in the house of the Lord God forever,
and shall go no more forth; which is greater than he that is in the world.
And in the seed and life keep your meetings with God and one with another.
So in that the Lord God Almighty preserve you all to his glory.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 158.

[.blurb]
==== To Friends, to dwell in peace and love.

Friends and brethren everywhere, dwell in that which makes for peace and love;
for "`Blessed are the peacemakers,
for theirs is the kingdom,`" that stands in righteousness, joy,
and peace in the holy ghost, and in power.
Therefore seek the peace, in which is the welfare and good of every one.
And take heed of strife and contention, for that eats out the good, and does not edify,
nor make for peace, for it is love that edifies the body.
Therefore keep in the seed, and know that which was before enmity was,
in which there is both peace and life.
And all be careful to watch over one another, for one another`'s good; and be patient,
and keep low and down in the power of the Lord God,
that there ye may come to enjoy the kingdom of peace, and sit down with Abraham, Isaac,
and Jacob in the same.
For blessed are all ye that lie down in the power of the Lord, and rise up in it,
and in faith remain;
through which power ye come to be preserved and united to the God of life and truth.
And take heed of any words or carriage that do not tend
to edification and building up in the love and life.
Therefore, ye that have tasted of the power of God, and of his good word,
and of his light, wait for wisdom, and in it walk, that ye may be preserved in unity,
in the light and life, and in fellowship with God, and one with another;
that to the Lord God ye may be a good savour, and to him a blessing in your generation,
strengthening one another in the faith, in the grace,
in the word by which all things were made and created.
And keeping the word of patience,
herein ye will see the Lord keeping you from all the temptations,
which come to try them that dwell upon the earth;
by which word of God ye may all be preserved in the sweet and holy life,
in which there is unity in the word, which was before enmity;
which word doth fulfill the words.
Therefore in that live, that ye may all feel life abundantly through the light and power,
that come from the word which was in the beginning;
through which immortal word your immortal souls may be brought up to the immortal God,
where is joy, peace, and comfort.
So, above all things, live in that which stops strife, contentions, and janglings,
and live in that by which ye come to serve one another in love, even in the love of God,
which thinks no evil, nor envies not, neither is it easily provoked.
Therefore, live in that which is not easily provoked, and thinks no evil;
which fulfils the law, which is love out of a pure heart.
And let not prejudice boil in any of your hearts,
but let it be cast out by the power of God, in which is the unity,
and the everlasting kingdom;
that ye may all witness your being made heirs of the same kingdom of peace,
and to be inheritors of it, sitting down in the same, knowing your own portion,
and increasing in the heavenly riches.
And this above all strife, that is below, and the man of it,
which is born of the Egyptian woman, which genders to bondage.
Therefore know the seed, the second man, the heir of the promise set over all,
and the blessing and presence of the Lord, which were before strife was.
Therefore know the seed of life and peace to reign in you all,
which possesses the kingdom, where there is no end.

The grace of our Lord Jesus Christ be with you all, to teach, season, and establish you,
which brings your salvation.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 159.

[.salutation]
Dear friends,

All dwell in the everlasting seed of God, Christ Jesus,
in whom ye have health and strength, life and dominion, and power over all weaknesses.
And keep your minds in the strength of the Almighty, and not in weakness,
nor in the infirmities, but in the Lord`'s power,
which was before weakness and infirmities were;
and then in that power ye will find life and refreshment from the God of strength.
And so in the power of God, that is over all,
keep your minds in the life and peace of God, and in the assurance of him and his love;
and so, in that dwell, and live in the dominion of God, in his love, and life,
and strength.
And be of good faith, and of a valiant mind for God`'s truth upon the earth,
in the power, life, truth, and seed, in which ye have dominion, peace, wisdom,
and the blessing of God upon you, and in you; and in that dwell,
and know that blessed seed your crown and life.
No more, but my love.

For the comfort of the people of God, and their encouragement to be faithful,
and to put their trust in him, who performeth all his promises.

[.postscript]
====

Postscript.--The people that know their God, they prosper and prevail,
and they that understand shall instruct many: and though they may fall,
and go into captivity, and be spoiled now; yet when they shall so fall,
they shall be helped; and when they are helped, many shall cleave unto them.
And some of understanding may fall, for to try and purge them, and to make them white,
till the time be out: for there is a time appointed to liberty,
for the faithful sufferers, that come from and through the great tribulations;
and "`Michael shall stand up for the children of
thy people,`" and every one shall be delivered,
that shall be found written in the Lamb`'s book of life.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 160.

[.blurb]
==== To Friends in Bristol.

All my dear friends, folly and wickedness will have an end,
but the word of the Lord will have no end, but endureth forever.
So, feed upon the milk of the word, ye babes,
that ye may live by that which comes from it, which doth endure.

G+++.+++ F.
