== Letters 186 &#8212; 201

[.centered]
=== Letter 186.

[.blurb]
==== To Friends in Barbados.

Friends, who have known and tasted of the power of the mighty God of heaven and earth,
and of his light and life, be faithful in the power, light, life, and truth,
to the spreading of the truth abroad;
with which ye may answer the truth in the inward parts in every one.
And dwell in that which binds and chains, and gives to see over the world; that life,
wisdom, and power may reign among you that are turned to the life, and believe in it,
who come to receive the light of life, Christ, the power of God.
Be faithful, and spread the truth abroad, and walk in the wisdom of God,
answering that of God in every one, and write, speak,
and send books abroad into the countries, and islands, and nations, or main land,
as ye are moved;
that the sound of the trumpet of the Lord`'s host may be heard in the nations and islands.
And be faithful and valiant for the truth of God upon the earth; that is the truth,
that the devil is out of, and abode not in; in that dwell and live,
in unity and peace one with another.
So, the God of love, life, and power, and wisdom be with you!
And ye that are turned to the light, and gathered into it, meet together,
and keep your meetings, that ye may feel and see the life of God among you,
and know that in one another;
for that keeps down and lays low all that which is out of the kingdom.
So, know the power of God, and keep your peace therein;
that ye may all grow up in the increase of God, (mark,
in the increase of God,) and feel his presence among you.
For "`where two or three are gathered together in my name,`" saith Christ, (that is,
in the power,) "`I am there in the midst of them.`"
In this meeting, in this gathering, Christ is felt in the midst.
Who feels the power of Christ, feels Christ, for he is the power of God,
and the Emmanuel with them; but who go from God, in the transgression,
are in the first Adam, where death reigns, and darkness;
and this is the state that is reprobated.
But who are turned to the light, Christ Jesus, to the Emmanuel,
they know the interpretation thereof, God with us; who redeems out of transgression,
and out of death, darkness, and sin; who being witnessed, the state of fallen man,
that was drove from God, and the state of being brought to God again,
is witnessed by Jesus Christ, the covenant of light.
In which covenant, which is light, the Lord God Almighty preserve you all!

Ye may write, how things are with you in the island.

G+++.+++ F.

[.centered]
=== Letter 187.

[.blurb]
==== This is to go among Friends.

My dear friends,

Dwell in the love of God together, for that edifies you all, and by that ye are built up;
and who go from that, pluck down with enmity, and discord, and wrangling, and quarreling,
and disputing; and are puffed up with high-swelling words,
and are large in their worldly wisdom, and earthly knowledge in a show,
to tread upon the simple; and are of the great comprehension.
Therefore keep over that spirit, for that will not stand to the end,
although it would be lord; it is scorched, when the heat of persecution comes.
And therefore stand faithful.
For that which runs into janglings, and disputes, and contentions, and questionings,
is the disobedient.
That was the devil`'s work in the beginning, which brought Eve out of her habitation;
and that is the work of his servants in the fall,
to bring the innocent out of their habitation, to question, reason, and jangle with them,
to bring them out of their habitation.
They will say, they must not meet together,
such as are gathered in the name of Christ Jesus, that never fell, who is above Adam,
that fell.
And thus the devil would lay all waste, and make the world like a wilderness,
and break down the bounds of the righteous gardens and plantations,
and would break them down into his wilderness, and lay them barren and waste.
And so, when they are gone from the truth themselves, the devil is got into them,
and would keep them from meetings, to draw others into the same,
who are gathered into the name of Jesus,
and are come to sit down in the heavenly places in Christ Jesus,
and are found with the flock that lie down at noon-day.
And so, that fallen spirit would bring the saints to forsake their assemblies,
and would make them like a wilderness; if he cannot, he will throw dirt upon them,
and backbite them, and prejudice them, and slander them, and speak evil of them,
and strive to sow discord amongst them, and preach up some outward things amongst them,
to bring them into an outward fellowship, from the immortal power and gospel fellowship,
and fill them with earthly wisdom and knowledge, and understanding, and carnal policy,
with quirks, tricks, turnings, and windings, to over word and ensnare the simple,
and to bring them into questioning.
And so, this spirit is to destroy, ruin, and lay waste, and to rob and beguile,
and would destroy, if it were in its power, the saints`' fellowship and worship,
and if it were possible deceive the elect.
For sometimes it will come in the show of worship and feigned humility,
and other times with Esau`'s tears; but all the strength of it is set,
to lead the innocent out of his habitation, and to destroy and devour him.
And so, being adulterated from the true spirit, the true light, and the fellowship in it,
it runs into all the secret evils, inward adultery, and outward adultery, uncleanness,
and fornication; and being in the evil, darkness, and uncleanness,
judges all like unto itself with it evil thoughts,
and casts out its flood of evil speaking and wickedness upon the righteous and just,
the saints of the Most High, whose garments are clean and pure.
And so, this spirit will cry down the saints`' fellowship in spirit,
and worship in spirit and truth,
and their fellowship in the power which was before their forms were, or the devil either;
and when it cannot get them down, and break their fellowship,
to forsake their assembling together, (which is contrary to the apostle`'s doctrine,
and the churches in the primitive times,
before the apostacy,) and when they see they can
neither break their fellowship nor worship,
then they say, away with your forms;
and cry down forms to such as be in the power of godliness.
And that spirit`'s work, that doth so, is to bring into such forms in time,
which are out of the spirit, and truth, and power of God,
in which the saints have fellowship and refreshment;
in which God is worshipped in that which is above, and was before time.
And that contrary spirit its work is, to bring into the many invented forms in the fall,
and sometimes runs out of all right form into confusion, and out of all order of life,
in which the saints of the Most High, that walk in the spirit, are,
in the fellowship and power of life, having the order of life amongst them.
And therefore, all Friends, keep your habitation everywhere in the truth of God,
and let your lights be shining, and your lamps burning, and have oil in your lamps,
and salt in yourselves to savour withal, that he may grow up into Christ Jesus,
by whom all things were made, that were made; that through him ye may know all things.
And so, live in him, that destroys the enmity; and in him sit, in Christ Jesus,
in whom ye have unity, life, peace, and salvation.

The honour was given to him that never changed, nor never fell, who is Christ Jesus,
and ye in him are partakers of this honour; and they that change and fall,
do not know this honour, but are a dishonour to him.

G+++.+++ F.

[.centered]
=== Letter 188.

Friends,

Live in the seed of God that destroys the devil,
who is the author and cause of wars and strife,
and bringing of men and people into the earth, where the war, strife, and pride are;
here the outward swordsmen have not learned yet to beat
their swords and spears into ploughshares and pruning hooks.
Yet ye that are in that seed, see that ye accuse no man falsely,
that hath the sword of justice, which is to keep the peace,
and is a terror to the evil doers, and to keep down the transgressors,
and for the praise of them that do well; this is owned in its place.
But he that killeth with the sword, must perish with the sword.
So there was a time the Jews were to fight with outward weapons, with sword, and spear;
but there is a time, when nations shall not learn war any more,
but shall come to that which shall take away the occasion of wars,
which was in the beginning before wars were.
And Friends take heed of blending yourselves with the outward powers of the earth.

All Friends, dwell in the life, and power, and seed of God,
in which ye may be kept in the son of God`'s kingdom,
and preserved in his dominion out of all changeable things;
in that God`'s blessing will be with you.

In the seed of God is the stayed state, and in that are the life and peace with God,
and the offering that satisfieth God,
and that perfecteth forever them that are sanctified.
And the seed bruises and destroys the serpent`'s head, who is the prince of the air,
the prince of darkness, the tempter and the troubler;
in which seed is peace and life enjoyed,
and by the wisdom of it be ordered to God`'s glory.
And there the reign of Christ is known, who is come to reign and to rule.

G+++.+++ F.

[.centered]
=== Letter 189.

[.blurb]
==== To Friends in New England and Virginia.

My dear friends, Robert Hodson, William Robinson, Marmaduke Stevenson, Peter Pearson.
William Brend, William Leddra, and the rest of Friends in New England and Virginia,
be faithful to the Lord in the truth of the Lord God,
and in his power and wisdom be valiant for it upon the earth, and spread it abroad,
and confound deceit.
And dwell in the power of God, and stand in it, which comprehends the whole world;
that through it ye may answer the witness of God in every one, and be a dread to nations.
And go on in peace, and love, and unity, one with another,
and keep in the wisdom of the Lord God;
that ye may be answerable to the witness in every one to whom ye preach.

And take heed of judging one another in the sight of weak Friends,
but dwell in the power of the Lord God, and that will keep that down in every particular,
which is to be judged;
through which ye may judge the whole world that lies in wickedness.
Therefore, dwell all, (I warn you from the Lord God of power, of life,
of heaven and earth,) dwell in his power, and wisdom, and life,
that in that ye may have dominion over the world, and the adversaries in it,
and live in it; through which ye will feel the preciousness and weight of truth,
which now is going over all the world.
And to all nations of mankind the everlasting gospel, the power of God,
is to be preached, through which life and immortality shall come to light;
in which power is the fellowship.
Therefore, this is the word of the Lord God to you all,
those that are convinced by the power of the Lord God and the light,
let them dwell in it, in which they may have unity.
For the Lord hath a seed that ways, if ye in patience all of you wait,
and not matter the weather, the storms, the winds, the hail, the rain,
when ye are to sow the seed, nor the rough ground that is to be tilled.
For the husbandman waits patiently after the seed is sown;
there is a winter before the summer comes.
And there must be a great work before the misty heathen be cleared in their understandings,
(that are so naturally,) and the dark air be driven back,
and the prince of life and light be witnessed.
Dwell in the life and in the light; for the great professors of spiritual Babylon,
the mother of harlots, that are full of craft, will be brought down;
and that must be witnessed, before ye know the bride made ready for her husband.
So live in patience and in peace, and in the weighty wisdom of God,
and then ye will see the end of all frothy spirits, that will not abide the trial.
Therefore, friends, keep ye in the power of the Lord God,
and dwell in love one with another, and in the pure power and life of truth,
and the seed of God which ye first kept in;
that ye may be kept over all light and airy spirits,
that will be up and down like a tempest, corners and goers to the seed;
that ye may stand in the seed which is everlasting.
In that the Lord preserve you.

Ye may write over how things are there; for truth is well here,
and spreads abroad in the world in other nations, and is of a good report.

G+++.+++ F.

Reading, the 15th of the 8th month, 1659.

The Lord is king over all the earth,
and Christ hath all power in heaven and in the earth;
and he is King of kings and Lord of lords,
let him rule and reign in all your hearts by faith, and exalt him in the land,
and in your assemblies.

G+++.+++ F.

[.centered]
=== Letter 190.

O friends! have an esteem of truth and God`'s glory!
Keep down all inordinate affections,
and have an esteem of truth above your lusts and earthly things, worldly riches,
and goods, and mind the example of the old world, when the sons of God saw,
the daughters of men were fair, they took unto them wives of all that they liked;
and so made no distinction between the righteous and the wicked.
Which grieved the Lord God, that he said, his spirit should not always strive with man.
And therefore he shortened his days to an hundred and twenty years,
which before were many hundred years.
Though Enoch, Methuselah, and Lamech, and the holy men of God,
their marriages God did not judge; but when the sons of those holy men,
which were called the sons of God, went to the world for wives,
they slew the spiritual birth in them, and quenched the holy spirit of God in them,
and corrupted the earth, and filled it with cruelty,
and followed the imaginations of their own hearts`' lusts continually;
insomuch that they grieved the Lord, and he repented that he made man.
For he saw, all flesh had corrupted his way upon the earth, saving Noah, a just man,
with his family, who walked with God, and did not join with the wickedness of the world.
Therefore God destroyed the old world; and the beginning thereof was these bad marriages,
as Jude and Peter saith,
"`They followed strange flesh,`" by which they came to be corrupted;
and therefore God sent a flood, and destroyed the old world with its ungodly deeds.
And there is your example, that marry with the world.
Gen. 6.

And doth not the Lord say to the children of Israel,
"`Thou shalt not give thy sons nor thy daughters in marriage with the heathen.`"
And were not such as did so, reproved by the Lord and his prophets?
As ye may see through the scriptures.
And doth not the apostle say, "`Be ye not unequally yoked together with unbelievers;
for what fellowship hath light with darkness, or Christ with Belial,
or a believer with an infidel?`"
For how many thousands of the Jews did the Lord destroy,
who went and married with other nations, and pleaded liberty?
And did not Phineas run one through, and his heathenish women?
And so, must not all such be run through with the sword of the spirit of God?
And the Lord said,
"`Phineas hath turned mine anger away from the children of Israel,`"
when the Lord had destroyed twenty-four thousand of them.
And doth not the world call such, bastard and hypocrite Quakers, and not faithful,
that go to the world for a wife, and to the priests to be married?
Oh! that ye should profess truth, and go from its power and life,
and so corrupt yourselves, and to have no more esteem of your bodies,
which God hath so honoured, and made them vessels of his mercy,
to put his mercy into! and have no more esteem of God, his truth nor his people,
but to esteem your affections and lusts above them all,
and to make yourselves a talk and a laughing stock, by going into that,
for which ye are judged of God, and of all his people,
and of that of God in your own consciences also!
And do not Friends buy burying-places,
because they cannot give their dead bodies to the world, no more than Abraham could?
And ye that profess yourselves to be quickened by Christ, and made alive by him,
to give your bodies to them that are dead in sins and trespasses,--Oh,
ye make yourselves ridiculous both to God`'s people and the world,
and come under the judgment of both, and of God and the scriptures,
to be such as follow strange flesh, and corrupt the earth, like the old world!
Ye bring burdens upon the just.
But God will shorten your days, as he did the old world`'s, except ye repent;
as ye may read, Gen.
6+++.+++ And therefore mind God`'s ordinance,
and then ye will know God`'s joining by his spirit and by his power.
And be not corrupted with them, that follow strange flesh, and corrupt themselves,
that creep among you, and would be called by your name,
which the priests and the world call bastard Quakers.
And therefore keep the gospel order, which is the power of God,
(before the devil was,) and the government of Christ Jesus,
which destroys the devil and all his works.

G+++.+++ F.

[.centered]
=== Letter 191.

All Friends everywhere, that are convinced with truth, and profess it, and own it,
keep to the single language, the good spirit, the light of Christ Jesus leads to it;
and that which goes from that, which doth not live in it, is to be judged.
And then, if man or woman seek to get gain by speaking the improper, untrue language,
and flattering language of the world, which is in confusion,
the Lord may take that gain away from them.
For plural and singular was the language of God, and Christ, and all good men,
and of the prophets and apostles; but the confused world, that lies in confusion,
cannot endure it, who live not in the fear of God,
neither follow the example of good men, but are in the double tongue,
quenching the spirit, and hating the light of Christ Jesus, which is single.
And so all Friends, train up your children in the same singular and plural language;
all masters, mistresses, and dames, or whatsoever ye are called,
that do take Friends`' children, that are in the singular and plural language,
it is not fit for you to bring them out of it,
neither to force nor command them otherwise, to please your customers, nor to please men;
for if they should pay two or three for one, that would displease you,
who would have them to speak two or three, when they should speak singular,
thee and thou to one.
And so, do not lose that testimony, which slays the world`'s honour,
and do not go into the custom of the world`'s fashions or commands,
nor force others from that, which is the language of God, and Christ,
and all good men and women, into that which is contrary to God and Christ,
and all good men and women; for there must be,
and always was a distinction betwixt one and many.
For if in your practice ye should not do it, but let one have many things,
when he should have but one thing, ye would think to suffer wrong,
and your servants to do that which were not righteous; and so,
do not they speak that which is not righteous, when they say many for one,
and nonsense and confusion?
And therefore keep to the proper, sound, single language.
For indeed, I did hear some that were troubled at their apprentices and servants,
for saying thee and thou to one, and because they would not say the word you; and such,
who have known the language from their childhood.
And therefore that selfish, man-pleasing,
and daubing spirit must be put down with the spirit, and condemned with the light,
else ye will presently be ridiculous to the world, and to all men, and they will say,
ye are not so as ye were in the beginning; and so follow the customs of the world,
and not the practice of Christ, and all good men.
And so, this is written that all may fear the Lord; and they who have done so,
may do so no more, and that others may be warned, and not to go into such things.
But mind the truth and spirit of God, the light of Christ Jesus,
that none of the free born may lose the true language,
and speak half the world`'s language,
and half of the people of God`'s. For to say to Friends, thee and thou,
and to the world you, that is hypocrisy.
And therefore for all hypocrites,
and hypocrisy and dissembling to be kept under judgment,
for that is a dissembling with the witness of God.
For ye see the outward Jews, when they went from the law of God,
in process of time spake half Hebrew, and half Ashdod.
And therefore, to prevent all dissembling and hypocrisy,
keep to the spirit of God and light of Christ Jesus,
that the Jews inward may not have a mixed language, no more than the Jews outward,
to speak half the confused language of the world, and half the true language.
Nor to the world speak confusedly, to speak the plural for the singular,
and when ye are among the world, speak as the world doth;
and when ye are amongst Friends speak as they do:
this spirit is not from the spirit of God, but is hypocrisy and for judgment.
And so let the truth have its passage in all things, and speak true words, and not false,
with the light ye will see; who act contrary to it, will be condemned by it.
So let Friends be distinct from all the world in their language, in their ways, in love,
and in their conversations; for in that ye are over the world,
and judge them by scripture, by grammar, and accidence, and all other teaching books,
for ye have them all on your side to hammer them down withal,
who follow neither scriptures, grammar, nor accidence, nor their new teaching books,
and are judged by them all, and the spirit of God also, which leads to one,
and to divide and distinguish singular from plural, many things from one thing,
and one from two and three; and many men and women from one, many ways from one,
many churches from one, many fellowships from one, and the many words from one,
and the many gods from one, and the true Christ from the many antichrists and false.
All this is distinguished and known by the one spirit,
the light and power of Christ Jesus, which gives an understanding.

G+++.+++ F.

Let this be sent abroad, that all may read it over.

[.centered]
=== Letter 192.

[.blurb]
==== A general epistle to Friends.

Friends,

In the fear of the Lord God live, departing from sin and evil,
as it appears in your own particulars, and therein ye will receive the wisdom of God,
by which all things were made and created;
with which wisdom they may be ordered to the glory of God, that created all things.
And with that wisdom use all things,
and order all that are under your hands and dominion,
to the glory of him that created them.
And in this ye will feel the Lord God going in and out amongst you, and to be with you,
and his blessing and presence with you,
(in your actings,) and he over all giving you dominion in his wisdom, power, and life;
that with that ye may come to answer that of God in every one,
with which your minds should be guided up to God.
And in that ye will be a good savour to God,
and in the hearts of all people that live up to the witness,
and are led by the witness of God up to God.
And such as go from it, upon them the law of God is to be added,
and they by it to be stopped and limited; which law is a praise to them that do well,
who come from under the occasion of the law.
And in this that eye is opened which beholds God and his law,
which answers that of God in every one; which when men go from that of God in themselves,
the law takes hold upon them.
Which when Adam went from, he transgressed the law of God,
when he went from the life and image of God within him; and then the law came upon him,
which was not made for the righteous, but for sinners and transgressors.
And in this stands the covenant of works,
the law of works that brings under and yokes the man down;
which Christ the covenant of God, and of life, and of peace,
redeems men from under this law;
and the law of the spirit of life makes free from the law of sin and death.
So Christ, the covenant of God being felt,
the law of life is come and witnessed within man again; and to such,
they that are in the wisdom of God, will be a praise, and your moderation will increase,
your temperance will increase,
your knowledge of God and his son Jesus Christ will increase,
whom to know is eternal life; and this will not be lacking.
And so as ye are kept in the wisdom of God, and in his life and power,
ye will see the law that goes over all transgressors,
which was added because of transgression.
Which life lets you see to the higher power, which was before any transgression was;
because of which the law was added upon man, when he went from that of God in himself.
Which, (as I said before,) every true christian,
(which is a christian indeed,) witnesseth the law of life in Christ,
which sets free from the law of sin and death; and such come to see and feel him,
who was before any transgression was.
And so as to the Lord God ye are kept faithful in your generation,
and in his fear are preserved in humility and mercy, doing good and justly,
the jaws of the wicked will be broken, and ye will feel the Lord`'s blessing upon you,
and come to know the seed in yourselves which inherits,
which is the heir of the promise of the world without end.
And the power of an endless life you will feel in Christ, the seed,
in whom the words of the prophets and apostles are fulfilled;
and therein is unity and love, righteousness and peace,
even in him who bruiseth the serpent`'s head, that feeds upon dust.
Here there is nothing fed upon, but life, yea, the life, which was with the Father,
before the world began, which is Christ Jesus.
And who are in this, are in the thing the scripture testifies of.
And this hath been wanting in Christendom.
They have had the words of the prophets, Christ, and the apostles,
and been on heaps about them, not being in the seed, Christ,
who is the end and substance of them; who is the light and life, righteousness, wisdom,
and truth, which makes free from the adversary, who is the cause of strife.

From a lover of your souls`' eternal good,
and of your establishment in righteousness and peace, in this day of the Lamb`'s power;
glory to the highest forever!

G+++.+++ F.

[.centered]
=== Letter 193.

[.blurb]
==== To William Ames.

Dear.
William, thou hast a fine compass in Holland and Germany,
and under the prince of Palatin`'s government:
and there is a seed in Poland that desires Friends.
So in the seed be faithful, which is immortal,
and is the heir of the world where there is no end.
And so, in that be faithful, and spread the truth over that part of the world:
for the Lord hath a vine and a mountain to be set up that aways,
and a standard and ensign held out to other nations.
So, in the power of the Lord God, and his wisdom and seed,
the Lord God Almighty preserve thee!

G+++.+++ F.

[.centered]
=== Letter 194.

Dear friends, who have found the better part, and chosen the better thing, the one thing,
which lasteth forever, which is the ground of all true rejoicing and joy,
in whom ye have all riches and life, and the blessings, and the immortal power,
to be your crown and covering.
And it may be, there will be a time of shearing and clipping;
but the earth is the Lord`'s, and the fulness thereof.
So, mind him to be your portion, and the seed Christ your all, and your life;
and fear not losing the fleece, for it will grow again.
And keep your meetings in the name of him that never fell,
which is above all the meetings of Adam`'s sons and daughters in the fall.
And keep in the fellowship in the gospel, which is the power of God,
which was before the devil was;
and this fellowship is above all the national fellowships in the fall of Adam.
And keep in the worship of the Father in the spirit and in the truth,
which the devil is out of,
and in that ye will live in the truth and spirit in yourselves,
and walk in unity in the same;
and then ye are over all the will-worships in the fall of Adam,
where they are in the strife about them.
And who are come to the church in God, do see above all the churches of Adam in the fall,
drove from God.
And as the outward Jews suffered by the outward Egyptians and Babylonians,
and they persecuted them and killed their children;
so the spiritual Egyptians and mystery Babylon persecute
and would kill the Jews in spirit,
that worship God in the spirit, whose praise is of God, and not of man,
and such have none from fallen men, but by them are persecuted.
But all such go, as dumb before their shearers;
for he that gave his back and his cheek to the smiters, overcame, and reigns,
and hath the victory and the honour, who is Christ, the amen, the first and last,
the top and corner stone; in him sit down, in life, and peace, and rest.
So no more, but my love in the everlasting seed, the second Adam,
that never fell nor changed,
whose love is above all the love in Adam`'s house in the fall.

G+++.+++ F.

[.centered]
=== Letter 195.

Friends,

All that are moved of the Lord by his power, light, and life, to go into other nations,
as messengers of his covenant of light, to preach the gospel,
according to that which shows the secrets of every man`'s heart,
wherein nations are brought into covenant with God, and redeemed out of tongues,
and people, and kindreds: keep your feet upon the top of the mountains,
and sound deep to the witness of God in every man; then will your feet be beautiful,
that publish peace; and to the captives proclaim liberty,
with your feet upon the mountains publishing peace, binding up the brokenhearted,
having oil of gladness for them that mourn.
And this is the word of the Lord God to you,
keep ye atop of the heads of all the mountains of sin and opposition, in innocency,
meekness, and true humility, in the fear of God;
that in his dread and wisdom ye may all be kept, and in the fear of the Lord stayed.
And dwell in the "`light of Christ,
that doth enlighten every man that comes into the world,
that all through him might believe;`" and bring all to believe in the light,
to give them the knowledge of the glory of God in the face of Jesus Christ,
from whom the light comes that they are all enlightened with;
and that they may come into the covenant of light with God and his people.
And so, dwell in the power of the Lord God, that ye may comprehend the world,
and see over it all: and keep ye over all the unclean spirits, and execute true judgment,
answering to that of God in every man; and here is the saints`' honour.
And this is the word of the Lord God to you:
enter not into consultings with the wrong nature, lest ye consult with the adversary,
whose head must be bruised; and lest in the meantime, that blind your eye,
and raise up a light spirit in you, and take you captive.
But dwell in the power, dread, and fear of the Lord God,
that ye may answer that of God in every man, and stop the mouth of that which opposes;
that ye may blind the eye that will not see the light,
and the ear stop that will not hear it, for that must be judged.
For that is it that keeps all from conversion, and that is the seed of the serpent,
which must be bruised with the seed of the woman, yea, the head of it:
and keep atop of the head of it, that ye may answer that of God in every man;
and be kept atop of the contrary, and tread it under feet.
And so, the Lord God Almighty keep you in his power and wisdom,
and by it bind the unruly; and when ye have bound them, then ye may speak to them,
and by it fetter them; then ye may catch them when ye will, when they are fettered.
And get the yoke upon the wild heifer; then will ye save yourselves from a push,
and bring them down, and order them with the power, and reach to the witness.
And see, that ye keep the bit in the wild horse`'s mouth,
whereby his head may be held down: and howsoever, see that he be bridled,
then with the power he will be ordered; though he snuffs and snores,
the bridle being kept in his mouth, he is held down by it: though he cries aha, aha;
that is above the witness.
And when this is done, being kept in the power, ye will know him,
that rides meekly upon the foal of the ass, (the colt,
the foal of the ass,) to Jerusalem, the highest place of worship;
who brings the prisoner out of the pit, where there is no water.
Christ, the same today as yesterday, and forever.
And the Lamb gets the victory, he that sits meekly upon the colt, the foal of the ass,
he it is that gets the victory, he by whom the world was made, who is not of the world,
that treads upon the highest worship in the world.
Lay hands upon no man suddenly,
I warn and charge you all in the presence of the living God,
but touch the witness of God in every one.

G+++.+++ F.

[.centered]
=== Letter 196.

Dear friends in Jamaica, and elsewhere, who know the truth of God,
and have been sufferers for the same, all live in it, which the devil is out of;
that ye may all be preserved in peace and freedom.
For truth brings to the noble mind, spirit, and nature, and seed,
which never will bend to sin and unrighteousness, nor ungodliness whatsoever,
nor to the author of it.
And therefore all walk in the truth,
that ye may all come to honour the Lord God in your lives and conversations,
in your words and dealings, doing truly, justly, and righteously unto all people;
that God may be glorified amongst you.
And that ye may come to be as lights to the world, and the countries about you,
so that by your light they may come to walk out of their dark, unrighteous, ungodly,
and corrupt ways, which the corrupt people walk in;
but the holy and the sanctified ones are of a more noble nature and seed,
than to tread in those paths.
And therefore all mind that, in which ye may honour God, and his holy name,
into which ye are called;
that ye may answer the Lord God for all his tender mercies and great riches,
that he hath plentifully manifested and enriched you withal.
That the love of God may fill your hearts, which hath abundantly been shed in you;
that so it may abound one towards another, and to all the creatures of God,
for their good; that they may come to the way of life and peace,
and that they seeing your good works, may "`glorify your Father, which is in heaven.`"
And so, let truth, righteousness, holiness, pureness, and justness be your jewels,
and in your eyes esteemed above all; for unrighteousness, unholiness,
and ungodliness is but dross, and is not of God nor Christ.
And therefore live in the truth, which the devil is out of, and in the life, which was,
before death and the devil, the power of it was; and in the light, which was,
before darkness was, and the devil, the prince of it;
and in this ye will have fellowship with God, with Christ, and one with another.
And so no more, but my love.
Things here are well, and meetings are quiet and large in this nation,
and this part of the world.
Farewell.

Ye may write unto us, and let us know how things are with you.

G+++.+++ F.

[.centered]
=== Letter 197.

Dear friends,

In the power of the Lord dwell, which will keep you all in unity, dwelling in it;
and all be bold in that, threshing down all deceit,
and wait to have all your minds guided with that which is eternal, up to God,
who is eternal.
And walk wisely in the wisdom of God,
(I charge you in the presence of the living God,)
and take heed of acting in your own wills,
contrary to that which is pure of God in you.
And know the power and life of God in one another, which gave forth the scriptures,
which was, before the scripture was; which life the saints had unity in,
one with another.
So, in the life God Almighty preserve you!
And meet together everywhere,
(I charge you in the presence of the Lord,) and wait together upon God,
to have your minds guided by that which is of God, up to him, with that which is pure,
which will judge all unrighteousness,
(which must never enter into the kingdom of God,) and with the eternal spirit of God,
and in his power ye may be kept from all fancies in your own wills.
So God Almighty be among you, to do his will in his love.

G+++.+++ F.

[.centered]
=== Letter 198.

Dear friends,

Keep over all that, which tends to strife, in the seed Christ,
in which is peace and life; for that which tends to strife,
and yet is in a feigned flattery, will corrupt you.
And, therefore, live in that which is pure and steadfast, and is not changeable;
and in that know one another.
And lay hands on no man suddenly; for that which is fickle and changeable,
will bring people into an unsettled state, and bring them out of their own conditions,
and bring into a questioning state.
And therefore keep in the seed, and light, and power of Christ,
in which ye may walk safely, and not give away your power; but dwell in it, in love,
unity, and peace one with another.
And in it keep your meetings, and be quiet; and live,
and dwell in the power of truth over all the unruly spirits.

And be faithful, that the seed, Christ Jesus may reign in you, and among you.
For the truth is over all, and reigns.
And so, be valiant for it upon the earth.

G+++.+++ F.

Lancaster prison, the 2d of the 5th month, 1660.

[.centered]
=== Letter 199.

Friends,

The matter concerning not putting off the hat in prayer,
and when they give thanks to God,
which hath been said by some to be heathenish and Romish,
and set up in the time of darkness and ignorance, and in the curse, and in the fall,
and cursed.
Then they, and ye, who have put off your hats, when ye have prayed,
and given thanks to God, must be wrong, according to their judgment,
(which is false.) For who have known the power of God, and the motions of it,
which power was before hats and coverings were, are out of this judgment.
For there was a sect of people amongst the Corinthians, that were jangling about meats,
drinks, days, marriages; and whether they should pray covered,
and whether the woman should pray and prophesy uncovered?
There was such a strife, before the Papists got up.
And therefore the apostle set up a comeliness amongst the churches, and says,
it was a dishonour for a woman to pray or prophesy with her head uncovered.
And also, a dishonour for a man to pray or prophesy with his head covered.

Now say they, who keep the hat on when they pray,
this covering of the woman is the spirit and power, (which is her covering,
and not the hat,) then the spirit and power must be covered,
when she prays and prophesies.
And how can she pray and prophesy, when the spirit and power is covered?
For that is her covering, and her head,
(say they.) And this must be uncovered in the man, when he prays and prophesies.
So, showing hereby a contradiction in the male and female; which shows forth,
that the spirit and power must be covered in the one, and uncovered in the other.

They say, Christ is the head of the woman,
(spoken of in the Corinthians,) and her head must be covered when she prays and prophesies;
and is it not meant of an outward hat.
Then Christ, which is the head,
must be covered in the woman when she prays and prophesies;
and when a man prays and prophesies his head must be uncovered.
This also shows a contradiction.
For prophecy is in the spirit, and praying is in the spirit,
and by prophecy they see Christ.
And if Christ be covered, then they must consider it by what the woman covers him,
and whether or nay she can prophesy when he is covered?
And so it is that mind which runs into outward things that stumbles;
and ever was and ever will be so.

And this mind and spirit which hath given this judgment
so upon Friends and amongst Friends,
not only in a paper to be spread up and down,
but also in disputes and janglings about it;
in which is such a judgment contrary to truth and the apostles`'
comely order and practice which was set up amongst them.
This judgment hath not only judged us but also the apostle.
They may as well say, he set up a form in the curse, ignorance, heathenish, and Romish;
who calls it a comely thing for a man to pray uncovered, if not he dishonours his head;
and a comely thing for a woman to pray or prophesy with her head covered.
So there was a comeliness and an honour in it.
We never use to preach up such things, who are come to the power of God,
before coverings or hats were.
And many would not have believed that ever such things would have come forth amongst us;
but now they see our comely order and practice is
likened to a heathenish and Romish order,
and curst.
Some such the apostle had to do withal,
when he set up his comely order before the Romish way was.

Therefore are we necessitated to speak a little to such things,
that Friends may keep in the power of God which was before hats and coverings were.
For when we see people run into such things, and make a sect of it, and cry,
they have attained to a greater glory than before;
they run into such outward things as the hat is;
and if they have attained to that they have but attained
to that which is since Adam fell.
For they that have attained to that state which Adam was in before the fall,
it is without hats or coverings.
And they that are come to Christ (and Aide in him)
are in a state beyond Adam before he fell,
far before outward coverings were; for Christ was with the Father before the world began,
before Adam was made.
And when the apostle spake to the Corinthians how that he
would have them to know that God was the head of Christ,
and Christ was the head of the man, and the man was the head of the woman;
and the woman was made for the man and not the man for the woman;
and he is the image and glory of God, and she is the glory of the man:
this the apostle spake to the Corinthians,
who were not come to the state of Adam and Eve before they fell;
amongst whom there was a sect about the man being covered, and the woman uncovered.
Amongst whom he sets up a comely order and practice,
and lets them see how they should pray, prophesy, and practice.
So he meant there of outward things, when he speaks of a man uncovered,
and a woman covered; or else he should be shaven and shorn.
Now these (as I said before) were not come to the state of Adam and Eve before the fall;
for who are come there are come to that which was before coverings were.
This was a comely and decent thing, and of good report amongst the primitive christians.

Therefore, all Friends, live in the power of God which ye first received,
the power which was before the fall was, in that is the fellowship and leads to order,
comeliness, and decency.
For all the sects about meats, drinks, and days,
are gotten up among the sons and daughters of Adam that are gone from the power of God,
and his image, righteousness, and true holiness, which were before coverings were.
And others who are fallen from that into such outward things,
there they are jangling about them.
And therefore keep over all such things is the power of God,
which was before outward things were; in that have ye perfect fellowship and unity,
for there is your profit.
For they that have a fellowship in keeping on their hats, and observing of meats,
those outward things lead them from the power, and so to no profit, but into strife,
and jangling, and vain disputes.
Therefore, the power of God all keep in.
The power of God was before strife was;
and in that is the perfect and standing fellowship
when all other fellowships shall have an end,
which were set up since Adam`'s fall.
And so farewell.
My love is to you all in the everlasting seed of God.

The church of the Romans fell away by running into
outward things from the power and life;
also the Corinthians, Galatians, and others of them; and also the Seven Churches of Asia,
by running into outward things;
and what the outward things were they ran into ye may read.
And how the apostle reproved them,
and what all are gone into since they lost the power of God, and the unity in the spirit.
And therefore, all dear friends, keep in the power of God over all outward things,
which was before they were; and in that power is the standing unity.

G+++.+++ F.

[.centered]
=== Letter 200.

[.blurb]
==== The line of righteousness and justice stretched forth over all merchants, etc.

And an exhortation unto all Friends and people whatsoever, who are merchants, tradesmen,
husbandmen, or seamen, who deal in merchandise,
trade in buying and selling by sea or land, or deal in husbandry,
that ye all do that which is just, equal, and righteous in the sight of God and man,
one to another, and to all men.
Find that ye use just weights and just measures, and speak and do that which is true,
just, and right in all things.
That so your conversations, lives, practices, and tongues may preach to all people,
and answer the good, just, and righteous principle of God in them all.
In which ye may be serviceable unto God, and to the creation in your generation,
and a blessing both to God and man.

All Friends, everywhere, live in the seed of God, which is the righteousness itself,
and inherits the wisdom and is the wisdom itself; with which wisdom ye may may order,
rule,
and govern all things which are under your hands (which God hath given you) to his glory.
Govern and order with his wisdom all the creatures that ye have under you,
and all exchangings, merchandising, husbandry.
Do what ye do in the wisdom of God, and with it, which is pure from above, and gentle,
and easy to be entreated.
With this wisdom (which is not earthly, sensual,
nor devilish) you do good unto all and hurt no one, nor yourselves;
for it is pure and preserves pure.

So this is the word of the Lord God to you all:
keep all in the power of God over all the unrighteous world;
which power of God was before it was.
In which power of God ye will be preserved in justice, in truth, in equal balance,
and weights and measures, in the truth, uprightness, and honesty to all people.
So all here in this are serviceable to God in their generation, and to the creation,
and are a blessing.
Do rightly; that is the word of the Lord God to you all, whether ye be tradesmen,
of what calling or profession, or sort soever, or husbandmen.
Do rightly, justly, truly, holy, equally to all people in all things;
and that is according to that of God in every man, and the witness of God,
and the wisdom of God, and the life of God in yourselves;
and there ye are serviceable in your generation, labouring in the thing that is good,
which doth not spoil, nor destroy, nor waste the creation upon the lusts.

And all merchants whatsoever, seamen, and traffickers by sea or land;
this is the word of the Lord God to you all: "`Do justly, speak truly,
to all people whatsoever.`"
Then are ye a dread and a terror to the unjust.
"`Wrong no man,
overreach no man,`" (if it may be never so much to your advantage,) but be plain,
righteous, and holy: in this are ye serviceable to your own nation and others,
by your change and exchanging of things and merchandise,
and to the Lord God ye come to be a blessing in the creation and generation.
"`Live in the life of truth, and let the truth speak in all things, and righteousness;
and let justice be acted and holiness in all things, without any guile, fraud, or deceit;
so that is well pleasing to God and men, and according to that of God in every one.`"
And this showeth forth the fruits of believers, that are passed from death to life;
from death, which came by sin, the original of which is the devil.
So being come from death to life, which goes over him; over him, I say,
who is the author of all unrighteousness.
Now, in the truth and righteousness ye will all have peace, favour,
and the blessing of the Lord in all things.
And that keepeth out the covetous mind, and covetous desires; the power and life of God,
that goes over the power of death, which brought the sin.
That which keepeth over this, hath the blessing and increase of the heavenly riches;
and that shall not want the creatures,
nor any good thing from them the Lord will not withhold.
So be careful to do good in all things to all people whatsoever.
In the fear of God serve him, and be diligent, and not stubborn in any thing,
but pliable in the power of God, that keeps you over all the powers of unrighteousness;
acting so in that, that ye may be a good savour in all nations, islands,
and places where ye come, in the hearts of all people, doing truly, and plainly,
uprightly, faithfully, justly, and honestly,
according to the light of Christ Jesus in every man; that ye may witness to all.
Then will your words, lives, and conversations preach and manifest,
that ye serve God in the new life; and that ye have put off the old man and his deeds,
which are unrighteous; and that ye have put on the new man,
which is renewed after God in righteousness and holiness, according to his image.

Loathe deceit and all unrighteousness, hard-heartedness, wronging, cozening, cheating,
or unjust dealing; but live and reign in the righteous life and power of God, and wisdom,
(that presseth all the other down,) and to answer
the good and just principle in all people;
and that will win people to deal with you, doing truth to all,
without respect to persons; to high or low whatsoever, young or old, rich or poor.
And so here your lives and words will preach wherever ye come.

All husbandmen, and dealers about husbandry whatsoever, cattle, or ground,
to you all this is the word of the Lord God: do rightly, holily, justly, honestly,
plainly, and truly to all men and people, whomsoever ye have to deal withal;
wrong not any in any case, though it be never so much to your advantage.
Deny yourselves, and live in the cross of Christ, the power of God,
for that destroys injustice; and "`without holiness none can ever see the Lord;
and out of righteousness there is no true peace.`"
Therefore all, of what sort soever, or what calling soever, do justly,
(whether ye be masters or servants, fathers or mothers,
sons or daughters,) to one another, and to all, do that which is just and righteous,
uprightly and holily; in that you will have peace, and see God.

So in all husbandry speak truth, act truth,
doing justly and uprightly in all your actions, in all your practices, in all your words,
in all your dealings, buyings, sellings, changings, and commerce with people,
let truth be the head, and practise it.
And in all your words let truth be spoken.
This brings righteousness forth, and deceit to the judgment bar.
Wrong no man, nor covet, nor cheat, nor oppress, nor defraud any man in any case;
but keep your dominion in the truth, in righteousness, holiness, and equity,
in the power, and light, and wisdom of Christ.
In this ye answer the light of Christ in every one, and are a blessing to the Lord God,
and to your generation ye are serviceable; and come to walk in the new life,
in which the righteous, holy God is served.
In which righteousness ye have peace; and in which holiness ye see God.
For the kingdom of God stands in righteousness, peace, and joy in the holy ghost.

So speak the truth, whether merchants or tradesmen, and all sorts of people whatsoever,
in all your occasions, and in all your tradings, dealings, and doings, speak the truth,
act in the truth, and walk in the truth; and this brings righteousness forth.
For it answereth the witness of God in every one;
which lets every one see all the deeds and actions they have done amiss,
and words which they have spoken amiss.
So the witness of God within them ariseth a swift witness against them,
for their words which they have spoken amiss,
and for their actions which they have done amiss, and brings them to the judgment bar,
and to condemnation.
Here righteousness goes forth,
and here the sweet savour to the Lord God begins to ascend;
and truth and equity arise both to be acted and spoken.

So all Friends, of what calling soever, that dwell in the power of God,
and feel the power of God, and the light of Christ Jesus: dwell in that, act in that;
that ye may answer that of God in every one upon the earth with your actions,
and by your conversations, and by your words, being right, just, and true.
This goes over the unjust, untrue, unholy, and unrighteous in the whole world;
and reacheth to the good and true principle of God in all people,
which tells them when they do not do equally, justly, righteously, and holily.
So that is the word of God to you all friends, of what calling soever ye be.
"`Live in the power of truth,
and wisdom of God,`" to answer that just principle of God in all people upon the earth;
and so ye answering of it, thereby ye come to be as a city set upon a hill,
which is above that mountain, that is in the whole world,
that lies above the just principle of God in every one there,
which the power of God goes over.
So let your lives preach, let your light shine, that your works may be seen,
that your Father may be glorified; that your fruits may be unto holiness,
and that your end may be everlasting life.
Dwell in the power of the Lord God, and light and life, with which ye may feel and see,
before the unrighteousness was;
in this ye will know the everlasting righteousness brought forth,
which answereth the righteous principle of God in every one,
to which they must come down, to lead them and guide them,
to teach them to speak and act truth justly, righteously, and holily.
And that hath the dominion which doth justly, holily, and righteously speak, act,
and think; and this hath the praise of God;
and they who do so come to answer that which God requires, "`to love mercy, do justly,
and to walk humbly with God.`"
And this is more than all the talkers of justice, righteousness, and holiness,
whose life denies what their tongues profess and talk of.
By that God and Christ is dishonoured.
So these are no good examples, neither serviceable in their generation nor creation,
nor any but they who live in the power of God, and in his wisdom;
in which they have the righteousness, peace, truth, holiness, justice, and equity.
These are comely and savoury both to God and man.

And all, of what trade or calling soever, keep out of debts;
owe to no man any thing but love.
Go not beyond your estates, lest ye bring yourselves to trouble, and cumber, and a snare;
keep low and down in all things ye act.
For a man that would be great, and goes beyond his estate, lifts himself up,
runs into debt, and lives highly of other men`'s means; he is a waster of other men`'s,
and a destroyer.
He is not serviceable to the creation, but a destroyer of the creation and creatures,
and cumbereth himself and troubleth others, and is lifted up,
who would appear to be somebody; but being from the honest, the just, and good,
falls into the shame.
Therefore dwell every one of you under your own vine,
(that know redemption from the earth,) and seek not to be great, but in that,
and dwell in the truth, justice, righteousness, and holiness;
and there is the blessing enlarged.

And no one, (of what calling soever,) run into debt, usury, and exaction;
for many people have been wronged thereby; they that have taken of them,
who by it have appeared great, and lived above what they were, and so would seem to be.
Therefore be true and honest, holy and righteous, every one, in that which ye have.
Owe to none any thing but love; and in that ye will feel the blessing,
and come to be serviceable in the creation, serving one another in love,
and not in oppression and taxation.
And that keeps all down in the power, wisdom, and life of God;
and bends all minds to strive for one another`'s good,
and to help one another in that which is good, just, and righteous,
and serve one another in that; in that ye live in the life, and in the seed, the power,
and righteousness that is everlasting, which is of God, and his wisdom,
through which ye come to answer the good, just,
and holy principle of God in every one upon the earth.
In which power ye have dominion;
in which ye come to live the life which is well pleasing to God,
a life which shall stand when the world is ended.
And in this life, power, and wisdom of God that is endless,
ye are a terror to all that are in the wisdom below;
ye are a terror to all that are in the unrighteous actions and words.
And ye are a terror to all that are in the unjust and unequal doings,
and all the defrauders, cozeners, cheaters, overreachers, liars, and wrong dealers.
In the power of God, and his life, in which ye have justice, ye have truth,
ye have equity, ye have righteousness; and it cometh to be to you as natural; your words,
your lives, your conversations, your presence, and your practices both judge and preach;
and ye will be a terror to all of them in the just life and everlasting righteousness,
Christ Jesus; living in him and in his wisdom, and walking in him,
and speaking the truth as it is in him in all things;
your life and your words are a terror to all that speak not truth in their dealings,
and to all that act not truly and righteously in their doings, your lives do judge them,
and are a judge to them; and through your constancy, faithfulness, and life,
which is everlasting, ye bring many to amendment.
For both life, actions; words, and conversation preach,
(all these preach to the unrighteous world,) being in the everlasting righteousness,
which over the world hath dominion; through which life, power,
seed of God and wisdom ye reach,
and answer the good and just principle of God in every one;
and it will make them at last confess to you,
though they may go on in the contrary for a time.

So in that power, and wisdom, and strength, that gives you dominion over all,
and to answer that of God in all,
the love and power of the Lord Jesus Christ preserve and keep you all in his wisdom,
life, seed and dominion, that to him ye may be a blessing,
and a good savour in the hearts of all people.
And let all your actions and words be one with the witness of God in all people.
Amen.

The wicked and unrighteous owe envy and hatred, and with that they pay their debt;
but the righteous, just, and harmless, who owe nothing to any man but love,
with that they pay their debt.
But drunkards, adulterers, swearers, rioters, who eat and drink, and rise up to play,
and live in pleasures wantonly upon the earth, fighters, quarrellers, envious, malicious,
unjust, unrighteous; all such actions and practices are judged out of the power of God,
and out of his kingdom.

And all Friends everywhere, that are shopkeepers or merchants, or factors,
or any other trades, keep low in the power of God, and do not go beyond your capacity,
nor reach after things more than ye can justly perform, and answer all men;
but all in your places be just and true, that ye may answer all men within and without,
and truth and justice in your returns, that ye may keep your words, so say, and so do;
which is the royal law of liberty in all your tradings,
else ye are a dishonour to christianity.
Therefore see your business, that what ye do, and what ye say, ye may perform,
that ye may not break your words and promises; for if ye do ye go to loss.
Neither are ye masters of what ye take in hand; for a master should be atop of things,
and be in that which can command things.

And none be negligent in their business, but give an account by words or writings,
how things are with them, when others write to them;
so that none may wrong one another in these outward things, nor oppress one another,
but be serviceable one to another, keeping their words,
(their going into things beyond their ability,
makes them break their words,) keeping within their
compass with that which they may answer others,
lest any should be lifted up.
For it is a bad thing to be lifted up,
and to make a noise and a show for a time with other people`'s goods,
and cannot keep their word, their promise, their day; such may be lifted up for a time,
and break, and fall, and go out as a stink,
and bring a great dishonour to Christ and true christians.
And therefore, keeping your word, your day, and keeping your just measure,
your just weight, that keeps down the oppression.
And by keeping to that just measure and weight, and to your word and day,
by the power a God and his spirit in your own hearts, there the blessing is doubled,
there ye come to be rich, and ye are a good savour to God,
and in the hearts of all people.

So every one strive to be rich in the life,
and in the kingdom and things of the world that hath no end;
for he that covets to be rich in the things of this world, falls into many snares,
and hurtful lusts.
And therefore, let him that buys, or sells, or possesses, or uses this world,
be as if he did not.
Let them be masters over the world in the power and spirit of God, and let them know,
that they owe no man any thing but love; yet serve God in truth,
and one another in their generation.

For Friends, if ye be not faithful in the outward treasure, and outward mammon,
who will trust you with the true treasure?
Or who can believe that ye have the true treasure, but that ye speak by hearsay of it?
So, I say to your all, see that ye are faithful in this outward mammon,
this outward treasure of the things of this life, of this world, faithful to your word,
faithful to your days, faithful to your promises, in all your tradings, traffickings,
bargainings true and just, and righteous and honest in these outward treasures or mammon,
concerning the things of this world, of this life, of these outward riches;
just and faithful, true and honest men and women in these outward things.
I say, as Christ saith,
"`Who will trust you with the true and heavenly treasure,`" if not as before?
Therefore I say, to be faithful in these outwards, that shows an honest man,
and honest woman; faithful in all your dealings and practices between man and man,
and woman and woman, that showeth an honest heart,
and a faithful man and woman in outward things,
that answers the faithful principle in all people.
So all men and women to be faithful in these outward things one to another,
that shows the good heart to receive the true treasure,
that ye may be faithful in it to God,
who have been faithful in their outward treasure or mammon one to another.
So let every one`'s conversation be without covetousness;
let not that be once named among saints.
And do to all men as ye would have them do to you, that is the law and the prophets;
if not, ye are judged by them both.
For the kingdom stands in righteousness, (mark,
stands in it,) and in peace and joy in the holy ghost, (mark, in it.)

For holiness becomes the house of God.
Whosoever acts unholily, it is that doth dishonour his house, and doth not become it.
Whosoever acts unfaithfully in this outward treasure or mammon,
or in the true treasure to God, is not justified in the sight of God nor man;
for they are justified by faith, through faithfulness both to God and man.
For whosoever doth righteousness, is of God; and he that doth not righteousness,
is not of God.
For God loveth the righteous, and delighteth in them;
but not in them that do unrighteousness.
For in the righteousness they have peace; but out of righteousness people have trouble.
So all God`'s people, his children, his saints must be holy, as he is holy;
and therefore do that which is holy and just in all your lives and conversations.
And whatsoever ye do, let it be done to the praise and glory of God,
(mark that,) have God`'s praise and glory in your eye in all your speakings and doings,
then ye will be preserved to his glory, and then ye will honour him;
and them that honour him, he will honour and beautify, and clothe with the fine linen,
the righteousness of Christ, that men may not see your nakedness.
For God will have a holy people, to serve him in holiness; a true people,
to serve him in truth, and in his spirit, and in his new and living way,
above all the dead ways that are come by sin and unrighteousness,
and transgression of his spirit, and power, and command.
So all ye that know his power and spirit, live in it,
that ye may glorify God in all your lives, and conversations and words,
that ye may answer that of God in all; that ye may glorify God in your bodies, souls,
and spirits, which are his, who hath made them, and gives them to you for that end.
To whom be glory and honour forever, who created all for his glory and for his honour.
So the Lord God Almighty keep and preserve you faithful
in all things to his glory and honour forever!

"`He that walketh in his integrity, is just;
and blessed shall be his children after him.`"
Prov. 20:7

"`Unjust weights, and unjust measures, both these are an abomination to the Lord.`"
Verse 10. G. F.

[.centered]
=== Letter 201.

Dear Friends,

In the stillness and silence of the power of the Almighty dwell, which never varies,
alters, nor changes, but preserveth over and out of,
and above all the changeable worships, religions, ministers, churches, teachings,
principalities, and powers, with the power of God, which keepeth over all this,
to the kingdom of Christ, that is everlasting, in which there is no changing,
who is King of kings, and Lord of lords.
All power in heaven and earth is given unto him, of whose light, life, power, and wisdom,
grace, and riches have ye received which comes from him, that doth not change.
So in that live, that doth not change, the unchangeable life, the unchangeable mind,
the unchangeable spirit and wisdom, and the unchangeable worship and church,
of which Christ is the unchangeable head, who remains the same yesterday, today,
and forever;
in that ye will feel the blessing and presence of the Lord God of life amongst you,
as ye all abide in the unchangeable kingdom, dominion, power, and life,
who are heirs of it according to your measures, who have received the light,
and received the life and grace, and the power of a kingdom and a world that hath no end.
So wait all in it, that ye may be possessors and inheritors of the kingdom,
and of the life and power which hath no end, and of the promises, that are yea and amen;
and let nothing, that is of the world, alter you,
but keep ye in that which keepeth you in the everlasting kingdom of God.

G+++.+++ F.

The 3d of the 3d month, 1661.
