== Letters 202 &#8212; 220

[.centered]
=== Letter 202.

[.blurb]
==== An answer to a letter sent to G. F. concerning the voluntary contribution to the king.

Friend,

To the thing thou queriest of me, concerning this matter, my answer is:
Seeing that the king and his friends desire it not as a tax or an assessment,
but a free gift of the people, which cannot be said is an oppression;
therefore it is left to all Friends to do as they are free.
And what the world doth, Friends are not to look at, who will set up a thing,
and dislike it; but Friends are to mind the universal power of the Lord God,
that they may do that freely in their own power which they do, better than by compulsion,
tax, or assess; for if all things were done so, it were the best, in the free state,
bounty, and love, which would more break the hearts of people,
than by force of assessment and tax.
So things are left to the wisdom and universal spirit of the Lord God,
which goes over the heads of all in the fall;
that with the living power and wisdom of God ye may overcome them,
and so do as ye are free.

G+++.+++ F.

[.centered]
=== Letter 203.

What, Friends!
Do ye reign as kings?
Can they pluck never a one (of you) out of the Father`'s hand?
Are ye put forth?
Do ye witness that scripture fulfilled; put forth to follow the King of kings,
(the shepherd,) who gives life abundantly?
In that let your joy be still, and your comfort remain;
in which ye will feel the endless kingdom and dominion.
In that the Lord be with you, who is your strength, comfort, and fulness forevermore,
world without end!
And, friends, mind the light, and dwell in it,
and it will keep you atop of all the world; and mind the seed of God, and know it,
and in it be content.

Dwell in the power of truth, and be not negligent in that, but diligent,
serving the Lord, every one in your measures;
that to the Lord God every one of you may be a blessing,
and a sweet savour unto him in your creation and generation,
feeling and knowing the Lord`'s power every one in yourselves, yea,
the power of an endless life, and of a kingdom that hath no end,
and of a dominion that is over all dominions.

And in the power of the Lord God everlasting,
ye may feel the seed of God in every particular of you raised up,
which doth inherit the same;
that ye may sit down in your own possession of everlasting life.
And in that meet together, waiting upon the Lord, and in it keep your meetings,
where ye may feel the chief shepherd leading you into pastures of life.
And so the blessing of the Lord be with you!

G+++.+++ F.

[.centered]
=== Letter 204.

[.blurb]
==== To all Friends, prisoners.

Dear friends and brethren,

The seed of God feel all in yourselves, which is the heir of the power of God,
that ye may sit down in the possession of the same; inheriting the power,
and the promise, and the gospel.
In which power of God is the fellowship, being heirs of the same,
and members of that fellowship which never hath an end,
which brings life and immortality to light;
which power of God was before that was which darkeneth life and immortality from people.
So walk in the truth, then ye walk with the God of all truth;
and walk in the righteousness, and then ye walk with the righteous God in all peace.
Walk in holiness, and then ye walk in that in which ye see God; which they that do not,
see him not.
Therefore walk in the power of God, which goes over the power of darkness,
which was before it was; which power of God is the gospel,
in which is the mystery of the fellowship,
a mystery (I say) to all the fellowships that are out of the power of God.
Therefore the seed of God know, which is the top-stone,
that it may be over all laid in you, which bruiseth the serpent`'s head,
which is the fulfilling of the prophets and prophecies;
which seed brings to the beginning, where are the pastures of life.
So in that meet, in the seed, in that wait, in the power of God, in which ye have life,
in that keep your meetings; which brings to feel that,
which was before the power of darkness was.
And wait to inherit the wisdom of God,
that with that ye may all be ordered to God`'s glory in his life,
in which ye may feel unity with himself, and one with another,
and his presence and blessings among you, in the power and seed of God,
which was before enmity was; in which is the unity, and the holy will and dominion.
Which power of God brings from all the barren mountains, where is death,
to the beginning, where is life.
My love is to all Friends in the everlasting seed of God, that hath the promise of life,
and doth inherit the same in which is the fellowship with God, and one with another.

G+++.+++ F.

London, the 22nd of the 3d month, 1661.

[.centered]
=== Letter 205.

All Friends, live in God`'s dominion, and power, and life,
which was before storms and tempests were, in which ye may feel life and dominion, power,
and victory, the Lord`'s power being lived in, which was before tempests were,
in which ye will have the victory.
There is a summer religion, which appears when the sun shineth upon them;
and in the summer time all the venomous creatures creep out of their holes, corners,
and dens, and the flies, wasps, and snakes; but when the winter is come,
and the storms and tempests come, then the summer religion is gone, then the venomous,
viperous creatures`' religion and works are gone.
But the religion, that is in the power of God standeth, which was before the devil was,
and all his works and children.
And so that is the standing religion, that is in the power of God,
which was before the power of darkness was.
And, friends, ye that know the light of Jesus Christ, and have tasted of his power,
by which ye come to be gathered into the name of Jesus,
do not forsake the assembling of yourselves together; but provoke one another,
and exhort one another to love, and, to good works, and let not powers,
nor principalities, nor prisons, thrones, nor dominions, spoiling your goods, mockings,
scoffings, nor reproachings, and pluckers off your hair, and smiters,
separate you from the love of God, that ye have in Christ Jesus,
who conquered death and the devil, the power of it, the adversary, the wicked one,
the enmity.
Christ is the life, the light, the love of God to mankind;
now ye coming to be gathered into him, who destroys the devil and his works,
the life that destroys death, and the light which destroys darkness,
and the truth that destroys error and all falsehood,
and the power of God that destroys the power of the devil,
and being gathered into Christ and into his name,
keep your meetings in the power of God and in his light and life,
whose gathering is above all other gatherings in the earth;
and Christ`'s name is above all other names on the earth.
And feel the seed of God set over all that which makes to suffer;
which was before it was, and will remain when it is gone.

G+++.+++ F.

From a lover of your souls, and your everlasting good.

[.centered]
=== Letter 206.

In the power of God that is everlasting, and doth remain in this your day of trial,
in it stand, Of which ye are partakers, and are come to be heirs of the same;
and in it is your peace and kingdom.
And though ye have not a foot of ground to stand upon,
yet ye have the power of God to skip and to leap in; standing in that,
which is your life, that is everlasting.
Who by the power of God are gathered up to the beginning, to the endless life,
who have your meetings in it,
that neither death nor the power of it can separate you from,
nor out of the power of God, for it was before death or the power of it was;
in that are your living meetings, and joinings,
and building up the spiritual household of living stones,
gathered by and through the power of God.
In which power of God is the household of faith, which faith gives them the victory;
in which power of God ye being, are gathered over Jews, Gentiles,
and the apostate christians`' meetings and gatherings, who are in enmity and confusion,
and out of the power of God; that put the wheat for the tares,
and so persecute the elect; which election was before the world began,
of which ye are made partakers.
Stand fast therefore in your confidence, in that which is without end,
in that in which the endless life is seen, in the power of God, and light;
which rules over powers, thrones, principalities, and dominions.
The power of God goes over them, and ye living in it,
nothing can separate you from the love of God, which ye have in Christ the seed,
which was before the world began, glorified with the Father,
who hath all kings and kingdoms in his hand, which is his power;
in that let your faith stand.
With which immortal power ye may all be clothed,
which covers you and preserves you over the mortal.
And prisons, fetters, dungeons, and sufferings, the royal seed, and heirs of the promise,
what are they to you,
who are married to the Lamb who was slain from the foundation of the world;
against whom they warred and banded themselves,
and took counsel together against the Lord, and his anointed,
who breaks their bonds asunder; whom neither death, grave,
nor all the powers of the world were able to hold nor contain, but over all he rose,
(the seed,) and reigns, till he hath made all his enemies his footstool.
Honour and praise be to the Lord, the living God, that lives forever!
So all ye who are gathered in the name of our Lord Jesus Christ, whose name is called,
the power of God, the word, which was in the beginning, over the powers of darkness,
before it was, and compelling worships, ministry, maintenance, and churches were;
this gathering, this meeting in the name, the power,
the unrighteous world cannot separate you from; for it is over it, and was before it was.
In that power have ye the kingdom and dominion, in the power,
reigning over all that which hath been out of the power.
And ye that partake of the power, have power with God,
in that we need not bid you keep your meetings;
for ye art met and gathered into the fold of Christ Jesus, and are put forth by him,
and are brought from under that, that leads from God, by the power of God.
In this gathering by the power into the name of Christ,
(which is the power,) with the power he is felt in the midst, who is King of kings,
and Lord of lords, and prince of life and peace,
and prophet to open by his power and light in you all, and a priest forever,
that lives to offer up the spiritual sacrifice and praise to God;
and he being felt among you, and in you all, ye will have every one of you,
in your own particular, joy, peace, comfort, consolation, assurance, confidence,
and satisfaction, when all gatherings, meetings, heaven, and earth, types, and figures,
and shadows, and prophets, and the prophecies are ended.
And swearing before the law and in the law, and all invented oaths since the law,
and amongst the heathen, when these are gone, past away and fulfilled, the election,
and the seed, and the gathering in the name of Jesus Christ,
the Lord of life remain and stand, and his throne and dominion;
in which there is no curse, but a blessing.
So, happy are ye who are partakers of this, heirs of this blessing,
and heirs of the promise, and of the life, and of the world that hath no end;
who have your confidence and assurance in him!
So all ye that have felt the light, and have been turned to it,
in that light ye feel the covenant with God, who is light;
which brings to be acquainted with the life of God,
and gives the knowledge of Christ your saviour and redeemer,
which is the salvation to the ends of the earth.
By which light and covenant ye are turned from darkness, and the power of Satan,
that separated you from God, who was the enemy, through whom ye had not peace with God.
But now being turned from him, into the light and power,
in this covenant of light and power ye have peace with God,
(that destroys the enmity,) and are come to receive it; and so heirs of the kingdom,
that is everlasting.
Be at peace one with another, and in love and tenderness,
and in the wisdom of God order and preserve,
and nourish and cherish all things to his glory; in which ye will feel his blessing,
and treasure, and riches, and fulness in you, with you, and amongst you.
So, put on the armour of light, that with it ye may be able to defend, and see, and walk,
and stand against all the arrows and darts that are in the unrighteous world,
and before they were, as children of the light, and children of the day,
where the darkness is past.
Put on your breastplate of righteousness, to save and preserve your hearts and minds,
and to keep you from all that which would defile and surfeit it,
or cause you to be weary, or think the war or time long.
For the power is everlasting, and the righteousness is everlasting,
that destroys the works of the devil, and him both,
whereby the seed of God comes to be set on the head of it all;
glory and praise be to him forever!
Put on therefore the shield of faith, by which faith (your shield) ye have the victory.
For faith is a mystery held in a pure conscience, by which ye have access to God;
in which faith ye please God, in which faith ye have unity,
which gives you the victory over that which separates from God--the enmity.
In that faith be joyful, which is the faith of God`'s elect,
that brings them over the world, and to that which was before the foundation of it.
And this is the faith the just lives by, by which he is saved and justified,
by which he lives and conquers, and hath the victory over the unjust;
glory to the Highest!

Put on the helmet of salvation, and take the sword of the spirit,
(the word of God,) your helmet being on, nothing can destroy nor hurt your salvation,
Christ Jesus being your helmet and your head, who destroys the devil and his works,
the sword of the spirit that mortifies, that crucifies, baptizes, cuts off,
plunges under all corruptions that have gotten up since the transgression;
then in the spirit ye will worship God, and have fellowship and spiritual weapons,
and come to be spiritual men,
and not as the carnal world that rule and wrestle with carnal weapons,
and with flesh and blood.
The stone cut out of the mountain without hands,
will dash and break into pieces all the cutters with hands,
and carnal-weaponed men about religion, church, and worship;
and his kingdom is an everlasting kingdom, and his dominion hath no end.
This stone is that which laid Nebuchadnezzar`'s head low,
and brought him to eat grass like a beast;
who knew not the kingdom of the Most High ruling in men.
So ye that know this stone cut out of the mountain without hands,
ye all know the kingdom of the most high God ruling in you,
and his dominion which is everlasting, and come to be his temple.
For there was but one temple in the whole world commanded of God, as a figure of Christ,
who would dwell in man, in male and female, who should be the temples of God,
in whom should be his name and power.
Blessings, honour, and glory, and praises be given to the Lord God forevermore,
by all them who witness this.

So all dear lambs, and babes, and brethren, happy and blessed are ye who know the seed,
which is heir of the blessings, and the power, and life, and the kingdom,
and the world that is everlasting and without end.
Be shod all with the gospel, which is the power of God,
which hath brought life and immortality to light, and hath and doth abolish death; I say,
be shod in the power, and then your feet will not slip nor slide, and ye will not fall,
and ye will stand steadfast, being shod with the everlasting gospel,
in the preparation of it.
And standing in the power ye stand over the workers of iniquity, and,
all unrighteousness in the world, and slippery ways,
standing in the power which was before death, darkness,
and the power of darkness and death was,
which hath darkened life and immortality from people,
so that they could not walk and get forward on their way to the Lord.
But in the power of God, (the gospel,) being in it, and with it shod,
your feet standing in the power, ye over death, darkness, and the power of it may stand,
walk, go, and leap, (which was before it was,) there is faithfulness and steadfastness,
and there ye may walk without doubt.
And keep the word of patience, and take unto you the word of God; and who are born of it,
(of the immortal seed,) nourished by the milk of the same up to eternal life,
know things as they were in the beginning, they feed upon that which lives,
and not upon that which is in the world and in the fall, which is below the word,
and below the power, and below the truth, and out of it;
who know the shepherd and his crook which plucks you out,
he shows you the pastures of life, in which ye must feed.
Every one that knows the power and light, and by it is guided and turned to him,
feels and knows this.
And so, ye that have the word of patience, ye have the hammer,
ye have that which was in the beginning; ye have that which lives, and abides,
and endures forever.
Ye know what the hammer is to; and ye know the word is a fire, and what the fire is to.
So ye that have the word, have the fire, which burns up all that which doth not abide,
and doth not endure, and doth not live forever, as the word doth;
which is the word of wisdom.
So ye that have the word have the wisdom, which was in the beginning,
before that which is below was.
So ye that have the word have the sword, yea, sharper than a sword with two edges;
which will cut down all that which hath gotten up since the beginning,
which hath transgressed the just spirit,
and burn up that which hath gotten up since the beginning, in the transgression.
And this is the word that makes clean, and reconciles to God;
and is the word of reconciliation.
And this is the word of patience to keep you;
and ye will be kept in the hour of temptation,
that comes upon them that dwell upon the earth.
For the word of God was before the tempter was, and goes over him and destroys him;
in that live, in his life that is eternal, which doth abide.
So in that the Lord Jesus Christ preserve you!
For in that patience is exercised, in that word,
which comprehends all that which hath gotten up since the beginning;
for with that ye may be tried.
But the word is over all, in that live, which hammers, burns, cuts down, and reconciles,
against whom the, tempter and temptation cannot come nigh to prevail; it breaks his head.
Neither meddle nor mix yourselves with the powers of the world, nor things below;
but live in the power of God, which is peaceable.

And forasmuch as we are scandalized as plotters,
we in the power of God do comprehend the power of darkness;
which power was before the powers of darkness were,
which destroys darkness and the power of it.
And we cannot plot; it is impossible we should, standing in that which destroys darkness,
and the devil, the power of it, who is the author of plots,
and the enmity in people`'s minds, bondaging and bringing the creature into thraldom;
which we in the power of God would have all persons from under,
and would have no man`'s person in the whole world hurt;
but in the power of God would have all men saved, and seek all men`'s peace.
And so that which manifests all plots, and the author of them, the devil,
and that which judges him, and destroys him and them, are we in,
and are made partakers of him who redeems and saves, and heals, and sets free,
who is the power of God.
So all you who are partakers of the power of God, that have been turned to the light,
and received the power of God, Christ Jesus,
that hath given you power to become the sons of God; in which light and power of God,
by which ye were turned to him, ye come up into the liberty, the liberty of the sonship,
into the power of God, that doth redeem and save, and destroy that which leads from God,
which doth defile, and destroys it, and gives dominion.
That is the power of God in which the saints have liberty,
where the sons of God sing together, and praise, glorify, and honour their Father;
to whom be glory, praise, and honour forevermore!
Who in him triumpheth in glory, and can say, Emmanuel is born, and a son is given.
So all in the life and power of God`'s seed and wisdom, which is everlasting, dwell,
and know the seed of God in every one of you, in your own particulars, male and female,
which seed is the heir of the promise, the heir of the wisdom,
and heir of the world that hath no end, of an endless life,
and the heir of the kingdom that is everlasting, and the heir of the blessing,
where there is no curse.
And every one an heir of the power, of the blessings of the kingdom, come to inherit,
come to possess your own inheritance, and then sit down in your own possession;
in which ye may know every one your election,
(in the seed,) which was before the world began,
and so be possessors and inheritors of life and substance.
The substance is the seed, the top-stone, on top of the law, on top of the prophets,
on top of the types, figures, shadows, parables, and end: them all,
and on top of all heathens`' inventions, though it hath been a mystery hid from ages.
See now, the seed, the seed of the Lamb and his marriage is known, and the Lamb reigns,
where there is no curse, but the blessing.
The curse is out of his dominion, who destroys the author of the curse, wrath, plagues,
and woe, that hath the blessing, the seed, Christ Jesus.

And all Friends, improve your talents, that to you all it may be said, "`Well done,
good and faithful servants;`" for they who do not,
their talents are taken away from them, who have been slothful, complainers, and idle.
Let your lamps be burning, have oil in your own lamps, and salt in yourselves;
then ye are the wise virgins that enter in with the bridegroom.
The word of God cannot be bound, which makes rich, which lives forever;
in which is the life.
So, do not quench the spirit, nor add to the prophecy, nor diminish;
that keeps you from the plagues,
and to see your names written in the Lamb`'s book of life:
there stands your joy everlasting, through which ye see the white stone,
through which light, power, and seed, ye overcome that which is gone forth from God.
So, ye dwelling in the son of God, ye shall go no more forth,
but shall inherit all things.
So, farewell!

Keep in the power of the Lord God, that goes over all the world,
that none of your flight may be in the winter.
And beware, lest any of your flight be on the sabbath day,
(the signification of which is rest,) but all in the power of the living God abide,
in which ye may feel life, peace, and rest, and an abiding place;
a secret chamber to turn into, till the indignation and wrath of the Lord be passed,
which is to come over all transgressors.
And if the judgment begin at the house of God first,
and the righteous pass the straight way to salvation,
where will the hypocrites and the sinners appear?
Over whom the overflowing scourge must come and pass.
Therefore in the life, power, and love of God, all dwell.
And the apostle saith, "`Forsake not the assembling of yourselves,
(as the manner of some is,`") but edify one another in the light and the life,
as the day doth appear: and to say, that people must not meet together to worship God,
they may as well say, ye must not be christians.
For persecutors were always blind,
and they stopped their ears to the spirit of God in themselves formerly;
so were in the blind zeal, and turned against them who were in the true zeal,
in the spirit of God.

G+++.+++ F.

Let this be carefully copied over, and sent amongst Friends.

[.centered]
=== Letter 207.

My dear friends,

Look above all sufferings that are outward, at the seed of God,
which was before that was which makes to suffer; and the seed of God, Christ Jesus,
will stand, when that which makes to suffer, is gone: and so, in the seed of God live,
and lie down in the same, which is Christ, the life, the way to God the Father of life.
The tithes of the Jews,
and the tithes of the apostate christians must all be borne testimony against,
by them that be redeemed from the earth, and reign above it, in his life, and power,
and wisdom.
And so, be of good faith, and never heed, but make war in righteousness with the beast,
dragon, whore, and her followers;
for by the Lord many walls and troops have ye gone through and leaped over,
and the Lord hath given you dominion over that which warred against you;
and by the power of the Lord ye have overcome,
and in the power of the Lord ye will overcome all, and in it will stand,
when all the contrary is gone.
And know your portion, and sit down in the possession of it: so,
every one of you to be in your possessions and inheritances,
and with the shield of faith and helmet of salvation,
and the breast-plate of righteousness, and the sword of the spirit, the word of God,
which was before deceit was, which will hammer, and break,
and cut down all that which is contrary.
And being shod with the preparation of the gospel, which is the power of God,
which was before the fall was, in that stand, in the power of God,
which was before the devil was, and will remain when he is gone.

G+++.+++ F.

[.centered]
=== Letter 208.

All ye prisoners of the Lord for his truth sake,
and for keeping the testimony of Jesus Christ, against all the inventions, traditions,
rudiments, will-worships, feigned humilities and self-righteousnesses,
that are in the fall,
(and are out of God`'s power and righteousness,) who have no weapons but carnal,
like themselves; your patience must overcome all the rough spirits in the world,
and your love must bear all things.
For patience obtains the crown which is immortal, which runs the race: so,
it is the Lamb must have the victory over all the unclean, airy spirits,
and over him that is out of the truth.
So, be meek and low, then ye follow the example of Christ,
and come to bear the image of the just, who suffered by the unjust;
and put on his righteousness, who suffered by the unrighteous, whose back was struck,
hair was plucked off, and face was spit upon, and yet cried, Father, forgive them:
here he kept his dominion, though a sufferer, who had the victory,
which the followers of the Lamb do (in measure) attain to.
So, put on courage, put on patience: let your loyalty be known for your King,
that hath conquered the devil, death, and hell; in walking in righteousness, peace,
and truth,
feeling the power of God preaching and reaching the witness of God in every one,
when words are not uttered.
And let your faith be in the power, that goes through all things, and over all things,
and every one hearken to it.
So, the power of the mighty God then ye will know, and his arm, how it works,
and the hand, how it carries you, which will bring you out of tribulation and thraldom,
and spiritual Egypt, into peace.
And this is the power of God, in which live and dwell, in which ye will feel him,
which was before enmity was.
And be at peace one with another, then ye will live in the Prince of princes`' peace,
and in his kingdom, dominion, and life, in which is unity, which was before enmity was,
and which destroys it.
And so, in the power of the Lord God ye are made strong,
which goes over the power of darkness,
and was before all that was which is out of the power of God.
And all people that are gone from the witness of God in their own particulars,
they are all weak, and feeble, and staggering:
all men`'s and women`'s strength is in the power of God,
which goes over the power of darkness.
So, feel all this in you, to carry you through all, and over all,
and in it preach and work for God, and let your ear be lent to it,
and hearken to it in one another, and by it feel the seed raised up in one another,
which is heir of the power; that ye may know each your portion.
For all people that are gone from the witness of God in their own particulars,
that are erred from it, and hate the light, they are full of darkness, sin, and iniquity,
and are far from inspiration and revelation, while their minds are,
erred from the spirit of God in themselves, that is hid from them.
So, when their minds are turned with the light and spirit of God towards God,
then with it they shall know something of revelation and inspiration;
as they are turned by that of God from the evil, and emptied of that,
then there will be some room in them for something
of God to be revealed and inspired into them.
And there in that, they will have prophecy, seeing things to come,
being turned from the evil that hath darkened them and separated them from God;
in which they will see the covenant,
through which they will come to have peace with God.

And all Friends, your sufferings ye may gently send to them who make you to suffer,
whether it be sheriffs, deputy-lieutenants, or justices, and let them see,
Christ`'s mind nor the apostles, was not to imprison any, nor did they imprison any;
whereby ye may clear your innocency to the consciences
and the witnesses of God in all men.

G+++.+++ F.

[.centered]
=== Letter 209.

[.blurb]
==== To Friends, in and about Norfolk and Lyn, etc.

My dear friends,

In the power of God and his immortal seed dwell, in which ye all will have life eternal,
and inherit the substance and dominion, and a kingdom of life, which never fadeth,
nor shall have an end.
And so dwell all in the power of the Lord God,
in which ye may all feel and know your strength renewed in that which is immortal;
and be of one mind in the power of God, and live in love and peace,
knowing the kingdom of the same, which stands in the power of God,
which was before the power of Satan.
And your fellowship being in the same power of God,
your fellowship is in that which is everlasting, and that never hath an end.
And the church-fellowship is in God, and the worship is in the spirit, and in the truth;
which truth was before the untruth was,
and stands when all the untruth in the world is gone.
In this live and dwell, in which ye will all have unity and fellowship;
in which ye will feel life eternal amongst you.
In that meet and keep your meetings, and wait together upon the Lord,
who are gathered together in the name of Jesus; whose name is above every name.
So is his gathering above all other gatherings;
which gathering stands when all other gatherings are ended.
And not in any other name under heaven is salvation brought, but in the name of Jesus;
in which name are your gatherings; in which name ye all know your salvation,
and shall all know it; as ye abide all in the power of God,
that keeps unto the day of salvation.
And so be faithful unto the Lord God, minding the seed, and feeling it,
and knowing it in yourselves; which destroys the devil, the destroyer, and the oppressor,
murderer, and liar, the father of all unrighteousness and ungodliness,
and all that is bad, which the seed destroys, which seed is Christ.
Therefore know that reign, and the top-stone over all laid;
in which ye will all feel life, and have life eternal,
coming to be heirs of the power of God, knowing every one that to be your portion,
and heirs of the gospel, and inheriting it.
Then ye possess fellowship, the gospel fellowship, which is everlasting,
which is the power of God.
And so farewell!
And the Lord God Almighty preserve you, and keep you.
So my love in the everlasting seed of God is to you all.

G+++.+++ F.

From Mendlesham, this 11th day of the 1st month.

[.centered]
=== Letter 210.

Friends,

Trust not in man, nor in the arm of flesh, neither put confidence in them,
but in the Lord.
Judge yourselves, and keep down the boaster, and that which would be high;
under judgment keep that down, by the power of God in yourselves,
lest the Lord God bring upon you something without you to bring you down,
who do not keep that down in yourselves.
And therefore keep all that down with the power of the Lord God in yourselves;
and then ye will have dominion over it all, in the power of the Lord God.
And live all in the power of God, which was before the fall,
in which ye will have fellowship over all the fellowships in the fall,
and above all outward things that have an end;
which fellowship seeth over all that which is in the strife.
For in the power of God your fellowship there hath no end,
which was before the fall and strife was, in which is peace;
which fellowship will remain when all that which is in the fall is gone,
and in which is the perfect unity,
which keeps over all such spirits which run into outward things;
from which arise quarrels, and strife, and imperfections.
And therefore keep in the power of the Lord God, that is everlasting,
in which is the fellowship that hath no end; in that live and dwell.
And feel the seed of God over all that which makes to suffer,
and it will remain when all that is gone, in that ye will feel life over death,
and light over darkness.
And so in that the Lord God Almighty preserve you, and keep you in the dominion!
This day I came into the isle of Ely, where I hear nothing, but things are peaceable,
and Friend`'s minds kept over all the bustlings in the world,
and take little notice thereof; but mind the power of God, which was before the fall was;
in which fall are bustlings.
And so to the Lord God be faithful.

G+++.+++ F.

[.centered]
=== Letter 211.

Friends,

All ye that have known the way of truth, and tasted of the power of the same,
and now turn back into the world`'s fashions and customs,
ye stop them that are coming out of the world, ye make them to stumble at the truth,
ye make them to question the way of the Lord, which is out of the way of the world,
and its ways; and ye grieve the righteous,
and sadden the hearts of the upright and simple.
Ye had better never have known the way of light, life, and power;
ye are the cause of many keeping in darkness;
you are the cause of the boasting of the wicked,
and make the wicked to take you for an example, and their object against truth,
and them that live in it, to plead against its ways.
Ye had better never have been born; your days will be sad,
trouble and vengeance will be your garment and clothing in that state;
and a hard thing it will be for any of you to repent,
for you will find a more subtle thing in you than was before you knew the way of truth;
who have neglected hearing the voice of God, through which your hearts are hardened.
Ye are the cause of many husbands and many wives to boast themselves against the truth,
and servants and children thereof; for in some families, there are servants convinced,
and children convinced, and in others there are husband convinced and not wife,
and wife and not husband, and servants and not masters, and children and not parents.
So ye that turn from truth, ye are the object for them that are not convinced,
to turn against them that are convinced.
Woe and misery is for you! ye had better never have been born, nor known the way of truth;
whose latter end is worse than the beginning,
when the way of peace is hid from your eyes, and a place of repentance ye cannot find,
though ye wash your altar with tears; being in the stained life, where all the tattlers,
tale-carriers, unclean persons, envious, murmurers and complainers are,
and are out of the life, and power, and wisdom of God, which hath the royal dominion,
and possession of the royal seed.
Therefore turn, turn all that are not hardened and past feeling, and hear the voice,
that the way of peace and repentance, and the way of life and salvation ye may know,
and live in; and upon all your disorderly carriages, walkings, words, and actions,
ye may come to receive judgment,
and through that ye may receive power to live a new life,
in which God is served in the truth, and not the devil, who is out of the truth;
for in the truth is the holy unity and the pure dominion,
and the everlasting life promised and received, and the royal seed, which the elect have,
wherein they have the bread of life.

G+++.+++ F.

[.centered]
=== Letter 212.

[.blurb]
==== To a Friend under an exercise of spirit.

Keep low in the power, and thy eye in the seed, that destroyeth the devil and his works,
and bruiseth his head; and live up in the seed, which was before the devil was,
that in that thou mayst have life and peace in that which was before death was.
And in the seed Christ, thou wilt have dominion over all thy enemies,
and see before they were.
And that which letteth thee to see thy hardness, darkness, thoughts, and temptations,
and the tempter, and thy confusion, deadness, and thy wants, is the light, and power,
and spirit of God in thee, which the bad spirit persuadeth thee to look out at.
And then thou murmurest and complainest, and art discontent, and not quiet,
and then the enemy and death covers thee,
and through that the mind comes to be unestablished.
And therefore keep to the good spirit in thee, which doth manifest sin and the devil;
and thy mind being stayed by that, it will inform thee.
And keep thy mind in the seed, in that is thy life; and look at the good,
and not at the bad, but over it.
For it is not a sin to be tempted; and that which the accuser layeth to thee,
and thy mind being against it, and not yielding to it,
it will never be laid to thy charge: and that thou wilt see,
as thou with the power of the Lord dost overcome.
And God give thee dominion in the life, and power, and truth, in which is the blessing,
and peace; and the Lord God Almighty bless thee in that.
Doubt not, faint not, question not; for Eve was deceived by the serpent, the questioner;
therefore keep over him in the power of God, and in that is the reigning.
And take not belief from the serpent, nor take meat from him,
but keep thy fast from that which is in the fall; for that bringeth from the Lord,
to feed upon the accuser and the tempter`'s food, that feeds unbelief.
And therefore keep thy fast to the Lord, and feed upon that which comes down from above,
in which there is life; and that strengtheneth that faith which hath the victory.
And therefore keep good faith in him that was before the devil was, Christ,
the first and last; and in him sit down, who is the amen.
And when thou hast been troubled, and resisted the tempter,
hath not the angel of the Lord after ministered to thee, to the strengthening of thee?

G+++.+++ F.

[.centered]
=== Letter 213.

Dear friends,

In the life and power of God dwell, by which ye were raised,
and by which ye are nourished and refreshed;
it is the sure foundation which shall never be raced out, for it is laid of God,
and no man can lay another.
And ye that feel the life and power of God in yourselves, ye feel Christ the salvation,
righteousness, and wisdom of God,
and so ye by the power and wisdom of God are kept
and preserved in sincerity and integrity to God;
and thereby come to be established upon the rock,
which the gates of hell cannot prevail against,
nor all the fiery darts of the wicked touch.
And in the power of God, ye being gathered and established,
ye stand and live in that which `scatters the clouds,
and keeps your eye clear to the Lord God;
by which power ye see him (in measure) with a good understanding,
through all the evil powers and spirits which work in the darkness against him,
and by the power of God are preserved out of them, and set above them,
where ye reign as kings in the immortal seed of God,
by which the serpent`'s head is broken, and his seed destroyed.
For the true freedom is in the son, who suffered and died, and is risen again in life,
and hath brought life and immortality to light again;
in which life and light ye are the children of the Most High God,
and heirs of the everlasting kingdom of God, where ye have a sure portion in the joy,
and peace, and blessing of God, in which sit ye down and keep your habitation.
And the God of life and peace, and endless love be with you all,
and clothe you with the garment, of everlasting praise;
that in all things ye may give him the glory who lives forevermore.

G+++.+++ F.

[.centered]
=== Letter 214.

[.blurb]
==== Concerning keeping on the hat in time of prayer.

Friends, the power of the Lord God is over all them that keep on their hats in prayer,
and they do not keep on their hats in prayer neither by the motion, nor the power of God,
nor by the spirit of God, but (by an earthly, dark spirit) against it,
and them that are in the power of God.
This was the first ground of it, both in Jo. Perrot and his company, when he run out,
and J. N. when he run out;
and this first was done in opposition to them that were in the truth,
and in the power of God; but the power of God will crush to pieces that feigned, dark,
earthly spirit, and to the earth and pit it must go,
with all its feigned and false pretences;
and the power of the Lord God and his truth reigns over it all.

The first that got up into this posture of keeping on their hats in prayer against Friends,
were the Ranters.
The next was J. N. but he quickly, by the power of the Lord, saw it, and judged it;
and the next was Jo. Perrot, whose end was according to his work,
and so will those that continue in it.
For the power of God is over them, and their dark, earthly spirit:
and the power of God was, before they were, and will remain when they are gone,
and it reigns over them all.
And that is the word of the Lord God to you all.
And for my part, I had as lieve see a priest stand up in a meeting, as one of these dark,
earthly spirits with their hats on their heads, when that Friends pray;
for they cannot deceive Friends.
For I have been more burdened with their dark, subtle, and sophistical spirit,
than with the priests,
which had no more show of reverence to God (in that) than to a horse,
whose outward seeming righteousness hath deceived many, but the power of God,
(which destroyeth the deceiver,) undeceiveth and bringeth
people to that which did first convince them.
And they that kept on their hats, when Friends prayed,
after awhile some of them ran to the priests to be married,
and some to hear them in the steeple-houses; then this dark, earthly spirit could bow,
and put off its hat to its own; the dark spirit,
which kept on the hat in the assemblies of the righteous,
in opposition against the spirit and power of God.
And so, this spirit hath led people into a feignedness of love and liberty,
which the power and spirit of God cannot own, but judge and stand over, and reign over,
if they keep their habitations in the power, and life, and truth of God; which reigneth.

If they, that are and have been in this dark, earthly spirit,
had but had a regard to the power of God and his truth, they would have been tender,
and afraid of giving any occasion of offence, both to them that are within,
and to them that are without,
to draw out their minds to look at that which their earthly spirit has promoted;
and so to lay stumbling blocks, and set up an idol, and an image to look at,
which draws people`'s eyes from the witness of God in themselves.
But the power of God is gone over it, and will break it down.
And so, this Belial`'s spirit, which would be without yoke, cries,
(to such as in love exhort them, and judge it,) ye lord over us.
And so this earthly, dark spirit,
(which is gotten above the witness of God in themselves,
which is not sensible of the moving spirit and power
of God,) it sets up its own earthly form,
which the power of God never set up, but judges.
And this earthly spirit judges all, that are gathered together in the power,
and that are constrained by the power and love of God, in a familiar way,
to take one another by the hand, through the dearness and nearness of the love of God,
and the pure, clean, and holy life;
and also are moved by the power of the Lord God to put off their hats in prayer.
This dark, sophistical, earthly spirit,
thus hath judged these practices of the people of God afore-mentioned, to be but a form,
which are done in the power of God, it being out of the power itself,
and the fellowship and unity of it.
And because they, that are in it,
are gone (from that which first convinced them) into outward things,
and into their form in the earthly spirit, it judges those that will not follow them,
that have lost the power of God.
And thus many of them are darkened with a cankered, rusty spirit,
which will corrupt them, and hath destroyed many.
And this is that that has brought the plague of hardness of heart,
through which there has been strangeness, and not unity, nor familiarness,
nor nighness in the truth; for how should it,
when they are gone from that which first convinced them?

To that all must come,
before they have fellowship and true unity in the power and truth of God; which,
if that had been minded, would have led to follow, "`whatsoever things are comely,
whatsoever things are decent,
whatsoever things are of good report,`" and such things as make for peace.
But this spirit has followed the contrary, and therefore the power of the Lord God,
and the life and truth, are against it, and over it are gone, and reign.

And ye, with your earthly spirit and earthly form,
have given occasion to the world to say, "`that the people of God called Quakers,
are divided, some with their hats on, and some with them off,
and so they are opposite one to the other.`"
And these are the fruits of the earthly spirit,
which would bring darkness and earth over all;
but the power of God is over this dark and earthly spirit, and the world,
and them that are in it; and looketh upon them and the world as one,
against the truth and the power of God.
And the people of God called Quakers are one (and
not divided) in the power of God and his truth;
and in God`'s power and spirit they are in unity
in the truth and power of an endless life.
This I was moved of the Lord God to write.

G+++.+++ F.

[.centered]
=== Letter 215.

[.blurb]
==== To Friends that labour in the ministry, that their lives may preach.

Dear friends and brethren, amongst whom the vine is manifest,
and who are (by faith) grafting into it,
through and in which ye may bear fruit to glorify God; be wise in all things,
and harmless, that your lives, conversations, and innocency may preach,
and reach to the hearts of all your opposers and persecutors.
And be faithful and valiant for the truth upon the earth,
and tender to one another in all convenient outward things, for that is the least love.
And dwell in that which redeems you from the earth, the power of God,
in which ye may know the kingdom which is everlasting, and come to be heirs of that;
that ye may sit down in your own possession, knowing the seed of God,
which was before the seed of the serpent was, knowing the birth born of the spirit,
which was before the birth born of the flesh was.
And so live in the truth, by which ye may see over that which stains, corrupts, cankers,
loads, and burdens the creation;
by which power of God and truth ye may answer the spirit of God in all,
which the wicked grieve, vex, and quench by their ungodly lusts, and filthy conversation,
and unsavoury words.
Fear not sufferings, which bring to wear the crown.
Fear not him that can kill the body only, but cannot hurt the soul;
for that that is immortal goes over him.
Fear God, and fear not him that can spoil the goods;
for the earth is the Lord`'s and the fulness of it.
But mind God`'s power, and let your patience be perfect,
and all your words seasoned with grace, that they may edify;
by which ye may season the earth, your hearts being established in the same,
over all the unsavoury words and talkers, and live in the truth above them.
And let your backs and cheeks be ready to the smiters;
that ye may overcome the evil with the good, and may heap coals of fire upon their heads.
For it is the good that overcomes the evil, and the lamb that hath the victory;
the rough goat must not.
So let your moderation be known unto all men, honouring all men, that is,
having them all in esteem; that ye may set them in the way of salvation and life.
That the power of God may come over them,
that your meekness and gentleness may prevail over the rough,
and in boldness in the unalterable, holy way, you may be preserved;
which is the new and living way, which is the light and life,
which brings into covenant with God, in which there is peace.
In which the Lord God Almighty give you dominion, and preserve you by his power,
into the endless life, where ye all may know happiness and peace in the pasture of life,
where all the sheep and lambs feed; in that the Lord God Almighty preserve you!

G+++.+++ F.

Let copies be sent to Virginia and Maryland.

[.centered]
=== Letter 216.

[.blurb]
==== To Friends in New England, and the islands beyond sea.

To all my dear friends and brethren,
among whom the precious truth and power of God hath been declared, and joyfully received,
whose belief, confidence, and innocency are spread abroad who are come to the vine,
Christ Jesus, that is your shade; whom bonds and death have not dismayed,
for the worth of truth sake.
And fetters, irons, whippings, stripes, and spoilings of goods,
and the like cruelties and persecutions have not daunted ye, whose courage, valiantness,
and boldness for the truth, have much appeared among a crooked and perverse generation,
that professed Christ,
and among whom he hath not had so much place of entertainment
as in their manger in the outward;
whose hearts are dens of dragons, and places of darkness,
and whose religion and profession they have shamed,
being unfruitful in the ways of God and Christ, workers of darkness,
whose iniquity hath flourished and sins sprung as the grass;
that their folly and shame might cover them,
and that they might be confounded in their iniquity.

So ye in the power of the Lord God, in his might, and strength, and hand,
that brings your salvation, stand;
in which power and arm ye see over that which brought destruction; in which power,
(that is the gospel,) life and immortality come to light,
and captivate that which hid life and immortality; living in the power of God,
see over it, and in that standing, all your feet are sure.
In which power of God, (the gospel,) which goes over the power of darkness,
and was before it was, ye see before all transgression, and how all things were blessed;
which power goes over all that which bringeth the curse, wrath, woe, misery, thraldom,
bondage, and captivity, by which power of God that is taken captive,
in that live and dwell; in which ye all have unity, peace, concord, love,
and fellowship in the gospel, which goes over the enmity, and was before it was;
in that ye bind and unite, and are established, and are gathered up to.
Christ, who was before transgression was, which hath scattered from God.
In the power of God see over all the meetings and the gatherings,
that are in the transgression, unestablished, like water;
in this power is the praying to the living God, that lives forevermore.
And then is the gospel, that is everlasting, preached unto all nations of mankind,
and all that are driven out from God in the power of darkness;
to the intent that they may all come up again to God,
and have life and immortality brought to light by his Almighty power,
that expels death and darkness.
So, in this gospel, the power of God, let all your faith be and stand,
then are ye all but one.
And so all ye that have tasted of the power, sit down under your own vine,
and abide in it,
then will ye bring forth fruit through the power of God and Christ Jesus,
who is the vine, which goes over the powers of darkness,
which is the cause of unfruitfulness.
Which power of God, Christ Jesus, destroys the devil and his works of darkness;
and dwelling all in the power of God, ye will have every one of you a habitation in it.
For God`'s power is sprung up in your hearts,
so in nowise abuse it through strife or jangling, for that eats out.
But all in the power of God live and dwell, which makes you subject to God,
and one to another in his fear, that keeps you from sin and evil,
which is the author of strife; and through the power of God ye will be all kept in unity,
and peace, and love.
And as many as receive the light, Christ Jesus, the power of God,
which he hath lighted you with,
(who hath all the power in heaven and earth given him,)
he will give you power to become the sons of God.
Therefore every one receive Christ the light, that hath enlightened you,
and ye shall feel the power, in which light ye shall all have fellowship;
which light will give every one of you the knowledge of the glory of God,
in the face of Christ Jesus, your saviour.
And in the power of the Lord God, which hath gathered you over the powers of darkness,
and all the meetings therein, in that power of God live, which is everlasting,
and keep your meetings; in that ye may feel fulness of life, and wisdom from above,
before that which is below was, by which ye may all be ordered to God`'s glory,
and order all things under your hands to his honour.
Through which wisdom ye may be a blessing to the Lord God in your generation,
and a sweet savour to him in the hearts of all people upon the earth, yea,
the very heathen, who are enlightened, to bring them to the light,
which Christ Jesus hath enlightened them withal;
that they may come to the knowledge of the same salvation or condemnation.

So spread the truth abroad, ye that are in it, and have it, which the devil is out of,
who hath darkened people from God, and his covenant, and his way;
through which they are strangers to his life, and kingdom that hath no end,
and dominion that is everlasting; wandering in strange paths in the dark world,
that lies in unrighteousness, which the devil hath made like a wilderness,
full of briers and thorns, that the lambs in it can hardly walk or work.
Yet work ye and labour in the power of the Lord God that lives forever;
in it make vineyards and plantations,
to the renewing of people`'s minds in the light and power of God,
and the knowledge of Christ Jesus, turning them from the enmity and the darkness,
(the power of Satan,) to the light, and to God,
that they may be renewed into his image and likeness; that the image of the devil,
and his likeness, may be defaced,
which is gotten up in the hearts of men and people since the beginning, in transgression.
So bring them to the great sacrifice, the Lord Jesus Christ, the seed of the woman,
who offered up himself for the sin of the world, the top-stone, which is over all laid,
who is restoring by his power, who hath all power in heaven and earth,
who is restoring all things into the place, as they were in the beginning,
and reconciling in one, by his power, things in heaven and things in earth,
destroying that which made the separation, and broke unity,
which is the enmity in people`'s minds,
which the light that doth enlighten every one that cometh into the world destroys:
through which all people come to have peace with God, and fellowship,
who do believe in it.

So spread the truth abroad, and be valiant for it upon the earth, improve your talent,
and be the wise virgins, with oil in your lamps;
that ye may enter in with the bridegroom.
Have salt in yourselves, that ye may savour all things,
and keep your consciences clean and pure unto God and all men.
Live in the cross of Christ, and rejoice in it, which is the power of God,
and goes over all that which lives out from God, and which is in the transgression,
and its fruits, to which it is death; to this cross, the power of God,
all must bend and bow.
And in the power of God is the fellowship of the cross,
which keeps over all the fellowships in the world, and crucifies to them.
And so ye who are heirs of the power of a world that hath no end,
and a kingdom that is everlasting, sit down in your inheritances of the power,
of the kingdom, of the blessing, of the promise, that are heirs of the same;
that ye may increase in the everlasting, in the blessing, and heavenly riches.

And though the oppressors of the earth will not let you have a foot of ground,
yet ye have the power of God to stand in, and so ye that are heirs of that,
and Christ Jesus, whose the earth is and all things therein, and are in the power of God,
separated from the power of darkness, the devil,
and are come into that which was before he was, ye have nothing to lose,
for all yours is the Lord`'s. For they that are separated by sin and transgression,
drove into the earth, there they stick fast, and have much to lose;
whose hearts are surfeited with the earth, and to that glued;
and all their fellowship is out of the cross of Christ, the power of God,
and are within the power of darkness and its dominion, over whom it hath the supremacy;
which the power of God goes over, in which is the son`'s liberty,
and the saints`' fellowship, that lives forever, through which they have eternal life.

Let this be copied over, and sent abroad to the Isles, and unto New England and.
Virginia.

G+++.+++ F.

[.centered]
=== Letter 217.

[.blurb]
==== Concerning judging, etc.

All my dear friends and brethren, who of the mighty power of God have tasted,
in which it hath brought you to the measure of the life of truth,
and to feel after God in it; unto which ye are turned,
as a way that is living and has no end, which is Christ Jesus, who is the way of peace,
and destroys the devil, the author of strife.
All ye that are turned unto this living way by the
power of the mighty God of heaven and earth,
live in peace one with another, and unity; and do not judge one another,
for that eats and wears out the good, and begets the enmity; and hinders growth in truth.
Keep that down, and live in love and peace, that edifies.

And all everywhere, unto you this is the word of the Lord God:
live in the power of the mighty God of heaven and earth,
that goes over the unrighteous world, in which is the strife, and the devil,
and his works; which power of God was before they were; in that ye will feel unity,
which was before strife.
So dwell in that, in which ye may have a kingdom that hath no end,
and the dominion that is above all dominions upon the earth.
In which power of God ye may enlarge your borders, and spread truth abroad both to Jews,
Christians, and heathens; having the power of God, that goes over them all,
and was before they were.
With that power of God ye will answer the witness of God in all, and bring them to that;
that with that they may have a part in the kingdom of God;
and a share with you of the same; in which ye will have peace, life, joy, dominion,
and prosperity.
And so it will be your life to do good, and to beget into life, up to God;
and in that power, that doth so, ye will not labour in vain.
But above all things take heed of judging one another,
for in that ye may destroy one another, and leave one another behind,
and drive one another back into the world, and eat out the good of one another;
and so hinder unity, hinder growth in the life and the power of God,
in which ye should have peace and joy in one another, and love, which edifies,
and overcomes, and gets the victory.

So, go on in the truth, answering it in every one in the inward parts,
and in the power of God, which comprehends deceit, which was before it was,
in that is your life, and in that the kingdom is felt that never hath an end,
and the dominion over all dominions; in that stands your peace and joy,
in the holy ghost, which is the spirit of God,
that plungeth down that which made the separation from God;
in that will be your fellowship,
which will stand and remain when all the fellowships of the earth are gone.
In which fellowship in the spirit ye will have fellowship with God,
the Father of spirits, and all the scriptures given forth from the same spirit,
and with all the saints that gave them forth, and with their spirits;
through which spirit of God ye will be brought, and come to the spirits of just men,
which are made perfect, and to God, the judge of all.
In which, (as I said before,) ye will have an everlasting fellowship,
in which spirit ye will have an understanding,
in which spirit ye will come to worship God, the Father of spirits, and in the truth,
which the devil and his works are out of, and all the will-worshippers.
So, in that ye will know the royal dominion and royal fellowship;
in which spirit ye will have the spirit of wisdom,
in which ye will know how to pray to God, who is a spirit,
and to praise and glorify the everlasting God, who lives forever and ever, amen!
And in that ye will come to know and see to the beginning, before the world began,
and that which quencheth, and grieveth, and vexeth the spirit of God; and that prayeth,
and that preacheth, and that praiseth, and yet grieveth, and vexeth,
and quencheth the spirit of God; such God, the Father of spirits accepts not, that judge,
rend to pieces, and tear one another about inventions.

Now ye being led by the spirit of God up to God, the Father of spirits,
in which ye have the fellowship, out of all that you will be kept;
and in that spirit of God the Lord God Almighty preserve you and keep you,
and in that meet and dwell,
in which your meetings may be preserved over all that which is in the world,
that are out of the spirit of God; who are in confusion, contending about the words.
Therefore ye in the spirit of God, answer that of God in them all.
So, in that dwell and live, and let no man take your crown.

Send copies of this to all Friends that are convinced in New England, Barbados,
and all the islands thereways.

G+++.+++ F.

[.centered]
=== Letter 218.

[.blurb]
==== To Friends in Ireland.

Dear friends and brethren,

Let patience possess your souls, and in the seed of God dwell;
that over all the top-stone may be laid and set.
And the kingdom of peace dwell in, which hath no end;
in which ye will feel the Supreme Head: and in the power of the Lord keep your meetings,
which was before the waves were, or winds either.
So in that look over all, and keep in the faith,
by which ye will have access to God over that which separates from God;
in that ye will have unity, and will not fear the amazements which are in the sea,
because of the winds, and storms, and blusterings,
who know the election which was before the world began.
And live in peace and unity in that, and send over how things are among you.
(I am in the north, at Swarthmore.) And, dear friends and brethren, be not troubled,
but dwell in the seed of God, which goeth over all this;
and remains and stands when all this blustering is ended and gone.
Therefore look at the Lord above all, and his arm: for God had a rod in secret,
to fetch down these persecutors, who have long reigned in their wickedness,
until they were neither fit for God, nor man hardly.
So again, God hath a rod in reserve, to bring down these spirits, which have been a rod.
Therefore all dwell in the power and spirit of God,
with which ye will comprehend all that which is to change,
with that which doth not change, and hath no end; in that live,
and ye will have an everlasting unity: and to you this is the word of the Lord God.

G+++.+++ F.

[.centered]
=== Letter 219.

All my dear friends, dwell in the life, and love, and power, and wisdom of God,
and in unity one with another; and the peace and wisdom of God fill all your hearts,
that nothing may rule in you but life, which stands in the Lord God.

G+++.+++ F.

[.centered]
=== Letter 220.

Friends,

Truth is that which is pure, and is that which the serpent is out of;
for there is no serpent in the truth, and it admits of no impurity:
and so there is no serpent in the way of truth, to bite and hurt any;
for the way being the truth, is the same as it was in the beginning,
though many things have risen against it: yet it remains the same pure truth,
and holy way.
So if any one have gone from it, they are for condemnation, and their works.

And when any thing is once condemned and judged, let it not be raised up again,
but keep it in the grave, and raise not up the dead out of the grave any more;
they living in the life and light which doth condemn and judge it.
And all live in the love of God, which gives dominion over all,
and unites and edifies all that abide in it.

If, among Friends, any reports or surmises be about any, or any backbitings,
or whisperings, all such things must be stopped and searched out;
for thus saith the Lord, "`Thou shalt not raise a false report among my people.`"
And that some of the faithful Friends of every meeting,
whose sincerity is for the glory of God, his honour, and his holy name,
(into which they are all called,) may be chosen to search out such things,
and follow it till they find out the author or authors of it,
that it may not lie upon any, nor in any;
but that all may be cleared and taken out of every mind, and all the reports stopped;
and the things that are for judgment, let them be judged and condemned.

And furthermore, that Friends take notice of all such Friends as go to sea, seamen,
merchants, masters of ships and passengers, abroad and at home, that profess the truth,
that if they have any ways dishonoured the Lord God, and brought an evil report,
either in their trading, lives or conversations, upon the truth and the good land,
and dishonoured the Lord God and his name, truth, and people;
that they may search into the bottom of it; that so,
if they have done any thing worthy of condemnation and judgment,
it may be past upon them without any respect of persons.
And, if the report be false, let their innocency be manifest, and the reporter reproved.
And so, that all that profess truth, may walk in the truth and the light of the Lord,
who are "`children of light,`" who have their name after the living God.

And all to be circumspect, diligent, and careful in all these things,
that in nowise God may be dishonoured; but in all things your lives,
and words may preach, that profess the truth.
And all of them that have gone from England and dishonoured God beyond sea,
to write over sea, to search out and know the ground of the matter,
that all obstructions that have hindered the glory of God,
and the spreading of his truth, may be taken away;
that the Lord`'s name may not be dishonoured, nor his way and truth evil spoken of.
And so, all reports being searched into, in all the plantations,
concerning Friends there,
that if any one hath done any thing to dishonour truth beyond sea,
let them come to judgment and condemnation, and give forth papers of the same,
that the papers may be sent abroad to take off the reproach from the innocent,
and so answer the witness of God in them through their repentance.
And, if they will not write their own condemnations,
then Friends must write and deny them, and take it out of the mouths of the world.

And all Friends that have dishonoured God, and his truth, and people,
and Friends have been to admonish them in a gospel-way,
and they still go on in their wickedness and do not repent;
Friends may draw up a paper at their meeting,
(when they are clear of them,) against them and their disorderly walking,
and unruly spirits, and looseness, in general words, not mentioning the particulars,
except they be notoriously known.
And Friends to do this with speed, and to bring it to the meetings;
and if any one be known to be an open offender,
that then there may be an open testimony against him in the particular;
showing that we have no unity nor fellowship with such workers of darkness,
and how that they cast out themselves from amongst us,
being gone from the life and power of God; in which our fellowship is.
And that copies of the paper may be read in meetings,
and the copies of the papers to be sent to the men`'s
meetings in the countries where they live.

G+++.+++ F.
