== Letters 221 &#8212; 232

[.centered]
=== Letter 221.

My dear friends, all everywhere, the power of the Lord God, that first convinced you,
and his light and truth, all wait and walk in,
and keep your first habitations in the power of the Lord God, and in his light, and life,
and spirit, by which all your minds may be stayed, and kept up to the Lord God,
in the unchangeable light, life, power, and spirit.
And so ye living in the unchangeable life and light, ye see Christ, that does not change,
but ends all changeable things, types, figures, and shadows,
and destroys the author of all evil inventions and traditions
among all the sons and daughters of Adam in the fall;
and so live all up in the royal seed, in which ye have life, which life was before death;
walking in the light, which was before darkness, and in, the power of God,
which was before the power of darkness was;
which power of God will keep you out of all feigned spirits,
creeping in a pretence of love and innocency,
to draw your minds out from the power of God, and your first habitations,
into some outward things; which will draw the mind outward from the power,
and so from your habitation of peace; through which trouble will enter,
as it hath done upon some, who now do see how they have gone from their habitation.
Therefore in the power of the Lord God, which is everlasting,
in which is the fellowship live; which power of God is perfect,
in which is the perfect fellowship, which was before imperfection was.
In which power of God is the joy and life;
and ye keeping in your habitations of the light, life, and power of God,
(the gospel,) by which you all see and discern your own conditions,
with the spirit of discerning, laying hands on no man suddenly,
but proving and trying all things; seeing your own conditions by the power of the Lord,
and his light, by which ye may have the spirit of discerning,
waiting and walking in the truth, that ye may adorn it; walking in the truth,
which was before untruth was.
And whatsoever is comely, decent, and of good report follow and walk in,
which is to the answering that of God in every one;
for living in the power of the Lord God,
through which ye have every one a habitation in God;
by the power of God ye will come over enmity, and see before it was;
for its habitation is in the earth, and some outward things,
but the power of the Lord God,
and the truth he is out of (who is the author of enmity,) and being gone out of truth,
seeks to bring others out of their habitations, the power of God.
Therefore live in the power of the Lord God,
and keep your habitations in the light and spirit in your own particulars,
that by it all your minds may be subjected to God; in which you may all live in peace,
love, and unity, and the royal spirit and seed of unity and dignity,
which keeps over the spirit of strife, and was before it;
for the strife among the sons and daughters of Adam,
in their fall from righteousness and holiness, and the image of God,
is about these outward things.
Therefore mind the power of God, and the righteousness and holiness,
and your renewings into it,
(which was before the fall was,) and follow that which makes for peace in the truth,
and in the life and power of God, which peace will stand,
in the same dwelling in love and unity, by which ye may all honour the truth,
which will keep you over all the fallen spirits, that are striving,
and are busy about that which is in the fall,
manifesting that they be fallen from the power of God,
and gone from their first habitation; in which power of God is the peace,
in which the kingdom stands.
Therefore all mind that, and to be heirs of that kingdom that stands in righteousness,
peace, and joy in the holy ghost.
And so feel the seed of God over all that set that makes to suffer,
which was before that was,
and will stand and remain when that which makes to suffer is gone,
in which you may all feel the life, which was in the Father before the world began;
and feel Christ to reign amongst you, who is the prince of peace and life;
and this will keep you from being tossed and carried about with strange doctrines,
(for the seed Christ was before they all were,
and will remain when they are all gone,) in a pretence
of new discoveries and outward things,
to bring people`'s minds from their habitations of life and truth;
which comprehends all things, and sees all things.
Therefore mind the spirit of truth, and the unfeigned love, and faith that works by it,
over all the feignedness, that by the shield of faith, the sword of the spirit,
that may be cut down, that none may be deceived by that, but keep the unity of the faith,
that gives you the victory and access to God, and the unity of the spirit,
the bond of peace, and the fellowship of the gospel, which is the power of God;
which power of God was before the power of Satan was, in that live,
and meet and walk in the name of the Lord, which is a strong tower,
(whose name is the power,) and in the tower is the safety over wickedness,
and before it was; sitting under your own vine, and abiding in it,
then ye abide in Christ, by whom the world was made, who is the light, life, and truth,
and the power of God; and as ye abide there, ye bear fruit to the glory of God,
and through him ye come every one to have a habitation in God,
who brings out of the fall, where the curse is,
to the state that man was in before he fell, and to the blessing,
and not only to that state, but to him that never fell, in whom the saints sit down,
in whom are the pastures of life, and riches eternal, everlasting,
and the blessing of the Lord, that with that ye may be clothed.
And so farewell!
My love to all Friends in the everlasting seed of God, that never changes,
which was before changings were, and stands when all changings are gone,
that ye may know Christ to reign amongst you, the prince of life,
and the prince of peace, and the counsellor hearing the voice of the light, the life,
the power of God, and truth`'s voice, which goes before you,
who will give you life abundantly, even that which is eternal.

Now the professors may see, that the hireling is fled and flies,
because he was an hireling, whose religion was for the summer, whilst the sun shined;
but in a storm, a tempest, a mist, or the sun clouded, their religion they flee from;
his flight is in the winter.
So the day manifests all things.
Our religion is in the power of God, before winter storms and tempests were, mists, fogs,
or clouds; in the light which shines over them all is our religion, that does not change,
in which there is fruit borne in the winter;
by which power of God all their religions are seen which must have an end,
and will have an end, which people run into.
But in the power of God, and his righteousness and holiness,
which was before the fall was, live; which power of God never alters nor changes,
in which is both life and peace which, remains forever, in that dwell and live;
and be faithful and valiant on earth, your hearts established with grace,
and your words seasoned with the same; keeping yourselves in the love of God,
and in the life, in which is peace, through which ye may be all a comfort one to another,
living in the life, in which is till everlasting fellowship.
And so in that the Lord God Almighty preserve and keep you all.

Let this be read in all your meetings in Barbados, New England, Nevis,
and sent to Jamaica, Virginia, and Maryland, to Friends there;
and to all the parts in the world, where there are Friends.
A general epistle to them all, from Colchester in England.

G+++.+++ F.

The 10th day of the 11th month, 1662.

[.centered]
=== Letter 222.

A general epistle to be read in all the christian meetings in the world.
Blessed is he that readeth, and blessed is he that heareth and understandeth,
and the eyes that see.
Read this over, and you may read that which you have not read,
and see that which you have not seen.

My dear friends all everywhere, in the seed dwell,
which is Christ the top-stone over all; feel it laid, in Which is life eternal,
which is over death, and before death was, and the devil, the power of it;
every one sitting under their own vine, which is Christ the life,
by whom the world was made, that in that ye may all bear fruit to God;
and all walking in the name of the Lord,
(which is the power,) then you will walk in safety.
For blessed are all you that rise in the power of God, and lie down in the same power;
your beds are pure, holy, and undefiled, who lie down in the power of God,
before unholiness was.
And so you that are gathered in the name of Jesus, who have bowed to the name of Jesus,
whose name is called, the power of God, and the word, light, life, and truth;
and for bowing to his name, for his name sake have ye suffered all along by many powers;
his name is a strong tower.
So who have bowed to the name, and gathered in the name of the Lord,
ye are in the strong tower, in which is safety and peace;
for being gathered in the name of Christ Jesus, whose name is above every name,
(for all things that were made,
were made by Christ,) above all other names and gatherings are you gathered,
who are gathered in the name of Jesus Christ, by whom all things were made and created;
and being gathered in the name of Jesus Christ, by which salvation is brought,
by the name of Christ, and not by any other name under heaven,
but by the name of Jesus Christ is salvation brought, by whom all things were made.
So ye being gathered in this name, by which salvation is given,
here ye come to be heirs of salvation, and then to inherit salvation, which is Christ;
and by this you come to fathom all other names under the whole heaven, and to see them,
that there is no salvation in them;
and so likewise all other gatherings in all other names, no salvation in them;
therefore cry people, there is no assurance of salvation upon the earth,
who are gathered in other names, but not in the name of Christ,
by which salvation is brought and given; by the name of Christ,
by whom all things were made; and this is the standing gathering; in the name,
in the strong tower, where is the safety, where is the salvation given and brought.
Rejoice ye all that are brought into this gathering, and have bowed to the name of Jesus.

Now to bow at the name of Jesus, who is called, the power of God,
is to bow to the power of God; all things in heaven, and things in earth,
must bow to the name of Jesus, before they be reconciled to God;
for all things in heaven, and things in earth, are reconciled by him in one.
So they must bow to the name of Jesus,
as they have bowed to the evil through which they are at difference one among another,
and not at unity, but bowing to the name of Jesus brings to reconciliation;
for all things in heaven, and things in earth, must bow at the name of Jesus,
must bow at the power of God, before they be reconciled in one.
So bow at the name of Jesus.

2dly.
You must bow at the cross of Christ, which is the power of God,
which since the apostles`' days the apostate christians have lost;
and therefore they bow to a cross, a stick, a stone, a piece of iron, a piece of wood.
Now bowing to the cross of Christ, which is the power of God,
that strikes over the nature of fallen man; for who bends, and submits, and, yields,
and bows to the power of God within, feels it to rise over and strike over,
and work over the carnal part, and that part that turns into ungodliness,
and all that is bad, and is a cross to it.
So bow to the power of God.
If all Christendom had done this, they had had a fellowship in this cross of Christ,
which is a mystery; but a cross stick, a cross piece of wood, or iron, or stone,
this is not a mystery; but the power of God, that crosseth down the earthly, carnal,
ungodly part in man and woman, and works over it, and strikes over it, and goes over it,
and crosseth it.
There is the mystery of the cross of Christ, the power of God,
in which is the fellowship; which power of God keeps the mind over all outward things,
in the everlasting power of God above them;
for the power of God was before unrighteousness and uncleanness,
and the idolatrous part in man was; which power of God is a cross to it,
and in that is the true glorying in the cross of Christ,
by which ye all are crucified to the world, and dead to the world,
and the world is dead to you; dead to the world through the power of the cross,
and the world is dead from the power of the cross,
(in which power is the fellowship of the cross of Christ.)

3dly.
The fellowship of the gospel, the power of God,
expels away all that which hath darkened the understanding, darkened the mind,
darkened the heart;
and by the power of God life and immortality are brought to light in you;
by which power of God ye come to see before that was,
that hath darkened you from life and immortality,
and over that life and immortality shines, being in the power of God,
which was before that was that had darkened mankind; and the power of God,
(the gospel) expels away that which burdened your spirits, minds, hearts, consciences,
and souls; so that being driven away by the power of God, and the mind set at liberty,
the spirit, the conscience, the heart,
the soul that is immortal being brought up by the power of God,
here the soul hath its pleasure in God; then, by the power of God,
man seeth over that which hath burdened his spirit, mind, soul, and conscience,
and beyond it, and before it was; where the spirit, soul, mind,
and conscience cry "`glad tidings.`"
And here is the joyful gospel, and here is the faith in the everlasting gospel,
the power of God;
and here is life and immortality come to light through the power of God,
(the gospel,) which power of God, the everlasting gospel,
was before that was that darkened man from life and immortality,
and hath loaded people`'s minds, hearts, souls, and consciences;
the power of God was before that was, and remains when that is all gone.
So now, ye that are come to be heirs of the gospel, know it your portion;
for as a man is heir of a piece of land or house, it is his portion,
(which must have an end,) and he comes to inherit it: so heirs of the gospel.
It is the portion of man and woman; and they that inherit it,
they inherit the power of God, which hath no end;
which was before the power of darkness was,
which hath darkened people from life and immortality, and loaded their spirits;
but being heirs of that which was before that was, here you inherit the gospel,
you inherit the power of God, in which is stability; here you are church members,
and here you are living stones, and here you are built up together a spiritual household;
here the church in God is known, the Father of Christ, who is the way to God,
where the church is; for now, as Adam and Eve were drove from God, and being in the fall,
their sons and daughters have their churches enough, heaps upon heaps,
one against another, and heads of every church,
and there they plead for sin while they live upon the earth;
but the church that is in God, the Father of Christ, doth not so;
for as mankind were drove from God, they must come up again out of that state,
where they are defiled, and be washed, sanctified, and cleansed,
and brought up out of the fall, up to God again.
If they come to the church that is in God,
and the fellowship which is the gospel fellowship, which is the power of God,
in which is stability, before that was that hath unestablished people; the gospel,
the power of God was, and before the devil was, that hath unestablished people.
In which gospel is peace, stability, life, and immortality, which is come to light again.
In this is the church fellowship with Christ in God, which will stand;
for the gospel is everlasting; the church of God is the pillar and ground of truth.
Therefore this will stand,
when all other churches and fellowships amongst the
sons and daughters of men in the fall,
will have an end.
The church in God will stand, the pillar and ground of truth,
and the fellowship of it will remain.
Therefore, ye heirs of the gospel, (and church members of it,) inherit it,
and set down in the fellowship of the same.
And this is beyond all the writings, subscribings,
and promisings to the church fellowships that be
among the sons and daughters of Adam in the fall;
that when a storm comes, or a tempest, they fly from their church and fellowship both.
But the gospel stands, the church in God stands, the pillar and ground of truth;
which the gates of hell cannot prevail against.

4thly.
The worship of God is In the spirit and in the truth,
that is the public worship which Christ set up;
he preached it when he put down the worship at the mountain, and at Jerusalem, and said,
God is a spirit; and they that worship him, must worship him in spirit and truth;
and the hour is come, and now is, that the Father seeks such to worship him.
Then the hour was, that worship was set up, above sixteen hundred years since,
when he denied and put down the worship at the mountain and at Jerusalem,
where the forefathers worshipped.
So this worship in the spirit and in the truth, was contrary to the forefathers.
This is the public worship, and this is not private nor particular;
the nation`'s worships are particular, which the sons of Adam are broken into,
the several worships one against another;
but this worship in the spirit and in the truth, hits all men and women;
they must come to the spirit in themselves, and the truth in the inward parts;
this is public, this is not a private worship,
but brings every man and woman to the spirit of God in their own hearts,
and truth in their inward parts; in which spirit and truth they must bow down,
and come into it, if they be worshippers of God in the truth and in the spirit.
And this is the standing worship that Christ preached up, atop of the hill,
where the forefathers had worshipped.
And this worship is over the worship that was at Jerusalem,
and over the worship that was at the mountain; so by this must every man,
every son of Adam, and daughter, come to the spirit in their own particulars,
and truth in themselves; by which they must know God is a spirit,
and will be worshipped in the spirit, and in the truth; and so no man must grieve,
nor vex, nor quench the spirit, but all must worship in it,
and they must come to the truth in the heart, to the hidden man in the heart,
to a meek and quiet spirit.
And they must not rebel against the spirit, if they worship in it; and all coming to it,
they have the adorning, that which beautifies and adorns them in the eyes of God;
none must walk despitefully against the spirit of grace,
nor turn the grace of God into wantonness, if they worship God in the spirit;
if they grieve, vex, quench the spirit of God within,
and turn the grace of God into wantonness,
and walk despitefully against the spirit of God,
and rebel against the spirit of God within, and are haters of the light.
These go from the public worship of God in the spirit and truth, to the particular,
which fallen men have invented; but they that worship God in the spirit and in the truth,
are in that which the devil is out of, and the dragon`'s worship,
and the beast`'s worship, and the will-worship are out of;
who worship in the truth and in the spirit, are over all these worships.
For truth is before they all were,
(and the spirit,) and will stand when they are all gone.

5thly.
To pray in the spirit, this was public, the public prayer set up among the christians;
the temple was the public place of prayer among the Jews; but to pray in the spirit,
is the public prayer set up by the apostles: every man,
every woman then must come to the spirit of God in their own selves;
for it will give them understanding and knowledge, and give them instruction,
it will help their infirmities, it will let them see their wants.
So, in that must every son and daughter of Adam pray in the spirit to God,
who is a spirit: and this is public,
the spirit of God in every man and woman to pray with unto God, who is a spirit;
then in this spirit have they fellowship and unity, and a bond of peace:
and this moderates all people, and mortifies, circumciseth, and baptizeth.
Now, who grieves, and quenches, and vexes, and rebels against the spirit of God within,
in which they should pray, they are like the Jews, babblers,
and go into the particular forms, and go from the public, which is universal,
whereby all men and women must pray to God, who is a spirit, in the spirit,
and keep out of the particular.
One hath one set form, another another, that is particular, as I said before;
but the praying in the spirit is general,
by which every man and woman might see their necessities and wants, and turn to God,
who is a spirit, for his help: for Christ the quickening spirit,
and the spirit of the Lord within,
is that which brings people to lift up their eyes to the Lord in spirit and truth,
and to watch and pray, by which they know temptations;
and the spirit giveth them understanding, and wisdom, and power to withstand them.

6thly.
Singing in the spirit is public; every man and every woman in the whole world,
they must not grieve it, nor vex it, if they sing in it; and this is public.
But they that go from the spirit of God within, they go into the particular singing,
inventing this thing and that thing, and then one will do it, and another will not do it,
and so there is no true fellowship, because it is not done in the spirit;
and there is no true fellowship in their worshipping, nor in their praying,
because it is not done in the spirit; for the true fellowship in singing, in praying,
in worshipping of God, is in the spirit of God, which the devil is out of;
for in that is the bond of peace.

7thly.
The teachers of the world told us (who called themselves ministers
of Christ) that they had received a gift from Christ,
who ascended on high, and led captivity captive;
and this gift was for the work of the ministry, and for the perfecting of the saints,
and that they were to bring people to the knowledge of the son of God,
from whence they had received this gift, and to the unity of the faith,
which faith gives the victory, and brings to have access to God,
and also to a perfect man`'s state,
and to the measure of the stature of the fulness of Christ.
And thus people followed them,
and were glad that they would bring them to a perfect man`'s state, that is,
to the state of Adam and Eve before they fell, for they were perfect then;
and when we had followed them, some twenty, some thirty, some more, some less years;
then they told us again,
that they hoped we would not look for perfection while we are upon the earth,
on this side the grave, for we must carry a body of sin about us;
and they hoped we would not look for perfection,
and would not hold the erroneous doctrine of perfection; and yet told us, as before,
that they would bring us to a perfect man`'s state;
and so we looked they would have fulfilled their words; for we had given our money,
and had spent our labour in following, after them,
and hoped they would have fulfilled their words,
and brought us to the knowledge of the son of God, and so to the unity of the faith,
and to a perfect man`'s state, to our father Adam`'s and Eve`'s state before they fell;
and now they have gotten our money, they hope we will not look for perfection here.
Oh, deceivers!
We will never set foot more after them, who will neither fulfill their words,
nor give us our money back again; for we gave our money,
that they should bring us to the knowledge of the son of God,
and to the unity of the faith, and bring us to a perfect man`'s state,
and to a measure of the stature of the fulness of Christ:
and now the scriptures that speak of sin and imperfection,
they bring to prove that we should not be perfect, against their own promises and words;
and all the scriptures that speak of perfection or overcoming,
they tell us there must be a meaning put to them: and thus they deceived us,
instead of bringing us to the measure of the stature of Christ, who never fell,
the second Adam, the Lord from heaven, who said, they would bring us to his stature;
and now they cannot bring us to the measure of the stature of the
righteousness and holiness of our father Adam and mother Eve,
that they were in before they fell; for they had no body of sin before they fell,
nor spot, nor wrinkle, nor blemish: so, the deceivers have got our money,
and now call that an error, which they said they would bring us unto,
(a perfect man`'s state,) and so will not fulfill their words,
nor give us our money back again neither.
Therefore now mark which of these three states the shepherds, the teachers,
and leaders kept their flock in, and do keep them in.
Whether is it in the state of Adam and Eve in the fall, where the body of death,
the curse, wrath, and woe are, imperfection, spots, wrinkles, and blemishes,
and tell them they must be there for term of life?
Or, whether or no can they keep them in the blessed and
good state of righteousness and holiness,
that Adam and Eve were in before they fell?
Or, whether or no can they keep them in the measure of the stature of Christ,
who never fell.
Now consider which of these three states do these
shepherds pretend to keep their flocks in,
that deny perfection,
and say their sheep must carry a body of death on their backs while on earth; for,
"`As the tree falls, it lies,`" and there is no repentance in the grave.
Whether it be not in Adam and Eve in the fall, with his sons and daughters?
Or, in that state before they fell, which was a good state, in righteousness and holiness?
Or, whether it be in Christ that never fell,
whom it cost his blood and his life to fetch Adam and Eve, and his sons and daughters,
out of that state in the fall,
(out of the unjust state,) to set them in the state before they fell; and not only there,
but to bring them into himself that never fell.
Now what value, and price, and worth have they made of the blood of Christ,
that cleanseth from sin and death;
and yet told people that they would bring them to the knowledge of the son of God,
and to a perfect man, and now tell them they must not be perfect on the earth,
but carry a body of sin about them to the grave?
As much as to say,
they must be in the state of their father Adam and their mother Eve in the fall,
under the wrath, curse, and woe,
and must not come to the state they were in before they fell, to the image of God,
in righteousness and true holiness.
And thus the deceivers are not worth the setting foot after.
And yet ask them for what end Christ came?
they will say, to destroy the devil and his works.
And then ask them,
if the body of sin and death be not the devil`'s works and imperfection?
they will say, yes; and so are in confusion:
Christ came to destroy the devil and his works, they say,
and yet they must carry them to the grave; and yet people are saved by Christ,
they will say; but while you are upon earth, you must not be made free from sin.
This is as much as if one should be in Turkey a slave, chained to a boat,
and one should come to redeem him to go into his own country; but say the Turks,
thou art redeemed, but while thou art upon the earth, thou must not go out of Turkey,
nor have the chain off thee.
So say Satan`'s messengers, you are redeemed, but must carry a body of death about you,
and cannot go to your father Adam`'s house before he fell,
but you must live in your father Adam`'s house in the fall, while ye be upon earth.
But I say you are redeemed by Christ;
it cost him his blood to purchase man out of this state he is in, in the fall,
and bring him up to the state man was in before he fell; so Christ became a curse,
to bring man out of the curse, and bore the wrath, to bring man to the peace of God,
that he might come to the blessed state, and to Adam`'s state he was in before he fell;
and not only thither, but to a state in Christ that shall never fall.
And this is my testimony to you, and to all people upon the earth.
And so the teachers of the world cried, men are redeemed, but while on the earth,
they must have original sin in them, and that is the devil,
for he is the original of sin, and of the body of death, and that they are redeemed;
but they must never come to the state of their father Adam before he fell,
while on the earth.
This is sad tidings!
Are these messengers of God, or messengers of Satan?
So you may see by this where the shepherds have brought their flocks,
and in what they sit, in Adam and Eve in the fall; not in Adam and Eve before they fell,
a good, blessed state, but in Adam and Eve in the fall, a bad, cursed state,
and not in Christ that never fell.
Now mark, the apostle said, "`He hath quickened us, who were dead in sins and trespasses,
and hath made us to sit together in the heavenly places in Christ Jesus;
that in the ages to come he might show forth his
exceeding riches and kindness towards us.`"
Now the ages are come, glory to the Lord God over all, in the highest forever,
that this kindness and these riches are seen, that the apostle`'s preaching is fulfilled,
who said, "`He hath quickened us,
and made us to sit together in the heavenly places in Christ Jesus.`"
So mark, in Christ Jesus, us the church, us the saints,
us the believers and true christians, made us to sit together.
Here was their meeting,
here was their sitting in the heavenly places in Christ Jesus the second Adam,
the Lord from heaven, him that was glorified with the Father before the world began,
him that never fell, but fetched man and woman out of the fall,
to the state that man and woman were in before they fell;
and they not to sit there in Adam in the fall, nor in Adam before he fell,
but in heavenly places in Christ Jesus, before Adam fell.
And there is the safe sitting, in Christ the new and living way, the word of God,
the power of God, the light, the life, and truth, in the first, and in the last,
in the beginning, and in the ending,
in him in whom is no shadow of turnings nor variableness; in him the saints sit,
(the church,) in Christ the head,
and there are the exceeding riches and the kindness known again.
For are not here kindness and riches,
for man and woman to be brought out of that state in the fall,
to the state of Adam and Eve before they fell.
And he that doth bring them thither is Christ, and it is by his blood,
it cost him his blood, his life,
and he doth not leave them in the state that Adam and Eve were in before they fell,
but he sets them down in himself, who never fell,
a safer state than Adam was in before he fell.
Now who sit here in the heavenly places in Christ Jesus, the first and the last,
the beginning and ending, the safe place, in the wisdom of God.
1+++.+++ They see where Adam and Eve sat before they fell; blessed, and in a good state,
in the image of God, in righteousness and holiness.
2+++.+++ They see where Adam and Eve sat in the fall, with their sons and daughters,
fallen from righteousness and holiness, and the image of God, where they have no peace,
neither do they see God, nor have dominion over the creation.
3+++.+++ They see where the Jews sat, in the types, figures, and shadows, and temples,
and oaths, in the offerings and sacrifices,
and there were to sit till Christ the substance came to end them all;
which Christ the substance was before they were.
4+++.+++ They see where the apostles sat in the heavenly places in Christ Jesus,
the substance of all the types, figures, and shadows, who ended them all,
and was before them all, and will be when they are all gone.
5+++.+++ They see where the Gentiles sit, in the traditions, inventions, idols`' temple,
which God never commanded.
6+++.+++ They see where all the apostate christians have sat since the apostles`' days,
in the rudiments, inventions, handiworks, and traditions, and cannot sit long in them,
therefore turn one against another.
7+++.+++ Now the age is come that the kindness and riches of the Lord are seen,
which were manifest among the apostles and saints
who sat in the heavenly places in Christ Jesus,
where many sit now, in Christ the seed, the first, the last, the beginning,
and the ending; and who sit in him, as I said before,
see where all the apostatized christians have sat since the apostles`' days;
who have removed their seat from the apostles,
and have not sat in the seat the apostles and the saints sat in;
for had they sat in the heavenly places in Christ Jesus, him that destroyed the enmity,
the devil, and his works, they had all sat in unity and peace.
And they see where Jews sit, where Gentiles sit,
and where Adam and Eve sat before they fell, and where they sat in the fall,
with their sons and daughters, and where the apostles sat,
in the heavenly places in Christ Jesus.
They that sit in Christ, they sit in him the apostles sat in,
who is the first and the last, the beginning and the ending;
they see the top and corner-stone over all set,
in which the life flourisheth over all which was before the devil, the power of death,
and the power of darkness were;
which seed (Christ) bruiseth and destroyeth the serpent`'s head, the devil,
and his works; and in him (Christ) the saints sit,
in whom they have the pastures of life, that floweth over all, death,
and was before it was, and the power of it.
8+++.+++ So, as new-born babes desire the sincere milk of the word, that you may grow thereby,
(mark,) the milk that comes from the word which was in the beginning,
by that milk is the growth, and not in the traditions, handle not them,
nor the rudiments, nor the vain inventions of men neither, touch them not,
taste them not, for they perish with the using of them; so then they do not grow by them.
But they may say thou deniest the means, because thou dost not handle the doctrines,
the commandments, the rudiments that perish with the using.
Now that is not the means, but that is the means, the milk that comes from the word,
by which thou must grow, thy growth is not by that which perisheth; but, as I said,
by the milk that comes from the word, which was in the beginning,
before the false doctrines, traditions, rudiments of men, false churches, false ways,
false teachings, worship, and religion were; before all these were the word of God was;
thou dost not grow by any of those, if thou shouldst teach them all thy life-time,
and spend thy days, thou art never the nearer, neither dost thou grow by them,
nor by the tongues, which make their divines, the beginning of which was Babel,
which builds up, and throws down, as you may see:
did they not build up the church-faith and directory, and now throw them down again?
Here is Babylon; and were they not offended because you would not touch their ordinances,
and told you, you denied the means.
Now doth not the word of God live, abide, and endure forever, when they are all gone.
So feed upon the milk of the word,
that you may grow by that milk that comes from the word, that was before their tongues;
and when you are redeemed from the tongues, and see the beginning of tongues, Babel,
thou that seekest for the milk of the word,
thou must seek to be before Babel and Babylon was; for the word was before Babel was,
and stands when Babylon is down.
So the milk which cometh from the word,
is it by which thou must grow up in the things of God; and this keeps the eye pure,
and nourisheth thee up in the word of wisdom, word of life, word of patience,
by the milk that comes from it, up into the word of wisdom,
(for wisdom is with the gray hairs,) and so up into the life, up into a living,
abiding state; for the word liveth and abideth forever;
and by the milk that cometh from the word which was in the beginning,
before the fall of man was, with all the confusions, false ways, worships, churches;
the word was before they all were, and abides when they are all gone; feed of the word,
the milk of it,
and be quiet with the milk by which thou growest
and art nourished up to everlasting life,
by which thy fruits will be unto holiness, and the end everlasting life,
feeding upon the milk that comes from the word which was before unholiness was,
and stands and remains when all that is gone; by this you are all nourished,
by this you all grow in a living and abiding state, up into the word Christ,
whose "`name is called the word of God,`" in whom is the sitting down;
so heirs of Christ, and of salvation, inherit salvation,
and heirs of the power of an endless life, and heirs of a kingdom that hath no end,
and of a power of a world to come.
So know this to be your portion every one, that you may be heirs of the blessings,
and inherit them, that with them you may be clothed, meeting in the name,
in the strong tower, meeting in the spirit, in which you may pray unto and worship God,
and sing, which is the public worship of God,
which hath been lost since the apostles`' days,
by and amongst the inward raveners from the spirit of God,
which have been got up into particular worshipping and praying;
which if they come to the public, they must come to the spirit of God,
which their forefathers inwardly ravened from, and to the public praying in the spirit.
So dwell in the love of God, and build up yourselves in the most holy faith,
and keep the unity of the spirit in the bond of peace;
and worship God in the spirit and truth,
(which the devil is out of,) and in that meet in the truth, in the power of God,
which was before the devil was, in which is the perfect fellowship,
the gospel fellowship, which stands in the power of God, which was before the devil was,
or the fall of man either, where all imperfection was, and is,
which the power of God expels away, in which is the perfect fellowship, as I said before.
The worship of God is a perfect worship, it is in the truth, in the spirit;
so the truth is that the devil is out of, and all imperfection,
which truth was before imperfection was.
The worship in the truth never changeth, which is of the God of all truth,
who is a spirit; and this is the perfect standing worship,
which will stand when all the worships in the fall are gone, devil, dragon, beast,
and will-worship; for truth was before they all were; for they are not perfect,
being out of the truth, out of that which is perfect.
So all Friends, be faithful and valiant for the truth of God upon the earth.
For there are religions only for the summer, while the sun shines,
amongst the sons of Adam in the fall; but when the storm comes,
their flight is in the winter.
So this day manifesteth every birth of what sort it is, and at that look;
it is not professing God, nor Christ, nor the scriptures, nor the ordinances,
but mind the birth, he that is born of the flesh, and he that is born of the spirit,
together with each birth`'s fruits.
For he that is born of the spirit is the royal birth of God,
whose fruits are above him that is born of the flesh below,
not in righteousness and love, nor of the spirit; and so each birth hath its religion,
hath its worship, hath its praying, and its singing; but when the winter comes,
then is its flight, and then the wall-makers are discovered,
the hireling fleeth because he is a hireling; but ye, mind the power of God,
which was before winter storms were,
and such religions as are while the sun shines and the summer is;
but when the winter comes are gone.
Therefore mind ye the power of God, that ye may bear fruit in winter,
and sit under your vine, Christ Jesus,
that ye may see before winter storms and tempests were,
and to that which shall never have an end, nor change; in this is the pure religion.
And so in the name of the Lord being gathered, having bowed to it,
then ye are in the strong tower, in the deepest storms and tempest,
being in the name of the Lord, by whom all things were made; there is the strong tower,
then ye are safe in all waves, tempests, winds, hail, floods,
being in the name of the Lord, your strong tower.
And so feel the seed of God, (friends, and brethren,
and babes,) over all that set that makes to suffer, which was before that was,
and will stand and remain, when that is gone that makes to suffer,
that in that you may know Christ`'s reign, and the seed to reign,
in which there is life eternal, and therein ye will have life eternal;
and so feel the top-stone over all laid; and hearing the voice of Christ,
which is the light, the light`'s voice, the life`'s voice, the truth`'s voice,
the power of God`'s voice, which goes before you, through which ye may have life eternal,
in Christ`'s fold, where his sheep carry no body of sin upon their backs,
for that is carried in Satan`'s fold, which Christ`'s sheep are put out of,
in which life (Christ) did foresee the hirelings flying, when the wolf comes.
And so christendom have more minded the hireling`'s voice,
than Christ the light`'s voice, the truth`'s voice,
the voice of the life and power of God in themselves; they have gone from that,
and gone to the voice of the hireling, who flies when the wolf comes,
and leaves his flock, and cares not for it.
Therefore you that have heard the voice of Christ, who are his sheep, and follow him,
who hath put you forth, who goeth before you, and ye have followed him; follow him still,
and he will give you life eternal, for he is the rest;
and know the sitting down in the heavenly places in Christ Jesus, being heirs of grace,
which grace comes by Christ.
Now the grace of God that brings salvation, hath appeared unto all men;
which if all men minded, this is public, it would teach them to live righteously,
soberly, and godly, and to deny the contrary, and then come to be heirs of this grace,
and inherit it, and so inherit their teacher that bringeth salvation,
and so come to enjoy salvation, and inherit Christ, in whom are the light and life,
and in him is the sitting down in the salvation.

All keep to the beauty of holiness; for in holiness lies your beauty;
and the fruits of righteousness is a tree of life,
and the name of the Lord is a strong tower, and the righteous flee into it,
and are safe.

G+++.+++ F.

From Cockford in Essex the 12th day of the 11th month, 1662.

[.centered]
=== Letter 223.

All friends and brethren, stand fast in the power of the Lord God Almighty,
with the breast-plate of righteousness, with the shield of faith, your weapons,
by which you have victory, and have access to God, in which you please him,
and in which you have unity one with another; take unto you all your spiritual weapons,
and be ready with the sword of the spirit the word of God, which was in the beginning,
before death and the power of it was.
And all the false worships, churches, and teachers;
and that your feet be shod with the gospel, the power of God,
in which you have all fellowship,
(which is a mystery,) by which life and immortality are brought to light in you all;
every one having the word of God,
which hammereth down all that which is gotten up since the beginning;
and every one having the sword of the spirit, the word of God,
which doth divide the precious from the vile, in which you have wisdom,
which cuts down all that for the fire; which hath gotten up since the beginning,
who knows the earth in which dwells the righteousness, and dwell in righteousness,
and truth, and justice, and equity, for in that ye dwell with God;
and they that dwell not in this, dwell not with him, but are such as grieve, and vex,
and quench God`'s spirit in them.
Be bold and valiant for the truth upon the earth, every one according to your measure,
beholding the face of God.
And fear not the power of the devil, but in the power of God, which was before he was,
tread on his head; and know the honour of the saints,
and the election in Christ the seed, which was before the world began,
and your salvation wrought out, and the glory of the Lord to be your reward.
And keep your faith in the power of God, in which you may all know your health grow,
and all your hearts to be established in grace, which is your teacher,
and brings your salvation, that all may see it is the grace of God, by which you stand,
which establisheth, seasoneth, teacheth, and bringeth salvation.
Heed not the earth, nor the rudiments of the world, nor the swine, nor dog`'s vomit,
nor men`'s carnal understandings, wisdom, nor knowledge; but mind the wisdom of God,
that is pure from above, and keeps so; and the spirit that gives the true understanding,
and the right knowledge of God, which is life eternal.
And know your fellowship to be in the spirit, which is the bond of peace, in that live,
and keep in it, in which you may have perfection, and the perfect gifts of God.
And mind the worship of God, which is in the spirit and truth,
which was before the devil was, which he is out of, and his ways.
For God`'s ways are in the truth; and in his power meet, and in his life live,
in which you may feed in the pastures of life,
in which pasture Christ is the leader and shepherd.
So all that be plucked out of the fall by his crook, which is the power of God,
and that know him and his voice; follow him, and ye will have life abundantly,
and riches eternal.
And every one keep on your watch and guard, against the enemy that led out from God,
out of life and truth.
For all the sufferings are by and through him that is out of the truth;
so they that will live godly shall suffer persecution; but you that suffer in the truth,
and by the contrary for the truth`'s sake, the spirit of glory will rest upon you;
and if you be evil spoken of for its sake, being faithful on your parts,
Christ is glorified.

And, friends, your house being built upon the rock Christ Jesus,
by whom the world was made, the storms, the floods, the tempests you fear not;
but all whose house is built on the sands, the floods, the storms,
beat down and wash away, as you may see before your eyes.
So Friends that are come to the beginning, see over storms, and tempests, and floods,
and live on the rock, which was before they were; on that you may rest safe,
and in peace.
And, friends, "`Fear not him that can kill the body,`" I say,
fear him not that can spoil thy goods, be not afraid of them;
for when they have done that, they can do no more; for the life is over them all,
they cannot touch that.
So mind that which is over them all.

G+++.+++ F.

[.centered]
=== Letter 224.

Dear friends, whom death, bonds,
nor the outward creatures can separate from the love of God in Christ Jesus,
live in peace and love one with another, and keep above that straitened spirit of strife,
which is below, and out of the power, and truth, and life of God.
Dwell in dominion, in love, in life, and in unity one with another, in the power of God,
which was before the power of darkness was, and in the seed of God,
which was before enmity was, and that you may all know Christ`'s reign.
And feed in the pastures of life: and none stain your virginity nor holiness,
where lieth your beauty.
And all that minister abroad, walk as examples to them you minister to.
And keep in peace, that you may not destroy them that you do minister to.
So live in the fear of God, and spread the truth abroad, and set the truth over all,
and in it live; in which you will have unity.
So my love is in the seed of God, which is immortal, to you all.

G+++.+++ F.

[.centered]
=== Letter 225.

[.salutation]
Friends,

Keep in the power of the Lord, which will bring you over all, to the fine linen,
the righteousness of the saints, and your bread of life;
and the same power of the Lord will bring all your persecutors to rags and poverty.
When they have done their work they will have their wages;
when the righteous and wicked have done their work, each shall have their wages; and so,
do not think the time long.
For each must have their day to do their work in; when the wicked`'s sun is gone down,
their day is ended; and then they are reckoned withal, and paid,
and then the people of God`'s day approaches,
wherein according to their works they shall have the rewards of life eternal.

P+++.+++ S.

The power of God is over all, and they that keep in it, it will carry them over all.

G+++.+++ F.

[.centered]
=== Letter 226.

My dear friends,

In the everlasting seed and covenant of life, be valiant for the truth upon the earth,
and dwell in the power of the Lord God, and never heed that which makes to suffer,
but the power of the Lord, which was before it was; and all live in that,
and spread the truth abroad; and every one improve your Lord and master`'s money,
your talent, to the advantage of your Lord.
And be of good faith, and valiant for the truth.
You who are gathered in the name of Jesus, keep your meetings in his name,
over all the meetings which are gathered by the sons of Adam in the fall;
and look over all prisons and outward bonds, which are in time, and will have an end;
at the power of God look, which hath no end, in which your life is, and peace, crown,
and dominion,
and think not the time long that the rod of the wicked should lie on your backs;
but rejoice in tribulations and persecutions, which are for the trial of your faith,
that it may be found more precious than gold that perisheth.
For remember that Christ the word, was tried, and Christ is the tried stone,
and all the prophets, apostles,
and martyrs were tried for their testimony to the precious pearl, seed, and truth;
and what sufferings they had in all ages were for the same, by the dark world,
which was not worthy of them; who were as pilgrims and strangers in the earth,
and many of them forsook their native land and country.
And so live in that which glorifieth the Lord, you who know the kindness, love,
and mercies of God, and are made partakers of the heavenly riches,
and of the inheritance that never fadeth away,
and are heirs of the kingdom that never hath an end,
and are partakers of the promises and blessings, that were before the curse was;
and know the new covenant made manifest in your hearts, and the law of God there written,
and the anointing within you to teach you, and then you need no man to teach you,
but as it doth teach you.
So abide in him, and learn of him in whom God is well pleased;
and none turn to them whom God is not well pleased with.
For you who are children of God, are not to look for salvation from the hills,
neither to look at the arm of flesh, nor to put confidence in man,
who are redeemed from under the curse, and the fear of man, and are bought with a price,
the blood of Jesus Christ; and so are not your own, and cannot do your own wills,
nor other men`'s, but are to glorify your Father which is in heaven.
And so dwell in the love of God together, and in peace, and unity,
and fellowship in the seed and life.
For there is your growth, and therein ye grow in grace and faith together.
The Lord God Almighty preserve you all in his everlasting arm and hand,
which is his power, over all to his glory, bearing one with another in the gentle wisdom,
which is peaceable and from above.
For how joyful a thing it is, for brethren to dwell together in unity;
and hereby it is known, that "`you are the disciples of Christ,
if you love one another;`" and a mark,
that "`you are passed from death to life,`" if you love one another.
And so the Lord God preserve your minds, and souls, and hearts,
all holy and pure to his glory; and all live and sit down in Christ the seed,
who is the faithful witness, the amen, the first and last, the beginning and ending.
No more, but my love is to you all, in the everlasting seed, Christ Jesus,
that never fell.

G+++.+++ F.

And dear Friends keep low, for there is no danger.

[.centered]
=== Letter 227.

Sing and rejoice, ye children of the day and of the light;
for the Lord is at work in this thick night of darkness that may be felt.
And truth doth flourish as the rose, and the lilies do grow among the thorns,
and the plants atop of the hills, and upon them the lambs do skip and play.
And never heed the tempests nor the storms, floods nor rains,
for the seed Christ is over all, and doth reign.
And so be of good faith and valiant for the truth: for the truth can live in the jails.
And fear not the loss of the fleece, for it will grow again; and follow the lamb,
if it be under the beast`'s horns, or under the beast`'s heels;
for the lamb shall have the victory over them all.
And so all live in the seed Christ, your way, that never fell;
and you do see over all the ways of Adam`'s and Eve`'s sons and daughters in the fall.
And in the seed Christ, your way, you have life and peace;
and there you do see over all the ways of Adam in the fall, in which there is no peace.
So in the seed Christ stand and dwell, in whom you have life and peace;
the life that was with the Father before the world began.

G+++.+++ F.

The 9th month, 1663.

[.centered]
=== Letter 228.

Dear friends, who have tasted of that which is precious,
and have felt the truth convincing of you; and also felt the power of the Lord God:
I feel something amongst some of you that is not right;
and how that such get up into the wise part, but are out of the power,
and out of the life, and with that judge, and are beholding the moats in others eyes,
whilst the beam is in their own eyes.
Oh! abuse not the power, in which is the gospel fellowship, which will keep all in unity,
and grieve not the spirit, in which is the true fellowship, and the bond of peace.
Keep down high-mindedness, despise not prophecies,
and quench not the spirit in the least;
for that is flesh and not spirit in yourselves that doth so.
Judge not before the time that the Lord do come,
who brings to light all the hidden things of darkness in you;
run not into outward things, that is the fleshly mind, that will run from one thing,
and so be restless, and will not know what seat to sit in;
after it hath been in one outward thing it will run into another, and call it,
his growth in the truth, and fall a judging others; but that judgment is after the flesh,
and their growth is in the flesh; for the fruits of it is strife, backbitings,
whisperings, and leads to idleness, busy-bodies from house to house, slandering,
scandalizing, vilifying, and are in lightness, out of the fear of God,
in variance and sowing dissention, and these are the seedsmen of the flesh,
and not of the spirit; and so feed one another with that which burdens the seed,
and quenches the spirit, and destroys the love and unity, which love you should grow in.
So the fruits of every birth manifesteth itself; the fruits of the spirit are love,
and peace, and truth, and plainness, and righteousness, and godliness.
But the fruits of the flesh are backbitings, whisperings, lyings, slanderings,
scandalizings.
And therefore mind what this birth hath brought forth,
(and shame it,) that hath cried up outward things, and what it hath run into,
and what it hath drawn you into, that are in it, and what it hath rent you from,
and whether you are not come to a loss, and, whether you are not gone into the flesh,
and into the air, and lost your first habitations of tenderness and compassion;
for every birth knows its own, and is grieved when its own is judged,
and that will never love plain dealing and righteous judgment, which are honest and true;
but will have the false prophet`'s cushion and pillow;
and can neither endure sound doctrine nor judgment.
And therefore mind your first habitation and first love, and that which did convince you,
that you may all come into life and power, to sit down in the habitation of it, in love,
and life, and unity, and let there not be a backbiter nor slanderous tongue, nor liar,
nor whisperer, reproacher, nor a busy-body found amongst you; for if there be,
it will leaven one another, and bring darkness and death upon you.

Therefore, as I said before, dwell in the power of God, in which you may keep unity,
life, love, and peace;
and in which power of God you may be drawn up out of Satan`'s power,
into the power of God, in which is my life, and in it is my habitation and dwelling,
where I know the unspotted garment hid from all the unclean beasts`' tongues, lips,
hands, and eyes; and blessed are all you that keep in the power,
and have kept your first habitation; for you grow up as calves in the stall;
and such gad not abroad to change their ways;
for the birth of the flesh would have some outward thing to feed upon,
but the birth of the spirit reigns over it, farewell.

G+++.+++ F.

Lancaster prison the 6th day.

[.centered]
=== Letter 229.

[.salutation]
Friends,

Let not your knowledge be after the flesh, but in the spirit.
Let not your fellowship be in the flesh, but let it be in the spirit, and in the gospel.
Let not your affections be in the flesh, and on things below,
but let them be set on things that are above, and on things that are heavenly,
above the things below.
Let not your souls be subject to the lower power of darkness, which is out of the truth,
lest you bring destruction upon your own selves;
but let your souls be subject to the higher power,
that is above the lower power of darkness.
Let your acquaintance and familiarity be in the spirit,
over that which would ensnare or entangle you, and bring you into bondage.
Let all your minds be heavenly, and not earthly.
Let all your minds be spiritual, and kept above all that which is carnal;
then they are kept out of death, in life, and in peace.
For the invisible is above all the visible, and the immortal is above the mortal,
and the eternal is above the external, and the incorruptible is above the corruptible.
As life is above death, and truth is above error and falsehood,
and light is above darkness, and righteousness is above unrighteousness,
so the godly are above the ungodly, and the holy above the profane,
the just are above the unjust, and the true prophets,
and the true ministers or preachers, and apostles,
and the true disciples are above all the false.
And the true Christ is above all the antichrists, and God is above the devil,
and virtue is above vice,
and the true worship in the spirit and in the truth is above the false,
which is out of the spirit and the truth,
and the true belief and faith and hope are above the false belief, which is unbelief,
and the living faith is above the dead faith, and the hope that is the anchor,
both sure and steadfast, anchors the soul in the great sea, the world,
when the leviathan maketh a storm, among the tongues, peoples, nations, and languages,
which are as waters; then the true hope standeth and stayeth, and is sure and steadfast,
and keeps the soul up to God, atop of the sea,
when the false hope of the hypocrite sinks therein, which are the waters,
and it goes over them, and in it they are swallowed up.
The unity in the spirit is the bond of the Prince of princes`' peace,
and the fellowship in the gospel, and the liberty in it is a perfect one,
above the imperfect, where is bondage.

G+++.+++ F.

[.centered]
=== Letter 230.

[.salutation]
Friends,

Stand still and see, be still and hear, sit at Jesus`' feet, and choose the better thing;
to do the work of God is to believe in his son Jesus Christ the light;
and your hope and faith are to stand in God, and in his son,
walk by that faith which he is the author of, and walk in the light,
and walk in the spirit.
As every one hath received Christ, so walk in him, and so serve God in the spirit,
and worship him in the spirit and in the truth;
for God is not worshipped out of the spirit and truth.
The babes`' milk is from the word, and their bread is from above,
and there is no true religion but what is pure from above; and the stayed,
patient people abide in their own house, but the whore is gadding abroad;
and there is no true church but where Christ exercises his offices in and amongst them,
and they are asking their husband at home, and he is their head,
and the true marriage to Christ the heavenly man
is witnessed by such as are flesh of his flesh,
and bone of his bone;
none come to be children of the light but such as believe in the light; no sons of God,
but by receiving Christ, and by being led by his spirit; no coming into all truth,
but by being led by the spirit of truth;
no running the true race in the straight way to get to the glorious crown,
but with patience; no purifying, but by coming to Christ, the hope of glory,
the purifier; and no overcoming, but by believing in Christ the light,
and he that doth so is born of God.
And there is no true witness within but the light, the life, and spirit of Christ,
the true record; no true faith but that which Christ is the author of,
which giveth victory; no true anchor to the immortal soul but by Christ,
the hope of glory.
So by hope you are saved; no true liberty but in Christ,
and in his law of the spirit of life, and in his gospel; no true knowledge of God,
but by his light and spirit in the heart; no salvation, but by the name of Jesus;
no true praying, but in the spirit; no true singing, but in the spirit; no true fast,
but that which breaks the bond of iniquity; no true fellowship, but in the pure faith,
light, spirit, and gospel of God and Christ; no true foundation, but Christ,
to build upon; no true way, but Christ; no true seed,
but what Christ hath sown in the heart; no true rest, but in Christ; no true peace,
but in Christ; no true service to God and Christ, but in the newness of life;
no knowing the things of God, but by the spirit of God;
no knowing the son nor the Father, but by the revelation of the holy spirit;
no knowing the scriptures,
but by the same holy ghost that moved the holy men to give them forth; no calling Jesus,
Lord, but by the holy ghost, by which he was conceived; no grafting into Christ,
but by believing in the light, which is called the light in men, and the life in him;
no true wisdom, but from above; and no true receiving it, but in the fear of the Lord;
and no true understanding of spiritual things, but what Christ gives; no divine reason,
but in the faith that Christ is the author of,
which giveth victory over that which is unreasonable, and separates from God;
and no true love to God, but what he sheddeth abroad in the heart;
and to know a fellowship with Christ in his death and sufferings,
is above the fellowship of bread and wine, which will have an end;
but the fellowship in the gospel and holy spirit hath no end.

G+++.+++ F.

[.centered]
=== Letter 231.

My dear friends,

Be faithful to the Lord God every one, in the truth and power of God,
and his righteousness, that it may flow over all, and walk and live in it,
that to the Lord God you may be a good savour; and a blessing in your generation.
Look over all sufferings, and that which makes you to suffer.
Dwell in the rock, which is above all storms and tempests;
for now is the trial of your faith, now is the trial of your meetings,
(who are gathered in the name of Jesus,) by them
that are gathered in the name of Adam in the fall;
now is the trial of your worship, which is in the spirit and truth,
by such as worship out of the spirit and truth.
And now is the trial of your fellowship in the gospel, the power of God,
by such whose fellowship lies in outward things; now is the trial of your church,
which is in God, by those that have their church in the fall, unsanctified;
and now is the trial of your faith, and your gospel fellowship in it, which is a mystery,
and Christ the second Adam is a mystery to fallen Adam,
and truth is a mystery to all them that are out of it,
and the light is a mystery to all the builders and stumblers at it, and haters of it;
and godliness is a mystery to all the ungodly.
Therefore may you praise the Lord, and bless his name,
who hath revealed these mysteries to you in the day of trial,
by which you may withstand the day of darkness, and the hour of it.
For those that have oil in their lamps enter in with the bridegroom,
who have heard his voice at midnight.
And so happy and blessed are all you that have laid up in store against this day,
and the time that is now come, whose bread fails not, nor water,
and have found the landmark of your everlasting portion and inheritance in the kingdom,
where nothing that defiles can enter.
And therefore be valiant for the truth upon the earth, and fear no amazement,
but fear the Lord, who upholds all things by his word and power,
in whom is all your fresh springs of life.
Live and walk in the second Adam, the Lord from heaven;
and all keep out of Adam in the fall, that is earthly,
that you may sit down in the heavenly places in Christ Jesus, that never fell,
who is your life, who is your peace and salvation, who redeems you from the earth,
that you may reign upon the earth, who makes you kings and priests to God;
and blessed be the Lord forever, who reigns, and lives,
and rules amongst his flocks and assemblies, gardens, plants, vineyards, babes, children,
sons and daughters, servants and prophets, watering them with the water of life,
giving the increase of life to them; glory and praise be to his name forever.
And God accepts you in his son, the second Adam, the seed Christ Jesus, who reigns.
But God is displeased with people as they are in Adam in the fall,
as they are out of Christ.
And so in him be faithful, who is your crown, let no man take your crown from you.
Yea, I say,
be faithful to him who was the "`Lamb slain from the foundation
of the world,`" who reigns and sits down at the right hand of God,
till all his enemies be made his footstool;
he who was glorified with the Father before the world began, sit down in him,
the amen and faithful witness.

G+++.+++ F.

Let this go among Friends, and dwell in peace and love, forbearing one another,
and so full the law of Christ.

From Lancaster Castle, the 1st month, 1664.

[.centered]
=== Letter 232.

[.blurb]
==== Two General Epistles to be read in all the congregations of the righteous, who are gathered out of the house of Adam in the fall, into the house of Christ that never fell, to be read amongst them.

All Friends everywhere, who are gathered in the name of Jesus Christ,
that never fell nor changed, yea,
into him that never fell being gathered ye will see
over all the gatherings of Adam and Eve in the fall,
from the garden of God, and the blessed state, and from the image of God,
and the righteousness, and the holiness that he was in before he fell;
wherein all is in the confusion in the fall.
The sons and daughters of Adam are broken into the many gatherings,
being in the fall from righteousness and holiness, and the image of God,
and the blessed state that they were in before they fell;
and so are from the witness of God, the spirit and the light in their own particulars.
And so as Jacob`'s prophecy was on his deathbed to his sons,
how that the gathering of all nations should be unto Shiloh, unto Christ Jesus,
(mark,) to Christ Jesus that never fell, who was with the Father before the world began,
in whom is the light, life, and peace, and rest in this gathering,
and so the gathering is out of Adam in the fall, up into Christ, that never fell,
and in him are safety and peace; and in this gathering you have every one a river, yea,
of living water, in your own bellies, which river comes from the fountain;
for all nations are blessed in him,
Christ Jesus that takes away the curse that stood over all nations,
and destroys the devil the author of it; and spreads over the blessing again,
and all are blessed in him, and therefore, bless and curse not.
And all they that are saved walk in the light of the Lamb, and so come to the holy city,
that comes down from God out of heaven, into which there is no unclean thing enters;
in which city there is no need of the sun nor moon,
the Lord God and the Lamb is the light thereof.
Of this city, which fences out all bad, and unclean, and unrighteous, and the adulterer,
and idolater, and the liar; and the power of the Lord God goes over all the bad;
and they that come into this city are saved,
(as I said before,) and walk in the light of the Lamb.
And therefore, friends, all know the blessed truth, which the devil is out of,
which truth makes you blessed, through which you come every one to have a crown,
and so to feed upon the tree of life, through which you come to live forever;
the leaves of which heal the wounded nations.
So you that have bought the truth, sell it not for trifles, neither give it nor leave it;
for that which the tempter will tempt you unto is out of the truth, to outward things;
but consider all the faithful all along how they suffered, and by whom, and for what,
in all ages since the fall, from the foundation of the world,
since the Lamb hath been slain;
not joining to men in any thing which the sons of Adam have invented and set up,
the sons of God nor the faithful could not join to.
They followed the Lord, his counsel, and his word and promises,
and went through the great tribulations to the rest,
as pilgrims and strangers to all the sons of Adam`'s evil ways, religions, and worships;
them that were in the worship of God, and in the way of God,
Christ Jesus that never fell, saw over them all.

And take heed of the rough garments, and rough spirit of Esau`'s rough nature,
but mind the plain Jacob, that supplants rough Esau; and mind the constant truth,
and take heed of the inconstant, and such as are given to changing,
which the son gives not himself unto, for he ends the changings,
the son Christ doth that never changes, and as every one hath received him,
so walk in him that never changes; walk not in the traditions of the Jews that changed,
nor the Gentiles, nor the apostate christians, but in him (as I said before,
Christ Jesus,) that never changed, and the way, that never fell, nor never changed,
nor never will change; and then you will see over all the ways of the priests,
the shepherds, the prophets,
and the teachers of Adam and Eve`'s sons and daughters in the fall, that do change,
and do fall and stumble, and are turned by every wind,
you being in Christ Jesus that never fell nor never changed, in whom you have life,
and peace, and rest.
For to preach Christ the way, the prophet, priest, and shepherd, that never fell,
and people to receive him, they come out of all them that do fall, both prophets,
and shepherds, and priests`' ways; and this is opposite to them all,
in which they took counsel against them that preached Christ the word,
which was in the beginning before the Jews`' ways and traditions were, or the Gentiles`',
or the apostate christians`', and he will be when they are gone.
So to preach Christ, is not to preach up the Jews`' traditions, nor the Gentiles`',
nor the apostate christians`', nor to follow the traditions of their forefathers,
but to follow the word; neither receive them, nor them that preach them,
and to follow that which lives, and endures, and remains forever.
And this is the word that makes the Jews to grieve, and the Gentiles,
and the apostate christians, to preach the word which was before their traditions were,
and their inventions; and this is the word which makes wise men and wise women;
and the word is the seed, which seed is sown in the field, and the field is the world,
and there is stony, thorny, and highway ground, and good ground;
and so this is universal doctrine, the universal seed hits the stony, thorny,
and highway ground, and falls upon all,
only it is the good ground that brings forth fifty, sixty, or a hundred fold increase.
And such as are the highway ground, they are so full of the fowls, and of the air,
that it takes it away; and such as are sown among thorns,
they are so full of the cares of the world, and the deceitfulness of richness,
that the thorns choke it, and the cares of the world;
they are such stony hearts that the seed hath not much earth,
that when trials and persecutions come with their heats,
it is scorched by the heat of the sun.
And therefore be ye all warned of these natures, both of the stony, and of the thorny,
and of the highway ground, and of the fowls, and of the air.

And, friends, keep down feigned flattery.
Keep in the truth, that brings to plain-heartedness, that all may be the good ground,
that you may abound in goodness, and righteousness, and holiness,
for peace is sown to the righteous, and gladness to the upright in heart;
and see that you walk in the light, and the life, that it may be your life,
that you may have treasure in your vessels, that you may enter in with the bridegroom,
having the oil in your own lamps, that you may inherit the life,
that is above all the foolish talkers which be out of the peace,
(the second Adam,) in whom the peace is, and the life;
for they that be in strife about the body of Christ, are in Adam in the fall,
and they are neither at peace in themselves with God, nor Christ,
nor them that are in Christ; so whatever men or people profess, their end manifests them,
and crowns them with death or life.

So, live in the word, which all ends in the seed; this,
keeps over all pretences in the substance,
and over the airy spirits that are out of the life,
running up and down sowing dissention, tattling, and backbiting, and whispering,
and setting one against another.

The seed Christ is over that spirit, and he hath little room in their hearts,
for they are abroad in the fields, lifting up themselves higher than the world,
but are worse to deceive the simple.
But truth, and the light, and the life is over all that,
in which all keep your habitation; for Adam lost his habitation,
and so his sons and daughters, who are in the disobedience, are in the fall;
and the Jews lost their habitation from the love of God,
and so they lost their authority, and were mingled among the heathen.
And the apostate christians lost their habitation
from the life and power that the apostles were in.
And so have brought all christendom into heaps and sects about outward things,
being out of the life and word,
which was in the beginning before the apostacy and the fall were.
So live in the word, in that you have life, and dominion,
and authority over all that which Adam and Eve`'s sons and daughters invented;
and also over all in the fall.
In which word you have wisdom, as I said before, and there is a faithful witness, Christ,
whose name is called the word, and he is the first and the last,
the beginning and the ending, the amen.

And, friends, keep over all the bustlings, and wars, and strife,
and the talkers of such things among the sons of Adam in the fall;
you that be in Christ Jesus that never fell, in whom is the peace,
who makes the first Adam`'s sons and daughters to break their swords into ploughshares,
and their spears into pruning hooks, that they shall not learn war any more;
for they that be there, are in the foolish state,
but they that are in Christ are in the wise state, and have spiritual weapons,
though accounted by the world foolish; yea,
the wisdom of God is so to the wisdom of the world, which is foolishness.
And so you that the Lord hath blessed in outward things for his truth,
keep over them and out of them, serving the Lord who hath blessed you,
lest you be entangled.
So keep above them in the righteous life and conversation,
that righteousness may flow to all men in all things; honesty and truth,
and that which doth justice, and doing justly, that may flourish;
for whose conversation is ordered aright, they shall see the salvation of God;
keep out of all heats and passions, and over the tempestuous spirits,
the ground of which is uncleanness, all which are up and down, and sudden;
which makes a mountain of wickedness and unholiness; and keeps out of the holy mountain,
which they that walk in the light of the Lord go to, and they are taught his ways.

Take heed of a false liberty in any thing to the flesh,
but keep your first love and habitation in the power and truth of God;
for the lowly mind, the humble, and meek, and broken,
and contrite spirit and heart the Lord doth not despise, but exalt.

Keep out of the many words of the world, and take, heed of a liberty of going into them,
but keep in the power of the Lord God; over all, which was before all, and is over all,
that your lives and conversations may preach to all men, and adorn the truth of God,
and speak in the hearts of all men.

Forsake not the assembling of yourselves together as the
manner of some was in the beginning of the apostasy,
which entered into the reasoning part, and so went from the exhorting daily,
and the building, and the fellowship, and the communion of the saints in the spirit,
and from the flocks, and the garden of God, which he waters with his water of life, and,
feeds with his bread of life; and sets open his broad rivers of living water to drink.
And such as forsake the assemblies of the righteous;
some for fear of the earth and sufferings, become quarrelling spirits,
and so go out of the path of the flock`'s footsteps,
and sit not down with the flock at noon-day, in the heavenly places in Christ Jesus;
for there the flocks meet, and there they have all a fountain,
through which they are all of one soul, and mind, and judgment, and heart, and spirit,
and come to be gathered out of all the separations, and sects, and fellowships,
and gatherings, and meetings of Adam and Eve in the fall,
and sit down in Christ Jesus that never fell, where the fulness is and the life;
in whom there is no shadow, no variableness, nor turning, in him that is the way.
But, Oh! the poverty, the shadows, the variableness, the turnings, the worships,
and traditions, and the sects that are in the world among the sons of Adam in the fall!
Oh! the riches that are in him that never fell,
the peace and the life that was with the Father before the world began, the amen.

And, friends, take heed of the vain inventions and arts of the world,
keep out of their rhymes and their verses,
for they are the arts of men and stir up the light part,
and lift up that that pertains to itself,
that is stirred up that will turn in the end to the strife, or the earth.
But you that live in the word of God that never fell, changes, nor alters do not,
but as you are moved by it, and that will stand and remain;
it whom you may know a dwelling, life over death, and before it was;
for the serpent that got into Adam and Eve by disobedience,
they had dominion over all things that God had made; yea, over the serpent:
and he came and told her, "`they should be as gods,
if they would eat of the fruit that was forbidden;`"
and they thought to have been as gods,
and to be made wise; but the, devil came to be god, and they came to be slaves.
And so he got into Adam`'s heart, and Eve`'s heart, through their disobedience,
through which they lost their dominion, and the serpent came to be god of the world,
the deceiver.
Now saith the Lord to the serpent, "`Upon thy belly shalt thou go,
and dust shall be thy meat all the days of thy life.`"
So you may see how the serpent got into Adam and Eve by disobedience.

Secondly.
He ruleth in all Adam`'s sons`' and daughters`' hearts that are disobedient to the light,
the truth, the power of God in themselves, and he darkens their hearts and minds,
and makes them envious; and from him they have their devilish earthly wisdom,
and all their invented arts and ways that are bad, that keep up,
and stir up the fallen nature that is sometimes puffed up, and sometimes down,
through which the earth is brought out of its course, and the bonds of civility broken.
So here he that rules in the disobedient,
and got into Adam and Eve`'s heart by disobedience, which is called the god of the world,
whose meat is dust, goes upon his belly: now if this ruler,
and this governor of the hearts of such as are disobedient,
who is called the prince of the air, and so whirls them up into the air,
who got into Adam and Eve`'s heart by disobedience,
and rules in his sons`' and daughters`' hearts by disobedience,
if he goes upon his belly, how go they that he rules?
Better than the ruler, think you?
Must the ruled go better than the ruler?

Thirdly.
If this ruler`'s meat be dust, that rules in the hearts of the disobedient,
which got into Adam and Eve`'s heart by disobedience, what feed the ruled upon then,
if the ruler`'s meat be dust?
for, can any feed upon life, but they that come to the light, and life,
and truth in their own hearts;
by which truth they come to see how he got in by disobedience;
and how he rules the disobedient.
Now, do you think that the devil would have any man or woman,
or his messengers or apostles, to obey the truth and light in themselves?
then how can he rule in their hearts, unless they went out of the truth?
The devil, the serpent, got into their hearts by disobedience, and rules the disobedient;
and therefore it is not like that the devil, or his messengers, or prophets, or apostles,
would have any man or woman to obey the light, the truth in their own hearts; for,
if they obey the light, the truth, which the devil is out of, and abide just;
by this they come to go upright, from under the slavery of him which upon his belly goes;
they come to feed upon the life, Christ,
which was with the Father before the world began; not upon the dust, which he feeds upon,
which is out of the truth; and they that he rules, are out of the truth.
So it is no strange thing for him and his messengers
to speak against the light in the heart,
for he hath made the world like a wilderness, all wild and rough;
he that got in by disobedience, and rules in the disobedient,
it is not like that he would have people to obey the light nor life within them;
he that is out of truth, who got into Adam and Eve by disobedience,
rules in all them that are disobedient, going roaring up and down,
seeking whom he may devour.
And so Adam came to be lost, and the Lamb came to be slain,
from the foundation of the world; and therefore comes Christ, the first and the last,
to destroy the devil and his works in men`'s hearts, and sanctifies them by his blood,
his life, which was the sacrifice for the sins of the whole world,
and destroys the devil and his works, through death;
and him that hath the power of death, and sanctifies and washes men and women,
and presents them back again to God perfect.
But the devil would not have men and women to own perfection,
who hath made them imperfect, nor his messengers;
but it is Christ that destroys him and his works, and saith,
"`Be perfect,`" and presents men and women perfect to God out of the fall,
up to Adam before he fell; and not only there, but up to himself that never fell,
the royal seed.
And in him keep your meetings, and dwell in peace and love,
that the fruits of the spirit may abound among you;
for the fruits of the flesh are in the fall, where the spirit is grieved;
for there they be out of the quietness, and out of the rest and peace.
Therefore in Christ, that never fell, the peace, and rest, and light, and life,
and the power and truth, live; and God is well pleased, and doth accept you in his son,
Christ Jesus; in the seed, in the light, in the truth, in the power of God,
in the righteousness, and in the wisdom; but God doth not accept them nor you,
as they and you be in Adam in the fall, in their own righteousness, in their own wisdom,
out of the light, out of the truth, out of the life, and not living in it in themselves.
And so God doth accept you in Christ the second Adam, that never fell,
and is well pleased with you in Christ the second Adam,
that righteousness which was before Adam was, is in Christ that never fell,
as you come out of Adam in the fall, and live in Christ Jesus that never fell.
And so Christ comes to be manifest in people`'s hearts, and the son to be revealed,
who casts out the strong man, which hath kept the house, and spoils his goods,
who got into Adam and Eve by disobedience,
and rules in the hearts of Adam and Eve`'s sons and daughters, Who are in disobedience.
And so Christ the second Adam must rule in people`'s hearts, who are in the obedience,
as he doth in all that have power, and enjoy life.

And so be valiant and faithful for the truth upon the earth,
serving the Lord in a new life, that is in Christ Jesus that never fell,
out of the old life of Adam in the fall; for the old life is in Adam in the fall,
where the spirit is grieved; and the new life is in Adam that never fell,
who was born in Bethlehem.
Beth is a house, and lathem is bread, where the fulness is,
who will dry up the river Euphrates with its froth,
which hath run so up and down among the sons of Adam;
that people may drink at him the fountain, the water of life,
through whom you come to know the mighty God of heaven and earth,
the upholder of all things, and creator of all things, to his glory and honour,
being in Christ Jesus, by whom were all things, who is the top and corner-stone,
in whom you all have life; in him live: and so farewell;
that you may have the blessings of the Lord come upon you.

And, dear friends, keep your hands, tongues, feet, bodies, and hearts clean and open,
out of all pollutions and uncleanness;
for blessed are all you whose feet are guided in the way of peace,
which is in the way of righteousness, through which the immortal life is lived in.
And light words and jesting all avoid, and fables, and foolish talk;
but live in the power of the Lord that is over all,
through which you follow godliness and holiness,
without which none shall see the Lord God.

And blessed be God the Father, who hath set Christ over all,
who is the first and the last, the beginning and the end,
God`'s faithful and true witness, the amen; in him have you the book opened,
and in him you see all things unsealed, in him manifest in you, who is your life,
who was with the Father before the world began, the amen.

For in this night of apostacy from the spirit and power that the apostles were in,
hath all things been sealed up, and no man could open; but now is the lamb come again,
that opens the sealed book.
And all Friends, keep out of all the vain fashions of the world,
and over that unchaste spirit that invents new fashions daily, both in apparel and diet.
Therefore keep chaste in the power of God over them all,
that your lives and conversations may judge them in such things,
who devour those things upon their lusts, which God hath given to the service of man.

G+++.+++ F.
