== Letters 246 &#8212; 253

[.centered]
=== Letter 246.

O dear friends! mind every one your habitation in the power of the Lord God,
that first convinced you, and keep your possession in it,
in the sense of God`'s love and mercy to your souls;
for your unity and fellowship lie in the spotless power, truth,
and life of the everlasting God of life and power;
and herein to you the springs of life will be opened,
through which you may be daily refreshed up to the God of life.
Oh! be tender of the spotless truth and life,
through which you may come to answer it in all Friends,
that they may have unity with you in the same life and power,
through which you may be a good savour to God, and a blessing to him in your generations,
serving the Lord God in the newness of life, as a chaste spouse and bride to him,
in body, soul, and spirit, having an esteem of your bodies, which are for the Lord,
and to be his temple, not for adultery or fornication, nor idolatry.
Oh! therefore mind and keep in the holy life,
and feel the moving and counselling power and spirit of the Almighty in you,
directing you into the ways of truth and righteousness, peace and holiness,
without which none shall see God.
Live in the peaceable life, and love it; eye that which makes for peace,
for God is the author of peace, and not of confusion.
So live all in the precious truth of God, feeling it in its operation;
through which unity and the peaceable life may be
preserved amongst you in righteousness and peace;
for wars, and strifes, and troubles, and fightings, come by unrighteous actions,
which are below truth and righteousness; for truth leads into the modest, decent,
and comely life, which is honourable and estimable to God,
and in the hearts of all his people.
So live in the truth and the power of it,
that you may all come to be heirs of the power of an endless life,
and to inherit and possess the endless life, the power of a world that hath no end.
And so keep your eyes to your possessions, and to the life that hath no end;
and herein you will increase in the truth, in the righteousness and holiness,
and the power and virtue of the holy life; and so sit down in your possessions,
that you may all serve the Lord in a pure mind, soul, and spirit,
and none to defile your bodies, but have esteem of them, as vessels of honour,
and vessels fitted to receive the treasures of the Lord.

G+++.+++ F.

London, the 16th of the 9th month, 1666.

[.centered]
=== Letter 247.

Dear friends,

Dwell in the gentle wisdom of the Lord God, which is easy to be entreated;
and let not willfulness, hastiness, and impatience, lay open your nakedness to the world;
but dwell in the power, seed, and life of Christ Jesus, the wisdom of God,
that with that ye all may be kept clothed in patience, and in the love of the Lord God,
and in the light; in which is the unity one with another, and with God.
And in the peaceable mind and spirit dwell, for the patient sufferer weareth the crown,
and hath the victory at last; and not the hasty, aggravating, revengeful, killing,
and fighting spirit; which must be crushed down with the seed of the Lord God,
that bruiseth the serpent`'s head; which is the cause of enmity, venom, and poison;
which head being bruised down with the seed and life, then nothing is fed upon but life,
and glory.
And in that is the peace.

G+++.+++ F.

[.centered]
=== Letter 248.

[.blurb]
==== An exhortation to set up women`'s meetings.

Friends,

Keep your meetings in the power of the Lord God, that hath gathered you;
and none quench the spirit, nor despise prophesying,
but keep up your testimony in public and private.
Let not the mouths of babes and sucklings be stopped, nor the seed in male or female,
but all be valiant for the Lord`'s truth upon the earth.
Concerning the women`'s meetings; encourage all the women of families,
that are convinced, and mind virtue, and love truth, and walk in it;
that they may come up into God`'s service,
that they may be serviceable in their generation, and in the creation,
and come into the practice of the pure religion, which you have received from God,
from above; that every one may come to know their duty in it,
and their service in the power and wisdom of God.
For now the practical part is called for.
For people must not be always talking and hearing,
but they must come into obedience to the great God of heaven and earth.

And so that none may stand idle out of the vineyard, and out of the service,
and out of their duty; for such will talk and tattle, and judge with evil thoughts,
of what they in the vineyard say and do.
And therefore the power of the Lord God calls in all, into their duty,
into their service, in their places, in virtue and righteousness,
and into the wisdom and power of God.
For all that are out of this, are out of their duty and services,
though they may have the knowledge of it,
yet are not serviceable in the creation nor in their generation;
and the power of God must go over, and is over all such; in which all must be acted,
and in which true obedience is known.

And therefore train up your young women to know their duty in this thing,
that they may be in their services and places;
for all truth`'s business you are to do in the power and wisdom of God;
by which you are kept open to the Lord, to receive of his gifts and graces,
and of his life, through which you are to minister one to another.
And all keeping in it, then there is none to let nor stop its flowing;
but through it you are all watered, as a garden of plants; by which you are nourished.
And so all be faithful and diligent.
And make all the sober women, both of town and country, acquainted with this thing.
And read this in your Monthly Meetings, when you are gathered together.
And when you have made the sober women acquainted, in the towns and countries,
and have them together, then read this amongst them.
So no more but my love.

G+++.+++ F.

[.centered]
=== Letter 249.

[.blurb]
==== A general epistle to Friends, and all people, to read over and consider in the fear of God.

Blessed are all those whose minds are stayed upon the Lord,
for they shall be kept in perfect peace; so where the mind is stayed upon the Lord,
there is a perfect peace; for it is a whole peace, which cannot be broken.
So here is not only a perfect peace, but a blessing;
a perfect peace which comes from the God of all peace,
(that bruiseth the serpent`'s head under your feet,
the troubler,) and the blessings which come from the blessed God.
So all imperfect peace may be broken, that is when the mind is stayed upon the creature,
or in any creature, and not upon the Creator; or in any outward things, goods, houses,
lands, or inventions of vanities, in the foolish vain fashions;
which the lust of the eye and the pride of life go into,
which will defile and corrupt it.
When any of these things fail, and are not according to your mind, it being in them,
then your peace is broken, and you are cross and brittle, and envy gets up.
So this is not a perfect peace, but is a broken peace,
and then you have the trouble and not the blessing.
And the reason is, because your minds are in the creatures, and the outward things,
and are not stayed upon the Creator, where the perfect peace is, and the blessing,
where nothing can get betwixt you and the Lord.
And this is below Job, to have the mind in the creatures and visible things;
for when you are tried, and creatures fail you, you are crossed and troubled;
that shows an imperfect state; for God said, that Job was a perfect man.
And when the Lord suffered him to be tried,
and when his goods and houses were thrown down, and driven away, and servants killed,
he said, "`Blessed be the name of the Lord; for the Lord gave, and the Lord taketh.`"
Here his mind was stayed upon the Lord, and he retained his peace.
And when that his children were destroyed, and his wife said to him,
"`What! dost thou still retain thy integrity?
Curse God and die;`" he rebukes her and calls her a foolish woman; and said unto her,
"`Shall I receive good of the Lord, and not evil?
Naked I came out of my mother`'s womb, and naked I must return.`"
Here Job kept his integrity still, and did not all this while offend with his lips.
Now many of you, who think yourselves high, and-above Job,
if your goods and children should be after the same manner taken away,
(whose minds are in them,) you would be found in a troubled brittle state, far below Job.
And when Job`'s friends came to reason with him, who kept his integrity,
and would no way yield to them, they counted him an hypocrite, and said,
"`he restrained prayer, and filled his belly with east wind;`" and said,
"`What! shall mortal man be more pure than his maker?
Shall man that is born of a woman be just?
God chargeth his angels with folly, and the heavens are not clear in his sight.`"
And these are the scriptures the priests use to bring against Friends,
(who keep their integrity,) as Job`'s friends did against him.
But at the last the Lord commanded Job to offer a sacrifice for his friends,
because they had sinned, and spoken not right, as Job had,
who was perfect and kept his integrity.
And the apostle said to the saints,
"`that he had learned in all conditions to be content.`"
(Mark,) in all conditions; but this was when he was Paul, not when he was Saul,
running up and down with his packet of letters,
haling the saints before the rulers like a parater; then he was not content,
neither with his own condition, nor others; but when he came to learn Christ,
who destroys the devil and his works, who teacheth to know all things,
then in all things he learned to be content.
So that you know that there is learning, and learned; as a child when he is learning,
and become learned, is witness of two states.
So Paul, he had learned in all conditions to be content; and who was his schoolmaster,
but Christ, by whom all things were made, not of man, nor by man,
(out of the truth,) so while he learned of men, and by men, he was not content,
neither are any others.

Therefore all are to learn of Christ, the light, the life, and the truth,
that you may come to that condition, to have learned in all conditions to be content,
and not to trust in uncertain riches, for they have wings and will flee away.
And so he is never counted a wise man,
that will put any confidence in that which will flee away from him;
for those are the heirs of the earth and the world, that load themselves with thick clay,
that they may set their nests on high; but they that be heirs with Christ,
and of the power of an endless life, trust in the living God,
and come to possess an everlasting inheritance of the power of an endless life,
and come to increase in the riches of the everlasting inheritance,
and there lay up riches that are everlasting, which will abide forever.
And mind every one God`'s word in your hearts, and in your mouths, and obey it and do it;
and be not of them that are saying in their hearts, who shall ascend or descend,
to fetch him from above, or from the deep?
Keep down that sayer under reproof,
and then your ear will be open to that which the righteousness of faith saith,
the word is nigh thee, in thy heart, and in thy mouth; so thou needest not to say,
who shall ascend or descend?
And that was the word which the messengers of God preached and do preach,
and rebukes the gainsayer.

And so all people, seeing the devil hath made the world like a wilderness,
and there are so many ways in it that they do not know which way to come out of it,
nor which to follow.
Therefore this is my answer to you all, take David`'s lamp and light.
You may say, what is that?
and where is it?
I say it is with you, the word of God.
You may say, people do not use to carry lamps in the daytime, but in the night.
I say, you are in the night of darkness, and therefore the word is called a lamp,
and a light to you; by which you may see the way of the Lord, which is perfect,
from all men`'s ways, which are imperfect;
by which ye may see the path of the just to be a shining light,
from all the unjust paths that are in the darkness.
For by this word did David come to outstrip his teachers,
and was made wiser than them all; so it will you, if you obey it;
for by this word he saw Christ, and called him Lord.
Therefore he loved the word and hid it in his heart;
and by it he spake so many glorious expressions,
which the world since hath turned into metre, and made songs of them.
And this was the word that came to Abraham,
which made him forsake his national religion and worship, and obey the Lord.
And this was the word that came to Jacob, the shepherd, by which he saw Christ,
and prophesied of him to his sons on his deathbed, when he said to Judah,
the sceptre should not depart from Judah; nor a lawgiver from between his feet,
till Shiloh came, (meaning Christ,) and the gathering of all nations should be to him,
as it is at this day; the gathering is to Christ.
And this was the word that came to Moses, the shepherd, when he `was keeping sheep,
which he obeyed and went to Egypt, and brought the children of Israel out of Egypt;
by which word he was made a minister;
and when that the children of Israel were come out of Egypt into the wilderness,
he told them, "`they need not go for the word beyond the seas, etc. for it was nigh them,
in their hearts and mouths, to obey it and do it.`"
And this was the word that made Moses a prophet, who prophesied of Christ; and said,
"`like unto him God would raise up a prophet, him should they hear in all things.`"
Mark! in all things; we are to be ordered both inward and outward,
through hearing Christ, by whom all things were made.
And every one that would not hear this prophet (Christ) should be cut off.
For how should they continue or reign that will not hear Christ?

And this was the word that came to Samuel, and made him a prophet,
who spake to Eli the priest, and reproved his sons, and the children of Israel.
And this was the word that made Saul to prophesy, and Balaam, though they erred from it.
And this was the word that made all the prophets to prophesy,
and to reprove the kings of Israel, and their priests,
of their superstition and idolatrous ways, in setting groves and images in high places;
and reproved all their monthly prognostications, who spoke and acted from them,
and not from the Lord.

And this was the word that came to Isaiah, by which he prophesied of Christ,
and of his preaching, and of his sufferings, and by which word he reproved the shepherds,
which were as greedy dumb dogs, that could never have enough,
seeking their gain from their quarter; And by this word he saw,
that all the children of God should be taught of God,
and be established in righteousness and peace;
and though many tongues should rise up in judgment against them,
yet those that were taught of God should condemn them all;
such power should be given to his children.
And the many weapons formed against them should not prosper, God would restrain them.
And also he saw them that were cast out, that trembled at God`'s word;
to whom God would appear to their glory,
and to the shame and to the confounding of them that cast them out for his name sake,
as it is at this day.

And this was the word of God that made Jeremiah a prophet,
by which he saw the new covenant;
by which word he was sent to reprove the people and the princes,
of the filthy and horrible thing committed in the land,
that the priests preached for hire, and the prophets prophesied falsely.
And for reproving them for their superstition and idolatry, they struck him,
and put him in the stocks and prison, and persecuted him in the dungeon,
till his persecutors were carried into captivity.
And by the word Jeremiah saw the number of seventy years
of his persecutors being in Babylon`'s captivity.

Elijah by this word was made a prophet,
and by the word reproved Ahab and Jezebel for their idolatry, and worshipping of images.
For which word`'s sake they persecuted him, and the rest of the prophets;
and was not he fed of the ravens by the river?
And did they not seek to take away his life?
And did not he think all the Lord`'s prophets had been killed, and he left alone;
yet did not the Lord say to him,
he had reserved seven thousand that had not bowed the knee to Baal?
And Elisha, the ploughman, by this word, was made a prophet, and forsook his plough;
and by the word reproved the idolatry in his age of priests and people.

And by this word was Ezekiel made a prophet;
by which word he reproved the shepherds of Israel, that made a prey upon the people,
and taught them for the fleece.
And by the word he saw that God would bring the people from under them,
that they should be made a prey upon no longer; and would gather them from their mouths,
and set one shepherd over them, even Christ,
(who is witnessed.) And by the word he reproved the false prophets,
that taught for handfuls of barley and pieces of bread,
and daubed with untempered mortar, and sewed pillows under the arm holes.
And by the word, he saw the pattern of the temple, and the return of the Jews.

And by this word Daniel was made a prophet, and saw Christ and his kingdom,
and how the saints should take his kingdom.
And by, the word he saw such that should rise up against the people of God.
And by the word he numbered the years of Christ to his time,
four hundred ninety-nine years, and of his death, and how he should end the sacrifices;
and how that Christ should bring up everlasting righteousness, and put an end to sin,
and end their prophets, and seal up their visions.

And by the word was Micah made a prophet,
by which he cried against the priests that preached for hire,
and the prophets that prophesied for money, and the judges that judged for rewards,
and such as preached peace to the people that put in their mouths,
(like the priests in these times,) and when they did not, they prepared war against them,
and chopped their flesh, and broke their bones.
But Micah saw by the word that the sun was gone down upon such prophets and priests,
and they should have no vision nor answer from God.
Therefore such as are against revelations and visions, on them the sun is set,
and gone down and the night comes upon them.

And by the word was Amos the herdsman made a prophet, who was a gatherer of fruits;
and likewise all the rest of the prophets, who spoke forth divine things,
and reproved the superstition and idolatry in their time and day.
And by the word did the prophets speak forth divine things;
which word brought them into the divine nature and mind;
which word hammered and cut down that which corrupted their natures.
And this was the word that made so many fishermen preachers of the gospel,
which is the power of God.

And this was the word which made Matthew the toll gatherer, Luke the physician,
and Paul the tent maker, ministers and preachers of the gospel, and power of God.
And this was the word which made Peter to see Joel`'s prophecy,
how that God would pour out of his spirit upon all flesh,
and sons and daughters should prophesy, and young men should see visions,
and old men dream dreams;
and the pouring forth of the spirit upon servants and handmaids,
that every one should have something to speak to the glory of God.
And now priests, and proud prelates, and bishops, and popes,
though you have made a trade of the saints`' words, and apostles`' and prophets`' words,
and gotten a great deal of money by them,
(which were fishermen and shepherds`' words from the word,) yet nevertheless,
if a company of shepherds, herdsmen, fishermen,
tent makers and toll gatherers should come amongst you to preach, you would say,
Away with these mechanic fellows;
they have not served seven years apprenticeship at the colleges,
which were set up to make ministers; therefore they are not to set up,
because they have not served their apprenticeship.
What say the shepherds, herdsmen, fishermen, tent makers, physicians, and toll gatherers?
Do you make a trade of our friends`' words, who were of our occupation,
that never served apprenticeships in colleges,
before they spake forth the words you make a trade of?
What! will you make a trade of our friends`' words, who were of our occupation?
Away with you to work, and away with your colleges;
for our brother Paul the tent maker said, he that will not work must not eat.
For, would you own Christ if he had come in your day, who was called, a carpenter`'s son?
You popes, with your triple crowns, and you lord bishops,
with your coaches and pampered horses, and gorgeous apparel, with your black coats,
and white coats, and silk girdles:
are you like to entertain him who was called a carpenter`'s son?
Or to cast him and his mother into the manger in your stables.

This was the word by which John the evangelist saw Christ,
who doth enlighten every man that cometh into the world, and saw how he became flesh,
and came to his own, and that his own did not receive him;
but to as many as received Christ the light,
to them he gave power to become the sons of God;
which all they that are ministers of the letter,
made by their seven years learning in their colleges, and not by the word,
(hating the light,) cannot know.
And by this word, the minister of the word preaches Christ`'s word, life,
death and resurrection.
And therefore, as John saith in his epistle, "`That which our eyes have seen,
our hands have handled, and our ears have heard of the word of life,
do we preach unto you; that which was from the beginning.`"
In the beginning was the word; though since the beginning were the words and letters;
for the scriptures of truth are the words of God, and the words of Christ;
and he that adds to these words,
(saith John in the revelations,) God shall add unto
him the plagues that are written in this book, etc.
So the word was in the beginning, and Christ`'s name is called, the word of God;
but Christ is neither called scriptures nor writings, for scriptures signify writings.
So, in the beginning was the word; since the beginning were all false ways,
false churches, false teachers; and in the word ye comprehend them all.
The priests say, that Hebrew, Greek, and Latin, are the original;
but the many languages began at Babel, which Nimrod, the hunter before the Lord,
began to build, after God had destroyed the old world with water;
then would he go build a tower, which should reach to heaven;
then God came down and confounded them into many languages.
So he hunted before the Lord, but the Lord followed him,
and confounded him in all his work, as he will all the builders that run before him.
And all the priests that have gotten the many languages, which began at Babel,
they tell simple ignorant people that they have the original, and are the orthodox men,
and get into a different habit from them, and say, the Quakers are a simple people,
and despise the learned orthodox men, who have the original.
Give ear O people!
If these languages, which came up at the confounding of Babel,
are the priests`' original that makes them orthodox and divine, then Pilate,
that crucified Christ, was as good an orthodox divine as they;
for when he crucified Christ, he wrote a paper in Hebrew, Greek, and Latin,
and set atop of him; he was as ignorant of scripture,
and of orthodox and divine matters as you, and you as he.
And the apostle saith,
"`that tongues must cease;`" then that which makes orthodox men and divines, as you say,
must cease, according to the apostles`' doctrine;
and so then tongues neither are the original, nor make orthodox nor divine.
And John, that gave forth the revelations, saith,
"`that the whore and beast set upon tongues,`" etc.
"`and the everlasting gospel must be preached again to all
kindreds and tongues;`" which was before Babel was,
where was the beginning of tongues.
Now it is clear that the gospel must be preached to all nations and tongues;
and that tongues are not the original, neither do they make divines, or orthodox men;
but it is clear that it is the word which was in the beginning which makes a divine; yea,
of tradesmen, who are base and contemptible in the eyes of the proud,
and them that have gotten Babel`'s tongues,
who are confounded by the ministers of the word which was in the beginning,
before Babel was; for all the earth was of one language and speech before Babel.
And you that call yourselves orthodox men made by tongues, and say,
that is your original, you are so blind,
that you cannot see that there was an original before Babel was; for,
did not Enoch the prophet, the seventh from Adam,
who prophesied in the old world before it was destroyed, and long before Babel was,
speak concerning the coming of Christ in ten thousand of his saints, as in Jude?`"
And Lamech prophesied, in the old world, concerning Noah and Adam,
and others might be instanced,
who were before your tongues (which you call your original) were.
And so we say, that the word of God is the original, which doth fulfill the scriptures;
and the word is it which makes a divine, which is called a hammer,
but it is a living hammer; and is called a sword and fire, but it is a living sword,
and a living fire, to hammer, and cut down,
and burn up that which separated and kept man from God;
by which word man is reconciled again to God, which is called the word of reconciliation;
by this word are men and women sanctified and made clean.
And this is the word that makes both men and women divine,
and brings them into the divine nature,
which hammers and cuts down that which corrupted their nature;
and by this word are they brought into a divine wisdom, understanding, knowledge, spirit,
and power.
And this is the word that lives, and abides, and endures forever,
by which the saints are born again of the immortal seed and word of God,
(who feed upon the milk of the word,) up into a divine life, wisdom, and understanding,
and divine nature.
And by this word they do see all flesh to be as grass,
and as the flower of the field that fadeth; and the word of God that lives, and abides,
and endures forever, is Christ, whose name is called the word of God.

And so keep the word of patience, which is over all the impatient spirits,
and then you will know that the word of life, the word of patience, and word of wisdom,
is everlasting, and abides and endures forever.
All they that are in the letter, out of the life and word,
have neither patience to themselves nor others; for the word of patience,
and the word of life, which is to be kept in all tribulations,
was before death and impatient spirits were.

=== Concerning the worship of God, and the Jew outward, and the inward Jew`'s offering, with their garments.

1+++.+++ There was a worship at Jerusalem.

2+++.+++ There was a worship at the mountain, where Jacob`'s well was.
Jacob went down into Egypt with his family, and he died in Egypt,
and his sons carried him out of Egypt, and buried him in the land of Canaan,
in his grandfather Abraham`'s burying-place;
and after several hundred years the children of Israel
came out of Egypt into the land of Canaan,
and there they built Jerusalem and the temple;
and there was but one temple in the whole world commanded of God,
and that was at Jerusalem.
And before, in the days of Jacob, there was a worship set up at the mountain,
near unto Samaria, where Jacob digged a well.
Therefore when the woman of Samaria came out to fetch water at Jacob`'s well,
the woman reasoned with Christ about worship, and she said,
"`Our fathers worshipped at this mountain,
but others at Jerusalem;`" and Christ answered her again,
"`The time cometh that neither at Jerusalem,
nor at this mountain shall God be worshipped.`"
There he denies the continuance of these two public places of worship;
and when he had done that, he sets up another worship, for he said, "`God was a spirit,
and they that worshipped him must worship him in the spirit and in the truth;
for the hour cometh, and now is, that such God seeks to worship him.`"
And this worship he set up, and preached up above sixteen hundred years since;
which worship he set up many hundred years before mass-book, common-prayer-book,
directory, or church-faith was.
And this was the public worship that Christ set up in the spirit and in the truth;
"`for God is a spirit,
and such he sought to worship him;`" that worshipped him in spirit and truth.
So all are to mind the worship that God seeks, and not the worship that men seek.
And Christ said, "`that the temple should be thrown down, and the city of Jerusalem,
and the Jews scattered over all nations.`"
And the apostle saith, "`He is not a Jew that is one outward,
but he is a Jew that is one inward in the spirit, and not of the letter;
for that killeth, but the spirit makes alive.`"
What! cries the world, do you deny temple-worship?
Nay, we say every man and woman must come into the temple,
if he worship God in the spirit and truth.
And is not the spirit within, and the truth in the inward parts?
For, "`do not you know that your bodies are the temples of the holy ghost,
which is the holy spirit?`"
And can any worship God who is a spirit, in the truth,
but they must come to the spirit and the truth of God in their own hearts?
Here we set up the public and temple worship, which Christ set up,
which every man and woman in the world must come to,
"`truth in the inward parts,`" and the spirit of God within them,
and worship in the spirit; they must be in it, and in the truth,
to worship the God of all truth, who is a spirit.
And this is the public and universal worship;
and this brings every man and woman in the world to truth,
and the spirit of God in their own hearts.
And so this brings all to know their bodies to be the temples of the holy spirit,
in which they worship, as the Jew outward worshipped in his outward temple.
But the temple, since the apostles`' days,
has been so filled with smoke out of the bottomless pit, and so filled with darkness,
that no man could enter into the temple to worship God;
and there the spirit of God hath been vexed and grieved.
And so their prophecy, revelation,
and vision have been denied by the author of this smoke;
but the seventh angel has poured out his vial,
that men begin to enter into the temple to worship God in the spirit and truth;
and the glory of the Lord shall fill the temple.
And Christ and his apostles never altered this worship in the spirit and in the truth;
though the beast and the whore, the false church,
have set up another worship since the apostles`' days.
But all must come to worship God in spirit,
(which was before their worship was set up,) which was set up in the apostles`' days.
And so all must come to worship God in the spirit and in the truth,
which was before mass-book was, which got up many hundred years after Christ;
but that is and was the public and universal worship, set up by Christ the second Adam,
to the sons of Adam in the fall, which brings every man and woman to truth,
and the spirit of God in their own hearts,
in that spirit and truth they must worship God.

But, cries the world, did not they pray in the temple, the Jew outward,
and must not you pray in the temple?
Yes, the Jews in the spirit pray in his temple, and sing, and rejoice in his temple; for,
what!

"`Do you not know, that your bodies are the temples of the holy ghost?`"
And so, if you pray, you must pray in the holy ghost, and rejoice in the holy ghost,
and sing in the spirit: and how can you sing, and rejoice, and pray in the spirit,
but you must go into the temple, your bodies being the temples of the holy ghost?
For the outward Jew`'s temple was thrown down: and he is not a Jew that is one outward,
but he is a Jew that is one inward in the spirit.
Stephen was stoned to death, for denying the Jews`' outward temple,
and witnessing Christ; and Stephen was full of the holy ghost;
so he was the temple of the holy ghost:
and so they whose bodies are the temples of the holy ghost,
are the temples made without hands,
which are set above all temples made with men`'s hands.

But if you say, "`Did not the Jews`' priests dwell in the temple,
and there they were to offer in the temple?`"

In answer, yes; there was but one temple in the whole world commanded of God,
and it was set up at Jerusalem, and never commanded to be set up in England, Ireland,
Scotland, France, Spain, and Rome;
but the Jews were to go either to worship at Jerusalem,
and there to keep the feast of tabernacles,
or else their eyes were to rot in their heads, and their tongues in their mouths,
and their camels were to die of such and such plagues; as in Zechariah you may read.
And they were to come out of all nations under heaven,
to worship and keep the feast of tabernacles at Jerusalem;
and the apostles did there wait, at the time of Pentecost,
to be endued with power from on high.
And so that temple was thrown down about forty years after Christ:
for you that cry up outward temple worship, made with men`'s hands in your own nations,
are worse than the Jews; for they were to have but one temple, and one people;
and that temple is down, and the worship; and he is not a Jew that is one outward,
but he is a Jew that is one inward in the spirit.
And so Christ`'s worship in the spirit and truth,
is set above the Jews`' outward worship at Jerusalem,
and the mountain worship near Samaria; and the Jew inward is set above the Jew outward;
and above the Jew`'s outward offering in his outward temple,
and the priest having chambers in the temple, that was the place of their offering;
the Jew inward, he offers in his temple the spiritual sacrifices;
and no where else doth he offer but in his temple; for by the spirit,
doth he offer to God, who is a spirit.
And they that offered in "`the Jews`" temple, were to wear the holy garments;
so are you to do that are the true christians, and are called a royal priesthood.
What! are all true christians priests?
Yes. What! are women priests?
Yes, women priests.
And can men and women offer sacrifices without they wear the holy garments?
No. What are the holy garments men and women must wear?
The fine linen; and they must go in white, What! is this the priest`'s surplice?
Nay; the surplice got up when the fine linen, the righteousness of saints,
and going in white, was lost.
What is the fine linen and going in white, that this royal priesthood must wear,
which are the royal garments?
It is the righteousness of Christ, which is the righteousness of the saints;
this is the royal garment of the royal priesthood, which every one must put on,
men and women.
So every one put on your robes, put on your garments, the righteousness of Christ,
as a cloak, that you may offer to the Lord an offering in righteousness.
You that are sensible of the Lord`'s mercies, offer to him his praise,
his glory and honour, his spiritual sacrifice in your temple, as the sweet odours, myrrh,
and frankincense.
And when the Jews`' temple was cleansed, and the rubbish cast out of it,
the glory of the Lord filled the temple: and when your temples are cleansed,
and the rubbish cast out of your temples by your high priest, Jesus Christ,
in the male and the female, who destroys the devil and his works,
you will witness renewing up into the image of God, into righteousness and holiness,
as man was in before the serpent got the rubbish into him.
So Christ, who destroys the devil and his works,
brings them to the state that man and woman were in before he got into them that is,
into righteousness and holiness, and up into himself,
to the measure of the fulness of Christ,
who was glorified with the Father before the world began.
Here the glory of the Lord will fill every one of your temples,
through which you will come to praise the Lord in your temple,
and to offer an offering in righteousness in your temple by the spirit,
a spiritual sacrifice to God, who is a spirit.
So here you are a royal priesthood, offering up the spiritual sacrifices.
And was not the Jew outward, to have fire and lamps burn always in his temple?
And are not the Jews in spirit always to have the word, which is a fire, in their temple,
and the light of Christ?
For doth not Christ say, "`Have oil in your lamps?`"
And were not their bodies that lamp?
And was there not to be salt in the Jews`' temple, to season their sacrifices?
And so, are not you to have always salt in yourselves,
(doth not Christ say so?) by which you may savour and be seasoned,
that all your sacrifices may be seasoned with salt?
And you know that the Jews outward were not to offer the blind, the lame, the unclean,
and the halt in their temple; neither are you, that are the Jews in the spirit,
to offer the halt, the lame, the unclean, nor the swine, nor the blind;
but the spiritual sacrifice with the spirit to God who is a spirit;
by which spirit you see, and by which spirit you are made clean and sanctified,
and are enabled to mortify that swinish nature; by which spirit you come to walk upright,
not to halt; as you walk in the spirit,
by the spirit you come to offer to God the spiritual sacrifices.
And this is the standing offering in the temple, which Christ your priest dwells in,
who ends the Jews`' priests that dwelt in their outward temple, and ends their temple;
and ends their offerings and sacrifices, and the blood of bulls and goats.
Christ the offering, once for all their offerings; and Christ the everlasting covenant,
ends the first covenant; and Christ the temple, ends the Jews`' outward temple,
where their offerings and sacrifices were, and the priesthood,
and sets up the royal priesthood, with his royal garment, his righteousness,
that offers to God the spiritual sacrifices in the temple.
And so Christ ends all the types, figures, and shadows,
and variable things that were given to man since the fall, and held up by the law,
which they were not to add to the law of God, nor take from it;
which stood very nigh two thousand years: which law served till Christ came,
and was good in its place, and was added because of transgression.
When many transgressed the image of God, his righteousness and holiness,
and were fallen from it, then the righteous law, which is good, holy, and just,
came atop of man; and this served with all its shadows till the seed Christ came;
but Christ is come, who was the end of the law for righteousness sake,
to every one that believes; and in Christ is no shadow, variableness, nor turning,
for he was before shadows were, glorified with the Father before the world began;
who is the first and last, the beginning and ending, the top and corner-stone,
the chief master builder, the elect and precious one,
whom all the builders in all ages rejected, that were of men, and by men, and from men;
whom the heirs of the world cast out, and could not abide that he should reign,
whose right it is.
Though he be the foundation of many generations,
all the heirs of the world know not his generation; they that are in the first birth,
whose building is not on Christ the rock, but on the sand.
And therefore have their houses of religion and worship
so often been beaten down with the storms of the sea,
not being upon the rock Christ Jesus,
which is above all the storms and tempests in the world, and before the sea was;
who is the lion of the tribe of Judah, and the root of David,
and the lamb of God which takes away the sins of the world.
And the lamb must have the victory over all that are in the nature of wild beasts,
wild heifers, dogs, wolves, and horses.
And is not this a mystery to you all, that the lamb should take away your sins,
that the lamb should have the victory over the doggish, wolfish, heiferish,
and swinish nature in you, like horses or serpents?
The clean and holy lamb must have the victory over all this in you;
and therefore join to him that hath the victory, who is the captain of your salvation,
who bruiseth the serpent`'s head;
Christ the seed (that is he) that breaks the serpent`'s power,
and crusheth him to pieces, destroying him and his works.
Here Christ is King of kings, and Lord of lords, above all principalities, powers,
and thrones, is he ascended; "`who opens and no man shuts, and shuts and no man opens.`"
So he that opens to you by his light, none can shut from you,
who filleth your lamps with oil of gladness;
and Christ shuts to all them that deny his light, for they deny him;
no man among them then can open;
and that makes them go together by the ears about their worships, and churches,
and scriptures, and to persecute one another.
Though they do profess Christ, yet denying his light, they deny him:
these are antichrists, that are against him, though they do profess him;
and such are by the light condemned, that are against the power of God and the gospel;
the power of God is the savour of death to them,
but a savour of life to them that be in the life.
And, "`in me you have peace,`" says Christ; and he gives peace to them that are in him,
that no man can take away: "`but in the world you have trouble,`" saith Christ: that is,
in Adam, in the fall from righteousness and holiness;
for in righteousness there is peace, and in holiness people see God;
and out of this holiness they do not see God.

=== Concerning who drink the new wine, and who drink the old, and who are the bottles that hold each. And whose teeth are set on edge, and whose not.

Now all that are called Christendom, they do profess to believe in the name of Christ;
yet look upon them, see what a confused family it is, worse than the Turks, and Moguls,
and the heathen; for in the Turks`' country there are Jews, Christians, and Turks,
and the Turks keep their sabbath upon the Sixth-day, and the Jews upon the Seventh-day,
and the Christians upon the First-day;
and the Turks do not persecute them about religion, but let them enjoy their meetings.
And the Mogul, it is said of him,
that there have been sixty sorts of religions in his country;
but he persecutes none for their religion, but lets them have their meetings.
And that all that are called Christendom, professing the name of Christ,
that they should persecute one another, and tear one another to pieces about worship,
and religion, and the steeple-house, which they have given the title of church to;
which is a title taken from the people, and given to a house.
And that they should persecute one another about eating flesh and fish, the lents,
the holy days, and about fastings, and about white coats, black coats, girdles, tippets,
and hoods, altars, crosses, and candlesticks, and about processions,
and running to graves for relics, and such visiting places!
And that they that profess Christ should fall out about outward things,
and tear one another to pieces about outward things, and kill, imprison,
and burn one another about such things; and about their sacraments, and baptisms,
which are bread, and water, and wine; the kingdom of God stands not in meats, nor drinks,
nor flesh, nor fish, nor holy days, nor fasting days, nor tippets, nor hoods,
nor girdles, nor white coats, nor black coats, nor altars, nor candlesticks,
nor processions, nor beads, not steeple-houses.
The kingdom of God stands in righteousness, and faith, and joy in the holy ghost;
and where there is righteousness there is peace;
and where there is true faith there is victory,
and building one another up in the holy faith;
but out of this faith there is no building, no victory; but Cain, the sacrificer,
persecuting Abel.
And therefore they are not counted wise men and wise women that persecute
one another about such things that the kingdom of God stands not in.
Therefore love one another, instead of persecuting one another; and be meek,
and not high; and entreat, and not threaten; and bless, and not curse; and love,
and not hate; and do good, and not evil; and live in the will of God,
and be not self-willed; and mind the religion of Christ, and not your own;
for you persecute one another about your own things that you invent, and not Christ`'s;
for Christ`'s religion doth not admit of any persecution or violence,
nor to hate friends or enemies; but self-religion will hate and persecute both;
such deny Christ, manifesting they are not of God.
And so biting and devouring one another, hath been the way of consuming one another.
For, were there not more true christians before, than there were after the pope got up?
For when they began to bite one another, then they consumed one another.
And you read in the scriptures of two bottles, the old bottle, that holds the old wine;
and the new bottle, that holds the new wine;
and he that drinks the new will not desire to drink the old; and he, that drinks the old,
will not desire to drink the new.
And Christ is the vine that affords this new wine, which is put in the new bottle; and,
they that believe in his light, and become children of his light, sit under his vine,
and drink of his wine.
And Adam in the fall is the old bottle, that holds the old wine of transgression,
where all the sour grapes are,
and they that sit in transgression drink of the sour grapes,
of which their bottle is full, full of the wine of the wrath of fornication.
So they will not drink of the new.
So this old wine, that comes from the sour grapes, sets all their teeth on edge,
by which they bite and devour one another, and so are consumed one of another,
and devoured one of another, by their biting with their edged teeth.
Let all the places called Christendom witness to this since there hath been a pope,
and since there hath come up a Turk;
and how it was before their was a pope or a Turk either; what grinning and biting with,
their edged teeth, and consuming one another there hath been and is, to this day,
about religions which they made themselves, and are the works of their own hands,
(contrary to Christ and the apostles`' religion,)
and have fed of the works of their own hands,
and bitten others with their edged teeth, that would not.
But they that drink of the new wine, and desire not to drink of the old bite not,
but love one another, and love enemies; and so they are not consumed one of another,
but live in love, peace, and unity, and mind that which the kingdom of God stands in,
righteousness, and faith, and joy in the holy ghost.
And there is the pure religion from above, that keeps itself from the spots of the world;
which is, to visit the fatherless, and relieve the widows,
and live in the unity and fellowship of the spirit, which is the bond of peace;
and live in the law of the spirit of life,
which makes free from the law of sin and death,
which life was before sin was or death either.
And such sit under their own vine Christ, in the fellowship of the gospel,
the power of God, which power of God was before the devil was, and are the church in God,
and Christ is their head.
But they that have the old bottle full of the old wine,
that comes from the grapes of transgression,
(by which their teeth are set on edge,) obey the law of sin and death,
and are under the authority of the prince of the air and darkness,
and are under the power of death, and his lusts and works they do,
who was a liar from the beginning, whose religion lies in a lie,
and not in the truth that makes free; but that is it which the devil is out of,
and all his servants, and therefore they fight against the truth with their edged teeth,
who are drunk with the old wine; and such cannot abide to hear talk of truth,
and the spirit to guide people, who first hate it in themselves and quench it,
and grieve it; but such the God of truth will quench their fierceness,
and will grieve them that grieve his spirit, which is given to them;
who will judge the world in righteousness, and the secrets of every ones heart,
according to the gospel, and every one shall have a reward according to his doing.
And all you that profess Jesus, and live out of the law of Jesus,
the law of love and faith, and the spirit of life that is in him,
you are all on heaps about his and the apostles`' words, like unto the scribes,
Pharisees, Jews, and Saducees, that professed the law of God and his prophets,
and lived out of the law of God, and the life of his prophets; such were on heaps,
as the christians are now, that live not in the law of Jesus;
which cannot build up one another, but are the old bottles, full of old wine,
whose teeth are on edge with it, tearing and biting at the righteous, and one at another;
but the righteous shall reign, and his seed shall have the victory,
and God will break the teeth of the wicked.

=== Concerning gathering in the name of Jesus.

Christ Jesus the second Adam, who came amongst the sons of fallen Adam,
you may see the beginning of his setting up his meetings, when he saith,
"`Where two or three are gathered together in my name, I am in the midst of them.`"
So you see here Christ begins with a few, two or three;
for there was the gathering of the Jews, scribes, and Pharisees,
to their temples and synagogues.
And likewise there was the gathering of the heathen to Diana`'s temple.
And all they that gathered in the name of Jesus came from the Jews`' synagogue and temple,
and likewise the Gentiles, into the name of Jesus, whose name is above every name,
and there is no salvation by any other name under the whole heaven,
but by the name of Jesus, into which the true gathering is,
where all know their salvation.
And so who are gathered into the name of Jesus, are gathered into his power and authority.
For you know when a tax or assessment is gathered
in the name of the head or heads of a nation,
it comes with power and authority, and you obey it either actively or passively.

And so who are gathered in the name of Jesus,
they are gathered in the power of the second Adam,
whose power and authority are above the power of the first Adam`'s sons and daughters;
by which power, and in whose names, there people are gathered; but Christ,
whose name is above every name, there is no salvation by any other under heaven,
but by the name of Jesus; and they that are gathered in this name of Jesus, by his power,
in which they know their salvation, they see that there is no salvation,
by any other name under the whole heaven, nor gathering, by which they gather;
they bid farewell to all other names and gatherings under heaven,
as knowing there is no salvation but in the name of Jesus;
and this fulfils Jacob`'s prophecy, who said,
"`The lawgiver shall not depart from between Judah`'s feet until Shiloh come,
and the gathering of all nations shall be unto him.`"
So then it is clear, if the gathering of all nations be unto Christ,
they must forsake all that into which they were gathered before.
And therefore,
that makes all the heads of the national ways to be angry that hold them up;
and with such, the lamb makes war in righteousness, going on conquering and to conquer,
that he may rule whose right it is, that he might subdue all things to himself;
in whose name all things are to be done, and to whom all people are to be gathered,
whom God hath given for salvation to the ends of the earth.
And likewise, this doth fulfill Moses`' prophecy, who said,
"`Like unto me will God raise up a prophet,
whom in all things the people shall hear,`" who is
the salvation to the ends of the earth,
to whom the gathering of all nations must be;
and they who are gathered in his name do and must hear him in all things,
by whom all things were made and created,
who was glorified with the Father before the world began.

[.centered]
=== Letter 250.

[.blurb]
==== A warning to all to keep out of the vain fashions of the world, which lead them below the serious life; and not to fashion themselves according to the world.

Friends,

Keep out of the vain fashions of the world; let not your eyes, and minds,
and spirits run after every fashion (in apparel) of the nations;
for that will lead you from the solid life into unity with
that spirit that leads to follow the fashions of the nations,
after every fashion of apparel that gets up.
But mind that which is sober and modest, and keep to your plain fashions,
that therein you may judge the world, whose minds and eyes are in,
"`what they shall put on, and what they shall eat.`"
And Friends that see the world so often alter their fashions, if you follow them,
and run into them, in that ye cannot judge the world,
but the world will rather judge you.
Therefore, keep all in the modesty, and plainness, and fervency, and sincerity,
and be circumspect; for they that follow those things,
that the world`'s spirit invents daily, cannot be solid;
and many fashions might be instanced, both of hats, caps,
and clothes of men and women that daily are invented,
which they that run into are near unto the world`'s spirit,
and their eyes are gazing after them, when they should be upon the Lord,
from whom they should receive judgment.
Therefore all keep down that spirit of the world that runs
into so many fashions to please the lust of the eye,
the lust of the flesh, and the pride of life.
And fashion not yourselves according to your former lust of ignorance;
and let the time past be sufficient,
in which you have lived according to the lusts of men, and the course of the world,
that the rest of your time you may live to the will of God,
taking no thought what ye shall eat, what ye shall drink, or what ye shall put on;
that therein your lives may judge the heathen, and that you may be as the lilies.
For nothing you brought into the world, neither any thing shall you take out.
And, therefore, while the eye is gazing after every new fashion,
and the mind and desire is thirsting to get it; when it has it, it lifts up the mind,
and so brings under the judgment of them that are in the sober life,
and of the world also, and to be like them.
Therefore take heed of the world`'s fashions, lest ye be moulded up into their spirit,
and that will bring you to slight truth, and lift up the wrong eye, and wrong mind,
and wrong spirit, and hurt and blind the pure eye, and pure mind,
and quench the holy spirit; and through such foolish toys, and fashions,
and fading things, you may lose your conditions.
Therefore take heed of the world`'s vanity, and trust not in the uncertain riches,
neither covet the riches of this world, but seek the kingdom of God,
and the righteousness thereof, and all other things will follow;
and let your minds be above the costly and vain fashions of attire,
but mind the hidden man of the heart, which is a meek and a quiet spirit,
which is of great price with the Lord.
And keep to justice and truth in all your dealings and tradings, at a word,
and to the form of sound words, in the power of the Lord and in equity,
in yea and nay in all your dealings, that your lives and conversations may be in heaven,
and above the earth, that they may preach to all that you have to deal with;
so that you may be as a city set on a hill, that cannot be hid,
and as lights of the world, answering the equal principle in all,
that God in all things may be glorified.
So that you may pass your time here with fear, as pilgrims, and strangers,
and sojourners, having an eye over all things that are uncertain, as cities, houses,
lands, goods, and as things below.
Possess them as if ye did not; and they that marry, as if they did not;
yet as having a city, whose maker and builder is God,
and a possession of an inheritance that will never fade away,
in which you have riches that will abide with you eternally.

G+++.+++ F.

[.centered]
=== Letter 251.

My dear friends in the truth and seed of God, in which is purity and life,
let that flow from the head to the feet, that righteousness,
and judgment may run down our streets as a stream.
For now Friends are become a people gathered in the holy name of Jesus.
Therefore all are to walk worthy of the high calling of God in Christ Jesus;
and every one as he hath received him, so walk in him, as becometh the gospel,
which is the power of God, which was before the devil was;
that in that your life may shine before men, to answer that of God in all,
that they may behold your good works, and glorify your Father which is in heaven.
And so, walk in the light as children of the light and of the day.
For you know that formerly we did cry against the powers of the earth,
because that judgment, and justice, and righteousness did not run down their streets.
And now that Friends are become a great people, shall not judgment, and justice,
and righteousness run down our streets as a stream and a flood,
to drive away all the filth from amongst us.

And now that Friends are become a good savour in the hearts of all people,
they have a friend in their house that will plead for them;
by which Friends have been kept and preserved in the life,
to answer the friend in their house.
And God having given them his dominion and favour, lose it not,
but rather increase it in the life;
for at first ye know that many could not take so
much money in your trade as to buy bread with;
all people stood aloof of you, when you stood upright, and gave them the plain language,
and were at a word; but now you, through the life,
having come to answer that of God in all, they say,
they will trust you before their own people, knowing that you will not cheat, nor wrong,
nor cozen, nor oppress them.
For the cry is now amongst them that are without,
where is there a Quaker of such and such a trade?
So that they will deal with Friends before they will deal with their own.
Oh! therefore friends, who have purchased this through great sufferings,
lose not this great favour which God hath given unto you,
but that you may answer the witness of God in every man,
which witnesseth to your faithfulness, that they may glorify your Father on your behalf.

And now, friends, if there be any oppression, exaction, or defrauding by making a prize,
through the freedom which God hath given you, the world will see such, and say,
the Quakers are not as they were; therefore such should be exhorted to equity and truth.
And also, if any run into debt, and aim at great things,
and make a great show in the world of other`'s goods, which comes to burden others,
and lift up themselves with that which is not their own,
and are not able to satisfy them, according to their time and word; such hurt themselves,
burden others, and oppress them, and bring grief,
and cause heart-rising in them to see such grown up by oppression;
therefore such must be exhorted to justice, equity, and righteousness,
and an even measure, to do as they would be done by.

And also, such as go under the name of Quaker, that are gotten into the earth,
and settle their nests there in ease; such come to cry against Quakers`' meetings,
saying, away with your forms; and will not come to our meetings, and hurt others,
by which the world gets occasion against the truth.
Therefore such must be exhorted, for such never knew the purchase of the truth,
and if they did, they have sold it.

And, friends, forget not the assembling of yourselves together, as the manner of some is,
and was; lest there be an evil heart of unbelief, in departing from the living God,
but exhort one another daily; and so much the more, as the day doth appear,
showing the more light, the more day, the more building, the more exhorting in the light,
and in the spirit, in fellowship one with another.
And they that do forsake the assembling of themselves together,
as the manner of some was in the apostles`' days, and is the manner of some now,
such grow more and more in the evil heart, departing from the living God.
And this brought in the apostacy, which the apostates set up,
and all the whole body of trifling traditions.
Therefore such as be in the everlasting power of
God must exhort such to take heed and be wise.

And also,
all such unruly spirits that have professed (falsely) and got under the name of Quakers,
whose evil words corrupt good manners, must be exhorted from house to house.

And also such young people, lasses and lads, that go in youthful ways,
and take liberty to go into pleasure, and to play, and to alehouses and drunkenness;
which corrupt the earth, which is one mark that they are dead whilst they live.
And these kill the just, and burden the righteous,
and cause the way of truth to be evil spoken of.
Therefore such must be exhorted to live in the truth,
and to come to that which will mortify that which leads to death;
so that truth may be adorned by them.

And also such that will not go to meetings, and cry against others that do, and say,
they are forms of men; and one while they will not give the hand;
and another while they will keep on their hats when Friends pray,
and yet secretly they can go to bad house`'s, as several have done.
From these abominable things they must be exhorted and reproved.
And if they do not repent,
and come to judge and condemn those things that they have done amiss,
and do live in that which doth condemn,
and give forth a paper to take their transgressions
and bad doings out of Friends`' minds;
and to the people of the world manifesting their repentance.
But, if they do neither repent, judge nor condemn,
nor give forth a paper against such bad actions,
which make the world to speak evil of the truth and the right way,
then Friends must give forth a paper to the world, to certify against them,
for clearing the truth.
And better such had never professed the name, nor known the truth,
nor come among them who were gathered into the name of Jesus,
and into the form of sound words, and into the son of God and godliness,
than to have gone into a form of their own, which they have received, yea,
even from the worst of men; who are thereby come under the judgment of common,
outward people.
And therefore Friends, all uncleanness, of all sorts, and unrighteousness,
and unfaithfulness, and youthful ways of running out, and liftings up,
such must be exhorted and reproved; that truth and righteousness may flow,
through which you may keep that which you have bought, and kept through great sufferings,
and some to death; that truth in all things may be adorned.

And all such as are tattlers, busy-bodies, backbiters, and gossipers,
are to be exhorted to mind their own conditions, that they may live in the truth,
and not to draw others out to words, wherein there is no profit; that truth may flow,
and the life may flow, and the unity may increase in the spirit and power;
that all may come to live in the gospel order, which was before the devil, or enmity,
or adversary was.

And all such as cry, "`Away with your laws, we will have none of your laws.`"
To such as come to the law of the spirit of life in Christ Jesus,
which makes free from the law of sin and death, and puts down that authority;
which life was before death and sin were, and remains when they are gone;
and in the life in Christ Jesus, is the saints`' fellowship, and unity,
and bond of peace.
All such as cry against laws so much, are the sons of Belial,
and would be without the yoke of the law of the son of God.
Such always were the stirrers up of mischief and schism from the body,
and they took liberty to say any thing; as ye may read in the book of Kings,
in the days of Jezebel, and in the days of Stephen;
and yet these that cry so much against laws,
yet they live themselves in the law of sin and death; which they obey when they do evil;
who are without the understanding of the righteous law,
which the righteous live in and see.
Therefore, such must be exhorted and reproved, if they go under the name of Quakers,
and are not in the life.
That justice, judgment, and righteousness may flow as a river, and as a stream,
and drive away all the filth from among us; that nothing but the power of God,
and the life of truth, may rule amongst us; that the living God,
which hath blessed you with his heavenly riches and mercies,
and largely manifested them among you, may be in all things honoured, magnified,
and exalted.
To whom all belongs, God over all, blessed forever.
So that every one may adorn the truth, and the gospel,
and mind the Lord`'s business above their own.
And every one be tender of the glory of God, and be careful,
that in nowise his name and truth be dishonoured.

G+++.+++ F.

So let this be read in all your men and women`'s meetings,
who are to take notice of all such things.
So no more, but my love in the universal seed of God, which never sinned,
which is first and last, the top and corner-stone.

[.centered]
=== Letter 252.

[.blurb]
==== To Friends in the ministry, scattered abroad in Virginia, Maryland, New England, Barbados, and other plantations beyond the sea.

To all you that minister abroad in those parts, this is the word of the Lord to you all:
live in lowliness of mind, and meekness of spirit, and pureness of heart,
and be examples in your lives, and chaste in your conversations, in holiness of mind,
that you may be a good savour amongst the people where you come.
Let all ungracious, light, unseasoned expressions, be kept out of your minds and mouths,
which edify not the new life; and keep single unto God, and single-hearted to man,
and plain in all things, and low.
For it is the word of the Lord, and the light of God,
that prophesieth and revealeth the dispensation of the gospel of Christ unto people.
Be ye faithful in it, and walk answerable to it,
and to that holy gift or manifestation of prophecy.
And let none be lifted up with it, for life brings low, and down,
as you are kept in the holiness of it, and the wisdom of God;
through which you answer that of God in all.
This doth not hinder the effect of that which you have to minister;
but the life is opened to receive it,
in walking and answering that which you have to minister;
though the contrary part may rise up against you.
Be at unity amongst yourselves, that you may not make sects nor schisms,
nor stumble the weak.
For you know that cursed spirit that made rents and
got into the affections and uppermost part of people,
hath buried the witness of God in many, and made open rents,
(which may break also into other ages against truth,
and them that live in it,) which in time will wither and fade away,
as grass upon the house top, and their arrows will turn into their own bowels,
that are shot against the righteous, both of the professor and profane.
And so be valiant for the truth upon the earth,
abhorring all uncleanness and unrighteousness,
flying all youthful ways and fond affections below, being kept above them,
showing the new life to them that be in the old,
and a new conversation to them that be in the vain, and gentleness to all the perverse,
and straightness to all the crooked, and plainness to all the rough,
and lowliness to all the mountains of ungodliness and unrighteousness;
for the Lamb must have the victory.
And so you may be one another`'s crown, joy and rejoicing in the Lord:
and not one another`'s sorrow and grief.
And so, that all may be brought to the witness of God,
(which first convinced them,) who have run out, and to the life to answer it;
through which you may come to have unity with God,
and with them in the eternal and everlasting life.
And some of you should take some of the eminent, true, good, and upright Friends,
and go and discourse with some of the heathen kings,
desiring them to gather their council and people together,
that you may declare God`'s everlasting truth,
and his everlasting way of life and salvation to them,
knowing that Christ is the promise of God to them, a covenant of light to the Gentiles,
(which is the heathen,) who is also the new covenant to the Jews;
for you have been amongst the old, rotten-hearted professors,
and seen the power of the Lord come over them.
So, now turn to the Gentiles, to whom Christ is given for a covenant of light,
and of salvation, to the ends of the earth.
So that the light must be preached and sounded throughout
all the heathen kings and princes`' countries;
and therefore, as you feel and are moved, about six or more persons,
living in those parts near unto them, to go with you, as I said,
and desire the king to gather his council and subjects together,
that they may hear that which hath been promised to them,
God`'s everlasting covenant of light, and life, and salvation, to the ends of the earth.
And so, be faithful in his power, which was before the devil was;
who hath darkened people, and set them one against another.
You having on the armour of light, which was before the power of darkness,
(and which must stand against them,) and having on the breast-plate of righteousness,
that you may stand against all unrighteousness, and the shield of faith,
the helmet of salvation, and the sword of the spirit, which is the word of God,
which was before the world was; through which you may savour and discern in wisdom,
and in understanding you may judge,
and feel by the word of reconciliation committed to God`'s servants, his sons,
and his daughters; which word of faith is now preached,
even the same which was amongst the apostles; which all must obey and do;
which reconciles to God, and to just men`'s spirits, and to one another.
So no more, but my love to you all in the everlasting seed of God that never changeth.
For the word is the same now as it was in the beginning, in ages past,
manifested over all; which many thousands have received.
Glory and blessing to the Lord God forever.
So be faithful, that you may be one another`'s crown, and rejoicing in the Lord,
going together in the love and fear of the Lord.

For Friends in Maryland were a pretty people: and Friends,
you have had large experience of that spirit that run into the hat,
that it was not of God, which scatters to the world,
(and begot none to God,) which is to be bruised by the seed of God, Christ Jesus,
which gathers to God.

G+++.+++ F.

London, the 1st of the 7th month, 1667.

[.centered]
=== Letter 253.

[.blurb]
==== To Friends in Holland.

Dear friends,

In the everlasting power of the Lord God I salute all the faithful and upright,
among whom the Lord hath joy and delight;
in which everlasting power of God have you your unity, fellowship, and dominion.
And so friends, all sufferings of Friends, of what sort soever,
for conscience sake to Christ, in Holland, in Germany, in Zealand, in Gilderland,
in the Palatinate, in Freezland, Sweedland, Switzerland, and Hamburg,
send an account for what they have suffered, and by whom;
together with the examples that are fallen upon the persecutors;
with their mittimusses and examinations, send all these to London, to Friends there;
that if any ambassadors or agents, out of any of those places, come to London,
Friends may make application to them; for there are some Friends,
who are ordered for the same purpose, to take knowledge of such things.
And likewise, if any Friends have come over into those parts of the world,
and have not walked answerable to the gospel of truth,
but have walked scandalously and disorderly;
whether they have been such who have come over to minister, or seamen, and factors,
or merchants, or masters of ships, whereby the Lord God hath been dishonoured,
and his holy name blasphemed, by which his people are called.
And also all such who have not been faithful in their callings between man and man,
but have been deceitful in their callings, and have been exacters,
and have not been true to their word;
by such doings they cause the holy name of the Lord God, and his righteous truth,
to be evil spoken of.
That a list of all such may be gathered up, and sent over to London,
to such who are to receive them; and that if they condemn those things,
and have given forth a paper of condemnation against them, if so,
that we may have a copy of it also,
to take away the reproach of their transgressions from Friends.

And let the faithful Friends amongst you meet together,
to consider and take care about these things.

G+++.+++ F.
