== Letters 254 &#8212; 264

[.centered]
=== Letter 254.

Friends, let your affections be set on things that are above;
for if they be on things below, then your minds, bodies, souls, and spirits,
will be brought into bondage, and in that the evil will get into you and burden you,
which ought to be kept down by the seed of life:
and learn the true humility of Christ the second Adam.
And so all they that watch for the soul, must have the immortal eye;
for the soul is immortal: and therefore all eyes must be kept above that which is mortal,
and out of it up to the immortal God, whose dwelling is in the light.
And so mind the gospel, which is immortal,
and the government of him that never sinned nor fell,
and to know the increase of it daily, which hath no end.
For the Lord is establishing his church in righteousness and truth,
whose church is without spot, wrinkle, and blemish, or any such thing;
and his people are a holy generation, and they are to stand up for holiness,
in which holiness they will see God among them:
and let every one see that they do keep their own vineyard clean.

Dear friends, mind the gospel, which is the power of God,
that was before the devil and old Adam were; in this power is the comely order;
and out of this power is all the uncomely orders.
And so know the government of Christ, and the increase thereof, which hath no end:
and this governor and government was before the devil and old Adam was,
and will stand when all that is gone.

G+++.+++ F.

[.centered]
=== Letter 255.

Dear Friends, all who from the beginning have been convinced of God`'s truth,
and are turned to the world, or gone into drunkenness, swearing, pleasure, and looseness,
or to the old mass-house, or have sold the truth for a wife or husband,
and gone to the priests covertly to be married,
contrary to the truth they have professed:
these all must be admonished to come to the light that did first convince them,
and give forth a paper of condemnation, and send it to the priests,
and to those places where they have dishonoured God, his truth and people.
And so to clear the truth, that none may make a jest of their transgressions;
and by walking out of the truth, cause the blind to wander:
so that the house may be swept, and ye being a holy generation,
may stand up for holiness in your generation,
as the wicked world stands up for unholiness.

G+++.+++ F.

Surrey, the 10th of the 7th month, 1668.

[.centered]
=== Letter 256.

My dear friends,

Live in the wisdom of God, which is gentle and pure from above, and easy to be entreated;
all "`bear one another`'s burdens, and so fulfill the law of Christ.`"
And if any weakness should appear in any in your meetings,
not for any to lay it open and tell it abroad, that is not wisdom that doth so;
for love covereth a multitude of sins, and love preserves and edifies the body;
and he that dwells in love dwells in God; for God is love,
and love is not easily provoked; and therefore keep the law of love,
to keep down that which is so provoked; for that which is easily provoked hath words,
which are for condemnation.
Therefore, let the law of love be amongst you, which is not easily provoked;
and this law of love being amongst you, it will keep down that which is so provoked,
and its words; and so the body edifies itself in love.

G+++.+++ F.

[.centered]
=== Letter 257.

Dear friends.

Be faithful in the service of God, and mind the Lord`'s business, and be diligent,
so will the power of the Lord be brought over all those that have gainsayed it.
And all ye that are faithful, go to visit them that have been convinced,
from house to house, that if it be possible ye may not leave a hoof in Egypt.
And so, every one go seek the lost sheep, and bring him home on your backs to the fold,
and there will be more joy of that one sheep than the ninety and nine in the fold.

And, friends, all take heed of sleeping in meetings, and sottishness, and dulness;
for it is an unsavoury thing to see one sit nodding in a meeting,
and so to lose the sense of the Lord.
And it is a shame and a sadness both, and it grieveth the upright and watchful,
that wait upon the Lord, to see such things; and for the priests, people, and others,
that come into your meetings, and see you that come together to worship God,
and to meet together to wait upon him, and to have fellowship in his spirit,
for you to sit nodding, it is a shame and an unseemly thing.
Therefore be careful and watchful, and let it be mended;
and mind the light and power of Christ Jesus in you,
and that will condemn all such things, and lead you out of, and above, such things,
and make you watchful one over another for your good.

G+++.+++ F.

Let this be read in all your meetings.

[.centered]
=== Letter 258.

Dear friends,

In the truth of God that changeth not, is my love to you,
in that which is unfeigned and everlasting, in the same power,
and the same seed of life as ever was, and was at the first going forth among you.
And so friends,
the Lord in his everlasting and mighty power hath moved some to go over
in those parts to declare his word of life and everlasting gospel.
And some have not walked afterwards as becometh the gospel,
both them that have declared it, and them who have received it;
whereby there hath been a stop to the progress of the truth and power of God,
that it hath not had its full course; and by that,
burdens have been brought upon the just and innocent, and the mouths of the world,
instead of stopping them,
they have opened them to speak evil of the truth and way of God.
And so, friends, this is the thing in short and plainness,
all that have come over into your plantations, and islands, either to minister or plant,
or as passengers to see the country, or seamen; masters of ships, factors, or merchants,
that have dishonoured the Lord God and his truth,
and have opened the mouths of the world to blaspheme God,
and to speak evil of his way and holy truth that the righteous live in: such, I say,
before mentioned, that have gotten into drunkenness, or looseness in words and life,
and have not been faithful in their dealings, or have showed any immodest carriages,
or are gotten up into those things which the power of God did not set up in the beginning,
(which faithful Friends have continued in,) and have gone into sects and jangles,
which is out of the power of God which Friends are in,
who keep their habitations in Christ Jesus, in whom there is peace.
And all such likewise, who are gone into uncleanness,
and such who pretend to preach the gospel, and are sat down in the earth, like Demas,
and have forsaken the gift of God, and sit down in the earth,
and esteem the earth before it; and so set up their own business,
and slight the Lord`'s. And such who are gotten into the rotten principles of the Ranters,
who wear their hats when Friends pray; who, out of the wisdom of God,
would manifest to the world a separation, and to show that they are not of the spirit,
power, and mind, as Friends were in at the first.
As also, all such that raise false reports,
which are forbidden by the Lord among his people.
These things are to be searched out to the bottom, that righteousness and truth may flow,
and have its passage through all hearts,
and all may come to the habitation which they had at the first;
and all that is contrary may come to judgment and condemnation.
For the house must be swept and cleansed of all the
things above mentioned that have gotten into any,
that all may come up into the sanctified life; for the Ancient of days is come,
and the judgment is set, and they that have kept their habitations witness this.
And therefore, friends, this is my advice to you,
I would have you to gather up a list of all these things aforementioned,
in all your islands and plantations, let them be searched thoroughly,
that what is for judgment and condemnation may be brought to it,
and that you may send an account to Friends at London of such that come from thence,
that have been since scandalous in their conversations.
So that every one may come to that which did at first convince them,
and to condemn their contrary actions.
And that papers may be sent to the world, who have known their transgressions,
to clear truth and Friends, and to fetch it out of their mouths;
that so they may not feed upon any one`'s transgressions;
that the miscarriages of some may not be charged on the body of Friends.

G+++.+++ F.

[.centered]
=== Letter 259.

My dear friends,

Be faithful in the truth which the devil is out of;
in which truth you have dominion over him; And live in the power of God,
which was before the devil was; in which power of God, which is the gospel,
is your fellowship.
And live in the light, which was before darkness was, and the power of it:
in which light is also your everlasting fellowship;
and in this you will know God`'s dwelling, which is in the light.
And dwell in the life, which was before death was, and the devil, the power of it;
and in this life you will have dominion over death and the power of it.
And so you do well that take heed to the light, and walk in it;
and they that do evil do not take heed to the light.
And so walk in the light, as children of the light,
and that ye will have fellowship one with another, and with the son and the Father.
And so mind the ingrafted word, which is able to save your souls;
and that will keep your eyes and minds over all that which is not able to save,
and keep your feet on the top of that.
And so be of that good faith which gives you victory and access to God,
in which you do all please God, and have unity one with another.
And so mind the seed of Christ, which is over all that which makes to suffer,
and was before that was, and will stand when that is gone that makes to suffer;
in that seed live, and know it your crown and life,
and in that you will be one another`'s crown and joy in the Lord God blessed forever.
And so keep your meetings in the name and power of the Lord Jesus Christ that never fell;
and the seed Christ reigns, in whom you have life,
that was with the Father before the world began.

G+++.+++ F.

[.centered]
=== Letter 260.

Dear Friends,

If the truth make you free, then are ye free indeed.
So then there are none made freemen, but by truth; and all that are freemen,
they are made free by the truth, they are God`'s freemen; they are free citizens,
they are freeholders of an everlasting inheritance, and free in an everlasting kingdom;
and they are free heirs of salvation;
and they are free in the heavenly city Jerusalem which is from above;
and they are free in the power of an endless life, which was before death was.
So they are not captives, they are not bondmen, they are not servants, nor slaves.
But (mark) free men and free women.
And what hath made them free men, and free women, but truth?
For if the truth hath made you free, then are you free indeed.
So, free to worship God in the spirit and in truth,
(which the devil is out of,) to serve the Lord God in the spirit and in the new life.
They are above the serpent, and from under his control;
and from under the control of old Adam, and his beggarly rudiments, and will-worships,
and false righteousness.
Truth makes free from all these; and makes free to be partakers of Christ Jesus,
and of his blood, and his spirit, and mind; who is the prince of peace,
and prince of life;
and makes free to be partakers of the divine nature and precious faith;
and to be members of the true church, and gospel fellowship, and power of God,
which was before the devil was.
So stand, fast in the liberty wherewith Christ hath made you free, free from the devil,
dragon, and serpent, and all slavery and servitude.
For free men do walk in their freedom; for it is the truth makes them free,
and so to triumph in glory.
And so, if the truth have made you free, then are you free indeed;
free from all the will-worships, and from all the windy doctrines;
from all the evil inventions, traditions, imaginations, and notions,
and rudiments of Adam in the fall, who are from truth; and free from the devil,
who is out of truth.
So, it is plain, none are free but by the truth, and all in the truth are free men.
And all out of the truth, are slaves in old Adam, and slaves to sin and Satan,
and to his will-worship, and to their own self-righteousness, and to their rudiments,
doctrines, and traditions; serving divers lusts, pleasures, and corruptions,
and serving the creatures more than the Creator, who is God blessed forever,
and serving the desires of their own minds; and so as slaves are kept in bondage;
all in prison all in the bonds of death and jaws of death;
for who are out of truth are no free men.
Though they be high priests, and readers, preachers, and expounders,
as the great high priests, and the lofty Pharisees and scribes were,
professing the scriptures, yet not in the truth, and so not freemen.
For they are in malice and envy, like Cain; oppressors, like Pharaoh; raging persecutors,
like Nebuchadnezzar and the Jews; as wild as Ishmael, as profane as Esau;
out of the truth are all those found, fasting to smite with fists of wickedness,
lifting up bloody hands, mingling their sacrifices with the blood of the persecuted,
praying to the magistrates for persecution.
All this is out of truth, and not in the freedom; so not free men,
but doing the devil`'s lusts and service, as the Jews did.
And so, if the truth make you free, ye are free indeed;
ye are free from all those things above mentioned.
The truth makes free from envy, and from profaneness, and from wildness,
and from wickedness, and from the bloody hands.
Free from the fasts of those that hang down their heads like a bulrush,
free from the persecuting spirits, free from the false prophets, deceivers, seducers,
antichrists; and all antichristian false prophets, deceivers, and seducers,
are Satan`'s bondslaves, vassals and bondmen;
and being with his oars chained in his galas, they carry his wares,
and do his work up and down the world; which is the sea.
But truth makes free from all these, free from the hypocrite`'s hope, which perisheth;
free from Nebuchadnezzar`'s fury.
And it makes free from the wild heifer`'s nature, and from the dog, swine, horse, viper,
cockatrice, serpent`'s nature, and from the spider, and his web;
and from the oak and cedar, and the bramble and briar, and bear, and lion.
The truth makes free from all these, and brings man and woman into the image of God.
And so, if the truth makes you free, then are you free indeed.
And the truth is Christ, and Christ is the truth,
which makes you free from all falsehood, and makes you free from the world,
which lies in wickedness and unrighteousness;
by which you come to be free men of the world which hath no end.

"`And a highway shall be there, and a way, and it shall be called the way of holiness;
the unclean shall not pass over it.`"
Mark, "`the unclean shall not pass over it.`"
This way, which is called the way of holiness, was spoken of by prophecy;
and this way is Christ, who is the way of holiness, who is above the unclean,
and destroys it, and the ground of it, the devil;
and so the unclean cannot pass over this way of holiness.
This is our way, who are in scorn called Quakers, to wit, Christ.
And this way of holiness shall be for the way-faring men, though fools,
yet they shall not err therein; where no lion, nor ravenous beast,
nor lion`'s whelp shall go thereon.
All the ravenous beasts are without, in the way of the world, without Christ and God.
But the redeemed, shall walk in this way of holiness, Christ Jesus;
and the ransomed of the Lord shall walk in this way of holiness;
and they that do return from the way of the world to Zion,
shall walk in this way of holiness with singing and everlasting joy upon their heads.
And they that walk in this way of holiness, Christ Jesus, shall obtain joy and gladness;
and sorrow and sighing shall flee away.
And all that walk in this way of holiness, their deaf ear is unstopped,
and their blind eye is opened.
And the lame man here shall leap as a hart, and the dumb man`'s tongue shall sing.
And here he shall see waters gush out of the rock, and streams out of the desert,
in this way of holiness.
And here he shall see in this way the parched ground become a pool,
and the thirsty land full of springs; and in the habitation, where dragons lay,
shall be grass with reeds and rushes, which begin to spring.
Glory be to the Lord forever.
And this way of holiness, which the prophets prophesied of, is Christ Jesus, the way,
who said of himself, I am the way; and he is over all the fallen ways,
and before the way of the serpent; glorified with the Father, before the world began.
And this is the way of the wayfaring men,
who have been way-faring up and down from religion to religion, from worship to worship,
from one people to another, from one minister and teacher to another,
and could not sit down in any of their ways, but way-fared, travelled and sought.
And now, glory be to the Lord forever,
thousands of these way-faring men are come to find their way, Christ Jesus, and,
though fools, yet shall not err therein; that is, they shall not err in their way.
They shall not err in Christ Jesus, for there is no error in him,
for he was before error was; for Christ the way, destroys the devil and his works,
the ground of all error.
So though they be called fools, (these way-faring men,) by all the sons of Adam,
that are set down in their own rudiments,
and have persecuted these way-faring men as fools,
because they would not sit down with them in their rudiments, worships,
self-righteousness, and national church, which national powers have established;
yet those way-faring men walk on in their way, Christ Jesus, where, though fools,
yet they shall not err in the way, Christ Jesus,
though they be called fools by all the sons of Adam,
who are in their own ways and rudiments; yet those fools shall not err in the way,
Christ Jesus, though counted fools for Christ`'s sake.
And they see how all the wise men in old Adam mixed with the wisdom of the serpent,
how they are all in their own ways, worships, and religions; and all the sects in it,
how they are like tradesmen, plucking from one church to another, and getting customers,
and drawing people from one another`'s church to their own ways;
and tearing one another to pieces,
to get people from one another`'s church to themselves.
And so are like lions, and ravenous beasts one against another,
to get from one another`'s church to maintain themselves;
and thus they seek the people`'s, not the people; and feed themselves, and not the flock;
for they are out of the way Christ, and sit down in their own ways.
But, for the way-faring man, the way of holiness is; for him,
that is way-faring and seeking up and down for his beloved.
"`I sought my beloved by night, and the watchmen smote me.`"
Did not the way-faring man go to the Papists and say, You watchmen of the night,
did you see my beloved?
What is thy beloved more than another`'s beloved, said they.
What is thy religion, more than another`'s religion?
Or thy profession, more than another`'s profession?
So the Papists smote and wounded the way-faring men.
The way-faring man did not ask the Papists for their beloved;
for the Papists had a beloved, a mass-book; but he asked them for his own beloved,
Christ Jesus.

Well, the next watchmen were the Common-prayer-men of every parish.
The way-faring man went to those watchmen of the night, and said, did ye see my beloved?
They stormed at the way-faring man, and said,
what is thy beloved more than another`'s beloved,
and thy religion more than another`'s religion.
They smote him, and wounded him also.

Well, the next watchmen of the night were the Presbyterians;
they were also the watchmen of some people, the way-faring man went to them, and said,
ye watchmen of the night, did ye see my beloved?
And they were exceeding angry, and said,
what is thy beloved more than another`'s beloved,
and what is thy religion more than another`'s religion?
He did not ask them for their beloved; for he knew they had a beloved, their directory.
And these watchmen smote the way-faring men, and punished some,
spoiled some of their goods, and killed some,
(as some at New England,) because they would not follow their beloved,
as the Papists and others had done before them.

The next watchmen were the Independents and Baptists,
the wayfaring man went to them also; for they were the watchmen of some people,
and said unto them, ye watchmen of the night, did ye see my beloved?
And these watchmen of the night were also exceeding angry, and said,
what is thy beloved more than another`'s beloved, and thy way more than another`'s way,
and thy religion more than another`'s. And these watchmen of the night smote cruelly.

Then the way-faring men went to the private meetings of the Manifestarians and Seekers;
and these watchmen fell a mocking, and scoffing, and railing,
and smiting with the tongue, and thrust them out of their meetings.
And when it was asked them, if they saw the wayfaring man`'s beloved?
They scoffed at their beloved.
And so the way-faring men way-fared up and down from
watchman to watchman to seek their beloved;
and many were imprisoned and persecuted by some of these watchmen of the night.
And now, glory forever be to the Lord,
thousands of these way-faring men have found their beloved, and have found their way,
Christ Jesus, and a fool shall not err therein; for there is no error in Christ Jesus,
all the error is out of Christ, who is the way, wherein the way-faring men,
though counted fools, yet shall not err.
And now my beloved is mine, and I am his; we are come to the banquetting house,
and his banner over us is love.
And the watchmen of the night told the way-faring men, that there was not any way,
but there was error in it; and that all the religions, and worships, and churches erred.
And so the way-faring men way-fared up and down to find the way of holiness.
For all the ravenous beasts, and the lions`' whelps trod in the way of error.
And all those night watchmen were among the ravenous beasts and the lions`' whelps;
and so neither the watchmen nor ravenous beasts could pass over this way of holiness,
nor enter into it, which is the way for the way-faring men, the way of holiness,
where the fools shall not err; which fools, all the wise men in old Adam,
and the serpent`'s error, cannot see, nor their ground,
nor how they err in their own ways.
And this is the eye which the wayfaring man hath opened in him, who sees his beloved.
And the way where the fools shall not err in.
And all shall come to this way of holiness, in which the fools shall not err,
which is the way of the way-faring men, into which all must come;
and out of the way of the serpent, and out of the way of old Adam in the fall.

And did not you watchmen of the night tell the way-faring men,
that the scriptures were not truly translated that speak of a way of holiness,
and a "`way that the way-faring men, though fools, should not err therein?`"
For ye watchmen of the night could not see this way of holiness: for, do you not say,
that a fool will err in everything he doth?
And was it possible there should be a way wherein the fool should not err?
for you said, the wisest man that was, sinned:
and here have not you wise men of old Adam manifested your
error and ignorance of the scriptures and the way of holiness,
which is the way-faring man`'s way: for all error is in your own way,
and there is no error in Christ, the way of holiness;
for way-faring men and the fools shall not err therein; that is to say,
they shall not err in Christ Jesus; for he was before error was,
and destroyeth the ground of it.

The outward Jew worshipped in his outward temple made with hands, at outward Jerusalem,
and they came up yearly to worship there;
and if they did not come up to worship at outward Jerusalem,
and keep the feast of tabernacles in the temple, upon them should be no rain;
and their eyes were to rot out of their heads, and their tongues out of their mouths,
that fought against Jerusalem,
as in Zechariah 14:12. So the outward Jew had but one temple in the whole world,
and there they went to worship in it; and the priest had a chamber in the temple.
And when Christ came, he ended the priesthood, he ended the offerings, and the temple,
and the worship therein of the outward Jews;
and set up another worship in the spirit and in the truth: for when the woman of Samaria,
that came to Jacob`'s well, said unto Christ,
how that our fathers worshipped in this mountain, where Jacob`'s well was,
and the well was made before Jerusalem was, or the temple either;
for Jacob died in Egypt, and afterward his sons came out of Egypt,
and builded a temple in Jerusalem;
and so there they set up a place of worship after the well was made:
so Christ said unto the woman, "`The hour is coming, and now is,
that they that worship the Father must worship him
in spirit and truth;`" and not at Jerusalem,
nor at this mountain is God worshipped; "`For God is a spirit, and they that worship him,
must worship him in the spirit and in the truth:`" and then did Christ set up his worship,
which was before the pope`'s, Turks`', Common-prayer, Presbyterian, Independent,
and other worships were; and the worship that Christ Jesus set up,
was in the spirit and in the truth.
Now where is this spirit, and where is this truth?
Is it not within people?
So, as the Jew outward was to worship in the temple,
and there was but that one temple commanded of God to be built, which Christ came to end,
who set up his worship in the spirit and in the truth.
So seeing the true worship is in the spirit and in the truth,
and the truth is within you, in the inward parts, the spirit of God is within you,
you must not grieve, vex, nor quench it.
And so every man and woman in the whole world must
come to the spirit and truth in their own hearts,
by which they must know the God of truth, who is a spirit,
and to feel the spirit in their own hearts,
and in the spirit of truth to worship the God of truth, who is a spirit.

So now, as the Jew outward was to offer his sacrifice in the outward temple,
and no where else, which temple is now thrown down, he is not a Jew who is one outward,
but he is a Jew who is one inward, in the spirit and in the truth; and so,
all ye Jews inward, in the spirit, ye must worship in the truth and in the spirit.
And so, the Jew inward can worship no where but in the temple.
What temple?
It is not a temple that is made with hands.
The Jews outward worshipped in the temple that was made with hands;
but the Jew inward his worship is to be in the spirit, and in the truth,
and in a temple not made with hands.
So to worship in the spirit, and in the truth, is to worship in the temple,
and no where else.
And so, every man and woman in the whole world must worship in the temple.
What temple?
The temple that is not made with hands; where the spirit of truth is.
"`Know ye not, that your bodies are the temples of the holy ghost;`" that is to say,
the holy spirit: and so,
every man and woman must be brought to truth in their own hearts,
and brought to the spirit of God in their own hearts.
This is the standing and perfect worship,
and it will stand when all the worships of old Adam are gone, and when the Jews`',
and Turks`', and Christians`' worships, that be not in the truth, are gone:
for this is a standing and perfect worship; the spirit of God is perfect.
And this is an universal worship,
and brings every individual man and woman to the spirit of God in their own hearts.
This makes no sect, but every one in the spirit, which is the bond of peace,
is in the truth, which the enmity is out of:
and this spiritual worship is in the spirit and truth, Christ Jesus, the spiritual man,
the heavenly man, which the second Adam,
the Lord from heaven set up above sixteen hundred years since.
And so, every one is to be in it, and to walk in the truth, and in the spirit,
and to come to the truth in their own particulars.
For that spirit makes sects, which persecutes people for not following them;
but they are all to worship in that spiritual worship, which Christ Jesus set up;
and every son and daughter of Adam is to come to the truth and spirit in their own hearts;
and so in that spirit and truth to worship the God of truth, who is a spirit;
for he seeketh such to worship him.
And Christ persecuted none for not following his worship;
but all are condemned by the spirit in their own selves, who grieve it,
and vex and quench it, and all are condemned with the light and truth that hate it,
who will not come to it, but hate it.
So they all that persecute about religion run into heaps, and sects, and darkness,
and are with the light condemned.
And so none can worship the God of truth, but who come to the truth in their own hearts;
and none can worship God, who is a spirit,
but who come to the spirit of God in their own hearts, which mortifies sin and evil;
which spirit leads into all truth.
So every one who is a Jew inward must worship in the spirit and truth;
and every one must be brought to the temple which is not made with hands,
and to worship in the spirit, which Christ set up, who is the spiritual man.
Carnal men may set up worships, who have not the same spirit and power the apostles had.
And such lead people into sects and heaps, and lead people, out of the spirit,
and persecute one another about their worships, which is not the way of truth,
nor the command of Christ, but on the contrary, "`to love one another.`"
So all that worship in the spirit and truth,
come to the spirit and truth in their own hearts, and love one another, and love enemies.
And so, the outward Jews`' priests had chambers in the temple, which priests, chambers,
and temple, Christ hath ended, so let Christ Jesus now have a chamber in your temple,
to sanctify your temple, and cleanse your temple,
that the glory of the Lord may fill your temple.
The Jews`' priests were to cleanse the temple,
and when they had cast the rubbish out of it, the glory of the Lord filled their temple:
and so Christ, as I said before, hath ended the Jews`' priests`' chambers and temple.
And so all ye who are Jews inward in the spirit,
let Christ your priest have a chamber in your temple, that he may cleanse your temple,
and cast the rubbish out of it, which is come in by transgression,
who doth renew you up into the image of God, that Adam and Eve were in before they fell;
so that the glory of the Lord may fill your temple.
And so as the Jew outward had but one temple to worship in,
the Jews inward must not have two; for then they make a sect,
and go from truth in their own hearts, and from the spirit of God.
And so to worship in the truth and in the spirit, is to worship in the temple.
So every man and woman come to this one temple.
Where is this one temple?
Where the spirit is in the heart, and the truth in the inward parts:
and this is the temple that is not made with hands;
"`do you not know that your bodies are the temples of the holy ghost?`"
And so this is the true worship that Christ set up, in the spirit and in the truth;
every man and woman in the whole world must come to it, the truth in their own hearts,
that by it they may know the truth, and the God of truth.
And by the spirit they may know God, who is a spirit,
and so worship him in the spirit and in the truth;
and this is the standing universal worship, that Christ the second Adam,
the Lord from heaven, the spiritual man, set up above sixteen hundred years since,
John 4. when he denied the mountain worship, where Jacob`'s well was,
and the temple worship of the outward Jews at Jerusalem,
where they went to the outward temple yearly to worship.
And so all are to worship in the spirit,
and come to the spirit and truth in their own hearts;
and in that to worship the God of truth, who is a spirit, as Christ commanded.
And so by the spirit of truth, they come to Jerusalem, which is above,
which cometh down out of heaven from God.
So this is a true, certain, standing, infallible, and perfect worship;
for truth and the spirit of God are certain, infallible, and perfect;
and so this worship is a certain perfect worship.
And so every one, as I said before, come to the truth in your own hearts,
and to the spirit of God, or else you cannot worship the God of truth, who is a spirit:
and every man that worships in the whole world, who would find this spirit and truth,
they must go into the temple.

And so in the spirit and truth worship God, who is a spirit;
and this spirit gives an understanding to know God, who is a spirit; and the truth,
and to know the God of truth, who is to be worshipped in the spirit and truth,
who is God blessed forever.
Amen.

G+++.+++ F.

[.centered]
=== Letter 261.

Friends,

To call men "`masters`" or "`gracious lord,`" and putting off the hat to them,
and the man`'s scraping with his foot, and the woman`'s making a courtesy.
These titles and fashions not giving and observing, doth not break the law of Christ,
nor of God, which respects no man`'s person,
but they are the customs of nations which are vain;
and the great manners and civilities that lie among Christians,
are in saying you to one man, and the man`'s putting off his hat,
and scraping with his foot, and the woman`'s bending her knees;
and in these and such like things lie their civilities, their honour, and manners,
and well-breeding, as they call it.
But the right manners are to keep people from evil words, which corrupt good manners,
and God`'s law; and Christ respects no man`'s person.
And man and woman in their not doing, nor scraping, and bowing, are not unmannerly,
nor uncivil; for man was forbidden by the angel to bow to him, but to bow to God,
and to worship him, and to bow at the name of Jesus, who is called, the power of God,
and the word of God; for the angel said to John, he was his fellow servant.
So servants were not to bow one to another; and if they do,
is it not reproved by the angel, and reproved by Christ,
the seeking honour one of another?
For "`how can you believe,`" saith Christ, "`that receive honour one of another?`"
John 5. So it is a mark, that they are unbelievers, who receive honour one of another;
and they are like the Pharisees, that love the praise of men,
and are called of men master, and like the heathen,
that will be called "`gracious lords.`"
For, saith he, you are all brethren, and have one master and Lord, Christ Jesus,
and one Lord, who is the creator of all.
For all things were made subject to man, and man subject to God;
all creatures were to fear and dread man and woman,
but men and women were to fear and dread God.
So all christians are to have one heavenly spiritual head, Christ Jesus,
and heavenly spiritual master, and they all as brethren are to serve and worship him.
And the prophets and apostles thoued God and Christ, kings and princes,
and great men and women, as you may see in the scriptures,
and they were never offended at it.
And you never read in all the scriptures of any that feared God,
that were offended at any for saying thou to a single person,
and standing with their hats on, (unless it were the Pharisees,
that loved the praise of men,) as it is said in the book of Job,
"`If I give flattering titles to men, my maker would soon take me away.`"
And so all their flattering titles, and loving the praise of men,
and seeking honour one of another, comes from that ground that is out of truth,
in the image of the beast and the dragon, who will be worshipped;
but the angel would not be bowed down to by the servant of the Lord; he says,
God must be worshipped.
So they that worship the beast and the dragon, receive the mark from the dragon;
he brands them and marks them with his spirit,
(out of truth,) and then he receives honour from them,
and the vain glory they give to him; but they who are sealed with the spirit of promise,
have their Father`'s mark in their foreheads; these worship the living God,
and are in his image and his likeness, that he made them in in the beginning,
and in the spirit of Christ Jesus, and those are Christ`'s.

G+++.+++ F.

[.centered]
=== Letter 262.

All Friends and people, that is to be condemned in yourselves,
which hath led you from Christ, from God, and from unity in the light; I say,
that is condemned by the light, and must be executed and killed,
and stoned with the living stone, and run through with the living sword,
and hammered down with the living hammer to pieces, and burnt up with the living fire,
and so made an end of.
For that which leads into looseness, whimsies, imaginations, false visions,
though it be condemned, yet, if it be not executed, it is in danger to rise again;
and if it rise again, and get over you, it will be your ruler,
if it get out of prison and be alive, and not executed.
For after a thing is condemned, as drunkenness, adultery, fornication,
or any manner of looseness whatsoever, or runnings out from the spirit and light,
if it be condemned, and judgment passed upon it, if it be not executed,
there is danger of its reviving.
For after a thing is condemned, and judgment passed upon it, it is to be executed.
For you know, after a thief or a murderer is condemned and judged,
and have sentence passed upon him, yet he is not executed that day;
the execution comes afterwards.
And therefore, after condemnation or judgment is passed upon any inward evil,
or any outward action of evil, let execution be speedily done with the living hammer,
and the living sword, and the living stone;
that the living fire may burn it up and consume it.

No man after he hath beaten his child, hateth him ever afterwards, but loveth him,
if he repent and amend; so doth the eternal Father.
And if a child be fallen down into the dirt,
he doth not go and tumble him more into the dirt, or into the ditch,
and there let him lie in the dirt and ditch, but takes him out and washes him;
and so doth the heavenly Father, who leads his children by his hand,
and dandles them upon his knee.
And so, all that be called fathers in the truth, or mothers,
their tenderness should be the same to all little children in the truth,
that can hardly go without leading, that sometimes may fall into the dirt and ditch,
and slip aside, and then be troubled, and cry.
To such there should be tenderness shown, and to wash them, and help them;
and love to such should be manifest; for there is difference betwixt a stubborn,
rebellious, and wilful child, and one that is penitent;
for those must have great chastisements, that know the will of their Father,
and do it not; they must have greater stripes,
and sorer stripes they must look for (be sure to expect it) than the other.
For Christ is manifest in the flesh, to condemn sin in the flesh,
all that witness Christ in them, male and female; I say, Christ manifest in their flesh;
he doth condemn the sin that is in their flesh; yea, and makes an end of sin,
and finishes the transgression, and brings in everlasting righteousness into them.
But first he condemns the sin that is in their flesh, the unrighteousness in their flesh,
and ungodliness in their flesh; the liar, the swearer, that is in their flesh;
the adulterer, the fornicator, the idolater, and all sin, whatsoever it is,
he condemns in the flesh.
So Christ is manifest in the flesh, to condemn the sin that is in the flesh;
every one that witnesses Christ condemning sin in the flesh, that they through Christ,
that condemns sin in the flesh, might become God`'s righteousness;
so they become another`'s. But the sin being uncondemned in the flesh,
they are of the serpent, of the unrighteous one, of the ungodly one,
who adulterated from truth, they are his.
But the sin being condemned in the flesh, Christ is manifest in the flesh,
so that they become Christ`'s; they are God`'s, and are in Christ,
who destroys the devil and his works, that are out of truth.
And these know the new life, which God is served in; and these know the new earth,
wherein dwells righteousness; and these know the old earth,
wherein dwell unrighteousness.
And these can bring forth things new and old.

For they that are led by the spirit of God, are the sons of God;
they that are led by the spirit of the devil, are the children of the devil,
and his works they do, the works of their father;
as they that are led by the spirit of God, his works they do, the works of their father;
and all they that quench the spirit of God, and vex the spirit of God,
and grieve the spirit of God, and hate the light of Christ,
and walk despitefully against the spirit of grace, and turn it into wantonness,
and disobey the word of God in their hearts and mouths;
sure you all may see such are not the sons of God, and do not the works of God;
though they may profess the scriptures from the beginning of Genesis to the end of Revelations.
Neither doth that birth know the scriptures, for they are known by the spirit of God,
the holy ghost, which led the holy men of God to speak them forth;
by the same spirit are they known again.
And Christ, who was conceived by the holy ghost, born of the Virgin,
he is known by the holy ghost again,
which led the holy men of God to give forth scriptures; which now leads into all truth.
And all them now, who despise revelations, inspirations, prophecies, gifts, and talents,
they despise the spirit of God and his gifts.
Such are neither ministers of God, or Christ, nor his sons;
but are the sons of him that is out of the true spirit that is of God, in the darkness,
Babel, and confusion; who think they can do great matters with their languages,
and with them make a trade of the scriptures;
who cannot endure any people should come to the spirit that gave them forth;
for none can walk in the spirit that quench it, and vex and grieve it.
And none come into the church fellowship that grieve, and vex,
and quench the spirit of God.
For the fellowship is in the spirit, that is the bond of peace;
and none are led into all truth,
but by the same holy ghost that was in the holy men of God,
that gave forth the scriptures of truth.
And all that are led by this spirit of truth, are led from the spirit of the devil,
that is out of truth.
And all that are led by the spirit that is out of truth,
are the first birth of the flesh, and of that murderer,
who will persecute him that is born of the holy spirit of God,
which leads into all truth.
But they that are led by the spirit that is out of truth,
are out of both the Father and the son.
And they that are led by the spirit of truth, are the sons of God;
and here are both in the Father, and in the son, and in the truth, which abides forever.
And here the heir, the son, inherits his possession,
his inheritance in the kingdom that never hath an end.

The true hope, the true cross, the true faith, the true worship, the true religion,
the true way, true image, and true fellowship have been lost since the apostles`' days,
amongst those called christians, who are out of the life.
And they that have lost the cross of Christ, which is the power of God,
in which is the true fellowship, they have set up a wooden or a stone cross,
etc. so false crosses, false christians.
They that have lost the true hope, which purifies, as he is pure,
they have set up a purgatory to cleanse them when they are dead.
And others cry up a body of sin and death on this side of the grave,
with their hypocrite`'s hope; and they have lost the true ministry,
and set up a false one, to preach up imperfection.
And people were imperfect in old Adam before Christ came;
for the law made nothing perfect; but the true minister, Christ in you the hope of glory,
doth make perfect, both in the apostles`' days and now.
"`Christ in you, the hope of glory,`" said the apostle, "`whom we preach,
warning every man, that we may present every man perfect in Christ Jesus.`"
So the perfection is in Christ Jesus; the imperfection is in old Adam.
So this is the true hope that purifies, which every one that hath it purifies himself,
even as he is pure.
And every one that hath not a possession of this hope,
pleads for impurity and imperfection,
and a body of sin and a body of death unto their grave,
and a purgatory when they are dead.
Such have a profession of the scriptures, like the Pharisees;
and the hypocrite`'s hope which shall perish.

And the true faith hath been lost since the apostles`' days;
the true faith which purifies the heart, which is the faith of God`'s elect,
which faith gives victory over that which separates from God;
in which faith ye all please God; which faith is the gift of God,
and Christ is the author of it: every one look unto him for it, for the finishing of it,
who is the author of it.
In this faith have all the saints unity in that which gives victory over the devil;
for by the faith, which is the shield, do they resist him and quench his fiery darts;
and they resist him that would defile them and make them imperfect,
and lead them into those things which would displease God.
And all that are out of this faith, they cry, no victory while we are upon the earth;
but they must have a body of sin unto the grave, and a purgatory to cleanse them in;
these are all in the error concerning the faith;
these have made shipwreck of faith and a good conscience;
these are all in the dead faith,
and so cannot preach the true and living faith of God`'s elect.
These are all out of unity; for the unity is in the faith,
which gives victory over the devil.
These are out of the just life; which just lives by his faith.
The life that I now live, is by the faith of the son of God; yet it is not I,
but Christ that lives in me, said the apostle.
And all that walk in the faith of God`'s elect, which is the victory over the devil,
walk in unity over the enmity.

And the true worship hath been lost since the apostles`' days; yea,
the worship that Christ set up above sixteen hundred years since,
in the spirit and in the truth; yea, in the spirit of God,
which was before the spirit of the devil was, who is out of truth; and in the truth,
which the devil is out of.
In this spirit, and in this truth, God, who is a spirit, and the God of truth,
seeks that men should worship him in the truth;
and so every man and woman must come to truth in the inward parts,
and to the spirit of God within themselves,
if they be worshippers of God in the spirit and truth, which the devil abode not in.
And this is the standing and perfect worship, in which there is unity in the truth;
for the enmity is out of it, and he cannot get into it.
Glory be to God forever!
And men that have erred from the worship that Christ set up,
above sixteen hundred years since, they are from the truth within, and the spirit of God.
And by that unclean spirit they have worshipped images;
they have worshipped the works of their own hands; they have worshipped the dragon;
they have worshipped the beast; they have worshipped the creature;
they have worshipped angels, persecuted one another about their worships,
and they have persecuted the true worshippers.
These are in the blind zeal, who have hated the light.
And so none can worship God, who is a spirit,
but they must come to the truth in their inward parts,
and to the spirit of God in themselves;
by which spirit they must know God to be a spirit, and to worship him in the spirit.
They must know God to be the God of truth, and then worship him in the truth;
which the devil is out of, in the enmity, an adversary.
And this is the standing, perfect, infallible worship, that Christ Jesus, the perfect,
infallible man, set up above sixteen hundred years since.

And the true way is lost since the apostles`' days,
which Christ set up above sixteen hundred years since; who said,
"`I am the way to the Father; and no man cometh to the Father, but by me.`"
So no one comes out of old Adam, but by Christ, the second Adam.
No one comes out of darkness, but by Christ, the light; no one comes out of death,
and from under the prince of death, the power of it, but by Christ, the life.
So he is the way to God.
No one comes out of unrighteousness, but by Christ, the righteousness;
no one comes out of the wisdom below, but by Christ, who is the wisdom of God,
which is from above.
And no one comes out of error and evil, but by Christ, the truth.
So is he the door and the way to God Almighty.
And no man comes to the Father, but by him.
No one comes out of captivity or prison, but by Christ the heavenly man.
And so, they having erred from Christ, the way,
they have set up so many ways in Christendom among them;
and fall out about their ways one with another, enmity being among them.
Now Christ is the way, which the unclean cannot walk in,
who was before the unclean way was; for he is over all the unclean;
and he is over all the perverse and crooked ways, and mountainous ways,
and evil and unrighteous, and ungodly ways; he is over them all.
And none come to this new and living way, Christ Jesus,
but who come to the grace of God in their hearts; the spirit of God in their hearts.
So he is the new and the living way, who is the first and the last,
the beginning and the ending, set up from everlasting to everlasting.
And all that be out of this new and living way, though they have all the scriptures,
from the beginning of Genesis to the Revelations, yet they are dead,
and under the power of death; which Christ the way destroys, through death,
yea the power of death, the devil; and was before death and his power was.
Here is the new and the living way.

And the true religion hath been lost, and erred from since the apostles`' days.
The religion that is pure from above, and undefiled before God,
which keeps from the spots of the world, which is to visit the widows and the fatherless.
Now they that are out of this religion have made many religions,
but they are spotted and defiled, and they cry up a body of death, and sin,
and imperfection to the grave, and a purgatory when they are dead.
And their widows, and their fatherless,
and strangers go begging up and down their streets and highways;
so their streets and highways are judges against them and their bodies of death,
and their purgatories manifest their errors and ignorance from this pure religion,
that comes down from above, which is not of man`'s making; but comes down from God,
which is pure before God, and undefiled in his sight,
that keeps from the spots of the world.
(Mark, the spots.) And these do not cry up a body of death,
nor a purgatory when they are dead; they are kept from the spots of this world.
So they are far degenerated from this pure religion from above,
(which is undefiled before God, which keeps from the spots of this world,
and leads to visit the fatherless, widows, and strangers,) whose religion is,
that they must have a body of sin and death unto the grave,
and a purgatory when they are dead.
And their fatherless, and widows, and strangers must go a begging in the streets.
All these religions are from below, and of their own making, and not from above,
but of him that is out of truth.
And all they that come to this pure religion, that is from above, and come to receive it,
it must be by the spirit of God within, and the light of Christ within,
and his grace within, and his faith within.

And the image of God in them hath been lost since the apostles`' days,
that man and woman were renewed into by Christ;
and therefore they have set up so many inventions of their own brain, and outward images,
and likenesses, and worship them; for man and woman was in the image of God,
before they fell.
And when they fell from the image of God, they set up many images of God, and man,
and other creatures, of things in heaven and things in earth.
And when Christ came, he renewed man into the image of God again, and into his likeness;
but since the apostles`' days have they lost this image of God, and this likeness;
and made a profession of Christ and the apostles`' words, as the Jews did of the law,
and worshipped the works of their own hands, and images.
But now is Christ renewing man again into the image of God,
as they were in the apostles`' days; yea, also I say,
that Adam and Eve were in before they fell.
Yea, and in this image of God they will reign over all images and image-makers,
either with hand or brain;
for they have made those images and likenesses by the evil spirit, that is out of truth,
which the spirit of truth leads out of, and above them, and from their works.
Glory to God forever, for his image and his likeness is led into by Christ Jesus,
and into Adam and Eve`'s state before they fell; and not only into that state,
but into Christ Jesus that never fell.

And the true praying hath been lost since the apostles`' days; for none can pray truly,
but by the spirit of God, unto God, who is a spirit, or unto Christ,
who is a quickening spirit.
And all they that have erred from the spirit, cannot abide to hear talk of it;
and yet may have the scripture from Genesis to the Revelations, and make prayers,
and say them over, and give them to others to say over; and so pray by the book,
and that must help his infirmity; and so have erred from the spirit,
and from the true doctrine of the apostles, who said,
the spirit must help their infirmities; and they must pray in the spirit.
So all that grieve, and vex, and quench the spirit of God, cannot pray in it to God,
who is a spirit.
But they think to be heard by their much babbling, and ask and pray, but do not receive.
And every one must come to the spirit of God in themselves, and to the light,
and to the faith that purifies his heart, and to the spirit of grace and supplication;
and by this his mind is to be turned towards Christ, who prays to God,
and asks in the name of Jesus, and in the power, and light, and spirit of Christ.

And the true fellowship hath been lost, and sanctification, and belief,
and the righteousness since the apostles`' days.
For many have had the letter, but lost the life; the notion, but lost the possession;
the profession, but lost the substance, Christ Jesus:
but the true fellowship is in the gospel, the power of God,
which was before the devil was.
And since men lost this power of God they have not known the scriptures aright,
but they have set up fellowships by that spirit which is of him that is out of the truth,
that have destroyed one another, and persecuted them which are in the power of God,
which is the gospel, which was before the devil,
and all the fellowships in old Adam were, and will be when they are all gone.

Now the gospel fellowship is a perfect fellowship, a pure and a holy fellowship,
it is an everlasting fellowship; for the power of God is everlasting,
it is over the Jews`' fellowship in the outward things,
and the Gentiles`' invented fellowships, and the fellowships of bread, water, and wine;
for these are no mysteries, the world`'s fellowship is no mystery,
the fellowship of bread, water, and wine is no mystery;
but the gospel fellowship is a mystery, and none see it,
but who come to the light of Christ, and to the truth in the inward parts.
For this is a standing fellowship, the gospel, the power of God;
and all fellowships out of it are imperfect and corrupt, where the body of death,
and sin, and their purgatory are pleaded for, which fellowships below, men make,
and are of men, and from men; but the gospel is not of men, nor by men, but of God,
and from Christ.
So this fellowship is the church fellowship that is in God, and it is a pure fellowship,
the gospel fellowship is, which gospel brings life and immortality to light,
and expels away all that which darkens, and burdens, and loads the soul, mind, spirit,
and heart.
So this is glad tidings to the immortal soul,
which comes by the immortal power up to the immortal God,
where life and immortality comes to light, and to shine over him that hath darkened it.
Here is liberty to the immortal soul, mind, and spirit in the gospel, the power of God,
which is the gospel fellowship, which is a mystery,
(but bondage and darkness to the other,) so life and immortality
are hid from all them that make fellowships below,
and have their fellowships by men, and of men, who are out of the power of God,
the gospel; and make fellowships of old authors, and make fellowships of the scriptures.
But being erred from the spirit, they know not the scriptures, nor the power of God,
and there they are in strife and enmity in their fellowships,
and falling out about their bread and wine, some taking it one way, some another;
and falling out about their handiworks,
and plucking people from one another to themselves, and not to Christ,
nor his gospel fellowship, that came not by men, neither was it of man.
So they that deny revelation cannot preach Christ until he be revealed,
nor can preach the gospel until it be revealed.
And they that say revelations are ceased, they may as well say, there is no gospel;
and so have no Christ to preach, and are only ministers of the letter;
neither have they the secrets of God to preach, which are revealed to them that fear him.
And that is the spirit of darkness from the prince of darkness,
that is out of the fellowship of the gospel, where is enmity,
which speaks itself sufficiently abroad among all their fellowships;
and into this fellowship of the gospel, the power of God, which was before the devil was,
he cannot get.

And the righteousness hath been lost since the apostles`' days;
therefore people have been found in their own self-righteousness and unrighteousness;
and therefore they are all found out of peace with God, and with Christ,
and one with another; for where there is righteousness there is peace.

And sanctification hath been lost since the apostles`' days;
therefore both teachers and hearers are found in uncleanness,
and preach up the body of death, and sin, and a purgatory;
and so have forsaken him that should sanctify them, and make them clean.

And the sanctifying belief hath been lost since the apostles`' days;
for he that believes is born of God; and he that believes in the light,
may become a child of the light;
every one that cometh into the world are enlightened by Christ,
that they should believe in the light, as he commands them,
and so become children of the light; and he that believes, overcomes the world.
And if there be no overcoming on this side of the grave, as the world`'s preachers,
made of men, say, then there is no true believing on this side of the grave;
and therefore the world is not overcome in them; and he that is their God,
is of the world also.
For "`he that believes, overcomes the world; for greater is he that is in you,
than he that is in the world.`"
So this greater overcomes the less, and he that believes passes from death, and sin,
that brings death, and the devil the power of death:
so becomes a child of light and of the day;
and of the light which was before darkness was, or the prince of it;
for this is the belief that overcomes the world, that sanctifies the unbelieving husband,
and the unbelieving wife, else their children were unholy, but now they are clean. 1 Cor. 7:14.

For this belief is greater than he that is of the world,
which overcomes him that would defile; for this belief is Christ,
which passes from death to life, it takes away the root of sin and iniquity,
which is complained of in the scriptures, which they were born in,
though they had the law which made nothing perfect,
which took hold of their outward actions or branches;
but this belief makes the root holy, and if the root be holy,
the branches that spring from the root will be holy also.

And all you that preach up a body of sin and iniquity,
and that you must have a body of sin and death unto the grave,
and a purgatory when you are dead.
Neither man nor woman of you do believe aright;
for the believing wife sanctifies the unbelieving husband;
and the believing husband sanctifies the unbelieving wife;
else their children were unclean, but now they are holy.

So from this sanctifying belief you are all erred since the apostles`' days.
But have made beliefs and creeds of your own, and then say,
there is no overcoming on this side of the: grave: you may as well say,
there is no true belief.

G+++.+++ F.

[.centered]
=== Letter 263.

[.blurb]
==== An exhortation to keep to the ancient principles of truth.

Friends, keep at a word in all your dealings without oppression.

And keep to the sound language, thou to every one.

And keep your testimony against the world`'s vain fashions.

And keep your testimony against the hireling priests, and their tithes, and maintenance.

And against the old mass-houses, and the repairing of them.

And against the priests`' and the world`'s joining in marriages.

And your testimony against swearing, and the world`'s corrupt manners.

And against all looseness, pleasures, and profaneness whatsoever.

And against all the world`'s evil ways, vain worships, and religions,
and to stand up for God`'s.

And to see that restitution be made by every one, that hath done wrong to any.

And that all differences be made up speedily,
that they do not fly abroad to corrupt people`'s minds.

And that all reports be stopped that tend to the defaming one another.

And, friends, live all in the power of the Lord God, and in his truth, light, and life,
that with it you may all with one heart, soul, and mind keep dominion; and in the light,
life, truth, and power of God do true judgment, justice, and truth, righteousness,
and equity in all your men and women`'s meetings,
without favour or affection to relations, kindreds, and acquaintance,
or any respect of persons; for if you do not so, judgment will come upon, you from God,
to put you down from your places.
For the power of God, light, life, and truth respects not any, but justice, truth,
righteousness, and equity, etc.

Let mercy overshadow the judgment seat, and let mercy be mixed with judgment.

Take heed of foolish pity; and if you be not diligent againt all profaneness, sin,
iniquity, and uncleanness, looseness; and debauchery, and that which dishonoureth God,
then you let those things come up upon you, which you should be atop of, and subdue,
and keep down with righteousness, and the truth, and the power of God.

And in all your men and women`'s meetings, let all things be done in love,
which doth edify the body; and let nothing be done in strife and vain glory,
but keep in the unity of the spirit, which is the bond of peace.
And let all things be done in the wisdom of God, which is pure and gentle, from above,
above the earthly, which is below, sensual, and devilish.

And take heed of hurting any concerning marriages, if the thing be right,
(through any earthly reasoning,) lest they do worse.

And so all be diligent for the Lord God and his truth upon the earth,
and the inheritance of a life that hath no end,
that you may live in that seed that is blessed forevermore.

And be diligent in all your meetings, and see to the setting forth of apprentices,
all fatherless and poor Friends`' children;
and that all the poor widows be carefully looked after,
that nothing may be lacking among you; then all will be well.

And keep your testimony against all the filthy rags of the old world;
and for your fine linen, the righteousness of Christ Jesus.

And keep your testimony for your liberty in Christ Jesus, and stand fast in it,
against all the false liberties in old Adam; and your liberty in the spirit of God,
and in the gospel of Christ Jesus,
against all the false and loose liberties in the flesh.

And train up all your children in the fear of the Lord, and in his new covenant,
Christ Jesus; as the Jews did their children and servants in the old covenant,
and so do you admonish your children and servants.
And let no man or any live to themselves, but in that love that seeks not her own.

And have an eye over them that come to spy out your liberty in Christ,
and will report out of your meetings things to make advantage,
and to the defaming of persons.

And let every one seek the good of one another, and their welfare in the truth,
and make others`' condition their own;
and this keeps as a father and mother to condescend to a child.

And all live in the seed which hath the blessing,
and in the wisdom by which you may order all things to God`'s glory, over the evil seed,
that is out of the truth.

And if any one hath any thing to say, in opposition to the matter of marriages,
propounded by any to the meeting, such Friend or Friends to make it known,
(what they have against the parties,) to such as are appointed by the meeting,
to inquire into the clearness of the parties,
who laid their intentions before the meeting.
And such Friends, as have intentions of marriage,
first to lay it before the men and women of the Monthly Meeting they belong to,
and to see that things are clear, before they are brought to the Two Weeks`' Meeting.

And if any difference arise, either about marriages, or any other case,
in the Two Weeks`' Meetings, that the business be presently referred to six Friends,
to have a hearing of the matter another day,
or else for them to go forth and determine it presently,
and not to discourse it in the open meeting.

And if any legacy be left by any deceased Friend, to a particular use,
as to putting forth apprentices, and breeding up poor Friends`' children;
that the said money be kept distinct, as a stock for the said use,
and a particular account thereof be kept.
And the Quarterly or Six Weeks`' Meetings to see,
that the said monies be disposed of to the uses as aforesaid.
And if any of the principal money so given, be at any time made use of to any other use,
that it be again made up by the meeting of Friends in general.
And though the money be left or given to any particular Friend for the use aforesaid;
yet the same to be paid to two or three persons,
whom the Quarterly Meeting or Six Weeks`' Meeting shall appoint to receive such money;
that so the meeting may have the ordering and disposing
of the said money to the best advantage,
and the use intended.

And that Friends do keep in their testimony against the vain fashions of the world,
and all looseness and uncleanness whatsoever; and against all profane, idle tippling,
and taking tobacco in coffee houses and alehouses, which is an ill savour.
And against all strife and contention whatsoever.

And that some Friends be appointed at every meeting to keep the doors,
to keep down rude boys and unruly spirits;
that so the meetings may be kept civil and quiet.

And if one Friend hath any thing against another, let him not treasure it up,
till the time of his marriage, and then cast it upon him publicly;
but let him presently speak to the Friend, and also to them,
that the meeting hath appointed to see after his clearness, etc.
And that things may not be deferred too long at the Two Weeks`' Meeting concerning marriages;
but that they may be answered in a short time,
lest they be put to a strait in the matter.

And stop all bad reports, (for thou shalt not raise a false report upon my people,
saith the Lord,) and minister justice upon it presently,
so that no man or woman may be defiled or defamed with such things.

G+++.+++ F.

Read this in the Men and Women`'s Meeting in the fear of the Lord,
as often as you See occasion, and record it in your book.

[.centered]
=== Letter 264.

An additional extract from other of G. F.`'s Epistles, both of former and latter dates,
more largely speaking to things contained in the paper foregoing, with some new matters;
recommended to Friends by him,
(from time to time,) to be taken notice of at their Quarterly and other meetings.

Friends`' fellowship must be in the spirit,
and all Friends must know one another in the spirit and power of God.

And in all the meetings of the county, two or three may be appointed from them,
to go to the Quarterly Meetings, for to give notice one to another,
if there be any that walk not in the truth, and have been convinced,
and gone from the truth, and so have dishonoured God.
And likewise if any that profess the truth, follow pleasures; drunkenness, gamings,
or are not faithful in their callings and dealings, nor honest, nor just,
but run into debt, and so bring a scandal upon the truth,
Friends may give notice to the Quarterly Meeting,
(if there be any such,) and some may be ordered to go and exhort them,
and bring in their answers to the next Quarterly Meeting.

And so to query and search out all such, as live not as becomes the truth of the gospel,
and yet do profess it, so that they all may walk in it, as well as talk of it;
for none hath the heavenly comfort of it, but who do walk in it.
For all the talkers of Christ and his gospel, that do not walk in him, dishonour him.
And all uncleanness and looseness in all your meetings, judge and condemn with the light,
power, and spirit of Christ; so that nothing may reign among you,
but that which doth glorify God and Christ.

And to admonish all them that be careless and slothful,
to diligence in the truth and service for God,
and to bring forth heavenly fruits to to God;
that they may mind the good works of God and do them, in believing in his son,
and show it forth in their conversations; and to deny the devil and his bad works,
and not to do them.

And to seek them that be lost,
or driven away from the truth into the devil`'s dark wilderness, by his dark power;
seek them again by the truth, and by the truth and power of God,
bring them to God again.

And to see, that all that come amongst Friends, and profess truth, keep to yea and nay,
in their dealings and communications, in justice and equity, and not in oppression.

And that in all the Monthly Meetings there be an inquiry, whether any that profess truth,
are out of the pure language, thou to every one,
whether they keep up God and Christ`'s language,
that the holy prophets and apostles used, over all the flattering words in the world.

And Friends, my desire is, that ye all may be preserved in the Lord`'s power,
and in his everlasting seed, and so in the order of the gospel,
and in the government of Christ Jesus; of the increase of which there is no end.
And that ye may keep up your ancient testimony,
(in the power and spirit of God,) against tithes;
and that ye may keep up your ancient testimony in the sincere life for Christ,
your high priest, against the hireling priests and their old temples;
manifesting that ye are the temples of God.

And let inquiry be made concerning all such among Friends as do pay tithes,
which makes void the testimony and sufferings of our brethren,
who have suffered (many of them) to death;
by which many widows and fatherless have been made;
and which is contrary to the doctrine of the apostles, and the doctrine of the martyrs,
and contrary to the doctrine of the righteous in this present age;
all which are to be inquired into, and to be exhorted to faithfulness therein.

And that ye may keep your ancient testimony for the church which is in God,
the living members, which Christ, the spiritual man, is the holy head of,
and your heavenly rock and foundation.

And all such as marry by the priests, who have some of them the rough hands of Esau,
and fists of wickedness,
and who have had their hands dipped in the blood of our brethren in New England,
and who have been the cause of the banishment of some of our brethren,
and have spoiled so many of their goods, casting them into prisons,
and keeping so many of them in prison at this day:
all such as go to them for wives or husbands,
must come to judgment and condemnation of themselves,
and that spirit that led them to the priests to marry them; or else Friends,
that keep their habitations, must write and bear their testimony against them both.
For from Genesis to the Revelations you never read of any priests that married any people,
but it is God`'s ordinance; and whom God hath joined together, let no man put asunder.
And they took one another formerly in the assemblies of the righteous.
(when all things were clear,) therefore let all these things be inquired into,
and brought to the Quarterly Meeting; and from thence some ordered to go to them,
and to return what they say, at your next meeting.
And let all this be done before they, or any of them, be declared as heathens,
or written against, let them be three or four times admonished,
that they may have gospel order, so that if it be possible,
they may come to that which at first did convince them,
and to repent and condemn their unrighteous doings.
So that ye may not leave, if possible, a hoof in Egypt.

Now, all Friends, who have known the power of God,
and do believe in the light of Jesus Christ, who is your high priest,
who is made higher than the heavens; you come to know him to be your teacher,
and to hear him in all things, and that God may work all your works in you and for you.
And all such pretended Friend or Friends, that have gone to the priests to marry them,
or have been drawn by their relations so to do,
in pretence to have their estates secured for their heirs,
such have gone from the light of Christ in themselves,
and have quenched the motions of the spirit of God in their own hearts,
and distrusted God, and let a spirit of unbelief enter into them,
and thereby such cause the world to glory over them, and Friends;
and both priests and the world say that such are hypocrites,
and they come to them but to save their estates.
And they talk of the living God, but it is seen the world is their god,
and the priest must do their work to preserve their estate.
Such distrust the living God about outward things,
though formerly they used to cry against them, and their teaching, and their marrying,
and their baptizing; but now they can come to them to marry them to save their earth,
and to shun suffering.
And thus they manifest their hypocrisy.
And therefore all such as have gone to the priest, to be married by him,
come to the witness of God in your consciences,
by which you may come to condemn that spirit that led you to them to be married.
For all those are far gone,
who can come so near a priest as to hear his prayers for money,
and to partake of his works.
Such have turned against the light, and quenched the spirit,
and abused the power which would have risen in them against it.
And such in their apostacies may have cried,
the power of God is not amongst Friends as it was in the beginning;
when they have abused it in themselves, and grieved the spirit of the Lord,
and Friends who live in the spirit.
For it is not the bishops`' nor priests`' work to marry people, nor is it to be seen;
nor you never read throughout the holy scriptures,
that either priests or bishops married any; but it is God`'s work, and his ordinance;
for whom God joins together, let no man put asunder.
And marriage is honourable in all, the bed being undefiled.
And they took one another in the assemblies of the righteous, the saints,
and the holy ones of God, who were of the seed of the righteous.
Which practice is now followed amongst the people of God, called Quakers,
who are of the seed and generation of the righteous, the elect people of God.
And also you may read, how Jacob, who was of the seed of the righteous,
took his wife in the assembly at Laban`'s house,
who gathered the people together when he took her, having declared it before;
and all parties were satisfied.
And Jacob was the beloved of God, who took his wife of the best sort of people;
his father and mother would not have him unequally yoked, as Esau had been before.
And also you may read Isaac`'s marriage, in whom the blessed seed was called,
as the apostle saith; "`In Isaac shall thy seed be called.`"
And how wonderfully it was carried on by the Lord!
See Gen. 24:25. And also read, how Boaz took his wife Ruth,
(after both sides were satisfied,) in the assembly of the people and elders;
and how he declared it unto the elders, "`Ye are witnesses this day,
that I take Ruth to be my wife; and they said, we are thy witnesses.`"
And of this Boaz came the line of Christ.
For Boaz begat Obed, and Obed begat Jesse, and Jesse begat David.
And also Isaiah the prophet, who prophesied of Christ`'s birth, sufferings, and death,
God commanded him, when he was to go to the prophetess, that he should take witnesses,
and write it in a roll; and this was the command of God;
and he was of the seed of the righteous.
And likewise the children of Israel, when they were carried into captivity,
when any married, and all things on both sides were clear, they took one another,
according to the law of Moses.
As for example, see Tobias.
And also Christ Jesus went to a marriage in Cana in Galilee,
(who ended the first priesthood,
who is the everlasting priest.) And he went with his disciples and the mother of Jesus.
Whence it is clear that there was a meeting and an assembly of people.
And marriage being God`'s ordinance, and God`'s joining, here Christ owns it;
for it was God`'s joining before the fall; and God`'s giving before the fall;
and it is so in the restoration out of the fall again by Christ Jesus:
who are come into the spirit and power of God,
they know it is God`'s joining again in the restoration; and whom he joins together,
let no man put asunder.
And so marriage was a figure of Christ and his church,
as the apostle instanceth in Ephesians.
And therefore they were not to be unequally yoked, believers with unbelievers.
The law of God did forbid it;
they were not to give their sons and daughters to the heathen, or marry with them,
for it grieved the Lord in the old world,
and brought destruction upon those bad marriages.
When the sons of God saw the daughters of men were fair,
and they took them wives of all which they chose, who corrupted the earth,
and filled it with violence.
Yet the holy men of God, their marriages were never judged of God in the old world.
Neither Seth`'s, Lamech`'s, nor Mahalaleel, nor Methusalah, nor Noah, nor Abraham,
Isaac nor Jacob; and so none before the law, nor none in the law,
not in the time of the gospel, their marriages were not judged by the Lord,
who walked in the power and spirit of the Lord, and knew God`'s joining;
who brings the man and woman together.
But such as mingled with the heathen and unbelievers, and followed strange flesh,
they went from the spirit, they lost the sonship;
through such the earth was corrupted and filled with violence;
and such could not know God`'s joining, who went from the spirit,
and from the law and gospel; and such are mingled among heathens and unbelievers,
and follow strange flesh, and corrupt their own, who go from the spirit,
by which they have been sanctified and led into the sonship.

And such as marry with unbelievers and heathen, go contrary to the law of God,
and grieve him and their righteous parents.

So marriage is God`'s holy ordinance, and Christ,
that comes to restore all things again into their place, saith,
"`Whom God joins together, let no man put asunder.`"
And brings it to the beginning again, how God made them male and female.
So in the restoration in the image of God and sanctification,
they are brought to the joining one male with one female again;
not for one man to have many women at once, God did not make many for him;
but in the fall from the righteousness of God and his image,
there they run together like beasts, a man and many women.
There men join and put asunder; "`but in the beginning it was not so,`" saith Christ,
the heavenly man, the second Adam, "`for God made them male and female,
and whom he joins together, let no man put asunder.`"
And so God joins with his spirit and power, for he is a spirit;
and this is a heavenly and spiritual joining; and them that God joins,
they do not follow strange flesh, but the spirit of God;
and such a marriage is sanctified by the spirit, and by the Lord,
and such know his heavenly ordinance.
And this is the marriage Christ owns, and sets up and encourages,
who is the covenant and the quickening spirit.
And so God, who is a spirit, joins with his spirit, power, and light;
this joining is in the covenant of God, all such marriages are honourable in all things,
for their bed is not defiled; but where the bed is defiled,
that marriage is not honourable.
And all that forbid marriage are in the doctrines of devils;
and they that are in the doctrine of devils, are out of truth, who destroys the creation,
and destroys some one way and some another,
that are under his power and command from truth; but they that obey the truth,
and obey Christ, and obeys God, are over him and his doctrine, and the defiled bed,
and strange flesh; and the spirit gives them an understanding to know God,
and his joining by his spirit, who is blessed forever.

Now if any should say, that Adam took his wife alone;
and so run into the works of darkness, and go together in the dark,
contrary to the righteous seed and holy generation:
such are judged by the holy seed and by them in the holy life and law of God,
and with the light of Christ Jesus condemned.

And as for Adam taking his wife alone, that was before there were any witnesses.
But there was a form of words betwixt them before they went together, or he knew her,
(as followeth,) viz. "`And when the Lord God brought the woman to Adam,
Adam said to the Lord, This is bone of my bone, and flesh of my flesh,
she shall be called woman, because she was taken out of man;
and they shall be one flesh.`"
But this form of words of Adam`'s, and his doing,
is nothing to them that are workers of darkness, and run together in the dark.
For after the earth was peopled,
you may read how the generations of the righteous
did take one another in the assemblies of the righteous,
and it was recorded before witnesses.

So all such as marry by the priests, or marry by the world, that are unbelievers,
do go from God`'s power and spirit, and his joining,
and do break the law of God in their marriages, who forbade to join with unbelievers.
And therefore with the light of Christ Jesus are such judged and condemned,
and must come through condemnation and judgment.

For the right joining in marriage is the work of the Lord only,
and not the priests or magistrates; for it is God`'s ordinance,
and not man`'s. And therefore Friends cannot consent,
that they should join them together.
For we marry none, it is the Lord`'s work, and we are but witnesses.
But yet, if a Friend through tenderness have a desire that the magistrate should know it,
(after the marriage is performed in a public meeting of Friends and others,
according to the holy order and practice of Friends in truth throughout the world,
and according to the manner of the holy men and women of God of old,)
he may go and carry a copy of the certificate to the magistrate;
Friends are left to their freedom herein.
But for priests or magistrates to marry or join any in that relation,
it is not according to the scripture;
and our testimony and practice hath been always against it.
It was God`'s work before the fall, and it is God`'s work only in the restoration.

Let not any go disorderly together in marriage,
contrary to the practice of the holy men of God,
who declared it in the assemblies of the righteous, when they took one another,
all things being clear, and they both being free from any other, in respect to marriage.
And when any take one another in marriage,
let there not be less than a dozen Friends and relations present,
(according to your former order,) having first acquainted the men`'s meeting,
and that they have clearness and unity with them; and then it may he recorded in a book.
And if any walk contrary to the order of truth herein,
let some be appointed to speak to them, and give notice thereof to the next meeting.

And all that are widows, who have children, and do intend to marry, let inquiry be made,
what she hath done for her children,
(if there be no will made,) then let such part of
her late husband`'s estate be set out for the children,
as is equal and according to truth; and what they can do more afterwards,
let them do it also.
And where there is a will made,
let those legacies and portions be improved and secured
(before their marriage) for the children of the deceased,
with what more they can do for them.
And then, when these things are done,
let them be recorded in a book at the next Quarterly Meeting.

And all men that hunt after women, from woman to woman; and also women,
whose affections run sometimes after one man; and soon after to another,
and so hold one another in affection, and so draw out the affections one of another;
and after a while leave one another, and go to others, and then do the same things there;
these doings are more like Sodom than saints, and are not of God`'s moving nor joining,
where they are not to be parted.
For marriage is God`'s ordinance, and God`'s command one to another,
and in that is felt the power of God.

And if any go together in marriage, having declared it at Friends`' meetings,
if the magistrates do cast them into prison,
because they are not married according to the national law, or by a priest,
all the men Friends and women Friends in the meeting,
(or twelve of them) may set their hands to a paper and send it to the justices,
it being done in truth and righteousness, and according to the scriptures of truth.
As Boaz declared his taking of Ruth in the town-gate; and Jacob when he was married,
Laban called in his kindred; and other examples you may see in the scriptures,
who did marry, and had no ring, nor priest neither to marry them.

Now, no man ought to speak to a woman concerning marriage
before that he hath spoken to her father and mother,
and have their consent; and if she have no father or mother, but guardians and trustees,
then they must speak to them, if she be under age, that they may have their consent,
and so proceed accordingly, as Abraham`'s servant did concerning Isaac`'s wife.
And you are to see that all widows do make provision
for their children before they are married to another,
according to truth and righteousness.

And you are to see,
that every man and woman are free from all entanglements
with any other woman or man before they are married;
and if they have been engaged,
you must have a certificate under the hands of the person
that they have been entangled with to discharge them;
so that all things may be done in peace, and unity, and righteousness,
according to the truth that is in every man and woman.
And if the young man or young woman`'s relations be of the world,
they must have their consent, and a certificate from them.
And if the man or woman comes from beyond sea, or out of another country,
ye must have a certificate from the men and women`'s meetings there, how they have lived,
and whether they are free from all other persons, by any engagement, covenant,
or contract concerning marriage; and if they are not clear, they must answer that,
and be cleared by a certificate under their hands, before they proceed any further.

And if any man should defile a woman he must marry her, if she be a beggar,
though he have never so many hundreds; for he must fulfill the law of God,
for the law of God commands it, that he must marry her, and condemn his action,
and clear God`'s truth.
But no such marriages, where the bed is defiled,
we bring into our men and women`'s meetings;
but some Friends (if such a thing happen) draw up a certificate,
and they to set their hands to it,
that they will live faithfully together as man and wife, and fulfill the law of God.

And this I write, if ever such a thing should happen;
but I hope that Friends will be careful, and keep in the fear of the Lord,
that they may have an esteem of the Lord`'s truth, and their own bodies,
and of the honourable marriage, where the bed is undefiled.

And when any marriages is to be propounded,
let it be laid before the women`'s meeting first.
And after they have declared it there, if they do know any thing of the man or the woman,
that it should not proceed so far as to the men`'s meeting,
then let two or three women go to the men`'s meeting,
that some of the men and women may have a distinct meeting concerning it,
and let them end it before it comes to the men`'s meeting;
and if there be no such occasion of any such meeting,
let two or three women go along with them to the men`'s meeting.
And so after Friends have taken their names, and places of abode,
let two women of the women`'s meeting be nominated, and two men of the men`'s meeting,
that if any one have any thing to say against the couple
before the next meeting they may speak to them;
and if there should appear any thing, they may end it before they come to the meeting.
And if there be nothing, when they come the second time again to the women`'s meeting,
the woman may go along with them to the men,
and testify that they know nothing against their proceedings.
And likewise the men, that are appointed to inquire out to make the like report,
(and let the man and the woman always appear together,
when they lay their intentions of marriage.) So then the thing is left to the
men to give their judgment and advice to the couple that are to be married,
all things being clear, and nothing appearing to the contrary; and their fathers,
and mothers, or guardians, or overseers being satisfied,
then they may have their liberty to appoint a meeting where they please,
in some public meeting-place, where their relations and Friends may be present,
and there get a certificate ready drawn up, with the day of the month, place, and year,
how that such a couple did take one another in the presence of God,
and in the presence of his people,
who had laid their said intentions so often before them;
and all things being found clear,
according to the law of God and the practice of the holy men,
recorded in the scriptures of truth, to live together in christian, honourable marriage,
according to God`'s ordinance and his joining,
to be help-meets together as long as they live.

And if any man or woman come out of another country,
they must bring a certificate from the men and women`'s meeting to them,
where they take their wife and husband.

And no man or woman is to be permitted to proceed in marriage,
if they be engaged or entangled with any other, till they be cleared.

Dear friends, if there happen any difference betwixt Friend and Friend,
let them speak to one another; and, if they will not hear,
let them take two or three of the meeting they belong to, that they may end it,
if they can.
And if they cannot end it, then it may be laid before the Monthly Meeting.
And if it cannot be ended there, then it may be brought to the Quarterly Meeting,
and there let it be put to half a dozen Friends, that they may end it,
that they may keep their meetings quiet.
Or, they that are at difference, may choose three Friends,
and Friends may choose three more to them, and let them stand to their judgment:
for there are few, that love quietness and peace,
who will have their names brought to a Monthly or Quarterly Meeting,
to have their names sounded over the country, that they are in strife;
but will rather endeavour to end it amongst themselves or at their own meeting,
before that they come to the Monthly Meeting.

And if there be any difference brought to the Monthly or Quarterly Meeting,
either men`'s or women`'s, after you have heard them one by one,
and let but one speak at a time, know of them, whether they will stand to your judgment?
And, if they will, let half a dozen Friends make a final end of it.
But, if they will not stand to your judgment, they are not fit to bring it thither.

And if any brother or sister hear any report of any brother or sister,
let him or her go to the party, and know the truth of the report; and if true,
let the thing be judged: if false, go then to the reporter, and let him or her be judged.
And if any should report it at a second or third hand,
without going to the party of whom the report goes, let such he brought to judgment:
"`for thou shalt neither raise nor suffer a false
report to lie upon my people,`" saith the Lord;
for they are to be holy, as he is holy; and just, as he is just.

Now concerning gospel-order;
though the doctrine of Jesus Christ requireth his
people to admonish a brother or sister twice,
before they tell the church, yet that limiteth none,
so as that they shall use no longer forbearance, before they tell the church,
but that they shall not less than twice admonish
their brother or sister before they tell the church.
And it is desired of all, that before they publicly complain,
they wait in the power of God to feel,
if there is no more required of them to their brother or sister,
before they expose him or her to the church: let this be weightily considered.

And further, when the church is told,
and the party admonished by the church again and again,
and he or they remain still insensible and unreconciled,
let not final judgment go forth against him or her,
till every one of the meeting have cleared his or her conscience;
that if any thing be upon any further to visit such a transgressor,
they may clear themselves, that if possible the party may be reached and saved.
And after all are clear of the blood of such an one,
let the judgment of Friends in the power of God go forth against him or her, as moved,
for the Lord`'s honour and glory`'s sake,
that no reproach may come or rest upon God`'s holy name, truth, and people.

And all such as behold their brother or sister in a transgression, go not in a rough,
light, or upbraiding spirit, to reprove or admonish him or her,
but in the power of the Lord, and spirit of the Lamb,
and in the wisdom and love of the truth, which suffers thereby,
to admonish such an offender.
So may the soul of such a brother or sister be seasonably
and effectually reached unto and overcome,
and they may have cause to bless the name of the Lord on their behalf,
and so a blessing may be rewarded into the bosom of that faithful
and tender brother or sister that so admonished them.

And be it known unto all, we cast out none from among us; for if they go from the light,
and spirit, and power, it which our unity is, they cast out themselves.
And it has been our way to admonish them,
that they may come to that spirit and light of God, which they are gone from,
and so come into the unity again.
For our fellowship stands in the light, that the world hates,
and in the spirit which the world grieves, vexes, and quenches;
and if they will not hear our admonitions, as before, the light condemns them,
and then goes the testimony of truth out against them.

And no condemnation ought to go further than the transgression is known;
and if he or she returns, and gives forth a paper of condemnation against him,
or herself, (which is more desirable,
than that we should do it,) this is a testimony of
his or her repentance and resurrection before God,
his people, and the whole world; as David, Psalm 57. when Nathan came to admonish him.

And that no testimony, by way of condemnation, be given forth against any man or woman,
whatever crime they commit, before admonition,
and till such time as they have had gospel-order, according to Christ`'s doctrine.

And so keep the church-order of the gospel,
according as the Lord Jesus Christ hath commanded; that is, "`If thy brother offend thee,
speak to him betwixt thee and him;`" and if he will not hear, take two or three.
If he will not hear two or three, then tell it to the church, etc.

And if any one do miscarry, admonish them gently in the wisdom of God,
so that you may preserve him and bring him to condemnation,
and preserve him from farther evils, which it is well if such do not run into;
and it will be well for all to use the gentle wisdom of
God towards them in their temptations and condemnable actions,
and with using gentleness to bring them to condemn their evil,
and to let their condemnation go as far as the bad action has gone, and no farther,
to defile the minds of Friends or others; and so to clear God`'s truth and people,
and to convert the soul to God, and preserve them out of further evils.
And take heed of spreading such things in the minds of the world,
and farther than they are gone there,
lest you by that means do cause them to blaspheme God`'s name,
and cause them to speak evil of the truth and God`'s people;
such do deserve reproof that so do, and condemnation.
So be wise in the wisdom of God.

And let no one accuse any one, either in a Monthly or Quarterly Meeting, publicly,
except they have spoken to them by themselves first, and by two or three, as before.

And dear friends, in the power of the Lord God, you who are gathered with it,
which is the authority of your men`'s and women`'s meetings;
in the power of the Lord Jesus see, that all things be well amongst you,
and that all do walk in the truth, and as becometh the gospel of Christ,
and his glorious light and life, so that all may stand up for God`'s glory,
and be valiant for his truth, and all to grow up in it.
And if any hear reports, or have any thing against any brother or sister,
let them first speak to them, before that they declare it abroad;
and this will keep down backbiting and whispering, and preserve in brotherly love.
And all looseness whatsoever, let it be reproved: and admonish, and exhort,
and encourage such as are young and tender, to keep and preserve them in the way of life;
and so watch over one another for good.

And that care be taken from time to time, as Friends are moved thereunto,
for relieving faithful Friends`' necessities,
and for other services of truth which shall be delivered
into the hands of a faithful Friend or Friends,
(who are desired to be receivers for that purpose,).
who are to give an account of all monies,
that shall be by them received and disbursed at the next Monthly or Quarterly Meeting,
after it shall be laid out, (if it be desired,) and so the account to be ended,
that ministering Friends may not be cumbered with outward things, but kept out of them;
and that what monies shall be by them disbursed for the service of poor Friends,
as aforesaid, shall be disposed of,
as Friends of the Monthly or Quarterly Meeting see meet to dispose of the same.

And all Friends, be tender over all Friends that are prisoners upon truth`'s account,
and that are sick and weak people, strangers and fatherless, and widows, servants,
and children, that their parents, masters, or dames and relations are not Friends;
keeping in the power of the Lord, it will lead you in all things without many words,
and bring you to see and feel, and live in that which was before enmity was,
or words either, which will chain it under in that you all will have unity,
and he all as a family, and in it be all as one; in that is the peace and unity.

And also all widows, in all your several meetings,
let them be taken notice of and informed, and encouraged, in their outward business,
that there be not any hinderance put to them in their inward growth,
and so to be carefully looked after, that they may be nourished and cherished,
and preserved in the truth, that love may be increased.
And if they have many children, to put them out apprentices,
(or servants,) which may be a burden to them to bring up,
then let Friends take care to ease them, by putting them forth, as may be seen meet.
Let all these things be looked into every meeting,
and notice thereof given to the next Monthly or Quarterly Meeting,
and some ordered to see that all these things are
done according to truth and righteousness.

And in all your meetings,
let notice be given to the Quarterly Meeting of all poor Friends: and when ye have heard,
that there is many more poor belonging to one meeting than to another,
and that meeting thereby is burdened and oppressed,
let the rest of the meetings assist and help them, so that ye may ease one another,
and help to bear one another`'s burdens, and so fulfill the law of Christ.
And so see that "`nothing be lacking,`" according to the apostle`'s words, mark,
"`nothing lacking;`" then all is well.
For the Jews outward, though they were as the stars of heaven,
and as the sand upon the sea-shore for multitude,
yet there was not to be a beggar amongst them, according to the law of God.
And amongst the christians in the first age,
there was a men`'s meeting set up at Jerusalem to see that nothing was lacking,
which was the gospel-order, according to the law of Jesus;
and this continued as long as they lived in the life, power, and spirit of God.
But when the apostacy came in, and the true church fled into the wilderness,
which was to continue there one thousand two hundred and sixty days,
and the witnesses prophesied in sackcloth one thousand two hundred and sixty days,
and the beast was worshipped just so long, one thousand two hundred and sixty days;
and then all things went out of order,
and everything was wanting in that time they worshipped the dragon and the beast;
and the devil made the world like a wilderness.
But now the judgment of the great whore, and of the beast is come,
and with them the false prophet and the dragon,
who shall be cast alive into the lake of fire;
and the true church is coming up out of the wilderness, and the man child,
(which was caught up into heaven,) is come down again
to rule all nations with a rod of iron:
and the marriage of the Lamb is come, and the Lamb and the saints shall have the victory,
and the everlasting gospel is and shall be preached again, as was among the apostles;
and the gospel-order shall be set up, as was amongst them; and a men`'s meeting,
as was at the first conversion, to see that nothing be lacking in the church;
then all is well.
So there is not to be a beggar now amongst the christians, according to the law of Jesus,
as there was not to be any among the Jews, according to the law of Moses.

And dear friends, who feel the power of the everlasting God, (for all who are out of it,
are in confusion,) you being come into God`'s fear,
which is the beginning of true wisdom, by which all things were created;
and by it all things must be ordered again to God`'s glory.
All that are out of this wisdom are in the earthly, devilish, and destroying state;
but the wisdom from above is gentle and pure, and preserves you, yea,
and the whole creation, to the glory of God.

And now,
that Monthly and Quarterly Meetings of two or three out of every
particular meeting of true and faithful Friends are,
set up, and kept in the most convenient place in the middle of your county,
you may know in your meetings of the wants and necessities of all Friends,
whether in bonds, or out, widows or fatherless, or aged people, their necessities,
being looked into, and every one feeling one another`'s condition;
this keeps in tenderness and love, as a family; and nothing being lacking amongst you,
then all is well, every want and necessity being supplied.
And by this, one meeting may be serviceable to another in outward things,
for that is the least love;
and by this you may come into the practice of the pure religion,
which is to relieve the widows, strangers, fatherless, and helpless.

And, friends, all the legacies that are given to the men or women`'s meetings,
let them be kept as a public stock for the setting forth of apprentices,
and setting them up.

And Friends to have and provide a house for them that be distempered,
and not to go to the world.
And to have an alms-house or hospital for all poor Friends, that are past work.

And Friends to have and provide a house or houses,
where a hundred may have rooms to work in, and shops of all sorts of things to sell,
and where widows and young women might work and live.

And dear friends, dwell all in the everlasting power of God, and his life,
in which is both unity, order, peace, and fellowship;
and wait in the fear of the everlasting God, that his wisdom you may receive,
which is pure and gentle from above, by which all things were made,
by which wisdom you may order all things to the glory of God.
The poor, the sick, the widows, the fatherless, the prisoners be tender of,
and feel every one`'s condition, as your own, and let nothing be lacking amongst you,
according to the apostle`'s doctrine to the church of God of old time;
and if nothing be lacking, all is well.

And dear friends, know in all your meetings who is sick, and weak, and in want,
and widows, and fatherless, and aged people, that cannot help themselves;
and such as God hath distributed unto, of that which God has distributed,
to lay aside for the necessities of others,
as you are moved and commanded of the Lord God by his power and spirit;
for he that gives to the poor, lendeth to the Lord; and he loves a cheerful giver.

Secondly.
That all prisoners for the truth be minded, who are in want, and who are not,
and the families of such who are in prison, whether they are in want or not;
and such as are decayed any manner of way, and cannot help themselves;
and such as have left a calling, which they cannot for conscience sake follow;
do the best you can to help them, and further them to employment,
that they may labour in the thing that is good, and be a blessing in the creation;
that this you may do, that you may be a blessing in your generation.

And all the fatherless children their estates to be recorded
in a book at the Monthly or Quarterly Meeting;
and all that are entrusted with any estates may be
entered at the Monthly or Quarterly Meetings,
(fatherless or widows`' estates,) that the meeting
may see that justice be done unto them,
and require them to give an account,
(if need be,) and to do that which is just and equal;
so that there may be no strife about outward things amongst you.
And that every one that is entrusted with any widows
or fatherless children`'s estates may be faithful,
and not fail them in time of need.
And that every Quarterly Meeting may have an eye over such as are entrusted,
and assist them in that which is right and righteous,
and to see that they are faithful to their trust.
So that righteousness, and justice, and truth, and equity may flow down amongst you,
and that the wisdom of God be among Friends, to order them in all things to his glory.

And let two faithful Friends in the truth in every
particular meeting be ordered to receive all collections,
and to bring them to the Monthly Meetings; and let two such Friends receive them there,
and bring them to the Quarterly Meeting;
and let four faithful Friends receive them there.
And whatever collections are received, let an account be kept of what is received,
and to whom it is disbursed;
that so an account may be given to any faithful Friend that may desire it.
And in every Monthly and Quarterly Meeting to inquire, what poor there are,
and who are fit to go apprentices or servants;
and that Friends then and there may order them to apprenticeships
to such trades as they in wisdom shall think fit.

And if any legacy be left by any deceased Friends to a particular use,
as to putting forth apprentices, and breeding of poor Friends`' children,
that the said money be kept distinct as a stock for the said use,
and a particular account thereof to be kept;
and the Quarterly Meeting to appoint some persons to receive the said money,
and to keep the account thereof,
and the meeting to see that it is disposed of to the uses aforesaid.
And if any of the principal money so given be at any time made use of to any other use,
that it be again made up by the Quarterly Meeting of Friends.
And though the money be left or given to any particular Friend for the use aforesaid,
yet the same to be paid to the two or three persons,
whom the Quarterly Meeting shall appoint to receive such money,
that the meeting may have the ordering and laying out the said
money to the best advantage to the uses aforesaid.

So that the legacies given apart to the meeting of men or women,
be kept apart for the setting forth poor Friends`' children,
and setting them up in their trades, that the memory of the deceased just Friend,
that gave it, may not be forgotten.

And all Friends in the wisdom of God train up your children in the fear of God,
that they may receive the wisdom of God; and as they are capable,
they may be instructed and kept employed in some lawful calling,
that they may be diligent, serving the Lord in the things that are good;
that none may live idle, and be destroyers of the creation,
or unserviceable in the creation, and thereby become burdensome to others,
and to the just in themselves; but that in the wisdom of God all may walk,
and with it all things may be ordered.

And all Friends, see that your children be trained up in soberness, and holiness,
and righteousness, and temperance, and meekness, and gentleness, and lowliness,
and modesty in their apparel and carriage,
and so to exhort your children and families in the truth,
that the Lord may be glorified in all your families.
And teach your children when they are young,
then will they remember it when they are old, according to Solomon`'s counsel.
So that your children may be a blessing to you, and not a curse.

And all men and women are to order their children and servants in the order of the gospel,
and in the new covenant, that they may all come to know the Lord.
For the outward Jews were to train up their children in the old law, in the old covenant.
And so you that are called christians are to train
up your children in the fear of the Lord,
and in Christ Jesus, that they may walk in him in modesty, and holiness, and virtue.
And so all to govern their families.
And they that are to govern, are to be governed and ordered themselves,
by the spirit and power of God, to God`'s glory, and as examples in their families;
for all looseness is out of the power of God, either in word or life.
And so by the power of God, and his righteousness, and truth, and light, and life,
all that is to be judged, and kept under and down; and the truth, and the light,
and spirit of God must be walked in, which all looseness is out of.

And so, whatsoever things are of good report, or whatsoever things are lovely,
or whatsoever things are pure, and decent, and virtuous, and godly, and righteous,
and holy, and just, those follow after; and do the works of charity, and not your own,
but the good works of hospitality, which are accepted of God.

And keep the order of the gospel, the power of God,
which power of God was before the devil was, and is over him,
which brings life and immortality to light in men and women;
and men and women they are to walk in this power of God, and to keep in it,
being heirs of the same, and under the government of Christ Jesus,
who bruiseth the serpent`'s head, and destroys him and his government;
men and women being heirs of grace and life together, and of the power of God,
and of the gospel of Christ Jesus, the amen.
And so as they come to possess and inherit him and his gospel order,
they come to possess him and his government and order;
of the increase of which there is no end.

And that notice be taken of all evil speakers, backbiters, slanderers,
and foolish talkers, and idle jesters, for all these corrupt good manners,
and are not according to the saints and holy men`'s practice,
whose words were seasoned with salt, ministering grace to the hearers.

And all such as go up and down to cheat, by borrowing and getting money of Friends,
and have cheated several, all such are to be stopped and judged,
and notice of them is to be given to Friends, and to other persons.

And dear Friends in the everlasting seed of life, wisdom, and salvation, my desire is,
that you all may be preserved in it, to the glory of God, and in his power, and light,
and life, over death, and darkness, in the heavenly unity, in all your meetings.

Now concerning them that do go to the Quarterly Meeting,
they must be substantial Friends, that can give a testimony of your sufferings,
and how things are amongst you in every particular meeting.
So that none that are raw or weak,
that are not able to give a testimony of the affairs of the church and truth,
may go on behalf of the particular meetings to the Quarterly Meetings,
but may be nursed up in your Monthly Meetings, and there fitted for the Lord`'s service.
So that two may go one time from every particular meeting, and two another time,
or as it is ordered in your Monthly Meetings.
So that some may go from all your meetings, that make up your Monthly Meetings;
for the Quarterly Meeting should be made up of weighty, seasoned,
and substantial Friends, that understand the business of the church;
for no unruly and unseasoned persons should come there,
nor indeed into the Monthly Meetings, but who are single-hearted, seasoned, and honest.

And if any one should speak or tattle any thing out of your Monthly or Quarterly Meetings,
to the blemishing or defaming any person or the meetings,
such are to be brought to judgment and condemnation;
(for it breaks the privilege and order of your christian society in your
meetings,) so that all may be kept and preserved in the power of the Lord,
and in his spirit, in love and unity.

And therefore keep your meetings solid and sober,
and let the authority of your men and women`'s meetings be in the power of God;
for every heir of the power has right to that authority,
and in it keep the King of kings and Lord of lords`' peace in his church.

And so, the Lord give you wisdom, that by it you may be ordered to his glory,
and that every one may have a care of God`'s glory, and of his name and truth;
and that in his power you may see, that all do walk as becomes his glorious gospel,
which hath brought life and immortality to light in you;
which will preserve you in life and immortality, over the devil that has darkened you.
So that nothing may get betwixt your souls and minds, and the Lord God,
that he may be glorified in you all, and through you all, and over you all,
blessed forever.
Amen.

And the least member in the church hath an office, and is serviceable;
and every member hath need one of another.

And now Friends, so many Monthly Men`'s Meetings as you have in your county,
you may have so many Monthly Women`'s Meetings; and if once a year, at least,
you had a general women`'s meeting it would be well,
(for in some counties they have as many Quarterly women`'s
meetings as men`'s,) and in others they have only two,
in the summer time, because the ways are foul and days short in winter.

And that one or two Friends in every meeting do take an account of all the marriages,
births, and burials, and carry them to the Monthly Meetings;
and let one or two there be ordered to receive them, and record them there in a book,
which is to be kept at the Monthly Meetings.
And from thence a copy of what is recorded there, to he brought to the Quarterly Meeting,
and let one or two Friends be appointed there to receive them,
and to record them all in one book, which is to be kept for the whole county.
And this will be most safe, that if one book should happen to be lost,
the other may be preserved for the use of such, as may have occasion.

And that all Friends, who are not already provided,
may speedily procure convenient burying places,
and that thereby a testimony may stand against the
superstitious idolizing of those places,
called holy ground.
For Abraham bought a place to bury his dead in,
and would not bury them amongst the Egyptians and Canaanites.
And Jacob was brought out of Egypt, and Joseph,
and they were buried in their grandfather and father`'s burying places.
And so Friends, get decent burying places for your dead,
and let them be decently and well fenced,
that you may show a good example to the world in all things.

And dear Friends, do all that you do in peace and love, and in the fear of God,
condescending one unto another, in the simplicity and innocency of life, and truth,
and in the wisdom of God, that that may be every one`'s crown,
that nothing may be done in strife, to occasion words;
for you are called to peace and holiness, in which the kingdom stands,
and to serve one another in love.
And my love is to all Friends in the everlasting seed of God, in which is life, purity,
cleanness, and righteousness that shines over all.

And all Friends, do that which ye do in the power of God,
and then you are the Lord`'s freemen in love, and not captives.
For all which is done out of the power of God is in the captivity.
So wait all in the power of the Lord, and in the light,
in which you will feel life and peace, and the Lord`'s blessing.
So in that the Lord God Almighty preserve you,
and keep you over all that which is contrary, and give you victory and dominion.
And in peace and love live, in the spirit and power of God,
in which is the unity and the fellowship in the bond of peace,
that truth and life may reign amongst you;
that in all things you may adorn and grace the truth, that never hath an end.

And the Lord God Almighty preserve you in his seed, life, and wisdom,
and give you discerning victory and dominion over all that which is contrary,
that you may feel Christ`'s reign and authority,
in which you may all act in his power and authority.
So in that, God Almighty preserve you.

And draw up an account of all that have died in prison, in every county,
for truth`'s testimony, and lay them before the magistrates;
and so to keep Friends clear from the blood of all men.
And preserve a list of their sufferings,
together with the number that have died in prison;
that their blood may come upon them that have thirsted after it,
and that their testimony may not be lost, who have sealed it with their blood,
but that it may be preserved.
And so keep a record of them in your Quarterly Meeting books.
So that the memorial of the innocent sufferers for the truth and the name of Jesus,
may not be lost nor forgotten; that his name and power, that hath supported them,
may be exalted, that hath carried them over death, and their persecutors,
and the spoiling of their goods.
So in the heavenly seed Christ Jesus, that reigns, who is the living rock and foundation,
and stands sure for all his elect to build upon,
stand above all the rocks and foundations that are below, and will have an end;
and in him the Lord God Almighty preserve you, and keep you all.
Amen.

And all my dear Friends everywhere,
who have been moved of the Lord God to speak in steeple-houses to the priests,
or in markets to the people, or in courts, or fairs, or assizes, or towns;
let an account thereof be drawn up together in one book,
with the substance of their words, that they spake in the power of God.
This would be a book, that may stand to generations,
that they may see their faithful testimony,
and what strength God did ordain out of the mouths of babes and sucklings.
And Friends that have been moved to go to the professors`' meetings;
that their testimony there may not be lost,
together with all the examples that have fallen upon the persecutors.

And such testimonies of Friends as are deceased, let them be recorded,
that so the testimony of the Lord through his servants may not be lost,
that he raised up in his people,
for the same they were carried on through great tribulations and sufferings;
and many laid down their lives, and had their goods spoiled,
and they persecuted to death, to keep up their testimony,
(which the Lord moved them to speak by his spirit,) to future generations.
So that those words, that they were moved to speak forth by the power, may not be lost;
that the power and spirit of the Lord may be exalted.
So that an account may be taken of that which hath been spoken
and done by the motions of the spirit of God from the first,
as above mentioned.
And so be diligent, and those that can write, help them that cannot.
This may be easily done.

And all they that be public ministers, (if unknown,) that pass up and down the countries,
and to other nations, for them to have a certificate from their meeting,
where such persons are known, and all their practices are looked into;
that will prevent any bad spirits, that may scandalize honest men.
For they that do minister to others, must have a double diligence in virtue,
and chastity, and patience, and carefulness, and watchfulness, more than their hearers,
lest they judge them.
For Christ the heavenly man, is our example; and the apostle saith, follow us,
as we do follow Christ.
For who esteems the beggarly lusts before virtue, is not worthy of it;
and who preferreth his ungodliness, and his unholiness, and his earthliness,
before that which is heavenly, is not worthy of the heavenly, nor of godliness,
nor righteousness, etc.

And, dear friends, be faithful, you that know the light, the truth, and the power of God,
and his life; in the wisdom of God be faithful;
by which wisdom all things were made and created;
and by which wisdom all things that are created,
must be ordered again to the glory of the Creator.
And you that are come to know the truth and the power of it,
all come to know the order of life,
so that all things may be kept in that sweet order and government
to the glory of God and the refreshment of all,
and a sweet savour to God and in the hearts of all people,
that through the wisdom of God ye may adorn the truth in all things,
for the preserving of love, peace, and unity amongst all.

And live in the peaceable truth, and keep in the heavenly order of the gospel,
and in the government of the heavenly man, of the increase of which there is no end;
and walk in the pure and undefiled religion, that keeps you from the spots of the world,
and in the worship of God in the spirit and truth, which the devil is out of.
So that in the truth you may be preserved in peace with God, and one with another.
And in the spirit of truth you may be preserved in the unity and fellowship of it,
in which is the bond of peace.

And my desire is, that all the faithful men, and faithful women in the light, and power,
and spirit of Christ, all may be kept in the possession of the truth,
and that all such may make up the men and women`'s meetings,
so that you all may be in your possessions of the order of the gospel,
and the government of Christ the seed, that bruises the head of the serpent,
who is the head of all ill government and disorders.
So that the joyful and glorious order of the everlasting gospel,
all may be in the possession of; so that in the light, spirit, and power,
ye may all have a care of God`'s glory, and his honour, and his church`'s peace,
keeping in the unity of his everlasting spirit,
which is the bond of the heavenly and spiritual Prince of prince`'s peace.
And all that are in the possession of this may admonish
and exhort all such as walk not as becomes the gospel,
and glorify not the Lord with their bodies, souls, and spirits; and so see,
that as every one has received Christ Jesus, they do walk in him;
that all may walk in the holiness which becomes the house of God;
so that God may be glorified by his light, power, and spirit in all, who is over all,
God blessed forever.

And so the God of glory, who hath brought Christ from the dead,
by him are you quickened and raised from the dead,
that henceforth you should not live to yourselves, but to him, and walk in him,
who is the Amen, and over all, the first and last.

G+++.+++ F.
