== The substance of some other Brethren`'s Testimonies concerning G. F.

Luke Howard, together with the rest of the Friends of the quarterly meeting in Kent,
testify concerning the Lord`'s faithful servant, George Fox:
That he was an honourable elder in the church and family of God,
a man of an excellent spirit, with whom was God`'s power, council and wisdom,
and that it dwelt with him, in doctrine,
and overseeing the whole flock of God`'s pasture: His labour of love was to God`'s glory,
by which many were begotten unto God;
he did see the fruits of his travel unto the third generation;
he declared the everlasting gospel amongst us through God`'s power,
to the convincing of many and confirming them in the faith; and causing many to tremble,
and the devil to rage; and afterwards the Lord sent the said G. F. again,
to appoint men`'s and women`'s meetings,
and to see that the whole family was kept in good order, as becomes the house of God:
also, that blessed instrument gave forth many good epistles and instructions,
both in print, and manuscript, for the edifying of the body,
and building of it up in the love of God,
who made him shine in the church unto the end of his days.
We have often felt the life and love of God in his ministry,
and never saw him applaud or set up himself; but in the Lord`'s name and power,
he withstood that spirit that hath risen up to oppose God`'s work.

Kent, the 5th of the 8th month, 1691.

[.asterism]
'''

Ambrose Rigge, concerning G. F.--That the Lord visited him early in our age,
with his gospel day of life and salvation,
and made him his messenger of glad tidings to many,
and an able minister of the New Testament (or covenant) not of the letter,
but of the spirit, and endued him with power from on high,
to proclaim the acceptable day of the Lord,
then ready to dawn and spring in the hearts of many,
who had long sat in darkness and under the shadow of death:
He preached the gospel of peace and salvation, not with enticing words of man`'s wisdom,
but in the demonstration of the spirit and power,
and an effectual door was opened in the north,
and many through his ministry were turned from darkness to light,
and from the power of Satan unto God,
and gathered to the true shepherd and bishop of their souls;
for he did not preach himself, but Jesus Christ.
Of this I was a witness, that he was a stranger and a pilgrim on earth,
and went to and fro, and light, wisdom and understanding began to increase:
he laboured in the power of the spirit, to build up a spiritual house for God,
and temple for the Holy Ghost to dwell in: he testified of the life of the son of God,
that it was the light of men, given to direct them into the way of peace and holiness.
He travelled through many sufferings, trials and tribulations;
in perils (by sea and land) and at last by false brethren;
but the Lord`'s power was his shield, and defended him to the end of his days,
from all the darts of opposition of the adversary.
He was a goodly person, and of an amiable countenance, and lived to a good old age,
and was gathered in peace unto his fathers, and rests in eternal glory:
and upon his death bed he testified, that the holy life and seed,
in which all the families of the earth are blessed, reigned; and this I must say also,
that whosoever grieved him, or smote at him, in words or writings,
must bear their own burden in the day of account.
This testimony laid upon me to give.

Ryegate in Surrey, the 6th of the 12th month, 1690.

[.asterism]
'''

John Taylor:--In the name and power of the Lord,
I give this short testimony for that worthy and honourable man of God, George Fox;
that he was an instrument by whom I was convinced of, and confirmed in the blessed truth,
and gathered into the fellowship of the gospel, which he was a true minister of,
and a faithful labourer in God`'s work and service, to the conversion of many.
The Lord did very wonderfully appear with him, for the gathering of people to himself,
having given him the word of reconciliation to preach to the poor and needy,
whereof I am a living witness.
When I first went to him, he treated me in meekness like a lamb; he took me by the hand,
and said, young man, this is the word of the Lord to thee,
there are three scriptures thou must witness to be fulfilled, first,
thou must be turned from darkness to light; next,
thou must come to the knowledge of the glory of God; and then,
thou must be changed from glory to glory; and this had such an impression on me,
that I was fully satisfied he was sent of God, and the word of life was with him;
and what he then said unto me,
was more effectual than all that I had ever heard from all my teachers before,
to the settling and confirming me in the faith of Jesus Christ;
and I praise the Lord that sent this his faithful witness,
with the gospel of peace and glad tidings to my soul.
He devoted himself to the service of God, seeking to gain souls to him,
having a constant care upon him, for the settling of the churches of Christ in peace;
I am assured that his memory is blessed, and he will be had in everlasting remembrance,
and that he is entered into that rest that abides forever;
though the sense that was upon me of the great loss,
and great want that would be of this valiant champion of the Lord,
cannot be expressed nor known as yet; and seeing so many worthy men,
and champions of God have been taken away from amongst us of late,
who finished their course,
and received that crown of life and glory that was laid up for them,
my earnest breathings and prayer to God is, that we may all double our diligence,
and walk in the holy order, and under the rule and government of our Lord and master,
Jesus Christ, our captain and bishop of our souls,
that he over all may have the glory and praise forever, and ever, amen.

York, the 2d month, 1691.

[.asterism]
'''

Richard Robinson`'s Testimony of G. F.--That the
Lord raised him up and made use of him in early days,
in his young years, and sent him abroad in his power, endued him with his wisdom,
and made him prosperous in his hand, to the gathering many to the Lord,
and the glory of his arisings, and turning them from darkness,
and the ways and works thereof, unto the true light, and from the power of Satan,
unto the power of the living and true God;
and confirming the faithful in that testimony God had given him.
He became famous, honourable, and of good esteem amongst good men;
and the word of God`'s eternal power dwelt plenteously in him:
the judgment of the Lord having fallen upon me (for my rebellion) and continued so long,
that I began to question if I had not slighted the day of my salvation.
This messenger of the Lord came into our parts in the third month, 1652,
who taught that every man was enlightened,
and had a measure of light and grace from the Lord Jesus Christ,
and that if it was obeyed and followed, it would lead to God, but being disobeyed,
would become men`'s condemnation, which reached home to my understanding;
and from that day and time I became affected to him,
and that people that holds forth that doctrine, and lived up to the same,
although they were but few that then professed the truth in these parts:
I found him to be a man fearing God and loving righteousness,
endued with the spirit of judgment, and discerning, of a sound mind,
and with gifts and graces becoming a true minister of the Gospel,
a messenger of our Lord Jesus Christ;
in a great measure being learned in Christ`'s school,
in the things relating to God`'s kingdom;
he stood in defence of the truth against all opposition,
and in all things he came to be tried with; he did approve himself a minister of God,
in much patience, in afflictions, imprisonments, tumults, sufferings and travels;
through whose labour, diligent testimony, and good example,
many have been turned to the Lord,
and had occasion to rejoice in the God of their salvation;
and being gone to his rest with the Lord, he is ceased from all his labours,
travels and exercises, and his good works follow him;
I have observed that a heavenly divine virtue did attend him, to the converting,
uniting and preserving the Lord`'s people out of rents and divisions;
and it hath been sealed upon my spirit, that his soul is with the Lord,
to rest in the paradise of his pleasure forevermore.

Countersell, Yorkshire, the 21st of the 12th month, 1690.

[.asterism]
'''

John Bowater`'s Testimony.--A short testimony for our honourable brother in the faith,
G+++.+++ F. It is about thirty years since I first heard him; his matter was sound and weighty,
though not with enticing words of man`'s wisdom,
but in the demonstration of the spirit and power of God, opening many weighty things;
he travelled up and down in God`'s power,
to gather people from the idol shepherds (that only feed themselves) to God,
that people might know the true shepherd and bishop of the soul, and his voice in them;
through many trials the Lord upheld him,
and delivered him out of many prisons he was cast into;
he travelled into many countries and islands beyond the seas,
into some of which I afterwards travelled,
and saw the fruit of his labours in many places, where he had settled many monthly,
quarterly and yearly meetings, that are of great service in many parts of the world,
though some angry and unruly spirits were offended, as some were against Moses;
though there was not a meeker man upon the earth,
yet some said that he took too much upon him, as some have,
concerning this faithful servant of Christ,
whose labour and care was all along to promote truth;
since God first sent him forth to preach his gospel, his care was, to keep things sweet,
clean and savoury in the church of Christ, and that care might be taken for the poor,
fatherless and widows; and not many days before his decease, to wit,
the 5th of the 11th month, 1690, about eight days before his departure,
at our Second-day morning meeting, I much minded his exhortation to us,
encouraging Friends that have gifts, to make use of them,
mentioning many countries beyond the seas that wanted visiting,
instancing the labours and hard travels of Friends,
in the beginning of the spreading of truth in our days, in breaking up of countries,
and of the rough ploughing they had in steeple houses, etc. but now it was more easy;
and he complained of many Demases and Cains, who embrace the present world,
and encumber themselves with their own businesses, and neglect the Lord`'s,
and so are good for nothing; and said,
they that had wives should be as though they had none; and who goeth a warfare,
should not entangle himself with the things of this world.
The Lord took him away from the evil to come,
and delivered him out of the hands of his enemies, who hated him without a cause.

[.asterism]
'''

Edward Bourn`'s Testimony.--After a long night of apostacy,
the great God raised up our dear brother, G. F. to publish the everlasting gospel,
in the nation of England, and abroad in other nations,
whereby many were turned to the Lord, and found him whom their souls loved,
who is the desire of the righteous: in many tribulations and exercises,
this our dear friend passed through, the Lord was with him,
and did bless and prosper him in his work; I was often With him in person,
in several places;
Christ sent him forth to preach glad tidings and good things to the poor,
labouring in the universal spirit and grace of God, for the good of Adam`'s posterity,
that they might come to the knowledge of the truth, and be saved;
and in his testimony in our holy assembly,
he did not appear with the enticing words of man`'s wisdom,
but in the demonstration of the spirit and power of God, and with authority from him,
and they who had the savour of life in them had a sense of the same:
we cannot by commendation add to his happiness or
faithfulness in the service of the Lord,
for he was of a deep judgment and sound understanding;
and the spirit and power of truth witnesseth to me,
that he is amongst the faithful and chosen of the Lord, who died in him,
and whose works follow them; and his works and writings,
for the exalting of the ever blessed truth, and for the debasing of deceit,
will remain as a blessed memorial to generations to come.

Worcester, the 24th of the 4th month, 1692.

[.asterism]
'''

Leonard Fell`'s Testimony.--My testimony for my dear, true,
and well-beloved friend and father in Christ, George Fox.

He was a man that loved righteousness, and hated iniquity;
and the great God of heaven and earth wrought in him by his power and spirit,
and framed him according to his mind,
and fitted and furnished him for his great and heavenly work,
and then sent him into the world; and many were turned to righteousness by him:
for many years I frequented his company, and I never saw any thing by him,
but that he was kept from the spots of the world, and having finished his course,
and truly performed his heavenly father`'s great work and service, through many trials,
tribulations and exercises,
he hath laid down his head in peace and great joy with the Lord in his kingdom,
where his abiding place must be forever, and evermore.

London, the 13th of the 4th month, 1691.

[.asterism]
'''

Thomas Robertson`'s Testimony of G. F.--The blessed everlasting day of the Lord dawned,
upon him in our age; he preached the blessed light, and many became children of it,
whereby the darkness was driven away; he had the word of reconciliation,
whereby many were brought to God out of sin and evil,
and through judgment received mercy and refreshment from the presence of the Lord;
let all that are called to it tread in the same steps, and teach the same things,
that they may profit themselves and others.

The 20th of the 7th month, 1691.

[.asterism]
'''

Stephen Hubbersty`'s Testimony of G. F.--He was a
man filled with the divine power and wisdom of God,
which made him very honourable in the churches of Christ;
my soul loved him from the first; he was a father in Christ to me, and to many thousands;
God made use of him, for the turning of us from darkness to light,
and from the power of Satan to God, in which we have found eternal salvation;
God preserved him to see the head of the spirit of opposition broken,
by which he suffered deeply; he sought the honour of God, by whom he was highly beloved,
and of all good men; and the Lord took him in everlasting mercy to himself,
and the same mercy will be unto all those that walk in his steps unto the end.

[.asterism]
'''

Robert Jones`'s Testimony.--A few words by way of testimony,
according to the knowledge and experience that I had of my dear friend,
and honourable in the Lord his God, G. F.

I certainly believe, that the Lord found him out,
and fitted him for his work and service, and did empower him from on high,
to go forth in that great and glorious work, whereunto he did commission him,
making his overcoming power manifest through him,
to the turning of many from darkness to the holy pure light,
and from the power of Satan to the power of God:
for the word of the Lord went through him as a lamp that burneth,
opening the eyes of many that sat in darkness,
and dwelt as in the region of the shadow of death; many are the witnesses thereof:
Oh how was he carried through so many trials, deep exercises,
and sufferings of various sorts, both by sea and land?
Surely it was the Lord his God, who clothed him with his holy armour,
that the arrows of the uncirmcumcised could not hurt him (though
ever so many and violent) for his life was hid with Christ in God.
I had knowledge of him above thirty years, being with him in many meetings,
and at my own house and elsewhere,
by whose testimony was refreshed and made glad in the Lord;
for his testimony was not with enticing words of man`'s wisdom,
but in the power and demonstration of the spirit of the most high God,
both sound and pertinent, to the edification of the hearers,
in great plainness exhorting people to wait to feel the power of God in themselves,
and keep to it; the children of the light can witness for him,
that his doctrine was sound and weighty;
the light of Christ he laboured to turn the minds of people to,
whereby they might witness the seed of the kingdom,
to have dominion in their inward parts.
What shall I say?
In the blessed seed he lived, and died,
and is ever with the Lord his God to behold his glory.
I have sometimes admired the great goodness of the Lord,
in prolonging his days (which was of great service to the
church of Christ) considering his great infirmities of body,
by reason of his sore and hard sufferings.
Well, good was, and is, the Lord that preserved him, who is gone to eternal rest,
and has left a good savour behind him.
To this as a testimony for, and in behalf of my dear friend deceased,
I in truth of heart subscribe my name, as above written.

The 20th of the 5th month, 1691.

* * *

====== A Testimony from Friends of Berkshire, viz. Oliver Samsom, John Buy, John Giddens, and others, of the labours and travels of our dear friend, G. F.

He was a father and an honourable elder in the church of God, a faithful pastor,
and a diligent and careful overseer over the whole flock of Christ in his time;
and in the universal spirit of love and life, he laboured abundantly,
to the advancement of the kingdom of God,
and the increase of the government of Christ Jesus,
and establishing the good order thereof in all places wherever he came.

And we in this county were partakers of his labour of love and fatherly care,
having been often comforted and refreshed by his ministry,
which was not in the words of man`'s wisdom,
but in the demonstration of the spirit and power of God; and also by his epistles,
which were of great benefit, full of divine counsel, good exhortations,
and wholesome admonitions, all tending to the confirming, strengthening,
and building of us up in our most holy faith and
hope towards God and our Lord Jesus Christ;
and also for the ordering our conversations aright,
and to bear our testimonies as christians faithfully in the world.
And when divers (inclining to an undue liberty) against the counsel of God given them,
run out into a spirit of strife and contention, and since into an open separation,
whereby the tender-hearted, who abode in the truth, were sorely grieved and burdened,
and became great sufferers, and were often distressed and bowed down;
in this season of great exercise, did our dear friend, abovesaid,
G+++.+++ F. tenderly sympathize, and send many greetings of tender love,
fatherly care and sound advice, whereby christian encouragement was received,
and divine strength renewed unto them who were near ready to faint,
who with joy to God`'s glory can testify,
that he hath many times lifted up the hands that hung down,
and strengthened the feeble knees: and although those contentious persons,
in a spirit of strife opposed him in the work of God,
seeking to lay waste and make void his labours, and to overcome him;
yet the Lord bore him up, so that all his enemies by all their striving against him,
were so far from prevailing,
that they always wounded themselves against that rock whereon he was fixed.
Wherefore we (many of us) having received much comfort and benefit,
did look upon ourselves in duty obliged to give forth this short testimony,
as a thankful remembrance of his labours and travels amongst us,
desiring it may stand to posterity, for the honour and glory of the ever-living God,
who so gloriously appeared, and dwelt, and wrought in him,
which made him a blessing to the nation.

The 30th of the 11th month, 1691.

=== Oxfordshire Friends`' Testimony.--For that faithful and honourable servant of God, and minister of the everlasting gospel of Christ Jesus, G. F.

He was a true and faithful labourer in the work and service the Lord called him unto,
in turning many from darkness to light, and from the power of Satan to Christ,
the power of the living God; and the Lord was with him,
and made his work to prosper in his hand; insomuch, that in a short time,
many that were as scattered sheep, that had no shepherd,
were by him gathered (as an instrument in the hand of the Lord) to Christ,
the true shepherd and bishop of the soul; for he came forth in the name of the Lord,
in his mighty power, in the breaking forth or dawning of his glorious day,
and sounded the trumpet out of Zion,
that gave a certain sound (and an alarm from the Lord`'s holy mountain) in this our age,
which alarmed the nation,
and awakened many of the inhabitants thereof unto righteousness;
for the power of the word of the Lord through him, shook the sandy foundations of many,
and overthrew the Babylonish buildings,
which many people had built in the time of darkness and ignorance,
and nature of unrighteousness;
then was the deceitfulness of Babel`'s builders laid open and discovered,
which made them rage like the troubled sea (and to call
to rulers to help them) and like the craftsmen of Ephesus,
that made silver shrines for Diana, for they began to see their trade was in danger.
(Oh!) the wonderful work of that time;
this alarm was sounded from north to south through this valiant warrior of the Lamb,
by whom the Lord wrought wonderful things,
who never turned his back in the day of his spiritual warfare:
some of us can well remember when he first came up
out of the north country into the south parts,
with dread, power and authority, which he was attended with from God;
which made the hearts of many to fear and tremble;
for many that were as sturdy oaks and tall cedars, high in notion and profession,
were made to bow at the power of the word of his testimony:
he was endued with a spirit of discerning of the false spirit, and opposed it,
and gave a true and just judgment upon it,
which was of a very great service to the church of Christ;
for he was in the hand of the Lord as a wall of defence
to the lambs and little ones of the flock of Christ,
in the days of their infancy.
As to his ministry, it was plain, yet powerful, consisting much in prophetical openings,
declaring the day was come in which God was fulfilling the prophecies of the prophets,
though not decked nor flourished with the words of man`'s natural wisdom,
but delivered in the gospel simplicity, power and demonstration of God`'s eternal spirit,
and in the wisdom of God, so known only to the truly sanctified.
He was a man given up to serve the Lord, and to spend himself and be spent,
endeavouring to promote the truth, that the knowledge of it might increase in the earth,
and all sober-minded and well-meaning people, of what religion or profession soever,
might be brought to the knowledge of it,
that in it they might find rest and peace to their immortal souls,
little minding the things of this world,
but the things of God relating to man`'s happiness in the world to come.

He was a man greatly beloved; for all good people that truly feared God,
and loved Christ the truth, that were acquainted with him,
loved him for the truth`'s sake, and had an honourable esteem of him,
as indeed he was worthy of double honour, who ruled well in the church of Christ;
not seeking his own things, but the things of God, and the welfare,
peace and prosperity of his church and people; not exercising lordship,
or seeking dominion over them, but rather cherishing all the tender-hearted;
but a terror he was to the evil doers, and zealous in his testimony against deceit,
to the end of his time; for which cause evil-minded men, hypocrites and deceivers,
hated him: he was unto such as a butt or a mark to shoot at;
and it may be said of him in that respect, as it was said of Joseph;
many archers shot at him, and they hated and grieved him, but his bow abode in strength,
when their`'s was broken, and the arms of his hands were made strong,
and continued in strength by the hands of the mighty God of Jacob;
and no weapon formed against his life ever prospered;
nor any tongue lifted up in judgment, but was by his innocent life condemned,
whereby he was made to stand in his testimony to the end,
over the heads of all his enemies, to the finishing his course in faithfulness,
and the laying down his head in peace; and is (we are satisfied) at rest in Christ,
whom he faithfully served, and hath left a good savour behind him:
so we shall conclude with this short testimony,
that he was a blessing in the hand of the Lord to many thousands in this nation,
and other nations, and his memorial will live through generations to come;
in whose behalf our souls have cause to bless the name of the Lord,
and to render to him the praise, honour, glory and thanksgiving, for he only is worthy,
who is over all the heavens and the earth, God, blessed forever, and forevermore.

Thomas Gillpin, Bray Dolly, Silas Morten, Thomas Nickolis, Thomas Gilks,
Christopher Barratt, Nathaniel Falkner, Richard Vivers, John Haynes, Jeremiah Wearing,
Timothy Burborrow, Thomas Penn, John Watts, Alexander Harris, John Hewes, Henry Franklin,
John Long, Sen., Daniel Flaxney.
