== To All That Would Know the Way to the Kingdom





Whether they be in forms, without forms, or got above all forms.





A direction to turn your mind within, where the voice of God is to be heard, whom you ignorantly worship as afar off; and to wait upon him for the true wisdom.





That you may know truth from error, the word from the letter, the power from the form, and the true prophets from the false.

Given forth by one of those whom the world in scorn call Quakers.--G. F.

Christ saith, except a man be born again of water and of the spirit,
he cannot see the kingdom of God, nor enter into it, John 3:3,5,8.
So no man in his first natural birth can see the kingdom of God,
nor enter into it, nor know the things of God: for they that see the kingdom of God,
they must come to the spirit of God,
and the spiritual birth by which the things of God are known, and the kingdom of God:
and John the divine said, he was in the kingdom, Rev. 1:9. then he saw it:
and the apostle said, God hath translated us into the kingdom of his dear son:
so then these saw the kingdom, and were in it, Col. 1:13.

And as many as receive Christ, he gives them power to become the sons of God;
even to them that believe on his name, which were born not of blood,
nor of the will of the flesh, nor of the will of man, but of God, John 1:12-13.
This is the birth that sees, and enters God`'s kingdom.

I am the light of the world, saith Christ,
who enlightens every one that cometh into the world:
Christ hath enlightened every one that`'s come into the world.
Thou that lovest that light, which Christ hath enlightened thee withal,
thou bringest thy works to the light,
that thy deeds may be proved that they are wrought in God;
and he that walks in the light, there is no occasion of stumbling in him;
it teacheth righteousness and holiness; it will keep thee from lying,
and not let thee lie, and keep thee in tenderness of conscience towards God and man,
and never let thee swear; it will check thee if thou dost;
the light will not let thee take God`'s name in vain, it will let thee see if thou doest,
thou must not go unpunished; and will never let thee follow drunkenness,
nor vain company, for who lives in that nature, are without God,
and shall never inherit the kingdom of God; therefore beware,
this light will keep thee from adultery and whoredom, for such will God judge;
and the light will keep thee from theft, quarrelling and fighting,
and abusing thyself with mankind, and envy, and it will keep in the fear of God;
this light which is of God, lets thee see all the works of the world,
and draws thee out of the worships of the world, and keeps thee in the fear of God;
where the true wisdom is made manifest, the pure wisdom is made manifest to the pure,
and put into the pure heart, and then thy own wisdom thou wilt see with the light,
arising out of the earthly part in thee; which wisdom is sensual, and devilish,
and earthly: for while there is enviousness in thee, there lodgeth the man slayer,
and all the wisdom is from below, while that nature stands: there are sects,
and there are opinions, and there are conceivings arising out of this earthly part,
where lodgeth this wisdom, and self-conceit, and pride,
and by this wisdom the living God is not known,
and so all who dwell in this wisdom put the letter for the word,
and give meanings and expositions upon it,
and so gather together with the outward letter,
not having the power and life that gave it forth; so there are castles built,
and strong holds, and fenced cities, and high walls, as the Jews,
who had the outward form of that which was given forth from the power,
the form of the prophets, and Moses and David, and Abraham, who saw Christ,
who lived in power; but the Pharisees and the Priests getting their words,
knew not Christ; so it is now with this generation of the world: for you say,
ye know Christ, the Jews said, they were of Abraham, so they had gotten the letter,
and others`' words which had the power,
and all these are but imitations and likenesses which are above,
lifted up above the pure spirit, and here lodgeth the serpent in this earthly part:
but as the eternal light which Christ hath enlightened you withal, is loved, minded,
and taken heed unto, this earthly part is wrought out, the daily cross is taken up,
the fear of the Lord grows, the true wisdom increaseth,
the errors of the wicked are discovered and made manifest, the unjust comes to be slain,
the just comes to reign, the wisdom of the world comes to be confounded,
then the heathen begin to rage, then tumults arise.

But dwelling in the light, all sects, and all opinions and religions are discovered,
and stand naked before the Lord, (and before all who are of God,
and are seen with the eternal eye) that arise out of the earth, and the earth is but one,
and all such do raise their ground from the letter,
which was given forth from the power of God.
Now dwelling in the power, in the eternal light, all sects,
and opinions come to be judged and overturned, and seen to be chaff that is to be burned,
with that which cannot be quenched; for the light is but one, which is Christ,
who enlighteneth every one, and all are enlightened with one light;
every one taking heed to that light which Christ hath enlightened you withal,
it leads you out of sects, out of forms, out of the beauty of the world,
to live in life and power:
and waiting in the light which Christ hath enlightened you withal,
you come to be disciples of Jesus Christ, and servants to the truth,
and not to serve the lusts, nor the desires, nor pleasures, but the light judgeth them;
for serving the desires and the lusts, thou turnest into the beastly nature in the world,
and into the flesh, and comest to be darkened and veiled;
then thy throat is an open sepulchre, that thou drinkest up iniquity as it were water:
but dwelling in the light, it judgeth all that;
and all thy works and actions come to be judged by that light:
and all walking in this light which Christ hath enlightened you with,
you all walk in unity and sameness of mind, and lay away all guile, sin, and uncleanness,
and are all taught to fear the Lord God: and it will lead you to the church of God,
from the church of the world, and from your teachers, to cease from men,
to be taught alone of God, who teacheth eternal things eternally;
and leads the mind up out of external things.

And dwelling in the light, there is no occasion at all of stumbling,
for all things are discovered with the light: thou that lovest it, here is thy teacher;
when thou art walking abroad, it is present with thee in thy bosom;
thou needest not to say, lo here, or lo there:
and as thou liest in thy bed it is present to teach thee, and judge thy wandering mind,
which would wander abroad, and thy high thoughts and imaginations,
and makes them subject; for following thy thoughts thou art quickly lost.
But dwelling in this light, it will discover to thee the body of sin,
and thy corruptions, and fallen estate, where thou art, and multitude of thoughts:
in that light which shows thee all this, stand, neither go to the right hand,
nor to the left: here is patience exercised, here is thy will subjected,
here thou wilt see the mercies of God made manifest in death:
here thou wilt see the drinking of the waters of Shiloah, which run softly,
and the promises of God fulfilled, which are to the seed, which seed is Christ:
here thou wilt find a saviour, and the election thou wilt come to know,
and the reprobation, and what is cast from God, and what enters: he that can own me here,
and receive my testimony into his heart, the immortal seed is born up,
and his own will thrust forth, for it is not him that willeth, nor him that runneth,
but the election obtaineth it, and God that shows mercy;
for the first step of peace is to stand still in the light (which discovers things contrary
to it) for power and strength to stand against that nature which the light discovers:
here grace grows, here is God alone glorified and exalted, and the unknown truth,
unknown to the world, made manifest, which draws up that which lies in the prison,
and refresheth it in time, up to God, out of time, through time.

Whom God loves, he loves to the end, where the eternal unity is, there is all peace,
all clean, no jar, who are all of one mind, hid from the world`'s wisdom, knowledge,
comprehension, and thoughts which can never enter, as it is written,
the world by wisdom knows not God, and he is coming to confound the wisdom of the wise.
And the church in God, is not in imitation, gathered from the letter,
nor is a high-flown people in their imaginations,
but are they who are born again of the immortal seed, by the word of God,
which lives and endures for ever, which the world knows not; for the word cuts asunder,
hews down all wickedness, corruption, pride, and honour of men,
that all the honour and glory may be given alone to God; he hews down the first birth,
that he may establish the second, and raise up the second;
and the word of the Lord is a fire, burns up all the corruptions,
burns up all that is hewn down, and as an hammer to beat down, that nothing can stand it;
and this is the word by which the saints are born again;
you are born again by the immortal word, which lives and endures for ever,
and feeding upon the milk of the word, which word is God, which word became flesh,
and dwelt among us; so he (Christ) is the head of the church, and they are lively stones:
but all you now who put the letter for the word, and have got it in your minds,
and gather assemblies by it; this you cannot witness, and it is ignorance for you to say,
the letter is the word; when the letter saith, God is the word;
and it is a lie to speak and say, the steeple-house is the church; or to say,
they that are gathered by the form of the letter, is the church of God;
for the church is the pillar and ground of truth,
gathered by the eternal power that was before letter was; and all who are in this church,
as it is called of the world, and live in the comprehension of the letter,
and the earthly part yet standing, there is devilishness in your minds, and earthliness,
and pride, and filth; do but hearken to that light in thy conscience,
and it will let thee see so: and while those are standing,
such sacrifice God accepts not, and praises (while nature is standing) God accepts not,
which is Cain`'s, to which God has no respect, but to Abel`'s.

And God is coming to judge the great whore, all manner of opinions,
and all manner of sects and fellowships, (as you call them) all manner of her forms,
as every one that lives in God is coming to overturn and overthrow,
for they all lodge in her: all the foundation of them is in the earth,
and earthly wisdom, gathered in the earthly nature: he will overturn them,
that he may establish his own truth, his own truth in righteousness, his own kingdom.
Now the stone cut out of the mountain without hands,
begins to strike at the feet of the image, (that the head of gold begins to fall,
and the breast of silver, and thighs of brass, and feet part iron,
and part clay,) and his dominion is a dominion for ever over all,
and all who dwell not in this light, which Christ hath enlightened you withal,
you will be found too light, for he is coming to weigh all things in this balance,
and before him the hills shall move, and the mountains shall melt,
and the rocks shall cleave, who measures the waters in the hollow of his hand,
and his thunders begin to utter their voices, that the mysteries of God may be opened,
and the carnal hearts rent; great earthquakes shall be,
the terrible day of the Lord draws near, the beast shall he taken, and the false prophet,
into the fire must they go, for the beast and the false prophet have gone together,
the one has holden up the other.
Now is the Lord coming to sit as judge, and reign as king,
who is the law giver which shall go forth of Zion.
Now shall Zion arise and thresh to beat the hills, and thresh the mountains,
now is the sword drawn, which glitters and is furbished, the sword of the Almighty,
to hew down Baal`'s priests, corrupt judges, corrupt justices, corrupt lawyers,
fruitless trees which cumber the ground.
Drunkard, thou canst not hide thyself; cursed speaker, thou canst not hide thyself;
whoremonger, thou canst not hide thyself.
Awake, awake all people every where who live in forms, see what ye possess,
not having that eternal spirit that gave forth the scriptures; all your formal prayers,
formal preaching, formal singing, will be found as the chaff,
which is for the unquenchable fire; for Christ is risen, the true light shines,
the glory of the Lord appears, and you are discovered to him,
to be empty of that eternal spirit in your understandings,
which gave forth the scriptures.
I am the light, saith Christ, which enlighteneth every one; that light you hate,
and all who hate this light, set up teachers without them; but all who love this light,
are of God, and lead to God, which is a cross to all the world,
and this light is in every one; wait in it to receive Christ;
and as many as receive Christ; to them he gives power to become the sons of God,
which are not born of the will of man, nor by the will of man, but by the will of God:
and these are they who are out of imitations, and have no images, nor likeness of truth,
but are in it, and possess it: glory, glory to the Lord God for ever,
who governs his people, and is the head of the church, Christ is the head of the man,
God is the head of Christ.
He that can receive this, if he had not known the letter, let him.
He is come who was before the letter was written.
In the beginning was the word.

Now all you that hate the light, your deeds are evil: Christ saith,
he is the light of the world, and he enlighteneth every one that comes into the world:
the one he loves the light, and brings his works to the light, and walks in it,
there is no occasion of stumbling in him: the other he hates the light,
and will not bring his works to the light to be made manifest,
because his deeds are evil, and the light will reprove him: thou that sayest,
the light is natural, and that sayest,
Christ doth not enlighten every one that comes into the world, thou art a liar,
and blasphemer, and denier of Christ`'s words, and lays waste the scripture;
and thou that sayest, the light is natural, thou puts the letter for the light,
which is natural; darkness (true it is) cannot comprehend this light,
but the light makes manifest darkness, and this is the condemnation of the world,
the light that thou hatest, this light thou hast.
Christ saith, swear not at all, the light will say the same to thee, in thee:
Christ saith, he that lusteth after a woman committeth adultery with her in his heart;
this light will tell thee the same, bringing thy works to it, and loving it.
Christ cried woe against the Pharisee, the hypocrite;
this light will let thee see the same.
Christ will say, go ye cursed workers of iniquity; this light will say the same to thee,
in thee, who art a worker of iniquity; here shalt thou be condemned with the light,
and judged with the light out of thy own mouth;
this light will let thee see all thy hard speeches, thy venomous thoughts,
thy evil intentions, and covetous desires, which is idolatry, and dissembling,
and deceit, to be works of darkness, and let thee see that all those things are evil;
there thou hast learned thy condemnation, there is thy teacher,
that would teach thee to know God, there is thy condemnation,
hating that light that will condemn thee from him.
Thou wilt say, thou knowest in thy conscience that drunkenness is sin,
here thou lovest darkness rather than the light that shows it thee, and lying,
and swearing, and cursed speaking is sin, and yet thou followest it, and pleasures,
there thou lovest darkness rather than the light that shows thee them,
because thy deeds are evil; and there thou hast learned thy condemnation;
when God`'s righteousness shall be revealed in flames of fire,
thou shalt witness I speak truth.
Thou knowest theft is sin, and all unrighteousness God forbids;
thou wilt say something in thy conscience tells thee so; if thou hearken to that,
it will exercise thy conscience, and bring thee to repentance.
Christ saith, I call sinners to repentance; that light in thee calls thee to repentance,
and if thou hearkenest to that, thou hearkenest to Christ, and if thou hatest that,
thou hatest Christ, and God, then thou tamest into sorcery and evil,
into all uncleanness, and then God is not in thy thoughts,
and then thou art the disobedient one,
which disobeyest the light which God hath enlightened thee with,
and there the wrath of God abides on thee, and the prince of the air rules in thee,
as he doth in all the children of disobedience, who hate this light.

Now do not think that I hold free will here, man`'s free will,
I speak of that which is contrary to man`'s will,
and loving the light it will keep your wills from running,
and your wills from willing any thing, and keep them in subjection;
but he that hates this light, and makes a profession of God and Christ, and saith,
the letter is the word, and the four books of Matthew, Mark, Luke and John is the gospel,
he knoweth not Christ which is glad tidings, the lamb of God,
which takes away the sins of the world; for the letter takes not away sin.
And thou that sayest thou hadst not come to repentance,
if thou hadst not known the letter, thou deniest Christ,
who came to call sinners to repentance before the letter was;
it is he that calls sinners to repentance, and not the letter,
but the letter is a declaration of the word, God is the word;
and it is a declaration of the light, Christ is the light;
and it is a declaration of the spirit, but the spirit is not it; a declaration of power,
but the power is not it; the power, and the life, and the light,
was in them that spoke it forth, which ever the world hated;
therefore waiting in the light, which Christ hath enlightened you with,
that is scripture within you,
and that will open the scripture (according as you
grow in the light,) and the saint`'s conditions,
as you are sanctified, and as you are cleansed and made free by the son of God,
for it is he that maketh free; who are made free from sin, and from the world,
are made free by the son of God; and blessed be the father of our Lord Jesus Christ,
who hath raised him from the dead, and by him raised us up from the dead.

And to you that tempt God, and say, the Lord give us a sight of our sins,
priests and people, does not the light, which Christ hath enlightened you with,
let you see your sins, that lying and swearing, cursed speaking, theft, murder,
and whoredom, and covetousness, and pride, and lust, and pleasures,
all these to be the works of flesh, and fruits of darkness?
This light within you lets you see it,
so you need not tempt God to give you a sight of your sins, for ye know enough;
and waiting in the light, power and strength will be given to you;
for they that wait upon the Lord, their strength shall be renewed;
and living in the light, and walking up to God,
it will bring you to true hunger and thirst after righteousness,
that you may receive the blessing from God; and give over tempting of God,
as if he had not given you a sight of your sins.
And to all ye that say, God give us grace, and we shall refrain from our sin,
there ye have got a tempting customary word,
for the free grace of God hath appeared to all men, and this is the grace of God,
which shows thee ungodliness and worldly lusts.
Now thou that livest in ungodliness, lying, and swearing, and theft, and murder,
and drunkenness, and filthy pleasures, and lusting after the world,
thou art he that turnest the free grace of God into wantonness,
and casteth his laws behind thy back,
and walkest despitefully against the spirit of grace;
here the scripture is fulfilled upon thee! oh vain man! yet thou canst say,
God is merciful; he is merciful and just, and that shalt thou see,
when destruction comes upon thee; for thou canst say, God is merciful,
yet liveth in thy wickedness, passing on thy time without the fear of God,
sporting thyself in thy wickedness.
Oh ye covetous proud priests! which deceive the nation, who mind earthly things,
whose God is your belly, who glory in your shame, enemies of the cross of Christ,
your destruction is coming, that ye shall not make a prey upon the people any longer:
the Lord hath spoken it.

Oh ye great men, and rich men of the earth! weep and howl for your misery is coming,
who heap up treasure for the last day;
your gold and silver shall eat you up as the rust and the canker; the fire is kindled,
the day of the Lord is appearing,
a day of howling will be amongst your fat bulls of Bashan,
that all the tall cedars and strong oaks must be hewn down,
and all the loftiness of men must be laid low: then shall the Lord alone be exalted.

The free grace of God is the saints`' teacher,
which teacheth them to deny ungodliness and worldly lusts,
to live righteously and godly (like God) in this evil present world,
denying all the world`'s lusts, and world`'s ways, and world`'s teachers,
and works of darkness, which grace is turned into wantonness,
by those who follow the course of the world, and the works of darkness, drunkenness,
and uncleanness; and such are they who cannot abide sound doctrine;
which heap up teachers, having itching ears.
And all who turn from this grace of God, into wantonness, deny it to teach them,
and they live in their worldly lusts and ungodliness.
Oh how doth the land mourn because of oaths!
Oaths are heard in the streets openly belched forth.
Oh how doth the pride and haughtiness of men and women abound,
that scarce know how to walk in the streets!
Oh how doth oppression and tyranny rule,
that the cries of the poor are entered into the ears of the Lord of sabbaths!
Oh how doth drunkenness and drunkards walk abroad in the streets,
which devour the creatures!
The Lord is rising, and surely he will be avenged of all his adversaries.
He is come to sweep the land of evil-doers, that the earth shall yield her increase,
and the land enjoy her sabbaths: and he will sit judge,
and righteousness shall run down our streets, and God alone be magnified and glorified,
to whom it alone belongs for ever.
Oh how doth all the creation groan under this bondage of corruption!
the Lord is pouring out his spirit upon all flesh,
that his sons and daughters may prophesy up and down this great city,
and none shall make them afraid, crying for justice, crying for righteousness,
crying for equity: for the cry of the great whore is come up before the Lord,
who is adulterated from the truth; they who hate this light,
hate Christ which is the husband, and go from him; they who love the light,
have the husband which is Christ, but the judgment of the great whore is come,
who made all nations to drink of the cup of her fornication,
who must drink of the cup of the indignation of the
wrath of God poured out without mixture,
who must have it filled double.
Rejoice, rejoice all ye prophets and holy men of God, triumph in glory:
sing aloud praise to the Lord God Almighty, and Omnipotent, who is come to reign:
rejoice over the world, over the false prophets, over the beast, over the whore,
which is adulterated from the light, and tells all her lovers that the light is natural,
and so denies the husband Christ Jesus, and lives in fornication:
but all who love the light, and walk in the light,
witness Jesus Christ to be the husband, and this light is spiritual:
now she is convinced of her adultery, of her witchcraft, of sorcery,
and that which doth convince her is the light which Christ hath enlightened her with,
and this is her condemnation.
And now the judgment of the great whore is come, God will be avenged on her,
who has drunk the blood of his saints, who dwelt in the light, and loved the light.

All who hate this light, they set up to be their light such as are called of men masters,
have the chief places in the assemblies, stand making long prayers,
lay heavy burdens upon the people,
which devour widows`' houses (the widow has not a
husband) all are as widows who are devoured of such;
but who loves the light which Christ hath enlightened them with, it joins them to Christ,
and then they witness him to be their husband, and such as are not devoured of them.
And who hate this light, hold up them who bear rule by their means; which Jeremy,
who dwelt in the light, was sent to cry out against.
And they that hate this light, hold up them that cry for their gain from their quarters,
and never have enough, which Isaiah, who dwelt in the light, was sent to cry out against.
And they that hate the light go after the error of Balaam,
and hold up such who love the wages of unrighteousness;
and all who hate this light have the spirit of error, and they that dwell in the light,
know the spirit of error, and what the spirit of error follows:
and all who hate this light, hold up the hirelings that Micah cried against,
and such as call for the fleece, and clothe themselves with the wool,
that Ezekiel cried against, who was in the light, and full of the spirit.
Now where the same light is made manifest,
as was in the prophets which saw Christ the light,
and in the apostles the same light which gave forth the scripture,
all the scripture is witnessed; and here we are grounded upon the prophets,
upon the apostles, and Christ the corner-stone, in the eternal light,
by which we see the priests bear rule by their means now,
and seek for their gain from their quarters now, and are greedy dumb dogs now,
nay worse than Balaam, who loved the wages of unrighteousness,^
footnote:[Numbers, 22.18.]
but durst not take it; but these sue men at the law for it; worse than Simon Magus,
who would have bought the gift of the spirit, but these sell the letter:
this corrupt practice hath long reigned, but now is made manifest:
and in this light we see the hirelings that preach peace,
but he that puts not in their mouths, they prepare war against him; and by this light,
we see teachers who profess they are sent of Christ,
to be in the seat of the Scribes and Pharisees, and are called of men masters,
and have the chief places, going in their long robes, love salutations in the markets,
have the uppermost seats at feasts, and under pretence making long prayers,
devouring widows`' houses, which Christ cried woe against.

And such we cannot own as sent of Christ, nor hold up; for if we should,
we should deny the scriptures, and hold up that which Christ forbids:
and if we should hold up them who rule by their means,
we should deny Jeremiah to be a true prophet, who cried against such:
and if we should hold up such as cry for gain from their quarters, we should deny Isaiah,
who was sent to cry against such:
and if we should hold up such as go for gifts and rewards,
who love the wages of unrighteousness, we should deny the apostle,
who cried against such; for the same light is manifest,
(praised be the Lord God,) by which they are seen and cannot be owned,
but must be denied, as they were by the prophets, by Christ, by the apostles:
and if we should hold up such that say, revelations are ceased,
we should deny the son as they do, for none knows the father but the son,
and he to whom the son reveals him, and so we deny those to know Christ,
or to be sent of Christ, which deny the son, and deny revelations;
for the apostle (which was a minister of God) he was not a minister of Christ,
until the son was revealed in him, and then he preached him,
and preached the kingdom of God; so all who deny revelations,
deny the son and the father both, and live in their imaginations of the letter:
and the apostle exhorts the saints to have the loins of their minds girded up,
and hope to the end for the grace that was to be
brought to them at the revelation of Jesus Christ:
now he was a minister, and did exhort to wait for the revelation of Jesus Christ:
but now thou that deniest revelations, dost declare thyself openly, to be no minister,
and eraseth thyself out from among the ministers of Christ;
and thou that goest in the ways of Cain, thou art raised out from Abel,
for in thy heart lodgeth persecution, and thy mouth utters it, and thy hands act it.

And you that speak a divination of your own hearts,
are raised out from them who speak from the mouth of the Lord;
for the prophets of the Lord cried out ever against such, and so they do now:
and ye that seek for gain from your quarter,
are they that are shut out from the true prophets of God; they cried out against you,
and the same light cries out against you now,
otherwise the prophets should be made of no effect, for they spoke forth freely,
and so they do now that speak forth from the same light; the light is free,
which hath enlightened every one that comes into the world;
thou that hatest it hast learned thy condemnation;
it lets thee see all the evil deeds of thy heart:
and the gospel is free to every creature, not to be bought and sold for money.

Oh shameless men, that tell people the letter is the word, and buy and sell it for money,
which is a declaration of the word: and the grace is free,
which hath appeared to all men, which is the saints`' teacher,
and You need not have any other teacher, if you own the grace,
which shows your ungodliness and worldly lusts; this grace will teach you to deny them,
and the light which hath enlightened every one that comes into the world;
there`'s every one of your condemnation in particular that hates it,
and there`'s every one of your teacher that loves it; which is but one,
and will open all the figures, and the parables and types to you; and waiting in it,
it will guide you to God, there is your teacher;
but there is your condemnation who hate it:
every one of you shall eternally witness this;
to that which should exercise your conscience do I appeal,
for now the mighty day of the Lord is coming; meet him,
by putting off your works of darkness.

God that made the world and all things in it, dwells not in temples made with hands,
neither will be worshipped with men`'s inventions: but Israel,
when he had forgotten his maker, built temples; and Judah built fenced cities;
but the Lord will send a fire to devour them,
and all your songs shall be turned into mourning; the mouth of the Lord hath spoken it.
O then all ye that profess, see that you possess, and profess no more than you are. 

All who stumble at the light are without, and are not come to repentance,
and so all who stumble at the light, stumble at the door,
the door is known by the light which comes from Christ: and all who stumble at the light,
stumble at the way; for Christ hath enlightened every one, that,
with the light he might see the way (which is Christ) to the father.
So all who stumble at the light, stumble at the scriptures,
and know not the meaning of them;
for that eye that is turned from the light is the blind, and leads into the ditch,
and is to be condemned with the light from Christ: and all who stumble at the light,
never knew hope which purifies, nor faith which purifies,
nor the belief which overcomes the world; but he walks in darkness,
and doth not know whither he goes, and the children of light, which dwell in the light,
to him their condition is unknown, for he hates that which they walk in;
so with that he is condemned; and to you all this is the word of God.
And all who stumble at the prophets`' words, and cannot understand the words of them,
spoken from the light which was in them; and all who stumble at the light,
stumble at the apostles`' words,
which were declared from the light which was made manifest in all consciences,
which ministered to the spirits in prison: so all who stumble at the light,
they are to be condemned with the light from the life of the prophets
and apostles (which dwelt in the light) with the rude wicked world.
And here every one shall witness his condemnation just, and see it just,
with the light which shows him his evil deeds, and that Christ`'s words are true,
and to own his condemnation that hateth it;
and they are the children of the light that love it, and believe in it,
and with the light they see their deeds are wrought in God, to the praise of God,
and joy, and comfort of themselves.

