== The Vials of the Wrath of God poured forth upon the Man of Sin, and upon all Professors of the World, who deny the Light of Christ, which he hath enlightened every one withal, and walk contrary to it; with it they are condemned.

By him who is called George Fox.

=== The World`'s Profession without Foundation: with several precious Notes to great Men, and rich Men.

All profession of the world is without ground, and the foundation:
for the light is denied of the world, and hated: professors, priests, and people,
and all who hate the light, their deeds are evil,
and they will not bring their works to the light, lest the light should reprove them;
they know their deeds are evil; thou wilt not bring thy works,
lest the light should reprove them: drunkard, thou knowest thy deeds are evil;
thou wilt not bring thy works to the light, lest the light should reprove thee;
there thou hast learned thy condemnation, which is the light.
Liar thou knowest thou shouldest not lie, there thou hast learned thy condemnation,
the light; and swearer, and railer, thou knowest thou shouldst not swear, nor rail;
the light within thee lets thee see thy deeds are evil,
and makes thee confess thy deeds are evil; there thou hast learned thy condemnation,
the light.
Ye devilish minds, who are hatching mischief,
plotting together to do mischief in alehouses, and upon your beds,
something in your consciences tells you, you should not do so;
there you have learned your condemnation, the light; ye cursed speakers, envious ones,
quarrellers, fighters, stoners, wrathful, malicious ones,
there is something in your consciences tells you, all this is of the devil;
there you have learned your condemnation,
the light that Christ hath enlightened you withal,
which lets you see your deeds are evil, when you are sitting in alehouses, drinking,
carding, shovel-boarding, swearing by God, or your soul, or your faith,
or cursing and provoking one another to wrath, fighting and abusing one another;
so you are they that defile the flesh; there is something in your consciences tells you,
all this is of the devil; there you have learned your condemnation,
which is the light which lets you see all the works of darkness.

Now therefore hearken to the light, which may lead you up to God the father of light;
it lets you see, you should not lie, not steal, not commit adultery;
you should not walk in unclean actions, and all you that do,
you know your deeds are evil by the light in your consciences,
which is your condemnation, the light in your consciences which should exercise it;
and all you wanton lustful ones, sporting yourselves,
who gather yourselves together to spend your time in vanity,
there is something in your consciences tells you, all that to be folly, foolishness,
and madness: laughter is madness, saith the prophet, and who is grown solid and civil,
and denies such practices, that is counted madness with you, who live in folly;
there is that in your consciences lets you see your deeds to be evil,
you have learned the condemnation, the light;
and when the book of all consciences is opened, you will all witness what I speak.
To that in your consciences do I appeal;
then the time will come that you will wish you had not been born into the world.

Now you easeful ones are at ease, and you professors,
priests and people have set your nests so high as though none could reach you;
and all you conceited ones, who rest in your conceits; and you worldlings,
who are drunk with the cares of this life: and you covetous ones, who devour one another,
for the creature, for the earth,
the time is coming when the poor despised ones shall sit down with Abraham, Isaac,
and Jacob, and a cry will be among all you, and a howling,
a wishing you had never been born.

Liar, thou art for the lake that burns; unbelievers, you are for the lake;
drunkards and scorners, you are for the lake that burns,
and shall never inherit the kingdom of God, who act such things; drunkard,
thou hast cast the law of God behind thy back; and you that mind earthly things,
your end is destruction, whose God is your belly, who glory in your shame,
who live in the lust, drunkenness, gluttony, devouring the creation, a time will come,
that you will wish you had never been born; for you have all known in your days,
that your deeds have been evil,
and that you have done contrary to the light in your consciences;
there is your condemnation, the light;
for you wicked will be as the chaff which the wind driveth away,
and all you proud will be as the stubble; the mouth of the Lord hath spoken it.

This is to be scattered among the ignorant, simple and blind people,
led by the god of this world, and drunkenness, and lust,
that the witness may arise in them, against these ungodly deeds,
that they may be left without excuse, who have had a time,
and a visitation and call to repentance.
Now you have a time, prize it; you have light which Christ hath given you;
to it I appeal, which lets you see all your evil deeds, hating it,
it will be your condemnation.
To all manner of people I speak, it will eternally witness for the Lord, and condemn you.

Some are drunk with drink, sitting together to invent mischief, to shed blood,
to destroy the innocent.
Another company, priests and people, are got together, drunk with rage and persecution,
as drunk as the other are in rage and madness;
plotting and inventing together against the righteous, to shed innocent blood;
some you get into prison, and you are worse than common drunkards, for you stock,
and cause the innocent to be imprisoned.
Therefore awake all drunkards, and fear God, and turn unto the Lord while ye have time.

Pharaoh thou oppressor, Pharaoh thou task master, Pharaoh thou proud one,
which layest heavy burdens upon the innocent and righteous seed, and oppressest the just,
plagues and woe is thy portion, as was Pharaoh`'s, who taxes, and oppresses,
and causest the just and righteous seed to labour under thee; who bindest with oaths,
and compellest to swear by that which is a declaration of Christ, who saith,
swear not at all; and, he that doth not abide in the doctrine of Christ, hath not God,
but is of the devil.

O ye earthly-minded men! give over oppressing the poor;
exalt not yourselves above your fellow creatures, for ye are all of one mould, and blood;
you that set your nests on high, join house to house, field to field,
till there be no place for the poor, woe is your portion.
The earth is the Lord`'s, and the fulness thereof.
And you that have not so much of the earth, give over your murmuring, and reasoning,
fretting, and grudging, for all your want, is the want of God;
the righteous God is coming to give to every one of you according to your works:
now the works of you all must be tried;
you that have appeared unto men beautiful outwardly,
will be found in the generation of murderers, and you that have pretended to worship,
your sacrifice will be found to be Cain`'s, which God hath no respect to.

O ye high ones, which spread yourselves, appear fair, tall and strong!
You know not God, nor yourselves to be oaks.
O ye tall cedars!
Ye know not yourselves to be so;
the Lord hath sent to look for fruit in his vineyard among you,
but it is full of wild olives, and wild grapes,
that many are drunk with the juice of the wild grapes;
and so the vineyard is full of briars and thorns, that the lambs and sheep cannot pass,
but they are tangled among the briars and the thorns, and the land is as a wilderness,
full of serpents, and the earth is overgrown with weeds and nettles,
that there is no feeding for the lambs, till the earth be dressed, and overturned.

Howl ye vine-dressers! a day of howling is coming among you,
who have been pretenders to the dressing of the vineyards,
which are overgrown with weeds, and nettles, and thorns, and crooked ways;
the lambs and sheep have been scattered and devoured amongst the briars and the thorns,
and no discerning you have had betwixt a lamb and a goat, a sheep and a wolf.
Now the Lord himself is gathering his lambs and his sheep
where they have been scattered in this cloudy dark day,
and some are torn, and some are trampled upon with the horses of Pharaoh;
but the Lord`'s hand is against you, and his sword drawn; the battle is begun,
and the sword drawn,
which must not be put up till it hath made a separation in hewing down,
and the Lord himself will have the praise, and the honour, and the renown,
who rules over all.

O how beautiful hath thy harlot been!
O how full is the land of enchanters!
O how full is the land of sorcerers, and witchcrafts!
The mystery of her hath deceived many through her whoredoms.
Green was grass, and fresh was the flower, the bay tree spread itself, and the hawthorn,
but the time is coming of fading; the flower will fade, and the grass will wither,
and the whoredom and the enchanter must come to judgment: the Lord is risen,
and riseth as a swift witness against the enchanter, against the sorcerers,
against the whoremongers, and the covetous.
The glittering sword is drawn to hew down you fruitless trees that cumber the ground;
ye lustful fleshly ones,
you have not seen yourselves to be these trees which cumber the ground:
ye heady high-minded ones,
you have not seen yourselves to be these trees which cumber the ground:
ye who live in the flesh,
ye do not see yourselves to be these trees which cumber the ground: ye scorners,
ye liars, ye dissemblers, false hearts,
ye do not see yourselves to be these trees which cumber the ground;
but the Lord is risen against you, the earth stinks with the dead that are upon it,
and the pollution of the polluted.
The Lord is risen with power, and sendeth forth to bury the dead,
and to raise up the dead; all who are immortal, this may see, this may receive.

Repent, for the day of the Lord is coming.
Awake ye worldlings, hearken to that in your consciences, which shows you sin and evil;
that will guide you unto God, loving it.
Awake ye drunkards, and lustful ones, who follow pleasures;
consider the ways you walk in; for you who act such things,
must never inherit the kingdom of God; for you act contrary to that in your consciences,
which will be your condemnation; pride, and ambition, selfishness,
and self-will stands up, which the plagues of God are due unto; silence all flesh,
who live in your conceit and deceit, thieving and stealing in the night,
what the saints spoke, making yourselves drunk with it, and then sell it to drunkards,
and then are jovial, eating and drinking with drunkards.
Howl ye drunkards, for ye shall want the staff of bread;
a day of howling is coming upon you; lay aside all deceitful merchandise.

And all ye star-gazers, who are gazing among the stars,
wondering after your imaginations, doing the works of darkness,
in whom lodgeth the spirit of witchcraft.

Silence, and come down all ye that ride so high, that do bestir you as Jannes did,
and Jambres, at the coming of the children of Israel out of Egypt;
through the fire and the sea, ye cannot come.

Silence all presumptuous talkers of God, who see him not, but are presumptuous boasters,
who live in envy, crossness, and perverseness, and vain contention,
which proceeds from corrupt minds, who mind the earth, and earthly things,
who are enemies to the cross of Christ, who glory in your shame,
whose end is destruction, whose belly is your God, who do not see God,
are not come so far as Moses; for Moses saw God face to face;
and death reigns from Adam to Moses, and all that see not God, death reigns in you.
To that in your conscience I appeal, which Christ hath enlightened you withal,
which calls you to repentance, which shows you your evil deeds,
which will be your teacher, owning and loving it; and your condemnation, hating it.
Now you have time prize it; this is the day of your visitation.
