== A Word from the Lord, to All the World,

[.heading-continuation-blurb]
And all Professors in the World; spoken in Parables:
wherein all may come to read themselves through the Parables, and see where they are.
By G. F.

Man being drove into the earth out of Paradise, and death having passed over all men,
the flaming sword turns every way to keep the tree of life,
death having passed over all men; death reigned from Adam until Moses:
and as there is death within, so death speaks;
and though Christ hath given to every one of you a measure according to your ability,
and this measure is the light; yet one, he loves the light, and the other,
he hates the light, and this is the condemnation; he that loves the light,
and brings his deeds to the light, there is no occasion at all of stumbling;
this is the light that gave forth the scriptures; according as thou art grown up in it,
thou wilt read them again; and this light thou that hatest, thou stumblest,
because thy deeds are evil; thou wilt not bring thy deeds to the light,
least it should reprove them; thou knowest thy deeds are evil, this light shows thee,
there thou hast learned thy condemnation; thou knowest thou shouldest not lie, be drunk,
and that thou shouldest not steal, nor commit adultery;
this light will tell thee all this, and it will condemn thee, and reprove thee;
if thou lovest it and bringest thy works to it: but thy deeds being evil,
and knowing it will reprove thee, therefore thou hatest it,
and wilt not bring thy deeds to it, therefore this is thy condemnation;
here thou hast learned it,
when the righteousness of God is revealed through flames of fire upon thee,
then thou shalt see it is true; thou knowest thou shouldst not be proud,
delight in fashions and customs, and follow the world; this light will show thee,
and let thee see all that is vanity,
and bring thee sometimes to confess it and yet thy heart being hardened,
and the deceit strong, thou rejectest and hatest that which calls thee to repentance,
which lies low in thee, and continually calling thee to forsake thy lovers:
it tells thee thou shouldest not lust, nor covet, nor thieve:
it tells thee there is danger to all you thieves, and lustful ones, and covetous ones;
it speaks to you, and I tell you there will be your condemnation;
when the book of conscience is opened, in your own mouths ye shall be judged,
therefore take warning: when the vengeance of God falls upon you, then you will say,
you had time once, when it is past, and the plagues of God are poured upon you,
who hate to be reformed by that light in your conscience;
when God calls you continually to repentance, ye hear not his voice,
but trust in your own fancies and dreams, and lying divinations, and so hate the light,
for if you love it, it would bring you to repentance, and the fear of the Lord;
and the fear of the Lord is to depart from all sin and wickedness, and all evil,
and all respecting of persons, for thou that dost, respects not God`'s law,
which forbids it; for he that doth respect persons transgresses the law,
and is convinced as a transgressor, and commits sin; thou that dost not own this light,
which is according to the law of God, which respects no man`'s person,
that in thy conscience, if thou lovest it and hearkenest to it, it will exalt God alone;
ye proud ones at this may stumble, but to that in your consciences,
which should exercise it, I appeal.

And this light will bring you to walk in the commands of Christ; Christ Jesus saith,
in all your communications let your yea be yea, and your nay be nay,
for whatsoever is more, is evil; and swear not at all, for that was in the old time,
the swearing: now thou that dost not abide in the doctrine of Christ art of the devil;
swear not by the head, nor by Jerusalem, nor by the earth, nor by Heaven:
these are great noted things: I say, swear not by the bible,
which is a great noted thing, which you swear by now; if the Lord`'s oath be performed,
which he swear by himself, then all oaths are put an end to;
if the high-priest Jesus Christ be owned, then all the priests are put an end to,
which were true types and figures of him;
for he that holds up priests which receive tithes according to the law,
doth deny Jesus Christ come in the flesh:
but who loves the light that he hath given them, witness Jesus Christ come in the flesh,
but those are they which deny all the priests that receive tithes;
for the receiving tithes was in old time, though Abraham paid tithes to Melehizedeck,
who was a figure; when Jesus Christ the everlasting priest was come,
he put an end to all figures; and you that hold up the figures,
deny Christ come in the flesh.
There was a temple which God commanded; when Christ was come and risen,
all outward temples were denied; and we witness one priest,
which is over the household of God, ten thousand witness one priest,
which is entered into the holiest; and all the priests and his hirelings are denied;
and all such as go after covetousness, to make gain of the people, are denied,
and all such as bear rule by their means, and seek for their gain from their quarters,
are denied; and all such as are called of men masters,
and have the chiefest places in the assemblies,
are denied by such who have one master Jesus Christ,
to whom all power is given in heaven and earth, who masters over all,
and hath conquered all, subdued all, reigns over all heaven and earth,
judge over all heaven and earth.
And the mighty day of the Lord is coming;
God that made the world dwells not in temples made with hands,
neither is he worshipped with the works of men`'s hands, seeing he is Lord of all,
hath given to all breath and life, made of all nations man of one mould,
to dwell upon the face of the earth,
and is coming to fill his with the knowledge of himself.
To all you that are unlearned outwardly, of the letter,
that cannot read the scripture outwardly, to you I have a word from the Lord to speak;
which is, Christ saith, I have given to every one a measure, according to their ability;
this is the measure, the light which is pure, which doth convince thee,
and if thou dost take heed to this light, that is scripture within thee;
as a man should give, or a king should give to his subjects,
or to them that are under him, every one a measure of the outward;
so Jesus Christ the king, gives every one a measure of the inward,
according to their ability; as the king doth outwardly according to their ability,
and so that is a figure to thee, and if thou waitest in this measure,
and improve thy measure, and be faithful in thy measure to God who hath given it thee,
then thou comest to be a servant to the king Jesus Christ;
as the servant outwardly doth improve his outward measure, and serve the king outwardly,
so thou comest to improve thy inward, that is a figure to thee;
so figures are spoken to the carnal part in man.

And as the light opens and exerciseth thy conscience,
it will open to thee parables and figures, and it will let thee see invisible things,
which are clearly seen by that which is invisible in thee,
which are clearly seen since the creation of the world,
that doth declare the eternal power and Godhead;
that which is invisible is the light within thee,
which he who is invisible hath given thee a measure of,
that will let thee see thy heart to be stony;
and as stones without thee of the like nature, and the highway ground without thee,
so thy heart is high-way ground; and as thorny ground without thee,
so thy heart is as thorny ground; and as thou walkest up and down,
it will let thee see the rough way without thee, and rough way within thee;
and as thou walkest in the way full of briars and thorns without thee,
so crooked ways within thee it will let see; as there are briars without thee,
so there are briars within thee; and as serpents without thee,
so the nature of serpents within thee; as vipers without thee,
so the nature of vipers within thee; and all this lodgeth upon the earth;
the earth without thee, so the earth within thee; as lions without thee,
so the nature of lions within thee; trees without thee,
so thou art the nature of a tree which riseth out of the earth;
as trees grow out of the earth without thee, trees within thee; as forests without thee,
so the wilderness in thy heart; these things doth the scripture speak of;
who had the light spoke forth these parables, to that nature in men and women:
this light lets thee see, who hatest the light: as fat bulls without thee,
feeding the flesh, thou art as a fat bull, who only feedest the flesh;
as here are dogs and swine without thee, thou art a dog that bitest and devourest,
and barkest, there is thy figure that barkest; as swine without thee,
thou art a swine wallowing in the mire; and as a foul house without thee,
thou art the house; as a candle lighted up in the house without thee,
the candle is lighted up in thy heart, which is the spirit of the Lord,
and thou wilt see the house foul, there is thy figure.

As tall cedars without thee, thou wilt see thyself a tall cedar,
who livest without the truth, spreading thyself: and as strong oaks without thee,
thou in thy strength wilt see thyself as a strong oak, who art full of earth,
and livest in thy power and dignity; and as horses without thee,
thou who livest in earth and filth, and lust, thou art as a horse neighing up and down,
this the light will let thee see; as asses without thee,
snuffing up their noses upon the mountains, thou art lifted up in thy high-mindedness,
and full of pride and wildness, thou wilt see thyself to be as a wild ass;
and as the grass without thee, which is green for awhile,
thou wilt see thyself to be as the grass that grows upon the earth,
which is green for awhile, but is suddenly cut down;
the light within thee will let thee see these things;
and as cutting down without thee with a sickle, so cutting thee down;
as reaping without thee, so reaping thee down, hewing the wicked:
here thou mayest learn thy figure, who art reaping and mowing,
as thou art walking in the field, thou mayest read scripture;
as flowers are beautiful for a time, so thou that art famous,
thou that art beautiful in thy glory, thou art as fading flowers,
there thou mayest learn thy figure;
this light will let thee see the good ground without thee,
so are they who are the good heart, plowing up without thee,
so plowing up the fallow ground within thee; as thou hearest the thunder without thee,
so thou mayest hear the thunder within thee; the voice without, so the voice within thee;
these are figures: as the earthquake without thee, so earthquake within thee;
and as mountains without thee, so mountains within thee; as hail-stones without thee,
so hail-stones within thee; as wolves without thee, so the nature of wolves within thee;
here thou canst go no way but thou mayest read thy figure.

As beasts without thee, so thou art the nature of brute beasts,
that turnest from the light of God in thee; as the canker without thee eating,
so the canker within; as the sea without thee, so the wicked are as the sea,
the like nature of the sea within thee; as foaming without thee, so foaming within;
as harvest without thee, so harvest within, who come to see with the invisible eye,
all they that mind the light shall see another harvest;
as there are many sowing the seed without, that lies under the clods,
so shalt thou see the seed that lieth under the clods in thee;
and as the summer without thee, so are the children of God brought into the summer,
where there is joy and peace, and are brought out of the world;
and as singing of birds without thee, so are they that are brought out of the winter;
the world is a figure to them; as a turtle-dove without thee,
that is a figure who comes to this joyful land; as doves without thee,
nature of doves within; as lambs without thee, the nature of lambs within;
as sheep without thee, so the nature of sheep within; and as goats without thee,
the nature of goats within; now the light of God gave forth all these figures,
like unto that nature in man, and of what the saints should enjoy;
and this light will let thee see, as there are fowls without thee who have nests,
so thou who art flown above the truth, art as a fowl that hath a nest,
the nature of fowls within: and as there are dragons that devour without thee,
so there is the nature of dragons that devours the righteous,
and acts contrary to that pure principle in thy conscience;
and as a bed of sorrow without thee,
so thou must be brought (that harloted from the truth) into the bed of sorrow within.
And as there is a widow without thee, which hath not a husband,
so thou art a widow which hath not Jesus Christ,
who followest such priests as are called of men masters; as a garden without thee,
and dressing it without, so is Christ and his spouse the saints:
as there is a weeding without thee, so the weeding of the weeds in the heart:
thistles without thee, the nature of thistles within thee; sour grapes without thee,
thou that are turned from the truth, hast the nature of sour grapes in thee:
as thou seest the wild grapes without thee,
which set the children`'s teeth on edge without thee, so they set their teeth on edge,
who are growing in the earth, and take off that which acts contrary to the light,
and the light will let you see it; as the night without thee and darkness,
so there is night within: and as stars without thee, so there are stars within thee;
as moon without thee, so there is moon within thee: and as clouds without thee,
so there are clouds within thee.
These are all figures; and as the sun without thee,
so the sun of righteousness arising with healing in his wings within thee.
All who mind the measure which God hath given you,
it will open unto you these outward figures which God spoke, and will teach you;
as you go up and down you shall read your figures; as covering without you,
so there is covering within; woe to him that is covered,
and not with the spirit of the Lord; and as fire and an oven without thee,
and as stubble without thee, all you proud,
and all you wicked are as stubble to be consumed in the fire, as fire doth the stubble.

Now this light will show you these figures:
here thou mayest read scriptures thou that lovest the light;
thou that hatest this light canst not see these figures.
But it is the invisible that opens these, that gave them forth;
and here thou that art unlearned in the letter, mayest read the scripture,
and as the secret chambers without thee, hearken to the light within thee;
and it will let thee see the secret places, where the retired place,
the secret chambers are; and as a prison without thee, so there is a prison within,
where the seed of God lies; and as there is threshing without thee,
it will let thee see threshing within thee; chaff without thee, the chaff within;
wheat without thee, so there is wheat within:
this light of God which gave forth the scripture,
this light of God according to its measure will open the scripture to thee;
for man being drove into the earth, and the earth being above the seed;
so as the earth without thee, so the earth within thee; the Lord speaking low things,
comparisons like to that nature in man;
that man may look upon the creation with that which is invisible, and there read himself;
there thou mayest see wherever thou goest.

And to all you the word of the Lord, that hath learned the letter of the scripture,
your Hebrew, Greek, and Latin, who hate the light within,
and say every one hath not the light; to you shall I open my mouth in some parables.
Ye are the painted walls, as ye see the painted walls without you,
so you are painted walls, there is your figure: and as you see men stumble without you,
which are blind; so do you which say that every one hath not the light,
and that every one is not enlightened:
for ye stumble at the eye which should let you see,
and your mouth is the mouth of the false prophet, which the scripture speaks of:
the true prophet saith, he enlighteneth every one that comes into the world;
and there was but two, and there are but two;
and thou that sayest he doth not enlighten every one that cometh into the world,
and he saith he doth enlighten every one that cometh into the world;
thou art the false prophet, and goest about to make Christ a liar,
who is the true prophet:
ye are the hypocrites who are hipt above the truth with your fair faces;
and ye are the thieves which steal your neighbours`' words, and ye are filthy dreamers,
which say, Christ hath not enlightened every one that comes into the world,
they speak a lie, the divination of their own brain; and sell the prophets`' words,
and Christ`'s words for money, which was spoken forth freely.
Ye tell people ye preach the gospel, who minister the letter, and know not the gospel;
and yet tell them that the letter is the word; and the letter saith God is the word;
and ye tell them the letter is the light; and the letter saith Christ is the light:
the Lord is coming in flames of fire, flames of fire without you,
as you see with a natural eye, see flames of fire within,
who have the light come upon you: you ungodly ones, as a sword without, which hews down,
so shall ye that are wicked find the sword of the Lord, which is the word of the Lord,
hew you down: and as you see fire burning without you, so ye that hate the light,
shall see the fire within you; and as you see wells without water without you,
so you shall see within you wells without water:
so ye that say every one hath not the light; and as a cloud without you,
so are ye clouds without water, and all your knowledge, Hebrew,
Greek and Latin is natural; and the, natural man knoweth not the things of God.

Therefore to all people every where, to that light in you I appeal,
which shows you sin and evil to be works of darkness, and deeds of the flesh.
O the old man!
There is your teacher, and there is your condemnation, hating that light:
and ye are they that get the saints`' words in the old bottles,
and ye give meanings to them,
ye who are of the generation that murdered ever the righteous seed;
as bottles without you, so are you bottles, new wine put into new bottles,
the old wine put into old bottles, and that is a figure:
and as trees with leaves without, that bears no fruit,
so are they that have profession and no life, nor no fruit;
as sons and daughters without, born by the will of man,
so there are sons and daughters of God, born by the will of God, heirs of another world;
as these are born in this world, and as there is the world without you,
so there is the world in the heart; as there is the field without,
so there is the field in the heart; as there is the merchant-man without,
that seeks for pearls without, so there is the merchant-man that seeks for pearls within;
and as there is the kingdom without, so there is the kingdom of heaven within;
and as the axe is laid to the tree-root without, to hew down the tree without,
so the axe is laid to the tree within, that brings not forth good fruit;
and as trees cumber the ground without upon the earth, so do men cumber the ground;
fruitless trees; and as there are rocks without, there are rocks within;
as there is cleaving of rocks without, so there is cleaving of rocks within;
as there are heavy burdens without, so there are heavy burdens within,
the pure are burthened and as the rain falls upon the plants without,
so doth the mercy of God fall upon the tender plants within;
as there is a vineyard planted without, so are the people of God a vineyard;
who love the light, and have the invisible eye, will read these figures and parables;
and ye need not go to your natural priests without you; but this within will open them,
as you love it, and walk in it as the saints did, who gave forth the scripture,
and they exhorted others to take heed to that light, and said,
ye have a more sure word of prophecy, unto which ye do well to take heed,
as unto a light shining in a dark place, till the day dawn,
and the daystar arise in your hearts.

And this light is your teacher, which teacheth you holiness,
and teacheth you the fear of the Lord;
and this light hating of it will be your condemnation, and then you stumble,
and then you neither understand parables nor figures,
but are they that stumble at noon day; all you who are earthly,
minding that which is invisible, ye will read the earthly parables and figures,
and see the time of winter; as there is winter without, so there is winter within,
the time of winter, and the time of summer, if you wait to get through the earthly part;
the earth must be removed,
and the earth must be shaken when the glory of the Lord ariseth.
This is witnessed; so God Almighty open your understandings, all people every where,
that you may see yourselves.
And if you take heed to that light which will exercise your consciences,
it will let you see yourselves, which eye is the light,
and this light will let you see God; but if your minds go forth,
the God of this world cometh in and takes the dominion, and so your minds are blinded,
and your understandings darkened: therefore every one, what you possess, profess,
for the saints were what they spoke;
and every one as Christ hath given you a measure according to your ability,
mind your measure, and improve your measure, and let the saints`' conditions alone,
but as you find them fulfilled in you; and lay aside all contention,
and striving about words, which is no profit, but mind the pure light of God within,
which will teach every one to know God, and so every one must improve his talent,
and improve his measure according to his ability;
so every one will be rewarded according to his works, whether they be good or evil.

And thou that sayest every one hath not the light, who art the blind Pharisee,
I shall stop thy mouth with a few words, which the servants of God hath spoken forth.
Christ himself saith, which is the true light,
he doth enlighten every one that cometh into the world, and the one he loveth it,
and the other he hateth it.
And this is the condemnation of the world, that light is come into the world,
and men love darkness rather than light, because their deeds are evil;
and thou that sayest he doth not enlighten every one that cometh into the world,
and there thou art a false prophet, and a witness against Christ;
and thou that sayest the grace of God hath not appeared to all men to teach them,
thou art he that tamest the grace of God into wantonness;
and to thee the grace hath appeared,
for that is grace that shows the ungodliness and worldly lusts,
and there thou goest to make the apostle a liar, when the grace of God, he saith,
(which we witness,) hath appeared to all men,
which teacheth us to deny all ungodliness and worldly lusts, and to live godly,
and soberly, and righteously in this present world;
and this grace hath appeared to thee who livest wickedly and ungodly,
and art of this present world; to that in thy conscience I appeal,
which thou shalt eternally witness, for to it the grace cometh and appears;
and when the book of conscience is opened, all men shall be judged out of it:
and here thou that sayest every one hath not the light in his conscience to exercise it,
thou goest about to make God unjust; for the light which lets man see sin and evil,
is a perfect light of God;
and thou that sayest every one hath not a measure of light within them,
to show them all their works and actions which they do,
thou goest about to make God unjust, and unrighteous,
and to keep the creature in darkness,
for God saith he will give to every one a reward according to their works;
and if he had not a light how should he see his works,
and how should the world be judged in righteousness?
But blind hypocrites must show themselves,
that they may openly appear blind to all them that are in the light, and love the light;
and you that hate the light, there is your condemnation.

