== A Visitation to the Jews

[.heading-continuation-blurb]
From them whom the Lord hath visited from on High,
among whom he hath, performed his Promise made to Abraham, Isaac, and Jacob.

[.heading-continuation-blurb]
The mighty Day of the Lord is come, and coming,
who dwells not in Temples made with Hands,
nor is He worshipped with Men`'s Hands, but in the Spirit,
from whom the Scripture was given forth. By G. F.

To the Jews scattered, who are of the seed of Abraham, to whom the promise belongs,
who have long had the words, but missed the promise, which promise is to the seed.
From them who are of the seed, who witness the promise, to you this is sent.

From them that are of the seed of Abraham,
to all the scattered Jews according to the flesh, who have the law of God,
the form of it, but being found out of the life of it,
have not possessed that which Moses saw, who received the law from God,
which law you have the form of, and your fathers in ages past had,
who put Christ to death, and slew him that is the end of the law, God`'s righteousness,
Christ Jesus, the end of God`'s righteous law, to keep out of all unrighteousness.

And your fathers, that had the form of the law,
slew the prophets that showed the coming of this just one, Christ Jesus,
the end of his righteous law, God`'s righteousness; they having the prophets`' words,
and Moses`'s words, but out of the prophets`' and Moses`'s life,
who saw the just one that was to come and suffer, were those that slew the prophets.

David saw the just one, and called him Lord;
and Moses saw him which received the law from God, which law was given to your fathers,
which you have had the form of, who said,
"`Like unto me will God raise you up a prophet from among your brethren,
and him they should hear,
and every one that would not hear that prophet should be cut off.`"

Now your fathers that had Moses, who saw this prophet, and received the law from him,
who said, God would raise up this prophet, and he came among your fathers,
that had the law, and Moses`'s words, but not Moses`'s life; and the prophet`'s words,
but not the prophet`'s life; they knew him not, neither heard him,
though he was a prophet, raised up from among the brethren;
and was made of the seed of Abraham, according to the flesh,
but declared to be the Son of God, according to the scriptures, by signs,
wonders and miracles, devils being made subject to him, loosing many from their chains,
which were kept under bonds;
and yet your fathers believed not that prophet which Moses saw, and the prophets saw,
who was come to fulfill what was written of him; neither heard they him,
though it was Moses`'s command they should, and God`'s command:
so therein were in the transgression, though the law the words of it they had,
but found in the transgression, out of the life of the law, and the life of the prophets,
and came to be mingled among the heathen which knew not God,
who be in the same transgression, though you profess the words declared from the life;
wherefore being out of the life of the prophets, being raised up among your fathers,
who speak of this just one, of this prophet; your fathers did persecute them,
and did put them to death; and at last the Son came.

And to your fathers spoke a parable, which was agreeable to the prophet`'s words:
as a man letting forth a vineyard to husbandmen,
and he sent his servants to look for fruits, and they beat one and cast him out,
and wounded another, and killed another; and last of all he sent his son;
and when they saw the son, the heir of the vineyard, come,
said they to the keepers of the vineyard, this is the heir, let us kill him,
and cast him out, then the vineyard will be ours.
And these things your fathers did fulfill, they killed him, they cast him out,
and delivered him up to the Gentiles to be mocked, scourged, and crucified.

Now consider, what hath become of you since, of you husbandmen?
Have not you been laid waste?
And was not the word fulfilled concerning his coming and rising up from among the brethren?
And when he was come among them,
he would have gathered them as a hen gathereth her chickens under her wings,
but your fathers would not.
And he showed them how they stoned the prophets, and killed them;
and how wise men should be sent among them, and scribes and prophets,
some of them they should crucify and scourge in their synagogues,
because they neither knew the Father, nor the prophet that he had raised up,
which Moses spoke of.

Wherefore, saith he to Jerusalem, behold your house is left unto you desolate.
Hath it not been so?
Was he not a true prophet to you herein?
Are not your houses unto you left desolate?

Are not this prophets words here fulfilled on your fathers, and you scattered,
which prophet Moses spoke of, who went up to Jerusalem,
and was betrayed by him that David spoke of, unto the chief priests and scribes,
who condemned him to death, and delivered him to the Gentiles to be mocked,
scourged and crucified, but the third day he rose again; and saith Christ,
it cannot be that a prophet perish out of Jerusalem.

This the prophet spoke to your fathers, of whom you have the form of the law,
and the words of the prophets, which killed the prophets, and yet built their sepulchres.

Here you may see your fathers, and as it was with them, so it is with you,
being now found in the same transgression, until you come to the life of the prophets,
and of Moses; then with the life you see him who is the end of the prophets and Moses,
even the Emanuel spoken of, born of a virgin, which is Christ.

Now coming to the life the prophets were in, and Moses was in, with that,
this you will come to see; and with it you will come to the conversion,
and see the everlasting offering.

And Christ the Emanuel, this prophet whom Moses speaks of, and the prophets saw,
(who said,
it could not be that a prophet perish out of Jerusalem) was delivered
by the chief priests and scribes to be condemned to death,
and delivered to the Gentiles to be mocked, scourged and crucified: +++[+++now mind,]
he was betrayed into the hands of the chief priests and scribes,
and was condemned to death,
and by them delivered to the Gentiles to be scourged and crucified.

Now saith Christ, when you shall see Jerusalem compassed with armies,
then know that the desolation thereof is nigh:
hath not Jerusalem been compassed with armies, and hath it not been laid waste?
Your house desolate, and scattered as the prophet said?
Hath not Jerusalem been compassed with armies, where the prophets were slain?
And saith the prophet, they should fall by the edge of the sword,
and be led away captive into all nations,
and Jerusalem should be trodden down of the Gentiles,
to whom your fathers delivered him to be crucified to death,
until the time of the Gentiles was fulfilled.
+++[+++Now mind,]
are not these words fulfilled which the prophets spoke whom God raised up?
Is not Jerusalem trodden down?
Have not you been carried captives into other nations!

Have not the Gentiles trodden Jerusalem under foot?
Hath it not been compassed with armies?
Have not your houses been left desolate?
Have not some fallen by the edge of the sword?
Have not they come upon you, the Gentiles, whom you delivered this prophet unto,
to be mocked and crucified?
And have not they laid Jerusalem waste?
And hath not the temple been thrown down, and not one stone left upon another,
which Solomon was commanded to build, as Christ foretold, who was a greater than Solomon.
So consider,
are not the words of this prophet fulfilled on you that had the words of the prophets,
but being out of the life, knew not the substance?
and being strangers from the life of Moses, who had the life of the law,
and strangers from the life of the prophets; you see not God`'s purpose, nor decree,
nor determined counsel,
which had showed unto his prophets of the coming of the just one before he came,
before whom your fathers being in the transgression,
out of the life of the law and the prophets, chose a murderer, Barrabas,
and the chief priests persuaded the people to ask the murderer, and to crucify the just.
Doth not this show that they were in the state of the murderer.

And when the just was risen, whom neither death nor bonds could not hold,
according to the determinate counsel of God, as David who foresaw it, said,
he would not leave his soul in hell, nor suffer his holy one to see corruption.

The chief priests, and those that set a guard on Christ after they had crucified him,
when the news came he was risen, gave large money to the soldiers to say,
that his disciples came by night and stole him away;
and this report hath gone among the Jews, and so blinded you with a lie,
for a lie is of the devil, and he it is that is out of the truth, and abode not in it,
that blinds the eye, and casts a mist before their eyes, that they should not believe,
and so believe the lies before the truth.

For had your fathers known Moses and the prophets in the life; they would have known him,
the just one, the holy one, whom God would not suffer to see corruption,
though he was numbered among transgressors, and among them he made his grave,
whom God highly exalted at his right hand, to whom thrones,
powers and dominions must be subject, who is the end of God`'s righteous law,
God`'s righteousness, which the prophet Esay spoke of,
who could not hold his peace for Zion`'s sake,
and for Jerusalem`'s sake he could not rest,
until the righteousness thereof go forth as brightness,
and the salvation thereof as a lamp that burneth.
And the Gentiles shall see thy righteousness, and kings thy glory;
and thou shalt be called by a new name.^
footnote:[Isa. 62:1]
This righteousness is come forth, and the Gentiles see it, and doth burn as a lamp,
and the brightness and salvation thereof is witnessed among them,
and the vengeance of our God is proclaimed, the acceptable year of the Lord is come,
and comfort to all that mourn; the good tidings are preached to the meek,
the brokenhearted are bound up; liberty is proclaimed to the captives,
and the prison doors are opened, and they that are bound go forth,
who sing of his glory;^
footnote:[Isa.
61]
and the Gentiles see his righteousness and profess it,
and the Lord is an everlasting light to his people, and God their glory.
For we can call salvation our walls, and gates praise.
And the sons have come from far, this is witnessed; and behold, saith the Lord,
Gentiles shall come to thy light, and kings to the brightness of thy rising,
lift up thine eyes round about thee, and all that gather themselves together,
they shall come to thee from far; and saith the Lord, arise, shine,
for thy light is come, for the glory of the Lord is risen upon thee: behold,
darkness shall cover the earth, and gross darkness the people,
but the Lord shall arise upon thee, and his glory shall be seen upon thee.^
footnote:[Isa.
60]
This light the prophet saw the Gentiles should come to,
and kings to the brightness of thy rising.
And saith the Lord by his prophet,
is it a light thing that thou shouldest be my servant to raise up the tribes of Jacob;
take notice, and restore the preserved of Israel, take notice again;
I will give thee for a light to the Gentiles,
that thou mayest be my salvation to the ends of the earth.^
footnote:[Isa. 49:6]

Now mind, the light to the Gentiles, and salvation to the end of the earth,
which now the Gentiles profess; the prophet who was in the life, saw this: and many,
as it is said before, do witness this light to the Gentiles,
and salvation to the ends of the earth, the redeemer of Israel,
the raiser up of the tribes of Jacob; and this is the redeemer of Israel, the holy one,
to him whom man despiseth, to him whom nations abhorreth, to a servant of rulers,
kings shall see and arise,
princes also shall worship because of the Lord who is faithful,
and the holy one of Israel, and he shall choose thee.^
footnote:[Isa.
49.7]

And thus saith the Lord, I will lift my hand to the Gentiles,
and set up my standard to the people, and the people witness the standard,
and the hand is witnessed, which to the Gentiles is lifted up of the Lord God.

Behold my servant whom I uphold, my elect in whom my soul delighteth;
I have put my spirit upon him, he shall bring forth judgment to the Gentiles:^
footnote:[Isa.
42]
and the Gentiles now witness this judgment brought forth to them,
and this judgment is set in the earth: he shall not fail nor be discouraged,
till he hath set judgment in the earth, and the isles shall wait for his law:
now many of the isles do witness this law, who have waited for it, which is royal.

Thus saith the Lord, he that created the heavens, and searched them out,
he that spread forth the earth, and that which cometh out of it;
he that giveth breath to the people upon it, and spirit to them that walk therein;
I the Lord have called thee in righteousness, and will hold thy hand, and will keep thee,
and give thee for a covenant of the people, for a light of the Gentiles:^
footnote:[Isa. 5:6]
Now this covenant to the people,
and this light to the Gentiles that the prophet speaks of, the Gentiles witness now,
and the people witness this covenant of God, and God`'s promise fulfilled.
And them that were ministers of this covenant,
were sent to turn the Gentiles from darkness to the light;
and those Jews and those Gentiles that did believe in the light,
did believe the everlasting covenant, and did receive the everlasting covenant,
and the glory of Israel; and this brought in the Gentiles to light,
which broke down the partition-wall between the Jew and the Gentile,
and of twain made one new man:
which covenant of light the prophet saw before he was come; and when he was come,
your fathers owned him not, neither received, though by signs and wonders, and miracles,
confirmed he his ministry, and that he came from God; yet said they blasphemously,
which had the prophets`' words, and Moses`'s words, but out of the life of both,
that by Beelzebub the prince of the devils he cast them out.

And here they having the words, and not the life,
when he was come that the words spoke of, they that had the words knew him not,
and the Gentiles, their minds being alienated from the life of God,
and strangers from the covenant of promise, and commonwealth of Israel,
to them the light was promised, and that to it the Gentiles should come, which many did,
and do now enjoy, and know the unsearchable riches that are hid in God, Christ Jesus.

And the Jews and the Gentiles receiving the light, the covenant of promise,
they come to be baptized with the spirit into the one body;
and that covenant of light which brings in the Gentiles,
lets see the end of the first covenant, that doth decay,
and lets see the everlasting covenant, Christ Jesus (who came to fulfill the law,
and not to break it: heaven and earth shall pass away,
but not one tittle of the law shall pass away till
all be fulfilled.) The law of life is perfect,
converting the soul,^
footnote:[Ps. 19:7]
and brings it from under that which was against it; and so at this covenant of God,
the light of the Gentiles, the Jews stumble, which covenant the prophets prophesied of,
and your fathers in those days stood against;
and so here is the saying of the Lord (which is the law of life) fulfilled:
the builders rejected the corner-stone; and as David said, their table became a snare,
a trap, and a stumbling-block,^
footnote:[Ps. 69:22]
and a recompense unto them: and hath it not been so?
I say, then, have they stumbled that they should fall?
God forbid, but rather through their fall salvation is come unto the Gentiles,
for to provoke them to jealousy; take notice of that.
Now if the fall of them be the riches of the world, and the diminishing of them, +++[+++mark,]
the riches of the Gentiles, how much more their fulness; I speak to you Gentiles.^
footnote:[Rom.
11: 2, 12]

So here, who are come into the life of Moses and the prophets,
do witness that which Moses and the prophets said should come to pass,
that Christ should suffer, and rise from the dead,
and show light to the people and to the Gentiles,
in which light Jews and Gentiles are one; I will make an everlasting covenant with you,
saith the Lord, even the sure mercies of David;
behold I will give him for a witness to the people,
a leader and commander to the people;^
footnote:[Isa.
54: 55-56]
behold thou shalt call a nation that knew thee not, and nations that knew thee not,
shall run unto thee: now this everlasting covenant is witnessed, to which nations run;
and the people witness the leader (which you that had the covenant which
did decay stood against) and do enjoy the covenant of peace and authority;
which you do not, that have not the life, which I will not remove,
saith the Lord that hath mercy on thee; and every one that keeps from polluting,
takes hold of this covenant; as for me, this is my covenant with them, saith the Lord,
my spirit that is in thee, etc.
So the everlasting covenant is witnessed, which doth not decay,
with which is seen that which doth decay; I will make an everlasting covenant with them,
and their seed shall be known among the Gentiles; and saith the Lord,
my glory shall be declared among the Gentiles,
and I will take of them for priests and Levites, saith the Lord; and behold,
saith the Lord, the day is come,
that I will make a new covenant with the house of Israel, and with the house of Judah,
not according to the covenant which I made with their fathers in the day
when I took them by the hand to bring them out of the land of Egypt,
which covenant they broke, though I was an husband to them, saith the Lord;
but this shall be the covenant which I will make with the house of Israel;
after those days I will put my law into their inward parts, and write it in their hearts,
and will be their God, and they shall be my people,
and they shall teach no more every man his neighbour, and every man his brother, saying,
know the Lord, for they shall all know me, from the greatest to the least,
saith the Lord, for I will forgive their iniquities,
and I will remember their sins no more: mind this, you that have this first covenant,
which was given to your fathers when they came out of the land of Egypt;
but saith the Lord, I will make a new covenant,
not according to the covenant I made with your fathers, which was to decay,
for there you had a law in tables of stone writ;
but here in this covenant you shall have the law written in your hearts,
with which you shall come to know the Lord, and need not say, know the Lord:
and here is the covenant which was everlasting.
Now the covenant which was made with your fathers,
while that was standing you were to be taught of the Lord;
but this covenant being witnessed and received, the law-writer in your hearts,
you shall no more every man teach his brother, and his neighbour, saying, know the Lord;
for all shall know him, from the greatest to the least.

And now thousands do witness this second covenant, this everlasting covenant,
not according to that covenant given to your fathers in tables of stone,
but the everlasting covenant written in the heart, where they know the Lord:
and these witness the second covenant, where the iniquities are forgiven,
and the sins and transgressions the Lord will remember no more.^
footnote:[Jer.
31]

If these ordinances depart from before me, saith the Lord,
then shall the seed of Israel cease from being a nation before me forever,
and I will give them one heart and one way, that they may fear me forever,
for the good of them, and of their children after them:
I will make an everlasting covenant with them,
that I will not turn away from them to do them good,
but I will put my fear into their hearts, that they shall not depart from me.

So you that had the covenant given to your fathers
when they came out of the land of Egypt,
stood against his covenant, though it was witnessed by Moses and the prophets,
which you read; so you stand against the promise of God to you,
which now thousands of the Gentiles do witness, the covenant of light,
which to them was promised, with which they knew God,
and so are come unto the life of the law,
and covenant of God which reconciles Jews and Gentiles together;
which brings to see that he is God of both, and brings them to one;
so that which doth convert, brings into the life that the prophet spoke of,
and Moses spoke of, which God to them did let see, and the promise,
which things is come to pass, and the life of the law and the prophets is witnessed,
and he that sits on the throne of David now reigns.

And again, thus saith the Lord, if you can break my covenant of the day, +++[+++take notice]
and my covenant of the light, that there should not be day and night in their season.
Mark, this covenant which orders day and night in their season,
then may also my covenant be broken with David my servant,
that he should not have a son to reign upon his throne; and this is the covenant,
and this is the king of the Jews, whom they would not have to reign.
And this is he who bears his Government upon his shoulders, which is without end;
and this is the heir, and this is he that is come for judgment into the world,
to make them blind that say they see, and to make them see, that see not.

And this is the question that lies upon you to answer, if he was David`'s son,
how did he call him Lord?
Now as you come to the light, you will see it, and him that shall,
and doth reign on the throne of David, with the priests, Levites and ministers;
as the host of heaven cannot be numbered, neither the sand of the sea measured,
so will I multiply the seed of David my servant, saith the Lord.

Now he that sits on the throne of David, his seed witness him Lord and king,
who is the prince of life, that hath dominion over death,
and through death has destroyed him that hath the power of death;
and repentance is preached, and remission of sins through faith in him,
from whom comes the refreshing into the soul, who is the bishop of it;
and as they cannot break the covenant that keepeth day and night in its season (for
they was made by him who was the covenant) so they cannot break this covenant with David,
that he should not have a son to reign on his throne;
if they can break that covenant that orders day and night,
then they may break this covenant with David my servant,
that he should not have a son to reign on his throne.
They shall set their faces towards Zion,
saying come let us join ourselves to the Lord in
a perpetual covenant that shall not be forgotten.^
footnote:[Jer.
33]
Now the everlasting covenant written in the heart, by which you need not say,
know the Lord, brings from among the heathen,
separates from among the strangers and aliens from the life of God, as the Gentiles were.

Though the Lord by his spirit in the prophets spoke of the promise,
that he should be a light to the Gentiles, and that they should see his glory,
which many now do enjoy, and embrace and see him who sits on the throne of David,
him whom Abraham, David, and Isaiah saw, and Jeremiah saw,
and the prophets gave testimony of, and Moses, who said, God would raise up,
and the people should hear him, and the people doth hear him;
yet they which had the words, being strangers from the life of God,
knew him not when he was come, and God had raised him up,
but denied the resurrection of the just one.

And Jesus Christ, the Emanuel that Moses spoke of, the prophet which God raised up, said,
"`Think not I am come to destroy the law, but to fulfill it;
(whom your fathers thought was out of the life of it,) saith he, it was said in old time,
thou shalt not commit adultery;`" +++[+++mark]
commit it: but I say unto you, he that looketh on a woman to lust after her,
hath in his heart committed adultery already.
Now mark, here is the law written in the heart,
here is the new covenant that the prophet speaks of, which is agreeable to Moses,
and to them all, that which fulfils the law, not breaks it.

And the law saith,
"`Thou shalt do no murder;`" but your fathers which had garnished
the sepulchres of the prophets which their fathers had killed,
desired a murderer before the just one, the Emanuel, the Saviour, him whom Moses,
the prophets, and Abraham did give testimony of; and they said,
"`His blood be upon us;`" and Christ said,
"`All the righteous blood from Abel to Zacharias,
should be required of this generation.`"
So have you not been driven into other nations, and your houses been desolate since,
and Jerusalem trodden under foot,
where the prophets perished that showed the coming of the just one;
and at last the Son was cast out by you, upon whom the Gentiles hath trodden.

But now is the Lord gathering to himself, and his name is great among the Gentiles,
and the remnant of Jacob shall be in the midst of many people, (which now is witnessed,
and his tent is known,) as the dew from the Lord, as the showers on the grass,
that tarries not for man, +++[+++take notice,]
nor waits for the son of man;
and the remnant of Jacob shall be among the Gentiles in the midst of many people,
as a lion among the beasts of the forest, as a young lion among the sheep,
whom if he goes through, he tears down, and tears in pieces, and none can deliver;
now this is seen among many people.

And in that day saith the Lord, there shall be a root of Jesse,
which shall stand for an ensign of the people, to it the Gentiles shall seek,
and his rest shall be glorious.^
footnote:[Isa. 11:10]
Now the Gentiles have found this glorious rest, and to this ensign,
this root of Jesse they do seek, which this day is fulfilled among them, and witnessed;
glory to the Lord God the highest forever: and he shall set up an ensign for the nations,
and shall assemble the outcasts of Israel, and gather together the dispersed of Judah,
from the four corners of the earth.

Now this ensign is set up for the outcasts of Israel, for nations,
and to the gathering of the dispersed of Judah from the four corners of the earth;
now you owning the light, you own this ensign,
(and this ensign now is witnessed,) and we see it,
and have that set upon the throne of David;
for the Lord will utterly destroy the tongue of the Egyptian sea,
and there shall be a highway for the remnant of his people,
which shall be left from Assyria, +++[+++take notice,]
like as it was to Israel in the day that he came up out of Egypt.^
footnote:[Isa.
11]

And where this covenant, (that is everlasting,) of light is received,
with it the first is seen that doth decay; and thus saith the Lord, I will hold thy hand,
I will keep thee, and give thee for a covenant of the people,
and a light to the Gentiles, to open the blind eyes,
to bring out the prisoners out of the prison,
and them that sit in darkness out of the prison-house.
I am the Lord, that is my name, and my glory I will not give to another; behold,
the former things are come to pass, and new things I tell you of,
before they spring forth, I tell you of them.

Now, when these things were sprung up among you, and come to pass,
that had the first covenant given to you, when you came out of Egypt; these new things,
this new covenant you received not,
though to you it was declared by the prophet before they did spring forth;
and this covenant of the people, the light of the Gentiles, opens the blind eyes,
brings out the prisoners out of the prison-house,
and this is he that preaches unto the spirits in prison:
now you and your fathers that have rested in the former things,
not beholding nor seeing the new things that are come to pass,
and declared to your fathers before they came to pass,
shows how you have refused the corner-stone,
(which have been builders of the words without life,) the covenant of light,
the prince of peace, the Lord of glory, he that sits on David`'s throne, that comes,
(as it is written in the volume of the book,) to do the will of God.

So the new things which were declared by the prophet before they sprang forth,
you that remain in the old have rejected, and have you not been rejected, +++[+++mark]
and provoked by a people that were not a people!
Have not the Gentiles which followed not after righteousness, obtained the righteousness,
even the righteousness of faith in Christ Jesus, the covenant of light,
the light of the Gentiles, among whom his name is great,^
footnote:[Rom 10]
and their eyes are opened, and the prisoners come out of the prison-house,
and in him do the Gentiles trust.
And thus saith the Lord, in an acceptable time have I heard thee,
in a day of salvation have I helped thee, I will preserve thee,
and give thee for a covenant to the people, to establish the earth:
I will give thee (saith the Lord) a light of the Gentiles,
that thou mayest be my salvation to the end of the earth.
Now he that establisheth the earth, the covenant witnessed, by whom all things were made;
what?
is he salvation to the end of the earth, the covenant of light?
yea, who enlighteneth every man that cometh into the world, which Isaiah spoke of,
which your fathers had their will on.
And thus saith the Lord, I will preserve thee,
and give thee for a covenant to the people, to establish the earth,
to obtain the inheritance of the desolate heritage; +++[+++mark]
this covenant of the people to establish the earth,
which obtains the inheritance of the desolate heritages, and says to the prisoners,
go forth, and to them that are in darkness, show yourselves; which is now fulfilled,
and fulfilling; they shall feed in the way,
and their pasture shall be on the tops of the hills,
and these witness the fresh springs of water,
and this is witnessed among them that witness his covenant,^
footnote:[Psal.
18]
and are converted to God, to serve the living God in righteousness,
who are come to the life of the prophets, and possess that which they spoke of;
therefore did David give thanks to the Lord among the heathen,
and sing praises to his name; great deliverance gives he to his king,
to David and his seed,
(whose seed we are forevermore;) and Moses that received the covenant from the Lord,
when your fathers came out of Egypt, said,
"`Like unto me will the Lord thy God raise thee up a prophet from the midst of thy brethren,
him shall ye hearken unto:`"^
footnote:[Deut 18]
now this prophet did Stephen witness and hold forth,
when he was brought before the council, whom they cast out and stoned.
Your fathers had the tabernacle of witness in the wilderness, as he had appointed,
speaking unto Moses, that he should make it according to the fashion which he had seen,
which also the fathers that came after brought in with Jesus,
into the possession of the Gentiles, whom God drove out before the face of our fathers,
unto the days of David, who found favour before God,
and desired to build a tabernacle for the God of Jacob; but Solomon built him a house,
howbeit the most high dwelleth not in temples made with hands, as saith the prophet,
heaven is my throne, and the earth is my foot-stool, what house will ye build me,
saith the Lord, or what is the place of my rest?^
footnote:[Acts 7]
Now your fathers that held up these outward things,
being not in the life that saw beyond them, the end of them,
the things which Stephen here witnessed,
whom your fathers that had the law and not the life, put to death,
which had persecuted the prophets that showed the coming of the just one,
of whom they had been the betrayers, and murderers, and that stoned Stephen;
these knew not that new thing that must come to pass, before declared,
which the Lord by his prophets spoke of,
but were disobedient and rebellious against the Lord,
and cast his law behind their backs, and slew his prophets which testified against them,
to turn them to the Lord, and they wrought great provocations;
therefore the Lord delivered them to their enemies,
and vexed them in the time of their troubles; and when they cried to him he heard them,
and according to his manifold mercies he gave them a Saviour,
who saved them from the hand of their enemies:
now you may see the cause why his hand was against them,
being rebellious and disobedient, casting the law behind their backs,
being out of the life of it;
here is the cause of slaying the prophets who witnessed the life of his law,
and yet many years did the Lord forbear them;
and testify against them that had the words by the spirit in his prophets:
therefore now you having the prophets`' words, have built their sepulchres;
were you in the prophets`' life, you would see that which the prophets gave testimony of,
and Moses, him by whom the world was made, the glory of Israel,
the light of the Gentiles, the leader of the people; +++[+++take notice]
the light is to lead, yea, the light is the leader of the people.

Now you being out of the life of the prophets and Moses, having their words,
thinking to have life in the scriptures, searching them which do testify of Christ,
but not coming to the prophets`' life, you know not the voice of the prophets,
though they be read among you every sabbath-day, nor Christ the end of them;
so coming not to the prophets`' life, you come not to Christ the life,
whom the prophets testified of, who said unto your fathers,
ye will not come to me that ye might have life, who had that which testified of him;
so he now is witnessed that the scriptures testifies of, who is the light and life,
which light is the life of man, he by whom the world was made.

And your fathers which had the prophets`' words, and Moses`'s words,
being strangers from the life, were them that said, they saw,
but were them that were blind, and saw not Christ the just one,
that the prophets showed the coming of, and Moses spoke of, whom you had your law from,
who said, like to him God would raise up a prophet, him you should hear,
whom you did not hear but put him away from you,
who were out of the life of the prophets,
and would not hear him that was the life of them, and said,
as for this man you know not whence he was, and would not have him to rule over you.

Therefore consider ye this;
your fathers nor you ever came to see this prophet which Moses spoke of,
and the prophets testified of; your fathers had the words, but come not to the life,
which you never come to see, until you come to the life of Moses,
and Abraham that saw his glory, and that will let you see Christ the end of them,
and that which the prophets spoke of, and wrote of, and gave testimony of,
which all his holy apostles witnessed after his resurrection; him,
who was the covenant that the prophets and Moses gave testimony of,
whom you having the words, but being found out of the life, persecuted.

But now you may come to see in this mighty day of the Lord, his gatherings together,
with his covenant of light and his mighty power, which is everlasting and changeth not,
where the prophecy is opened, and things not declared of are known,
which gathers together in one up to God,
which leadeth out of the changeable things up to God who is a spirit;
and the hour is now come, wherein they worship him in spirit;
and the salvation of the Jews which is to the end of the earth, is believed in,
and witnessed, and the time of the Gentiles not believing in the light is seen,
and their conversation, wherein was the excess, wantonness, lust, wine, revelling,
banqueting, and abominable idolatory;
by which light (who believe in it) are turned from them,
and come to the honest conversation, and the obtaining of the Saviour Jesus Christ,
who hath abolished death, and brought life and immortality to light through the gospel.
And the gospel is preached to the Gentiles,
which is the power of God to salvation to every one that believeth in the light;
and him saith God I give for a covenant, a light to the Gentiles;
and when this covenant of God was come, Christ Jesus the everlasting covenant said,
believe in the light, I am come a light into the world, and he that abideth in the light,
shall not abide in darkness.
And the ambassadors of this covenant of light, life, and peace,
hazarded their lives among the Jews and Gentiles, among all sorts of people,
which were out of the life of the law, and they did preach to them, to the Gentiles,
and do still, for the covenant of light is everlasting to bring them to it;
but now many have the words declared from this covenant of light,
but yet are strangers to it, and them; that killed the Lord Jesus Christ,
and their own prophets, and have persecuted the apostles, and pleased not God,
but were contrary to all them, these were of your fathers, who had the words,
but were strangers to the life; and these did forbid speaking to the Gentiles,
to whom the covenant was promised, they themselves being in the transgression,
out of the life of what they professed,
and out of the life of the prophets who declared this covenant;
but now the riches of the glory of the mystery of the Gentiles is known,
which God would make known, which had been hid from ages and generations,
which is now made manifest to his saints, which is Christ in them, the hope of glory,
whom we preach, warning every man,
that we may present every man perfect in Christ Jesus the light,
the everlasting covenant of God.

Now such Gentiles that walk after the vanity of their minds,
are strangers yet from the glory of Israel, and the commonwealth and life of God,
and the covenant of light;
but God is gathering with his covenant of light up
to himself both Jews and Gentiles in one:
I say his everlasting covenant,
not according to the old covenant which he gave to your fathers,
when they were brought up out of the land Egypt, which did decay and wax old,
for this covenant never doth decay or wax old; glory,
glory to the Lord God of life forever.

And so the Gentiles that are not yet come to own the light, are without the true hope,
without God in the world; and so the promise being to the seed, he saith not unto seeds,
as of many, but of one, which is the seed, which is Christ: and this I say,
that the covenant that was confirmed before of God in Christ,
the law which was four hundred and thirty years after,
cannot disannul that it should make the promise of none effect,
that the blessing of Abraham might come on the Gentiles through Jesus Christ,
as it is written,^
footnote:[Gal.
3]
"`I will give him to be a light,`" to whom he was preached after his resurrection;
and this light brings from giving offence to Jew and Gentile that believe,
but offends both that be against it.
And when the Gentiles which had not the law, did the things contained in the law,
this showed the work of the law written in their hearts,
that judged you Jews that had the law, and were transgressors of it,
which caused the Gentiles to blaspheme God,
and so your circumcision became uncircumcision,
and their uncircumcision became circumcision, and judged you; so the light,
which is the life, joins Jews and Gentiles together in one, up to one God, who is light,
who is Lord of all, and rich to all,
with which spirit they come to be baptized into one body:
and you may come to know the salvation that is sent to the Gentiles,
the everlasting covenant which among them is witnessed, which God of old promised;
and Christ the prophet says, "`Go not in the way of the Gentiles,
but to the lost sheep of the house of Israel.`"

Now when your fathers had delivered him up to be crucified,
he sent his apostles to preach to all nations, to the Jews, and to the Gentiles,
and when the Jews did not hear,
(your fathers that had the words of the prophets and Moses,
which spoke of this covenant) they turned to the Gentiles,
and the Holy Ghost they witnessed, to whom the apostles were sent,
to whom the promise belonged; and so Israel, which had the law and the prophets,
being out of the life, saw not the glory of Israel,
neither the light of the Gentiles which now is manifested,
him whom the apostles and prophets declared.^
footnote:[Luke 2]

Now among the Gentiles there is an exercising of lordship,
and the great ones exercise authority on them, but it shall not be so with you,
saith Christ the light, the covenant whom God spoke of,
whom Moses said God would raise up: for they that are in the light,
are from the will of the Gentiles turned, and their lordship to Christ the Lord, +++[+++mark]
and so the Gentiles are no more aliens but citizens, and co-heirs, joint-heirs,
who believe in the light, in the covenant.
So you that hold up that which doth decay, stand against the prince of life,
the covenant that doth not decay, which many of the Gentiles received;
and you that stood in the first, that doth decay,
come to be thrust out now by that which doth not decay;
and now as you hearken to the light, this you will come to see,
and it is the light that doth now manifest the counsels of your hearts, your thoughts,
your vain imaginations, and covetousness, which is idolatory,
and the lusting after those things which you should not.

Now this light gives to see Christ the covenant of light,
and brings into the life of the law and the prophets to see Christ who is the light,
which light in men, is the life of Christ, who is the end of the law.
He is the light of the world, and doth enlighten every man that cometh into the world,
He by whom it was made.
If you love the light, and bring your deeds to the light,
it will let you see whether they be wrought in God; but if you hate the light,
it will be your condemnation: and saith Solomon the king, (and Christ that was a greater,
said, a greater than Solomon was here; and Christ the light said, before Abraham was,
I am; which because he said,
they took up stones to cast at him,) to do justice and judgment,
is more acceptable to the Lord than sacrifice;^
footnote:[Prov. 21:3]
mark, this justice and judgment is more acceptable to the Lord than your sacrifice.
And saith the Lord, I will take no bullock out of thine house, nor goat out of thy flock;
for all the beasts of the forest are mine, the beasts of a thousand hills.
I know all the fowls of the mountains, and all the wild beasts of the field are mine:
if I be hungry, I will not tell thee, for the world is mine, +++[+++mark]
and all that therein is.
Will I eat the flesh of bulls?
or drink the blood of goats?
Offer unto God thanksgiving, and pay thy vows to the most high;^
footnote:[Psal.
50]
and (saith the Lord by the prophet) I desire mercy and not sacrifice,
and the knowledge of God more than burnt offering.
Now you may see, many had the burnt offerings, and not the knowledge of God,
whereas the knowledge of God, he required more than burnt offerings; and mercy,
and not sacrifice: +++[+++mind,]
mercy and not sacrifice.

And when Christ was come, the covenant of light,
he bid your fathers (who were in the burnt-offerings and sacrifices,
but out of the knowledge and mercy) go and learn what the prophets`' words meant,
he would have mercy and not sacrifice; such as had the burnt offering, and not the mercy,
nor knowledge of God; of such God desired mercy before sacrifice,
and the knowledge of God before burnt offerings.
So your fathers that had the sacrifice and the burnt offering,
were without the mercy and the knowledge of God,
who knew not the Son the covenant of light, that Moses and the prophets spoke of,
and the blind offered the blind, that which was not accepted of the Lord,
who respects not your persons, but suffered you to be trodden under foot of the Gentiles,
and to have been scattered.
But now is the Lord warning you to turn to him, and to do works meet for repentance,
that you might come to know the prince of life, the end of the law,
the end of the prophets, the end of all outward sacrifices,
and come to know the spiritual sacrifice, which is acceptable to God by Jesus Christ,
going up from the spiritual household, which is built on the prophets,
Christ the corner-stone, who is now come to reign on the throne of David,
whose seed witness him David`'s son; God will show mercy to his seed forevermore;
which mercy his seed witness, and witness the Son who reigns on the throne of David,
the Son of God, who is the seed of Abraham,
to whom the promise was when he was in the uncircumcision;
and the promise which was made to him when he was
in the uncircumcision do we witness fulfilled;
glory, glory to the Lord God forevermore.

And we are of the promise, which is to all the seed,
which was not made to him through the law, therefore it is of faith,
that it might be by grace, that the promise might be sure to all the seed;
not to that only which is of the law, but to that also which is of the faith of Abraham,
who is the father of us also; and he who was of Abraham is now witnessed,
that took upon him the seed, according to the flesh, who was before Abraham was;
a greater than Solomon; him, who according to the flesh, is of the seed of Abraham,
but according to the spirit was declared to be the Son of God, the king of glory.
And him David saw, and called him Lord, who said,
God would not suffer his holy one to see corruption, nor leave his soul in hell;^
footnote:[Psal.
68]
and saith David of him, thou host ascended up on high, thou hast led captivity captive,
thou hast received gifts for men, yea for the rebellious,
that the Lord God might dwell amongst men.
+++[+++Mark,]
He that ascended up on high, led captivity captive, and gives gifts unto men,
that the Lord might dwell amongst them, and he that ascended, +++[+++mark]
he that led captivity captive, what is it?
but he that descended first into the lower parts of the earth,
and he is the same that ascended far above all heavens, that he might fill all things,
by whom all things were made, to reconcile all things to himself.
And he gave some prophets, some evangelists, some apostles and teachers,
for the perfecting of the saints, for the work of the ministry,
for the edifying of the body of Christ, till all come into the unity of the faith,
and the knowledge of the Son of God, (the covenant) unto a perfect man,
unto the measure of the stature of the fulness of Christ.

And the prophet Isaiah, speaking of Christ, said,
he would proclaim liberty to the captives,^
footnote:[Isa.
61]
+++[+++mark]
to the captives, and he did proclaim liberty to the captives,
and went ministering to the spirits in prison.
Now you who have had the words declared forth from the prophets and Moses,
but not being guided with that spirit that gave them forth, you see not the captives,
but are captives; see not him that brings deliverance, and heals the brokenhearted,
and recovers to the blind their sight, and sets at liberty them that are bruised;
that leads captivity captive, and gives deliverance to the captives;
and this is not known till you come to the covenant of light.
And when Ezekiel was among the captives at the river of Keba, the heavens were opened,
and he saw the vision of God; +++[+++mark]
when he was among (the captives) and he was to go to them of the captivity,
and speak to them; and after he was commanded to speak to the captives,
the spirit of the Lord took him up, and brought him to them.

So consider now, you that have had the prophets`' words,
but not knowing him that is on high, that leads captivity captive,
being found out of the life, are scattered abroad;
and hearken to the light that will discover your iniquity,
whereby your captivity may be turned away;
whereby you may come to the life of the prophets and Moses,
with which you may see Christ: for Jeremiah did lament the falseness of the prophets,
which had not discovered their iniquity, which might have turned away their captivity,
that you might come to know the voice of the bridegroom, the voice of joy,
the voice of gladness, and the voice of them that say, "`praise the Lord of hosts,
for his mercies endure forever,`" and of them that bring
the sacrifice of praise into the house of the Lord.
I will cause to return the captivity of the land, as at first, saith the Lord; now know,
this captivity led captive, and this captivity returned.

And was it not often that Jerusalem and the children of Israel were carried
into captivity for transgressing of the righteous law of God?
And did not the enemy come upon you, which trod down the wall of Jerusalem,
which was before Christ was manifest in the flesh,
which after came and was manifest in the flesh,
according to the saying of the prophet which showed the coming of the just one;
and when he was come among you that had the words of Moses and the prophets,
but being out of the life, you saw not that which Moses and the prophets saw;
though the prophet said, Jerusalem should be laid waste, and compassed with armies;
the wall thrown down, and you scattered:
is not the word of this prophet fulfilled among you, and upon you?
Had you been in the life as Moses was in, and the prophets, and Abraham,
you would have seen the glory of Israel,
him whom God raised up to sit on David`'s throne,
the hope that all the fathers hoped for.

Now your fathers being out of the life, though they had the words,
knew not the substance when he was come,
(but on the contrary) delivered him up to the Gentiles to be crucified,
which Gentiles trod your city under foot, and they cried crucify him, crucify him,
and desired his blood might be upon their heads.
Now Jacob comes to be saved from his captivity, and Israel shall return to his rest,
and I will be found of you, saith the Lord, and will turn away your captivity,
and will gather you from all the nations,
and from all the places where I have driven you, and will bring you again to this place,
saith the Lord, whence I caused you to be carried away captive;
when you come to the life of the law, this you shall witness.
Now wait in the light, that you may come to witness this promise fulfilled,
for the Lord`'s flock hath been carried away captive, but now is the Lord redeeming,
and gathering them with his power out of captivity, and leading captivity captive.

And, saith the Lord,
I will gather the remnant of my sheep out of all the countries where I have driven them,
and bring them again to their fold, and they shall grow and increase;
and I will set one shepherd over them, which shall feed them; they shall dread no more,
nor be afraid, neither shall they lack any thing, saith the Lord: for the day is come,
saith the Lord, that I will raise unto David a righteous branch,
and a king shall reign and prosper, and shall execute justice and judgment in the earth.

Now this branch, this king, this shepherd, this fold do we witness, that are his sheep,
and are come to witness the life that Moses was in, and the prophets were in,
and David was in,
from which life the scriptures were given forth to be believed and fulfilled,
which we see with the same that gave them forth, and the Son we see to reign;
and the Lord is cutting off, according to his promise, Babel, his name and his remnant,
son and nephew,^
footnote:[Isa. 14:22]
and there shall be a highway for the remnant of his people,
which shall be left from Assyria,
like as it was unto Israel in the day when he came up out of the land of Egypt:
+++[+++of this take notice.]

In that day shall the remnant of Israel, and such as have escaped of the house of Jacob,
stay no more on him that smote them; +++[+++mark]
on him that smote them, but shall stay upon the Lord, the holy one of Israel in truth;
the remnant shall return, even the remnant of Jacob, to the mighty God;
for though thy people O Israel be as the sand of the sea,
yet a remnant of them shall return,
and there is a remnant that keeps the commands of God.
And did not the Lord speak to Ezekiel; that your fathers should be carried away captive,
and the time is come that whosoever shall call on the name of the Lord shall be saved;
for in Mount Zion and Jerusalem shall be deliverance, as the Lord hath said,
and a remnant the Lord shall call.
And the remnant of the Philistines shall perish: seek good, and not evil, hate the evil,
and love the good, and establish judgment in the gate,
it may be the Lord of hosts will be merciful to the remnant of Joseph,^
footnote:[Amos 5]
though the number of Israel be as the sand of the sea, yet a remnant shall be saved.
Even so at this present time, there is a remnant through the election of grace;
and now is the remnant known, that doth give glory to God.
And thus saith the Lord to your fathers, who changed his judgments into wickedness,
and his statutes more than the wicked: I will execute judgment in thee;
I will do unto thee what I never did before, neither will I do any more the like,
I will execute judgment in thee,
the whole remnant of thee will I scatter in all the winds.

And these things and many more this prophet doth relate, which was done to your fathers,
and what they should act and do, who are out of the life of the law:
but now such as be in the life of the law, prophets, and Christ, can say,
who is a God like unto thee, who takest away iniquity,
and passest by the transgression of the remnant of thy heritage; and saith the Lord,
I will bring again their captivity, and the captivity of Sodom, and her daughters;
and the captivity of Samaria, and her daughters;
and will I bring again the captivity of thy captives in the midst of them.^
footnote:[Ezek. 16:53]
Now they that be in the life of the prophets see this,
that they that were in the captivity, had despised the oath, in breaking the covenant;
yet notwithstanding, saith the Lord,
I will remember my covenant with thee in the day of thy youth,
and will establish unto thee an everlasting covenant,
and thou shalt know that I am the Lord:
the Lord will raise up the tabernacle of David that is fallen down,
and close up the breaches thereof; and I will raise up his ruins, saith the Lord,
and build it as in the days of old, that they may possess the remnant of the heathen,
which are called by my name, saith the Lord.

And the dragon was wroth with the woman, and went to war with the remnant of her seed,
which keep the commandments of God, and have the testimony of Jesus Christ;
the dragon is wroth with them that keep the commandments, and them he cannot endure,
but is wroth, and makes war against them.
And the remnant of the seed of the woman appears now, that have the testimony of Jesus,
and keeps the commands of God, over all the world stands,
and the dragon and his wrath fears not, but by the testimony of Jesus they overcome,
which is the spirit of prophecy, who are his remnant which keeps his commandments,
with whom the dragon now is wroth, and makes war against.
And now is the Lord made manifest to them that asked not after him,
and found of them that sought him not;
this prophecy of Isaiah is fulfilled in this our days, the father is made manifest;
God hath made manifest his covenant to them that did not ask after him.
+++[+++Mark,]
Them that asked not after him, to them he is made manifest.

And you which be strangers from the light, the covenant, having the first covenant,
this you saw not, your eyes were blinded, who were from the life of the law and prophets,
and this should provoke you to jealousy, they must come to life from the dead,
before the riches of the world be known, the covenant of light, the unchangeable,
and the conversion, to the life of Moses and the prophets, and the Son of God,
who of them is the end; and this you must know when converted,
and come to the father of spirits,
and know Moses and the prophets that gave forth the scriptures;
for the life is that which doth convert, and lets see for what purpose it was given,
and gives a spirit of understanding, by which the prophets spoke,
by which spirit they saw the eyes of your fathers blinded,
whose ears were dull of hearing, and hearts gross, and are in blindness,
not receiving the covenant of light within; so over your hearts the veil is remaining,
who yet have that eye blinded, and cannot hear the Holy Ghost,
nor him who was born of it, to be converted and healed, who ever testified,
and is for judgment with the spirit that scripture was given forth from;
for Moses in the light saw the covenant, and Abraham saw the promise in the light,
and we in the light do enjoy that promise, which they saw to be fulfilled,
the covenant of light, and witness the holy spirit the scriptures were given forth from,
and do see them which have the words of the scriptures,
but are not in the spirit that gave them forth, them God the father of spirits scatters,
though they gather together,
and such be the heathens that know not the spirit the scriptures were given forth from,
these know not God the father of spirits, but are all a-heaps about words,
killing and destroying one another.

From them who are Israel`'s commonwealth,
who are the remnant that keep the command of God, and are of the seed of Abraham,
who witness the mighty power of the Lord,
in raising his own seed by his own power in this day; and the trumpet is blown in Zion,
and the alarm is sounded in his holy mountain, which makes the earth to tremble,
and it doth tremble at the word of the Lord,
(and is by the dark world called Quakers,) at whose voice Moses exceedingly did quake,
which power and voice now is known among us,
which doth not only shake the earth but the heavens,
which power removes that which is shaken,
that that which cannot be shaken may remain and appear;
and before this covenant you come to know, your hearts must be rent,
so to come to witness the abolishing of death before life,
and immortality be brought to light through the gospel, which is the power of God,
which removes; shakes and throws down all the contrary,
and so the promise comes to be fulfilled: and saith the Lord by the prophet,
make the heart of this people fat, make their ears heavy, saith the Lord,
to him that was in the spirit, lest they should see with their eyes,
and hear with their ears, and understand with their hearts, and be converted,
and be healed;^
footnote:[Isa.
6]
these were from the light of the law, the life, for his law is light, saith Solomon.^
footnote:[Prov. 6:23]

But I said, how long Lord?
+++[+++mark]
and he answered, until the cities be wasted without inhabitant,
and the houses without man, and the land be utterly desolate, +++[+++take notice.]
They that be in the Holy Ghost see this fulfilled upon you,
who have not understood with your hearts, not seen with your eyes, nor been converted,
whose cities are laid waste, and houses without man,
and the land come to be desolate without the spirit, that gave forth scriptures:
and the Lord hath removed men far away,
and there is a great forsaking in the midst of the land +++[+++of this take notice.]
But yet in it shall be a tenth +++[+++mark]
and it shall return, and be eaten as a teil tree, and as an oak,
whose substance is in them when they cast their leaves, +++[+++of that take notice,]
so the holy seed shall be the substance thereof.
+++[+++Mark,]
The holy seed: life from the dead, he that hath an ear, let him hear;
and this must be known before the riches of the world be.

Now that which gathers you to the promise, is the light and power of God,
and the light will let you see all the evil deeds you have done,
all the ungodly actions you have committed, and all your transgressions,
that is the light which shows you them, and if you love the light,
you will come to see yourselves, and whether your deeds be wrought in God,
and if you believe in the light, which manifesteth all that ever you have done,
ye will become the children of light, and receive power from Christ,
from whence the light comes, him by whom the world was made, to stand against the evil,
which he hath given you a light to see;
and with this light you come to know the Messias your Saviour, to save you from your sin,
which he discovers, and to see the one offering.

But you that do hate this light, and go into the evil,
and love the darkness more than that which shows you your evil deeds, and evil ways,
when God is not in all your thoughts, when your heart revolts,
and when you call on him with your lips, and your hearts afar off:
this is the light of Christ that shows you this, and lets you see your covetousness,
and idolatry, and if you go on in these things before-mentioned,
the light will be your condemnation, saith Christ,
who enlighteneth every man that cometh into the world.
This light of Christ tells you, you should not do unjustly one to another,
that you should not be drunk, nor oppress one another, nor wrong one another.
It is the light that shows you this, and measures things aright,
and this word is nigh you, in the heart, and in the mouth, to obey and do it.

Now, as you love the light, and bring your deeds to it,
you will come to know the light Moses was in, and come to know the prophet,
which he said God would raise up, whom you should hear;
and come to know the covenant of light, which brings in the Gentiles from dead idols,
to serve the living God, which the prophet spoke of, which is the glory of Israel.
And as you love this light before-mentioned,
you will come to know the law in your hearts written, the new covenant,
the everlasting covenant, which the prophet prophesied of,
which now thousands do witness, with which light they know God the glory of Israel,
Zion`'s king, and him are come to worship; and this light will tell you,
you must not bow to any likeness, but unto God alone, nor commit adultery,
nor serve graven images, the gods of the heathen,
nor follow their customs which are vain, for against that God`'s hand is turned,
who is one with the light, which light the darkness cannot comprehend,
though it in darkness shines; and Christ the light came to his own,
and his own received him not, even among your fathers that had the oracles of God,
and the darkness could not the light comprehend, though the light in darkness shined,
neither could the darkness see him, by whom the world was made,
the light who is glorified with the Father,
with the glory that he had with the Father before the world was:
therefore to the light in you I appeal, that with it you may be turned from darkness,
and the power of Satan to God, and receive the covenant of light,
and the power of God Christ Jesus, that you may come to life, regeneration,
and conversion, and the renewing of your minds, remission of sins,
and receive the refreshing into your souls.

And as you love the light that shows you the evil that ever you have done,
ye love Christ,
and that light is it which gives the knowledge of the glory of God in the face of Christ,^
footnote:[2 Cor. 4:6]
which shines in the dark heart,
and none comes to the knowledge of God but by the light which shines in the heart;
and this treasure have we in earthen vessels,
that the excellency of the power might be of God, and not of man:
but if you hate this light, you hate Christ, and remain stumbling, blind, and scattered,
refusing the corner-stone, whom all the builders stumble at, who are out of the light,
and none comes from stumbling, to know the words of the scripture declared from the life,
but such as own the light.
To the light in you I appeal, if you go on in your evil deeds, and unbelief,
not believing in the light, the light is your condemnation; hating the light,
you hate Christ, for you do not come to the knowledge of God but by the light;
he that comes to the knowledge of God, knows his Son; now none comes to the Son,
but who owns and comes to the light, which from the Son doth come:
and this light brings to one heart, one mind, one people, one God, one mediator,
betwixt God and man; and this light unites and brings Jew and Gentile together;
and he that believes not in the light, doth not believe in God, who is light,
nor know his Son, who enlighteneth every man that cometh into the world.
And to you this is the word of the Lord.
