== A Visitation / to All You That Have Long Had the Scriptures,

[.heading-continuation-blurb]
But are found out of the Life of them that gave them forth,
that are stumbling about the words, fighting and contending about them,
imprisoning and persecuting them that witness the Life, that gave them forth.--By G. F.

To all you who are from the life of the law, and the prophets, which is light,
and from the spirit of understanding, which gave forth the scripture,
and hearing hear not, and seeing see not, having hearts and understand not,
whose ears are heavy, whose eyes are shut, and whose hearts are fat;
who are in the transgression, out of the law of God, and his covenant first and second,
against all such the Lord sent his prophet to declare, and commanded him,
go tell this people, hear ye indeed, but understand not, and see ye indeed,
but perceive not, make the heart of this people fat, and make their ears heavy,
and shut their eyes, lest they see with their eyes, and hear with their ears,
and understand with their heart, and be converted, and I should heal them,^
footnote:[Isa. 6:9-10]
who were from the light, who with that ear could not hear.

Now the prophet was in the life of the law,
the people were here gone from the life of the law,
therefore the life turned against them that were from that of God in them;
and the life of the law, the life turning against them,
being one with that of God in them, which they were gone from, so the life blinded them,
and their ears became heavy, and their hearts fat, and their eyes shut,
and they could not hear with their ears, nor understand with their hearts,
nor be converted, even such as were gone from the life,
with which the spirit of God was one, in which the prophet was.

And the prophet Isaiah told this people, that were gone from the life of the law,
what the Lord would do with his vineyard, he would take away the hedge thereof,
and it should be eaten up, and break down the wall thereof,
and it should be trodden down; and I will lay it waste, and it shall not be pruned,
nor digged;^
footnote:[Isa.
5:-6]
I will also command the clouds that they rain no rain upon it:
for the vineyard of the Lord of hosts is the house of Israel,
and the men of Judah his pleasant plant, he looked for judgment, but behold oppression;
for righteousness, but behold a cry.
These were those that were blind, where the judgment was not, but the oppression,
and were from the light, such Christ came to make blind,
against whom went the woe that drew iniquity with cords of vanity,
and sin as it were with a cart-rope, that called good evil, and evil good,
such as were from the life of the law, and such as these hearing hear not,
and seeing see not, whose hearts are made fat: make them fat,
whose eyes are shut lest they should see, whose ears are heavy lest they should hear.
Then said I, Lord how long?
and he answered, until the cities be wasted without inhabitant,
and the houses without men, and the land be utterly desolate;
+++[+++mark and take notice of this]
until the cities be without inhabitant, and the houses without men,
and the land be utterly desolate.^
footnote:[Isa. 6:11]
Now such as were here out of the life of the law and the prophets,
being in the transgression, the life went against them that were from the life,
and blinded them, and stopped that ear, and that heart cannot understand,
that against the life is turned, until the city be wasted without inhabitant,
and God hides his counsel and secrets from this eye, and from this ear;
so he comes to make them blind, that they cannot see, which are in the transgression,
but doth not blind the eye that the prophet saw withal.

And again the prophet said to them that were out of the life of the law,
in the transgression.
Stay yourselves and wonder,
for the Lord hath poured out upon you the spirit of deep sleep, and has closed your eyes,
the prophets, and your rulers, and the seers hath he covered,
the vision of all is become unto you as the words of a book that is sealed,
which men deliver to one that is learned, saying, read this I pray thee, and he saith,
I cannot; for it is sealed: and the book is delivered to him that is not learned, saying,
read this, I pray thee; and he saith, I cannot, for I am not learned.
Wherefore thus saith the Lord, forasmuch as this people draw near to me with their mouth,
and with their lips do honour me, but have removed their heart far from me,
and their fear towards me is taught by the precepts of men, therefore will I proceed, etc.
These people were gone from the life of the law, whose hearts were far removed from God,
to these the book was sealed,
and the vision of all was become unto them as a sealed book, and they could not read it,
neither the learned, nor the unlearned, for to both it was sealed;
to this people that could not see nor hear was the book sealed,
whose eye was blinded though they were learned or unlearned,
such as were gone from the life of the law, which was the light, the life of the law,
the light they had not, and such the prophet saw, who was in the light of the Holy Ghost,
and their fear towards the Lord was taught by the precepts of men,
(as it is now with them that are blind,) these their eyes were closed,
upon whom was poured a spirit of deep sleep, who staggered like a drunken man,
but not with wine, who sought deep to hide their counsel from the Lord,
and worked in the dark, among whom the Lord will do a marvellous work, and a wonder,
the wisdom of their wise men shall perish,
and the understanding of the prudent shall be hid.^
footnote:[Isa. 29:9-12, etc.]

These were them that turned things upside down,
who should be esteemed as the potter`'s clay; for shall the work say to him that made it,
he made me not?
Or, shall the thing framed say of him that framed it, he had no understanding?
Yea, he sees +++[+++take notice]
that hath made and framed: mind this, you who call upon God with your lips,
but your hearts afar off, who be strangers from the life of his law,
who turn things upside down that must be turned upside down, before the life of the law,
which is the light, be known, and your eyes opened.
Who are in the spirit of slumber, and the spirit of deep sleep,
yet have wisdom and a prudent understanding:
these were them that the prophet saw erred from the life of the law,
and such God made blind; for the promise was when God gave forth the law, the blessing,
and they that were in the life saw the end of it;
a curse was not to them that did abide in the life of the law,
the woe was not to them but the blessing;
the curse was to them that did not abide in the life of the law,
and such came not to see the end of what they professed;
and these went from the life of the law to men`'s precepts,
and they were such as called upon God with their lips, but their hearts were afar off;
and such owning not the life of the law, they owned not Christ when he came,
who was the end of it, but were blind, and so Isaiah`'s words came to be fulfilled,
which were spoken forth from the life, when Christ came, who was the life,
they that had the words of the law, and were out of the life, knew him not,
but were blinded, and by hearing should not hear, nor understand;
and seeing they should see, and not perceive;
these which were gone from the life of the law, the light, which Christ was one with.

These could not perceive nor see, though they saw, and though they heard,
they could not understand, being in the transgression gone from the life of the law,
and such Christ came to make blind;
and these eyes must be blinded that they cannot see nor hear; for that which must hear,
comes to the life of the law, and to the conversion;
and saith Christ to them that were gone from the life of the law,
which hearing heard not, neither understood, "`These people`'s hearts were waxed gross,
their ears were dull of hearing, (their eyes were closed, lest at any time, +++[+++mark]
they were so shut up from the light the life of the
law) lest they should see with their eyes,
and hear with their ears, and understand with their hearts, and be converted,
and I should heal them.`"

Now you may all come to see what sort of people they were whose hearts were waxed gross,
and ears dull of hearing, and could not see with their eyes, nor hear with their ears,
lest they should be converted, and Christ should heal them;
such as were out of the life of the law, and were from that of God in them,
in the unconverted estate, against whom Christ cried woe:
for how can they hear with their ears, or see with their eyes,
that are from the life of the law?
and how otherwise can it be, but that their hearts will wax fat and gross,
and be hardened with the deceit, who go from the life of the law,
which is the eye which God blinds not, who is light,
and teach men`'s commandments for doctrines; such as hear not the light of the law,
are blind, and are such as run into the lust, whose hearts grow fat;
and are such as have a wisdom, and a prudent understanding,
but as to hearing or seeing the things of God, their eyes are made blind,
and ears they have, but hear not, and hearts they have, but understand not;
and cannot understand with their hearts, nor see with their eyes,
lest any time they should see with their eyes and hear with their ears,
and I should convert them, and they should be healed.

Now this ear and eye which is gone from the life of the law, heareth not, sees not,
and the heart waxeth gross, and that eye must be made blind,
before Christ come to heal them, and convert them: "`He that hath an ear to hear,
let him hear.`"

And to such as were gone from the life of the law and prophets, into the transgression,
Christ spoke parables; they that were gone from the life of the law, seeing,
they saw not; and hearing, they heard not, nor perceived, nor understood;
these having the words, but being out of the life, were they that were blinded, gross,
and could not hear nor perceive, nor understand the mystery of the kingdom;
unto these Christ spoke in parables.
And the disciples said to Christ, "`Why speakest thou unto them in parables?`"
and he said unto them, "`To you it is given to know the mystery, but to them it is not,
who have eyes and see not, ears and hear not; but blessed are your eyes, for they see,
and your ears for they hear: for whosever hath, to him shall be given +++[+++mark,]
and he shall have more abundance; +++[+++mark,]
and whosoever hath not, from him shall be taken away, even that which he hath.
He that hath an ear to hear let him hear.`"
So they knew the mystery of the kingdom who were in the light,
and those saw not the mystery of the kingdom, which were not in the light,
therefore spoke Christ to them in parables, because in seeing, they saw not; and hearing,
they heard not, neither did they understand:
so in them is fulfilled the prophecy of Isaiah, which saith, "`By hearing you shall hear,
and shall not understand; and seeing you shall see, and not perceive:
for this people`'s heart is waxed gross, and their ears are dull of hearing,
and their eyes they have closed; lest at any time they should see with their eyes,
and hear with their ears, and should understand with their heart,
and should be converted, and I should heal them.`"

Therefore parables were spoken to these which were gone from the life of the law,
which did not understand with their heart the mystery of the kingdom,
to be converted and healed: for such as understood,
came with their heart to the life of the law, the light, to converting and healing;
others stood against it, and that eye was blinded, so saw them not,
and were not converted:
and all dullness of hearing was among them that were from the life of the law, the light;
which life of the law gave to see before transgression was;
and so these that did not understand with their hearts, not converted, not healed,
were they that were gone from the light, the life of the law;
such could not see the second covenant, when he was come,
and to these Christ opened his mouth in parables,
and uttered forth things which have been kept secret from the foundation of the world,
to the fulfilling of the prophets`' words who were in the life;
and to those that were out of the light, the life of the law, were the parables spoke;
but blessed, saith Christ to his disciples, are your eyes, for they see, and your ears,
for they hear; the life is manifested that was with the father before the world was,
which all the prophets of God did give testimony to,^
footnote:[Matt 13]
while Moses is read, the veil is over the heart, but where the life of Moses is,
that sees the end of the first covenant, Christ Jesus:
but they that were out of the life of the first, were in the hardness,
such had the words of Moses, but were out of the life, whose ears were dull of hearing,
and served God with their lips, out of the life the light, and their hearts afar off;
such were in the days of Isaiah the prophet, and in the days of Christ in the flesh,
these Christ plainly told, them he came to make blind who said they saw,
but were out of the life of what they professed, the light,
and the God of this world blinded the eye of their mind,
and for judgment Christ came into the world, to make them to see that saw not,
and to make them blind that said they saw, where the God of this world ruled.
And John speaks of the fulfilling of Isaiah`'s words, who saw the glory of the Lord,
and spoke of him; he saw them that were from the life of the law,
the light and the prophets, that could not see with their eyes,
nor understand with their hearts,^
footnote:[Job 19]whose serving God was with the lip, but the heart afar off;
these could not hear Christ when he came, nor understand with their hearts,
nor be converted nor healed; such were for judgment,
and such Christ judged and made blind; for these could not understand with their hearts,
nor be converted nor healed, who were far from the light, and had it not.

And the apostle speaks of the hated and loved, the election and reprobation,
that the purpose of God, according to the election, might stand, not of works,
but of him that calleth,^
footnote:[Rom.
9]
as it was said, the elder shall serve the younger; Esau have I hated,
Jacob have I loved +++[+++mark,]
so it is not of him that runneth, but of God that sheweth mercy;
as the scripture saith of Pharaoh, for the purpose have I raised thee up,
that I may show my power in thee,
and that my name may be declared throughout all the earth: +++[+++of this take notice.]
The power which overthrew Pharaoh, brings the seed out of bondage;
therefore hath he mercy on whom he will have mercy, and whom he will he hardeneth.
But thou willt say unto me, who hath resisted his will?
Why doth he yet find fault?
Nay, but O man, who art thou that repliest against God, who is light,
thou who art from the light?
Shall the thing formed say to him that formed it, why hast thou made me thus?
Hath not the potter power over the clay, of the same lump,
to make one vessel unto honour, another a vessel to dishonour?
+++[+++mark,]
but what, if God willing to show his wrath, and to make his power known,
endureth with much long suffering, the vessels of wrath fitted to destruction,
the children of disobedience.
+++[+++Mark]
Jacob is loved, but Esau is hated; Esau was the first, a prophane person:
Pharaoh a persecutor of the seed of God, who was hardened, God had mercy on his seed,
and made his power known, in overthrowing the one and delivering the other.

And he that willeth, and he that runneth, obtaineth not the promise of God,
but the election obtains it: in Isaac shall thy seed be called;
and they which be the children of the flesh are not the children of God;
and so it is not in him that willeth, nor in him that runneth,
but in God that shows mercy, the election obtains it.

But, O man, who art thou that repliest against God?
+++[+++mark]
man, not the election which obtains the promise:
shall the thing formed say to him that formed it, why hast thou made me thus?
Hath not the potter power over the clay, to make one vessel of honour,
another to dishonour?
What if God willing to show his wrath, and make his power known,
endured with long suffering, the vessels of wrath fitted to destruction: +++[+++take notice]
endured with much long suffering, the vessels of wrath fitted to destruction.

What if God will make his power known upon such,
and will show his wrath upon the vessels thereof,
who are in the disobedience from the light; hath not the potter power over the clay,
the vessels of wrath, where the enduring with much long suffering hath been;
such be from the life of the law of God, in the disobedience, children of wrath,
on whom the wrath of God abides; therefore the thing formed that saith,
why hast thou made me thus?
Here is the willing, and not the election,
which obtains it without the willing and running,
which overthrows the vessels of wrath fitted for destruction,
and the willing and the running, who hath endured with long suffering:
and now it is seen, the Lord will have mercy on whom he will have mercy,
and the promise is to the seed, and Jacob is loved, and Esau is hated,
and Ishmael is driven out; and the power which overthrew Pharaoh,
which hath raised up the seed; and the vessels of wrath,
on whom he doth make his power known, and shows his wrath,
which he hath endured with much long suffering,
the vessels of wrath fitted for destruction, and the will that is willing is seen,
and the mind which is running, and attains it not; and the man which replies against God,
who is saying, why hast thou made me thus?
As if the potter had not power over the clay: and here is the willing and the running,
but the promise of God is to the seed, and the election obtains it, and hath obtained;
that he might make known the riches of his glory
on the vessels of mercy whom he hath called;
so the promise is to the seed, not to seeds, as of many, but as of one,
which seed is Christ.
And David that was in the life of the law, seeing the second covenant,
saw them that had the words of the law, but were out of the life:^
footnote:[Rom.
11]
and Paul who was in the life of the law, the light that David was in,
saw David`'s words fulfilled in his generation,
among them that were out of the life of the law, though they had the words, and saith,
according as it is written, God hath given them the spirit of slumber,
eyes that they should not see, and ears that they should not hear unto this day;
they were such as were from the life of Moses and the prophets,
having their minds reprobated; and saith David, let their table be made a snare,
and a trap, and a stumbling block; and for a recompense,
let their eyes be darkened that they may not see, and bow down their neck alway:
such as were from the life of the law, have they stumbled that they should fall?
God forbid; but through their fall, salvation is come to the Gentiles.

Now they that had the outward covenant, the words of the law, and stood for the outward,
and were not guided with the inward, their tables became a snare unto them, and a trap,
and a stumbling block, and they fell, and through their fall (who were in the outward,
from the light, the life of the law) salvation came to the Gentiles,
and the riches of the world, the light, which is Christ the salvation,
which overthrows the outward, and brings in the inward, the Jews in the spirit:
for to such as were in the life of the law, the table did not become a snare, a trap,
but they saw the end with the light; but such as were from the life of the law,
had the spirit of slumber; so the election hath obtained it, and the rest were blinded;
+++[+++mark,]
the rest were blinded, the election is not blinded; read this, who sees this,
who is come to the election, which obtains, where this is witnessed,
that which is blinded is seen, and the God of this world is judged, and the eye he opens,
and that which doth blind is judged with the light,
with the eye where the conversion and healing is, and the casting away of them is seen,
that were out of the life of the law, and the prophets, which had the outward oracles,
which brought in the Gentiles, who said, they saw,
but were out of the life of what they professed.
For, if the casting away of them be the reconciling of the world,
what shall the receiving of them be, but life from the dead?
+++[+++mark,]
the receiving of them is life from the dead, and that life which came from the dead,
unites both Jew and Gentile together, when the converting comes, the healing comes,
and the elect; and the life of the law, and the prophets is fulfilled,
and the other eye is put out, and the gross heart, and the dull ear,
and the spirit of slumber, and all this is by the spirit of truth judged,
and the lip-service of God, and all this is judged, which brings the life from the dead,
which brings to serve God with the heart, and brings the heart nigh unto God,
while they who professed the law, being from the life, that heart perceives not,
that eye sees not, which goes from the light, and cannot see the mystery,
nor hear Christ the end of the law.

And here is the rebellious people, and the stiff-necked, which hearing hear not,
and seeing see not,^
footnote:[Rom.
1]
hearts have they, and understand not, whom God blinds, that his mysteries they see not,
they that are gone from the light, which are from the life of the law, the light,
which is one with the light of God, in every man, which answers his law,
so that which may be known of God is manifest, in them, for God hath showed it unto them,
with that they know that the judgments of God are upon them, when they act unrighteously.
And in the acts the apostles speaking to the Jews which had the words of the law,
and the prophets, (but out of the law and the life of Moses,
and the prophets who knew not Christ the end of them,
which life the apostles were in,) when he had spoken with the Jews,
and persuaded them concerning Christ out of the law, Moses, and the prophets,
shewing unto them the fulfilling of Isaiah`'s words, saying, go unto this people,
and say, "`hearing you shall hear, and not understand, and seeing you shall see,
and not perceive; for the heart of this people is waxed gross,
and they are dull of hearing, and their eyes are closed,
lest they should see with their eyes, and hear with their ears,
and understand with their hearts, and should be converted, and I should heal them,
to them he said, be it known unto you the salvation of God, is sent to the Gentiles,
and they will hear it,`" Acts 28. v. 28.

So here the apostle, Christ, and Isaiah saw them that had the words of Moses,
and the prophets, but out of the life, the light, such could not hear nor see,
being from the life of God, such were blind, and such God`'s hand often turned against,
and carried them into captivity, yea, to the bringing down,
and bringing forth of his seed out of captivity;
in bringing them down that were in captivity, they often came to remember God,
and so God`'s promise stands with the seed sure, and his election sure.

All along you may see in the days of the prophets, Christ and his apostles,
such as had not the life of the prophets and apostles,
being found out of the life of the spirit of God, had the spirit of slumber, had hearts,
and could not perceive, eyes they had and could not see,
ears they had and could not hear, and such eyes were blind, and ears were made deaf,
and knew not the mystery of the kingdom, having their hearts gross, and far from God,
and served him but with the lips, and they that were from the life of the law were here;
they that were in the life of the law, they saw such as were from the life of the law;
here one saw, and the other did not; one saw, and the other`'s eye was made blind:
And they that did carry God`'s seed into captivity, should be brought into bondage,
and God would judge them, and they had the eye which was blind; so you may all see,
that that which was from the life of the law, the life of the prophets,
the life of Christ, which is the light, doth harden, which is in the deceit,
and such as hear the voice of the Son of God are not hardened,
but such as hear not the voice of the Son of God, are hardened through the deceit,
among these there were wars, one destroying another, and carrying captives.

But who are come to the life of the law, and the end of the law,
the end of the first covenant, the everlasting priesthood,
from the changeable to the unchangeable, witness that which doth not veil, change,
nor harden, and makes to see the captive state, and leads out of captivity;
while Moses is read, the veil is yet over the heart, which doth harden,
but takes away that which doth harden, and brings the mind out of the changeable,
which their mind was in, in the outward, to the life,
the light (who were hardened and blinded,
having the spirit of slumber) and to the covenant of light, the everlasting covenant,
the end of all shadows, types, and figures, to the substance,
that old covenant is decayed to them, and so with this that is kept out,
which doth harden, +++[+++mark,]
the deceit, which is out of the truth, the life, which is in the transgression,
having a pretence of the worship, but out of the life of it; all such are blinded,
and can neither hear with their ears, nor see with their eyes, nor be converted,
nor healed, and from the life of the law are, whose hearts are afar off from God;
so all these that have the words of Moses, and of the prophets, that are from the light,
the life, with the life come to have all their wisdom and knowledge, overthrown,
such had their eyes blinded, and had a spirit of slumber, and hearts gross,
and these the life of the law overthrew, from top to bottom,
and all that profession without the life of the law, calling upon God with the lips,
but hearts afar off, God overthrows and judges, judges and blinds;
he that hath an ear to hear, let him hear.

That which overthrows the Jews outward, brings in the Jews inward,
in the spirit to Christ the light, which is one in the spirit,
and baptizeth them both Jew and Gentile into one body,
and here he comes to the life of the law, and the prophets, and Christ,
and the promise fulfilled, where there is seeing, and hearing, and conversion,
the heart being brought to the Lord God to perceive.
And to you this is the word of the Lord.

And this eye the Lord doth not blind, God doth not blind his own eye,
but that eye which is out of the life of the law, the prophets, and Christ,
and that eye is blinded which receiveth not the testimony of the prophets, nor the Son,
and this the prophet saw with the Holy Ghost, and Christ saw,
who by the Holy Ghost was conceived,
and the apostle saw with the Holy Ghost such as were blinded, and is to be blinded,
and the Holy Ghost was not blinded; that which goes from the life,
cannot believe the life, but is hardened, they being from the life could not hear,
nor see the life, when the life spoke unto them, to be converted,
their eyes were so closed, lest Christ the light should heal them,
to them woe was from the light, to them which were from it, they went from the life,
and the life was against them; so the light cast them away,
that held up the outward priests, that had the outward covenant;
their eyes they have closed, +++[+++mark,]
they have closed their eyes, lest they should see with their eyes,
and hear with their ears, and understand with their hearts, and should be converted,
and Christ should heal them; +++[+++mark,]
they have closed their eyes,
lest they should see Christ (that own not the light)
that lighted every man that cometh into the world,
they have closed their eyes, lest they should see it, and hear it,
and come to understand with the heart, and should be converted,
and Christ should heal them.
They closed their eyes, lest they should see the light,
(who were from it and owned it not,) the healing which brings to be converted,
and turns the heart from being gross, and the new heart comes to be received;
these that have closed their eyes, lest they should see the light at any time,
saying they see, but are blind; so being from the light the sin remains;
these call on God with their lips, but being from the light, the heart is afar off;
and these are the unconverted, and understand not with the heart, and are unhealed,
and follow the world, which say, they can see, when Christ came to make blind,
and for judgment is he come into the world,
that they that say they see may be made blind, and they that see not, may see;
and the light brings Jews and Gentiles to see one another,
and this raises up the tribes of Jacob, and gathers together in the unity in one,
and with it doth them reconcile up to God, with the covenant of light,
which is unchangeable.

And the apostle James, speaking of the faith of our Lord Jesus Christ, the Lord of glory,
which is without respect of persons, and shewing the law which is royal,^
footnote:[James 2]
saith, if ye fulfill the royal law according to the scripture,
thou shalt love thy neighbour as thyself, ye do well; but if ye have respect to persons,
ye commit sin, and are convinced of the law as transgressors:
so that you that respect persons, do commit sin,
and would have others to respect persons, and so commit sin, and who cannot,
these you cast into prison, and go into the transgression of the law of God,
and are against them whose souls are subject to the higher power,
and do not respect the ordinances of God (as they do) but respect persons,
and do commit sin, and are transgressors, and so bring to yourselves destruction,
whose souls are not subject to the higher power,
but the ordinance of God is resisted by such, and the royal law,
and it convinceth them as transgressors; so speak, and so do,
as they that would be judged by the law of liberty:
for whosoever shall keep the whole law, and yet offend in one point, he is guilty of all:
+++[+++mark,]
this one point of not respecting persons, if it be broken makes guilty of all.
As for instance; he that saith do not commit adultery, said also, do not kill;
if thou commit not adultery, yet if thou killest,
thou art become a transgressor of the whole law, adulterated from the life,
and resistest the higher power, to which the soul should be subject.

Quere.--But deceit will say, if I must not respect persons,
I must not honour my father and mother.

Answer.--He honours not father and mother that disobeys God`'s command,
and is out of his law, and lives not in the life of his law, who saith,
thou shalt not respect persons; and the same saith, obey your parents in the Lord;
for the law is the light, and the light is the life, and the life preserves,
which light gives to know God and his will in the law,
and God`'s judgments on them that transgress it, and this light keeps from adultery;
and where the royal seed Christ is now risen up, (made under the law) brings to know,
that marriage is honourable.
He that hath an ear to hear, let him hear.

Objection--Saith he that is out of the light,
may I not respect another woman as well as my wife, seeing I may not respect persons?

Answer.--The light which is the law, teacheth thee not to commit adultery,
and to love thy neighbour as thyself, and thy wife as thy own flesh,
and know that marriage is honourable, and the bed undefiled:
and this light brings parents to train up their children in the fear of the Lord,
with which they come to honour them in the Lord.
And this the law, which is the light, tells thee, thou must not lust nor covet,
which if thou doest, thou hast an idol.
So that which covets goes from the law, which is the light, and from the light,
which is the law, to the idol maker, where is the founder of the image, that hardens,
blinds, stops the ear, and makes the heart gross,
and there comes in the eye which God blinds, and there is the heart far from God,
though there be calling upon him with the lips.
To the light in you all I appeal, that you may come to the law written in your hearts,
with which you may come all to know the Lord, and Christ his son, his righteousness,
the end of God`'s law, which is righteous, the end of the righteous,
God`'s righteous law.

Let every man be subject to the higher power; +++[+++mark,]
for there is no power but of God; the powers that be are ordained of God.
+++[+++Mark,]
Put on the whole armour of God,
for we wrestle that we may be able to stand against the wiles of the devil:
for we wrestle not against flesh and blood, but against principalities and powers,
against the rulers of the darkness of this world,
against spiritual wickedness in high places;
wherefore take unto you the whole armour of God,
that you may be able to stand in the evil day, and having done all to stand;
having your loins girt about with truth, having the breast-plate of righteousness:
so the armour and breast-plate of righteousness,
brings to stand against the principalities and powers, against the rulers of darkness,
against the spiritual wickedness in high places,
whose feet are here shod with the preparation of the gospel of peace,
and have the shield of faith,
whereby they are able to quench all the fiery darts of the wicked,
and have the helmet of salvation, the sword of the spirit, which is the word of God,
and their souls are subject to the higher powers, and wrestle against the principalities,
powers, against the rulers of the darkness of this world,
against spiritual wickedness in high places.
For there is no power but is of God; the powers that be ordained of God,
bring to stand against the principalities and powers,
against the rulers of the darkness of the world, the spiritual wickedness in high places:
+++[+++mark,]
here is the higher power, that which God hath ordained,
to which the soul must be subject; and here is that which is out of the truth, the which,
whose loins are girded with truth stand against.

And whosoever therefore resisteth the powers which he ordained of God,
resisteth the ordinance of God; and they that resist,
shall receive to themselves damnation: such as go from the light, the truth,
and the power of God, their souls are not subject to the higher power,
but that comes in which wars against it, (the lusts) which war against the soul,
where the spiritual wickedness, and the ruler of the darkness is, against which,
who be in the truth war; for rulers are not a terror to good works, but to the evil.
Wilt thou then not be afraid of the power?
Do that which is good, and thou shalt have praise of the same; +++[+++mark]
then thou art kept in the truth, and the loins about girded with it;
for he is the minister of God to thee for good,
who hath this higher power which is of God, which is above the principalities,
and powers, and rulers of darkness in the world, and spiritual wickedness in high places,
which is out of the light, out of the truth; such are not the help-governors,
but he is the help-government that stands against sin,
which is the higher power to which the soul must be subject:
but if thou doest that which is evil, be afraid, then thou goest from the light,
and thy soul is not subject to the higher power,
and art where the spiritual wickedness is, and the ruler of darkness,
and the spiritual wickedness in the high places, which is to be wrestled against,
and so thou goest into the evil, and this higher power goes against thee,
for he is the minister of God, a revenger to execute wrath on him that doth evil,
whose soul is not subject to the higher power, but is gone from the truth, the light,
into the power of wickedness and darkness, which the power of God is above.
Wherefore ye must needs be subject, not only for wrath, but for conscience sake,
so the light which turneth from the evil, and the powers and rulers of darkness,
and spiritual wickednesses in high places and principalities,
the soul it brings to be subject to the higher power for conscience sake,
and to own the minister of God, which is for good, which is in the power,
which who resists, brings to himself damnation, who to the evil doers is a terror,
for the power of God turns against them that go from the light, and this is the power,
that no man`'s person doth respect.

So for the Lord`'s sake submit yourselves to every ordinance of man,
whether it be the king, as superior; or to governors, or unto them that are sent by him,
for the punishment of evil doers, and for the praise of them that do well;
here the higher power is it that punisheth the evil doer, and torments the evil,
goes against it, and against all the spiritual wickednesses, in high places,^
footnote:[1 Pet.
13-14, etc.]
+++[+++take notice of that:]
to that ordinance for the Lord`'s sake, we are to be subject unto, for the Lord`'s sake,
for it is the will of God to have the evil doer punished,
that so with well-doing you put to silence the ignorance of foolish men,
as free not using your liberty as a cloak of maliciousness, but as the servants of God.
+++[+++Mark,]
And again, Peter who was in the light, and his soul subject to the higher power,
and owned every ordinance of man for the Lord`'s sake, which went against the evil,
he said unto the rulers when they commanded him to speak no more in the name of Jesus,
whether was it better to obey God, or man?
This spoke Peter, he that stood against man`'s ordinance,
which was contrary to the command of God; so such as did not believe in the light,
such were not to be obeyed, whose souls were not subject to the higher powers,
for the commands of God are not contrary to his own power,
for whose souls are subject to the higher power, they own Christ the light,
the power of God, the end of the law: so all for the Lord`'s sake,
be ye subject to every ordinance of man, for the Lord`'s sake,
for the punishment of evil doers, +++[+++mark,]
to be subject to that ordinance that punishes the evil, that doth not punish the good,
that doth not go against the command of God, nor Christ,
for it is that power the soul must be subject unto.

And Peter that was subject to the higher power, who was not subject to the rulers,
the high-priests, elders, and council,
who charged them to speak no more in the name of Christ, said to them,
whether was it better to obey God or man, and to their ordinance was not subject,
but preached Christ the light, whose soul was subject to the higher power.
Neither were the three children subject to the king`'s command,
who commanded them to bow to the image he set up;
neither was Daniel obedient to the king`'s decree,
which was made that he should not pray unto his God,
neither was Mordecai obedient to the king`'s command, and to Haman could not bow,
though by his not bowing all the Jews might have been destroyed;
so him that would have Mordecai to bow, God bowed, and overthrew Haman,
and brought down Nebuchadnezzar that set up the image and gave forth his commandment,
to all nations, people, and languages, that all to it should bow;
and God with his power made him to know the most high reigned;
which most high made him to bow, and feed with the beasts of the field,
seven times was to pass over till he knew the most high to rule in the kingdoms of men,
and gives it to whomsoever he will; +++[+++mark,]
to whomsoever he will he gives it: here was a higher power above Nebuchadnezzar`'s power,
which Nebuchadnezzar was out of, which power overthrew him,
which power the three children were in.
This he knew not by all his might and authority, until seven times passed over him,
and that which was to pass over him seven times, was to be fulfilled,
before it was known that the most high ruled in the kingdoms of men; +++[+++mark,]
which thing he did not know,
when he was against that power which the three children were in,
and to which their souls were subject, though they were cast into the fire,
for not bowing to the image, nor hearkening to the king`'s command.
But the image, and the founder of the image, were thrown down,
and before he was thrown down, he knew not the most high to rule, as they do not now,
and such God with his power breaks down,
and the images to which the servants of the Lord could not bow,
that were subject to the higher power, that delivered them;
which power threw down Nebuchadnezzar that had set up the image, and made him to bow to,
and to worship, and to know that the most high reigned.
And to you this is the word of the Lord.
