== A Declaration

of the Difference of the Ministers of the Word, from the Ministers of the World; Who Calls the Writings the Word.

The Ministers of the Word now lay in Prisons, for witnessing Christ the Word, by them who have the Writings, who are filling up the Measure of their Fathers, who had the Writings, and persecuted the Word, and the Ministers of the Word.--By G. F.

They that were ministers of the word,
took in hand to set forth in order a declaration of those things,
which were most surely believed among them, which were eye-witnesses from the beginning,
and having had a perfect understanding of those things,
from the very first to write in order; shewing how John was born, how Christ was born,
and how they came to fulfill the prophets, and how Christ suffered, and how John suffered,
and how the prophets did give testimony of Christ, shewing the coming of the just one,
and Abraham, and Moses, and David;
and how the just one did come to fulfill what was written of him;
and how John was sent before to prepare the way, and how Christ was offered up and died,
and rose again according to the scriptures,
of this the ministers of the word set forth in order a declaration: Matthew,
a minister of the word, Mark, a minister of the word, Luke, a minister of the word,
and John, a minister of the word,
and John saith in his declaration (a minister of the word) what the word is.
God is the word; "`In the beginning was the word, and the word was with God,
and the word was God;`" ^
footnote:[John 1:1]
and he did not say, the declaration was the word, but said in his declaration,
God was the word: and in the Hebrews the minister of the word saith,
"`Who have spoken unto you the word of God, whose faith follow,
considering the end of their conversation, Christ Jesus the same yesterday, today,
and forever.`"^
footnote:[Heb. 13:7-8]
And John a minister of the word saith, "`That which was from the beginning,
which we have heard, which we have seen with our eyes, which we have looked upon,
and our hands have handled of the word of life; for the life was manifested,
and we have seen it, and bear witness,
and show unto you that eternal life which was with the Father, and was manifest unto us,
that which we have seen and heard, declare we unto you.`"^
footnote:[1 John 1: 1-3]
So that which was from the beginning with the Father, was before paper, and ink,
and writings, which the ministers of the word declared forth, and showed unto the saints:
and Peter, a minister of the word, in his epistle,
he saw the mockers and scoffers which spoke the high words in hypocrisy,
he declareth what the word was, "`That by the word of God the heavens were of old,
and the earth standing out of the water, and in the water,
whereby the world that then was, being overflowed with the water perished;
the heavens and earth which are now, by the same word are kept in store,
reserved unto fire against the day of judgment, and perdition of ungodly men.`"^
footnote:[2 Pet.
36-7]
So this is the word which is kept in store, and by which the heavens were of old,
as you may read: and the minister of the word, Peter, in his first epistle,
which declares of the builders that rejected the corner-stone,
such as had the scriptures, he saith, "`The word of the Lord endureth forever,
this is the word which is by the gospel preached unto you,
being born again not of corruptible seed, but of the incorruptible,
by the word of God which lives and endures forever;
as new-born babes desiring the sincere milk of the word; in the beginning was the word,
that which was from the beginning declare I unto you,
the word of the Lord endures forever;`"^
footnote:[1 Pet. 1:23:2]
but scripture is writing, and writing doth not endure forever,
but the word of the Lord endures forever: for all flesh is as grass,
and all the glory of man is as the flower of the grass that fadeth away,
but the word of the Lord endureth forever.

And in the epistle to the Hebrews, the minister of the word saith there,
"`Who being the brightness of his glory, and the express image of his person,
upholding all things by the word of his power, when he had by himself purged our sins,
sat down on the right hand of the majesty on high.`"^
footnote:[Heb. 1:3]
Here you may see that which upholds all things by the word of his power,
which the scripture speaks of, is that which was before writings was: and Paul,
a minister of the word saith, "`The word is nigh thee,
even in thy heart and in thy mouth, that is the word of faith which we preach,
that if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thy heart,
that God hath raised him from the dead, thou shalt be saved.`"
And then he saith,
"`The scripture saith (which are the writings) that
whosoever believes in him shall not be ashamed:
and the righteousness of faith speaks on this wise; say not in thy heart,
who shall ascend into heaven?
that is, to bring Christ down from above: or, who shall descend into the deep?
that is, to bring Christ up again from the dead: but (saith he) the word is nigh thee,
in thy heart, and in thy mouth:`"^
footnote:[Rom. 10:6-11]
and this is the word of faith which he preached,
and for preaching this word of faith were they persecuted, by them who had the writings:
and the twelve which were ministers of the word, called the multitude of the disciples,
and said unto them, "`It was not reason for them to leave the word of God,
and serve tables, but they would give themselves continually unto prayer,
and to the ministry of the word,`"^
footnote:[Acts 6:2,4,7]
as you may read: and the word of God increased,
and the number of the disciples multiplied: and in Deuteronomy you may read,
"`Neither is it beyond the sea, that thou shouldst say,
who should go over the sea for us, and bring it to us, that we might hear it,
and do it.`"^
footnote:[Duet. 30:11-14]
But the word is nigh unto thee in thy heart and in thy mouth, that thou mightest do it:
again, here you may see where the word is that Moses declared who wrote of Christ,
who said, "`Like unto me will God raise up a prophet,
him shall you hear;`" which prophet is the word;
and all the prophets from Samuel and all that have followed after him,
likewise foretold of these days of Christ,^
footnote:[Acts 3:22-24]
whose name is called the word of God.
When Peter, a minister of the word, was preaching Christ the word,
shewing how all the prophets did give witness,
that through his name whosoever believed in him should receive remission of sins:
while Peter was yet speaking, the Holy Ghost fell on them all that heard the word,^
footnote:[Acts 10:43-44]
which the prophets did give testimony of.

When the apostle preached the word of God, and most of the whole city came together,
the Jews were envious, who had the scripture,
and did not know the word that Paul preached; therefore saith the apostle,
"`Beware lest that come upon you which is spoken of in the prophets; behold ye despisers,
and wonder, and perish: for I work a work in your days,
a work in which you shall in no wise believe, though a man declare it unto you.`"^
footnote:[Acts 13:40-41, 46-50]
Yet the apostles Paul and Barnabas waxed bold, and spoke the word of God,
which was oft ministered among them that had the scriptures, and told them,
"`seeing you put it from you, and judge yourselves unworthy of eternal life,
lo we turn to the Gentiles,`" which had not the scriptures, Moses and the prophets;
and many of the Gentiles received the word,
and so the ministers of the word held forth the covenant of light to the Gentiles,
saying, "`I will also give thee for a light to the Gentiles,
that thou mayest be my salvation to the ends of the earth.^
footnote:[Isa. 49:6]
And when the Gentiles heard this they were glad, and glorified the word of the Lord,
and as many as were ordained to eternal life, believed.
And the word of God was published throughout all the region.
But the Jews which had the scriptures,
stirred up the devout and honourable women and chief men of the city,
and they persecuted Paul and Barnabas, and expelled them out of their coasts,
for preaching the word, and against them the apostles shook the dust off their feet,`"^
footnote:[Acts 13:48 to the end]
as you may read:
and in the same chapter you may see how the ministers of the word showed
unto the people how that which was written of the word was fulfilled;
and that it was said in the same scripture, "`Thou art my Son,
this day have I begotten thee:`" and to this agree the words of the prophets,
as it is written,^
footnote:[Ps. 2:7]
which showed the coming of Christ, the just one,
which the ministers of the word were witnesses of,^
footnote:[Acts 15:15]
and John a minister of the word said, that "`The word was made flesh,
and dwelt amongst them, and they beheld his glory,
as the glory of the only begotten Son of the Father, full of grace and truth:`"^
footnote:[1 John 1:14]
but he doth not say, that the writings were made flesh,
for the Jews that had the writings of Moses and the prophets, persecuted Christ the word;
and the chief priests, doctors, and the rabbies,
and such as had the law ministered forth, and sat in Moses`'s seat, had the writings,
the scripture, they did not know the word that was made flesh, but said he had a devil;
and so they that had the writings, the scriptures, were strangers to the word,
and knew not the word that was made flesh;
but they that saw his glory were ministers of the word,
the only begotten Son of the Father, full of grace and truth;
which same word is now manifest that ever was, Christ the same today, yesterday,
and forever: and saith Christ, "`If they call them gods to whom the word of God came,
the scripture cannot be broken;`" and saith Christ, "`As it is written in your law,
I say you are gods,`" +++[+++who hath an ear may hear this:]
and also it is written in your law, the testimony of two men is true,
I am one that bear witness of myself, and the Father that sent me beareth witness of me,
Christ whose name is called, the word of God.

Now the Jews that had the law, and the writings of the prophets,
and said they were of the seed of Abraham, and that God was their Father,
and they were not born of fornication,
these did not know Christ the word that became flesh,
as they who are gotten up into the same light of profession in this age;
and they could not understand Christ`'s speech, nor hear his word,
as they now that have the writings, and know not the word,
but put the writings for the word;^
footnote:[John 10 throughout]
and they questioned him whether he was greater than Abraham and the prophets, and said,
"`Who did he make himself,`"^
footnote:[John 8 throughout]
here they knew not the word (that had the scriptures) that became flesh, as you may read:
and many of the Jews, who had the scriptures, said the word was a devil,
and said of Christ Jesus, "`He hath a devil, why hear ye him?`"
And saith the prophet Jeremy, which cried against them that use their tongues, and say,
the Lord saith, when the Lord never spoke to them; and ran, and the Lord never sent them,
as these do that know not the word,
and by their lies and their lightness caused the people to err, saith the prophet,
"`What is the chaff to the wheat, saith the Lord?
Is not my word like a fire, and like a hammer that breaks the rock in pieces?`"^
footnote:[Jer. 23:28-32]
Now that which breaks the rocks in pieces, and is as a fire that burns up,
that is the word; he doth not say that the letter is so, as a hammer, and as a fire;
for though they had got the true prophets`' words, yet they did not profit the people,
which did not stand in God`'s counsel:
and the minister of the word in the epistle to the Hebrews declares,
that "`The word of God is quick and powerful, and sharper than a two-edged sword,
piercing, even to the dividing asunder of the soul and spirit, of the joints and marrow,
and is a discerner of the thoughts and intents of the heart.`"^
footnote:[Heb. 4:12-13]
This is the word, but he doth not say so of the letter which killeth,
neither is there any creature which is not manifest in his sight;
but all things are naked and open to the eyes of him with whom we have to do.
All things being upheld by the word, must needs be naked in his sight, and manifest;
and in the beginning was the word, by whom all things were made,
which is the word of reconciliation,
(to wit) "`That God was in Christ reconciling the world to himself,
not imputing their sins and trespasses,
and hath committed unto us the word of reconciliation,`"^
footnote:[2 Cor. 5:19]
which reconciles to God: the minister of the word thus saith,
who said the letter killeth, but the spirit gives life.

Many have the writings as the Jews had,
but they cannot witness the word of reconciliation;
for the Jews stood against the word of reconciliation, who had the writings,
as now the doctors and teachers of the world, who be in the nature of the Jews,
have given the writings the name of Christ, whose name is called,
"`The word of God,`" and persecute them who do not bow to their image:
"`And he was clothed in a vesture dipt in blood, and his name is called,
the word of God;`"^
footnote:[Rev. 19:13-16]
and this, John, minister of the word, declares in his revelation, and saith,
"`The armies which were in heaven followed upon white horses, clothed in fine linen,
white and clean: and out of his mouth goeth a sharp sword,
that with it he should smite the nations, and rule them with a rod of iron,
and he treads the wine-press of the fierceness and wrath of the Almighty God:
and hath on his vesture and on his thigh a name written, King of kings,
and Lord of lords.`"
And I saw the souls of them that were beheaded for the testimony of Jesus,
and the word of God, and which had not worshipped the beast, and his image,
nor received his mark in their foreheads, nor their hands; and they reigned with Christ,
whose name is "`The word of God.`"
See here now, they that did witness Christ the word of God, were beheaded, and suffered,
as you may read in John`'s testimony of the word,
and their`'s that were beheaded for the word.
The apostles went into the synagogues of the Jews and temple,
and them that held up the synagogues, tithes, and the first priesthood and the temple,
they having Moses and the prophets read amongst them every sabbath-day,^
footnote:[Acts 13:27]
the apostle showed them Christ Jesus the word that became flesh,
which the prophets prophesied of, which showed the coming of the just one,
and whom Moses wrote of: they showed them out of the prophets and Moses,
that Jesus was the Christ, whose name was called,
"`The word of God;`" and they hearing the scriptures, the writings,
but not knowing the word, were they that hauled out of the synagogues and temple,
and persecuted them that were ministers of the word,
and they knew not the word though they had Moses and the prophets, and the writings;
and the minister of the word did give testimony unto the word of his grace with boldness,
speaking in the synagogue and temple;
and the priests could tell by the scripture where Christ should be born;
When Herod had gathered all the chief priests together,
he demanded of them where Christ should be born?^
footnote:[Acts 13:46]
And the chief priests could tell him by the scripture, in Bethlehem of Judea,
it is written, for so saith the prophet:^
footnote:[Matt. 2:4-5]
now here the chief priests which had the writings of the prophets and the scriptures,
with which they could tell where Christ should be born,
and with it give answer to Herod at his demand, yet they knew not the word;
but the chief priest mocked him with the Pharisees,
and the chief priests and elders persuaded the multitude that they should ask Barrabas,
and crucify Jesus:^
footnote:[Mark 15:11,31]
here you may see that neither the chief priests nor elders knew the word,
"`And all the chief priests and elders,
and all the council sought false witness against Jesus to put him to death;`"^
footnote:[Matt. 26:59; and 27:1]
and the chief priests accused him and the elders;
now you may see here the chiefest of the priests,
and those that were elders sought false witness against Jesus the word of God,
though they had scriptures, as they do now against them who are witnesses for the word;
"`And the chief priests assembled together, and the scribes and the elders of the people,
unto the palace of the high priest who was called Caiaphas,
and consulted together to take Jesus by subtlety and kill him:`"^
footnote:[Matt. 26:3-4]
these had the writing, the scripture, but knew not the word; the chief of the priests:
as the chief of the priests and elders (they that have the writings of the prophets,
Christ, and the apostles) now, do cast into prison, and seek to put to death,
and scourge in the synagogues, and whip and beat,
and haul before the magistrates them that do witness Christ to be the word,
in the synagogues, and the scripture to be a declaration:
"`And these things shall they do unto you (saith Christ)
because they have neither known the Father nor me.
But these things I have told you, that when the time shall come,
you may remember I have told you.`"^
footnote:[John 16:2-4]
So we do remember now Christ`'s words, and see his prophecy fulfilled in this age,
they that have the writings, the scriptures in the synagogues and temple,
haul them out of the synagogues, and persecute them, imprison them,
and whip them that witness Christ to be the word, as the writings declare,
which they have among them read, every sabbath day:
but as Christ and the saints said to them which had the writings of the prophets,
they did not know the voice of the prophets, nor did they know the Son of God,
nor had seen God:^
footnote:[Acts 13:27]
and likewise the chief priests and the scribes and
the elders mocked Christ whose name is called,
"`The word of God;`"^
footnote:[John 5:37]
here they knew not the word, as they mock now at them who witness Christ the word,
and haul them out of their synagogues;
and the chief priests cannot endure the presence of them who witness Christ the word,
nor the elders, but persecute them; and the chief priests covenanted with Judas,
and bought Christ for thirty pieces of silver, to put him to death;
and a great multitude came with Judas with swords and staves,
from the chief priests and elders of the people,^
footnote:[Matt. 26:47]
to take Jesus to murder him; and here the chief priests which had the scriptures,
and the elders, knew not the word, but persecuted it, and them that believed in it,
and were ministers of it, as the disciples of Christ`'s testimony declare;
even as the chief priests and elders of the people which have the writings of the prophets,
Christ, and the apostles, now persecute them that believe in the word,
and own the word which the prophets showed the coming of,
and the apostles were witnesses of; and while Saul was among the chief priests and Jews,
he had authority from the chief priests, and a commission, to beat, to punish,
and to persecute in every synagogue them that believed in Christ the word;
this doth Paul a minister of the word declare,
in his examination and declaration to Agrippa;^
footnote:[Acts 26 throughout]
and when they were put to death for witnessing the word, Saul gave his voice;
and now do not the chief priests incense the multitude
against them that witness Christ the word?
And are they not hauled out of the synagogues?
And have they not authority from the chief priests and elders of the people to
haul out of the synagogues and to persecute them that witness Christ the word,
and the scriptures a declaration, as you may read.

And when the apostle was converted and denied the first priesthood,
from whence he had his authority to persecute,
and witnessed Christ the everlasting priest, whose name is called,
"`The word of God,`" then was he persecuted among them, and with them,
and by them that had the writings of Christ that was to come;
and they sought to put him to death who was a minister of the word,
and his end of going into the synagogues was to show them that Jesus was Christ,
out of the prophets, and Moses who wrote of him,
and showed the coming of him which they had the writings of,
but did not know him when he was come:^
footnote:[Acts 17:1-3]
so the end of the apostles going into the synagogues was not to hold them up,
nor the temple, but to witness Christ the everlasting priest, the everlasting covenant,
and the everlasting offering, and to bring the people to him,
to turn them from darkness to light,
so that they might come to witness their bodies temples of God.^
footnote:[1 Cor. 6:19]
so the ministers of the word Christ Jesus went into the synagogues to
the ministers of the law and the first priesthood that took the tithes,
that held up synagogues and temple;
and they that were ministers of the word were hauled forth by the first priesthood;
they that held up temple and synagogues hauled them out that were ministers of the word,
and knew not the word, and charged them to speak no more in that name,^
footnote:[Acts 4:18]
among them that had the writings, as you may read, and as the world doth now;
chief priests which have the writings and the tithes, and the synagogues,
are against them that are ministers of the word Christ Jesus,
who is the light of the world, and doth enlighten every one that cometh into the world,
that all men through him might believe, who is the word, whose name is called,
"`The word of God,`" and that every man might come
to hear that prophet which God hath raised up,
Christ Jesus, whom Moses prophesied of,^
footnote:[Acts 3:22-23]
and every soul that will not hear this prophet is to be cut off,^
footnote:[Acts 7:37]
as you may read; it is not the hearers of the word,
but the doers of the word are justified; if therefore ye hear and do the same,
happy are ye; "`Be ye therefore doers of the word, and not hearers thereof only,
deceiving your own selves,
and receive with meekness the ingrafted word which is able to save your souls,`"^
footnote:[James 1:21-22]
which is not the letter, nor the writing of the scripture,
but the ingrafted word is able to save your souls,
which you are to receive with meekness, as you may read,
which word the ministers of the word preach,
which differ from them that are ministers of the letter, and have the writings,
which do persecute them that are ministers of the word:
but never did minister of the word and spirit persecute any.

But Christ the word said, that they should be persecuted,
and they did persecute them from city to city, them that had the writings the letter,
which knew not the word which was in the beginning, by whom all things were made,
which is the word of reconciliation,
(which word now is witnessed amongst the children of light) they persecuted Christ,
the same today, yesterday, and forever?
Why persecutest thou me, saith Christ to Saul,^
footnote:[Acts 9:4]
who had his authority from the chief priests to persecute; and saith Christ the Word,
"`I was sick and in prison, and ye visited me not; I was naked and ye clothed me not;
and I was hungry and ye fed me not; and thirsty and ye gave me no drink.`"^
footnote:[Matt. 25:42-45]
When saw we thee thirsty, or hungry, or in prison?
(say they who have the writings and know not the word.)
Inasmuch as ye did it not to one of the least of these,
ye did it not unto me.
Therefore if you do not visit him in the prison,
what will become of you that cast him into prison?
Where will you stand in the day of judgment,
though you have and do profess the writings as the chief priests and scribes did,
but were persecutors of the word, and them that were witnesses for the word,
as the ministers of the word now are by them who have the writings,
but know not the word.
