== A Cry for Repentence, unto the Inhabitants of London, Chiefly,

And unto all those whose Fruits do shame their Profession, that they may come to Yea and Nay, in all their Communications, and Dealings, that their Life may judge the World; for who are out of that, are in the Evil, and fall into Condemnation.

Given forth for the Information of the Simple, that they may know the Way of Life, out of the evil communication which corrupts good manners.
By G. F.

Repent ye tradesmen of London, repent ye merchants and great men of the city,
the day of the Lord`'s hand is coming upon you,
the day of the Lord`'s wrath is to be poured upon you, who have lived in wickedness,
fulness and gluttony, and serving the creature more than the Creator,
who is God blessed forever; and serving your lusts more than Christ,
and making your bellies your gods, fatting up yourselves with the creature,
until you have forgotten God, until you grow proud and wanton:
alas! heap not up treasure upon earth, where thieves, and rust, and canker is,
but consider all of you what treasure you have in Heaven: ye tradesmen,
whatsoever calling you follow, turn to the Lord by repentance: ye watermen and fishermen,
repent, and put away your evil, and turn to the Lord by repentance,
whilst you have a day of mercy offered you: ye poorer sort of people, who are drudging,
labouring, and toiling in the earth under the great ones, repent: all ye small and great,
is not your labour for the mouth and apparel, yet your appetite,
your lust and eye is not satisfied.

Ye teachers of the people, called priests, who are got into the high places, repent,
and give over deceiving them, that ye may be found in the life of what you profess:
and ye rulers and magistrates, of what sort soever, high and low, small and great,
repent, repent, that ye may be found all in justice and judgment,
that this may run down your streets, and in them righteousness reign,
and the streams and floods of ungodliness may not run down, but be stopped:
ye proud and idle people, men and women, repent,
and come to acknowledge the Lord the Creator; and proud of the earth,
great rich and small, turn, turn to the Lord: and all you lawyers whatsoever repent,
that oppression may be taken off, and exacting there may be no more;
and mercy may be showed to the helpless, and the jaws of the wicked may be broken,
that would worry, and rend, and tear the innocent to pieces, that the oppressed,
the needy, and the helpless may be sought out, and of his burden eased,
that the Lord may bless you.

And all ye husbandmen, tillers of the earth, or keepers of cattle, repent,
that your minds may be brought out of the earth, and ye turned unto the Lord,
and that your minds may be brought out of the greediness of gain.
Ye buyers and sellers of cattle, and all others that are greedy of gain,
greedy after the earth, greedy after riches, greedy after fashions,
for this will men and women destroy one another with lies and flattery,
through greediness after gain, and the earth.
Repent; the voice and sound of repentance is cried unto you all,
which reacheth to the root of you all; and the axe is laid to the root of the tree,
and every tree that doth not bring forth good fruit to the Lord God,
must be cast into the fire; for the cry and voice of repentance is sounded,
and sounds to you all, rich and poor, small and great: all tradesmen, lawyers, merchants,
seamen, husbandmen, traders among cattle, judges, justices, rulers and magistrates,
and ye idle people of the land repent, for the day of the Lord`'s wrath is at hand,
his vial is to be poured out on you all.
And again, all you tradesmen, merchantmen whatsoever, or rulers, or judges, or justices,
or lawyers, or husbandmen, or buyers or sellers of cattle,
keep to yea and nay in all your communication; whatsoever is more is evil:
Is it not as well to say yea and nay, as to use so many words?
Is it not good to keep to yea and nay, to keep you out of the evil?
This is the word of the Lord God to you all whatsoever.

And again you tradesmen, merchantmen of all sorts whatsoever, buyers and sellers,
set no more upon the thing you sell in exchange, than what you will have;
is it not better and more ease to have done at a word, than to ask double or more?
Doth not this bring you into many vain words, and compliments, and talk,
that fills the vain mind?
This is deceitful before God and man.
And is it not more savoury to ask no more than you will have for your commodity,
to keep yea and nay in your communication, when you converse in your calling,
than to ask more than you will take?
And so is not there the many words where is the multiplying of sins?
This is the word of the Lord to you, ask no more than you will have for your commodity,
and keep to yea and nay in your communication,
and here will be an equal balancing of things,
and a consideration before you utter words, and a using of this world,
as though you used it not; and a possessing as though you possessed not;
and so you will come to show a life like christians, and the spirit like christians,
and you a people in Christ`'s doctrine, that love his doctrine,
which keep to yea and nay in your communication,
and you will not be a people that be high, and proud, and lofty,
So a child shall trade with you as a man, because of the equity, and yea and nay,
and righteousness, and true weighing of things, and true consideration of things,
and people shall not be afraid of one cheating the other, or destroying one the other,
where truth and equity is among them, and mercy and righteousness,
and no more is set upon the thing than what they will take,
who are in their yea and nay in their communication;
here is the consideration before words be uttered,
and where the power is over the tongue, the life of a christian is seen.

Ye porters and other labourers, and light and loose people, repent,
and all ye labouring people whatsoever, and judges of the earth, repent, repent,
and turn to the Lord God, lest against you the Lord`'s hand be turned speedily,
and you be found those that are convinced, and do not repent,
to give glory to the Lord God, lest into the bed of sickness ye be cast,
and sudden judgments and plagues come upon you;
for God is able to abase the pride and vanity of
them who have looked to the hills for salvation,
who cannot save themselves; therefore all ye that have lived unrepented,
whose lives are not changed, you are they that have cumbered the ground;
fruitless trees that have not brought forth fruit to God,
therefore have the streams of ungodliness, streams of unrighteousness,
rivers of wickedness,
floods of many waters been running so up and down the nations of the world,
which the woman sat upon, which sits upon the beast;
so have christians been an ill savour, their conversation, their communication,
who have been out of the yea and nay, the righteousness and judgment,
and are not at a word in their calling and trading, and commerce with people,
for which the heathen which are no christians judge them, as the Gentiles the Jews.
Oh ye christians, let your ways judge the heathen; let your lives, communication,
conversation, judge the heathen; let it not be in the earth, but in heaven;
ask no more for the commodity you exchange, than you would have.
You tradesmen, buyers and sellers of all sorts, or hirers of labourers, at a word speak,
and see before you speak, keep to yea and nay in all your communications,
this will keep you out of the evil, whatsoever is more comes of evil;
with this will you come to answer that of God in the heathen,
whom in righteousness God will judge.
Alas for you all your profession of the scriptures, of the apostles`',
Christ`'s and prophets`' words, if you be found out of the life of the prophets,
Christ and the apostles, is vain, ye are but as the Jews were,
of whom Christ said the devil was their father; and as the pharisees,
scribes and priests which Christ cried woe against, called whitened walls and graves,
vipers and serpents, venoming and poisoning others,
being not in the life the scripture was given forth from,
are found such as the apostles spoke of, vain janglers about words, and vain disputers,
and bringing the scriptures to oppose one another,
and disputing of Christ and the saints`' words, bringing scripture as the devil did,
and are out of the life that gave it forth, and disputing about the body of Moses,
such be in the unrepented state, which eat and drink damnation to themselves,
not discerning the Lord`'s body; therefore be ye warned.

This is the word of the Lord God to you all, ye rulers of the earth,
that righteousness and mercy, judgment and equity may run down, streaming in the nation,
that the oppressed may see relief, and the peaceable eased,
and the poor and needy may not be turned away,
that this may run down all that which is called Christendom, that professeth Christ,
who is come to reign, and has set up his kingdom in power and authority, and majesty,
who raiseth up jealousy as a man of war against all unrepented ones,
that the thoughts of men are full of, and their imaginations and conceivings are at work;
but the Lord is risen and rising, who will make waste him that hath made desolate,
who will judge righteously, according to the secrets of every man`'s heart,
who will enter into the house, bind the strong man, and spoil his goods.
The heart of all will I search, saith the Lord, the reins of all will I try,
the ways of all will I bring to light, the spirits of all will I make manifest,
and according to them will I judge,
who will make every one to confess that his ways and judgments are righteous,
and render to every one a reward according to his works, whether they be good,
or whether they be evil; I come quickly, and my reward is with me,
saith the Lord God Almighty, and there shall nothing escape in the heart,
but its secrets shall be revealed,
and the things that thou hast done in the body shalt thou give account for;
I will exalt my kingdom and set it upon the highest throne,
to tread dominions and principalities under my feet, who put down the authority,
who bear my government upon my shoulders; the Lord our righteousness is his name,
who judgeth according to the secrets of every man`'s heart,
who doth enlighten every man that cometh into the world,
with which be shall see when he doth evil, and when he doth wrong,
which is his condemnation that hates it; but he that loves the light,
which he is enlightened withal, and believes in it, shall receive the light of life.

And all you makers of images,
and makers of baubles and toys to please the lusts and vanity of people, repent, repent,
lest God consume you with the vanity; repent, lest God lay you in the dust with them,
and make you like unto them.
And all you that delight in fine houses, and apparel,
and the eyes are fixed in those things, repent, lest God destroy you with them.
And all you star-gazers and tellers of fortunes,
and drawing people to gaze after your fancy more than after the Lord, repent,
and be silent, and cover your lips, and give over your witchcraft, lest God cut you off,
and destroy you, and make a sudden end of you for your heap of confusion,
that hath long reigned and ruled against the Lord; God`'s arm is turned,
with which he will gather his people to himself; the furnace is prepared,
the oven is provided, and the high buildings shall be laid low, and the cities waste,
and without inhabitants: the Lord God is bringing his people to his city,
and many are in their way wandering to it; and many are entered into their rest.
Therefore to you repenting ones is this,
and to you unrepenting ones that you may come to see the way hither, out of the earth,
into the righteous way and path of life, which leads to God the father of life:
and to you this is the word of the Lord God,
from him that dwells in that which comprehends the world, and answering this,
shall be with that of God in every one of you.

G+++.+++ F.

Have not ribbons, jewels, images and baubles carried away the eyes and hearts of people,
which bringeth them to lose sincerity?
O repent ye whose hearts and eyes are given to vanity,
lest the Lord come upon you like mortar and clay, and tread you to pieces like potsherds.
