== The Woman Learning in Silence, 





or the Mystery of the Woman`'s Subjection to Her Husband.





As also the Daughter prophesying, wherein the Lord hath fulfilled and is fulfilling what he spoke by the Prophet Joel: "`I will pour out my spirit upon all flesh,`" etc.
Given forth by George Fox.

"`Quench not the Spirit.`"
"`Despise not Prophesying.`"--1 Thes.
5: 19-20.

Let your women learn in silence, with all subjection; here is a silent learning,
a learning in silence; I suffer not a woman to teach,
nor to usurp authority over the man, but to be silent; there she is to learn,
in the silence, and not to usurp authority over the man, but ask her husband at home.
That which usurps authority, the law takes hold of, but if you be led by the spirit,
then you are not under the law;^
footnote:[Gal. 5:18]
so I permit not a woman to speak in the church, as saith the law:
so let the woman learn in silence with all subjection;
but I suffer not a woman to usurp authority over the man, but be in all silence;
for Adam was formed, then Eve, and Adam was not deceived,
but the woman was in the trangression, (read 1 Tim.
2.) Nevertheless she shall be saved in child-bearing,
if she continue in faith and charity, and holiness, with sobriety.
Let your women keep silence in the church, for it is not permitted them to speak,
but they are commanded to be under obedience, as also saith the law,
the women are to be under obedience, and to be silent, and not to speak in the church,
as also saith the law, which doth not permit it: but Christ in the male,
and in the female is one, which makes free from the law:
"`I will pour out my spirit upon sons and daughters,
and they shall prophesy:`" and if they will learn any thing,
let them ask their husbands at home,
for it is a shame for a woman to speak in the church, which the law forbids,
(and commands silence;) it is a shame to suffer them to speak in the church.
What?
Came the word of God out from you, or came it unto you only.

Paul, according to the measure given to him, in all his epistles,^
footnote:[2 Pet.
3]
speaking in them of things of which some are hard to be understood,
which they that are unlearned and unstable wrest, as they do also the other scriptures,
to their own destruction: you therefore, beloved, seeing you know these things,
beware lest you also be led away with the error of the wicked,
and fall from your own steadfastness, but grow in grace,
and the knowledge of our Lord Jesus Christ,
who is the end of the law for righteousness sake.
Peter, who was unlearned in the letter, yet learned of Christ, says,
such as were unlearned wrest the scriptures, and the epistles, being unlearned.
The Scribes, Pharisees, great Rabbies, and doctors knew not the scriptures,
being not learned of Christ, he who was the life of the prophets, and the end of the law,
whom Peter was learned in, knew and preached, whom they knew not: so here the unlearned,
who were in the life, confounded all the learned out of the life,
and learned of him by whom the world was made,
who comprehended all the learning that was in the world; so the unlearned wrest,
they are to learn in silence, and not to speak, as saith the law,
but learn of Christ their husband who makes free from the law, Christ in the male,
and Christ in the female.

Husbands love your wives, and be not bitter against them.
Wives submit yourselves to your husbands as unto the Lord:
the husband is the head of the wife, even as Christ is the head of the church,
and is the saviour of the body; therefore as the church is subject to Christ,
so let the wives be subject to their own husbands in everything.
Husbands love your wives, even as Christ loved the church, and gave himself for it,
that he might sanctify and cleanse it, with the washing of water by the word,
that be might present it a glorious church, without spot or wrinkle, or any such thing,
that it should be holy and without blemish:
so ought men to love their wives as their own bodies; he that loveth his wife,
loveth himself, for no man ever hated his own flesh, but nourishes it, and cherishes it,
even as the Lord the church, for we are members of his body, of his flesh,
and of his bones; for this cause shall a man leave his father and mother,
and be joined to his wife, and they twain shall be one flesh: this is a great mystery,
I speak concerning Christ and the church;^
footnote:[Eph.
5]
he that hath an ear, let him hear this great mystery; now the unlearned men wrest it,
and the unstablished, who know not this great mystery;
you that are ignorant of the Lord`'s work, and the voice of his prophets,
who are wondering at the prophesying of the daughters,
who make yourselves ignorant of the scriptures,
and are wondering at the Lord`'s prophets, his daughters,
which Joel the Lord`'s prophet spoke of from the Lord, and saith the Lord to him,
I am the Lord your God, and none else, and my people shall never be ashamed:
it shall come to pass after those days, I will pour forth my spirit upon all flesh,
and your sons and your daughters shall prophesy, and your old men shall dream dreams,
and young men shall see visions;
and also upon the servants and upon the handmaids in those days will I pour out my spirit,
saith the Lord.

Here all may see the spirit of the Lord not limited,
but upon the handmaids and the servants is the Lord`'s spirit poured, and to be poured,
and many thousands of servants and handmaids witness
the spirit of the Lord poured upon them,
the word of the Lord fulfilled,
and upon the sons and daughters will the Lord pour out his spirit,
and they shall prophesy, and many daughters and sons, and young men and old men,
witness the spirit of the Lord upon them poured out, that visions are seen,
old men dream dreams, and young men see visions,
and their sons and their daughters do prophesy, Joel 2:28;
and in Acts 2. the apostles there did gather together, waiting upon the Lord,
and the Holy Ghost fell upon them, that were to wait for the spirit.
This prophecy of Joel they saw the fulfilling of,
yet to the world they were as men drunk;
and so here the apostles witnessed the fulfilling of the prophets,
who are witnesses of Christ, whom the apostles did give testimony of,
and did speak of the daughters prophesying;
and Philip had four daughters that did prophesy, which the apostle did not forbid;
and saith the apostle, despise not prophesying:
here the prophet Joel was not against the daughters prophesying,
nor the apostles were not against it, but said, despise not prophesying;
and saith the Lord, 1 Chron. 16:22. touch not mine anointed,
and do my prophets no harm: so you that persecute the daughters,
on whom the spirit of the Lord is poured, and believe them not,
you are they that despise the prophets, and despise prophesying,
and so have broken the apostles`' command, who saith, despise not prophesying,
and show that you are out of the prophets`' doctrine, and the apostles`' doctrine,
standing against the promise of God with all your might, who saith,
he would pour forth his spirit upon all flesh, and his daughters should prophesy;
and how can you be established, that believe not the prophets?
For believing the prophets they came to be established, as you may read, 2 Chron.
20.

So how ignorant of the prophets and promises of God do they,
called teachers of the world, make themselves manifest,
and how in darkness they appear to the children of light, 1 Thess. 5:20.
And you that despise prophecy, and cast the daughters and sons,
servants and handmaids into prison,
who witness the spirit of the Lord God poured forth upon them,
you show that you be out of the apostles`' doctrine,
and to be strangers to the spirit the scriptures were given forth from,
and are ignorant of the church the apostle speaks of,
who saith let the prophets speak two or three, and let the others judge,
and if any thing be revealed to one that sits by, let the first hold his peace,
for you may all prophesy one by one, that all may learn, and all may be comforted,
and the spirit of the prophets is subject to the prophets,
for God is not the author of confusion, but of peace,
as in all the churches of the saints.
This order was in the church of the saints, the prophets to speak two or three,
and the others to judge; and if any thing was revealed to another that sat by,
the first held his peace: they might all prophesy one by one,
that all might learn and be comforted,
and the spirit of the prophets was subject to the prophets, and this was order,
and not confusion, in all the churches of the saints,
which is disorder and confusion in the churches of the world,
who cannot endure a daughter to prophesy, for a daughter might prophesy,
and a daughter is a prophetess, whom the spirit of the Lord is poured forth upon,
and a son a prophet;
for you never read that any of the prophets or apostles were against the
daughters which had the spirit of the Lord poured forth upon them,
but a daughter might prophesy in the church: for let your prophets speak two or three,
and I will pour out my spirit upon all flesh, and your daughters shall prophesy.

So you that despise prophesying, despise God`'s command,
and are out of Moses`'s light and life, who said,
would to God all the Lord`'s people were prophets, Num. 11:26-28.
and daughters are the Lord`'s people;
and when they were prophesying in the camp, there ran a young man and told Moses,
and Joshua the son of Nun, the servant of Moses,
and one of his young men answered and said, my Lord forbid them; but Moses said unto him,
enviest thou for my sake?
Would to God all the Lord`'s people were prophets,
and that the Lord would put his spirit upon them.
Now mark Moses`'s answer, how far Moses was from limiting the spirit,
that he would have the Lord`'s spirit put upon them all, and said,
would that all the Lord`'s people were prophets.
Now hear you magistrates, priests and people,
which do put into prison sons and daughters for prophesying, and the Lord`'s people,
you show a contrary spirit, you show a spirit that hath erred from Moses`'s spirit,
who cannot endure that the spirit of the Lord should be poured upon them,
that they should prophesy, but would limit it to learned men, old books, and authors.
And Anna the prophetess, the daughter of Phanuel,
which was about four-score and four years of age, came into the temple,
who served God with fasting and prayer night and day,
she spoke of Christ to all them that looked for redemption in Jerusalem.^
footnote:[Luke 2:36-38]
Here was a large testimony borne of Jesus by Anna the prophetess;
here you may see a daughter which did give testimony of Jesus, which would be,
and is a wonder in this our age,
to see a woman of four-score years of age to speak of Jesus
to all them that look for redemption in Jerusalem,
as she did; put her in prison, would the wicked ones say,
into prison with her would the priests say.

And Paul, the minister of God, in Phil.
the 4th,
there he entreats his true yoke-fellow to help those
women which laboured with him in the gospel,
as you may there read.
The women were joined with the other fellow-labourers,
whose names are written in the book of life; and in Rom.
16. there you may see Priscilla and Aquila, Paul`'s helpers in Christ Jesus,
who for his life laid down their necks; here the wife Priscilla was an instructor,
and was one of them that laid down their necks, and a helper in Christ Jesus;
she and Aquila took Apollos, and expounded to him the way of God more perfectly;^
footnote:[Acts 18:24-26]
one who taught in the synagogue was instructed by
her and him in the way of God more perfectly;
at these you synagogue-teachers scoff, to be instructed by a woman,
and you that forbid a woman to speak that hath the spirit of the Lord,
you forbid scripture; for Aquila and Priscilla had a church in their house,
and the church in Priscilla and Aquila`'s house was to be greeted,^
footnote:[1 Cor. 16:19]
who were instructors; and in the aforesaid chap.
Acts 18. he that was speaking boldly in the synagogue,
witnessing Christ the second priest, the end of the first priesthood, that took tithes,
the law, the offering, and the temple,
Priscilla and Aquila expounded to him the way of God more perfectly,
and the apostle Paul, a minister of the Lord, who witnessed the daughter`'s prophesying,
saith, I commend unto you Phebe our sister,
which is a servant of the church which is at Cenchrea,
that you receive her in the Lord as becometh saints,
that you assist her in what business she hath need of,
for she has been a succourer of many, and of myself also:^
footnote:[Rom. 16:1-2]
this was Phebe the sister, the servant of the church,
which was to be received in the Lord, and assisted in whatsoever business she had need.
And saith the apostle,
as touching Priscilla and Aquila his fellow-labourers in Christ Jesus,
who laid down their necks for his life, unto whom he gave thanks,
and not only he did give thanks, but also all the churches of the Gentiles. Here you may see the account Aquila and Priscilla were in,
who laid down their necks for the apostle, how thank-worthy they were; and Mary, in verse 6.
was to be greeted, who bestowed much labour on the apostle.

You that cannot own the prophesying of the daughters, the women labourers in the gospel,
you are such as the apostle speaks of in the same chapter,
which serve not the Lord Jesus Christ, but your own bellies,
and by good words and fair speeches deceive the hearts of the simple,^
footnote:[Rom.
16]
for the obedience of these was gone abroad, which the apostle speaks of,
and your disobedience is gone abroad to the apostles`' doctrine,
who cannot endure the prophesying of the sons and daughters,
whom the spirit of the Lord is poured upon;^
footnote:[Joel 2:28]
and Mary Magdalen saw Jesus after his resurrection,
which on the first day of the week came to the sepulchre, and when she saw Jesus,
she knew not that it was he, and said unto him, master; Jesus saith unto her,
touch me not, for I am not yet ascended to my Father, but go unto my brethren,
and say unto them, I ascend unto your Father, and my Father, unto your God, and my God.
Mary Magdalen came and told the disciples that she had seen the Lord,
and he had spoken these things unto her; the same day at evening,
being the first day of the week, the disciples were assembled,
Jesus came and stood in the midst, and said, peace be amongst you.
Now here all may see that it was Mary Magdalen that was sent to declare his resurrection,
and she was to tell the brethren (the disciples) whither Christ was to go, to his Father,
and our Father, his God, and our God, where her testimony was received.
Now you that make a scoff and a wonder at a woman`'s declaring,
you may see that it was Mary that first declared Christ after he was risen.

So be ashamed forever, and let all your mouths be stopped for ever,
that despise the spirit of prophecy in the daughters, and do cast them into prison,
and do hinder the women-labourers in the gospel; and saith the apostle,
Christ in the male and in the female;
and if Christ be in the female as well as in the male, is not he the same?
And may not the spirit of Christ speak in the female as well as in the male?
Is he there to be limited?
Who is it that dare limit the holy one of Israel?
For the light is the same in the male, and in the female, which cometh from Christ,
he by whom the world was made, and so Christ is one in all, and not divided;
and who is it that dare stop Christ`'s mouth?
That now is come to reign in his sons and daughters, Christ in the male,
and Christ in the female?
And you that will not have him to reign in the female as well as in the male,
you are against scripture, and will not have him to reign over you,^
footnote:[2 Cor 13]
for that male in whom Christ doth reign, rule and speak,
he will own Christ in the female, there to reign, to rule and speak,
and come to see the apostle`'s doctrine, a minister of Christ and of God,
and not made by the will of man, who said, that Christ was in the male and in the female,
Christ all in all, and Christ in you, except you be reprobates.
Now you that be reprobates, in whom Christ doth not reign nor rule,
cannot endure that Christ should be in the female nor in the male,
but them you will haul into prison, and yet profess the words, as the Pharisees did,
to whom Christ said, I was sick, and in prison, and ye visited me not;
and I was naked and hungry, and ye clothed me not, nor fed me:
now they which might have scripture, and would not have Christ to reign, said,
when saw we thee in prison, or naked, and hungry, and we clothed thee not,
or visited thee not?
Inasmuch as you did it not to the least of these, you did it not unto me, said Christ.
So if they who visited him not in prison, who might have the scriptures to talk of,
of Christ that was to come, as you have of Christ which is come,
and would not have him reign, as you will not now;
such were to go into punishment prepared for the devil and his angels:
if such punishment came upon them that visited him not, when he was cast into prison,
what will come upon you that do cast him into prison?

But Christ is come to reign, be by whom the world was made,
who was before the world was made, who now reigns in his sons and daughters,
and in the male and in the female,
that the glory is seen that the Son had with the Father before the world began,
which glory those males and females that receive Christ do see,
and the spirits of the prophets are subject to the prophets,
whether it be son or daughter that prophesies,
for the spirits of the prophets are subject to the prophets,
and the prophets may speak one by one in the true church,
and the daughter may prophesy as well as the son.
Now every one having a light from Christ Jesus, the Son of God,
him by whom the world was made, being turned to the light, turned to Christ,
him by whom the world was made, sees him the prophet, whom God hath raised up,
which Moses spoke of, who is the end of the prophets, and with the light sees Christ,
the gift of God, the promise of the Father; and receiving him,
you will see with the light such as act contrary to the light,
which they are lightened withal, what portion is due to them,
who contrary to the light do act, which comes from Jesus Christ;
and with the light you will see the promise of life to them that walk in the light,
that comes from Jesus, and every one receiving the light which comes from Christ,
may receive the spirit of prophecy, whether they be male or female,
and the spirit of prophecy is the testimony of Jesus;
if male and female have received the testimony of Jesus,
they have received the spirit of prophecy.

