== A Declaration Concerning Fasting, and the Prayer that God Accepts.

Given forth by G. F.

To all you that be keeping fasts, who smite with the fist of wickedness,
and fast for strife and debate; against you hath the voice cried aloud like a trumpet.
Now to you, and to all, that you may come to know the true fast, which is accepted,
and the fast which is in the strifes, and the debate,
and smiting with the fists of wickedness; which fast is not required of the Lord: behold,
in the day of your fast you find pleasure, and exact all your labour; behold, mark,
take notice, you fast for strife and debate, to smite with the fists of wickedness,
you should not fast as you do this day, to make your voice known on high;
is it such a fast that I have chosen?
saith the Lord; a day for a man to afflict his soul;
is it to bow down his head like a bulrush, to spread sackcloth under him?
Wilt thou call this a fast, and acceptable day to the Lord?
Consider, all you that do fast,
see if yours be not hanging down the head for a day like a bulrush,
and is in strife and debate, and to smite with the fists of wickedness,
whose voice you make to be known on high, but this fast is not with the Lord accepted;
but that which leads you from strife, from debate, from wickedness,
which is not the bowing down the head as a bulrush for a day,
and yet live in exacting and pleasure, this is not accepted with the Lord,
but that which separates from wickedness, debate, strife, pleasures,
smiting with the fists of wickedness, that which separates from that,
brings to know the true fast, which breaks the bonds of iniquity,
and deals the bread to the hungry, brings the poor that are cast out to his own house,
and when he sees any naked he covers them, and hides not himself from his own flesh;
here is the true fast which separates from them,
where the bonds of iniquity are standing,
and the heavy burden of the oppressed remaining, and the yoke not broken,
who deal not the bread to the hungry, and bring not the poor to their own house,
and see the naked, but let him go unclothed, and hide themselves from his own flesh;
yet such will make their voice to be heard on high, as Christ speaks of the Pharisees,
which sounded a trumpet before them, and disfigured their faces,
to appear to men to fast, but the bonds of iniquity were standing,
strife and debate were standing, striking with the fist of wickedness standing,
that made their voice heard on high, who had their reward.

But that which brings to the true fast, which appears not to men to fast,
but unto the Father which sees in secret,
and the Father that seeth in secret shall reward it openly.
This fast separates from the Pharisees`' fast,
and them that bow the head for a day like a bulrush;
and this is it which brings to deal the bread to the hungry,
and to clothe thine own flesh when thou seest them naked,
and bring the poor to thine house, and to loose the bonds of wickedness; +++[+++mark,]
this is the fast, and to undo every heavy burden; +++[+++mark again,]
and to let the oppressed go free; this is the fast, and to break every yoke;
and thou that observest this fast, then shall thy light break forth as the morning;
and thine health shall spring forth speedily, and thy righteousness shall go before thee;
the glory of the Lord shall be thy rearward; then shalt thou call,
and the Lord shall answer, thou shalt cry, and he shall say, here I am;
if thou take away from the midst of thee the yoke,
the putting forth of the finger and speaking vanity,
and if thou draw out thy soul to the hungry, and satisfy the afflicted soul,
then shall thy light arise in obscurity, and thy darkness be as the noon-day;
the light brings to know this fast, and walking in it, this is kept,
and he that believeth in darkness abides not.

And again, the Lord shall guide thee continually, and satisfy thy soul in drought,
and make fat thy bones, and thou shalt be like a watered garden,
and like a spring whose waters fail not; these are they which are guided with the light,
which comes from Christ where the springs are.

And again, they that shall keep this fast, shall build the old waste places,
thou shalt raise up the foundations of many generations,
and shalt be called the repairer of the breach, the restorer of the paths to dwell in:
that which gives now to see the foundation of many generations,
is the light which separates from all which is out of the light;
and they that go out of the light, though they may pretend a fast,
bowing down the head for a time, yet they are far from this fast,
and him that doth raise up the foundation of many generations,
and is a repairer of the breach, and restorer of the paths to dwell in;
that which doth give to see this foundation of many generations;
and these breaches that are to be repaired and restored, and the paths to dwell in,
is the light, which brings to know the true fast, and where this fast is known,
which is from wickedness, from debate, from strife, from pleasures, from exacting,
from the voice that is heard on high, from the speaking of vanity,
from the bonds of iniquity which breaks every yoke, let the oppressed go free,
here the health grows, where the morning is known, righteousness goes forth,
the glory of the Lord is the rearward, and the light riseth,
and the soul is drawn out to the hungry, and satisfies the afflicted soul,
and the springs of living water are known and felt, the waters fail not,
here the Lord guides continually,
and the foundation of many generations comes to be seen and raised up,
and the repairer of breaches is here witnessed, and the restorer of paths to dwell in.

But all such as be from the light which the prophets were in, with which they saw Christ,
and such to be in fasts, where was strife, where was wickedness, where was debate,
where was bowing down like a bulrush for a day, lifting their voice on high,
and the bonds of wickedness yet standing, and the burdens unloosed,
and the oppressed not let go free, and the yoke not broken, the nakedness not clothed,
the bread not dealt to the hungry,
and the foundation of many generations not raised up until
these things before mentioned be broken down,
on such the light breaks not forth as the morning, and the Lord hears not that,
and such have their reward, and such their iniquities have separated them from their God,
and their sins have hid his face from them that he will not hear,
and such their hands are defiled with blood, and their fingers with iniquity,
whose lips have spoken lies, and tongues have uttered perverseness;
none called for justice, nor any plead for truth; they trust in vanity, and speak lies,
and conceive mischief, and bring forth iniquity, they hatch cockatrice eggs,
and weave the spider`'s web; he that eateth of their eggs dies,
and that which is crushed breaks out into a viper, their web shall not become garments,
neither shall they cover themselves with their work; +++[+++mark and take notice,]
their works are works of iniquity, the act of violence is in their hands,
their feet run to do evil, they make haste to shed innocent blood,
their thoughts are thoughts of iniquity, wasting and destruction is in their paths,
the way of peace they know not; there is no judgment in their doings,
they have made them a crooked path, whatsoever goes therein shall not know peace; +++[+++mark,]
such go from the light, therefore is judgment far, neither doth justice overtake;
and here is obscurity, and here is the walking in darkness,
and here is the groping like blind men, as though they had no eyes,
and their stumbling at noon-day in the desolate places, like dead men,
and here is the roaring like bears, and mourning sorely, like doves,
and here judgment is looked for, but there is none, and salvation is put far off,
for the light is denied which gives to see it, but here the multiplying of transgression,
and their sins testifying against them, and the transgression that was within them,
and their iniquities which they knew, in transgressing and lying against the Lord,
speaking the things they should not, when they knew with that of God in them,
they should not speak it; so departing from the way of God, speaking oppression,
revolting, conceiving and uttering forth from the heart words of falsehood;
here is judgment turned away backward, and justice stands afar off,
truth is fallen in the streets and cannot enter; yea truth falls,
and he that departeth from iniquity makes himself a prey; yea the Lord saw it,
and it displeased him.

These are such that are in the fast which God doth not accept,
and are not in the true fast of them, whose light breaks forth as the morning;
but these are such that be in the false fast, who grope like blind men,
and that which gives to know the true fast and the false fast, is the light,
that gives to see each, where the true judgment is, and the iniquity standeth not,
nor the transgressor, nor the speaker of lies,
but that is judged and condemned with the light, which makes it manifest;
and who be in this fast when they call upon the Lord, the Lord will answer them,
here am I; and here truth is pleaded for, and falsehood flies away,
but who be out of this fast in the perverseness, their tongues uttering perverse things,
are stumbling and groping like blind men, which be from the light, in the iniquity,
which separates from God, who hides his face from them that he will not hear;
going from the light, goes from the Lord and his face;
so this is it which must be fasted from, for this is it which separates from God,
and here comes the reward openly, which condemns all that before mentioned,
which is contrary to the light, injustice, iniquity, transgression, vanity,
and that which brings forth mischief, which hatcheth the cockatrice eggs,
and weaves the spider`'s web; he that eateth of these eggs dieth, +++[+++mark,]
that which is crushed breaks out into a viper; +++[+++mark again,]
their web shall not become garments,
neither shall they cover themselves with their works of vanity,
acts of violence is in their hands, this is all from the light in the wickedness;
their feet run to do evil, make haste to shed innocent blood;
their thoughts are thoughts of vanity, wasting and destruction is in their path,
this is all from the light: again, the way of peace they know not,
there is no judgment in their goings; they have made them crooked paths,
whosoever goes therein shall not know peace: +++[+++mark,]
who goes in their way, that know not the way of peace, shall not know peace,
whose path is crooked, where there is no judgment in their goings; +++[+++take notice,]
no judgment in their goings; and this is all from the light,
which manifesteth that which is to be judged, where the covenant of peace is known,
where all that which is contrary to that before mentioned, is kept out;
so all who live in those things before mentioned,
contrary to the light in the false fast, they may mark their path,
and behold their reward, who be out of the light, stumbling and groping like blind men;
and they that be in the true fast, are from all them separated, their words,
their actions and fruits, and their fast, whose fast breaks the bonds of iniquity,
and whom the Lord hears, and to whom righteousness springs forth, and goes before them;
the glory of the Lord is the rearward.
