== The Promise of God Proclaimed:





Which is Christ, the everlasting Covenant of God to the Jews, Gentiles, and all People upon the Earth, of which God spoke by his Prophets, and was preached by the Apostles, and by his Servants and Messengers, sent forth since for Barbadoes, New England, Virginia, the East and West Indies, and the South and North Parts of the World, to go to them all.--By G. F.

The promise of the most high God, that lives for evermore,
which he promised to the Gentiles by his prophets in the days of old, Isa. 11:10.
the earth shall be full of the knowledge of the Lord,
as the waters cover the sea, +++[+++mark,]
and in that day, +++[+++mark,]
there shall be a root of Jesse, which shall stand for an ensign of the people,
to it shall the Gentiles seek, +++[+++mark,]
to it shall the Gentiles seek, and his rest shall be glorious.

Behold, saith the Lord God, that lives for ever, behold my servant, whom I uphold,
mine elect in whom my soul delighteth; I have put my spirit upon him,
and the isles shall wait for his law, he shall bring forth judgment to the Gentiles,
+++[+++mark,]
judgment to them, though they lived as the wild beasts;
this is the promise which setteth up judgment in the earth,
and the isles shall wait for his law; he that creates the heavens, the Lord God,
and he that spreadeth forth the earth, and that which cometh out of it,
and he that giveth breath unto the people, and spirit to them that dwell therein,
and hath called his covenant in righteousness, and will uphold his hand;
I will give thee for a covenant of the people, and a light to the Gentiles,
to open the blind eyes, and to bring the prisoners out of the prison,
and them that sit in darkness, out of the prison house. Isa. 42:1,6-7.


The Lord he will not give his glory to graven images,
and his covenant of light is a new thing, he will bring to pass in the earth,
who measures the waters in the hollow of his hand, and meteth out heaven with a span,
and comprehends the dust of the earth in a measure, and weigheth the mountains in scales,
and the hills in a balance, the mighty God of heaven and earth,
that is the God of the spirits of all flesh, who hath all souls in his hand,
God that lives for ever and ever, whose hand is his power,
all nations are as a drop of a bucket, and are accounted as the dust of a balance;
behold he taketh up the isles as a very small thing,
all nations before him are as nothing,
and they are accounted to him as less than nothing, and vanity,
then to whom will you liken God, that lives for ever and ever.
Isa. 40.

And the living God saith, concerning Christ, his covenant,
is it a light thing that thou shouldst be my servant,
to raise up the tribes of Jacob and restore the preserved of Israel?
I will give thee for a light to the Gentiles, +++[+++mark,]
the heathen, which shall gather Israel, and be my salvation to the ends of the earth,
to him that the nations shall abhor, and man shall despise,
but thou shalt say to the prisoners go forth, and to them that be in darkness,
show yourselves, then the heavens shall sing, and the earth shall be joyful, Isa.
49. I will lift up my hand, saith the Lord God, that lives for evermore, to the Gentiles,
+++[+++mark,] the heathen, and set up my standard to the people, verse 22.
and thou shalt break forth on the right hand and on the left,
and thy seed shall inherit the Gentiles, and the desolate cities shall be inhabited, Isa.
54. +++[+++mark,]
the Gentiles shall inherit the seed, and so become heirs; and this is the covenant,
saith the Lord God, that lives forever, my spirit that is upon thee. Isa. 59:21.


Arise, shine, for thy light is come, and the glory of the Lord is risen,
the Gentiles shall come to thy light, and the kings to the brightness of thy rising,
and thou shalt see and flow together, and thine heart shall fear, and be enlarged,
because the abundance of the sea shall be converted, +++[+++mark the sea,]
unto thee, and the force of the Gentiles shall come unto thee,
and these shall show forth the praises of the Lord, that lives for ever,
and the isles shall wait for me, saith the Lord. Isa. 60:2,5.


And saith the Lord, that loves judgment,
that makes the everlasting covenant with the Jews,
their seed shall be known among the Gentiles, and their offspring among the people;
rejoice in the Lord my soul, and be joyful in God that lives for ever,
for he clotheth me with a garment of salvation,
and covereth me with the robes of righteousness,
who causeth righteousness and peace to spring forth before all nations;
the Gentiles shall see thy righteousness, and all kings thy glory,
and righteousness shall go forth as brightness, and salvation as a lamp that burneth,
the Lord God shall be an everlasting light unto thee, and thy God thy glory,
and the Lord God shall be thy everlasting light,
and the days of thy mourning shall be ended, and thy people shall be all righteous,
and they shall inherit the land for ever, the branch of my planting, the work of my hand,
that it may be glorified for ever, a little one shall become a thousand,
and a small one a strong nation, I the Lord will hasten it in its time. Isa. 60:61-62.


I will gather all nations and tongues, saith the living God,
and they shall come to see my glory, and I will set him for a sign among them,
to the isles and them afar off, that have not heard my fame,
and they that heard my glory shall declare my name among the Gentiles;
as the new heavens and the new earth, that I make shall remain before me, saith the Lord,
so shall your seed and your name remain, Isa. 66:19,22.
for thou O Lord that made the heavens,
the Gentiles shall come unto them from the ends of the earth,
and say surely our fathers inherited lies, wherein there is no profit, Jer.
16. here the Gentiles come to see their own vanities, with the light that comes from God;
proclaiming among the Gentiles, saith the mighty God, let the heathen be awakened;
come all ye heathen and gather yourselves together,
let the heathen be awakened and come up to the valley of Jehosaphat,
for there I will judge them round about; for the harvest is ripe and the press is full,
and the sickle is ready, Joel 3. and my name shall be great among the heathen,
saith the Lord of hosts, from the rising of the sun to the going down of the same,
shall my name be great among the Gentiles;
in every place shall incense be offered to my name.
Mal. 1.

Mat.
12. He shall show judgment to the Gentiles, and he shall not strive,
a bruised reed he will not break, nor the smoking flax he will not quench,
and shall bring forth judgment to the Gentiles; and Simeon prophesied,
who said his eyes had seen his salvation, a light to enlighten the Gentiles,
and the glory of Israel.
Luke 2.

The Lord sent Paul after he had opened his eyes,
and had chosen him to bear his name among the Gentiles,
and many of the Gentiles received the word of the mighty God through Paul,
and God granted repentance unto the Gentiles unto life,
and the Gentiles glorified the word of the Lord, as many as knew the life eternal,
and the Gentiles besought the apostles to preach the word.
Acts 13. And Christ suffered and rose again,
that he might show light to the people and the Gentiles, according to the prophets,
Acts 26. and so many of the Gentiles were called in the days of the apostles,
and came to see the glory of God.

And the Gentiles that sought not after the righteousness,
have obtained the righteousness of faith,
and the Gentiles did by nature the things contained in the law, which judged the Jews,
that had the law, Rom.
2. for both Jews and Gentiles were concluded under sin,
that he might have mercy upon all,
and God was the God of the Gentiles as well as of the Jews, Rom.
3. so glory and honour is to the Jew and Gentile,
that doth seek the glory and honour and eternal life;
and that the Gentiles might glorify God for his mercy, as it is written,
for this cause I will confess thy name among the Gentiles, and sing forth thy praise;
and Isaiah saith, there shall be a root of Jesse, +++[+++mark,]
that shall arise and shall reign over the Gentiles, and in him shall the Gentiles trust;
and God revealed his Son in the apostle, that he might preach him among the Gentiles,
who is now revealed that he might be preached,
and the blessing of Abraham might come upon the Gentiles,
that they might receive the promise of the spirit through faith, Gal. 14:3.
that the Gentiles should be heirs
and partakers of the promise of Christ by the gospel,
Eph.
3. to whom God would make known what is the riches of his promise to the Gentiles,
Christ in you the hope of glory, Col. 1:26. and great is the mystery of godliness,
God manifested in the flesh, preached unto the Gentiles, believed on in the world, 1 Tim. 3:16.
that it might be fulfilled that was written,
the land of Zebulon and Napthali by the sea coasts beyond Jordan,
Galilee of the Gentiles, spoken of by the prophet Isaiah,
they that sat in darkness and the region and shadow of death, to them light sprang forth,
Mat.
4.

Paul in his confession said, he was sent to open the eyes of the blind,
and to turn people from darkness to light, and from the power of Satan unto God,
this he confessed before the heathen rulers, for which they thought he had been mad,
which preached to the Gentiles repentance, to turn to God from dead works, Acts 10:11.
and Paul declared in the midst of Mars-hill the unknown God,
which set all the heathen in an uproar. Acts 17:22.


And the Lord put on righteousness as a breast-plate,
and the helmet of salvation upon his head, and the garments of vengeance, for clothing,
and was clad with zeal as a cloak. Isa. 59:17.




