== Something Farther Concerning Silent Meetings.

Concerning silent meetings; the intent of all speaking is to bring into the life,
and to walk in, and to possess the same, and to live in and enjoy it,
and to feel God`'s presence, and that is in the silence,
(not in the wandering whirling tempestuous part of man or
woman) for there is the flock lying down at noon-day,
and feeding of the bread of life, and drinking at the springs of life,
when they do not speak words; for words declared are to bring people to it,
and confessing God`'s goodness and love,
as they are moved by the eternal God and his spirit,
and so all the ravenous spirits that are from the witness of God in themselves,
cannot be still, cannot be silent, it is a burden to them;
so cannot keep at home in their own houses,
but are the hunters before the Lord like Nimrod, the first builder of Babel;
but God confounded them, for they went out of the stillness and quietness,
as did the Jews that went from the law of God, then they gadded abroad,
and changed their ways, and so did not see their salvation;
as do the apostate christians, who inwardly rove from the spirit of God;
so are gone from the silence, and stillness,
and from waiting upon God to have their strength renewed, and so are dropped into sects,
among one another, and so have the words of Christ and the apostles,
but inwardly are ravened from the still life,
in which the fellowship is attained to in the spirit of God, in the power of God,
which is the gospel, in which is the fellowship, when there are no words spoken.

G+++.+++ F.

