== The Fashions of the World Made Manifest

also A Few Words to the City of London.

What a world is this?
How doth the devil garnish himself, and how obedient are people to do his will and mind,
that they are carried away with fooleries and vanities, both men and women,
that they have lost the hidden man of the heart through vanity,
and the meek and quiet spirit, which is with the Lord of great price,
they have lost the adorning of Sarah, they are putting on gold, gay apparel,
plaiting the hair, men and women, they are powdering it,
making their backs as if they were carrying bags of meal,
and they look so strange that they cannot look at one another,
they are so lifted up in pride; pride hath so lifted them up,
and is flown up into their head, they snuff up like wild asses,
and like Ephraim they feed upon wind, and are gotten to be like wild heifers,
who feed upon the mountains: and pride hath puffed them up,
they are out of the fear of God, men and women, young and old, one puffeth up another,
they are not in the fashions of the world else, they are not in esteem else,
they shall not be respected else, if they have not gold and silver upon their backs,
or their hair be not powdered; or if he hath hung about his waist red, or white,
or black, or yellow ribbons, and about his knees, and gets a company in his hat,
and powder his hair, then he is a brave fellow, then he is accepted,
then he is no Quaker, because he hath ribbons on his back, and belly, and knees,
and his hair powdered; this is he they stand with their hats off to;
this is the array of the world.

Likewise the women, having their gold, or spots on their faces, and on their cheeks,
and foreheads, having their rings on their fingers, wearing gold,
having cuffs double under and above, having their ribbons tied about their hands,
and three or four gold laces about their clothes, this is no Quaker, say they,
this is it that pleaseth the world; this array, this attire pleaseth the world;
but this is not the attire of Sarah, whose adorning was in the hidden man of the heart,
of a quiet and meek spirit; this is the adorning of the heathen, not of the apostle,
nor of the saints, who said not wearing of gold, nor plaiting the hair,
but of a meek and quiet spirit, which was of the Lord of great price;
and here was the sobriety and good ornament, which was of the Lord accepted;
this was Paul`'s exhortation and preaching;
but we see the talkers of Paul`'s words live out of Paul`'s commands,
and example of Sarah, but are found in the steps of the great heathen,
who comes to examine the apostle in his gorgeous apparel.
Now are not all these that have got these ribbons hung about their breeches, hats, backs,
waists, knees, and hands, like unto fidler`'s boys,
and show that they are got into the fashion of them that be called rogues,
the fidler`'s boys, and stage players, and quite out of the paths and steps of solid men,
and in the very steps and paths of the wild heads,
which give themselves up to every invention and vanity of the world that appears,
inventing to get upon their backs, heads, feet and legs; and say,
if it be out of fashion it is nothing worth: are not these the spoilers of the creation,
and have the fat and the best of it, and waste and destroy it?
Do not these cumber God`'s earth?
Let that of God in all consciences answer, and who are in the wisdom judge.

And further, to get a pair of breeches like a coat,
and hang them with points up to the middle, and a pair of double cuffs on his hands,
and a feather in his cap; here is a gentleman, bow before him, put off your hats,
bow before him; gets a company of fidlers, a set of music, and women to dance,
this is a brave fellow, a gentleman; a gentleman; up in the chamber;
up in the chamber without, and up in the chamber within; are these your fine christians?
Yea, say they, they are christians.
Yea, but saith the serious people, they are out of Christ`'s life,
and out of the apostle`'s commands, and out of the saint`'s ornament;
and to see such a company as before mentioned, as are in the fashions of the world,
as is before mentioned, a company of them get a couple of bowls in their hands,
or tables, or shovel-board, or a horse with a company of ribbons on his head,
as he hath on his own, and a ring in his ear,
and so go to a horse racing to spoil the creature; Oh! these are gentlemen,
these are brave fellows, these are bred up gentlemen, these are no Quakers,
and they must take their recreations, and pleasures as lawful,
and these in their sports set up their shouts like unto the wild asses,
or like unto the kine or beasts when they are new put to grass,
lowing and glorying in the things before mentioned, but it is in the flesh,
not in the Lord; and these are called christians,
and show they are glutted with the creature, and then the flesh rejoiceth;
and here is bad breeding up youth and young women,
who are carried away with the vanities of their minds in their own inventions, pride,
arrogance, lust, gluttony, uncleanness, to eat and drink, and rise up to play;
this is the generation that God is not well pleased withal,
but their eyes are full of adultery, who cannot cease from evil;
these are they that live in pleasures; these are they that be dead while they live,
which glory not in the Lord, but in the flesh;
these are they which be out of the light that the scripture was given out from,
who live in the fashions and vanities of the world, and out of its adorning,
and in the devil`'s adorning, who are out of the truth,
and not in the adorning of the Lord, which is a meek and quiet spirit,
which is with the Lord of great price; but this ornament,
and this adorning is not put on with them which be adorned,
and have the ornament of him that is out of the truth,
which is not accepted with the Lord.

Is it not in all the synagogues, and temples, and churches, as the world calls them,
which be under the dominion of hireling-teachers, which teach for lucre and for gain,
and for money; the people that go thither to the temple, church and synagogue,
as the people call them, they sometimes spy abroad one upon another,
and sometimes upon the priest, to see what fashion he hath on,
and see what fashion the people have on them; and sometimes regard what the priest saith,
but it is gone out of them again, e`'er they are gone out of the synagogue, temple,
or church, as they call it; it is the fashion they can remember: ah! say they,
such a one hath such a fashion, and it is very well made;
and such a one hath such a fashion; and such a one remains in the old fashion,
which is not regarded; and here you see the eye is abroad,
and then in the week-day he gets such a fashion as he hath got in the steeple-house;
and then he or she comes to the steeple-house with their fashion,
which they have invented in the week-day; then may be sees another fashion,
then envy gets up,
that another have got a fashion which it may be their means will not reach to,
and then there is crying want; and to tell these they are of the world,
they would be angry; tell them they were of the fashions of the world that passeth away,
they would be angry; so they that be rich, full, in plenty, and abundance of the earth,
send for the tailor, what`'s the best fashion now?
I would have it made according to the fashion, or it is worth nothing;
such a fashion you may have; but who have such a fashion, saith the man or woman?
yea, but that fashion waxeth old, so that is worth nothing;
so every one strives to have a fashion according to the greatest,
and every one here is climbing up, and heightening up one another in these things.
And thus you see,
that many people go to the steeple-house on the first day to see fashions,
and show their fashions; and doth not many tradesmen go thither to see the fashion,
that they may please their customer with that fashion that they have seen at church,
as they call it, and the people have seen it likewise;
and therefore the tailor must make it according to the fashion, as the other was;
and then is not a great part of their talk about the fashions,
and about the invention of the fashions, and about the making of the apparel,
and about the putting of it on, that ornament, that attire; but where is Sarah`'s attire?
Where is Peter`'s counsel, that which is of the Lord of great price?
Do not all your fashions please your eyes?
Is not this of the lust of the eye, and the pride of life, and not of the Father?
Is not this the fashion of the world which passeth away?
And is not here the strife in all these trimmings, and envying one another,
and hatred to them that are in a fashion above your fashions?
And do not you scoff at another that is in a fashion below yours, make a mock of it,
and envy at them that be in a fashion above you, which your purse, you will say,
is not able to reach, but if I had money I would have such a fashion, I want money,
or I would have a gold ring on my hand; so the want is to get into the fashion,
which is the want of the fear of God.

But is not all this destruction to the creation,
and destroying the creatures of the Lord,
yea the best of the creation is destroyed here upon the lust,
and you carried away with the vanities of your minds,
and your own inventions of your wicked hearts, where envy, lust, pride, uncleanness,
ungodliness lodgeth: now do you not believe that God will spew you out,
for polluting and staining the earth, who are given up wholly to inventions and fashions,
crafts-men who are given up to inventing of fashions,
and so serving your invention more than God, though you may call upon him with your lips,
but your hearts are after your inventions; you call upon him with your lips,
professing him with your lips, but your hearts after your fashions,
the newest fashion that will please both priest and people; and like priest, like people.
Oh, say they, the Quakers`' religion stands in these things,
to cry against the fashions of the world altogether; nay, not altogether,
yet it doth stand to cry against them; their religion is pure,
and keep from the spots of the world, and from the fashions of it, that perish away;
it is time to cry against all your fashions,
for the devil hath carried you to such a height, who are in the wisdom that is earthly,
sensual, and devilish, it is time it was set upon the wall.

[.asterism]
'''

Oh!
London, thou art fatted in the flesh, whose flesh is as the flesh of horses,
and thou art stained with lust, pride and vanity, and thy beauty must fade and wither,
as the flower, to thee this is the word of God.
Thy profession without life is from God empty, thy wisdom, thy knowledge, thy prudence,
thy reason, understanding, the true understanding is hid from thee,
and this before-mentioned hath caused thee to err;
with the life of God thou art comprehended, and art to be ruled with the rod of iron;
thou hast been proud of thy profession, and religion and wisdom,
and knowledge and understanding, which hath been without the true ground,
and the worship is without the spirit, thy mountain must be beat,
and the rocks must be rent, the wall of the fenced city laid down,
thy high tower and castle thrown down to the dust,
all thy hypocritical profession shall not serve thy turn,
but God to judgment is come upon thee;
and thou who art found out of the life wilt be found unsavoury,
and trampled under by the foot of men, God will not heed thy wisdom,
he will not heed thy beauty, but deface it, nor thy pretence of God,
and Christ and pretence of profession of Christ, the apostles`' words and prophets,
the calling of him Lord, and the heart removed from him, in the pride, in the vanity,
in the lust, in the flesh, who the just hast destroyed.
Now the just is risen to plead with thee by fire and sword, which shall answer the just,
which thou hast quenched and destroyed in thee; therefore be awakened all hypocrites,
and heapers up of the earth, the Lord is risen, and will not spare;
and you that be from his witness, shall feel the judgment; and you that be in the field,
shall feel the sword, famine and plagues, you shall not escape it;
for the Lord that fills heaven and earth is come to judgment upon the earth,
who will answer the just in every man: and to you this is the word of God.

G+++.+++ F.
