== A Warning to All the Merchants in London, / And Such as Buy and Sell.

[.heading-continuation-blurb]
With Advice to them to lay aside their Superfluity,
and with it to Nourish the Poor.--By G. F.

For them to keep to yea and nay to all people in their common occasions,
for whatsoever is more than these, cometh of evil;
and to take heed of deceitful merchandize, and cozening, and cheating,
and defrauding one another, and dissembling one with another;
and to take heed of deceitful merchandize in all their buying and selling,
and in all their exchange; away with all deceitful merchandize,
for as a swift witness is the Lord come to plead with you,
and against you that use deceitfulness in your merchandize,
and use it in your buying and selling, and sir, and bow the hat, and scrape the foot,
and make the courtesy, and master, and mistress, in your service, and forsooth,
this is your vain custom,
and ask many times double the worth of the thing of some people;
and under this complimenting way, and in it, lies the deceit and over-reaching,
and lurks to cozen and cheat, telling a falsehood, a flattery;
so by fair speaking and flattering words, oft times the simple is deceived:
therefore this is a charge from the living God to you all, be true, be faithful to God,
be just, be innocent, and ask no more for the thing than you would have; be at a word,
so say, and so do; when you ask more than you will have, or almost double,
and say you will not take it except you have so much, and then send your boys after them,
and so take it, you are not here at so say, and so do;
and here are you judged with the law of liberty to be out of it,
far off from the life of christians, like heathens in life and practise;
therefore be at a word, and then you will be a good savour,
for the Lord is come near to judgment among you; for while you are not at so say,
and so do, you are not in the law of liberty, you are not in the prophets,
you are not in the gospel, you are found out of them all.

And again, ye merchants, great men and rich men,
what a dishonour is it to you to go in your gold and silver,
and gold chains about your necks, and your costly attire, and your poor,
blind women and children, and cripples,
crying and making a noise up and down your streets, a dishonour to your city,
showing that you are not under the law, nor under the gospel;
for under the law they had tithes and tenths to feed all the fatherless and strangers,
for tithes were partly for that work and end;
for how can you go up and down in your superfluity, and abound in your riches,
and see the poor, blind, and cripples go about your streets?
For of all other, the blind should be taken care of;
therefore let these things be minded, and considered, and fear God,
and do that which may be an honour to you, and to christianity, and your city;
and in all your shops, and warehouses, and exchanges, keep to your words, and so say,
and so do, and that you may not cozen and cheat one another, nor any people;
for some have a name and a bad report of deceitful merchandize,
which deceives the country people that deal with you.
O therefore blot it out, and do so no more, but judge one another in these things,
and be a good savour, and commend yourselves to the innocent and simple,
that a child may come among you and not be wronged,
and that will be pleasing to God that you do righteously, and to the just God,
that you do justly; and then to the righteous just God you will be a good savour,
and to the country people, when you are turned from the bad to the good,
so that you may be trusted for faithfulness and honesty, for in the contrary doing,
is dishonesty: and you that scrape, and cap, and courtesy, and sir, and master,
and mistress, and flatter one another with the deceitful titles,
and ask more for your commodity than it is worth, and are not at a word, so say,
and so do; but tell people you will not take it,
and then have your boys and lasses to fetch them back again;
this is the way to make the simple fear you, and the innocent to stand afar off,
and to keep up a bad savour, and a bad name; therefore this is the word of the Lord God,
and a charge to you in the presence of the Lord God, and to you all,
that you charge your servants not to cozen and cheat any,
nor to ask more for your things than you will take,
and to keep to yea and nay in your common occasions, and to keep to a word,
and that will be pleasing to God, and a good savour to all sober people.

And all you merchants whatsoever, and shop-keepers,
take heed of cozening and cheating of people with your dark back-windows;
for truth is risen, that will keep out all deceit; therefore be sober,
and take it patiently, and live in it, for truth will make you free;
and if you will be made free by truth, give over your deceitful merchandize,
and give over your many words, and keep to yea and nay; +++[+++mark,]
you must be judged by the law, and all your profession and crying up ordinances,
and your notions and experiences, while you live in deceitful merchandize,
and above yea and nay in your common occasions, you are in the evil,
and are not at so say, and so do; you are all judged by the law of liberty,
that are deceitful in your merchandize, in your buying and selling,
and cozening and cheating poor country people in your merchandize,
you are not to name the name of Christ,
but as you depart from iniquity and the truth hath not made you free,
who are found in the evil,
judged by the law of liberty in all your deceitful merchandize; therefore come to a word,
come to yea and nay, all you young and old whatsoever,
so by the Lord you will be received into his kingdom;
lest you be turned out with the rich glutton,
and the poor Lazarus taken into Abraham`'s bosom: therefore take in the blind,
halt and lame, and obey the things that Christ commands you, ye that call him Lord,
take in the blind and the cripples that cry up and down your streets,
and feast them when you make your feasts; for the rich feast the rich,
and not the poor that cannot feast them again;
and see now if you will take up the cross of Christ, and obey his commands,
then you will become like unto them, when you obey Christ`'s command,
and show that you have his spirit and mind in you, and are christians;
for while you are not made free by truth,
all your religion and profession of Christ and the apostles`' words is vain,
and your conversation is below in the earth, and not with Christ in heaven.

And again, all the while your poor, and blind, and lame cripples, and women,
and children, are crying up and down your streets, and steeplehouse-doors, and alleys,
and corners, after you that call yourselves christians,
and yet they christians as well as you, and so members of the same body; so you may say,
be clothed, be filled, be warmed, and be such a people the apostle speaks of,
yet let them be crying up and down the streets not provided for;
so this is to hang gold on one arm, and let the other go bare; or hang gold on the back,
and let the leg go bare; for all are members of one body, the poor as well as the rich,
and this declares that you are out of the law:
for the Lord took the tithes and gave them to the strangers, and fatherless, and widows,
and gave all enough, that there was not a beggar in Israel among them.
Now judge yourselves, and see how short you come of them in life and practice,
which say you are christians, and profess the gospel;
these things are a grief to many sober people in the city,
to see that magistrates have no more feeling of these things,
and yet so much profession of religion and preaching among them,
and so much riches that men never knew want of; and thereby many come to be hardened,
and one might think, if it were but to keep the honour of their city,
they would not let above all things, blind men, and cripples, and lame people,
and poor fatherless children make a noise up and down the streets,
and steeple-house-doors; but out of their abundance they would lay a little aside,
and have a place provided that all the poor, blind, lame cripples should be put into,
and nurses set over them, and looked to, cherished, and seen unto that they do not want;
and thus they that could work, to work; and this would be a good savour of the city,
and of the magistrates, aldermen, and merchants of the city, and to the sober people,
and to the Lord God, that there should not be seen a beggar walk up and down the streets,
but that there might be a place where they might
be maintained with a little out of their superfluity;
yea, before there should be such a noise with the poor, the blind, the lame,
and the fatherless, every one lay by a little out of their abundance,
and spare some off their backs in gold and silver lace, or their chains and rings;
for who considereth not the cry of the poor, but turneth his ear from them,
them their Maker will not regard: and all who do not visit the fatherless, and the poor,
and the sick, and feed the hungry, and clothe the naked,
and are of a profession of religion, and makes a talk of Christ`'s words,
and the prophets`', and Moses`'s, such are in the wisdom below, which is earthly,
sensual, and devilish, not preservers of the creation,
not in the wisdom that is from above, which is gentle, easy to be entreated,
by which the creation is to be preserved,
by which it must be ordered again to the glory of God; you going in your gold and silver,
yea in your very shoes laced, and the poor want bread, want stockings and shoes;
and you your many dishes, change of dishes, and that you call novelties,
and the poor cannot get bread; spare one of your dishes,
and let it be carried to the place for the poor,
and do not let them come begging for it neither,
but let them have a place where they may be kept,
and that will be for your honour and renown;
for consider what abundance of riches is in this city,
and what good you might do with it, or how soon you may be taken from it, or it from you,
by fire, or sea, and yet for all this ye will not consider your poor brethren,
which are made of the same blood and mould, to dwell upon the face of the earth;
therefore mind truth, that makes free from deceit, and from all cozening and dissembling,
and will bring you to a word in all your common occasions, and to so say, and so do,
and to worship God in the truth, and to worship God in the spirit,
that the devil is out of, and come to the pure religion, which is,
to visit the fatherless, to visit the sick, and relieve the hungry, and clothe the naked,
that brings you to practise and to do the will of God;
and give over your living in words, and your hearts afar off, surfeiting in riches,
iniquity and deceit; but come to honesty and plaindealing, and mercifulness,
and take heed of pride, and loftiness, and wantonness, and haughtiness,
and walk humbly before the Lord, that you may come to the life the saints, the prophets,
Christ, and the apostles were in.
For the mighty day of the Lord is coming,
wherein every one of you must give account of his deeds done in the body,
and every man`'s work must be tried by fire,
and every man`'s work shall be brought to the light, and made manifest by it.
So your day is not past, while you have time, prize it.
