== The Pearl Found in England.

This is for the poor, distressed, scattered Ones in foreign Nations.
From the Royal Seed of God, and Heirs of Salvation, called Quakers,
who are the Church of the Living God, built up together of Living Stones in England:
A Visitation and Uniting to the Pearl of God, which is hid in all the World,
that every one may turn into himself, and there feel it, and find it.--By G. F.

Friends,--The pearl is hid in the field, and the field is the world,
and the world is in your hearts, and there you must dig deep to find it;
and when you have digged deep and found it,
you must sell all to purchase and redeem this field,
and there you shall know the merchant-man that makes the exchange,
and there shall you know Christ, in you the hope of glory, to save you, and redeem you,
the Immanuel, God with us;
and there shall you know the woman that lost the piece of silver,
and was seeking it without; but when the candle was lighted and the house swept,
she found it in her own house, and then she did know the joy,
and went and told her neighbours; and then she did know the day-star rise in her heart,
and the day dawning, whereby the light shall be known,
that shines from the east to the west, and the word of faith in the mouth and heart,
and the oil is in thy lamp if thou enterest in with the bridegroom;
the light shines in thine own heart to give thee the light of the
knowledge of the glory of God in the face of Jesus Christ,
from whence it comes, and the anointing which abideth in thee will teach thee,
and as it doth teach thee, thou shalt continue in the Father and the Son,
from whence this holy unction comes, and thou hast received it,
and here thou shalt know that thou needest no man to teach thee,
but as the same anointing doth teach thee, and the ingrafted word,
able to save your souls, is in your hearts, and the hidden man of the heart,
which is renewed day by day is found there, and the meek and quiet spirit,
which is with the Lord of great price, is found in thee,
and the covenant of grace that brings salvation is in thy heart, and in thy mouth,
to season it and thy words, and to teach thee to deny all ungodliness and worldly lusts,
and the heap of teachers set up by men`'s lusts in the world,
that turn this grace into wantonness, and live wildly,
and it will teach thee to live soberly.

The devil went from the truth, and deceived the nations, and abode not in it,
and he rules in all the hearts of the children of disobedience, that obey not the truth,
he that went out of the truth, and so they become synagogues of Satan, and murderers.
Cain went from the truth, the Jews went from the truth, and so were of the devil,
the false prophets, antichrists, inwardly ravened from the truth,
and so all these turned against the just, and became murderers:
but who are come to the just that they ravened from, over all these they reign,
and bring people to God, to reign over all this that is out of the truth,
and contrary to it.
All you high gazing professors, and hypocrites,
the kingdom of heaven is within you (like unto a grain of mustard-seed,
like unto heaven) that comes not by observation,
who are and have been gazing for it without you.

Come all ye wearied souls,
who have been long travelling these many years since the
days of apostacy from the true apostles and disciples,
where darkness and mists have gone over the earth,
and blinded and darkened the minds and eyes of the people,
the true ministry being lost since the days of apostacy,
whereby people have run into heads, and parties, and sects,
and truth amongst them held in the unrighteousness,
the sin and the enmity in every one`'s mind, men slaying one another about religion,
and for religion, and about worship, which was not the work of the true christians,
true ministers, and true apostles, but they brought people into unity,
and wrestled against principalities, and powers, and spiritual wickednesses,
which ruled in the children of disobedience,
and brought them to the thing which they disobeyed,
so the enmity having been in all minds of professors upon earth, amongst christians,
teachers, people, and rulers, who would slay one another,
murder one another about worship, about scriptures, the prophets`',
Christ`'s and the apostles`' words: here is the devil, the old adversary of man,
got amongst professors, provoking to destroy one another,
keeping up the form of the saints`' words, in the nature of the Jews,
that kept up the form of the prophets`' and Moses`'s words,
which Christ said were of their father the devil, amongst whom the pearl was lost,
that has been lost since the days of apostacy from the apostles`' life, Christ`'s life;
nations covered with ignorance like unto waters.
But the prophets, Christ, and the apostles, they were in unity in the spirit,
which led them to speak forth the scriptures,
which now are professed amongst christians in Christendom, but the life of Christ,
of the prophets and the apostles, they having been out of, they want the bond of peace,
the unity; for the unity is in the spirit, which is the bond of peace, which Christ,
the prophets and apostles were in, that gave forth the scriptures, so words, forms,
traditions, inventions, idols, have people fallen out one with another about.

But now that is manifest which comprehends the world,
which was before the world was made; Christ Jesus the covenant of God,
which doth enlighten every man that comes into the world,
that all through the light might believe and feel the witness in themselves,
in which people come to have peace with God, and every one receiving the light,
that they be enlightened withal, him they receive that hath enlightened them,
Christ Jesus in their own particulars,
which gives them to see their sins and so to see the saviour of their souls,
and to know the saviour of their souls, Christ Jesus, from whom the light comes; for,
saith God, I will give him for a covenant, a light to the Gentiles,
and a leader to the people,
and I will make a new covenant with the house of Israel and Judah, them that had the old;
I will put my laws in their minds, I will write them in their hearts,
and they shall not need to say know the Lord,
which covenant thousands in England do witness, that they need not say know the Lord,
in which they have unity one with another,
and peace with God through Christ Jesus his covenant, and witness the power of it,
and feel the covenant of light, the leader, and God`'s covenant fulfilled,
him that Abraham, David, the prophets gave testimony of should come,
him that the apostles did give testimony of was come and risen, he is enjoyed,
in which people come to have unity one with another, (and the scriptures,
and the thing the scriptures speak of,) and God; and in the light,
him by whom the world was made, there is no occasion of stumbling,
so the covenant of light that God said he would give
by his prophets for a leader of the people,
the way to the Father, thousands witness him leading of them out of the first Adam,
drove from the Father, who is the end of the prophets,
and he is leading of them up to God, and is their teacher,
and they have found him in them, and come to him, and found rest for their souls,
and their souls have rest, and they have taken on Christ`'s yoke that is easy,
and his burden that is light, and he is become their teacher; and men`'s yokes,
and burdens, and teachings, and doctrines come to be ceased, from, and cast off,
which have ruled since the days of the apostacy from the apostles.

And the pearl that hath been hid in the earth is found, and the morning star is risen,
and the day is dawned, and the true light shines, and wisdom, (which all the knowledge,
understanding and wisdom that man hath cannot comprehend
nor find) cries in the streets to the simple ones,
and for all to fear God that they may receive it, the wisdom of God, Christ Jesus,
him by whom the world was made, the wisdom by which all things were made and created,
and to come out of sin and transgression which all the world has lived in,
that have the form of godliness, but have been in the transgression from the life,
and ravened from it, and have been in the sheep`'s clothing,
but everywhere has been ready to worry the lambs, they that have gotten their clothing,
the outside, the form of godliness, but inwardly ravened from the life, the antichrists,
which Christ said should come, John saw were come,
which the world hath been wandering after; so there has been the pearl hid,
and the life of Christ, the prophets, and apostles has been lost,
and the form they have had,
but life and glory is risen that manifests and discovers all things,
and churches and teachers that have not been made by the will of God,
which has got up since the days of the apostles,
from all such is God bringing his people to teach them himself, and from all their ways,
to Christ the way to the Father, and from all their churches to the church in God,
the pillar and ground of truth, and over them, and to the anointing which abideth within,
to which people are come, which as it doth teach them, they continue in the Son of God,
and the Father, and need not that any man teach them,
but as the same anointing doth teach them, which abideth in them,
and as it doth teach them, they continue in the Son of God, in the wisdom of God,
they continue in the life and in the truth; they continue in the covenant of God;
they continue in the power of God, and the rock Christ Jesus,
him by whom the world was made, before it was made;
in which people come to have peace with God, and one with another,
and the foundation of many generations is found and witnessed,
that breaks down the bond of iniquity that made the breach betwixt God and man,
which makes up the breach betwixt God and man, whereby health, and glory,
and peace in the inward is felt, the election is known before the world was made,
which hath obtained the promise of eternal life,
and the power of an endless life is enjoyed, and the world to come.

Therefore come all hither ye scattered ones over the world, the power of God in you feel,
and then you feel Christ Jesus who hath enlighted every one that comes into the world,
then you will feel the covenant, which you have with God,
which will blot out your sin and transgression,
then you will feel the blood of Christ Jesus which cleanseth from all sin,
which the light discovers as you walk in the light, as he is in the light,
and you will have fellowship one with another; the kingdom of heaven is seen,
which is as a grain of mustard-seed which is within, and many have received it,
and are become as little children, and they that be instructed to the kingdom,
they bring forth their things new, and their things old;
and many are digging in the field, which is the world,
which is set in their hearts seeking for the pearl, and many have found it,
and many merchant-men be exchanging, glory to the Lord forever.
So the pearl is within you, that is found in the nation of England,
and all people upon the earth come into yourselves, find the pearl in you,
the precious pearl that has lain under the earth,
and come out of your talk and profession in words, in which the Jews were,
in whom the pearl was hid, that you may find the pearl in yourselves,
and the kingdom there within you, though it be like a grain of mustard-seed,
it is like unto leaven, it will leaven you up into a new lump; teachings, churches,
notions without life shall wither, fade like flowers, wither like grass,
be burnt up like stubble, sticks and chaff that has cumbered the ground,
the wheat is got out into the garner, the lambs are leaping,
the Father carries them in his hands,
the babes born of the immortal seed by the word of God, and are at the breast sucking,
living riches is manifested, God the Father is known,
and is worshipped in the spirit and in the truth, in that which the devil is out of,
the blood of Jesus is witnessed, which flows and cleanseth from all sin,
the fountain is opened, where is the washing of all sores,
and God is bringing people into the life that gave forth the scriptures,
that the prophets, Christ and the apostles were in,
in which life they shall see their words, and have unity with them,
and with the Lord God, and one with another,
and the word of faith is possessed and known in the heart, in the mouth,
that divides asunder the precious thoughts from the vile thoughts,
and precious desires from vile desires, and precious affections from vile affections,
and it is in the mouth to divide asunder the precious words from the corrupt words,
and this word that divides asunder the precious from the vile, is quick and powerful,
and sharper than a two-edged sword: for the vile separated from God,
the word that divides it, the vile from the precious, hammers it down, burns it up,
cuts it down, reconciles to the Father, and separates that which separated.

So the word of God in you all feel, in all your occasions,
and then you will have the word of wisdom,
that will divide asunder your precious thoughts from your vile thoughts,
your precious words from your vile words, and this will teach you in all your occasions;
the pearl in you come to know, the seed in you come to know, which seed is Christ,
that inherits the promise, which now is risen in thousands,
who are come to be heirs of the promise, and heirs of God,
and heirs of the world that has no end: the anointing in you all come to know,
which abideth in you, and then you need not that any man teach you,
but as the same anointing doth teach you, and as it doth teach you,
you shall continue in the Son of God, from whence it comes,
in him by whom the world was made.
The kingdom of heaven in you all come to know,
which is like unto a grain of mustard-seed, and as you all come to receive it,
you will all come to be as little children, and there you will come to feel the leaven,
which leavens you up into a new lump, and so to know the kingdom of the world,
to become the kingdom of the Son of God, and this is the kingdom of heaven,
like a grain of mustard-seed in you, which never consented to sin, and receiving that,
you come to be as little children,
and to know the leaven that will leaven you up into a new lump,
which thousands do witness in England;
and the light all come to know which shines in your hearts,
which must give you the light of the knowledge of
the glory of God in the face of Christ Jesus,
in Christ`'s face, from whence the light comes, him by whom the world was made,
glorified with the Father before the world began; I am the light of the world,
and I do enlighten every one that comes into the world, saith Christ the second Adam,
who is the way again to God, man being drove from God in the first Adam,
Christ the second Adam, the life, the truth, is the way again to God,
which every one that comes into the world, is enlightened withal;
for man being drove from God, he is drove from life, and drove from God,
he is drove from truth, and drove from God, he is drove from his wisdom,
and drove from God, he is drove from his righteousness, and from his power,
under the power of Satan; so Christ the power of God through death destroys death,
and him that hath the power of death, the devil,
and is over it before the world was made, the redeemer of mankind out of the fall,
who doth enlighten every man that comes into the world,
that all through him might believe,
and he that is come into the light which he is enlightened withal,
he is come into the wisdom of God, into the righteousness of God,
he is come into the way, he is come to Christ the power of God, to the rock,
him by whom the world was made, and so come to the life, and rest, and peace.

He that believes is saved, he that doth not is condemned;
and he that believeth hath the witness in himself, and hath set to his seal,
that God is true, who hath performed his promise,
and sees the prince of this world is judged, and is come into the righteousness of God,
Christ Jesus, so Christ Jesus, he is the righteousness of God,
he is the new and living way, and the one way to the Father,
and all the many ways are in the first Adam, drove from God, in the transgression,
but Christ the second Adam, is the Lord from heaven, as death came by the one,
life came by the other, and as darkness came by the one, light comes by the other,
who is the righteousness of God, the truth, the life, as unrighteousness by the one,
righteousness by the other, as untruth by the one, so truth by the other,
as the many ways by one, so the one way to the Father by the other;
there is disobedience by one which brings death,
there is obedience by the other which brings life; him you must all come to find in you,
Christ Jesus, except you be reprobates, then you come to witness the substance,
then you come to know the everlasting covenant,
then you come to know the prince of peace,
the prince of life and comfort of what you do profess in your own particulars,
in coming into the covenant of the Father; for death has reigned from Adam till Moses,
and the law and the prophets were until John;
Moses had the law which went over all transgression,
and answered that in all people which was transgressed; Moses`'s words people have had,
but they have been out of the life of Moses; the prophets`' words they have had,
but they have been out of the life of the prophets; John`'s words they have had,
but have been out of the life of John; Christ`'s words they have had,
but the life of Christ they have been out of; the apostles`' words they have had,
but the life of the apostles they have been out of;
the apostates since the days of the apostles; now Christ said in the 7th,
and 24th of Matt.
that false prophets and antichrists should come,
to his disciples before he was offered up,
and Christ gave to his disciples the marks by which they should know them,
that they should be inwardly ravening, that is, devourers, having sheep`'s clothing,
that is the outside, but wolves inwardly; do men gather grapes of thorns,
or figs of thistles?
By their fruits you shall know them: now before the disciples`' decease,
Christ said unto them false prophets and antichrists should come,
they saw they were come already into the world,
as saith 1 John 2:4. Little children I write unto you that it is the last time,
whereof you have heard say, antichrist should come, whereby you know it is the last time,
for there are many antichrists, many false prophets already in the world,
and they went forth from us that it might be manifest they were not of us,
for had they been of us, no doubt they would have continued with us; but saith he,
ye have an anointing which abideth in you (to the
saints) and ye need not that any man teach you,
but as the same anointing doth teach you, and as it doth teach you,
ye shall continue in the Son of God and the Father; and Christ who said they should come,
he bade them not go after them,
the false prophets and antichrist which should be inwardly ravenous;
John saw they were come; he told the saints the anointing was in them to teach them,
and the false prophets and antichrists, of which they had heard say should come,
they were already in the world, and went out from them, and were inwardly raveners,
and all that dwelt upon the earth went after,
and all the world came to worship the beast and false prophet,
and all nations drank of the wine of her fornications, that is, of the whore. Rev. 13:17-18.

And now cry the professors and teachers of the world, they are come but now,
and now is the last time; but did not John say,
it was the last time when all nations had drank the cup of fornication,
and all that dwelt upon the earth had worshipped the beast:
now we say people are coming from the false prophets,
those which Christ said should come, John saw was come, which went forth from them,
which all people that dwelt upon the earth went after,
and all nations came to drink the cup of her fornications, and she sits upon the waters,
and the waters are people, and nations, and tongues, and languages, and multitudes, Rev.
17. where she sits, tongues are waters, people waters, languages waters, nations waters,
multitudes waters, for they have been from the rock, they which Christ said should come,
and John saw was come, that went forth from them; and so have been as waters,
and so the first beast arose out of the sea, and the second out of the earth;
and all this Babylon building up and throwing down, and all these crosses and images,
pictures and worshipping of names and idols, and all these pulpits, priests, tithes,
churches, with crosses in the church-yards, and church-ends, have been of them,
and all this making of ministers by the will of men, by their schools and colleges,
for covetous ends, and covetous practices, are amongst the apostates,
which are apostatized from Christ`'s disciples, who went forth freely, sent forth by him,
and all these names of blasphemy amongst people called christians are of the beast,
and given by the beast since the days of the apostles in the apostacy;
in their days there were not so many names given to christians;
so that which Christ said should come, John saw was come, which went forth from them,
which all the world went after, and worshipped the beast and false prophets,
but who had their names written in the Lamb`'s book
of life before the foundation of the world,
which kept the testimony of Jesus,
against whom the beast and false prophets should make war, and should overcome,
and the woman fled into the wilderness, and the man-child was caught up unto God,
that which ravened forth, which was the wolf from the life,
turned against them that kept the life; the testimony of Jesus which is the spirit.

But now the Lamb and the saints have the victory,
for every one that comes into the world being enlightened,
they which go from the light which they be enlightened withal they inwardly raven,
and you may see these were not those called heathens that got the sheep`'s clothing,
that went forth from the apostles which had been amongst them,
but they who did not continue, ravened from the life, had the sheep`'s clothing,
kept the outside, but made war against those that kept the life, that kept to the spirit,
the testimony of Jesus, and killed them; here began the apostacy;
amongst these has come up all this trash, when they ravened from the life,
and stood not in the counsel of God, but made ministers by their own wills,
and apostatized from the true cross, the power of God, and from the true church,
the pillar and ground of truth, and from the true apostles,
and set up a church with a cross on the end of it,
and these are they that have brought up all these pulpits, tithes, temples, schools,
colleges, and these are they that despise prophecy, and quench the spirit,
and limit the holy one, which sets them in confusion;
the order and practice of the church of the apostles is,
if any thing be revealed to one that sits by, let the first hold his peace,
for you may all speak one by one, that all may learn, and all may be comforted;
so from all these apostates and apostacy, the beast and the number of his names,
and his heads, and horns, and crowns, and his languages, and his crosses,
and his churches, pulpits, and his teachers made by the will of man,
is God bringing his people, and the Lamb and the saints have the victory;
glory forever to the highest;
and the everlasting gospel shall be preached to them that dwell upon the earth,
for all that dwell upon the earth have worshipped the beast,
and gone after them that inwardly ravened, that Christ said should come,
John saw were come, that went out from them,
and so all nations have been like a wilderness, that briars, and thorns,
and thistles may be gathered of them, and in this may every one see his fruits;
but who had their names written in the Lamb`'s book of life,
and kept the testimony of Jesus;
for all nations have drank of the cup of her fornications,
and this was that that made war with the saints, and overcame them;
but now the Lamb and the saints have got the victory
over that which Christ said should come,
and John saw was come, which all the world went after,
and now he is revealing the pure mystery;
now shall the saints and the holy prophets rejoice over her,
who are come to that which she went from,
now shall the holy tabernacle be witnessed with man;
now shall the holy city be witnessed, and the heavenly Jerusalem,
now cries the spirit come, and he that hears bids come, and the bride saith come,
for the Lamb and the saints have victory; and now is the marriage of the Lamb,
and to every one that thirsteth, he will give of the water of life freely.

So every one that comes into the world being enlightened, having a light from the Lamb,
being turned to the light,
that Christ Jesus the Lamb of God hath enlightened them withal,
and believing in the light which will let you see your sins,
with it you will see the Lamb of God which takes away sins, for all these tithes,
and pulpits, and temples, and priests, come up since the days of the apostles,
are amongst them that apostatized from them,
for the true apostles witnessed against the true temple which Solomon built,
and said their bodies were the temples of God,
and the apostles witnessed higher than the true priesthood,
whose lips were to preserve the people`'s knowledge, and offered for his own sins,
and the sins of the people, and witnessed the everlasting priesthood,
and the one offering, Christ the treasure of wisdom and knowledge,
which doth enlighten every man that comes into the world,
and the light that shined in their hearts, which came from him,
would give them the knowledge of the glory of God in the face of Christ Jesus,
and with that light they saw the glory which was with the Father before the world began,
from whom the light comes,
him by whom the world was made and the apostles brought them off the tithes,
and said the priesthood was changed, and the law was changed also,
and commandment disannulled which gave them tithes, Heb.
7. and Christ Jesus was come, the Son of God, the end of all similitudes and likenesses.
So as was said before, these priests, tithes, temples, pulpits,
were made by the will of man since the days of the apostles in the apostacy,
and these churches amongst whom are all these false names,
and several worships and opinions, and judgments, and having the sheep`'s clothing,
but every one as a wolf ravened from the life, and ready to devour one another,
so the form of godliness has been long amongst people,
but the life and power has been wanting, which they were in,
that gave forth the scriptures, in which people have unity,
from it they have been apostatized,
in which spirit the holy men gave forth the scriptures, which is the bond of peace,
in it is the unity, and the worship of the Father in the truth,
in that which the devil is out of, in which is no enmity,
and so all having been inwardly raveners that have been from the life within,
they have been wolves in sheep`'s clothing, ravening one after another,
to devour one another, and their fruits have been briars and thorns,
so profession of religion has been amongst people, but the life has been wanting,
into which life God is now bringing his people, to that which they all ravened from,
with which they shall see all the apostates in the apostacy,
and fathom over the heads of them all,
with which they shall come to see the rock Christ Jesus, the covenant of light, and life,
and peace.

So that which may be known of God is manifest within people,
which God hath showed unto them, that when they do the things that are not convenient,
not righteous or worthy of death, with that of God in them all they can tell,
and to that of God in them all they must come,
before they do hold the truth in the righteousness, or retain God in their knowledge,
or retain his covenant of light, in which is the peace with God, and one with another;
for the Jews they held truth, the prophets`', and Moses`'s and the saints`' words,
but their minds being reprobated from that which
might be known of God made manifest in them,
which God had showed unto them, they held it in the unrighteousness,
in the sin and enmity, so that was in that age; now the ages since,
people have held truth, Christ`'s words, the prophets`' words, apostles`' words,
but it has been in the unrighteousness, that is in the sin,
in the enmity in every one`'s mind,
and so there is the adversary and the wicked one amongst people,
professors and christians that have that name, and so they become synagogues of Satan,
in enmity one against another, giving one another names, gathering together in sects,
one against another, cages of unclean spirits, habitations of dragons,
yet truth held in the unrighteousness, in the enmity,
which makes them to slay one another about it;
and so there the devil puts men on to kill one another about religion,
wrestle against flesh and blood, while the power of darkness,
and spiritual wickedness rules, but those are no true christians,
no ministers of Christ that do so,
but they are all gone from that which may be known of God made manifest in them,
which God hath showed to them as the Jews were, outward Jews, not inward,
outward christians, not inward; for he is a true christian that hath Christ in him,
as he was a true Jew who was one inward, so to that which may be known of God,
manifest in them, must all people be brought, before they retain God in their knowledge,
from whence it comes, or retain his covenant Christ Jesus,
(the end of the prophets Abraham and David,) whom the apostles preached,
who was before the world was made, in which you come to have peace with God,
in whom truth must be held, and spoken as it is in Jesus,
and then it is held in righteousness, and spoken in peace,
the seed of God being brought forth, and the covenant of light and life witnessed,
the Lamb being risen which makes the powers of the earth to rage,
that be out of the fear of God, and Christ Jesus is come to reign, the same yesterday,
today, and forever, which makes all the ministers, teachers, prophets,
and antichrist to rage, that have been made by the will of man, and schools,
and colleges, that speak a divination of their own brain,
and not from the mouth of the Lord, and all ministers, teachers, prophets, pastors,
shepherds, guides, and leaders of the people, that have gotten Christ`'s,
the prophets`' and apostles`' words, and professors of them,
being found out of the life of the prophets, Christ and the apostles,
with the life of Christ, of the prophets and apostles are they all judged,
which makes them rage, which life is now made manifest, glory to the Highest forever.

And the Lord is come to teach his people himself by his spirit,
and to gather them from all the world`'s ways, and teachers, to himself,
and so all upon the earth which profess Christ`'s words, the prophets`' and apostles`',
and not in their life, they are raging against their life, which is now manifest,
and be raging against Christ, which is now manifest in his saints,
Christ the same today, yesterday, and forever, so the seed of God is risen,
glory to the highest forever, which seed is Christ in the male, and in the female,
whereby many males and females are come to confess Christ the seed,
in them who have the promise, and so are become heirs of the promise, heirs of God,
heirs of life, and heirs of the world that has no end,
and the rulers of the earth take counsel together against the Lord,
and against his anointed, and his babes as you may read, and as they may read,
that now are taking counsel against him, where the anointing is manifest,
such are they that slay him in the particular,
and are the builders that reject the corner-stone,
but the stone that is cut out of the mountains without hands,
shall dash the head of gold to pieces, and the breast of silver, and who have an ear,
they may hear: and the world is crying out for their honour,
and crying out for their bendings and bowings, and doffing their hats,
and cry Jacob bowed to Esau; it seems that Esau is lord among you yet, and not servant.
It is granted there was a time when Jacob bowed to Esau,
and there was a time that Pharaoh and his host was in the sea,
the family of Jacob rejoicing over them;
there was a time that the house of Esau must be as stubble,
and Jacob ride over the high places of the earth,
and Nebuchadnezzar brought down amongst the beasts to eat grass like an ox,
until he knew that the most high did rule in the kingdoms of men,
and the elder must serve the younger; he that hath an ear let him hear.
And as for the hat, it is honour amongst men, is honour below, and not honour from above;
while people are seeking for this honour below, they lose the honour which is from above,
which Christ commands to seek,
and questioned them that were there receiving honour one of another;
and seeking honour of men, how could they believe?
And said, moreover, I receive not honour of men, I which am the light of the world,
by whom the world was made, which enlightens every man that comes into the world,
and he does not come amongst the sons of Adam (drove from God) to receive their honour,
but to spoil it, deface it, stain their pride, deface their honour, mar their glory,
stain their beauty;
so the light (which every man that comes into the world
is enlightened withal) will not receive the honour below,
but will condemn him that receives it,
and that is it which brings to seek honour from above,
and stains the glory that is below;
so the first Adam in the transgression receives honour of the earth,
but the second Adam receives it not, nor will the light in them receive it,
which comes from the second Adam,
so I have a witness in all men`'s consciences upon the earth,
that will not receive honour of men below, but of God, and that comes from above.

And the teachers of the world, and ministers, and pastors, and doctors,
and shepherds have told us that the Hebrew and Greek was the original,
and they were the orthodox ministers to open the scriptures to us,
and they had the original,
when as Moses said that all the earth was of one language before Babel,
and Nimrod the mighty hunter, whose stock was of Ham,
whom God did confound into the many languages,
he was the beginner of the building of Babel; and Moses said,
like unto me will God raise up a prophet, him shall you hear,
and when this prophet was come, Christ Jesus, they crucified him,
and when they crucified him, they wrote a superscription over him in letters of Hebrew,
Greek and Latin; now here stands the world`'s original over Christ,
over the life when they crucified him; the beginning of these many languages was Babel;
and Pilate he could not open the scriptures with Hebrew, Greek and Latin,
but crucified Christ who is the substance of the scriptures, and when he had done,
he set his languages over him; and said John in the Revelations,
they must be redeemed out of every tongue or language,
which they have told us was the original,
that which was set over Christ when he was crucified, over the life;
but now the life is risen, Christ is risen, who had the languages set a-top of him,
Christ is risen that fathoms Babel and Babylon, before Babel or Babylon was,
who had the many languages, which is the world`'s original,
so the life is risen a-top of it, which they set a-top of him,
and over them that say it is original, and that they must open the scriptures with it,
with which they run all into confusion, Babylon,
so betwixt Babel and Babylon they may walk and see by plain
scriptures how the languages were set over Christ;
and Pilate could not open the scriptures with them,
nor can they now open the scriptures with their many languages, but break into heaps,
heads and parties, for if they could open them, they would satisfy one another,
and come all into one, for that which gave them forth is one, which must open them again;
so all people, teachers and professors, be all upon heaps,
in confusion about the words of the scriptures, saying that is the original,
and they are stopped at Babel, for all the earth was of one language before,
and the call is out of many languages, out of Babylon, Babylon is the end of them,
and the life is risen that stains their pride, defaceth their glory,
and mars their beauty, for they have a pride, a glory, a beauty in their languages,
which they call the original,
(the naturals,) and the light lets see before Babel or Babylon was, or Pilate either,
into the beginning, the covenant of light with God,
and when that people did imagine to build Babel, they went out of the life,
whom God confounded into many languages, that they might be scattered,
and God scattered them, as he will all other gatherings,
that are gathered with imaginations, of him, and are the builders,
that go from the life of God within them, and so from God,
and they that crucified Christ, they were from the life,
and they set the languages above Christ which was the life,
and they that were in Babylon, were of them that ravened from the spirit of God in them,
and went from the apostles`' doctrine into the many languages,
which the redemption is from, and so they cannot endure to hear talk of the life,
and the spirit of God within, and the light; and these are they that set up languages:
but now the life is risen (above the languages) which gathers
to God and lets see before Babel or Babylon was,
or Pilate either: and exalted Babel shall fall, and become a habitation of devils;
but over all the life is risen,
that gives to see to the beginning before the world was made,
which brings to peace with God, which opens the words of Christ, the prophets,
and apostles,
and gives to every one his particular satisfaction concerning the words of the prophets,
of Christ, of the apostles, in which life and peace with God is known,
which judgeth all them that have the words, and be out of the life.
