== The Serious People`'s Reasoning and Speech, with the World`'s Teachers and Professors

The world`'s teachers and professors say, "`The Quakers are fools,
because they will not wear ribbons; and idiots, and novices,
because they will not wear feathers in their caps, and great scarfs a-top of their hats,
and to hang over their hat-brims and shoulders, and their backs,
therefore are they like fools, idiots, and nobody.`"

"`Ay, but,`" says the serious people to these professors and teachers of the world,
"`you are more like novices, idiots, and fools,
with your scarfs a-top of the crown of your hats,
hanging over their brims upon your backs;
and your hearers and people with feathers in their caps,
which are no where like christians,
but are more like the idiots and the fools and novices, who have lost your sincerity,
whose minds are taken up with these foolish things, which destroy your seriousness,
and so you are not like the saints, you professors, and teachers, and people,
but are like the heathen in your gorgeous apparel.`"

The priests, and professors, and the world`'s table-talk, is,
"`The Quakers will not wear gold lace, will not wear ribbons in their hats,
nor at their knees, nor about their waists, nor a bunch of ribbons before them,
nor ribbons at their gloves, nor broad tassels upon their shoes,
nor ribbons at their hands, nor a bunch of ribbons at their backs, as big as one`'s fist,
as our women and members of our churches do, and a bunch of ribbons at their bosoms,
and down their bosoms, and three or four gold laces upon their coats, and petticoats,
and the Quakers, like a company of fools and novices, cry against us,
and say we are all daubed about and dressed with pride: how must the poor live,
if we must not wear their lace?
And gold and silver, and ribbons on our backs?`"

"`Ay, but,`" saith the serious people,
"`are not thou burdened with all this garb upon thy back, and this vanity?
And doest not thou spend much time in decking thyself?
And doest not thou see thyself ill-favoured with all these ribbons,
tashling about thy hands, and flapping upon thy hat,
and great bunches as big as a hand flapping at the backs of women like a besom,
and thy great things a-top of thy shoes staring;
and if you say how should the poor live if you do not wear that;
give them all that money which you bestow upon all that gorgeous attire,
and needless things, to nourish them, that they may live without making vanities,
and needless things, and costly attire for you, and through that you will live,
and they will live both; giving the poor all that which you lay out in needless toys,
and ribbons; and then you shall not be like fools, and fiddlers,
and the dancing light women,
with all their bunches of ribbons and toys about them,`" saith the serious people.

"`But,`" saith the world`'s teachers and professors;
"`these Quakers are good for nothing but to cross people, and cross us.`"

Answer.--`" Your minds that live in vanities and ribbons,
and delight in such fooleries you are so peevish, and so fretful, and so pettish,
if the bunch of ribbons be not right, as you would have them upon your backs,
and hang right upon your breasts, and your laces set right upon your coats and gloves,
and your dressing and ribbons right upon your heads, that through your peevishness,
and brittleness of your minds, that live in these earthly things, neither your men,
nor your maids, can tell how to please you,
nor your tailors to shape your garments right for you;
and so that which the Quakers cross, is but your earthly minds,
that live in these earthly toys, and so they are more your friends than you are aware of,
saith the serious people; and we know you,
for abundance of you are gotten up lately with your ribbons on your backs, and knees,
and your feathers in your hats, and your bunches of ribbons about your waists,
and dabbling of your gloves, and putting on gold and silver,
which is contrary to the apostles`' doctrine:
for we have known the time when many of you did not wear such things,
which you have lately got up, and put on, more like fools than serious people,
who are out of the apostles`' doctrine;
who saith it is not the wearing of gold nor costly apparel; and so, through your vanity,
you have lost sincerity, and gone from the apostles`' doctrine,
and so are turned into the lusts of the eye, pride of life, and lusts of the flesh.`"

"`Away with you,`" say the professors and teachers of the world,
"`you are a company of madmen, you are not fit to live upon the earth.`"

"`Ay, but,`" say the serious people, "`you are the madmen that destroy the creation,
and the creatures of God upon your lusts, and the lusts of your eye,
the lusts of the flesh, and the pride of life, which is not of the Father,
but of the world, by which you destroy the Father`'s works,
and the prime of the creatures, which were given forth to be used by the wisdom,
by which they were created to the glory of the Creator.`"

Priests, and professors, and teachers, say they; "`You are not fit to be talked to,
you would have all to be fools like yourselves, we have freedom to plait our hair,
and hang it about with ribbons, and lay it over our brows, this is our liberty,
and to set spots on our faces of half-moons, and a coach and horses,
and curl and powder our hair, and tie it up with ribbons and jewels.`"

"`Ay, but,`" say the serious people, "`this is not like the christians`' fashions,
nor the apostles`' doctrine, which saith, it is not the plaiting of the hair,
and putting on of gold; nor like Christ`'s doctrine, who saith,
they should not take thought what to eat and to drink, nor what to put on,
for the Gentiles did so: but you are taking thought for your gold lace, and ribbons,
and changeable suits, and cannot tell what to eat, nor what to drink, nor what to put on:
you are more like the fools, and the heathen, say the serious people, than christians;
and you tie up your hair, and your children`'s hair,
as the ostlers tie up the horse`'s tails, and manes, and hang ribbons at their ears,
as you do, so do the grooms and ostlers in the wild horses and mares`' heads,
as you do your men and women, and so are a people that have forgotten God,
and all sincerity;
and so you are a people that more pleasure in the creatures than in the Creator.
And as for your patches and half-moons, and horses and coaches on your faces,
you are more like fools,
and Jezebel`'s stock (who betrayed the just) that painted harlot,
and so the just have you betrayed in yourselves,
and have vexed and grieved the good spirit of God in you, by your vanity,
one vanity after another, so you are more like Jezebel, than christians;
what a crinkling is here with your feet,
and a mincing how suit you with such as the prophets cried against,
who shall be covered with ashes, and, instead of a sweet smell, a stink?`"

The priests, and professors of the world say, "`These fools, the Quakers,
cannot endure to see us with two or three rings on our fingers, nor jewels in our ears,
nor bracelets about our necks, nor cuffs, nor double cuffs,
nor great tashling band-strings,
they cannot endure we should wear a laced cap of twenty shillings price, or less,
or more, and a pair of double cuffs up our hands, and double white boot-hose-tops,
these novice Quakers cannot endure to see us with this garb upon our backs.
And how should poor people live if we should not wear them?`"

Say the serious people, "`All your gold rings, your cuffs, your great band-strings,
your lace, your jewels, your bracelets, your gorgeous apparel, and attire,
turn it all into money, and give it to the poor to buy them bread,
and I will warrant you, that they and you will have all enough,
and there will be no want amongst you, for you are always wanting rings, or ribbons,
gold hat-bands, laces, or bracelets, you are always wanting one thing or another;
if you see another fashion, the other is old; and you want to get into it,
and you envy others that are gotten into the fashion before you.
And here is the devil the king of pride, that murderer,
that leads people to consume and destroy the creatures upon their lusts,
for his lusts they do; and so you are more like fools, that are slaves to the devil,
who is out of the truth, that leads you to destroy the works, and creatures,
and creation of God, and all your want is of God, for you want God,
and his wisdom to order you.`"

The teachers and professors of the world say, "`The Quakers are offended at us,
because our women have a dressing come down to the middle of their backs,
and a great pair of cuffs upon their hands,
and how must the poor people live if they should not do so?`"

"`The makers of these things,`" say the serious people, "`let them make plain things,
and do you wear plain things, and that money which you lay out on these costly things,
give you to them; for who are you like in the scriptures?
You are not like the christians,
for what service is there in your wearing a bunch of ribbons at your women`'s back?
Do they scare flies away?
And at their breasts, tashling at their arms,
and a great company of ribbons tashling at their hands and their heads,
do you wear them to scare flies from your hands?
why do you wear that great bunch before?
What is the service of it, that you are thus dressed?
Are you dressed for a sight, and a show, that people should wonder and stare at you?
Or are you dressed according to the scripture, and the apostles`' doctrine, and commands?
Give some example for your fruits among the saints; saith the serious people,
we have seen Bedlam-people, and madmen hang ribbons in their caps,
and at their horn`'s ends, and mad people hung about with clouts;
so you are more like fools, and mad people, than the Quakers;
and it is a wonder that you professors, and teachers,
and people should be so offended at the Quakers, for they see no people outstrip you,
except it be the mountebanks, and stage-players, and French lackies;
therefore it is time for you to lay away your ribbons, and your gold, and your rings,
and your bracelets, and your lace, and your gold and your silver lace,
and your bunch of ribbons, and all your superfluity, and turn it into money,
and give it to the poor tradesmen that make these things;
so that they may not labour to serve your lusts, and wills,
to consume it upon your lusts, and that shall bring more honour to God,
in giving that which you waste on superfluity to the poor
tradesmen that works for your consuming wills and lusts.
Therefore, consider, saith the serious people,
for God will destroy the world that lies in pride and wickedness,
which the devil is the prince of, and that shall come to an end,
and it must be destroyed by the word, and the glory of the world will fade away,
but the glory of the Lord will not, nor his word, which lives, abides, and remains,
and endures forever.
Therefore consider, all you children of pride, amongst whom the devil is,
who is your king and ruler, who is called the king of pride, who are always in want,
for the murderer and devourer causes you to waste the creation of God, and destroy it,
and so your want is for want of God, and his wisdom.
The Lord God of power, and of heaven and earth, who will rule you with his hammer,
with his sword, with his word, which is a fire for all children of pride;
and the hammer is beating, and the sword is going, and the fire is kindling,
which will make all the proud to rage with a burning fire.`"
"`Hark!`" cries the priest, and professors, and teachers of the world,
"`we cannot get a Quaker to the ale-house, nor tavern, nor to feast with us,
nor to dance with us, nor to hear our fiddlers,
nor music (a company of precise people) there is none knows how to have them.`"

"`Say you so?`"
saith the serious people, "`that is, because they will not to the taverns with you,
and have the fiddlers, and pipes, and pots, and your banquetting, and feasting,
and your hooting more like madmen out of your wits, than men that fear God,
who thus destroy the creation upon your lusts.
The Quakers are come into the wisdom of God, by which all things were created,
so that if they eat, and drink, it must be to the praise and glory of God;
being in his fear,
so they cannot have fellowship with the destroyers and marrers of the workmanship of God,
and the creation.`"

The priests, and professors, and teachers of the world, say,
"`The Quakers will not doff their hats, nor scrape a leg, nor make a courtesy,
(a company of clowns.)`"

Saith the serious people, "`Where do you read in the scripture,
that the apostles taught any one that they should scrape a leg and make a courtesy,
or put off their hats, for great men will stand with their hats on one to another,
and sometimes they will bow and stir them, but they will seldom bow to the poor,
or scrape a leg to a beggar; so if he hath got a feather in his hat,
and a few ribbons on his breeches, and hair powdered,
and if she hath gotten a bunch of ribbons on her back, then there is, your servant,
madam, your servant, sir, your humble servant, Mr. then scrape, and courtesy,
and doff the hat, and you sir, and this pleaseth proud flesh,
but to say '`thou friend,`' makes him or her mad, which is a proper loving word,
and scripture order and practice, and a sound word, that cannot be condemned.
Therefore such proud ones, that bow not unto poor people,
and scrape not unto poor people, and thou`'s them, and not you them,
and yet they must be courtesied to, and scraped to, and capped to,
because they have some more of the earth and proud apparel,
and their poor brethren must not be scraped, nor bowed unto;
is not here respecting persons?
And so are judged by the law of liberty.

"`And as for your saying it is your liberty to wear cuffs, rings, beads, jewels,
powder your hair, gold and silver lace, bunches of ribbons at your backs,
great scarfs about your hats, feathers and ribbons, great things a-top of your shoes;
children`'s hair tied up, (like horse-manes with ribbons,) like horse-tails,
lusty great lasses and women, full of paint and patches of horses,
and half-moons upon their faces; this is our liberty,
say the professors and teachers of the world, and all is ours,
and it is the saints`' liberty; nay, this is the liberty of the flesh,
and the king of pride`'s kingdom, in his dominion in the earth; destroying the creatures,
and devouring the creatures,
and this liberty is your own bondage who are servants of corruption,
and this liberty will be your burden, and your vanity will fly you in the end,
though you will not fly it in your life time, and will stand you in no stead,
who will be found as Dives, that rich glutton, that fared sumptuously every day,
and the poor beggar hath a greater share in the kingdom, with Abraham, Isaac and Jacob,
than you; and sits in his bosom in that kingdom, when the other is in the lake.
Therefore, you that live wantonly upon earth, you kill the just,
and the devil is your king, (who is unjust,) and your law-giver,
who teacheth you to destroy and devour, and to consume,
and you that live in pleasures on the earth, are dead while you live,
and have denied the faith, and are turned wanton, that eat and drink,
and rise up to play, and go to dancing,
and are like the children of Israel that danced before the calf,
and like unto Herodias`'s daughter, that danced to please that glutton and gorgeous man,
who was reproved, who took off the head of John Baptist that reproved him,
to satisfy the lust of the dance;
and there is the end of those that live wantonly upon earth, that kill the just,
that are sporting themselves, and living in pleasures in the daytime;
such are gone out from the power of God, and are as the heathen, and not as the saints,
who were redeemed out of the earth, and its vanities and pleasures,
to know the election before the world began.

The priests and professors of the world say, "`The Quakers, those fools,
cannot endure our puppet-plays, nor our stage-plays, nor our May-games,
nor our shovel-boards, nor our tables nor dice, nor our sports nor shows,
nor that we should make pictures of things in heaven, and things in earth,
nor our little babies that we sell, nor our images, these fools, the Quakers,
cannot endure these things.`"
"`Are you not ashamed,`" saith the serious people, "`for shame, hold your tongues,
do you call yourselves teachers, and professors, and christians,
and name the name of Christ, and profess the apostles`' words?
Why, it is our recreation, say they.
Recreation?
Away, away, the recreation is in the law of God, the delight is there day and night,
and the exercise is there, and the glorying is in the cross of Christ,
that crucifies to the world.
Are not you ashamed to talk of fiddlers, mountebanks, and stage-players, and images,
and pictures, and shows, and your shovel-boards, and plays, and games, and dice?
Away, for shame, hold your tongues, for they are works of the flesh, and works of vanity,
and delights of fools, that live in their pleasures and lusts of the world,
who are enemies to the cross of Christ, that crucifies to the world,
and which is the saints`' glory, who glory in the Creator;
but those that follow their pleasures, glory in the creature more than in the Creator;
who are swearing almost at every word, and cursing at every word,
that there is such nasty streets, with such nasty unsavoury words,
and such cursing and swearing, that it is even a shame and loathsome to speak of,
a den of dragons, like as hell were broke open; and this is your noise in your streets,
taverns, and ale-houses.`"

Ha, ha, cry the professors and teachers of the world, "`What do the Quakers do?
They bid you mind the light of Christ within you.`"

Ay, saith the serious people, "`If you did mind the light within you,
it would never let you swear, nor curse, nor follow pleasures,
nor follow the fashions of the world, nor the vanities, nor the fooleries, nor images,
nor let you destroy the creation on your lusts, and creatures,
and so many in the nation to starve for want of food,
it would bring you to put off your gorgeous apparel, gold and silver, and rings,
and ribbons: but the light would lead you to Christ, the wisdom of God,
from whence it comes, and that would lead you to order the creatures to the glory of God,
the creator of them, which checks you, and reproves you,
and brings you out of Dives`'s state, to poor Lazarus`'s kingdom; but if you hate it,
it will be your condemnation.
And to you that is the word of the Lord God; for when men are lifted up in pride,
they shall not come nigh them without scraping and bowing the hat four or five times;
and this is the honour below to fools, which is like snow in summer, and rain in harvest,
unseasonable.
Two men and two women of the world meet the one the other,
and being much offended the one at the other; '`For,`' saith the one,
'`I bowed three times to him, and he scarce bowed once to me, and scarce stirred his hat,
he is not so civil and so courteous as he was wont to be; I wonder what is the matter.`"
I courtesied three times, the first almost to the ground, and she scarce bowed to me,
she made but half a courtesy, which is not as she used to be,
for she used to be more courteous.`'`"

"`Why how now,`" saith the serious people,
"`you were finding fault with the Quakers before?
who now cannot please one another with your courtesies, and scrapes, and your hats;
some do too little, some too much; for I saw one of the world,
a great professor and a teacher, and he came to another that had been a teacher,
and they bowed one to the other till they out-bowed one another,
and this the one said to the other, away with these compliments.
So much of your time is spent, saith the serious people, in capping one to the other,
and courtesying, and thinking what you shall eat, and what you shall drink,
and your compliments and fashions.
And this takes you off the service of God; and the civility which is in the truth,
that is out of all that; for true civility stands in truth and love, that envies not,
but the love of the world will envy,
and be envious at others that will not give them their fashion, their compliment,
their courtesy, their cap, and their scrape, which they call civility,
and that is not civility which will envy; for civility stands out of envy,
in truth and love, that envies not.`"

Priests and professors of the world say they,
"`These clownish Quakers will not drink to one, neither say good-morrow, or good-evening,
but say thou to every one; let him be great or small, they will thou him,
a company of clowns, and ill-bred people, they are not fit to dwell upon the earth.`"

"`How now?`"
saith the serious people, "`why do you say so?
why do you thus rage?
For it is a temptation in drinking one to another,
it is more civility to set down the cup,
let every one take the creatures in their service, and drink as he needs,
they stand to serve, and not to tempt one another to drink more than doth him good.`"

"`Ay, ay,
we thought ye would destroy all good fellowship,`"
cry the teachers and professors of the world.

"`Nay,`" cry the serious people, "`the good fellowship is in the spirit,
which gives an understanding and a good wisdom, that is pure and gentle, from above;
with that to order the creatures to the glory of the Creator, and the morning is good,
and the evening is good, for all things that God made were good; but bad people say,
the morning is bad, and the evening is bad, when it doth not please them:
and so to such we tell them that it is a good morning, and a good evening,
which they call bad; and them that do not know all things that God made to be good,
we tell them that they are; and them that say the morning and evening is bad,
we tell them it is good, but the night of darkness is bad,
where all the works of darkness are done.
And the morning of judgment is good, but he will think it is bad,
that his works and he must be tried by fire which cannot be quenched.
And those are the clowns that do not know the morning good, and the evening good,
but must be saying the words to one another all their lifetime.
And they that say thou to a particular, are not clowns,
for it is sound scripture language; David was not a clown, nor the prophets, nor Christ,
nor the apostles, that thou`'d particulars, and you`'d many;
but those be clowns that be out of the sound speech;
and surely these teachers and professors might have known ere now,
and have taught the world singular and plural numbers,
and have learned their accidence and their grammar ere now,
and not have called them clowns that come into the practice of the singular and plural;
a clown is untaught, and one that hath learned, and doth not practise.`"

G+++.+++ F.
