== The Diffference between the World`'s Relation,

Which stands in Strife, Malice, and Wickedness, and the Saints`' Relation,
which stands in Love, Life, Peace and Joy in the Holy Ghost.--By G. F.

The relation which stands in destroying, is by the children of the light denied,
all such who live out of light, and out of it walk, who wear the old garment,
whose mind is corrupt, and have a wisdom, but with it know not God, and have a knowledge,
and with it corrupt themselves, and have a humility, but feigned, and have a worship,
but in the will, and have a righteousness, but in the self, and speak the high words,
but it is in hypocrisy, and have a liberty, but in the flesh,
where the spirit is in prison, who in Cain`'s way are gone,
and have not a habitation in God, whose affections are below in the earth,
and serve the lusts and the pleasures, whose conversation is among the wicked,
and there is the world`'s relation where lodgeth the strife, and the debate and deceit,
and disdain, and setting up that which God will throw down; now while this is standing,
which is contrary to the light, they that in the light do walk, and be in it,
these they deny, and see that which leads nature out of its course,
and what sets the whole course of nature on fire;
and there the whole world are in confusion, and all the tongues are unbridled,
where power over them is not, while that reigns which leads nature out of course,
his religion is vain, and that relation stands out of truth;
but all such as to the light are turned,
see with the light (and that doth manifest what leadeth
nature out of course,) the marriage that is honourable,
and what sets the whole course of nature on fire, and what leads nature into course,
where the pure relation and the entrance of it is received,
where the self and its righteousness is denied, and the righteousness of Christ received;
where the worship of the will is denied,
and the worship of God in spirit and truth received; where self-righteousness is denied,
and Christ the righteousness of God received, and the former conversation put off,
and the conversation in heaven witnessed, the affections below changed,
and the affections which are above come to.

Here is the pure religion known without guile, who are out of Cain`'s way,
where the habitation in God is witnessed and seen, where the just live by his faith,
and honour in the Lord known, and the true humility learned of Christ,
who is not of the world, though it by him was made,
who lighteth every man that cometh into the world, who is man`'s way out of it;
which light is man`'s condemnation, if he doth not believe in it;
and the relation which is in the world (who hate the light) is in the lust,
where the perverseness is in the love of the world, where the envy is,
where the invention is, selfishness, crossness, perverseness, backbiting, maliciousness,
filling with unrighteousness, yet they have a love, yet they have a relation.
Now the light which comes from the beloved Son of God, where the love of God is received,
the world`'s relation is denied, for the relation of the world destroys and devours,
but the children of the light, which be in the relation out of the world, live in peace,
unity, and fellowship, and comfort enjoyed in the Holy Ghost;
so all you that profess relation in words,
and envy lodgeth in your hearts against one another,
and yet flatter one another to your faces, and backbite one another behind the back,
such relations we deny, and have a witness in your consciences against it.

And all that profess a relation one to another, and love and friendship with the tongue,
and in heart deceive one another, and cozen and cheat one another, and lie,
and dissemble one with another, all such relations we deny,
and have a witness in your conscience against it: and such as profess religion,
or worship, or humility, righteousness, and the scripture,
Christ and the prophets`' words, and live out of their life, and live in envy and malice,
and yet profess you have a relation to Christ, and God, whom you have not seen,
and you love him, and do not love them whom you have seen, such relations we do deny;
and all such as cry up your experiences, high notions, manifestations, as you call them,
dispensations as you call them, and live in pride, strife, and envy, debates, derision,
scorns, loftiness, high-mindedness, you be out of the light, and out of the way,
in corners, and out of the pure relation,
we have a witness in your conscience against those things,
which lets you see what you possess,
and will let you profess no more if to it you hearken,
which turns from the world and the relations therein, for all who believe not the light,
and are not to it come, have a love, but it is in the world, and a relation,
but it is in the world, which is enmity to God, so that relation which is enmity,
is denied with the light, that love which is enmity, is denied with the light,
which leads to the pure relation, which envies not,
where the destroyer and devourer is rebuked.

G+++.+++ F.

The faith of such is no better than the faith of the pharisees,
who only believe of a Christ, because the scriptures declare of him,
but the faith of them who dwell in the life and power of God,
and follow the Lamb wheresoever he goes, is that faith which overcomes the world.

To believe only of a Christ because the scriptures declare of him,
is to believe as the pharisees did believe,
who were the persecutors and murderers of the just, but to believe in the light,
the life that gave forth the scriptures is seen, and Christ is believed in,
and here he hath the witness in himself, and comes to be a child of light,
and born of God, which birth overcomes the world; and now, saith Christ,
they hate the light, because their deeds are evil, and will not bring their deeds to it,
because the light will reprove them, and this is the condemnation, the light,
saith Christ; and now it doth appear who hate the light, priests, teachers, people,
young and old hate the light, and will not bring their deeds to the light,
because the light will reprove them;
neither will they suffer others that walk in the light, and love the light,
and bring their deeds to the light, and show their deeds with the light,
and reprove them with the light, because they hate the light, and them that walk in it,
and cast them into prison, and so are stumbling at the light all sorts of people, +++[+++mark,]
it is the light that they hate, saith Christ,
they hate the light which reproves their evil deeds.

And this light is that which the world,
and the teachers thereof cannot endure to be talked of, but hate it,
and them that walk in it, and it is the light that is so much stumbled at,
because their deeds are evil, and they walk in darkness, there is a proof;
for they that walk in the light stumble not, but come to receive the light of life,
here Christ`'s words are fulfilled amongst them that hate the light,
and will not bring their deeds to the light, because the light will reprove them,
for that which doth make manifest is light,
so that which makes manifest they cannot endure, but would be in the dark,
and keep their deeds in the dark as it is manifest; and saith Christ,
the devil shall cast some of you into prison, he is out of the light, out of the truth,
and a liar, and a murderer from the beginning, which now is seen with the light,
and trampled upon, and all that own not the light which cometh from the word,
are the wicked seeds-men, sowing abroad for tares, there lies, the evil reports,
and they that are gone from the light, that comes from the word of truth,
are given up to believe lies and reports, and may cry up darkness, if you hate the light,
what have you to cry up else, if you turn from the light, pitiful preaching,
which hates the light, which manifesteth all the works of darkness.

G+++.+++ F.
