== To the People of Uxbridge.

Friends,--Your conditions is grieved and lamented over, your want of the life of God,
and barrenness of his power amongst you, whose lean souls are seen, whose barrenness,
and barren womb appears, who little thirsts after the living God, whose wildness,
wantonness, and negligence of the everlasting salvation appears; yet full,
like Sodom and Gomorrah, being full of that which is wicked and profane;
the streets of your town will manifest it.
O, people, where is your salvation, and what assurance have you of that,
and of your eternal inheritance, where nothing that doth defile enters?
O, are ye come to examine and see whether Christ be in you, or no, that wickedness,
profaneness, unrighteousness, ungodliness, filthiness might go out of you?
For if Christ be found within you, the strong man goes out that has kept the house,
and defiled the heart, and the body, and the mind, and that prisoned the soul;
if Christ be felt within, there is the soul`'s bishop.
O, people, I am grieved with your abominations, and, filthiness, and unsavouriness,
and untowardness, and your unsubjected state to the life and power of God;
if you do not repent,
and that your minds be not changed to serve the living God in spirit,
which mortifies sin and corruption, the earth will vomit you out, who have cumbered it,
and destroyed the creatures of God on your filthy ungodly lusts,
and that you have served and pleasured.
O, I am weary of mine adversaries, saith the Lord, I am weary of your abominations,
ye have loaded the just, and pressed it as a cart with sheaves,
your hearts are gross and fat; with your tongues you have talked of God,
but your hearts have been far off, after your own ends: your younger children,
boys and people, are full of lightness, wildness, folly, and vanity, and envy,
and mocking, scorn and derision,
(which is not a good savour in your streets,) stubbornness, and untowardness,
and profaneness, and wildness, more like Esau`'s and Ishmael`'s stock,
than Isaac`'s and Jacob`'s; your old men are not sober, nor solid, nor grave,
and so they are not good patterns to the younger:
so ye are all more like heathens than christians, empty of the good,
full of the forgetfulness of God, and out of his fear, as though there was no God,
as though ye had never heard talk of God, nor scripture, nor Christ;
but this saying is fulfilled, the teachers have not profited the people at all.
Jer. 23. But like people, like priest.
But what a teacher is he that must serve this people?
Who must be the prophet, or the priest, that must fit such a people?
Surely he must be such a one as teaches for filthy lucre, and bears rules by his means,
that will divine for money, that will preach peace to them,
while they put into his mouth, such as mind earthly things,
who serves not the Lord Jesus Christ, but their own bellies,
that has such fruits in the streets: but such as seek for their gain from their quarter,
and the price, never lead people to the Lord, but lead them into the earth,
and to be like themselves, and they live like beasts and swine, as you may read.
Jer. 5. Mic.
3+++.+++ Ezek.
34. Esai.
56. Ter.
23. Rom.
13. Matt.
23. whose fruits declare it.

And away with the profession of God with your lips, while your hearts are afar off;
and away with your making a trade of the scriptures,
Christ`'s and the prophets`' and the apostles`' words,
for which many suffered death in giving them forth; and away with your lukewarmness,
and away with your carnal formality, and away with your doctrines and traditions of men,
which perish in the using of them; and away with your singing of David`'s quakings,
and tremblings, and fastings in metre, and come to sing in the spirit;
and away with your hour-glass-preaching, and hypocritical praying,
and your old mass-house-worship, which is called steeple-house or church,
and come to the church in God.
I Thes.
1. and to worship God in spirit,
John 4. and the Lord is come to teach his people himself, by his spirit,
and to bring them off from all the world`'s teachers, and churches, and ways, to Christ,
the way to himself, and he doth enlighten every one that cometh into the world,
that all through the light might believe; and every one believing in the light,
which hath enlightened them, they shall become the children of the light;
but they that hate the light that doth enlighten them, they hate Christ,
and that condemns them:
and that is the light that lets the drunkard see he should not be drunk,
and the curser that he should not curse, nor swear, and the thief,
that he should not steal, and that the cozener should not cozen, nor cheat, nor wrong,
nor defraud; and lets the profane see he should not profane;
and lets the envious man see he should not envy, nor fight, nor quarrel, nor lie,
nor commit adultery; that is the light which discovers that:
not to look after a woman to lust after her, that is the light that saith so,
and if ye love the light, it will let you see all your evil thoughts, words, and actions,
which be wrought out of God, and turn you from them; and coming into the light,
your works will be wrought in God, and your words will be from him, and so good,
that is in every one of your bosoms that will judge you,
and condemn you acting contrary to it, and reprove you; but if you consider it,
and hearken to it, it will turn your minds to the Lord God; and if you hate it,
it will be your condemnation.
Therefore, now while you have time, consider and prize it,
for this is the day of your visitation, and salvation proffered to you:
and with the light which you see your sin,
which Christ Jesus hath enlightened you withal, with the same you may see your salvation,
Christ Jesus, from whence it comes, to save you from your sin.
And people, that which may be known of God is made manifest within you,
which God hath showed unto you, that when you do the thing which is not convenient,
not righteous, but worthy of death, by that of God in you ye can tell;
and while your minds are reprobate from that, ye are all strangers from the life of God,
and the covenant of promise.
And friends, the light you must feel in your own hearts,
to give you the light of the knowledge of the glory of God in the face of Christ, 2 Cor.
4. and all the children of the Lord, shall be taught of the Lord, Isa.
54. and ye must come to know the anointing in you, to teach you,
1 John 2. and the kingdom of heaven ye must know within you,
Luke 17. and that is it which never consents to sin.
And ye must come to know the new covenant, the law in your minds, and in your hearts,
by which ye need not say to one another, know the Lord,
but that all might come to know him, from the greatest to the least,
that witness the law of God put and written in your minds and hearts,
that you may come to witness the Lord is your God, and ye his people.
Repent, lest you come to say you had time, when it is passed;
so from a lover of your souls, and your eternal good.

G+++.+++ F.

[.asterism]
'''

Come, away with your self-righteousness, and your feigned humility,
and your will-worship, and your carnal security, and take heed of drunkenness,
and filthiness, and profaneness, and scoffing, mocking, scorning, and derision,
for such who live in such things, and act such things,
shall not inherit the kingdom of God; and away with that you call your sacraments,
and your sprinkling infants, and come to Christ the substance, and come to the spirit,
that you may be baptized into one body,
that you may come to possess the things the scriptures speak of.

The very mist of the air is among you, and so are so light, and vain,
which are the prince of the air`'s fruits,
and the priest`'s who has long preached for his mouth; but if ye put not into his mouth,
see if he turn not against you, and you shall not keep him long;
so look unto Christ Jesus to teach you, who said, learn of me,
who is the way to the Father, who hath enlightened you,
that with the light you may see him, who is the bread to feed upon; but if you hate it,
then you feed upon husks.

This is to be read among the people of Uxbridge.
