== A Word in Behalf of the King,





That he may see who they are that honour all Men, and love the Brotherhood, that fear God, and honour the King; according as it is written in the Scriptures of Truth.
1+++.+++ Pet.
2. 17.--By G. F.

Let all people consider what they do, and what they say, and practise;
who say they are christians (and go under that name) and bring Peter`'s words, 1 Pet. 2:17.
Honour all men, etc.
+++[+++Mark,]
that is a large word, for if they honoured all men, then they would not hurt any man,
but love all men, and have all men in esteem; and if they esteemed a man,
they would never hurt him; and if they esteemed all men, and honoured them,
then they would hurt no man.
So if they did but practise that which they say, here would be no strife in Christendom;
nor would there be strife with any men, nor hatred of any man, nor violence,
nor striking any man, for he honoured him, and had him in esteem,
and he that honoured him, loved him.

Now he that doth not honour all men, nor doth not love all men,
nor hath not all men in esteem, (though he may say these words of the apostle,
yet he is out of the doctrine of the apostle, and practice) he is in the nature of a Jew,
or a heathen, that hates, and dishonours, slanders, backbites, and envies,
and doth violence to men, doth not honour them, nor hath them not in esteem,
nor doth not love them.
So look what derision, scorn, maliciousness, and what envy men live in,
abusing one another, and wronging one another, yet would not these be called christians?
Do these honour all men?
Do these love all men, even their enemies?
Have these all men in esteem, that will strike, and fight, and shed men`'s blood?
Are these such as keep Christ`'s commands, who saith,
"`Thou shalt love the Lord thy God with all thy heart, with all thy mind,
with all thy soul, and with all thy strength,
and thou shalt love thy neighbour as thyself.`" Luke 10:27.
And again he saith,
"`All things whatsoever ye would that men should do unto you, do ye the same unto them,
for that is the law and the prophets.`" Luke 6:31.
Now he that loves his neighbour as himself, he will not hurt him;
and he that wrongeth or deceiveth his neighbour, or striketh, or abuseth,
or sheds another man`'s blood, he would not have the same done unto himself by another,
and so such an one is out of Christ`'s doctrine,
and a transgressor of the law and the prophets: but now it is not so,
that many have clothes in esteem, and riches in esteem,
and so admire men`'s persons because of advantage,
and so become respecters of men`'s persons, and do not honour all men,
but disesteem them that have not fine clothes, and gay apparel, and riches,
and esteem them that have; and so honour the one, and dishonour the other;
now this is respecting of persons, and not to honour all men,
as the apostle James speaks of, who saith, James 2:12.
"`My brethren have not the faith of our Lord Jesus Christ,
the Lord of glory with respect of persons: for if there come a man with a gold ring,
and goodly apparel, and there come in also a poor man in vile raiment,
and ye have respect to him that weareth the gay clothing, and say unto him,
sit thou here in a good place, and say to the poor man stand thou there,
or sit here under my foot-stool;`" now this is the respecter of persons,
who hath not the faith of our Lord Jesus Christ, and not the honourer of all men,
and so there is the sectary; but who honours all men, they are no sectaries,
but are out of them all.

The second thing is this, "`Love the brotherhood,
and love enemies;`" now here is the two things, to love enemies, it is not to kill them,
and to destroy them, but to overcome them with the good; now enemies are sons of Adam,
in whom the enmity is, and the sins of the flesh, who be strangers from the life of God,
and the covenant of promise and sonship, in which is the brotherhood.

And so they that are in the love of God (which is
to the world,) would have them to be saved,
and to know his mind and his salvation; now if they would have all men to be saved,
they would not have them destroyed, neither destroy them: let them be hypocrites,
let them be blasphemers, let them be schismatics, or heretics, or fanatics,
let them be what they will, he would have them to be saved.
And the patience and long suffering of God, is great salvation;
Paul and David who were great transgressors did witness it.
But the impatient and envious (which are the tares) they destroy the saints,
and pluck up the wheat for tares, as blasphemers and heretics.
But these have not the spirit of Christ guiding of them, and such cannot love enemies,
for they that hate enemies, are out of the commands of Christ, and out of his spirit,
and mind, who persecute about religion, and church worship, but do not love enemies;
neither are they in brotherly fellowship, nor in the spirit and power of God,
that goes over all transgression, that was before it was;
and so they that hate enemies have not all men in esteem, (mark,
all men,) these are not in brotherly fellowship, nor do not love brotherhood,
but are respecters of persons, that do not honour all men, and love enemies,
but are in hatred, and envy, and fury, and rage, and madness,
(not in the love and meekness,) and that is the fanatic spirit, that love not enemies.

Thirdly, "`Fear God and honour the king;`" so mark, they that fear God, honour the king,
and to fear God is to depart from sin, and evil,
(and that keeps the heart clean) which is the beginning of wisdom.
Now such as fear not God, honour not the king, and such as depart not from sin and evil,
fear not God, and they honour not the king.

It may be they may talk of him with the lips, and bow the knee, put off the hat, etc.
But that is not the honour; for they that live not in the fear of God,
do not honour the king.
Drunkards, and swearers, and cursers, you fear not God,
therefore you honour not the king; for the scriptures saith,
"`ye shall not swear nor curse,`" as Paul saith, to the Galatians, and as Christ saith,
Matt.
5. and James saith, James 5. And all ye who live in adultery, fornication, uncleanness,
idolatry, whoredom, lasciviousness, effeminateness, pleasures, gaming, sporting, pastime,
which stirs up vain and idle words,
(for which you must give an account) and vain actions, and taking God`'s name in vain,
ye fear not God that do so; therefore ye honour not the king, but do dishonour him,
and this nation, and his government, and his kingdom;
"`for righteousness exalteth a nation, but sin is a reproach to any people,`" said,
Solomon; and, saith the apostle, "`this know ye, that no whoremonger, nor unclean person,
or covetous man, who is an idolator hath any inheritance in the kingdom of Christ,
or of God.`"
5 Gal.
5.

And all ye cozeners, cheaters, defrauders, disssemblers, liars, backbiters, slanderers,
false accusers, envious, and malicious persons, murderers, plotters, fighters,
quarrellers, brawlers, scolders, tumultuous ones, rioters, ambitious, proud, heady,
high-minded, vain-glorious, perverse, wicked, and wilful men,
you live not in God`'s fear, therefore you cannot honour the king;
for they who honour the king, must fear God, as ye may read, 1 Pet. 2:17.
All reproachers, scoffers, scorners, despisers, and mockers,
and such as give nicknames to one another, and foolish jesters, and vain, and corrupt,
and filthy talkers, who vomit out your own shame by your corrupt communication,
you fear not God, therefore you do not honour the king in your hearts;
you must come to the witness of God in yourselves all of you,
which lets you see sin and evil, and depart from it, which is the fear of God,
to depart from sin and evil,
and then ye come to honour the king as ye live in God`'s fear, and no otherwise.

And all ye who are earthly-minded, and live in oppression, extortion,
grinding the face of the poor, in covetousness, which is idolatry,
and rebellion against God, which is as the sin of witchcraft, and stubbornness,
which is iniquity, and say you shall have peace,
though ye walk in the stubbornness of your hearts, and regard not the Lord,
ye fear not God, neither do ye honour the king.

And all you unsober, intemperate, immodest, ungracious,
who choose vice rather than virtue and piety, you fear not God,
but cast his law and his fear behind your backs; therefore you honour not the king,
for ye are to be in the fear of God, before you honour the king.

So never profess that ye are honourers of the king, who do not live in the fear of God;
and never profess that ye are fearing God, and honouring of the king,
while ye are cursing, swearing, damning, roaring, drinking healths, and spoiling,
and misspending, consuming, and destroying the creatures, and drinking in,
and vomiting up again; all that be there (and are so doing,) fear not God,
and so they do not honour the king, (this is not for the king`'s health,
nor this is not for the king`'s honour,) but as I said before, such dishonour him.

And all that follow the vain fashions of this world, that live in the lusts of the flesh,
the lust of the eye, and the pride of life, which is not of God the Father,
but of the world, these fear not God, so they honour not the king.

And all thieves, robbers, man-slayers, plotters to destroy men`'s persons,
lives and estates, to bring men into poverty, and to undo one another;
these live not in the fear of God, which is to love enemies, and to do good for evil;
and these honour not all men, these love not the brotherhood,
these cannot honour the king, that live not in God`'s fear.

All they that make discord, and strife, and dissension amongst people by lies,
and false reports, and dissemble to get gain, and lay snares for the righteous,
and betray the innocent to get gain and advantage to themselves,
by telling lies of some to others, these fear not God, these do not honour the king.

And all who envy one another about their fashions, and diet,
because they have not means to maintain it as high as others,
though they would be in the same fashion, and live as high as others,
but their estates will not maintain it,
and therefore they envy all others who have estates, and can maintain it;
and likewise they that have estates to maintain their fashions, etc.
They envy others that would be there, and do as they do,
but have not wherewithal to maintain it; and so these do not esteem all men,
nor love brotherhood, nor fear God, nor honour the king,
that have these evils undeparted from; for they that go into evil, and live in evil,
or in any manner of sin and wickedness, do not fear God, but they fear God,
that depart from sin and evil, and such are they that honour all men,
and love the brotherhood, who depart from sin, and these are they that honour the king.

But now, cursers, swearers, covenant-breakers, perjured persons, who will swear,
and break oaths, and forswear, make covenants, and vows, and promises and protestations,
and leagues, and break them, such fear not God, nor honour the king.

And such as will fight, and kill, and destroy for a morsel of bread,
or a mess of pottage, are profane, as Esau was; these are men without natural affection,
lovers of themselves, and lovers of pleasures more than lovers of God, boasters, proud,
blasphemers, disobedient to parents, unthankful, unholy, truce-breakers, incontinent,
fierce, despisers of them that are good, traitors, and men of corrupt minds,
and to every good work are reprobates.
These do not fear God, neither can these honour the king, nor the kingdom,
nor nation wherein they live.

All that follow gluttony, excess and riot, who eat and drink, and rise up to play,
feastings, banquettings, stage-playings, bear-baitings, cockfightings, horse-racings,
huntings, hawkings, dancings, chamberings, wantonness,
spending their times after the lusts and pleasures of the world,
which perish with the using; these fear not God, these are not like to honour the king,
that destroy the creatures upon their lusts, and vain pleasures.

Therefore tremble before the Lord God, ye that fear not his name, but live in sin,
and wickedness, enviousness, maliciousness, strife, bitterness, wrath, anger,
and clamour, and evil-speaking, lying, false accusing, persecuting the innocent;
and live in drunkenness, bloody-mindedness, hateful, and hating one another, desperate,
rash, hasty, froward, unruly, disorderly, rebellious, unmerciful, cruel, hard-hearted,
fierce, despisers, wrathful, obstinate, wilful, stubborn, full of threatenings,
revilings, haters of God; ye love not enemies, ye honour not all men,
ye do not love the brotherhood, ye do not depart from sin and evil, ye do not fear God,
nor is it like that ye should honour the king.

And therefore, all people from the highest to the lowest,
it is a warning to you all to depart from sin, and all manner of evil whatsoever.
Ye that live in adultery, idolatry, fornication, uncleanness, whoredom, cursing,
swearing, drunkenness, lying, sporting, and pleasures, and in cozening, cheating,
deceiving, and defrauding one another, dissembling, reproaching,
persecuting one another with tongue or hand, backbiting, or slandering,
or false accusing one another, rage, malice and hatred, and envying one another;
fear God, and depart from those things, and come into the chasteness, and temperance,
and sobriety, and truth, and righteousness, and meekness, and lowliness of mind,
out of the highmindedness, and to love the brotherhood, honour all men, fear God,
and then you honour the king.

For as ye live in sin and evil, ye honour not all men, ye love not the brotherhood,
ye fear not God, ye honour not the king; that is from the Lord God to you all,
ye dishonour men, ye dishonour the brotherhood, ye dishonour the king,
ye cast the fear of God behind your backs, and his law also, who live in sin and evil,
though ye prate never so much of your honouring the king, we will never believe you,
that you honour him while ye live in sin,
for that is it which is to his dishonour and reproach,
and will bring the judgments of God upon the land.

So while ye live in the wrath, and revenge, swearing, cursing,
blaspheming the name of God, and taking it in vain, and professing him in words,
but in works denying of him, living in lying, deceit, and hypocrisy, and dissimulation,
in unrighteousness, injustice, and iniquity, in pride, idleness, and fulness of bread,
in drunkenness, riotousness, and vain pleasures and delights,
(which causeth you to forget God,) and all manner of cozening, cheating, deceit,
defrauding, puffed up, heady, high-minded, ambitious,
and overreaching one another in bargaining,
to overthrow one another to make yourselves rich; we do say, and know,
and believe that you neither fear God, nor honour the king, nor love enemies,
nor love the brotherhood, nor honour all men, who are so wicked,
and malicious and envious against men.

And all that are persecutors about religion, church-worship, ordinances,
ministers`' maintenance, and their traditions,
which the apostles never did so in the primitive times,
neither did Christ ever give any such command; these fear not God that do so,
neither do they honour all men that do persecute them about religion and worship,
and cast them into prison, nor love enemies, nor love brotherhood, nor fear God,
nor Christ, nor honour the king; for Christ gave them no such command,
as ye may read in the scriptures of truth.

Fourthly, and all they that persecute people about observing of days,
and not observing of days, meats, and drinks, which stand in the will-worship,
as the apostle speaks of, 2 Col.
who neglect the body; and the kingdom of heaven stands not in such things,
but righteousness, and peace, and joy in the Holy Ghost;
and they that so (do contrary to the apostle, who said,
"`Let every man be fully persuaded in his own mind,`") Rom.
14. bring people from waiting to be satisfied in their own minds, that persecute them,
and compel them to observe days, and times, and months, and years;
these love not the brotherhood, nor honour all men, nor fear God, nor Christ,
nor honour the king; for that which keeps in the honour of the king,
keeps in righteousness, keeps in truth, keeps in justice, which establisheth a kingdom,
and keeps in the kingdom of God, which stands not in meats and drinks, etc.

Fifthly, and all who teach for filthy lucre, for hire, and for the love of money,
such serve not the Lord Jesus Christ, but their own bellies:
and all who judge for gifts and rewards, and oppress the poor,
and do not equal justice to all, nor minister freely, as Christ commanded,
(who have received freely,) these fear not God, nor regard the scriptures of truth,
nor honour the king, who is to keep all to truth, righteousness, and justice.

Sixthly, and all who get a form of godliness, the scripture of truth,
(which was given forth from them who were in the spirit of truth,) and yet fine, prison,
and persecute such as are in the same spirit as they were in that gave it forth:
these neither regard God, nor his fear, nor truth, justice, nor equity;
so these cannot honour the king, but such who honour the king, must be temperate,
moderate, sober, patient, meek, mild, gentle, loving, do equally, justly, righteously,
be holy, godly, true, and faithful, peaceable, merciful, and humble;
for humility is that which goes before the honour,
and these are the fruits of them that fear God, and honour the king,
and love the brotherhood, and honour all men. 1 Pet. 2:17.


And the fruits of them that fear not God, and do not honour the king,
or love the brotherhood,
nor honour all men (though they pretend to do it,) are such as these, viz, cursing,
swearing, drunkenness, whoredom, lying, murder, plotting, killing, fighting, theft,
adultery, fornication, lasciviousness, pride, envy, hatred, malice, cruelty, oppression,
unmercifulness, idolatry, covetousness, inordinate affections, lust, voluptuousness,
unsatiableness, incorrigibleness, impenitency, unbelief, uncharitableness,
unthankfulness, hardness of heart, enmity, strife, emulation, discord, persecution,
and hauling men without cause, and laying snares for the innocent.

Never did any kill about religion but the heathen, and Cain, and the Jews,
which had a law from God to kill and put to death such as drew them from their God,
by which law they were to receive a punishment according to their transgression, whipped,
or stoned, or run through; therefore did the Jews think they did God good service,
by killing such as were contrary minded to them, in that they did obey the law.
Therefore, under this pretence they did kill the saints,
the christians in the primitive times, for they were to love their brethren,
and to hate their enemies; for they were their enemies, the heathen, and Gentiles,
and such as set up a strange God among them.
Therefore the christians (who own Christ, which ends this law, and the Jews`' types,
and figures, and shadows held up by it,) were to love enemies;
and this was the difference whereby they differed from the pharisees,
that were to hate enemies, and the christians were to love them; for the time hath been,
saith Christ, "`an eye for an eye, a tooth for a tooth,`" but saith he now,
"`He that smiteth thee on the one cheek, turn to him the other, and resist not evil,
but love your enemies:`" Now the Jews who hated enemies, their weapons were carnal,
but they that love enemies (the christians,) their weapons were and are spiritual:
so Christ ends that law of the Jews, which they thought they did God good service by,
when they put to death them that were contrary minded to them;
for they could not love enemies that killed them,
neither can they that love enemies now kill them; for they love them that preserve them,
and do not kill them,
for Christ who endeth the prophets (when his disciples
would have had fire to come down from heaven,
as the prophet had,) rebuked them,
and told them they knew not what spirit they were
of and said "`he came not to destroy men`'s lives,
but to save them.`"

And Christ nor the apostles never did set up any law or commandment to imprison,
or persecute any, brethren, or enemies, but love, for God loved the world;
and so they that love the brotherhood, and honour all men, that have all men in esteem,
they cannot hurt any man upon the earth, that oweth nothing to any man but love,
that is the debt which must be paid, for love envies not,
and he that envies is out of love, and not a child of God, but of Cain,
and so a vagabond.

Now all Christendom do profess Christ and God in words, (but are out of the life,
and out of the power,) who fall into differences and strife about earthly things,
and inventions, as days, meats, and their own traditions,
which the kingdom of God stands not in, but in power, in righteousness,
and joy in the Holy Ghost;
but now since the days of Christ and the apostles in the primitive times,
they have made laws to persecute one another, who have lost brotherhood,
and honouring all men, which if they were in the kingdom which stands in power,
(and not in meats and drinks, or days, or outward things,) but in righteousness,
peace and joy in the Holy Ghost, then they would feel the law of love,
the law of the spirit of life, and to be made free from the law of sin and death.
But they that fall out about days, and meats, and drinks, and inventions,
and their own traditions, are out of the kingdom of God, and out of the brotherly love,
not esteeming all men, not fearing God, and they that do so,
are contrary to Christ and the apostles in the primitive times.

So they do not God good service that do persecute about religion now,
and about the church-worship, for Christ commands them to love enemies,
who ended the Jews`' law, that did persecute the Gentiles,
and such among themselves as did draw from the law of God;
and he broke down the partition-wall which was between Jew and Gentile,
who slew the enmity, and so of twain made one new man,
and thereby came the love to enemies.

