== To the Turk,





And all that are under his Authority, to read this over, which concerns their Salvation.--By G. F.

Friends,--The mighty God of heaven and earth, that created all things,
that hath given you breath, and life, and strength to this day,
commands you all to repent, and to believe in his Son the Lord Jesus Christ,
who was crucified at Jerusalem, who was dead, and ascended, and is alive again,
and lives for evermore, the man Christ Jesus, who now reigns;
he commands that all powers, principalities, dominions should be subject to him.
And this is the command of the Lord God to thee, and you all,
who rules kingdoms and kings with his mighty hand, which is his mighty power,
as he doth the waters; so he hath kings in his hand, as he hath the waters;
the Lord of hosts, of heaven and earth, is his name, who sent his Son,
who is the life of men, the Saviour of the world, the great and mighty prince of peace,
the covenant of God with mankind, to make reconciliation for iniquity,
and finish transgression, and put an end to sin, the great governor of heaven and earth,
who hath all power in heaven and earth given unto him, whose command is,
that he will be worshipped in spirit and in truth: the spirit that mortifies sin,
the truth, the devil and sin is out of, for by your Mahomet have you been deceived,
which saint is set up; therefore is the dreadful presence of the Almighty God,
the everlasting Father of life appeared among you, and to you,
if that you will regard and embrace his voice, his power, his command,
which mighty God of power, of dominion, and of dominions, who rules over all nations,
heaven and earth, will seize upon you, and surprise you, and take you at unawares,
and bring his judgements and dread upon you,
which is now appeared in this the day of his Son; and the hour of his judgement is come,
and coming upon all the world, of the mighty God of heaven and earth,
of the mighty righteous God of heaven and earth, who in righteousness reigns,
and in truth and equity.

Therefore dread the Lord, whose mighty power is spreading over all nations,
who commands all nations to forsake idols, and images, observances of inventions,
to serve and to worship him, the Creator of all things,
that clothes the earth with grass, and causeth the trees to bud, and bring forth;
that gathers the waters together in one place, that established man upon the earth,
the eternal God, the Lord of hosts is his name;
and the word and charge of the mighty God is to thee,
and you throughout all your dominions, not give any worship to the sun, the moon,
gods of stone, or gods of wood, brass, or silver, or iron,
and not to put any trust or confidence in them, nor any thing else, but the living God,
or any false conceptions, but the living God, the Lord of hosts,
who gives you all breath, life, strength, and all things needful;
that you might worship him who is a spirit, whose dominion is set up, and setting up,
whose glory now is revealed, and revealing; whose kingdom is now set up, and setting up,
and spreading over all the world, who will be glorified and admired, the mighty King,
the Lord of hosts, by all that fear him,
the terrible God of heaven and earth to the wicked,
and they shall find him dreadful that have trusted in lying vanities,
and false conceptions, the Lord of hosts is his name,
who delivers his people from their iniquities, and their sins; therefore remember him,
for now is the day of his Son, the Lamb`'s power, who is come to reign,
and to rule all nations with a rod of iron, whose sceptre is gone forth,
and righteousness shall shine throughout the world, to the ends of the earth,
Christ Jesus the everlasting covenant of God, the great sacrifice,
that one offering which ended all sacrifices, and offerings of rams, lambs, oxen, sheep,
and whatsoever was outward, Christ the mystery of God, the Saviour of the world,
to all that believe in him, that through him they might have life,
who is the way again to God, who is the second Adam, the Lord from heaven,
that leads the sons of Adam, and the daughters of Adam,
and is their guide up to the Father, who is the life, the light, and power of God,
and their sanctification, that makes people clean,
and presents them to the Father spotless, and blameless; for Adam being driven from God,
for sin and transgression,
and Adam`'s sons and daughters scattered up and down the face of the whole earth,
divided into families, and into nations, and several kingdoms,
spread up and down the face of the earth, and some in one worship, and some in another;
some worship the sun, some the moon, some stocks, some stones,
and some looking at Mahomet, others setting up dead images, and likenesses,
which the Lord never did command.

Now all the sons and daughters of Adam being dead in sins, and trespasses,
and in darkness under the power of Satan, killing and slaying about their worship,
being in darkness, and death, wanting life, and light, being separated from the Creator,
in sin and transgression, have set up their inventions in the earth,
and outward worships and inventions, but Christ is the second Adam, the Son of God,
which God sent into the world, which doth enlighten every one that cometh into the world,
that all through the light might believe, and that all might believe in Christ;
and this is the light that Christ the Son of God hath enlightened
every one that cometh into the world withal,
that he sees his evil deeds that he hath done, his evil works that he hath acted,
his evil ways that he hath walked in, his ungodly deeds,
that he hath ungodlily committed, and his ungodly thoughts, that he ungodlily thinks,
and his ungodly words, which he ungodlily speaks;
this is the light that discovers and makes manifest all this to people,
their sin and transgression, which they have done in the first Adam,
which separated them from God: now Christ, the second Adam, doth enlighten them,
with which light they see their sin; now being in this light,
they see their Saviour Christ, from whence the light comes to save them from their sins,
he is the second Adam, their life, and being in the light they have life,
being in the light Christ the life hath enlightened them withal, they have life,
for Christ is the life;
which light and life that doth enlighten every one that comes into the world,
every one receiving, they are separated from sin by Christ,
and by him brought to God again; for sin and transgression separates from God,
and this is that that brings people to worship God in truth,
the light which Christ the truth enlightens every man that comes into the world withal,
which believing in, he hath life, he hath truth, and he passeth from death,
and from darkness, from sin, and transgression, and hath the witness in himself,
through which light and life all comes to the Father of life,
which light brings from all the worship of images, as stocks, and stones,
and gods made of men`'s hands; yea, and from Mahomet, to the Lord Jesus Christ,
the great prophet, the Saviour of the world,
whom God did promise by his prophet he would give for a light to the Gentiles,
a ruler to the people, and that he should be his salvation to the ends of the earth:
and a new covenant to the house of Israel, and the house of Judah,
who would put his law in their minds and hearts, and they should not depart from him;
which every one of you that come into the world being enlightened,
and having light from the Son of God,
and feel your teacher that tells you all that ever you have done, you have thought,
or you have spoken, that is the man Christ Jesus; who saith, learn of me,
I am the way to the Father, that enlightens every man;
so all that come into the world must learn of him; (all the sons of Adam,
and daughters of Adam, in the transgression are drove from God,) the way again to God,
out of sin and darkness, and death and damnation, to life and light again, and salvation.
So every one that comes into the world being enlightened,
and being in the light they have the witness in themselves,
and he that believeth shall not come into condemnation;
but he comes into the light that condemns all that is contrary, he comes into the light,
into the truth, into the light that is the truth,
where the Father of light is worshipped, and the devil and sin are out of;
which truth will out-last all false worships, and worships that be out of truth.
Now is the mighty supreme judge risen, and the mighty supreme authority set up,
and the mighty King of glory, the Lord of hosts (risen) is his name,
before whose presence shall all nations tremble,
and before whose presence shall all nations and kings shake, for the mighty God of power,
of heaven and earth is come to rule,
and his mighty power is gone forth to the gathering of all nations to himself,
to the subduing all powers to himself, who will rule and reign, whose right it is,
the Lord God of hosts, whose the earth is, and the heavens, and the sea,
and all things that be therein, and people upon the earth, and gives them breath,
and life, and strength, and all things that is good, that they might serve, glorify,
and worship him that is the Creator.
Therefore, give attention to your Maker, to your Creator, and dread before Him;
for before Him, the Lord God of might and power,
shall all nations tremble in this his day, in this day of his power,
for his mighty power has gone forth to gather all nations, which doth compass them,
and all nations before Him is but as the drop of the bucket:
and now is his day of gathering of all nations and kings
to the battle of the great King of heaven and earth,
and nothing shall reign and rule but righteousness itself,
and that over all kingdoms and dominions, and thrones, and principalities is set up,
and the standard of the most high God is pitched over the whole world,
and his call is to the bar of righteousness, all kings, and dominions,
and powers whatsoever; therefore, dread his name, for his name is dreadful, the Lord God,
the mighty God, the Most High, who is in his glory, and rules in his dignity, and power,
and majesty; who is a spirit, and will be worshipped in spirit and in truth,
by whose breath of life man came to live, who is a spirit,
and will be worshipped in spirit, and that is the spirit that mortifies the sin,
and that is it in which people must have fellowship with God, and with one another,
and with his prophets`', and apostles`', and Son`'s words: therefore, fear the Lord,
let him be your fear and dread, and turn to the light,
which Christ the Son hath enlightened you withal, and believe in Christ,
the saviour of the world, the offering for the sin of the whole world,
that you might have life in him, and through him,
and come to the dominion (which Adam hath lost,) over all the creatures, to Christ,
the light and life, the power and righteousness over all, and wisdom of God itself,
that renews man into the dominion which man hath lost; Christ,
by whom the world was made, was before it was made, who is the brightness of his glory,
the express image of the substance of God: in him was life,
and the life was the light of men,
which doth enlighten every man that comes into the world;
through the light that enlighteneth them they have life, light, justification,
sanctification, redemption, they have salvation, they have truth,
they have peace with God; for the light is the covenant,
"`I will give him for a covenant of light to the Gentiles,`" saith God,
"`and a leader to the people:`" So that light should
be the leader of every man that comes into the world,
the light with which every man is enlightened that comes into the world,
that is the leader; which light was with the Father, glorified before the world began;
which light lets men see all their evil ways and sins,
and transgressions they have done in the world,
and the first transgression that was upon the earth, with which light,
(the covenant of God,) sin and transgression is finished and blotted out,
(to them that believe in it,) the which separated them from God,
(sin and transgression) Christ, the light and truth, separates from the sin,
transgression, and iniquity, and reconciles to God, and brings to unity with God again,
and in that hath the people life and immortality,
and that is the word of the Lord God to all, and I charge you all to hear it,
the light that lightens every one that cometh into the world,
it will make you free from sin,
by which light shall every one that believes see their salvation Christ Jesus,
and the man that hath told them all that ever they have done,
and they shall know his salvation to the ends of the world,
and to you all this is the word of the Lord God, ye believing in the light,
which Christ hath enlightened every one that comes into the world withal,
they being in the light, with the light they are justified;
and he that believeth in the light shall never be condemned in this world,
nor in the world without end.
And in the light you will have unity with God, and peace with God, and one with another,
and bring you to live peaceably upon earth one with another: yea, all nations and men,
the sons and daughters of Adam being enlightened,
having a light from Christ Jesus the second Adam, the way to the Father; the life,
the truth, all being in this truth which the second Adam hath enlightened them withal,
who is the life, the truth, the way to God, the way again to God the father of life,
where man is driven from, and cannot enter again, but by the light,
Christ the second Adam.
So all being in the light, they are in the way, they have found the way Christ Jesus,
the chief shepherd, the bishop of the soul, (which soul is immortal,) the same yesterday,
to-day, and for ever, who was the Father before the world began, by whom all was created,
who is the soul`'s bishop, and the author of man`'s salvation, and redemption,
and justification,
(who hath been driven from him by sin and transgression) Christ who blots it out,
and is the offering that offered himself for the sins of the whole world,
who is the light of the world, that enlightens every man that comes into the world,
that all through this light might believe in the Son of God, Christ Jesus,
the one offering, who is the way to God, and the covenant between God and man,
in him is God well pleased, and doth accept man; and they which believe in him have life,
have power, have wisdom, and receive him that gives them power;
and no one upon earth hath life, peace, or justification,
but such as come into the light of Christ the justification,
the life of all that come to God, who was glorified with him before the world began,
who lets all men see their way again to God, who is the life, the truth,
and the leader of the people;
which light is the condemnation to them that do not believe in it,
and such have not unity with God, nor one with another; they be not in the one offering,
the great sacrifice, the Prince of life, Christ Jesus, the Immanuel,
and know not the interpretation thereof, that is, God with us.
Therefore, every one of you that would have salvation, receive the light,
and so you receive Christ your salvation, and neglect it not;
for this is the day of your salvation and visitation;
and the mighty power of God is gone forth among you, and his everlasting gospel,
which is his power, is going forth to all nations, kindreds, tongues, and people,
that dwell upon the earth,
by which gospel shall kindreds and nations be gathered unto him,
and into the mystery of the fellowship of the gospel, which fellowship is everlasting,
the gospel everlasting, the power of God everlasting, in which is the fellowship,
so that is everlasting; in this, people have fellowship with God, and one with another.

From England.

