== Some Papers Given Forth to the Magistrates of the Isle of Milita





And to the Emperor of the House of Austria, and to all the Princes under him.
To the King of France, and to all the Powers that be under him; and to the King of Spain,
and lastly, to the Pope.--By G. F.

Friends,--Two women being moved of the Lord to pass towards Jerusalem, were stopped,
as we hear, by you rulers, who sent to Rome to the pope,
to know what you should do with them;
(the servants and handmaids of the Lord God,) And
why were you not worthy to receive them?
And why do you not own the apostles`' doctrine, which is to entertain strangers?
And what is this the end of your religion?
and why do you not own Christ`'s doctrine?
The Lord Jesus Christ, who is now come to reign, which bids to love enemies;
why do you send them to the inquisitioners,
who will stop the hand-maids and servants of the Lord?
Is this work like the true christians?
And is this doing like the apostles, and did you do in this,
like men that were in the wisdom of God, that had the mind of Christ Jesus,
and his spirit?
Where did ever the apostles do so, or Christ?
Or the true christians in the primitive times?
Why do you wrestle with flesh and blood, when the apostles said they did not?
Why do you act contrary to them?
why do you act contrary to the command of Christ?
(who hate enemies) as you pretend them to be your enemies, which be your friends.
Is not he a heretic, or a schismatic, that is erred from the true church,
the body of Christ, that hates enemies?
Why do you thus act contrary to Christ`'s commands, and the apostles`' doctrine?
Do you not manifest that you have but the form of godliness, and want the power,
did ever the apostles, or Christ, prison any, or put any to death about religion, church,
or worship, or any tradition, or compelling any to worship?
Had they any among them to force men by an outward law?
Was not the gospel preached, the end of the law of God,
and so the end of all evil men`'s laws and inventions whatsoever?
And are they preachers of the gospel,
that do not preach that which is the end of the law, and brings people to the end of it?
Are they not the persecutors that runs to the law, or their own inventions,
and doth not come to Christ that fulfils it?
How have ye made the world like a wilderness, and stained the earth by your persecution,
and inquisitions, prisons, and images, and destroying people, and drinking their blood,
of such as have been opposite-minded against you;
and this hath been since the true church went into the wilderness
(which was not an outward wood) since the apostles`' days
how hath this family of Christendom massacred one another?
How have they fallen out in the family amongst themselves?
when they should have loved one another, when they should have overcome evil with good,
when they should have loved enemies,
when they should not have wrestled with flesh and blood, but with principalities,
and powers, and spiritual wickednesses in high places, and rulers of darkness,
and brought the creature into the liberty of the sons of God;
and here is the spiritual weapons which the primitive christians warred withal,
but how hath the carnal weapons appeared in the hand almost, of every christian in name,
amongst which hath been the form of godliness, Christ`'s, the prophets`',
and apostles`' words;
whereby they have sheathed their carnal weapons in the bowels of one another, killed,
and slain, and tortured, burned, prisoned, and racked,
and put to death one another about their church, religion, worship, and ministry,
and teaching and tradition, and ordinances and sacraments as they call them.
Oh! how unlike the apostles, Christ, saints, and christians of old are you.
Oh! how have the spiritual weapons been wanting among you,
and the spirit of the Lord God, in which you would have had unity in the bond of peace,
whereby every one would have broken down the enmity, that which causeth it,
and have brought one another into the liberty of the sons of God,
and made manifest your spiritual weapons;
hereby would ye have come to live in the spirit, worshipped in the spirit,
prayed in the spirit, and in that had unity with God, the Father of spirits,
and one with another, and with the scriptures that was given forth from the spirit;
then should there have been unity in the family being in the spirit,
in which they all should worship God, in which the scriptures is known,
and God of whom they learned, that gave them forth;
but what a discord is there in the family of christians in Christendom! what a cry!
Heretics, schismatics, antichrists, errors, a whole family in confusion,
and setting up laws one against another, dividing the family,
putting one another to death, as heretics, blasphemers, schismatics.
Were these the weapons the apostles fought with?
Did they not preach the gospel, the end of the law, and priesthood, and temple,
altar and offering held up by a law?
And is not Christ the head of the church,
who hath all power in heaven and in earth given unto him?
Who saith, love enemies; and do you not hold up your religion, gospel, church, worship,
and ministry by a law which is invented, and statutes, and commandments!
Is this the bride, the Lamb`'s wife?
Or the beast, false prophets, and antichrist, and the mother of harlots,
(the false church,) which hath compelled, killed, and drank the blood of the saints,
and martyrs?
and have not you ruled in this posture, and garb, and wisdom that is earthly, sensual,
and devilish, since the true church went into the wilderness,
(of which Christ is head?) And must not they be taken, the beast, dragon,
and false prophets, and the judgment of the great whore, the false church come?
And the Lamb, and the saints, the true church his wife, have victory?
And is not his sword he killeth withal, the words of his mouth?
And hath not all your killing been with outward swords, with jails, inquisitions, racks,
and fires?
and so have you not been traitors to the Lord Jesus Christ, who saith love enemies,
overcome evil with good, and when they persecute you,
not that you should persecute again;
and Christ was persecuted and blasphemed by them that lived in error,
more than any man upon earth, who was the end of the law,
and he did not turn them to the Jews`' law,
which was yet standing before he was offered up to put them to death,
but rebuked the blind zeal of such that would have
had fire come down from heaven to consume people,
and told them he came not to destroy men`'s lives, but to save them,
and told them they did not know what spirit they were of:
no more now do they know what spirit they are of, that persecute men about religion,
church, and worship, and ministry, that slays and destroys men`'s lives,
and not saves them; they are not of Christ`'s mind:
and Christ did not use any law to compel and bind men to the worship of God in the spirit,
for the spirit of God (who worship in it,) binds down the wrong nature,
whereby they need not be compelled by the law, but come to live in the end of the law,
(who be true worshippers,) and this spirit, hearing what it saith, it brings to near God,
and learn of him, such comes to Christ, such are not compelled by an outward law,
to come to God, and Christ; but that brings to hear God, and Christ,
binds down that nature which occasions the law,
that comes upon them because of its fruits; so they that are come to the church in God,
the Father of Christ, are not compelled by an outward law,
they come to the end of the law, who come to the church that Christ is the head of;
so the church lives in the end of the law; the body of Christ makes free from the law,
and who comes to the body of Christ, comes to the church, and the head thereof is Christ,
therefore lay away your persecution, your jails, racks,
and inquisitions about your ministry, worship, and church,
and come into the power of the Lord God that comprehends the world,
and feels over the world to the beginning before the world began, Christ Jesus was,
who hath all power in heaven and in earth given him,
who is now come to rule and reign in his power, who is terrible to the wicked,
and the wrath of the Lamb is gone out against them,
and thousands there be living in his power, and are with the Lamb, the wonderful one,
the beginning, and ending, the prince of peace, prince of life, that slays,
that destroys the devil, the prince of darkness, the prince of the air,
the prince of the world, and saves men`'s lives.
So who comes into the power, into Christ`'s power,
which hath all power in heaven and earth given to him,
and have his mind to save men`'s lives, they shall know what spirit they be of,
and that they are contrary to this family of nominal christians,
who have manifested they have not the spirit of Christ.

And the mighty day of the Lord is coming upon all wickedness, and ungodliness,
and Christ is come to reign, who is the prince of life,
who will rule all nations with a rod of iron,
whose dread and power is to be sounded over all nations.

