== To the King of Spain.

Friend,--Thy cruelty is come up into remembrance with the Lord,
and with his power art thou fathomed in this his day, with thy inquisitions,
and cruelties, which thou hast acted upon such that to thy mind have been contrary;
the Lord has remembered thee, and remembered them whom thou hast martyred,
and in this day of the Lamb wilt thou be recompensed, and thy inquisitions, thy fires,
thy swords, thy torturings, shall not secure thee, nor profit thee,
nor stand thee in any stead.
The Lord is come, and coming to call thee to an account for thy actions, for thy works,
for thy deeds, and into remembrance of him are they come, and thou, thy religion,
thy church, and profession and worship hast thou defended, by swords, by faggots,
by inquisitions and tortures,
thou hast caused the heathen (who has had the name of a christian) to blaspheme,
by thy bloody cruel doings among them, thou hast shamed the name of a christian,
and the day of thy recompense is come and coming, and draws on apace, and thy fires,
faggots, inquisitions, racks, tortures, swords, shall stand thee in no stead,
and do thee no good in this day of the Lamb`'s power, which is now stretched over thee,
with thy jewels, with thy pictures, with thy images, thy relics,
thy crosses of wood and stone, hast thou corrupted the earth.
And the day of the Lord`'s power is gone over thee,
and the day of the dread of the Lord shall overtake thee, which is now risen,
the morning star is now broken forth,
and your religion and your profession shall be at an end;
the end of it is seen in the mighty power which is endless,
and the Lord`'s hand is against thee,
and ye all who have been quite contrary to the apostles, to Christ,
had they inquisitions, had they racks, tortures, fires, faggots, images, nunneries,
wooden and stone crosses, beads, pictures?
did they fight with Cain`'s weapons, a war with flesh and blood?
Did they burn, kill heretics, that were from them contrary minded?
Your desolation is coming, the Lord`'s power is over you,
and with it ye are comprehended to be out of truth,
to be such as the apostles saw were coming up before their decease, in Cain`'s, Core`'s,
Balaam`'s way, killing, slaying, such as be contrary to your minds, Cain-like, Jew-like,
that was in the transgression, which turned against the just, doing the devil`'s work,
as Christ said of the Jews, they were of their father the devil,
the murderer turned against the just.
The apostles and Christ were not persecutors, but the just always suffered by the unjust,
and with all your lying signs and wonders have you deceived the nations,
and kept the simplicity of truth from them, by your inquisitions, fires, faggots,
Cain`'s weapons, that went forth from the apostles, which made up your pope`'s church,
you heretics, Cains, Cores, Balaams,
which they saw coming in as they declared in their epistles,
your weapons declareth you to be of that stock which
went forth from the apostles into the world,
that set up your lying signs and wonders there, inquisitions, fires, faggots, jewels,
beads, pictures, images, wooden and stone crosses, that went forth from the apostles,
that were in the power of God, the cross of Christ,
and said the power of God was the cross of Christ.

And such as went forth from the true church the apostles were in,
hath set up your church, that the spirit spoke expressly should come,
and depart from the faith, and give heed to seducing spirits, and doctrines of devils,
forbidding of meats and marriages,
and so ye are come and fulfilled that the spirit spoke expressly you should do,
and you are such that Christ said should inwardly raven, have sheep`'s clothing,
inwardly ravening wolves, the antichrists and false prophets, against the true Christ,
and so you have put your bread and wine for him.
You say he is in the desert, in the secret chamber, lo here, and lo there;
and how have ye ravened over nations, with sheep`'s clothing upon your backs,
but you have rent and torn and worried the lambs, the sheep,
that is declared by your fruits, what thistles, and briars,
and brambles may be gathered among you, that is declared also by your fruits,
how ye are like thistles, thorns, briars,
the witness in all your consciences shall answer it, who are the inwardly raveners,
that Christ said should come, Matt.
7, and the 24th of Matt.
John saw was come, the 1st epistle, and 2d chapter, and the 4th chapter,
which went forth from the apostles into the world, and in the Revelations,
all that dwelt upon the earth went after them, all the world went after them,
but they whose names were written in the Lamb`'s book of life,
before the foundation of the world was,
so you worship the dragon who gave his power to the beast, you worship the beast,
and the beast made war with the saints, and overcame them,
the dragon was wroth with the woman, and fled into the wilderness,
and the man-child was caught up to God,
and the beast killed the saints that had the testimony of Jesus,
and power was given to him over all kindreds, tongues, and nations,
he established his lying signs and wonders in his nations, and his marks, and his horns,
and his images, likenesses, and his names, and the whore sat upon the beast.
Then came up your church to be established,
when the true woman was gone into the wilderness to be kept for a time, and times,
and half a time.
And the woman, the great whore, made all nations drunk with the cup of her fornication,
and the kings of the earth, she has corrupted the earth with her images, and idols,
and made the inhabitants of the earth drunk; she sits upon the waters,
and the waters are nations, kindreds, tongues, and people,
she has drank the blood of the martyrs, the blood of the prophets,
and this is the false church, the false woman, the whore, and there ye are.
The true woman, the true church hath been in the wilderness, and ye the false woman,
the false church hath ruled.
But now is the judgment of the great whore come.
Now is Babylon confounded, and confounding, and now shall the beast be taken,
the old dragon, the false prophet, and cast into the lake of fire.
And now shall the Lamb and the saints have the victory,
now is the man-child brought forth into the world,
which shall rule all nations with a rod of iron,
and this is the day of the Lamb`'s power,
and now shall the everlasting gospel go forth to all kindreds, tongues, and nations,
and to them that dwell upon the earth, which is the power of God,
through which power life and immortality shall come to light,
and ye to be judged with the power, and your mother and popish church, and to the power,
and to the state the apostles were in, is the saints come,
which have victory with the Lamb, over all your jewels, beads, pictures, crosses, images;
for the power, the hand of the Lord is turned against you,
and with it ye are all compassed, pope, papists, Jesuits, inquisitions, nunneries,
pictures, beads, jewels, crosses, by the cross of Christ, the power of God,
with that ye are comprehended, and judged, and trampled over, and gone over,
through which power the saints are crucified to the world.
Now is the mystery of iniquity discovered, that man of sin the apostle said should come,
which has destroyed, and devoured, and wrestled with creatures, flesh and blood,
and killed, and murdered men and women, and not saved their lives;
this hath been the work of the man of sin, which the apostles discovered;
we are come to the apostles`' power which they were in,
by which we comprehend you who have done the man of sin`'s will, pope, papists,
and Jesuits, priests, and thine, and the Lord reward you, as ye have drank blood,
he will give you blood to drink; as ye have killed with the sword,
so shall you perish by the sword, pope, papists, and Jesuits, and thou, and you,
which sword is gone over you, and turned against you.

The mysteries of God is manifest with which the mystery of iniquity is comprehended,
which hath wrought since the days of the apostles, and began in their days,
and ye fulfill the prophecy of Christ, which said love should grow cold;
ye have not loved your enemies, heretics, schismatics are enemies,
ye have not overcome evil with good; ye have not converted by the power, by the faith,
by the life and light of Christ Jesus: but by swords and faggots, and inquisitions,
have ye made nations to bend to you,
and the simple foolish people to stand in awe of you;
and the ignorant world whom you have gathered into
your body to make up your church withal,
and so your love declares itself like Cain, killers, slayers, murderers,
ye have broken the command of God, which saith receive strangers.
For as the apostle was to go over all nations,
so has the deceit since the apostles`' days, the false prophets spread over all nations,
and the mystery of the iniquity, the beast and dragon, the whore`'s power.
But now shall all these be taken,
and the everlasting gospel be preached again to all kindreds, tongues and nations,
to all that dwell upon the earth.
The great and mighty day of the Lord is come, and coming to all the world,
and his salvation shall be known to all the ends of the earth,
and life and immortality shall come to light,
and the Lamb`'s power known in this the day of the Lamb,
Christ Jesus who is come to reign,
who doth enlighten every one that cometh into the world,
that all through the light might believe,
that all with the light might see their salvation, their Saviour the Lord Jesus Christ,
from whence it comes, and receive his power, and enter into covenant with God,
Christ Jesus the covenant of God, given for a leader to the people,
which saith to the prisoners, show yourselves forth; which now hath thousands,
and ten thousands showed themselves forth, which has received the leader,
and feels the leader Christ Jesus the covenant, the leader of his people,
the way to the Father, and this in all your consciences shall you witness,
with the light which Christ Jesus hath enlightened you all with,
which is your teacher if you love it, your condemnation if you hate it.

The light discovers and makes manifest in all your consciences, popes, cardinals,
Jesuits, priests, kings, all the blood ye have shed, all the tortures, and fires, racks,
and inquisitions that ye have put people unto, that is the light which makes it manifest,
that comes from Christ the Saviour of the world,
which doth enlighten every one that cometh into the world,
that all through the light might believe, and save men`'s lives,
he that believeth in the light hath life and salvation, and comes not into condemnation;
he that doth not believe is condemned,
and he that doth believe hath the witness in himself,
and can set to his seal that God is true;
so it is the light which every one of you is enlightened withal,
which is your condemnation, for all your actions, your cruel actions, your cruel deeds,
and killing and slaying, and slaughtering, and burning the lambs, the babes of Christ,
and such as to your minds have been contrary, with the light,
the witness in all your consciences are all these things comprehended,
and in this the day of the Lamb shall the witness
in your consciences answer in you against your actions,
and cruelties in ye, in the pope, cardinals, kings, Jesuits, priests, papists,
the light which Christ Jesus hath enlightened every one of you withal,
shall cry against your evil works, your deeds, your carriages,
and condemn you for them all, and tell you they are all evil,
in this day of the Lamb`'s power.
And the Lord Jesus Christ, the man whom God hath ordained, is come to judge,
to judge according to the secrets of every man`'s heart, and the world in righteousness,
and ye shall give an account according to the deeds done in the body,
and the light shall answer to it.
By your beads, nunneries, and jewels, by your crosses, pictures, and images,
inquisitions, racks, fires, and prisons, have you buried the witness in yourselves,
and gone from the light in your own particulars,
which should have kept you up to receive Christ the image of God; and by your killing,
and slaying the creatures, by your wrestling with flesh and blood,
taking away men and women`'s lives, have ye lost the spiritual weapons,
which should have wrestled with powers of darkness,
and spiritual wickednesses in high places.
But now is the man-child brought forth into the world, whom the kings of the earth,
beast, false prophet, and dragon, great whore, make war against,
but the Lamb and the saints shall have the victory, who kills with the sword,
and slays with the sword, which is the word of his mouth.
Now are the reapers going forth to reap,
the angel going forth to reap with a sharp sickle,
and now shall the wine-press be trodden without the city.
Now is the gathering together to the great battle of the great God Almighty,
now shall the fowls of the air feed upon the flesh of kings and captains,
and now is your day of visitation, which with many of you is over,
for many of you are to be numbered with the sword, and cut down to the earth,
which has grown like sturdy oaks,
which has lain like a barren wilderness full of venomous serpents, and wolves,
devouring lions, and ravenous beasts, and bears.
Your field has been a field of blood, and the righteous blood lies among you,
the field of the persecutors upon the earth, transgressors, destroyers,
the earth the field, the world the field of blood,
where all the blood of the righteous lies, and it is required of you,
the righteous blood that has been shed since the days of the apostles by you,
the witness in all your consciences shall answer it.
Oh your field looks red with the blood of the righteous, the blood of the saints,
and prophets, and martyrs!
Oh Christendom how art thou bespeckled with blood!
Oh, how has this whore, this woman, this false church, bespeckled herself with blood,
and drank the blood of the saints, prophets, and martyrs,
since the woman fled into the wilderness, the true church, and she has sat as a queen,
seeing no sorrow!
Now loss of children, now sorrow, now blood to drink, you are of the whore,
and you are judged with that which let us see to the apostles, before the whore came up:
Hallelujah to the Lord in the highest, the saints shall have the victory,
and the mighty God is risen, the Lamb`'s power is known,
the marriage of the Lamb is come, the bride the Lamb`'s wife is witnessed,
she hath trimmed herself for her husband.
The alarm to the world is given, the trumpet is sounding, the woes is going forth,
plagues to the beast, vials, and thunders, and earthquake,
such a one as hath not been since the foundation of the world, coming upon you,
and all the earth, the light which Christ hath enlightened you withal, shall answer it,
and answer the salvation and condemnation,
the light in all your consciences shall answer it.
Now is the Lord gathering from east to west, from north to south,
and now shall the angel be known that holds the four winds.
The mighty God of Jacob is risen upon you, the seed of the woman,
Christ to sit upon the head of the serpent, and you shall in no wise escape,
you have been out of the wisdom of God, out of the power and life of God,
in the dragon`'s power, destroying, and devouring,
and the earthquake among you shall be known,
the dread of the power of the Lord God of life, is gone over you with woes, plagues,
terrors, and amazements; ye shall be laid level with the earth,
the Lord of hosts hath spoken it, the Lord God of thunders will perform his word,
and accomplish his desires upon you, and be avenged upon you his adversaries.
The day of his visitation is come, recompense, and vengeance, and fury upon thee,
and you, his adversaries, no hiding-place will be found for you to escape his judgments,
his power, his hand, his thunder, his sword, his arm, his strength is over ye all,
with it you are fathomed and comprehended, in which power, strength, life, arm,
his salvation, his servants are in, and the Lamb, the man-child rules and reigns,
who makes war in righteousness, with which power they go over you,
and shall answer the light in every one of you, which you are enlightened withal, pope,
cardinals, kings, Jesuits, priests, and papists, I say the light in all your consciences,
shall answer to the power of God that is over you, with which you are comprehended,
and by the church of our Lord Jesus Christ,
(the Lamb) who be in the power the apostles were in, by which they comprehend the world,
and fathom it, and you who are out of it,
this power shall tread you to dust and powder under their feet,
who are come into the power of the Lamb, the Lord, the Father before the world began,
in which the Lamb and the saints have victory, and the age is come the apostle spoke of,
that he will show forth his exceeding riches,
his grace and kindness through Jesus Christ, which the apostle spoke of to the Ephesians.
Now is redemption known, redeeming and recovering that which was lost,
and restoring into that which was before the apostacy came up,
which was in and among the apostles, with which (over you) this is seen,
and the fellowship in the mystery, people are brought into,
which is the gospel the power of God, which is everlasting, universal,
and this mystery and fellowship is possessed, glory in the Highest,
with which mystery and fellowship, is all other mysteries of iniquity discovered,
and comprehended, and you, and all fellowships of the world,
your time of desolation is at hand, the power of the Lord is gone over you,
and against you, and it ye cannot escape.
Consider this, and read it over, let a copy of it go to your father the pope,
and cardinals, and scatter it among the Jesuits, and priests,
and the rest of your fellow-kings, and emperors,
for the day of the Lord`'s power is going over you, passing over you,
his mighty hand and arm is stretched over you,
and the Son is come who reigns in his power,
and he hath set up his kingdom which is without end, the Lamb`'s authority, and throne,
the everlasting Father, the prince of life, the heir of all things reigns and rules,
in the midst of his saints and prophets, his righteous sceptre,
throne and dominion is set up, and they shall have the victory,
and the hand and power of the Lord God is come over you, and his terrors, thunders, woes,
plagues, and judgments,
ye must drink the fury of the cup of the Lord God`'s wrath and indignation,
for with a high hand, and stretched-out arm, and mighty power, dread, and authority,
will the Lamb, the man-child who is brought forth, rule you, and all the world,
who now sits upon his throne, conquering, and to conquer,
who goes on subduing all principalities, thrones, dominions, and powers to himself,
who will have the rule, the government, the victory, the glory and honour to himself;
so to you this is a visitation from the Lord, and the power of the most high God,
and the Lamb in this his day, who will rule, reign, and subdue.

The apostle said, let your moderation appear to all men,
but your immoderation hath appeared to all men, to all nations about you,
of all you papists, your prisoning, your killing, your inquisitions, your racks,
your torturing, your burning,
your immoderation hath appeared to all men and sufficiently is seen,
and hath declared itself.

From England.

George Fox.
