== To the King of France.





Read this over, it concerns thy general good, and all the Powers that be under thee, which are suitable things to this present age.--By G. F.

Friend,--Let none in all thy dominion under thee be imprisoned till death, or persecuted,
or banished concerning religion, church, or ministry, or about the scriptures, Christ`'s,
the apostles`', or saints`' words, for such as do so, are out of the life of Christ,
the apostles, and the saints.
For all Christendom hath been on heaps,
killing and destroying one another about the ministry, church-worship, and scriptures,
killing, imprisoning, banishing, whipping, and torturing the bodies of men:
now the cause is, (that) magistrates are out of the life of Christ, the prophets,
and the apostles, (and now into this is the Lord God bringing his people, to wit,
that which the scriptures were given from, in which they shall have unity,
and fellowship with God, with the scriptures,
and with one another:) therefore is there so many ways, opinions,
and judgments about the scriptures, because they want the spirit that gave them forth,
in which they shall all have fellowship, and in which is the bond of peace.

George Bayly was moved of the Lord to go over into France,
and was imprisoned to death in Paris,
whose innocent blood will be required at your hands, and lies upon your heads.
You should have overcome evil with good,
you should heap coals of fire upon your adversaries`' heads, you should love enemies,
let them be heretics, or whatsoever you call them, this is the doctrine of Christ;
you should receive strangers, you should not imprison them;
you want the life the scriptures speak of, you have the words,
but you want the life and power.
You are them the apostle saw should come, and of whom the spirit speaks expressly,
they would depart from the faith, and give heed to seducing spirits,
and doctrines of devils; forbidding meats, and marriages,
and their murdering about religion, this hath been the work of you, and the pope,
since the days of the apostles, and the true church fled into the wilderness.
Rev. 12. Christ told the Jews they were murderers, and persecutors, and had shed blood:
and that all the righteous blood shed from Abel, would be required at their hands,
for Christ came to save men`'s lives, and not to destroy them:
and when they would have had fire to come down from heaven to burn them,
he rebuked their zeal.
Now you, and the pope, instead of calling fire down from heaven, you have set up fires.
Therefore consider thy ways, that the Lord may show to thee mercy,
and give thee repentance, if thou turn to him: for the apostle saw such as you coming up,
that should go in Cain`'s way, and Balaam`'s way, in envy and murder,
and love the wages of unrighteousness,
(for will not the pope sell pardons,) and he saw them go in Core`'s way,
such as had the form, but denied the power, who gainsaid the truth,
and these the apostle saw come up before his decease;
and Christ said false prophets should come, Matt.
7. and Matt.
24. and antichrist which had the sheep`'s clothing, but inwardly ravening wolves;
this Christ spoke to his apostles and disciples,
which were to go and spread the truth in all nations, and before the apostles deceased,
they saw that the wolves were come, and they went from them, 1 John 2:4.
and they went into images, and idols,
and he bids the saints and the true church keep themselves from idols;
and they had the anointing within them, and they need not that any man teach them,
but as the same anointing teacheth them: so Christ said they should come,
the false prophets and antichrist, that had the sheep`'s clothing,
and John saw they were come, and these were the last times then,
and such went forth from them, and such were the heretics,
who drew people from the anointing within them,
which anointing the apostle told them would teach them all things.
So the false prophets which went in Cain`'s and Core`'s and Balaam`'s way (murderers
and in sheep`'s clothing,) went forth from the apostles into the world,
the heretics and seducers, them that forbid eating of meats, and marriages,
and in the world they set up their churches, tithes, and temples,
and making ministers by the will of man, which went forth from the apostles,
which were not of man, nor by man, but by the will of God made ministers.
They that went forth from them, set up their churches in the world,
killing with Cain`'s weapons, (were in the dragon`'s power,) and slaying the witnesses,
Rev.
11. and the dragon made war with the woman, the true church,
and she fled into the wilderness, there to be fed for a time and times, and half a time,
and the man-child was caught up to God, then people worshipped the dragon, and the beast,
and the dragon gave his power to him, and he made war with the saints, and overcame them,
and killed them that kept the testimony of Jesus,
and power was given to the beast over all kindreds, tongues and nations; +++[+++mark,]
the beast having power over all kindreds, tongues, and nations,
and the true ministers killed, and the true church fled into the wilderness;
here stands the tongues the beast hath the power over,
the tongues which the world calls their original,
so the beast had power over the tongues, and over the naturals,
when he killed the saints, killed the true ministers,
and then he having power over all tongues, kindreds, and nations,
the beast and his names were set up, his lying signs and wonders;
and all that have lived upon earth have worshipped him,
but who had their names written in the Lamb`'s book of life,
slain from the foundation of the world.
And then the whore she got upon the beast, that was in the dragon`'s power,
and the nations drank the cup of her fornication, and she hath corrupted the earth,
made the inhabitants of the earth drunk.
Now this whore, this false woman, mystery Babylon, this fenced city, this false church,
got up since the true woman went into the wilderness, which all nations manifest,
and kings of the earth drank her cup of fornication,
were not these kings and nations married, to Christ.
The Jews, when they had transgressed the law of God, and played the harlot,
and went among other nations, among the heathen,
so these that went forth from the apostles, to wit, seducers, heretics,
and false prophets, that had the sheep`'s clothing,
they whored and went forth from the apostles, and inwardly ravened from the spirit,
and all nations drank her cup, and she sits upon the waters, and multitudes, and tongues.
Now nations are waters, and people, multitudes and tongues are waters:
(this may all Christendom witness.) Now you may say, is the whore on our tongues,
our orthodox men, the pillars of our church, tongues are natural,
and the whore is upon them, and she drinks the blood of the, martyrs,
the blood of the saints, the blood of the prophets; this whore, this false woman,
this fenced city which is guarded with Cain`'s weapons, the dragon`'s power,
Core`'s gainsaying, and Balaam`'s stumbling blocks, images, and idols,
but no such things were among the apostles, but got up since the days of the apostles,
and the true woman fled into the wilderness, the true church;
so the whore is on people`'s tongues, orthodox men,
(so called) and why not the beast and the whore on your tongues, murderers,
as well as Pilate the murderer?
for when he had murdered Christ, he set upon him Hebrew, Greek and Latin,
and there stands the orthodox men`'s original,
the tongues of which Babel was the original, and which were never ministers of Christ,
then (I say) they cried up that to be the original;
but the word in the beginning was the original, before Babel was;
and when the mother of harlots, the great whore, the beast, and the dragon,
and Pilate is not, nor tongues neither, the word remains, and lives and abides for ever.

Now all the blood that hath been shed since the days of the apostles,
hath been by this fenced city, this whore, this mystery Babylon,
false church that is set up, and the kings of the earth have drank her, cup,
which are in the fornication, by the, beast, and by the dragon, about religion,
since the days of the apostles, and since the true church fled into the wilderness.
So now all the killing and slaying in the whole Christendom, hath been by the whore`'s,
the beast`'s, and dragon`'s power, who hath wrestled with flesh and blood,
who hath racked, tortured, burned, banished, and whipped creatures,
and defaced the workmanship of God, for the creature is the workmanship of God;
and the apostles did not wrestle with flesh and blood, they did not strike at creatures,
but they strived to bring people up into the liberty of the sons of God;
they wrestled with principalities, and powers, and spiritual wickednesses in high places,
and rulers in darkness, and said, there was a glory of the first body,
and a glory of the second, and their weapons spiritual and not carnal;
and Christ was made manifest to destroy the works of the devil, and death,
(where he had his authority, and works which he set up,) and to save men`'s lives,
who came to condemn sin in the flesh, that people by him might become the sons of God;
+++[+++mark that]
and so since the days of the apostles and Christ,
and the woman that hath been fled into the wilderness, all this blood hath been shed,
by the beast and false prophet,
this woman the false church hath been fenced with Cain`'s weapons, murderers,
sacrificers, having the form of godliness; they take of the earth,
and sacrifice of the earth, and these are Cain`'s weapons,
for whatsoever is not from God received, and from his spirit, is from the earth;
and so here in this hath all the righteous blood been shed by these wolves, seducers,
heretics, false prophets, beast, dragon, great whore, mother of harlots,
the false church, who went forth from the apostles, made up this church,
and the true church hath been in the wilderness, and the man-child caught up to God,
and the true prophet slain, so your field is a field of blood,
and much blood hath been shed among you in the whole Christendom,
on pretence of heretics, and blasphemers,
for was not that the pretence that Christ was slain for, and the apostles and prophets;
did Christ and the apostles give any such command, that they should be put to death,
and killed; but on the contrary, love enemies,
and they should be killed that kept his testimony,
and all that dwelt upon the earth should worship the beast,
but who had their names written in the Lamb`'s book of life,
before the foundation of the world.
But they that would raven and tear, who inwardly were raveners, and they that would rack,
and fry with fire the flesh, and mangle the creatures,
which were inwardly ravening wolves, and false prophets which had the sheep`'s clothing,
which went forth from the apostles into the world, such had not the Father, nor the Son,
but they that told the world that Christ was in the sacrament,
and Christ was in the bread and wine, and that was his body, and that was his blood,
erred; for the scriptures say, bread and wine is but a memory and a show until he come;
and saith, examine, and so eat, and then examine again after he hath eaten;
and know you not yourselves, how that Christ is in you except you be reprobates;
and if he be witnessed within, and known within, then he is come,
then what need you have bread and wine to put you in remembrance of him?
These things have got up since the days of the apostles, viz,
setting up all these schools and colleges to make ministers,
setting up these temples east and west, setting up these jewels, beads, pictures,
nunneries, holy-days, crosses, saints`' days,
since the days of the apostles hath this false church, this whore,
who was fenced with Cain`'s weapons, and all the covetous teachers, for filthy lucre,
and for love of money, and all the strikers and soon angry, are all found in her,
such were forbidden by the apostle,
and first they must be proved before they can minister;
therefore is it like that God should send a company of men to destroy his workmanship,
to imprison, destroy, banish, kill his creatures?
Christ came to save men`'s lives,
and the apostles brings them to the liberty of the sons of God,
and these ministers destroys creatures, this false church, and false christians,
so they are not like to bring any to the glory of the first body, nor the second neither,
but now since the days of the apostles, and the woman hath been in the wilderness,
and the prophets and martyrs, and true ministers have been killed,
the false ministers got up and spread over the world,
and this false church is the beast in the dragon`'s power,
the antichrist and false prophet in the beast`'s power,
but now is the man-child brought forth into the world,
to rule all nations with a rod of iron, the kings of the earth, the beast, the dragon,
the whore, which have risen against the saints,
but the Lamb and the saints shall have the victory,
which shall kill and slay with the sword, which is the word of his mouth, and the beast,
and the false prophet shall be taken alive and cast into the lake of fire,
that burns with fire and brimstone, and the judgment of the great whore is come,
this false woman, mystery Babylon, shall be confounded,
her flesh shall be burnt with fire, and the Lamb and the saints shall have the victory,
and the everlasting gospel shall be preached again to them that dwell upon the earth,
to all nations, tongues, kindreds, and people, and the bride, the Lamb`'s wife,
known again, and this is the day the marriage of the Lamb is come,
that the bride and the Lamb`'s wife is known, so the true church known again,
whereby people are brought into that which the apostles were in,
and the age is come that the kindness of the Lord,
and the riches that he showed forth to the apostle is seen,
in this the day of the Lamb`'s power, which over you all is stretched,
and which doth enlighten every one of you that cometh into the world,
with which light you will see all your evil deeds you have done,
all your evil ways you have walked in, all your ungodly words you have spoken,
all your unrighteous thoughts you have thought,
that is the light which Christ the Saviour of the soul hath enlightened you withal,
and loving it, and believing in it,
you shall feel the springs of life spring up in you to eternal life,
and it will be your teacher, but hating it, it will be your condemnation:
this is the word of the Lord to you.

