== For the Emperor of China, and His Subordinate Kings and Princes





From the People of God in England, in English called Quakers.--By G. F.

Friends,--There is a power above all powers, and this power is making itself manifest:
and this is God, whose power this is, who is an overruler, the creator, and former,
and maker of all things in heaven and earth; and gathered together the waters,
and made the sea, and made the earth, and caused it to bud, and bring forth;
who hath all times and seasons in his hand, and placed man in the garden.
But this being lost (his habitation) by transgression; yet God lives,
who is the God of the spirits of all flesh,
in whose hands is the breath and life of all mankind, who hath all souls in his hand,
and would have all to know him, and to worship him, and believe in him,
and to serve him in the spirit, and in the light, for God is light,
and this is the true light which doth enlighten every man that cometh into the world,
which is Christ the Son of God, the way to the Father, the second Adam,
that begets people to God, that brings them forth to God out of the earth, sin,
and the fall, and evil, and transgression: now this is the,
light which Jesus Christ hath enlightened you withal,
that doth let you see your evil thoughts, and the naughty words,
and the evil actions and deeds, and your evil ways you run into, and walk in.
Now this is the light, that doth discover all these,
this which Christ hath enlightened you withal, which is in you,
which if you receive this light, you receive Christ, you receive righteousness,
for the light discovers unrighteousness, unrighteous walking, and actions,
so receive this light, you receive righteousness, and come from unrighteousness,
and this is that which brings you into peace, and unity with God, and one with another,
and with Christ, who upholds all things by his word and power;
but not believing in the light, which every one of you be enlightened withal,
then ye come to be unrighteous, and ungodly, and speak wicked things,
and act wicked actions, and evil deeds.
And then this light condemns you in your own selves, and so then you fight, and quarrel,
and are envious one against another, which if you walk in the light,
you would be in unity, and would be in love one with another,
and so there is the love of God which is shed in the heart, in the light,
in the righteousness, which differs from the love of the world, who hates the light,
and so in that which kills, and hates one another, whose deeds are evil,
and words are wicked, and actions unrighteous; the light in them tells them so,
and that checks them, and condemns them, who hate it,
and they will not come to the light, because their deeds be evil,
and there they fret and vex themselves, when the light checks and condemns them.

And so all ye kings and powers of the earth, God is come to rule,
and his Son Christ to uphold all things, by his word and power,
whose power is going over all nations of men, in whose hand is the breath of mankind,
and hath all souls in his hand, who is the God of the spirits of all flesh,
creating man upon the earth, who gives him life, and breath, and strength,
and all things that are good.
But man being wicked, turns from his Maker, and grieves the spirit of God in him,
who is righteous, and by his unrighteous actions, and deeds,
quencheth the spirit of God in him.
He is come to rule, who hath all power in heaven and earth,
who doth enlighten every one that cometh into the world
that with the light all might believe in the light,
and in Christ from whence it came, and so come into covenant with their Maker,
that so he might take away their sin, and blot it out.
But they that hate the light, and doth not believe in the light,
that makes manifest their sins, and lets them see their evil actions, and evil words,
and evil ways, but goes into unrighteous words, and actions, God will judge,
who hath enlightened them, and the light will condemn them.
Now every one shall come to have a reward according to their deeds and actions,
who hath done unrighteously, and done ungodlily, and done wickedly and unjustly,
the light in your consciences and hearts tells you, and lets you see what you have done,
and that is Christ`'s witness in you, who will judge according to your words,
and actions, and it will tell you when you have done amiss in speaking, and in action,
which if you hear it, it will teach you;
the light which Christ hath enlightened you withal,
who is the way to God the Father of light and life, in whom there is no darkness,
nor no unrighteousness, nor no unholiness, and without holiness none can see him,
who is righteous, just, holy, and true.
So who goes into unrighteousness, and unholiness, and blindness, they cannot see God,
and do the things that is true.
So the Lord is come to reckon with you all,
and that you must all give an account for all your evil ways you have walked in,
for all your evil actions, and unrighteous deeds you have acted, unrighteous ways,
and unrighteous words ye have spoken.
You must give an account to the Lord God, the Lord is come to require an account thereof,
of all your ways, your words, and your actions, which have been acted by all kings,
and emperors upon earth.
Now is the mighty God of power, of heaven and earth,
of all the breath and life of mankind, and the soul, and spirit,
is come to judge all according to their works in this his day,
and every one shall have a reward according to his deeds, whether they be good,
or whether they be evil.
And the cause of all differences in the whole body of mankind, among kings, and emperors,
and people, and professions, and worships, and churches, and priests, and sacrifices,
is that they have been out of the light which Christ hath enlightened them withal,
who is the covenant of God, and transgressed the spirit, in which people have unity.
So the living God, the maker of the earth, and creator of all things,
doth accept of none but who are in the light, which is Christ his Son:
for they that hate the light, and walk in unrighteousness, in ungodliness,
(but doth not walk in the light) they do not walk in fellowship,
for in the light is fellowship with God, and one with another;
and so they that hate the light are in darkness; and not in fellowship one with another;
but in the unrighteous power in which the devil is in, out of truth,
where people kills one another about their religion, or church, or ministry,
or sacrifice, being out of the light, Christ the truth,
which would give them the light of the knowledge of the glory of God,
in the face of Jesus Christ.

