== A Few Plain Words by Way of Query and Information; to the Teachers and People of the Nation.

Friend,--Who art called a teacher of these people, of the ways of God,
how many hast thou brought into it?
Or art thou thyself in it?
How many hast thou brought out of evil ways, or art thou thyself out of the evil ways?
Wilt thou not preach peace to them that curse, swear, that are drunkards, adulterers,
idolaters, envious, strikers, and covetous, mockers, such as follow pleasures,
and live wantonly upon the earth, and liars, cozeners and cheaters,
while they put into thy mouth?
Wilt not thou preach peace to such as these are before mentioned?
And wilt not these serve to put into thy mouth?
And did not the prophets and apostles cry against such who taught the people for covetousness,
and made merchandize of them through it, and feigned words and speeches,
deceived the hearts of the simple?
That such serve not the Lord Jesus Christ, but their own bellies; who mind earthly things.
Did the people do well or ill, in holding up these teachers which the prophet reproves?
And might not the teachers say (who taught for filthy lucre,) it was sad
times when the apostles was come to draw the people from them,
and to reprove them who taught for filthy lucre?
as now the cry is amongst you, who have taught for filthy lucre,
that have preached peace to people while they have put into your mouths,
but now they do not put into your mouths, against whom you prepare war, not peace,
and cry, sad times.
Mic. 3. Where is the man that divines for money now?
Where is the man that prophesies for money now?
And did not Micah cry against such?
Is there none of Micah`'s spirit, thinkest thou,
to bear testimony against such as preach for hire, and divine for money,
and preach peace to people, while they put into their mouths?
Is there none of this spirit, thinkest thou, to cry against these things?
Where is the man now that preacheth for hire, that seeks for his gain from his quarter;
as a greedy dumb dog, who can never have enough?
Did Isaiah well in crying against such?
Isaiah 56. Did the people do well in spending their money for that which was not bread,
and their labour for that which doth not satisfy?
And did they do well that took their money for that which was not bread,
and made people run after that which did not satisfy?
Did Isaiah do well in reproving such, or ill?
and is there none in our age that are as greedy dumb dogs,
who seek for their gain from their quarter,
that makes the people spend their money for that which is not bread,
and their labour for that which doth not satisfy?
and is there none in our age of Isaiah`'s spirit, raised up to cry against such, think ye?
And where is the priest that rules by their means, and the people love to have it so?
Which is a horrible thing committed in the land,
for which cause will God`'s soul be avenged, on such a nation:
and think ye not that God`'s soul will be avenged on this nation
for such a horrible filthy thing as this is committed in the land?
did (and doth) the priests do well in bearing rule by their means?
Did (and doth) the people do well in loving to have it so?
Did Jeremiah do well in crying against those things?
Or those that be in Jeremiah`'s spirit, against them where these things are found?
Did the shepherds do well that taught for the fleece,
from whose mouth the Lord said he would gather them that
have been made a prey upon in the cloudy and dark day?
And is it not the cloudy and dark day now,
that the shepherds make a prey upon the people from
whose mouths the Lord will gather his people?
Will not these shepherds be offended then, and say it is a bad time,
that now they cannot get the fleece?
Is this the time that the clouds and darkness is going away?
Did Ezekiel do well in declaring against such,
that made a prey upon the sheep in the cloudy and dark day,
when they wandered from mountain to mountain?
And do they ill who be in Ezekiel`'s spirit now,
that cry against such that make a prey upon the sheep
for the fleece in the cloudy and dark day,
where the sheep are wandering from mountain to mountain,
and thinks that some mountains are greener than others, and fresher,
on which is better feeding, that hear the sheep are grown on their barren mountains?
therefore must not the promise of God be fulfilled, "`that he will seek his sheep,
and gather them where they have been scattered,`" and feed them himself.
Ezek.
34. Therefore, now is the cry and the call to come off from the barren mountains,
and to feed not among the thorns.
Did the pharisees do well in loving to be called of men masters,
in getting the chief rooms at feasts, and greetings in the markets?
And dost not thou do ill in following the pharisees in these steps,
seeing Christ forbid these things?
And if it be well, dost not thou do ill in not saying, Mr. Paul, Mr. Peter, Mr. John,
Mr. Mark, Mr. Timothy, Mr. Titus, Mr. Matthew,
etc.? Did the common-prayer men do well in putting the papists out of the mass-houses,
and so call it their church?
Did the presbyterians do well in putting the common-prayer men out of the same mass-house,
and call it their church?
and so likewise the independents?
And did not the papists say, "`The gates of hell should not prevail against it?`"
And have not you all done ill in telling the people the old mass-house is the church;
when as the apostle said, "`The church was in God.`"
ThEst. 1:1. Did the papists do ill in selling their mass by the hour-glass?
do ye do well that sell your prayers and preachings by the hour-glass,
and when the glass is run, the time is spent neighbours?
As much as to say, ye have your measure and bargain, give me my due,
that the pope my father gave me?
For Christ and his apostles made no such provision for me, but sent his without bag,
and would not suffer them to preach for filthy lucre; surely is not this the hard master?
but is not this the man that hid his talent, that said so:
that must be bound hand and foot, and cast into utter darkness,
and his talent taken from him; was tithes, midsummer-dues, Easter-reckonings, glebelands,
peter-pence, clerks`'-wages, preaching over the dead for money, marrying people,
christening children for money, the pope`'s provision, he made for ye,
and his dregs you drink, that lay in the bottom of his old bottle;
and are not ye popishly-minded, and Jesuitically affected who uphold these things?
And was not all these times, as Christ-mass, Michael-mass, Lamb-mass, Candle-mass,
and all these days named by the saints`' names,
and all these naming of the steeple-houses, the old mass-houses and colleges,
the pope`'s doing?
Did he well in doing this, or ill?
If well, then why cry ye against him who is your teacher, and call him the whore;
is not this ill-breeding?
Or did the apostles give all these names to them before mentioned?
if so, show us the scripture;
was the scripture given forth for men to make a trade of them,
or for men to believe them, and read them, and come into the thing they speak of?
Have ye the same spirit and power the prophets and apostles had,
who call yourselves teachers?
If not, how can ye sow spiritual things?
How can ye plant vineyards?
How can ye get flocks?
How can ye (thresh in hope, and plough in hope) but plough in vain, and thresh in vain,
and make wildernesses, and but turn against the flock that gives the milk,
not being in the power and the spirit the prophets and apostles were in?
Had the beast, dragon, false prophet, antichrist, mystery Babylon, the false church,
the tongues they set upon, the same spirit and power which hath killed the prophets,
martyrs, and saints,
and them which hath kept the testimony of Jesus since the apostles`' days, unto this day?
Have these been in the same spirit and power the apostles were in?
And again, have these had the same spirit and power the apostles had,
that have their jails, houses of correction, inquisitions, to hold up their church,
worship, religion, ministry, and maintenance?
Seeing the apostle said, "`Their weapons were not carnal, but spiritual,
and they wrestled not with flesh and blood;
therefore are not the other things before mentioned,
the dregs that came out of the pope`'s old bottle,
like unto that which came out of the Jews`' old bottle, against Christ and his disciples,
and John Baptist?
for did they ever put any to death for not putting into the priest`'s mouth?
did they fine or imprison any for not putting off the hat?
did they plunder or rifle the houses of people for not mending their temple,
and paying the clerk for saying amen, and bringing a cushion,
and hanging a priest`'s pulpit; as ye have done now, for not mending the old mass-house,
not paying the clerk that turns the glass, and says amen, and lays the cushion,
and hangs the priest`'s pulpit?
Was this the dregs of the pope`'s old bottle,
or from the spirit of glory that rested on the apostles?
Did the prophet do well that prophesied to the people for handfuls of barley,
and pieces of bread?
were the people wise that gave it them?
Did Ezekiel do ill in crying against such?
Was it not a bad time, they might say,
when Ezekiel cried against them that prophesied for handfuls of barley,
and pieces of bread?
Ezek.
14. And will the priests prophesy now without shocks and cocks of barley, wheat, peas,
and beans, midsummer-dues, glebe-lands, Easter-reckonings, augmentations, etc.
Is not this more oppressive than for handfuls of barley, or pieces of bread?
And do not they now cry bad times,
because the spirit of Ezekiel is raised to bear testimony against these things?
and might not the Jews say,
it was a bad time when the apostles went to bring the people off from the priest,
off the tithe, off the temple, and that Stephen said,
"`The most high dwelleth not there?`"
Did the apostle do well in doing so?
If so, then have ye not done ill, that have set up temples, tithes, and priests,
since the apostles`' days, which God never commanded, which ye have invented,
that cry now, is bad times,
because people are brought off your inventions by the power of God?
Did the apostle do ill in bringing the Gentiles off their temples which they had invented?
Might not the Gentiles cry then, it was a bad time, as ye do now?
And as the Jews called the apostle a pestilent fellow, a sower of sedition:
do you think the Jews would not say, it was a bad time, as ye do now,
that stick in your popish inventions, which have got up since the apostles`' days,
for which ye have no scripture,
that now these come to be cried against by them that comes into the power of God.
Did the prophets, Christ, and apostles, do well in saying,
the children of the Lord should be taught of the Lord;
and the kingdom of heaven was within people; and the word was within them,
and the anointing was within them, to teach them;
and the law was to be put into their hearts, and their minds,
that they need not say one to another, know the Lord:
and the light that shined in their hearts,
was to give them the knowledge of the glory of God, in the face of Christ;
and they that had not the spirit of Christ, were none of his.
And have not you done ill, who have denied this, that says, that ye,
nor no one else hath the same spirit and power as the prophets and apostles had,
neither shall the things before mentioned be looked for in our days?
And have not ye done ill, in keeping people always teaching,
that they may be always paying,
and hath not brought none to the condition the apostles did,
that they need none to teach them to know the Lord.
Heb. 8:1; John 7; Isa.
54; Luke 17; Rom.
8.

Are ye innocent?
Are ye innocent, O ye teachers, (before the Lord) of all the prisoning, and persecuting,
and shedding of the blood of the innocent, which is shed in this your day?

Go all ye gentry (so called) of all sorts,
does not your manners and breeding stand in capping, doffing hats, and scraping, bowing,
and courtesying, and speaking the improper language, you to a single person, as,
your worship, your majesty, your lordship, your honour, your highness, your grace,
your holiness, reverend brother; and such like titles.

All honour, all praise, all reverence, all holiness, all majesty, all dominion is due,
and peculiarly ascribed, and ought to be given to God alone,
who is God over all the unbelievers, who give and receive honour one of another,
for how can ye believe, who receive honour one of another?

Rejoice ye inhabitants of the earth.

G+++.+++ F.

