== Concerning Christ Jesus the Covenant of God

Christ Jesus, the covenant of God with all men, is peace, and life, and light,
and salvation to the ends of the earth, which is our testimony to all men upon the earth,
and is not to destroy men`'s lives, but to save them,
which covenant destroyeth the devil and his works, who is the author of all murder,
plots, and treachery, betrayers of which is of the devil`'s kingdom,
out of the truth and innocency, and the covenant of light and life,
which we have with God, and all people, which separates from sin and evil,
and destroys it, and in that is our peace, which is the covenant,
in which is no murderer, nor plotter, nor contriver, nor betrayer,
so in that we seek the peace of all men, and have all men in esteem,
and seek the good of all men, in that we deny ourselves,
and glory in the cross of Christ, the power of God, which crucifies us to the world,
and their plotters and worldly things, and carnal weapons, and wars,
into spiritual weapons, and war, with which we war with the devil and his works,
who led people from God.
But to plot and confederate, or to raise insurrections, or to gather riotous meetings,
or taking up arms outwardly, we utterly deny, and it is not our principle,
nor is it in the covenant, for it is out of the covenant of life, and peace with God,
and the light with men, though we cannot swear to this:
for he that hath all power in heaven and earth given to him,
commands us not to swear at all, by heaven, nor earth, nor any other oath; but saith,
in all your communication let your yea be yea, and your nay, nay,
whatsoever is more cometh of evil; and to this is our nay,
and so let the punishment be of yea or nay as for an oath;
and our yea is yea to that which is good, and nay nay to that which is contrary.

The Lord God so loved the world, that he gave his only begotten Son into the world,
who hath all power in heaven and in earth given to him, and that all power, and thrones,
and rule and government should be subject to him who is Lord of lords, and King of kings:
and the Lord saith, "`This is my beloved Son,
hear ye him;`" this is the prophet which Moses saith,
"`Like unto him that God would raise up, whom the people should hear, whom we do hear,
that speaks from heaven, at sundry times,
and in divers manners,`" God spoke to the fathers by the prophets,
but now in these last days hath spoken to us by his Son, which is the heir of all things,
upholding all things by his word and power,
that hath all power in heaven and in earth given to him, as he saith himself,
who fulfils the prophets, and ends the Jews`' power, and authority, and the law,
among whom was the oath, and swearing, and first covenant, and not only frivolous oaths,
but true oaths, that endeth the strife, and destroyeth the devil the author of it,
which the apostle brought as a similitude, the substance of it we do enjoy,
(that is to say,) Christ Jesus, to whom the angels must bow: and his command to us is,
"`swear not at all,`" who saith, "`he hath all power in heaven and in earth given to him;
but in all your communications keep to yea and nay,
that are his disciples,`" and his messengers and ministers observe it.
James 5. So if we love him we keep his commandments, and do the thing that he commands;
but if we say we love him, and keep not his commandment, we are liars,
and do not the thing commanded us; and we do know them that love him,
and keep his commandments, in them dwelleth the love of God;
and them that say they love God, and keep not his commandments, are liars:
and our yea is yea, and our nay is nay in that doctrine of Christ,
who is the end of oaths in the law and first covenant,
who are of the promise that remains, and are out of the promises of men that changeth;
and we are out of covenants with men that do change,
and in the covenant of God with him that remaineth and doth not change,
and cannot be broken, and in it is our yea, and our yea is yea in it,
and our nay is nay in it, and if it be not so found among you,
and all people upon the earth from us, let us suffer as much for the breaking it,
as for breaking an oath; for our life is in Christ Jesus,
who was before murderous plots were, that destroys the devil the author of them,
and our nay is against all murderous plotters and contrivers against the king,
or any of his people, or any man upon the earth;
and we would have him and all men to be saved, and come to the knowledge of the truth,
Christ Jesus, and that is our yea, for whose cause and sake we do suffer,
and this we will seal with our lives and estates and all,
for which cause and testimony we have suffered all this while in estates and lives.

Beyond sea, in Holland, the powers of the earth, and magistrates,
that knows our Friends cannot swear for conscience sakes, does not force them,
nor impose fines upon them,
neither imprison them who keeps to yea and nay according to Christ`'s doctrine.
And Christ Jesus saith, "`swear not at all.`"
Matt.
5.

And James saith, "`Above all things, my brethren,
swear not at all,`" James 5. but let your yea be yea, and nay nay,
for whatsoever is more cometh of evil.

And in Turkey, paying tributes, people may have their liberty to worship their God,
and Paul had his liberty to preach in his own hired house at Rome,
where the Emperor`'s seat was, Acts 18:13. though we paying our taxes,
are plucked out by the hair of the head, from prayer out of our houses,
and not suffered to pray together; as the heathen would not suffer Daniel,
and so this is contrary to the apostles, who said,
"`pray every where;`" who met together in their several houses,
and went from house to house. Acts 2:46.
And this was the practice of the church in the primitive times,
which we observe, who were to edify one another, and exhort one another,
and build up one another, and pray for one another,
and they were not to be tied to one place, synagogue, or temple,
which the Jews were only, but sometimes they met on mountains and hills,
and sometimes in houses.

And the church was in Aquila and Priscilla`'s house, 1 Cor. 16:19.
there was a meeting set up in the primitive time.

George Fox.

