== Truth`'s Triumph in the Eternal Power, / Over the Dark Inventions of Fallen Man

[.heading-continuation-blurb]
The Quaker`'s just Allegiance is to hurt none of God`'s Creatures upon the Earth,
and their Supremacy is the Power of God.
Also some particulars of what they own, and what they deny.--By G. F.

In the name and power of the Lord Jesus Christ, we deny all popery,
and the pope`'s supremacy, that holds up popery,
for all things is to be done in the name of the Lord Jesus Christ, as the apostle saith,
who is King of kings, and Lord of lords,
who hath all power in heaven and earth given unto him; so in the name of him,
Christ Jesus, who is risen from the dead, who sits on the right hand of God,
who is the judge of the world, we deny all the pope`'s inventions.

In the name of the Lord Jesus Christ, we deny all their rails, their altars,
their crosses, their crucifixes, their images, their pictures, their representations,
their purgatory that they have invented; we deny all their nunneries,
and their visiting graves, and tombs, and sepulchres, and praying for the dead,
and to the dead.

And in the name of the Lord Jesus Christ, we deny all their ordinations of ministers,
bishops, and cardinals, who are not made as they were in the apostles`' days,
who makes them by oaths, so did not the apostles,
so in the name of the Lord Jesus Christ we deny them all.

And in the name and power of the Lord Jesus Christ, we deny all swearing,
(of all sorts whatsoever) who commands to swear not at all, Matt. 5:34.
who hath all power in heaven and in earth given to him;
and they that have commanded to swear, have been since the days of the apostles,
and since the days of Christ`'s coming in the flesh, they are out of his power.

And in the name of the Lord Jesus Christ, we deny all their observing of days, and times,
and observing of meats and drinks, and their commandments to abstain from the same,
because we perfectly know it is a doctrine of devils, and all their several orders,
and several kinds of habits, distinguishing their several orders,
and all their orders of beggars, their begging friars and priests,
that tolerate begging by a law.

And in the name of the Lord Jesus Christ, we deny all their marrying with rings,
and sprinkling children with the sign of the cross, and bowing to crosses,
and bowing before images, and altars, and all their fasts for debate and strife,
their smiting with the fists of wickedness, which breaks not the bonds of iniquity.

And in the name of the Lord Jesus Christ, we deny all their old mass-houses,
which they call churches, and their idols, and images there set up,
and their hallowing pieces of ground, which they make graveyards on.

And in the name of the Lord Jesus Christ, we deny all their colleges,
and their universities in which they make ministers, by tongues, arts and schools,
contrary to the apostles, who were not made ministers of man, nor by man.

And in the name of the Lord Jesus Christ, we deny giving or receiving of tithes,
the tenths of men`'s estates, which they do that be separated from them,
who are apostatized from the apostles, who denied the Jews`' priesthood,
and the law that made them, Heb. 7.
and the apostles went freely forth without bag or scrip.

And in the name of the Lord Jesus Christ,
we deny all their compelling maintenance of people, and forcing it from them,
and we deny all their persecuting about church, and religion, and ministry,
and all their carnal weapons which they wrestle with flesh and blood withal,
and destroy men`'s lives about church worship and religion.

And in the name of the Lord Jesus Christ, we deny all this,
and the pope`'s supremacy of it, to be contrary to the apostles,
whose weapons were spiritual, and not carnal, and they coveted no man`'s silver nor gold,
but did all things in bounty and love concerning church worship, maintenances,
and religion.

And in the name of the Lord Jesus Christ, we deny all their organs, pipes, whistles,
singing boys, singing of prayers, matins, praying by beads,
and all their lying prophecies, and going on processioning, and their white sleeves,
surplices, tippets, hoods, caps, red gowns, mitres, and the cardinal`'s cap,
and pope`'s triple crown, excommunications, cursing, with bell, book, and candle,
for the scripture saith, "`bless and curse not,`" and his holy water we deny,
and we deny kissing his feet, and all his pardons to be of no effect.

And in the name of the Lord Jesus Christ, we deny all this,
and the pope`'s supremacy of it, knowing it is got up since the apostles`' days,
and is not found in the scriptures of truth.

And in the name of the Lord Jesus Christ, we deny all their inquisitions, and racks,
and doing penance, and all their heathenish traditions,
visiting the sepulchres of the dead,
knowing all these things are contrary to the scriptures; the angel said unto the woman,
"`why seek ye the living among the dead?`"

And in the name of the Lord Jesus Christ, we deny the doctrine of such,
that says bread and wine after consecration is the real body and blood of Christ,
that it is Christ, knowing this is contrary to the scriptures, that saith,
"`concerning bread, and the fruit of the vine, that was taken in remembrance of him,
to show forth the Lord`'s death until he come.

And in the name of the Lord Jesus Christ, we deny all teachers for money,
and marrying for money, and pardons for money, and sprinkling infants for money,
and burying of the dead for money, and the pope`'s supremacy, these we deny,
knowing it to be contrary to the scriptures, and the apostles`' doctrine,
where all things were to be done freely, and in love,
and this doctrine we own of the apostles,
which was before the papists`' and the pope`'s supremacy of these things;
and our allegiance to all men, is to have all men in esteem,
and to hurt no man`'s person upon the earth,
but to do unto all men as we would have them do unto us, and to love enemies,
and love the brotherhood, and keep brotherly fellowship, which is in the spirit,
and is in the power of God, and is in the light Christ Jesus,
which keeps us out of darkness, and over it, in covenant with God,
and unity one with another.

And we are of that principle and mind to hurt no man upon earth, but do good to all,
but especially to them of the household of faith,
and to do all things in bounty and love; that overcomes the evil, that fulfils the law;
and love doth not envy, nor doth not commit adultery, nor lie, nor steal, nor murder,
nor covet, nor commit idolatry; these are the fruits of love, for love thinks no evil,
nor envies not; in that our religion is pure from above,
but where the tongues are at liberty, their religion is vain;
and that wisdom which is pure, is from above, which is gentle, and easy to be entreated,
nor hurtful, nor destructive, but is to the preserving of the whole creation;
and our gospel and our cross of Christ is the power of God;
and our religion is pure from above; that is, to visit the fatherless, and widows,
and strangers, and this is above that which is below, which is vain,
and to keep ourselves unspotted from the world; where fatherless, and stranger,
and widow is not visited; nor the prisons, whereby so many beggars, and fatherless,
and widows are neglected in the world, their religion is vain,
and our church is in God the Father of our Lord Jesus Christ. 1 Thess. 1:1.

And our weapons are spiritual, and not carnal, yet mighty through God,
to the pulling down of the strong holds of Satan; our shield is our faith,
by which we have victory over all that which separates from God,
and our sword is the word of God, and our baptism is that of the spirit,
which plungeth down all corruption that hath been got up since the transgression,
which spirit brings into one body out of the many, into one mind, one judgment, one soul,
one faith, one heart, one mediator, one Lord over all, and by whom are all things,
and brings into one way of life, one truth, one faith,
and brings to drink into one spirit, by which we are all baptized into one body,
of which the body all drink, which brings into one wisdom, one knowledge,
one understanding, the wisdom by which all things were made and created,
with which we must be ordered and directed in all things to God`'s glory,
and the knowledge, which is to know God, is life eternal, and an understanding,
which gives us to put a difference between the precious and the vile,
and this is above all the knowledge and understanding which must perish,
and be confounded, and brought to nought, which we see, glory to the Lord forever,
that lives forever.

And our religion, church, and worship, is not by forcing with carnal weapons,
but by love; knowing that Christ loved us first, of whose body we are, who is our head,
who hath all power in heaven and in earth given him,
which came not to destroy men`'s lives but to save them,
as the apostatized worshippers have done in Christendom.

And our ministers are not made of man, nor by man, but by the grace of God,
which is free, and his gifts which are perfect, by which we minister one to another,
by which the body is edified, and the saints perfected; and our worship is in the spirit,
that mortifies sin and corruption, and in the truth, which the devil is out of,
and his worship, and all the will-worshippers, in that do we worship God,
the God of all truth.

And we tremble at the word of God, by which all things were made and created,
so we work out our salvation with fear and trembling; and we that fear God,
speak often one to another, and unto us the Lord hath hearkened, and heard;
and we forsake not the assembling of ourselves together, as the manner of some is,
but edify one another so much the more, as the light doth approach,
and we build up one another in our most holy faith, praying in the Holy Ghost,
keeping ourselves in the love of God, singing in the spirit,
having no confidence in the flesh, nor in the arm thereof,
but trust in the arm of the mighty God, which doth the valiant acts,
which brings salvation, in which arm we are carried, in which we sing, and rejoice,
and triumph in glory, knowing the King of righteousness,
who hath all power in heaven and in earth given unto him, and among us his shout is,
and this King lighteth every man that cometh into the world,
that all men through him might believe, and become his subjects:
but they that hate the light, and believe not in it,
and will not come to it because it will reprove them, and manifest their evil deeds,
the light is their condemnation; but they that love the light,
and are Christ`'s subjects with the light,
they may see whether their deeds be wrought in God;
and their deeds that are wrought in God, are in peace;
and where everlasting righteousness is brought in, and come forth,
they have their fruits unto holiness, and their end is everlasting life.

And we are not of that birth that is born after the flesh,
that will persecute him that is born of the spirit, and our back, hair,
and cheek hath been always ready to the smiter,
who have been persecuted and killed all the day long, and yet have never resisted,
who denies all persecutors and plotters that would murder and destroy men`'s lives,
but Christ came not to this end, and our swords are broken into ploughshares,
and spears into pruning hooks, and we cannot learn war any more with the carnal sword,
to lift up sword against nations, whose weapons and swords are spiritual, not carnal,
but warring with the devil, and his works, saving and preserving the creatures,
and loving all the creation of God, obeying Christ`'s commands, who said,
"`love enemies,`" and this is according to the love of God,
who gave his Son for a light into the world,
who lighteth every man that cometh into the world,
that whosoever believeth in him should not perish, but have everlasting life;
but who hateth the light, and loveth darkness rather than the light,
he is condemned already.

And such are they that receive not God`'s messengers, and ambassadors,
nor their Saviour Christ, the covenant of light, life and power with God,
in which covenant, we have unity one with another;
and our honour is from above which we seek, and the other honour is below,
which God layeth in the dust; and we cannot respect persons, which if we do,
we are convinced of the law of God as transgressors; and the higher powers we own,
which goes over all sin and unrighteousness, and transgression,
and the devil the author of it, to which higher power,
our souls are subject for conscience sake, which is for the praise of them that do well.

G+++.+++ F.

[.asterism]
'''

Mordecai did not deny the higher power,
because he could not bow in the king`'s court to Haman,
though it was the king`'s command,
and though it was in danger of destroying all the Jews,
it being a point of Mordecai`'s religion, yet Mordecai owned civil government.

And likewise Daniel, and the three children, did not deny the higher power,
who could not bow to Nebuchadnezzar, when the music sounded,
though for it they must be cast into the fiery furnace, by the fury of Nebuchadnezzar,
and this was a point of their religion; and Daniel could not give over praying,
though he was commanded by the king, who would have limited the spirit of God,
that prayers and supplications should not be poured forth to him,
which action and practice of Daniel`'s, that he did, was concerning his religion,
and in relation to God, whom he was to serve and worship, which Daniel was not against,
the civil government, and civil peace;
though he could not yield to the command of the king in forbearing praying,
and quenching the spirit, and making supplication to God,
but he would go to the lion`'s den, rather than obey the king`'s command.

And the Lord manifested his power unto Daniel, and upon the three children,
and also upon their enemies, who persuaded the king against them;
therefore a king is not to hearken to counsellors against them that worship God,
for to God they are as dear as the apple of his eye; for as the scripture saith,
"`touch not mine anointed, and do my prophets no harm;`" this is God`'s command.

Cain killed his brother about sacrifice and worship, Abel`'s being accepted,
and Cain`'s not; and he was the first murderer, persecutor,
and killer about religion upon earth;
therefore the apostle warned the saints against such as go in Cain`'s way,
and exhorts the saints to keep in the love of God,
and build up one another in the most holy faith, and pray in the holy spirit.

But Cain, Nebuchadnezzar, and Haman were full of fury, envy, and wrath,
who persecuted the righteous people of God,
that kept their integrity and their obedience to God, with whom they were accepted;
which condition of each people are recorded for example, and for learning of the good,
and shunning the evil, and the way of the wicked.

And the apostle saith, "`he that is born after the flesh,
persecutes him that is born after the spirit;`" now every man is to read his birth,
and what birth he is of, and his own practice and measure,
and try himself what state he is in.

For this is the law and the prophets, "`to do to every man, and every one,
as they would have them do to them;`" so they would have others have their liberty;
if they would have their liberty in matters belonging to the worship of their God,
and all professing the name of Christ Jesus, they cannot but let others have liberty,
if they have it themselves, or else they do not as they would be done by,
and they do not to others, as they would have others do to them,
if they were in power and authority as others were.

And the apostles are not to quench the spirit, nor to limit the Holy One,
if they meet to worship God on hills or markets, or highways, or hedges, or houses,
or house-tops, or any other place, which practice was not opposed among the apostles,
who were not tied up to any one place; for God created heaven and earth,
which is the God of all spirits,
who hath the breath of all mankind and their souls in his hand.

Therefore, they and you, that would stop people from meeting in highways, or hedges,
or houses, or upon mountains, or from speaking the truth as the apostles did in markets,
against sin; what would you have done against the apostles,
if you had been rulers in their days?
Would you not have stopped them from speaking the truth?
And suffered none but the chief priest to have spoken, and not the apostles,
who met in houses, markets, and other places, who were in a universal power, and spirit,
and wisdom, and declared the everlasting gospel,
by which life and immortality came to light.

And did not the prophets warn the priests both of their oppression, and covetousness,
and their heads, and rulers, and kings, of their sin and transgression;
was not their portion many times among such as they warned, persecution?
And not great benefices: now if these had been stopped from warning and preaching wholly,
or if they had not spoken,
being by the council commanded not to speak any more in that name,
if they had disobeyed the power of God, and obeyed men,
you might not have had that recorded which you have.

Now the apostles did own civil government, though it might have been charged upon them,
for disobeying the council`'s command; and they did seek the good and peace of all men,
as we do and have done.

And because all that dwell upon the earth should worship the beast,
(as may be read in the Revelation) whose names are not written in the book of life,
of the Lamb slain from the foundation of the world;
yet those that had their names in the Lamb`'s book of life,
slain from the foundation of the world, though they could not worship the beast,
yet these owned civil government that keeps the peace.

And now he that leadeth into captivity, must not he be led into captivity?
And in this was the faith and patience of the saints manifest, that worshipped the God,
and could not bow to the contrary worship; now such as leads into captivity,
and gives not liberty, but grieves and quenches the spirit of God,
and limiteth the Holy One, these bring destruction upon themselves.

For God gave to Adam and Eve liberty upon the earth,
though they transgressed his command, though they did transgress his command,
who is the Higher Power, and lost their dominion.

God gave Cain liberty, that persecutor in the earth,
that killed his brother about religion; the Lord gave wild Ishmael liberty in the earth,
in the wilderness, though he mocked and scoffed at the promised seed.

Therefore it is the patience, and the wisdom, and the power of God,
that doth recover man out of the transgression; for God gives man space to repent,
though men in their fury be out of patience, and the mind of the Lord.

Though the woman, the true church fled into the wilderness from the dragon,
the old serpent, as in the 12th of the Revelations,
(there to be fed of God,) who would have destroyed both her, and her man-child,
who was helped by the earth, and had a place prepared of God;
now all these actions and practices are not against the civil power and government.

And the witnesses which prophesied in sackcloth and ashes,
which were the two olive trees which bore the oil to anoint the nations,
and the two candlesticks which bore the light before the God of the whole earth,
who was persecuted and killed, and made merry over,
yet these were never against the Higher Power,
(mark) made merry over by them that sent gifts one to another,
that had been tormented by their prophesying,
which were to prophesy 1260 days in sackcloth.

And it was spiritual Sodom and Egypt which killed them, and crucified Christ,
in whose streets their bodies lie.

Therefore, to consider all who profess, and hath a profession without life and power,
which are to be turned away from, as the apostles commanded;
and the beast and the dragon should make war with the saints, and overcome them,
and have power over all kindreds, tongues and nations.

But here was the faith and patience of the saints, he that led captive,
should go into captivity, and that he that killed with the sword,
should perish by the sword,
shewing the saints`' patience and faith was it by which they overcame,
which were the true worshippers of God, and not ravening,
nor fighting with outward carnal weapons for their religion, for the apostle saith,
"`it is not only given you to believe, but also to suffer persecution.`"

Therefore woe will be to them, that doth persecute their brethren about their faith,
and about their worship and religion, for he is not out of the way of Cain,
who was a vagabond out of the love of God, and out of the law and the prophets;
and not in the love which envies not, and thinks no evil, and is not provoked;
for they that think evil, and are provoked, are out of this love of God,
and the apostles`' doctrine also, they are out of the law and the prophets,
which is to do to all men, as they would have others to do to them.

Again, they that will persecute about religion,
must needs be such that would have power over men`'s faith,
which is contrary to the apostles`' doctrine; who said,
"`they had not power over men`'s faith,
and whatsoever is not of faith is sin;`" and therefore
to bring any man or people by force,
contrary to their measure and gift of faith, is to bring them in sin,
and to unestablish them, for it is the faith which doth establish.

And so what is of faith, is not against the higher power that keeps the peace,
for the higher power which God hath ordained, goes over all transgressors,
and is a terror to the evil doer,
who acteth contrary to the power and spirit of God in themselves;
and is a praise to them that do well,
which are led by the power and spirit of God in themselves, out and from the evil, sin,
and transgression, and for such the law was not ordained.

"`Now the consciences of the weak,`" saith the apostle,
"`must not be emboldened for to do such things which another doth,
which they have not liberty in themselves to do,
lest the consciences of the weak be wounded,
and so they perish through another`'s knowledge, for whom Christ hath died.`"

Now this was not called nor looked upon by the apostle to be true wisdom,
nor good judgment; for when ye sin against your brethren, you wound their consciences,
so you sin against Christ.

So that is a sin against Christ concluded, which wounds the consciences of any, to lead,
or teach, or force, or compel any contrary to their consciences, their weak consciences;
this is a sin against Christ, and a bringing people in a perishing condition,
and to lose the state of a good conscience.

And likewise to lead people contrary to their faith,
(that which is not of faith is of sin) lead, or force, or compel contrary to their faith,
and if they yield, they may come to make shipwreck of their faith and a good conscience,
and then are they unserviceable in their generation, both to God and man.

Therefore,
how often was the testimony of the apostle to keep faith and a good conscience,
and his exhortation to the saints; but how many have made shipwreck of both?
and who keeps faith and a good conscience?
they are not against the higher power, but are subject to that for conscience sake,
which punisheth the evildoer; for that is it which makes disturbances in the nations,
and kingdoms, and to this higher power to be subject for conscience sake,
and not for wrath; for it is the will of God, which keeps down the evildoer,
who makes shipwreck of faith and a good conscience.

Now a king`'s safety, or an emperor`'s, or ruler`'s safety lieth in God,
and his protection is his power, and that which preserveth him, is his wisdom,
the wisdom of God,
being preserved in his spirit to give him true knowledge and understanding,
to put a difference betwixt the precious and the vile,
betwixt such as the law was made for as a terror to, and such as it was not made for,
but to him it is a praise.

And as touching religion, it is for their nobility,
that there be universal liberty for what people soever, let them speak their minds,
let there be places and houses set forth where every man may speak his mind,
and judgment, and opinion forth; for the king had better let men speak it forth,
than let it boil in their hearts and grow to a birth; and those that are sober men,
and wise men, ministers of the gospel, let them inform and instruct, with meekness;
for the man of God must have patience, with spiritual weapons, not with carnal,
by force and compulsion, but with love; and this is the way to overcome,
and let him not quench the spirit, nor limit the people of the Lord,
but stop all such as would do so,
and that would force men to act contrary to their faith and consciences,
which is to commit sin, and to the weakening and perishing of them, as in 2 Cor. 1:8.

And let him be Jew, or papist, or Turk, or heathen, or protestant, or what sort soever,
or such as worship sun, or moon, or stocks, or stones,
let them have liberty where every one may bring forth his strength,
and have free liberty to speak forth his mind and judgment.

For the ministers of the gospel who have the spiritual weapons,
need not fear none of them all, for they have the shield of faith, the armour of light,
and the breastplate of righteousness, they are armed soldiers with spiritual weapons,
and they need not cry out to the magistrates for the outward staff, and sword, and bag,
and jails, and prisons to help them, as the Jews did against the apostles, "`help,
men of Israel, these are the men that turn the world upside down.`"

But ye never read that ever the apostles or Christ did cry,
or make their complaint to any power of the earth,
and it was below their master`'s command, Christ Jesus,
who had all power in heaven and earth given to him,
who commanded them "`to love enemies,`" and so all true christians
are not to persecute them that were contrary-minded to them.

But those now that profess the name of Christ, persecute one another,
these manifest that they have but the form, and not the power,
for if they had the power they would love one another, and enemies also;
for the heathen persecute one another about the worship of their gods,
and the Turks about the worship of their Mahomet, and the Jews about their law,
and the papists about their eucharist, and other ceremonies;
and the protestants about outward ceremonies, judge and persecute one another,
which from Christ they have no command, but to love one another, and to be swift to hear,
and slow to speak, and slow to wrath.

And so they that have gone to persecute one another,
they have laid aside the doctrine of Christ Jesus, such as profess his name,
for his command is "`love, love one another, love enemies,
and have all men in esteem,`" this is the doctrine of Christ and his apostles;
and he that loves is not easily provoked, and thinks no evil, nor envies not,
and he that fulfils the law and the prophets,
doth to all as he would have them do to him; and he that doth not,
is out of the love which doth fulfill the law, and is in the envy, and wrath,
and out of the forbearance, and not in the patience.

Therefore as I spoke before, let there be houses,
and places that all may speak their judgment, and let none be persecuted;
and let the magistrates keep the civil peace, that people may not strike one another,
nor wrong one another`'s persons, but that they shall be patient to speak one to another:
and they that be spiritual-minded satisfy the contrary, and with meekness instruct,
and convince, and convert, and bring to repentance; let them come into them,
and bring in the strength of their treasure; let the ministers convince,
if they have the spiritual weapons, seeing they will not go out to them into the nations,
to the Jews, and heathen, therefore let there be houses for them to come in among them,
"`for this is noble, where there is patience to hear,`" as Paul said to Festus;
likewise Gamaliel, whose moderation appeared to the apostle,
to the stopping them that would have persecuted them,
lest they should be found fighters against God.

Therefore, moderation, temperance, and sobriety is good; but persecution was ever blind,
and so that doth not foresee, nor see things present; and the apostles`' command was,
that they should not judge one another about days and meats,
but that every one should be fully persuaded in his own mind,
that was the counsel of the apostle,
which did not say they should persecute and force about such things,
but judged such as were compelling the Romans to observe such things,
both Galatians and Romans,
and he told them that the kingdom of heaven did not stand in meat, and drink, and days.

And he that in these things served Christ, was accepted of God, and approved of men;
therefore they were not accepted that did judge one another about such things, as meats,
drinks, and days; and he rebukes their judgment and bids them judge this rather,
that they did not lay a stumbling block in one another`'s way;
and this is for all true christians to mind, that be of the true faith and foundation,
which the apostles and saints were in, in the primitive times,
which minds to keep faith and a good conscience.

And Christ saith, "`ye are the light of the world,
ye are the salt of the earth,`" to his disciples, his scholars; and he saith,
"`let your light shine before men:`" therefore if they must have been quenched and limited,
and that the apostles might not have spoken because they were fishermen, and poor men,
but the priests and doctors only have spoken; then had they not obeyed Christ`'s command,
and spread the truth abroad, their Father had not been glorified,
men had not seen their good works, for heaven and earth must pass away,
but not one jot or tittle of his word must pass till all be fulfilled.

So except the righteousness of the christians exceeds
the righteousness of the Jews and the pharisees,
who killed and persecuted about religion,
they shall in no wise enter into the kingdom of heaven,
for the righteousness of the christians is Christ Jesus, whom God loves,
and sent into the world, not to condemn the world,
but that through him they might have life.

And furthermore he saith to his disciples,
"`love enemies,`" and if you love them that love you again,
there is no difference betwixt you and pharisees, for that made and makes the difference,
to love such as did hate them, and persecute them.

And Christ came to call sinners and blasphemers to repentance,
and did not come to destroy men`'s lives but to save them; and he rebuked his disciples,
who would have had fire come down from heaven to consume them that were contrary to them,
and also told his disciples they did not know what spirit they were of.

Therefore they which know what spirit they are of,
comes to the mind of Christ which saves men`'s lives,
and seeks not the revenging nor the destroying of men`'s lives, but as Christ said,
"`Father forgive them, they know not what they do.`"

Therefore they that do revenge themselves, and doth persecute, and be avenged of others,
doth not do as they would be done by, and doth not love enemies,
and doth not do the law and the prophets, and doth not know what spirit they are of.

And Christ saith, "`when ye pray, use no vain repetitions as do the heathen,
who think to be heard through much speaking,`" which many hath said this prayer in Christendom,
but the practice is wanting, "`forgive us our debts, (thus they ask God,
and pray to him whom they have transgressed and sinned against) as we
forgive our debts,`" so they will be forgiven as they do forgive;
now will not this oblige all men to forgive if they will be forgiven themselves?
which will stop all the hands of persecution.

Now where is this practice in Christendom,
men forgiving others`' transgressions as freely as they would have the Lord forgive them,
and this to beg of God, and practise, but this hath been often said,
but the life is wanting, and that is the difference betwixt us and the world, the life,
and such as talk and doth not practise.

And this is the cause of so much strife, debate, and revenge, men cannot forgive,
so they stand bound in their sins, they cannot forgive men that trespass against them,
though nevertheless they would be christians, and say these words with their lips,
"`forgive us, O Lord,
as we do forgive them,`" (this is the form of sacrifice,)
so to have God forgive them their trespasses,
as they do forgive other men their trespasses;
so by this how many willfully and wickedly perish in their sins.

If people be forced and driven contrary to their own consciences,
gift and proportion of faith, to make shipwreck of both,
they go out of the bounds of humanity, and course of nature, into unreasonableness,
and setting the whole course of nature on fire,
where all the members are unruly and out of order, from the tongue, hand, lip,
to the foot; and it is said, the unreasonable man hath not faith;
therefore the way to bring people into unreasonableness,
and to set the whole course of nature on fire,
is to bring and force to act contrary to their own consciences,
and contrary to their measure of faith, and what is not of faith is sin:
therefore to keep people in the reasonableness, is to let them have their faith,
and not act contrary to it, nor contrary to a good conscience,
that keeps them both in reasonableness, and nature in its course,
and their members in order.

Who are in the wisdom of God, that is pure and gentle from above, mind these things.

G+++.+++ F.

[.asterism]
'''

=== Concerning the Spirit.

A manifestation of the spirit is given to every man to profit withal, 1 Cor. 12.
now every man profiting is in the spiritual things, and the things that be of God,
and out of the spirit no man profiteth,
though he profess all the scriptures from Genesis to the Revelations,
nor are not like to see the spirit that gave forth scripture, nor know them,
for the spirit is that which doth supply every man`'s want,
so all to stand steadfast in one spirit, for in that is the fellowship of the spirit,
and the fruit of the spirit is goodness and righteousness;
therefore be you filled with the spirit, the helmet of salvation,
the sword of the spirit, by which you war with all,
against that which causeth the enmity, and by which you are circumcised,
who put off the body of sin, and the flesh that is gotten up by the transgression,
in which spirit have ye the unity and strength, by which spirit ye sow to the spirit,
and come to reap life eternal, through which spirit you have an habitation in God,
and they that are led by the spirit are not under the law,
neither do they fulfill the lust of the flesh, which the law takes hold upon,
for the spirit doth mortify the lust of the flesh, which the law takes hold upon,
and that spirit doth refresh, and they that are led by the spirit of God,
they are the sons of God, and the last Adam was made a quickening spirit,
to quicken from that, and out of it, which the first Adam fell into, the earthly,
and so by one spirit are ye baptized into one body,
that plungeth that down the many bodies; so being renewed in the spirit of your minds,
and filled with the spirit, the fruits of the spirit is goodness, righteousness,
and so are made all to drink into one spirit,
and all that doth drink into this one spirit,
come into the manifestation of it in their own particulars;
by it they come to know baptism, circumcision, true worship in the spirit and truth,
and the Lord God the Father of spirit and truth;
and by this spirit they know all the seducing spirits, the spirits of error,
the spirit of witchcraft, and spirits that be unclean;
and by this spirit by which they are led into all truth,
they try the spirits that gets the saints`' and prophets`' words,
and is not in the spirit that they were in that gave them forth,
and so have not unity with them; and by this spirit have the saints discerning,
and in it have they fellowship, and in it do they sing,
and it gives them the true wisdom, it is called the spirit of wisdom,
and in it they come to walk, and so then not to fulfill the lust of the flesh,
that be in the transgressing spirit, under the spirit of the power of the air,
that rules in the children of disobedience;
and they that have not the spirit of Jesus Christ are none of his;
in this spirit are the mysteries spoken, and in it is the fight,
and that which doth unseal and open the spirit of understanding and knowledge,
that gives both to understand and know,
and this must every man come to know in his own particular,
for woe is unto them that are covered, but not with the spirit,
they are covered with transgression, sin, and iniquity, death and darkness, and grieve,
vex, quench, and transgress the good spirit of God in their own particulars,
and so grow up in the spirit of strife,
and hasten and bring forth folly and perverseness, and their own sorrow,
it is that spirit that God will cut off, which hath kept out the steadfastness from God;
and the Lord saith, "`I will pour out of my spirit on all flesh,
and my sons and daughters shall prophesy,
and the spirit of the prophets is subject to the prophets, so there is unity;
and except a man be born of water and the spirit, he cannot enter into the kingdom,
though they may profess all the scripture of the saints,
given forth from Genesis to the Revelations.
In the first birth following his own spirit he sees nothing; and the apostle saith,
"`pray always in the spirit, by one spirit have access unto the Father,
and quench not the spirit, and I will pray with the spirit, and with the understanding,
that all supplications, prayers, intercessions, giving of thanks be made for all men,
for rulers, and them that be in authority.`"

The spirit helpeth our infirmities, for we know not what we should pray for as we ought,
but the spirit itself maketh intercession for us with groans which cannot be uttered;
and he that searcheth the heart, knoweth what is the mind of the spirit,
because he maketh intercession for the saints according to the will of God:
so to pray always in the spirit, all supplications, and for the saints;
so they that pray not in the spirit, cannot intercede to God the Father of spirits,
for it is that which maketh intercession, and helpeth the infirmity;
and the flesh is weak, but the spirit is ready;
and in that which is weak lieth the infirmity,
and men know not what they ought to pray for,
but the spirit which gives them the understanding, in which they are to pray,
which makes the intercession to God, in which people must pray always;
all supplication must be in the spirit, and all giving of thanks for all men,
and praying for all rulers that be in authority, and supplication for them,
and prayers and thanks, the spirit lets see their mind in,
and this prayer in the spirit is acceptable to God,
which makes intercession to him the Father of spirits, according to his will,
for the spirit is that which helps the infirmity, in which they must pray,
and make intercession, and give them the understanding to see the flesh is weak;
which infirmity of flesh that is weak, they have a form,
and its own form of prayer without the spirit,
and think to be heard for their much speaking, which is called babbling by Christ,
and not justified, for the justified are in spirit, for it is it they must pray in,
which gives them both the knowledge and understanding, and intercession, and is a helper,
which the other praying with death, flesh, out of the spirit,
which thinks to be heard with much speaking, which is called babbling,
which maketh no intercession to God, and is without the understanding,
and this prayer is judge amongst christians and Jews, by Christ;
and God overturns who is a spirit, and must be interceded unto in the spirit,
and in the spirit supplication, prayer and thanks is heard of God,
for the spirit is the light by which they must see and ask according to his will,
who would have all men to be saved, and come to the knowledge of the truth.
If all men would come to the knowledge of the truth,
they must come to that which doth reprove them, and lead them into all truth,
and the Comforter; and none can lift up holy hands, and pray without wrath and doubting,
but who are in the spirit that makes intercession to God;
and they that pray not always in the spirit, pray by the letter that kills,
and do it not by that which giveth life and intercession to God,
neither have they holy hands, but are full of wrath and doubting;
neither are they ministers of the spirit, nor know the ministration of it,
which is more glorious than that of the Old Testament, which was glorious in its place,
but the ministrators of the letter, that professeth themselves beyond the law,
and doth not pray in the spirit, run all on heaps about the words, out of the spirit,
and are the killers; for they that pray in the spirit,
and sing in it through the spirit and the faith, obtains the promise of the living God;
and they that are in the spirit, are not under the law, nor under the curse of it,
but in that which doth fulfill it; and the spirit brings them all from the rudiments,
traditions, and ordinances that be in the world; they that walk in the spirit,
and are in the spirit, walk over them all, and see over them all; and the prophet says,
"`thou gavest them thy good spirit, to instruct them, and they rebelled against it.`"
Nehemiah 9:20.
So they that rebel against God`'s good spirit,
rebel against the God of heaven, the King immortal, and go into error and ignorance,
and from the good spirit of God, which would instruct them, and give them understanding,
in which they must pray and worship, in which they must have access to God,
so these are in the spirit of error, and the spirit of antichrist,
and the spirit of bondage, the unclean spirits, and come to be the familiar spirit,
and of divination, the proud spirit, and the spirit of whoredom, and perverse spirit,
and spirit of jealousy,
and come to be the frogs that go abroad to deceive and creep under every mountain,
and hill, and rock, croaking with their unclean spirits like frogs,
become the evil spirit,
which the saints of the living God must try with the living spirit,
who have the knowledge, the spirit of judgment, the spirit of meekness,
the spirit of understanding, the spirit of glory, the spirit of grace and supplication,
to supply the wants of all people that want, whatsoever wants they be;
which spirit brings them over all unclean spirits of error from God`'s good spirit;
nevertheless the spirit of glory resteth upon the
sufferers that are clothed with a meek spirit,
that have a new spirit but they that be in the spirit of error cannot pray, nor sing,
nor praise, nor give thanks, nor make intercession to God the Father of spirits,
nor cannot worship God in the spirit,
nor have fellowship in the spirit that be erred from it,
and such spirits are tried by them that are in the spirit of wisdom, understanding,
judgment and knowledge, who pray in the spirit, in which is their fellowship in that,
wherein they make intercession to God, they see the wants of all people,
through which spirit they make intercession for them, and this tries spirits and hearts,
who hath a new heart that serves God in a new spirit, and in it are patient,
and have the spiritual weapons, filled with the spiritual wisdom,
to war with such as have departed from the spirit, and erred from it,
being in the spirit of truth, comprehending the spirit of error, which bondageth,
that are blind from the ways of God and fellowship,
that corrupts and cumbers the ground and earth;
but people must pray always in the spirit,
for the manifestation of it is given to every one to profit withal,
and the spirit makes intercession to God for them,
in that they have profiting in their prayers,
and the spirit is the testimony of Jesus the spirit of prophesy,
by which they see what they are to pray for,
and give the man understanding of the supplication, and necessity,
and such come to be sealed with the holy spirit of promise,
and filled with both spirit and promise, which they that grieve the spirit,
and err from it, and quench it, they cannot pray in, they are not sealed,
they have not their Father`'s mark in their forehead,
and they are not to be believed though they have all scriptures,
being erred from the spirit that gave it forth,
their spirits are tried not to be spiritual men,
but are tried by the spiritual man that trieth all things:
and they that came to drink of the spiritual rock, Christ,
and receive the spiritual gift from God, and are zealous for them,
they come to the spiritual body, and to be blessed with spiritual blessings,
and to speak to one another with new tongues,
and filled with the spirit of understanding, and built up together a spiritual house,
to offer up spiritual sacrifices, these know, feel, fathom, try,
and understand all the spirits that be in the world, by the spirit of the living God;
they who have erred from his spirit in their own particulars, cannot sing, pray,
give thanks acceptable to him, nor worship him, and are out of fellowship with him;
he grieves, quenches, rebels against the spirit that should give him understanding,
and grace, by which he should pray and make intercession unto the Lord for him,
in which he should worship God, and in which he should have fellowship,
there be the unclean spirits, who like frogs can creep in every hole, rock, and mountain,
and bondageth both themselves and others, so cannot serve God in the new spirit,
but are proved proud, heady, and high-minded, amongst the spirits of error,
drawing and seducing others into their own spirits, without understanding,
without wisdom, without fellowship, without the worship of God, without true praying,
without true singing, without true giving of thanks, without patience,
and meekness of spirit, of grace, and a contrite spirit, without zeal, without promise,
and without the truth, and cannot come into it,
without the spirit of truth leads into the truth, without fruits of holiness,
without love, the true love, in the spirit of slumber, and they that are,
err from the spirit of God in their own particulars, want all these things,
and are not subject to the Lord, neither to one another;
and they cannot make supplication and prayer for all men to their conditions,
but overthrow their prayers and their spirits, that be erred from his spirit,
for they that be joined to the Lord are one spirit, and are in fellowship with the Son,
and with the Father, and have the spirit of understanding, and wisdom, patience,
and meekness, and are arrayed and adorned with it; and blessed are the poor in spirit,
though never so poor, from it you will inherit the blessing and the promise,
and it will make intercession for you to God,
and that hath the promise that makes the intercession to God,
and that prayer and supplication is received of God and accepted,
and that spirit that makes intercession to God,
in that he is worshipped and that brings the grace and salvation,
and in that spirit that makes intercession to God the spirit,
in that spirit is God served in a new life, and things received according to his will,
and that gives the spirit of understanding and wisdom to try other spirits,
in that is the fellowship, the spirit which doth not make intercession to God,
God regards not their prayers, nor thanks, nor worship, nor fellowship,
it is out of the true understanding, knowledge, and wisdom,
and the spirit that intercedes to God.

[.asterism]
'''

=== Concerning Faith.

The faith heals, being obedient to it,
and the true church is established in the faith that gives victory,
and access to God through the righteousness of faith,
and having the seal of the righteousness of the faith, and by faith are we saved,
and faith remains, and we are satisfied, and come to walk in the steps of faith,
having the word of faith in the heart and mouth to obey and to do it,
and then by faith thou standest and walkest, and by faith thou art justified,
by the spirit of faith, and there is one faith, which faith is unfeigned,
and in the faith there is great boldness and godliness,
and the edifying is in the faith which gives victory and access to God,
and in which faith all must ask of God,
and in the faith is both stability and steadfastness,
and in the faith is the heavenly riches received from God, I say,
in the faith of God`'s elect;
so let every one be faithful according to his proportion
of faith that God hath given to him;
and as God hath dealt to every man a measure of faith, in that let him walk,
and keep in the unity, and edify one another as faithful witnesses, and ambassadors,
and messengers, for God is faithful, that hath promised;
Stephen full of faith and of the Holy Ghost, all his disputers, and the council,
they had no other weapons against him,
but to deliver him up to the stoners to stone him to death;
and by faith the apostles overcame all disputers, stoics, epicureans,
and the wise philosophers, that he made them run out, and called him babbler;
and by faith in the power of God have many gone as signs in sackcloth, and haircloth,
and naked, among all the naked professors,
whose coverings have been as rough as sackcloth, and haircloth,
and so through faith in the power have ye seen a great deal of
their coverings taken off by such as have been worse than themselves,
and by faith in the power of God have many went with
ashes on their heads as signs among professors,
that have been covered, and not with the spirit of the Lord;
and they have seen a worse than themselves thrown dirt on their heads,
and covered them with dirt and darkness,
amongst whom they went with ashes on their heads;
therefore sing and rejoice ye prophets and messengers of the most high God,
and every one have the faith in yourselves, that you may meet in that,
for a faithful man abounds with blessings, and all the commandments of God are faithful;
and the righteous saith, "`my eyes shall be upon the faithful,
and the Lord preserves the faithful,
and a faithful man fears God;`" "`well done,`" saith Christ to the faithful servant,
for "`thou hast been faithful in a few things,
I will make thee ruler over much;`" be faithful in all things to God,
and all men upon the earth, for God is faithful, by whom ye are called;
and having obtained of his holy riches for to be faithful, for God is faithful,
who will not suffer you to suffer beyond your measures,
nor to be tempted beyond your measures;
so happy are you to whom the Lord hath committed his treasures, who counts you faithful,
for if people believe not, yet God and Christ still abide faithful;
therefore you that believe, be blameless and faithful children,
holding fast the faithful word, for God is faithful, who hath promised;
your souls every one committing unto the faithful Creator of all things;
so if you believe in the light by which you see your sins, and confess and forsake,
he is faithful and just to forgive you all your sins,
having a faithful witness in heaven, Christ Jesus,
that every one may come to see the end of your faith, the salvation of your souls;
for your faith and hope standing in God, virtue and knowledge is increased,
and in your faith, which gives victory and access to God, have you comfort,
and your trial of that work of patience,
and the trial of that being more precious than gold that perisheth, being found faithful,
and that it may flow over the world, giving victory over it, and its foundation,
from which the Lamb has been slain of the world, that lies in wickedness.

By faith was Enoch translated, and so by that faith are all from the death to the life,
from the darkness to the light, into the endless life, and so by faith comes to stand,
in which they come to increase in faith,
the faith makes them heirs of God and the promise,
which faith gives them victory and access to God, over that which separates from him;
and faith, hope and charity abideth, and they that are of faith,
are blessed with faithful Abraham,
and have victory over that which makes a separation betwixt God and man,
and which brought the curse, who are of the household of faith,
and so knows the unity of the faith, and one Lord, one faith, and one baptism;
so faith keeps the good conscience, being in the mystery held in a pure conscience,
looking to Jesus the author of it and finisher, by which faith you are saved,
you are sanctified, you are justified, and the just lives,
which gives the victory and access to the Lord,
over that which brought the separation from God, and condemnation in uncleanness,
and not pure; they who purify their hearts by faith witness this;
and the fruit of faith which works by love, and gives victory over the enmity;
so fight the good fight of faith, which is your shield,
for all they that have made shipwreck of it,
fight against it with carnal weapons and shields, canes or clubs; therefore,
above all things take the shield of faith, and put on the breastplate of faith,
and then stand with thy shield, and breastplate, and helmet of salvation,
which is the power of God, and the faith of the gospel the power of God,
and the cross of Christ the power of God,
and thy faith in the grace of God which bringeth salvation,
and then hold fast the profession of thy faith,
for without faith it is impossible any should please God,
for they be not in that which gives victory and access to him, which brings plagues,
wrath, woe, vengeance, and condemnation,
and all their offerings and sacrifices God doth not accept,
not being in the faith that gives access to him; how should he receive their sacrifice,
how can they bring them to him,
if they be not in that which gives them victory over that which separates from him,
and by which they have access to him?
How should they have access to him, and how can they please God,
not being in that which gives victory over that which doth displease him?
The Lord will render to every man according to his faithfulness;
so the preaching of faith which gives the victory and access,
in which is the unity and fellowship,
in which every one shall know his breastplate and shield to keep off and fight withal,
that which made the separation betwixt them and God,
through which he shall have the victory; and so who are come to this,
are come to the hearing of faith, and going on in the way, and on in the victory,
on in the unity, and are come to the end of the law, and to the hearing of faith,
there the spirit is received, and faith is in the conscience,
and by their faith they have peace with God,
having victory over that that made the separation betwixt them and God,
and so the heirs of righteousness by faith, and are to inherit Christ Jesus.
Gal. 3.
