== A Declaration to the Jews,





For them to read over: in, which they may see that the Messiah is come,
according to their own Prophets, and Gabriel the Angel,
and according to their own Number of Time and Years, out of Daniel 9.--By G. F.

From the building of the temple at Jerusalem, spoken of by Daniel in the ninth chapter,
was seven weeks, or forty-nine years, in which the temple was built;
from the finishing of which, there was sixty-two weeks,
which is four hundred and thirty-four years, until the baptism of Christ;
and after the sixty-two weeks, there was one week, in which the Messiah should be slain,
but not for himself; and the people of the prince that should come,
should destroy the city, and the sanctuary that was built,
and the end thereof should be with a flood,
and unto the end of the battle it should be destroyed with desolation,
and he shall confirm the covenant with many; for in one week,
in the midst of the week he shall cause the daily sacrifice to cease,
which death was about three years and a half after Christ was baptized;
for says the angel Gabriel, in the last verse of that ninth chapter,
"`And in the midst of the week, that is three days and a half,
he shall cause the sacrifice and the oblation to cease, etc.`"
Christ`'s sacrifice ends all other sacrifices,
and the covenant being confirmed with many of his disciples,
they preached it up and down in the synagogues and temples, and among the heathen:
and Christ preached of the destruction of the temple after it was built; the Prince,
the Messiah, he preached the destruction of the temple, that it should be thrown down,
and not one stone left upon another,
and it was thrown down (according to his prophesy,) by the heathen;
and he said "`Jerusalem should be compassed about with armies, and trodden under foot,
and they scattered abroad over all nations,`" which thing came
to pass (according to his prophesy) and never since had ye a prophecy
that you should be gathered again to outward Jerusalem,
and that your walls should be built again.

And now if you do believe Moses, Jeremiah, Samuel, Isaiah, Ezekiel, Zachariah, Daniel,
and the rest of the prophets, and Gabriel that spoke unto Daniel,
ye must believe that Christ is come in the flesh; they prophesied of him,
and set the time, and set the year that he should come, which time and year is over,
and come, and past, according to the prophets`' and angel`'s words,
as you may read what Gabriel said to Daniel, who numbered the time of your captivity,
as Jeremiah and Daniel numbered the time of building the temple,
and numbered the time in which the Messiah should come, the Prince.

And now if Gabriel spoke truth, and Daniel and the prophets spoke truth,
then you must believe that the Messiah is come, according to their words.

And whether or nay one did not come in that way according
to Gabriel and Daniel and the prophets,
that was called a Messiah and a Prince?
Whether the city was not built, and the people were not gathered before he came,
and after he was come, whether such an one was not cut off according to the week,
and after your city destroyed, and temple, and you scattered over all nations,
according to the Messiah`'s prophesy?

And whether or nay his covenant was not confirmed with many that were his disciples,
that preached up and down the one offering after he was cut off?

And whether or nay God did not prepare him a body,
according to David`'s prophecy to do his will,
which God accepted more than burnt offerings, and sacrifices and oblations,
who put an end to them,
for the overspreading of the abomination that made the desolation,
until your offerings were consumed, and the place where you offered?

And whether or nay he did not come poor, riding upon an ass, the foal of an ass,
according to Zachariah`'s prophecy.
Zach.
9+++.+++ Riding into Jerusalem,
who should let the prisoners out of the pit where there was no water,
who should give the water to the thirsty, and bread to the hungry?

And whether or nay you did not hide your faces from him, he being a man of sorrow,
and acquainted with griefs, according to Isaiah`'s prophecy?
Isa. 53.

And whether or no you did not stop your ears, and blind your eyes, that you heard not,
nor see not when he came, and so you have lost the number of time?

And whether or no David`'s prophecy is not fulfilled upon you, who said,
"`let their eyes be blinded, and their table be made a snare and a trap,
and they bow down their backs always,`" as you have done under every government?

That when he did come who was David`'s Son, that David called Lord the King of glory,
your gates were not set open to let him in, but his place amongst you was a manger.

And did not Malachi prophesy of him, and was one of the last prophets amongst you?

And did not John come to prepare the way before him, who baptized multitudes of the Jews,
who was the son of Zachary,
who was put to death by Herod at the pleasing of his daughter`'s dancing,
whom he beheaded in prison on his birthday?

And did not you persecute many of his disciples,
and cast them into prison for witnessing Christ the Messiah, the Prince among you,
who was come, according to Moses and the prophets, Gabriel and Daniel?

Did not they often tell your fathers that their eyes were blinded, and their ears dull,
that they heard nor saw not?

And did not the Messiah, the Prince tell you, in the days amongst your fathers,
that your house should be left desolate, so are not all your temples, sanctuaries,
and chief places of offerings, have they not all been desolate, and have been ever since?

And did not he say unto you that you should see his face no more, until you said,
"`Blessed is he that cometh in the name of the Lord?`"
Therefore if your houses be left desolate there was never
no promise of the Lord that they should be built again;
but happy are any of you who can say,
"`Blessed is he that cometh in the name of the Lord,`" who receives him,
receives the end of offerings and sacrifices.

And did not Moses say "`like unto him would God raise up a prophet,
him should they hear in all things; and he would raise up a prophet of their brethren?`"

And the prophets and David witness that the Messiah should
come of the seed of David and Abraham according to the flesh.

And was not Joseph and Mary of the household of David,
and was not his name called Emmanuel according to Isaiah`'s prophecy? Isa. 7:14.


And born in the year according to Daniel and Gabriel?
Dan. 9.

And did not David say "`he would not suffer his holy one to see corruption,
nor leave his soul in hell?`"
he saw the travail of his soul, and therefore was satisfied,
according to Isaiah`'s prophecy.

Therefore, after you had killed him by a shameful death upon the cross, and buried him,
did not he rise again and saw no corruption, whom neither death, bonds,
nor grave could contain nor hold?
Though the priests gave the soldiers money to say
that his disciples stole him away by night,
who now remains in heaven at the right hand of God until the restitution of all things,
who after his resurrection was seen of many brethren, and many witnesses,
who were the witnesses of his resurrection amongst your forefathers,
and amongst whom (your fathers) he wrought many miracles, and did many wonders,
to the astonishment of the very heathen, and of many of your forefathers,
yet their hearts being hardened, and their eyes being blinded, and could not,
nor would not, neither see nor believe,
therefore did he pronounce the woes against you which is come upon you;
and he doth enlighten every man that cometh into the world,
and is that which checks you for sin and evil,
which if you believe in the light you come to receive him that all the prophets, Moses,
and Gabriel spoke of, who is the Prophet that is to be heard,
and King that Daniel prophesied of, whose kingdom is an everlasting kingdom,
and dominion and everlasting dominion that hath no end,
who is the stone cut out of the mountain without hands,
that dasheth all that is contrary to it, and becomes a great mountain,
for you are hewing and cutting, as all other heathens upon the earth,
and making mountains with hands, and so nations or kingdoms;
this stone without hands that is cut out of the mountain without sword and spear,
breaks all to pieces, and it becomes an everlasting mountain,
and an everlasting kingdom and dominion,
whereby swords and spears are broken in ploughshares and pruning-hooks,
whereby nation shall not lift up sword against nation,
neither shall they learn war any more.
Mic. 4.

And Jeremiah prophesied of your captivity seventy years, and he said,
"`when you were brought into the land,
and all nations should be gathered to it in Jerusalem,
and when ye increased and multiplied in the land,`" in those days, saith the Lord,
"`They shall say no more the ark of the covenant of God,
for it shall come no more to be minded, neither shall they remember it,
neither shall they visit it, for that shall be done no more.`"
Jer. 3.

And Jeremiah saith in the 31st chapter, "`Behold,`" saith the Lord,
"`the day cometh that I will make a new covenant with the house of Israel,
and the house of Judah,
not according to the covenant that I made with their
fathers when I took them out of the land of Egypt,
which covenant they broke;
but this shall be my covenant that I will make with the house of
Israel after those days of their captivity and return,
I will write my law in their heart, and I will be their God, and they shall be my people;
and they shall not teach every man his neighbour, and every man his brother, saying,
know the Lord,
for they shall all know me from the least to the greatest of them,`" saith the Lord,
"`for I will forgive their iniquities,
and remember their sins no more;`" now this is the Messiah,
and this was promised and prophesied how after he should come into the land,
which came into the land of Jerusalem, according to Jeremiah, and Daniel, and Gabriel,
and Ezekiel, their words and prophecies.

And Jeremiah saith, in the 33d chapter, "`after they were carried away captive,
that they should be brought again into the land, and the Lord promised that good thing,
he would cause his branch of righteousness to grow unto David,
and he should execute judgment and righteousness in the land,
and in those days Judah shall be saved, and Jerusalem shall dwell safely,
and he should call and say here is the Lord our righteousness +++[+++mark,]
that calls Judah and calls Jerusalem, that makes them to dwell safely.`"
And thus saith the Lord,
"`David shall never want a man to sit upon the throne of the house of Israel;
neither shall the priests and Levites want a man for me to offer up the burnt-offerings,
and the meat-offerings,
and to do sacrifice continually;`" now this was to be after their coming into the land,
and after the Messiah was born, and the branch of righteousness sprung,
and he should sit upon the throne of David,
and execute judgment and righteousness in the land;
then the priests and Levites should have their men to offer meat-offerings,
and burnt-offerings, and sacrifices continually, and this was after Christ was come;
but when he was offered up, a sacrifice himself, that one offering once for all,
who judged and executed judgment amongst you before he was offered up,
both among the Jews and at Jerusalem, when he I say was offered up,
he caused those things (the offerings,) to cease,
and fulfilled them according to Gabriel`'s words and Daniel`'s prophecy,
and ends the priesthood, the Levitical priesthood,
who came not of the tribe of Levi nor Aaron, but of Judah, that lion;
so in one week in the midst of the week he should
cause the daily sacrifice and oblation to cease,
and so this was the covenant prophesied of by Jeremiah,
and this was he that Moses prophesied of,
like unto him would God raise up a prophet which the people should hear.

And Stephen witnessed him before the council in the days of Herod,
whom your fathers caused to be stoned to death.

And after this covenant was come, you should say no more the ark of God, nor mention it,
nor let it come into your minds, this was after ye were come into the land;
and Zachariah`'s prophecies, who prophesied of the destruction of Jerusalem,
who prophesied again, that Jerusalem should be safely inhabited,
and they that fought against Jerusalem should come up to worship year by year,
and keep the feasts of tabernacles;
and the Lord would smite the heathen and Egyptians that came not unto Jerusalem,
that came not up to keep the feast of tabernacles;
and the pots in the Lord`'s house should be like the bowls before the altar,
and every pot should be holy, and all they that sacrificed, should come and take of them,
after the people were come to worship at Jerusalem,
and the mountain which was a place of worship; when Christ said to the woman of Samaria,
"`the time was come and now is, that neither at Jerusalem, nor at this mountain,
but they that worship the Father, shall worship him in spirit and in truth,
for such the Father seeketh to worship him.`"

Now this was before Christ was offered up that ends the offerings, altars, sacrifices,
feast of tabernacles, for the Lord should come, my God and all his saints;
and the Lord should be king over all the earth.
And when Jerusalem was safe, and nations came up to it,
there was the feast of tabernacles to be kept, but after Christ was offered up,
though those things were practised in the days of his flesh, while he was upon the earth,
and did not cause them to cease until he was offered up, and then he ended them;
and then he prophesied of the destruction of Jerusalem, and the walls,
and your scattering over all nations,
and did not prophesy of your bringing back again to offer,
and to sacrifice and keep the feast of tabernacles again at Jerusalem,
and did not say that your outward worship should be set up again at Jerusalem.

But the scattering was for the bringing in of the Gentiles,
according to the promise of God by his prophets;
"`I will give him for a covenant and a light to the Gentiles,
and he shall be my salvation to the end of the earth;`" which many of the Gentiles
now have received and believed the covenant of light promised to the prophets,
though many of them do not live the life,
through whose lives and fruits the name of the Messiah is dishonoured,
and the unbelievers hardened through them that profess him in words,
and deny him in life; nevertheless,
the foundation of God and the new covenant standeth sure,
and his promise agreeable to all his prophets, and Gabriel`'s words,
as you may number Daniel the ninth yourselves,
that in such a time the Messiah was to come.

And whether or no such an one was not born in the same year,
when all Jerusalem was in an uproar at his birth;
Herod gathered all the chief priests together,
and demanded of them where Christ should be born, and they said, in Bethlehem of Judah,
for thus it is written by the prophets;
so whether or no such an one did not come according to the prophets`' words,
and suffered according to his words, and his garment parted, and was cast lots for,
according the prophets`' words,
and one of his own disciples betrayed him for thirty pieces of silver,
according to Zachariah`'s words.

And as it is written,
blindness happened unto Israel until the fulness of the Gentiles be come in,
and so all Israel shall be saved, as it is written, "`The deliverer shall come unto Zion,
and shall turn away ungodliness from Jacob, and this is my covenant with them,
when I shall take away their sins;`" for that is it which blinds,
and the light which is the covenant, is that which opens the eye,
in which the Jews and Gentiles are one.

So the Lord will save now through the blood of his covenant, and the offering,
the sacrifice Christ Jesus, who destroys the devil, the old liar, and the author of sin,
who hath imprisoned his people, and brought them into the pit,
where they have wanted the water;
and he the Covenant and Messiah brings the prisoner out of the pit, and gives the water,
and returns the prisoner of hope, and renders double to him that hath prisoned;
and he is called the Saviour, and he is Israel`'s Saviour,
and the Gentiles`' leader and covenant, yea, the salvation to the ends of the earth,
whom the isles wait for; and the prophet said, "`Kings shall be nursing fathers,
and queens nursing mothers,`" Isa. 49:23. and
they shall worship with their faces downward,
and lick the dust of the earth, for the Lord had said,
"`he would lift up his hand to the Gentiles, and standard to the people,
and they should bring their sons the Jews in their arms,
and thy daughters should be carried upon their shoulders,
the Gentiles;`" the Gentiles that had carried them away captive,
and the Lord would make them bring them back again, that had scourged them;
and nurse them, and carry the Jews, and lick the dust,
and so you were brought again to your own land;
and did not Cyrus and Darius and others aid you,
and hath not the Lord lifted up his hand and his standard to the Gentiles,
which many have received?

Isaiah was the son of Amos,
and prophesied about seven hundred and seventy-eight years before the Messiah was born;
and he prophesied of the Jews to be carried away captive by the heathen;
and how that the Gentiles should be nursing fathers, and kings should stoop down,
and bend down, and be made to carry them again, and be nurse to them,
and that the Jews should get a-top of that which captivated them,
and this was the carrying away from Jerusalem, and the carrying again to Jerusalem;
who also prophesied of the Messiah that should come amongst them,
to whom they should hide their faces, amongst whom the Jews;
Isaiah was a sign and a wonder to both the houses of Israel and Judah,
which was before they were carried away captive,
who were degenerated from the Lord by their idolatry, their sacrifices, their offerings,
and their temples that he turned them from, and said,
"`the Most High dwelt not in temples made with hands;
and he that offered sacrifice was as if he blessed
an idol;`" he prophesied in the days of Hezekiah,
king of Judah.
Isa. 37:1-2; 2 Kings 19.

Jeremiah prophesied in the days of Josiah, and in the days of Amon, Zedekiah, Zachariah,
and Haggai prophesied in the second year of Darius,
five hundred and nineteen years before Christ.
Jer. 1-3.

And Christ came not according to your minds, in pomp and glory,
as the kings of the kingdoms of the world doth and did, but he came meek, poor,
and despisable, and having no beauty to be desired, and a man of sorrows and griefs,
from whom you hid your faces, and crying away with him, he should not reign over us;
you would have no king but Ceasar, and desired a murderer, and crucified him:
and when Pilate said to you "`behold your King,`" and washed his hands from his blood,
you cried "`let his blood be upon us and our children;`" who hath been,
and brought the misery upon yourselves and your children;
and David`'s words are come upon you, who said,
"`let their children be vagabonds,`" which hath so been to this day, both from your God,
and your own nation.

Friends, in the 22d Psalm,
did not the saying of David come to pass by you upon Christ when he was upon the cross,
did not you say, "`he trusted in the Lord, let him deliver him?`"

Secondly, Did not you part his garment,
and afterwards cast lots for his vesture (according
to David`'s prophecy,) when you put him to death?

Thirdly, Did not you pierce his feet and hands when you nailed him to the cross,
according to David`'s prophecy in the 22d Psalm, did not you fulfil his saying?

Fourthly, Did not you give him vinegar and gall to drink, when he was upon the cross,
according to David`'s prophecy in the 69th Psalm;
and did not you stick in your outward things as a snare and gin,
and did not God pour forth his anger, wrath, and displeasure upon you,
according to the prophecy of David, who called Christ Lord?

And the prophecy of Jacob to his sons, and to Judah, who said,
the sceptre should not depart from Judah, nor the law-giver from between his feet,
until Shiloh come, and the people should be gathered unto him, unto Shiloh;
and is not the law departed from Judah, and the government and sceptre?
Where is his rule, if you say it is not departed?
And did not Shiloh come according to Jacob`'s and Daniel`'s prophecy?
and Gabriel`'s words in the days of Herod,
before the sceptre and the law had departed from Judah?
And so Shiloh being come, to him are the people gathered and gathering,
according to Jacob`'s prophecy, and the sceptre is departed from Judah this 1660 years.

Whether did ever the prophet say that you should be brought again into your own land,
to your outward worship, sacrifice, and the rest of your ceremonies,
after Jerusalem was destroyed, and the Messiah offered up, according to Daniel, Gabriel,
and the rest of the prophets.

Did not all the prophets prophesy of the new covenant to you before,
and in your captivity, and that your gathering should be unto him,
and that he should come when you were out of captivity in your own land?

Now if you can believe Moses, Isaiah, Jeremiah, and Daniel, Gabriel, and Ezekiel,
their prophecies, you must believe that the Messiah is come,
and receive the new covenant.

And the Lord said, he would gather his people from the mouth of the shepherds,
and teach them himself, and set one King over them,
which Teacher and King many do witness.

From a lover of all souls, and of the whole creation of God.

