== To All That Profess Christianity, / Are These Following Particulars

[.heading-continuation-blurb]
Concerning their Name of Christians, Loving Enemies, the Worship in Spirit,
Gospel Fellowship, their many Heads and Baptisms, their many Churches,
their disagreeing about Scripture Interpretation.--By G. F.

I+++.+++ Friends,--You have had the name of christians, which name hath come by tradition,
and succession, and hath been so kept up since the apostles`' days; but the life,
and the power, and the love, and the wisdom that was among the apostles, and in them,
which was the wisdom of Christ, have you kings, princes, rulers, teachers, and people,
high and low, been out of generally, and it is in the life and power of God,
in which God is served.
And now you christians, that have this name as after Christ,
but are found in the old life one with another, and in it one against another,
and this is in the apostacy and degeneration from
the life and power that the apostles were in,
in the primitive times;
and therefore are you (called christians,) broken into so many sects, and heaps,
and so many heads, and names, each one hating another; and this is the cause,
the being out of the power and life of Christ, and his wisdom,
which the apostles were in, which is gentle, pure, peaceable.
Now you kings, princes, rulers, teachers and people called christians,
are not peaceable one with another, and so are not in the wisdom that is from above,
and you are not gentle, neither are you easy to be entreated,
and therefore are in the wisdom below, below (I say,) that which is from above;
so therefore read yourselves and your condition, for the wisdom that is pure from above,
is gentle and easy to be entreated.
Now if all kings, princes, rulers, teachers, people high and low, were in this state,
then there would be no falling out, they would bear the badge of their master Christ,
and that which the apostles were in,
and there would be no strife in the whole family of Christendom,
for strife is out of the peaceable state, and gentle; therefore read yourselves,
your state, and your wisdom, and the apostles`' wisdom that they were in,
and what a degeneration and apostacy there is, and hath been from that.

II. Christ saith, "`love your enemies,`" and again he saith,
"`love one another,`" and that is the mark whereby you are known to be his disciples;
now let all Christendom look upon themselves, and among themselves,
and see how they have loved one another, and do love one another,
and how they have showed the mark of disciples; now if they had loved one another,
they had not hurt nor hated, nor gone to war one against another,
the ground of which hath come from their lusts, who have professed the name of Jesus,
but trampled his command under their feet, which command is to love one another;
and so hatred, lusts, war, contentions and strife are uppermost;
so now by this you may see there hath been a degeneration
and apostacy from the command of Christ,
in life and practice, and so in this his name hath been dishonoured.
Now to love one another, is not to war one with another, and to love enemies,
that is his command, and so not to war with them, nor strive, nor fight;
therefore now mind and remember, you that have professed the name of Jesus,
how out of this life and command of Christ, you are found,
and in the degeneration and apostacy from it,
and so separated from the apostles which were in it;
and that is the cause that you are in heaps among yourselves,
and have so many enemies abroad, for love makes friends,
and overcomes both among yourselves, and abroad.

III.
If you were in the worship of God in the spirit and in the truth,
that is that which the devil is out of, then would you be all in unity,
for unity is in the truth, which is before enmity was.
Now from this worship in spirit and truth, which Christ set up among the apostles,
hath there been a degeneration in Christendom, and an apostacy;
for if they had been all in it, that is to say in the spirit, and in the truth,
they had been in that which the devil is out of, who is the author of enmity,
and in the one standing worship, which is above the devil`'s worship,
and the worshipping of angels, and the will-worship,
and in the spirit is the fellowship with God, and with one another,
and with the scripture, to what state they were spoken.

IV. If you had all been in the gospel fellowship, (that is to say,
that which is called Christendom,) which gospel is the power of God,
which power of God was before the power of darkness was,
in which power of God is the everlasting fellowship,
which is the church-fellowship which was among the apostles,
from which there hath been a degeneration and apostacy, from the gospel the power of God,
which goeth over the power of darkness,
which hath darkened life and immortality from them,
and in this power of God the gospel is the mystery of the fellowship,
which is above all other fellowships in the world, which must have an end;
but the fellowship in the power of God, the gospel,
(before the power of darkness and the world was,
and its fellowships,) shall never have an end.
And men being gone out of the power of God, and degenerated and apostatized from that,
is the cause that they have gone into so many fellowships, and not into unity,
but one against another, for the unity and fellowship is in the gospel, the power of God,
(which is as I said before,) before enmity was, and in which no enmity can come,
and this is the standing everlasting fellowship of the church of God.

V+++.+++ The state of Christendom being gone into so many heads, and so many baptisms,
is because they are out of the power and spirit, light and life of Jesus,
which the apostles were in, and from that degenerated and apostatized,
and from Christ the one head, and one way, gone into so many,
and so in general being erred from the spirit and power of God in themselves,
which spirit should baptize into the one body, and so bring to the one head Christ,
and to plunge down all the corruptions which come through the enmity in man or woman,
which is the cause of so many bodies, and so many heads, and so many baptisms,
and so many ways which the many heads cry every one for his way and baptism, lo here,
lo there, which sets up so many broken cisterns, that hold not the living water,
but the one baptism with the one spirit,
which plunges down the corruption which is gotten up by transgression,
and the fall from God`'s image and holiness,
bringeth into the one body and to the one head Christ, the head of the body,
and so all to drink into the one spirit, where the water of life is felt.

VI. The state of Christendom in general, being run into so many churches,
(so called,) and every church miscalling one another,
and warring and striving and fighting one with another, and hating, and killing,
and slaying one another, and persecuting and imprisoning,
this is the state that is apostatized and degenerated
from the apostles in the primitive time,
and from Christ`'s doctrine, who said,
"`Let the tares and wheat grow together,`" and so doth not fight against the world,
for the church is made up of the wheat; but the state of all Christendom being on heaps,
church against church, and so many in it striving one with another,
is because they be not in the life of Christ Jesus, and in his power and wisdom,
and in his commandment, which is love, which commandment he gave forth, who said,
"`This is the commandment I give unto you,
that you love one another:`" so if christians`' feet
were foul and unclean to the sight of one another,
they should wash them, not imprison them or kill them, for Christ said,
"`He came not to destroy men`'s lives,
but to save them:`" when his disciples would have had fire come
down from heaven to consume them that were contrary-minded to them,
(as the prophet had done) such spirit Christ rebuked,
and told them "`They knew not of what spirit they were of.`"
Now what spirit hath Christendom been of,
that hath killed and persecuted one another about religion, church and worship;
have they known of what spirit they have been of?
And this hath manifested it to be the birth born of the flesh,
and not to be the birth born of the spirit, apostatized,
and so lost the fruit of the spirit, which is love, gentleness, and peaceableness, etc.
But the church is in God. 1 Thess. 1:1.
Now Adam and Eve being put out of the garden of the paradise of God,
because of transgression, and so the sons of Adam, and daughters of Adam in the fall,
out of God`'s image, righteousness, and holiness, which their father Adam,
and their mother Eve was in before they fell;
now in this state in the fall is many churches, but they that come to the church in God,
they must come out of that state that Adam and Eve,
and their sons and daughters were and are in, in the fall,
up into the state they were in before they fell, and so to be renewed again up,
into God`'s image, which in the fall is lost,
and up into his righteousness by Christ Jesus, who is the way to God,
and the head of the church that is in God,
so must all the sons and daughters of Adam scattered up and down the face of the earth,
of what sect or worship they are in, in the fall, in the state that their father,
Adam and Eve were in, in the fall,
they must be brought off to know the state that they were in before they fell,
if they come to the church that is in God the Father of Christ, who is the head of it,
and there is more in this.

VII.
And the state why all Christendom is on heaps about the scriptures,
and the interpretation thereof, the teachers and people,
and likewise about maintenance of their ministers, and are gone into so much idolatry,
and inventions and traditions of their own, and compelling people thereunto, as meats,
drinks, days, images and outward things, is,
that they are apostatized and degenerated from the life the apostles were in,
and the spirit in the primitive times, and so not being in the life of the prophets,
and the spirit of Christ in the apostles, which should open to them the scriptures,
from which spirit of God they were given forth, and of God they were learned,
the scriptures of truth cannot be broken, but must be fulfilled; so men and people,
high and low, teachers being not in the spirit as the prophets, Christ,
and the apostles were in, which lead them to speak forth scriptures,
in which Spirit the prophets, Christ and the apostles had unity and agreed;
and Christendom in general being not in this spirit,
they are all on heaps about scriptures, and the private interpretation thereof,
and therefore they set forth such great books one against another.
Now, if that they were in the spirit which gave forth the scriptures,
it would have been their bond of peace,
and in it they would have all had fellowship and unity with God,
of whom they had learned, and with scriptures, and one with another,
for in the spirit that gave them forth is the standing fellowship,
and with it the scriptures are seen, opened, and interpreted,
and men since the apostles`' days, not being in the spirit that gave forth scriptures,
they have said that the tongues were the original, the beginning of which was Babel,
and these tongues made them divide which have degenerated from the apostles, who said,
"`the tongues shall cease;`" and John in the Revelations, said,
"`they must be redeemed from tongues,`" and Pilate set the tongues a-top of Christ,
when he crucified him; and so this is cried up, which men must be redeemed from,
and must cease, the beginning of which is Babel, and which was set a-top of Christ,
this is cried up among such that be apostatized from the apostles, to be the original,
and to make divines, that be out of the spirit, life and power, that the prophets,
Christ, and the apostles were in; for the life, spirit and power that the prophets,
Christ, and the apostles were in, which brings people to know the scriptures,
given forth by the same spirit, and God of whom they were learned,
and to see the ceasing of tongues, and to see the beginning of tongues at Babel;
and to see the beginning before the fall, this is the spirit,
power and word of God which made divines, and makes divines,
and in which the original is known,
and this gives to see how Christendom hath apostatized from the apostles`' doctrine,
life and practice, which if people come out of, they must come to the light,
and feel and see the life of Jesus, and his power and spirit in their own particulars,
with which they may see the light,
life and power the apostles were in before the apostacy, in which is the unity.

There is one faith which justifieth and purifieth the heart, which is the gift of God,
which giveth victory over all that which hath separated man from God,
by which faith man hath again access to God, and in which faith he pleases God,
and in this faith is the unity of the church, and saints, which is in God,
and this is the true church faith, which hath been apostatized and degenerated from,
since the apostles`' days, by the generality of Christendom,
I say from this faith that works by love, which was among the apostles,
but the apostates and degenerated ones are in the hatred,
and not in the faith that works by love, their fruits declare it.
