== Christ`'s Light





The only Antidote to overcome and expel the Poison of Satan`'s greatest Temptations.--By G. F.

The ground of desperation is out of the light,
for Cain when he despaired went from the light, that killed the just;^
footnote:[Gen. 4:8]
he that killed the just within, killed the just without:^
footnote:[1 Sam. 28:15; 31:4]
and Esau, who despised his birth-right, who was a profane person,
did seek to kill the just; and he that rose up against the beloved of God,^
footnote:[Matt. 27:5]
David, he despaired, he rose up against the just: and the Jews did despair, and doubted,
they did not believe in the light, and were against the just,
though they professed all the scriptures; and Judas who despaired,
and turned from Christ the light to the changeable priests;
so the cause of desperation is going from the light, for that which leads to presume,
will lead to despair, which riseth up in that nature which acts contrary to the light,
and that is it which wanders to and fro, up and down, and hunts abroad,
and builds that which God confounds.^
footnote:[Gen. 25:27]
"`I am the light of the world,
and do enlighten every one that cometh into the world,`" saith Christ,
he by whom the world was made:
now every one being enlightened with the light that
comes from him who is not of the world,
who was tempted in the world to make himself away,
who was tempted to lust after the creatures, who was tempted to worship the devil,
who is out of the truth, but overcame all:^
footnote:[Luke 4:9; 6:5,8]
now every one of you that come into the world,
having a light from him that is not of this world, that was thus tempted,
who entered not into temptation; it is not a sin to be tempted, for he was tempted,
but to enter into the temptation:
so if you see temptations with the light that comes from Christ, the light, the truth,
and the life; look at him who was tempted, who overcame the temptations,
who was not of the world; having a light from him, whose name is called the Word of God,^
footnote:[Heb. 4:15]
who saith, "`because thou hast kept the word of my patience,
I also will keep thee from the hour of temptation which shall come upon all the world,
to try them that dwell upon the earth; so it shall not prevail over thee,
which shall come to try all that dwell upon the earth:^
footnote:[Rev. 3:10]
for having a light from the word by which all things were made, and keeping the word,
the power is received against all temptations, and they shall not come nigh.
Art thou tempted to make away with thyself?
So was Christ.
Look not at the temptations, but look at Christ, and there thou wilt receive power.
Art thou tempted to the creatures?
Doth the devil, he that is out of the truth, who is a destroyer,
tempt thee to the creatures?
So was Christ, he by whom all things were made.
Art thou tempted to worship the devil?^
footnote:[Rev. 3:8; Luke 4:3,7; Heb. 2:10; John 14:16]
Doth the devil, who is out of the truth, tempt thee to worship him, look to Christ,
he was tempted, who overcame: look to him who overcame,
he is the captain of our salvation: so every one having a light from Christ Jesus,
which is given to him to watch, and to pray, and to seek, and to knock after Christ,
who is the door, the way, the life, the covenant of peace:
so look not at the temptations, but at Christ, neither be troubled at them;
but look to him from whom your strength comes, that lets you see them,
and there stand still, for there salvation is received, and your strength.
Have you made a covenant with death,
who contrary to the light in your consciences have acted?
have you made covenants with hell, and the grave, and Satan, which is out of the light,
out of the truth;^
footnote:[Isa. 45:22; 28:16-18; 42:6; 49:9]
and that is the devil that is out of the truth, the destroyer, the devourer.
Therefore being turned to the light which comes from Christ, the covenant of God,
God`'s covenant of light, there waiting, the covenant of death is broken,
and in it believe, for there God`'s mercy is received,
against which covenant hell gates cannot prevail, let her open her mouth never so wide;
and all the bonds of iniquity, promises which you have made with the fleshly mind,
and the lusts being turned to the light,
the covenant of life breaks all the bonds and promises of the fleshly mind:
therefore in patience wait in the light which comes from Christ,^
footnote:[Lam. 3:26]
the covenant of peace which ye may receive to have peace with God;
and never look at the temptations, but at the light which shows them,
and there stand still to receive power from him, from whom all power is received;
for that which is out of the truth, that tempts to draw from the light,
and from the truth, and out of it; therefore every one having the light from Christ,
who is not of the world, which is come into the world,
that will let you see the temptations.
They that keep the word, they shall not prevail,
but power shall be received to trample upon all.^
footnote:[John 17:15; Rev. 6:10; John 8:44; Matt. 11:29]
And the worship in the spirit and truth will be known,
and the wisdom by which all the creatures were created, will be received,
with it to use them to the glory of God, to which end they were created;
and that which is out of the truth, which tempts to murder,
for that is the murderer which is out of the truth, and out of the light,
will with the light be seen, judged, and condemned;
but he who before did lift up and exalt, and the same will bring to despair;
but learn of Christ the light, who is meek and lowly, and he is kept out and down,
who is out of the light: but before this, he will tempt into the creatures,
to get thy mind into the creatures, he who is from the light, and from the life,
and so a devourer of them, and so out of the wisdom of them by which they were created;
therefore, as I said before, wait in the light which comes from Christ the life,
that with it you may come to receive refreshing from the Lord;
and to know the wisdom of the creation,
with which it must be used to the glory of the Creator.
So having a light from him by whom the world was made,
to whom all power in heaven and earth is given; wait in the light,
from him to receive power, which brings out of the world`'s lusts and defilements,^
footnote:[John 9:51]
which the light which cometh from him will show you all the temptations to the creatures,
or obeying the will of him that is out of the truth,
but you will come to know the right use of the creatures, waiting in the light;
so wait for power from the Lord in the light (which shows
you all temptations,) which comes from the Lord,
for power to stand against all temptations;
and so that all may be condemned by the light, that is contrary to it;
and so you may come to witness the leaven that leavens into the new lump,
and see him that makes intercession, who is able to save to the utmost;^
footnote:[Matt. 13:33; Heb. 7:2; 1 Cor. 10:13]
and so with the light you may see there is no temptation you are taken with,
but which is common to man.
So if you mind the light, and in it stand, you will see the Lord giving issue,
whereby you will find deliverance standing in the light, which comes from the word,
which is a fire, and a hammer, and a sword,^
footnote:[Jer. 23:29; 2 Cor. 5:10]
which beats down that which is contrary to the truth, divides and burns up,
but keeping the word, the temptations will not come nigh,
but the word of reconciliation be witnessed, and the word of faith which makes clean,
and purifies, and sanctifies; where the old garment is put off,
and the knowledge in the flesh denied, and the knowing in the life, in the spirit,
where nothing comes to reign but life and power, where all is overturned,
and with the power of the Lord comprehended, the dread and life of the living God,
to whom be all honour and glory for ever.

