== To All Rulers of Families

Of what sort soever, herein concerned.--By G. F.

I+++.+++ To all rulers of families of what sort soever,
who have an authority and command of children and servants,
and who should train them up in the fear of God, and in modesty, civility, sobriety,
and subjection, and gravity; but on the contrary, the unchristian-like is manifest,
and discovers itself, and shows itself forth unto all people;
for look upon yourselves and children, how wild and wicked they be, vain, proud,
and a multitude of unsavoury words,
and almost continually it hath been the practice of your
servants and children to come to the elect people of God,
in scorn called Quakers, to their meetings, and houses, scoffing, and scorning,
and mocking, with all manner of slanderous expressions they can invent,
casting upon the same people; and do abuse them with their tongues,
and casting mire and dirt, and stones at their windows; which if you had either modesty,
or gravity, or good neighbourhood,
you would be ashamed to see your children do such things, or hear of it,
which many times have been said before several of you,
and thus you act contrary to christianity, in which lies virtue,
and also have cast the law of God behind your backs,
which is to do unto another as you would be done unto;
and what would you have us to mock and scoff, and throw dirt at you,
as you go to your meetings, and throw stones at you in your meetings,
and break your windows?
Would you say this was good neighbourhood, or good christianity?
Or is it observing the law to do unto another as you would be done unto?
and so by this do not you see that your young people are not trained up in soberness?
for many old people have encouraged youth and young people into the same actions,
which shows gravity is lost, but old people should be grave, and old people moderate,
and young sober, and temperate.

II. And also all ye masters of colleges and schools, of what sort soever,
do you not shame to hear of the abuses of your scholars?
Have not you been often told of it, and it laid before you?
Should you not teach your scholars civility and manners?
Doth not evil words corrupt good manners?
And is this breeding and manners,
for your scholars to come to sober and civil peoples`' houses, and break their windows,
and throw dirt at civil people, and throw dirt and stones among them,
when they are met together to wait upon the Lord, and mock, and scoff, and reproach,
and revile,
and slander with the slanderous tongue all manner of slanders they can invent?
would you be so served yourselves, and so done by?
Do you either train up your children in the fear of God, or law, or gospel?
Are not you ashamed of these things?
Or do you call this neighbourly?
Or are you not ashamed to look your neighbours in the face?
Surely gravity, modesty, civility, sobriety,
and the training up children in the fear of God is lost amongst you;
and doth not this shame christianity to all forms;
for many of the heathen have not been so bad towards us.

III.
All ye heads of colleges, do you not shame, are you not ashamed to see your scholars,
or hear of their rudeness, and of their unvirtuousness, and of their unsoberness,
and ungraciousness,
and of their immodesty in their carriage towards the sober people of God,
in scorn called Quakers amongst you?
Have not your young scholars torn their clothes and knocked them down in their channels,
and shed their blood in the streets upon your pavements,
and torn their clothes off their backs, and thrown dirt and stones and muck amongst them,
and upon them, and broken their windows, and forms where they sat,
and leapt amongst them, and bruised them, and beat them,
with the same things that they broke off their forms,
and brought drink and threw it in the faces of them that met in the fear of God,
and ask for lasses, women, and wenches;
are these the two fountains and eyes of the nation, and the two well-springs of learning,
and the two famous universities of the land!
Oh do not these actions shame modesty, and christianity?
Are these fit to be ministers, and trained up ministers of Christ,
amongst whom is no better government?
For it is not a few that have come,
but sometimes by many scores they have showed these many abuses in and at our meetings:
doth not this show impiety, and doth not this manifest the orders and the governors,
and the masters and heads of colleges not to be grave themselves?
Seeing their young men are not sober, manifest the old are not grave,
who should train up the young to be sober and temperate; for where is soberness,
and temperance, and modesty, and civility, and gentleness, and meekness, and holiness,
and righteousness, which beautifies a people amongst you?
For would you be so served yourselves, for any other people to come and mock,
and reproach, and throw stones and dirt amongst you in your meetings?
Would you call this manners, breeding and gravity?
Doth not these actions shame both master and scholars, and dishonour virtue, breeding,
and manners, and render to all strangers the uncivility of their schools?
For more gravity have we found among the heathen, than these two eyes of the nation,
which have not the name of piety, whose actions declare against it; therefore, amend.

IV. And all ye ministers and overseers, do you not shame to see your people so rude,
so light and so vain, and so immodest, and so intemperate, what drunkenness,
and what swearing and profaneness is amongst you?
Is it not like Sodom, and people more like Egyptians than christians?
And wolves and Philistines than sheep?
Therefore, consider what account you will give to the Judge of all,
who will reward every man according to his works and doings; therefore,
where is modesty amongst you?
Where is sobriety?
Do not your young men want gravity, and your young women shamefacedness, and sobriety?
Have not you teachers lost both the example and pattern,
which should have been showed forth unto people?
Look among your people, is not good breeding almost lost,
and good manners corrupted by evil words,
and that people neither walk according to law nor gospel?
For if they walk according to the law, then you would do unto all men,
as you would they should do unto you: and if they did walk according to the gospel,
then they would love enemies; is this loving enemies, to stone, mock,
beat and slander the people of God, who be peaceably met together to worship God?
Would you be so served yourselves?
Would you have others do so unto you?
Do you to others as you would have others do to you?
Do you either observe law or gospel?
Therefore, all rulers of families, schoolmasters, and mistresses,
and masters of colleges, and governors, and teachers, and magistrates, and all people,
do unto all men as you would they should do unto you;
observe that rule of the law and the prophets, if you cannot obey the gospel,
which is to love enemies, and love one another;
if you cannot come so high as to a christian`'s life,
as to the gospel which is to love enemies,
which love out of a pure heart is the end of the law, yet at least come to obey the law,
which is to do as you would be done by.

Friends,--You have had a day of persecuting, of prisoning,
of spoiling the goods of the people of God, denying the light,
manifesting your works of darkness and deeds to be ever such that hated the light,
and persecuted it, that the place for the (children,) professors of light was your jails,
houses of correction, and stocks, and your whipping of such as walked in it;
now what good hath all your profession done you, and your works,
and what is it all come to?
Was not your zeal blind, and your worship in your wills, and your humility feigned,
and your religion vain?
Doth it not now manifest, that now it is not worth standing to, and by?

Now that your church faith and directory is not worth taking up in the streets;
may not all that pass by say, O how is the beautiful city fallen?
And what is become of the wall and the doors?
Is not now your desolation come, and loss of your children?
And doth not many of you gnaw your tongues for pain, and stand aloof, and cry, alas! alas!
How is the great city fallen?
And what howling is there among the merchants!
And so manifest that you are turned with the dog to the vomit,
and the sow into the mire that was washed?
And was not you in your height as a sow that did rend, and as a dog that did bite?
And was not persecution always blind?
And must ye not give an account for all the goods ye have spoiled,
and all the evil deeds you have done,
and for all the blood of the righteous ye have spilled, both by whippings,
prisonings to death; as instance that innocent James Parnell, a saint,
whose righteous blood lies upon you; besides many others,
whose righteous blood hath long cried for vengeance,
which is now coming on the heads of you,
who are spattered with the blood of the righteous,
and filled yourselves with the spoils of the innocent, yea many houses;
is not the Lord coming upon the spoiler; and to rebuke the devourer;
what havoc did you make a few years ago,
when you were in the height and prime of your religion, whipping, stocking, prisoning,
hauling up and down to your courts?
hardly any could come nigh you, your pride was grown so high;
and is not the Lord staining your pride, and laying your honour in the dust?
And it will be well for you if you find a place for repentance,
and come to see the way of peace, and it be not hid from your eyes;
for the way you went on in, was not like to prosper,
turning your sword backward against the righteous,
and letting the evildoers have liberty till they got over you,
so that the just hand of God is upon you, and you may say you had time,
but did not prize it.
Therefore, consider the days you have spent, and the deeds you have done,
and evil ways you have walked in,
and consider now if you can see yourselves where you are; and see if all your religion,
and your worship, and profession was not a work of darkness;
for now in a tempest and storm you dare not stand to it, it will not cover you:
and so it was a religion for summer, when your sun did shine, when you had the club,
staff, and bag, then every viper crept out; but now winter is come,
none of you are seen in public so your flight is in the winter;
so you are not only apostatized from the apostles`' doctrine and religion,
but also from your own; and what may all men say of you?
Now you are manifest to open view.

[.emphasis]
From a friend of your everlasting souls,
and ever was one that never turned his back nor cheek from your smiting,
nor his hair away from your plucking it off,
who have plucked and struck till you have tumbled yourselves into the ditch,
for we thrust you not in; and if you have not enough, our backs are ready still,
and we have yet a cow, and a little corn, and can give bread and drink to our enemies,
if they want it; and also we have a pot, and platter, and a horse, and credit,
who were so vilified by you, which you in your day thought to have taken all away.
