== Some Queries

[.heading-continuation-blurb]
To all the Teachers and Professors of Christianity to answer.--By G. F.

Query I. Where did ever the christians in the primitive times set up dancing schools,
and fencing schools, and send their youth to learn to dance and fence,
as those called christians have done since the primitive times;
let us see where such things were practised in the scriptures by the true christians?

Query II. Where was any instruments of music allowed of
God to be invented and used by the Jews to themselves,
but unto the Lord?
Indeed David used them as unto the Lord, and danced before the ark of the Lord:
but what is the use and end of all the music and dancing in Christendom?
Was not the melody the true christians made, in their hearts to the Lord?

Query III.
Where did the primitive christians invent plays and shows,
as those called christians have done since the apostles`' days.

Query IV. Whether any of the Jews under the Old Testament
ever invented plays and shows to get money by them,
as those called christians do now?
We desire you will produce your rule and example out of the Old or New Testament,
among Jews or christians for these things.

Query V. Where did the Jews or christians in the apostles`' days set up or use bear-baitings,
bull-baitings, cock-fightings, nine-pins and bowls, and cards and dice,
and such like sports and games, as those called christians do now,
to make themselves merry withal, and to spend their precious time away,
and call it pastime, and rejoice, and stir up wantonness in people?
Show scripture for these things, seeing you profess it your rule;
are not those that live wantonly upon earth, and in pleasure, dead while they live?
Are not those that rejoice, to rejoice in the Lord?

Query VI. Where did the christians in the apostles`' days make and use matches at foot-ball,
and wrestling, and appoint horse-races, and hunting for pleasure, and such like,
and so glory in their own strength, and abuse the creatures?
Are not these things contrary to the practice of the holy men,
who rejoiced and gloried in the Lord?
show us your rule in the holy scriptures for these things?

Query VII.
Whether all these plays, games, shows, sports, and other vain exercises,
countenanced in Christendom, do not spoil and corrupt youth, and men,
and ruin them in person and estate?

And doth not Amos say, woe to such that chant to the sound of the viol,
and invent to themselves instrument of music, like David?`"
Amos 6.

George Fox.
