== Gospel Liberty, and The Royal Law of Love.

[.heading-continuation-blurb]
From Christ Jesus, who hath all Power in Heaven and Earth given unto him;
set above Artaxerxes, and Nebuchadnezzar`'s Law and Commands;
and above the Medes and Persians, and Darius`'s Decrees;
being a Plain and Full Testimony against Persecutions for tender consciences sake.--By G. F.

Christ Jesus saith, "`all power in heaven and earth is given unto me.`" Matt. 28.
And when Christ sent messengers into a village of the Samaritans,
to make ready for him, and they did not receive him;
and when his disciples James and John saw this, they said, "`Lord,
wilt thou that we command fire to come down from heaven, and consume them,
as Elias did?`"
Mark, how Christ useth his power to his disciples, who were rebukeable;
Christ turned himself about and rebuked them, and said,
"`ye know not what manner of spirit ye are of.`"
Here he lays and stops the revenge which was in his
disciples against those that would not receive him,
and told them, they did not know what spirit they were of: now,
if his disciples did not know what spirit they were of, and were under the rebuke,
that would have fire to come down from heaven to
consume them that would not receive Christ;
how doth all Christendom know what manner of spirits they are of, which has prisoned,
banished, and put to death so many about religion?
Are they not all under the rebuke of Christ, and not knowing their own spirits?
For Christ, who hath all power in heaven and earth, saith, that the rebuke is to such,
whose actions be done out of his power,
"`that the son of man is not come to destroy men`'s lives, but to save them.`"
Now, +++[+++mark,]
then it follows, they that destroy men`'s lives (and not save them,) about religion,
have not the mind of Christ, neither do they act as from his power,
"`who hath all power in heaven and earth committed to him.`"
Luke 9:52-53, etc.

And also, in Matt. 13:25-30, where you may see Christ,
who has all power in heaven and earth, useth his power upon the forward servants,
that would be plucking up tares, which was not their places, but the angels`':
Christ`'s own words are as follows, in his parable,
"`The kingdom of heaven is like unto a man that sowed good seed in his field;
but while men slept, the enemy came and sowed tares among the wheat, and went his way:
(mark, the tares are sowed while men sleep;) when the blade sprang up,
and brought forth fruit, then appeared the tares also:
so the servants of the householder came, and said unto him, sir,
didst not thou sow good seed in thy field?
from whence then hath it its tares?
He said unto them, an enemy hath done it; the servant said unto him,
wilt thou that we go and pluck them up?
but he said, nay; lest while you go to pluck up the tares,
you root up the wheat with them.`"
Here Christ is a judge in matters of religion,
who has all power in heaven given unto him;
for you may see here that he doth not give these
forward servants a warrant to pluck up the tares,
lest they should pluck up the wheat also; but stops them with these words, etc. saying,
"`let both grow till the harvest; and in the time of harvest I will say to the reapers,
gather ye first the tares, and bundle them in bundles to burn them;
and gather the wheat into my barn.`"

Here Christ stops these forward servants; who saw the time that men would sleep,
and then the enemy would come, and sow his tares;
and did see also that many would be pluckers up, which was not their places,
and had no commission, nor hath any commission from him to this day; and such he stops.

And from the 26th verse to 42 of Matthew 13. where the disciples came unto Christ,
saying, "`declare unto us the parable of the tares of the field;`" Jesus answered,
and said unto them, "`the son of man is he that soweth the good seed;
the field is the world, and the good seed is the children of the kingdom;
but the tares are the children of the wicked one;
the enemy that soweth them is the devil; the harvest is the end of the world;
and the reapers are the angels; and the tares are gathered to be burned in the tire.
So shall it be in the end of this world, the son of man shall send forth his angels,
and they shall gather out of all kingdoms all them that offend, and that do iniquity.`"
Now mark, may not Christ, (who has all power in heaven and earth,
etc.) his word stop all forward persecutors in the world,
(which is called the field,) where the good and the bad seeds are sown; for,
doth not he say, "`the tares and the wheat must grow till the harvest,
and that is the end of the world;`" and doth not those that
would be reaping and gathering before the end of the world,
busy themselves, and oppose Christ in his command and power?
For seeing Christ saith, "`He will send forth his angels;`" and when, before the harvest?
nay, or before the end of the world?
nay, and his angels are his reapers, and so it is not men in the middle of the world,
that must be the reapers, and the gatherers of the tares; but it is Christ`'s angels.
And when then is the time of reaping?
The time of harvest, which is the end of the world: and who are the reapers?
the angels.
So then it is the angels`' work, and not men`'s;
so here it is plain that Christ is the judge in matters of religion,
betwixt tares and wheat, who sends forth his angels:
for Christ commands men to "`love one another,`" and to
"`love enemies;`" and so they that do not love one another,
nor enemies, do not obey the commands of Christ,
who hath all power in heaven and earth given unto him: for this is his royal command,
"`love one another;`" by this you are known to be the disciples of Christ Jesus;
and this is the command that Christ Jesus gave unto men and women,
who has all power in heaven and earth, men should love one another, and enemies;
and the angels should be reapers; and Christ saith, "`love your enemies,
do good to them that hate you, bless them that curse you,
pray for them that despitefully use you,
and persecute you,`" for Christ saw that there would be haters of his seed, and cursers,
and despiteful users of it, and persecutors of it,
which would be pluckers up of the wheat for tares, who had no such command from Christ.

And Christ saith,
(in the 15th of John,) who hath all power in heaven and earth given to him;
"`this is my commandment, that you love one another, as I loved you:`" so,
have not Christendom cast this commandment of his behind their backs?
For have they loved one another, or observed the commandment of him that has all power?
but instead of this, they have persecuted one another;
and so cast away the command of Jesus, as the Jews did the law of God,
and not walk in it; for herein saith Christ, "`is my Father glorified,
that you bear much fruit; as the Father loved me, so have I loved you;
continue ye in my love:`" so christians not continuing in the love of Christ,
with which he has loved them, they cannot bring forth fruits,
so they cannot glorify Christ, nor the Father;
"`for if you keep my commandments you abide in my love,
even as I have kept my Father`'s commandment, and abide in his love.`"
So here christians may see, they that abide not in the love, but in the enmity,
they have not kept the commands of Christ:
"`and ye are my friends if ye do whatsoever I command you; and this is my commandment,
that ye love one another, as I loved you;`" and so it is plain,
that these called christians, that love not one another, are no friends to Christ Jesus,
neither regard his power, nor doctrine.

Mark Christ`'s words further, where he saith, "`remember the words I said unto you,
the servant is not greater than his lord, if they have persecuted me,
they will also persecute you; if they have kept my sayings, they will keep yours also.`"
But now, christians, you that do persecute, are out of Christ`'s mind, and power,
and command, who saith, "`love enemies,`" and "`love one another;`" and so,
they that do persecute have neither kept the sayings of Christ,
nor the sayings of the apostles: so all you that profess yourselves to be christians,
and own Christ Jesus, and that God hath sent him, you are not to persecute one another,
nor enemies;
but the command of Christ (to whom all power in heaven and earth is given,) is to you,
to "`love one another,`" for that edifies the body, and overcomes the evil;
and that is the law of love that is to be among christians;
and this is the royal law from him that hath all power, who is King of kings,
and Lord of lords; and this love bears all things, endures all things, hopes all things,
is not provoked; for that which is provoked will run into words and actions,
enmity and persecution, malice and hatred, which are the works of the flesh,
which are judged all down by the law of love; so keeping the law of love,
you keep down that which would be provoked: so love overcomes the enmity,
and the light overcomes the darkness,
and the righteousness overcomes the unrighteousness,
as life overcomes death and the power of it, and so good overcomes evil:
so where is this universal life, and universal love amongst you christians,
whereby you might come out of your narrow angry spirit,
into a loving and universal spirit?

And Christ taught his christian disciples to pray,
who has all power in heaven and earth given to him,
which is a common prayer to all Christendom, for all can say it, and saith it in words;
"`forgive us our debts as we forgive our debtors; for if ye forgive men their trespasses,
your heavenly father will also forgive you; but if ye forgive not men their trespasses,
neither will your father forgive you your trespasses:`"
and this prayer differed from the pharisees,
who stood praying in the synagogues, and did not forgive, as christians now,
who say this common prayer of Christ, to God the Father, forgive us,
as we do forgive them that trespass against us; and that is,
they ask no forgiveness at all for themselves, if they do not forgive.
Oh, that they would come to that by which they might see their blindness,
and the chain that they are under:
for if christians do transgress and trespass one
against another in their religions and worships;
the papists against the common prayer, and the common prayer against the papist,
they must forgive one another: and the presbyterian, baptist, independent, lutherean,
calvanists, do not you all profess Christ, and God that sent him?
Do you not all say Christ`'s common prayer?
And have you not trespassed one against another in matters of religion, and worship,
and church?
Then must you not all forgive one another, according to Christ`'s prayer,
who has all power in heaven, etc. and if you ask the Lord to be forgiven,
as you do forgive, and you do not forgive, then you ask for no forgiveness:
for mark your words, you ask to forgive us,
as we do forgive them that trespass against us; so, mark the word +++[+++as,]
as you forgive, so you would be forgiven, and no otherwise: and so as you do persecute,
and cast into prison, and banish one another called christians,
and keep the debts in your books; think you not that your debts stand in God`'s book;
and that he will banish you from the land of the living,
and cast you into everlasting imprisonment, from the presence of God and his angels,
as you may read the dreadful sentence in Matthew 25,
wherein Christ saith to them that are the goats, on the left hand;
(they are on the left hand, and not on the right hand;
for it is the sheep are on the right hand,) "`depart from me ye cursed,
into everlasting fire, prepared for the devil and his angels: for I was an hungry,
and you gave me no meat; I was thirsty, and you gave me no drink;`" +++[+++mark,]
these were they on the left hand, let them be called christians, or whatsoever they be:
and they on the left hand are forwarder to take meat and drink from Christ,
and his little ones, than to give it them; and to cast them into prison till death,
for their bellies; but those are such as the apostle speaks of,
"`that serve not the Lord Jesus Christ, but their own bellies.`"
And Christ further saith, "`I was a stranger, and you took me not in;
and naked and you clothed me not: sick, and in prison, and you visited me not.`"
And they on the left hand shall answer and say unto Christ, "`when saw we thee hungry,
or a-thirst, or a stranger, or naked, sick, or in prison,
and did not minister unto thee?`"
hear Christ`'s answer unto them;
"`in-as-much as you did it not to one of the least of these,
you did it not unto me:`" and therefore, hear the sentence of him,
who has all power in heaven and earth, to them on the left hand which are the goats;
"`go away into everlasting punishment; but the righteous into life eternal.`"
Now they on the left hand, let them be called christians, or what they will be,
they are more like to make strangers, than to take in strangers,
who banish them from their wives and families, and native land;
and more like to make naked and make sick, than to clothe, and to visit; and to imprison,
than to visit in prison; and they that do so, press the seed of God in themselves,
from whence the love of God flows; and such men do that which they should not do;
for they should love one another; for it is the angels`' work to reap at the harvest,
which is the end of the world, and not men`'s;
for it is Christ that is judge in matters of religion; for he doth,
as you may see by the talents, they that had improved them had their reward;
and he that did not improve his talent was an unprofitable servant,
"`to be cast into utter darkness,
where shall be weeping and gnashing of teeth:`" and you that say, when shall this be?
it is answered, "`when the son of man shall come in his glory,
and all the holy angels with him; then shall he sit upon the throne of his glory,
and before him shall be gathered all nations; and he shall separate one from the other,
as a shepherd divideth the sheep from the goats;
and he shall set the sheep on his right hand,
and the goats on the left hand:`" so here it is plainly
seen that Christ is the only judge in matters of religion,
and in dividing sheep from goats; so it is not man, in his own dark reason,
that cast the law of Christ Jesus behind his back, (which is,
"`to love one another,`") which ought to be his rule,
for Christ is to be judge in matters of religion.

And as Christ saith, who hath all power in heaven and earth, "`blessed are the meek,
for they shall inherit the earth;`" then they that
are not meek do not inherit this blessing:
"`blessed are they that hunger and thirst after righteousness,
for they shall be filled;`" then they that hunger and thirst after unrighteousness,
and drink up iniquity, as an ox drinketh up water,
and persecute the righteous for his righteousness sake, they obtain not this blessing:
"`blessed be the merciful, for they shall obtain mercy;`" now the cruel,
and the persecuting, unmerciful, obtain not this blessing:
"`blessed are the pure in heart, for they shall see God;`" so the impure in heart,
that love the evil, and hate the light, and love darkness better than light,
do not come to be partakers of this blessing, nor see God:
"`blessed are the peace-makers,
for they shall be called the children of God;`" they
that are the strife-makers among the people,
for their bellies, and outward things, are not the children of God,
and have not this blessing:
"`blessed are they that are persecuted for righteousness sake,
for theirs is the kingdom of God;`" then what blessing have the persecutors?
and what kingdom is theirs?
Judge ye: "`blessed are ye when men shall revile and persecute you,
and say all manner of evil against you for my sake, and the gospel;`" then it follows,
the revilers and persecutors have not that blessing.

Query.
What evil could any, both in their other powers, days, and now,
find in the people called Quakers, but only concerning Christ, and their God;
for which they have been persecuted, banished, and imprisoned till death.

But here you may see Christ, who had all power in heaven and earth,
did see that there would be persecutors,
and speakers of all manner of evil against his people falsely, for his sake;
but he encourages the persecuted, and bids them "`rejoice, and be glad exceedingly,
for great is your reward in heaven:`" so here you
may see that their reward is not from the earth:
"`for so,`" said Christ,
"`they persecuted the prophets that went before you,`" which
was to let them know that persecution was no new thing;
nevertheless, Christ encourages them, that they are the salt of the earth, his children,
and the salt makes the earth savory; and they were the light of the world,
and a city set on a hill cannot be hid;
so that they could not be hid from the persecutors,
and such as did speak all manner of evil against them falsely, for his sake: and further,
Christ saith, to encourage them, "`that the light should be put on a candle-stick,
and not under a bushel to be hidden, but to give light to all the house;
for they were the light of the world;`" and bids them,
"`let their light shine before men, that they might behold and see their good works,
and glorify their Father which is in heaven;`" and this
was to keep their eyes above them that persecuted,
and spoke all manner of evil of them.
And so here you may see that the prophets,
and the children of the kingdom did not suffer as just men in the eyes of the persecutors;
for Stephen did not suffer as a just man in the eyes of his persecutors,
but as a blasphemer.
Acts 7. And Christ Jesus, in the eyes of the persecuting priests, scribes, and pharisees,
did not suffer by them as a just man, but was accounted a deceiver;
and the chief priests mocked him, wagging their heads at him;
and that is the way of the persecuting spirit now; but Christ said,
"`Father forgive them, for they know not what they do:`" and now,
you christians that persecute, are you not so blind that you do not know what you do?
And when the great persecuting professing Jews cried against Christ, "`crucify him,
crucify him,`" nothing but death would serve them; did not Christ say to Pilate,
"`if my kingdom were of this world, then would my servants fight,
that I should not be delivered to the Jews;
but now is my kingdom not from thence;`" which shows
that the kingdom of the world is the fighters;
and Christ, who had all power in heaven and earth given unto him,
would not defend himself against all his persecutors, mocking priests, and professors;
as you may see the greatest persecuting professors in Christendom,
they will now mock them they persecute;
but such have cast the law of Jesus behind their hacks;
but Christ prayed to his Father to forgive his persecutors, as the Quakers,
that have the mind of Christ, do now, although he had all power given unto him,
and could have prayed unto his Father for legions of angels, to defend him.

And you read in the scriptures that the great professors of scriptures, the Jews,
said that Christ was a deceiver, and he was mad, and had a devil,
and by the prince of devils cast out devils; and Christ knew this was for religion sake,
and for his virtue and Sonship;
and although he had all power in heaven and earth given unto him;
yet he did not give forth any law against them to have them punished,
though they would have stoned him, and took up stones to stone him,
who is the King of kings, and Lord of lords,
he did not give forth any command or warrant to bind any to their good behaviour;
for he suffered for his good profession and testimony: and oh, people,
that call yourselves christians, lift up your eyes, that Christ may be your example,
and follow him: not the man of sin, who was a persecutor, caster in prison,
and murderer from the beginning; for the proof you may see in the Revelation, it is said,
"`the devil shall cast some of you in prison ten days.`"

Peter said to Christ, "`Lord how oft shall my brother sin against me, and I forgive him,
till seven times?`"
Jesus said unto him, "`I say unto thee not until seven times,
but until seventy seven times.`"

Oh, ye people that call yourselves christians,
how unlike minded are you unto Christ in this?
how short, narrow, and impatient-spirited are you that persecute one another,
and cannot bear one another, and forgive one another, and be patient one towards another,
and love one another?
And so Christ after he had spoken to Peter, he spoke a parable,
how that "`the kingdom of heaven is likened to a
certain king which would take account of his servants:
and when he began to reckon,
one was brought unto him which owed him ten thousand talents;
but for-as-much as he had not to pay, his lord commanded him to be sold,
and his wife and children, and all that he had, and payment to be made;
the servant fell down, and said, lord have pity upon me, and I will pay thee all:
and the lord of that servant was moved with compassion, loosed him,
and forgave him the debt:`" +++[+++mark,]
here is the mercy, and the compassion, and the loosing,
and the forgiveness in the acknowledgment, from the Lord the King of heaven;
"`But the same servant went out and found one of his fellow servants,
which owed him one hundred pence; he laid hands of him, and took him by the throat,
saying, pay me that thou owest me; and though his fellow servant said he would pay him,
and besought him to have patience, and he would pay him all,
he cast him into prison till he paid the debt.`"

Is not this like unto the envious, unmerciful, impatient professing Jews and christians,
that are so passionate and mad, and casting into prison for every small matter; yea,
and some that owes them nothing, neither sets them on work,
as instance the priests and bishops.

So his fellow servant was sorry, and saw what was done, and came and told his lord;
then the lord called him unto him, and said, "`I forgave thee all that debt,
O wicked servant, because thou desirest me;
shouldst not thou also have had compassion on thy fellow servant,
even as I had pity on thee?
And his lord was wroth, and delivered him unto the tormentor,
until he should pay all that was due unto him:`" "`So,`" says Christ,
"`likewise shall my Heavenly Father do unto you;
if ye from your hearts forgive not every one his brother his trespasses.`"
Oh, ye that are called christians, and go by that name, that are so subject,
and so forward, to take your brother by the throat,
and hauling them into prison till your will be satisfied,
and make your brethren trespassers, when they are none, and cast them into prison,
when you have neither law nor ground, but to satisfy your wills:
consider the sentence of Christ,
how that he said his Heavenly Father will deliver you up to the tormentors,
till that you have paid him his due,
who do not forgive your brethren from your hearts which trespass against you; nay,
many of you cannot forgive that which is no trespass,
but with spleen and envy will revenge; for would you take vengeance out of God`'s hand?
who saith, "`Vengeance is mine,
and I will repay it;`" and every one that doth wrong
shall receive for the wrong that he doth,
God respects no man`'s person, and so this might convince you:
let the tares and the wheat grow together till the harvest;
for God would give them their reward according to their deeds,
whether they be good or evil.
Let all Christendom lay away this law of persecuting one another, and so make no more;
but mind that which is made already by Christ Jesus,
who hath all power in heaven and earth, which is the law of love,
and the great commandment, "`to love one another,
and enemies,`" and this is it that must unite all Christendom
in a uniformity and conformity to their head Christ Jesus,
their law-maker, and commandment-giver.

And in Matt.
22. Christ saith, "`thou shalt love thy neigbour as thyself,
thou shalt love the Lord thy God with all thy heart, with all thy soul,
and with all thy mind.
On these two commandments hang all the law and the prophets:`" this spoke
Christ to the lawyers when they came to ensnare him by their questions,
as many do now the children of his kingdom: so now how short are you, called christians,
of the law and the prophets, in the practice of Christ`'s doctrine;
for if you loved your neighbours as yourselves, then how can you imprison?
How can you banish?
How can you spoil goods?
How can you burn?
How can you hang your neighbours?
How can you love and serve God with all your hearts and your souls,
and destroy your fellow creatures, the works of his hands,
and for matter of religion and worship of God, whom you profess to love?
And seeing you all do profess God and Christ,
and yet do destroy one another about your religion and worship,
this is contrary to his command, who has all power in heaven and earth;
this is contrary to his command, which is to love one another, and enemies,
and contrary to his law of love, and contrary to his doctrine and example,
"`who came not to destroy men`'s lives,
but to save them;`" who rebuked them that would have had men`'s lives destroyed;
and "`to do unto all men,
as you would have them do unto you:`" mark this royal law and command,
and cast it not out from amongst you; for you would not have any man to persecute you,
or imprison you?
Would you have any to banish you, and put you to death for your religion and worship?
Or would you have any man to spoil your goods, and to have you from your families,
and to keep you in prison till death, and while your wives are made widows,
and children fatherless, for your religion;
and so that which you would not have men do unto you, do not you unto others,
for the royal law of liberty respects no man`'s person; and so do unto others,
as you would have others do unto you, and this keeps all to an even balance,
and just weight; and so observe the royal law of liberty.

The two sons of Zebedee, when their mother came with them to Christ,
and desired of him that her two sons should sit one on his right hand,
and the other on the left hand in his kingdom; and when the ten other disciples heard it,
they were moved with indignation against the two brethren.
Here you may see what caused indignation; that is, one disciple to be above another;
but Jesus, who has all power in heaven and earth, to take away this offence,
and clear all, and stop all, he called the disciples to him,
and said,`" ye know that the princes of the Gentiles exercise dominion over them,
and they are called gracious lords;
but it shall not be so among you;`" and this was
to keep the ministers of the gospel equal brethren,
and not to exercise lordship and authority one over
another in matters of religion and faith;
for it was the Gentiles that exercised lordship: and to confirm this, he said,
"`whosoever will be chief among you, let him be a servant;
and the Son of man came not to be ministered unto, but to minister,
and to give his life a ransom for all: and be not ye called of men rabbi,
for one is your master, even Christ,
and ye all are brethren,`" and so not to be called lords like the Gentiles.
And Christ said, by way of prophesy, how that the Jews, and others, "`should kill,
and crucify, and scourge you in the synagogue, and from city to city,
that upon you may come all the righteous blood shed upon the earth,
from the blood of righteous Abel, to the blood of Zacharias, son of Barachias,
whom you slew betwixt the temple and the altar.`"
And so upon whom must all the righteous blood come
that has been shed in all Christendom about religion,
since Christ`'s and the apostles`' days,
who have manifested the spirit of the Jews in scourging in your synagogues,
and from place to place, such as Christ has sent amongst you?

And did not Christ say, "`how can ye,`" that follow such practices,
whom he called a generation of vipers, "`escape the damnation of hell?`"
and therefore, said he, "`be you witnesses,
that you are the children of them that killed the prophets;`" and
so is not the same to be said to you that persecute now?
Be you witnesses that you are the children of them that killed Christ and the apostles,
and his witnesses, and saints, and martyrs,
that kept the testimony of Jesus since the apostles`' days,
and that fill up the measure of your forefathers.
And did not Christ say, "`Oh, Jerusalem, Jerusalem, thou that killest the prophets,
and stonest them that are sent unto thee; how oft would I have gathered thee,
as a hen gathereth her chickens under her wings, but ye would not?
Behold, your houses are left desolate unto you.`"

Was not Jerusalem the highest place of profession, where those persecutors, murderers,
and killers of the Lord`'s prophets lived?
And what may be said of Christendom, and her highest place of worship,
look both among papists and protestants?
How many have they killed and persecuted that were sent among them by Christ?
Do you think that Christ doth not weep over you, whom you thus daily pierce;
and if the persecutors`' houses at Jerusalem were to be left desolate,
then what will become of your houses, who call yourselves christians,
and yet are found persecutors?
Do you think that all persecutors`' houses will not be left desolate,
though they be never so high professors of the scriptures;
will not their houses be left desolate of God and Christ?
read Matt.
23. And doth not Christ say, "`If thou hast any thing against thy brother,
leave thy gift at the altar, and go and be reconciled to thy brother,
and then offer it;`" and so should not all the christians in the whole world
be reconciled to one another before they offer their gift to God and Christ,
whose law is, "`They should love one another.`"

And whereas it is said, in 1 Pet. 2:17. "`Honour all men: love the brotherhood:
fear God, and honour the king.`"
+++[+++Mark,]
To fear God, is not to grieve nor offend him, but to be subject to him,
and reverence him; to honour all men, and to honour the king, is to have the king,
and all men in esteem; and to esteem the king, is not to hurt the king, nor any man;
and this lays waste all persecution, and persecutors;
for how can they say they esteem the king, or esteem any man, if they persecute him?
And so as all true christians are brethren in Christ Jesus,
they are to love the brotherhood, and so to keep the law and command of Christ;
and one christian persecuting another about religion and worship,
is not to love the brotherhood.

And at the council of the great professing Jews,
when the apostles were brought before the council and high priests,
and they charged them "`they should preach no more in the name of Jesus.`"
Then answered the apostles, "`whether they ought to obey God rather than man,
judge ye:`" and the apostle said further to them,
"`the God of our forefathers has raised up Jesus, whom you slew and hanged on a tree,
and God hath exalted him at his right hand to be a Prince, and a Saviour,
and to give repentance to Israel, and forgiveness of sins;`" and the apostle said,
"`we are witnesses of these things.`"
When the council heard these things, they who had before slain the Son,
took counsel together how they might slay the apostles.
Here all may see this persecuting murdering spirit, that persecuted in all ages.
Who may say now, had we been in the days of Christ and the apostles,
we would not have killed them; so they that do persecute,
may see they are in the same spirit as the persecutors were, in the apostles`' days,
and not in the spirit of Christ and the apostles.
But then stood up one in the council, when they took counsel to kill the apostles,
who was a pharisee, named Gamaliel, a doctor of the law,
held in repute among all the people,
and commanded to put the apostles forth a little space; and said unto them,
"`ye men of Israel,
take heed to yourselves what ye do touching these
men,`" when he had convinced them by arguments,
as Acts 5. "`Let them alone,`" said he, "`for if this counsel or this work be of men,
it will come to nought; but if it be of God, ye cannot overthrow it;
lest haply ye be found even to fight against God.`"
So, to Gamaliel the council and high priest agreed, and called the apostles,
whom they beat, and commanded them to speak no more in the name of Jesus;
yet the apostles departed,
rejoicing that they were counted worthy to suffer for his name;
and the apostles went and taught daily afterwards in the temple,
and every house Christ Jesus.

Now would some in our days say, the apostles brought sufferings upon their own heads,
and that they did it to provoke the magistrates, as some in our days have said;
and you may see this persecuting council, though they had agreed to Gamaliel,
yet they did persecute the apostles.
Have not they, called christians in Christendom, wanted this Gamaliel amongst them,
to moderate and to stay them from banishing, killing, burning, prisoning,
spoiling of goods?
For this Gamaliel was a Jew, and christians think themselves above a Jew:
but where is the Gamaliel`'s spirit amongst you, that say,
"`if it be of God it will stand;`" shewing that they
knew not whether it was of God or no?
and where is Gamaliel`'s caution in Christendom?
"`let them alone, restrain yourselves, if it be of God it will stand;
if it be the work of men, it will come to nought;
if it be of God you cannot overthrow it: therefore,
take heed lest you be found fighters against God.`"
And therefore,
what became of all the Jews that were found fighters against God and Christ?
and what is become of the pope, and all those persecuting powers before you?
And so see if there be not a Gamaliel`'s spirit and council wanting amongst you,
to moderate the persecuting spirit;
mind Gamaliel`'s counsel in Acts 5. For indeed the true christians are above Gamaliel,
for they know that which they preach to be of God,
though the moderate Gamaliel (whose spirit is beyond
the spirit that is in Christendom,) cried,
"`if it be of God,
ye cannot overthrow it,`" and so stopped them from violent persecution:
so had not the Christian priests and bishops need
of such a Gamaliel to moderate and regulate them,
and hold their reins from posting on to persecution?
And doth not the apostle say, "`that christians should not bite one another,
lest they should devour and consume one another, but love one another?`"
and so fulfill the law of Christ Jesus, which is the law of love,
for the law of love preserves; and if they keep the law of love,
they will not bite one another, nor consume one another, nor persecute one another,
nor spoil one another, as they have done.

And the apostle saith, to the christians in the primitive times,
before the apostacy came in, "`For though we walk in the flesh,
we do not war after the flesh, for the weapons of our warfare are not carnal,
but spiritual, mighty through God, to the pulling down of strong holds,
casting down of every imagination,
and every high thought that exalts itself against the knowledge of God,
bringing into captivity every thought to the obedience of Christ.`" 2 Cor. 10:2,4-5.

Now, +++[+++mark,]
"`the strong holds,`" the high imaginations, and high thoughts,
were not brought down by carnal weapons,nor that
which exalts itself against the knowledge of God,
but by spiritual weapons.
And here it is clear that one Christian did not persecute another with carnal weapons;
for their war was not after the flesh, nor their wrestling, was it with flesh and blood;
and that which gives the knowledge of God, is the light which shines in the heart;
and persecutors since the apostles`' days,
instead of plucking down the imaginations and high thoughts,
and bringing that down to the obedience of Christ, which exalts itself,
which is the spirit`'s work,
they wrestled with flesh and blood since the apostles`' days, and warred after the flesh,
not having the power as the apostles had:
and so have lost the apostles`' warfare and weapons, which were spiritual,
and gotten carnal in the room of them.
And the apostle also spoke to the Ephesians,
who were the christians in the primitive times, he said, "`my brethren,
be strong in the Lord, and in the power of his might, and put on the whole armour of God,
that you may be able to stand against the wiles of the devil.`"
This was God`'s armour, and not man`'s, "`having their loins girt with truth,
and the breastplate of salvation,
and their feet shod with the preparation of the gospel of peace,
and taking the shield of faith,
wherewith you shall be able to quench all the fiery darts of the wicked,
and take the helmet of salvation, and the sword of the spirit,
which is the word of God.`"

+++[+++Mark.]
These were the weapons of the christians in the primitive times,
which they warred withal, and wrestled withal against principalities and powers,
rulers of darkness of this world, and spiritual wickedness in high places;
"`for,`" saith he,
"`we do not wrestle against flesh and blood;`" so here it is plain
that the primitive christians did not use carnal weapons,
clubs and staves, like Judas`'s company, to persecute and haul one another,
or those that were: of a different mind to them, to prison, or banish them;
for if they had, they must have used carnal weapons, and wrestled with flesh and blood;
so with spiritual wickedness they wrestled with spiritual weapons,
which weapons the apostate christians are degenerated from, and therefore took up carnal;
and we know, and you should know, that the shield of faith,
and the breastplate of righteousness, and the helmet of salvation,
and the sword of the spirit, and the word of God, and the feet shod with the gospel,
and truth to be the girdle; these be the spiritual weapons,
and this is the armour of God, which the christians in the primitive times used,
by which they did not wrestle with flesh and blood,
nor war after the flesh with carnal weapons;
and they that have warred after the flesh with carnal weapons since the apostles`' days,
about religion and church, are in that spirit and power,
that the apostles and primitive christians warred against,
having the scriptures in their carnal minds, warring and wrestling with flesh and blood,
which are judged and reproved by the apostles`' and primitive christians`' words.

And to the christians in the primitive times,
the apostles`' doctrine was they were not to avenge themselves,
but rather to give place to wrath, "`for vengeance is mine, saith the Lord,
and I will repay it;`" and so they were to follow peace with all men, and holiness,
without which no man should see the Lord; "`not to render evil for evil,
nor railing for railing; but contrariwise blessing,
knowing that they are thereunto called, that they should inherit the blessing.`" 1 Pet. 3:9.
Heb.
12. And they were to overcome evil with good,
and "`thou shalt heap coals of fire on his head in so doing.
Therefore, if possible, as much as in you lies, live peaceably with all men,
recompense to no man evil for evil.`"

Now people,
you may see how this doctrine and practice of the
primitive christians is laid aside in Christendom,
by such as have a form of godliness, but deny the power, who are to be turned away from,
who have rendered evil for evil, and takes revenge, as 2 Tim.
3+++.+++ And the apostle said, "`every soul must be subject to the higher power:`" +++[+++mark,]
the soul is immortal, and the power is so; for he says,
"`there is no power but it is of God, and the powers that be are ordained of God,
and he that resisteth the power,
resisteth the ordinance of God;`" so the power is not to be spoke against, nor resisted;
for it being ordained of God, the soul must be subject to it,
"`for rulers are not a terror to good works, but to evil:
wilt thou then not be afraid of the power, do that which is good,
and thou shalt have praise of the same.`"

+++[+++Mark.]
This power is not against the good, but against the evil; it is not a terror to the good,
but to the evil; the good has its praise by the power, and is not afraid of it,
but the evil is afraid, and it is a terror to it;
"`so he is a minister of God to thee for good;
but he that doth evil is afraid of the power, for he beareth not the sword in vain;
for he is the minister of God to revenge the wrath upon him that doth evil.`"
So not upon the good; so here he makes a distinction, the good from the evil,
the higher power is a praise to the good;
wherefore we must needs be subject not only for wrath, but also for conscience sake,
that is, to be subject to the power that is a praise to the good,
and a terror to the evil: now when magistrates acted contrary to the power,
(as you may read in the scripture,) ordained of God,
then he sent his prophets and servants,
to cry against the corruptions of the magistrates, (not against the power,
which God had ordained,) and such magistrates if they did not return to the power,
you may read how often God overturned them; and such magistrates,
you may see often in the scriptures, turned the sword backwards against the righteous,
and let the guilty go free, and made no difference between the precious and the vile;
and for this cause have we paid the tribute and dues; so custom to whom custom,
honour to whom honour, fear to whom fear; so we have not been behind on our parts,
they have had their tribute, and the magistrates their customs and their dues,
though they have turned their sword against us, against the good; and drunkards,
swearers and evildoers set at liberty; so we have not been behind on our hands,
though they have been on theirs, but we leave them all to the Lord,
to plead with them all.

And the apostle saith to the christians, "`owe nothing to any man, but love one another,
for love fulfils the law.`"
So they that do not love one another, and are out of love,
it is clear do not fulfill the law, but break it;
and are not christians great debtors in this?
And the apostle saith, "`thou shalt not commit adultery, nor kill, nor steal,
nor bear false witness, nor covet;`" if there be any other commandment,
it is briefly comprehended in this saying,
"`thou shalt love thy neigbour as thyself;`" and here it is clear, this higher power,
which God`'s ministers attend upon continually,
is not against the liberty of true christians,
nor does it take hold upon people in matters of religion and worship; but such as kill,
commit adultery, steal, and covet;
here is nothing of this higher power`'s meddling with difference in religion,
or to be any terror to them, but to the evildoers;
but this higher power is a praise to all that own God, and profess Christ Jesus,
and live in his life;
and all christians are "`to stand fast in the liberty
wherewith Christ hath made them free.`"

Now the apostle, who said, "`tribute to whom tribute,
and custom to whom custom,`" this was to the magistrates,
and that they should have their dues; this doth not concern the priests`' tithes,
for the apostle plainly declared against tithes, and said,
"`the law was changed by which the priesthood was made,
and the commandment disannulled which gave tithes.`"
Heb. 7. and he preached up another priesthood,
"`Christ Jesus made higher than the heavens.`"
Now as the apostle saith, "`love works no evil to its neighbour,
and love is the fulfilling of the law,`" and this keeps him out of killing, stealing,
committing adultery, and bearing false witness,
and this keeps him from under the magistrates`' sword, who is subject to the power,
which is a praise to him that does well; and he that loves his neighbour as himself,
he will not kill his neighbour, nor bear false witness against him, nor steal from him,
nor commit adultery,
for those are the actions of the evildoer the law is a terror against. Rom. 13:1-10.

The apostle saith to the Galatians, the law is fulfilled in one word,
"`thou shalt love thy neighbour as thyself;`" so if the law be fulfilled,
then it doth not take hold upon such that love their neighbour as themselves;
and ye that be led by the spirit of God, you are not under the law;
for they that are led by the evil spirit into drunkenness, envy, and murder, and strife,
and hatred; such fruits come under the law, and the higher power is a terror to them.
Gal. 5. And they that love their neighbour as themselves, do not bite, nor devour,
nor consume one another; but they that do hate their neighbours,
and bite and consume one another, these do not fulfill the law, but break it;
as cast your eye over Christendom, and you may see these fruits;
and the persecution came for the cross of Christ`'s sake, which cross was the power,
before the wood and stone was;
and therefore they that do persecute be out of the higher power, and cross,
and life of Christ Jesus.

And the apostle says to Timothy, "`we know the law is good, if a man use it lawfully.`"
Now, +++[+++mark,]
a man must use it lawfully, and then it is good,
"`knowing this,`" saith the great apostle of Christ Jesus,
"`that the law is not made for a righteous man.`"
Therefore they that be righteous men, and the Quakers,
whom no evil can be charged against in their lives and conversations,
the law is not to be laid upon them, if it be used lawfully;
"`for,`" saith the great apostle, "`the law was made for the lawless, disobedient,
for sinners, unholy, profane, murderers of fathers and mothers, man-slayers,
whoremongers, such as defile themselves with mankind, men-stealers, liars,
perjured persons,`" to such the law is a terror, for these be the evildoers,
which law is a praise to them that be good;
and so the law here was not made to limit people from worshipping God,
that owned God and Christ; but for such above-mentioned,
and this is according to sound doctrine, and also according to the blessed gospel of God,
which was committed to the apostles`' trust,
which he taught and laid down to be observed amongst the primitive Christians,
which others, apostatized from his life, are degenerated from,
and have not observed his sound doctrine, but many have turned the sword backward,
and the laws upon righteous men, which it was not made for,
and that has not been according to the glorious gospel of the blessed God,
nor according to the higher power, but the devil, from whence persecution has arisen.

When the pharisees took counsel how they might entangle Christ in his talk,
they sent from their councils their disciples with the Herodians, saying, "`we know,
master, that thou art true, neither carest thou for any man,
for thou regardest not the person of men, tell us, therefore, what thinkest thou,
is it lawful to give tribute to Caesar, or not?`"
Jesus perceiving their wickedness, said, "`why tempt you me, ye hypocrites?
Show me the tribute-money, and they brought unto him a penny, he said unto them,
whose is this image, and superscription?
they said unto him, Caesar`'s: then said he unto them,
render therefore unto Caesar the things that are Caesar`'s,
and to God the things that are God`'s.`"

+++[+++Mark,]
Those that came to tempt Christ were of the Jews, the great professors,
and Caesar was a heathen; and the Jews being under, the power of the heathen,
having lost the life of that which they did profess,
that spirit in them would have brought Christ under Caesar, by the temptations;
and these he calls hypocrites, who professed the scriptures,
and were not in the life of them, as all others are as this day,
who are found in the same nature that would ensnare; but Christ,
who is the wisdom of God, confounded them.
And Caesar must have his things, and what are his things, but his tribute, his custom,
and that which his superscription is upon?
And so other kings, whose image is set upon their money, must have their dues:
but as well as people, God must have his things of Caesar,
and the council of the great professing Jews; and what are God`'s things?
where his image and superscription is written in the heart, God must have his things;
so see each superscription and image.
So let Caesar have his due where his superscription and image is;
so the superscription and image of Caesar to Caesar,
and God`'s writing and image to himself; for the holy one must have his liberty,
and not be limited, and so here everything is in its place. Matt. 22:17.

As the apostle saith, "`whatsoever is not of faith is sin.`"
Rom. 14:23, shewing, that the true faith is not sin,
for it is that which gives the victory over sin, and access to God,
and purifies the heart; and therefore to bring people to that which is not of faith,
is to bring them into sin, and to make them to make shipwreck of their faith,
and of a good conscience,
seeing that the mystery of faith is held in the good and pure conscience;
therefore the true faith must have its liberty, which gives the victory,
in which God is pleased, and who are of faith are of Abraham.

And the great apostle Paul, saith to the Corinthians,
"`that we have not dominion or power over your faith, but we are helpers of your joy,
for by faith ye stand.`"
Now, +++[+++mark,]
all ye that are in Christendom, that call yourselves christians,
who persecute about religion, have not you degenerated from the apostles,
that would have dominion and power over men`'s faith?
Is not the case plain,
that you would not have the faith which is the gift of God have its liberty?
And that you are out of the true faith, the gift of God, which the apostles were in,
and so are no helpers of the joy of them that are in the true faith,
you yourselves not standing by it:
and why did the apostle bid them stand fast in the faith,
as knowing there were some who would oppose their faith.
1 Cor. 16:13; 2 Cor. 1:24.

And had not the apostles council amongst themselves, for doth he not say,
"`we have not dominion or power over your faith;`"
for if they had said they had power over their faith,
they might have said they had power over the gift of God,
for "`faith was the gift of God;`" and that they had power over Christ,
"`who was the author of faith, and finisher of it;`" but the apostle said,
"`they were helpers of one another`'s joy,
in the faith they were to build up one another in:`"
so it is clear that God must have his liberty,
who is the author and finisher of faith, which men must not have power over,
no not the apostles, for by, one faith they all stand.

And the gospel which the apostles preached, which they "`had not received of man,
nor by man, but by the revelation of Jesus Christ,
which was the power of God unto salvation to every one that believeth;`" this gospel,
the power of God, which is liberty, is to have its liberty,
and men must have their liberty in it; for if men turn against the power,
they turn against the gospel, and bring destruction upon themselves, in persecuting.
