== A Hammer





To break down all Invented Images, Image-makers, and Image-worshippers.
Showing how contrary they are both to the Law and Gospel.





By this, therefore, shall the Iniquity of Jacob be purged, and this is all the Fruit to take away his Sin; when he makes all the stones of the altar like chalk-stones that are beaten in sunder, the groves and images shall not stand up. Isa. 27:9.






Thou sawest till that a Stone was cut out of the Mountain without Hands, which smote the Image upon his Feet, that were of Iron and Clay; and break them to pieces. Dan. 2:34.






Ye shall defile the covering of thy graven Images of silver, and the ornament of thy molten Images of gold: thou shalt cast them away as a menstruous cloth, thou shalt say unto it, `"get thee hence.`"
Isa. 30.:22.





Thy graven Images also will I cut off; and thy standing Images out of the midst of thee; and thou shalt no more worship the Works of thy Hands. Micah 5:13.
By G. F.

The Lord God made man and woman in his own image, and in his own likeness,
and set them above all the works of his hand;
but when man and woman lost the image of God, and his likeness within them,
by transgressing his command, in eating of that which God had forbidden;
then by transgressing of his command, the serpent that was under them, got over them,
and in them, so that the body of death and sin then entered into man and woman,
for sin brings death, and then it came to be a body in man and woman; and so from that,
all transgression arose, and the original sin in man and woman;
so the devil was the beginning of it, in man and woman, and not God;
and so this death reigned in man and woman from Adam,
the entering of it by transgression until the law came,
which restrained man and woman from sin, and so from that that brought death,
so that death should not reign; but the law of God,
which was added because of transgression: and so the law came on the top of man,
though it answered the witness of God in him, which he had transgressed.

And though the law made nothing perfect, not taking away the root of sin,
but taking hold upon the actions; yet Christ, who destroyed death with his works,
takes away the root of sin, and destroys the beginning of it, to wit, the original,
the devil, that abode not in the truth himself, who led man and woman out of truth:
and so to be like him in his image, and not like God in his image; and therefore,
Christ who destroyed the devil, renews man again in the image of God.

And now all men that be in the image of the devil, out of truth, out of the image of God,
they are them that make images, likenesses, representations of things in heaven,
of things in the earth, and of things in the waters, above and below.

So these would all be imitators of the Creator,
and of the maker of all things in the heaven, in the earth, in the sea,
and in the waters, above and below, though they do not worship them;
and this is forbidden both to worship and to make them.

And therefore, all friends and people, pluck down your images, your likenesses,
your pictures, and your representation of things in heaven, things in the earth,
and things in the waters; I say, pluck them out of your houses, walls, and signs,
or other places, that none of you be found imitators of his Creator,
whom you should serve and worship; and not observe the idle lazy mind,
that would go invent and make things like a Creator and Maker,
any thing (I say) that is in heaven, the earth, or in the waters above or below.
(For mind,) while man was in the image of God, and his likeness, and the woman,
they did not make any likenesses, or images of things in heaven, or earth, or water.
But when man lost this image of God, then they did begin to make such things,
as the stock of Nimrod.
In Ninos`' time they began to make images of their children,
and indulge them that would worship them; and so afterwards set them up by a law,
their images and likenesses to be worshipped,
and at last they worshipped four-footed beasts, as you may see in the Romans,
and creeping things. Rom. 1:23.


So, when Moses came, images were forbidden, the maker and the worshipper,
and when Christ came, he brings people into the image of God and his likeness,
as man was in the beginning.
And the Jews that did forsake the law of God, see how they did run after images,
stargazers, and monthly prognosticators, which was forbidden by the prophets of God;
and the apostles brought up people into the image of God,
above the Jews`' true figures and shadows, and types of Christ the substance;
as the Jews in their time, with their types and shadows, and figures of Christ,
were to stand over all the heathen images, likenesses, and gods that they had made;
but Christ ends the true figures and shadows, and the apostle preached them down,
not only the Gentiles`' images, and likenesses,
but the true types and figures of Christ Jesus; for they preached up the substance,
Christ Jesus.

But now, since the apostles`' days, are you like christians that go under the name?
See what images, likenesses, representations, what an host,
or a multitude they have made, by which they have almost filled Christendom; yea,
many adore them.
They made images of God, they made images of Christ, of the apostles, and prophets,
and them they call their saints; yea, and set them in their books, their bibles,
their signposts, and in their houses, since they have lost the image of God,
as was in the apostles`' days among the primitive christians; and therefore,
see what dark spirit hath set up here among christians
such things as was forbidden by the law and gospel,
so that there was no image before the fall, nor likeness, nor representation;
but in the fall there hath been, and is,
and was among the Jews when they went from the law of God.
So among the christians, there is who have gone from the power of God, the gospel.

So in the restoration of Christ Jesus there is no image, no likeness, no representation,
who are brought by Christ into the image of God, as was Adam and Eve, before the fall.
So there was no image or likeness before man`'s fall, in the fall there was;
which by the law was forbidden, and by the gospel; and since they have lost the gospel,
they have set them up again, which are now forbidden by the gospel, the power of God,
which was before the devil was; and therefore, down and away with all your images,
likenesses, representations, you imitators of God, your Maker and Creator,
who hath made things, likenesses of things in heaven, and in earth, and in the waters.
I say, down with them out of your houses, and off your signposts, with the power of God;
for as that arises in your hearts, the nature that doth appertain to them, or adore them,
or worship them, and the makers of them, by the power of God are thrown down,
it and them both; which power of God brings you up into the image of God,
and his likeness.
"`Thus saith the Lord God, I am the Lord which brought you out of the land of Egypt,
and the house of bondage: thou shalt have no other gods before me.`"
Exod.
20.

Now here you may see God`'s people were brought out of Egypt,
out of the house of bondage: "`The Lord saith, thou shalt make thee no graven images,
nor any similitude of things that are in heaven above, neither in the earth beneath,
nor in the waters under the earth: and thou shalt not bow down to them, nor serve them.`"

Now they that are brought out of spiritual Egypt, that house of bondage,
can neither make images or likenesses, nor worship them;
but the spiritual Egypt as the outward Egypt doth.

Neither shall ye make gods of silver, nor gods of gold.

Now, you that make gods and Christs of bread and wine,
and make your pictures of Christ of gold and silver, you are the spiritual Egyptians,
and in the house of bondage, which they that come out of your house of bondage,
and your spiritual Egypt, utterly deny.

And the Lord said, in Exod.
23. "`Ye shall take heed to all things that I say unto you;
ye shall make no mention of the names of other gods;
(mark,) neither shall it be heard out of thy mouth.`"

So, hear no gods, but the living God, to be heard out of the mouth of his people,
nor to be made mention of; and they are such as bear his image.
"`Ye shall overthrow their altars, and break their images to pieces,
and cut down their groves.`"
So all that live in the power of God, that be the true christians in the image of God,
break down that nature in them that appertained to images and outward altars.
For the Jews were to break down the heathens,
but the true christians break down both Jews and heathens by the power of God,
and that nature appertains to either of them.
"`Thou shalt make thee no god of metals.`"
Here the Lord forbids it among the Jews, in Exod.
34. Therefore, is it not forbid among the christians?
And why do you make your pictures of silver and of gold, of God, and crucifixes of Christ?
Do not you adore them, and reverence them, and bow down to them?
yea to the images of the apostles which you made,
who do not bow down to the image of God; and do bow to the image,
and do not bow to the image of Christ Jesus, which the prophets and the apostles were in,
but bow to your own images, the works of your own hands.
"`You shall not turn unto idols, nor make to yourselves molten Gods; I am the Lord.`"
Leviti.
19. Here the Lord forbid idols and molten Gods, for he is the Lord that made all things;
"`You shall make you no idols, nor graven images, nor rear up any pillars,
neither shall you set up an image of stone in your land, to bow down to it;
for I am the Lord your God; for I will destroy your high places,
and cut down your images, and cast your carcasses upon the bodies of your idols,
and my soul shall abhor you.`"
Levit.
26. And what, do christians set up images in the land, or idols, or representations,
and bow down to them which God forbid among the Jews?
For, do not you set up images of crosses, images of stone in your land,
which are forbidden by the law of God, and much more by the gospel.

And in Numbers 33. "`Thus saith the Lord to the children of Israel.
When they came into the land of Canaan, they should destroy all their pictures,
and break in sunder all their images of metals, and pluck down their high places.`"
And now the Jews that were disobedient to God, they worship the pictures,
and images of metals, like such christians,
that are disobedient to the gospel of Christ Jesus,
who kneel before the images of metals and pictures, which is forbidden.

And so in Deut.
4+++.+++ When the Lord spoke unto the children of Israel by Moses, saying,
"`Take good heed to yourselves,
(for you saw no image in the day of the Lord speaking to you in Horeb,
out of the midst of the fire,) that ye corrupt not yourselves, and make graven images,
or representations of any figure, whether it be the likeness of male or female,
the likeness of beasts on the earth, the likeness of feathered fowls,
the likeness of any thing that creeps upon the earth,
the likeness of any thing that is in the waters, lest thou lift up thy eye to heaven,
and see the sun, moon, and stars, with all the host of heaven,
and shalt be driven to worship them,
which the Lord thy God hath distributed to all people under the whole heaven.`"
So here it is clear,
God`'s hand is full against all images and likenesses of any thing in heaven,
in the earth, and in the waters, lest they should be driven to worship them,
and adore them.
But all such things are to be broken down by the Jews; and what,
must they now be set up by the christians, and adored and worshipped?
Yea, the image of the apostles, angels, and Christ, and God,
which all by the power of God and the gospel is judged down among the true christians,
as the law of God did among the Jews, for to convince the Jews, Moses said,
"`They saw no image when the Lord spoke to them out of the fire.`"

And in Deut.
5+++.+++ There you may see how it is contrary to the law and covenant of God to make images;
graven images, or likenesses, or other Gods of any thing in heaven, in the earth,
and in the waters.
And none shall bow down themselves, nor worship them, nor serve them.
And doth not Christendom serve images, likenesses, and representations,
and bow down to them, which they made with their own hands.

God forbid the Jews to marry with them that made images, and served other gods.
Deut.
7+++.+++ For God`'s wrath was hot against them that served images and other gods;
and therefore, to stop his wrath, they were neither to make other gods or images,
but cut them down and burn them with fire.
So the nature of all christians that invent images, likenesses,
and representations of God, or Christ, or the prophets, or apostles,
must be burnt with fire, and cut down with the sword of the spirit for the fire.

And in Deut.
9+++.+++ Where you may see the Jews had transgressed the law of God,
and made a calf which they had molten of the treasures
which the Jews brought out of Egypt,
and therefore, take heed all ye christians that are come out of spiritual Egypt,
that the treasures you bring out of spiritual Egypt with you,
you do not make a God of it at last.
But see what Moses did, the Lord sent him,
and bid him "`go quickly unto the children of Israel,
for they have corrupted their ways with making a molten image.`"
And therefore said the Lord, "`they were a stiff-necked people,
let me alone that I may destroy them, and put their name out from under heaven.`"

And so consider all ye christians,
have you not corrupted your ways that hath made images and likenesses,
and your molten images, do you think your name will always stand under heaven?
and do you think the Lord will not bring destruction
upon that nature and wisdom which hath invented them.
And as Moses stamped to powder that molten image that the outward Jews had made to worship;
will not Christ Jesus stamp to powder your images with his power and seed,
which you have made and worshipped, and adored.
And not only your images but the nature in you which have invented them,
and holds them up?

"`Thou shalt set thee up no pillar, which thing the Lord thy God hateth.`"
Deut.
16. Do you regard the Lord, that set up such things, and love such things?
Do not you love that which God hateth?
And how can you but grieve the Lord, and so bring his wrath upon you?

Look upon your pillars; "`cursed be the man that maketh any graven or molten image,
which is an abomination unto the Lord, the work of the hand of the craftsman,
and putteth it into a secret place: and let all the people say, amen.`" Duet. 27:15.
So you that do make any molten or graven image,
or cause any workman to make them;
you cause them to make that which is an abomination to God.
But do not you here make your graven images, and do this abomination,
and put them in your pockets, and hang them about your necks?
And so are you not here under a curse, in that which is an abomination to the Lord.

So in Deut.
29. "`Ye know how you have dwelt in the land of Egypt,
and how you came through the nations which you passed by;
and you have seen their abominations, and their idols, wood and stone, silver and gold,
which were among them; and that there should not be among you man, or woman, or family,
or tribe, which should turn his heart away this day from the Lord our God,
to go and serve the gods of those nations.`"
So here the Jews might see those idols of wood and stone, silver and gold,
among other nations, which the Lord let them see forbidden;
yet that these Jews would go afterwards and set up images of wood, and of stone, of gold,
and of silver, like other nations; and that christians should now do the same,
which is all abomination and forbidden.

And in Judges 17. "`Micah had an house of gods,`" which was contrary to the law of God.
So look among many christians, see if they have not many houses full of images,
and pictures, and representations contrary to the law of God and the gospel;
and how zealous these were for images, as zealous as many christians are:
see what a great deal of money they give to make images, such things as God forbade.
Judg.
17. And in Psalm 60, where you may see the images among the Philistines and their gods.
So they that make images, christians, heathens, and Jews, are in one nature, and spirit,
and out of the image of God, and they need not find fault with the heathens,
nor the Jews, nor christians, that be image-makers,
for they be natural born children of one illnature,
both rebellious to the commands of God.
For did not the Philistines think that their images and idols did help them,
and the Jews that transgressed the law of God?
And do not you think, that are called christians, that your images, idols,
and representations help you, and put you in remembrance?
And so you have forsaken the spirit of God,
and got up a visible to put you in remembrance of the invisible God.
For did not the Philistines carry Saul`'s head,
and publish throughout their idol`'s temple,
and so thought their images and their idols got them victory.
And do not you place much upon your images,
and say that you have done miracles by your images and pictures,
and yet are called christians.
But David and his men burnt the images of the Philistines.
How can you profess David, and sing his Psalms, who set up makers of images,
and would have others to do the like.
For David saith, "`The idols of the heathens are silver and gold,
the work of men`'s hands: and they have ears and hear not,
they have mouths and speak not, eyes and see not, and there is no breath in them,
and they that make them are like unto them, so are all that trust in them.`"
Now all ye image-makers in Christendom, how can you escape David`'s judgments here,
or get from under them?

Psalm 135, and 115. "`Our God is in heaven, and he doth whatsoever he will;
but their idols are silver and gold, the works of men`'s hands;
they have hands and handle not, feet and walk not,
neither make they any sound with their throat; they that make them are like unto them,
and so are all that trust in them.`"

Now all ye in Christendom that are makers of images, pictures, idols,
and representations, are you better image-makers than were in the days of David?
Can either your gods, or pictures, or images speak, or handle,
or sound with their throats?
but you are as the heathen that David reproves, that make such things now in our days,
who serve their idols which was their ruin in David`'s days, and so it will be yours.

Psalm 106. "`When they made a calf in Horeb, and worshipped the molten image,
they turned their glory into the similitude of a bullock which eat grass,
and so forgot God,`" and so have you turned your glory into the similitudes,
and pictures, and images of things, and forgot your Creator and your Saviour.
"`And therefore a fire from the Lord was kindled against the Jews, in their assemblies,
and the flame burnt up the wicked.`"
And now can you escape?
You cannot, but are guilty of the same thing.

And in Psalm 97, "`Confounded be all they that serve images or trust in them,
and that glory in idols.`"
So you must not think to stand, that glory in your idols, and serve your graven images,
together with your pictures, for you are in the nature that is to be confounded.

And in 1 Kings 14. "`How Judah wrought wickedness in the sight of the Lord,
and provoked him more with their sins which they had committed,
than all that which their forefathers had done,
for they made them high places and images.`"
And so you that make images, and set them up in your high places,
do not you provoke God more than your first fathers, the primitive christians?
Now Asa, the king, he takes away the Sodomites out of the land,
and puts away all the idols that his forefathers had made,
and this man did uprightly in the eye of the Lord, as did David his father.
Now if he did right in the eyes of the Lord that put away images and idols,
do not you do evil in the eye of the Lord,
that set up images and pictures in Christendom, and compel people to worship them;
that people go in danger of their lives if they will not
pull off their hats as they go by your images and crucifixes?

1 Kings 21. "`There was none like Ahab,
who did sell himself to work wickedness in the sight of the Lord:
he did exceeding abominable in following idols, according to the Ammorites,
who the lords cast out before the children of Israel.`"
Now this Ahab humbled himself, but have you humbled yourselves for your bloodshed,
your wickedness and your abominations,
in making images and setting them up in the land and nation,
which was a wicked and an abominable thing in Ahab?
And what, is it become a good thing now for you that call yourselves christians,
and look upon yourselves to be above the Jews?
what, will you say that Christ hath redeemed you to do all these abominations,
and to make all those images, and pictures and representations?
do you not abuse both Christ, and the law of God in so doing?

In 2 Kings 3. "`Now Jeroboam did work evil in the sight of the Lord,
but not like his father Ahab, nor his mother Jezebel,
yet he took away the images of Baal that his father had made.`"
So it shows that you are not come so far as wicked Jeroboam, that are setting up images,
for you are not to make an image of God, or of Christ, you are forbidden:
for "`thou shalt not make an image of any thing in heaven or in earth.`"

2 Kings 10. See how Jehu destroyed the images and idols of Baal,
and brought them out of the temple and burnt them;
and what a zeal he had against the priests.
And in 2 Kings 11. How the Jews destroyed the house of Baal, their altars and images;
and yet your priests, and pope, and others are setting them up,
that look upon yourselves beyond Jehu, and a state beyond the law,
whose works are judged by the law.
In that 2 Kings 17, and 18, you may see how they left all the commands of God,
and made molten images, and two calves, and made groves,
and worshipped all the host of heaven, and served Baal, and used witchcraft.
And so, you called christians, have you not left all the commands of God,
who have made molten images, pictures, and likenesses, and adore them, and worship them:
yea, and have you not made images of the very host of heaven, of things in heaven,
things in earth, and things in the waters?
And persecute others because they would not worship things that you have set up,
and so are neither true Jews, nor true christians, but breakers both of law and gospel.

Now Hezekiah takes away their high places, and breaks down their images,
and cuts down their groves,
and breaks in pieces the brazen serpent that Moses made for the children of Israel,
when they burnt incense to it.
For this man did that which was right in the sight of God;
but you have not done right that set up images, for you do wickedly in God`'s sight,
as Ahab did, for it was time to break down that brazen serpent,
when they did once offer incense to it.

In 2 Kings 20. There you may see how Manasseh, the king of Israel,
led the people out of the way, to do wickedly, yea more wickedly than the heathen people,
whom the Lord destroyed before the children of Israel;
for he set up the images of the groves in the temple.
And is not this like many of the christians that set up images in their steeple-houses?
And if Manasseh led the people out of the way,
and made them do wickedly in following images and worshipping them,
have not you done the same, like Manasseh, that have set up images,
and caused people to follow them and worship them?

In 2 Kings 23. See how Josiah, the king, put down their idols,
and broke their images in pieces, and cut down their groves.
Here you may see how this man fulfilled the law of God;
and they that break the law of God set up images, and they that keep it, break them down;
so now you that put them up are breakers of the law.

And see how the fierce wrath of the Lord was kindled against Judah,
because of all the provocations wherewith Manasseh had provoked him;
so that the Lord said, "`I will put Judah out of my sight as I have put away Israel:
and I will cast off the city of Jerusalem.`"

Therefore, what will become of all you christians that follow Manasseh`'s steps?

So, 1 Chron.
16. David said, "`all the gods of the people are idols, but the Lord made the heaven.`"
So whosoever makes a god, or a christ for people, and images, and representations,
keep their minds from the Lord that made heaven;
and in the transgression of the law of God and themselves, rebels.

And 2 Chron.
14. Asa destroyed the idolaters and commanded the people to serve the true God:
for "`he brake down their images, and their altars, and their strange gods,
which they had made.`"

And Azariah in 2 Chron.
15. purged his country of idols, and bade the people, "`be strong,
and let not your hands be weak.`"

And so Jehosaphat in 2 Chronicles 17. "`abolished idolatry,
and caused the people to be taught the law of God against it.`"
Now these that did keep the law of God, whose hearts were upright before the Lord,
and did see the perfect law of God fulfilled, judge you that call yourselves christians,
and have founded those things that are judged by the law of God;
therefore your hearts are unright and imperfect before him.

And in 2 Chron.
23. There you may see how the people went to the house of Baal,
and broke and destroyed both their altars and their
images and yet these were called the Lord`'s people.
Therefore, you that set them up, whose people are you?

And in 2 Chron.
24. Where you may see, "`they that left the house of God, and the law of God,
and served groves and idols, wrath came upon Judah.`"
And God sent a prophet amongst them to bring them again unto the Lord,
and they stoned him, Zachariah by name; and thus did Joash, the king.
And so consider you that do set up images to lead people from the Lord,
have you not stoned and killed them that came and declared against you and them both?
for you have gone yourselves from the way of the Lord, and have drawn away others;
and so you persecute them that endeavour to draw you again to the way of God,
that his wrath may not come upon you.

In 2 Chron.
28. King Ahaz was an idolator,
"`and he did not that which was upright in the sight of God,
he walked in the ways of the kings of Israel, and made molten images to Balaam,
and burnt incense in the valley of the son of Hinnom:`" and at last "`burnt his son.`"
Here you may see when people go off from the law of God,
what wickedness they run into at the last; and therefore,
have not you that are called christians burnt them
which you have called the sons of the church?
yea, such which you have baptized into your faith;
and then because they will not follow your ways and religion, have you not burnt them,
and stoned them?
But consider the end of you, and them that have broke the law of God.

And in 2 Chron.
31. Here you may see how the people in Hezekiah`'s days destroyed idolatry,
and therefore, they were commended by God, and good men.

Likewise Manasses, in 2 Chron.
33. "`And the Lord spoke unto Manasseh,
who had set up graven images in the house of God,`" as you do in your steeple-houses,
your pictures and your images, but Manasses would not regard, nor the people.
So, will you regard, or do you regard the Lord and his law,
you that be image and picture-makers, or setters of them up, adorers,
and worshippers of them.
But when Manasseh was in tribulation, in his fetters and chains and carried into Babylon,
then he considered how he had transgressed the law of God;
and so may some of you when you are brought into troubles.
But while you are full and fat, you will kick against the Lord and his law.
And then Manasseh comes to abolish idolatry,
and to take away images out of the Lord`'s house; but when God brings trouble upon you,
it may be some of you will consider of it.

And in the 34th chapter "`Josiah purged Jerusalem and Judah from the high places,
and the groves, graven images, and molten images,
and broke them down and stamped them to powder,
and strewed them upon the graves of them that had sacrificed to them.`"
Now here was a man of God, which you are unlike unto,
that are now setting up such things as he threw down.
"`For the eyes of the Lord are upon all the ways of man, and he sees all his goings:
there is no darkness, nor shadow of death, that the works of darkness,
and the workers of iniquity might be hid therein, but he searcheth them out all.`"
Job 34.

And all you image-makers, and picture-makers, that set them up,
which lead people with them, and sink them to the earth to bow to your handwork,
that none can say, "`where is God that made me, which gave me songs in the night?`"

Isa.
2+++.+++ He said, "`the land is full of idolatry,
and they worship the works of their own hands:
but when the haughtiness of man is brought low, the Lord shall be exalted:
then the idols will be destroyed,
and they shall cast away their idols of silver and of gold,
which they made themselves to worship, and shall go into the holes of the rocks,
from the fear of the Lord, and the glory of his majesty,
when he shall arise to shake terribly the earth.`"
And therefore look to it, you christians, your earth is not shaken; yea,
your idols are not cast away, your loftiness and haughtiness is not brought low,
your land is full of images, that you are not creeping into the holes of the rocks,
to hide yourselves from the fear of the Lord, and the glory of his majesty.

And in Isa.
10. The Lord hath said, "`like as my hand hath found out the kingdom of the idols,
seeing their idols were above Jerusalem, and above Samaria: shall not I,
as I have done to Samaria, and to the idols thereof, so do unto Jerusalem,
and to the idols thereof?`"
and so will not the Lord do unto the christian idols, and idolaters, and image-makers?
For, are not your actions open to his eye?
For you that are image-makers, and idol-makers, have forgot the Lord of your salvation,
and have not remembered the God of your strength.

Isa.
17, and 19. "`The burden of Egypt: behold the Lord rode upon swift clouds,
and shall come upon Egypt, and the idols of Egypt shall be moved at his presence,
and the heart of Egypt shall melt in the midst of her.`"
Now consider, you spiritual Egyptians with your idols and images,
think you not that the Lord will come upon you that are spiritual Egypt?
And do you not think that your Egypt shall be moved at his presence,
and the heart of your Egypt shall melt in the midst of you.

Isa.
27. "`For God will purge away the iniquity of Jacob,
and his fruits of sin shall be taken away,
when he shall make all the stones of the altar as chalk-stones, broken in pieces,
that the groves and images may not stand up: his defenced cities shall be desolate,
and his habitation shall be forsaken, and left like a wilderness.`"
Now consider this, christians, ye are unpurged, and have images,
you are in your iniquities, where your images yet stand up,
your defenced cities are not yet desolate yet, and your habitations are not yet forsaken,
nor made like a wilderness: but look for all this to come to pass.

Isa.
30. "`Ye shall pollute the cover of the images of silver,
and the rich ornament of thine images of gold, and cast them away as a menstruous cloth;
and thou shalt say unto it, get thee hence: then shall the Lord give rain unto thy seed,
when thou shalt sow the ground, and the increase of the earth, and it shall be fat,
and as oil: in that day shall thy cattle be fed in large pastures.`"
But you called christians,
would you not be ready to kill and burn such as shall be ready
to pollute your cover and rich ornaments of the images of gold,
and cast them away as a menstruous cloth; and say, get thee hence:
but this is not come to you yet, there is adoring of them, you have not cast them away,
your sin is still upon you, you do not esteem them as a menstruous cloth,
you are afraid they should be polluted, who regard neither God, nor his law,
nor his prophets.
"`O, ye children of Israel, turn again in as much as ye are forsaken,
you are sunk deep in rebellion: in that day that you turn again,
you shall cast away your idols of silver, and of gold, which your hands have made,
even as sin.`"
So you may not make images now in Christendom, and pictures, and representations,
your hands make a sin, and you wont cast it away until you return to the way of the Lord,
for out of the way of God, you must look for nothing but wrath and judgment.

Isa.
40. "`To whom will you liken God?
What similitude will you set up to him?
The workman melts an image, and the goldsmith beats it out into gold,
and the goldsmith makes silver plates.
"`The poor chooses out a tree that will not rot, he seeks unto him a cunning workman,
to prepare an image that shall not be moved.`"
And is not this spirit also among you that are called christians, image-makers, of wood,
of silver, of gold and of stone?
To whom will you liken God or Christ?
To a piece of bread, and to a cup of wine?
You are grown wiser in the spiritual Egypt than they were in the old time,
that will set up the image of God in your bibles, and in your houses,
when no image ought or can be made of him, "`who is a spirit,
and to be worshipped in spirit and in truth.`"

Isa.
44. "`All they that make images are vanity, and they are deceivable things,
and shall nothing profit, and they are their own witnesses, that they see not nor know:
therefore they shall be confounded who have made
a god or a molten image that is profitable for nothing.
Behold, all they that are of the fellowship thereof shall be confounded,
for the workmen themselves are men; let them all be gathered together;
they shall fear and be confounded together.
With part of the tree they warm themselves, and with part they bake their bread,
and kindle the fire, and of part they make a god and worship it, and bow to it.`"
Read the chapter throughout and see, is not this like many called christians?
And must not all you be confounded that be in the fellowship, in the images,
and pictures, and idols, together with the setters up and makers of them?
And do not you eat part of your bread that you make your god of,
and drink part of your wine that you make a god and christ,
and refresh your bodies with the one part,
and the other part you make your god and christ of, which when you have made,
you worship him?
And here must you not all be confounded in these works?
Expect it.

Isa.
46. "`Saith the Lord, to whom will you liken me,`" make me like or make me equal,
or compare me, "`that I should be like him?
They draw gold out of a bag, and weigh silver in the balance,
and hire the goldsmith to make a god of it, and they bow down and worship it:
they bear it upon their shoulders, and carry it, and set it in his place:
and when they cry to him, he cannot deliver them out of tribulation.
Remember this and be ashamed, and bring it again to mind, O you transgressors.`"
Consider, you that are called papists, do not you carry your host upon your shoulders,
and put your host you make in a place, which you make of bread and wine?
And do not you and your people worship the bread
and wine which you make your god and christ of?
And do not you make pictures of gold like an old man?
And doth not the Lord reprove you, saying, "`who will you make me like,
or to whom will you make me equal?`"
what, will you make him equal with an image?
"`or to whom will you compare me?`"
what, will you compare him to man, and liken him to him who is a "`spirit,
and is to be worshipped in spirit?`"
And, have you not now your goldsmiths like the heathens,
to make you gods and images of gold and silver?
O remember this and be ashamed, O you transgressors.

Isa.
48. "`Thou that art obstinate, and thy neck is as iron, and thy brow as brass,
I have even from the beginning declared it unto thee; before it come to pass,
I showed it thee, lest thou shouldst say, my idols have done them, my graven images,
and my molten images have commanded them.`"
And therefore consider, you stiff-necked, whose brows are as brass,
and who are obstinate, who trust so much in representations, images and pictures,
and make your people believe that great things are done by them, which are lies;
for nothing can you do to glorify God, being in the transgression of his holy law.

Isa.
57. "`But you witches`' children, come hither, the seed of the adulterer,
and of the whore.
On whom have ye jested?
Upon whom have you gaped and thrust out your tongue?
are not ye rebellious children, and a false seed,
inflamed with idols under every green tree,`" etc.
Now consider, you that profess christianity, whose children you are,
of what seed you are, who are found inflamed with idols, pictures, and images,
and jest and gape with your mouths, and thrust out your tongues at his people,
therefore you cannot be called a people of God, for you have rebelled,
and vexed God`'s holy spirit, therefore is he turned your enemy,
and will fight against you.

Isa.
63 and 66. Wherein you may see your sacrifices are like the Jews,
who transgressed the law of God, that your sacrifice is like unto blessing your idols,
"`and cutting off a dog`'s neck, because you have chosen your own ways,
and your souls have delighted in your abominations:
therefore God will choose your delusion, and bring a fear upon you,
and none shall answer.`"

Jer.
10. "`Every man is a beast by his own knowledge:
every founder is confounded by the graven image, for his melting is but falsehood,
and there is no breath therein, and they are vanity, and the work of errors,
in the time of their visitation they shall perish.`"
So consider, you makers of images, who are beasts in your knowledge,
who be imitators of the Creator, and make images of things in heaven and in the earth,
and so are imitators of your Creator; but you are too short,
you cannot make them to speak; you cannot put breath in them, nor make them go,
nor handle, nor see, nor hear; so that your works are vanity.

Jer.
16. "`Shall a man make gods unto himself, that are no Gods?
Behold saith the Lord, I will this once teach them, I will show them,
my hand and my power, and they shall know that my name is the Lord.`"
You must feel the weight of this all ye god-makers, and christ-makers,
when the Lord`'s hand is upon you, and his power.

Jer.
43. "`I will kindle a fire, saith the Lord, in the house of the gods of Egypt,
and they shall burn and carry them away captive,
and he shall array himself in the land of Egypt.`"
Now consider, ye that are called christians, which are spiritual Egypt,
do not you think that the Lord will kindle a fire in the house of your gods, pictures,
and images which you adore and worship,
the God and Christ you made of the bread and wine.
He will make you know that he is the Lord, and you cannot make him,
but he made all to his glory.

Jer.
50. "`Declare this among the nations, publish it, and set up a standard, proclaim it,
and conceal it not.
Say Babel is taken, Bell is confounded, Merodach is broken down, her idols confounded,
and her images are burnt in pieces.
And now, you that are called christians, what think you of this?
Have you heard of this proclamation?
Is it set up among the heathen, and not among you?
Is not the standard yet set up?
Is this concealed yet to you?
Your images are not yet burnt, nor your idols yet confounded.

And in the same chapter, "`Drought is upon her waters, and they shall be dried up,
for it is a land of graven images.
What do you see?`"
Were these the Jews and heathens, and yet are not you, called christians,
in fellowship with them, is not your land full of images?
and do not you dote upon your idols, pictures, and representations?
There is a drought of the waters of life among you,
and therefore are you not trusting in your images, and bowing and praying before them.

Ezek.
6+++.+++ What brought the sword, and famine, and the pestilence upon Israel?
was it not because of idolatry, and their, images which should have been broken down,
and cast down?
Nay, were not there men slain upon their idols who had imitated the heathens`' ways,
like some that are called christians?
and did not God bring the carcasses of the children of Israel before their idols,
and scatter their brains before their altars, and make them to know that he was the Lord,
and by reason of these things, did he not bring famine and pestilence upon them?
So, that how can you think to escape?

Ezek.
7+++.+++ They made images of their abominations, and of their idols: and therefore,
did not this bring shame upon their faces, and baldness upon their heads,
and brought their land into the hands of strangers?
but you papists are not yet fully come to this.

And the ancients of the house of Israel, see what they did in the dark, in Ezek.
8+++.+++ Every one in the chamber of his imagery.
And so you christians called, see what you have done in the dark,
in the chambers of your imagery, for you have been workers out of the light,
and so your works are for condemnation.

And in Ezek.
14. "`Son of man, these men have set up idols in their hearts,
and put a stumbling block of iniquity before their faces,
I the Lord will answer him that comes according to the multitude of his idols.`"
Therefore you that think to come to God by your pictures, crosses, crucifixes,
representations, gods and christs you have made, the Lord will answer you with his wrath;
and therefore turn your faces from your abominations,
for you are all departed from God through your idolatry.

Ezek.
18. There you may see such were reproved that lifted up their eyes to idols:
and therefore christians look at home, see what you lift up your eyes to,
to the multitude of your idols, images and pictures.
And Ezek.
20. See how the Lord brought his people out of the land of Egypt,
into a land that flowed with milk and honey:
and yet after that how they rebelled against God, and followed the idols of Egypt,
and therefore wrath came upon them, as it did upon the Egyptians;
which you must not escape that follow such things now in the spiritual Egypt,
and defile not yourselves in observing the manner of other nations, with their idols.
And so, away with all image-makers, and image-worshippers,
for both the maker and they must be confounded.

Ezek.
21. "`The king of Babel stood up at the parting of the way, at the head of the two ways,
consulting by divination, and made his arrows bright.
He consulted with idols, and looked into the liver.`"

So consider ye that now pray before images, and to images and idols,
and to your pictures; you are in Nebuchadnezzar`'s spirit, who will persecute others,
because they will not bow down to your pictures, and images.

Ezek.
22 and 23. Thou hast offended in the blood that thou hast shed,
and hast polluted thy feet with the idols that thou hast made;
and so thou hast caused thy days to draw nigh,
therefore I have made thee a reproach to the heathen, and a mocking to all countries:
and therefore, thus saith the Lord God, the city sheddeth blood in the midst of it,
that her time may come, and maketh idols against herself.
And thus she committed whoredom with them,
even with all them that were chosen men of Ashur,
and defiled themselves with all her idols.

So consider this, have you not offended in blood, and shed blood in your cities?
Yea, and polluted yourselves with your idols?
Yea, all you idol-makers in Christendom, and followed the ways of the heathen,
and like the old Romans, who made images.
And Simon Magus, was not he an image-maker, and introducer of Simony at Rome?
And how do you think to escape the wrath of God, who are so unlike his saints,
and his people?
And you forefathers, what can you expect but nakedness and shame,
who have gone a-whoring after the heathen, and polluted yourselves with idols, pictures,
and images?
For when Israel of old, forsook God, they grew cruel and hardened,
with their idols and images, and at last they slew their children to their idols,
and for sacrifices:
and so you have sacrificed others that would not bow down to your idols, and images,
and your host, which you made.

Ezek.
29. "`Thus saith the Lord God, I will also destroy the idols,
I will cause their idols to cease; I will make their land waste;
I will bring a terrible people, a terrible nation upon them.`"
So when the children of Israel followed images, pictures, and idols,
he brought the Egyptians and Nebuchadnezzar upon them;
and so then they had images and idols enough; for the Lord brought that upon them,
that were in and of the nature that they were in themselves, when they had forsaken God.
And so, do not you expect (called christians,) that delight in pictures, images,
and idols, that the Lord in his time will bring them that you call heathen upon you,
for you are gone from God, and Christ, into the nature of the heathens;
and then you may cry to your pictures, idols, and images;
for when your people called out in Ireland to Patrick, and to your images, and pictures,
you see there was none able to deliver them.
And thus you have deluded the people, and kept them in bondage unto your pictures,
images, and idols, whom the Lord will reward.
So to make images and idols is an abomination, it is that which defiles people,
it is a transgression of God`'s law, he is as a beast that invents them,
or commands them to be made, or to worship them.

Ezek.
44. "`The Levites that were gone back from me, saith the Lord,
when Israel went astray from me after their idols, they shall bear their iniquity.`"
Now consider, you that call yourselves christians, you are gone back, all ye priests,
popes, cardinals, Jesuits, as well as Israel of old, and the Levites,
you are gone back from the Lord, ye are gone astray after idols, images, and pictures,
and you must bear your iniquity.

Dan.
3. "`Where Nebuchadnezzar set up a golden image,
and caused all both small and great to worship it, at the sound of the pipe,
and the instruments of music,
all were to fall down and worship the image that he had set up; but the three children,
Shadrach, Meschach, and Abednigo, that feared the Lord, and kept their religion clear,
could not follow Nebuchadnezzar`'s religion,
but transgressed and obeyed not his commands,
in not falling down to worship that which he had set up.`"
So now you papists have you not made images, pictures, and hosts,
and do not you command the people to fall down, yea,
to put off their hats at the sound of the Ave-mary bell,
or else be in danger of coming under your law,
and so here you are found in Nebuchadnezzar`'s spirit, not in Christ`'s,
nor the prophets`', nor apostles`'.

Hos.
4. "`Thus saith the Lord, Ephraim is joined to idols, let him alone:
and they shall be ashamed of their sacrifices.`"
Now consider, have you, called christians, that have worshipped images, and idols,
have you been let alone many hundreds of years,
and yet you are not ashamed of your sacrifices?
But they that are come from you are.

And when Israel forgot God, his Maker, he built temples:
Israel cast off the thing that is good; of the silver,
and of the gold they have made idols.
Now therefore, shall they be destroyed, and the enemy shall pursue him.
And therefore, consider you called christians, these things,
who have made idols of your silver, and of your gold,
think you not that the enemy will pursue you, who cast off things that are good,
who have forgotten your Maker, and built many temples,
and not mind that your bodies are the temples of the living God.

Hos.
10. "`Israel is an empty vine, they have made fair images, their hearts are divided,
now shall they be found faulty, he shall break down their altars,
he shall destroy their images.`"
So, consider all ye called christians, what an empty vine you are, and wild,
who have made you fair images, O how do you delight in them, and their pictures;
you are found faulty before God, who will break them down.

Hos.
13. "`When Ephraim spoke trembling, he exalted himself in Israel; but he sinned in Baal,
and is dead: and they sinned more and more, and made molten images of their silver,
and idols according to their own understanding,
and they are all the work of the craftsmen.`"
So consider, ye that call yourselves christians,
are not you dead that make these molten images, and idols of silver, and gold,
and of stone, and wood, etc.
And do not you kiss your pictures, and images?
And so, if Ephraim be dead, are you living that do so,
and follow your craftsmen whom you set at work, and worship their works,
which is an abomination to God, who is, and will be worshipped in spirit and in truth.

Hos.
14. "`Ephraim shall say, what have I to do more with idols?`"
but you that call yourselves christians, have not said so yet;
and therefore you are worse than Ephraim.

Amos 4. and 5. Where is a lamentation for the captivity of Israel,
who followed images which the heathens followed, who made gods to themselves like them;
which practice hath been followed by those that call
themselves christians who have made gods and christs,
makers for the people, which is an abomination,
who have kept people by such doings from the true Christ, who is the way to the true God.

Mich.
1. "`All the graven images shall be broken,
and all the gifts thereof shall be burnt with fire, and all the idols shall be destroyed:
for she gathered it of the hire of a harlot,`" etc.
Now how can you own this prophet, and keep your images and idols unburnt and destroyed?
For it is the work of the whorish spirit from God to make such things,
and not of the spouse of Christ.

Mich.
5. "`Thy idols shall be cut off, and thy images out of the midst of thee,
and thou shalt no more worship the work of thy hands,`" etc.
This prophet will take hold upon you that are called christians,
who are found in such practices, and then you will be separate from your lovers.

Nahum 1. "`The Lord hath given a command concerning thee,
I will cut off the graven images, and the molten images,
and I will make it thy grave for thee, for thou art vile.`"
So, consider ye christians, with all your images and pictures,
which are become your grave, for you are vile: therefore, mind the Lord`'s command,
that you may come out of your vileness; and cut down your pictures, and images,
and obey the Lord`'s command.

Hab.
2. "`What profiteth the image?
For the maker thereof hath made an image, and a teacher of lies;
though he that made it trust therein when he makes a dumb idol.
Woe unto him that saith unto the wood awake, and to the dumb stone arise up,
it shall teach thee: for behold, it is laid over with gold and silver,
and there is no breath in it.
The Lord is in his holy temple, let the earth keep silence before him.`"
And now you papists and christians, you say, your pictures, and images, which you make,
and your representations, they profit the people, and are laymen`'s calenders,
and thus your teachers are liars, contrary to the command of God, who saith,
"`they do not profit.`"
Your stones, and your wood, which you paint with gold, there is no breath in them,
away with all such fopperies.

Zach.
10. "`Surely, saith the Lord, their idols have spoken vanity,
and the soothsayers have seen a lie, and the dreamers have told a vain thing.`"
Now consider this, ye that call yourselves christians,
all you soothsayers that have set up idols, which are vanity, which have seen a lie,
and the dream you have told is but a vain thing, and do not you tell to people,
that your representations and images will profit them.

Zach.
13. "`The Lord saith, he will open a fountain to the house of David,
and inhabitants of Jerusalem, for sin and for uncleanness: and in that day,
saith the Lord of hosts, I will cut off the name of the idols out of the land,
and they shall no more be remembered,
and I will cause the unclean to depart out of the land.`"
Now consider this, you papists and others,
this fountain is not opened to you yet for sin, and for uncleanness, for your images,
and idols are yet standing in your land, held up by your unclean spirit;
for when this fountain is opened, your unclean spirit that held up your idols,
must depart out of the land, and then you will acknowledge the prophesy.

Mal.
3. "`For you have spoiled the nations with your images, and false gods and christs.
This may well be applied unto you that call yourselves christians,
that follow your pictures, and images, the gods you have made:
for Israel went from the ordinances of the Lord when he turned to images, idols,
and other gods, as you christians have gone from the ordinances of God.

And see in Acts 7. How Stephen reproved the Jews for making a calf,
and offering sacrifice to the idols, the work of their own hands;
and how God turned himself away from them, and how they served the host of heaven.
For, what is there in heaven or earth, but you have made pictures, and images of,
and so you are here judged by Stephen, whom the Jews stoned to death,
the same would you do to them that should cry against you.
The pictures, images, and representations that you have made,
being found in the same transgressing spirit like the Jews.

And the apostle commands,
in Acts 15. "`That the Gentiles who were converted should abstain from idols,
and from fornication,`" etc.
And therefore consider, you that are called christians,
you are here judged by the apostle, who sets up houses for fornication, and follow idols,
and images, and do not abstain from them,
you are transgressors of the apostles`' ordinance.

Acts 19. There you may see your own brethren, what rage they were in at the city Ephesus,
that worshipped Diana; and what a noise made those image-makers against the apostle.
And so look among yourselves, what a noise you craftsmen make now,
against the ministers of the spirit, that preach, and cry down your images and idols.
So the Gentiles were to abstain from idols and fornication, as before,
which shows that you are in the Gentiles`' nature, not converted, that do observe them,
and follow such things as they did in their unconverted state.

And Rom.
1+++.+++ There you may see your old brethren, "`when they knew God,
they did not glorify him as God: who turned the truth of God into a lie,
and worshipped and served the creature more than the Creator,
who is God blessed for ever.`"
And so, now this is your condition, who profess yourselves to be wise, but are fools;
for what, do not you and your people serve images, and pictures, and representations,
more than you do the Creator; for you are not come so far as to abhor idols;
and though you say in words, you do, yet you,
professing christianity doing the same as the heathen, are worse than they.

1 Cor.
8. "`Some make conscience of an idol: an idol is nothing.
And the Corinthians were not to eat meat sacrificed to idols.`"
And so what are all your sacrifices but to idols, images, and your christ you make?
And so, if an idol be nothing, then nothing can do you no good,
and that which you sacrifice and offer to it, is offered to nothing,
and so all comes to be confounded.
And therefore, as in 1 Cor.
10, both the sacrificer and the idol is not good for any thing but for judgment.
And "`what agreement hath the temple of God with the idol.`"
2 Cor.
6+++.+++ So, if you were the temple of God, that are called christians,
there would be no agreement with your pictures, images, and idols,
but showing that you have agreement with them.
Therefore you are no temples of God.

1 Thes.
1+++.+++ There it is manifested,
"`how they were turned from idols to serve the living God:`" but now it
is manifest how they are turned from the living God to serve images,
pictures, idols and representations, whereby it denotes you are in an unconverted estate.

2 John 5. The apostle saith,
"`Little children keep yourselves from idols,`" in his general epistle to the church;
but you that call yourselves christians have forgot this command,
or at least laid it aside, and command your people to keep to your images, pictures,
idols, and representations, and call them your laymen`'s books,
and therefore you are quite degenerated from John`'s doctrine and command here,
who command your people to keep idols, whereas John commands to keep from them.

And Rev.
2+++.+++ There you may see, "`there were some that laid stumbling-blocks,
that taught the doctrine of Balaam; and to eat meats sacrificed to idols,
and to commit fornication,`" and therefore consider,
is not this the condition of you papists?
Are not you in Balaam`'s reward?
Are not you in your idols, and fornication,
else what do you do with all those brothel-houses?

And Rev.
9+++.+++ There you see such as were so hardened that did
not repent of the works of their hands,
that worshipped the devil, idols of gold, silver, brass, stone and wood,
which neither could hear, see, nor go, and these God brought his plagues upon,
and such repented not of their sorcery, murder, fornication, and theft.
And so look into your own nest, and there you may find all these fruits,
and it is well if this doth not fall out that many will perish in these fruits,
and not repent.

And so for you that have followed the beast, as in Rev.
13, "`and his image, and made all, small and great, poor and rich,
bond and free to receive his mark,`" etc. and so keep them from God`'s mark and image,
to follow your images, and therefore, consider what will be the end, whether the beast,
the dragon, the whore, and the false prophet,
must be cast into the fire that burns with brimstone,
which hath been the ground of all these images, idols,
pictures and representations which be out of the image of God, you that made them,
that set them up, that command them to be made, and worship them; you have gone out,
I say, of the image of God, into the image of the devil, that is out of the truth.

Solomon, by taking strange women of the heathen to be his wives,
transgressed the law of marriage which was instituted by Moses;
in which law God forbid to marry with foreign nations.
And before all this he chanced to sin and default in the observation of the law,
at such time as he made the similitudes of beasts
to underprop the vessels called the great sea,
and those of lions, which he caused to be set unto his throne.
Josephus, p. 204.

