== The Heathen`'s Divinity, Set upon the Heads of All Called Christians

That say they had not known that there had been a God, or a Christ, unless the Scripture had declared it to them.

They are such Prophets, that said,`" Thus saith the Lord,`" and the Lord never spoke to them.

You have not heard his voice at any time, nor seen his shape; and the Word of God abideth not in you. John 5:37-38.

Who have the Form of Godliness, and deny the Power thereof; from such turn away.--By G. F.

Gen.
12. We read how Abraham went down into Egypt, with his wife,
and how the princes there commended her to Pharaoh, king of Egypt, who saw she was fair;
and Pharaoh took her into his house, and entreated Abraham well for her sake:
and how the Lord plagued Pharaoh`'s house with a great plague, because of Sarah,
Abraham`'s wife: and Pharaoh called Abraham, and said to him,
"`what is this that thou hast done unto me?
Why didst thou not tell me that she was thy wife?
I might have taken her to wife; now, therefore, behold thy wife, take her, and go thy way.

Now what was this in Phoraoh that made him consider
the plagues of God that were upon his family,
for Sarah`'s sake, etc. was not this a divine principle, a divine power,
that brought him to obey the Lord God, who had not the outward written law?
And doth not Pharaoh judge all christians, who covet after other men`'s wives,
both protestants, and papists?
And doth not Pharaoh judge them all here?
Who gave the man his wife again, and lay not with her,
and simply took her into his house at first,
thinking that she had really been his sister; and when he was plagued for it,
he returned her to her husband, and took her not to wife: so that here,
doth not Pharaoh`'s practice stand over protestants`'
and papists`' practices in this very thing?

Gen.
20. We read that Abraham said of Sarah his wife,
"`she is my sister;`" and how that Abimelech, king of Gerah,
took Sarah away from Abraham, but God appeared to Abimelech in a dream, and said to him,
"`thou shalt die, for the woman`'s sake whom thou hast taken away;
for she is a man`'s wife;`" and Abimelech had not as yet come near her.
Now mark what Abimelech said, "`Lord, wilt thou slay the righteous people?
Said not he unto me, she is my sister?
Yea, and said not she herself, he is my brother?
And with a pure heart, and innocent hand I have done this thing.`"

And God said unto him by a dream,
"`I wot it well that thou didst it in the pureness of thy heart;
I kept thee also that thou shouldst not sin against me;
and therefore suffered I thee not to touch her.
Now therefore, deliver the man his wife again, for he is a prophet,
and he shall pray for thee, that thou mayest live: but,
and if thou deliverest her not again, be sure thou shalt die the death, both thou,
and all that thou hast.`"

Now mark, all ye papists and protestants, who say, "`you never heard the voice of God,
nor of Christ:`" see how Abimelech talked with God, and God with him in a vision,
or a dream, and how God acknowledged his heart was pure;
and how he had kept him from another man`'s wife, though he innocently looked upon it,
that she had really been Abraham`'s sister, and not his wife.
And therefore, doth not Abimelech`'s obedience,
and the divine power of God in him judge all you papists
and protestants that covet after other men`'s wives,
and manifest yourselves to be unclean, and not innocent?

And further,
see how Abimelech spoke that which God had said unto him in the ears of his servants,
and obeyed God`'s voice, and delivered Abraham`'s wife to him;
and asked "`Abraham wherein he had offended,
that he had brought upon him and his kingdom so great a sin,`" etc.

Therefore, mark how Abimelech looked upon it as a very great sin,
to take another man`'s wife from him, whom you christians do look upon as a mere heathen:
and yet you papists and protestants, that call yourselves christians, can do such things,
who say, you never heard God`'s voice, you are more dark than Abimelech.
And was there not more virtue and divinity seen and manifested in Abimelech,
than in you papists and protestants, who covet other men`'s wives,
and take them from them, whose practice is neither according to law nor gospel,
though you profess both from the letter?
And he that had no letter condemns you both in practice.

And now to clear Abraham from the aspersion that
both papists and protestants do cast upon him,
as if he were a liar, in denying Sarah to be his wife, and calling her sister;
which scripture they bring to plead for a lie in case of necessity,
and so for sin as long as they live, and how they may lie by authority,
as having Abraham, the faithful, for an example: Abraham said unto Abimelech,
"`yet in very deed Sarah is my sister, for she is the daughter of my father,
though she be not the daughter of my mother;
and she became my wife;`" and so she was both his sister and his wife in truth,
and no lie can be charged upon Abraham in this matter,
as the false protestants and papists charges him withal,
and bring him as a liar to maintain their lies,
that so they may be tolerated to live in sin, which they have missed of;
for they should have brought the devil, the father of lies, and not Abraham,
the father of the faithful; for Sarah was both wife and sister.
And so Abimelech here condemns papists and protestants, who hath heard the voice of God,
and yet had neither law, nor gospel, nor letter, as they have, who say,
"`they have not heard the voice of God at any time,`"
though they have the letter both of law and gospel;
whereas he had neither the letter of law or of gospel, and yet he heard the voice of God.
And is not here divinity in him?
And did not he speak divine things?
Read Gen.
20.

Gen.
26. Where we read how Abimelech, king of the Philistines, said to Isaac,
that surely Rebecca is thy wife; and why hast thou done this to us?
For one of my people might have lain with thy wife,
and so by that means thou shouldst have brought sin upon us.
And he charged all his people, not to touch this man or his wife; for who so did,
should die.

Now consider what virtue was in this Abimelech;
and how tender was he of himself and his people,
and of committing sin with another man`'s wife:
and how far are protestants and papists off of this tenderness,
who pretend law and gospel, and yet keep neither, but covet after other men`'s wives;
whereas he that hath neither written law, nor gospel, obeyeth both law and gospel,
who would not himself, nor yet suffer his people to meddle with another man`'s wife,
though he had heard no other before, but that she was Isaac`'s sister,
until he had informed himself otherwise.

See then how short is that called Christendom of this virtue, that was in Abimelech,
king of the Philistines, that had neither written law nor gospel: how short, I say,
are they that profess law, and gospel, and divinity,
of this divine power and virtue that was in him?
Let all judge.

Exodus 8. The Lord commanded Moses, that Aaron should stretch forth his hand,
and with his rod smite the dust of the land of Egypt; and Aaron did so;
and so all the dust of the land of Egypt was turned into lice:
but the enchanters could not with all their enchantments make a louse;
so that the enchanters said unto Pharaoh king of Egypt, it was the finger of God.

So now you see here, the enchanters did confess the finger of God,
that turned the dust of the land into lice.

And now see professors, papists, and protestants,
how could you think those enchanters could confess that was the finger of God,
who had neither written law nor gospel, as you call it, without which you say,
you had not known whether there were a God or Christ,
if (say you,) written scripture had not declared it to you; and yet these men,
that had neither written law nor gospel, confess the finger of God to king Pharaoh.

And therefore, was it not a divine power in them, that confess the finger of God,
and a more divine power in them than in you, that call yourselves professors,
either protestants or papists, that say you had not known there had been a God,
if that scripture had not declared it to you; and yet these could declare it,
who never heard of scripture likely, but were against Jews, and Moses,
who received scripture, and wrote scripture.

Exodus 18. What scripture had Jethro, to speak all those good words to Moses,
his son-in-law,
when he met him in the wilderness heading and leading
the children of Israel towards Canaan?
"`For, saith he unto Moses, God shall be with thee; and be thou to the people God-wards,
that thou mayest bring the causes unto God: and thou shalt seek out of all the people,
men of activity, and such as fear God, true men, hating covetousness,
and make them heads over the people.`"

See what brave words and language, Jethro, a Midianitish priest did speak unto Moses,
who had no written law nor gospel; and yet,
did he not speak these words from a divine power of the Lord?
And Moses was subject to him, being, so far from reproving him for what he said,
that on the contrary, he approved of his counsel,
so that he put it in execution to the satisfaction of all Israel.

Numb.
23. and 24. Where you may see what great things, and prophesies, and parables,
Balaam spoke, who had no scripture, law, or gospel, so called.

And how do you papists and protestants think that he should speak such things,
and had no scriptures?

It is said, "`The Lord opened the eyes of Balaam, and the word of the Lord came to him,
and the spirit of God came upon him.`"
So these things and many more are set down, that Balaam spoke, who saw the star of Jacob,
who had no scripture; and therefore, doth not he and his ass reprove you all,
that say you never heard the voice of God, nor of Christ, nor had known God or Christ,
except the written law or gospel had declared it unto you?
And so, was not there more divinity in him?
And did not he speak more divine things from, and of God, than you,
who say you never heard God`'s voice?
for you speak only what others say; but he spoke what he had from God.
And though Balaam coveted after Balak`'s rewards,
which he should have had for cursing the people of Israel;
yet God restrained him from cursing.
But however, had not he more divinity, and spoke more divine things than you Balaamites,
that speak other men`'s words, in the scripture new and old, for rewards,
and never heard God`'s voice, as Balaam did, as you have confessed?

And in chap.
22. How the Lord opened the mouth of Balaam`'s ass, to reprove him;
this Moses recorded for truth; but had it been in your days,
who say there is no hearing of God and Christ`'s voice,
you would have judged it to be an imagination; but Balaam`'s ass may reprove you all,
who are going mad in preaching for rewards and gifts, cursing, and excommunicating,
and imprisoning such as will not give, and put into your mouths.

Esther 6. and 13. Where you may see what Haman`'s wife said; "`If that Mordecai,
were of the seed of the Jews,
before whom (speaking to her husband,) thou hast began to fall,
thou shalt not prevail against him, but shalt surely fall before him.`"

Now what was this that spoke these words in his wife,
who formerly had stirred up her husband to seek Mordecai`'s destruction,
and all the rest of the Jews;
and counselled him to set up a gallows for him of fifty cubits high;
and yet afterwards she said, "`that if Mordecai were of the seed of the Jews,
before whom thou hast began to fall,`" etc.

Now, how could this woman speak this, or prophecy, who had not scripture,
nor written law, nor gospel; but was against the Jews that had the law?
Would not you christians have said, that she had been a madwoman, and a madwoman preacher?
And yet she could not tell such things out of scripture.
And did not her words come to pass?
And did not he fall before Mordecai,
and was hung upon the same gallows that was set up for Mordecai?
Was she not therein a prophetess?

Job.
And what scripture had Job to speak forth all those sweet scriptures,
contained in his book?
Yea, and what scripture had all the holy men of God, who were before Moses,
to speak forth what they learned only of God, and spoke what they had received of him,
which in after ages came to be written, printed,
and known again by the same spirit that gave them first forth, to and through them?

Ezra 1. Where it may be seen, how the Lord God stirred up the spirit of Cyrus,
king of Persia, who said,
"`the Lord God of heaven hath given unto me all the kingdoms of the earth,`" etc.

Now how could this man, upon whom you look as upon a heathen,
and one that had neither law nor gospel; how could he, I say,
speak such things without scripture?
was not here a divine power and spirit in him, who acknowledged,
that the Lord God of heaven and earth had given him all the kingdoms of the earth;
and he was to build God a house in Judea, which was the Jews`' temple.

He did not say, he had got all these kingdoms by his own power, nor might, nor valour;
but that the Lord God of heaven had given them him.

Now would you not have thought this man whimsical, had you lived in those days,
and too confident to speak such things, and had no scripture,
and had them in captivity who professed and enjoyed scripture.

Ezra 6. and 7. What was that in Darius, that gave command to build God`'s house?
for do you not look upon Darius and Cyrus as heathens, having neither written law,
nor gospel, so called?

And what was that in Artaxerxes, who encouraged the priest of the Lord?
Who said unto him, "`that he was the priest of the law of the God of heaven;
and that he was to teach the law of God to the people, and to set judges over the people,
even such as knew the law of God: and those that will not fulfill the law of God,
and the kings, let them have judgment,`" etc.

So, now the law of God here the king owned; and his command and law was,
that God`'s law was to be obeyed.

And was not this by divine power, and a divine principle in him, though these were Jews,
who opposed the christians with their carnal weapon;
and they that do now use the scriptures for the building an old mass-house,
and bring the king`'s law, and God`'s law for it, deny Christ`'s coming in the flesh,
who hath ended the Jew`'s temple, and the law that held it up,
and made his people his temple, as scripture saith.

Judges 13. Where you may read how the angel of the Lord appeared unto Manoah, his wife,
and after to both of them; and how he said to his wife, "`we shall surely die,
for we have seen God;`" but his wife said unto him, "`if the Lord would have killed us,
he would not have received a burnt and a meat-offering at our hands;
neither would he have showed us all these things;
nor would now have told us such things;`" viz. "`that we should have a son.`"

Now mark, what a sermon here is, that Manoah`'s wife preached unto him:
would not you protestants and papists have called her a twattling woman?
and said, "`what, dost thou preach unto thy husband?
Go and learn of thy husband at home:`" and what scripture
had she for preaching to her husband?
but she believed a divine power, and the thing came to pass accordingly,
what the angel had spoken to her.

Daniel 2. What was that in Nebuchadnezzar king of Babylon, who said, "`of a truth,
your God is a God above all gods, and a Lord above all kings, and a revealer of secrets,
seeing thou couldst reveal this secret?`"

Did he not speak divinely, who confessed to the God of heaven,
and set up the true God above his own?
had Nebuchadnezzar, think you, been at the schools seven years,
and learned the seven liberal arts to speak this?
Or had he the written law or gospel to speak this by,
in that he confessed the God of heaven, and a Lord above all kings, and so above himself.

Daniel 3. Where we read that Nebuchadnezzar went
to the mouth of the hot burning fiery furnace,
who had cast into it the three children, Shadrach, Meshach, and Abednego,
fast bound in their clothes, and hats on;
it being heated seven times hotter than usually.

And the king said unto his council, "`did not we cast in three men bound, into the fire?`"
and they said, "`yes, O king.`"
And the king said, "`lo,`" for all that, "`I see four men walking loose,
in the midst of the fire, and they have no hurt;
and the form of the fourth is like the Son of God, to look upon.`"

And Nebuchadnezzar said, "`O Shadrach, Meshach, and Abednego,
ye servants of the most high God, come forth;`" then they came forth.

And then the dukes, lords, and nobles, and the king`'s counsellors came to see these men,
"`upon whose bodies the fire had no power; nor was an hair of their heads singed;
neither were their coats changed, nor the smell of the fire passed upon them.`"

Then spoke the king, saying, "`blessed be the God of Shadrach, Meschach, and Abednego,
who hath sent his angel to deliver his servants that trust in him,
and hath changed the king`'s command, and yielded their bodies,
that they might not serve nor worship any God save their own God.
Therefore, I make a decree, that all people, kindred, and tongues,
which speak any blasphemy, against the God of Shadrach, Meschach, and Abednego,
shall be cut in pieces, and their houses shall be made a dunghill,
because there is no god that can deliver after this sort.`"

Now, +++[+++mark,]
was it not a divine principle in Nebuchadnezzar, that caused him to utter these words,
who was a worshipper of images, and compelled others to do the same?
and could he tell of the Son of God, saying,
"`one was like the Son of God;`" and confessed,
these were the servants of the most high God;
and that none should speak evil against the God of heaven;
and praised them that did not change their religion;
and that none could save like the God of heaven; and that none should blaspheme him?

Could he speak these things without a divine power,
having neither written law nor gospel; but was looked upon as a heathen?
how could he speak these things without scripture?

What say you to this, you professors, that say, "`you have not known God, nor Christ,
without the scripture had declared it to you?`"
and if this had been in your days, would not you be ready to say,
that this was witchcraft, or conjuration?
Hath not Nebuchadnezzar judged all you divines here,
who spoke such things as these without letter or scripture;
whereas you confess you cannot, without letter or scripture?

Dan.
4+++.+++ See here what brave things Nebuchadnezzar had in his dream; what prophesies,
visions and openings; and how he foresaw the overthrow of his own empire;
and how he saw a watcher, even the holy angel that came down from heaven,
and hewed down the tree, which was himself, and left the stump in the ground;
and that he was to eat grass like an ox, for seven years,
until he knew the Most High ruling in the kingdoms of men.

And after, the king was walking in a palace, a voice came from heaven to him, saying,
"`thy kindom, O Nebuchadnezzar, shall depart from thee.`"

And when the seven years were expired, he lifted up his eyes to heaven,
and his understanding was restored to him; and he gave thanks to the Most High,
and magnified him forever and evermore; "`whose dominion,`" said he,
"`is an everlasting dominion, and his kingdom is from generation to generation;
and all the inhabitants of the earth are reputed as nothing;
and he doth according to his will,`" etc.

Then did Nebuchadnezzar love, magnify, and praise the king of heaven;
"`for all his works are true,
(said he,) and his ways are righteous;`" and as for them that walk in their pride,
he is able to abase.

Now but consider what gallant and brave divine things this heathen spoke,
who had neither written law nor gospel, far beyond you that have your schools,
written law, and gospel.

Daniel 5. Here you may see how Belshazzar, another heathen king,
made a feast for a thousand of his lords; and when he was troubled in his mind,
his wife told him, that there was a man in his kingdom,
that had the spirit of the holy God within him, meaning Daniel,
a captive of the children of Israel: whereupon he sent for him, and said,
"`art thou Daniel; I have heard of thee,
that thou hast the spirit of the holy God in thee, and light, and understanding:
if therefore, thou canst read me the writing, I will give thee gifts and rewards;
a chain of gold about thy neck, and thou shalt be the third ruler in the kingdom.`"

Daniel said to the king, "`as for thy rewards, keep them to thyself,
and give thy gifts to another; yet I will read the writing to the king,
and interpret it.`"
So Daniel told the king, "`thou hast magnified thyself above the Lord of heaven,
and in whose hands thy breath is.`"

"`Mene,`" that is, "`God hath numbered thy kingdom, and brought it to an end.`"

"` Tekel,`" "`Thou art weighed in the balance, and art found too light.`"

"`Pheres,`" "`Thy kingdom is divided, and given to the Medes and Persians.`"

Here you may see there was something that did make this Belshazzar, king of the Caldeans,
to condescend to Daniel`'s interpretation, though it was against himself,
though Daniel was as a captive amongst them: for the very same night the king was slain,
and the Medes took the kingdom.

Daniel 6. See there what language Darius spoke concerning God, though a heathen king,
when the informer informed the king against Daniel,
and caused him to be cast into the lion`'s den for praying to his God;
and how the Lord shut up the mouths of the lions, by his angels,
so that he had no hurt by them.
And how the king coming early in the morning to the den, who,
through much trouble of spirit could take no rest that night;
and how he cried with a lamentable voice unto Daniel, and said, "`O Daniel,
the servant of the living God, is thy God whom thou servest continually,
able to deliver thee from the lions,`" etc.
And how after this, Darius wrote to all people, kindred,
and tongues that dwelled in all lands; "`my command is, that in all my dominions,
men tremble and fear before the God of Daniel; for he is the living God,
and steadfast forever, and whose kingdom shall not fail; his power is everlasting,
even to the end; it is he that delivereth and saveth;
he doth wonderous marvellous works in heaven and in earth,`" etc.

Now people consider what brave language this heathenish king spoke,
and divine words he uttered; and how he confessed to God, and his kingdom and power,
who had neither written law nor gospel; for what scripture had he to speak these words?
and doth he not condemn you that call yourselves christians, who say,
you had not known whether there had been a God or no,
if scripture had not declared it unto you?
And so have known nothing of divinity; and therefore,
he and his divinity stands over your heads.

Acts 17. Paul said, that certain of the poets said,
"`that we are of God`'s own offspring; for in him we live, move, and have our being.`"
So now, had not the poets a sense of the living God, who said,
that they were of his offspring, and had their being from him?
now, how could they speak these, and the like things,
who were mere heathens without scripture?

Romans 1. Where the apostle saith, to the Romans who were heathens,
"`That that which is known of God was manifest in them,
for God showed it unto them;`" for his invisible things, that is to say,
his eternal power and Godhead are seen,
forasmuch as they are understood by the works of the creation of the world;
so that they are left without excuse, because, when they knew God,
they glorified him not as God.

Now consider, was not here something of God in these heathens,
that learned them to know God, though they did not glorify him as God,
though they had no written letter nor written gospel.

And doth not the apostle set up that of God in the Gentiles to judge the Jews, who said,
in the second chapter, "`he is not a Jew, that is one outward,
neither is it circumcision which is outward in the flesh; but he is a Jew,
that is one inward, and the circumcision of the heart, which consists in the spirit,
and not in the letter, whose praise is not of men, but of God.`"
For the Jews having the letter and circumcision transgressed the law;
and so the Gentiles that did the things contained in the law,
they made the outward professors of the law no professors, that broke it;
and circumcision, uncircumcision: and so they that by nature,
(by that of God in them,) kept the law, judge them that have the outward written law,
and the outward written gospel also, and yet kept it not, but broke it.

So here the obeyers of the spirit of God are justified,
and they that are professors of the things of God, and grievers of the spirit,
are condemned.
Matthew 27:19.
What was that in Pilate`'s wife, that made her to charge her husband,
"`that he should have nothing to do with condemning that just man,
(meaning Christ,) for she was very much troubled in her sleep about it?`"

And what was it that convinced, and doth convince the world of sin, of righteousness,
and of judgment?

And what was it that made Felix to tremble, when Paul reasoned with him of temperance,
of righteousness, and of judgment to come?

And what was it that convinced them of their sorceries
and witchcrafts spoken of in the Revelations,
though they did not repent?

And what is that, that brings every one to give an account of their words and deeds,
whether they be good or evil; seeing that God will judge the world in righteousness,
by the man Christ Jesus, according to the gospel, which is the power of God?

Doth not that imply, that there is something of the power of God in every man,
seeing they must be judged according to the divine power of God in the gospel?

What was that that troubled Ahasuerus in the night, that he could not sleep,
insomuch that he called for the record of the Chronicles,
which being read before the king,
he was put in mind of what great service Mordecai the Jew, had done for him;
by which means he, and all the Jewish nation, then there in captivity,
were preserved from that destruction, that Haman had wickedly contrived for them?

Acts 10. We read of one Cornelius, a centurion, that is,
a captain of a band of soldiers under the Romans;
and how notwithstanding he is said to be a devout man, and feared God,
with all his household and gave much alms to the people, praying to God always;
to whom the angel of the Lord appeared, who told him,
"`his prayers and alms were come into remembrance before God;
and that he should send for Peter to Joppa,
who would tell him what he should do:`" and when his servants came unto Peter, at Simon,
the tanner`'s house, to whom they delivered their message, saying, "`one Cornelius,
a just man, and of good report amongst all the people, etc. was warned by an angel,
to send for thee to his house, to hear words of thee.`"

Now mark, how could Cornelius and his servants speak these words, of fearing God,
or knowing there was a God, and of an angel,
which had neither the letter of the law nor gospel,
as you that call yourselves christians, saying,
"`you had not known there had been a God or Christ,
unless you had had scripture to declare it to you?`"
and what rule did this Cornelius, or the rest aforementioned walk by,
that spoke and did such heavenly things, who had not written law or gospel to walk by.

Do not you look upon Cornelius as a heathen read the scriptures,
and see what is said of him there;
and do not you say the same of them that have not the written law or gospel?

But see what Peter said to Cornelius, "`of a truth I perceive,
there is no respect of persons with God; but in every nation he that feareth God,
and worketh righteousness, is accepted of him.`"

So the Jews might look before, as if the Lord had only a respect for them,
as the professors do now; but see if that which Cornelius walked by,
that kept him and his household in the fear of God, does not condemn you, who say,
the scripture is your rule; who neither walk according to your rule of law nor gospel,
as you call it.

And Cornelius said, "`we are all here present before God,
to hear all things that are commanded unto thee of God.`"

So we see here Cornelius had a belief of the living God,
though he had no written law nor gospel, neither was he a Jew,
(but a heathen,) and had a belief, that that which Peter spoke to him was from God,
though he had not the outward bible to prove it, as we have now,
though we are not against proving men`'s words by the scripture;
but you say that you had not known that there had been God, Spirit, and Christ,
without scriptures, and set the scripture above the spirit;
whereas the spirit of God was before scripture was;
for the spirit led them to speak forth the scriptures to people;
and after when they were committed to writing, they were called, scriptures of truth;
and after much length of time, they were printed.

And the Jews did not know Christ by the scriptures, nor the apostles,
nor the prophets of the Lord; for had they known him by scripture,
they certainly would not have persecuted him, nor them.
So Christ, the prophets, apostles, and his scriptures, are known by the spirit of Christ,
which is the Holy Ghost, who leads into all truth.

1 Samuel 6:1-3, etc.
See how these heathen priests acknowledged the Lord God, and how they advised the people,
"`to offer a trespass offering to the Lord, to pacify his wrath gone out against them,
and their god Dragon,
for detaining and carrying away the ark of the Lord;`"
as you may see in the former chapter,
to the destruction of their God, and thousands of the worshippers of him;
saying "`in so doing you shall give glory unto the God of Israel;
peradventure he will lighten his hand from off you, and from off your own land;
wherefore then do you harden your hearts,
as the Egyptians and Pharaoh hardened their hearts,
when he had wrought wonderfully amongst them?
Did not they let the people go, and they departed?
Now therefore make a new cart,`" etc.

Mark, these heathens had neither written law nor gospel,
and you see they did acknowledge the living God, both as to his power, justice,
and mercy, in visiting them with forejudgments,
and by taking them off by such and such means:
all which may judge you protestants and papists, who say,
you had not known there is a God, without you had written law and gospel.

1 Kings 5. Solomon sent to Hiram king of Tyre, for timber and cedar,
for the building of the house of the Lord.

And verse 7, it is said, that Hiram, when he heard of it, he rejoiced greatly, and said,
"`blessed be the Lord this day,
which hath given unto David a wise son over this great people.`"

And in 2 Chron.
2+++.+++ We read, when Solomon sent to Hiram for cedar trees, etc.
Hiram wrote to Solomon, saying in way of answer,
verse 11-12. "`Because the Lord hath loved his people,
he hath made thee king over them.`"

"`Blessed be the Lord God of Israel, that made heaven and earth,
which hath given to David the king, a wise son, endued with prudence and understanding,
that he might build a house for the Lord,`" etc.

Now mark, do not you look upon this Hiram as a heathen king,
that had neither written law nor gospel?
and yet he came to understand that there was a Lord God in heaven,
etc. and blessed the Lord: would not you christians be ready to say,
that he followed the imaginations of his own heart, and that neither he,
nor any one else, had known whether there be a God or a Christ,
if scripture had not declared it to you?
And yet here you see to the contrary, to your own confusion.

2 Chron. 35:20, etc.
Where we may read the words of Necho, king of Egypt, to Josiah king of Judah,
who came out to fight with Necho, who came not to fight with him, but against Carchemich;
saying "`what have I to do with thee, thou king of Judah;
I came not against thee this day, but against the house wherewith I have war;
for God commanded me to make haste: forbear thee from meddling with God, who is with me,
that he destroy thee not.`"
Nevertheless, Josiah would not hearken to the king`'s words, but fought against him,
and Josiah was slain in the battle.

Now mark, you look upon the king of Egypt to be an heathen,
but here you may see he was a prophet; for his words came to pass concerning Josiah,
who had them from the mouth of God, verse 22, who had neither written law nor gospel.

And yet how ready would you have been to look upon him as a false prophet,
following the whimsies of his own brain:
whereas you may see there was a divine thing in him, more than you will own,
and many others, that profess the words of the scriptures without life: for you say,
"`that you had not known the will of God, unless scripture had declared it to you.`"

1 Kings 10:9, etc. and 2 Chron. 9:7, etc.
There you may see how the Queen of Sheba, came from the utmost part of the earth,
as Christ saith, to hear the wisdom of Solomon, Matt. 12:42.
For she had heard much of him in her own country,
and of the name of the Lord; and when she came and saw all, she said unto the king,
"`It was a true report which I heard in my own land of thy acts, and of thy wisdom;
howbeit, I believed not the words until I came, etc.
Happy are thy men, happy are these thy servants, which stand continually before thee,
and that hear thy wisdom.
Blessed be the Lord thy God, who delighted in thee, to set thee on the throne of Israel;
because the Lord loved Israel forever,
therefore made he thee king to do judgment and justice.`"

Now mark, all you that call yourselves christians, that say,
you had not known that there had been a God or a Christ,
if scripture had not declared them unto you: what scripture had this woman,
that came from afar off, who had neither written law or gospel.
And yet she heard of the name of the Lord, and of the fame of Solomon,
and blessed the Lord God, and said, he loved Israel,
and made Solomon king to do them equity and righteousness?

Now how could she talk of righteousness and equity, and of the Lord God, and of his name,
having neither written law nor gospel?
Would not you have said, that she had been a foolish woman,
and run mad out of her own country.

But was not this a divine principle, that brought her to come and see,
by which she was satisfied and refreshed, blessing the Lord God?
and she gave Solomon abundance of choice things, showing her love to God and his people,
and this she did by that divine principle and power of God in her; for God is a spirit,
and he and his things are made known by the spirit;
and so she judges all you by a divine power and spirit in her,
who had not the letter of the scripture to be an outward guide to her, as you have,
without which (as you say,) you had not known that there had been a God or Lord,
without the letter, and yet you see here she could tell without it, and bless the Lord.
Would not you have said she had been a preaching woman, and come to preach to the king?

Gen.
39. We read how Joseph was sold by the Ishmaelites into Egypt to Potiphar,
captain of Pharoah`'s guard, an Egyptian; and his master seeing the Lord was with him,
and how God made all to prosper in his hand,
insomuch that Joseph found favour in his master`'s eye,
so that he made him ruler over of all his house.

Now consider that this Potiphar was a heathen,
and yet he was made sensible how God was with Joseph, and blessed him for Joseph`'s sake;
and so through that sight that he had of God, he found favour with his master,
and how he could speak of God, and all this without written law or gospel.

Consider, I say, was not this Potiphar`'s sight far beyond all your blind christians,
that say, "`you had not known that there is a God or Christ,
unless the letter of the scripture had declared it unto
you;`" and so are not you more heathenish than this man?

Further observe, one cause of his loving Joseph was, that he saw God was with him,
and therefore loved him: wherefore you hate us the more,
in regard many of you cannot but be sensible the Lord is with us.

And did not the jailer there in Egypt, to whom Joseph was committed as a prisoner;
did he not see that God was with Joseph, and how that God prospered whatever he did;
and was not his sight beyond all you priests, that say you have not known God,
unless scripture had declared it to you.

And so are you not as dark as all your fellow-high priests,
that could not see Christ when he was come, but persecuted him?

And what scripture had the jailer, or what rule to see by, that God was with Joseph,
and how God had prospered whatever he did?
Was not this something of the divine light, both in Joseph and in the jailer,
which is testified by scripture?

Gen.
10. We read how Pharoah being displeased with his butler and baker,
cast them into prison, where Joseph was imprisoned;
and how they declared to Joseph each his dream, that they dreamed there.
Now was there not something in their two dreams which came to pass,
according to Joseph`'s interpretation?

And here Pharoah`'s servants judge you christians, that neither allow prophesies,
nor revelations.

Gen.
41. When Joseph had interpreted Pharoah`'s dream,
concerning the seven fat and seven lean kine, said Pharoah to Joseph,
"`Where shall we find such a man as this is thou speakest of,
in whom is the spirit of God; forasmuch as God has showed thee all this,
and that there is no man of understanding and wisdom like unto thee;
therefore thou shalt be over mine house,`" etc.

So all you christians may here see that Pharoah, a heathenish king,
doth here acknowledge God, and the spirit of the Lord was in Joseph;
and how that the king confessed and acknowledged that God had showed Joseph his dream;
and yet this Pharoah had neither written law nor gospel to inform him to confess God,
nor to know that there was a God; and yet he could confess to him, and say,
"`The spirit of God was in Joseph.`"

So then, that which brought him to confess and acknowledge the living God,
without the letter of law or gospel, judgeth you that say,
"`you know not that there had been a God, or a Christ,
without you had the letter to declare it to you.`"

Jonah 1. Where you may read how the master of the ship that set out from Joppa,
bound for Tarshish, said to Jonah, being a passenger in it,
when the ship was in a storm like to perish, "`what meanest thou, O sleeper, arise,
and call upon thy God, if so be, that God will think upon us, that we perish not.`"
And when they cast lots,
that they might know for whose cause this evil was come upon them;
the lot fell upon Jonah, to whom they said, "`what is thine occupation,
and whence comest thou?`"
etc. He answered, he was an Hebrew, and feared the Lord, the God of heaven,
which made the sea, and the dry land.
Then were the men exceedingly afraid, and said unto him, "`why hast thou done this?`"
for the men knew that he had fled from the presence of the Lord.

Now, before they did cast Jonah overboard into the sea, as he advised them,
they prayed unto the Lord, saying, "`we beseech thee, O Lord,
we beseech thee let us not perish, for this man`'s life;
and lay not upon us innocent blood; for thou, O Lord,
hast done as it pleaseth thee:`" so they cast him into the sea,
and the sea ceased from her raging; then the men feared the Lord exceedingly,
and offered a sacrifice unto the Lord, and made vows unto the Lord.

Now hear, and see this all you, called christians, that say,
you had never known there was a Lord, or Christ,
if scripture had not declared it unto you.
Were not these mariners heathens?
They had no written law nor gospel,
and yet did confess that the Lord did what pleased him, fearing God,
sacrificing and making vows to him, crying unto the Lord,
desiring that he would not lay innocent blood to their charge,
and that they might not perish; and desired Jonah to call upon the Lord.

Now, was there not something in these heathens above yourselves, who had no scripture,
and yet acknowledged God; whereas you say, you had not known there had been a God,
unless you had scripture to declare it to you: neither indeed do you know him now,
though you have scriptures;
nor yet have the spirit as they had that gave forth the scripture through them,
nor heard his voice, and yet pretend to be preachers of God, and of Christ,
but know neither, but are preachers for your bellies, and serve them,
and not the Lord Jesus.

Jonah 3. There we read the Lord commanded Jonah the
second time to arise and go unto Niniveh,
that great city, and exhort them to repent.
And then Jonah entered a day`'s journey into the city, and cried, "`yet forty days,
and Niniveh shall be destroyed.`"

So, the people of Niniveh believed God, and proclaimed a fast, and put on sackcloth,
from the greatest of them, even to the least of them.

And word came to the king of Niniveh, and he arose from his throne,
and laid his robe from him, and covered him in sackcloth, and sat in ashes,
and caused to be proclaimed through Niniveh, by the decree of the king, and his nobles,
saying, "`let neither man or beast, herd or flock, taste any thing, let them not feed,
or drink water; but let man and beast be covered with sackcloth,
and cry mightily unto God; yea, let them turn every one from his evil way,
and from the violence that is in their hands, who can tell if God will turn and repent,
and turn away from his fierce anger, that we perish not.

And God saw their works, that they turned from their evil ways;
and God repented of the evil, that he had said he would do unto them, and he did it not;
which made Christ to say,
"`that the men of Niniveh should rise up against that present generation,
which had the scriptures, but repented not at his preaching,
whereas they repented at the preaching of Jonah,
and behold a greater than Jonah is here.`" Matt. 12:41.

So now consider, you that are called christians, how Niniveh repented,
and God spared them; and the king persecuted not Jonah, as a false prophet,
but hearkened to Jonah`'s words, and believed, and cried unto the Lord, fasted,
and turned from the evil of their ways, so as God had mercy on them.

Now was not there something of God in these heathens, that made them cry to God,
and turn to God, and believe in God, whom you look upon, I say, as heathens,
who had not the letter of the scriptures,
neither written law or gospel which were more than six score thousand persons,
as scripture saith,
"`that could not discern between the right hand and
the left;`" and yet these could tell of God,
and cry unto him at the preaching of Jonah?
and yet you cannot tell, (you say,) "`whether there be a God or Christ,
unless scripture declare it to you.`"

And if any of God`'s servants come and call upon you to repent,
in your streets at any time, you stone them, or cast them into prison, or beat,
or whip them, as vagabonds; whereas Niniveh did not so to Jonah: but as Christ said,
"`they shall rise up in judgment against this wicked generation.`" Matt. 12:41.

This I say you do, instead of turning from your wickedness,
and from the evil of your ways, and from your false worship; so that I say once more,
Niniveh will arise up in judgment against you blind professors,
who are so full of the letter, and empty of the life and spirit that gave it forth,
as the pharisees were, and ignorant of the knowledge of God,
being ravened and erred from the spirit.

Joshua 2. Where we read how Joshua sent two men out of Shittim, to spy secretly, saying,
"`go and view the land, even Jericho:`" and they went and lodged at one Rahab`'s house,
a harlot: and when the king heard of their being at her house, he sent to her,
to bring them forth; but instead thereof, she went and hid them,
and after took care to send them privately away; saying unto them,
"`I know that the Lord hath given you the land, and that your terror is fallen upon us,
and that all the inhabitants of the land do faint because of you;
for we have heard how the Lord dried up the waters of the red sea for you,
etc.--for the Lord your God, he is God in heaven above, and in the earth beneath;
now therefore, I pray unto you, swear unto me by the Lord,`" etc.

Mark, here is a woman, an harlot, that had no letter of written law or gospel,
being a heathen in your account, how nevertheless, she confessed to the Lord,
that he was God in heaven above all, etc.

Now, was not this from a divine power and principle?
And did not her faith keep her from perishing with the rest,
as is there recorded by the Holy Ghost, in Hebrews 11:31.

And doth not this harlot judge you, who have the letter of the law and gospel,
and yet had not known that there was a God and a Christ,
if the scriptures had not declared it to you,
and so could not confess to God in heaven above, and in earth beneath,
as this woman did without the letter.

And it is worth your remark, that she, as a prophetess, foresaw,
and so encouraged God`'s people, saying, "`the Lord hath given you the land;`" and this,
I say, she spoke a good while before it was given unto them, namely,
to the children of Israel.
And this she spoke, that had no scripture to speak it by, but by faith.
But you that have neither faith, nor the spirit of God to guide you,
since prophesy is (as you say,) ceased, and you cannot endure women to preach:
but see what a brave sermon she preached to the spies,
and yet you cannot abide women`'s preaching; and if so be you do,
why did you record her preaching, and Huldah`'s,
and Mary Magdalen`'s preaching of Christ`'s rising to the apostles;
and Mary and Elizabeth`'s preaching, and old Hannah`'s preaching in the temple,
and old Dorcas, who was a woman-disciple of Christ.

2 Kings 5. We read, how that Naaman, captain of the king of Assyria`'s host,
came to Elisha, to be healed of his leprosy; and the prophet sent out to him,
to go and wash seven times in Jordan, and he should be cured,
which Jordan signifies the river of judgment.
But Naaman was sore troubled that the prophet came not out to him, himself,
as he expected he would, and call on the name of the Lord his God,
and strike his hand over the place, and so recover him:
but his servant came near and said to him, "`my father,
if the prophet had bid thee do some great thing, wouldst thou not have done it?
How much rather then, when he saith unto thee, wash and be clean?`"
whereupon he went and washed seven times, and was cured:
and so he returned to the man of God, and said, "`behold,
now I know that there is no God in all the earth, but in Israel:
and that he would from thenceforth offer sacrifice to no other God, but unto the Lord.`"
And he desired of Elisha, "`that when he went with his master into the house of Rimmon,
and bowed down, he desired the Lord to pardon him in that thing.`"
Now mark, what scripture had this man to confess God, and speak all these things?
Had he either law or gospel?
Was there not a principle of God in him, that brought him to confess God,
though he had no scripture?
And are not many servants forced to do that amongt those called christians,
as Naaman was, namely,
to go to a worship with his master contrary to the mind of the Lord,
and that principle of God in them?
So I say, do not you force many of your servants to do that which is contrary to God,
in following your ways, religion, and worship, which you made yourselves,
and set up in your steeple-houses, the places of your worship?
And think you that many of your servants and children are not troubled,
and cry for mercy to the Lord, as Naaman did;
who are forced contrary to the spirit of God, his principles in them, to your worship,
which neither God or the Lord Jesus ever set up.

2 Kings 6:8, etc.
We read of the king of Assyria`'s warring against Israel,
and how he took counsel of his servants,
which counsel was made known to the king of Israel, by the prophet Elisha,
whereby the king was many times kept out of danger,
which thing sorely troubled the king of Assyria,
in that he thought one of his counsellors might be false, and reveal his counsels; for,
saith he, "`will ye not show me which of us is for the king of Israel?`"
And one of his servants said, "`none, my lord, O king; but Elisha the prophet,
that is in Israel,
telleth the king of Israel the words that thou speakest in thy bed-chamber.`"

Whereupon the king sent a great host, to fetch Elisha out of Dotham, a city in Israel,
where he understood he was, and to that purpose compassed the city round,
both with horses and chariots; and Elisha went forth to them, and met them,
and prayed to the Lord, to smite the host with blindness, and so the Lord did:
and then Elisha said unto them, "`this is not the way, neither is this the city;
follow me, and I will bring you to the man whom ye seek.`"
But he led them to the gates of Samaria; and having prayed again to the Lord,
to open their eyes, who did so, so that they saw they were in the midst of Samaria:
and when the king of Israel would have smote them, Elisha would not suffer him;
but bid him set bread and water before them, that they might eat and drink,
and go to their master: so the king of Israel prepared great provision for them,
and afterwards sent them away in peace;
so as the bands of Assyria came no more into the land of Israel.

Now mark, what was this in the king of Assyria`'s servant,
that had neither written law or gospel, that enabled him to inform his master,
that it was the prophet Elisha, that from time to time told his words to the king:
of Israel, and revealed his counsels,
even what his master said privately in his bed-chamber.

Would not you papists, and protestants, that say,
"`you had not known whether there be a God, or a Christ,
had you not had the scripture to declare it unto you;`"
would you not (I say,) have been ready to have said,
that both the prophet, and the king of Assyria`'s servants, were witches; the one,
for telling the king of Israel, and the other,
in that he was able to inform the king of Assyria with it; and if it lay in your power,
(had such a thing been in your day,) would you not be as ready to put them both to death.
Nehemiah 6:16.
Here you may perceive, what all the enemies of the Jews, both heathen,
and some Jews,
that combined against them as they were busy in building the walls of Jerusalem,
having obtained leave of Darius; and when Sanballat and others, their enemies,
heard that they had finished the wall, it is said, "`their courage failed them,
and that they were afraid: and their enemies did perceive,
that the Jews`' work was of God.`"

Now, +++[+++mark,]
all you that call yourselves divines (and say,
that you had not known that there had been a God, or a Christ,
unless you had scripture to declare it to you,) how these heathens,
who were real enemies against the Jews, perceived that this work was of God,
who had neither written law or gospel.

Can you believe this, that they should be able to perceive that this work was of God,
having neither written law or gospel, but followed other gods of their own making?
What think you with all your wisdom, and your seven years schooling?
Was there not something of God in these heathens, that convinced them,
so that they were forced to acknowledge, that the work was of God,
which struck them into a fear, so that their courage failed them?

And here do not these heathens judge you christians by profession,
(who had neither written law nor gospel,) that have both,
in that they could speak of God without it?

Are not they the greatest heathens of all, who have both written law and gospel,
and yet deny Revelation?
Which clearly manifests their knowledge is no knowledge of Christ;
"`for no man knows the Son, but the Father; and none knows the Father, but the Son,
and to whom he reveals him.`"

And so these that have the letter of the scripture, and do deny Revelations,
whereby God and Christ are known,
and yet judge all others who have not the letter of the scripture,
that they are heathens; yea, and judge many of them, (whom they have baptized,
and called christians,) as not having the spirit of God,
though they were baptized by themselves, and pronounced heirs of the kingdom,
and that they were the children of believing parents.

Now the heathens that knew God, it was by Revelation,
who had not the letter of the scripture; and you that have scripture,
and deny Revelations, you deny that that gave others,
and should give you the knowledge of God, and of Jesus Christ.

So now, to close up all at present, you may see clearly, how that God did not,
as the apostle saith,
"`leave himself without a witness,`" Acts 14. "`but what
may be known of God is manifest in man,`" Rom. 1:19,
even in the very heathen also,
as well as all the holy men and all the holy women in the scriptures,
as may be read and seen in the scriptures of truth; which we own,
and have a high esteem of, and all the holy men and holy women of God,
Christ`'s prophets, and apostles, and their writings,
above all other writings in the world extant, which are given forth in the wisdom of men,
for the holy men of God spoke as they were moved by the Holy Ghost,
as they learned of God, which Christ came to fulfill; and his disciples, followers,
and all his people, who receive Christ, receive him that doth fulfill them,
and opens the scripture to them by the Holy Ghost,
who leads them into all the truth of them.
