[quote.epigraph, , 2 Cor. 4:1-2]
____
Seeing we have this ministry, as we have received mercy, we faint not:
but have renounced the hidden things of dishonesty, not walking in craftiness,
nor handling the word of God deceitfully, not by the manifestation of truth,
commending ourselves to every man`'s conscience in the sight of God.
____

== An Epistle / By way of preface to the Unprejudiced Reader.

The books and treatises in the following collection being perused,
we find the doctrine of our blessed Lord and Saviour Jesus Christ, and those matters,
essential to salvation and true christianity, so plainly asserted,
and fully demonstrated, according to holy scripture testimony,
as may sufficiently obviate our former and present adversaries`' objections,
and refute their calumnies and aspersions to the contrary.
And, though the most eminent reformers and martyrs have been most envied
and misrepresented by their adversaries in all ages,
as this true servant and minister of Christ was in his day, and since removed,
his name and memory most unjustly defamed by envious spirits;
yet the good report and fame, through which he, through faith,
(and blessed effects of his faithful labours, great travels and sufferings) obtained,
will outlive the great envy of his and truth`'s adversaries.
And as he was a true minister and witness for Christ and his kingdom,
both in life and doctrine, so he was a plain and true witness against antichrist,
and his kingdom; and although he gave preference to the holy spirit,
as all true spiritual christians do, yet his true love to, and sincere esteem of,
the holy scriptures, (being given by divine inspiration.) was clearly manifest.

[.numbered-group]
====

[.numbered]
_1st._ In his frequent advice to Friends to keep to scripture language, terms,
words and doctrines, as taught by the Holy Ghost, in matters of faith, religion,
controversy and conversation, and not to be imposed upon,
and drawn into unscriptural terms, invented by men in their human wisdom.

[.numbered]
_2d._ In his great industry in searching the holy scriptures, and frequently quoting,
reciting, aptly applying and opening the same in his writings,
as will appear in the following collection.
He truly testified, both in his ministry and writings, for Christ Jesus,
his power and coming in the flesh, and in the spirit;
he was both for the sacred history and ministry of Christ,
revealed according to the holy scripture testimonies of him,
respecting his sufferings without, the work of his power within,
and his kingdom and glory; under whose conduct, this his minister faithfully warred,
against the spirit of antichrist and persecution, and against the mystery of iniquity,
mystery Babylon, the false church, the power of darkness, the corruptions of the world,
and its deceit and hypocrisy under all professions;
and in the Lord`'s hand and power was instrumental in turning many to righteousness,
and from darkness to light, and from the power of Satan unto God,
that they might receive remission of sin, through faith in his dear son Christ Jesus.

====

He gave a thorough stroke in his ministry and writings against the son of perdition,
antichrist, Babylon, the beast and false prophet,
and therefore was the more hated by those in whom
the spirit of enmity and persecution ruled:
and we question not,
but he has his lot and portion with the holy prophets and apostles in heaven;
and a share in their rejoicing, at the downfall of mystery Babylon,
the mother of harlots, and the kingdom of antichrist and Satan:
therefore rejoice ye heavens, and ye that dwell in them rejoice over her; thou heaven,
and ye holy apostles and prophets, for God has avenged you upon her. Rev. 12:12.
and Rev. 18:20. which certainly will be fulfilled at her final downfall.

And as this faithful minister and witness of Christ was a man fearing God,
hating covetousness, and eschewing evil, and was a deep sufferer,
for his testimony to the truth, when on earth; he died in the favour of God,
and rests with him in heaven, with his church triumphant over his persecutors,
and the persecuting spirit, which blasphemes against God and his tabernacle,
and them that dwell in heaven: glory to our God, and to the lamb on the throne forever,
Hallelujah.

Signed at our Second-day morning meeting.

[.signed-section-signature]
George Whitehead, Francis Camfield, William Bingley, John Butcher, William Warren,
Thomas Lower, Theodore Eccleston, Richard Needham, William Robinson, Daniel Monro,
John Kent, George Oldner, George, Chalkley, John Tomkins

[.signed-section-context-close]
London, the 24th of the tenth month, 1705.
