[short="A Paper Published in 1654"]
== The Following Paper Was Published 1654 / with Several Papers of Other Friends

[.heading-continuation-blurb]
To all who love the Lord Jesus Christ, mercy and peace be multiplied unto you.

Who have been scattered abroad in the cloudy dark day from mountain to mountain,
and worshipping that which you know not, following the imagination of others,
which they spoke from the divination of their own brain,^
footnote:[Ezek. 34:12]
and not from the mouth of the Lord,^
footnote:[Jer. 23.]
shepherds that fed themselves, and clothed themselves with the wool,
and sought after the fleece,^
footnote:[Ezek. 34:23]
and so made a prey upon us, and upon the people.
Our God (as he promised, saying, I will gather my sheep from your mouths,
and seek them which have been scattered in the cloudy dark day) hath gathered us,
and doth feed us upon the mountain in a good pasture;
and so we witness the promise of the Lord fulfilled:
and as the Lord said I will seek that which was lost,
and bring again that which was driven away, through that one shepherd Jesus Christ;
herein do we witness the Lord fulfilling the scriptures in us,
and I witness the lost sheep is found;
and the Lord hath brought back again that which was driven away;
and here do we deny all the teachers of the world,
who speak a divination of their own brain,^
footnote:[Jer. 23:16]
and not from the mouth of the Lord;^
footnote:[Isa. 65:10-12]
for who spoke from the mouth of the Lord, denied them then; so do we by the same word:
and we deny all them that seek for gain from their quarters,^
footnote:[Isa. 55:1-4]
which are greedy dumb dogs, as the scripture saith;
and all those who take the people`'s money, and sell the letter,
which was spoken forth freely; for Isaiah that spoke from the mouth of the Lord,
he denied such things, and bid all come freely, without money, and without price,
to hear the voice of the Lord, that their souls might live,
and to make with them an everlasting covenant, even the sure mercies of David:
and this covenant I do witness; therefore I deny with the same word,
wherewith they spoke, the same things the scripture denieth,
and all those that bear rule by their means, and hirelings which preach for hire,
and prophecy for money.
For Jeremy, who had the eternal word, denied such things,^
footnote:[Jer. 5:30-31]
Micah denied such things;^
footnote:[Mic. 3:11]
and Jesus Christ who was the word, said, the hireling would flee,
because he is an hireling:^
footnote:[John 10:13-14]
and this word the Lord hath made manifest, which gathers our hearts together up to God,
and opens to us the scriptures,^
footnote:[2 Cor. 5:19;]
whereby we see the deceits of the Priests of the world now,
of the same generation and nature, and acting those things there is no scripture for,
which the holy men of God did not practice.
And for taking tithes, in the old time Levi was to receive tithes,^
footnote:[Duet. 26:12]
and the strangers, the fatherless and widows were to come and eat,
and be filled within his gate; but this was according to the law;
and here you see the priests of the world do not act according to the law,
in which were types and figures of Christ; and when Christ was come,
those he sent forth were not to have a bag, flora stick to defend them, nor two coats,
nor brass, nor silver; but freely ye have received, freely give:^
footnote:[Matt. 10:8-10]
the workman is worthy of his meat; so they neither walk according to the law,
nor the gospel, therefore we deny them; and the minister of Jesus Christ,
which went into the world, they had no portion of the world, but whipping, stocking,
prisoning.^
footnote:[2 Cor. 11:24; Acts 4:3,5:40, 7:58]

But they that were gathered out of the world in the eternal word, which met together,
and were of one heart, one mind, one soul, to such they said,
if we minister unto you spiritual things,
is it a great thing if you minister to us carnal things?^
footnote:[1 Cor. 9:10-11; Gen. 17:11]
This was spoken to them upon whom the end of the world was come; and this I do witness,
what the scripture doth say: God commanded an outward temple, circumcision, the sabbath,
given as figures and types, and shadows of Jesus Christ;^
footnote:[1 Chron. 22:11; Ex. 31:13-14, 17-18]
but when Jesus Christ, the substance was come, and when he was crucified and risen,
who believed in him, preached his resurrection,
and so went up and down in the synagogues, and into the temple,
reasoning and disputing with them that held them up,^
footnote:[Acts 17:2; Acts 4:2]
to bring them out of the figure, up to Jesus Christ, who was the substance;
so all which were gathered together in the substance, met together,
and then the church was in God,^
footnote:[1 Thess. 1:1]
and they denied the outward temple, which God commanded, being made the temples of God;^
footnote:[2 Cor. 6:16-17]
and denied circumcision outwardly, being circumcised with the spirit;^
footnote:[Rom. 2:28-29]
and denied the Jewish sabbath outwardly, and observing days;^
footnote:[Col. 2:16-17; Gal. 4:10]
for he that believes is entered into his rest, and hath ceased from his own work,
even as God from his.^
footnote:[Heb. 4:10]
And all those now, who have received Jesus Christ the substance,
who is the head of the church, deny all types and figures of him,
and do witness the scriptures fulfilled; and Jesus Christ,
who is the mediator between God and man, being made manifest in them,
makes them all of one mind, and one heart, and to deny the priests of the world,
who profess him in words, and act those things he forbids.^
footnote:[1 Pet. 2:25; 1 Tim. 2:5; Col. 1:26,29]

As, first, sprinkling of infants, and telling people they baptize them into the faith,
into the church, which there is no scripture for;
but the baptism by one spirit into one body, this we own; and the church is in God,^
footnote:[1 Cor. 12:13]
as Paul, and Silvanus, and Timotheus wrote to the church of the Thessalonians,
which was in God.^
footnote:[1 Thess. 1:1]
And they tell people of a sacrament, for which there is no scripture; that we do deny,
and them; but the Supper of the Lord we own:^
footnote:[1 Cor. 10:15-17]
the bread that we break is the communion of the body of Christ,
the cup we drink is the communion of the blood of Christ,
all made to drink into one spirit.
And the singing of psalms after their manner, we deny; for they sing David`'s tremblings,
quakings and roarings; this they have turned into metre;
as if we should see one of you lie roaring and crying, till his eyes should grow dim,
and watering his bed with tears,^
footnote:[Ps. 6:6; 131:1]
and we should turn it into metre, and make a rhyme of it, and take it,
and go among a company of ignorant people, and say,
let us sing to the praise and glory of God.
O Lord, I am not puffed in mind, I have no scornful eye, when they are puffed in minds,
and have scornful eyes: and when they read the psalms, they keep on their hats,
and when they sing them, they keep off their hats;
here they worship the work of their own bands; all such practices we deny:
but we will sing with the spirit, we will, sing with grace,
we will sing with understanding, praises, praises unto the Lord God on high.
And they speak a divination of their own brain, and not from the mouth of the Lord;^
footnote:[1 Cor. 14:15]
and such the Lord sent his prophets to cry out against;^
footnote:[Col. 3:16]
all these now who study a divination of their own brain,
and speak not from the mouth of the Lord, we do deny:
and all who are made ministers by Oxford and Cambridge, bred up with learning,
and so made ministers by the will of men,^
footnote:[1 Cor. 2:14; Gal. 1:1,14:1]
and speak natural languages, as Hebrew and Greek, and say that is the original,
which a natural man may learn, and the natural man knows not the things of God,
and all such we do deny; for Paul was brought up at the feet of Gamaliel,
in the Jewish religion, but that did not make him a minister of Jesus Christ;
for he declares that he was not made a minister by the will of man, nor of man,
neither by man, but by the will of God, and all such I own,
who stand out of the will of man, denying all carnal-ends;
for this ministry draws up to God out of the world,
and doth not respect any man`'s person, but ministers to that which is in prison.^
footnote:[1 Pet. 3:19]
But those teachers which are made by man, say, the letter is the light,
the letter is the word; the four books, Matthew, Mark, Luke and John, is the gospel,
when the letter saith, Christ is the glad tidings which was promised,
the Lamb of God which taketh away the sins of the world,
and this we witness to be fulfilled.^
footnote:[The gospel of Christ, which is the power of God to salvation, Rom. 1:16.
was before the four books were,
though they contain true declarations thereof.]

All they that are in the light are in unity; for the light is but one,
and who know the light are in unity; all who know the word, which is a mystery,
are come to the beginning, are sanctified by the word, and clean through the word;
for this word is a fire, burning up all corruption,
as an hammer beats down all high minds, high nature, that the pure seed may be raised up;
as a sword cuts to pieces, and divides asunder the precious from the vile,
and makes a separation inwardly and outwardly from uncleanness;^
footnote:[John 1:9]
and this is the word of reconciliation, that reconcileth together to God,
and gathers the hearts of his together,^
footnote:[John 1:1]
to live in love and unity one with another,^
footnote:[Gen. 3:15]
and lets them see how they have been strangers and aliens from the life of God;^
footnote:[Luke 2:10-11]
the light and the word draws from under the occasion of all laws outwardly,^
footnote:[John 1:29]
working out that filthy nature which the outward law takes hold on;^
footnote:[John 15:3]
so walking in the spirit^
footnote:[Heb. 4:12]
there is not a fulfilling the lusts of the flesh;^
footnote:[2 Cor. 5:19]
and the spirit is but one, which baptizeth into one body,
which we do witness to be fulfilled;^
footnote:[Eph. 2:12]
praise be to the Lord.

And whereas we are a people accused to raise up a new war, it is false;
for dwelling in the word, it takes away the occasion of wars,
and gathers our hearts together to God, and unto one another,
and brings to the beginning, before wars were; for the ministers of God,
which had the word of reconciliation to draw them from the occasion of all wars,
working out that nature that occasions war, said, whence do wars arise?
even from the lusts.^
footnote:[James 4:1-2]
Therefore, all dear people, who love the Lord Jesus Christ,
and the appearance of Jesus Christ in your souls, be not talkers of the truth,
nor followers of the blind guides,^
footnote:[Matt. 23:16]
but mind the pure light of God in you, which shows your sin and evil,
and how you have spent your time, and shows you how your minds go forth,
and every carnal thought; and if you love that light, you love Christ,^
footnote:[1 John 2:10]
and walking in the light in measure, there will be no occasion of stumbling,
for all stumbling is in being disobedient, and wait to find the word in you,
as the scripture saith; not to fetch it from above, nor from beneath; but what saith it?
It is nigh thee, in thy heart, for with the heart man believeth,
and with the tongue confession is made unto salvation:^
footnote:[Rom. 10:10-8]
and abiding inwardly in the light, it will let you see one another,
and the unity one with another,
and the teachers of the world to be the ministers of the letter.

And whereas we are accused for going into steeple-houses,
it was the practice of the apostles to go into the synagogues,
reasoning and disputing about the scriptures,^
footnote:[Acts 7:47-49]
shewing them the substance,
and they told them that God did not dwell in temples made with hands,
neither was he worshipped with men`'s hands: Stephen saith,
the most high dwells not in temples made with hands,
and for witnessing forth the substance, was stoned to death;
but these were types of Jesus Christ.
And the saints who were made the temples of God, denied the outward temple;
but there is a ministry now which doth in words profess Jesus Christ,
holds up these outward temples, and as Moses, which was a type of Christ,
which was a servant, was faithful in his house,
so the deceit (after him) got into his place,^
footnote:[Heb. 3:5]
and was called of men masters, which sat in his seat, which pretended justice,
and did it not; and that was the time before Christ was sacrificed up,
who came to fulfill the law, and not to break it; but he cried,
woe unto them that were called of men masters^
footnote:[Matt. 23:6]
and had the chiefest place in the assemblies, and laid heavy burdens upon the people,
and painted themselves with the prophets`' words.
But when Jesus Christ was sacrificed and risen,
and his ministers preached his resurrection,
they did not hold up the types and figures then, but held forth the substance,
Jesus Christ; and all who were gathered together in the substance, were of one heart,
one mind, one soul, and met together, and exhorted one another,
and builded up one another in the most holy faith,^
footnote:[Acts 4:32; Jude 20; Eph. 4:5]
and all true building is in that which is holy;
(and this faith I witness) which is but one, and all are one that are in it,
if ten thousand, which purifies the heart, stands in God;
glory and honour to the highest; and whom Jesus Christ made ministers,
he made them not masters; but said, be ye not called masters, for ye have one master,
even Jesus Christ.^
footnote:[Matt. 23:6-7]
But the teachers of the world, who in words profess the Lord Jesus Christ,
are called of men masters, and lay heavy burdens upon the people, go in long robes,
having the chiefest place in the assemblies, standing praying in the synagogues;
and they that did so, Christ Jesus said, their prayers were heathenish;
which shows they were never taught of him, for they abode not in his doctrine;
and he that abideth not in the truth is of the devil;^
footnote:[1 John 3:8]
and here they show themselves neither to follow Jesus Christ the example,
nor the apostles as an example, but take the scriptures to trade withal.

And all those which Jesus Christ, the prophets and apostles do deny, we deny.
When the apostles spoke to the saints,
he bade them take heed to the light that shined in a dark place, till the day dawned,
and the day-star arose in their hearts;^
footnote:[2 Pet. 1:19]
and as the light appeared, so they exhorted one another; for there were false prophets,
and false teachers among the people, which with feigned words and covetousness,
made merchandize of them, who had forsaken the right way, following the ways of Balaam,
going in the way of Cain, whose sacrifice God did not accept.^
footnote:[Jude 11]
Now all people that love the Lord Jesus Christ,
you may see all the teachers of the world there, going after the ways of Balaam;
for then that doctrine crept in, which is scattered over the world,
and the apostles saw certain creeping into houses, leading silly women captive,
laden with sin, and divers lusts, which were ever learning,
and never able to come to the knowledge of the truth, which he describes;
they were lovers of their own selves, covetous, proud, heady, high-minded, self-willed,
incontinent, truce-breakers, false accusers, fierce, despisers of those that are good,
and lovers of pleasure more than lovers of God; having a form of godliness,
but denying the power thereof; as Jannes and Jambres withstood Moses, so do these;
men of corrupt minds, reprobates concerning the faith; but they shall proceed no further,
their folly shall appear to all men.^
footnote:[2 Tim. 3:1-9]

Now the apostle bids, from such turn away; though once he said,
some preach Christ of envy, some of strife and contention, some of good will,^
footnote:[Phil. 1:15]
though their intention was but to add affliction to his bonds, yet he rejoiced in it;
and that was a time when few did believe that that was the Christ;
so that his name was spread abroad, he did not matter what they were;
but when his name was spread abroad, and many got the form, and had not the power,
such were antichrists, and were denied by them who had power, and so they are now.

And all people consider (you that have been long hearers and learners)
if you be yet come to the first principle of religion,
to that which turns the mind to God:^
footnote:[Heb. 6:1;]
all whose faith doth not purify, they are reprobates concerning the faith.^
footnote:[2 Tim. 3:8; 1 John 3:3]
So ask any priest or people, whether they shall overcome the body of sin,
as long as they are upon the earth?
they will say no.
Therefore their seeming faith I deny, for faith purifies the heart,
and gives the victory over the world;^
footnote:[1 John 5:4]
and this I own, and you have put off the body of sin,
by the circumcision made without hands;^
footnote:[Col. 2:11]
and whilst we were servants of sin, we were free from righteousness, but God be thanked,
who hath made us free from sin, to serve God in righteousness,
in the newness of the spirit, and not in the oldness of the letter.^
footnote:[Rom. 6:22; Rom. 7:6]

And whereas we are accused for not owning magistracy; justice we own for conscience sake;
for that light which is in the conscience, loves equity, and righteousness, and justice,
and leads out of all evil, and uncleanness;
for let every soul be subject to the higher power, for all power is of God,^
footnote:[Rom. 13:1]
and the powers of God our souls are subject unto; for he that resisteth that,
resisteth the ordinance of God; but who lives in drunkenness, in pride, in covetousness,
murder, lust and uncleanness, their souls are not subject to the higher power,
but resist it, and that nature we do deny, and justify that which cuts it down:
we own honour and set it up; and honour all men in the Lord;
but as for respecting persons we deny, for he that respects persons, commits sin,
and is a trangressor of the law.
For to respect a proud man, because he hath a gold ring on his finger, and fine apparel,
such respects we deny, for the scriptures deny the same;^
footnote:[James 2:2,9; 5:2]
and to set up a great man which hath abundance of earth, joining field to field,
and land to land, and respect such above the poor, this is an evil eye;^
footnote:[Isa. 5:8]
for God cries woe unto such, for God hath made all of one mold, and one blood,
to dwell upon the face of the earth, and he is no respecter of persons;
and who are in the faith of the Lord Jesus Christ, it is without respect of persons;^
footnote:[Acts 17:24; James 2:5]
for it is but one, and makes all one, one seed, one soul, one heart, one mind,
in one God, father of all, over all, blessed forever:
and this we do witness (praised be the Lord) to be fulfilled,
which all the holy men of God did witness forth, a good conscience,
and therefore we have a cloud of witnesses which are recorded in the scriptures.^
footnote:[Heb. 12:1]

And whereas we are accused for uncivil speeches, which the world calls uncivil,
and railing, as because we say thou to a particular person, and you to a number.
The scripture witness,^
footnote:[Acts 26:2,27]
that all the holy men of God practised the same, thoued one, and yeed many; thoued kings,
thoued God, thoued Christ, and said, thou O Lord of heaven and earth;^
footnote:[Ps. 25:1]
and therefore who art thou, O proud flesh, that thou art exalted?^
footnote:[2 Thess. 2:3]
Dost not thou, thou God, and thou Christ, in thy prayers?
And wouldst thou be yeed?^
footnote:[John 21:15]
Here shows the son of perdition himself,
and is exalted above all that is called God in thee;
and the language of God is not known with thee.
And as for the customs and fashions of the world,
bowing and making obeisance with cap and knee,
which men and women have done one to another, which lived without the fear of the Lord,
we deny;^
footnote:[Job 32:21]
but we honour all men in the Lord with our souls, and with our hearts,
and who looks for these things outwardly, there is a fleshly principle,
for these things may he done and are practised, and the heart full of envy;
therefore all these fashions we deny.^
footnote:[Acts 10:34; Rom. 12:2, Jer. 10:3]
And touching good-even and good-morrow, which are customs of the world,
spoken without fear of the Lord, we do deny; but good to all men we wish,
and the good day, that they may be brought into it, and that they may see the happy day;
but the vain fashions and customs which the fleshly and heathenish nature holds up,
and when it is crossed in its ways and customs, rageth, and is mad, we deny;
and that nature which holds up all these things, we deny.

For the God of power, light, and glory, hath raised up a light in his people,
and gathered their hearts together to himself,
and hath discovered unto them the vanity of all things, wherein they have lived,
and showed them his way and truth, where they should walk and glorify him,
and serve him in holiness and newness of life;^
footnote:[John 14:6; Rom. 7:6; John 6:35]
and with eternal food, the bread of life, doth he feed us,
whereby we become wonders to the world,^
footnote:[Isa. 2:20-21]as he hath raised his seed to his praise and glory,
and is adding daily to his church,^
footnote:[Acts 2:47]
and the strong man bows himself, and the keepers of the house tremble,^
footnote:[Ecc. 12:3]
and the powers of the earth shake, and the glory of the Lord is rising, and is risen,
which terribly shakes the earth, that the idols of gold and silver are cast away,
and God alone loved, who is Lord of heaven and earth;
and the works of the Lord are strange and wondrous, as ever were,
as the scriptures witness.
When Daniel heard the voice, he fell down and trembled, and his strength was gone.^
footnote:[Dan. 10:7]
And Paul, when he heard the voice, he fell down, and trembled:^
footnote:[Acts 9:6]
and Habakkuk, when he heard the voice, his lips quivered, his belly shook,
rottenness entered into his bones, that he might rest in the day of trouble.^
footnote:[Hab. 3:16]
And David when he heard the voice of God in the holy temple,
and his prayers came before him, the earth shook, and David his flesh trembled.^
footnote:[Ps. 119:120]
And work out your salvation with fear and trembling.
Now these workings are strange to them, where the strong man keeps the house,
and who are in the earth; but who are rising up out of the earth,
witness the power of the earth to be shaken; and who are raised up out of the earth,
witness these things, and have a cloud of witnesses to witness them,^
footnote:[Heb. 12:1]
passing through the same door,^
footnote:[John 10:1-2]
to the same rest; and so we witness the scriptures, and the power of Christ,
and them to be fulfilled, and fulfilling; praises,
praises be unto the Lord God Almighty forever.
We witness the happy day of the Lord is come, the good and happy day,
and glad tidings to souls, the day of Christ;^
footnote:[Luke 2:10-11; 19:9]
praises, praises, be to him forever.
All ye children of the Lord, praise the Lord forever,
sing praises unto the Lord forevermore.
This is the day of salvation, and the everlasting gospel,^
footnote:[1 John 1:7]
glad tidings are come into our souls, free pardon of sin by Jesus Christ,
who is come to take away sin, and to destroy the works of the devil;
thus do we witness the scriptures fulfilled by God alone,
therefore deny all the ministers of the letter.^
footnote:[1 Cor. 3:6]
