== To the High and Lofty Ones.

Hear the Lord God, and take heed of pride; woe unto you that are given to vanity,
you grieve the spirit of the Lord God in you, you lose seriousness,
you lose moderation in your apparel, in your diet; you lose temperance,
you are not temperate in your apparel, nor in your diet.
Bow to the Lord, you evil-doers; what a bowing and bending make you one to another;
bow to the Lord, give him the glory, give him the honour, ye who are offended,
that you have not the earthly honour.
Earthly man, earthly Adam!
Not the spiritual man, the Lord from heaven heavenly, not the spiritual man,
the second Adam.
O how do you go in your apparel, that you can scarce tell how to pass the streets!
O the glory of the world hath swallowed you up many of you!
O! you have entered into the great temptation.
What would the devil have given Christ to have bowed down to him?
Have you not the lusts of the flesh?
Have you not the pride of life?
And yet profess scriptures and bow down to him who is out of the truth:
have you not your hearts`' desire in those things?
Are you not dressed so in your apparel, that you can scarce tell how to walk the streets,
in gold, silver, jewels.
Old men, have you lost gravity?
Young men, have you forgotten sincerity?
And young women forsaken modesty, following vanity?
O what a painting of yourselves you make, young and old people?
O the spirit is vexed where vanity is!
God will not always strive with man.
O how have you forgotten the Lord, and given yourselves up to your hearts`' lusts!
Consider all people the days you spend, and have spent in vanity, in wantonness,
in fooleries and toys, in superfluities, in haughtiness, in sports,
in pleasures and games.
Doth not something in you all prick you and check you for your unconverted state,
for your conversation in the earth, and for delighting in all things in the earth,
setting your hearts in vanity?
O old men, how can you but see and consider,
is the fear of God quite gone out of your hearts?
O who can but speak, who can hold his tongue?
O how is the spirit grieved and vexed with your vanity and abominations?
O how is the just trodden under feet?
O how is every one carried away with vanity and vexation of spirit, and covered with it?
How do men reel in their folly and madness, that they cannot tell how to go,
nor what to wear, nor what to eat, nor what to drink, nor what to put on?
Is not this the fashion of the heathen, and not like christians?
Unsettled minds, that run into every fashion, that invent strange and new fashions!
Repent, repent, lest God`'s judgments come upon you, and sweep you away at unawares.
O how doth your inordinate affections appear!
You are excessive in apparel, you are excessive in superfluity and diet.

O what good doth your preaching and teaching do you?
How doth it profit you at all, while you are so given up to vanity,
as though you had never heard talk of God, talk of religion, talk of christians,
prophets and apostles! read their declarations, and see what they declared against.
The rod of God must be fed withal, ye lofty and full, ye haughty and high-minded;
O how do you eat and drink, and then rise up to play!
Is not this your practice ye full ones, and fat ones?
Do you call this recreation, ye idle ones, like the old world?
As Sodom and Gomorrah in fulness of bread and idleness, who turned against Noah and Lot,
the preachers of righteousness, so it is at this day,
and so it was in the days of the prophets, and in the days of the apostles;
these were spots in their feasts, that were beginning before the apostles`' decease,
to eat and to drink, and rise up to play, admiring men`'s persons because of advantage,
of whose root and offspring you are,
that make yourselves merry over the just in the particular, and then in the general,
and so live wantonly upon the earth, and in pleasure, and nourish your hearts,
you are of the flock that kills the just root and offspring;
for the people sat down to eat and drink, and rose up to play,
with whom God was not well pleased, of whom God slew thousands at once;
there is your example, and there is your stock, and there are your old fathers:
though you profess the saints`' words, if you read the scriptures,
you may see of whose stock you are, and of whose generation, and whose path you go in;
therefore if you love a long life, your souls`' happiness and good, come out of vanity,
come to seriousness and gravity, come to the Lord, come off all the barren mountains,
all people come off the barren mountains, that you may have refreshment of the Lord God;
come off vanity that you may be led with the spirit, and not grieve it, and vex it,
but that you may have unity in the spirit, with the Father of spirits,
and unity one with another; your vanities grieve the spirit,
whereby you are a burden to the creation;
it is a marvel how you can walk up and down the streets,
and not be checked and reproved in your own particulars, for your vanity,
and not be ashamed.
Is the witness stifled in you?
Hath the custom of the sin taken away the sense, are you past feeling?
Know you not that you must come to the dust you high, lofty, wanton, giddy ones?
O how are you daubed with silver lace, and your jewels, and your spots of your faces,
and your feathers, and your wearing of gold,
and through the abundance of your vanity and of your superfluity!
Ambition and pride, loftiness and haughtiness stops the ear from hearing the Lord,
his decree and sentence against you, and how he beholds you afar off,
and stops up the eye with which you should see yourselves,
and stops up your ear from hearing the poor, the blind and the lame,
that lay up and down your streets; so that he that regards not the poor,
regards not his Maker; and turning his ear from the poor, turns his ear from his Maker.

So all come to soberness and modesty, and shamefacedness,
and be ashamed of all your pride and vanity, and delight in the Lord your Creator,
more than the creature, the giver of all good, and take pleasure in him alone,
and in his judgments; if not, woe and wrath, and his plagues will come upon you.
O what a pudder is here, what a bowing and bending is here?
Bow to the Lord, give glory to Him, give honour to Him, fear Him, dread the Lord,
the Creator of all, of heaven and earth, and of power:
he will throw down all deceit with his power.
Honour you not the creature more than the Creator?
Bow you not more to the creature than the Creator?
Bow you not oftener with hat and knee to the creature, than to the Creator?
Give you not more honour and worship, and respect to the creature than to the Creator?
O shameless men and women!
God will abase your pride, and bring your honour and glory to the dust,
who beholds your vanity.
O how have you your lackies and lads to carry your trains after you.
O you scorners, give over scorning, and O ye fools learn to be wise,
all ye that are given to vanity, for shall they that are given to vanity prosper?
Hearken to the spirit of God in you, that checks you for vanity,
that you may come into the fear of God, whereby you may learn wisdom,
and may not destroy the creation, and that you may come to know God,
whereby you may come to feel eternal life, that which checks you for your sins,
and your vanity, and for your going after it, whereby you may come to understanding,
and know what is vanity, and vexeth the spirit, and what doth not vex the spirit,
that is pleasing to God, that you may learn with that which gives you understanding;
while you have time prize it, lest your time be past; this is the day of your visitation,
love the Lord God above all his creatures, and delight not in vanity,
that to the Lord God in your generation, you may be a blessing,
for all the destroyers of the creation are accursed; for woe, and misery,
and plagues are to come upon all the world,

Bow you not more and oftener with the hat and the knee to one another,
than you do unto the Lord?
People cannot tell how to please one another in their bowing with the hat,
in curtseying one to another, but they will he ready to think,
that I bowed with my hat oftener to him than he did to me,
and I curtseyed more to her than she did to me;
and thus they are offended one at another; and such a one hath more ribbons,
and gold and silver on him than I have, and spots on their faces,
and he powders his hair and curls it;
and so when any is in another fashion contrary to them, then they envy one another,
which is among such that have lost gravity.
And are ye not here as the transgressing children of Israel, mincing,
tinkling in round attire, amongst whom must come to the stink?
Isaiah 3. And are ye not out of the apostle`'s doctrine, who saith,
"`Not wearing of gold, nor broidered attire, nor plaiting of hair;
but the adorning which, is the hidden man of the heart.`"

[.asterism]
'''

=== To all the Rulers of the Earth.

Oh all ye rulers of the earth, from the foundation of the world, to this day,
who have been in the transgression of the law of God, of the life of God,
out of the fear of God, such in all ages have turned the sword against the just,
that have transgressed the just principle of God in themselves,
and grafted themselves into the wicked root; all such,
from the foundation of the world to this day,
have turned the sword backward like blind men;
so hit their friends that come with love to their souls;
and strike at them instead of their enemies; ye persecute the just, ye kill the saints,
the prophets, and the Son,
and persecute them that be in the life of the prophets and apostles;
these have always strengthened the hands of evildoers;
but they that have reproved in your gates, in your streets, have been your prey;
you have banished, you have whipped, you have prisoned, ye have persecuted,
you have burned my flesh, saith the Lord; ye have branded, ye have marked,
ye have fire and faggots, and houses of correction, and inquisitions,
and sending up and down warrants, mittimusses, banishing the servants of the Lord,
persecuting them because they cannot bow with the hat, give you the earthly honour,
not honouring the courts, (as it was in the days of the martyrs,
for the testifying of the truth,) and say thou to one,
shewing that you are of the earthly old Adam, drove from God into the earth,
not of the second Adam, the Lord from heaven, Christ Jesus,
who receives not honour of men.
None honours the Father and the Son, but who hath received honour from God,
and that which is of God.

Now men in haste and passion, in rage, and fury, and bitterness, and prejudice,
these are unseasoned men for to be justices, unseasoned men to have honour,
for humility goes before the honour: pride and high-mindedness, and fillings up,
that looks for respect of persons, more than for truth, justice and equity;
for if men keep down, low and humble, all doing justly,
they are honoured in the hearts of all people, with the just principle of God,
that all people honours the higher power, that honour justice,
and exalt the humility which goes before the honour,
for God brings down the mighty from his seat, and abaseth the proud,
and beholds him afar off, and brings down the lofty; and where bitterness, and prejudice,
and burnings are in the breasts of people, they will side for parties,
and be for their own ends; and what work have men with these innocent people,
which ye in scorn call Quakers?
Prisoning, hauling out of steeple-houses, sending them as vagabonds from place to place,
those that be able people outwardly, whipping of them;
and because they cannot bow with their hat to you,
what work are your judges making with them; and fining of them, prisoning them,
because they cannot swear; and prisoning them, and fining them,
because they cannot pay the priest tithes; preparing war against them,
because they cannot put into their mouths, such as Micah cried against;
if people were not hardened, they would look into these things,
and consider these things, and see all along from the foundation of the world,
how they out of the fear of God persecute, though they have got the form of words,
but out of the life of them:
these persecute men because they cannot put into the priest`'s mouth,
and such as hold up such priests as are made by men, and held up in men`'s wills,
and not by the will of God,
and persecute them because they cannot break Christ`'s command, but keep it, which saith,
"`Swear not all;`" and prison and persecute such as cannot receive honour from men,
nor give honour to men which is from below;
can the children of God give honour to that which God will abase and throw down?

All that seek or would be honoured in the hearts of all people,
must answer the principle of God in all people, with justice, with equity, with truth,
and they must have patience, and humbleness, and mercy, for ye have whipped,
ye have burned, ye have persecuted, and these things lie upon you:
you that have acted these things are out of the fear of God;
therefore now you that fear God, whose hands are clear from blood,
and from persecuting the innocent; and who have done justly to the wicked,
the Lord God will be your reward, you shall have a crown that is immortal,
that have kept yourselves from persecuting the innocent,
and put a difference between the precious and the vile;
and to them that do well have been a praise;
and them that have reproved sin in your gates, have not been a prey,
but ye have protected them, you have nourished them;
and the evil-doer hath not been strengthened;
happy are ye who are honoured in the hearts of all people,
ye are in their hearts who do justly, love truth, are merciful, and humble,
such God exalts and honours in the hearts of all his people, with that of himself,
such know the proud and lofty cannot honour them;
they will not receive the honour from them, which is but a compliment, and from below,
and is earthly for that which honours a magistrate, that doth justice and equity,
and honours the power, it is from the principle of God in him, that keeps him humble,
and low, which brings him from under the occasion of the law,
which is a praise to them that do well, and a terror to the evil-doers.

A lover of all your souls, and your eternal good, and a friend to the creation,
and the truth, and them that be in the life of God.

[.signed-section-signature]
G+++.+++ F.
