[#ch13, short="An Epistle to All People on Earth"]
== An Epistle / To All People on Earth;

[.heading-continuation-blurb]
Shewing the Ignorance of all the World, both Professors and Teachers,
of the Birth that must be Silent, and of the Birth that is to Speak,
which declares God; and the Difference betwixt Silence and Speaking,
that they may come to an Understanding of themselves,
and may know that Christ Jesus, the Light of the World, is their Teacher,
or their Condemnation:
Also shewing that it was the Practice of many to wait in Silence upon God,
to hear his Word, and know his Voice.--By G. F.

You are not come to know the time to keep silence before the time to speak, Ecc. 3:7.
but are such as Jeremiah speaks of, Jer. 23.
which use your tongues, and say the Lord saith, when the Lord never spoke to you,
so you have not known the keeping of silence before the speaking,
you are such as say your tongues are your own, you ought to speak, as David speaks of,
Psal. 12. so hear what Isaiah saith, sit down in silence, get thee into darkness,
O daughter of the Chaldeans, thou shalt no more be called the lady of kingdoms,
+++[+++mark here,]
the lady of kingdoms must come to silence, Isa. 41.
verse 4. and you know not to sit in silence in the fenced cities, Jer. 28.
but the Lord will put you to silence,
and you must witness silence before you come to speak.
Kir of Moab was brought to silence, because he was in the night.
Isa. 15. And all of you that be of Moab`'s stock must keep silence,
though you had a time to speak,
and used your tongues before the time of silence was known,
and the tongue of the dumb to sing,
and the songs of the temple shall be turned into howling, saith the Lord,
and there shall remain dead bodies in every place,
and they shall cast them forth with silence, Amos 1. he that hath an ear to hear,
let him hear: such as know the seven seals, shall know the silence in heaven.
And when I saw the seven seals, there was silence for half an hour in heaven;
he that can, read this and understand, Rev. 8:1. and the apostle said,
"`Let the woman learn in silence with all subjection, for I suffer not a woman to speak,
nor to usurp authority over the man, but to be in silence,`" as saith the law, 1 Tim. 2:11-12.
yet saith the Lord, "`I will pour out my spirit upon all flesh,
and my sons and my daughters shall prophesy,`" Joel 2. Acts 2.
and they that are led by the spirit are not under the law;
and be swift to hear and slow to speak, saith the apostle;
and he speaks of the many unruly and vain talkers,
and such teachers as be out of the faith, and had gotten the form of godliness,
which were to be turned away from, which crept in in those days, which were to be silent;
so here is a time to speak, and a time to keep silence; "`Be silent,
oh all flesh before the Lord.`"
Zach.
2:13.

Now here is a birth born of the flesh, and this birth born of the flesh,
will persecute that birth born of the spirit;
now come all to know the birth silent which is born after the flesh,
which will persecute, and see ye priests if it be flesh that speaks in you or no;
you teachers and professors which say you have not the spirit of God,
that gave forth the scriptures, then you have not that birth that they had,
so then you have the other birth, the flesh, so you are in the time to keep silence,
as Solomon speaks of, else you are of them that Jeremy speaks of, that use your tongues,
though the Lord never spoke to you,
and you are they that are swifter to speak than to hear,
contrary to the apostles`' doctrine, which are the lying prophets,
that have not the spirit the apostles were in, that the scriptures were given forth from,
therefore you have not that birth and spirit that speaks forth scripture;
some were come to the time that they might speak,
so holy men of God spoke forth the scriptures, as they were moved by the Holy Ghost,
and they came to the watching and praying,
but the "`sacrifices of the wicked are abomination to the Lord,
and all that watch for iniquity shall be cut off,`" Isa. 29.
and the apostles were to wait, and being assembled,
they were not to depart from Jerusalem, but to wait for the promise of the Father;
and they were to receive the power after the Holy Ghost was come,
that they might be witnesses unto Christ.

Now here was a time of waiting, here is a time of receiving, here is a time of speaking:
the Holy Ghost fell upon them, that they spoke the wonderful things of God, Acts 2:2-4.
and these were they that were gathered together with one accord.
So where two or three are gathered together in the name of Christ,
he is there in the midst of them;
and Christ commanded the assemblies that were met together,
to wait for the Holy Ghost and the power, not to depart,
but to wait for the promise of the Father at Jerusalem.
So the saints were not to forsake the assembling of themselves together,
but to exhort one another, inasmuch as they saw the day approaching.
Heb. 10. And what if you should see such an assembly as was in the days of Ezra?
They trembled at the word of the God of Israel,
because of the transgression of those that had been carried away,
and sat astonished until the evening sacrifice.
This would be a wonder amongst you.
Ezra 9.

And those that come into a true waiting, the true assembling,
they come to the true supplication and praying: what if you did see some sit down,
as Job did, seven days, and spoke not a word to one another;
this would fret the contrary mind, this would make you to wonder, Job 2. But I say,
wait on the Lord, and let them be ashamed that transgress;
wait on the Lord and be of good courage, and he will strengthen thy heart;
wait thou on the Lord, Ps. 25. and Ps. 27. and rest on the Lord,
and wait patiently for him.
Fret not thyself because of him that prospereth in his way,
because of the man who bringeth wicked devices to pass.
Ps. 37. The Lord will wipe away all tears from all faces, and rebuke the people,
the Lord hath spoken it.
It shall be said in that day, this is the Lord, lo we have waited for him,
we will be glad in his salvation.
Isa. 25. The Lord is good to him that waiteth for him, to the soul that seeketh him.
And it is good for a man that he should both hope,
and quietly wait for the salvation of the Lord.
It is good for a man to bear the yoke in his youth; he sitteth alone and keepeth silence,
because he hath borne it upon him.
Now that which hath acted iniquity must come into the silence,
before the just doth come to reign and have dominion. Lam. 3:28.
For the earnest expectation of the creature
waiteth for the manifestation of the Son of God,
and who groan within themelves for the adoption, to wit, the redemption of the body;
and are come to that condition, that they do not know what they should pray for,
but the spirit maketh intercession with sighs and groans that cannot be uttered;
and so come to feel him that searcheth the heart, and knoweth what is the mind,
of the spirit,
because he maketh intercession for the saints according to the will of God.
Rom. 8. And Micah cried against the diviners and teachers for money,
and he said he would wait upon the Lord, and he would look unto the God of his salvation,
and he would hear him.

Be patient, my brethren, waiting for the coming of the Lord Jesus Christ.
The husbandman waiteth for the precious seed of the earth, he hath long patience for it,
until he receive the early and latter rain:
so be ye also patiently established in your hearts,
for the coming of our Lord draweth nigh. Jam. 5.
The end of all things is at hand, be sober and watch unto prayer. 1 Pet. 4.
The apostles were in labouring, and watching, and fasting. 2 Cor. 6.
Now read these three places.
And blessed are they who when the Lord comes shall be found watching;
verily he shall make them to gird themselves and sit down to eat,
and will come and serve them.
So blessed is the man that heareth me, and watcheth daily at my gate,
watching at the posts of my door. Prov. 8.
And Christ said to his disciples; watch therefore,
for ye know not what hour the Lord doth come; and watch therefore,
for ye know not the day nor the hour, in which the Son of man cometh.
Matt. 25. This spoke Christ concerning the foolish virgins and the wise,
such as had oil in their lamps, and such as had not:
therefore look to yourselves you that are fain to go and buy.
And what think you of them that Christ bids tarry here and watch with him,
and Christ comes and finds them asleep and saith, could ye not watch with me one hour?
Watch and pray, lest ye enter into temptation.
"`Watch ye therefore, saith Christ, for ye know not when the lord of the house cometh,
lest, when he comes, he finds you asleep: and what I say unto one, I say unto all, watch.
Mark 13.

Now mind where the watching is, and the praying is, they are in the light,
in that which silences all flesh, for words in that leads from the watch.
Therefore come to know the watch set before every one of your mouths,
and so to keep that silenced that must be stopped; and so what Christ saith to one,
he saith unto all, watch.
Now all being upon the watch, all are waiting;
and here all men shall come to know the armour against that which will lead us aside.
Timothy was to watch in all things, and the saints were to watch and be sober unto prayer.
1 Pet. 4:7; 1 Thes.
1+++.+++ Let us not sleep as do others, but let us watch and be sober; for they that sleep,
sleep in the night, and they that are drunk, are drunk in the night;
but let us who be of the day be sober, putting on the breast-plate of faith and love,
and for an helmet the hope of salvation; for God hath not appointed us for wrath,
but to obtain salvation by our Lord.
The saints were to watch, yea and to stand fast in the faith,
and watch in the same with thanksgiving, Col. 2:4.
continuing in praying and watching with thanksgiving.
Remember therefore how thou hast heard and received, and hold fast and repent:
if therefore thou shalt not watch, I will come on thee as a thief,
thou shalt not know what hour I will come upon thee, Rev. 3:3. +++[+++mark,]
who are off from the watch, Christ comes on them so;
and they that are out from the watch, are out of the light that comes from Christ.
Watch therefore with all perseverance and supplication for all saints.
The apostles bid the saints watch, Acts 20. for wolves would come in amongst them;
(but he had coveted no man`'s silver,
nor no man`'s apparel) but such would enter in after the days of the apostles.
And such as feared the Lord met often together, and spoke one to another,
and such the Lord spares in the day he makes up his jewels,
as a man spareth his only son that serveth him.
And saith the apostle, build up yourselves in the most holy faith,
praying in the Holy Ghost.
+++[+++Mark,]
The building up is in that which is holy, in the holy faith,
and the praying in the Holy Ghost.
Now he speaks of some that speak high swelling words,
but themselves living in the hypocrisy, and were gone into the ways of Cain and Balaam,
and are they that must know a time of silence; for such build not among the saints,
for they are Babylon`'s stones.
So all these high speakers which speak the words of the
scriptures out of the Holy Ghost that gave them forth,
they be out of that in which the saints pray,
and so they that pray out of that are an abomination, they are to be silent;
and they that be out of the faith,
they be out of that the saints build up one another in, the holy faith.
That which is holy gives victory; in that the saints build up, in that they fear God,
so in the faith, in the unity; for it gives victory over the enemy and the impure;
for it purifies the heart, and without it man cannot please God,
neither can they build up in the unity, nor in the faith that gives the victory,
in which is the unity, which is the gift of God by which they please him.
That praying is in the Holy Ghost; the scripture was given forth from the Holy Ghost:
Stephen, a man full of the Holy Ghost, in his examination, when he spoke to the council,
he told them that they resisted the Holy Ghost, as their fathers did,
and yet they professed the scriptures, but resisted the Holy Ghost.
Now all those that have the scriptures, and resist the Holy Ghost,
they resist that which gave forth the scriptures,
and their gathering and their praying are abomination,
and their gatherings are to be scattered.

And therefore all friends, that are come to witness the Holy Ghost and faith,
in which the true praying and building is, which gives victory over the world,
which is the gift of God, in which you please God, keep your meetings,
and being met together, as you are moved, speak;
for they spoke as they were moved by the holy Ghost,
and as the spirit gave them utterance: and they prayed with the spirit,
and it helped their infirmities, for they could not tell what to pray for as they ought:
but be that searcheth the heart, knoweth the mind of the spirit that teacheth to pray.
And here comes to be known the birth born of the spirit,
which God the Father of spirits hears, which is not of that birth born after the flesh,
but is with that persecuted.

Now you may see the just man Simeon, Luke 2, who waited for the consolation of Israel,
it was revealed to him, he came to see it: and the people gladly received Christ,
for they waited for him, Luke 8:40. now +++[+++mark,]
that which is not silenced doth not wait upon Jesus but persecutes that birth:
but the birth is brought forth, and the light springs, and that is known and seen,
that must speak, and that is known that must keep silence.
Praises arise to the Lord God forever, who is exalting the birth born of the spirit,
which is feeding upon the bread of life,
which is nourished with the life in the bosom of the Lord God of life,
and the elder is become servant to the younger.
The arm of God reigns above the elder in his kingdom and throne,
and God hath fulfilled his promise, and is fulfilling it; and the time to speak is known,
and the time to keep silence is known.
Now they that are not come to distinguish each birth and each mouth,
they do not know the time of silence, and the time of speaking:
such are judged for judging the things of God, and are not fit to judge,
such as know the peace of God that passeth the understanding,
and that which is unspeakable, they know silence in the life and in the spirit of God.
This is to be read amongst Friends, and from them to pass abroad through the world,

That which brings to look into the world, into time, captivates.
Where is the ground of the spirit of strife and mastery,
and the crown that fades and vanishes away?
As the life ariseth that stands in God, which gives to feel the crown which is immortal;
therefore that which brings you to the beginning, which lets you see before pen,
ink or paper, or writing was, in that live,
that will let you see the fulfilling of that which was written.

And you that think yourselves above the world, whose wine is mingled with water,
who wear the linen and woollen garment, who through pride and ease,
and false joys lose the sincerity, whereby an earthen veil covers you,
through the lust lived in,
a veil of flesh is spread over the whorish and adulterish woman that hath been among you,
which brings forth many children,
which strives to lay the heritage of the Lord waste this is but as briars
and thorns that set themselves in battle against the Lord,
who is a consuming fire, the whole world, which are now stumbling at the light,
who have been checked with it and convinced, but now are turned from it;
so there stands all the world, giving names one to another, throwing dirt one to another,
where the enmity is, and fighting one with another with that weapon that is carnal,
and warring one against another, and they that do so, mock one another:
and here is the generation of mockers, out of the life, and out of the light,
and every one striving for mastery and lordship and authority one over another:
but it shall not be so with you who are children of light, disciples of Christ,
not of this world, whose kingdom is not of the world, and who come out of strife,
come into peace.
Therefore all people dwell in that which leads into peace, and out of confusion,
for God is not the author of that, but such be out of his life,
that hold the truth in unrighteousness.

Come out of the bustlings you that are bustling and in strife one against another,
whose spirits are not quieted, but are fighting with words,
whose hearts burn against each other with a mad blind zeal,
who are up in your wantonness, lightness and pleasures,
who set the whole course of nature on fire, among whom the way of peace,
and that which is perfect is not known; among whom you have the words of Christ,
the apostles and prophets, and the scriptures of truth,
who hold it in the unrighteousness, where all spirits are disquieted,
and the elements come to burn like fire,
where is all the masteries and seeking for earthly crowns, and exalting among the people,
and gathering parties out of people;
wherein stand the several ways and distances of people one from another,
and opinions and sects, wherein all come to throw dirt one at another,
wherein is the weariness, groans, burdens and travels, and persecuting the just,
quenching the spirit, despising prophesying,
destroying the meek of the earth and the helpless,
and rooting out innocency and simplicity, and destroying it; where enter heats and fires,
storms and the many waters; and the sea and the earth, the dragon and the beast,
and the false prophets, which was the wonder in heaven, cast down into the earth,
which make war against the saints and the Lamb,
but over all the Lamb hath got the victory;, that which drunk the cup of fornication,
and she that gives the cup of fornication,
and is that which draws people from the life within them.
So there are all the unquiet spirits in the world, and the restless and the wearied;
for there is none upon the earth that come to have their spirits quieted,
but who come to the light, that Christ Jesus hath enlightened them withal,
and so comes every spirit here to have a particular
satisfaction and quietness in his own mind,
and here comes the weary to have rest in Christ, who hath enlightened them;
and there is no one but holds the truth in unrighteousness,
until he comes to that of God manifest in him; and so that of God manifested in him,
leads his mind up to God,
he comes to the quiet and peaceable life and comes to retain God in his knowledge,
and his spirit is quieted, and he comes to hold the truth in righteousness,
and his mind is not reprobated; and such shall find mercy of God,
when their minds are guided up unto God,
and their spirits and minds are quieted in silent waiting upon God,
and in one half hour have more peace and satisfaction,
than they have had from all other teachers of the world all their life time;
and here they come to feel that which quiets their minds to God,
and they find and feel the way of peace,
and come to grow up in that life the scriptures were given forth from,
and the life the saints lived in,
and spirit which guided their minds up to God the Father of spirits,
whereby every particular comes to a particular satisfaction;
and all this bustling and teaching in the world for earthly things,
men and people shall turn from it; for that is in the earth,
it is that which went in Cora`'s way, and Cain`'s way, and Balaam`'s way,
which is now standing in the way, which the apostles saw coming in before their decease.

So as you all come to be guided with that of God in you,
and to feel that of God in you to guide your minds up to God,
you shall come to satisfaction; it leads you, up out of the earth to that within,
so from all those without,
and here comes the glory of the Lord God to be revealed in you:
and though you may profess all the scriptures of truth,
yet if every particular of you do not come to feel that of God,
which God hath manifested in you, and showed to you to guide your minds to God,
you cannot know any of the scriptures; for that opens the words to every particular,
and gives to every particular, a particular satisfaction,
by which every one comes to pray in the spirit, and sing in the spirit,
from which glory is given to God.
Now there is no people upon the earth come from the first Adam`'s state in the earth,
drove from God in sin, and death, and unrighteousness, to the second Adam`'s state,
but who come to the light that enlighteneth every one that cometh into the world:
they that will not come to the second Adam from the first Adam,
they will not come to the Lord from heaven who is the way to the Father.
So they that are not come to the light which doth
enlighten every one that cometh into the world,
they are in the first state drove from God, from his righteousness, from his wisdom,
from the truth, the light, the life, for Christ the light,
which doth enlighten every man that cometh into the world, is the way to the Father,
the truth, the life, the light, God`'s wisdom, God`'s righteousness, the hope of glory,
and the power of God, the redemption, the teacher and the saviour,
who doth enlighten every man that cometh into the world, who is the way to the Father,
which all the world despiseth.
And their teaching of people is far from the light which
doth enlighten every man that cometh into the world,
for they do not own that, being out of God`'s wisdom in the devilish,
that is both earthly and sensual.
So this is the state drove from God; God`'s wisdom brings to God;
and all you upon the earth that deny the light that
enlighteneth every man that cometh into the world,
ye are yet in the transgression in the first Adam, ye are in your own righteousness;
for any righteousness, that is not in the light, is your own,
for Christ the light is God`'s righteousness.
So every one that cometh into the world being enlightened, which hears not the light,
the light which doth enlighten him, he hears not the prophet, which Moses prophesied of;
so the light condemns him, and he is to be cut off from among the people.
And so all the world are from Christ the light, from that of God in them;
some in the presumption, some in the envy, and that eats them out and slays them;
some in the false joy of presumption mount up to heaven,
and fall down to the earth again.
There are all the minds unestablished in the world, they go from that of God in them,
which doth not change, the truth doth not change, which comprehends the world,
fathoms the world, the light, which doth enlighten every man that cometh into the world,
though he hates it, it is his condemnation.

And you teachers that profess yourselves so to be;
give over setting people at enmity one against another,
give over your railing and bawling, and backbiting of people in the pulpits,
for that is not to preach the word of God, what you have sown, that you must reap,
and gather into your barns and treasury; the Lord God sees what stock you are of,
who is come to judgment, to judge the great whore, which is adulterated from him,
and his judgment is now set, and she hath sat upon many waters, and rivers, and tongues,
and people, and languages; and all people come to know Christ your teacher, who saith,
learn of me, I am the way to the Father;
so the light that doth enlighten every one that cometh into the world,
is the new and living way; so you that are come to the light you are enlightened withal,
you are come to that which is new, and living, now as ever it was;
therefore all people come to know the light in you, shining in your hearts,
to give you the knowledge of God, in the face of Jesus Christ;
and all people come to know the heavenly treasure in the earthly vessels; which none do,
but they that come to the light, which Christ hath enlightened them withal;
and all people come to know the second Adam, the Lord from heaven, above the first Adam,
who doth enlighten every man that cometh into the world; none knows him,
but who owns the light, which brings them out of the first Adam`'s state,
out of the earthly into the heavenly;
and all people come to know God`'s word in your hearts, there to obey it,
and there mind to do it, this is the word of faith preached;
the ministers of the letter may keep you reading the letter without you,
and telling you of the letter without you, but they cannot endure,
(who deny the light) talking of the word within them in the heart;
for feeling God`'s word in the heart to obey it,
you come to know that which the prophets and apostles witnessed,
the word of life which became flesh, which is Christ in us,
know him in you all upon the earth, then you will not be reprobates,
for if Christ be in you, the body is dead because of sin,
and you are alive to righteousness;
and all people come to know the new covenant that God hath prophesied of by his prophets,
and Moses wrote of, and the apostles were witnesses and enjoyers of,
the everlasting covenant; and knowing the end of the first covenant,
know this covenant which is everlasting,
the new covenant with God and his people forever: his law is in their hearts,
that you need not say one to another, know the Lord,
that you may come to enjoy the thing the scripture speaks of;
and all people know the mind of Christ (which none can but who come to the light,
he hath enlightened them withal,) that you may come to be of one mind, heart and soul;
and all people wait to receive the spirit of Christ Jesus, which if you have not,
you are none of his; and all people come to live in the power of godliness;
many may have the form, but deny the power, and be against it, in them that declare it;
and so you will come to live in the gospel.

And all people come to the light which every one of you is enlightened withal,
that is come into the world, that you may come to the second Adam, from the first Adam;
that you may have your sins and transgressions blotted out;
and all people come to know the wisdom which is from above,
which is above all the earthly, sensual, and devilish, which is below; none owns this,
but who owns the light, which enlightens every man that cometh into the world;
and all people come to know Christ in you the hope of glory, which hope of glory,
Christ destroys the hope of the hypocrite, which hope purifies, even as he is pure.
Now come to know this hope, Christ in you, distinguished from your own hope,
which hope is a mystery;
and all people come to know the anointing that abideth in you to teach you;
and as you continue in that, which abideth in you,
you come to know the Father and the Son,
and none come to know the anointing abiding in them,
but who come to know the light Christ hath enlightened them withal;
nor none abide with the Son,
but who continue in the light Christ hath enlightened them withal:
therefore all come to know the anointing in you,
that you might come to know that which teacheth you to continue with the Son,
where you need no man to teach you;
for God is coming to take his people off from the teachings of men,
and to teach his people himself, and the Lord`'s children shall be taught of him;
and they shall cease from man, whose breath is in his nostrils,
and come to know their strength renewed, and come to know the prophet`'s life,
and the spirit he was guided withal; and all people come from the world`'s churches,
and come to know the church that is in God, the Father of our Lord Jesus Christ,
which is the pillar and ground of truth, where there is neither spot nor blemish,
nor any such thing, out of all strife and contention of this world,
and come to know the power of that world, where there is no end; and oh people!
Be not surfeited with the cares of this life;
neither overcharge your hearts with the deceitfulness of riches,
but mind the power of an endless life;
and cease from all these teachers which teach for earthly things,
who are such as keep you in the earth, and in sin,
and teach people must be in sin while they be upon the earth,
and so make the covenant of God of none effect, ministers of unrighteousness,
and still in their transgressions, and make Christ`'s dying in vain,
and the one offering of no value,
which hath perfected forever all them that are sanctified, and his blood of none effect,
which cleanseth from all sin; but the ministry of righteousness is manifested,
which lets you see the effect of the blood of Jesus, and of the everlasting offering,
which you made of none effect; and so they turn your minds to the light,
Christ Jesus hath enlightened you withal, that with it you might see yourselves,
and see Christ when he comes, and with it be justified from all sin;
and come into the unity one with another, and have the love of God,
and peace of God shed in your hearts,
and come out of strife one with another about words and forms of things,
and jangling about scriptures; but come to that of God manifest in you,
that you may know the life that gave forth the scriptures; the synagogue, temple,
and priest that takes tithes are to be denied by all such that witness Christ come,
and the second priesthood, and the Jews`' sabbath also;
for all that uphold these things are nominal christians that teach for filthy lucre,
and seek for the fleece, and divine for money, and bear rule by their means,
that stand praying in the synagogues, having the chiefest place in the assembly,
and are called of men, masters; for all these the prophets and apostles cried against,
and they that hold them up are to be denied.
All people upon earth that ever come to the knowledge of the true God,
must own the light of Christ Jesus within them, which light is but one in all men,
and brings into oneness all that believe in it.

All the world`'s teachers, people, and professors, you are far from silence,
and the silent meeting together, and waiting upon the Lord in silence,
you have too much flesh in you, which speaks, and so are too full of words,
which are not your own, and not owned of others, for you are out of the life of them,
who know a silence of the flesh, and a waiting upon the Lord in silence,
to hear his still voice, and to hear his voice behind them, saying, this is the way,
walk in it, and to have the mind stayed upon God, and to be guided by God,
and to be led with, the spirit of God into all truth,
when they do not speak words outwardly: first, the spirit leading,
then words from the spirit, and thus the spirit is not quenched in son nor daughter,
in handmaid, nor servant.
The false teachers, false prophets, and false apostles used their tongues,
they got the form of godliness, but denied the power,
for which they are to be turned away from, and who said, the Lord saith it,
when the Lord never spoke to them, neither stood in his council; had they,
they should have stood silent, and waited upon God;
but they that use their tongues and say, the Lord saith it,
when the Lord never spoke to them, they were not silent,
which the Lord said should be silent, and likewise them that went in Cain`'s way,
and Core`'s way, and Balaam`'s; that spoke the high thing in hypocrisy,
and likewise promise liberty, while they themselves were servants to corruption,
and these were against them that waited upon God, and these should be silent;
therefore now in this age, they that use their tongues and say the Lord saith it,
when the Lord never spoke to them, have the form of godliness, but deny the power,
and speak the high words, but they themselves are in the hypocrisy,
and in Cain`'s and Balaam`'s way, and Core`'s way,
separated from the spirit that gave forth scriptures,
and so from God the Father of spirits, professors and teachers;
such are angry and offended at them, that in silence wait upon God in his council,
and patiently wait upon him, whose hearts pant after God,
when there is never a word spoken, whose souls hunger after righteousness,
when there is never a word spoken; who receive strength and blessing from God,
the living mercy, the sure mercies of David, yea a hearkening diligently,
whose souls come to live, hence is a silent waiting and diligent waiting upon God,
and a silence in heaven, yea and the peace upon the earth,
and the good will towards men witnessed.

Now they that be exalted above their measure of the spirit of God manifest in them,
such glory in the expressions, glory in words, and feed upon them more than life,
and delight in words and methods, and curiosity in speech;
and this is that which is offended at silent waiting upon God,
which looks at high expressions, and is fuller of them than life,
that feeds the birth that must be silent, that is born of the flesh,
so there is the time to be silent.
This is the word of the Lord God to you all that you may
all come to that which God doth manifest within you;
it will let you see the birth that must be silent, and bring you to be silent,
and to wait to receive teaching from God, then what is said,
you may declare from the Lord of Heaven most high:
Cain was the first and Esau and Ishmael was the first birth;
now tell Cain the envious murderer of a silent meeting or waiting upon God,
when he is a vagabond from that of God in him,
and so from God would slay and murder them that are in the life,
and it he will slay and yet sacrifice, to which sacrifice God hath no respect,
who is from God`'s life, and so from God`'s life a vagabond, a murderer,
that hath not a habitation in God,
yet professeth the saints`' words which were declared forth from the life,
who had a habitation in God, here is Cain`'s offspring and generation known,
so he hath not eternal life abiding in him, he envies his brother,
and how can he know a silent waiting upon God in the eternal,
that hath not the eternal life abiding in him.

Consider this, all you envious ones, this is God`'s word to you all;
you are far off silent meeting and waiting upon God, or the love of God that envies not,
or the body that edifies itself in love; do not tell Esau of a silent meeting,
and a silent waiting upon God, that hath despised his birthright,
and after seeks it with tears, where there is no place found for him;
now tell Esau of silence, a silent meeting is a wonder to Esau,
that despiseth his birthright, and would sway the sword, and slay his brother Jacob,
the second birth.

But a silent meeting is not a strange thing to righteous Abel,
nor to the second birth Jacob, for God is the author of their faith;
and Esau the cunning hunter,
the profane person is among the beasts of the field that hath the fat of the earth,
a place for dragons, that bears the sword to destroy the righteous,
tell him of a silent meeting and waiting upon God,
he will hunt till he hath tired himself, that he faints again,
and despiseth his birthright; and likewise wild Ishmael the mocker;
tell these of silent meeting and waiting upon God, nay,
this will boast and mock and scoff at that which brings to wait upon God in silence;
this is that which is to be cast forth; so Esau, Cain, and Ishmael,
you may see your stock, offspring, and root, and you to be branches who be profane,
who be envious, and scoff and mock at them,
who do silently and patiently wait upon God for counsel, for instruction,
who is the giver of all good; so as they are moved by the spirit to pray, to praise,
to give thanks, to speak with the spirit, as it gives utterance, as it reveals things,
and so it leads them, and they receive from the Father of spirits,
and come to be obedient; glory over all to the Lord God the highest of heaven and earth,
that is bringing forth a birth born of himself, that knows the Father,
and declares him which doth keep the other birth silent,
and all who speak a divination of their own heart and brain, and are the filthy dreamers,
false prophets, false teachers, false shepherds, false apostles,
and ministers of unrighteousness, and such as divine for money,
and teach for filthy lucre, and make merchandize of the people,
and seek for their gain from their quarter, and bear rule by their means,
and teach for the fleece, and are called of men masters,
and stand praying in the synagogues, and have the chiefest places in the assembly,
which Christ, the prophets, and apostles cried against, who were out of the spirit,
these now cannot endure silent meeting together and waiting upon God;
these are full of words, and steal them from their neighbours,
these mind earthly things which make merchandize of the people;
and these are transgressors all of them, for they set up what the apostle threw down,
tithes, and temple, and synagogue, and priests before mentioned.
Now these are they that are out of the life, and these are offended at silent meetings,
and waiting upon God in silence, and for doctrine teach their own traditions,
and ordinances, and commands, and neglect the commands of Christ,
telling people of sprinkling infants, and a sacrament, when there is no such scripture,
and these will give to the people David`'s conditions in a metre, his quakings, praying,
roaring, tears and prophecies, and so use their tongues with other words,
when both teachers and people are out of David`'s condition,
and such cannot endure silence; before they will be silent, they will sing a lie:
they are not high-minded, they have no scornful eye, their bones quake and tremble,
they roar all the day long, their bones fail of fatness,
they fast till they may number their bones,
they cry and weep till their eyes are sunk in their head, and roaring on their couch,
when it is not so, and they are singing in a steeple-house; and this doth declare,
that gross darkness hath covered them all, and this is the birth that must be silent,
that speaks of David`'s condition, without David`'s life, of David`'s tremblings,
quakings and prophecies; so with David`'s spirit these are judged.

Now he that hath a psalm, +++[+++mark,]
now he that hath one, let him sing, and sing in the spirit, and with understanding.
And now he that sings in the spirit, and prays in the spirit,
as the spirit gives utterance, he is in that birth,
that silenceth the birth of the flesh.
And this is to all that would learn silent waiting upon God, and silent meeting;
for none ever shall come to God that is upon the earth,
but as they do come to that of God in them,
the light which Christ hath enlightened them withal;
and that is it which must guide every one`'s mind up to God,
and to wait upon God to receive the spirit from God;
and the spirit leads to wait upon God in silence, and to receive from God.
As many of the prophets and holy men of God, they sat often long waiting upon God,
and said, blessed are all they whose minds are stayed upon God,
they should be kept in perfect peace.
And, my soul wait thou upon God; and the meek inherits the blessing;
and ye shall find more strength, virtue, water of life, and the mercy of the Lord,
and the presence of the Lord God, as you are still.

Keep to that of God in you, which will lead you up to God,
when you are still from your own thoughts and imaginations,
and desires and counsels of your own hearts, and motions, and will;
when you stand single from all these, waiting upon the Lord, your strength is renewed;
he that waits upon the Lord, feels his shepherd, and he shall not want:
and that which is of God within every one,
is that which brings them together to wait upon God, which brings them to unity,
which joins their hearts together up to God.
So as this moves, this is not to be quenched, when it moves to pray or speak;
for there is the power of the Lord, this is the arm of the Lord, the dominion,
the victory over death.
And all teachers and people on the earth that have kept people from the
light that doth enlighten every man that cometh into the world,
that which is to be known of God manifest in them,
they are they that shut up the kingdom of heaven from men,
that would neither go in themselves, nor suffer others:
these are they that have taken away the key of knowledge from people,
that neither they nor the people could get into the scriptures,
nor tell what the prophets meant, nor what Christ nor the apostles meant;
but wrangling all about the light, about the door: for the light is the door,
the light is the power, that doth enlighten every man that cometh into the world,
that all through the light might believe, and he that believeth,
is entered into his rest, hath ceased from his own works as God did from his,
and he hath the witness in himself.
And he that is born of God overcometh the world, he doth not make haste:
here he knows a silent meeting and waiting upon God;
and knows that all people upon the earth,
if they come to the light Christ Jesus hath enlightened them withal,
their crowns must be laid down, down at his feet,
and their peace taken away from the earth; and Christ, (God`'s covenant of peace,
of light with God and man,) they must come into;
then all flesh must be silent before the Lord; so the life of God comes to guide.

And all you that are in your own wisdom, and in your own reason,
tell you of silent waiting upon God, that is famine to you;
it is a strange life to you to come to be silent, you must come into a new world.
Now thou must die in the silence, to the fleshly wisdom, knowledge, reason,
and understanding; so thou contest to feel that which brings thee to wait upon God;
(thou must die from the other,) that brings thee to feel the power of an endless life,
and come to possess it.
And in the silent waiting upon God thou comest to receive the wisdom from above,
by which all things were made and created; and it gives an understanding and a reason,
which distinguisheth from the beast.
And the life of God in thee, which brings to wait upon God, which gives thee life,
brings to know God; and to know God and Jesus Christ is life eternal.
And to you this is the word of the Lord God.
