== To All The Magistrates in London, etc.

Friends, that are called christians, and christian magistrates;
are not you worse than the Jews that took tithes, and had store-houses,
whereof all the strangers, and widows and fatherless were satisfied,
and there was not to be a beggar in Israel?
And your blind men, widows and fatherless children, crying up and down,
lying in every corner of your streets; crying up and down half a dozen together,
up and down your streets crying for bread, poor and lame;
is not this a shame to your christianity?
How dwelleth the love of God in you?
How clothe you your own flesh?
How feed you the hungry?
Are you not come here under the reproof of James?
How are you in the pure religion, to visit the sick, the fatherless, and the widows,
when both blind, and sick, and halt, and lame lie up and down,
cry up and down almost in every corner of the city,
and men and women are so decked with gold and silver in their delicate state,
that they cannot tell how to go.
Surely, surely you know not that you are all of one mould and blood,
that dwell upon the face of the earth.
Would not a little out of your abundance and superfluity maintain these poor children,
halt, lame, and blind, or set them at work that can work, and they that cannot,
find a place of relief for them; would not that be a grace to you?
Is not that a disgrace to you, for them to lie up and down in corners of your streets,
and high-ways, and steeple-house doors?
Doth not this show, that you want the wisdom of God, to order the creation?
And is not this a grief, think you?
And do you not believe it is so, to all the tender and sober people?
Is this true christian religion, to see so much preaching, praying, sermons, lectures,
and to see so many blind and lame, poor men and women,
and children up and down the streets, and at the steeple-house doors,
is not this an ill savour among you and in you, and the high profession ye profess?

Deal your bread to the hungry, honour the Lord God with your substance;
hide not thyself from thy own flesh; give to him that asketh of thee,
or would borrow of thee, lend, hoping for nothing again.
Him that turns his ear from hearing the cry of the poor, the Lord will not regard.
He that despiseth the poor, despiseth his maker.
So see, this is the word of the Lord God to you all,
and a charge to you all in the presence of the Lord God.
See all the poor, the blind, lame, the widows, the fatherless,
that cry up and down your streets for bread, for maintenance at your steeple-house doors,
and high-ways, and corners of streets and alleys,
that these be taken up and provided for, and they that can work,
that they may be set to it, and they that cannot, that they may be looked to,
that there may be a good savour in your streets,
that the Lord may come with a blessing upon you,
and give you an increase double another way.
Then you show the fruits of true religion, and the works of charity,
and the fruits of love, and the fruits of the spirit;
but now the fruits of the flesh which hath superfluity, which saith, I have enough,
I have superfluity, I have gold, I have money and goods in store, I have fine apparel,
and jewels, and rings, and dainty diet, dressing myself in glasses,
and buying glasses and pictures, and spices,
and consider not the poor which is ready to be starved, crying in the street,
and you are so proud,
that you cannot tell how to go up and down the streets in your laced shoes, and clothes,
and hats.
How are many with their hair powdered like bags of meal?
How are many in their jewels, and rings, and gold, and costly attire,
which the apostle speaks against, and checks such for; they regard not their own flesh,
they regard not their Creator, that regard not their fellow creature, that he created,
who created the one as well as the other, and causeth the sun to shine upon the just,
and the unjust, but destroy the creatures upon their lusts,
when others are in want of the creatures; slackening their hand,
and not giving to the poor.

God loves a cheerful giver, for God gives cheerfully, and freely, and liberally.
He that gives to the poor, lends to the Lord, the Lord restores him double again.
But people`'s hearts are hardened, and they mind not to disgrace the truth,
and the custom of the cries of the blind, the lame, the widows,
and the fatherless hath taken away the sense of compassion;
therefore let there be a store-house where all may be relieved, and let none want,
that all may have enough.
The Lord can take away from you as much in a week,
that would (it may be) serve thousands of the poor,
and cross you by sea and by land for your hard-heartedness;
which otherwise you would see as a blessing,
and feel as a blessing both within and without, in store, in field, by sea and land;
as you come into the wisdom of God, and stand in it, and are preservers of the creation,
then God will bless you, and, what you take in hand will prosper:
a preserver of the creation visits the sick and the fatherless,
and causeth not the blind to wander; cannot God bring the proudest of you all down,
and make you as poor as them that wander in the streets,
because you do not do good in your lifetime?
Therefore come to work, and do the work of the Lord, while ye have poor, ye great ones;
and come to the feeling of these things, ye magistrates,
that none of these may lie up and down your streets,
while it is in your power to do good.
From a lover of mercy and compassion to all that feed the wounded and feeble, lame,
and blind, and helpless: so in tenderness these things consider;
for there is so much destroyed in your superfluity and vanity,
that would maintain the weak, lame, and blind, that is spent upon your lusts.
O be a good savour, and do that which may be a good savour to the Lord God,
and in the hearts of all people in your generations.

From a lover of truth, and a friend of all your souls.

G+++.+++ F.
