== Concerning the World`'s Hypocritical Salutations, / Being out of the True, Are Condemned by the Truth.

The customs, and manners, and fashions of the world,
which are practised amongst people in the world, are vain;
when they meet one with another, they will say how do you sir, doff the hat,
scrape a leg, make a courtesie, I am glad to see you well, your servant,
your servant my Lord, (or sir) or mistress, and when they are past them,
with the same tongue with evil to them, speak evil of them, wish hurt to them, or to her,
and say he is so, and so, or curse him, or wish that he was hanged, or killed,
or do him a mischief; yet when he meets him, or she meets her, they bow one to another;
the hats bow, they are one another`'s servants,
(and your humble servant) and their service, and then when they are past one another,
wishes wickedness one to another, and laugh at one another behind their backs;
and this is a custom that is evil among men and women, which ought not to be,
and is to be rebuked, and reproved; they profess love and friendship to one another,
and with the same mouth wish ill one to another, and one destroy another;
this hath been an evil custom among men and women,
who when they meet together flatter one another,
and say they are one another`'s servants, and profess humility one to another,
and when one is gone from the other, envy one another, and lay a plot to do him mischief,
and do wickedness to one another; this is, and hath been a bad thing among people,
and is to be reproved; and these salutations are vain, and not to be observed,
but denied, and to be judged, that plainness, and truth, and uprightness,
and honesty may come to rule in people, and single-heartedness, and the love, indeed,
which is more than words; and this humility is feigned,
and this is a flattering one another in the presence, and a backbiting one another,
behind one another`'s back; this is to be judged and condemned,
that the witness of God in all may arise, that leads to truth in the inward parts.

G+++.+++ F.
