== The Second Covenant,

[.heading-continuation-blurb]
Which doth manifestly make known the End of the First Covenant and Priesthood,
which could not continue by reason of Death.
Or the New Covenant of Light, Life, and Peace,
wherein the Lord in Righteousness establisheth the Hearts of his People;
where they are taught of the Lord.
Also herein is declared the Difference between Christ`'s Way, and Judas`'s Way.--By G. F.

In the first covenant,
Exodus 18. and Deuteronomy 4. there you may see how
the people were taught the statutes of the Lord,
and what they were to observe, and what they were not.
The priests`' lips were to preserve the knowledge of the people,
and they should take the law at his mouth,
for under this priesthood the people received the law; now this law is changed,
and the priesthood changed, and the law by which the priesthood was made.
And in this first covenant there were ordinances and statutes;
but the second priesthood is now come, whom Moses prophesied of,
who had the ordinances and statutes,
which he gave to the priests and to others to teach to the people, who saw beyond them,
for he saw Christ whom the people should hear,
and the prophets saw beyond those figures and ordinances, and they saw Christ;
and David saw beyond them, and he saw Christ; and when Christ came whom they saw,
he blotted out the hand-writing of ordinances which formerly had been taught the people.
And they were to teach them one another, and teach their neighbour, and their brother,
and their children them, and write upon the posts and stones, and upon the walls,
and make fringes upon their garments, to put them in remembrance of them.
But Christ being come, the second covenant, the everlasting covenant, the first covenant,
that is not everlasting in which were ordinances, he blotted out.

Now where the light is received, Christ is received, the covenant of God,
and this lets every one see the first covenant,
(and the first covenant in which were the ordinances,
and the priests`' lips that must preserve knowledge,) the light that comes from Christ,
brings to see this,
and the change of this priesthood who was to keep knowledge to teach the people,
the people were to seek at his lips, and to see the decaying of the first covenant,
which is not everlasting,
and Christ which was to blot out the hand-writing of ordinances.
So who be in the covenant of light, see the first priesthood,
whose lips were to preserve knowledge, the first covenant decaying,
and the ordinances blotted out; these that be in the light, in the new heart know God,
and need not teach every man his neighbour, saying know the Lord;
for he that hath received the light, hath received the covenant with God,
and growing up in the light, is taught of Christ, and grows up in his knowledge;
and he it is that preserves his knowledge; and not the first priesthood;
and he it is that gives him life, and not the first priesthood;
and he it is that is the way, and not the first priesthood;
for the first priesthood doth decay, and from him it is that he hath his food,
and not from the first priesthood, which is changed,
and could not continue by reason of death.

So God at sundry times and in divers manners,
spoke in times past to our fathers by the prophets,
but now in these last days hath spoken to us by his Son, who is heir of all things,
and upholds all things by the word of his power, who is the brightness of his glory,
and the express image of his substance, and this now is witnessed, Heb.
1+++.+++ And Moses saith, that saw beyond his ordinances,
and he it is that preserves his knowledge;
now he that doth not hear him (this prophet) which
God has raised up which Moses spoke of,
who follows the decaying things, the changeable priesthood,
and pleads for the ordinances that Christ blotted out, as you are turned to the light,
to this prophet, may see with that which gave forth scriptures,
the statutes of them that are out of the life,
and the Jews which hold up the first priesthood,
and the ordinances and the first covenant, for in these was their life.
John 5. And Christ told them he was the bread of life, which came down from above;
and said, is it not writ in the prophets they shall be all taught of God?
And was there not in the first priesthood, they that were to teach one another,
to say know the Lord, and know his ordinances, and know his laws,
and was not this in this first priesthood, and first covenant?
But Christ the second priesthood, the second covenant, the prophet that Moses saw,
that the people should hear, which lighteth every man that cometh into the world,
that all men through him might believe, he saith here, it is written in the prophets,
ye shall be all taught of God,
every one therefore that hath heard and learned of the Father cometh unto me, +++[+++mark,]
he that hath heard and learned of the Father cometh unto me, saith Christ,
who is the way to the Father; now they that have not heard nor learned of the Father,
murmured against Christ, and would not come to him.
And did not God say when he had raised up his prophet which Moses spoke of,
that God would raise up, that the people should hear;
doth not God say this is my beloved Son, hear you him in all things?
and doth not Christ say, learn of me, I am the way, the truth, and the life?
who blotted out all the hand-writings of ordinances, triumphing over them,
and the end of the law to every one that doth believe in him for righteousness sake,
the end of the priesthood that could not continue by reason of death; he it is,
who lives forever, and the end of the first covenant that decays,
he is the everlasting covenant that decays not, who is God`'s covenant of light, of life,
of peace to his people, that all through him might believe.

And who are come hither shall know the Lord, and the blotting out of ordinances,
and the changing of the law, by which they were made,
and the disannulling of the command which they had to take tithes of the people,
and see these ordinances blotted out which the people were taught,
and see that which did preserve knowledge,
that priesthood at whose lips the people were to seek the law.
He that was made by a law, that law changed, and that priesthood changed also,
so that is the changeable; the light which comes from the unchangeable discovers it,
and they that are come to Christ, the treasury of wisdom and knowledge,
see the end of the first, they are come to the beginning, who is the heir of all things,
who was glorified with the Father before the world began, God`'s covenant of light, life,
and peace with his people, his everlasting covenant; and who are here need not say,
know the Lord, but shall witness the everlasting covenant,
and have the law of God written in their hearts, according to his promise,
and such as are come hither to Christ, to the second priesthood,
the everlasting covenant, him that blotted out the hand-writing of ordinances,
Christ told them they should be hauled before magistrates out of
synagogues (for such magistrates hold up the first covenant,
and the ordinances which Christ blotted out,
the first priesthood whose lips were to preserve knowledge, temple,
and synagogues) and Christ said to them that were his disciples,
when they were brought before magistrates, or scourged in the synagogues,
the Holy Ghost should teach them in the same hour what they were to say; +++[+++mark,]
the Holy Ghost teacheth these that are come into the everlasting covenant,
as it is known and witnessed at this day, by them that are in the covenant of light,
life, and peace, and the Holy Ghost doth teach them what to say in the same hour,
to answer the magistrate that holds up the first priesthood,
whose lips were to preserve knowledge, and the ordinances which Christ blotted out,
and they that were disciples of Christ directed to this priesthood,
to show them Christ Jesus out of the prophets, which spoke of Christ that was to come;
when he was come, they being found in the words of Moses and the prophets,
but out of the life of Moses and the prophets, therefore were they blind guides,
and led others into the ditch, and so saw not that which Moses and the prophets saw,
and received it not when it came, though the prophets spoke of Christ which was to come,
and so it is at this day with them that have the words of the scriptures,
but are out of the life, stand against the life that gave them forth,
stand against the things they spoke of.

So now they that are in the covenant that is everlasting,
the Holy Ghost doth teach them what to say in the same hour
when they are brought and hauled out of the synagogue,
and before the magistrate, or before the changeable priesthood,
and magistrates and people look at them,
and so doth not look to the everlasting covenant, Christ Jesus the prophet, to hear him,
which God hath raised up, which Moses prophesied of, which now thousands witness,
glory to the Lord God forever, Isa. 54.
he saith all thy children shall be taught of God,
and great shall be the peace of thy children:
and in righteousness shall they be established, +++[+++mark,]
the children of the Lord, which are taught of the Lord,
in righteousness shall be established, for who are taught of the Lord,
and established in righteousness, they are in Christ the righteousness of God,
who is the end of the law for righteousness sake:
so you that have heard and learned of the Father, come to Christ God`'s righteousness,
and hear the Son, the prophet Moses spoke of, that God should raise up.
Now do you believe that God hath raised up his prophet that Moses spoke of,
that the people should hear, that are holding up priests that take tithes, temple,
and synagogues?
Do you believe that this prophet is come that Moses spoke of that God should raise up?
You that are hearing the priests that are taking tithes,
are not you here out of the covenant that is everlasting?
Are not you strangers from the life of God, the covenant of peace,
and in the confusion one with another, about words, the words of Christ, the prophets,
and apostles, and so are not the children taught of the Lord,
which are established in righteousness, but strangers from this covenant of promise,
and strangers from the life of God, through the alienating of your minds,
and so are in the changeable;
shall any thing formed against those children taught of the Lord,
and established in righteousness, prosper?
And shall not he condemn every tongue that riseth up in judgment against them?
The children of the Lord, that are taught of him, and established in righteousness,
are they such that are taught of the first priesthood, that takes the tithes,
that is changeable, and holds up the synagogues, and temple, and first covenant?
Are these established in righteousness, and free from oppression,
which the children that are taught of the Lord and
established in righteousness are free from?

And David saith, who saw beyond the ordinances the first covenant that was to decay,
and the first priesthood that was to change, whose lips were to preserve knowledge,
and the people was to seek it at his lips;
David that saw beyond that priesthood and covenant, that saw Christ,
he out-stripped all his teachers.
Ps. 119:99. I have more understanding than all my teachers,
for thy testimony is my meditation.
+++[+++Mark,]
The testimony of the Lord was his meditation, for thou taughtest me,
how sweet were thy words to my taste, yea sweeter than the honey.
+++[+++Mark.]
Here David out-stripped them all, who had heard and was taught of God,
and said thou taughtest me;
he out-stripped and had more understanding than all his teachers, and said,
Oh how I love thy law, it is my meditation all the day; and saith Solomon, his son, Prov. 6.
the law is light; who said, to do justice is more than sacrifice; who said of wisdom, Prov. 8.
I was with him in the beginning, before the earth was, and the hills were settled;
and so he saw beyond the first priesthood, who saw into the beginning,
and before the beginning, when he gave the sea its decree and commandment,
and appointed the foundation of the earth.
I was with him, and took my solace in the compass of his earth,
and my delight was with the children of men, when he established the clouds,
when he prepared the heavens, before he made the mountains, and settled the hills,
when he had not made the earth, the field, or the highest part of the world,
then was I by him, as one brought up with him, daily his delight;
here he sees over all the world. Prov. 3.
And saith Job, 12, which came to hear God, and after came to see him,
Ask now the beast and they will teach thee,
and the fowls of the air and they will tell thee,
and speak to the earth and it will teach thee,
and the fish of the sea and it will declare unto thee,
who knoweth not that in all these the hand of the Lord hath wrought,
in whose hand is the soul of every living thing, and the breath of all mankind: +++[+++mark,]
mind this hand in which the soul of every living thing is, and the breath of all mankind,
mark this hand, feel and know this hand,
then you will know that which doth the valiant things,
and you will come to know that which will teach you.

And now is the time come of Isaiah`'s prophecy,
that the teacher shall be no more removed into a corner,
though they have bread of adversity, and water of affliction,
but thine ears shall hear a word behind thee, saying, this is the way, walk ye in it;
now all people being strangers from the covenant of light, their faces toward Egypt,
which is darkness, the word calls behind,
and all people are walking toward the first priesthood that is changeable,
and the first covenant that is changeable, and doth decay,
and to the synagogue and temple, and the ordinances that Christ blotted out,
and maintaining the priesthood with tithes, which were of the first priesthood,
but the covenant is changed that made them, and the command disannulled;
now this word is behind all these, for that is not the way,
and the word saith this is the way from all those ways, the word saith Christ is the way,
who saith learn of me, and saith God, this is my beloved Son, hear ye him,
him that Moses said God would raise up, this is the word, here is the voice behind,
and who heareth this voice, and hath heard this word, hears the Son;
in these last days God hath spoken to us by his Son, who is heir of all things,
whose name is called the word of God.
Rev. 19. Now they that are of the Jews, are for holding up synagogues, and temple,
and priesthood, that hold up the first covenant as the Jews did;
the priests that take tithes, they will not hear this word, nor this voice behind them,
they will have none of Christ, will not suffer him to reign over them,
and so will not hear the prophet that Moses said God would raise up,
and said people should hear, and so disobey Moses`'s command, and God`'s command,
who saith, this is my beloved Son, hear ye him, and Christ`'s command, who saith,
learn of me, whose name is the word of God.

So they that had the letter knew not the word,
and they that have the letter know not the voice now, nor the word,
but fly to the priest`'s lips and synagogues, and temple,
and there the priest`'s lips that takes the tithes must preserve their knowledge,
and so will not hear the word Christ, nor the voice,
but imprison and persecute them that come to tell them of this word, and this light,
and haul them out of the synagogue,
and put them into prison as they did in the days of the Jews:
now here Isaiah saw the word, and the covenant of light which the apostle preached,
and knew this voice, and this way, which the people was to walk in,
which he saw beyond sacrifice, and offerings, and priesthood, and first covenant,
for he saw Christ, and said this is the man whom God hath regard to,
who was of a broken heart and contrite spirit, and trembled at his word, Isa. 66.
and Jeremiah which saw beyond the first covenant, first priesthood,
and tables of stone, statutes and ordinances, saith the Lord by him;
I will make a new covenant with the house of Israel, saith the Lord, after these days,
+++[+++mind,]
I will put my law in their minds, I will write it in their hearts, I will be their God,
and they shall be my people.
+++[+++Mark,]
Here were days when the law was written in stone,
and they were to write them upon the walls, and upon posts,
and they were to have fringes to put them in remembrance of them;
now here were these days, but saith the Lord, after these days,
I will put my law in their hearts, they had put them in tables of stone,
there were those days wherein the people was to have the law taught,
and to have the Lord taught, and his laws, and his statutes, and his ordinances.

Now the law being written in the heart according to the promise of the Lord,
who performs and fulfils his words according as it is spoke, who saith,
he will put his law in their inward parts, and write them in their hearts,
after those days +++[+++mark,]
after the former days, and I will be a God to them, and they shall be my people,
and they shall teach no more every man his neighbour, and every man his brother, saying,
know the Lord, for they shall all know me, from the greatest to the least of them,
saith the Lord, and I will be merciful to their unrighteousness,
for I will forgive their iniquity, and remember their sins no more:
now while the law was written without, in the tables of stone, or upon the posts,
and had fringes to put them in mind of the law, they taught every man his neighbour,
and every man his brother: but these were the days when the laws were written upon stone,
the first priesthood, the first covenant standing.
Now after these days, the end of the first priesthood, the first covenant,
and the decaying of it,
these come to witness the Lord having written his law in their hearts,
and put them in their inward parts, +++[+++mark,]
the Lord having done this, every one feeling this which the Lord hath done,
putting his law in their inward parts, and written them in their hearts;
they feel here the Lord nigh them,
and they that feel this feel the promise of God fulfilled, and know the Lord,
he having put his law in their hearts, for this will teach every man to know the Lord,
and here every one shall feel the Lord is merciful to their unrighteousness,
and their iniquities, and their sins he will remember no more;
such as feel the law written in their heart, his promise fulfilled, know this,
and know the Lord, yea the least of them, to the greatest of them,
so that they shall not need to teach one another, saying, know the Lord;
thus saith the Lord who hath promised this, which giveth the sun for a light by day,
and the ordinances of the moon, and the stars, for a light by night,
which divideth the seas when the waves thereof roar, the Lord of hosts is his name;
+++[+++mark if these ordinances depart from before me, saith the Lord,
then shall the seed of Israel cease from being a nation before me forever.

And now is the Lord known, and his promise fulfilled, and his ordinances performed,
who hath put his law in their hearts, and written them in the inward parts of his people,
and he is their God, and these need not teach every man his brother,
and every man his neighbour, saying, know the Lord,
for they shall all know me from the least to the greatest, saith the Lord, and these,
who can show this, that the law of God is written in their hearts, they know the Lord,
from the least to the greatest, Jer. 31. and Ezek. 11.
saith the Lord by him, I will give them one heart,
and I will put a new spirit within you,
and I will take their stony heart out of their flesh, and give them a heart of flesh,
that they may walk in my statutes, and keep mine ordinances to do them,
and they shall be my people, and I will be their God; and now this spirit is witnessed,
which the Lord hath put within his people, and hath given them a new heart,
and this is the one heart,
the new heart which the people of God come to be joined together withal to God,
and this brings them to know the Lord to be their God,
and themselves to be his people according to his promise, they shall be unto me a people,
and I will be unto them a God,
but as for those that walk after the heart of their own detestable things,
and their own abominations, I will recompense their way upon their own heads,
saith the Lord God.

Now here is the end and portion of such who walk from the light of Christ,
walk from the light, so from the law, for the law is light,
but they that witness the new heart, the one heart, if it be thousands,
yea ten thousands,
these walk over all the abomination and detestable things of the world,
and see the Lord recompensing upon their heads such as walk after their own hearts,
they are not in this one heart, but in the heart that is desperately wicked,
and deceitful, and that is the old heart, the corrupt heart, that is desperately wicked,
and this is the portion of them that walk after detestable things, and abominations,
God will recompense it upon their own heads; and saith Christ the second priest,
the righteousness of God, the everlasting covenant of light, life and peace,
when he was to leave his disciples, and to pass away from them, saith he,
I will send you the Comforter, here is the Comforter, which is the Holy Ghost,
whom the Father will send in my name: he shall teach you all things, +++[+++mark,]
they that were of Christ and followed him, the Comforter, the Holy Ghost,
should come unto them, from the Father, which Christ is the way to,
which Holy Ghost should teach them all things, and bring all things to their remembrance.
Whatever I have spoken to you, +++[+++now mark,]
this is it that must teach, and was to teach, and must bring all things to remembrance,
which Christ hath spoken to his disciples, +++[+++mark,]
this brings to remembrance, the Holy Ghost, the Comforter which comes from the Father,
the spirit of truth, which leads into all truth;
now who would have any thing to teach them, and to bring to their remembrance,
all the things that Christ hath spoken, and to teach them,
and not the Comforter the Holy Ghost, they are besides the thing,
and there is all the jangling about the words.

And this is it which brings them to remembrance,
and the same baptizeth and shutteth out of the old memory the words,
he which hath them in the old memory, hath not the Holy Ghost to teach him;
now thousands are come to witness the Holy Ghost, such as are learned in letter,
and unlearned in letter, which Holy Ghost teacheth them,
and brings to their remembrance the things that Christ hath spoken,
it brings to memory that which is brought to memory, and without it is not taught,
neither learned, nor unlearned, as Peter speaks of, but this is it that teacheth,
the Holy Ghost, and brings to memory, and lets them see the words,
yea all things as Christ hath spoken; so peace I leave with you.

And the disciples and apostles which witnessed Christ`'s resurrection, and heard him,
witness the Holy Ghost teaching, these had received the Holy Ghost from the Father,
which things saith the apostle we also speak, not with words of man`'s wisdom, +++[+++mark,]
not with words that the man`'s wisdom teacheth, but which the Holy Ghost teacheth,
comparing spiritual things with spiritual things, +++[+++mark,]
these spoke not in the words which man`'s wisdom teacheth, not in the words,
+++[+++take notice of that,]
but which the Holy Ghost teacheth, and so these witnessed Christ`'s words fulfilled;
the Holy Ghost shall teach you,
and bring to your remembrance whatsoever I have spoken to you;
now these saw Christ`'s words fulfilled, which we do now that are in his life,
and witness the Holy Ghost, for these come to witness that are here,
that which Christ spoke should come to pass and enjoy it;
here every one comes to know what the Holy Ghost teacheth,
here spiritual things are compared with spiritual things,
and then you that are come to this teaching of the Holy Ghost,
you will know those things which also are spoken
in words of man`'s wisdom which that teacheth,
and these things which they speak.
Now they that witness the Holy Ghost teaching, witness a teaching above that,
which teacheth, in the words, which man`'s wisdom teacheth, +++[+++mark,]
not in the words. 2 Cor. 2.
Now they that be from this teaching of the Holy
Ghost in man`'s wisdom after its teaching,
and look at the words, get up heaps of teachers after their own lusts, and itching ears,
itching after the words of man`'s wisdom,
and the words that teacheth in man`'s wisdom pleaseth them, and these turn after fables,
who err from the truth, and are from the Holy Ghost teaching, 2 Tim. 4.
and are desiring to be teachers of the law, 1 Tim. 1.
understanding neither what they say, nor what they affirm;
we say the law is good if it be used lawfully, +++[+++mark,]
and take notice of this, the law is good if it be used lawfully, knowing this,
that it is made for the unrighteous and lawless,
knowing it is not made for the righteous, but for the lawless, ungodly, disobedient,
and sinners, for the unholy, profane, murderers of fathers, of mothers, man-slayers,
for whoremongers, and them that defile themselves with mankind, for liars,
for perjured persons, if there be any thing that is contrary to sound doctrine,
according to the glorious gospel of the glorious God, which is the power of God,
for these actions are contrary to the righteous, so it was made for such,
and not for the righteous, for Christ is the end of the law for righteousness sake,
to every one that believeth.
Nevertheless the law is good in its place upon them that do not believe,
but be in the sin, and pleading for it, and such are teachers of the law,
which do not know what they affirm, nor whereof they speak,
for they that did preach Christ, that were taught of the Holy Ghost,
said the law was changed by which the priesthood was made,
and the commandment was disannulled, which gave them tithes,
and so those teachers of the law which did not know what they affirmed,
nor whereof they spoke, were not taught by the Holy Ghost,
which lets see Christ the end of the law,
the righteousness of God to every one that believeth for righteousness sake.

Now the apostle who witnessed Christ Jesus the everlasting covenant,
who saw the end of the law, the end of the first priesthood,
the decaying of the covenant,
enjoined this which the prophet Jeremiah did give testimony of, and saw it fulfilled.
Now saith the apostle, if that first covenant had been faultless,
then should no place be found for the second, for finding fault with them he saith,
behold the days come, saith the Lord,
when I will make a new covenant with the house of Israel, and the house of Judah,
and not according to the covenant that I made with their
fathers in the day when I took them by the hand,
+++[+++mark,]
to lead them out of the land of Egypt, because they continued not in my covenant,
I regard them not, saith the Lord, +++[+++mark,]
because they did not continue in God`'s covenant, he regarded them not,
but now in the covenant which God makes with his people,
not according to that covenant which the people did not continue in,
the Lord regarded them;
for this is the covenant that I will make with the house of Israel after these days,
saith the Lord, I will put my law in their minds, and write them in their hearts,
I will be to them a God, and they shall be to me a people,
and they shall not need to teach every man his neighbour, or every man his brother,
for they shall all know me, from the least to the greatest;
and I will be merciful to their unrighteousness,
and their sins and iniquities I will remember no more.
He saith a new covenant, he made the first old, +++[+++mark,]
now that which decayeth and waxeth old, is ready to vanish away;
now who are in this new covenant, not according to the old made with the house of Israel,
and the house of Judah, and the law put in their minds, the law of God,
and written in their hearts, these witness the light, for the law is light,
and they need not to teach every man his neighbour, or his brother,
for this will teach every man, yea from the least to the greatest;
and who witness this light, the law written in their hearts, and in their minds,
they know and witness him that is merciful to their unrighteousness,
and their sins and iniquities he will remember no more,
who hath put his law in their minds, and writ it in their hearts;
here the Lord is their God, and they are his people, and they that are here,
witness the new covenant received from God, and he maketh the first old, +++[+++mark,]
he maketh the first old; they that are in the old, and the decaying,
and man`'s wisdom teaching, these are out of the new covenant,
and know not the Lord that gives the new; and now that which decayeth and waxeth old,
is ready to vanish away, +++[+++mark,]
waxeth old, decayeth, vanisheth away, and they that do not witness the new,
put into their minds, and written in their hearts, they know not the Lord,
they be in that which the Lord maketh old, the first,
and that which decayeth and waxeth old, and is ready to vanish away;
now this the apostle saw in his days, and such as be in the new covenant of God,
the law written in their hearts, and put in their minds, which is the light,
these see the decaying, and the waxing old, and the vanishing of the other,
and so these see those days while it was standing,
and these see those days of the new covenant which is come after those days.

Christ is come, the covenant of God, to do his will, as in the volume of the book,
the everlasting covenant of light and life;
and this is the covenant that I will make to the house of Israel and Judah,
to the Gentiles a covenant of light, to the Gentiles that be in darkness;
and the Jews and the Gentiles that be in the light, they be in one way,
and with the light they come to know the Lord,
and having received the light put into their minds,
they come to have the law written in their hearts, and put into their minds,
and he that receiveth the light, receiveth the covenant, whether he be Jew or Gentile,
so he that receiveth the covenant, the new covenant, the law written in the heart,
he receives a new heart, the stony heart goes away,
for the stony heart will hold the decaying things, and them that waxeth old,
and vanisheth away, and with that heart God is not seen;
and now that was not the heart which was desperately wicked, and deceitful,
that the saints were once in, for where the law is written in their hearts,
that is taken away, and so come to witness the new covenant, and the new heart,
and the one heart, and this was the heart the saints were in, who believes in the light,
Christ the covenant of light,
and with this they come to witness the law and Holy Ghost teaching,
and this turned them from man`'s teachings in the wisdom of words,
the Holy Ghost did teach,
and these came to witness the pure heart with which they see God, and know God,
which they that are out of do not; and this covenant,
this everlasting new covenant is witnessed in our days, and this new heart,
and this pure heart with which heart God is seen,
and God hath put his law in the minds of his people,
and in their hearts hath he written them, with which they do know him,
and he is their God, and they are his people,
and these witness that which the Lord hath spoken formerly,
in the ages past by his prophets, to be fulfilled, and come to pass,
for that is the end for which the scriptures were given forth, to be believed, fulfilled,
read and practised, and saith John, let that therefore abide in you,
which you have heard from the beginning, +++[+++mark,]
which you have heard from the beginning, let that abide in you,
for said Christ I am the light of the world,
who doth enlighten every man that cometh into the world, by whom the world was made,
and all things were created for him and to him, who is the heir of all things,
glorified with the Father before the world began,
who enlighteneth every one that cometh into the world,
that all through him might believe.
And this is the light that shines in darkness,
(and shows darkness and sin and evil,) which cometh from him who is the light,
and this was the light which the apostle was sent to turn people from darkness to;
so turning to the light, turns to Christ, to him from whence it comes,
by whom the world was made, and they that hear the light,
hear that which was from the beginning,
and hear that which ye have received from the beginning.
Therefore I say unto you all,
let that abide in you which you have heard from the beginning the light,
and if that which you have heard from the beginning shall abide in you,
you shall continue in the Son, and in the Father, for this comes from the Son,
and the Father, and leads up into the Son from whence it comes, the light,
and this is it which you have heard from the beginning: therefore I say unto you,
let that abide in you, and this is the promise which he hath promised us,
even eternal life.

And these things have I written unto you concerning them that seduce you;
now they that do seduce, seduce from that which you have heard from the beginning,
which he, in whom it abides, continues in the Son, and in the Father,
and comes to receive eternal life, which is the promise.
Now the seducer did teach, which had the seducing spirit,
but those are they which be out of the truth,
and abide not in that which he hath heard from the beginning, but is out of it.

And this is the word of the Lord God to you, and that is the sorcerer that is out of it,
which is heard from the beginning, and brings to eternal life,
and brings to have unity with the Father, and the Son,
and this is the word of the Lord God to you again, which the seducer is out of,
which would seduce from it, and seduceth all that are from it,
that which is heard from the beginning.
And hears the world of wickedness under the power of the seducer,
which seduceth from that which was heard from the beginning,
from having unity with the Father, and the Son,
and these are under the power of the seducing teachers,
and he that is out of this denies the Son, yea and the Father also,
which hears not that which was from the beginning,
that anointing which ye have received of him abideth in you.
+++[+++Mark,]
Abideth in you, the light which cometh from the holy one,
from him by whom the world was made; +++[+++mark,]
now it abideth in you, the anointing which you have received from him, from Christ,
from the holy one, and you need not that any man teach you,
but as the same anointing teacheth you all things, +++[+++mark,]
that which you have received from the beginning, the anointing which abideth in you,
it will teach you, and you need not that any man teach you,
but as the same anointing teacheth you of all things, +++[+++mark,]
but as the same anointing teacheth them that abide in it.

Now who hath teaching, but not as the same anointing teacheth him,
they are led from the holy one, and so are seduced, for they need not any man teach them,
but as the same anointing teacheth of all things that come from the holy one,
which you have received of him, of Christ by whom the world was made,
so the seducer leadeth from this anointing which
ye have received of him which abideth in you,
and you need not that any man teach you, but as the same anointing teacheth you.
Now there is man`'s teaching which draws from this anointing, which you have received,
which abideth within you, and telleth you that ye have need of man`'s teaching,
but the Holy Ghost teaching saith you need not that any man teach you,
but as the same anointing teacheth you of all things, and is truth; +++[+++mark,]
of all things the same anointing teacheth you, and is truth, and is no lie.
+++[+++Mark,]
This is that which abideth in you, and even as it hath taught you this anointing,
ye shall abide in him, +++[+++mark,]
in Christ from whence it comes, none comes to abide in Christ,
but even as this anointing which they have in them teacheth them,
they shall abide in him, and it is truth, and no lie,
and they need not that any man teacheth them,
but as this anointing teacheth them which abideth in you, and even as you are taught,
you should abide in him by whom the world was made, and to see over men`'s teaching,
and them to be out of this, and the seducer under it drawing from it.

And now little children abide in him,
that when he shall appear you may have confidence in him; now who abides in him,
abides in that which they have heard from the beginning, they that abide in this,
abide in the anointing which they have received from him who abideth in them,
and these need not any man teach them,
but as the same anointing teacheth them of all things, and it is true, and no lie,
and received from him, that you abide in him, even as it hath taught you;
you shall abide in him, +++[+++mark,]
as it hath taught you, you shall abide in him,
but as you abide in that which man teacheth you, and the seducing teacheth you,
they draw you from this anointing that abideth in you, such doth not abide in him,
nor the truth, but believe lies, but these come to the shame out of their confidence.
But ye shall not be ashamed at his appearing, who abide in him,
who are taught with the anointing, but ye shall have confidence,
and if ye know that he is righteous,
you know that every one that doth righteousness is born of him,
and this they know that abide in him, and are taught of the anointing,
and these comprehend the seducer`'s and men`'s teaching,
and such as draw from the anointing that abideth within you, +++[+++mark,]
it abideth within you, and none come to abide in the Son, but who abide in that,
and are taught with that, with the anointing,
and even as it teacheth them they shall abide in him, in him by whom the world was made.
And so the seducer and man`'s teaching people draweth from the anointing,
that abideth in them, that must teach them; for if the man-teacher,
and the seducer suffers people to own that which abideth in them,
and that they need not that man teach them, but as the same anointing teacheth them,
the seducer and man`'s teaching will soon fall, and man will have nothing to do,
as every one is taught with this anointing which they have in them,
they shall continue in the Son, and in the Father:
and to you this is the word of the Lord God.

[.asterism]
'''

=== Christ`'s Way and Judas`'s Way.

Christ Jesus which is the unchangeable priest, is the way to the Father,
who is the light, he is the way to the Father of light,
and all the changeable priests are not the way, that take the tithes,
hold up synagogues and temple made with hands, where the hirelings are,
and such as divine for money, teachers that bear rule by their means,
seek for their gain from their quarter, shepherds that seek for the fleece;
the teachers that through covetousness make merchandize of the people,
and teachers for filthy lucre sake, which have the love of money,
which is the root of evil, and these be all out of the way, which is the light,
and all they that be under these, they are kept out of the way by these,
and taught to deny the way, which are taught to deny the light,
which enlighteneth every one that cometh into the world,
and rail and blaspheme against the way, both teachers, and their hearers;
but the light that doth enlighten every man that cometh into the world,
this is the way that came from the Father of lights,
which lighteth every man that cometh into the world,
and cometh from the Father of lights, and goeth to the Father of lights again.
And said Christ, I came from the Father, and go to the Father again, I am the way,
the truth, and the life, no man cometh to the Father but by me,
who am the way to the Father, the light, truth, and life, and who cometh to me,
cometh to the Father, who am the way to the Father; who cometh not to me,
cometh not to the way, and cometh not to the life, and cometh not to the truth,
and cometh not to the peace.

Now the way of the devil was from the truth, who abode not in it, and he deceived Eve,
he that was from the truth, and she gave to Adam, who did eat,
though before it was said unto him, he should die the death;
which led out of the command of God, and so into death, which he did, and died;
and was drove from God, being gone from his command, he goes from God,
so the way from the command of God, is death; the command is life,
the way from it is death, he that abides not in the truth, but goes from it,
abides not in the way of God.
Now Cain went from the command of God, which command is light, so Cain a murderer,
so the devil who abode not in the truth.
Now here is the devil`'s way, here is Cain`'s way, both murderers, who go from the light,
from the truth, which is the command of God; and the Lord said unto Cain,
If thou doest well shalt thou not be accepted, and if not, sin lieth at the door?
He did not well, he so disobeyed the command of God,
and so went out of the command of God, and all the heathen which know not God,
are out of the way, which is the light, and all the Jews who had the law of God,
they that talked of the words of it, and obeyed it not,
were out of the way which is the light, for the law is light,
and these saw not Christ when he came, who were out of the law, which is light,
and the obedience of it, and these saw not Christ when he was come who was the light,
the end of the law, which is the way, the new and living way,
and Christ the end of the first priesthood, the end of the first covenant,
the end of the temple made with hands, and the end of all the synagogue-teachers,
and temple-teachers that take tithes, who is the way to the Father,
and the church in God the Father of our Lord Jesus Christ.

Now they that believe in the light, and walk in the light,
that enlighteneth every man that cometh into the world, they walk in the way,
they walk in truth, receive life eternal, these come to witness the holy one;
the anointing in them by which they need no man to teach them;
but as the same anointing teacheth them all things, and is truth, and is no lie,
and as every one abideth in this anointing which is within them,
received from the holy one, when he doth appear, they shall appear with him in glory,
for it is the way, comes from the way, and it is the way to the glory;
but who are turned from the light, which they have received from Christ the holy one,
him by whom the world was made,
which was glorified with the Father before the world began,
I say who turn from this light, go from the eternal honour, the eternal glory,
the eternal riches, the everlasting priesthood, the everlasting covenant of light, life,
and peace; they go from the way, they go from the truth, they go from the life,
err from the way to the Father, where the church is in God.
Moreover they that go from the light to the priests that take the tithes,
and hold up synagogues, and outward temples made with hands, which divine for money,
and teach for filthy lucre, and seek for their gain from their quarter,
and bear rule by their means, and seek for the fleece; they that follow such,
Judas is their way, not Christ, for they are gone from the light, Christ,
the unchangeable priest, to the changeable; they may talk of Christ,
but are gone from him, that are gone from the light,
to Judas which had received part of the ministry, when he forsook Christ,
he went and betrayed him, and sold him to the changeable priests,
and betrayed him to them;
so whoever forsakes the light which doth enlighten every man that cometh into the world,
which they be enlightened withal, and go to the changeable priest, Judas is your way;
you that have been convinced with the light, and are gone from it, to the priests,
the synagogues, temple priests, that take tithes, you speak evil of the right way,
and cause others to speak evil of it, who through covetousness make merchandize of you,
for the light is the way, and the light is the truth; and all they who hate the light,
who enlighteneth every man who cometh into the world,
nor cannot believe in the light that enlighteneth every man that cometh into the world,
they do not believe in the way, nor in the truth, nor in the life,
these do not receive the gospel;
for they do not receive the light of the glorious gospel,
the god of the world having blinded their eyes, the light of the glorious gospel,
which is the image of God, they do not see him by whom the world was made,
who lighteth every man that cometh into the world,
which do not see the light of the glorious gospel,
which lighteth every man that cometh into the world, which light is the power of God.

And you may see all that be out of the light, you be out of the way, out of the truth;
the Jews were out of the way, though they professed the scriptures,
and they persecuted the way, and the christians now that are in the letter,
now are out of the way, and persecute them that are in the spirit,
and crying up the letter, and crying against the way,
the light that enlighteneth every one that cometh into the world, as the Jews did,
which cried up the outward ordinances, and the law, and the letter, but denying Christ,
which lets them see the end of it; and persecution was ever out of the light,
and so was ever blind; this is the word of the Lord God to you all;
Judas was out from the light, and so from the way Christ,
when he went to the changeable priesthood, he went out from the everlasting priesthood;
so they all now that go to the priests that take tithes, and synagogues, and temple,
from Christ the everlasting priesthood, and receive not gifts from him,
who gives gifts that are perfect, that are for the perfecting of the saints;
but the priesthood that take tithes, and holds up synagogues, and temples,
say that men shall not be perfect while they be upon earth;
you are an imperfect ministry, but Christ is the way, who received gifts for men,
who is perfect, for the perfecting of the saints,
until that they do come to the unity of the faith,
and to the knowledge of the son of God to a perfect man,
and to the measure of the stature of the fulness of Christ,
who perfecteth forever them that are sanctified, +++[+++mark,]
he perfects them forever; but this ministry now,
and the work of this ministry is denied, with the ministers,
that deny the light which enlighteneth every man that cometh into the world,
which have not received their gifts from Christ, which makes perfect,
who ascended far above all principalities and powers,
which was glorified with the Father, with the glory which he had before the world began.
