== The Wrath of the Lamb

I will break into pieces, saith the Lord, I will make nations like dirt,
I will tread them into mire; I will make religions, professions, teachings, time-servers,
callers upon me with their lips, (and hearts afar off,) surfeiting in the earth, pride,
hypocrisy, and deceitfulness of heart, gathered into a religion that is vain,
gatherings on heaps, gatherings of multitudes, gatherings which they call churches,
fair shows, fair pretences, hypocritical teachings, self-ends, covetous practices,
I will make mire of them, I will make mortar, I will make dirt of them;
the wrath of the Lamb is risen upon all apostates, who are gathered in the apostacy,
apostatized from the prophets`' life, the apostles`' life, the life of the Lamb;
the Lamb is risen, the sceptre is gone out, the throne is set,
beware every one what you profess, what foundations you are laying, you shall be shaken,
not being in the possession, being out of the possession of the life of God,
of the prophets, of the apostles, of Christ.
Ye diviners, ye dreamers, ye notionists, in your curiosities in the air,
I will whirl you under, hail-stones, vials, plagues, thunders, woes,
judgments are come amongst you, upon your heads,
all nations that be out of the life of the Lamb, dread, quakings, fears,
shall surprise hypocrites with amazements; the pure life of God is risen,
that has been lost, from it ye have been apostatized, without it have you been gathered,
with it shall your gatherings be broken and scattered; from the life of my apostles,
of my prophets have you been all scattered and apostatized,
and so true ministry hath been lost, true apostles`' life lost,
true prophets`' life lost, false ministers got up, false apostles got up,
false prophets got up, and reigned in their stead: my sheep`'s clothing you have had,
wolves you have been, thorns and thistles your earth has brought forth,
has lain like a wilderness unploughed up, amongst whom are so many names, and horns,
setting up your inventions, but inwardly ravened, and apostatized, so the witness buried,
in you who are whored from it, and in the fornication.

But the rod is over you which must rule nations, trumpets sounding and sounded,
the just will rule, the Lamb will have the victory; woes,
woes and miseries are out-going upon all the heads of the wicked,
the judgments are come upon the world, the day of glory is appearing, and hath appeared,
the throne and the sceptre that is everlasting is come and witnessed,
and set over the world,
which shall answer that of God in every one who has ravened from it,
and all gatherings upon the earth from that, shall be broken,
and it shall answer the just in every one.

G+++.+++ F.
