== The Lamb`'s Officer / Is Gone Forth with the Lamb`'s Message

[.heading-continuation-blurb]
Which is the Witness of God in all Consciences,
to call them up to the Bar, the Judgment of the Lamb, in this his Day which is come.
To all the Parish Clerks, Vicars, Curates, and Professors in England, Ireland,
and Scotland, and elsewhere in the whole Christendom;
for you all to come up to the Lamb`'s Bar, in this his Day,
to see if they can stand before the Lamb to plead their Cause, Guilty, or not Guilty,
in this his Day, who have had the Scriptures, but out of the Life,
which they were in that gave them forth.--By G. F.

The Lord Jesus Christ is come to reign,
and his everlasting kingdom and sceptre is set up, and the bar of judgment,
and all are called to it, and he calls all up before it.
Now Christ said false prophets should come, Matt. 7:24. and antichrist,
which should have the sheep`'s clothing, but inwardly ravening wolves;
this he spoke to his disciples,
and before their decease they did come, 1 John ch. 2. ch. 4.
and they went forth from them; and in the Revelations it is written,
all that dwelt upon the earth went after them, and the dragon made war with the woman,
and she fled into the wilderness, the true church,
and the man-child was caught up to God, and the dragon gave his power to the beast,
and the beast made war with the saints, and overcame them,
and killed them that kept the testimony of Jesus, the spirit of prophecy:
so here they killed the true ministry, and the woman fled into the wilderness,
the true church, and the man-child caught up to God;
and then power was given to the beast over all kindreds, tongues, and nations.
+++[+++Mark,]
And all the orthodox men, the original, the beast had the power to kill the saints,
and suffered the original, the tongues to stand; the orthodox men so called,
that have the scriptures in three or four languages, that had the sheep clothings,
these inwardly ravened from the spirit of God,
and turned against them that had the spirit of God, and killed them; and then the whore,
the woman, the false church got a-top of the beast, who had power over all kindreds,
tongues, and nations, who had his names, marks, horns, and images,
and they gave their glory and honour to the beast,
and the nations drank this whore`'s cup, this false church, this woman,
and she corrupted the earth; and the kings of the earth drank her cup of fornication,
and she corrupted the earth, and she made the inhabitants of the earth drunk;
and this whore sits upon the waters, and the waters where the whore sits, are peoples,
and nations and multitudes, and tongues, and she drinks the blood of the martyrs,
prophets, and saints, and so killeth the true ministers; this false church, this whore,
and false woman, suffers the tongues to live under her,
the orthodox men so called the original; and John calls them waters,
the pillars of her church.
Now this whore went from something, she went from the apostles`',
got the sheep`'s clothing, inwardly ravened, and went into the world,
as the Jews which went from the law of God among the heathen, they whored,
and so all nations drank the cup of fornication, the kings of the earth, and the nations,
being unmarried to Christ.
And again, the judgment of this great whore should come; for as Cain,
when he had killed the just, then he built a city;
this great whore that was on the beast, that had the dragon`'s power,
that killed the saints and killed the just, and killed the prophets, and witnesses;
and the true church, when the woman fled into the wilderness,
and the man-child was caught up to God, then this great whore, this false woman,
false church, this great city was built, and all nations drank of her cup,
and the kings of the earth drank her cup of fornication,
and all nations have drank her cup of fornication,
that have drank the blood of the saints.

Come now, priests, guilty, or not guilty; the Lamb and the saints shall have the victory,
the judgment of this great whore is come,
and the bride and the Lamb`'s wife is witnessed.
Priests, as I said before, guilty or not guilty, now you are come before the bar,
are not you the tongues that the whore sits upon, which John calls waters,
who are the orthodox men, and boast of the original, having the sheep`'s clothing,
which have the scriptures in three or four languages.
Have not you been standing, when the martyrs`', and prophets`',
and saints`' blood hath been drank?
And did not you stand in the day of the beast`'s power, when he killed the saints,
and made war with them, the true ministers?
Had not he power over all kindreds, tongues and nations,
when the true ministers were killed?
Was not your original Hebrew, and Greek, under the beast`'s power?
And hath not he power over that original?
And was that ever called the original among the saints that the beast killed,
and that the whore drank the blood of?
And did not you shelter under the beast`'s power, and the whore`'s,
when the martyrs`' and the prophets`' and the saints`' blood was drank?
did not you turn from the dragon to the beast, after the beast to the whore?
and had not the beast power over the tongues, orthodox men, and the original?
Come, guilty, or not guilty?
And do you not say the church of Rome is the whore?
And from this whore, the church of Rome, have you not gotten tithes,
and Easter reckonings, and midsummer dues, and glebe-lands, and mortuaries,
and offerings?
And have you not drunken this whore`'s cup?
Guilty, or not guilty?
Must not you drink the cup of the indignation of the wrath of the Almighty,
that have drank this whore`'s cup, since the true woman went into the wilderness?
And come, priests, did not the whore set up your mass-houses with the cross a-top of it,
with their pictures and bells, and call it holy ground, where it stands,
and name them by St. Paul`'s, and St. Peter`'s, and St. Michael`'s, and St. Gregory`'s,
and St. Austin`'s? Come, priests, have you not drank the whore`'s cup here?
Is not this the whore`'s cup?
Guilty or not guilty?
If guilty, thou must drink the cup of the indignation of the wrath of the Almighty.
And come, priests, did not the whore set up your schools, and colleges,
this false church, whereby you are made ministers,
and gave them the names of Trinity college, Jesus college, Emanuel college,
where you are made ministers, since the true church went into the wilderness?
And here have you not drank the whore`'s cup?
Guilty, or not guilty?
Come, priests, answer: and did not the whore set up all these things,
and the beast that killed the true ministers, martyrs, prophets, and saints,
by the dragon, and beast, and whore`'s power,
since the true church went into the wilderness, true ministers killed,
man-child caught up to God?
And are not you here found amongst them in the same power, drinking the whore`'s cup?
Answer, are you guilty, or not guilty?
And was not this whore of Rome, the first author of preaching by the hour-glass,
funeral sermons, ten shillings a sermon, twenty shillings a sermon,
ten groats the grave and mortuaries, and two hundred pounds a year for preaching?
is not this of the whore of Rome`'s cup?
And have you not all drank it?
and do you not drink it daily?
are you guilty, or not guilty?
(which have been set up since the true church went into the wilderness.)
Did not the church of Rome first ordain the Jesuit`'s tribe,
the order of black-coats?
and have not you of their colleges followed their example, and drank off her cup,
and gone in the way of the Jesuit`'s tribe, black-coats?
are ye guilty, or not guilty?
and was not the whore of Rome the first setter up of sprinkling
a little water upon children`'s faces for money,
and churching of women for money?
and have not you drank this cup?
Come, priests, are you guilty, or not guilty?
and was not the whore of Rome the first setter up of bells, calling people together,
and christening of them, and going processioning, and setting up all your crosses?
Was not the whore of Rome that false church, since the woman went into the wilderness,
the setter up of all these things?
and have not you priests and professors, and magistrates and rulers, and people,
drank of this whore`'s cup?
Are you guilty, or not guilty?

Now you are come before the bar of the Lamb, and his throne, and the bride,
the Lamb`'s wife is come,
the true church which was before and in the days of the apostles.
Was not swearing, and oaths set up since the days of the apostles?
And Christ in the flesh, who said, swear not at all, for they that swore,
came into the condemnation; for the oath in the law ended the sin,
and put an end to the strife, and the sin: and Christ the oath of God,
blots out the sin and transgression, and ends the strife, and reconciles man unto God,
and saves from sin, and redeems from the earth, and brings peace on the earth,
and good-will towards men; so he makes an end of sin.
Now the man-child being caught up unto God, and the woman fled into the wilderness,
and the prophets, and martyrs, and saints killed by this beast; and the whore,
and the false prophets, beast and antichrist gets the sheep`'s clothing;
so hath not all this swearing since Christ, been set up by the false church,
the church of Rome?
And have not ye priests, rulers, magistrates and people, drank this whore`'s cup,
this false church, and forsaken Christ`'s command, and the true church,
which saith swear not at all, as in James: are you guilty, or not guilty?
Have you not drank the whore`'s cup,
and so will fine and imprison them that will not swear?
is not this the whore`'s cup?
And have not you drank of it?
are you guilty, or not guilty?
Now you are come before Christ, who said, swear not at all;
the true church was far off of fining and imprisoning people for not swearing;
Christ and the true church, but on the contrary,
gave them a command that they should not swear, and gave them an order what to say;
whatsoever was more than yea yea, and nay nay, was evil; and the apostle follows it,
and saith, condemnation followed the swearers, saying, above all things, my brethren,
swear not at all, so are not ye the false brethren, the false church,
since the true church fled into the wilderness, and true ministers killed,
which hath drank the blood of the martyrs, prophets, saints and apostles,
and so swearing is set up by the false church, the church of Rome, not by Christ,
and his apostles?
And have you not drank this whore`'s cup?
Are you guilty, or not guilty?
(all people, rulers, magistrates, and priests in all nations,
that will fine and imprison men that will not swear,
and break the command of Christ) and will not the tongues say, you must swear,
which the beast and the whore hath power on, that drank the saints`' blood,
which hath told the world they are orthodox men, that have the original;
but in the spirit of God you are all comprehended: were not all your tithes, oblations,
obventions, glebe-lands, your tythe-herbs and eggs, and mints, and sage, and rue,
and beasts, and doves, and tythe-fish and fowls, and tythe-corn and hay, and wool,
and pigs, and chickens, and smoke-penny, and plough-penny, gardens and bees, and apples,
and plumbs, and all other tithes?
Was not this set up by your mother-church at Rome, which you say is the whore?
And why do you rail against your mother from whom you have such an inheritance,
and call her whore?
But it is true enough, though you are ill-bred children,
to clamour against your mother so; for was not she the setter up of all these things,
the whore of Rome?
Come, priests, impropriators, answer, are you guilty, or not guilty?
Who must drink the cup of the indignation of God?
The guilty, who have drank the whore`'s cup;
for the true church witnesseth the end of the first priesthood, his temple, and tithes,
and among the apostles there was none, who was the true church;
but since the church fled into the wilderness, you set up these things,
and killed the true ministers, and apostatized from the church, and so set up tithes,
who have the sheep`'s clothing, but out of the sheep`'s life;
and now is the judgment of this great whore come, and the Lamb, and the bride is known,
and come; and do you not think he will not reward you that have drank her cup?
For you all know tithes are of the whore`'s cup; and have not you all drank it, priests,
and impropriators, and others?

Nay, come, priests, have you not cast many into prisons,
and hauled them before your courts, and took treble damages,
and almost thrice treble from some, and cast them in prisons until death?
and what abundance you have in prison this day,
because they will not give you the whore`'s cup, therefore you will have their lives.
Are you not guilty here before the Lamb, and stand guilty before the bar,
and to have the judgments and plagues poured forth upon their heads?
and was not that the whore of Rome that drinks the blood of the saints, that whips,
imprisons, and kills, and banishes, and causeth to be hauled out of the synagogues,
and prisoned, and put in the house of correction, and persecutes from city to city?
And have not you drank this whore`'s cup at large, and drank the blood of the saints,
and prisoning until death, and bruising, and knocking them down in your steeple-houses?
Come, priests, magistrates and people, are you guilty, or not guilty,
in this the Lamb`'s day, that are brought before his throne?
And hath not this killing and beating been by the dragon, beast, and false prophet,
and hauling out of their synagogues and assemblies, and killing true ministers, prophets,
and apostles; and the woman fled into the wilderness, and the man-child caught up to God,
and the beast had power over tongues, and the whore sat upon the tongues,
which are waters, your original, orthodox men?
and were not they the inventors of your schools and colleges, and setters of them up;
your natural schools of learning, and tell people that is the original?
and have not you drank the whore`'s cup, and followed the beast in this?
Are you guilty, or not guilty?
Answer, now you are come before the Lamb`'s throne, and speak, guilty, or not guilty?
And was it not among the apostles, that if any thing was revealed to any that stood by,
the first should hold his peace; and they might all prophesy one by one,
that all might learn, and all be comforted; for God was not the author of confusion,
but peace, and the spirit of the prophets were subject to the prophets;
and since the true church fled into the wilderness,
and true ministers and prophets slain by the beast, dragon, and great whore,
doth not the order of the true church set you all in confusion, and cry, he disturbs me,
take him away, magistrates;
and cry for a law against them that practise the order of the true church;
are you not all guilty here?
Let your stocks, and prisons, and houses of correction testify it;
and whether or no this has not been the whore`'s cup which you have drank,
and all the blood which hath been shed about religion, church ministry,
and worship in the whole Christendom?
and whether or no this is not the whore`'s cup and whether you have not drank it?
Are you not guilty here?
And whether or no the church of Christ did any such thing amongst the apostles,
before she fled into the wilderness,
and whether or no all the martyrs and prophets which have been slain,
since the church fled into the wilderness,
have not been by them which had the sheep`'s clothing, which are inwardly raveners?
and whether or no you have not drank this cup?
And whether or no this was not the whore`'s cup, the church of Rome, your mother?
And whether or no you must not drink the cup of the
indignation of the wrath of God Almighty?
And are you guilty, or not guilty?
Come, answer me before the Lamb`'s power, throne, and dominion.

And when the true woman was fled into the wilderness,
the kings of the earth drank the whore`'s cup; would they not make all nations to bend,
to drink the same cup, so by that means came all nations to drink the whore`'s cup;
so as the apostles had gone into all nations,
the whore`'s cup also went into all nations, false prophets, beast, and antichrist,
and killed the saints, prophets, and true ministers;
and are not you guilty in this thing, ye kings of the earth, and of the nations,
who took the inwardly ravener`'s cup, who had the sheep`'s clothing,
worrying and tearing the lambs?
Did ever lamb`'s and sheep tear wolves, and worry beasts?
And so you that prison, that whip, that burn, that cut off ears, that banish,
that prison until death, are not you the wolves in sheep`'s clothing?
And so the antichrists, and false prophets, the dragon and the beast in his power,
and the whore`'s cup, of the beast that drank the blood of the martyrs and saints,
so are you not guilty all in this, where these actions are found?
Whose fruits declare in your jails, you not to be the sheep,
but the wolves in the sheep`'s clothing, the inwardly raveners;
and hath not all this hanging men for cattle, and for money, and the creatures,
when they should have restored, or been sold for their theft,
been set up since the days of the apostles,
when you should have let them live to restore, or been sold for their theft,
that they might have laboured in the thing that is good?
And are you not guilty in this?
And act contrary to the law and gospel.

Well, come, priests, are not all you who have been called of men master,
(and you love to have it so) and your salutations in the markets,
and chief seats in the assemblies, when Christ saith to his disciples, be not ye so;
and go into all nations, teaching them to observe all things that he commands them?
Is not all these things got up since the woman fled into the wilderness,
the slaying of the prophets and saints, all these things set up by the beast, whore,
and dragon?
and have not you drank this whore`'s cup,
and taught people that they should call you masters,
contrary to Christ`'s command and was not the church of Rome the first setter up of it?
and have not you drank her cup?
are you guilty, or not guilty?
For where do we read of master Paul, master Timothy, master Peter, master John,
master Matthew?
And where did Christ or the apostles, or true church, preach by the hour-glass,
and no man might ask them a question in the time of the glass`'s running,
or going from the steeple-house, or coming to it, without six months imprisonment,
or being whipped?
And where did ever the church of Christ do so?
and have not you drank the whore`'s cup in this?
are you guilty, or not guilty?
and are you not guilty here again,
who must drink the cup of the indignation of the Almighty, who have limited the holy one,
and quench the spirit, which was not the work of Christ and his apostles;
for if any one ask you a sober question,
then to be satisfied you will prison him for a wicked malicious disturber,
and have him sent to the house of correction, and whipped.
Oh! poor satisfactions doth the priest here give to poor troubled people,
that are burdened and discontented!
So it is time for them to forsake them,
who get means and estates of people for that which is not bread,
and making a trade of the scriptures.
But come, priests, did not the whore of Rome give you the names of vicars, and clerks,
and parsons, and curates, and bachelors of art, and bachelors of divinity,
and all your orders of your schools?
Did not the whore of Rome give you these names?
And have you not drank her cup, and grown up by it?
Are you not guilty here again, drinking the whore`'s cup?
And hath not the whore, the false church, and false woman, given you these names,
since the true church, and true woman, went into the wilderness?
For where was there any such names among the apostles?
are you guilty, or not guilty?
Answer this, who are come before the Lamb`'s power, and day, in this his marriage;
and where was there any such names amongst Christ and the apostles?

And come, ye clerks, and parsons, and vicars, for the whore hath many garments,
and decks herself with many colours, as the beast had many names, and likenesses,
and colours; so you have many changings.
Why do you observe this Michaelmas, Christmas, and Candlemas, and Lammas?
Was not this of the whore`'s cup?
And have you not drank it, let all the nations witness it, how deep you stick in it,
what mass?
Christmas, Michaelmas, and Candlemas!
Curates, and priests, and clerks, and parsons?
Oh, cry you, we will change our names, we will be called ministers of the gospel; nay,
you can no longer be hid, now you are discovered, ministers made at schools,
Oxford and Cambridge, at the colleges;
and were not the papists the inventors of colleges,
and all these things before mentioned, the whore`'s cup,
which ye and all nations have drank, and yet drink of them daily, and stick in them,
and your people; and all your saints`' days, and your holy days,
was not all this the whore`'s cup, the abomination, which hath corrupted the earth,
and many so drunk with it, they can hardly endure to have these things cried against;
and such sports, plays, and drinking, and games, and excess are on those days,
and many of those days, the saints`' days, that they were killed on, and died on,
you feast on, and rejoice: this is the beast and the whore,
which makes merry over the witnesses, and sending their gifts one to another,^
footnote:[Rev. 11:7-10]
over the bodies of the saints, when they have killed them,
and make merry over them on the days they were killed; and having the sheep`'s clothing,
and killing, and prisoning, and whipping,
and banishing them that be in the same life that they were in,
which they were making merry over, and observing the days they were killed on,
with their sports, and their music, and their wassail-pots, and their pye-times,
and their Good Friday, and Holy Thursday, and their Shrove Tuesday.
How now, vicars, and priests, and curates, and parsons, whose cup have you drank,
and the people drinking now, and the professors, and the rulers of the earth?
Is not this of the whore`'s cup, the church of Rome, that false woman, that false church,
and all these things got up, since the true woman fled into the wilderness,
and the true church?
where was there any such thing among the apostles,
before the true church fled into the wilderness?
Come, are you guilty, vicars, curates, priests, clerks, and rulers, and magistrates?
Is not this of the whore`'s cup that you drink?
are you guilty, or not guilty?
and must not you drink the cup of the indignation of the Almighty?
and are not these, and they that follow such things,
such whom God spewed out of his mouth, which have deceived the nations?
for where was there such Christmas and Candlemas, and Trinity college,
and all these holy days amongst the apostles?
This hath been mystery, Babylon, the great city, like Cain`'s, that hath killed the just,
and yet observes the days the saints were killed on, (oh,
hypocrisy!) and are persecutors of the saints themselves, and gets the sheep`'s clothing!
Are you guilty, or not guilty?
Priests, and professors, parsons, vicars, curates, and clerks, and magistrates,
and people; have you not drank this whore`'s cup now,
who stands before the Lamb`'s power, in this the Lamb`'s day,
whose sceptre of righteousness is set up, who will judge you according to your works,
whose reward is with him, who will judge the world in righteousness?

And come up, priests, curates, and parsons;
was not the whore of Rome the first setter up of clerks to say amen,
and turners of the hour-glass, and readers of mass,
as the priest reads his sermons and notes?
Are you guilty here, priests?
Again, where were these clerks to say amen among the apostles,
and strain people`'s goods, if they will not give them money to say amen?
Come, are you guilty, or not guilty?
are not these the fruits of your mother church of Rome,
which things have been set up since the days of the apostles,
and the true church went into the wilderness?
Come up, priests, clerks, and vicars, and parsons, and curates to the bar of judgment;
where had you those names of sacraments, creeds, and abundance of such like,
which are from the pope of Rome`'s mass book?
And have you not drank the whore`'s cup here?
Are you guilty, or not guilty?
Was not the whore of Rome the setter up and observer of all these days,
May-day and Lady-day, and Whitsuntide, and Christmas, Michaelmas, Lammas, Candlemas?
Is not here the pope`'s order observed, and the whore`'s order observed,
and his authority established, and practised, and tolerated in all your almanacs,
and drank down, swallowed down; which all the vulgar people, and the priests,
and magistrates, and the courts called by the saints`' days,
set up by the authority of the whore of Rome; and for the keeping of them,
have you not all drank this whore`'s cup?
First, priests, and professors, magistrates and common people, are you guilty,
or not guilty?
Hear, you priests, and vicars, and parsons, are you not yet in the tribe of black-coats?
And are you not they that have deceived the nations, who have on the sheep`'s clothing,
and observe the sheep`'s days they have been killed on;
you have brought the people to that, but are of them which have killed the sheep,
and not brought people to the sheep`'s life, nor the spirit, nor the mind of the sheep;
nor to the life of Christ, the apostles, nor the prophets,
but you have drank the whore`'s cup,
as your practices and fruits declare throughout the nation;
as your calendars and almanacs declare,
observing the days that the saints were killed on:
and this hath been the work of the wolves in the sheep`'s clothing,
since the woman fled into the wilderness; so are not you guilty here?
and do you not cry guilty here before the Lord`'s presence, and the throne, and the Lamb?
and to judgment is your whore come, that woman that hath brought forth so many harlots,
which she hath scattered and spread over nations;
and now shall the Lamb and saints have victory, as the deceit hath had victory.

And now is the marriage of the Lamb come, the bride, the Lamb`'s wife,
the true church known again, and you and your mother judged:
and her flesh must be burnt with fire;
and you shall drink the cup of the indignation of the wrath of the Almighty,
poured forth upon you without mixture; and the man-child is brought forth,
which will rule all nations with a rod of iron;
and the everlasting gospel shall be preached again to all kindreds, tongues and nations;
as the deceit hath been over all nations,
and the apostles were to go over all nations before deceit came up,
and the deceit trod down the apostles`' work, the life, that which they set up,
and turned against it, and killed the ministers, and turned against the church;
and so got power over all kindreds, tongues, and nations: but now shall the beast,
false prophet, great whore, old dragon be taken, which has corrupted the earth,
and made the inhabitants of the earth drunk; the kings of the earth,
and corrupted the earth, with her fornication;
now shall she be taken and cast alive into the lake of fire,
and Babylon shall be confounded,
and the everlasting gospel shall be preached again to them which dwell upon the earth,
which is the power of God, whereby life and immortality shall come to light,
in which power of God, the gospel, is the mystery of the fellowship known;
and this shall go over all the deceit of nations, kindreds, tongues, and people;
and so shall truth go over all nations; the power of God, the gospel,
as it did in the days of the apostles; the same power as was in the apostles,
in which there shall be unity with their words, and with their lives,
and Christ in whom they end, and the marriage of the Lamb is come,
and the Lamb and the saints shall have the victory, who will kill with the sword,
and slay with the sword, which are the words of his mouth,
and the joyful days are coming.

Come up, priests, clerks, vicars, curates and professors to the bar:
are not all your carnal weapons that you persecute withal, of the whore`'s cup of Rome,
which hath been from the dragon`'s and beast`'s power, who hath killed the creatures,
and wrestled with flesh and blood?
And Christ said; he came not to destroy men`'s lives, but to save them,
who was the prince of life; and the apostle said, they wrestled not with flesh and blood,
but with principalities, and powers, and spiritual wickednesses, and rulers of darkness:
and it is said, Christ came to destroy the works of the devil, and the devil and death,
where he hath his authority, and destroys the sin that was in their flesh;
but doth not say, he destroyed their flesh, wrestled not with flesh and blood,
and so to bring the creature into the liberty of the Son of God,
(who is the redemption of mankind) and to destroy thee who art a destroying.
Now you, since the days of the apostles, and Christ in the flesh,
the church fled into the wilderness, who have destroyed and made war against the saints,
and killed them, and have wrestled with flesh and blood, and killed the creature,
and destroyed their flesh and blood; is not this the dragon`'s power, and beast,
and the whore`'s cup, and whipped, and beat, and abused the creatures, and burned,
and dismembered them?
Have you not drank the whore`'s cup here, and marred the workmanship of God?
Instead of saving men`'s lives, have destroyed them,
and instead of wrestling against spiritual wickednesses, and powers of darkness, whipped,
beat, and imprisoned the creatures.
How now, priests and professors, is not this the whore`'s cup?
Are you guilty, or not guilty?
Whom have you been married to?
Is not this the whore`'s cup, got up since the woman fled into the wilderness,
that drank the blood of prophets, martyrs, and saints, and tells the people,
Hebrew and Greek is the original; and hath got the sheep`'s clothing in those languages,
and persecutes and kills the sheep, and prisons, and whips them?
And where did the apostles say, that Hebrew and Greek was the original,
but the church of Rome?
Had not Pilate, the murderer, Hebrew, Greek and Latin, and set it a-top of Christ,
the life, and crucified him?
and hath not the whore of Rome set up her schools and colleges, to make her ministers,
and there the ministers, the orthodox men so called, have got Hebrew, Greek, and Latin,
the naturals, since the true woman fled into the wilderness,
and the man-child caught up to God?
And hath not this been the whore`'s cup you drank of?
And have you not drank the whore`'s cup?
Now the bride and the Lamb`'s wife is known; now you are come before his judgment bar;
are you guilty, or not guilty?
And the judgment of the great whore is come, and all her children;
and is not the original the word which was in the beginning before Pilate`'s tongues,
who set them a-top of Christ,
which the beast and the whore of Rome hath set up to be the original,
and all nations have drank her cup,
but who have their names written in the Lamb`'s book of life,
before the foundation of the world was?
(and this is from such.)

And hath not all your crying up sin, while men are upon the earth,
they must never be made free from sin; and is not this come from the whore`'s cup,
who pleads for a purgatory after death?
Come, priests, come up to the bar; are you guilty or not guilty?
Is not this doctrine come from the whore of Rome,
since the woman fled into the wilderness?
The apostle said, he was made free from sin,
and they spoke wisdom amongst them that were perfect; and he that is born of God,
doth not commit sin; and as he was, so they were in this present world;
and the blood of Jesus Christ cleanseth from all sin;
and the new covenant blots out sin and transgression,
and by the one offering perfects forever them that are sanctified;
and Christ was made manifest to save his people from their sin;
and the church of Christ is without spot, or blemish, or wrinkle, or any such thing;
and the work of the ministry was for the perfecting of the saints,
until they all come into the unity of the faith,
and unto the knowledge of the Son of God, and unto a perfect man,
and to the measure and stature of the fulness of Christ:
Now since the apostles and martyrs were killed, and true ministry,
and the church fled into the wilderness, do not you and your false church say,
that people must have sin while they be upon the earth, and so preaches up their sin?
And is not this the dragon`'s power which the beast got, and the whore?
And what good doth your preaching do, if they must have sin while they are upon the earth?
And what is your work to the people?
That doth not perfect them?
And have you not here drank the whore`'s cup?
Come up to the bar, answer, are you guilty, or not guilty?
And was not the work of the apostles for the perfecting the saints?
and had he not perfected some when he said,
he spoke wisdom amongst them that were perfect?
and is not your work to perfect none, that tells them they must have a body of sin,
and be in their sin while they are upon the earth?
And doth not that make them imperfect?
And so they can be but imperfect, who never come out, who hear you,
who are got up since the true church fled into the wilderness,
by that power that killed the prophets, martyrs, and saints, and whipped, and prisoned,
and banished them.
Are you guilty, or not guilty?
Answer it here at the bar; and priests, we will not here bid you hold up your hands,
and so you have cried up all the imperfection and sin,
and the body of sin while on the earth;
was not this the whore`'s cup which corrupts the earth with her fornication and abominations,
who is upon the beast that hath the dragon`'s power?
And so what can you cry up but sin; this fenced city, mystery Babylon, mother of harlots,
the great whore which hath been ruled by the dragon, and fenced by it,
and yet killed the martyrs and prophets, and saints, within her compass,
since this whorish woman, false church has got up, and hath enlarged her city,
since the true woman fled into the wilderness?
But now the man-child, the Lamb is come to reign, who makes war in righteousness,
and rides on the white horse, conquering and to conquer,
and the Lamb and the bride his wife is witnessed,
who will rule all nations with a rod of iron, he is come to make work with you,
and the Lamb, and the saints shall have the victory over the beast,
over the false prophet, over this whore, who will kill with his sword,
and slay with his sword, which are the words of his mouth,
and blessing and honour will be given to the King of kings, and the Lord of lords,
who is Lord Omnipotent, and everlasting.

And did not the beast who had the dragon`'s power
after the woman was fled into the wilderness,
who made war with the saints, and overcame them,
who then had the power over all kindreds, tongues and nations,
and they gave their honour to the beast, and the whore is on this beast,
and all nations have drank her cup,
and the kings of the earth which have drank the blood of the martyrs,
prophets and saints, and is not all this hat-honour, and hat-worship,
prisoning and fining, and raging if they had it not, is not this the beast, and whore,
and dragon`'s power, which have been over all kindreds, tongues and nations?
Was there any such things among the apostles,
and Christ and the true church before she went into the wilderness,
but by the inwardly raveners, wolves in sheep`'s clothing, false prophet and antichrist,
dragon, beast, and great whore, compelling all to worship, to receive his image,
his mark in their forehead, or the hand,
all that dwell upon the earth should worship him,
but whose names were written in the Lamb`'s book
of life before the foundation of the world;
What is this beast, honour and worship?
What is the thing he looks for, if it be not the hat, to bend and bow, and stoop to him?
Was not the beast, the whore, the first author of it?
Now here have you not all drank the whore`'s cup in the whole Christendom?
Hath not she given it you to drink, and have you not all drank it?
And will you not fine and prison those that will not do it,
and stand bareheaded before you?
and is not this the false church, the false woman, and her cry,
and the beast and dragon`'s authority?
Come up to the bar, priests; answer, are you guilty, or not guilty?
And professors, and teachers, and magistrates, and kings of the earth;
hath not this been since the true woman fled into the wilderness,
since the days of the apostles?
And did not the angel and John see her coming up,
who when he would have bowed to the angel,
did not the angel bid him twice see he did it not,
then why should mortals expect such honour?
And now in this you may see where you are fallen in your pride and arrogancy,
and your oaths and swearing was from your mother the pope, whose cup you have drank,
and fines and imprisons others that will not drink it.
And hath not your marrying with rings, and the surplice, and rails, and fonts,
and altars, and the sprinkling with rosemary and bays when you bury the dead,
hath not all this been of the whore`'s cup?
and have not you all drank it?
Now if you say you have laid away some of these,
how is it that you have not laid away all?
Now come, guilty, or not guilty?
And must you not drink the cup of the indignation of the wrath of God.

Come, priests, vicars, and curates,
do you not buy your gifts at schools and colleges for money,
and sell your gifts for money?
Are you not Simon Magus his brats here?
Guilty, or not guilty?
And do you not make merchandize of people through covetousness,
and teach for filthy lucre, and love of money,
and have pierced yourselves through many hurtful lusts,
and drowned yourselves through your pernicious ways, and have a form of godliness,
and deny the power, which hath caused the way of truth to be evil spoken of;
and the very ignorant people to cry against you, and the sober to be ashamed of you,
and made your names stink among the heathen that know not God, or Christ,
you that have professed him with your lips, and in your will-worship,
and feigned humility?
Come up, priests, to the bar, before the throne of the Lamb, are you guilty,
or not guilty?
Come, priests, and curates, and parsons, and vicars,
have you not sold your birthright for a mess of pottage, for a morsel of bread,
for a handful of barley, and earthly things?
And Esau-like, hunting up and down with his sword, to kill and slay the just Jacob,
and get great benefices, and cast him into prison, and would make him to bow,
when he is got past him; but now the younger is risen, and the elder shall be servant,
who has called you to judgment; and are you guilty,
or not guilty of these things that are charged upon you?
Come, priests and curates, parsons and vicars,
are you not they that will preach peace to the people, if they put in your mouths,
and he shall be a good churchman; if not, you will prepare war against him,
cast him into prison, haul him before courts,
make your names stink before the courts in the nation,
you will cast them into prison till death?
doth not the blood of many lie upon you, as in York jail, Lancaster jail,
Gloucester jail, Durham, Appleby, and other places?
Come up to the Lamb`'s bar, and plead your own cause, guilty, or not guilty?
And see how you can stand before the throne of the Lamb,
you that are not able to stand before the Lord`'s servants,
who are moved of the Lord to speak to you, but call to the magistrates to take them away,
and to whip them, to the house of correction with them: Come up, priests and vicars,
parsons and curates, are not you they that have borne rule by your means,
and take away your means and you will not bear rule over that people?
and are you not such greedy dumb dogs that can never have enough,
every one seeking for your gain from your quarter, and all looking for your own way,
and not after the ways of the Lord, who have told people you never heard his voice,
and so are they that God never sent?
Come to the bar of judgment, guilty, or not guilty?

And come, priests, vicars, and curates, and parsons,
are you not they that will not go without a bag,
and those which have taken the people`'s money for that which was not bread,
and the messengers of Satan, and his ministers of unrighteousness,
which Satan hath transformed himself into, that takes and will have money of them,
and means, whom you do not work for, and where you have neither plowed nor threshed,
and where you never planted, and have made the gospel chargeable?
Come up, guilty, or not guilty?
Answer for yourselves, and come up, priests, and curates, and vicars, and parsons,
are you not such as go in long robes, fashions and lusts of the world,
with your ribbons and points, and double cuffs, and wearing of gold rings,
in the lusts of the flesh, and pride of life, and the lust of the eyes,
which is not of the Father, but of the world, more like your mountebanks, and fiddlers,
and stage-players, than like unto sober men that preach the gospel?
Guilty, or not guilty?
Let the witness in all your consciences answer it,
which is now bringing you before the throne of the Lamb, which is his officer;
and come up, priests, and curates, vicars, and parsons, and professors,
have you visited Christ in prison,
or have you not been they that have caused him in his members to be cast into prison,
yea till death?
and must they go into everlasting punishment, that doth not visit him in prison?
And have not you cast him into prison,
and taken his means from him instead of visiting of him?
Have you not taken away the saints`' goods?
Come to the bar of judgment, are you guilty of these things or not?
Whither must you go to receive your punishment,
which you must have according to your desert?
Are you not come under the judgment of all the lives of the prophets, the life of Christ,
the lives of the apostles, in this the day of the Lamb,
in whom all the prophets and apostles end,
and found amongst all them that be out of the spirit of the prophets, Christ,
and the apostles, that have deceived the world,
(but could not the elect?) consider with yourselves,
for now are you calling up before the throne, and the bar of judgment, guilty,
or not guilty?
For now shall the false prophets, beast,
and dragon be taken and cast alive into the lake of fire,
and the judgment of the great whore come, the false church, and the false woman,
and now shall the Lamb and the saints have the victory; glory to the Highest,
and the everlasting gospel preached to them that dwell on the earth,
and the saints and the Lamb reign, who makes war in righteousness;
now is the day of your trial come, the Lamb`'s throne is set up,
and sceptre of righteousness held forth, which reaches over the whole world,
and comprehends the whole world, and all the state of mankind,
and now is the judgment of God come, and the man Christ Jesus,
whom he ordained to judge the world in righteousness, according to the gospel.

And are not you them priests, curates, vicars, and parsons,
which serve God with your lips, and call upon him with your mouths,
and your hearts afar off, being full of ravenousness, murder, and madness,
and persecution, and will drink the blood of the saints, who be contrary to you minded,
and deface and mar the creatures, which are the workmanship of God,
and yet make people believe Christ has sent you,
a company of disorderly men to mar the workmanship of God?
which is contrary to Christ and the apostles, who saved men`'s lives,
and wrestled not with flesh and blood,
but brought the creatures into the liberty of the sons of God, and said,
there was a glory of the first body, and a glory of the second;
now you that have destroyed creatures, and marred the creatures,
whipped and defaced them, and bruised them, have been in the dragon`'s power, beast,
false prophet, antichrist, great whore, and Jews, heathen, and Judas,
by your company with swords and staves, to haul before magistrates and high priests;
are you now guilty here, or are you not guilty?
Answer before the presence of the Lord God, and the Lamb`'s throne,
for now is your time and day wherein judgment is come nigh to you.
For is it like that all sober people should believe that
Christ should send forth men to mar the workmanship of God,
which pretend themselves to be ministers, and cause them to be marred?
Or is it like that any will believe that you are christians,
that will mar the workmanship of God about religion, church, ministers, worship,
and scriptures?
And is not the creature the workmanship of God?
And did not Christ come to destroy that which would destroy the creature,
and to save men`'s lives, and not to destroy them?
And did not the apostles bring creatures into the liberty of the sons of God?
And to wrestle with principalities, powers, darkness, and spiritual wickedness,
and not with flesh and blood, whose weapons were not carnal but spiritual,
and mighty through God.
