[#ch28, short="To the Magistrates of the Isle of Milita"]
== Some Papers Given Forth / To the Magistrates of the Isle of Milita

[.heading-continuation-blurb]
And to the Emperor of the House of Austria, and to all the Princes under him.
To the King of France, and to all the Powers that be under him; and to the King of Spain,
and lastly, to the Pope.--By G. F.

Friends,--Two women being moved of the Lord to pass towards Jerusalem, were stopped,
as we hear, by you rulers, who sent to Rome to the pope,
to know what you should do with them;
(the servants and handmaids of the Lord God,) And
why were you not worthy to receive them?
And why do you not own the apostles`' doctrine, which is to entertain strangers?
And what is this the end of your religion?
and why do you not own Christ`'s doctrine?
The Lord Jesus Christ, who is now come to reign, which bids to love enemies;
why do you send them to the inquisitioners,
who will stop the hand-maids and servants of the Lord?
Is this work like the true christians?
And is this doing like the apostles, and did you do in this,
like men that were in the wisdom of God, that had the mind of Christ Jesus,
and his spirit?
Where did ever the apostles do so, or Christ?
Or the true christians in the primitive times?
Why do you wrestle with flesh and blood, when the apostles said they did not?
Why do you act contrary to them?
why do you act contrary to the command of Christ?
(who hate enemies) as you pretend them to be your enemies, which be your friends.
Is not he a heretic, or a schismatic, that is erred from the true church,
the body of Christ, that hates enemies?
Why do you thus act contrary to Christ`'s commands, and the apostles`' doctrine?
Do you not manifest that you have but the form of godliness, and want the power,
did ever the apostles, or Christ, prison any, or put any to death about religion, church,
or worship, or any tradition, or compelling any to worship?
Had they any among them to force men by an outward law?
Was not the gospel preached, the end of the law of God,
and so the end of all evil men`'s laws and inventions whatsoever?
And are they preachers of the gospel,
that do not preach that which is the end of the law, and brings people to the end of it?
Are they not the persecutors that runs to the law, or their own inventions,
and doth not come to Christ that fulfils it?
How have ye made the world like a wilderness, and stained the earth by your persecution,
and inquisitions, prisons, and images, and destroying people, and drinking their blood,
of such as have been opposite-minded against you;
and this hath been since the true church went into the wilderness
(which was not an outward wood) since the apostles`' days
how hath this family of Christendom massacred one another?
How have they fallen out in the family amongst themselves?
when they should have loved one another, when they should have overcome evil with good,
when they should have loved enemies,
when they should not have wrestled with flesh and blood, but with principalities,
and powers, and spiritual wickednesses in high places, and rulers of darkness,
and brought the creature into the liberty of the sons of God;
and here is the spiritual weapons which the primitive christians warred withal,
but how hath the carnal weapons appeared in the hand almost, of every christian in name,
amongst which hath been the form of godliness, Christ`'s, the prophets`',
and apostles`' words;
whereby they have sheathed their carnal weapons in the bowels of one another, killed,
and slain, and tortured, burned, prisoned, and racked,
and put to death one another about their church, religion, worship, and ministry,
and teaching and tradition, and ordinances and sacraments as they call them.
Oh! how unlike the apostles, Christ, saints, and christians of old are you.
Oh! how have the spiritual weapons been wanting among you,
and the spirit of the Lord God, in which you would have had unity in the bond of peace,
whereby every one would have broken down the enmity, that which causeth it,
and have brought one another into the liberty of the sons of God,
and made manifest your spiritual weapons;
hereby would ye have come to live in the spirit, worshipped in the spirit,
prayed in the spirit, and in that had unity with God, the Father of spirits,
and one with another, and with the scriptures that was given forth from the spirit;
then should there have been unity in the family being in the spirit,
in which they all should worship God, in which the scriptures is known,
and God of whom they learned, that gave them forth;
but what a discord is there in the family of christians in Christendom! what a cry!
Heretics, schismatics, antichrists, errors, a whole family in confusion,
and setting up laws one against another, dividing the family,
putting one another to death, as heretics, blasphemers, schismatics.
Were these the weapons the apostles fought with?
Did they not preach the gospel, the end of the law, and priesthood, and temple,
altar and offering held up by a law?
And is not Christ the head of the church,
who hath all power in heaven and in earth given unto him?
Who saith, love enemies; and do you not hold up your religion, gospel, church, worship,
and ministry by a law which is invented, and statutes, and commandments!
Is this the bride, the Lamb`'s wife?
Or the beast, false prophets, and antichrist, and the mother of harlots,
(the false church,) which hath compelled, killed, and drank the blood of the saints,
and martyrs?
and have not you ruled in this posture, and garb, and wisdom that is earthly, sensual,
and devilish, since the true church went into the wilderness,
(of which Christ is head?) And must not they be taken, the beast, dragon,
and false prophets, and the judgment of the great whore, the false church come?
And the Lamb, and the saints, the true church his wife, have victory?
And is not his sword he killeth withal, the words of his mouth?
And hath not all your killing been with outward swords, with jails, inquisitions, racks,
and fires?
and so have you not been traitors to the Lord Jesus Christ, who saith love enemies,
overcome evil with good, and when they persecute you,
not that you should persecute again;
and Christ was persecuted and blasphemed by them that lived in error,
more than any man upon earth, who was the end of the law,
and he did not turn them to the Jews`' law,
which was yet standing before he was offered up to put them to death,
but rebuked the blind zeal of such that would have
had fire come down from heaven to consume people,
and told them he came not to destroy men`'s lives, but to save them,
and told them they did not know what spirit they were of:
no more now do they know what spirit they are of, that persecute men about religion,
church, and worship, and ministry, that slays and destroys men`'s lives,
and not saves them; they are not of Christ`'s mind:
and Christ did not use any law to compel and bind men to the worship of God in the spirit,
for the spirit of God (who worship in it,) binds down the wrong nature,
whereby they need not be compelled by the law, but come to live in the end of the law,
(who be true worshippers,) and this spirit, hearing what it saith, it brings to near God,
and learn of him, such comes to Christ, such are not compelled by an outward law,
to come to God, and Christ; but that brings to hear God, and Christ,
binds down that nature which occasions the law,
that comes upon them because of its fruits; so they that are come to the church in God,
the Father of Christ, are not compelled by an outward law,
they come to the end of the law, who come to the church that Christ is the head of;
so the church lives in the end of the law; the body of Christ makes free from the law,
and who comes to the body of Christ, comes to the church, and the head thereof is Christ,
therefore lay away your persecution, your jails, racks,
and inquisitions about your ministry, worship, and church,
and come into the power of the Lord God that comprehends the world,
and feels over the world to the beginning before the world began, Christ Jesus was,
who hath all power in heaven and in earth given him,
who is now come to rule and reign in his power, who is terrible to the wicked,
and the wrath of the Lamb is gone out against them,
and thousands there be living in his power, and are with the Lamb, the wonderful one,
the beginning, and ending, the prince of peace, prince of life, that slays,
that destroys the devil, the prince of darkness, the prince of the air,
the prince of the world, and saves men`'s lives.
So who comes into the power, into Christ`'s power,
which hath all power in heaven and earth given to him,
and have his mind to save men`'s lives, they shall know what spirit they be of,
and that they are contrary to this family of nominal christians,
who have manifested they have not the spirit of Christ.

And the mighty day of the Lord is coming upon all wickedness, and ungodliness,
and Christ is come to reign, who is the prince of life,
who will rule all nations with a rod of iron,
whose dread and power is to be sounded over all nations.

[.asterism]
'''

[.old-style]
=== To the Emperor of the House of Austria, / And All the Princes under Him

[.heading-continuation-blurb]
Friends, read this over, which is for your general and universal good,
and consider as you read,
and then you will see what hath been up and reigned since the Apostles`' Days,
and where you are, and what you act, and by what Weapons you hold up your Religion,
since the Apostles`' Days.--By G. F.

Friends,--There hath been a mighty breach in Germany, about religion,
and much killing and slaying one another,
and that is because they have been out of the patience, out of the life of the prophets,
of Christ, and the apostles, whose weapons were not carnal, but spiritual;
which life that was in Christ, and in the apostles, did not lead to do any such thing,
nor to kill men, but to save men`'s lives, not to war with flesh and blood,
and to use carnal weapons about religion, as the Jews did, which were not christians;
but the apostle saith,
(and thou mayest read his testimony that said it,)
"`they warred not with flesh and blood,
their weapons were not carnal, but spiritual,
mighty through God to the plucking down of strong holds, spiritual wickedness,
and rulers of darkness,
and to bring the creatures into the liberty of the
sons of God;`" for the devil went out of truth,
and tempted others out of truth to sin, and so came death.
And the devil, the strong man kept house, who hath the power of death,
and set up his works in men`'s hearts, that murderer,
and that yield their members to sin, and to unrighteousness, obeyed his will,
and murdered one another about their church, about ministry,
about their worship and religion; yea, murder one another about the prophets`',
Christ`'s, and the apostles`' words.
Now Christ,
who is manifested (which was glorified with the Father
before the world began) in the flesh,
to destroy the sin which is in the flesh, yet to save the man and the woman;
and manifested to destroy the devil`'s works, yet to save the man and the woman,
and through death to destroy the devil, the power of death, and death;
so a stronger than he is come to take the house, and take the possession,
and so truth comes to be known, Christ in you, who sanctifies the man, redeems the man,
and justifies the man to God: So doth not come to destroy men`'s lives, but to save them:
let the mind of Christ be in you, and the apostles that followed Christ, said,
they "`wrestled not with flesh and blood,
they did not kill the creatures:`" so all the wrestlers with flesh and blood,
and killing creatures, hath been learned from the devil, he was the first author,
and they have sprung from him; and such as Christ said should come, Matt.
7, and Matt.
24, "`Ravening wolves having got the sheep`'s clothing, but inwardly ravened,
false prophets, and antichrist:`" Now there is no false prophet nor antichrist,
but first he is inwardly ravened, and then he will cry, "`Lo,
he is here or there in the bread and wine,`" and
put the bread and wine in the secret chamber,
in the secret place, and say he is there, now these inwardly ravening wolves, antichrist,
and false prophets, which Christ said to his disciples should come,
and before the disciples deceased, they saw there were come, 1 John 2:4.
and they went forth from them, in the Revelations of John it is written,
all that dwelt upon the earth went after them,
and when they had gotten ahead in the world, they turned against the saints,
and them that kept the testimony of Jesus, and overcame and killed them,
and when he had overcome the saints and killed them,
then power was given unto the beast over all kindreds, tongues, and nations, +++[+++mark]
over the tongues, as well learned men as others, and then the cry was,
Who was like unto the beast, who is able to make war with the beast?
Then he sat up his names, images, lying signs and wonders.

Now here was the true church in the wilderness,
here were the saints and true prophets killed; and the beast had power over all kindreds,
tongues, and nations, +++[+++mark that,]
and read over the 12th and 13th chapters of Revelations.
Then the whore sat upon the beast which had the dragon`'s power,
and all nations drank the cup of her fornication,
and the kings of the earth drank the cup of her fornication, and she corrupted the earth,
and made the inhabitants of the earth drunk: and she sits upon the waters,
and the waters (where the whore sits,) and reigns over the kings of the earth,
are people, +++[+++mark,]
people are waters, and waters where the whore sits are nations, nations are waters:
and the waters where the whore sits are multitudes,
and the waters where the whore sits are tongues; and this is the great whore,
mystery Babylon, the mother of harlots; so here is the whore, this woman,
and all nations, and the kings of the earth have drank her cup of fornication,
and the kings and nations while they took this whore`'s cup,
could not be married to Christ; for the true church, the true woman,
was in the wilderness, and this whore has sat as a queen,
and has drank the blood of the martyrs, the prophets, and saints,
so killed the true ministers, and drank their blood.
The beast and whore hath power over tongues, and sits over tongues,
which they tell the world is the original,
and that they are orthodox men to open scriptures.
And why not the whore and beast to have power over their tongues,
as well as Pilate the murderer?
Who crucified Christ the just, and wrote a superscription in Hebrew, Greek, and Latin,
and set it upon Christ, as in Luke you may read.
And Babylon was the beginning of many languages, as in Genesis,
and now he that was dead is alive, and lives forevermore,
who was glorified with the Father before the world began, who was before Babylon was;
and he whom Pilate sat the tongues on, is risen, and is where beast, dragon,
false prophet, antichrist, great whore, mother of harlots, and mystery Babylon are not,
so the Lamb and the saints shall have the victory, and the beast shall be taken,
and with him the false prophet and the dragon, and cast into the lake of fire.
And the judgment of the great whore is come, mystery Babylon,
and they shall be cast into the lake of fire,
and shall be confounded and he burnt with fire.
And the marriage of the Lamb is come, and the everlasting gospel shall be preached again,
to all that dwell upon the earth, to all nations, kindreds, tongues, and people.
+++[+++Now mark,]
the tongues may say, (who have told the world they have been the orthodox men,
and have had the original) what, have we not had the gospel all this while?
I say no, they that went from the spirit of the Lord, and ravened from the spirit of God,
they went from the power of God, which is the gospel,
so hath this whore brought all nations on heaps, and the beast, false prophets, dragon,
and antichrist:
but now is the man-child brought forth to rule all nations with a rod of iron;
and the Lamb and the saints shall have the victory, and the beast, dragon,
false prophets, great whore,
and kings of the earth shall make war with the Lamb and the saints,
but he shall kill with the sword, and slay with the sword,
which are the words of his mouth.
And now is the marriage of the Lamb come, and the bride and the Lamb`'s wife known.
And all the killing (about religion, and church, ministry, and worship,) by fire,
by faggot, by rackings, inquisitions, by banishings, prisonings, and whippings,
hath been by the beast, whore, false prophets, inwardly ravening wolves,
who have ravened inwardly from the spirit of God;
and have not had the spirit of the apostles, nor Christ, who saved men`'s lives,
and warred not with flesh and blood, but with principalities and powers,
rulers of darkness, and spiritual wickedness:
and so these have warred against flesh and blood, and creatures,
like wolves which have had the sheep`'s clothing, this great whore Babylon,
mother of harlots, the false church,
which has ruled and reigned over the kings of the earth, since the days of the apostles:
but now shall she be confounded, and the loss of her children is come,
who has sat as a queen, and seen no sorrow; who has killed and slain,
whipped and martyred, and burnt and racked, and imprisoned, and all this righteous blood,
which hath been shed about religion, church, and worship, has been by the beast,
great whore, and mother of harlots, and the dragon, and antichrist, and false prophets,
inwardly ravening wolves, having sheep`'s clothing, but ravened from the spirit of God,
and so turned against them that had the spirit of God, and killed them;
and lost the spiritual weapons, and instead of warring with the powers of darkness;
and rulers of darkness, they warred with flesh and blood; so here is Cain`'s weapons:
and now with the power of God are they made manifest,
and instead of saving men`'s lives are destroying them;
and instead of bringing the creature into the liberty of the sons of God,
and instead of striking at the powers of darkness, and spiritual wickedness,
that captivates the creature, they stock, and whip, and burn, and imprison, and rack,
and hang, kill, and banish the creature,
instead of bringing the creature into the liberty of the sons of God:
so shows a quite contrary spirit than was in the apostles in their days.
And now is he redeeming and recovering things that were in the apostles`' days,
and now the gospel of God is known, the power of God,
and now is the mystery of the fellowship known,
by which shall all the mysteries and fellowships upon the earth be broken,
which are not in the power of God: and now vials, and plagues, and thunders,
and woes is coming upon the world, and the smoke of the bottomless pit hath ascended,
and the tormentings of this great whore is come in this the Lamb`'s day,
whose sceptre of righteousness is gone forth,
who will rule all nations with a rod of iron, and make war in righteousness.
There is a people come forth of the north that shall spoil Babylon.
And now this is the day of the Lamb`'s power,
and in this day of his power is the gospel going forth to all nations, kindreds,
and tongues, and people, that they may be ruled as with a rod of iron;
for they have been waters corrupt and drunken, corrupted with idols, images, relics,
running to graves, seeking the living among the dead, which had a check by the angel,
to them that did so, with a question saying, "`why seek ye the living among the dead,
he is risen,`" the life is risen, and many sit with him in heavenly places,
and the kindness and riches which the Lord showed towards the apostles, is now known,
and the age is come, and the gathering of people into unity,
into the power of the Lord God in the gospel, into the life which gave forth scriptures,
and to the breaking of the beast`'s horns, marks, and images.
Now a whore goes from something,
for when the children of Israel transgressed the law of God,
they played the harlot with other nations, the heathen;
so these inwardly ravened from the spirit of God, though they had sheep`'s clothing,
went out from the apostle, who had the spirit of God and got the world after them,
turned against them that had the spirit of God, and killed them; the whore did,
though they had sheep`'s clothing.
So among these inwardly raveners, which has sheep`'s clothing,
has all the blood been shed, who are a field of blood, about church, about religion,
and set up dead images, dead crosses, schools, and colleges, to make their ministers,
which went forth from the apostles, (set up tithes and temples) which were not of men,
nor by man, who witnessed the end of the first priesthood and tithes, Heb. 17.
the end of the temple and true offerings;
these went forth from the apostles into the world,
set up all their lying signs and wonders, killed, slew, and compelled to worship,
these has been out of the power of God, the cross of Christ, and out of the gospel,
which is the power of God, out of the image of God, and out of the word of God,
for these things were to continue, till the words of God were fulfilled.
Now is the fulfilling of the word of God, now is the earthquake known,
such an earthquake as hath not been since the foundation of the world.
And the mystery of iniquity shall be discovered,
and the true mystery of godliness is revealed, which doth discover it.
Glory to God in the highest, and the Lamb and the saints shall have the victory.
And now friend, prince, palatine, thou hast been moderate,
thy fame is come into England of thy temperance, and of thy moderation,
and sober carriage towards the Lord`'s servants, and messengers,
whom he is sending to all nations with the everlasting gospel,
and to preach the everlasting gospel to them that dwell upon the earth,
and happy are they, and blessed will it be to thee,
that dost not lift up a hand nor suffer thy servants to do so,
in this day of the Lamb`'s power, against the Lamb;
for now is his dread going forth to all the world, and all nations:
and his righteous sceptre shall be set up, and his kingdom is known,
where there is no end, and life and immortality is come to light through the gospel,
and a thirst is risen among people,
and they that thirst have of the water of life freely, and these worship not the beast,
and receive none of his marks, images, or names,
but has their Father`'s name in their foreheads.
And these are come out from the great whore, which has corrupted the earth,
and made the inhabitants of the earth drunk.
The inhabitants of the earth are drunk almost in every place, and the earth corrupted,
with images, and idols, and likenesses by this false church,
since the woman and true church went into the wilderness, and true martyrs,
and prophets slain, which is out of the life of the sheep, and the nature of them,
for never did sheep nor lambs worry dogs, nor wolves, nor beasts,
but they were as sheep among such.
And as Christ bid the apostles go into all nations,
so the inwardly raveners with sheep`'s clothing, beast, dragon, and whore,
has spread over all nations, and has brought nations into waters, Rev. 13.
having power over all nations, which has killed the prophets, martyrs, and saints,
and drank their blood, and overcome them, and the man-child hath been caught up unto God,
and the woman hath fled into the wilderness,
but now is the man-child brought forth to rule all nations with a rod of iron,
and the marriage of the Lamb is come, and the Lamb and the saints shall have the victory,
the dragon, beast, whore, and false prophet,
shall be taken and cast into the lake of fire,
and the Lamb and the saints shall over all have victory and dominion,
and the whore`'s flesh shall be burnt with fire, and the beast,
and the false prophets cast into the lake of fire, which burns with brimstone,
and these had the sheep`'s clothing, but quite out of the life of Christ, prophets,
and apostles: so have brought all into heaps about words,
and this is in whole Christendom.
And now friend, this is the day of thy visitation, now thou hast time, prize it,
and keep in the fear of the Lord God, and his counsel, and his dread,
that thou mayest grow in wisdom, which fear of the Lord is to depart from sin, and evil,
and the beginning of that wisdom by which all things were created,
with which wisdom thou mayest come to be ordered to the glory of the Creator,
and with which wisdom thou mayest order all things,
that be under thy dominion to the glory of him that created them,
and with that thou mayest come to answer the principle of God in every man, that is just,
holy, good, and righteous, and then with that thou wilt be a good savour unto the Lord,
and a good savour in the hearts of all people that be under thy dominion: and power,
life, wisdom, counsel, and instruction will be with thee, of the Lord God Almighty,
and thou shalt have his blessing:
for the power of the Lord God of life is spreading itself over all nations,
over all the world, and his salvation is known, and knowing, yea,
to the ends of the earth, the great, the mighty power of God, Christ Jesus,
the mighty prince of life,
who is now come to rule and reign himself in the hearts of people,
whose dread and terrors shall take hold of all nations, and the Lord alone will reign,
and the kingdom of the most high is ruling in men, and will rule in men,
and the tabernacle of God is now with them.
And now, friend, the ground and cause in the whole Christendom,
since the days of the apostles, that they have been in heaps, is,
they have had scriptures, but not the life that they were in that gave them forth,
the spirit of God, in which spirit is the unity with God, and with one another,
and no killing and slaying of men and women, but with the powers and rulers of darkness,
and spiritual wickedness, with that the spirit of truth wrestleth,
and brings creatures into the liberty of the sons of God,
and knowledge of the scriptures, and prophets`', Christ`'s, and apostles`' words,
the saints`' words, Christ`'s commands and ordinances,
but Christendom have torn one another about the sheep`'s clothing,
which all Christendom hath had, and have inwardly ravened,
and are broken all into heaps about them, and striving about the words, that is,
while they have wanted the word Christ Jesus, which is called the word of God,
in which the prophets doth end, the first priesthood doth end, the temple,
the circumcision, the first covenant doth end, and apostles`' words,
the scriptures of truth, they all end in Christ the word, which was in the beginning:
so the word reconciles men to the scriptures,
for they all fulfilled (the Lord,) which was in the beginning,
before scriptures were given forth, and it reconciles to the just men`'s spirits,
which gave forth scriptures, who all learned of God,
and received the spirit which spoke them forth; so the word of reconciliation,
which was in the beginning, hath been wanting; the word of power and life, yea,
since the days of the apostles:
but now is made manifest to hammer down all this wickedness,
to cut down all this wickedness, and to burn it up.
And again, friend, be tender to all that fear God,
and give a charge to all that be in office under thee, to be gentle,
and easy to be entreated, this shows the wisdom which is from above,
that is a mark and a sign of it.
And seek the honour which is from above, and keep above the honour which is below,
that God will stain, and be of Solomon`'s mind, who said,
"`before honour is humility;`" and be of Moses`'s mind, who said,
"`would to God all the Lord`'s people were prophets;`" and of Joel`'s mind, who said,
"`that sons and daughters should prophesy;`" and of Peter`'s, that witnessed it.
Now this power, this life, is witnessed and spreading itself abroad,
is fulfilled and fulfilling that promise, which saith,
"`He will pour out his spirit upon all flesh, and his sons and daughters shall prophesy,
and the children of the Lord shall be all taught of the Lord,
Isaiah`'s prophesy is fulfilled and fulfilling:`" and Christ said to the Jews,
it is written, "`They shall all be taught of God,
and every one that hath heard and learned of the Father, cometh unto me, their Saviour,
their captain, their way to God,
and they hear him;`" and such witness Moses`'s prophecy fulfilled, who said,
"`a prophet like unto me will God raise up, him shall ye hear,`" so the prophet is heard,
who is the salvation to the ends of the earth, as God said,
"`I will give him for a covenant, and to be my salvation to the ends of the earth,
to enlighten the Gentiles, the heathen, and a covenant to the house of Judah,
and to the house of Israel,
(which are called the people of God,) and I will put my laws into their minds,
and into their hearts, that had them without them before.`"
And now many witness this leader, this covenant of God, the light to the Gentiles,
who saith to the prisoners "`show yourselves forth;`"
and many have showed themselves forth,
and see over the dark night of apostacy,
to the life which was with the Father before the world began, glory be to the Highest,
Christ Jesus, who doth enlighten every man that cometh into the world,
that all through him might believe, and every man that is come into the world,
being turned to the light which Christ hath enlightened him withal,
they are turned to their Saviour Christ, from whence the light comes, the second Adam,
which blots out the deeds done in the first Adam`'s nature,
in the transgression drove from God: For when man transgressed the command of God,
the law was added because of transgression upon the man,
and there stood the first covenant of works, and all temples, tithes, priesthood,
and offerings, which must change: but the second covenant, the everlasting covenant,
it comes within the man again, and there is circumcision in the man, in the spirit,
and man`'s body comes to be the temple of God; and this ends the first priesthood,
the everlasting priesthood ends all the changeable,
and brings people to see the beginning, that doth end all the changeable types, figures,
and shadows.
And now friend and friends, (that be about thee,) do justice, love mercy,
and walk humbly with God; this is that the Lord requires,
and that will be of good report to thee,
come to know the seed of God in thy own particular, and your own particulars,
which is the heir of the promise of God, of life, of the power of the world,
where there is no end: for every one of you, as is said before, being enlightened,
having a light from Christ Jesus, the Saviour of the soul,
every one being in the light which hath enlightened them, they be in Christ,
and they come to feel the witness in their own selves,
and a spring of life springing up in them unto eternal life.
Now they that do not believe, are with the light condemned.
Friend, read this over, this is for thee, and thy council, from a lover of thy soul,
and all your souls`' eternal good, and for the establishing of righteousness and peace,
by the mighty power that feels and fathoms the whole world,
that gives to feel dominion before the world was, in this the day of the Lord`'s power,
which is now made manifest among his saints, and elect.

Let this be sent to the Palatinate, and to Holland, and into Hungary, and into Poland.

The Lord has an elect royal seed to be gathered in those parts.

G+++.+++ F.
