== To the Pope.

[.heading-continuation-blurb]
Friend, read this over, and the sad Lamentation that is over thee thou mayest behold,
how that thy field is afield of blood, and how that thou art naked,
thy Emperors and thy Princes, from the Spiritual Weapons, and the Armour of God,
who hast had the Form, but out of the Power since the Apostles`' Days, for yet thee,
nor any of thy company durst ever adventure a meeting
in the field with them that have the Spiritual Weapons,
(as in the book called the [.book-title]#Papist`'s Strength Broken,# may be seen.)
Therefore, they, and all the Emperors and Princes, and thyself,
having not the Spiritual Weapons, nor the Armour of God,
ye have set up your Inquisitions, your Racks, your Tortures, your Prisons,
your Banishments, and this showeth you have no Rule nor Government by the Power of God:
Therefore read this over, that you may see what you are got up into,
since the Apostles`' Days, and how you have killed and mangled,
martyred and tortured, which is not the work of a true Christian, but to love Enemies.--By G. F.

Friend, and friends, innocent blood hath long cried for vengeance to the Lord,
the earth almost swims with innocent blood, and the cry of it is heard,
your frozen profession, your cold winter images set up in your streets,
and the Lord God of power, of dread, of heaven and of earth, will be avenged on thee,
and you all; his day is approaching, his day is drawing nigh at hand on you all,
his everlasting arm, his power is stretched over you, and gone beyond you,
the Lord God is angry with all your idol images, your pictures, your jewels, your beads,
your nunneries, all your several orders you have set up in your wills,
and your will-worship, and your several orders of feigned humility;
you have been fed like fat hogs in dens, you great and rich cardinals and pope,
and seeing that thou wouldst not receive the Lord`'s messengers,
but threw them into prison, and into your inquisition, whose blood lies upon you,
it may be ere long the Lord may give you a visit another way, for his dread is gone out,
the zeal of the Lord is kindled against you, he that toucheth his,
toucheth the apple of his eye, and he shall never prosper;
the dread of the Lord is coming upon you, and his mighty power ere long,
who hath stained the earth and corrupted it with your images, but now is the Lord risen,
that will plead with you, you have drank the blood of the saints and martyrs;
now must you have blood to drink, for there is that gone forth that is against you,
and you shall not be able to stand before the Lord, before his power,
the mighty God of Jacob, God will break down your images, and your nunneries,
and dethrone the pope of his power,
(the Lord alone will reign,) for he hath been before the whore, the false church,
got up since the true church went into the wilderness,
and the man-child caught up to God, but now is the judgment of the great whore come,
and the Lamb, and the saints shall have the victory, the Lamb`'s wife is known again,
and the cry is, and the voice is, come out of her, that hath been the whore,
that hath drank the blood of the saints.
Oh blood!
The fields are sprinkled with the blood of the innocent, and you are the field of blood;
now is the Lord coming to take vengeance upon you,
and his hand is stretched over your heads, his power is gone over you,
and with that he will rule you and smite you under,
and bring you lofty ones from your seats, and abase your pride,
and take the glory to himself, and deface your glory and honour;
you have been the cage of unclean birds, and the locusts, that have gone in swarms,
that come out of the bottomless pit;
the Lord God in his mighty power is entered into all your quarters,
your wickedness hath grown to the full, your time draws to an end,
that the Lord God will be revenged on you;
now are you come into the remembrance of the Almighty,
your will-worship will the Lord destroy,
all your feigned humility will the Lord break down, all your invented images, pope,
cardinals, orders, nunneries, pictures, relics whatsoever, will the Lord break down,
for you are as a barren wilderness; Oh,
you have long cumbered the ground! you have long stained the earth,
and the man of sin hath long reigned among you, and Cain`'s weapons,
with them have you slain many that have been contrary to your minds,
you have been the great city, with Cain`'s weapons you are fenced,
thou hast reigned over the kings of the earth, the false church, the whore,
since the woman went into the wilderness, as thou mayest read in the Revelations,
the Lord is come to break you to pieces, with his mighty power,
and to lay your city level, and his power is entered among you,
for how much blood (which is unmeasurable here to be measured,)
have you slain and drank since the days of the apostles,
and made yourselves drunk with it?
But now is the indignation and wrath of the Almighty come, and coming upon you, and thou,
pope, must feel it, the Lord God of heaven and earth is come to rule and reign,
whose kingdom is without end, in whose hand all kings are as the waters, and thou,
and thy images, and relics, and cardinals, and the several orders,
they are but as the relics, and the potsherds; the mighty God is risen,
tremble before him, for he will abase you, and go over you all in his mighty power,
for the blood of the innocent lies upon you, who have laid aside the scriptures,
and the exhortations in them, which is to entertain strangers,
and you prison them till death, and you burn and rack people,
and this is your church`'s authority, for the whore hath drank the blood of the saints,
apostated from the true church, and set up images, and idols,
(the true church bid keep from idols,) and departed from the true faith,
and have taken the glory and honour to you, that belongs to God,
you are gone into Cain`'s ways, (murderers,) and are out of Abel`'s;
you are gone into Balaam`'s way, for the wages of unrighteousness,
you are as the devil that John speaks of, that casts into prison,
and you are them that have a name, but are dead,
you are the blasphemers that said they were Jews, and are not,
you have taken the honour and glory to your ownselves,
and compel others to worship the beast, and the whore, but now is the cry gone out,
worship not the beast, come out of her, fear God and give glory to him;
now see your fenced cities broke down with the arm of the Lord God,
the power of the Lord God is going over your city to break it down, and you are as Cain,
that went from God, to whom the woe belongs, and plagues, and misery, and thunders,
and vials, and the earthquake shall be known to shake down that part.
Are not you ravening wolves that set up your images, earthen images, crosses, and temples?
and the mystery of God is revealed, that discovers you all, and revealing,
and the Lord God will confound you, who have trusted in your graven images,
your molten images, who have deceived the world, made havoc, shed blood every way,
and flung your swords about you, set as a queen that sees no sorrow,
but now desolation is coming upon you, now it is near the door,
now shall the power of the Lord God go over you like reeds,
for you and your relics are as pieces of clay, as potsherds, and pieces of dusty doth,
with dark Cain`'s spirit, and wolfish spirits, that Christ said should come,
that went forth from the apostles, and the World is gone after you,
but the Lord God is risen, and the Lamb,
(and the saints shall have the victory,) and he shall kill with the sword,
and slay with the sword, even the word of his mouth,
who have been the cause of all bloodshed about religion, worship, and church,
and ministry, tremble thou pope, tremble, fear, and quake thou pope,
tremble you cardinals, tremble you Jesuits, tremble you priests,
tremble all you orders of monks, and friars, and tremble you papists of what rank soever,
for now is the power of the Lord God coming over you, now you shall be shaken;
and by whom shall you be shaken and dashed to pieces?
the living Almighty God will reign, who thunders out his power,
and hath uttered forth his voice, and hath sent his servants before to warn you,
for before the Lord God brings his judgments on a city,
he sends his servants to inform them, whom you have imprisoned,
and kept in your prison even to death,
the noise of which visitation of the Lord`'s servants is gone abroad,
who were sent to visit the pope, from the Lord God of hosts, of power,
of heaven and of earth, whom you have thus evilly entreated?
That the kindness of the Lord might be known to you,
before he hath brought his judgment and sword, and his plagues, and his woes,
that with his mighty thundering power you might be warned,
for by that he will break down your images, and pictures, and nunneries, and strike,
and break down your orders, and break down your fathership, your popeship,
and lay it in the dust, for ye have been the wolves, ye have been a wilderness,
and as wolves ravening up and down in the wilderness,
and made the earth like a wilderness, but the Lord God of power, of life,
of heaven and of earth will now reign and rule,
oh how have you cankered and cumbered the earth, and stained the ground!
Oh how is the Lord grieved!
Oh how is the Lord burdened with your filthiness
and pollutions! "`I will arise,`" saith the Lord,
"`I will avenge me of all my enemies,`" fear and dread shall surprise you,
and take hold upon you, and you shall become as a quivering leaf, as a shaking leaf,
the Lord hath spoken it, and his power will he bring over all nations,
and break you to dust, and trample you to powder, in this day of his glorious appearance,
and his majesty shines forth, and in his righteousness he reigns,
the Lamb and the bride is known, his wife is witnessed, he is going on conquering,
and to conquer; and the everlasting gospel shall be preached again to all kindreds,
tongues, and nations, and to them that dwell upon the earth,
for the beast hath had power over all kindreds, tongues, and nations, with lying signs,
and wonders, and hath corrupted the earth; and made the inhabitants thereof drunk,
which hath overcome, the saints, and killed them, and drank their blood,
and you have had the outside, the sheep`'s clothing,
but the sheep`'s life hath been wanting,
and you have been them that Christ said should come, Matt. 7:14.
which John saw was come, John 2:4. which went from the apostles,
which the world went after, and sat up your lying signs, and wonders, and miracles,
and your images in the world, (a cage of unclean birds,
the habitation of dragons,) the great city reigns over the kings of the earth,
who have been guided with the dragon`'s power, and the beast took it,
and the whore took it, the false church,
and since hath the true church and the woman been in the wilderness,
but now is come forth to rule all nations with a rod of iron,
and the saints shall have the victory, glory to God in the highest,
and the everlasting gospel shall be preached, as I said before, to all kindreds, tongues,
and nations, and to that the apostles were in, his people shall come into, and thousands,
and ten thousands witness it: and the arm of the Lord is spreading over the whole world,
the host of heaven shall be known, and the reapers, and they are going forth to cut down,
and the gathering together to the battle of the great day of God Almighty,
the fowls of the air shall feed on the flesh of captains, and nobles, and great men,
the mighty angel is going forth with the vials of the Almighty, pouring them out,
and the wrath of the Almighty is to be poured out without mixture upon you,
and that you must drink; the sharp glittering sword of the Almighty is drawn,
and hangs over thy head, thou pope, therefore call in thy Jesuits, priests,
and cardinals, and give up to the Lord when he calls, for he is coming,
he is nigh at hand, to throw down all your images, nunneries, pictures, crosses, jails;
deliver up all your arms, your carnal weapons,
for the mighty God of power is come upon you, and coming upon you,
and you shall not escape his arm; the Lord will plead with you in his power,
in his strength, in his might, and you shall feel his sword, (hand, arm, and strength,
and his threshing instrument;) which is drawn, which will hew you to pieces,
and you shall have no place to fly unto; you have been worse than the heathen,
you have been worse than the Jews,
you have made the name of a christian to stink among Jews and Gentiles, by your fires,
inquisitions, and cruel acts, your crosses, beads, and your nunneries,
you have been worse than the heathenish philosophers.
I will make you to know that I am the Lord, saith the Lord God Almighty,
who will stamp you to powder, and make you as ashes,
Cain`'s weapons shall not secure you, who are turned against them that are in the faith,
and would let them have no place among you:
now will the Lord God Almighty reign and rule, and of you take vengeance,
and be revenged on you his enemies, for his elect sake,
who by you have suffered since the days of the apostles, under your kingdom,
and your islands, and your nations, on you all will the Lord God take vengeance,
and make you as a shaking leaf, (as before,) whose dread, power, and authority,
and dominion over you all is set, the righteous sceptre over you all is gone,
and the bar of judgment to which you shall be called is set up;
you are ripe for the sword, for the press, to be trodden without the city;
his sword it is drawn to cut you all down, consider with yourselves what you have done;
since the days of the apostles, in this time, and times, and half a time,
since the woman hath been in the wilderness, and nourished and fed there of God,
and consider how unlike the apostles you have been, and the churches among them,
unlike Peter, unlike Paul, and having broached your traditions,
and call that your church, traditions set up by yourselves,
and so hath made the practices of the church of God,
and the commands of God of none effect, and thus deceived the world,
deceived the ignorant, and deceived nations,
but now shall the everlasting gospel go forth, and the power of God,
and you shall be taken, and the judgment is come, the beast and false prophet,
and the whore the mother of all harlots, and Babylon is confounded,
and the Lamb and the saints shall have the victory,
and the everlasting gospel shall be preached,
through which life and immortality shall come to light, in which the power of God is,
the unity and fellowship is, the mystery of the fellowship,
in the mystery of godliness is the fellowship that is everlasting, and the power of God,
the cross of Christ, instead of which, you have set up your stone, wooden,
golden and iron crosses, by your church authority,
which hath ravened from the power of God, the cross of Christ, but with the power of God,
the cross of Christ are you all judged, and your crosses, with the founders of them,
with all the rest of your lying signs and wonders, and over you is the power of God gone,
the cross of Christ that shall throw down all your crosses, nunneries, inquisitions,
images, your lying signs and wonders, and the mystery of God is now revealed,
Christ Jesus to the church is known, of which church the apostles were,
which was before you came up, and so over you is seen, and the age is come,
the exceeding riches of his grace,
the Lord did show through Jesus Christ to the churches among the apostles.
Ephes.
2+++.+++ Therefore now is the dread of the mighty God,
the great and mighty day of the Lord`'s power gone over you, and going over you,
and with that ye are foreseen, before you were, and before ye came up,
and what you have done since you came up, and since you reigned;
and this is the day of the Lamb and his power, (and his wife his church is known,
Rev. 19:7) and with this, the Lamb he fathoms you all, your time, your reign,
your actions, who sees before you came up to the days of the apostles,
and we are of the true church, and none of yours, 1 Pet. 2:9.
but are of the royal elect seed of God, and co-heirs with Christ,
and heirs of the covenant of God, Christ Jesus the covenant of God, that stands sure;
whose blessing, life, and immortality we possess,
with which power you are seen as dead corrupt trees, lying in a wilderness,
full of vipers, serpents, and venomous beasts, locusts, unclean spirits,
fruitless trees that hath not borne fruit to God, but cumbered the earth;
therefore I charge thee, and command thee from the Lord God, that thou read this over,
and consider as thou readest it, for thou and you shall feel it,
the Lord`'s power which is to come upon you, the woes, the plagues, the vials,
the thunders, the judgments of the Almighty, the recompense, the indignation,
the fury of the Lord is coming upon you, and over you are his terrors,
and upon you is his power gone, and that is the word of the Lord God to you;
you have kindled your fires, and made them flame for the servants of the Lord God,
but now shall they be for yourselves, and that power of life,
with that you shall be ruled, in that do the servants,
sons and daughters of the Almighty reign, in the power, word, and life, over you all,
which was before you were, which power will bruise you under,
and the Lord God of power will make you to know that he rules,
and he will be worshipped in the truth, (that Cain and the devil is out of,
the murderer is out of,) and he will be worshipped in the spirit,
and Christ hath enlightened every man that is come into the world,
from which you have ravened, from truth, from the light,
from the worship of God in the truth, and so with the light are you judged,
comprehended and condemned, with which light and power, you are all seen,
and comprehended, which was before the world was made, by which power the glory is known,
which was with the Father before the world began; the plagues of God will be thy portion,
oh pope I who hath deceived nations, and all you Jesuits, and cardinals howl, for you,
misery is coming, saith the Lord God, who will be worshipped in spirit, and in truth,
and with none of your inventions.
