== To All the Nations under the Whole Heavens

[.heading-continuation-blurb]
And to all those who have ministered the Letter, and yet are ignorant,
and have kept others in Ignorance both of the Letter and Spirit also.
From those People who are despitefully called Quakers,
who Tremble at the Word of God in their Hearts:
To which Word all the holy Men of God have brought
forth their Testimony after the same manner,
(and who have appeared in that which cannot be shaken,) as the Scriptures of
the Old and New Testament do eminently declare and set forth.--By G. F.

Hearken, ye mountains, and give ear ye mighty foundations of the earth:
have not all those prophets and teachers followed their own spirit,
and have seen nothing, that say they have not the same power and spirit the apostles had?
And have not all you prophets been like the foxes that have worried the lambs,
and have not stood in the gap,^
footnote:[Ezek. 13, 14]
and worse than them that have preached for the handfuls of barley, and pieces of bread;
for you have done worse, that by force have taken it away by cart-loads,
and cast into prison till death: besides, this shows the idol in your hearts,
which makes you to stumble in your own wickedness.

When Ephraim spoke trembling, he was exalted in Israel:^
footnote:[Hosea 13]
What! Was he a Quaker? And the heathen trembled; What!
Must they turn Quakers?

Blow the trumpet in Zion, sound an alarm in my holy mountain,
let all the inhabitants of the earth tremble;^
footnote:[Joel 2:1]
What! must all those turn Quakers?
You that despise trembling, it seems you have not yet heard this trumpet;
but in the day of the Lord this shall be witnessed,
when streams and floods fall upon you, and consuming fire flames before and behind you;
then shall all faces gather blackness, and the earth shall quake,
and the heavens shall be moved; and this we witness,
the fearful and horrible day of the Lord is upon you,
that despise trembling at the word of God: when the Lord is a defence unto his people,
the heavens and the earth shall quake,
and you shall know the Lord dwells in his holy mountain,
and the Lord treadeth upon the high places of the earth; his name is the Lord of hosts.^
footnote:[Amos 4:13]
Shall not that land tremble that have sold the chaff for the corn,^
footnote:[Amos 8]
saith the Lord of hosts?
And shall not destruction come upon them that have seduced the people, by saying peace,
and there is no peace?
And shall not their songs be turned into howling, and they hunger after the word of God,
and cannot find it; and the time shall come that ye shall tremble,^
footnote:[Micah 7; Jer. 4:24]
the mountains tremble and quake at the Lord, and the hills do melt at the Lord,^
footnote:[Nahum 1:5; Joel 2:10]
these here you see became Quakers;
they are called mountains and hills that be above the people,
and the mountains and the earth shall quake, yea the whole world,
and all that dwell therein; and you must be an astonishment, and stripped,
that you may hear this, whose knees shall tremble then, ye that scorn quaking:
the seed is the end of the law,
and all figures and parables which pertain to the first earthly Adam,
which Christ the seed ends in, the earth trembles, and the heavens rend,
and the clouds drop with water.^
footnote:[Nahum 3; Judges 5]

And was not Ezekiel a Quaker, whom the Lord commanded to eat his bread with quaking,
and drink his water with trembling?
And fearfulness and sorrow,
a sign to the people that they should eat their bread with heaviness,
and drink their water with sorrow, and they should know he was the Lord.^
footnote:[Ezek.
12]

All that be upon the earth shall tremble for fear of the Lord.^
footnote:[Ezek. 38:20]

And was not Daniel a Quaker?
Did not he tremble when the angel spoke to him?
Yea, was not his strength and his breath gone, that he fell down.^
footnote:[Daniel 10]

When Habakkuk heard the word of the Lord, his belly trembled, and his lips quivered,
and I trembled in myself?^
footnote:[Hab. 3:16]
You may see Habakkuk was a Quaker.

And doth not Solomon say, the keepers of the house shall tremble,
the strong men shall bow themselves?^
footnote:[Eccl.
12]
What, is not here quaking?
Must not you know this, before you know Paradise?

Isaac trembled;^
footnote:[Gen. 27:33]
Isaac trembled exceedingly.
Was not he a Quaker?
And did not he serve the Lord?

And Pharaoh counted Moses`'s words as idle words, and the people`'s;
and so terrible was the sight,
that Moses did fear and quake when God spoke to him in the bush:^
footnote:[Heb. 12:21]
Moses was a Quaker, whom Pharaoh bid "`Get thee out of my sight.`"

The Moabites trembled at the wonders of the saints,
they that transgress the command of the Lord, shall be as a shaking leaf,
and shall have no power to stand before their enemies;
then shall they not despise trembling and quaking at the word of the Lord.^
footnote:[Acts 7:32; Ex. 15:15; 2 Sam. 22:7-8]

David said, when his cry entered in the ears of the Lord, the earth trembled and quaked,
and the foundations shook,
and dread and fear came upon the nations under the whole heaven:^
footnote:[Ps. 18:6-7; Duet. 2:25]
thou didst, O Lord, cause thy judgment to be heard from heaven,
and the earth trembled and was still at the voice of the Lord, there was thunderings,
and lightnings, the earth shook, and the earth trembleth at the look of the Lord,
and if he touch the hills, they smoke, the earth trembled at the presence of the Lord,
who carries his lambs in his arms;
thou puttest away all the ungodly from off the earth like dross; I love thy testimony.^
footnote:[Ps. 77:18,97:4; 104:32; 121; 119:119-120]
My flesh trembleth for fear of thee, I love thy testimony.
Here you may see David was a Quaker, who loved the testimony of God,
and the word of God in his heart, and had outstripped his teachers;
the earth trembled for the fear that was sent out from God,^
footnote:[1 Sam.
14]
you shall know this fear, though you be out of it now.

"`Honour me before the people,`"^
footnote:[1 Sam 15]
saith Saul to Samuel.
When Saul disobeyed the good spirit, the evil came in,
when he went from the word of the Lord: when the power of the Lord goeth over all,
then the heart is not hardened.
Thus saith the Lord, "`But to this man will I look, even to him that is poor,
and of a contrite spirit, and trembleth at my word.`"^
footnote:[Isa. 66:2,5]
Here you may see it is the contrite Quakers the Lord doth regard, and saith,
"`Hear the word of the Lord all ye that do tremble at his word.`"
Your brethren hate you, and cast you out, and say, "`Let the Lord be glorified,
and he shall appear to your glory, when they shall be ashamed.`"

And Eliphaz the Temanite trembled, and his hair stood on his head, and his bones shook.^
footnote:[Job 4:14-15]
And doth not Job say, "`God removeth the mountains ere they are aware,
and he removeth the earth out of his place, and the pillars of the earth are shaken;^
footnote:[Job 5:9]
and what, are they turned Quakers?
The wicked saith to the Lord, "`Go from us,
we will none of his way;`" and the pillars of the heavens tremble and quake at his rebuke;
this the scoffers are ignorant of; and the earth trembled and quaked,
and the foundation thereof shook, and was removed at the Lord`'s wrath;
and this the wicked and the scoffers shall know.^
footnote:[Psalm 18]

Christ Jesus saith, "`The strong man keeps the house, and all his goods are in peace;
and now the strong man is got into the house, in the fall, since the beginning.`"
And man is that house, and Christ is stronger than the strong man,
and is come to cast him out, and spoil his goods;
and this you must know before you come into the garden again; and before you know this,
you must know trembling, and your salvation wrought out with fear and trembling,
which the apostle commands you; and then you will not despise Quakers and tremblers,
but will receive them,
and be with such who are in much fear and trembling at the word of the Lord.^
footnote:[Phil. 2:12]
And so here appears the ignorance of professors and teachers of the scripture,
and trembling at the word of God, but scoff and scorn in derision them that do;
but they are such that the Lord regards, that shall appear to their glory,
when they shall be confounded.^
footnote:[Isa.
66]

But the Lord is the true God, he is the living God, and an everlasting King;
at his wrath the earth shall tremble,
and the nations shall not be able to abide his indignation,
and the whole land shall tremble;^
footnote:[Jer. 10:10; 51:29]
for every purpose of the land shall be brought to
pass against them that have afflicted thee;
Oh, seed of the righteous!
Can ye endure this, ye mockers?
I beheld the mountains, and lo they trembled, and all the hills moved,
and the fruitful place was become a wilderness,
and all the cities thereof were broken down at the presence of the Lord.^
footnote:[Jer. 4:24]

And therefore, all ye nations, kindreds, tongues, people, multitudes, scoffers, revilers,
waters, on which the whore sits; the cup of trembling and astonishment ye are to know,
and your kings shall tremble, and your princes, dukes, captains, spoilers,
a voice of trembling is heard, and not of peace, and ye shall all melt away,
beating down one another as you go.^
footnote:[Ezek. 32:1; 26:16]
