== To Both Houses of Parliament

[.heading-continuation-blurb]
Friends, here is a few things for you to take into consideration.--By G. F.

[.numbered-group]
====

[.numbered]
I+++.+++ In righteousness and truth dwell, for that preserves both governors, and government,
and people in peace.

[.numbered]
II. Let no man that is a curser, a swearer, a drunkard, heady, highminded, furious, rash,
covetous, and loves gifts and rewards, and respects persons, bear office and rule;
for such will not he like meek Moses,
but will bring the wrath of God both upon people and magistrates,
as in former ages hath been seen; but set up such as loves mercy, and do justly,
walks humbly with God, and hates covetousness, Micah 6. such God requires,
and such as doth not respect men`'s persons,
and are not convinced of the law as transgressors, Jam.
2, 5, and these will be to the praise of God, of government, and governors;
and these differ from Pharaoh, Herod, and Nebuchadnezzar,
that knew not the kingdom of the Most High to rule in sons of men;
therefore to the witness of God in you come down to, and consider of these things,
that the nations and dominions may be ruled as a family.

[.numbered]
III.
And let no one be put to death for cattle, or money, or any such outward things,
for by the law of God they were to restore four-fold, and if they had it not,
to be sold for their theft; and so let them restore; and the apostle saith in the gospel,
"`let him that stole, steal no more, but labour in the thing that is good,
so let him live that he may repent.`"
These things lay upon me to write to you; and let no man be imprisoned, or persecuted,
because that for conscience sake they cannot swear, Matt.
5, but obeys Christ`'s commands, and the apostles`' doctrine, that saith,
"`swear not at all, lest they should fall into condemnation of the devil,
and evil,`" Jam.
5, but speaks truth,
and doth truth and justice at yea and nay in any places they are put in, or court,
according to Christ and the apostles`' commands, who is our Lord and Master.

[.numbered]
IV. And let none be persecuted because they cannot for conscience sake towards God,
put off their hats, and respect men`'s persons,
at which many hath been imprisoned and fined, which hath been like the pharisees,
a mark of unbelievers, that be from the witness in themselves, John 5,
such as seeks the honour that is from above only, that will never stain,
we would have all to be clothed with that, and honour all men in the Lord,
and have all men in esteem, and say, that they that rule well in truth, in justice,
and in righteousness, are worthy of double honour;
for every one that hath murder in his heart, may give honour with the hat deceitfully.

[.numbered]
V+++.+++ And let none he persecuted for not maintaining a ministry
that they know in their conscience is not of God,
which destroys both edification and comfort, quencheth the spirit,
and limiteth the Holy One, and despiseth prophesying; that is,
if any thing be revealed to another that sits by, let the first hold his peace;
this was order in the true church; for ye may all prophesy one by one,
and this is according to the apostles`' doctrine,
(which is disorder among the contrary,) 1 Cor.
14, and Peter said, Acts the 2d, and Joel 2,
"`that the Lord would pour out his spirit upon all flesh,
and his sons and his daughters should prophesy,`" which many witness,
glory and honour be to the Lord God forever.
And meek Moses said, "`he would that all the Lord`'s people were prophets,
and stopped and rebuked him that complained of them.`" Num. 11:29.

[.numbered]
VI. And let none be persecuted and imprisoned for warning drunkards, cursers, cheaters,
fighters, and quarrellers to repent, in streets, markets, cities, and towns,
and to tell them that they be out of the life of Christ and the apostles,
and shame their profession; which magistrates that be faithful, and fearing God,
should have kept down these things, and not have turned their sword upon the righteous,
and men that hath reproved sin in their gates, hath been to them a prey.

====

Consider these things, for it is your time now, and consider them in your time,
that to the Lord God you be faithful and valiant for his truth upon earth,
keeping to the light that shines in your hearts, that gives the knowledge of the truth,
1 Cor. 2:4, and the truth in the inward parts, which is the stay of the mind,
and word in the heart, which is to be obeyed and done,
in which is the wisdom that is pure, and from above, Rom.
10, and this is the ingrafted word which is able to save the soul which is immortal,
and bring it up to God, from whence it came, James 1:21,
and this will be always with you, taking heed to it, in counsel, wisdom and judgment;
and it will soften, and it will condemn if it be not obeyed,
and they that do not obey it, hurt their own souls;
and they cannot say by the testimony of the ingrafted word, that their souls are saved;
and let all your laws be drawn up into a short volume,
that every one in the nation may know them, and the end of them,
that they may not distract people about opinions of them,
but that all may know the full law and its end; for many men not knowing of them,
puts it to others to do for them, not knowing them themselves,
and so comes to be overthrown and undone, and great charges, which if things were short,
it would prevent this, that every one might know it.

And let all writs, indictments, warrants and mittimusses,
have no more in them than can justly be charged upon people,
and that is the way to keep things sweet and wholesome;
and if those things were looked into,
you would see abundance more in them than needs be put in;
which grieves the hearts of the simple and righteous.

And let none be persecuted about the word thou, to a particular person,
as many have been by them that takes more honour
and worship to themselves than they give to God,
who saith thou and thee to God.

And let no prisoners lie long in jail, but let them come speedily to trial,
for they learn badness one of another, and let none keep jails but sober men,
that they may be patterns and examples of good to prisoners.

And let none keep ale-houses, or taverns, but wholesome people, and such as fear God,
and are able to lodge travellers, that there may be no bad houses to nourish wickedness,
which grieves the souls of the righteous.

And let all things be done in love, that keeps down the spirit of strife,
where the vain-glorying is; and mind the law of God, and the gospel,
and let your actions be accordingly, that all your dominions may be as a family,
and ruled in mercy, truth, and righteousness,
and that establishes rulers and people in peace.

And let no one be persecuted about church-worship, and religion;
for Christ rebuked persecutors, and such as would revenge,
and told them that he came to save men`'s lives;
and the apostles`' weapons were not carnal, but spiritual,
that they wrestled with about religion: now mind them that wrestle with flesh and blood,
whether these be spiritual weaponed men, as was the apostles,
and have the mind of Christ.

Now such as will invent forms and worships, and set them up,
and compel others to bow unto them, mind and consider, and take heed of such, and that;
for Christ hath showed how people may worship God, and in what.
John, 4.

And they that fear the Lord, and meet often together, and speak often one to another,
which are his jewels, Malachi 3, be tender to such as you tender your souls,
for the Lord God hath reproved many for harming his prophets.
Psalm 105.

And let no one be persecuted for worshipping God in spirit and truth;
for Christ said to the woman of Samaria, "`neither at Jerusalem, nor at this mountain,
but they that worship the Father, must worship him in spirit and in truth,
for he seeks such to worship him;`" and the hour was come, and now is.

For Jerusalem was the place to which they came for to worship out of many nations,
and therefore the Jews persecuted the christians that came of their worship, and temple,
and priesthood, and witnessed Christ the everlasting priest, and the one offering,
that ended all the other offerings, and they that received him,
their bodies was the temples of God and Christ;
and all Christendom about their worship is on heaps,
they not being in the spirit and the truth, in which is the unity,
in which spirit and truth, the God of all truth, who is a spirit, is worshipped.

From a lover of your souls, and eternal good,
and that righteousness and truth may be established among you.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
A prisoner in Lancaster Castle.
