== A Measuring Rule / Concerning Liberty and Persecution.

[.heading-continuation-blurb]
And who have been the Persecutors,
and who have been the Sufferers from the Beginning.--By G. F.

Christians should love one another, that is the command of Christ,
and is a mark by which they are known to be his disciples.
Secondly, they should love their very enemies;
and by this they differ from the Jews and heathens, and all other people.

Now as for the late act concerning the people of God called Quakers,
there is no penalty laid upon any man for the not breaking up of their meetings,
or not putting the oath to them;
therefore it will try and manifest what spirit men are of,
and that which is in people will be made manifest now,
because the act is left to the executor of it, without any penalty: which act,
had it been in the days of the apostles,
would have taken hold of Christ and his apostles,
for he had twelve that often met together; and by this he might have but three,
for if there were five, it had been in the transgression,
who also had seventy disciples more.
Now I say, if it had been in the days of Christ,
it would have taken hold of him and his disciples.
Would Christ (and his disciples,) the wisdom of God, do you think, have obeyed this act,
and not met with his disciples?
Or if the Jews should have made laws to limit him but to four,
do you think that Christ the wisdom of God would have obeyed it, or his disciples?
And also, Christ said to his disciples, "`that they should wait together at Jerusalem,
and not depart;`" and they did meet together,
and you know that their meetings were different from the Jews and heathen;
and they were to wait together at Jerusalem until they received power from on high,
before they were to go to gather the churches:
and this was according to the wisdom of God;
which if the Jews had spoken to them that they should not meet,
do you think the disciples would have obeyed them, or the command of Christ?
And when the apostles had gathered churches out of the Jews and the Gentiles,
they settled them, to whom they wrote their epistles,
and built up one another in the holy faith,
and not to forsake the assembling of themselves together:
for if we sin willfully after we have received the knowledge of the truth,
then consider what is to be looked for: +++[+++so now mark,]
if the Jews or the heathens, out of whom the Hebrews, the Galatians, the Colossians,
the Thessalonians, and the Corinthians were gathered into several churches;
if the heathens and Jews had made laws against them,
that they should not meet saving four, do you think they would have obeyed it?
Therefore consider of these things, and do as you would be done by,
that is the law and the prophets:
did not many suffer in the ten persecutions for meeting together,
before there was a pope?
And hath not many suffered for meeting together, by the papists since;
as look through the book of martyrs, how they suffered by the papists,
and they called them conventicles;
and also in the times of the martyrs`' sufferings in the ten persecutions,
and since the ten persecutions, did they not make laws they should not meet?
And did they not call them conventicles?
And yet did they not meet in barns or houses, woods and fields?
As you may read in The Book of Martyrs.
Were these martyrs disobedient in the ten persecutions, and since to the papists,
in which so many thousands suffered for meeting together, for not paying tithes,
and for not swearing, and not yielding to their principles and practice,
that persecuted them?
Was it evil in them that persecuted them?
And is it good now in you that makes us suffer for the same things?
So are the martyrs, and persecutors, and you one, or the martyrs and we one,
who have suffered all along?
whether they have not the nature of the heathen that makes to suffer,
and not the nature of the apostles?
Likewise, have not many suffered here, as we now, for meeting together,
and not swearing now in these days?
As consider, in Oliver`'s days above three thousand suffered imprisonment,
and some to death, who suffered for not swearing, and for conscience sake,
as many of the martyrs in the time of the ten persecutions did,
and by the papists as we do now.

Therefore, consider these things, for it is Christ`'s command that we do obey,
and the apostles`' doctrine, which saith, "`swear not at all:`" consider now,
would not they in the ten persecutions, and the papists,
have punished Christ for preaching this doctrine, and made him to suffer,
(as we do now that own it,) who saith, "`swear not at all, but let your yea be yea,
and your nay, nay,`" etc. and the apostles for holding it forth;
for we do not these things in contempt or rebellion to any man;
for our love and tenderness is,
that all magistrates and people would live in God`'s fear, and receive his wisdom,
by which all things were made and created,
that by that they might be ordered to God`'s glory,
and order that which God hath given them under their hands, to his honour,
that to God they may be a blessing in their generation.

And consider, Daniel and the three children met, and disobeyed the king`'s command;
and Mordecai, who would not bow, disobeyed the king`'s command;
and the midwives disobeyed Pharaoh`'s command for not putting the children to death:
and the woman who had seven sons which suffered by the king`'s law,
because they would not eat swine`'s flesh; and one of her sons spoke to his mother,
"`I will not obey the king`'s command, I will obey the law of Moses,
which our forefathers obeyed.`"
And Daniel disobeyed Darius`'s command, which was, that Daniel should not pray;
and he prayed, and did not obey his command.
And the apostles disobeyed the high priest`'s and council`'s command,
when they charged them that they should speak no more in that name:
yet in the thing that is good, just and righteous, the righteous always have been,
and are ever subject to every ordinance of man for the Lord`'s sake,
to such as were for the punishment of evildoers, and for the praise of them that do well,
that they might live a godly and peaceable life; +++[+++mark,]
a peaceable life; for this cause they both prayed, and paid tribute,
not that they should bring them into an ungodly life, and unpeaceable,
for to that end were the higher powers ordained over the ungodly,
that went into the ungodly and unpeaceable life, for the ungodly are unpeaceable,
and this is for the praise of them that do well; for the law was made for transgressors,
and not for the righteous.
So they that be in the higher power are to distinguish the precious from the vile;
for not doing so, the prophet often cried against them;
and when they turned against the righteous, peaceable, and godly,
then is the saying known which the scripture speaks of,
"`what shall separate us from the love of God?
shall principalities, or powers, or thrones, or dominions?`"
Showing,
that there are principalities and powers that would separate
from the love of God which they had in Christ Jesus,
and that is from a godly and peaceable life; and so there is a distinction,
to be subject to that which punisheth the evil,
and there is a suffering by that which would separate from the love of God:
now that which would separate, turns the sword backwards against the righteous;
and persecutors were always blind, and could never see,
but run upon their friends instead of their foes: and therefore,
these things consider and distinguish.
God let Adam have liberty in the earth,
into which he was driven when he disobeyed his command;
and God let Cain have liberty in the earth,
after he had killed his brother about religion:
and God let wild Ishmael have liberty in the wilderness,
after he was put out of Abraham`'s family, the father of the faithful;
and the serpent had his liberty to feed upon the dust of the earth.
Now I say, consider,
who are they who would not have Christ the just to live upon the earth;
were not they them that Christ called serpents, the Jews, the great professors?
It was not God`'s mind that people should be out of the earth:
God let Adam and Eve have liberty in the earth, after they had transgressed,
though they were not to have liberty in the garden.
And Ishmael, though he had not liberty in Abraham`'s family,
yet he had liberty in the wilderness.
And Cain, though he had not liberty in the presence of God,
yet he had liberty to he a wanderer in the land of Nod.
Therefore consider what mind that is that would not let men have liberty in the earth,
though he be not of your assembly, yet he should have liberty in the earth.
Therefore consider whether it be the mind of God, or against it, yea or nay,
though the just comes over all these things, and are redeemed from the earth.

And if we must not meet together, how must we stir up one another, and edify one another,
and provoke one another unto love, and to good works,
if we must not meet together to speak one to another.
Consider this with understanding.

The world saith, "`kiss the book,`" the book saith,
"`kiss the Son lest he be angry;`" and the Son saith, "`swear not at all,
but keep to yea and nay in all your communications; for whatsoever is more than this,
comes of evil.`"

The world saith, "`lay your hand on the book;`" the book saith,
"`handle the word;`" and the word saith, "`handle not the traditions, inventions,
nor the rudiments of the world;`" "`and this is my beloved Son, hear ye him,`" saith God,
"`who is the life, and the truth, and the light, and the way to God,`" who saith,
"`swear not at all.`"

Therefore, cumber not the ground, you adulterers, cumber not the earth, you drunkards,
cumber not the ground, you swearers, cumber not the ground, you proud, vain persons,
cumber not the earth, you earthworms, covetous persons, cumber not the ground,
you oppressors and exactors, and grinders of the poor, cumber not the ground,
thou persecutor of the children of the Most High, cumber not the ground,
ye rich gluttons, cumber not the earth, you idle persons,
that live in fulness of pleasure, and abundance of idleness, as the stalled ox,
so as he lieth in the mire and the dirt; and as the full-fed horse that must be breathed,
with pleasure and sports, and your games of all sorts,
and call it recreation for your idleness, out of the service of the Lord;
for thou who art so full, thou needest not work thyself down by pleasures,
nor go to pleasures to get thee a stomach; if thou wilt work it down with labour;
work and chastity keeps all sweet, and labouring in the fear of the Lord.

Cain, the first birth, a persecutor, the first birth, a false worshipper; and Cain,
the first birth, that false worshipper, turned, and turneth against Abel; and Cain,
the first birth, out of his stock came up the false worshipper,
who was the inventor of harps and organs.

Nimrod`'s stock, false worshippers, and out of Ham`'s stock, he came,
whose spirit was not covered with truth, but with that which was from the truth;
and so that spirit which runs from the truth, is not like Shem nor Japhet,
and such worship not God in the spirit.

And they of the old world, that went from the spirit of the Lord, and grieved his spirit,
they could not worship God in the spirit.

And the Philistines grieved the spirit of the Lord, and they were the persecutors,
and they turned against the just.

And the Sodomites were the persecutors of the just,
and the Sodomites were such as lived in abundance of idleness and fulness,
and those that were idle and full persecuted the righteous and the just,
and the true worshippers; and they that did, and do so, are the false worshippers.

And Ishmael and his stock, the first birth, who scoffed at the just,
and turneth against the just, a persecutor, and so are all wild men now.

And Esau, the first birth, the profane person, a false worshipper, a persecutor of Jacob,
as many Esaus now, persecute them whom God loveth, who hate the first birth,
(being persecutors, profane, false worshippers,) whom God loveth not.

And the Egyptians were, and are persecutors, and of the first birth.

And Balaam was a persecutor of the just, and Balaam loved the wages of unrighteousness;
and such Balaams are now the lovers of the wages of unrighteousness, and the persecutors.

And the Jews that professed the law, the words of God,
and did live out of the life of the law of God, such did and do persecute the just;
and such professors were always, and now are persecutors.

And always such as preached for hire, and divined for money, and taught for filthy lucre,
and such shepherds, bishops and priests, that taught for the fleece and the wool,
and for handfuls of barley, and for pieces of bread, and were covetous;
such were and are persecutors, and false worshippers,
and persecutors of the just and the true worshippers of God in the spirit,
and they that did so, grieved it.

And the scribes, pharisees and chief priests,
that had the prophets`' and the saints`' words, and were not in the life of the law,
and the prophets, and saints, and yet did profess their words,
such did and do persecute the just, them that be in the life of the saints.

And also, likewise, all christians that do profess the prophets`', and Christ`'s,
and the apostles`', and Moses`', and the saints`' words,
and are out of their life and spirit, are the false worshippers,
and are the persecutors of the just,
and that is the end of all the profession without the life
and the spirit of God that the saints dwell and walk in,
who are the true worshippers of God in the spirit and truth;
and such as are led by the spirit of God, they are the sons of God;
and the false worshippers are such as grieve the spirit of God,
and yet will get the saints`' words, and the sheep`'s clothing,
and not live in their life.

The first birth liveth in the kingdom of the world, in strife, a persecutor:
the first birth is a birth of strife,
and the second birth is heir of the kingdom of the Lord;
and the fruits of this birth is love, etc. therefore come out of the first birth,
to the second.

Cain, Ham, Nimrod, Ishmael, Esau, Balaam, Sodomites, Philistines, pharisees,
chief priests, Babylon; were not these envious, wild, profane, idle, covetous,
oppressors, persecutors, false worshippers?
And so you that be of the same nature, and of the same birth, was it not,
and is it not the first birth?
If it be so, know your own kindred, and come out of this kindred.

Scoffers, scorners, mockers, reproachers, revilers, brawlers, railers, envious men,
do you profess God and Christ?
these be all evil weeds, and cumbers God`'s ground.
The Babylonians were and are persecutors of the just, and the true worshippers of God;
and the Babylonians build up, and throw down, who be out of the standing power,
life and spirit of God, which the apostles and we are in;
and so are not upon the rock Christ Jesus, upon which we are, that changeth not.

[.signed-section-signature]
G+++.+++ F.
