== To All Sorts of People in Christendom.

O ye priests, is it not for you to preach to all people, Christ Jesus, the new covenant,
how that in and by it all shall be taught of God from the greatest to the least?
and is not this gospel?
but instead of this you preach up war and strife among the people,
and you war and strive with them for your backs, bellies, and mouth,
and are never satisfied,
spoiling and straining the goods of them that you do not preach to,
and casting them in prisons that will not put into your mouths;
and are not you in this unlike the gospel-ministers?
And again, do not you preach up that men must have sin the term of their lives?
and so are preachers up of sin, and not of Christ, who came "`to take away sin,
and to destroy the works of the devil,
and to make men perfect;`" and are not these traditions your own,
and not the traditions of Christ and the apostles?
As to sprinkle infants, and sign them with a cross, and that they must have god-fathers,
and god-mothers: and do not you teach these traditions for doctrine among the people?
And is not this your own tradition,
to tell the people that the steeple-house is the church, which you teach for doctrine?
And is not the steeple-house that you call the church, made of lime, wood, and stone?
And will you make people believe that Christ shed his blood for lime, wood, and stone;
and sanctify lime, wood, and stone; and that he is the head of lime, wood, and stone;
and that Christ loveth lime, wood, and stone; and that in the midst of lime, wood,
and stone, that Christ will sing praises; for Christ sanctifieth and loveth,
and shed his blood for the church, which he is the head of; and the church is his body,
and lime, wood, and stone, is not his body: and for you to say that lime, wood,
and stone, is the church, the body of Christ, which the masons and carpenters have made;
and is not this tradition, like as the heathen, that made an image of wood, stone,
or other matter, and then said it was God, and worshipped it:
for do not you worship the house, when you put off your hats when you go into it,
and through it, when there is no service in it to God, as you do pretend?
And is not this your own tradition, and not from Christ and the apostles,
to make a trade of Christ`'s and the apostles`' words,
that suffered and died for speaking them freely, as they had received freely,
and judged them false prophets that preached for lucre and made merchandize of the words?
And is not this your own tradition, to make your ministers at schools,
and they must serve there seven years before they must preach?
And is not this like other tradesmen, that go by companies,
that will suffer none to set up their trade, but who hath served their apprenticeship,
seven years?
and in this tradition are not you gone from the ordination of God and Christ,
in making ministers?
Who saith that "`he will pour out his spirit upon all flesh,
and his sons and daughters shall prophesy;`" and the apostle saith,
"`that he was not made a minister of men,
nor by men,`" and that which he received and ministered, "`was not of man, nor from man,
but from the Lord Christ.`"
And is not all that you receive, from man, that is made of men?
And do not you persecute them that will not receive it, and give you money for it,
whereas the prophets and apostles did not sell that which they had received from God,
for so much a year, a hundred pound, more or less, as they could get it, as you do;
but it was not valued with money, or money-worth; and the prophet saith,
"`all should come freely, without money,
and without price;`" and Christ saith to all the true ministers of him and the gospel,
"`freely have you received, freely give.`"
But tradesmen that have served an apprenticeship, and have not received freely, say,
that they must not give freely, for it hath cost them money;
and so the command of Christ and the prophets,
and the practices of the apostles are laid aside like an old almanac.

See, hear the call of the patriarchs, prophets, and apostles: Abel was a keeper of sheep.
God had regard to Abel`'s offering, because he was righteous;
but to bloody and persecuting Cain`'s offering, (which was done in the custom and form,
and not in the faith,) God had no regard. Gen. 4:2.
Abraham was to go from his father`'s house, and his country and kindred,
and so from their religion and worship.
Gen. 12. Jacob and his twelve sons were shepherds, keepers of cattle; David,
beloved of God, a prophet, he kept his father`'s sheep. 1 Sam. 17:15.
Gideon, the Lord called him when he was threshing wheat,
by the wine-press, Judg. 6:11. Elisha, called from the plough-tail, a prophet;
and both Elijah and Elisha were persecuted by Jezebel. 1 Kings 19:21.
Amos, he was a prophet, a fig-gatherer, a herdsman. Amos 1:12.
Moses was a prophet, he was a keeper of sheep. Ex. 3:12.

Peter and John, unlearned men,
they were called from their nets when they were a-fishing. Matt. 4:18.
And James, and Andrew his brother, were called from mending their nets,
to follow Christ, and they leaving their father, nets, and ship, went after Christ. Matt. 4:12.

The wise men found Mary and Joseph, and Christ laid in the cratch, or manger,
no room for him in the inn: Joseph a carpenter: Christ was called a carpenter,
and a carpenter`'s son; you turn such into the stable, Luke 2:16.
Matthew was sitting at the receipt of custom, and Christ saw him,
and said to him, "`follow me,`" and he rose up and followed him; he was an evangelist. Matt. 9:9.

Luke called, who was a physician, and became an evangelist, Col. 4:14.

Aquila, and Priscilla his wife, he was a craftsman, a tent-maker,
and they instructed Apollos. Acts 18:24.
Paul was a tent-maker, and wrought with Aquila and Priscilla,
he being of the same trade. Acts 18:3.

Christ and his disciples went into his own country, and preached in their synagogues,
and his countrymen said, "`from whence hath this man this wisdom?
And is not this the carpenter, the son of Mary, and the brother of James and Joses,
and of Juda, and Simon?
and are not his sisters here with us?
And they were offended in him.`" Mark 6:2-3.
And what were the rest of the twelve, and the seventy disciples?
were not some of them tradesmen, that followed some callings?
the Jews marvelled, saying, "`how knoweth this man the scriptures,
seeing that he never learned?`"
Jesus said, "`my doctrine is not mine, but his that sent me;
and if any man will do his will, he shall know of the doctrine, whether it be of God,
or whether I speak of myself.`" John 7:15-17.

Isaiah saith, "`The spirit of the Lord is upon me, and the Lord hath anointed me,
and sent me to preach good tidings unto the poor, and to bind up the brokenhearted,
to preach liberty to the captives, and to them that are bound,
the opening of the prison.`"

And when did christians lose this commission of the prophet Isaiah,
and that they should now take one another by the throat;
and cast one another into prison; and bind and make captives; and to break,
and not to bind up the broken?
And is this your glad tidings, who say,
that you have not the spirit as the apostles and prophets had?
We do look upon all your teachers of Christendom by your fruits,
as Christ hath taught us; and by your fruits we know you not to be as the apostles,
but such as Christ spoke of in Matthew 24. as briars, thorns, thistles,
and not fig-trees, and vine-trees; but hirelings, and covetous,
greedy after lucre and rewards, and persecuting,
which is forbidden by Christ and the apostles;
for you have left the command of Christ and the apostles,
which is to "`love one another,`" and to "`love enemies:`" and therefore as Christ said,
"`go not after them,`" in Matthew 24. and the apostles saith,
"`we are to turn away from such,`" as in 2 Tim.
3.

And is not this a tradition of your own, and not from Christ, and the prophets,
and the apostles, to preach by the hour-glass, in a thing like a tub, on a soft cushion;
and that when the hour-glass is out, to say, that the time is past neighbours?
And is it not as much as to say, you have your measure, be gone?
and did Christ, and the prophets, and the apostles do so?
And had they so much a day, or a year for preaching by the hour-glass?
Or was the pulpit like unto yours, that you read of in scriptures;
for could not about forty men stand upon it?
read and see. Neh. 8:4.

What command have you, to persecute, or imprison any, concerning religion, or worship,
from Christ,
who hath all power given to him in heaven and earth`'?
But is not Christ`'s command to the contrary,
that you should "`love one another,`" and "`love enemies?`"
and so then, not to hate one another, and to hate enemies,
as those called christians do this day?
For did not God love the world,
(which were enemies to him,) that he gave his only begotten Son into the world,
that whosoever believed in him should not perish, but have everlasting life?
And was not Christ`'s love manifested to the world,
that when they were sinners and ungodly, Christ died for them?
And if people have sinned in their judgment concerning religion, and are mistaken,
hath Christ bidden you to persecute them for their sins`' sake?
Which he died for, and tasted death for every man;
and was manifest in the flesh to condemn sin in the flesh; and the promise is,
that he will take away their sin, and he will destroy the devil and his works,
which devil is the author of sin, and his work is sin?
And so it is Christ`'s work to destroy sin, and the author of it, the devil,
and not to destroy the creatures; and so he fulfilleth the promise of God,
"`The seed of the woman shall bruise the serpent`'s
head:`" and so Christ is the way to God,
who bringeth man and woman to God, destroying him and his works;
that led man and woman from God, and kept man from God.
And Christ commandeth you to "`love one another,`"
and to "`love enemies,`" and rebuketh his disciples,
which would have had fire to come down from heaven,
to have destroyed them that were contrary-minded to them; and Christ said to them,
"`that he came not to destroy men`'s lives, but to save them,`" +++[+++mark this,]
and Christ commands you in the scriptures,
that you must let the wheat and the tares grow together till the harvest;
and checketh those servants that would have gone to pluck up the tares, and saith,
"`lest they pluck up the wheat also.`"
Let all that say they are christians mark this, and the words of Christ,
how they obey them; and Christ saith, "`that the harvest is the end of the world,
and the angels are his reapers:`" so let men and women fulfill the command of Christ,
and love one another, and love enemies,
and that will differ the christians from the pharisees and scribes:
for Christ came to set at liberty the captive; and take notice of the sentence,
that he will give to them that do not visit him, that is imprisoned in his members;
and if they go into everlasting punishment that do not visit him in prison,
where he is made manifest, what will become of them that cast him into prison;
judge yourselves?
For liberty is a natural right, and every natural creature would have its natural right,
its liberty; and Christ gives liberty, and breaks the bonds asunder:
and where the spirit of the Lord rules, there is liberty; but where it is quenched,
there is the bondage, and not liberty,
that bondage that causeth the whole creation to groan,
which the creature waiteth to be delivered from,
into the glorious liberty of the sons of God, by Christ:
and all creatures in heaven and earth give him the glory and the honour,
for he is worthy, who giveth liberty, and destroyeth and consumeth the man of sin.

What wages doth the Lord desire of you for his earth that he giveth to you teachers,
and great men, and to all the sons of men, and all creatures,
but that you give him the praises, and honour, and the thanks, and the glory;
and not that you should spend the creatures upon your lusts, but to do good with them;
you that have much, to them that have little; and so to honour God with your substance;
for nothing brought you into the world, nor nothing you shall take out of the world,
but leave all creatures behind you as you found them,
which God hath given to serve all nations, and generations;
and so that you have food and raiment, therewith be content,
which is the apostles`' rule, and an example to you all; and Christ`'s command is,
"`that you should not take thought for tomorrow,
for sufficient for the day is the evil thereof;`"
and he biddeth you to consider the lilies,
how that they live without care and taking thought,
and that one of them was beyond Solomon in all his glory;
and that ye should be beyond them, and above them;
for so did God make man before he fell, and set him above all the works of his hands,
before he fell; and so he is in the restoration by Christ again,
though in the fall he is in the captivity under the creatures?

And what command have you from Christ and the apostles, that are called christians,
to judge one another, and persecute one another about meats, clothes; as white-coats,
and black-coats, and days?
Doth not the apostle command you to the contrary; and say,
that you should not judge one another about such things; and tells you,
that the kingdom of heaven standeth not in such things, but in righteousness, peace,
and joy in the Holy Ghost?
And do you judge and persecute one another, about such things,
that the kingdom of God standeth not in, and leave the righteousness, and faith,
and joy in the Holy Ghost?
And doth not the apostle say to you, "`that meat is for the belly,
and the belly is for the meat, and God will destroy both?`"
And so are not clothes for the body?
And doth not Christ tell you,
"`that which goeth into the mouth and belly doth not defile a man, but the wickedness,
that which cometh out of his heart, defileth the man?`"
And would not, or did not the pharisees and scribes,
and chief priests persecute Christ and his apostles, for not observing their days,
and their traditions?
And did not Christ tell them,
"`that he was Lord of the Sabbath,`" and how that they had left the commandment of God,
and taught their own traditions for doctrine?
And hath not Christendom done the same, left the commands of Christ and the apostles,
and taught their own traditions for doctrine, which they have not received from Christ,
nor the apostles; and if men do not observe them, they are judged and persecuted,
and imprisoned, and their goods spoiled?

I+++.+++ Is not this your own tradition, and not from Christ and the apostles,
to persecute one another about religion and worship?
for doth not the apostles say, "`who art thou that judgeth another man`'s servant?`"
for they must all stand and fall to their own master,
and every one must give an account to God.

II. And is not this your own tradition to persecute one another about days, and meats,
and clothes, and outward things, which the kingdom of God stands not in?
for doth not the apostle tell you, "`let every one be fully persuaded in his own mind?`"
and here have not you left his commandment, and have followed your own traditions?

III.
And is not this your own tradition and commandment, to set up a forced maintenance,
and tithes, for a christian ministry, whether they preach to them or no?
For, is not Christ`'s command to the gospel ministers, "`freely you have received,
freely give; and take no thought, etc.
And go ye into all nations and preach the gospel?`"
and did not they obey his command and will these ministers now-a-days,
that are placed and settled in great benefices and means, leave their means and benefice,
and go into all nations and preach the gospel?
Nay, are not they taking thought for themselves, and their families, like the heathen;
and they will have no call now from God, except it be to a larger benefice?
And when was the commission of Christ changed?

IV. And is not this your own tradition, who will suffer none to preach but yourselves,
and if any do, they come under your judgment, and are persecuted as deceivers,
though they be truer than yourselves; and do speak freely, as Christ commandeth,
having received freely?
and so are these ministers ever like to convert either Jew or heathen,
that will not go out of their parishes except it be to a larger;
and will neither obey the command of Christ themselves, nor suffer others that would?

V+++.+++ And is not this your tradition and custom, and not Christ`'s and the apostles,
for christians to use carnal weapons in their warfare to heaven,
and about worship and religion, seeing that the apostles said,
"`that the weapons of their warfare were not carnal,
but spiritual,`" and that the spirit and the flesh strived and warred one with another?
And so, hath not the spirit his weapons spiritual, which he warred withal?
And the flesh his carnal weapons, that he warreth withal, for his worship and religion?
And are not such carnal, and in the flesh?
and can they please God?
and the apostle saith, "`that they were to stop the mouths of gain-sayers,
in the convincing of them;`" but the casting into prison,
or persecuting people concerning religion, will not stop their mouths, nor convince them;
and this was not the apostles`' custom, or Christ`'s, but the heathen, and the Jews.

VI. And is not this your own custom or tradition, that such must preach that be covetous,
and strikers, and hirelings, when Christ telleth you, "`that a hireling will flee,
and leave the flock;`" and the apostle telleth you,
"`that the ministers must not be strikers, nor covetous,
nor given to filthy lucre:`" so mark your own custom, and mind the apostles`' words,
and obey them.

VII.
And is not this your own tradition and custom, to make your ministers by the will of men,
when the apostle saith, "`that lie was made a minister of Christ, not of men, nor by men,
but by the will of God;`" neither had he "`received it of men,
but by the revelation of Jesus Christ?`"
and so receiving of men for money, and selling it again for money;
is not this your own tradition and custom, and not from Christ,
(and the apostles,) who said, "`freely ye have received, freely give?`"
and the apostle saith, "`that they did not make merchandize of the word of God,
neither did they teach for filthy lucre.`"

Christendom hath not been rightly planted, nor the same planters as the apostles were,
and so not by the same power and spirit that the apostles were in;
but they have been planted by men`'s wills, and the sword and club;
and converted by such as say they have not the same power and spirit the apostles had;
and so one planteth, and another plucketh up:
but you that are planted by the same power and spirit as the apostles were in,
live in the mortified life.

And you that be Jews in spirit, give yourselves to the reading of the law of Jesus,
whom he hath made kings and priests:
as the kings and priests were to give themselves to the reading of it,
that they might inform the people to practise it,
that the blessing of God might come upon them, and not the wrath;
and so you must do the law of Jesus.

All people everywhere are to break down the imaginations of their hearts,
and the evil of their earthly mind, and their wisdom, and their knowledge,
and understanding, and all the images and idols of their hearts,
by the spirit that God hath given them,
that they may offer to the Lord a sacrifice and an offering in his temple:
the Jews in the spirit are beyond and higher than all the outward Jews in the flesh,
and their outward offerings in their temples, and the offerings of the Jews in spirit,
put down all the outward Jews`' offerings that be outwards, to do that which is inward:
and the Jews outward, eat of their outward offerings in the temple;
and so Jews in the spirit do eat of their offering, Christ, in their temple,
and of their sacrifices, and then they praise God in their temple.
And the outward Jews`' lamps always do burn in their temples, and never go out;
and they were to dress their lamps in their temple;
and as the Jews in the spirit their lamps are never to go out,
but always to burn in their temple; and they are to trim and dress them,
and so they come to be a royal priesthood,
always attending in the service of the Lord in the temple, morning and evening,
offering in the spirit the Lamb without blemish in the temple:
and so the Jews in the spirit, morning and evening offering in the Lamb`'s spirit,
and in their temple, who is without blemish, and at all times they must offer in him.

And there were priests to eat of the show-bread in the temple,
and the show-bread was always to be in the temple on the table;
and so the Jews in the spirit are always to have their bread in their temple,
to eat of it; and ye are a spiritual household, and a royal priesthood to God.
And the incense and sweet odours were to burn in the Jews`' temple;
and so the Jews in the spirit are always to have
the incense and sweet odours to burn in their temple.
And the Jews in the flesh were not to touch any thing,
nor eat any thing that was unclean;
no more are the Jews in the spirit to touch or handle, or eat any thing that is unclean;
but to handle Christ, and feed upon him, who is pure, and holy, and clean,
who is the bread of life.
And the Jews outward were not to follow and feed upon any offering but their own;
and so the Jews in the spirit are to follow no offering but Christ,
and feed upon him who is their own.

First, the wicked and the deceivers, robbers and false prophets,
and seducers do remove the land-marks of the righteous and just,
and then they make all their replenished places like a wilderness,
and then cometh up the power of the dragon, which begetteth and breedeth serpents,
and vipers, and all the unclean beasts, and so make the world like a wilderness;
and when the land-mark of the just and righteous they have removed, then truth, justice,
righteousness, and equity have no place among them, then he deceives,
and setteth up his own ways, and hateth all them that will not obey him.

The Jews outward in their appointed feasts praised the Lord with the outward trumpets;
and so the Jews in spirit, at their feasts in their temple,
in their feeding upon the bread of life, lift up their trumpets, their spirits,
in praising the Lord God.

Now all that you call Christendom do believe that Christ is come, and is risen,
and that Jesus is Christ the Son of God; so that now they are all to receive him,
and to walk in him, and abide in him; but you that do profess the scriptures of Christ,
that he is come, that which the saints professed and lived in;
as the Jews did profess Moses and the prophets, and God, and that Christ was to come,
but they denied the life, as you do, and lived not in it, neither do you;
but are disputing about the words, and deny the life and spirit of Christ,
the prophets and apostles,
and that is the cause that you are not in fellowship and unity, one with another,
but all on heaps.

And the Jew outward, he was not to touch the dead,
nor to feed on that that died of itself, for it made him unclean by the law of God.
And so the Jew inward in the spirit is not to touch the dead,
nor feed on that which dieth of itself, but on Christ.

And the Jews under the law, did not take tithes of fish, and of swine, and of foals:
did they offer up these in their offering a sacrifice to the Lord?
Where was there any swine, or horses, or fish, of any sort,
offered upon the altar in the temple by the priests
was not the swine an abomination to the Lord,
and to the priests?
But do not the priests now take that abominable offering, who are in the abomination?
And where did the priests under the law take tithe-rabbits?
Were they to be sacrificed upon the altar for an offering?
For the rabbits, foals, and the swine were not to be offered,
but they were to be an abomination to them.

And whereas you call christians lay-people, you that be ministers, and in some office,
and under some vow or oath; is not this contrary to the apostles,
who called the believing christians saints, and spiritual?
And are not all the true believers of the church, such as are passed from death to life,
and such as are born of God?
and the apostle Paul when he writes to the old Romans, he doth not call them lay-people,
as the Romans call christians now; but Paul called them,
"`beloved of God called to be saints,`" and that they were called of Christ Jesus;
read Romans the first, and see whether he called the Romans lay-people.
And Paul when he writeth to the church of the Corinthians,
he called them saints by calling, and the church of God,
and he doth not call them lay-people.
And also the Galatians, the church that was there, he calleth them brethen,
and not lay-people.
And Paul, when he wrote to the Ephesians, he calleth them saints, and not lay-people.
And when Paul and Timotheus wrote to the Phillippians, to the saints, bishops,
and deacons, they do not say, to the bishops, deacons, and lay-people.
And when Paul and Silvanus, and Timothy wrote to the Thessalonians, they said to them,
"`that their church was in God, the Father of Christ,`" and called them beloved brethren,
and not lay-people.
And James in his epistle, said that they were brethren.
And Peter in his epistle, doth not call them lay-people,
but such as "`have obtained the like precious faith, and beloved.`"
And John in his epistle calleth them babes, elect, dearly beloved, and not lay-people;
neither doth Jude in his epistle call them lay-people,
but called and sanctified of God the Father.

Christ saith, "`Go ye into all nations, and teach,
baptising them in the name of the Father, Son, and Holy Ghost;
but the priests and papists will hardly go any further
to preach and baptize than their own parishes,
where they are sure of great livings, which they have agreed for.

And do you hold by tradition from Christ and the apostles,
that the pope must wear a triple crown?
and is not this the glory of the world, and not from either Christ or the apostles,
who were not of the world?
And did Timothy, or Titus, or Peter,
or any of the apostles wear a triple crown of gold on their heads?
Was not Christ`'s crown that they made him, of thorns?

And you minister`'s of Christendom,
because that you are not in the faith that works by love,
nor in the universal love of God,
therefore you cannot build up Christendom in the love of God,
nor in the holy faith that works by love, for love edifies, and buildeth up;
but your faith is a dead one, and the fruits of it are wrath, and strife, and envy,
and tearing one another, to pieces with persecution; which persecution was always blind,
and the blind leadeth the blind into the ditch: so you are out of the catholic faith,
and the catholic church, and the catholic love, fellowship, and worship,
and catholic gospel, which is everlasting: for catholic is universal.

In the time of the law, they were not to touch the dead, if they did they were unclean;
which is a figure to them that be in the living gospel, which is immortal,
they are not to touch the dead ways, doctrines,
nor the dead flesh and bodies of sinful flesh; but to touch Christ and his flesh.
And therefore, touch nothing that is unclean, but the living and the clean;
the earth is corrupted with the dead bodies, and the flesh thereof maketh it to stink,
the living smell it.

Christ is the altar that all offer upon, that offer up to God:
which altar is in the temple, and Christ is the way to God;
and such as quench the spirit in themselves, and others, and not suffer it to arise,
are such as watch the sepulchre of Christ, and are afraid that Christ should arise.

Drunkenness, whoring, and swearing, which are the works of sin,
this is the way to hell if you continue therein; and hell gapes,
the grave openeth her mouth; and death and destruction talk of the fame of God,
and the horse-leech, that is bred in the waters, crieth, give, give.

You drink healths, but drunkenness and whoredom, are out of the fear of God,
and destroy the health of the body, mind and soul: you bless,
but a profane life denieth salvation, the blessed state.
"`Lord thy children love thy light,`" but the children
of darkness tread it and them under their feet.

You fast, pray, and preach, and talk of God and Christ, and scriptures;
but the Lord will require all your debts that you are run into,
for you are gone beyond your bounds, and so into drunkenness, swearing, cursing, pride,
covetousness, oppression, (and not to do justly to all men,) and to live in malice,
strife, and envy, which be the works of darkness, and destroy, and raven,
and pluck down to pieces; but love edifieth and buildeth up.

There is but one shepherd, and one fold, and the sheep know the shepherd`'s voice,
and follow him, and he giveth them life eternal;
and they are all led by the spirit of God, and are the sons of God;
and they have the spirit of Christ, and they are his; and whether they sleep or die,
or eat or drink, they are Christ`'s, for he died for them,
and hath purchased them with his blood: and therefore, they are not their own,
but Christ`'s; and so they are to glorify him in and with their bodies, souls,
and spirits, which are his.
But in the world there is a multitude of shepherds,
and they have their several flocks and folds; and the shepherds fall out with themselves,
and with their flocks about victuals, clothes, days and times; and one while,
one shepherd getteth the flock, and another while, another shepherd getteth the flock;
and by these doings the flocks are almost plucked to pieces by the hireling shepherds,
which leave the sheep in time of persecution,
when they have gotten all the wool they can off their backs,
because the sheep were not their own; and when one leaveth the flock,
then another taketh them, and bringing them into his way,
from the way that the other led them in, that is fled from them;
and then if the second shepherd leave them, and a third take them,
he bringeth them into his way, from the second.
And thus the sheep are tossed up and down, and starved;
and every shepherd sheareth the sheep, and plucketh the wool off their backs.
But Christ layeth down his life for his sheep, and abideth with them,
in all their troubles, and persecutions, and sufferings, he suffereth,
and is persecuted in his flock of sheep,
when the hireling fleeth because he is a hireling, and careth not for the sheep,
for they are none of his own.
And you may see as many flocks as there are in the world,
there are so many shepherds knowing of them, and keeping them in the world,
which the devil hath made a wilderness, and a desolate place,
among whom it is always winter to the elect: we that are taught of Christ,
and know his voice, and follow him, Christ is to us, both in life and death, advantage.

The burnt-offering was to burn all the night until the morning on the altar,
and the offerings made by fire, whosoever toucheth them must be holy.
Levit.
5+++.+++ Every true christian must read the substance of this within him.

A yoke you have laid upon christians and Christendom, which our forefathers threw off,
and would never bear, neither would, nor will they that be of their seed,
all your inventions, images, pictures, representations, relics, images of God,
and Christ, apostles, saints, and prophets, and images of things in heaven,
and in the earth; and the observing of Christ`'s, and the apostles`', and saints`' days,
which burden you lay on people, which Christ and the apostles did not,
which were our forefathers.

And you force maintenance from people to your ministers,
and so make the gospel chargeable, and so are become burdensome to the people,
and troublesome, and this is not the gospel-way that our forefathers went in.
And them that will not give you maintenance, you cast them into prison for means,
which was not the way of the apostles,
and there do keep many until they do die in prison, and such as you do not preach to;
and this is not glad tidings of peace of the gospel, but war, and strife, and trouble;
and this burden you lay upon us, which our forefathers, the apostles did not do;
for they were not chargeable, but kept the gospel without charge,
and did not make merchandize of the word.
And Christ saith, "`freely you have received,
freely give;`" and "`every one that thirsteth, come freely, without money,
and without price.`"
And also all your persecuting about religion, and worship, and church, and faith,
and for matters of conscience towards God; and your inventing tortures, and racks,
to imprison and torture people that do not conform to your way;
this was not the way of the apostles, nor Christ;
and so you may see that you have lost the power that Christ and the apostles were in.
Rev. 2:10.
"`Ten days the devil shall cast you into prison,
that you may be tried,`" which is ten years.
Rev. 11. "`Five months the tormentors were to torment
the people,`" which is one hundred and fifty years. Rev. 12:6.
The woman, the true church,
she fled into the wilderness when she was persecuted by the dragon,
and there she was to remain, and to be fed of God twelve hundred and sixty days,
so many years; and then the false church got up (called the whore,) on the beast,
which the dragon, the devil gave his power to, who had power over all nations, kindreds,
tongues, and people, and they worshipped the beast both small and great,
all that had not their names written in the book of life:
and that beast he was to continue forty-two months,
which is twelve hundred and sixty days, so many years.
Rev. 13. Rev. 16:19. The great city fell, and was divided into three parts,
and did not the Turk get one part, and the protestants another, the pope another?
Which city is the great whore, the false church; and the cry was, "`come out of her,
my people, lest you be partakers of her plagues:`" for plague, sorrow,
and mourning were to come upon the whore, and loss of children.

The promises of God are all fulfilled in the seed Christ,
and all the promises are fulfilled to the wicked seed, in the woes and plagues,
in judgment to the wicked seed,
which was the first birth of death spoken of in the scriptures.

What is it that people look at so much?
Is it not at some lie and jests that be vain, or at old stories,
and at vain light tricks, which the light airy spirit hath done,
which stirs up the light spirit in others to laughter; and so vanity begetteth vanity,
and lightness begetteth lightness, and such work the light airy spirit doth,
to pass away his time, and with plays, and shows, games, and sports, and light vain talk,
among whom seriousness and soberness hath no place.

G+++.+++ F.
