[#ch46, short="Act that Prohibits Above Four or Five to Meet"]
== Concerning the Act

[.heading-continuation-blurb]
That prohibits, that not above four or five may meet.--By G. F.

This act would have taken hold upon Christ and his disciples, had he been in your days.
Christ it is known had twelve apostles, and seventy disciples, which often met together;
and besides the great multitudes that met with Christ in the towns, wildernesses,
and mountains, in the days of Caesar and the Jews,
and you do not read that either Caesar or the Jews made any acts, or laws,
that Christ and his disciples should not meet together;
though at last by that law that they had amongst themselves,
they put him to death for saying that he was the Son of God.
And did not the Romans which were heathens,
let the Jews have their liberty to worship God, when they had power over them,
though their religion differed from theirs, as you may read both in the scriptures,
and in Eusebius, and Josephus?

Yea, had not the christians in Britain, liberty,
and lived peaceably until Dioclesian`'s time, and lived pretty quietly,
though their religion differed from the heathen`'s religion in this land?
And in Dioclesian`'s time many were persecuted to death at Litchfield, and Leicester;
but mark what was the end of his power.
And did not many suffer persecution about six hundred Years after Christ,
by Austin the Monk, when he brought over his snap-sack of ceremonies;
and caused not he many of the Britains to be destroyed,
because they would not conform to the ceremonies he brought from Rome.

And had not the children of Israel,
(though in captivity in a strange land,) liberty in the empire of Nebuchadnezzar,
though his religion differed from theirs,
until that Nebuchadnezzar set up his golden image, with all his music,
who cast the three children into the fiery furnace because they would not worship it,
but worshipped God, and did give to Nebuchadnezzar the things that belonged to him;
and did not the Lord preserve these three children that stood for him,
and worshipped him?
And did not Nebuchadnezzar change his word and decree which he had made,
to burn them that would not worship his image, and make another decree,
by which he gave liberty to the children of Israel,
and sent it among all his people and nations,
that they should not speak any thing amiss against the God of the children of Israel?
and did he not afterwards confess to the God of heaven
that his kingdom was an everlasting kingdom,
and his dominion from generation to generation?
And had not he the children of Israel in great esteem,
though they differed from his nation`'s religion, worship, laws, and manners?
as you may read in Daniel, the 3d and 4th chapters.
And in Daniel, chapter 5. did not Belshazzar, his son,
give liberty to the children of Israel?
but when this Belshazzar did meddle with the vessels of the children
of Israel which were brought out of the temple at Jerusalem,
was not there a hand-writing on the wall against him?
and so you that be in spiritual Babylon,
that do meddle with the vessels of the children of God, and Jews in the spirit,
do you not think that the hand-writing is against you,
"`Mene Tekel,`" you are found too light, being weighed in the balance;
and do you not divide?
And are not your years numbered?
and doth not spiritual Babylon set up his spiritual image, and music about it?
and has not he burnt and persecuted such as cannot fall down to it,
as you may read in history, and in the Revelations,
and yet is not come so far as Nebuchadnezzar, who altered his decrees,
and confessed to the God of heaven,
and gave liberty to such as differed from his national worship?
and had not Belshazzar a great esteem for the Jews,
though they differed from his religion, and were captives in his country?
And if it had been your day,
would you not have said the three children were disobedient and wilful,
because they would not fall down at the sound of the music, and worship his image,
but obeyed the Lord?

And was it not some of the Babylonians that were
the informers against the children of Israel,
the outward Jews, that raised persecution against them?
and are there not many informers now in spiritual Babylon,
that raises persecution upon the Jews in the spirit?

And in Daniel 6, in the days of Darius, emperor,
had not the children of Israel liberty under the emperor in his empire,
though they differed from his national worship and religion,
until that some of the princes sought to find out a fault or occasion against him,
but could find no fault, he being faithful?
then said the men, "`we shall not find any thing against this Daniel,
except we find it against him concerning the law of his God.`"

Now here you may see Daniel had liberty concerning the law of his God, till this time,
that they had made a decree, according to the Medes and Persians, which alters not,
"`that whosoever asked any petition for thirty days, saving of the king Darius,
should be cast into the lions`' den.

Now Daniel went into his house, after this decree was made,
"`his windows in his chamber being open towards Jerusalem,
he kneeled down upon his knees three times a day, and prayed,
and gave thanks before his God as he had done before time.`"

Now, O ye persecutors, would ye not say that Daniel was a very fool,
and a wilful rebellious person, as knowing the king`'s decree,
and the spite of these men against him;
and he having been formerly in favour with the king, to lose all, and endanger his life?
These men finding Daniel praying to his God, informed the king,
and the law was executed upon him: but mark how God preserved this Daniel,
and how glad the king was of it, and what became of his accusers,
who were cast to the lions and torn to pieces:
and did not Darius then confess to the living God, and his kingdom,
and make another decree to give liberty to Daniel, and the children of Israel?
which Darius, the emperor, wrote to all people, nations, and languages,
dwelling on the earth, "`That they should all tremble and fear before the God of Daniel,
for he is the living God, steadfast forever; and his kingdom shall not be destroyed,
and his dominion shall never have an end.`"

And so had not Daniel and these children of Israel,
liberty in the realm of Darius and Cyrus, kings of Persia and the Medes,
though they differed from them in their religion, and were captive?
and doth not this judge all christians who profess God and Christ,
and are not to have power over one another`'s faith,
who cannot give liberty to one another, but persecute one another,
contrary to the command of Christ, who said, they should love one another?

Jer. 39. Jeremiah, who had been cast into the dungeon, and set in the stocks,
and beaten for his testimony for the Lord, by the persecuting Jews,
who kept him in prison till Nebuchadnezzar carried
away his persecutors captive into Babylon:
the captain of this Nebuchadnezzar`'s guard, left of the poor of the people,
which had nothing in the land of Judah, and gave them fields and vineyards;
and Nebuchadnezzar gave charge to the captain of his guard concerning Jeremiah;
"`Take him, and look well to him,
do him no harm;`" and he took Jeremiah out of the court of the prison, and said,
"`This day I will loose thee from the chain which is upon thy hand,
if it seem good for thee to go with me into Babylon, I will look well unto thee;
but if it seem evil unto thee to go into Babylon, forbear; behold,
all the land is before thee, whether it seemeth good and convenient to go,
thither go;`" and so Jeremiah stayed in the land of Judah.

And now, friends, was there not more mercy in this heathen Nebuchadnezzar,
than in the Jews and the great persecuting professors?
For though he had conquered the land, yet he did not force Jeremiah,
nor the people he left behind him, to be of his religion,
but left them to follow their own religion in their own land:
and has not Nebuchadnezzar outstripped many people in this; as you may read in Jer.
ch. 38-40.

And have you not read in Ezra, the proclamation of Cyrus, king of Persia,
to all the Jews among the people throughout all his kingdom,
how that the Jews might go up and build their temple,
and what large liberty was given to them,
and how that they might have liberty to go and serve, and worship God?
And though the children of Israel were of another religion than the Medes and Persians,
yet he gave the children of Israel liberty.
But it was the Lord stirred up the spirit of this Cyrus, king of Persia,
to give liberty to worship God, and serve him;
then people may judge what it is that stirs up the spirits
of people to persecute people for worshipping God.
Ezra 1. And did not a prophet rise up to persecute the Jews afterwards,
and call them a rebellious people, under a pretence that if they built a temple,
they should damage the king, Ezra 4, but afterwards the persecutor was frustrated,
and the children of Israel went on in their work.

And, so this Darius made another decree for the Jews`' liberty,
and the building of the temple, "`and whosoever should alter a word of the decree,
the timber should be plucked down from his house, and being set up,
he was to be hanged thereon, and his house to be made a dunghill;
and the children of Israel were to pray for the life of the king and his sons.`"

And so here you may see what liberty this man, called a heathen,
gave to the outward Jews, who differed from him in religion, who was a heathen;
and what a strict decree he made against those that were against the Jews,
and would have hindered them from building the temple;
and so this decree was for the service of God, contrary to his own religion,
which temple Christ has ended, and the priests`' and the Jews`' services,
"`and now he is not a Jew that is one outward;`" so that command, decree,
and penalty of Darius is ended, for such a work;
"`for he is a Jew who is one inward--whose weapons are spiritual and not
carnal;`" but the inward temple comes to be raised up by the spirit,
and the law and command of Jesus observed,
"`to love one another;`" yet Darius may judge the persecuting spirit in christians.
Artaxerxes made a decree that whatsoever Ezra the priest,
the scribe of the law of God of heaven, should require,
should be done for the house of the God of heaven,
for why should there be wrath against the realm of the king and his son;
and so Ezra was to set magistrates and judges, and such as knew the law,
and taught them that knew it not; "`and whosoever would not do the law of God,
and the law of the king, judgment was to be executed speedily upon him,
whether unto death, or unto banishment.`"
Ezra 7.

And now here you may see what liberty this Artaxerxes gave to the Jews,
who were of a different religion from him, that they did not obey his heathen law,
and the law of God, it was death; and so he makes a distinction betwixt the law,
and the law of God, though he was a heathen; but Ezra the priest, and the Levites,
and the primitive priesthood, with all their offerings, and their temple,
Christ has ended that priesthood, and the law by which it was made.
Heb. 7.

And so, as for banishing, and putting to death, imprisoning,
confiscation of goods concerning the building of the Jews`' temple,
and sacrificing there, with their singers and ministers, Christ has ended all these,
and says, "`love one another,`" not banish, nor spoil one another`'s goods;
so his command now is to be observed, and not Artaxerxes`' nor Darius`',
to build the temple of the Jews, and offer sacrifice:
now this may condemn the christians, (for a heathen to give his law,
and promote the Jews, and the law of God,
by which the religion stood,) who makes laws to persecute
one another contrary to the law and command of Jesus,
who saith,
"`love one another;`" for where did you ever read
of any law the persecuting christians made,
that they should love one another, and that they should keep the command of Christ,
who saith, "`love one another,`" and not spoil the goods, and banish one another?
If not, has not Artaxerxes condemned them,
who by his heathen law promotes the law of God, and the Jews`' religion?
which religion and law of the Jews, Christ has ended, as offerings, sacrifices,
and temple, as I said before, "`for,`" as the apostle said,
"`your bodies are the temples of God.`"

And also you may read, Nehem.
2, the moderation and tenderness of Artaxerxes and his queen to Nehemiah,
though Nehemiah`'s religion differed from theirs; and though he was a heathen,
he gave Nehemiah an order to go and see Jerusalem`'s walls repaired,
though he had much opposition by many bad people, and was called rebellious,
because they had not observed other nation`'s religions;
yet their persecutions came to nought, as you may see throughout Nehemiah: and so,
why should christians be more unmerciful one to another,
and persecute one another worse than the heathen did the Jews?
And so people are not to hang, banish, spoil goods,
and imprison one another according to Artaxerxes, the heathen`'s law,
but to love one another according to Christ`'s law, and command; and so,
priests have ignorantly brought this scripture to persecute, banish, imprison,
and spoil goods, who are darker than the heathen,
who gave liberty to the Jews`' religion, which was contrary to their own;
and here the priests and professors are ignorant of the law and times of the Gospel.

And in the days of Ahasuerus, king, Haman was set above all the kings and princes,
and all the king`'s servants bowed to Haman; and Mordecai sat in the king`'s gate,
and the king gave command that they should bow to Haman.
The king`'s servants which were in the gate said to Mordecai,
"`why transgressest thou the king`'s command?`"
and they spoke daily to Mordecai, and he hearkened not unto them:
then the servants told Haman, "`to see whether Mordecai`'s matter would stand;
for he had told them that he was a Jew;`" and when Haman saw that Mordecai did not bow,
nor reverence him, Haman was full of wrath,
and Haman scorned to lay hands on Mordecai alone,
for they had showed him the people of Mordecai, who was a Jew;
wherefore Haman sought to destroy all the Jews throughout the whole kingdom.
Would not many of you christians say that Mordecai was a fool,
because he would not bow to Haman, and do according to the custom of the nation,
but in denying to do such a small thing,
to bring persecution and death upon himself and all the Jews;
and so to be counted stubborn and rebellious, disobedient to the command of the king?
And would you not say, let Artaxerxes`' law go upon him,
"`whosoever will not obey the law of God and the king,
let judgment be speedily executed upon him, whether it be to death, or banishment,
or confiscation of goods, or imprisonment.`"
Ezra 7. Nay, Mordecai obeyed the law of God, and was not rebellious,
though he could not obey the command of the king, to bow to proud Haman;
therefore Haman said to the king,
"`there is certain people scattered abroad among thy people,
in all the provinces in thy kingdom, and their laws are divers from all people,
neither keep they the king`'s laws;
therefore it is not for the king`'s profit to suffer them:
if it please the king to let them be destroyed,
I will pay ten thousand talents of silver.`"
And so Haman got a decree from the king, and sent it forth to destroy the Jews.

Now mind, here it is showed, that the Jews had liberty till this Haman got this decree,
because Mordecai, the Jew, would not bow to him, nor reverence him,
though the Jews`' religion differed from the king`'s and Haman`'s religion: and Hester,
the queen, being a Jew, spoke to the king that the Jews were to be destroyed,
who procured another decree from the king that the Jews should not be destroyed,
which was sent into all the provinces.
And Haman saw Mordecai sit in the king`'s gate, and stood not up, nor moved for him,
Haman was full of fury,
and therefore Haman caused a gallows of fifty cubits high to be made to hang Mordecai on;
and as Haman came back from the king, he came back sorrowful,
for he was to clothe Mordecai, and set him on horseback, and proclaim before him,
and say,
"`thus shall be done to the man whom the king delighteth to honour:`"
then Haman came home and told his wife what had befallen him,
and his wife said, "`if Mordecai be of the seed of the Jews,
before whom thou hast began to fall, thou shall not prevail, but fall;`" yet before,
Haman`'s wife and his friends would have him set up a gallows to hang Mordecai on,
which he was hanged on himself afterwards.

Here you may see the end of a persecutor and destroyer,
who was against liberty of conscience,
and whether is there more Mordecais or Hamans in Christendom,
that would kill and destroy men because they would not stand up and bow to them,
and reverence them?
Nay, would they not say Mordecai was an unmannerly ill-bred clown?
And would they not say he did it on purpose to lie in the king`'s gate,
could he not keep out of the king`'s gate,
for his doings were in danger to destroy all the Jews?
And if Mordecai, the outward Jew, could not bow to proud Haman,
though in so doing he did disobey the king`'s command,
whether or no can the Jew inward in the spirit bow to Haman`'s nature, where it appears?
And whether Haman`'s nature will not persecute, though it be in a christian?
And should christians be worse than Jews,
for christians should not persecute one another for not bowing to one another?
For the angel in the Revelations reproved John for bowing to him,
and told him he was his fellow servant, and said,
"`see thou do it not;`" and bid him worship God.
Rev. 22. So let Mordecai`'s nature reign amongst you, and not Haman`'s,
for mark Haman`'s end; for the true christians are Jews in the spirit, and are brethren;
Christ says, "`you are all brethren;`" for do not you, called christians,
call them impudent clowns, and unmannerly, that will not bow, and have fined many,
and persecuted many?
Is not this like Haman`'s nature, not Mordecai`'s?

Christ, who has all power in heaven and earth given unto him,
and to whom all judgment is committed, has said,
"`that for every idle word men shall speak,
they shall give account at the day of judgment; so by thy words thou shalt be justified,
and by thy words thou shalt be condemned.`" Matt. 12:20,30,37.

And doth not Christ say in Malt.
5, "`be thou reconciled to thy brother before thou offer thy gift.`"
Now if all christians did observe this, who would there be to offer amongst them;
for such as envied their brother christian, and persecuted him,
such were not to offer their gift until they were reconciled to the brethren;
for if they do, God has no respect to their sacrifice,
no more than he has to Cain`'s that envies his brother; and Christ,
who hath all power in heaven and earth, said, "`judge not, lest you be judged;
for with what judgment ye judge, ye shall be judged; and with what measure you meet,
it shall be measured to you again:`" now all you that are so rash in measuring, judging,
and persecuting others, you do not obey this law of Christ Jesus:
now it is clear that none are to judge till the beam be cast out of their own eye,
then they may see clearly a moat.
Matt.
7+++.+++ And doth not the apostle say, that you must "`do good unto all men,`" etc.,
and if you do good, and do not do evil: "`and every man must bear his burden;
and every man is to prove his own work;
and every one shall give an account to God for the things done in his body,
and shall have a reward according to his works,
whether they be good or whether they be evil;
and every man`'s own words shall be his burden: for God respects no man`'s person;
for he that sows to the flesh, shall of the flesh reap corruption;
but he that sows to the spirit,
shall of the spirit reap life everlasting;`" so every seeds-man reaps his own crop,
according to what he sows.
Gal. 6.

And Gal.
5, the persecuting priests and professors used to bring for their persecution;
viz. "`I would they were cut off that trouble you;`"
now this cutting off the apostles`' troublers,
it was with spiritual weapons, for the apostles`' warfare was not with carnal,
but with spiritual weapons; neither did he wrestle with flesh and blood,
so that he could not cut them off with carnal weapons.

And as the apostle saith in Galatians 4, "`he that is born after the flesh,
persecuted him that was born after the spirit;
so it is now:`" so the bondwoman and her son must be cast out,
and not be heir with the freewoman:
now it is clear it is the bondwoman and her son that are cast out,
that are the persecutors; so the persecuting christian may know his mother,
for as it was in the days of Isaac, and in the days of the apostles,
so it is now in these days, that the birth born after the flesh,
will persecute him that is born after the spirit,
and these be the children of the bondwoman which genders to bondage, which is Hagar;
but the children of the freewoman are of Isaac, in whom the seed is called,
and Jerusalem which is above is the mother of all these children which is free,
and gendereth not to bondage, and are not persecutors.

And the apostle`'s command to the Colossians was,
"`if ye be dead with Christ from the rudiments of the world,
why as living in the world are you subject to ordinances; touch not, taste not,
handle not, which all are to perish with the using,
after the commandments and doctrines of men.`"

Now, +++[+++mark,]
is there any ordinances, doctrines, and commandments of men,
those held up by men`'s power?
And will not they that are not dead with Christ, taste, handle, and touch,
and be subject to them, and rage, and be envious,
and persecute them that be dead with Christ, and cannot touch, taste, nor handle,
neither be subject to them?
So, is it not the birth of the flesh that is subject to men`'s doctrines,
ordinances and commandment, which perish in the using of them,
but they that be dead with Christ, and risen, seek that which came down from above,
from Christ, who sits at the right hand of God;
and so their affections are on things which are above,
and after that which doth not perish.
Col. ch.
2, 3.

And though the apostles said to the Corinthians, "`if any man love not Jesus Christ,
let him be an Anathema and Maranatha,`" yet the apostle plainly tells you,
"`that they did not wrestle with flesh and blood,
and the weapons were spiritual and not carnal;`" and he tells you,
"`that he that is born after the flesh,
persecutes him that is born after the spirit,`" and
the spiritual birth has his spiritual weapons,
but the carnal man has his carnal weapons; and so each birth hath his weapons.

And in Zachariah 13:3-4,
which is a place which the persecuting priests and
professors used to bring for their persecuting;
which is as followeth, "`I will cut off;`" saith the Lord,
"`the names of the idols out of the land, and they shall be remembered no more;
I will cause the prophets and the unclean spirits to go out of the land;
and it shall come to pass, when any shall yet prophecy,
then his father and mother which begat him shall say unto him, thou shalt not live,
for thou speakest lies in the name of the Lord;
and his father and mother shall thrust him through when he prophecies.
In that day the prophets shall be ashamed every one of his vision when he hath prophesied;
neither shall they wear a rough garment to deceive.`"

Now these prophets with the rough garment, who speak lies in the name of the Lord,
with their unclean spirits and idols,
were not to be suffered in the land among the children of Israel,
but their father and mother were to run them through which begat them;
but what must the christians weapons be now, that say they are not Jews outward,
but they are ministers of the gospel, and believers in Christ?
Their weapons must be all spiritual, not carnal,
by which they run through the false prophet, that false spirit, and lying spirit,
and so their weapons are spiritual, they do not wrestle with flesh and blood.
Are not these persecuting priests and professors
in Christendom like unto these rough prophets,
that will serve for pay under any one, presbyterian, papists, or episcopal,
as the soldiers used to serve under any one for pay, who wrestles with flesh and blood?
And is it not their work to call to the magistrate
to help them to wrestle with flesh and blood,
and them that are contrary-minded to them?
And are not these like the prophets, that one while they would be for the Jews,
and another while for Jezebel and Ahab; you may see how subject they were to turn,
as you may read through the scriptures.
But the true prophets and apostles were not persecutors, but persecuted.
Was not Moses persecuted by Pharaoh?
But what became of Pharaoh, and others that did persecute him?
and was it not for religion sake?
was not Abel murdered by Cain, the persecutor, about religion?
and though Cain could build cities, yet was a vagabond;
and doth not all persecutors go in Cain`'s way?
Read Jude.

The children of Israel, were oppressed under Pharaoh: mind the end of that oppressor.
And Elijah was persecuted by Jezebel, mind the persecutor`'s end.
The prophet was threatened by Jeroboam; Zachary was stoned to death for his religion.
Was not Micah for his religion thrown down, and his neck broken?
Was not Amos smitten with a club on the temples of his head,
and so brained for his religion sake?
Was not Isaiah sawed asunder in two parts for his religion?
And was not Jeremiah for his religion persecuted oft, imprisoned,
and put in a deep dungeon, and after stoned to death in Egypt?
Was not Ezekiel slain in Babylon, by the duke of the people, for his religion?
And was not Daniel thrown into the den of hungry lions, where he was preserved?
And was not the three children thrown into the fiery furnace for their religion?
And was not Baruch fain to fly, to save his life from king Joash`'s hand,
for his religion, and testimony?
Was not the prophet Urias slain with the sword by king Joiachim?
Was not John Baptist beheaded by Herod the Tetrach?
Was not Stephen stoned to death by the great professing Jews, for his religion?
Was not James beheaded by Herod Agrippa?
Was not Peter crucified at Rome, under Nero, his head downward?
was not Andrew crucified by Aegas, king of Edissa, at Pataras, a city in Achaia?
was not James Alpheus, of Jerusalem, thrown down from high,
and brained with a fuller`'s club?
Was not Thomas slain at Calamina, a city in India,
where the Panims ran him through with a dart?
Was not Philip crucified at Hierapolis, in Asia, for his religion?
Was not Bartholomew flayed alive in Judea, and his skin plucked over his ears,
and after beheaded?
Was not Martha run through with a naked sword in Ethiopia?
Was not Simon crucified?
Was not Jude slain, and John scourged, and often times persecuted,
and put in scalding hot oil?
Was not Matthias knocked on the head with an axe, and beheaded?
Had not Mark, the evangelist, a rope put about his neck,
and by it drawn through the city of Alexandria, till his flesh rent in pieces,
and the stones coloured with his blood, and at last was burnt to ashes?
Had not Barnabas a rope tied about his neck, and there plucked to the stake and burned?
Did not all these suffer for religion, and that which persecuted them,
was it not the birth that is born after the flesh;
and is not this birth now to be seen in Christendom,
which doth persecute him that is born of the spirit, wrestling with flesh and blood:
and so what is become of all these persecutors; doth not the memorial of the wicked rot,
and the memorial of the just live?

Was not Jacob persecuted by Esau because of his blessing? Gen. 27:41.
And was not Joseph persecuted by his brethren, who after banished him,
and sold him?
And was it not for that which God had showed unto Joseph, which after came to pass;
and had his brethren any praise for this work?
Were they not afterwards troubled, and judged in themselves for the same?
And was not Lot persecuted and mocked in Sodom?
Read what became of those temporal blind Sodomites persecuting the just,
then you may say what will become of these spiritual blind persecuting Sodomites?
And if outward Sodom was consumed to ashes, what will become of the spiritual Sodom?
and was not persecution always blind?

And did not Christ say that the persecuting priests and pharisees were "`blind guides,
and led the blind into the ditch?`"
and are not all the persecuting priests and teachers now in Christendom blind guides?
and will any be led by them but the blind, is not the place they lead into, the ditch,
and is not the persecution against them that can see?
And so all the guides in Christendom that persecute, are they not the blind ones,
and doing the works of the night, not of the day, wherein people can see:
and is not the birth which persecutes, that which was born from Hagar`'s womb,
and not born of the womb of the true woman which Isaac came of;
for Hagar was an Egyptian woman that bore wild Ishmael, whose hand is against every man:
so now is not the spirit of Cain, and the spirit of Core,
and the spirit of Sodom to be seen, and of Pharaoh, and of the Egyptians,
and of the persecuting Jews;
and doth not the spirit of all these reign in him that is born after the flesh?

Had not Abraham, that came out of his own country,
liberty to serve God among the Canaanites?
and when Abraham went down into Egypt, had he not liberty there to serve God,
as you may read in Gen. 12. though the Egyptians and Canaanites were bad people.
And had not Abraham liberty to serve God in Abimelech`'s country?
and Abimelech said, "`my land is before thee,
dwell where it pleaseth thee:`" and in what country was there a law made, that Abraham,
Isaac, and Jacob should not worship and serve the God of heaven,
though they differed from the countries`' religion;
and though the children of Israel were oppressed in Egypt,
where do you ever read that Pharaoh made a law that Joseph,
or the people of Israel should not serve the Lord their God whilst they were among them,
though when they multiplied, another king oppressed them with hard labour,
and gave a command to hinder their growth, to kill all the male children,
but the midwives fearing God, did not as the king of Egypt had commanded them,
to kill all the men-children.
Now would not many in Christendom say,
that these midwives were rebellious to the king`'s command,
and that Artaxerxes`' law should be executed upon them, of death and banishment,
for disobeying the king`'s law; for if the pope, or others should make a law,
that they should burn, kill, banish and imprison, would not you be willing,
though it be contrary to your consciences to obey it,
contrary to the command of Christ Jesus, that you should love one another,
and not destroy one another, and you doing so, viz,
obeying the papists`' or other`'s commands to destroy people that fear God;
doth not the midwives that feared God judge you, (who disobeyed the command of Pharaoh,
king of Egypt,) in not destroying the children`'s lives?
Exod.
1.

SAmos 1:14. When Saul, the king, gave command that Jonathan his son should die,
for tasting of the honey when Saul had forbidden
that any man should eat any food that day,
and therefore his son who had tasted a little honey might die;
and the people disobeyed the command of Saul, and said, "`Jonathan should not die,
for he had wrought salvation in Israel;`" so rash oaths and commands,
they that feared God, you may see, could not obey.

Another scripture which the priests and papists used
to bring to put men to death about religion, is Deut. 17.
"`The man that will do presumptuously,
and will not hearken to the priest that standeth to minister before the Lord,
or unto the judge, that man shall die.`"

Now people, this is one of the scriptures that papists used to bring,
because they would not hear their priests; so mark their ignorance,
for do not you know that these were the Jews`' Levitical priests;
and then must not all papists, protestants,
and others be put to death if they will not hear
the Jews`' priests that was to minister the law.
But I say Christ is come, that saves men`'s lives, and came not to destroy them,
which ends the Jews`' priests, and the law by which they were made, Heb. 7,
and their carnal weapons; and so Christ,
who is the priest made higher than the heavens, is to be heard in all things,
and not the Jewish priests, as you may read in Heb. 7. and Acts 7.
And another scripture they bring,
"`the prophet that shall presume to speak a word in my name,
which I have not commanded him to speak, or that shall speak in the name of other gods,
that prophet shall die.`"

Now, +++[+++mark,]
did ever you papists, or others called priests or prophets, ever hear the voice of God,
which you have denied to us, called Quakers, that ever you did;
then is not this sentence fallen upon yourselves, as dead men,
according to your own judgment; but this is your ignorance, Christ is come,
the great prophet, which fulfils the true prophets, who is to be heard,
and is the stone which falls upon the false spiritual prophets,
that have not heard the voice of God, and yet saves the men`'s lives:
and Christ ends the Jews`' carnal weapons, and sets up the spiritual,
by which they do not wrestle with flesh and blood, Deut. 18.

And also in Deut. 13.
another scripture the papists and protestants used to bring for persecution,
"`if there rise up any prophet or dreamer, or give thee a sign and wonder,
and the sign and wonder come to pass, whereof he speaks to thee saying,
let us go after other gods and serve them, and so to forsake the Lord God,
and his commandments, that prophet or dreamer shall be put to death;
if thy brother the son of thy mother, or thy son, or thy daughter,
or the wife of thy bosom, or thy friend which is as thy own soul,
shall in secret entice thee to serve other gods thou shalt not consent to them,
neither pity them, nor spare them, nor conceal them, thou shalt kill him,
and thy hand shall be first upon him to put him to death,
and shall stone him with stones that he die,
because he sought to turn you from the Lord God.`"

And now +++[+++mark,]
people,
these were they that by their dreams and prophesies
would bring people from the living God,
to serve other gods, which were by the Jews`' law to be stoned to death,
though they were their relations, as before mentioned; but Christ is come,
who has ended the Jews`' law, and their weapons, and their religion and worship,
and has set up the gospel, the worship in spirit and truth;
and Christ did not give forth any law,
nor did his disciples after him give forth any law to put men to death,
though they were false worshippers;
for you may see that many did forsake Christ that had followed him,
and many did forsake the apostles which had been convinced, and drew others after them;
yet neither Christ nor the apostles did make a law that such should be put to death;
for Christ rebuked his disciples who would have had men`'s lives destroyed, and said,
"`he came to save them, not to destroy them;`" and his commandment was,
that they should "`love one another,
and love enemies;`" and Christ is the top and cornerstone
which falls upon the false dreamers,
and false prophets, yet saves the men.

And you may read in Jude, and in Peter, there were filthy dreamers in their days, 2 Pet,
yet the apostles did not make a law to put them to death,
though they drew people from the power of Christ; for the apostle tells you,
his weapons are spiritual, and not carnal, they do not wrestle with flesh and blood,
nor war with it, but with spiritual wickednesses,
and it was the spiritual wickednesses in them that made them false prophets,
and false dreamers to draw people from God,
and that the apostles warred against with spiritual weapons,
and did not war with flesh and blood, and stone the creatures to death;
that law of the Jews is changed by Christ that puts men to death about religion,
and Christ has set up his law of love, to love one another, and love enemies,
and though Christ was called a blasphemer, a seducer, a devil, and a madman,
yet he did not make a law to put them to death,
and did not he pray to his Father to forgive them that persecuted him;
but you papists and others, if it should be granted to you,
that prophets and dreamers that draw people from the living God and his commands,
to serve other gods; and you that would have the Jews`' law,
which you bring out of Ezra passed upon them christians;
then doth not the Jews`' law come upon yourselves?
For after you have consecrated bread and wine do you not say it is God,
and so by the Jews`' law are not you to be put to death, who set up another god,
and draw people to it, and so are condemned out of your own scriptures?
Though I say Christ has ended the law and their weapons, and the Jews`' religion,
"`and he is not a Jew that is one outward,
but he is a Jew that is one inward in the spirit,`" as in Romans.

But if you papists should say that they must be put
to death that draw from Christ and his command,
then I say, as I said before, you have given sentence upon yourselves by your own law,
which you had not from Christ, for Christ`'s law is "`love one another,
and love enemies;`" and so from this law and command have you erred,
and by it you are judged, who instead of loving one another, you have envied,
persecuted and killed one another, like Cain, and so are of him that is of the flesh,
that persecutes him that is born of the spirit,
who are neither according to the law of Jesus among the true christians,
nor the law among the Jews; for that birth of the flesh in you,
is that which always did persecute them that gave forth the scriptures;
and Christ the substance of them, and them that live the life of them;
and so that birth of the flesh is that which doth not give forth the scriptures,
neither doth know them, nor can interpret them; and so a command from God is,
"`that flesh must be silent,`" and so the birth of the flesh must be silent,
that will persecute him that is born after the spirit;
and so he that is born of the spirit he must speak, whose weapons are not carnal,
neither doth wrestle with flesh and blood, nor war with it; Christendom mind this.

Josh.
9+++.+++ Joshua let the Gibeonites have liberty, who got it by craft,
though his command from God was to destroy all the wicked people of the land;
and though they were wicked people, and they got it by subtlety,
yet he let them have liberty; and surely christians should be beyond Joshua,
not to restrain those from liberty who desired nothing but liberty to worship God;
for the Gibeonites did not seek for their liberty to worship God,
and therefore there should be a difference betwixt christians
that seek for no liberty but to worship God,
and the Gibeonites; for the christians all profess Christ Jesus and God,
so did not the Gibeonites, and they are not to make one another slaves,
as you may see in Revelation 18, "`which made merchandize of the souls of men,
and slaves of them,`" this you will say was the whore of Babylon that made merchandize;
and you know it is judged by all the protestants that the
whore of Babylon is such as profess christianity,
and to be the papists, and such as are in the same nature;
and you know this is contrary to the primitive christian law, which is,
"`to love one another, and enemies.`"

Boniface the third, universal pope, was set up by Phocas, that murdered Mauritius,
his master, who was the first universal pope got up,
six hundred and two years after Christ, and about twenty years after the Turk got up;
and has not the christians liberty under the Turk, paying their tribute,
and not meddled with for their religion?
For doth not the Turk keep his sabbath day upon the sixth day,
And then his shops are shut up, and all the shops of the Jews and christians are open?
and doth not the Jews keep their Sabbath upon the seventh day in Turkey,
and then all the christians`' and Turks`' shops are open?
And the christians keep their Sabbath upon the first day of the week,
and shuts up their shops, and all Turks`' and Jews`' shops are open.
And here doth not the Turk give liberty of conscience, though he be a heathen;
and should not christians out-strip the Turk,
and give liberty to one another to worship God?
and hath not the Corinthians liberty in Turkey,
and the Greek churches liberty to worship God, and follow their own religion?
and it,
not this doing of the Turks beyond christians that cannot give liberty to one another?
And do not you know that the christians have their liberty in Egypt, and Jerusalem,
though it be in the Turk`'s country, and though they differ from his religion?
And when the Turk conquers any country,
doth not he let the people alone to their religion,
so he can have his tribute and custom?
And also, when Alexander conquered the world,
did not he let the Jew`'s have their liberty?
And when the Romans conquered Jerusalem, had not the Jews liberty?
Read the scriptures.
In the days of Christ and the apostles, there were many sects,
as of pharisees and sadducees among the Jews at that day,
as you may read in the scriptures: and had not they liberty among the Jews,
though they differed from one another in circumstances?
And is there not in the Mogul`'s country many sorts of religion?
Yea, and have not some christians liberty there to serve God;
of whom it is reported by one that travelled there,
he has sixty religions there that have their liberty without disturbance,
paying their customs?
And should not christians be of a more noble spirit than he?
Have not the christians liberty in Persia?
and among the Turks, is there not many kinds of religion amongst them,
that differ in some things, seeing they all own God and Christ Jesus?
and therefore should not they be of a more noble spirit than the Turk, Mogul,
and the Persians?
and hath not the Arians and the pope been the two first that raised persecution,
one christian against another, contrary to the law of Christ, love enemies,
"`and love one another?`"
and so has not Christ`'s law of love been laid aside?

And after that Adam and Eve transgressed the law of God,
God let Adam have liberty in the earth, though he had not of the paradise of God;
and so though christians cannot conform to your church
in tenderness of conscience towards God,
you may let them have liberty of the earth; and though Ishmael, the wild man,
had not liberty in Abraham`'s family, he had liberty in the wilderness.

And concerning the act that is made against the Quakers, and others;
as for us that are called Quakers, this we say,
we do not meet to plot nor contrive against the king,
neither do we hold dangerous principles, but the truth;
neither do we meet to terrify the king`'s subjects,
but seek the good and eternal welfare of the king, and all people;
and we do abhor and detest all plots and plotters, and workers of darkness;
and whereas the same act prohibits above five to meet together,
had you been in the days of Christ and the apostles,
this act would have taken hold upon him; for you know he had twelve apostles,
and seventy disciples, who often met together.

And also it would have taken hold upon the Ephesians, Phillippians, and Corinthians,
and all the other churches that did meet together:
and do you think that they would not have suffered either by heathen or christians,
before they would have broke up their meetings, or Christ have denied his disciples?
If some christians, or heathen,
that differed from them should have made a law that those christians
that differed from them should not meet above five at a time;
and is not, and would not that have been contrary to Jesus, who said, "`love one another,
and enemies,`" who has all power in heaven and earth given unto him;
for do you ever read that Christ and the apostles made a law to punish,
or to make any one suffer that did not hear them,
or differed from them in religion and worship?
And did you ever read that the Jews made any law
that not passing five might meet of the christians,
though the christian religion was contrary to theirs?
and so seeing that God will judge the world in righteousness,
signifying that there is something in man and woman which
answers the righteousness which they do transgress;
and he will judge the world by the man, Christ Jesus, according to the gospel,
that is according to the power, shewing,
that there is something in man that answers the power which is the gospel,
and is invisible; and they that walk in the power which is the gospel,
they ought to have the liberty of the gospel, which is the power of God,
before the devil was, where all bondage is;
and so all christians that own God and Christ Jesus,
and his gospel which is the power of God before the devil was,
they ought to have the liberty of the gospel, for the liberty is in the power of God,
and they that be in the power of God, the gospel,
cannot but give liberty to them that be in the power of God,
for the bondage is in that spirit that is out of the power of God;
and the liberty is in Christ Jesus who has all power in heaven and earth given unto him,
and there to stand fast in the liberty wherewith Christ
hath set them free from the bondage of the world;
shewing, that it is the world that brings into bondage, and not Christ.

They that wrestle with flesh and blood about religion,
are neither in the apostles`' spirit, nor power, nor doctrine;
and if the law reach but upon the outward man for his action, then it will follow,
and is clear, that the inward man after God must have his liberty,
which inward man brings the outward man conformably to the righteousness,
and to a righteous man`'s state, which the outward law was not made for;
so then it is not to be excuted upon the righteous man.
So all magistrates must make a distinction, and put a difference in this case;
for though kings`' powers,
and magistrates with their laws take hold upon the outward evil actions,
and the outward man, the evil spirit leading of him to do evil; but Christ,
who is the King of kings, and has all power in heaven and earth,
he must have the rule in the heart of the spiritual man, and God will dwell in man,
and walk in man, which is his temple,
and therefore he must have the rule in the conscience,
and in the heart in matters of his religion, and worship, and faith,
seeing God is the giver of it, and Christ is the author and finisher of it;
and the apostles themselves said,
"`they had not power over men`'s faith,`" which God was the giver of,
and Christ the finisher of;
and a man coming to subdue that evil spirit in him by the power of God,
and to have it mortified, and the actions that flowed from it,
then the man led by the spirit of God,
he is not under the law which is made for sinners and disobedient,
and not for the righteous; and Christ said,
"`christians should not exercise lordship one over another
as the Gentiles had done;`" and the apostle says,
"`be not many masters, for you have one master, even Christ,
and they were not lords over God`'s heritage, but they were helpers of their joy,
and they should not lord it over their brethren,
for they were all brethren;`" and this he spoke in matters of religion,
"`for they had one Lord, even Christ Jesus, by whom all things were made,
and one God who is over all, and in you all blessed forever.`"
And so if Christ be in you, and God be in you,
he must have the rule in matters of religion; for his religion is pure from above,
from himself, he must have the rule of the faith, who is the author of it,
and Christ must have the rule of his worship,
who is set up above sixteen hundred years since, in spirit and truth:
for could the Caldeans find any thing against Daniel, save in the matters of his God;
and could you ever find any thing against the Quakers, but concerning their God,
and the worship of him?
Could Cain find any thing against Abel, but the matters of his God;
or Jacob`'s sons against Joseph, but concerning his God?
Or could any fault be found with Isaiah, Jeremiah, and Elisha in their days,
but that which concerned their God?
or could they find any fault with Christ or the apostles, for which they persecuted them,
but only things concerning God and Christ?
and ever since the apostles`' days the beast, the whore, the false prophet,
and antichrist, which has drank the blood of the martyrs, prophets,
and saints who have kept the testimony of Jesus:
was not all this persecution upon them concerning their God and Christ Jesus?
for what fault could they find in them more than they did in Daniel concerning his God?
and so you may read through all the scriptures of Abraham, Isaac, and Jacob,
and the rest of the prophets, Moses, and Aaron, and Noah, and Lot,
did not their sufferings come upon them concerning their God?
For what fault could they find with them?
Or what fault could Pharaoh find with Moses and Aaron, but of things concerning their God?
or Sodom with Lot, or the old world with Noah, but in things concerning their God?
and so it is clear all along,
the birth of the flesh has always persecuted the birth of the spirit, as it is written,
"`he that is born of the flesh, persecutes him that is born of the spirit.`"

And Christ Jesus who set up his worship above sixteen hundred years since, who said,
"`the hour is come, and now is, that they that worship the Father,
must worship him in spirit and truth,
such God seeks to worship him;`" and Christ and the
apostles never altered this worship to this day,
which worship was set up before the many worships among christians were set up,
and will stand when they are gone;
and Christ is the judge in this worship set up by himself, and not by man;
and Christ gave no law, nor command,
or order to the apostles to persecute any that did not worship according to his worship;
but you may see all the worship set up by men, one time or other,
most of them have forced people to their worship, and persecuted for not conforming,
and that forcing makes but hypocrites from one worship to another;
and mark the end of all those worships and worshippers in the world,
where there has been force and persecution,
that which men make and set up they are judge of, and judge in;
and is not this to bring people to worship the works of men`'s hands?
and the worship that Christ set up he is the judge of, which is in the spirit and truth.

And so it is plain it is Cain in the first birth that has
persecuted Abel the second birth in all ages;
and this Cain, the first birth, and persecutor of Abel, God hath not,
nor never had respect unto his sacrifice who is Cain`'s offspring, the first birth,
and not of Abel`'s: and so Cain may read his birth and antiquity,
and suffering Abel may read his birth and antiquity, whom God had and hath respect unto,
and his sacrifice.
Yet had not Paul liberty at Rome,
among the heathen Romans that were of a different religion from Paul,
to preach the gospel two years together, in his own hired house,
as you may see in the Acts.

The law was added because of transgression, and not made for the righteous,
but for sinners and disobedient: +++[+++mark,]
because of transgression and disobedience was the law added;
man and woman in the beginning disobeyed and transgressed the command of God,
and so lost the image of God and his righteousness, and the paradise of God;
and so the law which is just, holy, and good,
came upon disobedient and transgressing man and woman,
which law served until the seed came,
and Christ is the end of law for righteousness sake, to every one that believeth.

And seeing that because of transgression the law was added,
then they that do not transgress, the law doth not take hold on,
neither are they under it.

And seeing the law was made for the disobedient and sinners,
then he that doth not disobey God`'s command, but is led by the spirit of God,
is not under the law.

And they that keep God`'s commandments, and do not transgress, are not under the law;
and therefore must not magistrates make a distinction,
and put a difference betwixt the transgressors and disobedient,
and the obedient and them that doth not transgress?

And now christians, papists, and others,
what say you to the apostles that disobeyed the command of the council of the Jews,
in preaching again in the name of Jesus, after they had commanded they should not preach,
Acts 4, would not you say that Artaxerxes`' law was to be executed upon them,
and they to be imprisoned, banished, and put to death, or their goods confiscated?
and also would not you have said,
that this law of Artaxerxes was justly to have been
executed upon Daniel and the three children,
for disobeying the king`'s command?
Would not you say that it should be executed upon the midwives
for not executing Pharaoh`'s command in killing the men-children,
who brought this law to be executed upon christians?

Now Artaxerxes, his heathen law, and God`'s law, was for the Jews to build the temple,
you that call yourselves christians, are you Jews?
And are you going to build the Jews`' temple,
which law was before Christ came in the flesh?
For except you go to fulfill Artaxerxes`' law, and to build the temple,
Artaxerxes`' law is against you; for no one`'s goods is to be spoiled,
or any to be banished, imprisoned,
or put to death for not going to build the temple of the Jews at outward Jerusalem now;
"`for he is not a Jew that is one outward;`" for the Jews`' temple is ended by Christ,
and the law which held up the Jews`' religion, temple and priest;
for by the Jews`' law you never read that any were to be put to death, or banished,
and goods spoiled, for not repairing or building the temple, at outward Jerusalem.

But Jerusalem that is now, that is below, is in bondage with her children by the Turk,
as she was under the Roman`'s power in the apostles`' days:
But Jerusalem that is above is free, and is to be free in her religion, faith,
worship and gospel, who is the mother of us all the true worshippers,
which has a new command from Christ, which is not to banish, kill, put to death,
spoil goods, but,
"`to love one another,`" and this is the law of Jesus
who has all power in heaven given unto him,
who is King of kings, and Lord of lords; and so his command is to be observed,
and he is to be heard in all things, and not Artaxerxes`' law, Ezra 7, nor the Jews,
nor Ezra, the priest, with his law to build the Jews`' temple.

And the apostles, in Rom.
1, speaks of such that be without natural affections,
as such as are without natural affections, as has not affections to nature,
but will destroy, prison and persecute the workmanship of God`'s hands,
and God`'s creatures he has created, about their worships and their religion;
and such as are without natural affections are such as can never be appeased,
nor be merciful, but merciless, and such destroy the good nature in themselves,
by which they have not natural affections to their natural brethren;
for Cain destroyed the natural affections in himself,
before he destroyed his natural brother; for nature is one, and would not destroy itself,
and it hath affections to itself; but the serpent going out of truth,
leading man and woman from the truth, so corrupting and destroying nature in themselves,
by which they are led by an evil spirit to destroy nature without them,
and have not affections to it, and this has been the work of the enemy,
and all the killers and persecutors about religion
and worship in the whole world to this day;
for they that destroy nature about such things, cannot have affection to nature,
but are without natural affections, and they that are without natural affections,
cannot know the divine things given forth by the holy men of God, Christ,
and the apostles, from the beginning to the ending of the scriptures;
and they that are without natural affections cannot love the brotherhood,
nor love one another, nor enemies; therefore, such do not keep the command of Christ;
and therefore, they that do love one another, and love enemies,
have affections to nature,
and would not have one another destroyed which are God`'s creatures,
and so love all things which God made, whose works praise him;
and such have not only natural affections to nature, but the divine nature,
and the affections set upon things which are above,
so they have affections to things of nature, and affections to things above;
so as the apostle says, "`he that says he loves God and hates his brother,
is a liar;`" so all that say they love God, (in Christendom,) what follows,
what are they?
What says the apostle, "`he is a liar that hates his brethren;
for how can he love God which he hath not seen,
and hate his brother which he hath seen;`" so mark this sound reason,
"`whosoever hateth his brother is a man-slayer,
and ye know that no man-slayer hath eternal life abiding
in him;`" so take notice of this great apostle`'s words,
all Christendom, you that hate your brethren, and persecute them, the great apostle says,
and tells you, "`you are man-slayers,
and have not eternal life abiding in you,`" 1 John 3. "`And
he that hateth his brother is in darkness until this time,
and he that loveth his brother abideth in the light;`" and mark Christendom,
"`he that hateth his brother is in darkness, and walketh in darkness,
and knoweth not whither he goeth,
because that darkness hath blinded his eyes:`" so
now consider this all ye that do hate your brethren,
what the apostle says; your path is not in light, but in darkness,
and you do not know whither you go, but darkness hath blinded your eyes;
and therefore lay away hatred, that your eyes may be opened,
that you may come out of darkness, and walk in the light,
that you may keep the command of Christ, which is, "`to love one another,
and enemies,`" and that you may come out of darkness, and know whither you go.

And so, is it not clear, that they whose eyes are blinded, who walk in darkness,
hating their brethren, is not this hatred come from the serpent, who was the first hater,
who hated Adam and Eve`'s prosperity, and dominion over all things God made?
Is not this darkness they walk in, that hate their brethren, from the prince of darkness,
the serpent?
And is it not he that has blinded their eyes,
who are hoodwinked with the serpent`'s hatred and darkness,
that they do not know whither they go; but they that walk in the light,
and love the brethren, know whither they go,
and in them there is no occasion of stumbling?
And how can they which hate their brethren,
and walk in the darkness which has blinded their eyes know the scriptures,
which holy men spoke, as moved of the Holy Ghost?
and has it not been the work of them that walk in darkness to hate and persecute such?
And has not the original been from the serpent, and not from God and Christ, which says,
"`love one another, and enemies?`"
This is in love to you all, for your eternal good.

[.signed-section-signature]
G+++.+++ F.
