== To All Professors in the Christian World:

[.heading-continuation-blurb]
Also to the Jews and Turks throughout the whole world;
that they may see who are the true worshippers of God,
that he seeks, and in what he is worshipped.

[.heading-continuation-blurb]
An exhortation to them to read it over, that they may see what they have all grieved,
vexed, and quenched, and what they have walked despitefully,
and rebelled, and kicked against, and stopped their ears, and closed their eyes to;
so that they may all return again, and turn within,
and see what they have professed and not possessed;
so that they may come to be the true possessors of the Truth,
and true worshippers in the Spirit of the True and Living God,
who is a Spirit, which is the Perfect Worship,
which Christ the Truth and Perfect One set up, above 1600 years since.--By G. F.

When the woman of Samaria said unto Christ, our fathers worshipped God in this mountain,
which was the mountain where Jacob`'s well was; and said she again,
you say that at Jerusalem is the place where men ought to worship;
but Jesus said unto her, "`woman, believe me,
the hour cometh when ye shall neither at this mountain,
nor yet at Jerusalem worship the Father; ye worship ye know not what,
we know what we worship, for salvation is of the Jews; but the hour cometh and now is,
when the true worshippers shall worship the Father in spirit and truth,
for the Father seeks such to worship him; God is a Spirit, and they that worship him,
must worship him in the spirit and the truth.`"
Now mark this, all men and women that are called Christians, or Jews, or Turks,
or others, and see if you know what you worship,
for there are many worships in the world made and set up by men,
and so men and women worship they do not know what,
that do not worship God in spirit and truth, as Christ saith:
now you may see there was a worship at the mountain where Jacob`'s well was,
and also there was a worship at Jerusalem at the temple,
set up many years after Jacob died in Egypt, by the Jews`' children,
and the plague and the punishment that was to come
upon them that would not go up to Jerusalem,
and keep the feast of tabernacles and to worship there from year to year,
you may read Zachariah 14. And in the Acts it is said,
there was in Jerusalem out of every nation under Heaven,
which worshipped at Jerusalem in the time of pentacost,
many of many strange languages and tongues,
and were amazed at the apostles that preached Christ,
Acts 2. Now in John 4. there you may see how that Jesus Christ
put down the worship at the mountain where Jacob`'s well was,
where the forefathers worshipped, and also put down the worship at Jerusalem,
where the Jews`' fathers worshipped, and where they came out of other parts to worship,
and if they did not, the Lord poured his plagues and judgments upon them,
as in Zachariah 14. now when Christ put down these two worships,
at the mountain where Jacob`'s well was, and at Jerusalem,
he set up another worship in the spirit and in the truth, and said,
"`such the Father seeks to worship him;`" and that hour that he
put down these two worships at the mountain and Jerusalem,
the same hour he set up a worship; for his words are, "`not at Jerusalem,
nor at this mountain shall ye worship the Father, believe me,`" saith Christ:
so they that hold up a worship at that mountain, or at Jerusalem,
or a worship of their own making, worship they do not know what,
and do not believe in Christ, for Christ`'s words are, "`woman, believe me, +++[+++mark,]
the hour cometh, when ye shall neither in this mountain, nor yet at Jerusalem,
worship the Father, for ye worship ye know not what.`"

So here it is clear, neither at the mountain nor at Jerusalem is the Father worshipped;
for Christ Jesus has put down those worships, yea, at Jerusalem,
which was once commanded of God,
and therefore those that God never commanded cannot stand; and Christ`'s words are,
"`But the hour cometh and now is;`" mark +++[+++now is,]
then it began, that hour when he put down the worship at Jerusalem, and the mountain,
and such worshippers that did not know what they worshipped;
"`But the hour cometh and now is,
(saith he,) when the true worshippers shall worship
the Father in the spirit and in the truth,
for the Father seeks such to worship him; for God is a Spirit, and they that worship him,
must worship him in spirit and in truth.`"

Now +++[+++mark,]
all people upon the earth, worshippers of all sorts, who worship you do not know what,
that be out of this true worship; here you may see that Christ set up a worship,
and it is above sixteen hundred years since it began;
and here you may see who the true worshippers are,
that worship the Father in the spirit and in the truth;
and here you may see who they are the Father seeks to worship him,
such as are in the spirit, and such as are in the truth.

So it is clear that none are the true worshippers of the Father,
but who are in the truth that the devil is out of, for the devil abode not in it.
Secondly, None are the true worshippers of the Father, but such as are in the spirit;
yea, in that spirit that mortifies sin,
and that spirit by which the body of death and the sins of the flesh are put off;
so it is clear that all who be out of the spirit and out of the truth,
are the false worshippers, and not the true,
and such the Father seeks not to worship him; for God is a Spirit,
and they that worship him, must +++[+++mark,]
worship him in the spirit and in the truth; for God is a Spirit,
and he is the God of truth, that changeth not; and therefore,
every man and every woman must come to truth in their inward parts,
and come to the Spirit of God in their own particulars, and not grieve it, nor quench it,
nor vex it; for in the spirit and in the truth they must worship the God of truth,
and God who is a spirit: and +++[+++mark,]
all men and women must be in the spirit and in the truth,
if they worship the God of truth, in the spirit and in truth;
and this worship that Christ Jesus set up above sixteen hundred years since,
breaks down all the worships in the whole world that men have set up; and the Jews`',
and the beast`'s, and the dragon`'s, that are out of truth and the spirit of God;
so every man and woman in the whole world must come to the truth in their inward parts,
which truth they receive from Christ the truth,
in which truth they must worship the God of truth;
and every man and woman in the world must come to the spirit of God in their hearts,
by which spirit they must have an understanding to know God, who is a spirit,
and so to worship him in the spirit.

Now there is the worshipping of angels, the will-worship,
the worship that was at Jerusalem, and the worship in the mountain,
the worship of the beast and the dragon,
the worships that men and all nations have invented;
but the worship in the spirit and the truth,
which Christ set up above sixteen hundred years since, is the true worship,
and the worshippers therein are such which the Father seeks.
So I say, this worship that Christ set up in the spirit and in the truth,
and the true worshippers that worship in it, that the Father seeks,
are set above all the will-worshippers, the worshippers of angels,
and the worshippers of the beast and of the dragon,
and above the worship at the mountain, and Jacob`'s well, and Jerusalem`'s worship,
and all the worships that men or nations have invented;
so every man or woman in the whole world must come to the spirit of God,
and to the truth, which comes from Christ in their inward parts,
if they be the true worshippers that worship God in the spirit and truth,
or to be such as he seeks to worship him; for God is a spirit,
and he is the God of truth,
and therefore they must be all in the spirit and in the truth,
if they be the true worshippers, and do worship God, the God of truth, who is a spirit,
for such he seeks; and all that are out of the spirit,
they worship they do not know what, and he seeks not such,
and they are not the true worshippers; and there are all the sects,
and such as grieve and quench the spirit,
and come not to the truth in their inward parts, and such as stop their ears,
and close their eyes to that of God in them, like the Jews and pharisees,
and kick against that which pricks them, like Saul, and such as hate the true light,
that enlightens every one that comes into the world,
and walks despitefully against the spirit of grace,
and such as rebel against God`'s spirit that is given unto them to instruct them,
and to profit withal.
Neh. 9. All such worship not God in the spirit and truth,
"`but they worship they know not what,`" as Christ saith;
therefore must every man and woman in the whole world come to the true light of Christ,
and the spirit, and the grace in themselves,
if they be the true worshippers of God in spirit and in truth.

And the worship that Christ Jesus, the Heavenly Man, the second Adam,
the Lord from heaven, the Spiritual Man, set up above sixteen hundred years since,
in the spirit and in the truth, for the true worshippers to worship in,
whom God seeks after; I say it is an infallible worship, or an eternal worship,
for the truth is infallible, and the spirit of God is infallible and eternal,
in which they worship the eternal God and truth,
and the spirit of God changes not though men may change from it:
for the truth makes no sects, or schisms, for all sects and schisms be out of it;
and the spirit of God makes no sects, or schisms,
for all sects are out of the spirit of God, and out of truth; for the dragon,
and the devil, and the destroyer, and the beast, are out of truth, and his worshippers,
and the will-worshippers; for the devil abode not in the truth;
and all they that worship they do not know what,
be out of the truth and the spirit of God.
So, had all Christendom kept to the spirit and the truth,
that the apostles and primitive church were in,
they would have kept up Christ`'s worship, and in it, as the apostles did,
that he set up above sixteen hundred years since,
and there would have been no sect among them,
but they would have kept in the substantial worship; for truth is substantial,
and truth doth not change, and the spirit of God doth not change,
but brings people to be substantial in the substantial worship,
and in the spirit they would have had a fellowship, and a unity.

Therefore, for all people to come out of the sectary worships, and will-worships,
and worshipping of angels, worshipping they do not know what;
and to be the true worshippers whom God seeks, they must all, every man and woman,
come to truth and the spirit of God in their own hearts,
by which they may worship God in the spirit and truth, which the devil is out of,
and to be the substantial worshippers that Christ
set up above sixteen hundred years since;
for all that do not worship God in the spirit and truth, are in the false spirit,
and all that do not worship God in the truth, they are out of the truth,
and of him that is out of the truth; for Christ Jesus, that signifies a Saviour,
and anointed of God, who came to redeem man from iniquity, and save man from sin,
and finish transgression, and to be man and woman`'s mediator,
and to purchase man from transgression, and shed his blood, and died for man,
who bruises the serpent`'s head that has kept man in captivity, and leads him captive,
and sets man free from his prison, death, darkness, and bondage, who is out of truth,
and so Christ the truth, sets up a worship for man and woman in the truth,
and in the spirit that the devil is out of; and this, I say, is the substantial worship,
where the devil cannot come with his false, lying, murdering spirit of error,
he cannot come into the truth, nor into the spirit of God.
In which truth and spirit the true worshippers worship the God of all truth,
who is a spirit; and this I say is the true and safe, and substantial,
and infallible worship that Christ set up, who is the truth,
and a quickening spirit above sixteen hundred years since,
and in which worship there is neither sect nor schism, nor discord,
for all that is out of truth; for concord is in the spirit and in the truth,
for the unity and the fellowship is in the spirit, and it is called the bond of peace;
and in this spirit and truth they must worship the God of truth, who is a spirit;
so the blind Jews, with the scribes, priests, and pharisees,
that think to go to worship at Jerusalem,
Christ tells your forefathers above sixteen hundred years since,
that God was not to be worshipped there, nor at the mountain; and therefore,
you are to believe in him your Saviour, and own his worship in the spirit and truth.

Now, if all Christendom have the scriptures of the new testament,
as the Jews had the old, and do not worship God in the spirit and in the truth,
which the devil is out of, but make worships of their own, and force men to them,
they worship they do not know what;
for it was the dragon and the beast that persecuted about worship, both in the Jews,
in the days of Christ, in the flesh,
and since in the days of his spiritual appearance by the Holy Ghost,
such as were out of the spirit of Moses and the prophets, and Christ and his apostles:
so as the outward Jews were to go to outward Jerusalem to worship yearly,
or else their eyes were to consume in their heads, and their tongues in their mouths,
and God`'s plagues and judgments were to come upon them.
Zach.
14:12. So all they that are not in the spirit, and in the truth,
by which they must worship the God of truth, who is a spirit,
and so come to heavenly Jerusalem that is from above, the mother of all true christians:
I say, that eye that is out of the truth, and out of the spirit,
is under a plague and shall consume in their heads and their mouths;
for all the Jews in the spirit and truth in their inward parts,
that worship God in the spirit and truth,
such are the true worshippers that the Father doth seek to worship him,
and now God has found many, praised be his name forever;
I say they do come to Jerusalem that is above,
the mother of us all that are the true worshippers,
and do see Jerusalem that is below in bondage with her children.

Now all people being dead in Adam, and gone astray, Jew and Gentile;
and Christ the seedsman being come, who sows his seed upon all grounds,
and is come to make them to see, that did not see;
and to make them blind that said they saw, and saw not, as there is too many now a-days;
and his grace hath appeared unto all men, and hath enlightened all,
and tasted death for all,
and the manifestation of his spirit is given to every man to profit withal;
so here Christ hath made no sects,
but they are the sect-makers that go from his true light, and go from his word and seed,
and go from the manifestation of his spirit that is given to every man to profit withal;
and Christ has given to every man a measure according to his ability,
and so they that go from their measure that Christ hath given unto them,
are the sect-makers, and are in the schisms,
then they may say that they have not ability; but they have ability to do evil it seems,
and therefore, these are they that turn against the true worshippers; therefore,
every man and woman, that are the true believers in Christ Jesus the Saviour,
they come to their measure that Christ hath given them,
the light and seed that Christ hath sown in their field, their hearts,
and to the Holy Ghost that does reprove them,
and the manifestation of the spirit of God given to them to profit withal;
and if they be the true worshippers in the spirit and truth, and come out of the sects,
and give over making sects.
Then there would be no sect in Christendom, nor in the world, nor among the Jews,
if they all would come to the truth in their inward parts, to the spirit of God within,
and in that spirit and truth to worship God, who is a spirit, and who is the truth,
then they would worship in that which the devil cannot come into,
for he is out of the truth; so I say,
if all people in the whole world would come into the spirit, and come into the truth,
in which they are to worship the God of truth,
they would be all in unity in the truth and in the spirit;
so as all people have been in the deceit and falsehood, out of the truth,
and in the false spirit, out of the true;
so must all people men and women come into the true, out of the false spirit,
and come into truth out of the falsehood and deceit,
if they are the true worshippers that worship God in the spirit and in the truth,
for such he seeks to worship him; for this, as I said before, is the substantial worship,
that Christ set up for his redeemed ones,
and saved ones that had been under the power of Satan, and his false spirit,
who had been deceived by him who abode not in the truth; therefore,
Christ the Saviour and Redeemer, who is the truth, that bruises the head of the serpent,
sets up a worship in the spirit and truth, which the devil is out of;
and this is the perfect and substantial worship; for truth is perfect, and will stand,
and the spirit of God, which the true worshippers in the spirit and the truth worship in;
I say, this worship in the spirit and the truth will stand,
when all the worships out of the spirit and truth are gone, which Christ the Son of God,
the truth which came from God, set up above sixteen hundred years since.
Blessed and praised be God through him forever.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 9th of the 8th month, 1673.

All the worships that have been made by man, and set up by man,
and compelled thereto by man,
(in the world,) since Christ hath set up his worship in the spirit and in the truth,
above sixteen hundred years since, to worship God in who is a spirit,
in the spirit and truth which he seeks,
and who are the true worshippers they are all alike,
and from the same spirit that set up worships before Christ came in the flesh,
who had not the spirit of Moses and the prophets, as these now say they have,
not the spirit and power the apostles had,
and yet they persecuted them that were in the spirit of Moses and the prophets;
and all these say now that have made worships, and set them up,
and compelled and persecuted others for not conforming, and put them to death about it;
I say, they say and confess they have not the same power and spirit the apostles had,
therefore, they be in another power, and another spirit, and in an unclean ghost,
and compel people to it; for there is but one Holy Ghost that leads into all truth,
and one spirit that baptizeth into one body, and one power of God, and one truth,
which the devil is out of; so all that worship the God of truth,
must be in the spirit of God, in the truth, the devil is out of;
and these be the true worshippers of the God of truth, who is a spirit,
and this truth and spirit is within them, and they in it;
and they are all false worshippers that be out of truth, and out of God`'s spirit,
and they worship the works of their own hands, and they do not know what;
and all that have not, and are not in the same power, spirit, and Holy Ghost,
that the apostles were in, and the same truth, you are not the true worshippers,
though you may talk of all the words of the scriptures of truth, and give your meanings,
and sell them for so much a-year, and make sermons of them, and prayers of them,
and songs of them; yet, I say,
if you be not in the same spirit and power that they were in,
the prophets and apostles that gave them forth, and have not the spirit of Christ in you,
you are none of Christ`'s, nor none of his true worshippers,
that worship God in the spirit and in the truth, as the apostles did,
but you are like unto all other national worships,
and the Jews that opposed Christ the truth and spirit, and the Spiritual Man,
and so his spiritual worship in truth, and his true worshippers,
as sufficiently hath been seen;
and so all the worshippers that be out of the spirit of God and his truth, are,
as I said before, like unto those worshippers before Christ came in the flesh,
that persecuted the prophets,
and persecuted Christ in the flesh above sixteen hundred years since, and his apostles,
and now such persecute him in the spirit;
and such may pretend to worship God like the Jews, but grieve, and quench,
and vex the spirit of God and walk contrary to the truth in themselves,
and such will never come to be the true worshippers that Christ the truth set up,
in the spirit and in the truth that the devil is out of,
that God who is a spirit seeks to worship him, until they come to the spirit and truth,
and walk in it in their own particulars; and so all the true worshippers,
that come out of the false worships, that worship they do not know what,
they must be in the power, and the spirit, and the Holy Ghost that the apostles were in,
who worship God in the spirit and in the truth that doth not change,
for truth doth not change, though men have changed from it,
and the worship that Christ hath set up in it; and the spirit of God doth not change,
though men and women have changed, and erred from it,
and gone into so many sects and worships, and persecute one another about them;
and God doth not change,
nor his worship in the spirit and truth which the devil is out of;
God`'s worship which Christ set up doth not change, nor doth Christ change,
nor doth God change, who is to be worshipped in spirit and truth that doth not change;
and this is the safe, perfect and infallible, catholic or universal worship,
for truth and the spirit of God is perfect;
so men and women must worship in that which is perfect: God who is perfect,
and Christ who is perfect,
set up this his perfect worship above sixteen hundred years since;
and men are gone out of his worship and gone into imperfect worships;
so every man and woman must come to the measure of
the perfect spirit and truth in their own hearts,
if they be the true worshippers of God in the spirit and truth, and with the spirit,
and with the truth within they must feel the God of truth who is a spirit, at hand,
with them, and Christ the truth, that set up this worship, as I said before,
in the spirit and in the truth, and they that be in the spirit and in the truth,
are the true worshippers, and can say, the Lord has sought them,
and the Lord has found them to worship him in his spirit, and in the truth,
that the devil is out of, and can praise God through Jesus Christ,
whom God sent above sixteen hundred years since, to set them up this worship;
for Christ that is the Saviour and Redeemer from sin and iniquity,
set up an established worship in the spirit and in the truth, which the devil is out of,
by which truth, men and women are made free, they are God`'s freemen and freewomen,
that are made free by the truth,
and serve and worship God in the spirit and in the truth that makes them free,
which is our established worship, which is set over the head of the serpent,
and the heads of the beast, and the whore that abides not in her house,
and the head of the serpent, which is out of truth, and over his power, is the truth,
in which spirit and truth all the true worshippers worship God; so as Christ saith,
"`if the truth hath made you free, then are you free indeed;`" for all captivity,
thraldom, bondage, and slavery, is out of truth, and under the head of the serpent,
whose head Christ the truth, bruises;
so the true worshippers worship God in the spirit and in the truth,
which makes them free, and can praise God through Jesus Christ for his worship,
and for their freedom through him.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.the-end]
End of Vol. 4
