[quote.epigraph, , 2 Cor. 4:1-2]
____
Seeing we have this ministry, as we have received mercy, we faint not:
but have renounced the hidden things of dishonesty, not walking in craftiness,
nor handling the word of God deceitfully, not by the manifestation of truth,
commending ourselves to every man`'s conscience in the sight of God.
____

[.style-blurb, short="Concerning the Living God of Truth"]
== Concerning the Living God of Truth; and the World`'s God, in Whom There Is No Truth

[.heading-continuation-blurb]
And also, how man and woman fell from the living God;
and how the Serpent became the God of the World.
And how God was the teacher of man and woman, who made man and woman perfect:
And when they forsook God`'s teaching, and followed the serpent`'s teaching,
they became unperfect.
And how Christ cometh to destroy the devil,
and bring man and woman under God`'s teaching again, who taught them in the beginning.
And how the son of perdition did appear.
And what the glory of the world is, that the devil would have given to Christ,
if he would have worshipped him.
And how the world`'s god came to have a kingdom, and what it standeth in,
and must have an end: And what Christ`'s kingdom stands in, which hath no end.
And how the gospel is bad news to the world`'s god; but good news to them that believe.
And how the Old Testament was read among the Jews in their mother-tongue;
and so ought all the Christians to read the New Testament
among the Christians in their mother-tongue.

[.heading-continuation-blurb]
With some Queries for all to consider of,
in the latter end of this book; and other remarkable things. By G. F.

The Lord God of heaven and earth, who is the creator and maker of all things therein,
which created and made all things good; so he is the great Lord of all,
both of things in heaven, and things in the earth,
and therefore all things are to be subject to the great Lord, especially man and woman,
whom he made in his own likeness and image.

So he is called God Almighty over all his works;
and the Lord God Almighty to oversee all his works, who is present everywhere,
God the father, who is the nourisher and preserver of all creatures that he hath made,
and takes care for all, who gives life, being and breath unto all,
and made the earth to be inhabited,
and placed man upon who is the God of the spirits of all flesh.
So he hath given man and woman a spirit and breath to dwell upon the face of the earth,
and to serve and worship him in: So that the earth is the Lord`'s,
and the fulness thereof; and man and woman is the Lord`'s, which he made in his image,
who gave all the creatures into the hands of man and woman, which are his,
to serve men and women; and men and women to worship and serve God,
and not to serve the creatures, but their Creator; nor to make images, or likenesses,
or gods, of any creature that God Almighty had created;
but that they all should serve man and woman, and man and woman to serve God the Creator,
who is above the creatures.

For God placed man and woman (whom he had made in his likeness)
above all the rest of the creatures that he had made,
and in his power gave them dominion.

So when God Almighty had made and created all things, he saw that they were good, yea,
very good, and blessed them; and made man and woman in his own image and likeness,
and set them in dominion above all that he made, and they were made good and perfect,
and he blessed them.

So man and woman were happy, blessed, perfect and good,
and all that God made and created was very good and blessed,
and so stood as long as man and woman stood in the counsel of God,
and in obedience to his heavenly voice and command, and so was happy, blessed,
good and perfect, and was not burdened, nor did not groan, neither man nor woman,
nor the creation under the bondage of corruption.

For there was nothing that made them groan so long as man and woman stood
in the righteousness and holiness that God Almighty made them in,
and obeyed his voice and command.

Now you may say, '`Then how came in the curse and imperfection,
and the bondage and corruption, that maketh both the creation,
and man and woman thus to groan?`'

I say, as long as man and woman stood in God`'s counsel, and in obedience to his word,
and wisdom, and power, by which all things were made and created,
they stood in the perfect, good and blessed estate, and in the dominion,
in God`'s righteous holy image and likeness,
which did neither corrupt nor burden themselves nor the creation,
but stood blessed and perfect in their good estate, which God, who is the only God,
had placed them in.

And likewise, all the creation stood in its blessed and good estate,
as God Almighty had made it in, who is good, and made all good, perfect and blessed.

And the Lord gave a general liberty to man and woman, and a dominion; and said,
'`Freely ye may eat of the fruit of the trees of the garden,`' and limited them
only from eating of the fruit of the tree of knowledge of good and evil;
saying, '`In the day that ye eat thereof, ye shall surely die.`'

Now the devil, the serpent, that abode not in the truth,
who was an enemy to man`'s prosperity and happiness,
that tree of knowledge of good and evil,
which God Almighty had forbidden man and woman to eat of, and told them,
'`In the day that they did eat thereof,
they should die,`' that did the serpent make his
text of to beguile and deceive man and woman with,
which God had forbidden man and woman to eat of.
And he being more subtle than any beast of the field, he said unto the woman,
by way of question, '`Yea,`' said he, '`hath God said,
ye shall not eat of every tree of the garden?`' So
the subtle serpent comes to tempt afar off,
at the first speaking in general, as to other trees as well as this tree of knowledge:
But the woman answered him wisely at first; if she had kept so,
she had kept her simplicity;
'`We may eat (said she) of the fruit of the trees of the garden;
but the fruit of the tree in the midst of the garden, God hath said, ye shall not eat,
neither shall ye touch it, lest ye die.`'

And then the serpent said unto the woman, '`Ye shall not surely die;
for God doth know (said the serpent) in the day that
you eat thereof your eyes shall be opened,
and ye shall be as gods, knowing good and evil.`'

Now here as Christ said, '`He was a liar and a murderer from the beginning,
who abode not in the truth, because there is no truth in him; and when he speaks a lie,
he speaks of his own,
for he is a liar and the father of it.`' So he was the father of this lie,
which Eve and Adam believed, and so came under the curse and condemnation,
and lost their blessed state; who instead of having their eyes opened, by disobeying God,
the god of truth, the world`'s god out of truth blinded them.

'`And when the woman saw it was good for food, and pleasant to the eyes,
and a tree to be desired to make one wise, she took of the fruit thereof, and did eat,
and gave also to her husband, and he did eat thereof.`'

And so the eyes of them both were opened to what was forbidden,
but came to be blind to the inward; and then they knew they were outwardly naked;
and they sowed fig-leaves together, and made them aprons.

Now their eyes were downward, through their disobedience to the voice and command of God;
for their eyes were far above transgression,
whilst they kept in obedience to God`'s command; they saw then no nakedness,
neither were they terrified or troubled at God`'s appearance, nor had they any shame:
But after they had broken the command of God, they heard the voice of the Lord God,
walking in the garden in the cool of the day;
and Adam and his wife hid themselves from the presence of the Lord God,
amongst the trees of the garden;
which hiding and fear was the fruits of their disobedience to their Maker.

And when the Lord God called unto Adam, and asked him, '`Where he was?`' he said,
'`I heard thy voice in the garden, and I was afraid, because I was naked,
and I hid myself.`'

And the Lord said unto Adam, '`Who told thee, thou wast naked?
Hast thou eaten of the tree which I commanded thee,
that thou shouldst not eat of?`' And Adam said,
'`The woman which thou gayest to be with me, she gave me, and I did eat.`'

And the Lord God said unto the woman,
'`What is this that thou hast done?`' And the woman said, '`The serpent beguiled me,
and I did eat.`'

So here came the first finding fault, the woman found fault with the serpent,
and the man with the woman after transgression.
But whilst they kept in obedience to the voice and command of the Lord,
there was no such finding fault.

And the Lord God said unto the serpent, '`Because thou hast done this,
thou art cursed above all cattle, and above every beast of the field,
and upon thy belly shalt thou go, and dust shalt thou eat all the days of thy life.`'

And then the Lord said, '`I will put enmity betwixt thee and the woman,
and between thy seed and her seed; it shall bruise thy head,
and thou shalt bruise his heel.`'

And unto the woman the Lord said, '`I will greatly multiply thy sorrow,
and thy conception: In sorrow shalt thou bring forth children:
and thy desire shall be unto thy husband, and he shall rule over thee.`'

So, here began the sorrow and anguish;
and here came the man to have the rule over the woman,
(after transgression;) for they were meet-helps before transgression,
and in the image of God.

And unto Adam the Lord said, '`Because thou hast hearkened unto the voice of thy wife,
and eaten of the tree which I commanded thee, saying, Thou shalt not eat of it,
cursed is the ground for thy sake;
and in sorrow shalt thou eat of it all the days of thy life.`'

Here the serpent tempted the woman to eat, and the woman gave unto the man,
and he hearkened unto her voice.

So they both forsook God`'s voice and commandment;
and then that brought them into sorrow, by hearkening to the serpent,
who was out of truth, and disobeying the voice and command of the God of truth.

So this brought the curse upon the ground for man`'s disobedience; and so,
in sorrow he was to eat of that which the curse had come upon, by their transgression,
all the days of his life,
and thorns and thistles the ground shall bring forth to Adam and Eve in the transgression.
So instead of the garden and paradise, they had that ground which was cursed,
for their sakes, and thorns and thistles it was to bring forth to them;
so that they had thorns and thistles, and the cursed ground instead of paradise,
for their disobedience: A sad change!
And the Lord said further unto Adam, '`In the sweat of thy face thou shalt eat thy bread,
until thou return unto the ground out of which thou wast taken; for dust thou art,
and unto dust thou shalt return again.`'

This man and woman brought upon themselves, by hearkening to the serpent`'s voice,
and disobeying the command and voice of the Lord.
Therefore the apostle exhorts the Corinthians,
that they should not be beguiled of their simplicity, as Eve was.

And also saith, '`That the devil like a roaring lion goeth up and down,
seeking whom he may devour, whom resist, steadfast in the faith.`'

For how should Adam and Eve be otherwise,
when they had fallen from the image and likeness of God, the righteousness and holiness,
and the power which God Almighty gave them dominion in, over all that he had made?

So by man and woman`'s transgression, came the ground to be cursed for their sakes,
and to bring forth thorns and thistles, and disobeying God`'s voice and command,
fell from his image, into the earth and dusty part; so in that earthly part,
he was with the sweat of his brows to get his bread, till he returned to dust again.

And to Adam, and to his wife, the Lord made coats of skins, and clothed them.
So this was the Lord`'s clothing of Adam and Eve, after the transgression of his command;
and their own clothing, that they clothed themselves with,
after they had disobeyed the Lord, and transgressed his command, were fig-leaves,
which they had stitched together.
And are not all the professors, and all people in the world, in the transgression,
sewing and stitching together something to cover their nakedness with,
like their father Adam and mother Eve, who are not covered with the spirit of God?
So all their stitched garments will not keep them from the woe and judgments of God.

And are not all mankind by transgression, come under the covering of beast`'s skins,
and covering themselves with fig-leaves, in their shame,
which they had none before transgression?
So after they had transgressed, they put fig-leaves upon them,
which the natural sun will scorch and dry;
and therefore the Lord covered man and woman with beast`'s skins.

And since man and woman in transgressions are grown so far in the lust of the flesh,
the lust of the eye and the pride of life,
that they cannot tell what to invent to put on,
since they lost that covering which God Almighty, who made them, covered them withal.

So the Lord drove Adam and Eve out of the garden, and sent them forth to till the ground,
from whence they were taken;
so that there was no place for them that had disobeyed
the voice and transgressed the command of God,
to remain in the garden and paradise of God.

And God placed cherubims and a flaming sword, which turns every way,
at the east end of the garden, to keep the way of the tree of life;
so that man and woman cannot come in again to the garden of God and tree of life,
but by those cherubims and through this flaming sword.

And now, here all mankind may see what brought the curse, and the misery,
and the sorrows upon them,
and what made the ground to bring forth the thorns and the thistles,
and what was the cause of Adam`'s misery and toiling, that man is to eat his bread in.
All this came through their disobedience to the God of truth`'s voice and command,
their maker and creator; and by hearkening to the subtle serpent, and obeying his voice,
who was out of truth, in whom is no truth,
who is the destroyer and common enemy of man`'s happiness.

So the subtle serpent came, saying '`Yea,`' said he, '`hath God said,
ye shall not eat of every tree in the garden?`'

So he doth not down-right fall upon the tree which God had forbidden,
but queries in the general.

And when the woman told him they might eat of the fruit of the trees of the garden,
but they were not to eat of the tree of knowledge of good and evil,
in the midst of the garden, nor touch it, lest they died.
For God said unto them, '`In the day that thou eatest thereof, thou shalt surely die.`'

This was God`'s command and testimony to them, '`In the day that thou dost eat,
thou shalt surely die;`' and therefore he said,
'`Thou shalt not eat thereof:`' And this was God Almighty`'s teaching,
who taught man the way, how he might live in the paradise of God, and not die.

And the serpent`'s false doctrine and teaching was,
'`Ye shall not surely die if ye eat thereof, but your eyes shall be opened,
and ye shall be as gods,`' etc.

So here was the first false doctrine taught by the world`'s god, who is out of truth,
who was a liar from the beginning, and a murderer,
who taught that doctrine contrary to the Lord God, which by feeding on it,
and obeying his voice, brought man and woman into the death and fall,
from the image of God, and to himself, who abode not in the truth.

And Eve saw that the tree was good for food; so her eye went out.
Now, can that be good for food, which by eating of it, brought death,
as God had forewarned them?
But the serpent said, '`Ye shall not surely die, but be as gods.`'

And the woman saw the fruit was pleasant to the eyes, and to be desired,
and would make one wise.
So here her ear went out to hearken to that lying doctrine.
But how could that be pleasant to the eye, or be desirable, or make wise,
when by eating of it they should surely die?
So thinking to be made wise, they became fools,
which brought the rod upon the back of them,
which also comes upon all their posterity in the fall.

But here you may see, the ear went from the Lord`'s voice and command,
after the serpent`'s doctrine; and the eye went out from the Lord,
and after that the mouth went also; and then death surely followed, and the woe,
misery and curse upon the ground, and the thorns and this, ties sprung up.
And so, out of the garden and paradise of God, man and woman was turned and driven:
And this they got by disobeying the command of the God of truth, and hearkening unto,
and obeying the voice of, the serpent, in whom is no truth.

And so, after disobedience and transgression of the command and voice of God,
then came nakedness to be seen, when they were fallen from holiness and righteousness,
and the image and likeness of God, which God had made them in, and clothed them withal;
and then came guilt and shame, and a hiding themselves among the trees,
and cover themselves with fig leaves, from the presence of the Lord;
but he who is present always and everywhere,
who sees man and woman`'s going out into the transgression,
and convicts them of their disobedience to his command and word,
and of their transgression in eating of that which he forbade them;
and then he passed sentence on the woman and the man,
and turned them out of the garden and paradise, into the earth, as was said before;
and passed sentence upon the serpent, and cursed him above all cattle,
and all the beasts of the field, and said, '`Upon his belly he should go,
and dust should be his meat all the days of his life,`'

So, here is no promise made unto the serpent, all the days of his life,
who taught the false doctrine and was the first false teacher, liar and murderer;
but '`dust should be his meat,
and upon his belly should he go;`' and was cursed above all cattle,
and every beast of the field.

But the promise of God was to mankind,
"`That the seed of the woman should bruise the serpent`'s head.`'

So here was the first promise of Christ, which all the faithful hoped for,
and believed in, for their resurrection out of that fallen estate.

Now, whilst Adam and Eve were in the paradise of God, and kept God`'s commandment,
and obeyed his voice, they were help-mates in the image of God, both male and female;
and God gave them dominion over all that he had made, and blessed them, and said,
Be ye fruitful, and multiply, and replenish the earth, and subdue it;
and have dominion over the fish of the sea, and the fowls of the air,
and over the cattle, and over all the earth,
and over every living thing that creepeth upon the earth,
and over every living thing that moveth upon the earth;
and their work was to dress the garden, and to keep it, and to subdue the earth,
and keep their dominion in his power and image, as he made them.

So here you may see the work which God commanded man and woman to do,
whilst they were in his image; they were not to be idle,
neither were they to do this in the sweat of their brows,
nor to eat their bread in the sweat of their brows, whilst they kept the command of God,
and obeyed his voice; neither did God set the man over the woman,
whilst they kept in the image of God, and obeyed his voice, and kept his command,
but were meet-helps; for both had power, male and female,
over all the creatures which God had made, as long as they kept in the image of God,
and obeyed his voice and command; but after they disobeyed God`'s voice and command,
and hearkened unto the serpent`'s, and so were subjected under hope of being as gods,
and of being wiser than God had made them; and thought that fruit was good for food,
and to make wise, which brought them surely to die that day they did eat thereof.
So Adam and Eve came to be dead to God; and instead of being wiser, came to be fools,
and got the cursed ground, and thorns and thistles, instead of paradise.

But ye may say, that Adam and Eve were alive after this,
else how could they have children afterwards?

Yea, they were alive outwardly, but they died from the image and likeness of God,
and righteousness and holiness, which God Almighty made them in, and from that power,
in which the Lord gave them dominion over all the works of his hands.

So the Lord God said, '`Thou shalt not eat of the tree of knowledge of good and evil;
for in the day that thou eatest thereof, thou shalt surely die.`'

But the serpent said, '`If ye eat thereof ye shall not surely die.`' And they did eat,
and disobeyed the Lord`'s voice and command, and did surely die;
and so death passed upon all men, and all died in Adam.

So God`'s teaching is true, who is the God of truth,
and the serpent`'s teaching was a lie, who was a liar from the beginning, and a murderer;
and Adam and Eve`'s becoming as gods, they were dead to God, according to God`'s word;
but the serpent he became their god, and Adam and Eve his slaves,
and their disobedient posterity, and were plunged and baptized into the serpent`'s image,
likeness, power and wisdom, by which man knows not God.

This was the fruit of their transgression, and disobedience to God`'s command;
and this was the wisdom they attained unto, and their disobedient sons and daughters,
by forsaking God`'s teaching, and following the serpent`'s.

Therefore, as Christ said, '`Go, teach all nations,
and baptize them in the name of the Father, Son,
and Holy Ghost.`' Seeing all was dead in Adam, and so plunged into death,
by disobeying the Lord, and hearkening unto the serpent.

So all must be baptized with the baptism of Christ, with fire and the Holy Ghost;
and all their disobedience, transgression, sin and corruption,
and their chaff must be plunged down and burnt up by the baptism of Christ,
before they can come into the paradise of God, and have right to eat of the tree of life.

So the serpent is called the world`'s god, the world that lies in wickedness;
and he hath made it like a wilderness with his rough plants, briars and thorns,
that he hath planted in man and woman`'s transgressing heart, which as Christ saith,
'`Must all be rooted up, every plant that the heavenly father hath not planted.`'

Now the serpent who said, '`If they did eat, they should become as gods;
but by this he brought them into death, by eating of that by which they died,
and he became God.

And so, this god of the world had blinded their eyes, and makes people heathen like,
so as they do not know God;
so that in process of time they were led so far into transgression,
that they made gods of stocks, and stones, and silver, and gold, and other metals.

So that Adam and Eve`'s sons and daughters were afar off from being god`'s themselves,
when they made gods of stocks and stones, and other creatures,
and fell a worshipping of them, and worshipped the host of heaven:
This was far off from being gods themselves,
who were so far degenerated from the image of the living God, as the lying teacher,
the serpent, that was out of truth, had told them,
and made them believe they should be as gods; but here they became slaves to him,
and to that which the world`'s god wrought in them, in whom there is no truth.

For you may see, the very Jews, who were of the stock of Abraham, Isaac, and Jacob,
when they forsook the Lord God and his ordinances, and disobeyed his voice,
how that after they felt his arm and power, and saw his great miracles and wonders,
they began to make gods of metals, and wood, and stone: They would be wiser,
like Adam and Eve, than God, who had made and taught them.
So here their ears and eyes also went out from the spirit of God,
which he had poured upon the whole house of Israel,
by which they might have kept his laws, ordinances and commands, like Adam and Eve;
and then their mouths went to swallow down that which the world`'s god wrought in them;
and so drank down iniquity, as the ox drinketh up water;
and then the curse came upon them, and judgment, woe and misery,
and they were like thorns and thistles one unto another,
which sprung out of the cursed ground of transgression,
of which they had enough both inwardly and outwardly;
and so lost the blessing both inwardly and outwardly,
that the heavens were as brass to them, and the earth as iron, all springs being stopped,
both above and below.

And therefore came God`'s judgment upon the Jews,
until they were driven out of the promised land of Canaan,
as Adam and Eve were driven out of paradise, for disobeying God`'s voice and command.

And now you may see what hath made man and woman blind,
even their forsaking and disobeying the living God of truth, that made them,
and by hearkening unto, and following the world`'s god, in whom there is no truth;
it is he that hath blinded man and woman,
and filled them with his earthly and sensual wisdom, by which man doth not know God.

And, therefore, Christ the promised seed, which bruiseth the head of the serpent,
which all the prophets and holy men of God had faith in:
It is he that opens the eyes of the blind;
so the Lord God of truth he made all good and blessed, and made man and woman to see;
but the world`'s god hath blinded them by disobeying the God of truth,
and hearkening to the serpent, the world`'s god, in whom there is no truth,
and hath brought them into the curse; and by disobeying God,
they lost and fell from his image, and came into the dust and death.
And by disobeying the good God, who made all good, and obeying the serpent,
the world`'s god, he makes all bad.

For the Lord God that made man and woman perfect and upright in his image,
in righteousness and holiness, and so to be like him their Father.
And man and woman by disobeying the Lord God of truth, his command and voice,
and obeying the serpent, the world`'s god, that abode not in the truth,
and in whom there is no truth that makes them so imperfect, unholy, unrighteous,
and ungodlike; not like God the father of truth, (the creator of all,
who takes care and feeds and nourishes all) but like unto the serpent,
to bear his image and do his works.
So the devil is their father, as Christ said to the Jews.
So they have the very image of their father, who is out of truth,
and was a liar and a murderer from the beginning, that obey him.

For whilst Adam and Eve obeyed the voice and command of the Lord God,
they abode in his image, and were in the likeness of God their creator.

But when they disobeyed the voice of the pure, true and living God,
and obeyed the serpent, the world`'s god, then they entered into his image, as the Jews,
which forsook the law of God, and the voice and command, and the laws of God.

Christ told them, '`They were of their father the devil, and his lusts they would do,
though they profess Moses and the prophets, and that they were of Abraham.`'

And so may many that are called Christians now, profess themselves christians,
and make a profession of Christ and the apostle`'s words;
but if they were of Christ and the apostles,
they would do the works of Christ and the apostles.
But let the christians and others examine themselves,
if they be not erred from that spirit,
which the living God of truth doth pour upon all flesh,
by which they should hear the voice of God and Christ, and obey his command,
and not have hearkened unto the foul, unclean, murdering spirit of the world`'s god,
in whom there is no truth, and lent their ears and eyes after his teaching,
and feed upon that which he works in them; and instead of being saviours upon Mount Zion,
they are destroyers of one another, and enemies unto one another,
instead of loving enemies, or one another.
And so, are not the fruits of this spirit manifest to be from this foul, unclean spirit,
the world`'s god, in whom there is no truth, and not from the living God of truth?

So it is clear, it is not the profession of the Jews, which profess the Old Testament,
nor the christians that profess the New, with that foul, unclean, murdering spirit;
but it is the fruits and the works that are wrought
by the spirit of Christ and the apostles,
the fruits and works of the spirit that God accepts, that make Jews in spirit,
and true christians, like Christ.

For all the children of Adam may make a profession
of their father and mother being in paradise,
whilst that they are out of it, serving the world`'s god, that makes them blind,
and fills them with sin and unrighteousness, and so are unlike the living God of truth,
but are like the world`'s god, that is out of truth.
And this the world`'s god causes them all to plead for the body of sin and death,
and imperfection,
which he hath wrought in them (and not the living pure God) as long as they live,
till they come to the grave.

But the living God of truth did not make Adam and Eve with a body of sin and death,
and blind, nor unrighteous, ungodly and unholy,
not like as the world`'s god hath made them;
but the living God of truth made man to see and hear him, and in his image and likeness,
holy, righteous, and perfect, without sin or a body of death;
but they disobeying the living God, and obeying the serpent, the world`'s god,
came to be blind, imperfect, unrighteous, and unholy, like the world`'s god,
and so came to have a body of death and sin; and so fell from life into death,
and so worshipped the dragon and the beast, and gods of their own making;
for the world`'s god hath several ways to keep his subjects in,
and will let them profess what they will, and have what outside shows they will;
and this world`'s god hath his ministers, his prophets, his pastors, his teachers,
and his apostles, all false, who got amongst the Jews,
and got amongst the christians before the apostles`' decease,
and he will let them make as many faiths and creeds as they will, to profess,
so long as they come not into the possession of life.

But the faith that is the gift of God, which Christ is the author of,
that is the victory over the world`'s god, which purifies the heart,
and brings them to have access to God; this faith that gives the victory,
the world`'s god and his messengers and ministers cannot endure to hear tell of.

Nor believe in the light, which is the life in him,
(the word) by whom all things were made, by which they come to be born of God,
and children of light, and by it overcome the world.
This the world`'s god, and his ministers, prophets, and apostles,
cannot endure to have spoken of; but call it a natural light,
and a made and created light, and insufficient: though Christ saith,
'`believe in the light;`' but the world`'s god and his ministers tell people,
it is not saving: but the world`'s god is not changed from his lying;
'`for when he speaks, he speaks of himself, and there is no truth in him,`' saith Christ.

For you may see, he told Eve, '`they should not die, if they did eat,
but should be as gods:`' but the living God of truth told them,
in the day that they did eat, they should die.`"

So the world`'s god is the same now, who tells you, the light within,
(which is the light of Christ,) which you are to believe in, is not saving.

But Christ, who destroys the world`'s god, the liar, he saith,
'`believe in the light:`' and saith the Lord,
'`he that believeth in the Son hath everlasting life:`' and the God of truth saith,
'`be ye holy, for I am holy: be ye perfect,
as your heavenly Father is perfect,`' saith Christ;
and this was to be whilst men and women were upon the earth.

For God made man and woman holy and perfect by Christ Jesus,
who comes to bruise the serpent`'s head, that made man and woman unholy and imperfect,
and to destroy the devil and his works, and was made sin and a curse,
to take away sin and the curse, that through him,
they who believe might be made the righteousness of God in him.

But the world`'s god, and his messengers and ministers say, '`none shall be holy,
nor be perfect on this side the grave; none shall be so baptized,
as to have all their chaff and corruptions burnt up in the floor of their hearts,
whilst they are on this side the grave, but they must have sin in them,
to humble them.`' But sin lifts up, and doth not humble any.

And so here again, the world`'s god and his messengers and teachers speak a lie;
for there is no truth in him, who was a liar from the beginning.

And the apostle said, '`they were circumcised with the spirit,
by which the body of the sins of the flesh was put off`' But the world`'s god,
and his apostles, and ministers, and messengers say and preach,
that all must carry this body of sin and death to the grave:
this is the doctrine of the world`'s god and his teachers, in whom there is no truth,
who hath brought this body of sin and death upon man,
through man`'s hearkening and obeying of him,
and disobeying the voice and command of God.

For without holiness none can see the Lord.

So the world`'s god, in him there is no truth, who is a defiler, corrupter, murderer,
and a liar, and make men liars and murderers; the ungodly one,
and so makes unlike God them that obey him; the unrighteous and evil one,
and so makes those unrighteous and evil like himself that obey him;
and the unmerciful and wicked one,
and so makes all his unmerciful and wicked like himself, that obey him.
And so the world`'s god is an enemy, an adversary, a destroyer,
and so makes men enemies and adversaries one unto another, and destroyers one of another,
by obeying and hearkening unto him.

And the world`'s god leads people into adultery, inwardly and outwardly,
and into fornication, theft, and all manner of deceit; for he is a lying unclean spirit,
in whom there is no truth; and so leads them into the lust of the eye, lust of the flesh,
and into the pride of life, and into the world`'s vanities and evil ways;
and all this is of the devil, the destroyer, and not of the living God, the God of truth,
who created all for his glory, and takes care for all.

For God, the creator of all, is the living, righteous, and eternal everlasting God:
but the world`'s god had a beginning, and must have an end in the lake of fire,
and all his followers, if they turn not from him, and obey the living God.

So the living eternal God is the creator and preserver, a holy, pure, just,
and righteous God, everlasting, immortal, and eternal, who lives forever,
who is without time, and over time, and hath all times and seasons in his hand,
a perfect and pure God, holy and glorious, full of riches eternal.

But the world`'s god, that is out of the truth, in whom there is no truth,
is a destroyer, and brings into poverty, death and darkness,
and is the prince of darkness, and maketh all dark like himself, that obeys him,
and so come under the power of death.

But the living, eternal, omnipotent God, is the God of truth, who is light,
and in him there is no darkness at all, a holy eternal spirit,
that fills heaven and earth; and heaven is his throne, and the earth is his footstool:
He is to be worshipped and served in his holy spirit and truth,
that he pours out upon all flesh, which truth, the world`'s god, (the devil,) is out of,
in whom there is no truth.

So they that worship the holy and everlasting eternal
God in God`'s spirit and in his truth,
then they are in that truth which is a top of the head of the world`'s god,
which truth he is out of, and there is no truth in him.

And the apostle saith, '`The prince of the power of the air,
the spirit that now worketh and ruleth in the hearts
of the children of disobedience.`' Eph. 2:2.

And Christ calls him, '`The prince of this world,`'
John 12:31. and 14:30. and 16:11.

So the prince of this world is judged,
and now shall the prince of this world be cast out;
'`for the prince of this world cometh, and hath nothing in me,`' saith Christ.

Now here all may see the prince of this world is judged by Christ, and cast out;
he finds no disobedience in Christ, as he did in Adam and Eve.

So all may see how this prince of the world, that lies in wickedness,
how he got into Adam and Eve by their disobedience;
and he got into the Jews by disobedience to God`'s command and spirit which he gave them;
for Christ said, '`They were of their father,
the devil:`' and he hath gotten into the christians since by their
disobedience to the command and voice of God and Christ Jesus,
and the spirit which he hath poured forth upon all flesh; but Christ judges him,
and casts him out; and though he came to Christ to tempt him,
yet he finds nothing in him.

Now this prince of death and darkness, which compasseth the old earth of disobedience,
and is a ruler and worker in the hearts of the children of disobedience,
and brings his obedient people to walk and to have conversation
according to the prince of the power of the air,
that works in them, and rules in them, to fulfill the lusts of the flesh,
and the desires of the same, in which nature they are children of wrath;
and he works in them,
and fills them with all manner of evil and blasphemy against God and Christ,
and them that dwell in him, and have their habitation in heaven.

So all may see, that believe in the light of Christ,
the beginning of this prince`'s kingdom, and the height of his authority,
which was begun in and by the disobedience of Adam and Eve to God`'s command and voice;
and he still rules in the hearts of all the disobedient to God and Christ,
and to his spirit, grace and truth; and through men`'s disobedience thereunto,
this god of the world`'s kingdom is upheld and enlarged.

I say, to such as disobey the God of truth`'s good spirit, and rebel against it,
and vex and quench it, into the hearts of such disobedient ones, the god of the world,
in whom there is no truth, gets.

For the spirit of God,
(if man did obey it and hearken unto it,) it would be found
stronger than that foul spirit that is out of truth,
that rules in the disobedient ones.

And likewise they that do err from that faith that is the gift of God,
and that Christ Jesus is the author and finisher of,
and do hate the light of Christ Jesus, which Christ commands them to believe in,
and walk despitefully against the Spirit of Grace,
and despise the word of Grace in their hearts, and resist the motions of the Holy Ghost,
and disobey the gospel, the power of God, and will not receive it; such disobedient ones,
the god of the world, and prince of the air and of darkness,
is the worker and ruler in their hearts,
and their conversation is according to the prince of the power of the air,
the god of this world; so that they are conformable to him,
and bear his image and likeness in them, and are not conformable to God nor Christ,
and bear not their image; so that they show forth in their words, ways,
lives and conversations whose image they bear, and what god and prince they plead for,
and worship and serve, to wit: The god of this world,
in whom there is no truth:`' For his sin, evil, ungodliness and unrighteousness,
imperfection and body of sin and death to the grave, they plead for,
and say they must carry about them.
And this god and prince of the world will allow them to
profess all the scriptures of the Old and New Testament,
so that they will plead for his works, that he, the world`'s god, that is out of truth,
hath wrought in them.

Now here all are left without excuse, that come under the judgment of God and his son,
who judges the world in righteousness; for Adam had something to disobey,
and so had the Jews and the Christians, and all mankind For the light,
which Christ doth enlighten every one that cometh into the world withal,
which is the life in him, by whom all things were made and created, which,
if they believe in it, they are saved; and if not, they are by it condemned.

So this light is stronger than the prince of darkness, the world`'s god,
that is out of truth, if people will believe in it.

Also, the grace and truth that comes by Jesus Christ,
it is sufficient to teach and bring salvation.
Paul had the experience of it; and God said,
'`It should be sufficient for him in all his temptations and troubles.`'

I say, this grace and truth is too strong for the prince of darkness, the world`'s god,
who abode not in the truth, and there is no truth in him.
And it is sufficient to teach people, and bring their salvation:
And it is the world`'s god and his followers who say to the contrary.

For the true and living God and his holy apostle say, '`It is sufficient to teach them,
and bring their salvation.`'

Likewise the word of faith, which Jesus Christ is the author and finisher of,
is sufficient to save, as Christ often said, '`Thy faith hath saved thee,
and made thee whole.`' And this faith is sufficient
to give victory over the prince of the air,
the world`'s god; and that which gives victory over him, and doth resist and subdue him,
that shield is stronger than he and all his followers.

And also, the Holy Ghost, or Holy Spirit, and the unction within,
it is sufficient to teach and lead into all truth, which comes from the Holy One,
and proceeds from the Father and the Son; I say, this is stronger than the world`'s god,
and prince of death and darkness, in whom there is no truth, who is an unclean spirit.
This holy, pure, clean spirit and unction from the Holy One,
is too hard and too strong for that unclean spirit,
that leads all the disobedient out of truth;
but this Holy Spirit leads the obedient into all truth.

And as to the light, spirit and power,
people may resist the motions of it in loving the prince of darkness,
(the world`'s god,) more than the light, and the eternal, immortal, living god of truth,
and Christ the prince of life; but the light and spirit is stronger than they,
and the world`'s god, whom they serve.

The light itself will be their condemnation, and by the pure,
Holy Spirit and power they will be judged; for Christ does judge the world,
according to the gospel, the power of God; and who believe it and receive it,
this everlasting gospel, the power of God, is over the prince of the world,
and of death and darkness, the world`'s god, in whom there is no truth;
and is stronger than he, whose dark unclean spirit and power had a beginning,
and must have had an end, in the lake of fire; but the power of God, the gospel,
is everlasting and without end, though it hath a beginning in men, to the saving of them;
and therefore it is called '`The Gospel of Salvation:`' But in itself, the gospel,
the power of God, is everlasting; and the light, which is the life in Christ,
in itself is everlasting; and they that believe in it, come to have everlasting life.

And the word of God, in itself is everlasting, and is a hammer and a sword,
and a fire upon the head of the world`'s god,
and them that conform to him and follow him.

And the truth and the spirit of God in themselves are everlasting;
though men may quench the motions of it in their hearts, that love the world`'s god,
the prince of the air, more than Christ Jesus, the prince of life, and the eternal,
immortal, everlasting God of truth.

And this world`'s god and prince of the air, in whom there is no truth,
as Christ and the God of truth hath declared;
and if there be no truth in this world`'s god, the prince of the air,
then what is in him?
Nothing but chaff, corruptions, sin, deceit and lies, falsehood, envy, malice, hatred,
theft, murder, death, darkness, bondage, ungodliness, unrighteousness and unholiness,
from this foul, unclean spirit, by which he burdens and imbondages the creation,
and makes it to groan, and all that obey him, and disobey God and Christ.

And whosoever obey that unclean spirit, or touch it, or join to it,
in whom there is no truth, are defiled, and brought into bondage by it,
and under a weighty yoke and heavy burden.
And therefore Christ saith, '`Come unto me all ye that are weary and heavy laden,
and I will give rest unto your souls; for my yoke is easy and my burden light.

And this prince of the air and god of the world, who is out of truth;
he hath his dark principalities and powers, and rulers of darkness,
and spiritual wickedness in his high places in the old earth;
and he fills them full of air in words, and notions and imaginations,
and puffs them up with lies and deceit in his dark power and principalities,
and spiritual wickedness in the high places in the earth,
where dwells his unrighteousness,
with which he maintains and upholds his kingdom of darkness and death.

So with this his dark power and principalities he wrestles with flesh and blood:
So this power of death, the world`'s god, he hath congregations of the dead,
and he hath his dead faith, for the disobedient,
(which he rules,) to make a profession of.

And he hath his vain and destroying religion for them to plead for.

And he hath his worship, which is out of God`'s holy, pure spirit and truth,
for his disobedient ones to serve and worship him in, in whom there is no truth:
'`For the prince of the air, the world`'s god, is an unclean spirit, out of truth,
and hath no truth in him.`'

And he hath his dead ways to lead them in that disobey God`'s grace, truth,
light and spirit.

And hath a faith to his followers, but it is dead, and gives no victory.
And a belief, but no overcoming on this side the grave, the world`'s god,
that is out of truth: Nay, rather their belief is,
'`That they have a body of sin and death,
which they must carry to the grave;`' which faith and belief, and body of sin,
they have from the world`'s god, and not from the living God of truth;
and it is not like the world`'s god, in whom there is no truth,
should work any other faith or belief in them,
or any thing else but this body of death and sin,
when they disobey the living God of truth, which gives the living faith,
that is the victory.

And the world`'s god, and the prince of the air, will suffer his obedient ones,
in whom he works and rules, to talk of baptism and circumcision;
but they must not believe that their body of death, and sins of the flesh,
must be put off,
which the god of the world hath wrought in them since
they disobeyed the living God of truth,
whilst they are on this side the grave; but those works which he hath wrought in them,
they must carry to the grave with them; and that the floor of their hearts,
minds and souls, shall not be thoroughly purged whilst they be upon the earth,
but that they must he purged in a purgatory, when they are dead;
and whilst that they are upon the earth, they cannot do otherwise than sin, that is,
to do the work of the god of the world, that is out of truth, and not,
the works of the living holy God of truth.

And Christ, who saith, '`Believe in the light,`' and serve him in his living, holy,
pure spirit and truth, which the world`'s god, that unclean spirit, is out of,
and there is no truth in him.
Yea, this world`'s god will suffer his messengers, ministers and professors,
to cry against sin, as much as they will, and preach up sanctification and redemption,
but they must not be made free from sin, nor cleansed, nor sanctified, nor redeemed,
or to be made clean from this world`'s god, and the works which he,
the prince of the air, hath wrought in them, whilst they be upon the earth.

And they must not have any assurance of their salvation and redemption from sin,
or election here: This is the prince of the air`'s doctrine, who is out of truth,
that he hath taught his ministers, messengers and apostles to preach and teach,
in his dark school of disobedience, and that there is no victory over this prince,
the world`'s god, and his works, whilst they are upon the earth,
nor overcoming of him that is out of truth.

And now, as he hath gotten Adam and Eve into disobedience by his subtlety,
so by his subtlety he would keep in disobedience, and death and darkness,
all his children and servants.

And therefore,
if any witness victory or overcoming on this side the grave of the world`'s god,
and that which he hath wrought in them,
and to have the same power and spirit the prophets and apostles had,
this is called presumption by the world`'s god, and the disobedient that he rules in,
and called by them '`A justifying of self.`'

And to have an assurance of their election, and salvation, and life eternal here,
as-Christ the truth saith, '`They have that receive him and believe in him.`'

This shakes the kingdom of the world`'s god, in whom there is no truth,
and makes his followers, that disobey God`'s spirit and command, to rage against it.

Now the god of the world is called '`The prince of the air,
who works and rules in the hearts of the children of disobedience`';`' and all
the disobedient ones walk according to the course of this prince of the air,
and wickedness, who is out of truth; and he works in them by his unclean spirit,
and fills them with airy notions and conceits, which he hath in store for them;
and with wickedness, death, darkness, corruption, vanity, folly,
looseness and all unrighteousness, debate and deceit:
By this his unclean ravenous spirit, he fills them with airy notions, words and lives,
and with drunkenness, whoredoms, and all manner of uncleanness and wickedness,
that proceed from this unclean spirit, that is out of truth,
and to spend their time out of God`'s fear, in wantonness, pleasures, sports, plays,
vanities, voluptuousness in meats, drinks and apparel, in idleness,
and all manner of looseness in conversation, with all covetousness and greediness,
devouring and destroying the creatures, and the creation upon their lusts,
with all greediness and oppression, injustice, unrighteousness, unmercifulness, unholy,
intemperate, impatient, cruel and tyrannical,
and with all manner of evil the god of the world works in them,
that disobey the living God of truth, and Christ his son:
The fruits of this evil spirit are easily seen,
and known by them that obey the Lord in his spirit, light, grace and truth.

And he is called the prince of the air,
for his kingdom and empire had a beginning in the disobedient;
for by disobedience he got into Adam and Eve,
in the disobedient he rules and works with his dark power and spirit,
and sets up his principalities, who is out of truth, and there is no truth in him.

Now to know the beginning of his empire, its height, length, breadth and end:

First, he got into Adam and Eve by disobedience, and so into his sons and daughters,
both Jews and christians, and others;
and so rules in the hearts of the children of disobedience;
his rule and his work goes no further, for none are conformable to him,
but who are disobedient; and none walk after his unclean spirit,
but who disobey God`'s pure spirit, grace, light and truth.

So, the compass, length and breadth of his empire and kingdom,
and his work reacheth no further than to and over these that disobey the grace, light,
spirit and truth, voice and command of the living God, and his son Christ Jesus.

Now the height of this god of the world, and prince of the air`'s empire and kingdom,
with all his principalities, powers, rulers of darkness,
spiritual wickedness in his high places, do not reach so high as the truth,
for he is out of it, for there is no truth in him,
and truth is over him and his followers; neither doth his kingdom or,
principality reach so high as righteousness,
nor so high as the light and the power of God, nor life; for the prince of the world,
the world`'s god, is death and darkness, unrighteousness and uncleanness,
and is an unholy, foul, dark, lying spirit, and is comprehended with the truth,
and with the light and life, and his unclean kingdom of death and darkness.
I say, he and his kingdom, empire and princedom, with all his dark powers,
principalities and rulers of darkness in the disobedient, his beginning is seen,
his compass is seen, his height is seen, his end is seen in the lake and fire,
together with all the disobedient that follow and serve him.

Now Christ is a prince of life, and a prince of peace, who is called light and life,
and the wisdom of God, and righteousness and the Holy One, etc.

He bruiseth the head of this world`'s god and prince of the air, that is out of truth,
and breaketh his power to pieces, and he opens people`'s eyes and ears,
that this world`'s god hath stopped and blinded, and cleanses and sanctifies,
purifies and washes such as this world`'s god hath defiled,
and redeems such as believe in him, that this world`'s god hath taken captive,
and leads him into captivity: And he gave gifts unto men, who ascended up on high,
far above all principalities, powers, thrones, and dominions.

So Christ gave gifts unto men, first unto his twelve, and seventy,
before he was crucified and ascended.

And it is also clear, that Christ gives gifts unto men after he ascended,
for the work of the ministry, and makes some evangelists, some pastors, some teachers,
and some prophets, according to the apostle`'s doctrine.
Ephesus iv.

So with these gifts which they have from Christ, since he was ascended, and before,
they were to bring people to the knowledge of the Son of God,
from whom they had received their gifts,
and who was the author and finisher of their faith;
and then to live by that faith in which they had victory and unity;
and so to a perfect man, the state that Adam and Eve was in before they fell;
and not only so, but to the measure of the stature of the fulness of Christ,
which is to a higher state than Adam was in in his first state,
which is a state shall never fall.

And the world`'s god he hath his ministers, prophets, apostles and hirelings,
to make a trade with the scriptures of the Old and New Testament,
with the natural languages and arts; and this they sell at great rates,
where they can get the greatest parsonages or bishopricks, or get most for it;
and they preach up to people, '`that they must have a body of death and sin to the grave;
and that it is impossible to obtain victory over sin here,`' which burdens the creation,
and causeth it to groan, which sin came into man and woman,
and brought the curse by their disobedience to the voice and command of God.
And if people will not give them earthly things, and put into their mouths,
and fill their bellies, which is one of their gods, set up by the world`'s god,
who is out of truth, then they will cast such in prisons.
And if the obedient and believers in Christ tell them,
that they are no ministers of Christ, but made at natural schools,
and by natural arts and languages;
and are ministers only of the letter of the Old and New Testament,
with their imaginations of it, and interpretations,
to make it suit the dark spirit that is out of truth, and to keep people in sin,
and in imperfection, which the God of truth made them not in:
and that they never heard God`'s voice, nor Christ,
as the '`prophets and apostles did;`' for if they did, and had freely received,
they would freely give, as the ministers of Christ did: Oh, cry the disobedient,
who walk according to the prince of the air, and obey the world`'s god,
that is out of truth, '`That it is presumption for any to say,
they have the same spirit and power the prophets and apostles had,
and to hear God`'s voice as they did: There is no such thing to be looked for now-a-days,
or in their days;`' which are the days of darkness, and not of light.

And the disobedient children that fashion themselves according to the God of the world,
and not according to Christ, who is not of the world, the world that lies in wickedness,
was brought so into this wickedness by the world`'s god,
and by obeying him that is out of truth, and disobeying the living God of truth:
And this world hated and hates Christ, and all his followers and disciples to this day,
and hated the prophets, and hates the appearance of Christ Jesus in his people now;
and it is no marvel, because they testified, and testify against the world,
that their works be evil.
And how should it be otherwise, when the god thereof is evil, who abode not in the truth,
and there is no truth in him?

So, here are two workers spoken of; the prince of the power of the air, the world`'s god,
who worketh by his unclean spirit in the hearts of
the children that disobey God and his holy pure spirit,
Eph. 2. And he worketh all manner of uncleanness, sin, evil, wickedness, unholiness,
unrighteousness and ungodliness in the hearts of
all such that do disobey the living God of truth,
and his son Christ Jesus, in his grace, truth, spirit and gospel, that he gives them.
So that the world`'s god fills them with unrighteousness and uncleanness, with his foul,
unclean spirit, that is out of truth; for there is no truth in him,
and he can fill them with nothing else.

But the living, eternal, and immortal God of truth, worketh otherwise;
as the apostle saith, it is God that worketh in you,
both to will and to do of his good pleasure.`' Phil. 2:12.

Now God works in his obedient children, by his pure, holy spirit, power, grace,
and truth, both to will and to do that which is good,
according to God`'s good pleasure (to wit) that which pleaseth the just, pure, righteous,
holy God.

So he works righteousness, holiness, justice, truth, virtue,
purity and godliness in the hearts of men and women that obey his good spirit,
by which spirit patience, tenderness, meekness, humility, soberness, temperance, mercy,
and kindness, etc. is wrought in the hearts of his people, by God`'s good spirit,
which brings '`to love God above all, and their neighbours as themselves.`'

And the God of truth, who works in his obedient people`'s hearts,
to will and to do that which is according to his good pleasure`';
he works out that which is contrary to his will,
and is not according to his good pleasure.

For he worketh all things after the counsel of his own will,
in his people and obedient children: so his people are his workmanship,
'`created in Christ Jesus unto good works, which God hath before ordained,
that his obedient children and people shall walk in them.`'
Eph. 110. So not to walk out of those good works,
which God hath ordained, which are not of mans own ordaining.

And such do serve the living God of truth in the newness of the spirit, and of life.

But such as do disobey the spirit of the living God of truth,
they may profess they know God, because they can read the letter of the prophets,
Christ and the apostles, which have declared of him, but in their works they deny God,
being abominable, and disobedient, and unto every good work are reprobate.

And let all professors, teachers, and others, examine themselves,
whether they are not such?
and then, who is their God, but the God of the world, the prince of the air,
in whom there is no truth, when they are reprobate to every good work, and disobedient,
and in their works deny the living God of truth, and yet profess him with their tongues?
Such disobedient ones cannot serve the living God;
but the God of the world and the prince of the air, who is out of truth,
and in whom there is no truth, who must be destroyed, and his kingdom.

For, as I said before, Christ bruiseth his head, and crusheth his power,
who through death destroys death, and the devil, the power of it.

And Christ sets up his kingdom, which is everlasting, and shall never have an end,
and which stands in righteousness, power and joy in the Holy Ghost:
so his kingdom is a holy, righteous kingdom, in his power, righteousness,
and Holy Spirit, and is an everlasting kingdom, and is over all kingdoms and dominions;
and will never have an end; a kingdom that is established forever,
that cannot be shaken.

For no unclean, imperfect, unholy thing can come into this kingdom,
nor any disobedient or defiled hath any part in it: so it is an incorruptible kingdom;
for no corruptible, unclean thing can come into it; but the saints,
the sanctified ones take this kingdom,
and have an inheritance in this everlasting kingdom.

And, therefore, why should any disobey God`'s spirit, light, and grace,
which he hath given them to profit withal, and to instruct them,
and bring their salvation; and not serve the Creator, but the devil, who is a destroyer,
and Satan, that is, an adversary, the serpent,
an enemy of man`'s prosperity and happiness, and disobey the living God of truth,
and Christ his son, who died for you, and to be servants to the world`'s god and prince,
who is out of truth, and there is no truth in him,
whose service is but a slavery and bondage in his unclean ghost,
in which there is no true joy, but misery in the end, which is your reward and portion,
who are subjects of his unrighteous, ungodlike kingdom of death, darkness and corruption,
which is an unholy and unjust kingdom, which he upholds with his foul, unclean spirit,
who goes on his belly, and dust is his meat all the days of his life?
and if their god and prince`'s meat be dust, and he go upon his belly,
then how will you disobedient ones, in whom he rules, go?
and what is your meat but dust?
For do you think you must fare better, or go better than your god and prince,
that is out of truth, and there is no truth in him doth?
Oh, no; therefore obey truth, which the world`'s god and prince is out of;
and the pure Spirit of God, that foul, unclean spirit is out of;
and then you will have heavenly milk and wine, and the honey and honey-comb,
and bread of life from heaven, by which you may live by Christ that gives it you,
the prince of life, who destroys the prince of death, and his followers,
that will not have Christ to rule over them.

For doth not the apostle say, that there should be a falling away?
And that the man of sin should be revealed,
that son of perdition?`' And was he not manifest when Adam and Eve fell away,
and the Jews fell away?
And is he not manifest now when the christians are fallen
away from that power and spirit the apostles were in,
according to their own confession?

And doth not this man of sin oppose, and exalt himself above all that is called God,
to wit, in man; and will not let his obedient sons (them that are fallen away,
and gone after him, who is out of truth) own the light of Christ, and his grace, spirit,
word, faith, and anointing within them, to save and teach them?

But this man of sin, the son of perdition, sits in the temple of God,
and shows himself that he is God; but he is the disobedient world`'s god,
that lies in wickedness, and them that be dead in his sins.

For as Christ said to the Jews, '`God was not the God of the dead, but of the living:
and therefore he said I am the God of Abraham, Isaac, and Jacob,`' who were living.
Though Christ through death destroyed death, and the devil, the power of death,
who had brought people out of life and truth, into death;
but Christ by his quickening spirit makes alive, who is risen from death, and is alive,
and lives forevermore: and, therefore, he is God, not only of the living,
but of the dead, who quickens the dead, who doth reveal this wicked man of sin,
and takes him away, who hath letted,
who hath exalted himself above all that is called God in the temples of men and women,
that fall away from the truth, to him, who is out of truth;
but the Lord will consume him with the holy spirit of his mouth, that unclean,
foul spirit, in whom there is no truth, and destroy that foul,
dark spirit with the brightness of his coming.
For this world`'s god, who is out of truth, Satan, the adversary of mankind,
he comes into the disobedient to the truth, with his lying signs and wonders,
and with his power of deceivableness and unrighteousness in them that perish,
because they receive not the love of the truth, that they may be saved.

So you may all clearly see, if people receive the truth, in the love of it,
this man of sin, the son of perdition, the world`'s god, and prince of the air,
who is out of truth, and abode not in the truth, and there is no truth in him,
could never deceive them, nor get into their temple, to sit there, if they receive it,
and walk in the love of it, for the truth is over him, in which they are saved,
which they that go from it, to him that is out of truth, they perish,
though they may have the glory of the wicked world from that foul, unclean spirit,
that is out of truth, for a season; but that glory and joy will perish,
and be consumed and destroyed with its god,
by the Holy Spirit that comes out of the mouth of the Lord,
and through the brightness of his coming, who is come and coming.
And ride on, O Lord, in thy truth, to consume the wicked one,
which hath sprung as the grass; so that the workers of iniquity have flourished,
to the dishonour of thy great name, and the grief of thy good spirit.

And the world`'s god hath wrought with this foul,
unclean spirit in people`'s hearts adultery, theft, murder,
and all manner of unrighteousness, sin and evil, ungodliness, wantonness, voluptuousness,
and the pleasures of this world; and such have their false,
loose liberty in that foul spirit for a time, but eternal misery will be the end of it.
And such are they that kill the just, though he do not resist them,
and kick against that which pricks them in themselves, and are disobedient to it,
and persecute God`'s children and servants that are led by it, to wit, the good spirit.

And this was and is the unclean path of all the disobedient,
that follow the old murderer, the world`'s god, and adversary of man`'s happiness;
and he fills the disobedient ones, and puffs them up, and fills them with air,
vessels of God`'s wrath, that cannot hold the living water; for how should they,
when they are disobedient to God, and truth`'s good spirit?

And then they are thrown down into hell and the flaming fire, where they centre at last;
for how can they come into heaven by following him that is out of truth,
in whom there is no truth?

For if they come to heaven, they must come to the grace and truth,
that comes by Jesus Christ, which will turn them to Jesus Christ, from whence it comes,
who bruiseth this serpent, the world`'s god`'s head, and destroyeth him and his works,
who is out of truth.
And therefore they are not to serve him, whom God and Christ will destroy,
but serve the living God, and Jesus Christ, through his grace, truth and spirit,
and hear his voice, and follow him, who will give them life eternal.

And the world`'s god, the prince of the air,
cannot pluck Christ`'s sheep out of his fold, in the truth; for he is out of truth,
and there is no truth in him: And therefore he is not like to come into truth,
or to meddle with Christ`'s sheep in his fold of truth.
And, indeed, that lying, foul, unclean spirit, that is out of truth,
cannot prevail upon any,
except they first disobey the voice and command of God and Christ,
and err from the faith, and quench the spirit,
and walk despitefully against the spirit of grace, and hate the light of Christ,
and disobey the power of God, the gospel, and not regard the word in the heart and mouth,
and the truth in the inward parts; into such he may enter, and exalt himself as God,
into their house and temple, and fill it with his unclean goods, and lying foul spirit.

But all they which do live in and obey the truth, and walk in the spirit,
and do the word, and receive the grace, and believe in the light of Christ Jesus,
which is the life in him, by whom all things were made,
and so become children of the light, and walk therein,
then they walk in that which condemns the prince of the air, the god of the world,
and all them in whom he rules.
And so walking in the light, life and truth,
they walk over the head of him in whom there is no truth,
and so in fellowship one with another, and with the Son and the Father,
in this heavenly light, which is the life in Christ.

Now when Jesus was led of the spirit into the wilderness to be tempted of the devil,
and when he had fasted forty days and forty nights he was afterwards hungry,
and this tempter said unto him, '`If he was the Son of God,
command these stones to be made bread.`'

But Jesus said unto him, '`It is written, man lives not by bread alone,
but by every word that proceedeth out of the mouth of God.`'

And again, the devil takes him up, and sets him on a pinnacle of the temple,
and said unto him, '`If thou be the Son of God, cast thyself down, for it is written,
he shall give his angels charge concerning thee,
and in their hands they shall bear thee up,
lest at any time thou dash thy foot again a stone.`'

And Jesus said unto him, '`It is written, thou shalt not tempt the Lord thy God.`'

And again, the devil takes him up into an exceeding high mountain,
and showed him all the kingdoms of the world, and the glory of them, and said unto Jesus,
'`All these things will I give thee, if thou wilt fall down and worship me.`'

Then said Jesus unto him, '`Get thee behind me Satan; for it is written,
thou shalt worship the Lord thy God, and him only shalt thou serve.`'

So here you may see, how the serpent, the devil, set upon Christ,
to tempt him to the creatures, and to destroy himself, and to worship him.

But Christ, who bruises his head, and destroys him and his works,
which he had set up in man and woman, whom he had beguiled by his temptation,
and so got into them through their disobedience to the God of truth`'s command,
else he could not.

But here he finds nothing in Christ, nor got nothing from him, but judgment,
and bruising his head, and destroying him and his works.

So Christ, who hath overcome this tempter, this adversary of man`'s happiness,
and under a pretence, that man and woman should be as gods, they falling from the truth,
and departing from it, he getting into their temple, became their god,
and there he sits till he be consumed with the breath of the Lord`'s mouth,
and the brightness of his coming.

So we have not such a high priest as cannot be touched with the feeling of our infirmities,
but was in all points tempted as we are, yet without sin,
and no guile found in his mouth; who remaineth a priest forever,
and is able to save to the uttermost all that come to God through him.

So now, it is clear, he that was tempted hath a feeling of the infirmities of his people,
in all points tempted, tempted like unto them.
So he is able to support, and to succour them with his grace, power, spirit,
truth and light over the head of the tempter, who saith to his believers,
'`I have overcome the world, be of good comfort;`' and therefore it is said,
'`He that believes, overcomes the world and its god,`' in whom there is no truth.

Now the devil would have given Christ the kingdoms and the glory of the world (which
were not in his power to give) if he would have fallen down and worshipped him,
who is out of the truth, and in him is no truth.

But what glory of the world was this he would have given to Christ, the truth?
It is his world of wickedness, that lies in unrighteousness,
which he hath made like a wilderness;
such kingdoms and such glory he would have given him, and then Christ, who was the truth,
must have gone out of truth, if he had worshipped him, that was out of truth,
which could not be; for the Son of God doth not change.

And none can fall down and worship the devil, the god of the world, who is out of truth,
but they must go from the spirit of God,
and from the grace and truth in their own hearts; they must fall from this;
for this would keep up their hearts, minds and eyes to the God of truth.
Who reveals his glory of another world in his people; yea,
they are changed from glory to glory, until they come into his image.

But what is the glory of the world, and its kingdom that lies in wickedness?
What glory can that be, that the devil can give, the world`'s god, that is out of truth,
in whom there is no truth?
For John saith, '`all that is in the world, the lust of the eye, and of the flesh,
and the pride of life, which is not of the Father, but of the world, that passeth away;
and the lusts thereof,`' the pomps and vanities of the world, the pleasures, the plays,
the shows, the idleness, gluttony, drunkenness, whoredom,
and all the ungodliness and deceit, that is unlike God: who is it like then?
Why it is like him, the world`'s god, that is out of truth, in whom there is no truth,
but presumption and blasphemy, a liar, and the father of all liars,
who puffs up with airy notions his servants, and fills them with pride and wickedness,
the murderer, persecutor, and destroyer; he hath no other glory to give,
who is out of truth, and there is no truth in him.

For the glory of the creation is the Lord`'s, who created it;
for the earth is the Lord`'s, and the fulness thereof, and he gives the increase.

For as Christ saith, "`that Solomon, the wise man and great king, in all his glory,
was not arrayed like one of the lilies.`' So Christ
set up a lily beyond and above all Solomon`'s glory;
for the lily was arrayed of God, and every herb, and every weed,
and every tree are arrayed by God with the glory they have.

The world`'s god, the devil, the prince of darkness, he cannot array a nettle, a thistle,
nor a thorn; for he is no creator, but a destroyer;
for the eternal God of truth is the creator: but the world`'s god is out of truth,
and a destroyer and an adversary to they that keep in truth.

So the world`'s god out of truth,
could not give Christ the glory of a thistle nor nettle;
for it was none of his to give to Christ nor no man; for the earth is the Lord`'s,
and the fulness thereof, and he gives it unto the sons of men,
and so to live upon the earth, and to serve and worship him in spirit and truth,
which the world`'s god is out of.

Now the world`'s god, which is out of truth, and there is no truth in him;
if ye disobey God and Christ`'s voice and command, and go from his spirit,
and err from it and the true faith, and hate his light,
and walk despitefully against the spirit of grace, which he hath given to teach you,
and bring your salvation.

Now, I say, if men fall down from this grace, spirit, and truth,
which should keep their minds up to the God of truth and Christ;
and when the world`'s god, Satan, tempts ye, and says,
he will give you the glory of this world, of wickedness, the pomps of the world,
the lusts of the flesh, and the lusts of the eye, and the pride of life, fornication,
whoredom, drunkenness, theft, murder, defraud, deceit, cozening, cheating,
and all unrighteousness, and fill you with so much malice, envy, and pride,
that you envy one another about it, and think that each one is finer than yourselves;
that no vain fashion can hardly please your lust of the eye and pride of life;
and so leads into gluttony and drunkenness, idleness, sports, plays, and shows,
and all the vain fashions and customs of the world, honouring one another,
so that you do not honour God, and makes you mad, and fight for it, and about it.
All this, the world`'s god will give unto all such as come to worship him;
which is not of God, the father of truth, but from the world`'s god,
in whom there is no truth.

Now, you cannot worship the world`'s god but in his unclean, foul spirit,
which is out of truth, and in whom there is no truth.

And ye cannot worship the true, living, eternal, everlasting, pure, holy God of truth,
the creator and maker of all, but in his holy, pure spirit, and in his holy, pure truth,
which the devil, the prince of the air, the world`'s god, is out of.

And when the world`'s god hath blinded their eyes,
he leads them which way he will into blasphemies, heresies and errors,
and so from one false way, faith and religion, church and teacher to another,
when they go from the truth in the heart, and grace and spirit, from Christ Jesus,
from whom it comes, and follow him, in whom there is no truth.

Now, in the eighth chapter of John, Christ describes the devil, what he was,
and what he is, when he spoke to the Jews, saying, '`Ye are of your father the devil,
and the lusts of your father ye will do; for he was a murderer from the beginning,
and abode not in the truth, because there is no truth in him.
So he is not like to abide in truth, when there is no truth in him.
And when he speaks a lie, he speaketh of his own; for he is a liar, and the father of it.

But, now, ye may say, the devil, the world`'s god, could speak true words, and say,
Christ was the son of God, and brought scripture to Christ.

And so could the Jews to Christ, and so may the christians;
but what better are they for that, whilst they are not in the truth,
and in the spirit that they were in that gave forth the scriptures?
For Christ will not know such that are not in the truth, but are workers of iniquity;
for he knows such that walk in truth, and in the spirit, which they have from Christ;
here they come to have fellowship with him, and he feeds them, and they know his voice,
and follow him, and he keepeth them in the light, spirit, and truth.

So all people`'s applying scriptures, or promises, or prophecies,
whilst they grieve God`'s good spirit in their hearts,
and hate his light that shines there, and walk despitefully against the spirit of grace,
and so disobey the voice and command of God and Christ, such cannot have comfort of God,
nor Christ, nor the scriptures, nor the promises nor prophecies of them.
But they that walk in the light, and spirit, and grace, and the gospel,
they have the comfort of God and Christ, and the prophecies and promises,
and of the scriptures,
which holy men of God spoke forth as they were moved by the Holy Ghost,
which came not by men`'s wills; and these are for the perfecting of the men of God,
not the men of the world, which follow the world`'s god,
who are not like to have perfection by following of him, that is out of truth,
in whom there is no truth: for perfection comes by obeying God in his grace, spirit,
and truth, and following him, as God and Christ commands.

So it is clear, that God Almighty, who is the creator of all,
and made man and woman in his image and likeness, in righteousness and holiness,
he was their teacher:
but when man and woman forsook God and disobeyed his voice and command,
and hearkened unto the serpent`'s teaching, and followed him,
they came to bear his image, and to do his works and lusts,
(not God`'s,) that murderer from the beginning, and is to this day a liar, murderer,
and persecutor about religion, church, and worship.

But the promise of God was to fallen man,
that the seed of the woman should bruise the serpent`'s
head;`' who is the head of all false prophets,
false '`teachers, false apostles, and false religions, ways, worships,
and false heads of them.
And of destroying him and his works, who through death destroys death,
and the devil the power of it.

And Christ saith, "`Learn of me, I am the way, the truth, and the life;
and no man cometh to the Father but by me.`' And God saith, '`this is my beloved Son,
hear ye him.`'

And so the apostle testifies in Heb. 1. who saith, '`God at sundry times,
and after divers manners, spoke in times past to our fathers by the prophets;
but he hath in these last days spoken unto us by his son,
whom he hath appointed heir of all things, by whom he made the worlds.`'

So now, here are three things to be minded in these words.

God was the first speaker to Adam and Eve in paradise;
and as long as they kept under his speaking and teaching, they kept the paradise of God,
and in that happy and blessed estate, in the image of God, and in his power,
dominion and wisdom, over all things which God had made.

But when they forsook God`'s teaching, and followed the serpent`'s teaching,
the second speaker, who is out of truth, in whom there is no truth, they lost,
and fell from truth and the image of, God, and the power in which they had dominion,
and fell from their perfection, and lost their blessed state in the paradise of God.

Nevertheless, the promise to them and mankind then was,
'`The seed of the woman should bruise the serpent`'s head:`' And
all the fathers and the faithful believed in this promise of God,
and died in the faith of it.

'`And God spoke by the prophets to these fathers at sundry times,
and after divers manners, in the old covenant.`'

But the seed being come which bruiseth the head of the serpent, that false teacher, liar,
murderer and deceiver, who is the head of all false teachers, ways, religions,
churches and worships; Christ, who is the saviour and the life, in these last days,
of the new covenant of grace, light and life, God hath spoken unto us,
the children of the new covenant, by his son, the immortal,
eternal and living God of truth, who was the first speaker to Adam and Eve in paradise,
who was the speaker by the prophets to the fathers in the old covenant,
who is the speaker unto his children of the new covenant by his son,
who bruiseth the head of the prince of the air, and destroyeth the serpent,
the world`'s god and false speaker.

So, the eternal God of truth, who was the first speaker,
he is the speaker again unto his people, by his son now,
in these latter days of the new covenant, and so will be to all eternity;
who by his son renews his believers again into the image of God,
as Adam was in before he fell; and creates them anew in Christ Jesus, unto good works,
out of the bad works,
that they may come to sit down in the heavenly places in Christ Jesus, that never fell,
who is the first and last, by whom all things were made and created,
who is over all things in this life, light, truth and righteousness,
in his kingdom of glory. Amen.

[.asterism]
'''

And is not that the beast and whore,
which goeth from the holy spirit of the God of truth, and receiveth the dragon`'s power,
in his foul, unclean spirit, whose kingdom is full of darkness, and compelleth all,
both small and great, to worship the beast in the dragon`'s power, and the whore,
that is whored from the clean holy spirit, of the God of truth,
which sits upon the beast,
which makes all nations to drink her filthy cup of fornication, and compelleth,
and would compel to drink of that foul cup, and worship that dragon, in that foul spirit,
in whom there is no truth; and would draw people from the light, and from the grace,
truth and spirit, and the word and faith within their hearts,
and cornpasseth all the earthly minds, though he cannot the heavenly and spiritual minds,
whose names are written in the lamb`'s book of life, before the world and his god was;
those he cannot get under his dark power, in whom there is not truth,
though he may draw them that disobey Christ and the God of truth?

And was not the law and the old covenant and testament
given forth to the Jews in their mother-tongue,
from God and his prophets, and to be read amongst them in all their synagogues,
and in their temple, in their own tongue and language?

And therefore are not the scriptures of the New Testament and new covenant to be translated,
and to be read, spoken and interpreted in every man`'s language and mother-tongue?
And they that are against it, and do gainsay it, are they not barbarians,
that say '`That all nations must not have the new covenant
and New Testament in their own mother-tongue or language,
translated, to read it?`' They are barbarians that do not edify.
And we do know, that the world`'s god and his followers,
would keep people as ignorant from the scriptures as to have them in their own languages,
as he would draw every man and woman from the light
which Christ doth enlighten them withal,
to believe in, and to be a child of light: And this light shining in their hearts,
to give them the knowledge of God, in the face of their saviour Christ Jesus,
from whence it comes; and to draw men from the spirit, which God poureth upon all flesh,
and say,
'`That is not sufficient to instruct them and to lead them into
all truth;`' by which they might profit in the things of God:
And to draw them from the grace and truth, which cometh by Jesus Christ in their hearts,
'`which grace hath appeared unto all men,
to teach them and bring their salvation:`' But them that follow the world`'s god,
in whom there is no truth, who is a destroyer, deny the grace to be a sufficient teacher,
and to save, and bring salvation.

And they that walk despitefully against the spirit of grace,
and turn this grace of God into wantonness, and follow ungodliness,
unrighteousness and worldly lusts, they do follow the god of the wicked world,
in whom there is no truth; and then such do crucify the just,
instead of crucifying their affections and lusts,
and put on the old image and the old man, which is after the god of the world,
in whom there is no truth, and puts off the new, which is after the God of truth.

And the apostle Paul said, '`So fight I, not as one that beateth the air,
but I do keep under my body, and bring it under subjection, lest that by any means,
when I have preached to others,
I myself should be a cast-away:`' This was the practice of the apostle of Christ.

But Satan, the world`'s god, his ministers and teachers,
instead of keeping under their bodies, do let them up in all manner of filthiness,
and a beating the air, and their fellow creatures,
and them that serve the God of truth in his holy spirit, and spoiling their goods,
and haling them into prisons till death, spoiling them:
And this is the fruits of the spoiler, the world`'s god, and the power of death,
who abode not in the truth, in whom there is no truth, which is unlike Christ, who said,
'`Freely you have received, freely give,`' to Christ`'s followers,
which the world`'s god and his followers cannot endure to hear of this command.

And is it not only deceit in those that say, '`The scripture is the rule of their faith,
life, manners and doctrine;`' and yet are found serving the world`'s god,
that is out of truth, in whom there is no truth;
and cannot endure to hear talk of the grace of God, which appears unto all men,
to teach them, and bring their salvation, to be in man: And cannot endure to hear talk,
that Christ enlightens every man that cometh into the world with a saving light,
to believe in; and that this light should be in their hearts,
which is saving to the believer in it, and condemns the unbeliever of it:
And cannot endure to hear talk that God should pour out of his spirit upon all flesh,
to instruct them, and to lead them, that they may profit in the things of God:
And that Christ hath tasted death for every man, by the grace of God,
which hath appeared unto all men, that all might have a sense of it:
and the gospel of good news and glad tidings preached unto, and in every,
creature under heaven: and that he through death destroys death, and the devil,
the power of death.
This is glad tidings to all people that receive it;
but bad news to the world`'s god and his followers, that disobey the truth, and him,
in whom there is no truth; who manifest, that their words corrupt their manners,
and they are dead in sins and trespasses, and serve not Christ in the new and living way.
For their fruits declare their faith is dead,
and their doctrines not according to scripture: for they are reproved by the prophets,
Christ and the apostles; who confess they have not the same power and spirit as Christ,
and the prophets, and apostles had: but in their own wills,
and in the foul spirit that is out of truth,
make a profession of the scriptures of the Old and New Testament,
which came not by the will of man,
but holy men of God spoke them forth as they were moved by the Holy Ghost.

But at the moving of this Holy Ghost,
and leadings thereof into the truth of the scriptures,
which were given forth by the movings of the Holy Ghost, such as have said,
'`the scriptures are their rule for their faith, life, manners,
doctrine and conversation, have made a scoff at the Holy Ghost`'s moving and leading now,
as it did them which gave them forth; and such their manners, life,
conversation and doctrine, is quite contrary to the scriptures,
and are reproved by them and by the Holy Ghost,
that moved upon them that gave them forth.

Now, for unholy men, that plead for sin and a body of death to the grave,
and a purgatory for to cleanse them in from their sin, when they are dead;
for such to interpret in their wills,
and give meanings with their unclean spirit to the scriptures,
which holy men of God spoke forth as they were moved by the Holy Ghost,
and minded nobody`'s wills.
For unholy men, with their wills and unclean ghost, that serve the world`'s god,
that is out of truth, how are they like to interpret that, and give meanings to it,
without wresting or perverting it,
that have not the same Holy Ghost that they had which gave forth the scriptures,
which came not by the will of man, but by the Holy Ghost, as was said before,
which no man can interpret in his will; nor are they to be led into the truth of them,
which holy men gave forth by the Holy Ghost,
but by the same Holy Ghost that gave them forth,
which leads into all truth and good manners, and conversation;
and the same Holy Ghost gave forth the true doctrine of the scriptures.

And this Holy Ghost, which Christ sends, lead to him,
the author and finisher of their precious faith, and to God,
and to the same faith of Abraham, and Moses, and Enoch,
that was before the scriptures were written, which guided them to see God,
who is invisible, and to forsake all, and follow him: and so doth the same faith now,
and brings unity with them, and to the comfort of the scriptures with all the faithful,
which God and Christ hath declared forth, and they see what is fulfilled,
and what is to be obeyed.

So Christ is the author of their faith, that doth increase it.

Now men being disobedient to the spirit of God, and to the voice of God and Christ,
and gone from his light and grace, and obeying him in whom there is no truth,
they make prayers for themselves, and for others,
and think that the bare saying over their prayers, and their paternosters,
and their praying by beads and books, they think that this will pacify the true God,
(because something in themselves disquiets them) which God doth not accept,
the prayers of such that disobey and rebel against his good spirit,
and obey the evil spirit.
For all the prayers that God accepts, they must proceed from his own spirit,
which he hath poured out upon all flesh.

So God, that is the holy, pure God of truth, must be prayed unto in his own holy,
pure spirit; and such prayers and praises he expects, and accepts of;
and not the prayers of the disobedient to his voice and good Spirit, who follow the foul,
unclean spirit, in whom there is no truth.

And also, men may think to please the God of truth by saying of grace,
and making of graces (as they call them) for others to say;
but they are mistaken who walk despitefully against the spirit of grace;
it is not their making or saying of graces that makes them acceptable to God.
For the grace of God, which brings salvation, hath appeared unto all men:
therefore all men must live in that grace, and observe its teaching,
and deny all that which it shows them to he unlike God; and unrighteousness,
not like the righteous, not like the holy God;
and then in this grace the God of all grace will accept them, and their thanks,
prayers and praises for all his mercies.

But if they walk despitefully against this spirit of grace,
and turn this grace into wantonness, and then fall a making graces,
and saying of them when they have made them, and following the unclean, foul spirit,
that is out of truth, and abode not in the truth, in whom there is no truth;
and doing the works that this unclean, foul spirit works in them,
these works and spirit are for condemnation (and all them that act in it) by the light,
and are judged by the spirit of the living God of truth?

And the world`'s god, who is out of truth, will allow such as disobey the truth,
and follow his unclean spirit, to cry against blasphemy,
when they are themselves the greatest blasphemers; as for instance: the Jews,
unto whom Christ said,
'`they were of their father the devil;`' how they blasphemed against him,
and called him a blasphemer, who never sinned, nor guile was found in his mouth:
and how should they do otherwise but blaspheme, when they disobey the truth,
and the spirit of God in their own hearts,
and blaspheme both against him that was the truth, and them that walk in the truth,
when they follow the world`'s god, in whom there is no truth?

And is it like, that the world`'s god and his followers should own revelation, prophecy,
and inspiration now-a-days, as the apostles had?
Did not he and his followers call them deceivers, then,
who with the spiritual weapons wrestled not with flesh and blood,
but with principalities and powers, and rulers of darkness in high places,
that were set up by the world`'s god, and in his dark old earth,
in whom there is no truth?

And is it like, that them who follow the world`'s god, in whom there is no truth,
in that false, foul, unclean spirit, should own the Holy Ghost, the spirit of truth,
that proceeds from the Father and the Son,
that should lead them (or the saints) into all truth.

And is it like, that the world`'s god, and them that follow him,
in whom there is no truth, and disobey the God of truth,
that he and they should own the worship of the God of truth,
in the holy spirit and in the holy truth,
which Christ the truth set up above one thousand six hundred years ago?

And is it like, that the world`'s god, which abode not in the truth,
in whom there is no truth, and his followers, should own Christ, and his true light,
that is, the life in himself,
with which he lighteth every man that cometh into the world, and his doctrine, who saith,
'`Believe in the light, that ye may become children of the light:
And he that believeth is born of God,
and overcometh the world;`' and so overcometh the world`'s god,
in whom there is no truth:
And so do you think that the world`'s god and his
followers should own and obey his doctrine,
to have himself and his works overcome?

And is it like, that the world`'s god, which is out of truth, and his followers,
would have people to believe and receive, that Christ, by the grace of God,
tasted death for every man, which the world`'s god hath brought into death?
And that this grace of God, which brings salvation, hath appeared unto all men,
to teach them and bring their salvation from him that doth destroy them?

And do you believe that the world`'s god would have people to believe, that Christ,
through death, destroyeth him (the devil) who is the power of death?

And do you think that the world`'s god, who is out of truth,
and in whom there is no truth, and his followers,
would have all people to believe that God pours out of his spirit upon all flesh,
so that with his spirit all flesh may see God`'s glory, and his salvation to mankind,
and his sons and daughters might come to prophecy
and be seers and followers of the God of truth,
and servers of him in his spirit?

And do you think that the world`'s god, in whom there is no truth, and his followers,
would have people to own the revelation of the Son of God now-a-days?
Or rather keep them in blindness, in this world`'s wisdom, by which they do not know God,
seeing that Christ saith, '`No man knoweth the Father, but the Son,
and he to whom the Son revealeth him?`'

So do you think that the world`'s god, in whom there is no truth,
would have people to own revelation now-a-days as it was in the apostle`'s days?
The apostle tells the church of Christ, '`That faith was revealed,
and grace was brought unto them, by the revelation of Jesus;
and no man knew the things of God,
but as they were revealed by the spirit of God,`' that is pure and holy.
And the Son of God is known by revelation, as Paul knew him;
and the gospel is known by revelation;
and the glory of God is revealed to them that know it.
1 Pet.
v.

So do you think that the world`'s god, that foul, unclean, dark, murdering spirit,
and them that obey him, would have people to own this pure, holy spirit of God,
and the grace, light and truth, and the gospel that comes by Jesus Christ,
the spotless lamb, and follow him in it?
This is contrary to him and his kingdom, whom the spotless lamb destroys,
and is the conqueror, and the saints follow and live in him the Amen;
blessed and praised be the God of truth forever, through Jesus Christ.

[.signed-section-context-close]
6th month, 1679.

[.signed-section-signature]
G+++.+++ F.
