[#ch2.style-blurb, short="A Distinction Between the Old and New Covenent"]
== A clear Distinction between the Old Covenant, or Old Testament, and the New Covenant, or New Testament; and how that Christ hath abolished and taken away the First Covenant and Testament, and established the Second. By G. F.

For in Jer. 31:31. it is said, '`Behold the day cometh, saith the Lord,
that I will make a new covenant with the house of Israel and the house of Judah.`' Mark,
this was a prophecy which they were to behold and take notice of;
these days were to come, and these are the days of Christ,
who came above sixteen hundred years since.

For the Lord saith, '`I will give thee for a covenant with the people,
and for a light to the Gentiles, to open their blind eyes,`' etc.
So this new covenant is to the Gentiles, as well as to the Jews.
Isa. 42.

And again, the Lord saith, '`I will give thee for a covenant to the people,
to establish the earth, to cause to inherit the desolate heritage,
that thou mayest say to the prisoners, go forth; to them that are in darkness,
show yourselves; and they shall feed in their ways, and in their pastures.`' Isa. 49.

'`And in that day there shall be a root of Jesse,
which shall stand for an ensign of the people, and unto it the Gentiles shall seek,
and his rest shall be glorious.
And he shall set up an ensign for the nations,
and shall assemble the outcasts of Israel.`' Isaiah 11.

And further, he saith, '`The Gentiles shall come to his light,
and kings to the brightness of his rising.`' etc.
Isa. 60.

Now it is clear, according to these promises and prophecies,
that the new covenant is not only to the Jews, but to the Jews, Gentiles and nations,
according to Isa. 42. '`Behold, or take notice, the former things are come to pass,
and new things do I declare, before this spring forth,
I tell you of them.`' This did Isaiah speak by prophecy concerning the days of Christ;
who saith in the same chapter, '`That he shall set judgment in the earth,
and the isles shall wait for his law,
and he shall bring forth judgment to the Gentiles.`'

Now the law from Sinai the Jews had before; but this is the law of life,
in the new covenant, which law of life goes from heavenly Zion,
and the word from heavenly Jerusalem, in the new covenant.

So these are new things, which were declared before they came to pass;
for the old things of the old covenant they had already,
when he declared these new things.

And therefore the Lord saith by Jeremiah, '`Behold, the day shall come,
that I will make a new covenant with the house of Israel;
not according to the covenant that I made with their fathers,
when I brought them out of the land of Egypt:
But this is the covenant that I will make with the house of Israel: after these days,
saith the Lord, I will put my laws in their inward parts, and write them in their hearts;
and I will be their God, and they shall be my people:
And they shall not need to teach every man his brother, and every man his neighbour,
saying, know the Lord; for they shall all know me,
from the least of them unto the greatest of them, saith the Lord:
For I will forgive their iniquity, and I will remember their sin no more.`'

So this is the new covenant, in which all shall know the Lord,
that was promised and prophesied of before it came to pass,
which is not according to the old.
Jer. 31.

And in Heb. 8. the apostle showeth the fulfilling of Isaiah`'s and Jeremiah`'s,
and Ezekiel`'s prophecy; and how the new covenant was come,
and he preached up the new covenant, and preached down the old;
and how that all should be taught of God in the new covenant: So in that he saith,
the new covenant, he hath made the first old covenant as a thing decayed,
and ready to vanish away.

And in Heb. 9. he saith, how the first covenant had ordinances of divine services,
and a worldly sanctuary and tabernacle, and candlestick, and table, and show-bread,
and censors, and pot of manna, and Aaron`'s rod, and many other outward things.

But in the new covenant Christ hath abolished all these outward things,
who will rule all nations with his rod of iron, which is beyond Aaron`'s rod.

And so it is clear, that the new covenant is not according to the old:
For in the old covenant, the priest`'s lips were to preserve the people`'s knowledge,
And Ezra had a pulpit of wood to read the law to the people upon:
And the law was written in tables of stone.
But in the new covenant and testament Christ ends this priesthood,
whose lips were to preserve the people`'s knowledge;
and they are to look unto Christ Jesus,
who is the treasure of wisdom and knowledge in the new covenant.

And God writes his laws in their hearts,
and puts them in their minds in the new covenant, by which all may know him,
from the greatest to the least of them.

And in the old covenant they had sanctuaries, and tabernacles, and temple,
and the high priest was to light the candle and lamps in them.
But in the new covenant, Christ who ends the first priesthood, and the old covenant,
and abolishes the sanctuary, tabernacle, and outward temple and lamps,
enlightens every man`'s spirit that cometh into the world, in his tabernacle or temple,
with his heavenly light, which is the life in himself, Christ Jesus, the high priest,
made higher than the heavens.
So he was made by the oath of God, and fulfils it;
so were not the priests in the law and old covenant.

So the new covenant is not according to the old; for the old covenant, and the law,
commanded offerings and sacrifices; but Christ in the new covenant,
offered up himself once for all the offerings and sacrifices, and ended them all,
and the old covenant also.

And in the old covenant, the blood of the clean beasts,
the priest with it made atonement for his own sins, and the sins of the people:
But in the new covenant, Christ, with his own blood,
hath made atonement for the sins of the whole world;
'`and by the grace of God hath tasted death for every man; which grace of God,
that brings salvation, hath appeared to all men, to teach them,
and bring their salvation, etc.`' And '`he hath given himself a ransom for all men,
to be testified of in due time,`' in the new covenant;
which the days thereof are come above sixteen hundred years since.

So in the new covenant of light, life and grace,
there is no need of offering rams and beasts, and other creatures for sins;
nor the blood of bulls and goats, nor the ashes of a heifer to cleanse;
nor outward lights nor lamps, in the outward tabernacle;
for Christ Jesus hath offered up himself once for all: And he, the one offering,
is a sufficient atonement in the new covenant, for the sins of the whole world.
And his blood, (the life of him) the clean lamb of God, without blemish,
'`who takes away the sins of the world,`' is sufficient to cleanse from all sin.
And his light, that is the life in him, the word, by which all things were made,
is sufficient to light every man`'s spirit, that cometh into the world.
And the oil from him, the heavenly man, is sufficient for every man`'s lamp,
to keep it burning.

So the new covenant is not according to the old; nor the New Testament is not as the Old.
For the New Testament is in the blood of Christ, which cleanseth from all sin;
and in him, the one offering, '`who offered up himself once for all,
who is the Lamb of God that takes away the sins of
the world.`' And the New Testament is in Christ,
who is the life and light of men.
And the Old Testament, in the old covenant, was for the outward light, and lamps,
and temple, tabernacle and sanctuary, and the priest`'s lips,
which preserved the people`'s knowledge: But the New Testament, in the new covenant is,
'`that Christ is the treasure of wisdom and knowledge;
and he is the everlasting high priest, who hath offered up himself for them,
and is risen, and is alive again, and lives forevermore;`' and is their light and life.

And in the Old Testament and old covenant,
the priesthood continued after the order of Aaron: But in the new covenant and testament,
Christ is after the order of Melchizedec, after the order of Aaron,
nor came not of that tribe, but of the tribe of Judah.
And in the New Testament and new covenant, all the believers in it,
their bodies are the tabernacles and temples of God and Christ,
and Christ the high priest dwells in them:

But in the old covenant and testament the priests had chambers in the temple;
which chambers and priesthood Christ hath abolished,
and made his chamber in the hearts of his people.

And in the old covenant and testament there was a covenant of salt,
with which the sacrifices were to be salted, and the priests were to salt them:
But in the new and everlasting covenant and testament, Christ,
the high and everlasting priest, doth salt all the spiritual sacrifices of his people,
and makes them savoury, and makes his followers the salt of the earth,
and the light of the world; so that they need not have the outward salt, and light,
and lamps in the old covenant, which Christ hath abolished.

And in the old covenant the Jews were to keep their feasts of tabernacles,
and the feast of passover, throughout all their generations;
and they eat of this passover when they came out of Egypt:
but in the new covenant and testament, the Jews in spirit,
that pass out of the spiritual Egypt, feed upon Christ, their heavenly passover,
and keep the heavenly passover throughout all their generations in the new covenant,
and keep their heavenly spiritual feast of tabernacles,
dwelling in the green booths of the green tree, Christ Jesus, the heavenly man,
the second Adam, whose leaf never withers, fades nor falls, but is always green.
And Christ abolishes the feasts and passovers of the old covenant;
so the new covenant is not according to the old.

And the Jews, in the old covenant, brought all their first fruits,
and offered them to the priests; so there was a feast of the first fruits.
But in the New Testament and covenant of light and grace,
they do offer the first fruits of the spirit, that which the spirit inspires them with,
or reveals to them; which spirit hath ploughed up the fallow ground of their hearts,
and so they sow to the spirit, and of the spirit reap life;
which crop goes into God`'s garner,
which the heavenly high priest gathers into his heavenly garner, his heavenly wheat,
that is threshed out with his heavenly spiritual flail.
For the priests, in the old covenant,
had their first fruits brought into the outward garner, which Christ abolishes:
So the new covenant is not according to the old.

And in the old covenant and testament,
there was but one tribe of twelve that was made a priesthood,
and they were to have no portion nor lot in the land,
but tithes and offerings was their portion and salary.
But Christ in his new covenant and testament makes
'`all his believers priests,`' as Peter saith,
and to offer up spiritual sacrifices:`' And saith in his general epistle,
'`Ye are a holy nation, a royal priesthood, a peculiar people,
offering up spiritual sacrifices,
having one high priest (Christ Jesus) that lives forever;
who sanctifies his people (his church) and washes and cleanses them with
the heavenly water of his word.`' So his people are a nation of priests,
of men and women;
for all must offer up to the Lord their spiritual sacrifices in his new covenant,
both male and female are all one in Christ Jesus.
And so he ends the first priesthood, and abolishes him,
with all his outward water and washings, and ends all his offices,
and changes the law by which he was made,
and the commandment that gave him his tithes and offerings.
For by the law he was to have no lot of the land: But now that law being changed,
he may take up land where he can, as others do.

And Christ saith in the new covenant and testament to the followers and learners of him,
'`Freely you have received, freely give:`' And bid them, '`Go without a bag or staff:
and into what city or town they came, they were to inquire, Who was worthy?
and to eat such things as were set before them:
For the workman was worthy of his meat.`' So the new covenant is,
'`Freely you have received, freely give:`' And they need neither bag nor staff:
for Christ the great prophet and priest will supply and uphold them.

And so it is clear, the new covenant and testament is not according to the old,
nor the new and living way according to the old way among the Jews;
which old covenant and testament, and old law, and old way among the Jews served,
until the seed Christ came,
who is the new and living way in his new covenant and New Testament;
and hath abolished that old way, Old Testament, covenant and law.

And in the old covenant, their circumcision was in the flesh,
and in that they were to obey and serve God; and he that was not circumcised,
was not to eat of the sacrifice, but to be cut off;
and the priest and levite was to circumcise them.
But in the new covenant and testament, Christ, the high priest,
is the minister of the circumcision of the spirit;
which circumcision of the spirit puts off the body of death, and the sins of the flesh,
which is got up in man and woman by transgression.
For Adam and Eve had not a body of sin and death before they transgressed.
So the christians in the new covenant of grace and light,
are the circumcision of the spirit, which serve and worship God in the spirit:
And such eat of the heavenly passover and supper (Christ
Jesus;) and if they be not circumcised with the spirit,
they are cut off from keeping that heavenly feast of the passover (Christ
Jesus.) So the new covenant and testament is not according to the old;
for Christ hath abolished both the Jewish passover and circumcision of the old covenant.

And in the old covenant and testament, they that did resist the high priest,
and gainsaid Moses, died an outward death by the hands of two or three witnesses.
But in the new covenant,
they that do neglect to hear the great prophet and
high priest (Christ Jesus) whom God hath raised up,
like unto Moses, and will not have him to reign over them,
nor hear him that speaks from heaven, a more severe punishment comes upon them,
than they that died by the hands of two or three witnesses (that
did resist Moses;) for that was a natural death in the old covenant,
but this is an eternal death in the new covenant.
And therefore hear the Son of God in the new covenant, and ye shall live;
'`and whilst it is called to day,
hear his voice,`' (for ye may be dead before tomorrow.) I say,
hear him that speaks from heaven, whose voice shakes the earth,
and so all that appertains to the earth, or is earthly; and not the earth only,
but the heavens also, that they may appear, which cannot be shaken, to wit,
the seed of life.
So people was to hear Moses and the high priest in the old covenant and testament:
But now they are to hear Christ, their high priest and prophet,
that God hath raised up in the new covenant, in his grace, light and spirit.
For the law came by Moses, in the old covenant;
and all the people of the Jews was to hear the law in the old covenant, and do it,
and live:
'`But grace and truth is come by Jesus Christ,`'
in the new covenant and testament of light,
life, and grace.

And so all the children of the new covenant are to hear Christ in his grace,
and to be under the grace, and truth`'s teaching, which will bring their salvation.

Now you may object, and say,
'`Do not the scribes and pharisees set in Moses`'s seat or chair?
And all that they bid you do, are ye not to do and observe it?`'

This Christ spoke before he was offered; for before he was offered up, he bid the people,
whom he had cleansed,
'`Go and offer a sacrifice to the priest for their
cleansing.`' And before he was offered up,
he told them, '`They ought to pay tithe of mint and anise to the priest,`' etc.
But when he had offered up himself once for all the offerings,
he put down all the priests, and their offerings;
and sent his disciples into all nations to preach the gospel:
And then he did not bid them go and hear the scribes and pharisees,
that sat in Moses`'s chair, and go to the priests for their cleansing,
and give them their tithes: But by the offering up himself once for all,
he had ended the priests and their services, and the old covenant, and its works.
+++[+++Mark, An offering once for all, for the sins of the whole world.`']
Then there was no need of the priests in the old law, to offer lambs and rams,
and the blood of the creatures, for the cleansing of the sins of the people, etc.
But the priests, in the old covenant, his works were finished; and his wages and salary,
his tithes and offerings, were taken away also.
So he took away the first old covenant, testament and priesthood,
and established the second.
So tithes in the old covenant and testament to the priests we grant;
but Christ hath abolished both it and them.
And the new covenant is not according to the old, in which Christ saith,
'`Freely you have received, freely give.`'

And in the old covenant and testament,
the Jews were to appear three times a year at the outward temple,
and there to worship the Lord: And there was another place of worship,
where Jacob`'s well was, at the mountain near Samaria.
But Christ saith in his new covenant and testament,
in John 4. That God is not worshipped, neither at the mountain of Samaria,
nor yet at Jerusalem; for the hour cometh, and now is, +++[+++Mark, now is]
that the true worshippers shall worship the Father in spirit and truth;
for the Father seeks such to worship him: '`For God is a spirit,
and they that worship him,
must worship him in spirit and truth.`' So this worship in the new covenant and testament,
is a new worship, which Christ Jesus, the heavenly spiritual man, the second Adam,
set up above sixteen hundred years ago;
and then put down and abolished the worship at the mountain,
and the worship at Jerusalem, when he set up this worship in spirit and in truth.
And this spirit and truth must every man and woman feel in their hearts,
by which they may know the God of truth, who is a spirit.
And so the Jew inward worships in temple, his body being the temple of the Lord.
And the Jew outward, in the old covenant and testament;
they sung and prayed in the temple, at outward Jerusalem: But the Jew inward,
in the spirit, in the new covenant and testament, and new and living way,
sings and rejoices, and prays in the Holy Ghost,
their bodies being temples of the Holy Ghost.

And so it is clear, the new covenant and testament, and the new and living way,
is not according to the old.

And in the old covenant and testament,
God poured out of his spirit upon the house of Israel,
that by it they might serve God in his law.
But in the new covenant of light and grace, and the New Testament,
'`God pours out of his spirit upon all flesh,`' as was prophesied
of in Joel 2. And the apostle preached the fulfilling of it,
in Acts 2. So that with the spirit all flesh might see the glory of God, and see Christ,
'`who gave himself a ransom for them all, and tasted death for every man.`'

And so in the new covenant the holy ghost, which proceeds from the Father and the Son,
leadeth the servants of God and Christ into all truth,
and reproves the world for their unbelief, and their false judgment and unrighteousness.
So that they need not have the priest`'s lips of
the old covenant to preserve their knowledge,
nor the priest to kill the clean beasts, to offer up for their sins,
to cleanse them with the blood of the clean beasts;
and they need not have the clean beasts to die for them: For Christ,
the lamb without blemish, hath tasted death for every man,
and died for the sins of the whole world, and so not only for the Jews.

And so God pours out his spirit upon the house of Israel,
that by it they might understand the law of works, and do it.

But in the new covenant, as was said before, God pours out of his spirit upon all flesh,
that by it they might understand the law of life, which is in Christ Jesus,
to make them free from the law of sin and death.

And as all the outward Jews in the old covenant were to walk in the law of works;
so in the new covenant of light and grace, and New Testament,
they are to walk in the light and spirit, and the law of life in Christ Jesus,
as every one hath received him.

And as the outward Jews in the old covenant and testament
received the law from Mount Sinai;
so the inward Jews in the spirit in the new covenant
and testament receive the law of life in Christ Jesus,
laid in heavenly Zion.

And so it is clear, the new covenant and testament is not according to the old.

And the old covenant and testament did forbid the
outward Jews the eating of several sorts of creatures;
but in the new covenant and testament, and the new and living way, Christ saith,
'`He that made that without, made that within, and that all things are clean;
and whatsoever goeth into the mouth, doth not defile the man;
for it goeth into the belly, and so into the draught, the purger of all meats.`'

But Christ Jesus is the purger of the conscience, mind, heart and soul, with his blood,
his life, the clean lamb without blemish,
and with his baptism with fire and the holy ghost: For he saith, '`These evils,
that come out of a man`'s heart,
defile a man.`' And so these evils came into man by transgression;
for Adam and Eve had them not, when God made them.

And the apostle saith, '`Whatsoever is sold in the shambles, that eat.`'

This he speaks to the Corinthians, who were Gentiles before their conversion:
And so these things sold, were in the Gentiles`' shambles; not in the Jews`' shambles,
where only the clean beasts and fowls were sold, but at Corinth,
or amongst the Corinthian shambles, where both were sold, 1 Cor. 10:25.
For the earth is the Lord`'s, and the fulness thereof;
'`And God saw everything that he had made, and behold, it was very good:`' Mark,
everything that he had made, he saw it was very good, Genesis 1:31.

And the apostle in the new covenant and testament, and in the new and living way, said,
'`Every creature of God was good, and nothing to be refused,
if it be received with thanksgiving; for it is sanctified by the word of God,
and prayer:`' For by the word of God were all things made,
and by his word and power were all things upheld: And the apostle saith to Timothy,
'`If thou put the brethren in mind of these things,
thou shalt be a good minister of Christ Jesus.`' 1 Tim. 4:4.

And moreover the apostle said, '`The kingdom of God stood not in meats and drinks,
but in righteousness, and peace, and joy in the holy ghost.`'

And when Peter saw in his vision a '`Sheet let down from heaven,
wherein were all manner of four-footed beasts of the earth,
and wild beasts and creeping things,
and fowls of the air;`' and there came a voice to him in the new covenant and testament,
and said, Arise, Peter,
kill and eat;`' And Peter having been a Jew of the Old Testament and covenant,
his voice was according to it, when he said, '`But not so, Lord;
for I have neither eaten any thing that is common or unclean.`'
And the voice spake unto him the second time,
and said, '`What God hath cleansed,
that call not thou common.`' Now the occasion of this was,
when Peter was to go and preach the gospel to Cornelius, a Gentile, as in Acts 10.

So here it is clear, that the new covenant and testament, and new and living way,
is not according to the old covenant and testament, and old way amongst the Jews:
For Christ doth reconcile in one, all things both in heaven and in earth.

And in the old covenant and testament, and the Jews`' old way, they did observe days,
months, times and years; and this they were commanded by the law.
But in the new covenant and testament, and new and living way, the apostle,
(that preached the new covenant, and the New Testament,
and the new and living way) brought them off from the observing of days, times,
months and years: And some after they were come from the observing of them,
were turning again to the weak and beggarly elements,
wherein they again desired to be in bondage: For saith he, '`Ye observe days and months,
times, and years.`' And the apostle said, '`I am afraid of you,
lest I have bestowed my labour in vain upon you.`' So he was afraid of them,
who had laboured to bring them out of the observing of them to Christ,
and his everlasting kingdom of light, life and grace:
And they to go back again into the observing of days, times, months and years,
they went into that which he had laboured to bring them out of; for which he was afraid,
lest he had bestowed labour upon them in vain.

So it is clear here, that the new covenant and New Testament, and the new and living way,
is not according to the old.

For in the old covenant and testament, the outward Jew had his days, times,
months and years, and feasts.
But in the New Testament and new covenant of light, and life and grace,
they came to the heavenly feast, and to the day of Christ,
and are called children of his day; and so have their bread from heaven,
and keep the heavenly and everlasting feast in Christ Jesus,
who abolishes the Jews`' feasts of the old covenant.

And in the old covenant and testament, God gave unto the Jews his Sabbath as a sign,
after he brought them out of Egypt, though he had not given it to Adam,
nor to the old world, nor to Abraham, Isaac and Jacob, by command to keep,
but to the Jews, and they were to keep it holy: And they were not to do their own work;
no, not so much as to make a fire to dress their meat, nor to think their own thoughts;
for six days they were to labour, and to do all their works in.
And this law that commanded this Sabbath, which God gave unto the Jews as a sign,
served till the seed Christ, the substance, came; and when he was come,
they accused him and his disciples as being sabbath breakers,
because his disciples gathered some ears of corn on the Sabbath day to eat.
And he healed on the Sabbath day.

And Christ said unto his accusers, the Jews, The Sabbath was made for man,
and not man for the Sabbath: Therefore the son of man is lord of the Sabbath, the sign,
who was the substance of it.`' Mark 2:23. 27. 28.

And this saying of Christ troubled the Jews,
that professed the old covenant and testament, and had the Sabbath, the outward day,
which was the sign in the old covenant.
Now that outward day was the sign of the eternal rest and day of Christ,
in his new covenant.
For Christ in his new covenant doth end all the Jews`' signs and shadows, and saith,
'`Behold, I make all things new.`' And as it is said before,
the apostle`'s labour was to bring them off the observation of days, etc.
And saith to the saints, in the New Testament and new covenant of light and grace,
'`Let no man judge you in meats or in drinks, or in respect of an holy day,
or of the new moon, or of the Sabbath, which were shadows of things to come;
but the body is of Christ.`'

So it is clear that the apostle brought the saints to Christ,
the substance of the shadows.
For the Sabbath, and the new moons, and those outward things amongst the Jews,
were but shadows and signs: And when the substance was come, the shadows fly away.
Col. 2.

So the apostle in another place, speaks of another day than the seventh day,
the Jews`' Sabbath, which is the day of Christ, and saith, '`We which have believed,
do enter into his rest.`' And again he saith, '`He that hath entered into his rest,
is also ceased from his own works,
as God did from his.`' So the believer`'s rest in the new covenant and New Testament,
and new and living way, is Christ Jesus, the substance, Heb. 6.

And the Jews were to keep the outward Sabbath day and sign holy,
and not to gather their meat, nor kindle a fire, nor bear a burden,
nor do their own work, nor think their own thoughts upon the Sabbath day,
(the sign) in the old covenant and testament.

So the true christians and children in the new covenant of light and grace,
that do enter into the rest by belief in the light, which is the life in Christ,
do cease from their own works; and in Christ, their Sabbath, their rest,
they bear no burden; and in him they do not think their own thoughts;
and in him they are not kindling their own fires;
and in Christ they are not gathering their own meat;
for he is their bread of life from heaven; so that in him they shall not hunger.
And he destroys the devil and his works, which hath burdened man and beast, yea,
even the whole creation; and in Christ people are over and above their own thoughts.
So all are to keep the eternal Sabbath, the eternal rest, by belief in the light,
which is the life in Christ, this holy day, this holy rest and Sabbath,
which ends the sign, that was to be kept holy in the old covenant.
For if the Jews in the old covenant and testament did not keep the Sabbath holy,
they were to be stoned to death with outward stones; but they that do not keep in Christ,
by belief in the holy rest, lie, the top and corner stone, falls upon them,
and grinds them to powder, and stones them to death with the heavenly stone,
that keep not in Christ, the holy, eternal, everlasting rest and Sabbath.

So here the new covenant is not according to the old;
for the old had an outward temporal day; but they in the new covenant have the substance,
Christ, and his eternal day, and enter into his everlasting rest, by belief in his light,
which is the life in him.

And the Jews in the old covenant and testament, and in their old way,
had outward helmets, shields and swords, and carnal weapons, and armour.
But Christ, in his new covenant and testament, who is the new and living way, he saith,
'`He came not to destroy men`'s lives,
but to save them.`' Though he was the king of kings, and lord of lords,
yet he was far off from giving any precept or command
to his disciples to destroy men`'s lives:
When some would have had fire to come down from heaven,
to consume them that would not receive him, he turned about and rebuked them, and said,
'`He came not to destroy men`'s lives, but to save them.`'

And such men as would have been plucking up the tares, Christ, the king of kings,
would give them no commission, no, not so much as a license; but said,
'`Let the wheat and tares grow together till the harvest, which was the end of the world;
and then his father would send forth his angels, which should be the reapers,
and they should sever the wheat from the tares,`' etc.
And Christ gave a reason wherefore he would not give
a commission to men to pluck up the tares,
lest they in their blind zeal should pluck up the wheat also with the tares.

And so Christ, in his new testament and new covenant,
who sent forth his twelve disciples, and after his seventy, to preach the gospel,
he did not send them with any carnal weapons or armour, or any carnal set maintenance,
or tithes, as was in the old covenant; nay,
they were not so much as to take a bag or a staff to defend them.

So the King of kings was far off from giving them commission or licenses,
to beat people into his religion, way, and worship, church, or belief,
with carnal weapons: but saith, '`He that believes, is saved; and he that doth not,
is condemned already;`' and that was punishment enough.
And therefore the apostle Paul saith, '`The weapons of our warfare are not carnal,
but spiritual.`' Mark, spiritual, in the new covenant and new testament,
and new and living way; but carnal, in the old covenant and old testament,
to the outward Jews in the old way.

And the apostle plainly saith, we in the new covenant and new testament,
and new and living way in Christ Jesus, wrestle not with flesh and blood;
who came not to destroy men`'s lives, but to save them;
but they wrestled with spiritual wickedness and rulers of darkness, etc.

And in another place the apostle tells the saints in the new covenant,
that their weapons and armour were the shield of faith, which is the gift of God,
which Christ is the author and finisher of, that saves men`'s lives;
and the sword of the spirit, the word of God; and the helmet of salvation,
that preserved their head; and the breastplate of righteousness,
that kept evil out of their breasts and hearts;
and their loins were to be girt with truth;
and to be shod with the preparation of the everlasting gospel of peace.

And these are Christ`'s ministers of the spirit, and believers, and true christians,
that stand in this armour, and have these weapons, and follow Christ,
and fight under his banner of love, with his spiritual armour and weapons,
in his new and living way, and new testament, and new covenant of grace and light;
and follow not the Jews in their carnal armour and weapons, and signs, and shadows;
for the substance is come.

So the new covenant and testament, and new and living way,
are not according to the Jews`' old covenant and testament, and old way,
which served till the seed Christ came.
And all those signs and shadows in the old covenant,
upheld with their outward weapons and carnal armour,
have done their service to hold up their signs and shadows; but Christ is come,
and hath abolished them.

And so it is clear, that the new covenant and new testament, and new and living way,
are not according to the old covenant, and old testament, and old way amongst the Jews,
as was said before.

And in the old covenant, and testament, and old way, the Jews were to swear,
and to perform their oaths unto the Lord; and not to swear falsely.

But in the new covenant, and testament, and new and living way,
Christ the son of God saith, '`Swear not at all, but let your yea be yea, and your nay,
nay; for whatsoever is more than these, cometh of evil.`' Matt. 5.

And the apostle James in the new covenant, in his general epistle saith,
'`Above all things, +++[+++mark, above all things]
my brethren, swear not,`' etc.
So these are the brethren in the new covenant, and testament, and new and living way,
that are not to swear at all.
And further he saith, '`They were not to swear by heaven, nor by earth,
nor any other oath; but let your yea, be yea, and your nay, nay,
lest ye fall into condemnation.`'

So it is clear, the command in the old covenant and testament,
which Christ calls the old time, in which they were not to forswear themselves,
but to perform their oath to the Lord;
so they did not go into evil and condemnation that did swear truly,
and perform their oath to the Lord in the old time, and old covenant;
but they go into evil and condemnation,
that swear at all in the time of the new covenant and testament: for Christ,
who is the oath of God, he fulfils the oaths of the old,
and takes away and abolishes the oaths of the old covenant,
and sets up yea and nay instead of them.

And now, if you should object, that Abraham, and Jacob, and Joseph, and Moses,
and the prophets, and the angels swore: Christ the son of God is greater than Moses;
who said '`Before Abraham was, I am;`' and he reigns over the house of Joseph and Jacob,
and fulfils the prophets; and he saith,
'`Swear not at all:`' and Christ the great prophet, whom God had raised up,
is to be heard in all things.

And as for the angel`'s swearing, it is said,
'`I bring forth my first begotten into the world,
let all the angels worship him,`' to wit, the son of God, who saith,
'`Swear not at all.`' And '`This is my beloved son,`' saith God, '`hear ye him.`'

And in the Old Testament it is said, '`That unto me every knee shall bow,
and every tongue shall swear, saith the Lord,`' in the old covenant and testament. Isa. 45:23.

But in the new covenant and testament the apostle quotes Isaiah, and saith,
'`Every knee shall bow, and every tongue shall confess to God.`' Rom. 14:10.

So here it is clear, that swearing was allowed in the old covenant and old time,
but confessing in the new covenant and new time.

And it is manifest,
that Christ hath taken away all swearing in his new testament and covenant:
for all swearing hath been since man fell from the image of God;
and Christ renews man and woman up into the image of God again, and sets up yea, yea,
and nay, nay, instead of an oath.

And Christ sets up in his new covenant instead of swearing,
'`true witness bearing;`' and that '`in the mouth of two or three
witnesses everything shall be established.`' He doth not say,
that in or by the mouth of two or three swearers everything shall be established.

And the apostle saith,
'`Let every man speak the truth to his neighbour;`' which speaking
truth is set up by Christ and his apostles instead of swearing,
which was commanded in the old time, and under the old covenant and testament,
in which the law commanded people to swear,
which oath was to end the controversy and strife amongst men;
which served until Christ the seed came.
But when Christ came, he abolished the law that commanded swearing, and swearing also.

And so it is clear, that the new covenant, and new testament, and new and living way,
is not according to the old covenant and testament, and the Jews`' old way.

And the apostle Paul writes to the Galatians,
and to such as were going again into circumcision and the law, and he saith unto them,
'`As many as are for the works of the law, are under the curse: for it is written,
cursed is every one that continueth not in all things,
which are written in the book of the law to do them.`'

And again he saith, '`That no man is justified by the law in the sight of God,
it is evident; for the just shall live by faith; and the law is not of faith.`'

And again he saith, '`Christ hath redeemed us from the curse of the law,
being made a curse for us.`' Gal. 4.

And here it may be seen, what labour the apostle had,
to bring people into the faith in the new covenant and testament,
and from under the works of the law in the old covenant and testament,
and from under the curse.

And again the apostle saith, '`Before faith came, we were kept under the law,
shut up unto the faith, which should afterward be revealed;
even so when we were children, we were in bondage under the elements of the world.
But when the fulness of time was come, God sent forth his son, made of a woman,
made under the law, to redeem them that were under the law.`' Gal.
3d and 4th chapters.

So they that are redeemed from under the law, are redeemed from under bondage,
and outward elements of the world,
which elements of the world the law commanded to be observed:
for the law commanded the priests`' garments to be distinct from others.

And the law commanded an outward temple and tabernacle, and a worldly sanctuary,
and outward altars, and candles, and candlesticks, and outward days, and months,
and times, and years, and feasts, and outward trumpets were blown at such times;
and sacrifices, and offerings of beasts, and fowls, and other creatures.

And the law commanded the priests`' tithes and offerings, and the store-house:
and these outward things with many others, were elements of the world,
which kept them in bondage, in the old covenant and old testament,
before Christ was revealed.
And where faith is revealed by Jesus Christ, who is the author and finisher of it,
he is the end of that law to every one that believeth;
which law commanded these outward worldly elements; and such are not under the law,
but under grace.`' Rom. 6.

And here the new covenant and new testament,
and the new and living way is not according to the old testament and covenant.

For the new covenant and new testament is heavenly and spiritual.
And the law of life, that is in Christ Jesus,
is not according to the law received upon Mount Sinai,
which commanded all these outward elementary things to the Jews;
and they were to observe and do them.
And the law served until the seed came; which the seed Christ is come,
and hath abolished them all, and changed the law, and covenant, and priesthood,
and the old testament.

And they that are believers, are come into the new covenant of light, and life,
and grace; and do receive the spirit of Christ,
and the law of life that is in Christ Jesus,
that makes them free from the law of sin and death.

And so, as I said before, it is clear, that the new covenant and testament,
and the law of life are not according to the old covenant, and the old testament,
and the law from Mount Sinai, that was written in tables of stone.

And now also, are not the priests`' garments, their surplice, and white sleeves,
and their other distinguishing garments, a work of the law,
though they do not offer sacrifices and offerings,
as the outward old Jews`' priests did`'?

Likewise, are not tithes, tenths, first-fruits and offerings,
which were to be given to the priests, works of the law,
though now they do not do all the priests`' work under the law?
And some of the priests now have lots of the land also,
contrary to the law in the old covenant.

And is not setting up lights and candles in temples,
works of the law and the priests under the law,
though they do not burn incense like them?

And is not swearing truly by the Lord a work of the law, which the law commanded,
by which they ended the differences amongst men in the old time of the law?
And so none of these are works of the gospel, or works of faith,
in the time of the new testament and covenant, which prohibiteth all swearing, and saith,
'`Men must not swear at all, or take any oath; but their yea must be yea, and their nay,
nay, lest they go into evil,`' and so into condemnation.

And so the law commanded swearing; but the gospel,
and new covenant and testament commands every man to '`speak truth to his neighbour;`'
and in the mouth of two or three witnesses every word should be established.`'

And the apostles, in the gospel-time and new covenant, (to whom Christ said,
'`Freely you have received,
freely give,`') did not go in distinct garments from other people;
for Peter had his fisher`'s coat, after Christ was risen.
And Paul bid them bring his cloak, which he had left at Troas, etc.

So the apostle saith, and tells them plainly,
'`As many as are under the works of the law,
are under the curse.`' And if ye do some things of the law,
and not continue in all things '`written in the book of the law, ye are cursed;
and no man is justified by the law in the sight of God.
And the law is not of faith, which the just do live by;
for God doth justify the heathen through faith;`' and they
are justified by that faith which Christ is the author of:
'`For by the works of the law no flesh shall be justified.`' Gal. 2:10.

And the priests`' pulpits is a work of the law; for Ezra had his pulpit to read the law,
in the time of the law and old covenant.
And the tenths of the increase, with the tithes and offerings, were a work of the law,
and not a work of the gospel; for Christ said to his gospel ministers,
'`Freely you have received, freely give.`'

And to kill blasphemers and sabbath-breakers, and to stone them to death,
or put to death with outward weapons about religion, is a work of the law,
and not of the new covenant and new testament.
For Christ, though his name was blasphemed,
and the apostles and their doctrine and teaching blasphemed and evil spoken of; yet, he,
the King of kings, and Lord of lords, and his great apostles, did not command,
nor put any to death with any carnal weapons.
But Christ said, '`They that blasphemed against the son of man, it might be forgiven;
but they that did blaspheme against the Holy Ghost, were not to be forgiven,
neither in this world, nor in the world to come;`' which was punishment enough.
And further, be said in the new covenant and his gospel-day,
'`He came not to destroy men`'s lives, but to save them.`'

So all they that wrestle with flesh and blood, and with carnal weapons about religion,
it is a work of the law, and the old testament,
and not a work of the new testament and new covenant.

For the apostle said, '`Their warfare was spiritual, and their weapons were spiritual,
and not carnal;`' and they did not wrestle with flesh and blood,
but with spiritual wickedness, and rulers of darkness.

So the apostles were of faith, in the new covenant and testament, and not of the law,
wrestling with their works and weapons of the old testament.
And the law was added because of transgression, and served until the seed Christ came,
who redeems from under the law, Christ Jesus, by whom the world was made.
So he was before man fell into transgression, by reason of which the law was added,
which served until the seed came, which seed is Christ,
who doth fulfill the promises and the law,
and so redeems his people from under the works of the law, and from under the curse.

And the apostle saith, that '`the law is fulfilled in one word, even in this,
to love thy neighbour as thyself.
And if ye be led by the spirit of God, ye are not under the law,`' etc.
Gal. 5. '`For I through the law am dead to the law, that I might live unto God.`' Gal.
And they that love one another fulfill the law.`' Rom. 13.

And further the apostle saith, '`The righteousness of God is without the law,
being witnessed by the law and the prophets, even the righteousness of God,
which is by the faith of Christ Jesus, unto all and upon all that believe;
for there is no difference.`'

So this righteousness in the new testament is larger than the righteousness of the law,
which the Lord gave unto the Jews, which he had not given the like to other nations.
So this is larger than the old covenant.

And therefore the apostle concludes, '`that a man is justified by faith,
without the deeds of the law.`' Rom. 3.

'`For the promise that was to Abraham and his seed, that he should be heir of the world,
was not through the law,
but through the righteousness of faith,`' before he was circumcised,
and before he gave tithes to Melchizedec,
as in Gen. 12. where the Lord said to Abraham, '`I will make of thee a great nation;
and I will bless thee, and make thy name great, and thou shalt be blessed;
and I will bless them that bless thee, and curse him that curseth thee.
And in thee shall all the families of the earth be blessed.`' So before he was circumcised,
and before tithes were paid, the promise was to Abraham.
And so, who are of faith, are of Abraham, and walk in the steps of our father Abraham,
which he had, being yet uncircumcised, yea, and before he gave tithes to Melchizedec.
Gen. 12. and Rom. 4. '`Therefore it is of faith, and by grace,
to the end that the promise may be sure to all the
seed.`' And therefore the apostle saith,
'`But now are we delivered from the law, that being dead wherein we were held,
that we might serve God in the newness of the spirit,
and not in the oldness of the letter.`' Rom. 7. '`For what the law could not do,
in that it was weak through the flesh,
God sendeth forth his own son in likeness of sinful flesh,
and for sin condemned sin in the flesh,
that the righteousness of the law might he fulfilled in us, who walk not after the flesh,
but after the spirit.
For the law of the spirit of life in Christ Jesus,`' saith he,
'`hath made me free from the law of sin and death.`' Rom. 8.
For Christ is the end of the law for righteousness`' sake,
to every one that believeth.

Now, this was the law of works,
and the law of the old covenant and testament that Christ was the end of,
and which the apostle laboured to bring people out of, into the law of faith,
and law of love, in the new covenant and testament, and new and living way,
and to establish people upon Christ, the substance, who is the end of the law.
For the apostle saith, '`When the fulness of time +++[+++mark, the fulness of time]
was come, God sent forth his son, made of a woman, made under the law,
to redeem them that were under the law, that they might receive the adoption of sons.
And because ye are sons of God,
he hath sent forth the spirit of his son into your hearts, crying, Abba.
Father.`' So no more servants under the law, and old covenant and testament,
but sons in the new covenant and testament, and new and living way,
through the redemption in Christ Jesus,
and through his spirit that he hath sent into their hearts.

So here the new covenant and testament, and new and living way,
are not according to the old testament and covenant,
and the Jews`' way in their old time:
nor the old law from Mount Sinai is not according to the law of life,
which is in Christ Jesus.

And Moses was faithful in all his house, as a servant,
for a testimony of those things which were to be spoken after; that is, all these signs,
shadows, and figures.
But Christ, as a son over his own house, whose house we are, to wit,
in the new covenant and testament, and new and living way.
So Christ is over his house, the Jews in the spirit, in the new covenant and testament,
and new and living way; and they enjoy him, the substance, who makes all things new.

And Moses was faithful in all his house, in the old covenant and testament,
in the old time, over the outward Jews with the outward shadows and signs,
which were commanded by the law, and served until Christ the seed came; and when he came,
he abolished them.
So as Moses was to be heard in his house in the old covenant concerning his shadows,
figures, and signs; so Christ is to be heard in his house in the new covenant,
who is the substance, and abolishes all the figures and signs of the old covenant.
And God saith, '`This is my beloved son, hear ye him.`'

And the high priest, in the time of the law and old covenant,
once a year went with the blood of the clean beasts into the holy place,
which he offered for himself, and the sins of the people.
But Christ being come a high priest,
by his own blood he hath entered once into the holy place, to wit, heaven itself;
and hath obtained eternal redemption for us.

So the blood of the beasts cleansed from sin in the time of the old covenant and testament:
but in the time of the new covenant and testament the blood of Christ Jesus,
the lamb without blemish, cleanses us from all sin.

'`And Christ is the mediator of the new testament, by means of death,
for the redemption of the transgressions that were under the first testament,
that they which are called, might receive the promise of eternal inheritance.`' Heb. 9.

So, as the priest entered into the holy place made with hands,
with the blood of bulls and goats,
for the cleansing of himself and the people in the old testament and covenant,
which were figures.
But Christ in the new testament, is entered into heaven itself,
now to appear in the presence of God for us.

So all are to look unto Jesus in the new covenant and new testament,
which is not according to the old;
for in the old the people were to look unto the priest for their cleansing,
and to the outward blood and water, by which they were cleansed.
But in the new covenant and testament they are to look unto Christ Jesus, his blood,
his life, and unto the heavenly water of life, by which they are cleansed.

So the new covenant and new testament is not according to the old.
For Christ, the high priest in his new covenant and testament, and new and living way,
and in his new Jerusalem, and he, the offering, and his blood,
is not of the building of the old covenant and old testament, and old priesthood,
with their offerings of the outward blood of beasts,
and their cleansing with the outward water; I say,
Christ is of a far greater and more perfect tabernacle, etc. not made with hands,
than that outward tabernacle, which is built and made with hands.
So he is not of the old covenant and testament building.

And in the old covenant and testament, it was the old way to anoint the priests,
the prophets, and the kings, with outward oil.
But in the new covenant and new testament, and new and living way, Christ,
the great prophet and high priest, who is made higher than the heavens,
and the King of kings, God hath anointed him with the holy ghost,
and he doth anoint his Jews in the spirit,
and his true believers and followers with his spirit,
in his new covenant and new testament.
So the anointing in the new covenant and new testament, and new and living way,
is not according to the old.

For the apostle saith, '`He which establisheth us and you in Christ,
and hath anointed us, is God.`' 2 Cor. 1:21.

And so, the manner of the anointing is also different in the new covenant and testament,
and new and living way, from the manner of the anointing in the old covenant;
in which the prophets, priests, and levites, did anoint the prophets, and the priests,
and the kings.
But in the new covenant God and Christ anoints his people with his spirit,
which God hath poured out upon all flesh.
And so that outward anointing amongst the Jews in the old covenant,
Christ hath abolished, which was with outward oil.

And in the old covenant the Lord bid Moses,
'`Go and lead the outward Jews (which he brought out of Egypt)
unto the place which I have spoken of unto thee,`' etc.
But in the new covenant and testament the Lord saith, '`I have given thee for a witness,
and for a leader and commander to the people; and thou shalt call nations,
that knew not thee; and they shall run unto thee, because of the Lord thy God,
the holy One of Israel; for he hath glorified thee.`' Isa. 55.

So Moses was the leader of the outward Jews in the old covenant in his day,
with his types, figures, signs, and shadows; and the rock Christ followed them.
But in the new covenant and testament Christ is the leader and commander of his people;
and is the good shepherd, that hath laid down his life for his sheep,
and goes before them (who is the substance) and not after them,
as he did after the old Israel in their shadows.
And his sheep do know his voice in the new covenant,
and they do follow him into the pastures of life, that are always green;
and to the living springs, that are always fresh.

And Christ, the commander and leader of his people, his call is larger than Moses`'s;
'`For he shall call and lead nations, that knew not God,
and they shall follow him.`' So he not only calls and leads the Jews, but nations.

And so it is clear, that the new covenant and testament, new and living way,
is not according to the old in this also.

And in the old covenant they had carnal ordinances, and a worldly sanctuary,
though the sanctuary was called holy in its time; and all these meats, and drinks,
and sacrifices, and outward washings with outward water,
which were imposed upon them by carnal ordinances, until the time of reformation,
that is, until the time of Christ in his new covenant.
And the priests were made after the law of a carnal commandment,
and had their carnal storehouse, and carnal tithes and offerings; and so,
the carnal mind is death.
And so it is called, '`The ministration of death in the Old Testament,
written and engraver in stone.`' 2 Cor.
iii. and Rom. 8. and Heb. 7:9. But Christ, in his new covenant and testament,
'`is not made after the law of a carnal commandment,
but after the power of an endless life.`' Heb. 7:16.

And so his ordinances and commandments are spiritual;
and to be spiritually minded is life and peace.`' Rom. 8:6.

So all these carnal worldly things in the old covenant, and carnal ordinances,
and worldly sanctuary, and the law, which was after the law of a carnal commandment,
served until Christ the seed came, to reform them out of those carnal worldly things,
figures, signs, and shadows, into the spiritual things, and to Christ the substance.
For when the substance is come, the shadows fly away.
And so, the new covenant and new testament is not according to the old.

And in the old covenant and testament they had an outward ark,
and in it they had the pot of manna, and Aaron`'s rod that budded, and outward altars;
and in the ark they put the testament.
But Christ in his new covenant puts his testament, his spirit,
in the hearts of his people; and the altar is spiritual,
upon which the saints do offer up their spiritual sacrifices;
and they have their heavenly bread in their hearts, which gives them life.
For they that eat of the manna, died in the wilderness;
but they that eat of this heavenly bread, it gives them life eternal.

And as Aaron`'s priesthood was tried by the budding of his rod in the ark,
when all the rest of the outward rods, that were laid in the ark with his, did not.
So are Christ`'s ministers, in the new covenant,
by the budding of the spiritual rod in their tabernacle,
and bringing forth spiritual fruits; which spirit God hath poured upon all flesh;
which fruits of the spirit they bring forth,
and that which they have profited by the spirit, they come to minister.

So the new covenant is not according to the old, with its outward rod, testament,
and manna, outward tabernacle and altar;
for all these outward things served but till the time of reformation,
till the seed Christ, the heavenly and spiritual man, came, in his new covenant of light,
life and grace, who puts the heavenly testimony,
and heavenly manna and rod in the heavenly ark, the sanctified hearts,
and who offer up the spiritual sacrifices upon the spiritual altar.
And Christ abolishes all those outward things, with the old covenant and testament,
and establishes the new.

And in the old covenant the priests, which were made by the law of a carnal commandment,
were to burn incense at the outward temple at Jerusalem,
and there they were to do it by course, and served in their course.

But in the new covenant and testament the Lord saith, '`From the rising of the sun,
even to the going down of the same, my name shall be great among the Gentiles,
and in every place incense shall be offered unto my name, and a pure offering;
for my name shall be great among the heathen, saith the Lord of hosts.`' Mal. 1:11.

So this pure offering and incense, which should be offered unto God in every place,
is by and in his pure spirit to the pure God,
the Lord of the hosts of the Jews in the spirit; yea, and the Gentiles also.

So likewise in this, the new covenant is not according to the old, but is larger.
For in the old covenant the priests by turns were
to burn outward incense only in one outward temple.
But in the new covenant all the believers in Christ Jesus
are to offer spiritual incense in every temple and place,
in the new covenant and testament, and new and living way;
for Christ abolishes and puts out, and to an end,
the outward fires of the outward incense, and tabernacle, and temple, and sanctuary,
those outward worldly things,
which served until the time of reformation by Christ the seed.
And so the new covenant is not according to the old;
for the one was of natural and outward things, and the other of inward and spiritual.

And God sent Moses to lead the people out of outward Egypt;
and they did not come out from outward Egypt till Pharaoh`'s first-born was slain.
And they had light in Goshen, before they came out,
though darkness was over the land of Egypt.
But Christ in his new covenant leads his Jews in spirit out of spiritual Egypt and Sodom;
and they have light in their Goshen before they come out,
though spiritual darkness be in spiritual Egypt.
And the first birth of the spiritual Pharaoh must be slain,
before the Jew inward comes out of the spiritual house of bondage and darkness within,
and to follow Christ, the captain of their salvation,
in his new testament and new covenant, and new and living way;
and so to worship God in his holy spirit, and in his truth, that the devil is put of.

So outward Pharaoh oppressed the outward Jews;
and spiritual Pharaoh oppresses the spiritual Jews, and will not let them go forth,
till the first and spiritual birth of him be slain.

And the Jews, when they received the law in the old covenant from Mount Sinai,
they were to wash their clothes, as they were commanded by the Lord,
and Moses was to sanctify them.
Ex. 19. But in the new covenant all that receive the law of life,
which is in Christ Jesus, from Mount Zion, Christ doth sanctify them,
and they are to wash their hearts, souls, spirits, and minds,
with the heavenly water of the word; and the blood of Jesus cleanses them.

And the priests sprinkled the people with the blood,
which is the life of the clean beasts, in the old covenant.
But Christ in his new covenant and testament sprinkles his precious blood
(which is his life) upon the hearts and consciences of his people,
by which they are made clean.
And the priest made atonement with the blood of the clean beasts,
for the sins of himself and the people;
but Christ with his blood hath made atonement to God for the sins of his people.
So the blood and the priest of the new covenant are contrary to the old, and exceed it.
For they offered up the blood of the beasts, and he offered up his own blood, his life,
for his people.

And so the new covenant and testament is not according to the old;
for Christ abolisheth all those outward washings and offerings,
and the law that commanded them.

And in the old covenant and testament the priests were to wear the outward fine linen,
and the high priest the urim and thummim written upon his breast,
which signifies light and perfection: but in the new covenant and testament,
Christ is the light himself,
and the perfection of all those outward things in the old covenant,
and the substance of them all.
And the righteousness of Christ is the fine linen, which will never dirt nor wax old;
which all Christ`'s believers in his new covenant and testament wear;
and they need not wash this fine linen, which all the believers that wear it,
are the royal priesthood, and offer up the spiritual sacrifices.
And as the priests in the old covenant were to wash their outward fine linen,
which outward fine linen Christ doth abolish, and the priests and their garments,
and the wearing of the urim and thummim upon their breasts in the old covenant;
and sets up his righteousness in the new covenant, for his royal priesthood to wear,
and light and perfection in their hearts.
And so, in this, also, the new covenant is not according to the old.

And all the unclean, in the old covenant, were to be put out of the outward camp,
and they were to dwell alone; and without the camp was their habitation to be.
Lev. 12. and Dent.
xxiii.
The unclean were to go out of the camp;
and they were to wash themselves with outward water, and to be clean,
before they were to come into the camp again; yea,
when they did go forth to ease themselves, they were to go forth without the camp,
and cover it with a paddle.
So the camp of the outward Jews was to be holy, in the old covenant;
for the Lord God said, '`He would walk in the midst of the camp to deliver them.`' Dent.
Xxii.

Therefore, if the Jews, in the old covenant and in these outward things,
were to be so holy, and all uncleanness kept out of it;
and their excrements were to be covered without the camp,
that the Lord might walk amongst them, in their figures, signs, and shadows,
which served till the seed Christ, came, the time of reformation,
in the new covenant of grace and light, which is not according to the old;
then much more the camp of the new covenant and testament must be kept clean;
and all their uncleanness must be done away, and buried with a spiritual instrument,
without the camp.
For the habitation of all the unclean is without the camp of God and Christ,
and his new covenant; and they cannot come into his holy camp and city,
until they be washed with the pure blood of Christ and the holy water of life.

And in the time of the old covenant,
the Jews were not to offer any thing to the Lord that was blind or lame,
or that was blemished, in their sacrifices.
Duet. 25. and Lev. 22:21. '`There shall be
no blemish in that which they offer unto the Lord;
neither shall it be broken, or blind, or maimed, nor have a wen or scab,
etc. or any thing superfluous, or lacking any of his parts, or that was crushed,
or bruised, or cut; they were not to offer any such things in all the land to the Lord,
but what was whole and clean, and without blemish: which was a type of Christ,
who was clean and whole, and had all his parts, and not broken,
but was a lamb without blemish, who, to establish the new covenant,
offered up himself once for all these offerings in the old covenant.
So he is both the peace offering and thanksgiving offering,
and the offering also for the sins of the whole world,
who abolished all the offerings of the old covenant, and ended them;
and consumes all the false offerings, with their fat, in his fiery baptism.

And so, the lame, blind, blemished, broken, scurvy, scabbed offerings,
were not accepted of God in the old testament and old covenant;
and much less are they accepted in the new covenant of grace, light, and life;
for in the new covenant,
the children of the covenant of grace offer spiritual sacrifices.

So it is clear here, the new covenant and testament is not according to the old.

And whosoever of the seed of Aaron had any blemish,
was not to offer the bread of his God in the old covenant and testament;
and what man soever hath a blemish, he shall not approach.
A man that is blind or lame, or scabbed, crushed, broken foot or hand, or crooked back,
or a dwarf, or that hath a blemish in his eye, or scurvy, or hath his stones broken,
or any superfluity, or hath any blemish, of the seed of Aaron the priest,
he shall not come nigh the offerings of the Lord.
Nay, the priests were not to drink wine or strong drink,
when they went into the tabernacle to offer.
So perfect, whole, clean, and clear, without blemish,
they were to be in the old covenant, that offered those outward things,
in the outward tabernacle or temple.
Then much more perfect, and more clean and clear, is Christ Jesus, the high priest,
who offered up himself to God, without spot or blemish, for the sins of the whole world,
and gave his holy flesh for the life of the whole world,
and who abolished all those offerers and offerings in the old covenant.

And therefore all his believers, in the new covenant and testament,
which are called a royal priesthood,
must be much more clean and holy than they were in the old covenant and law of works,
they that be in the new covenant of grace, and without blemish.
For as Peter saith, '`Christ, the Lamb of God, who offered up himself,
is without spot or blemish;`' and he sanctifies and cleanses, and washes his church,
his people, with the water of the word,
`'that he might present to himself a glorious church, without spot or wrinkle,
or any such thing, but that it should be holy and without blemish.`' Eph. 5.

So he cleanses away the inward brokenness, crookedness, scurviness, scabbedness,
blindness, deformities, lameness, and blemishes, that all the believers in the light,
which is the life in Christ, might offer their spiritual sacrifices unto God.
And so the children of the new covenant are called a holy nation, a royal priesthood,
and do exalt Christ the substance, who hath abolished the old priesthood,
and his offerings in the old covenant,
which are not according to the new covenant and testament.

And there were to be no drinkers of wine nor strong drink,
when they were to approach before God in the old covenant;
and drunken priests were forbidden in the time of the law and old covenant,
much more in the time of the gospel.

For whatsoever was blemished or evil-favoured,
was not to be offered to the Lord in the old covenant.
But in the new covenant, which is not according to the old,
all that are the followers of Christ, who brings them up into the image of God,
and the believers in the light, which is the life in him,
and are called the children of light, and are born of God,
and have passed from the death that blemishes them, and made them ill-favoured,
and crooked, and scabbed, and blind, etc.:
all these that are born of God and children of light, are very well favoured, like God,
their Father, and he doth accept their spiritual offerings and sacrifices,
and them also whom Christ doth present to God in the new covenant and testament,
and new and living way, which is not according to the old testament and old covenant,
the Jews`' old way; for the one was outward, and the other inward; the one was carnal,
(viz. in carnal ordinances,) and the other spiritual.

And the Jews in the old covenant and testament,
they were to eat only of the clean fowls and clean beasts;
and they were to put a difference between the clean and unclean beasts and fowls;
and that which died of itself, or was torn, they were not to eat,
nor to defile themselves withal.
Lev. 22. '`For ye shall be holy unto me, saith the Lord;
ye shall not eat flesh that is torn of the beast of the field;
ye shall cast it unto the dogs.`' Ex. 22. And Aaron and his sons, the priests,
were to eat part of the sacrifice of the clean beasts in the holy place,
Lev. 10. that was, in the temple or tabernacle.

Now all these outward clean creatures, and they that eat of them, were to be clean also;
for the priests were to be sanctified and cleansed before they eat of the sacrifice.
I say, all these clean meats and offerings were a type of Christ Jesus, the offering,
and of the heavenly clean food, that the children of the new covenant feed upon;
for they were not to feed upon such outward things, as were torn or died of themselves;
for they were dogs`' meat in the old covenant.
But in the new covenant, which is not according to the old,
all the creatures of God are clean unto them, and every creature of God is good,
and they cannot feed upon any thing that is torn, nor that which dies of itself.
I say, they cannot inwardly feed their souls with it;
but their food is that which is living, and from him that is living,
who did not die of himself, and is living, and dieth no more;
and the spiritual food and things are not torn things, and do not die,
which the Jews in the spirit feed upon.

So the new covenant and testament is not according to the old;
for the Jews in the old covenant fed upon outward things, and upon that which was clean;
and the priests were to eat part of the sacrifices in a clean place, in the temple.
But the Jews in spirit and new covenant,
unto them every creature of God is good and clean, and their food is spiritual,
and they eat of the sacrifice Christ Jesus, their bread from heaven,
all the royal priesthood of God in his new covenant
eat of it in the clean temple and tabernacle,
their hearts, of the clean heavenly food.
So the new testament is not according to the old.

And the Jews had a high priest over the rest of the
priests in the old testament and covenant,
which could not continue by reason of death, but when one was deceased,
they got another to offer their sacrifice, and he had the tenth of the tenths.

But Christ is the high priest in the new covenant,
who hath offered up himself once for all the offerings of the priests in the old covenant;
and so hath tasted death for every man, and is risen, and remains a priest forever,
and dieth no more; and is a high priest in his new testament and new covenant,
and makes all his believers priests and kings to reign upon earth, and over the serpent,
whose head he hath bruised.
Glory to God forever.

So our high priest is not according to the old,
and his followers are not according to the old priests`' followers;
for they are all spiritually minded,
and the spiritual cannot feed upon that which is torn or dies of itself, nor offer it,
but upon that which is living, and holy, and heavenly, and spiritual in the new covenant;
for that which dieth of itself, or is torn, is not spiritual, but carnal,
and the royal clean priests in the new covenant cannot feed thereon.

And all the Jews in the old covenant and testament, the Lord said unto them,
'`Ye shall sanctify yourselves, and ye shall be holy; for I am holy, saith the Lord,
and ye shall be holy men unto me.`' Ex. 22.

So they did sanctify themselves, and wash themselves with outward water,
and the blood of the outward clean beasts was sprinkled upon them;
and Aaron the high priest was to bear the iniquity of the holy things,
after that he was sanctified, which the children of Israel had hallowed,
and all their holy gifts. Ex. 28:38.
And Aaron and his sons were to eat the sin offering,
and to bear the iniquity of the congregation,
and to make an atonement for them before the Lord.
Lev. 10. And the priests`' garments were all to be holy, and the temple,
and tabernacle, and sanctuary were all called holy in the old covenant.

But the new covenant is not according to the old;
for Christ in the new covenant he bears the iniquity and sins of the whole world,
and was wounded for its transgressions, and bruised for iniquities,
and the chastisement of our peace was laid upon him; he hath borne our griefs,
and with his stripes we are healed,
and the Lord hath laid upon him the iniquities of us all;
whose soul was made an offering for sin, who saw the travails of his soul,
and was satisfied.
Isa. 55.

So he abolisheth all those outward holy garments, and tabernacle, and temple,
and offerings, and gifts, which were called holy in the old covenant,
but worldly in the new covenant.

So it is Christ, '`whom God the Father hath sanctified,
and sent into the world,`' John 10. that makes an end of sin,
and finishes transgression in his new covenant, who through death destroys death,
and the devil, who had the power of death, that made man and woman unholy.
And it is Christ Jesus that makes all things holy and new,
and sanctifies all things by his word, and all his gifts are holy;
who changes the first priesthood with all the outward things,
which were called holy in the old testament,
which were figures of the holy spiritual things in the new testament,
and the spiritual sanctuary, temple, and tabernacle, in the new covenant and testament.
All the Jews in the spirit feed upon Christ, their sacrifice,
which he gives for the life of the world; and so eat the bread from heaven,
in the holy and heavenly sanctuary, tabernacle, and temple,
that are not of the old covenant`'s building.

So Christ in his new covenant and testament,
the high priest made higher than the heavens,
in offering up himself once for the sins of the whole world,
is not according to the Jews`' high priests, and their offerings,
but doth put an end to them all, and abolisheth them all,
and establishes his new testament in the spirit, and new covenant of light,
life and grace.
I say, Christ, the high priest who was dead, and died for man,
to fetch man out of death to life, and to destroy him that kept him in death,
is alive again, and lives forevermore,
and is a high priest forever amongst all his royal priesthood,
and reigns in his holy sanctuary, tabernacle, and temple of the sanctified hearts.

And the Jews in the old covenant and testament, they were not to touch any unclean thing,
or creature, or unclean fowl, or beast, or creeping things that were outward; no,
not to touch any vessel where any of those unclean things were in; if they did,
they were to wash themselves with outward water.
Lev. 11. And likewise, they were not to come nigh, nor touch the dead; if they did,
they were unclean, and they were to sanctify and wash themselves with outward water, etc.

Now the new covenant is not according to the old, which saith,
'`Every creature of God is good.`' And God and Christ hath sanctified every creature;
as Peter preached it from a voice he heard from heaven, when he saw four-footed beasts,
and wild beasts, and creeping things let down from heaven, in his vision,
which he was to kill and eat;
and they were not to be called common nor unclean in the new covenant.
For everything that God had made was sanctified by the word,
by which all things in the beginning were made good, yea, very good.

And so in this the new covenant and testament, and new and living way,
are not according to the old.

And as they in the old covenant were not to touch the dead, nor the unclean creatures,
so the Jews in the spirit are not to touch the unclean creeping spirits,
which are like beasts and ravenous fowls.
And those are the unclean spirits which the apostles would not have the saints to touch;
for if they did, they must he washed with heavenly water, and the blood of Jesus,
before they can be cleansed.
And for eating, or touching of outward creatures, he told the saints in the new covenant,
that whatsoever was sold in the shambles, that they might eat.`'

And though it was the doctrine of the law in the
old covenant to forbid several sorts of meat to eat;
but in the new covenant it is the doctrine of devils to forbid meats and marriages,
or to command to abstain from them, which God hath created,
to be received with thanksgiving,
by them that receive the doctrine of Christ Jesus in his new covenant and testament.
'`For every creature of God is good, and nothing is to be refused,
if it be received with thanksgiving; for it is sanctified by the word of God,
and prayer.`' 1 Tim. 4:4.

So here it is clear, the new covenant and testament is not according to the old.

And in the old covenant, when the outward Jews went to wars with their carnal weapons,
and took any prize, everything that could abide the fire,
must go through the outward fire,
and that was to cleanse it and purify it with the outward water and fire;
and they were to abide seven days out of the camp, and to wash their clothes,
before they came in again into the camp.
Num. 31.

But in the new covenant, which is not according to the old,
everything must be washed with the water of life, and cleansed by Christ,
and come through his fiery baptism, before they can come into his treasure, and camp,
and city, and be perfect.
For the seven days that were to pass upon them in the old covenant,
was the perfection of days.
And that was outward fire and water, that was to cleanse and purify the Jews,
and those outward things;
but all the believers in the light must be washed with the heavenly water,
and purified with heavenly fire, and the blood of Jesus Christ,
before they can come into his heavenly camp.

And in the old covenant and testament, Ruben, Gad, and Asher, Zebulon, Dan, and Naphtali,
these were to stand up upon Mount Ebal, and to curse the disobedient;
and others were to stand up and bless the obedient.
Dent.
xxvii.

But in the new covenant and new testament, which is not according to the old,
Christ saith, '`Love your enemies, and bless them that curse you,
and do good to them that hate you, and pray for them that despitefully use you,
and persecute you, that you may be the children of your father that is in heaven:
for he makes the sun to rise on the evil and the good, and sends his rain on the unjust,
as well as the just.`' Matt. 5.

And this is Christ`'s doctrine in the new covenant.
And the apostle saith, '`Being reviled we bless; being persecuted we rejoice.`' 1 Cor.
iv.

And again the apostle saith, '`Bless them which persecute you; bless,
and curse not.`' So though they were to bless and curse in the old covenant;
yet in the new covenant they are to bless, and not curse, as in Rom. 12:14.

And so here it is clear,
the practice of the new covenant and testament is not according to the old.

And in the old covenant it is said, '`An eye for an eye,
and a tooth for a tooth.`' But Christ in his new covenant and testament saith,
'`Whosoever smites thee on the one cheek,
turn to him the other also.`' So here the new covenant`'s
practice is not according to the old.

And you have heard say in the old covenant and testament, and that old time,
'`Thou shalt not commit adultery.`' But Christ in
the new covenant and new testament saith,
'`Whosoever looks after a woman to lust after her,
hath committed adultery already in his heart.`' So the righteousness
and holiness of the new covenant doth exceed the old.

And in the old covenant, '`whosoever put away his wife,
was to give her a bill of divorcement,`' etc.
But Christ in his new covenant saith, '`Whosoever putteth away his wife,
save for the cause of fornication, and marrieth another, committeth adultery;
and whosoever marrieth her that is put away from her husband,
committeth adultery also.`' Luke 16. and Matt. 5.

So here the new covenant is not according to the old;
and the righteousness of the law of life doth exceed
the righteousness of works in the old law.

And in the old time it was said, '`Thou shalt love thy neighbour,
and hate thine enemy.`' But in the new covenant, which is not according to the old,
it is said, '`Thou shalt love thine enemies, and pray for them,
and do good for them that hate you.`'

So though the old covenant taught humanity,
yet the new covenant teaches not only natural humanity, but heavenly humanity, divinity,
and christianity.

And in the old covenant and testament the Jews were to keep the year of jubilee,
which was the fiftieth year; and therein they were to proclaim liberty with trumpets,
throughout all the land.
And this year of jubilee was to be holy unto all the Jews;
and in the year of jubilee the servants went out free,
and therein was a redemption of lands and houses, and bondmen, and servants,
which were of the children of Israel.
Lev. 25.

And now this was an outward freedom and liberty in the old covenant;
and this outward year was holy, and it was proclaimed with outward trumpets.
But in the new covenant and new testament, the year of jubilee is proclaimed,
blown and sounded with the spiritual gospel trumpets, throughout all the world,
and unto every creature under heaven, unto bond and free, without respect; yea,
eternal liberty in the gospel of Christ Jesus, the heavenly man, the power of God,
and in the light, which is the life in him; and in the grace,
which hath appeared unto all men, which brings their salvation;
and in the spirit which is poured out upon all flesh,
that by the spirit all flesh might see the glory of God, and Christ their salvation,
who redeems them, and pays all their debts of sin; who was made sin that knew none,
and so made it to be his; and so died for the sins of the whole world and the ungodly,
to redeem them out of the sin, and ungodliness, and bondage, and captivity, yea,
to set all the prisoners and captives at liberty, and to make the blind to see,
by opening their eyes; and heals the leper, cripple, and the sick,
and looses the tongue of the dumb.
Here is the year of jubilee, the everlasting holy year, or day of Christ,
who destroys the devil and his works, that hath made man and woman unholy,
and kept them in bondage and slavery.
And so Christ brings all his believers into his glorious liberty of the sons of God,
and to an eternal redemption; yea,
he takes off and destroys that which hath brought the oppression upon the creation.
So an everlasting jubilee in the new covenant, and new testament, and new and living way,
which doth far exceed the Jews`' outward year of jubilee,
which was only to that particular nation.
But Christ`'s jubilee of his everlasting gospel is
to all nations to whom the gospel is preached,
and liberty unto every creature under heaven, by his spiritual and gospel trumpets,
which are blown and sounded by his light, and power, and spirit, and faith,
in all nations, of their spiritual liberty and freedom in the land of the living, yea,
a liberty both inwardly and outwardly; and he that believeth in the light,
which is the life in Christ, is saved; and he that doth not, is condemned.

And this gospel trumpet, which sounds into all nations, and into all countries,
for their liberty, and salvation, and freedom,
proclaims forgiveness and redemption to men, if they will believe it,
and come out of thraldom and captivity; and he that believes it is saved,
and hath the comfort of the salvation and liberty;
and he that will not believe it is condemned, and lies under condemnation.
And so in this, the new Covenant and new testament is not according to the old;
for this liberty and jubilee is to all nations,
but in the old covenant it was but to the particular nation of the Jews.

And in the old covenant, the sons of Aaron shall blow with the trumpets;
and this was an ordinance to the priests; and when they blew the trumpets,
the outward Jews were to assemble themselves before the tabernacle.
And when they blew an alarm, then the camp set forward.
Num. 10. So they did not gather them together to
the door of the tabernacle with ringing of bells,
in the old covenant, but with the blowing of trumpets.
And at the solemn feasts they blew the trumpets; which was a day of blowing the trumpets,
which were outward, in their outward feasts,
to their outward gathering to their outward tabernacle.
But in the new covenant and testament, which is not according to the old,
the trumpets are spiritual and heavenly,
which are sounded with the power and spirit of God, in the day of Christ; yea,
all his believers in his light, the life in him, are a royal priesthood,
and blow the trumpet.
And at the sound of this heavenly trumpet, they gather to this heavenly tabernacle,
not made with hands, and to the heavenly Jerusalem, to his heavenly solemn feast,
through the baptism of Christ and circumcision with his spirit,
that plunges down and cuts off all corruptions; and so all come to drink into one spirit,
that put off the body of death and sins of the flesh,
that are gotten up upon man and woman by transgression;
for Adam and Eve had it not before they transgressed the command of God.

And so by these spiritual and heavenly trumpets, ye are gathered to the heavenly feast,
and bread, and wine, and honey, from heaven, and the new milk from the living word,
that lives and abides, whose heavenly breast is never dry,
but is always full of heavenly milk.
And so as the heavenly trumpet sounds, the Jews in spirit move and go,
and follow the heavenly spiritual Lamb in their fine linen, his righteousness,
and keep their feast of the heavenly bread, that cannot be leavened.
So the bread, the wine, the milk, the honey, the water, the trumpets, and the tabernacle,
are heavenly and spiritual in the new covenant and testament,
which are not according to the old, with their outward bread, and water, and trumpets,
and outward tabernacle.
All those outward things Christ abolished,
which served but till the seed came to reform it;
and in the time of the reformation of Christ, the heavenly and spiritual man,
he reforms his believers and followers out of the natural, outward, and carnal,
into the heavenly, inward, and spiritual.
And so the new and living way, and the new covenant and testament,
and the new time of reformation,
are not according to the Jews`' old covenant and testament, and old time and way.

And the outward kingdom among the Jews in the old covenant and testament, Christ,
in his everlasting kingdom, in his new covenant and new testament, doth exceed it.
And they were commanded to an outward cleanness in that outward kingdom,
with the outward cleansing by the blood of beasts, etc.
And when they did transgress the outward law of God in their outward kingdoms,
they were carried away captives.
But Christ`'s kingdom is an everlasting kingdom, and is holy and pure,
and none that are defiled enter into it;
for it stands in power and joy in the holy ghost.
And all must be born again before they can either see the kingdom of Christ,
or enter into it.
And Christ saith, '`The law and the prophets were until John,
(which was the forerunner of Christ,
and the preparer of the way,) but the least in the kingdom of God is greater
than John.`' '`And from the days of John Baptist until now,
the kingdom of heaven suffereth violence,`' saith Christ, and men press into it.
`'And Christ said unto his disciples,
it was given unto them to know the mysteries of the kingdom of God,`' etc.
And John, when he wrote unto the seven churches, said,
'`he was their brother and companion in tribulation,
and in the kingdom and patience of Jesus Christ.`'
Rev. 1. And Christ sent forth his disciples,
and bid them '`Go, and say, repent,
for the kingdom of God is at hand.`' And they preached the kingdom of God; yea, Paul did,
at Rome, to all that came unto him.
And Christ saith, '`Not every one that saith Lord, Lord,
shall enter into the kingdom of God; but he that doth the will of my Father,
which is in heaven.`' And they were to seek the kingdom of God,
and the righteousness of it,
and then all those outward things (which the Gentiles
did seek after) should be added unto them.
And Christ saith to his followers, in his new covenant and new testament,
and new and living way,
'`that except their righteousness do exceed the righteousness of the Scribes and Pharisees,
they shall in nowise enter into the kingdom of heaven.`'
And therefore the christians in the new covenant,
their inward and outward holiness, and righteousness, and godliness, and virtue,
and temperance, and patience, and love,
must exceed all the outward righteousness and holiness in
the old testament and covenant of the Jews and priests,
and Scribes and Pharisees, else they cannot enter into the kingdom of God.

And so it is clear, that the new covenant and new testament, and the new and living way,
and the kingdom of Christ, and his righteousness,
exceed the Jews`' in the old covenant and testament, and their old way;
which kingdom is an everlasting established kingdom,
and no unclean thing can come into it; and it stands in power and joy in the holy ghost.

And all the believers in the light, which is the life in Christ, are born, again,
and enter into his kingdom, and are heirs of it; so heirs of an everlasting inheritance.

And Aaron, he and his company, in the old covenant and testament,
were to look to the candlesticks, and to look to the seven lamps, a perfect number,
as you may see in Num. 8. and Lev. 24. and Ex. 40:
and Ex. 24. And this they were to do throughout their generations.
And so Aaron was to order the lamps, evening and morning,
which were to burn continually without the veil of
the testimony in the tabernacle of the congregation.
Lev. 24.

And these outward things served till the seed Christ came in his new testament,
and in his new covenant, who abolished all those outward candlesticks, lamps,
and lights in the outward Jews`' generation, and the priesthood also.
And in the generation of Christ in the new covenant, his believers,
that are gathered in his name, which are passed from death to life, which are his church,
doth not he call them candlesticks?
For in the revelations he calls the seven churches, or seven congregations,
which are a perfect number, seven golden candlesticks.`' And Christ, the high priest,
doth enlighten the candle, which is the spirit of man, in the candlestick.
And these congregations of people are them that he sanctifieth in body, soul, and spirit.
And Christ walks in the midst of these '`seven golden
candlesticks,`' in his heavenly fine linen,
and heavenly golden girdle; and his hair as white as wool and snow,
and his eyes like a flame of fire, and his feet like fine brass,
as if they were burning in a furnace; and out of his mouth went a sharp two edged sword;
and his countenance was as the sun shining in his strength.
So here Christ, in his new testament and new covenant of light, life, and grace,
is not according to the old, but doth exceed in glory.
Rev. 1.

And the Jews, in the old covenant, the priests,
before they did offer to God the outward sacrifice, they were to be sanctified;
which outward sacrifice was to be holy.
But the Jews in spirit, in the new covenant, which is not according to the old,
they are sanctified by Christ, and made clean by his blood and heavenly water;
and he is their sanctification.
And then all the sanctified believers are a royal priesthood,
and they offer up spiritual sacrifices, and the spiritual sacrifices are holy.
So the sanctifier and offering in the new covenant, and that which doth sanctify,
are not according to the old.
And therefore, Christ abolisheth the old covenant,
and all its ways of sanctifying with the blood of creatures, which was their life; for,
Christ sanctifies in his new covenant with his own blood, his life, and makes all clean;
and destroys him that made man and woman unclean;
and renews man and woman up into the image of God, which they were in before they fell;
and makes them as clean again as God made them, and brings them up into himself,
who is first and last, that never fell.
So that they are built upon him, the living rock and foundation, and grafted into him,
and he, the root, bears them.
And here they, with their spiritual, heavenly trumpets,
sound forth to the praise and glory of God, and bring forth fruits to his praise.

And the apostle, in the new covenant said,
that God had made them able ministers of the new testament, not of the letter;
for the letter of the old testament killed,
but the spirit of the new testament giveth life.`' And farther he saith,
'`If the ministration of death, written and engraven in stones, was glorious in its time,
so that the children of Israel could not steadfastly behold the face of Moses,
for the glory of his countenance; which glory,`' saith the apostle,
'`was to be done away.`' Which is done away by Christ in the new covenant and testament.
And therefore, the ministration of the spirit in the new covenant and testament,
and new and-living way, is more glorious:
for if the ministration of condemnation be glorious,
which was the ministration of the old testament and covenant,
then how much more doth the ministration of righteousness
in the new covenant exceed it in glory?
For that which made glorious in the old testament, had no glory in this respect,
by reason of the glory of that which excels it in the new covenant;
for if that which was done away was glorious, much more that which remains is glorious.
For Moses put a veil over his face,
that the children of Israel could not steadfastly look to the end of that which is abolished,
to wit, the old covenant and the veil,
which the apostle witnessed were abolished then in his day;
but their minds were blinded so that they did not see it.
For until this day remains the same veil,
untaken away in the reading of the old testament, which veil is done away in Christ.

'`But even till this day, when Moses is read,
the veil is over their hearts,`' saith the apostle, to wit,
the Jews and other Jewish minded people; for while Moses is read,
and in reading the old testament, it keeps the veil upon them;
then what do they that not only read it, but practise many things in the old testament,
and yet will be called christians of the new covenant?
But doth not the apostle tell you,
'`The veil is over their hearts when Moses is read?`' And the old testament and
veil are done away by Christ in his new testament and new covenant of light,
life, and grace.
And they that do not believe it, the veil is over them, and their glory is no glory;
and they are under the ministration of death and condemnation,
and not under the ministration of the new testament of life;
for the veil remains untaken away in reading of the old testament.
'`And even to this day, whilst Moses is read,
the veil is over their hearts,`' as the apostle saith.

And now, you called christians,
is not '`swearing truly by the Lord and performing the oath unto the Lord,
for the ending the strife among men,`' is not this in the ministration of Moses?
is not this your practice?
and did not Moses command it by the law in the old covenant?
And are not outward temples and pulpits, Moses and the old testament?
And are not tithes, and offerings, and first fruits, Moses`' veil and the old testament?
And is not the observing of days and months, and the passover,
which you call the time of Easter, and your Pentecost, or Whitsuntide, as you call it,
Moses and the old testament?
And is not calling of your days, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday,
Sunday, etc. and your calling the months by the names of May, June, July, August,
etc. which is neither from Moses nor Christ, but from the heathen,
which your practice herein is not according to the old covenant nor the new?
And are not the sabbath, and the priests`' surplice and white sleeves,
and the change of garments to differ them from other people, Moses and the old testament,
and not the new testament and covenant?
And are not outward altars, and candlesticks, and sanctuaries,
and outward candles burning in your temples, Moses and the old testament?
And whilst ye read and do all these things, doth not the apostle tell you,
'`the veil is over your hearts?`' For doth not the apostle tell you,
that Christ hath abolished Moses`' old testament, and hath taken off his veil,
and made his glory no glory,
because the glory of the new covenant and testament hath dimmed it,
and done away the glory of the old?

And therefore, are not you under the veil, with your tenths, and tithes, and offerings,
and candles, and candlesticks, in your temples, and altars,
and outward places of worship, with your priests`' distinguishing garments,
and your feasts, and observing of days and times,
and swearing to end strife and controversy amongst you?
Is not this Moses and the old testament, and reading the old testament,
and not the new testament and new covenant, which saith, '`Swear not at all,
but let your communication be yea, yea, nay,
nay?`' And Christ`'s righteousness is all the believers`' fine linen,
which are the children of the new covenant, and of the light,
and their altar is spiritual; and Christ hath enlightened their candle, their spirits,
with the light, which is the life in him; which burns in their temple night and day.
And so Christ, in his glorious new testament and new covenant,
he hath done away and abolished the first priesthood, with his garments, and offerings,
and his outward lights, and altars, and feasts, and days, and carnal sanctuary,
and oaths, and tithes.
And they are blind as the Jews,
that see him not come in his new covenant to abolish all those things of the old;
who saith, in his new covenant, to his disciples and followers,
'`Freely ye have received, freely give.`'

And so it is clear, that the new covenant and testament, and new and living way,
are not according to the old; and as people do, turn to the Lord by his light, grace,
and, truth, and spirit, and gospel, to Christ in his new testament and covenant of light,
life, and grace, the veil will be done away off the old covenant,
and Moses from off their hearts,
that they may come to read in the new covenant and testament.
And such as are in the new covenant and testament, they '`are manifestly declared to,
be the epistles of Christ, written not with ink, but with the spirit of the living God;
not in the tables of stone,`' as it was in the old testament and covenant,
'`but in the fleshly tables of their hearts.`' Now the Lord is that spirit,
and where the spirit of the Lord is, there is liberty.
'`But we all,`' saith the apostle, '`with open face (to wit,
in the new covenant and testament,) beholding as in a glass the glory of the Lord,
(a glorious beholding,) and are changed into the same image, from glory to glory,
even by the spirit of the Lord.`' A blessed glorious change into a glorious image.

And this is the glorious happiness and comfort,
that all the children of the Lord in the new covenant and testament,
and new and living way, did and do enjoy,
which doth exceed the old covenant and testament, and old way in its glory,
which is done away and abolished by Christ Jesus.
So he hath taken away the first and established the second,
who walks in the midst of his heavenly golden candlesticks,
and is the head of his holy sanctified church, and is alive,
and '`lives forevermore,`' who is worthy to have glory and honour,`'
the lamb that hath been slain from the foundation of the world,
who is razing down all the world`'s foundations, and he himself is the only holy,
spiritual, safe, sure rock and foundation for his believers,
which are living stones to build upon, who was, and is,
and will be to all eternity the first and last.
Glory to the Lord forever.
Hallelujah, praises to the Lord forever, and forevermore.

G+++.+++ F.

=== Postscript

The law showeth its righteousness by its works:
and the gospel showeth its righteousness by faith, which doth exceed that of the law.
And the law woundeth: but the gospel healeth, and is glad tidings and good news.
The law condemneth: and the gospel delivereth.
And Moses accuseth: but Christ defendeth.
And Moses condemneth: but Christ pardoneth.
The law restraineth the hands: but the gospel restraineth the hands and the mind.
And the law condemneth: but Christ saveth.
Moses, a servant, in his signs, figures, and shadows: but Christ a son, the substance,
who takes away the sins, and signs,
and makes all things new in his new covenant and new testament.
And the law was uttered with thunder from Mount Sinai:
but the gospel with joy from heaven, and comfort of salvation.
And the law and statutes were to one people, to wit, the outward Jews:
but the gospel is to all nations, and to every creature under heaven.
And as Moses lifted up the serpent in the wilderness, in the old covenant and testament,
even so must Christ, the son of man, be lifted up in his new covenant and new testament.
John 3. Moses led the outward Jews to Canaan outward;
and they were to conquer and drive out the seven nations
before them with outward carnal weapons and armour:
but Christ leadeth his Jews in spirit, in his new covenant, into heaven,
and they are to conquer the spiritual wickedness and rulers of darkness, through Christ,
with spiritual weapons and armour.
So the new covenant is not according to the old.
The old testament was the ministration of the letter;
and '`the letter killeth:`' but the new testament is not of the letter,
but of the spirit,
which '`giveth life.`' The ministration of death
in the old testament was engraven in stones,
answerable to the outward Jews in the old covenant and testament, their stony hearts:
but in the new covenant and testament, the Lord saith,
'`I will give them a new spirit and a new heart,
and will take away your stony heart out of your flesh;
and I will write my laws in your hearts, and put them in your minds:
and they shall all know the Lord,`' the Jews in the spirit,
(Jer. 31. and Ezek. 36.) in the new covenant and testament,
which is not according to the old.
And in the old covenant the Jews were to offer unto the Lord all their free-will offerings.
Lev. 22. And in Duet. 12. they were to '`eat of the free-will offerings
before the Lord.`' And in Ezra 3. '`Every one that offered willingly,
offered a free-will offering unto the Lord;`' and in Ezra
7+++.+++ Now in the old covenant they offered those things,
which were a free-will offering.
But Christ in the new covenant, which is not according to the old, he saith,
'`I am the good shepherd, that lay down my life for my sheep;`' and saith,
'`Therefore doth my Father love me, because I lay down my life, that I may take it again;
and no man taketh it from me, but I lay it down of myself: I have power to lay it down,
and I have power to take it again.
This commandment have I received of my Father.`' John 10. Here Christ the lamb of God,
is the free-will offering in his new covenant and testament,
which is not according to the offerings in the old testament and old covenant.
And Christ, by offering up himself freely once for all,
hath abolished all the offerings in the old covenant.
No unclean thing was to be offered to God,
nor to be eaten in the time of the law and old testament,
nor any unclean person was to offer.
And in the time of the gospel and new covenant,
which is not according to the law and old covenant,
much more doth not the Lord accept an unclean person, nor an unclean offering;
for it is the spiritual sacrifice that he doth accept; and they are to feed of the clean,
holy, heavenly sacrifice,

Christ Jesus, and feed of the clean spiritual food from heaven.
And the apostle saith to the saints, '`that they were not to touch the unclean,`' to wit,
the unclean spirits, and its works and actions.
And yet the same apostle saith,
that every creature of God is good,`' the outward creatures,
and ought to be received with thanksgiving;
For they are sanctified by the word of God and prayer.`' Therefore,
those things may be touched in the time of the gospel and new covenant,
which were not to be touched in the old.
And so the new '`covenant is not according to the old.

[.blurb]
=== Concerning the Passover in the Old Covenant; and the Jews in the Spirit, the True Christians in the New Covenant.

The paschal lamb was one of the flock without blemish,
to be sacrificed in the old covenant: but Christ was a perfect man without sin,
and died for sin.
And the paschal lamb, the Jews, in the old covenant, were not to break a bone of it:
and Christ, when they had crucified him, the paschal lamb in the new covenant,
they did not break his legs, as it is written,
'`Not a bone of him shall be broken.`'
And the Jews did eat their paschal lamb at evening;
and the whole congregation of the Jews did kill the paschal lamb at the evening,
and they were to eat of the lamb, '`a male without blemish;
and strike the blood on the two side-posts,
and upon the upper door-posts of the house.`' Ex. 12. But now
once in the end of the world hath Christ offered once for all,
to put away sin by the sacrifice of himself in the new covenant,
who sprinkles '`the hearts and consciences with his own blood.`' Heb. 9:26.
And did not the congregation of the Jews join together to kill Christ,
our paschal lamb, at their passover, who tasted death for every man;
and his blood cleanses from all sin?
For Aaron the high priest sprinkled the blood upon the people,
which was the life of the clean beasts,
and made an atonement with it for himself and the people in the old covenant and testament:
but Christ with his own blood, which is the life of him, the lamb of God without blemish,
which takes away the sins of the world, he the high priest,
sprinkles the hearts and consciences of his people with his own blood, which is his life,
and with it makes atonement to God for the sins of the world.
And none but the circumcised in the flesh did eat of the outward lamb,
the passover in the old testament.
And none do eat of Christ, the passover in the new covenant,
but who are circumcised in the spirit,
and by the faith which he is the author and finisher of.
The goat did bear the people`'s iniquities in the old testament: but Christ,
in his new testament, the Lord did lay upon him the iniquities of us all;
and '`Christ was made sin for us, who knew no sin,
that we might be made the righteousness of God through him.`' 2 Cor. 5:21.
And was not that one golden candlestick,
which Moses was commanded to make in the old covenant, with all its knobs, flowers,
and branches, and bowls like almonds, which were to be made of pure gold,
a type of the body of Christ, the church,
(Ex. 25.) seeing that the churches of Christ in
the new testament are called the golden candlesticks? Rev. 1:20.
The law saith, '`Do this and live; and be obedient,
and ye shall eat the good and fat of the land: but they that were disobedient, wandered,
and murmured, and died, and their carcasses fell in the wilderness,
and never saw the good land.

But in the new testament Christ saith, '`This is the work of God,
to believe in him whom God hath sent.
And he that believeth in the Son of God shall not perish,
but have life everlasting.`' And he seeks those good things which come down from above,
and hath them, and his affections are set on things that are above,
the everlasting things of the kingdom, and of the world that hath no end.
And they that make a profession of the words of Christ and his apostles in the new covenant,
as the Jews did of the old, and do not obey his gospel, nor believe in the light,
which is the life in Christ, they are not grafted into him;
and so do not enter into the eternal rest, but do wander in the spiritual wilderness,
and die in their sins, as Christ said of those that did not believe in him.
The outward Jews in the flesh in the old covenant, and outward circumcision in the flesh,
they had their outward genealogies and chronicles, for every tribe,
and written in outward books: but in the new covenant, which is not according to the old,
he is not a Jew that is one outward, but he is a Jew that is one inward, in the spirit.
So the Jews in the spirit, the '`true Christians in the new testament,
have their names written in heaven, and in the Lamb`'s book of life,
and have the Father who is the creator of all, his mark and seal in their forehead.
And outward circumcision in the flesh, was circumcision in the old testament.
But in the new testament, outward circumcision is not circumcision,
but inward circumcision, which puts off the body of death, and the sins of the flesh,
that hath gotten upon man and woman by transgression;
this is the true circumcision in the new covenant,
in which people serve God in the spirit.

And in the old covenant he was a Jew that was one outward: but in the new covenant,
he is not a Jew which is one outwardly; but he is a Jew that is one inwardly;
and circumcision is that of the heart, and in the spirit, and not of the letter,
whose praise is of God, and not of men.
And the Lord appeared among the Jews in the outward temple,
when they kept his law in the old covenant.
But in the new covenant, which is not according to the old,
God hath sent his son to abolish the Jews`' outward temple, and the old covenant,
and the law, and things in it, which God had commanded.
And in the new covenant, which is not according to the old, God,
and his son Christ Jesus, appears in his people, and dwells in them,
and makes them his temple.
And in the old covenant they had the temple in the city of Jerusalem;
but in the new covenant there is no temple in the heavenly Jerusalem;
for the Lord God and the Lamb is the light and the temple of it.

G+++.+++ F.

Marshgrange, the 8th Month, 1679.
