== To the great Turk and King at Algiers: together with a Postscript of George Pattison`'s taking the Turks, and setting them on their own shore.

In the name of the Great God, and Lord, creator and king of all things,
in heaven and earth, do I write unto you.
And I do take Enoch, Noah, Abraham, and Lot, and Isaac, and Jacob, and Joseph, and Moses,
and David, and all the prophets of the great and most high, dreadful and terrible God,
who is a consuming fire to the wicked, and John, as you say in your Alcoran, page 30,
chapter xxxiii.--I say, John the son of Zachariah,
that did affirm Christ to be the Messiah, and to be the word of God,
that great and chaste just prophet, and Mary, the mother of Jesus Christ,
with all his holy apostles, and your own Mahomet and your Alcoran,
to be witness against you, and some of your practices that are practised amongst you,
at the dreadful day of judgment of the great God,
when you shall all give an account of your words, deeds, and actions, and be rewarded;
who will reward every man according to his works, whether they be good or evil.
For I say of a truth, that the great God and Lord of heaven and earth,
and all things therein, is no respecter of persons, but in every nation,
he that fears God, and worketh righteousness, is accepted of him.

And now, O great Turk, and the king of Algiers,
I have something here to present before you, and my desires are, that you may read, hear,
and fear the great and terrible, righteous, holy, and pure God.

And here as followeth, you may see the impiety and unchasteness,
and the cruelties of some of your people at Algiers, against honest, chaste people,
that serve and fear and worship the most high God, which you have taken captive;
I say you have taken their ships, their goods, and some you keep slaves,
some till they have died, and others you have sold for slaves;
many people of the most high God, in scorn called Quakers,
besides great numbers of other English people,
and people of other nations cruelly oppressed, and inhumanly used by you.

Did ever Mahomet give you authority to rob, spoil,
and take the goods of them that do you no harm, and keep captives the bodies of them,
and sell them; or to beat upon the feet, belly, or back, them which are so taken,
to make them promise more money for their ransoms than they are able;
or to beat upon the feet with one, or two, or three hundred blows,
and hang up by the heels, and beat them which you have taken captives,
because they refuse to lie with your men, as a man lieth with a woman.
And is it not contrary to your very wild bulls, horses, rams, and he-goats,
and other wild creatures and brute beasts?

And is it not declared against, by the mighty and eternal God,
by Moses and all his holy prophets;
who saith it is an abomination to lie with mankind as with woman-kind:
and such men as commit these abominations have defiled the land,
and God will spew them out.
And such emperors, kings, and magistrates as wink at,
and suffer such wicked abominations and impieties,
the great God will bring his judgments and vengeance upon them.

For the eternal holy Lord God Almighty saith,
who is of purer eyes than to behold iniquity: '`If any man lieth with mankind,
as he lieth with women, both of these men hath committed abomination,
they shall surely be both put to death; their blood shall be upon them,
for all such defile God`'s land and earth;
and for such iniquities will the mighty God visit your land.`' For he is the mighty God,
to see all your actions, ways, and doings, and hears all your words,
and sees all your thoughts;
and you can turn yourselves no way from the eye and face of God,
nor from his hearing your words, nor seeing your thoughts.
Now, would you (to wit, the great Turk, and the king of Algiers,
or any of your subjects) be so served yourselves, if you should be so taken captive,
to be hanged up by the heels, and beaten with two or three hundred stripes,
because you esteem virtue, piety, and chastity, and not be forced to lie with other men,
as you lie with women,
could you undergo such punishment as you inflict upon some of our chaste people,
because they will not submit to such abominable impieties
as some of your subjects would force upon them,
that you have in captivity.

And would you think it were just, according to the law of the great God,
and your own Alcoran, if you were taken captive and your goods spoiled,
and to be beaten upon the belly, back, or feet,
to get more money than you are able to give, for the redemption out of your captivity?
And is this not contrary to the just law of the great and holy God,
and contrary to his prophets, yea, and contrary to Mahomet, that gave forth the Alcoran?
Or did those which took Lot, Abraham`'s friend, and his company captive, beat them,
because they would not lie with men, as aforesaid?
Or where did ever David, or any of the prophets of God,
force any that they had taken captive to lie with men, as you have done.

And do not you remember, that when some of your men-of-war took George Pattison captive,
who was a Quaker, and his ship, and his men; that afterward they conquered them again,
without hurting of them, and took them captive, and when they had done,
set them on the Turkish shore without hurting of them, as may be seen in the postscript?

And where did any of the Turkish men-of-war do so to the English or to the Quakers; but,
on the contrary, you beat them, to get more money than they are able to give you,
because they will not lie with your men.
And this practice of yours is neither moral nor humane, but worse than beasts;
and so do contrary to the law of the great God, in that you do that to others,
which you would not have others do unto you.
Now Mahomet saith in your Alcoran, chap. 15. p. 161:
'`When the messengers of the great eternal God were
sent to destroy the infidels of Sodom,
which came to Lot`'s house;
and the inhabitants of the city came to Lot`'s house to see the messengers:
and Lot said unto them, I beseech you, defile not yourselves with my guests: fear God,
and dishonour not yourselves; and how that Lot said, behold my two daughters, take them:
and the inhabitants said, we do not hinder thee to lodge thy guests.
And how that the inhabitants remained confounded in their drunkenness,
and that God overthrew the city, and turned it upside down,
and caused it to rain with stones and fire, which utterly destroyed it,
who were so impious.
And this shall serve for an example to passengers that shall see those ruins;
and for a mark of the omnipotency of God, to them that believe in his divine majesty,
that God avenged on them, they may serve for examples to posterity.`' Now,
how can you look up to the great God of truth,
and in your own Alcoran and scriptures concerning Lot, and suffer such impious,
abominable actions to be committed at Algiers, for your men to whip young men,
and force them, because they will not lie with men?
Is not this as bad or worse than the Sodomites,
that would have lain with the messengers that came to Lot`'s house, to commit sodomy;
who called to Lot, and said, bring them out that we may know them;
and Lot proffered them his two daughters to save the messengers.
And is not the eternal God, that changes not, the same,
to judge and destroy them that act such things among you, as them in Sodom did,
and that suffer such impieties and abominations to be acted,
and love their sins more than piety?

And Mahomet saith in your Alcoran, chap.
xv,
4 '`God guideth not the unjust.`' And therefore the great
and eternal God doth not guide your people in these impieties.
And you say the greatest part of the world are impious,
because of the enormities of their crimes: but now look among your own subjects,
and see if they be not the same for crimes, impieties, and enormities.
And if Jesus the son of Mary, who confirms the ancient scriptures, be full of light,
and of the gospel, to conduct the people the right way,
with a confirmation of the old testament, and to guide and instruct the righteous,
then certain your actions before mentioned at Algiers, and that way,
doth declare you not to be in this right way of light, and gospel of Jesus.

And again Mahomet saith in your Alcoran,
'`Such as shall not judge conformable to the laws of God,
are unjust:`' and these abominable impieties of yours
are not conformable to the law of God,
but lead you into the way of destruction, from the way of salvation, and, therefore,
unjust.

And you say in your Alcoran, chap.
v. '`God loveth the just:`' but he hateth such unjust actions of yours.
And in your Alcoran you write,
'`that God punished the children of Israel that polluted the earth,
and opposed the will of God,`' etc. and further you say,
'`He that slayeth an innocent person shall be punished
as if he had slain the whole world;
and he that shall give his life,
shall be recompensed as if he had given life to the whole world.`' Now,
hath not your practice herein been contrary to your Alcoran, as in chap.
v. p. 64, 65.

And do not you say '`you gave them your curse,
that altered the words of the scripture;`' and also saith,
'`that God loves them that do good.`' chap.
v. p: 65,

Now these bad actions of yours are contrary to the scriptures,
and contrary to your Alcoran, and therefore how can God love you.
And again you say, '`Such as have the knowledge of the scriptures,
ought to believe in Jesus before their death;
for he shall be a witness against them of their actions in the day of judgment.
Now, ye Turks, consider how you do acknowledge the scriptures, and believe in Jesus,
and in God, who show forth such abominable actions:
and do not you think that Jesus the Messiah will
be a witness against you at the day of judgment,
for your impieties and your infidelity?
And must not all such be cast into the lowest hell,
and find no relief except they repent in their lifetime,
and do good works meet for repentance, and resign yourselves to God,
and obey his commandments; as to this effect you say in your Alcoran, chap.
iv. p. 61.

And you confess '`that every man shall taste death,
and have reward at the day of judgment.`' And do you think of the day of judgment,
and fear God, that do such evils and impieties?

And again, you say in the Alcoran,
that '`you would have the fear of God before your eyes, and if you be converted,
your principle remains unto you, '`Do injustice to no man,
then it shall not be done unto you.
If your debtors be not able to pay, and in want,
you do well to stay their conveniency.`' Chap.
2. page 28.

Now, do not you Turks show, that you are degenerated from your principle,
and are not converted, that do these unjust, abominable things to others,
that you would not have them do unto you, and beat your slaves and captives,
because they will not give you more money than they have to redeem themselves withal,
and because they will not lie with your men as aforesaid; and therefore,
as you say in the same chapter,
'`the wicked shall he deprived of protection at the day of judgment.`' And again,
in your Alcoran, you say,
'`you shall all one day appear before his Divine Majesty to be judged.`' Therefore,
dread and fear this day, you that commit such abominations, and act such cruelties.
Again, Mahomet saith, in chap.
ii. page 19, '`There be men whose speeches may be pleasant to thee in this world,
they will call God to witness what is in their hearts,
nevertheless they are very pernicious.`' Now, is not this your condition at Algiers?
And you say, '`God knoweth, he is with them that fear him, chap.
ii. page 18. But truly you do show that you are not in this fear, chap.
ii. and page 11. Again, you say, '`Wheresoever men do turn themselves,
there the face of God will meet them,
his divinity extendeth through the whole earth.`' Therefore, how dare you,
in the face and sight of God, act such things and not repent,
and fear his Divine Majesty?
And therefore,
take heed that you do not purchase to yourselves the life and lusts of the world,
and quit paradise, and go into misery, as you say in your 8th page.

And again, Mahomet saith, '`If slaves have recourse to you,
ye shall redeem them,`' etc. page 8. Now, you are far from redeeming slaves,
when you beat them for not giving you money according to your wills,
and more than they can give,
and also beat them because they will not commit horrid uncleanness,
to defile and abuse their bodies with mankind.
And you say that Adam begged pardon for his fault, who departed from his grace;
and have not you need of this, and repent and turn to the Lord, you who defile the earth?
For else is not hell prepared for such that pollute the earth?
For you are not observers of God`'s law, nor of your own Alcoran, as you may see, chap.
ii. Page 2.

And the great God, the creator of all, doth know all in heaven and in earth,
both what is done in secret and openly, and all is naked before him,
who will reward every man according to his works; he is a consuming fire.

And Mahomet saith, '`that God guideth not the wicked,`' chap.
xix. page 115. And again, he saith, '`Alms are appointed for the poor,
for them that recommend themselves to God, to redeem slaves,
and such as are in debt;`' in the same chap.
page 11. I say, then, according to your own Alcoran, God hath not been your guide,
to be so wicked against the slaves you take.
And as for your alms and charity to them, it is manifest they are but cold.
But where did any called christians, after they had taken any of you Turks,
beat you because you would not give them more money than you had,
and because you would not lie with men, as aforesaid.
And if God be full of goodness for the people, as Mahomet saith, chap.
x. page 130, then you are degenerated from his goodness.

And again, in chap.
xi. page 134, Mahomet saith,
'`that God shalt reward every one according to his works.`' And therefore,
why do not you dread and fear this great God of heaven and earth?
And, chap.
xi. cage 140, Mahomet saith, '`Detain nothing from your neighbours,
defile not the earth,`' etc.
Then how can you detain men`'s children, and servants, and goods from them,
and beat them, because they will not give you more money than they have, to redeem them;
and hang them up by the heels, and beat them, because they will not lie with men.
Oh, horrible impieties!
And did not God destroy such, both in the day of Noah, Abraham, Lot, and Moses,
that did corrupt and defile the earth?

And, chap.
xii. page 144, '`How Joseph`'s mistress would have had him to have been unchaste,
and how amorous she was of Joseph, her husband`'s slave, and how that Joseph said,
'`O God, I had rather be a prisoner than do what she desireth.`' Now here,
do not you act contrary to Joseph and your own Alcoran,
who would force your captives to lie with you, like Sodomites?
Is not this worse than Joseph`'s mistress, who would not only force,
but beat them with some hundred stripes,
because they will not submit to your inhuman impieties, and Sodomites`' wicked lusts?
For our friends that are your captives, are of Joseph`'s spirit,
that obey the law of the most high God.
And you say, that '`Joseph`'s mistress did confess he was a just man,
but Joseph would not be a traitor to his master.`'
No more can the people of God called Quakers,
your slaves in Algiers, be traitors to God, and disobey his just laws,
that condemn such unchaste, inhuman impieties, that you Turks would force in Algiers,
to lie with men; they had rather be prisoners all the days of their lives.

And, therefore, as Mahomet saith, chap.
xix. page 188, '`That all such infidels, for their impieties, must burn in hell,
except they repent of their wicked actions.`' For as you confess,
'`you must all appear before the Lord, at the day of judgment,
and give an account of our actions.`' And could the old world, and Sodom,
be more vicious than you, that do such wicked actions?
And Mahomet saith, chap.
xxi. page 200, '`That David and Solomon, rendered such justice in the field,
that the flocks of the village entered by night without shepherds.`' Now,
are not you fallen and degenerated from this justice both of David and Solomon?
That the flocks cannot enter the villages without shepherds and guides,
let the great God of truth judge.
And therefore, what will you say in the day of judgment,
when the prophets and your own Alcoran will be against you?
For will not you that act such things, be found fire brands of hell?
And how can such expect the Lord`'s protection?
And therefore, the great God will call you to an account for all your actions;
and all men upon the earth, who transgress his good and holy just law.
And if the God of truth be king of the whole earth, as you confess in your Alcoran, chap.
xxiii, page 212, '`and the creator of all, and king of all things,
both in heaven and earth,`' then how dare you act such unchaste, unjust things,
and be such wicked rebels against his commandment and just law?
And therefore, the balance of the cursed, as you confess, shall be light,
or empty of good works, that obeys not the commandments of God.

And Mahomet saith, chap.
xxix.
page 245,
'`how God delivered Abraham from the people that would have killed
him.`' But if you were in the steps and faith of Abraham or Lot,
you would not defile yourselves with filthiness.
And do not you confess, that Lot said to them of Sodom,
'`Ye defile yourselves with filthiness,
unknown to any before you;`' and told them they inclined to the love of men.
Ye rob in the highways, and defile one another?
Now, have not you Turks forgotten Lot`'s preaching,
and degenerated from your own Alcoran, and are become robbers, and to follow that,
unknown filthiness, with which you defile yourselves, (to wit,) the lust of men?
That you beat those which you have robbed and spoiled, and taken captive,
because they will not lie with your men as aforesaid.
And therefore,
how can you expect but that God`'s wrath and indignation
will fall upon you for your impieties,
and you to be set forth for examples to posterity;
whom the devil hath seduced from the right way of the Lord, and of his righteous law;
who neither follow your own Mahomet, what he hath declared,
but the vanities of infidelity; and fear not God, his divine majesty, nor regard his law,
but have contemned his commandments.
And therefore, Mahomet saith, chap.
li. page 326, '`Such as fear not God, and do not believe,
shall be punished in hell fire.`' And again, Mahomet saith, chap.
lix. page 344, '`In the name of God, gracious and merciful,
whatsoever is in heaven and earth, exalts the glory of God.
He is omnipotent and wise;
it is he that exiles the wicked from among them that knoweth his law.`' Then here,
are not you the wicked that are exiled, that disobey his law,
and commit such abominable things?
And therefore, you cannot exalt God`'s glory, neither are you gracious nor merciful,
that do thus beat and abuse your captives, because they will not lie with men,
as aforesaid; yea, two or three hundred stripes,
and to give more money for their redemption than they are able to give.
And therefore, such wickedness as yours doth dishonour the great God,
and you will be made the examples of his wrath, and suffer the pains of hell fire,
except ye repent, as Mahomet saith, chap.
lxvii.
Page 356.

And therefore do not strengthen yourselves in impiety,
nor put your fingers in your ears and stop them, and cover your heads with your garments,
that you will neither hear nor see God`'s law, as Mahomet tells you,
which reproves you for your impieties, who are erred from the right way of the Lord,
that do commit such things.
And chap.
xciii.
p. 385, Mahomet tells you how the Lord enriches you,
and that you should do no injury to the orphans, and that you should not devour the poor,
but that you should recount the graces that God hath conferred upon you.
Now, are not you Turks degenerated, not only from the law of God,
but from Mahomet`'s teaching in his Alcoran?
Do not you devour the poor orphans, whom you take captive,
and injure them when you beat them,
because they will not give you more money than they have,
and because they will not lie with your men, which is abominable?

Again, Mahomet saith, chap.
cii. p. 319, '`He that persecutes his neighbour, misery is upon him,
and persecution shall come upon him, and conquer him.`' And therefore,
if ye believe his Alcoran, this will be fulfilled unto you, that do such things.
And again, Mahomet saith, '`He that heaps up treasures, and is busy to count them,
thinks they will make him immortal:`' he tells such what shall be their misery,
'`that their hearts shall be burnt in the fire of hell.`' And therefore,
what will become of you, who get your treasure by theft and robbery, and taking captives,
and beat them, to give more money for their redemption than they have,
persons that neither do nor think you any harm, who are the subjects of the great God,
and keep his commandments; surely such that do so,
will be overwhelmed with the flames of hell, and bound to great pillars of the same.
And again, Mahomet saith, chap.
cv. p. 391, '`He that devours the substance of orphans, and the bread of the poor,
blasphemes against the law of God,
and misery is upon him.`' Now are not you men of Algiers,
they that devour the substance of orphans, that hinder men to do well,
and follow their lawful business?
And so are not only under the judgment of the law of God,
but under the judgment of your Mahomet,
who live there by spoiling and robbing your neighbours, that think you no hurt.

And Jesus, the son of Mary,
which you confess in your Alcoran was sent to guide and instruct people in the right way,
who you confess was a great prophet,
and do find fault with the Jews because they did not obey him,
he commands people that they should love their enemies, and do good unto enemies,
and pray for enemies, and do good unto them that despitefully use them.
And you say in your Alcoran, that Jesus shall be a witness in the day of judgment,
against such as obey not his law;`' then do not you
believe he will be a witness against you,
for disobeying his command and law, who hate not only them you think your enemies,
but those that neither think nor do you harm, and take them captive,
and rob and spoil them of their goods; and beat them,
because they will not be defiled with your men,
and give you more money for their ransom than they are able to give.

And again Mahomet saith, chap.
iii. p. 34, that Jesus said, '`Who shall sustain the law of God in my absence?
And the apostles answered him, '`We will sustain the law of God in thy absence,`' etc.
And. therefore why do not you believe in the law of God,
according to Jesus and the prophets;
for Jesus`'s apostles declared against such men as
burned in their lusts one towards another,
men with men; and who knew the judgment of God was upon them that committed such things,
and that they were worthy of death, and yet did not only do such things,
but had pleasure in them that did them: and, therefore, you Turks that do such things,
are judged by the great God, and all his holy prophets, and Jesus Christ,
and his apostles, to act contrary to God`'s pure, just, holy, righteous law,
and they are witnesses against you, as is also your own Alcoran.

And now consider, O ye Turks! the great and holy eternal God,
who made the world and all things therein, he is Lord of heaven and earth,
and the great King over all, and dwelleth not in temples made with hands,
but in temples of his people`'s hearts; neither is he worshipped with men`'s hands;
he giveth to all breath, life, and all things, that they might serve and worship him.
And he hath made of one blood all nations of men, for to dwell on the face of the earth;
and hath determined the times before appointed, and the bounds of their habitations.
And all should seek after the Lord, who fills heaven and earth,
who is not far from any people, and now commands all men everywhere to repent;
because he hath appointed a day in which he will judge the world in righteousness.
And, therefore, how can you do any violence against your own flesh and blood,
seeing that God hath made of one blood all nations of men,
and commands you to do unto all men, as you would have them do unto you, yea,
and to love another, and to love enemies?
And therefore, it is the devil that seduces you,
and makes you hate both your friends and enemies, and your own flesh and blood.
And also the eternal God of truth commands,
that prayers and supplications be made for all men, who would have all men to be saved,
and come to the knowledge of the truth; and therefore you ought not to destroy them,
nor to hurt them, which you cannot hurt, if you truly pray for them.
For the Lord hath commanded his prophet Ezekiel to say unto the people, '`As I live,
saith the Lord, I have no pleasure in the death of the wicked,
but that the wicked turn from his wicked ways and live.
Therefore turn ye, turn ye from your evil ways, for why will ye die?
For I have no pleasure in the death of him that dieth,
saith the Lord God of truth.`' Therefore turn yourselves to the Lord, and ye shall live;
for the Lord God that created the heavens and the earth, and stretched them out;
he that spread forth the earth, and that which comes out of it;
he that giveth breath to the people upon it, and spirit to them that walk therein,
his law and covenant,
and light is to be minded and kept that he hath given to the nations,
so that every one that hath breath, may praise the Lord in his covenant of light;
for in the hand of the Lord is the soul of every living thing,
and the breath of all mankind.
And the Lord opens unto them that obey him, his good treasure;
that they have the blessings from above and also from below.
And he is the Lord God of the spirits of all flesh,
and therefore all are to worship and serve him in the spirit and truth,
who is the Lord God of their spirits.
And he was the teacher of Adam and Eve,
and as long as they kept under his teachings they were happy;
but when they forsook God`'s teaching, and followed the devil`'s and Satan`'s teaching,
who led them from God into corruptions, filthiness, uncleanness, and into divisions,
and to destroy one another.
But according to God`'s promises and prophets,
the seed of the woman is come to bruise the serpent`'s head:
and is the speaker and teacher again to his people by it,
as he was to Adam and Eve in paradise.
Glory and praise to the great and eternal God forever.

And God by his prophets said,
'`that he would pour out of his spirit upon all flesh.`' And Jesus Christ said,
'`that God was a spirit, and they that worship him,
must worship hire in spirit and truth.`' And now all men and women in the whole world,
they must come to the spirit and the truth in their own hearts,
which they have from the God of truth,
if they do serve and worship the holy and eternal God of truth, in his spirit and truth.
And these are the true worshippers that worship the
eternal God of truth in his spirit and truth,
which the devil, which is the foul corrupt spirit, is out of, who abode not in the truth,
and there is no truth in him; therefore he is not to be followed, nor worshipped,
but the God of truth.
And the grace of God which brings salvation, hath appeared to all men, which teacheth us,
his people, to deny ungodliness, and worldly lusts, we living soberly, righteously,
and godly in this present world.
Nov all men must come to this grace of God in their hearts,
which appears to them in their hearts,
which shows them their ungodliness and worldly lusts, and their unrighteousness;
and it will teach them to forsake it, and bring their salvation.
But if that you do turn this grace of God into wantonness,
and walk despitefully against the spirit of grace,
you walk in despite of that which should bring your salvation;
then you bring the wrath and indignation of the great God against you,
who abuse his grace and favour.
And the Messiah, and you,
and Mahomet do confess that John declares Christ the Messiah to be the word;
then you are to obey him.
Moreover John saith, that he was not that light, but sent to bear witness of that light,
'`and that was the true light, which lighteth every man that cometh into the world.`'

Now you all being enlightened with this true light,
which light lets you see all your evil deeds and actions that you do,
and all your evil words and thoughts that you speak and think.
And every one of you that doth truth cometh to the light,
that your deeds may be manifest they are wrought in God, from whom they have this light,
in whom there is no darkness; but every one of you that doeth evil, hateth the light;
then you hate Jesus Christ, and the eternal God; neither will you come to the light,
lest your deeds should be reproved by the light; and '`this is the condemnation,
that light is come into the world, and men love darkness rather than light,
because their deeds be evil.`' Now if you would do the truth, and come to the light,
and love it, it shines in your hearts,
and would give you the light of the knowledge of the glory of God,
in the face of Jesus Christ,
and then you would know this heavenly treasure in your earthen vessels,
and the excellency of this power to be of God, and not of your selves.
And you do confess, that Jesus Christ was not begotten by the will of man,
who was conceived of Mary,
and that she should conceive and bring forth without the touching of man;
and he being conceived by the holy spirit,
then whose son can he be but God`'s? Who taught him the scriptures,
and the mysteries of the laws of the old testament, and the gospel;
who was a prophet to the children of Israel, as you confess in your alcoran, chap.
iii. page 34. So he '`was declared to be God`'s son in the power,
according to the spirit of holiness,
by the resurrection from the dead;`' for all died in Adam,
and he tasted death for every man,
and is risen for the justification of all that believe in him,
the true light of the eternal God.

And now all ye Turks, and all people upon the earth; God, who is immortal, eternal,
and invisible, he has poured out of his spirit upon you all; but if you do grieve it,
and vex, and rebel, and err from and against his good spirit,
then you go from God`'s law, and that which doth witness for him,
which is his spirit in your hearts, which is a witness for the King of kings, yea,
the great King of heaven and earth.
I say, this witness doth witness for the great God,
who will judge the world in righteousness, according to this witness,
and the secrets of every man`'s heart;
he by his spirit doth show unto man his thoughts and the imaginations of his heart,
and searches the heart, and tries the reins, and all things are naked and open to him,
who is a consuming fire to the wicked.
Now this spirit of the God of truth,
which he hath poured upon all flesh of men and women,
it is a witness against you for the pure God, for all your unrighteous,
and ungodly impious actions, and your bad thoughts and words,
and whatever you do or act that is unjust and unholy, and for what you do to others,
you would not have done to you;
the holy spirit of the great God of truth is a witness against you.
It was a witness against Adam and the old world that disobeyed him;
it was a witness against the Jews,
and it is a witness against all christians that walk not in it; and Turks,
and all people upon the earth.
And they that are led by the good spirit of God, are his children, sons and daughters;
and therefore prize your time while you have it, ye Turks and others,
and mind God`'s good spirit, and his light and grace, which will bring your salvation,
that you may come into favour with the God of truth.

From him whose love is to GM and Jesus Christ, the just and holy One,
and all his holy prophets and apostles, and all people upon the earth,
for their salvation, and desires their eternal good and happiness,
and not any man`'s destruction.

G+++.+++ Fox.

Kingston upon Thames, the 16th of the fifth Month, 1680.

=== Postscript / Of George Pattison`'s taking the Turks about the 8th Month, 1663.

Dear Friend,

Thine I have received.
In answer to thy request, I have given thee an account as well and as near as I can;
but as to the exact time I cannot, for I have not my books.
I was George Pattison`'s mate, and coming from Venice,
being near a Spanish island called May York, we were chased by a Turkish ship or patah,
as sometimes before we had been, and thinking by our vessel`'s well sailing,
might escape.
But Providence ordered it so, that by carrying over-much sail,
some of our materials gave way, by which means the said Turk came up with us,
and commanded the master on board, who accordingly went, with four men more,
leaving me and three men, and a boy, on board our ship;
and so soon as our men came on board the Turk, they took them all out of the boat,
and came about fourteen Turks in our boat.
All which time I was under a very great exercise in spirit, not so much for myself,
because I had a secret hope of relief; but a great stress lay upon me,
for the men in this very juncture of time.
For all hope of outward appearance being then gone,
the master being on board of the Turk, and four more, and the Turks just coming on board,
I being as one, even as if I were or were not,
only desiring of the Lord for patience in such an exercise,
and going to the vessel`'s side, to see the Turks come in,
the word of life run through me, '`Be not afraid,
for all this thou shalt not go to Algiers.`' And I having formerly
good experience of the Lord`'s doing upon several such like occasions,
as in times of war, I believed what the Lord did say in me.
At this all kind of fear was taken from me,
and I received them as a man might his friend; and they were as civil,
so showing them all parts of the vessel, and what she was laden withal,
then I said to them that were our men, be not afraid, for I believe, for all this,
we shall not go to Algiers: but let me desire you, as you have been willing to obey me,
so be as willing to obey the Turks.
For by our so doing, I saw we got over them; for when they saw our great diligence,
it made them careless of us, I mean in securing of us.
So when they had taken some small matter of what we were laden withal,
some went on board their own ship again, and some stayed with us, which were about eight.
Then began I to think of the master and the other four, which were in the Turks`' ship;
for as for myself, and the others with me, I had no fear at all; nay,
I was so far from it, that I said to one then, '`Were but the master on board,
and the rest, if there were twice so many Turks,
I should not fear them.`' So my earnest desire was to the Lord,
that he would put it into their hearts to send him on board with the rest;
and good was the Lord in answering,
for it was as a seal to what he before spoke through me.

As soon as the master was on board with the rest, all manner of fear was off me,
as to my going to Algiers, and some said to me, I was a strange man;
I was afraid before I was taken, but now I was taken I was not.
My answer was, I now believe I shall not go to Algiers, and if you will be ruled by me,
I will act for your delivery, as well as my own.
But as yet I saw no way made, for they were all armed, and we without arms.
Now, we being altogether, except the master, I began to reason with them;
what if we should overcome the Turks, and go to May York?
At which they very much rejoiced; and one said, I will kill one or two; another said,
I will cut as many of their throats as you will have me.
This was our men`'s answer; at which I was much troubled, and said unto them,
if I knew any of them that offered to touch a Turk, I would tell the Turks myself;
but said to them, if you will be ruled, I will act for you, if not, I will be still;
to which they agreed to do what I would have them.
Then, said I, if the Turks bid you do any thing, do it without grumbling,
and with as much, diligence and quickness as you can, for I see that pleases them,
and that will cause them to let us be together; to which they agreed.

Then I went to the master, who was a man of a very bold spirit, and told him our intents;
whose answer to me was, if we offered to rise and they overcame us,
we had as good be burnt alive, the which I knew very well.
But I could get him no way to adhere to me, in that he was fearful of bloodshed;
for that was his reason, insomuch, that at last I told him we were resolved,
and I questioned not to do it without one drop of blood spilt,
and I believed that the Lord would prosper it,
by reason I could rather go to Algiers than to kill a Turk.
So at last he agreed to this, to let me do what I would, provided we killed none.
At that time, there being still two Turks lying in the cabin with him;
so that he was to lie in the cabin, that by his being there they should mistrust nothing,
which accordingly he did; and having bad weather, and lost the company of the man of war,
the Turks seeing our diligence, made them careless of us.

So the second night, after the captain was gone to sleep,
I persuaded one to lie in my cabin, and so one in another, till at last,
it raining very much, I persuaded them all down to sleep, and when asleep,
got their arms in possession.
Then said I to the men of our vessel, now have we the Turks at our command;
no man shall hurt any of them, for if you do, I will be against you.
But this we will do, now they are under, we will keep them so, and go to May York.
So, when I had ordered some to keep the doors, if any should come out,
straightly charging the spilling of no blood; and so altered our course for May York,
the which, in the morning, we were fair by.
So my order was to our men, if any offered to come out,
not to let out above one at a time.
And in the morning one came out, expecting to have seen their own country,
but on the contrary it was May York.
Now, said I to our men, be careful of the door, for when he goes in,
we shall see what they will do.
And as soon as he told them we were going towards May York, they, instead of rising,
fell all to crying, for their hearts were taken from them.
So they desired they might not be sold, the which I promised they should not.
So soon as I had pacified them, then I went in to the master,
he not yet knowing what was done, and so he told their captain what we had done,
how that we had overcome his men, and that we were going for May York;
at which unexpected news he wept, and desired the master not to sell him,
the which he promised he would not.
Then we told the captain we would make a place to hide them in,
where the Spaniards should not find them; at which they were very glad,
and we did accordingly.
So when we came in, the master went on shore, with four more,
and left me on board with the Turks, which were ten.
And when he had done his business, not taking product,
lest the Spaniards should come and see the Turks--.
But at night an English master came on board,
being an acquaintance; and after some discourse, we told him, if he would not betray us,
we would tell him what we had done, but we would not have the Spaniards to know it,
lest they should take them from us; the which he promised, but broke it;
and would fain have had two or three of them, to have brought them for England.
But we saw his end; and when he saw he could not prevail,
he said they were worth two or three hundred pieces of eight a piece; whereat,
both the master and I told him,
if they would give many thousands they should not have one,
for we hoped to send them home again.

So he looked upon us as fools, because we would not sell them;
the which I would not have done for the whole island.
But contrary to our expectations, he told the Spaniards,
who threatened to take them from us.
But so soon as we heard thereof, we called out all the Turks,
and told them they must help us, or the Spaniards would take them from us.
So they resolvedly helped us, and we made all haste to run from the Spaniards,
the which pleased the Turks very well.
So we put ourselves to the hazard of the Turks, and being taken again, to save them.

So we continued about six or seven days, not being willing to put into any port of Spain,
for fear of losing the Turks.

We let them have all their liberty for four days, until they made an attempt to rise,
which I foresaw, and prevented, without any harm.
I was very courteous to them, at the which some of our men grumbled, saying,
I had more care of the Turks than them.
My answer was, they are strangers, I must treat them well.

At last, I told the master it might do well to go to the Turks`' coast,
for there it was more likely to miss their men of war than where we were;
and also it might fall out so,
that we might have an opportunity to put the Turks on shore: to which the master agreed.

And in two days we were near the Turks`' shore, at a place called Cape Hone,
about fifty miles from Algiers, as the Turks told us.
So when we came about six miles from the shore it fell calm, and I had,
very much working in my mind, about getting them ashore.

At last I went to the master, and told him,
I had a great desire to put the Turks on shore, but how, I knew not;
for to give them the boat, they might go and get men and arms, and so take us again;
and to put half on shore,
they would raise the country and surprise us when we came with the rest.
But if he would let me go, and if three more would go with me,
I would venture to put them on shore; to which he consented.

So then I spoke to the men, and there were two more,
and myself and a boy took in the ten Turks all loose,
and went about six miles and put them on shore in their own country,
within about four miles of two towns which they knew.
Withal, we gave them about fifty padas of bread, and other necessaries to travel with.
They would fain have enticed us to go to the towns, telling us we should have wines,
and many other things.
As to their parts, I could have ventured with them.
They all embraced me very kindly in their arms when they went ashore.
They made one rising in the boat when going ashore, the which I prevented;
and we parted with a great deal of love.

When we came home to England; the king came to the vessel`'s side,
and inquired an account, the which the master gave him.

So this is as near as I can certify thee;
I have written thee more at large to give thee the whole as it was;
but thou mayest take what is the most material;
and so I rest thine in that which can do good for evil,
which ought to be the practice of all true men.

Thomas Lurting.

Liverpool, the 30th of the fifth month, 1680.
