[#ch4.style-blurb, short="The Protestant Christian Quaker"]
== The Protestant Christian Quaker, a sufferer by Relics of Popery, under all powers, for thirty years last past, who have Persecuted for Religion, yet call the Holy Scriptures their rule, that justifieth no such practice. By G. F.

The apostle exhorts the christians,
'`to be conformed to the image of the son of God.`' Rom. 8:29.
Who is the brightness of God`'s glory,
and the express image of his substance.`' Heb. 1.

And further, the apostle saith, '`That I might know Christ,
and the power of his resurrection, and the fellowship of his sufferings,
being made conformable to his death.`'

And also, the apostle exhorts the church, Rom. 12., saying,
'`Be not conformable to this world; but be ye transformed by renewing of your mind,
that you may prove what is that good, that acceptable, and perfect will of God.`'

Now here are three things for all christians to mind:

[.numbered-group]
====

[.numbered]
_1st._ They must be conformable to Christ`'s death.

[.numbered]
_2ndly._
They must be conformed to the image of the son of God,
who is the brightness of the glory of God,
and the express image of the Father`'s substance.

[.numbered]
_3dly._
They must not be conformable to the world; but be transformed from the world.

====

Now, to know what it is to be transformed from the world,
and not be conformable to the world, they must know what the world is,
that they must not be conformable unto, but be transformed from.

Which the apostle describes to be the lust of the eye, the lust of the flesh,
and the pride of life, which is not of the Father, but of the world,
and therefore must not be conformed unto, nor loved, but be transformed from;
for it passes away, and the lust thereof.

For if any man love the world, (saith the apostle,) and the things of the world,
the love of the Father is not in him.`' John 1:2.

Now, to be conformable to Christ`'s death, doth not the apostle say,
'`If they be dead with Christ, and conformable to his death,
then they are dead with Christ from the rudiments of the world,
and they cannot be subject to the worldly ordinances, and commandments,
and doctrines of men.`'

So here the world hath its ordinances, and commandments, and its doctrines,
which are not to be touched, nor tasted,
nor handled by them that are conformable to the death of Christ, and are dead with him,
and so, conformable to the image of the son of God,
who is the brightness of God`'s glory, and the express image of his substance.

Now all such as are conformable to the death of Christ, and are dead with him,
and are conformed to the image of the son of God,
which was the only conformity the apostle preached up; all such,
(1st,) cannot be conformable to the world, nor to the lust of the eye,
nor to the lust of the flesh, nor to the pride of life; (2ndly,) nor to their doctrines,
nor commandments of men, nor ordinances, nor traditions, no, not so much as to touch,
taste, or handle them; for they all perish with the using of them, saith the apostle.
But their conformity must be to the image of the son of God, as the apostles preached.

Now this conformity to the son of God was never held up nor defended by outward,
carnal weapons, neither by Christ nor his apostles; for Christ said,
'`he came not to destroy men`'s lives, but to save them.`'

And the apostles did affirm, that their war and weapons were not carnal, but spiritual;
and they did not wrestle with flesh and blood,
but with the powers of darkness and spiritual wickedness in high places,
for the plucking and pulling down the strong holds of Satan,
which he had set up in men and women`'s hearts since they fell from God.

So it is clear the apostles did not preach up a conformity
to the image of the son of God by carnal weapons.

So the apostles that preached conformity to the image of the son of God,
and to his death, did not hang, burn, banish, imprison, or persecute any,
or cut off the ears, or whip,
or spoil any people`'s goods that did not conform to the image of the son of God,
or conform to his death.
Nay, they did not imprison, put to death,
or spoil the goods of any of them that were conformable to the world and their doctrines;
but invited them, and exhorted them, and showed them the danger,
if they did not conform to the image of the son of God, and receive his grace, light,
spirit, truth, and gospel.

And they that did not die with Christ, could not live with him,
nor suffer with him could not reign with him.

Now they that are conformable to the image of the son of God,
are conformable to their saviour, their redeemer, and mediator,
and to the new covenant of grace, light, and life,
and to the worship in spirit and truth, and to the true church,
which Christ is the infallible head of,
who hath destroyed the devil and his image who is the head of all false images,
and image makers and worshippers.

And, therefore,
it is but fit that all christians should be conformable to the image of Christ,
and unto the happiness of this conformity the devil is an enemy,
and Satan is an adversary; and as he is a devil,
he seeks to destroy all them that are conformable unto it,
and that bear the image of the son of God.

And now all the doctrines, rudiments, and commandments of men,
which are not to be touched nor tasted, and so not to be conformed unto,
but transformed from;
for they are but the inventions of such as have not heard God and Christ`'s voice,
though they may have all the form of godliness both in the Old and New Testament;
and being out of the power and spirit that they were in that gave it forth,
all such are to be turned away from, and not to be conformed unto,
according to the apostles`' doctrine.

It is the power and spirit of God and Christ that brings to turn away from them,
and brings to be conformed to the image of the son of God, and so to do his will,
and to know his doctrine that is from above.

The doctrines, ordinances, commandments, and rudiments of the men of the world,
they are below:
`'for the world by wisdom knows not God;`' and they with their
wisdom would bring all men to a conformity to their image,
like Nebuchadnezzar`'s, which he set up, and to fall down to it,
else into his fiery furnace they must be thrown,
and Daniel must be cast into the lion`'s den.

So this was in the time of the old covenant amongst the Jews,
who were to be conformable to the law of God.
So they were not to conform to the ordinances or commandments, and decrees, and ways,
and worships of the men of the world, as Nebuchadnezzar and Darius, and the like,
about religion.

Which law and old covenant that came by Moses, Christ hath abolished:
but grace and truth is come by Jesus Christ, in his new covenant,
by which all must hear Christ, who is an infallible prophet, and an infallible priest,
who lives forever, and is an infallible shepherd and bishop of people`'s souls;
and to his image must all true christians be conformed.

Since the apostles`' days, how many ways, religions, worships, faiths,
and creeds have been made by men and councils, unto which conformity hath been required;
and yet they confess and say,
'`they have not the same power and infallible spirit
the apostles had.`' So then it is clear,
they are not guided by the same infallible spirit;
and yet such take upon them to judge of, and give forth doctrines, religions, ways,
worships, faiths, and judge of men`'s eternal states,
with their fallible spirit which they confess they are in; and then all their religions,
ways, worships, faiths, doctrines, creeds, ordinances, and directories must be fallible.
And yet these are such as fine and compel (with carnal weapons) men to fall down to,
and conform to their fallible ways, doctrines, religions, worships, faiths, creeds,
and ordinances, and canons, by force of carnal weapons.

And what is this they would have conformity to, but the likeness or image of a way,
religion, faith and worship,
that is not set up by the same infallible spirit and power the apostles were in?
And because people will not conform and bow down to their image of a faith, religion,
worship, and church, that their fallible spirit hath set up; therefore they will banish,
whip, imprison, burn, and hang,
or spoil the goods of such as cannot conform to this their image.

How many images of religions and ways have been set up since the apostles`' days?
And how much blood hath been shed?
And what burning, banishing, killing, hanging, and spoiling of goods hath been,
for not conforming to the image which this fallible spirit hath set up?
For they all confess they have not the same infallible
spirit and power that the apostles had:
and yet these called christians will say the scriptures are their rule,
for their life and practice, etc.
Then let them come to the rule, and try their practices by it.

For the apostles did not hang, burn, banish, or imprison,
or spoil the goods of any that were not conformable to the image of the son of God,
but still conformed to the world.
Neither did they wrestle with flesh and blood;
and the weapons of their warfare were spiritual, and not carnal,
by which they wrestled with spiritual wickednesses,
and plucked down the strong holds of Satan,
which he the foul spirit had set up in men and women`'s hearts.

Now all you that wrestle with flesh and blood, with carnal weapons, and have hanged,
burned, imprisoned, banished,
and spoiled the goods of such as could not conform to the image of your ways, religions,
faiths, and worships, (who confess, as was before said, that,
you have not the same power and spirit the apostles
had,) but conform to the image of the son of God,
declared in the scripture of the New Testament: in this your practice,
the scripture hath not been your rule,
if you will believe the apostles and Christ`'s doctrine, who said,
'`he came to save men`'s lives, and not to destroy them.`'

But the Papists, they cry, Conform, conform to their image of mass,
etc. or else away with them to the inquisition, or rack, or torture, or the like.

And the Turk, he cries, Conform, conform to his image, which Mahomet hath set up,
and to their Alcoran.

And did not the heathen emperors cry, Conform, conform, and persecute the christians,
because they could not conform to their idol images, which they had set up?

And the Protestant, he cries, Conform, conform, or else persecute and imprison,
as the many jails do testify.

And the Presbyterian, he cries, Conform, conform to his image, the directory,
or else he will hang them on his gallows, and cut off the ears, banish, whip,
and spoil the goods of all such as will not conform;
as witness the Presbyterian priests and magistrates in New England;
and also in Old England they were bad enough, who cried, Conform,
conform to their directory.
And yet they confess also,
that they have not the same spirit and power that the apostles had.

And the Independents, they cry, Conform, conform to their image,
their church faith they made at the Savoy in eleven days`' time;
and so would have all to conform to their church, way, faith, and worship,
and give their priests maintainance and tithes,
or else they will fill their prisons also with non-conformists,
and there keep them till death, and have made many widows and fatherless.

And the Anabaptists, they cry, Conform, conform to their image, and be of their church,
or else persecute.

So all these cry, Conform, conform, conform; but the apostle saith, '`Touch not,
taste not, handle not the doctrines, ordinances, and commandments of men,
and the rudiments of the world; but be conformed to the image of the son of God,
and be conformable to his death, and be ye not conformable to the world;
but be ye transformed,`' etc.

So every one that gets uppermost, and gets the staff of authority,
commands people to put into his bag, and to feed their priests with tithes,
and set maintainance, etc.
And the priests cry,
'`The law of the land requires it.`' But no law or command of Jesus requires it,
who said, '`Freely you have received, freely give.`'

Hath it not been the beast and the whore that did compel all, with their carnal weapons,
to conform to their images?
But Christ and the apostles did not compel any to conform by carnal weapons to his image;
neither did they spoil the goods of any of those
that would not be conformable to the image of Christ.

Neither do you read that the Jews did compel any of the nations they had conquered,
to be conformable to the law of God, but they lived under them as tributaries.
But if of their own accord they would join with them in a voluntary submission,
they might.

Neither do we read that king Abimelech did go about
to compel Abraham or Isaac to conform to his religion;
or that either Abraham or Isaac went about to compel him
or any of his subjects to conform to their God and his law,
by or with carnal weapons.

Neither do we read that Pharaoh did go about to compel
by carnal weapons the children of Israel,
which sojourned in his country, to be of his religion.

Neither do we read that Joseph, when he had great power in Egypt, next unto the king,
did go about to compel any of the Egyptians to be of his religion;
or that Pharaoh did go about to compel him to his religion by carnal weapons.

Neither do we read that any of those famous fathers in the old world, from Seth to Noah,
did go about to compel with carnal weapons the stock of Cain,
to be conformable to their religion.

But all are to be conformable to the image of the son of God:
Christ destroys the devil and his works,
who is the head of all false and fallible images, and likenesses, and false ways,
religions, doctrines, ordinances, and rudiments of the world,
which are not to be touched, tasted, nor handled, and so not to be conformed unto.
For by one man`'s disobedience came sin and death unto condemnation upon all men:
and so by one man`'s obedience, Christ Jesus, is justification of life come upon all men;
and so Christ hath tasted death for every man,
that they might be conformable unto his death;
and he hath enlightened all men that come into the world,
that by it they might come to the knowledge of him,
and so to be conformable to his holy and glorious image,
who bruises the head of all the false images and likeness makers.

And his grace, which bringeth salvation, hath appeared to all men, to teach them,
that they may deny all ungodliness and unrighteousness, and the lusts of the world,
and not to he conformable unto them,
but to be conformable unto the glorious image of the son of God, in his light, grace,
truth, spirit, gospel, and faith that comes from him, the author of it.
And so be made conformable unto his death,
and to his image of righteousness and holiness;
and not to be conformable to the world`'s lusts, nor vanities, nor their images,
nor likenesses of ways, worships, doctrines, ordinances, churches, faiths, and creeds,
which they have set up with their fallible spirits;
but to be conformed to the images of the son of God,
which is the universal conformity that ought to be by all the believers in Christ Jesus,
which is the alone infallible conformity in the infallible spirit of Christ,
who is the brightness of God`'s glory, and the express image of his substance,
whose image never changes; so, a conformity to an unchangeable image,
whose image never fell, who is the brightness of the glory of God,
and the express image of the Father`'s substance.

So he is over all, and liveth forever, who is the first and last,
in whom all nations are blessed, who destroyeth the devil and his works,
and bruiseth his head, and defaceth his image, in which all nations have been cursed.

So to this glorious unchangeable image of the son of God, the second Adam,
that never fell, in whose mouth there was no guile, who came to save men`'s lives,
and not to destroy them; I say, unto his image must all be conformable,
who destroys the devil that hath destroyed men`'s lives,
because they would not conform to their false and changeable religions, ways, worships,
and faiths.

But Christ nor his apostles in the new covenant did never destroy the lives of any,
nor spoil the goods of any, because they would not be conformable to Christ`'s way,
religion, church, faith, and worship; but if they would not be persuaded,
they left them to the judgment of the Lord.

Therefore, how far are men degenerated since the apostles`' days,
from the apostles`' warfare and weapons, doctrine, faith, worship, church, and image,
that they were conformable unto?
Let them that are conformed to the image of the son of God judge.

And thus people having erred from the spirit of God and Christ, and hating his light,
and walking despitefully against the spirit of grace,
not being conformable to the image of the son of God in themselves,
but are conformable to the spirit of the world in them, which lusts to envy,
by which they have set up their doctrines, commandments, ordinances, ways, and worships,
and cried, conform, conform to them; though they be uncertain how long their way,
worship, and religion shall stand,
which hath been no longer than till another power got up over them, of another way,
religion, and worship, which calls to them to conform to their way.

And from this fallible spirit hath all the persecution and bloodshed been about religion,
and spoiling of goods, imprisonments, and banishments, since the apostles`' days,
by them who are erred from the same spirit and power the apostles were in,
and so from their spiritual weapons also.

And the apostle saith to the Galatians,
'`How turn you again to the weak and beggarly rudiments of the world,
whereunto you desire again to be in bondage?
Ye observe days, and times, and months, and years.
I am afraid of you, lest I have bestowed on you labour in vain.`' Gal. 4.

And doth not the apostle here call these beggarly elements of the world?

And did not the apostle say, while he was amongst the Jews,
and under these elements of the world, '`he was carnal, sold under sin?`' Rom. 7:14.

And did not the apostle say, '`that Christ was an high priest,
not made after the law of a carnal commandment,
but after the power of an endless life?`' Heb. 7.

And again, doth not the apostle set forth,
how that '`the first covenant had worldly ordinances,
etc. and had outward lights and lamps;
and their outward services which stood in meats and drinks, and divers outward washings,
and carnal ordinances;
and that these things were imposed upon them until
the time of restitution came?`' Heb. 9,

So, doth not the apostle call all these outward things in the
old covenant which were seen with the carnal eye,
worldly and carnal?
Which the Jews were to be conformable unto in the old covenant,
which served until the time of reformation by Christ,
who reforms people out of those carnal worldly elements
and rudiments in his new covenant of light and grace:
so that they come to be conformable to his death, and to his image;
and not to be conformable to the world`'s elementary things, which pass away.

And Christ said, '`the world hated him, and he was not of the world,
but testified against it, and therefore it hated him.`'

And he said unto his disciples, '`that they were not of the world,
as he was not of the world;`' and therefore they
were to be conformable to the image of Christ,
and not conformable to the world.

And the apostle said, '`The world by wisdom knew not God;
and the wisdom of the world is foolishness; and the fashion of this world passeth away.`'

So can people that are conformable to the image of the son of God,
who is not of the world,
be conformable to the world`'s wisdom and fashions that pass away,
and to that wisdom which is foolishness, by which they do not know God?

And, therefore, as Christ said, '`They that are of the world,
speak of the world;`' but he is not of the world
unto whose image every true believer must be conformable.

And John said, '`Whosoever is born of God, overcometh the world;
and this is the victory that overcometh the world,
even your faith,`' which faith Jesus Christ is the author and finisher of.

And he said to the true believing christians in his General Epistle, '`We are of God,
and the whole world lieth in wickedness.`'

And again, John saith, '`You have overcome the world,
because greater is he that is in you, than he that is in the world;
and they that are of the world, speak of the world, and the world heareth them;
and we are of God, and he that knoweth God heareth us,
and he that is not of God heareth not us; hereby know we the spirit of truth,
and the spirit of error.`'

So here it is clear, that John and the true church of Christ,
were conformed to the image of the son of God, and not to the world, nor their ways,
nor wisdom, by which they knew not God; but said, they had victory over the world;
and their victory was their faith: so then,
they were not like to conform to that which they had victory over.

And therefore by the world and its spirit they suffered,
for not being conformable to its ways and ordinances;
for the spirit of God cannot be conformable to the spirit of the world, nor its image,
but brings to be conformed to the image of the son of God,
whose image is the brightness of the glory of God,
and express image of the Father`'s substance.

[.asterism]
'''

The Lord hath chosen us a people to himself, and led us by his light out of darkness,
and by his power from under the power of Satan, and by his holy pure spirit, grace,
and truth, which we received of Christ Jesus, and by it to follow him,
who is not of the world; and so to walk in him, who is the new and living way,
by whom all things were made and created, who is our rest, peace, and salvation,
our rock, foundation, and mediator, who makes our peace betwixt us and God;
and he is our priest, prophet, shepherd, and bishop of our souls, in his grace, truth,
gospel, and spirit, which is come from him; by it we are joined to him;
and so through Christ, with his light, power, and spirit, we do see over all the ways,
religions and worships, and the churches,
which men that are fallen from the spirit and power that Christ and his apostles were in,
have set up; and cannot join unto, nor walk in any of their ways, religions,
and worships, but in that new and living way,
that was set up above sixteen hundred years since,
and in that faith which Christ is the author and finisher of now,
as he was in the apostles`' days;
and in that religion which was set up above sixteen hundred years since,
which is pure and undefiled before God, and keeps from the spots of the world;
and in that worship which Christ set up in the spirit and truth, which comes by him,
which he set up-above sixteen hundred years since.

And we do join to that church which is come to the heavenly Jerusalem,
and the spirits of just men made perfect, which are the living stones,
and spiritual household; not a carnal household, with their carnal Jerusalem,
and carnal worldly sanctuaries and temples.

And this church is a holy priesthood, offering up spiritual sacrifices unto God;
of which church Christ is the heavenly and spiritual head and husband;
and so their heavenly prophet, and bishop, and spiritual priest,
that lives forever in his church.

And now, we have been branded, as being Papists and Jesuits, and Popishly affected.
But be it known to all the world, that we are neither Papists nor Popishly affected;
for our religion, way, and worship, and the grace, truth, spirit, faith,
and gospel of Christ, which we walk and live in, was before the Pope,
Papists and Jesuits, and their religions and worships were.

And we have suffered in the days of Oliver Cromwell, and in his long parliament time;
and before Oliver was protector, we suffered by Papists made in Queen Mary`'s time.

And we suffered in the days of the Presbyterians, Independents, and Anabaptists,
and now by the Episcopalians.

And the chief cause of all our sufferings,
that have been by all these that have had power, was,
for denying and not joining to the Popish and Jesuitical ways,
and the relics of the Papists, which they held up and allowed of amongst them.

[.numbered-group]
====

[.numbered]
_As first,_ for our not paying the Presbyterian priests, Independents, and Baptists,
and now the Episcopalians, their tithes, easter reckonings, midsummer dues,
and mortuaries, and such like, and surplices, pulpit clothes, and cushions,
and steeple-house or old mass-house rates, and clerks`' wages, and such like services.

Now, hath not the Pope and the Papists been the founders of all these things,
and not Christ nor his apostles?
And do not all these things stink of Popery?
For Christ saith to his ministers, that he made and sent forth to preach,
'`Freely you have received, freely give.`' And the apostle saith,
he coveted no man`'s silver, or gold, or apparel;
but kept the gospel without charge;`' and declared against covetous teachers.

And Christ said, '`the outward temple should be thrown down,
and not one stone left upon another;`' for he would build up a temple of living stones,
a spiritual household, in his new covenant, whose household the true christians are.

And Stephen and the apostle said,
'`the Most High did not dwell in temples made with hands.`'

And moreover, the apostle said,
that '`the bodies of the saints were the temples of God and of Christ,
and of his holy ghost.`'

So then they were not like to mend or repair the old temple and houses,
and call them churches, when, as they said,
'`the Most High dwelt not in temples made with hands,
but their bodies were the temples of the Holy Ghost.`' And so Christ preached or prophesied,
'`that they should be thrown down;`' and the apostles preached them down, and said,
'`the bodies of the believers were the temples of the living God.`'

[.numbered]
_Secondly._
We have suffered because we would not bring our infants,
and give the priests money to sprinkle them; and church our women;
and because we would not marry with the priest, and bring him a ring to put on,
and give him money for that service.

And hath not this also been derived from the Pope, Papists, and heathen,
who married with the ring, and not from Christ and his apostles?
Which practice of theirs herein they could never prove, or make good by scripture,
from Christ and the apostles.

And also,
we have suffered for bearing our testimony against their priests`' education at schools,
and their taking of degrees, as bachelors and masters of art, and doctors of divinity,
etc. and against their garbs of white coats, and black coats,
and their being called of men masters, like the proud Pharisees, and to be called lords,
like the Gentiles.

And are not all these things from the Pope, and Papists, and the heathen?
And not from Christ and the apostles.

For Christ forbids his ministers to be called of men masters;
'`for you have but one master, even Christ;
and you are all brethren;`' and that '`they should not exercise lordship one over another,
like the Gentiles; and be called lords; for it should not be so amongst them.`'

And the apostle Peter exhorted, '`that they should feed the flock of God,
but not to be as lords over God`'s heritage,`' as in 1 Pet. 5.
'`In the world there be lords many; but to us but one Lord Jesus Christ,
by whom were all things made; and one Lord God, the creator of all; and one faith,
and one baptism;`' and Christ alone is the one saving baptiser.

And therefore, how can the Pope, and his bishops and cardinals say,
'`they are the successors of Peter,`' when they are called lords?
Which Peter forbids any of his successors to be called lords;
'`but to be examples to the flock.`' And so in this they
are transgressors of Peter`'s doctrine and command,
and Christ`'s, who hath said, '`they should not be called lords, like the Gentiles.`'

And Christ saith, '`Whom God hath joined together,
let no man put asunder.`' So he doth not say, whom the priest shall join together,
or marry with the ring; but, '`whom God joineth together, let no man put asunder.`'

But amongst the sects aforesaid, the priests have money for joining;
and will also put asunder and divorce.

[.numbered]
_Thirdly._
Because we will not bow and put off our hats, and cannot say '`you`' to a single person,
but '`thou;`' and because we will not swear at all.

And is not all this from the Pope and Papists, and not from Christ and his apostles?
For where did ever they cast any into prison for not putting off their hats to them,
though '`every knee must bow to the name of Jesus?`'

But the apostle doth not say,
that every one must bow the knee to the apostles or the pope,
and that they must be uncovered to them; for the apostle taught,
that '`they must be uncovered (in their praying or prophesying) to the Lord,
because man is the image of God.`' But he doth not say, they should be uncovered to men,
or bow the knee to them, but to the name of Jesus, and to God the Father.

[.numbered]
_Fourthly._
And because we cannot swear and take oaths, have we suffered and been cast in prison.
And hath not this come from the pope, and Papists, and heathen, and Jews too,
amongst the Christians, and not from Christ and his apostles?

For Christ said, '`Swear not at all:`' though they had sworn in the old covenant;
and they then in the old time were not to swear falsely, but truly,
and to perform their oaths to the Lord; but Christ, in his new covenant of grace,
and in his gospel, saith, '`Swear not at all; but let your yea be yea, and your nay, nay;
for whatsoever is more than this, cometh of evil.`'

And the apostle James said, '`Above all things, my brethren, swear not,
neither by heaven, nor by earth, nor by any other oath,
lest you fall into condemnation.`'

So, whether must we follow Christ and the apostles,
or the pope and his Papists and Jesuits, and the heathen, Jews,
or others that uphold their principles?

So, in most of the things and causes that we have suffered,
it hath been for bearing a testimony against Popery,
and the heathenish and Jewish inventions and traditions.

For are not tithes, easter-reckonings, and midsummer-dues,
their old mass house and clerks`' wages, with their preaching funeral sermons,
and their mortuaries, and churching of women, and sprinkling little infants,
and signing them with the sign of the cross, and god-fathers, and godmothers,
and their swearing, and their preaching for money, and by the hour-glass,
and their making of ministers at schools and colleges, with their titles of bachelors,
masters, and doctors,
and calling bishops '`gracious lords;`' and their taking of their degrees,
and their expectation of being bowed unto, and having '`you`' said to one of them,
with their distinguishing garments, and white and black coats, etc.
Is not all this trumpery, and much more of the same sort, from the pope, Papists,
heathen, or Jews, and not from Christ nor the apostles?
And have not these been, many of them,
the chief things for which we have been imprisoned and persecuted, and some banished?
And for meeting together in houses, as the apostles and saints did; yea,
Christ himself had his meetings upon mountains, and preached out of ships.
Yea, many thousands of us have suffered imprisonment and spoiling of goods;
and some were banished in Oliver`'s days, and since, for not joining to these things,
which originally came from the Papists, or heathens, or Jews;
which practice of theirs in these things we have borne testimony against,
they could never make good by scripture of the new testament.

And therefore, how can either the Presbyterians, Independents, Anabaptists,
or Episcopalians, brand us for being Papists, or Jesuitically affected,
when our sufferings have been these thirty years, or more, some of us,
for not conforming to those things aforesaid, which came from the pope and Papists,
Jews and heathens?

And they that live in those Popish things, which they cannot make good,
by the scripture of the new testament, and yet say, it is their rule,
such are Popishly affected themselves.

But we are the true Protestant Christians,
and in the same power and spirit the apostles were in,
and do protest against all that which the apostatized spirit hath set up,
which is erred from that power and spirit the apostles were in.

So the doctrines, commandments, ordinances, and traditions,
that this spirit of error hath set up,
which is erred from that power and spirit the apostles were in, we cannot touch, taste,
handle, nor join with.

[.numbered]
_5thly._
Is not all the observing of holy days, and making of holy days, as Christmas, Candlemas,
Michaelmas, Easter, Whitsontide, and their Lents,
and calling their days and months by the heathen`'s names, as is in their almanacs,
from the pope, Papists, heathens, and Jews, and not from Christ nor the apostles?

====

And have not we suffered imprisonment and spoiling of goods,
for not observing their holy days, so called?

And was it not the work and labour of the apostle
to bring people off from observing days,
months, times, and years?
And them that did go into such things, to wit, observing of days, the apostle told them,
that he was afraid he had bestowed labour in vain upon them.`'

Therefore, as I said before, how can any in truth and righteousness, brand us as papists,
when we have suffered by you that call yourselves Protestants,
for denying such Popery as you allow of;
and have spoiled our goods for not observing your Popish holy days,
and other Popish things?
And yet you say, the scripture is your rule,
when you have no such commandment in the new testament, to observe days,
nor those things aforementioned, but the contrary.

And so, for bearing a testimony,
and protesting against such things which you have not from Christ nor the apostles,
and were not set up by that power and spirit the apostles were in;
and for bearing a testimony against the works and fruits of this erring spirit,
have we suffered by you called Protestants, and by the Papists also.

So our sufferings have been because we could not
join to that which you have had from the Papists,
heathens, and Jews, and not from Christ nor the apostles.

I say, we who are of the household of the true catholic faith,
in which the church was in the apostles`' days, have suffered by you,
and been branded as Papists; whereas in truth we are the true Protestant Christians,
bearing testimony against all Popish, heathenish, and Jewish inventions,
which have been set up by that spirit which is erred
from that power and spirit the apostles were in.

So as Modes the servant was faithful over his house in the old covenant,
and the law of works; so Christ the son of God is over his spiritual house,
in his new covenant of light, life, and grace, whose house we are.

[.asterism]
'''

[.blurb]
=== Concerning the upright and good conversation of the Saints in Christ, and in heaven.

David saith, '`The wicked have drawn out the sword, and have bent their bow,
to cast down the poor and needy, and to slay such as be of an upright conversation:
their sword shall enter into their own heart,
and their bow shall be broken.`' Ps. 37:14.

Here is David`'s judgment upon such that cast down the poor and needy,
and do slay such as be of an upright conversation.

'`But whoso offereth praise, glorifieth me,`' saith the Lord;
'`and to him that orders his conversation aright,
will I show the salvation of God.`' Ps. 1:23.

So all that will see the salvation of God,
you are first to see your conversations to be ordered aright with the light, power,
and spirit of God; for the apostle saith,
'`By the grace of God we have had our conversation in the world,`' etc. 2 Cor. 1:12.

So now are all by the grace of God to have their conversation
preserved from the wickedness of the world,
which grace brings their salvation.

And the apostle saith to the Ephesians,
how that '`we all had our conversation in times past in the lusts of our flesh,
fulfilling the desires of our flesh, and of our mind;
and were by nature the children of wrath,
even as well as others.`' Eph. 2:3. And therefore he exhorts
them '`to put off concerning the former conversation the old man,
which is corrupt, according to the deceitful lusts,
and be ye renewed in the spirit of your mind,
and only let your conversation be as becomes the gospel of Christ,
etc. that ye stand fast in one spirit, with one mind,
striving together for the faith of the gospel; for our conversation is in heaven,
from whence we look for the saviour, our Lord Jesus Christ,
who shall change our vile body,
that it may be fashioned like unto his glorious body.`'
--See Eph. 4:22. Phil. 1:27, 3:20.

So here the apostles and the saints had put off their
former conversation according to the world,
whose conversation was in heaven,
where all the true saints or christians had their conversation.

And the apostle exhorted Timothy, and said,
'`Be thou an example of the believers in word, in conversation, in charity, in spirit,
in faith, in purity;`' which is a good conversation to be followed.`' 1 Tim. 4:12.

And the apostle saith to the Hebrews, Heb. 13:5,
'`Let your conversation be without covetousness;
and be content with such things as ye have; for the Lord hath said,
'`he will never leave thee nor forsake thee.`'

And James saith in his General Epistle, James 3:13-14, '`Who is a wise man,
and endowed with knowledge among you?
Let him show out of a good conversation his works with meekness of wisdom;
for where envying and strife is, there is confusion, and every evil work.`'

Now this good conversation must be showed forth in practice.

And Peter, in his General Epistle, admonishes the church to be as '`obedient children,
not fashioning yourselves according to the former lusts in your ignorance;
but as he which hath called you is holy, so be ye holy in all manner of conversation:
+++[+++Mark, all manner of conversation;]
forasmuch as ye know that ye were not redeemed with corruptible things,
as silver and gold, from your vain conversation, received by tradition from your fathers,
but with the precious blood of Christ,
as of a lamb without blemish and without spot.`' 1 Pet. 3:14-15. etc.

And in 1 Pet. 3:1. '`Likewise, ye wives, be subject to your own husbands,
that if any obey not the word,
they also may without the word be won by the conversation of the wives,
while they behold your chaste conversation, coupled with fear,`' etc.
'`Having a good conscience, that whereas they speak evil of you, as of evil doers,
they may be ashamed that falsely accuse your good
conversation in Christ.`' 1 Pet. 3:16.

Here you see the true Christians`' conversations were in Christ,
which all Christians are and ought to be;
and they whose conversations are in Christ Jesus,
are agrieved and vexed with the filthy conversations of the wicked,
as just Lot was. 2 Pet. 2:7-8.

[.signed-section-signature]
G+++.+++ F.
