[#ch5.style-blurb, short="An Encouragement for All to Trust in the Lord"]
== An encouragement for all to trust in they Lord; who hath the breath of all mankind, and their souls in his hand. And how that not a sparrow shall full to the ground without the will of the Father. By G. F.

The Lord God breathed into man the breath of life, and man became a living soul.`'^
footnote:[Gen. 2:7]
Job saith, '`In the Lord`'s hand is the soul of every living thing;
and the breath of all mankind;`'^
footnote:[Job 12:10]
and is not his hand his power?
And again Job saith, '`The spirit of God hath made me,
and the breath of the Almighty hath given me life.`'^
footnote:[Job 33:4]
And David saith, '`The earth is full of the goodness of the Lord;
by the word of the Lord, were the heavens made,
and all the host of them by the breath of his mouth.`'^
footnote:[Ps. 33:6]

And David says, '`he trusted in the Lord, and his times were in his hand.`'^
footnote:[Ps. 31:14-15]
So you may see how all things were made by the word, Christ Jesus, and who made them,
to wit, the Lord; and man`'s time is in the Lord`'s hand.

And the Lord God, '`He that created the heavens and stretched them out;
he that spread forth the earth, and that which comes out of it;
he giveth breath unto the people upon it, and spirit to them that walk therein.`'^
footnote:[Isa. 42:5]
And Job says, '`God gathers to himself man`'s spirit and breath.`'^
footnote:[Job 34:14]
So God, that gives breath and spirit unto man,
it is he that gathers his breath and spirit to himself again, who has all in his hand.
And '`the steps of a good man are ordered by the Lord, and he delights in his way.
Though he fall, he shall not be utterly cast down,
for the Lord upholdeth him with his hand:`'^
footnote:[Ps. 37:23-24]
And David says, '`O Lord, how manifold are thy works! in wisdom hast thou made them all;
the earth is full of thy riches; the great and wide seas,
wherein are things creeping innumerable, both small and great beasts;
these all wait upon thee, that thou mayst give them their meat in due season;
that thou givest them, they gather; thou openest thy hand,
and they are filled with good.`'^
footnote:[Ps. 104]
So here you may see the Lord that created all; how he takes care for all,
and gives them their meat in due season.
And all that keep their mind to the Lord with his spirit, and so with it are acquainted,
and his hand, whose breath is in his hand, they can say, '`The Lord is my strength,
and is become my, salvation;
and the voice of rejoicing and salvation is in the
tabernacle of the righteous;`' and can say,
'`The right hand of the Lord doth valiantly, and is exalted.`'^
footnote:[Ps. 118:14-15]

So every man and woman`'s hope must be in the Lord, who made heaven and earth, the sea,
and all things therein, who keepeth truth forever.

And further, David saith, '`Put not your trust in princes, nor in the son of man,
in whom there is no help; his breath goes forth, he turneth to the earth,
in that very day his thoughts perish:^
footnote:[Ps. 146:3-5]
Therefore, all are to trust in the Lord, in whose hand is their breath and life.

And Solomon, speaking of the Lord,
Prov. 3. '`how by his wisdom the Lord hath founded the earth,
and by his understanding established the heavens;`' saith,
'`The length of days are in her right hand,
and in her left hand is riches forevermore.`' Therefore,
let this wisdom into your hearts, which cries in the streets,
if you will have her riches and pleasure.

And you may see in Isaiah,
how the Lord encourages his people that are sensible
that they are the work of God`'s hand.
He saith, '`That you may suck and be satisfied with the breasts of her consolations,
that ye may milk out,
and be delighted with the abundance of her (by wit Jerusalem`'s) glory.
For thus saith the Lord, '`Behold, I will extend peace unto her like a river,
and the glory of the Gentiles shall flow like a flowing stream: then shall ye suck,
ye shall be borne and dandled upon her knees; as one whom his mother comforted,
so will I comfort you, and ye shall be comforted in Jerusalem.
And when ye see this, your hearts shall rejoice,
and your bones shall flourish like an herb,
and the hand of the Lord shall be known to his servants.`'^
footnote:[Isa. 64:66-8:11 to the end]
Is not this the heavenly Jerusalem,
the mother of all true Christians in the new covenant and new testament?

Now, the breath of all mankind is in the hand of the Lord, who made the world,
and all things therein; seeing that he is Lord of heaven and earth,
he dwelleth not in temples made with hands,`' etc.
who giveth breath and life to all things,
as the apostle says, Acts 17.,
'`And who hath made of one blood all nations of men
that dwell upon the face of the earth,
that with his breath and life they should seek the Lord, and feel after him,
and find him, though he be not far from every one of them: for in him we live, and move,
and have our being,`' as some of the heathen poets could say.

And now God that giveth breath and life to all mankind, he commands all men, everywhere,
to repent, that they might turn to him, serve and worship him, and praise him,
who has created them, and takes care for them,
both with his temporal and spiritual blessings; opens with his hand, his power,
and fills with his blessings.
For '`God hath appointed a day wherein he will judge
the world in righteousness by Christ Jesus.`'

Now, all you that have erred from the spirit of God, and so from God,
among the witches or fortune-tellers, that tell people when and how they shall die;
such were forbidden, and judged by the Lord in the old testament,
and not to be followed or hearkened to.
But God, who gives breath and life to all mankind,
who hath their life and breath in his hand, and the length of their days; he saith,
'`Look unto me all ye ends of the earth,
and be ye saved.`' So with his breath and life they must look unto the Lord,
from whence it comes, and be saved.
So he that gives them breath and life, is the Creator,
and hath their breath and life in his hand, and is the saviour,
from whom all have salvation; and they are to look unto the Lord for it,
all the ends of the earth, through Jesus Christ.

And Christ saith in his new testament, when he encourages his disciples, he bids them,
'`Fear God, etc. and be not afraid of them that kill the body,
and after that have no more that they can do.`'^
footnote:[Matt. 10:28]

And again he saith, '`Are not two sparrows sold for a farthing,
and not one of them is forgotten before God?`' And Mat.
says, '`Not one of them shall fall on the ground without the will of the Father.
Fear ye not therefore, ye are of more value than many sparrows.
For even the hairs of your head are all numbered.`'
'`Whosoever therefore shall confess me before men,
him will I confess also before my Father which is in heaven,
and before the angels of God.
But whosoever shall deny me before men, him will I deny before my Father,
which is in heaven, and before the angels of God.`'^
footnote:[Matt. 10:29-33]

Now here ye may see what Christ saith,
that a sparrow shall not fall to the ground without the will of God;
for not one of them is forgotten of God.
So that neither with your guns nor nets ye can catch a sparrow without the will of God;
for not one of them shall fall to the ground without the Father that made them.
And therefore mankind, to wit, man and woman,
which are of more value than marry sparrows, are not forgotten of God,
neither shall they fall to the ground without the will of the Father.
For Christ says, '`The hairs of your heads are numbered,`' to wit,
by the Lord that made them.
And the Lord who giveth them their breath, spirit, and life,
by which they become living souls, to live to him,
who also '`hath their breath and their souls in his hand, yea, of all mankind, as in Job.
And therefore the eternal living God is to be feared
by men and women all the days of their lives,
that they may discern the times and seasons, that are in the Father`'s hand, etc.
This is a discerning beyond the hypocrites looking
at the face of the skies for fair weather and foul.^
footnote:[Matt. 16]

And if the sparrows are not forgotten of God,
and not one of them shall fall to the ground without the will of the Father,
as it is said before;
surely men and women are of more value than many sparrows with the Lord,
'`who hath numbered all the hairs of their heads,`' and gives them breath and life,
by which they become living souls, and hath all the breath of mankind, etc. in his hand,
his power.
How can any one of them be forgotten, when the sparrows are not;
who sees and knows with his all-seeing eye?
Certainly not one of them shall fall to the ground without the will of the Father,
who hath all in his hand, to wit, his power.

And God hath appointed Christ his son to uphold all things, by whom he made the world,
who is the '`brightness of his glory, and the express image of his substance,
and upholds all things by the word of his power.`'^
footnote:[Heb. 1:2-3]
So he, by whom all things were made, is heir of all things;
and he upholding all things with the word of his power,
there is no change or fall of any thing without his will and word of his power;
and therefore every man and woman`'s faith must be in Christ, in the son of God,
the second Adam, the Lord from heaven, by whom all things were made.

For Christ saith to the Jews, '`Ye are from beneath, and I am from above;
ye are of this world, and I am not of this world.
For if ye believe not that I am he, ye shall die in your sins.`'^
footnote:[John 8:23-24]
Now this is a bad dying for people to DIE IN THEIR SINS,
that do not believe in Christ the son of God, who is the heir of all things,
and upholds all things by his word and power, by whom men and women,
and all things were made.
And such as DIE IN THEIR SINS, do not believe in him, who would redeem them out of sin,
who bruises the serpent`'s head, and destroys the devil and his works,
and reconciles to God all things in one, both things in heaven and things in earth,
and is mediator between God and man, he that is from above, and is not of the world.
And they which do not believe in Christ, that DIE IN THEIR SINS,
they cannot sleep in Christ, when they put off their earthly tabernacle,
nor die in the Lord.
For blessed are the dead which die in the Lord, etc., the spirit-saith,
that they rest from their labours, and their works do follow them.`'^
footnote:[Rev. 14:13]

Now Christ hath taught you how to believe, and what to believe in; he saith,
'`While you have the light, believe in the light,
that ye may become the children of the light.`'^
footnote:[John 12:36 etc.]
And John, in his 1st chapter, tells you what this light is, who saith,
'`The light is the life in Christ, the word, by which all things were made and created,
which enlighteneth every man that cometh into the world.`'
Now all mankind being enlightened with the light,
which is the life in Christ, the word, (who is heir of all things,
and upholds all things by his word and power,
by whom all things were made,) you that believe in his light, which is the life in him,
that is from above, and not of this world, you become children of the light,
and not of the world, and are born of God,
and do pass from death to life in Christ Jesus;
and so are grafted in him your life and foundation, and built upon him your rock;
and so Christ your root bears you.
Such die in the Lord when they put off their earthly tabernacle; such sleep in Jesus,
as the apostle saith.^
footnote:[1 Thess. 4:14]

And the apostle saith, '`For we know,
that if our earthly house of this tabernacle were dissolved, we have a building of God,
an house not made with hands, eternal in the heavens.`'^
footnote:[2 Cor. 5:1 etc.]
So this the true christians were sure of, while they were in their earthly tabernacles.
For in this we groan, earnestly desiring to be clothed upon with our house,
which is from heaven, if so be that we being clothed, we shall not be found naked.
For we that are in this tabernacle, do groan, being burdened,
not for that we would be unclothed, but clothed upon,
that mortality might be swallowed up with life.`'
This should be every true christian`'s mind.

This is the mind of all the believers in the light, the life in Christ Jesus,
by which all things were made and created; and as Christ says,
'`He that believeth in the son of God shall not perish, but have everlasting life.
And he that believeth not the son of God, shall not see life;
but the wrath of God abideth upon him.`'^
footnote:[John 3]
For how can he see life, if he doth not believe in the light;
which is the life in Christ, by whom all things were made and created.
And therefore Christ saith, '`This is the condemnation,
that light is come into the world;`' and this light is the life in Christ, the word,
who is not of the world.
And men loving darkness rather than this light, because their deeds are evil,
then they love the DARKNESS more than the LIGHT, the life in Christ,
and more than CHRIST and GOD.

And Christ saith, '`Every one that doeth evil, hateth the light,
neither cometh he to the light,
lest his deeds should be reproved.`' So they that do evil, and hate the light,
will not come to the light by which their deeds are made manifest and reproved;
and therefore such will not come to the light, which is the life in Christ;
and this light is their condemnation, that do evil, and hate it,
and will not come to it to have their evil deeds made manifest, and be reproved by it,
as before.

So they that do hate the light, and will not have their evil deeds reproved,
and love the darkness more than the light, they love the devil, the power of darkness,
more than God and Christ, who comes to destroy the devil and his works,
and bruise the serpent`'s head.
'`But he that doth the truth cometh to the light, that his deeds may be made manifest,
that are wrought in God.`'

Now this heavenly, divine light, which is the life in Christ the word,
who is from above is the light by which all men see in whom their deeds have been,
and are wrought; so that Christ might very well say,
'`If you do not believe that I am he (THE SON OF
GOD) ye shall die in your sins.`' For how can such,
that do not believe in the LIGHT, the LIFE IN CHRIST, die in the Lord,
or sleep in Christ Jesus?
How can they die otherwise but in their sins, (as Christ saith,) and are condemned,
and the wrath of God abides upon them.^
footnote:[John 8]
And they that believe in the light, which is the life in Christ, are grafted into him,
and have eternal life.
Such are they that pass from death to life, and overcome the world,
and shall not come into condemnation.
For Christ saith, '`Verily, verily, I say unto you, he that heareth my word,
and believeth on him that sent me, hath everlasting life,
and shall not come into condemnation, but is passed from death unto life.^
footnote:[John 5:24]
For, verily I say unto you, the hour is coming, and NOW IS, (mark,
NOW IS,) when the dead shall hear the voice of the son of God,
and they that hear shall live.`"^
footnote:[Ibid.
25]
And they that will not hear, but love darkness rather than light,
and will not come to the light,
nor believe in the light that they may become children of the light,
how can they but DIE IN THEIR SINS, and PERISH IN THEIR VAIN SAYINGS AND CORRUPTIONS.

And the Lord saith in Ezek.
'`I have no pleasure at all that the wicked should die;`'^
footnote:[Ezek. 18:23,32]
again, '`I have no pleasure in the death of him that dieth, saith the Lord God;
wherefore turn yourselves, and live ye.`' Now the wicked die in their wickedness,
who have gone from the spirit of God in themselves, and so from God; and, therefore,
the Lord God would have them to turn again by his spirit to him who made them,
and gives them breath and life, that they may not DIE IN THEIR SINS.
And they that are led by the spirit of God, which are the children of the Lord,
SUCH DIE IN THE LORD, and SLEEP IN JESUS.
In such, God, who is a spirit, has pleasure with them in his spirit,
that live and walk in his spirit, and die in the Lord.
But he has no pleasure in them that hate the light, the life in Christ,
whom he sent to enlighten them, and rebel against his spirit,
and so against God who gave it them: such die in their sins,
and perish in their gain-sayings; in such, God, who is a spirit, has no pleasure.
Those that rebel against his spirit, rebel against him;
for his pleasure is with them while they live and walk in his spirit, and his light,
and truth, and grace.

Concerning the BIRTH OF JESUS CHRIST, THE SON OF GOD,
he came NOT into the world with the POMP and GLORY of the WORLD,
neither went he out of the world with the POMP and GLORY of the WORLD.^
footnote:[Now concerning the birth of Christ, etc.]
It is said, when Joseph went from Galilee out of the city of Nazareth into Judea,
unto the city of David, which is called Bethlehem;
(because he was of the lineage of David,) to be taxed, with Mary his espoused wife,
being great with child; and so it was, that while they were there, (to wit,
in Bethlehem,) the days were accomplished, that she should be delivered.
And she brought forth her first-born son, and wrapped him in swaddling clothes,
and laid him in a MANGER, because there was NO ROOM FOR THEM IN THE INN.
And there were in the same country shepherds abiding in the field,
watching over their flocks by night, etc.
And the angel of the Lord appeared to them, etc. and told them,
'`Unto you is born today in the city of David, a saviour, which is Christ the Lord.
And this shall be a sign unto you, YE SHALL FIND THE BABE WRAPPED IN SWADDLING-CLOTHES,
LYING.
IN A MANGER.`'^
footnote:[Luke 2]
So you do not read here, that Mary had so much as a midwife; and if she had not one,
she had the same power, the same holy ghost which came upon her;
and the same power of the Highest, which did overshadow her,
was able to help her to bring forth her first-born, which is called the son of God.

AND IF CHRIST AS YOU DO SAY, WAS BORN AT Christmas, AND Mary WRAPPED HIM,
AND LAID HIM IN A MANGER, IT WAS A COLD PLACE, AND A COLD TIME IN THE YEAR:
YOU DO NOT READ THAT Mary HAD SO MUCH AS A FIRE.
And again, WHEN CHRIST WAS CRUCIFIED AT THE TIME OF THE PASSOVER, WHICH YOU CALL Easter,
(WHICH IS A GOOD WHILE AFTER Christmas,) IT WAS COLD WEATHER;
FOR Peter WARMED HIMSELF BY THE FIRE, WHEN THE HIGH-PRIESTS WERE EXAMINING CHRIST.

Now here you see the son of God, and the Lord of glory,
what entertainment he had at his birth, amongst them that were in the pomp of the world.
He that said, he was from above, his cradle was a manger.
You know a manger is in a stable, where you feed your horses in.
And who were Mary and Christ`'s visitors,
but the country shepherds that watched their flocks by night?
There is no talk of scribes, high-priests, or Pharisees.
So see what entertainment the Lord of life found at his coming into the world,
without the pomp of the world, wrapped in swaddling-clothes,
a manger instead of a cradle.
Oh! the proud and lofty ones might say, this place was good enough;
there was no room within for a carpenter`'s wife and her son;
the innkeepers could find no room for Christ, the saviour, and Mary.

And what could the poor country shepherds present unto him,
that watched all night the sheep?
But such God made instruments to come to visit Christ the Lord and saviour; yea,
and declare him abroad.
And did not the Jews in a despising way, say, '`Is not this the carpenter`'s son?^
footnote:[Matt. 13:55]
Is not his mother called Mary?`' And in Mark, did not the Jews deride him, and say,
'`Is not this the carpenter, the son of Mary?`'^
footnote:[Mark 6:3]
So they called Christ the carpenter;
but they did not know that he was to build up the
fallen house of Adam with his power and spirit.
For the apostle Peter says, '`Ye are built up a spiritual household;`'^
footnote:[1 Pet. 2:5]
and the author to the Hebrews; '`He that buildeth all things is God.`'^
footnote:[Heb. 3:4]
And again, '`For he (Abraham) looked for a city, whose builder and maker is God.`'^
footnote:[Ibid.
11]
And the apostle Paul says, speaking of God and Christ, '`After this I will return,
and will build again the tabernacle of David, which is fallen down;
and I will build again the ruins thereof, and I will set it up.^
footnote:[Acts 15:16]
And who is this builder but Christ Jesus with his power and spirit?
Again, '`And now, brethren, I commend you to God, and to the word of his grace,
which is able to build you up,
and to give you an inheritance among all them which are sanctified.`'^
footnote:[Acts 20:32]
And the Lord spake by the prophet Isaiah concerning Christ, and said,
'`Is it a light thing that thou shouldst be my servant to raise up the tribes of Jacob,
and to restore the preserved of Israel?
I will also give thee for a light to the Gentiles,
that thou mayst be my salvation to the ends of the earth.^
footnote:[Isa. 49:6]
Again: and who is he that shall build up the waste places,
and raise up the foundation of many generations,
and is called the '`repairer of the breach, and the restorer of paths to dwell in?`'^
footnote:[Isa. 58:12]
And when the devil tempted Christ, and showed him all the kingdoms of the world,
and the glory of them, he said to him, '`All these things will I give thee,
if thou wilt fall down and worship me.`'^
footnote:[Matt. 4]
But Christ said unto the devil,
'`Get thee hence Satan.`' It seems he showed him the glory of the world,
which he would have given Christ, if he would have fallen down and worshipped the devil,
in whom there is no truth.
But Christ says, '`The devil was a murderer from the beginning,
and abode not in the truth, because there is no truth in him; when he speaks a lie,
he speaks of his own, and is the father of it.`'^
footnote:[John 8:44]
So it was not like for Christ, the truth, to bow to and worship him,
in whom there is no truth.

Now, what is the glory of the world?
John saith, '`Love not the world, nor the things that are in the world;
if any man love the world, the love of the Father is not in him.
For all that is in the world, the lust of the flesh, the lust of the eye,
and the pride of life, is not of the Father, but of the world.
And the world passeth away, and the lusts thereof; but he that doth the will of God,
abideth forever.`"^
footnote:[1 John 2:15-17]

Now, you see here, what is of the world, and what is its glory,
which the devil that overcame Adam and Eve by his lies,
in telling them they should be as gods, if they did eat that which God had forbidden.
He set upon Christ the truth; but as Christ says,
'`He found nought in him.`' Now the glory of the world, which is the lusts of the flesh,
the lust of the eye, and the pride of life, with the pomps and vanities of the world,
which are not of God the Father, but of the devil,
which he had begotten in the kingdoms of the world, and which was their glory,
who disobeyed God: this glory of the world the devil would have given to Christ,
who is the life and the truth, if he would have fallen down and worshipped him, to wit,
the devil, in whom there is no truth.
But Christ the truth bruiseth the serpent`'s head, and destroys the devil and his works.

And Christ set up a worship in the holy spirit of God,
and in the truth which the devil is out of; for there is no truth in him,
as Christ saith.
So they that worship God in his spirit and truth,
worship in that which the devil is out of, and is not in him, neither can he get into it.
And therefore, that which is of the devil, who is out of the truth,
the glory of the world, which the devil said he would give to Christ,
if he would have worshipped him, is that, which is not of the Father, but of himself,
'`the lust of the flesh, the lust of the eye, and the pride of life,`' which pass away.
For God Almighty created all things; and the earth is the Lord`'s,
and the fulness thereof and he gives the increase.
So the glory of all the creatures, and the glory of all the creation is the Lord`'s,
and he doth beautify them.
For the devil could not give Christ the glory of a thistle, the glory of a nettle, nay,
not the glory of any weed; for these are the Lord`'s, with the earth,
and the fulness thereof; and the glory of all his creation is the Lord`'s,
who is God in heaven, and in the earth, to be served and worshipped above all.

And Christ saith, '`For I say unto you, that Solomon in all his glory,
was not arrayed like one of these lilies.`'^
footnote:[Luke 12:27-28]
So it is God that arrayeth the lilies with glory,
that doth exceed Solomon in all his glory.
And Jesus Christ, who is a greater than Solomon, hath spoken it,
by whom all things were made and created, who is greater than Solomon,
and whose glory exceeds all the glory of the creatures in the creation;
'`who is the brightness of God`'s glory, and the express image of his substance,
upholding all things by the word of his power,`'^
footnote:[Heb. 1:3]
by whom all things were made;
who is glorified with the Father with the same glory
that he had with him before the world began,
and before the creatures were made, and their glory.

So here you see the glory of Christ, and the glory of Solomon,
and the glory of the arrayed lily, which was beyond all Solomon`'s glory,
for the lily was arrayed by the Lord.
But the glory of Christ is beyond the glory of the lily,
and the glory of the whole creation, as is said before.

And likewise here you may see the glory of the kingdoms of the world,
which the devil would have given to Christ;
which he had begotten in the sons and daughters of Adam and Eve, who disobeyed God;
which he would have given to Christ, if he would have fallen down and worshipped him:
which POMP and GLORY of the WORLD, is the LUST OF THE FLESH, THE LUST OF THE EYE,
AND THE PRIDE OF LIFE, which is not of God the Father that sent Christ.
Therefore Christ came not into the world with any of the POMPS and GLORY,
neither would he have any of them, when the devil proffered them to him;
for he came to destroy and bruise his head; and testified against the world,
that their works were evil;
and therefore he was not like to receive that which was not of his Father,
(nor none of his works, for that he testified against,) but of the god of this world,
which lies in wickedness, and of his works, that Christ came to destroy.
And so he was not like to TAKE THAT which he was come to DESTROY,
and which was not of his Father.
Nor are his followers to receive that which is not of the Father,
lest they worship the devil, and go from God`'s holy spirit and truth,
and love that which will keep the love of the Father out of them.
And they that walk in the truth, walk in Christ Jesus.

Now after the Lord Jesus had gone through all his temptings,
and all the revilings and evil speeches from the Jews, priests, scribes, and Pharisees;
and even his preaching and manifesting himself to
be the son of God by his signs and miracles;
and when they by their wicked tongues desired the murderer,
and by wicked hands had crucified the Lord of life, (who were in the murdering spirit,
and lusts and pomps of the world,) Joseph of Arimethea, a counsellor, (a good man,
and just, who had not consented to the counsel and deeds of the Jews,
who also himself waited for the kingdom of God,) went to Pilate,
and begged the BODY OF JESUS, which they had crucified between TWO THIEVES.
AND Joseph TOOK IT DOWN, AND WRAPPED IT IN A LINEN CLOTH, AND LAID IT IN A SEPULCHRE,
THAT WAS HEWN IN STONE, WHERE NEVER MAN LAY BEFORE.
So you don`'t read here, that Christ had so much as a COFFIN, as Joseph, Jacob`'s son,
had. Gen. 1:26.

So you see what entertainment the Lord of glory had, when, he came into the world,
a MANGER instead of a CRADLE.
And when he went out of the world, the scripture doth not say, he had so much as a COFFIN.
Joseph of Arimethea wrapped his body in linen, and laid it in a sepulchre in a garden.
And you may see in John what outcries were among the Jews and the priests, crying,
CRUCIFY HIM, CRUCIFY HIM.
And though Nicodemus, and some of the women, did come,
and brought their myrrh and other spices, as the manner of the Jews is to bury;
yet when out of the world, he was buried by Joseph of Arimethea, a counsellor,^
footnote:[John 19]
to fulfill the scripture, which says, HE MADE HIS GRAVE WITH THE RICH; but doth not say,
that he had so much as a COFFIN with a white and a BLACK cloth upon it.

So you may see here, our Lord and saviour, the son of God, the King of kings,
and Lord of lords, who hath all power in heaven and earth given unto him,
he was not carried to his sepulchre with a GILDED COFFIN,
WITH A GREAT WHITE AND BLACK CLOTH OVER IT, WITH ARMS OR SCUTCHEONS UPON IT,
AND MANY PRIESTS AND PEOPLE FOLLOWING IN BLACK CLOTHES, AND BLACK SCARPS ON THEIR HATS,
PRETENDING MOURNING, and have GOLDEN RINGS GIVEN TO THEM,
and TWIGS OP ROSEMARY IN THEIR HANDS, and RINGING OP BELLS,
which is more like going to a WEDDING than to a BURYING,
in the pomp and glory of the world.
But instead of that, Christ had a company of MOCKERS; yea, the chief priests, scribes,
and elders mocked him, saying, '`If he be the son of God,
let him come down from the cross, and we will believe him: he trusted in God,
let him deliver him now, if he will have him; for he said, I am the son of God.
He saved others, himself he cannot save.`'^
footnote:[Matt. 27:40 etc.]
See what blasphemy is here against God and his son, by the Jews and the priests,
who in words profess God, and the Messiah to come;
but in life and works denied them both.
'`For he that denieth the son, hath not the Father; but he that acknowledges the son,
hath the Father also.
Let that therefore abide in you, which you have heard from the beginning:
if that which you have heard from the beginning, shall remain in you,
ye also shall continue in the son, and in the Father,`' etc.^
footnote:[1 John 2:23-24]

And all you that say, THAT WE BURY LIKE DOGS,
because that we have not superfluous and needless things upon our coffins,
and a white and black cloth with scutcheons, and do not go in black,
and hang scarfs upon our hats, and white scarfs over our shoulders, and give gold rings,
and have sprigs of rosemary in our hands, and ring the bells;
how dare you say that WE BURY OUR PEOPLE LIKE DOGS,
because we cannot bury them after the vain pomps and glory of the world?
Whereas, ye do not read, that Christ, the prince of life, our Lord and saviour,
had any of these things, neither when he came into the world,
nor when he went out of the world; and refused the pomp and glory of the world,
when the devil tempted him with it.

Now, all people, come to learn of Christ,
who hath enlightened you with the life in himself, and believe in it,
that you may become children of the light:
for grace and truth is come by Jesus into your hearts and inward parts,
that with his grace and truth you may learn of Christ, who is meek and low in the heart,
and follow him, who is not of this world, and hear his voice,
and he will lead you into the pastures of life.
He that came into the world not with any pomp, nor lust, nor glory of the world,
neither did he go out of the world with the glory, pomp, or lust of the world,
(as is said before,) who was not of the world, who is the prince of life and peace.
And therefore follow not the pomps or glory of the
world at your children`'s coming into the world;
nor breed them up in the pomps and glory of the world the time while they live,
nor use them at going forth out of the world; but follow Christ Jesus,
who is not of the world; who is your redeemer, your saviour, your way, your truth,
and life, your bishop, your shepherd, your priest, your prophet;
and let him rule in your hearts by faith, who will give you life abundantly,
who is from above and not from below, that you may be built upon him the living rock,
and foundation of God that stands sure.
Amen, Amen, saith my soul.

[.signed-section-signature]
G+++.+++ Fox.
