[#ch6.style-blurb, short="Epistle to All Christians, Jews, and Gentiles"]
== An epistle to all Christians, Jews, and Gentiles, showing how that God dwells not in temples made with hands.

'`Thus saith the Lord, heaven is my throne, and earth is my footstool:
where is the house that you will build unto me,
and where is the place of my rest?`' This the Lord
said unto the Jews that built the temple. Isaiah 66:1.

And Solomon saith,
'`The heaven of heavens cannot contain God,`' how much less the house that he built? 1 Kings 8:27.
And the same in the 2d of Chronicles 6:18.

And again, Steven saith to the Jews`' high-priest, when he was examining him,
'`Though Solomon built an house for the Lord;
howbeit the Most High dwells not in temples made with hands; for heaven is God`'s throne,
and earth is his footstool; what house will ye build me, saith the Lord,
or where is the place of my rest?
Hath not my hands made all these things?
Ye stiff- necked and uncircumcised in hearts and ears,
ye do always resist the holy ghost; as your forefathers did, so do ye.`'

Now here all may see, that it was the stiff-necked and uncircumcised in hearts and ears,
that were the persecutors, as in the next verse, that did resist the holy ghost;
and therefore their bodies, in that state, were not like to be temples of the holy ghost;
as in 1 Cor. 6:19. And, therefore, these persecutors that did resist the holy ghost,
which comes from the Father and the son, were the criers up of the outward temple;
they were not like to see God, as Steven did,
who dwells not in the temples made with hands, and heaven to be his throne,
and earth his footstool, who resisteth his holy spirit that proceeds from him,
by which God is seen and known.

And the apostle Paul saith, '`God that made the world and all things therein,
seeing that he is Lord of heaven and earth, dwelleth not in temples made with hands,
neither is worshipped with men`'s hands, as though he needed any thing,
seeing he giveth to all, life, and breath, and all things,
and hath made of one blood all nations of men, for to dwell on the face of the earth, etc.
That they should seek the Lord, if happily they might feel after him, and find him,
though he be not far from every one of us; for in him we live, and move,
and have our being,`' etc.
Acts 17.

So you may see, here are many witnesses before-mentioned, that God that made the world,
and all things therein, who is Lord of heaven and earth,
dwelleth not in temples made with hands, but as the prophets, Christ,
and the apostles say, '`heaven is God`'s throne,
and the earth is his footstool.`' Matt. 5:34-35.

So, all come to know God,
who hath made of one blood all nations of men for to dwell on the face of the earth;
he gives to you all life and breath, and all things; I say,
all to know him by his spirit which he poureth upon all flesh, heaven to be his throne,
and earth to be his footstool; yea, all that dwell upon the face of the earth,
know the earth that you dwell upon, and walk upon, to be God`'s footstool,
and heaven to be his throne, who is Lord of heaven and earth,
who gives you breath and life, and poureth his spirit upon you, or in you.
Joel 2. and Acts 2. That with his spirit you may know the day is come that Joel spoke of;
and that with his spirit you may all know, that God hath poured his spirit upon you,
or in you, that with it you may live in God, and move in God, and have your being in God,
who is Lord of heaven and earth; and heaven is his throne, and earth is his footstool,
upon which face of the earth you dwell, and walk:
and so all to see and know that ye are the temples of the living God, as God hath said,
'`I will dwell in them, and walk in them, and I will be their God,
and they shall be my people.`' 2 Cor. 6:16. and Lev. 26:12.

And thus saith the Lord, who dwells not in temples made with hands,
but the saints that are lead by the holy ghost are the temples of God and the holy ghost;
for the Lord saith,
'`the children of Israel and Judah had provoked him to anger
with the works of their hands.`' The Lord saith,
'`For this city, (to wit Jerusalem,
and the temple,) hath been to me a provocation of my anger, and of my fury,
from the day that they built it, even unto this day, (to wit Jerusalem,
and the temple,) that I should remove it from before my face,
(saith the Lord,) and destroy it,`' etc.
Jer. 32.

So you may see here, that such as resisted the holy ghost,
were crying up outward Jerusalem, and the outward temple,
who were the stiff-necked persecutors, and uncircumcised in hearts and ears,
as you may see in the prophet`'s time, and in Isaiah`'s time, and in Christ`'s,
Steven`'s, and the apostle Paul`'s time; and such uncircumcised in hearts and ears,
that are persecutors, that did and do resist the holy ghost now,
are crying up outward temples, and imprisoning, and persecuting,
and spoiling the goods of people now,
because they will not give money to mend their temples or churches,
though they make no use of them; and yet they say,
the gates of hell shall not prevail against their church; and yet daily want repairing,
either by reason of weather, storms, or thunder!
And though the Lord tells them by his prophet, and Steven, and his apostles,
'`that God that made the world, and all things therein,
dwells not in temples made with hands, but heaven is his throne,
and earth is his footstool,
and he is the Lord of heaven and earth.`' And saith of his people in these words, '`What?
Know you not that your bodies are the temples of the holy ghost, which is in you,
which you have of God.`' And again, '`For ye are the temples of the living God,
as God hath said, I will dwell in them, and walk in them, and I will be their God,
and they shall be my people, and I will be a Father to you,
and ye shall be my sons and daughters, saith God Almighty.`' Jer. 31:33. And,
therefore, all that receive the holy ghost,
know your bodies to be the temples of the living God, and this holy ghost,
and heaven to be God`'s throne, and earth his footstool,
and that you dwell and walk upon his footstool, and that you do live and move,
and have your everlasting being in God, who dwells not in temples made with hands;
but God dwells and walks in you his temple, and he is your God and Father,
and you are his people, and the sons and daughters of God Almighty.
So that every one may truly say, I live, and move, and have my being in God;
heaven is his throne, and earth is his footstool, which I naturally dwell and walk upon,
and, spiritually, in God I live, and move, and have my being, to his praise and glory,
who is the Lord of all, both in heaven and earth, from everlasting to everlasting,
blessed and praised forever.
Amen.

One God and Father of all, who is above all, and through all, and in you all. Eph. 4:6.
All people know God the Father so to be.

[.signed-section-signature]
G+++.+++ Fox.

[.signed-section-context-close]
The 4th of the 7th Month, 1682.
