[#ch7.style-blurb, short="Concerning Persecution in All Ages"]
== Concerning Persecution in all ages to this day. How he that was born after the flesh, persecuted him that was born of the Spirit; and even so it is now: yea, and all that will live Godly in Christ Jesus, shall suffer Persecution. Mark, all them that will live Godly; not them that will live Ungodly, out of Christ Jesus. 2 Tim. 3:12. For unto you it is given in the behalf of Christ, not only to believe on him, but also to suffer for his sake. By G. F.

The spirit itself beareth witness with our spirits, that we are the children of God;
if children, then heirs of God, and joint heirs with Christ.
And if so be that we suffer with Christ, that we may be also glorified together;
for I reckon, that the present sufferings of this time,
are not worthy to be compared with the glory which shall be revealed in us.
Who shall separate us from the love of Christ?
Shall tribulation, or distress, or persecution, or famine, or nakedness, or peril,
or sword?
As it is written, '`For Christ`'s sake we are killed all the day long,
we are accounted as sheep for the slaughter; nay,
in all these things we are more than conquerors, through Christ that loved us.
For I am persuaded, that neither death, nor life, nor angels, nor principalities,
nor powers, nor things present, nor things to come, nor height, nor depth,
nor any other creature, shall be able to separate us from the love of God,
which is in Christ Jesus our Lord.`'

Here is and ought to be the noble resolution of the
true and faithful christians in Christ Jesus;
and as the apostle said to the Corinthians, '`We are made a spectacle unto the world,
and angels, and men, etc.
And we are counted fools for Christ`'s sake, and we are buffeted,
and have no certain dwelling place; and being reviled, we bless; and being persecuted,
we suffer it; being defamed, we entreat.
We are made as the filth of the world, and as the offscouring of all things;
but the Lord comforts us in all our tribulations;
for as the sufferings of Christ abound in us,
so our consolation also abounds with Christ.`' 2 Cor. 1:5-7.

And so it is no new thing for the christians now, to be troubled on every side,
yet not distressed; perplexed, but not in despair,
for our light afflictions which are but for a moment,
worketh for us a far more exceeding and eternal weight of glory;
and though our outward man perish,
yet our inward man is renewed day by day.`' Blessed be the Lord forever.

And as the apostle saith, '`I take pleasure in infirmities, in reproaches,
in necessities, in persecutions,
in distresses for Christ`'s sake.`' And here the apostle triumphed over all,
which should be every true christian`'s practice.

And you may read how Paul said, How that beyond measure he persecuted the church of God,
and wasted it; but when he was converted and became a member of Christ`'s church,
then he preached that faith which he sought to destroy; so you may see, as it is written,
'`he that`'s born after the flesh,
persecutes him that is born after the spirit;`' even so it is now.
Therefore, whatever Christendom doth profess and talk, the birth must be minded,
of what birth you are; if it be the birth of the flesh,
he will persecute him that is born after the spirit, the true believers in Christ;
for '`unto you it is given in the behalf of Christ, not only to believe on him,
but also to suffer for his sake.`' So this gift is not only to believe,
but also to suffer for his sake,
and so count all things but loss for the excellency of the knowledge of the Lord Jesus,
'`for whom I suffer the loss of all things,
and count them but dung that I may win Christ, and be found in him, that I may know him,
and the power of his resurrection, and the fellowship of his sufferings,
being made conformable unto his death.`' To this all should mind to be conformable,
and know the fellowship in his sufferings.

And the apostle encourages the Thessalonians, who saith, '`We ourselves glory in you,
etc. for your patience, and faith in all your persecutions, and tribulations,
that ye endure, which is a manifest token of the righteous judgments of God,
that ye may be worthy of the kingdom of God, for which ye also suffer,
seeing it is righteous with God to recompense to them that trouble you;
and so you that are troubled, rest with us, (saith the apostle,) therefore brethren,
we are comforted over you in all your afflictions and distresses for your faith.
Stand fast in the Lord, that no man should be moved by these afflictions,
for yourselves know that we are appointed thereunto,
(saith the apostle,) for we told you before that we should suffer tribulations,
even as it is come to pass.`' For Christ hath suffered; and being tempted,
he is able to succour them that are tempted, in all their sufferings.
And though Christ were a son, yet learned he obedience by the things which he suffered,
and being made perfect, he became the author of eternal salvation,
to all them which obey him; and so if we suffer with him, we shall reign with him.
And remember them that are in bonds, as bound with them; and them which suffer adversity,
as being yourselves also in the body, in bonds.
Here is a sensible feeling of one another that are born of the spirit,
and a fellowship in sufferings, who are persecuted by that spirit born of the flesh.

And the apostle saith to the Hebrews, '`Call to remembrance the former days,
in which after ye were illuminated, ye endured a great fight of afflictions,
partly while you were gazing-stocks, both by reproaches and afflictions,
and partly while you became companions of them that were so used;
for ye had compassion of me in my bonds, and took joyfully the spoiling of your goods,
knowing in yourselves that you have in heaven a better and enduring substance.
Cast not away your confidence, which hath great recompense of reward,
for ye have need of patience, that after you have done the will of God,
you may receive the promise; but if any draw back, (to wit,
in the time of sufferings,) the Lord`'s soul hath no pleasure in them.`'

Moses, by faith, chose rather to '`suffer afflictions with the people of God,
than to enjoy the pleasures of sin for a season,
esteeming the reproaches of Christ greater riches than the treasures in Egypt;
for he had respect unto the recompense of reward, and by faith forsook Egypt,
not fearing the wrath of the king,
for he endured as seeing him who is invisible.`'
And ye may see what cruel trials of mockings,
scourges, bonds, and imprisonments, and afflictions, and torments,
the saints went through, in the 11th of Hebrews.

And saith Peter, 1 Pet. 2:20. '`If when you do well, and suffer for it,
ye take it patiently; this is acceptable with God, for even hereunto were ye called.
If a man for conscience sake towards God suffer grief; this is thank-worthy,
because Christ also suffered for us, leaving us an example,
that we should follow his steps, who when he was reviled, he reviled not again;
when he suffered, he threatened not, but committed himself to God who judges righteously;
for Christ hath once suffered for sin, the just for the unjust,
that he might bring us to God.
Forasmuch then as Christ hath suffered for us in the flesh,
arm yourselves likewise with the same mind;
for he that hath suffered in the flesh hath ceased from sin.
But the God of all grace who hath called us into his eternal glory,
(saith the apostle,) by Christ Jesus, after that you have suffered awhile,
make you perfect, establish, strengthen, and settle you; cast all your care upon God,
for he careth for you; and rejoice,
inasmuch as you are made partakers of Christ`'s sufferings,
etc. and think it not strange concerning the fiery trials, which are to try you,
as though some strange thing had happened unto you;
for if ye be reproached and suffer for the name of Christ, happy are ye,
for the spirit of glory and of God rests upon you: on their part, he is evil spoken of,
but on your part, he is glorified.`' If any man suffer as a christian,
let him not be ashamed, but let him glorify God on this behalf:
wherefore let them that suffer according to the will of God,
commit the keeping of their souls to him in well doing, as to a faithful Creator;
and if ye suffer for righteousness sake, happy are ye.
And '`be not afraid of their terror, neither be troubled, having a good conscience,
that whereas they speak evil of you, as evil doers,
they may be ashamed that falsely accuse your good conversation;
for it is better if the will of God so be, that ye suffer for well-doing,
than for evil-doing;
for we both labour and suffer reproach because we trust in the living God,
who is the saviour of all men, especially of them that believe.`'

And the apostle said, '`He was appointed a teacher of the Gentiles,
for the which cause he also suffered,`' etc. but he was not ashamed,
for he knew in whom he believed; and said, though he suffered as an evildoer,
even unto bonds; but the word of God is not bound; nay,
the eternal word of God that lives, and abides, and endures forever,
by which all things were made and created,
this word of God cannot be bound by that which was created by it,
and doth not live and endure forever; therefore, saith the apostle,
'`I endure all things for the elect`'s sake,
that they may also obtain the salvation which is in Christ Jesus, with eternal glory.
It is a faithful saying, if we be dead with Christ, we shall also live with him;
and if we suffer with Christ, we shall also reign with him; and if we deny him,
he also will deny us,`' etc.

And you may see what persecutions and afflictions came upon the apostle at Antioch,
and at Iconium, and at Listra, what persecutions he endured;
but out of them all the Lord delivered him; yea,
and all that will live godly in Christ Jesus, shall suffer persecution.
Mark, shall, if they live godly.
But evil men and seducers shall wax worse and worse, deceiving and being deceived;
therefore he exhorts Timothy, to '`watch in all things,
and endure afflictions,`' etc. for he was ready to be offered up,
for the time of his departure was at hand, and he had fought the good fight,
and finished his course, and kept the faith,
and there was a crown of righteousness laid up for him, which the Lord,
the righteous Judge will give him at the last day, and not to him only,
but unto all them also that love his appearing;
for God hath not given to us a spirit of fear, but of power, of love,
and of a sound mind: therefore the apostle saith unto Timothy,
'`Be not thou therefore ashamed of our Lord, nor of me his prisoner,
but be thou a partaker of the affliction for the gospel, according to the power of God,
who hath saved us, and called us by a holy calling,`' etc.
And John saith, '`I know thy works, tribulations, and poverty; but thou art rich;
fear none of those things which thou shalt suffer.
Behold, the devil shall cast some of you into prison, that you may be tried,
and ye shall have tribulation ten days; but be thou faithful to death,
and I will give thee a crown of life:`' this was spoken to the church in Smyrna.
And you may see in the 11th chap.
how the witnesses of Christ suffered, and when they had taken away their lives,
and the dead bodies lay in the streets of the great city,
which is spiritually called Sodom and Egypt,
(so not naturally called so,) where Christ our Lord and saviour was crucified;
that was the great professors of the letter, the Jews, before the witness was slain;
but after three days and a half, the spirit of life from God entered into the witnesses,
and they stood upon their feet, which frightened their enemies;
and the witnesses were called up to heaven,
and the same hour there was a great earthquake, and the tenth part of the city fell,
and was shaken down; so here was the reward upon the city and the persecuting citizens.

And again, you may see how the dragon persecuted the woman, the true church,
which brought forth the man child,
after he was cast out of heaven by Michael and his angels;
but the woman (or true church) was nourished for a time, and times, and half a time,
in the wilderness; and the earth helped the woman; and the earth opened her mouth,
and swallowed up the flood, which the dragon cast out of his mouth after her;
and the dragon was wroth with the woman,
and went to make war with the remnant of her seed, which kept the commands of God,
and have the testimony of Jesus.

Now you may see how the devil, the dragon, and all his followers persecute,
and what his wrath is against, the true church, the woman,
that brought forth the man child, and they that kept the commands of God,
and have the testimony of Jesus Christ.
And then the dragon he gave his wicked persecuting power to the beast,
and he also was to continue forty-two months;
and he got up in such a rage in the devil`'s power,
that he opened his mouth in blasphemy against God, to blaspheme his name,
and his tabernacle, and them that dwell in heaven; not them that dwell upon the earth,
for all that dwell in the earth worship him,
but those whose names are written in the book of life of the Lamb,
slain from the foundation of the world, to wit, they do not worship him.
He that hath an ear to hear, let him hear.

But what became of the great city, and the whore, or the false church, and the beast,
and the dragon, with all his false prophets?
Are not they at the end burned; and cast into the lake of fire,
and the Lamb and the saints have the victory?

And David declareth, how he was persecuted, and said,
'`Let them be confounded and put to shame that seek after my soul;
let them be as chaff before the wind, etc.
Let their way be darkness, and slippery, etc.
False witnesses rise up, and lay to my charge things that I knew not;
they rewarded him evil for good, to the spoiling of his soul;
and his adversaries gathered themselves together against him,
with hypocritical mockery in feasts; they gnash upon me with their teeth, yea,
they open their mouths wide against me, and say, Aha, Aha,
etc. but God will save his afflicted people,
and bring down the high looks of them that afflict them.`' Ps. 18. Verse 27.

And David mourned by reason of affliction, and said, '`I am afflicted,
and ready to die from my youth upward,`' etc. and said,
'`Lord remember David in all his afflictions;`' and he said,
'`The wicked in his pride persecuted the poor; my times are in thy hand;
O Lord! deliver me from the hand of my enemies,
and them that persecute me.`' And also David cried to the Lord, and said,
'`How many are the days of thy servant?
Wilt thou execute judgment on them that persecute me?
They persecute me wrongfully; help thou me; the proud have digged a pit for me,
which are not after thy law;`' (and they that do
so now are not after thy gospel.) And David said,
'`O Lord my God! in thee I put my trust;
save me and deliver me from all them that persecute me; for the Lord heareth the poor,
and despiseth not the prisoners; let the heaven and earth praise him, the sea,
and everything that moveth therein.`' And David saith,
'`they that sat in the gate spoke against me,
and I was the song of the drunkards;`' and do not
the drunkards make songs of God`'s people now?

And you may see the sufferings and afflictions of Job by the Caldeans, and Sabeans,
and the trials and temptations of his wife, and his pretended friends;
and also he saith in his afflictions, '`They that are younger than I,
have me in derision,
whose fathers I would have disdained to have set with the dogs of my flocks,
the children of fools, children of base men; now am I their song, yea,
I am their by-word, they abhor me, etc. and spare not to spit in my face;
upon my right hand rise the youth, they put away my feet, they rise up against me,
etc. they mar my path, and set forward my calamity,`' etc.
But you may see how the Lord delivered Job out of all his afflictions and miseries;
for it was always the wicked that abused the righteous,
in their sufferings and afflictions.

And Jeremiah said, '`O Lord! my strength, and my fortress,
and my refuge in the day of affliction!`' The Lord is the fortress, and refuge,
and strength of all his people in the day of their afflictions, and persecutions;
and did not the Lord confound all Jeremiah`'s persecutors?
Did not Jeremiah tell his persecutors, '`The Lord is with me as a terrible one,
therefore my persecutors shall stumble; and they shall not prevail,
they shall be greatly ashamed, for they shall not prosper;
and their everlasting confusion shall never be forgotten?`' And
did not this come upon the persecutors that put Jeremiah in prison,
and dungeon?
Was not Jeremiah delivered?
And his persecutors went into captivity, and he set at liberty from his prison.
Jer. 20:11, you may see what became of his persecutors,
whether they did not go into captivity, and into prison.

And Isaiah, speaking by prophecy of Christ, how he was oppressed and afflicted,
yet he opened not his mouth; and was not he brought as a lamb to Pilate`'s,
and to the Jews`' slaughter, and as a sheep before the shearers;
and he was taken from prison, and from judgment;
who shall declare the generation of the suffering lamb,
slain from the foundation of the world;
for the transgression of his people was he stricken.
The smiters, and the afflictors, and the opposers, and imprisoners, despisers,
and rejectors, cannot declare the generation of Christ the Lamb of God.
And Isaiah saith, '`If thou loose the bonds of wickedness, to undo the heavy burden,
and let the oppressed go free, etc. if thou draw out thy soul to the hungry,
and satisfy the afflicted soul,
then shall thy light rise in obscurity.`' But what will
become of such that do oppress and lay their burdens,
and afflict the just?
Their light will be darkness.
And the Lord saith, speaking of the children of Israel, '`in all their afflictions,
he was afflicted; and the angel of his presence saved them;`'^
footnote:[Isa. 63:9]
in his love, and in his pity he redeemed them; and he bore them,
and carried them all the days of old;`' and God said,
'`I sent my angel before thee to keep thee in the way,`' etc.^
footnote:[Ex. 23:20]
And when the children of Israel cried unto the Lord, he heard their voice,
and delivered them from their persecutors, and afflictions.
And the Lord said, '`I have surely seen the afflictions of my people, which are in Egypt,
and have heard their cry, by reason of their task masters;
for I know their sorrows.`' So here you may see the Lord doth hear their cries,
and is sensible of the afflictions and sorrows of his people,
therefore commandeth his people, '`not to afflict the widow, nor the fatherless,
nor the stranger; for if they did, they would cry unto the Lord,
and he would make their wives widows, and their children fatherless.`'

And Amos cried, '`Woe unto such that chant to the sound of the viol,
and invent to themselves instruments of music like unto David, that drink wine in bowls,
and anoint themselves with chief ointments;
but they are not grieved for the afflictions of Joseph;
for I know your manifold transgressions, and your mighty sin,
they afflict the just;`' and that is it that afflicts the just in our age,
and are not sensible of the afflictions of Joseph,
nor of the afflictions of the righteous in our age.
And Christ saith, '`And shall not God avenge his own elect,
which cried day and night unto him?`' And did not Christ tell the Jews,
how they had slain and persecuted the prophets?`' And he said,
how that they should persecute his apostles and prophets?`'
And what are become of those persecuting Jews?
And Christ said to his disciples, They shall lay hands on you, and persecute you,
delivering you up to the councils, and scourge you in the synagogues,
and cast you into prison, being brought before kings and rulers for my name sake;
and it shall turn to you for a testimony.
Settle it therefore in your hearts, not to meditate before what ye shall answer,
for I will give you a mouth and wisdom,
(saith Christ,) which all your adversaries shall not be able to gainsay
or resist.`' Therefore it is good for all to look unto Jesus,
both for wisdom and for strength in all their trials, and sufferings, and persecutions;
for without him they can do nothing.

And Christ saith, '`Blessed are they which are persecuted for righteousness sake,
for theirs is the kingdom of heaven;
blessed are ye when men shall revile and persecute you,
and say all manner of evil against you falsely for my sake;
rejoice and be exceeding glad, for great is your reward in heaven;
for so persecuted they the prophets which were before you.
But I say unto you, love your enemies; bless them that curse you;
do good to them that hate you, and pray for them that despitefully use you,
and persecute you.`' And Christ saith to his disciples,
'`You shall be hated of all men for my name sake:
but he that endures to the end shall be saved; but when they persecute you in this city,
flee you to another; for verily I say unto you,
ye shall not have gone over all the cities of Israel till the son of man come.
But when they deliver you up, take no thought, how or what you shall speak;
for it shall be given you in that same hour, what you shall speak;
for it is not you that speak,
but the spirit of the Father that speaketh in you.`' And further,
Christ saith to the Jews, '`Behold I send unto you prophets and wise men,
and some of them ye shall kill and crucify;
and some of them ye shall scourge in your synagogues, and persecute from city to city,
that upon you may come all the righteous blood shed upon the earth,`' etc.

And also you may see how John Baptist was cast in prison, for reproving of Herod:
and his wife`'s daughter pleased Herod with her dancing, and Herod promised with an oath,
to give her whatever she would ask,
and her mother advised her to ask John Baptist`'s head, and she had it given her.
Now this was the fruit of transgressing the law of God, and of her dancing, and oaths,
and swearing, contrary to the command of Christ, who saith, swear not at all.

And also, Christ saith, '`I was hungry, and ye gave me no meat; I was thirsty,
and ye gave me no drink; I was naked, and ye clothed me not; in prison,
and ye came not unto me; I was a stranger, and ye took me not in; and sick,
and ye visited me not,`' etc.
And Christ saith, '`Inasmuch as ye did it not to one of the least of these,
you did it not unto me; and such shall go into everlasting punishment,
and the righteous into life eternal.`'

Is it not the practice of the professors now-a-days, instead of clothing the naked,
to take away their clothes?
And take away their meat and drink, instead of giving them meat and drink?
And cast into prison, instead of visiting them in prison?
Yea, such as pretend to be preachers of the gospel, though they do not hear them;
but such are transgressors of his command, who saith, '`Freely you have received,
freely give.`'

And Ahab the king, said, '`Take Micaiah, the prophet, and put this fellow in the prison,
and feed him with bread of afflictions until I come
in peace;`' and Micaiah said unto Ahab,
'`If thou return at all in peace, the Lord hath not spoken by me.`' So Ahab was slain,
according to Micaiah`'s prophecy. 2 Chron. 18:27.

And did not the prophet Hananii reprove Asa the king?
And the king was in a great rage, and put the prophet in prison,
because he reproved the king, who relied on the king of Asyria,
and not on the Lord God? 2 Chron. 16:7.

And you may see in the Acts,
how the priests and the rulers cast the apostles into prison,
and charged them that '`they should preach no more in the name
of Jesus.`' And Stephen said to the chief priest and the rulers,
'`Which of the prophets have not your forefathers persecuted,
and slain them which showed before the coming of the Just One,
of whom ye have been now the betrayers and murderers, who received the law,
etc. and have not kept it?
When they heard these things, they were cut to the heart,
and gnashed on him with their teeth, and stoned Stephen to death,
Stephen calling upon God, saying, Lord Jesus receive my spirit.`'

And Paul said,
'`I have persecuted this way (which was the way of true christianity) unto death,
binding and delivering into prison both men and women;
the high priest doth bear me witness, and all the state of the elders,
from whom also I received letters, and went unto Damascus to bring them which were there,
bound unto Jerusalem for to be punished.`' This was Paul`'s confession when he was converted,
and persecuted for Christ`'s sake, by the old persecuting professing Jews.

And Herod persecuted the Christians, and killed James, and imprisoned Peter,
whom an angel delivered through the prayers of the saints,
and the angel of God struck Herod that he died miserably.

And you may see, in the 16th of the Acts, how Paul and Silas were cast into prison,
and how the Lord wrought a wonderful deliverance to his glory for them!
And how often you see the Jews sought the life of Paul after he was converted;
and the heathen Romans had more tenderness,
who let him have liberty to dwell two full years in his own hired house,
and received all that came in unto him, preaching the kingdom of God,
and teaching those things which concerned the Lord Jesus; and no man forbade him.

And the Jews persecuted Jesus, because he had done good on the Sabbath day,
who was Lord of the Sabbath.
And Christ said to his disciples, '`Remember the word that I said unto you, (to wit,
his disciples,) the servant is not greater than his Lord; if they have persecuted me,
they will also persecute you, etc.
All these things will they do unto you for my name sake.`'

And this persecution and imprisonment the apostles
and the saints came to witness after Christ was risen;
and therefore you may see in his epistles he salutes his fellow prisoners,
and the apostle saith, '`He that is born of the flesh,
persecutes him that is born of the spirit;`' even so it is now,
each birth manifests both their works and fruits.

And the apostle saith to the Corinthians, '`Give no offence in any thing,
that the ministry be not blamed;
but in all things approving ourselves as the ministers of God, in much patience,
in affliction, in necessities, in distresses, in stripes, in imprisonments, in tumults,
in labours, in watchings, in fastings, by pureness, by knowledge, by longsuffering,
by kindness, by the holy ghost, by love unfeigned, by the word of truth,
by the power of God, by the armour of righteousness, on the right hand and on the left;
by honour and dishonour, by evil report and good report; as deceivers, and yet true;
as unknown, and yet well known; as dying, and behold we live; as chastised,
and not killed; as sorrowful, yet always rejoicing; as poor, yet making many rich;
as having nothing,
yet possessing all things.`' These are good examples for the true christians to follow.
2 Cor. 6:5. 11. 27.

And do not you read what became of Jezabel, that persecutor of the Lord`'s prophets?
And what is become of all the persecutors of God`'s people since the beginning?
That birth born after the flesh,
will it not have the same portion to the end of the world?
Is it not recorded to be the birth of the flesh;
and is not to inherit with the heir of the promise;
but is shut out from that inheritance?

G+++.+++ Fox.

London, the 8th month, 1682.
