[.style-blurb, short="How the Devil was and is the Old Informer"]
== How the Devil was, and is the Old Informer against the Righteous. By G. F.

He that is an informer, is a persecutor, and spoiler, and a destroyer;
and the devil is the head of all informers, persecutors, and destroyers of the righteous.

He is an adversary of the happiness of all God`'s people, and an accuser of them.
He is a serpent, an enemy to all that which is good.
See his enmity against Adam and Eve, and against their happiness,
how it did appear against Adam and Eve, in Gen. 1.

And see his enmity in the Sodomites,
who vexed just and righteous Lot`'s soul from day to day.
And Noah, a preacher of righteousness to the old ungodly world, who did not regard him,
no more than Sodom did Lot; but the one was drowned, and the other was turned into ashes.

And see the serpent`'s enmity in the Jews, and in Korah, Dathan,
and Abiram against Moses; and what became of them who would have stoned him?

And you may see the enmity of the serpent in the Jews against the prophets.
And did not both the ten tribes,
and the two tribes go into captivity for disobeying the Lord?
(like their father Adam,) in their enmity against his prophets and righteous people.

And likewise you may see the enmity of the serpent
in the Jews against Christ and his apostles,
insomuch that Christ called the Jews serpents,
and of their father the devil.`' And what became of those Jews?
Were they not scattered among all nations, and Jerusalem,
and their place of worship destroyed?

And what condition is all Christendom in, that is erred from the holy ghost,
and power the apostles were in?
Have they not received the unclean ghost, or foul spirit of the devil, the enmity,
adversary, accuser and destroyer, that old informer,
that makes them to destroy one another, makes them to envy and accuse, and informers,
and destroyers of the righteous?
And that foul spirit or unclean ghost hath brought Christendom on heaps,
one against another, that are not in the spirit and power of Christ the apostles were in.

And in Job, chap. i. 2. there you may see, the devil and Satan,
who was the enemy and murderer,
appeared against Job and his sons and daughters, to the spoiling of his goods, yea,
and his wife, who said unto Job,
'`Curse God and die;`' but Job called her a foolish woman, and did not sin with his lips,
though he lost his sons and daughters, and his goods, and was stripped of all;
and though the devil, Satan, said unto the Lord,
'`if that he would put his hand against Job, Job would curse him to his face.`'
Chap. 1:11.

And again, Satan the informer said, '`Skin for skin, yea, all that a man hath,
will he give for his life; but put forth thine hand now, and touch his bone, and flesh,
and he will curse thee to thy face.`' Job 2.

But in all these false informations of the devil,
who was a murderer and a liar from the beginning,
and so was proved and manifest to be both a murderer and a liar, and a false accuser;
for Job blessed the Lord, and did not sin with his lips. Job 1:2.

And Job`'s friends were miserable comforters; for the Lord said,
'`his wrath was kindled against them; for they had not spoken right of the Lord,
as his servant Job had; and therefore Job was to pray to the Lord for them;
and the Lord heard Job`'s prayer for them.`'

And Joseph`'s mistress was a wicked informer to her husband, against innocent Joseph.
First she informed the men of her house, then she informed her husband,
whose wrath was kindled against him, that he took him, and cast him into prison.
And all this was because Joseph would not yield unto his mistress`'s wickedness,
and sin against God; so here the serpent, and the devil, the adversary,
appeared against innocent Joseph whom God was withal, and made him to prosper.
Gen. 40.

But in Proverbs 7. you may see, how the woman, with the attire of an harlot,
and subtlety of heart, whose feet abides not in her house,
and lieth in wait in every corner of the street, in the twilight in the evening,
in the black and dark night, deceived the young man void of understanding;
for they that have understanding will shun her; for by the means of a whorish woman,
a man is brought to piece of bread,
and the adulterous will hunt for the precious life of the righteous.

And though the informers and archers, did sorely grieve Joseph, and shot at him,
and hated him, yet his bow abode in strength,
and Joseph`'s brethren did envy him for his dream,
but his father Jacob observed his sayings.

And you may see how Pharaoh, king of Egypt, informed his people the Egyptians,
against the children of Israel, and set task-masters over them,
that made their lives bitter; and the Egyptian task-masters obeyed Pharaoh`'s commands,
and made them to make brick without straw, and serve with rigour:
but the Hebrew midwifes would not obey Pharaoh, to kill the men children;
and the more Pharaoh and his task-masters persecuted and oppressed them,
the more they multiplied.
But what became of Pharaoh, and all his persecutors and informers at last?
Did not God overthrow them in the sea, and deliver his people?

There ran a young man, and told Moses, and said,
'`Eldad and Medad were prophesying in the camp.`' And one said unto Moses,
my lord forbid them; and Moses said unto him, Enviest thou for my sake?
Would God that all the Lord`'s people were prophets;
and that the Lord would put his spirit upon them.`' Num. 11.

Here Moses did not give credit to those informers, but rather reproved them,
and encouraged the prophets, desiring that all the Lord`'s people were prophets.
So Moses was far off from saying, have them before a magistrate,
and fine them 20£. a piece, for speaking.
And what became of all those that went to search the land of Canaan,
and brought an evil report upon the land of Canaan, contrary to God`'s promise,
and to the testimony of Caleb and Joshua,
that these false informers made the congregation so envious,
that they were ready to stone Moses?
And did not those false informers, and them that joined with them,
their carcasses fall in the wilderness?
Num. 14. And what became of Korah, Dathan, and Abiram,
and the two hundred and fifty princes, that were famous in the congregation,
and men of renown, which told Moses and Aaron, `'Ye take too much upon you,
seeing all the congregation were holy, every one of them; for the Lord is among them;
wherefore then lift you up yourselves above the congregation of
the Lord.`' See what high words these informers could speak,
to incense the congregation against Moses and Aaron, and such as feared God.
Did not the earth swallow up Korah and his company alive?
And did not a fire come from the Lord, and consume the two hundred and fifty men?
And on the morrow, all the congregation of the children of Israel murmured against Moses,
and told him,
'`he had killed the people of the Lord.`' Did not
the wrath of the Lord go out against them,
and there died of the plague 14,700 of them?
So here was the end of those murmurers, or informers, and rebels against the Lord,
his truth, and people.
Num. 16.

And again,
you may see what Moab said unto the elders of Midian against the children of Israel;
and Balak sent the elders of Moab, and the elders of Midian,
to Balaam with rewards of divination in their hands, to curse the Jews,
the people of God; but the Lord forbade Balaam to curse them,
though Balaam loved the reward of unrighteousness.
And Balak sent yet again princes more honourable than the first elders;
and Balak told Balaam '`he would promote him to great honour, if he would curse,
the children of Israel.`' But see what came upon Balaam, his ass reproved him,
and the Lord made her to speak that which confounded Balaam;
and after was not Balaam and the Midianites destroyed?
Num. 22. and xxxi.
Here you may see how the enemy appeared in Balak, who would have destroyed the Jews;
but the Lord prevented him and Balaam.

And many informers were against David, but especially Doeg the Edomite,
which informed Saul against David, and Abimelech the priest, and all his father`'s house,
because he received David.
And Saul commanded his footmen to slay the priests;
but Saul`'s servants would not put forth their hands
to fall upon the priests of the Lord;
and Saul bid Doeg the Edomite, the informer, and he fell upon them,
and slew eighty-five persons on that day, that wore the linen ephod; and Nob,
the city of the priests, smote he with the edge of the sword, both men, women, children,
and sucklings.
And here you may see the informer was a murderer of the innocent.
1 Sam.
xxii.
And in chap.
xxiii.
xxv. xxvi.
you may see how the informers went to Saul, and informed him against David.
And you may see in Ps. 52. how David prophesied the destruction of Doeg the Edomite,
who came and told Saul, and said unto him, '`David is come into the house of Abimelech.`'

And in Ezra 4. there you may see,
several informers writ letters against Jerusalem to Artaxerxes,
to hinder the building of the city of Jerusalem.
And you may see how busy Tobiah, and the Arabians, and the Amonites, and Ashdodites,
and Sandbalat were against the Jews when they built Jerusalem;
and how that Tobiah and Sandbalat hired the false prophet to prophesy against Nehemiah;
but their prpohecies and their works come to naught,
for the Lord helped his people against them, whom the serpent made enemies,
and adversaries, and informers against them.

And Haman, that great informer against Mordecai and the Jews,
Haman said unto king Ahashuerus,
'`There is a certain people scattered abroad in all the provinces of thy kingdom,
and their laws are diverse from all people, neither keep they the king`'s laws,
therefore it is not for the kings profit to suffer them.
If it please the king, let it be written that they may be destroyed,
and I will pay ten thousand talents of silver to
the hands of those that have the charge of the business,
to bring it into the king`'s treasuries.`' Now here you may see the devil, the destroyer,
who is the enemy and adversary of God`'s people,
how this informer hath exceeded all the informers before,
and all the informers in our times; for instead of being an informer to get money,
he would give the king money to destroy God`'s people, yea,
ten thousand talents of silver; and he got the king`'s seal for it too,
to seal his writing; but for all this, what became of Haman?
Was not he hanged on the gallows which he built for Mordecai,
and abundance of his confederates destroyed?
And there was the end of proud Haman,
whom the destroyer led to be an informer and a destroyer,
who was destroyed upon the gallows that he built for another.

And in Jer. 38. Pashur, with many others, were informers against Jeremiah,
to Zedekiah the king; and you may see this Pashur, the son of a priest,
had put Jeremiah in the stocks, and smote him;
and the envious informers said unto Zedekiah, whom the devil stirred up to murder him,
'`We beseech thee, O king, let Jeremiah be put to death,
for he weakens the hands of the men of war, that remain in the city,
and the hands of all the people, in speaking such words unto them;
for Jeremiah seeks not the welfare of this people, but their hurt.`' Then Zedekiah said,
'`He is in your hands,
for the king is not he that can do any thing against you.`' Then they took Jeremiah,
and let him down with cords into the dungeon, and he sunk in the mire.
And the Ethiopian, one of the king`'s eunuchs,
told the king what these informers had done,
and how that Jeremiah would die in the dungeon;
and the king bid him take thirty men with him, and take up Jeremiah before he died;
and the Ethiopian took old clouts and rotten rags,
and let them down by cords into the dungeon, and bid him tie them under his arm holes,
and so he drew him out of the dungeon, and put him in the court of the prison,
where he remained till Jerusalem was taken by Nebuchadnezzer,
who put Jeremiah out of prison, and gave him liberty.
And so he found more mercy at the hands of the Ethiopian and Nebuchadnezzer`'s officers,
than he did among the professing Jews, the informers.
And you may see what a destruction came upon the city, Zedekiah and his sons,
and his men of war, and his people, for disobeying the word of the Lord.
And Jeremiah told the "`Ethiopian that helped him out of the dungeon,
that he should not fall by Nebuchadnezzer`'s sword,
because he put his trust in the Lord.`' Jer. 39.

So here was the end of these informers, carried into Babylon, and many destroyed.
And you may see how the devil, the murderer, and his informers, his persecutors,
that put Jeremiah in the dungeon, and thought to have taken away his life,
were put into prison themselves, and many of their lives lost; and Jeremiah,
who was faithful, and trusted the Lord, saved.
Jer. 49. and xl.

And Dan. 3. you may see how the destroyers raised up informers against the three children,
and went to the king, and accused the Jews, and said, '`Thou, O king, hast made a decree,
that every man should fall down and worship the golden image; and whoso falleth not down,
and worshippeth, he shall be cast into the fiery furnace:`' '`there are certain Jews,
(said they,) which are set over the affairs of the province of Babylon, Shadrach,
Meshech, and Abednego; those men, O king, have not regarded thee,
they serve not thy gods,
nor worship the golden image which thou hast set up.`' This said the informers.
Then Nebuchadnezzer, in his rage and fury, commanded to bring Shadrach, Meshech,
and Abednego, before him, and he said unto them, '`Is it true?
do you not serve my gods, nor worship the golden image which I have set up?
etc. But if you worship not,
ye shall be cast the same hour into the midst of the fiery furnace.
Who is that god that shall deliver you out of my
hands?`' Then said the three children unto the king,
'`We are not careful to answer thee in this matter; but if it be so, our God,
whom we serve, is able to deliver us from the burning fiery furnace;
and he will deliver us out of thy hands, O king.
But if not, be it known to thee, O king, we will not serve thy gods,
nor worship the golden image which thou hast set
up.`' Here was a positive answer and a godly confidence.
Then was the king full of fury, and the form of his visage was changed,
against the three children;
and he commanded his furnace to be heated seven times more than it was wont to be,
and commanded the most mighty men of his army to bind the three children in their coats,
hose, and hats, and other garments, and cast them into the midst of the burning furnace;
which flames of fire slew those men that cast them in.
Then the king was astonished, and rose up in haste, and said unto his counsellors,
'`Did not we cast three men bound into the midst of the fire?
And they answered, and said unto the king, True, O king.
And he answered, and said, Lo, I see four men loose, walking in the midst of the fire,
and they have no hurt, and the form of the fourth is like the son of God;
and the king called the three children out of the fire.`'
And so the king was made to bless the God of Shadrach,
Meshech, and Abednego; and made a decree, '`that every people, nation, and language,
which spoke any thing amiss against the God of Shadrach, Meshech, and Abednego,
shall he cut in pieces, and their houses shall be made a dunghill,
because there is no other God that can deliver after this sort.`'

Now here you may see, the Lord confounded the murderous informers,
and the fury and rage of Nebuchadnezzer; and his mighty men were slain,
that cast the three children into the fire;
but the Lord delivered the three children that trusted in him,
to the exaltation of his glory and name.

And also you may see in Dan. 6. Darius made Daniel chief of the presidents,
and the presidents and princes turned informers against Daniel;
and these informers could not find any fault or error in him, because he was faithful;
then said these informers, '`We shall not find any occasion against this Daniel,
except we find it against him concerning the law of his God.`'
And therefore they got the king to establish a decree in writing,
that it be not changed, according to the law of the Medes and Persians, which alters not;
which decree was,
'`that whosoever should ask a petition of any God or man for thirty days, saving of thee,
O king, they shall be cast into the den of lions.
And the presidents of the kingdom, and the governors, and the princes,
and the counsellors, and the captains, consulted together concerning this decree,
which the king signed.
Now Daniel knew the writing was signed; he went to his house,
and his windows being open in his chamber, etc. he kneeled down three times of the day,
and prayed and gave thanks to God, as he had done before time.`' Then these men,
the informers, assembled, and found Daniel praying,
and making supplication before his God; then these men assembled unto the king,
and informed him against Daniel; then the king commanded Daniel to be brought,
and be cast into the lion`'s den,
according the decree that they had wickedly got of the king;
and the king encouraged Daniel, and said unto him, '`Thy God, whom thou servest,
he will deliver thee.`' And early in the morning the king rose,
and went in haste unto the den of lions, and said, '`O Daniel,
the servant of the living God! is thy God, whom thou servest continually,
able to deliver thee?`' And Daniel said, '`My God hath sent his angel,
and shut up the lions`' mouths, that they have not hurt me,
forasmuch as before him innocency was found in me, and also before thee, O king,
I have done no hurt.`' And then the king commanded
them to take up Daniel out of the lions`' den;
and commanded them to take those great men,
which were the accusers and informers against Daniel, and cast them,
and their wives and children, into the lion`'s den;
and the lions had the mastery over them,
and broke all their bones in pieces or ever they came at the bottom of the den.
So here was the end of these devilish informers, or accusers,
who were princes and presidents.
And then Darius made a decree, '`That in every dominion of his kingdom,
men tremble and fear before the God of Daniel; for he is the living God,
and steadfast forever, and his kingdom that which shall not be destroyed,
and his dominion shall be even to the end.`' Here you may see,
God was exalted by them who believed in him,
and the wicked destroying informers were destroyed.

And the chief priests and scribes sought how they might kill Jesus,
for they feared the people; then entered Satan into Judas,
and he communed with the chief priests and captains, how he might betray him unto them;
and they were glad, and covenanted with him, to give him money, to wit,
thirty pieces of silver.
And the chief priest persuaded the multitude, that they should ask Barrabas,
and crucify Jesus;
and all the chief priests and elders of the people
took counsel against Jesus to put him to death;
and they sought false witnesses against him, but found none;
at the last there came two false witnesses, and said, '`This fellow said,
I am able to destroy the temple of God,
and build it in three days.`' And Pilate sought to release Jesus; but the Jews cried out,
'`If thou let this man go, thou art not Caesar`'s friend,`' etc.
And so when these false accusers, and informers, and false witnesses,
with Pilate`'s judgment, had crucified Jesus, after he was risen,
the chief priests assembled with the elders, and after they had taken counsel,
they gave large money to the soldiers that watched the sepulchre, to say,
'`that Christ`'s disciples came by night,
and stole him away while they slept.`' So here is the devil and Satan,
which entered into the Jews, and Judas, etc. which made Judas a betrayer,
and the Jews false witnesses, liars, and murderers of the just;
and the Jews to this day believe their lies, and false information,
that Christ`'s disciples stole him away by night, while the watch slept;
but the Lord recompensed them all according to their works.

And you may see how Satan made false witnesses and informers against Stephen;
and they brought him to the high priest`'s court, and there he examined him;
but at last you may see they murdered him, and stoned him to death,
as he was calling upon God, and saying, '`Lord Jesus receive my spirit.`' Acts 7.

And did not Judas betray Christ with a kiss?
And was not Christ led to Caiaphas the high priest`'s court or hall,
where the scribes and elders were assembled;
and the high priest examined him in his court, until the cock crew twice?
And did not the truth that Christ spoke to the high priest,
put him into such a wrath or rage, that he tore or rent his clothes?

And were not Peter and John haled before Ananias the high priest`'s court,
where the rulers, elders, and scribes, and John, and Alexander,
and many of the kindred of the high priest, were gathered together?
And did not they set Peter and John in the midst, and examine them, and charged them,
to speak no more in the name of Jesus?`' But Peter and John said unto them,
'`Whether it be right in the sight of God to hearken unto you, or unto God, judge ye;
for we cannot but speak the things which we have seen and
heard.`' Then the high priest threatened them,
and let them go.
Acts 4.

And again, you may see how the high priest, and all that were with him,
were filled with indignation, and rose up against the apostles,
and cast them into the common prison; but the Lord delivered them.

And you may see all along in many places of Acts,
how the Jews rose up against the apostles;
and how that one of the officers came and told the chief priest and captain,
'`that the apostles were preaching in the temple,
which they cast into prison.`' And the captain and the officers brought them,
and set them before the council; and the high priest and they took counsel to slay him;
but Gamaliel said unto them, '`Refrain yourselves from these men, and let them alone;
for if this work, or this counsel be of men, it will come to nought; but if it be of God,
you cannot overthrow it,
lest happily ye be found even to fight against God.`' And his counsel
swayed and stopped the high priest and his court from murdering of them.

And Saul, he made havoc of the church, entering into every house, haling men and women,
and committing them to prison; and Saul yet breathed out threatenings and slaughters,
against the disciples of the Lord, and went to the high priest,
and desired of him letters to Damascus, to the synagogues, '`if he found any of this way,
whether they were men or women,
he might bring them bound to Jerusalem.`' So his
authority was from the chief priest to persecute;
but Christ met him in the way,
and told him '`it was hard for him to kick against the pricks;`' and said unto him, Saul,
Saul, why persecutest thou me?`' For he was persecuting Christ in his members;
and Christ converted him, and after some time sent him to Damascus to preach his gospel,
where he was going to persecute.
But after many days that he had preached the gospel at Damascus,
the Jews there took counsel to kill him,
and they watched night and day at the gates to kill him;
but the disciples of Christ took Paul by night, and let him down by the wall,
in a basket, and so he escaped those murdering professors, without possession,
as you may see, in Acts 9. So he that went to persecute at Damascus,
was persecuted at Damascus for preaching Christ, whom he was going to persecute.
And here you may see how the persecutors were confounded.

And in Acts 14 there you may see how the unbelieving Jews stirred up the Gentiles,
and made their minds evil-affected against the brethren; and Elimas,
the sorcerer withstood Barnabas and Paul, to turn away the deputy from the faith.
Here you may see the professing Jews and the sorcerer were found in one spirit;
but the Jews were spiritually blind with evil, and God struck Elimas naturally blind.
And the Jews, which were more than forty, that came to the chief priests and elders,
and said unto them how that '`they had bound themselves under a curse,
that they would not eat nor drink,
until they had killed Paul;`' and the chief priests and
council were to manage this matter for these murderers;
then they were to send to the captain, that kept Paul a prisoner,
to bring him out of the castle, which was his prison, to the chief priests and elders,
under a pretence that they would inquire something of him;
and these murderers were ready to murder him, before ever he came near them.
But the captain of the castle understanding the thing,
the Lord put it in his mind to send Paul away,
by which the innocent escaped the hands of these murdering informers and liars,
which the chief priests and council had a hand in;
and Paul had more mercy from the Roman captain,
than he had from the professing Jews and their priests.
And after awhile Ananias, the high priest, with the elders,
with a certain orator named Tertullus, informed the governor Felix against Paul;
and after a great deal of daubing, and plausible expressions, as you may see,
in Acts 24. said they, '`We have found this man, a pestilent fellow,
a mover of sedition among all the Jews throughout the world,
and a ringleader of the sect of the Nazarenes:`' and so
after many grievous false charges they laid against Paul,
Paul had liberty to clear himself of their lies, and slanders, and false informations.
And when they had kept Paul about two years in prison there,
Festus came into the province; then the high priest,
and chief of the Jews informed him against Paul, and desired favour against him,
that he would send for him to Jerusalem, the Jews lying in wait in the way to kill him;
but Festus said unto them, '`Which among you are able,
go down to Cesaria to accuse this man;`' and when they came there,
they laid many grievous complaints against Paul, which they could not prove;
and so the Lord delivered him out of these murderous informers`' hands,
though Festus would have done the Jews a pleasure, as by having Paul up to Jerusalem,
to be judged there by him; but Paul appealing unto Caesar, prevented him, and the Jews,
and the high priests, of their design against him, as you may see,
in Acts 25. more at large.

And what became of Jezebel, with her informing letters,
that she wrote in Ahab`'s name to the elders and nobles that were in the city,
dwelling with Naboth; who bid them proclaim a fast,
and set up Naboth on high among the people; and sent two sons of Belial before him,
to bear witness against him, saying,
'`Thou didst blaspheme God and the king;`' and then carry him out, and stone him,
that he may die.
And they did so, according to Jezebel`'s information; and when they had killed him,
she and her husband took possession of his estate.
But what destruction came upon Ahab and Jezebel, and all those that took their part,
as you may read the sentence and judgment, 1 Kings xxi.

And therefore let all murderers, informers, and sons of Belial, take heed,
who seek the destruction of the righteous,
in that they bring destruction upon themselves,
as you may see all along in the scriptures, what was the end of such,
whether they were high or low, priest, professor, or prophane,
the righteous God spared none;
and therefore read the scriptures from one end of the book to the other,
and there you may see the sad examples and judgments that have come on such,
whom the devil, who was the great informer, hath made liars and informers,
false witnesses, and false accusers, against the righteous;
and let them be like so many way-marks, to shun the evil.
But '`Christ is come to destroy the devil and his works,
and to bruise his head,`' who was the informer against Job,
and the false teacher and informer of Adam and Eve to transgress the command of God;
therefore, if Christ destroyeth the father of all such informers, persecutors, and liars,
and false witnesses, his children may fear destruction;
and the saints can sing hallelujah over the devil, Satan, serpent, and all his followers,
that do his work, whom the living God will reward accordingly.

[.signed-section-signature]
G+++.+++ F.
