[#ch9.style-blurb, short="Against the Pomps of the World"]
== A Paper to Friends, and others, against the pomps of the world, followed and used by many tradesmen, in their vocations, contrary unto many of their sureties, promises, and vows.

Friends, stand in the eternal power of God, witnesses for the eternal God,
against the devil and his works, and the world, and the lusts, and pomps,
and vanities of the world, which world the devil is god of.
Now, there is a saying by the godfathers and godmothers,
(so called,) that they do promise and vow, etc. to forsake the devil and all his works,
the pomps and vanities of this wicked world, and all the sinful lusts of the flesh,
and vow for children that they will not follow them, nor will be led by them;
but forsake them all.
But do not we see that many that say so, run into all, or many of the lusts, and pomps,
and vanities of the world?
And are not such offended at those tradesmen that cannot
trim their clothes and apparel according to the pomps,
and lusts, and fashions of the world, which pass away?
But such tradesmen that stand as witnesses in the power and truth of God,
against such pomps, lusts, and vanities of the world,
cannot fulfill the people`'s minds in them; and therefore they are offended at them.
But, did God make man and woman with these pomps, vanities, and lusts of the world?
Or how came they into them?
No, God did not make man and woman with these pomps, vanities, and lusts of the world.
But when man and woman forsook the living God, and disobeyed him,
and followed the serpent, Satan, and the devil; then he filled them with these pomps,
and lusts, and vanities of the wicked world, which the devil is god of.
So they fell from the righteousness, and holiness, and image of God;
and disobeying and transgressing the command of God, and going from God,
and following the serpent, he hath filled them with pride, envy, malice, and hatred,
one against another; and with the lusts and pomps of the world.
And they are grieved and vexed, one against another,
when they cannot have such pomps and vanities as others have, and think much at such,
and envy them that are in pomp and pride beyond them, or above them.
And this pride, pomp, and lust, the devil hath begotten in man and woman,
in the fall from God.
And so it had a beginning in man and woman, and must there have an end,
if ever they come to God.

And they that stand faithful witnesses for the eternal God,
in his eternal power and truth, are witnesses against all this pride and pomp,
and vanities of the world, and lusts of the flesh, and the devil and his works,
and cannot please them, nor satisfy them in their pomps, pride, and lusts of the world,
which are of the devil, and not of God, though it might bring them in much gain;
yet they in their pomp and pride are offended,
and very angry with them that cannot satisfy their minds in them.
For the apostle saith, '`The lusts of the flesh, the lusts of the eye,
and the pride of life, is not of the Father,`' (mark,
not of the Father,) not of God the Father, the creator of all, that takes care for all,
who is the Lord of all.
Now, if the lust of the flesh, the lust of the eye, and the pride of life,
be not of the Father, who is it of then, but of the devil,
the god of the world which lies in wickedness?

Now, how comes this lust of the eye, and pride of life,
and lust of the flesh into man and woman?
Seeing it is not of the living God the Father, it came by the devil,
when man and woman transgressed the command of the living God, and obeyed the serpent,
and so fell from their innocency, and the image of God in righteousness and holiness.
So then the devil, the god of the world, filled them with the lust of the flesh,
the lust of the eye, and the pride of life, which is not of the Father.
So this had a beginning in man and woman when they went from God, and disobeyed him,
and transgressed his commandment, and not before.
So they that stand in the eternal power of God and Christ,
who hath renewed them up into the image of God that
man and woman was in before they fell,
they stand witnesses against the lusts of the flesh, and the lusts of the eye,
and the pride of life, and the god of the world,
that hath filled man and woman with these things, and hath begotten these things in them.

So these tradesmen that are God`'s witnesses, and cannot satisfy, nor fulfill,
nor please the lust of the eye and the pride of life, nor lust of the flesh,
which is not of the Father, but of the god of the world, the devil,
whom Christ destroyed and his works; who, through death destroyed death,
and the devil the power of death.
And so Christ`'s witnesses and followers,
do stand witnesses in his power and truth against the devil and his works,
and the pomps and vanities of the wicked world.
These are sealed certain witnesses in God`'s eternal power and truth,
against all that which is not of the Father, but of the devil.
And also are witnesses for that which is of God the Father, and his son Jesus Christ,
and for his glory, and for his honour, and his praise.

But they that are in their pomps and vanities,
and followers of the god of the world and his works, and the lusts of the flesh,
the lusts of the eye, and the pride of life,
do hate and persecute them that stand witnesses against such things.
And they who are in their pomps,
will hardly employ those that stand witnesses against them in their pride and pomps.
So that these tradesmen can hardly get any trading amongst them,
whilst they stand witnesses in God the Father`'s power and truth,
against those who are in those pomps and vanities,
and in that which is not of the Father.
And in so doing, they know that they keep clean consciences to God; and know,
and are assured that his blessings rest upon them,
who will bless them with blessings from above, and the blessings beneath.
And they are witnesses for God, who hath his upper springs,
and his nether springs to refresh them,
which enables them to stand faithful witnesses for the living God their Father:
to whom be glory forever; whose glory is over all the works of his hands;
who is worthy to be served, worshipped, and honoured forevermore.
Amen.

[.asterism]
'''

And therefore it is good for all, to wait patiently upon the Lord;
for some of you do know, when truth first broke forth in London,
that many tradesmen could not take so much money in their shops for some time,
as would buy them bread and water; because they withstood the world`'s ways, words,
fashions, and customs.
Yet by their patient waiting upon the Lord, in their good life and conversation,
they came to answer the truth in people`'s hearts and consciences.
So there arose a belief in people, that Friends would not wrong them in any thing:
so that at last the Lord did increase his blessings,
both inwardly and outwardly upon his people.
And therefore let none murmur nor complain,
but wait in patience and faithfulness upon the Lord,
who is both God in heaven and in the earth, and all is the Lord`'s,
who can fill you both with his temporal and spiritual blessings:
therefore all walk worthy of them in truth and righteousness;
that whatever ye do in word or deed, it may be done to the praise and glory of God.

G+++.+++ F.

London, the 2d of the 11th month, 1682.
