[#ch10.style-blurb, short="A Way to Prevent the Judgments of God"]
== A way to prevent the indignation and judgments of God from coming on a kingdom, nation, or family. Commended to the consciences of all concerned.

[.numbered-group]
====

[.numbered]
_First,_ all you vintners that sell wine, that keep taverns or such like houses;
and all you innkeepers, and you that keep victualling-houses, ale-houses,
strong-water-shops, etc. see that you never let any man or woman have any more wine, ale,
strong drink, brandy, or strong waters, or other strong liquors,
than what is for their health and their good;
in that they may praise God for his good creatures.
For every creature of God is good, and ought to be received with thanksgiving.

But if you do give or let men or women have so much wine, brandy, strong liquors,
strong beer, or ale, till they be drunk, or to make them drunk:

====

[.numbered-group]
====

[.numbered]
1+++.+++ You destroy the good creatures of God.

[.numbered]
2+++.+++ You destroy them that have not power over their lusts, no more than a rat or a swine,
who will drink till they are drunk.

[.numbered]
3+++.+++ You are a great cause of ruining them in their healths, purses, and estates,
(their children and families,) in feeding of them in their lusts,
by letting them have more than doth them good;
which also tends to bring God`'s judgments upon you, to your own ruin and destruction.

====

For many, when they are full of wine, beer, or strong liquors,
then they will cry for music, pipe, and harp, and it may be, their whores also.
And so in this, you that suffer or allow such things, are nursers of debauchery,
and corrupters of them, and of your own families also.

And also such men, when they are full of wine or strong liquors,
and have destroyed the creatures, by taking more than doth them good,
then they are got to that height that they are ready to quarrel and abuse,
or kill or destroy one another; and sometimes kill other people,
(who do them no harm,) as they are walking or travelling in the streets or highways.
For when they are overcome by strong liquors,
then are they fit and do lie open to all manner of wickedness.

And though you think by selling or letting people
have wine or strong liquors more than doth them good,
or is for their health, '`the more they drink, the more gain you think it brings you;
and the more you vend your goods, the more profit you get.`' Ah poor sellers!
Do not you think, that God with his all-seeing eye doth behold you and your actions?
And cannot the Lord soon bring a blasting upon all your undertakings,
and such ungodly gain and profits, and whatsoever you have gained by your covetousness,
and from the lusts of others, through which they do destroy their estates, children,
and families?
Will not this bring destruction upon you and your unrighteous gain,
which you have gotten by feeding their lusts?
For that spirit which feeds the destroying lusts, must needs be the destroyer;
and the profits of that will not be gain to you in the end.

For are not you sensible, how that many, after they have spent their estates,
or part of them, will run into your debt for wine or strong liquors, yea,
such as you let have more than did or doth them good?

And is not this the cause that many break, by trusting,
and other ways as before mentioned?
Trust should be with that which is trusty, which doth not waste or destroy,
and such God will bless.
And therefore take heed of letting any man or woman have any more wine or strong liquors,
than what is for their nourishment, health, and good.

See what a dreadful woe the Lord pronounced against them,
'`that rise up early in the morning, that they may follow strong drink,
that continue until night, until wine inflame them.
Then they call for the harp and the viol, the tabret and the pipe, etc.
But such regard not the work of the Lord,
neither consider the operation of his hands.`' '`A sad state!`'
'`Woe unto them that are mighty to drink wine,
and are men of strength to mingle strong drink.`'
And therefore all are to shun such things;
all are to be sober, and to mind and fear God, that they may escape these woes;
as you may see in Isaiah, chap.
v.

And therefore all vintners, and such as sell wine, with ale-houses, inns,
and victualling-houses, who sell ale, brandy, and strong liquors,
never let any one have any more than doth them good, and is for their health,
(as is said before,) so that all may eat and drink
the good creatures of God to his praise and glory;
which drunkards and gluttons cannot,
nor they who let them have the creatures of God in excess,
or immoderately till they are drunk and surfeited,
for such do feed themselves without the fear of God.

[.numbered-group]
====

[.numbered]
_Secondly,_ let all who go under the name of Christian families,
train up their children in the fear of God, and keep themselves in the fear of God,
that they may keep all their servants and families in the fear of God;
out of all looseness and wantonness, and vanities and excess, and from all drunkenness,
fornication, whoredom, or uncleanness, and unrighteousness, and all ungodliness;
that they may keep out of all those things that displease or dishonour the Lord God.
And do not nourish up the lust of the eye, nor the pride of life,
nor the lust of the flesh; for if you do,
you nourish up that which is not of God the Father.
And therefore to shun all these evils, and to depart from them,
and keeping in the fear of God; this is the way to bring the blessing of God upon a land,
kingdom, nation, or family

====

[.signed-section-signature]
G+++.+++ F.

[quote.scripture, , Rev. 11:18]
____

God will destroy them which destroy the earth.
____

Drunkenness makes a man worse than a beast, and makes a strong man weak,
and a wise man a fool.

This testimony and warning was, and is owned and subscribed by many vintners and others,
concerned in the trades and callings before mentioned,
who were present at the reading of the manuscript.
