[#ch11.style-blurb, short="To All Rulers and Magistrates"]
== To all rulers and magistrates, to be tender, and take heed of persecuting, and imprisoning, and spoiling the goods of God`'s people, for obeying, serving, and worshipping the Lord God that made them, and the heavens, and the earth, and all things therein. By G. F.

For we, (the people in scorn called Quakers,) have suffered
as the lambs of Christ by all sorts of powers,
both imprisonment and spoiling of our goods,
only for serving and worshipping the God that made us.
And for these thirty-five or thirty-six years the
jails in most countries have seldom been empty,
but we are, and have been imprisoned, and many to death,
which hath caused many weeping widows, and many crying fatherless,
having their goods spoiled which should refresh and nourish them.
And did we ever but entreat, when we have been threatened?
And when we were cursed by bishops and priests, did not we bless?
And we, who are and have been persecuted, have not we always prayed for our persecutors?
Have not we been devoured like chickens, and hunted like partridges by birds of prey?
Have not we been as sheep among wolves?
And do not you know, that in New England some of us have been hanged,
and others banished on pain of death,
and others their bodies whipped and beat till they have been like a jelly?
And have not others of us had our ears cut, in the other power`'s days?
And now, in several dungeons and jails, men and women are crowded, yea,
some that have sucking children?
Oh! do not loose the bowels of humanity, nor the love and tenderness of christianity;
do ye and they learn of Christ, who is meek and low in heart,
that do and have done so unto us.
Would such be so served themselves?
Is this to fulfill the royal law of God,
'`To do unto all men as they would have them do unto them?`' Are not many of us spoiled
both in our trades and husbandry through the informers that take away our goods?
God in heaven knows and sees all our sufferings and afflictions;
which is only for obeying, and serving, and worshipping him.

And you know that the prophets, and Christ, and the apostles, they were never imprisoned,
nor persecuted, and suffered as just and righteous men,
(by them that made them to suffer,) but the question is,
'`whether they would be so done unto themselves, as they do unto others?
whether they would not judge it to be hard measure?`'

Therefore I beseech you all to consider,
whether ever Christ and his apostles did give any power to imprison and persecute,
and spoil the goods of any for obeying, serving, and worshipping God that made them?
Or did they ever persecute, imprison, or spoil the goods of any,
because they would not be of their religion?

Oh! therefore consider, you that profess yourselves christians,
shut not up your bowels of compassion against your brethren; but as the apostle saith,
'`Put on bowels of mercy and lovingkindness one
towards another.`' And consider what became of Pharaoh,
that oppressed and persecuted the children of Israel,
and all his host that rose up against them, and would not let them go to worship God.
And what became of Cain, that killed and persecuted his brother about religion?
And what became of the old ungodly world?
And what became of the cities of Sodom and Gomorrah, that grieved just Lot?
And what became of the Jews that persecuted the prophets, Christ, and the apostles?
Did they not persecute them because they obeyed God, and they themselves disobeyed God?
And what became of them that persecuted Daniel and the three children?
Did not they persecute them for worshipping and obeying God that made them?
And what do you read will become of the beast that compelled to worship?
And the whore spoken of in the Revelations,
that drinketh the blood of the martyrs and servants of Jesus?
Doth not John in the Revelations say, '`that their end will be destruction,
and their followers,
with the devil and his angels?`' who was the first
that led man and woman from obeying God.

But my desire is, that none that profess christianity may follow their ways,
lest they partake with them in their misery;
but that all may come to the knowledge of the truth, as it is in Jesus,
and in their own inward parts: and that all may cease from persecuting, and imprisoning,
and spoiling the goods of such as meet together to
serve and worship God in spirit and in truth,
as Christ hath commanded.

And Christ Jesus, by the grace of God, hath tasted death for every man,
and then hath he not shed his blood for all?
and bought them with the price of his blood?
And is there any thing that brings condemnation but disobedience, and unbelief in him?
And did Christ give any command to his apostles, messengers, and ambassadors,
to persecute them that would not believe, hear or receive their testimony?
But to shake off the dust of their feet as a witness against them,
and that should be punishment enough for them in the day of judgment.

And doth not Christ say, '`Let the tares and the wheat grow together until the harvest,
(which is the end of the world,) and in the end of the world,
Christ would send his angels that should be the reapers,`'
that should distinguish the wheat from the tares?
So Christ did not give men power before the world was ended, to pluck up the tares,
lest they should pluck up the wheat with the tares;
for that power Christ gives to his angels,
to sever the wheat from the tares at the end of the world.
And if they went into everlasting punishment, that did not clothe Christ in his members,
and visit when he was in prison;
what will become of them that cast him in his members into prison?

And you read what Christ saith unto Saul,
'`why persecutest thou me?`' when he was going with authority
from the chief priests to persecute the Christians at Damascus.

And you read how often Christ commands christians to forgive one another,
as God and Christ hath forgiven them.
And must these commands of Christ be preached, and talked of, and not practised?
For Christ saith,
'`you must do the will of his Father if ye enter in the
kingdom of heaven.`' And they that love God and Christ,
will not only call him Lord, but keep his commands, and do what he saith.

And how do they that are called Christians say the Lord`'s prayer,
who desire the Lord '`to forgive them their trespasses,
as they forgive them that trespass against them?`' For Christ saith,
'`If you forgive men their trespasses,
your heavenly Father will also forgive you your trespasses?
But if ye forgive not men their trespasses,
neither will your Father which is in heaven forgive you your trespasses,`' to wit,
your trespasses that you trespass against him.
Matt. 6. Mark 11.

Now here you may see that you pray to God conditionally,
for God to forgive you your trespasses against him,
as you do forgive them that trespass against you,
and not otherwise you desire God to forgive you yours?
Therefore I desire you will consider what you desire in this prayer.

Oh! that all that profess themselves christians had the spirit of Christ,
and the mind of Christ, who said, '`he came not to destroy men`'s lives,
but to save them?`' And rebuked his disciples,
who would have had fire to have come down from heaven
upon the Samaritans that would not receive Christ,
and told them,
'`they did not know what spirit they were of.`' So
if all Christendom had been in the spirit of Christ,
and the mind of Christ, and known what spirit they had been of,
they would not have destroyed so many men`'s lives,
by jails and persecutions about religion and the worship of God,
as they have done since Christ and the apostles`' days.

So it is clear, it is not the mind of Christ, that any should suffer, or be put to death,
because they would not receive him, or believe on him;
but to shake off the dust of their feet,
to be a witness against them in the day of judgment.

And if we are to pray for them that persecute us,
then they need not fear that we should hate them;
for we are commanded to love our enemies, and salute them, and not only our brethren;
we are to pray for all men, even for kings, and all that are in authority,
that we may lead a quiet and a peaceable life in all godliness and honesty;
for this is good and acceptable in the sight of God our saviour.
Now this should be the practice of all them that profess true christianity,
for God would have all men to be saved, and come to the knowledge of the truth;
for there is one God, and one mediator betwixt God and men, the man Christ Jesus,
who gave himself a ransom, for all, to be testified in due time.

Now, if kings, and, all men, must be prayed for, and all that be in authority,
and God would have them all to be saved, and come to the knowledge of the truth,
and Christ gave himself a ransom for all; then why, should men persecute, and imprison,
and destroy one another, and spoil the goods of one another, concerning church, religion,
and worship, for not conforming one to another, whereas they should pray for one another.
And do they not pretend to pluck up tares before the world`'s end?
Which Christ hath forbidden; but it is the angels`' work at the end of the world.

Why should such as pretend themselves Christians,
imprison and persecute any to death whom Christ hath ransomed,
who gave himself a ransom for all?
And God would have all men saved, and come to the knowledge of the truth;
then why should any be destroyed upon the account of religion?
And Christ said he '`came to save men`'s lives, and not to destroy them.`'

So it is clear,
it is not the mind of God and Christ that men should destroy one another about religions,
ways, and worships, but pray for one another.

And when Christ came, there were too many destroyers of men`'s lives about religion,
in the world; and some of the disciples were giving way to that spirit,
that would have had men`'s lives destroyed that would not receive Christ;
but he came to destroy the devil and his works, who was the destroyer of men`'s lives.
And so Christ came not to destroy men`'s lives, but to save them.
And therefore have all in Christendom, who have destroyed,
not known what spirit they have been of,
that have destroyed so many men and women`'s lives,
by imprisoning and persecuting them about religion and worship,
since the apostles`' days.
And hath not this been contrary to the commands of Christ, and the mind of God?
Who would have all be saved, and all to be prayed for, and to forgive one another,
and to love one another, and to love enemies; yea, to pray for persecutors,
and not be persecutors;
and to be clothers and visitors of Christ in his members in prison,
and not to be casters of him and his members into prison; for Christ,
who tasted death for every man, and gave himself a ransom for all, to wit, men and women;
who saith he came to save men`'s lives, and not to destroy them:
he is the one mediator between God and man.

So judge in yourselves what spirit it hath been,
that hath led professed Christians to persecute, and imprison,
and destroy men`'s lives and estates about religion, church, and worship,
since Christ and the, apostles`' days, seeing Christ bids you '`Love enemies,
pray for persecutors, and them that hate you,
and despitefully use you.`' And therefore my desire is to the Lord,
that all that profess Christianity, may, possess Christ`'s spirit and mind;
and then they will not persecute Christ in his members.

And so I desire that all may come into the fear of God, that they may receive his pure,
gentle, heavenly wisdom, that by it you, may all, be ordered, and order all that.
God gives you under your hands, to his glory.
Amen.

From him that desires nothing in his heart and, soul, but the eternal good,
and all men`'s everlasting happiness and welfare in Christ Jesus.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 24th of the 12th Month, 1682.

[quote.scripture, , 2 Tim. 3:12]
____

All that will live godly in Christ Jesus, shall suffer persecution.
____

[quote.scripture, , Gal. 4:29]
____

He that was born after the flesh, persecuted him that was born after the spirit,
even so it is now.
____

[quote.scripture, , Prov. 21:13]
____

Whoso stoppeth his ears at the cry of the poor, he also shall cry himself,
but shall not be heard.
____
