[.style-blurb, short="Why Adam and Eve Were Driven Out of Paradise"]
== The cause why Adam and Eve were driven out of Paradise, and the Jews out of their own land of Canaan.

[.heading-continuation-blurb]
1+++.+++ Here you may see the cause of Adam and Eve being drove out of Paradise.

[.heading-continuation-blurb]
2+++.+++ And the cause of the destruction of the old world.

[.heading-continuation-blurb]
3+++.+++ And the cause of confounding Nimrod and his company.

[.heading-continuation-blurb]
4+++.+++ And the cause of the Jews going so often into captivity,
and the destructions that came so often upon them.

[.heading-continuation-blurb]
And the confusion that is, and hath been among the Christians,
where all may read, hear and fear,
that they take warning and turn from such evils,
lest the judgments of God come upon you, as they did upon Adam and Eve,
and the old world, and the Jews,
and their forefathers that disobeyed God and Christ, and,
the good spirit that he gave them;
for no unclean thing shall enter into the Paradise and kingdom of God,
nor into the holy city New Jerusalem,
though the unclean do enter into the great city of the whore of Babylon.

[.heading-continuation-blurb]
Adam and Eve were driven out of Paradise for their disobedience,
and for disobedience, Cain`'s stock, and the old world were destroyed.

[.heading-continuation-blurb]
For disobedience, Nimrod and his company were confounded and scattered.

[.heading-continuation-blurb]
And for disobedience,
the Jews were drove and tarried captive out of their own land of Canaan.

And for disobedience to the same light, power, and Holy Ghost,
that the apostles and the church were in, in the apostles`' days,
the Christians in name, and not in power and nature,
are without the heavenly holy city, New Jerusalem.
'`An unjust man is an abomination to the just, and he that is upright in the way,
is an abomination to the wicked.`' Prov. 29:27.
'`In God I will praise his word,
in God I will put my trust.
I will not fear what flesh can do unto me.`' Ps. 56:4.
Thus saith the Lord, '`I will feed them that oppress thee with their own flesh,
and they shall, be drunk with their own blood, as with sweet wine,
and all shall know that I am the Lord.`' Isa. 49:26. By G. F.

The Lord God is holy and pure,
therefore he would have all his people to be holy and pure;
and therefore consider what the Lord in the Old and New Testament commands you to forsake,
and commanded that you shall not do.
In Exodus, the Lord saith, '`Thou shalt not kill.
Thou shalt not steal.
Thou shalt not bear false witness against thy neighbour.
Thou shalt not commit adultery.
Thou shalt not covet thy neighbour`'s house.
Thou shalt not covet thy neighbour`'s wife, nor his man-servant, nor his maid-servant,
nor his ox, nor his ass,
nor any thing that is thy neighbour`'s.`' These things
are forbidden in Ex. 20. in the old testament,
and much more in the new, for Christ saith,
You have heard that it hath been said of old time,`' (to wit,) in the old testament,
'`Thou shalt not commit adultery, but I say, whosoever looketh on a woman,
to lust after her,
hath committed adultery with her already in his heart;`'
and here you may see the law took hold of the outward act,
and the gospel took hold of the inward act.
'`For out of the heart proceed the evil thoughts, murders, adulteries, fornications,
thefts, false witnesses, blasphemies;
these are the things which defile a man.`' Matt. 5:28. and Matt. 15:19.

And these evil things are in man and woman, yea, committed before they be acted outwardly.
And the apostle saith in 2 Cor. 5:10. '`Every one shall
give an account of things done in the body;`' for,
saith he, we must all appear before the judgment seat of Christ,
that every one may receive the things done in his body, according to that he hath done,
whether it be good or bad.
Knowing therefore the terror of the Lord, we persuade men,
etc. to shun that which is bad and evil, and cleave to that which is good,
and lust not after beauty in thy heart, but keep thee from the evil woman;
from the flattery of the tongue of a stranger;
neither let her take thee with her eye-lids.
For by means of a whorish woman, a man is brought to a piece of bread:
and the adulteress will hunt for thy precious life.
But whoso committeth adultery with a woman, lacketh understanding.
He that doeth it, destroyeth his own soul, and a wound and dishonour shall he get,
and his reproach shall not be wiped away.`' Prov. 6:32. And you may
see in Prov. 2:16. this '`strange woman which flatters with her words,
who forsaketh the guide of her youth,`' the spirit of God,
'`and forgetteth the covenant of her God.
For her house enclineth to death, and her paths unto the dead.
None that goeth unto her returneth again,
neither take they hold of the paths of life.`' And therefore,
'`that thou mayst walk in the way of good men,
and keep in the paths of life.`' Prov. 2:20.
This is the exhortation of the wisdom of God to follow:
'`For the mouth of the strange woman is a deep pit, and he that is abhorred of the Lord,
shall fall therein.`' Prov. 22:14. And you may see in
Prov. 5. how Solomon exhorts to the study of wisdom,
and showeth the mischief of riot and whoredom; and Prov. 7. how the silly young man,
void of understanding, in the twilight, in the evening,
in the black and dark night,`' how he was deceived
by the speeches and attire of the harlot,
'`whose house is the way to hell,
going down to the chambers of death.`' And this well-favoured harlot,
deceived the young man under pretence of religion; for she pretended,
she had peace-offerings, and she had paid her vows, and the good man was gone from home;
and this whore abides not in her house, but is without in the streets,
and lieth in wait at every corner; she is out of her house from the spirit of God,
whored from that; and so Christ the good man is not within,
and so that whorish spirit`'s habitation is in the twilight and darkness,
and would beget others, either to spiritual adultery, or carnal adultery.
One while, this whorish spirit is loud and stubborn, and another while,
with flattering speeches.
All that keeps with this spirit of God,
and the light of Christ in their hearts will keep out of her way that leads to hell,
'`and the chambers of death.`'

In Jer. 3. how Jeremiah complains against Judah`'s vile whoredom and committing adultery;
and Judah was worse than backsliding Israel, who said,
'`She is gone upon every high mountain, and under every green tree,
and there hath played the harlot.
And thou hast polluted the land with thy whoredoms, and thy wickedness,
and thou hast a whore`'s forehead,
thou refusest to be ashamed.`' Here you may see what a sad condition the Jews came into,
when they forsook the Lord; and therefore,
let Christians beware that they be not found in the same practice,
and so come under the same judgment,
as you may read in Jer. 3. and v. you may see the judgments of God upon the Jews,
for perverseness and adultery; for the Lord saith, '`How shall I pardon for this,
by children have forsaken me, and sworn by them that are not god`'s;
for when I had fed them to the full, then they committed adultery,
and assembled themselves by troops into the harlot`'s house.
They were as led horses in the morning, every one neighing after his neighbour`'s wife.
Shall not I visit for these things, saith the Lord?
Shall not my soul be avenged on such a nation as this?
And the prophets shall become wind;
and the word is not in them.`' Now let them that
are called Christians in Christendom look to themselves,
and see if they be not found in this spiritual and
natural whoredom that the Jews were found in,
though they made a profession of the scriptures of the old testament;
and they that go under the name of Christians,
may make a profession of the new testament in words, but Jeremiah saith,
the word was not in those Jews, that run into these wickednesses,
neither is it in those called Christians, that run into spiritual or carnal whoredom,
'`for the word of God is a fire, and hammer, and a sword, to beat, and cut down,
and burn up the evil matter, and its fruits.`'

And in Jer. 29:23, speaking to the Jews,
'`Because they have committed villany in Israel,
and have committed adultery with their neighbours`' wives,
and have spoken lying words in my name, which I have not commanded them,
even I know and am a witness, saith the Lord,`' Therefore is their destruction foretold.

And Jeremiah saith, in chap.
ix. '`Oh! that I had in the wilderness a lodging place of a wayfaring man,
that I might leave my people, and go from them: for they be all adulterers,
an assembly of treacherous men.
Their tongue is as an arrow shot out, it speaketh deceit.
One speaketh peaceably to his neighbour with his mouth,
but in his heart he layeth wait for him.
Shall not I visit for these things?
saith the Lord.`' And therefore, saith the Lord, '`I will make Jerusalem heaps,
a den of dragons,`' which was the chief city of worship amongst the Jews;
and did not the Lord bring his judgments upon it?

And Jeremiah saith, '`My heart is broken because of the prophets; and all my bones shake,
and I am like a drunken man, and like a man whom wine hath overcome, because of the Lord,
and because of the word of his holiness, for the land is full of adulteries:
for because of swearing the land mourns, etc.
Their course is evil, and their forces not right.
I have seen also in the prophets of Jerusalem a horrible thing; they commit adultery,
and walk in lies; they strengthen also the hand of evil doers,
that none doth return from their wickedness.
They are all of them unto me as Sodom,
and the inhabitants thereof as Gomorrah.`' Jer. 23. And Jeremiah saith,
'`I have seen thine adulteries, and thy neighings; the lewdness of thy whoredoms,
and thine abominations on the hills in the fields.
Woe be unto thee,
O Jerusalem! wilt thou not be made clean?`' Jer. 13. And again he saith,
'`Thou hast polluted the land with thy whoredoms, and with thy wickedness;
and through the lightness of her whoredoms, (to wit,
the Jews,) and committest adultery with stocks and stones.`' Here
you may see the carnal and spiritual whoredom among the Jews,
who were the greatest professors of the old testament, in their day,
and yet the greatest disobeyers of God; let them that calls themselves christians,
be warned of their sins, and of their judgments.
And the Lord saith, '`Will you steal and murder, and commit adultery,
etc. and come and stand before me in this house, which is called by my name?
And, saying, the temple of the Lord, the temple of the Lord;
and say we are delivered to do all these abominations?
This house which is called by my name is become a den of
robbers.`' So God rejected the vain confidence of the Jews,
and the sacrifice of the disobedient. Jeremiah 7:9.

And Job speaks against the murderers and adulterers, he saith,
'`They are of those that rebel against the light; they know not the ways thereof,
nor abide in the paths thereof; the murderer rises with the light,
killeth the poor and needy, and in the night is as a thief.
The eyes of the adulterer waiteth for the twilight, saying, no eye shall see me,
and disguises his face in the dark.
They dig through houses which they had marked for themselves in the day time;
they know not the light, for the morning is to them as a shadow of death.
Then here was some terror upon the adulterers, if they were known;
but as drought and heat consumeth the snow water,
so doth the grave those that have sinned, etc.
The womb forgets him, the worms shall sweetly feed upon him;
he shall be no more remembered, and wickedness shall be broken as a tree.`' Job 24:15, etc.
See how loathsome wickedness and adultery was in days past.
And Solomon saith, in Prov. 23. '`For an whore is a deep ditch,
she layeth in wait as for a prey,
and increaseth the transgressors among men;`' and this by experience is seen.

And Hosea shows God`'s judgment upon the Jews, for their spiritual and carnal whoredom,
in the first chapter; and further saith, '`By swearing, and lying, and killing,
and stealing, and committing adultery, they break out, and blood touches blood:
therefore shall the land mourn, for whoredoms have caused them to err;
they have gone a whoring from under their God,
they have committed whoredom continually.`' Read the chapter throughout,
and there you may see the abominations and wickedness of the Jews,
and of their spiritual and carnal whoredom, whom God threatens with his judgments.
And in Hosea 2. he saith, '`Let her therefore put away her whoredoms out of her sight,
and her adulteries from between her breasts, lest I strip her naked,
and set her as in the day she was born; and make her as a wilderness,
and set her like a dry land, and slay her with thirst.`' For the Lord saith,
'`I will not have mercy upon her children,
for they be the children of whoredoms.`' '`They are all adulterers,
as an oven heated by the baker, who ceaseth from raising after he hath kneaded the dough,
until it be leavened,`' etc.
Hosea 7. Where you may see God`'s reproof and wrath
against the manifold sins of the Jews,
throughout the whole book.
And therefore, let all that go under the name of christians,
beware of these sins of the Jews, lest the wrath of God come upon you.
And the Lord sent Isaiah to reprove and declare against the Jews,
and their whorish idolatry, and saith, '`The righteous perisheth,
and no man layeth it to heart, and merciful men are taken away;
none considering that the righteous are taken away from the evil to come.
But draw near hither ye sons of the sorceress, the seed of the adulterer and the whore,
against whom do ye sport yourselves; against whom make ye a wide mouth,
and draw out the tongue; are ye not children of transgression,
a seed of falsehood?`' Isaiah 57:4.

And David saith, '`Seeing thou hatest instruction, and castest my words behind thee.
When thou sawest a thief, then thou consentest with him,
and hast been partaker with the adulterers; thou givest thy mouth to evil,
and thy tongue frameth deceit.`' Unto such wicked ones, God saith,
'`What hast thou to do to declare my statutes,
or that thou shouldst take my covenant in thy mouth,`' etc.
Ps. 1. So every one that names God and Christ, must depart from iniquity.
And in Mal. 3. the Lord saith, '`I will come near to you to judgment,
and I will be a swift witness against the sorcerer, and against the adulterer,
and false swearer, and against those that oppress the hireling in his wages,
and the widow and the fatherless, and that turn aside the stranger from his right,
and fear not me, saith the Lord of hosts.`' Here you may see,
God is both witness against wickedness, and the judge of it.

And Ezekiel the Lord sent to denounce judgment upon the Jews for their adultery,
and said, that they were old in adulteries; and they went a whoring after the heathen,
and were polluted with their idols, and had forgotten the Lord,
and cast him behind their backs.
'`Through their lewdness and whoredoms, they have committed adultery,
and blood is in their hands.`' And you may see in chapter xxiii.
throughout, '`They have committed whoredoms in Egypt:
they have committed whoredoms in their youth: there were their breasts pressed,
and there they bruised the teats of their virginity.`'
Oh! let all that are called by the name of christians,
have a care of this spiritual and carnal whoredom.
And Ezek. 6. '`I am broken, saith the Lord,
with their whorish heart which hath departed from me;`'
therefore the Lord threatens his judgment upon them.
And again, the Lord declareth against the Jews`' monstrous whoredom and adultery,
as you may see in chapter xvi.
throughout; they are compared, through their lewdness, and whoredom, and wickedness,
to Sodom.
And in Ezek. 43. they are exhorted to put away their whoredoms,
and their abominations which had defiled God`'s holy name;
so ought all that are called christians, to put away such things that defile God`'s name.
You may see how the Lord forbids adultery in Lev. 20.
and you may see what judgments came upon Israel,
who committed adultery with the children of Moab;
and how the Lord brought his judgments upon Israel,
and them that they committed adultery withal,
as in Num. 25. for the Lord said and cornmanded,
that there should be no whore of the daughters of Israel,
nor a Sodomite of the sons of Israel.`' Duet. 23.
Then surely there ought not to be a whore,
nor a Sodomite amongst them that are called christians; but when either Jews, Christians,
or others, rebel against God`'s good spirit he hath given to instruct them,
then they run into whoredoms and adultery, and are as bad as the Sodomites,
and profane the name of God, and his son Christ Jesus.

And what became of Jezabel, and all her priests, who was called,
'`the mother of whoredoms and witchcraft,`' as in 2 Kings 9:22. Did not her whoredoms,
and her bloody spirit, act together in wickedness and blood shedding?

And the Lord sent Nahum to declare against Nineveh, and the misery and ruin thereof,
and saith, '`Woe to the bloody city!
It is full of lies and robbery; and therefore,
because of the multitude of the whoredoms of the well favoured harlot,
the mistress of witchcraft, that selleth nations through her whoredom,
and families through her witchcraft: behold, I am against thee, saith the Lord of hosts,
I will discover thy skirts upon thy face.
I will show the nations thy nakedness, and the kingdoms thy shame;
and I will cast abominable filth upon thee, and make thee vile;
and will set thee as a gazing stock, and all they that look upon thee,
shall fly from thee, and say,
Nineveh is laid waste.`' Nahum 3. Now Nineveh had repented at Jonah`'s preaching;
but see what whoredoms and wickedness she was run into, which brought her destruction;
and therefore let all that go under the name of christians, take heed of such evils,
lest they bring judgments and destruction, and ruin upon themselves.

And Jacob`'s sons were not able to bear nor endure,
that Shechem should ravish or defile their sister Dinah,
Gen. 34. that they should deal with their sister
as with a harlot;`' and it grieved them,
and they were wroth, because he had wrought folly in Israel,
and therefore that folly is to be kept out of Christendom.

And Joseph, who was tempted by his mistress, the Egyptian woman,
though he was her bought slave, and her captive; yet Joseph said unto her,
'`How then can I do this great wickedness, and sin against my God.`' Gen. 39. But,
as David said, God ordained in Joseph a testimony against such wicked things,
when Joseph was in Egypt; '`and God established a testimony in Jacob,
and Joseph succeeded him in the testimony of God.
Ps. 78. and 5, xviii.
and 5. For David saith, "`He established a testimony in Jacob,
and appointed a law in Israel.`' Mark,
in which he commanded their fathers that they should make them known to their children,
that the generation to come might know them, even the children which should be born,
who should rise and declare them to their children,
that they might set their hopes upon God, and not forget the works of God,
but keep his commandments.
So all that keep the law and testimony of God in their hearts,
will testify against all such evils before mentioned, and judge them.

And the scribes and Pharisees said unto Christ,
in Matt. 12. '`We would see a sign of thee.`' And Christ said unto them,
'`An evil and adulterous generation, seeks after a sign,
but there shall be no sign given unto it, but the sign of the prophet Jonas.
For as Jonas was three days, and three nights in the whale`'s belly,
so shall the son of man be three days and three nights in the heart of
the earth.`' Here is a sign for the evil and adulterous generation,
who rebel against the good spirit that God hath given to instruct them,
that with his spirit they might see Christ the substance of all signs.
And Christ said, '`Whosoever therefore shall be ashamed of me, and of my words,
in this adulterous and sinful generation; of him also shall the son of man be ashamed,
when he cometh in the glory of his Father,
with his holy angels.`' Mark 8. and 38. So we must not be
ashamed to confess the truth before an adulterous generation,
that are adulterated from the truth.
'`Know ye not,`' saith the apostle,
'`that the unrighteous shall not inherit the kingdom of God.
Be not deceived, neither fornicators, nor idolaters, nor adulterers,
nor abusers of themselves with mankind, nor thieves, nor covetous, nor drunkards,
nor revilers, nor extortioners, shall inherit the kingdom of God.`' 1 Cor.
vi. Now they that do think that such as live in these evils,
shall inherit the kingdom of God, they are deceived.
And again, the apostle saith to the Galatians, '`Now,`' saith he,
'`the works of the flesh are manifest, which are these, adultery, fornication,
uncleanness, lasciviousness, idolatry, witchcraft, hatred, variance, wrath, strife,
sedition, heresy, envyings, murders, drunkenness, revilings,
etc. of which I tell you before, as I have also told you in times past,
that they which do such things,
shall not inherit the kingdom of God.`' Gal. 5.
Therefore they are deceived that live in such things,
and think they shall inherit the kingdom of God.
And the apostle saith,
'`Your bodies are the members of Christ,`' speaking to the Corinthians,
and he bids them fly fornication; every sin that a man doth, is without the body.
But he that commits fornication,
sins against his own body,`' as well as against the Lord`'s law and gospel.
And '`Ye are bought with a price.
Glorify God in your bodies, and in your spirits, which are God`'s.`' 1 Corinthians vi.

And the apostle tells the Ephesians, in Eph. 5:3. '`But fornication,
and all uncleanness, or covetousness, let it not be named amongst you,
as becometh saints.
Neither filthiness, nor foolish talking, nor jesting, which are not convenient:
but rather giving of thanks.
For this ye know, that no whoremonger, nor unclean person, nor covetous man,
who is an idolater, hath any inheritance in the kingdom of Christ, and of God.
Let no man deceive you with vain words:
for because of these things cometh the wrath of God upon the disobedient;
be not ye therefore partakers,`' to wit, in such things before mentioned;
for they that live in, and practice such abominable things, before mentioned,
and do think to have an inheritance in the kingdom of Christ, and God,
where no unclean thing enters, they deceive themselves.
'`Therefore let us cast off the works of darkness, and put on the armour of light;
let us all walk honestly, (to wit, true christians,) as in the day;
not in rioting and drunkenness, not in chambering and wantonness, not in strife and envy;
but put ye on the Lord Jesus Christ, and make no provision for the flesh,
to fulfill the lusts thereof.`' Romans 13.

James saith, in chap.
iv, '`Ye lust, and have not; ye kill, and desire to have, and cannot obtain;
ye fight and war, yet ye have not; ye ask, and receive not, because ye ask amiss,
that ye may consume it upon your own lusts.
Ye adulterers and adulteresses,
know ye not that the fellowship of this world is enmity with God?
Whosoever, therefore, will be a friend of this world,
is the enemy of God.`' And therefore, all you that go under the name of Christians,
consider to whom you are enemies, and with whom ye have friendship.

And in 2 Pet.
ii. he shows how God spared not the angels that sinned;
he spared not the old world that sinned,
but brought a flood upon the world of the ungodly, and saved Noah,
etc. the preacher of righteousness.
And God turned the cities of Sodom and Gomorrah into ashes,
and condemned and overthrew them for their sin, wickedness, and ungodliness,
making them an example unto all those that after should live ungodly;
and delivered just Lot, vexed with the filthy conversation of the wicked;
for that righteous man dwelling amongst them, in seeing and hearing,
vexed his righteous soul from day to day with their unlawful deeds.

And now, is not spiritual Sodom,
which makes a great profession of the old and new testament,
as great a grief to the righteous souls, who hear and see their unlawful deeds?
And the apostle saw in this day, such as had forsaken the right way,
which were '`as natural brute beasts,`' and should '`perish in their own corruption,
and shall receive the reward of unrighteousness,
as they which count it pleasure to riot in the day time.
Spots they are, and blemishes, sporting themselves with their own deceivings,
while they feast with you.`' So the apostle hath
marked them to be known by their spots and blemishes,
'`Having eyes full of adultery, that cannot cease from sin, beguiling unstable souls:
a heart they have exercised with covetous practices;
cursed children`' so their hearts were not only full of adultery,
but the apostle could see that their very eyes were full of adultery;
and so is it with the same spirit now.
Such who have forsaken Christ, the right way,
these are wells which have no water in them,
and clouds which are carried about with a tempest,
to whom the mist of darkness is reserved forever.
So clouds, ye know, are high, and ye know what the tempest is;
so they are known by the tempest, that is, in their spirit, and their clouds,
and their great swelling words of vanity, etc.
These are they that promise liberty, and themselves servants of corruption,
and they that are overcome by them, are brought into bondage;
and it is better for such never to have known the way of righteousness,
than after they have known it, to turn from the holy commandment;
but it is happened unto them, '`the dog is turned to his vomit,
and the sow to the wallowing in the mire.`' And are not the days of scoffers come,
which walk after their own ungodly lusts, and not after Christ.
You may see how the apostles, especially Paul, Peter, James, John, and Jude,
bore a testimony against all manner of looseness, and such who had known the truth,
and run into evil, that their latter end would be worse than their beginning.`'

And you may see, in Rev. 17. the mother of all abomination,
'`a woman arrayed in purple and scarlet, with a golden cup in her hand,
sitting on the beast, which is great Babylon,
the mother of harlots,`' who harloted from God`'s good spirit;
this mother of harlots is the abomination of the earth,
which is drunk with the blood of the saints and martyrs of Jesus.
This woman, the false church, who is whored from the spirit of God,
which is drunk with the blood of the martyrs and saints,
'`she is drunk as with wine;`' and this drunken whore is mad,
and in a rage and fury for the blood of the saints.
But what becomes of her in the end?
Is not she burnt in the fire?
And the beast, false prophets, and the devil?
And the Lamb and the saints, will have the victory over them: and this great whore,
or false church, who is whored from the spirit of God,
is the spirit of all them that be harloted from the spirit of God into the evil destroying.
And all those that are led by the spirit of God,
they are of the woman the true church that is in God,
and are of the church of the first born, which are written in heaven;
and heavenly Jerusalem that is above, is their mother; and they sing '`hallelujah,
and glory, and honour, and praises, to the Lord God,
for true and righteous are his judgments:
for he judgeth the great whore which corrupted the earth with her fornication,
and hath avenged the blood of his servants at her hand,
hallelujah.`' Rev. 19. And in Rev. 18. you may see what
great lamentations are from the high and low,
to wit, the harlots which see the downfall of their mother the whore,
who is whored and harloted from the spirit of God; what crying and saying, '`Alas,
alas,`' there is; and what rejoicing of the apostles and the prophets, yea,
the very heaven rejoiceth at the downfall of this whore, yea whorish spirit,
and false church, for in her was found the blood of the prophets and saints,
and all that were slain upon the earth, hath been found in this whorish spirit,
who have whored from the spirit of God and the Lamb.

And in Rev. 21. he saith, '`He that overcometh shall inherit all things,
and I will be his God, and he shall be my son.
But the fearful and unbelieving, and the abominable, and murderers, and whoremongers,
and sorcerers, and idolaters, and all liars,
shall have their part in the lake which burns with fire and brimstone,
which is the second death.`' Whosoever is not found written in the book of life,
is to be cast into the lake of fire; and therefore,
what good will all your profession do in Christendom,
if ye be found in these sins and evils before mentioned,
and your names not written in the Lamb`'s book of
life before the foundation of the world;
for they that have right to the tree of life, walk in the light of the Lamb,
and believe in it; such are they that enter in through the gate into the heavenly city,
New Jerusalem, and have their father`'s name written in their foreheads.
For without this holy city New Jerusalem '`are dogs,`' biters of the lambs of Christ,
'`and sorcerers, and whoremongers, and murderers, idolaters,
and whosoever loveth and maketh a lie;`' all such deceivers, and defilers,
and corrupters of themselves and others, are without the holy city of God, New Jerusalem.
Rev. 22. '`For whoremongers and adulterers,
God will judge.`' Heb. 13:4. And therefore, all that love God and his son,
are to judge such evils, and turn from them,
(before mentioned,) if you will come into favour with God.
And here you may see what wickedness hath been all along,
and in all ages since man and woman fell from the image of God:
and amongst such that rebel against God`'s good spirit,
which he hath given them in the time of the law.

And God pours out of his spirit upon all flesh in this gospel day;
and all such as rebel against this good spirit of God, what idolatry and other evils,
whoredoms, adulteries, and fornications, are amongst them; who, as I said before,
do rebel against God`'s good spirit, which grieves the Lord, and his righteous people,
for which God will judge.
And such as act such things before mentioned, and live in them, the Lord tells them,
they shall not enter into his kingdom, nor into his holy city, New Jerusalem,
for no unclean thing comes into this holy city or kingdom,
all must be made clean with the blood of the Lamb.

And what became of Adam and Eve, who disobeyed the Lord?
Were they not turned out of paradise, the garden of God, the garden of pleasures,
into the earth?

And what became of the old world, who disobeyed and grieved the Lord`'s spirit?
Did not the Lord bring a flood upon them, and destroy them all?
Who saved righteous Noah and his family?

And what became of Nimrod, that mighty hunter before the Lord, and them that followed him?
Did not the Lord say,
'`Nothing will be restrained from them which they
imagined to do;`' and so the Lord confounded them,
and scattered them abroad from Babel, upon the face of all the earth.
Gen. 11. This was the fruit of them that followed their imaginations,
and not the Lord and his spirit.

And what became of Sodom and Gomorrah for their wickedness and filthiness?
Did not the Lord destroy them and their cities by fire, and saved just Lot?
Gen. 19.

And what became of the Jews, to wit, the house of Israel, and the house of Judah?
Who rebelled against God`'s good spirit, who disobeyed the Lord,
and persecuted his prophets,
who went early and late to warn them of the judgments that would come upon them;
but they neither regarded the Lord nor his prophets?
Did not the Lord bring the heathen upon them, which carried them out of their own land,
which flowed with milk and honey, into captivity under the heathen,
in which nature they were gone into who rebelled against God and his spirit.

And what became of the Jews after they came again into their land,
who rebelled against Christ, and cried up Caesar, and crucified Christ,
and persecuted his apostles?
And did not Christ say, '`That their temple should be thrown down,
and the city compassed about with armies,
and the Jews scattered over all nations?`' And did
not this come to pass after Christ was risen?
And did not the Jews also rebel against Titus, when he came to besiege Jerusalem?
So they did not only rebel against Christ, but rebelled against the heathen at last;
and what became of them but destruction and calamity; who,
under a pretence of worshipping God, and crying up the temple, and outward Jerusalem,
and making an outward profession of the old testament, resisted the holy ghost,
and rebelled against God`'s good spirit, and his son Christ Jesus,
in their deceitful hypocritical profession, and living in idolatry,
and spiritual and carnal whoredom and adultery.

And what becometh of the false prophets and beast, of the whore and all her harlots,
that are whored and harloted from the spirit of God?
Must not they all have their end in the lake of fire that burns with brimstone,
with the devil, the god of the world, and the prince of the air,
who rules in the hearts of the children of disobedience,
that disobey God and his good spirit.

And the prince of the air makes many like the unclean
fowls of the air with his foul airy spirit,
by his foul air in whom he rules;
and he is the ruler in all the children of the disobedient,
which disobey God`'s good spirit, he rules in them with his airy unclean spirit,
who blinds the disobedient with his dust and air; for dust is his meat,
who is out of the truth, and abode not in it, in whom there is no truth;
and all that disobey the holy spirit of the lamb, are his followers and subjects,
and he in whom there is no truth, rules in them, who is the author of all sin,
corruption, and darkness, whose end is in the lake of fire that burns with brimstone,
and that of his followers; but the chaste virgins follow the lamb,
and they that are led by the spirit of God, are the sons of God, and walk in the truth,
and '`worship God in spirit and truth.`' His truth is over the head of the devil,
and he is out of it, and cannot get into it, for there is no truth in him,
and therefore he and his followers are not like to get into the truth,
that God`'s children worship God in.

[.signed-section-signature]
G+++.+++ F.
