[#ch13.style-blurb, short="Several Plain Truths Manifested"]
== Several plain truths manifested and declared from the Spirit of God, and borne testimony to by Christ, the apostles, and Scriptures of Truth.

[.heading-continuation-blurb]
I+++.+++ Concerning Mount Zion.

[.heading-continuation-blurb]
II. A distinction betwixt wars and armour in the old testament and the new.

[.heading-continuation-blurb]
III. Concerning Cain.

[.heading-continuation-blurb]
IV. Concerning uniformity, and conformity.

[.heading-continuation-blurb]
V+++.+++ The authority of the church of Christ.

[.heading-continuation-blurb]
VI. Concerning exhorting and admonishing.

[.heading-continuation-blurb]
VII. Concerning such as cry against orders, etc. By G. F.

Mount Zion was a hill higher than other hills, and it stands northwards in Jerusalem,
and therefore is called Zion, that is, a watch-tower, because from this hill,
(Zion,) from it one might see the Holy Land, and all the countries thereabouts;
and upon this bill David built his city, and blew the trumpet:
which Mount Zion and Jerusalem were types of the heavenly Jerusalem and Zion;
for the Lord said, '`I have set my king or anointed upon my holy hill of Zion.
Heavenly Zion is the hill, or mountain of God`'s holiness; beautiful for situation,
the joy of the whole earth is Mount Zion;
let Mount Zion rejoice,`' Ps. 48. For God will save Zion;
the salvation of Israel comes out of Zion, (to wit,) Christ, who is elect and precious,
laid in Zion, but not in the outward hill, or Mount Zion;
for Christ was born in Bethlehem, and David saith by prophecy, concerning Christ,
'`Oh! that the salvation of Israel was come out of Zion!
When the Lord brings back the captivity of his people, Jacob shall rejoice,
and Israel shall be glad.`' Ps. 14.

And again he saith, '`Let Israel rejoice in the Lord that made him,
let the children of Zion be joyful in their king;
for Zion shall be redeemed through judgment,
and her converts through righteousness.`' Is not this Zion God`'s people,
and not the outward hill?
'`For out of Zion shall go forth a law,
and the word of the Lord from Jerusalem.`' Is not this heavenly Jerusalem,
and heavenly Zion, that the word of the Lord and his law go out of,
and not out of the outward hill Zion?
'`In the last days, Isaiah saith,
that the mountain of the house of the Lord shall be established on the top of all mountains,
and exalted above all the hills,
and all nations shall flow unto it.`' Is not this heavenly Mount Zion,
and heavenly Jerusalem?
And Isaiah saith, '`The Lord is exalted, for he dwells on high,
he hath filled Zion with judgment and righteousness.`'
Zion is called a city of our solemnity,
and Jerusalem, '`a quiet habitation, a tabernacle that shall not be taken down;
not one of the stakes thereof shall ever be removed,
neither shall any of the cords thereof be broken.`' Is not this heavenly Jerusalem,
and heavenly Zion?
But let the hypocrites or sinners of outward Zion or Jerusalem be afraid,
which may be removed or broken, which heavenly Zion or Jerusalem cannot;
for no unclean thing enters into it.
'`O Zion! that bringest good tidings, get thee up into the high mountain; O Jerusalem,
that bringest good tidings, lift up thy voice with strength: lift it up, be not afraid;
say unto the cities of Judah,
behold your God.`' So here are Zion and Jerusalem that bring good tidings.

Now, do ye think that this was the outward Jerusalem, or outward hill?
For Christ was born in Bethlehem, a chief corner stone, elect and precious, laid in Zion;
but it doth not say in the outward hill Zion.
Isaiah speaks by prophecy, Isa.
'`He will comfort all her waste places, and he will make her wilderness like Eden,
and her desert like the garden of the Lord; joy and gladness shall be found therein,
thanksgiving and the voice of melody.
I have put my words in thy mouth, and have covered thee, even in the shadow of my hand,
that I may plant the heavens, and lay the foundations of the earth, and say unto Zion,
thou art my people.`' Here you may see that Zion is God`'s people;
and how beautiful upon the mountains are the feet of him that brings glad tidings,
that publishes peace, that brings good tidings of good, that publisheth salvation,
that saith unto Zion, '`Thy God reigns,`' when the Lord shall bring again Zion, to wit,
his people; for the outward mountain, with the outward hill, was not removed.
And the redeemer shall come to Zion, and unto them that are turned from transgression.
Isa. 59. and Rom. 11. And this redeemer is Christ.
And Isaiah saith, '`Who hath seen such a thing, and who hath heard such things?
Shall a nation be born at once?`' For so soon as Zion travailed,
she brought forth her children.

Now, here you may see the wonder of Zion`'s travail, which was not the great hill,
nor watch-tower in Jerusalem.
And Zachariah saith, '`The Lord shall yet comfort Zion,`' that is, his people. Zach. 1.
And Zachariah saith, Shout thou daughter of Zion.`' And again he saith to Zion,
'`Let not thy hand be slack.`' So Zion was and is God`'s people.

And Micah saith, '`In the last days,
etc. the mountain of the house of the Lord shall be established above all the mountains,
and it shall be exalted above all the hills`' So, here is God`'s heavenly mountain,
or watch-tower, which is above all hills or mountains, and people shall flow unto it,
and many nations shall come, and say, '`Come, let us go up to the mountain of the Lord,
and to the house of the God of Jacob, and he will teach us of his ways,
and we will walk in his paths.`'

Here God is the teacher of his people, and nations;
for these last days are the days of Christ, in his new covenant or testament,
where the Lord goes forth from heavenly Zion, the mountain of the house of God,
established above all mountains, and the word from heavenly Jerusalem,
that is above old Jerusalem,
which was the word of faith (the apostles preached) in people`'s hearts and mouths.
Rom. 10. Micah 4. Isa. 2.

The Jews, in the old testament, they had the law given to them at the outward hill,
Mount Sinai, who had the outward hill north in Jerusalem, called Mount Zion,
and read the outward law in outward Jerusalem; but the mountain of the Lord,
or heavenly Mount Zion, which is called the mountain of the house of the Lord,
is established on the top of all the mountains, and exalted above all the hills,
so that all nations may see it and flow unto it.
And Obadiah saith, '`Upon Mount Zion shall be deliverance,
etc. and saviours shall come upon Mount Zion, to judge the Mount of Esau,
and the kingdom shall be the Lord`'s.`'

And the apostle saith, Rom. 9., '`As it is written, behold,
I lay in Zion a stone of stumbling, and a rock of offence,
and whosoever believeth on him shall not be ashamed.`' And Peter saith, 1 Pet.
2, '`Behold I lay in Zion, a chief corner stone, elect and precious,
and he that believeth on him, shall not be confounded;
to all that believe in him he is precious, but unto them that are disobedient,
he is a stone of stumbling, and a rock of offence, who stumble at the word,
the stone which the builders disallowed,
(viz. the outward professors,) the same is made the head of the
corner of God`'s house,`' whose house God`'s people are,
and in this Zion, the chief corner stone, which is laid in Zion,
was not laid in the hill called Zion, in outward Jerusalem; for Christ,
the chief corner stone, was born in Bethlehem, as is said before.

And the apostle writes to the church in his epistle to the Hebrews, and said,
They were not come to the Mount Sinai, where they received the law,
but ye are come to Mount Zion, the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels; and they were come to the general assembly,
the church of the first born, which are written in heaven, and to God the judge of all,
and to the spirits of just men made perfect,
and to Jesus the mediator of the new covenant, and to the blood of sprinkling,`' etc.
See that ye refuse not him that speaks from heaven;
if we turn away from him that speaks from heaven, whose voice shakes not the earth only,
but the heavens also, but if ye hear the voice of Christ and follow him,
ye will receive his kingdom that cannot be moved nor shaken.

And now, all ye Christians, that profess Christianity, are ye come to Mount Zion?
Or are ye under the law which came from Mount Sinai, not Mount Zion?
Which law commanded tithes, offerings, sacrifice, oaths, and swearing,
with outward tabernacle, sanctuary, and temple,
and priests`' lips to preserve people`'s knowledge,
commanded by the law in the old testament.
And if ye be come to Mount Zion, and heavenly Jerusalem, the city of the living God,
then you see the innumerable company of angels, and the spirits of just men made perfect;
and they that are come here, their names are written in heaven;
and such are come to Jesus, the mediator of the new covenant, who speaks from heaven,
whose voice shakes the heavens and the earth, that are to be shaken,
that those things that cannot be shaken, may remain.
Heb. 12. And John said, Rev. 14. '`He saw a lamb stand on Mount Zion,
and with him a hundred forty-four thousand,
having their father`'s name written in their foreheads;
which were redeemed out of the earth, and from amongst men, and they followed the lamb;
and in their mouths were found no guile,
for they are without fault before the throne of God; and they sung a new song,
before the throne, and no man could learn that song,
but the hundred forty-four thousand which were redeemed,`' etc.
Then surely this was spiritual, this was heavenly Zion, and not earthly,
which the hundred and forty-four thousand stood upon, which were redeemed from the earth,
and so from earthly Zion, and earthly Jerusalem, and all those earthly things;
that followed Christ the Lamb, and was with him after he was risen,
before the throne of God.

G+++.+++ F.

Gouses in Essex, the 13th day of the 2d month, 1683.

[.inline]
=== A distinction between the Wars and the Weapons, and the Arms and the Armour in the Old Testament and the New; for in the Old Testament they were carnal, and in the New Testament Spiritual.

The apostle bids the church of Christ, '`Put on the whole armour of God,
that ye may be able to stand against the wiles of the devil;
for we wrestle not against flesh and blood, but against principalities and powers,
against the rulers of the darkness of this world,
against spiritual wickedness in high places.`' So
this wrestling was with spiritual weapons,
spiritual men; for carnal men wrestle with flesh and blood, and with carnal weapons,
and men`'s armour, and not the armour of God.
And again the apostle saith, '`Take unto you the whole armour of God,
that you may be able to stand in the evil day, and having done, and having overcome all,
to stand, having your loins girt with truth.`'

So this is a heavenly girdle, not natural;
and '`having on the breastplate of righteousness,`' this is a spiritual breast-plate,
not natural;
'`having your feet shod with the preparation of the gospel
of peace,`' which is the power of God over the devil,
and before he was; to be shod thus, is not with outward shoes,
but with that which will never wax old nor wear out; '`and above all,
take the shield of faith,`' that faith which Christ is the author and finisher of,
'`wherewith ye shall be able to quench all the fiery
darts of the wicked;`' this shield of faith is holy,
divine, and precious, and is the victory; which spiritual faith,
God and Christ is the author of, and not men.
'`And take unto you the helmet of salvation, and the sword of the spirit,
which is the word of God.`' Phil. 6. This helmet of salvation is spiritual,
and the sword is spiritual; so not a natural sword or a natural helmet;
and the word of God is called a hammer, a fire, and a sword, to hammer down,
and cut down, and burn up that which hath made a separation between man and God;
and it is called the '`word of reconciliation,
that reconciles to God.`' So the true church and ministers
of Christ are to prove themselves '`by pureness,
by knowledge, by long suffering, by kindness, by the holy ghost, by love unfeigned,
by the word of truth, by the power of God, by the armour of righteousness,
on the right hand and on the left.`' 2 Cor.
vi.

For though the church of Christ do walk in the flesh, yet the apostle saith,
'`We do not war after the flesh; for the weapons of our warfare are not carnal,
but mighty through God, to the plucking down of strong holds, (to wit,
of Satan,) casting down imaginations,
and every high thing that exalts itself against the knowledge of God,
and bringing into captivity every thought to the obedience of Christ,
having in readiness to revenge all disobedience.
This is with spiritual weapons, not carnal.
2 Cor.
x.

And the apostle saith to the Romans, '`The night is far spent, and the day is at hand;
let us cast off therefore the works of darkness,
and put on the armour of light.`' This armour of light is not natural,
but divine and spiritual, to all the children of the light, and of the day.
This armour of light is before darkness was, and the devil the power of it, and he,
the power of darkness cannot pierce through this armour of light;
and this armour of light is above all natural and carnal armour;
and all the children of the light, that walk in this light, and this armour,
they walk honestly, and decently, as in the day; for they that walk in '`rioting,
drunkenness, chambering and wantonness, make provision for the flesh,
to fulfill the lust thereof;`' such are naked concerning armour of light,
and though they may make profession of Christ, they do not put him on, as in Rom. 13.

And Christ saith, '`When a strong man armed keeps his house, his goods are at peace,
but when a stronger than he shall come upon him, and overcome him,
he takes from him all his armour wherein he trusted, and spoils his goods,`' etc.
Is not Christ stronger than the devil that hath kept the house of the hearts of people?
And doth not he disarm him and spoil his goods?
And are not Christ`'s weapons spiritual?
And the Lord saith to Zachariah, '`Not by might, nor by power, (to wit,
of men,) but my spirit, saith the Lord of hosts.`' Zach.
iv. The Lord saith, '`Comfort ye my people, speak ye comfortably to Jerusalem,
and cry unto her that her warfare is accomplished, that her iniquity is pardoned,`' etc.
Is not, this Jerusalem God`'s people, whose iniquity Christ pardons,
and warfare is accomplished.
Isa. 40. And again Isaiah saith, (Isa. 2. and Micah 4.,) speaking of Christ.
'`He shall judge amongst the nations, and shall rebuke many people,
and they shall beat their swords into plough shares, and their spears into pruning hooks.
Nation shall not lift up sword against nation, neither shall they learn war any more,
but they shall sit every man under his vine, and under his fig tree,
and none shall make them afraid,
for the mouth of the Lord of hosts hath spoken it.`' Is not this vine Christ,
and are not these the days of his gospel of peace?

And David saith, Come, behold the works of the Lord,
what desolation he makes in the earth, he makes wars to cease unto the ends of the earth,
he breaks the bow and cuts the spear in sunder,
he burns the chariots in fire.`' Ps. 46. The Lord rebukes the company of spearmen,
the multitude of the bulls, with the calves of the people,
until every one submit himself, (to wit,
to the Lord,) who scatters the people that delight in war.`'
And are not these the days of Christ in the new testament,
'`who ascended on high, and led captivity captive, and gave gifts unto men,
that the Lord God might dwell amongst them.`' Ps. 68. and Eph.
4:8. where the apostle shows the fulfilling of it;
and the apostle James saith, in his General Epistle to the church of Christ,
'`From whence come wars and fightings amongst you?
Come they not even of your lusts, that war in your members.`' (Mark,
in your members.) James 4. So here is a war in your members,
the ground of it is from your lusts,
before the wars and fightings were outwardly amongst people,
which wars and fightings without, come from the lusts of the members within.
And the apostle saith to the Hebrews, in the 11th chapter,
'`Who by faith subdued kingdoms, stopped the mouths of lions,
quenched the violence of fire,
escaped the edge of the sword.`' This was the shield of faith,
a stronger weapon than outward swords, and is a stronger weapon than fire,
and can quench the violence of it, that stopped the mouths of lions:
this is beyond carnal weapons, which fire and lions may overcome.

And the apostle exhorts Timothy, 2 Tim.
'`Thou, therefore, my son, be strong in the grace that is in Christ Jesus,
and endure hardship,
as a good soldier of Jesus Christ.`' But Timothy did not war with flesh and blood,
with carnal weapons, as he was a soldier of Christ,
but with Christ`'s heavenly arms and armour; for as the apostle Peter saith,
in his General Epistle to the church,
'`Forasmuch then as Christ hath suffered for us in the flesh,
arm yourselves likewise with the same mind, (to wit,
of Christ,) for he that hath suffered in the flesh, hath ceased from sin,
that he no longer should live the rest of his time in the flesh to the lusts of men,
but to the will of God.
For the time past of our life,
may suffice to have wrought the will of the Gentiles or nations.`'

And the apostle saith to the Romans, chap.
vi. '`Yield not your members as instruments of unrighteousness unto sin,
but yield your members unto God, as those that are alive from the dead,
and your members as instruments of righteousness unto God.`' So it is clear,
that they that yield their members as instruments of unrighteousness unto sin,
are not alive unto God;
and the two witnesses that had power to smite the earth as often as they would,
do you think that they did it with carnal weapons?
'`And there was war in heaven, Michael and his angels fought against the dragon,
and the dragon fought and his angels, and the dragon prevailed not,
neither was there any more place found in heaven for him,
but he and his angels were cast out into the earth.`' Rev. 12.

Now the holy angels of God are spirits, so then they had spiritual weapons,
and not carnal swords, muskets, pikes, and pistols, etc. to fight with the dragon.
And John said, '`I saw heaven open, and behold, a white horse, and he that sat upon him,
was called faithful and true, and in righteousness he doth judge, and make war,
etc. and he was clothed with a vesture dipped in blood, and his name was called,
the word of God; and the armies which were in heaven followed him, upon white horses,
clothed in fine linen, white and clean; and out of his mouth goes a sharp sword,
that with it he should smite the nations; and he shall rule them with a rod of iron, etc.
And the beast, and the kings of the earth, and their armies, gathered together,
to make war against him that sat on the horse, and his army, who is King of kings,
and Lord of lords; but the beast was taken, and the false prophet,
etc. and them that had received the mark of the beast, and had worshipped his image,
these both were cast alive into the lake of fire burning with brimstone,
and the remnant were slain with the sword of him that sat upon the white horse,
which sword proceeded out of his mouth.`' Rev. 19.

And were these, think you, carnal weapons, that Christ and his followers made war with,
against the beast and the false prophet,
and they that worshipped the beast and his image, and received his mark, and took them,
and overcame them,
and cast the beast and the false prophet into the lake that burns with brimstone?
And was that an outward carnal sword that went out of his mouth,
by which he slew the beast`'s worshippers, that had his marks and image?
Do you think that Christ, or his army, that sat on white horses, and followed him,
which were in heaven, that they had outward swords, and pistols, and pikes, and muskets,
and guns, and cannons, by which they overcame the beast and the false prophet?
No; it is said,
'`that Christ`'s army was clothed with fine linen and Christ`'s
vesture was dipped in blood,`' which army followed him in heaven.

Nebuchadnezzer lift up his eyes to heaven, and blessed the Most High, and said,
all the inhabitants of the earth are reputed as nothing,
and the Lord doth according to his will, in the armies of heaven,
and amongst the inhabitants of the earth, and none can stay his hand, nor say unto him,
what dost thou?
Here you may see Nebuchadnezzer was made to confess to the great God,
who saw his armies in heaven, who abased his pride.
And Jesus said unto Pilate, '`My kingdom is not of this world;
if my kingdom were of this world, then would my servants fight,
that I should not be delivered to the Jews;
but now is my kingdom not from hence,`' (that is,
of this world.) John 18:36. Here you may see a
distinction betwixt the new covenant and the old,
and the kingdom of Christ, and the kingdoms of this world, and their arms and armour.

[.asterism]
'''

The apostle exhorts the Ephesians, '`My brethren,`' said he, '`be strong in the Lord,
and in the power of his might; put on the whole armour of God,
that ye may be able to stand against the wiles of the devil;
for we wrestle not against flesh and blood, but against principalities, powers,
and rulers of darkness of this world, and against spiritual wickedness in high places.
Wherefore, take unto you the whole armour of God,
that you may be able to stand in the evil day, and having done all, or overcome all,
to stand.
Therefore, having your loins girded about with truth,
and having on the breast-plate of righteousness,
and your feet shod with the preparation of the gospel of peace; above all,
taking the shield of faith,
wherewith ye shall be able to quench all the fiery darts of the wicked one;
and take the helmet of salvation, and the sword of the spirit, which is the word of God;
and praying always with all prayer and supplication in the spirit, +++[+++mark,
in the spirit they are to pray,]
watching thereunto with all perseverance,
and supplication for all the saints.`' Is not this
generally to be practised now by all true christians,
as it was in the apostles`' days?
And the apostle saith to the Romans, '`The night is far spent, the day is at hand,
let us therefore cast off the works of darkness,
and let us put on the armour of light.`' So light, you see, is your armour,
which will defend you against darkness, and the prince of the power of it,
and their weapons; and all such that hate the light of Christ, and are against it,
are naked, and are without the light, which is the true armour;
and you may see what the saints did do,
and what victory they had with the shield of Faith, in Heb. 11.

And the apostle said,
'`He was set for the defence of the gospel,`' which is the power of God,
and that was in the shield of faith.

And David said, '`Thou, O Lord, art a shield for me, my glory,
and the lifter up of my head;`' so he is now to all his people.
And further, Thou hast given me the shield of thy salvation,
and thy right hand hath holden me up,
and thy gentleness hath made me great.`' All must feel this shield of salvation from God,
and if they be held up, it must be by his right hand.
And again, David saith, '`The Lord is my strength and my shield,
my heart trusteth in him, and I am helped; therefore my heart greatly rejoiceth;
and with my tongue will I praise him.`' This was not an outward shield,
but the Lord was his strength and his shield:
so God is to all his people in all their troubles.

And David said, '`The Lord is my rock, and my fortress, and my deliverer, my God,
my strength, in whom I will trust, my buckler, and the horn of my salvation,
my high tower.`' Mark, a rock, fortress, deliverer, strength, horn of salvation,
high tower; the Lord God was so to David, and is so to all his people;
God`'s way is perfect, the word of the Lord is tried, and endures forever,
and God is a buckler to all those who trust in him.
And again, saith David, '`The eyes of the Lord are upon them that fear him,
etc. to deliver their souls from death, and to keep them alive from famine.
And David said, '`Plead my cause, O Lord, with them that strive with me;
fight with them that fight against me; take hold of shield and buckler,
and stand up for my help, etc. and stop the way against them that persecute me;
and say unto my soul, I am thy salvation.`' Here David looked unto the Lord,
his shield and buckler, and his help,
to plead his cause against them that strove and fought against him;
and so should all God`'s people.
And David saith, '`I will sing of thy power; yea, I will sing aloud of thy mercy;
for thou hast been my defence and refuge in the day of my trouble.`' And
therefore let all God`'s people now know the Lord to be their defence,
and refuge in the time of trouble.
And David said, '`The Lord is only my rock and my salvation, he is my defence,
I shall not be greatly moved;`' so he is to all his people.

David saith, '`Blessed is the man whose strength is in thee;
they grow from strength to strength, every one of them in Zion appear before God.
Behold, O God, our shield, look upon the face of thine anointed;
for the Lord God is a sun, and a shield, and the Lord will give grace, and glory,
and no good thing will he withhold from them that walk uprightly.
He shall cover thee with his feathers; thou shalt not be afraid of the terror by night,
nor for the pestilence that walketh in darkness,
nor for the destruction that wasteth at the noon day;
and under the Lord`'s wings thou shalt trust,
his truth shall be thy shield and buckler;`' so no outward shield or buckler;
'`but the Lord is my defence, and the rock of my refuge.`' So he is of all God`'s people.
O ye that fear the Lord, trust in the Lord; he is their help,
etc. their shield that trust in him; for `'thou art my hiding-place and my shield;
my hope is in thy word; depart from me, ye evil doers,
for I will keep the commands of my God.`' Here is the bold
confidence and steadfastness of all God`'s people.
'`Blessed be the Lord, my strength, my goodness, my fortress, my high tower,
and my deliverer, and my shield; and he in whom I trust,`' etc.
Here you may see the Lord was all to David, who said,
'`I know the Lord will maintain the cause of the afflicted,
and the right of the poor,`' etc.

Therefore, as the apostle saith to the Thessalonians, '`let us who are of the day,
be sober, putting on the breast-plate of faith and love, and for a helmet,
the hope of salvation.`' This was the children of light`'s heavenly armour and defence,
which they had from God, and Christ, and not out of smith`'s shops;
for such will not defend them from the devil. 1 Thess. 5:8.

G+++.+++ F.

[.inline]
=== Concerning Cain.

And the Lord God said unto Cain, '`If thou dost well, shalt thou not be accepted?
If thou dost not well, sin lies at thy door, and unto thee shall be his desire,`' etc.

So here you may see, it is not only saying or talking well, but acting, and doing well,
if they be accepted with the Lord God; for if ye talk and say never so well,
and if ye do not do well, but evil, sin lies at the door of your hearts,
and gets into your hearts, (if ye do evil,) and then makes you persecutors and murderers,
like Cain; and so not doing well, ye do not rule over sin, but sin gets into you,
and rules over you, and the Lord God hath no respect to such, nor their offerings,
nor sacrifices, nor fair speeches, nor good words, that do not well.
But if ye do well, then the Lord will accept you,
as you may see in Gen. 4. And Christ saith, '`Blessed is that faithful servant,
whom the Lord, when he comes, shall find so doing;`' to wit, doing the will of God.
Christ said to his disciples, '`When ye shall have done all these things,
which are commanded you, say, we are unprofitable servants,
we have done that which was but our duty to do.`' Luke 17. So here you may see,
that which would boast of his doings is to be kept down, and kept out,
for it is every servant of God`'s duty to do his will.

And the Jews said unto Pilate, Crucify him, crucify him,`';(to wit,
Christ,) and Pilate said three times over,
'`What evil hath he done?`' Luke 23. But the Jews that did evil,
could not accuse him of any evil that he had done;
for Christ came to bruise the serpent`'s head, and destroy the devil and his works,
and to finish transgression, and to make an end of sin,
and to bring in everlasting righteousness into the hearts of his people.
And Peter said, '`Of a truth, I perceive that God is no respecter of persons,
but in every nation, he that fears God, and worketh righteousness, is accepted with him.
So here you may see, it is not he that talketh of righteousness out of the fear of God,
and worketh not righteousness, that is accepted with the righteous God,
as in Acts 10:35. For Christ saith, '`Every one that doth evil hates the light,
neither comes to the light, lest his deeds should be reproved.`'

Now, here you may see, who are them that hate the light of Christ,
who is the life in him, who enlightens every man that comes into the world;
every one that doth evil hates the saving heavenly light of Christ,
which they should believe in, and become children of the light; and they that do evil,
and hate the light, neither come to the light, lest their deeds should be reproved.
All these doers of evil, and haters of the light of Christ, and that will not come to it,
lest their evil deeds should be reproved; all such,
God nor Christ doth not accept their offerings nor sacrifices.
And such that hate the light of Christ, hate Christ; though they may preach him,
and profess him in words, yet they persecute,
and hate the believers in the light of Christ, which are the children of the light,
and walk in the light, and are the children of the day of Christ.

And again, Christ saith, '`He that doth truth comes to the light,
that his deeds may be made manifest that they are wrought
in God.`' So it is not he that only talks of truth,
but, (mark,) he that doth truth, comes to the heavenly and spiritual light of Christ,
that with his spiritual light he may see his deeds, that they are wrought in God.
This is a blessed work, and a blessed sight to see, and a happy comfort,
and a satisfaction to every one, and such God doth accept, and respect their offering.
And all the children of the Lord are, to be tender one to another; for Christ saith,
'`If I then, your Lord and master, have washed your feet,
ye also ought to wash one another`'s feet; for I have given you an example,
that ye should do as I have done unto you,`' as in
John 13. And this is a practice of humility,
in condescending, in the tender light of Christ, one to another.

And John in his General Epistle, saith, '`Little children, let no man deceive you,
he that doth righteousness, is righteous, even as he is righteous;
whosoever doth not righteousness, is not of God,`' etc.
So here you may see, it is not the puffed-up boasters and talkers of righteousness,
but them that do it, that are of God.
And was it not the reason that Cain slew his brother, because his works were evil,
and Abel`'s were righteous?
And is it not the cause now of prisoning and persecuting, both with tongue and hand,
because their works are evil, and of them that did and do persecute the righteous now?
But let them not be weary in well- doing; for in due season they shall reap,
if they faint not; for they that do evil, sow to the flesh,
and shall of the flesh reap corruption; but he that is in the spirit of God,
sows to the spirit,
and shall of the spirit reap life eternal.`' And whatsoever good thing any man doth,
the same shall he receive of the Lord, whether he be bond or free;
for there is no respect of persons with God,
for he doth accept all that are the servants of Christ,
and do the will of God from their hearts.
But he that doth wrong, receives for the wrong which he hath done;
for God is no respecter of persons,
for he doth render to every man according to his deeds;
to them who by patience continue in well-doing, seek for glory, and honour,
and immortality, eternal life; but unto them that are contentious,
and do not obey the truth, but obey unrighteousness, indignation, wrath, tribulation,
and anguish upon every soul of man that doth evil, of the Jew first,
and also of the Gentile; but glory, honour, and peace to every man that worketh good,
to the Jew first, and also to the Gentile; for there is no respect of persons with God.
And as Christ saith, '`Every good tree bringeth forth good fruit,
and a corrupt tree bringeth forth evil fruit.`' So by their fruits trees are known;
'`for it is not every one that saith, Lord, Lord, shall enter into the kingdom of heaven,
but he that doth the will of my Father which is in heaven.`'

So here you may see that it is not the talkers of God and Christ,
that enter into the kingdom of God, but every one that hears the sayings of Christ,
and doth them, is likened unto a wise man, which built his house upon a rock,
that neither the rain, floods, nor wind, shall beat it down,
because it is founded upon a rock!
But every one that hears the sayings of Christ, and doth them not,
is likened to a foolish man which built his house upon the sand; and the rain,
and the floods, and the winds, beat upon his house, and it falls,
and great is the fall of it.
These are they that do not the will of God; these are the sayers, and not the doers;
these are them that walk not in the light, nor grace, nor truth, nor spirit,
nor gospel of Christ; these are the hearers of the word, but not doers of the word,
which deceive their own selves,
and are likened to a man that beholds his natural face in the glass,
and straightway forgets what manner of man he was:
but that man which is the doer of the work, and the word of God, is blessed in his deed;
to him that knows to do good, and doth it not, to him it is sin.
And Christ said, the Jews, Scribes, and Pharisees, they say and do not; that is,
they said Moses`' and the prophet`'s words,
but they did not Moses`' and the prophet`'s words.
And now the Christians, they have Christ`'s and the apostles`' words,
and say them often over; but the same woe will be to them that do them not,
that was against the Pharisees.
And Christ saith, '`But all their works they do for to be seen of men.
But such works and doers are not accepted with God and Christ;
for he cries woe against such workers.
And Christ commended them that improved their talents, and said unto them, '`Well done,
good and faithful servants, that had been faithful in a few things,
he would make them ruler over many things;`' and said '`Enter into
the joy of the Lord.`' So the wicked go into everlasting punishment,
and the righteous into life eternal.
And therefore the saints are to take unto them the whole armour of God,
that they may be able to stand in the evil day,
and having done all to stand in his armour; for every sin that a man doth,
is without his body,
and every one shall receive according to the things done in his body.

So here you may see,
he must have truth`'s judgment and sentence upon the sins done out of the body,
and upon the sins done in the body, by thoughts and imaginations,
before they be acted outwardly.
So every one shall receive a reward and judgment according to his works,
whether they be good or evil; and therefore all the saints have need of patience,
to exercise that gift that after they have done the will of God,
they might inherit the promise of eternal life; for so is the will of God,
that with well doing ye may put to silence the ignorance of foolish men.
So it is not only well-talking, but well-doing;
for it is said that God hears not sinners; for they that go into sin and do evil,
go out of God`'s spirit of grace and favour;
but if any man be a worshipper of God in his spirit and truth, and doth his will,
him he heareth in his spirit.
And therefore are all God`'s children exhorted to walk in the faith, and by the faith,
which Christ is the author of; to walk in the light of Christ,
in which they have fellowship one with another; and to walk in the spirit of God,
by which they are circumcised and baptized, in which they have fellowship;
and to put on the Lord Jesus Christ, and to walk in him.
So it is not only talkers of the light, and spirit, and faith,
and of the will of God and Christ, and his will and his doctrine,
but they that walk in his will, and do his will, etc. that are accepted,
and enter into his kingdom, that he hath prepared for them.

G+++.+++ F.

[.inline]
=== Uniformity and Conformity proclaimed to the whole world, in the name of the eternal God, and his Son Christ Jesus.

God so loved the world, that he gave his only begotten son,
that whosoever believes in him should not perish, but have everlasting life; for,
'`as in Adam all die, so in Christ shall all be made alive.`' And Christ,
by the grace of God, hath tasted death for every man,
and is a propitiation for the sins of the whole world,
the one mediator between God and man; through death destroys death, and the devil,
that had the power of death; for sin brought death, and the devil,
who abode not in the truth, in whom there is no truth, he is the power of death;
and Christ, who is the truth and the life, makes an end of sin, that brought death,
and destroys death and the devil, and his power of death.
For the son of God was manifest that he might destroy the works of the devil,
and finish transgression, and to make an end of sin,
and to make a reconciliation for iniquity,
and to bring in everlasting righteousness into man and woman.

Here is the work of the son of God, who bruises the serpent`'s head, breaks his power,
and destroys the destroyer; he is the saviour, called the seed of the woman,
in which seed (Christ) all nations are blessed, which bruises the serpent`'s head,
who hath brought man into the curse and sin, darkness and corruption, etc.
But in this seed (Christ) that bruises the serpent`'s head, and destroys his works,
are all nations blessed, and all in uniformity, unity, and fellowship one with another,
and with the son and the Father.
And therefore, all must come into this seed, Christ Jesus,
if they come into the heavenly unity and uniformity; and that ye may know him,
and the power of his resurrection, and the fellowship of the sufferings of Christ,
being made conformable unto his death, who, by the grace of God,
tasted death for every man; for in Adam all died.
Now, Christ, by the grace of God, having tasted death for every man,
that every man may be conformable unto his death;
here is a conformity unto the death of Christ;
for ye must all die with him before ye live with him, and ye must all suffer with him,
if ye reign with him And therefore all men and women in the whole world,
of what religion or opinion soever ye be of, in old Adam ye all died, and are dead,
and Christ, by the grace of God, hath tasted death for you all,
and by Christ ye may all be made alive;
and therefore ye must all be made conformable to Christ`'s death,
and that is the conformity ye are all to press after,
and to exhort one another to be conformable to the death of Christ, and to die with him,
if ye do intend to live with him; and to suffer with him,
and to come into the fellowship of his sufferings, if ye reign with Christ,
or do intend to reign with him; yea, all that do profess Christ the son of God,
they ought to be conformed to the image of the son of God;
and if that ye be not conformed to the image of the son of God,
who destroys the devil and his works,
your outward profession will stand ye in no more stead,
than the Jews`' profession without life;
but all that are conformable to the image of the son of God,
in his image they are in uniformity, and in unity, hallelujah, praising the Lord.

And the apostle saith to the saints, '`Be not conformed to this world,
but be ye transformed by the renewing of the mind, etc. to the image of the son of God,
and being made conformable unto his death.`' Phil. 3:10. Rom. 8:29. and xii.
2+++.+++ And now, all people, if ye be not conformable to the death of Christ,
that hath tasted death for you all, then you are yet alive in your sin;
and if ye be not conformed to the image of the son of God,
who bruises the serpent`'s head, and destroys the devil and his works,
what image then are ye conformable to?
All your profession, without ye be conformed to the image of the son of God, is nothing;
which who do so conform, are in the heavenly unity and conformity, and Christ,
who tasted death for every man,
(for all died in Adam,) he enlightens every man that comes into the world,
with his heavenly light, which is the life in him, the word,
by whom all things were made.
Now, every man and woman being turned to the light, which is the life in Christ,
and believing in it, and walking in it,
is the means by which they may be made conformable to the image of the son of God,
and so come into unity, and conformity, and fellowship, one with another,
and with the Father and the Son.

And the grace of God which brings salvation, hath appeared unto all men;
which grace taught the church of Christ, which grace and truth came by Jesus; now, I say,
this grace taught the church of Christ to live godly, righteously,
and to deny ungodliness and unrighteousness, and to live soberly in this world.
Now, if all people will be conformed to the image of the son of God,
it must be through this grace that comes from the son of God;
and this grace is in their hearts, to settle them, and establish them,
which teaches them to deny that which is ungodly and unrighteous,
and to receive and cleave to that which is godly and righteous.

And so, here are God`'s love and favour to all men, who died in Adam,
that his grace and favour should appear unto all men,
to teach them and bring their salvation,
that they may be made conformable to Christ`'s death, who hath tasted death for them all,
and die and live with him, and suffer and reign with him,
and so be conformable to the image of the son of God; and here is a heavenly, divine,
and spiritual conformity and uniformity.

And Joel saith, by prophecy, '`It shall come to pass in the last days,
I will pour out my spirit upon all flesh.`' Now these last
days are the days of the new covenant and new testament,
and the days of the gospel of salvation, preached to every creature, man and woman,
that all might be obedient and conformable to the power of God, the gospel of salvation;
and so, as all are conformable to this glorious gospel of Christ,
they will be conformed to the image of the son of God,
and so into a glorious peaceable uniformity and conformity,
fellowship and unity in the gospel, the power of God,
which brings life and immortality to light;
and in this power of God they will see over the power of the devil, and before he was,
that hath darkened them.
And likewise, God who poured out of his spirit upon all flesh, both men and women,
that all with the spirit of God might mortify the deeds of the flesh,
and in the spirit of God live, and that all with the spirit of God might be circumcised,
and put off the body of death, and sins of the flesh,
that`'s come into them by transgression, and disobeying of God,
so that all in the spirit may be conformable to the image of the son of God,
and be in unity and a spiritual fellowship and uniformity,
through the spiritual conformity.
For all the sons and daughters of God are led by the spirit of God;
and here is a spiritual conformity, and a heavenly uniformity,
amongst the sons and daughters of God;
and God having poured out of his spirit upon all flesh, that is, all men and women,
that all men and women might be conformable to this holy pure spirit of God,
which spirit of God will baptize them, if they do not quench, vex, grieve,
and rebel against it, or err from it, I say, it will baptize them all into one body,
which Christ, the Lord from heaven is the head of;
and so with this holy spirit that baptizes into one body,
are all made to drink into one spirit.

Here is a spiritual conformity, and a heavenly uniformity and concord,
where there is no discord; for the apostle saith, '`There is one Lord, one faith,
one baptism,`' etc. and the work of the ministry
was to bring people into the unity of this faith,
and the knowledge of the son of God,
who was and is the author and finisher of this precious holy and divine faith;
in which faith they had victory over that which is unholy, and access to God;
in which faith they pleased him, having victory over that which displeased him.
And this is called the '`faith of God`'s elect,`' in which they had all unity,
and they were called '`the household of faith,`' and through
this faith did receive the righteousness of Christ,
through which faith they were made conformable to Christ`'s death,
and conformable to the image of the son of God, through the righteousness of faith,
which was before, and beyond, and above the righteousness of man,
and the righteousness of the law; and in the righteousness of Christ,
and the image of the son of God, here is the saints`' holy and righteous uniformity,
and spiritual and heavenly unity and fellowship.

And David saith,
'`Behold how good and how pleasant it is for brethren to dwell
together in unity.`' Now the unity and fellowship is in the light,
grace, and truth, and spirit, and the gospel, the power of God,
and the faith which Jesus Christ is the author and finisher of; and therefore,
all must be conformable to the light, grace, and truth that comes by Jesus Christ,
and to the spirit of God, that God pours upon them, and to the gospel of salvation,
and to the faith that Jesus Christ is the author and finisher of,
(if ever ye do come into spiritual uniformity, unity, and fellowship in the light,
in the truth, in the gospel, in the faith,
in the image of the son of God,) one with another, and with the Father and the son,
that the saints are and were in, in the apostles`' days.
Glory and honour to the Lord over all forever, who is teaching his people by his son,
who bruises the serpent`'s head, that false teacher,
and now God is the teacher of his people by his son,
and I say was the teacher of Adam and Eve in paradise before they fell,
who is God all-sufficient, and a sufficient teacher.

G+++.+++ F.

[.inline]
=== The Authority of the Church of Christ.

The apostle saith to the Corinthians, '`I told you before, and foretell you,
as if I were present, now I write to them which heretofore have sinned,
and to all others, if I come I will not spare.`' 2 Cor. 13:2.

Here the apostle used his authority in the power and spirit of Christ,
who would not spare sin and sinners.

And John said, '`That I wrote unto the Church, but Diotrephes,
who loveth to have the preeminence amongst them, received us not; wherefore if I come,
I will remember his deeds,
which he doth prate against us with malicious words.`' And
so John thought of this Diotrephes in the power of God,
and had authority in his power to judge such prating puft-up Diotrephes`'s,
and their malicious words;
and so hath the church of Christ in his power to judge such now,
as in 3 John 3:10-9. '`And therefore, my beloved, follow not that which is evil,
but that which is good; for he that doth good, is of God, and he that doth evil,
hath not seen God.`' Here is the true judgment of
a true watchman in the power and spirit of Christ.
As many as receive Christ, to them he gives power to become the sons of God,
which were born not of blood, nor of the will of the flesh, nor of the will of man,
but of God; these had power from Christ to admonish, reprove,
and rebuke such as went out from the will of God, into sin and evil.
And the apostle said, `'Though I should boast somewhat more of our authority,
which the Lord hath given us for edification, and not for your destruction.`'

So here the apostles had authority, which the Lord had given them,
for the edification of the church, to keep them out of destruction.
2 Cor.
x.

And the apostle said to the church of Corinth,
'`I fear lest when I come I shall not find you as I would,
and that I shall be found unto you such as ye would not, lest there be debates, envying,
wrath, strifes, etc. and lest when I come again, my God will humble me amongst you,
and I should bewail many which have sinned already,
and have not repented of your uncleanness, fornication, and lasciviousness,
which you have committed.
I write these things being absent, lest being present I should use sharpness,
according to the power which the Lord hath given me- to edification,
and not to destruction.`' Here you see the authority and
power from the Lord the apostles had to judge such as these,
for the edification of them that profess christianity, not for their destruction. 2 Cor. 20:21.
And the apostle saith, '`For to this end also did I write,
that I might know the truth of you, whether ye be obedient in all things;
to whom ye forgave anything, I forgave it for your sakes in the person of Christ.`'

So here you may see where there was an obedience to the truth,
there was a forgiveness in Christ.
2 Cor.
ii. And the apostle saith, '`For verily, as absent in the body but present in the spirit,
I have judged already, as though I was present, concerning him that has done this deed;
in the name of the Lord Jesus, when you are gathered together,
and my spirit with the power of our Lord Jesus Christ,
to deliver such a one unto Satan for the destruction of the flesh, etc.
Know ye not, a little leaven leavens the whole lump; purge out therefore the old leaven,
that ye may be a new lump.`' 1 Cor.
v.

Here you see the apostle and the church of Christ
had power and authority from Christ to cast out,
and to purge out that which is evil, or the old leaven, out of the church of Christ,
that they may be a new lump; for the apostle said,
'`He would shortly come to the church of the Corinthians, if the Lord will,
and I will not know the speech of them which are puffed up, but the power;
for the kingdom of God is not in word, but in power.`' So here the apostle,
in his authority in the power of Christ, would know the power of Christ in others,
and would have the church of Christ to do the same; for the apostle saith,
'`Do ye not know that the saints shall judge the world.`'

So the sanctified, which are made holy, judge the unholy world.
And again, `'Know ye not that ye shall judge angels.`' Angels are spirits;
they that keep their habitation in the truth, and are in the spirit of Christ,
do judge the angels, and spirits that are fallen from the truth,
and their habitation in the truth; yea, I say the devil and his angels,
in whom is no truth; they that walk in truth,
and live in the power and spirit of Jesus do judge such:
and therefore it was a shame to the church of Christ, who had this power,
to go to law one with another before the unbelieving world, whom they had power to judge,
and not to set up the least in the church to judge
of outward things pertaining to this life,
seeing they had the power to judge of greater matters.

So here you may see the church of Christ hath power from Christ to judge the angels,
to judge the world, and to judge in outward matters of things that pertain to this life.
1 Cor. 6.

[.inline]
=== Concerning Exhortation and Admonition.

Concerning exhortation, Judas and Silas, etc. exhorted the brethren with many words,
and comforted them.
Acts 15, And the apostle confirmed the souls of the disciples.
and exhorted them to continue in the faith,
and that we must through many tribulations enter into the kingdom of God;
when he had ordained them elders in every church, etc. they commended them to the Lord,
whom they believed.
Acts 14. So you may see here were elders ordained in every church;
and the aged women are commended as well as the men,
as in Titus 2. And Barnabas exhorted the church of Antioch, yea, he exhorted them all,
that with purpose of heart they would cleave unto the Lord.
Acts 11.

And the brethren wrote, exhorting to receive Apollos, who when he was come into Achaiah,
helped them much who had believed through grace.
Here you may see it was the practice of the church of Christ to exhort,
and did help them which believed through grace.
Acts 18. And you may see in Acts 20. how the apostle
had given the church of Macedonia much exhortation,
and this exhortation was in the spirit and power of Christ;
for Christ gave to his disciples power and authority over all devils, etc.
Luke 9.

And the apostles exhorted the Thessalonians to exhort.
2 Thess. 3. and in Thess. 4:1. and said,
'`We beseech you brethren, and exhort you by the name of the Lord Jesus,
that as you have received of us, how ye ought to walk and please God.`' And said,
moreover, '`Ye know how that we exhorted, and comforted, and charged every one of you,
etc. that ye walk worthy of God, who hath called you unto his kingdom and glory.
1 Thess. 2.
Wherefore comfort yourselves together, and exhort and edify one another,
even as ye also do.
And we exhort you, brethren, warn them that are unruly, and comfort the feeble-minded,
and support the weak,
and be patient towards all men.`' Here you may see the church hath authority,
both to support, and comfort, and export, and warn the unruly.
1 Thess. 5.

And you may see how the apostles did command and exhort such as walk disorderly,
in 2 Thess. 3.
And the apostle did exhort, saying,
'`Save yourselves from this untoward generation.`' Acts 20:40.
And the apostle exhorted the mariners that were in the ship,
'`Be of good cheer, for there shall be no loss of any man`'s life; I believe in God,
and that it shall be even as it was told me,`' to wit, by the Lord.
Acts 27. And the apostle saith to Timothy,
'`Give attendance to reading, to exhortation,
to doctrine; neglect not the gift that is in thee;`' and bid Timothy, teach and exhort,
and to be an example to the believers in word, conversation, faith, charity, and purity.
1 Tim. 2:4. 6.

And the apostle exhorts Timothy, '`Preach the word in season, and out of season, reprove,
rebuke, exhort with all long-suffering and doctrine.
The time will come when they will not endure sound doctrine,
but turn their ears away from the truth, and heap to themselves teachers,
having itching ears.`' And therefore ye see the church`'s authority to exhort, rebuke,
and reprove such. Tim. ii. 4.
But the apostle saith to Timothy, '`Rebuke not an elder, but entreat him as a father,
and the elder women as mothers,`' etc. 1 Tim. 5.

And the apostle saith to Titus, in chap. 2.
'`Exhort, rebuke, with all authority,
and exhort servants to be obedient to their own masters,
etc. that they may adorn the doctrine of God in all
things.`' And the apostle exhorted Titus,
'`to set in order the things that are wanting in Crete, and ordain elders in every city,
as I had appointed thee.`' And they were to be such as were able, by sound doctrine,
both to exhort, and convince gainsayers.
And the apostle exhorted Titus, '`to rebuke sharply the unruly,
and vain talkers and deceivers.`' Tit. 1. And Titus received the apostle`'s exhortation,
when they sent him to the Corinthians. 2 Cor. 8.
And the apostle said, '`A man that is a heretic,
after the first and second admonition, reject.`'

And the apostle saith, '`Let us consider one another,
to provoke one another unto good works,
not forsaking the assembling of ourselves together, as the manner of some is,
but exhorting one another, and so much the more as ye see the day approach,`' to wit,
of Christ Jesus. Heb. 10:24-25.
And the apostle said, '`I beseech you brethren,
suffer ye the word of exhortation,`' etc.
Heb. 13. And the apostle saith to the Colossians,
'`Let the word of Christ dwell in you richly, in all wisdom,
teaching and admonishing one another,`' etc.
Col. 3. So here you may see the church of Christ, from his word dwelling in them,
were able to teach and admonish one another from the word of wisdom in them.
So it seems then, they did not set a priest over them,
that he might be always teaching of them, and they might be always paying of him.
And the apostle saith to the Romans, Rom. 15:14.
'`I myself also am persuaded of you my brethren,
that ye are full of goodness, and filled with all knowledge,
able also to admonish one another.`'

So here you may see the church of the Romans were able to admonish one another then,
without setting up of colleges to make priests to admonish them; and therefore,
as the apostle saith to the Philippians, in chap.
ii '`that ye may be blameless and harmless, the sons of God, without rebuke,
in the midst of a crooked generation, among whom ye shine as lights in the world,
holding forth the word of life.`' And the apostle saith, '`I have sent Tychicus unto you,
(the Ephesians,) that he might know your affairs,
and might comfort your hearts.`' Eph. 6:21. Here the churches knew,
and made known the affairs one unto another in the Lord.

And Jude exhorted the church in his General Epistle,
that they should earnestly contend for the faith which was
once delivered to the saints or sanctified ones,
which faith Christ is the author and finisher of.
And now, had all Christendom contended for this faith or belief,
then they would not have made so many faiths or beliefs
to kill and destroy one another about,
had they kept in Christ`'s saving faith, which saves and doth not destroy,
and with that shield of faith ye do not war with flesh and blood to destroy it.

And the Lord sent Jeremiah to admonish the children of Israel,
that they should not go into Egypt;
but they disobeyed the word of the Lord unto Jeremiah, and went into Egypt;
therefore Jeremiah told them, '``they should die in the land of Egypt,
and should be consumed.`' Jer. 42:43-44. Here you may see what became
of them that disobeyed the admonishment of the Lord and his prophet;
and therefore Solomon saith, '`Better is a poor and a wise child,
than an old and foolish king, who will no more be admonished,
or knoweth not to be admonished.`' Ecc. 4. And Solomon saith,
'`The words of the wise are as goads, and as nails fastened by the masters of assemblies,
etc. by these my son be admonished.`' Ecc. 12. So it is good for all to receive
the exhortations and admonishments from the power and spirit of Christ.
And Christ bade John write unto the church of Thyatira,
'`that he had a few things against them, because they suffered Jezabel to teach,`' etc.
Rev. 2. And so you may see this church came under reproof,
because they did not make use of their power and authority,
in the spirit of Christ to judge Jezabel`'s spirit;
and therefore the church of Christ now, is not to suffer Jezabel`'s spirit,
lest they come under the same reproof, if they suffer that Jezabel`'s spirit to teach,
now as then.
And here you may see how that Christ hath given his church
power and authority in his holy spirit to admonish,
exhort, judge, reprove, and rebuke in his power and spirit.

G+++.+++ F.

[.inline]
=== Concerning such as cry against Orders.

God is a God of order, and not of confusion;
and the apostle saith to the church of Christ, '`Let all things be done decently,
and in order.`' Mark, all things in the church of Christ.
So then there is nothing to be done indecently, out of the order of the peaceable truth;
for God is not the author of confusion, or tumults, or unquietness,
but of peace in all the churches of the saints.
And therefore, if God be not the author of such confusion, tumults, and unquietness,
but of peace in all the churches of the saints; then confused, tumultuous, unquiet,
and indecent, and disorderly spirits, with the power and spirit of God,
they must be admonished to the peaceable spirit of God in them,
and with it judge out the contrary, else the church of Christ,
in its power and peaceable spirit, can have no unity with them,
but with the spirit and power of Christ, judge that indecent, confused, tumultuous,
unquiet, disorderly spirit.
For God, as I said before, is a God of order; but the devil, which is the world`'s god,
hath made the world like a wilderness, which lies in wickedness; and this devil or Satan,
in whom there is no truth, the power of death, and darkness, and confusion,
got into Adam and Eve by their disobedience, and rules in the hearts of the disobedient,
where all tumults, disquietness, confusion, and disorders are;
for who went and go into disobedience from God, they went and are gone from his image,
from the innocency and simplicity, and his power and spirit within,
and so go out from his power, spirit, and image, in which his holy order is,
and out of simplicity and innocency, into subtlety and craft: for the devil,
that abode not in the truth, and his followers, that disobey God and his truth,
which follow the devil, in whom there is no truth, there is no order amongst them,
but confusion.
Truth hath an order for all things that God did make by Jesus Christ,
who upholds all things by his word and power.
So, with his word and power he keeps all things in their places, and in their order,
in their times, and in their seasons; the summer and the winter, the night and the day,
the sun, moon, and the stars,
all things are kept in order by the word of God and his power;
and the earth is the Lord`'s, and the fulness thereof, and the sea,
and the fulness therein.

So both the earth and the sea, and all things therein,
are kept in their order by the word and power of God, by which they were made,
by which they were upheld.
So all the works of the Lord praise him,
and so do all men and women that are in the truth,
which makes them free from him that abode not in the truth, in whom there is no truth.
So all God`'s free people or children,
(that are made free indeed by the truth,) are in the order of the truth,
and in the order of the spirit of God, and in the order of the gospel,
and are in the order of the light, the life in Christ,
and are over the foul spirit of disorder, in the land of death and darkness;
as the scripture saith, '`a land of darkness, as darkness itself,
and of the shadow of death, without any order,`' mark, without any order,
'`where the light is as darkness.`'

This spirit may cry out against orders, whose habitation is darkness, without any order;
but as the Lord saith, '`Who offers up praise, glorifies me,
and he that orders his conversation aright,
shall see the salvation of God.`' Now here is a particular
order for every man and woman to observe;
for '`the steps of a good man are ordered by the Lord,
and he delights in his way.`' Ps. 37. '`The Lord hath sworn,
and will not repent,`' speaking of Christ, '`thou art a priest forever,
after the order of Melchizedek.`' Ps. 110. Heb.
5+++.+++ And Christ is not called after the order of Aaron.
Heb. 7. Here you may see, Melchizedek the priest was not made without an order,
and Aaron`'s priesthood was made by an order of God,
according to his rod`'s budding in the tabernacle.
And Christ was not a priest made without an order,
which is after the order of Melchizedek; and his royal priesthood,
who offer up spiritual sacrifices acceptable to God, are in his spiritual order,
and in the order of the spirit of God.

And Isaiah saith, chap.
ix. '`Unto us a child is born, unto us a son is given,
and the government shall be upon his shoulders.`' So here,
Christ bears up his government, '`and of the increase of his government and peace,
there shall be no end;`' for Christ orders it, and establishes it, etc.
So Christ`'s government is a peaceable government, and there is no strife in it;
and Christ`'s government is peaceable in his power, light, and spirit.
And the apostle, after he had exhorted the Corinthians of many things, said,
'`The rest I will set in order when I come;`' and
this was by the power and spirit of Christ.
And the apostle saith to Titus, '`I left thee in Crete,
that thou shouldst set in order the things that be wanting,
and that thou ordain elders in every city,
as I have appointed thee.`' And in the 2d chap.
ye may see how he speaks of the qualifications of the aged men, and the aged women,
that were to be teachers of good things, and of the younger, etc.
Now here you may see the apostle was for good order,
and established good order in the church of Christ, and encouraged Titus to set in order,
and ordain elders in every city in Crete, which were wanting,
so that all the church of Christ might be kept in
the order of the power and spirit of Christ.

And the apostles saith to the Colossians, '`Though I be absent in the flesh,
yet I am with you in the spirit, joying and beholding your order,
and the steadfastness of your faith in Christ;
and as you therefore have received Christ Jesus the Lord,
so walk in him.`' Now here you may see, the church of Christ had a spiritual order,
though the apostle was absent in the flesh from them,
yet he was present with them in his spirit, with which spirit he rejoiced,
and beheld their spiritual order; so in this spiritual order must all God`'s people live,
though they be absent in body one from another, yet in the spirit they may rejoice,
beholding the spiritual order that is in the church of Christ,
and the steadfastness of one another`'s faith in Christ Jesus,
who is the author and finisher of it.

G+++.+++ F.

[.inline]
=== Concerning meeting in Houses, Ships, Streets, Mountains, and High-Ways, and in what places the Prophet Jeremiah, Christ, and the apostles taught or preached in, may be seen in this book.

[.inline]
=== And how Christ and the apostles were haled out of their meetings, when, or while they were speaking. John 18:1. Matt. 26:47. Mark 16:17. Acts 4:2-3. and 5:24-27. By G. F.

Here you may see, how Christ and his apostles, and John Baptist,
were not tied to places to preach in;
for Christ sent his apostles into all nations to preach the gospel,
and to every creature under heaven.

And sometimes Christ preached in the synagogues, and in the temple, and in houses,
and in the wilderness, and on ship-board, and upon the sea-shore, and upon the mountains;
and the apostles did likewise preach not only in the synagogues,
but in other common houses.
And the primitive christians, you do not read that they gave titles of synagogues,
or temples, or churches to their meeting houses,
as were given to the Jews synagogues and temple, in the old testament;
for a church was Christ`'s believers, and Christ was the head of them.

Now they that profess the scriptures of the New Testament, and say, it is their rule,
they may see by the scripture that follows,
it is no strange thing for God`'s people to meet in mountains, or deserts, or in ships,
or in common houses, And did not John the Baptist preach in the wilderness of Judea,
saying,
'`Repent for the kingdom of heaven is at hand,`'
in his raiment of camel`'s hair and leather girdle,
and then went out to him Jerusalem, and all Judea, and the regions round about Jordan.
Matt. 3:3-4, and Mark 1:3-4. John was a voice crying in the wilderness, saying,
'`Prepare ye the way of the Lord, make his path straight.`' And Luke 3:4-5,
'`The word of the Lord came to John, the son of Zachariah, in the wilderness,
who preached the baptism of repentance for the remission of sins,`' and said,
'`Every valley shall be filled, and every mountain and hill shall be brought low,
and the crooked shall be made straight, and the rough shall be made smooth,
and all flesh shall see the salvation of God.
Bring forth fruits worthy of repentance,
etc. for now is the axe laid to the root of the trees,
and every tree therefore which brings not forth fruit,
is to be hewn down and cast into the fire.`' And John was a man sent from God,
who bore witness to the light, and said, '`He was not that light;
but that was the true light which enlightens every
man that comes in the world.`' John 1:6-9.

And the wise men that came from the east, who saw the star in the east,
that came to see the young child Jesus, and the star stood over the house,
where Christ was born in Bethlehem, and when they were come into the house,
they saw the young child with Mary his mother, and fell down and worshipped him.
Had not the wise men a meeting with Christ Jesus and Mary in the stable in Bethlehem,
though he lay in a manger?
And Herod was in such a rage,
because that the wise men did not tell him where Christ was born,
that he sent forth and slew all the men children that were in Bethlehem,
and in the coast thereof, from two years old and under, etc.
For the wise men were warned of God, not to go to Herod,
but to depart into their own country, by another way.

'`And Jesus walked by the sea side of Galilee, and saw two brethren, Simon called Peter,
and Andrew his brother, casting their nets into the sea, for they were fishermen;
and going from thence, he saw other two brethren, James, and John his brother,
in a ship with Zebedee their father, mending their nets, and he called them,
and they immediately left their ship and nets, and their father,
and followed him.`' Here did not Christ preach by the sea-side of Galilee,
and convert those four persons, and made them his disciples? Matt. 4:18-21.

And there followed Christ a great multitude from Galilee, and Decapolis,
and from Jerusalem, and from Judea, and from beyond Jordan;
and Jesus seeing the multitude, he went upon the mountain, and when he was sat down,
his disciples came unto him, and he opened his mouth and taught them and the multitude,
as you may see, in Matt. 5. to Matt. 8. and how he expounds the law,
and makes a distinction between the old testament and the new;
there you may see his large sermon upon the mountain,
to the great multitude and his disciples: so he preached upon a mountain.
And Christ, after he had given power to his twelve apostles, he said unto them,
'`As you go, preach, saying, the kingdom of heaven is at hand;`' mark, as you go, preach;
so they were to preach as they went; and into whatever city or town ye enter,
inquire who is worthy, and there abide until ye go thence;
and when ye come into any house, salute it; and if the house be worthy,
let your peace come upon it, etc.
And whosoever shall not receive you, nor hear your words,
when ye depart out of the house or city,
shake off the dust of your feet for a testimony against it,`' etc.
Matt. 10. Mark 6:11. Here you may see, that Christ`'s disciples preached in houses;
and Christ bid them, '`Beware of men, for they will deliver you up to councils,
and they will scourge you in their synagogues.`'
That was their portion they should have there;
and that was and is the portion of Christ`'s disciples,
that they have from the outward professors, in their outward synagogues,
and haling of them before the rulers and governors for Christ`'s sake,
and for a testimony against them.

And Jesus went through the corn-field on the sabbath day, and his disciples were hungry,
and began to pluck the ears of corn, and to eat; and when the Pharisees saw it,
they said unto him, '`Behold,
thy disciples do that which is not lawful to do upon the
sabbath day.`' And you may see how Christ preached to them,
and reproved their blindness.
Matt. 12.

And Jesus sat by the sea shore, and a great multitude were gathered together unto him,
and he went into the ship, and sat, and the whole multitude stood on the shore,
and Christ spake many things in parables to them, and taught them out of the ship.
Matt. 13. And Jesus came nigh unto the sea of Galilee, and went into a mountain,
and sat there, and a great multitude came unto him,
and they continued with him three days;
and he commanded the multitude to sit on the ground in the wilderness,
and took the five loaves and three little fishes, and he gave thanks, and brake them,
and gave to the disciples, and the disciples to the multitude;
and they that did eat were four thousand men, besides women and children.
And was not here a great meeting that Christ both fed, taught,
and wrought this great miracle upon the mountain, and in the wilderness? Matt. 15:29.
Mark 8.

And Jesus taketh Peter, and James, and John,
and brings them up into an high mountain apart, where he was transfigured before them,
and as he prayed, the fashion of his countenance was altered,
and his raiment was white and glistering.
Matt. 17. Mark 9:2. Luke 9:28. Here you may
see Christ prayed with his disciples in the mountain;
and was not here a meeting?
And Jesus came into the coasts of Judea, beyond Jordan,
and a great multitude followed him, and he taught them. Matt. 19:12.
Mark 10:1-2. And the Pharisees came and tempted him,
that were in a profession without possession.

And Christ saith in his parable, '`The kingdom of heaven is like unto a certain king,
who made a marriage for his son, and sent forth his servants, and said,
go ye into the highways, and as many as ye shall find,
bid to the marriage.`' Matt. 22:9. And is not
this a parable of the marriage to Christ,
the son of God?
And did not they that made light of his marriage, entreat his servants spitefully,
and slew them, and went away, one to his farm, and another to his merchandise,
etc.? '`And as Jesus sat at meat in his house,
behold many publicans and sinners came and sat down with him and his disciples;
and when the Pharisees saw it, they said unto the disciples,
why eateth your master with publicans and sinners?`' But Christ, when he heard that,
said unto them, '`that the whole need no physician, but them that are sick;`' for,
said he, '`I am not come to call the righteous,
but sinners to repentance.`' Matt. 9:10-13. And did not he preach in a house here?

And again, as Christ sat upon the Mount of Olives, and his disciples came to him,
Christ foretold them the destruction of the temple, and what great calamity should come,
as you may see in Matt. 24. to the end.
And had not Christ and his disciples a meeting there upon the Mount of Olives,
over against the temple? Mark 13:1.
Luke 21:5. And had not Christ a meeting with his disciples in Bethany,
in the house of Simon the leper,
when the woman poured the precious box of ointment upon his head?
And did not Christ instruct his disciples largely about that, and said, '`Verily,
I say unto you, wheresoever this gospel shall be preached in the whole world,
there shall also this, that this woman hath done, be told for a memorial of her?
For in that she hath poured this ointment upon me,
she did it for my burial.`' Matt. 26. and Mark 14:6. to the 10th. And did
not Christ preach this doctrine in the house of Simon the leper at Bethany?
And did not Christ keep the passover in a house with his disciples?
For when the evening was come, he sat down with the twelve. Matt. 26:19-20.
and Mark 14:18. Luke 22:24. John 13. And here did not Christ
keep an evening meeting in a house with his disciples concerning the passover,
and taught them, and instructed them?
And he did not keep this meeting in the temple, or the Jews`' synagogues,
but in a chamber in a house, as you may see in the scriptures.

And had not Christ a meeting in the house of Simon, and healed his wife`'s mother,
who lay sick of a fever, and at evening, when the sun was set,
all the city were gathered together at Simon Peter`'s house door?
And had not they here an evening meeting? Mark 1:29-33.

In Mark 3:13-14. '`Christ he goeth up into a mountain,
and calls to him whom he would;`' and there Christ ordained twelve disciples,
'`that they should be with him,
and that he might send them forth to preach the gospel,`' etc.
And they went into an house, and the multitude came together,
so that they could not so much as eat meat; verse 19, 20. to the end.
Here you may see Christ ordained his twelve disciples on a mountain,
and they had a meeting in a house.

And again in Mark 4. Christ begins to teach by the sea-side,
and there were gathered unto him a great multitude, so that he entered into a ship,
and sat in the ship on the sea-side, and the whole multitude was by the sea on the land,
and he taught them many things,`' etc.
Here you may see again Christ taught by the sea-side in a ship.

And again, '`Christ entered into Capernaum, and it was noised that he was in the house,
and straightway many gathered together, insomuch that there was no room to receive them;
no, not so much as about the door.`' You may see here Christ preached in a house,
and unto them that were without doors.
And when Jesus was passed over again by ship, unto the other side,
'`much people were gathered unto him,`' and he was nigh unto the sea.`' Mark
5:21. Here you may see Christ had a great meeting nigh unto the sea.

And Jesus taught his disciples in a house, as you may see, Mark 9:28. 33.
And also when he came to Capernaum,
here you may see how he taught his disciples in that house.
Also, Mark 9:31-35. And again, in Mark 10:17.
Christ taught his disciples in a house.

And as Jesus went, with his disciples, into the towns of Caesaria and Philippi,
by the way he '`asked some questions,
and taught them many things.`' Mark 8. from verse 27 to 34. So
here you may see Christ`'s disciples asked him questions,
and he taught them by the way.
And Christ sent two of his disciples into the city,
and they were to say to the good man of the house, '`The master saith,
Where is the guest-chamber, where I shall eat the passover with my disciples?
And they showed him a large upper room, furnished and prepared,
and they made ready the passover; and in the evening he cometh with the twelve,
and as they sat at meat,
Jesus taught them.`' Mark 14. from verse 18 to 32. Here you may
see Christ and his disciples had a meeting in a house,
in an upper chamber, in the evening.
And in Luke 1:40. when Mary entered into the house of Zachariah, and saluted Elizabeth,
what a heavenly meeting was there when they met together in Zachariah`'s house,
(from verse 40 to 56.)

And Levi made a great feast in his house, and there was a great company of publicans,
and others, that sat down with them, to wit, Christ and his disciples;
but the scribes and Pharisees, murmured against his disciples, saying,
'`Why do you eat and drink with publicans and sinners?`' And Jesus answered, and said,
'`They that are whole need no physician;`' and preached to them in a Levite`'s house.
Luke 5:29 to the end.

And the shepherds that were in the country of Bethlehem, '`which abode in the field,
keeping watch over their flocks by night, and they came and found Mary and Joseph,
and the babe lying in the manger, because there was no room in the inn;
and the shepherds returned,
and glorified and praised God for the things which they had heard and seen:
Here you may see the shepherds had a meeting, and met with Christ and his mother,
though he was wrapped in swaddling clothes, lying in a manger.
Luke 2.

And again, '`Christ went into a desert place, and the people sought him,
and came unto him, and stayed with him.`'
Here you may see Christ and the people had a meeting in the desert. Luke 4:42.
And again, Christ taught the people out of Peter`'s ship. Luke 5:3.

And again, in Luke 5. '`Christ withdrew himself in the wilderness, and prayed,
and it came to pass on a certain day, as he was teaching,
there were Pharisees and doctors of the law came out of every town of Galilee, and Judea,
and Jerusalem,`' etc. and they brought a man in a bed, which was taken with the palsy,
and because of the multitude they went upon the house-top,
and let him down through the tiling in the midst before Jesus, and he healed him.`'

Here you may see Christ had a great meeting in a house in the wilderness.

And Christ and his disciples went into the desert of Bethany,
and there they had a great meeting of five thousand men, and he '`made them to sit down,
and he took the five loaves and two fishes, and looking up to heaven, blessed them,
and gave them to his disciples to set before the multitude, and they did all eat,
and were all filled, and there were taken up of fragments that remained,
twelve baskets.`' Here you may see Christ had a great meeting in this desert,
where he wrought this miracle.
Luke 9.

'`And Jesus took Peter, and John, and James, and went into a mountain to pray,
and the next day, when they were come down the hill,
much people met Christ.`' Here you may see, in Luke 9. what places Christ prayed in,
and had meetings.
'`And Jesus went into a mountain to pray, and continued all night in prayer to God;
and when it was day he called unto him his disciples,
and he came down with them into a plain, and a great multitude of people,
out of all Judea and Jerusalem, and from the sea coasts of Tyre and Sidon,
which came to hear him,`' etc.

So you may see, here was a great meeting, where Christ stood in the plain,
Luke 6. from verse 12 to the end.
And one of the Pharisees desired Christ that he would go eat with him,
and he went into the Pharisee`'s house, and sat down to meat,
and the woman stood at his feet behind him weeping, which was a sinner,
and began to wash his feet with her tears, and did kiss his feet,
and anoint them with ointment she brought; and the Pharisees said, '`This man,
if he was a prophet, would have known who, and what manner of woman she was,
that touched him.`'

And you may see how Christ preached to him,
and to them that were in the Pharisee`'s house, from verse 40 to the end,
in Luke 7:36-39. And Christ went through every city and village,
preaching and showing the glad tidings of the kingdom of God.
Here again you may see in what places Christ preached. Luke 8:1.
And had not Jesus a meeting at Martha`'s house?
See what he said to her and her sister Mary; '`For Mary sat at Jesus`' feet,
and heard his words;
but Martha was cumbered and careful about many things;`' but Christ said,
'`Mary had chosen the good part,
which should not be taken away from her.`' Luke 10:38 to the end.
And when Christ had appointed seventy disciples, he sent them by two and two, and said,
'`into whatsoever house ye enter, first say peace to the house;
and in the same house eating and drinking such things as they give you;
for the labourer is worthy of his meat or hire.`' Go not from house to house.

Here you may see, Christ`'s disciples were to preach in houses.
Luke 10:1 to 12. And Christ taught his disciples to pray. Luke 11:12.
And Christ went into a house of one of the chief Pharisees,
to eat bread on the sabbath day, and there came a man before him, which had the dropsy,
and he healed him.
You may see how Christ preached to the lawyers and Pharisees on the sabbath day,
in the Pharisee`'s house; and he put forth a parable to them,
'`Of a certain man that made a great supper, and bade many,`' etc.
'`and they all with one consent began to make excuses, and one said,
he had bought a piece of ground, and I must needs go see it,`' etc.
'`And another had bought a yoke of oxen, and he must prove them; and another said,
he had married a wife, and therefore could not come.
So the servant came and showed his lord these things;
then the master of the house being angry, said to his servants,
Go quickly into the streets and lanes of the city, and bring in hither the poor, maimed,
halt and blind.
And the servant of the lord said, It is done as thou hast commanded,
and yet there is room.
And the lord said unto the servants, Go ye out into the highways and hedges,`' etc.
'`that my house may be filled.
I say unto you that none of those men which were bidden,
shall taste of my supper.`' To wit, he that had bought a piece of ground,
and he that had bought the oxen, and he that had married the wife, who made excuses,
they could not come and taste of his supper, as in Luke 14.

So here you may see the servants of Christ preached in the streets, lanes, highways,
hedges.
And had not Christ a meeting at Zaccheus`' house, who was a chief publican?
And did not Christ tell him, '`He was the son of Abraham,
and this day salvation was come to his house?`' And
did not Christ preach many things to them,
and in parables?
Luke 19. And after Christ was risen from the dead, he appeared to two of his disciples,
as they were walking to a village called Emaus, and he opened their understandings,
and showed them out of the scriptures,
'`that he was the Christ;`' and they went to Jerusalem
and found the eleven gathered together,
and them that were with them, and they told them how that Jesus Christ was risen;
and as they thus spoke, Jesus himself stood in the midst of them, and said,
'`Peace be unto you,`' etc.
And Christ bid them '`tarry in the city of Jerusalem until
they were indued with power from on high.`' Luke 24.

Here you may see Christ preached to two of his disciples by the highway side,
and in the house, and his disciples and others kept their meetings,
and Christ was amongst them after he was risen from the dead,
as well as in their meetings with him before he was crucified.
And there was a marriage in Cana of Galilee, and Jesus was called,
and his twelve disciples, and the mother of Jesus was there. John 2:1.

Here you may see Jesus was at this marriage meeting,
and his disciples through his words and miracles believed on him.
And Nicodemus the ruler of the Jews, that came to Jesus by night, and said to him,
'`Thou art a teacher come from God,`' etc.
John 3. Had not Christ and his disciples a meeting with him in the night?
And Christ taught him, that he must be born again,
before he could see the kingdom of God, or enter into it.
And in John 4. had not Christ a meeting with the woman of Samaria at Jacob`'s well?
And did not he teach her, that God was worshipped not at Jerusalem,
neither in that Mountain where Jacob`'s well was, but that God is a spirit,
and they that worship him, must worship him in spirit and truth?

And did not the disciples marvel at Christ`'s speaking with, or teaching the woman?
And did not the woman leave her water pot, and go into a city of Samaria,
and say to the men of that city, '`Come,
see a man which hath told me all things that ever I did.
Is not this the Christ?`' And they went out of the city, and came unto him;
and through this meeting of Christ with the woman at the mountain of the Samaritans,
many of them believed in him.
And there lay a great multitude of impotent folk at the pool of Bethesda,
and there Christ on the sabbath day,
healed a man that had an infirmity thirty-eight years;
and therefore the Jews persecuted Jesus, and sought to slay him,
because he had done these things on the sabbath day.
John 5. And in John 11. had not Christ and his disciples a meeting in Martha`'s house,
when Lazarus was dead, when the Jews were met together with Mary and Martha?
And did not he preach to them in Martha`'s house?
And did not many of the Jews believe on him through his preaching,
and raising Lazarus from the dead?
John 11:17 to 54.

And again,
had not Christ and his disciples another meeting at Bethany at Martha`'s house,
after he had raised Lazarus from the dead?
And Lazarus was one that sat at table with Christ and his disciples at supper;
and many people of the Jews came not for Christ`'s sake only,
but that they might see Lazarus, whom he had raised from the dead.
But the chief priests consulted that they might put Lazarus to death,
because by reason of Lazarus`' being raised from the dead,
many of the Jews believed in Christ.
John 12. And when Jesus went forth with his disciples over the brook Kidron,
where was a garden, into which he entered with his disciples,
for Jesus oftentimes resorted thither with his disciples; so here you may see,
Christ and his disciples oftentimes had meetings in this garden,
And Judas knowing the place where he and his disciples oft resorted,
having received a band of men and officers from the chief priests and Pharisees,
cometh thither with lanthorns, torches, and weapons, while he was yet speaking;
and Jesus said unto them, '`Whom seek ye?`' And they said unto him,
'`Jesus of Nazareth.`' And Jesus said unto them, '`I am he; if ye therefore seek me,
let those go,`' to wit, his disciples.
Here you may see Christ was taken out of a meeting in the garden,
(and while he was yet speaking,) by Judas and the officers,
and a great multitude with lanthorns, torches, swords, and staves.
John 18. Matt. 26:47.

And the disciples when they came to the Mount of Olives,
where Christ did ascend into heaven from them, they went to Jerusalem,
and went into an upper room,
and these all continued with one accord in prayer and supplication with the women,
and Mary the mother of Jesus, and his brethren;
and Peter stood up in the midst of the disciples,
and showed them the fulfilling of the scriptures;
and this meeting was of about an hundred and twenty,
the first meeting after Christ`'s ascension, in an upper chamber.
Acts 1. And at the time of Pentecost, they were all with one accord in one place,
and they were filled with the holy ghost; '`for suddenly there came a sound from heaven,
as of a rushing wind, and it filled all the house where they were sitting;
and there were dwelling at Jerusalem devout men, out of every nation under heaven.
Now when it was noised abroad, the multitude came together, and were confounded,
because that every man heard them speak in his own language, and they were amazed,
and were in doubt, and marvelled, saying one to another, what meaneth this?
And others mocked, saying, these men are full of new wine.`'

This meeting, and the new tongues of the holy ghost, confounded the professors,
that did not possess the life;
but Peter and the eleven apostles stood up and preached to them Christ,
(from verse 14 to 41.) and showed to them the fulfilling
of the scriptures concerning him;
and '`there were converted and added to them about three thousand souls that day;
and they continued daily with one accord in the temple,
and breaking of bread from house to house, and did eat their meat with gladness,
and singleness of heart.`' Acts 2.

Here you may see what a wonderful conversion there was at this meeting, in this house.
And Peter and John, and the apostles continued in their preaching; but the priests,
and the captain of the temple, and the Sadducees,
being grieved that they preached in the name of Jesus, who is risen from the dead,
laid hands on them, and put them in hold; and howbeit, many of them which heard the word,
believed, to about the number of five thousand men.
And the next day they had them out of the prison before Ananias the high priest,
and the rulers, and elders, and scribes; and Peter and John preached Christ unto them,
and said, '`There is no other name given under heaven among men,
whereby we must be saved, but the name of Jesus,
neither is there any salvation in any other.`'

And the priest and the rulers commanded them not to speak at all,
nor to preach in the name of Jesus; but Peter and John said unto them,
'`Whether is it right in the sight of God, to hearken unto you, more than unto God,
judge ye;
for we cannot but speak the things which we have heard and
seen.`' So when the rulers had threatened them,
they let them go, finding nothing how they might punish them.
Acts 4. So you may see, as the disciples were speaking to the people,
the priests and the captain of the temple, and the Sadducees, came upon them,
being grieved that they taught the people,
and preached through Jesus the resurrection from the dead, and laid hands upon them,
and put them in hold, and had them before the high priests, etc.

So the disciples of Christ were taken out of their meeting,
as they were teaching and preaching to the people,
by the priests and captain of the temple, and the Sadducees. Acts 4:1-2.
And again, when the apostles were set at liberty,
they went to their own company,
and reported all that the chief priests and elders had said and done unto them;
and when they heard, they lifted up their voice to God with one accord, and preached,
prayed, and glorified God, and they were filled with the holy ghost,
and the place was shaken where they were assembled.
Acts 4:23,24,31, to the end.

And again, they were all with one accord in Solomon`'s porch,
and the high priest rose up, and all that were with him, with the sect of the Sadducees,
and they were filled with indignation, and laid hands on the apostles,
and put them in prison; but the angel of the Lord by night opened the prison doors,
and brought them forth, and said, '`Go stand and speak in the temple to the people,
all the words of this life.`' Acts 5:20. And then came one and told them,
'`The men that ye put in prison, stand in the temple,
teaching the people.`' Then went the captain of the temple, with the officers,
and brought them out with violence, and set them before the council;
and the high priest asked them, saying, '`Did not we straightly command you,
that you should not teach in the name of Jesus,`' etc.

But the apostles preached to the council and the high priest;
and when they had beaten the apostles, they commanded them,
'`that they should preach no more in the name of Jesus,`' and let them go:
but the apostles answered, and said,
'`We ought to obey God rather than men.`' But the apostles daily,
in the temple and in every house,
'`ceased not to preach and teach Jesus Christ.`' Here again,
you may see the captain and officers brought out the apostles from their meeting,
when they were teaching in the temple;
and it seems the multitude of believers kept their
meeting with one accord in Solomon`'s porch,
for all the high priests`' and the officers`' threatening, beating, and imprisoning;
yet they ceased not daily to teach and preach Christ Jesus, in the temple and in houses,
as Acts 5.

And in Acts 6. Stephen being a man full of faith and power, certain of the synagogue,
of the Libertines, etc. disputed with him,
and they were not able to resist the wisdom and the spirit by which he spake,
etc. and they stirred up the people, and elders, and scribes, and came upon him,
and caught him, and brought him to the council and high priest,
and set up false witnesses against him, and put him to death. Acts 6:7.
Here you may see the work of such libertines
and disputers with their false witnesses,
high priests, and councils, and false professions,
when they cannot resist the power and spirit of God, then they murder.
And Saul made havoc of the church, entering into every house, and haling men and women,
committing them to prison. Acts 8:3.
And had not Saul, who was a great outward professor,
his authority from the chief priests, to hale, imprison,
and disturb the true Christians in their meetings?
And was not Philip commanded to preach to the eunuch?
And did not he go into the chariot, and preach to him Christ Jesus,
and opened to him the scriptures, and converted him?
And had not Peter a meeting at Cornelius`' house at Caesaria?
And did not he call together his kinsfolks and near friends, and said unto Peter,
'`We are all here present before God,
to hear all things that are commanded thee of God;`' and Peter opened his mouth,
and preached Jesus Christ unto them, and converted them.
Acts 10.

Was not this in Cornelius`' house, the centurian at Cwsaria?
And do ye think he had not a christian meeting in his house,
after he and his friends were converted?
And Herod apprehended Peter, and put him in prison;
but prayer was made without ceasing of the church for him, and the Lord heard them,
and he sent his angel and delivered Peter, and he came to the house of Mary,
the mother of John, where many were gathered together, praying.
Acts 12. Here you may see, here was a christian meeting in Mary`'s house, in the night,
when they had killed James, and persecuted Peter; but the angel of the Lord smote Herod,
the persecutor, and '`he was eaten of worms that he died.`'

And when the apostles had gone through the isle unto Paphos, Sergius Paulus,
a prudent man, deputy of the country, called for Barnabas and Saul,
and desired to hear the word of God; but Elymas, the sorcerer, which was with the deputy,
withstood them, seeking to turn away the deputy from the faith;
but the Lord struck him blind, and the deputy believed,
being astonished at the doctrine of the Lord.
And had not Paul and Barnabas a meeting at the deputy`'s house,
for them to hear the word of God? Acts 13:7.
etc.
And at Antioch, after the reading of the law and prophets,
the rulers of the synagogue sent unto Paul, and his company, saying,
'`Ye men and brethren, if ye have a word of exhortation for the people,
say on.`' Acts 13:15.

And here you may see what a large sermon the apostle preached to them.
And the apostle went to a colony in Macedonia,
and he went out of the city to a river side, where prayer was wont to be made,
and the apostle sat down, and spoke unto the women by the river side,
which resorted thither, and a certain woman named Lydia, of the city Thyatyra,
whose heart the Lord opened,
that '`she attended unto things which were spoken by Paul,`' and she besought them,
saying, '`If ye judge me faithful to the Lord, come to my house, and abide there;
and she constrained them.`' Acts 16:13-15. Here you may see,
the apostles had a meeting by the river side; and had they not another in Lydia`'s house?
(Paul and his company,) and then the magistrates of that country cast them into prison, etc.

And had not Paul and Silvanus a meeting in the prison?
And did not they preach the word of the Lord to the jailer,
and all that were in his house?
And did not they believe in God with all his house?
So had not they a meeting here in the jailer`'s house?
Acts 16. And they went out of the prison, and went into the house of Lydia again;
and when they had seen the brethren, they comforted them and departed. Acts 16:40.
And here, had not the apostles another christian meeting in Lydia`'s house?

And Paul, and Silas, and their company, came to Thessalonica;
and did not Jason receive them?
And the unbelieving Jews, which believed not, moved with envy, with certain lewd fellows,
assaulted Jason`'s house; and they drew Jason, and certain brethren, unto the rulers,
crying and saying,
'`These are they which have subverted the state of the world.`'
And when the rulers had taken security of Jason,
and of others, they let them go.
Acts 17. from verse 1 to 9.

And Paul disputed at Athens, in the synagogue of the Jews, and in the market place,
daily; and he stood in the midst of Mars-hill:
it was the highest court in Athens where Paul preached to them.
Acts 19. from verse 22 to 33. And Paul came to a man`'s house, whose name was Justus,
one that worshipped God, and Crispus, the chief ruler of the synagogue,
believed on the Lord, with all his house, and many of the Corinthians hearing, believed;
and the apostle continued there a year and six months,
preaching the word of God amongst them.
Acts 18.

And do you think that Paul had not Christian meetings at Crispus`' and Justus`' house?
And the Jews made insurrection with one accord against Pazitl,
and brought him before the judgment seat, and they brought him before Gallio,
who was deputy of Achaia; and Gallio said to the Jews,
'`If it were a matter of wrong or wicked lewdness, O ye.
Jews! reason would that I should bear with you;
but if it be a question of words and names, and of your law, look you to it,
for I will be no judge of such matters.`' And he
drove the Jews away from the judgment seat. Acts 18:14-16.
Here you may see,
that the heathen governor had more reason and moderation,
(to the apostle Paul,) than the professing Jews.
And Priscilla and Aquila took Apollo unto them,
and expounded to him the way of God more perfectly; therefore,
had not Priscilla and Aquila a meeting at their house? Acts 18:26.

And Demetrius, the silversmith, made a great uproar,
and through him the city was filled with confusion, and said,
'`This Paul hath persuaded and turned away much people, saying,
That they are no gods which are made with hands; and cried out,
great was Diana.`' And having caught Gaius and Aristarchus, men of Macedonia,
Paul`'s companions in travel, the town-clerk appeased the people, and said,
'`Ye have brought hither these men, neither robbers of your churches,
nor blasphemers of your goddess; wherefore if Demetrius and the craftsmen,
which are with him, have any matter against any man, the law is open,
and there are deputies, let them implead one another;
for if ye inquire any thing concerning other matters,
it shall be determined in a lawful assembly;`' and said, '`Ye ought to be quiet,
and do nothing rashly.`' And when he had thus spoken, he dismissed the people.
Acts 19:23 to 41. And here you may see the moderation of the town-clerk to the apostles;
but Demetrius for love of gain, raised an uproar against Paul and his companions,
which was appeased by the town-clerk,
who showed more moderation and reason than the professing Jews and priests.
And Paul disputed daily in the school of one Tyrannus.
Acts 19. and this continued by the space of two years;
so that all they which dwelt in Asia heard the word of the Lord, both Jews and Greeks.
So here you may see Paul both preached and disputed in a school house.

And Paul and his company came to Troas, and upon the first day of the week,
when the disciples came together, Paul continued his speech until midnight,
and there were many lights in the upper chamber, where they were gathered together,
and there sat a young man in a window, named Eutychus, being fallen into a deep sleep,
as Paul was long preaching in an upper chamber, he sunk down with sleep,
and fell from the third loft, and was taken up dead; but Paul went down and embraced him,
and he was brought to life again, to their comfort. Acts 20:6-11.
Here you may see Paul had a night-meeting in a chamber;
and would not many professors, without possession, say, he was a house-meeter?
And again, the apostle said to the christians at Ephesus,
I have kept nothing back that was profitable unto you, but have showed you,
and have taught you publicly, and from house to house.`' Acts 20:20.

Here you may see the apostles taught the Ephesians, from house to house,
as well as publicly.
And the apostle and his company came to Tyre, and stayed there seven days,
finding disciples there; and when they went away,
their wives and children brought them out of the city,
and Paul kneeled down on the sea-shore, and prayed;
so they had a meeting on the sea-shore. Acts 21:3-5.

And Paul and his company came unto Gesaria,
and went to the house of Philip the evangelist; and the same man had four daughters,
which did prophesy, and they tarried there many days, and the prophet named Agabus,
came to them, and took Paul`'s girdle, and bound his own hands and feet, and said,
'`Thus saith the Holy Ghost,
so shall the Jews at Jerusalem bind the man that owns this girdle,
and shall deliver him into the hands of the Gentiles.`'
And much of it came to pass when Paul came to Jerusalem;
for had not the chief captain and his soldiers rescued Paul, and sent him to Caesaria,
to Felix, the governor, the Jews and the priests would have destroyed him,
as in Acts 21:22-23.

Do you think that the apostle and his company had
not a meeting in Philip the evangelist`'s house,
with him and his four daughters, and Agabus and others? Acts 21:8-9.
And the city of Jerusalem was moved, and ran together,
when Paul came into the temple, and they took Paul and drew him out of the temple,
and as they went about to kill him, tidings came to the chief captain,
'`that all Jerusalem was in an uproar,`' who saved his life,
who was more moderate than the professing Jews.
And Paul stood upon the stairs of the castle, and preached to the Jews,
that Jesus was Christ; as you may see, Acts 21. xxii.
Chap.

And Ananias, the high priest, with the elders, informed Felix, the governor,
against Paul, and said, '`We have found this man, a pestilent fellow,
and a mover of sedition among all the Jews throughout the world,
and a ringleader of the sect of Nazarites.`' Acts 24. Here you may see true christianity,
and preaching the gospel of Christ Jesus, is called a sect and sedition,
by the professors of the scriptures without possession.

And when Paul was brought before Festus, he being willing to do the Jews a pleasure,
said to Paul, '`Wilt thou go up to Jerusalem,
there to be judged of these things before me,`' (to wit,
the things that the Jews accused him of,) then said Paul,
'`I stand at Caesar`'s judgment seat, and where I ought to be judged.
To the Jews I have done no wrong, thou knowest it very well.`' Then Festus,
when he had conferred with his council, said unto Paul, '`To Caesar thou hast appealed,
and unto Caesar thou shalt go.`' Acts 25.

And Paul preached a brave sermon to king Agrippa, that Agrippa said unto Paul,
'`Almost thou hast persuaded me to be a christian,`' etc.
Acts 26. And was not that in an house?
And then they sent Paul away by shipping, towards Rome, and the ship touched at Sidon,
and Julius, a centurian of Augustus`'s band, courteously entertained Paul,
and gave him liberty to go unto his friends at Sidon, to refresh himself;
and had not he a meeting there with his friends?
And Paul admonished the people in the ship,
and the centurian believed Paul more than the master of the ship,
as in Acts 27:22. And there was in the ship two hundred threescore and sixteen souls;
and had not he a meeting in the ship there?
And when they were cast upon Malta, the chief man of the Island, whose name was Publius,
received them, and lodged them courteously three days; and when Paul came to Rome,
the centurian suffered Paul to dwell by himself with a soldier, that kept him;
and Paul dwelt two whole years in his own hired house,
and received all that came in unto him, '`preaching the kingdom of God,
and teaching those things which concerned the Lord Jesus, with all confidence,
no man forbidding him.`' Acts 28:16. 30, 31.

Here you may see Paul kept a christian meeting in his own hired house at Rome,
and preached in it; so that they were more kind to him than the Jews,
that haled him out of the temple, and would have killed him. Acts 21:30-31.
And the apostle saith, '`Greet Priscilla and Aquila,
my helpers in Christ;
likewise greet the church that is in their house.`' Rom. 16:3-5. 1 Cor.
16:19. So here you may see the church was in Aquila`'s and Priscilla`'s house;
their house was a meetinghouse for the true christians.

And the apostle in his epistle to the Colossians, saith,
'`Salute the brethren which are in Laodicea and Nymphas,
and the church which is in his house.`' Col. 4:15.
Here you may see the church was in Nymphas`'s house;
and they met in a house, and did not call the house a church.
Paul`'s epistle '`To Philemon, and Apphia, and Archippus,
etc. and to the church which is in thy house.`' So here
you may see the church of Christ was in Philemon`'s house.
Phil.
Ver. 2.

And John writes to the seven churches in Asia, and he saith to every church,
'`He that hath an ear,
let him hear what the spirit saith to the churches.`'
So it is the spirit of God that speaks to the churches;
and the churches are not the outward temple or steeple-house, but the people of God;
and the people of God are the church,
who are to hear what the spirit of God saith to them.
So they that have a spiritual ear, are to hear what the spirit saith.

[.asterism]
'''

[.blurb]
=== Postscript

After Christ was risen, he said unto Mary, '`Touch me not,
for I am not yet ascended unto my Father; but go to my brethren, and say unto them,
I ascend unto my Father, and your Father,
and to my God and your God.`' And she came and told the disciples,
that he had spoken these things unto her; and the same day at evening,
being the first day of the week, when the doors were shut,
where the disciples were assembled, came Jesus, and stood in the midst, and said,
'`Peace be unto you.`' John 20:19. Mark 16:14. You may
see Christ met with his disciples in the evening,
on the first day of the week, who did rise on the same first day.
So he had a meeting with the disciples in a house the same first day he rose,
and not in the Jews`' temple or synagogues.

And the word of the Lord came to Jeremiah, saying,
'`Go and cry in the ears of Jerusalem,`' etc. Jer. 1:2.
And the word of the Lord came again to Jeremiah, saying,
'`Stand in the gate of the Lord`'s house, and proclaim, and say,
hear the word of the Lord, ye that enter in at the gates to worship the Lord,
amend your ways and doings,
and I will cause you to dwell in this place.`' Jer. 7:1-3.
Here you may see Jeremiah preached in the gate of the temple,
which is called the Lord`'s house.

And the Lord said to Jeremiah, '`Go down to the house of the king of Judah,
and speak there this word, etc.
Hear the word of the Lord, O king of Judah, that sits upon the throne of David, thou,
and thy servants, and thy people that enter in by these gates, thus saith the Lord,
execute ye judgment and righteousness,
and deliver the spoil out of the hand of the oppressor; do no wrong,
do no violence to the stranger, the fatherless and the widow;
neither shed innocent blood, etc.; but if ye will not hear these words,
I swear by myself, saith the Lord,
that this house shall become a desolation.`' Jer. 22:1-3. 5.
Here you may see Jeremiah went and preached at the king`'s house.

Thus saith the Lord to Jeremiah, '`Stand in the court of the Lord`'s house,
and speak unto all the cities of Judah, which come to worship in the Lord`'s house,
all the words that I command thee to speak unto them,
diminish not a word.`' Jer. 26:2. Here you may see Jeremiah
preached in the court of the Lord`'s house.

And the word of the Lord came to Jeremiah, saying, '`Go into the house of the Rechabites,
and speak unto them, and bring them into the house of the Lord,
into one of the chambers.`' Jer. 35:1-2,
to 19. And here you may see by the obedience of the Rechabites,
Jeremiah condemns the disobedience of the Jews,
and God blessed the Rechabites for their obedience.
And here you may see Jeremiah preached to the household of the Rechabites in the chamber.
So here is no strange thing to preach in houses, chambers, schools, highways, hedges,
streets, mountains, ships, deserts and wildernesses, in gates, and in the temple- doors,
the law and gospel, though they that did so were cast into prisons,
as Jeremiah in the prison, and in the dungeon; and the apostles were cast into prison,
and into the stocks, for preaching Christ Jesus, who preached him in such places,
as before, and many for preaching Christ in such places,
have been since cast into prisons and dungeons, by them that are called christians,
who could not own their synagogue and temple-worship,
but worship God in spirit and truth;
which worship Christ set up above sixteen hundred years ago.

G+++.+++ F.

Kingston, the 23d of the 5th Month, 1684,
