[#ch14.style-blurb, short="The State of the Birth Temporal and Spiritual"]
== The state of the birth Temporal and Spiritual, and the duty and state of a Child, Youth, young Men, aged Men, and Fathers in the truth.

[.heading-continuation-blurb]
Also, showing that Children are the Heritage of the Lord,
and that he hath a glory in them. By G. F.

The state and duty of a child, youth, and young men,
and the state of aged men and fathers, it is the Lord that doth bring to the birth.
David saith, '`My substance was not hid from thee when I was made in secret, etc.
Thine eyes did see my substance, yet being unperfect,
and in thy book all my members were written, which in continuance were fashioned,
when as yet there were none of them;
for thou possessed my reins when thou covered me in my mother`'s
womb.`' Here you may see God`'s infinite and all-seeing eye,
work, and providence.
The darkness nor secrets hide not from God, but the night shineth to him as the day,
and the darkness and the light are alike to his all-seeing eye, who made both;
and therefore all are to consider how God hath made them, and fashioned them.
Ps. 139.

And the Lord saith in Isa. 66. '`Shall I bring to the birth,
and not cause to bring forth, saith the Lord?
Shall I cause to bring forth, and shut the womb, saith my God?`' So here you may see,
it is the Lord that fashions in the womb, and brings it forth,
both the natural birth and the spiritual birth, and opens the womb and shuts the womb,
both the womb of the morning, and of eternity, and of the natural.

And the Lord said to Jeremiah, in the 1st chapter, '`Before I formed thee in the belly,
I knew thee, and before thou camest out of the womb, I sanctified thee,`' etc.
And so here all may see, and consider, and know themselves to be the great work of God;
that when God that forms and fashions you in the womb, and brings to birth,
and hath brought you forth, that you may choose the good and forsake the evil;
that you may remember and consider, that you are the work of the Lord,
and remember your Creator, and who hath fashioned you and formed you in the womb,
and hath brought you to a birth, and hath brought you forth to fear, and serve,
and worship, and honour him that hath made thee, and brought thee forth.
For as Solomon saith in Ecc. 12. '`Remember now thy Creator in the days of thy youth,
whilst the evil days come not,
or before the evil days do come.`' Now this is the duty of all youth,
let them be males or females, to remember their Creator,
and let him not go out of their memory,
so that they may be fitted to stand in the evil days when they come;
for when they grow up to be young men, then the evil days will appear,
in which they may be tempted to '`adultery, fornication, drunkenness, theft, murder,
lying, cozening, cheating, unrighteousness, ungodliness, lightness, wantonness,
pleasures,`' and other evils,
by which they may forget their Creator by going into such evils,
when they are tempted to such things.
The evil days are come to try youth,
for they that yield unto such evils before mentioned, forget their Creator,
and forsake him; for Solomon saith, '`Train up a child in the way he should go,
and when he is old he will not depart from it.`' Prov. 22:6.
Here is the duty of parents,
and the duty of children, which is to be practised and followed.
Now here is the duty of youth, '`to remember his Creator in the days of his youth,
before the evil days come.`' But what must we do when we come to be young men?
What is their means and duty?
David declareth in Ps. 119:9. '`Wherewith shall a young man cleanse his ways?
By taking heed thereto according to thy word, etc.
Thy word I have hid in my heart, and do meditate on thy word,
that I might not sin against thee.`' So now,
for all young men to take heed to the word of God in their hearts,
and hide it in their hearts, and to meditate upon it; for the word is called a hammer,
and a sword, and a fire, to hammer down, and cut down,
and burn up that which would defile them in their ways, words, and hearts.

And the apostle saith, '`that the word of faith which he preached,
was in their hearts and mouths, to obey it,
and to do it.`' Rom. 10. And '`the ingrafted word
was able to save their souls,`' James saith.
And Peter saith, '`that they were to feed upon the sincere milk of the word;
but they which are hearers of the word, and not doers of the word,
deceive their own souls.`' And Christ said to his disciples,
'`Now ye are clean through the word,`' etc.
So this word will keep the ways and the hearts of young men clean, the word of God,
which is a sanctifying word, a reconciling word; and Christ told the Jews,
his word had no place in them.

And again, he told the unclean Jews, '`Ye have not his word (to wit,
the word of God) abiding in you.`' So these Jews made a great profession of the scriptures,
but had not the word of God abiding in them;
John 5. then they were not like to be made clean by it.

And Christ said, '`Sanctify them through thy word, thy word is truth.`' (To wit,
his disciples and believers.) And again Christ saith, '`I have given them thy word,
and they have kept thy word,`' (namely, his disciples,) to wit, the word of God.
John 17.

Now here you may see the disciples kept the word of God,
which was the means to keep their hearts, ways, and words clean; but the Jews, priests,
Scribes and Pharisees, that made a great outward profession of the scriptures,
whose ways were unclean, and mouths full of foul unclean words against Christ,
Christ told them, '`that the word of God did not abide in them.`' And therefore,
though they had the scriptures, and made an outward profession of them,
like the professors of our age, and others who go from the means,
the word of God in their hearts, to keep their ways and lips clean, and to sanctify them;
therefore they plead for a body of death to the grave,
and a purgatory when they are dead,
who live in a profession of the letter without the word.

And John saith, '`I have written unto you young men, because you are strong,
and the word of God abideth in you;
and you have overcome the wicked one,`' viz. the devil, by the word of God,
which was before the devil was.
So here you may see,
what is the means by which the young men`'s ways are cleansed and sanctified,
and what makes them strong,
and to overcome the wicked one--the word of God abiding in them.
And therefore, every young man, and all young people are to love, and obey,
and do the word of God, by which their ways, words, and hearts,
and all may be kept clean; for the word of God is a hammer and a sword, to hammer down,
and cut down the devil and his works, and a fire to burn them up.
So it is the word of power, the word of wisdom, the word of reconciliation,
and the word of patience, by which they overcome.

Now concerning aged men or fathers in the truth, John saith, '`I have written unto you,
fathers, because you have known him that is from the beginning,`' to wit, Christ Jesus.
And John writes as a father himself, who saith, '`That which was from the beginning,
which we have heard, which we have seen with our eyes, which we have looked upon,
and our hands have handled of the word of life;
for the life was manifested and we have seen it, and bear witness,
and show unto you that eternal life, which was with the Father,
and was manifested unto us.`' 1 John 1:1-2.

So here you may see, not only John 1n his epistle, but also John in his evangelists,
declares Christ in the beginning, and saith, '`In the beginning was the word,
and the word was with God and God was the word; the same was in the beginning with God,
and all things were made by him, and without him was not any thing made that was made;
and the word was made flesh, and dwelt among us, and we beheld his glory,
the glory as of the only begotten of the Father, full of grace and truth.`' John i.

Now, here you may see how John writes as a father,
that knew Christ as he was in the beginning;
and he writes to the fathers that knew Christ as in the beginning.
So the fathers knew him in the glory that he had with the Father before the world began;
and that all things were made by Jesus Christ.
So they knew him as he was God, the word.
They knew Christ, as he was man:
'`The word was made flesh, etc.`'
They knew Christ in the promises and in the prophecies;
they knew him in the figures, types, and shadows made under the law.

'`They knew him, and of whom he was to be conceived, to wit, the virgin;
they knew him in his birth, life, doctrine, preaching, miracles, sufferings, death,
grave, resurrection, and ascension, into the glory with the Father,
and at his right hand; yea,
the glory which he had with the Father before the world began.
So the fathers have known, +++[+++mark, have known,]
Christ from the beginning. 1 John 2:14.

So, here you may see the state of the birth temporal and spiritual,
and the duty and state of youth, the duty and state of young men and young people,
and the state of fathers in the truth.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 10th mo.
1684.

[.asterism]
'''

David saith, '`Lo children are an heritage of the Lord,
and the fruit of the womb is his reward.
As arrows are in the hands of a mighty man, so are children of the youth.
Happy is the man that hath his quiver full of them: they shall not be ashamed,
but they shall speak with the enemy in the gate.`' Ps. 127.

'`Blessed is every one that feareth the Lord; that walketh in his ways:
for thou shalt eat the labour of thine hands.
Happy shalt thou be, and it shall be well with thee.
Thy wife shall be as a fruitful vine by the sides of thine house;
thy children like olive plants round about thy table.
Behold, that thus shall the man be blessed that feareth the Lord; yea,
thou shalt see thy children`'s children,
and the Lord shall bless thee out of Zion.`' Ps. 128.

Now all you that do murmur against people that have many children,
and do complain and say, '`that they do fill your towns, cities,
and countries with children;`' and many times you
that do so complain have few or no children;
and you are afraid that they should come to want,
and that then you must be fain to relieve their necessities.
And what then?
What you do give to the poor, you lend to the Lord, and he will repay it to you again,
if they cannot.
And this wanting mind, is for want of faith in God, who gives the increase of all,
and is rich unto all that call upon him.
And the Lord would have you to take notice that children are the heritage of the Lord.
And so, what you do give to the breeding, and nursing, and relieving of children,
you do it to the heritage of the Lord; and the Lord hath many adopted sons,
that he hath taken to be his,
'`that have received the adoption of sons.`' Gal. 4. And
what if you that have no children should do so?
It was but a cross to the grumbling or murmuring self, which many times have no children,
and are discontent with the poor that have many;
and do think much either to adopt them to yourselves,
and are afraid that they will be chargeable to you, namely,
the children that are the heritage of the Lord;
but the Lord that doth increase the children which are his heritage,
he will take care for his heritage,
whether that murmuring complaining mind against poor people of having so many children,
you relieving them or no, he will take care for his heritage.
Blessed be his name forever.
Amen.

'`Sing unto God, sing praises to his name:
extol him that rideth upon the heavens by his name JAH, and rejoice before him.
A Father of the fatherless, and a judge of the widows,
is God in his holy habitation`' Ps. 68. The sayings of old which we have heard,
and known, and our fathers have told us, we will not hide them from their children;
showing to the generations to come the praise of the Lord.`' Ps. 78. And David saith,
'`Let thy work appear unto thy servants, and thy glory unto their children,
and let the beauty of the Lord be upon us,`' etc. Ps. 90:16-17.

See what heavenly love he had to children, God`'s heritage.
So they are not of David`'s mind,
who think that they shall be undone by maintaining of poor people`'s children,
which children are God`'s heritage.
And David saith, '`Ye are blessed of the Lord, which made heaven and earth; the heavens,
even the heavens are the Lords,
but the earth he hath given to the children of men.`'
Ps. 115:16. And the Lord saith to David,
'`If thy children will keep my covenant and my testimony, that I shall teach them,
their children also shall sit upon thy throne
forevermore.`' Ps. 132:12. '`Praise the Lord,
O Jerusalem, praise thy God, O Zion; for he hath strengthened the bars of thy gates,
he hath blessed thy children with thee.`' These are they that keep in the covenant,
and the testimony that God doth give them, that have his blessings.

And you may see the tenderness of Joseph to his father, and to his children,
and to his children`'s children, in the days of the famine, when they were in Egypt.
Gen. 45. Here he was tender of children, which are the heritage of the Lord.
And the Lord said,
'`Thrice in the year shall all your men children appear before the Lord
God of Israel.`' Ex. 34:23. Here you may see the care the Lord takes,
that children, which are his heritage, should be acquainted with him,
which ought to be the duty of all parents.
And the Lord said, '`Take heed to thyself, and keep thy soul diligently,
lest thou forget the things which thine eyes have seen,
lest they depart from thy heart all the days of thy life: but teach them thy sons,
and thy sons`' sons;
especially the day that thou stoodest before the Lord thy God in Horeb,
when the Lord said unto me, (viz. Moses,) gather me the people,
and I will make them hear my words,
that they may learn to fear me all the days that they shall live upon the earth,
and that they may teach their children.`'

Here you may see the care of the Lord, to his people,
and how they are commanded to teach their children; yea, their sons`' sons;
that the children that are God`'s heritage might
be instructed by their parents in the things of God. Duet. 4:10.

And in the Old Testament the Lord God said,
'`Thou shalt do no manner of work on the sabbath day, thou nor thy son, nor thy daughter,
nor thy man servant,
nor the stranger which is within thy gate.`' They were all to rest on the sabbath day,
in the old covenant; so are all the believers, whether they be masters, or mistresses,
sons, daughters, or strangers, to rest in Christ in the new covenant;
for he that believeth is entered into Christ the rest, and ceaseth from his own works,
as God did from his.
'`Know therefore this day, and consider in thine heart,`' mark, in thine heart,
that the Lord he is God in heaven above, and upon the earth beneath; there is none else.
So with the spirit of God ye may know him in heaven, and know him in earth.
And thou shalt keep therefore his statutes and his commandments,
which I command you this day, that it may go well with thee, and thy children after thee,
that thou mayst prolong thy days upon the earth.`' Here again you
may see what care the Lord takes for his people and his children. Duet. 39:40.

And you may see in Nehemiah 5:5. how they complained of them and their children;
their sons and daughters were brought into bondage '`because of
going astray from the Lord`'s commandments.`' And in Nehemiah 9.
'`how they had rebelled against the good spirit of the Lord,
that he gave them to instruct them.`' And is not
this the cause now that christians are in confusion;
for rebelling against God`'s good spirit,
though they may make an outward profession of the new testament,
as the Jews did of the old?

Thus saith the Lord in Isa. 49. '`Behold!
I lift up my hand to the Gentiles,
and set up my standard to the people;`' and is not this standard Christ?
'`And they shall bring their sons in their arms,
and thy daughters shall be carried upon their shoulders.`'
And where do they carry their children,
and their sons and daughters?
Is it not to Christ, who teacheth them and blesseth them?
The Lord saith, '`I will make all my mountains a highway,
and my highway shall he exalted.`' And is not God and Christ`'s highway his light?
That is the path of the just, and highway to the perfect day.
And kings shall be nursing fathers, and queens nursing mothers,`' etc.
And that will be a happy day when they come to nurse Christ`'s chickens, doves, lambs,
babes, and little children;
then persecution will cease for not taking oaths and swearing, and for not paying tithes,
and for not going to the worship '`temples made with
hands;`' and then Christ`'s doctrine will be obeyed;
who saith, '`Swear not at all, but let your yea be yea, and your nay, nay,`' etc.
And then every one that hath received freely from Christ,
will '`give it freely,`' as he commands;
then every one will know their '`Bodies are the temples of the living
God;`' and then every one will '`walk in the light,`' God`'s highway,
which shall be exalted; and in it they '`have fellowship one with another,
and the blood of Christ, the son of God cleanseth you from all sin.`'

And Isaiah 54. '`All thy children shall be taught of the Lord;
and great shall be the peace of thy children`' that are taught of the Lord.
'`In righteousness shall they be established,`' that are taught of the Lord.
'`Thou shalt be far from oppression, thou shalt not fear; and from terror,
for it shall not come nigh thee`' that art taught of the Lord.
'`Behold, they shall gather, but not by me;`' so then it is by the wicked spirit;
'`whosoever shall gather together against thee,
shall fall for thy sake,`' '`that art taught of the Lord.`'
No weapon that is formed against thee shall prosper;
and every tongue that shall rise up against thee in judgment, thou shalt condemn, etc.
This is the heritage of the servants of the Lord, and their righteousness is of me,
saith the Lord.`' And in 1 Kings 2:4. David saith,
'`That the Lord may confirm his word, which he spake concerning me, saying,
if thy children take heed to their way, to walk before me in truth,
with all their hearts, and with all their souls, there shall not fail thee, said he,
a man to sit on the throne of Israel.
See that thy children take heed to their way, and walk before me,
as thou hast walked before me to wit, David.

Now here, you may see,
that not walking in the truth before the Lord with all their souls and their hearts,
made such confusion among the Jews, and likewise makes,
or hath made such confusion among the christians:
for not walking before God in the truth, kept them off the throne of Israel.
And therefore children are to succeed their fathers`' path in the truth,
if they will be accepted and exalted by the Lord,
and if they do enjoy the comfort of the Lord, as their fathers did, with the promise,
as in 1 Kings 2:4. and viii.
25.

And Micah 2. he declareth against their oppression,
and reproves the Jews for their injustice and idolatry, and saith,
'`The women of my people have you cast out from their houses,
from the children have ye taken away my glory;`' to wit, the Lord`'s;
for children are the Lord`'s heritage, and he hath a glory in them.

And Joel declareth sundry judgments of God, and exhorts the Jews to observe them,
and bids the old men '`tell their children of it,
and let your children tell their children,
and let their children tell another generation.`' See what care was here,
and watches set up, that children`'s children might escape the judgments of God,
by their walking in the truth, and keeping to the Lord with all their hearts.
And children which were the Lord`'s heritage,
were to warn and tell one another to walk in the fear and way of the Lord,
with their whole hearts, that he might have his glory in them,
and their children which are his heritage.

And you may see in Luke 19:43-44. the judgments
that Christ pronounceth upon the Jews and their children,
that disobeyed God, and did not believe in him.
And Christ saith, '`While ye have the light, believe in the light,
that you may become children of the light.`' Here
Christ encourages his believers with a new name,
that believe in the light, to wit,
'`Children of the light.`' John 12:36. And Paul saith to the believers in the light,
'`Ye were sometimes darkness, (that was,
when they did not believe in the light,) but now are ye light in the Lord;
walk as children of the light.`' Eph. 5:8. '`Ye are all the children of the light,
and the children of the day; we are not of the night,
nor of darkness.`' 1 Thess. 5:5. These are the believers in the light,
as Christ commands.

And John saith,
'`My little children (1 John 2:2) these things I write unto you that you sin not,
etc. and if any man sin, we have an advocate with the Father, Jesus Christ,
the righteous, etc.
+++[+++But they must take heed of sinning willfully.]
I write to you little children, because your sins are forgiven you,
for his name sake.`' Here is a comfort to Christ`'s little children.
Again, John saith to little children, '`It is the last time,
and as ye have heard that antichrist should come, even now are many antichrists,
whereby we know that it is the last time; they went out from us, (to wit,
the antichrist,) but they were not of us, (to wit,
the elect members of the church of Christ,) for if they had been of us,
they would no doubt have continued with us; but they went out from us,
that they might be made manifest that they were not all of us.
And these things I have written unto you concerning them that seduce you:
but the anointing, which ye have received of him, abideth in you,
and you need not that any man teach you,
but as the same anointing teacheth you of all things, and is truth, and is no lie;
and even as it hath taught you, ye shall abide in him.
And now, little children, abide in him, (to wit, Christ.) Whosoever abideth in him,
sinneth not; whosoever sinneth, hath not seen him, neither known him.
Little children; let no man deceive you, he that doth righteousness, is righteous,
even as he is righteous; he that committeth sin is of the devil;
for the devil sinned from the beginning.
For this purpose the son of God was made manifest,
that he might destroy the works of the devil.
Whosoever is born of God, doth not commit sin, for his seed remains in him,
and he cannot sin because he is born of God.
In this the children of God are manifest from the children
of the devil,`' which is a clear manifestation and distinction.

Again, John saith, '`My little children, let us not love in word, neither in tongue,
but in deed and in truth.
Hereby we know that we are of the truth,
and shall assure our hearts before him.`' This is a good trial, little children.
1 John 3. '`Ye are of God, little children, and ye have overcome them, (to wit,
antichrist, and the world and its god,) because greater is he that is in you,
than he that is in the world; (a good reason to little children,
the greater to overcome the lesser;) and every one that loveth him, (to wit,
God that begot him,) loveth him also that is begotten of him;
by this we know we love the children of God, when we love God,
and keep his commandments.`' This is a good trial, and a manifestation. 1 John 5:1.

And Paul saith to the Galatians, in chap.
iv. '`My little children, of whom I travail in birth again,
until Christ be formed in you.`' This is a good travail,
which should be every true christian`'s, and not to travail to persecute Christ,
where he is formed within his people; for that is a bad travail.
And John writes to the elect lady and her children, whom he loved in the truth,
etc. and said,
'`I rejoiced greatly that I found thy children walking in the truth,`' etc.
This is cause of great joy to see God`'s children walk in the truth.
Again, he writes; Gaius whom I love in the truth,
(said he,) I have no greater joy than to hear that thy children walk in the truth.
3 Epist.
of John.
Now this is a concern for all true christians,
that they and their children walk in the truth,
that they may have joy and comfort of them in the Lord and his truth,
in this world and in the world to come.
'`And every one that names the name of Jesus,
let them depart from iniquity,`' and not in iniquity,
and to see that their children do depart from iniquity; for David saith,
'`The Lord hates all workers of iniquity,`' and saith, '`Depart from me,
all ye workers of iniquity.`' And therefore train up all
your children in the nurture and fear of the Lord,
that both you and they may all serve God in his spirit, in your creation and generation;
for children are the heritage of the Lord, and ought to be trained up in his fear,
and serve and worship him in his spirit and truth;
for it is the Lord that gives the increase of them all.
It is he that brings to the birth, and gives power to bring forth,
whether it be natural or spiritual, and the life, and breath,
and the souls of all are in his hand and power.

'`I was by him, as one brought up with him.
I was daily his delight, rejoicing always before him,
rejoicing in the habitable parts of his earth; and my delights are with the sons of men.
Now therefore hearken unto me, O ye children! for blessed are they which keep my ways.
Hear instruction, be wise,
and refuse it not.`' Prov. 8. Here you may see the eternity of wisdom,
which is to be desired, for the blessing it brings.

The apostle Paul tells the Corinthians, '`I have espoused you to one husband,
that I may present you as a chaste virgin to Christ.`' 2 Cor. 11:2.
