[#ch15.style-blurb, short="Trying of Spirits in Our Age Now"]
== Trying of Spirits in our age now, as in the Apostles`' days, by the Spirit of Christ the anointing within.

[.heading-continuation-blurb]
Showing also, that the Church of Christ hath authority and power from Christ,
their head, to admonish; judge, reprove, and rebuke,
such as make a profession of the truth, but do not walk and live in the truth. By G. F.

Dear friends, and brethren in the Lord Jesus Christ,
who is your heavenly rock and foundation, and your holy sanctuary, your place of safety,
who destroys the destroyer, and is our saviour, the chief bishop of your souls,
to oversee you;
and your great prophet that God hath '`raised up for you to hear
in all things,`' and the chief shepherd who hath '`laid down his
life for his sheep;`' who feeds his sheep with his heavenly food,
and clothes them with his heavenly clothing,
'`whom he hath bought with a price,`' his blood;
and that they might know his voice and follow him,
'`who is from above,`' and not of this world;
whose voice is distinct from all the voices of this world, that are below;
'`who gave himself a ransom for all,
to be testified in due time;`' who is the mediator between God and you;
in whose name you have all salvation; in whose name, power, and authority,
we meet that are his followers; and he is before all things,
and by him all things subsist; who hath delivered us from the power of darkness.
And God hath translated us into the kingdom of his dear son,
and therefore '`whatsoever ye do in word or deed, do all in the name of Jesus Christ,
giving thanks to God and the Father by him.`'

For, friends, ye know the light God hath commanded to shine out of darkness,
and hath shined in your hearts to give you the light of the knowledge
of the glory of God in the face of Christ Jesus,
which light is the life in him.
Now, you have this '`heavenly treasure in your earthen vessels, which is of God,
and have received the grace of God which brought
your salvation,`' and by which you are saved,
and your hearts established in the election and covenant of grace.

Now they that hate the light of Christ,
and walk despitefully against the spirit of grace, such are of the birth of the flesh,
which do persecute them which are born of the spirit.
But as the apostle said, '`All that will live godly in Christ Jesus,
shall suffer persecution;`' but the Lord`'s portion is his people, and Jacob,
the second birth, the election, who is the supplanter of profane Esau,
he is the Lot of God`'s inheritance, to wit, Jacob.
The Lord led him about and instructed him, and kept him as the apple of his eye;
so tender is the Lord of his elect people.
And again, the Lord saith, '`He that touches you, (to wit,) his elect or chosen people,
touches the apple of God`'s eye.`' So you know the apple of the eye is a tender place.
So the Lord hath a sense of all his suffering people, and is nigh unto them,
and feels all their sufferings.

And now, friends, the apostle John writes a General Epistle to the church of Christ,
as I do to you the church of Christ.
Now, '`ye have an unction from the Holy One, and by it ye know all things;`' and now,
this unction or anointing within, which ye have received from the Holy One,
which '`abides in you, ye need not that any man teach you,
but as the same anointing teaches you of all things, and is truth, and is no lie,
and even as it hath taught you, and does teach you,
ye shall abide or continue in the son and in the Father, in whom ye have eternal life,
according to his promises.`' Now, all, since the apostles`' days,
that are gone from this anointing, and unction, and teaching within,
that comes from the Holy One, such are gone and wandered from the Father and the son,
and seduced from the anointing and teaching within,
by which they should have continued in the son and the Father.
But, my friends and brethren in Christ Jesus,
that have the anointing and unction within you, which ye have received from the Holy One,
and by it you continue in the son and Father; by this unction and anointing within you,
the church of Christ knows all things,
as the church of Christ did by the same unction in the apostles`' days; and therefore,
the apostles bid the church of Christ, by this unction,
'`Try the spirits,`' and bid them '`believe not every spirit,
but try the spirits whether they be of God;`' and
they know the spirit of God from the spirit of error.
So there you may see, with this unction they could try spirits,
and knew the spirit of truth from the spirit of error.
He doth not bid the church try their words only, but '`try their spirits,
whether they were of God,`' yea or nay; for many had good words and fair speeches,
and deceived the hearts of the simple.
And were not these a kind of Christians that served not the Lord Jesus Christ?
etc. which the apostles warned the Romans of,
in Rom. 16. and such that had gotten '`the form of godliness,
and denied the power thereof, that were heady, high-minded, without natural affections,
truce breakers, etc. false accusers, incontinent, fierce,
despisers of them that were good,`' that were compared to Jannes and Jambres,
that withstood Moses.
'`So do these also resist the truth, men of corrupt minds,
reprobates concerning the faith,`' etc.
And did not these go under the name of Christians and leaders,
'`which had the form of godliness,
but denied the power thereof,`' which the church were to turn away from,
and not to follow?
And is there not of this sort now, that trouble the church of Christ,
as they did in the apostles`' days?

And therefore, as the apostle saith,
'`Try their spirits whether they are of God or no.`'
The apostle did not say to the church of Christ,
'`Try them, whether they had the good words, and fair speeches,
and the form of godliness, but try their spirits,`' whether they be of God, yea or nay;
and so, if they have not the power of godliness, they are to be turned away from.
And therefore, with the anointing within, by which you may know all things,
with it '`Try their spirits,`' whether they be of God or no,
and try whether they have the power of godliness; yea,
such as have the fair speeches and good words, and the form of godliness,
try their spirits whether they be of God, and whether they have the power of godliness;
and if not, they are to be turned away from.

And the apostle exhorts Timothy '`to avoid profane
and vain babblings and oppositions of science,
falsely so called, which some professing,
have erred concerning the faith;`' therefore the church is to avoid such things now,
as then, lest they err concerning the true faith of Christ.
And 1 Tim. 6:20-21. Phygellus, and Harmogenes, and Hymeneus, and Philetus,
do not you think that these had gone under the name of christians in the apostles`' days,
though '`their words will eat as doth a canker,
them that do receive them;`' and such troubled the church of Christ then,
and the same spirit now, which is to be tried and turned away from, and not only so,
but to '`shun profane and vain babblings,
for they will increase unto more ungodliness,`' therefore
that is to be kept out of the church.

And the apostle exhorts Timothy to charge them, (to wit, the church,) before the Lord,
that '`they strive not about words to no profit:`'
and therefore that strife which is to no profit,
and to the subverting of the hearers,
the charge now is for the church of Christ to shun such things,
and if any man teach otherwise, and consent not to wholesome words,
and the words of our Lord Jesus Christ, and the doctrine which is according to godliness,
he is proud, or a fool, and knowing nothing,
but doting about questions and strife of words, whereof comes envy, strife, railing,
evil surmisings, perverse disputings of men of corrupt minds, and destitute of the truth,
supposing that '`gain is godliness,
from such withdraw thyself.`' So must all the members of Christ`'s church now
in our age withdraw themselves from such that are destitute concerning the truth,
though such may go in the name of christians, as such might do in the apostles`' days,
and troubled the church of Christ then, as they do now.
But '`believe not every spirit,
but try their spirits,`' whether they have the power of godliness, yea or nay.

Now the spirit speaks expressly,
'`that some should depart from the faith,`' (then they had
it once,) and that they would give heed to seducing spirits,
and doctrine of devils, speaking lies in hypocrisy,
having their consciences seared as with a hot iron, forbidding to marry,
and commanding to abstain from meats,
which God hath created to be received with thanksgiving,
etc. for every creature of God is good, (mark,
good,) and nothing to be refused if it be received with thanksgiving,
for it is sanctified by the word of God and prayer.`'

For all things were made and created by the word, and all things upheld by the word, etc.
And by the word of God, man and woman is sanctified, and it sanctifies things to them.

And do ye not think that these that had departed from the faith,
and given heed to the doctrines of devils, forbidding marriages,
and to abstain from meats, etc. went not under the name of christians,
as too many such do now?
And therefore the apostle saith, '`Try their spirits, whether they be of God or no,
and whether they be in the power of godliness, and in the faith of God`'s elect.`'

And the church of Christ now, as in the apostles`' days,
is to '`shun profane and old wives`' fables, and to exercise themselves in godliness;
'`for bodily exercise profits little,`' or for a little time;
'`but godliness is profitable unto all men, having the promise of this life that now is,
and of that life which is to come.`' So all that have a care of the church of Christ,
will mind those things which are for the comfort and edifying of it.

And the apostle, his charge was to some, '`not to give heed to endless genealogies,
which ministered questions, rather than to godly edifying,
which is in faith,`' from which some have turned aside unto vain janglings.
And therefore foolish and unlearned questions avoid,
knowing that they do gender unto strife.
These things the church of Christ were to shun then, and now,
and follow godly edifying in the faith;
for did not they go under the name of christians that turned aside unto vain jangling,
and such that desired to be teachers of the law, understanding neither what they say,
nor whereof they affirm?
And, therefore, as the apostle said, '`Try their spirits whether they be of God,
and whether they be in the power of godliness;`' for that
spirit that doth not understand what it saith of the law,
cannot understand what it saith of the gospel: so is not fit to be a teacher of either.

And the apostle exhorted Timothy,
(2 Tim. 4:3) '`to preach the word in season and out of season, reprove, and rebuke,
and exhort with all long-suffering and doctrine;
for the time will come when they will not endure sound doctrine,
but after their own lusts shall they heap to themselves teachers, having itching ears,
and they shall turn away their ears from the truth, and shall he turned unto fables.`'

Now were not these itching ears, and their teachers,
that should turn from the truth to fables, a kind of christians,
who could not endure sound doctrine,
therefore their spirits are to be tried whether they be in the truth and sound doctrine;
for the itching ears that will have teachers after their lusts,
the spirit that hath tried them saith, they are turned from the truth to fables.

And Simon Magus, and Demas, that forsook Paul,
and '`loved this present world,`' and Alexander,
had not they gone under the name of christians?
But the spirit that tried them, saw Demas turned a worldling,
and Simon Magus turned to his old wickedness again;
and the apostle exhorts Timothy to beware of Alexander the coppersmith,
'`which had done him much evil,`' for he had greatly withstood the apostle`'s words.

So here you may see the apostle, which was a watchman, and tried their spirits,
such as he had tried not to be of God, nor in the truth, nor in the faith,
nor in the power of godliness, he exhorted the church of Christ, and the ministers,
to beware, and to shun, and to turn away from such.

And the apostle exhorts Titus, '`to hold fast the faithful word as he had been taught,
that he might be able, by sound doctrine,
both to exhort and convince the gainsayers;`' for, saith he,
'`There are many unruly and vain talkers, and deceivers,
especially they of the circumcision, whose mouths must be stopped,
who subvert whole houses, teaching things which they ought not for filthy lucre`'s sake;
they professing that they know God, but in works deny him;
being abominable and disobedient, and to every good work reprobate:
wherefore,`' saith the apostle to Titus, '`reprove them sharply,
that they may be sound in the faith.`'

Now did not, these vain unruly talkers, whose mouths were to be stopped,
which denied God in their works, and to every good work reprobates,
did not these go under the name of christians?
And are there not too many such in our days; unruly vain talkers,
that deny God in their works, and are reprobates to every good work?
For there are too many such unruly talkers and professors of God and Christ in words,
but in their works deny him, and are reprobate to every good work.
Such are against the practice of truth and religion, both in themselves and others,
and therefore all such spirits are tried with the anointing within, not to be of God,
neither now, nor in the apostles`' days, nor in the power of godliness,
therefore are to be turned away from; and all such that give heed to Jewish fables,
and commandments of men, that turn from the truth.
This the apostle exhorted Titus not to give heed to, but to '`avoid foolish questions,
and genealogies, and contentions, and strivings about the law,
for they are unprofitable and vain.`'

And therefore whatsoever is unprofitable and vain,
the church of Christ is to be turned away from now as in the apostles`' day,
for it is out of the power of godliness;
and therefore try their spirits whether they be of God or no.

And the apostle saith, '`Rebuke not an elder, but entreat him as a father;
and the younger men as brethren, and the elder women as mothers;
the younger women as sisters, with all purity.
Against an elder receive not an accusation, but before two or three witnesses;
but a man that is an heretic, after the first and second admonition, reject,
knowing that he that is such is subverted and sinneth,
being condemned of himself.`' Therefore, I say,
try such spirits with the anointing within, whether they be of God or no;
for a man errs from the spirit of God before he be a heretic;
for you read that the Jews had the scriptures,
and many that are called christians have got the scriptures, the form of godliness;
but the prophets told the Jews, '`that they rebelled against the spirit of God,
and resisted the holy ghost;`' and so they tried their spirits,
and found them not to be of God.
So must they that go under the name of christians, (that have the form of godliness,
but deny the power thereof,) be tried now with the
holy ghost that giveth forth the scriptures,
whether they be in it or no.

And Christ speaks of the false prophets and antichrists to his disciples,
Matt. 7. how that they should '`come in the sheep`'s clothing,
but inwardly they should be ravening wolves,
and by their fruits they should know them;`' but were not these like sheep,
and christians, when they had gotten the sheep`'s clothing on, the form of godliness,
but were inwardly ravened from the spirit and power of God?
So their fruits were thorns and thistles.
So try their spirit, and what fruit they bear, whether they be of God, yea or nay;
for such inwardly ravening wolves are destroyers of the sheep of Christ,
and cannot bring forth good fruit, nor abide the practice of truth and pure religion;
and therefore Christ bid them beware of them, and not follow them;
and John bids the church believe not every spirit, but try their spirits,
whether they be of God or no.

And as Christ said, Matt. 7:22. '`Many should call him Lord, Lord, or Master,
and shall say, we have prophesied in thy name, and cast out devils in thy name,`' etc.

Now, did not these go under the name of christians, and were great preachers,
that could preach in the name of Jesus, and do such miracles?
But Christ saith, he will profess he never knew them, and saith, '`Depart from me,
ye workers of iniquity.`' And Christ saith, '`It is not every one that saith, Lord, Lord,
shall enter into the kingdom of heaven,
but he that doth the will of his father which is in heaven.`'

And so you may see here, it is not every one that saith, Lord, Lord,
nor them that preach in the name of Jesus, and have the form of godliness,
and not in the power of God, that Christ receives, and that entered into his kingdom;
but such as depart from iniquity, and do the will of God, that are received by Christ,
and that enter the kingdom of God; for the apostle himself saith, '`I keep under my body,
and bring it into subjection, lest that by any means when I have preached to others,
I myself should be a cast-away.`' Here the apostle had not only a care of others,
but of himself, that he might be preserved in Christ Jesus.

And there were certain vagabond Jews, exorcists,
took upon them to call over them that had evil spirits in the name of the Lord Jesus,
saying, '`We adjure you by Jesus,
whom Paul preaches.`' And there were seven sons of one Sceva, a Jew,
and chief of the priests, which did so, and the evil spirit answered and said,
'`Jesus I know, and Paul I know,
but who are ye?`' And so the evil spirits came over them, and prevailed over them,
and against them, that they fled away naked, etc.
So you may see here, it is not them that take upon themselves to use the name of Jesus,
and the name of Paul, that gives dominion over the evil spirits,
but they that are in the spirit and power of Jesus, that Paul was in;
this is it that arms them and clothes them.

And all such as preached up outward circumcision, or else they could not be saved;
and also such as observe days, months, times and years,
and thought to be justified by the law, and not by the faith of Christ;
did not these go under the name of christians, whom the apostle said,
'`he was afraid lest he had bestowed upon them labour in vain;`' and of whom he said,
'`I travail in birth again, until Christ be formed in you, and if Christ be not in you,
you are reprobates?`' And they that sought to be outwardly circumcised,
Christ profited them nothing, etc.
'`For in Christ neither circumcision, nor uncircumcision availeth any thing,
but a new creature,`' and therefore the churches were not to trouble
themselves with that which did not avail any thing,
but mind the new creature in Christ, etc.

And those false brethren that came privily to spy out the liberty
which the apostles and the true christians had in Christ Jesus,
that they might bring them into bondage,
'`To whom (saith the apostle) we give place by subjection, no not for an hour,
that the truth of the gospel might continue with you,`' to wit, the church.
Gal. 2 6. And the apostle saith, but some of these seemed to be somewhat in conference,
but, '`they added nothing to me, and whatsoever they were, it makes no matter to me,
for God accepteth no man`'s person.`'

Now, here you may see the apostle makes use of his authority
in the power and spirit of Christ Jesus,
over such false brethren that came to spy out their liberty in Christ,
and bring them into bondage,
and though '`they seemed somewhat in conference,`' the apostle did not matter it,
'`for he knew God respected no man`'s person,`' to
whom he would not bestow an hour`'s time withal,
that the truth of the gospel might continue with the church.
But did not these go under the name of christians?
Did not the apostle here try their spirits, whether they were of God or no?
And though they did seem somewhat in conference, it added nothing,
and such the church is to reject now, which brings into bondage.

And the apostle saith to the church of the Colossians, Col. 2:18-23,
'`Let no man beguile you of your reward, in a voluntary humility,
and worshipping of angels, intruding into those things which he hath not seen,
vainly puffed up by his fleshly mind.
Not holding the head, from which all the body, by joints and bands,
having nourishment ministered, and knit together, increaseth with the increase of God.
Wherefore if ye be dead with Christ from the rudiments of the world, why,
as though living in the world, are you subject to ordinances?
Touch not, taste not, handle not, which all are to perish with the using,
after the commandments and doctrines of men.
Which things have indeed a show of wisdom in will-worship, and humility,
and neglecting of the body,
not in any honour to the satisfying of the flesh.`' Here the apostle,
who could try their spirits, would have others to try their spirits,
and had a care of the church,
and would not have them beguiled by intruders in the things they had not seen,
who were vainly puffed up with a fleshly mind, which held not Christ the head, etc.
These were gone from the light and spirit of God,
by which they might have seen the things of God;
so they were not likely to worship God in spirit and truth;
and therefore the church is to beware of such beguilers now, as in the apostles`' days,
and to try their spirits, whether they be of God or no.
And they that be dead, and risen with Christ, which are the church of Christ,
they are not to be subject to the rudiments, or elements, or ordinances of this world;
for they are not to touch, taste, nor handle the doctrines or commandments of men,
which are all to perish with the using, that are not after Christ, nor from him,
though they may have a show in will-worship and humility,
if they do neglect the body of Christ the church, and not hold him the head:
and all that spirit works, is but to satisfy the flesh, which brings no honour to God.

And therefore the church of Christ is to try the spirits of such now,
as in the apostles`' days, lest they should be beguiled of their reward.

And again the apostle saith,
`'Beware lest any man spoil you through philosophy and vain deceit,
after the traditions of men, and after the rudiments, or elements of this world,
and not after Christ.`' Here again you may see the apostle had a care of the church,
that they should try their spirits, not to follow that which is not after Christ;
and therefore the church is to beware of such things and spirits, lest they be spoiled.

And again the apostle warns the church,
'`lest any man shall beguile them with enticing words.`' And again he saith,
'`Beware of dogs, beware of evil workers, beware of the concision;`' that is,
false apostles which gloried in circumcision, and the apostle calls them concision,
which is a cutting off and tearing asunder of the truth.
See the margin in Phil. 3:2.

So the apostle would have the church to try such spirits then,
which the church ought to do now by the spirit of God, and anointing within;
and that they may not be beguiled with men`'s enticing words,
and they may beware of dogs, and evil doers, and evil workers,
etc. though they may come in sheep`'s clothing, fair speeches, and good words,
and a '`form of godliness,
but denying the power of it;`' from such the church is to turn away;
for the prophet saith, '`As to the wicked,
what have they to do to take God`'s words in their mouth,
and hate to be reformed?`' And Christ saith to such preachers,
that are workers of iniquity, '`Depart from me, I know you not;`'
and the apostle saith, 2 Tim. 2:19.
'`Every one that nameth the name of Jesus,
let them depart from iniquity;`' and so saith the church of Christ,
and all his faithful ministers now.

And the apostle saith to the church, Acts 20:29. '`I know this,
that after my departing shall grievous wolves enter in amongst you,
not sparing the flock;`' also '`of your own selves shall men arise,
speaking perverse things, to draw away disciples after them;
therefore watch and remember, that for the space of three years,
I ceased not to warn every one night and day with tears,`' and said,
'`Take heed therefore unto yourselves,
and to the flock over which the holy ghost hath made you overseers,
to feed the church of God which he hath purchased with his blood;`'
here you may see the apostles care of the church of Christ,
and with what they were to watch and oversee the flock of Christ,
and to feed his church withal, to wit, the holy ghost;
in which holy ghost is the church of Christ`'s communion,
by which they should try their spirits that were amongst them;
and were not these men that should arise among themselves, and speak perverse things,
and should draw away disciples after them, a kind of christians?
And would they not draw into a kind of separation from the church?
And did not the apostle say,
that `'They should have grievous wolves that would not spare the flock,
which should enter amongst them?
And had not they the sheep`'s clothing?
And is not the church of Christ to beware of all such now,
as were in the apostles`' days, and to watch against them with the same holy ghost,
and not to believe every spirit, but try them whether they are of God.

And the apostle said to the church, what saith the scripture,
'`Cast out the bond woman and her son,
the son of the bond woman shall not be heir with the son of the free woman,
for the son of the bond woman was born after the flesh,
and will persecute the free woman`'s children born after the spirit;
for the free woman`'s children which are the church of Christ, Jerusalem, which is above,
is their mother.`'^
footnote:[Gal. 4:30]

And again, the apostle exhorts the church of Christ,
and bid them '`take heed lest there be any fornicators or profane person, as Esau,
who for a morsel of bread sold his birth right;
for ye know that afterwards when he would have inherited the blessing he was rejected.
He found no place of repentance, though he sought it with tears;`'^
footnote:[Heb. 12:16]
and the apostle said to the church of Christ,
'`This is the message that ye have heard from the beginning,
that we should love one another, not as Cain, who was of that wicked one,
and slew his brother, and wherefore slew he him, because his works were evil,
and his brother`'s righteous.`'^
footnote:[1 John 3: 11-12]

And the church now must take heed of this nature of Ishmael, Esau and Cain,
though Cain did offer sacrifice, so he was a kind of a priest,
but a persecutor and a slayer of the righteous; and Ishmael was circumcised outwardly,
and was in an outward fellowship, yet he was wild, and a mocker,
and a persecutor of the heir of the promise.

And Esau he was also circumcised,
who despised his birth right for a mess of pottage and a morsel of bread,
who said in his heart he would kill Jacob, the second birth whom God loved;
but Esau and Ishmael were not circumcised with the spirit;
and therefore the church of Christ now is not to believe every spirit,
but try their spirits whether they are of God, or of Cain, Esau and Ishmael, and if so,
to beware of them.

And John, in his epistle to the church, said, 2 John 1:7.
'`Many deceivers were entered into the world, etc. look to yourselves,
etc. whosoever transgresseth and abideth not in the doctrine of Christ, hath not God;
and he that abideth in the doctrine of Christ, he hath both the father and the son.
If there come any unto you, and bring not this doctrine, +++[+++mark,
not this doctrine of the apostles]
receive him not into your houses, neither bid him God speed;
for he that bids him God speed, is partaker of his evil deeds.`'

Now here the apostle, with the spirit of Christ, warned the church of Christ in his day,
of such before mentioned; and the church of Christ now are to look to themselves,
and beware of such now that walk not in the commandments of Christ,
and abide not in the doctrine of Christ; such are transgressors,
and abide not in the Father and the son, though they may profess them both in words.
And the church of Christ had and hath authority in the power
and spirit of Christ not to receive such into their houses,
nor bid them God speed, etc. therefore try their spirits whether they be of God,
and lay hands on no man suddenly.

And the apostle saith, 3 John 1:9. '`I wrote unto the church: but Diotrephes,
who loves to have the preeminence among them, receiveth us not; wherefore if I come,
I will remember his deeds which he doth, prating against us with malicious words.
And not content therewith, neither doth he himself receive the brethren,
and forbiddeth them that would,
and casteth them out of the church.`' Now here you may see
the apostle`'s care of the church in his day then,
which ought to be so now, against such prating Diotrepheses with their malicious words,
which love to have the preeminence.
And did not this Diotrephes go under the name of a christian?
But John had the power and spirit of Christ to deal with him, and to remember his deeds,
and to judge them.
And so hath the church of Christ now, with the power and spirit of Christ,
to judge and try such spirits, whether they be of God or no.

And likewise the apostle James in his General Epistle,
he taught the church to try the pure religion from the false,
from such as seemed '`to be religious, and bridled not their own tongues,
that deceived their own hearts`'^
footnote:[James 1:26]
in their vain religion.

And likewise, the apostle brought the church to see '`who were the doers of the word,
not only hearers;`' for they that were '`only hearers and not doers,
deceived their own selves.`'

And also the apostle exhorted the church to try their faith and belief,
for many would say they had faith, and believed.
Then you would say these were called christians; but the apostle saith,
'`If a brother or sister be naked, and be destitute of daily food,
and if you say to them, depart in peace, be ye warmed and filled,
and you give them not those things which are needful to the body, what doth it profit?
Even so faith, if it have not works, is dead,
being alone.`' And therefore the true and living
faith is to be showed forth by its good works,
which will feed the hungry, and clothe the naked, and relieve the widow and fatherless;
and so to practice religion and faith, which is the victory,
and gives the victory over the devil and his bad works,
in which faith they do please God.

And so here you may see the practices of the church of Christ in the apostles`' days,
and now; and who are the hearers of the word, and not the doers of the word,
and who are in the pure undefiled religion,
etc. which is to visit the fatherless and the widow,
etc. and who seem to be religious in a vain religion,
and who are in the true living faith, and who are in the dead faith,
and who are in the pure peaceable wisdom that is from above, and its fruits,
and who are in the wisdom that is earthly and devilish below,
and whose dead faith brings them to respect a person,
because of his gold ring and gay apparel, and despise the poor; such,
their spirits are to be tried with the spirit of God, and anointing within,
in the church of Christ now, as in the apostles`' days.

And Peter, in his General Epistle to the church, tells them,
'`that there shall be false teachers amongst them,
who privily should bring in damnable heresy, even denying the Lord that bought them,
and should bring upon themselves swift destruction.
And many shall follow their pernicious and lascivious ways, by reason of whom,
the way of truth shall be evil spoken of.
And through covetousness shall they with feigned words make merchandise of you.
And there shall be false teachers amongst them; whose judgment, etc. lingered not,
and their damnation slumbered not.`'

And the apostle shows the church the state and example of the fallen angels,
and old world, and the cities of Sodom and Gomorrah, of their destruction,
and how God saved Noah the preacher of righteousness, and delivered just Lot,
who was vexed with the filthy conversation of the Sodomites.
But these, to wit, the false teachers that should come amongst the christians,
which the apostle speaks of, which are '`as natural brute beasts,
etc. that speak evil of the things they understand not;
sporting themselves with their own deceivings, as they feast with you, (to wit,
the christians,) beguiling unstable souls, etc. which have forsaken the right way,
(to wit, Christ,) and following the way of Balaam, (that is,
in the error from the spirit of God,) these are the wells without water,
carried about with a tempest, (mark,
with a tempest,) and speak great swelling words of vanity,
to allure them that escaped from them, etc. while they promise them liberty; yet,
themselves are servants of corruptions, for of whom a man is overcome,
of the same he is brought into bondage.
For if after they have escaped the common pollutions of the world,
through the knowledge of Christ, they are again entangled therein, and overcome,
the latter end is worse with them than the beginning;
for it had been better for them not to have known the way of righteousness,
than after they have known it, to turn from the holy commandment delivered unto them.
But it is happened, etc. the dog is turned to his own vomit again,
and the sow that was washed, to the wallowing in the mire.`'

Now here you may see what care Peter had, in his General Epistle,
of the church of Christ; the same care in the same power and spirit ought to be now.
And do you think that these false teachers had not,
or did not go under the name of christians, which were amongst the christians then,
and should make merchandise of them, and feasted with them,
which had forsaken the right way; but they could speak high swelling words of vanity,
to allure, and promise them liberty, to bring into bondage,
and it had been better for them '`not to have known the way of righteousness,
(which it seems they had,) than after they had known it,
to turn from it and the holy commandment;`' who had been washed,
and to turn again into the mire; and therefore the apostle very well might say,
'`Believe not every spirit, but try the spirits, with the spirit of God,
and the anointing within.`'

So the church of Christ is now to try such spirits,
and to blow the trumpet in heavenly Zion against such spirits, when they do rise;
and so you may see what kind of spirits these were, that promised liberty,
or what liberty it was which brings into bondage, and into the mire,
and to forsake the right way of Christ, in whom true liberty is;
and in him they are free, and yet,
as not using their liberty for a cloak of maliciousness, as too many do, and have done,
but using their liberty as the servants of God, in righteousness and holiness;
and this is the true church`'s liberty in Christ Jesus.

And Jude in his General Epistle to the church,
see what care he hath of the church of Christ, and exhorts them to contend for the faith;
for he saith, '`there were certain men crept in unawares,`' etc. yea, '`ungodly men,
that turned the grace of God into lasciviousness,`'
etc. and therefore they put the church in remembrance,
though they knew it, how that the Lord having saved the people out of Egypt,
and after destroyed them that believed not, but murmured, and rebelled against him;
and how that the angels, which kept not their first state, but left their habitation,
God hath reserved to everlasting chains of darkness,
etc. and how God overthrew Sodom and Gomorrah, for their wickedness;
and are set forth for an example,
suffering the vengeance of eternal fire.`' Now these examples,
and the unbelief of them that perished in Egypt, and the destruction of the old world,
and Sodom, and the angels not keeping their first state or habitation,
the apostles put the church in remembrance of,
that they should be steadfast in the holy faith, and contend for it,
and build one another up in it.

And the apostle saith, likewise these filthy dreamers, that had crept in at unawares,
ungodly men, which turn the grace of God into lasciviousness, which defile the flesh,
and despise dominion, and speak evil of dignities.
Now the dominion and dignities were of the power and spirit of Christ; but these also,
saith the apostle, speak evil of those things which they know not,
but what they know naturally, as brute beasts, in those things they corrupt themselves;
and too many such there are at this day.
But woe unto them, for they are gone in the way of Cain, that is in envy,
who was a destroyer, a killer, and a sacrificer too, who went from Christ, the way,
who came to save men`'s lives and to destroy the destroyer,
and they ran greedily after the error of Balaam, that is, from the spirit of God;
and are gone in the gainsaying of Korah, which was against the law,
and Moses the servant of God.
So these '`turn the grace of God,`' which should bring salvation
'`into lasciviousness,`' and have forsaken the right way.

The apostle saith, Jude 12. '`These are spots in your feasts of charity,
and when they feast with you, (to wit,) the true christians,
they feed themselves without fear.`' And they were in danger
to bring the christians to be without the fear of the Lord.
And the apostle saith, '`They are clouds without water,
carried about with winds;`' then they were chaff, and not wheat.
And the apostle said, '`they were trees, whose fruit withereth, and without fruit,
twice dead, and plucked up by the roots.`' Then they were not like to grow;
first dead in sin and trespasses, and then quickened by Christ, and then dead again.
These are the raging waves of the sea,
(they may be known by their rage,) foaming out their own shame; wandering stars,
not fixed in the firmament of God`'s power, etc.
These are murmurers and complainers, walking after their own lusts, and not after Christ;
and these with their mouths '`speak great swelling words,
having men`'s persons in admiration, because of advantage.`' And these are they,
who separate themselves; sensual, having not the spirit of God; and how can they,
when they are erred from it, and twice dead?
So here you may see a self-separation from the spirit of God in Cain, and Korah,
and Balaam`'s way, which turn the grace of God into lasciviousness.
The fallen angels, the old world, Cain, Korah, Balaam, and Sodom,
their example that they follow, that are the wells without water, trees without fruit,
clouds without rain, raging waves of the sea, foaming out their own shame,
wandering stars, lost their first state and habitation, murmurers and complainers,
their mouths can speak great swelling.
words, yet mockers; these be they who separate themselves, sensual,
having not the spirit, (as before,) filthy dreamers, defile the flesh, despise dominion,
speak evil of dignities; and what dignities and dominions were in the church,
in Jude`'s days, but the power and spirit of Christ in his church?
And therefore the apostle well might say, '`Believe not every spirit, but try them,
whether they be of God.`'

And the church of Christ is to try in our day, with the anointing within,
and with the spirit of Christ.
He saith, try such spirits and fruits, and of some '`have compassion,
making a difference; and others save with fear, plucking them out of the fire,
hating even the garments spotted with the flesh.`' And now
to him that is able to keep you from those false teachers,
and falling into their ungodly ways,
and is also able to present you faultless before the presence of his glory,
to him I commend you.

And John in the Revelations writes to the seven churches,
and Christ saith to the church of Ephesus,
'`Thou bast tried them which say they are apostles, and are not,
and hast found them liars,`' showing that they had power,
etc. and '`Thou hatest the deeds of the Nicolaitans, which I also hate.`'^
footnote:[Rev. 2]
Now here you may see, the church of Ephesus, in the power of Christ,
had authority to judge, and to try liars and false apostles,
and the deeds of the Nicolaitans; and in the same spirit and power of Christ now,
the church of Christ hath power to try,
and to judge such things with the anointing within, as they had in the apostles`' days.
And therefore, Christ saith, To him that overcomes,
I will give to eat of the tree of life, which is in the midst of the paradise of God.`'

And John writes to the church in Smyrna, and Christ saith, '`I know thy work,
and tribulation, and poverty, but thou art rich;
I know the blasphemy of them which say they are Jews, and are not,
but the synagogue of Satan.`'

So here you may see the power and spirit of Christ,
which did judge those that were not in the truth;
and Christ saith to the church of Smyrna, which was to be tried,
'`Be faithful unto death, and I will give thee a crown of life; and he that overcomes,
shall not be hurt of the second death.`' Here is
Christ`'s comfortable promise to the faithful.

And John writes to the church of Pergamos; and Christ saith,
'`I know thy works where thou dwellest, where Satan`'s seat is;
and thou holdest fast my name, and hast not denied my faith;`' to wit,
the faith of Christ, etc.
'`but I have a few things against thee,
because thou hast there some that hold the doctrine of Balaam,
etc. and hold the doctrine of the Nicolaitans, which thing I hate.
Repent, or else I will come unto thee quickly,
and will fight against them with the sword of my mouth,`' etc.

'`But to him that overcomes, I will give to eat of the hidden manna,
and will give him a white stone, and in the white stone, a new name written,
which no man knows,
saving he that receives it.`' Here you may see the care
and encouragement of Christ concerning the church.

Now were not these, that said they were apostles, but the church found them liars,
and they that said they were Jews, but found synagogues of Satan,
and these which held the doctrine of Balaam and the Nicolaitans, a kind of christians,
that were got among the churches then, who, with the power and spirit of Christ,
had authority to judge such spirits then, and now, in the church of Christ,
and to try their spirits whether they were and are of God?

And John writes to the church of Thyatira, etc.
'`I have a few things against thee, because thou sufferest the woman Jezabel,
which calls herself a prophetess, to teach and to seduce my servants,`' etc.

Now was not this Jezabel a kind of a christian,
which the church of Thyatira did not make use of the authority
in the spirit and power of Christ to judge and stop,
which they ought to have done, and to do now in the church of Christ,
with the power and spirit of Christ;
but Christ saith unto the rest of Thyatira that have not known this doctrine, to wit,
of Jezabel`'s, but that which ye have, to wit, the truth, '`hold fast until I come;
and he that overcomes and keeps my words unto the end,
to him I will give power over nations,`' saith Christ,
'`and he shall rule them with a rod of iron;
as the vessels of a potter shall they be broken to shivers,
even as I received it of my Father,
and I will give him the morning star.`' Here Christ
encourages his church with large promises,
to be faithful in his power and spirit, and to keep the authority of it, then,
and he is the same now to his church that are faithful
in the authority of his power and spirit.

And John writes to the church of Sardis, and encourages '`to be watchful,
and strengthen the things which remain that are ready to die; for I know thy works,
thou hast a name that thou livest, and art dead;
for I have not found thy works perfect before God.`' And if they did not repent,
and watch, and hold fast that which they had received,
Christ would come upon them as a thief, etc.;
'`but thou hast a few names in Sardis which have not defiled their garments,
and they should walk with Christ in white,
for they were worthy.`' Therefore it is good for the church to keep holy, clean,
and pure, for Christ saith such shall walk with him, the Holy One.
And Christ saith to the church of Sardis, '`He that overcomes.
the same shall be clothed in white raiment,
and I will not blot out his name out of the hook of life,
but I will confess his name before my Father,
and before his angels.`' Here is encouragement to
the church of Christ to be valiant for his name,
and to he faithful in his power and spirit.

And John writes to the church in Philadelphia, and Christ saith, '`I know thy works,
behold, I have set before thee an open door, and no man can shut it;
thou hast a little strength, and hast kept my word,
and hast not denied my name.`' '`Behold,`' saith Christ,
I will make them of the synagogue of Satan, which say they are Jews, and are not,
but do lie; behold, I will make them to come and worship before thy feet,
and to know that I have loved thee,`' etc.
Were not these a kind of christians, which were the sayers they were Jews, and were not,
but did lie,
that Christ with his power would make them come and worship before the church in Philadelphia;
but Christ bids the church in Philadelphia, '`Hold fast that which thou hast,
that no man take thy crown.
Him that overcometh, will I make a pillar in the temple of my God,
and he shall go no more out; and I will write upon him the name of my God,
and the name of the city of my God, which is New Jerusalem,
which cometh down out of heaven from my God,
and I will write upon him my new name.`' Now here you may
see how Christ encourages his church to be faithful,
and to overcome in his power, and Christ will write God`'s name, and his own new name,
and New Jerusalem`'s name upon them that do overcome,
and he will make them pillars in the temple of God.
Here the church may see what promises Christ hath promised to them.
He that hath an ear, let him hear what the spirit saith to the churches, then and now.

And John writes to the church of the Laodiceans, and Christ saith, '`I know thy works,
that thou art neither cold nor hot: I would thou wert either cold or hot;
because thou art lukewarm, and neither cold nor hot, I will spew thee out of my mouth,
because thou sayest, I am rich with the increase of goods, and have need of nothing,
and knowest not that thou art wretched, miserable, poor, blind,
and naked.`' And was not this church rich in outward profession,
but wanted the possession, and the fire of God`'s spirit, and its riches,
by which they should have been made rich,
and to see and be clothed with Christ`'s clothing.

And therefore the church of Laodicea, and all such that be rich in outward profession,
without possession, are to take counsel of Christ, who is head of his church,
and to buy of Christ, '`gold tried in the fire, that they may be rich, and white raiment,
that they may be clothed, and that the shame of their nakedness do not appear;
and anoint their eyes with eyesalve,`' that they may see
these things Christ`'s church must have from him.
And Christ saith, '`As many as I love, I rebuke and chasten; be zealous, therefore,
and repent.
Behold, I stand at the door, and knock;`' I, to wit, Christ; '`if any man hear my voice,
and open the door,`' to wit, of his heart, by the grace and the light of Christ,
'`I will come in unto him, and will sup with him, and he with me,`' to wit,
the heavenly marriage supper.
'`To him that overcomes, I will grant to sit with me in my throne,
even as I also overcame,
and sat down with my Father in his throne.`' Here
you may see the blessed promises of Christ,
that he hath promised to his church; which may encourage all to be faithful,
and to walk and live by the faith of Christ,
which is the victory by which they have access to God.

The apostle told the Philippians and the Ephesians,
'`Let no man deceive you with vain words; for many walk, of whom I have told you,
and now tell you even weeping, that they are enemies of the cross of Christ,
whose end will be destruction.`'

You may see what care in the spirit of God the apostle had of the church of Christ;
and were not these a kind of christians that the apostle warns the church of,
that they should not be deceived with their vain words;
and therefore the church of Christ is to beware of such now,
and try their spirits whether they be of God,
for the true fellowship is in the spirit of God.
And had not the apostle a great deal of trouble with the false apostles,
deceitful workers, transforming themselves into the apostles of Christ?
and said, no marvel, for Satan himself is transformed into an angel of light;
and therefore,
it is no great thing if his ministers also be transformed as the ministers of righteousness,
whose end shall be according to their works.
And are there not too many such, who pretend to be apostles and ministers in this day,
and such as boast themselves above their measure,
and without the measure of the spirit of God?
And were not these the false brethren whom the apostles
of Christ had to do withal in their day?
And now the servants of Christ have to do with the same,
(and have their perils,) who in the power of Christ, that daily comes upon them,
have the care of the churches now, as in the apostles`' days.

And did not these false apostles, deceitful workers,
that transformed themselves as the apostles of Christ,
and the ministers of Satan transform themselves as the ministers of righteousness?
I say, did not these go under the name of christians, and such as were puffed up?
But the apostle saith, '`I will come,
and I will not know the speech of them which are puffed up, but the power,
for the kingdom of God is not in word but in power.`' For Satan`'s ministers
and false apostles might have the good words and the fair speeches,
and speak great swelling words of vanity,
having the sheep`'s clothing and form of godliness, but denying the power thereof;
and therefore the church of Christ is not to believe every spirit,
but to try their spirits whether they be of God; and not to know their speech,
but the power, and to know whether they be in the power of godliness,
for the kingdom of God stands not in word but in power.
And therefore, it is the safe knowledge to know people not in speeches,
but in the power of God, and with the anointing, and the spirit of Christ within,
to try spirits whether they be of God or no,
for the unity of the church of Christ is in the spirit, which is the bond of peace,
and their fellowship, and comfort, and communion, is in the holy ghost,
which leads the church of Christ into all truth,
which proceeds from the Father and the son.

And doth not John say, concerning the antichrists and false prophets,
'`They went out from us, but they were not of us, for if they had been of us,
they would have continued with us,`' to wit, the church of Christ;
'`but they went out from us, that they might be made manifest,
that they were not all of us.`' And so now many such
have gone out from the church of Christ,
that they might be made manifest that they were not of us; but the church of Christ,
in the apostles`' days and now, have an unction and anointing from the Holy One in them,
which proceeds from the Father and the son;
and the church of Christ need not any man to teach them,
but as the same anointing teaches them; and as it doth teach them,
they shall continue in the son, and in the Father, from whence this anointing comes,
by which the church of Christ knows all things; yea,
those that would seduce them from this anointing; yea, the antichrists, and deceivers,
and false prophets that go out from the church, which are not of the church,
though they may have the form of godliness, fair speeches, and good words,
but deny the power thereof; from such the church of Christ is to turn away,
which know the power of words with the unction,
and the spirit of Christ can try their spirits,
that have the spirit of discerning whether they be of God,
and so they are not to believe nor follow every spirit,
but try them first what they believe in, and what they follow.
This was the practice of the church of Christ in the apostles`' days,
which ought to be the same now in the church of Christ;
by which anointing they continue in the Father and the son, as before said,
and in it they have fellowship with the Father and his son Jesus Christ.`' Amen.

And in the old testament Christ was preached and held forth by promises, and by figures,
types, and shadows, and by the prophets, and by the prophecies.
And when Christ was come, the apostles proved, out of the law, and the prophets,
and the Old Testament,
that Jesus was the Christ`' to the Jews that had the law and the promises,
Moses and the prophets; so, out of the scriptures, Moses, and the prophets,
they proved that Jesus was the true Christ.

And they were noble that did search the scriptures to see if these
things were so as the apostles preached concerning Christ.
And Christ did manifest himself to be the true Christ, by his preaching and doctrine,
miracles, sufferings, death, resurrection, and ascension, and in sending the holy ghost,
and appearing in his people, to be the true Christ, and the son of God.
And after Christ was risen, and preached both to the Jews and Gentiles,
and many believed in him, the apostle bids them examine themselves,
and prove their own selves, how that Jesus Christ was in them,
except they were reprobates.
So you may see, here are two proofs.
First to prove that Jesus was the Christ by Moses, and the law, and the prophets.

And the second proof was, after the Jews and Gentiles did believe in Christ,
they were to prove and examine themselves, whether or no Jesus Christ was within them;
if not, they were reprobates.
And again he saith,
'`Christ in you the hope of glory.`' And again he saith
'`That we may present every man perfect in Christ Jesus;
and let Christ rule in your hearts by faith; and he that hath the son of God hath life;
and he that hath not the son of God, hath not life;
and Christ was manifest in the flesh to condemn sin in the flesh,
that we through him might become the righteousness of God in Christ;
and such sat together in the heavenly places, in Christ Jesus.

And so the church, the saints now, with the unction within them,
and the spirit of Christ, are to try who are in the power of godliness, and who not,
and to try the power of words, and who make a profession of Christ without life;
and if Christ the life is not in them they are reprobates.
Therefore we are not to believe every spirit,
though they have a form of godliness and good words, and fair speeches,
with the sheep`'s clothing, but we are to try their spirits whether they be of God,
yea or nay.
That was and is to be the practice of the church of Christ with the anointing within,
which they have from the Father and the son,
which is sufficient for the church of Christ to try withal.
For the apostle saith;
`'By it they know all things;`' then all things were created by Jesus Christ.
Eph. 3. '`And all things were made by Christ the
word.`' John 1. So he was before all things,
and by him all things do consist.
Col. 1. And Christ is '`heir of all things; by whom God made the worlds,
and so he upholdeth all things by the word of his power.`' Heb. 1.
Who hath all power in heaven and in the earth given to him.

And '`if any man be in Christ he is a new creature,
and all things are passed away and all things are become new; and all things are of God,
who hath reconciled us to himself by Jesus Christ;
and God was in Christ reconciling the world to himself,`' etc. 2 Cor. 5.
'`Christ by whom the world was made; I say, reconciling all things to himself,
whether they be things in heaven, or in the earth,`' by Jesus Christ,
by whom God made all things both in heaven and in the earth,
that he might reconcile all things to God, who hath reconciled us to God;
Col. 1. who bruises the serpent`'s head, and slayeth the enemy,
and destroys the devil and his works; that in the dispensation of the fulness of times,
God might gather together in one all things in Christ, both which are in heaven,
and which are in the earth, even in him by whom they were made.
Eph. 1.

So Jew, Gentile, male, female, bond or free, are all one in Christ Jesus.
And the apostle Paul saith,
he was to make all men to see what is the '`fellowship of the mystery,
which from the beginning of the world hath been hid in God,
who created all things by Jesus Christ.`' Eph. 3. So this fellowship
hath been a mystery hid from the beginning of the world,
and their fellowship in the world,
but now '`is made manifest in Christ,`' by whom the worlds were made, to wit,
to his church.
And God who is faithful hath called us to the fellowship
of his son Jesus Christ our Lord, 1 Cor. 1. as he did the church in the apostles`' days.
And John in his General Epistle to the church of Christ, saith,
'`That ye also may have fellowship with us, and truly our fellowship is with the Father,
and with his son Jesus Christ.
And if we walk in the light, as he is in the light,
we have fellowship one with another.`' So here is
the true church`'s fellowship with God and Christ,
and one with another, that walk in the light, which is the life in Christ,
and not the vain talkers of the light, and walkers in darkness.

And David saith, '`Shall the throne of iniquity have fellowship with thee,`' to wit,
the Lord, '`which frameth mischief,`' etc. Ps. 94:20.
For the apostle saith, 2 Cor. 6.
'`what fellowship hath righteousness with unrighteousness,
or what communion hath light with darkness?`'
And the apostle saith to the church,
'`I would not have you to have fellowship with devils.`'
And the apostle told the church of Christ,
that their fellowship was in the gospel, the power of God which was before the devil was,
and his fellowships.
And such come to know the power of the resurrection of Christ,
and the fellowship of his sufferings.
And such had a fellowship with the Father and with the son, after Christ was risen;
and such had no fellowship with the unfruitful works of darkness,
but rather reproved them.
And the apostle said, '`The cup of blessing which we bless,
is it not the communion of the blood of Christ?
And the bread that we break, is it not the communion of the body of Christ?
For we being many, are one bread and one body,
for we are all partakers of that one bread.`' Is
not this the bread Christ which comes down from heaven,
as in John 6.? And his blood, which Christ saith,
'`they must eat and drink if they have life in them?`'
In which bread and blood is the saints`' communion;
and the saints and the church of Christ`'s communion now, and in the apostles`' days,
is in the holy ghost, 2 Cor.
xiii.
which proceeds from the Father and the son, which leads them into all truth.
And the church of Christ`'s communion is not in that which proceeds from men below;
but in that which proceeds from God and his son;
unto whom be glory in the church by Christ Jesus, throughout all ages, world without end.
Amen.

There are many opposers of the order of the truth,
and of the glorious gospel of Christ the power of God, who never grew up in the truth,
though they have had some opening and some sights, and it may be,
are come so far as Korah, Dathan, and Abiram; and so far as Cain and Balaam;
and so far as these that John speaks of in his General Epistle, that went '`from us,
and had they been of us,
no doubt but they would have continued with us;`'
and such as come so far as the apostle speaks of,
these '`heady, high-minded, and self-willed, fierce, despisers of them that are good,
that had the form of godliness, but denied the power thereof;
and these that with good words and fair speeches deceived the hearts
of the simple;`' and these false brethren and false apostles,
and false teachers that promised liberty, to beguile and bring into bondage:
all these might get the form of godliness, but deny the power thereof,
and so the order thereof, and were '`men of corrupt minds,`' who did resist the truth,
which now rules in the hearts of God`'s people; and so then,
resisted the order of the truth and the gospel of the holy government of Christ;
and such as James speaks of in a '`seeming vain religion,`' which did not warm, clothe,
and feed their brother or sister,
nor visit the fatherless and widows in their tribulation, etc.
Such might be hearers and talkers of the word, but not doers of the word;
and boasters of faith, and belief, and religion,
but were out of the works and practice of the living faith, belief, and pure religion.
And there are too many such now, as was then in the apostles`' days,
who profess they know God, but in works deny him, being abominable, and disobedient,
and to every good work reprobate.`'

And also Peter and Jude declare against filthy dreamers, that despise dominion,
and speak evil of dignities, and are presumptuous, self-willed, and wells without water,
and trees without fruit, twice dead, and plucked up by the root;
and carried about of the winds, or with a tempest, and clouds without rain,
and raging waves of the sea, foaming out their own shame.
These are the murmurers and complainers,
etc. and with their mouths they speak great swelling words,
etc. and these are they who separate themselves, '`sensual,
having not the spirit,`' but are erred from it like Balaam;
and then speak evil of dominion and dignities,
as Korah and his company did against the law of God and Moses;
and so do these against the dignities and dominions of the truth,
and spirit and power of God, the gospel,
and his apostles and ministers of the spirit and the gospel of Christ,
and the holy order of the truth, and spirit and gospel of Christ,
whose government and increase of it hath no end,
who now rules in the hearts of his people, in males and females, his church,
who is the glorious head of it.

And the apostle saith, '`Let the elders, that rule well,
be counted worthy of double honour,
especially they that labour in the word and doctrine.`'

Now, they that labour in the word,
labour in that word by which all things were made and created,
and in that word that upholdeth all things by his power.
And John saith, '`In the beginning was the word of life, which they had heard, and seen,
and looked upon,
and handled with their hands the word of life.`'
And so the elders do labour in the word of life,
which was in the beginning, and all things were made by it;
and this is the word of reconciliation,
which is committed to Christ`'s ministers of the spirit.
And so they do labour in this word, by which they are made clean and sanctified,
and by this word all things are sanctified to them,
by which word they were made good that do labour
in the word by which all things were made.
And this is the word that doth reconcile God`'s people to God,
and all things in heaven and in earth;
and this is the word by which all God`'s children are born
again of the immortal seed by the word of God,
and do feed on the milk of the word by which all things were made;
which word lives and abides forever.
And this is the word, which by the gospel is preached unto you, to wit, the church.
And John saith, '`the old commandments is the word,
which ye have heard from the beginning, and is called the word of faith,
and the word of wisdom, and the word of patience, and the word of power,
and the word of life;`' in this word the ministers of the spirit did labour,
and the church of Christ was washed with the water of the word;
and this was the word that was performed to Jacob,
and which so often did appear to the prophets,
by which they saw Christ to come many years before
he came and was made manifest in the flesh;
and was the word whom the apostles preached, which the letter professors knew not,
nor know now, but by the revelation of the light and spirit of God.

And the apostle saith to the church of the Romans, '`Salute Urbane,
our helper in Christ.`' So the true ministers of the spirit were the helpers in Christ,
the second Adam.
And again the apostle saith, '`Greet them that be of the household of Narcissus,
which are in the Lord;`' so these were in religious families, that were in the Lord.
And salute '`Tryphena, and Tryphosa, who labour in the Lord.
And salute Persis,
which laboured in the Lord;`' so you do see how Christ`'s
ministers did labour in the Lord then,
and now.

And the apostle saith to the Corinthians, we are labourers together with God,
'`Ye are God`'s husbandry, ye are God`'s building;`' and the apostle saith,
that '`ye submit yourselves to such, and to every one that helpeth with us,
and laboureth in the Lord.`' And the apostle saith to the Philippians, '`I entreat thee,
true yokefellow, help those women which laboured with me in the gospel,
with Clement also, and with others, my fellow-labourers,
whose names are in the book of life.`'

Here you may see the women, as well as the men, laboured in the gospel, the power of God,
whose names were written in the book of life; so the apostles and ministers could then,
and the saints now, with the anointing within, try the spirits; and could,
and can tell who laboureth in the Lord, and in the word and gospel,
from the ministers of the letter.
Now to '`Him that is of power to establish you according to my gospel,`' to wit,
of Christ, and the preaching of Jesus Christ,
'`according to the revelation of the mystery,
which was kept secret since the world began, but now is made manifest,
and by the scriptures of the prophets,
according to the commandment of the everlasting God,
(so not of the commandment of men,) made known unto all nations for the obedience
of faith;`' according to Romans 16. And so now again the same gospel is preached
to them that have apostatized from it since the apostles`' days.
So the grace of God be with all them that love our Lord Jesus Christ,
and peace be with you all which are in Christ Jesus.`' Amen.

And '`God the Father, who hath loved us, and hath given everlasting consolation,
and good hope through his grace, comfort your hearts,
and establish you in every good word and work.`'

Now, all my dear friends and brethren in Christ Jesus, in the bowels of Christ Jesus,
consider all these things for your good and comfort in him.
Amen.

And you may see in Ps. 120. how godliness hath the promise,
of this life and that which is to come.
And David saith, '`Blessed is the man that fears the Lord,
surely he shall not be moved forever;
and the righteous shall be in everlasting remembrance,`' mark, everlasting remembrance.

And again in Ps. 24. the citizens of God`'s spiritual kingdom,
'`Lift up your heads,`' saith Christ, '`O ye gates, and be ye lifted up,
O ye everlasting doors, and the king of glory shall come in.
Who is the king of glory?`' The Lord of Hosts, he is the king of glory.
And where doth he come in, but in the hearts of his people?

And in Prov. 20. '`As the whirlwind passes, so is the wicked no more,
but the righteous is an everlasting foundation, the righteous shall never be moved;
the lips of the righteous know what will be acceptable,
but the mouth of the wicked speaks frowardness.`'

And Isa. 56:5. the Lord saith, to '`them that were faithful,
even unto them will I give, in mine house and within my walls, a place and a name,
better than of sons and of daughters; I will give them an everlasting name,
that shall not be cut off.`'

And you may see the church`'s glory and increase, in Isa. 60. The Lord saith,
'`Whereas thou hast been forsaken, and hated, etc.
I will make thee an eternal excellency, a joy of many generations;
thou shalt call thy walls salvation, and thy gates praise.`'

And Jeremiah saith, '`The Lord is with me, etc. therefore his persecutors shall stumble,
they shall not prevail, they shall be greatly ashamed, for they shall not prosper;
their everlasting confusion shall not be forgotten.`' Jer. 20.
'`And I will bring an everlasting reproach upon you,
and a perpetual shame which shall never be forgotten.`' Jer. 23.

Here you may see the judgments of the Lord upon the wicked Jews.
And again, the Lord`'s promise is to the faithful, who saith,
'`I have loved thee with an everlasting love,
therefore with lovingkindness have I drawn thee: I will build thee, thou shalt be built,
O virgin of Israel,`' etc. Jer. 31.

And Christ saith, '`He that believeth on the son of God, hath everlasting life;`' mark,
hath everlasting life; '`but he that believeth not on the son of God, shall not see life,
but the wrath of God abideth on him.`' John 3:36. But
whosoever drinketh of the water that I shall give him,
(to wit, Christ,) shall never thirst; but the water that I shall give him,
shall be in him a well of water, springing up unto everlasting life.`' John 4:14.

And the apostle exhorts the Colossians,
to stand fast,`' etc. who were '`beloved of the Lord Jesus Christ, and God the Father,
who hath given us everlasting consolation,
who shall punish the wicked with everlasting destruction from the presence of the Lord,
and the glory of his power.`' 2 Thess. 1:9.

Now here you may see the everlasting misery of the wicked,
and the everlasting happiness of God`'s faithful people.
And Christ saith, '`My sheep hear my voice, and I know them, and they follow me,
and I give unto them eternal life, and they shall never perish,
neither shall any pluck them out of my hand; my Father which gave them me,
is greater than all,
and none is able to pluck them out of my Father`'s hand.`' John 10. Therefore,
it is good for all the sheep of Christ, to follow Christ, the shepherd,
who gives you eternal life, and keeps his sheep from them that would destroy them;
but they cannot pluck them out of Christ the shepherd`'s hand,
nor out of Christ the sanctuary, in whom they have peace and safety.
And in Christ`'s pastures of life he feeds his sheep with eternal life,
which hear Christ, the second Adam, his heavenly voice,
which is distinct from the voice of the devil and his angels,
and all the voices of natural Adam`'s sons and daughters below.

[.signed-section-signature]
G+++.+++ Fox.
