[#ch16.style-blurb, short="The Heavenly and Spiritual Worship of the Saints"]
== The Saints, (or they that are born of the Spirit,) their Heavenly and Spiritual worship, Unity, and Communion; and the Ministers of the Spirit in the New Testament, preached the word of Life, which was in the beginning, which they had heard, seen, and handled, and brought the Church of Christ to the same word: and they brought the Church of Christ to have fellowship with the Father and his Son.

[.heading-continuation-blurb]
And concerning the Supper, that Christ calls his brethren unto,
after that he was arisen, and ascended at the right hand of God. By G. F.

You that are believers in the light, which is the life in Christ, the word,
by which all things were made and created, and are become the children of the light,
and of Christ`'s day, and have received Christ,
and he hath given you power to become the sons and daughters of God;
and so are the children and heirs of his kingdom.
And have received the holy ghost, that proceedeth from the Father and the son,
which leads you into all truth, and out of evil and unbelief,
and from your own righteousness, to Christ`'s righteousness.
And are brought into communion of the holy ghost;
and this communion is above all communions, that stand in outward elementary things.
And these are the saints, and sanctified, and sons and daughters of God,
and the children of light, and of the day, of Christ`'s communion in the holy ghost;
and their fellowship and unity is in the spirit of God, by which they are led,
which is their spiritual bond of their heavenly peace, that is, a perfect peace,
which is the peace of God, that passeth all understanding that is outward.
And this peace cannot be broken,
neither can any one take this peace away from God`'s children,
and the sheep and the lambs of Christ; for Christ saith, '`My peace I give unto you,
not as the world giveth;`' for his peace is beyond, and above the world`'s; and Christ,
the second Adam, saith, '`In me you have peace, and in the world you have tribulation;
but be of good cheer, I have overcome the world,`' to wit,
in which God`'s children have tribulation; and in this,
Christ`'s sheep and lambs are to be of good cheer,`' that Christ hath overcome the world.

And Christ Jesus saith, '`Except a man be born again,`' of the spirit, or from above,
he cannot see the kingdom of God.`' Again, Christ saith,
'`Except a man be born again of water, and of the spirit,
he cannot enter into the kingdom of God; for that which is born of the flesh, is flesh;
and that which is born of the spirit, is spirit.`' And Christ said,
'`Marvel not that I say, you must be born again.`' John 3. to wit, of the spirit,
or from above.
And these are the true worshippers, that worship the Father in spirit, and in the truth,
and that are born of the spirit; for the Father seeks such to worship him.
And they do knew that God is a spirit; and they that do worship him,
must worship him in spirit and in truth; and these are they that are born again of water,
and of the spirit.
Here Christ makes a distinction between each birth, and saith,
'`That which is born of the flesh, is flesh; and that which is born of the spirit,
is spirit;`' and the spiritual birth lives in the spirit, and walks in the spirit,
and sows to the spirit, and shall of the spirit reap life everlasting.

And this new birth is the Jew which is one inward,
and the circumcision is that of the heart in the spirit, and not in the letter,
whose praise is not of men, but of God.
Christ Jesus is a minister of this circumcision, etc.
And the apostle said, '`We are the circumcision which worship God in the spirit,
and rejoice in Christ Jesus,
in whom also ye are circumcised with the circumcision made without hands,
in the putting off the body of the sins of the flesh,
by the circumcision of Christ.`' Col. 2. So this circumcision of Christ is spiritual,
that puts off the body of the sins of the flesh,
that came into man and woman by transgression;
and all must come into the circumcision of Christ by his spirit,
if they be the true worshippers of God, in his spirit and truth.

So here you may see, here is an inward spiritual circumcision, and a spiritual worship,
for the spiritual birth, which are living stones, built up a spiritual household,
a holy and a royal priesthood,
that offer up spiritual sacrifices acceptable to God by Jesus Christ,
which are come to Mount Zion, and to the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels;
and are come to the general assembly and church of the first born, which are written,
or which are enrolled in heaven; and are come to God the judge of all,
and to the spirits of just men made perfect.
These are they which are born of the spirit, or from above, that are written in heaven,
and come to heavenly Jerusalem, and see the kingdom of God, and enter into it,
that can neither be shaken, nor moved; and such serve God in newness of spirit,
and are come to the spirits of just men made perfect.

And the apostle saith to the church of Corinth, '`I verily, as absent in body,
but present in the spirit,`' etc. 1 Cor. 5:3.
And again the apostle saith to the Colossians, Col. 2:5.
Though I be absent in the flesh, yet I am with you in the spirit, joying,
and beholding your order, and the steadfastness of your faith in Christ.`'

Now this was, and is the true christians`' spiritual order,
that was discerned in the spirit; though they were absent in the flesh, or body,
one from another, yet they could behold their spiritual order, with the spirit of Christ;
and also, though they were absent in the flesh or body,
they could behold the steadfastness of their faith in Christ Jesus,
who was the author and finisher of the saints`' holy, divine, and precious faith;
which faith is the saints`' victory, called the faith of God`'s elect,
in which they have access to God, and do please him.
Now the saints do behold one another`'s steadfastness in this faith of Christ,
though they be absent in the flesh, or body, one from another;
yet in the spirit of faith, they behold one another`'s steadfastness in the divine, holy,
pure, precious faith in Christ Jesus.
And into this heavenly unity, both in the spirit and in the faith,
the apostle brought the saints to know one another, though they were absent in the flesh,
or in the body, yet present in the spirit,
joying and beholding the spiritual order that is amongst the saints,
and the steadfastness of their faith in Christ Jesus.
This is a heavenly beholding, and a heavenly joying, and a heavenly order,
and a spiritual and a heavenly sight, and society, and communion,
that can see and behold one another`'s steadfastness in the faith in Christ Jesus,
and do behold that heavenly and spiritual order amongst the saints;
though they be absent in the flesh, or body, one from another,
yet they are present in the spirit, and beholding the order of the spirit.
All that are in this heavenly and spiritual unity, fellowship, and society,
can say as the apostle said to the church,
'`By one spirit are we all baptized into one body, whether we be Jews or Gentiles,
whether we be bond or free, and have been made all to drink into one spirit.`' Namely,
all that are baptized by one spirit into one body.

So, though we are absent in the flesh, or body,
yet by one spirit we are all baptized into one body,
and so have all been made to drink into one spirit.

So here is a unity and a fellowship in the spirit;
and the saints know by what they are baptized into one body,
and into what spirit they do drink, though they be absent in the flesh, or outward body,
from one another.
And to this heavenly and spiritual fellowship and order,
the able ministers of the spirit brought the saints, the church of Christ,
to behold one another in the spiritual order, and the spiritual fellowship and communion,
and in that to joy and rejoice; and likewise,
to behold one another in their steadfastness, in the holy, divine, pure,
and precious faith in Christ Jesus; and though they were absent in the flesh,
or outward body, yet they were present in the spirit.
And therefore,
every one must come to their own measure of the spirit in their hearts and gift of faith,
which Christ is the author of, if they will come into this heavenly and spiritual sight,
and beholding the order of the saints,
and the steadfastness of their faith in Christ Jesus, though they be absent in the flesh,
or outward body, one from the other.

So every one must come to the grace, light, and truth, in their hearts,
that`'s come by Jesus, and the word of faith in their hearts,
if that they come to this heavenly and spiritual unity, and fellowship, and order,
that is amongst the saints in light; though they be absent in the flesh or body,
yet they are present in the spirit,
and the spirit brings them to the spirits of just men made perfect,
to have unity with them.
And the apostle saith, '`If any man have not the spirit of Christ,
he is none of his.`' And the apostle saith,
'`It was the spirit of Christ which was in the prophets,
which brought them to inquire and search diligently of the
grace that should come;`' and the spirit of Christ,
in the prophets, did testify beforehand of the sufferings of Christ,
and the glory that should follow;
and the spirits of the prophets were subject to the prophets;
and so they had a communion, and a spiritual sight, fellowship, and society,
one with another; though they were absent in the body,
yet they were present in the spirit of Christ.

And now all such that do say,
BECAUSE THE MEN AND WOMEN DO NOT MEET TOGETHER IN ONE PLACE IN A BODILY PRESENCE,
THAT THESE ARE IN A SEPARATION,
AND HAVE DECLARED AND PREACHED THEM UP TO BE IN A SEPARATION,
BECAUSE THEY DO NOT MEET OUTWARDLY ALTOGETHER, MEN AND WOMEN, IN A BODILY PRESENCE.
In this you have showed your ignorance, and numbness, and darkness,
and blindness to the spiritual sight,
and from being ministers of the spirit that the apostles were in; not seeing,
nor beholding, though they be absent in the body, or flesh, yet present in the spirit,
joying, and beholding the saints`' order,
and steadfastness of their faith in Christ Jesus our Lord.

And you, then, are not like to bring people to the spiritual order, nor spiritual joy,
nor the steadfastness of the saints in the divine, holy, precious faith in Christ Jesus,
who are so blind, you cannot see no more than the Pharisees:
though the saints are absent in the flesh, or body, one from another,
yet are present in the spirit.

Now, though all the world were present in a nation, if it would hold them,
and if they be, present in the outward body, or flesh, and have not the spirit of Christ,
which the apostles and the true church were in, they are none of Christ`'s,
but are in a separation from the spiritual joy, and spiritual order,
and divine faith in Christ Jesus.
And such cannot preach in truth every one to the grace, and truth, and spirit,
and the word of faith in their hearts, that say,
EXCEPT THE MEN AND WOMEN ARE TOGETHER IN AN OUTWARD BODILY PRESENCE,
THEY ARE IN A SEPARATION.
Such be out of the doctrine of the able ministers of the spirit, which said,
'`Though they be absent in the flesh, or body, yet they are present in the spirit,
joying and beholding their order,
and the steadfastness of faith in Christ Jesus`' And so, all are in a separation,
let them meet outwardly together, in a bodily presence, if they are not,
as I said before, in the spirit of Christ the apostles and the true church were in;
as the apostle saith, '`These be they that separate themselves, sensual,
having not the spirit, (to wit,) raging waves of the sea, foaming out their own shame.
They are gone into Cain`'s way,`' in envy,
'`and after the error of Balaam,`' from the spirit, and Korah`'s way of gainsaying;
'`clouds without water, trees without fruit, twice dead,
plucked up by the roots,`' so cannot grow; '`wandering stars,
to whom is reserved the blackness of darkness forever, which kept not their first state,
but left their habitation`' in the spirit.
These are the murmurers and complainers, and their mouths speak great swelling words, etc.
These be they who separate themselves, sensual, having not the spirit;
though they meet all together, men and women, in a bodily presence,
yet they are in a separation from the spirit of Christ,
the apostles and the church were in.
I say they are in a separation from the heavenly spiritual worship, and unity,
and communion, and order in the holy spirit,
and gospel the church of Christ were and are in.
You may know them by their fruits, their murmuring, and complaining,
and their mouths speaking high swelling word; and yet, wells without water of life,
and trees that have not spiritual fruit on them, and in Cain`'s envy and Balaam`'s error,
and Korah`'s gainsaying, self-willed, speaking evil of those things they know not,
and speaking evil of dignities or dominions, that is over such spirits, the power of God.
These be they which separate themselves, sensual, having not the spirit,
which troubled the church in the apostles`' days, and now who are known by their fruits;
and though they meet in a bodily presence together,
yet they are in a separation from God;
and though the faithful believers in Christ do meet, the women by themselves in one room,
in the spirit and name of Christ Jesus; and the men do meet in another room, in the name,
and spirit, and power of Jesus, to do those services that he commands them;
this is no separation, though they be absent in the flesh, or outward body,
one from another, yet they are present in the spirit, joying and beholding,
seeing their order in the spirit,
and the steadfastness of their divine faith in Christ Jesus the Lord from heaven,
who is the author and finisher of it.
And so every believer in Christ, and saint comes to their own,
and lives and walks in their own, as they did in the beginning,
when they were turned to the light.
But they that see not the spiritual order of the saints,
though they be not outwardly absent in the body one from another,
they are they that separate themselves, sensual, having not the spirit,
and are blind and do not see, like the Pharisees; and have ears, and do not hear,
and have hearts, and do not perceive.
Such are wells without water, and trees without fruit, that are gone into Cain`'s,
Korah`'s, and Balaam`'s way; though they have great swelling words of vanity,
yet they are gone from their own; to wit, erred from the spirit of God,
and so from the spiritual order, into the outward carnal order;
and so from the spiritual union, and communion, and fellowship, into their body, sight,
and fellowships, who are absent from the spirit, and separate from it,
and are present together in the body; and that is the thing that they so rage for,
like waves of the sea, foaming out their own shame,
and gainsay the saints`' order and practice; that is, though they be absent in the flesh,
or body outwardly, yet the saints are present in the spirit,
joying and beholding one another`'s heavenly and spiritual order,
(which are born of the spirit,) and the steadfastness of their holy faith in Christ,
the Holy One, the author and finisher of it;
and so are under Christ`'s peaceable government,
of the increase of which there is no end, and praise God in the spirit,
and to him sing hallelujah.
Amen.

As it is written, '`The first Adam was made a living soul, the last Adam, (to wit,
Christ,) was made a quickening spirit.`' Again, '`The first man is of the earth, earthly,
the second man is the Lord from heaven, (to wit,
Christ;) and as we have borne the image of the earthly,
we shall also bear the image of the heavenly, (to wit,
Christ,) who shall change our vile body,
that it may be fashioned like unto his glorious body, etc.
For as in the first Adam all died, even so in Christ, the second Adam,
shall all be made alive.`' Christ is a quickening spirit, and makes alive,
and changes the vile body like unto his glorious body;
so that the saints come to bear the heavenly image of Christ,
and know one another in Christ, that hath quickened them, and made them alive in him,
and know one another in his heavenly image.
And so, as all have borne the image of the earthly,
we must also bear the image of the heavenly; and as all are born in Adam,
they must be born again of the spirit, before they can see the kingdom of God,
or enter into it.
For Peter saith in his General Epistle to the church of Christ, '`Being born again,
not of corruptible seed, (so here is a seed that will corrupt,
and a seed that will not corrupt,) but of incorruptible seed by the word of God,
which lives and endures forever.`'

For all flesh is as grass, and all the glory of man, '`as the flower of the grass,
which withereth and fadeth away.`' And Christ saith, '`That which is born of the flesh,
is flesh; and that which is born of the spirit, is spirit.`' And Peter saith,
'`The word of the Lord endureth forever;`' by which
the saints were born of the incorruptible seed;
and those that were born again of the incorruptible seed, by the word of God,
desired the sincere milk of the word, that they might grow thereby.
Now, they which were and are born of the immortal seed,
fed and do feed upon the immortal milk of the word,
and by it grow up in the incorruptible seed; and these stand fast in one spirit,
with one mind, striving together for the faith of the gospel of Christ;
which is the practice of all the spiritual;
and so every one is kept to their own measure of the spirit of God.
And the apostle saith to the Philippians,
that '`every tongue shall confess that Jesus is the Christ,
to the glory of God the Father.
Wherefore, my beloved, as you have always obeyed, not in my presence only,
but much more in my absence, so work out your salvation with fear and trembling,
for it is God that works in you, both to will and to do of his good pleasure.`'

So here again you may see, every one is to keep your own measure of grace and truth,
and the spirit of God in you, to confess Christ Jesus;
and the spiritual could see with the spirit one another`'s spiritual obedience,
though absent, as well as present, (Philippians 2.) and in that was their spiritual joy.

And John saith, '`I baptize you indeed with water unto repentance,
but he that comes after me, (namely Christ,) who is mightier than I,
whose shoe-latchet I am not worthy to unloose;
he shall baptize you with the holy ghost and with fire: whose fan is in his hand,
and he will thoroughly purge his floor, and gather the wheat into his garner,
but he will burn up the chaff with unquenchable fire.`' Matt. 3:11-12. Luke 3:16.

Now all that are baptized with the baptism of Christ, with fire, and with the holy ghost,
they know their floor to be thoroughly purged,
and their chaff of sin and corruption burnt up with unquenchable fire,
and their wheat to be gathered into God`'s garner, by Christ their baptizer,
a safe place from the devil`'s devouring vermin;
and Christ that is this baptizer is mightier than John.
And so all you that know this baptism of Christ,
and that you are wheat gathered into God`'s garner,
that is a safe place from all the destroyers and devourers,
for no destroyer nor devourer can come into God`'s garner, to hurt his wheat,
nor no unclean thing can come into his everlasting kingdom, nor his holy city,
heavenly Jerusalem;
for all the unclean and abominable spoilers and devourers are without.
And therefore ye are happy who know the baptism of Christ,
and that he hath gathered God`'s seed, yea, his wheat, into his garner,
where no devourer nor destroyer can come,
though the Lord may suffer or permit the destroyer which is out of the truth,
to spoil your outward goods, for a trial to you, as he did Job;
but the Lord can make rich again with these outward things, for the earth is the Lord`'s,
and the fulness thereof, and he gives the increase.

John saith, '`In the beginning was the word, and the word was with God,
and the word was God, and all things were made by him, (to wit,
the word,) and without him was not anything made that was made, and in him was life,
(to wit, the word,) and the life was the light of men,
and that was the true light which enlightens every
man that comes into the world.`' John 1. And Christ,
who is the word, who was made flesh, saith, '`Believe in the light,
that ye may become the children of the light.`' John 12.

So there is no coming to be children of the light, but by believing in the light,
which is the life in Christ the word; and they that believe in the light,
are grafted into Christ Jesus the word, by which all things were made and created;
and all that walk in the light as he is in the light, have fellowship one with another,
and see one another to be children of the light and of the day of Christ;
and though they be absent in the body one from another,
yet they behold one another in the light, and they have fellowship in the light,
and are children of the day of Christ, as is said before.
So here everyone is kept to the witness; for he that believes in the light,
is become a child of the light, and hath the witness in himself,
and is sealed with the spirit of the promise of this life, and that which is to come;
and so are kept to their own witness and seal in which they have unity and fellowship.

And John saith, '`That which Was from the beginning, which we have heard,
which we have seen with our eyes, which we have looked upon,
and our hands have handled of the word of life, for the life was manifest,
and we have seen it, and hear witness, and show it unto you, (to wit,
the church,) that eternal life which was with the Father, and was manifest to us;
that which we have seen and heard, we declare unto you,
that ye also may have fellowship with us; and truly our fellowship is with the Father,
and with his son Jesus Christ.`'

Here you may see what was the fellowship that John brought the church of Christ into,
namely, into the fellowship with the Father and his son Jesus Christ,
that he himself and others were in, and this was a spiritual, heavenly fellowship;
and though they were absent in the body one from another,
yet they were present in the spirit.
Here every one keeps to their own testimony of Jesus, and record,
which record is eternal life, and this life is in his son.

And the apostle declared the word of life, which was in the beginning,
which they had heard, and seen, and handled; this word of life, they bore witness unto,
by which all things were made and created; and so the apostle brought the saints to hear,
to see, and to handle the word of God, which was in the beginning.
So that they were to look over all the ways, and religions, and worships,
and doctrines of men, which have been set up since the beginning,
and not to cumber themselves by hearing, and looking upon,
and handling the doctrines and commandments of men, and the worships, and religions,
and the rudiments, and elements, and inventions of the world,
and the fellowships which have been set up since the beginning,
where all the confusion is.
And they which will have fellowship with the Father and the son,
must see with their eyes, and handle with their hands, and hear with their ears,
and bear witness to the word of life, which was in the beginning,
if that they have fellowship with the Father, and with his son Jesus Christ;
which fellowship is above all the fellowships since the beginning,
set up and invented by man; yea,
it is above the Jews`' fellowships in their outward elementary things,
which have been set up since the beginning,
which did serve in the old testament until Christ the seed did come;
but now in the new testament,
the true christians`' fellowship is with the Father and with the son,
by whom all things were made and created;
and all fellowships below this will come to nothing.
And '`He that hath the son, he hath life; and he that hath not the son of God,
hath not life.`' 1 John 5:12. Therefore, let all that profess themselves christians,
examine your own selves, whether you be in the holy, pure,
divine faith that Jesus Christ is the author and finisher of.

And '`prove your own selves, how that Jesus Christ is in you,
except you be reprobates.`' 2 Cor. 13:5. Is not a reprobate,
a mind void of judgment and the knowledge of life eternal?
And such reprobates that Christ is not in, they cannot meet in his name.

And Christ said to the church of Laodicea, '`Behold I stand at the door and knock,
if any man will hear my voice, and will open the door, I will come into him,
and sup with him, and he with me;`' and this was the supper that Christ preached to John,
and to the church, after he was ascended:
for John had taken the supper of the elements of bread and
wine in the same night that Christ was betrayed,
before Christ was crucified; but now John writes to the church,
and tells them of another supper, the marriage supper of the lamb, which is a nearer,
and a more inward supper,
than taking the elements of bread and wine in remembrance of Christ`'s death,
which Christ gave to his disciples before he was crucified, and said,
'`As often as ye eat this bread, and drink this cup, do it in remembrance of me,
and to show forth his death until he come.`' But after Christ was risen, and ascended,
he saith, '`Behold, I stand at the door and knock, if any man will hear my voice,
and open the door,`' to wit, of his heart, mind, and soul, (by joining to the light,
grace, and truth of Jesus,) I will come in to him, and sup with him,
and he with me;`' and is not this the marriage supper of the lamb?
And is not this supper beyond, and a further supper,
than taking the elements of bread and wine in remembrance of his death, to wit,
to sup with Christ in his resurrection and ascension?
He with them, to wit, in their hearts, and they with him?
And they hear his voice, and so Christ is in them, then they are no reprobates.
And he that hath the son of God hath life;
for may not reprobates take bread and wine in remembrance of Christ`'s death,
and not hear his voice after his resurrection and ascension?
And can any that do not hear the voice of Christ,
nor open the door of their hearts to let Christ in, sup with him, and he with them,
at the heavenly marriage supper of the lamb,
which is the last supper that Christ calls people to after his resurrection and ascension?
Which blessed are they that come to the marriage supper of the lamb, and sup with him,
and he with them.

Christ, the seed of the woman, is come and manifest in the male and female,
who bruises the serpent`'s head; and if the serpent doth put out his head,
who is the seed of enmity and strife, and puffs up the high and conceited mind,
with his jingling and sounding brass, and tinkling cymbals; but the seed of the woman,
which is manifest in the male and female, will bruise his head,
and into the pit and lake he must go, from whence he came, with all his followers.
And I say again, to your own grace and truth, and the spirit and gospel of Christ,
and the light, which is the life in Christ the word, that with this heavenly light,
you all, males and females, may see your service for God and Christ,
that you are to do and act for his glory,
both in your men`'s and women`'s meetings and families, and other ways.

And therefore every one to your own, to your own, I say, the seed Christ in all,
males and females; which is the heir of the promise,
which is in this life and that which is to come; for the serpent set first on the woman,
the weaker vessel;
but now the seed of the woman is come into the females as well as in the males,
that bruises the head of the serpent, and that makes the serpent so to rage,
that Christ should be in the females as well as the males, to bruise his head,
that he cannot set upon the weaker vessels, as he did upon Eve,
and that now the women should have a meeting in Christ, and in his name,
and through Christ, they should be too hard in and through Christ,
for the serpent to bruise his head, and tread him under their feet through Christ;
and he should be their redeemer, saviour, sanctifier, justifier, and their righteousness,
and wisdom, and mediator,
and so that they should be married to Christ that takes away their sin,
and that Christ should be a faithful and true witness
in the female as well as in the male.
Oh! this is that which hath made the serpent, the old dragon, in his instruments,
to rage against Christ the faithful witness in the females,
because that he cannot deceive them as he did Eve; but he that is in the female,
bruises the serpent`'s head, Christ the faithful and true witness.
So in Christ, male and female all are one; I say,
in Christ the faithful and true witness, and they are true witnesses of God and Christ,
and of what he hath commanded them, in his spirit, power, and wisdom,
to do and act to his glory.
And so the females in Christ are to be teachers of good things,
and labourers in the gospel, and servants in and to the church, as Phoebe was.

The serpent cries nowadays,
'`to your own;`' but what is that but to deceive and to lead out to his own,
and from the seed of the woman that bruises the serpent`'s head,
and is manifest in the males and females, in which seed the females do meet,
and have their meetings, as well as the males;
and therefore the serpent or old dragon is so wroth against Christ the seed of the woman,
in the males and females, and his peaceable government,
of the increase whereof there is no end.
And the serpent casts forth his floods of lies, and calumnies,
and reproaches against the seed of the woman, and they that do possess it;
but the promise was,
'`The seed of the woman should bruise the serpent`'s head,`' for he is out of the truth,
who is the head of all wickedness, and who gives his power to the beast:
so the raging beast and the foul spirit mixeth together
against the lamb or seed of the woman,
and crieth '`to your own,`' to draw people from Christ, who is formed in them,
and to bring them to fall under the dragon, and the beast,
and the whore of Babylon`'s power; but the lamb who is manifest in his males and females,
will have the victory over the whore, beast, and the old serpent the dragon,
and will overcome them.
And in the lamb or seed of the woman, the females do meet as well as the males,
and they are all one in him; though they are absent in the body,
yet they are present in Christ, their own head and husband, salvation, and life eternal;
and all such cry, '`We are come to our own husband, and to our own city,
heavenly Jerusalem, our one mother of us all, that are born again of the spirit,
or from above.`' So we are come to our own, and do line of our own,
from our own mother and husband, and do know our own husband, mother, and city,
and do know our own work and service in the spirit, power, and wisdom of God and Christ,
that God and Christ doth command us,
that we might serve God and Christ in his new creation, and holy generation,
and so to serge him with all that we have; and if the serpent do put forth his head,
and spit forth his venom at this, Christ, the seed of the woman, will bruise his head.

And we are come to hear our own prophet, which God hath raised up, Christ Jesus,
to open to us; and him we do hear in all things in our meetings.
And-we are come to our own shepherd and bishop to hear his voice, who doth feed us,
and oversee us in his pasture of life,
and none is able to pluck us out of his holy hands.
And we are come to our own minister, teacher, and circumciser, and baptizer,
Christ Jesus, who gathers his wheat into his garner.

And we are come to our own captain of our salvation, the conqueror,
that bruises the serpent`'s head, and destroys the devil and his works, `who,
through death, destroyed death and the devil, the power of death.
So we are come to our own sanctuary Christ Jesus, which God hath pitched, and not man,
which sanctuary is a safe place, in whom we have all peace, life, and salvation.
And also we are come to our own beloved Christ Jesus, who is our way, truth, and life.

And also we are come to our own word of faith, and of power, wisdom,
and of patience in our own hearts, which the apostle preached to the church in his day,
by which word we are born again, not of corruptible seed, but of incorruptible,
and do feed upon the sincere milk of the word, and grow by it, which milk is our own.

And also we are come to our own anointing or unction,
which we have received from the Holy One, which teacheth us,
etc. and by which unction we know all things to our salvation and life eternal,
and do know our duty, and service, and worship to God and Christ,
and also our services and places in the church of Christ.

And also we have received the comforter, the spirit of truth,
which spirit proceeds from the Father and the son,
which is our own leader and guider into all truth,
which gives us an understanding how to behave ourselves,
and walk towards God and man in the truth; in which holy ghost is our communion,
as it was the church of Christ`'s in the apostles`' days.

And likewise we have received the glorious gospel of salvation,
which hath brought life and immortality to light,
by which we see over the devil and the power of darkness, who abode not in the truth,
who had darkened us from life and immortality,
but now it is brought to light by the gospel, the power of God,
and so are become heirs of the glorious gospel.
So we are come to our own inheritance,
and have a glorious fellowship in his comfortable gospel of peace, and in it we do all,
males and females, see our services in the church of God,
in our own heavenly sight and light.

And also we are the believers in the light, which is the life in Christ the word;
so are become children of the light and of the day,
and so we do know our duty and services in the day of Christ,
so that we are not only come to our own, but we walk in our own day and light,
as it was in the beginning;
and God hath given Christ to us to be our counsellor and commander,
who hath quickened us, and made us alive; who counsels us,
and commands us with his heavenly counsel and wisdom; who is the heavenly spiritual man,
whose heavenly counsel and commands are precious to us,
which is beyond all natural men`'s; and so he doth counsel us who hath made us alive,
how to walk among the saints in light, and in our services in the church of God.
So that we are come to our own heavenly counsellor Christ Jesus,
who bruises the serpent`'s head, so we need none of his counsel, nor his followers;
Christ is sufficient, who is first and last, the beginning and ending; who was, and is,
and is to come, in whom all nations are blessed, and have their joy, peace,
and happiness in the Lord.
Amen.

'`The nations of them that are saved shall walk in the light of the holy city,
and the glory of God doth enlighten it,
and the lamb is the light thereof.`' Rev. 21:22-23.

Geo. Fox.

Kingston, the 9th of the 9th Month, 1684.
