[#ch17.style-blurb, short="To Such as Wander from the Anointing"]
== A word of admonition to such as wander from the anointing and teaching within, and from the Father and the son.

[.heading-continuation-blurb]
As also concerning the supper of the Lord, before he was crucified;
and his marriage supper after he was risen and ascended.
And who are they that declare the generation of Christ,
distinct from the generation of natural Adam;
and the reason why all become not the sons and daughters of God that are called Christians;
with many other precious instructions.

[.heading-continuation-blurb]
Showing also how the Jews and Christians wander from the commands of God,
and communion with him.

[.heading-continuation-blurb]
Likewise God`'s promise to Cain, if he did well,
he should be accepted.

[.heading-continuation-blurb]
Lastly, the true Christian`'s righteousness,
which must exceed the righteousness of the Scribes and Pharisees.
By G. F.

The apostle John saith in his first General Epistle to the church of Christ,
'`The anointing which ye have received from the Holy One which is in you,
and as this anointing abideth in you, and you in it, ye shall continue in the Father,
and in the son, and you need not any man to teach you,
but as the same anointing doth teach you.`' And all
that are gone from this anointing`'s teaching,
which comes from the Holy One,
by which they should continue in the Father and in the son,
they are gone and wandered from the Father and the son,
that are gone and wandered from the anointing`'s teachings within.
They wander after the world`'s teachers, and their sects and seducers,
and '`so are carried about with every windy doctrine,`' and so are unstable, unsettled,
for they that are gone and wandered from the anointing`'s teachings within,
they are wandered from Christ the true rock and foundation;
and also are wandered from the Father and son,
the apostles brought the church of Christ to in their days; for the anointing within,
which they have received from the Holy One, by which they need no man to teach them,
but as it teacheth them, and as it doth teach them,
they shall continue in the Father and the son, and by it know all things,
and be built upon the living rock and foundation.
So such are a stablished people, and abide in the doctrine of Christ and the apostles,
and do God`'s will, and know Christ`'s doctrine.

And all that abide in Christ the vine, they are the new bottles, and have the new wine,
but all that abide not in Christ, and he in them, are reprobates,
though they may profess all the scriptures that speak of Christ;
they are the old bottles, and old creatures, that hold the old wine,
and cannot drink the new wine of grace and truth, righteousness and holiness,
for that breaks the old bottles of old Adam in transgression.
And such cannot bring forth righteous and holy fruit,
that do not continue in Christ the righteous and Holy One;
but all that abide in Christ their vine and fig-tree,
they shall not want heavenly wine and figs,
and so such do bring forth righteous holy fruit;
yea every branch that abides in Christ the vine;
and they that abide not in Christ the vine, they abide not in him the head;
such wander from the head, and such wander from the spirit of Christ,
and are none of his.

Now consider, grace and truth came by Jesus Christ, and this grace of God,
which brings salvation, hath appeared unto all men; which grace taught the christians,
in the apostles`' days, and brought their salvation; by which grace they were saved.

Now all they that are wandered from the teaching of this grace of God,
they are wandered from that which should bring their salvation and save them;
so they are not like to be under grace, nor under the election of grace,
as the church was in the apostles`' days.
And all they that are wandered, or erred from the spirit of God within,
and truth in their inward parts, they are not like to worship God in spirit and truth;
and though they may make a profession of all the scriptures,
yet they are not like to know them, which were given forth from the spirit of God,
nor like to know the things of God, or the scriptures of truth,
without the spirit of God, that was in the holy men of God,
that moved them to speak them forth.

And all they that are wandered and gone from the law that God writes in their hearts,
and puts in their minds, (by which they all should know the Lord,
from the greatest to the least,) they are teaching their neighbours, saying,
'`Know ye the Lord,`' and have tithes and maintenance, for teaching people,
and have got a law to force it from them, yea, from such as they do not teach;
though Christ saith, '`Freely ye have received,
freely give,`' and '`No man knows the Father but the son,`' etc.
and the son and the Father are known by the revelation of his spirit,
But such as deny the law of the spirit of life written in their hearts,
and put in their minds, deny the revelation of the spirit,
and that by which they should know the Lord,
and God`'s teaching his people in the new covenant.

And you that are wandered from the light, which is the life in Christ,
who '`enlighteneth every man that comes into the world;`' you are
wandered from that which Christ commanded you to believe in,
and to become children of THE LIGHT, in which ye should have life everlasting,
and come out of condemnation;
and you that wander from the light that shines in your hearts,
which should give you the knowledge of the glory of God in the face of Christ Jesus,
you do perish for lack of knowledge,
and call that light (which should give you that knowledge) natural,
who wander from that which should give you the knowledge of God and Christ.

They go into spiritual captivity, Babylon, Sodom, and Egypt,
who go from the spirit and law of God, that he writeth in their hearts,
and the gospel the power of God,
and the grace and truth that cometh by Jesus Christ the light,
and anointing that they have from the Holy One;
and then they are unfaithful to God and man;
and he that is unfaithful in the outward things,
who will trust him with the true and everlasting treasure?

And the gospel of salvation being preached to every creature under heaven,
which gospel is the power of God to salvation,
to every one that believes,`' doth establish men;
but all they that have wandered from the gospel,
they have wandered from the power of God, which should save them,
and that in which they should be established,
and should bring life and immortality to light in them; and such remain in darkness,
and do not know whither they go or wander.
And the Lord poureth out of his spirit upon all flesh, both men and women,
that with his spirit they might all know God and Christ, and the things of God,
and to be led by the spirit of God, that they may be his sons and daughters;
but all you that err and rebel and wander from the spirit of God in your hearts,
you know not Christ nor God, nor the things of God;
you are not the sons and daughters of God,
and you are out of the fellowship and circumcision and baptism in the spirit of God,
neither can you worship the God of truth, but in his spirit and truth.

The preaching of Christ in his promises, and in the prophecies of him,
and in the figures, and shadows, and types of him that was to come;
and in his miracles and sufferings after he is come; and his death, and resurrection,
and ascension, at the right hand of God,
and after to preach him in man or woman that believes in him;
and Christ to reign in their hearts, except they be reprobates;
and this was the apostles and the saints`' doctrine in their days.
And the apostle did prove that Jesus was Christ, by Moses and the prophets;
and when he had proved this to the Jews, that had Moses, and the prophets,
and the promises, that prophesied of Christ; and when that Christ was come,
according to the promises, and according to Moses and the prophets,
and proved and manifested himself to be the Christ by signs and miracles,
and then after the Jews had crucified him, and he died, and was buried, and rose again,
and ascended, is set at the right hand of God,
(according to the scripture,) and when many believed in Christ Jesus,
then the apostles bid them '`prove themselves whether they were in the true faith,
(to wit, that true faith which Jesus Christ was the author and finisher of,) and try,
and prove, and know themselves how that Jesus Christ was in them,
except they were reprobates.`' So here the first proof was,
to prove by the scriptures of Moses and the prophets, and the promises, and the figures,
types, and shadows, that Jesus was the Christ, and the substance of them,
both to the Jews, and the world.

And the second proof was, that when christianity was spread abroad,
and many did believe in Christ Jesus, the apostle bids the Christians '`try themselves,
and prove and know themselves, if that Christ Jesus was not in them,
they were reprobates;`' and he that had not the spirit of God, he had not life,
and he that had not the spirit of Christ, he was none of his,
and none can call Jesus Lord but by the holy ghost.
So all the true christians must have the same holy
ghost and Christ in them that the apostles had,
if they truly call Jesus Lord and master, and are his,
for the wicked Jews and Judas could call Jesus Lord or master,
but it was by the unclean ghost.

And the apostle John, in his General Epistle, bids the Church '`Believe not every spirit,
but try the spirits whether they are of God;`' he doth not
bid them only try their words but their spirits,
because '`many false prophets are gone into the world,
hereby know ye the spirit of God from the spirit of error,
every spirit that confesseth that Jesus Christ is come in the flesh, is of God,
and every spirit that confesseth not that Jesus Christ is come in the flesh,
is not of God.
And we know the son of God is come, and hath given us an understanding,
whereby we may know him that is true, and we are in him that is true,
even in his son Jesus Christ.`' So these confessed Christ come according to the promise,
and the prophecies; and his death, and resurrection, and ascension,
and his coming in them, and they to be in him who were no reprobates.
And these with the unction which they had from the Holy One, which did abide in them,
by which they continued in the Father and the son, can know all things,
and with this unction they can try spirits, yea,
the spirits of seducers and false prophets;
and they could try such as got a form of godliness, but denied the power thereof,
which were to be turned away from; and they could try such as were in a false liberty,
such as Paul and Peter spoke of, that were out of Christ Jesus;
and also they could try such who with feigned words
and fair speeches deceived the hearts of the simple,
who served not the Lord Jesus Christ, but their own bellies;
and also they can try such as go in Korah`'s, Cain`'s and Balaam`'s way,
and are to try such that went in Jannes`' and Jambres`' way, resisting the truth;
and could try the wells, and the clouds, and the trees, whether they had either water,
rain, or fruit.
So the apostle saith to the true christians that have the anointing in them,
try the spirits whether they are of God;
and he doth not bid the christians in the apostles`' days, try their words only,
for many had gotten the good words and fair speeches to deceive the simple withal,
and a form of godliness, but denied the power thereof,
but they were to try their spirits whether they were of God,
for the unity and fellowship and true worship is in the spirit of God;
for all the true christians are all baptized into one body with one spirit,
and are made all to drink into one spirit.
And the things of God knows no man, but the spirit of God;
and the things of God are not to he spoken in the words which man`'s wisdom teaches;
but in the words that the holy ghost teaches, etc.
So this unction or anointing within, can try when men do speak the things of God,
in the words that man`'s wisdom hath taught them,
and not in the words that the holy ghost teaches.

And the taking the bread and wine in remembrance of Christ`'s death until he came,
which he gave to his disciples after supper at the passover,
which he gave before he was crucified, when Christ promised his disciples,
'`I will not leave you comfortless, I will come to you.`' John 14:18-5. And John said,
'`the son of God was come, and they were in him,
and he that hath the son of God hath life,
and he that hath not the son of God hath not life.`'

And the apostle Paul tells the Corinthians,
after he had baptized some of them with water, and had given them the cup and the bread,
if that Jesus Christ was not in them they were reprobates;
though they had all these outward elementary things; and therefore, as I said before,
taking the elementary bread and wine in remembrance of Christ`'s death until he came;
and when he is come, must he stand knocking at the door of your hearts,
and call unto you, and you not hear his voice,
that he might come into your hearts and souls, that he might '`sup with you,
and you with him,`' at the heavenly marriage supper of the lamb;
which is a nearer supper than to take the elements
of bread and wine in remembrance of Christ`'s death.
And if Christ is not within you, you are reprobates,
for Christ took the bread and wine and gave it to his disciples, when he was with them,
before he was crucified; but now he is risen and ascended,
and stands at the doors of your hearts and knocks;
and if any man will hear his voice and open to him with his grace, and light, and spirit,
by joining to it, Christ tells you in Rev. 3. that he will come in and sup with you,
and you with him; and here Christ sups in you, and you with him,
which is the last supper spoken of in the Revelations;
and this is the spiritual and heavenly marriage supper.
And here Christ`'s words are fulfilled, who said he would come again,
and doth not leave his followers comfortless.
And John, that took the elements of bread and wine in remembrance of Christ`'s death,
at the passover, before he was crucified,
he preaches to the christians in the Revelations,
and brings them to the marriage supper of the lamb,
for it is like they had taken the bread and the cup
in remembrance of Christ`'s death until he came;
but now John tells them that Christ is come,
and stands at the door of their hearts and knocks, and saith,
'`If any man will hear his voice and open to him, he will come into him,
and sup with him, and he with Christ,`' which is a nearer supper,
than to take the elements of bread and wine in remembrance
of Christ`'s death until he came,
who is now come, and knocks at the doors of your hearts.
I say, the marriage supper of the lamb is a nearer supper,
to hear Christ`'s voice after he is risen and ascended, and to let him into their hearts,
and he to sup with them, and they with him, that is within them;
for the element of bread and wine which they took
in remembrance of Christ`'s death before he was crucified,
risen, and ascended, that was without them, an outward thing;
so examine yourselves whether you hear Christ`'s voice, and let him into you,
and he to sup with you, and you with him, a heavenly marriage supper of the lamb;
and if Christ be not within you, though you have had elements of bread, and wine,
and water, but if he stands at the door and knocks, and you will not hear his voice,
and let him in, the apostle tells you, '`You are reprobates.`' 2 Cor.
xiii.
and you that have not he son of God, have not life.
1 John 5. xii.

Who shall declare the generation of Christ the second Adam, revealed from heaven,
for his life was taken from the earth, Isa. 53:8. and he shall see his seed,
but who shall declare his heavenly and spiritual generation, who saith,
'`I am from above, and ye are from below; and I am not of this world,
ye are of this world.`' Now who shall declare his generation that is from above,
and is not of this world.
Thus Christ saw his seed that he had sown in his prophets, and saints,
or sanctified ones, and his elected.

Now the generation of Adam, who are of this world, the natural sons of Adam,
may declare their generation, which cannot declare the seed and generation of Christ,
who is from above, and not of this world; they must be born again,
and born of the spirit, and of the immortal and incorruptible seed, by the word of God,
and who have received Christ, and he hath given them power to become the sons of God,
that know and see Christ`'s heavenly seed, and declare his generation,
and see his seed and generation,
that entereth into his everlasting kingdom that hath no end,
and into his heavenly Jerusalem, and that is from above, where no unclean thing entereth,
and know his heavenly voice, which is distinct from all the natural voices;
who feedeth them with his heavenly milk, wine, bread, and water,
which nourishes them up unto eternal life in his everlasting kingdom,
and heavenly Jerusalem; who are clothed with the fine linen, the righteousness of Christ.
Hallelujah.

And '`God, who doth inhabit eternity,
dwells with the humble in heart;`' and therefore all your hearts must be humble,
if God that doth inhabit eternity dwell in you;
for '`God doth behold the proud afar off,`' whether they be proud in heart,
or in apparel, or in riches, or have a profession like the Jews and Pharisees.
I say, in a profession of the old testament,
without the possession of that holy spirit and holy ghost,
that those humble hearts were in that gave them forth.
So '`God beholds the proud afar off,`' for they are far off from God,
Ps. 138:6. though the Lord be nigh, and hath respect to the lowly,
and '`God resisteth the proud, and gives grace to the humble.`'

And David said, '`Thou hast trodden down all them that err from thy statutes,
and salvation is far from the wicked,
for they seek not thy statutes.`' And the Lord said to the Jews. Ezekiel 5:6.
'`They have changed my judgments into wickedness more than any nation,
and my statutes more than any countries round about her;`' to wit,
the church of the Jews; for they have refused my judgments, and my statutes,
they have not walked in them;
and let the greatest part of Christendom apply this to themselves.
And unto the wicked saith God, '`What hast thou to do to declare my statutes,
or that thou shouldst take my covenant in thy mouth; seeing thou hatest instruction,
and castest my words behind thy back?
When thou sawest a thief, thou consentest with him,
and hast been partaker with the adulterers.
Thou gavest thy mouth to evil, and thy tongue frameth deceit.
Thou sittest and speakest against thy brother,
thou slanderest thy own mother`'s son;`' such are not fit to declare God`'s statutes,
to take his old and new covenant in their mouths, as in Ps. 1.

Therefore all must be reformed in their words, lives, and conversations,
if they take God and Christ`'s commands and statues, or covenant in their mouths;
for the holy scriptures of truth were given forth by the holy ghost,
as it moved the holy men to speak them.
So not wicked men, that were led by an unclean spirit, or an unholy ghost;
for such are not fit to declare God`'s statutes, or the holy scriptures of truth.
For, as it is said, the Lord spoke by the mouth of his holy prophets.
And Christ saith, it is the spirit of the Father that should speak in the apostles;
so they were reformed holy men in word, life, and conversation by the holy spirit,
which made them holy that gave forth the holy scriptures of truth.
But the unreformed, wicked, unholy, ungodly in their lives, words, and conversations,
what have they to do to take and declare with their wicked mouth`'s,
God`'s and Christ`'s statutes and commandments, and to make a trade of them,
or otherwise, seeing that they are forbidden of God in his holy scriptures of truth?
And Christ saith, '`Depart from me all ye workers of iniquity.`' Though they may boast,
and say, we have preached in thy name, and preached in the streets.
And these went under the name of christians then,
or else they would not have preached Christ; and those had the sheep`'s clothing,
who were inwardly ravened from the spirit of Christ; they appeared as christians,
and them that went in Korah`'s, and Cain`'s, and Balaam`'s way,
and got into a form of godliness, but denied the power thereof.
These appeared like christians; and were not the Nicolaitans, and Jezabel,
that was a teacher, a kind of christians, spoken of in Revelations ii?
and all such that professed a false liberty, spoken against by Paul, and Peter,
a kind of christians?
And therefore Christ saith, '`Depart,`' to such as said they had prophesied,
or preached in his name; or, '`Depart from me all ye workers of iniquity,
I know you not.`' So Christ doth not give workers of iniquity a commission,
or license to preach him, or his gospel.
For Christ bids the workers of iniquity depart from him,`' and saith,
he knows them not.`' Matt. 7:23.

And Christ saith, '`It is not every one that saith Lord, Lord,
shall enter into the kingdom of God,
but he that doth the will of my Father which is in heaven.`' So
they must do his will if they enter into the kingdom of God,
etc. which will is their sanctification: not only say they do his will;
for many shall say, '`Lord, Lord, we have prophesied in thy name,
etc. and in thy name have done many miracles; we have eaten and drunken in thy presence,
and thou hast taught in our streets;`' but Christ saith, '`I will profess unto them,
and will tell them, I never knew you whence you are.
Depart from me all ye workers of iniquity.^
footnote:[Luke 13:27]
And were not these teachers, or preachers, a kind of Christians, that Christ bids,
'`Depart from me all ye workers of iniquity.`' Matt. 7. Luke 13. And
therefore what had these to do to take the name of Christ in their mouths,
and were not reformed from iniquity?

And the apostle saith, who keeps in the same doctrine of Christ, and of the prophet;
who saith,
'`Let every one that names the name of Jesus Christ depart from iniquity.`' 2 Tim. 2:19.
For iniquity separates from God and Christ,
who was bruised for our iniquities.
'`And therefore, every one that names the name of Jesus, (mark,
every one,) let them depart from iniquity,`' for it is the command of the apostles;
therefore he would have them to be reformed from iniquity that names the name of Christ,
and preaches him.
And they are likewise reproved by the prophets, for taking God`'s laws, or statutes,
or commands in their mouths, that be wicked; and Christ saith,
'`Depart from me ye workers of iniquity,
I know you not.`' So it was not like for Christ to give the wicked, and ungodly,
and the unrighteous, and workers of iniquity license,
or a commission to preach him who is holy, and his glorious gospel.
And the apostle saith, '`Every one that names the name of Christ,
let him depart from iniquity.`' Here the prophet, Christ,
and the apostle are against the wicked preachers,
or namers of the name of God and Christ.
And the apostle again saith, '`None can call Jesus Lord,
but by the holy ghost;`' for all such as call Jesus Lord or master,
without the holy ghost that the apostles were in, are but like the Jews,
who resisted the holy ghost; and Judas`'s kiss, who said '`Hail,
master,`' and betrayed him to the Jews, tithe-mongers, and priests,
who made profession of the scriptures of the old testament, and resisted the holy ghost,
that led the holy men of God to speak forth the scriptures,
by which they should have called Jesus Lord, as David did in spirit.

Now to read all the saints and the holy men of God`'s words, and their travels,
and experiences, and sufferings, and to walk out of the saints holy spirit, way, path,
and life, such have not the comfort of Christ and the holy men of God`'s word,
the holy scriptures of truth, being led by the unclean ghost into confusion,
out of all truth; but they that are led by the holy ghost,
that proceeds from the Father and the son, have the comfort of the holy ghost,
and the comfort of the scripture, that was given forth by the holy ghost,
and this comforter, this spirit of truth, that proceeds from the Father and the son.
Christ saith, '`He shall testify of me.`' And again, Christ saith,
'`He shall glorify me,`' to wit, the spirit of truth, the comforter,
he shall receive of mine, and show it unto you:
he shall lead and guide you into all truth, when he is come.
And did not Christ speak these words to his followers before he was crucified?
And were not Christ`'s words fulfilled, when the holy ghost fell upon the believers,
in Acts 2.? Which led and guided the believers then, and now, into all truth.
And is not this holy ghost now reproving the world of sin and unbelief,
because they believe not in the light, the life in Christ, as he commands?
And is not this holy ghost now reproving the world of their righteousness,
that will not be guided by the holy ghost to Christ and his righteousness?
And is not this holy ghost reproving the world for their judgment,
which is not from the holy ghost, but from the unclean ghost,
and by the judgment of that unclean ghost, it is said, that the prophets were fools,
and the spiritual men were mad?
And that John had a devil, and that Christ by the prince of devils, did cast out devils,
and that Christ was a deceiver, and a blasphemer, and that the apostles were deceivers,
and Paul was a babbler, and a pestilent fellow.
This was, and is the judgment of many great professors of the scriptures,
with their unclean ghost, who neither have the comfort of the scriptures,
nor the holy ghost, but are reproved by it.

But as many as receive Christ in his light, life, grace, and truth, that comes from him,
to them he gives power to become the sons of God, and then God is your Father,
and you are led by his spirit; and this is the noblest birth in all the world,
above all the natural, or mortal births in the world; for this birth is heir of heaven,
and heavenly Jerusalem, its mother; and it is heir of an everlasting kingdom,
that will never have an end,
which will stand when all the kingdoms in the world will have an end;
for God`'s kingdom stands in his power, righteousness, and peace,
and joy in the holy ghost.
And the apostle said, '`He that believes, is born of God, and he that is born of God,
overcomes the world.`' And again, '`What manner of love is this,
that we should be called the sons of God?`' And Peter saith, '`Being born again,
not of corruptible seed, but of incorruptible, by the word of God,
which lives and abides and endures forever.`' And the apostle saith,
'`They that are led by the spirit of God,
are the sons of God;`' then God is their Father, who is greater and mightier,
and more powerful than all, and richer than all; for all that is in the earth,
and all that is in heaven is the Lord God`'s, your heavenly Father`'s;
who is God in heaven, and God in the earth,
who can enrich thee with riches and blessings above, and riches and blessings below;
who dwells with all his sons and daughters that have received Christ,
and are led by the spirit of God their Father; so they can say,
he that inhabits eternity, dwells with the humble, meek, and lowly-hearted children.

Now what is the matter that all people in the world, that profess God,
are not the sons of God?
The reason Christ and the apostle tells you, because that they do not receive Christ,
and are not led by the spirit of God, but rebel against it, and are led by the devil,
the spirit of that wicked one; and so become his children,
and his works and commands they will do, and not the living God`'s, that made them,
to serve and worship him in spirit, and God is angry with them every day;
and therefore the judgments of God`'s spirit stands over the head of such,
who will not believe in Christ, and follow him, who bruises the serpent`'s head,
that you might have life and salvation in Christ.

[.asterism]
'''

[.blurb]
=== Concerning God`'s God`'s promise to Cain, and how by disobedience he fell short of it.

And the Lord said to Cain, '`If thou dost well, shalt thou not be accepted?
and if not, sin lies at thy door.`' Here was the promise of God to Cain,
but Cain disobeyed God, and did not well;
for he persecuted and killed his brother Abel about religion and worship;
and therefore God pronounced, that he should he a fugitive, and a vagabond in the earth.
Though Cain built a city, and Ishmael the son of Hager, who was born after the flesh,
who mocked Isaac, who was born after the spirit or promise,
as in Gal. 4. God commanded Abraham to turn Hager and Ishmael
out of his family! and they wandered in the wilderness,
a place for persecutors, though Ishmael became a great man afterwards in the earth.
Gen. 21.

And the Lord said, '`Because of these men, (to wit, the Jews,) which have seen my glory,
and my miracles which I did in Egypt, and in the wilderness,
and have tempted me now these ten times, and have not '`hearkened unto my voice,
surely they shall not see the land, (to wit, Canaan,) which I swore unto their Fathers,
neither shall any of them which provoked me see it,`' save Caleb and Joshua,
which were of another spirit, and followed the Lord fully.
And the Lord`'s anger was against the rest that rebelled against him,
and made them to wander in the wilderness forty years,
and to bear their whoredoms from the Lord, until their carcasses fell in the wilderness.
Numbers 14. and Num. 3. and Deut. 1.
These were those that murmured and rebelled against the Lord, and Moses, and Joshua,
and Caleb; and bade them stone them with stones, and said one to another,
'`Let us make us a captain, let us return into Egypt.`'

Now here you may see those Jews, that had seen the glory of the Lord,
and his wondrous works, and mighty arm;
and yet they murmured and rebelled against the Lord, and his faithful servants,
and through their disobedience they perished in the wilderness,
and did not inherit the land of Canaan; and therefore take heed you christians,
through your disobedience, murmuring,
and rebelling against God and his faithful servants, that you are not destroyed,
and perish in the spiritual wilderness, and never come to see heavenly Jerusalem,
and wander in the spiritual wilderness, where there is no way, and grope in the dark,
without the light of Christ, and stagger like drunken men.

And David speaks of such wicked transgressors, that make a noise like a dog,
they belch out with their mouths, swords are in their lips;
these are them that wander up and down, for they are out of the path of life.
But David said, '`With my whole heart have I sought thee;
let me not wander from thy commandments;`' for they
that love God and Christ will keep them.

And the Lord told the Jews they loved to wander: '`they have not restrained their feet,
therefore the Lord doth not accept them.`' And how did the Jews wander from the Lord,
and his ways, both in the days of Isaiah and Jeremiah?
'`Yea, they wandered from the Lord, and his spirit, and his law;
so that the ten tribes were carried into captivity by the king of Assyria,
and at last the two tribes were carried into captivity by the king of Babylon.
And therefore let those that profess themselves christians, consider;
are not they wandered from the same holy ghost,
and the power and spirit of Christ that the apostles were in?
Are not they gone into captivity, into the mystery of Babylon, or confusion?

And you may see God`'s judgments upon Moab for their pride; and the Lord said,
'`I will send unto him wanderers, that shall cause him to wander,
and shall empty his vessels, and break his bottles.`'

Now, all ye proud, consider ye this;
for there is none that is proud but they are wandered from Christ, the way to God,
who is meek and low in heart; and they that be proud, they learn of the proud,
and the proud comes over them.
So one wanderer learns of another, but their bottles will be broken,
and vessels will clash one against another; and then your filthy liquor will be spilt.

And Jeremiah in his Lamentations, chap.
iv. 14, cries out against the Jews, and saith, '`For the sins of her prophets,
and the iniquities of her priests that have shed blood in the midst of them,
they wandered as blind men, etc. they polluted themselves with blood,`' etc.

Now let Christendom consider this, let her prophets and priests,
that have shed the blood of the just, about religion and worship,
consider and see if they be not wandered from Christ the way,
who came not to destroy mens`' lives, but to save them;
and when you are thus wandered from God and Christ, who then have you to save you?
are not you wandered from your saviour?
Therefore, blessed are they whose minds are stayed upon the Lord,
they shall be kept in perfect peace.

But all you that curse people, and not only so, but spoil their goods,
because they will not be of your way, worship, and religion;
and are not your curses as the wandering bird?
and so your curses do not hit nor come upon them, but upon yourselves;^
footnote:[Prov. 26:2]
for Christ saith, '`Bless, and curse not,`' and they that curse,
are wandered from his way and doctrine.
And doth not Solomon tell you, your wandering desires are vanity, and vexation of spirit?
And therefore those desires are not to be followed or served,
for wanderers must turn to the Lord by his spirit if they be saved.
And the Lord said, '`I will send a famine in the land; not a famine of bread and water,
but of hearing the word of God, and they shall wander from sea to sea,
and from the north unto the east; they shall run to and fro to seek the word of the Lord,
and shall not find it.`'^
footnote:[Amos 8:11-12]

Now ye may consider, the Jews had the words in the old testament in Amos`'s days,
and after; and let Christendom consider, they have the words of the new testament.
And do not the teachers in Christendom say,
there is no hearing of God`'s and Christ`'s voice nowadays,
nor receiving the word from heaven, as the apostles did?
Such do wander to and fro, from one way, from one sect, and from one religion to another;
manifesting there is a famine amongst them of Christ and the word of God,
that they cannot find it; which word should reconcile them to God and the scripture;
and so it may be said of you, as Hosea said to the Jews;
for your silver you possess nettles, and thorns are in your tabernacles.^
footnote:[Hosea 9:6]
And are not you of their spirit, that say, the prophet is a fool,
and the spiritual men are mad; for the multitude of your iniquities have blinded you?
And was it not the cause of the Jews wandering among the nations,
because they forsook God and his law, and rebelled against his good spirit?
And is it now the cause of people`'s wandering,
because that they have erred from the spirit of God,
and the law of the spirit of life in Christ Jesus,
and from the same holy ghost the apostles were in?
And yet make a profession of the words of the scripture,
which was given forth by the holy ghost, like the Jews,
that made a profession of the scriptures of the old testament,
and always resisted the holy ghost that gave them forth.
So both the Jews and christians,
that are not in the same holy ghost that the prophets and apostles were in,
are the wanderers, and wandered from their habitation.
But the Lord is gathering his sheep which have been scattered,
and have wandered from mountain to hill; and has set one shepherd over them to feed them,
Christ Jesus; and Christ`'s sheep know his voice, and follow him,
and can praise God through Jesus Christ their shepherd, that feeds them.

And the apostle writes against the idle wanderers, and teachers from house to house,
and busy bodies, that speak things which they ought not;
all such wander from the spirit of God, in which is the heavenly fellowship and unity;
and they that went in Cain`'s, Korah`'s, and Balaam`'s way,
feeding themselves without fear, clouds without water, trees without fruit,
twice dead and plucked up by the roots; then they are not like to grow.
They were raging waves of the sea, foaming out their own shame, wandering stars,
to whom is reserved the blackness of darkness forever.
Now these being twice dead, first dead in sins and trespasses, and then made alive,
and then dead again, yet remain trees, wells, and clouds, but without water, rain,
or fruit; so wandering stars, in Cain`'s, and Korah`'s, and Balaam`'s way.
Cain wandered in the old world, Balaam and Korah wandered in the next world;
but these which Jude speaks of, wandered from Christ, and true christianity.
Now wandering stars are not fixed stars in the firmament of God`'s power,
so wandering stars are not to be steered by, nor followed; for they that do follow Cain,
Balaam, and Korah, are they that feed themselves without fear,
that foam out their own shame, clouds without rain, wells without water,
and trees without fruit, twice dead, plucked up by the roots, and cannot grow;
which kept not their first habitation, but have lost their first habitation;
which have forsaken the right way, that are carried about with a tempest,
to whom the mist of darkness is reserved forever.
And these wandering stars, they that keep their habitation in Christ cannot follow,
though they speak high swelling words of vanity, etc. and promise them liberty,
etc. yet bring into bondage; but as the apostle saith, follow us,
as we follow Jesus Christ; for they that do so,
are the fixed stars in the firmament of God`'s power, which bring people to the light,
grace, and truth, by which they may be fixed upon Christ, from whence grace comes,
by which they shall see and discern who follow Christ,
and who follow the wandering stars,
by the same spirit of discerning as was in the apostles,
and the church in the primitive time.
For they that have not the spirit of Christ, are none of his sheep,
but they that have the spirit of Christ are his sheep, and established in him,
and upon him their heavenly rock and foundation, through whom they have peace with God.

And are not you sensible how the Jews, Scribes, and Pharisees, priests, and high priests,
were wandered from the holy ghost,
and resisted it when the Lord Jesus Christ was come in the flesh, and also resisted him?
and were not they gone into many sects?
and did not Christ`'s prophecy come upon them that
they should be scattered among all nations,
and their city Jerusalem should be destroyed, and is not that come to pass?

And are not most Christians wandered from the holy ghost, the apostles were in,
and is not that the cause that Christians are led into so many sects,
by the unclean ghost or spirit, and with it destroy one another,
because they will not commune or conform one to another?
who are wandered from the true communion of the holy ghost,
and the fellowship and unity in the spirit, 2 Cor. 13:14.
and the fellowship of the son of God, 1 Cor. 1:9.
and the fellowship of the glorious gospel of salvation, the power of God,
and the fellowship with the Father and the son, and one with another, 1 John 1.

And you may see the vagabond Jews were like unto Cain and Judas,
persecutors and killers of the just and righteous,
that kept their habitation in God and Christ,
but the Lord hath pronounced a woe against all such
vagabonds and wanderers from God and Christ,
and his law, and spirit, and command; and will reward them according to their works.
And therefore, while ye have time, turn to the Lord by his spirit,
'`and seek him while he may he found,
and call upon him while he is nigh;`' who would have all men to be saved,
and come to the knowledge of the truth.
'`Your hearts shall live that seek God.`' Ps. 69:32.

[.asterism]
'''

[.blurb]
=== The Christians`' righteousness must exceed the righteousness of the Scribes and Pharisees, or else they cannot enter into the kingdom of God; and such as persecute the righteous, are full of dead men`'s bones, and their throats are open sepulchres; and such as envy their brethren, are menslayers, and have not eternal life abiding in them.

Christ saith,
'`Except your righteousness exceed the righteousness of the scribes and Pharisees,
ye shall in nowise enter into the kingdom of God.`' Matt. 5. So it is clear, with it,
to wit, the righteousness of the scribes and Pharisees,
they cannot enter into the kingdom of God, which stands in Christ`'s righteousness;
and as long as people remain in the righteousness of the scribes and Pharisees,
they remain out of the kingdom of God.

Now, what is the righteousness of the scribes and Pharisees?
Is it not the righteousness of the law,
Do this and live?`' And no flesh is justified by the works of the law,
but by the faith and righteousness which is in Christ Jesus.
Now what is the righteousness of the law, and the works of the law,
and the righteousness of the Jews, priests, scribes, and Pharisees?
Is it not outward circumcision, and observing the new moons and feasts,
and their paying their tithes, first fruits, and offerings,
with all their priests`' garments; with Aaron`'s bells, lamps, candles and candlesticks,
outward tabernacles, arks, altars, temples, sanctuaries,
and priests`' lips to preserve people`'s knowledge; with their sabbath days,
with their swearing, and oaths, and all their outward washings and observing of meats?
Are not all these the works of the law, and commanded by the law?
And by the works of the law,
'`no flesh shall he justified.`' Then what profit
or comfort have you in doing all these things,
seeing that these are the works of the law, and that by the works of the law,
'`no flesh shall be justified.`' Gal. 2:16. And did not the Jews, priests, scribes,
and Pharisees, cry up these works of the law before mentioned,
in opposition to the gospel, by which they were not justified?
And were not the works of the law, the righteousness of the scribes and Pharisees,
which Christ saith to his disciples,
'`Except your righteousness exceed the righteousness of the scribes and Pharisees,
they shall in nowise enter into the kingdom of God?`' But now in the new covenant,
the righteousness of God without the law is manifest,
being witnessed by the law and the prophets, even the righteousness of God,
which is by the faith of Jesus Christ unto all, and upon all them that believe;
and therefore, as the apostle saith,
we conclude that a man is justified by faith without the deeds of the law.

And Isaiah saith, '`All our righteousness is as filthy rags,
and our iniquities like the wind have taken us away.`' Isa.
64:6. So this righteousness that was like filthy rags,
was below the righteousness of the law, which was just, holy, and good.

And the apostle saith, '`the Gentiles which followed not after righteousness,
have attained to righteousness, even the righteousness which is of faith;
but the children of Israel which followed after the law of righteousness,
have not attained to the law of righteousness, because they sought it not by faith,
but as it were by the works of the law, for they stumbled at the stumbling stone, to wit,
Christ and his righteousness.

And the apostle saith, '`I count all things but loss,
for the excellency of the knowledge of Jesus Christ, my Lord,
for whom I have suffered the loss of all things, and do count them but dung,
that I may win Christ, and he found in him;
not having my own righteousness which is of the law,
but that righteousness which is through the faith of Christ,
the righteousness which is of God by faith.`' Eph. 3:9. And Christ saith,
the comforter should reprove the world of their sin, because they believed not in him,
and of their righteousness, and of their judgment.`' So the world as well as the Jews,
high priests, scribes, and Pharisees, have a righteousness,
and a judgment in their sin and unbelief, which judgment, righteousness, and unbelief,
are reproved by the holy ghost, that proceeds from the Father and the son.
And with that righteousness they cannot enter into the kingdom of God,
that stands in power, and righteousness, and peace, and joy, in the holy ghost.
And Christ said to the scribes and Pharisees,
'`Ye strain at a gnat and swallow a camel,`' and ye cleanse the outside of the cup,
and of the platter; but within they were full of extortion and excess;
they were like unto whitened sepulchres, which appeared beautiful outwardly unto men,
but are within full of dead men`'s bones, and of all uncleanness;
though outwardly they appear righteous unto men,
but within they are full of hypocrisy and iniquity;
as you may see in Matt. 23. And John saith, in his 1st epist.
iii chap.
15 ver.
'`Whosoever hateth his brother, is a murderer or a manslayer,
and ye know that no murderer hath eternal life abiding
in him.`' And David and the apostle say,
'`Their throat is an open sepulchre, and there is no faithfulness in their mouths,
in their inward parts is wickedness,
and with their tongues they flatter and use deceit.`' Ps. 5. Rom. 3.

Now, here you may see the great professing high priests, Jews, and scribes,
and Pharisees, which were the greatest professors upon the earth.
'`Their throats were open sepulchres, and full of dead men`'s bones, yea,
such as appeared outwardly beautiful and righteous unto men,
and yet the greatest killers and persecutors of men,
about religion;`' and have not all the persecutors
and killers of people about religion in Christendom,
succeeded them, in their spirit, and followed them in their examples and footsteps,
and not Christ and his apostles?
And then are not their throats open sepulchres, and full of dead men`'s bones,
as the Jews were?
and to be such as hate their brethren, murderers, and manslayers?
and no murderer among the Christians, or Jews, or heathens,
hath eternal life abiding in him, but '`their throats are open sepulchres,
and full of dead men`'s bones.`' And such their outward beauty and righteousness,
and outward washings avail them nothing, whose throats are open sepulchres,
and they full of dead men`'s bones; and therefore Christ cried,
woe against such scribes and Pharisees, and hypocrites, and said, they were as graves. Luke 11:44.
So you know that a sepulchre that is open and full of dead men`'s bones,
gives an ill savour, for he that hates his brother is a manslayer, and a murderer,
and he hath slain him, and buried him in his heart, his sepulchre,
if he have not killed him, and buried him outwardly,
'`for their throat is an open sepulchre,
and they are full of dead men`'s bones;`' and so their open
sepulchres give an ill savour to God and just men,
as before said.
And all persecutors that persecute and kill men outwardly concerning religion,
and they that hate their brethren are murderers, and all such are graves,
and open sepulchres, and full of dead men`'s bones;
and have not eternal life abiding in them, though they may profess the new testament,
as the Jews did the old,
without being in the same holy ghost that they were in that gave them forth,
and so the wicked persecuted the righteous and just in all ages.

G+++.+++ F.
