[.style-blurb, short="Concerning Such as Shall Enter the Kingdom of God"]
== Concerning such as shall enter into the kingdom of God, and New and Heavenly Jerusalem, and such as shall not. By G. F.

Christ Jesus saith, '`No man can see the kingdom of God,
nor enter into the kingdom of God, except he be born again of water, and of the spirit.
For that which is born of the flesh, is flesh, and that which is born of the spirit,
is spirit.`' John 3:6. '`And he that was born after the flesh,
persecuted him that was born after the spirit;
even so it is now.`' Gal. 4:29. '`And in Christ,
neither circumcision availeth any thing, nor uncircumcision; but a new creature.
For he that soweth to the flesh, shall of the flesh reap corruption:
but he that soweth to the spirit,
shall of the spirit reap life everlasting.`' Gal. 5:15,6,8.

Now consider, what good all the Christians`' or the Jews,`' or Turks`' outward worships,
religions, or professions do them; if they be not new creatures, and born again,
it availeth them nothing, neither shall they see the kingdom of God, or enter into it,
except they be born again of the spirit; for if they do sow to the flesh,
of the flesh they shall reap corruption, for they cannot sow to the spirit,
and of the spirit reap life eternal, except they be born of the spirit.

'`The works of the flesh are manifest, which are these, adultery, fornication,
uncleanness, lasciviousness, idolatry, witchcraft, hatred, variance, wrath, strife,
sedition, heresy, envyings, murder, drunkenness, revelings, and such like;
of which I tell you, as I have told you before in times past,
that they which do such things shall not inherit the kingdom of God.`' Gal. 5:19-21.

And now consider, all you that do these evil works, the apostle tells you,
ye shall not inherit the kingdom of God, for the kingdom of God is not in words,
but in power; and stands in righteousness and peace, and joy in the holy ghost.

And again, the apostle saith,
'`Know ye not that the unrighteous shall not inherit the kingdom of God?
Be not deceived, neither fornicators, nor idolaters,
nor abusers of themselves with mankind; nor thieves, nor covetous, nor revilers,
nor extortioners, shall inherit the kingdom of God.`' 1 Cor. 6:10-9.

Here you may see, such as act and live in these wicked things,
shall not inherit the kingdom of God.
And therefore, you that act such things and live in them, consider what your end will be,
and what kingdom you must inherit.

And the apostle saith to the Corinthians, '`Know ye not that you are the temple of God,
and the spirit of God dwelleth in you?
If any man defile the temple of God, him shall God destroy;
for the temple of God is holy, which temple ye are.
Let no man deceive himself.`' 1 Cur.
Iii. 16, 17, 18.

Here you may see what judgment God threatens upon them that defile his temple; namely,
their bodies, as in 1 Cor. 6:15 to 19.

And the apostle saith to the Ephesians, '`Fornication and all uncleanness,
and covetousness, let it not be once named among you, as becometh saints;
neither filthiness nor foolish talking, nor jesting, which are not convenient,
for this ye know, that no whoremonger, nor unclean person, nor covetous man,
who is an idolater, hath any inheritance in the kingdom of Christ and of God.
Let no man deceive you with vain words,
for because of these things cometh the wrath of God upon the children
of disobedience,`' as you may see in Ephesians 5:6.

Now here you may see, they that commit these things and live in them,
shall not inherit the kingdom of Christ nor of God;
but these evil things who commit them, bring the wrath of God upon them:
and do not deceive yourselves, for you cannot escape it.
And these evil things are so far from being practised or acted amongst the saints,
that they are not so much as once to be named amongst them;
the saints are to be kept so holy, which do inherit the kingdom of Christ and of God,
which is holy.

And Christ said unto John, '`He that overcometh shall inherit all things,
and I will he his God, and he shall be my son.
But the fearful and unbelieving, and the abominable, and murderers, and whoremongers,
and sorcerers, and idolaters,
and all liars shall have their part in the lake which burns with fire and brimstone,
which is the second death.`' Revelations xxi.
7, 8.

Now here you may see is the end of all such that live in such unclean actions,
according to Christ`'s judgment.
And the end and comfort of all them that overcome the devil and his works,
they shall inherit all things, and shall be called God`'s sons.

'`And the nations of them which are saved shall walk in the light of heavenly Jerusalem,
the glory of the Lord doth lighten it, and the lamb is the light thereof.
And the gates of it shall not be shut at all by day, for there shall be no night there,
and there shall in no wise enter into it any thing that defileth,
neither whosoever worketh abomination, or maketh a lie,
but they which are written in the lamb`'s book of
life;`' they shall enter into this heavenly Jerusalem,
for without this heavenly Jerusalem are dogs, and sorcerers, and whoremongers,
and murderers, and idolaters, and whosoever loveth and maketh a lie.`' Revelations xxii.
15

And therefore consider, all ye that live in these evils, and are defiled with them,
Christ tells you ye can in nowise enter into this holy city New Jerusalem.

And John saith, '`the devil and them that he had deceived,
were cast into the lake of fire that burneth with brimstone,
with the beast and the false prophet;
and shall be tormented day and night forever and
forever.`' So here is an end of the devil,
beast, and false prophet, and his followers.

And John he saw '`death and hell were cast into the lake of fire,
this is the second death;
and whosoever was not found written in the lamb`'s book of life,
was cast into the lake of fire;`' there is their end.

'`And the beast and his followers made war with him that sat upon the horse,`' namely,
Christ and his followers, '`and the beast was taken,
and with him the false prophet that wrought miracles before the beast,
with which he deceived them that received the mark of the beast,
and them that worshipped his image;
these both were cast alive into the lake of fire which burns with
brimstone.`' And here is the end of such deceivers and worshippers,
as you may see in Revelations xix.
19-20; which make war against Christ and his followers, but he is too hard for them,
and '`overcometh them.`' And they '`that worship the image that
the beast hath made,`' such do not worship God in spirit and truth,
as Christ commanded above sixteen hundred years ago.
And you may see the judgment and punishment of the great whore, mystery, Babylon,
mother of harlots, or false church,
who hath harloted from the spirit of Christ that the apostles were in,
who hath drunk the blood of the martyrs, and in her was found the blood of the prophets,
and of the saints,
and of all that were slain upon the earth concerning religion and worship;
in this whore which is whored from the spirit of God the apostles were in.
But you may read her judgment and punishment, fall and destruction, in Revelations xvii. 18.
'`And of the beast that ascended out of the bottomless pit, and goeth into perdition,
and they who dwell on the earth shall wonder,
whose names were not written in the book of life, from the foundation of the world.`'

But they whose names are written in the book of life,
do not wonder at the downfall of the beast, and whore, the false church.
And Christ Jesus said unto his disciples, and to the multitude,
'`Except your righteousness do exceed the righteousness of the scribes and Pharisees,
ye shall in nowise enter into the kingdom of heaven.`' Matt. 5:20.
Christ`'s righteousness doth exceed the righteousness of the law,
and man`'s own outward righteousness, which is as filthy rags.

Christ saith, '`It is not every one that saith unto me, Lord, Lord,
shall enter into the kingdom of heaven;
but he that doeth the will of my Father which is in heaven.`' Matt.
7:21. So here you may see it is not the sayers of the will of God,
and calling Christ Lord,
but the doers of the will of God that enter into the kingdom of heaven.
And James saith, '`if they were hearers of the word only, and not doers,
they deceive their own souls;`' for the apostle Paul saith,
'`The hearers of the law are not justified before God,
but the doers of the law shall be justified.`' Rom. 2:13. and James 1:22.

And Christ Jesus saith, '`Woe be unto you scribes and Pharisees,
hypocrites! for ye shut up the kingdom of heaven against mm,
for ye neither go in yourselves,
neither suffer ye them that are entering to go in.`' Matt. 23:13.

Now is not this the state and condition of many great professors in Christendom,
with their long prayers, and with their tithes, mint, anise and cummin, and making,
or forcing '`to themselves proselytes, and shutting up the kingdom of heaven from men;
and neither go in themselves,
nor suffer them that would enter.`' And drawing people from the light of Christ,
and his spirit, and power, and grace, in their own hearts,
by which they should see the kingdom of God, and enter into it.
And Christ said to his disciples when he '`sent them
forth as sheep in the midst of wolves,`' namely,
the outward professing Jews, '`And whosoever shall not receive you and hear your words,
when you depart out of that house or city, shake off the dust of your feet.
Verily, I say unto you,
it shall be more tolerable for the land of Sodom and Gomorrah in the day of judgment,
than for that city.`' Matt. 10:14.

Here you may see they that will not receive the message of Christ and his gospel,
they '`shake off the dust of their feet against them,`'
and leave them to the day of judgment,
as Paul and Barnabas did,
in Acts 13:50-51. And Christ said to him that he gave five talents to,
and he had gained five talents more.
'`Well done thou good and faithful servant: thou hast been faithful over a few things,
I will make thee ruler over many things:
enter thou into the joy of thy Lord.`' Matt. 25:23.
Here you may see they that do well,
and do improve their heavenly talents,
do '`enter into the joy of the Lord.`' And they which do believe do enter into rest,
and he that is entered into his rest is ceased from his own works, as God did from his;
and they which do not believe in the life of Christ, do not enter into him their rest,
because of their unbelief. Heb. 4:6. 10.
And therefore consider, where they remain,
if it be not in the kingdom of the beast and dragon,
'`full of darkness?`' and there '`they gnaw their tongues for pain,
and yet will not repent of their evil deeds.`' Rev. 16. But unto his son he saith,
'`Thy throne O God is forever, and ever,
a sceptre of righteousness is the sceptre of thy
kingdom.`' Heb. 1:8. And Peter saith,
'`Of a truth, I perceive that God is no respecter of persons,
but in every nation he that feareth God,
and worketh righteousness is accepted with him.`' Acts 10:34-35.
Here you may see they must be such as work righteousness,
and not only talk of righteousness if they be accepted with God.
And the unprofitable servant that hid his talent, and did not improve it,
it was taken from him, and he '`cast into utter darkness,
etc. where there shall be weeping and gnashing of teeth;`'
and will not this be the portion of all them that do not
improve their heavenly talent that Christ gave unto them.
And Christ Jesus speaking of the sheep on his right, and the goats on his left hand;
to the goats he saith, '`Depart from me ye cursed into everlasting fire,
prepared for the devil and his angels.`' And so '`they
do go into everlasting punishment;`' but the sheep,
which are the righteous, '`that are on his right hand,
they shall go into everlasting life.`' Matt. 25. Now here
you may see Christ`'s judgments upon the wicked,
and their end, and the happiness and eternal state of the righteous,
which Christ calleth his sheep.
