== Concerning Condemnation.

He that believeth on Christ in his light, which is the life in him, is not condemned;
but he that believeth not in the light, as Christ commands, '`is condemned already.
And this is the condemnation that light is come into the world,
and men love darkness rather than light, because their deeds are evil.
And every one that doth evil hateth the light, neither cometh to the light,
lest his deeds should be reproved,`' John 1:3. 12.

Now here you may see, this is the condemnation that light is come into the world,
and every one that doth evil hateth the light, and loveth darkness rather than light,
whose deeds are evil.
And again Christ.
saith, '`He that heareth my word, and believeth on him that sent me,
hath everlasting life, and shall not come into condemnation,
but is passed from death to life.`' John 5:24. '`And he
that believeth not the son of God shall not see life,
but the wrath of God abideth on him, and he is condemned already.
But whosoever believeth in the son of God, shall not perish,
but have everlasting life.`' John 3:16-18, 36. So it is by believing in the light,
which is the life in Christ, that people come out of condemnation to life.
And '`as by the offence or disobedience of one, namely, Adam,
judgment came upon all men to condemnation; even so by the righteousness of one, namely,
Christ,
the free gift came upon all men to justification of life.`' Rom. 5:18.
Now if you do not believe in Christ,
as he hath commanded, in his light, which is the life in him,
'`you shall not see life`' without his light;
and Christ tells you that you are condemned already
that do not believe in him,`' and his light,
'`and the wrath of God abideth upon you.`'

And the apostle Paul saith, '`There is no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the spirit,`' Rom. 8:1; that is,
not after the motions of the flesh, but after the motions of the spirit of God.
These are they which believe in the light, which is the life in Christ,
and are grafted into him.
And the apostle calleth the old covenant, or old testament,
'`a ministration of condemnation,
though it was glorious in its time;`' but the ministration
of righteousness in the new covenant,
and new testament, exceeds it in glory;
and the glory of the first testament is done away, and abolished by Christ, as in 2 Cor.
Iii.

Now in the first testament it was the command of God,
'`that they should not forswear themselves,
but perform their oaths to the Lord,`' as in Matt. 5:33-34.
But Christ in his new testament and new covenant,
saith,
'`I say unto you swear not at all;`' and this doctrine he preached to his disciples,
and to the Jews that had commanded oaths and swearing.
And the apostle James, who directed his epistle to the twelve tribes,
and he had been a Jew and a professor of the old testament and old covenant,
and now was converted and a believer in Christ Jesus,
and a preacher of the new covenant and new testament, according to Christ`'s doctrine;
and he said, But above all things my brethren swear not; neither by heaven, nor by earth,
neither by any other oath; but let your yea, be yea, and your nay, nay,
lest ye fall into condemnation.`' James 5:12.

Now here according to James`'s doctrine, they that swear, or take any oath,
fall into condemnation;
and go out of the doctrine of Christ and the apostles in the new testament and new covenant;
and Christ said unto the Jews, '`If you had known what this meaneth, I will have mercy,
and not sacrifice,
ye would not have condemned the guiltless.`' Matt. 12:7. And James saith to the Jews,
'`Ye have condemned and killed the just,
and he doth not resist you.`' This James speaketh to the Jews,
that '`had lived in pleasure upon the earth, and been wanton,
and had nourished their hearts as in the day of slaughter.`' James 5:6.
But such ungodly men are for condemnation,
as in Jude 4. And as Solomon saith, '`A man of wicked devices will the Lord condemn;
and he that justifieth the wicked, and he that condemneth the just,
even they both are an abomination to the Lord.`' Prov. 12:2. 17. 15.
And Christ Jesus saith, in Matt. 12:36.
'`I say unto you, that every idle word that men shall speak,
they shall give account thereof in the day of judgment;
for by thy words thou shalt be justified,
and by thy words thou shalt be condemned.`' Are not all here to have a care,
and to be watchful against idle words, and bad words, lest they be condemned;
but as the apostle saith, '`there is no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the spirit;`' that is,
not after the fleshly ways, words, nor works.
And then, as the apostle saith, '`who shall lay any thing to the charge of God`'s elect?
It is God that justifieth, who is he that condemneth?`' Rom. 8:1. 33, 34.
So you may see here, who are condemned, and who are justified;
and who enter into the kingdom of God, and into the heavenly Jerusalem, and who not.

G+++.+++ F.
