[#ch20.style-blurb, short="Concerning Such as Have Forbidden Preaching"]
== Concerning such as have forbidden preaching, or teaching in the name of Jesus, and such as are ashamed to confess Him before men, and call not on the name of the Lord, etc.

Here you may see who, and what they were, that forbade the apostles to preach, or teach,
or speak in the name of Jesus;
and what Christ saith of such that are ashamed to confess him before men;
and what judgments come upon those families, kingdoms, or nations,
that do not call upon the name of the Lord.
And they that do not call upon the name of the Lord, and know him not,
are such as devour Jacob, the elect and beloved of God.
'`And yet the Lord poureth out of his spirit upon
all flesh,`' that with the spirit they may know God,
and call upon his name.
Joel 2. Acts 2.

The Jews and their priests said unto the apostles, and threatened them,
'`that ye speak henceforth to no man in this name`' Jesus. Acts 4:17.
And they said again (in verse 18,) to the apostles,
that they should not teach in the name of Jesus.`' And in Acts 5:28. they again said,
'`that they should not teach in the name of Jesus,`' mark,
not to teach in the name of Jesus.
And in verse 40, they said again to the apostles,
that they should not speak in the name of Jesus; mark,
not so much as to speak in the name of Jesus.
And yet the apostle said, '`With the heart man believeth,
and with the mouth confession is made unto salvation.
And if thou confess with thy mouth the Lord Jesus Christ,
and that God hath raised him up from the dead, thou shalt be saved.`' Rom. 10:10-9.

And the Jews, which were the greatest outward professors, agreed,
that if any man did confess that he was the Christ,
he should be put out of the synagogue.`' John 9:22.
'`And many of the chief rulers believed on him;
but because of the Pharisees, they did not confess him,`' namely, Christ,
lest they should be put out of the synagogue.`' John
12:42. So here were them that did believe,
both rulers and others, in Christ; but they were afraid to confess Christ,
lest they should be excommunicated, or put out of their synagogue.
And Christ saith unto his disciples, '`Whosoever shall confess me before men,
him will confess also before my Father, which is heaven:
but whosoever shall deny me before men, him will I also deny before my Father,
which is heaven.`' Matt. 10:32-33. and Luke 12:18. So here you may see,
they that do confess Christ before men, are confessed by him before his Father;
and they that deny him before men, Christ will deny before his Father.

And John saith, '`Every spirit that confesseth that Jesus Christ is come in the flesh,
is of God; and every spirit that confesseth not that Jesus Christ is come into the flesh,
is not of God.`' So here you may see that it is the good spirit
of God that doth confess his son to be come in the flesh. 1 John 4:2-3.
Here you may see the two spirits, that which is of God,
and that which is not of God, the good spirit, and the bad spirit.
And '`who confess not that Jesus Christ is come in the flesh, is a deceiver,
and an antichrist,`' and so not in the spirit of God nor Christ. 2 John 1:7.
And the apostle saith, '`Prove your own selves,
know ye not your own selves, how that Jesus Christ is in you,
except you be reprobates?`' 2 Con xiii.
5+++.+++ And so if they have not the spirit of Christ, and if he be not in them,
then they are reprobates, and so none of Christ`'s.

And the apostle saith to the Colossians, '`Christ in you,
the hope of glory.`' And they warned every man, and taught every man in all wisdom,
that they might present every man perfect in Christ
Jesus.`' So then Christ must be in his people,
and they must be in him. Col. 1:27-28.

And Christ before Pontius Pilate '`witnessed a good confession.`' 1 Tim. 6:13.
This was before his persecutor;
so must all the followers of the lamb confess him before men,
to the glory of God the Father, and not he ashamed of Christ, their life, light,
and salvation, redeemer, mediator, prophet, bishop, shepherd, leader, counsellor,
way and door to God, and the author and finisher of their faith,
and heavenly rock and foundation, and the captain of their salvation,
and not to be ashamed to meet in his name,
who hath all power in heaven and in earth given to him,
lest he be ashamed of you before his holy angels, and his Father, which is in heaven.
And therefore, in his light, spirit, grace, truth, and faith,
see and hold Christ your head, who bruiseth the serpent`'s head,
and reconcileth you to God, in whom you, and all nations are blessed,
and have rest and peace.
Amen.

'`Pour out thy fury upon the heathen that know thee not,
and upon the families that call not upon thy name; for they have eaten up Jacob,
and devoured him, and consumed him,
and have made his habitation desolate.`' Jer. 10:5.
These were the persecutors of the faithful.

And David saith, '`Pour out thy wrath upon the heathen that have not known thee,
and upon the kingdoms that have not called upon thy name; for they have devoured Jacob,
and laid waste his dwelling place.`' Ps. 79:6-7.
These were the persecutors of God`'s elect.

Yet '`God setteth the poor on high from affliction,
and maketh him families like a flock.`' Psalm evil.
41.

And God '`setteth the solitary in families,
and bringeth out those which are bound with chains.
But the rebellious dwell in a dry land.`' Ps. 68:6.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 6th of the 10th month, 1684.
