[.style-blurb, short="To Magistrates, Rulers, Ministers, Justices, and Other Officers"]
== To the Chief Magistrates, Rulers, Ministers, Justices of the Peace, and other Officers; who profess Christ and Christianity, and are called by that worthy name, and great title of Christians; which is from the King of kings, and Lord of lords, Christ Jesus.

[.numbered-group]
====

[.numbered]
_1st._ And you professing the holy scriptures of truth,
and confessing to the new testament and new covenant, and the law and the prophets,
which is, to love God above all, and your neighbours as yourselves,
and the royal law of God, spoken of in the new testament; which is,
to do into others as you would have them do unto you.
Now would not you judge and believe, that it was contrary to the royal law of God,
if that the Papists,
or the Presbyterians should make spoil of your goods
and take away your goods out of your shops,
and your very beds and working tools, your corn and your cattle,
so that you have not a cow to give your family and your children milk,
nor corn to make you bread;
and all that because for conscience sake you cannot
be of the Papists`' or Presbyterians`' religion?
Would you say, this was according to the royal law of God,
and the nobility of true christianity in them, TO DO UNTO ALL,
AS THEY WOULD BE DONE UNTO, if they should serve you so?

[.numbered]
_2dly._
And would you say, it was according to the royal law of God,
to be haled from your peaceable meeting by officers and soldiers,
for serving and worshipping God in his spirit and truth, that made you;
and to have your goods taken away from you through informers,
to the ruin of your wives and children; and to be cast into loathsome prisons,
there to be kept till some of you died;
because for conscience sake you cannot be of the Papists`', Presbyterians`',
or Independents`' religion?
would you not say, this was contrary to the royal law of God,
and to the nature and nobility of true christianity in them, that should do so to you?

[.numbered]
_3dly._
And if the Presbyterians, Independents, or Papists,
should make you pay twenty pounds a month, or two-thirds of your estates,
and bring quitam writs against you, as is now against many hundreds of us;
and cast you in prison, and spoil your goods, as ours now are;
because for conscience sake you cannot join with their outward forms of religion;
would you say, that this was according to the royal law of God,
'`to do unto others as they would have them do unto
them?`' or according to the law and the prophets,
'`to love their neighbours as themselves?`'

[.numbered]
_4thly._
If the Papists, Presbyterians, or Independents,
should banish you from your wives and children, or imprison you,
(as many of us are now imprisoned,
and others have been banished,) because you do peaceably
meet together to serve and worship God,
and pray to him; and they should call your peaceable meetings,
seditious conventicles and riots,
because you cannot for conscience sake join to any of their forms of religion?
would you not say this was contrary to the law and the prophets,
'`to love their neighbours as themselves;`' and to the royal law of God,
'`to do unto all men,
as they would have them do unto them?`' and to the nobility of true christianity,
in them that should do so unto you?

[.numbered]
_5thly._
And would not you think it very hard from the Papists, Presbyterians or Independents,
if they should premunire you, and cast your men, women, and widows into prison,
(as many of us are now from their wives and children,) because
for conscience sake you dare not swear at all,
or take any oath, because Christ and his apostles forbids it,
(Matt. 5. and James 5.) though your peaceable lives and conversations have,
and do show forth your allegiance to the king;
and though you are willing to testify the truth in all matters and cases with yea, yea,
or nay, nay, as Christ and the apostle commands; and as we have done, and do?
Would you say, this was according to the law and prophets in them,
and the royal law of God,
'`to love their neighbours as themselves,`' and '`to do unto all,
as they would be done unto?`'

[.numbered]
_6thly._
And would the bishops and priests believe, that it was according to the royal law of God,
and according to the law and the prophets, for the Papists, Presbyterians,
or Independents to excommunicate them, and cast them into prison,
and there to keep them till they die, (as several of us have been so kept,
and many are now in prison,) because for conscience sake you cannot join to the Papists`',
Presbyterians,`' or Independents`' forms of religion?
Would you say,
this were '`to love their neighbours as themselves,`' and '`to do unto others,
as they would have others do unto them;`' and that it was according
to the nature and nobility of true christianity in them,
that should do so unto you?

====

And now I do in humility desire you to consider,
did ever Christ and his apostles force any to be of his true religion and worship;
and if that they would not, then to give forth orders to take away their goods,
and their very beds, and their corn which should make them bread,
their cattle which should help to maintain them,
and their cows which should give them milk,
their clothes they should wear to keep them warm,
and their tools they should work withal to get their living?
Did not Christ on the contrary exhort christians TO LOVE ONE ANOTHER, and TO LOVE ENEMIES?
And the apostle says, OVERCOME EVIL WITH GOOD.
And Christ told the Jews, what the substance was of the law and the prophets,
viz. '`to love God above all, and their neighbour as themselves.`' And should not all,
that go by the name of Christians, and profess that great title of christianity,
from Christ Jesus the lamb of God, show forth the nobility of true christianity,
and his lamb-like nature;
and not '`one christian to tear another to pieces,`' and '`spoil his goods,
and cast him into prison,`' because he cannot for conscience
sake receive and join to one another`'s form of religion;
seeing that Christ rebuked his disciples,
'`that would have had fire come down from heaven,
to consume them that would not receive him;`' and told them,
'`they did not know what spirit they were of,
and that he came not to destroy men`'s lives,
but to save them.`' Should not all true christians have the mind of Christ?

Do you think, that God doth accept the sacrifice or offerings of forced religion,
to save themselves from prison, and from spoil of their goods,
contrary to their tender conscience?
Were not the offerings and sacrifices to be free-will
offerings to the Lord in the time of the law?
And in the gospel day of the new covenant and testament,
are not the offerings and sacrifices of the Lord spiritual?
And can any man force and compel the spirit of God to that offering and sacrifice?
For doth not the apostle say to the christians, '`Ye are a royal priesthood,
offering up spiritual sacrifices to God by Jesus Christ?`' And after Christ was ascended,
did ever the apostles, bishops, or elders give any orders to excommunicate, spoil goods,
and cast any into prison, there to be kept till death,
(as many of us have been,) such as could not conform to their religion?

And therefore I desire you in the fear of the Lord, and in his gentle, holy wisdom,
(which is easy to be entreated,) to consider these things, and us,
who are under great sufferings, imprisonment, and spoiling of goods;
whether this is according to the royal law of God, and his prophets, which is,
'`to love their neighbours as themselves,`' and '`to do unto all,
as they would be done unto?`' or according to the nature of the lamb, Christ Jesus,
and the nobility of true christianity?
And whether or no ye would say, if the Presbyterians, Independents,
or Papists should do so to you concerning your tender consciences,
and for your worship and serving of God, and your not joining with them,
it would be well in them, and according to the royal law of God, '`to do unto you,
as they would not have others do unto them?`' and whether you would say,
it were according to the lamb-like nature of Christ, and according to true christianity?

Song. 1 desire you, that ye would weigh these things with the spirit of God,
and the balance of the sanctuary;
and measure them with the line and rule of righteousness,
according to the scriptures of truth.

From him that desires the good and happiness of the KING and KINGDOM,
and all the king`'s subjects in it, in this life,
and his and their eternal welfare in the life and world which is everlasting;
and does pray for kings, princes, governors, and magistrates,
that we may lead and live a holy, peaceable, and quiet life in all godliness under them:
FOR MAGISTRATES ARE FOR A PRAISE OF THEM THAT DO WELL.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 17th of the 9th month, 1684.

[.blurb]
=== Postscript

Where do ye ever read, that the Jews, when they had conquered any nation or kingdom,
did by the law force them to the Jewish religion, or to be circumcised?
Or that they cast them into prison,
if they would not join with them in their divine service?
Though Christ said,
'`they compassed sea and land to make proselytes;`' yet where do ye read,
they made them by force, or they became proselytes to save their goods,
or keep themselves out of prison?
And ye read in Genesis, '`that Abraham and Isaac lived in Gera,
in king Abimelech`'s country;`' yet ye do not read
that the king forced them to his religion;
but they had their liberty to serve and worship God.
And also in Genesis, when Abraham went down into Egypt,
and Jacob and his family after him;`' ye do not read,
that king Pharaoh forced either Abraham, or Jacob and his family to his religion,
while they lived there.
And the Turks, when they conquer any nation or people, or take captives,
we do not hear that they force them to their religion.
For our Friends, (the people called Quakers,) in Algiers,
that are taken captives by the Turks, have their liberty peaceably to meet together,
to serve and worship God there without disturbance.
And therefore they that bear that great and worthy name of Christians, from Christ Jesus,
and profess the holy scriptures of truth, and the royal law of God, which is,
'`to do unto others,
as they would have them to do unto them,`' should show forth the nobility of true christianity,
and the nature of the lamb, Christ, which is far above all Turks and heathens.

[.signed-section-signature]
G+++.+++ F.

[quote.scripture, , Matt 5. 7.]
____
Blessed are the merciful, for they shall obtain mercy.
____

[quote.scripture, , Matt 9:13]
____
Christ saith,
Learn what that meaneth, I will have mercy, and not sacrifice.
____
