== An exhortation to all people, to pureness, cleanness, and holiness, and faithfulness to the Lord.

Here you may see who they are that dwell with everlasting burnings, and in God`'s tabernacle and holy mountain, and who not. By G. F.

David saith, '`Who shall ascend unto the hill of the Lord?
and who shall stand in his holy place?`' David answers, and saith,
'`He that hath clean hands, and a pure heart; who hath not lift up his soul unto vanity,
nor sworn deceitfully; he shall receive the blessing from the Lord,
and righteousness from the God of his salvation;
and this is the generation of them that seek the Lord.`'
Ps. 24. So here is a generation of clean hands,
and a pure heart that ascend into the hill of the Lord, and stand in his holy place.

And Isaiah saith, '`Who amongst us shall dwell with devouring fire?
Who amongst us shall dwell with everlasting burnings?`' And Isaiah answers his questions,
and saith, '`he that walketh righteously, and speaketh uprightly;
he that despiseth the gain of oppression, that shaketh his hands from holding of bribes;
that stoppeth his ears from hearing of blood, and shutteth his eyes from seeing of evil;
he shall dwell on high, his place of defence shall be the munition of rocks;
bread shall be given him, his water shall be sure;
thine eyes shall see the king in his beauty,
etc. and thine eyes shall see a tabernacle that shall not he taken down,
not one of the stakes thereof shall ever be removed,`' etc.
Isa. 33.

Here you may see who they are that can dwell with devouring fire,
and everlasting burnings, and yet shall not be burned nor devoured.

David saith, '`Lord, who shall abide in thy tabernacle?
And who shall dwell in thy holy hill?`' David answers his questions, and saith,
'`He that walketh uprightly, and worketh righteousness,
and speaketh the truth in his heart.
He that backbiteth not with his tongue, nor doth evil to his neighbour,
nor taketh up a reproach against his neighbour; in whose eyes a vile person is condemned,
but he honoureth them that fear the Lord, etc.
He that taketh not a reward against the innocent;
he that doth these things shall never be removed,
but shall abide in the tabernacle of the Lord,
and dwell in his holy hill.`' Ps. 15. '`But the ungodly are not so,
but are like the chaff which the wind driveth away;
therefore the ungodly shall not stand in judgment, (namely,
righteous judgment,) and sinners shall not stand in the congregation of the righteous.`'

'`The mountain of the house of the Lord, shall be established above all the mountains;
and exalted above all the hills;`' and doth not the Lord here teach
his people his righteous and holy ways and paths to walk in?
as in Isa. 2. Micah 4. And the stone that smote the great image of gold, of silver,
of brass, and iron, and clay, that they became like chaff of the summer threshing floors,
and the wind carried them away, that no place was found for them;
and the stone that smote this great image, became a great mountain,
and filled the whole earth.
Dan. 2. xlv.

Is not this stone, that becomes a great mountain, that filleth the whole earth,
Christ Jesus?
And so through him the kingdoms of the world become the kingdoms of Christ.

Here you may see this stones or mountain that filleth the whole earth,
will dash to pieces, and grind to powder all that is not of its holy and pure nature,
and with its holy divine nature fill the whole earth.

The Lord saith,
'`They shall not hurt nor destroy in all my holy mountain.`'
Isaiah 11. And is not this holy mountain Christ,
who destroyeth the devil and his works, the destroyer?
'`And them that take hold of my covenant, saith the Lord,
even them will I bring to my holy mountain,`' etc.
Isa. 56:6-7, and chap.
ii. 2.

'`And he that putteth his trust in me,`' saith the Lord,
'`shall inherit my holy mountain.`' Isa. 57:13.
'`For thus saith the high and lofty One,
that inhabits eternity, whose name is Holy, I dwell in the high and holy place,
with him also that is of a contrite and humble spirit,
to revive the spirit of the humble,
and to revive the heart of the contrite ones.`' Isa. 57:15.
Therefore is it not good to wait upon the Lord,
and trust in him?
