== Concerning such as eat up God`'s people like bread, and such as make Idols and Images, and worship them, are without the true understanding, and are fools that hate knowledge; and such as go into Adultery and Uncleanness, are void of the wisdom of God, and true understanding; and God`'s fury is upon all such as do not call upon his name.

David saith, '`Have all the workers of iniquity no knowledge,
who eat up my people as they eat bread?`' Ps. 14:4. Here the workers of iniquity,
as they eat bread, they eat up God`'s people; that is, they devour them.
Are not these devourers men-eaters?

And again in Ps. 53:4. the Lord saith,
'`The workers of iniquity eat up my people like bread.
But God did give his people corn from heaven,
and man did eat angels`' food.`' Ps. 78:24-25. And David said, '`The wicked,
even mine enemies and my foes, came upon me to eat up my flesh,
they stumbled and fell.`' Ps. 27:2.

Here you may see these wicked men-eaters, and enemies of the righteous,
stumbled and fell, when they came to eat up the flesh of the righteous;
so they fell short of their devouring prey. Ps. 27:2.

Solomon saith, '`Whoso committeth adultery with a woman, lacketh understanding;
he that doth it, destroyeth his own soul; a wound and a dishonour shall he get,
and his reproach shall not be wiped away.`' Prov.
6:32-33. '`And they that want understanding,
the wicked woman draweth in; but he knoweth not that the dead are there,
and that her guests are in the chambers of hell.`' Prov. 9:16 to the end.

And therefore Job saith, '`The fear of the Lord, that is wisdom,
and to depart from evil is understanding.`' Job 28:28. And Solomon saith,
'`He that is slow to wrath, is of a great understanding; but he that is hasty of spirit,
exalteth folly.`' Prov. 14:29. '`And understanding is a well-spring of life to him
that hath it.`' Prov. 16:22. '`But the man that wandereth out of the way of understanding,
shall remain in the congregation of the dead.`' Prov. 21:16. '`Evil men understand
not judgment.`' Prov. 28:5. '`And the strange woman deceiveth the simple ones,
and the youth, who are void of understanding; her house is the way to hell,
going down to the chambers of death.`' Prov. 7. And therefore
it is good to keep and walk in the spirit of understanding,
by which you may depart from evil, and keep out of the snare of the whore,
and the congregation of the dead.

And the Lord said concerning the Jews that rebelled against his spirit,
'`My people are foolish, they have not known me, they are sottish children,
they have no understanding, they are wise to do evil,
but to do good they have no knowledge.`' Jer. 4:42.
Is not this the condition of many Christians,
as well as the Jews?

The prophet saith, '`Pour out thy wrath upon the heathen that know thee not,
and upon the families that call not upon thy name; for they have eaten up Jacob,
and devoured him, and consumed him,
and have made his habitation desolate.`' Must not God`'s fury come upon these men-eaters,
that eat Jacob the beloved of God, and devoured him, and made his habitation desolate. Jer. 10:25.
And David saith,
'`Pour out thy wrath upon the heathen that have not known thee,
and upon the kingdoms that have not called upon thy name; for they have devoured Jacob,
and laid waste his dwelling place.`' Ps. 79:6-7. God`'s
fury will be poured upon such that devour the righteous,
and lay waste his dwelling place.

And you may see in Jer. 51. "`They that are founders of graven images,
or molten images,`' are brutish by their knowledge, '`which are the works of error,
and shall perish.`' And the Lord saith, '`A drought is upon her waters, namely Babylon,
and they shall be dried up, for it is a land of graven images,
and they are mad upon their idols.`' Jer. 1:38.
Upon such God brings droughts and famine,
who disobey and forsake the living God,
and dote upon their idols and images which they make.
'`And the Lord frustrateth the tokens of liars, and maketh the diviners mad,
and turneth wise men backward,
and maketh their knowledge foolish.`' And hath not this been seen and fulfilled? Isa. 44:25.
And the Lord saith, '`They eat up the sin of my people,
and they set their hearts on their iniquity, and there shall be like priest like people,
and I will punish them for their ways,
and reward them for their doings.`' Hosea 4:8-9. And the Lord saith to Daniel,
'`The wicked shall do wickedly, and none of the wicked shall understand;
but the wise shall understand.`' Daniel 12:10.
The fear of the Lord is the beginning of wisdom,
and the secrets of the Lord are with them that fear him,
and the Lord taketh care for them that fear him,
as in Ex. 1:21. Therefore it is good to live in the fear of the Lord,
which ye must if ye would know his secrets.
