[#ch24.style-blurb, short="The Cause of Drought, Barrenness, Famine, and Plagues"]
== The cause of drought, and barrenness, famine and plagues, for disobeying the Lord, and grieving his Spirit.

The cause of drought, barrenness, and famine.
'`The Lord turneth rivers into a wilderness, and the water-springs into dry ground,
and turneth a fruitful land into barrenness,
for the wickedness of them that dwell therein.`'
Mark, it is for the wickedness of them that dwell therein.
Ps. 107:33-34.

And you may see them that disobeyed the Lord and forsook him,
and because of the wickedness of their doings,
the Lord will smite such with consumptions, and fevers, and blotches, and blastings,
and mildews, until they perish.
'`I will,`' saith the Lord, smite them with madness, and blindness,
and astonishment of heart, and the locust,
and the worms shall consume and devour their fruits;
and the heavens that are over thy head shall be as brass,
and the earth that is under thee shall be iron.
And the Lord will make the rain of thy land powder and dust;
and will smite thee with the blotches of Egypt, and with the emiroeds, scab,
and itch that thou canst not be healed.`' And this
is the portion of them that disobey the Lord,
and forsake him, as in Duet. 28. you may see more at large,
and how the curse followeth the wicked and disobedient, in city and field,
and upon themselves and their flocks, and the fruits of their lands, yea,
the plagues and the judgments that he poured upon Egypt,
he poureth upon them that disobey him, and grieve and rebel against his spirit.

And the Lord sent the prophet Gad unto David, when he caused Joab to number the people,
and said unto him, '`Shall seven years of famine come upon the land,
or wilt thou fly three months before thine enemies, whilst they pursue thee,
or that there be three days pestilence in thy land.`' 2 Sam. xxiv.
And did not this action of David bring death and
destruction of seventy thousand of the Jews,
through David`'s hearkening to the temptation of Satan, as in 1 Chron.
xxi. but David repented, and the Lord stayed the hand of the destroying angel,
that Jerusalem was not destroyed?

And did not the Lord call for a famine, and it came upon the land seven years?
as in 2 Kings 8:1. And was not this because of their wickedness?

And in Jer. 11:22. doth not the Lord there punish Judah for idolatry, and saith,
'`that his sons and daughters should die by famine.`' And in Jer.
14:12. there the Lord said to the Jews that disobeyed him,
'`When they fast I will not hear them, nor accept their offerings;`' but said,
'`I will consume them by famine, and by pestilence,`' etc.
And likewise you may see in Jer. 15. how the Lord
saith concerning the rebellious and disobedient Jews;
and for the wickedness of Manasses he threatened them with death, captivity, and famine, etc.
And likewise you may see in Jer. 18:21. how the Lord threatens famine
and judgments against the Jews for their revolting from the Lord;
and in Jer. 44:13. see how the Lord threateneth the disobedient by famine and pestilence.
And the Lord threateneth his plagues and judgments concerning Babylon, and saith,
'`A drought is upon the waters, and they shall be dried up;
for it is a land of graven images,
and they are mad upon their idols.`' And therefore let all that disobey the Lord,
and make graven images, and idols, and worship them, beware of these judgments. Jer. 1:38.
And Ezekiel,
he declareth the judgments upon Jerusalem for their rebelling against God,
how that they should die and be consumed with famine and pestilence,
in Ezek. 5:12. And likewise in Ezek. 6. you
may see the judgments upon Israel for their idolatry;
the Lord saith, he would '`pour his fury upon them,
and they should die by pestilence and famine.`' And the Lord saith,
'`he would leave a few of the Jews that should escape from the pestilence and famine,
and that these Jews that escaped might declare their own abominations
among the heathen.`' Ezek. 12:16. And in Isaiah 14. you may see how
the Lord threatened the Assyrians with famine and pestilence.
'`Thus saith the Lord, because of mine house that is waste, yea,
every man runneth to his own house, therefore the heaven over you is stayed from dew,
and the earth is stayed from her fruit; and I called for a drought upon the land,
and upon the mountains, and upon the corn, and upon the new wine, and upon the oil,
and upon that which the ground bringeth forth, and upon men, and upon cattle,
and upon all the labour of their hands.`' Haggai 1:10-11.

Here you may see the reason of the judgments of God,
because people mind their own houses, and business, and wills, more than the Lord`'s.

And did not the three years`' famine and six months come upon the children of Israel,
because of their turning from the Lord,
and rebelling against his law and spirit in the days of wicked Ahab and Jezebel,
who set up their idolatry, and persecuted and killed the Lord`'s people?
And did not the Lord shut up heaven,
that they had no rain nor dew for three years and six months in the land of Israel?
as in Luke 4:25. 1 Kings 17:9.

And you may see in Rev. 18. what plagues, and famine,
and judgments the Lord poureth upon the false church, mystery Babylon, the great whore,
that hath whored from the spirit of Christ, and killed the Lord`'s prophets,
and drunk the blood of the saints and martyrs, who sat as a queen; but plagues,
and judgments, and famine, and destruction is their end, with the dragon, beast,
and false prophets, and their followers.
And therefore let all be warned that rebel against the spirit of God,
and so turn from the Lord into sin and wickedness,
such cannot expect to escape these plagues and judgments, that God and his prophets,
Christ and his apostles, have pronounced against them in the holy scriptures of truth.
