== Concerning such as overcome the Beast, and Dragon, and Whore, and False Prophet.

Rev. 11:7.
'`The beast shall overcome the two witnesses of God,
and kill them.`' Rev. 13:7. '`And the beast shall make war with the saints,
and overcome them.`' Rev. 17:17. '`But the lamb
shall overcome the beast and his followers.`'
Rev. 13:21.
And Christ saith '`To him that overcometh
will I grant to sit with me in my throne,
even as I also overcame, and am set down with my Father in his throne.`'
Rev. 12:11.
'`And the saints overcame the dragon by the blood of the lamb,
and the word of their testimony, and they loved not their lives to the death.`'
Rev. 2:26-27.
'`And he that overcometh and keepeth my words unto the end,
to him will I give power over the nations, saith Christ,
and he shall rule them with a rod of iron;
as the vessels of a potter shall they be broken to shivers,
even as I received of my Father, and I will give him the morning star.`'
Rev. 2:7.
'`To him that overcometh will I give to eat of the tree of life,
which is in the midst of the paradise of God.`'
Rev. 2:10-11.
'`And be thou faithful unto death,
and I will give thee a crown of life;
and he that overcometh shall not be hurt with the second death.`'
Rev. 3:5.
'`And he that overcometh, the same shall be clothed in white raiment,
and I will not blot his name out of the book of life,
but I will confess his name before my Father, and before his angels.`'
Rev. 3:21.
'`And him that overcometh will I grant to sit with me in my throne,
even as I also overcame, and am set down with my Father in his throne.`'
Rev. 2:17.
'`And him that overcometh will I give to eat of the hidden manna,
and will give him a white stone, and in the stone a new name written,
which no man knoweth, saving he that receiveth it.`'
Rev. 3:10.
And Christ saith, '`thou hast kept the word of my patience,
I will keep thee from the hour of temptation, which shall come upon all the world,
to try them that dwell upon the earth.`'
Rev. 3:13.
'`And him that overcometh will I make a pillar in the temple of my God,
and he shall go no more out, and I will write upon him the name of my God,
and the name of the city of my God, and I will write upon him my new name.`'
Rev. 21:7.
'`And he that overcometh shall inherit all things, and I will be his God,
and he shall be my son.`'

But the dragon and the beast, the false prophet and their followers,
and the false church that maketh war with the lamb and the church of Christ the saints,
these say, that there is no overcoming of them while they live upon the earth,
but the beast, false prophets, and the whore, and the dragon must have the victory;
and the lamb and the saints must not have the victory;
and the kingdoms of the world must not become the kingdoms of Christ; this is the beast,
and the whore, and the false prophets`', and the old dragon`'s, the devil`'s,
and Satan`'s false doctrine;
but the lamb and the saints shall have the victory over them all.

Isaac said, that when Esau had broken Jacob`'s yoke from off his neck,
then Esau should have the dominion, and this Isaac spoke by prophecy,
in Gen. 27:40. and was fulfilled in Jehoram`'s days. 2 Chron. 21:4-5.
8+++.+++ For then the Edomites made themselves a king,
and this Jehoram compelled Judah to his false worship, and to forsake God`'s worship. 2 Chron. 21:11.

David saith, '`O Lord preserve my life from the fear of the enemy,
and hide me from the secret council of the wicked,
and from the insurrection of the workers of iniquity, who whet their tongue like a sword,
and bend their bows to shoot their arrows, even bitter words.`' Ps. 64:2-3.

G+++.+++ F.

