== A distinction between the two suppers of Christ; namely, the last supper in the same night that he was betrayed, before he was crucified; and the supper after he was risen and ascended at the right hand of God, which he calls people to in Rev. 3. To hear his voice, and open the door, and he will sup with them, and they shall sup with him.Likewise, something concerning Christ, the resurrection of the just and unjust.And also, concerning the stone cut out of the mountain without hands, which smote the image.
Dan. 2.And concerning Christ, the vine, and the Jews,
how that God planted them a noble vine, but they degenerated,
and destroyed the Lord`'s servants, and son, that came to look for fruits.
By G. F.

It is said in Matt. 26. and Mark 14. and Luke 22. and 1 Cor, xi.
'`In the same night that Christ was betrayed, he took the bread and the cup,
etc. and said, '`As often as ye do eat this bread, and drink this cup,
do it in remembrance of me;
and ye do show forth the Lord`'s death until he come.`' And Christ saith,
'`I say unto you, I will drink henceforth no more of this fruit of the vine,
until that day that I drink it new with you in my Father`'s kingdom.`' Matt. 26:29,
and Mark 22:16. And Christ said, when he was at his last supper, when he was betrayed,
before he was crucified, '`I say unto you, (namely,
his disciples,) I will not any more eat thereof, (namely,
of the bread of the passover,) until it be fulfilled in the kingdom of God.`'

Now mark, the fruit of the vine, and the bread which Christ broke at his last supper,
and gave to his disciples in the same night that he was betrayed,
before he was crucified, which they were to take in remembrance of his death,
and show forth his death until he came; that after they had eat of that outward bread,
and drunk of that outward cup, the fruit of the vine, which he gave to his disciples,
henceforth he would eat no more thereof, (namely,
the bread,) until it was fulfilled in the kingdom of God,
and drink no more of the fruit of the vine,
until the day that he drink it new in the kingdom of God,
(Matt. 26. Mark 14.) as Christ said this unto his disciples, at his last supper,
before he was crucified.
But after Christ was crucified, buried, and rose again,
he did eat and drink again with them, as ye may see in these scriptures following,
which did fulfill his own words,
as in Luke 24:30. '`And it came to pass as Jesus sat at meat with them, he took bread,
and blessed it, and broke it, and gave it to them,`' namely, to some of his disciples;
and they said unto others of them, '`the Lord is come;
and he was known to them by breaking of bread,`' as in ver. 35. And ver. 41-43,
Jesus appeared unto his disciples again, and he said unto them, '`Have ye any meat?
and they gave him a piece of broiled fish and honey-comb, and he took it,
and did eat before them; and he said unto them,
These are the words which I spake unto you, while I was yet with you,
that all things must be fulfilled,`' etc.

And again, Jesus said unto his disciples, after he was risen, John 21:5. 9. '`Children,
have ye any meat?`' they answered, no.
And as soon as his disciples were come to land, they saw a fire of coals there,
and fish laid thereon, and bread; and Jesus said unto them,
'`Come and dine;`' and Jesus took bread, and gave to them, and fish likewise:
And this was the third time that Jesus showed himself to his disciples,
after he was risen from the dead, as in John 21:12-13. And Christ,
after he was risen from the dead, he told his disciples,
'`All power in heaven and earth was given unto him.`' And
Christ said unto his disciples whom he sent forth to preach,
before he was crucified, '`Verily, I say unto you,
ye shall not have gone over the cities of Israel,
until the son of man be come.`' Matt. 10:23.

And again, Christ said unto his disciples, '`I tell you of a truth,
there be some standing here,
which shall not taste of death until they see the
son of man coming in his kingdom.`' And again,
Christ saith, '`Verily, I say unto you,
there be some standing here which shall not taste of death,
until they have seen the kingdom of God come with
power.`' Matt. 16:28. Mark 9:1. Luke 9:27.

And the apostle saith, Acts 10:41. that they, did '`eat and drink with Christ,
after that God had raised him up from the dead.`' And so they fulfilled Christ`'s words,
that he would eat no more of the bread, nor drink of the fruit of the vine,
until he drank it new with them in the kingdom of God. Mark 14:25.
And again, Christ said, '`There are some standing here,
which shall not taste of death until they see the son of man coming in his kingdom
and power.`' Matt. 16:28. And was not this fulfilled after Christ was risen,
when he said,
'`All power in heaven and earth is given unto me.`' Then did not he come in power,
and did not the disciples see him in his kingdom, after his resurrection?

And John, he that was one of Christ`'s beloved disciples,
that leaned upon his breast in the same night that Christ was betrayed,
before he was crucified,
did not John then take the elements of bread and wine at that last supper?
And was not John one of the disciples that did not taste death
till he saw Christ come in the kingdom of his Father with power,
when Christ said,
'`All power in heaven and earth is given unto me?`' And was not John one
of the disciples that did eat and drink with Christ after he was risen?
And after that Christ was ascended, and sat at the right hand of God,
and the churches were gathered,
as yet they were not come off many outward elementary things.
And did not Christ send John, after he was ascended,
to call the church to another supper, and said, '`Behold, I stand at the door and knock:
if any man will hear my voice, and open the door, I will come in to him,
and will sup with him, and he with me; he that hath an ear to hear,
let him hear what the spirit saith unto the churches.`'

Now they that come to this inward and heavenly supper, and to sup with Christ,
the heavenly and spiritual man, the second Adam, the Lord from heaven,
since he is risen and ascended,
they must have their spiritual ear to hear the spiritual voice of Christ,
and his spiritual knocking at the door of their immortal souls and hearts,
and with his spirit, the spiritual man, the second Adam, the Lord from heaven,
the king of glory, that he may come into their hearts and souls,
and then they to sup with him, and he to sup with them the spiritual and heavenly supper.
And to this heavenly and spiritual supper did Christ send John,
to call the church of Christ, after he was risen and ascended.
And John said, when Christ sent him with this message, to call the church to this supper,
'`I John, am your brother,
etc. in the kingdom and patience of Jesus Christ.`' So here you may see,
John was in the kingdom and patience of Christ,
when he called the church to this heavenly spiritual supper of Christ,
after Christ was ascended at the right hand of God; which spiritual supper,
after Christ was ascended, is beyond,
and a higher supper than the last supper the same night that Christ was betrayed,
of taking the elements of bread and wine in remembrance Of Christ`'s death,
and a show of his death till he come.
And had not John taken that supper?
And was not the kingdom of God come, when John said,
'`he was in the kingdom and patience of Jesus Christ?`' Rev. 1:9. chap.
iii. 20. John tells you, Christ is come, and Christ saith,
'`Behold I stand at the door and knock,
(then is not he come?) and if any man will hear my voice, and open the door,
I will come in to him, (mark, into him,) and I will sup with him,
and he with me.`' And doth not the apostle say, '`Prove yourselves, examine yourselves,
know ye not your own selves, how that Jesus Christ is in you,
except you be reprobates.`' 2 Cor. 13:5.

And may not reprobates take the elements of bread
and wine in remembrance of Christ`'s death,
and say, they will do it till Christ come; yet Christ saith, '`Behold,
I stand at the door and knock, (so then he is come,) and if any man will hear his voice,
and open the door, he will come in to them, and sup with them, and they with him.`'

And cannot reprobates be sprinkled with the element of water,
and take the elements of bread and wine?
And Christ, that is ascended at the right hand of God, saith, '`Behold,
I stand at the door and knock; and though he is come, and stands at the door and knocks,
yet they will not open the door, and hear his spiritual voice,
that he might come in to them, and sup with them, and they with him, as is said before.
And such will not open the spiritual ear to hear
what the spirit saith to the church of Christ;
for they must have the spiritual ear that let in Christ, when he stands at the door,
and knocks at the door of their hearts, to hear his spiritual voice,
and to sup with the spiritual man at his spiritual supper, after Christ is ascended.
And they that hear not the spiritual voice of Christ,
when he stands at the door and knocks, are such as err from the spirit of God,
and faith of Christ, and hate his light, and go from the grace and truth in their hearts;
and such do not come to the heavenly supper of Christ, that he calls to,
now after he is ascended, that will not hear his voice, nor open the door by his grace,
light, spirit, and truth, but their dark spirit leads them to live in weak elements,
outward things which perish with the using, and which keep them in bondage. Gal. 4:9.
Col. 2:22.

And the angel said unto John,
'`Blessed are they which are called to the marriage supper of the lamb.
This is the spiritual marriage supper of the lamb,
which the true christians were called to,
after Christ was risen and ascended.`' Rev. 19:9. For
they that are come to this marriage supper of the lamb,
are married to Christ, the second Adam, the Lord from heaven.
And these are they that hear his spiritual voice, and he is come into them,
and suppeth with them, and they with him; and this is the marriage supper of the lamb,
that taketh away the sins of the world, and they that come to it are blessed.
For reprobates may take the outward elements of bread
and wine in remembrance of Christ`'s death,
till he comes, as they say; and yet he stands at the door of their hearts and souls,
and knocks, after he is risen and ascended at the right hand of God,
and they will not let him in, nor hear his voice; and the apostle tells them, in 2 Cor.
xiii.
'`they are reprobates if they know not Christ in them.`'

And here you may see now, that Christ called his followers to this marriage supper,
after he was risen and ascended into heaven, at the right hand of God;
and is not this the last supper that Christ called his people to, after he was ascended,
namely, the marriage supper of the lamb; yea,
such that had taken the elements of bread and wine with Christ at his last supper,
the same night that he was betrayed, before he was crucified,
in remembrance of his death till he come.
And John, who was one that took it in remembrance of his death till he came, said,
in his first epistle, chap.
v. 20. after Christ was risen and ascended, '`We know that the son of God is come,
and hath given us an understanding, that we may know him that is true,
and we are in him that is true, even in his son Jesus Christ, (mark,
in him,) and this is the true God,
and eternal life.`' And this John spake after Christ was risen and ascended.
He that hath an ear to hear, let him hear.

And Jesus Christ said, '`If any man love me, he will keep my words and sayings;
and he that hath my commandments, and keepeth them, it is he that loveth me;
and he that loveth me, shall be loved of my Father, and I will love him,
and will manifest myself to him.
I go to my Father, but ye shall see me; and because I live, you shall live also.
Ye shall know that I am in my Father, and you in me, and I in you;
and he that keepeth my words, my Father will love him, and we will come unto him,
and make our abode with him.`' John 14.

And the apostle saith to the Colossians,
'`God hath delivered us from the power of darkness,
and hath translated us into the kingdom of his dear son.`' Mark,
into the kingdom of his dear son.
And this he said while they were upon the earth, and after Christ was risen and ascended.
And John said, '`that he was in the kingdom and patience of Jesus Christ,
while he was upon the earth.`' Rev. 1:9. Col. 1:13.

And the Colossians were not converted, when he took bread and wine,
and gave to his disciples at his last supper, the same night he was betrayed.
And were not they that were translated into the kingdom of Christ Jesus,
come to the marriage supper of the Lamb?
And Christ supped with them, and they with him;
and sat together in the heavenly places in Christ Jesus, as in Eph. 2:6.

Here you may see a distinction betwixt the last supper
the same night that Christ was betrayed,
before he was crucified, and the heavenly marriage supper of the Lamb,
that Christ calleth people to,
after he was ascended into heaven at the right hand of God.

And John saw an angel standing in the sun, and he cried with a loud voice, saying,
to all the fowls that fly in the midst of heaven,
'`Come and gather yourselves together unto the supper of the great God,
that ye may eat the flesh of kings, and the flesh of captains,
and the flesh of mighty men, and the flesh of them that sit on horses,
and the flesh of all men, both free and bond, both small and great.`' Rev. 19:17-21.

Now, all you that will not open the door of your souls and hearts,
at which door Christ stands and knocks, nor hear his spiritual voice, to let him in,
that he might sup with you, and you with him, the blessed marriage supper of the lamb,
slain from the foundation of the world; I say to you all, take heed,
both great and small, high and low, free and bond,
lest Christ do not make of you a supper for the fowls to eat your flesh,
and be filled with it, as in Rev. 19.;
for they are not blessed that the fowls make a supper of,
but they are blessed that are called, and come to the marriage supper of the lambs.
And they that are a supper for the fowls, do not eat the flesh of Christ,
nor drink his blood, the bread from heaven; and such have no life in them,
and so will not come to Christ that they may have life, but live in outward elements. John 5:40.
But whosoever eateth the flesh of Christ, and drinketh his blood,
which is the living bread that cometh down from heaven, hath everlasting life.
And again, Christ saith, '`He that eateth my flesh, and drinketh my blood,
dwelleth in me, and I in him.`' And these are they that are blessed,
and come to the marriage supper of the lamb, and Christ sups with them,
and they with him,
since his resurrection and ascension into heaven at the right hand of God,
the heavenly and spiritual supper of the lamb, and come to be members of his body,
of his flesh, and of his bone.
John 6. Eph. 5:30.

Now concerning them that say,
'`The bread and the wine that Christ took and gave his disciples, and said,
as often as ye do eat this bread, and drink this cup, do it in remembrance of me,
showing forth the Lord`'s death till he come,`' as in Matthew, Mark, Luke 1 Cor.
etc. they that say that this outward bread, and the wine, the fruit of the vine,
is the very body and blood of the Lord Jesus Christ,
and whosoever receiveth and eateth it, receiveth and eateth the Lord Jesus Christ,
after the priest have consecrated it; in this they may see their error that do say so,
and hold this doctrine; for the apostle saith, '`Ye that do eat this bread,
and drink this cup, ye do show forth the Lord Jesus Christ`'s death,
till he come.`' Then it is clear, the bread and the cup is not the Lord Jesus Christ;
and the Lord Jesus Christ is not come when they eat this bread, and drink this cup;
for while they are eating the bread, and drinking of the cup,
they are showing forth the Lord`'s death till he come.
Then he is not come;
for they take the bread and cup '`in remembrance of the Lord`'s death,
and to show forth his death till he come.`' So it is clear,
the cup and the bread is not the Lord Jesus Christ, as in 1 Cor. 11:24. 26.

And again, the apostle saith, '`In the same night that Christ Jesus was betrayed,
he took bread and brake it, and said, do it in remembrance of me,
and likewise the cup.`' So Christ`'s body was whole, and was not crucified,
when he brake that outward bread;
for that which they were to take in remembrance of Christ,
and in a show of his death till he came, it was not the Lord Jesus Christ,
but outward bread and wine in an outward cup.
And Christ was nowhere called a cup, it is said,
'`Christ took the cup when he had supped.`' Then
he did not take his own blood and give unto them,
but he called it,
'`the fruit of the vine.`' Matt. 26:29. And Christ '`took the cup and gave his disciples,
and said, drink ye all of it; and took the bread, and brake it,
and gave it to his disciples also.`' And in Mark 16:22. '`They all drank of the cup,
and he brake the bread and gave it to his disciples,`' (namely,
the twelve,) as in Luke 22. And after he had broken it, and given it them,
and given them the cup,
and called it '`the fruit of the vine,`' after Christ had given them this, he said,
'`Drink ye all of this.`' Matt. 26:25. Luke 22:21. '`Behold,`' saith Christ,
'`the hand of him that betrayeth me,
is with me on the table.`' So it seems here that Judas did eat of the bread,
and drink of the fruit of the vine in the cup,
and he did partake of these outward elements in the same night that Christ was betrayed,
which elements were taken in a show and remembrance of the Lord`'s death till he came.
But Judas did not stay till he came, for he betrayed him.
Now if this outward bread and outward wine had been Christ,
the living bread that came down from heaven, and his blood,
which if any man did eat of that bread, and drink his blood, he shall live forever,
and not die, as Christ saith, '`Whoso eateth my flesh, and drinketh my blood,
hath eternal life, and dwelleth in me, and I in him; and he that eateth me,
shall even live by me; and he that eateth this bread that comes down from heaven,
shall live forever.`' See John 6:50 to 59.

Now here you may see, it is clear,
that the cup and bread that Judas did eat and drink of at the last supper,
was not the flesh of Christ, or bread of life that came down from heaven,
nor his blood that giveth life everlasting; for Judas had not eternal life,
nor did not live forever by eating that outward bread, and drinking of that outward cup,
the fruit of the vine.

And so, Judas did not eat Christ and live by him, and live forever,
though he drank of the outward cup, the fruit of the vine,
and eat of the outward bread that Christ brake at his last supper,
the same night that he betrayed him; and that Judas might do,
and not eat the bread from heaven, the flesh of the son of man, and drink his blood,
for such have not life eternal in them, as Christ saith,
that '`do not eat his flesh and drink his blood;`' for Christ said,
'`Except ye eat the flesh of the son of man, and drink his blood,
ye have no life in you.`' John 6:53. And the Jews murmured at Christ, when he said,
'`I am the bread that came down from heaven;`' and
'`except ye eat my flesh and drink my blood,
ye have no life in you.`' And '`he that eateth my flesh, and drinketh my blood,
hath eternal life.`'

So here is a great difference betwixt the flesh and the blood of Christ,
or the bread which came down from heaven, which giveth life eternal,
and the elements of bread and wine, which reprobates and Judas`'s may take and eat,
that have not life eternal, nor Christ in them, as the apostle saith,
'`If Christ be not in you, ye are reprobates.`'

And here you may bee a distinction betwixt the baptism of John,
with his element of water, which must decrease, a forerunner of Christ`'s baptism,
which doth increase; who came after John, who baptizeth with fire,
and with the holy ghost; who cometh with his fan,
and thoroughly purgeth the floor of the heart from sin and corruption,
and burneth up the chaff with unquenchable fire.
And this fire that is unquenchable, is above the natural fire that may be quenched.
And Christ gathereth his wheat into his garner,
into which garner the devil with his foul spirit, nor none of his vermin, his followers,
can come to hurt God`'s seed or wheat.

And all men and women must come to this baptism of Christ,
who baptizeth with unquenchable fire and the holy ghost,
before ever they know the wheat or the seed of God come into God`'s garner;
for John who said, he must decrease, his baptism with outward elementary water,
doth not bring the wheat, the seed of God, into God`'s garner.

And the apostle said,
'`he thanked God that he had baptized none of the Corinthians
but Crispus and Gaius,`' etc. for he said,
'`Christ sent him not to baptize, but to preach the gospel,
(1 Cor. 1:14. 17.) not with the wisdom of words,
lest the cross of Christ should be made of none effect.`'

And John the Baptist was prophesied of by Isaiah, before his coming, Isaiah 40:3.
'`I indeed baptize you with water unto repentance,
but he that cometh after me, is mightier than I,
whose shoe latchet I am not worthy to unloose; he shall baptize you with the holy ghost,
and with fire; whose fan is in his hand, and he will thoroughly purge his floor,
and gather his wheat into his garner,
but he will burn up the chaff with unquenchable fire.`' Matt. 3:11-12.
Mark 1:9. Luke 3:21. And John said,
'`He that hath the bride, is the bridegroom; he must increase,
but I must decrease.`' And John further speaketh of Christ, and saith,
'`He that is from above, is above all.`' And again, '`He that cometh from heaven,
is above all.`' John 3:29-31. So John confesseth Christ was greater that he,
and came after him, who must increase, and was mightier than he,
and preferred before him, for he was before him.
And indeed Christ is preferred before John 1n his birth, in his miracles, in his offices,
and in his death,
who '`by the grace of God tasted death for every
man,`' and was mightier than John in his birth,
who was conceived by the holy ghost, and in his power,
who hath '`all power in heaven and earth given unto
him.`' So he was preferred before John;
for he was before him, for all things were made and created by Jesus Christ,
whose name is called the '`word of God.`' John i.

And when Christ came to be baptized of John, John forbade him, saying,
'`I have need to be baptized of thee, and comest thou to me?`' And Jesus said unto him,
'`Suffer it to be so now,
for thus it becometh us to fulfill all righteousness;`' then he suffered him. Matt. 3:13-15.
So here,
John knew that himself must be baptized with Christ`'s baptism, with fire,
and with the holy ghost, before the seed of God, the wheat,
be gathered into God`'s garner.
And John answered the Pharisees, when they questioned him, and said,
'`I baptize you with water; but there standeth one amongst you, whom you know not,
he it is that cometh after me, which is preferred before me,
whose shoe latchet I am not worthy to unloose.`' And John seeing Christ come unto him,
said,
'`Behold the lamb of God which taketh away the sins
of the world.`' This is he of whom John said,
'`After me cometh a man which is preferred before me, for he was before me;
and that he should be made manifest to Israel;
therefore came I baptizing with water.`' John 1:27 to 31.

Here you may see, John clearly declareth for what end he was sent to baptize with water,
namely, that Christ might be made manifest to Israel, the Jews,
that had the figures and shadows of Christ; for John doth not say,
be came baptizing with water,
that Christ might be made manifest to the Gentiles or heathen, but to Israel.
For the apostle Paul said to the Corinthians, '`he was not sent to baptize, (namely,
with the element of water,) but to preach the gospel;`' for the
apostle thanks God that he baptized none of the Corinthians,
but two or three, that he mentions in 1 Cor.
i. And he tells the Corinthians,
(which were the Gentiles,) '`By one spirit are we all baptized into one body,
whether we be Jews or Gentiles, whether we be bond or free,
and have been all made to drink into one spirit.`' 1 Cor. 12:13.

So this was the spiritual baptism of Christ that
the apostle brought both Jews and Gentiles into.
Then surely the apostle Paul must see the decreasing
of John`'s baptism with elementary water,
who brought them to the spiritual baptism.

And the apostle Paul writeth to the Ephesians, and exhorts them,
'`to keep the unity of the spirit in the bond of peace;`' and saith '`There is one body,
and one spirit, etc. and one Lord, and one faith, and one baptism,
and one God and Father of all, who is above all, and through you all,
and in you all.`' Eph. 4:3-6.

So God was in them all, and through them all, by his spirit; and this was the one Lord,
and one faith, and one baptism,
that the apostle brought the church of Christ the Ephesians to,
which was not John`'s baptism, with elementary water,
but Christ`'s baptism with the holy ghost, which burned up the chaff,
by which God`'s wheat, or seed was gathered into his garner.
Surely these Ephesians had their wheat, or seed, gathered into God`'s garner;
for the apostle saith,
'`they sat together in heavenly places in Christ
Jesus.`' Eph. 2:6. And these were not Jews,
but Gentiles.
And if John`'s decreasing baptism, with elementary water, had been Christ`'s baptism,
then the apostle would not have thanked God he baptized none but these few;
nor have said, that Christ did not send him to baptize with water,
but to preach the gospel, as in 1 Con xiv.
16, 17. but it is clear,
the apostle did bring the church of Christ to the one spiritual baptism of Christ Jesus.

And the apostle saith in Acts, how John first preached before the coming of Christ,
the baptism of repentance to all the people of Israel; he doth not say,
to all the Gentiles.
And as John had fulfilled his course, (mark, his course,) of baptism, he said,
'`Behold there cometh one after me,
whose shoes of his feet I am not worthy to unloose.`' Acts 13:24-25.

Now, mark, as John had fulfilled his course of elementary water baptism,
John saith of himself,
that '`he must decrease.`' Then Christ`'s baptism came in with the holy ghost,
and with fire, which doth increase; by which holy ghost and fire, the sin and corruption,
which is chaff, is burned up, and God`'s wheat and seed is gathered into his garner.
And also, Christ is the true and heavenly baptizer,
with his heavenly unquenchable fire and holy spirit.

And Christ commanded his disciples, '`that they should not depart from Jerusalem,
but wait for the promise of the Father.`' And further said,
'`For John truly baptized with water,
but ye shall be baptized with the holy ghost not many days hence, (mark,
not many days hence,) and ye shall receive power
after that the holy ghost is come upon you,
and ye shall be witnesses unto me, (namely, Christ, who baptizeth with fire,
and with the holy ghost,) both in Jerusalem, and Judea, and in Samaria,
and unto the uttermost parts of the earth.`' Acts 1:4 to 8. And
in Acts 2. the apostles being met together at Jerusalem,
they were all filled with the holy ghost.
Here Christ`'s words were fulfilled in them, and upon them, who said,
that '`John baptized with water,
but ye shall be baptized with the holy ghost not many days hence;`' which came to pass,
(Acts 2.) and they were witnesses of Christ, both in Judea and Samaria,
and to the Gentiles, etc.

And the apostle came to Ephesus, and finding certain disciples, he said unto them,
'`Have ye received the holy ghost since ye believed?
And they said unto him,
we have not so much as heard whether there be any holy ghost.`' And he said unto them,
'`Unto what then were ye baptized?`' And they said,
'`Unto John`'s baptism.`' Then said Paul,
'`John verily baptized with the baptism of repentance, saying unto the people,
that they should believe on him that should come after him; (that is, on Christ Jesus,
etc.) and when Paul had laid his hand on them, the holy ghost came upon them.`' Acts 19.

Here you may see the baptism of John, with his elementary water,
was not the baptism of Christ with the holy ghost;
for they that baptized with John`'s baptism, said,
'`We have not so much as heard whether there be any holy ghost.`' Then
they were not like to know the baptism of Christ with the holy ghost.
But when the apostle Paul laid his hands upon them, the holy ghost came upon them,
then they were baptized with the holy ghost.

And while Peter spoke to Cornelius`'s family,
the holy ghost fell upon them which heard the word that he preached. Acts 10:44.
So the holy ghost was given through the preaching of the word Christ,
and the holy ghost doth baptize them;
through which baptism the wheat or seed of God is gathered into God`'s garner.

And Saul, who had been a persecutor of God`'s people, and was struck blind,
and Ananias went to him, and laid his hands upon him, and said,
'`The Lord Jesus sent me to thee, that thou might receive thy sight,
and be filled with the holy ghost.`' Acts 9:11 to 18. which came to pass unto Paul,
who did receive his sight.
And was not he baptized by the holy ghost, who was filled with it?
And then after, did not he bring others to the same spiritual baptism,
and called Jesus Lord by the holy ghost, and bore witness to Christ,
both among Jews and Gentiles?
And the apostles laid their hands upon the Samaritans that believed in Christ;
and through the laying on of the apostle`'s hands,
the holy ghost was given to the Samaritans,
when they had prayed that they might receive the holy ghost.
And Simon Magus proffered the apostles money to buy their gift;
but they sharply rebuked him, and said,
'`Thy money perish with thee,`' because he thought
the gift of God might be purchased with money;
and told him, '`that he was in the gall of bitterness, and in the bond of iniquity,
and bid him repent,`' etc.
Acts 10:15 to 24.

Now were not these Samaritans,
that received the holy ghost by the apostles`' laying hands on them,
baptized by the holy ghost?
And the holy ghost said, '`Separate me Barnabas and Paul,
for the work whereunto I have called them.`' So they being sent forth by the holy ghost,
departed and preached the word of God. Acts 13:2.
4.

Here you may see,
it was the holy ghost that fitted Paul and Barnabas for the work whereto they were called,
and sent them forth to preach Christ Jesus.

And Stephen said to the outward professing high priests and Jews, their council,
'`Ye stiff-necked, and uncircumcised in hearts and ears! ye always resist the holy ghost;
as your forefathers did, so do ye.`' Acts 6:15. chap.
vii. 1. 51. And may not the same be said of many that are called christians,
that live in an outward profession of the letter of the scripture,
and some outward elements of bread, wine, and water, and outward shows and signs?
And how can such as resist the holy ghost, as their forefathers did,
come to be baptized by the holy ghost, and by unquenchable fire,
(which is the baptism of Christ,) and have their sins and corruptions burned up,
that chaff, and their wheat gathered into God`'s garner?

And some came unto John, and said, '`He to whom thou bearest witness, behold,
the same baptizeth,
and all men come to him.`' And '`the Pharisees heard that
Jesus made and baptized more disciples than John,
though Christ himself baptized not`' with water; for Christ baptized with the holy ghost,
and with unquenchable fire, as John bore witness of his baptism, John 3:26. chap.
iv. 1, 2. And from that time John was cast into prison, Jesus came into Galilee,
preaching the gospel of the kingdom of God, and saying, '`The time is fulfilled,
the kingdom of God is at hand, repent ye,
and believe the gospel.`' Mark 1:14-15. Matt. 4:12. 17. So here you may see,
Christ preaches a higher doctrine than John,
and cometh with a greater baptism after John.

And the apostle saith to the Romans,
'`that so many of us as were baptized into Jesus Christ,
were baptized into his death.`' Mark, they were baptized into Christ Jesus and his death.
Then that must be by the holy ghost; and therefore the apostle saith,
'`We are buried with him by baptism into death,
that like as Christ was raised up from the dead by the glory of the Father,
even so we also should walk in the newness of life.`'
So they that come out of this death by baptism,
walk in newness of life; and this baptism into Christ and his death,
is not the baptism of John, with his outward elementary water.
The apostle saith, '`If we have been planted together in the likeness of Christ`'s death,
we shall also be planted in the likeness of his resurrection.`' Rom. 6:3-5.
And the apostle saith, 1 Cor. 10:12.
'`that all our father`'s were under the cloud,
and all past through the sea, and were all baptized unto Moses in the cloud,
and in the sea.`' Mark, unto Moses in the cloud, and in the sea, they were all baptized. Ex. 13:21.
and chap.
xiv. 21. '`The Lord caused the sea to go back by a strong east wind all that night,
and made the sea dry land,
and the children of Israel went into the midst of the sea upon dry ground,
and the waters were a wall unto them on their right hand,
and on their left.`' Here you may see, though it is said they were baptized in the cloud,
and in the sea unto Moses, yet they went upon dry land, or ground,
and the waters did not touch them.

But the apostle brings the same Corinthians to the baptism of the spirit, and saith,
'`We are all baptized into one body, whether Jews or Gentiles, whether bond or free,
and have been all made to drink into one spirit.`' This is Christ`'s spiritual baptism,
which is beyond John`'s with the element of water, which was to decrease.
And the apostle saith, '`he was not sent to baptize,
but to preach the gospel.`' And the apostle saith,
'`For as many as have been baptized into Christ, have put on Christ.
There is neither Jew nor Creek, bond nor free, male nor female;
for ye are all one in Christ Jesus.`' Gal. 3:27-28. Mark,
they that have been baptized into Christ, are all one in him, and have put on Christ.
And this baptism is not into outward elementary water;
for the spiritual baptism brings to put on Christ, the heavenly man,
and makes all one in him.
Heb. 6. So it is clear, the apostle brought people off the doctrine of many baptisms,
to the one faith, and one spiritual baptism,
as in Eph. 4:5. And by this one spirit were all to be baptized into one body,
and so to drink all into one spirit,
and in that they have unity and fellowship with the Father,
and with his son Jesus Christ, and one with another. 1 Cor. 12:13.
1 John 1:3. The Lord bring all people into this spiritual baptism,
and into this fellowship.
Amen.

G+++.+++ F.

=== Postscript

Christ saith, '`It is written, behold I send my messenger before thy face,
which shall prepare thy way before thee.`' And Christ saith, '`Verily I say unto you,
amongst those that are born of women,
there is not a greater prophet than John the Baptist;
but he that is least in the kingdom of God, is greater than John;
for all the prophets and the law prophesied until John.
Since that time, the kingdom of God is preached, and every man presses into it.
This is that Elias which was to come, (namely,
John,) he that hath an ear to hear let him hear.`'
Matt. 11:10 to 15. Luke 7:17 to 28. chap.
xvi. 16. And Christ said unto his disciples, '`But Elias is come already,
and they knew him not, but have done unto him whatsoever they listed.
Likewise shall also the son of man suffer by them,`' (namely, the Jews,
etc.) And Christ`'s disciples understood that this Elias that was come already,
was John Baptist, whom the Jews and Herod had done unto whatever they listed. Matt. 17:12.
So you may see here, the least in the kingdom of God,
is greater than John.
And since the time of John, the kingdom of God hath been preached, and men press into it,
and the least in the kingdom of heaven is greater than John.
And the apostle said, '`God hath delivered us from the power of darkness,
and hath translated us into the kingdom of his dear
son.`' Col. 1:13. And Rev. 1:9,
'`I, John, who am your brother,
and in the kingdom and patience of Jesus Christ.`' So those
that were in the kingdom and patience of Jesus Christ,
were greater than John the Baptist.

And all those that do grieve and vex the spirit of God, and err from it,
and rebel against it, are such as do resist the holy ghost, whether they be Jews,
or Gentiles, or Christians, or bond, or free;
though they may make a profession of the letter of the scripture,
and some outward shows and signs of some outward elementary things,
they are not like to be baptized with the holy ghost, that do resist the holy ghost,
and therefore the wheat or seed of God is not like to be gathered into God`'s garner;
'`for none can call Jesus Lord,`' as the apostle saith,
'`but by the holy ghost.`' And by that holy ghost, and the unquenchable fire,
(which is above the natural fire that may be quenched,) are all they,
who have their wheat gathered into God`'s garner, baptized;
and all such have communion and fellowship in the holy ghost.

G+++.+++ F.
