== Concerning Christ, the resurrection of the just and unjust.

Christ saith to Martha, '`Thy brother Lazarus shall rise again.`' Martha said unto Jesus,
'`I know he shall rise in the resurrection at the last day.`' Jesus said unto Martha,
'`I am the resurrection and the life, he that believeth in me, though he were dead,
yet shall he live.`' Mark, though be were dead, yet shall he live,
that believeth in Christ; he shall live forever, he hath eternal life,
as in John 11:23-26. And again, Jesus saith, '`Whosoever liveth and believeth in me,
shall never die.`' Christ said, '`Believest thou this, Martha?
She said unto him, Yea, Lord.`' Mark, who liveth and believeth in Christ,
shall never die, but have eternal life, and are grafted into Christ,
them that live and believe; and though we were dead, he that believeth in Christ,
yet shall he live.
And Christ said, '`As I live by the Father,
so he that eateth me shall live by me.`' John 6:57. And Jesus said, '`Verily,
I say unto you, he that heareth my word, and believeth on him that sent me,
hath everlasting life, and shall not come into condemnation,
but hath past from death unto life.`' Mark,
such believers as these are passed from the death in Adam, to the life in Christ,
and have everlasting life in him.
And again, Jesus said, '`Verily, verily, I say unto you, (namely,
the Jews,) the hour is coming, and now is, (mark,
and now is,) when the dead shall hear the voice of the son of God,
and they that hear shall live.`' Mark, they that hear shall live.
'`Marvel not at this, for the hour is coming,
in which all that are in the grave shall hear the voice, (mark,
the voice,) of the son of God, and shall come forth, they that have done good,
unto the resurrection of life, and they that have done evil,
unto the resurrection of damnation.`'

So here you may see, the resurrection of them that have done good, to life,
them that have done evil, to damnation. John 5:25.
29. and Matt. 25:46, '`The wicked shall go into everlasting punishment,
but the righteous into life eternal.`' Christ saith,
'`the Father hath given him authority to execute judgment, because he is the son of man.
The Father hath committed all judgment unto the son,
and all power in heaven and earth is given unto him; because he hath appointed a day,
in the which he will judge the world in righteousness,
by that man whom he hath ordained,`' to wit, Christ Jesus. Acts 17:31.
Rev. 22:12. John 5. Matt. 28. And here you may see, Christ saith,
he is the resurrection and the life; '`for as the Father raiseth up the dead,
and quickeneth them,
even so the son quickeneth whom he will.`' John 5:21.
And Christ who is the image of the invisible God,
'`by him are all things created that are in heaven, and that are in the earth, etc.
All things were created by him,
and for him.`' Col. 1:16-17. '`He is before all things,
and by him all things consist, and having made peace through the blood of his cross,
by him to reconcile all things unto himself, whether they be things in heaven,
or things in the earth.`' For by Christ God made the world,
'`who is the brightness of his glory, and the express image of his substance,
and upholdeth all things by the word of his power.`' Heb.
1:2-3. John 1. "`All things were made by Christ,
the word, and without him was not any thing made that was made.`' Christ Jesus,
the first born of every creature, the first begotten from the dead,
by him were all things created that are in heaven, and that are in the earth.
And the apostle saith,
'`that the gospel of Christ was preached to every creature under heaven.`' Col. 1:15,16,18.
23. '`And that in the fulness of time Christ might gather in one all things in himself,
both which are in heaven, and which are on the earth,
even in him.`' Eph. 1:10. And therefore the apostle saith,
he was to '`let all men see what is the fellowship of the mystery,
which from the beginning of the world hath been hid in God,
who created all things by Jesus Christ.`' Eph. 3:9. Here you may see,
all things were made and created by Jesus Christ;
and man being fallen from God into sin and death, from the life, Christ saith,
'`I am the resurrection and the life;`' and saith,
'`he that believeth on him shall not perish, but have everlasting life.`' And moreover,
saith he, '`He that believeth on me, though he were dead, yet shall he live;
and whosoever liveth and believeth in me,
shall never die.`' And Christ saith to the Jews, '`If any man keep my sayings,
he shall never taste of death.`' And again, Christ saith unto the Jews, Verily, verily,
I say unto you, if any man keep my sayings,
he shall never taste of death.`' John 8:51-52. '`The Father loveth the son,
and hath given all things into his hand; and he that believeth on the son,
hath everlasting life, (mark, hath it,
and is not condemned,) but he that believeth not the son, is condemned,
and shall not see life, but the wrath of God abideth on him.`' John 3:18. 36.

The Sadducees asked Christ, and said, '`There were seven brethren took one woman to wife,
one after, another;`' and they asked Christ,
'`whose wife she shall be in the resurrection?`' And Christ said unto the Sadducees,
'`that they did err, and knew not the scriptures, neither the power of God;
for when they shall rise from the dead, they neither marry, nor are given in marriage,
but are as the angels which are in heaven;
neither can they die any more.`' Luke 20:36. And
'`as touching the resurrection of the dead,
that they rise, have ye not read in the book of Moses,
how in the bush God spake unto him, saying, I am the God of Abraham,
and the God of Isaac, and the God of Jacob.
(Luke 20:38) He is not the God of the dead, but the God of the living,
for all live to him.`' And Christ said unto the Sadducees, '`Ye do greatly err,`' etc. Mark 12:13.
20. 27. Matt. 22:23. 28. 30, 31.
'`For he that believeth shall not perish, but have everlasting life.`' John 3:15.

And you may see how the apostles were witnesses of
the resurrection of Christ from the dead,
and that his soul was not left in hell, neither did his flesh see corruption.
Acts 2:30-31. and 4:33.
But the preaching the resurrection of Christ to the philosophers, Epicureans,
and Stoics, they called it babbling, and so mocked at it;
as in Acts 17:18.22. And there see how they opposed the apostle,
when he preached Christ the resurrection from the dead, Acts 23:6.
And the apostle said, '`that there shall be a resurrection of the dead,
both of the just and unjust;`' and for preaching the resurrection of the dead, (namely,
Christ Jesus,) he was called in question. Acts 24:15. 21.
For all men being dead in Adam,
Christ by the grace of God hath tasted death for every man,
and is risen for their justification; he is the quickening spirit,
and is the resurrection and the life, and the first born from the dead,
and is become the first fruits of them that sleep.

Now concerning the son of God, Jesus Christ our Lord,
which was made of the seed of David, according to the flesh,
and declared to be the son of God, with his power, according to the spirit of holiness,
by the resurrection from the dead. Rom. 1:3-4.
'`And like as Christ was raised up from the dead,
by the glory of the Father,
etc. for if we have been planted together in the likeness of his death,
we shall be also planted together in the likeness of his
resurrection.`' Rom. 6:5. And the apostle said,
'`That I may know Christ, and the power of his resurrection,
and the fellowship of his sufferings, being made conformable to his death,
if by any means I might attain unto the resurrection of the dead, (namely,
the Lord Jesus Christ,) who shall change our vile body,
that it may be fashioned like unto his glorious body, according to the working,
whereby he is able even to subdue all things unto himself.
Phil. 3:10-11 to 21. Mark, change your vile body,
and fashion it like unto his glorious body in the resurrection.
So the vile body must be changed if it be made like unto his glorious body in the resurrection.`' 2 Tim. 2:18,37.
But Hymeneus and Philetus concerning the truth erred,
who said that the resurrection was past already.
Such overthrew people from the faith that stand in Christ,
who is the resurrection and the life,
through which faith they attained to the resurrection, and had their vile bodies changed,
and made like unto his glorious body.
And the apostle said, '`Blessed be God, the Father of our Lord Jesus Christ,
who according to his abundant mercies hath begotten us again to a lively hope,
by the resurrection of Jesus Christ,
from the dead.`' 1 Pet. 3:21. And through their faith in Christ Jesus,
who is the resurrection and the life, did many suffer, as in Heb. 11:35.

And John said, '`Blessed and holy is he that hath part in the first resurrection,
on such the second death shall have no power,
but they shall be priests of God and Christ,`' etc. Rev. 20:6.

Now these are the true believers in Christ Jesus, that shall not perish,
'`but are passed from death to life, and shall have life everlasting;
and they that have done evil, their resurrection is unto damnation; but the righteous,
and they that have done good,
their resurrection is unto everlasting life.`' John 5:29. Matt. 25:46. So,
they that come to the resurrection of condemnation, who have lived in the death of Adam,
and would not believe in Christ the life, they are cast into the lake of fire,
with hell and death, which is the second death;
but they are blessed that have part in the first resurrection, (namely,) Christ,
who is the resurrection and the life, on such the second death hath no power. Rev. 20:6.
14, 15. For Christ, who is the resurrection, and the life,
destroyeth the devil and his works, who through death destroyeth death, yea, the devil,
the power of death, and bruiseth the serpent`'s head, and casts the devil,
the old serpent, and the dragon, and the beast,
and the false prophet into the lake of fire.
Rev. 18:20. and 20:10.

Now Christ, who is the beginning and ending, the first and the last,
all that believe in him, and are grafted into him, and put him on, and walk in him,
who is the resurrection and the life,
such neither the first death nor the second death hath power over,
but they live and walk in Christ, who hath power over death,
and destroyeth death and the devil, the power of it,
who is the resurrection and the life, who brings people out of the first death in Adam,
and gives them power over the second death and hell, which is cast into the lake of fire,
with all them that are not written in the Lamb`'s book of life,
from the foundation of the world.
So in Christ the resurrection and the life, all are blessed and happy eternally.

And the apostle Paul explains very fully the resurrection, 1 Cor.
xv. and saith, '`Now if Christ be preached, that he rose from the dead,
how say some amongst you, (namely,
the Corinthians,) that there is no resurrection from the dead?
And if Christ be not risen, then our preaching is vain, and we are false witnesses,
because we have testified of God, that he raised up Christ from the dead.
And if Christ be not raised up from the dead, then is your faith vain,
and you are yet in your sins; for if the dead rise not,
then is not Christ raised.`' So here you may see, here were some amongst the Corinthians,
that said, there was no resurrection of the dead. 1 Cor. 15:12.
And therefore the apostle thus reasoned with them,
'`If Christ was not risen,
then there was no resurrection from the dead;`' then their preaching was vain,
and their faith was vain, and they were yet in their sins;
and '`if in this life only we have hope in Christ,
we are of all men most miserable;`' but now '`Christ is
risen from the dead,`' as Col. 1:18. And Rev. 1:5,
'`The first begotten from the dead,
and the prince of the kings of the earth.`' And Christ saith, '`I am he that liveth,
and was dead; and behold, I live forever more.`' Rev. 1:18. For by man, (namely,
Adam,) came death; and by man, (namely,
Christ,) came also the resurrection from the dead; for as in Adam all died,
even so in Christ shall all be made alive.
But some will say, '`How are the dead raised?
and with what bodies do they come?`' But the apostle answereth, and saith to such,
'`Thou fool, that which thou sowest is not quickened except it die,
and that which thou sowest, thou sowest not that body that shall be, but bare grain;
it may chance of wheat, or some other grain, but God giveth it a body as it pleaseth him,
and to every seed its own body.`' In the marginal note it is said,
that '`Paul sendeth such fools that seem to be witty and wise,
to be instructed of the poor rude husbandmen,`' 1 Cor.
15:35. As in the first Adam we are all born natural,
so in Christ, the second Adam, we are all born spiritual.

Here you may see how the apostle teacheth these fools
by the seedsman that soweth his wheat,
or some other grain; and the natural seed that is sown in the creation,
preacheth the resurrection of the dead,
and may teach such fools the resurrection of the dead, that say,
with what body do they come, when the dead are raised up '`Thou fool,
that which thou sowest is not quickened, except it die, and that which thou sowest,
thou sowest not that body that shall be,
but God giveth it a body as it pleaseth him,`' etc.
For the husbandman that soweth his wheat or barley, doth he sow that body that shall be?

And Christ saith, '`Verily, I say unto you,
except a corn of wheat fall into the ground and die, it abideth alone, but if it die,
it bringeth forth much fruit.`' John 12:24. So, what the husbandman soweth,
whether wheat, or other seed, be soweth, (mark, he soweth) not that body that shall be,
but God giveth it a body as it pleaseth him, and to every seed its own body.
And there are heavenly bodies, and there are earthly bodies.
The glory of the heavenly is one,
and the glory of the earthly is another.`' So here
is a distinction of glories to each body,
so also is the resurrection from the dead; '`it is sown in corruption,
it is raised in incorruption; (mark, in incorruption;) it is sown a natural body,
it is raised a spiritual, (mark,) raised a spiritual body.
There is a natural body, and there is a spiritual body.
And so it is written, The first man Adam was made a living soul,
the second man Adam was made a quickening spirit.
Howbeit, that was not first which is spiritual, but that which is natural,
and afterwards that which is spiritual.
The first man is of the earth earthly, the second man is the Lord from heaven.
And as is the earthly, such are they also that are earthly; and as is the heavenly,
such are they also that are heavenly.
And as we have borne the image of the earthly,
we shall also bear the image of the heavenly.`' Mark,
as we have borne the image of the earthly,
we shall also bear the image of the heavenly in the resurrection, as the apostle saith.

'`Now this I say, brethren, that flesh and blood cannot inherit the kingdom of God,
neither doth corruption inherit incorruption.`' (Mark,
corruption doth not inherit incorruption.) '`Behold, I show you a mystery,
we shall not all sleep, but we shall all be changed,`' (mark,
all.) So here is a changing from corruption to incorruption,
and from mortality to immortality, and from an earthly image to a heavenly,
and from a vile body, unto Christ`'s glorious body in the resurrection,
whose flesh saw no corruption, and to be flesh of his flesh, and bone of his bone.

And further, the apostle saith, '`In a moment, in the twinkling of an eye,
at the last trumpet; for the trumpet shall sound,
and the dead shall be raised incorruptible, and we shall be changed.`' Mark,
the dead shall be raised incorruptible, and mark, we shall be changed.
And is not this a heavenly trumpet?
for this corruptible '`must put on incorruption,
and this mortality must put on immortality.`' 1 Cor. 15:1 Thess. 4:16.
So when the corruptible hath put on incorruption,
and this mortal shall have put on immortality, mark, put on immortality and incorruption,
'`then shall be brought to pass this saying that is written,
Death is swallowed up in victory.
O death! where is thy sting!
O grave! where is thy victory?
The sting of death is sin, and the strength of sin is the law; but thanks be to God,
which giveth us (mark, us,) the victory, through our Lord Jesus Christ.`' 1 Cor.
xv. Isa. 25:8. Hos. 13.

=== Postscript

Peter saith to the church,
'`I will not be negligent to put you always in mind,`' (namely,
of the things that he had declared unto them, though they knew them,
and were established in the truth;) '`as long as I am in this tabernacle, to stir you up;
knowing that shortly I must put off this my tabernacle,
as our Lord Jesus Christ hath showed me.`' 1 Pet.
1:12-14. And the apostle Paul saith,
'`For we know, that if our earthly house of this tabernacle be dissolved,
we have a building of God, a house not made with hands, eternal in the heavens;
for in this, (namely, earthly house,) we groan earnestly,
desiring to be clothed upon with our house that is from heaven.`'

So God`'s people have a house, and a clothing from heaven,
when they put off the earthly tabernacle;
'`for we that are in this earthly tabernacle do groan, being burdened,
not for that we would be unclothed, but clothed upon,
that mortality might be swallowed up of life.`' 2 Cor. 5:1. 3, 4.

Here you may see what the spiritual groaning was for,
'`for a house and clothing from heaven,
and that mortality might be swallowed up of life,`' and so to be ever with the Lord.
And here you may see how Christ is the resurrection and the life;
and in the resurrection, the vile body is changed like unto his glorious body;
and in the resurrection they are spiritual, '`and mortal puts on immortality,
and corruptible puts on incorruption.`' And so as we have borne the image of the earthly,
we shall also bear the image of the heavenly; as the apostle saith,
'`There are earthly bodies, and there are heavenly bodies;
the glory of the earthly is one, and the glory of the heavenly is another;
there is a natural body,
and there is a spiritual body.`' The natural body may be seen with the natural eye,
but the spiritual body must be seen with the spiritual eye.
