[#ch28.style-blurb, short="Concerning the Stone that Smote the Image"]
== Concerning the stone that smote the image; and concerning Christ the vine, and the Jews, how that God planted them a noble vine, but they degenerated, and destroyed the Lord`'s servants and son, that came to look for fruits.

Daniel saith, '`The stone that was cut out of the mountain without hands,
which brake to pieces the great image of iron, clay, brass, silver, and gold,
and broke them to pieces,
that the image became like the chaff of the summer threshing floor,
and the wind carried them away, that no place was found for them;
and this stone that smote the image became a great mountain,
and filled the whole earth.`'

Now this image of gold, silver, brass, iron, and clay,
was the four monarchies which the stone brake to pieces; and in the days of these kings,
(namely,
the four monarchies,) shall the God of heaven set up a kingdom that shall never be destroyed,
and the kingdom shall not be left to other people,
but it shall break to pieces all those kingdoms, and it shall stand forever.`'

Now here you may see, this stone, which is Christ, breaks to pieces those great Goliahs,
and their kingdoms; the great image of gold, was the Babylonian monarchy, and of silver,
was the Medes and Persians`' monarchy, and of brass, was the Grecians`' monarchy,
and of iron and clay was the Roman monarchy;
and in the days of the Roman monarchy Christ came, who said,
'`All power in heaven and earth is given unto me,
and his kingdom was not of this world.`' And so in the days of these four monarchies,
which were called the great image, Christ`'s kingdom was set up, which stands forever.
So Christ is the stone, that breaks this great image to pieces,
'`and became a great mountain, and filled the whole earth.`' Dan. 2:35 to 45. Mark,
this mountain became so great, that it filled the whole earth,
and if it filled the whole earth, then all the people of the earth may see it.

What! can people in Asia, Europe, Africa, and America, see this great mountain?
Yes, it filleth the whole earth; and if it fill Europe, Asia, Africa, and America,
then all the people in these places may see it, namely, in Europe, Asia, Africa,
and America.
And Isaiah and Micah saith, '`It shall come to pass in the last days,
that the mountain of the Lord`'s house shall be established in the top of the mountains,
and shall be exalted above the hills, and all nations shall flow unto it,
and many nations shall come, and say, let us go up to the mountain of the Lord`'s house,
etc. and he will teach us of his ways,
and we will walk in his paths.`' Isa. 2:2-3. Mic. 4:2. Is not
this mountain which is established on the top of all mountains,
and exalted above all the hills, Christ Jesus, the mountain that fills the whole earth,
to whom all nations must flow, to be taught God`'s ways, and walk in his paths?
And doth not Christ, this holy mountain, by whom all things were made,
that filleth the whole earth, enlighten every man that cometh into the world,
that with this light, which is the life in Christ, (I say,
that with this true light,) they might all see Christ, the holy and great mountain,
that filleth the whole earth?
Yea, I say, all the men that come into the world, in Europe, Asia, Africa, and America,
Christ enlighteneth every one of them that cometh into the world,
that with his light they might see him, the great mountain that fills the whole earth,
exalted above all the hills and mountains in the earth; for Christ, the great mountain,
filleth the whole earth, as is said before.

And the apostle Paul saith, '`God who commanded light to shine out of darkness,
hath shined in our hearts, to give the light of the knowledge of the glory of God,
in the face of Christ Jesus.`' John 1:9. 2 Cor. 4:6.

So here you may see it is the light of Christ that shineth in the heart,
which Christ enlighteneth every man that cometh into the world withal,
that giveth the knowledge of the glory of God in the face of Christ Jesus,
who is the great mountain, that filleth the whole earth.
So that every man that cometh into the world, in what part soever it be,
with the light may see Christ, the mountain that filleth the whole earth.
'`And they shall not hurt nor destroy in all my holy mountain,`' saith the Lord;
which holy mountain is Christ, and none doth hurt nor destroy in Christ Jesus;
for in him they have life, peace, and rest,
who is the holy mountain that filleth the whole earth; for Christ destroyeth the devil,
the destroyer, which hurts people, and his works;
'`and the earth shall be full of the knowledge of the Lord,
as the waters cover the sea.`' Isa. 11:9. And that which
giveth the knowledge of the Lord and Christ Jesus,
to all people, it is the light of Christ Jesus that he hath enlightened them withal,
which shines in their hearts, by which light they may know the Lord,
and see Christ the holy mountain.

And the apostle saith to the church of Christ, the Hebrews,
'`Ye are come unto Mount Zion, and unto the city of the living God,
the heavenly Jerusalem.`' Heb. 12:22. And is not this the Mount Zion,
in which Christ is laid, who is elect and precious, the chief corner stone. 1 Pet. 2:21.
And is not this the stone that becomes a great mountain,
and filleth the whole earth?
And the apostle saith, '`There shall come out of Zion a deliverer,
and shall turn away ungodliness from Jacob.`' Rom. 11:26. Isa. 59:20.
This is not that outward hill Zion,
that mountain at outward Jerusalem; for Christ was born in Bethlehem,
some miles from Jerusalem.
So this was heavenly Zion, in which Christ was laid, and the church of the Hebrews,
in the new covenant and new testament, came unto.

And David saith, '`Oh! that the salvation of Israel was come out of Zion!
When the Lord bringeth back the captivity of Israel, Jacob shall rejoice,
and Israel shall be glad.`' Ps. 14:7. Here you may see,
Christ the salvation comes out of Zion.
And David saith, '`The Lord is greatly to be praised in the city of our God,
in the mountain of his holiness; beautiful for situation, the joy of the whole earth,
is Mount Zion.`' Ps. 48:1-2.

So here you may see, Mount Zion is the joy of the whole earth;
is not this the mountain of God`'s holiness, which fills the whole earth,
which is the joy of the whole earth?
'`Out of Zion,
the perfection of beauty hath God shined.`' Ps. 1:2.
So that with his divine light of Christ they might see,
and come to this Mount Zion, the joy of the whole earth.
And David saith, '`The Lord sends help from his sanctuary,
and strength out of Zion.`' Ps. 20:2. And Jeremiah saith, '`The Lord will bless thee,
O habitation of justice,
and mountain of holiness.`' Jer. 31:23. Is not this
the mountain of holiness that is established above all mountains,
and exalted above all the hills, and filleth the whole earth?
And so with the light of Christ you may know the Lord your God dwelleth in Zion,
his holy mountain, and saith, '`Blow ye the trumpet in Zion,
and sound an alarm in my holy mountain.`' Joel 2:1. and chap.
iii. 17. 20. Here you may see where God dwelleth, and where the trumpet is to be blown,
and alarm is to be sounded, namely, in Zion, God`'s holy mountain.

'`Upon Mount Zion shall be deliverance; and there shall be holiness,
and saviours shall come upon Mount Zion to judge the mountain of Esau,
and the kingdom shall be the Lord`'s.`' Is not this Mount Zion a great mountain,
and the watch tower that fills and looks over the whole earth,
and is the joy of the whole earth?
And is not this the Mount Zion that the apostle said,
the Hebrews were come to in the new testament, and heavenly Jerusalem,
the city of the living God, and an innumerable company of angels in the city,
and the spirits of just men made perfect.
Which outward Jerusalem, and the outward Mount Zion,
was a type of the heavenly Jerusalem, and the heavenly hill Mount Zion.
And upon that outward hill Mount Zion, a man might see a great way in the land of Canaan,
but upon heavenly Mount Zion in heavenly Jerusalem,
the spiritual men may see over the whole world or earth;
for it is the joy of the whole earth.

And John said, '`I looked, and lo a lamb stood upon Mount Zion,
and with him a hundred and forty-four thousand,
having his father`'s name written in their foreheads.`'
And was not this heavenly Mount Zion,
and heavenly Jerusalem?
as in Rev. 21. chap.
xiv. 1. '`And the glory of God doth light it,
and the lamb is the light thereof.`' And they whose
names are written in the lamb`'s book of life,
enter into this heavenly Jerusalem, and heavenly Mount Zion.
And David saith, '`Give unto the Lord the honour and the glory due unto his name;
worship the Lord in the mountain of holiness.`' Ps. 28:2.

And Christ saith, "`The hour cometh, and now is,
when the true worshippers shall worship the Father in spirit and in truth,
and not at the mountain of Samaria, nor at Jerusalem; for God is a spirit,
and they that worship him,
must worship him in spirit and in truth.`' Is not the worship in
the spirit and in the truth above all the worships in the world,
above the dragons, devils, beasts, and will-worshippers, and the mountain at Samaria,
and Jerusalem`'s worshippers.
They that worship the Lord in spirit and truth,
do they not worship him in the beauty of holiness? Ps. 29:2.
John 4:20-21. 23, 24. And the Lord saith,
'`For out of Zion shall go forth the law,
and the word of the Lord from Jerusalem.`' Isa. 2:3. Mic.
4:2. And is not this heavenly Jerusalem and heavenly Zion,
the joy of the whole earth, which the word of the Lord goeth forth from,
and the law of life, love, and faith in the new covenant and new testament.
For the law of works in the old covenant and old testament,
was it not received from Mount Sinai, and observed by the Jews in outward Jerusalem,
where the outward hill Mount Zion was,
but the children of the new covenant and new testament, the apostle saith,
'`were come to heavenly Jerusalem, the city of the living God,`' and so to Christ Jesus,
the elect and precious stone laid in Zion.

And is not Christ the mountain of myrrh and hill of frankincense spoken of in Canticles,
yea, the mountain that fills the whole earth? Song. 4:6.
Dan. 2:35. And John saith, '`We know that the son of God is come,
and hath given us an understanding, and we know him that is true,
even his son Jesus Christ.`' Now John, who was a witness of Christ,
both in the days of his flesh, and after his resurrection and ascension,
was not he come to this heavenly Jerusalem and Mount Zion, the joy of the whole earth?
And John saith to the saints, '`That ye may have fellowship with us;
and truly our fellowship is with the Father, and with his son Jesus Christ.
And if we walk in the light as he is in the light,
then have we fellowship one with another,
and the blood of Jesus Christ his son cleanseth us from all sin.`' 1 John 1:3. 7.

And Christ`'s blood is called the blood of the everlasting covenant and testament. Heb. 13:20.
And Jesus Christ, '`who hath loved us,
and washed us from our sins by his own blood,`' Rev.
1:5. '`who hath redeemed us to God by his blood,
out of every kindred, tongue, people, and nation,
and made us unto our God kings and priests,
and we shall reign upon the earth.`' Rev. 5:10-9.
These are they that sing a new song,
and are come to Mount Zion, and to heavenly Jerusalem, and to Christ,
the mountain that filleth the whole earth.
This is established above all the mountains, and exalted above all the hills.
And '`they overcame with the blood of the lamb, and by the word of their testimony,
and they loved not their lives unto death.`'

So these were the weapons by which the saints overcame, namely, by the blood of the Lamb,
the life of Jesus, they overcame death, and the devil, the power of death;
and by the word of their testimony, the testimony of Jesus, the spirit of Jesus,
or spirit of prophecy, and the word by which all things were made, which liveth, abideth,
and endureth forever; by which God`'s people are born again of the immortal seed,
by the word of God, who feed upon the milk of the word,
which liveth and abideth forever.

And Christ said to his disciples, '`I am the true vine, my Father is the husbandman:
abide in me, and I in you; as the branch cannot bring forth fruit of itself,
except it abide in the vine, no more can ye except ye abide in me.
I am the vine, ye are the branches, he that abideth in me, and I in him,
the same bringeth forth much fruit; for without me ye can do nothing.
If any man abideth not in me, he is cast forth as a branch, and is withered,
and men gather them, and cast them into the fire,
and they are burned.`' John 15:1 to 6. Here you may see,
that none can bring forth fruit, except they abide in Christ the vine;
for from him every branch receives its sap and nourishment, viz. from Christ,
the vine tree, as they abide in him.
And Micah saith, '`They shall sit every man under his vine, and under his fig tree,
and none shall make them afraid,
for the mouth of the Lord hath spoken it.`' Mic. 4:4.

And in Zech. 3:10. '`In that day, saith the Lord of hosts,
shall ye call every man his neighbour under the vine,
and under the fig tree.`' And is not this the day of Christ and his gospel of salvation,
preached to every creature under heaven, to bring them into and under Christ the vine,
so that they might bring forth fruit in him;
for without him they cannot bring forth fruit?
Now Christ is the great vine tree, who with his grace, truth,
and light enlighteneth all that come into the world: so all that do abide in his light,
grace, and truth, they are branches of Christ Jesus,
and abide in Christ the great and flourishing vine, and in him they bring forth fruit;
but if they do not abide in the light, spirit of grace and truth,
that cometh from the vine, they cannot abide in Christ the vine,
and then they are withered branches to be cast into the fire.
So here you may see, Christ is the great vine that spreads over all the earth,
and all are the true christians and the living branches that abide in him,
and bring forth righteous holy fruit to the praise and glory of God.

And David saith, '`Thou bast brought forth a vine out of Egypt,
and thou hast cast out the heathen,
and planted it with thy right hand.`' Ps. 80:8. 15.
And were not they the children of Israel,
that God had planted with his right hand, (after he had thrown out the heathen,
the rubbish,) whom he called the vine;
and in Isa. 5. he called the Jews '`his vineyard, and he planted them a choice vine,
and fenced it, and built a tower in the midst of it, and he looked for grapes,
but it brought forth wild grapes;`' and the Lord said,
'`this vine and vineyard was the house of Israel, and the men of Judah,
that he had planted,
that went into wickedness,`' as you may see Isa. 5. from ver. 1 to 10. And again,
the Lord said, '`I had planted thee, (namely, the Jews,) a noble vine,
wholly of a right seed,
how art thou returned into a degenerate plant of a strange vine unto me?`' Jer. 2:21. Ps. 44:2.
Ezek. 17:5. Here while the Jews kept to the good spirit of God,
and to the Lord and his law, they kept within the hedge that fenced the vine,
and '`sat every one under his vine, and under his fig tree`' in safety. 1 Kings 4:25.
And then their vines gave a good smell to the Lord,
as in Song. 2:13. And when the vines do flourish, which are compared to the church,
and the tender grapes appear, such come to bring forth fruit to the Lord,
as in Song. 7:11.

And Solomon saith, '`They made me keeper of the vineyard,
but my own vineyard I have not kept.`' Song. 16.
And they that do not keep their own vineyard,
they are not like to keep others.
And Christ '`speaketh a parable to the Jews,
of a certain householder which planted a vineyard, and hedged it round about,
and digged a wine press in it, and built a tower, and let it out to husbandmen, etc.
And when the time of fruit drew near, he sent his servants to the husbandmen,
that they might receive the fruits of it;
and the husbandmen took the servants and beat one, and killed another,
and stoned another.
And again, he sent other servants, more than the first, and they did unto them likewise;
and at last he sent his son, saying, surely they will reverence my son;
but when the husbandmen saw the son, they said among themselves, come let us kill him,
and let us seize of the inheritance, and it shall be ours; and they caught the son,
and cast him out of the vineyard, and slew him.`' And Christ asked the '`Jews,
when the Lord therefore of the vineyard cometh, what will he do with the husbandmen?
And the Jews answered Christ, and said unto him,
he will miserably destroy these husbandmen, and let the vineyard unto other husbandmen,
which will render him the fruits in due season.`'
Matt. 21:33, to the end. Mark 12:1. Luke 20:9. Jer. 2:21. Isa. 5:1.
For the chief priests, Pharisees,
and the Jews perceived that Christ spake this parable of them,
and they had given judgment against themselves, and were so angry,
they sought to lay hands on Christ, but they feared the multitude,
which took him for a prophet.

And here all the persecutors in Christendom may see in this parable the persecuting Jews,
which beat, and stoned, and killed the servants of God,
and at last killed the heir that came to look for heavenly fruits amongst them,
and at last God sent his son, and they killed him.
And this parable may serve for all the persecuting Jews and Christians in the world,
who make an outward profession of the new and old testament, and beat, persecute,
and kill God`'s servants,
that he sends to seek for spiritual heavenly fruits amongst them.

And will not the Jews`' judgment that they gave against themselves,
come upon such Christians, that the Lord will miserably destroy these wicked husbandmen,
and let out the vineyard to other husbandmen,
that will render him the fruits in their season.
This was the Jews`' judgment upon themselves, who had beat, killed,
and stoned God`'s servants,
and at last killed the heir which came to look for
heavenly spiritual fruits amongst them.
And therefore let all the beaters, killers,
and persecutors of God`'s servants concerning religion,
see which way they can escape the judgment and sentence upon themselves,
or get off that judgment before mentioned, as in Matt. 21:41.

Again it is said in Duet. 33. '`Moses commanded us a law for an inheritance of the
congregation of Jacob.`' So the law which Moses received from God in Mount Sinai,
was an inheritance for the congregation of Jacob in the old covenant and old testament,
which had served till Christ the seed came, who is the end of the law,
and the end of that inheritance.
For the apostle saith, '`Christ is the end of the law for righteousness`' sake,
to every one that believeth.`' So he is the end of that inheritance.
And as the apostle saith,
'`Christ hath redeemed us from under the law.`' And
so Christ redeems from under and out of that inheritance,
namely, the law that came by Moses, and is the end of that inheritance.
For the apostle saith, '`While Moses is read,
the veil is over the heart.`' But that veil is done away in Christ;
for Moses had a veil over his face,
etc. when he brought the law to the children of Jacob for an inheritance,
in the old testament.

And so, while Moses was read, and the old testament veil was over the Jews`' hearts,
yet when it is turned to the Lord, the veil shall be done away by Christ,
who is the end of the law for righteousness`' sake to every one that believeth;
and he that believeth is entered into Christ, his eternal rest.

So now,
if the law was given for an inheritance of the children
of Jacob in the old testament and old covenant,
which served till Christ the seed came in his new covenant and new testament;
then is the law of the spirit of life, which is in Christ Jesus,
that which makes people free from the law of sin and death,
and to all the children of the new covenant and new testament, the inheritance,
in which inheritance they serve God in the newness of life,
and in the new and living way.
And so, is not the law of life, love,
and faith an inheritance for all the children of light in the new covenant and new testament,
for them to inherit, possess, enjoy, and walk in?
For all God`'s saints are in his hand, and he loveth them,
and they are humbled at his feet, to receive his words. Duet. 33:23.
4.

'`The ministration of death or condemnation, written and engraven in stones,
was glorious,
so that the children of Israel could not steadfastly behold the face of Moses,
for the glory of his countenance,
which glory was done away ay by Christ.`' So that outward
glory which Moses with a veil covered and hid,
in the old covenant and testament, was done away by Christ; for we all,
(in the new covenant and testament,) '`with open face beholding, as in a glass,
the glory of the Lord, are changed into the same image, from glory to glory,
by the spirit of the Lord.`' So in the new covenant
and new testament this is a spiritual image and glory,
and an inward glory, which is not to be done away, but remains,
and all who profess christianity are to mind that, that they may enjoy it.

[.signed-section-signature]
G+++.+++ F.
