[#ch29.style-blurb, short="To All Kings, Princes, Rulers, Governers, Bishops, and Clergy"]
== To all all Kings, Princes, Rulers, Governors, Bishops, and Clergy, that profess christianity in Christendom.

[.heading-continuation-blurb]
Being a distinction between the laws, commandments,
and ordinances of the higher powers, for the punishment of evil doers,
and for the praise of them that do well.

[.heading-continuation-blurb]
And the ordinances, doctrines and commands of men,
concerning religion and worship, which are not to be touched, tasted nor handled.
And the hand writing of ordinances among the Jews, which Christ hath blotted out. By G. F.

You all owning one God, the Father, the creator of all, and one Lord Jesus Christ,
by whom all things were created; and you all do profess that you own one God,
and Christ Jesus, and believe in him.
And Christ said to them that believe in him, '`A new commandment I give unto you,
that YOU LOVE ONE ANOTHER, AS I HAVE LOVED YOU;
by this shall all men know that ye are my disciples,
if you have love one to another.`' John 13:34-35.

Now let all that profess christianity in christendom, and that say,
they believe in Christ, see how they have obeyed this command of Christ;
for Christ saith, '`If any man loves me, he will keep my word and sayings;
and it is he that loveth me that hath my commandments,
and keepeth them.`' John 14:11. 21. 23. Here you may see
how Christ`'s disciples are known to be true christians,
by loving one another.
And again, Christ saith, '`LOVE YOUR ENEMIES, bless them that curse you,
do good to them that hate you,
and pray for them which despitefully use you and persecute you.`' Matt. 5:44. Luke 6:27.
So here you may see that christians which are the disciples of Christ,
and learners, and followers of him: First, they are to love one another,
by which they are known to be the disciples of Christ.
Secondly, they are to love their enemies; yea them that be enemies of Christ,
and enemies of christianity;
and if such enemies of Christ and christianity should curse the christians,
yet they are to bless and not curse them again.
'`But, bless them that curse you, and pray for them that persecute you;
bless and curse not.`' Rom. 12:14. Matt. 5:44.
So christians are not to curse one another;
no, they are forbidden to curse their persecutors,
or to curse them again that curse them, but bless and curse not.
These are the commands of Christ and the apostles,
to be obeyed by them that profess Christ, and believe in him; and they that love Christ,
will keep his commandments.

And Christ saith, '`that Christians should do good to them that hate them,
and pray for them which despitefully use them,
and persecute them.`' So it is clear that all christians that believe in Christ Jesus,
should not persecute one another, nor curse one another,
nor despitefully use one another, but love one another; for they should not curse, hate,
despitefully use nor persecute their enemies, but love them,
bless them that do curse them, and do good to them that hate them,
and pray for them that persecute them.
And these are the commands of Christ; and they that love Christ, will keep his commands;
'`and he that loveth him not, keepeth not his commands nor sayings.`' John 14:24.

Now here you may see that christians are to love one another, and to love enemies;
so they are not to curse, hate, and despitefully use one another, no, not their enemies;
but to love them, do good to them, and pray for them, and bless them,
though they do curse, hate, despitefully use, and persecute christians.
So here is the spirit of persecution quite shut out (which
is got up since the apostles`' days) from among christians,
by the power and spirit of Christ Jesus; that christians should neither curse, hate,
despitefully use nor persecute one another; for they are not to persecute enemies,
but to do good to them, and love them.
And christians are to bless them that curse them, and are not to curse again;
and they are not to hate, despitefully use or persecute enemies,
but to love them and pray for them.
Here you may see the virtue and nobility of true
christianity is clear of the spirit of persecution,
both from among themselves, and to enemies;
and all will confess to this that have the spirit of Christ;
and they '`that have not are none of his.`' Rom. 8:9. And then you may see,
how hath this persecuting spirit risen in that which
is called Christendom since the apostles`' days.
Now every sect in Christendom when they have gotten the magistrates`'
power to maintain their sect with outward laws and carnal weapons,
then they will say, '`Let every soul be subject to the higher powers,`' etc.
Rom. 13. and '`submit yourselves to every ordinance of man for the Lord`'s sake,
whether it be to the king, as supreme, or unto governors,
as unto them that are sent by him for the punishment of evil doers,
and for the praise of them that do well.`' 1 Pet.
2:13-14. And rulers are not a terror to good works,
but to the evil. Rom. 13:3.
And the apostle tells you what these evil works are, and '`evil doers,
ungodly sinners, unholy, profane, murderers of fathers, and murderers of mothers,
man-slayers, whoremongers, lawless, disobedient,
and them that defile themselves with mankind, men-stealers, liars,
perjured persons,`' etc. 1 Tim. 1:10-9.
Such as these the law was made against,
and was not made for a righteous man, but against such sinners and evildoers.
And the christians in the primitive times in the apostles`' days were
to submit themselves to every ordinance of man for the Lord`'s sake,
and to the higher powers for the punishment of such evil doers.
And such rulers are not a terror to good works, but to such evil doers,
and were a praise to them that do well.
And they that do well, are not afraid of that power to punish evil doers,
for they have the praise of the same; for the higher powers, and every ordinance of man,
that punisheth such evil doers before mentioned is for the praise of them that do well. Rom. 13:3.
1 Pet. 2:14.

And now here you may clearly see, that the christians in the primitive times,
whose souls were to be subject to the higher powers,
to every ordinance of man for the Lord`'s sake,
for the punishment of such evil doers as the apostle speaketh of in Timothy,
and a terror to such evil workers, but a praise to them that did and do well.

Now the apostle doth not say, let every soul be subject to the higher powers,
and every ordinance of man for the Lord`'s sake,
for the punishment of such as meet together to wait upon God and to pray unto him,
and do obey, serve, and worship the living God that made them; and the apostle saith,
that the law of the higher powers is not a terror to good works,
neither was the law made for the righteous,
but for such like sinners as be hath before mentioned.
So it is clear that the christians in the primitive times,
whom the apostle doth teach that their souls were to be subject to the higher powers,
and to every ordinance of man for the Lord`'s sake,
for the punishment of such evil doers as he speaketh of 1 Tim. i.
which all true christians now, their souls are subject to every such high power,
and every such ordinance of man, for the punishment of such evil doers, that are lawless,
and disobedient, and ungodly, and that murder their fathers and mothers,
and are unholy and profane; and are men-slayers, and are whoremongers,
and defile themselves with mankind, and are men-stealers, and liars,
and perjured persons, and such like ungodly sinners;
every true christian`'s soul is to be subject to
every ordinance of man for the punishment of such,
which is for the praise of them that do well, and no terror to good works,
but a terror and a discourager of such evil workers and works before mentioned.

Now here you may see it is clear,
the apostles do not say that every soul should be subject to the higher powers,
and to every ordinance of man for the Lord`'s sake,
for the punishment of people concerning their faith, religion, and for worshipping,
obeying, and serving of God Almighty for their tender consciences,
no not so much as such weak consciences as observed days,
and made scruple of eating of meats, or herbs;
but the apostle left such as were weak in the faith,
that every one of them were to be fully persuaded in their own minds,
and they were not to judge one another, much less to persecute one another,
as in Rom. 14.

Where do we ever read in the New Testament that Christ
or the apostles gave forth a law and commandment,
or ordinance, to punish any that were of a contrary opinion, or religion and worship,
to Christ and his apostles,
and would not receive the doctrine of Christ and the apostles, and their spiritual way,
religion, worship, and faith, that Christ and the apostles preached?
Where ever can ye prove this in the New Testament?
And when Christ sent two of his disciples into a
village of the Samaritans to make ready for him,
and when his disciples, James and John saw this, that they would not receive Christ,
they said, '`Lord,
wilt thou that we command fire to come down from heaven and consume them,
even as Elias did?`' But Christ turned, and rebuked James and John, and said,
'`Ye know not what manner of spirit you are of.
For the son of man is not come to destroy men`'s lives,
but to save them.`' Luke 9:52-56.

Now here you may see what a zeal was in these disciples,
that would have had fire to come down from heaven
to consume them that would not receive Christ;
but Christ rebuked them, and their blind zeal without knowledge, and told them,
they did not know what manner of spirit they were of;
for Christ came not to destroy men`'s lives, but to save them.

Now have all these in Christendom, that have destroyed men`'s lives, by burning, hanging,
and imprisonment, or otherwise, and have spoiled people`'s goods,
and ruined them in their estates, because they would not be of their opinions,
nor of their church, faith, religion, way and worship;
are not they of such as have not known what manner of spirit they were of?
And have they not been in a blind zeal without the knowledge of Christ,
who '`came not to destroy men`'s lives, but to save them.`'

And therefore, all they that have destroyed men`'s lives about religion, their worship,
faith, and church, and their opinions, ruined and spoiled the goods of people,
or banished them, or imprisoned them, had they the mind of Christ,
or the spirit of Christ Jesus?
as in Rom. 8:9. and 1 Cor. 2:16. where the apostle saith,
'`But we have the mind of Christ.`' And again the apostle saith,
'`If any man have not the spirit of Christ, he is none of his.`' And therefore,
what spirit hath this been that hath led people in Christendom to destroy men,
both in their lives and estates, such as would not receive their ways, worships,
and opinions?
This is not,
neither hath it been the mind and spirit of Christ Jesus since the apostles`' days,
that hath thus destroyed people in their lives and estates,
for not receiving their opinions, ways, religions, and worships; for the mind,
the spirit of Christ, declares and tells you plainly,
that Christ '`came not to destroy men`'s lives,
but to save them.`' And so they that destroyed men in their lives and estates,
because they would not receive their opinions in their ways, religions, and worships,
they have not known what manner of spirit they have been of.
So they have all done it in a blind zeal, without true knowledge of their own spirits,
or knowledge of the mind and spirit of Christ;
and therefore all such spirits in their blind zeal,
without the knowledge of their own spirits,
or without the knowledge of the mind and spirit of Christ,
are come under the rebuke of Christ,
who is come to '`save men`'s lives,`' and doth not destroy them.
And Christ is '`the same today as yesterday,
and so forever.`' And they that have destroyed men in their lives and estates,
because they would not receive their religion, opinion, way, and worship,
are not come from Christ, neither hath he sent them to do any such work,
neither have their opinions, ways, religions, and worships been of Christ`'s setting up.
And therefore let all Christendom consider,
since they have gone out from the spirit and power of Christ, which was in the apostles,
what spirit they have been of,
that have destroyed so many men in their lives and estates,
because they would not receive their opinions of religions, ways, and worships.

And now consider, when and how this destroying spirit got first into christians.
You may read in 2 Pet.
ii. what a loose company got up, that forsook the right way, and went astray,
and followed the ways of Balaam, who loved the wages of unrighteousness,
and went into the way of Cain, and gainsaying Korah;
and these were spots in their feasts of charity amongst the christians,
though they fed themselves without fear; and were clouds without water,
carried about with winds, trees whose fruits withered, and so without fruit, twice, dead,
and plucked up by the roots, raging waves of the sea, foaming out their own shame,
wandering stars, as in Jude.

Now here you may see these forsook the right way, which is Christ,
and became wandering stars from the firmament of God`'s power,
and so having the form of godliness or christianity, but denying the power thereof;
from such the true christians did, and do turn away; for these were dead,
and made alive by Christ, and dead again, and then plucked up by the roots;
then they were not like to grow nor bear fruit to God.
And these were they that went in the gainsaying way of Korah;
and Korah gainsayed the law and Moses in the old testament;
so these gainsay the gospel and law of life.

And these ran greedily after the error of Balaam, who loved the wages of unrighteousness,
who forsook the right way, and from it went astray.
And these are they who through covetousness and feigned
words have made merchandise of people,
as in 2 Pet. 2:3. 15. And these were they that forsook
the commands and charge of Christ to his ministers,
'`Freely ye have received, freely give;`' but these gainsay the doctrine, command,
and charge of Christ, and gainsay it like Korah.
And these are they that have made such havoc of people`'s
estates because they would not put into their mouths,
nor give them maintainance, since the apostles`' days.
And these are they that have forsaken Christ, the new and living way,
'`who cometh to save men`'s lives,`' and have gone
in the way of Cain since the apostles`' days,
which have killed, and slain,
and destroyed in their lives and estates so many men and
women about their sacrifices and opinions of religions,
ways, and worships.
And this hath been the way of Cain, who was of the wicked one,
'`and slew his brother;`' and wherefore slew he him,
but because Cain`'s own works were evil, and his brother Abel`'s works righteous.
And now let all you and them that have slain their brethren, concerning their offerings,
religion, and worship, consider whether or not your works have not been evil;
and you of the wicked one like Cain your brother,
and them that you have slain their works righteous,
and of more godly lives and conversations than they that persecuted and slew them;
let scripture, and history, and the wise in heart judge.

And now is it not clear,
that all that have destroyed and slain people about their opinions, religions,
and worships, and their offerings and sacrifices, gone in Balaam`'s way for wages,
Korah`'s gainsaying way, Cain`'s slaying way, who was of the wicked one,
and his works evil?
And therefore have not all their works been evil, and of the wicked one,
that have killed, slain,
and destroyed their brethren concerning their opinions of religion, worship, offerings,
and sacrifices, since the apostles`' days;
and have been out of the mind and spirit of Christ, who '`came to save men`'s lives,
and not to destroy them?`' And are they not all of them of the birth of the flesh,
that persecute them that are born of the spirit?
For where did you ever read that the birth of the spirit in the
new testament did persecute any for religion or worship?
and how they have gone from Christ, and what they have gone in,
and so followed the way of the wicked one, and forsaken Christ the way to God.

Though Cain, whose works were evil, and was of the wicked one,
slew and murdered his brother Abel about his religion, offering, and sacrifice;
and you that have slain and murdered your brethren concerning religion,
and their worships, and offerings;
have not you been slayers and murderers like your old brother Cain, and not like Abel,
nor Christ and his apostles, who '`came to save men`'s lives,
and not destroy them?`' And the apostle tells you,
'`that no murderer hath eternal life abiding in him.`' So,
have these that have murdered and slain people since the apostles`' days, for religion,
worship, offerings, and sacrifice, eternal life abiding in them?
And if they have not eternal life abiding in them,
they are not Christ`'s believers nor sheep;
for they that do believe in him are his sheep, and have eternal life. John 10:28.

Here you may see how such man-slayers, and destroyers about religion,
have got up since the apostles`' days;
and have not such built up Christendom with blood and iniquity?
And is not this the cause that Christendom is so all on heaps,
and so barren of the heavenly fruit,
being erred from the spirit and power of Christ that the apostles were in,
and so erred from the spiritual weapons and armour
that the apostle warred withal in the primitive days;
who said, that their weapons were spiritual, and not carnal,
and they did not wrestle with flesh and blood?
But how hath Christendom been filled with carnal arms and armour,
with which they wrestled with flesh and blood,
and destroyed men in their lives and estates,
because they would not be of their opinion in their religions, ways, and worships,
and misapplied the scriptures the apostle speaketh of, which saith,
'`Let every soul be subject to the higher powers,
and to every ordinance of man for the Lord`'s sake,
for the punishment of evil doers,`' as the apostle speaks of in 1 Tim. 1.
So by this means have they persecuted people,
and destroyed men`'s lives for their opinions about their religions and their worships;
though we know that the law is good in its place,
if a man use it lawfully against such as the apostle saith it was made for, to wit,
murderers of fathers and mothers, and man-slayers, and whoremongers,
and defilers of themselves with mankind, and men-stealers, and liars,
and perjured persons.
The law was not made for a righteous man, but for such lawless, disobedient,
and profane persons; and Christ and the apostles did never say,
let every soul be subject to the higher power,
and to obey every ordinance of man for the Lord`'s sake,
for to punish people for their several opinions about religion and worship.
Nay, Christ and his apostles,
did not give forth any laws or commands to punish
and destroy men in their lives and estates,
because they would not be of Christ`'s religion, faith, way, and worship.
For Christ saith on the contrary, '`he came not to destroy men`'s lives,
but to save them;`' and Christ saith,
'`Let the tares and the wheat grow together until the harvest,
which is the end of the world, and then his angels should be the reapers,
and sever the wheat from the tares.`' And if they went into ever-lasting
punishment that did not visit Christ nor his members in prison,
then what will become of them that say they are christians,
and yet cast his members in prison?
And Christ said to Saul, '`Why persecutest thou me,`' that is, Christ in his members?
But when he was converted, then he was persecuted himself;
but the apostle declares the weapons of his warfare, not carnal, but spiritual.
And Christ tells his disciples and believers that they should be killed, and crucified,
and persecuted, and scourged in their synagogues,
and hated of all nations for his namesake;
but Christ gave no such commands to his believers, his disciples, the true christians,
that they should hate, persecute, scourge, kill,
or crucify any that would not receive Christ nor his doctrine; for he saith,
'`he came not to destroy men`'s lives, but to save them.
And them that would not receive the doctrine of Christ and his apostles,
they were to shake off the dust of their feet as a witness,
which should be a testimony against them in the day
of judgment,`' and that was punishment enough.
How have all them in Christendom,
who have destroyed men`'s lives about their opinions in religious ways and worships,
fulfilled the royal law of God, to love their neighbours as themselves,
and to do unto all as they would have others do unto them?
Let all destroyers and persecutors about religion consider this,
and how short they have been of the practice of the law of God,
and the nobility of true christianity;
and let them all go learn this lesson what the Lord saith, '`I will have mercy,
and not sacrifice.`' But they that have killed and destroyed men in their
lives and estates about their sacrifice of religion and worship,
since the apostles`' days, have not they wanted the spirit of mercy,
and have not learned of God what this means, I will have mercy, and not sacrifice?
And have not all you that profess christianity,
that are persecutors and destroyers of men`'s lives, said the Lord`'s prayer,
'`Forgive us our trespasses,
as we forgive them that trespass against us?`' And Christ saith,
'`If you forgive men their trespasses, your heavenly Father will also forgive you;
but if you forgive not men their trespasses,
neither will your heavenly Father forgive you your trespasses.`' Matt. 6, 12. 14, 15.

I pray consider how short of the practice of this prayer of Christ you have been,
that have destroyed men in their lives and estates,
because they would not be of your opinion in their religion and worship;
whether you in this have done unto others, as you would have others do unto you?
if not, you cannot but confess you have acted contrary to the royal law of God,
and the gospel of salvation.

And the apostle bids Titus put the christians in
mind to be subject to principalities and powers,
and to obey magistrates, and to be ready in every good work. Tit. 3:1.

And this is according to the scripture, in Rom. 13. where the apostle saith,
'`Let every soul be subject to the higher powers;`' and 1 Pet. 2:13-14,
'`Submit yourselves to every ordinance of man for the Lord`'s sake,
for the punishment of evil doers; which is for the praise of them that do well.`' Mark.
This was for the punishment of such evil doers as the apostle speaks of, 1 Tim. 1.
but he doth not say that they were to be subject to every
ordinance of man for to punish people for matters of faith,
religion, and worship; for the apostle clears that, and makes a distinction,
when he saith to the church of Christ, the Colossians,
'`that if ye be dead with Christ from the rudiments of the world,
why as though living in the world are ye subject to ordinances, (touch not, taste not,
handle not,
which all are to perish with the using,) after the commandments and doctrines of men.`'

So you may see here, ordinances, and doctrines,
and commandments of men concerning men`'s religions, ways, and worships,
which ordinances, doctrines, and commandments of men,
christians in the primitive time were not to taste, touch, nor handle;
and therefore they suffered by the Jews`' outward worshippers,
because they could not join with them in the traditions of their fathers,
and testified that Christ was come,
and '`was made a priest not after the law of a carnal commandment,
but after the power of an endless life.`' And the
Jews`' first covenant had ordinances of divine service,
and a worldly sanctuary, and their priests, with their outward offerings, sanctuaries,
and sacrifices; but that priesthood '`was changed,
and the law by which it was made.`' Heb. 7:12. ix.
1+++.+++ And the apostle saith, '`Christ hath abolished in his flesh the enmity,
even the law of commandments, contained in ordinances, for to make in himself of twain,
(namely, Jews and Gentiles,) one new man, so making peace,
that he might reconcile both unto God in one body.`'

So here you may see these commandments and ordinances among the Jews in the old testament,
when Christ was come in his new testament, he abolished them;
and therefore the believing christians, that followed Christ Jesus,
suffered by the unbelieving Jews,
because they would not follow the Jews`' law and commandments,
and their ordinances and services, and their priests;
which law and priesthood Christ hath changed,
and abolished the law of commandments and ordinances,
as in Heb. 7:12. and Eph. 2:15-16.

And likewise the laws, ordinances, and commandments of Diana`'s worshippers,
and the Romans, and other heathens, they were not to be subject to, nor touch, nor taste,
nor handle after the commandments and doctrines of men.
The christians, though they lived in the world,
yet they were not to be subject to the rudiments of the world,
nor the commandments nor doctrines.
Nay, they were not to taste them, nor handle them, that were dead, with Christ from them.
Col. 2:20-22.

So here you may see the apostles made a clear distinction between the ordinances of men,
and the higher power which is for the punishment
of such evil doers as the apostle speaketh of,
and the praise of them that do well; which was not to punish people for matters of faith,
and serving and worshipping God,
but for such evil doers as the apostle speaketh of 1 Tim. I.
And likewise such ordinances and commandments, and doctrines of men, yea,
of the Jews and Gentiles, concerning men`'s religions and worships,
which the christians were not to touch, taste nor handle;
and happy had all Christendom been if they had kept
in the spirit of Christ the apostles were in,
and that they might have made the same distinction as the apostles did.

And now if you do say;
who have destroyed men in their lives and estates for not obeying your doctrine,
ordinances and commandments, concerning your opinions of your religion and worships,
that they are not of men, and that they have not been set up since the apostles`' days,
neither by such as have erred from the spirit of Christ Jesus,
'`who came to save men`'s lives,
and not to destroy them,`' then you are to prove by the scriptures of the new testament,
where ever did Christ and the apostles give forth any such ordinances, doctrines,
and commandments, to persecute, or imprison, or kill,
or destroy such as would not be of their way, faith, religion, and worship,
prove this by the scripture of the new testament from Christ and his apostles if you can;
or else confess that your doctrines, ordinances and commandments are of men,
and are of men`'s inventing,
by which you have destroyed people in their lives and estates,
for matters of religion and worship,
not to be from the spirit of Christ and his apostles,
and that you have not had the spirit of Christ to lead you into this destroying work.
For Christ saith, '`he came not to destroy men`'s lives,
but to save them.`' And we know that the prophets, Christ, and the apostles,
they that did persecute them,
and put them to death in their blind zeal without knowledge,
not knowing what spirit they were of themselves,
they did not persecute Christ and his apostles and prophets as true men,
but as deceivers; so hath this spirit done in Christendom since the apostles`' days.
'`But God will reward every one according to their works.`' But where did ever
Christ and his apostles in the New Testament give forth any such ordinances,
doctrines, or commandments, to punish, imprison, or destroy heretics, schismatics,
blasphemers, or seducers, or Jews or Gentiles, that would not receive him?
Prove this if you can out of the New Testament,
or else acknowledge such to have been heretics, schismatics, blasphemers, and seducers,
that have not had the spirit of Christ, which have punished, imprisoned,
and destroyed men in their lives and estates, which have been the servants, and lambs,
and sheep of Christ, for following him, and not obeying your ordinances,
and commandments, and doctrines,
which you never had from the spirit of Christ nor his apostles,
"`who came to save men`'s lives, and not to destroy them.`'

Hath not christendom in many places been like a slaughterhouse, imprisoning, beating,
banishing, hanging, killing, and destroying, and burning,
about their opinions of their religions and worships,
and acted not like the royal law of God,
'`to do unto others as they would have others do
unto them;`' and not in the nobility of true christianity,
in the spirit of Christ Jesus, '`who came to save men`'s lives,
and not to destroy them;`' but more like the god of the world,
who abode not in the truth, who is called a destroyer.

And if Peter and Paul, and the rest of the apostles, who said,
'`Let every soul be subject to the higher powers,
and to every ordinance of man for the Lord`'s sake,
for the punishment of such evil doers,`' as the apostle speaketh of,
had intended for the punishment of people for religion; I say again,
if the apostles did mean that every soul should be subject to the higher power,
and to every ordinance of man,
concerning the doctrine and commandments of men in matters of religion and worships;
then why did the apostles and christians suffer by the Jews, Gentiles, or heathens,
and by Cesar, and in the ten persecutions?
You may say, why were not their souls subject to the higher powers among the Jews,
and to Caesar; and why did not they obey every ordinance of man,
to follow their doctrines and commandments, concerning worshipping and religion?
If that the apostle meant when he said, '`Let every soul be subject to the higher powers,
and to every ordinance of man,`' concerning their doctrines, and commandments,
and religions, and worship, and their ordinances; then you may say,
that the apostles Paul and Peter had forgot themselves, for to write in their epistles,
that other christians`' souls should be subject to the higher power,
and to every ordinance of man, and they themselves were not subject to the Jews,
Gentiles, nor heathen, nor Caesar`'s doctrines, nor commandments, nor ordinances,
concerning religion and worship?
But the apostles declared to the heathen or Gentiles,
and against the shadows among the Jews, and preached Christ the substance was come,
and their shadows fly away;
and so the apostles made a distinction between every ordinance of man,
for the punishment of such evil doers, as they speak of, and the doctrines,
and ordinances, and commandments of men, concerning religion and worship,
which were not to he touched, tasted, nor handled.

So have not all you that have brought these scriptures,
that '`every soul must be subject to the higher powers,
and to obey every ordinance of man for the punishment of evil doers,`' misapplied them,
and turned them to punish people,
and lay them upon people that differ from you in your opinions of religions and worships?
which the apostles never did, nor intended any such thing;
for the apostles warred and wrestled with the Jews and Gentiles,
concerning their religions, doctrines, and worships, with spiritual armour,
and spiritual weapons, and so did not wrestle with flesh and blood with carnal weapons,
and destroy men`'s lives about religions and worships,
as others have done since their days.
And if that you do say, that '`every soul must be subject to every higher power,
and to every ordinance of man,`' concerning religion and worship,
and their doctrines and commandments,
then you must be subject and conform to all religions, worships,
and doctrines in the world, and to the Jews, Turks, and heathen,
and all the sects in the world that will plead to be subject to their ordinances,
commandments, and doctrines; and if the apostle had meant so,
then had they never suffered, nor been imprisoned, nor put to death.

But the apostles made a distinction of being '`subject to the higher powers,
and to every ordinance of man for the punishment of such evil doers,`' as he speaks of,
and the doctrines, and commandments, and ordinances of men,
concerning religion and worship, which was not to be touched, tasted, nor handled;
and therefore the apostle doth not say,
that any should be punished for not obeying such commandments and doctrines of men,
concerning religion.

And also the apostle doth not say,
that the christians should be punished for not being subject,
and their not obeying the Jews`' law, and commandments, and ordinances,
that commanded their altars, sanctuaries, temples, offerings, sacrifices, and priests,
and their divine services and worships; for they knew that Christ was come,
and had changed the law and priesthood by which it was made, and had abolished the law,
and commandments, and ordinances, and offerings of the Jews`' ceremonies and traditions,
for Christ was offered up once for all.
And so as the apostle rightly and truly saith, we know that the law is good in its place,
if a man use it lawfully, which was not made for the righteous,
but for '`the punishment of evil doers, unholy, profane,
murderers of fathers and of mothers, and men-slayers, and whoremongers,
and them that defile themselves with mankind, men-stealers, liars,
perjured persons.`' And such lawless, disobedient,
ungodly sinners the law was made against;
and the christians their souls were to be subject '`to the higher powers,
and to every ordinance of man for the Lord`'s sake,
for the punishment of such evil doers,`' and the praise of them that do well.
And so the apostle doth not say, that the soul should be subject to every higher power,
and to every ordinance of man for the Lord`'s sake
for the punishment of people that disobey the doctrines,
commandments, and ordinances of men, concerning religion and worship.

But the apostle in this made a clear distinction betwixt
the ordinances of men for the punishment of evil doers,
and the doctrines, commandments, and ordinances of men concerning religion and worship,
which were not to be touched, tasted, nor handled.
And the apostle saith,
'`Christ by the grace of God tasted death for every
man.`' Heb. 2:19. And again the apostle saith,
'`Christ is a propitiation for our sins, and not for our sins only,
but for the sins of the whole world.`' 1 John 2:2.

And also the apostle saith in 1 Tim.
ii. I to the 8th, '`I exhort therefore, that first of all, supplications, prayers,
intercessions, and giving of thanks be made for all men, for kings,
and for all that are in authority,
that we may lead a quiet and peaceable life in all godliness and honesty.
For this is good and acceptable in the sight of God our saviour.
Who would have all men to be saved, and to come unto the knowledge of the truth.
For there is one God, and one mediator betwixt God and men, the man Christ Jesus.
Who gave himself a ransom for all, to be testified in due time.
Whereunto I am ordained a preacher, and an apostle,
(I speak the truth in Christ and lie not,) a teacher of the Gentiles in faith and verity.`'

Now, here you may see what a good and general doctrine
the apostle preached in the primitive times,
that prayers and intercessions be made for all men,
yea for kings and them that be in authority,
and this is good and acceptable in the sight of God our saviour,
'`who would have all men to be saved,
and come to the knowledge of the truth.`' Now you
that do destroy men`'s lives about their opinions,
religions, and worships, you have not patience to pray for all men,
etc. that they may repent and be saved, and come to the knowledge of the truth;
therefore your practice cannot be acceptable in the sight of God the saviour,
that destroy men`'s lives about religion and worship,
whereas ye should pray to God for all men,
who would have all men to be saved and come to the knowledge of the truth;
for there is one God, and one mediator betwixt God and man, the man Christ Jesus,
'`who gave himself a ransom for all, to be testified in due time.`'

Now if Christ hath given himself a ransom for all, to be testified in due time,
and this doctrine Christ had ordained the apostle to preach, and said,
'`he spake the truth in Christ and lied not,`' what spirit is that which
hath led people to destroy men and women about religion and worship?
Whereas God would have all men to be prayed for, and to be saved;
and Christ hath given himself a ransom for all,
'`to be testified in due time,`' and he '`came not to destroy men`'s lives,
but to save them.`'

And therefore,
what spirit is this that hath destroyed men`'s lives
about religion and worship since the apostles`' days,
seeing Christ hath given himself a ransom for all?
Surely it is not the spirit of God nor Christ?
For he would have all men to be saved,
'`and would have all men to be prayed for,`' and
all to come to the knowledge of the truth;
and Christ that '`gave himself a ransom for all,`'
is the '`one mediator betwixt God and man.`'

And that impatient spirit, that hath destroyed men`'s lives,
concerning religion and worship, and hath preached up persecution in their blind zeal,
without true knowledge, was not like to wait in patience, nor to pray for all men,
that all men might be saved; that Christ who gave himself a ransom for all,
'`might be testified in due time;`' and therefore
that spirit that destroyed them in their own time,
hath not been the spirit of Christ, who gave himself a ransom for all,
to be testified in due time.`' And Christ,
'`who by the grace of God tasted death for every man,
and hath given himself a ransom for all,
and is a propitiation for the sins of the whole world.`'
So hath not he then purchased all mankind by his death,
and ransomed them, and would have all men to be saved,
'`who came not to destroy men`'s lives, but to save them?`' And, therefore,
what spirit hath that been in Christendom, and from whom,
that hath destroyed so many men and women, concerning their religions, and opinions,
and worships, in Christendom, since the apostles`' days?
And have they not destroyed such as Christ hath purchased, ransomed, and died for,
and is a propitiation for; seeing that Christ '`gave himself a ransom for all,
and tasted death for every man,
and is a propitiation for the sins of the whole world,`'
and '`came not to destroy men`'s lives,
but to save them?`' And so let the spirit of Christ be judge in this matter.
From him that is a lover of God, and Christ, and all men,
that desire liberty and eternal happiness in Christ Jesus.
Amen.

It is said, '`Judah and Israel dwelt safely, every man under his vine,
and under his fig tree, from Dan even to Beersheba,
all the days of Solomon.`' 1 Kings 4:25. And what
a rich and glorious kingdom had Solomon in his days,
when every man sat under his vine and fig tree in his kingdom?
And in Micah 4:4. '`Every man shall sit under his vine, and under his fig tree,
and none shall make them afraid;
the mouth of the Lord of hosts hath spoken it.`' And Zech. 3:10. '`In that day,
saith the Lord of hosts, shall ye call every man his neighbour, under the vine,
and under the fig tree.`' And is not this the day of Christ?
For doth not Christ say, '`I am the vine,
and ye are the branches.`' John 15. and Solomon saith, '`My mother`'s children,
etc. they made me keeper of the vineyards,
but mine own vineyard have I not kept.`' Song. 1:6.

Now all ye that are made keepers of vineyards,
see that your own vine and vineyard is kept and enclosed with God`'s power,
and instead of keeping others`' vineyards, ye do not destroy them and your own.
And let all that profess God and the Lord Jesus Christ, who is the vine,
sit under him their vine, peaceably and safely in this gospel day of Christ,
who is the new and living way to God; Heb. 10:20.
and to serve God through Christ in newness of spirit;
and also to walk in newness of life; Rom. 6:4. chap.
vii. 6. and to sit under their vine and fig tree,
and none to be made afraid or terrified by persecutions, imprisonments,
or spoil of their goods, by laws or ordinances,
which were made '`for the punishment of evil doers, murderers of fathers and mothers,
and man-slayers,`' etc. such as the apostle speaks of, the law was made against.
1 Tim.
i.

For Christ Jesus never made or gave any law, commandment, or ordinance to imprison,
or spoil the goods of any for not believing in him,
much less against those that did believe in him, and sat under him,
and abode in him the vine, who hath enlightened all mankind,
that they might believe in him, and sit under him, and abide in him the vine.
And they that do not abide in him, nor sit under him in his light and grace,
but hate his light, and turn his grace into wantonness, such by the light are condemned,
and that will be punishment enough upon them. John 8:19.
And Christ saith,
'`He will reward every man according to his works
and deeds.`' And is not this in matters of religion,
who serves God through him, and who serves him not?
And, therefore, '`Let the tares and the wheat grow together, till the harvest,
which is the end of the world,`' as Christ saith.
Matt. 13:30 to 43. For he did not give any ordinance or command
to any to be '`pluckers up of tares`' in the field,
which is the world; but on the contrary,
he gave a command to stop them that would have been plucking up.
And his heavenly wisdom and care was, '`Lest while ye gather up the tares,
ye root up also the wheat with the tares.`'

And Christ hath enlightened all mankind, and his grace has appeared to all men,
to teach them, and to bring their salvation,
and his gospel is preached to every creature under heaven.
Now if they do not abide in the light, grace, and gospel of Christ, who is the vine,
he will reward every man according to his works.

And the apostle saith, Rom. 8:26-27, '`The spirit also helpeth our infirmities;
for we know not what we should pray for as we ought,
but the spirit itself makes intercession for us, with groanings which cannot be uttered.
And he that searcheth the hearts, knoweth what is the mind of the spirit,
because he maketh intercession for the saints, according to the will of God.`'

So here you may see the apostle did not tie up the
church of Christ to only one outward form of prayer,
but left them to the spirit of God, '`which helpeth our infirmities,
and makes intercession,`' etc. teaches us to pray as we ought,
'`with sighs and groans that cannot be uttered.`'

And Acts 2:17. Joel 2:28. '`God poureth out his spirit upon all flesh,`' namely,
men and women: that all in the spirit of God might pray to him, and serve, fear,
and worship him in his spirit and truth; and not to grieve, rebel against, vex,
or quench the motions of the spirit of God; for if they do, they go into bondage,
and bring God`'s judgments upon them.
But they that are led by the spirit of God, are his sons and daughters;
and where the spirit of the Lord is walked in, and they are led by it, there is liberty,
and the fruits of the holy spirit of God will show themselves forth, which are, '`love,
joy, peace, long suffering, gentleness, goodness, faith, meekness, temperance,
righteousness and truth,
proving what is acceptable unto the Lord;`' against such there is no law. Gal. 5:22-23.
Eph. 5:9.

G+++.+++ F.

London, the 30th of the 3d month, 1685.

Thus speaketh the Lord of hosts, '`Execute true judgment, and show mercy and compassion,
every man to his brother.`' Zech. 7:9.

And the Lord, saith, '`He hath showed thee, O man, what is good;
and what doth the Lord require of thee, but to do justly, and to love mercy,
and to walk humbly with thy God.`' Micah 6:8.

And the Lord saith, '`I desire mercy, and not sacrifice; and the knowledge of God,
more than burnt offerings.`' Hosea 6:6.

And Christ saith unto the Jews, '`Go ye and learn what that meaneth,
I will have mercy and not sacrifice.`'- Matt. 9:13.

And Christ saith, '`Blessed are the merciful,
for they shall obtain mercy.`' Matt. 5:7.

And again Christ saith, '`Be ye merciful, as your heavenly Father is merciful.`' Luke 6.

[.blurb]
=== Postscript

After Cyrus, king of Persia,
had made a proclamation throughout all his kingdom in writing, saying,
'`Thus saith Cyrus, king of Persia,
the Lord God of heaven hath given me all the kingdoms of the earth,
and hath charged me to build him a house in Jerusalem,
which is in Judah.`' And this proclamation was, that all the Jews in all his kingdoms,
and wheresoever they sojourned, that had been in captivity,
should have their liberty to go into the land of Judah, and build Jerusalem,
as in Ezra 1.

Now when the adversaries of the Jews that had been in captivity,
saw that the Jews did begin to build, they hired counsellors against them,
to frustrate their purpose of building, etc. all the days of Cyrus,
until the second year of the reign of Darius, king of Persia,
and in the beginning of the reign of Ahashuerus,
these accusers of the Jews wrote unto him accusations
against the inhabitants of Judah and Jerusalem.
And they wrote to Artaxerxes, king of Persia, against the Jews, namely,
Rehum the chancellor, and Shimshai the scribe, and their companions the Dinaites,
the Apharsachites, the Tarpelites, the Apharsites, the Archetites, the Babylonians,
the Susunchites, the Dehatites, and the Elumites, and the rest of the nations, etc.
Ezra 4.

The copy of the letter these sent to Artaxerxes: '`Be it known unto the king,
that the Jews which came up from thee to us, are come to Jerusalem,
building the rebellious and bad city, and have set up the walls thereof,
and joined the foundations, etc.
Now, because we have maintainance from the king`'s palace,
it was not meet for us to see the king dishonoured;
therefore have we sent and certified the king that search
may be made in the book of the records of thy fathers;
so shalt thou find in the book of the records and know,
that this city is a rebellious city, and hurtful unto kings and provinces.
And that they have moved sedition within the same of old time,
for which cause was this city destroyed,
namely Jerusalem.`' And these enemies of the Jews, (heathens,) which were pensioners,
and had maintainance from the king`'s palace, which writ to the king Artaxerxes,
and the king upon these enemies, pensioners, and informers,
sent a letter to them that they should stop the Jews from building Jerusalem;
and they did stop the Jews from building Jerusalem
until the second year of Darius king of Persia.

Now here you may see what kind of pensioners and
informers these heathens were against the Jews,
who had been long in captivity by the Babylonians, and the Assyrians,
though Cyrus before had opened the two leaved gates, both of the Assyrians,
and the Caldeans, for the Jews to go out of captivity,
as in 2 Chron. 36:22. Jer. 25:12. and 29:10. Isa. 44:28. and 45:13.

And now is it not a shame that any that do profess christianity
should take a text from these heathen pensioners,
informers, that had maintainance from that heathen king`'s palace Artaxerxes,
that were the informers against the Jews which had been so long in captivity;
and also to inform the king so contrary to Cyrus`'s proclamation and command,
which were for the Jews to build Jerusalem, etc.
And now for any one that professes christianity,
to make a text of these pensioners and informers words, and apply it to christians,
to destroy men in their lives and estates, about religion and worship,
which is quite contrary to the command of Christ, who saith,
'`he came not to destroy men`'s lives,
but to save them.`' And so through the means of those pensioners, (heathen,) informers,
they hindered Jerusalem from being builded till the second year of Darius,
and then the Jews began again to build Jerusalem, and the temple.
And then Tatnai the governor, and Shetharboznai, and their companions, the Apharsachites,
the pensioners,
the old enemies of the Jews that had risen against them in Artaxerxes`'s time,
they said unto the Jews in Darius`'s time, '`Who commanded you to build Jerusalem,
and make up the walls?`' And they asked the elders of the Jews their names,
that they might certify them to the king Darius?
But the Jews answered and said unto them,
'`that they were servants of the God of heaven and earth.`'
So these enemies of the Jews wrote a letter to Darius,
concerning them against the building of Jerusalem and the temple;
and Darius caused search to be made in the records of Babylon,
and he found the proclamation and decree of Cyrus,
which he gave unto the Jews to build Jerusalem. Ezra 5:6.

And then Darius made a decree, and sent it to Tatnai the governor, and to Shetharboznai,
and their companions the Apharsachites, who had been the enemies of the Jews,
and bade them, '`let the house of God alone,
let the governors of the Jews and elders build a
house in its place.`' And so this Darius made a decree,
'`that of the king`'s goods, and even of the tribute, they should assist the Jews,
and not hinder them in their building; and whosoever did alter this decree or word,
let the timber be plucked down from his house, and being set up,
let him be hanged thereon,
and let his house be made a dunghill for this.`' And Artaxerxes said, '`I make a decree,
that all they of the people of Israel, etc. in my realm,
they should go up to Jerusalem with Ezra;`' and said,
'`Whosoever will not obey the law of thy God, and the law of the king,
let judgment be executed speedily upon him; whether it be unto death, or banishment,
or confiscation of goods, or to imprisonment.`' Ezra 7:13. 26.

So according to the commandment of Cyrus, Darius, and Artaxerxes, kings of Persia,
the Jews finished Jerusalem, and the house, in the sixth year of Darius. Ezra 6:14-15.
Now here you may see what strict laws and
decrees these kings made against these heathen informers,
pensioners, and their company, who would have hindered the Jews,
when they went out of captivity, from building Jerusalem and the temple,
contrary to Cyrus`'s command.
Ezra 1.

But you may see here that these kings stopped the Jews`' enemies and evil doers,
that would have destroyed the Jews; and these decrees,
laws and ordinances were for the praise of them that do well.
But these informers and pensioners said to the king Artaxerxes,
'`Jerusalem was a rebellious city, and was hurtful to kings and provinces,
and that they had moved sedition.`' In Ezra 4. from the
8th to the 19th. And though these enemies of the Jews,
and heathen pensioners and informers,
whose wicked words did prevail with Artaxerxes for a time,
yet you see that king Artaxerxes gave a strict commandment, with these punishments,
against them that should hinder the Jews; as in Ezra 7:12-13. 26.

And likewise Darius, in chap.
vi. 11. So that according to the command of Cyrus, Darius, and Artaxerxes,
kings of Persia, Jerusalem and the temple were built. Ezra 6:14.

So you may see, though Artaxerxes had made a decree,
which did stop the Jews from building until the second year of Darius,
upon the information of those heathen pensioners,
who called Jerusalem '`a bad rebellious and seditious city,
and hurtful to kings,`' as in Ezra 4:12. 15; yet in Ezra 7,
Artaxerxes makes a decree for the encouragement of
the Jews to go up to Jerusalem and build the temple;
'`and whosoever disobeyed the law of God, and the law of the king,
judgment was to be executed speedily upon them, whether unto death, or banishment,
or confiscating of goods,
or imprisonment.`' So this was a torment to those pensioners the informers,
who had not their wills upon the Jews,
who had formerly got a decree of the king against the Jews to hinder them from building;
the same king makes another decree, '`for them to assist the Jews;
that whosoever would not do the law of God, and the law of the king,
judgment was speedily to be executed upon them, whether it be unto death, banishment,
confiscation of goods, or imprisonment,`' as it is said before.
Now here, as the apostle saith, '`the law was good in its place,
for the punishment of evil doers,
and for the praise of them that do well;`' as in 1 Tim. 1:8-9. and 1 Pet. 2:13-14.

So here you may see none of these laws were made against religious
people for meeting together to serve and worship the living God,
that made them; for the law of God and the king were for the punishment of evil doers,
that would have destroyed God`'s people;
for God nor Christ never made a law for punishing people for serving and worshipping him;
but God`'s law was to protect his people from murderers and man-slayers, etc.
(and the punishment of such evil doers,) which was for the praise of them that do well;
and serve God, and worship him in spirit and truth.
Yea, Cyrus, Darius, and Artaxerxes`' decrees stopped those heathen informers,
and pensioners, and enemies to the Jews, that wrote to the king against the Jews,
to hinder them from building the city.
So the law is good in its place, if it be used lawfully; and they that use it lawfully,
put a difference between the precious and the vile, and them that serve God,
and them that do not,
which law is for the punishment of such evil doers as the apostle speaketh of,
1 Tim. 1:1 Pet.
ii.

But the apostle doth not say, it is for punishing people concerning religion,
and for serving and worshipping God in the spirit and truth;
for Christ and the apostles have given forth no law, nor ordinance, nor decree,
to punish people, or to banish people, or to imprison people,
or pluck down the timber of their houses, to set up gallows to hang people,
and put them to death, and make a dunghill of their house, or spoil their goods,
and make confiscations of their goods.
No, Christ nor the apostles never gave forth such a law or ordinance,
for the punishing of people for serving and worshipping of God that made them,
or to punish such that differed from them in faith and matters of religion.
For Christ said, '`he came not to destroy men`'s lives,
but to save them.`' So he is an example of meekness and patience.

The king of Assyria,
the Lord did not suffer him to carry away the ten tribes into captivity,
for the account of religion, or the not conforming to his religion;
for the ten tribes of the Jews they had left all the commands of the Lord their God,
and did not regard God, nor his law, nor his prophets.
2 Kings xvii.

And the two tribes of the Jews,
the king of Babylon did not carry them out of Canaan into captivity,
because they were not subject to his religion, though they had forsaken the Lord,
and his law and religion, that he had taught them,
and regarded neither the Lord nor his prophets.

And the informers they did not inform Artaxerxes against the Jews,
upon the account of not being of their religion.

And those decrees or laws that Darius and Artaxerxes made,
were not against those informers, and pensioners, and such like heathens,
because they would not be of their religion;
but that they and others would have hindered the Jews from building their city,
etc. when they went out of captivity.

And therefore all you consider, that have or do punish,
or persecute people about religion, faith, worship, and serving the living God,
what became and was the end of all them that persecuted the prophets, Christ,
and his apostles, and all the martyrs since the apostles`' days.
And what do ye read is the end of the beast, whore, and dragon,
that killed and drank the blood of the martyrs, prophets, and saints,
spoken of in the Revelations?

And therefore, let all that profess christianity, learn of Christ,
who teacheth you to love one another, and love enemies,
and commands you '`to let the wheat and the tares grow together until the harvest,
which is the end of the world, and then he will send his angels,
which will separate the wheat from the tares.`' Matt. 13:30 to 41.

G+++.+++ F.
