[.style-blurb, short="True Liberty and False"]
== A distinction between true liberty and false. By G. F.

God pouring out of his spirit on all flesh, both on sons and daughters,
handmaids and servants, etc. all are to walk in the liberty of this holy, pure,
peaceable, gentle spirit of God, that keeps in humility, and in tenderness and kindness,
and leads into righteousness, godliness, and holiness, and into modesty, sobriety,
virtue, and chastity, and into things that be of a good report.
In this holy spirit of God is the pure holy liberty, the fruits of which,
are love and peace, etc.
And this holy pure spirit of God leads out of strife, contention, hatred, malice,
and envy, and all unrighteousness, and ungodliness,
and false liberty of the will and the flesh,
and the inordinate and loose affections that are below.
And if the will and the flesh and inordinate affections have their loose liberty,
they set the whole course of nature on fire with the unruly will and tongue,
which is to be limited, kept down, and mortified with the holy spirit of God;
in which spirit is the unity kept, which is the bond of peace,
in the church of Christ among all true christians,
that are called the '`household of faith,`' and '`of
the son of God,`' who is over his house.

And the holy, divine, pure, and precious faith, which is the victory,
and purifies the heart, Christ is the author and finisher of;
and the mystery of this faith is held in a pure conscience;
by which faith all the faithful have access to God, and in it do please God.
And in this faith all the household of God have unity and liberty,
who are called '`the household of faith.`' Now this
pure holy spirit of God he pours upon all flesh,
and the holy divine faith cannot admit nor join to any loose or false liberty,
to the will of the flesh, or inordinate affections, or to that which is immodest,
or not virtuous, or unchaste, or uncivil, or of an evil report;
or to any thing that is unreasonable, or unjust, or ungodly;
for such things are to be mortified by the holy spirit of God,
which the unity and liberty are in.
And the holy divine faith purifies God`'s people from such things,
and gives victory over them, which faith works by love;
and the pure conscience hath its liberty, which it is held in,
and in it all the faithful are in unity, in which they know they please God.
And this is the faith of God`'s elect, by which the just do live,
which gives them victory over the devil and his works,
and that which is unjust and unrighteous,
and purifies the hearts of such as be defiled by it, from that which defiles it.
And Christ Jesus enlightens every man that comes into the world,
which light is the life in Christ the word, by whom all things were made.
And the grace of God, which brings salvation hath appeared to all men.
Now in this light and life of Christ, and in this grace of God, which brings salvation,
is the true liberty,
and brings to stand fast in the true liberty in Christ the light and life,
who makes them free, from all bondages and false liberties;
for all liberties out of the spirit of grace, and light, and life of Christ,
are bondages; for light cannot have unity with the spirit of darkness,
the works of darkness.
And the light of Christ gives both understanding and knowledge
of all false liberties out of Christ Jesus,
and cannot join with them in those liberties which
are out of the light and grace of Christ,
no more now than the apostles and church in the primitive
times could with such in their days.

The Jews who opposed Moses and the prophets in their ages, and spake against them,
who were great professors of the scriptures,
did not come into the unity and liberty of the holy ghost the prophets were in.
The holy prophets of God were subject one to another in the spirit of God;
but the professing Jews that erred from the spirit, and rebelled against it,
were not subject to the spirit of the prophets,
and so were neither in the liberty nor unity in the spirit of God.
And when Christ came, who was conceived by the holy ghost,
etc. and holy men of God who spake forth scriptures, as moved by the holy ghost;
the Jews who professed all these scriptures, that were given forth from the holy ghost,
opposed Christ and the holy men, and resisted the holy ghost:
these did not come into the liberty of Christ Jesus,
and the liberty or communion of the holy ghost.
And all those in the apostles`' days, that made an outward profession of christianity,
which the apostles and the churches were troubled withal,
and some of the seven churches were troubled with also,
which were as raging waves of the sea, which foamed out their own shame,
and casting up their mire and dirt, in Cain`'s way of envy, Korah`'s way of gainsaying,
and in the error of Balaam, from the spirit of God; wells without the water of life,
trees without holy fruit, twice dead, dead in Adam, and made alive, dead again,
and plucked up by the roots; that cannot grow in the life of Christ,
and are become synagogues of Satan; puffed up with high swelling words of vanity,
and have fair words and good speeches, but wandering stars,
from the firmament of God`'s power,
not fit for the innocent to steer by to the heavenly Jerusalem,
no more than the outward mariners to steer their course
by the outward wandering stars to an outward port.
And such as the apostle calls fierce despisers of them that are good, incontinent,
covenant breakers, having a form of godliness, but deny the power thereof,
which were and are to be turned away from.

Though such as these before mentioned, in the apostles`' days, and now,
may profess liberty for a cloak, to cloak their evil spirit, and its fruits;
yet all such actions are not according to Christ, and the grace of God;
for the grace of God has no union with fierce despisers of them that are good,
nor with such as are puffed up with high swelling words of vanity.
And though they have good words and fair speeches, and an outward form of godliness,
yet deny the power thereof, and so deny the free liberty in the power of God,
and so the liberty in Christ Jesus, and so the liberty in his grace and light,
which is a gracious liberty, that brings people into favour with God.
And the apostles of the true churches, did withstand all loose and false spirits,
and had no unity nor fellowship with them of Cain`'s, Korah`'s, Balaam`'s;
trees without fruit, wandering stars, wells without water, raging waves of the sea,
casting up mire and dirt, as they do now against the righteous.
Such as bear these fruits their liberty is not in the spirit of grace,
nor in the light and life of Christ.
And such the church of Christ in the apostles`' days, and now have not unity with,
neither can they join with them in unity and liberty,
that are not in the spirit of grace, light, and life in Christ Jesus,
in which all true liberty is, in Christ the truth that makes them free.

And that spirit that leavens people into malice, hatred, envy, evil surmising,
false jealousies, and into rage, and the root of bitterness,
and into disputings and janglings, and whose words eat like a canker,
and they who make a profession in words of the truth, and live not peaceable,
and walk not in Christ, but are puffed up with many idle notions and vain conceits;
such fruits are not from the spirit of grace, light and life of Christ,
nor in true faith, which works by love, in which true unity is, and liberty,
and love that bears all things, love that doth not envy, and is not puffed up.
For they that profess knowledge and faith, and want this love of God,
they were called as tinkling cymbals, and sounding brass, in the apostles`' days,
and so they are now.
And God`'s people cannot set up a tinkling cymbal and sounding
brass for the life of righteousness and truth;
though a tinkling cymbal and sounding brass may deceive the simple,
and such may devour them.
But it is love that unites all the members of Christ together, to him the head;
in which love they are built up together a spiritual household.
And the wisdom that is pure and peaceable, gentle and easy to be entreated,
this is from above.
But the wisdom that is from below is earthly, sensual and devilish;
and men that are in this wisdom, and pretend knowledge and faith,
without the love of God, and are incontinent, fierce, despisers of those that are good,
with their fair words and good speeches,
and puffed up with high swelling words of vanity, vain disputers, janglers,
'`in a form of godliness,
but out of the power,`' with such the church of Christ had never unity.
And that liberty and those fruits are not in the spirit of grace,
and light and life of Christ; and by their fruits such were and are known to them,
whose liberty and unity is in the light and grace which is in Christ Jesus;
and in the grace of God that hath appeared to all men,
and in his spirit which he hath poured on all flesh, the light,
which is the life in Christ, which enlightens every man that comes into the world,
all men and women are to have their liberty in Christ Jesus,
in which they all have unity, and an everlasting liberty and unity,
and fellowship in the everlasting son of God, in Christ the head;
and in Christ the head they are joined together by his light, life, and spirit of grace.
And all that walk contrary to the light, life, and spirit of grace,
let them profess what they will, they are not in the true liberty and true freedom,
nor in the true fellowship with the Father and the son, and his people;
for the true liberty and unity are in the spirit, light, and life of Christ,
to which all men and women, from the first have been directed,
that in it they may all live and walk in the true freedom, liberty and unity,
and fellowship with the Father and the son, and one with another.
And the true freedom and liberty are in the gospel, '`in the glorious gospel of life,
peace and salvation;`' which gospel is the '`power of God, preached to,
and in every creature under heaven.`' And every one`'s conversation
must be according to this glorious gospel of life,
peace and salvation.
For they who order their conversation aright by the gospel,
do see and receive this gospel of peace, life, and salvation.
And in this gospel, the power of God, is the true, glorious,
peaceable freedom and liberty in the life and salvation in Christ Jesus.
And all that do profess the gospel of Christ, the power of God, in words,
and do not live and walk in the gospel the power of God,
they are in bondage under the power of darkness,
and are out of the peaceable free liberty of the glorious gospel of life and salvation,
like the raging waves of the sea, casting up mire and dirt, as I said before;
and in their vain janglings and disputings, and false jealousies,
murmurings and complainings, revilings, railings, defamings, unstablished,
and to every good work and service of God reprobate.
And from such spirits and leaven God Almighty keep and preserve his people in his light,
truth, and spirit of grace and holy faith in Christ Jesus,
who is the holy and heavenly rock and foundation;
in him they have life and peace with God, and are in the holy liberty and freedom.
And in him, namely, in Christ Jesus, my desire is,
that all his true and faithful followers may stand fast, in their holy and pure liberty,
in him who is holy and pure, who was first, and is last,
and now is the rest of his people, the Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 12th of the 8th month, 1685.
