== How the unchangeable God is, and how all people may know him, and in what he is worshipped and served. By G. F.

The Lord '`hath measured the waters in the hollow of his hand.`' So the Lord,
the incomparable God knoweth the measures of the waters in the seas, brooks, rivers,
wells, and ponds, for he hath measured them;
so they are measured in the hollow of his infinite hand,
and the incomparable God with his infinite hand,
'`hath meeted out heaven with his span,`' (mark,
he hath meeted it out,) so he knoweth the breadth and the
compass of it with his infinite span of his great hand,
and the Lord hath comprehended '`the dust of the earth in a measure.`'
So the incomparable God knoweth the measure of the dust of the earth,
and the Lord '`hath weighed the mountains in scales,
and the hills in a balance.`' So the Lord who hath weighed them,
knoweth the weight both of the hills and mountains.
'`Behold, the nations are but as the drop of a bucket,
and are counted as the small dust of the earth.
Behold, he taketh up the isles as a very little thing.
To whom then will ye liken God,
or what likeness will ye compare him to,`' who is the infinite incomparable God,
as in Isa. 40. '`In the Lord`'s hand is the soul of every living thing,
and the breath of all mankind.`' Job 12:10.

So here you may see and feel the Lord`'s hand is
nigh unto all men and women in the whole world,
and in them, if their soul and breath be in his hand.
Here you may see the eternal, infinite hand of the incomparable God,
in whose hand is '`the soul of every living thing,
and the breath of all mankind`' in the whole world;
for '`God breathed into man the breath of life, and he became a living soul.`' God,
who is immortal, hath the breath of all (and all immortal souls) in his hand,
and none can fall out of his eternal hand.

'`The spirit of God hath made me,
and the breath of the Almighty hath given me life.`' Job 33:4. And Daniel told
Belshazer the king how that he lifted up himself against the Lord God of heaven,
'`in whose hand is thy breath.`' Dan. 5:23.

And the apostle saith, '`God that made the world and all things therein,
(he is Lord of heaven and earth,) dwelleth not in temples made with hands,
neither is he worshipped with the works of men`'s hands, as though he needed any thing;
and hath made of one blood all nations of men for to dwell upon the face of the earth,
and he giveth to all life and breath, and all things,
etc. that they should seek the Lord, if haply they might feel after him and find him,
though he be not far from every one of us,
for in him we live and move and have our being.`' Acts 17:24 to 28.

Here again you may see how God gives life and breath unto all, who hath it in his hand,
and he would have all to know him and serve him, and that he is nigh unto them all,
who hath their breath and soul in his hand;
so then he is nigh unto all that they might know that they live, move,
and have their being in the Lord, who '`poureth out of his spirit upon all flesh,
that all flesh might see his glory,
and see the salvation of God.`' Isa. 43. Luke 3:6. Acts 2:17.
For the Lord poureth out of his spirit upon all flesh,
that in his spirit and in truth all might know God, and serve him,
and worship him in his spirit and truth, for such spiritual worshippers God,
who is an infinite holy spirit, seeks to worship him.
Now it is and hath been often said by the priests that are bred up at schools and colleges,
that '`the priest`'s lips should preserve people`'s knowledge,
and they should seek the law at his mouth.`' I answer,
that these were the Jews`' priests that were made by the law of
a carnal commandment in the old testament and old covenant;
but '`Christ was made a priest after the power of
an endless life`' in the new testament and new covenant,
who came of Judah, and is called the lion of the tribe of Judah,
and not after the order of Aaron, who offered rams, and lambs, and bullocks,
and other creatures, but after the order of Melchisadeck, from Melech a king, Tsedech,
just or righteous, so a just and righteous king.
Of whom we do not read that he offered up outward creatures as Aaron`'s priests did,
though he offered up praises to God when he met Abraham.

But Christ hath changed the priesthood of Aaron, and the law by which they were made,
and disannulled the commandment which gave him tithes; as you may see in Heb. 7.

Now you that do say the Jews`' priests that are made by the law,
their '`lips are to preserve people`'s knowledge,
and they are to receive the law at their mouth,`'
this law served until Christ the seed came,
(Gal. 3:10) '`who is the end of the law for righteousness to
every one that believes.`' Rom. 10:4. And in the old testament
and covenant God gave the Jews a law in tables of stone,
but in the new testament and new covenant, God saith, '`I will put my law in their minds,
and write it in their hearts, and I will be their God, and they shall be my people,
and they shall not teach every man his neighbour, and every man his brother, saying,
know the Lord, for they all shall know me from the least to the greatest,
saith the Lord.`' Heb. 7:10-11.

So you may see here is no need of the Jews`' priests lips,
etc. to preserve people`'s knowledge, and to receive the law at their mouths,
and to give them tithes for receiving the law,
for Christ hath changed the priesthood and the law by which it was made,
and disannulled the commandment that gave them their tithes,
and saith in his new testament to his ministers, '`Freely ye have received,
freely give.`' And in the new covenant and new testament the Lord puts it in their minds,
and writes it in their hearts, that they shall not need to teach every man his neighbour,
and every man his brother, saying, know the Lord,
and Christ Jesus the treasure of wisdom and knowledge, '`for all shall know me,
from the least to the greatest,
saith the Lord.`' So this law that God writes in their hearts and
puts in their minds gives them knowledge to know the Lord;
so this law they receive from the Lord, and not from the college priests,
and the Jews`' priests in the old testament.

And the Lord poured his spirit upon the house of
Israel and the house of Judah in the old testament,
but it is said in Joel 2, '`that God would pour his spirit upon all flesh,`' etc.
And after Christ was risen, the disciples and the believers were met together,
and the Jews came gazing upon them,
and '`others mocked and said they were full of new wine;`' and Peter and
the eleven told them '`that they were not drunk as they supposed,
seeing it was but the third hour of the day;
but this is that which was spoken by Joel the prophet,
It shall come to pass in the last days, saith the Lord,
that I will pour out of my spirit upon all flesh,
and your sons and your daughters shall prophesy, and your young men shall see visions,
and your old men shall dream dreams, and on my servants and on my handmaids,
I will pour out of my spirit in those days,
and they shall prophesy.`' Acts 2:13 to the 18th.

Here you may see the spirit that God poureth upon all flesh,
gives people knowledge of prophecies, and of dreams, and of visions;
so the spirit of God,
that God poureth upon all flesh in the new testament and new covenant gives them knowledge,
that they need not the priests`' lips in the old testament to preserve their knowledge,
and people will not perish for lack of visions,
if they mind the spirit of God that he hath poured upon them,
and '`the spirit of truth will lead them into all truth.`' But if sons, and daughters,
and handmaids, and servants, and old men, do rebel against the spirit of God,
that he poureth upon them in the new testament, as the Jews did in the old testament;
for God gave them his good spirit, but they rebelled against it;
then those go from the key of knowledge, both Jews and christians, and all flesh.
And the Jews`' priests when they went from the spirit of God,
they neither preserved the people`'s knowledge nor their own, and became deaf and blind,
and turned against the prophets, Christ, and the apostles,
though they might make an outward painting of the sepulchres of the righteous,
in an outward profession of words, and turn against the righteous.

So now all flesh, Jews and Gentiles,
and all Christendom whom God hath poured out of his spirit upon,
if they rebel against God`'s good spirit, and err from it, and quench it, and vex it,
they are gone a whoreing from God and Christ, and his spirit,
and have neither true visions, nor true prophecies, nor true dreams, and are as Babylon,
all in heaps and confusion, and cannot worship the eternal God in his spirit,
and in his truth, and are out of the unity and the fellowship in the spirit,
which is the bond of peace; and so '`have not fellowship with the Father and the son,
nor fellowship one with another,`' but are broken into sects and heaps one against another,
whereas the spiritual, that walk in the spirit, are in the spirit, the bond of peace,
and are in fellowship with the Father and the son, and one with another,
and worship and serve the living God in his spirit and truth.

G+++.+++ F.

