== A true account of the sensible, thankful, and holy stale of God`'s people; and of his speaking to them, both in the Old and New Covenant. By G. F.

Here you may see that all God`'s people were a living and a sensible people,
and did always, for all things, give thanks to God the Father,
in the name of Jesus Christ.

And such as were unholy, past feeling, and insensible, having a form of godliness,
but denying the power thereof, were unthankful, and to be turned away from,
and that such went in Cain`'s, Korah`'s and Balaam`'s way,
who did feed themselves without the fear of God,
and were like the idolatrous Jews who forgot God, and eat and drank, and rose up to play;
and how God destroyed such who were unthankful and
insensible of his temporal and spiritual mercies.

The Lord said unto his people that were acquainted with him, and knew him,
'`that when they gathered together their corn and their wine,
etc. they should eat it and drink it in the court of my holiness,
and praise the Lord.`' Isa. 62:8-9.

So here you may see,
they that gathered together that which the Lord gave the increase of,
they were to eat it and drink it in the court of the Lord`'s holiness, and praise him;
and they that gather the increase of the Lord`'s fruits, and do eat them,
they should be sensible of the holiness of his courts, who filleth heaven and earth,
who is worthy of all praise and glory for all his mercies.
And they that eat and drink that which the Lord, who hath made them, hath provided,
are to be sensible in his spirit that he is worthy of all thanks and praises,
and so are not to be like the idolatrous Jews,
who forgot the Lord and his great power and mercies,
who had done such great things for them, both in Egypt,
and in delivering them out of Egypt, who after '`sat down to eat and drink,
and rose up to play.`' 1 Cor. 10:7. Num. 25:9.

And there you may see what became of all those who
did not eat and drink in the courts of God`'s holiness,
and praise the Lord; and they that did, and do forsake the right way of the Lord,
and do go into the way of Cain, Korah, and Balaam,
are they that do feed themselves without the fear of God.
Such are as the wandering stars from the firmament of God`'s power,
and are trees that do not bear fruit to God, and are as clouds,
(for people to stare at,) without water,
and raging waves of the sea foaming out their own shame,
as in Jude 12:13. And such were not,
nor are not like to praise God in the court of his holiness,
for his daily mercies they receive from him.
Such look not after their way, whether it be the way of the Lord, or the way of Cain;
and they which be in the way of Cain, Korah, and Balaam, eat the bread of idleness,
and are in the destroying spirit; but they that be in the way of the Lord,
praise him for his blessings, riches, and mercies, that he daily giveth to them.

And you may see how the christians, when they were converted unto Christ,
'`did eat their meat with gladness and singleness of heart,
praising God.`' Acts 2:46-47.

And the apostle saith to the church of Christ, '`Whatsoever ye do,
do it heartily as to the Lord.`' And again the apostle saith,
'`Whatsoever ye do in word or deed, do all in the name of the Lord Jesus;`' (mark,
in the name of the Lord Jesus! then ye must live in his grace,
which giveth a sense of the Lord Jesus;) '`giving thanks
to God the Father by him.`' Col. 3:17. 23.

So here you may see there is nothing to be done in word or deed,
but all is to be done in the name of the Lord Jesus,
and to give thanks to God the Father by him.

And again the apostle saith to the church of Christ, '`Whether ye do eat or drink,
or whatsoever ye do, do all to the glory of God.`' 1 Cor. 10:31.

Now, all that profess themselves christians and members of the church of Christ,
consider this, whether ye eat or drink, or whatsoever else ye do,
that ye do all to the glory of God.
So you are neither to eat nor drink, nor do any other thing, but to the glory of God,
so that he may have the thanks, glory, and praise through Jesus Christ,
who created all things for his glory by Jesus Christ.

For the apostle saith, '`the unthankful, unholy, without natural affections,
truce breakers, false accusers, incontinent, fierce, despisers of them that are good,
having a form of godliness,
but denying the power thereof:`' from such the apostle
commands the church of Christ to turn away.
2 Tim.
iii. So the members of Christ have no unity with such unthankful, unholy,
and truce breakers.

And the apostle saith, '`Give thanks always for all things unto God the Father,
in the name of our Lord Jesus Christ.`' Eph. 5:20.

So always, in all things, to give thanks to God the Father,
in the name of our Lord Jesus Christ, showing forth,
that you are a feeling and a sensible people of the mercies of the Lord,
through Christ Jesus, who is worthy of all thanks, glory, honour, and praise, forever.
Amen,
G+++.+++ F.
