== How the Lord spake unto Moses in the outward Tabernacle in the Old Testament, and God speaks now by his Son in the New Testament, in the Tabernacle and hearts of his people.

The Lord said unto Moses, when he and the Jews were to make the tabernacle,
'`Thou shalt put the mercy-seat above the ark,
and in the ark thou shall put the testimony that I shall give thee,
and there I will meet with thee, and I will commune with thee from the mercy- seat,
from between the two cherubims which are upon the ark of the testimony,
of all things which I shall give thee in commandment
unto the children of Israel.`' Ex. 25:21-22.

'`And when Moses was gone into the tabernacle, etc. to speak with the Lord,
then he heard the voice of God speaking unto him from the mercy-seat,
which was upon the ark of the testimony.`' And here the Lord spake to Moses in the tabernacle,
as in Num. 7:89.

'`And when the cloud did abide upon the tabernacle,
the children of Israel abode in their tents;
and when the cloud was taken off the tabernacle, then the children of Israel journeyed;
so at the commandment of the Lord they journeyed,
and kept their tents.`' Num. 9:20. '`And the glory of
the Lord filled the tabernacle.`' Ex. 40:34-35.

Here you may see the Lord spake to Moses in the tabernacle, and communed with him there,
and what the Lord did speak to him in the tabernacle,
he was to speak it to the children of Israel,
and the testimony which the Lord gave to Moses was in the tabernacle;
and was not the candlestick put in the tabernacle
which Moses was to make in the old testament?
And the Jews were not to go on their journey into the land of Canaan,
but at the commandment of God; and the Lord said to Moses,
'`I will meet with you in the tabernacle.`' Num. 17:4. '`And
the stranger that cometh nigh the tabernacle shall be put to death.`'

And the Lord bid Nathan go tell David,
'`that since the time that I brought the children out of Egypt, even unto this day,
that he had walked in a tent,
and in a tabernacle.`' 2 Sam. 7:6. And Solomon built an outward temple.
2 Chron.
iii. In which temple the Lord appeared unto the Jews,
in all those outward things which the Lord did command Moses and his servants to make;
the Lord did appear in them in the old covenant and old testament,
(which were figures and shadows of Christ the substance,
and of his spiritual house and church in the new
testament,) and were commanded in the law,
and served till Christ the great prophet came in the new covenant and new testament,
who is to be heard in all things;
and he the substance putteth an end to all those
figures and shadows in the law and old testament,
as namely, the outward tabernacle, ark, sanctuary, and temple, which were outward,
and made with hands,
where the Lord had formerly spoke to the Jews in the old testament and old covenant;
and in the new testament God speaketh to his believers by his son,
as in Heb. 1. And Christ Jesus enlighteneth every
man and woman that cometh into the world,
that is, he enlighteneth the spirit of man and woman,
which is the candle of the Lord in every man`'s and woman`'s tabernacle,
that there they might hear God speaking to them by his son, by his light, grace,
and spirit from heaven, at his mercy-seat;
and whatever any man or woman receiveth from God through Christ,
they receive it in their tabernacle,
and there is a witness and a sense of it in their tabernacle or temple,
where the glory of the Lord appeareth.
And Christ Jesus doth rule in their hearts, in their tabernacle,
and the Lord pouring out of his spirit upon all flesh, men and women,
all that have received the spirit of God, they are sensible of it,
and its motions in their tabernacle.
And they that are led by the spirit of God,
they are sensible of God`'s spirit leading to the land of the living,
and in this every one knows the voice and command of God,
from the stranger and his voice, that must not come into the tabernacle,
but that must be mortified and killed by the spirit of God.
And every one that receiveth the grace of God which bringeth salvation,
and hath appeared unto all men,
they are sensible of this grace and favour of God in their tabernacle,
and of their growing in grace, and receiving more grace from the throne of grace.
And Christ being the author and finisher of the holy, divine,
precious faith in man and woman,
every one that receiveth it are sensible of it in their tabernacle,
and of Christ the author and finisher of that faith,
and every one that believeth in the light which Christ enlightens their spirits withal,
which is the candle of the Lord in their tabernacle, and so become children of the light,
and in Christ`'s light they see more light,
and it shineth more and more until the perfect day.
And of this every child of light is sensible,
and hath a testimony or witness of this in their temple or tabernacle,
in the new testament, and do know that their bodies are the temples of the holy ghost,
and of God, and Christ.
And the gospel being preached to, or in every creature under heaven,
every man and woman that receiveth this gospel of life and salvation are sensible,
and have a testimony or witness of it in their temple or tabernacle;
and all that receive God`'s mercies and blessings from above, and tenderness,
and kindness, and gifts from God and Christ, that ascended on high,
and of the love of God shed in their hearts,
they have a sensible witness or testimony of these things in their tabernacle and temple,
and there is ascending praises to God on high from
their spirit of God in their tabernacle and temple,
from whom they do receive infinite mercies and blessings.
So if they do pray in spirit, and sing in the spirit to God, who is a spirit,
it is in the tabernacle and temple where the spirit of God and Christ is within.
And the word of faith, life, and patience is in the heart and mouth obey it, and do it;
and the anointing is within to teach God`'s people, and they need no man to teach,
but as it teacheth,
and this teacher of God`'s people is within the temple and tabernacle,
in the new testament and covenant;
so that they need not run to the old covenant and testament,
and to outward sanctuaries and temples made with hands,
and to those outward teachers that may be removed into a corner.
And the holy ghost that proceeds from the Father and son,
that leadeth the true believers into all truth,
this leader is in the tabernacle and temple.
And in the new covenant and testament, God writeth his law in the hearts of people,
and puts it in their minds, whereby all may know the Lord,
that they need not teach every man his neighbour, saying, know the Lord,
for all from the greatest to the least shall know the Lord;
and this knowledge of the Lord is known in every man`'s temple and tabernacle,
in the new covenant; for there is no man nor woman, from the highest to the lowest,
that hath any sense, or understanding,
or knowledge of the mercies and goodness of the Lord,
but it is by his light and spirit in their tabernacle or temple.
All who are sensible of the heavenly dew, and the small rain,
and the showers of the mercies of the Lord,
they are sensible of them in their tabernacle or temple, to his praise.
And all those who are ministers of Christ, and none can be ministers of Christ,
or preachers of Christ, and of his word, faith, and gospel, or word of life,
or of the grace of God, or be made ministers of the spirit,
except they have received these things from God and
Christ by his spirit in their tabernacle and temple.
I say, from God and Christ in their tabernacle and temple,
then they can declare what spiritual things they have received
from the Lord in their tabernacle and temple;
then such are ministers of the spirit, and sowers to the spirit in others,
in their tabernacle, which can apprehend the things of God, and discern them.
So as every one hath received freely the gift from
the Lord in their tabernacle and temple by his spirit,
let them minister it freely to others;
and if they have not received it from the Lord into
their tabernacle and temple by his spirit,
and have not testimony and witness of it in their tabernacles,
they are not ministers of Christ nor God, but are ministers of the letter,
which others have spoken forth from the spirit of God in their temple or tabernacle,
who were the voice and mouth of God,
as God spake by the mouth of all his holy men and women in their tabernacle;
such were and are the true ministers of God and Christ in all ages and generations.

And Christ who doth enlighten every man and woman that cometh into the world; that is,
he doth enlighten every man and woman`'s spirit,
which is the candle of the Lord in their temple or tabernacle.
And how often do the wicked, by turning from the light of Christ,
which enlightens their candles, by their hating the light of Christ,
and going away from it into evil deeds and works,
and loving the darkness more than the light, put out their candle, their spirit,
which Christ hath enlightened?
And when the candle is put out, their houses are houses of darkness, full of darkness,
spiritual Egypt, and do oppress and persecute the Jew inward;
and such whose candle is put out, they are gone from the light,
and they seek to bring all others from the light, and put out their candles,
in drawing their minds and spirits from the light of Christ that doth enlighten them,
and call the light of Christ, which enlightens their spirits,
(which are the candle of the Lord, in their temple and tabernacle,) a natural,
created and made light, or a natural conscience, which light is the life in Christ,
by which all things were made and created.
And thus they go about in their error of darkness, who have put out their own candles,
and seek to put out the candles of others,
who seek to shut up the kingdom of heaven from men,
who are shut out of the kingdom of heaven themselves, and hate the light,
the kingdom of God and Christ, and the light of the heavenly Jerusalem,
and love the darkness,
and the kingdom of darkness more than the light and kingdom of Christ;
and all those teachers, or preachers, or professors, or profane, that call the light,
(which is the life in Christ the word,
by which all things were made and created,) a natural light, and a created light,
and a made light, or a natural conscience, or a Jack in the Wisp, or a dark lantern,
they have put out their candle which Christ hath lighted in their tabernacle,
and they seek to put out the candles of others in their tabernacles,
in drawing them from the light, which is the life in Christ,
which enlightened their candle, the spirit of man in their tabernacle;
for it is the light of Christ that shineth in their heart,
which enlighteneth the spirit of man, the candle of the Lord in their tabernacle,
that giveth the light of the knowledge of the glory of God in the face of Jesus Christ.
2 Cor.
iv.

And the Lord said to Abraham, '`I will bless them that bless thee,
and curse them that curse thee; and in thee and thy seed shall all the nations,
or all the families of the earth be blessed.`' Gen. 12:3. and xviii.
18.

So here the world shall recover by the seed, which is Christ,
the blessings which they lost in fallen Adam; for Christ who bruises the serpent`'s head,
who destroyeth the devil and his works, who making peace through the blood of his cross,
by him to reconcile all things unto himself; by him, I say,
whether they be things in the earth, or things in heaven.
undefined Col. 1:20.

'`And Christ by the grace of God tasted death for every man.`' Heb. 2:9.

'`For as all men died in Adam, even so in Christ shall all be made alive;
and so by man came death, (namely,
Adam,) and by man came also the resurrection of the dead,`' (namely,
Christ.) 1 Cor. 15:21-22.

So here you may see all died in Adam, then they are dead from eternal life;
but Christ by the grace and favour of God to mankind,
(that are dead in Adam,) tasted death for every man; so he hath ransomed them,
and purchased them by his death, out of the death of Adam in the fall,
into the life that man and woman were in before they fell,
and into himself that never fell.
And Christ doth enlighten every man that cometh into the world,
with his divine heavenly light, which is the life in Christ the word,
by whom all things were made, that with his light in their hearts,
all men and women may know Christ Jesus that hath redeemed them, and died for them,
and their sins and trespasses, and is risen for their justification.

And God having poured out of his spirit of grace upon all flesh,
that by his spirit they might know and see the things of God, and his glory,
and with the spirit of grace they might see God`'s
love and favour to them in Christ Jesus,
and how that they are dead in fallen Adam,
and how that they are made alive again by Christ Jesus the second Adam,
the Lord from heaven, and how that Christ is their resurrection from the dead,
into the life everlasting in him,
and how Christ doth awaken them out of the sleep of sin and death in Adam,
and bringeth them into his everlasting righteousness,
that they may praise God through Jesus Christ.

And in the old covenant and old testament,
for the sins and transgressions of man and woman,
the clean beasts and other creatures were put to death, and their blood was shed,
and they were offered as a sacrifice for the sins and transgressions of the people;
and their blood was sprinkled upon the people and the tabernacle;
and almost all things were by the law purged with blood,
and without shedding of blood is no remission of sin.
So here the blood of the clean creatures was shed,
and they offered up as a sacrifice for man and woman`'s sins and transgressions;
the lambs, goats, rams, heifers, pigeons, doves, etc. these were put to death,
and their blood shed and offered up for man and woman;
which were types of Christ Jesus the lamb of God, in the new covenant and new testament,
who through the eternal spirit offered up himself without spot to God,
and purgeth our consciences from dead works, to serve the living God; who said, I come,
in the volume of the book that is written of me to do the will of God; namely,
the volume of the book of prophecies, promises, types, figures, and shadows,
and that he might take away the first covenant and testament,
and establish the second covenant and testament;
by the which will of God we are sanctified through the offering
of the body of Jesus Christ once for all:
for by one offering he hath perfected forever them that are sanctified.
Heb. 9. x. chap.

Here all may see Christ the lamb of God, (who is the offering,
and offered up his body by the eternal spirit of God once for all,)
endeth all the offerings and sacrifices amongst the Jews.
He the holy lamb tasted death for every man that is dead in Adam,
in their sins and transgressions; so he that tasted death for every man,
hath shed his blood for all men, and so his blood is sprinkled upon all men,
that they might drink it, and have life through the sanctification of the spirit,
and obedience, and sprinkling of the blood of Jesus. Heb. 12:24.
1 Pet. 1:2.

So now all in the new testament and new covenant are to look to
be cleansed and purged by the blood of the everlasting covenant,
Christ Jesus, which sprinkleth their consciences and tabernacle, and in it to have life,
and to know Christ that was crucified, and died for their sins,
and so by the grace and favour of God hath tasted death for every man:
so he is the offering for the sins of the whole world,
which offering or sacrifice God doth well accept;
who is the lamb of God that taketh away the sins of the world, so maketh an end of sin,
and finisheth transgressions, and destroyeth the devil and his works,
and bringeth in everlasting righteousness,
that all might walk in his light and spirit of grace, in the truth,
and in his everlasting righteousness,
to the praise and glory of God through Christ Jesus, who is a propitiation for our sins,
and not for our sins only, but for the sins of the whole world,
and is the '`one mediator betwixt God and man, the man Christ Jesus,
who gave himself a ransom for all,
to be testified of in due time.`' 1 Tim. 2:5-6. 1 Pet. 1:18. So we are redeemed,
not with corruptible things, as silver and gold,
from the outward figures and traditions of the Jews, and from our vain conversation,
but with the precious blood of Christ, as a lamb slain without blemish, and without spot;
who was ordained before the foundation of the world,
but was manifest in these last times for you,
who by him do believe in God that raised him up from the dead, and gave him glory,
that your faith and hope might be in God through Christ, as in 1 Pet. 1:21.

Christ being offered and sacrificed for sins and transgressions of men and women,
he endeth all the offerings and sacrifices of the
beasts and other creatures in the old testament.

And Christ being slain and put to death,
and his blood shed for the sins and transgressions of men and women,
he also made an end of putting to death, and killing, and slaying,
and shedding the blood of rams, lambs, heifers, goats, and other creatures,
for the sins and transgressions of men and women in the old testament and covenant.
So the offering, sacrificing, putting to death,
and shedding the blood of Christ (I say,) putteth
an end to that priesthood that slew and put to death,
and shed the blood, and offered, and sacrificed the outward dumb clean creatures,
for the sins and transgressions of men and women in the old testament.
For the old testament and covenant was established
by the blood of the outward clean creatures,
but the new covenant and new testament is established by the blood of Christ,
the blood of the everlasting covenant, by whose blood we are washed, and cleansed,
and sanctified, and made clean, and presented to God.

So the clean beasts were killed and slain, and put to death in the old covenant,
for the sins of men and women.

But Christ in his new covenant, is the lamb without blemish, and was killed, slain,
and put to death for the sins of the whole world, in the new covenant.

G+++.+++ F.

