[#ch34.style-blurb, short="To Magistrates in Christendom that Do Profess Christianity"]
== To all Magistrates in Christendom that do profess Christianity. Concerning Christian gospel-liberty, against persecution, and one Christian, forcing, persecuting, imprisoning, and spoiling the goods of another, because they will not be of their faith, worship, or religion. By G. F.

Christ saith, '`Let the tares and the wheat grow together till the harvest,
which is the end of the world;`' and then Christ`'s
angels shall separate the tares from the wheat.
And are not angels spirits, and not men?
For Christ commands christian men to '`love one another,
and love their enemies;`' so not to persecute them.
And those enemies may he changed by repentance and conversion, from tares to wheat.
But if men imprison them, and spoil and destroy them,
they do not give them time to repent.
So it is clear it is the angels`' work to burn the tares,
and not men`'s. Christian men must '`love one another,`' and their enemies.
And Christ rebuked his disciples, that would have had fire to have come down from heaven,
to have destroyed them that would not receive him; and told them,
'`He came not to destroy men`'s lives, but to save them.`' And Christ is the true light,
that doth '`enlighten every one that comes into the world;`' and saith,
'`Believe in the light,
that ye may become children of the light.`' And God pours out his spirit upon all flesh;
namely, his sons and daughters, servants, and hand maids, young men and old men.
And so the manifestation of the spirit of God is given to every one to profit withal;
so that in the spirit they may serve and worship the living God that made them.
And none are to grieve, nor vex, nor quench the motions of the spirit of God;
but to walk in it, and to be led by it, that they may be the sons and daughters of God.
And the '`grace and truth is come by Jesus;`' and this grace of God,
which brings salvation, hath appeared to all men;
which will teach them to deny ungodliness,
and to '`live righteously and soberly.`' So all men that do know their salvation,
and come into favour with God, it is by his grace.
And this grace and truth is in men and women`'s hearts, to establish them upon Christ,
who is full of grace and truth.
And God would have all men to come to the knowledge of the truth, and be saved.
And so he would not have men to be destroyed, nor gave any such command,
that men should destroy one another about religion.
And Christ sent his apostles and disciples to preach
the gospel of life and salvation to all nations,
and every creature under heaven.
He did not say they should imprison, and spoil the goods,
and destroy such as would not receive their gospel, nor believe it;
but they should '`shake off the dust of their feet;`'
which should be a sufficient witness against them.

'`And Christ, by the grace of God, tasted death for all men;
and Christ gave himself a ransom for all men, to be testified of in due time.
So, hath not Christ in this purchased all, and bought all mankind with a price, namely,
with his blood, in tasting death for them all,
and giving himself a ransom for all?`' And therefore,
are not all men to '`love one another, and forgive one another,`' in this his gospel-day?
For Christ saith, '`Judge not, that ye be not judged; and, with what measure ye meet,
it shall be measured to you again.`' Matt. 7. i, 2.

And the Christians were not to judge nor despise one another about eating of meats,
nor observing of days;
but '`let every man be fully persuaded in his own mind.`' Rom. 14. to the end. Col. 2:16.
And the apostle Paul saith to the church of Christ,
'`Not that we have dominion over your faith; but we are helpers of your joy.
For by faith ye stand.`' 2 Cor. 1:24.

So faith being the gift of God, which Christ is the author and finisher of,
the apostles did not claim a dominion over the faith,
which is the gift of God in people`'s consciences.
And the apostle saith,
'`God hath dealt to every man a proportion of faith,`'
as in Rom. 12:3. And this faith,
the apostle saith, '`works by love.`' Gal. 5:6. 22. And again, the apostle saith,
'`Whatsoever is not of faith, is sin.`' Rom. 24:13.
And the righteousness of faith saith,
'`The word is in the heart, and in the mouth, to obey it, and to do it.`'

And the apostle said, '`they were not to speak evil one of another,
or condemn one another; for he that did, spoke evil of the law, and condemned the law,
and did not do it.`' James 4:11. For the law of God commands people to love one another,
and not to persecute one another; yea, to love enemies.
And the apostle saith,
'`Love doth no ill to his neighbour.`' And the apostle Peter saith, '`Honour all men,
etc. and love the brotherhood.`' So if they have honoured all men,
then they have them all in esteem, as they are the creatures of God,
whom Christ hath died for, and gave himself a ransom.
And the apostle saith to the church of Christ, '`Though we walk in the flesh,
yet we do not war after the flesh;
for the weapons of our warfare are not carnal,`' etc. 2 Cor. 10:3-4.
For '`we wrestle not with flesh and blood,`' saith the apostle. Eph. 6:12.
And in this chapter you may see the saints`' spiritual armour,
and spiritual weapons.
And so it is clear, the christians, in the apostles`' days, did not use carnal weapons,
and wrestle with flesh and blood; and their warfare was not carnal,
in matters of faith and religion, in the church of Christ,
and serving and worshipping of God.

And the apostle Peter saith,
'`the elders were not to be lord`'s over God`'s heritage;`'
but that they might be examples in good life and conversation,
and good doctrine; '`not by constraint for filthy lucre; but willingly,
and of a ready mind.`' 1 Pet. 5:1-2.

And the apostle Peter saith, '`Of a truth I perceive,
that God is no respecter of persons; but in every nation, he that feareth God,
and worketh righteousness, is accepted with him.`' And this the apostle Peter said,
when he went among the Gentiles, he by nature being a Jew.
So if God doth accept, in every nation, all them that fear him and work righteousness,
therefore, ought not all that have the mind of Christ, and profess true christianity,
to be tender to such as fear God, and work righteousness?
And are not all christians, that love Christ, to keep the command of Christ,
'`to love one another, and to love enemies?`' Then they cannot persecute,
and spoil the goods, and imprison any, concerning church, faith, religion,
and the worship of God.

And God reproves and judges such as build up Zion with blood; for the Lord saith,
'`that Zion, that is built up with blood, shall be ploughed up as a field,
that is turned upside down.`' Micah 3:10. 12. Therefore you may see,
such as build with blood and persecution, their work doth not prosper.
For the body, or church of Christ, is edified, knit, and united,
and built up together with the love of God. Ephesians 4:16.
Colossians 2:19.

[.blurb]
=== Postscript

Do not all christians that profess christianity, say these words in the Lord`'s prayer,
'`forgive us our trespasses, as we forgive our trespassers?`' And doth not Christ say,
'`If ye forgive men their trespasses,
your heavenly Father will also forgive you your trespasses;
but if ye forgive not men their trespasses,
neither will your heavenly Father forgive your trespasses.`' Matt. 6:12. 14, 15.
So here you may see, all christians in Christendom pray to God conditionally,
to be forgiven of God their trespasses against him,
as they do forgive men their trespasses against them.
And therefore, it behooves all christian people to be serious, and consider what they do,
when they pray to God, that they do forgive others,
as they would have God to forgive them.
And if they do forgive, they will not hate nor persecute, but love.

G+++.+++ F.
