[.style-blurb, short="God`'s People Not to Take Names of Heathen Gods in their Mouths"]
== How God`'s people are not to take the names of the heathen gods in their mouths, nor follow their customs, nor learn their ways. By G. F.

Thus saith the Lord to the house of Israel, '`Learn not the way of the heathen,
and be not dismayed at the signs of heaven; for the heathen are dismayed at them,
for the customs of the people are vain, etc. for they are altogether brutish and foolish.
Their stock is a doctrine of vanities.
Thus shall ye say unto them, the gods that have not made the heavens and the earth,
even they shall perish from the earth, and from under these heavens.`' Jer. 10:2.

'`Pour out thy fury upon the heathen, that know thee not,
and upon the families that call not upon thy name; for they have eaten up Jacob,
and devoured him, and consumed him, and have made his habitation desolate.
But the Lord is the true God, he is the living God, and an everlasting king;
at his wrath the earth shall tremble,
and the nations shall not be able to abide his indignation.`' Jer. 10:10. 25.

Here you may see they that did follow the vain customs of the heathen,
and learn their ways, and follow the doctrine of their vanities, are foolish and brutish,
and such worship the gods that are made with hands,
which made not the heavens and the earth,
and all such gods the Lord saith shall perish from the earth,
and from under these heavens.
As you may see these that learned the way of the heathen,
and followed their vain customs and doctrines of vanities, and were foolish and brutish,
and were dismayed at the signs of heaven; and these are such that eat up Jacob,
the second birth, and seek to devour him, and consume him,
and to make his habitation desolate.
So the Jews, the children of Israel, were not to learn the ways of the heathen,
nor their vain customs, nor to follow their doctrine of vanities,
for they were foolish and brutish that did so.
And the portion of Jacob, the second birth, is not like them, for the Lord is his portion.
The Lord said to the children of Israel in the old testament, and old covenant,
'`In all things that I have said unto you be circumspect,
and make no mention of the names of other gods,
neither let it be heard out of thy mouth.`' Ex. 23:13.

Now here you may see God`'s people were to make no mention of the names of other gods,
namely, the gods of the heathen that were made with hands,
neither were they to be heard out of their mouths; for he saith,
'`The gods that made not the heavens and the earth,
even they shall perish from off the earth,
and from under these heavens.`' Jer. 10:11. And
God`'s people were not to learn the way of the heathen,
nor follow the vain customs of the people; for they are altogether brutish and foolish,
and their stock is a doctrine of vanities.
And therefore God`'s people in the old testament, were wholly forbidden such things;
but they were to serve and to fear the Lord God.

The old pagan Saxons, in their idolatry,
brought in the names of the days after their gods;
and these called christians have retained them to this day;
and yet they say the scripture is their rule, for their faith and practice,
and yet their practice is quite contrary to the scripture, and the command of God.
The first day of the week, the idolatrous Saxons worshipped the idol of the sun,
from whence came Sun`'s- day or Sunday.
The second day of the week they worshipped the moon,
from whence came Monday or Moon`'s-day.
The third day they worshipped the idol of the planet, which they called Tuisco,
from whence came Tuesday.
And from their idol Woden, came Woden`'s-day, called Wednesday.
And from their idol Thor, came Thursday.
And from their idol Friga, came Friday.
And from their idol Satur, came Saturday.
And the heathen called Mars the god of battle,
and from thence they called the first month March.
And Venus they called the goddess of love and beauty,
and from thence they called the second month April.
And Maja a heathen goddess, called Flora and Chloris,
were called the goddesses of flowers; unto Maja the heathen idolaters used a sacrifice,
from thence was the third month called May;
and upon the first day of May they used to keep Flora`'s
feast to the two goddesses of flowers,
to wit, Flora and Chloris.
Flora was a strumpet in Rome,
that used on the first day of May to set up a may-pole at the door to entice her lovers;
from whence came may-poles to be first observed.
And from the heathen goddess Juno, is the fourth month called June.
And in honour to Julius Caesar, a Roman emperor, they called the fifth month July.
And the sixth took its name August, in honour to Augustus Cesar.
And September, October, November, and December, are called from the Latines.
And one Janus, a king of Italy, was for his wisdom pictured with two faces,
and whom they honoured as a god, and from this name Janus was the eleventh month,
called January.
And Saturnus, Pluto, Februs, were called the gods of hell,
whom the heathens said had the rule of the evil spirits there; and from Pluto,
Februs was the twelfth month called February.

Now here you may see how the christians call the days, and many of the months,
after the heathen gods and goddesses, and not after the scriptures,
which in the beginning called them the first, second, third, fourth,
etc. and called the months, first, second, third, etc. to the twelfth.

And the Lord commanded the Jews, his people, as is said before,
'`In all things I have said unto you be ye circumspect,
and make no mention of the names of the other gods;
neither let it be heard out of thy mouth.`'

Now all you that profess christianity, how do you obey the Lord, and are circumspect,
who make mention of the names of other gods and goddesses,
and are so often heard out of the mouths of you and your children;
and to keep them up in the memory, both in your mouths, and children`'s mouths,
ye put them in your Almanacs, lest ye should forget them;
and yet you say the scripture is your rule, and yet disobey both the command of God,
and the holy scriptures of truth, and are often angry with, and deride the people of God,
whom you in scorn call Quakers,
because they do not call the months and days after the heathens`' gods and goddesses,
but do call them according as the holy men of God
in the scripture of truth have first called them,
and cannot call them after the idolatrous heathens`' gods and goddesses,
nor mention their gods`' and goddesses`' names, as you do,
without the breach of the command of God,
as in Ex. 23:13. and the scriptures of truth.

The Lord saith, '`I will cut off the names of the idols out of the land,
and they shall no more be remembered.`' Zach.
xiii.
2+++.+++ And the Lord saith, I will take away the names of Baalim, out of her mouth,
and they shall no more be remembered by their name.`' Hos. 2:17.

[.signed-section-signature]
G+++.+++ F.
