== A testimony for God`'s truth: First, concerning new and heavenly Jerusalem, and Jerusalem from below.

Secondly, concerning Christ, the great mountain that fills the whole earth.

Thirdly, how man and woman was created in the image of God, and to be meet-helps one to another.

Fourthly, how every one ought to improve the talent God gives them, to his glory, and their eternal happiness. By G. F.

The apostle writes to the church of Christ, and saith,
'`Jerusalem which is above is free,
which is the mother of us all.`' All Jerusalem`'s children are born of the spirit,
and led by the spirit of God.
'`And as many as receive Christ, he gives them power to become the sons of God;
even to them that believe in his name.`' And whosoever believes that Jesus is the Christ,
is born of God;`' and they that believe in the light, the life in Christ,
do become the children of light, as in John 1:12. and xii.
36. and 1 John 5:1.

And now in this heavenly light, power, and spirit,
they come to be heavenly Jerusalem`'s children, that is from above.
For such as hate the light, and do evil, are condemned by it,
and they that have not the spirit of Christ are none of his; but all the true christians,
in the new covenant, and new testament, in Christ Jesus,
to whom Christ hath given his life, which is his light and his power,
them that believe in it, and receive him, do become the children of light,
and the sons of God; so they are heavenly Jerusalem`'s children, born from above,
of the spirit and the light.

The apostle saith to the converted Hebrews, '`Ye are come unto Mount Zion,
unto the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels,
and to the general assembly and church of the first born, which is written in heaven,
and to God the judge of all, and to the spirits of just men made perfect, and to Jesus,
the mediator of the new covenant;`' and hither Jerusalem`'s children were come then,
while they were upon the earth.

The children of God, that were born of the spirit, and the children of the light,
they were come hither in the apostles`' days, they were come to that heavenly Mount Zion,
that looks over the whole world.
For natural Zion, the watchtower, looked over into Canaan; but this heavenly Zion,
spoke of in the new testament, which is the joy of the whole earth,
looks over all the earth, and in this joyful Zion,
Christ the elect and precious was laid. 1 Pet. 2:6.
And Christ the deliverer comes out of this Zion. Rom. 11:26.
And the children of heavenly Jerusalem,
which is the city of the living God, they see the innumerable company of angels.
And is not this the city that Abraham, Isaac, and Jacob sought for,
which hath foundations, whose builder and maker is God; is not this heavenly Jerusalem,
the city of the living God, that they sought for?
And are not all heavenly Jerusalem`'s children written in heaven?
seeing the apostle said, '`Jerusalem that is above,
is the mother of us all`' that believe in Christ, and receive him,
and are born of the spirit, and they were come '`to the General Assembly,
the church of the first born, written in heaven, and to God the judge of all,
and to the spirits of just men made perfect.`' All these were and
are born of the spirit that come to heavenly Zion and Jerusalem,
and to God and his son, and to the just men`'s spirits made perfect;
for it is the spiritual birth, heavenly Jerusalem`'s children,
that sees these things and knows them; that which is born of the flesh is flesh,
and may know fleshly things, and that which is born of the spirit is spirit,
and knows spiritual things.

And John in the Revelations, he saw the great holy city, new Jerusalem,
coming down from God, out of heaven, prepared as a bride adorned for her husband,
having the glory of God; and her light was like unto a precious stone,
and the city had no need of the sun, neither of the moon, nor of a candle,
for the glory of God doth enlighten it, and the lamb is the light thereof.
This heavenly Jerusalem is and was the mother of all them that receive Christ,
who gives them power to become the sons of God,
and they that believe in the light are the children of the light,
and walk in the light of their mother, new Jerusalem.

And you may read how this new Jerusalem is garnished with pearls, figuratively,
and there is written on the wall the names of the twelve tribes, and twelve apostles,
and of the lamb; the gates of it shall not be shut at all by day,
for there shall be no night there.

So here you may see there is no night here, but always day, in the holy city,
new and heavenly Jerusalem, that is from above.
All the children of the light, and that are born of the spirit from above,
see it their mother;
and the nations of them that are saved shall walk in the light of this city,
new Jerusalem, that is from above.
And all Jerusalem`'s children, that have overcome, have right to the tree of life,
and drink of the water of life in this new and heavenly Jerusalem.
And in this heavenly Jerusalem there shall be no more curse,
and none that are defiled enter into it,
but they that are written in the lamb`'s book of life.
And he that overcomes saith Christ, '`I will make a pillar in the house of my God,
and he shall go no more out, and I will write upon him the name of my God,
and the name of the city of my God, new Jerusalem,
which comes down out of heaven from my God; and I will write upon him my new name.`'

Here you may see New Jerusalem`'s children, and the name of God, and the holy city,
and the name of Christ written upon them,
and their father`'s name written in their foreheads,
that they may know that they are the children of New Jerusalem, and of God and Christ;
and they shall see his face, and his name shall be in their foreheads. Rev. 22:4.
and iii.
12. '`He that hath an ear,
let him hear what the spirit saith to the churches,`'
heavenly Jerusalem`'s and Zion`'s children.
And therefore all that are born of the spirit, the children of the light,
that believe in Christ, and receive him, their mother is new and heavenly Jerusalem;
and this spiritual birth cannot own any mother below this new and heavenly Jerusalem.
And all heavenly Jerusalem`'s new born babes are
nourished with the sincere milk of the word,
and the bond- woman`'s children, that are born after the flesh,
persecute new and heavenly Jerusalem`'s children, that are born after the spirit;
the bondwoman`'s children are in bondage, but Jerusalem`'s children, which is from above,
are free, who give glory to the Lord God over all forevermore.

So new and heavenly Jerusalem brings forth a new and heavenly generation,
a spiritual household, heavenly and spiritual citizens, and a royal priesthood,
that offer up living and spiritual sacrifices.

And in the apostles`' days, before the apostacy,
all the true believers and followers of Christ,
had Jerusalem that was above for their mother, but since the apostles`' days,
in the apostacy the outward christians have gone into many sects,
and they have got many mothers, and by law they force others to them;
but they that are brought out of the night of apostacy, by the light, power,
and spirit of Christ Jesus, they are come to new and heavenly Jerusalem,
and can own none of their mothers, that they have set up since the apostles`' days,
that are below heavenly Jerusalem, that is from above,
in whom there is neither sect nor schism, rent nor division, contest nor strife,
for no unclean thing comes into it.

And the Lord said, '`Behold, I create new heavens, and a new earth,
and the former shall not be remembered,
nor come into mind.`' Isaiah saw this by prophecy. Isa. 56:17.
And John said, '`I saw a new heaven and a new earth,
and the first earth was passed away,
and there was no more sea.`' Rev. 24:1. And the Lord said,
'`Behold I create Jerusalem a rejoicing and her people a joy,
and I will rejoice in Jerusalem, and joy in my people,
and the voice of weeping and crying shall be heard no more in her.`'
Is not this heavenly Jerusalem that Isaiah prophesied of? Isa. 65:18-19.
And is not this the heavenly Jerusalem that John saw in Revelations?
xxi. 2, 3, 4. This new and heavenly Jerusalem that is above,
it shines over all the nations,
for the nations of them that are saved walk in the light of it, where it is always day,
and there is no night there, for the Lord God and the lamb is the light of it,
in which light the nations of them that are saved walk.

Natural men may know natural sciences, and the natural tongues and languages,
and the natural arts, and natural philosophy;
for the natural Jews and Pilate could set their natural tongues, which began at Babel,
over Christ, and yet crucify him.
And the whore of Babylon and confusion, the mother of harlots,
she hath power over the natural tongues, that is whored from the spirit of God,
and so these natural men, with these natural things, that know nothing,
but follow their own spirits, and see not the things of God,
they are foolishness to them; but God is pouring his spirit upon all natural men,
upon all flesh, that with his spirit they may know the things of God,
and serve and worship him in spirit and truth, and know heavenly Jerusalem their mother,
with the spirit that God pours upon them.

And John saw the mother of harlots drunk with the
blood of the saints and martyrs of Jesus,
and their blood was found in the mother of harlots, the mystery Babylon,
the false church.
And were not these saints, martyrs of Jesus, and prophets,
of heavenly Jerusalem`'s children, whose blood was and is found in the mother of harlots,
the false church, the mystery Babylon? Rev. 17:18.

He that was born after the flesh, persecuted him that was born after the spirit,
even so it is now; and the children of new Jerusalem, that is above, and is your mother,
they and their mother never persecuted any.
But the mother of mystery Babylon, and of harlots,
she and her harlots were and are the persecutors,
in whom is found the blood of the righteous,
viz. '`the free born children of Jerusalem from above.`'

G+++.+++ F.

[.asterism]
'''

=== How all nations may see with the light, the life in Christ, him the great mountain that fills the whole earth.

Concerning the stone cut out of the mountain without hands,
spoken of in Daniel 2. which did dash to pieces the image whose head was fine gold,
which was Nebuchadnezzar`'s and the Babylonian`'s monarchy,
and should dash to pieces the breast and arms of silver,
which was the Medes`' and Persians`' monarchy,
and likewise it should dash to pieces the belly and thighs of brass,
which was the Grecians`' monarchy, and the legs of iron,
and his feet part of iron and part of clay, which was the Roman`'s monarchy.

So all these four monarchies were but one image, the head was gold,
and the breast and arms silver, and the belly and thighs brass, and his legs iron,
and his feet part of iron and part of clay; and this same stone, cut out of the mountain,
brake the image of iron, clay, silver, brass, and gold to pieces,
and they became like unto the chaff of the summer threshing floor,
and the wind carried them away, that no place was found for them.
So here was the end of these four monarchies,
and the stone that smote the image became a great mountain, and filled the whole earth.
'`And in the days of these kings,
(or four monarchies,) shall the God of heaven set up a kingdom,
which shall never be destroyed; and the kingdom shall not be left to others,
but it shall consume and destroy all these kingdoms, and it shall stand forever,
and of his kingdom there shall be no end.`' Dan. 2. and Luke 1:33.

Now is not this stone Christ, that becomes a great mountain, and fills the whole earth?
And did not he come in the day of these four monarchies, who dashed them to pieces,
and set up his kingdom?
And did not Christ say, when he was come,
'`My kingdom is not of this world?`' and also did not he say,
'`All power in heaven and earth is given unto me?`'

Now Christ`'s kingdom is an everlasting kingdom that shall never be destroyed,
but shall stand forever, and his kingdom stands in righteousness, and power, and peace,
and joy in the holy ghost; and Christ said to Nicodemus,
'`Except a man be born again he cannot see the kingdom of God;`' and again,
he saith to him, '`Except a man be born again of water, and of the spirit,
he cannot enter into the kingdom of God.`' John 3. And also the apostle saith,
'`that none that is defiled or unclean shall enter into the kingdom of God and Christ;
and the natural man knows not the things of God, they are foolishness to him.`'

So this everlasting kingdom of God, which was set up above sixteen hundred years ago,
shall never have end, for no unclean or defiled person can enter into it,
nor none can see it, nor enter into it,
except they be born again of water and of the spirit;
this everlasting kingdom stands and remains over all,
and the unclean and defiled cannot enter into it,
and they that are not born again cannot enter into it, nor see it,
so they are not like to destroy this everlasting kingdom, it remains firm,
and will never have an end; though the unclean and defiled,
and them that are not born again do not see it;
yet John saith in Rev. 1:9. he was '`in the kingdom and patience of Jesus Christ.`'

And the apostles told the saints, '`That they were delivered from the power of darkness,
and translated into the kingdom of his dear son.`'
And was not this while they were upon the earth? Col. 1:13.
So these were born again; and Christ saith,
'`The law and the prophets were until John,`' and
he was the greatest prophet born of a woman,
'`but the least in the kingdom is greater than John;`' and since John Baptist preached,
men pressed into the kingdom, and those are they that are born again,
and have the spiritual eye that see the end of the prophets and John,
that see Christ`'s everlasting spiritual kingdom, and press into it.

Now Christ is the stone that became the great mountain, and fills the whole earth, (mark,
the whole earth,) '`and none shall hurt nor destroy in my holy mountain,
saith the Lord.`' Isa. 65:25. And this is the mountain of the house of the Lord,
that is established on the top of all mountains, and exalted above the hills. Isa. 2:2.
Mic. 4:1.

And now Christ this mountain, filling the whole earth, you may say, what,
does it till Asia, Africa, Europe, and America, and the east, west, north, and south?
I say yes, Christ this mountain fills the whole earth,
and he doth enlighten every one that comes into the whole world; '`for in him was life,
and this life was the light of men.`' This was the true
light which enlightens every one that comes into the world,
and that every one with this true light, the life in Christ, both in Asia, Europe,
Africa, and America, both east, west, north, and south, that is come into the world;
I say with this divine light, the life in Christ, they may see Christ, the mountain,
in their own country, which fills the whole earth, for the light shines in their hearts,
to give the knowledge of the glory of God in the face of Christ Jesus. John 1:4.
9. 2 Cor. 4:4. And Christ saith, '`Believe in the light,
that ye may become children of the light.`' John 12:36. So the light,
which is the life in Christ, gives the knowledge of him in all places,
who is the mountain that fills the whole earth, for the light is the life in Christ,
that great glorious mountain, and they that believe in the light, the life in Christ,
and are become children of the light, they see this everlasting glorious kingdom,
and enter into it, and so are the children of the kingdom of God and Christ.

The Lord saith, speaking of Christ, '`I have set my king upon my holy hill of Zion,
or upon Zion, the hill of my holiness.
Ask of me, and I will give thee the heathen for thy inheritance,
and the utmost parts of the earth for thy possession:
thou shalt break them with a rod of iron,
and dash them to pieces like a potter`'s vessel.
Be wise therefore now,
O ye kings! be ye instructed ye judges of the earth! serve the Lord with fear,
and rejoice with trembling; kiss the son least he be angry, and ye perish from the way,
when his wrath is kindled but a little.
Blessed are all they that put their trust in him.`'

How can the kings be wise, and the judges instructed, and kiss the son,
and keep in his way, and trust in him, but by believing in his divine light,
which is the life in Christ?
Now Christ with his divine light, doth inherit the heathen,
and possess the utmost parts of the earth who receive him;
but the wrath of the lamb is turned against them that do evil, and hate the light,
which is his life, then he dashes them to pieces, like a potter`'s vessel,
and they perish from him the way; and therefore all must believe in the light,
which is the life in Christ, the great mountain that filleth the whole earth; and here,
in this mountain the Lord will teach them his ways;
and so the knowledge of the Lord shall cover the earth as the waters covers the sea.
God`'s and Christ`'s everlasting kingdom is over all, and from generation to generation,
and the sceptre of his kingdom, is a righteous sceptre,
and he rules in the kingdoms of men; for by him kings rule, and princes decree justice;
and his seed I will make endure forever, and his throne as the days of heaven.

G+++.+++ F.

[.asterism]
'''

=== Here you may see how male and female were meet-helps in the government, when God made them in his image of righteousness and holiness, and how Christ restores man up into his image again, and how that male and female are all one in him, and of the increase of Christ`'s government and peace there is no end.

God said, '`Let us make man in our image, after our likeness,
and let them have dominion over the fish of the sea, and over the fowls of the air,
and over all the cattle, and over every living thing that moveth upon the earth:
so God created man in his own image, in the likeness of God created he him,
male and female created he them, and blessed them; and God said unto them, be fruitful,
and multiply and replenish the earth, and subdue it,
and have dominion over it,`' etc. as before, as in Gen. 1. ii.
chap.

Here the female which was the meet-help for Adam,
and they both male and female were meet-helps, joined in government, dominion, and rule,
being in the likeness and image of God, and they were blessed in it;
for God said unto them, (mark, them,) '`Be fruitful, and multiply,
and replenish the earth, subdue it, and have dominion over it,`' etc.
And this was before man and woman fell from his image.
So God who made man and woman in his own image,
gave them an understanding to understand what he said to them.

And the apostle saith to the Colossians,
'`Seeing ye have put off the old man with his deeds,
and have put on the new man which is renewed in knowledge,
after the image of God that created him, where there is neither Greek nor Jew,
circumcision, nor uncircumcision, Barbarian, Scythian, bond nor free, but Christ is all,
and in all.`' Col. 3:10-9.

Now this old man, in Adam, in the fall, being put off, and this man in the image of God,
that he made and created them in, put on in righteousness and holiness,
in such Christ is all and in all, a ruler and a governor,
so that he rules in the male and in the female; in the new man, in the image of God,
they know him to be a ruler and governor.
Isaiah saith, '`Unto us a child is born, a son is given,
the government shall be upon his shoulders,
and his name shall be called the wonderful counsellor, the mighty God,
the everlasting Father, the Prince of Peace;
of the increase of his government and peace there shall be no end,`' etc. Isaiah 9:6-7.

And the Lord saith, '`Behold, a virgin shall conceive and bear a son,
and shall call his name Emanuel, God with us.`' Isaiah 7:14.

And man was drove from God, for his sin and transgression,
but Christ his son makes an end of sin, and finishes transgression;
and Christ renews man and woman again up into the image of God,
that God had created them in, and so the emanuel, God with us.
And so Christ is a ruler and a governor in them that have put on the new man,
that he hath renewed in the image of God,
'`For in Christ Jesus neither circumcision availeth any thing, nor uncircumcision,
but a new creature.`' Gal. 6:16. For the apostle saith,
'`As many of you as have been baptized into Christ, have put on Christ;
there is neither Jew nor Greek, there is neither bond nor free,
there is neither male nor female,
for they are all one in Christ Jesus.`' Gal. 3:27-28.

So here all are one in Christ, that are baptized into the death of Christ,
and have put him on; and such know his rule and government,
the increase of which there is no end, etc.

The apostle saith to the Ephesians, '`For we are God`'s workmanship,
created in Christ Jesus unto good works, which God hath prepared, or ordained,
that we should walk in them, that Christ may dwell in your hearts by faith,`' etc. Eph. 2:10.
iii.
17.

So the new creation in Christ Jesus is God`'s workmanship in his image,
in righteousness and holiness, as man was made in the beginning;
and such know Christ to be ruler and governor in male and female,
for Christ who is the brightness of God`'s glory,
and in the express image of his substance, who destroys the devil and his work,
renews man and woman up into the image of God again, as God made them in the beginning;
and such know him to be a ruler, and a governor, and a counsellor, and a father.
And the work of the apostles, who warned every man, and taught every man in all wisdom,
that they might present every man perfect in Christ Jesus,
for in Adam in the fall they were imperfect, and so to be members of his body,
and the mystery which hath been hid from ages and generations,
which is now made manifest to the saints, which is Christ in you the hope of glory. Col. 1:27-28.

And Christ being in his people the hope of glory, which hope purifies them,
even as lie is pure; and is not Christ`'s government upon his shoulders in his people,
and a wonderful counsellor, and a prince of peace in them?
as in Isaiah 9:6.

And doth not the apostle say, God hath set some in the church,
which is the body of Christ, to be helps in government, (to wit,) in the image of God,
in righteousness and holiness, where Christ is governor and counsellor;
and such have put on love and charity, which is the bond of perfectness,
and the peace of God rules in their hearts, by which they are called into one body,
which Christ is the holy head of, prince of peace, governor, and counsellor;
but as there were such in the days of the apostles, that were self-willed,
wells without water, and carried about with tempests,
that speak great swelling words of vanity, promising themselves liberty,
that were presumptuous, and despised government.
And was not this the holy pure government of Christ in his male and female, his people,
his church which they despised?

Now they that have come so far as a Cain and a Balaam, to hear God`'s voice, and Korah,
Dathan, and Abiram that came out of Egypt,
and never came so far as to be baptized into the death of Christ; and to put him on,
nor ever came to be created anew in Christ Jesus,
and to put off the old man of Adam in the fall,
and to be renewed up again into the image of God, in righteousness and holiness,
that God Almighty made them in.
Therefore such Cains, Corahs,
and Balaams never came to know the government of Christ in male and female;
but presumptuously despised government, as Korah, Dathan, and Abiram did Moses,
and as Balaam, who went forth with Balak to curse Israel; but God restrained him,
and reproved him for his error, who was destroyed at last, as well as Korah, Dathan,
and Abiram:
so will all they come to naught that despise the
holy government of Christ in his males and females;
and do not you think that Korah, Dathan and Abiram,
and Balaam could not speak high swelling words of vanity,
though they were wells without water, and trees without fruit,
and clouds that are carried about with a tempest, as in 2 Pet.
ii. and Jude 11:12-13. Which such presumptuous
ones as these now are known by the fruits,
as it was in the apostles`' days,
which despise the righteous government of Christ in his male and female;
but Christ the beloved seed, who bruises the serpent`'s head, in all his followers,
and destroys the devil and his works, he will reign whose right it is,
in them that are baptized into his death, and have put him on,
and have put off the old man in Adam in the fall,
and have put on the new man in the image of God,
which he hath created in righteousness and holiness;
in such Christ was and is a wonderful counsellor, and a governor, and a prince of peace,
the same today as he was yesterday, and so forever, in his church, throughout all ages;
who destroys the devil and his works, that would hinder him; so he will reign, rule,
and govern, and is a counselor in the hearts of his people, whose right it is.
Blessed be the Lord forever.
Hallelujah to the Lord, and his Christ reigns.

God said, '`Let us make man in our image, after our likeness,
and let them have dominion,`' etc. Gen. 1:26.

Now the Lord saith, '`Let us,`' and were not all things made and created by Jesus Christ,
whose name is called the word of God?
And doth not John say, '`There are three that bear witness or record in heaven,
the Father, the word, and the holy ghost,
and these three are one?`' So there are three that bear witness and record in heaven, etc.
'`And there are three that bear record or witness in earth, the spirit, the water,
and the blood,
and these three agree in one.`' And is it not the
spirit of God that mortifies the deeds of the flesh,
and the water of the word that washes, and the blood of Christ that cleanseth?
Are not these three that bear witness for God in the earth, for man or against man,
are they not God`'s witnesses in the earth?
And the Lord saith, '`Out of the mouth of two or three witnesses, (namely,
men witnesses,) every word is established among men,
but the witness of God is greater`' than the witness of men.
He that hath an ear, let him understand these things. 1 John 3:7-8.

[.asterism]
'''

=== Here you may see how every one is to improve his talent which Christ gives them, if not, it will be taken from them, and they cast into utter darkness.

Christ Jesus saith,
'`The kingdom of heaven is as a man travelling into
a far country to receive for himself a kingdom,
and to return, who called his own servants, and delivered them his goods,
and to one he gave five talents, and to another two, and to another one,
and to every one according to his several ability,`' etc.
Matt. 25. Luke 19:20. '`And after a long time the Lord of those servants cometh,
and reckoneth with them; and he that had five talents, had gained five more;
and he that had two talents, had gained two more.
And the Lord commended these servants, and said, well done good and faithful servants,
enter into the joy of your Lord; but he that had received the one talent,
went and digged in the earth, and hid his Lord`'s money: the Lord said, take it from him,
and give it to him that hath ten, and cast the unprofitable servant into utter darkness,
and there shall be weeping and gnashing of teeth.`'

Now these talents that were given to the Lord`'s servants,
and to every one according to their several abilities, was the Lord`'s heavenly treasure,
and was not their own, but the Lord`'s, and they were,
and are to improve this heavenly treasure for the Lord, and to put it forth,
and to gain with it for the Lord at his appearing to them,
when he calls them to an account, that it may be said,
'`Well done good and faithful servant,
enter into the joy of the Lord.`' But the wicked and slothful servant,
(he is called a servant too,) hideth the Lord`'s talent in his earthly napkin,
and did not improve the Lord`'s heavenly treasure; and he was cast into utter darkness.
And therefore all are to consider,
whom the Lord hath given more or less of his heavenly treasure to, how you do,
and how you have put the Lord`'s heavenly treasure forth, and have improved it; I say,
the heavenly treasure which you have from the Lord Jesus Christ,
who spake this before he was crucified; and after he was risen,
did not he go to the Father to receive a kingdom; who said,
'`All power in heaven and earth is given to me?`' Therefore
the Lord`'s money or treasure of talents ought to be improved,
and put to the exchangers, that he may receive it with usury and advantage.
So here are exchangers of the heavenly talents or treasure of the Lord,
the increasing of them to advantage for the Lord;
as there is outward bankers and exchangers, and usuries,
where they do put forth their outward money for gain and profit to themselves.
But this is a parable that Christ speaks concerning
improving of his heavenly treasure of talents,
which every one is to improve, or increase that heavenly talent,
or measure which they have received from the Lord, as good and faithful servants,
and stewards, if that they do intend to enter into the joy of the Lord.

G+++.+++ F.

Kingston upon Thames, the 7th of the 10th month.
1687.

