== Concerning the apostate Christians, that think to do miracles by dead men`'s bones, etc. of praying to the saints that are dead, and asking counsel of the dead, and praying for the dead.
Concerning purgatory, and making a God or Christ of the elements of bread and wine.
Concerning the traditions the Jews taught,
which made the word and commandment of God of none effect,
and the traditions the apostate Christians teach people to follow,
and set up above the scriptures of truth.
How Christ is the true rock, and not Peter.
And that he is the head of the true Church, and so to he held by his members.
The antiquity of the cross of Christ,
which was and is acknowledged to he the power of God by his true Church.
By G. F.

The Lord saith, '`Whosoever toucheth the body of a man that is dead.
or dieth in his tent, and purifieth not himself, he defileth the tabernacle of the Lord,
and that soul shall be cut off from Israel, because it purifieth not itself;
and whosoever touched, any that are slain with the sword in the open field,
or a dead body, or the bone of a man, or a grave, shall be unclean seven days;
and if he do not purify himself, he shall be cut off from among the congregation,
because he hath defiled the sanctuary of the Lord.`'^
footnote:[Num. 19:11,13,16.]And this was the law of God,
and a perpetual statute among the Jews, as you may see in Num. 19.

And now, do you apostate christians imagine to do miracles with dead men`'s bones,
or the dust of the graves, which defiled the Jews,
and they were not to come into God`'s tabernacle or sanctuary,
but to be cut off according to the statute and command of God, if they were not purified?

And now if you apostate christians do allege of the Jews burying a man,
and casting him into the sepulchre of Elisha,
'`and when the dead man touched the bones of Elisha,
he revived and stood upon his feet.`' 2 Kings 13:21. But where
was ever such a miracle as this wrought by the apostate christians,
by burying one in the grave of another?
Let them produce one example if they can.

Let all the apostate christians produce one scripture where ever
the saints got the bones of the saints to do miracles by.

[.asterism]
'''

=== Of praying to the saints that are dead, and asking counsel of the dead, and praying for the dead.

Let all the apostate christians produce one scripture
for their vain tradition of praying for the dead,
or to the dead, or asking counsel of the dead;
but Saul when he had transgressed the command of God, and disobeyed him,
he went to the witch of Endor, pretending to raise up Samuel, to ask counsel of the dead;
but what was the end of Saul?
You may see in 1 Sam. 28. and 31. chapters.

And David prayed to God while his child was living; but when the child was dead,
he gave over praying to God for it, and fasting, and said, '`Now the child is dead,
I cannot bring him back again; I shall go to him,
but he shall not come to me.`' 2 Sam. 12:16 to
ver. 23. '`The grave cannot praise thee,
death cannot celebrate thee,
they that go down into the pit cannot hope for thy truth.`' Isa.
38:18. '`The dead praise not the Lord.`' Ps. 115:17.

And yet do not you pray to the dead, that cannot praise the Lord?
And Solomon saith, '`The dead know not anything.`' Ecc. 9:5,

And yet do not you pray to them that know not any thing?
Is not that madness?

[.asterism]
'''

=== Concerning the apostate christians`' tradition of a purgatory, after they are dead.

Solomon saith, '`All turneth to dust again;
and who knoweth the spirit of man that goeth upward;`' and the spirit
shall return unto God that gave it;`' so then not into purgatory. Ecc. 3:20-21.
xii.
7+++.+++ And Elisha prayed for the Shunimite`'s child that was dead,
and he was raised up to life; so he doth not say he prayed him out of purgatory.

And when Lazarus, that poor man, died, he was carried by angels into Abraham`'s bosom;
and when '`the rich man died and was buried, in hell he lift up his eyes,
being in torment, and seeing Abraham afar off, and Lazarus in his bosom,
he cried and said, Father Abraham have mercy on me,
and send Lazarus that he may dip the tip of his finger in water and cool my tongue,
for I am tormented in this flame.
But Abraham said, Son remember that thou in thy life time receivedst thy good things,
and likewise Lazarus evil things; but now he is comforted, and thou art tormented.
And besides all this, between us and you there is a great gulf fixed,
so that they which would pass from hence to you cannot,
neither can they pass to us that would pass from thence.`' Luke 16:22-26.

And now here you see, that when Lazarus died,
he was carried by angels into Abraham`'s bosom, not into purgatory,
who would have been glad of the rich hard-hearted man`'s crumbs that fell from his table;
and the rich man`'s dogs had more compassion of the poor man,
(in licking his sores,) than he had.
But when this rich man died and was carried into hell,
neither Abraham nor Lazarus could go to him, nor help him out, nor he to them;
so that neither Abraham nor Lazarus could relieve him there,
not with so much water as would hang on the tip of his finger to cool his tongue.

And Christ said to the thief upon the cross that was crucified with him,
'`Verily I say unto thee,
today shalt thou be with me in paradise.`' Luke 23:43. So he doth not say,
he should go into purgatory, to be purged;
but as Abraham said to the rich man that was in hell,
'`If they will not hear Moses and the prophets,
they will not be persuaded if one rose from the dead.`'
For these were the Jews to whom Christ spake this parable,
who set up their traditions, and made the word of God and his command of none effect,
so they were not like to hear Moses and the prophets,
who like the apostate christians now,
set up their vain traditions above the holy scriptures of truth,
and allow the ignorant people to read their traditions,
and deny them the reading of the scriptures,
contrary to the holy men of God that gave them forth, to be read, believed, fulfilled,
and practised, as in 2. Tim.
iii. 16. John 7:38. Luke 24:25. 1 Thessalonians 5:27.

'`Give attendance to reading,`' etc. 1 Tim. 4:13.
And Christ exhorts his hearers to ask in his name,
'`And whatsoever ye shall ask the Father in my name,
he shall give it you,`' as in John 16:23. 25,
26. And again Christ teacheth his disciples to pray, and say,
'`Our Father which art in heaven,`' etc.
So that Christ never taught his believers to pray either to his mother, the virgin Mary,
in his name, or to any saint, or in the name of any saint after they were dead,
nor his apostles after him.
And the apostle James saith in his General Epistle to the church of Christ,
'`If any of you lack wisdom, let him ask it of God,
that giveth to all men liberally.`' James 1:5. And John
saith in his General Epistle to the church of Christ,
'`If our hearts condemn us not, then we have confidence towards God;
and whatever we ask we receive of him, because we keep his commandments,
and do those things which are pleasing in his sight.`' John 3:21-22.
And again John saith,
'`This is the confidence that we have in God,
that if we ask any thing according to his will,
he heareth us.`' 1 John 5:14-15. And it is said,
'`Saul died for his transgression which he committed against the Lord,`' etc.
And also '`for asking counsel of one that had a familiar spirit,
(the witch of Endor,) and inquired not of the Lord,
and therefore he slew him.`' 1 Chron. 13:14. And you
read of such that set the counsel of the Lord at naught,
and would have none of his counsel, and what was their end?
as in Prov. 1:25-26. And the Lord said,
'`My people ask counsel at the stocks,`' etc. who were gone a whoring from God.
Were not these the Jews that followed their own traditions,
and made the commands of God of none effect,
(Hos. 4:12) like the apostate christians that
pretend to pray to saints that are dead,
and for the dead, that set up so many images and kneel down before them;
but hear what is said in Isa. 30:1. '`Woe to the rebellious children, saith the Lord,
that take counsel, but not of me, and cover with a covering, but not of my spirit,
that they may add sin to sin.`'

So here you may see what is the portion of all such that cover with a covering,
but not of God`'s spirit; and ask counsel, but not of him.

[.asterism]
'''

=== Concerning the apostate Christians.
traditions, of making a God or Christ of bread and wine; and of their bowing to him,
and worshipping him, and eating him when they have done.
We never read that the heathens, nor the apostate Jews,
when they had made gods and bowed to them, and worshipped them,
eat them when they had done.

Christ`'s disciples said unto him, the day of unleavened bread,
when the passover must be killed, '`Where wilt thou that we go and prepare,
that thou mayst eat the passover?`' Mark 14:12. Luke 22:7. Now Christ,
though he is the christian passover, he did not eat himself.

And again the apostle saith, '`In the same night that Christ Jesus was betrayed,
he took bread and brake it, and said, do it in remembrance of me,`' and likewise the cup.
So Christ`'s body was whole, and was not crucified when he brake that outward bread;
for that which they were to take in remembrance of Christ,
and in a show of his death until he came, it was not the Lord Jesus Christ,
but outward bread, and wine in an outward cup, and Christ was nowhere called a cup.
It is said,
'`Christ took the cup when he had supped,`' then
he did not take his own blood and give it unto them,
but he called it,
'`the fruit of the vine.`' Matt. 26:29. And Christ
took the cup and gave his disciples and said,
'`Drink ye all of it; and took the bread and brake it,
and gave it to his disciples also.`' And in Mark 16:22. '`they all drank of the cup,
and he brake the bread, and gave it to his disciples,`' (namely,
the twelve,) as in Luke 22. Then he did not brake his own body, for it was then whole;
and after he had broken the bread and given it them, and given them the cup,
and called it '`the fruit of the vine`'--after Christ had given them this, he said,
'`Drink ye all of this.`' Matt. 26:25. Luke 22:21. '`Behold, saith Christ,
the hand of him that betrayeth me is with me on the table.`' So it seems here,
that Judas did eat of the bread, and drink of the fruit of the vine in the cup,
and he did partake of these outward elements in the same night that Christ was betrayed,
which elements were taken in a show and remembrance of the Lord`'s death till he came;
but Judas did not stay till he came, for he betrayed him.

Now if this outward bread, had been Christ the living bread that came down from heaven,
and his blood, which if any man eat of that bread, and drink his blood,
he shall live forever, and not die; as Christ saith, '`Whosoever eateth my flesh,
and drinketh my blood, hath eternal life, and dwelleth in me and I in him;
and he that eateth me, shall live by me;
and he that eateth this bread that cometh down from heaven
shall live forever,`' see John 6:50 to 59.

Now here you see it is clear,
that the cup and the bread that Judas did eat and drink of at Christ`'s last supper,
was not the flesh of Christ, the bread of life that came down from heaven,
nor his blood that giveth life everlasting; for Judas had not eternal life,
nor did live forever, by eating of that outward bread, and drinking of that outward cup,
'`the fruit of the vine.`' And so Judas did not eat Christ, and live by him,
and live forever, though he drank of the outward cup,
'`the fruit of the vine,`' and eat of the outward
bread that Christ broke at his last supper,
the same night that he betrayed him; and that Judas might do,
and not eat the bread from heaven, the flesh of the son of man, and drink his blood;
for such have not life eternal in them, as Christ saith, that do not eat his flesh,
and drink his blood.
For Christ said, '`Except ye eat the flesh of the son of man, and drink his blood,
ye have no life in you.`' John 6:53. And the Jews murmured at Christ when he said,
'`I am the bread that came down from heaven;`' and '`except ye eat my flesh,
and drink my blood, ye have no life in you;`' and '`he that eateth my flesh,
and drinketh my blood hath eternal life.`'

So here is a great difference between the flesh and the blood of Christ,
the bread which came down from heaven, which giveth life eternal,
and the elements of bread and wine, which reprobates and Judas`'s may take and eat,
that have not life eternal, nor know Christ to be in them, as the apostle saith.
'`Where the tree falleth there it shall be.`' Ecclesiastes 11:3.

And after Esau had sold his birthright, he sought it carefully with tears,
but he found no place of repentance; and therefore, how are any like to repent,
and come out of the grave and purgatory, as you call it, after they are dead,
when Esau could not find repentance upon the earth?

[.asterism]
'''

=== Concerning the traditions of the Jews, and apostate Christians.

Christ said to the Pharisees,
'`Why do you transgress the command of God by your traditions?
You hypocrites, well did Isaiah prophesy of you:
This people draweth nigh me with their mouth, and honoureth me with their lips,
but their heart is far from me.
But in vain do you worship me,
teaching for doctrines the commandments of men.`' Thus you have
made the commandment of God of none effect by your traditions. Matt. 15:3.
6, 7, 8, 9.

And again Christ said unto the scribes and Pharisees,
'`Laying aside the commandment of God, you hold the traditions of men,
and of your elders;`' and again he saith unto them,
'`Full well you reject the commandment of God, that ye may keep your own traditions,
making the word of God of none effect through your traditions
which you have delivered.`' Mark 7:3. 8,
9. 13.

Now is not this the condition of the apostate christians
that set up their traditions above the scriptures of truth,
like the Jews, and forbid the reading of the scriptures of truth?
Nay, are not they worse than the Jews, for they must read and pray in an unknown tongue;
so are like barbarians, worse than the Jews who read and pray in their mother tongue?

And Paul saith to the church of Christ, '`Ye have heard of my conversation in times past,
in the Jews`' religion, how that beyond measure I persecuted the church of God,
and wasted it, and profited in the Jews`' religion above many my equals in my own nation,
being more exceedingly zealous of the traditions of my fathers; but when it pleased God,
who separated me from my mother`'s womb, and called me by his grace,
to reveal his son in me, that I might preach him,`' etc. Gal. 1:13-16.

Now here you may see while Paul was zealous of the traditions of his forefathers,
he was not separate from traditions, nor called by God`'s grace,
nor the son of God was not revealed in him; therefore he was not like to preach him,
but persecute him.

And now are all the apostate christians in their blind zeal of their forefathers,
(like persecuting Saul,) separate from the Lord, and not so called by God`'s grace,
as Paul was?
And is the son of God revealed in them that have
been such persecutors and wasters of God`'s people,
the church of Christ, since the apostles`' days?
And if not, can they preach Christ in truth,
but withstand him like the Jews in their traditions,
and set traditions above the holy scriptures of truth that testify of Christ?

And after the apostle was converted,
he bid the church of Christ '`Beware lest any man
spoil you through philosophy and vain deceit,
after the traditions of men, and not after Christ;
if you be dead with Christ from the rudiments of the world, why, as living in the world,
are ye subject to ordinances?
Touch not, taste not, handle not, which all are to perish with the using,
after the commandments and doctrines of men;
which if you be risen with Christ seek those things which are above,
where Christ sits at the right hand of God.
Set your affection on things above, not on things on the earth.`' Col. 2:8. 20, 21,
22, and iii.
1, 2.

So you may see that the apostle brought the church of Christ off the traditions,
and doctrines, and ordinances of men, and rudiments of the world;
and would not have them to be spoiled by any man, through philosophy and vain deceit,
for such things as these were not after Christ.
But the church of Christ was, and is to seek those things that are above,
where Christ sits at the right hand of God, and not those things on the earth,
which are below; they are not so much as to touch, taste, nor handle them,
all which perish with the using; but the scriptures of truth they are to read, believe,
and practice: for the church of Christ then, and now,
know that they are not redeemed with corruptible things, as silver and gold,
from their vain conversation, or by the traditions of their forefathers,
but with the precious blood of Christ, as of a lamb without spot or blemish.
Glory to God forever, through the Lord Jesus Christ,
who is the only one mediator between God and man, even the man Christ Jesus,
who makes peace between us and God; the same today, yesterday, and forever.

[.asterism]
'''

=== Christ is the rock and foundation which the heavenly Father revealed to Peter, on which he builds his church, and not on Peter, nor that which flesh and blood had revealed to Peter.

Jesus asked his disciples,
'`Whom do men say that I the son of man am?`' and the disciples answered and said,
'`Some say thou art John Baptist, and some say Elias, and others Jeremiah,
or one of the prophets.`'

Here you may see there were divers judgments and
opinions of Christ among people that knew him not.
And Jesus said unto his disciples, '`But whom do you say that I am?
And Simon Peter answered and said, Thou art Christ the son of the living God;
and Jesus answered and said, Blessed art thou Simon Bar-Jonah,
for flesh and blood hath not revealed this unto thee, but my Father which is in heaven;
and I say unto thee that thou art Peter,
and upon this rock will I build my church,`' (mark,
he saith upon this rock which flesh and blood had not revealed,
he doth not say upon thee Peter,) '`and the gates of hell shall not prevail against
it.`' And Jesus showed unto his disciples how that he must go to Jerusalem,
and suffer many things of the elders, chief priests, and scribes, and be killed,
and be raised again the third day.
'`Then Peter took Christ, and began to rebuke him, saying, Be it far from thee Lord,
this shall not be unto thee; then Christ turned and said unto Peter,
Get thee behind me Satan, for thou art an offence unto me,
for thou savourest not the things that be of God,
but those that be of men.`' Matt. 16:13-18; 21-23.

Now here you may clearly see that Christ doth not build his church upon Peter,
as a man of flesh and blood, or that which flesh and blood reveals,
but upon that rock which flesh and blood had not revealed unto Peter,
but the Father which is in heaven.
And so I say again, it is clear,
that Christ doth not build his church upon Peter and his outward name,
as a man of flesh and blood, nor upon that which flesh and blood may reveal,
or did reveal unto Peter;
but he builds his church upon that rock which the
Father which is in heaven had revealed to Peter,
which was,
'`Thou art Christ the son of the living God.`' This is the
rock and foundation that the true church is built upon,
Christ who bruises the serpent`'s head, and destroys the devil and his works;
so that the gates of hell cannot, nor shall not prevail against Christ`'s church,
and him the rock and foundation, which his church is built upon.
And though Christ blessed Peter in Matt. 16:17. after his revelation,
yet in the 23d verse, Christ said unto Peter, '`Get thee behind me Satan,
thou art an offence unto me, for thou savourest not the things which be of God,
but those that be of men.`' So here it is clear,
Christ did not build his church upon Peter, nor his outward name Peter,
as a man of flesh and blood, nor the revelation of flesh and blood, nor upon Satan,
for he bruises Satan the serpent`'s head;
so he was not like to build his church upon him: Therefore, they that do succeed Peter,
it must be in that which the Father revealed from heaven,
(to wit,) '`thou art Christ the son of the living God,`' '`upon
this rock will I build my church;`' but when Peter rebuked Christ,
saying, '`Be it far from thee Lord; this shall not be unto thee,`' (namely,
when Christ told him and the rest that he should suffer and be killed,
and rise again the third day,) Christ called Peter Satan, and bid him get him behind him,
as before.

And Christ said unto Peter, he was '`an offence unto him,
and savoured not those things that be of God,
but those that be of men,`' in that which he said to Christ.
And what, are any so ignorant as to think that Christ built his church upon Peter,
as he was in this condition?
No, surely, they are mistaken that think so;
and they that do succeed Peter in that condition, they savour not the things of God,
but of men, and are an offence to Christ, whom Christ calleth Satan,
and bids get behind him;
for he was not like to build his church upon that which was an offence unto him,
and savoured not the things of God, but the things of men.
And therefore they that build their church upon such,
the gates of hell are like to prevail against them;
and they that do succeed Peter in that spiritual revelation,
which the Father revealed from heaven, namely, Christ, the son of the living God,
upon which rock the true church is built,
which the gates of hell shall not prevail against; this is above Satan,
and the revelation of flesh and blood, and that which offends Christ,
and that which savours the things of men, and not the things of God,
and that which flesh and blood may reveal;
Christ`'s church is not built upon such things, but the rock which is far above them,
which the heavenly Father revealeth, and hath the glory of it, who is blessed forever.
Amen.

G+++.+++ F.

[.asterism]
'''

=== Now concerning whom the scripture saith is the true rock and foundation.

David saith, '`The Lord is my rock and my fortress,
and my deliverer.`' Ps. 18:2. And again, David saith, '`For who is God save the Lord,
or who is a rock save our God.`' Verse 31. And again,
'`He (viz. God,) only is my rock and salvation, he is my defence,
I shall not be moved.`' Ps. 62:2.6. And David speaking of Israel, said,
'`They remembered that God was their rock.`' Ps. 78:35.

And Isaiah speaking of Christ, saith, that '`he shall be for a sanctuary,
a stone of stumbling, and a rock of offence,
to both the houses of Israel.`' And Peter is so far off from looking
upon himself to be the rock upon which Christ builds his church,
that he tells the church of Christ, in his General Epistle,
that Christ was '`a stone of stumbling,
and a rock of offence to them which stumble at the word,
being disobedient.`' 1 Pet. 2:8. For the apostle saith to the Romans,
the church of Christ, speaking of Christ,
'`Behold I lay in Zion a stone of stumbling and a rock of offence,
and whosoever believes in him shall not be ashamed;`' this was Christ, and not Peter. Rom. 9:33.
And the apostle tells the church of Christ, speaking of Israel,
how that '`they did all drink the same spiritual drink,
for they drank of the same spiritual rock that followed them,
and that rock was Christ.`' 1 Cor. 10:4. So he did not say it was Peter,
nor any outward man.

And the wise man builds his house upon the rock Christ Jesus; if it be not,
the rain and the floods will beat it down,
as in Matt. 7:25. And the apostle tells the church of Christ,
'`No other foundation can any man lay than that which is already laid,
which is Christ Jesus.`' 1 Cor. 3:11. And again he saith to the Ephesians,
'`You are built upon the foundation of the apostles and prophets,
Christ Jesus himself being the chief corner stone;`'
so the rock and foundation of God stands sure.
Christ Jesus, the same yesterday, and today, and so forever.

[.asterism]
'''

=== The antiquity of our Cross.

The apostle saith to the church of Christ,
that '`the preaching of the cross is to them that perish foolishness;
but unto us that are saved,
it is the power of God.`' 1 Cor. 1:18. And such
as were and are enemies to the cross of Christ,
were and are enemies to the power of God; so all your stone, wooden, brass,
silver or gold crosses you have invented and set up since the apostles`' days,
are not the cross of Christ the power of God.

And the apostle saith,
'`God forbid that I should glory save in the cross of our Lord Jesus Christ,
by whom the world is crucified unto me,
and I unto the world.`' Gal. 6:14. So it was the power of God, the cross of Christ,
that the apostle gloried in, by whom the world was crucified unto him,
and he unto the world;
and this is our cross which was set up above one thousand six hundred years ago;
and it is not likely that it was a cross made of wood, stone, iron, brass,
silver or gold that the apostle or the church of Christ gloried in,
or that such outward temporal and worldly crosses as men make and invent,
should crucify people to the world!
That which crucifies people to the world, and the world to them, is the cross of Christ,
the power of God, which power of God all are to bow down to;
and they are foolish and dark that think a cross of stone, wood, iron, silver, or gold,
which man hath made, is the cross of Christ, the power of God;
and to bow to such worldly temporal things, and call them the cross of Christ,
is contrary to the scriptures that the apostles taught to the church of Christ,
in their day; and this was the church of Christ`'s cross in their days,
and is the church of Christ`'s cross now, but they could not,
nor can we bow to any temporal, outward,
worldly cross that men have made with their hands, and bow down to them;
for such as do worship the works of their own hands are enemies to the cross of Christ,
the power of God.

There were such in the apostles`' days that were
vainly puffed up with their fleshly minds,
not holding Christ the head, and so there are now,
from which head all the body of Christ by joints and bands hath nourishment ministered,
and by him is knit together, and increaseth with the increase of God;
as in Col. 2:18-19.

Now Christ enlightens every man that comes into the world with the light,
the life that is in him, the head, by whom the world was made,
that with the light they might see Christ, and him the head of the body, his church,
by which all the children of the light and of the day may be knit together in him,
and have their increase of God ministered through him,
and so to have fellowship with the Father and the son, and one with another.

Now all they that are intruding into things they have not seen,
puffed up with a fleshly mind, and do not hold Christ their head,
but have set up other heads, have broken into sects, schisms,
and divisions one against another: this is clearly seen now,
as it was in the apostles`' days.

G+++.+++ F.

The 2d month, 1688.

