[#ch38.style-blurb, short="The Speech of Sultan Mahomet"]
== The speech or declaration of Sultan Mahomet, the Great Turk, which he sent to the emperor of Germany, dated March 25th, 1683, from Adrianople, just after the Baron Saphonara, the Emperor`'s Ambassador, had his last audience of the Prince Vizier, wherein the said Ambassador could not comply with the extravagant demands of the Turk; which caused the said Grand Seignior to transmit the same to his Imperial Majesty: which is faithfully translated out of High Dutch.

Mahomet the Fourth, son of emperors, and of the famous and renowned God;
emperor of the Turks, king of Greece, Macedonia, Moldavia, Samaria, and Hegha;
king of great and lesser Egypt; king of all the inhabitants of the earth,
and prince of the earthly paradise; acknowledged prince and obedient son of Mahomet;
preserver of the cities of Hungaria; possessor of the sepulchre of your God;
lord of all the emperors of the world,
from the rising of the sun to the going down thereof: king of all kings,
lord of the tree of life, conqueror of the Malonian Hegley, and the city Prokenix;
the great persecutor of the Christians, and all wicked people;
joy of the flourishing world, commander and guardian of your crucified God,
lord of the multitude of the heathens.
We command ye to greet the emperor Leopold, in case he desire it;
and you are a friend to our majesty, whose power and will we have extended very far.

You have for some time past acted to our prejudice, and violated our friendship;
though we have not offended you either by war or otherwise;
yet you have taken secret advice with other kings, and your councils,
how to shake off your yoke; in which you have proceeded very indiscreetly;
and thereby you have exposed your people to fear and danger,
who have nothing to expect now but death, which you have brought upon yourselves:
for I declare I will make myself your master, and pursue you from the east to the west,
and extend my majesty to the end of the earth.
In the procedure of all which, you shall find my power exerted to your extreme prejudice,
and shall feel the dreadful effects of my wrath.
And since you have put your hope in the strength of some towns and castles,
I have given command to overthrow them,
and trample under my horses`' feet all that is delightful to you,
leaving no room hereafter to make friendship with me,
or suffer you any fortified place to remain to put your trust in;
for I have resolved forthwith to destroy you and your people,
and to depose you of the German empire, after my will,
leaving in the empire a remembrance of my dreadful sword,
that it may publicly appear that I will establish my religion therein,
and pursue your crucified God, whose wrath I fear not, nor his coming to defend,
or deliver you out of my hands; but will condemn your sacred priests to the plough,
and suffer the breasts of your wives to be sucked by dogs and beasts.
You will do well to forsake your religion,
otherwise I will give order to consume you with fire.
This is enough to let you understand my will, if you will be so wise as to know it.

[.blurb]
=== An answer to the speech or declaration of the great Turk, etc. By G. F.

[.salutation]
Sultan Mahomet,

I find in a paper, which is said to be thy declaration, directed to Leopold,
the German emperor, dated the 25th of March, 1683, viz.

[.numbered-group]
====

[.numbered]
_First,_ thou sayst thou art a '`possessor of the sepulchre of your God,`' to wit,
the christians.
And that thou art a great persecutor of the christians.

[.numbered]
_Secondly,_ thou sayst thou art lord of all the emperors of the world,
from the rising of the sun to the going down thereof.

[.numbered]
_Thirdly,_ thou sayst thou art king of all kings, and lord of the tree of life.

[.numbered]
_Fourthly,_ thou sayst thou art commander and guardian of your crucified God, (to wit,
the christians,) and thou sayst, thou wilt '`pursue your crucified God,
whose wrath I fear not, nor his coming to defend or deliver you out of my hands.`'

====

Now, here is something in answer to the words of sultan Mahomet,
the emperor of the Turks, saying, he is a great persecutor of the christians;
but let him take heed, for the great God that made him, and heaven, and earth,
and the sea, and all things therein, who is Lord, Creator, and Father of all,
who is above all, and through all, and beholds all his words, ways, thoughts,
and actions, and all men`'s and women`'s upon the earth;
neither is there any creature that is not manifest in God`'s sight,
but all things are naked and open unto the eyes of him, with whom we have to do,
who are the true christians, in scorn called Quakers, who do fear, serve,
and worship the great God that made us, who is a consuming fire to the wicked.
And wheresoever men do turn themselves, there the face of God will meet them;
his divinity extends through the whole world.
Therefore you are to fear his divine majesty, as you do confess in your Alcoran;
for the great God, the creator of all, doth know all in the heavens, and in the earth,
both what is done in secret, and openly, and all is naked before him,
who will reward every man, and woman, according to their words and works,
whether they be good or evil, for God is a consuming fire to the wicked;
and who shall dwell with everlasting burning, but the just and holy?

And, Mahomet saith in his Alcoran, chap.
iii. page 34, that Jesus said, '`Who shall sustain the law of God in my absence?
And the apostles answered him,
we will sustain the law of God in thy absence;`' and that '`Jesus shall be a
witness in the day of judgment against such that obey not his law,`' etc.

Now see how you Turks do obey the law or command of Jesus, for Jesus saith,
'`Love your enemies, bless them that curse you, do good to them that hate you,
pray for them that despitefully use you, and persecute you,
that you may be the children of your Father which is in heaven.`'

Now if the christians were the Turks`' enemies,
according to the command and law of Jesus the Turks
are to love and bless them that curse them,
and do good to them that hate them,
and pray for them that despitefully use them and persecute them;
so then the Turks are not to be persecutors,
if they do obey the command of the Lord Jesus Christ,
and if they be the children of God the Father which is in heaven.

[.numbered-group]
====

[.numbered]
But the emperor of the Turks saith, he is a great persecutor of the christians;
and you say in your Alcoran,
that '`Jesus shall be a witness in the day of judgment against
such that obey not his law?`' Are not your own words in your Alcoran,
(and the Lord Jesus, and the apostles of Jesus,
who should sustain the law of God in Jesus`' absence,) witness against you,
who are haters and persecutors, instead of loving enemies,
according to the command or law of Jesus?
And therefore as Mahomet saith,
'`Jesus shall be a witness in the day of judgment against
such as obey not his law.`' So according to your own Alcoran,
you Turks, and all others that are persecutors, who disobey the law of Jesus,
he will be a witness against you in the day of judgment; yea, I say, against you Turks,
and all other persecutors upon the earth.

[.numbered]
_Secondly._
Sultan Mahomet, emperor of the Turks, saith, he is lord of all the emperors of the world,
from the rising of the sun to the going down thereof, king of all kings,
and lord of the tree of life.
But are there not many kingdoms and kings in this northern part of the world,
and many emperors and heathen kings in America, and also in the East Indies?
Hath not the Great Mogul many kingdoms under him?
Besides Prestor John, (commonly so called,) hath not he many kingdoms under him?
And doth not the emperor of the Turks know,
that these kingdoms and empires he is neither king nor emperor over?
Yet he saith, he is emperor over all the earth, from the rising of the sun,
to the going down thereof!
Which world he knows is but his own country, and from the rising of the sun in it,
to the setting of the sun in it; for the sun riseth and sets in America,
and the East Indies, and all other parts of the world where he hath no rule nor power;
and how long he may have rule and power, and be emperor in his own country God knows.
And therefore it is best for the emperor of the Turks to be humble,
and not conceit himself with an high and ambitious mind, that he is king of kings,
and emperor of the world where he is not, and where God hath given him no power,
lest the Almighty God do abase him, and take away his power which he hath given him.
For Daniel said to Nebuchadnezzar the emperor, that he should '`eat grass like an ox,
etc. till he knew that the Most High God ruleth in the kingdoms of men,
and giveth them to whomsoever he will;
and his kingdom should be sure to him after that he knew that the
Most High did rule.`' And therefore the unchangeable God,
man must fear; for heaven is his throne, and the earth is his footstool,
that earth that the Turks and all men stand and walk upon.
And so from the face of the eternal God and his footstool, cannot the Turk,
nor any other man or woman turn themselves, but there the face of God will meet them,
for God`'s divinity extends throughout all the earth; who inhabits eternity,
and dwells with an humble heart; who beholds the proud and lofty afar off,
and brings down the high looks, and abaseth the pride of men.

[.numbered]
_Thirdly._
And again, Sultan Mahomet, emperor of the Turks, thou sayst,
thou art lord of the tree of life.
But the Turkish emperor must know he is not lord of the tree of life,
which beareth twelve manner of fruits, and yieldeth her fruits every month;
and the leaves of the tree were for the healing of the nations.
We do not believe that the emperor of the Turks hath
any such natural tree in all his land or garden,
that yieldeth twelve manner of fruits every month,
the leaves of which are for the healing of nations.
This tree of life the Turks have no power over; and John the apostle of Christ,
that kept the law or command of Jesus, Jesus spake to him and said,
'`Blessed are they that do his commandments,
that they may have right to the tree of life,
that they may enter through the gates of the city,`' namely, heavenly and holy Jerusalem,
which descends out of heaven from God,
which is not outward Jerusalem in the land of Canaan;
as in the Revelations of John the 21st. and 22d chap.
And Christ said to John his apostle, '`He that overcorneth,
I will give him to eat of the tree of life;`' namely, he that overcomes the devil, sin,
and unrighteousness, whose name is written in the book of life,
hath right to eat of the tree of life.
But if the emperor of the Turks doth not overcome, with the spirit of God and his power,
the devil and his works, sin and unrighteousness, etc. he cannot eat of the tree of life;
therefore he is not like to lord, and to have power over this tree of life,
which he cannot eat of,
except with the power and spirit of God he overcome the devil and his works.

And concerning the pure religion and the false,
James who was one of the apostles of Christ Jesus saith,
'`If any man seems to be religious, and bridles not his tongue,
but deceives his own heart, that man`'s religion is in vain.`' Therefore,
what religion soever the emperor of the Turks set up or profess,
or any man or woman else in the whole world,
and bridle not their tongues with God`'s power and spirit,
according to the law or command of Jesus which he gave to the apostles,
their religion is vain,
and they do but deceive their own hearts with their vain religion,
from their unbridled tongues;
'`For pure religion and undefiled before God and the Father, is this,
to visit the fatherless and the widows in their affliction,
and to keep themselves unspotted from the world.`' And this
is the pure religion that God and Christ Jesus set up,
and his apostles preached and declared to men,
and all the believers and converted to God and Christ, and that keep their command,
did and do walk in this pure religion.

[.numbered]
_Fourthly._
Sultan Mahomet, emperor of the Turks, thou sayst,
thou art commander of the christians crucified God; and sayst,
thou wilt '`pursue their crucified God, whose wrath thou fearest not,
nor his coming to defend or deliver them out of thy hand.`'

====

[.discourse-part]
_Answer._
These high words are not spoken in the fear of God;
for if thou knowest God thou wouldest know his son Jesus Christ,
who was made of the seed of Abraham according to the flesh,
and declared to be the son of God, according to the spirit of holiness,
by the resurrection from the dead; so that thou hast neither power over his godhead,
nor his flesh.
And Mahomet confesses in his Alcoran, '`that Jesus, son of Mary,
is full of light,`' (which is according to the ancient scriptures,) '`and of the gospel,
to conduct people the right way; with a confirmation of the old testament,
and to guide and instruct the righteous.`' Now Mahomet and the Turks,
who make this confession in your Alcoran, then you must believe the old testament,
and the gospel of the new, concerning Christ Jesus, the son of Mary,
and of the seed of David, according to the flesh;
and that Jesus Christ came according to the promise of God to his prophets,
who was born of the virgin Mary.

And Mahomet in his Alcoran confesses '`that Jesus
Christ was not begotten by the will of man,
who was conceived of Mary, and that she should conceive,
and bring forth without the touching of man.`' I say, the angel of God said to Mary,
he was '`conceived by the holy ghost,`' and so called the son of God.
And Mahomet saith in his Alcoran, page 30. chap.
xxxiii '`That John did affirm Christ to be the Messiah, and to be the word of God.`'

Now if the Turks do believe this which Mahomet saith in his Alcoran,
then you must believe what Christ saith of himself, and the angel of God,
and what the apostle saith of him John saith of him, '`In the beginning was the word,
and the word was with God, and God was the word; and all things were made by the word,
and without him was not any thing made that was made.
And in the word was life, and the life was the light of men,
and that was the true light which enlightens every man that comes into
the world.`' Now here is the divine light which is the life in Christ,
the word, by which all things were made,
which enlightens every man that comes into the world, to their salvation,
if they believe in the light, and to their condemnation if they hate the light.
And John saith, '`This word was made flesh, and dwelt amongst us,
and his apostles beheld his glory, as the glory of the only begotten of the Father,
full of grace and truth,
and of his fulness they did receive grace for grace;`' and saith,
'`The law came by Moses, but grace and truth by Jesus Christ.`'

Now whereas the emperor of the Turks saith,
'`that he is commander and guardian of the christians`'
crucified God.`' Now in this he is mistaken;
for the eternal, incomprehensible, invisible, everlasting God,
whose divinity extends throughout the whole earth, who is God in heaven above,
and in the earth beneath, to whom all nations are but as the drop of a bucket;
this is the true christian`'s God, whom they serve and worship in his spirit and truth,
which the Jews did not crucify, nor could they crucify.
And it is blasphemy for the Jews, or any to say,
that they did crucify the true christians`' eternal invisible God;
and great ignorance for any to say, that the true christians`' God was crucified,
or that the eternal, incomprehensible, immortal God, the creator of all,
who is the God of the spirits of all flesh,
and the breath of all mankind is in his power; so that poor mortals, or externals,
should say, think, or imagine that the eternal, invisible, everlasting, immortal,
incomprehensible God was, or can be crucified, which they cannot comprehend,
which is the true christians`' God.

But Christ, which was made of the seed of David, according to the flesh,
who took not upon him the nature of angels, but the seed of Abraham,
he suffered for us in the flesh.
And so as Christ also hath once suffered for sins in the flesh,
he the just for the unjust, that Christ might bring us to God.
So God was not crucified, but Christ being put to death, or crucified in the flesh,
but quickened again in the spirit and rose again, and sits at the right hand of God.
This Peter, one of the apostles of Jesus, testifieth,
and the true christians now believe it; and though Christ was crucified through weakness,
that is, through the flesh, yet he is alive, and liveth by the power of God.
2 Cor.
xiii.

So it is clear that the eternal, and invisible, incomprehensible God, was not,
nor cannot be crucified; but Christ, the son of God, suffered according to the flesh,
not in his godhead.
So Christ died for our sins, according to the scripture of the old and new testament.
'`For as in Adam all died, so even in Christ shall all be made alive,
and that Christ by the grace of God should taste
death for every man.`' So it was not the invisible,
eternal, incomprehensible God that was crucified and died,
and did taste death for every man, but Christ according to the flesh,
who was manifest to take away our sin, and in him there was no sin.
So Christ was manifest to destroy the works of the devil, and Christ through his death,
destroys death that sin brought, and the devil the power of death.
'`And about the ninth hour,`' (when Jesus Christ
hanged upon the cross,) '`he cried with a loud voice,
saying, My God, my God, why hast thou forsaken me.`' So it is clear,
the eternal God did not die, nor was crucified, but Christ was put to death in the flesh;
this testifies Matthew, one of Christ`'s apostles.
So he was the one offering, who made an end of all the offerings among the Jews,
through the offering up of the body of Jesus once for all.
So the man Christ Jesus offered up himself one sacrifice for sins;
so by that one offering he hath perfected forever them that are sanctified;
so he is the propitiation, offering, and sacrifice for the sins of the whole world, yea,
Jesus Christ which was of the seed of David; and so, according to the scripture,
Christ died for our sins, and he was buried, and rose again the third day,
according to the scriptures;
and after he was risen from the dead he was seen of the apostles;
and again he was seen of above five hundred brethren at once, that were believers in him;
and this was after he was dead, buried, and risen.
But none of the princes of the world knew him; for had they known Christ,
they would not have crucified him.
But we know now, that Christ being raised from the dead, dies no more,
and death hath no more dominion over Christ, in that he died unto sin,
and for the sins of the whole world; but now he being raised from the dead,
he is set at the right hand of God.
And therefore, Jesus of Nazareth, a man approved of God by miracles, wonders, and signs,
which God did by him, this Jesus, the son of Mary,
the Jews with their wicked hands did take, crucify, and slay.
But it was God who loosed the pangs of death,
because it was not possible that he should be holden of it;
and though the Jews did crucify Jesus and slew him, and hanged him on a tree,
yet God hath raised him up the third day, and God hath exalted him at his right hand,
to be a prince and a saviour, to give repentance, etc. and forgiveness of sins.
So Christ`'s apostles were witnesses, how God raised him from the dead.
So you may see here, it was not God that was crucified and died,
for he raised Christ from the dead on the third day,
and showed him openly to his apostles;
and they did eat and drink with Jesus Christ after
that God had raised him up from the dead.
And he commanded his apostles to preach to the people, and testify,
that it was he that was ordained of God to be judge of the quick and dead,
and to him gave all the prophets (and apostles) of God witness,
that through the name of Jesus,
whosoever believed in him should receive remission of sins,
neither is there salvation in any other;
for there is no other name under heaven given amongst men whereby we must be saved,
but by Jesus of Nazareth, whom the Jews crucified, whom God hath raised from the dead.
For God said to David, '`That of the fruit of his loins,
(according to the flesh,) God would raise up Christ to sit on his throne.
And David, he seeing this before, spake of the resurrection of Christ,
that his soul was not left in hell, neither did his flesh see corruption.`' So,
though the Jews crucified him, and a soldier thrust a spear into his side;
and though he was crucified and hanged on a tree, and slain, dead, and buried,
him did God raise up the third day, and he appeared to his apostles and disciples,
and did eat and drink with them after he was risen; who were the faithful witnesses,
that God raised him up from the dead,
who is ascended up into heaven at the right hand of God,
who being the brightness of God`'s glory, and the express image of his substance,
and upholding all things by the word of his power,
when he had by himself purged our sins,
sat down at the right hand of the Majesty on high,
whom the heavens must receive until the time of the restitution of all things,
which God hath spoken by the mouth of all his holy prophets since the world began;
and he that descended, is the same also that ascended far above all heavens,
that he might fill all things, who led captivity captive, and gave gifts unto men, etc.
And we have redemption through Christ`'s blood, even forgiveness of our sins,
who hath delivered us from the devil,
(the power of darkness,) who is the seed of the woman,
which bruiseth the old serpent`'s head, which deceived Adam and Eve;
which God promised to Adam,
'`that the seed of the woman should bruise the serpent`'s head;`' in which seed,
viz. Christ, all nations are blessed, '`who is the image of the invisible God,
the first born of every creature; for by him were all things created that are in heaven,
and that are in the earth, visible and invisible, whether they be thrones, or dominions,
principalities, or powers; all things were created by him, and for him,
and he was before all things,
and by him all things consist.`' And Christ saith in his prayer to his Father,
'`This is eternal life, that they might know thee the only true God,
and Jesus Christ whom thou hast sent.`' And Jesus desired of God his Father, saying,
'`That those whom God had given him, might be with him where he was,
that they might behold his glory which God hath given him;`'
for he loved him before the foundation of the world;
therefore, saith Christ, '`Now, O Father, glorify thou me, with thy own self,
with the glory which I had with thee before the world was.`' And
Christ said to his disciples after he was risen from the dead,
'`All power in heaven and in earth is given unto me;`' and he bid his disciples,
go into all the world, and preach the gospel to every creature, etc.
And then after the Lord Jesus Christ had spoken to his disciples,
he was received up into heaven, and sat down at the right hand of God.
And now, we who are the believers in Christ Jesus, and true christians,
we do live unto him; and if we die, we die unto the Lord, whether we live or die,
we are the Lord`'s. '`For this end Christ both died, revived, and rose,
that he might be the Lord both of the dead and of
the living.`' And he is judge both of quick and dead,
who is the only one mediator between God and man, even the man Christ Jesus,
who makes intercession to God for his people,
and is able to save to the utmost all that come to God by him;
who ever lives to make intercession for them,
who is sat down at the right hand of God in heaven;
who is the prince of the kings of the earth, who said to John,
'`I am the first and the last, I am he that liveth, and was dead, and behold,
I am alive forevermore.`'

And therefore Sultan Mahomet, emperor of the Turks, who saith,
I will pursue your crucified God: wherein he is mistaken,
it was not the eternal incomprehensible God, but Christ that was crucified,
and died for his, and all men`'s sins, if the emperor of the Turks will believe it;
if not he will die in his sins.
And if he thinks to pursue Christ that was crucified,
he is like unto the Jews that did crucify him.
But Christ is risen from the dead, and is alive, and dies no more,
death hath no more dominion over him, nor hath Mahomet neither; and so is alive again,
and lives forevermore, and is sat down in heaven at the right hand of God,
out of the Jews`' and Turks`' reach to pursue,
so is far above their vain imagination and reach.
And he that hath all power in heaven and earth given to him,
who is the prince of the kings of the earth, and King of kings, and Lord of lords,
and rules all nations with a rod of iron, he is able to dash them to pieces,
like a potter`'s vessel, and to abate the pride of haughty men,
and to save and deliver his people out of the hands of the destroyers;
for he gives unto his believers and followers eternal life.
And Christ who laid down his life for his sheep, said to the Jews,
'`He had power to lay down his life, and he had power to take it up again:
this commandment I have received of my Father,`' saith he;
so it was not God his Father that died.
And Jesus said, '`his sheep heard his voice, and followed him;`' and saith he,
'`I give unto them eternal life, and they shall never perish,
neither shall any man pluck them out of my hand;`' and saith Christ,
'`My Father that gave them me is greater than all,
and no man is able to pluck them out of my Father`'s hand.`'

Here the emperor of the Turks may see, that neither he nor the Jews,
nor any man upon the earth, is able to pluck Christ`'s sheep out of his hands,
Jesus Christ saith so, who hath all power in heaven and earth given to him,
and is the prince of the kings of the earth, and King of kings, and Lord of lords.
And your own Alcoran saith,
'`that Jesus will be a witness in the day of judgment against them that obey not his law,
and do not believe in him;`' and here the emperor may see,
that Christ is able to defend his sheep and save them;
and none is able to pluck them out of his hands; who said,
'`All power in heaven and earth is given unto me;`'
who is sat down in heaven at the right hand of God,
and is revealed by his spirit in his people, who know his heavenly voice,
distinct from the voice of the devil and all his angels,
and all the natural men`'s voices upon the earth; Christ Jesus`' heavenly voice is known,
distinct from them all, who is above them all.
And God and Christ may suffer or permit thee to destroy hypocrites,
etc. but Jesus Christ saith, thou,
nor any man is able to pluck his sheep out of his hands, yea,
out of his hand that was crucified, and is risen, and ascended into heaven,
and sits at the right hand of God; thou hast no power to pluck his sheep out of his hand,
and therefore thou art not able, nor any man.
And therefore take heed of striving against him that is too mighty for thee.

And Sultan Mahomet, emperor of the Turks, thou sayst,
'`thou dost not fear the wrath of their crucified God, to wit,
the Christians.`' As is said before, God cannot be crucified,
but Christ Jesus was crucified according to the flesh, who is risen and ascended,
and sits at the right hand of God.
But hear, O Turk! what his apostle saith of him,
'`When the Lord Jesus Christ shall be revealed from heaven,
with his mighty angels in flaming fire, taking vengeance on them that know not God,
and obey not the gospel of our Lord Jesus Christ;
who shall be punished with everlasting destruction from the presence of the Lord,
and from the glory of his power, when he shall be glorified in his saints,
and be admired by all them that believe;
who shall consume the wicked with the spirit of his mouth,
and destroy them with the brightness of his coming.`' Hallelujah.
And therefore let every one that names the name of Jesus, depart from iniquity,
for he hath borne the iniquities of us all, and makes an end of sin,
and redeems us from iniquity, and finishes transgression;
who through his death destroys death that sin brought, and the devil the power of death;
and so here is no other name amongst men, given under the whole heaven,
whereby we must be saved, but by the name of Jesus, which signifies a saviour.
And according to the prophet, '`A virgin shall be with child conceived by the holy ghost,
and shall bring forth a son, and they shall call his name Emmanuel,
which by interpretation is God with us;`' so by his son Jesus Christ, God is with us,
that God who was speaker unto, and teacher of Adam and Eve in paradise:
and as long as they kept under his teaching, they were happy;
but when they forsook God`'s teaching and speaking,
and hearkened unto the serpent`'s speaking and teaching, and followed it,
they came into misery, and his posterity.
But according to the promise of God to Adam, '`the seed of the woman is come,
to bruise the serpent`'s head,`' the destroyer; and he, namely, Christ the son of God,
is the saviour; and now in these last days, God teaches us,
and speaks to us by his son Christ Jesus,
whom God hath appointed to be heir of all things, by whom he made the world, the heavens,
and the earth, and the seas, and all things therein;
and so all the children of the Lord are taught of the Lord,
and in righteousness are they established.

And there are three which bear witness or record in heaven, the Father, the word,
and the holy ghost; and these are one: and there are three which bear record in earth,
the spirit, the water, and the blood,
(viz.) the blood of Christ which cleanseth from all sin,
and the water which washeth from all filthiness, and the spirit to lead into all truth,
and baptizes and plunges down sin and evil, and to circumcise,
to put off the body of death, and sins of the flesh,
which are come into man and woman by transgression.
And you must feel this spirit in your hearts,
which is a witness for God who gives it you, which will be a witness for you,
or a witness against you.
And you must feel the blood of Christ sprinkle your consciences from your dead works,
that you may serve the living God; which blood will be a witness for you,
or a witness against you.
And you must feel the water of the word to wash you and cleanse you,
which will be a witness for you, or a witness against you.
So the spirit of God, the blood of Jesus, the water of the word,
are three that agree in one, that bear witness or record in the earth;
and there are three which bear witness or record in heaven, the Father, the word,
and the holy ghost, and these three are one.
He that hath an ear to hear, let him hear.

'`By the offence of one, (to wit, Adam,) judgment came upon all men to condemnation;
even so by the righteousness of one, (to wit,
Christ Jesus,) the free gift of God came upon all men unto justification of life.`'

For God so loved the world, that he gave his only begotten son Jesus Christ,
that whosoever believeth in him should not perish, but have everlasting life.
And they that do believe in him have everlasting life. John 3:16.
Rom. 5:18. Now concerning God`'s son, Jesus Christ our
Lord, he was made of the seed of David according to the flesh,
and declared to be the son of God with power, according to the spirit of holiness,
by the resurrection from the dead. Rom. 1:3-4.

[.signed-section-signature]
G+++.+++ F.
