[#ch39.style-blurb, short="Concerning Daily Sacrifices and Offerings"]
== Concerning daily Sacrifices and Offerings. By G. F.

The priests under the law daily offered sacrifices;
but Christ our high priest need not daily, as those priests,
offer sacrifice for his own sin,
and then for the people`'s. (Heb. 7:16. 28.) For Christ did once offer up himself,
who is made, not after the law of a carnal commandment,
but after the power of an endless life; who is sat down at the right hand of God,
and so cannot be offered as an offering and sacrifice any more;
who abolished the changeable priesthood, with all its offerings and sacrifices,
by the sacrifice and offering of himself once for all.

And so it is said, '`I am come to do the will of God;`' to take away the first, namely,
priesthood and covenant offerings, and establish the second,
by the which will we are sanctified through the offering of the body of Jesus.
Mark, Christ`'s body is offered up once for all. Hebrews 9:10.

And so Christ is entered into heaven itself, not that he should offer himself often,
as the high priests did, for then must Christ often have suffered;
but he hath put away sin by the sacrifice of himself once for all.
So Christ was once offered to bear the sins of many, '`and unto them that look for him,
shall he appear the second time without sin unto salvation;`' as in Heb. 9:25-26. 28.

So here you may see Christ is not often offered up as a sacrifice,
or an offering for the sins of the whole world, then had he often suffered.
But after Christ had offered up one sacrifice for sins forever,
he sat down at the right hand of God.
And by this '`one offering Christ hath perfected forever
them that are sanctified.`' So here you may see,
it is one offering, and one sacrifice once for all, not offering Christ many times,
nor often.

And in Hebrews 12:12. 14. The priests under the law, they offered offerings;
but Christ offered up himself, who had power to lay down his life, and take it again;
so it was not priests that offered Christ up:
for after Christ had offered up one sacrifice, and one offering for sins,
by which offering and sacrifice '`he perfected forever them that
are sanctified,`' and sat down at the right hand of God,
who ever lives to make intercession for his people.

And Christ saith, '`Offerings and sacrifices thou wouldst not,
but body hast thou prepared me to do thy will;
by the which will we are sanctified through the offering
up of the body of Jesus Christ once for all,`' as before.
And so he did not often offer up his body as a sacrifice for all,
for then must he often have suffered, as before; but now once, mark, once,
hath he appeared to put away sin by the sacrifice of himself,
and not by offering or sacrificing of himself often; for as it is said,
Christ '`having somewhat to offer,`' that is, he offered up himself, his body,
once for all sins, and the daily sacrifice, and made an end of the daily sacrifices;
as in Dan. 9. Wherein you may see he caused the
daily sacrifices and oblations to cease,
when he was cut off, not for himself, but for the people,
who by one offering and sacrifice of himself, ended the daily offerings and sacrifices.
And therefore all are to look unto him the one offering and sacrifice once for all.

David saith, '`The sacrifices of God are a broken spirit,
and a broken and contrite heart,`' and these are the sacrifices
'`that God will not despise,`' as in Ps. 51:17. And David said,
'`Let my prayer be set before thee as incense,`' (mark,
as incense,) '`and the lifting up of my hands as the evening sacrifice,`' (mark,
as the evening sacrifice.) Now here you may see,
David saw beyond the outward offerings and sacrifices;
for he desires that his prayer might be as incense,
and his lifting up hands as the evening sacrifice.
Ps. 141:2. And Solomon saith,
'`that the sacrifice of the wicked is an abomination to the Lord;
but the prayers of the upright-hearted are his delight.`' Prov. 15:8.

Here you may see, you that are wicked, your prayers and sacrifices are not accepted.
'`And to do justice and judgment is more acceptable to the Lord
than outward sacrifices.`' Prov. 21:3. So here you may see,
it is not offering sacrifices only with a company of words, nor outward things,
but a practising judgment and justice.

And Christ saith to the outward Jews,
that were in their outward offerings and sacrifices, and their long prayers;
Christ said unto them,
'`I will have mercy and not sacrifice,`' and bid them go learn what that meaneth.
For the Lord said, '`I desire mercy, and not sacrifice,
and the knowledge of God more than burnt-offerings.`' Matt. 9:13.
Hos. 6:6. So here you may see,
mercy and the knowledge of God is beyond outward offerings and sacrifices.

For as the apostle saith, '`Christ hath loved us,
and hath given himself an offering and sacrifice for us to God,
for a sweet smelling savour.`' Eph. 5:2. So you may see Christ
hath given himself an offering and sacrifice for us to God;
and the saints now do not offer up Christ, who hath already offered up himself, (mark,
himself,) but they are to present their bodies a living sacrifice, holy,
acceptable to God, which is their reasonable service.
This the apostle writ to the church of Christ, the Romans,
which same is the duty of all christians.

And the apostle saith to the church of Christ, the Hebrews, '`By him, (namely,
Christ,) let us offer the sacrifice of praise to God continually, that is,
the fruit of our lips, giving thanks unto his name; and do good and communicate,
for with such sacrifices God is well pleased.
For even Christ our passover is sacrificed for us;`' as in 1 Cor. 5:7.

And Peter, in his General Epistle, told the church of Christ,
that they were built '`a spiritual household, a holy royal priesthood,
to offer up spiritual sacrifices, acceptable to God by Jesus Christ,`' (mark,
by Jesus Christ to God.)

Now all the true christians are a royal priesthood, and a spiritual household,
and with the spirit they are to offer up spiritual sacrifices;
these are they that are acceptable to God by Jesus Christ in the new testament,
and new covenant.
So the apostle did not say they should offer up Jesus Christ,
but '`offer sacrifice to God by Jesus Christ;`' for
Christ had offered up himself once for all.

And you may see how the Jews, when they forsook the Lord,
they joined themselves to Baal-Peor, and did eat the sacrifice of the dead,
which was forbidden of the Lord, and provoked him to anger,
that his plague broke out upon them; as in Ps. 106:28-29.

G+++.+++ F.
