== Concerning the antiquity of the people of God called Quakers; their worship; their mother, new and heavenly Jerusalem; their faith, and who is the author and finisher of it; their belief their way, their original; their hope, distinct from the hope of the hypocrite that perishes; their gospel, the true ministers, their leader and teacher, and that which gives them knowledge; their mediator, their overseer, the church of Christ`'s prayer, and in what is their cross, and their baptism. By G. F.

I+++.+++ Concerning the antiquity of our worship.

It is that which Christ set up above sixteen hundred years ago, which,
when he put down the Jews`' worship at the temple at Jerusalem;
and the Samaritans worship at the mountain of Jacob`'s well; saying,
'`The hour cometh and now is, they that worship the Father,
must worship him in the spirit and in the truth.`' And this worship
'`in the spirit and in the truth,`' is above all will worshippers,
and dragon worshippers, and the worshippers of the beast;
for God hath poured out of his spirit upon all flesh,
and grace and truth is come by Jesus;
and this spirit and truth is in the hearts and inward parts of people,
that with this spirit of truth they may know the God of truth;
and in the spirit of truth, serve and worship the God of truth;
which pure truth and holy spirit, the devil, the foul spirit,
and all his worshippers are out of, and cannot come into, for there is no truth in him.
And this is our pure and perfect standing worship,
which Christ the son of God set up above sixteen hundred years ago.

II. Concerning the antiquity of our religion.

Which was set up by Christ in his apostles, above sixteen hundred years ago, who saith,
that '`pure religion and undefiled before God is this:
to visit the widows and the fatherless;
and to keep themselves unspotted from the world.`' And this pure undefiled religion,
which brings to visit the widows and the fatherless, is above all the impure, vain,
defiled religions, that do not bridle people`'s tongues,
nor keep them from the spots of the world;
and their widows and their fatherless go a begging about the streets, and not taken in,
fed, nor clothed, nor visited.
And this is below the pure undefiled christian religion,
that was set up among the primitive christians, in the apostles`' days,
which is our pure undefiled religion.

III.
Concerning the antiquity of our mother, new and heavenly Jerusalem.

She is the same as she was confessed to by the apostles, in the primitive times,
above sixteen hundred years ago, who said, '`Jerusalem,
that is below is in bondage with her children, but Jerusalem that is above is free,
which is the mother of us all;`' which is the mother
of all the true believers in the light,
the life in Christ, who walk in the light of heavenly Jerusalem their mother.
And they that receive Christ, to them he gives power to become the sons of God.
And so are the children of heavenly Jerusalem, '`the bride,
the lamb`'s wife,`' which is free,
as in Gal. 4:25. And the apostle saith to the church of Christ, the Hebrews,
'`Ye are come to heavenly Jerusalem; and to the innumerable company of angels;
and to the assembly and congregation of the first born, which are written in heaven;
and to God the judge of all,
and to the spirits of just men made perfect.`' Heb. 12:22-23.

Now here you may see,
that the saints were come in the apostles`' days to heavenly Jerusalem their mother;
and to an innumerable company of angels, and to the spirits of just men made perfect,
and to the congregation of the first born, written in heaven,
while they were upon the earth.
And this heavenly Jerusalem that is free,
is the true mother of all the true christians now; for as all by nature are born natural,
so all the true believers in Christ are born again; for he that believes, is born of God,
so born spiritually, and such are heavenly Jerusalem`'s children.

An again, John in the Revelations saw this holy and heavenly Jerusalem,
descending out of heaven, from God, prepared as a bride adorned for her husband;
and '`there shall enter into it no unclean thing, nor whatsoever worketh abomination,
or maketh a lie;
but they which are written in the lamb`'s book of
life.`' Rev. 21:2. and Rev. 10:27.

Now here you may see,
here are three witnesses or testimonies that do confirm heavenly Jerusalem,
that is above and free, to be the mother of us all,
that believe in Christ and receive him,
to whom he hath given power to become the sons of God, and children of the light,
(by believing in his light,) and children of the day.
And they of this spiritual birth know heavenly Jerusalem their mother,
and walk in the light of their mother, heavenly Jerusalem,
whose light is the Lord God and the Lamb.
Now this heavenly Jerusalem our mother, comes down from heaven,
that brings forth her free born children; and the power and light is from Christ,
who is from above; through whose power and light they become children of God,
and children of the light, and of heavenly Jerusalem, where there is no night;
and so are nursed up in the arms and bosom of heavenly Jerusalem their mother,
who feeds them with the milk of the word, and they grow by it.

For the Lord saith, '`The law shall go out of Zion,
and the word of the Lord from Jerusalem.`' Micah 4:2.
Is not this heavenly Zion and heavenly Jerusalem?
And that the word shall not depart out of the mouths
of heavenly Jerusalem`'s seed and children;
yea, not out of the mouth of its seed`'s seed, but the word of power, and of patience,
and of wisdom, shall abide in the mouth of its seed`'s seed; namely,
all heavenly Jerusalem,
our mother`'s spiritual children in the new covenant and new testament,
which cannot join to, nor own any mother church below her that is heavenly.
And here is the antiquity of our mother acknowledged,
to be the mother of all true christians in the apostles`' days, and now.
And in our mother heavenly Jerusalem`'s children, is love of loves, and joy of joys;
above all joys and loves below, that will pass away.

IV. Now concerning the antiquity from whence we have our faith,
and who is the author and finisher of it.

The apostle saith to the church of Christ, the Hebrews,
'`Let us run with patience the race that is set before us;
looking unto Jesus the author and finisher of our faith.`' Heb. 12:12. i. 2.

Now here you may see the apostles did not make the saints a faith,
but bid them look unto Jesus, who was the author,
or beginner and finisher of their holy and precious faith;
the mystery of which is held in a pure conscience.
And so Christ doth reveal his faith to his people; and so they grow in faith,
and from faith to faith up unto Christ, the author and finisher of it.
So the apostle did not say to the saints, the church of Christ,
look unto us to make you a faith,
and that they should be the author and finisher of their faith, for them;
but bid them look unto Jesus, the author and finisher of their faith.
And so this was the apostles`' doctrine to the christians in the primitive times,
above sixteen hundred years ago; and this is the doctrine that we have received, and own,
who do look at none below Jesus Christ,
to be the author and finisher of our holy precious faith;
in which faith all God`'s people please him, and have access to him;
which faith is our victory over that which displeases God,
and in which holy faith is our holy unity, and by this precious faith all the just live.
And this is the one, holy, pure, precious faith, that,
purifies the hearts of God`'s people, which Christ is the author and '`finisher of;
in which they have access to the holy God, and serve and please him.
So our holy, catholic, or universal faith,
Christ is the beginner or author and finisher of;
in which holy faith the church of Christ did,
and do build one another up which (as before) Christ the holy one,
is the author and finisher of, and not men.

V+++.+++ Concerning the antiquity of our belief.

Christ, the heavenly man, and second Adam,
doth enlighten every one that comes into the world, with his heavenly spiritual light,
which is the life in him, the word, and by him the word,
all things were made and created.
And Christ saith, '`Believe in the light,
that you may become children of the light.`' And so we believing in the light,
the life in Christ, are become children of the light, and so are grafted into him,
the life, in whom we have the light of life, and so are passed from the death in Adam,
to the life in Christ, the second Adam; and as the apostle saith, '`He that believes,
is born of God, and overcomes the world.`' And these are the true and living members,
or the living stones that make up the spiritual household, the church of Christ,
which he is the holy head of.
And as the apostle saith, '`It is given us to believe;`' so Christ hath given us a light,
which is the life in himself; and saith believe in the light:
so we believe in that which Christ hath given us,
and commandeth and teacheth us to believe in, namely, the light,
which is the life in him, by which we may see him, and know him,
and that we may become children of the light, and of the day of Christ;
and this light shining in our hearts,
it gives us the knowledge of the glory of God in the face of Christ Jesus.
And this is the treasure which we have in our earthen vessels; and after we do believe,
we are sealed with God`'s spirit, and can set to our seal,
having the witness in ourselves, that God is true in all his promises, and prophets,
and types and shadows in the law, concerning his son Christ Jesus, in whom we do believe,
who is our heavenly rock and foundation to build upon in this heavenly divine light.
And all the foundations that men lay below Christ, we cannot build upon;
for we believe in the light, the life in Christ, and are grafted into him.
And Christ saith,
'`He that believeth in me hath eternal life.`' And they that do the work of God,
believe in the son of God that he hath sent; and '`he that believeth shall not perish,
but hath everlasting life.`' And Christ said to Martha, '`He that believeth,
though he were dead, yet shall he live;
and he that liveth and believeth shall never die.`' This
is the true and living belief that Christ hath taught us.
And he hath given us his light to believe in;
which belief is distinct from all false beliefs that men make and teach.

VI. Concerning the antiquity of our way.

Christ Jesus said, '`I am the way, the truth, and the life; no man cometh to the Father,
but by me.`' John 14:6.

So Christ is the new and living way, which God hath consecrated for us,
as in Heb. 8:20. And this new and living way Christ set up himself,
above sixteen hundred years ago, by which we come to God.
And as David said, '`As for God, his way is perfect;
and it is God that girdeth me with strength,
and maketh my way perfect.`' Ps. 18:30. 32.

And again, David saith, '`Wherewith shall a young man cleanse his way?
By taking heed according to thy word.`' Ps. 119:9.
So the word will keep out of defiled ways.

And as Solomon saith, '`The way or path of the just is as the shining light,
which shines more and more unto the perfect day.`' Prov. 4:18.
But the way of the wicked is darkness,
and they know not at what they stumble.`' And that
is the condition of them that hate the light.
The just man`'s way or path, and the way of the just is uprightness;
and the most upright God doth weigh the path of the just. Isaiah 26:7.

And you that have been astray from the light,
have not you heard the word from behind you say, '`This is the way,
walk in it.`' Isaiah 30:21.

And all you that have heard the word Christ, and so turned to him, the light,
and the way, you know the scripture fulfilled.
The old testament was the good old way for the Jews to walk in;
but Christ in the new testament, is the new and living way to God,
to them that believe and walk in him;
for God hath given Christ to be a governor and leader for his people,
and to be his salvation to the ends of the earth.
So Christ, who is our leader, is our counsellor and salvation, and way to God,
and there is no other way to the Father but by him, who hath died for our sins,
and is risen for our justification.

VII.
Concerning the original.

John saith, '`In the beginning was the word, etc.
And all things were made by the word; and without the word was not any thing made,
that was made.`' John 1:9. And the apostles were preachers of the word. 1 Pet. 1:25.
And the apostle said, '`The word is nigh thee,
in thy heart and in thy mouth;
and this is the word of faith which we preach.`' Rom. 10:8. And James saith,
'`Of his own will begat he us, by the word of truth.`' James 1:18.

So God`'s people are begotten by the word of truth, being born again,
not of corruptible seed, but of incorruptible, by the word of God, which lives,
and abides, and endures forever;
and so as new born babes desire the sincere milk of the word, that they may grow thereby. 1 Pet. 2:2.

And John saith, '`That which was from the beginning, which we have heard,
which we have seen with our eyes, and our hands have handled of the word of life;
that declare we unto you, that ye also might have fellowship with us;
and truly our fellowship is with the Father and his son,
Jesus Christ.`' 1 John 1:1-3. And this word is no new commandment; for John saith,
'`I write no new commandment unto you, but an old commandment,
which you had from the beginning.
The old commandment is the word,
which ye have heard from the beginning.`' 1 John 2:7. And by the word of God,
which did abide in the saints, they overcame the wicked one. 1 John 2:14.
'`And John bore record of the word of God,`' Rev. 1:2. and said Christ`'s
name was called the word of God;`' and the word is called the word of grace,
and the word of faith, and the word of wisdom, and the word of power,
and the word of patience;
and this is the word by which all God`'s people are sanctified and made clean;
and by it all things are sanctified to them, and by this word they are reconciled to God,
and this word was before the confusion of Babel, with their many languages,
which the priests and the world called the original.
And Pilate set a superscription in letters of Hebrew, Greek, and Latin, upon Christ,
when they crucified him.
And the beast and the whore, and the false church,
had power over the natural tongues and languages, as in Rev. 13:7. and xvii.
15. But the word of God was before their tongues and languages were.
And natural men with their natural arts and sciences, and tongues,
do not know the things of God; for natural men, in their natural schools,
may learn their natural arts and sciences, and their natural tongues,
and their natural religions, and so to be natural ministers.
But they that hear Christ`'s voice, and learn of him, and are bred up in his school,
are made able ministers of his everlasting word.

VIII.
Concerning the antiquity of our true hope, distinct from the hope of the hypocrite,
that perishes.

'`The mystery which hath been hid from ages and generations,
is now made manifest to the saints, which is Christ in you, the hope of glory,
whom we preach; warning every man, and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus.`' Col. 1:27-28.
'`And every man that hath this hope in him purifies himself,
even as he is pure.`' 1 John 3:3. And we are saved by hope,
as in Rom. 8:24. So that all the saints may know what is the hope of their calling;
for we being saved by hope, are saved by Christ, who is to dwell in our hearts by faith;
for the apostle said, '`The Lord Jesus Christ, who is our hope.`' 1 Tim.
i. And we are to hold fast this hope that is set before us,
which we have as an anchor of the soul, both sure and steadfast;
and it entereth into that which is within the veil,
where the forerunner is for us entered in, even Jesus. Heb. 6:18-20.
And '`blessed be God, even the Father of our Lord Jesus Christ,
which according to his abundant mercy, hath begotten us again unto his lively hope,
by the resurrection of Jesus Christ from the dead, to an inheritance immortal,
and undefiled, and that fadeth not away, reserved in heaven for the saints,
which are kept by the power of God through faith unto salvation.`' 1 Pet. 1:4-5.

Here you may see the saints that are in this true and living hope,
have an inheritance immortal and undefiled, who are kept by the power of God,
through faith unto salvation.

IX. Now concerning the antiquity of our gospel.

The apostle tells the Romans,
that '`the gospel of Christ is the power of God to salvation to every one that believes.
For by the gospel, the righteousness of God is revealed, from faith to faith;
so that the just shall live by his faith.`' Rom. 1:16-18.

And again, the apostle saith,
'`The gospel which hath been preached to every creature under heaven.`' Col. 1:23.
For Christ said unto his disciples,
'`Go ye into all the world and preach the gospel to every creature.`' Mark 16:15.

'`And God will judge the secrets of men`'s hearts by Jesus Christ,
according to my gospel,`' saith the apostle.
He being the heir of it, that is according to the power of God,
which is preached to every creature under heaven.

And the gospel was preached to Abraham, saying,
'`In thy seed shall all nations be blessed.`' And was not this gospel preached
to Abraham four hundred and thirty years before the law of Moses was given forth?
For '`unto Abraham and his seed, was the promise made.
He said not unto seeds, as speaking of many, but unto thy seed, as of one,
which seed is Christ,`' as in Gal. 3:8. 16, 17. So in this seed Christ,
are all nations and families of the earth blessed.
Therefore all nations and families of the earth must come into Christ, the seed,
that bruises the serpent`'s head, if they be blessed,
and then they who are of the seed through faith, are blessed with faithful Abraham.
For the children of the promise are counted for the seed,
as in Rom. 9:8. And therefore all nations and
families of the earth must come into the seed,
if they be blessed; and they that be in the seed, and are baptized into Christ,
have put him on; and there, in Christ, is neither Jew nor Greek, bond nor free,
male nor female, they are all one in Christ, Gal. 3:27-28.
And so are all the sons of God, by faith in Christ.
Now this everlasting gospel and promise was preached to Abraham,
four hundred and thirty years before the law was given to Moses; saying,
'`In thy seed shall all nations and families of the
earth be blessed.`' And was it not preached to Adam,
when God said,
'`The seed of the woman shall bruise the serpent`'s head?`' And when Christ came forth,
he sent his disciples into all nations,
to preach the gospel to every creature under heaven, as before.
And John in the Revelations, who saw the night of apostacy, and Babylon`'s fall,
saw the '`angel fly in the midst of heaven having the everlasting
gospel to preach unto them that dwell on the earth;
and to every nation, and kindred, and tongue, and people; saying with a loud voice,
Fear God, and give glory to him; for the hour of his judgment is come,
and worship him that made heaven and earth, and the sea,
and fountains of water.`' Rev. 14:6-7. So this is the
everlasting gospel which is preached by the holy ghost,
sent down from heaven.
Now many may have the letter of the scripture, and the form of holy men`'s words,
for the Jews had Abraham`'s, and the prophet`'s words,
as the Christians have Christ`'s and the apostles`' words, Matthew, Mark, Luke, and John,
and so may put the letter for the gospel;
but the letter of the scripture declareth what the gospel is.
Outward scriptures or letters may be worn out, but the gospel is everlasting,
which is the thing that the scripture declareth of;
for '`he that preacheth any other gospel,
(the apostle saith,) let him be accursed.`' For the gospel,
which the apostles preached and taught, was not of man,
neither did they receive it of men, but by the revelation of Jesus Christ. Gal. 1:10-9.
And this is the everlasting gospel of life and salvation; saying,
in thy seed shall all nations be blessed.
Now men may be taught the outward letter of the scripture,
and receive that from men in the natural state;
but that which the scripture or letter declareth of, is revealed by Jesus Christ,
(namely,) the everlasting gospel, the seed, in which all nations are blessed.
And for the defence of this gospel were the apostles set in their day; and so have I,
and many others in our day and age; against the letter wise Christians,
as the apostles were against the outward letter wise Jews.
And see what opposition the letter wise made then, and now;
that professed the gospel in words, but did, nor do not come into the seed,
in which all are blessed, and which brings life and immortality to light,
to all them that are in Christ the seed.

X+++.+++ Concerning the antiquity of the true ministers.

Moses, and Aaron, and the prophets, were all sent of God, in the old testament.
And the Lord commanded Moses to take twelve rods, and write every man`'s name,
that were the heads of the house of their fathers, upon the rods;
so one rod forever prince, according to the house of their fathers, even twelve rods.
And Aaron`'s rod was among their rods; and Moses laid their rods before the Lord,
in the tabernacle of witness: and on the morrow, Moses took all the rods,
and Aaron`'s rod; and behold Aaron`'s rod, for the house of Levi, was budded,
and brought forth buds, and blossoms, and ripe almonds;
but the rest of the heads of Israel`'s rods brought forth nothing.
So the Lord chose the house of Levi to serve him, in the outward tabernacle.
Num. 17. And so the Lord chooseth in his new testament and covenant,
whose spiritual rods do bud in the inward tabernacle,
to serve him in the inward tabernacle, to be a holy, royal priesthood,
to offer up spiritual sacrifices to God, by Christ. 1 Pet. 2:5.
9+++.+++ And John, the greatest prophet born of a woman,
was a man sent from God. John 1:6.
Matt. 11:11. And Christ said the living Father sent him,
as in John 6:57. And Christ said, '`As thou didst send me into the world,
so have I sent them into the world,`' (namely,
his disciples,) and the apostles did believe that God had sent Christ,
as in John 17:8. 18.

And Christ called his twelve disciples, and sent them forth to preach,
and gave them power; and said unto them, '`Freely ye have received,
and freely give,`' as in Matt. 10:1 to the end.

There you may see how Christ doth encourage his free ministers,
and likewise in Mark 9. from the first to the sixth.
And Christ said unto his disciples, the harvest was great, and the labourers were few;
wherefore pray the Lord of the harvest that he would send forth labourers into his harvest.
And so you may see Christ here gives them power,
and they were to pray to the Lord of the harvest for labourers,
and not to the high priests and rabbis, and the powers,
for them to send forth their letters to learned doctors, and to have power from them.

And you may read in Matt. 23. how Christ declareth against the false teachers;
and how that the Jews should persecute, crucify,
and scourge such as Christ sends in their synagogues, and from city to city.
So these false teachers always persecuted the true.
Matt. 23 30 to the end.
And you may see in Matt. 22:1 to the 16th,
how Christ sends forth his disciples to call to the marriage.
And when Christ sent forth his seventy disciples, he said,
'`I send you forth as lambs amongst wolves,
without bag or scrip;`' and you may see how he did exhort them,
how they should preach and behave themselves.
Luke 10. from the 1st to the 12th. And the apostle told the Ephesians,
among whom he had been labouring for the space of three years, and preached among them;
and '`he had not ceased to warn every one of them
both night and day with tears,`' and said,
'`I have coveted no man`'s silver, gold, or apparel; for ye know,
that these hands have ministered to my necessities, and to them that were with me.
I have showed you in all things, how that in so labouring, ye ought to support the weak,
and to remember the words of our Lord Jesus, how that he said,
it is a blessed thing to give, rather than to receive.`' Acts 20:31-35.

Here you may see an example of a true minister of Christ, and also in 1 Cor.
ix. from the 1st to the 20th,
how the apostle there strove to keep the gospel without charge, and to make it free;
and how the apostle reproves such that did not labour,
that they might labour and follow the apostles, whom they had for examples,
as in 2 Thess.
iii. who would not be chargeable to them, as from verse 6th to the 13th.

And the apostle said that Christ ascended on high,
and gave gifts unto men for the work of the ministry; some apostles, some prophets,
some evangelists, some pastors, some teachers, for the edifying of the body of Christ,
till we all meet together in the unity of the faith, and the knowledge of the son of God,
unto a perfect man, and unto the measure of the stature of the fulness of Christ;
and so to every one of us is given grace,
according to the measure of the stature of the fulness of Christ.
Eph. 4. from the 1st to the 16th.

Here you may see, they had the gifts from Christ that made them ministers,
and not from schools, and colleges, nor powers.
And Peter saith, '`Let every man as he hath received the gift,
minister the same one to another, as good stewards of the manifold grace of God;
and the elders were to feed the flock of God; not by constraint, but willingly;
not for filthy lucre, but of a willing mind;
not as though you were lords over God`'s heritage,
but that you may be examples to the flock.`' 1 Pet. 4:10. and v. 2, 3.

And in Rom. 10. there you may see how the apostle exhorts them to improve their gifts,
in teaching, and prophesying, and exhorting; and these gifts they had from Christ.

And in 1 Tim.
iii. there you may see how the bishops, deacons, and overseers,
they were not to be given to wine, nor strikers, nor fighters, nor covetous,
nor given to filthy lucre; but should be such as could rule their own houses well,
having their children in subjection.
For, if they could not rule their own houses well,
how should they take care of the church of God?
And likewise, their wives were to be honest, not evil speakers,
but sober and faithful in all things.
And so let these bishops, elders, deacons, and ministers first be proved,
and if they be found blameless, then let them minister, as in 1 Tim. 3:1 to the 13th.

So it seems they were not to minister, if they were not blameless in these things.

And likewise, you may see the qualifications of the elder men, and the women,
that were to be teachers of good things, and teachers of the younger women,
as in Tit. 2. from the 1st to the 6th. And you may see all along in the scriptures,
how Christ and the apostles testified against the covetous prophets, shepherds,
and teachers, that preached for hire, and filthy lucre; and how that the true prophets,
Christ, and the apostles spake forth freely, and did suffer by the hirelings,
and the covetous, that taught for filthy lucre.

And Christ bid his disciples and believers to wait at Jerusalem,
until they were endued with power from on high, and they should receive the holy ghost,
and then they should be witnesses of Christ, both in Jerusalem, and in all Judea,
and Samaria, and unto the utmost parts of the earth, as in Acts 1:4-9.

Now here you may see the primitive ordination of Christ`'s ministers;
they had their gifts from Christ, and were endued with power from on high,
and they received the holy ghost,
and every one was to minister as they had received the gift from Christ.
So these were not endued with power from below, nor from the high priests, nor kings,
nor emperors, nor men, nor schools, nor colleges;
but they were endued with power from on high,
and their gifts they had from Christ that ascended on high, above all principalities,
powers, thrones, and dominions.
So here is the antiquity, and first ordination of Christ`'s ministers, and teachers,
according to the scripture which we own.

And God, who poured out of his spirit upon all flesh, as in Joel 2. Acts 2. By which,
sons, daughters, handmaids, and servants should prophesy,
and have their spiritual visions, and old men have their spiritual dreams.
And this now is witnessed in the days of the new covenant, and the gospel day of Christ;
but they that rebel against the spirit of God, and vex it, and grieve it,
and make a mock at it; they say, prophecy, and revelation, and visions are ceased.
But the apostle saith, no man knows the things of God, but by the spirit of God,
and the spirit of God doth reveal them;
and the natural man perceiveth not the things of the spirit of God,
they are foolishness to him; neither can he know them,
because they are spiritually discerned. 1 Cor. 2:11-14.

XI. Concerning the antiquity of our leader, and that which gives us knowledge.

The Lord said, speaking of Christ,
in Isa. 55:3-4. '`I will make an everlasting covenant; and behold,
I will give him for a witness, and a leader, and a commander to the people;
and he shall feed his flock like a shepherd, and he shall gather his lambs in his arm,
and carry them in his bosom,
and gently lead those that are with young.`' Isa. 40:11.
'`And I will bring the blind by a way that they know not,
and I will lead them into paths that they have not known.
I will make darkness light before them, and crooked things straight.
These things will I do unto them, and not forsake them.`' Isa. 42:16.

And Christ said, he is the good shepherd that lays down his life for his sheep;
and he calleth his sheep by name, and leadeth them, and goes before them;
and his sheep follow him, for they know his voice.
John 10.

And Christ said, he would send his believers the comforter, the spirit of truth,
which should proceed from the Father, which should guide them,
and lead them into all truth.
John 15. and xvi.
chap.
So this was, and is the ministers, and teachers, and disciples, and believers in Christ,
their leader and guider into all truth.
For the apostle saith, that no prophecy of scripture came by the will of man,
neither is it of any private interpretation;
but holy men of God spake forth the scripture, as they were moved by the holy ghost.
And so it is the holy ghost, the comforter, the spirit of truth,
that leads Christ`'s believers into all truth, and into all the truth of the scriptures. 2 Pet. 1:21.

And John saith, '`He that sitteth on the throne shall dwell among them,
and they shall hunger and thirst no more.
For the lamb which is in the midst of the throne shall feed them,
and shall lead them to living fountains of water,
and God shall wipe away all tears from their eyes; they are before the throne of God,
and serve him night and day in his temple.`' Rev. 6:9 to the end.

That which gave the church of Christ knowledge in the apostles`' days, gives us,
the church of Christ, knowledge in our days.
The apostle saith, '`God who commanded light to shine out of darkness,
hath shined in our hearts, (mark,
in our hearts,) to give us the light of the knowledge of the glory of God,
in the face of Jesus Christ; and we have this treasure in earthen vessels,
that the excellency of the power may be of God,
and not of us.`' So here we have this light from God and Christ,
and it shines in our hearts by God`'s command,
to give us the knowledge of his glory in the face of Christ his son;
and God hath the glory and honour of this light,
which gives us the knowledge of Christ our saviour,
who is the treasure of wisdom and knowledge; which light of God and Christ,
gives us the knowledge of the glory of God, in the face of Christ,
(as before,) and without this light we have not the knowledge of the glory of God,
in the face of Jesus Christ; as in 2 Cor. 4:6-7.

XII.
Now concerning the antiquity of our teacher in the new covenant.

Christ saith, '`Is it not written in the prophets, ye shall be all taught of God?
Every man therefore that hath heard and learned of the Father, cometh unto me;
and no man cometh unto me, except the Father which hath sent me,
draw him.`' John 6:44-45. '`All thy children shall be taught of the Lord;
and great shall be the peace of thy children,
in righteousness shall they be established,`' etc. Isa. 54:13.

And the Lord said in Jeremiah 31:31-34, '`Behold the day is coming, saith the Lord,
that I will make a new covenant with the house of Israel, and the house of Judah;
not according to the old covenant, that I made with their fathers:
but this is the covenant, I will put my law in their inward parts,
and write it in their hearts; and I will be their God, and they shall be my people.
And they shall not teach every man his neighbour, and every man his brother, saying,
know the Lord;
for all shall know me from the least to the greatest.`'
So the old covenant and its priests,
whose lips were to preserve people`'s knowledge, they cease,
and there is no need of them in the new covenant; for all shall know God,
by the law he puts in their minds, and writes in their hearts.
Hebrews 7:8 to the end.

And this new covenant is an everlasting covenant, and lasts forever in all ages.
And all God`'s people know God and Christ, by the law he puts in their minds,
and writes in their hearts, that they need not give priests tithes and maintainance,
to teach people to know the Lord.

The apostle saith to the church of Christ, the Thessalonians, 1 Thess. 4:9.
'`As touching brotherly love, you need not that I write unto you,
for ye yourselves are taught of God to love one another.`'
And John in his General Epistle to the church of Christ,
directs them to their teacher, the anointing within them; and saith,
'`Let that therefore abide in you, which you have heard from the beginning;
if that which you have heard from the beginning shall remain in you,
ye also shall continue in the son, and in the Father.
And this is the promise that he hath promised us, even eternal life.
And these things have I written unto you, concerning them that seduce you;
but ye have an anointing that you have received from him, that abideth in you,
and you need not that any man teach you,
but as the same anointing teaches you of all things, and is truth, and is no lie;
and even as it hath taught you,
ye shall abide in him.`' This John wrote to the church of Christ,
that had received the truth, and were established in it.

Now this anointing in them, which they have received of God,
was the teacher of his people then, and it is the teacher of God`'s people,
the church of Christ now.
And the priests or teachers, that would seduce from this anointing`'s teaching within,
they would seduce them from continuing in the Father, and in the son,
and so from the promise of eternal life, as in 1 John 2:21; 24-27.

And the apostle saith to Titus, '`The grace of God, which brings salvation,
hath appeared unto all men; teaching us, that denying ungodliness and worldly lusts,
we should live soberly, righteously, and godly,
in this present world.`' Tit. 2:11-12.

Here you may see what was the church of Christ`'s teacher, the law in the heart,
the anointing within, the grace of God in the heart, which brings salvation;
it hath appeared unto all men, to teach them, and bring their salvation,
if they do not walk despitefully against the spirit of grace,
and turn it into wantonness.
And the Lord said unto Paul, '`My grace is sufficient,
my strength is made perfect in weakness.`' 2 Cor. 12:10-9.

And here is the antiquity of our teacher,
which was set up above sixteen hundred years ago; by which we know God,
and continue in the Father and in the son, and have eternal life;
which grace is sufficient to establish our hearts, and bring our salvation.
So that we have no need to give the priests and hirelings tithes and money to teach us;
for we are come to the waters of life, without money and without price,
which satisfies our thirsty souls. Isa. 4:1-2.
and John 7:37. So that we do praise God, and sing hallelujah,
through Jesus Christ.

XIII.
Concerning the antiquity of our mediator.

The apostle saith, '`The law served, which was added because of transgression,
till the seed should come, to whom the promise was made.`' Gal. 3:19.

And the apostle said, '`God would have all men to be saved,
and come to the knowledge of the truth;
and Christ gave himself a ransom for all to be testified of in due time.
And there is one God, and one mediator betwixt God and man,
even the man Christ Jesus.`' 1 Tim. 2:4-6.

Now this is the one mediator, which we own betwixt God and man;
God having poured his spirit upon all flesh, men and women,
that with the spirit of God they might know Christ,
the one mediator betwixt them and God.

So here you may see, the apostle did not set up many mediators between God and man,
but one mediator, Christ Jesus the son of God.

XIV.
Concerning the antiquity of overseers.

The apostle saith unto the elders, '`and to all the flock,
over which the holy ghost hath made you overseers,`' etc. Acts 20:28.

Here you may see, the overseers of the church of Christ were not made by men;
but the holy ghost made them overseers.
So they had the spiritual eye to watch one over another.

And Christ when he sent forth his ministers, told them,
'`that they should be brought before magistrates and powers.`' And said unto them,
'`Take ye no thought how or what things ye shall answer, or what ye shall say;
for the holy ghost shall teach you in the same hour,
what ye ought to say;`' as in Luke 21:14-15.

So here they were to wait in the holy ghost, that led them into all truth,
and not to take thought nor follow their own thoughts, but to trust to the holy ghost,
their leader and comforter.

XV. Concerning the antiquity of the church of Christ`'s prayer, and in what.

The apostle saith, '`The spirit helps our infirmities;
we know not what we should pray for as we ought,
but the spirit itself maketh intercession for us,
with sighs and groans that cannot be uttered.
And he that searcheth the heart, knows what is the mind of the spirit,
because he maketh intercession for the saints,
according to the will of God.`' Romans 8:26-27. And again the apostle saith,
'`I will pray with the spirit, and I will pray with the understanding;
I will sing with the spirit,
and I will sing with the understanding also.`' 1 Cor. 14:15. And again,
the apostle Jude saith, '`Ye beloved, build up yourselves in the most holy faith,
praying in the holy ghost.`' Jude 20.

Here you may see it is the spirit that God poureth upon all flesh, and the holy ghost,
that the church of Christ, and all people are to sing and pray in,
and serve and worship God in, and not to grieve the spirit of God, nor vex it,
nor quench it, nor rebel against it.

After that God had made man and woman in his own image and likeness, and blessed them,
and put them in paradise; and gave them a command to eat of every tree,
except the tree of knowledge of good and evil; for in the day they did eat,
they should die.
But the serpent, the lying spirit, told them they should not die, if they did eat;
and so they followed the serpent`'s teaching,
and disobeyed God`'s. And therefore God drove them out of paradise into the earth.

Here you may see how soon a lying false teacher arose, and sowed his evil seed.
And Adam and Eve for disobeying God, were driven out of paradise,
and lost the image of God, and their blessed state.

And the old world, which grieved the Lord and his spirit, and corrupted the earth,
and filled it with violence; the Lord said,
'`his spirit should not always strive with man.`' So that
God brought a flood upon the old ungodly world,
and destroyed them; but saved Noah, and his family, a preacher of righteousness.

And after, in the new world, Nimrod got up and built Babel,
but the Lord confounded him and his followers.
And after, Sodom and Gomorrah run into ungodliness, and unlawful deeds;
and God turned them into ashes.
And after the Lord, by his mighty power, had brought the children of Israel out of Egypt,
how soon did the serpent sow his wicked seed in them?
And God gave them his law, and his good spirit to instruct them,
as in Neh. 9:20. but they rebelled against his spirit,
and turned their backs against his good law.
And for their disobedience,
how often did the Lord suffer them to be carried into captivity!
And at last the ten tribes, for their disobedience, by Salmonazer, the king of Assyria,
were carried away out of Samaria, and the land of Canaan, into captivity,
for their disobeying and rebelling against the Lord.
And after, the two tribes were carried away by the king of Babylon from Jerusalem,
and the land of Canaan, which was called the glory of all lands.
And when the Lord Jesus Christ came, the Jews stopped their ears,
and closed their eyes to him and his doctrine; and cried, Away with him, crucify him,
crucify him.
And Christ told them, their city should be compassed with armies,
and their temple thrown down, and they should be scattered over all nations;
which came to pass by Titus the Roman, who destroyed Jerusalem, and the temple,
and scattered the Jews, that they could never build Jerusalem nor the temple since.
And thus they were driven out of their own land, for disobeying God,
and forsaking his law and spirit, like Adam and Eve,
who were driven out of paradise,for disobeying God,
and following the serpent`'s teaching, and forsaking of God`'s.

And after Christ sent his disciples to preach the
gospel of life and salvation unto all nations,
and to every creature under heaven, the devil,
he sowed his wicked seed and tares in the hearts of people when they slept,
and grew careless of God`'s truth; and the devil begat many antichrists, false prophets,
false teachers, false apostles, seducers, and deceivers,
which got the form of godliness and the outward form of christianity,
and led many after them, and so set up a false church, the whore, mystery Babylon,
mother of harlots; who rid upon the beast in the dragon`'s power, and made the people,
nations, and tongues like waters; and in this whore and false church,
is found the blood of the prophets and martyrs of Jesus.
For John saith,
'`she was drunk with the blood of the prophets and martyrs of Jesus;`' that is,
with heavenly Jerusalem`'s children`'s blood.
For heavenly Jerusalem, the bride, the Lamb`'s wife,
is the mother of all the true christians that believe in the light,
and are children of the light, and receive Christ,
who gives them power to become the sons of God.
So this whore, or false church, went from the true mother, heavenly Jerusalem,
and from Christ the true husband; and became the mother of harlots, the whore,
that drank the blood of the martyrs,
and got upon the persecuting beast in the dragon`'s power.
But the judgment of the great whore is come, and the beast, dragon, and false prophet,
John saw cast into the lake of fire,
and the everlasting gospel preached again to all nations, tongues, and people,
to settle them; and all that receive the everlasting gospel,
the seed in which all nations are blessed, are heavenly Jerusalem`'s children,
and children of the seed,
and are children and heirs of the everlasting kingdom of God and Christ,
that stands in power and righteousness, and joy, and peace in the holy ghost,
and are of the new creation in Christ Jesus.
And this seed shall be as the sand of the sea, and the dust of the earth,
and the stars of the heaven, that cannot be numbered.
Christ saw his seed, which are the children of his kingdom.
'`He that hath an ear, let him hear.`'

'`Jesus Christ, the same yesterday, and today,
and forever.`' Heb. 13:8. who exercises his prophetical office,
as he is a heavenly prophet; who open people`'s eyes,
to see spiritual and heavenly things; and Christ their saviour,
who redeems and purchases them with his own life, his blood.
And so Christ the prophet is to be heard in all things by his children,
who enlightens every one that cometh into the world;
that in the light they might see him, and hear him.
And he openeth the book of conscience to them, and the book of life;
that in it they may read and see their names written there;
which book no man can open but Christ the lamb.

And Christ exercises his office as a heavenly bishop,
who raises up his children out of the death in Adam,
and makes them to sit together in the heavenly places in Christ Jesus;
and he is a bishop to oversee them,
that they do not go out of the heavenly places in him.

And Christ exercises his office as a heavenly shepherd among his spiritual sheep,
and feeds them with his bread from heaven, and water of life in his heavenly pasture,
and his sheep know his voice, and follow him.

And Christ exercises his office, as he is the King of kings, and Lord of lords;
who rules in the hearts of his people by faith, that they all may be one, saith Christ;
as thou Father art in me, and I in thee, that they also may be one in us.
And the glory that thou gavest me, I have given them, that they may be one,
even as we are one; I in them, and thou in me, that they may be made perfect in one. John 17:21-23.

So Christ, the heavenly king and Lord, rules, orders,
and governs in the hearts and souls of his children,
who is the bishop and chief shepherd of the soul to oversee and feed his sheep.

[.blurb]
=== Concerning our Baptism.

The apostle saith, '`There is one baptism.`' Eph. 4:5. And '`by one spirit,
we are all baptized into one body; whether we be Jews or Gentiles;
whether we be bond or free,
and have been all made to drink into one spirit.`' So this is the one spiritual baptism,
which was set up above sixteen hundred years ago.

And you may see more of the distinction between John`'s-baptism and Christ`'s,
in my book, entitled, '`A distinction between the two baptisms,
and the two suppers of Christ.`'

How that John`'s baptism, with the elements of water did decrease, and Christ`'s baptism,
with fire and the holy ghost doth increase; who thoroughly purges his floor,
and burns up the chaff with unquenchable fire;
and how Christ gathereth the wheat into his garner and this is our baptism,
and baptizer.

G+++.+++ F.

Edmondton, the 2d month, 1688.

=== Postscript.--__The antiquity of our Cross.__

The apostle saith to the church of Christ,
that '`the preaching of the cross is to them that perish, foolishness;
but unto us that are saved, it is the power of God.`' 1 Cor. 1:18. And such as were,
and are enemies to the cross of Christ, were, and are enemies to the power of God.
So all your stone, wooden, brass, silver, or gold crosses you have invented,
and set up since the apostles`' days, are not the cross of Christ, the power of God;
but the works of your own hands.
And the apostle saith, '`God forbid that I should glory,
save in the cross of our Lord Jesus Christ, by whom the world was crucified unto me,
and I unto the world.`' Gal. 6:14. So it was the power of God, the cross of Christ,
the apostle gloried in, by whom the world was crucified to him, and he unto the world;
and this is our cross which we glory in,
etc. which was set up above sixteen hundred years ago.
And it is not like that it was a cross made of wood, stone, iron, brass, silver or gold,
that the apostle, or the church of Christ gloried in; or that such outward, temporal,
and worldly crosses, as men make and invent, should crucify people to the world.
That which crucifies people to the world, and the world to them, is the cross of Christ,
the power of God, which power of God, all are to bow down to,
and their faith is to stand in it; and they are foolish and dark,
that think a cross of stone, wood, iron, silver, or gold, which man hath made,
is the cross of Christ, the power of God; and to bow to such worldly temporal things,
and call them the cross of Christ, is contrary to the scriptures,
that the apostles taught to the church of Christ in their days;
and this was the church of Christ`'s cross in the apostles`' days,
and is the church of Christ`'s now.
But they could not, nor can we, bow to any temporal outward worldly cross,
that men have made with their hands, and bow down to them.
For such as do worship the works of their own hands, are enemies to the cross of Christ,
the power of God.

G+++.+++ F.
