[#ch41.style-blurb, short="A Salutation to All that are Seeking the Kingdom of God"]
== A spiritual or Heavenly salutation to all the tender-hearted in Christendom, that are seeking the kingdom of God, and the righteousness thereof; which I desire and entreat them to read over, in the love of God, in which they are sent to them, from him that desires the good of all mankind here, and their eternal happiness hereafter. By G. F.

To all the tender-hearted in Christendom,
whose faces are turned towards heavenly Jerusalem,
and whose minds are turned and drawn by the spirit of God to Christ,
who is the new and living way to God, and the one mediator between God and man;
who enlighteneth every one that cometh into the world, with his heavenly divine light,
which is the life in Christ the word, by whom all things were made and created.
Christ saith, '`Believe in the light,
that ye may become children of the light.`' So Christ who is not of the world,
but from above, hath given us his light to believe in, and to walk in,
that we may have the light of life; and he that believeth is a child of light,
and born of God, and overcomes the world; and passes from the death that came by Adam,
and is engrafted into Christ the life, the second Adam,
and so are living stones or members of him the living head.
And the children of this light, that walk in this light,
have fellowship with the son and the Father, and one with another;
and all christendom that walk not in the light that Christ hath given you,
are not in this heavenly divine fellowship.
But this prophecy we do witness fulfilled and fulfilling concerning Christ.
God said, '`I will give him for a covenant of the people, and a light to the Gentiles,
and he shall be my salvation to the ends of the earth.`' Isa.
49:6. 8. So that they that come to know their salvation,
and into covenant with God, they must come into the light of Christ,
which giveth the light of the knowledge of the glory of God in the face of Christ Jesus,
which light shines in their hearts, the heavenly treasure in the earthen vessels;
and if all that is called Christendom, had believed in the light, the life in Christ,
which Christ giveth, and teacheth to believe in that which he giveth them,
then had they been all children of the light, and of the day of Christ,
in unity and fellowship in the light,
and then they had not made so many faiths and beliefs
which they have destroyed one another about.
And if all Christendom had observed the apostle`'s doctrine to the church of Christ,
who exhorted them to '`look to Jesus the author and finisher of
their faith,`' then they would not have made so many faiths,
about which they have persecuted one another.
Whereas no manner of men below, can make a catholic divine faith; for I say,
that Christ Jesus is the beginner and finisher of our holy, divine, precious,
catholic or universal faith, which he the Holy One, doth reveal from faith to faith.
And the mystery of this holy faith is held in a pure conscience,
and not in an impure one; and it purifies the heart,
and gives victory over that which displeases God, and separates from God;
in which holy faith, which we have from the Holy One,
we please the holy God which gives us the victory over that
which displeases him and separates from him,
and have access to him.
In this holy divine faith is our unity; so Christ has the honour,
who is the author of our faith, and finisher of it, and likewise gives us his light,
the life in himself.
And happy had all christendom been, had they kept to the apostle`'s doctrine,
to the church of Christ, who said, '`The grace of God that bringeth salvation,
hath appeared unto all men, and teacheth us, (namely, christians,
then and now,) to live godly, righteously, and soberly,
and deny unrighteousness and worldly lusts.`' Now I say,
happy had all christians been since the apostles`' days,
if they had kept to this grace of God their teacher,
which would have brought their salvation,
and would have brought them into favour with God.
If they had, then there would not have been so many itching ears,
and have set up so many schools and colleges to make teachers,
which brings Christendom into confusion one against another.
Some may say, '`Is this grace sufficient?`' God said to Paul, it was sufficient,
when he was in his trials and temptations; and thousands can witness,
that the grace of God is sufficient, and doth teach them what to deny, and how to live,
and doth bring their salvation.
For as the law came by Moses, in the old testament, and the Jews were to live under it;
so grace and truth is come by Jesus in the new testament,
and this grace and truth is in the hearts of God`'s people,
and they are under grace`'s teaching, and in the covenant of grace.
For Christ by the grace of God tasted death for every man,
that they may all come out of the death in Adam, to the light and life in him,
by his light, grace, truth, and faith in their hearts, that he is the author of;
for there is a prophecy in Joel,
'`that God would pour out his spirit upon all flesh,`' which
the apostles in Acts 2. show the fulfilling of to the Jews.
And now what is the matter that all the sons, daughters, servants, handmaids,
and old men in christendom, have not their heavenly prophecies, visions, and dreams?
Is it not because they have erred from the spirit of God, and vex, quench, and grieve it,
that he hath poured upon them, and become like the Jews, to whom God gave his spirit,
but they rebelled against it?
Therefore, is not all christendom on heaps one against another, out of fellowship?
Therefore the means by which all christendom,
and all people are to come into unity and fellowship in the spirit, is,
that they must come all into the spirit that God hath poured upon them,
by which spirit they must be circumcised,
and have the body of sin and death cut off which they came into by transgression in Adam,
who had none before he fell; and they must be baptized with the spirit,
to plunge down sin by this spirit.
I say, all must be baptized into one body, and so all to drink into one spirit;
this spirit of God brings all into fellowship and unity,
for the '`spirit of God is the bond of peace,`' and in it is the profiting;
and it openeth the heavenly prophecies, visions, and dreams to God`'s people now,
as it did in the apostles`' days.
Christ Jesus set up a worship above sixteen hundred years ago,
in the spirit and in the truth, when he put down the Jews`' worship at Jerusalem,
and the Samaritans`' at Jacob`'s well, and said, '`The hour cometh, and now is,
that they that worship the Father, must worship him in spirit and in truth,
for such he seeketh to worship him.`' And therefore all
must come to the spirit of God and his truth in their hearts,
by which truth and spirit in their hearts, they must know the God of truth,
an infinite spirit, and in his truth and in his spirit,
to worship and serve the God of truth.
And if all christendom had kept to the truth and spirit in their hearts,
they had kept to the worship that Christ, the Lord from heaven has set up,
(for none can set up a better than he,) and then they had not set up so many worships,
and persecuted one another about them.
But all people must return to the spirit of God and the truth in their hearts,
if they will serve and worship God their creator;
for God is come to teach his people himself, by his son; for as the apostle saith,
'`God at sundry times and in divers manners, spake to the fathers by the prophets,
but now in these last days God hath spoken to us
by his son;`' who bruises the serpent`'s head,
who hath been the head of all false speakers and false religions, churches, ways,
and worships.
But God is the speaker now to his people by his son,
who was the speaker to Adam in paradise; but when Adam forsook God`'s teaching,
and followed the serpent`'s, he lost his happiness; so have the Jews and the christians.
Therefore all must return by the spirit, light, grace, and truth of Jesus,
to Christ Jesus the great prophet, shepherd, bishop, leader, and counsellor,
that they may hear God speak to them by his son.
'`And he that hath the son hath life,
and he that hath not the son hath not life,`' though
he may make a profession of all the scriptures.
And none can receive the son, but by the light, grace, and truth that comes from him,
in their hearts.
Why are not all christendom the sons and daughters of God,
which make a profession of Christ?
Is it not because they do not receive Christ, in his grace and truth in their hearts,
which comes from him?
For Adam and Eve, by eating of that which God forbid,
brought death on them and their posterity that have sinned. Rom. 5:12.
And now Christ the second Adam, saith, that he is '`the bread from heaven,
and except they eat this bread from heaven, etc. that he gives,
they have not life in him.`' So by eating came death, and by eating comes life again;
it is not by talking.
And he gives his bread from heaven now, for he is the heavenly bread, rock,
and foundation; Christ the same today as yesterday, and so forever, to all his people;
who was dead, and is alive again, and lives forevermore, and reigns in his people.
And now in this gospel day of Christ, the new covenant,
God writes his law in the hearts of his people, and puts it in their minds,
that all should know him from the greatest to the least;
and none need say to his brother, know the Lord,
which thousands do witness this law of love, faith, and life,
that all may read what God puts in their minds, and writes in their hearts;
and such are heavenly Jerusalem`'s children, who is the mother of them all.
And no mother can they own below the heavenly Jerusalem,
no more than the christians did in the primitive times;
and such are the '`church of the first born written in heaven,`' clothed with the sun,
and the moon under her feet; all changeable churches, ways, worships,
religions and teachers; all which change as changeable things, for the moon changes,
but the sun doth not change, but clothes his living members, who is over his house,
the royal priesthood offering up spiritual sacrifices to God,
(not carnal,) by Jesus Christ.

And when Christ sent his disciples to preach the gospel,
it was not with the penalty of prisons, gallows, fire,
and spoiling of the goods of them that would not believe and receive them.
And therefore, it is time for all that profess christianity,
to put up the carnal sword concerning religion, and obey Christ`'s command,
who said he came not to destroy men`'s lives, but to save them;
and therefore love God and Christ, and one another, and enemies,
for love and charity is the most excellent way,
above all tinkling cymbals and sounding brass; for they that dwell in love, dwell in God.

=== Postscript

And all you teachers that make a scoff and a mock
at the motion or moving of the spirit of God;
you had never had the holy scriptures which you make a trade of,
had not the holy men of God spoken them forth as
they were moved by the holy spirit of God;
and this shows that you are erred from the holy spirit of God, that the apostles were in,
and the moving of it, and fellowship in it, which proceedeth from the Father and the son.
And as the apostle said to the church of Christ, '`That I may know him,
and the power of his resurrection, and the fellowship of his sufferings,
being made conformable unto his death.`' Phil. 3:10,
This is the right knowledge of Christ, and the true conformity.

And they that are conformable to Christ, who saith, he is from above,
and not of this world, such are not conformable to this world.

And now all you that go under the name of christians,
'`let every one that nameth the name of Christ depart from iniquity.`' 2 Tim.
ii.19. '`And if any man have not the spirit of Christ he is none
of his.`' Rom. 8:9. And the apostle tells the church of Christ,
that '`no man can say that Jesus is the Lord,
but by the holy ghost.`' 1 Cor. 12:3. And the
holy ghost proceedeth from the Father and the son. John 15:26.
And again the apostle saith to the Corinthians,
'`Examine yourselves whether you be in the faith, prove your own selves;
know ye not your own selves, how that Jesus Christ is in you,
except you be reprobates.`' 2 Cor. 13:5. And again the apostle saith to the Romans,
'`The word is nigh thee, even in thy mouth, and in thy heart;
and this is the word of faith which we preach.`' Rom. 10:8.
And again the apostle saith,
'`The mystery which hath been from ages and generations,
but now is manifest unto the saints;
to whom God would make known what is the riches of
the glory of this mystery among the Gentiles,
which is Christ in you, the hope of glory, whom we preach, warning every man,
and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus.`' Col. 1:26-28.

Now, let all that are called christians consider these scriptures before mentioned.
Have you the holy ghost and spirit of Christ?
If not, how are you Christ`'s and can call him Lord?
Is Christ in you, and the word of faith in your hearts and mouths to obey it,
and do it Oh! mind the hidden man in the heart, and truth in the inward parts,
which is with the Lord of a great price; and have salt in yourselves to savour withal,
and oil in your own lamps, that you may not be like the foolish virgins;
and improve your own talents, and be not like the slothful servant,
for the manifestation of the spirit of God is given to every man to profit withal;
and be not only sayers or hearers of the word of God, but doers,
lest you deceive your own souls.
'`For pure religion and undefiled before God the Father is this, to visit the fatherless,
and the widow in their affliction,
and to keep himself unspotted from the world.`' All that
profess christianity must come to this pure religion,
that will keep them from the world`'s spots;
and therefore this religion is above all the world`'s religions and spots,
and keeps in the pure holy tenderness and exercise to visit the widows and fatherless.
So God Almighty preserve all that really profess christianity in it.
Amen.

And the apostle said to the true christians, '`Ye are the temple of the living God,
as God hath said, I will dwell in them, and walk in them, and I will be their God,
and they shall be my people.`' And again the apostle saith,
'`Know ye not that your bodies are the temples of the holy ghost which is in you,
which ye have of God,`' 2 Cor vi, 16,
All christians that profess christianity should come to this knowledge,
that their bodies are the temples of God.
In the old testament the Jews had an outward temple,
but Stephen saith in the new testament,
'`The most high dwells not in temples made with hands.`' Acts 6:47-49, etc.
But as before, God hath said, '`I will dwell in them, and walk in them,
and I will be their God,
and they shall be my people;`' and their bodies are
the temples of the Lord and his holy ghost,
and all that profess christianity should know this.
And again the apostle saith, '`Know ye not that ye are the temple of God,
and that the spirit of God dwelleth in you?
And if any man defile the temple of God, him shall God destroy,
for the temple of God is holy, which temple ye are.`' 1 Cor. 3:16-17.

Now, all that profess christianity, ought to know the spirit of God to dwell in them,
and their bodies to be the temple of God, and have a care of defiling it,
lest God destroy them; for God is holy, and he would have his people to be holy.

And Christ told the Pharisees, which were great outward professors of the old testament,
that the kingdom of God comes not by observations, etc.
'`Neither shall they say, Lo here, or lo there,
for behold the kingdom of God is within you.`' Luke 17:20-21.

Now all you that profess yourselves christians,
have you found the kingdom of God within you?
Christ saith the kingdom of heaven is like unto leaven,
which a woman hid in three measures of meal, till the whole was leavened;
and again Christ saith,
'`The kingdom of heaven is like a grain of mustard seed.`'
You that profess christianity have you found this kingdom,
and the pearl hid in your field?
Come light your candles and sweep your house,
that you may find the heavenly treasure in your earthen vessels,
who have been looking without for it;
and that you may know the leaven of the kingdom to leaven your souls, hearts, and minds,
etc. into one heavenly lump, as you may read,
Matt. 13. and Luke 10 v. And the apostle saith, '`The things of God knows no man,
but the spirit of God.
Now we have received not the spirit of the world, but the spirit which is of God,
that we might know the things that are freely given us of God.`' 1 Cor. 2:11-12.
So all that profess themselves christians,
they must come to the spirit of God in them, if that they come to know God and Christ,
and the things of God which he freely gives unto them, without money, and without price.

And Isaiah saith, Oh! every one that thirsteth come to the waters,
and he that hath no money: come ye, etc. and ye may have milk and wine without money,
and without price.
Wherefore do ye spend your money for that which is not bread,
and your labour for that which satisfies not?
Hearken diligently unto me.
and eat that which is good, and let your soul delight itself in fatness.
Incline your ears and come unto me; hear,
and your souls shall live.`' Isa. 4:1-2. John 7:37-38.

Now is it not time for all Christians to hearken unto the Lord by his spirit,
and come unto his free waters of life, that their souls may live?
'`And the spirit and the bride say, come.
And let him that heareth, say, come.
And whosoever will,
let him take the water of life freely.`' Rev. 22:17.
Here are the free callers to the free water of life,
without money, and without price.
And the Lord saith, '`Look unto me, and be ye saved all the ends of the earth,
for I am God,
and there is none else.`' Isa. 45:22. Now God
having poured his spirit upon all flesh,
that with his spirit they might all look unto the Lord Jesus Christ,
and see their salvation.^
footnote:[Ex. 14 13, 2 Chron. 20:17.]
And again the Lord saith,
'`All the ends of the earth shall see the salvation
of God:`' and that must be by his spirit;
for the Lord saith, '`My righteousness shall be forever,
and my salvation from generation to generation.`' Isaiah 51:8. and 52:10.
'`Your strength is to sit still,`' (viz.) in the spirit and power of God. Isa. 30:7.
They that wait upon the Lord shall renew their strength;
they shall mount up with wings as eagles; they shall run and not be weary;
they shall walk and not faint.
Now this is the comfort of all them that wait upon the Lord,
whose '`strength is to sit still,`' or to stand still and see the Lord their salvation.
'`And all the children of the Lord shall be taught of the Lord,
and great shall be the peace of his children,
and in righteousness shall they be established,`' etc. Isaiah 54:13.
John 6:45. And the many weapons
that are formed against them shall not prosper,
and every tongue that shall rise up against them in judgment,
God`'s children shall condemn, that are taught of him;
and we know many weapons have been formed against us,
and many tongues have risen up in judgment against us that are taught of God,
but God hath restrained the weapons,
and given power to his children to condemn their false judgments, and evil tongues.

[.blurb]
=== Now concerning Prayer and Singing.

The apostle said, '`I will pray with the spirit, and pray with the understanding also.
I will sing with the spirit,
and sing with the understanding also.`' And the apostle Jude exhorts the church of Christ,
'`to pray in the holy ghost.`' Jude 20. and 1 Cor.
14:15. So he did not give them books to pray by;
to pray with the spirit, and to pray with the holy ghost, is not to pray with books.
The apostle saith, '`The spirit helps our infirmities,
for we know not what we should pray for, as we ought,
but the spirit itself makes intercession for us with groans that cannot be uttered;
and he that searcheth the heart knows what is the mind of the spirit;
because he maketh intercession for the saints according
to the will of God.`' Rom. 8:26-27. So my desire is,
that all may come to this holy ghost, or holy spirit, in their hearts,
in which they pray to God, and for one another, and for all men,
and praise God for his mercies which endure forever.

The apostle said, '`God hath revealed his things unto us by his spirit,
for the spirit searcheth all things, yea,
the deep things of God.`' 1 Cor. 2:10. And again the apostle saith,
'`The righteousness of God is revealed from faith to faith.`' Rom. 1:17.
And again the apostle saith,
'`The gospel which was preached by me is not after man.
For I neither received it of man,
neither was I taught it but by the revelation of Jesus Christ.`'
Now can any preach the righteousness of God,
and the faith of Christ, and the deep things of God and the gospel of Christ,
except these things be revealed to them by the spirit of God,
as they were to the church of Christ in the apostles`' days? Gal. 1:11-12.

And the apostle saith, '`When it pleased God, who separated me from my mother`'s womb,
and called me by his grace, to reveal his son in me,
that I might preach him among the heathen.`' Gal. 1:15-16. And Christ saith,
'`No man knows the son but the Father, neither knows any man the Father save the son,
and he to whom the son will reveal him.`' Matt. 11:27.

Now can any be ministers, or preachers of the son of God, or of the Father,
without this revelation, seeing they cannot know the son,
or the Father but by revelation?
So then none can truly preach God or Christ, if they do not know them,
except Christ do reveal him and his Father to them,
which blessed be God he hath done to thousands in this age,
that freely preach him and the Father, who walk in the light, as he is in the light,
and have fellowship with the Father and the son, and one with another:
blessed be God forever.

[.signed-section-signature]
G+++.+++ F.
