[.style-blurb, short="A Scripture Testimony Against Persecution for Religion"]
== A Scripture testimony against persecution for religion; and a persuasive to take off all the laws in Christendom, made to force or bind the tender consciences, which is God`'s prerogative.

Haman would have destroyed all the seed of the Jews, because their laws, religion,
and worship, were contrary to Ahasuerus the king; but Haman was destroyed himself,
who said, '`it was not for the king`'s profit that they should live;`'
but the king saw it was for his profit they should live,
and have their liberty.^
footnote:[Esther 3:5. 8.]

And Christ rebuked such as would have had fire to come down from heaven,
to destroy the lives of those that would not receive him,
and he told them they did not know what spirit they were of; and, therefore,
how have they known what spirit they were of that
have destroyed men`'s lives about religion and worship,
since the apostles`' days,
who have not prayed for fire to come down from heaven to destroy them,
but have kindled fires on earth to destroy them?
And have not such been worse, and more dark than they which Christ reproved,
that would have had fire to come down from heaven
to consume them that would not receive him?
And are they not under a great reproof?

And Christ whipped the buyers and sellers out of the temple of God;
but we do not read he ever whipped any in.

And Christ said, '`Let the tares and the wheat grow together until the harvest,
which is the end of the world,
lest they pluck up the wheat also;`' and at the end
of the world Christ will send forth his angels,
which should be the reapers.
And are not angels spirits, and not men?

Christ bade Peter put up his sword into his sheath, and said, '`All that take the sword,
shall perish by the sword;`' and did ever Peter,
or any of Christ`'s apostles and disciples draw out the carnal sword out of its sheath,
or make use of carnal weapons after, to defend Christ`'s church, religion, worship,
or faith?
But on the contrary, Christ bidding Peter put up his sword,
and healing the high priest`'s servant`'s ear, which he had cut off;
this was a sign of the healing gospel; and the apostle said,
'`that the weapons of their warfare were not carnal,
but spiritual;`' and that they did not wrestle with flesh and blood.
Now hath not all Christendom,
that (since the apostles`' days) have defended and held up their church, faith,
and worship, with carnal weapons, and wrestled with flesh and blood;
have not their weapons and warfare been carnal, and not spiritual, as the apostles were,
and the church of Christ in the apostles`' times?
And therefore, they that have drawn the sword to defend their religion, church, faith,
and worship, have not been in the spirit which Christ and the apostles were in,
but the spirit of the destroyer.

And have not they that have used these scriptures to persecute for religion, abused them?
saying, '`Let every soul be subject to the higher power,
and obey every ordinance of man for the Lord`'s sake,
for the punishment of evil doers,`' etc.
And the apostle tells you what evil doers they were, men-slayers, murderers of fathers,
murderers of mothers, and perjured persons, etc.
But the apostle doth not say, let every soul be subject to the higher powers,
and to obey every ordinance of man to punish people for religion, faith and worship,
and because they will not be of their church; for if the apostle had meant so,
why was not he subject to the Jews`' religion, and to Caesar`'s, the Roman emperor,
and Diana`'s? But the apostle saith to the church of Christ,
they were not to touch nor taste the doctrines, commandments and ordinances of men;
and said, Christ had abolished the Jews`' law of ordinances and commandments.
And therefore the christians were not like to be subject to them, nor to the heathens,
when they were not to touch, taste, nor handle them, who said,
'`they perish with the using.`'

And do not you read in the Revelations,
how it was the beast in the dragon`'s power that compelled all, both small and great,
to conform, and to worship him and his image, and to receive it,
and to be of his religion?
But doth not John tell you, the beast was cast into the lake of fire?

And doth not John tell you,
that the blood of the prophets and martyrs of Jesus was found in mystery Babylon,
the mother of harlots, or false church?
And how that she was drunk with the blood of the saints and martyrs of Jesus,
and that the inhabitants of the earth were made drunk with the wine of her fornication,
which made them mad, and rage against the saints and martyrs of Jesus?
and what doth John tell you was the end of this whore, or false church?

And do you not read in the ten persecutions,
what havoc the heathen kings and emperors made of the Christians,
in the days of the ten persecutions;
and was it not because they did not join and conform to them in their religion and worship?

And therefore,
is it not time for all that profess christianity to lay away their carnal weapons,
and put up their outward swords into their sheaths, as Christ commanded,
that they have defended their religion, church, and worship with,
and come to the spiritual weapons and warfare that the apostles used?
etc. And remember the example of old Cain,
that vagabond and wanderer from the true faith, who killed righteous Abel;
and remember Ishmael, that persecutor of the right seed.
And the apostle saith, '`He that is born of the flesh,
persecutes him that is born of the spirit.`' Even so it is now; for we never read,
that he that is born of the spirit did persecute any.
And Christ Jesus said, '`Love enemies, and love one another,
and by this ye shall be known to be my disciples;`' and
therefore all that profess Christ should obey his command.

Nebuchadnezzar caused a herald to proclaim, '`that whosoever would not bow to his image,
should be cast into the fiery furnace;`' but the Lord changed his purpose,
and saved his people.
And did not the Lord after that make him to know
that the Most High ruled in the kingdoms of men?

And therefore never let any herald cry more in Christendom under pain of fire, halter,
imprisonment, and spoiling of the goods of them that will not bow,
and fall down and worship another`'s image of religion;
for it cannot be the true religion, being Christ never gave any such commandment,
who sent his disciples to preach the gospel to all nations;
but not with a penalty of fire, halter, gallows, prison,
and spoiling of the goods of them that did not receive it, nor them;
but the dust of their feet will be a sufficient witness against them in the day of judgment.

Were not Pharaoh and his host great persecutors and destroyers of children?
And what became of him and his host?
Were not they destroyed in the sea in the end, by the Lord`'s power,
who heard the groans of his people in their sufferings?

And was not Herod a great persecutor of the Lord`'s people, who killed young children,
and who would have killed Christ?
But the Lord delivered him out of his hand;
and therefore it is time to lay away all persecution about religion,
for that is not of God; for the apostle saith,
'`He that hates his brother is a man-slayer, and hath not eternal life abiding in him;
but he that dwelleth in love, dwelleth in God, for God is love.`'

David was not to build the outward temple, because he had been a man of blood,
in outward war, in the old covenant.
Therefore, how can you that have shed so much blood,
and spoiled so many people in their persons, lives, and estates concerning religion,
faith, and worship, build up a spiritual house or temple in the new testament,
who have been out of the peaceable spirit of Christ Jesus?

Zion was not to be built up with blood, in the old testament;
therefore is that which is called Christendom, in the new testament,
like to build up heavenly Zion, with blood, persecution, jails, and spoiling of goods?
When Christ saith plainly to them that would have
had men`'s lives destroyed that did not receive him,
'`they did not know what spirit they were of;`' and
how can you know what spirit you are of,
that have put to death, and imprisoned to death,
and ruined so many in spoiling their goods about matters of faith, church, religion,
and worship?
And how are we like to trust our bodies and souls with them
that do not know what spirit they are of themselves?

Christ Jesus, who often said to the people,
and to the multitude '`He that hath an ear let him hear;`'
so that he did not persecute any that had not ears to hear,
and such as stopped their ears, or closed their eyes, and would not see with their eyes,
nor hear with their ears, lest they should have been converted.
And Christ did not prison, nor persecute,
nor spoil the goods of any that did not hear and conform to his religion, way, worship,
and church; but often, as is said before, Christ said,
'`He that hath an ear let him hear,`' and left them to the ear.
And John in the Revelations.
saith to the seven churches, '`He that hath an ear,
let him hear what the spirit saith to the churches.`' So he did not say,
he that doth not hear what the spirit saith to the churches, and conform,
should be cast into prison, and his goods spoiled, and banished.
Christ gave no such command, nor his apostles; but his command is,
'`that we should love one another, and loves enemies.
And he that dwells in love dwells in God;`' so then
he that dwells not in love doth not dwell in God;
and '`he that hates his brother is a man-slayer,`'
and no man-slayer hath eternal life abiding in him.
And doth not John say, in the Revelations,
'`it was the beast in the dragon`'s power that compelled all, both small and great,
to worship him and his image?`' And do you not read,
'`that the beast and the dragon was cast into the lake of fire,
and all his followers and worshippers?`'

And therefore is it not time for all that profess Christ to repent and reform,
and come to the apostles`' spiritual weapons and armour, concerning the faith, church,
religion, and worship of God?

[.signed-section-signature]
G+++.+++ F.
