[.style-blurb, short="The Inward and Spiritual Warfare"]
== The inward and spiritual warfare, and the false pretence of it. and a distinction between the true liberty and the false. And how God hath anointed the ministers of Christ and his church, and they have the anointing in them. And shepherds, husbandmen, fishermen, and tradesmen made prophets and apostles, to preach the word of God, and set forth his glory. Concerning purification by fire and water, in the old and new testament, and the eating of the heavenly bread, that people may grow thereby, and not be dwarfs. And how the son of perdition betrayed Christ without; and since his ascension betrays Christ within. And such who ignorantly say Christ reconciles the devil, etc. who destroys him and his works, and slays the enmity. And concerning prayer by the spirit, without the book. By G. F.

There are many people that do profess the apostle`'s words,
concerning his inward warring and warfare,
yet do not own the spirit that God poureth forth upon all flesh;
nor do believe that Christ doth enlighten every one that cometh into the world,
with the light of life;
nor do believe that the grace of God which brings salvation hath appeared unto all men,
and to be sufficient to teach them, and bring their salvation; though God saith to Paul,
'`his grace was sufficient for him`' when he was in his troubles and temptations.

Now all you that do talk of Paul`'s inward warfare,
and do not believe in the light of Christ, you cannot see his inward warfare,
for whatever makes manifest is light, and the light of Christ which shines in the heart,
gives the knowledge of the glory of God in the face of Christ Jesus,
through whom they overcome the devil and his works,
and he makes them more than conquerors.
For Christ saith, '`they that believe in the light, do become the children of light,
and are born of God,`' and pass from the death in Adam, to the life in Christ;
in whom they overcome the world.
Now you that do not believe in the light,
you say there is no overcoming while ye are on this side the grave.
You are not in the spiritual warfare, nor in the true belief which doth overcome,
nor in the true faith which is the victory; and how can you be in the spiritual warfare,
which do not come to the spirit of God, nor the spirit of grace,
which should teach you to deny ungodliness and worldly lusts,
and to live soberly and righteously, which God saith is sufficient,
and will bring you salvation?

But if you do pretend a warfare, without the light of Christ,
and his faith and spirit of grace, which brings salvation, and overcomes,
and is the victory;
then you may war all your life time till you go to the grave in your own wills,
and not overcome, nor have the victory; and that is the blind man`'s war and warfare,
without the light of Christ, and faith which is the victory, and the spirit of grace,
which brings salvation to all the believers in Christ.

And Joel said, '`that in the last days,
God would pour out of his spirit upon all flesh.`' And the
apostles showed the fulfilling of Joel`'s prophecy,
in Acts 2. When they preached Christ in his new testament, and new covenant to the Jews,
how that the saying of Joel was come to pass,
how that '`God would pour out of his spirit upon all flesh,
and his sons and his daughters should prophesy,
and his handmaids and servants should prophesy, and have visions,
and old men should dream dreams.`' Now this was the
fruit of the spirit of God in sons and daughters,
handmaids, and servants, and old men, to have their spiritual visions, dreams,
and prophecies.
And now what is the matter, that sons, daughters, handmaids, servants,
and old men have not prophecies, visions, and dreams now in Christendom,
as they had in the apostles`' days?
Is it not because they are erred from the spirit that God poureth upon them,
and so have not the spiritual dreams, visions, and prophecies;
and all they that are erred from the spirit that God poureth upon them,
they cannot serve and worship God in the spirit,
neither can they have unity with one another, nor fellowship in the spirit;
and that is the cause that so many in Christendom are in heaps one against another,
being erred from the spirit of God, so from the spiritual union and communion.

Now the means how all people may come to serve and worship God in the spirit,
and come into fellowship and communion in the spirit, and come to spiritual dreams,
visions, and prophecies, is to come to the spirit of God in their own hearts,
that he poureth upon them, young and old, sons and daughters, servants and handmaids,
that in and with the manifestation of the spirit, daughters, servants, young men and old,
may profit in their heavenly visions, dreams, and prophecies,
and so all to drink into one spirit, being baptized all with one spirit, into one body;
so in the spiritual communion, unity, and fellowship in the spirit of God;
and in the same spirit you will all serve and worship
the eternal infinite everlasting God that made you,
in his new covenant, and new testament.
'`Behold, the days come,`' saith the Lord,
'`that I will make a new covenant with the house of Israel, and the house of Judah:
not according to the covenant that I made with their fathers,
in the day that I took them by the hand to bring them out of the land of Egypt,`'
etc. Jer. 31:31-32.
Now here you may see the new covenant is not according to the old,
with their priests, whose lips were to preserve people`'s knowledge,
and circumcise the males outwardly, who had their outward Jerusalem,
and outward temple worship, and had their outward law given to them in tables of stone,
and the priest had a pulpit to read it in; and he had his tenths,
and offered offerings and sacrifices; and had their holy days, and sabbath days,
and their outward sacrifices, and outward altars, lights, and lamps; but the Lord saith,
the new covenant that he would make should not be according to the old,
for in the new covenant circumcision is of the spirit, not according to the flesh,
and such worship God in the spirit and truth,
and their bodies are the temples of the holy spirit of God,
and Christ is the one offering for sins, once for all,
and his blood cleanseth from all sin, and God writes his law in their hearts,
and puts it in their minds that all may read the law in their hearts and minds,
and know the Lord. Heb. 8.

And the old covenant commanded them to take oaths, and swear,
but in the new covenant Christ saith,
'`Swear not at all.`' And in the old covenant the priests took tithes;
but in the new covenant Christ saith, '`Freely ye have received,
freely give.`' And in the old covenant, they stood up to bless the obedient,
and curse the disobedient; but in the new covenant it is said, bless, and curse not.
In the old covenant they were to love their neighbours, and hate their enemy;
but in the new covenant it is said, love your enemies.
Here you may see the new covenant, that God had not made it according to the old,
and we are in the days of the new covenant and new testament.

The apostle exhorted the christians to look unto Jesus,
the author and finisher of their faith; for he saith, '`Jesus Christ, the same yesterday,
and today, and forever.`' Heb. 12:2. xiii.
8.

Now Jesus Christ is the rock of ages, and the foundation of many generations.
So then in every age and generation,
all the true christians forever must look unto Jesus, who is the author and beginner,
and finisher of their faith.

And now here it is clear, that the apostles and disciples of Jesus Christ,
in all their councils and meetings,
they did not make faiths for the true christians in the first primitive times;
but bid them look unto Jesus the author and finisher of their faith.
And all true christians must observe the apostles`' teaching and exhortation,
in every age and generation forever.
For Adam and Eve disobeyed God`'s command,
and so lost the image of God in righteousness and holiness,
and so forsook God`'s teaching, and the liberty God had placed them in,
and followed the serpent`'s teaching, who led them into a false liberty,
which brought death, corruption, and destruction.

God gave the Jews his righteous, just, holy, and good law,
and gave them his good spirit to instruct them; but they rebelled against his spirit,
and turned from God and his law, and were led by the evil spirit, the serpent,
into a false liberty, which led many of them into captivity, death, and destruction.

And God pouring out of his spirit upon all flesh in his new testament and new covenant,
by which spirit all may know God, and Christ;
but all christians that are gone from the spirit,
they are gone out of unity and fellowship, and true worship, into confusion,
and into false liberty in the flesh; for the spirit that God poureth upon all mankind,
is the only means to bring all into unity,
and to serve and worship God in his spirit and truth, if they believe and obey it;
and Christ, enlighteneth every one that cometh into the world with his true light,
which is the life in himself, that all might believe in the light,
and come to have life in Christ.
But they that hate the true light, which is the life in Christ,
and love the darkness more than the light, because their deeds are evil,
and will not come to it, because it will reprove them; this light doth condemn them,
and their evil deeds, in their darkness and false liberty, and false worship;
seeing they will not receive, nor hearken to the reproofs of the light of Christ,
and turn and have life in him, therefore they are condemned by the true light of Christ.

And Christ bids his disciples go preach the gospel, to wit, of life and salvation to,
or in every creature under heaven.
Now the gospel, the apostle saith, is the power of God unto salvation,
to every one that believes.
So now every one that doth not believe and receive his gospel, and them that receive it,
and after disobey it, all such go into, and are in a false liberty of death,
and destruction, from life and salvation, and peace with God; and upon such,
judgment comes from God, according to the gospel.
And the grace of God which brings salvation, hath appeared unto all men;
and if all men do not receive this spirit of grace, and walk in it,
which will teach them to deny ungodliness, and worldly lusts,
and to live soberly and godly, and will bring their salvation,
and bring them into favour with God, but turn the grace of God into wantonness,
and walk despitefully against the spirit of grace, such go out of favour with God,
and from the grace which is sufficient to teach them, and bring their salvation;
and such go into a false liberty, into death and destruction,
turning the grace of God into wantonness,
and walking despitefully against the spirit of grace, which is sufficient to teach them,
and bring their salvation, if they obey it, and walk in it:
and such are condemned with the light and spirit of God,
and such lie under condemnation that do not walk in it, and obey it.

But all they that walk in the light, and in the spirit of grace, and in the gospel,
and obey it, such know their true liberty in the spirit, and gospel, and in Christ Jesus,
and stand fast in that liberty,
in which Christ hath made them free from the yoke of bondage, from the devil,
and the world, that lieth in wickedness.
And the Lord preserve all his people in Christ Jesus, in whom true liberty is,
in whom they have life, and peace with God.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.asterism]
'''

[.blurb]
=== Here you may see how several of the Prophets and the Apostles were Shepherds, Husbandmen, and Tradesmen, who preached the word of God, and set forth his glory, and were despised and persecuted by the world, and the ministers of the letter without life.

Righteous Abel was a keeper of sheep, or a shepherd;
and by faith Abraham sojourned in the land of promise, as in a strange country,
and dwelt in tabernacles with Isaac and Jacob, the heirs with him of the same promise;
for they looked for a city which hath foundations, whose builder and maker was God. Heb. 11:10-9.

So these did not build great outward cities, but kept great flocks of cattle,
and dwelt in tabernacles; and Abraham was the father of the faithful,
and in Isaac was the seed called, for he was the seed of the promise. Gen. 21:12.

And Jacob he sold pottage. Gen. 25:19.
30, 31. And Jacob the second birth was a keeper of sheep,
for he kept Laban his father-in- law`'s sheep twenty years. Gen. 31:41.
And Rachel kept her father Laban`'s sheep, and watered them,
and Jacob helped Rachel to water them, and rolled away the stone.
So those two, Jacob and Rachel, married one another; and Jacob, the second birth,
rolled away the stone that the sheep might drink.
And the first uncircumcised birth stops the well, but the good nature doth open them,
and it naturally, and the divine nature doth it divinely.

And when Moses was full forty years old,
he fled from Pharaoh into the land of Midian to Jethro.
And Jethro had seven daughters, and they came and drew water,
and filled the troughs to water their father`'s sheep; and Moses sat at the well,
and the shepherds came and drove them away, but Moses stood up and helped them,
and watered their flock.
And Jethro sent for Moses, and he went to him, and married Zipporah, Jethro`'s daughter,
and kept his sheep.
And when forty years were expired,
the Lord appeared to Moses in the wilderness of Mount Sinai and Horeb,
in a flame of fire in a bush. Acts 7:23. 30. Ex. 2:13. and 3:2.
So Moses kept sheep forty years,
for he was forty years old when he departed out of Egypt, and fled from Pharaoh;
and he was eighty years old when he left Jethro his father-in-law,
and when he came into Egypt to speak to Pharaoh,
to let the children of Israel go out of Egypt, to worship and serve the Lord.
And Moses was forty years keeping the Lord`'s people,
the children of Israel in the wilderness, and he was forty years Jethro`'s shepherd,
keeping and watering the sheep of his father-in-law;
and forty years the Lord`'s shepherd, keeping of his people, and watering them,
as before.
And David was a shepherd, and kept his father`'s sheep in the wilderness.
And the Lord called him from keeping and feeding of outward sheep,
to feed his people the children of Israel. 2 Sam. 7:8.
And thus saith the Lord of hosts, '`I took thee from the sheep-cotes,
from following the sheep,
to be ruler over my people Israel.`' And as the Lord
called Jacob from keeping Laban`'s sheep;
so the Lord called Moses from keeping of Jethro`'s sheep, to feed and keep his sheep,
and his people.

And Elisha was a ploughman, and when he was ploughing with his servants,
and his twelve yoke of oxen, he forsook them, and obeyed the Lord,
when he called him to be his spiritual ploughman,
to plough up the fallow ground of their hearts. 1 Kings 19:19.
And Amos said, '`I was an herdsman, and a gatherer of sycamore fruit,
or wild figs; and the Lord took me as I followed the flock; and the Lord said unto me,
go and prophesy unto my people Israel.`' Amos 7:14-15.

And the words of Amos, who was among the herdsmen of Tekoah,
which he saw concerning Israel, were, '`The Lord will roar from Zion,
and utter his voice from Jerusalem;
and the habitations of the shepherds shall mourn.`' Amos 1:1-2.
And you may read the book of Amos,
and see how the Lord caused him to declare many dreadful prophecies,
not only to the Jews, but to other countries and nations.
So the Lord made him his herdsman, and to gather his fruit, and to watch over his people.

And as Jesus was walking by the sea of Galilee, he saw Peter, and Andrew his brother,
casting a net into the sea, for they were fishers, '`And he said unto them, Follow me,
and I will make you fishers of men;
and they straightway left their nets and followed him.
And going on from thence, he saw James and John, two sons of Zebedee,
in a ship with their father, mending their nets, and Jesus called them,
and they immediately left their ship and their father with their hired servants,
and followed Jesus.`' Matt. 4:18-21. Mark 1:16-20.

And Christ did make these fishers of men, and they did fish them out of the great sea,
the world; and sometimes they did drag out of the sea of the world,
some thousands at a time; as you may see about three thousand was converted at one time,
in Acts 2:41. Though the Jews, priests, rulers, and elders,
did with all their power and might, keep men in their sea, howbeit,
the number of them that did believe, and heard the word, were about five thousand men. Acts 4:4-5.

And Christ said, '`that the kingdom of heaven is like a net cast into the sea,
and gathered of every kind, which when it was full, they drew to the shore, and sat down,
and gathered the good into vessels, but cast the bad away.`' Matt. 13:47-48.

And do not you read of Simon Magus, Acts 9:10 to the 21st; and Ananias and Sapphira, Acts 5:1.
and Nicholas,
Acts 6. And were not these drawn out of the sea and then after cast away.
But what a glorious work they did, that Christ made fishers of men,
and gave them a net that would hold and never want mending-- his power;
for they were to preach the gospel to all nations, and to every creature.
So their net, the power of God, would reach over the sea, the whole world,
to gather the good, and cast away the bad.

The apostle Paul met with Aquila and Priscilla at Corinth,
and because Paul was of the same craft, he abode with them and wrought,
for by their occupation they were tent makers. Acts 18:1-3.

But did not Paul bring many to the grace and truth, and power,
and spirit of God in their hearts; who turned them from darkness,
to the light of the gospel of Christ; and from the power of Satan to God;
and so brought them to the inward tent and pavillion, where dwelleth the grace, truth,
spirit, and light of Christ, by which they receive him to rule in their hearts by faith.

'`And the Jews said of Christ, whence hath this man this wisdom, and these mighty works?
is not this the carpenter`'s son, and is not his mother called Mary,
and his brethren James and Joses, Simon and Judas, and his sisters,
are they not all with us?
Whence then hath this man all these things?`' Matt. 13:54-56.

And again, the Jews said, '`Is not this the carpenter, the son of Mary,
the brother of James and Joses, and of Judas and Simon; and are not his sisters with us?
and the Jews were offended at Christ Jesus.`' Mark 6:2-3.

'`And the Jews marvelled, saying, how knoweth this man letters, having never learned?
And Jesus said unto them, my doctrine is not mine, but his that sent me.`' John 7:15.

Here you may see, that the professing Jews called Christ the carpenter,
and the carpenter`'s son.
But Christ doth build up the fallen state of Adam and Eve,
who fell from the righteousness, and holiness, the image of God that he made them in.
Christ doth renew them up in the image of God again in righteousness and holiness;
and so are built up a spiritual house, and Christ a son is over his house.
'`And so he shall build the old waste places;
thou shalt raise up the foundations of many generations,
and thou shalt be called the repairer of the breach,
the restorer of the paths to dwell in.`' Isaiah 58:12.

Moses said, '`I have led you forty years in the wilderness,
your clothes are not waxen old upon you,
and thy shoes are not waxen old upon thy foot.`' Duet. 29:5.

And it was said to the tribe of Asher, '`Thy shoes shall be as iron and brass,
as thy days, so should thy strength be.`' Duet. 33:23-24.

Now this was the condition of the children in the wilderness,
in the old covenant and testament; their outward clothes and shoes did not wax old.
And here you may see that Moses did lead God`'s flock, his people forty years.

And now in the new covenant and testament, all the children of light,
have the light of life, and walk in the same, and are led by Christ;
their '`feet are shod with the preparation of the gospel
of peace,`' which '`gospel is the power of God unto salvation,
unto every one that believes.`' Eph. 6:15. and Rom. 1:16.

And they are shod with the gospel, the power of God; the power of God will never wax old;
shoeing with brass, iron, or leather, that will wax old, and wear away;
and to be clothed with the fine linen, the righteousness of Christ,
that clothing will never wax old.
Song. 1 say, many have been shod with the gospel, the power of God, in this age,
and their feet hath not slipped,
but have gone over the rocks in foul and stormy weather
being shod with that which will abide all weathers,
and all rough and thorny places; for the gospel is over all,
and they that are shod with it stand sure.

Here you may see what men they were in the eyes of the world,
that exalted the glory of the Lord, and spread his name and truth abroad;
and many others might be instanced in the scriptures.

In the temple of the Lord, every one doth speak of his glory. Ps. 29:9.
And therefore keep in the temple,
knowing that your bodies are the temples of the holy ghost.

'`By faith, Noah being warned of God, of things not seen as yet, moved with fear,
prepared an ark to the saving of his house, by the which he condemned the world,
and became heir of the righteousness,
which is by faith,`' and was not Noah a husbandman?

[.signed-section-signature]
G+++.+++ F.

[.asterism]
'''

[.blurb]
=== Here you may see all was to be purified by fire and water before it went into the camp of God, in the old testament; and all must be purified by the baptism of the holy ghost, and by fire, and the circumcision of the spirit; and washed by the water of the word, and made clean, before they go into the kingdom of our God, and heavenly Jerusalem.

The Jews in the old covenant and testament, when they went to war,
this was the ordinance and law of God to them, whatsoever they took in the wars,
whether it was gold, silver, brass, iron, tin, or lead, that would abide the fire,
they were to make it go through the fire,
and to be purified with the water of separation; and all that which abideth not the fire,
they were to make it go through the water; and they were to purify all the raiment,
and all that is made of skins, and all works of goats`' hair,
and all that was made with wood, and they were to wash their clothes,
and on the seventh day to be clean, and afterwards they were to go into the camp.

So you may see all things were to be purified by fire and water,
and that which would not abide the fire, was to go through the water;
and they were to wash their own clothes, and purify themselves seven days;
the perfection of days were to pass over them before they came into the camp.
And they were to purify the captives they took prisoners,
before they brought them into the camp; so that nothing was to go into the Lord`'s camp,
but what was clean, purified by fire or water.
And the warriors were to purify themselves before they went into the Lord`'s camp,
as you may see in Num. 31.

And Christ in his new testament, saith, '`that all must be born again of the spirit,
before they can see the kingdom of God, or enter into it,`' as in John 3.

And Christ, he baptizeth with the holy ghost, and with fire, whose fan is in his hand,
and he will thoroughly purge his floor, and gather his wheat into his garners;
but will burn up the chaff with unquenchable fire, as in Matt. 3:11-12.

Here you may see the chaff comes not into God`'s garner, but must be burnt up,
and no unclean thing enters into the kingdom of God, as you may see in the Revelations.

And though the gates of heavenly Jerusalem are not shut at all by day,
for there is no night there,
'`there shall in nowise enter into it any thing that defileth,
neither whosoever worketh abomination, or maketh a lie.`'
Rev. 21:27. and 22:14-15.

So here you may see all must be purified by the spirit, and by the heavenly fire,
and washed by the water of the word,
before they come into the city of new and heavenly Jerusalem, or the kingdom of God,
and walk in the light; and they must go through the baptism of fire and the holy ghost,
and the washing of the water of the word, before they come into heavenly Jerusalem,
and the kingdom of God, as before.
And they that are married to the Lamb, which are his wife, his church,
'`shall be arrayed in fine linen, clean and white,
for the fine linen is the righteousness of the saints;
and the armies which were in heaven, and followed Christ upon white horses,
were clothed with fine linen white and clean.`' Rev. 19:7-8. 14.

So as is said before, all must be washed, and clean, and purified,
and circumcised with the spirit, and baptized with the holy ghost, and with fire,
before they come into heavenly Jerusalem, and the kingdom of God.

The Lord saith,
'`a dwarf shall not come nigh to offer the offerings of
the Lord made by fire;`' he might eat the bread of his God,
as in Lev. 21.

Therefore, you that profess the new testament grow in the truth,
and feed upon the bread from heaven; take heed you be not dwarfs,
but live and walk in the spirit of God,
that you may be kept by the spirit without blemish, and that you may grow in grace,
and faith;
that you may be a royal priesthood to offer up spiritual sacrifices acceptable to God,
by Jesus Christ, as in 1 Pet. 2:5. 9. and that you may not be dwarfs,
but eat of the heavenly bread,
and grow that you may offer the spiritual sacrifice as before.

[.asterism]
'''

[.blurb]
=== Concerning the ministers of Christ, and his church, and the testimony of them.

[.heading-continuation-blurb]
How God hath anointed the ministers of Christ,
and his church, and they have the anointing in them.

Now he who establishes the ministers of Christ, and his church in Christ,
and hath anointed them, is God.
Now here you may see Christ`'s ministers God hath anointed.
And the apostle saith, '`who hath also sealed us,
and given us the earnest of his spirit in our hearts.`'
Here you may see God seals his people,
his ministers, and his church, and gives them the earnest of his spirit in their hearts,
and anoints them, and establishes them in Christ Jesus. 2 Cor. 1:21-22.

Now concerning the son of God, the Lord saith, '`Thou hast loved righteousness,
and hated iniquity, therefore God, even thy God,
hath anointed thee with the oil of gladness, above thy fellows.`' Heb. 1:9.

Here you may see Christ`'s ministers and his church are anointed,
and they have the anointing abiding in them; and they need no man to teach them,
but as the same anointing teacheth them of all things, etc. 1 John 2:27.

But God hath anointed Christ with the oil of gladness above his fellows,
who brings many sons unto glory; '`for both he that sanctifieth,
and they that are sanctified are all of one;
for which cause Christ is not ashamed to call them brethren.`' Heb. 2:10-11.

And Christ maketh his '`able ministers of the new testament, not of the letter,
but of the spirit; for the letter killeth,
but the spirit gives life.`' 2 Cor. 3:8. '`And he that soweth to the spirit,
shall of the spirit reap life everlasting.`' Gal. 6:8.

Here you may see what Christ`'s ministers sow to, and what they reap;
'`for Christ when he ascended on high, he led captivity captive, and gave gifts unto men;
and he that descended is the same also that ascended up far above all heavens,
that he might fill all things.
And he gave some apostles, some prophets, some evangelists,
and some pastors and teachers.`' These gifts of Christ to them,
were and are '`for the perfecting of the saints; for the work of the ministry;
for the edifying the body of Christ, until we all come into the unity of the faith,
and knowledge of the son of God, and unto a perfect man,
and unto the measure of the stature of the fulness of Christ.`'
And this was the work of the ministry of Christ,
and so brought them into the '`unity of the spirit,
in the bond of peace.`' '`There is one body, and one spirit,
even as you are called children into one hope of your calling;`' and this hope is,
Christ in you the hope of glory, whom the ministers of Christ preach,
'`warning every man, and teaching every man in all wisdom,
that they may present every man perfect in Christ Jesus.`' And
the ministers of Christ brought the church of Christ to '`one Lord,
one faith, and one baptism, and unto one God, and Father of all, who is above all,
and through all,
and in you all.`' Eph. 4. from 3 to 14. Col. 1:28. And the apostle saith,
'`If any man be in Christ Jesus, he is a new creature, old things are past away,
behold all things are become new; and all things are of God,
who hath reconciled us unto himself by Jesus Christ,
and hath given us the ministry of reconciliation.`'

Mark, the ministers of Christ have the ministry of reconciliation given to them,
to reconcile people to God through Christ.
And now let all the ministers of Christ consider,
how many they have brought to the unity of the faith,
and the knowledge of the son of God,
unto the measure of the stature of the fulness of Christ;
and how many they have presented perfect in Christ Jesus;
and with the gift of the ministry of reconciliation,
how many they have reconciled to God through Jesus Christ.

And the apostle saith, that '`God was in Christ reconciling the world unto himself,
etc. not imputing their transgressions unto them.`' And again,
Christ '`having made peace through the blood of his cross,
by him to reconcile all things unto himself; by Christ, I say,
whether they be things in the earth, or things in heaven; and he hath put in us,
or committed unto us, the word of reconciliation.
Now then, we the ministers of Christ are ambassadors for Christ,
as though God did beseech you by us, we pray you in Christ`'s stead,
be ye reconciled to God.`' 2 Cor. 5:17 to the end. Col. 1:20.

Now here you may see the ministers of Christ have
the word of reconciliation committed to them,
to reconcile people to God and Christ; for the apostle saith to the church of Christ,
the Colossians, '`You that were sometimes alienated, and enemies in your minds,
by wicked works,
yet now hath he reconciled.`' Col. 1:21. Therefore let all the ministers of Christ
consider how many they have reconciled to God by the word of reconciliation.

And the apostle saith to the church of Christ, '`The word is nigh thee,
even in thy mouth and in thy heart; and this is the word of faith which we preach.
If that thou confess with thy mouth the Lord Jesus Christ,
and believe in thy heart that God hath raised him from the dead, thou shalt be saved;
for with the heart man believeth unto righteousness,
and with the mouth confession is made unto salvation.`' Rom. 10:10-9.

And again the apostle saith, '`Wherefore God hath also highly exalted Christ,
and given him a name which is above every name;
that at the name of Jesus every knee should bow, of things in heaven,
and things in the earth, and things under the earth;
and that every tongue should confess that Jesus Christ is Lord,
to the glory of God the Father.`' Phil. 2:10-9.

Now here you may see all are to be subject to Christ`'s power,
and that every tongue shall confess that Jesus is Lord, to the glory of God the Father;
though they are not ministers and apostles, etc. yet they are confessors,
for with the heart man believes unto righteousness,
and with the mouth confession is made unto salvation,
and the word of faith being in their mouths and hearts,
that with the heart they may believe, and with the mouth confess.
And this is the word if they will hear it and obey it,
and that will reconcile them to God.

Now friends, if the Lord hath counted you faithful, and put you into his ministry,
seek to perform and fulfill it, and not neglect the gift that is given you;
and be good examples of the believers in word, in conversation, in charity, in spirit,
in faith, in purity; and always be ready to preach the word, and be instant in season,
and out of season.
He that observes the wind or storms, will not sow the seed;
and he that regards the clouds will not reap. Ecc. 11:4.
But the word of the Lord must be preached in season and out of season,
as in 2 Tim. 4:2. And the apostle saith to Timothy, '`I put thee in remembrance,
that thou stir up the gift of God which is in thee.`' 2 Tim. 1:6.
Which indeed there is need enough now to put many in remembrance,
and to stir up the gift of God in them, and to fight the good fight of faith,
and to lay hold of eternal life, whereunto they are called;
and to follow after righteousness, godliness, faith, love, and meekness.

And the apostle saith, that the holy ghost witnesses in every city; saying,
'`That bonds and afflictions abode him, and waited for him,
but none of these things moved him; neither counted he his life dear unto himself,
so that he might finish his course with joy;
and the ministry which he received of the Lord Jesus Christ,
to testify the gospel of the grace of God.`' Acts 20:24. You may see
the apostle had received his ministry from the Lord Jesus Christ.
And what a resolution was in him to finish it,
though bonds and afflictions waited upon him.
He did not mind the storms and winds of persecution;
and he exhorted others to take heed of the ministry
which they had received from the Lord to fulfill it;
and did exhort all to let their speech be always with grace, seasoned with salt,
that they may know how to answer every man,
commending themselves to every man`'s conscience in the sight of God.

And Peter saith in his General Epistle to the church of Christ,
'`As every man hath received the gift, even so minister the same to another,
as good stewards of the manifold graces of God.
If any man speak, let him speak as the oracles of God; if any man minister,
let him do it as of the ability which God giveth,
that God in all things may be glorified through Jesus Christ.`' 1 Pet. 4:10-11.

So here you may see the ministry is not limited to one sort of people, or to a tribe.
But '`as every man hath received the gift,
even so let him minister the same one to another,
as good stewards of the manifold grace of God.`' So this gift they receive from God,
and are stewards of the manifold grace of God.
'`And if any man speak, let him speak as the oracles of God.`' So not the oracles of men.
'`And if any man minister,
let him do it as of the ability which God giveth him.`' So it is
not of the ability that they minister which men give,
but what God giveth.
So it is to the glory of God through Jesus Christ.

And the apostle saith,
'`God hath dealt to every man a measure of faith.`' And he that ministered,
was to wait on his ministry; and he that exhorteth, on his exhortation;
and he that teacheth, on teaching; and he that giveth, he must do it with simplicity;
and he that ruleth, with diligence; and he that showeth mercy, with cheerfulness.
So this work and practice is from the grace and faith of Christ in their hearts.
Rom. 12:3 to the 9th.

And the apostle exhorts to give no offence in any thing that the ministry, namely,
of Christ, be not blamed.

Now you see what a care the apostle had upon him to keep all blameless,
that God may be glorified, saying,
'`But in all things approving ourselves as the ministers of God, in much patience,
in affliction, in necessity, in distresses, in stripes, in imprisonments, in tumults,
in labours, in watchings, in fastings, by pureness, by knowledge, by long suffering,
by kindness, by the holy ghost, by love unfeigned, by the word of truth,
by the power of God, by the armour of righteousness on the right hand and on the left,
by honour and dishonour, by evil report and good report, as deceivers, and yet true,
as unknown, and yet well known, as dying, and behold we live, as chastened,
and not killed, as sorrowful, yet always rejoicing, as poor, yet making many rich,
as having nothing, yet possessing all things.`' 2 Cor. 6:4 to the 11th.

Here you may see the ministers of God and Christ prove themselves.
And the apostle exhorts the ministers and the church of Christ,
'`to put on the armour of light.`' Rom. 13:12.

Here you may see light is the armour against darkness and its works.

And again, the apostle writes to the church of Christ, and the ministers, and saith,
'`My brethren be strong in the Lord, and in the power of his might;
and put on the whole armour of God,
that ye may be able to stand against the wiles of the devil;
for we wrestle not against flesh and blood, but against principalities, against powers,
against the rulers of darkness of this world,
against spiritual wickedness in high places.
Wherefore take unto you the whole armour of God,
that ye may be able to stand in the evil day, and having done all, to stand.
Stand therefore, having your loins girt about with truth,
and having on the breastplate of righteousness,
and your feet shod with the preparation of the gospel of peace; above all,
taking the shield of faith,
wherewith ye shall be able to quench all the fiery darts of the wicked,
and take the helmet of salvation, and the sword of the spirit,
which is the word of God.`' Eph. 6:11 to the 18.

Here you may see the heavenly and spiritual arms and armour,
that the ministers of Christ and his church are to put on,
which is able to defend and preserve them,
against the devil and all his foul instruments.
For God`'s people have proved and tried these heavenly arms and armour,
and by it they have been preserved steadfast and undaunted,
and valiant for Christ Jesus and God`'s name and truth upon the earth;
and by it they have been able to stand against the wicked, and overcome him,
and have the victory over him.
And my desire is, that all God`'s ministers and his church,
may be armed with these heavenly arms and armour, in this their age and generation,
and then they will not fear the devil, nor all his darts, nor lying accusations,
nor slanders, nor false reports, but in the spiritual arms and armour of God,
they will stand as valiant soldiers in Christ, over him and them all.
Amen.

Let all have oil in their own lamps, and water in their own wells,
and fruit on their own trees, and mind their own vine, and improve their own talent,
and not hide it in a napkin, like the slothful servant,
and let none put their candle under a bed, or a bushel, but in a candlestick,
that it may give light.
So let your heavenly light so shine that men may see your good works,
and glorify your Father which is in heaven.

When Christ sent for his disciples, he said unto them, '`When I sent you without purse,
and scrip, and shoes, lacked ye any thing?`' and the disciples answered and said,
they lacked nothing.

The apostle said, '`Let us, who are of the day, be sober,
putting on the breastplate of faith and love,
and for an helmet the hope of salvation.`' 1 Thess. 5:8.

Here you may see that Christ`'s disciples wanted nothing, who freely had received,
and freely did give.

And you that are of the day of Christ, be armed with this breastplate of faith and love,
and the helmet of hope and salvation.

David said, '`Mine heart is not haughty, nor mine eyes lofty;
neither do I exercise myself in great matters,
or in things too high for me.`' Ps. 131:1.

And the apostle said, '`I do exercise myself to have always a conscience void of offence,
toward God, and toward men.`' Acts 24:16.

And the apostle writes to Timothy, to exercise himself unto godliness,
for bodily exercise profits little, but godliness is profitable unto all things;
having the promise of the life that now is, and of that which is to come. 1 Tim. 4:7-8.

And the apostle saith, '`Strong meat belongeth to them that are of full age, even those,
who by reason of use have their senses exercised
to discern both good and evil.`' Heb. 5:14.

God chasteneth his people for their profit, that they might be partakers of his holiness.
'`Now no chastening for the present seems to be joyous, but grievous; nevertheless,
afterwards it yieldeth the peaceable fruits of righteousness,
unto them that are exercised thereby.`' Heb. 12:11.

Now here Christ`'s ministers and his church must know these several sorts of exercises,
both to God and man, and unto godliness, and a discerning of good and evil;
and this exercise must be in the spirit and power of God,
which keeps people`'s minds low and in humility.
And this must be in the spiritual exercise, for bodily exercise profits little,
or for a little time, that passes away, but godliness is profitable unto all things;
and they that are exercised in this godliness,
they have a promise of the life that now is, and of that which is to come,
which is life everlasting; and God preserve all his people in this exercise.
Amen.

And Paul said to Agrippa, the king, when he was brought before him,
he was sent to open people`'s eyes, and '`to turn them from darkness to light,
and from the power of Satan unto God, that they may receive forgiveness of sins,
and inheritance among them which are sanctified by faith in Christ.
Whereupon, O king Agrippa, I was not disobedient unto the heavenly vision,
but showed first unto them of Damascus, and at Jerusalem,
and throughout all the coasts of Judea, and then to the Gentiles,
that they should repent and turn to God,
and do works meet for repentance.`' Acts 26:18-20.

So here you may see, it is no new thing for the ministers of Christ,
to turn people from darkness to light, and from the power of Satan to the power of God.

[.asterism]
'''

[.blurb]
=== Concerning such who ignorantly do say that Christ reconcileth the serpent, Satan, devil, and enmity: for Christ comes to destroy the devil, etc. and slay the enmity.

The apostle saith, all things are of God,
who hath reconciled us to himself by Jesus Christ,
and God was in Christ reconciling the world unto himself,
and having made peace through the blood of his cross
by him to reconcile all things unto himself,
by Christ, I say, whether they be things in the heaven, or things in the earth,
and that he might reconcile both Jews and Gentiles unto God in one body by the cross,
having slain the enmity thereby, or in himself.

Now some have said, both ranters and others, that Christ doth reconcile the serpent,
Satan, the devil, and enmity,
which they ignorantly say from these scriptures before mentioned; for they say,
are not these things which defile a man, which come out of a man, the evil things?
And though they are called things, yet these evil things were not in Adam,
when God made him, nor as long as he abode under God`'s teaching;
but when he forsook God, and disobeyed him, and followed the serpent,
teaching them his transgression and sin,
brought into his heart all these evil things which come from the heart; evil thoughts,
murders, adulteries, fornications, thefts, false witness, blasphemies, sin, death,
and the devil, the power of death.
And so these evil things defile a man and woman, which proceed out of him,
as Christ speaks of.

And Christ was manifest to destroy the works of the devil,
and who through death destroys death, and the devil the destroyer,
who is the power of death, and bruises the serpent`'s head, and slays the enmity,
and makes peace; and so doth destroy the things and works of the devil, Satan, serpent,
and enmity.
And so it is clear, Christ doth not reconcile the things and works of the devil;
nor the devil, Satan, serpent, and enmity; but bruises the head of the serpent,
and destroys the devil, and his works, and his things, and slays the enmity, as before;
and Christ reconcileth all things in the earth, and things in the heaven,
which are God`'s works that he hath made.
And Christ sanctifieth man, who hath been defiled by the devil,
and his evil things and works; and the old man must be put off with his deeds,
and the new man put on, which is after God, etc.
So the old man, and his deeds, and the evil things, and the members that are below,
are to be mortified, or killed.
So Christ doth not reconcile to God, the old man and his deeds;
nor the evil things and members that are below; nor the body of death; nor the chaff,
nor sins of the flesh.
For Christ, baptizeth with the holy ghost and with fire, whose fan is in his hand,
and he will thoroughly purge his floor, and gather his wheat into his garner,
but will burn up the chaff with unquenchable fire so the chaff
and corruption is to be purged and burnt up with unquenchable fire,
and not reconciled to God.

And the apostle said, '`Ye are circumcised with the circumcision made without hands,
in putting off the body of the sins of the flesh,
by the spiritual circumcision of Christ.`' So you may see
this body of sins of the flesh is not to be reconciled,
but to be put off.
And God through Christ reconcileth all things in heaven,
and things in the earth to himself, who bruises the serpent`'s head and slays the enmity;
and destroys the devil and his works, and makes an end of sin;
and so through death destroys death, and the devil, the power of death,
as is said before.
And so it is clear, that Christ doth not reconcile the serpent, Satan, devil,
nor none of his works, but destroys them, and slays the enmity;
and yet God by Christ doth reconcile all things unto himself; by him, I say,
whether they he things in the earth, or things in the heaven. Col. 3:20.

[.asterism]
'''

[.blurb]
=== Here you may see how the son of perdition betrayed Christ to the Chief Priests without, and how the son of perdition since Christ`'s ascension gets into the temple, and betrays Christ within, where Christ and his truth should be.

The devil, who abode not in the truth, tempted Adam and Eve to disobey God,
and to go into a false liberty, out of truth, to eat of that which God had forbid,
by which they lost the image of God, and were drove out of the paradise of God,
wherein was the true and blessed liberty, and all things were blessed to them.
And when people began to multiply upon the earth, in the old world,
they run into wickedness and false liberty, and corrupted the earth;
and therefore God spared not the old world, but brought his judgments upon them,
and saved Noah and his family, a preacher of righteousness; but the ungodly old world,
regarded not his righteousness that he preached unto them,
but went on in their loose and false liberty,
until God brought a flood upon the old ungodly world and destroyed them.

And likewise the Lord turned the cities of Sodom and Gomorrah into ashes,
who ran into wickedness and false liberty;
and therefore God condemned them with an overthrow,
making them an example unto all those that after should live ungodly.
And Abraham prayed to God that he would not destroy the city of Sodom and Gomorrah;
and the Lord said, '`if he found but ten righteous within the city,
he would not destroy it for the ten`'s sake.`' But the Lord delivered just Lot from them,
who was vexed with the filthy conversation of those wicked people;
for that righteous man, Lot, dwelling among them, in seeing and hearing it,
vexed his righteous soul from day to day, with their unlawful deeds.

So here you may see these people of the city of Sodom and Gomorrah,
their conversation was filthy and wicked, and their deeds were unlawful;
such deeds and liberty, the Lord and his law did not allow of;
and so they were in a false liberty.
And therefore of that false liberty, which is out of righteousness and the law of God,
let all take heed; for if they do not,
they will be sure to come under judgment and condemnation.
For God spared not the angels that sinned, which kept not their first estate,
but left their habitation; he cast them down to hell,
and hath reserved them in everlasting chains under darkness,
unto the judgment of the great day.
And therefore all are to have a care to keep their habitation in the truth and righteousness,
and where there is righteousness, there is peace; for you read in the apostles`' days,
many in au outward profession did forsake the right way and went astray,
following the way of Balaam: and also such as went in the way of Korah, Dathan,
and Abiram.

Now Cain and Balaam had heard the voice of God,
and Korah and his company the Lord had brought out of Egypt by his mighty arm and power;
and therefore these might speak great swelling words of vanity,
but were out of the way of light and life,
and troublers of the children of the Lord in all ages, that walked in the way of Cain,
Korah, and Balaam.
And these are the wells without water, and clouds that are carried about with a tempest,
to whom the mist of darkness is reserved forever.
And these are trees whose fruit withers, and without fruit; twice dead,
and to be plucked up by the roots.
They were dead in Adam, and quickened and made alive, and dead again,
and plucked up by the roots.
Then they were not like to grow any more in the true ground;
but it happeneth to them according to the true proverb,
'`The dog is turned to his own vomit again;`' that which he once vomited up,
he takes it again, and '`the sow that washed,
to her wallowing in the mire.`' And so it seems she was once washed.
And these are they that promise themselves liberty, and are the servants of corruption,
and whosoever is overcome by them, is brought into bondage.
So the latter end of all such as walk in those paths is worse than the beginning.

And these are the raging waves of the sea, foaming out their own shame,
showing that they are gone into the world, the sea; wandering stars,
to whom is reserved the blackness of darkness forever.
And these were false teachers, and many should follow their pernicious ways,
by reason of whom the way of truth shall be, and is, evil spoken of.
These be they who separate themselves, sensual, having not the spirit.
This is a separation from the spirit of God,
and so from the fellowship of God`'s sons and daughters in the spirit;
so they cannot be the fixed stars in the firmament of God`'s power.
And therefore all God`'s children are to be built up themselves in the
holy faith which Jesus Christ is the author and finisher of,
and dwell in the love of God, which edifies the body of Christ.
And you have heard how the Lord saved his people out of the land of Egypt,
and afterwards destroyed them that did not believe,
neither received the truth in the love of it, nor walked in his law,
but rebelled against his spirit, which he gave them to instruct them;
and so rebelling against that which would have kept them in fellowship,
and in unity in the spirit, the bond of peace;
for which cause God destroyed many thousands of them in the wilderness.
And now take heed,
all you that God hath brought out with his mighty power out of spiritual Sodom, Egypt,
and Babylon, lest you forsake his power, and Christ the right way of life,
and go in the way of Cain, Korah, Dathan, and Abiram, and Balaam;
and like Sodom and Gomorrah, and the old world; and become like raging waves of the sea,
and the sow to the mire, and the dog to the old vomit again; and so wells without water,
clouds without rain, trees without fruit, and wandering stars;
carried about with a tempest; such must expect to be cast down into hell,
and the chain of darkness to come over them,
and to be reserved unto the judgment and condemnation of the great day.

The apostle saith,
'`There must come a falling way first before the man of sin be revealed,
the son of perdition, who opposes and exalts himself above all that is called God, etc.
So he that sits in the temple of God, etc. but that wicked one shall be revealed,
whom the Lord shall consume with the spirit of his mouth,
and destroy with the brightness of his coming.`' And the son of perdition,
his coming is after the working of Satan, in the enmity, with all power,
etc. and '`with all deceivableness of unrighteousness in them that perish,
because they receive not the love of the truth that they might be saved;
for this cause God shall send them strong delusions that they should believe a lie,
that they all might be damned, who believe not the truth,
but had pleasure in unrighteousness.`'

Therefore, brethren, stand fast in the Lord Jesus Christ,
and be established in him in every good word and work.

And now, my friends,
here you may see this mystery of iniquity did begin to work in the apostles`' days,
after Christ was ascended, and after the gospel was preached in the nations;
and you may see how the apostles,
and the church of Christ were troubled with such as went in Cain`'s,
Korah`'s and Balaam`'s way, and Jezabel`'s and the Nicolaitans,
and such as said that they were Jews, and were not, but did lie,
as many say they are christians and inward Jews now, but do not walk in Christ.

Now there hath been a night of apostacy since the apostles`' days,
and now the everlasting gospel is preached again, which was preached to Adam, saying,
'`The seed of the woman shall bruise the serpent`'s head;`' and to Abraham, saying,
'`In thy seed shall all the nations,
and all the families of the earth be blessed;`' so
that many are gathered into Christ the seed,
both males and females; into his government, of the increase of it,
and his peace there is no end.
And now this mystery of iniquity, you know how it hath wrought,
and that there hath been a falling away, and many have run into Cain`'s, Korah`'s,
and Balaam`'s way, and Jezabel`'s, and the Nicolaitans, and have been,
and are the troublers of the church of Christ; and the son of perdition,
that man of sin is revealed, who opposes and exalts himself above all that is called God,
etc. and sits in the temple of God;
and they that receive not the truth in the love of it, but believe a lie,
are deceived by him to their destruction.

Now you read how the outward Judas or son of perdition betrayed Christ without,
but this was and is an inward son of perdition that betrayed Christ within,
who sits in the temple of God,
and opposes and exalts himself above all that is called God, as before;
for that which may be known of God is manifest within, and God hath showed it unto them.
So the son of perdition, the man of sin, the wicked one, and mystery of iniquity,
whose working is after Satan with all deceivableness in them that perish;
he gets into the temple of God and sits there, where light, grace,
and truth and the word of God should be, and the holy ghost;
for the saints`' bodies are the temples of the holy ghost, and God and Christ,
who dwells in them, and walks in them.
But there is a falling away from the truth first,
before the man of sin and son of perdition be revealed, and then his opposition is seen,
and then he deceives, after the working of Satan,
such as receive not the truth in the love of it;
for Judas the son of perdition which betrayed Christ, he was numbered with the apostles,
and obtained part of their ministry, from which by transgression he fell;
and therefore saith the apostle, '`As it is written in the book of Psalms,
let his habitation be made desolate,
and his bishopric let another take;`' as in Acts 1:17. 20.

So here you may see no man is to dwell in Judas`' habitation who fell from the truth,
and that part of the ministry which he had: so there is a falling away first,
before that the man of sin the son of perdition be revealed,
and many may come so far as outward Judas the son of perdition,
to be partakers of the true ministry, and then fall away from the life and power of it,
and become sons of perdition, opposers, betrayers,
and deceivers of them that believe a lie, and receive not the truth in the love of it.
But let all men beware of his habitation,
for the Lord will consume him with the spirit of his mouth,
and destroy him with the brightness of his coming.

And you that have stood steadfast in the Lord Jesus Christ and his government,
have been sensible what work this man of sin, the son of perdition,
hath made in his opposition and opposing, yea,
with all its power to betray them who walk and live in Christ, with their words,
and books, and carriages, and actions; but he shall not prosper,
for the Lord will consume him with the spirit of his mouth,
and destroy him with the brightness of his coming.
Hallelujah.

And therefore, all everywhere that have received the gospel,
and the seed in which all nations are blessed, dwell in this seed, males and females,
who are all one in him, and live in the peaceable holy government of Christ,
of the increase of which, and its peace, there is no end.
And in this government, neither Cain, Korah, Dathan, nor Abiram, with their false fire,
nor Balaam, nor the son of perdition can come.
These are all without; though they trouble the church of Christ for awhile,
yet Christ will trouble them in the day of their consuming and destruction.
And so all walk in Christ Jesus, who was before they were,
and will be when they are gone; and in Christ there is no division, but peace,
for he is not divided; and in him God Almighty preserve all his people.
Amen.

[.blurb]
=== A postscript concerning prayer.

[.heading-continuation-blurb]
Here you may see is a scripture testimony of the apostle of
Christ to the Christians and church of Christ,
how and what they were to pray by, and in;
and that the apostles did not make them prayers,
and give them books and other things to pray by.

The apostle writes to the church of Christ, the Ephesians,
(Eph. 5:18-19) and exhorts them, and saith,
'`Praying always with all prayer and supplications in the spirit,
and watching thereunto with all perseverance and supplication for all the saints,
and for me, that utterance may be given unto me,
that I may open my mouth boldly to make known the mystery of the gospel.`' Mark,
their prayers, and supplications, and watchings, were to be in the spirit,
both for themselves, and the saints, and for the apostles.

And the apostle doth not give them a book to pray by, and say, pray by the book,
but by the spirit, yea, the apostle saith, '`they were always to pray in the spirit.`'

And the apostle saith to the church of Christ, the Corinthians,
(1 Cor. 14:15) '`I will pray with the spirit, and will pray with understanding also.
I will sing with the spirit,
and I will sing with understanding also.`' And again the apostle said to the Colossians,
'`that he prayed always for them.`'

So you may see the apostle doth not say that he prayed by the book;
but he prayed by the spirit, and the people cannot have always the book to pray by,
but the spirit they may have in them, by which they may pray always.

And the apostle saith to the Romans of the church of Christ,
'`The spirit helpeth our infirmities,
for we know not what we should pray for as we ought;
but the spirit itself maketh intercession for us with groans that cannot be uttered;
and he that searcheth the heart, knows what is the mind of the spirit,
because he makes intercession for the saints according
to the will of God.`' Rom. 8:26-27.

Now here you may see the apostle doth not say it was outward forms, or prayer books,
that did help their infirmities,
nor turn them to the prayer books to help their infirmities,
or make intercession for them;
but he plainly tells them the spirit did help their infirmities,
and makes intercession for them according to the will of God,
who knows the mind of the spirit; for the spirit which he pours upon them,
people have always with them, but the book they may not always have with them,
but the spirit they have always with them by sea and land, and night and day,
to help their infirmities, and make intercession for them, if they do not err from it,
and rebel against it.

And the apostle Jude in his General Epistle to the church of Christ, exhorts them,
saying, '`But ye beloved, build up yourselves in the most holy faith,
praying in the holy ghost.`' Jude 20.

Now here you may see what the church of Christ were to build themselves up in,
and what to pray in.
Namely, in the holy faith, and to pray in the holy ghost.
He doth not say they were to pray in books,
neither do we read that he made books for them to pray by or in;
but the apostle told the church of Christ,
in the last time '`there should be mockers who should walk after
their ungodly lusts;`' and these were they who separate themselves,
sensual, having not the spirit, who were wandered and erred from it:
then such were not like to pray in the spirit, and in the holy ghost,
as the true christians were and are.
Christ saith, '`Watch ye therefore, and pray always.`' Luke 21:36.

And in Luke 18:1. it is said, '`that men ought always to pray,
and not to faint;`' and this must needs be by the spirit that makes intercession.

And the apostle saith, '`Be careful for nothing,
but in everything by prayer and supplication with thanksgiving,
let your requests be made known unto God.`' Phil. 4:6.
'`And I will therefore that men pray everywhere,
lifting up holy hands without wrath and doubting, and that prayers, supplications,
intercessions,
and giving of thanks be made for all men.`' Is not this in the holy spirit,
with lifting up holy hands. 1 Tim. 2:1.
8.

And the angels offered up the prayers of the saints upon
the golden altar which was before the throne of God,
and the prayers of the saints ascended up before God out of the angels`' hand. Rev. 8:3-4.

And do you think that these prayers of all the saints
were outward prayer books that were made for them,
or were they prayers by and in the spirit, which they offered up to God?

[.signed-section-signature]
G+++.+++ F.
