[#ch44.style-blurb, short="Several Treatises"]
== Several treatises worthy of every true Christian`'s serious consideration, By G. F.

[.heading-continuation-blurb]
I+++.+++ A distinction betwixt the prophets of God, Christ, and his ministers,
and the messengers of Satan; for the one preaches up Christ`'s works and things,
and the other preaches up Satan`'s works and his evil things.
Wherein you may clearly see, the outward body of man and woman is not the body of death,
nor sins of the flesh, nor the old man with his deceitful lusts, which must be put of;
and how that men and women had outward bodies, before the body of death,
and sins of the flesh, and the old man came into them,
and by what means they came into man, and by what means they are cast out again,
while men and women are upon the earth.
And how that the ministers of Satan teach people,
that they must carry about them a body of death, and sins of the flesh, and imperfection,
whilst on this side the grave, which never did the prophets of God, Christ,
nor his apostles preach any such doctrine.

The Protestant priests, ministers, and teachers, preach to the people,
and teach them both in public and private, that they must carry a body of sin,
and a body of death, as long as they live on this side the grave;
and none can be made free from sin and this body of death,
as long as they live upon the earth.
And they have so riveted this doctrine into the people,
of carrying a body of sin and death,
and not being made free from it while upon the earth,
that both the professors and the hearers, as well as the priests,
plead for this body of sin, death and imperfection while upon the earth;
and many of the teachers and professors are so ignorant, that they say,
the outward body or creature of man and woman, is the outward body of sin and death;
which doctrine is utterly false, and they are quite mistaken, for the apostle saith,
'`The earnest expectation of the creature waiteth
for the manifestation of the sons of God,
because the creature itself shall also be delivered from the bondage of corruption,
into the glorious liberty of the children of God.`' Rom.
8:19-21. So here it is clear that the outward man of flesh,
blood, and bones, is not the old man with his body of death,
and body of the sins of the flesh.
For the apostle saith, '`Knowing this, that our old man is crucified with Christ,
that the body of sin might be destroyed, that henceforth we should not serve sin;
for he that is dead is free from sin; but now being made free from sin,
and become servants of God, that ye have your fruits unto holiness,
and your end everlasting life.`' Rom. 6:6-7. 22. So you may see here that the Romans,
and the church of Christ, and the apostles, as men and women, were living,
though the old man of sin was crucified.

And in the beginning,
when God Almighty created man and woman in his own likeness and image,
'`God blessed them, and said unto them, be fruitful, and multiply,
and replenish the earth, and subdue it.`' And said unto them,
'`Have dominion over the fish of the sea, and over the fowls of the air,
and over every beast of the earth; and over all the earth,
and over every creeping thing that creepeth upon the earth.
And God saw everything that he had made,
and behold it was very good.`' Gen. 1:26 to the end.

Now here you may see all that God made was very good, perfect, and blessed;
and man and woman had no body of death, nor body of sin,
though they had outward bodies when God made them.
And the Lord God planted a garden, and put them into it, to dress it, and keep it,
and said unto them, '`Of every tree of the garden thou mayst eat freely,
but of the tree of knowledge of good and evil thou shalt not eat;
for in the day thou eatest thereof, thou shalt surely die.`'

Now here you may see Adam and Eve in paradise, what commands God gave unto them,
and as long as they kept under God`'s teaching they kept in his image, and were blessed,
perfect, and happy, and they had dominion over all that God made, and the serpent;
and they had outward bodies, yet they had no body of death, nor body of sin,
but were perfect, as you may see in Gen. 1:2. For Adam said,
'`Eve was bone of his bone,
and flesh of his flesh.`' So it is clear that their outward body of flesh and bone,
is not the body of death, and body of sin,
the old man which must be crucified and put off,
as in Rom. 6:6. And Adam and Eve had not this old man,
the body of death and body of sin, when God made them,
nor as long as they kept under God`'s teaching,
but when they hearkened unto the serpent`'s false teaching;
for '`the serpent said unto the woman, yea, hath God said,
ye shall not eat of every tree of the garden?
The woman said unto the serpent, we may eat of the fruit of the trees of the garden,
but of the fruit of the tree which is in the midst of the garden, namely,
of the knowledge of good and evil, God hath said ye shall not eat of it,
neither shall ye touch it, lest you die; for God said,
in the day that thou eatest thereof thou shalt surely
die.`' The serpent said to the woman,
'`ye shall not surely die, for God doth know that in the day you eat thereof,
then your eyes shall be opened, and ye shall be as gods,
knowing good and evil.`' here the devil was a liar and a murderer from the beginning,
for he taught them to eat that which the Lord said,
'`in the day they did eat they should surely die,`' and the serpent said,
'`they should not surely die, they should be as gods,`' etc.
So in this it is plainly seen, he was a murderer and a liar from the beginning.
'`And when the woman saw that the tree was good for food, to wit,
the tree of knowledge of good and evil,`' which God said,
'`in the day that you eat thereof ye shall surely
die;`' here went out the lust of the flesh,
'`and she saw that it was pleasant to the eyes,`'
here was the lust of the eye to that which God forbade,
'`and she saw it was a tree to be desired to make one wise;`' here was the pride of life.

And John saith, '`For all that is in the world, the lust of the flesh,
the lust of the eyes, and the pride of life, is not of the Father, but is of the world;
and the world passes away and the lust thereof,
but he that doth the will of God abideth forever.`' 1 John 2:16-17.
And James saith in his General Epistle to the church of Christ,
'`But every man is tempted, when he is drawn away of his own lust, and enticed;
then when lust hath conceived it brings forth sin, and sin,
when it is finished brings forth death.`' James 1:14-15.
Now here is the conception of the body of sin and death,
'`and the old man which is corrupt according to the deceitful
lusts.`' Eph. 4:22. Now here you may see clearly,
this old man which lust hath conceived, which brings forth the birth of sin and death,
and the lust of the flesh, lust of the eye, and pride of life, is not of the Father,
but of the world; so this old man with his deceitful lusts, and body of sin and death,
is not the outward creature of man and woman,
nor his outward flesh and blood which God hath made.
For you may see Adam and Eve had no body of death
and body of sin when God Almighty made them;
but when they forsook God and disobeyed his command, and forsook his teaching,
and obeyed the serpent`'s, the liar and murderer`'s teaching, who abode not in the truth,
and so followed the lust of the flesh, the lust of the eye, and the pride of life,
which is not of the Father; and so when lust had conceived it brought forth sin,
and when it was finished it brought forth death, and so there came the body of sin,
and body of death into man and woman, called the old man with his deceitful lusts,
which hath a wisdom below, which is earthly, sensual, and devilish,
which is not from above.
This wisdom man and woman got by hearkening to the serpent,
and looking out at the tree they thought to be made wise, etc. became fools.
After man and woman had transgressed the command of God, and disobeyed him,
in eating that which God forbid, and hearkening to the serpent, and obeying him,
they died, and fell from the image and likeness of God, and his wisdom, power,
and dominion, and then God drove them out of paradise into the earth.
And though man and woman died from the image and likeness of God,
of righteousness and holiness, and his wisdom and power,
yet they were alive outwardly in the earth, with their body of death,
and sins of the flesh, and had children.
And in process of time, the serpent the devil that deceived them, telling them,
'`they should be as gods,`' (instead thereof,) he came to be god of the world,
which got in by disobedience, and rules in the disobedient;
and so I say in process of time,
the devil got the disobedient to make gods of stocks and stones, and to worship them.
Now all the devil`'s messengers, teachers, ministers, disciples, prophets, bishops,
and shepherds, and his angels and unclean spirits,
like the devil that abode not in the truth, all these preach up a body of death,
and a body of the sins of the flesh,
that men must carry about them as long as they live whilst on this side the grave,
and say they must not be made free from sin and this body of death;
whereas the body of death and sins of the flesh,
came into man and woman by disobeying God, and forsaking his teaching,
and hearkening to the devil`'s teaching.
And so the devil and all his messengers, ministers, prophets, false apostles, priests,
bishops, and shepherds,
study and labour with all their might in the devil`'s dark power and unclean spirit,
to keep up the devil`'s works in man and woman, and tells them,
there is no perfection here, no overcoming here, while on this side the grave.
So they deny the end of Christ`'s coming, for God never sent any of his prophets,
nor his son, nor his apostles, to tell the people they must carry a body of death,
or a body of the sins of the flesh to the grave, but said, '`Be ye holy,
for I am holy.`' And Peter saith, '`He that hath called you is holy,
so be ye holy in all manner of conversation.`' 1 Peter 1:15. '`And for this purpose
was the son of God manifest that he might destroy the works of the devil`' And again,
'`Ye know that Christ was manifest to take away sin.`' 1 John 3:5.
8+++.+++ This is the ministers`' of Christ`'s doctrine,
and the blood of Christ cleanseth from all sins. 1 John 1:7.
And he shall finish transgression, and make an end of sin,
and make reconciliation for iniquity, and bring in everlasting righteousness,
etc. to wit Christ. Dan. 9:24.
Now the devil`'s teachers say you must have your sin,
and it is not taken away as long as you live,
but you must carry about you the body of death and sins of the flesh to the grave,
which is the devil`'s works, and his ministers`' doctrine.

And Peter saith '`Forasmuch as ye know that ye were not redeemed with corruptible things,
as silver and gold, from your vain conversation,
etc. but with the precious blood of Christ,
as of a lamb without blemish or spot.`' 1 Pet. 1:18-19. And the apostle saith,
'`Let us draw near with a true heart in full assurance of faith,
having our hearts sprinkled from an evil conscience,
and our bodies washed with pure water.`' Heb. 10:22. And Christ '`sanctifies
his people with his own blood.`' Heb. 13:12. And John saith,
Christ that '`loved us and washed us from our sins in his
own blood.`' Rev. 1:5. And again the apostle saith,
'`We have redemption through the blood of Christ,
the forgiveness of sins.`' Eph. 1:7. And the apostle saith,
'`being justified by the blood of Christ.`' Rom. 5:9.
So you may see the doctrine of the holy apostles of Christ
was not to preach up the body of death and sins to the grave,
as Satan`'s ministers do, but how they were washed, and cleansed,
and justified by the blood of Christ.

The Lord said, Noah was a just and perfect man in his generation, and walked with God.
The Lord said to Abraham, '`I am God Almighty, walk before me,
and be thou perfect.`' Gen. 6:9. and 17:1
And the Lord said unto Israel, '`Thou shalt be perfect with the Lord thy God.`'
Duet. 18:13.
The Lord said Job was a perfect and upright man,
one that feared God and eschewed evil. Job 1:1. and 2:3.
Solomon saith,
'`The path of the just is a shining light which shines more and
more unto the perfect day.`' Prov. 4:18. And Christ saith,
'`Be ye therefore perfect,
even as your Father which is in heaven is perfect.`' Matt. 5:48.
Zacharias and his wife Elizabeth were both righteous before God,
and walked in all the commandments and ordinances of the Lord blameless. Luke 1:5-6.
The apostle saith to the Corinthians,
'`That ye be perfectly joined together in the same mind
and in the same judgment.`' And again the apostle saith,
'`We speak wisdom among them that are perfect.`' 1 Cor. 1:10. and 2:6.
And the apostle saith,
'`Let us cleanse ourselves from all filthiness of the flesh and spirit,
perfecting holiness in the fear of the Lord`' 2 Cor.
7:1. And the apostle saith to the Corinthians,
'`We wish even your perfection.
Finally brethren, farewell, be ye perfect, be of good comfort, be of one mind,`'
etc. 2 Cor. 13:9. 11.
And James saith, '`Let patience have its perfect work,
that ye may be perfect and entire, wanting nothing.`' James 1:4. And the apostle said,
strong meat belongeth to them that are of full age, or perfect;
let us go on to perfection. Heb. 5:14. and 6:1.
And Peter saith to the saints,
'`The God of all grace who hath called us into his eternal glory by Christ Jesus,
after that ye have suffered awhile, make you perfect, establish,
strengthen and settle you.`' 1 Pet. 5:10. And the apostle saith,
'`that the man of God may be perfect,`' etc. 2 Tim. 3:17.
And you may see in Eph. 4. how Christ
gives gifts unto men '`for the work of the ministry,
and for the perfecting of the saints, and for the edifying of the body of Christ,
till we all come into the unity of the faith, and the knowledge of the son of God,
unto a perfect man,
unto the measure of the stature of the fulness of Christ.`'
Eph. 4. to the 14. And again the apostle saith,
'`Christ in you the hope of glory, whom we preach,
warning every man and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus.`' Col. 1:27-28.

Now here it may be clearly seen, God, and Christ, and his prophets and apostles,
call and encourage to perfection, and justify the perfect.
And the work of the ministers of Christ was and is
to present every man perfect in Christ Jesus,
and bring them to a perfect man.
So here it is clearly seen from Genesis to Revelations, never did God, the prophets,
Christ, nor his apostles preach up a doctrine to people,
and tell them they should not be perfect,
but they must carry a body of sin and death whilst they are upon the earth to the grave.
So is it not clear here that all such are Satan`'s ministers and preachers,
and not God`'s nor Christ`'s, that say people must be imperfect,
and have a body of sin and death whilst upon the earth,
which body of sin and imperfection came into man and woman by disobeying God,
and hearkening to the devil, and obeying him,
and so his ministers preach up the devil`'s works, which Christ came to destroy,
and Christ through death destroys death, and the devil, the power of death,
and bruises the serpent`'s head.

Now the scriptures that the ministers of Satan used to bring for a body of sin,
and a body of death and imperfection are as follow.
David was a sinner, cry they,
and cried out of his sins and iniquities after he had committed adultery and murder,
etc. but he confessed his sins and transgressions,
and said,`' My sins are ever before me.`' Ps. 51. throughout.
But David said, '`As far as the cast is from the west, so far hath he, (to wit,
the Lord,) removed our transgressions from us;`' and said, '`Bless the Lord O my soul,
and all that is within me, bless his holy name;`' and again, '`Bless the Lord, O my soul,
and forget not all his benefits, who hath forgiven all thine iniquities,
who hath healed all thy diseases,`' etc.
Ps. 103:1-3. 11, 12.

Now here you may see Satan`'s ministers and preachers take David`'s sins and transgressions,
which Satan tempted him to run out into;
but how the Lord had forgiven David all his iniquities, and healed all his diseases,
and his transgressions were removed as far as the east was from the west,
and how that all within him praised God.
These scriptures are against Satan and his ministers, and are not for their purpose.

And again, Satan`'s ministers say, that the most righteous man that is,
sins seven times a day;
and this both priests and professors have affirmed to my face that it was scripture,
but I searched the scriptures, and never found any such scripture.
But Solomon saith, '`Lay not wait, O wicked man, against the dwellings of the righteous.
Spoil not his resting place; for a just man falleth seven times, and rises again,
but the wicked shall fall into mischief.`' Prov.
24:15-16. Now here is no seven times a day;
and though David did fall, yet he rose again and was healed,
and his iniquities were removed, as far as the east is from the west.

But hear what Solomon saith concerning the Church: '`Thou art all fair, my love,
there is no spot in thee.`' Song. 3:7. '`Open to me my sister, my love, my dove,
my undefiled.`' Song. 5:7. So Solomon is far from saying, she had a body of death,
and a body of sin.
And David saith, '`Mark the perfect man, and behold the upright,
for the end of that man is peace.`' Ps. 37:37. But Satan and
his ministers will not allow there is any perfect man and upright,
to be marked; for the devil who is blind, hath blinded his ministers,
and they can neither behold nor mark the perfect man.

And another scripture Satan`'s ministers bring, of Peter`'s saying to Christ,
'`though I should die with thee,
yet I would not deny thee;`' and after Peter was examined, he cursed and swore,
and said he did not know the man, namely Christ. Matt. 26:25.
70 to the end.
But in the 75th verse, you may see Peter repented of what he had said, and wept bitterly,
And Christ said unto Peter,
'`When thou art converted strengthen thy brethren.`' Luke 22:23. So
it seems that Peter was not wholly converted when he denied Christ.
And Satan`'s messengers say, that Judas was partaker of the ministry,
who carried the bag and betrayed Christ.
He was like unto the devil, who abode not in the truth;
and is not covetous Judas`'s bag entailed upon all Satan`'s ministers and messengers?
And do not they hold it by entail?
And are they not worse than Judas?
For Judas put in his bag what people gave him,
but had not a law or staff to compel people to put in his bag, nor cast any into prison,
as Satan`'s ministers and messengers do, and have done.

And again Satan`'s messengers and ministers say, Paul cried out and said,
'`O wretched man that I am! who shall deliver me
from this body of death?`' And he was in a warfare,
and therefore people must be in a warfare, and carry a body of death,
and a body of sin about with them as long as they live, to the grave,
and there is no overcoming nor no victory here.
But in this, Satan`'s messengers and ministers wrong the apostle`'s words,
and do not take them all; for though he cried out,
who shall deliver him from that body of death and sin;
yet he thanks God through Jesus Christ our Lord, and saith,
'`The law of the spirit of life which is in Christ Jesus,
hath made me free from the law of sin and death.`' Mark,
he said Christ Jesus had made him free, as in Rom. 7:24-25. and viii.
1, 2. And said, there was '`no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the spirit.`' And again, he saith,
'`Thanks be to God,
who hath given us the victory through our Lord Jesus
Christ.`' 1 Cor. 15:57. And again,
he saith, '`They that be in Christ are new creatures.`' And again, the apostle saith,
'`I have fought the good fight, I have finished my course,
I have kept the faith.`' 2 Tim. 4:7.

Then the apostle, if he had fought the good fight, he was not fighting;
and having kept the faith he kept the victory; for faith is the victory.
And John saith, '`This is the victory that overcomes the world,
even our faith.`' 1 John 5:4. And Jesus Christ is the author and finisher of our faith. Heb. 12:2.
So here you may see the apostle had fought
and kept the faith of Christ which is the victory.
So he was not always fighting and warring as Satan`'s messengers would have it,
who was a liar from the beginning.
For the apostle said, '`I am crucified with Christ, nevertheless I live, (mark,
live,) yet not I, but Christ liveth in me; and the life which I now live in the flesh,
I live by the faith of the son of God, who loved me,
and gave himself for me.`' Gal. 2:20.

And the apostle saith, '`That ye put off the former conversation, the old man,
which is corrupt according to the deceitful lusts, and that ye put on the new man,
which after God is created in righteousness, (now this new creation,
the devil`'s messengers and ministers are ignorant of,) and true holiness.`' Eph.
4:22. 24. Now these were the ministers of Christ that preached this true doctrine;
but the ministers and messengers of Satan say, they must carry the old man,
which is corrupt, with his deceitful lusts, while they are upon the earth,
to the grave with them.
And again the apostle saith to the church of Christ, the Colossians,
'`Seeing that ye have put off the old man with his deeds, and have put on the new man,
which is renewed in knowledge after the image of God that created him;
and ye are complete in him,
(viz. Christ,) which is the head of all principality and power:
in whom also ye are circumcised with the circumcision made without hands,
in putting off the body of the sins of the flesh,
by the circumcision of Christ.`' Col. 2:10-11. and iii.
9, 10.

And here you may see the true christians were circumcised with the spirit,
and they had put off the old man with his deeds, and his body of death,
and put on the new man, which is after God, etc. and were complete in Christ their head,
while they were upon the earth, before they went to the grave.
But Satan and his messengers, and ministers, and hearers say,
that they must carry the body of death and sins of the flesh,
with the old man and his deeds, while they are upon the earth; but I say,
by disobeying God, and hearkening to the serpent`'s teaching,
this body of death and sins of the flesh, with the old man, with his deceitful lusts,
came into man and woman who had none before.
And now the devil and his teachers say,
they must carry this body of death and sins of the flesh, and the old man and his lusts,
as long as they live upon the earth, till they go to the grave;
but Christ`'s ministers say to the believers in Christ,
they had put off the old man and his deeds, and the body of the sins of the flesh,
with the circumcision of the spirit, while they are upon the earth;
but the circumcision of Christ with his holy spirit,
Satan and his ministers with his unclean spirit, deny while they are upon the earth.
And therefore the devil`'s messengers and hearers,
do carry a body of death and the sins of the flesh,
and the old man with his deceitful lusts as long as they live, to the grave;
and this is the devil`'s doctrine, and not Christ`'s nor his apostles.

And the apostle said to the believers in Christ,
'`We have redemption through his blood.`' Col.
1:14. And again the apostle saith to the Ephesians,
'`We have redemption through Christ`'s blood,
the forgiveness of our sins.`' Eph. 1:7. And the Lord saith,
'`their sins and iniquities I will remember no more.`' Heb. 8:12.
And the apostle said to the Jews,
'`Repent ye therefore, and be converted,
that your sins may be blotted out.`' Acts 3:19. So if people do repent and be converted,
then their sins are blotted out, then they are not like to carry their body of death,
nor read their sins, when they are forgiven and blotted out;
and this is a contrary doctrine to the devil and his ministers, who say,
they must carry this body of death and sins to the grave.

John said,
the devil '`sinned from the beginning,`' and '`he that committeth sin is of the devil;
and for this purpose the son of God is made manifest
that he might destroy the works of the devil,
and Christ was manifest to take away our sins, and in him is no sin,
and whosoever abideth in him sinneth not,
and whosoever is born of God doth not commit sin, for his seed remains in him,
and he cannot sin, because he is born of God;
in this the children of God are manifest from the
children of the devil.`' 1 John 3:5 to the 11th.

Now concerning the devil`'s ministers, messengers, and teachers, who say,
there is no victory nor overcoming on this side the grave.
But John saith in his General Epistle to the church of Christ,
'`I have written to you young men, because you are strong,
and the word of God abideth in you,
and you have overcome the wicked one.`' 1 John 2:14.
This is contrary to the devil`'s ministers and messengers,
that say, there is no overcoming sin, which is of the wicked one, on this side the grave.
But John, a minister of God, writes to the young men in Christ, and tells them,
they had overcome the wicked one, and that was whilst they were upon the earth,
and could read his epistle.
And again, the apostle John saith, '`whosoever is born of God overcometh the world,
and this is the victory that overcomes the world,
even our faith;`' this John said to the believers
in Christ while they were upon the earth,
and if they overcome the world, then they overcome the devil, the god of the world. 1 John 5:4.
And '`who is he that overcometh the world,
but he that believeth that Jesus is the son of God?
and he that believeth is born of God.`' Here you may see the devil`'s messengers,
ministers, hearers, and teachers, are not in this true belief,
born of God that overcomes the wicked world, neither are they in the true faith,
which Christ is the author of, which overcometh the world,
and gives the victory over the world which lieth in wickedness,
and is the shield that quenches all the fiery darts of Satan. 1 John 4:5. 19.
And John saith to the followers of Christ,
'`Little children ye have overcome them, (to wit, Satan and his ministers,)
because greater is he that is in you,
than he that is in the world.`' 1 John 4:3-4. And again,
John saith to the believers in Christ, '`Every man that hath this hope, purifies himself,
even as he is pure.`' 1 John 3:3. Col. 1:27.

Now Satan`'s messengers and ministers deny this hope
that purifieth people while they are upon the earth,
as Christ is pure; they are in the hope of the hypocrite and a dead faith,
as in James 2:17-18. 20. And though they may call themselves believers,
and say there is one God; the devils believe and tremble,
so may a vain man in a dead faith say,
in which there is not victory over the body of death and sin whilst upon the earth,
as they say.

And Christ saith, '`Verily, verily I say unto you, he that heareth my word,
and believeth on him that sent me, hath everlasting life,
and shall not come into condemnation,
but is passed from death unto life.`' John 5:24. Now if
the believers in Christ are passed from death to life,
and have everlasting life, and shall not come into condemnation,
then they are not like to carry the body of death,
if they be passed from the death in Adam, to the life in Christ.
But Satan`'s priests, ministers, and teachers cannot be the true believers, that say,
they must carry a body of death to the grave; such remain under condemnation,
(in the death in Adam,) by the light of Christ. John 5:24.
And Christ saith, I am the light of the world,
and whosoever believeth on me, shall not abide in darkness.
Now if the believers in Christ do not abide in darkness,
then they do not abide under the devil the power of darkness.
For John saith, he that believeth overcomes the world, then the world`'s god. John 12:46.
and 1 John 5:5. Again John saith,
'`We know that ye are passed from death to life.`' 1 John
3:14. This was while they were upon the earth;
then they were passed from the body of death, and the devil the power of death,
which Satan`'s ministers, priests, and teachers plead for,
which first came in by hearkening to Satan`'s teaching, and forsaking God`'s teaching.
And by hearkening to God and Christ`'s teaching, they came out of death and darkness,
and put off the body of death and sins of the flesh,
and put off the old man with his deeds while they were upon the earth,
and put on the new man, which after God is created in righteousness and true holiness,
whilst upon the earth. Eph. 4:24.
And so they that be in Christ are new creatures,
and old things are passed away.
And again the apostle saith to the saints,
'`Seeing that ye have put off the old man with his deeds, and put on the new man,
which is renewed in knowledge after the image of him that created
him.`' Col. 3:10-9. And this was while they were upon the earth.
And so it is clear the outward body is not the body of death, and body of sin,
nor the old man.
For after the old man is crucified, and the body of death and sins of the flesh put off,
the saints bodies are the members of Christ, and '`the temple of the holy ghost,
and the temple of the living God, as God hath said, I will dwell in them,
and walk in them, and I will be their God,
and they shall be my people.`' And this was while they were upon the earth,
before they went to the grave. Rom. 6:6.
1 Cor. 6:15. 19. 2 Cor. 6:16.

And the apostle saith,
but now Christ '`once in the end of the world hath appeared to
put away sin by the sacrifice of himself,`' and Christ said,
I come to do the will of God,
by which will we are sanctified through the offering
of the body of Jesus Christ once for all;
for by one offering he hath perfected forever them that are sanctified. Hebrews 9:26.
and 10:9,10,14.

Now here you may see Christ putteth away sin, and we are sanctified by his will,
in and through the offering of his body once for all,
and by his one offering he hath perfected forever them that are sanctified.
But such as do not believe to have their sins put away,
and to be sanctified and perfected here,
they do not believe in Christ the one sacrifice and offering.
It is a general saying by the priests, teachers, and professors,
that none keep the commands of God.
So in this they would make the commands of God grievous, who say,
none can live and keep the commandments of God.
The Lord saith,
'`Thou shalt have no other gods besides me,`' (to wit,) who is your Maker and Creator.
And what! cannot you live, but you must make gods and graven images,
or likenesses of things in heaven, or in the earth, or in the waters,
and bow down to them?
And cannot you live, but you must dishonour your father and mother?
And cannot you live, but you must take the name of the Lord God in vain?
And cannot you live, but you must kill, steal, commit adultery,
and bear false witness against your neighbour?
And cannot you live, but you must covet your neighbour`'s house, and his wife,
and his man servant, maid servant, ox, or ass?

The young man in the gospel told Christ,
that from his youth he had kept the commands of God,
though he could not sell all and give to the poor, and follow Christ,
who is the end of the law for righteousness`' sake to every one that believes. Matt. 19:20-21.
Rom. 10:4. Zachariah and his wife '`were both righteous,
walking in all the commandments and ordinances of God blameless.`'
Surely they kept the commandments and ordinances of the Lord then,
if they walked in them blameless, as before.
And the apostle said to the Galatians, all '`the law is fulfilled in one word,
even in this,
thou shalt love thy neighbour as thyself.`' Gal. 5:14.
And the apostle saith to the Romans,
owe no man any thing, but to love one another;
for he that loves another fulfilleth the law, for he that loveth God,
will not make any other gods.
Love will not take God`'s name in vain.
Love will not dishonour father nor mother.
Love doth not kill, steal, commit adultery, nor bear false witness.
Love doth not covet neighbour`'s house, wife, servant, ox, or ass.
He that loves his neighbour as himself, this love works no evil to his neighbour;
therefore, love is the fulfilling of the law. Rom. 13:10-9.
Now they that be out of this love of God,
say they cannot keep the commands of God,
but they do not say they cannot keep the commands of the devil,
they are easy enough to them; and the old world, the earth was corrupted by them,
and the earth was filled with violence,
and all flesh had corrupted its way upon the earth. Gen. 6:11-12.
And the Lord brought a flood upon them and destroyed them,
saving Noah and his family.
And the Lord turned the cities of Sodom and Gomorrah into ashes, and delivered just Lot,
whose soul was vexed from day to day with their unlawful deeds, as in 2 Pet. 2:2. 6,
7, 8. Mark, their unlawful deeds; those unlawful deeds were easy enough for them,
though the deeds of the law were hard enough for them, as they say now.
And you may see in Rev. 19:2. the judgment of
the great whore which did corrupt the earth,
which is called the mystery of Babylon, or confusion, the mother of harlots,
and abomination of the earth. Rev. 17:5.

Now this whore, or false church, which is whored from Christ, and corrupteth the earth,
which rideth upon the beast, and sitteth upon the prophets, multitudes, nations,
and tongues, which are called waters.
And is not this whore, or false church, called a cage of unclean birds?
And hath not she her teachers among the nations, peoples, multitudes, and tongues?
And did not the dragon give his power to the beast, that this whore,
the false church rideth upon, like Balaam upon his ass?
And is it like for the beast, (Rev. 16:13) in the dragon`'s power, which the whore,
the false church rideth upon?
or for the false prophet, or the unclean spirits,
(Rev. 17:8. 15.) like frogs that went out of
the mouth of the beast and the false prophet?
or for the peoples, multitudes, nations, and tongues,
that the whore that corrupteth the earth sitteth upon, and hath made them like waters;
I say, is it like for all these to own perfection,
and overcome the old man and his lusts, and the body of death and sins of the flesh,
whilst on this side the grave?
And though all these do make war against the Lamb and the saints, the Lamb, I say,
that takes away the sins of the world, he shall and will overcome them,
for he is Lord of lords, and King of kings,
and they that are with him are called chosen and faithful.
And will not the whore, and the beast in the dragon`'s power, false prophets,
and all their followers, say, that none can keep the law of God and his commands;
but they will not say, they cannot keep the beast`'s, whore`'s, dragon`'s,
and false prophets`'. The apostle saith, the law is spiritual, just, and good, etc.
And David saith, the law is light;
and how are men like to keep the law of God which is spiritual,
and be whored from the spirit of God, and hate his light, and be out of the truth,
and do it not?
And is not the end of the whore, beast, false prophet, dragon, or devil,
and all his followers, to be consumed and destroyed with fire,
as the old world was with water?
And the beast, false prophet, and whore, or false church,
that take their power from the devil, that abode not in the truth, and set up a worship,
and compel others to that worship,
and to drink that whore`'s cup that is whored from the truth;
they that worship God in his spirit and truth as Christ commands, and hath set up,
cannot drink the whore`'s cup, nor cannot bow to the dragon, the beast`'s worship,
which hath been set up by the dragon`'s power, which is out of the truth.

Job saith, no man knows the price of wisdom, it cannot be gotten for gold nor silver,
neither shall silver be weighed for the price thereof;
for it cannot be valued with the gold of Ophir, or with the precious onyx, or sapphire,
or pearls, or coral, or rubies.
Now all these and many other things may be purchased with the price of gold and silver;
and all the histories, libraries,
and all the books and authors in the world may be purchased with gold and silver;
and all the sciences and natural arts,
these may all be purchased and learned for gold and silver;
and that which the world calls philosophy, and its books,
may all be purchased for gold and silver; and all outward knowledge, wisdom,
and understanding, which they may get a great deal of knowledge from this tree,
without life and the true heavenly wisdom, and be like unto the fowls of the air,
and the lion`'s whelps, and the fierce lions, and ravenous beasts;
but no unclean thing comes in the way and path of the heavenly wisdom,
which cannot be gotten nor bought for gold nor silver, nor precious stones, nor jewels,
nor fine gold, for man knows not the price of it.
Job 28. Isa. 35. And unto man, God said, '`Behold the fear of the Lord, that is wisdom,
and to depart from evil is understanding.`' So it is clear,
they that fear God and depart from evil, shall have both wisdom and understanding,
though they have not gone to the schools and colleges
to learn the priests`' seven arts and sciences,
and without the great shops of old histories and authors, and the world`'s philosophy,
which things may puff up the fowls of the air, and the vultures and ravenous beasts,
with the outward tree of knowledge without life.
The Lord with,
'`Every man is brutish by his knowledge.`'
And again he saith, '`Every man is brutish in his knowledge;
the pastors are become brutish, and have not sought the Lord.`'
Jeremiah 10:14. 21. and 57:17.

Here you may see what men get by their outward knowledge;
for when Adam and Eve fed upon the tree of knowledge,
then the lamb was slain in them from the foundation of the world.
And when the Lamb Christ was manifest in the flesh,
then they that were in this outward brutish knowledge and wisdom below,
crucified Christ outwardly without the gates of Jerusalem.
And after, when christianity was spread up and down the world,
and many got an outward form of christianity and denied the power,
and got into this brutish outward knowledge and wisdom below,
they crucified to themselves Christ afresh,
as in Hebrews 6:6. And the beast and whore was,
and is in this brutish knowledge and wisdom below, that killed the Lord`'s witnesses,
and the martyrs, and compelled all the world to worship, and to drink the whore`'s cup,
and all did drink and worship, but whose names are written in the Lamb`'s book of life,
slain from the foundation of the world. Rev. 13:8.
And the beast in the dragon`'s power, with the seven heads and ten horns,
which the whore or false church rideth upon, as Balaam did upon his ass.
And this whore, or false church, sitteth, or rideth upon peoples, multitudes, nations,
and tongues, which are called waters.
So she makes peoples, multitudes, nations, and tongues, like Balaam`'s ass,
and these ten horns of the beast are ten kings, which received power from the dragon;
and these ten kings, or ten horns, should hate the whore, or false church,
and make her desolate, and burn her with fire, which is the great city,
which reigns over the kings of the earth.
So these ten kings that hate the whore, the false church, and burn her with fire,
will not then suffer her to reign over them, and ride upon them like Balaam upon his ass.
Rev. 17:1 to the end.
For glory to the Lord God forever,
Christ reigns in all his true believers and followers,
who is the prince of life and peace, who was before the devil, beast, whore,
and his followers were, and will be when they are all gone.

And John said, '`There appeared a wonder in heaven, a great red dragon,
having seven heads and ten horns, and seven crowns upon his head,`' the old serpent,
the devil, and Satan.
Was not this a proud devil?
And his tail drew the third part of the stars from heaven,
(had not these been some stars in the church?) and cast them to the earth.
These stars were lights in the night; but he was cast out of heaven,
and persecuted the woman the true church, which had the moon under her feet.
And John saw a beast rise out of the sea, having seven heads and ten horns,
and upon his heads ten crowns; and was not this a proud beast?
And the dragon gave the beast his power, and his seat, and great authority,
and the world worshipped this proud dragon and the beast,
and the beast opened his mouth in the devil`'s power, in blasphemy against God,
to blaspheme his name, tabernacle, and them that dwelt in heaven,
after the dragon was east out of heaven.
So here you may see some dwelt in heaven,
and sat in the heavenly places in Christ Jesus. Rev. 12:13.
And John said, '`I saw a woman sit upon a scarlet coloured beast,
full of names of blasphemy, having seven heads and ten horns,`' and this woman,
the false church, that rid upon the beast, was arrayed in purple, scarlet colour,
decked with gold, precious stones and pearls, having a golden cup in her hand,
full of abomination and filthiness of her fornication,
and upon her forehead was a name written, Mystery Babylon, mother of harlots,
who was drunk with the blood of the saints and martyrs of Jesus.
Was not this a proud whore, the false church, that rideth upon the beast,
that rose out of the sea, in the devil`'s seat, power and authority?
Must not this proud whore, the false church, be burnt, and this proud devil, dragon,
and beast, and their followers go into perdition, and the lake of fire?
Rev. 17. and 19:20. and 20:10.
And the Lamb and the saints will have the victory.
Hallelujah.

And Job saith, '`Though after my skin worms destroy this body,
yet in my flesh shall I see God.`' Job 19:26. Satan`'s messengers say,
that must not be in this life, but in another world;
but afterwards Job said unto the Lord, '`I have heard of thee by the hearing of the ear,
but now mine eye seeth thee.`' Job 42:5. And this
was while Job was alive upon the earth.
Another scripture Satan`'s messengers bring against perfection,
'`Shall mortal man be more just than God?
shall a man be more pure than his maker?
He charges his angels with folly.`' Job 4:17-18. Again,
'`How can he be clean that is born of a woman?`' Job 25:4. And again,
'`What is man that he should be clean,
and he that is born of a woman should be righteous?`' Job 15:14-15.
Now these were not Job`'s words,
but Eliphas`' the Temanite, which contended against Job, as in Job 4:1. 17, 18. and xv.
14, 15. and Bildad the Shuhite`'s words that contended against Job,
as in Job 25:5. For God said Job was '`a perfect and upright man,
that feared God and eschewed evil.`' Job 1:8. and 2:3.
So these were the words with which Job`'s miserable comforters contended against Job,
which Satan`'s ministers bring against perfection.

And John saw '`an hundred and forty-four thousand,
having their father`'s name written in their foreheads, which were not defiled,
which followed the lamb, in whose mouth was found no guile,
for they were without fault before the throne of God.`' And besides,
John said he saw a great multitude, which no man could number, of all nations, kindreds,
and tongues, stand before the throne, and before the lamb, clothed with white robes,
and palms in their hands, crying with a loud voice, saying,
salvation unto our God which sitteth upon the throne, and unto the Lamb.
Rev. 7:5 to the 11th. and 14:1 to the 6th.

Now the messengers and ministers of Satan do not see these,
but he is a minister of Christ that sees these holy people that follow the Lamb,
that was without fault or guile.

And Peter saith in his General Epistle to the church of Christ,
'`Ye are a chosen generation, a holy nation, built up a spiritual house,
a holy royal priesthood to offer up spiritual sacrifices,
acceptable to God by Jesus Christ,`' as in 1 Pet. 2:5. 8, 9.
Then surely these have put off the body of death, and sins of the flesh,
and the old man with his deceitful lusts.

[.inline]
=== II. Priests the chief promoters of persecution, in the prophets, Christ, and the apostles`' days, and since, and now the Lord is opening the eyes of people`'s understandings, that they will not let them ride upon them, as Balaam in his error upon his ass, for his wages of unrighteousness.
Here you may see, how the priests in all ages turned against the righteous,
and persecuted and killed them.
See how Cain the priest was full of wrath, and killed righteous Abel in the field,
and what was the end of Cain. Gen. 4:5. 8.

And you may see how Korah and his company, and Dathan and Abiram opposed Moses and Aaron,
and how the Lord did consume them (as in Num. 16. chap.
throughout) in their rebellion; and what became of old Eli that reproved his two sons,
but did not restrain them, as you may see in 1 Sam. 4. chap.
throughout; and the badness of the priests you may see in the second chapter.
And how the Lord sent Samuel the child to admonish old Eli,
for not restraining his sons from their wickedness;
and for the wickedness of the priests, God brought his great judgment upon Israel;
and see how the man of God cried against Jeroboam and his altar and priests. 1 Kings 12:13.

And did not his prophecy come upon them, in 2 Chron. 23:17-18. chap.
You may see what priests they ordained, 2 Chron. 11:15.
And you may see what work Josiah made with Balaam`'s altars,
and his idols and priests, how he purged the land of them.
2 Chron. 34:3 to 9. And you may see what work Jehu made with Baal`'s worshippers,
prophets and priests. 2 Kings 10.
And the Lord commanded Jehu.
And it had been well for him and his children,
if they had not followed the sins of Jeroboam, who made Israel to sin,
but walked in the law of God.
And you may see how Manasses made Israel to sin by rearing up altars for Balaam,
for which cause the Lord carried them into captivity.
2 Chron. 33:1 to 13. And see what work Josiah made with Manasses`' images, altars,
and priests. 2 Kings 23.
And how did Ahab and Jezabel with all her Baal`'s
priests and prophets persecute the Lord`'s people,
and what became of them in the end, see 1 Kings 21.
and 2 Kings 9.
And you may see what Isaiah saith,
because of the wickedness of the priests and others who had defiled the earth,
therefore the Lord would empty the land of them.
Isaiah 24. to the 7th. And also declares,
how the priests and prophets have erred through wine and strong drink,
for all tables are full of vomits and filthiness, so that there is no place clean. Isaiah 28:7-8.

And again, see how Isaiah crieth against the shepherds and watchmen,
and calls them greedy dumb dogs that can never have enough,
that fill themselves with wine and strong drink; they all look to their own way,
every one for their gain, from their quarter.
May not this practice be applied to many of the shepherds,
priests and watchmen now of our times?
as in Isaiah 56:10-12. And see how Jeremiah testifies against the priests,
and how the Lord had made him a brazen wall, and an iron pillar against the priests, etc.
Jer. 1:18. 2:8.
And Jeremiah saith, '`Every one is given to covetousness;
from the prophet to the priest,
every one deals falsely.`' Jer. 6:13. And again Jeremiah saith,
'`A wonderful horrible thing is committed in the land, the prophets prophesy falsely,
and the priests bear rule by their means,
and my people love to have it so.`' Jer. 5:30-31. and 8:10, 11.

And did not Pashur son of Immer the high priest, strike Jeremiah,
and put him in the stocks, for declaring the truth to him? Jer. 20:1.
And did not Jeremiah tell them,
that both prophets and priests were profane?
Read Jer. 23:11 to the end.
And did not the priests and the prophets and the princes say,
that Jeremiah was worthy to die? Jer. 26:11.
Here you may see the priests had a hand in the persecution of Jeremiah.

And the Lord sent Ezekiel to cry against the priests, and said,
they had violated his law, and profaned his holy things,
and put no difference betwixt the holy and profane. Ezek. 22:25-26. 28.
and how the prophets, etc. were like roaring lions,
and daubed with untempered mortar,
and how the Lord sent Ezekiel to prophesy against the shepherds of Israel,
and how he would gather his people from among them,
and set one shepherd over them to feed them.
Ezek. 34. throughout; and was not that Christ?
And see how the Lord sent Hosea to cry against the priest, saying,
'`I will also reject thee, and thou shalt be no priest to me,
seeing thou hast also forgot the law of thy God.`' So like priest, like people;
and the Lord saith he will punish them for their ways. Hosea 4:6. 9.
And have not the priests now forgot the law and command of Christ,
'`freely you have received freely give,`' and to keep the gospel without charge?
And '`as a troop of robbers wait for a man,
so the company of priests murder in the way by consent,
for they commit lewdness.`' Hosea 6:9. Amaziah the priest of Bethel,
sent to Jeroboam king of Israel,
and told him that Amos the prophet had conspired against him,
and forbade him to prophesy any more in the king`'s chapel.
Amos 7:10 to 17. So here the priest was a lying informer against Amos,
for speaking the truth.
And you may see how Nehemiah cries to the Lord,
because the priests had defiled the priesthood. Neh. 13:29.
And said, neither our kings, princes, priests,
nor our fathers had kept the law of God. Neh. 9:32. 34.
And Micah said they built up '`Zion with blood,
and Jerusalem with iniquity; the heads thereof judge for reward,
the priests thereof teach for hire,
and the prophets thereof divine for money,`' and yet they would lean upon the Lord,
and say, is not the Lord among us, and no evil can come upon us?
'`Therefore shall Zion for your sakes be ploughed up like a field,
and Jerusalem shall become on heaps.`' And so it was,
and is not this the state of Christendom?
Have not the hireling priests and the prophets in Christendom brought it all on heaps?

And you may see what the Lord saith in Malachi, '`And now, O ye priests,
this commandment is for you; if ye will not hear, and if ye will not lay to heart,
to give glory unto my name, saith the Lord of hosts, I will even send a curse upon you,
and I will curse your blessings; yea, I have cursed them already,
because ye do not lay it to heart.
Behold, I will corrupt your seed, and spread dung upon their faces,
even the dung of your solemn feasts,
etc. and ye shall know that I have sent this commandment unto you,
saith the Lord of hosts.`' Mal. 2:1-4. May not the priests
of our times apply this commandment to themselves?

And the Lord said, '`I will cut off the remnant of Baal from Jerusalem,
and the names of the Chemarims with the priests;
the prophets are light and treacherous persons,
their priests have polluted the sanctuary,
they have done violence to the law.`' Zeph. 1:4, and 3:4.

Here you may see all along in the Old Testament the wickedness of the priests and prophets,
and how the Lord sent his holy prophets to declare against them;
and by their wicked lives and means, often the Jews went into captivity,
and the Lord`'s prophets suffered.

And you may see how the chief priests, scribes, and elders,
consulted to put Christ to death. Matt. 26:34.
And in Matt. 27. the chief priests and elders
took counsel together against Jesus to put him to death.
And did not Judas that betrayed Christ,
sell him for thirty pieces of silver unto the chief priests, etc.
Matt. 26:14-15. and 27:1-2. and Mark 14:10.

And did not the chief priests and elders persuade
the multitude that they should ask of Pilate,
Barrabas, and crucify Jesus?
And when they were crucifying Christ, did not the chief priests mock him? Mark 15:30-31.
And when they had crucified Christ, and watched his sepulchre;
and after Christ was risen, some of the watchmen came into the city,
and showed unto the chief priests all things that were done concerning Christ;
and did not the Jews`' chief priests take counsel, and gave large money to the soldiers,
to say that his disciples stole him away by night, as they slept,
as in Matt. 28. And this saying and lie is commonly
reported among the Jews to this day.

So here you may see how busy the priests and chief priests
with their company were to crucify and murder the just.
And Judas that betrayed Christ, came with a great multitude with swords and staves,
from the chief priests and elders of the people. Matt. 26:47.
Mark 14:43. Here you may see how
eager the priests were to destroy the just,
and gave money to tell lies.

And did not the high priests and the kindred of the high priests,
gather together against the apostles for preaching Christ after he was risen?
And did not they threaten them,
and charge them not to speak at all in the name of Jesus? Acts 4:6. 18.
And did not the high priests rise against the apostles with indignation,
and put them into the common prison, but the Lord delivered them,
as in Acts 5:17-19. And when that the chief priests
took counsel together to put the apostles to death,
Gamaliel`'s counsel stopped them, as in Acts 5:33 to the end.

And did not the high priest examine Stephen in his counsel when he was put to death?
Acts 6:15. and 7:1.
And did not Paul say he had authority from the
chief priests to shut up the saints in prison,
and when that they were put to death he gave his voice against them. Acts 8:3. and 26:10.
And did not Ananias the high priest, with the elders,
and a certain orator named Tertullus, inform the governor Felix against Paul,
and called Paul a pestilent fellow, and a mover of sedition,
and sought to take away his life, as in Acts 24. to the end.
And how the high priests and chief of the Jews informed Festus against Paul,
and desired that he would send for him to Jerusalem,
lying in wait by the way to kill him. Acts 25:1-3.
And after Saul was converted, the Jews took counsel together to kill him,
in Acts 9:9. For he was going with his packet of letters
from the high priests to persecute the christians at Damascus,
and before he got thither he was converted; and when he got to Damascus,
he preached Christ there, and they set watch at the gates of Damascus to kill him,
but he escaped their hands.
Acts 9:1 to the 31st. And have not the priests had the chiefest hand
in imprisoning and persecuting God`'s people since the apostles`' days,
both among Protestants and Papists;
let the scripture prove their persecuting and imprisoning
and putting to death in the prophets,
Christ, and the apostles`' days.
But since their days, amongst Papists and Protestants,
the histories and the jails prove the priests stirring up to the persecuting,
imprisoning, banishing, and putting to death of God`'s people.
And have not the Jesuits and the priests been like the frogs,
the unclean spirits that have gone out of the mouth of the beast and false prophet? Rev. 16:13-14.

But have the priests, either Papists or Protestants, come so far as Cain or Balaam?
For these heard God`'s voice, and Balaam went astray, and forsook the right way,
and loved the wages of unrighteousness, but Balaam`'s ass rebuked him for his iniquity,
and forbade the madness of him. 2 Pet. 2:15-16.
Jude 11.

And have not most of the people both among Protestants and Papists, been like dumb asses,
and their priests, like or darker than Balaam, ride upon them,
who say they never heard the voice of God nor Christ,
and the people durst not reprove them for their iniquity, error, and madness,
and their wages of unrighteousness?
Christ saith to his ministers, '`freely you have received,
freely give,`' and they laboured '`to keep the gospel without
charge.`' And now the Lord hath opened many mouths,
that they will not let Balaam`'s priests and prophets ride upon them,
nor follow Balaam`'s error and way, nor give him the wages of unrighteousness,
though he loves it; though the Balaams be angry and cause them to be cast into prison,
and their goods spoiled; but declare against the covetous greedy Balaams,
and their wages of unrighteousness, and follow Christ their way, who saith,
freely you have received, freely give;
and will not let Baal`'s priests ride upon them any more.
And the Lord hath made his people a holy royal priesthood,
to offer up spiritual sacrifices to God by Jesus Christ.
1 Pet. 2:5 to the 10th.

And how often have the priests generally turned within this hundred years, to queen Mary,
and from queen Mary to queen Elizabeth, and to king James,
and then to Oliver and Richard Cromwell,
and called them Caleb and Joshua that led them into the promised land?
But was it not in the tithes, offerings, augmentations, and glebe lands?
And then when king Charles II. came in, did not they most of them turn to common prayer,
and persecute them that did not?
And when king James came to the throne, what did many of the priests and bishops do then,
with their passive obedience and non-resistance?
Were not many of them posting to Rome, their mother church, as they call it,
(let all the sober judge,) and forsaking Jerusalem, which is above, which is free,
the mother of all true Christians? Gal. 4:26.

[.inline]
=== III. And what a scabbed flock the bishops and priests have, which should oversee them; and how the magistrates are troubled with them, to send them to the jails, and transport them.

I desire the bishops and the priests to look into their bishoprics and parishes,
and see what scabbed flocks they have, lying, swearing, cursing, damning,
and whore houses, and play houses, to corrupt youth and people;
and they may see abundance of theft, murder, and whoredom,
and how the jails are filled up and down the nation with thieves and unclean persons;
that many are transported yearly out of England, Scotland and Ireland, into America,
of their scabbed flock, which the bishops and priests are to watch over, look after,
and cure, in all their bishoprics and parsonages; who are hired and take their tithes,
easter-reckonings, and midsummer-dues, to watch over them, and look after them,
and yet let them go astray; yea, they are so greedy,
they take tithes of them that are not of their church, and spoil the goods of many,
and cast them into the jails, because they will not pay them,
and cannot own them to be ministers of the gospel.

And let the bishops and the priests look into all the sessions, assizes, and courts,
and see how the justices of the peace,
and the judges are troubled with some of their scabbed flock, which they should oversee,
and watch over, and keep from the occasion of the magistrate`'s sword.
What stewards are you, and how do you watch over them,
that you may present their souls to God, to whom you must give an account,
as you pretend?
And are not you ashamed, both bishops, priests, and teachers,
to hear that so many of your flock are brought before the sessions and assizes,
and how the jails are filled with them, and how many are hanged yearly,
and how many are transported beyond the seas for their wickedness?
And are not these members of your church,
which you are to oversee and have the charge over?
And pray, consider, are you not like them that do not profit the people at all,
but seek you own profit, and your own hire, and tithes, and your gain from your quarter?
And therefore, is it not time for you either to amend and look better to your flocks,
or give over your pretence?
Read Isa. 56. to the end. Jer. 5:29-31. and 23. chap. throughout,
and Micah 3:10-12. and Ezek. 13. chap. throughout.

Now if you priests, bishops, and shepherds, had an outward shepherd that you hired,
and let your sheep be so scabbed and corrupted, and that they should run so astray,
and he not watch over them nor oversee them better, would not you soon turn him away?
I pray you look into your bishoprics and parishes, and make application upon yourselves,
as before.

[.inline]
=== IV. How no persecutor upon the earth, for faith, worship, and religion, can exercise a good conscience towards God and man, until they be converted.

The apostle Paul saith, after he became a christian, and confessed Christ Jesus,
I exercised myself to have always a good conscience,
void of offence toward God and toward men.
This he declared before Felix, the governor,
when he was accused by the high priests and elders of the Jews,
which said Paul was a pestilent fellow,
and a mover of sedition among all the Jews throughout the world,
and a ringleader of the sect of the Nazarenes. Acts 24:15-16.

Now here you may see when, the apostle Paul was turned from the Jews`' temple worships,
and the priests that took tithes.
For the apostle Paul said, when he was brought before king Agrippa, '`Verily,
I thought with myself, that I ought to do many things contrary to Jesus of Nazareth,
which things I also did in Jerusalem; and many of the saints I did shut up in prison,
having received authority from the chief priests; and when they were put to death,
I gave my voice against them.
And I punished them often in every synagogue, and compelled them to blaspheme;
and being exceeding mad against them, I persecuted them even unto strange cities.
Whereupon as I went to Damascus, with authority and commission from the chief priests,
that if I found any of that way,
(viz. of them that believed in Christ,) whether they were men or women,
I might bring them bound to Jerusalem.`' And as he was coming near unto Damascus,
Jesus Christ did convert him; and after a while he preached Christ in Damascus,
where he was going to persecute, and confounded the Jews,
and the Jews took counsel to kill him,
as in Acts 9:1 to the 28th. and 26:8,9,10,11,12. and 24:16.

Now while Paul was persecuting and imprisoning,
and consenting to the death of the followers of Christ; and having his packet of letters,
and his authority and commission from the chief priests,
to go up and down and persecute the saints the believers in Christ, from city to city;
then he was exercising an evil conscience towards Christ and men; for Christ saith,
'`Saul, Saul, why persecutest thou me?
It is hard for thee to kick against the pricks.`' So in
this it is clear he was exercising an evil conscience,
whilst he was a persecutor; and the Jews, priests and elders also,
which gave him letters, commission and authority, to persecute Christ in his members.
And so likewise, all the Protestant and Papist priests, which call themselves christians,
that have, and do persecute and imprison people for their faith and a good conscience,
they have, and are persecuting Christ in his members;
such always have and do exercise an evil conscience against Christ in his members.
For the Jews and chief priests,
would have Christ crucified without the gates of Jerusalem, and cried Matt. 17:25,
'`O let his blood be upon them and their children;`' in
that they exercised an evil conscience towards Christ.
And after Christ was risen, the chief priests and elders, and Saul,
imprisoned and persecuted Christ in his members; and so have the Papists,
and many of the Protestant priests, because they do not conform.
And therefore have they imprisoned and persecuted to death,
and spoiled the goods of many;
in this they have exercised an evil conscience towards Christ and his people.
For Saul, nor any other, did not,
nor do any exercise a good conscience towards God and man,
until that they were and are converted to Christ Jesus to follow him,
and to forsake the Jewish priests, and the tithes, and temple worships,
and all other outward temple worships, and priests that take tithes,
and persecute others that will not conform and give them their tithes, etc.
For Christ saith, he came not to destroy men`'s lives, but to save them; and saith,
love one another, and love enemies, and pray for them that persecute you; and,
freely you have received, freely give.
And they that keep the commands of Christ and his gospel without charge,
are always exercising a good conscience towards God, in obeying,
serving and worshipping him, and a good conscience toward men, in that which is just,
righteous, honest, and true; to do unto all men, as they would have others do unto them,
according to the royal law of God.
And so it is clear, that no persecutor and spoiler of people`'s goods,
in all ages from Cain, both in the days of the prophets, Christ, and the apostles,
and since, to this day, did, nor has,
nor can exercise a good conscience towards God and man.
'`For he that is born of the flesh,
will persecute him that is born of the spirit.`' That persecuting birth of the flesh,
is not like to exercise a good conscience towards God or man;
he that is born of the spirit, is born of God;
for the birth of the flesh doth not do unto all men, as it would have them do unto it;
and is not like to exercise a good conscience towards God,
when it persecutes his spiritual birth, though they go in Cain`'s, Korah`'s,
Balaam`'s and Jezabel`'s way, in the wolves`' and sheep`'s clothing.
All these may make an outward profession of christianity, and deny the power thereof;
but such are to be turned away from.
And is it like that they that go in these evil ways,
should exercise a good conscience towards God and man?
And also such false teachers that make merchandise of people,
that make the gospel chargeable; and such priests and teachers that divine for money,
and preach for hire, and bear rule by their means, and preach for handfuls of barley,
and pieces of bread, and deceive the people.
Such doings the Lord was against, and such shepherds which are called greedy dumb dogs,
which can never have enough, seeking for their gain from their quarter,
etc. and looking after their own ways, and not after the Lord`'s; such, God`'s prophets,
Christ and the apostles testified against,
and such as these were not like to exercise a good conscience towards God and man.

And when Balak sent messengers to Balaam, to curse the children of Israel, the Lord said,
thou shalt not go with them, thou shalt not curse them, for they are blessed.
And Balak sent other messengers to Balaam, and said, I will promote thee to great honour,
and will do whatever thou sayest unto me.
And after, Balaam went, and God`'s anger was kindled against him, because he went,
and the angel of the Lord stood in the way as he rode upon his ass, and he smote his ass,
and his ass fell down, and the Lord opened the mouth of the ass,
and it reproved Balaam And was not Balaam going to be promoted by Balak,
and to receive his wages of unrighteousness?
And did not Balaam cause Balak to build altars, and offer up rams and oxen?
But for all Balak`'s and Balaam`'s offerings, that he might curse the children of Israel,
instead of that, the Lord made him to bless them.
So Balaam angered Balak, that he missed his honour, and his wages of unrighteousness,
though he loved it. Num. 22. 23. 24. chap. 2 Pet. 2:15-16.

And do not our spiritual Balaam`'s that ride upon the dumb asses,
so love the wages of unrighteousness, that they would destroy all the Lord`'s people,
if the Lord did not restrain them?
But was not Balaam at last slain with the sword?
as in Num. 31:8. And will not all the spiritual Balaams, think you,
that are erred from the spirit of God, be slain by the sword of the spirit,
the word of God, who love honour, and the wages of unrighteousness?
But the Lord is opening the mouths of his people by his spirit,
which have been like dumb asses, and they are throwing off Balaam and his error, honour,
and wages.
That makes the spiritual Balaams angry, that they are ready to kill them,
as old Balaam would have done his ass, but the Lord restrains them, as he did him.
Glory over all to the Lord forever;
so that his holy people can sing hallelujah over them, and learn of Christ,
who is meek and low in heart, and in him they have found rest for their souls, who saith,
'`Freely you have received, freely give.`'

[.inline]
=== V+++.+++ And the bad example of Gehazi and Simon Magus, to be shunned.
Naaman, captain of the host of Assyria, he was a leper, and had a leprosy,
and he came to Elisha to be healed, and he bid him go and wash in Jordan seven times,
and his flesh should come again, and he should be clean.
And he went into Jordan, and washed seven times,
and came again to Elisha and was made well.
And Naaman would have given Elisha great gifts, but Elisha utterly denied them,
and would receive none, but bid him go in peace.
But Gehazi, the servant of Elisha, went after Naaman, and said,
My master Elisha hath sent me, saying, behold, even now there be come to me,
from Mount Ephraim, two young men, of the sons of the prophets; give them, I pray thee,
a talent of silver, and two changes of garments.
And Naaman gave him two talents of silver, and two changes of garments.
And Gehazi, Elisha`'s servant, took them to himself, and bestowed them in the house,
and came to Elisha.
And Elisha asked him whence he came?
And he said, his servant went no where; but Elisha said unto him,
went not my heart with thee when the man turned again in his chariot to meet thee?
And Elisha said to Gehazi, The leprosy of Naaman shall cleave unto thee,
and unto thy seed forever; and he went from Elisha a leper,
as you may see in 2 Kings v. throughout.

And are not all the covetous teachers in the world of the seed of Gehazi?
Yea, are not many of them grown worse than he,
who will take money and the clothes from such that do not own them,
and if they will not give them means or rewards, they will cast them in prison,
and spoil their goods.
Is not this covetous leprosy seen upon them, who are of the seed and spirit of Gehazi?
For he went with a lie in his mouth to Naaman, (as though Elisha had sent him,
but he did not,) who gave him two talents of silver, and two changes of garments,
which Elisha would not receive from him.
Here Elisha, freely what he had received of God, freely gave it again,
according to Christ`'s doctrine,
though Gehazi abused Elisha in going unto Naaman in his name.
But he that took the reward for doing nothing, he had the leprosy with it.
And is not this the condition of all the covetous teachers,
that be of the spirit and seed of Gehazi, or rather worse,
that will take money and rewards by force, of them they do nothing for?
And such are not of the spirit and seed of Christ, who saith, freely you have received,
freely give.
And are not these things written for our admonishment,
and that we should not follow the examples of that covetous seed and spirit,
but follow Christ, and obey his command?

And what think you of Simon Magus, who believed and was baptized?
And when he saw that through laying on the hands of the apostles,
the holy ghost was given, this Simon Magus, offered the apostles money, saying,
'`Give me also this power, that on whomsoever I lay hands,
they may also receive the holy ghost.
But Peter said unto him, Thy money perish with thee,
because thou hast thought that the gift of God may be purchased with money.
Thou hast neither part nor lot in this matter,
for thy heart is not right in the sight of God.
Repent therefore of this thy wickedness, and pray God,
if perhaps the thought of thine heart may be forgiven thee;
for I perceive thou art in the gall of bitterness,
and in the bond of iniquity.`' Acts 8:17th to 24th.

Now here it is clear, that all the teachers in Christendom,
that think the gift of God can be purchased with money, their hearts are wrong,
and they are in the gall of bitterness and bond of iniquity,
and their money will perish with them,
and they have neither lot nor part in the gift of God;
though they may pretend themselves to be believers, and to be baptized,
they know not the baptism of the holy ghost.
All the teachers in Christendom may apply Simon Magus`'s condition to themselves,
that have gotten their natural tongues, arts, and sciences, and old authors,
and histories, and make people believe that they have the gift of God,
and so they are called to the ministry, when they have neither part nor lot in it,
but do daily show forth the gall of bitterness,
and bond of iniquity to people that will not give them means for their gift,
which they sell to people; but Christ who gives gifts to his people, saith,
freely you have received, freely give.

[.inline]
=== VI. Concerning the priests and professors, that say they must do as the priests say, not as they do.

The priests and professors used to bring this scripture, the saying of Christ,
that '`the scribes and Pharisees sit in Moses`'s seat or chair:
all therefore whatsoever they bid you observe, that observe and do;
but do not ye after their works, for they say, and do not.
For they bind heavy burdens and grievous to be borne, and lay them on men`'s shoulders,
but will not move them with one of their fingers.
But all their works they do to be seen of men,`' etc.
They love the uppermost rooms at feasts, and the chief seats at synagogues,
and greeting in markets, and to be called of men rabbi, and master.
And Christ pronounces eight woes against them, and calls them hypocrites, and fools,
and blind guides, who made clean the outside of the cup, and of the platter,
but within full of extortion and excess; and called them whited sepulchres,
which indeed appeared beautiful outwardly, but within full of dead men`'s bones,
and of all uncleanness; who also outwardly appeared righteous unto men,
but '`within ye are full of hypocrisy and iniquity; ye serpents, ye generation of vipers,
how can ye escape the damnation of hell?`' Matt. 23. to the end.
These are very suitable scriptures for the priests and professors to apply to themselves.

Now the priests and professors say, though they be as bad as scribes and Pharisees,
they must do as they say, and not as they do.
And another scripture the priests and professors bring, how Christ said,
that the scribes and Pharisees paid tithes of mint, anise, and cummin,
and have omitted the weightier matters of the law, judgment, mercy, and faith. Matt. 23:23-24.
These ought ye to have done, and not to leave the others undone:
ye blind guides, which strain at a gnat, and swallow a camel.

Now the Jews were to hear the scribes and Pharisees, which wrote the law,
and read the law; so they were to do the law which Christ came to fulfill,
and they were to pay their tithes of mint, anise, and cummin,
which were commanded by the law, and not to neglect judgment, mercy, and faith,
those weightier matters of the law; for tithes, offerings, and priests,
were commanded and held up by the law, and this law served till the seed Christ came,
as in Gal. 3:19. And when Christ was come, not to break the law, but to fulfill it;
and when he was offered up as a sacrifice once for all, he changed the priesthood,
and changed the law, and disannulled the commandment, that gave them tithes,
and abolished the priesthood with its daily sacrifice and offerings,
with the sacrifice of himself once for them all; when Christ had healed or cleansed any,
before he was offered up, he bid them go to the priests,
and offer a sacrifice for their cleansing,
but when Christ by one offering had perfected forever them that are sanctified,
as in Heb. 10:14. Christ ended all the offerings, by offering up himself,
and hath abolished the priesthood, and thrown down Moses`' chair or seat,
and is the end of the law for righteousness`' sake, to every one that believes.
And when Christ sent forth his disciples into all nations, to preach the gospel,
after he was risen, and gave them power, he did not bid them take tithes of mint, anise,
and cummin, etc. but said, Freely you have received, freely give.
And when the apostles had either healed any sick, or cleansed any lepers,
they did not bid them go to the priest and offer a sacrifice for their cleansing,
as Christ had done, in the days of his flesh,
but that was the law which Christ bid them do and observe, before he was offered up;
and Christ is the end of the law for righteousness`' sake to every one that believes.
And the apostle saith, after Christ was offered up,
that no flesh is justified by the deeds of the law;
for the apostles knew that Christ by the offering up of himself,
had ended and abolished the Jewish priesthood, and their offerings,
and ended the daily sacrifices.

And now for the priests and professors to bring this scripture,
though their priests be as bad as whited walls, and painted sepulchres, and vipers,
and serpents, and in all those evils that the scribes and Pharisees were in;
yet whatever they bid us do, that we must do and observe, but not do as they do,
for they say and do not.
But I say, Christ saith we must not follow the inward ravening wolves,
and the false prophets that come in sheep`'s clothing, for Christ bids beware of them. Matt. 7:15.
And the apostle saith, that he that hath the form of godliness,
but denies the power thereof, from such turn away. 2 Tim. 3:5.

But now if you say, that Paul said some preached Christ even of envy and strife,
etc. supposing to add afflictions to my bonds, etc.
And the apostle said, whether in pretence or truth Christ is preached,
I therein do rejoice, yea, and I will rejoice. Phil. 1:15-18.

And now you that bring these scriptures for men that be in strife and envy,
you are very dark concerning the times the apostle speaks of;
for you must consider how all were hated that professed the name of Christ,
and how the Jews said to Paul at Rome concerning this sect,
'`we know that everywhere it is spoken against,`' namely, them that believe in Christ. Acts 28:22.

And so the apostle did rejoice, if envious contentious men,
and men of strife did preach Christ, so that his name was spread abroad at that time.
But when Christ`'s name was spread abroad, and many came into a form of godliness,
but denying the power thereof, the apostle bids the church of Christ turn away from such,
as in '`2 Tim. 3:5. And the apostle Paul saith, brethren be followers together of me,
and mark them which walk so as ye have us for an example;
for many walk of whom I have told you often, and now tell you even weeping,
that they are the enemies of the cross of Christ, whose end is destruction,
whose God is their belly, and whose glory is in their shame, who mind earthly things.
And let the teachers in Christendom apply these scriptures
to themselves who mind earthly things. Phil. 3:17-19.
So here you may see the apostle doth not rejoice at such as these,
but weeps.
And also you may see, James, Peter, Jude, John, in their epistles,
and John in his revelations, reproved such as forsook Christ the right way,
and did not walk in it, or that erred from the faith.
And the apostle saith, '`There are many unruly vain talkers and deceivers,
etc. whose mouth must be stopped; teaching things that they ought not,
for lucre`'s sake.`' Tit. 1:10. And so the apostle doth
not rejoice at such as preach Christ out of envy and strife,
which added afflictions to his bonds; but such that had the form of godliness,
denying the power thereof, they were to turn away from.

[.inline]
=== VII. To all you priests, teachers, and professors, that mock and scoff at the motions of the spirit.

All you priests, teachers, and professors,
that mock and scoff at the motions and movings of the spirit of God in his people; yea,
your very children as well as yourselves will mock and scoff,
and say the spirit moves you,
which doth demonstrate that you are all erred from the spirit of God,
and to the motions and movings of it you have stopped your ears, and closed your eyes,
and so know not the things of God, for no man knows the things of God,
but by the spirit of God.
And so you that scoff and mock at the movings of the spirit of God, I say unto you,
you had never had the scriptures, neither priests, teachers, nor professors,
if the spirit of God had not moved the holy men to give them forth,
which by your own wills and private interpretations you make a trade of; yea,
one of the greatest merchandise and trades in Christendom,
to get money by the scriptures which holy men of God spake forth,
as they were moved by the holy ghost; and they came not by the will of man,
neither are they of any private interpretation.
And now you that mock and scoff at the motions of the holy ghost or spirit,
and yet make merchandise and trade of the scriptures,
that holy men of God spake forth as they were moved by the holy ghost, as before;
and in this you do show forth your error and apostacy from the holy spirit in
them that gave forth the scriptures as they were moved by the holy ghost.
And so you are very unlike to be led into all truth by the holy ghost,
or to pray or have any fellowship in the holy ghost that deny it,
and say you have it not, as the church of Christ, and the apostles had it in their days.

Now you bishops, priests, professors and others, that call yourselves Protestants,
and the reformed church, I do entreat you to consider these things as follow,
by which we have suffered imprisonments, and spoiling of our goods,
who are the true Protestants, and reformed church.

We have greatly suffered both imprisonments, and the spoiling of our goods,
because we could not observe your holy days, as you call them,
and for opening of our shops we have been much assaulted by the rude multitudes,
and sometimes our goods have been spoiled, and we cast into prison; especially,
because we could not observe that you call Christmas day.
Now was not Christmas day set up by the Papists, and also your Candlemas, and Michaelmas,
and Childermas, and Lammas, were not all these masses set up by the Papists,
and not by Christ and his apostles?
and are they not their relics of Popery?
And did the apostles command that the christians should observe Easter,
the Jews`' passover, or Whitsuntide, the Jews`' Pentecost, in the gospel day,
in the new covenant and testament?

And again, did Christ and the apostles command the christians to observe circumcision,
and the epiphany, and the purification of Mary, St. Matthew`'s day, Ash Wednesday,
the Annunciation, Palm Sunday, Good Friday, Mark the evangelist`'s day,
Philip and Jacob`'s day, and Holy Thursday, St. Barnabas, Trinity Sunday,
John Baptist`'s day, Peter and James`'s day, Bartholomew`'s day, Simon and Jude`'s day,
All Saints`' day, Andrew`'s day, Thomas`'s day, Stephen`'s day,
John the evangelist`'s day, and Innocents`' day, and Paul`'s day of his conversion,
and that they should observe all these days in their several months and years;
where did ever Christ and his apostles give the church command to observe these days,
times, months and years?
for the apostle Paul saith,
'`I have not shunned to declare unto you all the counsel of God.`' Acts 20:27.

Now, where did the apostle in all the counsel of God declare to the church of Christ,
that they should observe these days before mentioned, in their times, months, and years?
Nay, was not the apostle Paul so far from bidding the church of Christ observe Christ`'s day,
or any of the apostles`', or his own, etc. that he said, '`O ye foolish Galatians,
who hath bewitched you, that ye should not obey the truth,`' etc.
And also he saith.
'`Are ye so foolish having begun in the spirit, are ye now made perfect by the flesh?
But now after that ye have known God, or rather are known of God,
how turn you again to the weak and beggarly elements, or rudiments,
whereunto ye desire again to be brought into bondage?
Ye observe days and months, and times and years;`' the apostle said,
'`I am afraid of you, lest I have bestowed upon you labour in vain.`'
Gal. 3:1. 3, 4. 9, 10, 11.

Now let all Protestants, and professors of the reformed churches consider these things,
and the apostle`'s labour, and these foolish Galatians,
that went into these weak elements and rudiments that brought them into bondage,
that had begun in the spirit, and thought to have been made perfect in the flesh;
and therefore pray consider, you that set up these days, for people to observe.

And do not you say to your people in your steeple houses,
'`Six days thou shalt labour, and do all that thou hast to do,`' etc.
And then do not you stand up in the same steeple houses,
and bid your holy days and mass days; and have your paritors,
and other officers to trouble people for opening their shops on many of those days,
which you have no command from God, nor Christ, nor his apostles, to keep or observe.
But all you Protestants, consider, is not God, and Christ,
and his truth and name more dishonoured and blasphemed upon your holy days,
as you call them, than any other day in the week,
when all are let loose to sports and plays, and all manner of vain pastimes,
as they call it, and drunkenness, looseness, lightness, wantonness,
oaths and profaneness, out of the very bounds of sobriety, modesty,
and christian moderation, which should be showed forth by all the true christians?
And they that turned again to the weak elements and rudiments,
whereunto they were brought into bondage, in their observing days, months, times,
and years, this was not a christian gospel practice in the new covenant;
but a gospel and christian testimony and judgment, against them that did do so.
And the apostle saith,
'`Stand fast therefore in your liberty wherewith Christ hath made you free,
and be not entangled again with the yoke of bondage,`' as some of the Galatians were:
also going back into the Jews circumcision, besides their observing of days, times,
months, and years; and so it could not be the spirit of God that led into such things.
For the apostle calls them fools, and saith, '`Who hath bewitched you,
that ye begun in the spirit,
and think to be made perfect in the flesh.`' And
therefore I desire you in the spirit of meekness,
that you may reform, and be reformed out of these weak elements and rudiments,
which brought people into bondage in the apostles`' days;
and therefore they must needs bring people into bondage now;
for which you have no command from Christ, nor his apostles,
but their testimony against them:
and therefore I desire you may be reformed by the spirit of God into the primitive reformation,
the apostles`' testimony, practice, and judgment, and to stand fast in the liberty,
where Christ makes free out of bondage,
and not to force others to that which brings into bondage.

And ye know the great observation on May-day,
a great deal of vanity and looseness is acted upon that day;
and was not the ground of observing May-day, and the may-poles, from Flora,
a strumpet at Rome?

Is not this a heathenish custom,
and not fit to be practised amongst them that profess the gospel day of Christ,
and his new covenant, and the true christians that are followers of Christ?
And seeing you have no such command from Christ, nor his apostles,
to follow any such vain custom and tradition, like your forefathers the heathen,
but not the forefathers the apostles and the church of Christ in the primitive times.

And did ever the Jews in the old testament observe Adam and Eve`'s days, or Noah`'s day,
who by faith built the ark, who was a just man, and perfect in his generation,
and walked with God, or Enoch`'s day, who walked with God. Gen. 5:22. and 6:9.

And did ever the Jews observe Abraham`'s day, or Isaac`'s, or Jacob`'s, or Moses`',
or Aaron`'s, or Joshua`'s, or any of the prophets of God`'s days?
Though Abraham saw the day of Christ, and rejoiced,
yet he did not say it was an outward day that he saw and observed,
nor call it Christmas day, which you have from the pope, and not from Abraham, Christ,
nor his apostles.
As dark and as blind as the Jews were,
yet we do not hear that they observed any of the days before mentioned,
in the old testament.
But Herod who observed his birthday, and made a feast to his lords and high captains,
etc. and when the daughter of Herodias came in, and danced, and pleased Herod,
that he said, he would give her whatsoever she would ask,
and her mother counselled her to ask John Baptist`'s head,
which was given her in a charger; and here are their fruits of their dancings,
and their bloody feast, to slay the just, though we do not hear that Herod, nor any,
either in the old or new testament, had any command either from God or Christ so to do.
Neither have the christians from Christ or his apostles to observe their days,
birthdays, or others:
for the apostle said to the Galatians that were turned
again to the weak elements and rudiments,
whereunto they had been brought into bondage, who observed days, and months, and times,
and years, they did not obey the truth in that,
before whose eyes Jesus Christ had been evidently set forth, and crucified amongst them.
And do not they crucify Christ among them now, that observe days, months, times,
and years?
And do not they persecute and spoil the goods of them that obey the truth,
and imprison them that cannot observe their days, times, months, and years?
Look over all Christendom, I pray, both Protestants and Papists,
and see if that birth born of the flesh,
hath not been persecuting that birth born of the spirit. Gal. 4:29.

And where did ever Christ or the apostles command lent to be kept, and Shrove-Tuesday,
and many more holy days, as you call them, that might be mentioned?
And is not there a great deal of rudeness and wickedness
committed on that day you call Shrove-Tuesday,
throughout the land?
And is it not time for you to reform from these heathenish and Popish customs,
by the spirit of sobriety and modesty, and that your moderation may appear,
that you are christians in nature and deed.
And I pray be not offended with such true christians,
as cannot in conscience observe such things.
And had you not the names that you give unto most of your days and months,
from the heathen and Papists, and not from the prophets, Christ, nor his apostles?
And were not the old pagan Saxons in their idolatry,
the first that brought in the names of the days after this manner,
and these called christians have retained them to this day.

The first day of the week they worshipped the idol of the sun, from whence came Sunday.
The second day of the week they worshipped the moon, from whence came Moonday, or Monday.
The third day they worshipped the idol of the planets, which they called Tuisco,
from whence came Tuesday.
And from the idol Woden, came Wednesday.
And from the idol Thor, came Thursday.
And from the idol Friga, came Friday.
And from the idol Seater, came Saturday.
And the heathens called Mars the god of battle,
and from thence they called the first month March.
And Venus they called the goddess of love and beauty,
and from thence they called the second month April.
And Maia, a heathen goddess called Flora,
Flora and Cloris were called the goddesses of flowers;
and unto Maia the heathen idolators used to sacrifice;
from thence was the third month called May.
And upon the first day of the same month, they used to keep Floralia,
feasts to the goddesses of the flowers, (viz.) Flora and Cloris.
And Flora was a strumpet in Rome, that used on the first day of that month,
to set up a may-pole before her door, to entice her lovers;
from whence came may-poles to be first observed.
And from the heathen goddess Juno, is the fourth month called June.
And in honour to Julius Caesar, a Roman emperor, is the fifth month called July.
And the sixth month took its name August, in honour of Augustus Caesar.
And September, October, November, and December, are called from the Latines.
And one Janus a king of Italy, was for his wisdom pictured with two faces,
whom they honoured as a God; and from this name Janus,
was the eleventh month called January.
And Saturnus, Pluto, Februs, were called the gods of hell,
whom the heathens said had the rule of the evil spirits there; and from Pluto or Febris,
was the twelfth month called February.

And now, are not all these contrary to the holy scripture of truth,
and the command of the Lord?
Who saith, '`In all things that I have said unto you be circumspect,
and make no mention of the names of other gods,
neither let them be heard out of your mouths.`' Ex. 23:13. And further the Lord said,
'`They shall overthrow their altars, (namely, the heathens,) and break their pillars,
and burn their groves with fire;
and you shall hew down their graven images of their gods,
and destroy the name of them out of that place;
these are the statutes and judgments which ye shall observe to do,
in the land which the Lord God of thy fathers gives thee to possess
all the days that ye live upon the earth.`' Duet. 12:1-3.

And now consider, all you that profess christianity, both Papists and Protestants,
do ye not make mention of the names of the heathen gods,
and are they not heard out of your mouths, as before?
Nay, are they not put in your Almanacs,
that your very children may make mention of the heathen gods,
and to be heard out of their mouths?
Also is not this contrary to the law and command of God to the Jews?
And therefore it should be below them, that profess the gospel in the new covenant,
when the apostle saith, '`Every one that names the name of Jesus,
let them depart from iniquity;`' and the Jews were to teach their children,
to observe and do the law of God in the old testament;
much more should the christians teach their children virtue, and the law of love, life,
and faith, in the new testament.

And we entreat you to consider, we have suffered many reproaches, and sometimes blows,
and had many evil names given to us, and called us ill-bred clowns and unmannerly,
to make us odious in the sight of men, because we would not give the title of rabbi,
and master, to the priests; which is against the command of Christ,
who said to his disciples, ministers, and teachers that he sent forth,
'`Be ye not called of men rabbi, rabbi, or master, for one is your master even Christ,
and ye are all brethren.`' Matt. 23:7-8.

Now we do not read that either the twelve, or seventy disciples,
did disobey the command of Christ.
For where do you read in the new testament of those titles, Mr. Matthew, Mr. Mark,
Mr. Luke, or Mr. John, or any other of the apostles?
Or where do you read that any of the apostles, when they writ one to another,
or the church to them, that they called one another masters?
For James was far off from titling himself master.
For James saith, '`My brethren, be not many masters,
knowing that we shall receive the greater condemnation.`' So he calleth them brethren,
(James 1:1) and not masters.
And Christ did not teach his ministers and disciples clownishness, and unmannerliness,
when he said, Be ye not called of men masters, for one is your master, even Christ,
and ye are all brethren.

And as for all your titles of bachelor of arts, master of arts,
and your several sorts of garments, as surplices, lawn-sleeves, hoods, caps, girdles,
etc. have you any example for these things from Christ and his apostles?
Or a command from Christ and his apostles, for your practice in holding up these things,
with your rails, altars, organs, and crosses?
Or had you them from the Papists,
seeing that we find no command nor example in the
new testament for them in the apostles`' days?
And therefore, it is good to be reformed out of all the relics of heathenism and Popery,
and come to the cross of Christ, the power of God, and the fine linen,
the righteousness of Christ.

And we have had many hard thoughts upon us, and hard words also,
because we cannot give the title of lord bishops, and call them gracious lords.
And we never read in the scriptures, when the apostles wrote to the bishops and elders,
and said to Timothy and Titus, which were bishops,
that they gave them the titles of lords, or gracious lords.
And Christ said unto his disciples,
'`The Gentiles exercise lordship and authority over them,
and are called gracious lords or benefactors; but ye shall not be so;
but he that is greatest among you, let him be as the younger, and he that is chief,
as he that doth serve.`' Luke 22:25-26.

And here you may see that Christ never set up the title of lord in his church,
among his disciples, but he told them, he had appointed them a kingdom,
etc. which was above the glory of the world, and their titles.
And Peter writes to the elders, and exhorts them, who said, I am also an elder,
etc. and bids the elders '`Feed the flock of God, which is among you, not by constraint,
but willingly; not for filthy lucre, but of a ready mind;
neither as being lords over God`'s heritage, but as being examples to the flock.
And when the chief shepherd shall appear, you may receive a crown of glory,
that fadeth not away.`' 1 Pet. 5:1-4.

Now here it may be seen that Peter who was an elder,
he doth not call himself lord or master, nor them lords or masters.
But they were to be examples to the flock, and to mind Christ their chief shepherd,
and to receive the crown of glory of Christ when he should appear.

And the pope that saith he sits in Peter`'s chair, he is far off Peter`'s doctrine,
who takes the title of lord,
and he is not like to receive a crown of glory of Christ the chief shepherd,
who hath got an outward worldly triple crown upon his head already,
of the glory of the world that will fade away; which we never read in the scriptures,
that Peter had either called himself lord or master,
or gave those titles to other elders, though he was an elder.
But take away the filthy lucre from either the pope, bishops, and priests,
and their titles of lords, etc. and you shall have but a few overseers.
And therefore, we do entreat you that you call yourselves Protestants,
to reform from all these titles which you have from the pope, and Papists,
and not from Christ and his apostles.

And another thing the teachers and professors have taken offence against us,
because we use the single language, thou to one, and you to many;
which is according to their own teaching books, accidence, and grammar,
and the translation of the Bible, which they are taught at school,
and was the practice of the holy men of God, as may be seen in the scriptures of truth;
they familiarly used thou to one, and you to many.
And therefore we thought it very strange,
that they would neither suffer us to practice what they taught us in grammar, accidence,
and Bible, nor practice it themselves.
And for the practice of theirs, of saying you to one,
and cannot endure to have thee and thou said to them,
they neither have it from their accidence, grammar, nor Bible;
then is it not from the pope, and their own pride?
And I desire the Lord to open your, eyes, and give you an understanding,
and a tender heart, who profess yourselves Protestants,
that with the spiritual armour and weapons, you may subdue atheism, heathenism,
and the relics of Popery, and not deny the Popish religion in words,
and hold up some of the relics; and that all that profess themselves ministers,
may obey Christ`'s command, Freely you have received, freely give,
and to covet no man`'s gold, silver, nor apparel, but to keep the gospel without charge,
as the apostles did.
For tithes and offerings are not Christ`'s gospel ministers`' maintainance.
For were ever tithes or offerings paid in England by any christians,
till after Austin the monk came in?
And so I desire you may be reformed by the spirit of Christ, into the same practice,
and spirit, and power, the church of Christ were in in the apostles`' days.
From him who hath a tender conscience toward God,
and hath been a great sufferer for Christ, and the true reformation,
and desires your reformation, good, and prosperity here,
and your eternal happiness hereafter.

G+++.+++ F.

[.inline]
=== VIII. A reformation from Heathenism and Popery, etc. concerning the observation of days, months, times, and years, etc. the beggarly elements of the world.

The apostle saith to the Galatians, '`For when we were children,
we were in bondage under the elements of the world; but now after that ye have known God,
or rather are known of God, how turn ye back again to weak and beggarly elements,
whereunto ye desire again to be brought into bondage?
Ye observe days, months, times, and years.
I am afraid of you, lest I have bestowed upon you labour in vain.`'
Gal. 4:3. 9, 10, 11.

Now here you may see, observing of the Jewish days, months, times, and years,
which they were commanded of God, the apostle saith, when they were children,
they were in bondage under.
And the apostle calls them weak beggarly elements of the world,
that some christians were turned back to, which formerly they had been under.
And therefore how is Christendom since the apostles`' days,
turned back into these weak beggarly elements of the world, in observing days, times,
months, etc. which God never commanded?
And not only in bondage themselves by observing of them, but bring others into bondage,
and imprison and persecute such that will not observe them, and shut up their shops.
And hath not the apostle bestowed all his labour in vain upon such?
And is not God and Christ more dishonoured upon those
times and days which they call holy days,
than any other times and days in the week?
For do not you see there is more vanity, wickedness, looseness, profaneness,
and taking God`'s and Christ`'s name in vain, upon those you call holy days,
which the apostle calls beggarly elements, than any other days of the week?
You that be in bondage under these weak beggarly elements of the world,
are not you spoiled through philosophy and vain deceit, after the traditions of men,
after the rudiments or elements of the world, and not after Christ?
And did not the apostle warn the church of Christ of such things?
And said, '`If you be dead with Christ from the rudiments or elements of the world; why,
as though living in the world, are ye subject to ordinances?`' viz. of the world.
And the apostle saith, '`Touch not, taste not, handle not;
which all are to perish with the using,
after the commandments and doctrines of men.`' So the church of Christ were not to touch,
taste, nor handle the rudiments, elements, traditions, ordinances, commandments,
nor doctrines of the world.
And therefore they suffered because they would not taste them, nor handle them.
But they that are not dead with Christ, do not hold him their head, they are not like,
but in the world set up many heads, and taste, touch, and handle the traditions,
rudiments, elements, ordinances, commandments, and doctrines of the world,
commanded by worldly men, which are not after Christ; and such are in bondage under them.
Col. 2. the chapter throughout.
And such persecute them that will not observe their days and rudiments,
etc. but see the day of Christ, and observe it.

And the apostle said,
'`I am sold under sin,`' Rom. 7:14. and '`to be carnally minded is death,
because the carnal mind is enmity with God; it is not subject to the law of God,
neither indeed can it be.`' Rom. 8:6-7. And again the apostle saith,
'`God hath concluded all both Jews and Gentiles in unbelief,
that he might have mercy upon all.`' Rom. 11:27. And again he saith,
'`all are concluded under sin,
that the promise by the faith of Jesus Christ might
be given to them that believed.`' Gal. 3:22

How that death past over all men, and all died in Adam.
This is the unconverted estate in the death, sold and concluded under sin and unbelief;
then sin and death is over the unconverted.
Now Christ shedding his blood,
and tasting death for every man that is dead in sins and trespasses,
and so died for their sins, and is a propitiation for the sins of the whole world,
and is a quickening spirit, and is the one mediator between God and man,
who gave himself a ransom for all, and would have all to be saved,
and come to the knowledge of the truth, that will make them free,
that they might live in Christ, and follow him that makes an end of sin,
and finisheth transgression, and brings in everlasting righteousness;
who died for their sins, and destroys the devil and his works,
and bruises the serpent`'s head, who brought in sin, and through death destroys death,
and the devil the power of death, and so is risen for their justification.
And all that he hath quickened and made alive by Christ, as the apostle saith,
he hath raised us up together,
and made us to sit together in the heavenly places in Christ Jesus. Eph. 2:6.
And so God by Christ reconcileth all things unto himself, by him, I say,
whether they be things in earth, or things in heaven;
and the gospel of life and salvation is preached to every creature under heaven. Col. 1:23.

And the apostle saith to the Hebrews,
in the first covenant they had ordinances of divine services, of ceremonies,
and a worldly sanctuary; which covenant stood only in meats, drinks, and divers washings,
and carnal ordinances, and ceremonies imposed on the Jews until the time of reformation;
but Christ being come, a high priest of good things to come,
by a greater and more perfect tabernacle not made with hands, that is to say,
not of this building, namely, the old covenant. Heb. 9:1.
10, 11. who is made a priest, not after the law of a carnal commandment,
but after the power of an endless life. Heb. 7:16.
But now once Christ in the end of the world hath appeared to put away sin,
by the sacrifice of himself; so in the end of the world, of all worldly things,
worldly sanctuaries, tabernacle and carnal ordinances, and commandments,
and divers outward washings, and all outward worldly tithes, offerings,
and sacrifices which are worldly.
Now Christ once in the end of the world hath appeared
to put away sin by the sacrifice of himself;
(Heb. 9:26) in the end of all these worldly things;
and he is the beginning of a new world with his heavenly things,
who makes all things new.

And the apostle saith to the Corinthians, upon them the ends of the world are come,
that is, the end of all outward worldly things;
and he calleth them babes in Christ, 1 Cor. 10:11.
he could not speak to them but as unto babes in Christ, who were not of this world.
He that hath an ear to hear, let him hear, and read these things.

G+++.+++ F.

[.inline]
=== IX. Concerning the builders that reject the corner stone; and the husbandmen that kill the Lord`'s servants and son; and how Cain built the city Nod, and Nimrod the city and tower Babel; and God hath set up his city, new and heavenly Jerusalem, and the apostate christians have set up the city Babylon, since the apostles`' days.

What are all your priests, bishops and teachers, the wise master builders in Christendom,
that like the Jews do reject Christ the corner stone,
and so do fulfill the scriptures like the Jews;
who make a profession of the letter of the new testament, as the Jews did of the old,
who rebelled against the good spirit that God gave them to instruct them,
and resisted the holy ghost, that led the holy men of God to give forth the scriptures,
and resisted them also, and persecuted them, and resisted Christ,
that was conceived by the holy ghost, and crucified him.
And this was the work of such wise master builders, in the days of Christ in the flesh.
And all you outward professors of the letter in Christendom,
that look upon yourselves the wise master builders,
do not you hate the true light the life in Christ,
by which he enlightens every one that comes into the world, and do not own it?
Then they must be blind builders.
And do not acknowledge that God pours out of his spirit of grace upon all flesh,
and to lead them, and teach them, and bring their salvation;
and do not you say this is not sufficient, without you wise master builders?
And do you acknowledge that the grace and truth is come by Jesus,
and all people in this grace, and truth, and spirit, to serve and worship God?
And they that do so, and come to forsake you priests, bishops and teachers,
that look upon yourselves to be the wise master builders, are you not then angry,
and persecute such, and say they have forsaken the means?

And what! are all you bishops, priests, ministers, and teachers,
the keepers of the vineyard in Christendom?
Hath it not been let out to you husbandmen,
and when the Lord hath sent forth his servants to look for fruits among you,
have not you banished, imprisoned, stoned, hanged, killed,
burned and put to death many of the Lord`'s servants?
And have you not crucified to yourselves afresh the son of God, the heir of the vineyard,
and put him to open shame, by your evil lives and conversations?

And therefore what will the Lord of the harvest do unto you husbandmen, think you,
that have thus done unto his servants, and son, and heir?
Do you think you will not all be turned out,
and your vineyards let forth to such as will bring forth fruits to the Lord?
Let all the persecutors, and imprisoners, and banishers in Christendom about religion,
since the apostles`' days, consider this, and what will be your end,
who have brought forth no fruit to God, but have disobeyed him, like Adam and the Jews,
and followed the serpent, the murderer and destroyer of men`'s lives,
and have not followed Christ that destroys the devil and his works,
and came to save men`'s lives, and not to destroy them,
and rebuked such as would have had men`'s lives to be destroyed,
and told them they did not know what spirit they were of.
And therefore all you husbandmen, and vineyard keepers, and wise master builders,
that have destroyed so many men`'s lives, and imprisoned, and banished so many,
and spoiled their goods, because they would not conform, and be of your faith, religion,
and worship; and you have not been of the true religion, faith nor worship of God;
neither know what spirit you have been of yourselves, that have done this;
neither have you been nor are in the spirit of Christ, who came to save men`'s lives,
and not to destroy them;
and Christ did not destroy those Samaritans that would not conform and receive him,^
footnote:[Luke 9:54.]
but rebuked them that would have had men`'s lives destroyed by fire from heaven.

So not like these mad people that build gallows and prisons,
and kindle fires on earth to destroy men;
because they would not receive their invented ways, religions, and worships,
and yet they would be called christians, after Christ`'s name,
and follow him not in life, example, and doctrine.

And Cain who disobeyed God, and did not well, who was a murderer,
though he was a sacrificer, he was a builder of the city of Nod;
and doth not that signify wandering?
And in the new world did not Nimrod, who did not regard the Lord, build Babel,
a city of confusion; and what became of Nimrod`'s city and stock?

And did not the Jews, who rebelled against God and his law, and spirit, become vagabonds,
persecutors, and murderers of the righteous?

And have not the christians since the apostles`' days, that hate the true light,
the life in Christ, and are erred from the spirit of God,
that he hath poured upon all flesh to lead and guide them,
and the truth and grace of God that comes by Jesus, to teach them,
and bring their salvation; have not these been the builders of Babylon,
the city of confusion, since the apostles`' days?
in whose city the blood of the prophets and martyrs of Jesus is found;
so that they are become drunk with the blood of the righteous, and prophets,
and martyrs of Jesus.
And are not the dragon, beast, and false prophet found in this city?
But down they must fall, and God will reward them according to their works.

And there was scarce a righteous man, or a prophet,
but they suffered in outward Jerusalem, by the transgressing Jews; for Christ said,
'`Nevertheless, I must walk today, and tomorrow, and the day following;
for it cannot be that a prophet perish out of Jerusalem,`'
Luke 13. But God is setting up his new and heavenly Jerusalem,
into which, neither the dragon, the old serpent, nor the beast that rose out of the sea,
the sea-beast, nor the beast that rose out of the earth, the land- beast,
nor the false prophet, nor the whore of Babylon,
nor no persecutor or unclean person can enter, though the gate stands open night and day,
but such who walk in the light of the Lamb,
and their names are written in the book of the lamb, and the glory of the Lord,
and the lamb is the light thereof.
Hallelujah forever.
And the nations of them that are saved walk in the light of this city.

[.inline]
=== X+++.+++ News, news! Cain, Ishmael, Esau, Korah, Dathan, and Abiram, Balaam, and old Simon Magus, and his followers, turned outward Christians.

News, news!
Cain that wrathful murderer of the righteous is become a christian,
but hath not left his wrathful hatred, murder, and persecution,
but still remains a wicked one.

And news, news! wild Ishmael, whose hand is against every man,
is become an outward christian, and hath put on the sheep`'s clothing,
but remains in his mocking, and scoffing, persecuting birth, at the seed of the promise.

News, news! profane Esau, that man of the field,
which despiseth his everlasting birthright, who is the first birth,
who would have slain Jacob, he is become an outward christian,
but he hath not put off his rough garment,
by that he may be known not to be a sheep of Christ.

News, news!
Korah, Dathan, and Abiram are become outward Christians,
but still remain with their false fire, until they be consumed by the Lord`'s fire,
and remain in their rebellion and gainsaying till the earth swallow them up:
so they may be known by their false fire, gainsaying,
and rebelling against the law and gospel.

Strange news!
Balaam, that layer of stumbling blocks before God`'s people,
is become an outward christian, but he remains in his error,
and coveteth after the wages of unrighteousness.
And why may not Balaam become a christian as well
as the sons or followers of Simon Magus,
who buy their pretended gift for money, and sell it for money, as old Simon,
who thought to have bought the spiritual gift for money, and have sold it for money?

And because we cannot give covetous Balaam his wages of unrighteousness,
and the followers of Simon Magus money for their gifts,
they are and have been very angry, and full of wrath, envy, and malice,
and persecuted us; but they are known to all true christians to be of the seed of Balaam,
and of old Simon Magus, and not of Christ.

[.inline]
=== XI. Here you may see the heavenly and spiritual gifts that God and Christ gives to his ministers, are not to be bought and sold for money, and they that do, are in the bond of iniquity, and gall of bitterness, like Simon Magus.

Christ said to his apostles, disciples, and ministers,
when he sent them forth to preach his gospel, freely you have received, freely give.
So the ministers of the gospel are distinct from the ministers and teachers of the law;
for they had tithes and offerings, and other things for ministering and teaching the law,
and that which the law commanded in the old covenant and testament,
which law served until Christ came in his gospel and new covenant, and new testament,
and sent forth ministers of his new covenant and new testament,
whom he made able ministers of the spirit, not of the letter, which sowed to the spirit,
not to the flesh, and of the spirit they reaped life eternal.
And to them that he sent forth he said, freely you have received, freely give; namely,
his gifts that are perfect, his grace, etc. his spirit or holy ghost,
that comes from the Father and son, his faith, which he is the author and finisher of,
his everlasting glorious gospel of life and salvation; these are heavenly, spiritual,
and divine things, which they received freely from Christ,
and they were to give them freely again to people,
and they were not to sell and bargain with people for so much a year,
and to sell them these spiritual gifts;
for by the laying on of the apostles`' hands many received the holy ghost.
And Simon Magus proffered the apostles money, and would have bought this gift,
that on whomsoever he laid his hands, they might receive the holy ghost;
but the apostle told him, that he was in the gall of bitterness,
and the bond of iniquity,
that thought the gift of God could be bought and sold for money;
so are all they that be in his belief.
And though Paul plant, and Apollo may water, yet they give this water of life freely.
And the general proclamation, both by Isaiah and John in his Revelations is,
'`Oh every one that thirsteth,
come freely to the waters of life.`' So they were
to eat and drink the heavenly food freely,
and hear the gospel freely, and what the spirit saith to the churches;
so they were to come without money, and without price,
and not to spend their money for that which is not bread,
and their labour for that which doth not satisfy.
And all that thirsted were to come without money, and without price,
and hearken diligently, and their souls should live.
So heavenly and spiritual things, and the gifts of God,
are not to be bought and sold for money; though they did eat of their carnal things,
and what was set before them, that did minister spiritual things to them;
though in the time of the law, tithes were called holy, but they are not in the gospel,
for Christ makes all things holy;
and his ministers that freely did give his spiritual things,
and bid them give them freely again, they did believe in Christ,
and trust in him for outward things;
and when that he sent them forth without bag or staff, and when they returned again,
he asked them if they wanted any thing?
And they said nay: for he was able to supply them he sent forth,
when he was able to feed so many with a few loaves and fishes.
And when the disciples had been toiling all night
with their nets and could catch no fish,
but Christ bid them cast their net again into the sea, which they did, and drew it out,
and at his word the net was full of fish.
And therefore whom Christ sends forth with his power and holy ghost, and saith unto them,
'`Freely you have received,
freely give,`' these dare trust Christ both with carnal and temporal things,
both for themselves and families,
and such labour to keep the gospel of Christ without charge, so that none can say,
it is a chargeable gospel.
And the apostles, and they that did succeed them in the same spirit,
did convert more Jews and heathen to Christ by their free preaching,
than ever the Papists and Protestants have done this thousand years;
for they converted them with the spiritual weapons and armour,
which Christ armed them withal,
but have not Protestants and Papists made them turn
from one sect to another with carnal weapons?

And in the old testament they had singers, and so they have now in their cathedrals.
But singing in the grace, and singing and praying in the spirit and the holy ghost,
this is in the gift of God, this is not to be done for money, but freely,
as the grace of the spirit of God moves them in his wisdom, in his gospel day.
And the apostle saith, we speak wisdom among them that are perfect,
but not the wisdom of this world?
For Job saith, that wisdom cannot be purchased for gold, silver, nor pearls;
for such things cannot be equalled nor valued with the gift of God.
For all the ministers of God and Christ in the new testament,
their heavenly and spiritual gifts and things,
which they have freely received from Christ, they are freely to give them again,
for they are not to be valued, equalled, nor purchased for gold, silver,
nor precious stones.
For they that think they can either be bought or sold for money,
they are in the spirit of Simon Magus, and not in the holy ghost,
nor spirit and power of Christ, that the apostles were in.

And the apostle saith, '`Obey them that have the rule over you, and submit yourselves,
for they watch for your souls, as they that must give account,
that they may do it with joy,
and not with grief.`' Heb. 13:17. And the apostle said
in Acts 20. that the holy ghost had made them overseers.

Now the ministers and teachers both of the Protestants and Papists,
bring these scriptures, and say,
they are ministers that do watch for the souls of people,
that they may present them to God, etc. and call themselves the curers of souls.
And yet they say, they have not the same power and holy ghost that the apostles had;
and yet they will confess and acknowledge that the soul is immortal,
and that God breathed into man the breath of life, and he became a living soul,
and in his hand is the soul of every living thing, and the breath of all mankind. Job 12:10.

Now the hand of God is immortal and spiritual,
and is it like that they should watch for the immortal soul, and cure it,
and are not in the same holy ghost and spirit of Christ,
and power of God that the apostles and overseers were in, in the primitive times?
And is it like that any should present the immortal souls to the immortal God,
and cure them without the immortal power and holy ghost that the apostles were in?
For both the Papist and Protestant teachers have confessed,
that they have not the same power and holy ghost that the apostles were in.
Therefore, I say, they are not like to cure the immortal souls,
and present them to the immortal God,
without the same power and holy ghost that the apostles were in.

Now all the priests, ministers, and teachers, both of Protestants and Papists,
pretend to preach the everlasting gospel, which is the power of God unto salvation,
to every one that believes.
But how unlike is it they should know the everlasting gospel, the power of God,
and preach it, and have not the same power and holy ghost that the apostles had?
Therefore, I say, such cannot preach the everlasting gospel, and power of God,
and not be in the everlasting power and holy ghost.

And again, the Papists and Protestant teachers say, they preach the kingdom of God,
and the grace and faith of Christ.
Grace and faith are the gifts of God and Christ which are perfect,
and Christ who ascended on high, gives gifts unto men,
to bring them to the knowledge of the son of God, and to the unity of the faith,
and unto a perfect man, etc.
And the Papists say, they must have a purgatory when they are dead.
And the Protestants say, they must have a body of death and sins of the flesh,
whilst on this side the grave, and that there is no perfection while upon the earth.
And how are such like to preach the faith, grace, and the gifts of God,
which are perfect, and are for the perfecting of the saints,
and to bring people to be perfect men,
when they have not received these perfect gifts freely from God and Christ?
And how can they preach the kingdom of God, that stands in righteousness and peace,
and joy in the holy ghost, and have not the same holy ghost as the apostles had?
And how are such like to preach spiritual and heavenly Jerusalem,
the mother of all true christians, where no unclean things enter,
and have not the same power and holy ghost that the apostles were in,
but follow their own spirits in their natural arts, tongues, and sciences,
which they have purchased for money?
And how are such like to preach Christ, who saith, I am from above, and not of this world?
And are such with their natural gifts, tongues, and sciences that are below,
like to preach Christ Jesus and the truth as it is in him?
And the scripture saith, that none can call Jesus Lord, but by the holy ghost,
and they that have not the spirit of Christ are none of his.
And therefore, how can such be the ministers of Christ,
and have not the spirit of Christ and the holy ghost, that the apostles were in?
For the apostle saith,`' Such as have not the spirit of Christ
are none of his;`' therefore they are none of his messengers,
ministers, and teachers.
And the Papist and Protestant teachers which do oppose the true light of Christ,
which enlightens every man that comes into the world, which is the life in Christ, who,
with their darkness, cannot comprehend it, though it shines in their darkness,
and are haters of the light, because their deeds are evil, and will not come to it,
because it will reprove them.
And so close their eyes and stop their ears to the light, which is the life in Christ,
and so will not hear with their ears, nor see with their eyes.
So they are not like to be converted to Christ, to heal them,
when they stop their ears to the divinity of Christ, namely, his light the life in him,
which Christ commands them to believe in and walk in; and yet, without the light,
the life in Christ, pretend to preach him in the flesh, and deny him in his divinity.
And the apostle saith, '`He had known Christ after the flesh,
but henceforth he knew him so no more.`' But what will the teachers,
both of the Papists and Protestants say to this, that deny Christ the true light,
which enlightens every man that comes into the world?
And such are not like, neither can they preach Christ truly as he was in his flesh,
nor him in his divinity.
Nor can any,
except they be in the same power of God and holy ghost that the apostles were in,
that leadeth into all truth, they are not like to preach the truth as it is in Jesus,
not being led into it by the spirit of truth.
For Christ saith, '`The holy ghost shall take of mine, and give unto you,
and bring unto your remembrance the things that Christ had spoken;`' and such
are not like to preach the spiritual things that the holy ghost receives of Christ,
and have not the holy ghost to receive them.
And the apostle saith, '`The things of God we speak,
not in the words which man`'s wisdom teacheth,
but in the words which the holy ghost doth teach.`' And you that
have not the same holy ghost that the apostles had,
are not like to have the words that the holy ghost teacheth,
to speak the things of God in,
but you speak the things of God in the words that man`'s wisdom teacheth,
by which wisdom the world knows not God nor his things,
and so are ministers of the letter and old authors.
and not of the spirit.

[.inline]
=== XII. How that such as kill and persecute people, are not like to convert them, as the apostles did.

And if that Christ had caused fire to come down from
heaven upon the Samaritans to have consumed them,
as the zealous disciples would have had him, who were without the true knowledge,
for they did not then know what spirit they were of,
when they desired such a thing of Christ; but Christ said unto them,
that he came not to destroy men`'s lives, but to save them;
and if that they had been destroyed,
then there could not have been so many of the Samaritans
converted after Christ Jesus was ascended;
so that the disciples heard at Jerusalem, and sent to Samaria, Peter and John, to Philip,
who was at Samaria, and preached Christ there, and the people there with one accord,
gave heed unto those things which Philip spake.

If that king Manasses, that great idolater, had been cut off by the Jews in his idolatry,
then he had not repented, as it is said he did.

And if the christians had killed Saul, that great persecutor,
then he had not repented and become a christian, and been called Paul.
And all those thousands of Jews, that were converted after Christ was ascended,
by the apostles, which were not converted before Christ was crucified;
if that Christ in the days of his flesh had caused them to be imprisoned,
and their goods spoiled, and to be put to death, then they after had not been converted,
that opposed him.

And is it not said, that Christ will consume and destroy the man of sin,
the mystery of iniquity, who letteth, opposeth,
and exalteth himself above all that is called God?
So vengeance is the Lord`'s and he will repay it,
and all men and women are to obey the law of God, and command of Christ;
love thy neighbour as thyself, and do unto all as they would have others do unto them,
which is the law and the prophets, and Christ and the apostles taught it.
Now would any have others to burn, or hang, or prison, or spoil their goods,
and banish them, because they will not be of another`'s religion, and forsake their own?
And they that will not be done so to themselves,
and do think it is hard for others to do so to them;
then is it not hard for them to do so to others and will not be so done to themselves?
Then do not such that do so to others, as they would not have them do to them,
do contrary to the law and the prophets, Christ and the apostles,
(to wit,) to love thy neighbour as thyself, and to do to others,
as you would have others do unto you?

[.inline]
=== XIII. Concerning the Papists making the flesh and blood of Christ of bread and wine; and the apostle saith, they knew Christ no more after the flesh; and how the formal Christians take the bread and wine kneeling, in remembrance of Christ`'s death, and his disciples took it sitting.

There is and hath been a great deal of stir among several sorts of people called christians,
about the eating and drinking of bread and wine, which some call a sacrament,
and some call it Christ after they have blessed it, and consecrated it, as they call it.
And also they that do not say the elements of bread
and wine are the body and blood of Christ,
or the very Christ,
(which they take upon their knees kneeling,) such are called heretics.
The Jews were not to eat the passover which God commanded, upon their knees,
or to kneel down and eat it;
for where did the Lord command the Jews to kneel down to
any thing that he commanded them to take or eat?
And all the figures and shadows, or types,
where did the Lord ever command the Jews to bow or kneel down to such things,
but they were to bow down to the Lord, and serve and worship him?^
footnote:[Ex. 12:10-11. and 20:4, 5. Duet. 5:8-9.]
For do not you, after you have consecrated the elements of bread and wine,
and made you a Christ and a God of it, do not some of you bow down, and kneel down to it?
And it is but elements of bread and wine when you have done.
And the Lord saith,
'`Thou shalt not make a likeness of any thing that is in heaven,`' etc.
And do not you make a likeness of Christ, who sitteth at the right hand of God in heaven,
of the elements of bread and wine?
And this is a breach of the command of God.

Now when the evening was come, Christ sat down with his twelve disciples,
as in Matt. 26:20 to the 31st. So he doth not say they kneeled or bowed,
but they sat down, when they eat the last supper with Christ.
And again in Mark 17:18. And in the evening Jesus cometh with his twelve disciples,
and '`as they sat and did eat, Jesus said unto them,`' etc.
Here you may see they sat and did eat.
It is not said they bowed or kneeled and did eat.
But they sat with the King of kings, and Lord of lords at supper,
the night before he was crucified.
And in Luke 22:14. And when the hour was come, Christ sat down,
and the twelve apostles with him.
It is not said they bowed down, or kneeled down,
but they sat down with Christ when they did eat the bread and wine.

And therefore you that profess the scripture is your rule,
why do you force people to bow and kneel, when they take the elements of bread and wine,
etc. seeing here are three witnesses, Matthew, Mark, and Luke,
that all say they sat down with Christ at the last
supper the same night that he was betrayed,
when they drank and did eat; and never one of them say,
they bowed or kneeled when they drank of the fruit of the vine,
and eat of the bread in remembrance of Christ, to show forth his death till he come?
Of this you may see more at large, in a book entitled,
'`A Distinction Betwixt the Two Suppers of Christ;`' to wit,
the supper when he was betrayed, and the supper after he was ascended.

And when did ever Christ, or the apostles command them to make an altar, and bow to it,
or before it, and set up outward candles in outward candlesticks,
to burn night and day in the outward churches or sanctuaries, as you call them,
as your Papists do?
And do not the unreformed bow before the altar that they have made,
and set up an outward candle in an outward candlestick?
Though they do not light them,
there they stand ready if the pope should command them to be lighted.
These things, altars, candles, and candlesticks, lighted or unlighted,
and bowing and kneeling to your altars, and bread and wine when you take it,
had you not all these things from the pope and Papists,
and not from Christ and his apostles?
And if you observe the apostles, they took bread and wine at night after supper;
but you take it before dinner, and you say the scripture is your rule.
And Christ said unto John, Rev. 1:20. '`The seven candlesticks which thou sawest,
are the seven churches;`' so they were not seven
outward candlesticks set up in the churches,
as you call them;
but the seven churches were the seven golden candlesticks which held the light of Christ,
which shines continually; so the church of Christ was,
and so the church of Christ is now.

And the apostle saith, '`For both he that sanctifieth,
and they that are sanctified are all of one;
for which cause Christ is not ashamed to call them brethren, saying,
I will declare thy name unto my brethren,
in the midst of the church will I sing praises unto thee.`' Heb. 2:11-12. Rev. 1:15.
So where two or three are gathered together in his name,
he is in the midst; and the church of Christ is the golden candlestick,
and Christ is in the midst.
So he is a light in the midst of the seven golden candlesticks.
So unto God be glory in the church by Jesus Christ, throughout all ages,
world without end. Amen. Eph. 3:21.

And the Jews in the first covenant had ordinances of divine service,
and a worldly sanctuary, and a tabernacle, and a candlestick;
but hath not Christ abolished all these worldly things,
which were made and pitched by men?
as in Heb. 9:1-2.

But Christ our high priest is a minister of the sanctuary, and of the true tabernacle,
which the Lord pitched, and not man. Heb. 8:1-2,

And the apostle saith, '`Henceforth know we no man after the flesh, yea,
though we have known Christ after the flesh,
yet now henceforth we know him no more,`' namely, Christ after the flesh;
and is not '`henceforth,`' time to come. 2 Cor. 5:16.
So the apostles were far off from
making a Christ of the elements of bread and wine,
both his flesh, bones, and sinews, when they said '`Yea,
though we have known Christ after the flesh,
yet now henceforth know we him no more;`' to wit, after the flesh.
Then was it not in the spirit, and his godhead, and as he was God?
But what work hath the Papists made to pretend to make flesh, blood,
and bones of Christ of the elements of bread and wine, and bowing down to it,
and worshipping it, and burning and killing such as would not!

Now they that in the apostles`' days did take the elements of bread and wine,
did it in remembrance, and in a show of Christ`'s death till he came.
And Christ said he would come again to his disciples, and did so.
And Christ was put to death in the flesh, and not his godhead, nor as he was God,
who saith, '`Being put to death in the flesh,
but quickened by the spirit.`' 1 Pet. 3:18. And Jesus said, '`If any man love me,
he will keep my words, and my Father will love him, and we will come to him,
and make our abode with him.`' And again Christ saith,
'`You have heard how I said unto you, I go away and come again unto you;
if ye love me ye would rejoice.`' John 14:23. 28. He that hath an ear to hear,
let him hear.

And where did ever the apostles take bread and wine
in remembrance of Christ`'s death in the flesh,
after they had said, though we have known Christ after the flesh,
yet now henceforth know we him no more, (viz. after the flesh.) 2 Cor. 5:16.

And now you Papists, that call yourselves Roman Catholics, that is, universal,
and yet you did say in a dispute,
that you had not the same power and holy ghost that
the apostles had in the primitive times;
and yet you do say after you have consecrated bread and wine, it is the body of Christ,
both his flesh, blood, and bones, yea, the very whole Christ; and yet when so made,
he hath no legs, hands, nor mouth, and can neither speak, hear, see, nor go!
And why cannot you make a virgin Mary, the mother of Christ, as well as make a Christ?
and a St. Peter of bread and wine, as well as a Christ; and set him up in a chair,
as well as set up a pope in Peter`'s chair, as you call it?

And is not this a strange juggling, that you should turn wine into blood,
and bread into flesh, bones, and sinews?
This is as strange a miracle as ever was heard of in the world,
wrought by an unclean ghost; for some Popish priests confessed,
in a dispute with some Quakers, at Thomas Apostles in Gerrad Robert`'s house,
when it was asked you, whether you had the same holy ghost as the apostles had,
and you denied it, and said, it was presumption to affirm any such thing;
and then it was said unto you,
then it was not like that you should be led into all truth.
In what could you pray, and in what was your fellowship?
It could not be but in the unclean ghost, which led out of all truth,
for the holy ghost led the apostles and the church of Christ into all truth;
and they prayed in the holy ghost, and had fellowship in the holy ghost.
And the apostles, and the church of Christ never did say nor pretend,
that with the holy ghost, they could turn wine into blood, and bread into flesh, bones,
and sinews, and then say it was the whole Christ, and eat him when they had done;
and they that would not believe it, to burn them,
as you Papists have done who pretend to turn wine into blood, and bread into flesh,
bones, and sinews, and say it is the whole Christ, which could neither speak, see,
nor go!
Strange monster makers, with your unclean ghost, and when you have done you eat him!
And when we have said unto you, and desired you to try your Christ,
whether his flesh and blood will not corrupt;
to have part of the wine and the bread you consecrated,
locked up with the unconsecrated in a cellar, and seven Protestants,
and seven Papists to keep watch over the cellar, and if the consecrated did corrupt,
mould, and die, as the other, then you should turn to us; but if it prove immortal,
and the very flesh, blood, and bones of Christ, then we would all turn to you,
and this would bring truth to light, and honour to God;
for you have burnt and put many to death,
because they could not believe in your great miracle and monster,
that you have made with your unclean ghost.
For we are in the Catholic faith, set up in the apostles`' days,
which Jesus Christ was and is the author and finisher of,
and we are redeemed not with corruptible things,
but with the precious blood of Jesus Christ,
as of a lamb without blemish and without spot.
And the apostle saith, '`Christ`'s flesh did not see corruption,
and though he was crucified, nailed to the cross, and his side run into with a spear,
and dead and buried, and was three days and three nights in the sepulchre,
yet his flesh saw no corruption, and did not change; for the apostle saith,
'`The Lord did not suffer Christ, his holy one, to see corruption.`'

'`And therefore,`' it is said, '`did my heart rejoice, my tongue was glad: moreover also,
my flesh shall rest in hope,`' whom God raised from the dead to sit upon his throne,
and his flesh saw no corruption. Acts 2:26-27. 31, 32.
And therefore now you Papists.
come out and try your great monster and miracle, as before.

[.inline]
=== XIV. The trial of the Pope`'s Spirit.

Will the pope let the Protestants have their meetings peaceable in France, Spain,
Portugal, Italy, and Rome, and in all the cities or dominions, where he,
or his have power?
If that he, or his,
do desire that his people should have their meetings peaceable in the nations, kingdoms,
cities or governments, where the Protestants have the power;
come let us see if he hath so much holiness, or infallibility, to do unto others,
as he would have others do unto him?
I say to do unto others, as he would have others do unto him, that is,
to let others of a different persuasion from him have their liberty,
as he would have his, seeing they all profess Christ in words, as before; if not,
he is below the law and the prophets, and short of a christian;
and if his actions be below the law, and the prophets, and christianity,
it is then a shame to talk of infallibility and holiness.

[.inline]
=== XV. Concerning the kingdom of God.
The law and the prophets were until John, who was the greatest prophet born of a woman,
but the least in the kingdom of God is greater than John;
and since John Baptist the kingdom of God is preached, and men do press into the kingdom.
So the everlasting kingdom of God is the end of the law, and the prophets, and John,
for the everlasting kingdom of God stands in righteousness, and peace,
and joy in the holy ghost, which the law, and the prophets, and John called for,
and was held forth by them in figures, types, and shadows,
and John ran before and prepared the way to the kingdom;
and they that are in the kingdom are in the substance, and in the end of the law,
and the prophets, and John`'s ministration,
and are in the end of all things that do change; for the kingdom of God is everlasting,
and doth not change.

Moses was faithful in all his house, as a servant,
for a testimony of those things which were to be spoken after.
But Christ, as a son over his house, whose house we are,
that be children of heavenly Jerusalem.
For Moses was over the house of Israel with their figures and shadows; but Christ Jesus,
who is the substance, is over his great spiritual house;
who hath all power in heaven and earth given to him,
who doth enlighten all their spirits in the house or tabernacle of fallen Adam,
which light is the life in Christ, by whom Adam and Eve were made,
and all things that were made, were made by Christ.
For Aaron did light the outward candles and lamps
in the outward tabernacles that were made with hands.
But Christ the great prophet, priest, bishop, and shepherd,
doth enlighten the spirits of men, the candle of the Lord,
in their tabernacle not made with hands, with his true heavenly divine light,
which is the life in himself, the word, by whom all things were made, as before.
So Christ is over his great house, an enlightener, a quickener, a saviour, a redeemer,
a counsellor, a leader, a captain, a prophet to open, a shepherd to feed,
a bishop to oversee, and a king and lord to rule, order,
and govern in his great spiritual house, which he is the head of;
and a father that doth take care of his great heavenly and spiritual house and family;
and he shall reign over the house of Jacob forever, and of his kingdom there is no end. Luke 1:33.
And you do read that some would not have Christ to rule over them,
and what became of them that said,
We will not have this man to rule over us Luke 19:14.
But these were not of the house of Jacob,
the second birth; but of Esau, that profane person`'s birth, or nature.

For all the outward pleasures, delights, lightness, wantonness, vain glory,
and profaneness, will perish and come to naught, with all foolish jesting,
and idle vain talk, and idle words are judged, and will vanish away like smoke,
and all unholiness, unrighteousness, and ungodliness, looseness, debauchery, uncleanness,
proud boasting, loftiness,
and haughtiness is judged out of the kingdom of God and Christ.

'`For behold a king shall rule in righteousness.`' Isaiah
32:1. And his sceptre is a sceptre of righteousness;
and the Lord shall reign forever unto all generations: praise ye the Lord.
And by Christ kings do rule, and princes do decree justice,
and all the judges of the earth.
And Isaiah 11:10. and Rom. 15:12. There shall be a root of Jesse,
and he that shall arise to rule over the Gentiles, in him shall the Gentiles trust;
therefore praise the Lord all ye Gentiles, and laud him all ye people.
Ps. 116:1. For Christ in you is the hope of glory,
and Christ is to dwell in your hearts, to wit, the saints, by faith, saith the apostle;
for Christ is the same today as he was yesterday, and so forever.
And Christ Jesus is made an high priest forever, and again, '`Thou art a priest forever.
For the law made high priests which have infirmities;
but the word of an oath which was since the law, maketh the son,
who is consecrated forevermore.`' And Christ saith to John '`I am he that liveth,
and was dead, and behold I am alive forevermore.`'

So Christ hath set up his kingdom, which shall never have an end,
and all power in heaven and in the earth is given to him;
and the saints that are born again do see his kingdom, and press into it,
and are heirs and possessors of it.

And they that do sing the song of Moses, and of the Lamb, said that he is king of saints.
And Hezekiah said, "`Thou art the God,
even thou alone of all the kingdoms of the earth.`' So not only of the kingdom of Israel,
but of all the earth.
And the good seed are the children of the kingdom; but the tares, that the wicked one,
the devil soweth, are the children of the wicked one.
And '`no man having put his hand to the plough, and looketh back,
is fit for the kingdom of God.`' Luke 9:62.

And when that Jesus perceived that they would make him a king by force,
he departed into a mountain himself alone. John 6:15.
For Christ was anointed king by the Lord,
and so he knew that he needed not be made king by man; for Zechariah in the 9th chap.
saith, '`Fear not daughter of Zion.
(John 12:15) Behold thy king cometh upon an ass
colt.`' And was not this fulfilled when Christ came?
But it was their spiritual king, and they would not have him to reign in spirit.

And Nathaniel called Christ the son God, and king of Israel.
And the apostle tells the Colossians,
that they were translated into the kingdom of God`'s dear son. Col. 1:13.
'`To the King eternal, immortal, invisible, the only wise,
be honour and glory, forever, and forever.
Amen.`'

Here is an immortal, eternal, invisible King, and is known by his invisible holy spirit,
and rules in the hearts, and in the kingdom of heaven in men and women,
who is the only potentate, the King of kings, and Lord of lords, and hath immortality,
and dwelleth in the light.
And John said, '`that he was in the kingdom and patience of Jesus Christ,
when that he was in the isle of Patmos; and that Christ the first begotten from the dead,
he is the prince of the kings of the earth, and has made us kings and priests spiritual,
unto God his Father, to him be glory and dominion forever and ever.
Amen.`' Rev. 19:16. And upon Christ is written a name, that he is King of kings,
and Lord of lords;`' and they that see this name, and the writing,
it is with a spiritual eye.

G+++.+++ F.

[.the-end]
End of Vol VI.
