== Introduction

=== A Testimony, how the Lord sent G. F. forth at first, in the year 1643.

When the Lord first sent me forth in the year 1643,
I was sent as an innocent lamb (and young in years) amongst (men in the nature of) wolves,
dogs, bears, lions, and tigers into the world,
which the devil had made like a wilderness, no right way then found out of it.
And I was sent "`To turn people from darkness to the light,`" which Christ,
the second Adam, did enlighten them withal; that so they might see Christ,
their way to God, with the spirit of God, which he doth pour upon all flesh,
that with it they might have an understanding to know the things of God, and to know him,
and his son Jesus Christ, which is eternal life;
and so might worship and serve the living God, their maker and creator,
who takes care for all, who is Lord of all;
and with the light and spirit of God they might know the scriptures,
which were given forth from the spirit of God in the saints,
and holy men and women of God.

And when many began to be turned to the light (which
is the life in Christ) and the spirit of God,
which gave them an understanding, and had found the path of the just, the shining light,
then did the wolves, dogs, dragons, bears, lions, tigers, wild beasts,
and birds of prey make a roaring and a screeching noise against the lambs, sheep, doves,
and children of Christ, and were ready to devour them and me, and to tear us to pieces.
But the Lord`'s arm and power did preserve me;
though many times I was in danger of my life,
and very often cast into dungeons and prisons, and haled before magistrates.
But all things did work together for good: and the more I was cast into outward prisons,
the more people came out of their spiritual and inward prison,
(through the preaching of the gospel.) But the priests
and professors were in such a great rage,
and made the rude and profane people in such a fury,
that I could hardly walk in the streets, or go in the highways,
but they were ready oft-times to do me a mischief.
But Christ, who hath all power in heaven and in the earth,
did so restrain and limit them with his power, that my life was preserved;
though many times I was near killed.

Oh! the burdens and travails, that I went under!
Often my life pressed down under the spirits of professors and teachers without life,
and the profane!
And besides, the troubles afterwards with backsliders, apostates, and false brethren,
which were like so many Judas`'s in betraying the truth,
and God`'s faithful and chosen seed, and causing the way of truth to be evil spoken of!
But the Lord blasted, wasted, and confounded them, so that none stood long;
for the Lord did either destroy them, or bring them to nought, and his truth flourished,
and his people in it, to the praise of God, who is the revenger of his chosen.

[.signed-section-signature]
G+++.+++ F.

=== Concerning the first spreading of the truth, and how that many were imprisoned, etc.

And the truth sprang up first (to us,
as to be a people to the Lord,) in Leicestershire in 1644, and in Warwickshire in 1645,
and in Nottinghamshire in 1646, and in Darbyshire in 1647,
and in the adjacent countries in 1648, 1649, and 1650, and in Yorkshire in 1651,
and in Lancashire and Westmoreland in 1652, and in Cumberland, and Bishopric,
and Northumberland in 1653, and in London, and most parts of the nation of England,
and Scotland, and Ireland in 1654, etc.

And in 1655, many went beyond seas, where truth also sprang up.

And in 1656, truth brake forth in America, and many other places.

And the truth stood all the cruelties and sufferings
that were inflicted upon Friends by the long-parliament,
(to the spoiling of goods, imprisonment, and death, and over all the reproaches, lies,
and slanders,) and then by O. Cromwell, protector,
and all the acts that Oliver made and his parliaments, and his son Richard after him;
and the committee of safety.
And after, it withstood and lasted out all the acts and proclamations since 1660,
that the king came in.
And still the Lord`'s truth is over all, and his seed reigns,
and his truth exceedingly spreads unto this year, 1676.

And Friends never feared their acts, nor prisons, nor jails, nor houses of correction,
nor banishments, nor spoiling of goods; nay, nor life itself.
And there was never any persecution, that came, but we saw it was for good;
and we looked upon it to be good, as from God.
And there was never any prisons, that I was in, or sufferings,
but still it was for the bringing multitudes more out of prison.
For they that imprisoned the truth, and quenched the spirit in themselves,
would prison it, and quench it without them.
So that there was a time, when there were so many in prison, that it became as a by-word,
truth was scarcely any where to be found but in jails.

And after that the king came in, divers Friends suffered much,
because they would not drink the king`'s health, and say,
"`God bless the king;`" so that many times Friends
were in danger of their lives by rude persons,
who were ready to run them through with their swords for refusing it;
until the king gave forth a proclamation against drinking healths.
For we were and are against all drinking healths and excess, both before his coming in,
and after; and we desire the king`'s good,
and that the blessings of God might come upon him, and all his subjects,
and all people upon the face of the earth.
"`And we did desire people not to drink the king`'s health, but let him have his health,
and all people else; and so to drink for their own health and necessity only.
For that way of drinking healths, and to excess, was not for the king`'s health,
nor their own, nor any others.
Which excess often brought forth quarrelling and destroying one another;
for they destroyed the creation, and one another.
And this was not for the king`'s wealth, nor health, nor honour;
but might grieve him to have the creatures destroyed, and his subjects.`"
And so the Lord`'s power gave us dominion over that also, and all our other sufferings.

But Oh! the number of sufferers in the commonwealth`'s days,
and in the protector`'s days, and since!
But especially they, that were haled before their courts, for not paying tithes,
and not swearing in their juries, and for not putting off their hats,
and for going to meetings on the First-days,
(under pretence of breaking the sabbath,) and other meetings in the week-days;
who were abused both in the meetings, and on the highways!
Oh, how great were the sufferings we then sustained upon these accounts!
For sometimes they would drive Friends by droves into the prison-houses,
(like penfolds,) and there keep them on the First-days;
and then take their horses from them,
and keep them for pretended breach of their sabbath.
Though they would ride in their coaches,
and upon their fat horses to the steeple-houses themselves, and yet punish others.
And many Friends were turned out of their copyholds and customary tenements,
because they could not swear; and as they went to meetings,
they have been stoned through the streets, and cruelly abused otherwise.
And many were fined with great fines,
and lay long in prison for not putting off their hats; but Friends could never pay them,
though they kept them in prison, till they had satisfied their own wills upon them;
and at last turned them out, after they had kept them a year, or more, in prisons.

And many Friends were exceedingly spoiled in their
estates and goods in the petty courts for tithes,
till we got a prohibition and demur out of the king`'s bench,
that then threw the trial of such things out of their petty courts,
that they might sue for them in the courts at London.
And my desire is, that the Lord may open their understandings also,
(if it be his will,) to throw them out of those courts also.

And many books I gave forth against tithes,
and how the priesthood was changed that took them.
And that Christ sent forth his twelve (and after, seventy) disciples, and said unto them,
"`Freely they had received, and freely they were to give.`"
And so all that are transgressors,
and do not obey the doctrine and command of Christ therein, we cannot receive them.

And many suffered for not swearing, both before and since the king came in;
because they could not swear, in obedience to the command of Christ and the apostles,
who forbade all swearing.
And tenths were offered up in the time of the law;
but all must be offered up in the time of the gospel for Christ`'s sake.
For there were no tithes nor swearing before the fall;
and so there are none again to be in the restoration by Christ.
And though swearing was in the time of the law; yet our yea is to be yea,
and our nay to be nay in the time of the gospel.

And several books I was moved to give forth against swearing,
and that our yea and nay might be taken instead of an oath; and if we broke that,
let us suffer the same punishment that they did that broke their oaths.
And in Jamaica the governor granted the thing, and the assembly;
and it is also granted in some other places.
And several of the parliament-men in England have
acknowledged the reasonableness of the thing.
For the true oath of God was but to tie people to swear by the Lord,
and to say and to do truth, since man and woman fell, in the time of the law,
and not before the fall.
And this was the oath that Christ came to fulfill and end; and he saith,
"`Swear not at all.`"
And I say, Christ fulfils and ends this oath, which men were to perform to the Lord,
who performs God`'s oath, which he swore by himself, and fulfils that;
and he sets up yea, yea, and nay, nay, instead thereof.
Concerning which I and my Friends have written at large in our books touching this subject.
And the magistrates, after some time, when they saw our faithfulness in yea and nay,
that were they moderate,
(both before and since the king came in,) would put Friends into offices without an oath.
But they that were cruel and envious, would fine Friends to get money of them;
though Friends could not pay them any.

And thus the Lord`'s power hath carried us through all, and over all,
to his everlasting glory and praise!
For God`'s power, which was before the devil`'s was, hath been our hedge, our wall,
and our keeper, and the preserver of his plants and vineyard,
who have not had the magistrates sword and staff to help them,
nor ever trusted in the arm of flesh.
And have gone, without Judas`'s bag or the magistrates`' sword and staff,
to preach the word of life, which was in the beginning, before they were;
which word reconciles to God.
And thousands have received the word of reconciliation,
and are born again of the immortal seed by the word of God,
and are feeding upon the milk of the word, which lives, and abides, and endures forever.
And many have suffered to death for their testimony, both in England and beyond the seas,
both before and since the king came in; which ye may see, as followeth:

This was given to the king and both houses of parliament, being "`A brief, and plain,
and true relation of the late and sad sufferings
of the people of God in scorn called Quakers,
for worshipping, and exercising a good conscience towards God and man.`"

"`By reason whereof eighty-nine have suffered till death,
(thirty-two of whom died before the king came into England, and fifty-seven since,
by hard imprisonment and cruel usage,) forty-three
have died in the city of London and Southwark,
since the act was made against meetings,`" etc.
(about 1661.) They have thus suffered;
of which a more particular account was given (with
their names who did suffer) to the king and parliament,
about 1663.

And though divers laws were designed against us,
yet never could any of them justly touch us, neither did they truly concern us,
though they did execute them unjustly upon us;
and they knew we were not the people justly chargeable;
and some have been made to confess it.
And all those laws, that were already made, and the oath which they imprisoned us for,
(because in obedience to the command of Christ Jesus,
we could not swear at all,) were never originally intended against us.
And yet we suffered by the several powers and their laws,
(though they did not concern us,) both spoiling of goods and imprisonments,
even to death itself.
And the governor of Dover Castle, when the king asked him,
"`if he had dispersed all the sectaries meetings?`"
said, "`he had; but the Quakers, the devil himself could not.
For if he imprisoned them, and broke them up, they would meet again;
and if he should beat them, and knock them down, or kill some of them, all was one:
they would meet, and not resist again.`"
And thus the Lord`'s power did support them, and keep them over their persecutors;
and made them to justify our patience and lamb-like nature.
This was about 1671.

And since the king came in,
three acts have been made against us by the king and parliament,
(besides the proclamations,) by which many have suffered imprisonment, and banishment,
and many to death.
And yet for all these acts and proclamations, and banishment, and persecutions,
and sufferings, faithful Friends are as fresh as ever in the Lord`'s power,
and valiant for his name and truth.
And some weak ones there were, when the king came in, that did swear, and take the oaths;
but after, when they had so done,
they were so sore troubled for disobeying the command of Christ, and the apostle,
that they went to the magistrates, and condemned themselves,
and offered themselves to go to prison.
And thus the Lord, in his everlasting power,
hath been the support and stay of his people.

And when the glorious gospel and truth was spread over the nation,
and they had received the word of life, then first the Quarterly,
and some Monthly Meetings, were settled throughout the nation; and then after,
as truth more and more spread, the monthly Men`'s Meetings, in 1667 and 1668.

And then also some Women`'s Meetings were set up;
and afterwards the Women`'s Meetings throughout the nation,
and other nations were exhorted unto, and set up and established throughout the nations.
For I was sent for to many sick people; and at one time I was sent for to White-Chapel,
about the third hour in the morning, to a woman that was dying, and her child;
and the people were weeping about her.
And after a while I was moved,
(in the name and power of Christ Jesus,) to speak to the woman;
and she and her child were raised up.
And she got up, to the astonishment of the people, when they came in, in the morning;
and her child also was healed.
And when I came to G. Roberts`'s house, about eight in the morning,
there came in Sarah Blackberry to complain to me of the poor,
and how many poor Friends were in want; and the Lord had showed me, what I should do,
in his eternal power and wisdom.
So, I spake to her,
to bid about sixty women to meet me about the first hour in the afternoon,
at the sign of the Helmet, at a Friend`'s house.
And they did so accordingly, such as were sensible women of the Lord`'s truth,
and fearing God.
And what the Lord had opened unto me, I declared unto them,
concerning their having a meeting once a week, every Second-day,
that they might see and inquire into the necessity of all poor Friends,
who were sick and weak, and were in want,
or widows and fatherless in the city and suburbs.
And so, they blest the Lord for the wisdom of God,
that had settled such a meeting in his power amongst them.
For they saw, that all that were heirs of the power of God,
were to take their possession of the power of God, the gospel and its order, which was,
before the devil was.
And this brought them into the practice of the pure religion, and to visit the sick,
and for the relief of the fatherless and the widow, and to see,
that nothing was lacking amongst them; and that they,
in visiting the sick in the Lord`'s power and word,
through it they would have the wisdom of the Lord, and of his creation,
and how to administer his creatures,
and by the same power to heal and strengthen with the outward things, and without them.
Which they have felt prosperous to this day:
and great things have been done in their meetings by the Lord`'s power,
and very honourable it hath been in the eyes of all the faithful, yea,
and commendable in the world also.

And afterwards the same Women`'s Meetings were settled up and down the nation,
and beyond the seas, in the power of the Lord, which was before the devil was;
into which power of the Lord no sect nor apostacy can come, but peace and unity.
And the power of the Lord, the gospel,
is the authority of all the Men`'s and Woman`'s Meetings, and all the heirs of the power,
the gospel,
both men and women are to take their possessions of the inheritance of the power of God,
which is over the devil.
So, in it nothing can get betwixt them and the Lord God.

And at the settling of the Men`'s Meetings in the gospel, the power of God,
I let them see,
how they had a men`'s meeting in the first conversion amongst the primitive christians,
of such as were faithful men, and full of the holy ghost; and these were to see,
in the Lord`'s power and wisdom, that nothing was lacking.

For since the Christians denied the Jews`' temple, storehouse, and priests,
where the widows, strangers, and fatherless were relieved;
they set up a men`'s meeting in the power of God, and in the holy ghost,
(and they had Deaconesses also,) to see that widows, fatherless,
and strangers were relieved, and that nothing was wanting among them.
Now, though this practice hath been lost since the apostles`' days,
since then have gone from the power of God, and the holy ghost,
that the apostles were in, (and therefore are the streets and country so full of widows,
strangers, and beggars, and so full of wants,
who want the sense of the good spirit and power to open their hearts,
that the apostles and primitive christians were in.) But the everlasting gospel
being preached again by the same holy ghost that the apostles were in;
and received from heaven as they received it;
and many thousands having received this gospel now again, men`'s meetings are set up,
(as were in the days of the apostles,) in the power of God, and in the holy ghost.
And women`'s meetings as mothers, and that they may be teachers of good things,
and so to see, that nothing be lacking amongst them; and so to do good unto all,
but especially to the household of faith.

And now, the power of God is the authority of both our men`'s and women`'s meetings,
and all our other meetings;
which power of God was before the apostacy was from the apostles,
and before the fall and the devil were, and is over all;
and all are to take their possessions of it, and in it to do God`'s service and business.
So these meetings are for the converted and elect,
"`before the world began,`" and such as are heirs of the power, and do possess it;
and what they do and act in the spirit and power of God,
they do it in that which shall never have an end, to the glory of God forever.
Amen!

[.signed-section-signature]
G+++.+++ F.

=== Upon the Fourth-day of the First month, 1650, I felt the power of the Lord to spread over all the world in praise.

Praise, honour, and glory be to the.
Lord of heaven and earth!
Lord of peace, Lord of joy! thy countenance maketh my heart glad.
Lord of glory, Lord of mercy, Lord of strength, Lord of life, and of power over death,
and Lord of lords, and King of kings!
In the world there are lords many, but to us there is but one God the Father,
of whom are all things; and one Lord Jesus Christ, by whom are all things:
to whom be all glory, who is worthy!
In the world are many lords, and many gods, and the earth maketh lords,
coveting after riches, and oppressing the creatures; and so,
the covetous mind getting to itself, lords it above others.
This nature of lordly pride is head, until subdued by the power of God: for every one,
in that state, doth strive to be above another; few will strive to be the lowest.
Oh! that every one would strive to put down, in themselves, mastery and honour,
that the Lord of heaven and earth might be exalted!

[.signed-section-signature]
G+++.+++ F.
