== Epistles 32 &#8212; 48

[.centered]
=== Epistle 32.

[.blurb]
==== To Friends, that their minds go not out from the spirit of God.

[.salutation]
Friends,

When your minds go forth from the pure spirit of God, and are drawn out from it,
there the image of God comes to be lost, in those whose minds go out from the pure,
to lust after that which is in the fall, which may appear like truth in the notion;
in that nature, out of the truth, lodgeth the enchanter and sorcerer.
To speak of truth, when ye are moved, it is a cross to the will;
if ye live in the truth which ye speak, ye live in the cross to your own wills.
For that which joins with the earthly will, goes out from God, and that which is pure;
and so makes a place for the enchanter and sorcerer, and the airy spirit, to lodge in;
whereby a grave is made for the just,
and the partition wall between God and man standing.
Death comes to reign, and the grave hath the victory over such;
and in the airy spirit lodgeth the enchanter, which the Lord will rebuke.
Dwell in the pure and immortal, and wait upon the living God, to have your hope renewed,
and to be renewed again into the image of God, and the image of the devil defaced,
and the prince of the air cast out; for he lodgeth in the mind that doth despair,
and in that mind that doth presume.

So, dwell in the light, and wait upon God to have the image of God renewed;
and all come to witness yourselves to be restored by Christ Jesus into the image of God,
and to be made by him like to God, pure, holy, perfect, and righteous.
This was witnessed, this is witnessed,
and this will be witnessed measurably with thousands, who are growing up out of the fall,
and coming up out of the grave.
Let not the lust go out to any thing which is mortal, to be servant thereto;
but mind the joining to the life.
Here ye are kept in the image of God.
Not but that ye may use the creatures lawfully, but being kept in the image of God,
ye are kept as kings over all the creatures, and over the creation;
here ye will see all things, and by whom they stand.
To the pure all things are pure, being in the image of God above all the creatures below,
not worshipping the host of heaven, nor being in bondage to the creatures,
nor minding any thing in comparison of that which is immortal,
which joins you unto the Lord; and all that speak here, in that which is immortal,
are joining unto the Lord.
But that nature keep out, and that judge, which is mortal, which will join to the harlot,
the fleshy; from all that there is to be a separation.
And here (as ye are brought by the power of God) the gate is seen that stands open;
which gate is shut from all mortal eyes.
And all the wonderers are here seen, who inquire after new things and novelties;
but the "`wise man satisfies not the fool.`"
For that part is above the pure, if it be not kept in the cross; which,
not being wrought out, will join to the flesh, and so become one with the harlot.
And such join together to put Christ to death afresh.

So, therefore, dwell in that which is pure and eternal, which guides the mind to God;
here is perfect peace to those whose minds are stayed upon the Lord: which,
if the mind goeth from, there the peace is lost; and there getteth in the light,
airy spirit in that nature.
And if the mind go back, to fetch up things again, and speak them forth,
there will lodge the airy spirit too, though there may be true experiences;
and if the life speak them forth, by which they were opened,
it keeps down the airy spirit.

Therefore mind the substance, that keeps you in your present conditions,
and that which doth disobey or rebel against the word of the Lord,
in that nature lodgeth the airy spirit;
and that which hearkens to things that are spoken out of the life, without,
that lets in the devil.
And so, ye come to be possessed with evil thoughts, and doubts, and carnal reasonings,
and bondage, and troubles; these things in you will rest,
until the life be risen again within, to cast all that forth,
which the earthly ear and mind hath let in.
Now, if ye hearken diligently, ye will learn your safeguard,
and judge forth that which is not pure, which defiles;
that the just may have the dominion.
And here ye will see, what stains, and what defiles,
and the pure eye and ear will be opened to hear God; and the wizard, and the enchanter,
and the sorcerer, and the soothsayer, all that will be kept out and judged.
For none of that must live in Israel, where there is to he no transgression.
For where they live, truth doth not; and where truth doth live, that doth not,
but is all judged out.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 33.

[.blurb]
==== To Friends, for all to wait and walk in the truth.

All Friends and brethren everywhere, in the life and power of the Lord wait,
and from it none walk;
but that to the light of Christ in every one ye may be made manifest,
that the fear and dread of the Lord may be in all your hearts,
that nothing may reign but life itself.
And so, all your meetings in every place keep, waiting in the light,
which from Christ doth come, the saviour of your souls;
that his presence in the midst ye may all feel,
who are gathered together in his name and power in his light,
(which is his name,) and from the world`'s gatherings are turned.
And if any be moved (who are turned to the light) with the power which comes from him,
to any service for the Lord, to it be obedient;
and ye will see Christ with you to the end of the world.
But if any go, before they are moved, and so from the light walk,
he is a stumbling block, and is to be judged and condemned by the light;
and is out of the wisdom, and out of the fear, and soweth to the flesh,
and reaps corruption, and by the light is condemned.
For that answereth not the light in every man`'s conscience,
neither doth it reach to the life, the spirit in prison; but it manifesteth weakness,
and foolishness, and nakedness, which is from the light, and contrary to it.
And such are stumbling blocks, and do not answer the witness of God in the conscience.

Therefore wait all in the light,
for to receive the power from him who is not of the world,
that ye may be preserved from nakedness and weakness.
For that which goes from the light, and is not guided with it, runs into the lust;
and there is the slothful, which is to be judged, and that that will offend,
to which the woe is; for it answereth not that of God in the conscience:
neither is it honourable, nor of good report; for that which is honourable,
and of good report, answereth that which is of God,
and answereth the light of Christ in every man in the world with wisdom,
which from the light doth come, even from him by whom the world was made.

Therefore all Friends, this is a charge to you all,
and a command to you all in the presence of the living God: "`In the light, life,
and power,
and wisdom of God walk,`" that to that of God in
every one ye may be manifested in the sight of God,
and it may be your witness, that ye are of God, in every man`'s conscience,
which witnesseth against the world, and for him who is not of the world.
And wait all in the light for the wisdom by which all things were made,
with it to use all the Lord`'s creatures to his glory,
(and none to stumble one another about the creatures,
for that is not from the light,) for which end they were created,
and with the wisdom by which they were made, ye may be kept out of the misuse of them,
in the image of God, that ye may come to see, that "`the earth is the Lord`'s,
and the fulness thereof,`" and the earth may come to yield her increase,
and to enjoy her sabbaths; and all such that walk contrary to the light,
may be turned to the light,
that with the light they may see and condemn that which is contrary to it.
So that in the wisdom of God ye may all be kept,
and in the fear of the Lord and his righteousness established;
which is far from oppression, where all bonds of iniquity are broken,
and the prince of darkness judged out, and the Prince of peace reigns,
under whose dominion keep and walk.
And all that cause strife, are to be condemned and shut out,
which have their eye without, and are condemned by the light,
the god of the world having blinded the eye of the unbeliever.

Therefore, ye believers in the light, wait in the wisdom,
that with it and in it ye may be ordered to the glory of God,
that among you nothing may reign, but light, and life, and wisdom, and power,
the dread and fear of the Lord be among you, and truth and righteousness reign;
which will answer the light of Christ in every man.
And all that is contrary,
let it be condemned with the light which comes from him by which the world was made,
who was before the world was, who "`lighteth every man, that cometh into the world.`"
Though they believe not in it, yet ye may answer the light in every man,
though it be their, condemnation.

So being kept in the light, which cometh from him by whom the world was made,
who was before it was made, ye come to receive the wisdom by which all things were made,
and with it to order and use them to the glory of God.
For that which is not from the light, nor from the wisdom, is the offender,
which is to be condemned with the light which comes from the life;
and to it in you all take heed, that your hearts may be joined together to God,
and all that is contrary condemned.
And so, the Lord God Almighty preserve and keep you all in wisdom!

[.postscript]
====

P+++.+++ S.

Friends, a warning from the Lord to you all, in wisdom to walk,
that ye may adorn every one, what ye profess,
that the measure of God`'s spirit in every one ye may answer.
And know the Lord to guide your understandings,
and let his wisdom be justified by you all,
and ye in the measure of the spirit of God in unity kept;
that ye may see righteousness spring and flourish among you, and no deceit stand,
nor nothing that is deceitful; but with the eternal judge it down, and keep it down,
that nothing may live that is for the sword, which would defile the land.
Therefore in that which is eternal, dwell, as a royal priesthood,
in that which comes from him by whom the world was made;
who to all your souls is a Friend, from whence the refreshing is received.
So the Lord God Almighty preserve and keep you all, that in his life, dread,
and power ye may be preserved.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 34.

[.salutation]
Friends,

I do warn you in the presence of the living God,
not to speak the things of God out of the fear of God, at random, in a presumptuous mind;
for proud boasters are excluded out of the kingdom of God,
and with the light of Christ condemned, and with the life,
that gave forth the scriptures, are they judged.
Therefore to you this is the word of the Lord, in the light,
which Christ hath enlightened every one of you withal, wait in it, and love it,
and ye shall have the light of life;
and it will bring you to stand in the counsel of God, and keep you from all wicked ways.
And with it ye will see all the enchanters, false prophets,
who speak a divination of their own brain,
whose minds are turned from the light of Christ; with this light are they condemned.
All whose minds are turned from it, and hate it, whose deeds are evil,
with this light are they condemned;
though they may make a profession of the words which proceeded from the light,
from them who lived in it, and walked in it.
So they that turn from it, and hate this light,
making a profession of their words that dwelt in it,
and hate them that walk in the light now, (Oh,
high deceit!) all such are to be condemned with the light.
And such that hate the light, and deny it, though they may profess the words,
that did proceed from the life, and be full of them,
they turn no people from their wicked ways; for in the counsel of God they stand not.
For they were in the counsel of God, who gave forth the scriptures,
who were in the life of them, from which the letter did proceed.

Therefore in the life, (every one in your measures,) wait and walk,
which gave forth the scriptures, which will open them to you again;
else you all I do deny, and ye are to be turned away from, as having the form,
but not the power.
And know the life of God in one another, and the power of God in one another;
but that knowledge in the form without the life we deny,
though it be never so finely painted, and the harlot be never so beautiful,
who is turned from the light, which Christ hath enlightened withal.
This is the harlot, who dresseth herself with the words that proceeded from the light,
who persecuteth them who dwell in the light, who drinketh the blood of the saints,
who dwell in the life which gave forth the scriptures.
And with the words that proceeded from the light, doth she clothe herself,
and is harlotted from the life; and all that she brings forth, is contrary to the light.
So she is called the mother of harlots.
But if ye love this light, and your minds be guided by it to see the face of Jesus,
and him the head, then with this light ye will see all the harlots,
and the mother of harlots, and where she is, and what she is joined to.
The light is that, by which ye come to see; he that walketh in it, stumbleth not.
But thou stumblest, who art turned from the light among the harlots.
I charge you every one in the presence of the living God, to take heed to the light.
It is your teacher, loving it; it is your condemnation, hating it.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 35.

[.blurb]
==== To Friends in the Ministry.

Stand up ye prophets of the Lord, for the truth upon the earth; quench not your prophecy,
neither heed them that despise it; but in that stand which brings you through to the end.
Heed not the eyes of the world, ye prophets of the Lord, but answer that in them all,
which they have closed their eye to; that ye may to them tell of things to come,
answering that of God in them that shall remain.
Keep ye in your habitations, ye sons of God, that over all the contrary ye may reign.
And ye daughters, to whom it is given to prophesy, keep with in your own measure,
seeing over that which is without, answering that of God in all.
And despise not the prophecy, keep down that nature that would,
which is the same as that is which acts contrary to that of God in them.
Neither be lifted up in your openings and prophecies,
lest ye depart from that which opened, and so come by the son of God to be judged,
and bidden to depart as workers of iniquity;
for a worker of iniquity is gone from that which leads to the son of God,
who is the end of the prophets.

Quench not the spirit, by which ye may prove all things,
and that which is good hold fast; for if the spirit be quenched,
then light is put for darkness, and darkness for light, and evil is put for good,
and good for evil.
This is when the spirit is quenched, then cannot ye try all things,
then cannot ye hold fast that which is good.
For then ye cannot see good, when the spirit is quenched;
but when the spirit is not quenched, then with the spirit ye may see the good,
to take the good, and the evil to shun.
And this brings to put a difference between the precious and the vile,
the profane and the holy, the clean and the unclean;
the spirit is it that proves all things.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 36.

[.salutation]
Friends,

Take your heavenly censers, and offer up your spiritual prayers to the Almighty God,
and having heavenly fire in your censers,
it will consume all false offerings and sacrifices,
which are offered in the evil nature.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 37.

[.blurb]
==== To Friends in Cumberland.

Dear Friends, prize your heavenly calling,
by which ye are called into holiness and righteousness,
without which no one shall see the Lord.
And let your conversation be, as becometh the gospel, the holy power of God,
which is the gospel of Christ, the holy one, who suffered by the unholy ones.
And keep in the lowly mind, and the humility of Christ,
that the fruits of your good conversation, and translation,
and regeneration in your lives may appear,
as a people redeemed from the pleasures of the flesh, and the spirit of the world,
and the beggarly lusts; and that ye may obtain the promise of the eternal God,
and the power of the truth, through the word in the heart, the hidden man,
that ye may obtain victory over that which wars against your souls;
through which ye may be arrayed and adorned,
and by that ye may be preserved and kept from that which is not of the Father,
(the lust of the flesh, the lust of the eye,
and the pride of life,) in the simplicity and innocency of Christ Jesus,
(over all the subtlety and feigned deceit,) through which ye may
esteem nothing in comparison of that which is of God,
and him above all, through Christ the light, the truth,
the power of God manifested in you.
And keep out of all false liberties,
and that which would lead you out of the fear of God;
and in that ye will be preserved in the sense of the power and the truth of God in
your own hearts.
In that every one watch, through which knowledge and virtue is ministered unto you,
and peace from the God of virtue and peace.
And keep out of all that which tends to strife, and whisperings, and backbitings,
and tattlings, which draws from the witness, watch, and fear of God within,
which leavens into the fleshly lusts and nature; and then that judges,
and yet is in the same thing for which he judges others; which nature and judgment,
are for judgment and condemnation.
So be wise, and keep your first love; break not wedlock with the Lord Jesus Christ;
keep your first habitation, keep your garments clean, for such as so do,
they are blessed; that ye may shine as lights to the world, and be examples in virtue,
righteousness, and holiness, walking in the truth in all patience and quietness,
looking at the Lord, your strength, and Christ Jesus, the conqueror,
and beyond all the hills and mountains; that ye may be a good savour to the Lord,
having salt in your selves.
Let your lamps be burning, and your lights shining,
and then ye will see over all the unsavouriness that is in Adam`'s family in the fall,
who live in Christ, the power of God, that never fell,
and keep marriage with him the Holy One, the Just One, the light, the truth,
and power of God, who makes an end of all unholiness.
And so, walk in the righteousness, that your feet may be kept in the way of peace.
And keep your tongues, and hands, and bodies, and lips, and minds,
and words out of all that, which would defile and corrupt you,
and bring you under the indignation and wrath of God,
and his hand to be turned against you.
So, keep in the fear of God, and keep in his truth which ye at first received,
for truth never changes.
And walk in the spirit, and then the lusts of the flesh will not be fulfilled,
and then strife is kept out, that which would be high and get up,
through which come strife and wars.
So keep your fellowship in the spirit, in which is the unity and bond of peace,
and the fruits of the spirit will appear, righteousness, holiness, goodness, peace,
soberness and gentleness, chastity and virtue,
through which ye may have fruit to feed the hungry, and to relieve the sick and poor.
For the unfruitful walk not in the spirit, and so bear not fruit; and so the curse comes,
and briars, and misery.
So, eye the Lord God in all things in the spirit, who is a spirit;
in that ye may distinguish his things, and the things that are of your selves,
and what is of men, and what is of God, and what to keep alive, and what must die.
So be obedient to the spirit, and to the good power of God, that hath quickened you;
and live in it, that ye may die no more, for that gives you life.
For they that are made alive, and come to die again, and to be twice dead,
and then come to be plucked up by the roots; such lie dead upon the earth,
and corrupt it.
So, let not the world, let not things visible draw your minds away from the Lord.
Do not mind the body more than the Lord; do not forsake the Lord;
but be of good faith in the truth of God, and live in it, then ye live in Christ Jesus,
who is your way, who is your teacher, who is your prophet, who is your priest,
who is the bishop of your immortal souls, Christ that never fell, nor never changed,
nor never will change.
And here ye come into the seed, the top stone, that is atop of the world set,
and before the world was, who will remain when the world is gone; who was full of grace,
and truth, and virtue, and life, by whom grace comes, that brings salvation,
who is every one of your teacher in yourselves.
So, know Christ the head and salvation, in which there is peace, and no condemnation;
for the condemnation is upon them, that are out of the light.
And so, live in unity in the light, before darkness and enmity was,
in which ye have peace, and love to God, to Christ, and to one another.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 38.

[.blurb]
==== An Epistle to the travellers in the Lord`'s way, with a Testimony against the false prophets, and those that hold them up.

[.salutation]
Friends,

All are to receive your spiritual bread and water from the Father of life,
by which ye may be strengthened and watered from the Father of life,
in your passing and travelling on in your spiritual journey heartily and comfortably;
that ye may come to your heavenly rest,
being come and coming out of the great city of Sodom,
towards the city of heavenly Jerusalem, where ye shall abide eternally forever.

Reason not with flesh and blood, that shall never enter;
take not counsel of that which draws thee nearer to carnal things,
and draws thee to consult with carnal reason,
and so draws thy eye and mind to visible things,
and so brings thee to wander from going on thy journey; and if thou followest that,
thou goest to death, hell, and destruction, and to the pit and the snare,
and that gets dominion over thee, and comes to rule over thee, which ought not.
But every one wait in the pure spirit to guide you to God,
then ye shall see the promise of God fulfilled in you,
and the springs of life opened to you, and refreshment daily coming in from the Lord;
and then ye will come to walk with the Lord, forsaking all, father, mother, wife,
and children, lands, livings, and all.
Here is joining to the Lord, as one spirit; and he that doth not forsake all,
is not worthy of him.
All who are in the first birth, and all who reason with flesh and blood, stand here,
and are for persecuting them who are born of the spirit,
that are passing out of this city, towards the city whose foundation and builder is God.
For in that city the righteous ones are slain, by them who are of Cain`'s generation.
All ye, who are got up into his steps, professing Christ and to be ministers of Christ,
who stand in the envy, and have the "`chiefest place in the assemblies,
and are called of men master,`" which Christ forbids! lie down all for shame,
who are in pride and oppression, and in the steps and places of the Pharisees,
and have got a form of the words which the apostles said, and which Christ said,
and have got it in three or four languages; the Lord hath discovered you now;
the Lord God Almighty hath discovered you by his prophets and servants.
All honour, and glory, and thanks be to him forever,
who now is come to rule alone in his saints.
Rejoice, O all ye prophets and righteous ones!
The beast, which made war with the lamb and the saints,
the lamb hath got the victory over the beast, and the ten horns, which pushed at him.
Powerful Father and eternal God, to thee alone be all glory, honour, and thanks forever.

Now all ye teachers, and hearers that hold you up, I witness against you,
that ye may be witnesses against yourselves,
and that ye witness yourselves to be in Cain`'s generation,
and in the generation of the false prophets, and antichrists, and seducers,
(who have the form of godliness,
but deny the power,) and in the generation of them that ever slew the righteous seed,
as it will, appear.

Now all people, take notice! who are they, that bear rule by their means?
Who are the hirelings now, that the scriptures speak of?
Who seek for their gain from their quarters now?
Who feed themselves with the fat now?
Who seek for the fleece, and clothe themselves with the wool now,
and so make a prey of the people?
Where are the hirelings now?
The priests preach for hire, and the prophets prophesy for money.
Who sue men at the law now, which Christ spake against; which the apostle speaks against,
who was a minister of the living truth which testifies against all such practices?
Who go in the way of Balaam now for gifts and rewards?
Where are the covetous teachers now?
Who are called of men master now?
Who love the chiefest places of the assemblies now?
Who go in long robes now?
Who stand praying in the synagogues now, and speak a divination of their own brain,
which the woe was pronounced against by Christ Jesus,
(the substance of all the prophecies,) who cried
woe against all such Pharisees and false prophets?
Who hale out of the synagogues now?
Who stone and stock, prison and beat now, and hale before magistrates?
This was the Jews`' practice and religion, ye may say; the Jews did so.
But the prophets of God testified against these things;
and the apostles testified against all these practices.
And Jesus Christ testified against all the evil works of the world;
and all these practices were held up in Cain`'s generation.
So, be ye witnesses that ye are here in the generation of the false prophets,
and in the chair of them that spake a divination of their own brain,
that are called of men masters; love the chiefest places in the assemblies;
lay heavy burdens upon the people; of them that seek their gain from their quarters,
and of them that go in the way of Balaam, and in the generation of Cain.
Where any prophet comes to cry against any of you, ye seek to imprison him,
or to destroy him, which Abel did not, (as ye may read,) but Cain,
who was the first birth, whose sacrifice God had no respect to;
no more hath God to your customary will-worships, praying and prayers,
than to Cain`'s. For Cain`'s generation was and is the same that ever it was,
and is not of the generation of the righteous.
And except ye all be born again, ye cannot inherit the kingdom of God.
So, here be ye witnesses against yourselves, that ye are in the generation of Cain,
which ever slew the righteous seed; and in the generation of all the false prophets.
Put it not far from you, as they did who put Christ to death.
If thou hadst lived at that day,
(thou mayst say,) thou wouldst not have put Christ to death.
But thou shalt see the same nature in thee now, as was then.
For now is the son of God come; and ye are of the same generation that they were,
seeking to put him to death where he is manifest.

But the eternal, glorious God of heaven and earth, the same as ever he was,
is manifesting himself in his sons and daughters,
who are called out of that generation and worship.
For he said, "`Come out from among them, be ye separate, touch no unclean thing,
and I will be a Father unto you,
and ye shall be my sons and daughters;`" and this we witness, and this is fulfilled.
The generation of the wicked we know, and the generation of the faithful we know;
here is a separation between the precious and the vile, between the holy and the profane.
So all people, weigh and see, in what generation ye are!
The generation of the righteous shall shine;
the generation of the wicked are for the fire prepared, and to be turned into hell.
Ye are the stubble; ye that are proud, are for the fire; ye that are wicked,
ye are chaff that the wind drives to and fro; ye that are scorners, are turned from God;
ye that are heathenish, know not God; and all that are heathen, know not God;
the Lord will render vengeance in flames of fire upon you.
The mighty day of the Lord is coming, that shall burn as an oven.
The fire is kindling in the earth, which shall burn up all, root and branch,
head and tail; the Lord of hosts hath spoken it.
The Lord God of power will reign.
O happy day! praises! praises!
Praise ye the Lord, ye righteous ones; sing praises to the Lord God Almighty forever!

All ye liars and dissemblers ye must never inherit the holy city in that state.
And all ye, who commit sin, and live in sin, know not God; and who are disobedient,
and hold the truth in unrighteousness, the wrath of God abides upon you.
All ye, that work iniquity, (and live and die in that,) are to depart from God,
as cursed, to everlasting punishment; where then will ye find him,
that ye talk of with your mouths, and call your saviour?
Ye that live in your vain, wicked, profane ways, and take him to be your cloak, and say,
ye are redeemed by him, and live in your wickedness, "`Go, ye cursed,`" he will say,
"`I know you not.`"
Plagues, woe, and misery will be poured upon you all.
Let every one that nameth the name of the Lord, depart from iniquity.
None can call him Lord, but by the holy ghost; and where the holy ghost is come,
there he is Lord and king.
This is witnessed in all his saints, where he is so; but in Cain`'s generation it is not,
but these persecute it.
But he is risen and come in his saints, who is Lord and king,
who will reign over all the world, and bear the government upon his shoulders.
For the Lord is king in his saints, he guards them,
and guides them with his mighty power,
and doth preserve his seed and children from the seed of evil doers,
in his kingdom of glory and eternal rest, where they find joy, and peace,
and rest eternal.
All glory and praise be to the Lord God Almighty forever!

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 39.

[.blurb]
==== To Friends in the North.

[.blurb]
=== All Friends in Westmoreland, Cumberland, Bishopric, New Castle-side, Northumberland, and Lancashire,

Wait in the measure of the spirit of the living God,
that with it all your minds may be guided up to the living God, and to it take heed,
that ye may have dominion over these spirits that are in the earth;
that in the spirit of the living God ye may all know one another,
and with it come to reign over the world in the power of the mighty God,
which upholds all things; and wait to receive wisdom from God,
who created the creatures to his glory.
And the Lord God Almighty keep you all in the spirit, and be with you all.

And all of you, live in the life, that with it ye may come to know the Father of life;
and all being led with the spirit of the living God, the Lord`'s presence ye will enjoy;
and all that is contrary, with it will be judged.
So the Lord God Almighty preserve you in that which is pure, up to himself, who is pure,
to receive his wisdom, and that with it and in it,
ye all may come to be ordered to his glory, who is God over all;
to whom be all honour and glory, God blessed forever;
that with it ye may come to see the lamb of God, the saviour of your souls, who was,
before the letter was.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 40.

[.salutation]
Friends,

I warn and charge you all, to be faithful in the measure of the life of God,
which he hath given you.
And watch over one another, that with that which is pure ye may discern,
and have unity with that which is pure.
And take heed of any lightness and frowardness, which is contrary to that which is pure,
but in that wait and dwell, which doth that judge in particular and general;
that the garden of the Lord may be dressed, and ye in his wisdom preserved and kept.
The mighty power of the Lord keep you all in his spirit, and with it up to himself,
your hearts joined together!
And see that ye meet together,
and be led together in the spirit and in the power of the Lord;
and that ye keep out of all men`'s evil wills, which are contrary to the power and light.
This is the counsel of the Lord to you.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 41.

[.salutation]
Friends,

To you all this exhortation is from the word of the Lord: Dwell in the life,
that with it ye may see the Father of life.
And dwell in the light, with which light the world is condemned;
which light comprehends the world`'s wisdom;
which light comprehends the world and their knowledge, and all the deceivers,
which are entered into the world,
(who are turned from the light,) with which light they are condemned, that is, the world,
who hate the light, because their deeds are evil,
and they will not bring their deeds to the light, because the light will reprove them,
they hating it, and you that live in it.
And all the deceivers, and all the antichrists,
they are such as are turned from the light, which oppose Christ.
To you all, my brethren, who dwell in the light, which is the condemnation of the world,
and of all the deceivers, who are turned from the light; it is not possible,
that those deceivers should deceive you, who are the elect, who dwell in the light,
which comprehends the world.
I do charge you all in the presence of the living God,
to dwell in what ye speak and profess; and none to profess, what he doth not dwell in;
and none to profess, what he is not; a sayer, and not a doer; such beget vain talkers.
So, with the light all such are to be condemned from the life.
So, I charge you all in the presence of the living God, to dwell in the light,
which is the world`'s condemnation, who hate it.
Though they may profess all the words declared from them that were in the light of Christ,
they hating the light in the particular, with the light, which never changes,
are they and all their profession to be condemned, and woe is the end of it and them,
from Christ, who is the light.
Wherefore, to you I speak, friends, that dwell in the light, and love it,
that to the light in all consciences of them that hate it,
(which Christ Jesus doth enlighten them withal,) ye may be made manifest,
which is the world`'s condemnation.
In the light all Friends dwell, which comprehends the world, which is its condemnation.
The highest religion to it must bend and bow; and all that is to be condemned,
which is contrary to it.
And all Friends, dwell in the light, which is eternal, which comprehends the world,
that with it ye may comprehend the world; and rise up,
and go on in the mighty power of God,
as mighty men of war in the power and strength of the mighty God of life,
the Lord of hosts, who is with you, your shield, buckler, and defence, and armour,
who arms you over all the wicked to reign, triumph, and trample.
God Almighty bless you, and prosper his work,
that to the light in all consciences ye may be made manifest, to the measure of God,
which is pure, which is given to every one;
that with it all may see what is contrary to God.
And to you this is from the word of God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 42.

[.blurb]
==== To Friends, concerning the light, in which they may see their saviour, and the deceivers.

To all Friends everywhere, scattered abroad: in the light dwell which comes from Christ,
that with it ye may see Christ your saviour; that ye may grow up in him.
For they who are in him, are new creatures; and "`old things are passed away,
and all things are become new.`"
And who are in him, are led by the spirit, to them there is no condemnation;
but they dwell in that which doth condemn the world,
and with the light see the deceivers, and the antichrists,
which are entered into the world.
And such teachers as bear rule by their means; and such as seek for the fleece,
and make a prey upon the people, and are hirelings, and such as go in the way of Cain,
and run greedily after the error of Balaam; and such as are called of men master,
and stand praying in the synagogues, and have the chief seats in the assemblies,
all which are in the world, who by those that dwelt in the light, were cried against;
for it did them condemn, and all such as speak a divination of their own brain,
and are filthy dreamers, who use their tongues,
and steal the words from their neighbours; with the light,
the world and all these aforesaid are comprehended, and all that is in it;
and all they that hate it, and all the antichrists that oppose it,
and all the false prophets and deceivers, that are turned from it,
with the light are comprehended, and with the light are condemned,
and all that are turned from it and hate it.

"`I am the light of the world,`" saith Christ,
and he doth enlighten every one that cometh into the world; and he that loves the light,
and walks in the light, receives the light of life: and the other, he hates the light,
because his deeds are evil, and the light doth reprove him.
And this is the condemnation, that light is come into the world, in which light,
they that love it, walk; which is the condemnation of him that hates it.
And all the antichrists, and all the false prophets, and all the deceivers, the beast,
and the well-favoured harlot, all these are seen with the light to be in that nature,
acting contrary to the light; and with the light are they comprehended,
and by the light condemned.

For he is not an antichrist, that walks in the light that comes from Christ;
he is no deceiver, that walks in the light that comes from Christ.
Many deceivers are entered into the world.
The world hates the light, and deceivers are turned from the light,
and the antichrists they are turned from the light, therefore they oppose it,
and some of them call it a natural conscience, a natural light;
and such put the letter for the light.
But with the light, which never changes,
(which was before the world was,) are these deceivers seen,
where they enter into the world.
For many deceivers are entered into the world,
and the false prophets are entered into the world; the world hates the light,
and if it were possible, they would deceive the elect.
But in the light the elect do dwell, which the antichrists, deceivers,
and false prophets are turned from, into the world, that hate the light:
that light which they do hate, the children of light dwell in, the elect.
So it is not possible, that the antichrists and deceivers,
that are entered into the world, that hate the light, should deceive the elect,
who dwell in the light which they hate; which light doth them all comprehend,
and the world; which light was before the world was, and is the world`'s condemnation;
in which light the elect walk.
And here it is not possible, that they that dwell in the light should be deceived,
which comprehends the world, and is the world`'s condemnation.
Which light shall bring every tongue to confess, and every knee to bow:
when the judgments of God come upon them, it shall make them confess,
that the judgments of God are just.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 43.

To all my dear brethren, the flock of God everywhere;
keep together in the power up to God,
and none be discouraged or disheartened at the enemies without,
which are without God in the world; but be bold all in the power of truth,
triumphing over the world.
Hold your freedom, and keep and stand fast in it, that ye may be armed with wisdom,
and furnished against your enemies,
who are wiser in their generation than the children of light.
But the wisdom of the Most High is spreading, and making itself manifest in your hearts,
by which ye may comprehend the world`'s wisdom, the world`'s worship and knowledge.
And waiting in that which is pure,
it will lead you into that which was before the world was, before the false worship was,
before the seducers were, before the antichrist was, and before the outward temple was,
and false prophet and hirelings: and here ye will comprehend the world,
and what is done in the world.
Therefore every one keep your habitation, abide the trial, and abide the day,
and stand fast in your freedom, so far as Christ hath made you free;
free from man`'s will and commandments, which imbondageth;
free from the fashions and lusts of the world, the fleshly will,
which bondageth and burdens the pure.
And to you that cannot witness this, wait, and mind the pure,
and then the burden will be easy; and wait for redemption and salvation, to make it so.
And your strength is, to stand still, that ye may receive refreshings; that ye may know,
how to wait, and how to walk before God, by the spirit of God within you.
So God Almighty be with you, and keep you up to himself under his own dominion,
from under the dominion of Satan, that ye may trample him under your feet.

And Friends everywhere, meet together,
treading and trampling all the deceit under your feet;
and watch over one another in that which is eternal, and see every one,
that your words be from the eternal life.
Examine and search with that which is eternal,
which speaks to that which is in prison in others.
And ye that are led forth to exhort, or to reprove, do it with all diligence,
taking all opportunities, reproving that which devours the creation,
and thereby destroys the very human reason.
For the truth doth preserve everything in its place.
And all meet together everywhere, and in your meetings wait upon the Lord;
and take heed of forming words, but mind the power, and know that which is eternal,
which will keep you all in unity, walking in the spirit,
and will let you see the "`Lord near you, and amongst you.`"
So, God Almighty be with you, and multiply you, and give you the dew of heaven,
the heavenly dew, the living mercies, (which nourisheth the tender plants,
which causeth them to grow, bud, and bring forth,) and water you with his blessings.
So, the Lord God of power be with you all, my dear hearts!
I am with you in the spirit, and in the love of your God, your Father and mine.
The Lord God prosper, guide, and protect you,
and bring you all into his kingdom of glory, you who are elected, called,
chosen and faithful, who are the lambs.
God Almighty bless you, and keep you all, my dear hearts!
The love of God is love past knowledge, which bears all things, endures all things,
hopes all things, envieth not, thinketh no evil.
And the love of God is the ground of all true love in your hearts,
which casts out the love of the world, and the enmity,
which was begotten betwixt you and God.
"`He that believes, is born of God; and he that is born of God, overcomes the world.`"
So, fare ye all well, and God Almighty bless and prosper you.

[.signed-section-signature]
G+++.+++ F.

And all ye Friends, that wait in that which is pure in itself, which cannot lie,
which doth not change, wait upon God, for God doth not change,
and let all flesh be silent before the Lord, that the life may speak in all;
then the mouth of the Lord is known, and God is exalted and glorified with his own work,
which he brings forth.
And meet together therein everywhere, and mind that which gathers you,
and wait on that which is pure, which gathers you out of the world`'s nature,
disposition, conversation, churches, forms, and customs,
which will knit your hearts together up to God.
That which gathers you out of all these, is the spirit of the Lord,
which will gather you up to him, who is the Father of spirits;
that ye may be able to judge, and discern, and confound all the deceit in the world,
and grow up to be as kings,
and suffer nothing to reign in you but what is in the life eternal.
And beware of speaking in the presence of the Lord,
except your words be from the eternal life, the eternal word of God,
else it doth not profit, nor build up, nor edify.
So, God Almighty be with you all in your meetings, that ye may see him to be your head,
king, and Lord over all.
To you all, who are enlightened with the light of the spirit,
that is the light which shows you sin and evil, and your evil deeds and actings,
and the deceit and false-heartedness; it will teach you holiness, walking in it,
and bring you into unity; and it will draw your minds up to God,
and in it ye will see more light.
But hating the light, there is your condemnation.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 44.

All Friends, wait upon the unlimited power and spirit of the Lord,
which baptizes into one body:
where ye will have all unity in that which crucifies the flesh,
and mortifies all evil desires, and puts off the body of sin, the old man with his deeds,
and circumcises without hands, and joins together your hearts up to God,
from whence the living mercies come, from the living God alone, who is God over all,
blessed forever.
To that in every one of your consciences do I appeal and speak,
to the measure that God hath given, the light; loving it, and taking heed to it,
and waiting in it for power from God, it will guide you to the Father of light,
in which ye will have all unity; and hating the light it will be your condemnation.
Oh! wait, wait upon the living God to nourish the tender plant in you,
that ye may bring forth fruits of righteousness unto God, for he accepts such,
and none else.
Therefore wait upon God, he hath a pure seed among you.
Let your waiting be in the light;
and mind that he is a wise man whose eye is in his head, which is Christ,
the end of all priests, the end of the outward temple: and the fool`'s eye is abroad,
after many priests, and they are led away with conceivings, and divers temptations.
Therefore in the light wait, where ye will see all deceits within and without.
For it is a sin to enter into temptations; but it is no sin to be tempted.
Christ was tempted, but he entered not into the temptation.
Therefore in the fear of the Lord wait and watch.
The light is that, which lets thee see sin, and evil, and temptations;
which if thou enter into, the light will be thy condemnation;
then thy heart will not be right towards God.
But in the light of God all wait, which will bring you to see where wisdom`'s gate is;
the fear of the Lord is the beginning of it.
Pure wisdom is let out of the treasury into the pure heart, which sees God;
and fearing the living God, it keeps the heart pure and clean,
to receive the wisdom from the treasury freely, who doth not upbraid.
And as ye depart from evil and iniquity, he breaks the bonds by showing mercy;
and then the understanding grows pure and clear.
So in the power of the Lord God fare ye well.

And the Lord God of power keep you all in his measure up to himself,
from and above all the world`'s evil ways, baits, customs, and teachings,
to trample upon them in his power; that wisdom may be justified of you all,
and ye may be preserved, and God glorified.
To whom be all glory, honour, and thanks over all, God blessed forever!

Read these among all my brethren and friends, and send it abroad to Friends,
that ye may all know the power of the living God in one another, not in words,
but in power.
So farewell.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 45.

[.blurb]
==== Concerning the heirs of the kingdom of God, and how Christ was, and his saints are tempted.

They are the heirs of the kingdom of God, and of the generation of God,
that live out of the kingdom of the wicked world, (up to God, in the seed,
which all the promises of God are to,) following after Christ, who was in Egypt,
and passed out of Egypt, the house of darkness.
And he was in the wilderness, and there he was tempted to lust after the creature;
he was tempted to make himself away; he was tempted to worship the devil,
(to bow down and worship him.) He is the captain of our salvation; he is gone before,
he endured the cross, be despised the shame, he suffered the contradiction of sinners,
for the glory that was set before him, he hath won the crown.
He hath overcome Egypt, and he hath fulfilled the law, he hath overcome the world,
he hath overcome the temptations; he is able to succour all who are tempted.
It is no sin to be tempted, but to enter into the temptation, that is sin.
He is the head of the body, he is the head of the church,
who hath blotted out the ordinances and traditions of men;
who is the end of the daily sacrifice; who is the end of the Levitical priesthood;
he is the end of all outward temples, who is the substance of the prophets,
for they all witnessed of him.
He is ascended above all principalities and powers.

Now, to all dear ones, the same seed, which is Christ, the same spirit is now manifest,
as ever was; the same world is now, as ever was; the same temptations,
and the same devil, and the same vain worship of the world,
twining into another form and colour.
And Jesus Christ is the way, the truth, and the life, the door,
that all must pass through, and he it is, that opens it; the same door that ever was,
the same Christ yesterday, today, and forever.
And all who follow Christ, the seed, and are of his generation,
and are brought out of Egypt, the house of darkness, and from under the law,
the righteousness of the law is fulfilled in them; who walk not after the flesh,
but after the spirit, (as the apostle saith,) which we do witness.
And the seed`'s generation hath passed through the wilderness,
where they have been tempted to lust after the creature.
Ye that have been in the wilderness, can witness this with me, and the same temptations,
even to despair, and to make themselves away.
The devil, before he would go out of his kingdom, he would destroy all.
But look at the captain Jesus Christ, who hath passed before,
who was tempted (the captain of our salvation) with
the same temptations to worship the devil;
and that if thou wouldst worship the devil, thou shouldst have the glory of the world;
if not, be called a devil, as Christ was, and be called a mad man, as he was;
and that none followed him, but a cursed people,
(as they said.) And they that worship the devil, gave those titles to him.
And thou shalt lose thy good name,
and be a laughing stock to them that worship the devil, and as a derision among them,
and a mark for every one of them to shoot at, and the drunkards to make songs of.
This is the portion of them, who deny the worship of the world, and the glory,
and the favour, and the evil fashions thereof, and cannot fashion themselves to it;
who are tempted to all these things.
But it is no sin to be tempted; but standing in the power of the Almighty God,
ye will be enabled to stand against, and above all the wiles of Satan.
So dwell in the power of Almighty God, which carries through the wilderness,
and through temptations to the end, and gets the victory over all the carnal ordinances,
and commands, and traditions of men; and he that overcomes, ascends above them all.
And he that overcomes, shall sit down with Christ in his throne.
So, every one must witness Christ born in them, passing through death to him,
through the world, through the law, through temptations, through the wilderness,
and out of the world; and the son of God ye will witness to arise, who doth overcome,
who was born of God.
And the same spirit, that raised up Jesus Christ, the same spirit raiseth you up,
and quickeneth your mortal bodies; and he that hath not the same, is none of his.

So, examine yourselves, and see if ye have fellowship with Christ in his sufferings,
and be brought to be conformable to him in his death,
and to have fellowship with him in his temptations and reproaches, and buffetings,
and scornings, and the contradiction of sinners, and to be spit upon, as he was;
and he that hath fellowship with him in his sufferings,
shall have fellowship with him in his glory.
And he that doth confess him in this dark world, him will he confess before his Father,
and his angels; and he that doth deny him in this world,
him he will deny before his Father and his angels in the world to come.

Now to all you who are convinced, and have your understandings enlightened,
and the worship of the world doth appear to you to
be contrary to the worship of God and Christ in spirit,
and all the prophets and apostles, who worshipped the living God in newness of life,
in the second birth, beware ye enter not into the temptation, to lust after the creature,
and give not way to the lazy, dreaming mind, for it enters into the temptations.
So there thou wilt be polluted with the pollutions of the world;
then thou wilt be tempted to despair, and the devil there gets power upon thee,
if thou enter into temptations,
and follow thy imaginations in going from the light of Christ within thee.
And then thou judgest with evil thoughts; and he will come with his instruments,
his evil angels, to tempt thee from God`'s worship to the false worship,
or else thou wilt lose thy credit or good name, or thy place, or thy authority,
where thou art, except thou wilt bow to him.
And every one will stare at thee, and thou wilt be gazed at, and wondered at.
So if thy mind go from the light, and out of the fear of the Lord,
then thou wilt consult with flesh and blood,
which must never enter into the kingdom of God, and that carnal reason must never enter.
And then thou wilt take counsel of the harlot,
and so the eye of thy mind will be turned out from God,
and so thou goest under the power of the prince of the air,
which rules and reigns in the children of disobedience,
and so under the dominion of Satan.
And then, though thou hast the praise of the world, and the glory of the world;
yet disobeying that, which should have led thee into the kingdom of God,
and from under the dominion of Satan, thy latter end will be worse than thy beginning.
And in the world there thou mayst have thy honour, and the fleshly man is nourished,
and thy glory and renown may grow again among the fleshly ones,
who are gone out from God, and have disobeyed the light in them,
which should have led them from under the dominion of Satan,
(under whose dominion they are now,) up to God, where there is joy eternal,
where there are riches and glory eternal, and where there is comfort eternal;
whose kingdom is forever, whose dominion is an everlasting dominion.
But thou, who forsakest the right way, goest into eternal destruction.
Woe, woe is to thee!
For the love of the world is an enemy to God; and he that loveth the world,
the love of the Father is not in him.
And thou, who settest thy hand to the plough, and lookest back,
art not fit for the kingdom of God.

And all who can witness the second birth, and are born again,
know the promises of God in and to the seed are yea and amen;
and ye coming out of that which was in time, ye come up to God, who was before time was.
This is a mystery, he that can receive it let him; and he that hath an ear to hear it,
let him hear what the spirit saith.
Abel was the second birth, he was no murderer, nor no sinner; for God called him.
And God saw no iniquity in Jacob, but Esau the first, is hated, and not perfect.
And except ye be born again, ye cannot enter into the kingdom of God.
Flesh and blood shall not inherit the kingdom of God.
And "`he that is born of God, sins not, because the seed of God remains in him,
neither can he sin, because he is born of God.`"
And "`he that is born of God overcomes the world;`" he that is born of God,
is not of this world.
And he that is born of God testifies against all the works of the world,
and the wickedness of it; and he that is born of God, doth not commit sin.
He that committeth sin is of the devil, and hath not seen God at any time.
Hereby are the children of God made manifest from the children of the devil;
for he that sins is of the devil, and knows not God.
For this purpose was the son of God made manifest, to destroy the works of the devil;
and he that doth righteousness, is righteous, even as he is righteous.
And they that were of the second birth, were taught of God,
and needed no man to teach them; and were come into the everlasting covenant.
And those are the second birth,
who are born again of the immortal seed by the will of God, and not by the will of man.
And as many as received Christ, he gave power to them to become the sons of God,
which are not born by the will of man, but by the will of God; not by water only,
but by water and the spirit.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 46.

To all Friends who are in the unity, which is in the light; walk in the light.
It is one light that doth convince you all; and one Christ,
that doth call all to repentance, up to himself the one head, which is Christ.
The wise man`'s eye is in his head, who changeth the mind,
and calleth from above to that which lies below; it is he alone that gives faith,
and all who are in this faith are one.
It is one power that raiseth up the seed; and your faith being out of words,
in the power, ye are all one, and that seed is one; and ye are all one,
if ye be ten thousand; which seed is one, which is Christ, and he is the master,
which is one: and all the brethren who are in the spirit, are one.
Ye have all one eye, which is the light; one fire,
which consumes all which the light discovers to be evil; and one spirit,
which baptizes all into the one body, where there is no confusion,
but pureness and oneness.
Therefore all Friends, mind the oneness,
and that which keeps you in the oneness and unity,
it is that which keeps you out of the world;
and this one light leads you out of darkness into the everlasting day,
where ye see the church of God.
But living in the darkness, and following that mind,
it leads into the world`'s assemblies, who have the letter of the saints`' words,
but live out of the life, smiting at one another, fighting for the husks.
But minding the light within, it leads you into the assemblies of the righteous,
who are in the life.
The kernel is to be found within, the husk is without, which the swine feed upon,
but the pearl is hid from them;
and the swine and the dogs would devour them in whom the pearl is found.
They are outsides, who feed upon outsides.
God that made the world, and all things therein,
seeing he is the Lord of heaven and earth, dwells not in temples made with hands,
and hath made all nations of men, that dwell upon the face of the earth, of one blood,
and hath appointed the times and seasons,
and hath given to every one a measure according to their ability.
God hath given ability to every one according to their measure,
(that are faithful to it,) and here is the righteousness of God received,
and the wrath of God revealed upon the children of disobedience.
The grace of God hath appeared upon all, which taught the saints to deny ungodliness,
and teacheth us; which the world turns into wantonness,
and walks despitefully against the spirit of grace;
and yet tempts God and calls for grace.
These are they that set up teachers without.
And Christ saith, he is the light of the world,
and hath enlightened every one that cometh into the world; and he that loves the light,
brings his deeds to the light, to him there is no occasion of stumbling;
and this teaching guides to God, the Father of light.
And the other, he hates the light, because the light will reprove him;
here he knows his deeds are evil, by the light.
And this is the condemnation, that light is come into the world,
and men love darkness rather than light.
And here thou must become silent, O flesh,
that temptest God to give thee a sight of thy sins; for Christ hath enlightened thee,
and given thee a sight of thy sins, which shall be thy condemnation, hating it.
For thou that hatest it, hast it.
And it is thou, that puttest the letter for the light, which was given from the light,
from them that walked in the light; but thou hating the light given thee,
thou knowest not the conditions of them that had the light,
but puttest darkness for light, and light for darkness; and so woe rests upon thee!
It is thou that puttest evil for good, and the woe rests upon thee!
And it is thou that art covered, and not with the spirit of the Lord.
And it is thou that standest not in the counsel of the Lord,
but followest thy own imaginations, that art turned out from God;
and so the woe rests upon thee!
And thy kingdom and crown is pride; and woe is to the king of pride!
And thou art the wicked, that forgettest God, who must be turned into hell;
and livest in perverseness, and art a child of disobedience, who disobeyest the light;
and so the wrath of God rests upon thee.
But who love the light, and walk in the light, Jesus Christ is their king,
whose gospel is preached to every creature.
For death having passed over all men, all in the first nature are children of wrath,
and all in the second are children of God.
The seed is sown upon all sorts of ground; upon the highway ground, thorny,
and stony ground, and good ground.
And Christ hath given to every one a measure, and ability according to his measure;
he that improves not his measure, he hath the eye, and seeth not, and ear,
and heareth not, and heart, and doth not understand.
And he is the thief, that steals the apostles`' words, and Christ`'s words.
And is the drunkard who abides not in the light; gone from his measure,
and so abides not in the doctrine of Christ.
And this light shall be thy condemnation, when the book of conscience is opened,
which should exercise your conscience, which will condemn you.
And the wrath of God abides upon the children of disobedience.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 47.

[.blurb]
==== To Friends in Cumberland, Bishopric, and Northumberland.

All Friends everywhere, who with the light that never changeth, are convinced,
and turned from darkness, in the light dwell,
that ye may come to learn of Christ in the life,
and with it know the movings of the spirit of life in you,
that moves against all the works of death, and so works freedom.
A measure of this living spirit and power being known in every one, and ye kept to it,
with it ye are kept diligent, quick, and lively, to walk in the life;
for it is the life that redeems, which only overcomes, and gives an entrance into rest.
Therefore every one of you know a measure of that spirit, which exerciseth meekness,
truth, and faithfulness in you in power, which, as it is known,
breaks the bonds of iniquity, and scatters the armies of the aliens;
that ye may all know, what it is to follow the Lamb with joy and peace in your minds,
your hearts upright to your guide.
Take heed that none of you walk by imitation of others only.
For though the way they walk in be good to them who are in the light,
yet thou art in darkness, and knowest, not whither thou goest,
nor canst ever receive any strength from God to carry thee on in the way,
nor reward for it; and thy fellowship is not with God in that way, but with men,
and in this way thou canst not be cleansed, but in the end thy labour will be lost.
And of this sort are they that turn back, and speak evil of the way of God,
when the way of God they never came into, nor his life, peace, and power;
that is a way they never knew.
By these the offence comes, and the stumbling block, whereby many are offended:
but woe to such by whom the offence comes!

And take heed of judging the measures of others, but every one mind your own;
and there ye famish the busy minds and high conceits, and so peace springs up among you,
and division is judged.
And this know, that there are diversities of gifts, but one spirit,
and unity therein to all who with it are guided.
And though the way seems to thee diverse; yet judge not the way,
lest thou judge the Lord,
and knowest not that several ways (seeming to reason)
hath God to bring his people out by;
yet are all but one in the end.
This is, that he may be looked to from all the "`ends of the earth,
to be a guide and lawgiver;`" and that none should judge before him.
Deep is the mystery of godliness!
Therefore silence all flesh, and see your own ways be clean; and as ye grow therein,
the way of peace will be more prized by you, and the perfect bond ye will come to know.
And all who are here established, shall stand in strength,
when others fall on the right hand and on the left.

Dear friends, ye have long been convinced, and owned the Lord in word and form;
and look for it, ye must be proved and tried,
not only your faith and patience in persecution by the enemy without,
(for that many of you have escaped,) but proved ye must all be with that which is nearer,
even a falling away amongst yourselves.
And it is good that the steadfastness of all should be known herein.
For many are crept in unawares, who are self-ended, slow bellies,
who love this world more than the cross of Christ, who are got high in the form,
and have great swelling words,
which they can utter for their advantage in earthly things,
deceiving the simple therewith, who are not yet got above the pollution of the world.
And this was ordained of old, for the manifesting of him that is approved.
And with that eye that leads out of the fall, is he seen to be fallen,
who hath got the saints`' words to plead for that which is in the fall to uphold it.
And here the oppressor would set his seat faster than before,
the devil being now transformed into the likeness of an angel of light.
And thus is the scripture fulfilled, "`My little children, this have I written to you,
that when ye see this come to pass ye might not be amazed,
as though some strange thing had befallen the church of God;
but even the same that was of old, to prove you, and to perfect you against the devil:
herein is he made manifest, that ye may know his wiles.`"
And great steadfastness shall it produce to all,
who mind their standing upon Christ the rock,
and have salt in themselves to savour withal.
But that which will not come to the everlasting foundation,
is apt to be tossed to and fro with airy spirits, who are now gone out into the world,
to deceive such whose hearts look back after worldly things.
Therefore stand with your minds girded up to God above the world, lest ye run in vain,
and lose your crown; which none receives, but he that continues to the end.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Let this go to all the churches of the saints.

[.centered]
=== Epistle 48.

[.blurb]
==== To Friends, concerning judging.

Friends, to you all this is the word of the Lord: take heed of judging one another;
judge not one another (I charge you in the presence
of the Lord) with that which must be judged;
neither lay open one another`'s weaknesses behind one another`'s backs;
for thou that dost so, art one of Ham`'s family, which is under the curse.
But every one of you in particular with the light of Christ,
(which he hath enlightened you withal,) see yourselves,
that self may be judged out with the light in every one.
Now, all loving the light, here no self can stand, but it is judged with the light;
and here all are in unity, and here no self-will can arise, nor no mastery;
but all that is judged out.
And let there be no backbiting amongst you; but in love,
ye that dwell in the light and see clear, speak to the others,
whose minds are gone from the light: else, as I said before,
if ye do speak behind their backs, there will be the evil eye and filthy mind,
which dare not speak to their faces.
And so the same mind which doth condemn behind the back, is for condemnation;
and so self should be judged first.
Here ye will be kept watchful in the pure fear and love of God,
and all self will be judged out from amongst you, which would be judging in secret;
which is a work of darkness.

And take heed (I charge you all in the presence of the living God) of a feigned humility,
and a feigned love, which is out of the light,
and then that to use as a customary salutation, or a formal gesture;
which is all for condemnation, and to be kept out, being out of the covenant.
So see that all your actings be in and from the light;
here ye will be kept clean and pure,
and will come to be sealed in the everlasting covenant of God,
with the light which comes from Christ.

And again, I charge you all in the presence of the living God,
not to suffer your minds to go out to contend with them who are not of the truth,
in that which is out of the truth, both which are to be condemned with the truth.
For the same mind will boast and get up,
which is out of the truth and reaches at things in the comprehension,
though it lives not in it, but is excluded out of the truth, and shall not enter;
but is for condemnation.
And so to you all this is the counsel of the Lord God of power and of peace,
that in peace ye may be preserved to wait for the spirit of grace, and of wisdom,
and of understanding.

And Friends all everywhere, met together, waiting upon the Lord,
that your minds may be guided by the spirit of God up to God.
And know the life of God in one another, which all, whose minds are abroad,
are strangers to, and to the covenant of promise;
for the covenant and promise of life is with and to the seed: and there is no sin,
iniquity, or transgression in the covenant; for that is all judged,
being out of the covenant of God.
And therefore all wait,
that ye all may come to witness the covenant of life made with your souls,
and to find the witness, the seal of the spirit, that ye are Sealed to God with,
and that ye may all witness sin and transgression finished,
and blotted out by Christ Jesus, the new covenant of God;
and ye may all come to know the Lord, and to love the light,
which Christ hath given you to teach you; then ye will witness the covenant,
yea ten thousands will witness the covenant, Christ Jesus.
For as the Lord said, "`I will give him for a covenant of light to the Gentiles,
to open the blind eyes;`" and so, this light doth open the eyes of the blind.
All ye that were blind as the Gentiles, or the Jews, ye know,
that with the light your eyes are opened, and ye do see the new covenant,
the unchangeable priest, the unchangeable covenant.
So in that which changeth not, dwell, that that which is changeable and wavering,
may be judged and condemned with that which changeth not.
And though the ministration of condemnation was and is glorious in its time,
yet the ministration of the spirit exceedeth in glory, which changeth not;
and there is no condemnation to them who are in Christ Jesus, the new covenant,
who walk in the spirit.
But who are in that which changeth, running into the changeable ways and works without,
and are in that nature which hates the light, all such are for condemnation by the light,
which is eternal, and never changeth.
And all the beggarly lusts, traditions, and rudiments of men,
which are acted in that nature, contrary to the light,
are for condemnation by the light.

So dwelling all in the light, which is unchangeable,
ye come to judge all the changeable ways and worships, that are variable and changeable,
by that which comes from God, which changeth not; and with his light,
which he hath given, all those things are judged.
So dwelling in the judgment, ye will be filled full of mercy; for first judgment,
and then mercy is to spread over all, that the just may rule over all.

And friends, I charge you all in the presence of the living God,
let no evil communication, nor evil words proceed out of your mouths.
And if ye find the root in you not taken away, that would act such things,
dwell in the light which lets you see the evil communications,
and with the light give judgment upon it in the particular, and first judge it there;
for that is it which corrupts the good manners.
And there are no good manners, but all is corrupted whilst there is evil communication,
and all that profession is abomination to the Lord, whilst that stands.
So, put away all filthy communication out of your mouths, and all wrath, unrighteousness,
and ungodliness, with the light ye will see it all; and walking in the light,
and loving it, ye may judge all that with the light,
and with it come to know the good manners and pure communication.
And walking in this light, it will keep out all evil communication from amongst you,
for the corrupt manners are there, and proceed from that;
and all the profession which is performed in that nature,
whilst the evil communication is standing, is abomination, and for condemnation:
for all the evil manners corrupt, and all their profession is corrupt and for the fire.

So, all walk in the light with which ye are enlightened,
for it will teach you all the good manners and pure communication,
and condemn all corrupt manners and corrupt communication;
and so to have the heart and mind cleansed from all such things.
And all walking in the light, ye have the bosom;
labour to sweep the land from all such corrupt manners and vain communication,
and with the light all that comes to be judged down.
So the light is the judge, and the condemnation; and in the light walk,
and ye will shine.

And, my dear brethren in the covenant of life, keep to yea and nay,
and (call the days,) First-day, Second-day, Third-day, Fourth-day, Fifth-day, Sixth-day,
and Seventh-day, as they were given forth, and called by God in the beginning.
The endless riches ye are made partakers of,
and the endless inheritance ye are come to have a share of,
heirs with Christ of the kingdom that never fadeth away; and ye that suffer with Christ,
shall reign with Christ.
And to you all, friends, who are not come up to the covenant,
and cannot witness that ye are come into it, and sealed,
(by the spirit,) follow no image makers, but the life guiding you, which is eternal,
that will hew down all imaginations, and likenesses, and images, and image makers,
that the glorious God, the Father of life, may be exalted, the ground of all truth.
And friends, none speak abroad, but as ye are moved of God with the spirit of the Lord,
and to that be obedient, as faithful servants,
that ye may enter into the joy of your Lord.
And friends, I warn and charge you all,
that there be no keeping of old things in store in the mind or memory,
or heart-rising one against another, or backbiting among you,
or speaking evil one of another; but judge that out by the light of Christ.
And dwell in the life of God, then ye all in this life of God will have unity.
And beware of, and not suffer that in you to contend which goeth out of the truth;
but by the truth judge it out.
And meet together everywhere, knowing one another in the spirit, and not in the flesh;
and with the spirit of God wait upon God, the Father of spirits.
And, friends, live not on that which is out of the truth, but all be kept low;
that that which is pure of God, and comes from God, ye may live and feed upon.
And that there be no feeding on feigned love, but on that which is pure and eternal,
without mixture or stain; that all the other may be hewn down, and trampled upon,
and trodden down, "`earth to the earth, dust to the dust;`" that ye may all be kept pure,
and in joy, waiting for the eternal riches from the eternal God.
So all to know the ministry and prayer, which is from and in the spirit,
and in it all are one; and by it all the contrary is judged.
And take heed of pride, but by the eternal spirit keep all that down, and judge it.
"`The sacrifices of the wicked are abomination to the Lord, and he hears not hypocrites;
but the prayers of the righteous are heard.`"

[.signed-section-signature]
G+++.+++ F.
