== Epistles 49 &#8212; 76

[.centered]
=== Epistle 49.

Friends, dwell in the life and power of God, which doth teach you to deny yourselves,
which keeps you from all strife, and from all deceit, that nothing may appear,
but by the pure spirit it may be judged;
and that by the spirit of God ye may all be kept up to him, who is a God of order,
and not of confusion.
For all who are in confusion, are in that nature that is contrary to the light,
who are with it to be condemned.
And so the God of life be with you all,
that the fear of the Lord may be set in all your hearts, that the dread, terror,
and fear of the Lord amongst you may remain,
and faith from him ye may all come to receive, and love.
And let love proceed one towards another, from the faith which purifies,
that all actions may be brought to the light, that all deeds contrary to the light,
may with it be condemned;
that in peace and righteousness ye may all grow up in that which is eternal,
guided to him who is eternal, taking all heed to the measure of God`'s grace,
that with it your minds may he guided up to God, the Father of life,
and all your minds with the eternal kept to him, who is eternal.
That the kingdom of God ye may all come to see, waiting in the light, taking heed to it,
which calls to repentance, which informs your minds towards the kingdom of God,
where there is no end, but love, joy, and peace forevermore.
And wait in the light for power to remove the earthly part,
that ye may all witness the kingdom, and joy in the holy ghost;
that with the light your minds may be kept up to God, who is pure,
and in it ye may all have unity, who in the light of life do walk.
For who act contrary to the light, this is their condemnation.
And let no unsavoury speeches, nor profaneness, nor looseness, nor idleness,
nor filthiness be amongst you, but be diligent, serving the Lord in the light;
for all that which is contrary to the light, with the light is to be condemned.
And to you this is the word of the Lord, that with the spirit of the Lord,
that comes from the Father of spirits, ye may all come to witness the spirit of promise,
and set to your seals that God the Father of Spirits is true.
So in the name and power of the Lord Jesus Christ be ye all kept and preserved;
and keep together, and meet together, that ye may grow in the measure of God`'s grace.

[.signed-section-signature]
G+++.+++ F.

And dear Friends, in the eternal dwell, that as the plants of the Lord ye may grow;
and who ye are the vineyard dressers, keep out the subtle and cunning foxes,
who make their holes in the earth.
If ye all dwell in the light, which was before the earth was,
with it ye will preserve the tender plants.

And all Friends, in that which is pure, patiently wait to inherit the substance;
and in that dwell which sees beyond the shadow, types, traditions, and evil lust.
And dwell in the life, that ye may be nourished with living food,
and be kept above the world in the light,
that the son of God be not crucified afresh with
that which turns from the light into the lust.
So, all ye that have a sight of this, and are come hither, wait in the light,
that ye may grow up in the living word, to comprehend the world;
that every one of your souls may come to find its rest, where no burden is,
and the travail in the will of man is ceased.
For all those travails and burdens are among them that act contrary to the light,
and the burden is their own, and the travail is their own;
which is to be condemned with the light which leads up into life.
And so the power of the mighty God of life be with you,
which is raising up his living seed, and the seed is one, which is turning up the earth,
and cleaving it asunder, and removing it out of its place,
and bringing into the faith of Abraham, and to the God of Abraham.
The Lord God be with you that dwell in the light,
whose minds are turned towards Christ the way,
from all that which Christ the light discovers to be evil.
Ye children of the light, seek to turn many to the light,
and to wisdom`'s gate bring them,
that ye may all come to be doorkeepers in the house of the Lord,
and see what must be kept out of his house, and what to receive into the house;
and own no sacrifice but that which is from the living, which is accepted of the Lord.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 50.

All Friends, dwell in that which is pure,
and wait for the power of God to preserve you in that which is pure, up to God.
And know the seed of God in one another,
that the knowledge which is after the flesh may die;
and know the power of God in one another.
Let your faith stand in that which throws out the earthly nature,
and the loftiness of man; which overturns the worldly wisdom and the carnal knowledge,
which is brutish and devilish.
Dwell in that which is pure, that ye may be able to discern, and savour,
and comprehend that which is not pure; and wait in that which is pure,
to have your minds guided thereby, which will let you see God,
and show you your evil thoughts, and judge them; and is a cross to your evil desires,
wills, and lusts.
I say, dwell in that which is pure, which will guide you to God; but if ye lust,
(as aforesaid,) then the pure is veiled, and the light mind speaks at random,
with a drunken spirit, and not from the mouth of the Lord.
And there lodgeth the dreamer, and the lying spirit, and the false prophet,
and that which is like the truth but is not the truth; but dwelling in the truth,
this will be discovered.
And wait upon God in that which is pure, for the receiving of that which comes from God,
which is living, which nourisheth up to everlasting life.
So God Almighty be with you!

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 51.

[.blurb]
==== To Friends, concerning the cross of Christ, the power of God, that leads out of the world, to the world that is without end.

The cross is to the carnal part, which is the ground of images,
the ground of the seducers, and the ground of the false prophet and antichrist;
the cross is to that ground, to the root and life of it.
This being minded, which is pure and eternal,
it makes a separation from all other lovers, and brings to God,
and the ground of evil thoughts comes to be opened, and the cross is to that ground;
which cross overturns the world in the heart.
Which cross must be taken up by all,
who follow Jesus Christ out of the world which hath an end,
into the world which is without end; and all the evil things of the world must be denied.
For "`who loves the world,
the love of the Father is not in him;`" but where the world is standing,
the cross is not lived in.
But dwelling in the cross to the world, here the love of God is shed abroad in the heart,
and the way is opened into the inheritance which fades not away;
where nothing shall enter which is defiled.
For God is not seen but in the eternal light whence all pure wisdom comes.
This treasure is not seen but with the spiritual eye;
nor received but with the pure in heart,
and by those who dwell and abide in the eternal light.
But the carnal heart may get the words from them who had received the wisdom,
who dwelt in the fear of the Lord; but they who live without the fear,
may get their words, and yet know not wisdom`'s gate, whence those words proceeded,
having the old bottle.
Watch all, therefore, and see what ye possess.
For all who gave forth the holy scripture, who dwelt in the fear of God,
they possessed the life which those words proceeded from;
and the secrets of the Lord were with them.
Therefore, all in your measure, which is of God, wait,
that it may guide your minds up to God, and follow it, and not your evil desires,
nor the lust of the world; for the fear of the Lord will keep your hearts clean,
and the true wisdom will be with you in the pure heart.
And every one that hath this light, which Christ hath enlightened them withal,
the deeds that are evil, ye know to be so by the light;
and this light will be their condemnation, ye know it.
And all who witness this light, and love it, their eye is in their head, which is Christ,
if they be ten thousands.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 52.

[.blurb]
==== To Friends in the North.

All Friends in Westmoreland, Lancashire, Cumberland, Northumberland, Bishopric,
and about Newcastle, whose minds are turned to the light, meet together,
and wait upon the Lord, and keep your several meetings in the light of Christ;
that all your hearts may be joined together, and ye all kept in unity up to God,
the Father of lights.
The Lord God Almighty keep you and preserve you,
that ye may all see the blessings of God; for the blessings of the Lord are among you.
And that ye all with the light may know your minds kept up to God,
to receive the wisdom of God, by which all things were made;
that with it ye may come to order the creatures,
and in the wisdom of God ye may be preserved to walk wisely.
And that no deceit nor slothful spirits be amongst you, nor hangers-on, getting the form,
etc. who speak what they are not; all such I do deny,
and with the light all such are to be condemned.
Such cumber the ground, and stain the earth, that it cannot enjoy her sabbaths,
nor yield her increase.
They that are so, and act contrary to the light, are by it to be condemned,
and with it I do them deny, which light is one in all your consciences;
that with the light your minds may be kept up to God,
and all that which is contrary may be condemned to the fire, which is for the fire.
And I warn you all, in the presence of the living God,
to take heed to the measure of the grace of God;
that with it your minds may be kept up to God,
and that ye may all come to profit in the spirit.
And from you all God doth look for the fruits of that spirit,
of which a manifestation is given you to profit withal.
And to you this is the word of the Lord.

O friends! mind the seed of God, and the life of Christ.
And take heed of being hurried with many thoughts,
but live in that which goes over them all, that in it ye may reign,
and live in the seed of God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 53.

[.blurb]
==== Concerning the duty of all Friends in truth.

All Friends everywhere, that have wives, or that have husbands, or that have children,
or that have servants; or servants that have masters, or children that have parents,
that are not Friends, this is to you all, that are in the light,
"`which lighteth every man that cometh into the world,`" that they,
that act contrary to the light, and believe not in it, who know not the word,
and will not be won with the word,
(speaking to them,) that your chaste conversation (ye walking in the light
which comes from the word) may answer to the light in them,
which they hate and walk contrary to; that your chaste conversation may judge them,
and ye may win them by your chaste conversation, walking in the light,
which answereth the light in them wherewith they are enlightened;
which light comes from the word, which casteth down all that is contrary to it.
That they that act contrary to the light, beholding your chaste conversation,
and your good works,
the light which they act contrary to may make them confess to your good conversation,
and glorify your Father which is in heaven; who are born of the light, children of light.
That ye may receive the wisdom from above, which is neither earthly, nor sensual,
nor devilish, with which ye may be ordered to the glory of God,
and with that order all that ye have to order.
And to you this is the word of the Lord.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

Postscript.--"`Honouring all men,`" is reaching that of God in every man,
for that brings to seek the honour of God; the other fades,
and reacheth not to that of God in man; for the saints, which were to honour all men,
were in that of God which reached to that of God in all men.
And they that are not in the spirit of God, dishonour the son, and miscal men,
honouring and setting up that which is out of the truth,
which is to he trodden under foot

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 54.

[.blurb]
==== This is to be sent among Friends, who are in the light.

All my dear brethren, babes of God, born of the immortal seed,
whose dwelling is in the power that upholds all things, which power is made manifest,
which hath brought you to him that was in the beginning, before the world was,
and with the life to comprehend the world, and that which is in it, and what it is,
and what it lies in.
All my dear babes of God, who are in the arms of the Almighty, dwell in the light,
that ye may be manifested to the light of God in all consciences,
that to the light which is of God, people`'s minds may be directed,
and they come to receive the life, and to witness it, that gave forth the scriptures;
that with the light ye may see them who act contrary to the light, who are for the sword,
who are for the hammer, and who are for the fire.
Here not a deceiver shall stand, nor a false prophet, nor an antichrist,
who oppose the light; but with the light all such are seen and comprehended.
Which light is eternal, and was before the world was, which comprehends the world;
which light is one in every man`'s conscience;
which light is the condemnation of all that hate it,
and of all that profession that is acted in that nature contrary to the light.
My babes, dwell in the light, in the immortal seed of God, and grow up in it,
and be clothed with Christ`'s zeal, having his mind;
that with the light ye may see them who are turned from the light,
and act contrary to the light, who with the light are to be condemned.
And so all they that make a profession of the scriptures declared from the light,
and act contrary to the light that comes from Christ Jesus, and yet profess his command,
their zeal is without knowledge, and they will persecute.
For they that are in the self righteousness,
are in that nature that acts contrary to the light,
who with the light are to be condemned; which light leads to Christ,
and brings to witness him, the Lord of righteousness.
Therefore dwell in the light,
that to the light in all consciences ye may be made manifest,
to turn them from the darkness to the light, and so to Christ, from whence it comes;
that with the light every one may see their salvation, Christ Jesus,
and so ye may bring every one to sit under the vine Christ Jesus,
and bring every one into the light, which comprehends the world,
which is the world`'s condemnation, and all them that hate it.
And bring every one to the light, which condemns all evil deeds and works of darkness,
and works of the flesh; that with the light they may all see,
what shall enter into the kingdom of God, and what not.
And bring all into the light, that they may see the false prophets, and the antichrists,
and deceivers, which are all in that nature which acts contrary to the light;
in which light is unity, with which light are they all condemned.
And to you this is the word of the Lord.
And he who turns from the light,
and gets the words of them that knew what they declared from the light,
and makes a profession of them, his knowledge is brutish.
But he who dwells in the light, and with the light sees Christ,
his knowledge is from that which is eternal; with which light the other is condemned,
who acts contrary to it, though he may have the words declared from it.
And all who are turned from the light,
and make a profession of the words declared from the light,
and gather there a great deal of wisdom, yet their minds are turned into the earth,
which is a seat for the devil; there is the sensualness, there is the devilishness,
and earthliness, there is the wisdom that is from below,
which is acted in that nature contrary to the light; with the light that is comprehended,
and with the light that is condemned.
That wisdom is from below.
But the light leads the mind up to Christ, from whence it comes,
to receive the wisdom which is from above, and condemns that which leads from the light,
for that is pure and gentle which is from above; but the other is sensual, earthly,
and devilish, perverse, and envious, and is with the light comprehended and condemned;
which light is against the false prophet, whose words, knowledge,
and wisdom is not from it.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 55.

[.blurb]
==== Concerning the spiritual warfare.

The word of the Lord God to all my brethren, babes, and soldiers,
that are in the spiritual warfare of our Lord Jesus Christ.
Arm yourselves, like men of war, that ye may know, what to stand against.
Spare not, pity not that which is for the sword (of the spirit,) plague, and famine,
and set up truth, and confound the deceit, which stains the earth,
and cumbers the ground.
The dead stinks upon the earth, and with it the earth is stained, therefore bury it.
And wait in the light which comes from Jesus, to be clothed with his zeal,
to stand against all them who act contrary to the light which comes from Jesus,
and yet profess the words declared from the light; which are sayers, but not doers.
All such are to be trodden without the city under foot;
and woe proceeds from the Lord against all such, and the stone is falling upon such,
and fallen, to grind them to powder.
Arm yourselves like men of war; the mighty power of God goes along with you,
to enable you to stand over all the world, and (spiritually) to chain, to fetter,
to bind, and to imprison, and to lead out of prison; to famish, to feed, and to make fat,
and to bring into green pastures.
So the name and power of the Lord Jesus Christ be with you!
And go on in the work of the Lord, that ye may trample upon all deceit within and without.
And all they who are gathered together with the light,
and their minds turned towards Christ Jesus, who doth enlighten them,
that they may all see the Lord Jesus among them, their head, and they his branches;
in the light waiting, and growing up in Christ.
Jesus, from whence it comes, they may bring forth fruit to the glory of his name.
And all waiting and walking in the light, with it ye will see the Lord Jesus amongst you.
And ye will see with the light all that hate it,
who profess Christ Jesus`' words declared from his light, and walk not in it;
by his light are they, and all their profession, condemned.
And to you this is the word of the Lord.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 56.

[.blurb]
==== To call the minds out of the creatures.

All friends of the Lord everywhere, whose minds are turned within towards the Lord,
take heed and hearken to the light within you, which is the light of Christ and of God,
which will call your minds to within,
(as ye heed it,) which were abroad in the creatures;
that by it your minds may be renewed, and by it turned to God,
with that which is pure to worship the living God, the Lord of hosts,
over all the creatures.
That which calls your minds out of the lusts of the world,
will call them out of the evil affections and desires, and turn you from them,
and set your affections above.
And the same which calls your minds out from the world`'s teachers, and the creatures,
and to have your minds renewed, there your obedience is to be known and found;
and there the image of God is renewed, and ye come to grow up into it.
That which calls your minds out of the earth, turns them towards God,
where the pure babe is born in the virgin mind; and the babe`'s food is known,
and the children`'s bread witnessed, which comes from the living God,
which nourisheth up to eternal life.
Which babes and children receive their heavenly wisdom from above, from the pure,
living God, and not from the earthly one; for that is trodden under foot with such.
And all who hate this light, whose minds are abroad in the creatures,
and in the image of the devil, they may get the saints`' words,
(who received their wisdom from above,) in their old nature and corruptible mind;
but such are murderers of the just, enemies to the cross of Christ,
in whom the prince of the air lodgeth, sons of perdition, betrayers of Christ.
Therefore take heed to the light, which is oppressed with that nature;
which light shall condemn (as it ariseth) all that evil nature, and shut it out,
and turn it out of the house.
And so ye will come to see the candle lighted, the house sweeping and swept,
and then afterward the pure treasure will be found;
and then the name of the eternal God will be exalted.
And the same light that calls your minds, which were abroad, out of the world,
the same turns them to God, the Father of light.
Here the pure mind is known, and the pure God is waited upon for wisdom from above;
and the pure God is served night and day, and the peace which hath no end is enjoyed.
For ye may have openings; but your minds going into the lusts of the flesh,
here the affections are not mortified.
Therefore, hearken to that,
and take heed to that which calls your minds out of the vile affections,
and the world`'s lusts, to have them renewed; the same will turn your minds to God,
the same light will set your affections above,
and bring you to wait for the pure wisdom from, God from on high,
that it may be justified; Wait all in that which calls your minds inward,
and turns them to God; and here is the cross witnessed,
that the mind shall feed upon nothing but the pure light of God,
and on the living food which comes from the living God.

So, the Lord God Almighty be with you all,
and keep you all in his strength and power to his glory, over all the world,
whose minds are called out of it, and turned to God, to worship the creator,
and serve him, and not the creature.
And the light of God, that calls your minds out of the creatures, turns them to God,
to an endless being, joy, and peace.
Here is a seeing God always present, who is not known to the world,
whose minds are in the creatures, whose knowledge is in the flesh,
and whose minds are not renewed.
Therefore to you, whose minds are called out of the creatures,
and out of the world and fading things, by the eternal light of God,
the same eternal light which hath turned it and presented it to God,
will bring you to see all these things,
and those whose minds are abroad in the creatures; and so,
judgment will be given upon that, and them who hate the light.

And friends mind the seed of God, and dwell in it,
which will bring you to reign over the world; and dwell in the power of the Lord,
which will keep you clear in your understanding;
that the seed of God may reign in you all, which is but one in all,
which is Christ in the male and in the female, which seed the promise is to.
Wait upon the Lord, to feel the just to reign over the unjust,
and the seed of God to reign over the seed of the serpent, and to be the head,
that all which is mortal, may die; for out of that will rise presumption.
So fare ye well!
And God Almighty bless, guide, and keep you all in his wisdom.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 57.

[.blurb]
==== To a Friend in distress, when the accuser had got in.

In the time of thy weakness the accuser of the brethren is got in;
therefore mind the seed of God to cast him out,
and what may hinder thee from eating the things of the creation.
So do not hear that, but mind the seed of the Lord, and thou wilt feel life and dominion.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 58.

O Friends! look not out; for he that doth, is darkened.
And take heed of lightness; take heed of the world,
and of busying your minds with things not serviceable.
A wise man`'s eye is in his head, but a fool`'s eye is gazing up and down.
Oh! be valiant for the truth upon the earth, and tread upon the deceit!
And keep to yea and nay; for he that hath not power over his own tongue,
his religion is vain.
And take heed of knowledge, for it puffeth up, but dwell in the truth,
and be what ye speak; he that abideth not in the truth, is led by the evil one.
Wait on the Lord, he will perfect his work amongst you;
he that hearkens diligently to the teacher within, denieth all outward hireling teachers.
He that is made the temple of the holy ghost, placeth no holiness in the world`'s temples.
The teachers without exalt the carnal mind, but the teacher within destroyeth it.
There is not a word in all the scripture to hold up the practice of sprinkling infants,
nor the word sacrament, nor to hold up an hour glass,
to preach by for an hour`'s time in a place; but the vain mind doth hold up many things,
which Christ doth not command.
Earth maketh masters, (amongst earthly men,) but let him that ruleth, rule in love;
for the earth is the Lord`'s, and the fulness thereof.
And he that laboureth, let him labour as to the Lord, in love.
So let love be the head in all things, and then the Lord is exalted;
then there is no eye service, but singleness of heart; then all that is done,
is done as to the Lord.
So be faithful in all things, and keep from the world`'s vain customs.
Do not wear apparel, to gratify the proud mind, neither eat nor drink,
to make yourselves wanton; for it was created for the health, and not for the lust,
to be as servants to us, and we servants to God, to use all those things to his glory.
To whom be praises, honour, and glory forevermore,
who hath created all things to his glory, and so to be used and spent.
Do not make profession to be seen outwardly, for Christ was condemned by the world,
and the formal professors, and all his followers are as wonders to the world.
Therefore marvel not if the world hate you, but rejoice.
Look not back, but keep forward, knowing that the world is enmity with God.
Ye that know the light, love one another, and dwell in it, and know one another in it.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 59.

[.blurb]
==== An exhortation to Friends, not to make flesh their arm.

[.salutation]
Friends,

Make not flesh your arm by carnal reasonings, consultations,
and disputings in that part which is above the innocent life,
for that needs none to plead its cause, but God its Father,
who will give you sufficient strength and wisdom at the same hour;
the other shall and will fall before the enemies of the Lord.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 60.

[.blurb]
==== To Friends, to keep in the fear of the Lord.

[.salutation]
Friends,

Every particular, mind that which is pure of God in you, to guide you up to God,
and to keep you in the fear of the Lord,
that ye may receive refreshment from God alone in yourselves,
and grow up in the inward man, nourished and strengthened by that which is immortal.
And delight in that which shows you the deceit of your hearts,
and judges that which is contrary to God, and be obedient to that which is pure;
so ye will see the Lord God present with you, a daily help,
his hand always ordering of you,
and as a shepherd always keeping the dogs from his lambs,
whom he feeds in green pastures, and waters with his heavenly dew of mercy,
who makes them all fruitful.
The cry of want and poverty shall be no more heard in the land of the living, but joy,
gladness, and plenty.
The wearied soul, that hath lain in the pit and in the mire,
and lived in the clouds of temptation, and cried out for want of the Lord,
shall cry plentious redemption, and say, God is our king, who fills heaven and earth,
and the voice of our king is heard in our land.
So fare ye well in the Lord! and the Lord God Almighty
keep you and preserve you in his mighty power.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 61.

[.salutation]
Friends,

Dwell all in the immortal seed of God, which is heir of the promise of God,
and doth inherit the same; so every one of you know the promise of God your portion,
and the power of God your portion, and the kingdom of God, that is everlasting,
without end, and the power of an endless life; being heirs of that, come to inherit it,
knowing it your portion, that ye may possess it,
and increase in the same kingdom and power, and endless life.
Here ye lay up treasure in heaven, where the thief, moth, nor rust comes not.
And know the seed of God, in which is the election, that never altereth nor changeth;
which seed never changeth, neither doth it submit to that which doth change,
but standeth steadfast and distinct from all the changeables.
Which seed endeth all types, figures, and shadows, and variable things,
and typical things, that do change; which seed doth not change, which is Christ,
which keeps above all the inventions, rudiments, traditions, vain talkers, and babblers,
that be in the world, and standeth when they will be all gone and have an end.
In which seed are power, wisdom, and life eternal, that remains forever and ever,
which hath the dominion in the life and power, and unchangeable wisdom of God,
which is pure and gentle from above, and preserving above all the destroying;
which keeps up the heads of the living to life; in that live.
Which seed of God breaks the head of them that go out of the truth, to wit, the serpents.
And here life goes over all in renown and dominion,
and the top stone comes to be laid over all.
So live in life, and the love, and the power of God, which was before man and woman fell;
in that power ye are kept over all outward things, that have been set up,
and are set up in the fall, which cause pride, and contention, and strife; which,
if lived in, keeps out of the power, in which is the saints`' everlasting fellowship,
that stands and remains, and is everlasting, forever and ever.
In which power the living seed lives, and the living babes are preserved;
in which power they have their food from the God of life, which is living,
which nourishes the immortal babes up to the immortal God, with the immortal food;
through which they come to be the living stones, that build up the spiritual household,
who are the church in God; who are brought out of the state,
where Adam and Eve with their sons and daughters are drove from God,
up to God again by Christ, the power of God, who is the way to God,
where the church is in God, that is the pillar and ground of Truth.
So all live in that which brings you up to God, out of the state of Adam and Eve,
and their sons and daughters in the fall.
In that power, (as I said before,) ye will have an everlasting fellowship with God,
and one with another, which power of God was before the fall was.
In that power ye will know one another, and see one another,
in which ye shall ever be together;
in which ye shall see and know your election before the world began.
So farewell.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 62.

All Friends, be low, and dwell in the life of God, to keep you low.
Ye are the salt of the earth, to make it savoury unto God.
Ye are the light of the world.
Therefore walk in the light of Christ, whose light doth justify you,
who then shall condemn you?
Therefore in that dwell, which doth condemn all the evil in the world.

[.signed-section-signature]
G+++.+++ F.

And all Friends everywhere, pray to the Lord to give you dominion over all,
and that in his power, and life, and seed, ye may live and reign.
And all Friends, submit yourselves one to another, in the fear of God,
and be one with the witness of God in all, and look at that,
and that will keep you down from looking at the bad; but looking at the good,
keepeth your minds over the bad, with the Lord.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 63.

[.blurb]
==== To Friends, concerning the covenant of light and life.

Friends everywhere, to the measure of the life of God in you all take heed,
that with it your minds may be guided up to the living God,
from whence light and life come, and virtue, and strength, and nourishment;
so that with the life ye may be kept from that which veils, and clouds, and darkens,
where the mist of darkness cometh over you.
Wherefore to the measure of light take heed,
that with it all your minds may be guided up to the Father of life,
from whence life cometh;
that the knowledge of the glory of God in the face of Christ Jesus,
ye may all come to enjoy.
So that in peace, patience, righteousness, and temperance, and godliness ye may be kept,
and all grow up in brotherly kindness, and be kept from that which causeth strife,
and sects, and divisions; so that nothing may rule, but the light of God among you.
To that which is pure and lowly, take heed, that mastery and strife may be thrown down,
and the evil eye, and the eye that is out from the life of God,
may be known and plucked out; so that the light of the glorious gospel may shine,
and that ye may all know it.
And so, all awake to the righteousness of Christ, the righteousness of God,
whom man was departed from, Christ the righteousness of God,
who "`enlighteneth every one, that cometh into the world,
that all men through him might believe.`"
So, all having a light from Christ Jesus, the righteousness of God,
he is the way to the Father, whom God gave for a covenant of light, life, and peace.
Therefore every one in your measures wait, that ye may see him,
and come to witness the covenant of life and peace with God, receiving his gift,
Christ Jesus, the son and mediator.
So this I warn you all in the presence of the living God,
to wait every one in the measure of light and of life,
that ye may all come to witness the seal of the covenant,
and be led and kept with that which will keep you spotless, and clean, and holy,
and righteous, where power is received from him, who hath given you a light;
so that in the light ye may all have unity, and in it be kept,
and all that which is contrary to it, with it may be condemned.
And in this covenant of light and life, (the gift of God,) know one another,
and him by whom the world was made, who was before the world was;
who is now again manifested,
(Glory and honour forever be unto the Lord!) That the crown, that is immortal,
ye may all come to see and receive, and your own crowns lay down at the feet of Jesus.
And so his light being come to, all your own works are ceased from,
and your own thoughts; which if ye follow them, they will lead you into error.
Therefore wait in the light which comes from him by whom the world was made,
to receive wisdom from him, that in it and with it ye may be preserved from the world,
and out of the world, to him by whom the world was made;
and that wisdom may be justified of her children, and ye kept all low in the fear of God,
from all strife and deceit, and dissention, and pollution, and hypocrisy,
and dissimulation, single with the measure of light which comes from the Father of life.
Every one to feel with the life of God, the arm of the Lord God not to be shortened;
but to reach to every one of you all, and to carry you all in his arm,
and gently to lead them that are with young.
So feeling the presence of the Lord God with you,
ye receive virtue into your souls from the living God,
who nourisheth his own living plant and plants.
So the Lord God Almighty preserve you in the light,
which shows to every one their evil deeds, and reproves for them; this is the true light,
which if ye come to it, and love it, ye come to Christ,
and love him by whom the world was made;
and it will let you see the chief shepherd and bishop of your souls,
and how ye have gone astray, like sheep without a shepherd.
For it is that which restores you to Christ, the bishop of your souls,
who is the prophet that must be heard.
And all who will not come to the light, which cometh from Jesus Christ,
but hate it because their deeds are evil, they do know that the light will reprove them.
Therefore this is their condemnation, the light which is your teacher; who come to it,
and receive it, ye receive Christ, and he giveth the power to become to the sons of God;
which many do witness, blessed be the name of the Lord.
Therefore wait every one in your measure, to know the scripture fulfilled in you,
which came not by the will of man, but was learned of God;
which is for the perfecting of the man of God through faith in Christ Jesus,
and is to be read and to be fulfilled, and to be practised,
which was given forth from the spirit.
Therefore every one wait in the measure of the spirit, to learn of him,
as they did who gave it forth.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 64.

[.blurb]
==== To Friends in the ministry.

All Friends, who are moved of the Lord to speak the word of the Lord,
whom the Lord hath made to be his mouth,
speak not your own words to feed the sensual part of man in your own wills;
for there God is not honoured, and wisdom is not justified.
But ye that are moved to speak in steeple-houses, or to the priests,
(who have not the word of the Lord,
but the letter,) speak the word of the Lord faithfully,
neither add to it with your reason, nor diminish from it with a disobedient mind;
but speaking the word of the Lord faithfully it is sharper than a two-edged sword,
to cut down all deceit, and as a fire to burn up the chaff;
and it purifies you that speak it:
and so as a hammer it will break down all the contrary.
And the word is but one, which sanctifies all, and cleanseth the heart,
and sanctifies and reconciles to God.
And the light is but one; and all being guided by it, all are subject to one,
and are one in the unity of the spirit.
And if your minds turn from the light, and that mind speak of the light,
there gets up pride, and presumption, and the will;
and then ye begin to strike your fellow servants.

Therefore, all dear friends and brethren, be servants to the truth,
and do not strive for mastery, but serve one another in love.
Wash one another`'s feet, take Christ for your example,
that I may hear of no strife among you: but all walk in the truth, and in the love of it,
up to God, for there ye are my joy and crown in the Lord.
Children would be striving; but that which would have the mastery, must die,
and shall not enter into the kingdom of God.
Therefore mind not high things, but fear, and condescend to men of low degree;
for the fear of the Lord keeps the heart clean, and the pure in heart see God.

And, friends, spread yourselves abroad,
that ye may be serviceable for the Lord and his truth,
and get over the head of the wicked,
and trample all that which is contrary to God under your feet;
that ye may answer that of God in every one.
And him, who was promised to be the covenant of God to the Gentiles,
and the new covenant to the Jews, hold forth to them both;
that all may know him their leader to God, and the prisoner to come forth unto him.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 65.

This is the word of the Lord to all Friends, and fellow-labourers in the truth,
who are subduing the earth, and its earthly knowledge, and its carnal wisdom,
and beating down and threshing down that, in hope to get forth the wheat,
and to be made partakers of your hope; I charge you all, dwell in the light,
which doth comprehend the world, their evil ways, their will worships, what they worship,
and what is their end in all their actions: so that ye may yoke the oxen,
and bridle the horses, and tame the wild heifers, and bring them to Christ`'s yoke,
that is, to the light; bring every one unto it, to see their way to salvation,
and with it every one may know their condemnation, who act contrary to it.
Wait all on the Lord, that ye may be settled and stayed in the Lord,
and to grow up in the light, that gave forth the scriptures;
that there may be no stumbling about the words which came from the light.

For no creature can read the scriptures to profit thereby,
but who come to the light and spirit that gave them forth.

Love the truth more than all, and go on in the mighty power of God,
as good soldiers of Christ, well fixed in his glorious gospel, and in his word and power;
that ye may know him, the life and salvation, and bring up others into it.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 66.

All Friends, meet together in the light,
that with it ye may see the Father of life amongst you in your meetings.
And so, the Lord God of power be with you, and keep you.

And the Lord God Almighty give you dominion over the beasts of the field,
and the fowls of the air, the fishes in the sea, and all creeping things.
And the Lord God Almighty be with you all!
Farewell.

And all live in peace, in love, in life, and in the power of the Lord God,
and keep your meetings, every one of you waiting in the power of God upon him;
that in it ye may have unity with God, the Father, and the son, and one with another.

And, dear friends, let wisdom guide you in patience,
and do not strive with any in meetings; but dwell in the power of the Lord God,
that can bear and suffer all things.
And make no strife among Friends, but live in that which makes for peace, and love,
and life, in which edification is known.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 67.

[.blurb]
==== To Friends, concerning marriages.

Whom God joineth together, are with the light (which is eternal) in the unity,
in the covenant of life and of peace, and this marriage is honourable,
and this bed is not defiled.
For the light leads from all whoredom and adultery, which God will judge.
For there is no marriage honourable, but what is in the Lord, and that is in the light;
with which light the covenant of life is known and seen,
and the faith in Jesus (the gift of God) is received: and they that forbid marriage,
are out of the light, and in the doctrine of devils.
And they who are in the light, "`whom God doth join together,
let no man put them asunder;`" for they that seek to do so,
are in that nature which acts contrary to the light.
And this marriage, which is honourable with the children of the light, is seen and known,
who are in the covenant of light, and with the light are turned to the Lord Jesus Christ,
who leads from all the works of darkness.
And none who are in the light, are afraid of their deeds being tried,
but they bring them to the light, to be tried, whether their works be wrought in God.
Now who follow the motions of the flesh, fulfilling the desires of their will,
and go into the lust of the flesh, such are adulterated from the light,
and their marriage is not honourable,
and the children of the light cannot approve of them.
But whom God doth join together, they are led from the evil motions of the flesh;
and the children of the light do approve of and justify them.
And who follow the motions of the flesh, are in the eagerness, lust, extremes, excess,
and the hastiness; and that mind is afraid to declare its work,
though afterwards is forced by constraint: and that the children of light cannot justify,
which is done in that nature contrary to the light.
Therefore the joining together in the light,
the children of the light do honour and justify,
and the light doth not hide from its own; but the darkness hides from the light,
and is afraid to be reproved.
Therefore, all ye children of the light, let your light so shine before men,
that the marriage which is honourable may be witnessed,
and all that is contrary to the light, condemned.
Therefore let all proceedings in such things, where they are intended,
be declared to the children of light, that therewith they may have unity,
and all the motions and works of the flesh may be condemned,
and that the pretence of the spirit`'s moving may
not be a cloak or cover for the beastly lust;
but that all such proceedings may be searched into by the light,
and tried whether they stand in or out of the covenant.

Let this be read amongst all Friends.
The God of peace and love be with you,
that to the Lord of life ye may all be a sweet savour,
and in the wisdom of the Lord ye may all be kept;
watching one over another in that which is pure;
and waiting for the appearing of that which is good.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 68.

[.salutation]
Friends,

Know the life and power of God in yourselves, and one in another,
and to that power be obedient,
to thresh down all deceit within and without you in wisdom,
and in that dwell which comprehends the world; and know the rest,
which is for the people of God, which he that believeth hath entered into.
So know the life that stands in God; and all know the power of God,
for that power shall never be shaken nor change,
but will shake down all that must be shaken and will change.
So in that the Lord God Almighty preserve you, which giveth you to see,
where there is no changing nor shadow.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 69.

[.blurb]
==== To Friends at Malton.

[.salutation]
All my dear friends at Malton,

Mind that which is pure in you, that ye may grow up in the power, out of the form.
And take heed of deceit, and of jarring one with another;
take heed of strife and confusion in your minds.
But mind the pure life of God in you, according to your measures,
to guide you up to God out of the flesh, and all the ways and works of it,
within and without, which that which is pure and holy, calls all unto.
So all walk in the wisdom of God, which is given into the pure heart,
that none of your nakedness may appear, and men see your shame;
but all wait in the spirit upon God the Father of spirits,
to be clothed with his righteousness.
So God Almighty keep you and bless you;
the blessing of the Lord be with you and among you!
I am with you, present in spirit, (joying and beholding your faith towards God,
which ye have in Jesus Christ,) though absent in body.

And all Friends, quench not the spirit of God in you,
but live in the authority of the son of God and his power,
whereby ye may be kept on top of the world.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 70.

[.salutation]
Friends,

I do judge all that in all, which is contrary to the life and power of God,
even the ground and root of all jars and strife, which is not of God,
but is out of the life of God; I judge its beginning and its ending,
and judged it is by the light.
And I do judge with the spirit of truth all foolishness, hastiness, and strife,
which are not of God.
And all friends, wait in the measure of the spirit of God, to guide you up to God,
and keep you all in peace and unity.

[.postscript]
====

Postscript.--Heed nothing but the life and power of the Lord God; for all that is out of it,
is and will be confounded.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 71.

[.blurb]
==== To Friends, to live in the power of God, in Christ that never fell.

[.salutation]
Dear Friends,

All be faithful in the everlasting seed, in which ye have life and power,
dominion and wisdom, and clothing with that which is immortal,
and the blessing of the Lord, and peace in the seed, Christ,
that never fell nor changed, nor will change; in whom ye have peace,
in whom ye have blessings, who takes away the curse.
For the peace is in the second Adam that never fell, Christ Jesus,
and the blessings and the righteousness are in him; but the troubles, and the curse,
and the unrighteousness and misery are in Adam in the fall, and all deceitful teachings,
ways, and worships.
And so, sit not down in Adam in the fall, but in Christ Jesus that never fell,
(then in him ye will all have life,) that was with the Father before the world began.
He ends all the types, figures, and shadows, first covenant, and priesthood,
and ways in the fall, in old Adam, Christ that never fell, who is the way,
who is the substance; in him (I say) sit down,
and then ye will be all found in the endless life.
For Adam lost his habitation and Eve, and the apostate christians from the righteousness,
from the law, and from the power of God.
Therefore ye that are come to Christ Jesus the substance, the end of the prophets,
in whom ye have life,
(as I said before,) which was with the Father before the world began, in him live,
and love one another, and serve one another in love, and in the fear and wisdom of God,
that is above Adam and Eve`'s sons and daughters`' sensual, devilish wisdom in the fall.
And so keep your meetings in the name of Christ Jesus, that never fell,
then ye will see over all the meetings of Adam and Eve`'s sons and daughters in the fall,
their confused meetings and gatherings,
who are out of the habitation of righteousness and holiness, and so out of peace.
So in the life (Christ) live, in whom ye have peace, keeping your habitation in him;
that none be as the untimely figs, nor as the corn upon the house top,
that is soon withered and gone.
But that ye may live in the seed, the substance, Christ the life,
in whom ye have riches that never fade away; feeding upon the tree of life,
whose leaves heal the nations.
So live in unity one with another in the life, Christ Jesus,
that the seed may be all your crowns.
And so farewell.
My love to all Friends in the seed of God, Christ Jesus,
who was with the Father before the world began.

[.signed-section-signature]
G+++.+++ F.

And Friends, in the measure of life, which the Father of life hath given you, wait,
with it to be guided; that ye all may profit in the life and spirit,
that the fruits of it may appear, to the glory of the Father of life.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 72.

[.blurb]
==== To Friends in the North.

Friends, see that all friends professing truth thereaways, be kept in order,
that no confusion, no pride, filthiness, nor uncleanness be amongst you;
but with the light let all that be judged down and condemned, and cast out,
that all in that which is pure may patiently wait to inherit the substance.
And in that dwell which doth bring out of the shadows, types, traditions, ungodliness,
unrighteousness, pride, filthiness, lust, and uncleanness.
So, the mighty power of the Lord God be with you all, and keep you.

And all Friends, dwell in the life which comes from God, the Father of life,
that with it ye may see God,
and all may be nourished and fed with the living food which comes from the living God.
Ye babes of God, dwell in the wisdom of God, and in grace,
that ye may grow up in the wisdom and the grace of God.
So, the mighty power of the Lord be with you all, and keep you in obedience to the light,
out of the evil of the world; which light doth condemn it.

Let this go to all them that dwell in the light, whose minds are turned towards Jesus,
the way to the Father; let that be burnt up which the light doth discover to be evil,
and condemns it.
And to you this is the word of the Lord.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 73.

[.blurb]
==== Concerning Tithes.

All Friends, who are in the eternal light, ye see the figures, the shadows,
and the types,
(the beginning and ending of them,) and with the light ye come
to see the substance of the things shadowed and figured forth.
So all in the light dwell, that with it ye may come to know the ministry of life,
and the ministry of condemnation;
that with the light ye may come to witness the substance, Christ Jesus.
And with the light ye will see what the apostle meant,
when he spake of tithes and offerings, and of the changeable priesthood,
and when he spake of the substance of those things he had before spoken of;
who with the light denied the first priesthood,
the tithes and offerings that were changeable.
And now, with the light, the changeable priests are denied,
and the unchangeable ministry of life witnessed; and the law that gave tithes,
and the commands about them (with the light, ye see) are ended.
And with the light God is seen, who was before those things were;
and the end of those things ye come to see, Christ Jesus,
the sum and the substance of them.
So all ye that are summoned with writs (which come from the courts above) to answer,
because ye cannot pay tithes, keep to the light in you, which comes from Jesus Christ;
that with the light ye may all come to see Jesus, the sum and substance,
and the end of all the before mentioned tithes and offerings.
And so, according to the light of Christ in them all, speak,
that to it their minds may be guided; and declare the truth to them,
which is agreeable to that of God in every one`'s conscience.
And bear witness to the sum and substance, Christ Jesus, and show forth that to them all.
And declare it to the highest judicature in the nation,
when ye suffer for the testimony of Jesus, that ye witness to the substance,
Christ Jesus, who is ascended far above all the principalities and powers;
and that ye witness to the ministry of life.
And show forth the substance to them, (if ye have an opportunity,) showing to them,
that ye suffer for conscience sake.
And so over the world stand, and over all their evil works,
and bring all men`'s works to the light.
And being guided by the light, it will let you join to none of their vain inventions,
that are acted and made in that nature that is contrary to the light;
it will bring you to witness the sum and substance, Christ Jesus, over all the world.
And so, if the spoilers take your goods, let them go, and let them take the coat also.
And keeping to the light which comes from Jesus,
to that of God in every one`'s conscience ye will be manifest;
and keeping clear your consciences, with it all that which is contrary will be condemned.
And so, every one keeping to the light, it will let you pay no tithes to the hirelings,
nor join with them therein; but it will bring you to witness the sum and substance,
Christ Jesus.
For the tithes and offerings were ministered in the first priesthood`'s time,
and it was glorious in its place; but with the light was and is seen, the beginning,
their time, and the end of them, and with the light, the sum and substance,
Christ Jesus is witnessed.
And all in the light dwell to guide you,
that to that of God in all consciences ye may be made manifest;
that they that imprison you for tithes,
and resist the light of Christ in their own particulars, that over them all ye may stand;
being guided by that which is pure, that it may lead you to act,
that no condemnation upon your actions may come.
For who contrary to the light doth act, upon his actions condemnation doth come.
That so over all the world ye may stand in the light,
which doth comprehend and condemn it; and with it ye may witness the end of the shadows.
And unto you this is the word of the Lord God.
And none act any thing in your own wills.
But who act contrary to the light, and pay tithes, go to the changeable;
and with the unchangeable are cast out from the children of light.
And so the children of light are one in the light, and with the light see the body,
and Christ Jesus the head, and are all one in him.
Where did any sue one another for tithes under the first priesthood?
But with the light the primitive christians witnessed Christ Jesus,
the substance of the things typified in the first priesthood`'s time.
To the light of Christ Jesus in all your consciences, which comes from Christ, I speak,
that ye may see what ye act; and that such as are sued for tithes,
may look to the sum and substance, the unchangeable priest Christ Jesus.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 74.

My dear friends, live in the immortal seed and power of the Lord God,
that ye may meet in that, and in that feel one another.
And live in the spirit, in which ye will have unity and peace, and the spiritual weapons,
to cut down the spiritual enemies of your peace.
And dwell in the life and power of God, that ye may have dominion,
and come to witness that ye are the heirs of the power of an endless life,
and of a world whereof there is no end; and so in this keep your meetings.
And dwell in the peaceable seed, which destroyeth that which causeth troubles, wars,
and fightings; in that dwell, which was before that was,
in that will ye have life and peace everlasting.

And living in the seed, ye will see the everlasting commander, that saith,
"`Swear not at all;`" and the witnesses of the true seed say the same.
And this is the command of the royal seed,
which is the everlasting commander among the believers, and to all others;
and they that believe not in the light, it condemns them, being in the evil.
The oath bound to God in the time of the law and the prophets; but Christ,
the oath of God, the everlasting covenant, ends the law and prophets,
who bringeth up to God, and destroyeth the devil, and endeth strife and oaths,
and fulfils the law and the prophets.

And the everlasting command of the royal seed is, to love enemies,
(which the Jews were allowed to destroy,) for ye are all brethren,
not ruling in lordship, like Jews and Gentiles,
but the greatest shall be as the least among you; for the seed is one in all,
and that is the master, who destroyeth the devil.
And to respect men`'s persons is a transgression of the royal law;
let there be no such thing among you.
But let every one believe in the light, and then in it see their salvation;
and ye will receive power to become the sons of God.
Let no one have but one wife, for Christ hath but one, his church, which is his people.

So in the power and in the bed of purity, in the singleness of virginity,
and in the beauty of holiness live, where righteousness, and holiness,
and truth dwell together, and peace in the kingdom of power,
where is the everlasting joy, peace, and dominion, and victory,
where the bed is not defiled, but the marriage that is honourable is known;
in that live.

About am I compassed with the virgins pure, and the undefiled ones are my joy.
The virgins trimmed with oil in their lamps, enter in with the bridegroom.
And all ye virgins pure, lose not the ornaments of the Lord, but wait,
that ye may be married to the lamb in the everlasting marriage,
and remain with him in the world that is without end.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 75.

Dearly beloved friends and brethren, in the power, and life, and seed of God all dwell,
serving one another in love and in the wisdom of God,
that with it ye may be ordered to the glory of the Lord God;
that nothing may reign but life itself, and in it be faithful.
Keep all your meetings, and know the power of the Lord God among you all.

Ye must do nothing for the Lord by earthly policy, nor trust to that;
but wait in the power of the Lord God, and be ordered by that to his glory.
Ye will never be right, till then, and that must keep peace among you.

And take heed of high-mindedness,
for that will puff up that part which should not be exalted;
and if that come up to rule which is for judgment, then it will do hurt.
But when he comes to reign whose right it is, then peace and good will are unto all men;
and no hurt in all the holy mountain of the Lord is seen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 76.

O all Friends! in the unchangeable life and power, and seed of God live,
and be out of the low, earthly, changeable spirit of the world,
which is given to changing and tossing, and tempest and waves, by which dirt is cast up.
Oh! therefore, the life and power of God and his seed live in, which never changeth,
by which every one may stand in the power of God, and in his life and wisdom,
through which ye may all live.
And stand steadfast in the unchangeable life and seed of God,
which was before changings and alterings were;
and which will remain when they all are gone.

So, God Almighty in that preserve you, in which ye may have the blessing among you,
and God`'s wisdom to order you, (both men and women,) to his glory;
that so in his fear ye may be preserved to the glory of God, in his wisdom and life,
in that which doth not change, in which ye may feel the unchangeable fellowship.

And friends, be wise and low, and take heed of abusing the power of God; but live in it,
in the still life, patient, to the answering the good in all,
to the refreshing one of another, and not to the stumbling.
But mind that which keepeth in unity, in the life, though never so little.

[.signed-section-signature]
G+++.+++ F.
