== Epistles 77 &#8212; 106

[.centered]
=== Epistle 77.

Friends, in the measure of the life of God wait,
to guide your minds up to the Father of life, where there is no shadow nor changing.
As ye come hither, ye must know a removing and changing of that which will change,
with that which doth not change; to that take heed to guide all your minds,
that none be found naked.
For who are found naked, they are in that which hath an end, and doth change,
and that causeth blindness.
And therefore to you all this is the word of the Lord: in the measure of the life wait,
that it may join your hearts unto the Father of life,
that clothing and righteousness ye all may come to receive,
and come to feel your strength renewed from the God of all strength,
to every one of you according to your measure, and see him that shows mercy.
And so live in peace, which comes from the God of all peace,
who bruises Satan under your feet, who hath ruled.
So here the love of God will come to be shed abroad in your hearts, which love is one,
and doth not change; in it dwell, and grow and abound,
that over all that which is contrary to the Lord of life, who destroys death,
ye may reign every one over your own hearts, and lusts, and vile affections,
and your former vile conversation, disposition, and nature, and wills.
So that ye may come to know the saints`' state, unto whom all things were become new,
and the old things were passed away; and that which doth not change, which is new,
that mind, to guide all your minds up to the living God, from whence light, life,
and power come.
So in it the Lord God of life preserve you,
that to him ye may be a sweet smelling savour; for that which will corrupt,
and doth corrupt, and will grow ragged, and come to be torn, and will die of itself,
and will wither, fade, and stink in the nostrils of God,
is that which is contrary to the measure of the life of God,
and is with the light condemned.
Therefore wait,
(I do warn you all in the presence of the living God,) in the measure of the life of God,
in it to grow up in love, in virtue, and in immortality, in that which doth not fade,
which joins and unites your hearts together;
and that all that may with the light be condemned, which is contrary to it.
For that which doth defile, is out of God`'s kingdom,
and is with the light seen and condemned; in which light the children of the light walk,
and have unity one with another, and with the son of God, from whence it comes.

And, my dear friends, keep your meetings, and ye will feel the seed of God among you all,
though never a word be spoken among you.
But be faithful, that ye may answer that of God in every one.
And do not neglect your talents, but be faithful in the power and life of God,
which ye have received.
And dwell in the life, and power, and love of God one with another.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 78.

Friends, in the power and life of God dwell, in unity one with another,
that with the life of God ye may answer that of God in every one.
And keep down and low, that nothing may reign but life among you;
and unto the power of God be obedient.
And, friends, the going from the life and power into the changeable things,
there is the strife, which the life is over; by which power of God all things were made,
wherein wisdom is received to order all things to his glory.
So, the seed, Christ, in you all know, which goes over the earth,
and inherits the promise of God; that ye may be all heirs of the promise of God.
And cease from your own words, but in the power live; for it breaks down rocks,
mountains, old and sandy foundations, and the bond of iniquity,
and makes up the breach between God and man, and breaks down that which made the breach.
So the seed know one in another, which seed is Christ;
who according to the flesh was of Abraham, and according to the spirit, the son of God.
And this is the word of the Lord God to all Friends,
and a charge to you from the Lord God, to live in peace one with another,
and that the peace, life, and wisdom of God may rule you all.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 79.

[.blurb]
==== To all Friends, to abide in their callings.

To all dear Friends, who are called, who are enlightened,
whose minds are turned from the world`'s worships and teachers,
having your eye to the light and guide within,
which is leading you out of this dark world, and your old, vain conversations,
towards God and the world which is without end;
mercy and peace from God the Father be multiplied among you!
Every one of you abide in your calling, waiting upon God where he hath called you.
And take heed of reasoning with flesh and blood, for there disobedience, pride,
and presumption will arise; and there ye will grow up to be trees that bear no fruit,
and as a fig tree which beareth leaves and no fruit, and as wells without water.
Oh! therefore, mind the pure, which would lead you out of this corruptible, heathenish,
dark world and its vain ways, and from destruction and death to life.
And so the Lord God of power bless you, guide you,
and preserve you on in your way towards the holy city,
being called out of the unholy city; for he that hath called you is holy.
Now many are called but few are chosen.
Oh! therefore, abide in that which hath called you,
(which is holy and pure,) up to him who is holy and pure,
and let the time past of your evil ways be sufficient,
wherein ye have lived in wickedness, and in the ways of this untoward generation;
lest your minds turn back into Egypt and the world,
and so cause the worthy name of the Lord to be blasphemed,
(which hath called you,) by turning aside, and growing into hardness of heart,
and turning from a pure conscience, and making shipwreck of it, and of faith.
For ye may see, how far many may go, and did go, and were led out of many things;
yet did turn again into the world.
So mind your present guide, and your present condition, and your call,
what ye are called from, and what ye are called to;
for whom the Lord hath called and chosen, are the Lord`'s freemen.
And so, abide every one in your calling with God, where God hath called you,
and there walk in newness of life, and not in the oldness of the letter;
for he that turneth from him that calleth, walks not in the life of God.
Therefore, all Friends, walk in the truth and in the love of it up to God;
and every one in particular mind your guide, that ye may grow up in wisdom,
and improve your own talents, and the gift which God hath given you.
And take heed of words without life,
for they tend to draw you out of the power to live above the truth,
and out of your conditions; which nature will not have peace, except it have words.
But every particular submit to that which is of God in you, to guide you to God.
And be ye all servants to the truth, and diligent in your callings,
and serve one another in love, in which ye can wash one another`'s feet.
So, serve one another in love, and do not lavish out yourselves without the fear of God;
such are clouds without water, which have the words but not the power,
flown up into the air; which have a light, and yet are as wandering stars,
which lead up into the presumption; and thou that art there, thy garments are defiled,
for thou goest from the spirit which should sanctify thee;
for ye are sanctified through obedience to the spirit.
Therefore every particular, walk in the spirit and obey it,
then ye will all have unity one with another in the spirit, and ye will see, knowledge,
tongues and prophecies shall cease; but he that cometh to the end,
to him who openeth all truth, is blessed.

Therefore, all friends, obey that which is pure within you,
and know one another in that which brings you to wait upon the Lord;
that ye may all witness a living soul, and yourselves to be come out of death.
For these things ye must all find within, there is your peace,
and there refreshing comes into your souls from the Lord.
And standing still in the light within, and therein waiting, ye will see your saviour,
Christ Jesus, raising you up out of death; by which work he is glorified.
For the works of the Lord praise him, which are wondrous to the world.
Now every one in particular, mind the pure in you,
for the chaste virgins follow Jesus Christ, the lamb of God,
who takes away the sins of the world; and who are not chaste, will not follow him.
For that in every particular of you, which is not chaste, will not submit to the pure,
which would guide you to God, but rather submit to their own thoughts, and follow them,
and run after them and their own wills, and seek to accomplish them;
and so run out into that generation whose thoughts were not as God`'s thoughts,
nor ways as God`'s ways.
Therefore watch all, and abide all in your callings;
the light is that which will let you see your transgression and your running aside,
and the by-paths and crooked ways, and the generation of serpents and vipers.
And this light is Christ, which showeth these things.
Now, before these things be known and judged of aright,
judgment must be brought forth into victory, and set up in the earth,
where this state is witnessed.

Now the woman, (which is the church,) must be subject to her husband in all things.
Jesus Christ is the husband; in everything she must be subject to him.
Who are in the flesh know nothing of this in the first nature,
for it is the mystery which the apostle speaks of; and so it is a mystery still,
but where it is opened and made manifest, such are subject to the husband Christ Jesus.
Now take heed of getting these words into the comprehension,
and the light mind speaking them, there is danger;
but that ye may all wait to be comprehended of, and to walk in the truth.
My little children in the Lord God Almighty, this is my joy,
that ye be all ordered and guided by the mighty power of God, and dwell in it,
and know it in one another, and know the voice that speaketh, and the sound of the words,
and power of them.
For words without power destroy the simplicity, and bring up into a form,
and out of the obedience of the truth.
And therefore, walk in the power of the truth,
that the name of the Lord God may be glorified among you,
and his renown may be seen in you and among you, and all the world may be astonished,
and the Lord admired in ordering of his people, who are guided by his wisdom,
and in it found.
And take heed of running out, to make conceited ones wise;
for then thou wilt consume that which the Lord hath given thee upon their lusts,
and so give holy things unto dogs, and a pearl to a swine for want of wisdom, and savour,
and salt, and discerning.
Therefore have salt in yourselves, and be low in heart; the light is low in you,
and it will teach you to be low, and to learn that lesson of Jesus Christ,
to the plucking down all the high thoughts and imaginations.
And take heed of strife in your minds; and if there be, then glory not,
for it is the vain mind, and it is not good.
Let no strife be amongst you, and let none seek for the highest place,
for there is the separated Pharisee; but be lowly-minded,
condescending one to another in a low degree, and bear one with another in patience;
and be not high-minded, but fear.
And all who are servants, labour in love, as unto God, for "`the earth is the Lord`'s,
and the fulness thereof;`" and labour in singleness, as unto the Lord.
And all who have families, rule in the power and love of God,
that that love may be head among you.
For the time is coming, that it shall be, "`as with the servant, so with the master;
and as with the maid, so with her mistress.`"
For it is one seed that hath raised them up with one power, out of one grave, one death,
which seed all the promises of God are to; and as thou passest out of death,
thou shalt witness the promises of God fulfilled, which are to the seed,
destroying the one and raising up the other in thee.
So all Friends, this is to you who know the voice of the living God,
and know your calling, stand fast, and waver not, lest ye lose your recompense of reward;
but stand fast, that ye may receive the recompense of reward.
For God is just in all his ways, and abideth faithful.
Turn not aside, lest he whet his sword, and cut you asunder; for ye that do,
the woe followeth you.

Therefore, all Friends, mind that which is of God in you, which is pure,
which is but one, to guide you to the Father of life, who gives you food, and raiment,
and strength; that ye may gather strength, and flourish,
and your souls delight themselves in fatness,
and feed and eat of the abundance of riches with
him and from him which filleth all things,
and of the daily bread which cometh from above, which none can feed upon,
but who are above the world; for who are below, never could nor would,
but are ready to stone them that confess, they eat of the bread of life,
and would give of it to them.
Dear friends, wait upon the Lord, that all of you may grow up in the inward man,
and be comforted and cherished there, in the things that be eternal.
So with bowels of love to you all, I rest.

Read this among Friends, who have an understanding, and are called of the Lord;
and so farewell!

And stand in the will of the Lord, and be obedient to him.
And the grace of our Lord Jesus Christ,
which teacheth you to deny all ungodliness and worldly lusts,
that grace fill and establish your hearts,
that your hearts may grow up in that grace to God, from whence all gifts and graces come.
Amen.

And all Friends, take heed of unruliness, and vain talking and talkers,
for such are not obedient to the truth; therefore avoid and shun it and them.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 80.

[.blurb]
==== To seek the kingdom of God first.

Friends, seek the kingdom of God first, and the righteousness thereof, and those things,
"`what ye shall eat, and what ye shall drink,
and wherewith ye shall be clothed,`" will be added, and will follow.
Therefore take no thought, what ye shall eat, nor what ye shall drink,
nor wherewithal ye shall be clothed; for the Gentiles seek after these things,
who seek not after the kingdom of God and the righteousness of it.
But seek ye first the kingdom of God,
and the righteousness of it And consider the lilies of the field,
and who clothes the earth with grass, and who feeds the young ravens, when they cry.
And the kingdom of heaven being sought after, and the righteousness of it,
he that is here lives out of the creatures up to the Creator,
which differs him from the people of the world, who take thought,
(which thoughts they live in,) "`what they shall eat, what they shall drink,
and what they shall put on.`"
And they that be there, are out of the wisdom of God, which the saints are in,
that have sought and found the kingdom of God and his righteousness;
which (wisdom) brings them to use the creatures to his glory; whether they eat,
or whether they drink, all is done to the praise and glory of God.
Such as abide there, can do nothing against the truth,
which truth hath made them free indeed;
who into the kingdom of the dear son of God are come, which is without end,
who over the kingdoms of the world reigneth.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 81.

All Friends everywhere, to you this is the word of the Lord God:
dwell in the life and power of God, and the seed of God,
which inheriteth the promise of God; that all light, hasty, airy,
drunken spirits may be limited and stopped, and judged,
and all foolishness and unsavouriness, and confusion,
(which causeth distraction,) the cause of it may be taken away,
and all ye kept in the authority and power of the truth,
that know the power of God manifested among you.
And ye knowing it, and the life, dwell all in it, and abuse it in nowise;
but wait for the wisdom of God, that it may be justified of her children,
and God glorified, and honoured, and exalted,
and the preciousness of his truth considered well of, which ye have bought;
and do not sell it for changeable things, for things that pass away,
and subsist but for a time.
But as the glorious truth is springing and manifest among you all,
live and walk worthy of what ye are called unto,
the high calling in God and Christ Jesus, above all the world,
out of all that which doth change, where the life that is immortal is felt,
and a crown that fadeth not away, a crown of life that endureth forever!
Live in the dominion of the life that is hid in God,
and every particular know it in one another.
And live in the power of God, and of life, that ye may see over the day of tempest,
over the day of darkness, and blackness, and mists: and feel, and know,
and come into that which comprehends the world; that ye all may be guided with wisdom,
and ordered to God`'s glory.
And be all obedient to the truth, which all the enmity is out of;
and know the life of God in you all, that with it ye may all be guided,
and your hearts joined together up to God, the Father of life;
that ye may all be inheritors of the power of an endless life, and of the world,
where there is no end, and possessors of substance.
And feel the seed of God in you all, which inherits the promise from God;
which seed is atop of the serpent`'s head.
And keep that under that feeds upon dust, which the glory and life are over;
which seed breaks the strength of all men, and inherits the strength of the Almighty,
the possessor of heaven and earth; which seed is Christ,
that gives the dominion over the first Adam, over the earthly,
and brings down all that which stains.
So feel the seed, which is Christ in you all,
and ye all will feel the Lamb of God "`which taketh
away the sins of the world,`" who gives to see,
where there is no shadow, nor change, nor altering, nor variableness;
wherein ye all may come to inherit the blessings from God, and come into the living way.
For whose way dies, they err from the living principle of God in them;
for who walk in the way that lives, they answer the principle of God in every man;
though they act contrary to it that are in the way that dies, and do not live,
but change and alter: and to you this is the word of the Lord.
So the Lamb must get the victory in every one of you,
which is Christ in the male and in the female; who brings into the Father`'s house,
(from all the congregations of the dead,
and their houses of darkness,) wherein every one comes to have his mansion,
and his food of life from God the Father of life, who is blessed forevermore!
Whose kingdom and glory is revealed and revealing, and setting up in the life, and power,
and wisdom of God.
The Lord God Almighty preserve and keep you all in love,
in peace and unity one with another, in the light and covenant with God,
and one with another; which light is the condemnation of all that hate it.

And my dear lambs, and babes, and plants of the Lord God,
dwell every one of you in your own, that ye may feel the precious springs of God.

And, friends, all dwell in the authority of the truth, the power of the son of God,
and feel the power and dread of the Lamb, which is to subdue all other powers.
All power in heaven and in earth is given to the son;
and his authority stands over the world, and will subdue it,
and make the kingdoms of the world to become the kingdom of the son of God.
So, live in love, meekness, patience, and in the power and wisdom of God,
which are over all the world.

Sound, sound the trumpet of the Lord of hosts, whose terrible day is come and coming,
and pleading with all flesh by fire and sword.

The mighty day of the Lord is coming upon all flesh,
that all hearts shall be ripped up and made manifest: therefore whilst ye have time,
repent.

This is the message of the Lord to all nations,
let all your laws be according to that of God in all consciences.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 82.

The word of the Lord to all Friends, who are brought into the eternal truth of God,
whose minds are guided out of the earth up to the Lord,
(whose it is,) and have received wisdom from God;
that with it ye may come to know how to order the creation
with the wisdom by which all things were made.
This I charge you and warn you all in the fear of the living God,
that no creatures be destroyed through slothfulness, laziness, and filthiness,
nor upon the lust; for if ye let that rule and be set up, that is for condemnation,
and that which sets it up, is for condemnation with the light, that leads to the wisdom,
by which the creation must be ordered.
And, friends, to the light in you all I speak:
see that there be no slothfulness amongst you, but all keep in diligence and liveliness;
for he that is slothful, and gets the form, may have an easeful mind,
but is an evil example: and all such must be judged with the light,
that they may come to know the servant`'s place, and be diligent.
And such who have gone up and down a begging, if ye have received any such amongst you,
with the light, which hath convinced them, see that they be kept in diligence,
and not suffered to wander, but be kept in obedience to the light,
to receive the wisdom from God, how to labour in the creation;
and see that they have things decent and necessary, and their nakedness covered,
that no reproach nor shame may come upon the truth amongst such as are without;
but that with the light all such may be condemned who act contrary to it:
that in the light which condemns the world, ye may walk,
and receive the light of the son of God, which the world stumbles at,
which is their condemnation, and in which the saints have unity.
And all being kept diligent, and walking in the light, there will be no slothfulness;
and then none shall have self-ends in receiving any,
but those ends shall be judged with the light which is eternal.
Nor no one can come in amongst you, which hath such ends, to make a prey upon you;
but ye dwelling in the light which is eternal, he is judged, and his self-ends,
with the light which is eternal; which is one with the light in his conscience,
which condemns him.
Then if he own his condemnation, he is to be received amongst you in the light,
in which ye all have unity with Christ and with God.
And to you this is the counsel of God.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

To go amongst Friends everywhere.

====

[.centered]
=== Epistle 83.

Dear friends in the eternal truth of God,
whose minds by the light of Jesus Christ are turned towards God,
meet often together in the fear of the Lord, and to the light take heed,
that with it all your minds may be kept up to God, from whence it comes.
And in all your meetings wait low in his fear,
that ye may come to know the life and power of truth one in another.
And all ye whom the Lord hath made overseers over his church in your several places,
be faithful to the Lord, and watch over the flock of Christ with all diligence;
ye which are strong watch over the weak, and stir up that which is pure one in another;
see that all your meetings be kept in order.
Be faithful unto the Lord where he hath set you, and ye shall not lose your reward.
Servants, be faithful unto your masters, not with eye service,
serving them as men pleasers, but in singleness of heart, as unto the Lord;
that ye may come to undo the heavy burdens; being faithful in your places,
where the Lord hath set you, there is your right service.
And take heed of forward minds, and of running out before your guide,
for that leads out into looseness; and such plead for liberty,
and run out in their wills, and bring dishonour to the Lord;
and the unbridled will gets at liberty, and an exalted spirit gets up, and pride,
and haughtiness, and high words.
And such are they who add to the burden, and do not take it off.
Therefore all wait low in the fear of the Lord, and be not hasty nor rash,
but see the way be made clear; and as the Lord doth move you, so do,
and return with speed, (when ye have done,) to the place where ye were abiding,
and be faithful there; that the truth of God be not evil spoken of through you,
as they speak of vagabonds and wanderers, that it may not be so among you.
For such are vagabonds and wanderers, who run before their guide.
And masters rule over your servants in love, with all diligence and meekness,
knowing that ye have one master in heaven.
And friends, in all places, where any go abroad, as they pass by examine them,
whither they are going, and what about?
And if they cannot give a good account, exhort them to return back,
and abide faithful in their places until they see their way made clear.
So farewell in the Lord.
The eternal God of power and wisdom direct and guide you to his eternal praise,
that his name may be honoured and glorified in you and through you all!
Be diligent every one in your places, where the Lord hath set you,
for the work of the Lord is great;
and God Almighty keep you to be faithful labourers in his work.

From one who is a lover of your souls, and whose care is over the church of God,
that it may be kept in order, and that all, that are guided by his spirit,
may be led into all good order.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 15th of the 3d month, 1655.

[.centered]
=== Epistle 84.

[.blurb]
==== To Friends, to sit tinder their own vine.

My dear Friends, sit every one of you under your own vine,
and there none shall make you afraid;
and in that ye will bring forth fruit to God abundantly, to his praise.
And as ye abide in the vine, ye will all become heirs of Christ,
and come all to know the seed,
which is heir of the power of the world where there is no end, and heirs of the kingdom,
and so possess that.
And live in the seed, the top stone, which was before enmity was,
in which ye will feel unity and virtue, and love and peace; in that keep your meetings.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 85.

[.blurb]
==== An Epistle to Friends, that with the light they may see their salvation.

[.salutation]
Friends,

All to the light, which Jesus Christ hath enlightened you withal, take heed,
that with the light of Christ, the saviour of your souls,
ye may all come to see and enjoy rest; and the new covenant ye may all witness,
where ye need no man to teach you, saying, know the Lord.
And this light shows you sin, and the evil of the world, and the lust of it,
and the vain fashions of it, that pass away, and the unrighteousness,
and the ungodliness of it; for they are not in covenant with God,
but are contrary to the light, and to be condemned with the light.
Therefore to the light I direct you, that with it ye may see yourselves;
then in it stand, that with it ye may see Jesus, from whence it comes.
And join not with your vain thoughts, nor that which doth consult,
and set and frame ways; there is the idol maker, and the image maker,
and the founder of the images, whom ye will see with the light, if ye take heed to it.
And so, the founder of the image will be destroyed,
and with that ye will come to hear the voice of the son of God;
and who hears his voice shall live.
And Stephen, who was stoned to death, witnessed the substance,
and Moses`' words fulfilled, who said, "`Like unto me will God raise up a prophet,
him shall ye hear.`"
He heard this prophet, and denied the first temple and priests; and so,
to deny that which God had commanded was more than to deny these which God never commanded.
Therefore consider in your life time, how much time ye have spent in hearing them,
and what assurance ye have of the eternal inheritance which never fades away!
G+++.+++ F.

[.centered]
=== Epistle 86.

[.blurb]
==== To Friends in London.

There is something drawing towards you, see to it.
Take heed of the earth, and keep atop of that which will cumber the mind;
and dwell in love and peace one with another.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 87.

[.salutation]
Friends,

In the power of the Lord go forth, and gather with it into the fold,
and spread the name and truth of the Lord abroad; and in his service be diligent,
and for his truth be valiant on the earth, and for his name`'s sake.
And dwell in that which will pierce the hearts of the heathen,
and will overturn their heathenish customs, and take away their false covers;
and in that power of the Lord be diligent,
answering the witness of God in all consciences.
And dwell in peace and love amongst yourselves; confound the deceit,
and bring the truth over the heads of the heathen,
to the answering the witness of God in them all.
And that is the word of the Lord to you.
And live in the seed,
and there ye will feel the ministry of the life and spirit in your own particulars;
in which ye may be serviceable to others that are without, and amongst yourselves.
And let the heathen know that the plagues, and curses, and wrath,
and woe are unto them that live out of the truth; for wrath, envy,
and strife is out of the truth,
and the vengeance of God is due to them that do not obey it, where is the burning,
flaming fire.
And let them know that the glory of the Lord is risen.

And walk in the power of the Lord, and in his wisdom, that in places where ye do come,
ye may season them, and be all of a good savour in the hearts of all,
and to the Lord a blessing in your generation.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 88.

[.salutation]
Friends,

Meet together, waiting upon the Lord, that nothing but the life may reign among you;
and that in life, love, and wisdom ye may grow up.
And in the measure of the grace of God all wait to guide your minds up to God.
And all Friends, I do lay it upon you to see, that in order all your meetings be kept.
So the Lord God Almighty keep you all to his glory, in his wisdom to himself.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
To be read among all Friends at their meetings.

[.centered]
=== Epistle 89.

[.blurb]
==== For Plymouth.

[.salutation]
Friends,

Keep your meetings, that in the truth ye may reign, and in the power spread it abroad.
And keep in the truth, that ye may see and feel the Lord`'s presence amongst you;
and for it be valiant upon the earth, and know one another in the power of it.
So the Lord God Almighty preserve you in his power to his glory!
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 90.

[.salutation]
Friends,

All ye whose minds are turned with the light towards Jesus Christ, from whence it comes,
in it wait, that with it ye may all see Jesus,
and all that condemned which is contrary to it;
that so by that ye may be kept from all extremes, passions, agonies, and hastiness,
presumption, and desperation.
For dwelling in the light which doth never change,
this keeps your minds out of all those things before mentioned,
which lead nature out of its true course;
and with the light all that is seen and condemned, which is contrary to it.
And that which doth condemn, keeps you in peace and order,
and leads to the door of mercy, and nature into its right course,
and into the virtue of that word by which the creatures were made,
and with it to use them all to his glory.
Which light is the condemnation of the carnal wisdom and knowledge of the wicked world,
and the condemnation of the disobedient,
and the condemnation of them whose deeds are evil, who hate the light.
Which brings to witness the word to be as a fire,
to burn up that which is to be condemned, and to the purging of the floor,
and burning the chaff with unquenchable fire,
and to the gathering of the wheat into the garner.
Therefore, in this light dwell and wait, from which the true words did proceed,
that with it all those words may be opened again,
and all they condemned with the light which have the words, and act contrary to it;
such must go empty away.
And to you this is the word of the Lord,
that ye may come to have savour and salt in yourselves.
For dwelling in the light, ye will be manifest to the light in their consciences,
(though they hate it,) who have the words declared from the light;
such go empty away from God, who is light.
And all they who abide in the light of the Lord,
see all such to be out of the true course of nature, who act contrary to the light,
which defiles the flesh;
and they are such who were of old ordained to condemnation with the light.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 91.

[.blurb]
==== A General Epistle for Friends, concerning the Priests.

All Friends, in the spirit of the living God wait upon God,
to learn of and to be taught by him.
For now doth the beast open his mouth in blasphemy, speaking great swelling words.
And now is the cage of unclean birds, and the unclean spirits,
which are gone forth into the earth, seen.
And now are the locusts seen, and the caterpillars known.
And now are the seven thunders uttering their voices.
And now are the hailstones falling,
and the vials of the wrath of God pouring out upon the beast and the false prophet.
And now are the whited walls seen, and the painted sepulchres,
who garnish the sepulchres of the righteous, and build the tombs of the prophets,
full of dead men`'s bones.
Now are the inwardly ravening wolves seen, which have gotten the sheep`'s clothing.
And now are the false prophets seen,
which through covetousness make merchandise of the people.
And now are the thistles, and briars, and thorns, where the figs do not grow, seen.
And now are they seen which make merchandise of the words of the prophets, Christ,
and the apostles, and through pretence make long prayers; who devour widows`' houses.
And now are such known, who lead silly women captive, who are always learning,
and never able to come to the knowledge of the truth, some thirty, forty,
some sixty years.
And now are such known and seen, and manifest with the light, that Christ spake of,
that should beat his followers in the synagogues,
and hale them before magistrates for his name`'s sake; yea, if they killed them,
should think they did God good service.
And now are such teachers seen and known, that sport themselves in the daytime,
and walk after their own ungodly lusts.
And now such are seen that go in Cain`'s way, who would murder,
and do murder in their hearts, who are in envy, who are the vagabonds, and the fugitives,
who have not a habitation in God, who is love.
And now are such seen and known, that go in Balaam`'s way,
that love the wages of unrighteousness, gifts and rewards.
And now are such seen and known, that bear rule by their means,
and the people love to have it so;
holding up the horrible and filthy thing committed in the land, as in Jeremy.
And now are such shepherds seen and known, as seek for their gain from their quarters.
Now are such seen and known, as seek for the fleece and the wool,
and make a prey upon the people; and such as are hirelings,
which the Lord sent Ezekiel and Micah to cry against.
And now are such seen and known, which our Lord Jesus Christ cried woe against;
who stand praying in the synagogues, having the chiefest seats in the assemblies,
called of men masters, which devour widows`' houses.
And now are such deceivers seen and known,
that by their lies and lightness have caused the people to err;
which speak a divination of their own brain, and use their tongues, and say,
the Lord sent them, when he never sent them.
And now are the mockers and scorners come, which the scriptures speak of, which mock,
stone, and persecute the children of the light, as they pass up and down the streets;
and many have been almost murdered in the highways and steeple-houses by them.
And now is the scripture fulfilled, which saith,
"`That the beast and the dragon shall make war against the
lamb and the saints;`" for such are manifest now,
who are as natural brute beasts, what they know they know naturally,
having not the life that gave forth the scriptures; but are found in the self-separation,
(from the spirit of God,) having gotten the words,
which were declared from the spirit of God, murdering and destroying,
(as much as in them lieth,) those that are in the
light and life of those holy men of God,
that gave forth the scriptures.
Now the shame of all their profession is seen, which is abomination unto the Lord,
who profess the words declared from the light of God,
but are strangers to the light and life.
And now the unsavoury things are smelled, tasted of,
and seen to be among many of the professors of religion, who are more like swine rending,
and like dogs biting and devouring one another, than like the children of the light.
Which doth manifest them to be contrary to the light; which all that are contrary to,
with the light are condemned.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 92.

[.blurb]
==== To all the seed of Abraham, who suffer for denying the world`'s customs, and because they cannot hold up the corrupt priesthood that is therein; or for testifying against the world, that the works thereof are evil.

All Friends and brethren everywhere, that are imprisoned for the truth,
give yourselves up in it, and it will make you free,
and the power of the Lord will carry you over all the persecutors,
which was before they were.
For since the beginning hath this persecution got up;
therefore live and reign in that power which remains when the other is gone,
and in that ye will have peace and unity with God, and one with another,
who suffer "`for not putting into the false prophets
mouths,`" and for crying against them,
and for not swearing, and not giving the world`'s compliments and their honour,
which the Lord is staining; and who are suffering for reproving sin in the gate.
Be faithful in the life and power of the Lord God,
and be valiant for the truth on the earth, and look not at your sufferings,
but at the power of God, and that will bring some good out in all your sufferings;
and your imprisonments will reach to the prisoned,
that the persecutor prisons in himself.
So be faithful in your sufferings in the power of the Lord,
who suffer now by a false priesthood for their tithes, oaths, temples,
which have got up since the apostles`' days.
For as the apostles and true christians suffered for denying the Jewish temple,
priesthood, tithes, and oaths, so ye do by the false,
and amongst the apostatized christians, who are got up since the apostles`' days.
So the power, and life, and wisdom of the Lord God Almighty keep you, and preserve you,
to finish your testimony to the end,
that ye may witness every one of you a crown of life eternal,
in which ye may sing praises to the Lord, and in that triumph!
And so, be faithful in that which overcomes, and gives victory.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 93.

[.blurb]
==== That Friends should have a sense of one another`'s sufferings.

Friends, in the power of the Lord God live, which goes over the heads of all the world,
that so in the power ye may witness forth the truth in their courts;
and then if ye suffer, ye by suffering will get dominion over their heads.
And lay down and offer up your lives for one another.
And here is the love of, and unto the brethren manifest,
to lay down their lives one for another.
But the love of Christ is further, he laid down his life for his enemies.
So dwell low in the life, that ye may answer that of God in every one.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 94.

Friends, I warn and exhort you all in the presence of the Lord God,
dwell in the measure which God hath given you of himself, in which is no strife,
but unity.
Therefore every one of you dwell in it.
And this I do warn you of, boast not yourselves above your measures,
but dwell in the truth itself;
that with the measure of the living spirit of the living God ye may be guided up to God,
in which spirit ye will all have unity, in the least measure of it.
And so every one of you judge self, for it would have the mastery;
which is to be condemned with the light, in which is unity.
So the eternal God of light, and life, and power be with you all, and in you all!
And keep from all strife, and above it in love and unity in every place.

And friends, the going from the life into the changeable,
is the cause of strife and confusion.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 95.

Grow in the increase of God, my dear children, and know all your assurance in the Lord,
and the seed in every one of you, which the promise of God is to.
And be obedient to the just, and in the truth of God walk, and the love of it.
And my dear hearts, in the seed dwell, which gives the victory over the world,
and that in the wisdom ye may be preserved, which bruises the contrary under foot;
whereby ye may reign in the life of God, to be as nursers and waterers of the plants,
and that all the contrary may be kept under;
that in the eternal power of God ye may be kept, which gives dominion over all,
and condemneth the contrary.
In which power the Lord God Almighty preserve you to his glory.
Amen.

[.offset]
Live in the life of God, and feel it.

And, friends, take heed of being hurried with many thoughts;
but live in that which goes over them all.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 96.

[.blurb]
==== A warning to Friends to keep to the light, out of deceit and strife, in unity.

[.salutation]
Friends,

I warn and exhort you all in the presence of the Lord God,
to meet together in the measure of life, that with it ye may be guided up to God,
and in unity kept together up to him, the Father of light and life;
and God Almighty be with you!
And that the dread and terror of the Lord may be among you, and deceit confounded;
and that with the measure of life all your minds may be guided up to God,
that so ye all may be kept in peace and love.
And let this be sent among Friends, to be read in all their meetings.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 97.

[.blurb]
==== To a Friend.

Stand in the will of God, with thy own will offered up, as his was who said,
"`Not my will, but thine be done.`"
And beware of striving in thy own will against the eternal providence and power,
which is now working invisibly, cross and contrary to all the powers of darkness.
And wait in the fear of the Lord, that thy duty to the Lord thou mayst know,
whose everlasting love is to thee; whose blessing reacheth unto thee,
if thou be faithful with faithful Abraham, who received the blessing,
and to his seed after him.
So beware, lest through thy forwardness and rashness thou bring the curse upon thee,
and so break thy peace in covenant with the Lord God.
The everlasting God give thee faith in Christ Jesus, in whom the promise is yea and amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 98.

Dear friends, stand in the faith, which gives the victory over all the world,
in which ye all will have victory, and so come to be of Abraham`'s faith,
and know the word, that quickens you, and reconciles to God,
and hammers down the contrary.
So, in the power and life of Christ Jesus live,
and in that ye all will be preserved to his glory.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 99.

[.blurb]
==== To all that make mention of the name of the Lord, and that profess his living truth.

[.salutation]
Friends,

A warning and charge to you all from the presence of the living God,
to let all lightness and airiness, foolishness, willfulness,
and frothiness be judged in patience; let it come to the fire and be burned, and hay,
wood, and stubble, and all that which is above the seed; he that builds there,
is above the foundation, his works are to be burned, he will suffer loss.
Therefore all keep down to the seed of God, and feel that atop of all,
which seed inherits the promise of God; that nothing may reign but the seed itself,
which inherits from God.
So all come into the authority of God, which is not usurped,
which gives the dominion over all the usurped authority;
that ye may live all in the one power of the son of God,
which brings all into the unity and subdues all things that cause the enmity.
So, the one power, the one soul, the one heart, the one mind is witnessed;
here the glory is revealed among you, and the one head, (Christ,) the seed,
and ye are all of one family.
Here is the power of the son of God known, all power being given to him;
which power and seed bruiseth the serpent`'s head, and breaks it,
in which standeth the enmity.
So all power is given to the son to rule, to subdue, and to judge.
So, live in the power, and ye live in the unity, ye live in the peace,
ye live all in the subjection one to another in the fear of the Lord;
ye live all in the seed, which is one, which keeps atop of the head of the serpent,
and keeps his head down, and bringeth it under.
So, feel the seed of God in every particular to be the head in the male and in the female,
and then ye come to be bone of his bone, and flesh of his flesh,
and to inherit every one the promise of God in the particular;
whereby ye may come to be inheritors in the Lord`'s strength,
feeling it and professing it in your own particulars.
So the seed of the serpent being kept down with the seed,
which is Christ in the particular, he brings to see over all that is contrary.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 100.

[.blurb]
==== Concerning all such as set up outward crosses.

[.salutation]
Friends,

In the power of the Lord God dwell and live, that over all the world ye may stand,
in that which fathoms it, that ye may handle the word of God aright,
which is as a hammer, and as a sword to divide the precious from the vile; and is a fire,
to burn up that which is hammered down, and divided from the precious.
And in the wisdom of God wait, that ye may answer that of God in every one;
which light will bring them off those things, which they have set up in that nature,
which is gone from the light.
Which things the light goes over,
and brings to see the beginning and ending of all those, whom Christ said should come,
which John saw, were come, who went out from them, whom all the world went after;
amongst whom have come up all these heads and horns, and Babylon, beast,
and false prophet, and mother of harlots, who have sat upon the waters,
which have been peoples, nations, and languages.
And these have been from the light, and so from the rock, and from the true foundation;
and the kings of the earth have drunk of the cup of her fornication.
And all nations, that have been from the life and the foundation of God,
have been in this fornication, from Christ the husband.
So now people are to be turned by the light to Christ their husband, the rock,
the corner stone,
and are to be brought from their outward crosses to the cross of Christ,
the power of God within them, and from the dead image to the image of God,
which they have lost through their going forth from the light,
and thereby have lost the power of God.
And all these crosses of wood and stone,
and the founder of them must all be thrown down by the power of God,
which is the cross of Christ; and to the light must they be turned,
which answers to that of God in every one,
before they come to feel Christ to rule and reign in them.
Then the outward, dead crosses of stone, wood, silver, or gold they,
shall not need (to have) to put them in remembrance of Christ,
or to bring him into their minds;
for such as are come to the light which Christ hath enlightened them withal,
and believe in it, they feel the power of God, they feel Christ and his cross,
which is the power of God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 101.

[.blurb]
==== An exhortation to patience in the time of suffering.

Dear friends and brethren in the everlasting seed of God, which hath the wisdom,
and life eternal, and dominion over all that is in the fall,
in which the blessing of the everlasting God is known, and his life that never fadeth;
in which seed (that hath the dominion over all that
is in the fall) is the wisdom that is pure and gentle,
which was before the wisdom below was.
And so, all Friends, be ready to offer up yourselves in the power of God,
joining to the suffering seed, in which ye offer up yourselves to God in the patience,
in your sufferings, feeling the seed which was before that was which makes to suffer.
For the lamb must have the victory, mark, the lamb,
and not the rough nature which hath gotten up since man fell from God`'s image;
the lamb must have the victory over that.
So, give up all in the lamb`'s nature, that in that ye may all meet in life, in power,
in victory, and dominion over all that which is in the fall,
knowing the birth that will persecute, and the birth that is persecuted;
and knowing the birth that is born of the flesh and the birth that is born of the spirit.
There are but these two births, and the elder must serve the younger;
and the elder is the first birth.
Therefore all feel Jacob, and the seed of God,
then ye come to feel that which shall remain forever and ever.
So in that all stand and dwell, that to the mighty God ye may be a blessing,
and a good savour in the hearts of all people,
being valiant for the truth upon the earth.
And take heed of grieving the spirit, but be faithful; and take heed of provoking,
and keep down all that with the spirit of God, that is contrary to God,
by which ye may answer that of God in every one.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 102.

Friends, encourage not your wives nor children,
in setting them up in the world`'s honour; for that which would do so in you, is carnal;
and the carnal mind is not subject to the law of God.
If ye do mind that which is of God in you, it will draw you up to God,
out of the world`'s honour, and friendship, and words, and ways, and fellowships,
and preferments, customs, and fashions, up to God`'s everlasting kingdom,
where is everlasting joy forevermore.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 103.

[.blurb]
==== To keep to the witness of God.

Friends, take heed of darkness, or going beyond your bounds or limits,
but keep in God`'s fear, that ye may receive his wisdom from above,
that with it ye may order all things to his glory,
answering the witness of God in every one, keeping in godly sincerity and simplicity,
meekness, patience, and humbleness, justice, truth, and mercy; this graceth a government,
and is a praise to them that do well, and is a terror to them that do evil.
For they that do evil, go from the witness of God in their own conscience,
and then the higher power comes over them.
Therefore keep to the witness of God in yourselves,
and that is the word of the Lord to you; and then ye will have the just weight,
and measure, and balance, and true understanding,
to answer the just principle of God in every one.

Bow and submit yourselves to the power of the mighty God of heaven and earth,
and to no deceit, and take heed of bringing any into it.
And take heed of respecting persons in judgment;
and that is the way to obtain favour from the Lord, and his blessing.
From him who loves your soul`'s eternal peace and good.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 104.

All Friends everywhere, in the power of God dwell and know that over all to keep you.
And lose not the power of God which keeps down, tames, and breaks all wild, unruly, rash,
and hasty spirits, which will run without the power;
which spirits reach not to the seed and the witness of God in men,
and strike not through the earthly,
neither receive wisdom to be ordered to the glory of the Lord God.
And there is safety in the power; and there is the wisdom of the Most High felt,
and the power of the endless life.
And this is the word of the Lord God to you all everywhere.
Dwell in the power of the Lord God, and live in it;
for that brings all your souls into peace, into oneness, into God, from whence they come,
who hath them all in his hand.
And in the power ye will all come to feel the end of words, the life,
from which all words of truth were given forth; and all hasty, rash, loose,
lustful spirits, the power will strike down, for they beget nothing to God,
but go out of his dread.
Therefore this is the word of the Lord God, and a charge unto all Friends upon the earth,
to dwell all in his power; then his dread, fear, terror, and majesty will be with you,
and amongst you all, to cleanse, wash, water, regenerate,
and sanctify every one`'s vessel, who will be thereby fitted for the Lord`'s use.
So that the power being lived in,
it keeps you over all the world in the dread and majesty of truth,
in cleanness and newness of life;
and to know the wrath of the lamb against all his enemies.
And the power of the Lord God will strike drown the lust that causeth pride, strife,
and contention; it will bring you to live in love and unity one with another,
and to know the kingdom of the Most High, that stands in power, ruling in you all.
And all your crowns it will lay down, that are mortal,
and will raise up the seed and bring life and immortality to light;
where the crown that is immortal is known,
and the glory that fadeth not away is possessed.
And all spirits that are unruly and out of the power, must be judged with it,
and kept subject; for that which lives in the power, is begotten by the seed Christ,
the new man, that is made after God in righteousness and holiness.
This birth is of the immortal seed by the word and will of God,
not begotten or brought forth by the will of man.
And none quench the spirit`'s movings in the least degree, nor none go beyond.
And feed not upon that, which dies of itself, but on that which cometh from above.
Know the son of man`'s flesh, which is your bread, and his blood, which is your drink;
which who eats and drinks of, hungers no more, nor thirsts no more,
but hath the endless life.
Nor any write, print, nor speak, (for God,) but as ye are moved of the Lord God;
for that reacheth to that of God in others, and is effectual.
Nor any stop writing or speaking, when ye are moved with the spirit of the Lord God,
for the power of the Lord God is to order, and to keep down that which would be hasty,
or that which would not be obedient, for that leads into the wilderness,
(each way,) which the power, and life, and seed of God must be set atop of,
which keeps you over the world, and brings you to the beginning.

And all Friends everywhere, in all your meetings know and feel the power,
and the seed (that is the heir of the promise) of the Lord God amongst you, over you,
and in you;
then in that ye will feel the presence of the Lord God dwelling in the midst of you.
And to the Lord your hearts will be brought, and it will bring you nigh one to another,
and to come into sweet love and unity, and into easiness and openness of heart;
and keep you over all that which would stain you, or hurt you, or defile you.
Whereby wisdom shall be given to you, with which ye shall be ordered to God`'s glory;
whereby ye shall feel his blessing, and order the creatures to his praise.
And the gospel ye shall be shod with.
And standing and dwelling in the power of God, there the shield of faith ye will receive,
that gives the victory over the world, with which ye have all access to God;
which mystery of faith is held in a pure conscience.
So, in the power of God ye all living, ye live in the Lamb`'s authority,
in the Lamb`'s dominion; and victory through him over all the world ye come to obtain,
to answer that of God in all consciences, in cleanness of heart and mind.

And all Friends, dwell in the life and power that stands in God,
that ye may have unity with God, and one with another, and feel his presence among you.
And the seed, and life, and power, and wisdom of Christ know in you all, and in another.
And the Lord God Almighty preserve you, and keep you in his power, life, and dominion,
which lets you see him who was in the beginning, before the world was made;
that nothing may rule but life itself;
that ye may feel God`'s presence in you and with you,
that truth and life may spread over all the world.
So the Lord God Almighty preserve you in the life, and power, and wisdom of God,
that ye may all be ordered to his glory.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

This is to be read in all your meetings.

====

[.centered]
=== Epistle 105.

[.blurb]
==== Concerning the Light. (To be read amongst Friends.)

All Friends everywhere,
keep your meetings waiting in the light which comes from the Lord Jesus Christ;
so will ye receive power from him,
and have the refreshing springs of life opened to your souls,
and be kept sensible of the tender mercies of the Lord.
And know one another in the life, (ye that be turned to the light,) and in the power,
which comes from the Lord Jesus Christ, who is your light, who is your life;
that ye may all in the life see Christ to reign in you, who is the truth,
from whence ye have light.
Here the old serpent is chained, and put into the bottomless pit,
and Christ is known to reign, and ye to reign with him; heirs with him, joint-heirs,
and heirs of God.
Here is the dominion received and witnessed of the world that is without end,
and the promise of life from the Father of life to you, who are turned to the son,
who to the Father is the way, who is the mediator between the Father and you.
All wait to receive the everlasting priest, the everlasting covenant of God, of light,
life, and peace; into which covenant no sin, no darkness, nor death comes,
but the blessing of the only wise God, the Father of life, here is known,
where no earthly man can approach.
But he that is of God knows God`'s truth; and he that is of the devil, doth his lusts,
who was a murderer from the beginning, in whom is no truth, who in it abode not.
So he it is that speaks a lie, and speaks of himself, and not God`'s word;
for he is out of the truth.
But ye that are turned to the light walk in the light, walk in the truth,
where no darkness is; with which light, that never changeth,
ye may come to see that which was in the beginning, before the world was,
where there is no shadow nor darkness.
In which light as ye wait, ye will come to receive into your hearts the word of faith,
which reconciles to God, and is as a hammer, to beat down all that is contrary;
and as a sword, to divide the precious from the vile; and as a fire,
to burn up that which is contrary to the precious: which word is pure,
and endureth forever; which was in the beginning,
and is now again witnessed and made manifest.
Therefore wait in the light, that ye may all receive it, the same word that ever was,
which the scriptures were given forth from.

So, friends, keep your meetings; and as ye are moved of the Lord, be obedient to him,
and keep your habitations.
And be not troubled; but look at that which giveth you to see over the world.
So the Lord God Almighty preserve you all to his glory!
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 106.

[.blurb]
==== To Friends, to keep in the life, out of janglings.

Friends, stand faithful to your measures of the gift of God,
which cometh from him who was before the world was made;
that ye may stand over the world, and all the betraying spirits in it,
that nothing may reign but life in you all.
And keep out of janglings and parties,
in that which is able to keep you above them all to God; and in that all wait.
And the bustlings of the world keep out of, in the covenant of peace with God.

[.signed-section-signature]
G+++.+++ F.
