== Epistles 161 &#8212; 184

[.centered]
=== Epistle 161.

O friends! do not die from the good through the wantonness of fleshly lusts,
neither be choked with the cares of this life, nor fear the shearers,
neither let the heat scorch your green blade; but dwell under the shadow of the Almighty,
who will shade you from the heat and cold.
Neither be cumbered nor surfeited with the riches of this world, nor bound,
nor straitened with them, nor married to them; but be free and loose from them,
and be married to the Lord.
The sufferings in all ages, of the righteous and just, were,
because they could not join to the nations`' vain worships, evil customs, rudiments,
traditions, and carnal inventions, but joined to the Lord, and not to them;
and therefore they suffered,
and kept single to the Lord God in following him and his truth, and living in it,
the amen, the crown, life, virtue, and righteousness, that floweth over all,
in which the righteous have peace.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 162.

[.salutation]
Friends,

Keep your meetings in the power of God, and in his wisdom,
(by which all things were made,) and in the love of God,
that by that ye may order all to his glory.
And when Friends have finished their business, sit down and continue awhile quietly,
and wait upon the Lord to feel him: and go not beyond the power, but keep in the power,
by which God Almighty may be felt among you.
For the power will bruise the head of the serpent, and all false and contrary heads;
this blessed seed, as he is the head of the church,
so he is also the head of every member of his body.
And so, by the power of the Lord ye come to love truth, and love Jesus Christ,
and love holiness; and by the power ye come to love God, and praise him, and bless him,
and magnify him, who lives forevermore.
For the power of the Lord will work through all, if that ye follow it.

When ye judge of matters, or when ye judge of words, or when ye judge of persons,
all these are distinct things.
A wise man will not give both his ears to one party, but reserve one for the other party,
and will hear both, and then judge.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 163.

[.salutation]
My dear friends,

Live in the life in which is the unity and peace one with another,
and lowliness and humbleness of heart and mind,
serving one another in the fear of the Lord God;
by and in which fear the wisdom of God is received from above,
and by which all things were made and created,
and by which ye may all be ordered to his glory.
And so, this is the word of the Lord God to you all: live in the power of the Lord God,
in which is peace, love, unity, and dominion in the life and power of God,
which was before enmity was; and in the light, which was before darkness was;
and in the life, which was before death was: and so,
in that feel unity and life in the power of God.
And so, the seed of God feel over all that set, which makes to suffer;
which was before it was, and will remain when that is all gone.
And so, feel the top-stone over all laid, that his life ye may feel over all,
and in that live.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 164.

[.blurb]
==== To Friends, to keep their meetings.

[.salutation]
My dear friends,

Keep your meetings in the power of the Lord God,
in which ye may all feel life eternal among you.
And do not forsake the assembling of yourselves together,
but provoke one another to love, in which is edification, life, peace, truth,
and dominion; in which ye may feel the blessing of God covering you,
ye dwelling in the same.
And so, meet together in the name of the Lord Jesus Christ,
whose gathering is above the gatherings of the sons and daughters of Adam in the fall,
and will stand when they are all gone; in which there is life, peace, and wisdom, order,
and edification, in the love and life of Christ,
over all the brittle and foolish priests and professors in the world;
and in which life and power there is the perfect fellowship, that will stand forever,
when all other fellowships are ended and gone.
And so, ye that know the life, and power, and light of Christ,
which was before death and darkness, and the power of the same was, be faithful,
who are gathered together in this life and power, and are met in it,
in it keep your meetings, in the life and power of the Lord, over all other meetings;
in which ye may all feel one another in the fellowship and unity that is everlasting,
and never hath end.
And so, in that the Lord God Almighty preserve you all to his glory;
that to the Lord God ye may be a blessing in your generation, and a good savour to God,
and in the hearts of all people.
That none may say, ye are an unstayed, unestablished, or a fickle people,
and have your religion, truth, and worship to seek; but that ye have it already,
and are established in the life and power of God, and in his worship, church,
and religion, which Christ is the head and the life of,
(which destroyeth the devil and his works,) who is the pasture of life,
who was before death was.
And so, feel him set over all that, which makes to suffer, who was before it was,
and will remain when it is gone: and so, feel the top-stone over all laid,
and Christ to reign.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 165.

All Friends, be faithful in the power of God and his seed, and mind the power of God,
which was before the power of darkness, and the fall of Adam were.
In which power of God is your fellowship,
and in which fellowship ye may see over the Jews`' fellowship and the Gentiles,
and ye may see the apostles`' fellowship, and the apostatized christians.
Now, the gospel is preached, and the true fellowship come into again,
which the apostles were in, which was before the apostatized christians`' fellowship was,
out of the life and power of God which the apostles were in,
and the church in the primitive times.
And the gospel fellowship, the power of God, is perfect, in which is our fellowship,
which was before any imperfection was.

And they have no more command to set up temples, tithes, oaths,
or swearing among the christians since the apostles`' days,
than the Gentiles had to set up Diana`'s temple; for the temple worship, tithes,
and oaths Christ came to end, and to bring people out of them,
and to make them his temples, and to bring to yea, yea, and nay,
nay in their communications.
And so, before the fall there were no oaths, in the fall there were;
but in the restoration there are to be no oaths, tithes, nor outward temples.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 166.

[.blurb]
==== To the church of God in Scotland.

[.salutation]
Dear friends,

In the power and light is my love to you all, in which the virtue, life, holiness,
and righteousness are known, and the riches, that never fade away.
Live in the truth, which ye first received, that it may be your crown and your clothing.
And dwell in love, and peace, and unity one with another in the truth of God,
which the devil is out of, and keep your meetings in the name of Christ Jesus,
that never fell; and then ye will see over all the gatherings in the fall,
in whom the peace, life, and the blessing are.
And all know one another in him, who is the substance,
and him to be your way and teacher, priest and prophet, that never fell;
and then ye will see over all the false ways, prophets, priests,
and teachers in the fall, ye being in him that never fell, your priest and prophet.
Be faithful to God every one in your measure of light, life, and truth;
which truth is over the whole world, and all that is in it.
And so, living in the light and truth,
ye may answer the light and truth in every man and woman;
and be a good savour to God in the hearts of all people.
And keeping your habitations in the truth, and in the light and life,
then ye will see over Adam and Eve, their sons and daughters`' habitations in the fall,
who cannot abide the truth, light, and life in the inward parts;
therefore they are not in peace one with another,
being not in the habitation that Adam was in before he fell,
nor in Christ that never fell, in whom the saints sit down, in the life, Christ,
who was with the Father before the world began.
Adam lost his habitation, and the Jews lost their habitations,
the one went into the earth, and the other into captivity, where the apostates are;
and so are become like untimely figs, or like unto the corn upon the house top.
Now this is the word of the Lord God unto you all, keep your habitations in the light,
life, and power, which ye first received and felt in yourselves;
that ye may be clothed with the blessing of the Lord, which was before the curse was.
And live in the unity in the light, which was before darkness was, or the power of it;
and in the life which was before death was;
and in the truth which was before the devil was; and in the power of God,
which was before the power of Satan was.
All live in this, that ye may be clothed with that which is immortal,
and attain to the crown of life, and to know the election before the world began.
He that is the first and the last, that is the beginning and the ending, sit down in him,
not in Adam in the fall, but sit down in Christ, that never fell;
and there that life ye will come to know,
which was with the Father before the world began.
And so, live in the substance, which is the seed, Christ, who ends the prophets,
first covenant, first priesthood, and all the types, and figures,
and shadows given after the fall.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 167.

[.salutation]
My dear friends,

Be not carried away by good words and fair speeches, nor the affectionate part,
which is taken with them; but every one have hold of the truth in yourselves,
and the life, and light, and power of the Most High,
by which ye may be stayed upon Christ, your bread of life;
he is the staff of your heavenly and eternal life; bread is the staff of life.
Now friends, who have denied the world`'s songs and singing; sing ye in the spirit,
and with grace, making melody in your hearts to the Lord.
And ye having denied the world`'s formal praying, pray ye always in the spirit,
and watch in it.
And ye that have denied the world`'s giving of thanks, and their saying of grace,
and living out of it; do ye in everything give thanks to the Lord through Jesus Christ.
And ye that have denied the world`'s praising God with their lips,
whilst their hearts are afar off; do ye always praise the Lord night and day,
and from the rising of the sun to the going down of the same, praise ye the Lord.
And ye that have denied the world`'s fastings,
and of their hanging down their heads like a bulrush for a day,
who smite with the fist of wickedness, keep ye the fast of the Lord,
that breaks the bond of iniquity, and lets the oppressed go free;
that your health may grow, and your light may shine as the morning.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 168.

Friends all everywhere, who have tasted of the love, mercy, and kindness of God,
and his power, ye are called to holiness and chastity.
Therefore keep out of inordinate affections, and inordinate fleshly love,
and feigned flattery and desires, which are below the truth;
which will bring you to infirmness.
And keep out of fond affections, and fond love, that draws out the fleshly part,
the fleshly eye, and brings into pride, and looseness, and false liberty,
and to abuse the power of God.
Oh! keep out of all uncleanness, whatever may be pretended, and fleshly desires;
for the "`lust of the eye, the lust of the flesh,
and the pride of life are not of the Father, but of the world.`"
And therefore keep down that which is not of the Father, but of the world.
And take heed of dishonouring your bodies, and defiling your minds,
but keep your bodies clean from all fornication, adultery, and uncleanness;
for that which pretends otherwise, and doth so, defiles it, and is out of the truth,
and is contrary to the law of God, and contrary to Christ`'s doctrine.
And therefore defile not yourselves, but live pure, chaste, and holy,
as becometh the saints;
for no adulterer nor fornicator hath any part in the kingdom of God.
Such go from that of God in themselves, and quench the spirit of God,
and abuse his power, and go into fleshly love, and feigned desires,
and flattering pretences, covering it with a false liberty,
and so are in the bondage to the beggarly, fleshly lusts; and whom they overcome,
they bring into the same bondage, and through their feigned flattery,
and dissembling carriage rob, and beguile, and spoil, to fulfill their insatiable,
ungodly desires, wills, and lusts.
Therefore live in the truth, for all such things are out of the truth,
and such as do the same, whatsoever they be;
therefore all that go into uncleanness under what fair pretence soever,
are to he judged.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 169.

To all the elect, chosen and faithful, who are of the royal seed of God, living stones,
elect and precious, knit and built up together, and united,
the family and household of God, and come to his mountain,
that is established upon the top of all mountains, that walk in the light of the Lord,
in unity and covenant with God, in the covenant of life and peace with him.
Who in this the Lamb`'s day are the gold tried in the fire.
Who have been tried by goods spoiling, by bonds, by whippings, by mockings,
and reproaches in the day of the Lamb`'s power, and some have been tried unto death;
and ye have proved to be the pure gold, that hath come out brighter and brighter.
Who have not feared the waves of the sea, nor the winds;
who fear not the storms nor the weather; whose anchor holds, which is the hope,
the mystery, which anchors the soul which is immortal, to the immortal God.
Among whom the star of Jacob is seen, and the morning star is risen,
and the sun of righteousness shines, and the Lamb`'s voice is known,
the church in her glory and beauty is appeared and appearing; the marriage of the lamb,
and the bride, and the wedding day is known, in which there is unity;
and the virgins sing praises, and follow the Lamb, because of his sweet ointment;
and the virgins are upon Mount Zion.
And the gospel is going forth unto all nations, kindreds, and tongues;
and life and immortality are coming to light through the gospel,
which is the power of God; and the mystery of the fellowship is known,
which is in the power.
And for want of the power, the gospel, in which is the fellowship,
hath Christendom been on heaps, and the heathen ignorant.
And now ye who know the power of God, ye know the gospel;
and ye who are in the power of God, ye are in the mystery of the fellowship.
So mark, the fellowship is a mystery, and the mystery of the fellowship is everlasting.
So, if any wants the power of God, he wants the mystery, in which is the fellowship,
although he may have all the scriptures.

And now, friends, if any be moved of the Lord God by his power, be obedient to it,
and wait in the life and in the power, and it will direct you to the glory of God,
in his wisdom, not to abuse it; that whatsoever ye do, ye may do it to his glory,
ye answering the just principle of God in every one.

If any be moved to go to the steeple-houses, or markets, or to reprove sin in the gate,
or to exhort high or low, or to reprove them; reason not with flesh and blood,
nor quench the spirit.
And when ye have done, in the same spirit live; and then ye will have peace, and rest,
and fellowship with God, and one with another.
For the unity is in the spirit, and it is the bond of peace.

And all Friends, in your meetings do not quench the spirit.
And take heed, and do not judge one another in the meetings;
but have patience until the meetings be done.
So, if any have any thing upon him to speak to another,
he may speak to him after the meeting is done; that will cover one another`'s weakness,
and not hurt others.

And all Friends everywhere, wait to feel the power of God in yourselves in your meetings.
And take heed of sleeping, and feel the power of God in one another;
that ye all may be in the mystery of the fellowship.
For woe unto them, that are at ease in Zion!
I warn and charge you all in the presence of the living God,
that none make their habitation in the earth, or build tabernacles there,
lest ye become vagabonds from the Lord.
But let every one rest in his habitation in God, and here is no vagabond;
but there shall every one know an heirship, a habitation, and an inheritance.
And I warn and charge you from the Lord, not to make any of the world`'s jewels your God;
but live all in the power of the Lord God,
in which ye will be carried over the spirit of the world.

And Friends all everywhere, dwell in the love and fear of the Lord God,
and in peace one with another,
and in the power and life of the Lord God keep your meetings;
and live in the mystery of the fellowship of the gospel, which is everlasting.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

This is to go to all the meetings of Friends among them to be read.

====

[.signed-section-context-close]
London, the 11th of the 3d month, 1658.

[.centered]
=== Epistle 170.

[.blurb]
==== To Friends at Worcester.

[.salutation]
Friends,

Every one of you having a light from the son of God, wait in it,
that ye may come to receive the son of God, from whence it comes;
and receive power from him to become the sons of God, and have faith in him.
For who are of faith are of Abraham`'s seed, which faith gives the victory over the world.
It is by faith our hearts are purified.
So, dwell in the light which casts out all jangling spirits;
in which ye may have unity one with another, and with Christ from whence the light comes,
and with the Father, whom he is the way to.
And that with the light ye may answer the light in every man,
(which comes from Christ,) though they hate it.
So, the Lord God Almighty keep and preserve you.

And all keep your meetings in the power of God,
that the Lord ye may see present among you.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 171.

[.blurb]
==== An Epistle General to them who are of the royal priesthood and chosen generation; given forth from the movings of the power and spirit of truth, and now made public. To be sent abroad among the saints scattered in Old and New England, Germany, Holland, Ireland, Scotland, Barbados, and Virginia, for them to read in the fear of the Lord.

[.salutation]
Friends,

Let all that ye do be done in the name of the Lord Jesus Christ,
by whom all things were made and created,
that ye may do that which ye do in the true dominion;
and then what ye do ye do in the power of God.
And all Friends, dwell in love, for that is the mark of a disciple,
and the fruits of faith and the spirit;
which love out of a pure heart is the end of the commandment and fulfils the law,
and in that is edification and building,
and the fruits of being passed from death to life; there is love to God, brethren,
and enemies, being in the seed that destroys death and the power of it, the devil.

We need no mass to teach us;
for the spirit that gave forth the scripture teacheth us how to pray, sing, praise,
rejoice, honour, and worship God, and in what;
and how to walk and to behave ourselves to God and man, and leadeth us into all truth,
in which is our unity; and it is our comforter, and guide, and leader,
and not men without who say,
they have not the spirit and power that the apostles had that gave forth the scriptures.

And we need not your Common Prayer to teach us,
for the spirit that gave forth scriptures teacheth us how to pray, sing, fast,
and to give thanks, and to praise and worship, and in what;
and how to honour and glorify God, and how to walk before him and men;
and how to use all creatures upon the earth;
and leadeth and guideth into all truth which was given forth from it,
which reproves the world of sin; that is our comforter, leader, and guider;
by which we know sonship, and in which we have unity, and this doth never change.
But that which man doth invent,
and their prayers and forms (who say that they have not
the same spirit which gave forth the scriptures) do change.
But the spirit that gave forth scriptures teacheth us how to pray, speak, sing, fast,
give thanks, and how to read them with understanding, and how to walk before God and man,
and how to worship God, and in what; for it leadeth us into all truth,
which is our comforter, in which we have unity and fellowship,
and to know the true religion which doth never change.

And so, the spirit of truth which gave forth the scriptures, is our director, guide,
leader, and comforter, which reproveth the world for sin.
And this leadeth to see the end of all directories which men invent,
who have not the spirit the apostles had;
and when they cannot hold it up they cry to the powers of the earth to help them.
And these we see are erred from the spirit and without the spirit;
with whom we cannot trust our bodies, spirits nor souls, into their hands,
but have committed them to the Lord, whose they are.

And we are a people that are redeemed from the earth and world,
and need none of your church-made-faith,
which ye have framed and made in eleven days`' time, and your other three days set apart.
For Christ is the author of our faith, which is the gift of God,
which is a mystery held in a pure conscience.
And we say, that all the priests in Scotland, London,
and New England cannot make the gift of God, the mystery,
which is the faith which remains, and by which men are justified and saved,
neither have they power over it; which brings us to have access to God,
and giveth us victory over that which separated us from God.
And so, we need none of their faith to lead us;
for the faith Christ is the author of we live in, which they cannot make nor frame.
And though they may cry to the magistrates to help them to uphold their made-faith
(which idol they cannot hold up themselves) which they have invented,
and say,
"`they are not in the life and power as they were
in that gave forth the scriptures;`" and say,
"`revelation is ceased from people,
and there is no victory while they are upon the earth.`"
These are the fruits of their framed-faith, which we need not.
For the spirit that gave forth the scriptures teacheth
us to know who is the author of our faith,
and the fruits of it; which giveth victory.
And the spirit teacheth us how to pray, sing, give thanks, praise, rejoice, fast,
worship God, and in what; and how to walk to God and man, and leadeth us into all truth,
the reprover, of the world for sin, which is our comforter, guide, and leader,
and director; in which we have unity and fellowship that is without end,
and a pure religion that doth never change.
And a great deal of stuff there is in their books, which is not worth mentioning,
it will rot and that nature that gave it forth; but the seed, and life,
and power will stand.

Church-faith changeth, Directory changeth, Common Prayer changeth, and Mass changeth.
And here are the four religions which are got up since the apostles`' days;
which they have fought for and killed one another about.
But the pure religion doth not change which we are of and own;
in which are the spiritual weapons which were amongst the apostles.
The true faith changeth not, for it abideth and remaineth, which is the gift of God,
and a mystery held in a pure conscience; of which we are, and which is our faith.

Mass for the Papists, common prayer for the Episcopal men;
and the directory for the Presbyterians;
church-made and framed faith for the Independents, and mixed Baptists and others.
And those have had their fellowships in these for which they fought,
and about which carnal weapons got up since the days of the apostles.
But the fellowship in the spirit remains, and doth not change,
which hath spiritual weapons,
and these are known and used to fight withal about religion,
in which the seed of God is known,
which bruiseth the serpent`'s head which led man from God,
and made a separation betwixt man and God.
And the election is known (in him who was) before the world begun;
who is the head of our church, and not they that be head of the mass,
head of your directory, head of the common-prayer, and head of the church-made faith,
which we see all change and come to nought, and God confounds.
And men stand in doubts and questions, and have no assurance in their religion;
but that of God stands in them all bound.

They that followed the pope, were called Papists;
and they that protested against the pope, were called Protestants.

And thus they gave names one to another.
And so common-prayer men, and directory men, and Independents, and Baptists.
And thus in the envy, out of the love, out of the spirit,
which gave forth the scriptures, gave they names one to another; all of which we judge.

Our faith, our church, our unity is in the spirit, and our word at which we tremble,
was in the beginning, before the Papists`' mass, and your Episcopals`' common-prayer,
and the Presbyterians`' directory, and Independents, Baptists,
and other church-made framed faiths were; and our unity, church,
and fellowship will stand when they are all ended.
By which spirit we judge them all, and deny their works; in which is our unity with God,
with the scriptures, and one with another.
For they have been to people like so many changeable coverings,
but now the spirit is taking them off; by which we are covered,
and it is our weapon in this day of great battle with them.
The scriptures which ye do speak, and show forth in your books, are owned,
but your imaginations of them we deny; but they are all owned in themselves and places.
So they are all ours, which end in Christ, who is ours, and in him we are that remaineth.

[.offset]
The mass is the Papists`' sacrifice, that they kill about.

The common-prayer is the Episcopals`' sacrifice, that they persecute and kill about.
And --

The directory is the Presbyterians`' sacrifice, they persecute and kill about.

The made and framed church-faith is the Independents`' and Baptists sacrifice,
which they kill and persecute about.

Which sacrifices the Lord doth not accept, neither hath he respect to,
which are of them who have erred from the spirit which the apostles were in,
with which they offered spiritual sacrifice to God the Father of spirits,
which we are in.

And all my dear hearts, all know the fellowship of the seed in its sufferings,
and to be made conformable to his death;
that ye in the suffering through it may know the
power of the resurrection of the just seed.
And this is it which kills all bad spirits that will talk, but not do;
such may crucify Christ in themselves afresh.
Therefore mind the daily suffering which the seed had, and have unity with that;
so ye may rise with that, which destroyeth that which causeth it to suffer.

[.offset]
The Papist cries, higher powers, help, help, or else my mass will go down,
and all my ceremonies.

[.offset]
The Episcopal man cries, help, help, higher powers, or else my common-prayer goes down.

[.offset]
The Presbyterian cries, help, help, higher powers, or else my directory will go down.

[.offset]
The Independent, and Anabaptist, and others cry, help, help, higher powers,
or else our framed faith, (which is our eleven days`' work,) will down,
and we shall not stand.

Are not ye all ashamed?
And show ye are naked, out of the power and life the apostles were in;
and from their weapons naked?
The outward power neither upheld nor separated them from the love of God,
which they had in Christ, the end of the law.
I am not one of them, that call themselves Papists, Common-prayer-men, nor Presbyterians,
Independents, nor Antibaptists, Puritans, nor heathens, which are out of the life of God;
but that which God hath called me to, that I am,
and in the elect before the world began.

This is to go everywhere abroad amongst Friends, who are of the royal priesthood,
which destroys that which made a separation from God.
From the royal seed goes the royal commandment, which seed remains forever,
from the royal seed to the royal seed, which are the royal priesthood,
which have the royal law, and love to friends and enemies;
which is beyond the love of the world, and before it was.
That is the royal love, where no enmity can come.

Forgive us, as we forgive them, cry Papists, cry Episcopal, cry Presbyterians,
and Baptists, and Independents; these cry and say the Lord`'s Prayer,
"`Forgive us our debts and trespasses,
as we forgive them that trespass against us;`" and like a company of senseless men,
without understanding, fall a fighting one with another about their trespasses and debts,
and never mind what they prayed, as though they never looked for forgiveness,
and to receive the things they prayed for; That pray, "`Forgive us Lord,
as we forgive them,`" and fall a persecuting and imprisoning one another,
and taking their brethren and fellow servants by the throat about religion,
which in their prayers they said.
"`Forgive us, as we forgive them,`" and will not forgive, but say their prayers,
as the Pharisees did the scriptures, and did not: this is he,
that must be cast into prison, until he pay the utmost farthing, and must not come out.
And this hath been their work since the apostles`' days, and is not here law?
The apostles and Christ did not bid, that any should kill about their words,
but that they should love enemies;
but ye will kill about their words who were killed for speaking them forth.
And so all Friends, dwell in the seed of God,
which is heir of the power of the world which is without end;
in that dwell and keep your meetings, that ye may all be possessors.

All religions will fight about religions and worships,
and kill like the heathen about their gods; Jews, Gentiles, Papists,
Protestants of all sects, which are out of the power of the Lord,
and the spirit that the apostles were in.
And so, they are all out of the royal spirit, that hath the royal, spiritual weapons,
and out of the royal seed, which saith,
"`love enemies,`" which is the royal command to the royal priesthood.
And they confess, they have not the same power and spirit of the apostles;
so then it is true for them to say, we are not the spiritual men,
we have not spiritual weapons to fight withal; if ye do not help us, higher powers,
we fall.
For we hold our traditions, and that which we have is by tradition,
is by the earthly powers.
For we are not made ministers, as the apostles were, by the immediate spirit and power,
and gifts; therefore the higher powers must help us,
and to them go we with our packet of letters, as Saul did;
for we are not spiritual weaponed men, as Paul was.
For in all these things are the priests guilty.

The Papists, Common-prayer-men, Presbyterians, Independents, Baptists,
persecute one another about their inventions, (which they have invented,) their mass,
their common-prayer, their directory, church-faith,
(which they have made and framed,) their inventions and handiworks,
and not for the truth.
For they know not what spirit they are of, that persecute,
and would have men`'s lives destroyed about their church, worship, and religion;
for Christ said, "`he came not to destroy men`'s lives, but to save them.`"
Now they that know not what spirit they are of,
that will persecute and destroy men`'s lives, and not save them,
we cannot trust our bodies, souls, nor spirits into their hands,
that know not what spirit they are of themselves;
they are not like to be trusted with others, that would destroy by a law,
which the disciples would have done by prayer,
to command fire to come down from heaven to destroy them that would not receive Christ.
Which sort Christ rebuked, and told them, that they did not know what spirit they were of.
And now, if they did not know what spirit they were of;
do these which have persecuted about church and religion, since the apostles`' days,
who would compel men`'s bodies, goods, lives, souls,
and estates into their hands by a law, or else make them suffer?
These are not the ministers of Christ, (the saviour,) that destroy men`'s lives,
and they know not what spirit they are of; and the lives, bodies,
and souls are not to be trusted in their hand.
And ye that persecute, shall have no resurrection to life, except ye repent.
But they that know what spirit they are of themselves, they are in the unrebukable zeal,
and by the spirit of God they offer up their spirits, their souls,
and bodies to the Lord, which are his; whose they are, to keep them.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 172.

We are of the royal seed, elect and precious, before the world began,
that which (ever) the Sodomites crucified, grieved, and vexed by their unrighteous,
ungodly conversation, who lived in fulness, and pleasures, and abundance of idleness.
And we are of that seed, that cannot serve the wills and lusts of men,
and bow and stoop to them; who are a people redeemed out of kindreds, kingdoms, peoples,
and nations, who are of the household of God, built up together a spiritual house,
whose builder and maker is God, and do reign upon the earth,
as kings and priests unto God; whom we serve day and night.
And are of the seed that hath been slain from the foundation of the world,
which the princes of the world, and counsels,
and the great and wise of the earth crucified;
who lived in the form of godliness of the saints`' words,
but quenched the spirit in themselves, and being that birth born of the flesh,
persecuted that which is born of the spirit.

We are of the seed, the anointed,
which the powers of the earth combine and take counsel together against,
whom God (we see) sitting in heaven, laughs them to scorn.
We are the royal priesthood, who offer daily to the Lord the spiritual sacrifice;
the holy generation, and the peculiar people, zealous of good works,
clothed with the zeal of Christ against the bad works, and the workers thereof.
Therefore of all nations, peoples, sects, ways, professions,
and talkers of religion are we hated, by them that are out of the way and power of God,
though they profess scriptures, church, worship, and ministry;
yet such have crucified Christ, and the Lord of glory.
We are they that witness the promise of God fulfilled, and that do witness,
that the age is come wherein God would show forth his exceeding riches and kindness,
which was wrought amongst the apostles.
We are the anointed of God, and his prophets, that he saith,
"`touch not;`" who are as the apple of his eye; who for our sakes hath reproved powers,
and thrones, and dominions, and rebuked them.
We are the preachers of righteousness in the great city Sodom,
wherein Christ was crucified, where the life of the prophets, and the apostles,
and holy men of God lies slain, and cursers, swearers, drunkards, eaters, and drinkers,
that rise up to play, in all fulness, wantonness, and profaneness, profess their words,
and make merry over their lives.
And the witnesses since the apostles`' days have been slain; the woman in the wilderness,
the lamb and his wife shall be known, which is come up out of the wilderness.
So in this great city Sodom and Gomorrah, the false church and the whore are,
where all the abominations are,
that made all the nations drunk of the wine of the wrath of her fornication;
whereby the world is all on heaps about religion, and church worship,
and the several ways in Sodom`'s nature, professing the saints`' words, imitating forms,
killing and slaying one another about professing the saints`' words,
but out of their life.
Which shows, that they are not of the royal seed, which saith, love enemies;
that is the royal seed, and they that follow him, are of the royal priesthood,
and holy people and generation, amongst whom is the royal law of love;
whereby we cannot respect men`'s persons, for he who doth, is convinced of the royal law,
to be a transgressor.
So every one of us, that is come to the seed of God, that bruiseth the serpent`'s head,
that led man from God, who is the prince of the world, the prince of darkness,
and the prince of the air, the father of lies, a murderer from the beginning,
the corrupter of mankind, the author of the separation from God, and the original of sin,
the beginning of it, which led man from his dominion over the handiworks of God;
which the royal seed Christ, destroys, and renews man again in the image of God,
and brings him again to his dominion over the handiworks of God.
And this hundreds of thousands are now witnessing; by which they come to be kings,
and redeemed from the earth, and come to be made kings upon the earth,
in the image of God, over the handiworks of God,
in the wisdom by which they were created.
So all powers whatever, that are a terror to evil doers, that bear not the sword in vain,
to us are a praise, that do well.
And all kings upon the earth, that were anointed by God, a figure of our Christ,
the king anointed, he ends them all, and makes kings to reign upon the earth.
Amongst these Christ is king, which thousands witness; amongst these he is king,
and all other kings made by man, and putting on man earthly crowns,
earthly man will put them off again, and unking them, if they cross them.
This is the state amongst them in whom Christ reigns not, nor the true magistrate obeyed,
which is to the evil doers a terror.
But since the apostles`' days all hath been in confusion about religion, church,
and worship, amongst them that have killed the witnesses,
and since the true church went into the wilderness, and the witnesses have been slain,
and the man child caught up to God.
So they that have slain the witnesses, and killed the saints,
have been in all this confusion; and the witnesses are rising,
and the everlasting gospel shall be preached again (amongst them that have had the words,
but have slain the life of the prophets and the apostles) unto all nations, kindred`'s,
and tongues of them that dwell upon the earth.
So the great professors of the world, (which were the Jews,) could not abide Jesus,
the king, that he should reign; and where he is now in the male and in the female,
he is king, and that makes kings, among whom he is king.
All in the name of the mighty King of kings is to be done, and then it is the power.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 173.

All Friends, take heed of running on in a form, lest ye do lose the power;
but keep in the power and seed of God, in which ye will live in the substance.
And at any disputes take heed; many may be lifted up in the victory and conquest,
and after have a joy in the prophecies and openings, and after fall.
And if babblers come, and janglers say, they have a bad meeting;
and so the murmuring nature getteth up, out of patience, and the seed,
which beareth all things, and suffereth all things,
which keepeth down that which causeth lifting up, murmuring and disputing,
which the seed endeth, and prophecy, and keepeth down all the other that is contrary,
and would live in the contrary;
that which keeps down that which doth change is the peace, corner stone,
and the stayedness in the seed and life.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 174.

Dear Friends all everywhere, feel the seed of God over all that which is in the fall,
that is gotten up since Adam and Eve fell from righteousness and the image of God;
and in which fall the Lamb hath been slain.
And so feel the seed of God over all that which makes to suffer;
and will stand and remain when he that makes to suffer is gone.
And so feel Christ to reign and rule over all that which is in the fall,
and there ye may all feel the life to flow over all,
which life was with the Father before the world began;
and which life will remain when death and the power of it are gone.
And in that life all live and dwell, and in it keep your meetings.

And feel the word of patience and the word of wisdom,
in which ye may find both patience and wisdom in this day of life.
And feel my love to all Friends in the everlasting seed of God.
G+++.+++ F.

[.centered]
=== Epistle 175.

[.blurb]
==== To Friends, to serve one another in love, in outward things.

[.salutation]
My dear friends,

In the order and wisdom of life order all things to God`'s glory,
and dwell in the love of God together, all serving one another in love,
and in the life of the truth; and ye that "`give to the poor,
lend to the Lord,`" and he will give you again with advantage.
And so be fruitful in every good work,
and be subject to one another in the fear of the Lord,
and do that which ye do in love and peace;
and in that keep in the authority and power of God, in kindness.
And keep down and be master over all passion, and the hasty and cross spirits,
and silence that which is sudden; and let love have the preeminence in all and over all.
And provoke one another to love and to good works, and be diligent in all your places;
that ye may be a good savour in the hearts of all, and that the truth may flow over all.
And let nothing be wanting amongst you, and then all is and will be well.
And encourage one another to seek out the poor, and sick, and fatherless, and widow,
and imprisoned, and make up their necessities and wants;
then there will be nothing lacking.
And keep in discerning, that ye may not be ensnared, nor made a prey upon;
but that in the power and wisdom of God ye may be kept over all such,
and to feel through all states and conditions.
That the Lord God may be honoured in and by you all,
and ye all may be preserved in his power and life to his glory.
For your bestowing of outward things to such as stand in need, is the least love,
and things of little value in comparison to the things that are above and immortal.
And so keep over all in that in which ye have the
blessing poured upon you from the Lord God,
to clothe and cover you.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

This is for the men`'s meeting.

====

[.centered]
=== Epistle 176.

[.blurb]
==== To Friends in the ministry.

Friends, that minister up and down among Friends, be examples in wisdom, life, patience,
righteousness, holiness, and in godliness and soberness,
that your lives and conversations may preach.
And keep out and over all vain, youthful ways and childishness,
and over all those fallen spirits, that quarrel, jangle,
and contend about outward things, and have a life in them;
through which they are eaten out from the life and truth of God.
And such become as the dross, and they come to be as the untimely figs,
and as the corn and grass on the house-top.
And so ye all that minister abroad to others,
first see that ye be in the truth that will never change,
and in the word and life that will abide; and in the gospel, the power of God,
which was before meats and drinks, and outward apparel were;
that ye may abide in that which never changes, that ye may not be confounded.
For when they that are ministers change and alter
from that which they went forth first in,
and brought the people into, it doth show that they are either gone out of the truth,
or else they were never in the truth; and this confounds people.
They had better never have gone out at all.
Therefore ye that minister abroad, see that ye be in that which will never change,
and is over all them that do jangle about changeable things;
for that being ministered to people that never changes,
and they that minister being in that which never changes,
this begets people into an established state.
For they are all fallen spirits, and not ministers of the word, nor the gospel,
nor of Christ that never fell,
(which destroys the devil and his works in the fall,) that are quarrelling, and siding,
and disputing, and contending, and striving about outward things.
For that mind that goes into them is in the heats and tempests, up and down,
and is in the wrong judgment, and cries against others as being lords,
and being esteemed and looked upon, and looking at men;
when the wrong lords in themselves, and that is it which should not be esteemed.
The outward part being gotten up in themselves, who have gotten a life in outward things,
in the outward knowledge, and the outward reason, and outward wisdom,
that outward part and reason, wisdom and knowledge, must all perish,
and the life they have in them also, before the life of God can come to rule in them,
in which is the everlasting unity and fellowship.
And so, friends, all that minister abroad in the everlasting word, which never changes,
and the gospel, in it abide, the first and last.
For the word keeps down the pride of life, the lust of the flesh,
and the lust of the eye; which is of the world, and not of the Father.
And so let your liberty be in the word, and spirit, and the power of God,
which keeps you out of the liberty of the world, and its vain fashions;
and be not fashioned after them.
And so take heed of light words, unseasoned talk, and of taking liberty to the flesh;
but walk in that which is pure, and keep in that in which ye may have the wisdom,
(which is the beauty of gray hairs,) that to the Lord God ye may be a good savour,
and in the hearts of all; walking in all comeliness and decency.
The word of truth makes you to be seasoned and savoury; and this is comely,
keeping in the beauty of holiness, in which holiness the Lord is seen,
over the beauty of the world, that is vain.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 177.

All Friends everywhere, who are dead to all carnal weapons,
and have beaten them to pieces, stand in that which takes away the occasion of wars,
in the power which saves men`'s lives, and destroys none, nor would have others.
And as for the rulers, that are to keep peace, for peace`'s sake,
and the advantage of truth, give them their tribute.
But to bear and carry carnal weapons to fight with, the men of peace,
(which live in that which takes away the occasion of wars,)
they cannot act in such things under the several powers;
but have paid their tribute.
Which they may do still for peace sake, and not hold back the earth, but go over it;
and in so doing, Friends may better claim their liberty.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 178.

[.blurb]
==== For Friends in Barbados, Virginia, New England, and all the islands about.

Friends and brethren,
who are made partakers of the power of the world that is without end,
and are partakers of the heavenly gift, and feel the power, in which are the unity,
peace, and kingdom that hath no end, in that feel one another, and know one another,
and in the life, in which ye will have peace and unity one with another;
that the top-stone may be laid over all, and ye all in the wisdom, life,
and seed in your measures may be preserved, spreading the truth abroad,
confounding the deceit, answering the witness of God in all.
To which they must be brought before their minds can be turned to God,
and be acquainted with his covenant of promise, and his life, and to know God,
the Father of spirits.
For all Christendom, which hath gotten the words of the prophets, Christ,
and the apostles,
that are not in the spirit and power that they were in that gave them forth,
are all on heaps about them, and not in unity, being out of the spirit,
in which is the unity and true fellowship.
For there are the heaps, amongst them that are out of the spirit and power of God,
having the words in the transgression, in the fall, in the earth, and in the many bodies,
names, and heads, churches, religions, and worships, which are in the first birth,
born of the flesh, which will persecute him that is born of the spirit;
which spirit plungeth down by baptism, and putteth under, and bringeth into the one body,
and putteth that under which causeth many heads,
and answereth to that which is transgressed against.
For all must come to the one baptism with the spirit into the one body.
And all my dear friends, be faithful, and quench not the spirit,
but be obedient to the truth, and spread it abroad, which must go over all the world,
to professors, Jews, christians, and heathen,
to the answering the witness of God in them all; that they may come to the truth,
which answers the witness in them, to be made free by it.
And, friends, in the wisdom of God dwell,
which preserveth in unity in the spirit and power.
If any thing be spoken in a meeting which ye cannot bear,
speak to them concerned betwixt them and you, after the meeting is ended;
for if any of the world be there it may give occasion to them to reproach truth.
For wisdom preserveth in the peace, and maketh peace, and preserveth out of the contrary,
and overcomes with the wisdom and love, and answereth the witness with the life,
and so hath unity, and that hath the kingdom.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

All Friends, ye must come into a temperance above all the world.

[.offset]
And all Friends, ye must come into a patience above all the world.

[.offset]
And all Friends, ye must come into a moderation above all the world.

[.offset]
And all Friends, ye must come into a wisdom above all the world.

[.offset]
And all Friends, ye must come into a knowledge above all the world.

[.offset]
And all Friends, ye must come into an understanding above all the world.

[.offset]
And all Friends, ye must come into a sobriety, and gravity,
and a seasoned state above all the world.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 179.footnote:[The 1831 American edition of Fox`'s [.book-title]#Complete Works# (from which this edition was created) omits the number _179_ when numbering Fox`'s epistles. As it is believed this omission was merely an accident, the editors of this edition have chosen to correct the numbering from this point forward. Therefore, epistles 179--320 in this work correspond to epistles 180--321 of the 1831 edition. Similarly, the 1831 edition skips the numbers _322--332,_ which has also been corrected, resulting in a difference of 11 for the numbering of epistles starting with 321 in this edition.]

[.salutation]
My dear friends,

In the love, and life, and power of the Lord God dwell, in the power, life,
and seed which hath no end; in which ye all may have unity.
And be faithful and diligent in the things that are good, and keep your meetings,
and meet together in the power of the Lord which cannot be broken;
in which is an everlasting unity.
And live in peace and unity one with another, and all keep in the power of the Lord God,
and take heed of getting into a form without the power;
(any of you,) for that will bring deadness, and coldness, and weariness, and faintings;
and what will it not bring in that nature?
Therefore keep in the power of the Lord, which will keep all the contrary down and out,
and preserve you in peace and life, love and unity, fresh and fruitful,
and diligent in the wisdom of the Lord God,
with which and in which ye may be kept and preserved to his glory,
and be a good savour to him, and in the hearts of all people.
That to the Lord ye may be a blessing in your generation,
and a peculiar people in tenderness,
and full of that faith which overcomes the world and all things in it;
through which ye may come all up into the unity of
the spirit which is the bond of peace.

And all Friends, live in the power of the Lord God and keep down the wise part,
which will judge truth to be simple and come to despise it,
and cry up their own words of wisdom in its place.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 180.

[.salutation]
Friends,

Live in the unchangeable power of God, which will keep you in righteousness, and truth,
and love, and unity, and dominion over all the unclean spirits, and rough ways,
and mountains within and without:
that the power of the Lord God may be supreme amongst you,
and that ye may in the wisdom of the Lord be preserved.
And none abuse it, but all patiently in the power of the Lord wait,
that in it ye may be all kept low, in love and unity with God and one with another;
that in the seed ye may be kept, which is heir of the power.
And all be diligent in your places, serving the Lord,
and that your spirits may not be plucked down with earthly things nor limited by them;
but that in the power of the Lord God ye may act over them,
(the handiworks of God,) out of the entanglements and thraldom of them,
and out of the vain inventions of men, but keep in the power of the Lord God over them;
in which power is the mystery of the fellowship and the dominion,
and let every one`'s eye behold it and mind it.
For that is it which will keep you out of the changeable things, and present your minds,
souls, and spirits to the Lord; and there the seed comes up which is heir of the power,
and of the wisdom which is pure from above,
where the city is known that lets no uncleanness in,
and the salt is known that savours all things.
Therefore feel it in the heart, which is more than in the head or tongue;
which many may strive for, but do not obtain the power nor the kingdom.
Therefore all be wise in the wisdom of God, and let every one`'s eye be unto that wisdom,
which the departing from sin and evil is the beginning of;
that with it ye may be ordered, and do whatsoever ye have to do with it and by it.
In that ye will feel his presence and blessing,
that ye may know the seed immortal to have the dominion in you;
that there ye may come to know Christ to reign.
And your growth in the seed is in the silence,
where ye may all find a feeding of the bread of life.
And all Friends, keep in the wisdom of the Lord that is pure and holy from above,
by which wisdom ye may be preserved and kept holy and pure, above that which is below,
and out of that which is below, the wise part wherein is the strife;
that being kept down by the power of the Lord,
the seed comes up which is heir of the power.
And there innocency, and simplicity,
and nakedness of heart and spirit are lived in and life is fed upon.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

And so, if any Friends have friends or relations beyond sea, send them books or papers,
and be diligent to spread the truth; and send Latin books, or French books,
or other books, to Leghorn, France, Poland, Italy, Norway, Low Countries, etc.

====

[.centered]
=== Epistle 181.

[.blurb]
==== To Friends beyond the sea.

[.salutation]
My dear hearts,

Do your business faithfully, and fear not the amazement of men,
ye sons and daughters of Abraham.
Trample upon all deceit, and keep over all that in the dominion of God`'s power,
above the world, answering that of God in all; and spare not any deceit.
Be ye faithful,
and ye will find and feel the word which is sharper
than any two-edged sword to cut down deceit;
and ye will feel the blessing of the Lord God with you.
And if the world`'s works lie like a wilderness, care not for it and matter it not,
but do the work of the Lord faithfully; and ye will feel it prosper,
answering that of God in every one.
And so God Almighty preserve you in his power.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 182.

[.salutation]
Friends,

Dwell in patience, and in the power, life, and wisdom of God, and in peace, and love,
and unity one with another.
And be subject in the power, and life, and wisdom of God to God and to one another;
that in it ye may be as a pleasant field to the Lord God, and as the lilies,
and the flowers, and the buds,
feeling the pleasant showers and the streams of life from
the living God flowing upon you and coming into you,
whereby the presence and blessing of the Lord God Almighty amongst you all may be felt.
And in that the Lord God Almighty preserve and keep you,
that to him ye may be a good savour.
And live in peace.
And the God of all peace keep you,
that nothing may reign and rule amongst you but the life, and power, and seed,
and wisdom of God;
that in him ye may be preserved by which all things were made and created.
That ye may be all ordered to his glory,
and be a good savour in the hearts of all people;
in which ye do refresh others and are refreshed.
So, dwell in the fear of the Lord,
which brings a dread and terror upon all his enemies that are in Esau`'s mount;
but your peace comes from the mountain of God.
And let your joy and peace be in the Lord.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 183.

O my dear friends and brethren everywhere! the power of the Lord God, that is over all,
live in, that in that ye may feel unity and fellowship;
that in the power of the Lord God ye may all come
to be heirs of the power of an endless life,
through which ye may inherit eternity, and so to feel life eternal abiding in you.
Now, the man-slayer hath not eternal life abiding in him,
that is he that envies his brother; so all the persecutors, that envy their brethren,
have not eternal life abiding in them:
under this all the persecutors about their church and vain religion, false worship,
faith, and ministry, are.
Therefore all of you, feel this eternal life abiding in you;
for he that hath the son of God, hath life eternal; and so,
in this eternal life ye have fellowship with God and his son, and with one another;
and in this, the law of life, that is in Jesus Christ,
passeth sentence on the law of sin and death in every man and woman,
and brings it to the execution.
Through which law of life righteousness flows and runs down, and also justice and truth;
and by this law of the spirit of life in Christ Jesus, (mark,
in Christ Jesus,) ye come to know the Lamb`'s throne,
and the throne of iniquity thrown down, and all blasphemous mouths stopped,
and the chambers of imagery thrown down, and the household of God raised up,
and the fruitless trees thrown down, and the plant of God raised up,
which is of his own planting, the tree of righteousness, whose fruit is unto holiness,
whose end is everlasting life.
So mark, here is the fruit of this tree, and the end of this tree,
and by this spirit ye do distinguish names and plantings, and pluckings up;
and God`'s building ye will distinguish from man`'s building; and man`'s plucking down,
and man`'s gathering together-- ye that are gathered together in the name of Jesus,
can distinguish men`'s gathering, and their scattering.
Oh! therefore be valiant for the truth, which ye are come to the knowledge of,
and worship God in that truth, which the devil is out of, and abode not in;
this makes you free from the devil and his works, that are out of the truth.
Here in this worship, (in the truth and in the spirit,) the living God, who is a spirit,
the God of all truth, he hath his glory and his honour from his spirit in every heart.
And so, keep in the spirit and truth, and the power of the everlasting God,
who is from everlasting to everlasting,
that ye may know him Lord of the earth and of the heaven, and of the heaven of heavens,
ruling and reigning, whose eye is over all his works;
that ye may glorify him in his power and spirit, and serve him in the new life,
which will keep you over all men`'s fables and devices, whimsies and imaginations,
out of all janglings and vain disputes of men of corrupt minds.
And so, all to live in that which is the same today, as was yesterday, Christ Jesus,
the power of God, and the seed of life, and word that was in the beginning; so,
no new thing, but that which was and is to all eternity: let your fellowship be in that,
and your unity and communion be in that;
for by the spiritual eye the eternal unity with the eternal God is seen.
So, hear his voice everywhere, that speaks from heaven, whose voice shakes the earth,
and not the earth only, but heaven also.
The heaven signifies joy; so, all the false joys, the lifted up joys, or exalted joy,
and joy in vain glory, and joy in the world, or any outward thing or creature,
or men or women, his voice, that speaks from heaven, shakes the earth and the heavens,
and these must be shaken and removed, both the heaven and the earth,
before that doth appear that can never be shaken, the noble, royal seed,
elect and precious, which was before the world began; being heirs of him,
come to inherit him; in him ye shall know that which cannot be shaken.
And there is the true joy, the standing joy,
in that which is from everlasting to everlasting, who is the beginning and ending;
here is not any lifted up, nor cast down.
So I say, hear his voice, and harden not your hearts; for through not hearing his voice,
ye harden your hearts, then ye provoke God to wrath and sore displeasure.
Let him have your ear, that speaks from heaven; that ye may come to observe his counsel,
teachings, instructions, and directions.
For all the prophets, the holy men of God, and the apostles,
were attentive and obedient to this heavenly voice, who witnessed to the truth,
who had a witness in heaven also; and such declared forth the glorious truth,
which they had from the instruction of the Almighty.
As ye may read throughout the scriptures,
what glorious expressions and weighty truths they declared,
whose ears were attentive to him that spake from heaven;
and how they declared against them that stopped their ears, and closed their eyes,
and hardened their hearts.
For such, whose ears are not attentive to the heavenly voice, are earthly; so,
if the earthly, and sin, and evil have the ear, it will fill it with that which is bad,
and harden the heart, and choke the good: therefore the Lord must have the ear,
who is the ruler of heaven and earth.
And as your ears are attentive to the Lord`'s voice that is from heaven,
iniquity`'s mouth is stopped in you, the throne of iniquity is thrown down in you,
(that is, the wicked spirit and power,) wherein iniquity sits,
and the chamber of imagery is thrown down in you,
where man`'s thoughts and imaginations are.
But as the ear is attentive to the voice of him that speaks from heaven,
ye will come to the throne of the Lamb, who hath the victory and the dominion:
that all may live in the everlasting power of God, that goes over all deceit,
which was before deceit and darkness were.
And always feel a growing in the power of the Lord God,
that is universal and everlasting,
that ye may be all heirs of the power of the endless life, and come to inherit it,
and possess it, and sit down in the possession of the same;
that every one`'s lot may fall in the land of the living,
where the Lord hath his glory and his honour forever and ever.
Oh! the glory of the Lord spreads itself over all!
And here as ye abide, ye have the savour,
and can taste your meat in the power of the Lord God,
feeding upon every word that proceeds out of the mouth of God, having your ear open,
and attentive to his voice; in this ye grow up in the life that is eternal.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 184.

All Friends, be obedient to the power of God, which is the higher power,
and is above that which abode not in the truth.
So ye that know the power of God, be obedient to it;
for ye have authority from the power of God,
which comprehends all the powers of darkness, to answer the witness of God in every one;
and to trample upon all the power of darkness, and its authority.
For ye that feel the power that comprehends the world, and all the powers of darkness,
keep in the authority, in the power of God.
Mind not words without the power, nor the pleasing of the reason and carnal knowledge,
wisdom and understanding, of fancies and thoughts of men; but dwell in the authority,
(the power of God,) ye that know it: that over all ye may reign in the seed,
who fulfilled the law and the prophets; who spake with authority,
and speaks with authority now, more than the scribes and Pharisees,
the writers of the law and of the prophets, and the speakers of them,
who were transgressors against the life that gave forth the words which were written.
And so, the authority of the scribes and Pharisees, who wrote Moses and the prophets,
is as the authority of the professing christians,
who profess Christ and the apostles`' writings,
but are without the life and from the seed of God;
these are one with them who put Christ to death, and knew not the authority of the seed.

[.signed-section-signature]
G+++.+++ F.
