== Epistles 232 &#8212; 244

[.centered]
=== Epistle 232.

[.blurb]
==== The second epistle.

Friends, this is the day of the trial of your faith, and therefore be faithful;
for the faith is it by which you have victory and access to God;
by faith all the fiery darts of Satan are quenched,
and by faith the mountains are subdued and removed;
and in this faith all your sacrifices are accepted of God,
and that gives you victory and access to God; and in this faith you please God,
and that gives you victory over that which displeased him;
and in this faith you have all unity, which is the faith of God`'s elect; the one faith,
which keeps you in the oneness, and all the sacrificers, and worshippers,
and religions that are not in this faith, are not one,
their sacrifices nor offerings God hath no respect to, but they are like Cain`'s,
that went from the presence of God, and persecuted about his religion,
who built a city in the land of Nod, which signifies, wandering to and fro,
and unsettled, and tossings to and fro, up and down.
And this is the city that all that persecute about religion live in, the land of Nod,
tossings, wanderings to and fro; let them be of what profession or religion soever,
heathen, Jew, or Christian, if they be persecutors about religion with carnal weapons,
they are in Cain`'s land of Nod, wandering out of the faith of Abel, of the elect;
in which faith God accepts the sacrifice, and these are in the land of the living;
but Cain`'s land of Nod, where the envious ones are persecuting others about religion,
in that land God has respect to none of their sacrifices not religions.
The outward Jews had outward weapons to hold up their outward services,
for which they had a command from God;
but the heathens had no command from God to hold up their inventions;
and Christ Jesus came to end the Jews`' law and commandments,
that held up their outward services, together with their outward weapons,
and all outward things.
And he who is the substance reigns, for all the types, and figures,
and shadows were given to man, after man fell,
but Christ that comes to redeem man out of the fall,
to the state that he was in before he fell, ends them all, and in him there is no shadow.
So he sets up a spiritual ministry, and spiritual worship, and a spiritual fellowship,
and a church that is without spot or wrinkle, and a religion that is pure from above;
and this religion is ruled with spiritual weapons.
And now, friends, here you may discern what is set up by Christ and his spirit,
and what is set up by man.
For Christ who ended the Jews`' laws and commandment, who preached,
and taught his disciples who were to go into all nations to preach the gospel,
to gather people unto him, and to establish churches; he gave forth no command nor order,
that those that would not hear them, nor receive them, his law, his commandment,
his doctrine, should be persecuted, imprisoned, or banished; though he suffered,
and was blasphemed, and persecuted, and his apostles, for publishing forth the truth;
and he rebuked them that would have had men`'s lives destroyed, and said,
that he came to save men`'s lives.
And the apostles, and the true church in the primitive times, before the apostacy,
that were in the spirit of Christ Jesus, walked in the doctrine of Christ,
and his commands, and did not persecute any about religion,
nor imprison among themselves, nor others about religion,
though they had ordinances and commands amongst them for the utmost;
and if they rejected the churches counsel, they were to be left as heathen,
which was the utmost penalty.
And so here you may see,
the spirit of Christ did not persecute any for not
observing that which it gave forth and set up,
which it received from God.
Now here is a distinction betwixt the spirit of Christ, and the spirit of fallen men;
for that which man`'s fallen spirit sets up, which he hath invented,
if others will not fall down to it, and worship it, he persecutes them.
This is the practice of the heathen and Jews, that transgressed the law of God,
and followed their inventions, who persecuted the prophets, and killed the just one.
And this is the practice of the spirit of all the apostatized christians
from the primitive spirit which was among the christians,
which was the spirit of Christ.
So that spirit that does set up ordinances commandments, ways, religions, worships,
and persecute others because they will not observe them; this is the spirit of the world,
that lusts to envy, and not the spirit of Christ.
And also those are the works of men which they persecute about,
and not the works of Christ, which neither he nor his apostles persecuted about.
And so here is a clear distinction to you,
that you may know what leads to the spirit of Christ,
and what lusts to the spirit of envy;
for the spirit of Christ does not persecute any that
do not receive that which he sets up;
but the spirit of the world doth persecute them that
will not receive that which it sets up.
And in this you may try both fruits and spirits (as the rod of Moses devoured
up all the magician`'s serpents) of the lying signs and wonders;
so shall the rod of Christ, who has all the power in heaven and earth given unto him,
who will rule all nations with his rod of iron.
Christ`'s rod shall and will devour all the serpents
and lying wonders of the spiritual Egypt and Sodom,
yea, and all the serpents that be in all nations; for all nations are to be ruled by it.
And Moses`' song was sung when his rod had devoured the serpents,
and the outward Egyptians in the sea: so the lamb`'s song shall be known,
as all the spiritual Egyptians`' serpents are devoured by Christ`'s rod;
and the spiritual Egyptians being overthrown in the sea,
the Jews in spirit shall rejoice and sing the song of the lamb.
The abomination that made desolation, that is spoken of by Daniel the prophet,
which should come in after the daily sacrifice was taken way,
and should continue one thousand two hundred and ninety days;
this abomination hath made desolate from the truth, light, life, and the power of God,
true religion, and true worship, and true church and fellowship.
So the beast that John saw and speaks of, which must continue forty-two months;
and the whore, the false church, upon the beast;
which beast should be worshipped forty-two months; the time of his continuing;
and the whore should sit in her scarlet, the false church upon the beast.
The true church this time has been in the wilderness
a thousand two hundred and threescore days;
which is now come out again,
and the man child is come down from heaven to rule all with his rod of iron,
and the lamb and the saints shall have the victory, who make war in righteousness,
and are going on conquering and to conquer.
And so you followers of the lamb be faithful and valiant for the truth upon the earth,
and heed not your native soil,
but mind the birth that is born and brought forth from the womb of eternity,
that separates you from your mother`'s womb, by which you believe in God,
and fear not man, what he can do unto you; neither look at the hills for salvation,
for the Lord can make the rocks a standing pool, and the mountains streams.
And therefore dwell in the power of God, which was before the fall of man was;
whose fallen spirit persecutes those who are come to taste
of the power of Christ`'s resurrection and life,
and in this power of God you will not be weary nor faint,
which was before the fallen spirit was that doth assault you.
And in this power you will have stability, content, comfort, joy, and peace.
And keep over that spirit, let it not have power over you,
that may receive the truth in a notion, and may be a little civilized by it,
that is ready to join with every gainsaying core,
and is ready to wander after every strange thing that is new,
and so will follow strange flesh, who are uncleansed by the power of truth,
and unestablished in it; and such often have their religion to seek,
that live in questionings and disputings in carnal reasons, out of the power of God,
in which is the fellowship, the one thing, which is Christ the substance,
in which all stability is felt, which has little room in such hearts.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 233.

All you prisoners of the Lord for his truth`'s sake,
and for keeping the testimony of Jesus Christ, against all the evil inventions,
traditions, rudiments, will-worships, feigned humilities,
and self-righteousness of them that be in the fall,
who are out of God`'s power and righteousness, who have no weapons but carnal,
like themselves carnal.
Your patience must overcome all these rough and hasty spirits in the world,
and your love must bear all things; for patience obtains the crown which is immortal,
which runs the race.
So it is the Lamb must have the victory over all the unclean airy spirits,
and over him that is out of the truth.
So, be meek and low, then you follow the example of Christ,
and come to bear the image of the just, who suffered by the unjust;
and put on his righteousness, who suffered by the unrighteous; whose back was struck,
and his hair was plucked off, and face was spit upon, and yet cried,
"`Father forgive them.`"
Here he kept his dominion, a sufferer who had the victory,
which the followers of the lamb do in measure attain unto.
So put on courage, put on patience.
Let your loyalty be known; for your king that hath conquered the devil, death, and hell,
in walking in righteousness, peace, and truth, feeling the power of God,
teaching every one of you when words are not uttered.
And let your faith be in the power that goes through all things, and over all things,
and every one hearken to it.
So the power of the mighty God know, (the arm,) and how it works,
and the hand how it carries you, which brings out of tribulation, and thraldom,
and spiritual Egypt, into peace.
And this is the power of God, in which you feel to before enmity was,
and be at peace one with another, then you live in the prince of peace`'s kingdom,
and dominion, and life; in which is unity, which was before enmity was,
which destroys it.
And so in the power of the Lord God you are made strong,
which goes over the power of darkness, and was before it was,
which is out of the power of God.
And all people that are from the witness of God in their own particulars,
they are all weak and feeble, and stagger.
All men and women`'s strength is in the power of God;
that goes over the power of darkness.
So feel all this to go through all, and over all, preaching and working in you;
and let the ear be lent to it, and hearken to it in one another.
And by it feel the seed raised up in one another, which is heir of the power,
that you may know each your portion.
For all people that be from the witness of God in their own particulars,
that are erred from it, and hate the light; they are full of darkness, sin, and iniquity.
Inspiration and revelation,
while their minds are erred from the spirit of God in themselves, are hid from them.
So when their minds are turned with the light and spirit of God, towards God,
then with it they shall know something of revelation and inspiration;
as they are turned with that of God from the evil, and emptied of that,
then there will be some room in them for something
of God to be revealed and inspired into them.
And therefore in that, they will have prophecies, and seeing things to come;
being turned from the evil that hath darkened them, and separated them from God;
in which they will see the covenant,
through which they will come to have peace with God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 234.

[.salutation]
Friends,

You who now come to suffer by a land flood, keep on the rock, for there is safety,
though a storm be in the sea, and the flood be great, and the winds great,
and the way rough and crooked, the seed Christ can make all plain.
And so think not the winter and cold weather, nor the night, long;
for the lilies do grow, and the gardens do give a good smell;
and there is a difference between the carnal mind and a spiritual,
and the meetings of Adam in the fall,
and them that be gathered into Christ the resurrection, and the life, and power,
and spirit.
And the sun shines, and the light is clear, and not dim, that you may see your way,
and life, though there is a storm and tempest in the sea.
And so mind the summer, and singing of birds; and not the winter and night,
in which evil beasts do yell.
And so blessed and happy are you that have the oil in your lamps,
and have risen at the voice of the bridegroom,
and have laid up in store against this day that is come; which,
now all the rich in profession, who thought they had something, are come to poverty,
your old opposers.
And the rock remaineth.
And therefore all, and every one, from the highest to the lowest,
let none take your crown, but be faithful,
for the Lord`'s ears are open to the cries of his oppressed and afflicted ones;
he heareth the groans and cries, day and night, of them.
And the Lord`'s eye is open, and he sees all the actions of men,
and times and seasons are in his hands, who is King of kings and Lord of lords;
the strong and all sufficient, omnipotent God, _Elshdy,_ who destroyeth the destroyer,
and ruineth him that would destroy and ruin all;
who by his seed destroyeth him and his works.
And so in the seed sit down, in whom ye have life and peace; and he remaineth,
and changeth not, who now reigneth and is over all; and in him live,
that hath been slain from the foundation of the world,
and prisoned and pressed as a cart with sheaves,
and yet gave his back and cheeks to the smiter,
and his hairs to the pluckers of them off.
And so in him, the second Adam, you will not be weary, nor faint,
nor think the time long of your sufferings.
For all the weariness and faintings are in Adam in the fall.
And so your church being in God, and your worship in the spirit, and power, and truth,
which the devil is out of; and your fellowship in the gospel the power of God,
which was before the devil was, keep your fellowship in the power of God,
and look above all outward sufferings, and dwell in that which is above all,
and will stand when all other is gone.
And so dwell in the love of God, and in the unity of the spirit, one with another.
And in that the Lord God Almighty preserve you all; yea,
over all that which is contrary to his power, to his glory, forever.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 235.

All my dear friends, in the everlasting power, life, and truth live,
for you cannot live without it in the winds and storms.
And though the hills and the mountains are burned, and the trees are become fruitless,
and winter hath devoured the former fruits,
and you do see that persecution hath choked them, and the heat hath scorched them;
whereby the untimely figs are fallen, and the corn is withered on the house-top,
and the night is come, and the evil beasts go out of their den.
But truth lives, and the power of God is over them all; and Christ ruleth,
and there is bread of life, and water of life in him, and in his house;
though the caterpillars and locusts are agreed to eat up all the green.
But, as you are in the truth, you are in its day; and they in the darkness,
are in the day of darkness.
And all who are in the truth, rejoice through Christ, in the God of truth,
and never heed prisons, for they are but for a time;
and mind him who hath all times and seasons in his hand.
And never heed the raging waves of the sea,
nor be troubled at his tongue that speaks nothing but tribulation, anguish, and bondage;
nor be troubled at the cords of the ungodly; for the cords of love,
the power of God are stronger.
And what doth he that sits in heaven, but laugh them to scorn?
And so be valiant for the truth upon the earth,
for the power is the Lord`'s. And so my love to all Friends in the everlasting seed,
that never fell nor changeth.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 236.

[.salutation]
My dear Friends and brethren,

The Lord is with you all everywhere, who suffer for his name and truth`'s sake,
in all your bonds and afflictions be of good comfort, for the Lord is with you;
neither be dismayed at your sufferings, for if you suffer, Christ suffereth;
and if you be persecuted, it is Christ that is persecuted; and if you be not visited,
it is Christ that is not visited; and if you be oppressed, it is he that is oppressed.
And he will lay no more upon you than you are able, to bear.
And the angel of his presence suffered with the outward Jew,
and Christ suffereth with the inward Jew in the spirit:
and so hath a fellow-feeling with you all, in all your bonds and afflictions;
and Christ who suffereth, will overcome all his enemies.
He reigns, and they must be his footstool to stand upon.
And so, be of good faith, and be valiant for the truth upon the earth.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 237.

My dear friends and brethren, all everywhere, keep your habitation and your first love,
and do not go forth from your rule of faith and life within;
in which you all have unity and fellowship,
and the Lord will be your comforter and teacher.
And if you do not go forth from the light, spirit, and truth within,
the light you will feel to guide and lead you, and instruct you.
And by it you may have immortality put upon you.
And be not ashamed of Christ Jesus the light, and life, and teacher;
nor of his spirit to lead you.
For, can they find no occasion against you, but because you worship God in spirit,
and obey the command of Christ Jesus.
And so, as the old cry was, "`away with such a fellow from the earth,
it is not fit for him to live;`" so it is now.
But blessed are those that keep their habitations clean,
and live in the power of the Lord, which was before the curse was.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 238.

[.blurb]
==== A General Epistle to all Friends.

All my dear friends and brethren, who are of the royal seed of God!

Patience obtains the victory that runs the race and obtains the crown;
be married and joined to the seed Christ the Lamb,
slain from the foundation of the world; from its foundation, I say.
For as you are joined to the seed,
and married to that which hath been slain from the foundation of the world,
which hath the victory and doth overcome; by this you come to the end of the world; mark,
to its end.
And now all Friends, look upon the sufferings that have been since the fall,
and since the world began.
And again, look upon the valiant prisoners,
and such as stood with the Lord and for the Lord, and followed and obeyed his movings,
and motions, and commands; with the victory they had, how they triumphed in the Lord,
over that which was against the Lord; for by faith Abraham forsook his country,
and his Father`'s house, and his national worship.
And by faith was Abel`'s offering accepted of God, unto whom, God had respect.
Therefore did wicked Cain persecute and kill him about his religion.
And this was not long after man was fallen from the righteousness, and the power,
and the image of God, which man was made in.
And by the faith, and the power,
and wisdom of God did Moses go down and speak to Pharaoh the king of Egypt,
and through the power, and hand, and arm of God he led them out of Egypt;
which signifies misery, thraldom, and bondage; though afterwards when they were come out,
and had tasted the power of God, many fell.
And Moses saw Christ, the great prophet that was to come, which was to build his house,
(as Moses by the wisdom of God had done his, in the time of the law, with types, figures,
and shadows,) and so look upon Moses how he conquered all the magicians,
and comprehended all the sorcerers, and soothsayers, and Pharaoh`'s religion,
and their worship, and could not bow nor bend unto it.

Look upon Joseph, who through the enmity in his brethren was sold into Egypt,
who underwent reproach and imprisonment; unto whom God gave power over all at last,
and confounded all the wise men, and the national worshippers in Egypt,
and came in favour over them all by the power of God.
And remember Abraham, who was in the faith and the fear of God;
and how Abimelech`'s house for his sake God plagued.
Therefore keep in the faith of Abraham,
then who wrongs you the hand of the Lord will turn against them.
And whilst they stood in the power of God, what victories they had over their enemies!
As instance Sampson, David, and Saul.
But when any went from the command of God, how under the heathen they fell!
So now ye who are come to God`'s power, which goes over the power of darkness,
and before it was; in that stand, triumph, and trample;
who are come to the end of carnal weapons, and striving with outward arms.
And ye may look upon them, how valiant they were over the Philistines,
both Sampson and David, and his mighty men, when they were in the power of God;
and how David`'s three mighty men broke through a
whole host to fetch water to refresh David.
Therefore now ye in the power of the Lord, the mighty God,
go over all the Philistines of the earth, and their carnal weapons,
as there they in the time of the law did with carnal weapons.
And how often Jacob`'s well was stopped up (the beloved of God,
the second birth) by the Philistines; but Jacob did thresh the mountains as he did arise,
and drove them away; by which he might drink again.
So read this in the substance, who are come to the second birth,
which goes over Esau and the Philistines, both which was before they were.
And also remember how the prophets were imprisoned, and put into dungeons and stocks, etc.
As in particular Jeremiah, and how they were mocked, and scoffed at, and reproached,
for declaring against the sins and wickedness of the times, both by rulers, teachers,
and people; and yet by the power of God they were carried through, and over all.
And the cry was then "`Cursed is he that puts his trust in man, or feared man,
or the arm of flesh,`" etc.

So remember Daniel, and the three children, though prisoners,
yet could not bow to the national worship, and so were cast into the fiery furnace,
and the den of lions, unto whom the Lord God gave dominion over their enemies,
and confounded the national worshippers, with all the magicians,
and made the king to change his decree and law.
And this was in the Babylonish monarchy; and when the Medes and Persians got up,
the power was changed, then they cast Daniel into the den of lions,
because he prayed to his God contrary to the king`'s decree,
to whom God appeared again and confounded them all,
and made the king or emperor to change his decree.
Therefore keep faith in the power of God,
for that is it by which the elders of old obtained a good report.
And consider Mordecai, who stood faithful, and could not bow to proud flesh,
though it was in danger of destroying all the Jews, over whom, through obedience to God,
he gave him victory, by which he came to answer the good in all people.
Now consider, they that came to profess Christ, who was the substance before the types,
figures, and shadows, which were held up by the Jews in the law, and first covenant,
and priesthood, and ordinances, (which Christ the substance came to end,) how that,
I say, the christians of old by that kind of people, the Jews,
as you do now suffer the most, and have done,
by them that are the greatest professors of Christ`'s words,
but out of the life and power of Christ,
which the apostles and saints were in in the primitive times.

So it is no new thing, and, as Solomon saith,
"`here is no new thing under the sun;`" for it is not a new thing for the birth
that is born after the flesh to persecute the birth that is born after the spirit.
And look upon the apostles, and consider how they suffered,
(and by whom,) that bore testimony to the substance;
their sufferings were by such as were in the husks, shadows, inventions,
and rudiments of the world, and such as were fallen from God`'s righteousness, image,
and holiness, and not in the renewed state.
And consider how that the Hebrews suffered the spoiling of their goods by the Hebrews,
who were called Jews, as you may read in the epistle to the Hebrews;
for ye read in few of the epistles,
that the Gentiles suffered the spoiling of their goods,
(or the christians by the Gentiles,) but mostly by the Jews, the great professors,
as you do and have done in these days.

And consider how the witness hath been slain,
and (the true church,) the woman fled into the wilderness, who was persecuted;
and how she hath been fed there of God;
and how since that time the beast and dragon`'s worship hath been up,
and the false prophet, and the whore,
(the false church,) which hath ridden on the beast in the dragon`'s power,
whom the people have worshipped;
who hath caused all nations to drink of the whore`'s cup of fornication.
Now you that have come to the end, and beyond all the worships of the beast,
and after the worship of the dragon,
who come now to fathom the whore (the false church) and the false prophets,
and come to see the power, and to be in it,
that takes them and casts them alive into the lake of fire,
(which hath been worshipped,) and burns the whore`'s flesh with fire;
which power gives them dominion over them all, and to see to the very apostles`' days,
what they were in, and what hath got up since then;
for it is sixteen hundred years since the false prophets and antichrists came in,
(therefore they may plead antiquity.) Now with the power
of God ye may look what tricks they have played in the world,
since the primitive times in the apostacy:
but now is the bride coming up out of the wilderness,
and the prophet is arisen and arising, and the everlasting gospel shall be,
and is preached again to all nations, kindreds, tongues, and peoples,
of them that dwell upon the earth; and the reapers are going forth to reap people down,
and so up to God, and to bring them into the barn,
and to gather the wheat into the garner.
And people shall come to worship God, that made heaven and earth, the sea,
and all that is therein, and the beast`'s worship, and dragon`'s worship,
and the great whore`'s church is falling,
(the true woman is coming up,) false prophets are falling,
true prophets and true witnesses are rising and risen.
Sing, triumph, and rejoice; glory in the highest! trample, tread,
and bow them before the mighty God: let the wicked,
bow before the gates of the righteous.
Sing and rejoice, the heaven of heavens praise the Lord!
Now the dragon`'s worship, beast, false church, false prophet are taken,
the old dragon cast into the lake of fire,
(and with him the false prophets,) and the flesh of the whore burnt.
Reap out, reap out, reap out, I say, (with the power of God,) ye reapers unto the Lord,
for here is the day of harvest; for as the other falls, the day of harvest is known,
a day of gathering; for it is that which hath inwardly ravened that hath scattered.
For the inwardly raveners, and wolves in sheep`'s clothing,
whose fruits have been briars and thorns, and thistles,
are them which have made up the false church, the whore, the false prophets,
and the beast`'s worship, and the dragon`'s worship out of the truth,
which have made the world like a wilderness, overgrown with thistles, thorns, and briars,
in which lodge the wolves and dragons.
The beginning of this ravening into this state was
a matter of sixteen hundred years since,
amongst whom is found the blood of the martyrs, prophets, and saints in the faith,
and in the testimony of Jesus, shed in this dark night of apostacy, separation,
degeneration, with all their compelling worships, inventions, laws, traditions, churches,
rudiments to be observed, and cups for people to drink.
In these, I say,
and among these have the righteous suffered since the days of the apostles:
and among them is the blood of the martyrs, and the prophets,
and holy people of the royal seed found; and by them have they all suffered,
and from amongst them will God fetch his royal seed with his own hand,
and with his mighty power will he fetch it.
Glory over all to him! rejoice and sing praises, he is now triumphing gloriously,
and bringing you over with his power, that ye might see to the beginning before man fell;
and know the state of the Jews in the law,
and the state of the christians in the end of the law,
and the state of the apostatized pretended christians since the apostles`' days,
out of both law and gospel, how they have gotten up,
and in what they have lived out of the life and power the apostles were in,
and Christ Jesus, who is the first and the last, the top and corner-stone,
who is over all felt, and lies heavy upon the transgressors, who is the rock,
upon which the lambs leap and skip.
Him feel in you all, then ye may all feel the first and the last,
who destroys the devil and his works, (which are imperfect,) whose works are persecution,
and murder, and banishment, and cruelty, and imprisonment:
"`for the devil shall cast some into prison,`" saith John in the Revelations;
and the devil was a murderer from the beginning, and a liar, whom Christ destroys,
and his works, who was before he was, and remains when he is destroyed and gone,
and his works.

Therefore in him (the seed) have ye life eternal, and in him meet together,
and then ye are in the pastures of life, who is the first and the last,
who is over death and the power of it, and the pastures of death.
So who are in this royal seed comprehend the state and time before the law,
the time of the law, the time of christians, and the time of the apostacy:
for the seed Christ is the first and the last, the beginning and the ending;
and in the seed is the stayedness and plainness of words and life,
yet a mystery to all them that be out of it.
And who are in the seed comprehend and see the state
of the sufferings of the just before the law,
and the state of the sufferings of the just in the law, by whom,
and for what they suffered; and also comprehend the state of the christians,
who lived in the end of the law, in Christ the substance, and by whom they suffered,
and for what; even by such as were the greatest professors,
out of the life of Moses and the prophets, which, had they been in,
they would have read Christ the substance, and all them that testified of him,
and were witnesses of him: and also comprehend the state,
and see who are them that apostatized from the apostles,
and the church in the primitive times, who have been the sufferers,
and who it is that hath made them to suffer, and for what.

So the measuring line of righteousness is in this known;
and also the state now wherein the Lamb and the saints shall have the victory;
and the rising of the witnesses, and the prophets,
and the reapers going forth to reap the earth,
and the woman is coming out of the wilderness,
and the worshipping of God that made heaven and earth, the sea and the dry land is known;
and the destruction of the devil`'s worship, and the dragon`'s, and the false prophets,
and the great whore, (the false church,) and the saints shall reign,
and the lamb shall have victory; and the bride, the lamb`'s wife, shall be known,
which is the true church, which Christ is the head of.
So in this live; that is, in the life and power of Christ, in Christ the substance,
in which ye may know him, the first and the last,
and the gospel fellowship which is preached again; which gospel is the power of God,
which was before the power of darkness was,
which hath darkened life and immortality from people; in which power,
life and immortality come to be brought to light again to people;
in which power of God is the fellowship which is a mystery.
So wait to know every particular of yourselves, to be heirs of this;
and know your portion, the power of God, the gospel fellowship,
then are ye members one of another, and living stones,
that build up the spiritual household.
And also know the cross of Christ, which is the power of God,
which crucifies from the state in the fall and the apostacy; in that state, I say,
that Adam and Eve, and all their sons and daughters are in, in the fall; where,
in that state, they glory in the creatures, and in their shame, and in their inventions,
or in their strength, wisdom, or riches.
But glorying in the cross of Christ, the power of God,
the glorying is in that which doth crucify from the state of Adam and Eve,
and all their sons and daughters in the fall;
and from this state all the apostate christians are since the apostles`' days.
And in this power of God is everlasting glorying;
which is a cross to all that live (as I said before) in the apostacy, and in the fall;
but not a cross to them that be redeemed and crucified;
for their glorying stands in it which is over all the gloryings in the fall,
and all creatures.
So in the power of the Lord God meet, wait, live, and dwell, and have fellowship;
for in the power Christ lives.
Therefore now you that are come to know the gospel
preached again which was amongst the apostles,
in this power of God you will feel before the fall of Adam and Eve,
where all things were good and blessed in the beginning before the fall; which,
after the fall, the curse came, which brought the woe and misery:
so you that feel the redemption out of the fall,
you know the state of the blessing before the fall, how all things were good and blessed:
come into the same power that brings you up before the fall,
and brings you to be gathered in the name of Jesus, which is above every name,
and be gathered into the name of Jesus, by which salvation is brought;
for there is no other name under heaven given, by which salvation is brought,
but by the name of Jesus.
So, ye being gathered in the name which is above every name,
and also in the name by which salvation is brought, and by no other name; in that wait,
and meet, and keep together; so ye will feel the blessing of the Lord in you,
and amongst you.
So farewell.

And consider how the servants of the Lord, and his royal people, and prophets,
feared not flames, feared not dens of lions, or dragons, heeded not prisonments, bonds,
banishments, whips, nor scourgings, nor spoiling of their goods, and their tortures;
nor feared not their being sawed asunder, nor their stocks, their clubs, and staves,
nor persecution; but chose rather to suffer reproach with the people of God,
than to enjoy the pleasures of sin for a season.
Add how that reproaches, slanders, vilifying words they regarded not,
but trampled upon such and said,
the sufferings were not to be valued with the excellency and riches of grace,
which they were made partakers of.
And the cry was, what shall separate us from the love of God,
which we have in Christ Jesus?
Shall death, shall famine, or sword, or persecution, or cold, or nakedness,
or things present, or things to come, or heighth, or depth, or angels, or men,
or principalities, or powers, separate us from the love of God?
etc. For by the powers were all the national worships held up, as they are at this day,
and the false prophets, the teachers,
and the powers joined together then against them that were in the faith;
by which faith they overcame and said,
there was not any thing that was able to separate them from
the love of God which they had in Christ Jesus.
Mark!
Christ the seed, who destroys the devil and his works;
in which seed (Christ) ye come over the devil the author of all prisoning, persecuting,
darkness, ungodliness, unrighteousness, unholiness;
Christ who doth subdue all things to himself, whose kingdom is an everlasting kingdom,
and dominion an everlasting dominion over all dominions.
And in this kingdom and dominion have ye all peace, where no unrighteous thing enters.
And so in this ye come to be a free people, in life, and power, and dominion.
And there is no new thing under the sun, for the wicked cry light is darkness yet,
(as of old time,) and call good, evil; and evil, good; and truth, error;
and cry up the false teachers and prophets for the true; and false church and worship,
and the feigned humility, for the true; and the blind zeal, for the good and true zeal,
now as in former days.
And so it is the old enemy of mankind and his works, which the seed destroys, who reigns.
Glory forever to the Highest.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 239.

[.salutation]
Friends,

All outward things, figures, types, shadows, and inventions,
have been set up since Adam fell; which inventions Christ destroys, and the types,
figures, and shadows of him he fulfils, and brings man up out of the fall,
to the seed he was in before he fell; and so in the power of God, into peace, love,
and unity, and into the everlasting fellowship.
Cain differed from Abel in matter of worship; Abraham from his countrymen and nation.
Likewise in matter of worship,
Moses and the children of Israel differed from the Egyptians and the Canaanites,
and other nations, in matter of worship.
Yet after the children of Israel were brought out of Egypt by the power of God,
how soon after did they set up a calf, an outward thing?
Therefore in the power of God keep over all things, and in his wisdom.
And how soon Cora, Dathan, and Abiram began to offer a strange sacrifice,
after they were brought out of Egypt by the power of God; and went from the power of God,
in which they should have offered; therefore in the power of God keep.

And how soon the children of Israel (when they multiplied
and grew numerous,) offered out of the life of the law,
and the power of God; then their sacrifices were like unto the cutting off a dog`'s neck,
and blessing idols: therefore keep in the life and power of God.
And ye may see Daniel`'s religion and worship differed
from Nebuchadnezzar`'s the emperor of Babylon,
and likewise differed from the Chaldeans and Persians,
as yours comes to differ now from all the apostates,
gone from the apostles`' and Christ`'s life and doctrine.
And there is the mystery of Babylon, as the Jews differed from outward Babylon;
therefore keep in the power of God, that keeps you to the beginning.
And also ye may see what differences there were among
the churches in the primitive times,
about meats, drinks, days, and times,
but the apostle tells them the kingdom of God stands not in such things,
but in righteousness, peace, and joy in the holy ghost.
And they were not to judge one another about such things; for meats were for the belly,
and the belly for meats, but God would destroy both them and it;
and showed them that it was below christians to jangle about such things.
And also what jangling was there in the church in the primitive times about circumcision,
which the apostle brings them off, and tells them,
that circumcision nor uncircumcision availeth nothing, but a new creature.
Therefore mind that new creature, and the faith that works by love.
And how also there were janglings about baptism and the supper, and about men,
some for Paul, and some for Apollo, etc.
But the apostle directed them all to know Christ the seed, in the male and female,
and told them he preached Christ in them, and bid them examine themselves,
and prove themselves, and to know him to be in them, otherwise they were reprobates;
and he brings them off from things that are seen,
for the things which are seen are temporal, but the things that are not seen are eternal.
Now these things which they jangled about, were things that were seen,
and not eternal things, but temporal; for, if they did not come to Christ Jesus,
the substance of those things, they remained in the reprobation from the life, truth,
and substance.
And also what janglings there were amongst the primitive christians,
about marriage of believers and unbelievers,
and the departing of the believers from the unbelievers; which the apostle told them,
that marriage was honourable in all, and the bed undefiled;
and how that they should abide together, the believer with the unbeliever;
and how that the believer sanctifieth the unbeliever,
by which their children were not unholy, but clean;
and how it was better to marry than to burn;
though he spake to the same Corinthians of a state which was beyond that.
And likewise, also how there were janglings about ministers and teachers,
about such as transformed themselves as into angels of light,
and such as preached for filthy lucre, and such as served not the Lord Jesus Christ,
but their own bellies; the apostle stops all such, and brings them to the life, and seed,
and power of God over them all; and shows concerning marriage,
how God made them male and female in the beginning;
which was the honourable marriage before the defiled state was.

And likewise what janglings there were, whether the woman should be covered,
or the man should be covered, when they prayed or prophesied;
in which the apostle set forth a comeliness among them, of the man`'s being uncovered,
and the woman covered; inasmuch as the man was the image and glory of God,
and the woman the glory of the man.
Nevertheless, he would have them to know, that God was the head of Christ,
and Christ was the head of the man, and the man was the head of the woman;
and the woman was made for the man, and not the man for the woman.
And thus ye may see that these Corinthians were not
come up to the state of Adam before he fell,
and of Eve, by the apostles setting thus forth their states.
And whereas it is said by some,
"`that Christ is the head of the man,`" etc. which head of man,
(say they,) is the same that is head of the woman.
Mark, now, if it be so, according to this interpretation,
(which is wresting,) then Christ must be covered in the woman,
when she prays or prophesies, and the woman must have power over Christ,
and she be uncovered, then Christ must be shorn or shaven; which is ridiculous,
and shows then a difference of Christ in the male and the female; which is not so,
for God is the head of Christ, and Christ the head of man, as he was made,
and man the head of the woman.
But as woman received the temptation, and likewise also the man,
and so are both in the fall; now this was spoken as man was made before he fell,
which as man comes up again out of the fall, and woman,
Christ in the male and in the female is head of both.
But now this was spoken to the Corinthians,
(who were not come up to the state that Adam and Eve were in before they
fell,) among whom this difference about covering or uncovering was,
whether the man should be uncovered, and the woman covered when they prayed, etc.
Which was the comely order which the apostle set amongst them,
and told them there should be heresies among them,
that they that were approved might be made manifest, and looked upon them as heretics,
who, jangled contrary to his comely order and practice, which was, as said before,
spoken to such as were not come to the state of Adam and Eve before they fell;
for they that are come thither, to that state, by Christ,
are come before outward coverings were; and them that are come to Christ,
are come to the end of prophecy, to the seed Christ, the top-stone,
in whom all things end;
which top and corner-stone is over all that laid that ends and changes.
So let your life be in that which never ends, nor never changes,
and in whom there is no changing nor altering.
And who are come to this will not go back again into outward things.
And also ye may see what jangling there was amongst such as did forbid meats, and drinks,
and marriages; and such got up into worshipping of angels and compelling ways,
which after a time did separate, and apostatize from Christ, and the apostles,
and so afterwards became antichrists, in an anti-liberty, and anti-freedom,
to such as know all things good and blessed as they were in the beginning; which,
who are there, are out of the state which Adam and Eve were in before the fall,
where all the janglings are about outward things, which is in the fallen wisdom;
but who are come up into the wisdom, and the seed, and the life, and the substance,
and know the state of Adam in the fall, and his sons and daughters, where the curse,
wrath, and woe are and know the state of Adam and Eve before the fall,
how all things were good and blessed to them: these, I say,
are above the janglings about outward things;
for they that set up outward things are in the fall,
and there keep people from going home to the beginning,
and there is the ground of making sects about outward things,
which keeps them from the universal power of God, which was before the fall,
and brings up out of it; and that is not to preach the gospel, which is the power of God,
which was before types, figures, and shadows were, and brings up out of them.
And in this power of God is the fellowship of the gospel, which lasts forever;
so is the fellowship everlasting, that never hath an end.
For all the jangling in the apostacy brings into sects, and schisms, and heresies,
since the apostles`' days, (from the apostles, out of the life and power of God,
that they were in,) it hath been in outward things, and about outward things,
and their eyes have been at them, and about them have been jangling; which,
now ye that have seen the everlasting gospel,
and known the everlasting gospel preached again, which was among the apostles,
and have been reaped out from among the apostates, got up since the apostles`' days;
I say, live in it, and dwell in it;
in which life and power ye see over to the apostles`' days,
by the spirit that gives to have an understanding of things;
in which power of God ye do not only see to the apostles`' days,
but over the Jews`' law without, and its figures, types, and shadows,
which were given to the sons of men, and of Adam after he fell, in the fall,
which type out the life, that is to say, Christ, who redeems up out of the fall,
which man was in before he fell, and up into the state of Christ, which shall never fall,
unto himself.
And in this man seeth the blessed state, how all things were good and blessed,
and how all the works of God are perfect, and he himself God`'s work,
who set him in dominion before he fell, as he was in the power, image,
and righteousness of God.
And so Christ, who brings man out of the fall, whom all the types, figures, and shadows,
and typical things figured forth; all which he ends,
and is the substance of all variable and changeable things,
in whom all the true christians have life, and live in his life.
Now the janglings of the Jews against the christians were, about their outward things,
in the first covenant, law, and first priesthood,
that held up these things (in opposition to the christians) which God had commanded,
not seeing him whom the true christians witnessed,
who restored them out of all the changeable things,
up into the state man was in before he fell, and before those types, figures,
and changeable things were, which since the days of the apostles, and also in their days,
things were getting up, which the apostles judged;
and setting up also by such whom the apostles judged and denied,
and set forth orders and comeliness among the saints,
and preached up the substance Christ, in whom there is no shadow, changing,
nor variableness.
And that the heat of some spirits got up so high about their outward things,
that when they were not owned nor received, their sacrifices, and their will-worships,
and their feigned humility, and their observing of days, and times,
and forbidding marriages, setting up their doctrines and traditions,
which were not to be touched, tasted, nor handled, they went enviously into Cain`'s way,
and Balaam`'s, and got great men on their sides,
and admired their persons because of their advantage.
Such went from the voice of God, which brought them out of Egypt, as Core did.

And all the envious spirits rose against them that were in the power of God in all ages,
because they could not observe their outward things which they had set up to be observed,
which they that were in the universal power of God, which was before the fall was,
could never do; for their freedom stands in that;
therefore is Cain wrathful (against his brother,)
who is the wanderer and vagabond from God`'s voice,
way, life, and acceptation.

So ye may read all, the state in the fall from God`'s power,
where the forcing and compelling to outward things hath been,
which hath kept people out of the power, and from coming up to the beginning again,
and from the universal fellowship;
in which fall and apostacy have they broken to pieces into many sects, heads, heaps,
names, and peoples.
Therefore ye all dearly beloved Friends, that know the universal power of God,
that goes over all the apostacy and the fall, (where the curse, and wrath,
and woe are,) to the beginning;
you know the redemption out of this state into the beginning,
where all things are blest to you that live in love and life,
in which ye have the everlasting peace with God.
And so keep in the universal eye, and the power of God,
which keeps you over all to the beginning, which is the pure eye;
for the impure eye is in the fall, out of God`'s power;
for all the setting up outward things in the apostacy, and in the fall,
doth but keep people from home, and from going home,
that is to the state which man was in before he fell, up into that state home again;
which, when come thither, he is come out of the fall, and also out of the apostacy.
Now they that do so, (to wit, set up outward things,) gather people to themselves,
not unto God, nor home again to their first habitation;
for they who set up outward things lost their first habitation,
to keep people in the fall.
Adam and Eve lost their habitation; Cain lost his habitation not doing well;
Balaam went from his prophecy and his habitation not doing well;
And all they that went from the apostles in Cain, Core and Balaam`'s way,
lost their habitations, and so came under a chain of darkness.
As likewise all they that are inwardly ravened from the spirit of God,
who are gone into outward things since the apostles`' days, in the apostacy,
have lost their habitation,
and set up outward things to keep others out of their habitations,
and then if they do not observe them, they are wrathful against them like Cain.
And Core went from his habitation, from the power that brought him out of Egypt;
and so such come under the chain of darkness, who lose their habitations,
and they that lose their habitations, lose their first love.

Therefore to you all, this is the word of the Lord God, who have tasted of his power,
and believed in his light, and enjoyed his light, by which ye see his seed,
keep your habitations, then ye keep your first love, then ye keep unity and fellowship,
then ye keep dominion.
And let Cain, Balaam, Core, and all the apostates, and the devils out of truth,
and the sons of Adam in the fall, roar and rage never so much, ye in your habitations,
and in your houses coming up to the beginning, ye are safe and at peace.
In which, ye feel the power, and life, and seed of God, that never alters nor changes,
in which ye have the blessing and promise of God; and know the state where the curse is,
to them that goes from their habitation, and so lose their first love.
In which ye in your habitations and first love abiding, the power of God,
and his seed the top-stone are over all set.
And in the wisdom of God ye come to answer that of God in every, one,
and so come into dominion, and the habitation in which ye hear the voice of God,
and see the blessed state, where all things are blessed, as I said before,
before the apostacy, that man was drove from God, in which ye feel life and power,
and the seed which remains when all that which is in the fall and apostacy is gone;
in which ye know the kingdom of the son of God that lasts forever;
in which ye know the worship of God in spirit and in truth, which the devil is out of;
and the fellowship of the gospel, which was before the devil was;
and the fellowship of the cross, which crucifies from the state of Adam and Eve,
with their sons and daughters in the fall; and in that be glad and rejoice,
in which ye have settlement and establishment, and come to the church in God.

Therefore ye in the universal seed of God, and power of God, which fathoms all things,
that never ends nor changeth; in that all dwell and live,
that the seed ye may feel over all set, and the top-stone over all laid,
which is the first and the last.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 240.

Dear friends, keep your meetings in the name of the Lord Jesus Christ that never fell,
in which you may see over all the meetings that are gathered by all the sons of Adam,
that are out of the power and life.
You that are gathered in the name of the Lord Jesus Christ that never fell,
him will you feel in the midst of your gatherings, in the light, life, and truth.
And so look, (over all the wicked`'s prisons,) at the seed of God, Christ,
which was before they were, and will stand when they are all gone.

And so never heed the wicked`'s tempest, storm, nor hail, nor his arrows,
nor instruments of cruelty; let not the back and the hair,
the cheek and the shoulder be ever turned from him;
though many weapons be formed against him and his followers,
yet they shall never prosper, for the seed Christ shall reign over all,
and will stand when they are gone, which was before they were.

And so be faithful unto the Lord God, and be valiant for his truth upon earth!
Showing that something will oppose it, or else what need the word valiant be spoken?
And so mind the truth, (and not the wicked`'s persecutions,) and the living way,
which is Christ Jesus, who never fell nor changeth,
in which you may see over all Adam`'s sons`' and daughters`' ways in the fall,
who do change, being in the way, Christ Jesus that never fell, who doth not change;
in this way you have life eternal, in which you see over all in the fall,
(in which is death,) and so Christ being the way, he that forsakes his way,
forsakes his life; and he that doth not come out of the way of Adam that fell,
(into the way of Adam that never fell,) lives in death.
So let all haste and run for their lives into Adam that never fell,
out of Adam that fell; for Adam`'s ways that fell, are the ways of death;
but Adam that never fell is the way of life.
In Adam in the fall are trouble and unquietness;
but in Adam that never fell are peace and rest.
In Adam in the fall are shadows and turnings;
but in Adam who is the living way are no shadows nor turnings.
So every one in Adam that never fell, (Christ Jesus,) who never changeth,
the same yesterday, today, and forever; then you are in the living way,
in which you all have life, in Christ the living way, which never fell.
And so he is the way, and he that forsakes the way, Christ, forsakes his life.
In this all may sound forth, "`who hath any thing against this way, Christ,
who never fell nor changed?`"
It was Adam changed, and Eve changed,
and their sons and daughters in the fall are in the falling, changing, changeable ways.
But who are in Christ that never fell, see over them all in the fall,
that turn about with every wind as it ariseth.
And so in your way live, all in Christ Jesus, so will you feel light, life, and power;
that life which was with the Father before the world began.
In that all feed, and in that feel power,
and that way never changeth with the winds and tempest; and the cry is, haste, haste,
out of Adam and Eve`'s evil ways, in the death, fall, and changings; and run, run,
out of them into the second Adam, the life, and the way that never fell nor changeth.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 241.

[.blurb]
==== The saints`' weapons are spiritual, that the blessing of God may come upon all men.

We are not against any man,
but desire that the blessing of the Lord may come upon all men,
and that which brings the curse may be destroyed; and in patience do we wait for that,
and with spiritual weapons against it do we wrestle,
and not against any man or woman`'s person.
For amongst us Christ is King, who bringeth the blessing,
and destroyeth that which brought the curse.
And whoever dwells in righteousness, (man or woman,) and loves mercy, and doth justly,
and walks humbly with God, and hath the humility, which goes before the honour,
we are not against.
But whosoever doth unrighteously, or doth not justly, nor righteously,
nor walk humbly before God, and will have honour before humility,
God will overturn such by his power.
And in that let your faith be; for we look not at persons, but at the power of God;
and know the reign of Christ amongst us.
And as it is said,
"`God save the king,`" or "`God bless the king;`"
we would not have him nor any man destroyed,
but saved; and so blessed.

And the saved man will not suffer any thing, to rule that destroys; and so our mind is,
and we would that all men were saved, and come to the knowledge of the truth,
which the persecutors are out of.

And all Friends, dwell in the endless power of the Lord, in which the supremacy is known,
and the power which hath no end; whose dominion is over all dominions,
and will stand when all other have an end; and in that is the patience felt,
which runneth the race, and obtaineth the crown; and that hath the wisdom,
which is sweet, and cool, and pure,
whereby the living truth hath the supremacy and dominion, and in that keep your,
meetings.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 242.

All my dear friends, this is your day to stand in him that stood steadfast,
and reigned over old Adam and the devil, and all the persecutors.
Old Adam did not stand, but Christ the second Adam, the heavenly man, stood,
and never fell.
Ye, I say, in him stand; for now is your time to stand in the life over death,
and in the light over darkness, and in the seed that bruises the serpent`'s head,
in whom you all have life, dominion, and peace.

The Lord is coming upon the wicked in his thundering power, for they are ripe.
For they are all corrupt with blood, and their flesh is rotten;
and they are fallen into the pit,
being led by their blind guides into the pit and ditches, where they rot and stink,
being putrified with the heat of their lusts.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 243.

[.blurb]
==== To Friends in Barbados, Virginia, Maryland, New England, and elsewhere.

[.salutation]
O friends!

You all that have tasted of the power of the Lord God, and of his truth, that is pure,
and doth not admit of any impurity nor change.
Oh! therefore the holy truth mind, which will let nothing that is unholy in you live.
For nothing that is unholy can enter into the kingdom of God;
and none that are disobedient to truth must enter into the paradise of God; for,
because of disobedience was man and woman put out of paradise.
And therefore all everywhere, mind the pure power of the Lord God,
and the truth which first convinced you;
and whatsoever is gotten up through the carnal reason,
and your eyes going from the power of God, and that which did convince you;
let that be purged out of your hearts; if not,
it will lift up your hearts to consultations, subtlety, questionings, reasonings,
and disputes.
Oh I feel too much of that which hath gotten up into the wrong understanding part,
through which wrong liberty gets up, which will bring a plague into the heart,
which is worse than an outward plague.
Oh! therefore consider,
the life and the power of God hath not the supremacy in all your hearts;
for I feel some minds, and some bodies have let in that which hath defiled them,
and doth defile them.
Oh! cleanse, cleanse, cleanse, and join to the pure immortal power; for, the power,
of the Lord God will make room for itself,
either in cleansing or in vomiting or casting out them and
that that doth not join to the power of God.
Sodom, that whorish and adulterous spirit, it must to the fire;
and gainsaying Core into the earth.
And it will throw down that which hath been lifted up.
The besom of the Lord is going forth to sweep,
the candle of the Lord is lighted to search every corner of your houses;
for the just walk in the path which is a shining light, which admits of no rubbish in it.
Oh! come out of all these things which you have entertained in your minds,
which you received not from them that came to minister unto you in the beginning.
Oh! dwell in the power of the Lord God, for to keep you low;
and take heed of getting up into conceitedness and the air,
and to set up that which pertains not to the kingdom of God, but to strife,
which never the apostles, nor the saints since, in the power of God set up;
for if you do, the power of God will sweep it and you all away.
And Oh! you that come to be vessels of honour, and vessels of the mercies of God,
have esteem of your bodies; for such as defile their bodies,
are neither vessels of honour, nor vessels of the mercies, but of wrath,
and are for the wrath.
Therefore keep out strife, keep out fornication and the adulterous spirit;
keep out the lusts of the eye, the lusts of the flesh, and pride of life,
which is not of the Father; that that which is of the Father, may be received,
and have an entrance into every vessel.
Oh! be not lifted up with a vain mind; and let Balaam`'s nature be slain,
that erreth from the spirit, and raiseth stumbling-blocks;
and such as keep not their first habitation in the power of God and his truth,
become enemies to such as are heirs of the kingdom, and the power of an endless life.
Therefore all Friends and people, mind that which first convinced you,
that power of God which first awakened you, and arise and live in it, that all your eyes,
minds, and, hearts may be kept single and naked to God, and to one another;
and unclothed of all that which is contrary, and is got up since.
For the seed, the life of Christ Jesus, reigns and rules: glory to him forever.

I have been incapable to write or receive writing a long time, or to speak,
or bear to be spoken to, but have been as a man buried alive,
for else I should have written to you before now; and therefore,
O dear friends! give no occasion of stumbling; keep tender;
for hardness of heart is worse than an outward plague,
for that brings destruction many ways.
And so grieve not the spirit in others, nor in yourselves.
And whatsoever is decent and comely follow; honest and of a good report;
that makes for peace, and not for strife under pretence of love; for that is not of God.
For God who is low, is not the author of strife and confusion, but of peace.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

So, I desire you to let copies of this be sent into Virginia, Maryland, and New England,
to be read among Friends in all their meetings.
Things are pretty well here, Friends being in love and unity,
and the dread of the Lord God is amongst us, who reigns and will reign.

====

[.centered]
=== Epistle 244.

[.blurb]
==== An epistle to be read in all the assemblies of the righteous.

All my dear friends everywhere, live in the noble seed Christ Jesus,
the saviour and the anointed one, and the righteous holy one, that your minds, hearts,
souls, spirits, and bodies may be righteous, living in the righteousness of Christ Jesus,
in all love, virtue, truth, and holiness, without which none can see God.
For the Lord loveth the righteous, and the righteous are in peace,
and all workers of iniquity their mouths shall be stopped.
The throne of iniquity must down, and the chamber of imagery in every heart;
for the Lord must have the heart, for it is to be his offering and sacrifice.
All lips must be pure, and hands clean, that confess the Lord Jesus Christ,
and all tongues and eyes single to God and one to another;
and all mind the Lord`'s business in the truth, and be given up to him, and in it,
serving the Lord God in newness of life;
that all your feet may be guided in the way of peace,
and to walk uprightly before the Lord in his way, which is Christ Jesus the light,
which is perfect.
This is the way of the just, which is a shining light;
and in this way is the living God well pleased with you.
And you that grow rich in the world in earthly things,
who have had a stirring in you formerly in the service of God,
take heed lest your minds run into your outward businesses, about outward things,
and therein be lifted up above the good and just spirit,
and so leave the service of the Lord and his business, in minding your own.
For outward riches, and the things of this world,
will pass away with the outward riches therein, for they have wings:
but the word of the Lord, which lives and abides, and endures forever, will remain.
Labour for the riches of it, for that will endure with you; and seek the kingdom of God,
which will never have an end, that stands in righteousness and in holiness,
in which you have joy and peace in the holy ghost; then all outward things will follow,
which are below.
So that in righteousness, holiness, and truth, as just men and holy men,
and men fearing God, and as righteous men, sons, and servants, and children of God,
you may all live, in all righteousness, holiness, pureness, truth, justice, and equity,
in all manner of life and conversation;
so that your conversations may shine as lights of the world,
knowing that all unrighteousness, uncleanness, unholiness, injustice, untruth,
and impurity are not of God, but are out of the kingdom of God;
and likewise all cheaters and cozeners, who do enrich themselves by falsehood;
and all drunkards, adulterers, whoremongers, fornicators, murderers, idolaters,
and liars; these works and workers are out of the kingdom of God and his power,
and they are of their father the devil, who is out of the truth.
And therefore in the truth live, which the devil and his works are out of;
and that truth makes you free.
In which truth and spirit is God worshipped.
All that do violence, cursed speakers and swearers,
are out of the truth and the command of Christ Jesus;
and therefore live you in the love of God, in which you may be sensible of his mercies;
in which love, you living in the pure humility, you learn of Christ Jesus.
For presumption is learned of Adam in the fall,
of the serpent that brought him into the fall,
where all the defilement is and the profaneness.
Being in the whoredom from God, where all manner of whoredom and uncleanness is,
and deceit and falsehood, the liar, and all sin, and unrighteousness, and transgression.
And this is comprehended all to be in the fall,
with the serpent that brought them into the fall, whose head Christ comes to bruise,
that is, to break his power and strength, and to destroy him and his works.
And Christ is pure, the holy one that doth this, the righteous one, the holy one,
and in him live, the second Adam that never fell;
then shall you come to know a state that will never fall,
in that which is first and last.
For Christ that sanctifies is pure, who sanctifies the impure; he who never fell,
sanctifieth and washeth them that are in the fall; he who never transgressed,
redeems out of transgression; he who never sinned, redeems out of sin,
and makes an end of it; and he who never trespassed,
comes to forgive trespasses and blot them out.
And every one that comes to witness this forgiveness by him,
who have been the trespassers against God,
they cannot but forgive men their trespasses against them,
as they come into the kingdom of glory and life, where the Lord hath his glory.
Oh! the glory of the Lord which lasteth forever!
And glory, glory be to him forever, whose everlasting glory, and life,
and power shines over all, and spreads itself, and puts forth itself over all.

O friends! let righteousness flow amongst you all, truth and equity,
uprightness and holiness, which become the house of God;
and live in the holy order of the life, spirit, and power of the everlasting God.
Keep in the faith that works by love, that purifieth your hearts;
the mystery of which is held in a pure conscience;
which faith brings you to have access to God,
and gives you victory over that which separates from God.
This is that by which you subdue mountains, and quench the fiery darts of Satan,
and overcome him withal; and in this you have all pure unity;
and you edify and build up in the holy faith the gift of God;
and this is that which is to be contended for,
which is the same that was once delivered to the saints.
Oh! live in the pure hope, which purifies you as he is pure; which hope is Christ,
who was before the hypocrite`'s hope was, who both (him and his hope) are impure;
and so feel Christ your hope, which anchors your immortal souls,
that stays it in all waves, storms, and tempests, and is sure and safe in all weathers;
Christ, who is the same today as he was yesterday; so no new thing.
For he is the rock of ages, who was before ages; who is the corner-stone,
and also the first and last, who will crush and bruise to pieces all giddy, wandering,
and unestablished spirits, and confound them who are cunning, and hunt before the Lord;
for the Lord should go before them, he should be the guide.
For they that hunt before him, will not have the Lord to be their guide,
who is the same today as he was yesterday, and so forever.
For Adam and Eve did not abide in their possession, nor Cain, nor Core, nor Balaam;
see what came upon them, and what was their end.
And likewise the Jews did not abide in the possession of the law of God,
which was just and holy.
And also the apostatized christians have gone from Christ, and did not abide in him,
who is the same yesterday, today, and forever;
therefore they are gone into so many ways, and seek after so many new ways,
and run into so many fables, as though Christ, who is obeyed one day,
should not be obeyed next day.
And this is disobedient Cain, wandering in the land of Nod, smiting at Abel,
who obeys him, who is the same today as he was yesterday, and so forever;
yea a lamb slain from the foundation of the world;
who reigns over that nature that hath slain him,
and will reign till he hath put all under his feet.
And therefore, friends, in Christ live, and in him walk; hear, obey, and follow him,
who is the same today as he was yesterday, and so forever.
And so you that are the true believers, who are past from death, and sin that brought it,
and the devil the author of it, are come to the life of Christ Jesus, (who,
as I said before,
is the same today as he was yesterday,) if your
belief stand in him that is the first and last,
the same today, yesterday, and forever.
And this is the believer that is born of God, the immortal birth;
and this birth is he that overcomes the world, that doth not sin, that keeps himself,
because he is born of God, and the seed of God remains in him;
and hereby the children of God,
and the true believers are manifest from the false believers and children of the devil.
He that doth righteousness is of God; he that doth not righteousness, is not of God.
Therefore you that feel the law of the spirit of life in Christ Jesus,
to have put down the law of sin and death in you,
(that authority of putting it down,) be ye ordered by the
law of the spirit of life that is in Christ Jesus,
which makes you free from the law of sin and death.
So in this law of the spirit of life in Christ Jesus have you fellowship, order, rule,
and government, in the law of life, and in the law of peace that gives victory,
which Christ Jesus is the author of,
who renews you up into the righteousness and holiness in the image of God,
out of the unrighteousness and unholiness, and the image of Satan.
Here the Lord hath the glory, and Christ your holy redeemer and saviour is confessed;
to the glory of God.
So wait that you may all sit down in Christ, who is the first and the last,
and the image of God, and wisdom of God; that by his wisdom, which is pure, righteous,
and holy, you may come to order all things to God`'s glory.

Adam fell from the state God placed him in; and in the fall,
Adam`'s sons and daughters turn from way to way of their own.
But for man and woman to come out of all national corrupt ways, religions, churches,
worships, fellowships, and teachers,
to the state that Adam and Eve was in before they fell, and no farther;
that is a state where he may fall again.
But, to come to Christ, who was before the world began, who is first and last,
beginning and ending, such abiding in him shall know a state that will never fall.
For Adam`'s state before he fell, was above all the earthly and worldly wise,
and knowing, and their dark understandings and perverse ways,
which their perverse spirit leads into; where are all manner of uncleanness,
unrighteousness, falsities, puffing-up and pride, and all the crooked, rough, cross ways,
and mountains of sin, which are become as graves and prisons for the just.
Adam`'s state before he fell is beyond all this, who fell into this;
but Christ that never fell, is a state beyond Adam;
and he is to be heard and followed that never fell; and in him are people to sit down,
who is the rest, and peace, and life;,who destroyeth the devil and his works,
and makes an end of sin, together with ungodliness and unrighteousness,
which hath dishonoured God; so bruiseth the head of the serpent, and breaks his power,
and crusheth him to pieces, that the seed Christ may rise in all;
which honoureth the Father.
Now this being manifest and known in all, then the lamb is known to have the victory,
which hath been slain from the foundation of the world;
and then in the seed you come to know your election before the world began.
And here the Lord`'s words are fulfilled, his glory he will not give to another,
who destroyeth that that took the glory to itself;
which brings up to that noble seed and plant in man which gives the glory to God.
And here as you live in the seed Christ Jesus,
your election you know before the world began, and reprobation since the world began.
For Core, Cain, Ishmael, Esau, Sodom, and Egypt, spiritual and temporal,
have been since the world began.
For Egypt is thraldom, bondage, anguish, and darkness, and Sodom is whoredom,
and Cain disobeyed the voice of God, and Core gainsayed the law;
and whoever feels all this nature in them, they are vessels of wrath;
and let them not complain and say, why hast thou made me thus?
For there are vessels of honour, and vessels of dishonour.
Vessels of mercy, vessels of wrath.
And it is not in him that willeth and runneth, but in God that showeth mercy.
Now Esau, the first birth, signifieth a worker.
Jacob the second birth, signifieth supplanter;
and when Jacob hath supplanted Esau the first birth, the profane nature,
Jacob is called Israel; that is as much as to say, thou hast power with God now.
So where the election is risen and hath put down Cain, Core, Egypt, Sodom,
the first birth slain, which brought all the wrath into the vessel,
and the old bottle broken; here is a new bottle that holdeth the new wine,
and vessels of honour, and vessels of mercy, in the election before the world began;
and you have all things made new, a new heaven and a new earth.

And all Friends, that be in any manner of sufferings, imprisonments,
or banishments for Christ and his truth`'s sake, live in Christ and sit down in him,
in whom you have all peace, life, virtue, and rest in Christ Jesus,
who was before all that was that makes to suffer, and will remain when it is all gone;
and was the "`first and last, the beginning and ending, the same today, yesterday,
and forever.`"
In him sit down and live, that doth not change; then your religion doth not change,
your worship doth not change, your way doth not change; for Christ is your way,
"`who is the same today, yesterday, and forever;`" and your fellowship, and unity,
and community do not change, being with the Father, who doth not change,
but is the same from everlasting to everlasting.
And they whose religion, fellowship, and worship change, and who gad about,
and change their ways, are fickle,
and have itching ears after the ways that change from Christ, who doth not change,
who is the way, the "`same today as he was yesterday,`" to be walked in.

And all Friends, that are in any temptations or troubles, look at Christ,
who bruiseth the serpent`'s head, your adversary, your enemy, your troubler,
your tempter, your defiler, your accuser, the wicked one; fear him not,
but look at Christ Jesus, that bruiseth his head, breaketh his power and strength,
and crusheth him to pieces; in Christ have you peace, which was before the devil was.
Reign in him, Christ Jesus, who is your light, and life, and salvation; and fear God,
and give glory; glory to him forever.
For this serpent, the enemy, the adversary, the devil, the wicked one, the dragon,
the accuser, the tempter, he tempted Christ to the creatures, to the glory of the world,
and to worship him, to destroy himself; but Christ bruiseth his head,
breaks his power and strength, and crusheth him to pieces,
and destroyeth him and his works.
So in him live and rejoice, in whom you have peace, and life, and dominion;
in him who was before the serpent was, the first and last, the "`same yesterday, today,
and forever.`"

Ah! my dear friends and brethren everywhere! the power of the Lord God is over all,
live in it, that you may feel a unity and fellowship in the power of the Lord God;
that through that power of the Lord God you may all
come to be heirs of the power of an endless life;
through which you may inherit eternity, and so to feel life eternal abiding in you;
the manslayer hath not eternal life abiding in him; that is, he that envies his brother.
So all the persecutors that envy their brethren have not eternal life abiding in them.
Under this all the persecutors about church, religion, worship, faith, ministry,
and fellowships, and envious persons, having not eternal life abiding in them,
are comprehended.
Therefore you all, feel this eternal life abiding in you.
And he that hath the son of God hath life eternal abiding in him;
and so in this eternal life you have an eternal fellowship with God and his son,
and with one another.
And in this the law of life, that is in Jesus Christ,
passeth sentence on the law of sin and death in every man and woman,
and brings it to the execution.
Through which law of life righteousness flows, and runs down as a stream,
and also justice and truth.
Here by this law of the spirit of life in Christ Jesus, (mark,
in Christ Jesus,) you come to know the Lamb`'s throne,
and the throne of iniquity thrown down, its mouth stopped,
and the chambers of imagery thrown down, and the household of God raised;
the fruitless trees thrown down, and the plant of God raised up,
which is of his own planting; a tree of righteousness, whose fruit is unto holiness,
whose end is everlasting life.
So mark here the fruits of this tree, and the end of this tree.
By this you distinguish man`'s planting, and man`'s plucking up;
and God`'s building you will distinguish from man`'s building; and man`'s plucking down,
and man`'s gathering together, you that are gathered in the name of Jesus distinguish,
and his scattering.
Oh! therefore be valiant for the truth, which you are come to the knowledge of,
and worship God in that truth which the devil is out of, and abode not in;
this makes you free from the devil and his works, that are out of truth.
Here in this worship, in the truth and in the spirit, the living God, who is a spirit,
the God of all truth,
hath his glory and honour from the spirit of the Lord in every heart.
And so keep in the spirit, and truth, and power of the everlasting God,
who is from everlasting to everlasting,
that you may know him Lord of the earth and of the heaven, and of the heaven of heavens,
ruling and reigning, whose eye is over all his works,
that you May glorify him in his power and spirit, and serve him in the new life;
which will keep you over all men`'s fables and devices, whimsies and imaginations,
out of all janglings and vain disputes of men of corrupt minds:
and so it is good for you all to live in him which is the
"`same today as he was yesterday,`" Christ Jesus,
the power of God, and the seed of life, and word which was in the beginning:
so no new thing, but that which was and is to all eternity:
let your fellowship be in that, and your unity and communion be in that;
for this is seen by the eternal eye, the eternal unity, and the eternal God.
So hear his voice, every one of you, that speaks from heaven,
whose voice shakes the earth, and not the earth only, but the heavens also.
The heaven imports joy: so all the false joys, the lifted-up joys, or exalted joys,
and joys in vain glory, and joys in the world, or any outward thing or creature,
and men or women; his voice that speaks from heaven shakes the earth and the heavens;
and these must be shaken and removed, both the heavens and the earth,
before that doth appear that can never be shaken, the noble, royal seed,
elect and precious, before the world began.
Being heirs of him, come to inherit him:
in him you shall know that which cannot be shaken, and there is the true joy,
in that which is from everlasting to everlasting, who is the beginning and ending:
here are not any either lifted up or fallen down to despair.
So, I say, hear his voice, harden not your hearts; for not hearing the voice,
you harden your hearts, and then you provoke God to wrath and sore displeasure.
Let him have your ear, that speaks from heaven, that you may come to observe his counsel,
teaching, instruction, and direction; for all the prophets and holy men of God,
and the apostles, were attentive and obedient to this heavenly voice,
who witnessed to the truth, who had a witness in heaven also:
and such declared forth the glorious truth,
which they had from the instructions of the Almighty,
as you may read throughout the scriptures,
what glorious expressions and weighty truths they declared,
whose ears were attentive to him that spoke from heaven;
and how also they declared against them that stopped their ears, and closed their eyes,
and hardened their hearts: their ears not being attentive to the heavenly voice,
but to the earthly.
And so if the earthly, and the sin and evil have the ear,
it will fill it with that which is bad, and harden the heart, and choke the good;
therefore the Lord must have the ear, who is the ruler of heaven and earth.
And as your ears are attentive to the Lord`'s voice, that speaks from heaven,
iniquity`'s mouth is stopped in you, the throne of iniquity is thrown down in you;
that is, the wicked spirit and power, where iniquity sits;
and the chambers of imagery are thrown down in you,
where all thoughts and imaginations are.
As the ear is attentive to the voice of him that speaketh from heaven,
you will come to the throne of the Lamb, who hath the power,
who hath the victory and the dominion,
that all may live there in the everlasting power of God, that goes over all deceit,
which was before deceit and darkness were;
and always feel a growing in the power of the Lord God,
that is universal and everlasting,
that you may all be heirs of the power of an endless life, and come to inherit it,
and possess it, and sit down in the possession of the same,
that every one`'s lot may fall in the land of the living,
where the Lord hath his glory and his honour forever and ever.
Oh! the glory, glory of the Lord, that spreads over all!
And here you have his savour, and can taste your meat in the power of the Lord God,
feeding upon every word that proceeds out of the mouth of God,
having every one`'s ear attentive to his voice:
in this you grow up in the life that is eternal.

[.signed-section-signature]
G+++.+++ F.
