== Letters 265 &#8212; 279

[.centered]
=== Letter 265.

All you that are believers in the light of Christ, which manifesteth darkness,
ye are kept by the power of God unto the day of salvation.
So, though your salvation is not yet completed, yet you have your keeper,
the power of God, which neither slumbers nor sleeps, and it will keep you unto that day.
For those virgins, in the parable, they had their keeper,
by which they were preserved in their virginity, which they were never accused of losing;
for it is said, that "`the cry was at midnight;`" that is, the mid-time of darkness;
for darkness is called night, and the voice of the bridegroom was at midnight, "`Arise.`"
Now they that had no oil in their lamps did not enter with the bridegroom,
but they that had oil did.
Now that which doth keep is the power of God,
and preserves pure unto him in the virginity,
from that which would defile the virgin mind, and the virgin soul and spirit.
For it is all from the same man of sin that defiles the mind, and the spirit,
that leads them out to defile their bodies, and corrupt them;
therefore all are to mind their keeper, the power of God, which was before the devil,
the man of sin, was; by which power of God they have oil in their lamps,
through which their lamps may be always burning in their temple,
and such come to be the temple of God; for they that defile the temple,
defile their souls and bodies, they let in the defiler and destroyer,
and so their lamps go out, and they go from God and his power, the keeper,
and such God will destroy.
And so many as are kept by the power of the Lord unto the day of salvation,
though the day of salvation is not yet completed,
yet in the day of salvation the people of God are a willing people,
even in this day of his power.
And so they are to abide with their keeper, which is the power of God;
for while they be in the night, and not in the day of salvation, nor day of power,
though they may be in the wilderness of temptations and trouble, yet may feel the power,
the keeper, to lead through all these things, out of Egypt, through the Red Sea,
through the wilderness, through Jordan, the river of Judgment, and over the Canaanites;
and therefore every one`'s faith is to stand in the power of God,
and believe in the power of God, that will bring to the day of God`'s power,
and to the day of his salvation.
For the outward Jew did not enter, because of unbelief;
and so this great foul man of sin hath defiled all mankind outwardly and inwardly.
And therefore all to have their faith to stand in the power of God, their keeper;
for the defilement is in the night, by the power of darkness, and through it.

Therefore let thy faith stand in the power of God, thy keeper, which will keep body,
and soul, and spirit clean and blameless to the day of redemption, and day of salvation;
and by the power of God such will have a dominion over the soul man of sin, the devil;
for it is he in people that leads and tempts to outward defilement of their body,
and so to lose their virginity; and it is he that draws their minds from God and Christ,
and from God`'s ways, and his worship, and his truth, and his spirit, and his grace,
and his faith that he works in people.
Therefore if thy faith stand in the power of God, all by it is preserved in this, body,
soul, and spirit, in purity and a hidden mind, soul, and spirit, secret to the Lord,
who is a spirit; and they are preserved by his power, their keeper.
For, as is the saying of some of the world, that are the most modest,
that they will keep their outward virginity to the day of their death,
or of their marriage, but such as before that have no esteem of their bodies,
no more than unruly beasts, give up their bodies to uncleanness,
and themselves to work wickedness, and so forsake their keeper, the power of God,
which should keep both inwardly and outwardly.
And so all the inward virgin minds, and souls and spirits, that are hidden to the Lord,
they will die before they will lose their inward virginity,
but will keep it to the marriage of the Lamb, as the wise virgins did;
by which power they are preserved over the man of sin,
whom Christ their husband bruises the head of, and destroys him and his works.
For Christ was before the man of sin was, (the devil,
or his works either,) who was glorified with the Father before the world began;
and therefore all such virgins as are come to Christ, and are married to him,
Christ your husband, he will deal with the soul man of sin, and bruise his head,
and break his power and strength to pieces,
and will take him and cast him into everlasting fire.

And therefore keep your faith in the power of God,
which will bring you to the marriage of the lamb; by which power of God,
which was before the devil was, you may have oil in your lamps,
that your lamps may burn always;
by which power of God you may come to the day of God`'s power,
and all to be a willing people, to serve God, and walk in truth, and to obey him;
and so by the same power of God, which is your keeper,
you may come to the day of salvation; you may have the song of salvation,
and joy of salvation, and comfort of salvation, and the possession of salvation,
and be heirs of the same.
And so here you have your keeper, to wit, the power of God.
And Peter`'s words answer to this,
"`You have a light which you do well to take heed unto, that shines in a dark place,
until the day dawn, and the day star arise in your hearts;`" signifying it is sufficient,
which you must take heed to, it will lead you to the day dawning,
the light that shines in the dark place of your hearts, in the dark place of your minds.
Now you do well to take heed to this light, for it leads you to the day star,
and day dawning.
"`Out of Egypt have I called my son,`" saith the Lord; and Israel was called God`'s son,
who was called out of the house of darkness and bondage; they had light in Goshen,
when the children of Egypt were in darkness, and could not see one another.
For now the children of light have light, and can see one another; the children of Egypt,
Sodom, and Babylon cannot see one another.
And so, they do well that take heed to the light,
but they do ill that do not take heed to the light, for they walk in darkness,
and know not whither they go, and stumble at noon day, the highest time of light;
for this light leads to the day dawning, and day star arising in their hearts,
which is a sure word of prophecy.
A prophet is a seer, and so with the light he will see,
that which doth make manifest is light; by it you shall see the day dawning,
and the day star arising, and when that ariseth, the sons of God sing together,
because of the joyful day; and the saints sing, who have long been in the brambly,
briary wilderness, and in the house of bondage, of darkness and trouble,
and of sorrow and misery.
Therefore, there is joy when the day star appeareth and the day dawn;
there is great cause of joy for all the sons of God, when the day star appears,
and for them to sing together; for long nights of trouble and travel have they been in.
"`The path of the just is a shining light,`" the path of the unjust is darkness.
So there are but two paths.
Now the unjust cannot abide to hear talk of the light, but call it natural,
and created and made, or conscience, they do not know what to call it,
whose darkness cannot comprehend the light, though it shines in the darkness; and so,
the path of the just being "`a shining light,
which shines more and more unto the perfect day;`" signifying that the day is come,
that the just hath his path, and his path is a shining light; and so increaseth,
shineth more and more unto the perfect day.
Now the unjust being in darkness, they hate the light,
and love darkness rather than light; the just man`'s path, the light,
because their deeds are evil; for the light will reprove them.

So the just man`'s path is sufficient, a shining light: for it shines more and more,
it increaseth, it it is sufficient, and brings to the perfect day.
Now the unjust, whose path is darkness, say,
"`It is not sufficient,`" but such cannot abide the light,
cannot abide the just man`'s path, nor the just neither, but hate both,
and speak against him and his path, with his darkness, that cannot comprehend the light,
though light shines in his darkness;
and therefore if he cannot comprehend the light with his darkness,
(how can he comprehend the prophets`', and apostles`',
and Christ`'s words?) but calls light darkness, and darkness light, and calls it natural,
or created, or made, or conscience; and so this comes to be fulfilled on them,
as John said, who with their darkness could not comprehend the light,
yet they would be talking of the saints`' words, law and prophets, with their darkness,
which could not comprehend the light.
They would call light, darkness, saith Christ,
"`If that light that is in you be darkness, how great is that darkness?`"
You neither know the scriptures nor the power of God.
How should they know the scriptures or the power of God either,
whose darkness does not comprehend the light?
A dark man, is a blind man.
A blind man hath not true judgment.
Therefore how should they call it otherwise, but a natural light, a created or made light?
So the Pharisees believed that Christ was to come, and preached him to come;
as the Protestants and Papists preach him, that he is come and to come;
and can tell by scripture where he was crucified,
as the Jews could tell by scripture where he was to be born.
But they were all against Christ, the light.
When he came, they said, "`Christ had a devil.`"
The Pharisees said of him, who was light, that he was the prince of devils;
who was the light, and the truth, and the life; and that he was the carpenter`'s son.
So without the light they could not see him, nor his works, with their darkness;
neither can they now, neither can they know the scriptures nor the power of God,
whose darkness cannot comprehend the light.
And John was a man sent from God, the greatest prophet born of a woman,
who came for a witness, to bear witness of the true light,
which lighteth every man that cometh into the world, that all through him might believe;
and it is said, in Christ was light; and this light was the life of men.
And so the life that is in Christ, is the light of men.
So this is a heavenly light, a divine light, a spiritual light, a saving light;
which is the life of Christ, which is the light of men;
though the professors in Christ`'s time, and these times, Papists and Protestants,
with their darkness, cannot comprehend the light, so not the life;
so no true preachers of Christ without the light and life.
John said, he was not the light, but was sent to bear witness of the light.
That he was not worthy to unloose the latchet of Christ`'s shoes.
And yet John, who had seen Christ, the lamb of God,
that taketh away the sins of the world, pointed his disciples to him,
and showed them Christ; and they forsook him and went to Christ.
For John came for a witness, to bear witness of him who was the true light;
and that he that was to came after him, was preferred before him, for he was before him.
Yet when John was cast into prison, he questioned whether Christ was he,
or whether he should look for another; and sends to Christ.
And Christ answers his messengers, and saith unto them, the blind receive their sight,
and the poor receive the gospel, etc.
And as for these Papists, and Protestants, and Jews, they question whether Christ,
the light that lighteth every man that cometh into the world, be the spiritual, divine,
saving, and heavenly light.
And further, mark Christ`'s own words. John 12:46.
He saith, "`he is the light of the world,
that teacheth you how to believe;`" to wit, all his disciples,
as Christ hath taught them, who saith, believe in the light.
Now, believing in the light, you believe in that which doth make manifest all things;
for that which doth make manifest is the light; and therefore to believe in the light,
is to believe in that which doth make manifest Christ to be their way, their teacher,
priest, mediator, interceder, saviour, and redeemer.
And he that believeth in the light, believes in that which makes manifest all false ways,
and false religions, and false worship, and false teachers, and antichrists.
For they that believe in the light, it manifests all true ways, and true religions.
And so, they are no true believers, neither Protestants, nor Papists,
who only believe Christ is come, from scripture, as the Jews believed Christ was to come,
from scripture.
But, I say, they are no true believers,
but as they also believe in the light as Christ the heavenly man doth teach.
For the Jews, may teach their people to believe from the scripture,
the Papists and Protestants may teach their children to believe from the same; but,
not believing in the light, they are no true believers, as Christ hath taught;
for Christ, who is the saviour, he teacheth people how to believe, and saith,
believe in the light.
Which is plain, that they are no true believers that do not believe in the light,
neither Jews, nor those that have got the name of christians; for believing in the light,
they become children of the light.
And so it is plain, they are no children of light but who believe in the light,
nor children of the day.
For children of darkness may profess scriptures, the devil may bring scriptures,
and Protestant, and Turk, and Papist, and Jew may bring scriptures, with a dark spirit,
and hold them in the unrighteousness; but there is no true believer in God,
nor in Christ Jesus, but who believes in the light, which the scripture testifies of;
showing there is no salvation, redemption, justification, sanctification,
but to them who believe in the light, that manifesteth all things, nor seeing Christ,
who died, and is risen for them.
And therefore the heavenly man, the second Adam, the Lord Jesus Christ,
teacheth how to believe, and saith, "`believe in the light,
while you have it;`" and this light will manifest him to be their way, their truth,
and life;
which light comes from him who enlighteneth every man that cometh into the world,
that all through the light might believe.

And so they that believe not in the light, as Christ hath taught, are no true ministers,
nor true messengers, nor true disciples, nor true christians,
nor true preachers of Christ Jesus, who believe not, as he hath taught them;
but they that lay away Christ`'s teaching,
and teach one another to deny the way that Christ hath taught to believe in,
are keepers of people in darkness, out of the light, and call it natural, created,
and made, and conscience,
and so with their darkness and blindness give the light such names,
who with their darkness cannot comprehend it; for he that believes in the light,
it lets him see the scriptures, the prophets, Christ and the apostles`' words,
and by it they do distinguish the true prophets`' words from the false,
the holy men`'s words from the unholy, the sanctified from them that are not sanctified,
Christ`'s words from antichrist`'s, the true apostles`' words from the false.
So Christ the light teacheth his people to believe in that which manifests all things;
and they that believe in the light have the witness in themselves of Christ,
in whom they do believe, they have the witness in themselves, that he is their redeemer,
and saviour, and their way, their truth, and their life; for with the light they see him,
they believing in the light that doth make manifest; and after they believe in the light,
become children of the light; they witness themselves, that they are sealed,
for their belief in the light stands in Christ the light,
who hath bought and purchased them;
and after that they are sealed by the spirit of promise,
having God`'s mark or stamp set upon them, they can set to their seal,
that God is true in all his promises, in all his prophets concerning Christ Jesus,
who taught them to believe in the light.
With the light they see,
and come to know the "`three that bear record in
heaven,`" and the "`three that bear record on earth,
the spirit, the water, and the blood.`"

First, the spirit that beareth witness in the earth, which mortifies them,
which circumcises them, which leads them into all truth;
in which spirit is their fellowship, and a bond of peace,
that keeps down that which troubles them;
by which spirit the believers are baptized into one body, brought out of the many bodies;
and so by the spirit they are brought to the one head, which is Christ Jesus,
(though there are many heads in the world,) by which spirit they are sanctified,
by which spirit they are instructed, by which spirit they worship God,
by which spirit they are covered, by which spirit they pray,
and by which spirit they sing praises to God who is a spirit,
by which spirit they have an understanding, the spirit of wisdom and knowledge,
which is to know God, and Jesus Christ whom he hath sent, which is life eternal.

2dly.
They come to know the water, which is a witness in the earth;
by which water they are washed, their minds, their souls, their spirits,
and in their bodies, with this pure water.
And this is a witness in the earth with the light; they that believe in it,
it manifesteth these two witnesses in the earth,
and with the light they see the pope`'s counterfeit holy water,
which he hath set up since the apostles`' days,
who with the light bear witness against it, not to be God`'s witness,
nor God`'s setting up.
And so the children of the light, that believe in the light, their bodies, their souls,
their spirits, and their minds are washed clean in this pure, clean, holy water,
that comes from above, from the pure holy God,
which is one of these witnesses in the earth.

The third witness is his blood, with which the hearts of people are sprinkled,
and their consciences are sprinkled with the blood of Jesus.
As Moses sprinkled the outside of the posts, etc. with the blood of bulls and goats;
which blood of bulls and goats, Christ`'s blood ends,
which sprinkles the heart and conscience of people.
So this blood of Jesus Christ, the heavenly man,
is felt in the hearts and consciences of people; by which blood they are sanctified,
they are cleansed from all their dead works, to serve the living God,
and to serve their dead works no longer.
So by this blood they are cleansed from all sin.
They that walk in the light, and believe in the light, they are children of the light,
and children of the day; and the blood of Jesus Christ, the son of God,
cleanseth them from all sin; and their garments are made white in the blood of the Lamb;
by which they come to testify of Jesus, they overcome the beast, the whore,
the false church.
And so every true believer, believes as Christ hath taught them, to believe in the light,
that so they may become children of the light.
They have these three witnesses that bear witness in the earth,
to bear witness in themselves; and they can set to their seal,
that God is true in all his works, in prophets and apostles, and his son;
and they shall come to know, and do come to know, the three that bear record in heaven,
and the three that bear record in the earth.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 266.

And all ye believers in the heavenly light, as Christ hath taught,
you seek that which is lost and driven away; but the false prophets, false ministers,
and teachers, they did not seek that which was lost, and driven away from God;
they put no difference between the precious and the vile, but mash all together,
like the priests and prophets of our times.
Therefore, seek that which was lost and driven away.
Some may be driven away by the storms,
some may be driven away by the great winds of the wicked, and storms of the ungodly;
some may be driven away by tempests and foul weather,
and some may be lost in the foul weather, and lost in the sea of the world;
for it is this wicked one that raiseth all this foul weather and these storms.
Therefore seek that which is lost, ye that believe in the light, by which you see,
then you are distinguished from the false prophets and teachers,
and by the light you put a difference between the precious and the vile;
for Jacob was found in a desert land, and you see all the prophets,
how they sought that which was lost, and the apostles,
and how Christ encouraged to seek that which was lost.
And when the lost sheep was found, what joy there was, more than of the ninety and nine.
And who are they that make the land desolate, but the rough Esaus, and wild Ishmaels,
and Cores?
And who makes the world as a wilderness but the devil?
and who brings the whole world to lie in wickedness, but the devil, that wicked one?
And if you should not find that which is lost and driven away, at the first, nor second,
nor third time of seeking, if you should not find him that is lost, go again,
that you may have your joy, and rejoice others; for Christ in the parable saith,
"`the prodigal son was lost, yea, was dead,
and is alive again;`" when he had been feeding among swine, and upon husks,
and could never fill his belly.
When any such come back again, they will tell you how hungry they were,
they could never fill their bellies among the husks, while they went astray,
and tell you long declarations of the citizen that they were joined to:
and therefore when the lost is found, and brought back again to the Father`'s house,
where there is bread enough, there is joy, and the heavenly instruments of music,
and the heavenly feast of the heavenly fat things,
and the heavenly robes of righteousness are enjoyed.

And so all be diligent, ye believers in the light, as Christ hath taught you;
look up and down, in the light you will see where the lost sheep are,
and such as have been driven away, you will spy them out, out of the woods, or brambles,
or pits, where there is no water, where they are ready to be famished,
where they are tied with thorns and briars; and so with the light you will see,
and put a difference between the precious and the vile.
"`For whatsoever makes manifest is light;`" for by that you see,
and you will see with it, how the false prophets, and ministers,
and teachers drive people away; they drive them away from God, and his way, from Christ,
and the covenant of light.
How angry they are with them that believe in it!
With their clubs, how have they beaten many, and wounded many, and imprisoned many,
because they would not be driven by them into the devil`'s pit-fold, or prison!
But do you never give over seeking, for the light shines over all, which believe in,
and walk in the path of the just, which is as a shining light;
for it hath been the work of all the false teachers and ministers to drive away from God,
and his truth, and light, and those have been the devil`'s servants,
and the wages he gives them is death.
This hath been the way of all true ministers, "`to seek that which was lost,
and that which was driven away;`" as you may see Christ and the apostles,
and all the true prophets did, and to bring them to feed in the pastures of life,
and gently to lead them, whose wages is life;
and he gives them their heavenly penny of life eternal.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 267.

[.blurb]
==== To ministering Friends.

[.salutation]
Friends,

All ye that believe in the light, as Christ hath commanded,
that are become children of the light, and of the day, and of the promise,
and do minister therein, do not judge one another in public meetings,
you that do minister, as you have received the grace,
and have the word of the Lord God committed to you, that minister abroad,
or go abroad in cities, towns, countries, or nations, do not judge one another,
nor reflect one upon another in public meetings; for that hurts the hearers,
and you do more hurt than you do good, and that makes confusion.
If you have any thing to say, have patience, let that gift be exercised,
and speak to one another by yourselves alone;
for that was the way before any thing was spoken against any of the church,
and that will show the spirit of order and government, and the spirit of love,
and of patience and humility.
And keep down passion, and that part in yourselves that cannot bear all things,
nor endure all things, whereby the love comes up that will endure all things,
and bear all things, which edifies the body, and by which the body is edified;
for "`the spirit of the prophets is subject to the prophets.`"
This shows the true spirit, for that which cannot bear all things, many times,
is forward in judging, that cannot bear all things, nor endure all things,
and so goeth out of the true love and edification;
which breeds confusion and distraction, and destroys more than ever it will beget to God.
And also goes out of the church order,
"`first speak to him alone;`" for by that he may win his brother.
Speaking publicly makes strife, some owning and some disowning,
and that spirit must be shut out by the true spirit, that keeps order, and unity,
and fellowship, and the true love which edifies the body.
And so all who feel the power stirring in them to minister, when they have done,
let them live in the power, and in the truth, and in the grace,
that keeps in the seasoned words, and that keeps in a stablished and seasoned life:
and so all may minister as they have received the grace;
so every one is a steward of the grace of God,
if he do not turn the grace of God into wantonness; and so to minister in that love,
and grace, and power, that keeps all things in subjection and order,
and in unity in the life and in the power, and light,
by which you may see that of God in every man,
and answer to that which God hath showed unto people:
for the true labourers in the vineyard do answer that of God,
the true ministers bring people to that which is to instruct them, viz,
the spirit of God, and so are ministers of the spirit, and ministers of the grace;
they answer the spirit, and the grace, and truth in all,
in which all that do minister have unity,
and through which they have fellowship with God and Christ.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 268.

[.blurb]
==== Not to be over thoughtful of the things of this world.

[.salutation]
Friends,

Did not God provide for man and woman before he made them?
Did he not make all things in six days?
And the sixth day he made man in the image of God, in righteousness and holiness.
And therefore Christ, who is the son of God,
who comes to restore man up again into the image of God,
and leads man up into his image in righteousness and holiness,
as he was in before he fell: doth he not reprove such as take thought,
and told them of their little faith,
and that they could not add one cubit to the stature that God had made;
and it was the practice of the heathens and of the Gentiles to take thought?
So it is clear, before God made man, he took care for him;
but after man was fallen from the image of God, and his righteousness,
he took care and toiled,
though he cannot add one cubit to his stature in the Lord`'s work.
For thou mayst sow thy seed in the ground or garden, thou mayst have much cattle,
and other things, but yet there is no increase but by the Lord, neither of thy seed,
nor of thy cattle; for is not the earth the Lord`'s and the fulness thereof?
Mark! and doth he not give the increase, who upholds all things by his word and power,
who is the Creator of all, and provided for man before he made him,
and set him in dominion over all the works of his hands; which dominion man lost.
Man lost righteousness and holiness, in his disobeying the command of God,
which Christ comes to restore man to, and sets man above all again,
as he was in the beginning, and up to his own state beyond Adam before he fell,
to him that never fell.
And so all that believe in the light, as Christ commanded,
in the light they see they cannot add one cubit to the stature,
and so they come to grow in the faith, in Christ and in God.
And so herein hath the Lord the praise of his works; and all things praise him,
who hath created them all to his honour, and to his glory, and to his praise;
and man to glorify him in righteousness and holiness,
in the image of God and of Christ Jesus,
above all other creatures in the covenant of God,
in the covenant of light and life in Christ Jesus, him by whom the world was made;
by him they praise and please God, and in their pleasing God,
they honour God and Christ.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 269.

[.blurb]
==== Concerning the single language.

All Friends that do believe in the light, as Christ hath commanded you,
and are become children of light, keep to the proper speech; that is,
thee and thou to a singular, and you to many; as you may see throughout the scriptures,
it was the language of God and Christ, his prophets and apostles, and all good men;
though it is the practice of the first birth, and of the flesh, to say you,
when they should say thou.
Therefore take you heed of flattery to please men,
and of letting the world`'s spirit over you.
Though they have learned in their grammar and accidence, and other teaching books,
the plural and singular language, yet they speak plural when they should speak singular,
to one.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 270.

All that are gathered in the name of Jesus,
and are made alive by him and quickened by him, come to the flock of Christ;
and know where they feed at noon-day, they are gathered into the name of Jesus Christ,
whose name is above every name;
and know that there is no salvation under the whole heaven, but in the name of Jesus,
in the testimony that they have of Jesus, which is the spirit, by which they see Jesus,
and see his pastures of life, see his springs of life, and his rivers of life,
and his bread of life; and see the footsteps of the flock, the testimony of Jesus,
the spirit, by which they see him and his flock;
and they see the barren mountains they have been upon and come off from.
And therefore all you that be gathered into the name of Jesus,
and walk in the path of the just, where the footsteps of the flock are,
quench not the spirit in any, and if any will not have of your bread of life,
and water of life, let them fast, that will neither receive, nor give;
for the bread of life and water of life, are not only given to feed yourselves,
but by them you may feed others, and refresh others: therefore have bread in your houses,
and water in your own well, and fruit of your own tree, and salt in yourselves,
to savour withal, that you may try all things; and have oil in your own lamps,
that they may burn in your own temple; and odour and frankincense,
that it may burn continually upon your own altar, that it may ascend as a sweet savour,
holy and pure, up to God who is holy and pure.
Be not removed off your ground, wherein you may grow and increase.
And so quench not the spirit, despise not prophecy, hate not the light,
but improve your talent; hide it not but improve it.
Mind the kingdom within, and the heavenly penny, and the spirit of God,
which is given to instruct you; and walk according to the rule of the spirit of God,
that he hath given to you to profit withal; and mind the truth in the inward parts;
so that you may be adorned and arrayed with a meek and a quiet spirit.
For the light that shines in your hearts will give you the
knowledge of the glory of God in the face of Jesus Christ,
that you may know the heavenly treasure in your earthly vessels,
and the day star to arise, the day to dawn in your own hearts,
that you may become temples of Christ; he to dwell with you, and walk with you,
and sup with you; and the blood of Christ to sprinkle your hearts from dead works,
and your consciences also, that you may serve the living God.

So know the true faith to purify your hearts, which Christ is the author and finisher of;
and the true hope, to purify you.
And so, be true believers in the light, as Christ commands,
and become children of the light; for he that believes, hath the witness in himself.
And know the true word in your hearts and mouths;
which is the word of faith the apostle preached,
which distinguishes your good thoughts from bad, and your good words from bad;
which word is in your hearts to obey and do.
Which is as a hammer to hammer down sin and evil, and as a sword to cut it down,
and as a fire to burn it up.
So that by that word you may be sanctified, by that word you may have salvation,
by that word you may be reconciled to God; by which all things are upheld,
by his word and power; by this word you may be born again of the immortal seed,
that lives and abides forever.
And so from this word you may have your milk; for this is the ingrafted word,
that is able to save the soul, and raise the soul, that is immortal,
up unto the immortal God.
And by this word you will see over all the deceivers of your souls;
which word was before they were.
And by this word you will understand the scriptures of truth, that cannot be broken.
And by this word you will come to judge all those that are
got into the imaginations concerning the scriptures,
and that set them up in the room of God and Christ, in their dark imaginations,
who in their darkness cannot comprehend the light.
And by this word you will have riches; out of this word is poverty.
And by this word you will come to know life and salvation;
for in the beginning was the word, and the word was with God;
and Christ`'s name is called the word of God;
and the scriptures are the words which are to be fulfilled.
So all be diligent in the truth, that you may be fruitful in the word of God,
that it may have its passage through you all.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 271.

[.blurb]
==== Concerning those that go out of unity and deny forms.

Those that are gone from the light, from the spirit and power of God,
and so from the unity, by the light, and by the spirit, and by the power are judged;
and the power, and light, and spirit are over them.
And they being gone into their own wills, and into a perverse spirit, then they say,
they will not be subject to men`'s will, nor to the will of man;
and that spirit leads them out of the bonds of humanity.
When they are thus gone from the light, and the power and spirit of God,
they go out of all true forms, into confusion and emptiness, without form; then they say,
they will not be subject to forms,
and cry down all forms with their darkness and a perverse spirit,
and so mash all together.

For there is a form of godliness, and there is a form of sound words; many have a form.
All creatures have a form, the earth hath form,
and all things were brought into a form by the power
of God for the earth was once without form,
and was void, and empty and confused.

So they that be gone out of the covenant of God and life, and out of the power of God,
are gone into a confused condition without form,
a state which is out of the bond of civil men and women.
And so such are confused without the right form; for the form that God hath made,
viz. the form of the earth, the form of the creatures, the form of men and women,
the form of sound words, the form of godliness, nor the form of sound doctrine,
was never denied by the men and women of God.
But such as got the form only, and denied the power of godliness, those were denied,
for they deny the power; and do not only so, but quench the spirit,
and grieve and vex it, and hate the light; by which light they are condemned.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 272.

[.blurb]
==== To Friends in Ireland.

Keep to the equal measure and just weight in all things, both inwardly and outwardly,
that you may answer equity, answer truth in the oppressed, and the spirit, and grace,
and light in all people.
And so, being kept in righteousness, and equity, and truth, and holiness,
that preserves you over the inequality, injustice, and the false measure, and weight,
and balance in all things, both inward and outward.
And this keeps your eye open, keeps you in a feeling sense, keeps you in understanding,
and true wisdom, and true knowledge, what you are to answer to all men in righteousness,
and truth, and equity, both inward and outward.
And this is to all you that have purchased or bought any Irish land,
so that justice and righteousness, and the true measure, and true weight,
and even balance may be among you, to answer that which is true, and just, and even,
and equal; that you may answer that which is equal, and just, and true in yourselves,
and in every man and woman; that you may be preserved in the sense and favour of God,
and so may answer the good and righteous principle in all,
by which they may be brought to truth, the equal principle, and just measure,
and true weight and balance;
by which they may know the just and true God in all his works and out-goings.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 273.

[.blurb]
==== Not to trust in uncertain riches.

All Friends, be ye as strangers to all things visible and created,
but be acquainted with the Creator, your maker, the Lord God Almighty;
for outward things are not durable riches, nor durable substance,
nor durable habitations, nor durable possessions, for they have wings and will fly away;
and so therefore be as pilgrims and strangers to the world, and all worldly,
created and visible things, and witness redemption from the earth,
that you may reign upon the earth, as kings and priests to God,
that you may know a habitation in God, and the riches of his grace and life,
that is everlasting, and a substance that fadeth not away,
the riches which hath not wings, and the riches that is not deceitful,
that is durable and true.
For men trusting in outward riches, and outward things, they will deceive and fail them,
and have wings and flee away from them.
And so man in that state is deceived, and riches are deceitful to him.
Therefore, as I said before, be as strangers and pilgrims to the world,
and all things therein, possess, as though you did not possess them, and what you enjoy,
as though you did not; be above all such things,
and loose to them in the invisible life and power, which is over all things;
for the birth that is born again of the immortal seed by the word of God,
that lives and abides, and endures forever, and is above all things;
for all things are upheld by his word and power.
And so be acquainted with the heavenly and certain riches, the durable substance,
and the everlasting possession and inheritance of life,
through which you may be acquainted with your maker and creator, the Lord God Almighty.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 274.

My dear friends,

In the pure and undefiled life all live, in the holy seed that changes not,
that will wear out all in the transgression, and was before transgression was,
(and this seed was never a transgressor,) and it will be when transgression is gone,
and is over that spirit which is in transgression,
and is a burdensome stone to the transgressor, and him that is out of truth,
and it will outlast all.
And so in that live, in which ye may reign in the life and truth,
and in its time it will break all their bonds.
For that spirit that doth transgress, doth persecute in the particular the just,
and persecution makes the just to suffer in the general; and so,
they that will live godly in Christ Jesus must suffer persecution
by them that persecute those that are godly;
it is no wonder for them to persecute the godly in Christ the heavenly man:
so the just suffereth, within and without, by the unjust.
And so be valiant for the Lord`'s truth upon the earth, and dwell in love,
and in humility, and meekness, and patience, and righteousness,
in which the love of the Lord is manifested.
So no more but my love.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 275.

All Friends everywhere, in the living spirit, and living power,
and in the heavenly light dwell, and quench not the motions of it in yourselves,
nor the movings of it in others; though many have run out,
and gone beyond their measures,
yet many more have quenched the measure of the spirit of God,
and after became dead and dull, and questioned through a false fear;
and so there hath been hurt both ways.
And therefore be obedient to the power of the Lord, and his spirit,
and his spiritual weapons;
war with that Philistine that would stop up your wells and springs.
Jacob`'s well was in the mountain, (read that within,) he was the second birth.
And the belief in the power keeps the spring open.
And none to despise prophecy, neither to quench the spirit;
so that all may be kept open to the spring, that every one`'s cup may run over.
For you may all prophesy one by one,
and the spirit of the prophets is subject to the prophets.
"`Would all the Lord`'s people were prophets,`" said Moses in his time,
when some found fault; but the last time is the christian`'s time,
who enjoys the substance, Christ Jesus; and his church is called a royal priesthood,
offering up spiritual sacrifices; and his church are his believers in his light.
And so in the light every one should have something to offer;
and to offer an offering in righteousness to the living God, else they are not priests;
and such as quench the spirit cannot offer, but become dull.
"`I will pour out of my spirit upon all flesh, in the last time,`" saith the Lord,
which is the true christian`'s time, God`'s sons and daughters shall prophesy,
and your young men shall see visions, and old men shall dream dreams;
"`and on my servants and handmaids I will pour out of my spirit in those days,
and they shall prophesy.`"
Now friends, if this be fulfilled, servants, handmaids, sons, daughters, old men,
young men, every one to feel the spirit of God, by which you may see the things of God,
and declare them to his praise; for with the heart man doth believe,
and with the mouth confession is made unto salvation; first, he has it in his heart,
before it comes out of his mouth; and this is beyond that brain-beaten-heady stuff,
which man has long studied, about the saints`' words,
which the holy men of God spake forth as they were moved by the holy ghost:
so the holy ghost moved them, before they came forth and spake them.
And therefore, as I said before, do not resist the holy ghost, for they that did so,
grew stiff-necked, and their hearts were uncircumcised; but feel this holy ghost,
this spirit of truth, that leads you into all truth.
So with the holy ghost, and with the light and power of God,
do you build upon Christ the foundation, and life; and by the same heavenly light,
and power, and spirit, do you labour in the vineyard,
and do you minister and speak forth the things of God, and do you dig for your pearls;
therefore bring them forth, and let them be seen how they glister the glistering pearls.
And all come into the vineyard of God to labour,
in the light which was before darkness was,
and with the life which was before death and his power was;
and in the truth and power of God, which the devil is out of,
that every one of you may have your penny, that precious penny,
and heavenly treasure from God Almighty, the great Lord, who is the orderer,
and disposer, and governor, and ruler in the vineyard, among his servants,
who pays them their wages, and gives them their heavenly penny of life.
Mark, it is the labourers in the life, truth, and power of God,
that labours in God`'s vineyard, that have their heavenly penny,
that everlasting treasure.
So see that you have it; if you be in the labour of life, you will have it.
Friends, you see how men and women can speak enough for the world, for merchandise,
for husbandry, the ploughman for his plough; but when they should come to speak for God,
they quench the spirit, and say, and do not obey God`'s will.
But come, let us see what the wise merchants can say;
have they found the pearl and field, and purchased the field,
which yields those glorious glistering pearls?
Let us see what can you say for God, and that heavenly merchandise.
What can the ploughman say for God with his spiritual plough?
Is the fallow ground ploughed up?
Has he abundance of the heavenly seed of life?
So what can the heavenly husbandman say, has he abundance of spiritual fruit in store?
What can the thresher say, has he gotten the wheat out of the sheaf, the heavenly wheat,
with his heavenly flail?
and let us see, what can the spiritual ploughman, husbandman and thresher say for God?
And how they have laboured in the vineyard, that they may have their penny,
some are breakers of clods in the vineyard, some are weeders,
some are cutting off the brambles and bushes, and fitting the ground,
and cutting up the roots with the heavenly axe for the seed, some are harrowing in,
some are gathering and laying up the riches; so you may see, here are merchants,
ploughmen, harrowers, weeders, reapers, threshers in God`'s vineyard,
yet none are to find fault one with another, but every one labouring in their places,
praising the Lord, looking to him for their wages,
their heavenly penny of life from the Lord of life.
So none are to quench the spirit, nor to despise prophecy, lest ye limit the Holy One;
and every one is to minister as he hath received the grace,
which hath appeared to all men, which brings salvation; so that the Lord`'s grace,
his light, and truth, and spirit and power may have the passage,
and the rule in all men and women, that by it he may have the glory, and from it in all,
who is blessed forever and forever.
The Lord hath said, "`From the rising of the sun to the going down of the same,
my name shall be great among the Gentiles.`"
Now mark, friends, this is a large space, wherein God`'s name shall be great;
and the Lord further saith, "`In every place, incense shall be offered unto my name,
and a pure offering; for my name shall be great among the heathen,
saith the Lord of hosts.`"
Now mark, friends, this heavenly incense, and pure offering, is a spiritual offering,
which is to be offered by the spirit to God, who is a spirit;
then here none quench the spirit of God in their own hearts,
and all such come under the title of the royal priesthood,
offering up spiritual sacrifices;
which royal priesthood has a priest that lives forever, Christ Jesus.

And, friends, do not quench the spirit, nor abuse the power;
when it moves and stirs in you, be obedient, but do not go beyond, nor do not add to it,
nor take from it; for if you do you are reproved, either for going beyond,
or taking from it.
And when any have spoken forth the things of the Lord, by his power and spirit,
let them keep in the power and spirit, and that keeps them in the humility,
that when they have spoken forth the things of God, they are neither higher nor lower,
but still keep in the power, before and after;
and being obedient to the spirit and power of God, it keeps them from deadness,
and alive to God, and keeps them in a sense, that they do not go beyond, and run out,
as some (you know) have done;
and all that hath come for want of living in the power of God, and in his spirit,
which keeps all things in subjection and in order, and in the true fear of the Lord,
always to feel the presence of the Lord with you.

Come, fishermen, what have you caught with your nets?
What can you say for God?
Your brethren, Peter and John, fishermen, could say much for God.
Read in the Acts and you may see it; I would not have you degenerate from their spirit.

Shepherds and herdsmen, where are you?
What can you say now for God, whose abiding is much in the fields?
David, Jacob, and Amos, your fellow shepherds and herdsmen,
(do not you see?) they could say much for God; I would have you to be like them,
and not to degenerate from their spirit.

Come, tradesmen, tent-makers, physicians, and custom-men, what can you say for God?
Do not you read that your fellow tradesmen in ages past could say much for God?
Do not degenerate from their spirit.
Do not you remember the accusations of the wise and learned Grecians,
when the apostles preached Christ among them,
that they were called poor tradesmen and fishermen?
Therefore be faithful.
The preachers of Jesus Christ now are the same to the wise of the world as then.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 276.

[.salutation]
Dear friends,

Live in peace, and love, and patience with one another, for that doth edify the body,
and strife doth not, but doth eat out the good; for the body doth edify itself in love;
in which there is nourishment, and virtue, and life from the head;
so in that meet and build up one another.
Dear hearts be faithful, and live in the life, and power, and seed of God,
and in love and peace one with another.
And so the God of peace in it preserve you.
Peace be among you, and live in that which keeps peace; for the peace-makers are blessed.
And all strive for that which makes for peace; and they that are lowest, and so keep,
receive the most from God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 277.

My dear friends,

When you were formerly in a profession, you took your servants, your apprentices,
your children along with you to your places of worship.
And now, that you are come to truth, and are convinced that the same is the truth of God,
through which you come to have a portion and inheritance of life and salvation,
and of a kingdom and world which hath no end,
and into a possession of that which formerly you did profess in words.
Now, therefore, friends, you that are come to this possession,
and go into the assemblies of the people of God, that are gathered into his name,
(where salvation is,) and in no other name under heaven, but in the name of Jesus Christ.
Is it not more reputable for you to take your servants, apprentices, children,
and maidens along with you to the meetings, to be partakers of the eternal truth,
that they may have a possession with you of the same that you do possess?
For, if you should leave them behind, and be careless of them,
they are many of them apt to run into liberty, and to looseness, and to plays,
and to tippling-houses, and so into loose company.
Such liberty hath been a great hurt to youth,
and the truth hath been much dishonoured thereby.
And such do not only lose the wisdom of God,
and the true understanding given to them by his son, but the reason of men,
in these practices.
And then after you may come to find fault with your servants, children,
etc. and for a small matter put some of them away, when the fault is in yourselves,
that you did not take them along with you to the meetings,
and govern them in the wisdom of God, and true understanding and knowledge;
which is to know the true God, and his son Jesus Christ, whom he hath sent;
whom to know is life eternal.
By which liberty such do not keep authority over them;
for you should bring them to the meetings with you, to wait upon the Lord.
For truly my life hath been often burdened through the
want of restraining them of that liberty they run into;
wherein you should be more prudent, wise, and careful,
and should keep more in your dominion and authority in the life, power, and seed,
in which you have the true wisdom, knowledge, and understanding.
Therefore, consider of these things in all your families,
and remember the time of your former professions,
wherein you exercised the reason of men, as to bring your servants,
etc. to an outward profession.
Now you being come to a possession of life, take heed lest you lose the right reason,
wisdom, understanding, and knowledge.
Therefore rouse up yourselves,
that you may exercise the right wisdom and understanding in that which lives forever,
and is and will remain when all the contrary is gone; into which all must be brought;
that in that you may be good patterns and examples in all your families,
and bring them forth with you to your meetings,
that they may find the substance of that which you did formerly profess in words.
And now you enjoying the substance, be more careful, be more diligent and circumspect,
that God may be glorified throughout all your families, and his name may be called upon,
and honoured, and exalted, who is God over all, blessed forever.

And, friends,
some among you breed up your children not as when you were in a profession only,
in such a rude, heady way, that when they grow up, they do not matter you,
nor care for you; so they are not a blessing and a comfort to you;
but in many things they are worse than many of the world`'s, more loose, stubborn,
and disobedient; which truth teaches no such things, but brings more into humility,
and meekness, and gentleness, and tenderness;
so that when they come to be set to prentice,
many times they run quite out into the world.
And therefore, by the power, and life, and wisdom of God,
these things you must take notice of, that all such may be brought into,
and kept in subjection by the power of God, that God may be honoured and glorified,
through the breaking of the stubborn will in them, and subjecting them to truth;
and let them all know their places, and not to give way to that which may get over you;
so then you will not know how to rule them at last, but bring a grief, and sorrow,
and trouble upon you, as too many examples may be seen.
Therefore, while they are young, restrain them from such things,
and every one in the life, and power, and seed of truth, keep your authority,
and lose not the true wisdom and understanding given you by Christ,
nor the true knowledge, nor true reason, which gives to distinguish good from bad;
but in all things keep your authority, which is given to you of God,
and your places in it; for they that fear and worship the Lord,
shall have a place with him.
And in the power, and life, and wisdom of God,
you will breed up and govern your sons and daughters, servants and prentices,
and cause them to keep in their places,
and in the power of God answer the good in them all.
For an outward father or mother, over their families, apprentices, and maidens,
are to keep all things that are outward, civil, and subject, in their places,
with reason and true wisdom: and such as come to be fathers in truth,
are to train them up in the truth, and to exercise that wisdom,
and that knowledge and understanding, which is beyond the outward.
Therefore in it they should train them up in the truth, through which all should be free;
not in the eye-service of men, but serving the Lord in righteousness and diligence,
in their services: that they may be partakers of the heavenly life,
and come to be heirs of salvation, and children of the promise,
and sons and daughters of Zion, to whom Christ is elect and precious,
and through him their conversations may be brought up into heavenly things,
and their minds and affections to be set on things above.
So friends, all these things consider of in the life which was before death was,
in the truth which the devil is out of, in the wisdom of God, which is pure from above,
and in the righteousness, which was before unrighteousness was,
that God may be glorified throughout all your families, who is blessed forever.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 278.

And friends,
see that all apprentices that are bound amongst you may serve out their times faithfully,
according to covenant, that all may know their places; for youth, if they be let loose,
are like wild asses, and wild heifers;
and such many times bring a great dishonour to God, by running into looseness;
which are more fit to be under rule and order, than to rule;
and through a foolish pity of some,
they let up a great deal of airiness and wildness in them:
all which should be kept under by the power of God,
wherein the honour of the Lord may be preserved; and so,
that liberty may not be given to youth in those cases;
for the true liberty is in Christ Jesus,
which gives authority over that which will dishonour God;
for many such things have spoiled several, in letting unbridled youth at liberty,
in taking the reins to themselves, and brought trouble upon their parents, masters,
and mistresses, and great dishonour upon God.
Let care be taken, that truth suffer not about such things,
and that none buy out their time without the consent of their parents or guardians; or,
in the want of them, to advise with the Monthly Meetings.
For do you not see what hurt hath been done in such cases?
Wherefore keep all such under the yoke;
and hinder and stop wickedness and looseness that would break forth.
So in all such things you should exercise the pure wisdom of God, the pure reason,
knowledge, and understanding; and in the authority of it keep,
that none under a profession of truth be let into looseness;
whereas youth should be kept under a bridle and restraint,
and be nurtured and trained up in the fear and wisdom of God,
that the power of God and God`'s truth may have its passage through all, and over all;
and all lightness, frothiness, wildness, and looseness, may be kept down:
so that the good may be kept up in all, to honour and to glorify the Lord God Almighty,
who is blessed forevermore, who reigns among us.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 279.

[.blurb]
==== The substance of a General Epistle.

All Friends everywhere, who are friends of Christ the heavenly man,
by whom the world was made, and are become friends of God through Christ Jesus,
who are quickened by Jesus, and made alive by him, who were dead in old Adam,
and are now made alive by the second Adam, and have drunk his blood,
through which you have life,
and by which you come from among the congregations of the dead,
who only talk of his blood and his flesh.

And now being gathered in the name of Jesus, who hath made you alive,
in the name of him whose blood you have drunk, yea, even of the heavenly man`'s,
which is his life; and so are come out of your native countries, religions, and worships,
and left the old stuff behind, who are gotten atop of the old house,
and will not go down again to fetch out any of the old stuff.
I say, ye that are gathered in the name of Jesus, the heavenly man, out of the old Adam,
and are made alive by the heavenly man, keep your meetings in the name of Jesus.

Then it is he that is persecuted, if you be persecuted; and he that suffers;
for in all your afflictions and sufferings he is with you, who are made alive by him,
and have drunk his blood, and so are come to be faithful witnesses of Christ Jesus,
as all that are made alive by him are, and have drunk his blood;
for they that have not drunk his blood, and are not made alive by him,
are no true witnesses of Christ Jesus.
And therefore you that the Lord hath gathered, and sought and searched out,
who have been scattered in this cloudy dark day,
(since the apostles`' days of light,) and have been
made a prey upon by the hireling shepherds,
and have been left to the wolves by the flying of the hirelings,
whom you thought had been true men, and now the Lord hath sought and searched, and found,
and gathered you from their mouths, to whose mouths you have been a prey;
and the Lord is known to feed you atop of the mountains with his heavenly bread,
and he hath set one shepherd over you, (the heavenly man) who lives forever,
who is the shepherd over all the living, that are made alive by him;
and so the Lord hath the glory of seeking and of gathering you out of the wildernesses,
pits, graves, and ditches of old Adam and the serpent, and from his brambles and briars;
and so Christ, by whom the world was made,
is the rest of the living that he hath made alive, and is their shepherd,
to feed them with life, and with the springs of life, and is the bishop of their souls,
that doth oversee them, that they do not go out of the pastures of life,
and from the springs of life, nor from the fold of life.
It is a glorious pasture, to be fed atop of all the mountains, in the life,
in the pastures of life, by the living shepherd, and to be overseen by the living bishop,
and to be sanctified, and to be presented to God by the living priest,
and to be counselled by the living counsellor to an everlasting inheritance,
and to a kingdom, and to a world, that hath no end, by an everlasting priest,
that sanctifies and offers you to God without spot or wrinkle, a perfect offering,
who sprinkles your consciences and hearts with his blood,
that you may serve the living God, and not the dead works among the dead.

And now you having an everlasting preacher, whom God hath anointed to preach,
and an everlasting minister, that ministers grace, and life, and salvation,
and truth to you; an everlasting prophet that God hath raised up, who is to be heard;
all the living hear him, but the dead talk but of his fame.
So none can silence or stop the mouth of them whom he opens, or take away your shepherd,
your bishop, your minister, your preacher, your prophet, your counsellor, etc.
And therefore let him have your ears, hearken to him, let him be set up in your hearts,
who was set up from everlasting to everlasting by the Father,
whom all the righteous witness, Christ Jesus, who is your possession,
being heirs with him, by whom all the living are made alive;
and so in him live by whom the world was made,
who was glorified with the Father before the world began.
So in Christ the heavenly man, you have rest,
but in old Adam (the transgressor) you have no rest; there is the wilderness, Sodom,
Egypt, Babylon, and confusion.
For God blessed Abraham in his obeying of his commands,
when he went from his native country, and relations; yea, and made him a prince.
So they that are redeemed out of kindreds and tongues, Christ makes as princes,
to overcome the prince of darkness.

And Abraham was to walk before God, who was perfect, and he was to be perfect;
so must all who are of the faith of Abraham.
Abraham saw Christ`'s day, and did rejoice;
but thousands now come to enjoy the day that Abraham saw.

The outward Jews did eat of the manna in the wilderness, and disobeyed and perished;
but they that eat of the flesh of Christ, and drink his blood, have life everlasting;
and this gives an eternal life, by which they come to an eternal possession,
and to the land of the living, as the outward Jews came to possess the land of Canaan.
And so you that are heirs of Christ, the heavenly man, and are come to possess him,
(whom he hath made alive,) stand fast, now is your time to stand; stand in the life,
which was before death, or the king of it was; stand in the light,
which was before darkness, or the prince of it was; and stand in the power of God,
which was before the devil was; and sit down in the heavenly places in Christ Jesus,
who was set up from everlasting to everlasting.

And therefore keep your faith in the Lord;
for he is the same who hath given you dominion, through faith,
over the mountains of opposition, by which they have been subdued,
and by which the fiery darts have been quenched.
And hath not this been fulfilled, "`in all their afflictions he was afflicted;
and that the angel of his presence should be with them in their trials and sufferings.`"
So the Lord hath a tender care of his sheep, his people,
that the angel of his presence should be with them in all their trials.
And therefore let your minds be out of all outward things, and visibles;
and fear not the fleece, for it will grow again; and if the Lord should try you now,
with the spoil of outward things, after he hath blessed you with them,
to see whether your minds be with them, or with him: therefore now stand,
having on the whole armour of God, and his righteousness,
and your feet shod with the power of God, which was before the devil was;
this will keep you from slipping; and having on the armour of light,
to stand against darkness; and the breast-plate of righteousness,
which is armour proof against the devil and his fiery darts;
and keep the shield of faith, and sword of the spirit, the word of God,
and the helmet of salvation,
that preserves the head in all battles with the devil and his instruments.

And thus with your heavenly armour and arms stand, and keep your possession of life,
who are brought out of spiritual Egypt, Sodom, and Babylon, having one to go before you,
the captain of your salvation, (Christ Jesus,) who was before Moses and Joshua were.
And see how the children of God all along in the scriptures through faith had the victory;
Daniel by faith, the three children by faith, Abraham by faith, Joshua by faith,
and Caleb by faith; and the other spies, which had no faith,
and the elders among the outward Jews and the people, how they fell through unbelief!
But by grace through faith the just were saved, by faith they had victory,
and by faith they pleased God; and therefore keep in the faith,
and you will have the water of life, and the bread of life, from above.
And stand still in the faith, for the just live by faith;
and they that had not faith to believe, they perished.
And Christ hath taught all how to believe,
who hath enlightened every one that cometh into the world, he saith,
"`Believe in the light;`" which was a blessed doctrine of the heavenly man;
for you believing in the light, you believe in that which makes manifest all things,
all fruits, all creatures, all religions, and worship;
for the light was before they all were, and will be when they are all gone.
Therefore, believe in the light, saith the heavenly man, who teacheth what to believe in;
for whatsoever is made manifest, is made manifest by the light.
So to believe in the light, that doth make manifest all things that are reproveable,
therein you will become children of the light, and children of the day, and sons of God,
and daughters of God, and sons of Zion, and daughters of Zion, the heavenly Zion,
the heavenly joy.
And so herein you come to be of the royal family, above all the families of the earth,
above all the households of the earth, a household of God, the workmanship of God,
the planting of God, the building of God, the household of faith;
which are titles higher than all the titles among men in the world, in the creation;
sons and daughters, and servants and handmaids,
every man to enjoy something in the household.
Every one to have an inheritance (of their own) of life,
that they may offer to God of their heavenly substance,
who are called a royal priesthood; that is, a kingly priesthood over the devil,
and over Adam, in a possession of a spiritual kingdom, and of a world that hath no end,
and of a heavenly durable substance and riches which are spiritual;
and so to offer up spiritual sacrifices to God, who is a spirit.

So now the time of trying is; therefore all to stand,
and see if there be any thing able to separate you from Christ,
who is from everlasting to everlasting, who is first and last, who makes an end of sin,
and finishes transgression, and destroys the devil and his works,
and is the top and corner-stone, the possession of all the righteous,
the rest and sabbath of all the righteous, that have drunk his blood,
whom he hath made alive.
So in Christ you shall bear no burden,
for he destroys that which oppresses both man and beast;
and in Christ you shall not go out to gather your meat, who is your sabbath and rest;
but in old Adam there is no rest; in the second Adam the heavenly man, there is the rest;
and in him, to wit, Christ the heavenly man, you need not go out to gather your meat.

For he is the bread of life, that comes down from above, in him stand,
and sit down in the heavenly places in Christ Jesus,
who was with the Father before the world began, who is your way to God;
which way was set up above sixteen hundred years since,
before all these got up among the Papists and Protestants,
who is the new and living way to all who are made alive by him, and drink his blood.
The dead make dead ways for the dead to walk in; but mind you Christ`'s worship,
which was set up above sixteen hundred years since, by himself, in the spirit and truth,
whereby every one comes to the truth, the spirit of God in his own heart;
in which truth and spirit he worships the God of truth,
(who is a spirit,) and feels him always present.
Now to worship God in the truth, is that which the devil and old Adam is out of;
and this is the perfect and standing worship; and people that have lost this worship,
that Christ set up,
they have set up so many false worships among Protestants and Papists,
and compelling one another to them, since they have lost the peaceable truth,
in which the God of peace is worshipped.

And therefore now all prize the standing truth, and walk as becomes the gospel,
the power of God, which was before the devil was, which destroys the devil and his works.
And so stand fast in the liberty wherewith Christ hath made you free; yea,
free from the devil and old Adam; for the freedom is in him, in Christ,
and not in the devil who is out of the truth, nor in old Adam.
Yea, Christ is able to deliver out of the six troubles, and the seventh trouble,
the perfection of trouble; he who is the perfection itself,
so he is the deliverer and mediator, and the intercessor,
that makes peace betwixt you and God.
So in Christ, (who is the deliverer,) is the peace and the rest, yea,
an everlasting rest; he was set up over all troubles, and persecutions, and persecutors,
who was before they were, glorified with the Father before the world began,
and he will be when they are all gone, as I said before, all that have drunk his blood,
and are made alive by him, have life; yea, a possession that will never have an end;
but they that are dead in old Adam, are against Christ, who is the life,
till he make them alive by believing in the light;
and then they become the congregation of the living.
And these are they that are gathered together by the Lord;
and they that are not gathered together by the Lord, but by men, to themselves,
they come to be scattered.
Now the congregation of the living, have drunk the blood of Jesus, that are alive by him,
and so are gathered together by him, the heavenly man, and he is in the midst of them,
to preserve them, and exercise his offices among them, as a shepherd, and a bishop,
and a prophet, etc.

And these are the living members, who have a living head, Christ Jesus;
and that saying comes to be fulfilled, "`Thy dead men shall live together,
with my dead body shall they arise;`" so come to live with Christ Jesus.
And they are the congregation of the dead, that believe not in the light,
nor drink the blood of Jesus, but death and destruction talk of him and of God,
and his prophets`' and apostles`' words; and they come to set their house upon the sand,
and so are the fools; and then a storm arises upon the sea,
and their house is presently in the sea again, and there they are drowned;
the house sits so nigh the sea, that in a little storm they are drowned,
they are so nigh the world.
But the wise men set their house upon the rock, and the rock is Christ, the life,
who was before the world was, and will stand over all; and they that are built upon it,
the storms and tempests cannot move their rock, nor their house.
So here is the wisdom of the wise,
who build their house upon him by whom all things were created, who is the rock of ages.
So in all storms they keep to their house, and they meet in him, and are gathered in him,
and he is their head and counsellor, to order them; and in him they all please God;
and in Christ Jesus are one another`'s crown and life;
and so through him they have all a crown of life,
who was with the Father before the world began.
So in him sit down, over all the windy doctrines,
that toss the chaff abroad in the world.

I say, in Christ sit down, in him who was before the world was,
for out of him is all wearisomeness, but in him ye have rest.

G+++.+++ F.
