== Letters 303 &#8212; 316

[.centered]
=== Letter 303.

Dear friends,

All be faithful in the eternal power of God that is over all; I say,
keep in this power of God, that you may answer that of God in all,
and not that which is contrary; for the kingdom standeth in power, and in righteousness,
and joy in the holy ghost: so that which doth not live in the power, and righteousness,
and joy in the holy ghost, cometh not into the kingdom.
So this kingdom, and power, and righteousness, and holy ghost, in which is the joy,
is over all; and this kingdom standeth not in word, but in power.
So know one another in the power, and in the spirit of God,
(who is a spirit,) know and confess Christ in his death and sufferings,
and in his resurrection.
So no more but my love in him.

G+++.+++ F.

Worcester Prison, the 21st of the 9th month, 1673.

[.centered]
=== Letter 304.

[.blurb]
==== To Friends in Virginia.

Dear friends, to whom is my love, I am glad to hear of the increase of truth amongst you,
and the Lord prosper his work, and increase people in his knowledge,
who will fulfill his promise,
"`that the knowledge of the Lord shall cover the earth as
the waters cover the sea,`" in the new covenant;
though in the old covenant, the word was to Jacob, and the statutes to Israel;
the like was not to other nations, but the new covenant is to all nations,
Jews and Gentiles; "`For I will give him for a covenant of light to the Gentiles,
and he shall be my salvation to the ends of the earth;`" therefore he saith,
"`Look unto me all ye ends of the earth,
and be ye saved:`" and there is no salvation by any other name under heaven,
but by the name of Jesus, which signifies a saviour.
And in his name keep your men`'s and women`'s, and all your other meetings,
that you may feel him in the midst of you, exercising his offices; as he is a prophet,
which God has raised up to open to you, and as he is a shepherd,
who has laid down his life for you, to feed you, so hear his voice;
and as he is a counsellor, and a commander, follow him and his counsel;
and as he is a bishop to oversee you, with his heavenly power and spirit;
and as he is a priest, who offered up himself for you,
who is made higher than the heavens,
(and that is higher than all the priests that are
made upon the earth,) who sanctifies his people,
his church, and presents them to God without blemish, spot, or wrinkle: so, I say,
know him in all his offices, exercising them amongst you, and in you.
I am glad to hear of some of your diligence,
in taking that great journey to Carolina through the woods;
for if you visit them sometimes, it would do well:
and there is a people at that place you call New Country, as you go to Carolina,
who had a great desire to see me, amongst whom I had a meeting.
I received letters,
giving me an account of the service some of you had with and amongst the Indian king,
and his council; and if you go over again to Carolina, you may inquire of captain Batts,
the old governor, with whom I left a paper to be read to the emperor,
and his thirty kings under him of the Tusrowres,
who were to come to treat for peace with the people of Carolina:
whether he did read it to them or not, remember me to major general Benett,
and colonel Dew, and the rest of the justices that were friendly and courteous to me,
when I was there, and came to meetings; and tell them,
that I cannot but remember their civility and moderation, when I was amongst them:
and so the Lord redouble into your hearts, and theirs,
the love and kindness which they and you showed unto me.
I have been a prisoner here about these eight months, and now I am premunired,
because I cannot take an oath; but the Lord`'s seed and power is over all,
blessed be his name forever, and glory and honour to him, who is over all,
and is worthy of all.

G+++.+++ F.

Read this amongst Friends in their meetings.

Worcester, 1673.

[.centered]
=== Letter 305.

My dear friends, live in the seed that bruiseth the serpent`'s head,
who is the head of all false teachers, and ways, and false worships, and religions:
but Christ is the head of all the true worshippers; and in his name keep your meetings,
in whom you have salvation, and not by any other name under heaven.
And sit under your teacher, Christ Jesus, that doth bring your salvation,
the grace of God, that you may all witness that you have a teacher, from God,
that doth bring your salvation; and in your hearts you have received him,
and believed in him, and with your mouths confession is made to salvation,
that your teacher hath brought you;
that you all may witness his salvation to be your walls and bulwarks,
that doth surround your camps and tabernacles.

G+++.+++ F.

London, 1673.

[.centered]
=== Letter 306.

[.blurb]
==== To Friends in Holland.

Friends, Do not grow barren, but in the root abiding, ye will spring upward,
and bring forth much fruit in this life, and in the life to come inherit life eternal;
and so your lives being hid with Christ in God,
you will be made conformable to his image, and know the power of his resurrection,
and the fellowship with him in his sufferings, and the fellowship with him in his death,
that you may have fellowship with him in his resurrection and life;
and as you have borne the image of the earthly,
so also you may bear the image of the heavenly.
And as your vessels have been full of wrath and dishonour,
so your vessels may be full of his mercies, and praises to God;
and as in your old earth hath dwelt unrighteousness,
so you may see and know the new earth, wherein dwelleth righteousness.
There is a belief that God is not the author of,
for such have not the witness in themselves of what they do believe;
and a belief may be of God and Christ, and of the scriptures,
and yet such may be in death, for they are not in Christ the light,
and so are not children of the light; and there is a faith,
which Christ is not the author of, and that faith giveth not the victory,
nor purifieth the heart, neither do they in it please God, nor have they access to God,
and that is the dead faith which hath no works.
And there is a hope that doth not purify, and that hope is that which is not of Christ,
who saves, and purifieth, as he is pure; but that hope is the hope of the hypocrites.
And there is a way that may be defiled, where all the wolves, dogs, and beasts,
and the unclean passeth, and hath many turning ways in it, and many crooked, and rough,
and mountainous ways in it; and there is the broad way that leadeth to destruction;
and these are not the way of Christ, that leadeth to life,
which is the narrow and strait way.
And there are many names in the world by which there is no salvation;
the beast hath many names, which all the world wondereth after,
and receive the beast`'s mark, that he marketh them with,
his beastly spirit and power which he hath from the dragon;
but there is but one name under the whole heaven by which people shall be saved,
and that is the name of Jesus; and they gathering in his name,
by whom the world was made, and receiving their Father,
the Lord God Almighty`'s name and mark in their foreheads,
Christ is in the midst of them, and they will not receive the beast`'s mark,
nor will not be marked by him.
And there are many religions in the world,
all which are spotted and defiled with the world`'s spirit,
with which they do destroy one another; but there is but one pure religion from above,
that is undefiled in the sight of God, and that keeps from the spots of the world,
and leads to visit the widow and fatherless in their distress;
and they that receive this pure religion from God,
(who is above,) it is by God`'s spirit, the fruits of which is love;
and this pure undefiled religion from God hath the
glory in all the hearts of them that do receive it,
who is the author of it; and it is above all those religions that are below,
that are made by men`'s earthly, sensual, and devilish wisdom,
who with it compel people to conform to them, and such are not gentle, pure,
nor peaceable, as the wisdom which is from above is.
And there is but one true worship, which the devil is out of, and his unclean spirit,
and he cannot get into it; which worship is in the spirit and in the truth,
which Christ the heavenly man hath set up above sixteen hundred years since.
And every one that cometh into the spirit, and into the truth,
are the true worshippers of the God of truth, who is a spirit;
and all that are not in the spirit and truth, are in the beast`'s worship,
(out of the spirit of God,) and in his wrath under the dragon`'s power.
And there are many instructers that cause people to err;
but there is but one spirit of truth, which leadeth into all truth;
and this is the one spirit that led the prophets and apostles to give forth the scriptures;
and all the instructers that are out of it,
cause people to err from the spirit that the prophets and apostles were in,
and so are in confusion.
And there is one leader, Christ Jesus, that God hath given;
and all that are not led by him, are led into the ditch, the corrupting place,
and they tell them, there is no perfection here.
And all the learned in Babel`'s confused tongues, who have the letter of the scriptures,
yet follow their own spirits, (see not,) and the divination of their own brains,
and use their tongues, such buildeth up Babylon again,
who are not in the spirit the prophets and apostles were in,
and know not the tongue of the learned, nor the scriptures of Christ, and the prophets,
and the apostles; but they are as a sealed up book to them;
and therefore they are raging and contending about the meanings of them,
teaching their people, by their example, to do the same.

G+++.+++ F.

[.centered]
=== Letter 307.

My dear friends, who feel the precious truth of God,
by which you are made God`'s free men and women, and have bought the truth,
do not sell it for dross or dung, but be valiant for the truth upon the earth,
you who have received God`'s seed into the good ground,
that in this life some bring forth fifty, sixty,
and a hundred fold of fruit from God`'s seed, to his glory,
and that have received the anointing oil in your lamps from the Holy One,
that they may burn and shine both night and day in your tabernacles,
through which you may be lighted into the bridegroom`'s chamber;
and the power of God has always been your keeper, and will be unto the day of salvation;
which power of God is over all, yea, over the power of the devil,
the waster and destroyer, who makes the world like a wilderness,
and fills it with unrighteousness, death, darkness, and cruelty.
Therefore let your faith stand in the power of God, which the kingdom stands in,
which is a cross to the world`'s power, that causes persecution;
which power of God is the gospel, which was before the devil was,
that brought death and darkness into you;
this power of God brings life and immortality to light in you,
by which power you see over him that has darkened you, and before he was.
And you that are heirs of this gospel keep the holy and heavenly order of it;
by which power of God you come to dig, and have found the pearl in your own field,
of great price; by which power of God you come to sell all, and to purchase the field,
then you have riches enough.
And have salt in yourselves, that you may savour withal;
and that your salt lose not its savour,
through which you may be kept from under the feet of men,
though they that will live godly in Christ Jesus must suffer persecution.
And it is not only given you to believe in Christ, but to suffer for his name,
whose name is above every name.
And there is no salvation by any other name under heaven, but by the name of Jesus;
whose name is a strong tower, and the righteous flee unto it, and are safe;
by whose name and power (that is over all) you have been upheld through all your tribulations,
sufferings, imprisonment, and spoiling of goods.
And Christ Jesus, and his power, is the same today as he was yesterday, and so forever.
And therefore, as I said before, let your faith stand in his power;
for Christ`'s kingdom stands not in word, but in power, and in righteousness,
and in joy in the holy ghost; whose kingdom is an everlasting kingdom,
and the riches in it are everlasting.
Blessed are all they that are heirs and possessors of this,
their minds and hearts are kept over all fading things, and the riches that have wings,
that the spoiler may spoil.
And therefore consider all the faithful before you, how they accounted all but as loss,
dross, and dung, to the excellency of the knowledge that they had in Christ Jesus;
and consider likewise the faith of the martyrs, the faith of the apostles,
and primitive christians, that kept the faith and testimony of Jesus;
their patience was seen.
And likewise consider all the prophets of God to Enoch,
how their faithfulness is made manifest; and all the rest,
how they were tried by persecutors, by prisons,
and by spoiling of their earthly goods and riches,
but never of the heavenly goods and riches;
for there the thief and spoiler could not come.
And therefore mind that noble seed, that never bowed to sin and iniquity, nor the devil,
but bruises his head, and destroys him and his works,
that ye may all be flesh of his flesh and bone of his bone,
who is your heavenly food and bread that comes down from heaven,
through whom you may eat, and live by him, as he lives by the Father;
and so by eating this heavenly bread that comes down from heaven,
you may have everlasting life.
The Lord may try you by persecution,
or spoiling your outward goods which he has given you,
by permitting the spoilers and persecutors come to try you,
that you may come forth like gold seven times tried in the fire,
(the perfection of trial,) for many are the troubles of the righteous,
but the Lord will deliver out of them all; and happy are they that are tried,
that they may come forth more pure than gold.
And let none sell their birth-right for a mess of pottage, and a piece of bread,
Esau-like.
And let none have their eyes wandering after their carrying away the fleece;
nor look back at Sodom`'s judgments; for the earth is the Lord`'s,
and the fulness thereof; and he can make the fleece grow again.
And, therefore, consider the riches of Job, and the poverty of Job,
and how his friends despised him in his poverty, and how they were reproved;
and God increased his prosperity, and lengthened his tranquillity.
And as Daniel`'s windows were opened towards outward Jerusalem,
in the time of the informers, when he prayed to his God,
as he did before in the time when they were not.
And therefore should not all your windows and doors be open towards heavenly Jerusalem,
your mother, that God may come in and help you against the false mother and her children.
And therefore keep your meetings in the time of sufferings, as you did before,
and preach the word in season, and out of season; the word, I say,
that commands the clouds and storms, and was before they were.
And therefore blessed are those eyes that see the sun of righteousness that never sets,
the sun of righteousness that changes not;
for the prophet speaks of a sun and moon that shall be turned into darkness,
before the notable day of the Lord come; and where this notable day of the Lord is seen,
and by whom it is seen, they see the glorious son of God, the son of righteousness,
by whom were all things, who is over all things, who is the head of his people,
and dwells in them, who is present with them, and who was, and will be, to all eternity;
of whose kingdom there is no end, who is God over all, blessed forever.

G+++.+++ F.

Kingston, the 1st of the 7th month, 1674.

[.centered]
=== Letter 308.

[.blurb]
==== ^
footnote:[Given forth in the time of his sickness in Worcester prison, 1674.]

My dear friends in England, and all parts of the word; the gospel,
Which is the power of God, which you have received from the beginning, keep in it,
and the fellowship of it; in which there is neither sect nor schism,
but an everlasting fellowship, and an everlasting order;
which gospel brings life and immortality to light, in every one of your hearts,
and lets you see over him, that hath darkened you.
Now every man and woman here, will have a testimony in their own hearts,
of this order and fellowship, being heirs and inheritors of it;
by which you will see over all the false orders and fellowships,
that are or may be set up or made.
Therefore it is good for every one to keep their habitation.
For those that went in Cain`'s way,
(as the apostles`' speak of,) they envied the apostles that kept the fellowship.
And Cora`'s way, and Balaam`'s way; these were them that had been great professors,
that envied the apostles.
For mark, it was the way of such as were of Cain, Cora, and Balaam`'s spirit,
to oppose the power, who were against Abel, and Moses, and the apostles;
and so there began the apostacy, and there came up the many orders,
amongst them in the apostacy.
So that at last the gospel order was lost amongst them, and the government of Christ,
and his worship; and the beast was then set up.
And therefore now the gospel order is to be set up again,
and the government of Christ Jesus, by them that be heirs of him, and of his government,
who is first and the last, the beginning and the end,
of the increase of whose government there is no end.
Now, I say, you that be heirs of Christ, possess him, and walk in him;
and as you have received him, so walk all in peace, and love,
and live in his worship in the spirit and truth, which the devil is out of.

And at your general assemblies of the ministry at London, or elsewhere, examine,
as it was at the first, whether all the ministers that go forth into the countries,
do walk as becomes the gospel.
For that you know was one end of that meeting, to prevent and take away scandal.
And to examine, whether all do keep in the government of Christ Jesus, that preach him,
and in the order of the gospel, and to exhort them that doth not.
For the foundation is already laid, which is Christ, and his government is set up;
of the increase of which there is no end.
So had all these called christians, kept in his order, and government,
they had not troubled themselves, and others, with so many disorders,
if he had been head of their church; so if you keep in the gospel order,
and government of Christ Jesus, you will keep out of the apostacy,
which they have been in, and the many false orders, and governments, that they went into,
and made one against another, when they went from the true;
as you may see in the scriptures of truth,
that it was some high Cain and Cora-like spirits that did so;
for Cain was able to build a city.
And Cora, that opposed the chief leader Moses, was of the princes of the people.
And so these opposed (with their many orders,) the true order.
And Balaam, that was able to teach a nation, and prophesy before a king,
made the children of Israel to stumble by his bad counsel.
These were men of esteem, these are they the world went after,
these came to ride upon the people; and such as these opposed Abel, Moses, and Christ,
(the leader and governor,) and his apostles, and set up the many orders, and governments,
in their churches, and broke all into sects.
And therefore, friends, if you keep under Christ, the governor,
who governs his church in righteousness, and who is a prophet, and preacher,
and keep in his gospel order; none of these can deceive you,
let them come with never so fair pretences.
For Christ bruises the serpent`'s head, who is the head of all false teachers,
and false orders, that are not in his power, and is the first and last; and therefore,
keep in his power, and in the unity of his spirit, which is the bond of peace.
Mark, the pure, holy, eternal, invisible spirit of God, is the bond of peace.
Therefore, forfeit not your bond of the Prince of princes; for if you do,
you lose your life, and go into death, and into an evil spirit,
and break the Prince of princes`' peace,
so that you lose your peace with him Christ Jesus.
And therefore it concerns all, that profess themselves to be ministers, to be humble,
else they are no learners of Christ; not to be harsh nor high-minded,
but walk as examples amongst God`'s flock, and not to be lords over God`'s inheritance;
but let him be Lord whose right it is, etc.

And you have known the manner of my life, the best part of thirty years,
since I went forth, and forsook all things; I sought not myself,
I sought you and his glory that sent me; and when I turned you to him,
that is able to save you, I left you to him: and my travels have been great,
in hungers and colds, when there were few, for the first six or seven years,
that I often lay in woods and commons in the night; that many times it was as a by-word,
that I would not come into houses, and lie in their beds.
And the prisons have been made my home a great part of my time, and in danger of my life,
and jeopardy daily.
And amongst you I have made myself of no reputation, to keep the truth up in reputation,
as you all very well know it, that be in the fear of God.
With the low, I made myself low; and with the weak and feeble, I was as one with them,
and condescended to all conditions,
for the Lord had fitted me so before he sent me forth;
and so I passed through great sufferings in my body, as you have been sensible.
And few at the first took care for the establishing men and women`'s meetings,
though they were generally owned when they understood them: but the everlasting God,
that sent me forth by his everlasting power, first to declare his everlasting gospel,
and then, after people had received the gospel, I was moved to go through the nation,
to advise them to set up the men`'s meetings, and the women`'s,
many of which were set up; and I was moved to write to other places,
for them to do the like, that kept the power.
And this was the end, that all that had received the gospel, might be possessors of it,
and of the gospel order, which is heavenly; and that all that had received Christ Jesus,
might so walk in him, and possess his government in the church,
who are members of him the heavenly head.
And so men and women being heirs of Christ, they are heirs of him, and of his government:
so that men and women may be both possessors of this government;
and men and women being heirs of this gospel, might inherit it.
Then men and women are heirs of the order of the gospel, which is from heaven,
and not by man, nor of man; which is an everlasting order,
which is from the power of God; for the gospel is called, the everlasting gospel.
So that all now in the restoration by Christ Jesus, into the image of God,
may be helps-meet in holiness and righteousness,
as Adam and Eve were in before they fell; for in the church of Christ, where he is head,
there is his gospel, and his order, and his government;
there is his power felt in every one`'s heart,
and there are these offices of admonishing, rebuking, exhorting, reproving,
amongst them that are convinced, and converted, by them that are in the power;
for there are several states.
So they that would not have people to be admonished, that go under the name of truth,
and yet go into sin and wickedness, those are out of the gospel order,
and government of Christ Jesus, and of a loose mind themselves,
and would be up themselves, and lords.
But that spirit is for judgment, for it is out of the power of God,
and out of the spirit, in which is the fellowship.

G+++.+++ F.

[.centered]
=== Letter 309.

[.salutation]
Friends,

Seek the peace of all men; which peace is in Christ,
which is a peace that the world cannot take away.
And blessed are the peacemakers, that make peace among the brethren and people;
these shall have a blessing from the Lord, the king of peace;
but woe be unto them that cause strife and offence.
And all walk in the righteousness of Christ the Lord, over your own righteousness,
and do, and act, and speak in his righteousness; then you act, and do, and speak,
and walk in that, in which you have peace, and then God will delight in you,
and you will be loved of him, for he loveth the righteous.

And let it be below any of God`'s people to raise an evil report on his people,
or any others, or to give both their ears to any one`'s report of his people or matter,
till they have heard both parties; so that righteousness, and truth, and judgment,
may be kept up, and not fall.
And in your men and women`'s meetings, you are in and about the Lord`'s business,
and not your own; and therefore let the Lord be in your eyes,
that all of you his presence, and power, and wisdom, and judgment may receive, to do,
and act, and speak in.
And this keeps all in his fear, to be careful of their words and doings,
and keeps all solid, and virtuous, and sober; and then whatsoever is of a good report,
and is decent and comely, and whatsoever is virtuous, and tends to virtue, and is lovely,
that to follow after and cherish.
And here your eyes are kept open, to see that nothing be lacking,
and that you stand in that which shall never fall, in the power, and spirit,
and seed Christ, who is the sure foundation, and the rock of ages.

G+++.+++ F.

[.centered]
=== Letter 310.

[.salutation]
Friends,

In everything give thanks to the Lord; for from him every good thing you do receive;
for the apostle saith, 1 Thess. 5:18. "`In everything give thanks:
for this is the will of God in Jesus Christ concerning
you;`" and they that do not obey this doctrine,
do not do the will of God in Christ Jesus.
And the apostle saith, "`Every creature of God is good, and nothing to be refused,
if it be received with thanksgiving,`" etc. 1 Tim. 4:4.
And David saith, "`At midnight I will rise to give thee thanks,
because of thy righteous judgments.`"
Ps. 119:62. And David saith, "`O give thanks unto the Lord, for it is good,
because his mercy endureth forever.`"
Ps. 118:1. So the Lord is worthy of all the thanks and praises, through Jesus Christ,
who created all by Jesus Christ, to his glory and honour forevermore.

G+++.+++ F.

[.centered]
=== Letter 311.

[.blurb]
==== For the men and women`'s meetings in Barbados.

[.salutation]
Dear Friends,

Let all things be done in love, and in the spirit of Christ,
which is the spirit of the lamb, that must have the victory;
for patience runneth the race, and hath the crown.
And keep down rough Esau`'s spirit,
for that will not let the Jew inward pass the king`'s highway.
And therefore quench nothing that is good; but keep in the love of God,
that is shed in your hearts, and every one keep to your own springs,
and at your own breast,
and feel your own bread in your own house (from heaven.) And strive not for mastery,
but let Christ be the master, who is the wisdom of God, and your wisdom,
and righteousness, and sanctification, and justification,
and you to dwell in humility and love, that will bear all things;
and that is not easily provoked, and envieth not: if your love is not in this love,
it is not the love of God.
Though you may be convinced of the truth;
but they are happy that do obey the truth of what they are convinced; and if they do not,
they will lose the days of their innocency and simplicity.
And know the birth that is freeborn, which can give the cheek to the smiter;
for there is a birth of the mortal seed, and there is a birth of the immortal seed,
by the word of God, that liveth and abideth forever;
which latter hath a habitation that is forever.
And take heed, friends, in laying open one another`'s weakness;
but if any one has any thing to say, let them speak to the person concerned;
and if they will not hear, take two or three more, before they are brought into public.
This is the order of the head Christ, to his body, his church.
And if any report be upon any, let them speak to the parties that are concerned;
for the report may be false: and the Lord saith,
"`Thou shalt not raise a false report upon my people.`"
So in this you will have a care one of another, for one another`'s good,
preferring one another in the truth.
And so let the true brotherly love continue, and kindness, affableness,
and courteousness, and whatsoever is decent, comely,
and of a good report in the eyes of God, and the hearts of all good men,
that follow after; and so, that in your men and women`'s meetings,
nothing may be seen of the old leaven, of the old malice, nor of the old man,
nor his deeds, nor his old image, nor his old bottle be drunk of,
nor his sour grapes eaten of; for if you do, it will set your teeth on edge,
one against another.
But mind the royal seed, Christ Jesus, that makes all things new,
that new and living way, a new man, after God and his image:
so children of the new covenant, having the new leaven,
that leavens up into the love of God, which edifies the body, of which Christ is head;
and new bottles, full of new wine from Christ the vine;
the new wine which makes all your hearts glad to God and Christ, and one in another.
So here is the new heart, the new spirit, the new life, in which the living God is served.
And therefore, this is the word of the Lord God to you all, "`Let this new way,
new covenant, new man, new leaven, new wine, new life,
show forth its fruits in the new life, from the new man.
So that the fruits of the old may not appear, and that the bond of peace,
in the unity of the spirit, may be kept amongst you.
So keep in this unity of the spirit, which is the bond of peace;
and none to break their peace, and go into the ill behaviour;
for that is out of the spirit of God and Christ, which is meek, gentle, etc.
So that the Lord God of your lives may be glorified in you all, and above all,
who is over all, God blessed forever and ever.

G+++.+++ F.

London, the 15th of the 3d month.

[.centered]
=== Letter 312.

All Friends that are in the power of God, and in his spirit;
through this spirit you pray unto God, and ask in the name of Christ Jesus,
(which all true prayers are to be in,) and the true
singing and rejoicing are to be in the spirit,
and the true preaching and ministry are to be in the spirit;
for the saints were made able ministers of the spirit, and not of the letter.

Now when a minister, in the spirit of the living God,
does minister spiritual and heavenly things, they that receive them,
receive them with joy in the assembly; now he that is a minister of the spirit,
and ministers spiritual things, if they that receive them, receive them in sincerity,
with joy and gladness, and rejoice in the receiving of them,
whilst the other is ministering them, he that is a minister of the spirit,
does not judge such; but rejoices in them that do receive them,
and praises God for the same.

And so likewise they that do sing in the spirit do reach to the spirit in others,
whereby they have a sense that it proceedeth from the spirit;
for at the hearing of the speech of the true minister,
there is joy to all that seek and thirst after righteousness;
for the preaching the gospel is the glad-tidings, the joyful news,
and is a comfort both to soul, body, and spirit,
to all that receive it in integrity and sincerity,
and they cannot but rejoice at the sound of the power, where it is received;
and they that preach in this cannot judge such as rejoice in the spirit and power,
and in their souls praise God when they hear the sound of it.

Oh! the everlasting gospel, the everlasting power of God, which is liberty,
where this is heard (the sound of it,) which is the liberty to the spirit, to the soul,
to the creature; if a creature should praise God in his soul, in his spirit,
in the very hearing of the sound of this glorious gospel, or make a joyful melody;
the minister of the spirit, who preaches the glorious gospel, cannot judge such for that,
and say it is a confused noise; for that is the minister of the letter that so judges,
who may gather up parcels of the letter, and make a song of that, or preachment of that,
to which the gospel ministry of the spirit is the savour of death unto death,
and of life unto life.

And concerning praying in the spirit; which "`spirit makes intercession to God,
with sighs and groans that cannot be uttered.`"
Now where this spirit is prayed in,
(which all true prayer is to be in,) it makes intercession through the veils,
through the clouds and thick darkness, by the invisible power, to the invisible God;
and this prayer being made in an assembly to the throne of grace,
there the assembly (in their spirits) join in this spirit, and do make intercession,
and do enter through the veils, clouds, and thick darkness to the throne of grace.
And if some of these should praise God in a joyful sound with their souls and spirits,
can he that prays in the spirit, and makes intercession therein,
judge them that groan in the spirit, and feel the intercession to the throne of grace?
No, he cannot; for he feels a unity in the spirit;
and in case that some do groan and sigh, when another is praying in the spirit,
that makes the intercession easy in the invisible spirit, to the invisible God,
and throne of his grace; which the spirit of God operating in the assembly,
makes some to sigh and groan, being sensible of their wants;
and the power has awakened such;
therefore can any judge such that pray in the power and spirit, that has awakened them?
Nay, but hears them, and is glad where it stirs; and so having the mind of the Lord,
and makes intercession to him by his spirit, who hears the sighs of the needy,
and groans of the oppressed, he cannot judge such.
And therefore they that do judge such sighers, prayers,
and such who make a joyful melody,
(from the word dwelling in their hearts,) they who judge such,
are not in the spirit that makes intercession;
and that which is contrary is to be reproved and admonished in private,
by them that are in the spirit of God, lest they pluck up the wheat and tares together,
and make a confusion in the church; for God is not the author of confusion,
but of peace and good order.
But that spirit which is high and lofty, and can form a praise by words,
and pray in his own spirit, will judge such sighing, groaning, praising, and singing,
as before; but that exalted spirit is to be cut down with the sword of the spirit.
For if any should sigh, or groan, or rejoice, or make a joyful sound,
when another is praying in the spirit of God, and ministering in the spirit,
spiritual things; this the spirit of error cannot bear, but swells,
and breaks out into confusion and disorder, which,
(as I said before,) is to be cut down with the sword of the spirit;
for he denies the effect of true prayer, and the spirit of prayer,
which makes intercession, who hath, or would have,
no feeling of the effects of true prayer; but that which is formal, and in the imitation,
that makes many to groan and sigh, who are burdened with that spirit; yea,
many tender ones.
And therefore all are to keep low before the Lord, in the humility,
in the spirit and power; out of the imagination, imitation, and self-exaltation.
And so keep in the unity of the spirit, which is the bond of peace; yea,
the bond of the Prince of princes`' peace.
Here the gospel of peace is known, and the peace of God, which passes all understanding;
which is the King of kings, and Lord of lords, and Prince of princes`' peace, who saith,
"`In me you have peace;`" and all are bound by the spirit of God to keep his peace;
and all his believers, and faithful ones, and true christians,
are bound to keep it amongst themselves,
and in all their assemblies (his church) which he is the head of.

G+++.+++ F.

Worcester Jail, the 14th of the 9th month, 1674.

[.centered]
=== Letter 313.

Friends, All that are sensible of the power of God, and have received it,
which is immortal and everlasting, live in it, and grow up in it;
for the power of God is over the power of the devil; which power of God is the gospel,
and it is called the cross of Christ.
And therefore all ye men and women, that have received the gospel, the power of God,
and come to be heirs of it, take your possessions of the same;
and in it keep your men and women`'s meetings, in your possession of the gospel,
the power of God.
Herein is the holy, heavenly, and powerful order, which is everlasting,
and will have no end; and this order of the gospel, which is the power of God,
is over all the orders in the world, and before they were, whether Jews, Gentiles,
or apostate Christians.
For the apostle saith, in Gal. 1:11-12. "`Now I certify you brethren, (to wit,
the church,) that the gospel which was preached of me, was not after man;
for I neither received it of man, neither was I taught it,
but by the revelation of Jesus.`"
So I can declare to you all, in the presence of the Lord, that the gospel,
which is the power of God, I neither received of man, neither was I taught it,
but by the revelation of Jesus Christ.
And all you that have received the same power, (to wit,
the gospel,) and are possessors of it, can testify, that the gospel, the power of God,
is neither by man, nor of man; though some men and women, in their carnal wisdom,
may oppose it; but as Peter saith, 1 Pet. 1:11-12. "`the gospel by the holy ghost,
sent down from heaven,`" was it which was preached to the churches then,
and so it is now.

And therefore, all you that have received it, this heavenly and everlasting power of God,
the heavenly dignity, keep in your possessions of it, being heirs of it,
and in the holy order of it, and walk, as becomes the gospel,
and let your conversation be according to it, as the saints,
and the churches were in the primitive times;
for Christ that redeemed his people out of their vain conversation,
and purchased them with his blood, and is become the head of the church,
the heavenly and spiritual man,
has given them a heavenly and spiritual possession and order to walk in, and to keep in,
which is the heavenly, and eternal, and everlasting unity and fellowship; to wit,
in the everlasting gospel, the power of God, which I am not ashamed of,
of the gospel of Christ; for it is the power of God unto salvation,
to every one that believes. Rom. 1:16.

And the cross of Christ is the everlasting power of God:
so no longer do you keep in fellowship, but as you keep in the cross of Christ;
for the enemy to the cross of Christ is the mind
that runs into outward and earthly things,
and sets up another god, to wit, their belly; and another glory, to wit, their shame;
and therefore it is called the mystery of the fellowship of the cross of Christ,
which is the power of God.
So this fellowship is not of man, nor by man; for it is in the everlasting power of God.

And therefore, forsake not the fellowship,
and the assembling of yourselves together in it, as the manner of some is, and was;
but exhort one another, and so much the more,
because ye see that the day draweth nigh more and more unto you;
for if there be a sinning willfully,
after that ye have received the knowledge of the truth,
there remains no more sacrifice for sin, but a fearful looking for judgment,
and for indignation, which shall devour the adversaries.

And therefore, keep in the new and living way,
which is prepared for all the true believers,
as you may see in Heb. 10:20. And "`exhort one another daily,
while it is called today;`" mark, while it is called today;
for thou mayst lose the harvest day, and be hardened before tomorrow;
and "`lest any of you be hardened,
through the deceitfulness of sin;`" and this was the practice of the church,
that was in the light, power, and spirit of God, as in Heb.
3+++.+++ And in Titus, see how the apostle admonishes him, who was in the power of God,
to exhort and rebuke, with all authority; and so forth,
after he had showed him how the grace of God, which bringeth salvation,
appeareth to all men, which taught the saints how to live,
etc. and they that went from it were to be rebuked, and others exhorted to it. Tit. 2:11.

And also he instructs Timothy, who was in the power of God, to exhort the church;
and likewise that the scriptures, which were given forth by the inspiration of God,
were profitable for doctrine, to reprove instruct, and correct in righteousness,
that the man of God may be perfect, thoroughly furnished to all good works; mark,
the man of God, not the man of the world, that denies perfection;
and they that have the spirit of God, that gave forth the scriptures, do the same. 2 Tim. 3:16-17.
And they that were to exhort,
were to be an example in word and conversation, in love, in spirit, in faith,
and in pureness; such were to give attendance to exhortation, and to doctrine,
and still are,
as you may see in 1 Tim. 4:12. And Peter saith to the church in the primitive times,
which ought to be the practice of the church of Christ now,
"`As every man hath received the gift, even so let him minister the same one to another,
as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracle of God; if any man minister,
let him do it as of the ability which God giveth;`" mark, God giveth, and not man,
or as God hath ministered to him,
"`that God in all things may be glorified through Jesus Christ,
to whom be praise and dominion forever and ever.
Amen.`"
1 Pet.
4+++.+++ And the apostle saith "`To every one of us is given grace
according to the measure of the gift of Christ;
for there is one God and Father of all, which is above all, and through all,
and in you all.`"
So every one, now as then, is to mind him that is in them all, who is above all,
and his gift, and the measure of grace, the gift of Christ; for it will teach them,
and bring their salvation;
and through the measure of the gift of grace they grow up to a perfect man,
and to the measure of the stature of the fulness of Christ, as may be seen Eph.
4.

And as God hath dealt to every man a measure of faith, in the faith they should walk,
which gives them victory and access to God, which purifies their hearts;
with which they please God.
And the apostle said to the church then,
which is to be the practice of the true church now,
that according to the grace that was given, "`whether we prophesy,
let us prophesy according to the proportion of faith;`" or any office,
let us wait on the office; "`or, he that teacheth, on teaching; and he that ministereth,
on ministering; or, he that exhorteth, on exhortation; and he that distributeth,
let him do it with simplicity,`" etc.
And "`he that showeth mercy, with cheerfulness;`" as you may see, Rom. 12.
So all this is to be done, in the faith,
and according to the measure of the grace given to every one;
so that all may be done in the faith from one spirit,
which the manifestation of is given to every one to profit withal;
by which spirit they are all baptized into one body,
which Christ the heavenly spiritual man is the head of.
So all members, from the eye to the foot, are serviceable in the body,
in the grace of God, who are joined together by the spirit of God,
and to Christ their head, from whom they receive nourishment;
for the spirit of God does distribute to every one severally, as he will,
and so are all made to drink, (mark to drink,) into one spirit;
in which they have all fellowship in the heavenly drinking of the spiritual drink,
and eating of the spiritual bread that comes down from heaven.
Therefore every man and woman`'s eye must be lifted up to heaven, and minds, and thirsts,
and desires, and hearts, and the soul that hungers, and the needy that sighs,
and the poor that groans, for this bread that comes down from heaven;
and the spiritual drink, and so they may have the spiritual bread in their own houses,
and heavenly water in their own cisterns,
with which they have to refresh themselves and others.
So here may all eat and drink to the praise and the glory of God,
for all drink into one spirit.
And as they eat of the bread that comes down from heaven,
then they can say the scripture is fulfilled; "`All eyes are lifted up unto thee,
thou opens with thy hand;`" to wit, thy power;
"`and thou fillest with thy blessings;`"and then with their souls, hearts, and spirits,
minds, and lips, they will show forth his praise, in praising God, the Creator,
who is in all, over all, through all, and above all.

And therefore, in the power and name of Jesus, in whose name you were gathered,
keep you meetings, your men`'s and women`'s meetings,
that in the power you may be kept in the holy unity, and holy order, in diligence,
in the church of God, and in his business, and affairs, admonishing, exhorting,
rebuking such as talk, and do not walk accordingly: such as profess, and do not possess:
and such as are the sayers, and are not the doers.
So that every one`'s life and conversation may be
as becomes the gospel of our Lord Jesus Christ,
the heavenly man, and keep in the unity of the spirit,
which is the bond of the Prince of princes`' peace: which, if you break,
you forfeit your riches in your estate and inheritance of life.

And some men may say, man must have the power and superiority over the woman,
because God says, "`The man must rule over his wife; and that man is not of the woman,
but the woman is of the man.`"
Indeed, after man fell, that command was; but before man fell there was no such command;
for they were both meet-helps,
and they were both to have dominion over all that God made.
And as the apostle saith, "`for as the woman is of the man,`" his next words are,
"`so is the man also by the woman; but all things are of God.`"
And so the apostle clears his own words; and so as man and woman are restored again,
by Christ up into the image of God,
they both have dominion again in the righteousness and holiness, and are helps-meet,
as before they fell.
So then the man is not without the woman, neither the woman without the man in the Lord.
He that hath an ear to hear, let him hear.
But there are some dark spirits that say, that for women to meet together to worship God,
apart from the men, is monstrous and ridiculous.
But this dark spirit has not defined what worship is;
for if a company of women should meet together,
and some of these women should kneel down, and lift up their hands and eyes to God,
and pray to God, or praise God, as John would have fallen down to the angel,
this is worship.
And if the dark spirit calls this monstrous and ridiculous,
because men are not with them, then it will follow,
it will be monstrous and ridiculous to pray to God, or to worship God,
except men be with them.
Therefore, with the spirit of God,
all may see what confusion this dark spirit is running into,
that is against women`'s meetings,
and that women must not worship God apart from the men,
and calls it monstrous and ridiculous; but from their own monstrous spirit,
their own ridiculousness is manifest.
For you may see in the scripture what worship was, and what worship is;
such as were not to worship idols, they were not to lift up their hands nor eyes to them,
nor to fall down to them, but to worship God, and to bow down to him,
and to lift up their hands and eyes to him;
for all men and women must lift up their eyes, hands, hearts, and spirits to the Lord,
and to bow to him, and worship him; and ought in all their meetings,
that gather in the name of Jesus, to wait upon the Lord for wisdom, counsel,
and understanding,
that by it they may be ordered and directed in his holy service and business,
in his holy church, which Christ is the holy head of,
as they are directed and ordered by the Lord`'s power and wisdom, to praise, and magnify,
and glorify him, with thanksgiving, both in your men`'s and women`'s meetings,
and all other meetings, in the name of Jesus Christ, for he is in the midst of them,
their prophet, priest, teacher, shepherd, bishop, and counsellor,
opening with his heavenly power, feeding with his heavenly food,
counselling with his heavenly counsel, sanctifying them,
to present them to the holy God without spot,
overseeing them with his holy power and spirit;
that God may have the praise and the glory through Jesus Christ, in all, and through all,
who is blessed forever.

So Friends are not to meet like a company of people about town or parish business,
neither in their men`'s nor women`'s meetings, but to wait upon the Lord;
and feeling his power and spirit to lead them, and order them to his glory;
that so whatsoever they may do, they may do it to the praise and glory of God,
and in unity in the faith, and in the spirit,
and in fellowship in the order of the gospel;
and the devil and his instruments cannot get into this gospel, which is the power of God;
and that makes him rage; and he would not have the woman to have a share in it,
(who first deceived the woman, and now would again,) nor the men neither.
Nor he cannot get into the worship of God, which is in spirit and truth,
which the devil is out of; and therefore keep your possessions in the power of God,
and your habitations there within, and in Christ Jesus,
who bruises the head of the serpent, who is the head of all false orders, and disorders,
and has made the world like a wilderness,
and he in his instruments is against the order of the gospel, and the power of God,
that men and women should be in the possession of, and the dignity thereof.
And this many spoke evil of in the apostles`' days, and so they do now;
but the power stands, and the order of it over his head, and his instruments;
and Christ is the same today as yesterday; and so forever;
and of the increase of his government there is no end.
So all that be heirs of Christ,
and of his power and righteousness are heirs of his government;
and they see there is no end of the increase of it.

And you may see how the apostle, after he had convinced people,
he brought them into the order of the gospel; and the Jews after they came out of Egypt,
they were brought into the order of the law of God.
And as the christians come to believe in Christ,
then they are to come into the order of the gospel.

So as I was first moved of the Lord God,
to go up and down the nation to preach the gospel,
then after the Lord moved me to go up and down, to exhort and to write,
that all people might come into the possession of the gospel,
(and the order of it,) which is the power of God, which was before the devil was;
which is not of man, nor by man and his word;
by which all things are upheld and ordered to the glory of God.
And Christ is a priest after the order of Melchizedek.
So you may see there was a heavenly order in the power and spirit of Christ`'s priesthood,
as there was of Aaron`'s; of whose order Christ came not.

And the apostle saith to the church, "`Let all things be done decently, and in order.`"
And this order was in the power of God, the gospel, 1 Cor. 14. where all decency is.
And the apostle saith, "`Though he was absent in the flesh,
yet he was present with them in the spirit,
rejoicing and beholding their order;`" to wit, the churches`' order,
and their steadfastness in Christ.
"`And as you have received Christ Jesus the Lord, so walk in him.`"

So this was the spiritual order of the gospel, which the apostle in spirit beheld,
and does admonish them unto; in whom their walking should be; to wit, in Christ,
the spiritual heavenly man; and not to walk in old Adam,
who was without this spiritual heavenly gospel order;
which is the duty of all true christians, to walk in Christ and his gospel order.
And it is said in Ps. 37:23. "`The steps of a
good man are ordered by the Lord;`" and that is,
by his power and spirit.

And in Psalm 50. "`To him that ordereth his conversation aright will I
show forth the salvation of God;`" "`and whoso offereth praises,
glorifies me,`" saith the Lord.
So they that offer up praises by the spirit, glorify God, which all must keep to,
and not quench it.
And all whose conversation is ordered aright, it is by the power of God, the gospel;
for they are kept by the power of God unto the day of salvation;
and this is the right order, and everlasting order, which all must keep and walk in;
by which all conversations must be ordered aright, that all may see their salvation,
Christ Jesus, who is the head of the church, and who see and receive him,
have life everlasting, and through him they have peace with God.
So all in him live, and meet, in whom you have life, and a peace that is everlasting,
that none can take away; which peace is not this world`'s peace.

And also the whole church of Christ, which are the believers in the light,
children of the light, living stones, that make up the spiritual household;
over which house Christ is the head; all such believers, men and women,
are a chosen generation, a royal priesthood, a holy nation, a peculiar people,
that they should show forth the virtue of Christ,
that hath called them out of darkness into his marvellous light.

So into him the life, to wit, Christ Jesus, by whom the world was made,
here in him they know their election before the world began.
So a royal priesthood, Christ`'s church is called,
offering up spiritual sacrifices to God, who is a spirit;
and this royal priesthood has a high priest, made higher than the heavens, to wit,
Christ Jesus; and this royal priesthood is not after the order of Aaron,
whose order was proved by his rod`'s bearing fruit, laid over night in the tabernacle,
and in the morning brought forth fruit; but your order is proved by your rods`' budding,
and bringing forth fruit, in the morning of God`'s day,
which are the fruits of the spirit;
through which spirit you come to offer according to your order,
which is in the power of God, the gospel, the spiritual sacrifices,
the first fruits of the spirit to God, who is a spirit;
according to your order (as I said before) of the gospel, the power of God.
For the Jew outward was to offer the first fruits of the earth,
according to the order of Aaron; but according to the order of the gospel,
you (both men and women) are to offer the first fruits of the spirit to God,
who is a spirit, over all, blessed forever.
And show how the Lord has blest you in your spiritual fruits,
and how you have been captives, in spiritual Egypt, and how you were redeemed.
Much more I might write concerning these things but they are hard to be uttered,
or to be borne;
for there has so much strife and foolishness entered into the minds of people,
and a want of the stillness and quietness in the pure spirit of God,
in which things are revealed that have been veiled;
in which things are opened that have been hid, and uncovered that have been covered.
But wait all in the diligence, in the holy life,
by which the holy things are seen and received,
in which the holy unity and fellowship is.
So no more but my love.

G+++.+++ F.

[.centered]
=== Letter 314.

[.blurb]
==== To all my dear Friends, elect and precious, in America.

Stand fast in the faith which Christ Jesus is the author of, by his heavenly ensign,
in your heavenly armour,
and your feet shod with the preparation of the heavenly gospel of peace,
and your heads preserved with the helmet of salvation,
and your hearts fenced with the breastplate of righteousness,
and so stand feeling and seeing God`'s banner of love over your heads,
manifesting that you are the good ground, that God`'s seed hath taken root downward in,
and springs upward in, and brings forth fruits in some sixty,
and some an hundred fold in this life, to the praise and glory of God,
always beholding the sun of righteousness, that never sets, ruling the supernatural day,
of which you are children, and the persecutor`'s sun,
(which rises and sets again,) the heat of it cannot scorch your blade,
which it may do that seed that grows on the stony ground.

And therefore, be valiant for God`'s truth upon the earth, and fear him,
that can break their fetters, their jails, and their bonds in sunder,
and can make your fleece to grow again,
after the wolves have torn the wool from your backs;
for the rod of the wicked shall not be always upon the backs of the righteous.

And therefore mind Christ, who is the first and last,
who bruises the head of him who is the head of all persecutors, to wit, the devil.

And consider how all the faithful in all ages suffered, from righteous Abel to just Lot,
and the children of Israel by Pharaoh, and the true prophets by the false,
and Christ and the apostles by the vagabond professing Jews,
(out of the possession,) and what rejoicing it was to them to suffer for the Lord Jesus,
and how it was given unto them, not only to believe, but also to suffer;
so it was the gift of God to them not only to believe, but to suffer,
and to bear them up in their sufferings.

And consider how all the martyrs and saints have suffered since the apostles`' days,
by the heathens and false Christians; and so there is no new thing under the sun.

And therefore, keep your meetings in the name of Jesus, whose name is above every name,
in whose name you have salvation; and be valiant for God`'s truth upon the earth,
and sound his name abroad, and keep in the truth,
and give no just occasion to the adversary; for the lamb must have the victory.
And keep in the Lord`'s power, that is over all, and in his peaceable truth,
in which you will seek the good and eternal welfare and salvation of all people.

And the prophet Isaiah speaking of Christ, says,
"`In all their afflictions he was afflicted,
and the angel of his presence saved them;`" so all
Friends feel the Lord in all your afflictions.

And the apostle saith, "`We ourselves glory in you, (to wit,
in the churches of God,) for your patience and faith in all your
persecutions and tribulations that you endure.`"

So here you may see the saints are one another`'s joy in the Lord,
who doth uphold them in all their persecutions, tribulations, and sufferings;
and therefore look over the devil, that is out of truth, that makes to suffer, to Christ,
who bruises his head; and in Christ, who is first and last, in him have you rest, life,
and peace.

And you see, by faith, "`Moses chose rather to suffer afflictions with the people of God,
than to enjoy the pleasures of sin for a season.`"

So by faith,
"`he esteemed the reproaches of Christ greater riches than the treasures in Egypt.`"

And by faith, "`Moses forsook Egypt, nor fearing the wrath of the king, for he endured,
as seeing him who is invisible;`" and so by faith
God`'s people now forsake spiritual Egypt.

And by faith "`the mouths of the lions were stopped;`" and "`by faith they endured tortures,
not accepting deliverance that they might obtain a better resurrection;
and by faith they underwent all the cruel mockings, scornings, bonds, and imprisonments;
and by faith they underwent stoning and sawing asunder,
and were tempted and slain with the sword;
and they wandered about in sheep-skins and goat-skins, being destitute, afflicted,
and tormented; of whom the world was not worthy,`" etc.

Now all these lived in the one faith, by which they saw him who was invisible;
which is the faith of God`'s elect now,
(which Christ Jesus is the author and finisher of,) which faith upholds his people now,
as it did then, against the persecutors in days and ages past.

And hold fast the hope which anchors the soul, which is sure and steadfast,
that you may float above the world`'s sea;
for your anchor holds sure and steadfast in the bottom, let the winds, storms,
and raging waves rise never so high.
And your star is fixed, by which you may steer to the eternal land of rest,
and kingdom of God.
So, no more, but my love to you all.

G+++.+++ F.

Swarthmore in Lancashire, the 12th of the 12th month, 1675.

[.centered]
=== Letter 315.

[.blurb]
==== To Friends in Barbados.

[.salutation]
Dear Friends,

To whom is my love in the holy truth; my desire is, that you may all be valiant for it,
against all deceit, that the camp of God may be kept clean;
and all may be faithful in your testimonies of light and life,
against all those things which have come up in this night of apostacy from the light,
life, and power of God.
So look at the Lord and his eternal power,
which has brought you out of the night of apostacy, to his eternal praise,
and his power hath preserved you to this day.
The Lord with his glorious power was with us in all our assemblies,
at this Yearly Meeting; he hath the dominion,
and over all evil spirits gave dominion to his people.
Glory to his name forever.
Amen.

Great persecutions are in most counties in England,
and many are imprisoned in many places, and their goods spoiled.
And we had a very large Yearly Meeting here, and very peaceable and quiet.
And the Lord`'s power and presence was richly manifest in our meetings,
and the Lord wonderfully supports Friends in all their trials and sufferings,
and Friends generally are in much love and unity one with another.

Now, friends, we desire that at your Quarterly Meeting,
you may write over an epistle to the Yearly Meeting in London,
of the affairs of the church of Christ, and the prosperity,
and the spreading of his truth there;
for we had a large epistle from the Half-Year Meeting in Ireland, which declares,
that Friends were all in unity there; and likewise an account was given from Scotland,
that Friends were in unity there;
and likewise an epistle was read in our Yearly Meeting here,
from the Yearly Meeting in Holland, which gives an account,
that Friends are in love and unity there; and in Friesland, Germany, and other places;
but at Embden and Dantzick, they are under great persecution;
and we have lately a new meeting set up beyond Holland,
who have been under much suffering and persecutions, but they stand faithful to the Lord.
And at Algiers, in the Turks country,
Friends there have set up a meeting amongst themselves,
(who are captives,) about twenty Friends,
and some other of the captives have been convinced at that meeting.

And one Thomas Tilby, a captive Friend, hath a testimony for God,
and speaks there among them; and their patrons, or masters, let them meet;
and one of their masters spoke to a Friend, as he was going to a meeting,
and thought he had been going to a public tippling house, and he stopped him,
and asked him whither he was going?
and he told him, to worship the great God; and he said it was well, and let him go;
and some of the Turks said, they had some among them of their people,
that would not buy stolen goods.
I have written a large epistle to them to encourage them,
and that they might preach the gospel abroad in those parts, both in their words, lives,
and conversations; and this meeting there, among the Turks, may be of great service.

And now, friends, all be careful of God`'s glory, and seek the good one of another;
and strive all to be of one mind and heart,
and that the peace and gentle wisdom of God may order you all.
And be courteous, and kind, and tender-hearted one to another;
and so the Lord God Almighty, in his holy spirit,
preserve you all in unity and fellowship one with another.
Amen.

G+++.+++ F.

And Friends you may send a copy of this to the Carribee Islands,
to be read in their Quarterly Meetings; and you may read it in your own.

[.centered]
=== Letter 316.

[.salutation]
Dear Friends,

All that feel the life, and power, and spirit of the living God,
who are made alive by Christ Jesus, the living, heavenly, and spiritual man;
and so are come to feed upon the heavenly and spiritual things,
which Christ your shepherd directs you to, according to your capacity, age, and growth;
and so to know him that God has sent to feed you,
above all the feeders that men have sent.
Therefore, look unto him, who with his net,
(which is his power,) hath gathered you out of this great sea, the world.
And now, do not build like the fools upon the sand of the sea-shore;
but upon the rock and foundation, which is Christ the life, that will stand over death,
tempests, winds, and storms; and so looking unto Jesus, that is your saviour,
that has saved you out of the flood of destruction, who is the author of your faith;
by which faith you may walk upon the world`'s sea, looking unto him that will finish it;
and so in truth you can say, faith is your victory; this is your victory,
even your faith, that Jesus has been the author of, the heavenly and spiritual man.
And faith comes by hearing of the word, by which all things were made and created,
and by which all things are upheld, which lives, and abides, and endures forever;
which word was in the beginning with God, and God was the word; which word became flesh,
and dwelt among us, who beheld his glory, the glory as of the only begotten son of God,
who is risen, whom you come now to hear and see, and not only so,
but come to be made partakers of his glory, and of his resurrection from the dead.
So blessed are they, and you, that come to have part in the first resurrection,
that on you the second death may have no power; and such as do,
they know a dying to sin here, and putting off the body of sin and death,
and a crucifying the old man, with his affections and lusts; and a putting him off,
and to be dead from the rudiments of the world: and so they that "`die with Christ,
shall live with him;`" and they that are risen with Christ, can never touch, taste,
nor handle the doctrines, commandments, and dead rudiments of men of the world.
But let such put on the new man,
which (after the image of God) is created in righteousness and holiness;
and such come to live in Christ, and walk in him,
and have their part or lot in the first resurrection, in Christ Jesus,
and the second death hath no power over them: but they live in him,
that hath power over death, hell, and the grave, (and over the devil,
and the power of death,) Christ Jesus, who was before he was, the first and last.
But they that will not believe in Christ the resurrection and the life,
are for condemnation with the devil, hell, and death,
which are to be cast into the lake of fire; and over such the second death hath power.
And therefore, all that come out of death, and partake of the first resurrection,
and know that they have been dead in sins and trespasses,
and are quickened by Christ Jesus, and know a living here in Christ,
and a dying here with Christ, while upon the earth,
(for John spake it whilst he was upon the earth,) the "`second
death shall have no power over them;`" and they that do not,
the second death hath power over them,
which (as I said before) must be cast into the lake of fire, that burns with brimstone;
and such have not the blessing, (as they in the first resurrection,) but the curse, woe,
and misery.
And therefore all you who are the first-fruits to God,
in the resurrection by Jesus Christ, and who know him, the resurrection and the life,
and are translated from darkness to light, and into the kingdom of his dear son,
that stands in righteousness and holiness, and joy in the holy ghost;
that you may show forth righteous and holy fruits, so that you may glorify God,
the Father of our Lord Jesus Christ; and may be as lights to the dark world,
and salt to season the unsavoury.
For every sacrifice, which was offered up to God, was to be seasoned with salt;
so every sacrifice now that is to be offered up to God, must be seasoned,
and made savoury with this heavenly salt of his heavenly spirit,
so that all may give a good savour to him,
and be as a sweet smelling sacrifice to the pure holy God, that made all to his glory.
And you cannot bring forth this holy, righteous, and pure fruit unto God,
but as you abide in Christ Jesus, the truth,
who did descend and ascend far above all principalities, thrones, and dominions,
that he might have the preeminence above all,
and that ye in him might live above all unto God.
And so every one of you that has received Christ Jesus the Lord over all,
in him (who is your Lord) walk, who is the amen;
and there all the living can praise God together;
and the living gather in the name of Jesus, the name of him who was dead,
and is alive again, and lives forevermore, who is the first and last.
And here you all know,
that there is no salvation in any other name under the whole heaven,
but in the name of Jesus; who is a priest made higher than the heavens.
So in his name keep your meetings, in whom you have salvation;
and these are the true meetings, and true gatherings,
who feel Jesus Christ in the midst of them, their prophet, their counsellor,
their leader, their light and life, their way and their truth, their shepherd,
that laid down his life for them, that has bought you, his sheep,
who feeds you in his pastures of life; and your heavenly bishop, to oversee you,
that you do not go astray again from God.
And so it is through him you overcome,
and he that overcomes shall go no more forth out of his fold, out of his pastures,
who shall sit down in the heavenly places in Christ Jesus, who is your priest,
that offered up himself for you, and sacrifices for you, and makes you holy and clean,
that he may present you blameless up to the holy and pure God;
and here you come to witness and know him in his offices, by his light, spirit,
and power; and all your men`'s and women`'s meetings, in the power of God,
which was before the devil and his power was, in the holy order of the gospel keep them,
you being heirs of the everlasting gospel, the everlasting power of God,
that will last forever; a joyful gospel, a joyful order, a comfortable gospel,
so a comfortable order, a glorious gospel, and glorious order.
So in this everlasting gospel, the power of God,
in which you have everlasting fellowship and dominion over all sin and wickedness,
unrighteousness, unholiness, and all that is bad whatsoever, you have dominion over,
in the gospel, the power of God, yea, over the devil.
And this gospel may every one testify unto, and to the order of it,
that it is not of man, nor by man,
neither is it received but by the revelation of Jesus Christ, sent down from heaven,
which all the believers, that have part in the first resurrection, live, walk,
and keep in the order of this gospel; and so have power to admonish, exhort, reprove,
and rebuke, with all authority, such as talk of Christ, and do not walk in him;
such as profess him, and do not possess him;
such as live not in the religion that was set up above sixteen hundred years since;
such as profess Christ the way, and walk not in the way, the truth, and the life,
all such talkers, and not walkers, are dishonourers of God,
and cause his holy name to be blasphemed among such as make no profession.
And therefore, all Friends that know that you are alive to God, by Jesus Christ,
and know your translation from death to Christ the life,
and from darkness to Christ the light;
so that you may all come now to be helps-meet in your restoration by Christ Jesus,
into the image of God, and his righteousness and holiness,
that man and woman were in before they fell:
for before they fell they were meet-helps to subdue the earth,
they had both power over all that God made, while they kept in the image of God,
and his righteousness and holiness; and so all that God made was blest and good to them;
and so none can renew up into the righteousness and image of God, but Christ Jesus.
And therefore, I say, in him live and walk, and keep his gospel-fellowship and order;
so that men and women may be meet-helps, in the distinct men and women`'s meetings,
one unto another in the gospel, the power of God, in the restoration,
as man and woman was in before they fell:
so if the men have any thing to communicate unto the women,
or the women any thing to the men, in the righteousness, and wisdom, and power of God,
in the gospel order, in which the heavenly fellowship, unity, and order are kept,
they may, as brethren and sisters.
So here is the foundation of our meetings;
and our men and women`'s meetings are testified unto
by the spirit of the everlasting God,
that the foundation of them is Christ, of the increase of his righteous, glorious,
and spiritual government and peace there is no end; nor of the glorious, everlasting,
heavenly unity and order of his heavenly gospel,
which the spiritual and heavenly minds keep and walk in accordingly, which is not of man,
nor by man; so man has no glory, but God and Christ alone, who is almighty, omnipotent,
immortal, everlasting, and eternal, and dwells in the light, blessed forever,
the inexpressible God.

And so all keep the unity of his eternal spirit,
which is the eternal bond of your heavenly and eternal peace, of your King of kings,
Lord of lords, and Prince of princes`' peace, Amen.

All Friends be faithful in the Lord`'s power, and in his spirit,
to the Lord God and his truth, that is over all, and will keep you over all,
as you all do live and walk in it, to the glory of God,
and bring forth fruits that are heavenly to his praise.
So live in the possession of life eternal, which was before death.
And so in this power of Christ, nothing can get between you and the Lord,
your everlasting home.
So with my love.

G+++.+++ F.

Swarthmore, the 10th month, 1675.
