== Letters 317 &#8212; 320

[.centered]
=== Letter 317.

[.blurb]
==== To all the elect and chosen of God in Christ Jesus, before the foundation of the world.

Friends and brethren,

It lies upon me from the Lord to write unto you these following lines.
First, I was sent out by the Lord God, in his eternal light and power,
to preach the word of life, which was before the word of death,
and to turn people to the light, which was before darkness and the power of it,
that all might be reconciled to God, by the word;
and that all might believe in the light, which is the life in Christ the word,
and so become children of the light, and to know Christ the author of their faith;
and their faith to stand in him, who is the author and finisher of it;
and to turn people to the spirit, which they had quenched, vexed, and grieved,
and rebelled against; that in that holy spirit,
they might see before the spirit of error was;
and that in the spirit they may know God and Christ, and the scriptures,
which were given forth from it; and that in the same spirit,
they might all have fellowship one with another, and with the Father and son;
and so to preach the everlasting gospel, the power of God,
(which was before the devil was,) that brings life and immortality to light,
in all that do receive it, that they might see over him that had darkened them.
Which gospel I received not of man, nor by man, but of the Lord Jesus Christ,
by his holy spirit sent down from heaven.
And so after I had received this, and preached it, and many thousands were come into it,
in several places of the nation, then by the same power, and spirit, and light,
I was moved to advise, to the setting up the men`'s Monthly and Quarterly Meetings,
and the women`'s meetings.
So that all in the power of God, the gospel, which was before the devil was;
and in the light, which was before darkness was, and all in the holy spirit,
before the unholy spirit was.
That they might be all in their possessions of the light, spirit, and power of God;
and therein to keep this heavenly order of the gospel, being heirs of Christ,
and of his government; of the increase of which there is no end.
Which gospel order is over all the orders of Adam in the fall,
or amongst the apostates from that gospel the apostles were in, and will stand,
(the power of God, the gospel,) when they are gone.
So that all the heirs of life and grace, and heirs of the gospel,
might be in their possession, and keep in the power which was before the fall was;
and into this no apostacy can come.
So here in this power of the gospel, all have their liberty, and all have unity,
and all have liberty in the spirit, and unity in the light, and unity in the faith,
that Jesus Christ is the author of.
So that all may see him and his government,
which is over the government of Adam in the fall; for he was before old Adam was,
and will be when he is gone.
And so that all might be in the possession of Christ, and as they have received him,
so to walk in him, the heavenly and spiritual man;
of the increase of whose government there is no end;
but there will be an end of old Adam`'s.

Now, friends, whosoever shall come, under what pretence soever, to alter these meetings,
or to deny or speak against the men and women`'s meetings,
it is the spirit of confusion and opposition, which would be seeming to do something,
yet its work is to disquiet the simple minds;
and it is the very same spirit with John Perrot`'s; and mark his end, and their end,
and such as join with it.
For it is against the power of God, in which the order is established,
and the eternal spirit and light, in which the men and women`'s meetings were set up;
in which all things should be established, and are fastened,
in the light which was before darkness was, and in the power of God,
before the devil was, and in the holy spirit, before the unclean spirit was,
and will stand when he is gone.
Therefore, in it keep your possessions in the power of God, and in his light and spirit,
that you may know the mountain of the Lord established above all mountains.
And they are none but loose spirits, and such as tend to looseness,
that stand against the men and women`'s meetings,
though it may come under pretence to set up a better way; or,
under pretence only to alter them to another day; and, it may be,
pretend their fear of the corruption of observing a day.
All this is but from a corrupt spirit of darkness, which God will blast;
for we put no holiness in the usual and constant days of Monthly and Quarterly Meetings.
For I would have them all to know, that they who are heirs of the gospel,
and of Christ Jesus, are redeemed out of the vain observation of days,
and out of the Jewish and apostate christians`' holy days, to God by Christ,
who made all days, and everything good,
and their eyes are to the supernatural day of Christ;
and they are the children of this day.

And that is a creeping spirit,
that would go to alter the usual and constant meeting days,
under pretence to prevent people from the corruptions of observing a constant day,
or under a pretence of keeping people out of a form,
and so would father their deceit upon God.
For they who are in the possession of the power,
by which all true forms and all things are upheld,
(which word and power gives form and being to all things,) and all they that are in it,
are above all such things, and judge all such dark spirits.
And they that are in the observation of days, are not heirs of the power, nor of Christ,
who was before days were, and such cannot sit in the heavenly places in Christ Jesus,
to do his churches`' business.
So, I say, that after people were turned to the light, power, and spirit of God;
and they all come into the light, power, and spirit of God;
all such are to make up the men and women`'s meetings;
and in it to feel the wisdom of God, by which all things were made and created,
and with it to be ordered, and to order all things to God`'s glory:
so that wisdom may be justified of her children.

Now concerning laying all marriages before the men and women`'s meetings.
Some have darkly objected, this is not as was in the beginning.
Whereas in the beginning we were but few in number,
and could not presently be so sensible of the service of them,
as when grown more numerous, and a body of people;
but in the beginning there was a care things might be kept clear: for, in 1653,
several Friends came to me, concerning marriage,
and to know what they should do in that case.
And I waited upon the Lord, and saw in his eternal light, that all that did marry,
they should lay it before some faithful Friends, in the wisdom of God,
that they might see into it.
These were my words then, as in a paper of mine, given forth that year, may be seen.

And afterwards I was moved to go round the nation,
to advise to the setting up the men and women`'s meetings,
and to write to those places where I could not go:
that all the faithful might keep their meetings in the power of God,
and in it be settled, and established:
and that all marriages might be laid before the men and women`'s meetings,
who were in the wisdom of God, and in the possession of his gospel order,
who had the care of the church of Christ`'s business,
that they in the wisdom of God might look into it,
and see that they were clear from all other persons, etc.

And therefore now that pretence is generally taken away from all, they cannot say now,
that they cannot tell where to find a meeting of the faithful,
to lay their marriages before them, before they declare it in the common public meetings.
Now that the men and women`'s meetings are settled in the power of God,
to look after the churches`' affairs;
for all know where they may be found at certain days, times, and places,
to lay it before them.
And they that go together in the truth and power of God,
will be willing to lay their marriages before them
that are in the same truth and power of God:
so that all things may be done in truth, love, and unity, and pureness, clearness,
and holiness, to the praise and glory of God.
And all, whosoever they be, that oppose this good order, are loose spirits,
out of the power of God; and their work tends to looseness,
and to draw into a loose liberty,
under a deceitful pretence of keeping people out of forms.

So the same power and spirit, that directed all marriages to be laid before the faithful,
at the first, when there were but few Friends, in many parts of the nations,
and no men`'s nor women`'s meetings: I say,
the same power of God that did convince Friends at the first,
the same power and spirit directed to the setting up the men`'s and women`'s meetings,
that they might be in the possession of the gospel, and its order.
And the same power and spirit of God set up our order
for marriages in our men`'s and women`'s meetings:
and that all are to speak first to their parents, and have their consent,
before they engage the affections of the children;
and this order is settled by the power of God, in the men and women`'s meetings.
For some formerly did speak to neither father nor mother,
till they had drawn out and entangled the affections of the daughter;
and that brought great troubles and discontent upon the parents, and among Friends.
And therefore this is to be inquired into, in the men and women`'s meetings,
where their marriages are to be spoken of.
So as Friends come to truth, which the devil is out of, and to the power of God,
which was before the devil was; all being heirs of life, and the gospel,
and heirs of Christ; I say, take your possession of life,
and come into the order of life, and into the order of the gospel,
and then you will have a witness in yourselves, and will say with me,
our order is not of man, nor by man, but by Jesus Christ, and his gospel;
and of his government, of the increase of which there is no end.
And so all be faithful, keeping in your possessions, and in your inheritance,
in that where no apostacy can come: for I must tell you,
here is the same spirit stirring, if it could prevail,
that would lay waste God`'s heritage, and bring you out of your possessions,
that it might rule over you: but if you keep your possessions of the gospel order,
the power of God in Christ Jesus, you will rule over it,
being in and upon the foundation of God, that stands sure;
though some earthly loose spirits it may draw after them.
But mark the end of it; for the power remains, and will remain,
and the seed reigns over the head of all such false spirits, and orders, and governments,
that are not set up by Jesus Christ, and it will grind them to pieces:
that is the word of the Lord God to you, let whoever will oppose it;
for the power was before they were, and will stand when they are gone.
For all our men and women`'s meetings, which are set up by the power and spirit of God,
these meetings are for the practice of religion,
and to see that all that do profess truth, do practise it and walk in it.
And all such as are against them, are begetters of people into talking, and not walking,
and of saying, but not doing;
and such always were judged by all them that walked in the truth,
and in the pure religion, that is undefiled before God,
that kept and keeps from the spots of the world.
And all such are never like to prosper,
that are against the practice of the pure religion.

And therefore, as I said before, live in the possession of the gospel and its order,
the power of God, which was before the devil was, or the apostacy either;
and know his government, of the increase of which there is no end,
who is set up from everlasting to everlasting, the Amen.

And live in love and unity one with another; for that edifies the body of Christ,
and that is it, which will bear all things; and in the patience run the race,
and have the crown, and keep in the meekness of the Lamb, that will have the victory.

And such opposers as cry against forms, and prescriptions, and edicts of men,
they are the most in it themselves this day, and gather into a separation,
by prescriptions and subscriptions; and under a pretence of crying against such things,
oppose the power, and them that are in the possession of it.
But the power will blast them, and make them to wither,
like the grass and corn on the house-top, as it did John Perrot and his company;
to whom it was the word of the Lord then, and so it is to these now; and the word lives,
and abides, and endures forever.

So with my love in the Lord Jesus Christ to you all,
in whom is my labour and travail for your eternal
good and settlement upon the eternal rock.
Amen.
Farewell.

[.signed-section-signature]
G+++.+++ F.

Let this be read in the men and women`'s meetings, when Friends are assembled together.

Swarthmore, the 12th of the 12th month, 1675.

[.centered]
=== Letter 318.

All dear friends and brethren, keep up your testimony in the light, power,
and spirit of God, for the worship, that Christ set up above sixteen hundred years since,
in the spirit and truth, (which truth the devil is out of,
who is an unclean spirit,) which is a worship that cannot be shaken.
And keep up your testimony, against the anti-christian ministry,
that is inwardly ravened from the spirit of God, and the light of Christ,
and his anti-christian tithes, and maintenance, which he hath set up,
by that inwardly ravening spirit, who hath ravened from the spirit of Christ, who said,
"`Freely you have received,
freely give;`" and Christ`'s ministers coveted no man`'s silver, nor gold, nor apparel.
And keep up your testimony in the power of Christ,
for the church that is made of living stones,
(which he is the head of,) who are the first-born written in heaven,
a spiritual household, a royal priesthood, that offer up spiritual sacrifices.
So that every one may have something to offer from the spirit to God,
who are of the church that is in God; gathered by the power and spirit of Christ to him;
who feed on the bread that comes down from heaven; and drink of the heavenly wine,
and so become flesh of his flesh, and bone of his bone,
and sit together in the heavenly places in Christ Jesus;
who is the heavenly and spiritual head of his church, which is written in heaven, etc.
And also keep your testimony, for your pure and undefiled religion,
etc. and for the wisdom that is above, etc.
And keep your testimony for the cross of Christ, which is the power of God,
by which the world is crucified to you, and you to the world.
And you that were dead, and are risen with Christ, keep your testimony for those things,
that you have sought, and have found, and received from above,
(those heavenly things,) where Christ sits, at the right hand of God.

And likewise, keep your testimony for the new and living way, Christ Jesus;
and likewise for the light of Christ, which you believe in,
and become children of the light and of the day.

And keep your testimony for your men and women`'s meetings, in the power of God,
by which you are gathered out of the apostacy, and over it,
into the everlasting gospel order, as was in the apostles`' days.
Which gospel order is not of man, nor by man; but by Christ, the spiritual man.

And all ye that are ministers of this gospel,
help and encourage all those women in their meetings, that labour in the gospel;
and the women may in the same power of God (the gospel) help and assist you.
So that you may be helps-meet together, in the restoration by Christ,
in his glorious gospel and order, who never fell, nor changed, nor will change.
So that all the plants that God hath planted, may flourish, bud, and spring,
and bring forth fruit, to the praise and glory of God, in his power.
And this gospel of Christ Jesus, is everlasting, and holy, and glorious; which you all,
that feel it, are heirs of; which hath brought life and immortality to light in you;
which gospel, the power of God, was before the devil was, that had darkened you.
Now, in this power of God, the gospel, is all your comfort, and glad tidings;
and an everlasting joy, in this everlasting gospel;
and an everlasting possession and comfort, in the everlasting order,
which is the gospel of Christ Jesus, who is the first and last,
the spiritual heavenly man; his spiritual and heavenly order,
for his spiritual and heavenly ones to keep and walk in.

And, friends, keep your testimony against the world`'s vain ways, words, fashions,
customs, and worships, as you did at first, and to your proper, sound, plain language.

And, friends, keep your testimony to the Lord in all your sufferings and afflictions;
for by the testimony of Jesus, and the blood of the Lamb, did and do the saints overcome;
and the testimony of Jesus is the spirit of prophecy;
by which they see him that gives them their victory;
and they feel him that suffered for them; and in all their sufferings and afflictions,
he suffers with them, and is afflicted with them; who is able to save to the uttermost,
and to help and succour you in all distresses; who is blessed forever.
Amen.

And, friends, keep your testimony (who are children of the new covenant,
and are taught of God; in whose hearts God hath written his law,
and put it in your minds) for your counsellor and leader, which God hath given you;
and for your prophet, which God hath raised up, whom you ought to hear;
and for your shepherd, that God has given, who laid down his life for you,
who hath redeemed you from the world`'s hireling shepherds,
and feeds you in his pasture of life, and brings you to rest in his fold.
And keep your testimony for Christ, your priest, who is made higher than the heavens,
who laid down his life for you, and sanctified you, and presents you to God,
without spot or wrinkle; who is holy, harmless, and separate from sinners.
And so keep your testimony for your heavenly spiritual bishop, Christ Jesus,
who is the bishop of your souls, who doth oversee you with his light, power, and spirit.

And keep your testimony, for the sufferings and resurrection of Jesus Christ;
for they that suffer with him, shall reign with him.
But they that shuffle, and flee in the time of persecution, and deny him before men,
such he will deny, or be ashamed of, before his heavenly Father.
Who deny him, or are ashamed of him, before earthly men, such fear the wrath of men,
more than the wrath of God; and such are the stony ground,
whose blade is scorched up by the heat of persecution;
but the good seed sown in the good ground, that brings forth thirty, sixty,
and a hundred fold in this life.

And keep your testimony for your unity in the faith, that gives you victory;
and your fellowship and unity in the spirit, which is the bond of the Prince of princes,
King of kings, and Lord of lords`' peace.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 319.

[.blurb]
==== To Friends in Nevis, and the Carribee Islands.

Dear friends,

To you all in Nevis, and the Carribee Islands thereabouts,
I have seen a letter from some of you,
wherein I understand that there has been some scruple concerning watching,
or sending forth watchmen in your own way.

Truly, friends, this I declare to you, that it is a great mercy of the Lord,
to subject the governor`'s mind so much by his power and truth,
that he will permit you to watch in your own way, without carrying arms,
which is a very civil thing, and to be taken notice of.
For could Friends obtain the same in Jamaica, and other places,
they would willingly have done it, and did proffer themselves to do it to the governors.
But because they would not bring swords and guns, and other arms,
to watch against the Spaniards, as they pretended,
their standing fine was about 17s. each man`'s neglect,
but they took often 30s. worth for it, and tied some of them neck and heels besides,
till the blood hath come forth at their mouth, nose, and ears.
And this I have seen upon record, who freely proffered to watch in their own way,
but it would not be accepted.
And in other places it hath been the same.

And now as for watching in itself:
Do not you watch your plantations against thieves in the night?
And are not common watches set to discover thieves in the towns, or house-breakers,
or such as might wickedly fire houses?
Such civil things we were subject to, and do submit ourselves, for conscience`' sake,
unto every such ordinance of man, which are for the punishment of evil doers,
and for the praise of them that do well.

Now those evil doers that may rob your plantations, or houses,
you complain to the magistrates, for the punishment of them,
though you cannot swear against them; or if the Indians come to rob your plantations,
or houses, you complain to the magistrates for the punishment of such evil doers,
to stop them, which magistrates are for the praise of them that do well.
So this watching is for the preventing thieves and murderers,
and stopping burning of houses.
So we do submit to every such ordinance of men for the Lord`'s sake;
for the apostle exhorted to submission, whether it be to the king, as supreme,
or governors, as unto them that are sent by him, for the punishing of the evil doers,
and for the praise of them that do well; for so it is the will of God,
that with well doing you might put to silence the ignorance of foolish men, as free,
not using your liberty for a cloak of maliciousness, but as servants of God;
so that justice, and truth, and righteousness may be set upon the unrighteousness,
and unjust, not using this liberty for a cloak of unrighteousness to any one,
but as servants in the righteousness of the righteous God,
as you may see in 1 Peter 2:13. and in Titus 3:1. "`Put them in mind to obey magistrates,
and to be ready to every good work.`"
Mark, "`every good work,`" that is against the evil, as drunkenness, murder, whoredom,
these and all manner of uncleanness; so far we can obey them,
in the Lord`'s power and truth, as they act against the evil,
and that which dishonours God; and if they act against the good,
or if they would compel us to those things,
which are matter of conscience in us towards God, we resist not, but suffer under them.
For rulers are not to be a terror to the good workers, but to the evil;
and wilt thou then not be afraid of the power?
Do that which is good, and thou shalt have praise of the same;
for he is a minister of God to thee for good, for he should keep down the evil.
But if thou dost that which is evil, be afraid; for he beareth not the sword in vain;
for he is a minister of God to revenge and execute wrath upon him that doth evil.
So he is the revenger and executioner of the wrath upon the evil doer,
as God hath placed him, upon the adulterer, and him that steals or kills,
and bears false witness, etc.
But when the magistrate turns his sword backward upon the just and righteous,
then he abuses his power, and therein the just suffer under him.
And therefore such have been warned by the just, as you may see through the scriptures.
So you are not to be the revengers, but he is the revenger;
and to that power that executes the revenge, and brings the sword upon the adulterer,
murderer, thief, false witness, and other evil doers, we must be subject to that power,
and own that power, not only for wrath, but for conscience`' sake;
which is for the punishment of the evil doers, and the praise of them that do well.
For if any should come to burn your house, or rob you,
or come to ravish your wives or daughters,
or a company should come to fire a city or town, or come to kill people;
do not you watch against all such actions?
And will you not watch against such evil things in the power of God in your own way?
You cannot but discover such things to the magistrates, who are to punish such things;
and therefore the watch is kept and set to discover such to the magistrate,
that they may be punished; and if he does it not, he bears his sword in vain.
So if thou watches thy own plantation against thieves, in thy own way,
which thou art desired, for the good of thyself and neighbours,
against such as would burn thy plantation, and thy neighbour`'s, and destroy and rob you,
wilt not thou discover this to the magistrates, to punish such evil doers,
who are set for the punishing of the evil doers, and executing wrath upon them,
and for the praise of them that do well?
Surely yes.

And for this cause we pay tribute to them, and give Caesar his due,
that we may live a godly and peaceable life under them,
as they are God`'s ministers attending upon this very thing, to wit,
the punishing of the evil doers, and the praise of them that do well;
for the law was not made for the righteous, but for the sinner and disobedient,
which is good in its place.
Now if they do not do their duty, we are clear in giving them their tribute or customs;
I say, if they do not do their duty to keep down evil doers,
and be for the praise of them that do well, God Almighty will turn against them.
But if the magistrate would have all, both God`'s due, and Caesar`'s too,
that we cannot give; for God must have his worship, his praise, his honour, and his due;
and Caesar must have his due, his earthly custom and tribute; and so herein,
we render unto God the things which are God`'s, and unto Caesar the things which are his.
And whereas some may say, that the apostle would not eat flesh,
lest he should offend his brother, that was upon a religious account;
and not to give offence to the magistrate,
who is set for the punishing of the evil doers, and for the praise of them that do well.

And whereas the apostle saith, Col. 2.
"`Wherefore if you be dead with Christ, from the rudiments of the world; why,
as though living in the world, are ye subject to ordinances, touch not, taste not,
handle not, which all are to perish with the using,
after the commandments and doctrines of men?`"
Now these ordinances, these doctrines, these commandments,
were concerning religion and worship; and that was another thing,
where the apostle saith, "`Be subject to every ordinance of man, for the Lord`'s sake;
for the punishment of evil doers.`" 1 Pet. 2:13.
For this was for the Lord`'s sake,
which was for the praise of them that do well, and for the punishment of the evil doer.
So he makes a distinction here.

And you know that masters of ships, and Friends, have their watches all night long,
and they watch to preserve the ship, and to prevent any enemy,
or hurts that might come to the ship, by passengers, or otherwise.

And Christ came in the fourth watch of the night, walking on the sea, etc.
And Peter was in the ship, and his disciples,
as you may see in Matt. 14. and in Mark 6:48.

And Simon Peter had part of the ship,
as you may see in Luke 5. And so it was that James and John, sons of Zebedee,
were partners with Simon.

And Christ saith, (Luke 12:38-39) speaking of his coming, and exhorting to watch,
"`If he, (to wit, the master,) should come in the second or third watch,
and find them watching, blessed are those servants.`"
So this watching was for Christ, and against sin and evil in their own hearts.
And then he brings a comparison.
"`And this know, that if the good man of the house,`" said he,
"`had known what hour the thief would come, he would have watched,
and not suffered his house to be broken up,`" etc.

And so here is the good man`'s watching against sin and evil without,
and the spoiler and thief without, whom the magistrate is to revenge,
and to lay his sword upon.
And here is also a watching against sin and evil within,
and a waiting to receive Christ the Lord at his coming.

And as there is a shutting the outward doors, to keep out the murderers and the thieves,
and a bolting and locking of them out.
So there is a shutting up, and locking the door of the heart,
to keep out the adulterer and murderer, and all that is deceitful, from coming within,
into the heart.

And, friends, the priests and professors used to bring this scripture,
"`You must be subject to every ordinance of man for the Lord`'s
sake;`" to the end that we should pay them their maintenance,
and hold up their worship.

And when the magistrates brought that scripture for these ends,
we could not obey them in these things, nor touch, nor taste their ordinances, doctrines,
nor commandments.
But to be subject to every ordinance of man for the Lord`'s sake;
which was for the punishment of evil doers; as drunkards, thieves, murderers, adulterers,
and such like, and to keep down such evil doers,
and that we might live a godly and peaceable life under them;
which was for the praise of them that do well; this we always owned, and were subject to,
and watched against, and declared against in our own way,
and laid such actors and actions before the magistrates, for them to punish,
and keep down with their power, which is their sword of justice;
but if they would compel us to things that we could not do, contrary to our conscience,
for the Lord`'s sake, we suffered for it.

So where Friends have the government, as in Rhode Island, and that province,
Friends were willing to watch, in their own way, and they made a law,
that none should be compelled to take arms.

So Friends have always proffered the magistrates,
though they could not join with them in carrying arms, swords, and pistols;
yet to watch in their own way against the evil doer.

And this they have proffered in Barbados, as I have heard, to discover,
if negroes should rise up to burn plantations, or steal, or do any hurt,
or other Indians invading their land.

And so if the foreign Indians should come to steal your goods, or to kill;
for you to be left to your freedom to watch in your own way,
and to discover to the magistrate such as would destroy your lives or plantations,
or steal, let them come from at home, or come from abroad,
such evil doers the magistrate is to punish, who is for the praise of them that do well.
So that you may live and lead a godly and peaceable life under them.
And you that are righteous, you watching,
discovering and declaring against such evil doers, and things, you clear yourselves,
and demonstrate that your testimony is against such things.
And if the magistrates should be evilly inclined,
and God should bring the evil doers as a rod upon them;
yet you are clear in your testimony, that knows truth,
and are in your duty and in your obedience.
And for this cause he has his tribute, and his custom, and his due, and double honour,
if he rules well; and God has his praise, and his honour;
and in that power and truth of God, which is against untruth, and the power of darkness;
and in the light which is against evil; and in the life, which is against death,
you discover the bad to him, for him to punish them upon true evidence;
and if he does not do it, it will lie upon him.

And if he be a praise to the evil, and a discouragement to the good,
then the Lord will deal with him; and though to such, for conscience,
and for the Lord`'s sake, we cannot be subject to the evil, but rather suffer thereby,
and are subject to that which punishes and keeps down the evil, and are glad of it.
And we desire that justice were uppermost in all magistrates,
that they would hear Friends at their yea or nay, that do come to them,
and discover to them the evil, and that they might see what they should do,
and what they should not do.
So Friends may discover all that which is evil, which comes to devour and destroy,
both within and without, both within the island and without,
to them that should keep it down.

And so, in the Lord`'s everlasting power, in which freedom is and dominion,
the Lord God Almighty keep you in his power and life, in the gospel,
which brings life and immortality to light in you,
that you may see over the devil that had darkened you,
and kept you in a separation from God: so that by his gospel, the power of God,
which was before the devil was, and will be when he is gone,
who was the author of strife; that in that power you may all freely approach to God,
and in it feel nothing betwixt you and the Lord of hindering your passage unto him.
So that in this gospel, the power of God,
in which life and immortality are brought to light,
you may keep and feel your everlasting fellowship and order of the gospel;
which is not of man, nor by man.

So my love to all Friends in all those parts, as though I named them:
and be at peace one with another; neither judge one another about such things,
but live in love, which edify.
And in the power of God, that your hearts, and souls, and minds,
may unite together in it; and all to walk as becomes the gospel:
and let your lives and conversations preach,
that with a measure of the spirit of God you may reach to that of God in all;
so that his name may be glorified, and he honoured,
in your bringing forth much heavenly spiritual fruit, from the heavenly seed,
that Christ the heavenly seeds-man hath sown in your hearts;
that so a hundred fold of holiness, righteousness, godliness, virtue, and piety,
from this heavenly seed, you may bring forth and increase in this life-time,
and in the world to come reap life everlasting.

And give no occasion to your adversaries, neither in your lives nor words;
but that you may all serve God in the new life, showing forth that you are new men,
and that you are renewed in the image of God,
and that you are born again of the immortal heavenly seed,
by the eternal everlasting word, that lives, and abides, and endures forever.
And that you do feed upon the heavenly milk and bread from above,
and that your conversation is in heaven,
and that you are clothed with the fine heavenly linen,
which is the righteousness of saints,
which is Christ`'s (the heavenly and spiritual man`'s) livery;
by which his servants are known by his badge of righteousness,
and distinguished from all the servants of old Adam, Egypt, Sodom, and Babylon,
with their badge of unrighteousness.

And so be valiant for God`'s truth upon the earth, and spread it abroad;
preach Christ and his kingdom, his light, his grace, his truth to men;
that all should walk in it; and his dreadful day upon all the talkers of God, Christ,
his prophets, and apostles`' words, that do not walk in the same power, spirit and life,
grace and truth, as they walked in.

I say, preach this to the magistrates, and amongst the heathen men,
and show yourselves to be quickened (by Christ) who have been dead in sins and trespasses;
but that you are now made alive by him; and so show forth his light, life, and truth,
and that you are awakened to righteousness;
and therefore show it forth to them that are asleep in the unrighteousness:
so that the Lord`'s glory, and righteous power, truth, light, and life,
may flow over all, to his glory over all, forever.
Amen.

And much I could write to you concerning these things, but I have not been very well;
but, blessed be the Lord God, his everlasting seed is over all,
which reigns from everlasting to everlasting, and my life is in it.

And therefore, stand and live in the Lord`'s name and power,
which is against all manner of unrighteousness; and in the light,
which is against darkness, and all the works thereof; and in the life,
which is against death, and over death, and all the actors of it; and in the truth,
that is over all evil, and against all the doers thereof, within and without.
And so, that in the light, life, power, and truth of God, and in his holy spirit,
you may live in fellowship, and in the unity of the spirit, which is your bond of peace;
yea, even of the Prince of princes`' peace; which the world cannot take away from you.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 5th of the 9th month.

[.centered]
=== Letter 320.

[.blurb]
==== An encouragement to all the faithful women`'s meetings in the world, who assemble together in the fear of God, for the service of the truth. Wherein they may see how the holy men encouraged the holy women, both in the time of the law, and in the time of the gospel; though selfish and unholy men may seek to discourage them. But go on in the name and power of Christ, and prosper.

[.salutation]
Friends,

You may read in the old world, how one family after another, till Noah`'s time,
served the Lord God.
And then from Noah, Abraham, Isaac, and Jacob, and their wives,
and after Moses and Aaron had brought the children of Israel out of Egypt,
and that they were come to be a great people, Moses said,
"`I would all the Lord`'s people were prophets.`" Num. 11:29.
And when a young man said unto Moses,
"`Eldad and Medad do prophesy in the camp;`" and he would have had Moses to forbid them:
but Moses answered and said unto him again,
"`Would to God all the Lord`'s people were prophets,
and that the Lord would put his spirit upon them.`"

So Moses here, (who was captain, governor,
and judge over Israel,) was far from restraining any from prophesying in the camp,
but reproved his envy that would have had him forbid them;
and did moreover encourage them, by saying,
"`I would to God all the Lord`'s people were prophets:`" and surely
all the Lord`'s people are made up of both men and women.

And the Lord having given his law to the children of Israel, which was holy,
just and good, the Lord said, "`I have poured out my spirit upon the house of Israel:
so that by this spirit, they might understand his law, which was spiritual.`" Ezek. 39:29.

Now in the time of the law, there were the assemblies of the women;
for all the women that were wise of heart,
did work with their hands about those holy things which God had commanded.

And all the women whose hearts stirred them up in wisdom,
these women wrought about those holy things that belonged to the tabernacle and sanctuary;
as you may see in Exod.
35.

And likewise the assemblies of the women, in the 38th chapter,
and of the women`'s assembling at the door of the tabernacle of the congregation;
and in the margin it is said, they assembled by troops.

Now, here you may see, that the women were in the work and service of God,
as well as the men; and they had their assemblies.
For God had poured out his spirit upon the house of Israel,
to give them an understanding, both men and women, to do that,
and make those things which God had commanded, which were called holy things;
which were but figures and shadows of the substance, Christ Jesus, the holy one.

Now Moses and Aaron, and the seventy elders,
did not say to those assemblies of the women, we can do our work ourselves,
and you are more fit to be at home to wash the dishes; or such-like expressions;
but they did encourage them in the work and service of God,
in those things which God had commanded them in the time of the law.

For God having poured his spirit on the house of Israel, to give them an understanding,
to do those things which God had commanded them;
by which spirit their hearts were stirred up to do God`'s work, both males and females.

And in the time of the law, the women were to offer up sacrifices and offerings,
as well as the men, upon God`'s altar; as you may see, Hannah when she brought Samuel,
and offered him up to the Lord, she brought him to the house of the Lord in Shiloh,
and when she brought him, she took up with her three bullocks, besides flour and wine:
so see how she paid her vows to the Lord,
and offered up her sacrifices upon God`'s altar.
And other places might be shown of the women`'s offerings and sacrifices.

And you may see Hannah`'s fervent zeal to God,
and what a large speech she made in magnifying and exalting the Lord, in 1 Sam.
1st and 2d chapters.

And so you may see,
the offerings and sacrifices of the women were accepted upon God`'s altar,
as well as the men`'s.

But the hire of a whore was not to be brought into the house of God for any vow,
for it was an abomination to the Lord. Duet. 23:10.

Now Hannah`'s husband, and the other women`'s husbands,
that offered up their offerings upon God`'s altar, were not offended at them,
nor did they say, their offerings were enough for them both;
but every one was to offer up their peace-offerings and thanksgiving-offerings themselves,
and other offerings.

So here you may see the service and work of the women,
and how serviceable the women were in their assemblies in the time of the law,
about the tabernacle and holy things, and how the women offered upon God`'s altar,
as well as the men; they had their liberty.
But the hire

of the whore was to be kept out of God`'s house,
and not to be offered up upon God`'s altar.

So you may see man and woman were meet-helps in paradise, before the fall;
and death reigned from Adam till Moses, and after Moses received the law from God,
which went over death,
(and sin that brought it,) who saw the state of man and woman in paradise:
men and women in the time of the law were meet-helps again to one another,
in the work and service of the holy things about the tabernacle and sanctuary,
and the women had their assemblies.

And it is said,
in Joel 2. and in Acts 2. "`that the Lord would pour out
of his spirit upon all flesh in the last days or times.`"

So this spirit being poured upon all flesh in the christian times, sons and daughters,
handmaids and servants, old men and young men, that by the spirit of God,
all these might have his visions, prophecies and dreams: and this is his spirit,
by which all should profit in the things that be eternal, and to serve God in the spirit,
both men and women, sons and daughters, old men and young men, handmaids and servants;
all offer up to God his spiritual sacrifices.

For all being dead in old earthly Adam, Christ,
the heavenly Adam has tasted death for them all,
and is a propitiation for the sins of the whole world, and he enlightens all,
and his grace hath appeared unto all, and his spirit is poured upon all flesh,
and his gospel, which is the power of God, is preached to every creature under heaven.

And now, must not all receive the grace, and believe in the light,
and receive this gospel, and walk and labour in it, both men and women,
sons and daughters, old men and young, servants and handmaids.

Yea, I say, the gospel being preached to all nations, and to every creature under heaven,
old men and young, servants and handmaids, sons and daughters; I say,
then must not all these receive this gospel, and the light and grace?
and are they not all to walk in it?
and to offer up their spiritual sacrifices upon the heavenly altar, in the new covenant,
and to walk in the new and living way; and all to receive the light of Christ,
which enlightens all; and to become children of light,
and to feel the blood of Christ to cleanse them from all sin,
which they have in old Adam.

So as the women were to offer, in the old covenant, and in the time of the law,
upon the outward altar, their offerings;
and God poured out his spirit upon the house of Israel, that they might understand,
and do what he commanded them: at which time they had the assemblies of the women,
which were not forbidden.

So now, in the time of the gospel, and the day of Christ, which enlightens all,
and in the time of his grace, which hath appeared unto all men, to teach them,
and to bring their salvation; and in the time of his gospel preached to every creature,
and in the time of his pouring out of his spirit upon all flesh,
that they might understand, and walk, and live in his gospel,
and by his spirit offer up their spiritual sacrifices.

So, in this the time and day of Christ, the captain of our salvation,
must not all these labour in the gospel, and in the word, and in the grace,
and in the light,
and know and do God and Christ`'s work and service
about his heavenly tabernacle and sanctuary?
Hath not every one their service that are enlightened?
And his grace, that hath appeared unto them, are they not stewards of it?
And must not they have their assemblies of the women in the time of the gospel,
and of the new covenant, and in the time of grace, and light, and life,
as well as in the time of the law, and of the old covenant?

And are not all to labour in that which tends to God`'s glory, and praise, and honour?
For which end he hath made them all, and for which end he hath redeemed them,
and converted them, and translated and sanctified them,
to make them vessels of his honour, and of his grace and mercies.

And so now the end of all our men`'s and women`'s meetings in the time of the gospel,
(the power of Christ being the authority of them,) is,
that they might all labour in his power, and in his grace, and in his spirit,
and in his light, to do his service, and his business in truth and righteousness.

So the women in the time of the gospel, light, and grace,
are to look into their own selves and families,
and to look to the training up of their children;
for they are oft-times more amongst them than the men,
and may prevent many things that may fall out,
and many times they may make or mar their children in their education.

So now they come to be exercised in the grace of God, and to admonish and exhort,
reprove and rebuke, and to keep all their families modest, honest, virtuous, sober,
and civil, and not to give liberty, nor indulge that which tends to vice,
or lasciviousness, or any evil, or idleness, or slothfulness,
or the fashions of the world, which pass away; and to stop all vain words,
and idle talking, and stories, and tales, which are unprofitable;
but rather to turn their ears to godliness,
which they should be trained up and exercised in, and not to fulfill the lust of the eye;
for that being satisfied, brings the pride of life, and then comes the lust of the flesh;
and this is not of the Father, but of the world.

And if either men or women suffer such things,
they suffer that which defiles their children and families;
and therefore such things are to be reproved in families,
and their children to be stopped from going into such things.

And therefore they are to have an esteem of truth and virtue above all such things,
and not to indulge any such things as will draw out their minds from virtue to vice.

Now when the women are met together in the light, and in the gospel, the power of God;
some are of a more large capacity and understanding than other women,
and are able to inform, and instruct, and stir up others into diligence, virtue,
and righteousness, and godliness, and, in the love and wisdom of God,
to inform and reform their families,
and to help them that be of weaker capacities and understandings in the wisdom of God,
that they may be fruitful in every good work and word.

So that they may see that all their families are ordered to God`'s glory;
and that which tends to looseness or evil, either in words, ways, or actions,
that would corrupt them, either in their lives or manners,
may be kept down and reproved.

So that all their children and servants may be trained up in the fear of God,
in the new covenant; for among the Jews in the old covenant,
they that sojourned amongst them were to keep the sabbath,
and if they did eat of their sacrifice, they were to be circumcised.

And the women had their assemblies in the days of the judges and the kings;
and old Ely`'s sons abused them, and old Ely did admonish his sons,
but he did not restrain them from their wickedness; and therefore God cut off his sons,
and he lost the ark of God, and the priesthood, and his own life also.

So many of you may admonish your children,
but if ye do not restrain them by the help of the spirit of God,
which God hath given to you, you will quench the spirit of God in you, by indulging them;
so by that you will lose your spiritual offering, and your priesthood therein;
and take heed if you do not lose your own lives, and your children`'s also;
therefore mind old Ely for your example.

Now old Ely was not against the assemblies of the women, who assembled by troops,
as (in the margin of the bible) you may see, 1 Sam. 2:21-22.
though some men now-a-days may be against
women`'s meetings or assemblies in the gospel-times,
and against women`'s speaking or prophesying,
but they are ignorant of the universal spirit, and of their service and labour to God,
in his grace and gospel, and are of a narrow spirit,
and are not the true servers of God themselves; for if they were,
they would have all people to serve God in his power, and to keep the true religion,
which is to visit the fatherless and the widows,
and to keep themselves from the spots of the world.

And some there have been, that would not have the women to meet without the men;
and some of them say, the women must not speak in the church, and if they must not speak,
what should they meet with them for?

But what spirit is this, that would exercise lordship over the faith of any?
And what a spirit is this, that will neither suffer the women to speak amongst the men,
nor to meet amongst themselves to speak?

But all this is for judgment,
with that spirit that gives liberty unto all that labour in the gospel, in the light,
and in the grace.

And some men and women there are that suggest,
if women should meet (by themselves) in the order of the gospel, the power of God,
they would be too high: but such men and women, as so suggest, are too high already,
and would be ruling over men and women`'s possessions, and waste their own;
for if they were in the power and spirit of God,
they need not fear any one`'s getting over them.
For the power and spirit of God gives liberty to all;
for women are heirs of life as well as the men, and heirs of grace,
and of the light of Christ Jesus, as well as the men,
and so stewards of the manifold grace of God.

And they must all give an account of their stewardship, and are to be possessors of life,
and light, and grace, and the gospel of Christ, and to labour in it;
and to keep their liberty and freedom in it, as well as the men.

And they are believers in the light, as well as the men,
and so children of the light and of the day, as well as the men.

And so the assemblies of the women, whom God hath poured out his spirit upon,
are to be in the time of the gospel, as well as in the time of the law,
that they may be helps-meet to the men in the time of the gospel, in the restoration,
as they were in the beginning, and time of the law.

So all the women, (in all their assemblies in the time of the gospel,
and of the new covenant of light, life, and grace,) are to be encouraged,
as they were in the time of the law,
and to be stirred up in the wisdom of God to their
diligence and service of God and Christ,
in his new covenant, in his gospel time,
to do the Lord`'s business about the heavenly tabernacle, and heavenly garments,
as the women were about the figure in the time of the law.

And now, you that stumble at women`'s meetings,
had not your women many vain meetings before they were convinced,
and you were not then offended at them, when they met to satisfy the flesh,
and had junketing meetings to themselves; did you reprove them for such meetings?

And why should they not now meet in their conversion, in the Lord`'s power and spirit,
to do his business, and to visit the fatherless and widows,
and to keep themselves from the spots of the world,
which is the practice of the pure religion,
wherein the men and women may be helps-meet in the religion that is not of the world,
that keeps from the spots of the world.

But some have said, that such meetings must not be,
but as business requires or occasions them.
As much as to say,
you must not make up the hedges till the beasts have devoured your corn;
and then the parish overseers must meet together to compute the damage.
And here their wisdom is seen, as if it were not more their duty to meet,
to prevent bad actions that may fall out,
and with the power of God to stop up gaps to prevent evil, or weak places;
for when the evil is entered into, it is too late to meet then,
which rather brings scandal than remedy; and therefore the labourers in the gospel,
men and women,
(being helps-meet,) are to see that all walk and live in the order of the gospel,
and to see that nothing be lacking, then all is well.
For the women in their assemblies may inform one another of the poor widows and fatherless,
and in the wisdom of God may find the best way for the setting forth of their children;
and to see that their children are preserved in truth,
and to instruct them in the fear of the Lord.

And you may see the care of Abraham, about Isaac taking his wife; and the care of Sarah,
that the son of the bondwoman should not be heir with her son,
and how that he sent his servant, that spoke to the parents,
before he spoke to Rebecca the daughter, concerning the message of his master Abraham,
and they confessed it did proceed from the Lord, as in Gen.
24.

And also you may see the care of Rebecca concerning Jacob, who said,
'`If Jacob take a wife of the daughters of Heth, what good will my life do me?`"

And here you may see Isaac and Rebecca were helps-meet; and Isaac did not say,
hold thy tongue, thou foolish woman.
For Isaac exhorted Jacob, and charged him, not to take a wife of the daughters of Canaan;
as you may see in Gen.
27.

And when Rebecca was with child, the children struggled in her womb, and she said,
If it be so, why am I thus?
And she went to the Lord to inquire, and the Lord said unto her,
"`Two nations are in thy womb, and two manner of people,
and the elder shall serve the younger,`" etc. as in Gen.
25.

So you may see, that she had recourse to the Lord, and inquired of the Lord,
and he heard her and spoke to her, and she heard the Lord`'s voice.
She is an example to all women in that condition, to ask counsel of the Lord, as she did.

And when Sarah said to Abraham, "`Cast forth the bondwoman and her son;
for the son of the bondwoman shall not be heir with my son
Isaac;`" but this thing was grievous in Abraham`'s sight,
because of his son Ishmael.
But God said unto Abraham, "`Let it not be grievous in thy sight, because of the lad,
and because of the bondwoman; for in all that Sarah hath said unto thee,
hearken unto her voice; for in Isaac shall thy seed be called.`"

Here you may see God justified this honourable woman`'s speaking,
and her husband Abraham did according to her words, as in Gen. 21.
for the church was in Abraham`'s house at that time;
and so Sarah spoke in the church.

And you may see the counsel of Rebecca to Jacob, and how she instructed her son,
in chap 27, etc.

And likewise you may see Rachel and Leah their counsel to Jacob, who answered Jacob,
and said unto him,
"`Is there yet any portion or inheritance for us in our father`'s house?
Are we not counted of him as strangers?
For he hath sold us, and hath quite devoured also our money;
for all the riches which God hath taken from our father, that is ours,
and our children`'s; and now therefore, whatsoever God hath said unto thee, do.`"
This was Rachel`'s and Leah`'s counsel unto Jacob; and were not these three a church then?
And did he forbid them from speaking in the church?
see Gen. 31:14-16.

And in Exodus 1. there you may see the midwives, which feared God,
did not obey king Pharaoh`'s command, in destroying the male children,
but saved them alive.

And after that the king of Egypt sent for the midwives, and asked them,
"`Why they had done so, in saving the male children?`"
Yet these midwives, after he had thus examined them, and re-enforced his command,
yet they still disobeyed his command, and would not yield to his persecuting,
murdering decree; and therefore it is said, God dealt well with the midwives.

"`And it came to pass, because the midwives feared God, that he made them houses.`"

And here you may see the Lord took care for these honourable women that feared him.

And do ye think that these honourable women did not meet often together,
and took counsel together, to stand together,
and adventure their own lives and estates to preserve the lives of those male children?
Would you not say, if this were in your days,
that these were bold women to answer the king after such a manner,
and to disobey the king`'s commands thus?
as in Exod.
1.

And after the children of Israel came out of Egypt,
and saw the destruction of Pharaoh and his host; after Moses made an end of his song,
and praising of the Lord, then Miriam the prophetess, the sister of Aaron,
took a timbrel in her hand,
and all the women went out after her with timbrels and with dances, (mark,
all the women,) and Miriam answered them, and said, "`Sing ye unto the Lord;
for he hath triumphed gloriously,
the horse and his rider hath he overthrown in the sea,`" etc.

Now, here you may see what an assembly there was of the women, that praised the Lord,
who were instructed by Miriam the prophetess;
and Moses and Aaron were not offended at them; for they were sensible of their joy,
and were partakers of the deliverance and salvation, the women as well as the men;
as you may see in Exod.
15.

And Deborah, a prophetess, judged Israel,
and sent to Baruch and exhorted and encouraged him;
and she prophesied to him that he should not have the glory of the battle;
but that the Lord should sell Sisera into the hands of a woman;
as you may see in Judges 4.

Then sung Deborah and praised the Lord; and there you may see her large declaration,
in praising and magnifying the name of the Lord, the whole chapter throughout;
and how she said, "`Blessed be Jael above all women, the wife of Heber;
blessed shall she be in the tent,`" etc.
And we do not read that the elders did reprove her, or bid her hold her prating;
for she was filled with the power of the Lord to praise his name.
Judges 5.

And you may see how the apostle set forth the honourable women,
and their faithfulness and constancy, who by faith received the dead,
raised to life again, Heb. 11:35.

And Hannah, who prayed in the temple before Ely, as aforesaid,
who was ignorant of her condition, he reproved her, and thought she had been drunk;
but she convinced him; so that at last he encouraged her,
and desired the Lord to grant her petition: and when the Lord had granted it to her,
you may see how this honourable woman exalts the Lord, 1 Sam. 2:1 to the 10th.

And Ruth and Naomi, you may see what virtuous women they were,
and how the women blessed the Lord on their behalf,
and how they declared of the goodness of the Lord to them.

And Huldah the prophetess, who dwelt in Jerusalem, in the college,
where the king sent out the priest Hilkiah, and his scribe, and others,
to inquire of her.
Now the Jews here did not despise communication with a woman.
And she instructed the priest and the king`'s scribe, who came to her.

So neither king nor priest did despise this prophetess`'s teaching and instruction,
but obeyed it, as you may see what a large sermon she preached to them,
in 2 Kings, 22. from 14 to the end.

And you may see Abigail, that honourable woman`'s wisdom,
how she saved her family and her house from destruction.
Yet she did not go to ask her husband (old churlish Nabal) at home, but she,
who was innocent and wise, took it upon herself;
and you may see what a brave sermon she preached to David, who heard her patiently;
and she told David, how that "`he was bound up in the bundle of life with the Lord God.`"
And David blessed the Lord God that she came to him, and said,
"`the Lord God of Israel had sent her that day to meet him;`" and said,
"`Blessed be thy advice,
and blessed be thou who hast kept me this day from
shedding blood;`" as you may read in 1 Sam. 25.
And was not this a noble and honourable act of this woman,
which prevented so much evil and bloodshed,
which her husband had like to have brought upon them?
So David did not despise the counsel of this honourable woman,
who was wiser than her husband Nabal.

And now, must not the virgins, in the time of the gospel, trim their lamps,
and get oil into their own lamps, by labouring in the grace, light, and power of Christ,
and keep their lamps trimmed and always burning.

In the time of the law it was Aaron the priest`'s office;
but in the time of the gospel all the virgin minds must trim their lamps,
that their lamps may burn the clearer;
and to see that they have oil in their lamps from the heavenly olive tree, Christ Jesus.

And therefore, they that would not have the virgins and women to be diligent,
serving the Lord in his heavenly business and service, their lamps are going out,
and they are become fools, and would have others like themselves.

And the Lord sent Elijah in the time of the famine, and said unto him, "`Behold,
I have commanded a widow woman to sustain thee;`" and he arose, and went to Zarephath,
and when he came to the gate of the city,
the widow woman was gathering sticks to make a fire, to bake her a cake,
who had but one handful of meal and a little oil in a cruise,
and yet in faith she made the man of God a cake, though she had no more than this,
that she and her son might eat and then die; but her meal wasted not,
nor her cruise of oil, according to the word of the Lord;
and so the Lord blessed this woman, as you may see in 1 Kings 17.

And in the 2d of Kings and the 4th, there you may see the faith of the widow woman,
and how largely she spoke unto the prophet Elisha,
and how the Lord increased her stock of oil through her belief and faithfulness.

And Elisha passed unto Shunnim, where there was a great woman,
and she constrained him to eat bread; and so it was, as oft as he passed by,
that he turned in thither to eat bread; and she said unto her husband, "`Behold,
now I perceive, that this is a holy man of God, which passes by us continually;
let us make him a little chamber, I pray thee, on the wall,
and let us set for him there a bed, and a table, and a stool, and a candlestick,
and it shall be that when he comes to us, that he shall turn in thither.`"
Now to this good action of this holy woman was her husband subject;
and how she was blest afterwards for her faithfulness, and receiving of the man of God!

Now the prophet of the Lord did not despise this woman`'s speaking,
in the time of the law.

Neither did Solomon despise the prophecy his mother taught him.
Prov.
31.

And David said, "`The Lord gave the word,
and great was the company of those that published it.`" Ps. 68:11.

And the king`'s daughter was among the honourable women.
So there were the honourable women, that feared and served the Lord God,
in the time of the law, and before the law.

But now there should be much more in the time of the gospel,
which is preached to every creature;
which gospel-light has enlightened every man that cometh into the world;
and in the time of the covenant of grace, which hath appeared unto all men,
to teach them, and bring their salvation.
And so in the time of the gospel, light, and grace,
the honourable women should be meet-helps,
and fellow-labourers together in the work and service of the Lord,
as man and woman was before they fell, and as they were in the time of the law.

For that honourable Deborah, which was a valiant mother in Israel,
was a judge and a prophetess.
Judges 5.

And Jephtha`'s daughter, was not she a virtuous young woman?
and see what a sermon she preached to her father, and said to him,
"`Let me go up to the mountains to bewail my virginity:`" and he said unto her, go;
and she went and her companions, fellow-virgins: and she said unto her father,
as thou hast opened thy mouth unto the Lord,
so do unto me according to what hath proceeded out of thy mouth,
forasmuch as the Lord hath taken vengeance for thee of thy enemies.

And the daughters of Israel went yearly to lament the daughter of Jephtha.
Judges 11.

So here they had a Yearly Meeting upon this occasion:
but the assemblies of the women about the works and services the Lord commanded,
was beyond this.

And Manoah, Samson`'s mother, unto her the angel of the Lord appeared,
and declared unto her great things, which she declared unto her husband,
but her husband did not reprove her;
and when her husband was in fear that they should die, then his wife encouraged him,
saying, "`If the Lord were pleased to kill us,
he would not have received a burnt-offering, and have showed us all these things.`"

And here you may see the steadfastness of this woman`'s faith, beyond her husband`'s,
as in Judges 13.

And the woman of Tekoah, see what a sermon she preached to king David.
2 Sam.
14.

And you may see what a large sermon the woman of
the city of Abel preached unto Joab the general;
she told him, she was one of them that were peaceable and faithful in Israel;
and thou seekest to destroy a city and a mother of Israel;
why wilt thou swallow up the inheritance of the Lord?
So she convinced him and preserved the city.

And so these and such women are recorded to posterity for their wisdom, and their virtue,
and zeal, and their faith, as you may see in the 2d of Samuel and the 20th.

And what think you of Esther?
read her book, and see the behaviour of this virtuous honourable woman,
who by her wisdom, faith, and virtue, preserved her people Israel;
she was a nursing-mother to them; as you may read in the book of Esther,
who kept a fast with her maidens to the Lord,
and also desired Mordecai to keep a fast in Shushan. Esther 4:16.

Now, all you careless women, that are out of God`'s service,
and think ye have no need to be in the service and work of the Lord,
hear the word of the Lord, what Isaiah says to such: "`Arise up, ye women,
that are at ease; hear my voice, ye careless daughters, give ear to my speech;
many days and years shall ye be troubled, ye careless women; for the vintage shall fall,
and the gathering shall not come.`"
Nor you cannot expect it in your ease and carelessness,
that neglect God`'s voice and speech, and are not diligent;
your heavenly vintage will fall, and of it ye will have little gathering.
"`Tremble, ye women, that are at ease; be troubled, ye careless ones; strip ye,
make ye bare, gird sackcloth upon your loins,`" etc.
Isaiah 32. Therefore put off that careless garment, and shake off sloth,
and put on diligence in the service of God.

Now, the Jews had their assemblies of mourning-women;
and therefore the prophet calls for the mourning-women, and let them bewail, says he,
when the Jews went into transgression.

And this was because the men and women were not diligent in his service,
in the power and spirit of God, which he had poured upon them.

And Jeremiah says, "`Hear the word of the Lord,
O ye women! and let your ears receive the word of his mouth,
and teach your daughters wailing, and every one their neighbours lamentation.`" Jer. 9:20.

So, here the prophet exhorts the women, to hear the word of God first,
and then to teach and exhort their daughters and neighbours, yea,
wailing and lamentation.

And were they not, and are they not,
to teach their families and their neighbours from the word of the Lord,
both in the time of the law and the gospel, to prevent wailing and lamentation.

And see in Ezekiel, how he exhorted, and what the Lord says there;
I will cause lewdness to cease out of the land,
that all women may be taught not to do after their lewdness.

And then, as they are obedient to this teaching,
they will shun the judgments that came upon the Jews, which were compared to women;
as in Ezek. 23.
And the assemblies of the women did continue
amongst the Jews till they went into captivity.

And when Saul and David had made a great slaughter upon the Philistines,
the women came out of all the cities of Israel (mark, out of all the cities of Israel;
and surely this was a great assembly of women) singing and dancing, etc. with joy,
and with instruments of music; and the women answered one another as they played,
and sung praises unto God.

And Saul the king was not angry with the women, but at David,
because they ascribed so much honour to him;
for they were partakers of the salvation of the Lord, and of the deliverance,
as well as the men. 1 Sam. 18:6.

And so they are partakers in the gospel, of the deliverance over the devil,
the grand enemy of mankind: and are exhorted to praise the Lord,
and to make melody in their hearts to the Lord,
for their salvation and deliverance by Christ, in the time of the gospel,
as well as the men. 1 Sam. 18.

And in 2 Chron. 25. there Jeremiah lamented for Josiah,
and all the singing-men and singing-women spoke of Josiah in their lamentation.

So here were not only singing-men, but singing-women,
which did not only sing but lament for this good man Josiah.

And in the days of Ezra, after the Jews returned from their captivity to their land,
there were two hundred singing-men and singing-women.
Ezra 2.

And in Neh. 7. where the priest stood up with Urim and Thummim,
(that is, light and perfection,) they had two hundred and forty-five
singing-men and singing-women.

So these were encouraged by the priests, according to David and Solomon`'s order;
and these were besides the assemblies of the women,
about works and services in the holy things; for these sung praises to God.

And in Zeph. 3. he saith,
"`Sing, ye daughters of Zion, shout and rejoice with all thy heart,
ye daughters of Jerusalem; the Lord hath taken away thy judgment,
etc. the Lord is in the midst of thee, thou shalt see evil no more.`"

And in Zech. 2. he encourageth them,
to "`sing and rejoice, O daughter of Zion; for, lo I come,
and I will dwell in the midst of thee, saith the Lord.`"

So here is great cause for the daughter of Zion to rejoice; and who shall stop her mouth?

And in Luke 1. you may see,
how the angel of the Lord appeared unto Mary the mother of Jesus,
and what he said to her, and what a noble virtuous mind was in her;
and she said unto the angel, "`Behold the handmaid of the Lord,
be it unto me according to thy word;`" so her belief was beyond Zachariah`'s the priest.

And when Mary came unto Elizabeth, what a meeting and salutation was there;
and how she was filled with the holy ghost, and the babe leaped in her womb,
and she praised the Lord God, and called her the mother of the Lord.
Read from the 40th to the 57th verse, and see how she extols the Lord,
and magnifies Christ Jesus; for here was a heavenly meeting of these two,
which is chronicled to ages.

So you may see her belief was above Zachariah`'s the priest.
So Mary and Elizabeth were notable preachers of Christ Jesus.

And you may see in Luke 2:7. how Mary wrapped Christ in swaddling-clothes,
and how tender she was of the heavenly birth, conceived by the holy ghost.
And so must all true and tender christians, that receive him in the spirit:
and how she kept all the sayings that were spoken of Christ,
and pondered them in her heart.
Verse 19. And so should every true christian.

And there was Anna a prophetess, which was eighty-four years old,
who departed not from the temple, but served God with fasting and prayer night and day,
"`and she gave thanks unto the Lord,
and spoke of Christ unto all that looked for redemption in Israel;`" she spoke of Christ.
Here was a notable old woman of eighty-four years of age,
a preacher and declarer of Christ.

And you do not read that ever any despised her, or said,
it was forbidden for a woman to speak in the church.

But this woman is set forth for an example to all young and old women,
of her love to Christ her saviour; and not only so,
but a preacher of him to all that looked for redemption in Israel.

And the woman of Canaan that came unto Jesus, and said, "`Lord,
help,`" but he answered and said,
"`it is not meet to take the children`'s bread and cast it unto dogs;`" and she said,
"`truth, Lord, yet the dogs eat of the crumbs which fall from the master`'s table.`"
Then Jesus answered and said unto her, "`O woman! great is thy faith,
be it unto thee even as thou wilt.`"

So you may see, by this woman`'s faith in Christ Jesus,
this woman`'s daughter was made whole,
which was an example for all the faithful to look unto Jesus for help,
as you may see in Matt. 15.

And Mary, that took a pound of ointment of spikenard, very costly,
and anointed the feet of Jesus, and wiped his feet with her hair;
and the whole house was filled with the odour of the ointment.
But when Judas saw it, he had indignation, saying, "`What profit is this waste?
Why was not this ointment sold for three hundred pieces of silver,
and given to the poor,`" as you may see in Matt. 26. and Mark 14. and John 12.
Now this was Judas, who carried the bag,
and betrayed Christ; and many there are that carry the bag now,
that would not have their wives nor the women bestow any thing upon Christ,
nor his poor followers.

But Jesus said, '`Let her alone, why trouble you her?
She hath wrought a good work on me; for the poor ye have with you always,
and whensoever ye will, ye may do them good, but me ye have not always;
she hath done what she could; she is come beforehand to anoint my body to my burial.
Verily I say unto you, wheresoever this gospel shall be preached throughout the world,
this also that she hath done shall be spoken of, for a memorial of her.`"

So Christ did not forbid the woman`'s practice, but encouraged her,
and so he doth still them that obey him.

And the woman that was twelve years troubled with an issue of blood,
who had spent all upon physicians, and grew worse and worse; her faith was so strong,
that she believed, if she could but touch the hem of his garment, she should be well.

And as soon as she had touched his clothes, virtue went from Christ and healed her;
and then the woman came fearing and trembling, and fell down before Christ,
and told him all the truth, what she had done; and he said unto her, "`Daughter,
thy faith hath made thee whole; go in peace.`"
Mark 5.

Now Christ, who is the head of the church, here suffered a woman to speak before him,
from whom she had received the healing virtue.

And you may see when Christ was crucified, how many women were there, as Mary Magdalene,
and Mary the mother of James, and many others which came up to Jerusalem,
that were about Jesus at the time of his being crucified, as in Mark 15.

And Mary Magdalene, and Mary the mother of James, came to the sepulchre,
and the angel said unto them, "`Be not afraid: ye seek Jesus of Nazareth,
which was crucified: he is not here, he is arisen: behold the place where they laid him.
But go your way, tell his disciples and Peter, that he goeth before you into Galilee,
there shall you see him, as he said unto you.`"
For Jesus appeared first, viz. to Mary Magdalene, as in Mark 16.

And in John 20. it is said, the two angels said to Mary, "`Woman, why weepest thou?`"
And she said, "`Because they have taken away my lord,
and I know not where they have laid him;`" and when she had thus said,
she turned herself, and saw Jesus standing, and knew not that it was Jesus, etc.
But Jesus said unto her, "`Mary,`" and she turned herself, and said unto him,
"`Rabbi,`" (as much as to say, master,) And Jesus said unto her, "`Touch me not;
for I am not ascended yet unto my Father; but go unto my brethren, and say unto them,
I ascend unto my Father, and your Father; and to my God, and your God,`" etc.
And Mary Magdalene came and told the disciples, that she had seen the Lord,
and that he had spoken these things unto her.

So here Mary Magdalene was a messenger of Christ Jesus,
who did not despise her speaking before him, who was the head of the church,
nor did not refuse to send her to preach his resurrection to his disciples,
though she was a woman.

And in Luke 24. it is said, it was Mary Magdalene, and Joanna,
and Mary the mother of James, and other women who were with them, who told the apostles,
that Christ was risen; and this was said unto them,
"`Why seek ye the living among the dead?
He is not here, he is risen.
Remember that he spoke unto you, when he was yet in Galilee, saying,
the son of man must be delivered into the hands of sinful men,`" etc.

And they remembered these words, and they returned from the sepulchre,
and told all these things unto the eleven disciples, and all the rest.

And mark, as I said before, it was Mary Magdalene, and Joanna,
and Mary the mother of James, and other women that were with them,
which told these things unto the apostles;
and these words seemed unto them as idle tales, and they believed them not.

Now mark their message, and to whom it was, and who they were that were the messengers,
the weaker vessels, and to whom, to the apostles; and what they preached was,
what they remembered Christ had spoken to them before, to wit, that Christ should suffer,
and rise again.

And Christ appeared again unto two of his disciples, and he talked with them,
and asked them, "`What communication they had?`"
And they said unto him, "`Art thou a stranger in Jerusalem,
and knowest not the things that have befallen,`" etc.
And he said unto them, "`What things?`"
And they said unto him, "`Concerning Jesus of Nazareth, that was a great prophet,
and mighty in deed and in word, before God and all people, which the Jews have crucified;
but they trusted he should have redeemed Israel; and besides all this,
today is the third day since these things were done.
And certain women also of our company made us astonished,
which were early at his sepulchre; and when they found not his body, they came, saying,
that they had seen a vision of angels, which said, he was alive.`"

So here the woman`'s testimony of the resurrection of Christ astonished them.

And Jesus said unto them, "`O fools,
and slow of heart to believe all that the prophets have spoken!
Ought not Christ to have suffered these things, and to enter into his glory?`"
etc.

Now here you may see it was Mary, and Joanna, and Mary the mother of James,
and the other women that were with them,
that declared the resurrection of Christ unto the eleven,
which seemed but as idle tales to the apostles.

And here was a joyful women`'s meeting indeed,
of messengers and preachers of Christ`'s resurrection,
which is recorded to posterity to their renown, that all should believe;
though their message and speech were as idle tales to the disciples;
but they were owned by Christ the head of the church, as aforesaid,
though their preaching was slighted by the apostles, and counted as idle tales;
but they came to believe afterwards, as in Luke 24.

And the woman of Samaria, that Christ Jesus convinced,
and taught her how God was to be worshipped, to wit, in the spirit and truth;
you may see what a large discourse Christ had with her,
as in John 4. from the 7th to the 27th,
and suffered her to speak before the head of the church.

And Christ`'s disciples marvelled that he talked with a woman;
and the woman left her pitcher of water, and went away into a city of Samaria,
and said unto the men of the city, (mark,
unto the men,) "`Come and see a man that told me all that ever I did,
is not this the Christ?`"
And many of the Samaritans believed because of the saying of the woman, which testified,
"`He told me all that ever I did.`"
And when they heard Christ, they said unto the woman, "`Now we believe,
not because of thy saying only, but we have heard him ourselves,
and know that he is indeed the Christ, the saviour of the world.`"

So here you may see, there was a woman preacher,
that Christ (the head of the church) suffered;
and through her means many were converted unto Christ.

And when they had crucified Jesus Christ, there were many women that beheld him afar off,
which followed him from Galilee, ministering unto him, amongst which were Mary Magdalene,
and Mary the mother of James, and Joses the mother of Zebedee`'s children.

And here you may see, there was a women`'s meeting with Christ, in his sufferings, which,
when he was risen, some of them preached his resurrection,
as you may see in Matt. 27:61 and chap.
28:5-7. where you may read the message Christ gave to the women,
to declare to the apostles, as aforesaid, which is recorded and set forth,
that others might believe their message.

And when Christ spoke in reproof to the Jews, he said, "`I tell you of a truth,
many widows were in Israel in the days of Elisha,
etc. but to none of them was Elisha sent, save to Zarephath, a city of Sidon,
unto a woman that was a widow,`" etc.
And the Jews arose up, and thrust Christ out of their city,
being filled with wrath against him, for this saying, and his reproving of them.

And you may read at large the acts, doings, and sayings of this faithful woman,
in 1 Kings 17:9. and Luke 4.

And in Luke 7. Christ turned him to the woman, and said unto Simon, Seest thou this woman?
I entered into thy house, but thou gavest me no water for my feet;
but she hath washed my feet with tears, and wiped them with the hair of her head.
And thou gavest me no kiss; but this woman, since the time I came into the house,
hath not ceased to kiss my feet.
My head with oil thou didst not anoint;
but this woman hath anointed my feet with ointment.
Wherefore I say unto thee, her sins, which are many, are forgiven; for she loved much;
but to whom little is forgiven, the same loved little.`"

And they that sat at meat with him began to say, "`Who is this forgiveth sins?`"
and he said unto the woman, "`Thy faith hath saved thee; go in peace.`"

So here you may see how Christ justified the woman`'s actions above Simon,
whose faith saved her; which is chronicled to her renown, and the honour of God.
And in Matt. 28. there you may see this Mary Magdalene,
who was a preacher of Christ, it was she,
out of whom Christ had cast out seven devils; and with her Joanna, the wife of Chusa,
Herod`'s steward, and Susanna, who ministered unto Christ of their substance.

Now, would not some niggards be ready to say,
these women picked their husbands`' pockets; and others, with Judas, who carry the bag,
may say, we must have but one purse, and is not our gift and benevolence sufficient?
as in Matt. 28. Luke 24.

But this woman loved Christ; and Christ said, "`My mother and my brethren are these,
which hear the word of God and do it.`" Luke 8:21.

"`And Martha received Christ into her house, and she had a sister called Mary,
that sat at Jesus`' feet, and heard his words;
but Martha was cumbered about much serving;`" and Jesus said unto her, "`Martha,
thou art caring and troubled about many things, but one thing is needful,
and Mary hath chosen that good thing, which shall not be taken away from her.`"
Which is the duty of every good man and woman to do,
if they will be kept out of the many things.
And you may see how Mary talked with Christ, and Christ with her.

So this is chronicled, that all might choose the good part, and the one thing,
which cannot be taken away from them; and to be kept out of the many things that cumber,
as you may see in Luke 10.

And doth not Christ say, "`The kingdom of heaven is like unto leaven,
which a woman took and hid in three measures of meal, till all the lump is leavened?`"
So, must not every man and woman know this leaven in their hearts,
if they will know the kingdom of Christ?
Luke 13.

And the parable of Christ, concerning the woman that lost her piece of silver,
who lighted a candle and swept her own house, and found it in her own house;
and when she had found it, she rejoiced, and told her neighbours.
And must not every woman light her own candle at the light of Christ Jesus,
and sweep her own house with the power of God, before she finds God`'s treasure?
And then for joy that they have found it,
go and declare it unto their friends and neighbours?
And do not all those women that have found this,
preach Christ to their friends and neighbours, and call them together?
For may they not be suffered after they have lost an outward treasure,
and found it again, to call their neighbours together to rejoice with them,
which they may find by lighting an outward candle?
But their spirits being the candle of the Lord,
this must be lighted at the heavenly light and fire,
by which their everlasting treasure is found;
and must not they say then to their neighbours and friends, rejoice with me,
for I have found the piece which was lost?
"`Likewise, I say unto you,`" saith Christ,
"`there is joy in the presence of the angels of God,
over one sinner that repenteth;`" as you may see in Luke 15.

Now, here you may see all these renowned, faithful women,
were encouraged by Christ and his followers;
and are recorded and set forth to encourage all that are faithful to wait upon Christ,
and to light their candle at God`'s light and fire,
that so they may sweep their house and find their treasure,
that they may declare their joy of it to their friends and neighbours.

And also you may see Dorcas was full of good works, and alms-deeds which she did:
"`and all the widows stood by Peter weeping,
showing the coats and garments which Dorcas made, whilst she was with them,`" (to wit,
the widows:) mark, and was not there a women`'s meeting then?
whilst Dorcas was with them; to wit, the widows; and Dorcas was a disciple of Jesus.
Acts 9.

And Paul on the sabbath went out of the city by a river side,
where prayers were wont to be made, and spoke to the women who resorted thither;
and was not there a women`'s meeting also, who resorted there to pray together?

And there was a certain woman named Lydia, a seller of purple, of the city of Thyatira,
who worshipped God, whose heart the Lord opened,
that she attended unto the things spoken by Paul,
and she besought him to come to her house, if he judged her faithful to the Lord,
and abide there, and she constrained him and them that were with him.
Acts 16. So you may see the faithfulness of this woman,
and the practice or the other women before they were converted.

And Priscilla, who was a notable faithful woman,
whom Paul often mentions with her husband Aquilla; and Philip`'s four daughters,
who were prophetesses, who were set forth to encourage others.
And you may see Phebe,
whom the apostle Paul sends his epistles to the Romans from Corinth by,
and calls a servant of the church of Cenchrea; and he saith, "`Greet Mary,
which bestowed much labour upon us; and Priscilla and Aquilla,
my fellow-labourers in Christ Jesus.`"

So here you may see there were women labourers and helpers in the gospel.
And he farther saith, "`I commend unto you our sister Phebe,
who is a servant unto the church,`" etc.
And saith, "`Priscilla and Aquilla, my fellow-helpers in Christ Jesus,
which for my life have laid down their necks, unto whom not only I give thanks,
but also all the churches of the Gentiles.`"

So here you may see in what esteem were this man and woman, and Phebe, and other women,
for their faithfulness to the churches; as you may read, Rom.
16.

And the apostle saith,
"`that the unbelieving husband is sanctified by the believing wife,`" etc.
"`else their children were unholy; but now they are clean;
and the unbelieving wife is sanctified by the believing husband:`"
so here is an equal share in the belief. 1 Cor. 7.
And the apostle saith,
that every woman that prayeth or prophesieth with her head uncovered,
dishonoureth her head.`"

So women may pray and prophesy here, according to order, in the church,
as well as the men. 1 Cor. 11.
And yet the same apostle in the 14th chapter, forbids a woman to speak in the church.

And the apostle saith,
"`Let the women keep silence in the church;`" and "`if they will learn any thing,
let them ask their husbands at home.`"

But when they have learnt of Christ their husband at home,
they are not forbidden of Christ from prophesying or praying;
but to lie babbling and prating in the church, such speaking in the church is a shame.

Now a widow hath no husband to ask but Christ; nor a virgin, yet she may prophesy;
and a believing woman, that hath an unbelieving husband, he is to be sanctified by her:
so she is not to learn her salvation of him, but of Christ, and to do his work.

And the same apostle saith, "`Let the men keep silence in the church,
if they speak an unknown tongue, and there be not an interpreter.`"
So, here the men must keep silence in the church in this case, as well as the women.
1 Cor. 11. and chap. 14. 27.

And the apostle further saith, "`I permit not a woman to speak in the church,
but to be under obedience;`" as also saith the law.

But though the law did not permit their usurping authority in the church,
yet it did permit their prophesying in the church, in the time of the law,
as well as in the time of the gospel;
as you may see by those famous women before mentioned, in the Old Testament,
as well as in the New.

And the same apostle saith, "`I beseech thee, Euodias, and I beseech Syntyche,
that they may be of the same mind in the Lord; and I entreat thee also, true yokefellow,
help those women which laboured with me in the gospel; with Clement also,
and with other my fellow-labourers, whose names are in the book of life.`"

So here the apostle entreated his yokefellow to help
those women who laboured with him in the gospel,
the power of God:
so these women were meet-helps with the apostle in the labour of the gospel,
(the power of God,) as you may see in Phil.
4+++.+++ And all that be of his mind in the Lord, will encourage either women or widows,
or virgins, that have received the gospel, to labour in it;
and all that have not the mind of the apostle in the Lord,
will discourage women`'s labouring in the gospel, and not entreat others to help them;
but such will give them liberty to labour in the power of darkness, and to slothfulness,
and carelessness; which the woe is unto, and not the blessing.

And again, the apostle writes to Timothy,
"`that the women should adorn themselves in modest apparel, and shamefacedness,
and sobriety, not with broidered hair, or gold, or pearls, or costly array,
but which becomes women professing godliness, with good works;
and let your women learn in silence with all subjection, etc.
But I suffer not a woman to teach nor to usurp authority over the man;
but learn in silence, etc.
For the woman being deceived, was first in transgression,`" etc.

Now for a woman to preach or teach, such a teaching as Eve taught Adam,
such a sermon as she had from the serpent, that drew herself, and Adam her husband,
from God`'s teaching; here, in this teaching, she usurped authority over the man;
and therefore God set the man to rule over the woman; but they were meet-helps before,
while they were under God`'s teaching.

Now, to usurp authority over the man by such teaching, is out of the unity;
which teaching is forbidden both by law and gospel; and they are not fit to teach,
if they have not learned subjection to the spirit of God,
and know the silence of all flesh before the Lord,
and have not learned to adorn themselves with that which is modest,
and the lesson of sobriety, which becomes godliness; and with the good works,
the fruits of the spirit.

And such women as have learned this lesson may teach and prophesy;
for the spirit is poured upon them to that end.

And the same apostle saith, 1 Tim. 5.
"`that the elder women should be as mothers;`" and a mother is a nurser,
and a teacher, and instructor of her children; "`and the younger women as sisters,
with all purity;`" and sisters in Christ and in purity, all have but one father;
and a sister is in the unity, in the spirit, in the gospel. 1 Tim. 5.
"`And if any woman that believes have widows, let them relieve them.`"
So here was the woman`'s work, to relieve their widows, etc.

And again, the apostle writes to Titus, and saith unto him,
"`Speak thou the things which become sound doctrine, etc.
The aged women, that they be of good behaviour, as becometh holiness; not false accusers,
not given to much wine; teachers of good things.`"

Now here they must be qualified before they can be teachers of those good things.

And that these aged women teach the younger women; first, to be sober; secondly,
to love their husbands; thirdly, to love their children; fourthly, to be discreet;
fifthly, to be chaste, and keepers at home, and good, obedient to their own husbands,
that the word of God be not blasphemed.

Now here the aged women, not a woman, but the aged women,
were to teach the younger women these things.

And how could these women be teachers of all these virtues and good things,
if these mothers and holy women did not meet together,
and converse together of holiness and virtue; as in Tit. 2.

And in 1 Pet. 3. he encourageth wives and women,
that if their husbands will not be won by the word,
they may without the word be won by the chaste conversation of the wives;
"`whilst they behold your chaste conversation,`" saith he, "`coupled with fear;
and whose adorning,`" saith he, let it not be that of the outward,
with plaiting of the hair, or wearing of gold, or putting on costly apparel,
but let it be the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,
which is in the sight of God of great price.`"

And this, he saith, was the ornament of the holy women in the old time,
with which they adorned themselves, who trusted in God, as Sarah, etc.
"`whose daughters ye are, as long as ye do well, and are not afraid with any amazement.`"

And likewise the believing husband, and the believing wife,
are heirs together of the grace and life.

And therefore the believing women being heirs of grace and life, as well as the men,
they may impart of their life, which they do inherit, as well as men;
for an heir of life is beyond an heir of the earth.

And there is no believing husband will hinder his believing wife, being heirs of life,
to administer some of their temporal things to them that are in necessity;
he will not have all the earth to himself, but let her have the disposing of some of it,
as well as himself, whilst they do enjoy it;
and ministering of outward things is the least love.
And women many times know the condition of poor families, and widows,
and such as are in distress, more than the men,
because they are most conversant in their families, and about such things.

But there are many idle talkers, and busy bodies,
that are out of the sense and service of God, that will not do good themselves,
nor suffer others to do their service of love and charity for the Lord in the church.

And John writes in his second Epistle unto the elect lady and her children,
"`whom I love in the truth,`" saith he, "`and not I only,
but also all they that have known the truth, for the truth`'s sake, which dwelleth in us,
and shall be with us forever, etc.
I rejoice greatly,`" says he, "`that I have found thy children walking in the truth.`"
And further saith, "`I write no new commandment unto thee,
but that which we had from the beginning, that we love one another.`"

And so he trusts to come and see her, and speak face to face unto her;
"`the children of thy elect sister greet thee.`"
Amen.

So was not this an honourable woman, that had trained up her children in the truth,
as was commanded by John?
And he admonished her against such as did transgress,
and did not abide in the doctrine of Christ Jesus,
that they had not the Father nor the son;
but they that did abide in the doctrine of Christ Jesus,
had both the Father and the son.

So is not this an encouragement to all faithful women,
to see that their children do walk in the truth, and abide in the doctrine of Christ,
that they may have both the Father and the son?

And farther Solomon saith, "`A gracious woman attains honour,
and a virtuous woman is a crown to her husband,
and every wise woman buildeth her own house.`"
Surely then she hath a work to do.
He that hath ears let him hear.
"`But the foolish woman plucketh it down with her hands.`"
And there are too many of those that are in the transgression
of the spirit and power of God,
with which they must build.
"`But a woman that feareth God, she shall be praised; give her of the fruit of her hands,
and let her works praise her in the gates.`"
And then surely she hath a work to do, that must praise her in the gates.

"`She stretcheth forth her hands to the poor; yea,
she reacheth forth her hands to the needy.`" Prov. 31.
And must she not then have something of the outward to do it withal?

"`She opens her mouth in wisdom, and in her tongue is the law of kindness.
She looks well to the ways of her household, and eateth not the bread of idleness.
She is like the merchant`'s ship, she bringeth her food from far;
she riseth also whilst it is night, and giveth meat to her household,
and portions to her maidens; she considereth a field,
and buyeth it with the fruit of her hands; she planteth a vineyard;
she girdeth her loins with strength, and strengtheneth her arms;
she perceiveth that her merchandise is good; her candle goeth not out by night,`" etc.

And here is an example to all women, a pattern of virtue, and of fruitfulness,
and faithfulness, and valour, and practice in the Lord`'s work;
and such their children will rise up, and call her blessed.
"`Many daughters have done virtuously,
(says he,) but this woman excelleth thern;`" that is, the nurse of them.

And now friends, many of other examples in the scriptures might be showed,
to encourage women`'s meetings in the service of God and Christ,
both concerning their faithful testimony for the Lord and Christ,
and their encouragement by the faithful in the old and new testament,
how that they had their assemblies and their meetings.
And now they being heirs of life, and of grace, and of the gospel of Christ,
which hath brought life and immortality to light,
you may see over him that has darkened you, and before he was.

Therefore this gospel, the power of God, which is the everlasting orderer,
is to keep you in life and immortality,
that you may be meet-helps in the power and image of God to the men,
as man and woman were in before they fell.

So, to administer of the heavenly and temporal refreshments, to such as want it;
and to stand up for your liberty in the light, and life, and grace, and glorious gospel,
being heirs of life, and grace, and of the gospel of salvation, and of Christ Jesus,
as well as the men.

So that all, males and females, are one in Christ Jesus, who is the first and last,
and over all from everlasting to everlasting, your everlasting joy, peace, and happiness.

And if there was no scripture for our men and women`'s meetings, Christ is sufficient,
who restores man and woman up into the image of God,
to be helps-meet in the righteousness and holiness, as they were in before they fell.
So he is our rock and foundation to build upon.

"`Wisdom hath sent forth her maidens, she crieth upon the high places of the city,
whoso is simple, let him turn in hither; as for him that wanteth understanding,
she saith to him, come, eat of my bread, and drink of my wine, which I have mingled;
forsake the foolish, and live, and grow in the way of understanding.`"

Here you may see the wisdom of God sends forth maidens,^
footnote:[True ministers, who are chaste to Christ.]
though the wisdom of the world will not receive them,
(that make ministers by their wisdom,) and such as will not receive wisdom,
will not receive her maidens. Prov. 9:1-3.

The Lord saith, "`I will pour out upon David, and upon the inhabitants of Jerusalem,
the spirit of grace and of supplication,
and they shall look upon me whom they have pierced, and mourn, etc.
In that day there shall be great mourning, the house of David apart,
and their wives apart; the house of Nathan apart, and their wives apart;
the house of Levi apart, and their wives apart; the family of Shimei apart,
and their wives apart; all the families that remain, every family apart,
and their wives apart.`" Zech. 12:10.

And this would be madness to all them that are not in that spirit;
but here every one hath the sense of Christ, whom they have pierced in the spirit,
which is poured upon them, but the hard-hearted are not sensible.

[.signed-section-signature]
G+++.+++ F.

Marshgrainge, the 16th of the 9th month, 1676.
