== Letters 321 &#8212; 343

[.centered]
=== Letter 321.

[.blurb]
==== To all the men and women`'s meetings that are gathered in the name of Jesus. Several scripture testimonies to the saints`' practices, wherein all may see the practice of the holy men and women of God, in their services in the church of Christ, and what good works, and practices, and services, they exhorted unto, as followeth, as you may see both in the Old and New Testament, which is the duty of all true christians to follow.

Who gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people, zealous of good works. Titus 2:14.

The woman wrought a good work upon Christ, as he saith. Matt. 26:10.

Paul saith to the church of the Colossians, being fruitful in every good work,
and increasing in the knowledge of God. Col. 1:10.

And that you may be established in every good word and work. 2 Thess. 2:17.

She (to wit, a widow) well reported for her good works. 1 Tim. 5:10.

That the church which believe in God might be careful to maintain good works;
these things are good and profitable to men. Tit. 3:8.

And let ours also (to wit,
the church of Christ) learn to maintain good works for necessary uses,
that they may not be unfruitful.
This says Paul to Titus, and to the church. Tit. 3:14.

Let us consider one another, to provoke unto love, and to good works. Heb. 10:24.

That they do good, that they be rich in good works, ready to distribute,
willing to communicate; for God giveth us all things to enjoy. 1 Tim. 6:17-18.

But to do good, and to communicate, forget not;
for with such sacrifices God is well pleased. Heb. 13:16.

As God hath distributed to every man, and as the Lord hath called every one,
so let him walk, and so ordain I in all churches. 1 Cor. 7:17.

And Paul exhorts the church of the Romans to their
distributing to the necessity of the saints,
and of being given to hospitality. Rom. 12:13.

And to make contribution for the poor saints that were at Jerusalem,
which the apostle Paul mentions to the Romans.
Chap.
15:26.

Only that we should remember the poor, the same which I also was forward to do,
said the apostle to the church at Galatia. Gal. 2:10.

If any man minister, let him do it as of the ability which God hath given him,
that God in all things may be glorified through Jesus Christ,
to whom be praises and dominion forever and ever.
Amen. 1 Pet. 4:11.

And let us not be weary in well-doing; for in due season we shall reap, if we faint not;
as we have therefore opportunity, let us do good unto all men,
especially to the household of faith. Gal. 6:9-10.

And whatsoever you do in word or deed, do all in the name of the Lord Jesus;
and whatsoever ye do, do it heartily, as unto the Lord,
knowing that of the Lord ye shall receive the reward of the inheritance;
for ye do serve the Lord Christ. Col. 3:17,23,24.

Therefore, to him that knoweth how to do good, and doth it not, it is to him sin. James 4:17.

He that hath pity on the poor, lendeth unto the Lord;
and that which he hath given will he pay him again. Prov. 19:17.

And you may see, such as were careful to hearken unto the voice of the Lord God,
and to obey and keep his commandments; for the Lord thy God will bless thee,
as he hath promised, thou shalt lend unto many nations, and thou shalt not borrow, etc.
Duet. 15:5-6.

For the Lord shall open unto thee his good treasure,
the heaven to give thee rain unto thy land in his season,
and to bless all the works of thine hands; and thou shalt lend unto many nations,
and thou shalt not borrow; and all people of the earth shall see,
that thou art called by the name of the Lord; and they shall be afraid of thee. Duet. 28:10,12.

And David said, I have been young, and now am old,
yet have I not seen the righteous forsaken, nor his seed begging bread;
for he is ever merciful and lendeth, and his seed is blessed. Ps. 37:25-26.

A good man showeth favour, and lendeth, he will guide his affairs with discretion.
Ps. 112:5.

The righteous showeth mercy, and giveth. Ps. 31:21.

The righteous giveth, and spareth not; he that hath a bountiful eye shall be blessed;
for he giveth of his bread to the poor.
Prov. 21:26, and 22:9.

And he that giveth to the poor, shall not lack. Prov. 28:27.

God giveth to all men liberally, and upbraideth not.
So all men should give of that which they have received of him, liberally,
without upbraiding, as in James 1:5.

And he that giveth, let him do it with simplicity. Rom. 12:8.

Give, and it shall be given unto you, saith Christ. Luke 6:88.

And see the care of the apostles of the poor saints, as in 2 Cor. 9:6-11.

But this I say, he which soweth sparingly, shall reap sparingly;
and he which sows bountifully, shall reap bountifully. 2 Cor. 9:6.

So every man, according as he purposeth in his heart, so let him give,
not grudgingly or of necessity; for God loveth a cheerful giver, (mark,
a cheerful giver,) and God is able to make all grace abound towards you,
that ye always having all-sufficiency in all things may abound to every good work,
as is written, "`He hath dispersed abroad, he hath given to the poor,
his righteousness remaineth forever;`" mark! now he that ministereth seed to the sower,
both ministereth bread for your food, and multiplies your seed sown,
and increaseth the fruits of your righteousness. Isa. 4:10.
and 2 Cor. 9:7-10.

Being enriched in every good thing to all bountifulness,
which causeth through us thanksgiving to God.

And you may see how the disciples, every man according to his ability,
determined to send relief unto their brethren, who dwelt in Judea,
and they sent it by the hands of Saul and Barnabas. Acts 11:29-30.

And so of brotherly love, ye need not that I write unto you;
for God teacheth you to love one another. 1 Thess. 4:9.

But whoso hath this world`'s goods, and seeth his brother have need,
and shuts up his bowels of compassion from him, how dwelleth the love of God in him? 1 John 3:17.

There is a generation whose teeth are as swords, and their jaw teeth as knives,
to devour the poor from the earth, and the needy from among men. Prov. 30:14.

And therefore the poor and needy are not to be oppressed nor vexed, nor sent away empty,
but relieved, and their cause is to be pleaded; as in Prov. 31:9.

And the apostle saith to the church, "`Give to him that needeth.`" Eph. 4:28.

"`But my God shall supply all your need,
according to his riches in glory by Christ Jesus.`" Phil. 4:19.

And Christ said, "`The Father knoweth what things ye have need of.`" Matt. 6:8.

And you may see the manner and way of collections,
that the apostles ordered for the saints, in 1 Cor. 16:1.

And the Lord saith, "`If thou deal thy bread to the hungry,
and that thou bring the poor that are cast out to thy house,
and when thou seest the naked that thou cover him,
and that thou hide not thyself from thy own flesh,
then shall thy light break forth as the morning,
and thy health shall spring forth speedily, and thy righteousness shall go before thee;
the glory of the Lord shall be thy reward.
Isaiah 58:7-8, 10,

And if thou draw out thy soul to the hungry, and satisfy the afflicted,
then shall thy light arise in obscurity, and thy darkness shall be as the noon-day.

And the Lord shall guide thee continually, and satisfy thy soul in drought,
and make thy bones fat, and thou shalt be like a watered garden,
and like a spring of water whose waters fail not.
Here is the practice of godliness.
Isaiah 58:7-11, etc.

The hungry and thirsty, their souls faint in them, then they cry unto the Lord,
and he satisfieth the longing soul in their trouble,
and filleth the hungry with goodness, (or good things.) Ps. 107:50.

The Lord which made heaven and earth, which giveth food to the hungry,
preserveth the stranger, and relieveth the widow and fatherless;
but the way of the wicked he turns upside down.
Ps. 146:9.

If thy enemy hunger, give him bread to eat; and if he thirst, give him water to drink.
Thou shalt heap coals of fire upon his head, and the Lord shall reward thee. Prov. 25:21-22.

And the law of God ye may see in Ezek. 18:7,9. He that hath not oppressed any,
but hath restored the debtor his pledge, and hath spoiled none by violence,
and hath given his bread to the hungry, and hath covered the naked with his garment,
he shall surely live, saith the Lord God.

And Job said, "`Because I delivered the poor that cried, and the fatherless,
and him that had none to help, the blessing of him that was ready to perish came upon me.
I caused the widow`'s heart to sing for joy, and I was a father to the poor.`" Job 29:12-13.

Dorcas, (a woman,) a certain disciple of Jesus Christ; when she was dead it is recorded,
"`This woman was full of good works, (mark, full of good works) and alms-deeds,
which she did in her life time; and all the widows, (mark, all) they stood by Peter,
(the widows,) and wept,
and showed him the coats and garments that she had
made whilst she was alive with them,`" mark,
with them.
A women`'s meeting in the practice of religion.
Acts 9:36 to the end.

"`Pure religion, and undefiled before God and the Father, is this:
to visit the fatherless and widows in their affliction,
and to keep himself unspotted from the world.`" James 1:27.

And this religion is to be practised by all the right and true christians.
For if a brother or sister be naked, and be destitute of daily food,
and thou say unto one of them, depart in peace, warm yourselves, and fill your bellies,
notwithstanding you give them not those things which are needful to the body,
what helpeth it?
Even so faith, if it have no works, is dead in itself, James 2:15-17.
See how James encourages to practice religion,
and to show forth the works of faith, that works by love.

If thou afflict any widow or fatherless child in any wise, and they cry at all unto me,
I will surely hear their cry, saith the Lord, and my wrath shall wax hot,
and I will kill you with the sword, and your wives shall be widows,
and your children fatherless. Ex. 22:22.

The Lord is good to all, and his tender mercies are over all his works.
Ps. 145:8-9.

The righteous considereth the cause of the poor; but the wicked regardeth not to know it,
(to wit, the cause of the poor,) what condition they are in. Prov. 29:7.

And if thy brother be waxen poor, and fallen in decay with thee,
then shalt thou relieve him; yea, though he be a stranger or a sojourner,
that he may live with thee. Lev. 25:35.

The poor is hated even of his neighbour, but the rich hath many friends;
but he that is merciful to the poor, happy is he. Prov. 14:20-21.

He that oppresseth the poor, reproaches his Maker; but he that honoureth him, (to wit,
his Maker,) hath mercy on the poor. Prov. 14:31.

Whoso mocks the poor, reproaches his maker. Prov. 17:5.

Whoso stops his ears at the cry of the poor, he also shall cry himself;
but shall not be heard. Prov. 21:13.

The Lord maketh poor, and maketh rich; he bringeth low, and lifteth up. 1 Sam. 2:7.

Therefore I command thee, thou shalt open thy hand wide unto thy brother, to thy poor,
and to thy needy in the land, saith the Lord. Duet. 15:11.

The poor useth entreaties; but the rich answereth roughly. Prov. 18:23.

Here you may see what care the Lord lays upon his people, to look after the poor, widows,
and fatherless, both in the time of the law and in the time of the gospel;
and how that they should obey him in his commands, the Lord God, who created all,
and gives the increase of all, and gives man and woman good things,
both temporal and spiritual, to do good withal.
So the Lord is to be obeyed, and his truth is to be practised; and the pure religion,
that is undefiled before God and the Father, is above all religions in the world.
And this religion is, to visit the widows and fatherless in their affliction,
and to keep himself unspotted from the world; (mark,
unspotted from the world.) And this religion is above the Papists,
that must have a purgatory to wash off their spots of the world;
and above those Protestants,
that plead they must have a body of death and sin to the grave,
with which they are spotted like leopards.
And these are the religions of the world;
and are not the pure and undefiled religion before God and the Father;
and their fatherless and widows in their afflictions are not visited,
as they ought to be.
And therefore, you who are come to be of this pure religion,
that is undefiled before God and the Father,
and do visit the widows and fatherless in their afflictions,
and do keep yourselves unspotted from the world;
you are of the religion that was not set up by man,
but by Christ and his apostles above sixteen hundred years since;
by which you see over all the religions set up since;
and see therefore that you practise it.

And Job said, "`If I did despise the cause of my man servant, or of my maid servant,
when they contended with me, what then shall I do when God shall arise?
and when he visiteth, what shall I answer him?`"
See the care of this patient man!
Is not this for all the true christians to practise? Job 31:13-15.
And, saith Job, "`Did not he that made me in the womb, make him?
and did not one fashion us in the womb?`" verse 15.
And if I have withheld the poor from their desire,
or have caused the eyes of the widow to fail, or have eaten my morsel myself alone,
and the fatherless hath not eaten thereof;
(for from my youth he was brought up with me as with a father,
and I have guided her (to wit,
the widow) from my mother`'s womb:) if I have seen any perish for want of clothing,
or any poor without covering; if his loins have not blessed me,
and if he were not warmed with the fleece of my sheep;
if I have lifted up my hand against the fatherless when I saw my help in the gate;
then let mine arm fall from my shoulder-blade,
and mine arm be broken from the bone.`" "`The stranger did not lodge in the street,
but I opened my doors to the traveller.`"
"`Did not I weep for him that was in trouble?
was not my soul grieved for the poor?`"
Now, here ye may all see the actions and practice of this man,
by his practising the pure religion: so it is not a talk, but a walking in it;
as you may see in Job 30, 31 chapters.

"`And blessed is he that considereth the poor,
the Lord will deliver him in time of trouble.`" Ps. 41:1.

Now, all you that profess God and Christ,
see how you walk in the steps of these good men and women;
and not only to talk as they did, but do and practise as they did;
for it is not every one that saith, Lord, Lord, enters the kingdom,
but he that doth what he commands.

And Christ saith, "`Ye call me Lord and master; and ye say well, for so I am; and if I,
then, your Lord and master, have washed your feet,
ye also ought to wash one another`'s feet: for I have given you an example,
that ye should do as I have done unto you.
And if ye know these things, happy are ye if ye do them.`" John 13:17.

And Christ saith, "`Not every one that saith unto me, Lord, Lord,
shall enter into the kingdom of heaven;
but he that doth the will of my Father which is in heaven.`" Matt. 7:21.

So all people may see by Christ`'s own words,
that their saying and speaking of God and Christ, and his prophets and apostles,
signifies nothing, except they do his will; that is, practise it,
and be obedient to what he commands and requires.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 332.

[.blurb]
==== To Friends in Cumberland.

[.salutation]
Dear friends,

Who are gathered in the name of Jesus, by whom all things were made and created,
who upholds all things by his word and power, and gives the increase of all things;
the earth is his, and the fulness thereof.
And therefore let your minds and hearts be with the Lord, and your care cast upon him:
and though the Lord is pleased now to try you, and to exercise you in sufferings,
and permits your persecutors to spoil your goods, or cast you into prison,
to try whether your minds be in him, or in the outward things he gives you:
yet let not visible things separate you from the love of God in Christ Jesus,
nor no persecutions amaze you, nor separate your minds from the love of God.
For all things shall work together for good, to them that love God;
for the love of God bears all things, and suffers all things;
and they that spoil the goods of the innocent and cast them into prison,
for serving and worshipping of God, the Lord sees it and beholds it;
and so leave them to the Lord to deal with them.
For that which they get by spoiling you, they will never be the richer for;
and when they have done spoiling, the Lord can spoil them and theirs.
And all the goods they take from Friends, for serving God, will torment them at last,
and be a greater plague to them, more than keeping on your hats, and saying thou to them,
was.

And you have had experience how the other powers spoiled your goods;
but were they either the richer or the fatter?
Nay, the more they did eat, destroy, and devour,
the more they looked like Pharaoh`'s lean cattle.

And did not the christians of old suffer joyfully the spoiling of their goods,
by professors and profane?
So they that are born of the flesh, will persecute them that are born of the spirit;
and they that will live godly in Christ Jesus, must suffer persecution;
and blessed are they that do suffer persecution for Christ and his righteousness`' sake.

And so never fear the loss of the fleece, for God can make it grow again,
as he did poor Job`'s. And it is the way of the enemy and adversary,
to set upon the young convinced, to think by that means to make them to yield.
For, have you not read, it was the way, how that the enemies of Israel, of old,
fell upon the weak and feeble of their camp, and the hindermost of the flock;
but they had their reward at the end.
And so wait upon the Lord, and he will support you, though he may try you awhile;
as he doth all his saints,
that the trial of your faith may come forth more pure than gold.

And so never fear man, nor what they are permitted to do unto you, but the Lord:
though the hungry lions may lack, yet they that wait upon the Lord,
shall not want any good thing; for his promise is,
he will never leave them nor forsake them.

And so the Lord God Almighty give you power and courage,
to stand against all the wiles of the enemy,
and to be valiant for his truth upon the earth.
And so, with my love in the everlasting seed, Christ Jesus,
who is over him that makes to suffer, and will be when he is gone.

[.signed-section-signature]
G+++.+++ F.

Marshgrange, the 6th of the 4th month, 1676.

[.centered]
=== Letter 333.

[.blurb]
==== To Friends in Barbados.

My dear friends in the heavenly relation, and Zion`'s children,
amongst whom the stone that the builders rejected, is elect and precious,
and in him Christ, you are elect, who is the head of the corner of God`'s building;
and therefore in the name of Jesus keep your meetings, in whom you all have salvation,
and not by any other name under heaven.
And though the Lord may try you, where your minds are, and in what,
by the outward powers, yet be valiant for God`'s truth upon the earth;
and if some of you be cast into prison, and your goods be spoiled,
the seed is upon the head of him that maketh to suffer, and will remain when he is gone:
and the Lord God who giveth the increase of all, both invisible and visible,
can make the fleece to grow again.
And therefore let your faith be in the power and word of life;
and the authority of your men and women`'s meetings is the power of God;
and all the heirs of the gospel are heirs of Christ, the heavenly man,
and of his government, of the increase of which there is no end.
And so all walk in Christ, who bruiseth the serpent`'s head,
that hath gotten between you and God; so as you all are in him,
then nothing can get between you and the Lord God.
And so in the glorious order of the gospel, the power of God, dwell,
which is over the devil, and the world, and before he and it were,
and the power of God will be when he and it are gone: this is the everlasting gospel,
which bringeth life and immortality to light; and that you,
all may see over him that hath darkened you, to him who was before he was,
and the power of God will be when he is gone.
And therefore walk in the glorious, blessed, peaceable,
and comfortable order of the everlasting gospel; for the gospel, the power of God,
is the gospel of peace, and the truth is peaceable: the devil,
the destroyer and adversary, abode not in the peaceable truth,
and the kingdom of God stands in peace and joy in the holy ghost;
and the unity of the spirit is a bond of peace, yea, the bond of the heavenly man,
the Prince of princes`' peace, that bond must be kept, by all Zion`'s children,
the heirs of life.

And all seek the peace and good one of another, and dwell in the love of God,
that does edify the body of Christ, and bears all things, and endures all things;
and build up one another in the most holy faith, which you have from Christ,
the Holy One; for "`holiness becomes the house of God.`"
And therefore all mind that which becomes his house;
and now is the time for every one to put on the armour of God,
and to take his weapons and arms, that you may stand by God`'s ensign in the truth,
against him that is out of truth, keeping on your helmet of salvation,
as a token of your victory; and your breast-plate of righteousness,
which preserves both mind, heart and soul; and your loins girded with truth,
that you may be valiant for it; and your feet shod with the preparation of the gospel,
the power of God, that your feet may stand fast over all slippery places,
in the power of God, the gospel, that is sure and everlasting: here is your armour;
and your weapon is the sword of the spirit, the word of God,
the word of life and salvation, and wisdom and reconciliation;
that is as a sword and a hammer,
to cut down and hammer down that which hath made a separation betwixt you and God,
and is as fire to burn it up.
And the shield of faith, that is your shield by which you have victory and access to God;
by which faith all the just live, and are saved, and contend for it,
which is declared to the saints by Christ, who is the author and finisher of it.
And by this faith you come to Christ, the author, and as many as receive him,
walk in him, that you may be always fresh and green in him,
who bruises the head of the serpent, that hath made people lean and barren,
and hath made so many barren mountains,
which Christ is gathering and calling his people from,
that they might walk in the light of the Lord,
and come to the mountain of the house of the Lord,
that is established above all the mountains, where God teaches all his, the way of life,
truth, and salvation.
And the mountain of the house of the Lord is always green,
with fresh springs and fruitful, and all that live under God`'s teaching know it.
So serve God in the spirit, and in the newness of life, which is over the old,
that the Lord God`'s presence may be felt amongst you; and his son,
a prophet to open to you, and a priest to sanctify you, a bishop to oversee you,
and a shepherd to feed you; the rock of your age, and ages,
the foundation of your generation, and many generations; and who are in him,
who was elected before the foundation of the world, they build upon him,
who is the first and the last, the beginning and ending;
in him you have all life and salvation, who is the Amen.

And my desire is, that you may, in the power of God,
encourage all the faithful women in your island, in the work and service of God;
and now you have six men`'s meetings, if you had as many women`'s meetings,
it would include all the faithful women in all the corners of your island,
and some of your ancient faithful women to go from meeting to meeting,
till they are settled in the power of God,
and that will keep all alive in the Lord`'s working power and living life.

And all that are not faithful, let them be admonished to faithfulness,
that so they may come into the light, and life, and service of God and Christ;
for all the wise hearted and faithful women, in the time of the law,
were to work about the tabernacle of God, and the holy things:
and they were called the assemblies of the women.

And all the women in the time of the law were to offer sacrifices upon God`'s altar,
as well as the men.
And now in the time of the gospel, which hath brought life and immortality to light,
God doth pour out of his spirit upon all flesh; and therefore live in the gospel,
and its order; and all true christians, men and women,
do offer their spiritual sacrifices to God, who is a spirit.

And therefore, my friends, be valiant for God`'s truth upon the earth; dwell in love,
that will bear all things; and let there be an order entered in your books,
that there be no provoking words spoken in your meetings,
but if any have any thing to say, let them speak to them in love privately.
And when ye have settled your six women`'s meetings, then you may have a six weeks`',
or a Monthly as well as a Quarterly Meeting, as you may see meet.
And so that all your wells of life may be kept open,
and every one have a fresh spring springing up in you;
so that in every one of you the living water of life may flow;
so that ye all may be refreshed with the fountain of life,
and feel Christ a bishop to oversee, and a counsellor to counsel,
and a king to rule in your hearts, and a prophet to open,
and a shepherd to feed you with his heavenly food.

And so see that nothing be lacking among you, both inward and outward;
and whatsoever is decent, comely, modest, virtuous, righteous, and of good report,
follow after, and be steadfast upon Christ the rock and foundation.
And whatever you do, let it be done in the name of Jesus, (that is,
in his power,) and mind the gospel of peace, and its order,
which hath brought life and immortality to light, that you may be preserved in life,
and in immortality, by the immortal power.
And all to be children of the wisdom that is from above, which is pure and peaceable,
and easy to be entreated, keeping the unity in God`'s holy spirit,
in which is the bond of the Prince of princes`' peace, in whom you have all peace, life,
and salvation.

I received your letter from your Quarterly Meeting,
and I am glad that you are in the Lord`'s work and service.

And my desire is, that ye all may stand up for the glory and honour of the Lord God,
and that his blessings may abound among you.

And so if you do write to New England and Jamaica,
where I hear they have precious men and women`'s meetings,
it might do well to encourage one another in the work and service of God:
so that the women may all be helps-meet to the men in the restoration,
in the image of God, as man and woman were in before they fell.
So with my love in the seed of life to all Friends in the island.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, in Lancashire, the 25th of the 8th month, 1676.

[.centered]
=== Letter 334.

[.blurb]
==== To Friends in the Isle of Man.

My dear friends, be valiant for God`'s truth upon the earth, and live in the light,
and power, and spirit of God, that you answer that of God in all,
by which their minds may be turned to God.
And keep your meetings in the name of Jesus, in whom you have salvation;
whose name is above every name under the whole heaven;
that the Lord`'s glory you may see to shine in and about your tabernacles,
and his presence among you to teach and order you, and be you obedient to it.
So with my love to you all in the everlasting seed,
that bruiseth the head of the serpent; which seed liveth and reigneth over all,
from everlasting to everlasting, in his glory,
in whom the saints do sit down In their peace, and rest, and joy forevermore.
Amen.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 5th month, 1676.

[.centered]
=== Letter 335.

[.blurb]
==== To Friends in Virginia and Maryland.

My dear friends,

All dwell in the love of God, and in his power and truth,
that the presence of the Lord God you all may enjoy, who is the life of you all,
and the length of your days, who hath the breath of all mankind,
and the spirits of all flesh in his hand; and in him you do all live, and move,
and have your being, who is your rock and salvation, and fountain of life,
and of all your mercies, and of your water of life: and therefore serve, and honour,
and fear, and worship him in his spirit and truth;
and that you all may abide in the holy, heavenly and spiritual vine,
and in him bring forth heavenly and spiritual fruits, to the glory of God,
who sent his son to be a leader, and the way to God, who draweth all men up to himself,
where he is ascended, to sit together in heavenly places in Christ Jesus,
out of all sin and transgression, by which man was driven from God,
that made him barren and unfruitful.
And therefore, be ye separated from the world to the Lord,
by the word which was in the beginning, which divideth the precious from the vile;
that by that word ye may be reconciled to God;
which word reconcileth all things in heaven and in the earth in one;
which word hammereth down that which made twain;
and so by the glorious everlasting word of life you
are born again of the immortal seed of God,
and feed upon the milk of this everlasting word, which liveth, and abideth,
and endureth forever, and was in the beginning;
by which word you have wisdom and salvation,
by which wisdom all God`'s children are justified.
The Lord God in his immortal power preserve you, out of all evil, and out of the earth,
and over your enemies, within and without, in his everlasting seed Christ,
that is over all, to his glory, forever.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 336.

[.blurb]
==== To Friends at Dantzie.

[.salutation]
Dear friends,

In the love of God, and the Lord Jesus Christ, look above all your outward sufferings,
and him that is out of truth, that makes you to suffer;
and let nothing separate you from the love of God which you have in Christ Jesus,
by whom all things were made: I say, let not the birth of the flesh,
with all his carnal weapons, jails, and prisons, threats, or reproaches, move you,
nor separate you from the love of God, nor from your foundation, the rock of ages,
Christ Jesus: but feel the well of life springing up in you,
to nourish the plant that God has planted in you, of his renown,
that that may grow up within his hedge, his power,
which will keep out the devil and all the venomous beasts,
from entering into God`'s garden, or kingdom.
And therefore let your faith stand in the Lord`'s power, which is your hedge and defence,
and which is your keeper, and will keep you safe,
that you need not be afraid of your enemy, your adversary;
for the Lord`'s power is over his head, and you within his power,
then nothing can get betwixt you and God;
and in the power of the Lord is the city set upon his hill, where the light shines,
and the heavenly salt is, and the lamps burning,
and trumpets sounding forth the praise of God, of the eternal joy,
in his eternal word of life, that lives, and abides, and endures forever.
And so to the praise and glory of God you may bring forth fresh and green fruit,
being grafted into the green tree that never withers.

Oh! be valiant for God`'s glory and his truth upon the earth, and spread it abroad,
answering that of God in every man and woman`'s conscience;
knowing him that hath brought everlasting peace into the earth: so,
that the songs of salvation may be in your mouths; for it is said,
"`With the heart man believes, and with the mouth confession is made to salvation.`"
So every true believer will confess to Christ his salvation, their way, light, and life,
out of death and darkness; their prophet, to open to them; their shepherd, to feed them;
and their bishop, to oversee them; their captain and commander,
to command and to lead them; their counsellor, to counsel them; and their priest,
who hath offered himself for them, and also sanctifies them, and offers them up to God:
to whom be all praise and glory forever.
Amen.

I wrote something to the magistrates, which is in print in England; which,
if you have it not to give them, you may send into Holland,
and let it be translated into your language, and given to them,
and spread it up and down in your country.

And as for truth in this part of the world, and in America, it prospers, and spreads,
and goes on; and by it many men and women are made God`'s free men and women,
being redeemed from him that is out of truth,
that they may serve God in the new life in Christ Jesus,
(out of the old life in Adam in the fall,) and so come to live in the heavenly unity,
wisdom, love, and dominion.

So, in that love that bears all things, and keeps your hearts, minds,
and souls up to God, which comes from God, through which you come to love God,
and Christ, and one another; in that live and dwell.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 17th of the 3d month, 1676.

[.centered]
=== Letter 337.

[.blurb]
==== To Friends in Holland.

[.salutation]
Dear friends,

To whom is my love in the seed of life, that bruises the head of the seed of death;
and through him you have all life eternal; who is the foundation of the prophets,
and the apostles, and all God`'s people, in all ages, their rock to build upon,
that will stand the waves of the sea, and all storms and foul weather;
who is the horn of your salvation, to push down all that stands in your way to God;
and to push down him that has led man and woman from God: so,
that you may all sing of your rock, and the horn of your salvation,
as the holy ones did in ages past; and Christ, who is your foundation, the lamb of God,
who hath been slain from the foundation of the world, but now he has overcome the world,
and is risen, and ascended far above all principalities, powers, thrones, and dominions;
and is razing down to the ground the world`'s foundation,
from which foundation he has been slain, and is setting up himself,
the living and everlasting foundation, for all his to build upon.
And therefore, because the world and its foundation, Christ is razing down,
they are offended and angry, and the heathen rage and take counsel against the anointed.
But it is to no purpose, for he will shake the foundation of all false religions, ways,
worships, churches, and teachers, and will make the pillars of them to totter,
and they must be at their wit`'s end, before they see another foundation.
For God shook down the four monarchies, the great empires of the world,
and scattered them abroad with his wind, as the chaff of the summer floor,
all those great persecutors.
And the little stone that is cut out of the mountain without hands,
that no earthly man has the glory of, is becoming a great mountain,
and will fill the whole earth,
(glory to God forever!) and it will dash down all men`'s glory and pride,
let them soar as high as Nebuchadnezzar, and shelter as many under them as he did,
in their sects, that he may make them to know,
that the Most High rules in the kingdom of men,
and that his kingdom is an everlasting kingdom.
And therefore, all Friends, that know the light, which is the life in Christ,
be faithful in the truth, and spread it abroad,
answering the light of Christ in every one;
for Christ bid his disciples go preach the gospel unto all nations:
and since that was done, are many gathered into the fellowship and order of it.
But since, the world has worshipped the beast, and given their glory and honour to him,
instead of God and Christ; which beast is out of truth,
and had his power from the dragon, and the whore, and all nations have drunk of her cup,
and she has rode upon the beast;
and now the everlasting gospel must be preached again to all nations, tongues,
and people, that dwell upon the earth.
So all nations have been darkened from life and immortality; and now the gospel,
which is the power of God, brings life and immortality to light again,
that they may come to see over him that has darkened them, and before he was;
and such come into the city of the heavenly Jerusalem,
and drink of the waters of life freely.

And therefore, all live and walk in the light, in which you have fellowship and unity,
and be at peace among yourselves, and in love, which edifies, and bears all things;
for this is that which passes knowledge, and keeps in the humility of Christ Jesus.
So, my desires are, that you may all spread and grow in the vine,
for the Lord hath a great people to come out in those parts, which I saw in 1651.
And therefore labour in God`'s power, that you may increase your heavenly treasure,
and enter into the joy of the Lord.
And so, with my love to all in the truth, that walk and live in it,
that by it they may be made God`'s freemen.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 2nd of the 7th month, 1676.

[.centered]
=== Letter 338.

[.blurb]
==== To Friends in Maryland and Virginia.

My dear friends,

Be valiant for the truth, and the power of it, in the spirit and faith of Jesus,
and let no one take your crown;
for the saints overcame by the blood of the Lamb and the testimony Jesus.
And so fear not the wrath of man, but fear the Lord,
and keep your men and women`'s meetings in the name of Jesus;
in whose name you have salvation, life, and peace; so that all may be in the vine,
bringing forth heavenly fruit, to the glory of God.
And so feel his banner of love over you,
and you sitting under the shadow of the Almighty,
and look over that which maketh to suffer, to that which was before it was;
and know your faith, to stand in the seed that bruiseth the head of it; which seed,
Christ, is your rock and foundation,
who will raze down the foundation of the world of wickedness,
from which foundation the lamb hath been slain.
But he is risen, and hath overcome the world, and hath the victory:
glory to the Lord God and the Lamb forever.
Amen.
And in him you have the victory, and do overcome; and they that do overcome,
shall eat of the hidden manna,
and shall go no more forth into the barren world of wickedness,
but feed in the fruitful land of the living, and their feet shall be set in a sure place;
and beautiful are the feet of those that publish peace and glad tidings,
and that say in truth and righteousness to Zion, thy God reigneth.
Who is a consuming fire to the wicked;
and the joy of the Lord is strength to the righteous.
So serve the Lord in the newness of life,
for the Lord is dishonoured in the old life of wickedness;
and keep the unity of the spirit, which is the bond of peace, which no man can take away.
So, with my love to you all, in the everlasting seed, that changeth not.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 339.

All my dear friends and brethren, everywhere, in the name and power of Jesus Christ,
your Lord and saviour, life and peace, live and walk, in the Lamb which hath the victory.
And so in the humility of Christ, which you have learned of him; and in patience,
with which you run the race, and obtain the crown of immortal life;
and in the love of God all dwell, which will warm all your hearts,
and knit and unite you together, and build you up a holy temple for the Lord.
And his love will keep and carry you above all things, to the glory of God.
And this love will enable you to bear all things what ever wicked men can do unto you;
or, what the Lord may try you withal.
So, let your faith be in the invisible God and his son, who is able to succour you,
and save you to the uttermost; who is over all, King immortal, invisible,
the only wise God, blessed forever.
Amen.

So, God Almighty establish you all upon this holy rock and foundation, Christ Jesus,
who is the same today as yesterday, and so forever,
who was all the holy men and women`'s foundation, who is the first and the last,
the beginning and ending, the saints`' mediator and peacemaker between them and God.
Their joy and rejoicing is in him, their everlasting joy, the Amen, blessed forever.
So, with my love in the Lord Jesus Christ unto you all, in whom I have laboured,
(and) among you.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 19th of the 12th month, 1676.

[.centered]
=== Letter 340.

[.blurb]
==== To Friends in New Jersey in America.

My dear friends, in New Jersey, and you that go to New Jersey, my desire is,
that you may all be kept in the fear of God, and that you may have the Lord in your eye,
in all your undertakings.
For many eyes of other governments or colonies will be upon you; yea, the Indians,
to see how you order your lives and conversations.
And therefore, let your lives, and words, and conversations be as becomes the gospel,
that you may adorn the truth, and honour the Lord in all your undertakings.
Let that only be in your eye, and then you will have the Lord`'s blessing and increase,
both in basket, and field, and storehouse; and at your lyings down you will feel him,
and at your goings forth, and comings in.
So that you may answer the light, and the truth, in all people,
both by your godly lives and conversations.
Serving the Lord, and with a joyful heart, being valiant for his truth, upon the earth,
and the glorious name, in whom you have salvation.

And keep up your meetings for worship,
and your men and women`'s meetings for the affairs of truth, both Monthly and Quarterly.
And, after you are settled, you may join together and build a meetinghouse.
And do not strive about outward things; but dwell in the love of God,
for that will unite you together, and make you kind and gentle one towards another;
and to seek one another`'s good and welfare, and to be helpful one to another;
and see that nothing be lacking among you, then all will be well.
And let temperance, and patience, and kindness,
and brotherly love be exercised among you, so that you may abound in virtue,
and the true humility; living in peace, showing forth the nature of christianity,
that you may all live as a family, and the church of God,
holding Christ your heavenly head, and he exercising his offices among you, and in you;
and hold him, the head, by his light, power, and spirit;
and that will keep your minds over the earthly spirit, up to God; for the earth,
and the sea, and all things therein, are his, and he gives the increase thereof.

And therefore be not over eager after outward things,
but keep above them in the Lord`'s power, and seed Christ Jesus, that is over all;
in whom you have all life, election, and salvation.

And write over yearly, from your meetings, how you are settled,
and how your affairs go in the truth,
and how your men and women`'s meetings are settled.

And my desires are, that we may hear that you are a good savour to God,
in those countries.
So that the Lord may crown all your actions with his glory.
So with my love to all.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 4th of the 1st month, 1676.

[.centered]
=== Letter 341.

My friends,

All you that do know God and Christ your teacher,
and are come to be the sons and daughters of the Lord God, and are in his new covenant;
in which you all do know the Lord, and need not any man to say unto you, know the Lord.
And are heirs of the gospel of peace and salvation,
that hath brought life and immortality to light; and that by the power of God,
the gospel, you do see over him, the adversary and the destroyer, that hath darkened you.
And so do know,
that the power of God is the authority of your men`'s and women`'s meetings;
in it keep them, and all other meetings.
And all such as be heirs of grace, and heirs of life, and heirs of the gospel,
keep your men`'s and women`'s meetings in the power of God, the authority of them;
and they that cry against them, or you, strive not with them,
for they will in God`'s time die of themselves, and wither away;
but keep your testimony of the life, and of grace, and of the gospel,
and of the order of it, and your faith in him, your teacher,
who bruises the head of the serpent, the author of all disorder and ill government;
even Christ, of the increase of whose government (in his truth, and power,
and righteousness) there is no end.
Glory to the Lord God forever.

And so all strive to be of one mind, and heart, and soul, and spirit, and faith,
living together in unity, and in the love of God, all drinking into one spirit,
by which you are baptized into one body, having one head, who is heavenly and spiritual;
and in the one spirit, by which you are circumcised,
which putteth off the body of the sins of the flesh.
So as you do keep to the spirit of Christ, it will keep you to be one body,
and to him the one head, Christ Jesus, the Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 342.

My dear friends and brethren,

That faith, which is the gift of God, which all the saints lived in,
(and by which they pleased God, and had victory, by which they had access to God,
and by and in which faith they did walk: and all the just, in all ages and generations,
did live by the same faith,) do you all live and walk now in your age.
I say, walk in that faith by which Enoch (the seventh from Adam) was translated,
and by which he had this testimony, that he pleased God.

And also keep in that faith by which Noah built his ark,
wherein he and his family were preserved, when the old world, that grieved God,
and his good spirit, were drowned.

And also walk in that faith by which Abraham forsook his father`'s house,
and native country, and their idolatrous religion.

And live in that faith, by which Moses forsook Egypt,
and refused to be called the son of Pharaoh`'s daughter,
and chose rather to suffer "`affliction with the people of God,
than to enjoy the pleasures of the world for a season.`"
And by this faith (which is the gift of God) he saw God, who is invisible.

And by this faith was Rahab the harlot saved, and her family.
And by this faith the walls of Jericho fell down, without any outward instrument of war.

And by this faith Jacob went down into Egypt, and his children;
and by this faith he knew they should return again.
And the Jews that did not keep in this faith, their carcases fell in the wilderness;
but they that kept in this faith entered into the land of promise.
And by this faith had all the valiants of God the victory,
and his holy prophets and prophetesses, as you may read all along in the scriptures.
And by this faith were they kept in the fire,
and by it the violence of the fire was quenched;
and by it the mouths of the lions were stopped.
So by this faith they had the victory.

And by this faith was Elijah taken up to heaven.
And so as Christ Jesus saith, "`faith saves, and makes whole.`"
And all are to look unto Jesus, the heavenly and the spiritual man, the second Adam,
the Lord from heaven, by whom all things were made and created,
who is the first and the last, to be both the author and finisher of their faith.

Now Christ said, "`When the son of man cometh, shall he find faith in the earth?`"
For all, both Jews and Gentiles, were concluded under sin and unbelief;
so sin and unbelief were over them, and they shut up under it.
So whosoever hath this true, saving, and justifying faith,
Christ Jesus hath been the author of it,
and is the finisher of this divine and precious faith.
So all eyes must look unto him, for he is both the author and finisher of this living,
precious, and divine faith.
And this is the faith of God`'s elect; by which faith they have access to God,
and know their election; by which faith they are translated from death to life,
and from the darkness to the light, and from the power of Satan unto the power of God,
and from the corruption to the incorruption, and from the mortal to the immortal,
and from the natural to the spiritual.

And by this faith, the devil, the destroyer, is resisted, who abode not in the truth;
and by this faith the fiery darts are quenched, of Satan,
(the adversary of man,) and he thereby is overcome.
So by this faith you come to know the partition wall broken down,
that hath been betwixt you and God.
So in this faith are all the household of faith to build upon Christ Jesus,
(who bruises the serpent`'s head,) who is the author and finisher of faith;
and this is called the holy faith, and the one faith, and by this one faith,
which Jesus Christ is the author and finisher of,
(by whom all things were made and created,) by it we do understand the worlds were made,
+++[+++by the word of God,]
and this is the faith which all the household of faith are to contend for,
this one faith which Christ Jesus is the author of; which faith is the gift of God,
and is held in a pure conscience.
And it is called the mystery of faith; for no natural men, with all the arts, languages,
and wisdom upon the earth, can find it out, or know this mystery, nor make it;
for Christ Jesus, the heavenly and spiritual man, is the author and finisher of it;
and no natural man, though he may have all the languages that began at Babel,
and yet he may not know the mystery of this one faith,
which Christ Jesus is the author of.
For Pilate, that set Hebrew, Greek, and Latin atop of Christ,
who was the author and finisher of faith; he was so ignorant of the mystery of faith,
that he asked Christ, what is truth?
And the Greeks, that spoke natural Greek, and the Hebrews, that spoke natural Hebrew,
the preaching of Christ, the author and finisher of the true faith,
was a stumbling block and foolishness to them.

So I do conclude, that no man or woman hath true faith only by the natural knowledge,
reading, or understanding of the original tongue and language of the New Testament,
no more than the natural Jews had by the reading
or knowing of the natural tongue of the Old Testament;
nor can any in the whole world have true faith,
except Jesus Christ be the author and finisher of it.

Now those that do say, that the tongues are the original,
and that by them the orthodox men and divines (so called) are qualified,
(which tongues began at Babel,) and these are the preachers that make faiths for people,
who have gotten scriptures in Hebrew, Greek, and Latin.
But I must tell you, that Pilate, and Herod, and the Jews, and the chief priests,
and the Grecians, and others that could speak Latin, and Greek, and Hebrew naturally,
knew not Christ, nor this one faith, which is the gift of God,
which Christ is the author of.
No more can they, with all their natural knowledge of all the tongues,
until Christ Jesus, the author of the true and saving faith, give it unto them;
by which one faith was Enoch translated before the many languages were;
and by which faith Abel`'s sacrifice was accepted, and by which faith Noah built the ark,
and by which faith he was saved;
and by which faith now all the household of faith are saved from the wrath,
by which God will destroy the wicked world,
which is reserved in store by the same word unto fire,
against the day of judgment and perdition of ungodly men;
which word will hammer down all, and burn up all, and cut down all the ungodly;
and by which word all things were made;
by which word of life and wisdom his people are reconciled to God;
and therefore they love the word Christ, who doth fulfill the mind of God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Letter 343.

Friends, in the power and image and truth and wisdom of God,
who are come under God and Christ`'s teaching,
(the heavenly and spiritual man,) do not you strive about men,
like the carnal Corinthians, that cried, I am of Paul, and I am of Apollos.
And they that do so, leave them to themselves,
after you have admonished them to keep to the light, grace,
and faith that comes from Christ; if they will not hear it, nor him, nor you, then I say,
they must be left to themselves.
And you, whose faith stands not in men, but in Christ, the author of it,
and in his gospel of salvation, by which you are saved; which gospel is the power of God,
your keeper.
Keep ye in the order of the gospel, (the power of God,) all ye that are heirs of it;
and in this power of God keep your men and women`'s meetings,
the power of God being the author and authority of them; by which power of God,
the gospel, you are saved, and have your liberty;
and in it you are over him that would destroy you, and darken you,
and keep you in bondage.
In which power of God, (the gospel,) you see life and immortality brought to light.
So it is the gospel that hath brought it to light, and keeps life, and immortality,
and an understanding up in you, above him that has darkened you from it.
Now this is an everlasting and invisible power,
in which you are all help-meets in the restoration,
by Christ the heavenly and spiritual man, whereby you are brought into the image,
likeness, righteousness, holiness, and power of God,
that man and woman were in before they fell.
And now the same spirit that drew Adam and Eve from the image and likeness of God,
and his power, and righteousness, and holiness,
under pretence to feed upon that which God had forbidden them,
(for they thought they should have been wiser than God had
taught them) would keep man and woman in the fall.
Now they, by hearkening to that spirit, and eating of the forbidden fruit,
fell and lost the image of God, and righteousness, and holiness,
and the power in which they had the dominion,
and were brought into the fall by hearkening to this false spirit, the adversary,
who envied their happiness and prosperity.
And so by their fall they came under another power, another image, another likeness,
and another God, even the God of the world.

Now this adversary and deceiver appeared against man in paradise;
and now men and women are deceived by him, and under his power in the earth;
who creeps on his belly, and dust is his meat.
This same spirit, who is the adversary and destroyer,
that led Adam and Eve into the fall, strives to keep men and women in the fall,
and in the earth, and opposes them in their conversion, regeneration, and restoration.

And this was the same spirit that rose in Cain against Abel,
and envied his acceptable sacrifice, and his righteous state,
as it did Adam and Eve`'s prosperity in the ruling power,
wherein they had dominion over all.
And the same spirit is risen now, which strives to keep people in the fall,
where he has got them,
that men and women should not be helps-meet in the restoration by Christ Jesus,
as they were in before they fell, in power, and righteousness, and holiness,
and likeness, and image of God.
So I say, the same spirit that envied Adam and Eve before they fell,
the same spirit opposes the men and women`'s meetings in the order of the gospel,
in their restoration.
And that which led them into the fall, does strive to keep them in the fall,
that it might be Lord, and not Christ Lord, who restores them;
so the same spirit now would not have men and women to have dominion in the power of God,
over all in the restoration, as they were help-meets together in the beginning.
And this is the adversary, the serpent, that led into the fall,
and would keep in the fall, and there be head.
But Christ, who is the head, and gives forth the order of his gospel,
(for his people to live and walk in,
and under his spiritual and heavenly government,)
bruises the head of this adversary to man and woman,
and God`'s order, and government, and teaching; and Christ,
(that does bruise his head,) is the head of all his people, that sits under his teaching,
and under his order and government, which they are to walk in.
So the same spirit is risen, that rose against Noah in the old world; yea,
it is seen what the sons of God run into then, even that which grieved God,
by following that spirit which led from God,
(which led Adam and Eve also from God.) But Noah was preserved in the ark,
over the floods, when the old world was drowned,
but all God`'s people are preserved in Christ Jesus, over the floods of the world;
and that spirit that led Adam and Eve into the fall,
and to feed upon that which made them think they
should be wiser than God had taught them.
I say, they are preserved in Christ Jesus,
(the ark,) over all the floods of the adversary,
and from the judgments that God brings upon him, and them that follow him.
And as Noah was preserved in the ark, over the outward floods that drowned the old world,
so will God`'s people be preserved from the fire and brimstone,
that is prepared for the wicked, and the devil and his angels.

And the same spirit is risen now, that led Nimrod to build Babel,
a city to preserve him and them after the flood,
but God did confound them and their work.
And so he will do all such builders.
For you see how God did confound all the Jewish builders, yea, the wise master builders,
who rejected Christ the corner-stone, and his order, and his government,
and his counsel.

And the great city Babylon,
which this spirit and its followers have built since the apostles,
is come into remembrance with God, which the same destroying spirit has built,
that led Adam and Eve from God, and from the order he placed them in.
So this same spirit, which hath led man and woman from the order the apostles were in,
strives to lead people from it now, where it is risen.

And the same spirit that led Cain to kill Abel, who afterwards built a city,
and the same spirit that led Adam and Eve from the command of God in paradise,
leads from it now; but God will lay Cain`'s city waste,
and there is no lodging in it for the saints, who seek another city,
whose builder and maker is God.

And the same spirit is risen now, that arose in Pharaoh, and in Korah, Dathan,
and Abiram; in Pharaoh, to oppose the people, and stop them from going out of Egypt,
and walking in the law of God, in which they might worship God;
which law of God was good, just, and holy, and went over all transgression and sin,
which led into death, that it might reign; and not the Lord and his law.

And that spirit that led Korah, Dathan, and Abiram,
who thought Moses took too much upon him, and busied himself too much,
pretending that the people were holy; so would not have them go further,
but there to have made a stop, and set down according to its will:
but see how they were stopped, and what became of Pharaoh, how he was sunk in the sea,
and the other into the earth.

And what became of them that opposed Aaron in his priesthood, their rods did not bud,
yet they would have been teachers and ministers,
but had not the fruit in the tabernacle in the morning,
that they might see how to deal their bread to the hungry;
and therefore they whose rods did not bud, God`'s fire consumed them;
for they have nothing to offer to God,
but manifest presumption and rebellion and see the end of such.

And the same spirit that rose against the prophets in the Jews,
who resisted the holy ghost, and rebelled against the spirit, is risen now,
and is the same spirit that deceived Adam and Eve in paradise,
which led the people from God, and his law, and his prophets:
but what became of these Jews, and what was their end?
Some to the fire, some to the sword, and some to captivity; as you may read.
And those that rebelled against Moses, and Joshua, and Caleb,
wandered in the wilderness till they perished, and came not to the good land.

And therefore, keep under Christ Jesus`' teaching, who is the prophet God has raised up,
like Moses, whom all should hear and obey.
And the same spirit is risen now, that rose against Christ and the apostles.
And Christ called them serpents, and of their father the devil, the destroyer,
the adversary, who had deceived Adam and Eve by his false teaching;
and envied their happiness, and led them from God.

So you may see how these Jews, high and low, were gone from God, and his law,
and his command, by hearkening to, and obeying this spirit,
which had led Adam and Eve to disobey God`'s command;
and therefore they would not receive his son, nor his order, nor doctrine.

And what became of all these Jews?
was not their city laid waste, and they scattered over all nations,
and they destroyed of the destroyer, who had denied Christ their saviour,
that wept over them, and would have saved them from destruction?

And such as came to John, and were baptized by him,
and rejoiced in his light for a season, and many that followed Christ,
and said he was a prophet; yet at last these turned from him that descended and ascended;
and he told them that rejoiced in John`'s burning light for a season,
God`'s mind was not abiding in them, and that they had not seen his shape,
nor heard his voice at any time; and that they received honour of man,
but knew not Christ the heavenly man, that received not honour of the earthly man,
who received their favour one of another: and such as said he was a prophet,
when he said, they must eat his flesh, the heavenly bread that came down from heaven,
they forsook him; for their minds turned downward, to feed upon that which was below.

And the same spirit is risen now, that rose against the apostles,
as you may see in their epistles, in the Romans, Corinthians, and in Peter, Timothy,
Titus, Jude, and John.
Some got the form of godliness, and denied the power;
and some were enemies to the cross of Christ, the power of God;
others were getting another gospel than the power of God,
which brought them under the curse; others were speaking the things of God,
in the words that man`'s wisdom taught them; others their faith was standing in words,
and not in the power of God; others their faith was standing in Paul and Apollos,
which should have stood in Christ: which grieved the apostles,
for their faith should have stood in Christ, whom they preached:
others with good words and fair speeches deceived the hearts of the simple.

And therefore, all they who preached faith, and made shipwreck of faith, were,
and are still denied: and all such as preach God and Christ,
and crucify Christ to themselves afresh, and deny God in their works, were then,
and are denied.
And all such as preach the light, and walk in darkness, and preach the spirit,
(the fruits of which are love and peace,) and are in strife and enmity,
were never owned by God, nor Christ, nor good men, though they may be called christians.
And all such as preach liberty, and themselves were servants of corruption, were,
and are still denied.
And all such as cry, Lord, Lord, and preach, Christ, Christ, and do not his will,
enter not into his kingdom themselves: and into it they can bring none,
that do not go into it themselves: which kingdom stands in power, and in joy,
and peace in the holy ghost.

And all such as preach the word of God, and are not doers of the word,
they are deceivers of their own souls, and they may deceive others with the good words:
and such cannot be reconciled to God,
neither can they bring others to reconciliation with God.

So this spirit is but one;
which spirit all along has wrought against the true spirit of God in all his people:
and was in strife, and contention, and disquietness against the righteous in all ages;
but it wrought its own destruction and the fall of them that followed it;
as you may see through all the scriptures.

And therefore, all are to keep the unity of the spirit,
the bond of the heavenly man Christ Jesus`' peace,
who renews man up into the image of God, as man was in before he fell;
and not only into that state, but up into himself, that never fell,
where they know both his gospel order and his heavenly government, and are subject to it:
he being the head, above all principalities, powers, thrones, and dominions:
who is ascended above all, that he might fill all things: who is over all,
the beginning and ending, and lives and reigns from everlasting to everlasting,
the Amen.

G+++.+++ F.
