== Letters 387 &#8212; 397

[.centered]
=== Letter 387.

[.blurb]
==== To the Monthly and Quarterly Meeting in England, etc.

[.salutation]
Friends,

Be all faithful in your testimony against tithes,
and all those things that have come up in the night of apostacy from the light, life,
and power of God and Christ, and against all looseness whatsoever,
that the heavenly camp of God may be kept clean and pure.
And all Friends, look at the Lord above all your sufferings, and trust in him,
who by his eternal power has preserved you to this day.
The Lord in his glorious power was with us in all our assemblies at this Yearly Meeting;
he over all hath the dominion, and over all evil spirits gave dominion to his people.
Glory to-his name forever.
Amen.

And therefore let your eye be to the gospel, the power of God,
which has brought life and immortality to light in you,
which is farther than the law to be looked at.

G+++.+++ F.

The 9th of the 4th month, 1683.

[.centered]
=== Letter 388.

[.blurb]
==== To Friends that are captives at Algiers.

Dear friends, who are captives in Algiers,
whom the Lord hath enlightened with his day spring from on high,
and visited you with his tender mercies in your slavery and captivity,
that you may know his will, and do it in his light, grace, truth, and spirit,
that you may serve and worship the holy, eternal, and invisible God that made you.

Now, dear friends, to you is my love, and to all the rest that fear God,
that meet with you; my desires are, that you may all keep low in humility,
in the fear of God, there is no danger; for God dwells with the humble,
and teaches the humble the way they should walk.
And therefore be careful of God`'s glory, you who profess the name of God, and his son,
that your lives, and words, and conversations may preach godliness, righteousness,
holiness, virtue, sobriety, and modesty, both to Turks, Moors, Jews, and to your patrons,
and to the families where you live;
for Christ hath enlightened every man that comes into the world,
he hath enlightened the Turks, Jews, and Moors, with the light,
(which is the life in him the word,) that all in the light might know God and Christ;
and "`the grace of God which brings salvation hath
appeared unto all men;`" so to the Turks,
Jews, and Moors, yea, to all nations;
so that with the grace of God they may be taught to deny ungodliness and unrighteousness,
and live righteously and godly;
and therefore all must come to this grace of God in their hearts,
which brings their salvation, (if they have salvation,) and come to the throne of grace;
and this is the covenant of grace, in which is the election; and God, who made all,
pours out of his spirit upon all men and women in the world,
in the days of his new covenant, yea, upon whites and blacks, Moors, and Turks,
and Indians, Christians, Jews, and Gentiles, that all with the spirit of God,
might know God and the things of God, and serve and worship him in his spirit and truth,
that he hath given them.
But they that do resist the truth, and quench, and vex, and grieve,
and rebel against the spirit that God hath given them,
such are not like to serve and worship God in his spirit and truth;
but he that endures to the end in God`'s grace, spirit, light, and truth, shall be saved.
And the gospel of salvation is preached to every creature under heaven;
which gospel is the power of God, and the gospel of peace;
and so it is glad tidings to every creature under heaven, and to all nations,
to the Turks, Jews, Indians, Moors, Christians, and Gentiles,
if they receive and obey the gospel of salvation, it is glad tidings to them all.
Now, this is the day of God`'s gathering: and therefore all must come to the light,
grace, truth, power, and spirit of God in their own particulars,
which they have from God and Christ, that by it they might be built upon Christ,
their heavenly rock and foundation, who is their way to God,
who bruises the serpent`'s head, and through death destroyed death,
and the devil the power of death, and so destroys death,
and so destroys the devil and his works; for sin brought death; and now Christ,
who destroys death that sin brought, and makes an end of sin,
is the sanctuary for all his believers in all storms and tempests, trials, and troubles,
and sufferings, to rest upon, in whom they have peace; yea, life and salvation.

Now there is a common saying among the Turks to the Christians,
"`Your crucified God,`" meaning Christ.
Now this is their mistake; though God was in Christ reconciling the world to himself,
it was not the eternal God that died, and was crucified, that was in Christ;
for Christ said, when he was about to suffer, "`My God, my God,
why hast thou forsaken me?`"
So Christ suffered in the flesh, and died, and was crucified, as he was man,
not as he was God, the word, which was in the beginning; but as he was man,
who bore the sins and iniquities of all mankind,
and was an offering for the sins of the whole world,
who through death tasted death for every man; all being in death in Adam.
So that they might have life through Christ the second Adam: so, I say again,
that Christ did not die as he was God, but as man.
"`He was crucified and buried, and rose again the third day, and ascended,
and is at the right hand of God;`" this he did by the power of God, as he was man.
So the Turks are mistaken, to say, or to think,
that the eternal God could be crucified or die.

Dear friends,
I thought it needful to write a letter to you concerning this their mistake,
which you may be wise in making use of; and my desires are, that you may be preserved,
and exalt God`'s name in your places of captivity, and in your lives, words,
and conversations, answering God`'s witness in the Turks, Jews, Moors, and your patrons.
And keep low, and walk wisely,
that you may be a good savour in the hearts of all there-aways;
and then the blessings of the Lord, and his presence, will rest upon you, and be in you.
I think you have more liberty to meet there than we have here;
for they keep us out of our meetings, and cast us into prison, and spoil our goods.
And therefore prize your liberty in your meetings, and do not abuse it;
and the Lord preserve you all in his grace, fear, and wisdom,
that you may grow up in Christ the head, and walk in him, to the glory of God.
Amen.

Read this openly in your meetings;
and I have sent you here some books that you may read them,
and give them to the Turks or English, as you may see fit; which books are to the Turks,
one concerning good conversation; and another concerning the temple;
and another concerning Abraham instructing his family, and one to all kings and princes;
and another concerning revelation and inspiration, with some others,
to read among yourselves.

And, friends, it would be very well for you,
if you could get the Turks and Moors`' language,
that you might be the more enabled to direct them to the grace and spirit of God in them,
which they have from God, in their hearts; and then getting their language,
you would be able to write and translate any papers to them,
which may be serviceable to instruct them,
and for the spreading of the truth among the Turks and Moors.
So with my love to you.

G+++.+++ F.

Gousey in Essex, the 10th of the 2nd month, 1683.

[.centered]
=== Letter 389.

[.blurb]
==== To all the household of faith, which is the church of Christ, who is the author and finisher of faith; who are to do good unto all, but especially to them of the same faith.

The apostle saith to the church of Christ, "`I wrote unto you an epistle,
not to keep company with fornicators;
yet not altogether with the fornicators of this world, nor with the covetous,
extortioners, idolaters, etc.
For then ye must needs go out of the world.`" 1 Cor. 5.
"`But now I have written unto you, not to keep company;
if any man that is called a brother, be a fornicator, or covetous, or an idolater,
or a railer, or a drunkard, or an extortioner, etc. with such an one, no not to eat.`"
Therefore you see all such are to be avoided, as knowing, neither fornicators,
adulterers, effeminate, and abusers of themselves with mankind, nor thieves,
nor covetous, nor drunkards, nor revilers,
nor extortioners shall inherit the kingdom of God.`"
So ye may see, all such workers you are not to keep company with,
nor so much as to eat with them,
though they have gone under the notion of brothers and sisters.
So the camp of God must be kept clean of such;
for the feast must be kept with unleavened bread of sincerity and truth.
So the old leaven must be purged out; "`For a little leaven leavens the whole lump.`"
And therefore ye must be a new lump, as ye are leavened by it;
"`For even Christ our passover is sacrificed for us.`"
Therefore, (as I said before,) let us keep the feast with sincerity and truth.

And the apostle saith, "`Be ye not unequally yoked together with unbelievers.
For what fellowship hath righteousness with unrighteousness?
And what communion hath light with darkness?
And what concord hath Christ with Baal?
And what part hath he that believeth with an infidel?
(mark, part,) and what agreement hath the temple of God with idols?
Wherefore come out from among them, and be ye separate, saith the Lord,
and touch no unclean thing; and I will receive you, and I will be a father unto you,
(that is, take care for you,) and ye shall be my sons and daughters,
saith the Lord God Almighty.`"

And therefore if God`'s sons and daughters,
must be separated from all such things without, and not to touch them,
neither to have an agreement of unity with them,
nor be yoked with such actions and actors without, and not touch such as act such things.
Then, are they not to be separated from all such actions and actors within,
and not to touch such as act such things, though he be called a brother or sister,
seeing such actions make them infidels, and like Belial, and bring them into darkness?
And if there be no fellowship, communion,
yoking or agreement with such actions and actors without, then what yoking, communion,
or fellowship and agreement, (mark,
agreement,) can there be with such as act such things within,
that is called a brother or sister, or keep company with such, or eat with such,
"`that have a form of godliness, but deny the power?`"

Therefore such lepers that defy the camp of God ought to be turned out of it,
till they be healed and cleansed from such leprosies;
as knowing that such actions and actors are out of the kingdom of God,
and out of the holy city, new and heavenly Jerusalem.
And no unclean thing comes into the kingdom of God, nor enters the kingdom, the holy city.
And none come into the holy city, but by repentance,
and being turned and changed from all manner of evil and uncleanness whatsoever.

The adulterer is brought to a morsel of bread, and the slothful goes in rags.
But the virtuous are happy, and the diligent are rich that serve the Lord.
Therefore have no fellowship with the unfruitful works of darkness,
but rather reprove them.
For the church of Christ`'s fellowship, (that are the believers,) is in the light,
which is the life in Christ.
And so their fellowship is with the Father and the son,
and their communion is in the holy ghost, which proceeds from the Father and the son.
And therefore the church of Christ is to abstain from every appearance of evil.
And if they are to abstain from every appearance of evil,
then they cannot join or have unity with them, where evil appears.

And again, the apostle saith to the church of the Thessalonians,
that they were to "`study to be quiet, and to do their own business,
and to work with their own hands, and to walk honestly towards them that are without;
and that ye may have lack of nothing.`"
So here you may see the diligence in the truth that
the apostle exhorted the church to practise.
First, they are all to study to be quiet.
Secondly, they are all to do their own business, and work with their own hands,
that they may lack nothing.
And thirdly, to walk honestly towards them that are without.
And if they walk honestly towards them that are without,
they must walk honestly to them that are within.
For the apostle had some occasion to write to the Thessalonians upon the matter.
For saith he, "`We hear that there are some which walk among you disorderly,
working not at all, but are busy bodies.
Now them that are such we command and exhort by our Lord Jesus Christ,
that with quietness they work, and eat their own bread.
And if any man obey not our word by this epistle, note that man,
etc. and have no company with him, that he may be ashamed.
Yet count him not as an enemy, but admonish him as a brother.`"
You may see there were not those gross evils charged
upon him as were upon some among the Corinthians.
So you may see the apostle`'s care in the church
of Christ was to keep all things clean and pure,
and all diligent in their places, serving the Lord, and not to be busy bodies,
and talkers about other men`'s business; but to be quiet, and not idle,
but doing their own business, that they may lack nothing;
and so eat their own bread natural and spiritual.

Now the apostle speaks of widows, in his first Epistle to Timothy, chap. 5.
what sort of widows they were to receive.
And ye may see first the decent and lovely practice in the church of Christ:
"`Rebuke not an elder, but entreat him as a father, and younger men as brethren;
and the elder women as mothers, and the younger women as sisters, with all purity.`"
So are these to be entreated; and honour widows, that are widows indeed.
And if any widow have children or nephews, let them learn, (mark,
learn,) first to show piety at home, and requite their parents;
for that is good and acceptable before God.`"
So this piety must be learned and showed at home;
and these the widows must learn to look to.
Here these widow women have a service;
and in the first place they must "`learn to show piety at home,
and to their parents and nephews, and to show it abroad then in the church of Christ.`"
So all must learn this lesson, to show piety to their children and nephews,
and to requite their parents.
For this practice and service is good and acceptable before God.

Now the state of desolate widows, she that is a widow indeed, and desolate,
trusteth in God, and continueth in supplications and prayers night and day.
But she that lives in pleasure is dead while she lives.
These things give in charge, that they may be blameless.
But if any provide not for his own, and especially for those of his own house,
he has denied the faith, and is worse than an infidel,
(mark! that is worse than the world.) For the faith
brings every man and every widow to be diligent,
and to provide for their own; that is, their children and nephews,
or kindred and parents, as before.
But the apostle says, especially those of his own house.
And so here is piety to be shown still two ways; "`for his own,
and especially to those of his own house or family;`" and here are nephews and parents,
as before mentioned.

Again the apostle saith,
"`Let not a widow be taken into the number under threescore years old,`" etc.
Mark, here was a number that the widow was to be taken into;
and the widow that was to be taken into this number,
see her qualifications before she come into the number.
She must be well reported of for good works: "`If she has brought up children,
if she has lodged strangers, if she has washed the saints`' feet,
if she has relieved the afflicted, if she has diligently followed every good work,`" etc.
These are the qualified widows that are to be taken into the number.
So here was a great practice, and a diligence in piety for this woman to do,
before she was received into the number of the faithful.
"`But,`" says the apostle, "`the younger refuse;
for when they begin to wax wanton against Christ, etc. they cast off their first faith,
and withal, they learn to be idle;`" so they forsake to learn and show piety,
and to live in that; and so do not learn to be diligent;
and wander about from house to house, and not only idle, but tattlers and busy bodies,
speaking things they ought not.
And therefore such things were, and are to be reproved;
such as these were not to be received, and taken into the number of the faithful,
but to be refused.

And again the apostle saith, "`I will therefore, that ye younger women marry,
bear children, guide the house,
give no occasion to the adversary to speak reproachfully.`"

And the apostle says, "`If any man or woman that believeth, have widows,
let them relieve them, and let not the church be charged;
that it may relieve those that are widows indeed.`"
So here you may see the care, piety, and duty; if either man or woman that believes,
have widows, they are to relieve them,
and not let the church of Christ be charged with them.
So let men and women learn to show piety to widows, to nephews, and to parents.

And the apostle saith to Timothy, "`I charge thee before God, and the Lord Jesus Christ,
and the elect angels, that thou observe these things,
without preferring one before another; do nothing by partiality,
lay hands suddenly on no man.`"
So here you may see the apostle`'s care in the church of Christ,
who would have all to be exercised in truth and piety, and be diligent in their service,
that truth requireth of them.

And then again, the apostle speaks of such as are lovers of themselves, covetous, proud,
boasters, disobedient to parents, unthankful, unholy, without natural affections,
(to wit, to husband, or wife, children, parents, or others,) and likewise,
truce-breakers, which break their covenant or promises in their marriages,
with God and with man; and so likewise,
break their truce and covenant with men in outward things; and also,
such as are false accusers, incontinent, fierce, despisers of them that are good,
such are not like to be subject to the good spirit of God in themselves; and traitors,
heady, high-minded, lovers of pleasures, more than lovers of God,
having the form of godliness, but denying the power thereof; from such turn away,
says the apostle.
Now if they were to turn away from them, they were not to be heeded,
though they had the form of godliness, and of christianity;
if they were to turn away from them, they were not to receive them into the camp;
for such are as lepers are to be turned away from.
And therefore the camp of God must be kept clean.
And Christ hath given authority to his church to admonish and exhort,
and to reprove and rebuke all such things with authority.

Now, friends, concerning putting on of apparel.
The apostle in the spirit and power of Christ had a care in the church of God,
that they should adorn themselves as becomes the gospel,
with chaste lives and conversations, and with the hidden man of the heart,
in that which is not corruptible, even the ornament of a meek and quiet spirit;
which is in the sight of God of a great price.
This is that which arrays and beautifies God`'s church;
and not the outward adorning and plaiting the hair,
and every new fashion that comes up into the world.
1 Pet.
3+++.+++ And also the apostle writes to Timothy, and gives him that exhortation to the church,
"`That women adorn themselves with modest apparel, (mark,
modest,) with shamefacedness and sobriety, (mark, sobriety,) not with broidered hair,
or gold, or pearls, or costly array.`"
For that was the practice of the Jew outward, and is to this day;
but with that which becomes women professing godliness, with good works.
So this is the adorning that all that profess godliness must be arrayed withal. 1 Tim. 2:9.
So that all may be in that good behaviour,
as becomes godliness and holiness.
And likewise chaste and discreet, teachers of good things;
that the word of God may not be blasphemed, which they profess; as in Tit.
2.

And it is desired, that all Friends, that have children, families, and servants,
may train them up in the pure and unspotted religion, and in the nurture and fear of God;
and that frequently they read the holy scriptures,
which is much better than to be gadding abroad.
And exhort and admonish them; that every family apart may serve and worship the Lord,
as well as in public.
And that when they go to meetings, they may take their servants and families with them,
that they may not go wandering up and down in the fields, or to ale-houses,
as many have done, to the dishonour of God,
and to the dishonour of their masters`' and mistresses`' families,
and to their own ruin and destruction.
And therefore, for Christ`'s sake and his pure religion, let there be care taken,
to prevent all these things.
For such an one as cannot rule well his own house,
having his children in subjection with all gravity,
how can he take care of the church of God.
1 Tim.
3.

And now, friends, concerning marriages, of which very many things have been written,
it is desired that all may be careful in that thing, of running hastily together.
And consider it first; that first, as it is God`'s joining, so it is his ordinance,
and it is honourable in all, and the bed undefiled.
And again, such men as draw out young women`'s affections, and run from one to another;
and leave them, and run to others.
And such women as draw out men`'s affections, and then leave them,
and draw out other men`'s affections: these practices bring many young women,
and many young men into trouble; and are sharply to be reproved.
For this work is not of God`'s joining, but out of his covenant.
Some of which have gone so far, as to promises, espousals, and contracts,
and then left them, and gone to others.
This is to be judged and reproved.
For, as we make no contract for marriages, we break none.

And likewise such young people, that trim up themselves in gay apparel,
and make a great show, and hang most on their backs,
that appear what they are not in substance;
which women have sometimes deceived young men; and men deceived women,
and drawn out their affections and minds by outward show,
and deceived one another and brought one another into trouble.
Such are out of the fear of God and a chaste mind.
And therefore they are not like to expect a blessing in this life,
nor in that which is to come, without great judgment and repentance.
Therefore such actions are to be reproved, that they may be brought into chastity,
virtue, and piety, and to the adorning the hidden man of the heart,
which is not corruptible, and the ornament of a meek and quiet spirit;
which ornament or adorning is acceptable with the Lord.
For after this manner, in old time, the holy women, who trusted in God,
adorned themselves.

And likewise such, as after they are married break their covenant in marriage,
such go from the spirit of God, and his joining,
and from the spiritual society of God`'s people, and their unity and fellowship.
Such are to be reproved by the spirit of God.
And if they do not return after reproof,
Friends cannot have unity or fellowship with them, but turn away from them;
though they may have the form of godliness, and have been called a sister or a brother,
but have denied the power of godliness.
Therefore all must abide in Christ the vine,
if they bring forth fruit to the glory and praise of God.
Amen.

The apostle says, "`Now, we command you, brethren, in the name of our Lord Jesus Christ,
that ye withdraw yourselves from every brother that walks disorderly,`" etc.
2 Thess.

Now, dear friends, consider old Eli`'s case, who did admonish his children;
but because he did not restrain them from the follies and the evils they run into,
therefore the Lord brought his judgments upon him, that he lost his children`'s lives,
and his priesthood, and his own life.
And do you think, that this was not written for an example, that others should be warned,
hear, and fear?
And was not the gospel and the law given forth to restrain people from sin and evil,
and such things as dishonour God?

G+++.+++ F.

[.centered]
=== Letter 390.

[.blurb]
==== An epistle to all Friends everywhere.

[.salutation]
Friends,

This is the word of the Lord unto you all.
All live in the seed, in which all nations are blest;
in which seed you are blessed every way, in your rising up and lying down;
in your goings forth and comings in.
And you have the blessings from above, and the blessings from beneath, in this holy seed;
yea, the blessings of him that dwelt in the bush, that made the very ground holy,
that Moses trod upon, who brings you out of the world, which is as a bushy,
thorny wilderness, that ye might dwell in this blessed seed,
in which all nations are blest; which bruises the serpent`'s head,
who was the first questioner, and tempter, and liar, and deceiver;
and man and woman by hearkening or giving ear to this questioner, liar, and tempter,
the serpent, they fell from their habitation in the image of God,
and so went out of their habitation and service, that God had placed them in,
and commanded them to do.

But, the seed of the woman is come, that bruises the serpent`'s head,
in which seed Christ, all nations are blest.

And all you who live and walk in this seed,
you live in him that bruises the serpent`'s head, that liar, tempter, and questioner;
yea, and every one by this seed Christ, may be renewed up into the image of God,
as Adam and Eve were in, in the beginning.
Then you are all in your habitations of life and truth, and the image of God;
and in it you know your services, that the Lord God Almighty commands you.
And you living in this holy seed, you live over all vain unruly talkers,
and vain disputers, men of corrupt minds, which have the form of godliness,
but deny the power thereof:
All you that live in the seed that bruises the serpent`'s head, turn away from such,
for their work is to destroy; whose words eat as a canker; who do profess truth in words,
and may have the form of godliness, but in their works deny the power thereof,
who are to every good work or service reprobated.

And these are as the raging waves of the sea and tempests,
they are known by their tempestuous spirits, and its raging, like a raging of the sea,
casting up mire and dirt; a murdering spirit, like Cain; a gainsaying spirit, like Korah;
and erred from the true spirit, like Balaam.
No rain in their clouds, no water in their wells, nor fruit on their trees; twice dead;
that is once dead, and made alive, and dead again; so they cannot grow in the truth,
light, nor the spirit of God, nor his gospel; but such corrupt the earth,
and corrupt people`'s minds; are sowers of discord, strife, and contention;
co-workers with the serpent to beguile the unstable minds;
all such the seed of God reigns over.

And therefore in this holy seed Christ, all live and walk,
and shun such evil spirits and their works;
and all be established in this seed Christ Jesus, that the serpentine spirit,
either by its strife, vain jangling, vain disputing, or its sowing of dissention,
tempting and questioning, nor with feigned, fair, flattering,
enticing words may not draw you out of your habitation of the seed, Christ Jesus;
and the image of God, and your work and service in it, that God and Christ commands you.

And therefore beware of this serpentine spirit, that you may not be deceived, as Eve was;
and beware of dogs that will bite and devour you; and beware of evil workers,
though they have never such fair words to deceive the hearts of the simple.
Beware of false prophets, which are inwardly ravened from the spirit of God,
and are become wolves, though they have got the sheep`'s clothing,
and the words of truth, of Christ and his apostles,
whose fruits are as thorns and thistles.
But the seed Christ, that discovers all these things, in him live, grow up,
and walk and be established.

And beware of the leaven of the Pharisees,
who make an outward profession of the holy men`'s words, but are persecutors of the seed,
Christ Jesus, in whom all nations are blest, and despisers of his peaceable government;
of the increase of which there is no end.
And into this blessed seed, the serpent cannot come,
nor any of his instruments nor his angels, which are evil spirits.
And all the doters about questions and strife of words, and the vain janglers,
and vain perverse disputers and contenders, and the sowers of strife and dissention,
makers of debate and strife: all these are out of the blessed peaceable seed;
although they may profess the truth of all the new and old testament in words,
without the power of God, (that they are turned away from,
and therefore they are to be turned away from,) the trumpet of the Lord,
his spirit and power is blown against them,
though they have never such high swelling words of vanity,
and have never so many flattering fair words and good speeches,
and trimmed and decked with the sheep`'s clothing, yet they are in the wolf`'s nature,
and whored from the lamb and his nature, and so from the seed Christ,
in whom all the children of the kingdom and the elect are to walk,
that are of his heavenly and spiritual generation,
and grow up in him as trees of righteousness, whose fruits are unto holiness,
and whose end will be everlasting life.
And the end of that spirit and its fruits, before mentioned,
that are out of Christ and his peaceable truth, will be destruction in the lake of fire.
And that is the word of the Lord to you all; therefore be warned what you join to,
and what you lay hands on suddenly.

For I remember, before we were called Quakers,
as I was sitting in a house in Nottinghamshire,
(about the year 1648,) the word of the Lord came to me and said,
"`Some of those that should come to be convinced with the light and spirit of God,
and should come so far as Cain to hear God`'s voice,
and as far as Balaam to hear God`'s voice, and to have some openings,
and to come so far as Korah, Dathan, and Abiram, these should be the deceivers,
and the troublers of the church of Christ, and seek to destroy the faithful,
and to betray them: who formerly had some experience to talk of,
but did not live in the truth.`"
Which I and many others have seen come to pass and fulfilled.

For Christ said to his disciples, that the false prophets and the antichrists,
(which were inwardly the ravened wolves,
which the apostles and believers should beware of,) should come to them, to try them,
they had the sheep`'s clothing, and outward profession of christianity,
but were inwardly ravening wolves to devour them.
Now, these were inwardly ravening from something.
And the apostle John speaks of such as went out from us.
It seems, they were once among them, "`but,`" (saith he,) "`they were not of us;
for if they had been of us, they would no doubt have continued with us:
but they went out from the true church,
that they might be manifest that they were not of it.`"
And these were the antichrists and false prophets, that Christ said should come,
which John and the apostles saw were come, and exhorted the church to beware of,
and to keep to the unction which they had from the Holy One.
And this unction and anointing, as it abides within the saints, the true church,
and they in it, it will teach them all things, and is truth;
and by it they shall continue in the son and the Father, and so in the holy seed, rock,
and foundation, that cannot be shaken.

And the apostle said, "`there was to be a falling away first,
before the man of sin was revealed; the son of perdition,
who opposeth and exalteth himself,`" etc.
And when the apostle saw the mystery of iniquity already working;
"`and his coming is after the working of Satan,
with all deceivableness of unrighteousness in them that perish,
because they receive not the love of the truth, that they might be saved.`"
And such go into strong delusions, that they should believe a lie, and not the truth.
And here you may see there is a falling away, before the son of perdition, or Judas,
be revealed; and they that fall away, receive not the love of the truth,
that they might be saved, but believe lies, that they shall be damned.
And the Lord will consume him with the spirit of his mouth,
and will destroy him with the brightness of his coming, the wicked one,
and son of perdition, that is against the righteous,
and is the opposer and betrayer of them.

Therefore all the church of Christ are to stand steadfast and be established in him,
in every good word and work,
who are from the beginning chosen for salvation through Jesus Christ,
through the sanctification of the spirit, and the belief of the truth,
and are called by the gospel, the power of God,
to the obtaining of the glory of the Lord Jesus Christ,
in whom the glorious rest and peace is.

And you may see how the church of Christ was troubled by such as went out from them,
and fell away from truth, and inwardly ravened.
Some went like unto the swine into the mire; and some like the dogs to the vomit;
and some like wolves that inwardly ravened, and yet kept the sheep`'s clothing.
Some went into the nature of Cain, sacrificers, and yet were destroyers of the righteous;
and some went in the nature (or spirit) of Jannes and Jambres, that withstood Moses;
and others in the nature of Judas to betray; and others in the nature of Korah,
Dathan and Abiram, to gainsay and resist the truth; and others in the nature of Jezabel.

And this spirit and nature troubled the church in the old testament,
and troubled the church in the new testament,
and are troubling the church of Christ in this gospel day,
that is come and coming out of the apostacy.
But God`'s trumpet, spirit, and power, was and is always sounded against it,
that all people may beware of this evil spirit and nature,
and keep in the seed Christ Jesus, that bruises the head of it, in whom you have love,
rest, salvation, quietness and peace.
Hallelujah.

And all dwell in love, then you dwell in God, who is love;
let that be all your habitations, which love edifies the body of Christ,
and builds you up in him, and all strive to excel one another in virtue, in patience,
courteousness, kindness, tenderness, meekness, and humility, in temperance, modesty,
and chastity; and whatsoever things are decent and comely, and of good report, honest,
and lovely, those follow: for these are the good fruits of the spirit of God,
and his heavenly seed; which fruits are acceptable to God,
and will make you all lovely and comely to him,
and unto one another in his heavenly seed; in which (as I said before) you are blessed,
and all nations are blessed; which seed (Christ) is your sanctuary,
who destroys the devil the destroyer, and so is over him, and was before he was,
in whom the true believers live, and have peace, who clothes them with salvation,
and with his righteousness, the sanctified one`'s fine linen.

So all walk worthy of the mercies of God and his blessings from above, and from below,
to the glory and praise of God.

And they that dwell not in love and charity, are like the sounding brass,
and tinkling cymbals; as you may read, 1 Cor. 13:1-8.

This you may read amongst the children of the light, and of the day.

G+++.+++ F.

Dolston, the 13th of the 10th month, 1683.

[.centered]
=== Letter 391.

[.blurb]
==== To the meeting of friends in truth, that are captives in Algiers.

Now, dear friends, the Lord having drawn you by his spirit to his son Christ Jesus,
in whose name ye come to be gathered, in whose name ye have salvation,
and not in any other name under the whole heaven:
so that now you come to know Christ your saviour, who destroys the destroyer,
the devil and his works; and it is he, that brings forth everlasting righteousness,
that makes an end of sin, and finishes transgression.
So that now, you may live and walk in the everlasting righteousness of Christ Jesus,
who is your priest that is made higher than the heaven, Heb. 7.
and who is your prophet, that God has raised up, and not man,
whom ye must hear in all things, Acts 3:22.
and 7:37. who were as lost sheep gone astray;
but are now returned to the chief priest and bishop of your souls;
namely, Christ Jesus. 1 Pet. 2:25.
And Christ saith, he is the true shepherd,
that hath laid down his life for his sheep; and his sheep know his voice and follow him:
who is the holy and just one, and never guile was found in his mouth.
And Christ says, no man comes to the Father but by me.
So he is the new and living way; and God has given him for a leader and counsellor,
to counsel his people; who is the holy living rock and foundation,
which is above all the rocks and foundations below:
for he the rock and foundation is from above, whom all the children of the light,
that believe in his light, which is the life in him, and are grafted into him,
do build upon.
And so, the Lord God Almighty with his eternal power support you all,
in all your afflictions and sufferings, trials and temptations,
that you may be built and settled upon this rock and foundation, that cannot be shaken.

And now, dear friends, my desires are,
and the desires of Friends here that you may all walk soberly, honestly, modestly,
and civilly, and lovingly, and gently, and tenderly, to all your patrons,
and to all people.

And, that ye may walk righteously, justly, and holily in all your words, dealings,
and doings; that his name you do profess now, may be honoured, and you may reach,
by your righteous godly lives and conversations, the good in all your patrons,
and in all others; so that you may show forth the fruits of the spirit,
and the fruits of christianity;
and that you are the possessors of Christ Jesus your mediator,
who has made peace betwixt you and your God.
And as you have received Christ, so walk in him,
and know him to rule in your hearts by faith.
For herein (as Christ said) is my Father glorified;
that you bring forth much heavenly fruit,
and that your spiritual and heavenly light may shine before men,
that they may see your good works, and glorify your Father which is in heaven.

And now, friends, we understand, that some that have come lately among you,
have been under great sufferings and abuses by their patrons,
because they cannot honour them with that honour as other slaves do,
or as they have done before.
Now, if you wait in patience upon the Lord in his truth, (for you are to buy the truth,
and not to sell it; and truth is that that is stronger than all,) the Lord in his time,
(though he may try you,) can mollify that nature in them there,
as he hath done in other places, where he hath tried his people with such things.
And when they have seen, it is for conscience`' sake towards God,
and it is from the principle of truth and the spirit;
in which spirit and truth they worship the Most High God, who is an eternal,
incomprehensible spirit, who is God in heaven and God in the earth,
and dwells by his spirit in his humble people, they have been overcome.

And now, friends, consider, they are blessed that suffer for Christ`'s sake;
and it is not only given you to believe, but to suffer for his name.
And they that will live godly in Christ Jesus must suffer persecution:
But the apostle says of the true christians,
"`Who shall separate us from the love of Christ?
Shall tribulation, or distresses, or persecution, or famine, or nakedness, or peril,
or sword?
As it is written, for thy sake are we killed all the day long:
we are counted as sheep for the slaughter;
in all these things we are more than conquerors through him that loved us.
I am persuaded that neither death, nor life, nor angels, nor principalities, nor powers,
nor things present, nor things to come, nor height, nor depth, nor any other creature,
shall be able to separate us from the love of
God, which is in Christ Jesus our Lord.`" Rom. 8:36-39. Ps. 44:22.

Now, dear Friends, you may see here was a godly sincerity, fervency, steadfastness,
and resolution in the true christians, which ought to be in all such now,
without boasting.
And the apostle says, "`Rejoice, forasmuch as ye are partakers of Christ`'s sufferings,
that when his glory shall be revealed, ye may be glad also with exceeding joy:
for if ye be reproached for the name of Christ, happy are ye:
for the spirit of glory and of God rests upon you.
On their part he is evil spoken of, but on your part he is glorified.`" 1 Pet. 4:13-15.

And so, dear friends, be wise, that you may give no just occasion:
and keep low in the humility; for such learn of Christ, and the meek follow him.
And so my desire is, that you may all be preserved to the glory of God;
and that you may be valiant for the truth upon the earth, and spread it abroad,
that all may come to the spirit of God, that God poureth upon all flesh,
and to serve and worship him.
And so that all flesh may see the glory of God, by his spirit;
and that all might come to the light, which is the life in Christ the word,
by whom all things were made and created,
with which light he enlighteneth every man that comes into the world, to believe in,
and to love it, and to try their works,
"`whether they be wrought in God, yea or nay.`" 1 John 3:19-21.

And that all might come to the grace of God, which hath appeared to all men,
and brings salvation, which will teach to live godly, righteously, and soberly,
and deny unrighteousness.
This is the true christian`'s teacher, which brings salvation,
and teacheth to deny that which would lead them into destruction, into ungodly,
ungracious ways and words; but this grace teacheth the saints to walk in gracious ways,
and their words come to be seasoned with grace, which teaches them,
and brings their salvation.
So that which is the true christian`'s teacher, brings their salvation.

And so every one sit under this teacher, as the true church of Christ did;
as you may see, Tit. 2:11-12.

And so, dear friends, I do commend you to him that has all power to support,
who is God all-sufficient to supply you,
and is near unto all that call upon him in truth and righteousness.
Therefore cast your care upon him; for he cares for you: and so,
as you walk in the truth, to answer the truth in your patrons and others,
you will see in time, you will reach the good in them,
that they will give more credit to you,
and trust you more than them that disobey the spirit of God in their hearts.
So the Lord preserve you faithful to himself.

G+++.+++ F.

Let us hear as often as you can how things are with you

London, the 4th of the 3d month, 1684.

[.centered]
=== Letter 392.

[.blurb]
==== To the Quarterly and Monthly Meetings in England, etc.

Dear friends and brethren in the Lord Jesus Christ, who reigns over all,
and has all power in heaven and earth given unto him,
by whose eternal power our meetings this year have
been preserved unto his great glory and honour;
and his living refreshing presence has livingly been amongst us,
for which his people do give him the honour, glory, thanks, and praise,
who is Lord over all, and worthy of all, blessed forever and ever.
And therefore we desire and entreat all our friends and brethren everywhere,
who are of the seed of the promise, and the children of the kingdom of God,
and of the new covenant of light and life, to walk in the same, and worthy of the same,
to the glory of God.

And you that do profess the primitive, pure, and undefiled religion,
which is above all the religions in the world, show it forth in life and practice.

And you that profess the worship of God in the spirit and truth,
which Christ hath set up, which is above the Jews`' worship,
and all the worships that the men of the world have set up, be steadfast in the same;
for all worships out of God`'s spirit and his truth, are idolatry.

And now, dear friends and brethren,
who profess and possess that which is above all religions, ways,
and worships in the world; our desire is,
that you may always outstrip and exceed the world in virtue, in purity, in chastity,
in godliness, and in holiness, and in modesty, civility, and in righteousness,
and in love, with that you may overcome the evil, and with the good overcome the bad:
so that your moderation and sober life may appear unto all men,
and answer that of God in all,
that so the fruits of the spirit of God may show themselves forth in meekness,
and kindness, and humility, from the holy understanding, and the pure heavenly wisdom,
and the word of life and patience, by which all things were made,
in that you will be able to bear all things and endure
all things through him that strengthens you.
And whatsoever things are lovely, decent, or comely, and honest, and of a good report,
that answers the truth in all, that mind and practice,
that God Almighty may be glorified through you in the seed,
in which all nations are blest, which bruiseth the head of the serpent,
that brought the curse; in which seed no enmity nor strife can come; in which seed,
Christ Jesus, your heavenly unity and fellowship is preserved.

And whatsoever storms or tempests should arise in the world,
keep in the seed Christ Jesus, your sanctuary, who was before the world was,
who is your saviour, that destroys the destroyer, in whom you have all life, peace, rest,
safety, and salvation; in him, who is the Amen, the first and last, in him farewell,
and from him the blessings of the Lord rest upon you.

G+++.+++ F.

[.centered]
=== Letter 393.

[.blurb]
==== To Friends in Holland.

Dear friends in the peaceable truth,

The glory of God all mind, in all your lives and conversations,
and that the heavenly fruits of the holy spirit of
God you may all bring forth to his praise,
living in righteousness, godliness, and meekness, lowliness, and humility,
learning of Christ Jesus your saviour, who is meek.
For the humble God doth teach, and they grow up in his grace and favour.
And therefore all take heed of going back again into the world`'s ways, spirit,
and words, but keep to the holy spirit of God, that doth lead you in the narrow way,
that is to life eternal.
And in the Lord`'s light, power, and spirit meet together,
and keep your meetings in the name of Jesus Christ,
who hath all power in heaven and earth given to him,
that you may feel his living and divine presence among you, and in his pure, gentle,
and heavenly love and wisdom, you may be valiant for the name of Jesus,
and his truth upon the earth, and not to be ashamed of Christ your teacher and prophet,
that God hath raised up in his new covenant and testament, whom you are to hear.
Neither be ashamed of Christ your shepherd, who hath laid down his life for his sheep,
whose voice you are to hear; who doth feed his sheep, and give them life eternal,
and none is able to pluck his sheep out of his hand, his power.
Neither be ashamed of your high priest, who hath offered up himself for you,
and doth sanctify you, who is a priest made higher than the heavens.
Neither be you ashamed of your bishop, and the chief shepherd of your souls,
to whom now ye are returned by his grace and truth,
who doth oversee you with his heavenly eye, that you do not go astray from God.
So in him let your faith stand, who is the author and finisher of it.
So with my love to you all in the Lord Jesus Christ, who is your sanctuary,
in whom you all have life, peace, rest, and salvation, who is the Amen.

"`Greet ye one another with a kiss of charity.
Peace be with you all that are in Christ Jesus.`"
Amen.
This charity keeps all God`'s people in the heavenly love and unity.

G+++.+++ F.

Amsterdam, the 14th of the 4th month, 1683.

[.centered]
=== Letter 394.

Dear friends and brethren,
who are elect and chosen in Christ Jesus before the foundation of the world;
in Christ you have peace, and in the world you have trouble.
But "`be of good cheer, Christ hath overcome the world,`" that lieth in wickedness,
and all the persecutors in it; and in him you all overcome the devil and his works,
and "`without him you can do nothing;`" but through Christ, and his power and strength,
you will be able to do all things according to the will of God.
And though for a time ye may suffer for the name of Jesus, and for his truth,
and be cast into prison, and suffer the spoiling of your goods; the eternal God knows,
and his son Christ Jesus, it is for him alone, and his truth`'s sake, we suffer,
and not for any evil doing, or doing wrong to any man.
And so the Lord hath given us not only to believe,
but also to suffer for his name and truth`'s sake; and so it is the gift of God,
with his eternal spirit and power, that doth uphold us in all our sufferings,
which hath made so many to finish their testimony for the truth in jails and prisons;
and not to love their lives to the death,
but love God and Christ Jesus above their lives, and all outward things;
as practice and experience have declared it.

And now, dear friends, be faithful in Christ Jesus to the end,
that you may all have the crown of life, and that peace from Christ Jesus,
which the world, and all the apostate spirits from the truth, cannot take away from you;
I say, neither the world, with their outward persecutions and spoiling of goods,
nor the apostate spirits from the peaceable truth, with all their lies and defamations,
and their filthy, scandalous books, and evil tongues,
though they be like the raging waves of the sea, casting up mire and dirt,
whose folly is manifest to all that hear and see them;
yet all this cannot disturb the peace of the righteous.
And all the restless, unquiet, unruly murmurers and complainers,
that are filled with false jealousies, and are the wandering stars,
who are wandered from the witness of the Lord in their own hearts;
such their judgments do not linger, nor their damnation doth not slumber,
though they may be suffered for a time to try God`'s people.

And now, friends, you know envious Cain was a sacrificer as well as Abel,
but out of the faith and righteousness, who murdered his brother Abel,
he may be said to have been a type of Judas, who was a partaker of the ministry,
yet betrayed his master.
And you read that Ishmael and Esau were circumcised as well as Isaac and Jacob;
but Esau hated Jacob, and would have slain him; and Ishmael scoffed at Isaac,
and so he that is born of the flesh persecuteth him that is born of the spirit;
and that birth is not heir with the seed of the promise,
though it may come into the outward form, and outward profession.

And likewise you read of Korah, Dathan, and Abiram, and their company,
and their rebelling against the Lord, and his servants, Moses and Aaron,
and of their false liberty; but what became of them, in Numb. 16. you may see.

And likewise how that the Jews (after the Lord brought them out
of Egypt) made themselves a calf of their jewels and ear-rings,
as in Exod. 32. Ps. 106:19.
The Jews made a calf in Horeb, and worshipped the golden image,
and forgot God their saviour, who had done great things in Egypt,
and wondrous things in the land of Ham, and murmured in their tents,
and hearkened not to the voice of the Lord.
And therefore God overthrew them in the wilderness,
and they came not into the promised land.

And you read how the Jews run into false liberty in the days of Balaam,
and joined with Baal-Peor, and how the anger of the Lord was kindled against them,
and what a destruction he brought upon them,
who had turned against the Lord and his faithful people; as in Numb.
25.

And likewise how often the Jews murmured against Moses and Aaron,
and what a destruction came upon them in the wilderness,
that none of that old stock the Lord brought out of Egypt that dishonoured him;
though they had seen his glory, none entered into the land save Caleb and Joshua,
but they perished in the wilderness for their murmuring and rebelling;
and therefore take heed of murmuring and rebelling against the Lord and his spirit,
but in all things learn to be content.

And also you read in Judges, how often the Jews forsook the Lord,
and what judgments came upon them; and also how the Jews turned against the prophets,
and imprisoned and persecuted them: and in the days of the kings, as in the Chronicles,
how David and many of the prophets, and the righteous suffered:
but what became of them that made them stiffer?
And likewise in the days of Christ, and his apostles, how did they suffer,
by the professing Jews!
And there were many comers and goers in the days of Christ that could say, "`Lord,
Lord:`" but such do not enter into the kingdom of God, except they do the will of God.

And you read how the apostles and the true church
were troubled with false Christians and false brethren;
whom Paul writeth against in many of his epistles, and Peter, and John, and Jude;
and John in his Revelations.
And therefore, all Friends, dwell in the seed Christ Jesus,
in whom ye cannot be deceived,
"`who bruises the head of the serpent,`" who is the head of all deceivers;
and the head of all enmity, and false ways, worships, and religions;
and the head of all false liberties: but in Christ Jesus,
in whom all nations are blessed, is the true liberty.
In him all stand fast, so far as he hath made you free; and in him all walk,
as ye have received him, to the praise and glory of God:
in whom you have all eternal life, peace, rest, and salvation;
and in him the Lord God Almighty preserve you all in love, unity, and fellowship.
Who is able to support you, and supply you with his eternal hand and power,
with what you do need in all your sufferings and trials.
Amen.

G+++.+++ F.

[.centered]
=== Letter 395.

[.blurb]
==== To Friends at the Yearly Meeting in York.

Dear friends, who are turned to the light, and are the believers in the light,
which is the life in Christ, my desires are, that you may all be established upon him,
your eternal rock and foundation, and grow up in Christ Jesus, the second Adam,
by his light, grace, and truth, that is come from him;
for you know Christ had many enemies, (and his disciples and followers,
and Moses in the time of the law,) such as turned their backs on the Lord,
and erred from his good spirit, and rebelled against it, they turned against the Lord,
and Moses and Aaron, and they went from the fellowship of the law of God and his spirit,
and then destruction came upon them:
such Jews were they that rebelled against Christ and his apostles,
and yet were great professors of the Old Testament.
And such that were called christians, that got the form of godliness,
and the fair speeches, and good words, but denied the power thereof,
and so the order thereof: such as these separated themselves,
and erred from the spirit and the faith, and so from the unity of the faith,
and the fellowship of the spirit of God.
Such were and are to be turned away from by all them that are in the faith,
and the spirit of God; and all the spiritual witnesses in the tabernacles of Gad,
testify against such,
though they may make a great profession of Christ and the apostles`' words,
but deny the power, and err from the spirit, and the peaceable truth:
such cannot be the true worshippers of God in the spirit and truth: and therefore,
friends, you that have been turned to the light, and truth, and grace of Christ,
and know the power and spirit of Jesus, walk in the same, and in it keep your fellowship,
and your dominion, over all that which is out of the truth, and abides not in the truth:
and that your heavenly light may shine,
and you may all be kept in love and unity in the same light, power, and spirit,
to the glory of God, and the comfort one of another.
Amen.

G+++.+++ F.

London, the 27th of the 3d month, 1684.

[.centered]
=== Letter 396.

[.blurb]
==== To the suffering Friends of Dantzic.

Friends, with my love in the Lord Jesus Christ to you, who is your saviour and prophet,
that God has raised up for you, to hear in all things; your shepherd,
that has laid down his life for you, whose voice ye must hear,
who will feed you in his living pastures of life, who is your priest,
that offered himself for you, who sanctifies you, that he might present you to God:
so is become your high priest, who is made higher than the heavens;
so is a higher priest than the priesthood of Aaron,
and all the priesthoods upon the earth, that are made by men below:
for he is a high priest, made higher than the heavens.
Heb. 7. And so, is the chief shepherd and bishop of your souls, to oversee you,
that you do not go astray from God, who is your sanctuary,
in whom you are preserved from the destroyer; who destroys the devil,
the great destroyer, and his works, and bruises his head, and breaks his power: he,
namely, Christ, is your saviour; in him you have rest and peace,
salvation and life eternal.

Now, dear friends, we do hear and understand,
that the magistrates have cast you into prison again in Dantzic;
and that they have proffered you your liberty, upon condition that you would go away,
or forsake your common meeting place, or divide yourselves into several little meetings.
Truly, friends,
we have had many of these proffers made to us within these twenty or thirty years,
but we never durst make such bargains or covenants,
to forsake the assembling of ourselves together, as we used to do;
but did leave our suffering cause wholly to the Lord Christ Jesus,
in whose name we were gathered, who has all power in heaven and earth given unto him:
and the Lord at last did and hath tendered the hearts of
many of our persecutors both in England and other places;
and therefore in the spirit and power of the Lord Jesus Christ,
it is good to be faithful;
who is God all-sufficient to support and supply you all in whatever you do,
and strengthen you in all conditions.
For if that should get a little advantage upon you, and get you into weakness,
it would not rest so, but get more upon you.
And therefore it is good to stand fast in the liberty in Christ Jesus, the second Adam,
the Lord from heaven, who, hath made you free out of the snares, and bondage,
and limitations of the wills of the sons of old Adam.

And whereas some of the magistrates have alleged that Christ
departed out of the coasts of the Gadarenes upon their request,
after he had cast the devils out of the possessed men, and they entered into their swine,
and run into the sea.
This argument is of no weight, for you to go out of their coasts or city,
who are settled citizens, and have wives and families;
for Christ went up and down from place to place and preached; as he said,
"`The son of man hath not where to lay his head, though the subtle foxes had holes,
and the high-flown fowls had their nests.`"
And would they take it kindly themselves, if the king of Poland, their protector,
who is of a contrary profession, should use the same argument to them, and say, begone,
or else do not meet at your great public places of worship, but meet in small companies,
or else to depart out of these coasts, as Christ did out of the coasts of the Gadarenes.
And if you do not, then you are disobedient to Christ`'s example;
as they do apply it upon you.
And so, let them weigh the matter and their argument with the just law of God,
to do unto you as they would be done unto themselves.

And now, dear friends, I desire, however, that you walk wisely, and gently, and lovingly,
and meekly, and soberly to all the magistrates, and all people,
that they may have no just occasion in any thing against you.
For the good must overcome the bad, as the apostle says,
"`Overcome evil with good,`" and dwell in that love that can bear all things,
and endure all things.
And nothing can separate you from this love which you have in God through Jesus Christ.
In this love build up and edify one another,
that by it you may answer the good in all people, and spread his truth abroad,
and be valiant for that upon earth.
So in his holy, peaceable truth, and his seed Christ Jesus,
in which all nations are blest, God Almighty preserve and keep you to his glory.
Amen.

And now, dear friends, you that have stood such hard and cruel sufferings so long,
for the Lord`'s name and truth, and could not be overcome by cruelty,
take heed now lest you be overcome by fair words and flattery;
for in that there is a greater danger.

G+++.+++ F.

[.centered]
=== Letter 397.

[.blurb]
==== An epistle to Friends, against pride, haughtiness, and the vain customs and fashions of the world.

[.salutation]
Friends,

Here you may see how the holy men of God testify, against pride, haughtiness,
high-mindedness, and the abominable customs and fashions,
and the ungodly lusts of the world, which are not of the Father, but of the world.
And how man and woman came into these things by forsaking the Lord,
and so falling from his image.
And now Christ renews them up into the image of God again, to serve him in humility.
And all that are in the image of God are of one mind.

=== To all Friends and Brethren everywhere.

Peace from God and the Lord Jesus Christ be multiplied in you, who by his grace, light,
and spirit, are turned towards the Lord, to receive it from him;
and that by it you may grow up in the Lord Jesus Christ,
out of the world`'s nature and spirit.

For Christ said unto his believers and followers, "`Ye are not of the world,
even as I am not of the world.
I have given them thy word, and the world hath hated them,
because they are not of the world.`"
And therefore, as the apostle saith.
"`love not the world, nor the things of the world,
for the love of the world is enmity to God.`"

And in the beginning God created man in his own image.
So in the likeness of God created he him; male and female created he them,
and God blessed them.
And in this state God set them above all things that he made.
But, after man and woman had transgressed the command of God,
they sowed fig leaves together to make them aprons; for their eyes were opened,
and they came to see their shame.
By their transgression and by transgressing the command of God,
the spiritual eye came to be shut, and man and woman came to fall from the image of God.

And so, after man and woman had transgressed the command of God,
and fallen from his image, the Lord God made coats of skins to clothe them withal.
So, you may see, that the first covering which Adam and Eve made after transgression,
was made of fig leaves; and the natural sun would soon scorch and dry them to powder.
But those that the Lord made them, was of skins.

So the transgression of the command of God came, when the ear went out after the serpent,
and the eye went after the fruit of the tree, which God forbid them to eat of.
So here they came to see their outward shame and nakedness;
who had fallen from the image of God that covered them;
and therefore they went to cover the outward shame.

And now man and woman in the fall, are taking thought what they shall eat and drink,
and what they shall put on.
And this is come upon them by forsaking the Lord`'s teaching,
and following the serpent`'s.

And doth not John say, "`Love not the world, neither the things that are in the world.
If any man love the world, the love of the Father is not in him.`"
And farther saith, "`For all that is in the world, the lust of the flesh,
the lust of the eye, and the pride of life; this is not of the Father, but of the world;
and the world passeth way, and the lust thereof.`"

Now, all may see, what man and woman is fallen into by transgressing the command of God;
and therefore it is not good for any to live in that which will pass away,
and is not the Father but of the world.

And you may see how pride is cried against throughout the scriptures of truth.
And they that fear the Lord, do hate evil, pride, and arrogancy.
"`By pride cometh contention, and a man`'s pride shall bring him low;
but honour upholds the humble in spirit.`" Prov. 29:23.

"`For when pride cometh, then cometh shame; and pride goeth before destruction,
and a haughty mind before a fall; but with the lowly is wisdom.`" Prov. 6:2.
and 16:8. "`And better it is to be of an humble spirit with the lowly,
than to divide the spoil with the proud.`"

And Isaiah saith, "`The Lord of hosts hath purposed to stain the pride of all glory,
and to bring into contempt all the honourable of the earth.`" Isaiah 23:9.
And therefore love not that which God will stain.

The Lord saith, "`he will spread forth his hands in the midst of them,
as he that swimmeth, and he will bring down their pride.`" Isaiah 25:11.
And therefore it is good to keep it down in every one.
And the Lord cries, "`Woe to the crown of pride,
whose glorious beauty is a fading flower;`" and "`when
the crown of pride is trodden under foot,
the Lord of hosts shall be for a crown of glory.`" Isaiah 28:1,5.

And the Lord saith,
"`He will mar the pride of Judah, and the great pride of Jerusalem.`" Jer. 13:9.

And doth not Jeremiah say, "`Because of the pride of Moab, he was so exceeding proud,
his loftiness, his arrogancy,
and the haughtiness of his heart brought him into derision.`" Jer. 48:26,29.

And therefore it is good to keep in the humility;
for pride is that which deceives the heart, and brings the judgments of God. Jer. 49:16.
And therefore take heed, let not pride bud, lest the rod blossom.
Ezek. 7.
to verse 11.

And the children of Israel, were grown in pride and fulness of bread, like Sodom,
when they transgressed against the Lord, like their father Adam.
And therefore let them that profess themselves christians take heed,
lest they be found in the same steps.

And see in Ezekiel 16:49. what became of Sodom, and the children of Israel.

And when Nebuchadnezzar confessed the kingdom of God, and praised, and extolled,
and honoured the king of heaven, and said, "`All his works are truth,
and his ways judgments; and those that walk in pride, God is able to abase.`"
Dan. 4:34, etc.

And Hosea saith, "`The pride of Israel doth testify to his face;
and therefore Israel and Ephraim shall fall in their iniquity.
And Judah shall fall with them.`" Hos. 5:5.

And therefore you may see, and take heed of pride,
for it is the cause of man and woman`'s fall.

And in Hosea 7. you may see that pride hath hindered man from seeking after the Lord,
and turning to him.
And you may see Edom`'s destruction was for his pride.
Obad.
1.

And you may see the judgments that came upon the Philistines, and Moab, and Ammon,
and Ashur for their pride.
Zeph.
2.

And in Zechariah 10. and 11. chapters, doth not the Lord say,
"`The pride of Jordan shall be spoiled, and the pride of Assyria shall be brought down;
and there shall be a voice of howling of the shepherds, for their glory is spoiled.`"

And Christ saith in Mark, "`Pride is one of those evils that cometh out of the heart,
and defiles the man;`" so take heed of that which defiles.

And as John saith, "`The lust of the flesh, the lust of the eye, and the pride of life;
this is not of the Father, but of the world;`" all this must be kept down in christians.

And David saith, "`The wicked in his pride doth persecute the poor;
but are they not taken in their devices that they have imagined.`" Ps. 10:2.

And David saith, "`the Lord hid them that feared him, in the secret of his presence,
from the pride of man, and kept them secretly in a pavilion,
from the strife of tongues.`" Ps. 31:20.

And also David saith, "`that pride compasseth the wicked as a chain,
etc. and they speak loftily; and they set their mouths against heaven;
but the Lord casts down such to destruction, and saves the righteous that fear him.`"

And so you may see how pride was testified against by Christ and his prophets,
and the holy men of God, both in the Old and New Testament,
since man and woman fell from the image of God; and therefore all are to fear the Lord,
and learn of Christ Jesus, who is meek and low in heart.

For it is said, that "`Josiah`'s heart was tender,
and he humbled himself before the Lord.`" 2 Chron. 34:33.

"`And if my people, which are called by my name, shall humble themselves, and pray,
and seek my face, and turn from their wicked ways; then will I hear from heaven,
and forgive them their sins, and heal the land; and mine eyes shall be open,
and mine ear attentive to their prayer;`" this is the comfort of the humble. 2 Chron. 7:12.

And David saith, "`The Lord forgets not the cry of the humble.`" Ps. 9:12.
Again David saith, "`Arise, O Lord, lift up thy hand, forget not the humble.
Lord, thou hast heard the desire of the humble, thou wilt prepare their hearts,
and wilt cause thine ear to hear.`" Ps. 10:12,17.

And the Lord, who inhabits eternity, whose name is holy, saith,
"`I dwell in the high and holy place.
And also with him that is of a contrite and humble spirit;
to revive the spirit of the humble, and to revive the hearts of the contrite ones.`"
Isaiah 57: 15. Here are joy and comfort to the humble.
And James saith, "`God gives grace to the humble, but he resisteth the proud.`" James 4:6.
"`Humble yourselves therefore under the mighty hand of God,
that he may exalt you in due time; and be clothed with humility.`" 1 Pet. 5:6.

So you may see how God resisteth the proud, and dwells with the humble, as is testified,
both in the Old Testament and the New.
And Christ saith, "`Whosoever shall humble himself as this little child,
the same shall be greatest in the kingdom of heaven.`"

So here you may see Christ, and the prophets, and the apostles taught humility,
and judged pride.
And again Christ saith, "`He that humbleth himself shall be exalted,
and he that exalteth himself shall be abased.`" Luke 14:11.
and 18:14.

And therefore learn of Christ, who is meek and low in heart:
for he rules in the hearts of the humble, who is king, priest, and prophet,
and a shepherd to feed them, and a bishop to oversee them, and an everlasting Father,
who begets man and woman up into the image of God, and an everlasting Prince of peace.

And so all that are in true humility, are the true subjects of Christ;
and all the children of pride are subject to the prince of the air, the god of the world,
who is the king of pride, in whom there is no truth.

=== Now concerning vain fashions, deckings, and customs, etc.

The Lord forbids his people, by Jeremiah, to follow them,
or to learn the way of the heathen, for the customs of the people were vain,
and they did not only deck themselves, but they also decked their images and idols.
And God`'s people were not to be dismayed at the signs of heaven, in the old covenant;
for the heathen were dismayed at them;
much less in the new covenant should the true christians not be dismayed at them.
Jer. 10:2, etc.

And again, doth not Jeremiah cry against the paintings and deckings of Judah?
And though "`Judah rent her face with painting, yet her lovers would despise her.`"
And this was when they forsook God, and followed other lovers;
and therefore God`'s anger was against them in the old covenant; much more in the new. Jer. 4:30.

And it is true, God did deck the Jews in the old covenant with outward things;
but when they played the harlot with them, and decked their images with them,
the Lord`'s anger was against them, as in Ezek. 16:15-16.

And Hosea cries out against the Jews`' "`decking of themselves with ear-rings and jewels,
and going after other lovers, and forgetting the Lord.`" Hosea 2:13.
And you may see the attire of the harlot, and the subtlety of her heart,
how she decks herself, and decks her bed,
and "`deceives a young man among the youth,`" Prov.
7+++.+++ And therefore let all that profess themselves christians take heed of such deckers.

And you may see how the Lord sent Isaiah to cry against their haughtiness,
and stretched out necks, and wanton eyes, and tinklings, and mincings,
and their round tires like the moon, and their chains, and bracelets, and their rings,
and nose jewels, and other vain ornaments; and told them, "`they should be desolate,
for the spoil of the poor was in their houses.`" Isa. 3:16.

Now if such things were testified against in the old covenant,
then surely much more in the new.

And in Revelation 17. and 18. chapters, you may see how the whore decked herself,
who drank the blood of the martyrs; but at her fall God`'s people sung hallelujah.

And in Lev. 18. the Lord commanded the Jews in the old covenant,
"`not to defile themselves with the customs of the heathen;`" so
much more they should not do it in the new covenant.

And the apostle Paul exhorts the Corinthians, to "`use this world, and not abuse it;
for the fashion of this world passeth away.`"

And Peter exhorts the saints,
"`not to fashion themselves according to their former lusts, in their ignorance;
but as Christ, who had called them, was holy,
so be ye holy in all manner of conversation.`" 1 Pet. 1:14.

So see what a care the apostle had,
lest that they should go into their former lusts of ignorance.

And the apostle Paul tells the Philippians, "`their conversations were in heaven,
from whence we look for a saviour, the Lord Jesus Christ,
who shall change our vile bodies,
that they may be fashioned like unto his glorious body.`" Phil. 3:21.

This is the fashion that all true christians are to look at.

=== Now concerning wearing and putting on of apparel.

Isaiah testifieth against vanity in apparel, and the changeable suits among the Jews.
Isa. 3.

And what became of Tyrus, with all his broidered works, and chests of rich apparel,
did not the Lord bring them down in their pride? Ezek. 27:24.

And did not Zephaniah say,
the Lord would punish all such as were clothed with strange apparel? Zeph. 1:8.

But first they were clothed inwardly in transgression,
before they clothed outwardly with the strange apparel.

And what became of Dives, with all his sumptuousness and bravery,
who despised poor Lazarus?
And also Herod:
and are not people`'s eyes gazing more after fine apparel than after the image of God? Luke 16:19.
and Acts 12:21.

And you may see that the first apparel that Adam
made after transgression was of fig leaves,
and then God made them coats of skins: but now people are so far degenerated from that,
and have gotten so far into the lusts of the flesh, the lusts of the eye,
and the pride of life, that they know not what to put on.

And their life is below the lilies, and the fowls of the air, as Christ saith,
"`The fowls of the air do not sow, nor reap, nor gather into barns:
and the lilies they toil not, neither do they spin;
but the heavenly Father feeds and clothes them.`"

And Christ also saith,
(speaking to people,) "`that ye are much better than the fowls of the air, or the lilies:
and therefore take ye no thought what ye shall eat, or what ye shall drink,
or wherewith ye shall be clothed; for after these things the Gentiles do seek;
for your heavenly Father knoweth that you have need of all these things;
but first seek ye the kingdom of heaven, and the righteousness thereof,
and all these things shall be added unto you, as in Matt.
6.

Here you may see how Christ is restoring people up into the image of God,
out of the thoughts and cares of the heathen;
for God took care for man and woman before he made them.

And the apostle exhorted Timothy,
how the women should adorn themselves with modest apparel,
and with shamefacedness and sobriety, and not with broidered or plaiting the hair,
or gold, pearls, or costly array, but with that which becomes women professing godliness,
with good works.
1 Tim.
2+++.+++ Mark this every one.

And James reproves and exhorts such, whose eye and esteem was to the "`gold ring,
and goodly apparel, more than the poor in vile raiment,`" and tells them,
they were not "`to hold the faith of our Lord Jesus Christ,
with respect to persons;`" much more not with gay clothing or apparel. James 2:1.

And Peter, in 1 Pet. 3. exhorts the saints how to adorn themselves:
"`Whose adorning,
let it not be the outward adorning, of plaiting the hair, or wearing of gold,
and putting on of apparel.
But let it be the hidden man of the heart, in that which is not corruptible;
even the ornament of a meek and quiet spirit;
which is in the sight of God of great price.`"

"`For after this manner, in old times, the holy women also, who trusted in God,
adorned themselves.`"
And this ought to be the adorning now in the new covenant.
And though you may say, the Jews and Hebrews adorned themselves with jewels,
and they did adorn the temple, etc.

But in the new covenant these things were forbidden.
And they were to adorn the temple of the heart, and not to defile that,
and to know the hidden man of the heart, which is not corruptible.
And therefore look into all your hearts, and see if you can find any thing there,
which is not corruptible, and to put off the old man with his deeds;
with "`the lust of the flesh, the lust of the eye, and the pride of life;
which are not of the Father, but of the world.`"

And this old man delights in the glory of the world, which must be put off.
And all Christians in the new covenant must put on the new man,
that is renewed in knowledge, after the image of God that created him,
which walks and serves God in the new and living way; who is born again,
not of corruptible seed, but of incorruptible seed, by the word of God;
and feeds upon the incorruptible milk, and wine, and water, and bread,
and the incorruptible flesh and blood of Christ, and wears the fine linen,
the righteousness of Christ, the incorruptible clothing.
And this is the birth born of the spirit,
that enters into the incorruptible kingdom of God,
as in John 3:5. and in 1 Pet. 1:23.

And the apostle Paul exhorts the Ephesians,
in chapter 4:22. to put off their former conversation, "`the old man,
which is corruptible, according to the deceitful lusts;
and be renewed in the spirit of your minds;`" that is out of the fall of Adam.
And that ye put on the new man,
which after God is created in righteousness and true holiness.
So here man comes to know his first creation, and his degeneration;
so always to see the new man put on, which is in righteousness, and holiness;
and the old man put off, with all his vain deckings, trimmings, and clothings,
which is not acceptable both in the sight of God and his people.

And so all in the new covenant are to be conformable to the image of God.
Rom. 8;2. For all have been conformed long enough to the image of Satan.

And the apostle saith, "`We all behold with open face, as in a glass,
the glory of the Lord; and are changed into the same image from glory to glory;
even as by the same spirit of the Lord.`" 2 Cor. 3:10.
So every one are to mind this happy and blessed change.

And the apostle saith, "`Put on the Lord Jesus, and make no provision for the flesh,
to fulfill the lust thereof.`" Rom. 13:14.
And as every one hath received the Lord Jesus, so walk in him,
and then you will put off the old Adam, and his deeds in transgression;
and not walk in him, but walk in Christ that never sinned,
nor was guilt found in his mouth.

"`And if any man be in Christ, he is a new creature.
Old things passeth away, and all things become new.`" 2 Cor. 5:17.

Therefore the apostle exhorts the Colossians,
chapter 2:8. that they were not to follow the rudiments of the world,
for they were not after Christ.
And so people are not to follow the world`'s rudiments, but Christ.

And you may see how the children of Israel, that came out of Egypt,
and the mixed multitude, lusted after the flesh pots of Egypt.
And the Lord smote them with a grievous plague. Numb. 11.
And David saith, "`They tempted God in their hearts, by asking meat for their lust.`"
Ps. 78:18.

And again David saith, "`They lusted exceedingly in the wilderness,
and tempted God in the desert.
And he gave them their request, but sent leanness into their souls.`"
Ps. 106:14-15.

And therefore in the new covenant the apostle saith, these things were for our examples,
to the intent we should not lust after evil things; as they also lusted. 1 Cor. 10:11.
And Solomon exhorts to "`keep from the evil woman,
from the flattery of the tongue of a strange woman.
Lust not after her beauty in thy heart, neither let her take thee with her eyelids.
For by means of a whorish woman, a man is brought to a piece of bread.
And the adulterous will hunt for thy precious life.`" Prov. 6:26.

And Christ not only forbids adultery, but lust also.
Matt.
5+++.+++ And again Christ saith, "`The cares of the world,
and the love of other things choke the word, and it becomes unfruitful to them.`" Mark 4:19.

And you may see what became of such, as the apostle speaks of in Rom. 1:21. who,
when "`they knew God, glorified him not, as God; neither were thankful.`"
How at last "`God gave them up,`" when they forsook him, through the lust of their hearts.
And there you may see what evils they run into.
And also you may see in Jude 16, 18. how he declares against murderers, and complainers,
and mockers, who walked after their ungodly lusts.

And in 1 Pet. 2:11. the apostle Peter saith, "`Dearly beloved,
I beseech you as strangers and pilgrims, abstain from fleshly lusts,
which war against the soul.`"

And James saith, war and fightings came from the lusts, that warred in their members.
And such asked, but received not, because they asked amiss,
that they might consume it upon their lusts.
Therefore, saith he, "`Know ye not that the friendship of this world is enmity to God?
Whosoever therefore will be a friend to the world, is an enemy to God.`" James 4:1.

And Paul saith, "`that the grace of God, which brings salvation,
hath appeared unto all men.
Teaching us to deny ungodliness and worldly lusts.
That we should live soberly, righteously, and godly in this present world.`"
Which is the duty of every true christian, that to deny, and so to live. Tit. 2:11.

And therefore the apostle exhorts Timothy, to fly youthful lusts,
and to follow righteousness, faith, and charity,
and peace with all them that call on the name of the Lord out of a pure heart.
And such teachers who had the form of godliness, but deny the power,
which the saints were to turn away from; those were they that led silly people captive,
laden with sin and divers lusts. 2 Tim. 2:22.
and 3:5. And such as could not abide sound doctrine,
but after their own lusts, shall heap to themselves teachers, having itching ears;
they turn away their ears from the truth and grace that comes by Jesus Christ,
(which should teach them and bring their salvation,) and from the spirit of God,
which they should walk in, as the apostle saith, "`If ye walk in the spirit, (mark,
in the spirit,) ye shall not fulfill the lusts of the flesh.`" Gal. 5:16.
And the apostle further saith,
"`That every one of you should know how to possess
his vessel in sanctification and honour,
and not in the lusts of concupiscence, even as the Gentiles which know not God.`" 1 Thess. 4:4.

"`If a man purge himself from these things, he shall be a vessel unto honour,
and sanctified, and meet for his master`'s use, and prepared for every good work.`" 2 Tim. 2:21.
But they that will be rich, fall into temptations and snares,
and into many foolish hurtful lusts, which drown men in destruction and perdition.
"`But the man of God is to fly these things, and follow after righteousness, godliness,
faith, love, patience, and meekness.`" 1 Tim. 6:11.
"`And they that are Christ`'s, have crucified the flesh,
with the afflictions and lusts.`" Gal. 5:24.

And haughtiness and high mindedness were forbidden both by God and his people.
And David saith, "`The afflicted people the Lord will save.
And his eyes are upon the haughty, to bring them down.`" 2 Sam. 22:28.

And David said, "`Lord, my heart is not haughty, nor mine eyes lofty;
and my soul is like a weaned child.`"
Ps. 131:2. Then he was fit for the kingdom of God.
And again David saith, "`God will save his afflicted people,
but will bring down high looks.`" Ps. 18:27.

And Solomon saith, "`Before destruction, the heart of man is haughty, and before honour,
is humility.`" Prov. 18:21.

And Isaiah declared against the haughtiness of the daughters of Zion.
Isaiah 3. And how the haughty people of the earth do languish,
because they had transgressed God`'s laws, and changed his ordinances.

And doth not the Lord say by Isaiah, chap.
16:6. "`that Moab should howl for his pride and haughtiness?
And I will punish the world for their evil, and the wicked for their iniquity.
And I will cause the arrogancy of the proud to cease.
And I will lay low the haughtiness of the terrible.
The lofty looks of man shall be brought low,
and the haughtiness of men shall be bowed down;
and the Lord alone shall be exalted in that day.`"
And this is a good day; for "`the day of the Lord of hosts,
shall be upon every one that is proud and lofty, and upon every one that is lifted up,
and he shall be brought low.`" Isaiah 2:3.
and 10:24.

And Ezekiel saith, "`that the children of Israel were haughty, and like Sodom,
and committed abominations before the Lord, and he took them away.`" Ezek. 16:46.
And Zephaniah saith, "`Thou shalt be no more haughty.`" Zeph. 3:11.
"`Neither shall ye go haughtily.`" Mic. 23:1.
And therefore all are to learn humility,
that they may exalt the Lord their maker.

And the apostle exhorted the Romans, "`not to be high-minded, but fear;
for they stood by faith.`" Rom. 11:20.
And the apostle exhorted Timothy,
to "`charge those that were rich in this world, that they be not high-minded,
nor trust in uncertain riches, but in the living God,
who gives us richly all things to enjoy.`" 1 Tim. 6:17.
And the apostle again tells Timothy,
"`that the heady high-minded are lovers of pleasure more than lovers of God.`"
And daily experience shows; as you may see at large the fruits of such. 2 Tim. 3:4.
And therefore all those things the faithful are to shun,
and to be "`kindly affectioned one to another, with brotherly love,
and in honour preferring one another.`" Rom. 12:10.
And the apostle exhorts the Corinthians, to be perfectly joined together,
in the same mind, and in the same judgment; that they might all speak the same thing.
So that there may be no division among them.
1 Cor.
1.

And again, in 2 Cor. 13:11. the apostle saith, "`Be perfect, be of good comfort,
be of one mind, live in peace.
And the God of love and peace shall be with you.
For by one spirit we are all baptized into one body, whether Jews or Gentiles,
bond or free.
And have been all made to drink into one spirit,
and the spirits of the prophets are subject to the prophets.
For God is not the author of confusion, but of peace.`" 1 Cor. 12:13.
and 14:32-33. And the apostle writes to the Philippians,
that they should be of one accord, and of one mind; and said,
"`Let nothing be done in strife, or vain glory, but in lowliness of mind,`" etc.
Phil. 23.
And the apostle saith to the Romans, "`Be of one mind towards one another,
and not mind high things, nor to be wise in their own conceits,
but condescend to men of low estate.`" Rom. 12:16.
"`And the God of patience and consolation
grant you to be like-minded all towards one another,
according to Christ Jesus.
That ye may, with one mind and one mouth, glorify God,
even the Father of our Lord Jesus Christ.
Receive ye one another, as Christ also received us to the glory of God.`" Rom. 15:5-7.
"`For God hath given to his people the spirit of power, and of love,
and a sound mind.`" 2 Tim. 17.

And Peter in his first general epistle, chap. 3. ver. 8. saith,
"`Be ye all of one mind, and have compassion one of another;
love as brethren, be pitiful, be courteous.`"
And the apostle Paul saith,
in Acts 20:19. how he served the Lord in all humility of mind.

And it is a mark of Christ`'s disciples, (as he saith,) "`if they love one another,
and love enemies.`"
And so all that are believers in him, are to love one another as he hath loved us,
who hath laid down his life for us.

And therefore all are to deny themselves; yea, and to offer all up for him.

And whatsoever you do, do it in the name of Jesus, to the praise and glory of God.

G+++.+++ F.

[.postscript]
====

=== Postscript: A testimony out of the Old Testament and New, of the Lord sending his prophets to declare his judgments against the disobedience and pride of the Jews; and how his judgments were fulfilled upon them that did not repent; and how the apostle did admonish and reprove such as went into pride and the fashions of the world.

The Lord saith, "`Because the daughters of Zion are haughty,
and walk with stretched forth necks and wanton eyes, walking and mincing as they go,
and making a tinkling with their feet;
therefore the Lord will smite with a scab the crown of the head of the daughters of Zion;
and the Lord will discover their secret parts;
in that day the Lord will take away the bravery of
their tinkling ornaments about their feet,
and their cauls, and their round tyres, like the moon, the chains, (mark,
the chains,) and the bracelets, and the mufflers, the bonnets,
and the ornaments of the legs, and the head bands, and the tablets, and the earrings,
the rings, and nose jewels, the changeable suits of apparel, and the mantles,
and the wimbles, and the crisping pins, and glasses, and the fine linen, and the hoods,
and the veils.
And it shall come to pass, that instead of sweet smell, there shall be a stink;
and instead of a girdle, a rent; and instead of well set hair, baldness;
and instead of a stomacher, a girding of sackcloth; and burning instead of beauty.
Thy men shall fall by the sword, and thy mighty in the war;
and her gates shall lament and mourn, and she being desolate shall sit on the ground.`"
Isa. 3:16 to the end.
And you may read in 2 Kings 17. how that the children
of Israel were carried into captivity in Assyria;
for the king of Assyria besieged Samaria, and after three years besieging,
he took it and carried away the ten tribes of the
children of Israel into the land of Assyria.
And Isaiah, according to the word of the Lord, went to the prophetess,
and she conceived and bore a son, etc.
And the Lord said, "`Before the child should have the knowledge to cry,
my father and my mother, the riches of Damascus, and the spoil of Samaria,
shall be taken away by the king of Assyria. Isaiah 8:3-4.

Now here you may see what a destruction came upon Samaria and the Jews,
because of their rebellion and disobedience, and their haughtiness and pride,
that Isaiah cried against in chap.
3+++.+++ And then what became of all their haughtiness and pride, and their mincing,
and their tinkling with their feet, and their chains, and bracelets, and jewels,
and round attire, with their glasses, and hoods, and veils,
when they were driven away by droves, by the king of Assyria, into captivity,
into Assyria, out of their own land, houses, and cities?
Then Isaiah`'s prophecy was fulfilled upon those haughty and proud Jews:
and did not Nebuchadnezzar afterwards carry away the two tribes, and destroy Jerusalem,
because of their disobedience, rebellion, haughtiness, and pride,
who would not regard the Lord nor his prophets;
therefore the Lord suffered them to be led away prisoners, out of their own houses,
cities, and land, into Babylon, so stripped them of their pride,
and caused them to be carried away into strange countries; so,
was not the prophet`'s prophecy fulfilled upon them?

The Lord saith, "`Behold, the day cometh that shall burn as an oven, and all the proud,
yea, all that do wickedly, shall be as stubble; and the day that cometh shall,
burn them up, saith the Lord of hosts, that it shall leave them neither root nor branch:
but unto them that fear my name,
shall the son of righteousness arise with healing in his wings, and ye shall go forth,
and grow up as calves in the stall.`" Mal. 4:1-2.

Therefore it is good for all to keep out of pride and wickedness, in humility,
lest they be burnt up.

And the apostle commanded, that "`women adorn themselves in modest apparel,
with shamefacedness and sobriety, not with broidered hair, or gold, or pearls,
or costly array, but that which becometh women professing godliness, with good works.`"
1 Tim. 2:9-10.

And likewise Peter in his general epistle, saith to the women, "`whose adorning,
let it not be that outward adorning, of plaiting the hair, and of wearing of gold,
or of putting on of apparel; but let it be the hidden man of the heart,
in that which is not corruptible, even the ornament of a meek and quiet spirit,
which is in the sight of God of great price.
For after this manner in the old time, the holy women, who trusted in God,
adorned themselves, being in subjection unto their own husbands.`" 1 Pet. 3:3-5.

Here you may see both the prophets and apostles declared
against the pride and haughtiness of people,
both in the old and new testament.

And the apostle John saith in his general epistle to the church of Christ,
"`Love not the world, neither the things that are in the world;
if any one love the world, the love of the Father is not in him;
for all that is in the world, the lust of the flesh, the lust of the eye,
and the pride of life, is not of the Father, but is of the world;
and the world passeth away, and the lust thereof; but he that doth the will of God,
abideth forever.`" 1 John 2:15-17.

Now here you may see an express command to the true christians,
(the church of Christ,) against the love of the world, and the things of the world,
and the lust of the eye, and the lust of the flesh, and the pride of life;
and they that love the world, the love of the Father is not in them:
and how that the world passeth away, and the lust thereof;
and therefore love not the lust of the eye, the lust of the flesh, and the pride of life,
which is not of the Father.

And do not most of christendom say the Lord`'s prayer, "`Our Father which art in heaven,
hallowed be thy name,`" etc. and you that live in the lust of the flesh,
and the lust of the eyes, and the pride of your life,
which is not of the Father which is in heaven, but of the world that passeth away,
and the lust thereof.
And is it not said, "`The devil is the king of pride?`"
And therefore do not do his lusts; but "`he that doth the will of God abideth forever.`"
And therefore consider when you say, "`Our Father which art in heaven,
hallowed be thy name,`" etc. when you live in those
things which are not of the Father which is in heaven,
and daily obey and love the lust of your eye, the lust of your flesh,
and the pride of your life, "`which is not of the Father, but of the world.`"
And the apostle John tells you, "`He that loves the world,
the love of the Father is not in him.`"

====

G+++.+++ F.
