== Epistles 280 &#8212; 301

[.centered]
=== Epistle 279.

All dear Friends everywhere, who have no helper but the Lord,
who is your strength and your life, let your cries and prayers be to him,
from whom all your help and strength comes; who with his eternal power,
hath kept up your heads above all waves and storms.
Let none go out of their habitations in the stormy time of the night,
whose habitation is in the Lord; let every one keep his habitation, and stand in his lot,
the seed, Christ Jesus, to the end of the day.
There is the lot of your inheritance,
and in this seed you will see the bright and morning star appear,
which will expel the night of darkness that hath been in your hearts;
by which morning star you will come to the everlasting day, which was before night was.
So every one feel this bright morning star in your hearts, there to expel the darkness.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 280.

Dear friends, the truth of God mind, and his pure holy power,
which the Lord hath made you partakers of, by his good spirit.
Oh! let not his spirit be grieved by you.
Let that be mortified that would get up to grieve or quench the spirit,
for that will corrupt your reason, understanding, and knowledge;
and that which gives you to know God and Christ, that is life eternal.
And all have a care that you do not abuse the power,
nor crucify to yourselves the seed afresh, but let that be crucified by the seed;
in which seed you have life eternal.
And therefore prize the truth above all things.
Now you have liberty to spread it abroad;
for you are called to righteousness and holiness, without which none shall see God.
Therefore mind your high calling in God, out of old Adam, into Christ Jesus,
the second Adam; and keep your meetings in the name of Jesus,
and feel him in the midst of you, who is your life and salvation;
and that all occasions and stumbling blocks may be taken away,
so that the precious truth may be minded by you all, wherein all are to live in unity,
and walk in peace, with the God of peace, and one with another;
that all your springs may be kept open, and all your fountains may run with living water;
and all your candles may burn,
and every one may have bread on his own table in his temple, and his rod budding there,
that he may be known to be a priest of the royal priesthood.
So that all may have salt in yourselves, that you may be good for something;
for if you be not the good salt, you cannot make the earth savoury.
Therefore all keep in the sense of truth, and be digging for the pearl in your own field,
and to find the silver in your own house, that was lost,
and the leaven in your own hearts; that were it works, and is joined to,
will leaven into its own nature.
So in all your meetings, be faithful in the power and life,
that you may be watered by the spring of life, that you may grow.
And so whatever strife, or whatever runs out, or whatever occasion of offence has been,
let the seed of God rise, and put all that down in all; that all you,
in the everlasting seed, the second Adam, may have your peace, familiarness,
and kindness, and affableness, and courteousness, and gentleness, and love,
one with and towards another; for the power of the Lord God is over all,
and his everlasting seed, Christ Jesus, reigns over all, in whom is eternal fellowship,
peace, and unity, and not in old Adam;
for old Adam`'s sons and daughters may get the words of Christ, and of the prophets,
and apostles, but are out of their life, as their practice speaks.
And therefore it is the life that differs, and the new way differs from the old,
and the religion that is above, from that which is below;
and the worship Christ set up above sixteen hundred years ago,
from all them that are made since, amongst the nominal christians;
and the fellowship of God in the spirit and gospel,
differs from all the fellowships that have been made since the apostles`' days;
and the liberty in Christ, in the gospel, in the spirit,
is far above the liberty of old Adam in the flesh, in the sin,
the wages of which is death; here no false liberty can be in the spirit,
and in the power of the gospel, and in Christ Jesus; nor any false freedom in the truth,
for all false freedom is out of the truth;
and therefore keep over all those false liberties and false freedoms,
(in old Adam and his spirit, and dark power, and corrupt seed,) in the seed of life,
and spirit and power of God, that is holy and pure, without spot.
So no more, but my love in the holy seed, that is over all.

[.signed-section-signature]
G+++.+++ F.

To be read in all Friends`' Meetings.
And send copies of this to Maryland, Virginia, Barbados, New England, etc.

[.centered]
=== Epistle 281.

Friends, in the seed that bruiseth the serpent`'s head,
and destroyeth the devil and his works, live; and in the light, which is the life,
in the word, by which all things were made; which light, and life, and word, doth hammer,
and cut down, and condemn, and judge, all evil words and works, and the spirit of them,
that is out of the light, life, seed, and word of reconciliation.
In this, I have unity with you, and in this all true believers are reconciled to God,
and one to another, and in it is the heavenly wisdom,
in which is the holy and spiritual fellowship preserved, over that short, brittle,
defaming, and inconstant spirit,
which must be kept down with the spirit of God that doth not change,
which hath been crucified by the wicked; but the seed of life doth slay the enmity,
and in life and power reigns over it.
Glory to the Lord God forever.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 282.

[.blurb]
==== To Friends at Bristol in time of suffering.

Dear friends, now is the time for you to stand; therefore put on the whole armour of God,
from the crown of the head unto the soles of your feet,
that you may stand in the possession of life: and you that have been public men,
and formerly did travel abroad, mind to keep up your testimony,
both in the city and in the countries,
that you may encourage Friends to keep up their meetings as usual thereaway;
so that none faint in the time of trial; but that all may be encouraged,
both small and great, to stand faithful to the Lord God, and his power, and truth;
that their heads may not sink in the storms, but may be kept up above the waves.
So, go into your meeting places, as at other times: and keep up your public testimony,
and visit Friends thereabouts, now in this time of storm; for there is your crown,
in the universal power and spirit of God.
So let your minds, and souls, and hearts, be kept above all outward and visible things.
Few travel now the countries: it may be well to visit them, lest any should faint.
Stir up one another in that which is good, and to faithfulness in the truth, this day.
And let your minds be kept above all visible things;
for God took care for man in the beginning, and set him above the works of his hands:
and therefore mind the heavenly treasure, that will never fade away;
and dwell in the seed, in which you may know your election.
It is hard for me to give forth in writing what is before me,
because of my bodily weakness; but I was desirous in some measure to ease my mind,
desiring that you may stand fast, and faithful to truth.
Of my travels and weakness it is like you have heard, and of my affliction,
both by them that are without, and also by them that are within,
which are hard to be uttered and spoken.
My love is to all faithful Friends.

[.signed-section-signature]
G+++.+++ F.

The 2d of the 11th month, 1670.

[.centered]
=== Epistle 283.

Dear friends and brethren, see that all live in the peaceable and blessed truth,
into which no enmity can come; for the blessed seed, Christ Jesus, takes away the curse;
of the increase of whose government there is no end;
who rules in righteousness among the righteous forever.
And see that this righteousness,
(in which you all have peace,) run down and flow as a stream among you,
who are begotten again into a lively hope,
and born again by the immortal seed of the word of God, which lives and abides forever.
And you who have received Christ, have received power to become the sons of God,
and to believe in the light, in obedience to Christ`'s command;
by which you become children of the light, and children of the day.
Therefore this I say unto you, let no man abuse this power, that is everlasting;
and keep the gospel order, which was before any impurity was,
and will be when it is gone.
So that in all your men and women`'s meetings, see that virtue flow,
and see that all your words be gracious, and see that love flows, which bears all things,
that kindness, tenderness, and gentleness may be among you,
and that the fruits of the good spirit may abound;
for nothing that is unclean must enter into God`'s kingdom,
which stands in righteousness, and in holiness, and in the power of God,
and in the joy of the holy ghost: for all joy that is out of the holy ghost,
will have an end.
And see in all your men and women`'s meetings, that God be no ways dishonoured,
nor the pure and blessed name of Christ (in which you are gathered) be blasphemed;
but in all things that God may be glorified, exalted, and honoured;
for you have the light, to see all evil, and the power to withstand it,
and to see that nothing be lacking, then all will be well among you,
in all your men and women`'s meetings.
And see that nothing be lacking, neither within nor without, for God is rich in both,
and abundance of his riches you have received.
And so this is a warning and a charge to you all, in the presence of the living God,
that you keep up the testimony of Jesus,
against all that which is contrary to Jesus the heavenly man,
that your fruits may appear to his glory, and your works to his praise;
and that you may have water in your own cisterns,
and know those clouds through which Christ gives you rain,
having purchased the field wherein the pearl lies.
And now is the spring time that the lily and the rose begin to flourish,
and the vine is putting forth, and the apple tree to bring forth her fruit,
by the power of the Lord God, who is over all.
And keep your testimony for your religion, that you have received from God,
and for your worship in the spirit and in the truth, that Christ Jesus hath set up;
and for your gospel fellowship, which is in the power of God before the devil was:
and see that all live in peace and in the love of God, for love edifieth the body;
for he who is the head of it, is the beloved of God,
who is from everlasting to everlasting.
And see that every one`'s affections be set on things above, and not upon things below,
that be earthly; for now is the time to contend for the faith, that gives victory,
which was once delivered to the saints, in which you have unity.
And so the God of power preserve you all, and keep you in his blessed seed, to wit,
Christ Jesus, that none of you may be without a minister, without a priest,
or without a prophet, or without a shepherd, or without a bishop,
but let every one receive him in his offices:
then you all have one who will exercise his offices in you all,
whom God hath given for a leader and a covenant; yea, an everlasting leader,
who was the foundation of the prophets and apostles, and is to us this day.
And so be valiant for the truth upon the earth, in the seed Christ Jesus,
that through him who destroys death, you may have a crown of life;
and through him you may be one another`'s crown and joy in the Lord; yea, I say,
through Christ, who was glorified with the Father before the world began.

I am just now upon leaving this island, where I have had very great and blessed service;
though I underwent very great weights, and burdens, and sufferings, and travels:
but all is well, and the blessed seed and power is over all;
to whom be glory forevermore.
Amen, amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 284.

[.salutation]
Dear friends,

This is the counsel of the Lord to you all,
who are brought into the eternal truth of God,
whose minds are guided out of the earth up to God,
and have received their wisdom from God; which wisdom orders all the creatures;
that with it you may come to know how to order in the creation,
with the wisdom by which all was made.
This I charge you, and warn you all, in the presence of the living God,
that you suffer no creature to perish for want of the creatures,
and that none be lost through slothfulness, laziness, and filthiness;
and let not these things be,
which are for condemnation with the light that leads to the wisdom,
with which the creation must be ordered.
And, friends, let there be no slothfulness among you;
but all keep in diligence and liveliness.
For he that is slothful, is an evil example; and such must be judged with the light,
that they may come to know the servant`'s place, and be diligent.
And such as have gone up and down begging, whom you have received in amongst you,
with the light which hath convinced them, see that they be kept in diligence,
and not wander, but be kept in obedience to the light, to receive their wisdom from God,
how to labour in the creation; and see that they have things decent and necessary,
and that their nakedness may be covered,
that no reproach nor shame may come upon the truth from such as are without;
but that with the light all such may be denied who act contrary to it;
and in the light which condemns the evil world ye may walk,
and receive the light of the son of God, (which the world stumbles at,
which is their condemnation,) and in which the saints have unity.
And all being kept diligent, walking in the light, there will be no slothfulness.
For that is judged with the light, which is one with that in his conscience,
which condemns him for evil.

[.signed-section-signature]
G+++.+++ F.

This to go among Friends everywhere.

[.centered]
=== Epistle 285.

[.salutation]
Friends,

When you are met together in the name of Jesus your saviour,
let your minds be over all to him, and out of all things that change, and perish,
and die of itself, and will corrupt, and are visible, up to him that is invisible,
the Lord God, and his son Jesus Christ, that you may see him and feel him among you,
and in your meetings, in his life, and light, and power, and spirit;
and that you may know that God is,
and that he is the rewarder of all them that diligently seek him;
and to know that God is present.
And that which giveth the knowledge of him, is the light that shineth in the heart,
in the face of Jesus Christ, and so see him in all your troubles and afflictions;
and that God is present, beholding all your actions done in your bodies,
and your consenting to your evil thoughts, lusts, or motions; the thoughts,
what you will speak or act; or motions which you have not acted outwardly;
but if you do consent to do them in your mind or heart,
the Lord seeth them there to be done,
though they be not done outwardly to the sight of men;
and so to God you must give an account of things done in your bodies,
and of things done out of the body; for God both heareth,
and seeth what is done in the body, and what is said and done without the body;
and therefore turn from the evil that leadeth to destruction, and judge it,
and yourselves for cleaving to it; and turn to the Lord,
and know him who is mighty to save, and to reward all them that diligently seek him,
who is Almighty in his power to save and deliver, and to help in time of need.
So know him that was from everlasting to everlasting.
And here thou knowest God in his power, light, and life, and righteousness,
which his kingdom stands in, in that righteousness, and power, and holy ghost, and peace,
that never will have an end; and is over all kingdoms that will have an end,
and are unclean; and any unclean and imperfect thing may enter into them;
and in them are troubles, tumults, and sin, and not peace, but sorrow.
But into the kingdom of God no imperfect thing entereth, nor sin, nor any unclean thing.
For the kingdom of God standeth in righteousness, and everlasting peace,
and in joy in the holy ghost.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 286.

[.salutation]
Friends,

Consider, you that have known the mercies of the Lord God, and of Jesus Christ.
Look back, and see how they that had known much of God, how soon they forgot him,
as in the days of the old world, and in the days of Moses, and in the days of the Judges,
how they soon forgot God, that had done great things for them, and forsook God,
and his way, and religion, and worship, and followed such gods as men had made.
And in the days of the prophets, how the people forsook the Lord God;
and in the days of Christ and his apostles, how they were mostly gone astray from God;
though they kept an outward profession of their words, yet denied Christ in his light,
and life, and power; who was the end of the law and the prophets.
And they that did receive Christ Jesus, and believed in him,
in a few ages after the apostles, how most of Christendom ran from the life into death,
and ran from the light into darkness; and into error, from the holy spirit,
and into Babylon, which is confusion; and from the worship in the spirit,
and in the truth, that Christ set up,
and followed after the worship of the beast and the dragon;
and went from the true church after the whore; and from Christ, the way to God,
after the ways that men had made; and from the religion that is pure from above,
after the religions that men have made.
And so, now the gospel is preached again, and the living way (Christ) to the living God,
and his religion and his worship are set up and received of many,
and they come to the true worship, which is in God.
And all be faithful, and take heed of running back again, where you were before,
lest you and your children perish, as others have done,
that forsook the Lord God of mercies.
And therefore train up your children in the fear of God, and in the way of Christ,
and in his worship and religion, that they may observe and keep in it,
when you are gone.

And walk in the spirit and truth, in which God is worshipped,
and keep in the order of the gospel, in the power of God, which was before the devil was;
which power of God will keep you pure to God,
that nothing may get betwixt you and the Lord God.
And be obedient to the law, that God hath written in your hearts, and put in your minds,
that you may be the children of the new covenant;
and that you may be the royal priesthood, offering up to God the spiritual sacrifices.
And sitting under your teacher, the grace of God, which bringeth salvation,
and seasoneth your words, and establisheth your hearts.
And this grace saveth, and is sufficient, saith God Almighty.
And you need no man to teach you,
but as the same anointing doth teach you to know all things:
which anointing abideth in you.
And hearken all what the righteousness of faith saith, speaking on this wise,
The word is nigh thee, even in thy heart and in thy mouth, to obey it and do it.
That thou need not say, who shall ascend to bring Christ from above,
or descend to bring Christ from the grave,
etc. for that is the word of faith which we do preach.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 287.

[.blurb]
==== To Friends in Carolina.

Dear friends, to whom is my love in the blessed seed,
which bruiseth the head of the serpent, and is over all, and changeth not,
which is the first and last, in whom you have life and peace with the God of peace.
So you few that are that ways, keep your meetings and meet together in the name of Jesus,
whose name is above every name, and gathering is above every gathering;
and there is no salvation in any other name, but by the name of Jesus;
and you gathering in his name, where salvation is, he is your prophet, your shepherd,
your bishop, your priest, in the midst of you, to open to you, and to sanctify you,
and to feed you with life, and to quicken you with life; wait in his power and light,
that ye may be children of the light, by believing in the light,
which is the life in Christ; that you may be grafted into him, the true root,
and built upon him, the true foundation,
who was the foundation of the holy prophets and apostles, and of all the holy martyrs,
and is the foundation of all his holy people now; and is the rock of ages, yea,
of the ages of the prophets, and of the ages of his apostles,
and of the ages of his people now, and martyrs,
who kept them above the raging of the seas, and doth now;
which rock the wise men build upon,
the rock that stands against all the storms and tempestuous weather.
And therefore be valiant for God`'s truth upon the earth, and his good spirit;
and live in it, by which you may profit in the things of God,
through which ye may answer the witness of God in all,
and the spirit which they grieve and quench, which they are erred from,
through which he may be served, and his truth spread abroad.
So every one in your measures of the spirit of God and Christ, be faithful,
that in it you may increase, and answer the Lord in a good life and conversation,
for all his mercies.
And as every one hath received the Lord Jesus Christ, so walk in him,
that you may serve the Lord in a new life, and worship him in the spirit and truth,
which the devil is out of; and by this truth you may be made free,
by which ye may be espoused and married to Christ Jesus,
for the marriage of the Lamb is come and coming.
And therefore, if you want wisdom, keep in the truth,
that you may go to the treasure of life and of salvation,
that you may be heirs of the same, and of life, and possessors of it.
Yea, I say, heirs of life, and inherit that, and that will be more to you,
than if all the world was your portion; and the riches you lay up there, will stand by,
and be with you when time is gone, and shall be no more.
For the truth is the truth, and changeth not, in which live,
and it will be your peace and joy everlasting.
And in the seed, Christ Jesus, (who bruises the serpent`'s head,
who was before the devil was, glorified with the Father before the world began;
and was from everlasting to everlasting, the first and last,
the top and corner-stone,) in him live, that you may inherit life everlasting;
and dwell in the love of God in Christ Jesus, that will edify and build one another up;
and therein walk in all holiness of life and conversation, for that becomes God`'s house;
and dwell, and live, and walk in the peaceable truth, that keeps you in peace,
and in the holy fellowship of the spirit, the bond of peace;
by which spirit you may be led into all truth, up to God and Christ,
from him who is out of the truth.
Amen saith my soul.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 288.

Dear friends everywhere, be faithful to God, who hath been faithful and true to you;
therefore be you true to God, and faithful witnesses to him, and to Christ Jesus;
that now ye may all have riches and treasure laid up in store, against a time of want,
storms and tempests, that you may stand; for if you do not stand now,
you are as bad as such professors, who stood only when the sun shined,
and crept out when it was fine and fair weather, but when a storm or tempest came,
then they ran creeping into their holes and corners,
and skulking into by corners and fled by back doors, who were ashamed of their religion,
and what they professed; but when the sun did shine,
then they showed their enmity to the righteous.
And therefore be you of the faith of David, and of his spirit, who said, "`I was young,
and now am old.
I never saw the righteous forsaken, nor his seed begging bread;`" and the Lord,
(to encourage his people,) saith, "`In all their afflictions he was afflicted,
and the angel of his presence saved them;`" and Christ tells you,
it is he that suffers and is persecuted, when his children are persecuted.
And so it is for the Lord`'s sake that the just suffer by the unjust;
and you read how such as suffered the spoiling of their goods, and scoffing and mocking,
yet they were not to forsake the assembling themselves together,
as the manner of some was; for they that suffer with Christ shall reign with him;
for the Lord may try you.
(who hath blessed you with outward things,) whether your minds do stand with him,
or in the outward things.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 289.

Dear friends, live in love, for that is of God, and doth edify the body of Christ;
and keep in the truth of God, which the devil is out of;
and walk in the same peaceable truth, and do righteously to all people,
and walk in righteousness: and then you will walk in peace with God,
and one with another: and walk in holiness, for that becomes the house of God,
and in holiness you will see the holy God among you.
And so that you may keep the unity in the spirit, which is the bond of peace,
and dwell in love one with another: for all eyes are upon you, and some watch for evil,
but do you answer the good in all, in your words and lives.
This is the counsel of the Lord God to you all,
and that you may be the salt of the earth, and the light of the world,
and as a city set on a hill that cannot be hid:
so that all that do profess Christ and God,
may show forth Christ and godliness in life and word.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 290.

[.blurb]
==== To all the women`'s meetings, that are believers in the truth.

[.salutation]
Friends,

Keep your women`'s meetings in the power of God, which the devil is out of;
and take your possession of that which you are heirs of, and keep the gospel order.
For man and woman were helps-meet in the image of God, and in righteousness and holiness,
in the dominion, before they fell; but after the fall in the transgression,
the man was to rule over his wife; but in the restoration by Christ,
into the image of God, and his righteousness and holiness again,
in that they are helps-meet, man and woman, as they were before the fall.
Sarah obeyed Abraham, and called him lord.
Abraham did also obey the voice of his wife Sarah,
in casting out the bond-woman and her son.
Dorcas, a woman, was a disciple.
So there was a woman disciple as well as men disciples;
and mind the women that accompanied her.
And women are to take up the cross daily, and follow Christ daily, as well as the men;
and so to be taught of him their prophet, and fed of him their shepherd,
and counselled of him their counsellor,
and sanctified by him who offered up himself once for all.
And there were elder women in the truth, as well as elder men in the truth;
and these women are to be teachers of good things;
so they have an office as well as the men, for they have a stewardship,
and must give an account of their stewardship to the Lord, as well as the men.
Deborah was a judge; Miriam and Huldah were prophetesses; old Anna was a prophetess,
and a preacher of Christ, to all them that looked for redemption in Jerusalem.
Mary Magdalene, and the other Mary,
were the first preachers of Christ`'s resurrection to the disciples,
and the disciples could not believe their message and testimony that they had from Jesus,
as some nowa-days cannot; but they received the command, and being sent preached it.
So is every woman and man to do, that sees him risen, and has the command and message;
daughters shall prophesy as well as sons.
So they are to be obedient, that have the spirit poured upon them.
Women are to prophesy; and prophecy is not to be quenched.
They that have the testimony of Jesus, are commanded to keep it, whether men or women.
Priscilla and Aquilla were both exhorters and expounders, or instructers to Apollos.
So in the church there were women instructers, and prophetesses,
and daughters prophetesses in the church; for Philip had four daughters, virgins,
that were prophetesses; and there were women disciples in the church,
and women elders in the church, as well as men.
So women are to keep in the government of Christ, and to be obeyers of Christ;
and women are to keep the comely order of the gospel, as well as men,
and to see that all that have received Christ Jesus, that they walk in Christ Jesus;
and to see that all that have received the gospel, do walk in the gospel,
the power of God, which they are heirs of;
for this is a day for all to keep their possession in the gospel order,
who are heirs with Christ, of the increase of whose government there is no end.
So the foundation of our women`'s meetings is Christ, to all them that be heirs of him,
and of his government.
And the ground of our order of the women`'s meetings is the gospel, the power of God,
which was before the devil was; and all that be heirs of the gospel,
which hath brought life and immortality to light in them,
which shines over him that hath darkened them, and was before he was: I say,
they are heirs of the comely order of the gospel; and therefore, I say,
take your possessions of it, and walk as becomes the gospel;
and keep the comely order of it, and in it keep your meetings.
And here is the ground and foundation of our women`'s meetings.
Now mothers of families, that have the ordering of children, maids, and servants,
may do a great deal of good in their families,
to the making or spoiling of their children, maids, and servants;
and many things women may do, and speak of amongst women, which are not men`'s business.
So, as I said before, that you, both men and women, be helps-meet in the image of God,
in the righteousness and holiness in the restoration,
as man and woman were in the image of God before they fell; and not only so,
but in Christ the foundation, and in his gospel that never fell, nor never will fall,
whose foundation stands sure, for all his members and heirs to build upon.
And so see that nothing be lacking amongst you, then all will be well.

[.postscript]
====

Postscript.--And the elder women in the truth were not only called elders, but mothers.
Now a mother in the church of Christ, and a mother in Israel, is one that gives suck,
and nourishes, and feeds, and washes, and rules, and is a teacher, in the church,
and in the Israel of God, and an admonisher, an instructer, an exhorter.
So all that are come to that office, growth, and stature, be diligent;
for a mother in Israel, or in the church of Christ, is beyond all the mothers in Egypt,
and in Sodom, and the mother of harlots, mystery Babylon, who had power over tongues,
nations, and people, with the cup of her fornication.
But the mothers in spiritual Israel, and church of Christ, has the cup of salvation,
and the breasts of consolation, which are full of the milk of the word,
to suckle all the young ones, and to nourish, and instruct, admonish, and exhort,
and rebuke all the contrary; and to refresh and cherish every tender one.
So the elder women and mothers are to be teachers of good things,
and to be teachers of the younger, and trainers up of them in virtue, in holiness,
and godliness, and righteousness, in wisdom, and in the fear of the Lord,
in the church of Christ.

And if the unbelieving husband is sanctified by the believing wife,
then who is the speaker, and who is the hearer?
Surely such a woman is permitted to speak, and to work the works of God,
and to make a member in the church; and then as an elder,
to oversee that they walk according to the order of the gospel.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 291.

[.blurb]
==== To Friends in New England, Virginia, and Barbados.

[.salutation]
Dear friends,

Be faithful in the power of the Lord God, in what you know,
and then the Lord will preserve you; that you may answer the witness of God in every man,
whether they are the heathen, that do not profess Christ,
or whether they are such as do profess Christ, that have the form of godliness,
and are out of the power.
And keep your meetings, you that know the power of the Lord, and feel it,
that in it you may have unity with God, and one with another.
The Lord God hath a seed in those parts,
who shall be heirs of his grace that brings salvation, which grace is it that teacheth,
in which grace they sing praises to the Lord.
So, now you who are come to the dawning of the day,
and to the ending of the night of the apostacy; happy and blessed are you,
who are come to see these things, to see the hidden mysteries of God revealed,
and his glorious riches to the Gentiles, through the power of an endless life.
And you that are and have been faithful, spread the truth abroad, ye that know it;
and feel that which makes free;
let not principalities and powers separate you from the love of God,
which you have in Christ Jesus, who hath all power in heaven and earth given unto him,
mind his reign, his teaching, his kingdom, which hath no end;
for God hath some to be brought out from amongst those heathens,
if you be faithful among them, answering the witness of God in them;
for as the Lord saith,
"`I will give him for a covenant to the Gentiles;`" and those are called heathens.
Therefore keep your meetings, and dwell in the power of truth,
and know it in one another, and be one in the light,
that you may be kept in peace and love in the power of God,
that you may know the mystery of the gospel: and all that ever you do, do in love;
do nothing in strife, but in love, that edifies the body of Christ, which is the church.
So as any are moved to go amongst the heathen, in the power and love of God,
to preach the gospel, (which is the love of God to them,) bring them to the power of God;
to that God, which is the God of the stones, which they make idols of,
and the God of the trees, earth, brass, silver, iron, and gold, which they make gods of;
and that he is the living God; for those are dead gods that are made with men`'s hands.
He is the living God that clothes the earth with grass and herbs,
and causes the trees to grow, and bring forth food for you,
and makes the fishes of the sea to breathe and live,
and makes the fowls of the air to breed, and causes the roe and the hind,
and the creatures, and all the beasts of the earth to bring forth,
whereby they may be food for you.
He is the living God, that causes the stars to arise in the night, to give you light,
and the moon to arise to be a light in the night.
He is the living God, that causes the sun to give warmth unto you,
to nourish you when you are cold.
He is the living God, that causes the snow and frost to melt,
and causes the rain to water the plants.
He is the living God, that made the heaven and the earth, and the clouds,
and causes the springs to break out of the rocks,
and divided the great sea from the earth, and divided the light from the darkness,
by which it is called day, and the darkness night,
and divided the great waters from the earth, and gathered them together:
which great waters he called sea, and the dry land earth:
he is to be worshipped that doth this.
He is the living God, that gives unto you breath, and life, and strength,
and gives unto you beasts and cattle, whereby you may be fed and clothed.
He is the living God, and he is to be worshipped.
And that which gives you to be sensible of him, and to know him,
is that which convinceth you in your hearts of sin and unrighteousness.
So all gods that are made of stone, mortar, wood, silver, brass, iron, or gold,
are not the living God, but are made of men`'s hands;
and the living God is he that gives you life, and breath, and strength,
and all things that are good, and would have you to feel after him,
with that which checks you for sin and evil; and would have you to worship him in spirit,
and serve him who is holy and righteous, and to live in peace;
who hath promised he will give Christ Jesus for a covenant of light and peace to you,
who are called Gentiles and heathens.
And now is the day approaching to you,
(this covenant of light,) by which you shall come to have peace with the Lord God,
the king of the whole earth.
This is the King of kings, and Lord of lords, in whose hand is the breath of all mankind:
this is the God of the spirits of all flesh,
who hath made all nations of mankind of one blood, to dwell upon the face of the earth.
And God having divided the sons and daughters of Adam,
and scattered them up and down the face of the earth, being in the transgression and sin,
led away with the god of the world, the wicked one, the devil,
that abode not in the truth, who causes people to destroy one another,
and murder one another about earthly things: this is the prince of darkness,
that rules in all the hearts of the children of disobedience;
disobedient to that which is righteous in them,
which discovers the unrighteous actions and words from the righteous.
And Christ, the second Adam, the Lord from heaven, saves men from sin;
who is the prince of peace, and of life, and the covenant of God,
who brings men to have peace with God, and one with another, who destroys the devil,
the author of strife: this is Christ the second Adam,
which brings the sons and daughters of Adam into reconciliation with God again,
and destroys sin, and finishes it, and makes reconciliation for sin and iniquity.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 292.

[.blurb]
==== To Friends in Barbados.

Dear friends, to whom is my love in the Lord Jesus Christ, by whom were all things made,
and by whom all things do consist, and who filleth all things,
and doth uphold all by his word and power; who is the first and last,
the holy head of his holy church, and the door into the holy way,
for his holy people to walk in,
and the setter up of a holy worship in the holy spirit and truth,
to worship the holy God in; and the setter up of a holy religion,
to keep from the spots of the world; which religion is pure in his sight.
And this never came out of the brain-beaten stuff of man, nor of his chamber of imagery;
but for his people to walk in, that they might sing forth his praises in righteousness.

And therefore, all Friends, in your men and women`'s meetings, be faithful,
and see how you do grow in the truth and power of godliness, and are circumcised;
and witness your renewings into the heavenly image of him that created you;
and that you all may be fruitful in the knowledge and grace of our Lord Jesus Christ,
who is the orderer of all things; and wear his livery and fine linen,
the righteousness of Christ; and hold forth his ensign and his standard,
and all to be filled with his grace, and love, and peaceable truth,
and be over all outward earthly things; so that none be carnally but spiritually minded;
and walk as becomes the glorious order of the gospel,
having the water of life in your cisterns, and the bread of life in your tabernacles,
and fruits on your trees, to the praise of God.
Amen.

And all your family meetings do not neglect, among your whites and negroes,
but do your diligence and duty to God and them; which you will not neglect,
if you keep in the faith of Abraham, and of the blessed seed which inheriteth the crown.
And be at peace among yourselves,
that each one show that you are in Christ the prince of peace;
and that doth show that you are the disciples of Christ,
and learners and followers of him.
So possess him who is life eternal.
Amen.

And your love and kindness towards us, the Lord redouble it of his mercy into your bosoms.
We are all pretty well.
We have had great travail by land and sea, and rivers and bays, and creeks,
in New England, Jersey, Delaware, Maryland, Virginia, Carolina,
where we have had great service among Friends, and governors, and others,
(and men and women`'s meetings,) and with the Indians, and their kings and emperor.
O blessed be the Lord God Almighty, who is over all, and over all giveth dominion.
And glory be to his great name forever.
Amen.
And his truth is of a good savour in the hearts of people, and spreads.
So no more but my love.

[.signed-section-signature]
G+++.+++ F.

Read this in your men and women`'s meeting.

Maryland, the 24th of the 12th month, 1672.

[.centered]
=== Epistle 293.

Friends, the truth is above all, and will stand over all them that hate it,
who labour in vain against it, and will bring their old house on their own heads,
to their great trouble; and in the winter, and cold weather,
when that their house is down, and their religion is frozen,
and their rivers are dried up, and their husks are gone,
and the swine begin to cry about the plantations,
and the vermin run up and down amongst their old rubbish,
and their sparks and candles are gone out,
and hail and storms lighteth upon the head of the wicked,
then woe will be to Gog and Magog, and to all the wicked, who have no covering.
In Christ you have peace, in the world you have trouble.
No peace with God can be enjoyed, but in the covenant of light; without it trouble.
Amen,

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 294.

Friends, at the first convincement there is not so much danger,
for the spirit of God keeps in the fear of the Lord, and under judgment;
then after getting acquaintance or knowledge, and a familiarity, and a liberty,
but not in the holy spirit, there is greater danger;
and therefore your knowledge and familiarity must be in the invisible spirit;
for the flesh fadeth and withereth, as the grass.
So that knowledge and familiarity is as grass that withers;
but the word of the Lord endureth forever.
And the right knowledge of one another is this:
to know one another in that word which was in the beginning, before man fell;
"`for man liveth not by bread alone,
but by every word that proceedeth out of the mouth of God.`"
This is the fresh and heavenly food from above,
and above all the husks that the swineherd feedeth his swine with,
in the unrepented state.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 295.

[.salutation]
Friends,

All keep your meetings in the power of the Lord God, that hath gathered you;
and none to quench the spirit, nor despise prophesying;
and so keep up your testimony in public and private.
Let not the mouths of babes and sucklings be stopped, nor the seed in males or females;
but all be valiant for the truth upon the earth.

Concerning your women`'s meetings;
encourage all the women of families that are convinced, and mind virtue,
and love the truth, and walk in it, that they may come up into God`'s service,
that they may be serviceable in their generation, and in the creation,
and come into the practice of the pure religion,
which you have received from God from above, that every one may know their duty in it,
and their service, in the power and wisdom of God;
for now the practical part is called for.
People must not be always talking and hearing,
but they must come into obedience to the great power
of the great God of heaven and earth.

And so that none may stand out of the vineyard idle, and out of service,
and out of their duty; for such will talk and tattle,
and judge with evil thoughts of what they in the vineyard say and do.
And therefore the power of God must call all into their duty, into their service,
into their places, into virtue, and righteousness, and into the wisdom of God.
For all that be out of their duty in their service, though they have the knowledge of it,
yet are not so serviceable in the creation, nor in their generation;
for the power of God must go over, and is over all such;
by which power all must be acted; in which true obedience is known.

And, therefore, train up your young women to know their duty in this thing,
that they may be in their services and places;
which they are to do in the power and wisdom of God;
by which you are kept open to the Lord, to receive of his gifts, and graces,
and of his life, through which you are to minister one to another.
And all keeping in it, then there is none to let or stop its flowing,
but through it you all are to be watered as a garden of plants,
by which they are nourished.
And so all be faithful and diligent in the Lord`'s business,
and make all the sober women, professing truth in the country about you,
acquainted with this thing; and when you have them together at the Monthly Meeting,
read this among them.
So no more but my love.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 296.

[.salutation]
Dear friends,

Keep in the power of the Lord; for if you lose that,
you lose the kingdom which stands in power, and peace, and righteousness,
and joy in the holy ghost; for out of the kingdom is strife, and no peace;
and therefore keep in the power, and life, and love, which you did first receive;
that you all may be heirs of the kingdom, and sit under your teacher the grace of God,
which will bring your salvation, that you may witness that you have a teacher from God,
that doth bring your salvation; which salvation is your walls and bulwarks,
that he may be glorified, and ye may have your comfort in your salvation.
And keep your men`'s and women`'s meetings, both being heirs of life,
and of the gospel order, and of Christ and his government;
though you may have some opposers.
But this is a day of possessing of Christ, and his government, and of the gospel order;
and therefore do not lose your authority, men nor women, in the gospel, nor in Christ;
though some may slight it.
For the foundation of our men`'s and women`'s meetings is Christ Jesus,
who bruiseth the serpent`'s head, who is the head of all false orders and foundations,
and the gospel, which is the power of God, which bringeth life and immortality to light,
shines over him that did darken you: which power of God he is out of.
And therefore all in the power and spirit, encourage both men and women in their duty,
in the order of the gospel of Christ, in whom you have dominion,
and in him who changeth not.
My love is to you all.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 297.

Dear friends, to whom is my love in that which changeth not, the royal seed,
that bruiseth the serpent`'s head, in whom you have life and peace,
in that live and walk, that you may bear fruit to the glory of God,
and answer that of God in every one.
And live in the peace that passeth knowledge and understanding;
and in this troublesome time of wars and strife, mind the power of God,
and his kingdom that standeth in righteousness, and joy in the holy ghost,
that is over all, and never will have an end;
and that will keep you over all these times of trouble, fresh in the life and power.
My troubles have been great in the service of the Lord;
and the convincement of people is great in America, and the islands in those parts;
blessed be the Lord God over all forever.
Amen.
Whose power, and life, and truth are over all;
and he in his power gave dominion over all, by sea and by land.
And people and Friends are well settled beyond the sea;
and meetings are precious beyond words.
So in haste, my love to all Friends, in all those parts, as though I named them;
and live in love, for that doth edify you.

[.signed-section-signature]
G+++.+++ F.

Bristol, the 1st of the 6th month, 1673.

[.centered]
=== Epistle 298.

[.blurb]
==== To Friends at Jamaica.

[.salutation]
Friends,

We do hear that some, professing truth amongst you,
do not keep to your meetings so diligently as they ought to do,
nor yet meet but few of you together on the First-days.
And the reason is, that upon the First-days some of you write and make up your accounts;
so as you cannot have time to go to and frequent the meetings.
Truly friends, this is an ill savour to come over here into England,
and shows that you mind your own business more than the Lord`'s,
and the things of this life,
more than the things that appertain to the life that is without end;
which should be sought for first, if you desire to be blessed and to prosper.
And if you do not, you will grow loose and wither,
and not have the blessing of God with you; you cannot expect it.
And therefore, you that go under the name of the friends of God and of truth,
keep diligently your meetings on the First-day together,
that the Lord`'s power may stir among you;
for if you do not keep your meetings upon the First-day of each week,
you are worse than the world, that meet in their steeple-houses or places of worship,
who prefer your own business before the Lord`'s. The Lord, I say, will not,
in so doing prosper you in it.
And therefore I say once more, in the name of Christ Jesus, keep your meetings,
who are gathered in it.
And let there be meetings on the week days, and also men`'s meetings,
to see that nothing be lacking among you, once in a fortnight;
and likewise a women`'s meeting, though there be but a few.
For you that have seen the order of truth in England and other places,
how can you go out of the practice of it, without growing wild and withering.
That so men and women in their distinct places, may be helps-meet in government,
in the seed of life, and in the wisdom of God, by which all things were made,
and in the gospel, the power of God, which was before the devil was:
so that you may feel the presence of the Lord with you.
And that all Friends may be invited to the meetings;
and that you may be good examples and patterns unto all in the island,
in righteous dealing and doings, in weights and in measures.
And keep to the sound language, and the honour that you have received from above;
so that your lives and conversations may preach in virtue, righteousness, and holiness,
that God may be glorified through you, and among you all,
that you may be patterns in holiness, and in truth, as you expect the blessing of God in,
with, and among you.
And owe nothing to any man but love.
And so seek first the kingdom of God, and keep in it,
then all outward things will flow to you, so as there will be no want of them,
if you enjoy God, who upholds all with his word and power, and gives the increase of all.
And see that there may be no ill example among you,
and no such ill report may be heard of you in Old England.
And when you have got up your First-days and weekly meetings,
and men and women`'s meetings, in the power of God,
which will preserve you in truth and righteousness,
see that nothing be lacking among you; then send over how things are with you,
how truth spreads and prospers, from your men and women`'s meetings,
to the men and women`'s meetings in Old England.
So no more but my love.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 299.

[.salutation]
Dear friends,

Let your faith stand in the power of God,
for that is your keeper unto the day of salvation;
so every one that hath not yet obtained it, come to that day,
for the kingdom stands in power, and not in words.
Therefore, as I said before, let your faith stand in the power of God,
in which the kingdom stands, the kingdom of peace and joy, which stands in righteousness,
and holiness, and in the holy ghost; where no unclean thing enters, neither can it.
For the power of the Lord God keeps you fresh, keeps you open, and keeps you alive,
and keeps you in a sense of the things of his kingdom, the treasures, the pearls,
and riches, and jewels thereof; and this power will keep you all in peace, and in unity,
and quietness, and condescension, and love, and kindness one to another;
and in the power of the Lord, and in his spirit,
you will be enabled to give the Lord his glory, and continual praise,
and continual thanks, which is due unto him from you all;
it will ascend to him who is worthy of all, blessed forevermore.
And so none quench the spirit, nor the motions of it in you,
lest Isaac`'s well be stopped up by the uncircumcised Philistine,
that must go down into the pit, who loath lived aloft;
for as Christ comes to take the peace from the earth, which men are in,
as all sects and ways, that have peace in their ways, religions, and worships,
and traditions of their forefathers; as in the days of his flesh,
when he came amongst the Pharisees, Sadducees, Herodians, Scribes,
and other sects among them; and likewise all others, that now have a peace in the earth,
and that are settled in it,
they must know that peace taken away before they are redeemed out of the earth;
and so as he taketh away that peace, such as come to learn of him,
and to be his disciples and followers, his peace he gives unto them;
who is the King of peace, the Prince of peace, and of life;
and which is such a peace that the world cannot take away from them.
And this you and all Friends everywhere, have sufficiently known,
who have been and are the learners of Christ Jesus, both men and women,
that in all your persecutions, mockings, imprisonings, spoiling of goods,
they could never take your peace away, which you had from this Prince of peace.
Is not this true, and the scripture fulfilled in you?
Therefore let him have the praises and the glory out of all your hearts;
and keep this peace, in the unity of the spirit, the bond of peace;
you are bound to keep it with the spirit, this Prince of princes`' peace;
you are all bound to keep it by the law of life, the law of the spirit;
for Christ is the same now, today as yesterday, and so forever;
the same as in the apostles`' days, who said,
"`Think you that I came to send peace on earth?
I tell you nay; but rather debate.
For the father shall be against the son, and the son against the father.
And the mother against her daughter, and the daughter against her mother.
And the daughter in law against her mother in law,`" etc. Luke 12:53.
"`And he that loveth father or mother more than me,
is not worthy of me,`" said Christ Jesus.
"`Or he that loveth son or daughter more than me, is not worthy of me.
And he that taketh not up his cross, and follows not me, is not worthy of me.
He that will save his life, shall lose it;
and he that is willing to lose his life for my sake, shall save it.`"
And, speaking to his disciples, said, "`He that receiveth you, receiveth me;
and he that receiveth me, receiveth him that sent me.`" Matt. 10.
These things, friends, have been seen, and have been fulfilled,
and must be fulfilled; for Christ is the same today as yesterday, and so forever.
For have not you seen, son against the father, and father against the son;
and mother against the daughter, and daughter against the mother?
etc. And this hath been through retaining Christ, who sets at variance,
and so not at peace; for he doth not bring a peace to that nature they lived in,
in old Adam.
And so we may see, when people are convinced, what variance it maketh in a family.
This hath been seen and fulfilled, when a husband is convinced, or a wife is convinced,
or son or daughter in a family is convinced.
And this must be fulfilled, and interprets itself in the fulfilling;
for he brings a sword and war, and not peace to that nature they lived in,
and had in old Adam, before they received the Prince of peace,
and the sword of the spirit from him to war against the other peace which they had;
and so the peace of all religions must be broken
before they come to the true religion from above;
and the peace of all worships must be broken,
before they come to the worship in the spirit and truth the devil is out of;
and the peace of all ways must be broken, that men and people are in,
before they come into the way of Christ Jesus;
and the peace of all churches must be broken,
before they come to the church which is in God;
and the peace of all fellowships must be broken,
before they come into the fellowship of the spirit, and unity therein,
which is the bond of peace; and the peace of all earthly teachers must be broken,
who are made of men by natural tongues, before they come to the heavenly teacher,
and the tongue of the learned indeed;
and the peace of all earthly bishops and shepherds
must be broken before they come unto Christ,
the bishop of the soul, and heavenly overseer, and heavenly shepherd,
who feeds with his heavenly food; and so the heavenly priest,
made higher than the heavens, who is holy, harmless, separate from sinners,
breaks the peace of the earthly priests,
and of all them that are made lower than the heavens,
(mischieful,) that are not separate from sinners, nor from sin, but hold up sinners,
and prop them up, and plead for sin term of life; this Prince of peace,
made higher than the heavens, breaks all their peace,
as he did above sixteen hundred years since, for he is the same now as then,
and his power and spirit will make them rage still, and they that confess him before men,
they will rage at them still.
And therefore, as I said, keep in Christ`'s power, in which the kingdom stands,
and not in words, that you may see the fulfilling of the scriptures;
and stand still in the power, which will keep you all to the day of salvation,
that are not come to it.
And so the Lord preserve you in his fear, and give you wisdom from above,
that you may be preserved in the unity of the spirit,
which (as I said before) is the bond of peace,
which is your duty to keep the peace of the Prince of princes.

And all you that have received the power of Christ in your hearts,
have you not seen what wars, and what rumours, and nation against nation,
as it was in the two births in the womb, that came forth, two nations, two births,
nation against nation; and much may be seen, what wars outwardly there have been,
and bringings down, before the appearance and receiving the Lord;
and so here he being received, here is people against people, and nation against nation,
and earthquakes, and shakings within and without.
They that receive the Lord`'s power must feel this, and know this,
and see the fulfilling of it, and not look out, for his kingdom without,
like a company of Pharisees, lo here, lo there, but as Christ, the power of God,
is known within,
(as Christ said the kingdom of heaven is within,) and as they come to feel it there,
they shall know the shakings and earthquakes, and wars, and rumours,
and that part that pertains to nations,
that must be shaken before they come to be of the holy nation,
which is against the other; and this is to be known, and seen, felt,
and fulfilled with the power of Christ Jesus, and by his spirit;
as they that live in it may take a prospect of these wonderful
things and workings of the Lord God and his power in this age.
Therefore be still in the power of God, which is your keeper, as I said before;
for it is your keeper in the night, before you come to the day,
and it keeps you to the day of salvation; for the virgins lamps did burn in the night,
and it was their light, and they that were wise, that got oil in their lamps, entered;
for the voice of the bridegroom was at midnight, and bid them arise.
And so as outward midnight is a great while off the day star`'s arising;
yet here is a lamp burning.
Therefore every one see that you get oil in your lamps, that you may not go forth,
that you may arise at the hearing of the heavenly voice of the bridegroom,
and enter with him; though Satan`'s messengers have told you,
there is no hearing his voice now-a-days.
Sad messengers they are, and have been,
they see who have received the true message of the Messiah in his power,
through which they see over them, and see their own foundation, Christ Jesus,
who was the foundation of the prophets and apostles.

[.signed-section-signature]
G+++.+++ F.

Let this be read in your men`'s and women`'s meetings, and copies kept in their books.

Worcester Prison, the 2d of the 7th month, 1673.

[.centered]
=== Epistle 300.

[.blurb]
==== To all the Women`'s Meetings.

[.salutation]
Dear friends,

This is the day for all to take your possessions, that know the gospel, the power of God,
which brings life and immortality to light in them.
I say, this is the day for all to take their possessions of this gospel order,
which was the apostles`' doctrine to the church in the primitive times,
that they should keep the comely order of the gospel.
The words are general to men and women; and now you being heirs of the gospel,
as was said before, that hath brought life and immortality to light in you,
by which you see over the devil, that has darkened you, and before he was,
in whom is all disorder.
Therefore keep this comely order of the gospel, the power of God,
the everlasting order and gospel, it will outlast all other orders in old Adam;
in which order of the gospel you have joy, you have peace and comfort.
So every one take your possessions of this holy, everlasting, joyful,
and peaceable gospel and order; for the peace is in the power of God;
so it is called the gospel of peace, that keeps all in the peace,
which you have from the Prince of peace, that the world cannot take away from you;
and likewise that you may be heirs and possessors of Christ, and of his government,
which is pure, holy, righteous, and heavenly,
of the increase of this heavenly man`'s government there is no end;
but there will be an end of old Adam`'s and the devil`'s, which began in time,
and will end in time, but there will be no end of his,
that was set up from everlasting to everlasting.
So all be possessors of this heavenly government, and of this heavenly, glorious,
and comely order.

And whereas it hath been said by them which are without,
you must come to hear the gospel preached; the answer is,
and will be from the possessors of the gospel, I am an heir of the gospel,
and do inherit it; for it is my portion, and do know it and possess it,
and need not thee to tell me of it, and of my portion.

And whereas it hath been said by them without, you must come and hear Christ preached.
The answer is from the possessors of him, I have examined myself, and proved myself,
and have found Christ Jesus in me, and he rules in my heart by faith; and I am in him,
and he is in me; "`and behold ye`" (that is as much as to say,
take notice) "`all things are become new.`"

And whereas the saying has been by them that are without,
why do not you come to hear the word preached?
The answer is, and will be, from the possessors of him, the word is nigh me,
in my heart and mouth, to obey it and do it; and need not say to any,
who shall ascend to bring it down from above,
or who shall descend to bring it up from the grave;
for I am come to the righteousness of faith`'s speaking, (mark,
faith`'s speaking,) that saith on this wise, "`The word is nigh thee,
in thy heart and mouth,
to obey it and do it;`" by which word I am born again of the immortal seed, which lives,
and abides, and endures forever;
by which word I have milk to give freely to babes and sucklings.
So the possessors have breasts; and the possessors`' breasts are not dry;
glory to the Lord forever.
So no more but love; and God Almighty preserve you in his wisdom,
that is pure and gentle from above, by which you may be all ordered,
and order all that you have under your hands to his glory.
And keep in the unity of the holy spirit, which is the bond of peace,
of the Prince of princes`' peace,
which is every one of your duty to keep this heavenly peace of the Prince of princes,
which none can take away from you; for you are bound with the spirit to keep it,
so that your praise may be in the gospel;
that you may admonish and exhort all that do profess the truth of the gospel,
that they may walk in the truth, as becomes the gospel,
and that every one that does profess Christ Jesus, and has received him,
may walk in him in the new and living way, out of the old way.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 301.

To all Friends that live in the truth, and by it are become God`'s freemen and women,
and by the truth and power of God are brought out
of the world`'s vain fashions and customs,
in their feastings, and revelings, and banquetings, and wakes, and other vain feastings,
where they spoil the creatures, and dishonour the Lord God more those times and days,
which they call holy days, and feast days, than any other times and days;
and therefore you that are brought out of such things,
and do see the vanity and folly of them;
and likewise you that are brought out of all the
extravagant feastings of companies in corporations,
and of making of feasts, when the masters of companies are chosen, and constables,
and head-boroughs, you see their vanity, and their folly, and madness,
in their destroying of the creatures, to the reproach of christianity,
and the dishonour of God, and the blaspheming of his name;
and many times through the abusing of themselves by excess,
are more like beasts than men, in these things and doings;
and therefore as you do see the folly and vanity of all such doings,
in their voluptuous and vain feastings, and cannot observe their evil customs,
then that vain spirit is in a great rage and fury, because you have, and do,
break off fellowship with them in all these their vain customs.
And therefore you that are redeemed from these things by Christ,
and from the feasting of the rich, and all other their vanities,
and voluptuous dishonouring of God therein; I say to you,
mind and practise Christ`'s words, as you may read in Luke 13:14. Christ saith,
"`When thou makest a dinner, call not thy friends, nor thy brethren, neither kinsfolks,
nor thy rich neighbours, lest they also bid thee again, and a recompense be made thee;
but when thou dost make a feast, call the poor, the maimed, the lame, and the blind,
and thou shalt be blessed; for they cannot recompense thee again,
but thou shalt be recompensed at the resurrection of the just.`"
So here you may see how Christ ordereth thee to make a feast or a dinner, and to whom,
contrary to the world; and though it be a cross to them, yet it is to be obeyed,
and observed, and practised; for it is the heavenly man`'s doctrine, and command,
and will, and he that doth it shall know his doctrine;
and this will judge the world in their vain feasts, dinners, and suppers,
which they make for the rich, for which they have self-reward.
But Christ`'s command being obeyed, denieth self, and hath the Lord`'s recompense;
and all that call him Lord, should do as the Lord commandeth;
and they that are his disciples, and do love him, will keep his commands;
for saith Christ, "`If you love them that love you, what thank have you?
For sinners also love those that love them.
And if you do good to them that do good to you, what thank have you?
For sinners also do even the same.
So give and it shall be given unto you.
Good measure, pressed down, shaken together,
and running over into your bosoms;`" and the Lord is kind to the unthankful,
and therefore, "`be ye merciful, as your heavenly Father is merciful.`"
Luke 6. And therefore as you have forsaken all the world`'s vain feastings, and dinners,
and suppers, (if so,) give the blind, the lame, the maimed, the widow, the fatherless,
and the poor, a feast or a dinner, and obey Christ, the heavenly man`'s doctrine,
though it do cross old earthly Adam`'s will and practices; and though he be angry,
never heed him, but obey the Lord.

G+++.+++ F.
