== Epistles 333 &#8212; 345

[.centered]
=== Epistle 333.

[.blurb]
==== An epistle to be read in the men and women`'s meetings.

[.salutation]
Dear Friends,

My love in the Lord Jesus Christ (to you all) in whom I have laboured,
and my desires are, the God of all peace, and the son of peace,
may fill your hearts with his love, and peace, and wisdom, and knowledge, in all things,
to do his heavenly glorious will: in that you will know his son`'s doctrine;
and as you know it, obey it.
And my desires are in the Lord, that you may all walk worthy of your vocation,
and of him that has called you to holiness, and righteousness, and to peace;
so that his peace may flow as a river, and righteousness run down as a stream,
to the gladding of the city of God; the walls of which are his power, and salvation,
and light, and life.

And now, my friends, keep all your meetings in the name of Jesus,
in whom you have all salvation; which is above every name under the whole heaven,
in which there is no salvation.

And also, all your men and women`'s meetings everywhere,
keep in the power of the Lord Jesus Christ, his gospel,
by which he hath brought life and immortality to light in you,
that you may see over him that hath darkened you, and before he was;
which power will preserve you in life and immortality.
So that you may now all labour in the gospel, the power of God,
in his glorious and comfortable gospel, joyfully serving the Lord in his gospel of peace;
through which gospel you have peace with God: so that in this gospel, the power of God,
there can come nothing between you and God: here is your heavenly order,
not of man nor by man.
So that all the faithful men and women may, in the Lord`'s power,
be stirred up in their inheritances of the same gospel, and to labour in it,
helps-meet in the restoration, as man and woman were before the fall,
in the garden of God.
All are to work in his righteousness, and in his image, in his power, in his garden,
to subdue the earth, and keep the dominion in his power, in the restoration,
as man and woman did in the image of God before the fall.
Whosoever would hinder you in this work,
it is the same serpent`'s spirit that led Adam and Eve into the fall,
from the work of God, which now would keep you in the fall, to do his work and command,
and not the Lord`'s; and therefore over that keep your dominion, authority,
and inheritance in the restoration, in the power of God,
in which every one of you must give an account to God.
And therefore be diligent in the Lord`'s power, light, life, and spirit,
in which you all see your services to God; so that he may be glorified among you all,
and in you all, and over you all his glory may shine.

And you all, men and women, in your men and women`'s meetings be diligent,
labouring in the light, life, and the power of God, the gospel,
in the garden and church of God;
so that righteousness and peace may flow down amongst you, and truth, and godliness,
purity, virtue, and holiness, over all that is contrary;
and that the weight and care of God`'s glory, and his honour, and his pure holy name,
and his truth, religion, and worship, you may all stand up for,
against that which would in any wise cause it to
be evil spoken of by ill walkers and talkers.
And let all things you do, be done in love,
and condescend one to another in the power of the Lord,
and in his truth have esteem one of another,
and let all things be done among you without any strife;
for it is love that edifies the body, and knits it together,
and unites it to Christ the heavenly and holy head.

And now, you women, though you have been under reproach,
because Eve was first in transgression; the promise was,
"`The seed of the woman should bruise the serpents head.`"
And this promise of God is fulfilled, "`A virgin should have a child,
and they should call his name Emmanuel, God with us, again.`"
For man and woman was driven from God out of paradise, and the serpent became their head,
and god of the world;
but Christ is come according to the promise of God and his prophets,
who was born of a virgin; and therefore saith Mary,
"`My spirit doth rejoice in God my saviour: my soul doth magnify the Lord,
for he hath regard to the low estate of his handmaid; for behold,
from henceforth all generations shall call me blessed.`"
Now, here comes the reproach to be taken off from women,
which were first in transgression, who are not suffered to speak in the church;
but here Mary did speak, and believe that which was spoken to her:
and also the reproach and transgression taken off men,
that believe in the seed Christ Jesus, who bruises the head of the serpent,
that has brought man and woman into his image, and his works;
but Christ destroys both him and his works,
and renews man and woman up into the image of God, as they were in before they fell,
and into the power, to have dominion, to work in his garden, to subdue the earth, etc.
So that all are now to labour in the garden of God,
that are in the power and image of God, being brought into it by Christ Jesus,
that bruises the serpent`'s head, that has been head in them all.
So that Christ Jesus may be head in all men and women,
and every man and woman may act from him their holy head, their life, and salvation,
and keep his heavenly peace in his church,
and every living member (believing in the light,
which is the life in Christ) may be grafted into him the fountain of life,
and receive from him the water of life, that they may feel the living springs,
and the rivers springing up in them to eternal life: these are living stones,
the spiritual household, of which Christ is both head, rock, and foundation.

And Christ is called the green tree, which green tree never withers,
into whom they are grafted by belief in the light, which is the life in him,
from whom they all receive their heavenly living nourishment,
through which every graft is nourished;
then it comes to bud and bring forth fruit to the praise of the eternal God.
Now every one of these living believers are members of the living church in God,
which Christ is the head of, and every member in the church hath an office;
and so every member is serviceable in the body in his office, in the light,
which is over darkness, and was before it was; and in the life which is over death,
and was before it was; and in the power of God,
which was before the power of the serpent was.
And so they are in this light, life, and power to execute their offices: I say,
in this divine light, life, power, and spirit of God for God`'s glory, in truth, purity,
virtue, holiness, and righteousness, they are to stand up for the honour of his son,
and receive him, who hath all power in heaven and earth given to him;
and all that receive him, he gives them power to become the sons and daughters of God;
then in his power all are to act and walk, and to serve God in their generation,
and in it to serve him in the new creation, in righteousness and holiness,
and to stand up in his power for his glory, in his power, righteousness, and holiness,
that Christ brings into them, and renews them in, and so into the restoration;
that they may labour in the church and garden of God in his power,
to his everlasting praise and glory.
Amen.

And all Friends, stand fast in the liberty wherewith Christ hath made you free,
and in the liberty in the faith, which Christ is the author and finisher of;
which faith purifies the heart, and gives victory, in which you have access to God,
the mystery of which is held in a pure conscience;
in which faith it hath its true liberty.
And keep in the liberty of the everlasting glorious gospel of peace, which is not of man,
nor by man, but from heaven;
which gospel bringeth (and hath brought) life and immortality to light,
and will preserve you in life and immortality, over him that hath darkened you;
and in this gospel you have everlasting liberty and peace, and in the truth,
which maketh you free from him that is out of the truth.
This free state all are to keep in; and also in the pure holy spirit of God and Christ,
that doth mortify all that is to be mortified and crucified;
and doth baptize you into one body.
In this holy spirit you are to walk, which leadeth you into all truth,
in which is your unity and fellowship;
and giveth liberty from that which hath grieved it, and quenched, and vexed it.
And so in the liberty, and fellowship, and unity of the holy, pure, and peaceable spirit,
you are all to dwell and walk, which is the bond of the Prince of princes`' peace,
which the world cannot take away.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 13th of the 9th month, 1677.

[.centered]
=== Epistle 334.

[.salutation]
My dear friends,

To whom is my love in the everlasting seed, that reigns over all,
and will overcome all your persecutors, and the devil, that is the cause thereof,
who fighteth against the light,
(which is the life in Christ,) as they did against him in the flesh,
above sixteen hundred years ago.

And now, my friends, suffer as lambs in the time of your sufferings;
let all your wills be subjected with the patience that hath the victory;
and run the race, and obtain the crown of life;
and be willing to go to suffer for Christ`'s sake; for the apostle said,
"`It is not only given you to believe, but also to suffer for his name sake,
in whom you have salvation;`" for "`they that suffer for righteousness`' sake are blessed,
and theirs is the kingdom of God;`" and by faith the holy men of God had victory,
as you may see at large in Heb. 11.
So nothing is overcome by any man`'s will, but by faith that giveth access to God,
in which they do please God.
And I do believe that all your sufferings will be for good,
for your establishing upon the holy rock of life,
which was the rock of all the sufferers, the prophets, and the apostles,
who is the anointed saviour, to the answering that of God in all people;
for the Lord hath a great work and seed in that place.
So live in the spirit, that mortifieth all, and circumciseth all, and baptizeth all;
so that with the spirit you may sow to the spirit,
and of the spirit reap life everlasting.

And my desire is, that you may all be kept alive to God,
and live in the living unity of the spirit, which is the bond of the heavenly peace,
that passeth the knowledge of the world;
which peace brings such joys which transcend all your sufferings,
and will carry you above them.
And so in love to God, and in love to your persecutors,
you can pray for them who persecute you;
and this suffering is above all the sufferings in the world,
which are without love and charity, who maketh one another to suffer,
when they get the upper hand.
But such are not the sufferers for the true Lord Jesus, who suffered;
though he was above all, yet he made none to suffer; and when he was reviled,
he reviled not again, but said, "`Father,
forgive them;`" and committed himself to him that judgeth righteously.
So let the same mind be in you as was in Christ Jesus; for the apostle said,
that they had the mind of Christ, and the Lamb overcame, and had the victory;
and this his sanctified ones, that follow him, are partakers of.
Glory to his name forever.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 12th of the 5th month, 1677.

[.centered]
=== Epistle 335.

[.blurb]
==== To Friends at Sussex.

[.salutation]
My dear friends,

To whom is my love, and to the rest of Friends that aways.
And my desire is, that you may all suffer as lambs of Christ; for when he was reviled,
he reviled not again; and he gave his back and cheek to the strikers and smiters,
and his hair to be plucked off, and was as a "`lamb led dumb before his shearers,
and he opened not his mouth;`" though he was the King of kings, and Lord of lords:
and so left his followers and believers an example, that they should follow him,
like innocent lambs; for the Lamb and the saints have the victory over all the tearers,
and strikers, and pluckers, and devourers, and persecutors.
And so let patience have its perfect work in you and among you,
in which you run the race, and do obtain the crown of eternal life.
And do not strive, but keep down that spirit that would strive, with love,
which differeth you from all other sufferers that have not love, which envieth not,
neither is provoked, but beareth all things, and endureth all things,
and will wear out all evil doers.
And so be faithful, and of the good faith that hath the victory,
and in it suffer joyfully, as the saints did, and leave the gainsayers to the Lord God,
who will reward and repay them.
And keep in the seed that will out-last all, and bruise the head of the serpent.
And so the Lord God preserve you all both in life, word, and conversation to his glory;
and that all your words may be gracious.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 8th of the 5th month, 1677.

[.centered]
=== Epistle 336.

[.blurb]
==== Concerning subjection of the spirits of the apostles one to another, in the unity of the spirit of Christ.

The apostles heard at Jerusalem, that the Samaritans had received the word of God,
and they sent unto them Peter and John. Acts 8:14.
Now Peter and John did not, in opposition, say,
we will stay till we have a motion.
But as the spirits of the prophets were subject to the prophets,
so the spirits of the apostles were subject to the apostles.
And when tidings came to the church at Jerusalem, that the Grecians had believed,
they sent forth Barnabas to them, and when he came, he exhorted them;
and when Barnabas had found Paul, he brought him to Antioch,
(and there the disciples were first called christians,) and the church
sent the collection by the hands of Paul and Barnabas unto the elders.
Acts 11:22-23, 30. and 9:27. Paul and Barnabas took with them John,
whose surname was Mark; and Mark did not gainsay, and tell them,
I must wait for a motion. Acts 12:25.
It pleased the apostles and elders, with the church,
to send chosen men to Antioch, with Paul, and Barnabas, and Judas surnamed Barsabas,
and Silas, chief men among the brethren, and wrote letters by them unto the Gentiles. Acts 15:22.
saying, "`Forasmuch as we have heard,
that certain that went out from us have troubled you with words, subverting your souls,
saying, ye must be circumcised and keep the law; unto whom we gave no such commandment.
It seemed good unto us, being assembled with one accord, to send chosen men unto you;
men that have hazarded their lives for the name of our Lord Jesus Christ.`"
Paul said unto Barnabas, let us go again unto every city,
where we have preached the word of the Lord, and see how they do;
and Barnabas determined to take Mark with them; and Paul chose Silas,
being recommended by the brethren unto the grace of God;
and they went through Syria and Cilicia; and as they went through the cities,
they delivered them the decrees for to keep,
that were ordained of the apostles and elders which were at Jerusalem;
and so were the churches confirmed and established in the faith,
and increased in number daily. Acts 16:4.
The brethren exhorted the disciples to receive Apollos. Acts 18:27.
And Paul sent unto the Ephesians, and called the elders of the church,
and exhorted them. Acts 20:17.
Paul commends "`Phebe,
a servant of the church which is at Cenchrea,`" and bid them receive her in the Lord,
and assist her in whatsoever business she hath need of.
Rom. 16. Now if Timothy come, so that ye receive him without fear,
let no man despise him, but conduct him forth in peace, that he might come unto me,
for I look for him with the brethren.
Paul said to the Corinthians,
"`Did I make a gain of you by any whom I sent unto you?`" 2 Cor. 12:17.
"`Or did Titus make a gain of you?
Tychicus, a beloved brother and faithful minister of the Lord,
shall make known unto you all things; whom I have sent unto you for the same purpose,
that you might know our affairs, and comfort your hearts.`" Eph. 6:21-22.
Paul sent to the Colossians, Onesimus with Tychicus,
to make known all things unto them that were done with him. Col. 4:9.
And when they had read his epistle,
they were to cause it to be read at Laodicea;
and Paul charged the Thessalonians by the Lord,
that they did read his epistle amongst all the holy brethren. 1 Thess. 5:27.
And Paul saith, "`Take Mark, bring him with thee,
for be is profitable to me for the ministry; and Tychicus I have sent to Ephesus.`" 2 Tim. 4:11-12.
Paul said to Titus, chap.
3:12. "`When I shall send Artemas or Tychicus unto thee,
be thou diligent to come unto me to Nicopolis, and bring Zenas the lawyer, and Apollos,
on their journey diligently, that nothing be wanting unto them.`"
Paul saith to Philemon, "`Having confidence in thy obedience, I wrote unto thee,
knowing that thou wilt also do more than I say.`"
Philemon 21-22. John saith, 2 Epist.
"`Look to yourselves, that we lose not these things that we have wrote,
but that we may receive a full reward.
I wrote unto the churches, but Diotrephas,
who loveth to have the preeminence amongst them, received us not.
Wherefore if I come I will remember his deeds which he doth,
prating against us with malicious words,`" 2. and 3. epistle of John.
And in Jude, such as go in Balaam, Cain and Korah`'s way, "`wandering stars,
raging waves of the sea, wells without water, clouds without rain, trees without fruit,
twice dead and plucked up by the roots, their mouths speak great swelling words,
to whom is reserved the blackness of darkness forever.
These are they that separate themselves, such as have not the spirit.
But, beloved, build up yourselves in the most holy faith, praying in the holy ghost;
and keep yourselves in the love of God.`"
Jude.
"`Now I praise you, brethren, that ye remember me in all things,
and keep the ordinances as I delivered them unto you;
and the rest will I set in order when I come.`"
1 Cor.
11: 2, 34. Paul in his second epistle to the Thessalonians, chap.
3:4. "`And we have confidence in the Lord touching you, that ye both do,
and will do the things which we command you.
Now we command you, brethren, in the name of our Lord Jesus Christ,
that ye withdraw yourselves from every brother that walketh disorderly,
and not after the tradition which he received of us.`" "`Now we exhort you, brethren,
to warn them that are unruly, and comfort the feeble-minded, and support the weak,
and be patient towards all men, for ye yourselves are taught of God to love one another;
and that ye study to be quiet, and walk honestly to them that are without;
and that ye may have lack of nothing.`" 1 Thess. 5:14.
And in 2 Thess. 2:15. "`Therefore, brethren, stand fast,
and hold the traditions which you have been taught, whether by word or our epistle.`"

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 337.

Dear friends, to whom is my love in the heavenly seed Christ Jesus,
in whom all nations are blessed; Oh! therefore keep all in this seed,
in which ye are blessed, and in which Abraham and all the faithful were blessed,
(without the deeds or the law,) and so the promise was and is to the seed,
and not to the law of the first covenant.
And in this seed all nations and ye are blessed,
which bruiseth the head of the seed which brought the curse,
and separated between man and God.
This is the seed which reconciles you to God,
and this is the seed in which ye are blessed, both in temporals and spirituals;
through which you have an inheritance, that cannot be defiled, among the sanctified,
neither can any defiled thing enter into its possession,
for all defilements are out of this seed.
This is that which leavens up into a new lump,
and bruiseth the head of the wicked seed that leavens into the old lump,
upon whom the sun of righteousness goes down and sets;
but never goes down nor sets to them that walk in
the seed in which all nations are blessed;
by which seed they are brought up to God,
which puts down that seed which separated betwixt them and God;
so that there comes to be nothing betwixt them and God.

And so now, all my dear friends, my desires are, that you may all be valiant,
in this heavenly seed, for God and his truth upon the earth, and spread it abroad,
answering that of God in all;
that with it the minds of people may be turned towards the Lord,
that he may come to be known, and served, and worshipped,
and that ye may all be the salt of the earth, to make the unseasoned savoury.
And in the name of Jesus, keep your meetings, who are gathered into it,
in whose name ye have salvation, and he in the midst of you,
whose name is above every name under the whole heaven.
And so you have a prophet, and bishop, shepherd, priest, and counsellor,
above all the counsellors, priests, bishops, prophets, and shepherds,
under the whole heaven, to exercise his offices among you, in your meetings,
that are gathered in his name.
And so Christ`'s meeting and gathering is above all
the meetings and gatherings under the whole heaven.
And so his body church, and He the head of it, is above all the bodies, and churches,
and heads under the whole heaven.
And so the faith that Christ is the author of, and the worship that he hath set up,
and his fellowship in his gospel, is above all historical faiths,
and the faiths that men have made, together with their worships and fellowships,
under the whole heaven.

And now, dear friends, keep your men and women`'s meetings in the power of God,
the gospel, the authority of them, which brings life and immortality to light in you.
And this gospel, the power of God, will preserve you in life and in immortality,
which hath brought it to light in you, that ye may see over him that hath darkened you,
and so from the knowledge of the things of God.
And so, it is he and his instruments, that would darken you from life and immortality,
and that would throw down your men and women`'s meetings,
which are established in the power of God, the gospel,
and would darken you again from this life and immortality,
which the gospel hath brought to light; and will preserve you in life,
and in immortality, as your faith stands in the power of God, the gospel,
in which every one sees your work and service for God.
And every heir of the power of God, the gospel, hath right to this authority,
which is not of man, nor by man; which gospel, the power of God, is everlasting,
and leads you into an everlasting fellowship; and in the gospel is everlasting joy,
comfort, and peace, which, will out-last all those joys, comforts, and peace,
that will have an end; and also that spirit that opposes its order,
and the glorious fellowship, peace, and comfort that are in it.

And now, my dear friends, my desire is, that ye may keep in the unity of the spirit,
that baptizes you all into one body, which Christ is the heavenly and spiritual head of;
so that you may see, and witness to your heavenly and spiritual head;
and all drink into that one spirit;
which all people upon the earth are not like to drink into while they grieve, quench,
and rebel against it; nor be baptized into one body, nor keep the unity of the spirit,
which is the bond of peace: yea, the King of kings and Lord of lords`' peace,
which is the duty of all true christians to keep, who are inwardly united to Christ.
So with my love in the everlasting seed.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 26th of the 7th month, 1678.

[.centered]
=== Epistle 338.

[.blurb]
==== To Friends in the County of Oxford.

[.salutation]
Dear friends,

Keep in the Lord`'s power, that his kingdom stands in, and in righteousness, and peace,
and joy in the holy ghost, which the devil and all his instruments of strife and debate,
and sowers of discord among brethren, are out of;
and keep that spirit out with the power of God, which was before it was;
in which gospel (the power of God) is your holy and heavenly order;
in the possession of the same labour, walking in the new and living way,
over all the dead ways in Adam, let them be what sect they will;
and in this new and living way you have the life and the truth,
which death and darkness cannot get into, which is out of the truth,
though they may talk of the words of the truth.
But keep in the pure religion that was set up above sixteen hundred years ago;
and this pure religion, which is undefiled before God,
will keep you from the spots of the world,
and above all the spotted and dirty religions that are not pure,
but are defiled before and in the sight of God.
And in this religion, in your men`'s and women`'s meetings,
that are in the gospel of Christ, and in the order of it,
you will see that nothing is lacking, being ordered by the holy, pure,
peaceable and gentle wisdom of God from above.
And so keep in the worship of God, in the new covenant, in the spirit, and in the truth;
which the devil, that foul spirit who is out of the truth, cannot get into,
nor his company: and so in the seed of life, which bruiseth the head of the serpent,
all dwell, and sit down, who is the Amen, the first and last,
in whom you have peace with God; and then nothing can get between you and the Lord God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 339.

[.blurb]
==== To the Yearly Meeting in Yorkshire.

[.salutation]
My friends,

In the service, and in the work of the Lord Jesus Christ, the second Adam, in his power,
light, and truth live, over death and darkness, and him that is out of the truth.
So, all in the seed that bruises the serpent`'s head,
stand up for God`'s glory and honour; in which seed you are all one, male and female;
and in which seed you all have peace and unity that is everlasting.
And in this heavenly seed,
see that all walk as becometh the glorious gospel of Christ Jesus,
which hath brought life and immortality to light through the gospel;
by which ye do see over him that hath darkened you.
And this gospel, the power of God, will keep you in life and in immortality;
in which you may all see your work and service for the Lord God, in holiness,
and in righteousness, and in godliness, that the Lord God may be glorified in you all,
and among you all, who is over all, blessed forever.
Amen.

And, friends,
see that all your children and families be trained up in the new covenant of grace,
and in life, and peace, and circumcised and baptized with the spirit,
that they may all eat of the spiritual food,
and drink into one spirit in the new covenant, and to feed upon the substance,
as the Jews did on the shadows in the old, which faded away.
And the power of God, the gospel, is the authority of your men`'s and women`'s meetings;
and every heir of the gospel is to labour in their inheritance and possession,
in the restoration into the image of God, in righteousness and holiness,
being made by Christ, that never fell, helps-meet in the restoration,
(as they were before the fall,) who is the first and last,
the foundation and rock of ages.
In him sit down in life, and peace, and rest, the Amen,
that nothing may get between you and the Lord God;
and see that nothing be lacking among you, then all is well.
So with my love in the Lord Jesus Christ.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 3d of the 4th month, 1678.

[.centered]
=== Epistle 340.

[.salutation]
Friends,

Know what the Lord doth require of you, and all have a sense of that in yourselves,
that he doth require; which is, "`to do justly, and to love mercy,
and to walk humbly with God.`"
Now, the Lord who is merciful and just, holy and righteous, pure and perfect,
he doth require, that man and woman should do justly and righteously,
and live godlily and holily, by the holy light, and spirit, and truth, and grace,
that the Lord hath given every man and woman to profit withal.
And so, to answer the holy, pure, righteous, just God of truth, in all their lives,
and words, and conversations; and so, to glorify him upon the earth.
And the more the Lord gives, the more he requireth; and the less that he giveth,
the less he requireth.
But the Lord requireth of every man and woman as he giveth,
who will judge the world in righteousness, by the man Christ Jesus,
according to the gospel, the power of God,
that is preached to every creature under heaven; that is,
according to the invisible power; manifesting,
that there is something of the invisible power of God in every man and woman.
So, here the Lord Jesus Christ doth not judge according to the hearing of the ear,
and to the seeing of the eye; for with righteousness shall he judge you,
according to the light, which is the life in the word, Christ,
with which he doth enlighten every man that cometh into the world,
to the salvation of them that believe in it,
and the condemnation of them that do hate it, and that will not receive the gospel,
nor the grace, which bringeth salvation, which hath appeared to all men,
but walk despitefully against the spirit of grace, and turn it into wantonness.
So, according to his grace, and light, and gospel,
will the righteous God judge the world in righteousness, by Christ,
the heavenly and spiritual man, who hath died for the sins of the world;
though they deny him that bought them, and tasted death for every man.
Such deserve his judgment.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

Send this abroad among Friends, to be read in their meetings.

====

[.signed-section-context-close]
Swarthmore, the 11th month, 1678.

[.centered]
=== Epistle 341.

[.blurb]
==== An epistle to Friends, to keep in the power of God in their peaceable habitations, over all the troubles of the world.

All my dear friends and brethren, who are gathered by the light, grace, and truth,
and power, and spirit of Jesus Christ, to him, the head over all,
by whom were all things created, the first-born of every creature,
and the first-begotten from the dead, know him, and the power of his resurrection,
that you all may be partakers of it, and of life everlasting,
and may sit together in the heavenly places in Christ Jesus, who is over all,
the first and last.
And in him you have peace, who is not of this world; for in this world there is trouble.
And the world did and doth hate Christ, yea, and his light, grace, truth, power,
and spirit; and therefore it is no marvel if the world do hate Christ`'s members,
that do follow him in his light, grace, truth, power, and spirit;
and so with it receive him into them, their life and salvation.
And so he that hath the son of God hath life;
who is the fountain that filleth all that wait upon him,
with his heavenly blessings and riches of life, from Christ the rock and foundation,
that cannot be shaken, though the rocks and foundations of the world may be shaken,
and cloven in pieces, and the pillars of the earth may reel and stagger,
and all hypocrites and sinners may fear; but they that fear the Lord, and wait upon him,
shall be as Mount Zion, that cannot be removed; for the Lord`'s power is over all,
by which he keeps his people to the day of salvation.

And therefore, all you that have this keeper, the power of the Lord,
through faith unto the day of life and salvation,
need none of the slumbering keepers or watchers; for the Lord was the keeper of Israel,
who neither slumbered nor slept, till Israel forsook the Lord,
and then they set up slumbering and sleepy watchers and keepers;
like the apostate christians, who have forsaken the power of God to keep them,
and then they are soon forsaken.

And therefore, friends, you that do know the power of God,
in which the kingdom of God stands, you know your keeper,
through the faith which Jesus Christ is the author of, which stands in his power,
and not in words; and so your faith standing in his power,
it will keep you out of the words of men`'s wisdom, and above them.

And the golden lamp in your tabernacle, all are to have to burn with the heavenly oil,
which you have from Christ your high priest, being returned to him,
the great shepherd and bishop of your souls, who will bring you, his sheep,
into his safe fold; who gives unto his sheep eternal life,
and his sheep shall not perish, neither shall any pluck them out of his hand.
Though men may pluck hypocrites and apostates one from another; but Christ saith,
"`no man is able to pluck his sheep out of his Father`'s hand.`"
And therefore, all feel the hand that hath brought you out of spiritual Egypt,
where Christ hath been crucified, to Christ, in his new covenant of light and life,
as the Jews were brought out of Egypt in the old covenant, which Christ hath abolished,
and makes all things new; so that all may be grounded on him,
who was the foundation of all the holy prophets and apostles,
and of all the holy men of God to this day.

And therefore, consider who it is that abides in the tabernacle of God,
and dwells in his holy hill; it is the faithful and the upright,
which holy hill is a safe place for all the upright.
As the Lord said,
"`in the last days the mountain of the Lord`'s house
should be established on the top of the mountains,
and should be exalted above the hills,
and all nations should flow unto this established house.`"
And here the Lord does teach his people that come
up to the mountain of the house of the God of Jacob.
So all mountains, houses, hills, and teaching will be shaken,
but the mountain of the Lord`'s house shall be established in the last days,
as the prophet said, which are the days of Christ.

Is not this the stone that became a great mountain, and fills the whole earth,
which smote and broke to pieces the iron, clay, brass, silver, and gold image,
or monarchs, which were as mountains?
And this stone which becomes a great mountain,
sets up a kingdom which shall never have an end.
Is not this the kingdom of Christ, which Christ saith,
"`Except a man be born again he can neither see the kingdom of God, nor enter into it.`"

And therefore, friends, all you that do know his kingdom that stands in power, in peace,
and joy in the holy ghost, over the power of the evil, and all the unclean ghosts,
which keeps them in their first birth, and leads them into all evil,
as the holy ghost leads them into all truth.

And so, dear friends and brethren, know this rock, this stone, this foundation,
the house of God, that is established upon the Lord`'s mountain, above all other houses,
hills, mountains, and teachings in the world, where God doth teach his people,
and establish them upon Christ Jesus, the living rock and foundation, and living way.
And so though there may be troubles without, and troubles within;
yet if you wait upon the Lord, he will renew your strength.

And the children of God they are set for signs and wonders; for as it is said, "`Lo,
the children that thou hast given me, they are for signs and wonders.`"

And therefore, friends, keep your habitation in Christ Jesus, in whom you have peace;
for all the rude talkers, and vain disputers, and janglers, which canker and rust,
go out of the peaceable truth; and that which is torn, and dies of itself,
must not be fed upon, but the life must be fed upon, which gives you life eternal.

And the Lord did not build his Zion, and outward Jerusalem, with blood,
in the old covenant; for they that did build their Zion and Jerusalem with blood,
made their Zion a field, and their Jerusalem a heap;
so if this practice was forbidden in the old covenant, much more in the new,
who think to build Zion and Jerusalem with blood and iniquity;
for such have not been Zion`'s children, nor Jerusalem`'s, that is from above,
who shed men`'s blood concerning religion, church, and worship;
for Christ rebuked such that would have had men`'s lives destroyed, and told them,
they knew not what spirit they were of; so they that do not know what spirit they are of,
they are not like to build up God`'s Zion and Jerusalem.

For Christ said, He came to save men`'s lives, and not to destroy them;
for the world`'s god was the destroyer of men`'s lives,
but Christ came to destroy him and his works, and to save men`'s lives and souls also.

And so, dear friends, let the love of God, which is shed abroad in your hearts,
cast out all fear.
And keep in the name of Jesus, in which you are gathered,
which is above every name under the whole heaven, in whom you have life and salvation,
and his presence among you; whose name is a strong tower;
and Christ is a rock to hide yourselves in, and his spirit to cover you,
which is a covering sufficient enough for you;
"`and woe will be to that spirit which is covered,
but not with his spirit;`" they may fly to the rocks
and mountains to cover and hide them,
which will not be sufficient; for the rocks will rend, and the mountains will be removed;
such may run down into spiritual Egypt for strength, where Christ was crucified,
like the Jews in the old covenant, that ran into outward Egypt from his spirit,
but all was in vain.

And therefore, trust in the Lord,
who has preserved you by his glorious light and power to this day,
that you may be settled upon the seed Christ Jesus, which is over all that,
within and without, that is contrary to it, and bruiseth the head of the serpent,
that hath been between you and God.
So that in Christ the seed you have peace with the Lord God, life, and dominion,
and election, and salvation, who redeems out of the curse, and fear of men,
or that makes the arm of flesh his strength, and not the arm of God;
and therefore the arm of the Lord being your strength, Christ your rock and salvation,
then you need not fear what man can do unto you;
for all God`'s children are dear and tender to him,
whom he hath begotten again by the word of God to be heirs of his kingdom;
he feeds them with life eternal, and the milk of his word, which word lives, and abides,
and endures forever, and is always full and plenteous of milk,
and nourishes all God`'s children unto eternal life, and to inherit his kingdom,
and the world which is everlasting, which Christ is the ruler of,
(the heavenly and spiritual man,) and therefore they that are in him must be new creatures;
for all the old creatures are in old Adam.

And therefore my desires are, that you may all be settled in Christ Jesus,
who was dead and is alive again, and lives forevermore, a prophet, counsellor, priest,
bishop, and shepherd, a circumciser and baptizer,
a living rock and foundation forevermore, the beginning and ending, the first and last,
the Amen; sit down in him, and he in you, in whom you have peace with God.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 6th of the 12th month, 1678.

[.centered]
=== Epistle 342.

My dear friends, whose faces are set towards Zion,
from this dunghill world of vanity and vexation of spirit; the glory, comfort,
and pleasures of which pass away; they that have more or less of it,
and that enter into it, enter into trouble; and when they are in it,
it is a great trouble to come out of it, and to be a fool for Christ`'s sake,
who is not of this world, but of the world that hath no end.
And therefore you must believe in the light, grace, and truth that cometh from him,
in the inward parts or heart, which directeth your minds to Christ,
from whence this comes, and to unite to him that is heavenly, who saith,
"`seek the kingdom of God first.`"
and the righteousness of his kingdom,
then all outward things will be added to them that have found the kingdom of God,
that stands in righteousness over unrighteousness; and it stands in the power of God,
over the power of the devil, and was before he was,
and it standeth in peace and joy in the holy ghost, over all the unclean ghosts,
or unholy spirits; and the good seed are the children of this kingdom,
which is everlasting.

And take heed of your wills, and give not way to them,
but give way to the power and spirit of God, which crucifieth it,
and keeps it under the cross of Christ; so that your inward man may be renewed,
and the old Adam put off, so that the daylight of Jesus Christ may be seen,
which Abraham rejoiced to see, and so do they that be of the faith of Abraham,
which faith is the gift of God, that see the sun of righteousness shine in their hearts,
to nourish that which God hath there planted,
who watereth it with the living water of the word, his living plant.
And here is water in your own wells,
that you may drink out of your own wells or cisterns,
and to have grapes off their own vines,
from which they may have the new wine in their new bottles,
to glad and cheer their hearts with the wine from
the heavenly branch of the heavenly vine,
of which the Lord is the husbandman; and this must every one of God`'s people feel.

What is the matter that all the world is of so many ways since the apostles`' days?
Because they are out of Christ, the way, the new and living way,
(which is over all the dead ways) which was set up above sixteen hundred years ago.

And why have they so many religions?
Because they are out of the pure and undefiled religion before God,
which was set up above sixteen hundred years ago,
which religion keeps from the spots of the world;
and then this religion must be above the world, that keepeth from the spots of it;
and they that are gone from this religion, into those of their own making,
and tell people, they must not be perfect here,
and must carry a body of death with them to the grave: and others say,
that they must have a purgatory when they are dead;
this doctrine is contrary to the apostles, who said,
that "`they were cleansed by the blood of Jesus,
and washed by the water of the word;`" and this blood and
water God`'s people must feel the effects of within,
to wash and cleanse their hearts, souls, minds, and consciences;
"`their hearts and consciences being sprinkled (as the apostle
saith) with the blood of Jesus from their dead works,
to serve the living God:`" for many may talk of the
blood of Jesus without them in their dead works,
not serving the living God,
their hearts and consciences being not wrinkled with the blood of Jesus;
and they must feel it within as well as without.
And if they have life, they eat his flesh and drink his blood,
if they do live by him that is heavenly and spiritual, the second Adam,
the Lord from heaven: for they have drunk long enough into old Adam`'s unclean spirit,
which is the cause that there are so many bodies,
that they do vex and quench the good spirit, and "`resist the holy ghost,
which should baptize them all into one body;
that is to plunge down all sin and evil that is got up by transgression,
and burn that up which is chaff or corruption, and so to drink into one spirit,
as the apostles and churches did in the primitive times,
and so to have the same fellowship and unity in the holy spirit of Christ, as they had,
to wit, in Christ Jesus, who was, and is, the holy head of his church, his elect in him.
And Jerusalem, that is above, is the mother of all such; and such do worship God,
as Christ taught above sixteen hundred years ago, in spirit and in truth.

So all must come to the spirit and the truth in their hearts and souls,
if they do know the God of truth, who is a spirit,
and must worship him in spirit and in the truth;
into which holy spirit and truth the unclean spirit, and him that is out of truth,
cannot come.
So all will-worshippers, and the dragon, and beast, and false worshippers,
are out of this holy spirit and truth, in which the pure and holy God is worshipped;
and as all that did eat of the passover in the old
covenant were to be circumcised in the flesh,
so are all in the new covenant to be circumcised with the spirit,
by putting off the body of the sins of the flesh, that came upon man by transgression,
if they will feed on Christ their heavenly sacrifice.
For the old covenant of circumcision was held in the flesh,
and then they did feed upon the natural sacrifices;
but the new covenant is held in the grace, light, and spirit,
by which they are circumcised, and so do feed on their heavenly sacrifice:
for in the old covenant they were not to eat the blood of beasts, or any blood;
but in the new covenant Christ tells you, "`Except ye do eat my flesh,
and drink my blood, ye have no part in me:`" for as by Adam and Eve,
their eating that which God forbad, came death;
so if Adam and Eve`'s sons and daughters have life again,
it is by eating of that which Christ commands; and as by eating came death,
so by eating cometh life, and not by talking; no, not by talking of the son of God;
for all reprobates may do so; for the apostle saith, "`If Christ be not in you,
ye are reprobates;`" and "`He that hath not the son of God,
hath not life;`" and "`He that hath the son of God, hath life.`"
And the saints did confess the son of God was come, and had given them an understanding,
and they were in him, and they were to walk as he walked,
and not only to talk as he talked: for there are too many talkers,
and few walkers in Christ; my desire is there may be more.

And the Lord God Almighty strengthen you in your inward man,
and over all give you dominion in the seed of life,
which bruiseth the head of the serpent,
(that brought death and a curse,) and this seed bringeth the blessings,
in which all nations are blessed; and out of this seed they are not blessed,
though they may profess all the words of this good seed; and if they are not in it,
they have not the blessing in it; and they that be in this,
their blessings and peace flow as a river from the rock and foundation of life,
that standeth sure, which all the prophets, apostles,
and sanctified ones did and do build upon, who is their life and salvation.

So feel the stone that is cut out of the mountain without hands,
which must become a great mountain, and fill the whole earth,
which hath a kingdom that is everlasting, which, except a man be born again,
he neither can see it, nor enter into his kingdom.

And my desire is, that you (in your measures) may be preserved to the Lord,
and know what he doth require of you, "`To love mercy, to do justice,
and to walk humbly with God;`" for the more he giveth, the more he requires;
and the less that he gives, the less he requires;
who will judge the world in righteousness according
to the gospel preached in every creature,
showing that there is something of God in every creature that shall answer his judgment.
And therefore my desire is,
that all may be faithful to what the Lord hath made
known unto them by his grace and truth,
light, power, and spirit, and then the Lord will supply them with more;
to whom be glory and praise, who is the creator of all, through Jesus Christ,
by whom all things were made.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 343.

And, dear friends, my love to you all in the seed of life and peace,
which floweth as a river, and bruiseth the head of the serpent,
that hath brought death and darkness, woe, misery, and imperfection upon and in man;
and in this seed Christ is all nations blessed and elected;
and out of it is the curse and reprobation.
And out of this seed are all the false religions, false ways, false worships,
and false churches, or bodies without heads, like so many monsters,
which the seed of the serpent hath brought forth since the apostles`' days,
and then they have made them heads, out of their bodies, or churches,
and when one head is fallen off, then another they make,
and set it upon their body or church, having lost and gone from the true head, Christ.

And sometimes the members do fall out about making a head for their body,
so that the members do destroy one another about it.
Now this monstrous body is brought in by this evil
seed in such as are gone from the light,
grace, truth, power, and spirit, that cometh from Christ, the heavenly head,
in whom dwelleth the fulness of divinity.
And they are never like to come to the true head, Christ, but by coming to the light,
grace, truth, power, faith, and spirit of Jesus, which cometh from him,
and turneth to him again, (the head,) and so to hold him their head,
by which all the members are coupled together by joints and bands,
which do receive their nourishment from him their head,
who doth supply every member with life everlasting from him that is alive,
and liveth forevermore.

And since such have gone from the light, grace, truth, spirit,
and power of Jesus in this night of apostacy,
they have gone from that which cometh from the head, Christ, which should join to him.
And therefore in this night of apostacy there have
been many bodies without the true head,
which have made so many heads, and set them upon their bodies, and when they are gone,
they do make more; and the beast, dragon, wolves, and false worships or bodies of people,
without the true head, Christ, being out of the grace, truth, light, power, faith,
and spirit which the apostles were in,
they have brought forth so many monstrous bodies without heads,
till they have made heads for them; and when one is gone, they do make another.
And therefore all must come to the grace, truth, power, spirit,
and faith that cometh from Jesus, if that they do come to him from whence it cometh,
and so hold him their head, Christ, which head all things were made by,
who is first and last, the beginning and ending.
Hallelujah.

And my desires are, that all may be in their services for Christ, men and women,
in his grace, truth, light, power, and spirit,
that from him they may all have their penny,
who doth reward every man and woman according to their works,
and not stand idle chaffering in the marketplace.

So with my love in the Lord, the Creator of all, and in the Lord Jesus Christ,
by whom was all, who is over all, the first and last,
a living rock and foundation for all the living to build upon, that are quickened by him,
and do believe in his light, which is the life in Christ, the word,
by whom all things were made; and so are grafted into Christ, the living tree,
that never withereth;
and so from him the green tree every graft doth receive its nourishment,
that is grafted into him; and so the living root doth bear every living branch,
+++[+++and nourishes it, that it may bring forth fruit to the praise of God over all,
blessed forever.

And this is the tree whose leaf never fadeth, nor fruit faileth;
but its fruit feedeth all the living, and the leaves thereof heal the nations.
And this tree stands in the midst of God`'s garden, who saith,
in the midst of thy church will I sing praise, which are living stones,
a spiritual household of faith, elect and precious, the church of the living God,
written in heaven; so holiness becomes the house of the Lord.
And therefore the Lord doth require more from Friends than all other people,
because he hath given more to them;
and so all people do expect more from Friends than all other people,
in answering that of God in them all in truth and in righteousness,
and holiness and godliness; for ye are the lights of the world,
and the salt of the earth to season it.
So all must glorify the Lord God in their lives and conversations, with their bodies,
spirits, and souls, which are Christ`'s,
who has bought them and cleansed them with his blood and the pure water of his word,
who makes them sanctified vessels of his mercy for his glory;
therefore none must dishonour the Lord.

And therefore my desires are, that you may all be valiant tor the truth upon the earth;
and keep up all your men and women`'s meetings in the Lord`'s power, the gospel,
which hath brought life and immortality to light,
and it will preserve you in life and immortality over him that hath darkened you;
and in this all will see their works and services for the Lord God,
and his son Christ Jesus, in that which hath brought life and immortality to light;
in which gospel is an everlasting perfect fellowship and order,
which will stand when all others are gone; all the saints that do enjoy this,
cannot but praise the Lord, and sing praises to him forever and ever.
Amen.

The apostle saith, "`If any man be in Christ he is a new creature;
old things are passed away, behold all things are become new.`" 2 Cor. 5:17.

So they that are in Christ are new creatures;
and they that are in old Adam are old creatures; and are in their old things, old ways,
old worships, and old religions, and have the old garments, and the old bottles,
that hold the old wine, and cannot endure the new; and have the old, rusty,
moth-eaten treasure.
And they that are in Christ, the heavenly and spiritual second Adam,
who maketh all things new, are new creatures, and spiritual men, and are heavenly-minded,
and are new bottles, that hold the new wine and the new heavenly treasure,
and have the new clothing, the fine linen, the righteousness of Christ,
and are the new and living way, over all the dead ways.
And they are in the new worship, which Christ set up above six hundred years ago,
which is in the spirit and in the truth;
in which holy spirit and holy truth the holy God is worshipped:
and this was new to both Jews and Gentiles, and is new to all the apostate christians,
who are not in the holy spirit and truth that the apostles were in.
And this new creature in Christ hath a new religion, which is pure and undefiled,
and keepeth from the spots of the world;
and this religion is new to the Jews and Gentiles,
and all the apostatized christians that plead for a body of death and sin to the grave,
and a purgatory when they are dead.
And they that be in Christ are new creatures, and they have a new head,
who is the head of all things, the first-born of every creature,
and the first-begotten from the dead, who is alive, and liveth forevermore,
who bruiseth the serpent`'s head, who hath made things old,
but Christ maketh all things new; and they that be in him, are new creatures;
and they that be out of Christ, are the old creatures in old Adam;
and these old creatures are doting about their old things, and their old bottles,
old wine, old garments, and are doting about their old ways, old religions,
and old worships, and persecuting one another with their old carnal weapons,
these old creatures, which dote about their old worships, religions, and ways;
so that one old creature falleth out with another old creature,
so that these old doting creatures in old Adam, out of Christ the second Adam,
do wrestle with flesh and blood about their old ways, religions, and worships:
and these old doting creatures (which be out of Christ the
saviour) do destroy one another about their old ways,
worships, religions, and churches.
And these old creatures, that be out of Christ the head,
are monstrous bodies without a head, till that they have made one,
and then the old creatures set it upon their body;
which head (as they do think) doth pardon their sins;
and when this their head is fallen off their body, then they do make another,
and set it on their old creature`'s body.
But they that are in Christ, are new creatures, and Christ is their head,
who is their redeemer, sanctifier, and saviour, who is alive, and liveth forevermore;
and walk in Christ, the second Adam, who is heavenly and spiritual.
And the old creatures, out of Christ, their walk is in old Adam,
who are natural and carnal, and so are their weapons and armour,
that they defend these old ways, church, religion, and worship with,
they are carnal (and not spiritual) by which they kill one another;
and the old creatures do study or dote which way they may destroy or imprison,
persecute or banish, spoil or torture the righteous or new creatures in Christ.
And they that are in Christ are new creatures, their weapons and armour are spiritual,
and they do not wrestle with flesh and blood,
but spiritual wickedness and rulers of darkness in high places,
and bring down imaginations and high thoughts,
as Christ (whom those new creatures are in) teacheth them, who saith,
that "`he came not to destroy men`'s lives,
but to save them;`" and rebuked such as would have had men`'s lives destroyed,
and told them, that "`they did not know what spirit they were of.`"
So it is clear, that the old creatures, that are out of Christ,
(who destroy men`'s lives about their old ways, churches, religions,
and their old worships,) do not know what spirit they are of;
and although they do not know what spirit they are of,
whether it be a good spirit or a bad one, yet people must conform to that way, religion,
worship, and church that this old creature, that is out of Christ, hath set up,
or else he will persecute them or, destroy their lives, though Christ saith,
"`they do not know what spirit they are of.`"
And is not this hard, to conform to that which the old creatures have made and set up,
which do not know their own spirits, nor what spirit they are of?
And therefore, were not those doctrines, ordinances, traditions,
and rudiments of the world the old creatures (who
are in old Adam) which they did and do dote after,
which the new creatures in Christ Jesus, the second Adam, were not to taste, touch,
nor handle, for they did perish with the using?
And are not all the will-worships, and the beast`'s and the dragon`'s worships,
of the old creatures, that are out of Christ,
bearing the mark of the beast in their hand or forehead?
And they that are in Christ, who are new creatures,
have their Father`'s mark or name in their foreheads, and worship the holy,
pure and living God in spirit and in truth.
And it was the old creatures that made images and idols; and such make them now,
and worship them; but they that are in Christ, are new creatures,
and are renewed up into the image of God, and worship him in his holy spirit and truth,
that liveth forever.
Amen.

And these cannot touch, taste, nor handle the old creature`'s images, idols, doctrines,
ordinances, traditions or rudiments of the world, which are the old creature`'s,
in old Adam, which doth touch, taste, and handle them: but the new creature cannot,
who is in Christ, the express image of the Father;
and he maketh his new creatures like himself.
Moses appointed servants for God in the law or Old Testament;
but Christ made sons in the New Testament; for "`as many as received Christ,
he gave them power to become the sons of God.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore in Lancashire, the 30th of the 11th month, 1678.

[.centered]
=== Epistle 344.

[.blurb]
==== To Friends in America, concerning their Negroes, and Indians.

All Friends, everywhere, that have Indians or blacks,
you are to preach the gospel to them, and other servants,
if you be true christians for the gospel of salvation
was to be preached to every creature under heaven;
Christ commands it to his disciples, "`Go and teach all nations,
baptizing them into the name of the Father, son, and holy ghost.`"
And this is the one baptism with the spirit into one body,
which plunges down sin and corruption,
which hath gotten up by disobedience and transgression.
For all have been plunged into sin and death from the life, for all died in Adam,
then they have been all subjected by the evil spirit,
which hath led them out of the truth into the evil;
and therefore they must all be baptized into the death of Christ, and put on Christ,
if they have life.

And also, you must preach the grace of God to all blacks and Indians,
which grace brings salvation, that hath appeared unto all men,
to teach and instruct them to live godly, righteously, and soberly:
which grace of God is sufficient to teach and establish all true christians,
that they may appear before the throne of grace.

And also, you must teach and instruct blacks and Indians, and others,
how that God doth pour out his spirit upon all flesh in these days of the new covenant,
and new testament; and that none of them must quench the motions of his spirit,
nor grieve it, nor vex it; nor rebel against it, nor err from it, nor resist it;
but be led by his good spirit to instruct them;
and with which they may profit in the things of God;
neither must they turn from his grace into wantonness,
nor walk despitefully against the spirit of grace,
for it will teach them to live soberly, godly, and righteously, and season their words.

And also, you must instruct and teach your Indians and negroes, and all others,
how that Christ, by the grace of God, tasted death for every man,
and gave himself a ransom for all men, to be testified in due time,
and is the propitiation not for the sins of christians only,
but for the sins of the whole world: and how,
that he doth enlighten every man that cometh into the world, with his true light,
which is the life in Christ, by whom the world was made.

And Christ, who is the light of the world, saith, "`Believe in the light,
that ye may become children of the light.`"
And they that do evil,
and hate the light (which is the life in Christ) and will not come to the light,
because it will reprove them, and love the darkness more than the light;
this light is their condemnation.
And so, all must be turned from darkness to light, to believe in the light;
and from the power of Satan to God; and, if they do not believe, they will be reproved,
condemned, and judged by Christ, who hath all power in heaven and in earth,
given unto him, who will judge both the quick and the dead,
and reward every man according to his works, whether they be good or evil.

And therefore you are to open the promises of God to the ignorant,
and how God would give Christ a covenant, a light to the Gentiles, the heathen,
and a new covenant to the house of Israel, and the house of Judah,
and that he is God`'s salvation to the ends of the earth;
and how that the earth shall be covered with the knowledge of the Lord,
as the waters cover the sea;
so that the glorious knowledge of the Lord should cover the earth.

And the Lord said, "`He knew that Abraham would teach and instruct his family,
that they should learn to keep his laws and statutes after
he was gone;`" and Abraham did circumcise all his males,
yea, them that he had bought with his money of any stranger.
Now who are of faith, and walks in the steps of faithful Abraham,
do preach up and instruct all their families in the circumcision of the spirit,
that they might be circumcised with the spirit, which puts off the body of death,
and the sins of the flesh, that is come up in man and woman by transgression;
so that in the spirit they may serve and worship the true and living God;
and so that ye all may come to enjoy the presence of the Lord in your families,
and improve your talents that Christ hath given unto you; for David saith,
that saw Christ in his new covenant, "`Let all nations praise the Lord;`" and again,
"`All that have breath praise the Lord;`" again,
"`Let the poor and needy praise thy name.
And let all people praise thee, O God.
And O ye servants of the Lord, praise the Lord; for the Lord is good to all,
and his tender mercies are over all his works.
And all thy works shall praise thee, O Lord; and thy saints shall bless thee,
they shall speak of thy glory and of thy kingdom, and talk of thy power.`"
For the Lord saith, "`From the rising of the sun to the going down of the same,
my name shall be great among the Gentiles.
And in every place incense shall be offered unto my name; and a pure offering;
for my name shall be great among the heathen, saith the Lord of hosts.`"
And this heavenly incense, and offering in every place,
is the spiritual offering in the new covenant;
for the Jews were to offer but in one place, in the temple in the old covenant,
but in the new covenant their offering is in the holy temple of their hearts,
in the spirit, with which they offer the pure, and holy, and acceptable sacrifice to God;
with that spirit which God hath given them,
they have a living sense of God their creator, and Father of all their mercies,
who hath made them, and hath made all things for them,
and redeems them by his son Christ Jesus, to whom be praise, and glory, and honour,
and thanks forevermore.

So let all bow at the name of Jesus, to his power, and light, and spirit,
for they have bowed to the power of darkness, that foul and unclean spirit,
who is out of truth, and in whom there is no truth.
And therefore now all are to bow at the name of Jesus;
for there is no salvation in any other, name under heaven, but in the name of Jesus,
whose name is above every name under the whole heaven,
who is the first born of every creature, and the first begotten from the dead,
whom God now speaks to his people by, his son; and all are to hear him,
the great prophet; and every tongue is to confess to Christ Jesus,
to the glory of God the Father, who is the first and last,
who bruises the serpent`'s head.
And so through Christ Jesus man and woman comes again to God.
All blessings and praises be to the Lord God, through Jesus Christ, forever and evermore.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 10th month, 1679,

[.centered]
=== Epistle 345.

Dear Friends everywhere, that have received the truth as it is in Jesus,
which is holy and pure, and brings to live in him that is pure and holy.
The truth is peaceable, and a peaceable habitation;
and the truth is sufficient and able to make you
free from him that abode not in the truth,
and in whom there is no truth.
And all that do not live and walk in the peaceable truth,
follow him that is out of the truth, into strifes, and vain janglings and disputings,
like men of corrupt minds, destitute of the truth.
And now the grace and truth that comes by Jesus Christ,
is that which all people should be under in this new covenant of light, and life,
and grace, and truth; as the law came by Moses in the old covenant,
and the Jews were to be under the law.
But the true christians who have received the grace
and truth come to be under this grace`'s teaching,
leading, and establishing;
by which grace and truth they are united and joined to Jesus Christ,
from whence it comes,
And this grace and truth is able and sufficient to
make you free from him that is out of the truth,
and to come to have a peaceable habitation in Christ Jesus,
their eternal rest and sabbath.
For Christ Jesus saith to his believers and followers, "`In me ye have peace,
but in the world ye have trouble;`" and the trouble is in the world of wickedness.
And therefore God`'s people are not to love the world, nor the things of the world;
for the love of the world is enmity to God.

And therefore, feel God`'s love shed abroad in all your hearts, through Christ Jesus,
to carry all your hearts and your minds above the love of the world;
and this love is that which will preserve you in the excellent way of bearing all things;
and the love of God fulfils the law.

And the fruits of the pure holy spirit of the God of truth is love,
which is a peaceable spirit: but the foul, unclean spirit, that is out of the truth,
is a ravenous, unquiet, unpeaceable spirit.
And the faith that Jesus Christ is the author and finisher of, works by love;
and the spirit of faith is a peaceable spirit;
which faith gives the victory over the unpeaceable, unruly, ravenous spirit;
and by which faith you have the inheritance.

And the glorious gospel of Christ Jesus, which is the power of God, the gospel of peace,
which is over the power of darkness, and was before it was,
and it will be when it is gone;
and in this gospel all the heirs of it have an everlasting unity,
and an everlasting glorious fellowship in the glorious gospel of peace, yea, a glorious,
peaceable fellowship and an access to God.

And the wisdom of God from above is gentle and peaceable,
and justifies and preserves all her children above the unpeaceable wisdom that is below;
and this peaceable wisdom preserves above all the unruly spirits,
and vain talkers and janglers, such as talk of the wisdom of God, but live not in it,
but in the wisdom of the world.

And such as talk of the gospel of Christ, the power of God, but live not in it,
but do live in the power of Satan, the enemy and adversary, and the devil,
the destroying power and spirit; and such have no comfort of the scriptures,
nor of the things of God, nor of the grace, nor of the truth, nor of the wisdom of God,
nor of faith, nor light, though they may talk of all these things,
while they follow that unruly, foul, unpeaceable spirit, that abode not in the truth,
(in whom there is no truth,) and where there is no truth there is confusion and disorder.
Now the God of truth is a God of order, from whom you have grace, truth, and faith,
which is his gift, and his spirit, and gospel, and wisdom,
that you may all live in the order of it, and as it orders you.
For God is a God of order, and his order is known in his light, grace, and truth,
and spirit, and his gospel, the power of God, and in his wisdom.
And all his children and people should live in the order of his light, spirit,
and gospel, and wisdom, and delight in the order of it.

And all you that know God, and Jesus Christ, which is eternal life;
then in this eternal life you do know,that the God of truth is a God of order,
and you love his order, in his light, and life, and grace, and truth, in his gospel,
and in his spirit, and in his heavenly pure wisdom,
by which all his children are justified.

And in his truth, that makes free from him that abode not in the truth,
(in whom there is no truth) that all his children should walk in the order of truth,
which hath made them free,
who are born again of the incorruptible seed by the word of God, that lives, and abides,
and endures forever.
And so feeds of the milk of this immortal word,
and so are of an incorruptible generation, which is above the corruptible;
and here is the hidden man of the heart, that is incorruptible, known,
that hath an everlasting fellowship, and hath an incorruptible crown,
and is an heir of an incorruptible kingdom.

And now the God of this world, (and his followers,) that abode not in the truth,
in whom there is no truth, cannot endure to hear talk of the order of truth,
which is in the light, and life, and in the gospel,
and in the wisdom of the God of truth.
For the world is full of disorder and confusion; but the living, eternal,
immortal God of truth is a God of order, and not of confusion,
who hath sent his son to destroy the devil and his works.
Blessings and praises, with all glory and thanks, be unto him, who hath all power, might,
majesty, and dominion, now, henceforth, and forever.
Amen.

[.signed-section-signature]
G+++.+++ F.
