== Epistles 346 &#8212; 351

[.centered]
=== Epistle 346.

[.salutation]
Dear friends,

All live the life of the true christians, and not the life of old Adam,
that went from God`'s command and voice; nor like the Jews,
and such as have got the name of christians, that say,
there is no hearing of God and Christ`'s voice now, which are out of the life, power,
and spirit, grace, and truth, and image of God, that the true christians were in,
and Adam and Eve before they fell; so that none can live the life of the true christians,
and the holy prophets and apostles, except they are in the same power and spirit,
grace and truth, and faith and image that they were in,
which is a life above the world and its God, in whom there is no truth, no life, light,
nor power of the living God abiding in them.
And therefore, before any can live the life of the saints,
they must bow to the name of Jesus, their saviour, in his light, grace, and truth,
and power, and spirit, which cometh from him,
who submitted himself to the shameful death of the cross,
and destroyed death and his power, who had no sin, nor guile in his mouth,
and is risen again for our justification, and so hath tasted death for every man,
and given himself a ransom for all, that all should now bow at his name, Jesus,
a saviour; and so to his power and authority bow,
who hath all power in heaven and earth given to him.
So all men have bowed under death and sin by transgression.
And Christ hath submitted to the cross and death for them,
and hath borne their stripes for sin and iniquity, who had no sin, neither knew any,
to bring us out of death and sin.
Therefore, every one must bow at the name of Jesus,
(as before,) whatsoever they do in word or deed, it must be done in the name of Jesus;
and before that they can confess to Jesus Christ, to the glory of God the Father,
they must all bow at the name of Jesus, and bow to his grace, and truth, light, spirit,
and power that cometh by Jesus, which they know; him the fountain,
the rock and foundation to build upon,
who brings out of death and darkness into light and life,
and a kingdom and a world that is everlasting;
and there to have food and clothing that is everlasting.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 347.

[.salutation]
Dear friends,

With my love to you in the holy peaceable truth that never changes, nor admits of evil,
but makes all free that receive it, and that walk in it,
and is over all the clouds without rain, and wells without water,
and trees without fruit.
And from the truth floweth justice, equity, righteousness, and godliness, mercy,
and tenderness, that brings a man`'s heart, mind, soul,
and spirit to the infinite and incomprehensible God,
and from it a love flows to all the universal creation,
and would have all to come to the knowledge of the truth;
and it bends every one to their utmost ability to serve God and his truth,
and to spread it abroad, and it brings their minds out of the earth,
which makes them brittle, and changeable, and uncertain; for it doth not change,
neither doth it touch with that which does change.
As to unity, it makes all like itself, that do obey it.
Universal, to live out of narrowness and self, and deny it.
So it brings all into oneness, and answereth the good principle of God in all people,
and brings into humility, and the fear of the Lord, which is the beginning of his wisdom;
and it brings all to have a care of God`'s glory and his honour;
and watches over all the professors of it for their good, to keep within its bounds,
and walk within its order; which he that is out of truth, leads into all disorder,
in whom there is no truth; and the truth makes all its children free from him,
and in it to reign over him.
Thanks, glory, and honour to the Lord God of truth over all forever.
Amen.

The Lord, who is the God of all peace and order,
alone protects and preserves his people with his eternal power;
for the devil`'s power is not eternal, it had a beginning, and must have an ending;
for the eternal power limits that devourer and destroyer.
And therefore, friends, patience must be exercised in the truth;
and keep to the word of patience, which word was before the world was,
and abides and endures forever;
and it will keep Friends over and out of all the snares of the world,
and its temptations.

So with my love in the seed of life, that reigns over all,
and in it the Lord God Almighty preserve and keep you all to his glory.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 348.

[.blurb]
==== An epistle to be read amongst Friends.

[.salutation]
Friends,

You that are believers in the light, which is the life in Christ,
and are grafted into him who is ascended far above all principalities, powers, thrones,
and dominions, by whom all things were made and created,
all the children in the new covenant do gather together in the name of Christ Jesus,
whose name is above every name under the whole heaven,
and in whose name they have salvation, and not by any other name under the whole heaven.
And at this name must every knee bow, and every tongue confess Christ Jesus,
to the glory of God the Father; and they that have bowed their knee to the name of Jesus,
and do confess him to the glory of God the Father,
cannot gather in any other name under heaven, below the name of Jesus; but,
gather in the name of Jesus, which is above every name under heaven,
in whom they have salvation, and so cannot gather in any name below Christ; for,
they do know that they have not any salvation in whatsoever
name that they do gather together in below the name of Jesus.
And being gathered in the name of Jesus, he is in the midst of them,
the Prince of life and peace, and captain of salvation,
and a prophet to open the book of conscience, and the book of the law, and prophets,
and gospel, and his book of life to them, and a bishop to oversee them,
and a heavenly shepherd to feed them in his heavenly pasture of life,
and a heavenly King to rule in their hearts, and in his glorious kingdom,
amongst them that are born again;
and that seeth and entereth into his everlasting kingdom of righteousness, peace,
and joy in the holy ghost.
And all these children in the kingdom, and in the new covenant of grace, light, and life,
cannot feed of any bread for their immortal souls that is made by man,
which he hath leavened with the sour leaven;
for that sour leavened bread will make their hearts to burn,
and the Jews were not to keep their feasts with leavened bread in the old covenant;
then much more the Jews in the spirit, in the new covenant,
who have their bread from heaven, their unleavened bread,
who in the new covenant do keep their feast with unleavened bread from heaven,
and cannot feed their souls with any bread, but that which cometh down from heaven.
And this bread from heaven giveth life to the soul,
and is the staff of their heavenly life; this heavenly bread,
as the outward bread is the staff of the natural life,
in this world that must have an end,
but the bread from heaven is the heavenly staff of life,
that doth nourish up into a heavenly life, and a world,
and a kingdom that is without end.
And such as feed on this heavenly bread cannot feed their
souls with any bread below that which comes from heaven,
for it doth not give them life.
So that they can neither touch, taste, nor handle that which is below, which perisheth;
for the bread of life from heaven doth not perish, but giveth life eternal;
and this bread is sure, and they that feed upon it shall hunger no more.
So all eyes are to look up to heaven for this bread of life, which giveth them life;
and not below heaven; for neither are they to follow them that cry, "`Lo, it is here,
and lo, there;`" or to drink of their cup that are whored from the spirit of God,
nor to eat of their leavened bread; for they that do believe in the light,
which is the life in Christ, are grafted into him the true vine.
So the believers do feel a living spring springing up in them to eternal life,
from the fountain from whence it cometh.
And so here all the true believers have the upper and the nether springs in themselves;
and such may drink freely and eat freely of the bread and water of life,
and do hunger and thirst no more, but eat and drink that which is eternal,
which nourisheth them up to eternal life, and so bear heavenly spiritual fruits,
to the praise of the eternal God;
which plants he hath watered by his upper and nether springs, which trees or plants,
their fruits are unto holiness, and their end is everlasting life.
So none of the children of the new covenant need go to the world for bread or water,
to give them life everlasting, to keep them from the world`'s storms;
or weapons to defend their church or worship, for they have them from heaven,
and heavenly bread and water, and spiritual weapons and armour,
and the righteousness of Christ, the fine linen, their clothing.
Glory to the Lord forever, who makes all his spiritually rich,
and to be lenders and not borrowers, and givers and not receivers,
who is more blessed than the receiver.

And the Jews in the old covenant were to wash their clothes,
and to sanctify themselves when they did appear before the Lord,
and so the children of God in the new covenant of life, light, and grace,
who do appear before the Lord, are to be washed and cleansed, and sanctified,
and to put on the righteousness of Christ, their fine linen that never will wax old;
and so to put off all the old Adam`'s garments,
that he hath covered himself and his sons and daughters with in the fall and transgression,
which will wax old and rot;
but that which God and Christ doth put on and clothe his saints withal, is everlasting.
So man`'s righteousness and his filthy rags must be put off;
and they must come into the righteousness of Christ, and put it on,
which doth exceed the righteousness of the law, if they do enter into the kingdom of God,
which doth stand in righteousness, and peace, and joy in the holy ghost.

Now in the Old Testament it is said,
"`The priests`' lips are to preserve the people`'s
knowledge:`" but the New Testament saith,
"`that Christ is the treasure of wisdom and knowledge.`"
The Old Testament saith, "`that you must offer your sheep, goats, bulls, and heifers,
and other creatures, which God commanded by the law in the Old Testament,
for your sins and cleansing:`" but the New Testament saith,
that "`Christ is offered up once for all:`" and the Old Testament saith,
"`that the blood of bulls and other creatures cleanseth
from sin:`" but the New Testament saith,
"`that Christ`'s blood cleanseth from all sin.`"
And in the Old Testament it is said, "`You must carry your offerings, and firstfruits,
and tithe, to the store-house:`" but the New Testament saith, "`Freely you have received,
freely give;`" and forbiddeth bag or staff.
And in the Old Testament the priest was to light
the candles and lamps in the tabernacle and temple,
and to circumcise the men children: but the New Testament saith,
"`Christ doth enlighten every man that cometh into the world with
his heavenly light:`" which is the life in Christ the word;
and the spirit of man is the candle of the Lord:
so he doth enlighten the candle and lamp in the tabernacle, and saith,
"`Believe in the light,
that ye may become children of the light;`" and Christ
doth minister the circumcision in the spirit,
that putteth off the body of the sins of the flesh,
that came upon man and woman by transgression.
So that the children are the circumcision of the spirit in the new testament,
and not of the flesh and letter, as they were in the old testament.
And in the Old Testament it is said, that "`the priests put the Testament, and the law,
and the pot of manna into the ark,
in the tabernacle and temple:`" but in the New Testament,
God poureth out of his spirit upon all flesh,
and the holy ghost proceedeth from the Father and the son into the hearts of his people,
to lead them into all truth, and reproveth the world of sin;
and the bread of life that they have from Christ, is in their arks and hearts,
or in their temples; and God doth write his law in the hearts and minds of his people.
So in the new testament they have the law written in the heart and mind,
and the old they had in the letter and tables of stone;
and in the new they have the testament and testimony,
the spirit of Christ in their hearts, and the heavenly, unleavened bread in their hearts,
which they do keep the everlasting feast with.
And in the old testament, the clean and circumcised outwardly did eat of the passover,
the lamb without blemish: but in the new testament,
the clean and circumcised in heart do eat of the passover, Christ,
the heavenly bread and flesh,
and so do keep the feast of their passover in the new testament.
And the old testament had the outward temple and tabernacle, and outward lights:
but in the new testament, the saints`' bodies are the temples and tabernacles of God,
and his light doth shine in their hearts, to give them the knowledge of the glory of God,
in the face of Jesus Christ.
And in the old testament it is said, "`Do this and live;`" and the new saith,
"`Believe in the light (Christ) and be saved.`"
And the old testament saith, "`Thou shalt swear,
and perform thy oaths to the Lord:`" but Christ saith in the new, "`Swear not at all.`"
And the old testament saith, "`Thou shalt not kill,
nor commit adultery:`" but Christ in the new saith,
"`Thou shalt not be angry without a cause, and thou shalt not lust after a woman.`"
And the old testament saith, "`Thou shalt stand up and curse:`" but the new saith,
"`Bless, and curse not.`"
The old testament saith, "`Thou shalt hate thine enemy:`" but the new saith,
"`Thou shalt love thy enemies,
and do good to them that hate thee and despitefully use thee.`"
So the new covenant and testament is not according to the old.
And in many things besides these,
it might be shown how one doth exceed the other in glory.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 349.

[.blurb]
==== To all the men and women`'s meetings everywhere.

All the faithful men and women are to be as Abraham and Sarah; Abraham,
the father of the faithful; and Sarah, a mother in Israel, to give suck,
and to nourish up the seed, the heir of the promise.
Likewise, to be as Adam and Eve, before they fell, meet-helps, in the image of God,
and in the power of God, with which they were to subdue the earth:
in which power and image of God, they were not only to subdue the earth,
but subdue unrighteousness and all ungodliness,
and that which they know doth dishonour God.

And likewise all the faithful women are to be as Dorcas, a disciple of Christ Jesus,
that their good works of the spirit and faith may follow them:
and also they are to be as Phebe, who was a minister of the church at Cenchrea;
and she was such a faithful trusty minister,
that the apostle sent his epistle by her to Rome, from Corinth,
with a recommendation of her.
And also all the faithful men and women are to be as Aquilla and Priscilla,
who were the apostles`' fellow-helpers in Christ Jesus, and had a church in their house,
and were instructers concerning the things of God, and Christ Jesus,
(in his new testament and new covenant,) and of his kingdom:
and likewise to be as Mary Magdalene, and Joanna, and Mary, the mother of James,
and other women that were with those women,
who first preached and declared to the apostles the resurrection of Jesus Christ.
And Christ said unto those women,
"`Go and tell my disciples that I am risen from the dead;`"
so these women were the first messengers of the glad tidings. Matt. 28. Luke 24. Mark 16.
And these tidings did astonish the apostles at first;
for they said, "`Certain women of our company,
(which were of the disciples,) made us astonished, saying,
that Jesus was risen from the dead;`" this two of
his disciples said when they were talking with Christ,
but they did not perceive it till he opened their eyes,
as in Luke 24. So the women continued in their firm belief;
and then afterwards the apostles came to believe also.
And therefore it is good for every one to have a sense of the resurrection of Christ,
and not seek him below; but seek him above, for he is risen from the dead, and lives,
and sits at the right hand of the living God.
And also all the faithful are to be as Miriam the prophetess, to encourage the church,
and praise God.
And also to be as Huldah the prophetess, who instructed the king, his princes,
and priests, in the law of God, and the old covenant.
So they should be much more diligent to teach and instruct in the new covenant,
and testament, which doth exceed the old in its glory.
And also to be as Anna the prophetess, an ancient woman of eighty-four years old;
and she gave thanks,
and spake of Christ to all them that looked for redemption in Jerusalem;
and so here was a general and a public preaching of Christ Jesus.
And also to be as Hannah, in the Old Testament,
who consecrated her son Samuel unto the Lord; and the Lord accepted her prayers, tears,
and offerings.
So she had not a mind to let him run wild.
And likewise as Deborah, who was a prophetess in the old covenant, and a judge in Israel.
What victories, with outward weapons, the Lord did give her,
and how she praised the Lord, which was by faith, in the time of the old covenant.
But in the time of the new covenant the true believers wrestle not with flesh and blood,
but are all to be diligent in the spiritual judgment and warfare in the spiritual Israel.

And the apostle writes to Titus, how he had left him in Crete,
that "`he should set in order the things that were wanting,
and ordain elders in every city, as he had appointed him.`"
And after he had spoken many things to Titus concerning overseers and teachers,
that they must be blameless; he saith, "`that the aged men must be sober, grave,
temperate, sound in faith, in charity, and in patience.
And the aged women likewise, that "`they be in behaviour, as becomes holiness,
not false accusers, etc. but to be teachers of good things;
and that they teach the younger women to be sober, to love their husbands,
and to love their children, and to be chaste, keepers at home, good, obedient,
etc. that the word of God be not blasphemed.`"
And likewise Titus was to exhort the young men to be sober-minded.
And here you may see the apostle, who did forbid one sort of women to be teachers,
who were usurpers of authority, which both the law and the gospel forbids; yet the law,
and Christ, and the apostles in the gospel,
encouraged the honourable women to preach and to teach.
For Christ sent the faithful women to declare and preach his resurrection to his disciples;
and likewise the apostle encouraged the aged, and honourable,
and faithful women to prophesy and teach, and to be teachers of good things, as before.
That is his charge to them in general.
Then he comes to particulars, charging them,
that "`they should teach the young women to be sober and discreet, chaste, and good,
to love their husbands, and their children, that the word of God be not blasphemed.`"
So these were to be as mothers to the younger women,
and were public women in their public services, and charge that was committed to them.
And a bishop, and an elder, or a deacon, was to order and rule well his own house,
and to have his children in subjection, with all gravity.
For if a man know not how to rule his own house,
how shall he take care of the church of God?
So every man and woman is to teach, instruct, and order their own children and families,
as the Jews did in the old covenant;
then much more they should train them up in the new covenant, which exceeds the old;
so that in all things they might give thanks and praises to God,
that in all things the Lord might be glorified in all their families.
So all christian families are concerned in these particular services,
before they come to the general service, (to wit,) to be overseers and ministers,
faithful men as fathers, and faithful women as mothers, and teachers of good things;
and the young men and women as brethren and sisters in purity.
And so let none spoil their families with bad lives, and unruly tongues,
with letting the poison of asps be under their tongue,
by which they spoil and corrupt their families;
which begets into a loose and bad language; but that is to be bridled by the word of God;
"`for a soft tongue breaketh the bone,`" the tongue of the just is as choice silver,
and the tongue of the just is health, and useth knowledge aright,
and a wholesome tongue is a tree of life; and who keepeth his mouth and his tongue,
keepeth his soul from trouble.`"
And after that Solomon had spoken of a virtuous woman, he saith,
"`In her tongue is the law of kindness, and her children rise up, and call her blessed;
and her husband also praises her.`"
He that hath an ear to hear, let him hear.
And therefore all are to keep in this law of kindness,
and there your candle doth not go out by night, and your virtue will flow;
for "`the hoary head is a crown of glory,
if it be found in the way of righteousness;`" and,
"`better is he that rules over his own spirit, than he that takes a city;
for he that hath no rule over his own spirit is like a city that is broken down,
without walls;`" then the security and strength are gone.
And therefore let every one keep his own little city with the spirit and power of God,
by which you have power over your own spirits;
and then the power of God is your strength, and keeps you safe in it,
that be led by the spirit of God.

And so that all men and women may exercise their talent,
their gift that God hath given them,
in the "`true light which lighteth every man that
cometh into the world;`" that is the light in Christ,
that they may become children of the light, and grafted into Christ,
and walk as children of the light and of the day.
And that all may profit in the manifestation of the spirit that God hath given them;
and be led by the spirit,
that you all may be the sons and daughters of God in this day of his new covenant,
and new testament, wherein God poureth forth of his spirit upon all flesh,
which none are to grieve, vex, nor quench, nor rebel against, but obey it.
And "`the grace of God that brings salvation hath
appeared unto all men,`" to teach them to live godly,
righteously, and soberly, and to deny ungodliness and unrighteousness.
And therefore all are to be faithful stewards of this grace of God, which teaches them,
and brings them their salvation.
For the apostle saith, "`As every one hath received the gift,
even so minister the same one to another, as good stewards of the manifold grace of God,
that the God of all grace, and Christ by whom it comes,
may be glorified in all his people,
who gives unto them freely the spiritual and heavenly gifts.`"
And the gospel of peace and glad tidings,
God and Christ hath sent to be preached to every creature under heaven.
And all you that have received it,
by which life and immortality are brought to light in you,
by which you see over him that hath darkened you; by the everlasting gospel,
the power of God, and are come to be heirs of this everlasting gospel, the power of God,
so you are heirs of the everlasting order of the gospel;
for the power of God is the order and authority of all your meetings.
This everlasting gospel, the power of God, is an unlimited order;
and this glorious order of the gospel, the power of God, is beyond the order of Aaron,
and beyond all the orders of the heathen.
And the power of God cannot be limited, though it may limit that which is contrary to it,
and out of the truth.
So our order and government are of Christ, and his gospel, and in his light,
and holy spirit, and we are heirs of it, being heirs of Christ,
and grafted into him by belief;
and all his sons and daughters do know his glorious liberty, and their rest in him.
For we have received the spirit of adoption, whereby we can cry Abba, Father;
for the spirit itself beareth witness with our spirits that we are the children of God;
and if children, then heirs of God, and joint heirs with Christ.

And now, friends, (as I said before,) train up all your children in the fear of God,
in this new covenant of light and grace, that they may know Christ,
who is their baptizer and circumciser;
and he sprinkles your consciences and hearts with his blood to cleanse you from all sin,
and the Lord writes his heavenly law in their hearts, that they may obey it and do it.
For, do not all people in their several false religions, ways, and sects, yea,
the very Turks and heathens, train up their children in their own ways?
And likewise,
did not the Jews train up their children in the old testament and old covenant of works;
which old testament and covenant Christ hath abolished,
and hath established the new covenant of light, life, and grace?
And therefore must not all the Jews in spirit, in this new testament,
train up their children in this new covenant of light, life, and grace?
Or else do they not bring themselves under condemnation?
For, doth not the beasts and the fowls teach their young to pick, suck,
and feed their young?
And will not the young ones cry after the old ones for their food?
All these things might teach people.
Now you having your food from Christ, and God your Father; yea, your bread, your milk,
your water, your wine, your honey, your fine linen, your clothing, your breath,
your life, your souls, and the image of God, which he made you in,
which man and woman hath lost by transgression,
but are to be renewed into again by Christ, your redeemer, and sanctifier,
and reconciler, and mediator, who makes your peace between you and God,
from whom you have your light, grace, and truth, who gives you his gospel, and faith,
and spirit, in whose name you have salvation,
and not by any other name under the whole heaven,
who is your heavenly spiritual rock and foundation;
and have not you all these things from above freely, and none of them from below?
And also your heavenly armour, and spiritual weapons,
in which you stand witnesses for God and Christ.
And cannot you train up all your children in the fear of God,
and tell them from whence you have all these good things,
that they may come to receive of all these good things
which you receive from the good God,
and Christ the treasure of wisdom and knowledge, that you may say,
the children of your children are the crown of your old men in the truth,
and the glory of their fathers in God; and that you may say,
your wives are as fruitful vines by the sides of your house,
and your children like olive plants round about your table.
Thus shall they be blessed, that fear the Lord; that you may say,
your sons are plants of God, growing up in their youth,
and that your daughters may be as corner-stones,
polished after the similitude of a palace; and that your garners are full,
and afford all manner of store, so that there is no complaining in your streets:
and "`happy is that people whose God is the Lord.`"

And now, my friends, if there happen any difference among Friends,
either with Friends or the world, let it be put to reference,
if it cannot be ended between themselves:
and all that are concerned to end any difference, let them have but one ear to one party,
and let them reserve the other ear to hear the other party;
so that they may judge impartially of matters, without affection or favour,
or respect of persons.
For you may see how the Jews in the old covenant did judge of things among themselves,
as long as they kept the law of God, and did not go to other nations, or to the heathens,
for them to judge of their matters;
and therefore the apostle reproves the Corinthians for that fault,
"`for going to law one with another before unbelievers,`" and told them,
that "`the saints should judge the word,`" yea, angels;
and then how much more might they judge of things appertaining to this life?
And therefore the apostle exhorted,
"`If then ye have judgment of things pertaining to this life,
set them to judge that are least esteemed in the church:`" and Christ saith,
"`If thy brother trespass against thee,
go and tell him his fault between him and thee alone; if he should hear thee,
thou hast gained thy brother: but if he will not hear thee,
then take with thee one or two more,
that in the mouth of two or three witnesses every word may be established:
and if he neglect to hear them, tell it to the church;
and if he neglect to hear the church, let him be unto thee as a heathen and a publican.
Verily I say unto you, whatsoever is bound on earth shall be bound in heaven;
and whatsoever ye shall loose on earth shall be loosed in heaven.`"
And farther Christ said, "`If two of you shall agree on earth,
as touching any thing that they shall ask,
it shall be done for them of my Father which is in heaven:
for where two or three are gathered together in my name, there am I in the midst of them.
Matt. 18.
And Christ saith, "`If thy brother trespass against thee, rebuke him;
and if he repent, forgive him: and if he trespass against thee seven times in a day,
and seven times, if he turn again, saying, I repent, thou shalt forgive him.`"
Luke 17. Here you may see what instructions Christ, (who is the King of kings,
and Lord of lords,) gives to his church, and much more, which is too large to write.
And they had elders in the old covenant then;
much more ought there to be elders in the new covenant, which are grown in the truth.
And they had the assemblies of the women in the law,
who were concerned in the things about the figures and shadows,
and they wrought about the holy things,
and they brought of their clean things to be offered; all which Christ, the Holy One,
hath abolished, and put an end to in the old covenant.
So, much more the believers in Christ, in the new testament, in the time of the gospel,
are to have their assemblies and meetings;
besides their instructing and looking into their own families,
whether they walk in the fear of God.
And then after, in the general service of the church of God, the aged men,
and aged women in the truth, are to be teachers of good things,
as the Lord shall order them with his spirit, to teach and instruct, exhort, admonish,
reprove, rebuke, with the holy spirit; for the least member hath an office,
and every believer in the light,
(which is the life in Christ,) is a member of Christ`'s church, and grafted into him;
and so he is the holy head of the church, and they are heirs of his order,
and of his government, of the increase of which there is no end,
in his eternal power and spirit.

And therefore,
all that deny the men and women`'s meetings that are established in the light, power,
and spirit of Christ, by which we are gathered together, he being in the midst of them,
they may as well deny Christ, as deny his heavenly order of his gospel,
and his heavenly spiritual government.

And all they that deny the men and women`'s meetings, in the new covenant,
in the restoration out of death and darkness, by Christ,
and in his gospel of light and life, they may as well deny the preaching of the gospel,
if people shall not come into the possession of that which is preached, and practise it.

For the faithful men and women that are restored into the image of God, by Christ Jesus,
as Adam and Eve were in before they fell, they were meet-helps in righteousness,
and in the image of God, and in Christ Jesus; yea, they were meet-helps one to another;
and Christ makes them as kings and priests to reign upon the earth,
over the serpent and the devil, the destroyer, in the power of God,
which was before he was, in which is the holy order.
And they that offer the spiritual sacrifices to God, and are his heavenly witnesses,
stand for God and Christ, and his righteousness, in his light and life,
by which they are grafted into Christ; and so by and in his power, light,
and life stand over death, and darkness, and the prince and power of it,
and in it reign over him.
And so do praise God, and his son that liveth forever, and sing Hallelujah.

[.signed-section-signature]
G+++.+++ F.

Swarthmore, the 10th month, 1679.

[.centered]
=== Epistle 350.

[.blurb]
==== An Epistle to Friends, for them to read.

My dear friends,

The peaceable truth live in, which you have received from Jesus your saviour,
that by the grace and truth that is come by him into your hearts,
you may all abide in Christ, and grow up in him, from whence it comes.
For, as Christ saith, "`Except you abide in me, ye cannot bring forth fruit.`"
And there is none that abide in Christ, but who abide in his light, grace, and truth.

And Christ saith,
"`Without me ye can do nothing;`" who is the heavenly and spiritual man, the second Adam,
the Lord from heaven, who hath all power in heaven and earth given to him.

So without this truth, and grace, and light, and power, and spirit of Christ Jesus,
which you receive from him, you cannot abide in him.
This brings you to abide in him, and to have his presence to strengthen you,
so that through him you may do all things which he commands and requires of you.

And now, dear friends, to the light, and grace,
and truth in your hearts you were turned at the first,
and now as you do all walk in the light, and are established in the grace and truth,
in your hearts, minds, and souls, it brings you to Christ,
the heavenly spiritual rock and foundation, and to build upon him, with the light, grace,
and truth that come from him; and then you will see such as Christ speaks of,
that did profess him and preach him, but did not abide in his light, grace, and truth,
so not in Christ Jesus; and such Christ will not know, that do not abide in him,
with his light, grace, and truth, from whence it comes.

For the grace, truth, and light that cometh by Jesus, this makes inward christians,
and the Jews inward, who have the praise of God, though may be not of men.

And the apostles in their days, had to do with several sorts of people,
some that preached Christ of envy, and some of contention, and some of good will;
notwithstanding, the apostles rejoiced that Christ was preached.
But then after a time, when many had gotten the form of christianity and godliness,
and denied the power thereof, he exhorted the faithful,
that kept their habitation in Christ Jesus, to turn away from such.

And yet such were under the name of christians,
else they could not have the form of godliness.

And likewise, such as got the good words and fair speeches,
with which they deceived the hearts of the simple,
these were got to be preachers among the christians.

And the heady, high-minded, and fierce despisers, these had the form of godliness,
though they denied the power of it, which they were turned from.

So they that lived in the light, grace, and truth, and the power and spirit of Christ,
were to turn away from such, that had the form of godliness, and denied the power.

And such as these, that had the form of godliness and denied the power,
were come farther than such as taught for doctrine
the rudiments and precepts of the world,
and doctrines of men; or the professing Jews and Gentiles,
that stood against the name of Christ,
which were altogether unbelievers of the very form of godliness of the new covenant.

And likewise such that were doting about questions, and in strife about words,
vain janglers, and disputers, men of corrupt minds, and those that were unruly,
and vain talkers; many of these were teachers,
who were troublers of the churches in the apostles`' days.

And those that Peter and Jude cried against, that were come so far as Balaam,
to prophesy, and Cain to hear the voice of God, and a Cora, who came out of Egypt;
many of these got up to be teachers, having high swelling words,
whom the apostle judged amongst the fallen angels, and thee old world, and Sodom;
who were turned to be mockers.

And such like as these were they, that separated themselves, being sensual,
having not the spirit.
And so it seems these did set up separations from the apostles and saints in their days.

And the apostle declareth, how the Lord saved his people out of the land of Egypt,
and afterwards destroyed them that believed not;
and the angels that kept not their first state, but left their own habitation,
he hath reserved in everlasting chains under darkness,
unto the judgment of the great day.

And so these, who went under the name of christians, that had been convinced,
and had got a form of godliness and christianity, that kept not their first state,
in the light, and grace, and truth, and by it their habitation in Christ Jesus,
they came under the chain of darkness.

And therefore, friends,
you see how the apostle was troubled with the false apostles and Satan`'s messengers,
that got among the Corinthians, and how they despised the apostle.

And likewise what was got up among the Romans and Galatians, and in the days of John,
as he manifests in his epistles.

And therefore, how careful were the true apostles, of the saints,
in their watching over them!

For John said, "`If ye walk in the light, as he is in the light,
then have we fellowship one with another.
And that ye also may have fellowship with us;
for truly our fellowship is with the Father and his son Jesus Christ.
And these things write we unto you, that your joy may be full.`"

For many may talk of the light, and preach the light; but to walk in the light,
that is it which grafts into Christ Jesus, and brings to live in him,
which talking of him doth not.

And as the apostle said, "`As every one hath received Christ Jesus, so walk in him.`"
And the sayers of the word, and not the doers, deceived their own souls.

So there may be many sayers of the word, deceivers of their own souls and others,
and preachers of Christ Jesus.
But the doers of the word, and the walkers in Christ Jesus,
are they that are accepted of the Lord.

And again, as the apostle saith, The word of faith was nigh them,
in their hearts and mouths, to obey it and do it;
and that was the word of faith which they preached.`"

"`And the light shined in their hearts,
to give them the knowledge of the glory of God in the face of Christ Jesus.`"

"`And the anointing which you have received of him, abideth in you;
and ye need not that any man teach you,
but as the same anointing teacheth you all things, that is true, and is no lie;
and even as it hath taught you, ye shall abide in him.
And these things I have written unto you,`" saith the apostle,
"`concerning them that seduce you.`"

So here may all the inward christians in the grace, light, truth, power,
and spirit of Christ Jesus, see what the apostles exhorted the saints unto,
that they might be preserved in their day, and so by the same now,
from them that deceived their own souls and others.

And so by this light, this word, the anointing, grace, truth,
power and spirit of Jesus Christ in the heart, mind, and soul,
must all the saints be guided now, by which they may come to be inward christians,
and have a habitation in Christ Jesus,
and so built upon him the living rock and foundation,
as the saints were in the apostles`' days; and so to have salt in yourselves,
and the leaven in your own meal, and the pearl in your own field,
and your lamps lighted in your own tabernacles, and nourished with the heavenly oil.
So that you may put a difference betwixt the clean and the unclean,
and what you are to touch, and what you are not.
And that no man or woman may look below heaven for their bread,
to nourish their souls and inward man, and below God and Christ for their springs,
which by continuing in the light, which is the life in Christ the word,
by which all things were made and created,
they shall have a spring from him the fountain, springing up in them to eternal life;
so they shall have both the upper and nether springs
to nourish the plant that God hath planted.

And such as came out of Egypt with Moses, and after rebelled against the Lord, and Moses,
and the law and the prophets,
were a greater grief to Moses and the prophets than the heathen.

And likewise, those that came to be christians,
(called,) and had got the form of godliness,
came to be a greater grief to the apostles than the world;
for their work was to seek to destroy that which the apostles had begotten,
and them that they had turned to Christ.
And therefore well might the apostle exhort the saints "`to turn away from such that
had the form of godliness and denied the power;`" and therefore he told the saints,
"`The kingdom of heaven stands not in words,
but in power;`" and therefore they were to know one another in the spirit and power;
and that is the internal knowledge.
And their fellowship was to be in the holy ghost, and their unity in the spirit,
which was the bond of peace; and their fellowship was to be in the gospel,
which was the power of God.
So an everlasting fellowship in the everlasting power of God,
that will out-last the power of darkness; for it was before it was.
And also, their unity was to be in the precious divine faith,
which Christ was the author and finisher of;
the mystery of which was held in a pure conscience;
and their worship was in the spirit of God, and in truth.
So you may see what a heavenly unity and fellowship,
and a worship Christ and the apostles set up.

And the saints in the light, grace, truth, spirit, and the power of God, the gospel,
lived in it, and walked in it.
So with the light, grace, truth, power, spirit, and word of life in the heart,
all hold Christ the head, who is the head of all things, by whom all things were made,
who is the treasure of the heavenly saving wisdom and knowledge,
who is called the second Adam, the Lord from heaven.

And therefore, all are to have their knowledge and their wisdom from him the treasure,
by the light, grace, truth, power, and spirit that comes from him,
it leads you to him your treasure of heavenly wisdom and knowledge;
by which knowledge you know God, and Jesus Christ whom he hath sent,
which is life eternal to know.

=== And now, my dear friends, concerning true liberty.

The true liberty is in the gospel, the power of God, which the devil and his instruments,
with his false liberty, cannot get into.

And in this gospel is the saints`' fellowship,
which the devil with all his false fellowships cannot get into, nor find it;
for it is a mystery.
Likewise, true liberty is in the faith, which Jesus Christ is the author and finisher of,
which gives victory over that which separated man and woman from God,
and by which they have access to God again.
And in this holy, pure, divine, precious faith, that is held in the pure conscience;
which pure conscience hath its pure, holy, divine, precious liberty, in this holy,
divine, precious faith, which works by love, (and not as the dead faith doth,
which works by enmity,) which is the fruit of this holy, pure, divine faith;
and in it is the divine, pure, holy, and precious liberty and freedom.
So here is the divine, holy, pure, and precious liberty in this faith,
which works by love,
that is the victory over that which brought man and woman into bondage, and slavery,
and false liberty.
So this living faith is the victory over all dead faiths and false freedoms and liberties;
which holy, divine, pure, and precious faith, the saints were and are to contend for,
which Christ the Holy One is the author and finisher of.
So in this holy, divine, pure, and precious faith, they have a holy, divine, pure,
and precious unity and liberty, which is the victory over the enmity and the adversary,
the destroyer, and all his instruments; and they cannot come within this holy, divine,
pure, and precious unity and liberty, which is in the faith; for it is a mystery,
and gives victory over him, and the access to the pure God,
and to Christ the author of it;
which all are to stand fast in that liberty wherewith Christ hath made them free,
who is the heavenly and spiritual man, the second Adam.

For the bondage, captivity, and thraldom, false freedom, and false liberty,
were and are in old Adam, in transgression;
and the true liberty is that which Christ the pure and holy one makes free in;
and this is a pure holy liberty, which Christ makes, and sets his people free in;
in which they are all to stand fast over all the false liberties and freedoms,
which are bondage.

Also, the true liberty is in the truth, which if the truth hath made you free,
then are you free indeed, from him that abode not in the truth,
in whom there is no truth.
So then there is no true freedom nor liberty in him; and he in whom there is no truth,
cannot come into this freedom and liberty, which is in the truth,
but remains in the false.

For the Jews in the days of Christ, boasted of their liberty and freedom,
though they were in bondage both inwardly and outwardly;
and that they were of Abraham their father; but Christ told them,
"`the devil was their father, and his lusts ye will do.`"

And also in the days of the apostles,
many of the false christians boasted of their liberty;
but who was overcome by them was brought into bondage.

And the apostle was so careful of his liberty in Christ Jesus,
that such as came to spy it out, and were somewhat in conference;
but they added nothing to him; and unto such he would not give place by subjection,
but rather reproved them;
and directed every one to walk according to the measure
of the rule which God hath distributed to them.

And also true liberty is in the light, and grace, and the spirit which comes by Jesus,
which by believing in the light, they are grafted into Christ,
and so into true liberty and freedom, and so are entered into the rest,
out of the toil of old Adam; for they are grafted into him, who was before old Adam.

For unbelievers in the light are grafted into old Adam, in transgression.
And the believers in the light,
(which is the life in Christ,) are grafted into Christ the word,
by which all things were made and created.
So here is perfect, true freedom and liberty.

And likewise, the true liberty and freedom is in the grace which brings salvation,
and not destruction; and teaches to live godly, not ungodly; and soberly, not unsoberly;
and righteously, not unrighteously; and teaches to deny the world,
and not to cleave to it, and follow it.

This grace establishes the heart, and seasons the words;
the fruits of its liberty and freedom will manifest itself.

And also,
the true liberty in the pure holy spirit of God and Christ doth baptize
and plunge down that which is gotten up by transgression in man and woman
and circumcises and cuts off the body of death and sin in the flesh,
that is gotten up in man and woman by transgression,
and mortifies and kills that which would grieve, vex,
or quench the motions of the pure spirit of God; so that in this holy, pure spirit,
of this pure God and Christ,
is the holy pure freedom and liberty over all bondage and false liberties and freedoms.

And the fruits of this pure spirit are pure love, righteousness, and godliness, patience,
temperance, and humility; by which spirit all are made to drink into one spirit;
so that all are the living wells, that have their living water from God and Christ,
their true and living fountain;
and in which spirit they have a holy and spiritual fellowship, in this baptizing,
mortifying, circumcising spirit, yea, one with another,
and with the son and the Father also,
through which the love of God warms every one`'s heart.
But when the love of many waxes cold, as Christ saith, then they go from this grace,
light, truth, power, and spirit, and the anointing,
and the word of God in their own hearts; then such turn to be betrayers,
and not saviours upon mount Zion.
And against such God`'s swift judgment turns, and suddenly falls,
though they may cry for a time, liberty, freedom, and peace, peace;
but a day of trouble will overtake them ere they are aware.

And therefore, all ye friends of Christ Jesus,
stand fast in that liberty wherewith Christ hath made you free, by his light, grace,
truth, spirit, faith, and everlasting gospel, the everlasting power of God,
which is an everlasting freedom and liberty above
all bondage and false fallen liberties and freedoms;
in this glorious gospel, and glorious joyful liberty,
where all may exercise God and Christ`'s holy gifts in his holy supernatural light,
grace, truth, spirit, and divine faith, and word of life, and the gospel;
which word cannot be bound with all the world`'s cords or chains;
"`for it is a fire to burn, and a hammer to break, and a sword to cut in pieces.`"
And therefore love the word, and keep the word of patience, and the Lord will keep you,
for it is a tried word, and it will keep you in all trials,
which shall come upon all the world to try them.
For the word was before the world was, and will be when the world is gone,
which all the new born babes of the incorruptible seed,
who partake of the milk of the word, grow by it up into an immortal life,
and kingdom that is without end; "`Glory and praises to the Lord God forever.`"

And now, ye babes of Christ, if the world do hate you,
it hated Christ your Lord and master also; if they do mock, and reproach, and defame,
and buffet you, they did so to your Lord and master also; who was and is the green tree,
that gives nourishment to all his branches, his followers.

Now, if the world do persecute you, and take away your goods or clothes,
was not your Lord and master so served?
Did not they cast lots for his garments?
Was not he haled from the priests to Herod, and before Pontius Pilate, and spit upon?
And if they hate thee, and spit upon thee, he was hated and spit upon for thee.
Did he not go to prison for thee?
And was he not mocked and scourged for thee?
Did not he bow to the cross and grave for thee, he who had no sin,
neither was guile found in his mouth?
And did he not bear thy sins in his own body upon the tree?
And was he not scourged for thee, by whose stripes we are healed?
Did not he suffer the contradiction of sinners, who died for sinners,
and went into the grave for sinners, and died for the ungodly, yea,
tasted death for every man, who through death destroyed death, and the devil,
the power of death, and is risen?
For death and the grave could not hold him, nor the powers and principalities,
with all their guards and watches, could not hold him within the grave; but he is risen,
and is ascended far above all principalities, powers, thrones, and dominions,
and is set down at the right hand of God,
and remaineth in the heavens till all things be restored.
And he is restoring with his light, grace, truth, power, spirit, faith, gospel,
and word of life; so that you read of some,
that came to sit together in heavenly places in Christ Jesus.

And therefore all must bow at the name of Jesus their saviour, in his light, grace,
truth, power, spirit, and gospel, (for he hath bowed for you,) if you rise with him;
and you must suffer with him, if you will reign with him; and die with him,
if you will live with him.
And all that are dead and buried with Christ, and are risen with him,
they will seek those things that come down from above,
where Christ sits at the right hand of God;
and there you will seek those things which come down from above,
and not things which are below.

For those which seek those things that are below, are the talkers of God and Christ,
and the prophets, and apostles`' words, but they are not dead with Christ,
nor risen with him;
and therefore they do not seek those things that come down from heaven,
where Christ sits at the right hand of God.
But they are them that seek the things that are above, that are dead with Christ,
and risen with him; they, I say, do seek those things which come down from heaven,
where Christ sits at the right hand of God; and they have not only sought them,
but have found them, and received them,
and come to sit together in heavenly places in Christ Jesus, a safe, established,
and heavenly sitting in the heavenly rest and habitation in Christ Jesus,
who is the first and last, and over all, from everlasting to everlasting.
Blessings and praises over all be to the Lord God through him forever.
Amen.

The eternal living God of truth, he is a God of order,
and is not the author of confusion, but of peace in all the churches of the saints.

Now the author of confusion, and not of peace, is the god of the world,
who abode not in the truth, because there is no truth in him; and when he speaks a lie,
he speaks of his own; for he is a liar, and the father of it.

Now the Jews, who did the god of the world`'s lusts, and those called christians that do,
were in strife, confusion and disorder.

For the Jews went out of the order of Aaron and Moses,
going from the spirit of God poured out upon the house of Israel,
and so went from the Lord, and his law, into confusion and disorder,
which the living God of truth was not the author of.

Also the christians, who go from the light, grace, truth, power, spirit, gospel,
and faith, which Christ Jesus is the author of, they go from Christ and his order,
who was not made a priest after the order of Aaron, but after the order of Melchizedek,
who was without beginning of days, or end of life; an everlasting order.

And such go into strife and confusion that go from Christ,
which Christ and God is not the author of, but the world`'s god,
who got into man and woman by transgression and disobedience of the command of God;
who is the author of confusion, strife, and disorder, in whom there is no truth.
For what order can there be in the world`'s god, and amongst his subjects,
in whom there is no truth?
For in whom there is no truth, there is no true order;
and they that abide not in the truth, grace, light, spirit, gospel, faith,
and word of life, they abide not in the order of God and Christ.

And such will cry against the order of the truth, light, grace, spirit, gospel, faith,
and word of life, which brings into the order of Christ,
and the order of the living eternal God of truth, who is a God of order,
and delights in order, having pleasure in them that live in his spirit, and law of life,
and the gospel, and its order.
For blessed is the man that delights in the law, or order of God;
it was so under the old covenant.
Much more blessed is the man or woman that delights in the law and order of love,
and the law and order of faith, and the law and order of life, and of the gospel,
the power of God.

And none keep the law of faith, but who keep in the faith which Christ is the author of,
which works by love.
And none keep the law of life, but who keep in the law of the spirit, and walk in it,
which is in Christ Jesus, the heavenly and spiritual second Adam,
who was before old Adam, who was under the world`'s god, out of truth,
in whom there is no truth, nor true order, but confusion and disorder.

And therefore all who come to God, who is a God of order, must come by the grace, truth,
light, power, gospel, faith, and anointing, the word of life within;
and such come to love the Lord Jesus Christ, and to delight in God and Christ`'s order.
So you may see, that God is a God of order, who called Aaron and Moses,
and they had an order from God.
And Melchizedek had an order; and Christ is after his everlasting order.

And Christ, the truth, hath an everlasting kingdom,
that stands in everlasting righteousness, and power, and joy in the holy ghost; yea,
an established kingdom, that will never have an end, and cannot be broken;
and no imperfect, defiled, nor corruptible thing enters into it.

And all Christ Jesus`'s subjects of his everlasting kingdom, that see it,
and enter into it, are born again, not of the will of man, but of an incorruptible seed,
by the word of God, and have the incorruptible milk of the word of God,
by which they grow from babes to men of God; and have the fine linen,
the incorruptible clothing, the righteousness of Christ, which is the fine linen,
which they do wear in Christ`'s kingdom.

So all Christ`'s subjects of his kingdom are known by their birth and clothing,
and live in the order of his gospel of love, life, light, grace, and truth;
and no man comes into his kingdom and order, but by the light, grace, truth, faith,
power, and spirit, and anointing, and word of life within,
through which they know Christ, and his everlasting kingdom, that stands in power,
and righteousness, and joy in the holy ghost;
and by it keep in the order of the law of life, which they have in Christ Jesus.

And they that follow the world`'s god, that are out of truth, and disobey their Creator,
the God of truth, and the Lord Jesus Christ; I say,
all such obey and follow him in whom there is no truth;
and such cannot endure to hear talk of the order of truth, and of the gospel, or the law,
or order of the spirit of life which is in Christ Jesus;
which all they that do obey the voice of the Lord, and Christ Jesus in his light, grace,
and truth, and gospel, the power of God, and his holy spirit, and faith,
and word of life within, come into unity and fellowship one with another,
and with the son, and with the Father; and in this they know the order of Christ,
and God to be a God of order, and delight in his heavenly and eternal order of light,
life, power, and spirit of God, that is over death and darkness, and the world`'s god,
who is a god of disorder, in whom there is no true order, but confusion;
and into this holy order of the everlasting light and life he cannot come.
Glory to the Lord God, and his son Christ Jesus,
who is over all from everlasting to everlasting, and is the rock, and foundation,
and habitation of his people, blessed forever and evermore.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

Postscript.--Here you may see by these following scriptures,
how the apostles loved the good and holy order of Christ in his gospel, and light,
and life, and truth; but as Job said, "`The land of darkness is without any order.`"
And Babylon signifies confusion, which is the false church, and is called a woman,
and a city of confusion, who is against the order of the true church,
and gets the titles of the true church that is called a city,
and a woman "`which brings forth the man-child,`" Christ Jesus;
and "`of the increase of his government and peace there shall be no end;
who sits upon the throne of David, and upon his kingdom, to order it,
to establish it with judgment and with justice, from henceforth and forever.`"
So here you may see Christ doth order in his kingdom; and them that have him,
have his order. Isa. 9:7.

And David saith, "`Although mine house be not so with God,
yet he hath made with me an everlasting covenant, ordered in all things, and sure;
for this is all my salvation, and all my desire,`" etc. 2 Sam. 23:5.

Again David saith, "`Order my steps by thy word,
and let not iniquity have dominion over me.`"
Ps. 119:133.

Which is the duty of every christian, to have their steps ordered by the word of God,
that lives, and abides, and endures forever; which word is a word of order.

And David saith, "`The steps of a good man are ordered by the Lord,
and he delights in his way.
I have been young, and now am old, yet I have not seen the righteous forsaken,
nor his seed begging bread.
He is ever merciful, and lendeth, and his seed is blessed.`"
Psalm 37.

Here you may see, how the Lord delights in him, and them that walk in the steps,
the Lord orders them with his word.

"`And he that orders his conversation aright, shall see the salvation of God.`" Ps. 50:23.

And this order must be in the light, which is the life in Christ the saviour.

And the apostle Paul, after he had spoken many things to the Corinthians, said,
"`The rest will I set in order when I come.`" 1 Cor. 11:34.

And he saith concerning the collections for the saints,
in 1 Cor. 16:1. "`As I have given order to the churches of Galatia,
even so do ye,`" to wit, the Corinthians.

So they were to practise the same order, who were the believers in Christ,
which the apostle in the power of Christ had given to them.

For the apostle had the wisdom of God, which he had ordained before the world began,
unto the glory of his people then and now also. 1 Cor. 2

And the order that the apostle did give to the churches
of the Galatians and the Corinthians was,
"`That upon the first day of the week,
every one of them should lay by him in store as God had prospered him,`" etc. 1 Cor. 16:2.

And in Acts 14. when they had ordained elders in every church, and had prayed,
they commended them to the Lord on whom they had believed,
confirming the souls of the disciples, etc. and exhorting them to continue in the faith;
and that they must through much tribulation enter into the kingdom of God.

And as Paul and others with him went through the cities,
they delivered them the decrees for to keep,
that were ordained of the apostles and elders which were at Jerusalem;
and so were the churches established in the faith, and increased in number daily.
Acts 16.

And the occasion of these decrees was, because some men that went from Judea,
taught the brethren, saying, "`except ye be circumcised after the manner of Moses,
ye cannot be saved.`"
Acts 15. And these decrees were to stop such preachers.

For the apostles and elders said, "`Forasmuch as we have heard,
that certain which went out from us, have troubled you with words, subverting your souls,
saying, ye must be circumcised, and keep the law; to whom we gave no such commandment.`"

Now it is clear, the apostles and elders gave these teachers no such commandment,
to preach such doctrine to trouble the churches.

And the apostle Paul, after he had spent some time at Caesarea and Antioch,
went over all the country of Asia and Phrygia in order, strengthening all the disciples.
Acts 18.

So you may see, how they were a comfort one to another.

And the apostle writes to Titus, chap. 1.
"`For this cause I have left thee in Crete,
that thou shouldst set in order the things that are wanting;
and ordain elders in every city, as I have appointed thee.`"

So here Titus in the spirit of God did observe that which
Paul in the power of Christ did exhort him to.

But such as are against the order and practice in the light and gospel,
cannot order their speeches by reason of darkness.

And the apostle saith, Col. 2:5 "`Though I be absent in the flesh,
yet am I with you in the spirit, joying and beholding your order,
and steadfastness of your faith in Christ.
As ye have therefore received Christ Jesus the Lord, so walk ye in him.`"

Here the apostle rejoiced in the order that kept them in
the faith and steadfastness in Christ Jesus.

Therefore the apostle saith, "`Every man in his own order, Christ the first-fruits, etc.
For as in Adam all died, even so in Christ shall all be made alive.`"

And they that are alive in Christ Jesus, are in his order of life and light,
and in his gospel the power of God.

And the apostle saith, 1 Cor. 14.
"`Let all things be done decently and in order.`"

And the heavens and the earth, and all things therein,
are governed and ordered by the Lord, in his power and wisdom;
and all God`'s holy angels are governed and ordered by God;
and all God`'s children and people are governed and
ordered by God and Christ in his light,
and spirit, and grace, and truth, and power, gospel, and word of life.

And the Lord hath set apart him and them that are godly for himself.
Psalm 4.

And God hath ordained his arrows against the persecutors. Ps. 7:13.

And it ought to be the practice of all the true christians now,
that are in the same power and spirit as the apostles were in,
to let all things be done decently and in order, in the new covenant of light, life,
and grace, to the glory of the great God, who is over all,
and orders all things to his glory.
Amen.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 351.

[.blurb]
==== Concerning true liberty.

And now, friends, you who are called into this glorious liberty of the sons of God,
stand fast in it.
And as the apostle saith, "`Brethren, ye have been called unto liberty,
only use it not for an occasion to the flesh; but in love serve one another.`" Gal. 5:13.

"`As free, not using your liberty for a cloak of maliciousness,
but as the servants of God.`" 1 Pet. 2.

For there were some, who while they promised themselves liberty,
they themselves were servants of corruption.
Such were like the dog and the sow, biting, and rending, and vomiting,
and wallowing in the mire;
and as bad as the synagogue of the libertines that turned against Stephen.
2 Pet. 2. and Acts 6:9.

And therefore the apostle was careful of the churches`' liberty in Christ, when he said,
"`But take heed,
lest this liberty of yours become a stumbling-block to them that are weak,`" etc.
1 Cor. 8.

For the apostle was so careful and tender,
that he would not have his true liberty judged of another man`'s conscience,
etc. as you may see more at large in Cor. 10.

And the apostle said, "`False brethren came unawares privily, to spy out their liberty,
which they had in Christ Jesus, that they might bring them into bondage;
to whom we gave place by subjection, no not for an hour,
that the truth of the gospel might continue with you,`" to wit, the Galatians. Gal. 2:4.

And therefore he exhorts them to stand fast in that
liberty where with Christ Jesus hath made them free,
etc. which is the duty of all true christians now,
to stand fast in that heavenly glorious liberty,
which Christ the heavenly and spiritual man, the second Adam, makes them free in;
and in this they will have salt in themselves,
to discern between the true liberty and freedom and the false,
and know how to use their holy and spiritual liberty and freedom in Christ Jesus,
to the praise and glory of God.

So, friends, the Lord God Almighty preserve you all,
in the heavenly order of Christ Jesus, in his holy seed, life, power, and spirit,
that all may live and walk in it, to the praise, and glory, and honour of God and Christ.
Amen.

[.signed-section-signature]
G+++.+++ F.

The 3d of the 9th month, 1679.
