== Epistles 352 &#8212; 362

[.centered]
=== Epistle 352.

Dear friends and brethren,
in the Lord Jesus Christ! and blessed be the God and Father of our Lord Jesus Christ,
who hath blessed us with all spiritual blessings in the heavenly places in Christ Jesus,
and hath chosen us in him, before the foundation of the world.

And now, that all may walk in him in love,
who hath seen the great deliverances of the Lord,
and hath been acquainted with his great mercies, that endure forever;
deliverance after deliverance, multitude of deliverances,
out of great trials and temptations;
and hath seen how the Lord hath brought to confusion the enemies of his truth,
both within and without, from the beginning;
and therefore in the Lord`'s spirit and power, all that live in it, that know the Lord,
are encouraged to trust in him.
God hath raised you up together, and quickened you who were dead in Adam,
and made you to sit together in heavenly places in Christ Jesus,
that you might show forth the riches of his grace and glory,
and his kindness towards you through Jesus Christ.
For by one spirit we are all baptized into one body; whether we be Jews or Gentiles,
bond or free; and have been all made to drink into one spirit.
And therefore, endeavour all to keep the unity of the spirit in the bond of peace,
and live and walk in the spirit: and the fruits of this spirit of God, is love, joy,
and meekness, etc.
And by this one spirit, you have access to the Father of spirits; and this one spirit,
which baptizes you into one body, both male and female, knows your service to God:
for the spirit of God divides severally to every one of you,
as he wills your offices and places, yet all in unity in the spirit,
with which you are baptized into one body, and drink into one spirit.
And the apostle Paul, who wrote from Rome to the Colossians, told them,
that "`they were complete in Christ Jesus;`" and said, "`Though I be absent in the flesh,
yet am I with you in the spirit, joying and beholding your order,
and the steadfastness of your faith in Christ.`"

And now the Lord hath gathered his people, by his power,
into the same spirit that the apostles and churches were in, in the primitive times:
and though they be absent in the body, or flesh, men in one room,
and the women in another; yea, as far as the east is from the west,
or the north is from the south, yet they are present in the spirit,
rejoicing and beholding with the spirit, the spiritual order that the churches:
and apostles were in, and the steadfastness of their precious, holy, and divine faith,
which Christ (the second Adam) is the author and finisher of; and this is no separation,
but they are the household of his holy, divine, and precious faith;
and live and walk in this holy faith, and spirit of God,
by which they are baptized into one holy body, of which Christ Jesus,
the holy and spiritual man, is the head.
And this, I say again, is no separation, though they be absent in the body or flesh,
yet they are present in the spirit, and with the spirit behold the spiritual order.
And this is not an imposed outward form, order or prescription, as some ignorantly think.
But they that do say, and prescribe, that men and women must meet all together outwardly,
in a bodily presence in one room, or else it is a separation, I say,
it is an outward form, an outward order, and imposition, and prescription,
and they that fiercely press it, know not the spiritual order; yea, I say,
if all men and women in the world could meet outwardly together,
and are not in the power and spirit the apostles were in, they are in a separation.
But God Almighty is bringing his people, by his son Christ Jesus,
and by the same power the apostles were in, out of this separation,
and apostacy from the apostles`' spirit, that began in the apostles`' days,
into the same spirit that the church and the apostles were in, in the primitive times;
and though they be absent in the body, or flesh, yet they are present in the spirit,
seeing and beholding, in the spirit, the spiritual order,
and the steadfastness of their divine faith, which Christ (the second Adam,
the spiritual man) hath been the author and finisher of.
And therefore, let no man beguile you by enticing words, from this spiritual order,
fellowship, and unity.
And again, the apostle saith, "`For I verily, as absent in the body,
but present in the spirit, have judged already, as though I were present,
concerning him that hath so done this deed.`"
So here was a spiritual sight, and a spiritual judgment; yea, a judgment,
though absent in the body, by a spiritual sight of such as walk not in the spirit,
but walk out of the order of it. 1 Cor. 5:3.

And this is to the spiritual-minded, who can judge of these things,
for "`as many as are led by the spirit of God,
they are the sons of God;`" and the Lord now, by his spirit,
is separating his sons and daughters from the apostacy and sin,
which hath separated from the spirit that the apostles were in,
that they may behold one another with joy and comfort with the spirit,
in the spiritual order, fellowship, and unity;
though they be absent in the body and in the flesh, yet they are present in the spirit,
and know one another in the spirit of God.
And also, the apostle saith, "`As many as are baptized into Christ, have put on Christ:
there is neither Jew nor Greek, bond nor free; and here is neither male nor female,
but ye are all one in Christ Jesus.`"
So, though these be absent in the body, one from another, Jews, Greeks, bond, or free,
males or females, yet they are all one in Christ Jesus, the spiritual and heavenly man,
and with the spirit joying and beholding one another`'s spiritual order; so the joying,
unity, and fellowship stand in the spirit of God,
and not in the outward fleshly bodily presence, and carnal and natural sight.
And therefore keep your spiritual order, joying in the spirit,
beholding your spiritual order, and steadfastness of your faith in Christ Jesus.
And in this you will be all steadfast men and steadfast women,
and not tossed up and down with every windy doctrine,
and the cunning crafts and slights of men,
but steadfast men and steadfast women in the faith of Christ, as trees of righteousness,
the planting of the Lord, whose "`fruit is unto holiness,
and whose end is everlasting life.`"
And such have fruit on their own trees, and water in their own wells,
and are not shaken with winds, storms, nor tempests, that may rise up within or without,
but are steadfast and immoveable, built upon the rock and foundation of life,
Christ Jesus.
So that as every one hath received the gift, even so minister one to another,
"`as good stewards of the manifold grace of God.`"
And this is the grace of God wherein ye stand, that will teach you to live godly,
righteously, and soberly, and brings salvation; so not only to talk godly,
but to live godly, keeping yourselves in the love of God,
and building up yourselves in the Most holy faith, which you have from Christ Jesus,
which makes you steadfast and immoveable, from him who is the author and finisher of it;
and with the spirit of God,
in which you (spiritually) behold your substantial and steadfast spiritual order,
over all outward and carnal orders, and will out-last them all;
with which spirit you all see your work and service
for the eternal immortal God of truth;
to whom be all glory, honour, thanks, and praises in the church of Jesus Christ,
throughout all ages, world without end.
Amen.

From your friend and brother in the kingdom and patience of Jesus.

[.signed-section-context-close]
Worplesdom, the 22nd of the 5th month, 1680.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 353.

[.blurb]
==== To Friends in America.

[.salutation]
Dear friends,

My love to you all in the holy peaceable truth; and my desires are,
that whatsoever ye do may be done in the name of Jesus, to the glory of God the Father.
And all be subject one to another in the fear of the Lord God,
so that ye may all come to dwell in the love of God, which edifies the body of Christ,
who is the heavenly man.
And let all strifes, and divisions, and backbitings, or whisperings, or prejudices,
cease and be buried; and so whatsoever is amiss, or hath been amiss,
let it be put down by the truth and spirit of God, that it may be uppermost,
which is a strong bond to unite your hearts, and minds, and souls together,
and to the Lord.
And be kind and courteous one towards another, all studying to be quiet,
and to excel one another in virtue, and purity, and holiness, and righteousness,
and godliness, in all your words, and lives, and conversations;
so that you may all walk as become saints and christians,
every one esteeming and preferring one another above yourselves in the truth,
in meekness, and lowliness of mind, and humility; for he that inhabits eternity,
dwells with an humble heart.
And therefore, do not quench the least motion of God`'s good spirit in yourselves,
nor in any other; but let truth and goodness be cherished in all; and let all harshness,
and bitterness, and revilings be kept down by the truth,
that it may have its passage through you all,
and in it you may bear one another`'s weakness and infirmities,
and so fulfill the law of Christ; keeping down revenge, hastiness or passion,
as knowing vengeance is the Lord`'s, and he will repay it on every one that does wrong,
without respect of persons.
For, friends, you there should be as lights, or as a city that cannot be hid.
Lights, I say, to give light in all people; and also to be as the salt of the earth,
to be a good savour, and savoury to all people; for he or she, that is an ill savour,
hath lost the salt`'s savour, and is good for nothing,
and is trodden under the foot of men.
And therefore take heed of losing the salt`'s savour, either in word or conversation;
for if you do, you will come under the foot of men, they will trample upon you;
therefore be careful, fervent, circumspect, and faithful in the truth,
and let your moderation, temperance, and sobriety appear to all men,
showing forth the work of the Lord,
and your honesty and justness in all your words and dealings between man and man;
and that you may owe nothing to any man but love,
that every one of you may be adorned with a meek and quiet spirit,
which is with the Lord of great price.
And every one of you to be indued with wisdom from on high, which is pure and peaceable,
gentle, and easy to be entreated, and full of mercy and good works;
let the fruits of this appear among you all,
and then you will all be gentle and easily entreated one of another.
And keep in the unity of the spirit, which is the bond of the heavenly peace,
(and then none quench it,) and all walking as becomes the glorious, joyful,
peaceable gospel of Christ, which is the power of God, which was before the devil,
and his power was, and is over him;
in this gospel you all know life and immortality brought to light,
that you all see your everlasting glorious fellowship,
in the everlasting gospel of peace; in this gospel, the power of God,
that was before enmity was, and will remain when it is gone.
And therefore all you who know this glorious gospel of peace live and walk in it,
keeping your glorious, heavenly, comfortable fellowship in this glorious gospel of peace,
in which enmity cannot come, as before.
And in this everlasting gospel, the everlasting God, (who is over all,
from everlasting to everlasting,) will have the praise, glory, and thanks,
who is worthy of all, forever and evermore.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 7th of the 12th month, 1680.

[.centered]
=== Epistle 354.

[.blurb]
==== To Friends in Yorkshire.

[.salutation]
Dear friends,

In the Lord`'s power and holy spirit, feel his presence amongst you,
who hath drawn you with his spirit to his son; and you that have received him,
he gives you power to become his sons and daughters; and so from the son of God,
the second Adam, you have power to meet, whose power is above Adam`'s power,
and his sons and daughters in the fall.

And now, my friends,
if you do want wisdom and knowledge to order you in the affairs and service of God,
Christ is the treasure of your wisdom and knowledge;
and so receive them from his treasury which is above.
This heavenly, saving wisdom and knowledge, from whence you have your grace and truth,
light and life, and the gospel, the heavenly spirit; yea, heavenly food,
and heavenly bread, and water of life from above; and the unleavened bread,
and sweet milk of the word, and water of life,
to keep the feast of the heavenly man`'s passover,
which is not to be found in any of old Adam`'s sons
and daughters`' storehouses in the fall;
but his old, mouldy, leavened, sour bread,
which makes his sons and daughters`' hearts to burn one against another,
and clothes them with his old rags, which will not cover their nakedness,
which they have stitched together, which must be all cast off,
and trodden under foot by the spirit and power of Christ;
which power turns you to Christ,
who clothes all his sons and daughters with his heavenly fine linen,
which will never wax old.

And therefore let all your lamps be trimmed, and candles lighted,
that all of you may see your work and service for God and Christ, in this his day.
So that you may have the blessings from above from him,
as the holy men and women of God had in the days of old;
so that there may be nothing lacking, neither spiritual nor temporal.

And so let all things be done in peace and love, in the name and power of Jesus,
amongst you; and all condescend to one another in meekness, patience, and quietness,
in the fear of the Lord; being all ordered with the wisdom of God, which is from above,
which is pure, peaceable, gentle, and easy to be entreated, that all your hearts, minds,
and souls may be knit together in the love of Christ,
and that you may be all of one mind and spirit in him; and whatever you do,
let it be done in the name and power of Jesus, to the glory of God the Father,
that created all, and takes care for all, blessed forever.
Amen.

[.signed-section-context-close]
London, the 6th of the 4th month, 1680.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 355.

[.blurb]
==== A letter to the captives who meet together to worship God in Algiers.

[.salutation]
Dear friends,

I understand by a letter from a Friend, a captive amongst you,
dated the 20th of the 10th month, 1681,
that you have a meeting there in Algiers of about twenty.
I am glad to hear you meet; and it is very well,
that you have so much liberty from your patrons; and my desire is,
that the Lord may preserve you all, that do meet in the name of Jesus,
that in your lives, and conversations, and words, you may preach righteousness,
and holiness, and godliness, and the life of truth;
so that you may answer the spirit of God, both in the Turks and Moors,
and the rest of the captives; that God`'s city may be set upon the holy hill there,
which cannot be hid;
but that all may see it with the light wherewith Christ
hath enlightened every man that cometh into the world.
And that Christ`'s ensign may be set up in those parts; that with his light in all men,
they may all see it, and flock to it;
and Christ the ensign furnisheth all that come to him,
with heavenly armour and spiritual weapons.
Now Christ enlightens every man that cometh into the world,
that every one may believe in the light, and may become a child of the light,
and have eternal life, and be saved.
And so the gospel of salvation, the power of God,
is to be preached to every creature under heaven.
And he that believes, is saved, and hath the salvation; for Christ by the grace of God,
hath tasted death for every man.
And the grace of God that brings salvation, hath appeared to all men.
And therefore all men, if they will have salvation, it must be by believing, receiving,
and walking in the grace of God, which brings it.
And the Lord pours out of his spirit upon all flesh; and therefore,
all men and women must come to this holy spirit of God,
by which the spirit of enmity may be slain and crucified in them;
that in this holy spirit of God, they may all be in love and unity;
and with the spirit of God, they may all come to know the eternal, immortal God,
and serve and worship him in his holy spirit of truth, which he hath poured upon them.
And in this, all will honour God,
and glorify him through Jesus Christ in his new covenant of light and grace.

And so, my dear friends, be faithful and valiant for God`'s truth upon earth,
and do not deny the name of Jesus, in whom you have salvation;
whose name is above every name under the whole heaven;
that ye may all be with his light built upon him
your rock and foundation that stands sure.
And now, my dear friends, though you remain as captives,
yet if ye be Christ`'s and God`'s freemen, who leads the devil into captivity,
that led you captive into his prison of death, darkness, and corruption: if Christ,
I say, has led you out of that prison and captivity,
into the glorious liberty of the sons of God,
stand fast in the liberty wherewith Christ hath made you free;
and be not entangled with any yoke of bondage, to bring you out of that heavenly,
spiritual liberty.
For in this you are free, notwithstanding the prisons and captivity of men;
and they are but small matters to it.
And therefore trust in the arm of the Lord`'s power, who can lay the mountains low,
and remove the hills out of their places, and make his lambs to skip over all.
And therefore mind the Lord and his power, that is over all that,
that makes you to suffer.
Now your sorrows and afflictions may bring many to call upon the name of the Lord,
when he has brought you low; for God is merciful and gracious to the righteous,
and his mercies endure forever.
And though hunger, and thirst, and cold, many times you are in, and many distresses,
yet the Lord is able to support you.
And now, that you may mind the Lord in your poverty, and prize his mercies;
and consider how he brought them down that did not enough prize his mercies, and liberty,
and plenty.
And ye may read the 107th Psalm throughout;
there ye may see how the Lord brought down such as contemned his counsel,
and rebelled against his words.
Well, what can you tell but that this may be the day of the Lord with you,
in your captivity, to bring down your hearts and spirits,
that with the spirit of the Lord you may turn to him, who is a God at hand;
and that you may call upon the Lord in truth and righteousness, that all your sufferings,
afflictions, and captivity may be sanctified to you.
So that you may say, "`all things shall work together for good, to them that love God.`"
And so with Job you may bless God,
"`who giveth and taketh away,`" and that you may
glorify God in whatsoever condition you may be;
that no trouble may move you; and that you may rejoice in afflictions, persecutions,
and tribulations in the Lord, through his spirit that doth uphold you.
And as you do walk in the light, grace, spirit, and gospel, you may turn others to it.
That you may have unity with them in it;
and that they may come out of the spiritual prison of death, darkness, and corruption,
and captivity, into the liberty of the sons of God in Christ Jesus.
Amen.

So with my love to you all in the holy seed Christ Jesus,
that reigns over all from everlasting to everlasting.
The Lord preserve you all tender vines in him.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 17th of the 1st month, 1682.

[.centered]
=== Epistle 356.

[.blurb]
==== To Friends in Burlington, West Jersey.

[.salutation]
Dear friends,

The Lord by his mighty hand and power having brought you to that place,
and now you are settled there, my desire is,
that your lives and conversations may preach righteousness and holiness;
for without holiness none shall see God.
And going into unholiness, that is the cause that none see God;
and the cause why there is not peace among a nation or people is,
they do not live and walk in righteousness; but walk and follow the unrighteous spirit,
which is out of the truth.
And again, Christ says, "`Blessed are the pure in heart, for they shall see God.`"
For it is the defiled and impure hearts that do not see God.
And therefore, keep in the pure spirit of God,
that does mortify all impurity and unholiness,
which blind people from the sight of the pure God.

And now, my dear friends, the eyes of other nations will be upon you;
and now you profess truth beyond them all; but if you do not exceed them in truth,
in righteousness, in holiness, justice and equity, and in the wisdom of God,
that is pure, peaceable, etc. by which you may answer the good in your government,
and all governments about you likewise, (which is my desire that you may,
that they may not see any nakedness among you,) if you do not,
you will bring both the judgment of God upon you,
and the judgment of truth that you and we profess.

For you know how that Friends in England, and other places,
have admonished the governors and rulers to do that which is just and right;
and therefore now ye are come into place,
have a care that you do that which is just and right,
lest you come under the same reproof by others.

And therefore, have an eye to the Lord in all your actions.
For David saith, (2 Sam. 23:3) "`The God of Israel said,
the rock of Israel spake to me, he that ruleth over men must be just,
ruling in the fear of God:
and he shall be as the light of the morning (that doth so) when the sun riseth,
even as a morning without clouds;
as the tender grass springing out of the earth by dear shining after rain.`"
Here you may see, it must not be unjust men, and men that do not fear God,
that must be rulers, for they do not receive his wisdom to rule withal;
and such will be as clouds without water,
(as in Jude,) and then they are not like to refresh the tender grass, but hurt it.

And Solomon saith, "`As the roaring lion, and the raging bear,
so is a wicked ruler over the poor people.`"
And therefore with the spirit of God keep down the wicked spirit in you,
and then you will keep down the roaring lion and the raging bear,
with the spirit of meekness, and patience, and wisdom, and understanding. Prov. 28:15.

And the apostle says, "`Rulers are not a terror to good works, but to the evil.`"
Therefore both rulers and ruled must be out of the evil works.
And the rulers cannot be a terror to evil works, if they live in them themselves.
Therefore all ought to live in the power of God,
which brings them out of the evil to do that which is good;
and then they will be an honour to God, and a praise one to another,
both ruler and ruled.

Now the Lord said unto Moses, "`Judges and officers shalt thou make in all thy gates,
(so they were not to be made in corners,) which the Lord giveth thee in all the tribes;
and they shall judge the people with just judgment.
(Mark! just judgment.) Thou shalt not wrest judgment, thou shalt not respect persons;
thou shalt take no gift.
For the gift blindeth the eyes of the wise, and perverteth the words of the righteous.
Thou shalt not wrest the judgment of the poor in any case.
Keep thee far from a false matter.
The innocent and righteous slay thou not; for I will not justify the wicked.
That which is altogether just, shalt thou follow,
that thou mayst live and inherit the land which the Lord thy God hath given thee.`"
Now a people following and doing that which is not just,
is the cause they do not live and inherit the land. Duet. 16:18-20.
Ex. 23:6. And therefore do that which is just,
that you may inherit Christ and your spiritual land.
"`Thou shalt not oppress a stranger, seeing you were strangers;
nor vex the widows and fatherless.`"
And the Lord saith, "`You shall be holy men unto me.`"
Again, the Lord says, "`Thou shalt not raise a false report, etc.
Put not thy hand with the wicked to an unrighteous witness.
Thou shalt not follow a multitude to do evil; neither shalt thou speak in a cause,
to decline after many, to wrest judgment.`" Ex. 23:1-2.

Again, the Lord saith, "`Ye shall not do unrighteousness in judgment;
thou shalt not respect the person of the poor, nor honour the person of the mighty.
But in righteousness thou shalt judge thy neighbour.`" Lev. 19:15.
And Duet. 1:16-17. and Josh. 7:24.
"`I charged your judges,`" (says Moses,) "`saying,
Hear the causes between your brethren,
judge righteously between every man and his brother, and the stranger that is with him.`"
So let all the strangers that are with you have righteous judgment,
as well as those among yourselves.
And again he saith, "`Ye shall not respect persons in judgment;
but ye shall hear the small as well as the great.
You shall not be afraid of the face of man;
for the judgment is God`'s.`" So long as ye judge righteously.

And therefore, now, friends, my desire is,
that you all may be kept in the power and spirit of God and Christ in humility,
and in that you will have a sense of all things, that whatever you act,
it may be done in the spirit and power of Jesus Christ, to the praise of God the Father,
who is over all, from everlasting to everlasting,
who beholds and sees all your words and actions;
that you may behold and see with his spirit, his and his son`'s divine majesty among you.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.postscript]
====

Read this in your assembly, and in your meetings.

====

[.centered]
=== Epistle 357.

[.blurb]
==== To suffering Friends at Horsham in Sussex.

Dear friends, who suffer for your testimony, and to all the rest in your county,
I am glad to hear of your faithfulness,
and of your standing for the church which Christ is the head of, which is in God,
and are become his living members; and therefore wheresoever ye are in prison,
or out of prison, where two or three are gathered in his name, there is a church,
and Christ the living head in the midst of them; a prophet,
to open to his church the things of his kingdom; and a bishop,
to oversee his living members, that they be preserved in his light, grace, truth, spirit,
and gospel; and he is a shepherd to feed them with heavenly food,
who gives life eternal to his sheep, which he hath purchased with his own blood;
and a priest who has offered up himself a sacrifice for the sins of the whole world,
who cleanses, and washes, and purifies his church, his people; a high priest,
made higher than the heavens.
Heb. 7. And no priest made below the heavens will become Christ`'s church;
and therefore feel and see Christ exercising his prophetical, priestly,
and kingly offices, and his ruling in your hearts.
And all that will know the right way, or highway, or path to the church in God, (2 Thess.
1.) must walk in the light, which is the life in Christ,
and that will guide them to Christ, the way to God, the head of the church,
the rock and foundation of God that stands sure.

And now, dear friends, my desires are, that you may all live in the love of God,
and in the unity of his spirit, which is the bond of peace,
in which you will be all kind and courteous one to another;
and so the God of all peace and power support you, and strengthen you, and uphold you,
throughout all your trials and sufferings, that he may be glorified in you all,
who is over all, from everlasting to everlasting, blessed forever;
from whom ye have blessing and life.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 20th of the 12th month, 1681.

[.centered]
=== Epistle 358.

[.blurb]
==== To the flock of Jesus Christ everywhere, to be read in their assemblies.

Grace, mercy, and peace be multiplied among you all from God the Father,
and the Lord Jesus Christ, who is the fountain of all: and God,
who hath called you by his grace,
and gathered you to be a people by his power and spirit, to his son Christ Jesus,
your holy, heavenly, spiritual head, life, rock, and foundation.
Now that you may all walk in Christ Jesus, and abide in him your vine,
and in him you will all bring forth heavenly fruit to the praise and glory of God.

Christ saith, "`In me ye have peace,
in the world ye have trouble;`" and therefore keep out of the spirit of the world;
let not the spirit of the world come into you; for if ye do,
ye go into trouble both inwardly and outwardly: but if ye keep in Christ,
who is not of the world, you keep in your heavenly place and region:
for,`" He that hath the son of God,
hath life;`" and therefore keep in the life in Christ;
and he that hath not the son of God, is in old Adam, in death, without life.

And, "`without me`" (says Christ) "`ye can do nothing;`" without his grace, his light,
his truth, his gospel, his power, his spirit, his faith, ye can do nothing; and,
"`if Christ be not in you, ye are reprobates;`" and if he be in you, and you in him,
you are in the election, and in the seed, in which all nations are blessed.

And therefore, my friends and brethren, both males and females,
keep and walk in the seed, in which all nations are blessed,
which bruises the head of the serpent, and destroys the devil and his works,
which brought misery and the curse upon all nations.
So that in this holy seed,
you all may be the children of the kingdom of God that stands in righteousness,
and power, and joy in the holy ghost: I say, in the righteousness of Christ,
which was before unrighteousness was; and in the power of God,
which was before the power of Satan and dragon were; and in the peace of God,
that passes all the understanding of the world, and was before the god of the world was;
and in the holy ghost, which was before the unclean ghost got into man and woman.

And so that you may all come to walk in the new covenant of light,
which was before the prince of darkness was, and life, that is over death,
and was before death was.
Here in this you will have your heavenly religion to walk in,
which will keep you out of all the world`'s unruly ways and actions,
and ungracious words and languages,
that all your words be seasoned with the grace of God, that hath brought you salvation,
that you may edify the hearers, and your conversation may be in heaven.

And keep in the cross of Christ, the power of God, that keeps you crucified to the world;
that is, dead to the world, and the world dead and crucified to you:
for if you do not keep in this power of God, which was before the world and its god was,
to keep you crucified to the world, but let in the spirit of the world,
you let in its god, which will crucify the good in you,
and you will come to crucify to yourselves the son of God afresh,
and put him to open shame.

Therefore keep that crucified with the power of God, the cross of Christ,
which did and would crucify the just; and then you will keep alive in the power of God,
and live in Christ Jesus, and he is alive in you, and you in him.

And now, all friends and brethren, let your meekness, your temperance,
and your gentleness and sobriety, and tenderness and moderation appear to all men,
"`that your light may so shine, that they may see your good works,
and glorify your Father which is in heaven.`"

And ye being the salt of the earth, you will make all savoury;
therefore take heed of losing your salt, lest you be trodden under the feet of men.

And keep out of the restless, discontented,
disquieted spirit of the world about the government:
for you know it has been always our way to seek the good of all,
and to live peaceably under the government, and to seek their eternal good, peace,
and happiness in the Lord Jesus Christ, and to lay our innocent sufferings before them,
who have suffered as lambs and sheep, and made no resistance,
but have "`prayed for them that persecuted us, and despitefully used us,
and hated us,`" according to the command of Christ.

"`For ye were as sheep gone astray,
but are now returned unto the shepherd and bishop of your souls:
for hitherto ye are called; because Christ hath suffered for us, leaving us an example,
that ye should follow his steps, who did no sin, neither was guile found in his mouth:
who when he was reviled, reviled not again; when he suffered, he threatened not;
but committed himself to him that judgeth righteously.
And he that will love life, and see good days,
let him refrain his tongue from speaking evil, and his lips that he speak no guile.`"
2 Pet.
2.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 21st of the 9th month, 1681.

[.centered]
=== Epistle 359.

[.blurb]
==== To suffering Friends in Leicester.

Dear friends, that are in prison, and all Friends and sufferers that are in the county,
to whom is my love in the Lord`'s eternal power, and seed of life, that reigns over all,
in whom you have peace with God, and riches that are everlasting.

Now, dear friends, your sufferings have been long in that county,
and great have been your trials, and spoiling of your goods,
through your adversaries`' and persecutors`' rage against you;
but the Lord`'s secret hand and power is that which hath upheld you through all to himself;
and therefore we may say,
"`What shall separate us from the love of God that we have in Christ Jesus?
Shall tribulations, persecutions, powers, or principalities, thrones or dominions?
Nay, there is not any thing able to separate us from the
love of God in Christ Jesus,`" whom you have chosen:
a priest that is from above, not from below, who has offered up himself to God for you,
who is not like the Jews`' priests,
that had the tithes of the people for offering up their outward offerings,
and such like services.
So you have a priest from heaven, that is made higher than the heavens,
and is the prophet that God has raised up like Moses, whom you are to hear in his light,
grace, and truth.
And he is your shepherd from heaven, who has laid down his life for his sheep,
who is above all the earthly shepherds below;
and this shepherd will feed you with that which is heavenly.
And he is your bishop from heaven, to oversee you,
that you may be kept from sitting down in any earthly place with your minds, spirits,
and souls, but only to sit down in the heavenly places in Christ Jesus,
who is the heavenly and spiritual bishop, who lives forevermore, the first and last,
the beginning and ending, who is the first-born of every creature,
and the first begotten from the dead, who does quicken, and makes alive,
and begets from the death,
and makes them to sit together (whom he has made
alive) in the heavenly places in himself.

And now, dear friends,
I do feel the Lord`'s eternal power present with you in all your sufferings,
how it hath and doth support you;
and therefore let your faith be steadfast in the power of God,
which will keep you all unto the day of salvation.
And that you may all be valiant and faithful for God`'s
truth upon the earth in this day of trial and persecution,
from both teachers, professors, and profane, which are below,
whose persecuting spirit will have but a time.
And therefore be of good faith;
for a sparrow shall not fall to the ground without the will of the Father;
and ye are of more value than many sparrows.
And "`Blessed are they which suffer persecution for righteousness`' sake,
for theirs is the kingdom of heaven.
And blessed are ye when men shall revile you, and persecute you,
and say all manner of evil against you falsely for my sake.
Rejoice, and be exceeding glad, for great is your reward in heaven.`"
For so the old persecutors persecuted the prophets and apostles before you.
But rejoice inasmuch as ye are partakers of Christ`'s sufferings;
for the spirit of glory, and of God, rests upon you, who are railed upon,
and suffer for his name sake.
And though he is evil spoken of by your persecutors, but on your part he is glorified,
that suffer for his name.
And therefore let none be ashamed to suffer as a christian,
but let him glorify God in his sufferings, who doth support him.

And so, dear friends, live in love and unity, and be kind, and courteous,
and tender-hearted one towards another; yea, and to all your persecutors,
that you may heap coals of fire upon their heads; and so overcome evil with good.
And so the God of all peace establish you all upon
his heavenly rock and foundation of life,
(Christ Jesus,) which standeth sure, and cannot be moved.
And so with my love to you all in the holy seed, in which all nations are blest.
And in this seed, the Lord God Almighty keep and preserve you,
which bruises the head of the evil seed, that makes you to suffer.
And the Lord God Almighty arm you with his armour, and strengthen you,
that you may be able to stand to his glory,
and that he may be glorified in and among you.

Amen.
So fare ye well in the Lord.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 18th of the 12th month, 1681.

[.centered]
=== Epistle 360.

[.blurb]
==== To Friends in Carolina.

[.salutation]
Dear friends,

With my love to all the faithful and tender Friends in Christ, the holy seed,
that bruises the head of the serpent, (the cause of enmity,) in which seed no enmity is,
nor can come; for in this seed are all nations blessed,
which destroys the evil seed that brought the curse, and his cursed works and workers.
So let this seed Christ rule in all your hearts,
who was promised and prophesied of to come, who is come, and reigns, in whom is wisdom,
salvation, life, and glory over all, the first and last;
this seed doth live and reign over all that doth change and will have an end.
Now in this holy seed you enjoy the blessings, and your election in it,
which was before the world began.
Now in this holy seed is the treasure of wisdom and knowledge,
and as you all live and walk in this seed,
you will have wisdom and knowledge that is heavenly from this treasure;
with which wisdom and knowledge you will have understanding,
that all your conversations may be ordered by it aright, and to preach righteousness,
and holiness, and godliness, so that you may glorify God in your lives and conversations,
and all your words may be gracious, and seasoned with grace;
and whatever promises you may make to any man, you may consider before,
that you may perform them; that so your words may preach righteousness and truth;
so that you may be the lights of the world, and the salt of the earth,
that by your light shining, you may answer the light in all men; and by the grace,
and by the salt, you may savour that which is unsavoury; and so by your good works,
and keeping to the salt, and to the light shining,
you may be instrumental to open the eyes of others,
to know your Father which is in heaven, that they may glorify him.

And my desire is, that all Friends may keep low, and meek, and humble,
that he that doth inhabit eternity may dwell with you;
and that you may take upon you Christ`'s yoke,
that you may draw with his heavenly plough, that with it the earth may be turned up,
that hath oppressed and grieved the tender seed, and God`'s holy spirit;
so that God`'s plantations may be minded above the outward,
that his lilies and vines may grow, and bring forth fruit to his praise,
who giveth the increase.

And now, dear friends, keep in the love of God, which doth edify the body of Christ;
that will bear all things.
And be gentle, and courteous, and kind one to another in the fear of the Lord;
for there is no danger in keeping low; for the danger is to such that are high and lofty,
and puffed up.
Such will swell; and though they may have good words, and a form of godliness,
yet such that do so swell, will break out into bitter fruits, strife, and contention;
and such go out from the power of God and his spirit, and so out of the camp of God,
and then out of the unity of the spirit, which is the bond of peace;
and therefore all must keep in the holy spirit of God,
if they will keep in fellowship with the saints in light, and so keep the bond of peace.
For they that go from the spirit of God in themselves,
though they have the whole form of godliness, they break the bond of peace;
and such run into vain disputes, strife, and contention.
But there is no such custom in the church of Christ, which keeps the unity in the spirit,
which is the bond of peace.

And now, dear friends, in the name and power of the Lord Jesus Christ, and his spirit,
keep all your meetings for worship, and your meetings for business,
that you may see that all that profess the light of Christ, and his truth,
and have received it, that they do walk according to truth, and as becomes the gospel,
that the name of God may not be blasphemed amongst you.
And if that you of Ashly Cooper River, and that way, and Albemarle River, and that way,
had once a year, or once in a half year, a meeting together, it might do very well,
some where in the middle of the country, as you shall see meet,
as they have in Maryland and Rhode Island.
And if you had sometimes some meetings with the Indian kings and their people,
to preach the gospel of peace, of life, and of salvation to them;
for the gospel is to be preached to every creature;
and Christ hath tasted death for every man, and died for their sins,
that they might come out of death and sin, and live to Christ, that died for them;
who hath enlightened them, with the light, which is the life in himself;
and God pours out of this spirit upon all flesh; that is, upon all men and women.
And the grace and favour of God appears unto all men;
so that all may believe in his light, and walk in his holy spirit, and receive his grace,
which will teach them to live godly, etc. and bring them salvation;
so that you may come to see the light of Christ`'s glorious gospel set up in those parts.
And God hath promised he will lift up an ensign unto the nations.
And again, "`There shall be a root of Jesse,
which shall stand for an ensign to the people; to it the Gentiles shall seek.`"
And again, he saith, "`For the earth shall be full of the knowledge of the Lord,
as the waters cover the sea.`"
So, I desire that that part of the earth may be filled with the knowledge of the Lord.

And now, dear and tender friends, my tender desire is, that you may in nowise abuse,
neither by your words, nor by your lives nor conversations,
the liberty which God or the rulers have given you;
but in all things you may have an eye to God`'s glory,
that he may be glorified by you all, who is worthy of all, who is the Lord of all,
both in heaven and earth, blessed forever.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 361.

[.blurb]
==== An Epistle concerning the Government of Christ, and his Peace, of whose kingdom there shall be no end.

Concerning the government of Christ, and his peace,
"`of the increase of which there shall be no end, upon the throne of David,
and upon his kingdom, to order it, and to establish it with judgment, and justice,
from henceforth and forever.
The zeal of the Lord of hosts will perform this.`"

Now Christ Jesus, the second Adam, the Lord from heaven, it is he who rules, and reigns,
and governs in the hearts of his saints, who are the believers in his light,
(the life in him,) who is their governor and counsellor, who died for their sins,
and is risen for their justification, and is the captain of salvation.

And Christ`'s government in the hearts of his people, is by his grace and truth,
that comes from Christ Jesus, by whom all things were made,
who doth enlighten every man that cometh into the world, which light is the life in him;
he saith, "`Believe in the light,
that you may become the children of the light;`" and such have the light of life,
and by it come under Christ`'s government and peace, and his order in his light and life.
Now, they that hate his light, they hate the life in Christ the heavenly man;
and such will hate Christ by whom all things were made and created; and hate his order,
and his justice, and judgment, and his light and life:
and such are not like to come into his established government and kingdom; so Christ,
who is the governor, the counsellor, the orderer,
he orders and governs with his light (his life) in
the hearts of all the believers in the light;
and all the believers in the light, have the witness in themselves,
of Christ their ruler, counsellor, orderer, heavenly governor, and of his judgment,
justice, and peace; and that of the increase of his government there is no end.

Now, they that hate the light, which is the life in Christ the second Adam,
the Lord from heaven, they are those that would not have Christ rule over them,
nor in them; therefore it condemns them.
And, what is the matter that all men and women do not see, but are blind,
and are not in unity?
Is it not because they hate the light,
(the life in the second Adam,) and will not come to the light, nor walk in the light?
And then, is not the light their condemnation, who are in transgressing old Adam?
And, how are they like to see or believe, or have faith in Christ, that hate his light,
and will not come to it, which is the life in the second Adam?
And therefore all that hate his light (which is the life in him) are not like to see,
nor receive faith from him, that will not believe in his light, nor come to it,
but hate it; and such will hate both the divine faith and the author of it.
And therefore all that do hate the light (which is
the life in Christ) which he enlightens them withal,
they hate his order, they hate his government, his rule; yea, Christ the second Adam,
the Lord from heaven: and all such haters of Christ, his light, life, order, government,
and counsel, are in a false liberty,
though they may profess Christ or his government in words,
yet not believing in the light,
and walking in the light (the life of Christ) they
have no true fellowship one with another,
but are in confusion;
and have no true fellowship with the believers in
the light (the life in Christ) nor with the son,
and the Father; for, how should they?
For, until they come to believe in the light,
(the life in the second Adam,) they cannot see their own states,
they are in a blind state; for none see, nor enter into the kingdom of God,
till they are born again; and those that are born again,
are the believers in the light (the life in Christ) and so become children of the light,
grafted into Christ; and such do know and see the true liberty in Christ Jesus,
the second Adam: all such do see, and know, that all false liberty is out of the light,
(the life in the second Adam,) in old Adam in the transgression.

And Christ that doth enlighten every man that cometh into the world,
(which is the life in him,) such come to Christ, and are grafted into him the head,
and so hold Christ their head, by whom all things were made and created; who is over all,
from everlasting to everlasting, the first and the last, the beginning and the ending.
These are they that see his order, his government, and his rule in their hearts,
and receive his law of spirit and life, and live and walk in it,
which makes them free from the law of sin and death.
These see Christ to be the author and finisher of their holy, divine, precious faith.
And their faith stands in Christ, who is the author of it,
"`who hath all power in heaven and earth given to him.`"
And the mystery of this faith they hold in a pure conscience,
and do know the law of this faith,
and the law of love that God hath shed in their hearts through Jesus Christ.
And so in this light, faith, and life, that they have from Jesus the second Adam,
the Lord from heaven, they come all to be of one faith, of one light, and one life;
and so of one mind, heart, and judgment, in this new covenant of light and life;
so in it they are under the government, and counsel, and order of Jesus,
that he establishes in his everlasting covenant of light and life in their hearts.

The law came by Moses, and all the Jews were to be under the law in the old covenant;
and this law served till Christ (the seed) came, in his new covenant.
He is come, and now grace and truth are come by Jesus Christ, the great governor.
And now, this grace and this truth is come from him,
into the hearts of all his believers.

And with and in this grace and truth,
Christ rules in the hearts of them that receive his grace and truth;
and with this grace and truth, and in it,
every believer and saint receiveth Christ their governor, and his order, and his counsel,
and heavenly judgment, and justice from the heavenly man, in his established government,
which he establishes with his grace and truth.
Now this grace of God which brings salvation, which hath appeared unto all men,
which does manifest, that all men have a day of grace and favour:
now this must needs be the special grace of God, which brings salvation,
which hath appeared unto all men.
Now then, not receiving this grace and favour of God,
but turning from this grace into wantonness,
and walking despitefully against the spirit of grace; therein they are hardened,
and blind, and turn that into wantonness, and walk despitefully against it;
which should teach them, and bring their salvation.
And therefore such come to be blind, and hardened against the grace and favour of God,
that turn it into wantonness, as I said before,
and walk despitefully against the spirit of grace and truth;
and such turn against God and Christ, from whence grace and truth come,
and turn from and against his people that are established in the grace of God,
that brings their salvation.
Though such may profess God and Christ in words only, and his grace and truth,
their profession will come to nothing,
except they receive his grace and truth into their hearts.
They that do receive Christ in his grace and truth, which come from him;
they know his government in the truth, and in the covenant of grace; yea,
in their hearts, and know their gracious and true liberty in the grace and truth,
and in Christ from whence it comes, and his holy and heavenly order in his grace,
and his reign in their hearts.
And all such that walk despitefully against the spirit of grace,
and turn the grace into wantonness, though such may profess God and Christ,
their profession will come to nothing, and all their liberty is false, and in the flesh,
in old Adam in transgression.
For true liberty is in the grace and truth that is come by Jesus,
which leads up unto Jesus, from whence it comes,
in whom the everlasting true liberty is.

For Christ, who is the truth, holy and pure, he reigns in the truth, and in his grace.
And therefore every man and woman, must with this grace and truth in their hearts,
(which they have from Christ,) feel and see Christ`'s reign and rule in their hearts;
and him in his heavenly, eternal, everlasting government.

The Lord spoke by his prophet Joel, "`that it shall come to pass in the last days,
that God will pour out of his spirit upon all flesh,`" etc. Joel 2:28.

And Peter said, "`This is that which was spoken by the prophet Joel,
it shall come to pass in the last days,
(saith God,) that I will pour out of my spirit upon all flesh,
and your sons and your daughters shall prophesy; your young men shall see visions,
and your old men shall dream dreams; and on my servants, and on my handmaids,
I will pour out in those days of my spirit, and they shall prophesy.`" Acts 2:17-18.

Now it is God that pours out of his spirit upon all flesh, by which sons, daughters,
young men, old men, servants, and handmaids, have their visions, and prophecies,
and dreams.
And these last days are the days of Christ, in his gospel and new covenant.

It is said in the old covenant,
that God did pour out of his spirit upon the house of Israel, and the house of Judah.
But in the days of the new covenant of light and grace,
God poured out of his spirit upon all flesh, both Jews and Gentiles.
Now all flesh must come to the spirit of God, and be led and guided by it,
if they will see Christ`'s heavenly spiritual government and order; and with this spirit,
to know Christ the spiritual man, to rule and govern in their hearts.
And all that by this spirit are circumcised, they eat of the heavenly passover,
or their bread from heaven.
And all that are baptized with the spirit, are baptized into one body,
and do all drink into one spirit.
So here they are one, in this spiritual fellowship, which is the true church-fellowship;
even that church which is in God, the pillar and ground of truth,
which church Christ is the heavenly and spiritual head of; and well he may,
for he is the author of their faith, and the author of their light, and life, grace,
and truth, and spirit, and gospel of peace and salvation;
by which he rules in the hearts of his living members, the church.
And all they that grieve, vex, quench, and rebel against the spirit, come to be blind,
as the Jews, and will not see with their eyes, nor hear with their ears,
nor perceive with their hearts; and such may profess Christ in the new testament,
and the apostles`' words, and the government, and order of Christ;
as the Jews did profess the old testament, and Christ to come;
but they would not receive him then, when he was come.
No more do they now, that profess he is come, who vex and quench his spirit,
and grieve it, and rebel against it, and err from it.
And such are not like to receive Christ into their hearts,
nor come into his heavenly order, and establish peaceable government,
as those that are led by the spirit of God, which are the sons of God,
and keep the unity of the spirit;
which holy spirit is the bond of peace amongst all Christ`'s subjects, lambs, and sheep,
that feed together in the pasture of life.
For it is God that gives the heavenly understanding
of Christ`'s established government and order.
And they that quench, and vex, and rebel against the spirit of God,
will rebel against Christ`'s established government and order,
and his people that are in it, that are led by the spirit of wisdom and understanding,
and a sound mind.
And such as will not hear the spirit of God in themselves,
will neither hear God nor Christ, nor his sheep, nor such as he sends,
but rebel against them.

Now the gospel being preached to, or in, every creature under heaven;
which gospel is the power of God to salvation, to every one that believes;
so all that receive this gospel, the power of God unto salvation, in their hearts,
receive Christ, (the power of God,) and his government and order in the power.
And Christ reigns in their hearts in his power; and such come into the gospel order;
and they that come to be heirs of the gospel, the power of God to salvation,
are heirs of Christ`'s peaceable established government,
and are true subjects to Christ`'s power, and established peaceable government;
and so this gospel, the power of God to salvation, is peaceable, joyful, and comfortable,
which is the gospel of Christ, the second Adam, the Lord from heaven;
and is not called the gospel of old Adam in transgression.
And this gospel, which is the power of God unto salvation, keeps all that believe in it,
in the everlasting joy, peace, and comfort, and in order;
for it is the everlasting gospel, which brings life and immortality to light,
by which they see over the devil, and before he was, that hath blinded them,
and darkened them from life and immortality.
So in this gospel that hath brought life and immortality to light in God`'s people,
both men and women, they are established in the order of it,
in which they do serve the eternal everlasting God of truth.

Now all they that do not receive the gospel of Christ, the power of God to salvation,
which is preached to every, or in every creature under heaven,
life and immortality are not brought to light in them;
and such the God of the world hath blinded,
(and so they remain blind under the god of the world,)
and such are blind concerning the order of the gospel,
and are ignorant of their salvation, and of the joy, and comfort,
and peace of the gospel; neither can they serve God in the gospel,
though they may profess Christ, and his gospel in words, yet such have no comfort of it.
And therefore such as disobey the gospel of Christ, the power of God to salvation,
and will not receive it, nor believe in it,
how can they receive the order of the gospel of Christ, the heavenly man,
from whence the gospel comes; or to receive him to reign in their hearts,
when they will not receive his gospel, the power of God to salvation, in their hearts?
And again, how can they receive his people, or believe his people,
that are in the order of the gospel of Christ, and have received it,
and him in their hearts, who disobey it, and will not receive it in their own hearts?
Such are not like to come into the order of the gospel, that disobey it.
Such will disobey Christ, and will not regard his people, in whom he reigns,
who walk in the order of his gospel, the power of God unto salvation.

Now it is Christ the second Adam, that lighteth every man that cometh into the world,
with the light, (which is the life in himself,) and all that believe in the light,
and become children of the light, and walk in it, walk in unity and fellowship,
and in the order of the light and government of Christ; in such Christ doth reign.
And all those that hate this light, and will not come to it, nor believe in it,
are condemned by it.

Now, "`the grace of God that brings salvation hath appeared unto
all men;`" and all men that receive this grace and truth,
that is come by Jesus, they receive Christ from whence it comes, in their hearts,
to be their teacher and their salvation; and so come into Christ`'s government and order,
in the truth, and into the covenant of grace.
And they that hate the truth, and turn from the grace into wantonness,
and walk despitefully against the spirit of grace, they turn against Christ,
his order and government, and his power also.

And God pouring out of his spirit upon all flesh: all that are led by the spirit of God,
and Christ, are the sons of God;
and such are obeyers of Christ`'s spiritual order and government.
And they that quench the spirit of God, and rebel against it,
rebel against Christ`'s order and government, and him in his people;
and their spiritual fellowship, and the gospel of salvation,
being preached to every creature under heaven; which gospel is the power of God,
every creature under heaven must receive this gospel in their hearts,
if they receive Christ and his government; and his order of the gospel,
and him to rule in their hearts.

And all you that have received it, have received the comfort of it;
and those that disobey and rebel against the gospel, the power of God,
such disobey and rebel against God and Christ, and his government,
and his people who are in the order of the gospel, the power of God.

And as it is said, "`Christ is in you,
except you be reprobates;`" and all that receives Christ in them, it is by his light,
(which is the life in him) and the grace and truth that comes by Jesus,
and the faith that he is the author of, and his spirit and gospel.
This they must receive in their hearts, if they receive Christ in them.

And Christ said to his disciples and followers,
that he would send them the spirit of truth,
(the comforter,) which should proceed from the Father and the son,
which should lead them into all truth; and he should reprove the world of sin,
righteousness, and judgment.
So that which leads the believers and disciples of Christ into all truth,
and is their comforter, is the reprover of the world of their sin, righteousness,
and judgment.
So here that which is the world`'s reprover, is the saints`' comforter,
and leader into all truth, and so into all true fellowship, and true liberty.
And this holy spirit, and comforter, does not proceed from old Adam,
nor any of his followers, but from the Father and the son.
And so every one is to have oil in your own lamps, from the heavenly olive tree,
that your lamps may burn always, both night and day, in your tabernacles,
looking to your high priest, who will feed your lamps with heavenly oil.

And every one have heavenly salt in yourselves to savour withal, what is earthly,
and what is heavenly; and what is from below, and what is from above;
and what is out of the truth, and what is in the truth.

And that every one may keep their own vine in their own garden,
and their own lily in their own field, or orchard;
which lily doth exceed Solomon in all his glory.
And every one have the word of faith in their hearts and mouths, to obey and do,
which will sanctify, and make you holy, and reconcile you to God.

And every one have the anointing, or unction, within you, which you have from the Father,
or Holy One; so that in it you may continue in the Father, and in the son.

And every one continue in the grace of God, which will teach you how to live,
and what to deny, and will bring your salvation, and establish you upon Christ,
the rock and foundation, from whence the grace does come.

And every one abide in the holy, divine, and precious faith,
which you do hold in a pure conscience, by which faith you do live,
and have victory over that which displeaseth God: and in this faith you do please God,
which Jesus Christ, the Lord from heaven, is the author and finisher of.

And every one that hath digged deep, and found the pearl of great price;
and hath sold all, and purchased the field, then the field and pearl is your own:
such do know a thorough redemption.

And all you believers in the light,
(which is the life in Christ,) that are become the children of light, walk in the light,
and in Christ, as you have received him.

And every one mind the heavenly leaven, that will leaven you into a new lump.

And every one keep the feast of Christ our passover, with his heavenly unleavened bread,
in sincerity and truth.

And every one mind the light, that God hath commanded to shine out of darkness,
and hath shined into your hearts,
"`to give you the light of the knowledge of the glory of God in the face of Jesus Christ,
(your saviour,) that the excellency of the power may be of God,
and not of yourselves;`" in this you are sensible
of his heavenly treasure in your earthly vessels;
and every one have water in your own wells and cisterns,
and heavenly fruit on your trees, which God hath planted.

Nebuchadnezzar, though his greatness reached to heaven, as a tree,
yet he was to be "`hewn down,
until he knew that the Most High ruleth in the kingdoms of men:
and the God of heaven shall set up a kingdom which shall never be destroyed;
and the kingdom shall not be left to other people.`" Dan. 2:44.
"`And the stone that smote the image became a great mountain,
and filled the whole earth.`"
Ver. 35.

"`They shall not hurt nor destroy in my holy mountain:
for the earth shall be full of the knowledge of the Lord, as the waters cover the sea.`" Isa. 11:9.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 27th of the 8th month, 1681.

[.centered]
=== Epistle 362.

[.blurb]
==== To Friends in Jamaica

Dear friends, with my love in the Lord to you all: it hath been often in my mind,
from a sense of the spirit of the Lord; which thing I shall lay before you,
and commend it to the witness of God in all your consciences.

The thing is this: that if you had (once in a year) a Yearly Meeting,
as they have in Holland, Germany, and Friesland, and at Rhode Island, and in England,
and elsewhere, which is, and hath been, of great service; for Friends to see one another,
and know how the affairs of truth prosper, and how Friends do grow in the truth of God,
to the comfort and joy of one another in it; in which the Lord Jesus Christ is exalted.
And if there should be any difference among Friends,
it may be ended at the Yearly Meeting, by some Friends out of the meeting,
which could not be ended at other meetings.
So that all things (by the truth and power of God) may be kept in peace and love,
all dwelling in the wisdom of God, that is from above, which is pure, and peaceable,
and gentle, and easy to be entreated.
And so for you once in a year to meet together in the Lord`'s power,
and to wait upon him in his spirit and truth one day,
and then another day you may have a Yearly men and women`'s meeting in the Lord`'s power;
which in time you may find and feel a great service in the Lord`'s spirit and power;
in which you may feel his presence and blessing flow among you.
And as for place and time, I shall leave it to your best convenience;
and the Lord direct you, that you may do all things, whatever you do, to his glory.
For you know that in other countries, or provinces,
they have either Half-Year Meetings or Yearly Meetings, except it be in Jamaica,
which several times hath been in my mind for you to have one there;
for where they are settled, they see a great service in them;
and the Lord hath owned them, and honoured them with his presence,
and that keeps all in a sense of a care of his glory, and a care of one another,
that they may be kept and preserved in God`'s eternal truth, in meekness, in gentleness,
and in tenderness, and in love, that edifies the body of Christ, the second Adam,
the Lord from heaven.
And so that all of you, in godliness, holiness, and righteousness,
may spend your days to the glory of God; that your conversations may be in heaven,
and not below in the earth, among the wicked; that the Lord God,
and his son Christ Jesus, may be glorified in you all, who is over all, blessed forever.
Amen.

And, friends, it would be very well, if that you brought on your case of not swearing,
and taking oaths, which hath been lost through that spirit which was unfaithful:
now the same governor is come over again,
in whose time (when he was there formerly) that act was obtained at the assembly,
in which your yea and nay was taken instead of an oath and swearing.
Therefore, see if you can prevail with this governor and his assembly,
to have the same act renewed again,
and to clear yourselves from that spirit which was the cause that the act was repealed.
So with my love in the Lord Jesus Christ to you all.

And my desires are, that you may all be preserved in God`'s power, to his glory;
and that you may grow in the truth,
and with the truth answer the truth in every one`'s inward parts;
so that ye may spread the truth abroad,
and that with it your hearts may be united together.
And walk in it, and in the love of it; for love edifies the body of Christ.
And that ye may be good examples in the truth, and in righteousness and holiness,
and show forth christianity in the possession of it, above the outside professors.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
From Dolston, the 24th of the 7th month, 1682.
