== Epistles 363 &#8212; 375

[.centered]
=== Epistle 363.

[.blurb]
==== To Friends in Holland.

Friends and brethren, in the holy seed of life, that reigneth over all; in it walk,
and in the power, and spirit, and truth of God,
that you all may be as a city set upon a hill, that cannot be hid;
and the salt of the earth, and light of the world, to answer the light of Christ in all,
and be a good savour in them that are saved, and in them that perish.
And all live in love, that beareth all things, and doth edify the body of Christ,
and grow up in him, your head and life; and be kind, and courteous,
and tender in affection to one another, and walk as becometh the gospel of Christ,
the power of God.

And, dear friends, this Yearly Meeting the Lord`'s power was over all,
and his seed of life;
and the Lord`'s living refreshing presence was among us in all our meetings.
And your epistle from your Yearly Meeting in Holland was read,
to the refreshing of Friends; and another from the Half-Year`'s Meeting in Ireland;
and a testimony from Scotland, that Friends are in love and unity there,
and the truth prospereth and spreadeth; and by letters from America,
that Friends are pretty well there; and at Algiers, in the Turks`' country,
Friends have set up a meeting, about twenty that are captives, among themselves;
and a Friend that is a captive, declareth the truth there among them;
and their masters do let them meet, and it may be of great service there.
And the Lord`'s power is over all, and in it be valiant for God`'s truth upon the earth,
and spread it abroad; and that you may all in humility, exalt the Lord,
and that the presence of God, and his son, may be among you all;
and so the blessing of the Lord be among you all.
Amen.

[.signed-section-signature]
G+++.+++ F.

London, the 17th of the 4th month, 1682.

[.centered]
=== Epistle 364.

[.blurb]
==== To Friends in Barbados.

[.salutation]
Dear friends,

In all your meetings, see that the Lord God be glorified, and have an eye to his glory,
and let all things be done without strife or reflections;
but all to mind the testimony of life, and that which doth preserve your unity in it;
and in that you will seek one another`'s good, and not slight one another;
but to esteem one another in the truth, and keep low in humility,
for such God will exalt.
And be kind and tender-hearted one to another, and dwell in the love of God,
that he doth shed abroad in your hearts;
for that love which cometh from God doth edify the body of Christ.
And therefore you must be of a noble spirit, that are of the noble birth,
born of the spirit; and to love the brotherhood in the spirit,
and to esteem all men and women, as they are God`'s creation;
whose natural sun shineth and rain falleth upon the just and unjust,
and on their natural fields;
and so doth God`'s eternal son of righteousness shine with his light, and grace,
and spirit, that he doth enlighten them withal, and gives his grace and peace to all;
for his spirit is poured out upon all.
Thus doth he shine through all, and upon all, and over all, and above all;
and therefore let your light shine, that are the believers in the light,
that are become the children of the light,
that others may glorify your Father which is in heaven in seeing your good works,
and your good and gracious words, and lives and conversations;
and mind the more excellent way the apostle showeth to the Corinthians,
which is the charity that will bear all things, and is not puffed up, nor envieth not.
This doth keep above all brittleness.

And, friends, after that your meetings are settled and seasoned by the power of the Lord,
if you do alter them, without the consent of Friends in the power of the Lord,
that makes and breeds discontent; and therefore keep them, after they are settled,
in the power of the Lord,
(and you settled in it,) upon Christ the holy rock and foundation of God,
that standeth sure.
And in all your meetings, if there be any difference between brother and brother,
do not reflect one upon another in meetings, but speak one to another between yourselves,
as Christ commands; and then you may preach the gospel of peace freely,
and speak the truth in the love of it, as it is in Christ Jesus.
And this is the best way; so that nothing may be seen in your meetings but the life,
truth, and peace; so that the serpent, whose meat is dust,
may find none in your meetings; and none to quench nor abuse the power or spirit,
nor any to go beyond its motion; for, if you do,
you will both bring trouble and burdens upon yourselves, and others, and run out,
that so you can hardly get in again.
And therefore be wise in the heavenly wisdom of God,
to be ordered in his spirit of understanding, to the glory of God,
and the comfort and edify of his people;
that you all may know how to behave yourselves in the church of God, to the glory of God.
And let all your lives and conversations preach virtue, purity, righteousness, holiness,
and godliness, else you cannot be the lights of the world, nor the salt of the earth.
And when any do badly or wickedly, they, instead of being lights or salt, are unsavoury,
and are stumbling blocks; and when the salt hath lost its savour, it is good for nothing,
but to be trodden under the foot of men; and therefore keep your savour,
and then you will not come under the foot of men; and in the light,
and then you will not go into darkness.

And therefore have salt in yourselves, and oil in your own lamps,
and keep in your own houses,
(for it is the whore that abideth not in her own house,) with the word of life,
and grace, and truth within, and to the light and purifying faith,
and mortifying and baptizing holy spirit of God; the fruits of which spirit are love,
peace, long suffering, gentleness, meekness, temperance.
And bear one another`'s burdens, and so fulfill the law of Christ;
and forgive one another, as Christ hath forgiven you;
and strive to excel one another in holiness, and righteousness, and godliness,
and meekness, and modesty, in virtue, truth, and love,
that you may all live to the praise and glory of God.
Amen.
And the Lord saith, Isaiah 49:8. speaking of Christ,
"`I will give thee for a covenant of the people, to establish the earth,
to cause to inherit the desolate heritages.`"
So that you may see the fulfilling of this in the promise,
and have a care of God`'s glory; and all live in the seed Christ, your sanctuary,
which is a safe place, over all storms, and destroyers, who was before they were,
and will be when they are gone; in whom you all have rest and peace;
and by whom you are presented to God, holy in body, soul, and spirit.
And therefore all must be kept clean and holy, if that they do offer up,
or be presented to him that is holy; and therefore you must be a holy people,
and walk in the holy truth, and obey the holy word of God, and walk godly,
as the grace of God teaches, which brings salvation, and walk in the light;
if that you do keep in the fellowship, in the heavenly light.
And in this you do differ from the world that make
a profession of the scriptures of truth,
and dishonour God, and cause his holy name to be blasphemed,
by their not obeying the word, nor walking in the light, spirit, grace, and truth,
whose candle is gone out, and now cannot endure to hear talk of the light.
And therefore "`let your light so shine before men, that they may see your good works,
and glorify your Father which is in heaven;`" and then you will have his favour,
presence, and blessing; and the Lord God Almighty preserve you all,
and Friends everywhere, in his power and seed Christ Jesus.
Amen.

[.signed-section-signature]
G+++.+++ F.

The 26th day of the 8th month, 1682.

[.centered]
=== Epistle 365.

[.blurb]
==== To Friends in New Jersey and Pennsylvania.

[.salutation]
Dear friends,

With my dear love to you all, in God`'s holy peaceable truth; and my desires are,
that you may be all kept careful of God`'s glory.
Now in your settling of plantations and provinces, and especially in woody countries,
as those are, you may have many trials and troubles;
but if you keep in the wisdom of God, that will keep you gentle, and kind,
and easy to be entreated one of another, that will preserve you out of heats,
or extremes, or passions; and that all Friends that come over,
be with speed settled in their plantations, that they may not lie and waste their time,
both of themselves and their servants,
and spend that which should help to settle them in their plantations.
And therefore you that are concerned in ordering those things,
have a care that no reproach come upon yourselves, and your countries;
but there may be such care taken in all things,
that there may be no complaints come into England against you.

And I desire that you may be very kind, and courteous, to all in necessity,
in the love of God; for there are many people go over to your countries,
some poor and some rich; and so, many eyes are upon you, and them that come over to you;
and therefore my desire is, that you may all be careful in the love of God,
and in his truth and righteousness, as the family of God;
and be careful and tender to your servants, in all respects,
that there may come no complaints from them or others;
that so in all things you may be ordered by the wisdom of God,
that his blessing may be amongst you.

And, dear friends,
I desire that you would send over an account by the next ship how many meetings you have,
and how many meetings monthly, of men and women, and how many Quarterly Meetings,
and Half-Year Meetings; and let us know how truth spreads and prospers amongst you;
which you would do well to write over every year, to the Yearly Meeting at London.
So, with my love in the seed, which reigns over all,
in whom you have all life and salvation, and peace in the Lord God.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 366.

[.blurb]
==== To Friends that are Prisoners in York.

Dear friends, with my love to you, and all the rest of the faithful Friends in bonds;
and my desire is to the Lord,
that ye all may stand faithful and valiant for his glorious name,
and his holy peaceable truth, now in this day of storm and tempest,
that none may turn their backs on the Lord in this day of trial,
and none may be ashamed of confessing of Christ before the adulterous generation,
as Christ said, lest Christ be ashamed of them before his Father,
and before his holy angels.
And therefore now is the time and day of your trial; for the Lord is just;
though I know that the faithful and innocent, just, and righteous must stand it out.
And therefore mind the Lord in all your sufferings, and keep all low,
and in the humility of heart, and there you will feel that he that inhabits eternity,
dwells with an humble heart, and he will be your shield and buckler,
and defender in time of trouble.
And the Lord hath promised to deliver his people in the six troubles, yea,
in the seventh, the perfection of troubles; and therefore do not think time long,
and your sufferings long,
for the Lord will lay no more upon you but what you are able to bear; yea,
upon his faithful people.
I know it, and am a witness for God in all my sufferings and imprisonments,
and haling before magistrates about sixty times, about these thirty-six years.
And so, friends, when you are tried,
you may come forth more precious than gold that is tried in the fire;
and keep the word of patience,
and it will keep you from the temptations that come upon the world to try them;
for the word of God was before the world was.
And though you be in outward bonds from your wives, families, houses, and relations,
yet the word of God is not bound, neither can they bind the word of God;
it is at liberty, it abides and endures forever; it will make you all rich,
though they think to make you poor with their bonds, and cast you into prisons; but,
I tell you, the word of God will make you rich,
for the word of God was before the wicked and his bonds were;
for in the beginning was the word, but since the beginning was the devil,
who had cast some into prison, spoken of in Revelations:
that ten days might be a longer time than ten natural days.
For they that will live godly in Christ Jesus shall suffer persecution by the ungodly;
for it was the just that suffered by the unjust in all ages; and Christ said to Saul,
"`Why persecutest thou me?`"
So they that stood in Christ, and were in Christ Jesus,
it was Christ that was persecuted, as well as they in whom he reigned.
And do not you understand, and know,
the sufferings and trials the holy men of God went through;
and how by faith they subdued the mountains; and consider the faith of Abraham, Isaac,
and Jacob, and the faith of Abel, and Enoch, and Noah, and the faith of Jeremiah,
and the rest of the prophets, and the faith of Daniel, and the three children,
and the faith of all the apostles, what sufferings and imprisonments they went through;
and consider all the martyrs since the apostles`' days,
consider what sufferings they have gone through;
and God and Christ is the same to uphold you, that are given up in his spirit, power,
and faith, to stand for his glory; and be valiant for his truth and name upon the earth.
And therefore keep in your sanctuary, Christ Jesus, who destroys the destroyer,
and bruises the serpent`'s head; and so in Christ Jesus, your sanctuary,
you all are in safety, in whom you have all life, and salvation, and peace with God,
in him you may all triumph and rejoice with exceeding great joy, and say,
"`What shall separate us from the love of God which we have in Christ Jesus?`"
And the apostle said to the saints in their days,
that "`there was not any thing able to separate him from the love
of God in Christ Jesus;`" you feeling the same love,
you feeling the same faith to dwell in you, and walk by;
"`for the just shall live by faith,`" which is his victory, and hath access to God,
in which he pleases God.
And so with my love to you all in Christ Jesus, who was before the devil was,
that makes you to suffer, and will be when he is gone.
In Christ you have heavenly peace, that none can take away from you;
in him dwell and live.
Amen.

[.postscript]
====

Postscript.--And all be faithful in their testimony of life, against riches,
and all those things which have come up in this night of apostacy, from the light, life,
and power of Christ and God, against all looseness whatsoever,
that the heavenly camp of God may be kept holy, clean, and pure.

And all Friends, look at the Lord above all your sufferings, and trust in him,
who with his eternal power hath preserved you to this day;
and the Lord in his glorious power was with us in all our assemblies,
at this Yearly Meeting; he over all hath the dominion,
and over all evil spirits gave dominion to his people.
Glory to his name forever.
Amen.

And therefore let your faith be in the gospel, the power of God,
which hath brought life and immortality to light in you.

====

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 367.

[.blurb]
==== To all the elect of God, chosen and faithful, who have known the work of the Lord, and his dealings, and his eternal hand, his spirit and power, in preserving of you to this day, and in this glorious gospel day of Christ Jesus; who are built upon him, the holy rock and foundation of God, that standeth sure, and are fed with the heavenly bread, and feel the springs of living water, and enjoy the presence of the Lord, who daily gives the increase.

And now, friends, with the eternal power, and heavenly light of Christ,
with it you have seen, and do see, and will see, that which Christ hath spoken, Matt. 13.
and Luke 8. which he taught to the great multitude in parables,
when he sat in a ship; "`Behold,`" saith Christ, "`a sower went out to sow his seed,
and as he sowed, some fell by the highway side, and it was trodden down,
and the fowls of the air devoured it: and some fell upon the rocks, or stony places,
where they had not much earth, and as soon as it was sprung up, it withered away.`"
So he that receiveth the seed into rocky and stony places,
the same is he that receiveth the word with joy, yet hath he not root in himself,
but endureth for awhile, or for awhile believeth, and in temptations falleth away;
for when tribulations or persecutions arise because of the word,
by and by he is offended;
and upon too many such have we seen this parable fulfilled in times of persecutions,
and tribulations, and sufferings; when the heat of persecution is up, they are scorched,
and withered away, and so come to nothing.
"`And some fell among thorns,
and the thorns sprung up and choked it.`" And they
also that received seed among the thorns,
are they that hear the word, and when they have heard, go forth,
and are choked with the cares of this world, and deceitfulness of riches,
and pleasures of this life, and become unfruitful, and bring no fruit to perfection.
And this is seen to be the condition of too many.
But the other "`fell into good ground, and brought forth fruit, some thirty, some sixty,
and some a hundred fold.`"
So they that received the seed into the good ground,
are they who (in an honest and good heart) have heard the word, and understand it,
and keep it, and bring forth fruit with patience, some a hundred fold, some sixty,
some thirty, as was said before.
These are the honest and good hearts, upon whom Christ, the son of righteousness, shines,
that nourishes his good seed, who brings forth fruit unto perfection,
who live over the deceitful riches and cares of the word,
and the pleasures of this life that pass away;
who are not offended nor moved at tribulations and persecutions,
but patiently do endure them; such do bring forth fruit unto perfection, yea, a hundred,
sixty, thirty fold in Christ Jesus,
who bruises the head of the serpent that makes men and women`'s hearts like the highway,
thorny, rocky, and stony ground.
For men and women, whose hearts are like unto the highways, stony,
rocky and thorny ground, the seed hath fallen into these grounds,
(as before,) and from these grounds all can talk of the seed, and of the word,
but bring forth no fruit unto perfection.
And therefore let all consider what ground you are, and what fruit you bring forth;
and when ye hear the word of the kingdom, that ye understand it, which none can,
without the light and spirit of Christ,
(and walk in it,) but he that shall endure to the end in the light, in the grace, truth,
and spirit, and in Christ, from whom you do receive these, shall be saved.

For the apostle saith, "`The just man lives by faith.`"
And this is not by any faith which men make,
but by the faith which Christ Jesus is both the author and finisher of,
in your hearts and consciences; and in this faith ye have access to God,
and do please him.
But, "`if any man draw back,`" (to wit,
in not living by this faith,) doth not the Lord say,
"`My soul shall have no pleasure in him?`"
But we are not of them who draw back unto perdition,
(that is a sad drawing back,) but of them that believe, to the saving of our souls.

[.signed-section-signature]
G+++.+++ F.

From Kingston upon Thames, the 2nd of the 9th month, 1682.

[.centered]
=== Epistle 368.

[.blurb]
==== In epistle to all planters, and such who are transporting themselves into foreign plantations in America, etc.

My friends, that are gone, and are going over to plant,
and make outward plantations in America, keep your own plantations in your hearts,
with the spirit and power of God, that your own vines and lilies be not hurt.
And in all places where you do outwardly live and settle, invite all the Indians,
and their kings, and have meetings with them, or they with you;
so that you may make inward plantations with the light and power of God,
(the gospel,) and the grace, and truth, and spirit of Christ;
and with it you may answer the light, and truth, and spirit of God, in the Indians,
their kings and people;
and so by it you may make heavenly plantations in their hearts for the Lord,
and so beget them to God, that they may serve and worship him,
and spread his truth abroad.
And so that you all may be kept warm in God`'s love, power, and zeal,
for the honour of his name.
That his name may be great among the heathen, or Gentiles; and ye may see over,
or be overseers with the holy ghost,
which was before the unclean ghost got into man and woman.
So with this holy ghost you may see, and oversee,
that the unclean ghost and his works may be kept out of the camp of God.
So that his camp may be holy, and all the holy may come into it; and he, who is holy,
may walk in the midst of you his camp, and be glorified in and among you all,
who is over all, and worthy of all glory, from everlasting to everlasting,
blessed and praised forevermore.

"`From the rising of the sun, even to the going down of the same,
my name shall be great among the Gentiles.
And in every place incense shall be offered unto my name, and a pure offering;
for my name shall be great among the heathen, saith the Lord of hosts.`" Mal. 1:11.

"`The Lord reigneth, let the earth rejoice, let the multitudes of the isles be glad;
let everything that hath breath praise the Lord,
for the Lord taketh pleasure in his people.
He will beautify the meek with salvation.`"
Psalm 97, 98. and 149. cl.

[.signed-section-signature]
G+++.+++ F.

London, the 22nd of the 9th month, 1682.

[.centered]
=== Epistle 369.

[.blurb]
==== To all Christians, to keep to yea, yea, and nay, nay, and to fulfill their words and promises.

All my dearly beloved friends and brethren everywhere, the Lord God Almighty,
with his holy power and spirit, hath gathered, and kept,
and preserved you to this day a people to himself.
And now, dear friends and brethren, in all your words,
in all your business and employments,
have a care of breaking your words and promises to any people; but that you may,
(before you make any promises to any man or woman,) consider before hand,
that you may be able to perform and fulfill both your words and promises to all people,
that you make your promises, or give your word unto.
And that your yea be yea, and nay, nay, in all things,
which Christ hath set up instead of an oath; yea, above an oath and swearing,
in his new covenant and testament.
And the apostle James holds forth the same doctrine.
And this yea, yea, and nay, nay, was set up when they forbid all oaths and swearing.
And therefore every one`'s yea should be yea, and every one`'s nay should be nay,
and so to stand.

And therefore all are to consider beforehand, before they speak their yea, yea,
and before they speak their nay, nay, in the new covenant of grace, light, and life;
that with the light they may see safely when they speak their yea, yea, and their nay,
nay, which is the practice of the children of light in the new covenant of light;
by and in which light they see and consider what they are able to perform,
what they speak at yea, yea, and what they are able to stand to at nay, nay.
So if you walk in the light,
it will preserve you out of all rash and hasty words and promises, which many run into,
that do neither perform their yea, yea, nor their nay, nay.

Therefore in the new covenant of grace, light, and life, all are to speak yea, yea,
to what they can do and perform; and what they say nay, nay to, that in the light,
and life, and grace of God they may like, wise stand to their nay, what they say nay to.

So that none make any promise, or speak yea, yea, or nay, nay, rashly,
which they cannot perform:
for such kind of inconsiderate and rash speaking
is not in the everlasting covenant of light,
life, and grace.
Take heed, lest you be numbered among the covenant breakers, spoken of, Rom. 1:31.
and such truce-breakers, which the apostle speaks of, 2 Tim.
"`Which have a form of godliness, but deny the power thereof;
from such turn away,`" saith the apostle.
And therefore they that deny the power of godliness, will not be faithful to God nor man;
and such cannot exercise a good conscience to God, in obedience to him, nor to man,
to perform that which is just, righteous, and honest.
Therefore the apostle exhorts the christians in the New Testament,
to "`speak the truth in love, and to put away lying,
and to speak every man the truth to his neighbour.`" Eph. 4:15,25.
And David saith, "`Who shall abide in thy tabernacle,
and who shall dwell in thy holy hill?
He that walketh uprightly, and worketh righteousness,
and speaketh the truth in his heart: but they that speak vanity,
every one to his neighbour, with flattering lips and a double heart,
the Lord shall cut off.`"
And Solomon, speaking of wisdom, says, "`My mouth shall speak truth,
and wickedness is an abomination to my lips.`"
And James says, in his general epistle, "`So speak ye, and so do,`" etc.
So see here how certain and steadfast the holy men of God
would have God`'s people to be in their words and doings.
And also James was careful,
that the saints in their very outward dealings were to be just,
and reproved such for saying, "`Today or tomorrow we will go into such a city,
and continue there a year, and buy, and sell, and get gain:
whereas they did not know what should be on the morrow.
But they ought to say, if the Lord will, we shall live, and do this or that.`"
Therefore you may see how careful the apostle was,
to keep all true christians in the fear of the Lord, and in the sense of his will.
God is true and faithful to his people in all generations;
and so he would have his people to be true and faithful to him, and to one another,
and to all men in his spirit and truth.
And Christ saith, "`He that is faithful in that which is least, is faithful also in much;
and he that is unjust in the least, is unjust also in much.`"
And further he saith, "`If ye have not been faithful in the unrighteous mammon,
or riches, who will commit unto you the true riches?`"
Therefore there must be a justness and faithfulness
in the outward riches between man and man,
if you will have a place in your hearts for the true heavenly riches:
the inward faithfulness to God bringeth forth faithfulness to men in outward things.
And as the apostle said to the saints, '`Finally, brethren, whatsoever things are true,
whatsoever things are honest, whatsoever things are just, whatsoever things are pure,
whatsoever things are lovely, whatsoever things are of good report;
if there be any virtue, and if there be any praise,
think on these things:`" which are very good things to be minded, thought upon,
and practised by the church of Christ.
The Lord saith by Zechariah, "`These are the things that ye shall do:
speak ye every man the truth to his neighbour,
execute the judgment of truth and peace in the gates.`"
Again, Therefore, saith the Lord, "`I am returned unto Zion,
and will dwell in the midst of Jerusalem; and Jerusalem shall be called a city of truth,
and the mountain of the Lord of hosts, a holy mountain.`"
And if outward Jerusalem was called so in the days of the old testament,
surely much more is heavenly Jerusalem, in the new covenant and testament,
called "`the city of the living God,
the heavenly Jerusalem;`" into which nothing that is unclean can enter;
but all the believers in the light, and the children of the light, enter into it,
whose names are written in the Lamb`'s book of life;
and are to walk in truth and righteousness,
and speak the truth every man to his neighbour, according to the apostle`'s doctrine.

And so, as every one hath received Christ Jesus, who is the truth, walk in him the truth,
and speak the truth, as it is in Jesus.
"`For you are bought with a price,
therefore glorify God in your bodies and in your spirits, which are his.`"

And the Lord in mercy grant, that all his people,
(who profess his name,) may do so to his praise, to his glory, and to his honour,
over all forever.
Amen.

And do not slight the form of sound words in truth: you who have bought the truth,
do not sell it.
And "`he that orders his conversation aright shall see the salvation of God.`"
And the apostle says to the Phillippians,
"`Let your conversation be as it becometh the gospel of Christ:`" for the apostle says,
"`our conversation is in heaven,`" where must be
the conversation of all the true followers of Christ,
that are built upon him the rock and foundation, who is from above.
And the Lord God establish all his people upon this
rock and foundation which standeth sure,
that upon him they may stand fast with the grace and truth that come from him.
Amen.

[.signed-section-signature]
G+++.+++ F.

Edmonton, in Middlesex county, the 23d of the 11th month, 1682.

[.centered]
=== Epistle 370.

[.blurb]
==== A way to prevent the indignation and judgments of God from coming on a kingdom, nation, or family; commended to the consciences of all concerned.

First, all you vintners that sell wine, that keep taverns, or such-like houses;
and all you innkeepers, and you that keep victualling-houses, ale-houses,
strong-water shops, etc. see that you never let any man or woman have any more wine, ale,
strong drink, brandy, or strong water`'s, or other strong liquors,
than what is for their health and their good;
in that they may praise God for his good creatures.
For every creature of God is good, and ought to be received with thanksgiving.

But if you do give, or let men or women have so much wine, brandy, strong liquors,
strong beer, or ale, till they be drunk, or to make them drunk:

1+++.+++ You destroy the good creatures of God.

2+++.+++ You destroy them that have not power over their lusts, no more than a rat or a swine,
who will drink till they are drunk.

3+++.+++ You are a great cause of ruining them in their healths, purses, and estates,
(their children and families) in feeding of them in their lusts,
by letting them have more than doth them good;
which also tends to bring God`'s judgments upon you, to your own ruin and destruction.

For many when they are full of wine, beer, or strong liquors,
then they will call for music, pipe, and harp,
(and it may be their whores also:) and so in this, you that suffer or allow such things,
are nursers of debauchery, and corrupters of them, and of your own families also.

And also such men, when they are full of wine, or strong liquors,
and have destroyed the creatures, by taking more than doth them good,
then they are got to that height that they are ready to quarrel and abuse,
or kill or destroy one another; and sometimes kill other people,
(who do them no harm) as they are walking or travelling in the streets or highways.
For when they are overcome by strong liquors, then they are fit,
and do lie open to all manner of wickedness.

And though you think by selling or letting people have wine or strong liquors,
more than doth them good, or is for their health, the more they drink,
the more gain you think it brings you; and the more you vend your goods,
the more profit you get.
Ah! poor sellers! do not you think,
that God with his all-seeing eye doth behold you and your actions?
And cannot the Lord soon bring a blasting upon all your undertakings,
and such ungodly gain and profits, and whatsoever you have gained by your covetousness,
and from the lusts of others, through which they do destroy their estates, children,
and families?
Will not this bring destruction upon you and your unrighteous gain,
which you have gotten by feeding their lusts?
For that which feeds the destroying lust must needs be destroyed;
and the profit of that will not be gain to you in the end.

For, are not you sensible, how many, after they have spent their estates,
or part of them, will run into your debts for wine or strong liquors, yea,
such as you let have more than did or doth them good?
And is not this the cause, that many break by trusting, and other ways,
as before mentioned?
Trust should be with that which is trusty, which doth not waste or destroy;
and such God will bless.
And therefore take heed of letting man or woman have any more wine or strong liquors,
than what is for their nourishment, health, and good.

See what a dreadful woe the Lord pronounced against them,
"`that rise up early in the morning, that they may follow strong drink,
that continue until night, till wine inflame them:
then they call for the harp and the viol, the tabret and the pipe, etc.
But such regard not the work of the Lord,
neither consider the operation of his hands:`" a sad state!
"`Woe unto them that are mighty to drink wine,
and are men of strength to mingle strong drink.`"
And therefore all to shun such things; all are to be sober, and to mind and fear God,
that they may escape these woes: as you may see in Isaiah chap.
5.

And therefore all vinters, and such as sell wine, with ale-houses, inns,
and victualling houses, who sell ale, brandy, and strong liquors,
never let any one have more than doth them good, and is for their health,
(as is said before,) so that all may eat and drink
the good creatures of God to his praise and glory;
which drunkards and gluttons cannot,
nor they who let them have the creatures of God in excess or immoderately,
till they are drunk and surfeited, for such do feed themselves without the fear of God.

Secondly.
Let all who go under the name of christian families,
train up their children in the fear of God, and keep themselves in the fear of God,
that they may keep all their servants and females in the fear of God;
out of all looseness and wantonness, and vanities and excess, and from all drunkenness,
fornication, whoredom, or uncleanness, and unrighteousness, and all ungodliness;
that they may keep out of all those things that displease or dishonour the Lord God.
And do not nourish up the lust of the eye, nor the pride of life,
nor the lust of the flesh; for if you do,
you nourish up that which is not of God the Father.
And therefore to shun all these evils, and to depart from them,
and keeping in the fear of God; this is the way to bring the blessing of God upon a land,
kingdom, nation, or family.

"`God will destroy them which destroy the earth.`" Rev. 11:18.

Drunkenness makes a man worse than a beast, and makes a strong man weak,
and a wise man a fool.

This testimony and warning was and is owned and subscribed by many vintners and others,
concerned in the trades and callings before mentioned,
who were present at the reading of the manuscript.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 371.

[.blurb]
==== An epistle to the household of faith.

Friends,
consider how the blessing of the Lord came upon the obedient and faithful to the Lord,
and rested upon them.
The Lord said to Abraham, "`Get thee out of thy country, and from thy kindred,
and from thy father`'s house, etc.
And I will make of thee a great nation, and I will bless thee, etc.
And thou shalt be a blessing, and I will bless them that bless thee,
and curse them that curse thee; and in thee and thy seed,
shall all the families of the earth be blessed.`"
Abraham obeyed the Lord, and went forth from Ur of the Chaldees,
and so he left all the religions, and worships,
and teachers of the country of the Chaldees behind him, and followed the Lord.
And the Lord said unto Abraham, "`Walk before me, and be thou perfect.`" Gen. 17:1.
And again, the Lord said unto Abraham,
"`Seeing that Abraham shall surely become a great and mighty nation,
and all the nations of the earth shall be blessed in him.`" Gen. 12:1-3.
and 18:18. And again, the Lord said unto Abraham,
"`That in blessing I will bless thee,
and in multiplying I will multiply thy seed as the stars of heaven,
and as the sand which is upon the sea shore,
and thy seed shall possess the gates of his enemies;
and in thy seed shall all the nations of the earth be blessed,
because thou hast obeyed my voice.`"
Abraham obeying God`'s voice, brought this blessing upon him, as in Gen. 22.
And the Lord said,
"`I know Abraham that he will command his children and his household after him,
that they shall keep the way of the Lord, to do justice and judgment,
that the Lord may bring upon Abraham all that which he hath spoken of him.`"
Now you may see here what it is that brings the blessing,
and kept the blessing upon Abraham and his seed, etc.
Now if you be of the true faith, you are of Abraham,
and are blessed with faithful Abraham. Gal. 3:9.
And in this seed and faith of Abraham,
you will command your children and your household after you, to keep the way of the Lord,
to do justice and judgment,
that the Lord may bring the blessing upon you and your household and children;
keeping in the same faith and seed of Abraham,
and you and your children and your household,
keeping in the way of the Lord to do justice and judgment, then, I say,
the blessing which came upon Abraham will come upon you,
and upon your children and your household,
and then you will know the promise of God fulfilled; "`Cursed is he that curses thee,
and blessed is he that blesseth thee;`" and therefore live and walk in the seed,
which "`bruises the head of the serpent,`" in which seed all nations are blessed, yea,
all families, households, and children, in which faith and seed you command (mark,
command) "`your children and your household after you,
to keep the way of the Lord,`" as Abraham did, "`to do justice and judgment.`"
Gen. 18. and 19. Now you that have not this authority
to command over your children and households,
you are not in the faith and seed of Abraham, to wit,
"`to command your children and household after you, to keep the way of the Lord,
and to do justice and judgment.`"
Now the Lord had a confidence in Abraham,
and so he hath in all them that be of his seed and faith now,
that they will command their children and household to keep the way of the Lord,
as he did, and walk before the Lord, and to do justice and judgment;
and that Abraham`'s family and children should not
go back again into those country religions or ways,
which the seed and faith of Abraham hath and had led them out of.
For they that are commanded to come out of them, into God`'s way,
into the way of the Lord, are commanded to keep in the way of the Lord,
and they are to command their children and their household to keep the way of the Lord,
and to keep out of all the ways of the world, and out of all the ungodly, unjust ways,
in the seed, which bruises the head of the serpent.
And the Lord said to Isaac, "`I will make thy seed to multiply as the stars of heaven, etc.
And in thy seed shall all the nations of the earth be blessed.`" Gen. 26:4.
Now here you may see that Isaac inherited
his father`'s inheritance in the seed,
and in the faith and way of the Lord; in which seed all nations are blessed:
and so do all they that are of the faith and seed of Abraham,
that walk in the steps of faithful Abraham, in the way of the Lord, and obey his voice,
inherit the blessing of Abraham; for you may see it was not the only care,
that their children might inherit a little earth after them,
but that they might inherit the seed and the faith, which had the blessing.

And Isaac said to Jacob, "`God Almighty bless thee,
and give the blessing of Abraham to thee, and to thy seed with thee.`"
Gen. 28. And this Isaac spake to Jacob before Jacob had any children;
and here you may see Isaac`'s care,
that Jacob and his seed might inherit the faith and blessing of Abraham and Isaac;
and this should be their first inheritance,
and then they should inherit the outward land.
And this should be the care of all them that walk in the steps of the faith of Abraham,
to see that their children and household do inherit the faith, seed,
and blessing of Abraham, in the first place, by keeping in the way of the Lord, etc.
And they are to command their children to walk in the way of the Lord,
etc. that they may so do; and you may see,
that Jacob did inherit the blessing of Abraham and Isaac,
in Abraham and Isaac`'s seed and faith.

When the Lord said unto Jacob, "`Thy seed shall be as the dust of the earth,
and thou shalt spread abroad to the west, and to the east, and to the north,
and to the south, and in thee,
and in thy seed shall all the families of the earth be blessed.`"
So here you may see Jacob`'s possession,
who did inherit the blessing of Abraham and Isaac;
and they that are of the seed and faith, which keep the way of the Lord,
they do inherit this blessing in the seed, in which all nations are blest.
And this is according to Christ`'s doctrine, "`seek ye first the kingdom of God,
and his righteousness, and all these things shall be added unto you,`" to wit,
what ye shall eat, or what ye shall drink, or wherewith shall ye be clothed;
for after all these things do the Gentiles seek.
For your heavenly Father knoweth that you have need of all these things.`"
And here Christ, (who was of the seed of Abraham, and of David,
according to the flesh,) would have people to seek
their inheritance in the kingdom of heaven,
and its righteousness, before they seek outward things.
And they were to lay up for themselves treasure in heaven, etc.
And to know that portion for them and their children.
Matt.
6+++.+++ And the apostle saith, "`The children of the promise are counted for the seed.`" Rom. 9:8.
"`For in Isaac shall thy seed be called.`" Gen. 21:12.
And Christ saith, "`The good seed are the children of the kingdom.`" Matt. 13:38.
And this is the seed in which all nations are blest,
who keep the way of the Lord, and justice, and judgment,
such the Almighty hath blessed with the blessings from above,
"`the blessings of the deep, the blessing of the breast, and of the womb.`"
Gen. 49. And he will also bless the fruit of the land, "`thy corn, thy wine, and thy oil,
and the increase of thy kine, and the flocks of thy sheep.`" Deut. 7.
And they that serve the Lord their God, he will bless their bread, and their water. Exod. 23.
And "`a faithful man shall abound with blessings.`" Prov. 28:20.
So you may see, they that are in the faith, and in the holy seed,
which keeps in the way of the Lord,
and command their children and household to do the same;
they have the blessings from heaven above, and the blessings below, yea,
the blessings of the eternal inheritance, and of the kingdom of God.
And that was their chief inheritance,
that all the faithful seed of Abraham sought to possess
their household and their children in,
who did command their children and household to keep the way of God,
that they might inherit the blessing.
David saith, "`Blessed is the man that walketh not in the counsel of the ungodly,
nor standeth in the way of sinners, nor sitteth in the seat of the scornful.
But his delight is in the law of the Lord, and in his law doth meditate day and night.`"
Now here is the condition of them that do enjoy the blessing,
they must keep from the counsel of the ungodly, and the way of sinners,
and the seat of the scornful.
Now here you may see David`'s instruction, how people might inherit the blessing.

Levit. 10. "`That you may put a difference between the holy and unholy,
and between the clean and unclean, and that you may teach your children all the statutes,
which the Lord hath spoken unto them by the hand of Moses.`"
And it was so in the old testament, that they might learn the statutes there.
Surely much more they are to learn the commands of Christ in his new testament.

And in Duet. 4:9-10. "`they were to teach their sons,
and their sons`' sons;`" and again, they were to teach "`their children,
that they might learn to fear God all the days that they lived upon the earth,`" etc.
This they were to teach their children; and again, in Deut. 11. it was the command of God,
that they were to teach their children the commandments of God,
and they were to speak of them, when they sat in their house,
and when they walked by the way, when they lay down, and when they rose up.
And in Deut. 30. Moses told them, that
"`the word was nigh them, in their mouths, and in their hearts, that they might do it.`"
And David said, "`Come, you children, hearken to me,
and I will teach you the fear of the Lord.
O fear the Lord, you saints; there is no want to them that fear him.`" Ps. 34:11-9.

"`Ye that fear the Lord, trust in the Lord; he is their help and their shield.`"
Ps. 115:11. And you may see all along in the Old Testament,
they that feared the Lord were commanded to teach
and instruct their children the way of the Lord,
that they might walk in it, and inherit the blessing;
which was a better portion than outward riches which will pass away;
for "`they make themselves wings and fly away.`"
Solomon saith, "`Train up a child in the way he should go,
and when he is old he will not depart from it.
Foolishness is bound up in the heart of a child,
but the rod of correction shall drive it far from him.`" Prov. 22:15.
He that spareth the rod, hateth his son; but he that loveth him,
chastiseth him betimes.`" "`By mercy and truth, iniquity is purged out;
and by the fear of the Lord, they depart from evil.`" Prov. 13:24.
and 16:6. And the apostle`'s command is,
"`for children to obey their parents in the Lord, for this is right.`" Eph. 6:1.
and Col. 1:3:20.

It is well pleasing to the Lord, children to obey their parents.
And the bishops or elders, were to rule well their own houses,
and to have their children in subjection, with all gravity; and likewise,
the deacons were to rule their own children and their own houses well.
Tim. 1:3. And likewise you may see the good report of the widows bringing up children,
which followed every good work, etc.
And in Titus, such as were elders or overseers, their children were to be faithful,
not accused of riot, or unruly; and the aged women were to be of good behaviour,
as becometh holiness, etc. and teachers of good things;
and that they teach the younger women to be sober, etc.
And that the word of God be not blasphemed.
And Titus was to exhort young men to be sober-minded.
"`For the grace of God which brings salvation hath appeared unto all men, teaching us,
that denying ungodliness and worldly lusts, we should live soberly, righteously,
and godly in this present world; that being justified by his grace,
we should be made heirs according to the hope of eternal life.`"
And Peter saith, "`As obedient children,
not fashioning yourselves according to your former lusts, in your ignorance;
but as he who hath called you is holy, so be you holy in all manner of conversation;
and be not like them, feeding themselves without fear, which are the clouds without rain,
and wells without water, and trees without fruit, whom Jude declares against;
such cannot eat and drink to the praise and glory of God,`" etc.
So you see what care, both in the old and new testament, the faithful parents had,
to teach their children the way of the Lord;
and the Lord hath a confidence in all them that fear him,
and are of the faith and seed of Abraham,
that they will not only admonish their children and household,
but command their children and household after them, to keep the way of the Lord, etc.
Gen. 18. And to keep out of the wicked ways of the world.
The apostle saith, "`They which be of faith are blessed with faithful Abraham.`"
And so are all the children of God by faith in Christ Jesus; "`and if you be Christ`'s,
then are you Abraham`'s seed, and heirs according to the promise.`"
Gal. 3. And so the children of God are counted for the seed,
which the good seed Christ saith, are the children of the kingdom.

And the apostle spake to the Romans,
that they should walk in the steps of the faith of Abraham.
Again, the apostle saith to the Corinthians, concerning Titus,
"`Walked we not in the same spirit, walked we not in the same steps?`"
And in the first epistle of Peter, "`Christ hath suffered for us,
leaving us an example that we should follow his steps, who did not sin,
neither was guile found in his mouth.`"
So these were holy steps,
and are a religious holy people that walk in the steps of faithful Abraham,
and of Christ and the apostles; and these have the pure religion,
and do visit the fatherless and widows in their affliction,
and keep themselves unspotted from the world;
and these are they that are circumcised with the spirit,
and baptized with the holy ghost, and serve God night and day,
and worship him in spirit and truth.
And these are the religious families, which are of the holy, divine, pure,
and precious faith, which Christ is the author and finisher of,
which faith purifieth their hearts, and is their victory,
by which they have access to God, in which they please him,
in that faith which Christ is the author and finisher of,
which is called the gift of God; and they that are of this faith,
the same are the children of Abraham, and are blessed with faithful Abraham.
And Abraham was called the friend of God;
and so are all his children that are of his seed and faith,
they are not friends of the devil, the wicked and unrighteous one,
but him and his works they forsake, who are friends of God,
they are friends of righteousness and holiness, etc.
And such the blessings of God rest upon, them that are of the seed, and walk in the seed,
Christ, that bruises the serpent`'s head, and in that seed are all nations blest;
and out of the mouth of the seed`'s seed, shall not God`'s word depart;
but it shall abide in the mouth of the seed`'s seed,
(this living word of God.) But the word of God do not abide in them,
who make a profession of the scriptures,
but live not in the power and spirit of the holy ghost, that gave forth the scriptures;
such are like the Jews, John 5. and such think to have life in the scriptures,
but they will not come unto Christ that they may have life; for none come to Christ,
but by believing in the light, which is the life in him the word.

Now, dear friends and brethren in Christ Jesus,
if you keep in the seed and faith of Abraham,
in it you will command your children and families to walk in the way of the Lord;
for in it you have authority: that they may keep the pure, holy,
and righteous way of the Lord after you,
when you are gone,`"that they may succeed you in the faith and seed, and way of the Lord,
and in the blessing of God, as Abraham, Isaac, and Jacob did.
Amen.

[.signed-section-signature]
G+++.+++ F.

[.centered]
=== Epistle 372.

[.blurb]
==== To the Quarterly Meeting at York.

Dear friends and brethren in the Lord Jesus Christ, your life and salvation,
your rock and foundation, rest and sanctuary, in all storms, trials, and sufferings.

Now, dear friends, my desire is, that you may all strive for that which makes for peace.
"`For blessed are the peacemakers, they are called the children of God.`"
And therefore, whatsoever things are honest, just, pure, lovely, and of good report,
if there be any virtue and praise, think on these things to practise them.
So that in the power of the Lord, that is over the devil and his power,
all may be kept chaste, pure, and holy, to the glory of God;
and all that are in the true faith and knowledge may show it forth in virtue, temperance,
patience, godliness, brotherly kindness, and true charity or love,
which beareth all things.
For they that dwell in love, dwell in God, that is their habitation.
And let all things be done in love, in the name and power of Jesus Christ.
And all to strive in the spirit of the Lord God, and his truth,
to be of one mind and judgment;
so that you may all be baptized with one spirit into one body,
and so all to drink into one spirit.
And keep the unity and fellowship in the holy spirit of God,
which is the bond of peace amongst all God`'s children, that are led by his holy spirit,
whose communion and fellowship is in the holy ghost, by which ye are led into all truth.

Now, dear friends, let there be no strife in all your meetings,
nor vain janglings nor disputings;
but let all that tends to strife be ended out of your meetings,
that they may be kept peaceable; so that you may be at peace among yourselves,
and the God of peace and love may fill all your hearts, which love edifies his church.
And condescend one to another in the fear of the Lord, to that which is honest, just,
virtuous, and of good report; and where any weakness has been in any thing,
let it be covered and buried in the spirit and love of God,
that his spirit and love may be uppermost in you all, to unite all your hearts together:
and that you may all show forth that you are the
children which the heavenly wisdom is justified of,
which is pure, (mark,) pure, peaceable, gentle, and easy to be entreated,
which is above the wisdom that is below, that is neither pure, peaceable,
nor easy to be entreated, etc.
And in all matters of business, or difference, or controversies,
treat one another in such things kindly and gently, and be not fierce, or heady,
and high-minded; for that spirit will bring men and women to be lovers of themselves,
and to be despisers of others, and that which is good,
which leads nature out of its course, and so loses natural affections,
and at last comes to be without natural affections;
which spirit we see most of christendom is led by: for,
if they were in natural affections,
they would not destroy their fellow creatures about religion;
but being without natural affections, they have not affections to their fellow creatures;
to wit, man and woman, which were made in God`'s image.
The law and the prophets commanded to "`love their
neighbour as themselves;`" and Christ commands,
"`to do unto all men, as they would have men do unto them.`"
And the gospel commands,
"`to love one another;`" by which they are known to be Christ`'s disciples;
and to "`love their enemies, and to pray for them,
and to forgive one another,`" as Christ has forgiven them.
So that those, whose conversation is according to the gospel of peace,
do establish the law and the prophets; who know the divine nature,
and are made partakers of it, are not without natural affections,
but have affections to it, to cherish and preserve it.
And this the word of wisdom teaches,
by which all things were made and created good and blessed;
by which all things are upheld, by which all things are sanctified to God`'s people,
that God created by his word, and made them good, and blessed them:
by which word and wisdom all things are sanctified to God`'s people,
(as before,) and are used and ordered by his word of wisdom to his glory and praise.

And now, dear friends,
whereas there have been formerly some discourses by some in your meeting,
of marrying within a year after the decease of the wife or of the husband; my desire is,
in those things, friends may show forth both chastity, and virtue, and temperance:
for formerly hasty marriages were reckoned amongst the infamous persons,
as for a man or a woman to marry within the year of the death of the wife or husband.
And therefore, for virtue and chastity`'s sake, and the truth, and good example`'s sake,
that which is honest, lovely, and of good report, keep, and walk in, and follow:
for we ought, in the power of Christ Jesus, to outstrip the world in virtue, chastity,
modesty, and temperance, and in that which is of good report.
For our heavenly light ought to "`shine so before men, that they may see our good works,
and glorify our Father which is in heaven.`"
And therefore all in the church of Christ ought to live in the spirit and power of Christ,
in which they do judge the world and all the fallen angels.
So in this heavenly power, the virtue, purity, chastity, flows and shines over all;
and they that do possess, as though they did not; and they that marry,
as though they married not: they are all resigned in the power of Christ,
that gives dominion over the world, which brings all into one mind,
and to be of one heart and soul, and to one judgment, and are a chosen generation,
a royal priesthood, and holy nation; a peculiar people,
that show forth the praise of Christ,
who hath called them out of darkness into his marvellous light, and as living stones,
are built up a spiritual household, a holy priesthood,
to offer up spiritual sacrifices acceptable to God by Jesus Christ.

And so, my dear friends, my desire is, that in Jesus Christ ye may all live and walk,
who is the seed of the woman, "`that bruises the serpent`'s head;`" that is,
the head of all wickedness and strife; and in this seed, Christ, all nations are blessed,
as they live and walk in him: and the blessings from above, and the blessings beneath,
rest upon them: and in this seed Christ all have rest and peace,
who is the first and the last, over all blessed forever.
Amen.
In him is my love to you all, as though I named you.

[.signed-section-signature]
G+++.+++ F.

Read this in your Quarterly Meeting at York.

[.centered]
=== Epistle 373.

[.blurb]
==== To the Six Weeks Meeting in Barbados.

[.salutation]
Dear friends,

In Christ in whom we have peace, purity, holiness, and righteousness,
you must be kept holy and righteous to the glory of God, and righteousness, and holiness,
and purity, must wear and outlive all that is contrary to it; and patience, and meekness,
and humility, and kindness, and sobriety, must wear out passion, envy, strife, and wrath,
high mindedness, and loftiness, and willfulness.
And therefore consider, the holy men and women of God must not strive,
but be gentle to all; and in that alone keep their dominion: for truly, friends,
love gathereth into love, and edifies the body of Christ.
And let nothing be done with strife, but in love, to the glory of God,
in the name of Christ, and in his power;
so that you may all see and feel Christ among you,
ordering you all to his glory with his wisdom, which is pure, peaceable,
and easy to be entreated; so that none may be burdened nor oppressed in your meetings,
but that the life and seed may reign in you all;
and so the Lord may have the glory of all, and ye may all have comfort in him your head.
And do not much strive with unruly talkers,
but keep your peace in the spirit and power of Christ,
that will overcome and wear out all that is contrary to it.
So that all may keep their own habitation in Christ Jesus, who is over all,
the first and last; and in his power and spirit live and walk,
so that you all may be trees with fruits, and wells with water,
and have bread in your own tabernacles, and your own lamps trimmed and burning,
and that there may be no strife among you, but dwell in love;
for he that dwelleth in love, dwelleth in God; so, God who is love,
is to be your salvation.
And condescend to the meek, and to every appearance of the Lord God,
and make every one`'s condition in the truth your own; in that you will deny yourselves,
and become all to all in the truth, so that none may be hurt in the truth,
nor made to stumble, nor the blind caused to wander, but be directed into the right way,
and all as the tender plants may grow together, as the Lord`'s planting,
and he watering them, and giving the increase and growth to his glory;
so that the Lord may have the praise and glory of all his works.
Amen.

And be careful in all your meetings,
that they may be kept peaceable in the wisdom of God, that is pure and peaceable,
and easy to be entreated; so that "`wisdom may be justified of her children.`"
That there be no harshness or fierceness, but meekness and mildness,
and gracious language, which will edify and season the hearers, and be of a good savour.
And this will honour the seed Christ, from whence grace and truth cometh,
and will be to your comfort, and show forth whose children you are; for, as Christ said,
"`Blessed are the peacemakers, they are children of God.`"
And therefore all do this work, that you may have this blessing.
And so, with my love to you all, that are convinced of God`'s truth,
as though I named you all; and all to dwell in love; then you all do dwell in God,
as I said before; and so the Lord God Almighty preserve you all in Christ your sanctuary.
Amen.

[.signed-section-signature]
G+++.+++ F.

You may read this in your Monthly or Quarterly Meetings.

Kingston, the 7th of the 9th month, 1683.

[.centered]
=== Epistle 374.

[.blurb]
==== To suffering Friends in prison at Bristol.

[.salutation]
Dear friends,

With my love to all the prisoners and the faithful, as though I named them.
It is the time now for all the faithful to keep in Christ their sanctuary,
in whom you have all peace, rest, life, and salvation, and by the testimony of Jesus,
and the blood of the Lamb, whose names are written in the Lamb`'s book of life,
before the foundation of the world, they were they that did overcome,
and did eat of the hidden manna, and had the new name.
And therefore now is the time to keep the word of patience, and the testimony of Jesus;
for they that keep the word of patience,
the Lord will keep them in the hour of temptation, which will come upon the whole world,
to try them which dwell upon the earth; for the word was before the world was,
and the tempter; for all things were made by the word.
And it is also the word of reconciliation, the word of power, the word of wisdom,
and the word of life, and the word of salvation, by which people are reconciled to God,
that are born again of the incorruptible seed by the word of God;
and they feed and grow by the milk of the word, which lives, and abides,
and endures forever, which strengthens all the faithful, in all ages,
in all their afflictions, imprisonments, and sufferings;
and it is the same to God`'s people now in this day of trial,
to preserve all his people everywhere, in his spirit and power, faithful to himself;
for, he that endures faithful to the end shall be saved.
And Christ saith, "`He that is ashamed of me before men,
him will I be ashamed of before my Father, and his angels which are in heaven.`"
And therefore it is good to confess Christ before men, to be your priest, prophet,
your shepherd, your bishop, your way, your mediator,
that makes your peace betwixt God and you;
and be valiant for his glorious name and truth upon the earth.
And so with my love in the seed, in which you and all nations are blessed.

[.signed-section-signature]
G+++.+++ F.

From Dolstan, the 6th of the 10th month, 1683.

[.centered]
=== Epistle 375.

[.blurb]
==== To Friends in Charleston, in Carolina.

Dear friends, of the Monthly Meeting of Charleston, in Ashley Cooper River, in Carolina,
I received your letter, dated the sixth day of the Eighth-month, 1683.
Wherein you give an account of your meeting, and of the country,
and of your liberty in that province, which I am glad to hear of,
though your meeting is but small; but, however,
stand all faithful in truth and righteousness, that your fruits may be unto holiness;
and your end will be everlasting life.
And that you may be patterns of virtue, modesty, chastity, and sobriety,
showing forth the fruits and life of christianity in your lives and conversations,
that they may preach righteousness, truth,
and holiness to all people in that dark wilderness,
that you may answer the truth both in them that are called christians,
and in the Indians.
And my desire is, that you may prize your liberty, both natural and spiritual,
and the favour that the Lord hath given you, that your yea is taken instead of an oath;
and that you do serve both in assemblies, juries, and other offices, without swearing,
according to the doctrine of Christ: which is a great thing, worth prizing.
And take heed of abusing that liberty, or losing the savour of the heavenly salt,
which seasons your lives and conversations in truth, holiness, and righteousness.
For you know, when the salt hath lost its savour,
it is good for nothing but to be trodden under the foot of men.
For we here are under great persecution, betwixt thirteen and fourteen hundred in prison;
an account of which hath lately been delivered to the king.
Besides the great spoil and havoc which is made of Friends`' goods, by informers;
and besides the great spoil upon the two-thirds of our estates,
and upon the twenty pound a month acts, and for not going to the steeple-house;
and besides many are imprisoned and premunired for not swearing allegiance, both men,
women, widows, and maids; and many are fined and cast into prison, as rioters,
for meeting to worship God.
And we are kept out of our meetings in streets and highway in many places of the land,
and beaten and abused.
And therefore prize the liberty, both natural and spiritual, that you enjoy.
And many are cast into prison because they cannot pay the priests`' tithes;
and also many are cast into prison by the bishops`' writs, de excommunicato capiendo.
So, that at present we are under great sufferings, persecutions, and imprisonments.
But the Lord`'s power is over all, and that supports his people.

But in Ireland, Scotland, Holland, Germany and Dantzick,
we hear that Friends are in peace and quietness;
and therefore you that have great liberty, both natural and spiritual,
(as aforesaid,) be valiant for God`'s truth upon the earth, and spread it abroad,
both among them that are called Christians and Indians,
turning them from darkness to light, Christ Jesus, the saviour,
whom God hath set up for an ensign among the Gentiles or heathen,
and to be his salvation unto the ends of the earth: so seek the good of all,
and the profit of all, and the salvation, and the glory of God above all,
and the exalting of his name and truth in your day and generation; and live in love,
and in the truth, and the love of it; and overcome evil with good;
and hold fast that which is good, then you can try all things.

And so with my love to you all in the holy seed of life, Christ Jesus,
that reigns over all, who is your sanctuary, in whom you have all life, and peace,
and salvation, in him the Lord God Almighty preserve and keep you all, holy, pure,
and clean, to his glory.
Amen.

[.signed-section-signature]
G+++.+++ F.

London, the 23d of the 12th month, 1683.
