[quote.epigraph, , Rev. 18:11]
____
And the merchants of the earth shall weep and mourn over her,
for no man buyeth their merchandise any more.
____

[quote.epigraph, , Rev. 18:18-19]
____
And they cried when they saw the smoke of her burning, saying,
what city is like unto this great city And they cast dust on their heads, and cried,
weeping and wailing, saying, alas, alas, that great city,
wherein were made rich all that had ships in the sea by reason of her costliness,
for in one hour is she made desolate.
____

== The Epistle to the Reader.

To all the world to whom this may come to be read,
that they read with a good understanding,
and hereby they may come to the perfect knowledge
of the ground of difference between the priests,
and professors, and all sects in these nations, and us who are in scorn called Quakers;
showing that the controversy on our part is just and equal against them all,
and that we have sufficient cause to cry against them, and to deny their ministry,
their church, their worship, and their whole religion, as being not in the power,
and by the spirit of the living God, as commanded of him,
or ever practised by his saints: but this declareth the ground,
and foundation thereof to be another thing, than that on which the true church,
and ministry, and practice, and worship,
and true religion were built in the days of the apostles.
And also, this is an invitation to all sects and professions of people,
to come forth and try if what they hold and profess
be according to the scriptures of truth;
and to do this by evident and sound arguments,
and by the best spiritual weapons they have,
and to lay aside all this persecution and unrighteous dealing, and stocking,
and whipping, and imprisoning of us for speaking against their religion;
and that they come forth in fair dispute, to contend in the spirit of meekness,
for what they profess and practice, and to prove, according to the scriptures,
their ministry, church, and whole religion, that it is in,
and by the spirit and power of God, or otherwise to renounce and deny all their religion,
and the profession and practices thereof,
that every man may be satisfied who they are that are in the true and right way,
and of the true worship, and true religion, and who are not;
and this is desired by us who are called Quakers.
And here also is a true account of our first beginning and coming forth in the world;
and of the great sufferings we have sustained,
and how we have been carried on and preserved to this day.

The Lord God everlasting, who is true and faithful, hath fulfilled his promise in us,
and unto us, and we are gathered from the mouths of all dumb shepherds,
and out of the mouths of all hirelings, who have made a prey upon us,
and fed themselves with the fat, and devoured souls for dishonest gain.
And we are come to the fold of eternal rest, where Christ Jesus is the chief shepherd,
and he is the shepherd and bishop of our souls,
that feedeth his flock with living bread that nourisheth us unto life eternal.
He hath called us by his name, and put us forth, and he feedeth us in green pastures,
and we are are fed with hidden manna, and lie down at noon with his gathered flock.
And out of nations, kindreds, multitudes, and peoples are we redeemed to God,
and are come out of the world, and out of great Babylon,
and out of spiritual Sodom and Egypt, where the Lord Christ was and is crucified,
and lieth slain to this day.
And atop of the world hath the Lord set us,
on the mountain of his own house and dwelling; where we behold and feel the life,
and glory, and crown of the world that hath no end;
and the world that hath an end is seen over,
and its crown and glory are his footstool that reigns among us.
And as for all that which this perishing world brings forth, which men seek after only,
it is reckoned our temptation, though all the sons of Adam are seeking its glory,
its riches, its crowns, its contentments.
But of that birth are we which hath no crown, no glory, nor rest under the sun:
a birth is brought forth amongst us which is heir of another kingdom,
and possessor of another crown, whose glorying is in the Lord all the day long;
and he is our refuge, our rock, and our fortress against all our enemies.
And what though the wicked arm themselves, and the ungodly bend their bow?
--what though all sorts of people,
from the prince upon his throne to the beggar upon the dung-hill,
exalt themselves against the despised people of the Lord`'s inheritance, who,
for his name`'s sake, are killed all the day long?
--what though the wise men bring forth their arguments,
and the rulers bring forth unrighteous judgments against the seed that God hath blessed?
--what though the revilers and scorners open their mouths,
and reproachers and revilers cast out their bitter words
as a flood against the remnant of the woman`'s seed,
that hath long been fled into the wilderness?-- and what if the teachers, the prophets,
and the elders, and the heads, and wise men of the world set themselves to pray,
and preach, and print against the chosen seed of Jacob?
--Notwithstanding all this, though this is come to pass, and hell open her mouth,
and her floods break forth to overflow, and be much more increased;
yet shall the King of righteousness rule among his people,
and his presence will not forsake his chosen ones.
The Lord is with us, a mighty, and a terrible one, and the shout of a king is amongst us,
and the dread of the Almighty covereth us, and it goeth before us,
and compasseth us about; and the Lord is working a work in the earth,
mighty and wonderful!
He is gathering the scattered, and binding up the brokenhearted,
and his people shall dwell in safety, and none shall make them afraid,
and no weapon that is formed against them shall prosper,
nor any hand that is lifted up shall prevail.
For Zion shall arise out of the dust, her beautiful garments shall be put on,
and mourning and sorrow shall flee away; and her light is risen that is everlasting,
and the sun shall never go down, but his day shall remain forever,
and the night shall not again cover her brightness, nor the sun set upon her habitations.
The city that hath long lain waste, shall again be builded,
and the dwelling that hath long been without inhabitant, shall be replenished;
for the numberless seed of Jacob is coming out of Egypt,
that will replenish the whole earth, and the seed of Esau shall become bondmen.
And wherefore are you gathered together?
and to what purpose have the wicked spent their strength
to oppose what the Lord is bringing to pass?
Shall not all our enemies be broken to pieces, and will not the Lord grind them to powder?
Will he not mar their beauty, and stain their pride?
Will he not bring down their crowns, and corrupt their glory,
and stain it with his fire of wrath, and make them ashamed of their ways and doctrines?
Hear this ye priests, and howl,
and lament for the misery that is coming upon you! the Lord hath laid you naked,
and made you bare, and you are seen as you are,
and the elect is risen amongst us which ye cannot deceive.
But, alas! woe is me! how have you caused the people to err,
and how have you led the blind out of the way, and how is truth fallen in your streets!
And you have daubed falsely with untempered mortar, and have cried peace to the wicked,
and condemned the righteous, and all this hath vexed the righteous soul,
and the Lord will now arise, and is risen, and you shall not resist,
and escape the stroke of his hand, which will come upon you,
and bruise you as a millstone; for you have caused the wicked to rejoice,
and the righteous to mourn, and you have made sad his heart whom God hath not made sad.
Have not you fed yourselves with the fat, and clothed with the wool?
and hath not the people`'s souls been starved, and leanness been upon them all?
Your plants are dry, barren trees that bring forth no good fruit;
and your people are like a wilderness that is unfilled, and unploughed, and undressed;
and your flocks are like wild asses upon the mountains that are untamed,
as rude as the horse and mule, that know no bridle.
And now it is seen what the end of your ministry is, and what fruit it hath brought forth.
The Lord hath taken notice, and beheld how you have loitered and lain idle,
and the nations lie yet like fallow ground that bears no fruit;
and men`'s hearts are untouched with absence of God`'s word, and there is no sound, true,
and perfect sense amongst your people of the dealings of the Lord,
nor of the operation of his spirit, but they remain in great blindness and ignorance,
void of the knowledge of God.
For ye have not caused them to hear his word, but you have told your dreams,
and your false visions, and you have spoken imaginations of your hearts,
and not from the mouth of the Lord; neither have you stood in his counsel,
nor hearkened to his voice, and therefore people remain unprofited.
What they and you know, it is naturally, and not by the spirit of the Father;
but as dry trees you are, not taught of the Father, and as rough goats,
in the nature of swine that are polluted in the filth of the world,
and in the nature of dogs, and lions, devouring one another, and biting one another,
and killing one another; which things were not in the churches of Christ.
And we have a great controversy with you, and that from the Lord.
We have tried you, searched you, and discovered your foundation, and it is not sound,
nor will stand in the trial.
We have fetched your line from the first original, and we have found out your beginning,
and we find yours of that race, which Christ prophesied of that should come,
who should deceive many, having the sheep`'s clothing, but inwardly ravening;
and who John saw were come, and went out from the apostles and true churches,
went from the truth, and went into the world,
and had the form of godliness without the power:
here began the race in the apostacy of the churches.
And when they apostatized from the true faith, then came your original up,
and the world went after them, and all that dwelt upon the earth worshipped the beast,
that hath reigned through all this time of apostacy,
which hath been since the days of the apostles.
And we find your original goes no further than to the false brethren, and false apostles,
who went out from the true apostles, and run for gifts and rewards,
and preached for filthy lucre, and through covetousness made merchandise of souls,
seeking money and gain to themselves.
I say, we find your original begins there, and your line goes no further,
and never came your first rise so far as the true apostles; you were not,
in your beginning, of their life nor birth, nor can be reckoned from their original,
for you succeed not them; but you truly succeed the false apostles, and false brethren,
which Christ prophesied should come after his days,
and John saw were come and coming in his days.
And we find you of this stock and generation,
and now you are discovered to be contrary to the true apostles,
and agreeing with the false apostles, in call, in practice, in maintenance,
and in all things; and the line of true judgment is laid upon you all,
and you are measured, and found too short, and weighed, and found too light.
And we will deal truly with you in judgment: first,
we do hold controversy with you as concerning your call, your ministry,
it agreeth not with, but is contrary to what the apostles`' call was;
they were called by power from on high,
and were made ministers by the gift of the holy spirit received from God,
and their ministry was an absolute gift from God,
and not to be bought and sold for money; and they were anointed of the Father,
by his spirit of promise, to preach the gospel.
But your call is at schools and colleges, in such and such orders,
which are attained through natural industry, such and such arts and sciences,
and degrees,
having been so many years brought up in studying natural arts and natural languages;
this is your ordination and your call,
having no respect to receive or to wait for the gift of the holy spirit,
to be made ministers thereby; and this is different from the apostles and true ministers,
and equal and according to the false prophets and deceivers.

[.numbered-group]
====

[.numbered]
_Secondly._
Again you are not according,
but contrary to the true ministry and ministers of Christ in practice;
for they were led by the spirit of the Father which dwelt in them,
and they preached the gospel by the spirit, and spake as the spirit gave them utterance,
and went up and down the world through nations,
converting people to the knowledge of the truth; and what they had handled, tasted, seen,
and felt of the word of life in them, that they declared to others,
and preached the gospel, which they had not received from man, nor by man,
but by the revelation of Jesus Christ in them.
But your practice is not such, but contrary, for the spirit of this world leads you,
and it you follow in all your works, in your preaching, praying,
and in your whole worship, in form and tradition;
what you have studied out of books and old authors, you preach to people,
and what ye have noted in a book, that you preach by an hour glass,
and not as the spirit of God gives you utterance.
And you seek out and inquire after great benefits, and much money by the year,
and where there are much tithes and glebe lands, and such like;
thither and to such a place, you go, and seek to be ministers there,
and there you remain twenty or forty years,
more or fewer as you can agree with the people,
and while they will give you so much as will content you, and maintain you,
your wives and families, as you say,
and regard not whether any be converted to God by your preaching,
but people remain always in blindness and ignorance generally,
and without the knowledge of God.
For you preach other men`'s words,
and what you have collected in your imaginations from the saints`' words,
an hour by a glass, leaning upon a soft cushion,
and for money and hire preaching to the people, and this is your manner of practice,
and ministry in these nations.
But thus did not the apostles, nor Christ`'s ministers; but the contrary.
And by your fruits and works it appears that you are not followers
of that spirit that Christ and his ministers were guided by,
neither are lawful successors of the apostles;
but by your fruits and practice you manifest that the Lord never sent you,
and Christ never called you into his service to be his ministers;
for in all your practices and in your whole performances of worship you differ,
and do not agree with,
but are contrary to what the practice and worship of Christ`'s
ministers and churches were in the days of the apostles.
This I charge upon you, in the name, and by the authority of the Lord God,
and am able to prove it against you, face to face,
or otherwise to show that you are not of the same spirit,
but contrary to the saints and apostles of old, and so not true successors of them,
nor lawful ministers of Christ; as to all people it is, and shall be made manifest.

[.numbered]
_Thirdly._
You disagree with and are contrary altogether to the true ministry, and to the apostles,
in respect of your maintenance and wages;
for the wages which Christ allowed his ministers, was,
into whatsoever house they entered, that was worthy,
they might eat such things as were set before them,
for the workman (saith he) is worthy of his hire.
And the apostles eat only of the fruit of the vineyard that they had planted,
and of the milk of the flock which they kept, by a free gift of the people,
whom they had begotten to the faith; and to whom they sowed spiritual things,
it was but as a small matter if they reaped their carnal things;
and though as a free gift they would do it,
yet the apostle said he would not make the gospel of Christ chargeable.
And in this manner were Christ`'s ministers and ministry in wages and gifts,
upheld and maintained outwardly in the world.

But your practice and maintenance are not such, but contrary, as is fully made manifest;
for you will have so much by the year promised to you in tithes, money, or glebe lands,
or stipends; and of drunkards, and swearers, and profane worldly people,
who are not sheep of Christ`'s flock, nor plants of his vineyard,
you will have so much of each of them,
and of every man in such a compass as you call your parish.
And if any, either out of covetousness or good conscience, cannot pay you,
you sue them at law, and cast them into prison, for wages, and spoil their goods,
and take treble, nay sometimes five-fold damage.
And through violence, and injustice, and cruelty are you maintained in such a manner,
and not as the true ministers and apostles of Christ were,
but in a way and manner quite contrary, as it is manifest; and so herein it is proved,
that you are not lawful successors of the apostles and ministers of Christ.

[.numbered]
_Fourthly._
Again, you follow not the apostles and true ministers of Christ,
but are contrary to them in doctrine, as this following volume will clearly manifest,
which for this very end is collected from your own mouths and pens,
that all men may see what you are, and what you hold and profess;
and being truly laid down and answered, let yourselves, and all sober men,
compare your doctrines and sayings with the doctrines of the apostles,
and they may see you agree not with them, but are contrary to them.
And now, friends, to all you that profess yourselves to be ministers of the gospel,
I do hereby declare unto you, in the name and authority of the Lord,
that we have controversy with you, and a great charge against you in all these things,
in your call, in your practice, in your maintenance, and in your doctrines;
and our mouths hath the Lord opened,
and they cannot be shut from declaring and crying against you,
as such whom the Lord never sent, but are contrary to Christ, his prophets, and apostles,
in all your ways and practices; and the hand of the Lord is certainly against you,
and his power and dread will come over you, and lie upon your consciences.

====

Now, reader, whosoever thou art that readest this following volume, if thy mind be sober,
and thy heart right towards God,
thou may come to a good understanding of the ground and cause of this great controversy,
between the priests and the professors of this nation,
and us who are in scorn called Quakers, for it is not unknown to nations.
Of this great debate and battle, now for some years of continuance in this nation,
no man can be ignorant.
What putting in prisons, and what persecuting,
and what preaching and printing against us,
and what reports and fame have been through this nation for some years past!
And the Quakers, so called, have written, and spoken, and printed against the priests,
and their worships, and ways, and doctrines, and declared against them,
as deceivers and false prophets, and such as never were sent of God.
And on the other hand, thus have the priests, and more abundantly, cried out against,
and printed against the Quakers, as heretics, and deceivers, and witches,
and all that they could say that was evil.
And these things being not unknown, but publicly brought to pass,
it will be good to discover unto every man,
the first ground and cause of this great strife, and the matter of it, and its beginning,
so that all may know the certainty of these things,
and know they are not without good ground and sufficient reason on our part, to wit,
that we have just cause to do,
and strive against that generation of priests and teachers,
and that we do nothing rashly, and without sufficient reason.

It is now about seven years since the Lord raised us up in the north of England,
and opened our mouths in this his spirit; and what we were before in our religion,
profession, and practices is well known to that part of the country;
that generally we were men of the strictest sect,
and of the greatest zeal in the performance of outward righteousness,
and went through and tried all sorts of teachers, and run from mountain to mountain,
and from man to man, and from one form to another, as do many to this very day,
who yet remain ungathered to the Lord.
And such we were, (to say no more of us,) that sought the Lord,
and desired the knowledge of his ways more than any thing beside,
and for one I may speak, who, from a child, even a few years old,
set my face to seek and find the saviour, and,
more than life and treasure or any mortal crown,
sought with all my heart the one thing that is needful, to wit, the knowledge of God.

And after our long seeking the Lord appeared to us, and revealed his glory in us,
and gave us of his spirit from heaven, and poured it upon us,
and gave us of his wisdom to guide us, whereby we saw all the world,
and the true state of things, and the true condition of the church in her present estate.
First the Lord brought us by his power and wisdom,
and the word by which all things were made, to know and understand, and see perfectly,
that God had given to us, every one of us in particular,
a light from himself shining in our hearts and consciences; which light, Christ his son,
the saviour of the world, had lighted every man withal;
which light in us we found sufficient to reprove us, and convince us of every evil deed,
word, and thought, and by it, in us, we came to know good from evil, right from wrong,
and whatsoever is of God, and according to him, from what is of the devil,
and what was contrary to God in motion, word, and works.
And this light gave us to discern between truth and error,
between every false and right way,
and it perfectly discovered to us the true state of all things;
and we thereby came to know man, what he was in his creation before transgression,
and how he was deceived and overcome by the devil, and his estate in transgression,
and in disobedience, and how he is driven and banished from the presence of the Lord,
and the sorrow and anguish which he is in and to undergo.
And also by the light in us, we perfectly came to know the way of restoration,
and the means by which to be restored,
and the state of man when come out of transgression and restored.
These things to us were revealed by the light within us, which Christ had given us,
and lighted us withal; what man was before transgression,
and what he is in transgression, and what he is being redeemed out of transgression.
And also as our minds became turned,
and our hearts inclined to the light which shined in every one of us,
the perfect estate of the church we came to know; her estate before the apostles`' days,
and in the apostles`' days, and since the days of the apostles.
And her present estate we found to be as a woman who had once been clothed with the sun,
and the moon under her feet, who brought forth him that was to rule the nations;
but she was fled into the wilderness, and there sitting desolate,
in her place that was prepared of God for such a season, in the very end of which season,
when the time of her sojourning was towards a full end, then were we brought forth.
If any have an ear they may hear.
So that all these things concerning man, and concerning the times and seasons,
and the changing and renewing of times, and all things that pertain to salvation,
and redemption, and eternal life, needful for man to know, all these were revealed,
discovered, and made known to us, by the light which was in us,
which Christ had lighted us withal.

And we found this light to be a sufficient teacher, to lead us to Christ,
from whence this light came, and thereby it gave us to receive Christ,
and to witness him to dwell in us; and through it the new covenant we came to enter into,
to be made heirs of life and salvation.
And in all things we found the light which we were enlightened withal,
(which is Christ,) to be alone and only sufficient to bring to life and eternal salvation;
and that all who did own the light in them which Christ hath enlightened every man withal,
they needed no man to teach them, but the Lord was their teacher,
by his light in their own consciences, and they received the holy anointing.

And so we ceased from the teachings of all men, and their words, and their worships,
and their temples, and all their baptisms and churches; and we ceased from our own words,
and professions, and practices in religion, in times before zealously performed by us,
through divers forms, and we became fools for Christ`'s sake,
that we might become truly wise.
And by this light of Christ in us were we led out of all false ways,
and false preachings, and from false ministers, and we met together often,
and waited upon the Lord in pure silence from our own words, and all men`'s words,
and hearkened to the voice of the Lord, and felt his word in our hearts,
to burn up and beat down all that was contrary to God;
and we obeyed the light of Christ in us,
and followed the motions of the Lord`'s pure Spirit,
and took up the cross to all earthly glories, crowns, and ways, and denied ourselves,
our relations, and all that stood in the way betwixt us and the Lord;
and we chose to suffer with and for the name of Christ,
rather than enjoy all the pleasures upon earth,
or all our former zealous professions and practices
in religion without the power and spirit of God,
which the world yet lives in.
And while waiting upon the Lord in silence, as often we did for many hours together,
with our minds and hearts toward him, being stayed in the light of Christ within us,
from all thoughts, fleshly motions, and desires,
in our diligent waiting and fear of his name, and hearkening to his word,
we received often the pouring down of the spirit upon us,
and the gift of God`'s holy eternal spirit as in the days of old,
and our hearts were made glad, and our tongues loosed, and our mouths opened,
and we spake with new tongues, as the Lord gave us utterance, and as his spirit led us,
which was poured down upon us, on sons and daughters.
And to us hereby were the deep things of God revealed,
and things unutterable were known and made manifest;
and the glory of the Father was revealed,
and then began we to sing praises to the Lord God Almighty, and to the Lamb forever,
who had redeemed us to God, and brought us out of the captivity and bondage of the world,
and put an end to sin and death; and all this was by and through,
and in the light of Christ within us.
And much more might be declared hereof,
that which could not be believed if it were spoken,
of the several and particular operations and manifestations
of the everlasting spirit that was given us,
and revealed in us.
But this is the sum: life and immortality were brought to light,
power from on high and wisdom were made manifest,
and the day everlasting appeared unto us,
and the joyful sun of righteousness did arise and shine forth unto us and in us;
and the holy anointing, the everlasting comforter, we received;
and the babe of glory was born,
and the heir of the promise brought forth to reign over the earth,
and over hell and death, whereby we entered into everlasting union, and fellowship,
and covenant with the Lord God, whose mercies are sure and infinite,
and his promise never fails.
We were raised from death to life, and changed from Satan`'s power to God,
and gathered from all the dumb shepherds, and off all the barren mountains,
into the fold of eternal peace and rest,
and mighty and wonderful things hath the Lord wrought for us, and by us,
by his own outstretched arm.

And thus we became followers of the Lamb whithersoever he goes;
and he hath called us to make war in righteousness
for his name`'s sake against hell and death,
and all the powers of darkness, and against the beast and false prophet,
which have deceived the nations.
And we are of the royal seed elect, chosen and faithful,
and we war in truth and just judgment; not with weapons that are carnal,
but by the sword that goes out of his mouth, which shall slay the wicked,
and cut them to pieces.
And after this manner was our birth or bringing forth,
and thus hath the Lord chosen us and made us an army dreadful and terrible,
before whom the wicked do fear and tremble; and our standard is truth, justice,
righteousness, and equity; and all that come unto us, must cleave thereunto,
and fight under that banner without fear, and without doubting,
and they shall never be ashamed nor put to flight,
neither shall they ever be conquered by hell or death, or by the powers of darkness;
but the Lord shall be their armour, weapon, and defence forevermore.
And they that follow the Lamb shall overcome, and get the victory over the beast,
and over the dragon, and over the gates of hell; for the Lord is with us,
and who shall be able to make us afraid?

Then having thus armed us with power, strength, and wisdom, and dominion,
according to his mind, and we having learned of him,
and being taught of him in all things, and he having chosen us into his work,
and put his sword into our hand,
and given us perfect commission to go forth in his name and authority,
having the word from his mouth what to cut down and what to preserve,
and having the everlasting gospel to preach to the inhabitants of the earth,
and being commanded in spirit to leave all, and follow him, and go forth in his work,
yea an absolute necessity was laid upon us, and woe unto us if we preached not the gospel.
For when we looked abroad and beheld the world, behold it was altogether darkness,
and even as a wilderness, and desolate, and barren of good fruit;
and death reigned over men, and no good fruit was brought forth to God,
but leaves we beheld upon every soul.
And all men and peoples were made drunk with the wine of whoredoms,
and the whore`'s cup they had drunk,
and were committing fornication with the great whore,
and she reigned over the kings and peoples of the earth.
And the antichrist was set up in the temple of God, ruling over all,
having brought nations under his power, and set up his government over all for many ages;
even since the days of the apostles and true churches hath he reigned,
while the woman hath been fled into the wilderness, and the man child caught up to God.
Christ said antichrist should come, and put on the sheep`'s clothing,
and be inwardly a ravening wolf; and John saw that antichrist was come in his days,
and he went forth then from the true church, and went into the world,
and deceived the world; and ever since, his kingdom hath reigned over nations;
for then he began to exalt himself, and it is sixteen hundred years since,
all which time antichrist hath had the sheep`'s clothing, but inwardly a ravener,
and hath ruled and reigned.
And this we saw, in the very time of our birth and bringing forth;
and we beheld nations as a wilderness untilled, and men`'s hearts as the fallow ground,
unbroken up, and not ploughed nor sown with the good seed of God`'s kingdom.
So that we saw all states and orders of men corrupted
and degenerated from what they ought to be,
and from what God had once ordained them.
As for the ministry, first, we looking upon it with a single eye,
in the light of the spirit of God which had anointed us,
we beheld it clearly (which we had been stumbling at,
and much doubting that it was not the perfect ministry of Christ,
for many years before) not to be of Christ, nor sent of him, nor having the commission,
power, and authority of Christ, as his ministry had in the days of the true churches;
but in all things, as in call, practice, maintenance, and in everything else,
in fruits and effects we found it to disagree,
and be wholly contrary to the true ministry of Christ in the days of the apostles.
And likewise, we truly beheld it to be in call, practice, and maintenance;
and all things, the very same in fruits and effects with the false ministry,
and false prophets, and false apostles, and deceivers of old.
And this I do testify, and am able to prove in the spirit and authority of the Lord,
that the public ministry as now it stands generally,
is wholly degenerated from what the true ministry of Christ once was, and differeth,
and is contrary in all things to what Christ`'s ministers were, and agreeth,
and is equal in all things with what the false prophets
and deceivers were throughout all ages.
And this I charge upon it, in the face and view of all men to whom this may come;
for this we saw concerning it, in the beginning, and our first assurance.
And as for other places and orders of men and callings,
we saw them also corrupted and degenerated,
and evil and iniquity abounding among all sorts of people;
and blindness and darkness covered the face of the earth and of the world;
and all people were in their transgressions, and making void the law of God;
and that it was time for the Lord to work,
and to arise to ease himself of his adversaries.
And as for all churches (so called) and professions and gatherings of people,
we beheld you as all in the apostacy and degeneration from the true church,
not being gathered by the spirit of the Lord, nor anointed thereby,
as the true members of Christ ever were, but to be in a form,
and in forms of righteousness without the power,
and in imitations without life and perfect knowledge.
So that all the practices of religion we beheld without power and life,
though some had a sincerity in them, and a zeal and a desire towards the Lord;
yet all people erred in judgment, and none were guided in judgment by the eternal spirit;
and the error in judgment made their zeal blind,
and their performances of righteousness not accepted,
though acted in some sincerity and zeal; because they were not guided in practice,
and led in judgment by the spirit of the Lord, which only leads into all truth,
and none are in the truth but who are led only thereby.
So that we beheld all profession to be but as coverings with fig leaves,
while the nature of transgression stood uncondemned and not crucified.
We then also saw not only that the performance and practice in church state,
and in religious orders were corrupted, but also government, and magistracy,
and all things in civil state were not aright in the sight of the Lord,
nor as the Lord required, neither as he had ordained in the beginning; for government,
we know, as ordained of God, is to punish, and limit, and terrify all evil doers,
and to preserve and defend all that do well;
and that men`'s consciences are to be left free, to be ruled by the Lord alone,
and guided by his spirit; and that outward power and civil magistrates and laws,
(so called,) ought not to be Lord or ruler in men`'s consciences, nor over them.
But we beheld how unrighteousness and iniquity,
and sin and wickedness were strengthened and encouraged in the government,
and by such as were in authority;
and how the exercise of a good conscience in the fear of God was abused;
so that it was turned backward from what it ought to be;
them that did well were punished, and limited as transgressors,
and the evil doers were set free, and not made afraid: so that we could truly cry,
truth was fallen in the streets, and justice and true judgment turned backward,
and equity had no place to enter,
and the innocent were devoured through want of true and just judgment,
and the needy were spoiled and made a prey.
For no sooner had we opened our mouths, but the magistrates began to put us in prison,
and execute great injustice upon us, and became oppressors of the innocent,
and laid unjust burdens upon us, grievous to be borne,
and true justice and judgment were neglected, and wrong judgment brought forth,
and good government abused, and men in authority not ruled by the Lord,
neither ruling for the Lord among men: and thus it came to pass upon us,
through the corruption and degeneration in government and magistrates,
which we saw to be, as it was fulfilled by them, to wit, not as the Lord required,
nor as he in the beginning ordained it, but quite the contrary.
And this we saw in the beginning, when the spirit of the Lord was poured down upon us,
and power from on high was revealed to declare against all the abominations of the earth,
and to make war against all corruption, in all orders, and places, and men.

Then being prepared of the Lord, and having received power from on high,
we went forth as commanded of the Lord,
leaving all relations and all things of the world behind us,
that we might fulfill the work of the Lord into which he called us.
We consulted not with flesh and blood, nor any creature, nor took counsel of men,
but of the Lord alone, who lifted up our heads above the world,
and all fears and doubtings; and was with us in power and dominion,
over all that which opposed us, which was great and mighty;
and gave us power over it all, and to bind kings in chains,
and nobles in fetters of iron; and this is the saints`' honour.
And the word of the Lord we sounded, and did not spare, and caused the deaf to hear,
the blind to see, and the heart that was hardened to be awakened;
and the dread of the Lord went before us, and behind us,
and terror took hold upon our enemies.
And first of all, our mouths were opened,
and our spirits filled with indignation against the priests and teachers,
and with them and against them first we began to war,
as being the causers of the people to err;
the blind leaders that carried the blind into the ditch;
the fountain of all wickedness abounding in the nations, and the issue of profaneness:
for from them hath profaneness gone forth in all nations:
and against them we cried aloud,
being redeemed from their mouths who had made a prey upon us,
as they do upon all that follow their ways.
And in steeple-houses we visited them often, and in markets and other places,
as the Lord moved and made way for us, showing unto them and all their people,
that they were not lawful ministers of Christ, sent of him,
but were deceivers and antichrists, and such whom the Lord never sent.
And we spared not publicly, and at all seasons,
to utter forth the judgments of the Lord against them and their ways,
and against their churches, and worships, and practices, as not being of God,
nor commanded by him, but by which they deceived the world.
And this was our first work which we entered upon, to thresh down the deceivers,
and lay them open, that all people might see their shame, and come to turn from them,
and receive the knowledge of the truth, that they might be saved.
And this we did with no small opposition nor danger, yea,
often times we were in danger of our lives, through beating, abusing, punishing, haling,
casting over walls, striking with staves and cudgels, and knocking down to the ground;
besides reproaching, scorning, revilings and hootings at, scoffings and slanderings,
and all abuses that could be thought or acted by evil hands and tongues.
And often were we carried before magistrates, with grievous threats,
and sometimes put in the stocks, and whipped, and often imprisoned,
and many hard dealings against us, the worst that tongues or hands could execute,
sparing life.
Of this all the north countries may witness;
and all these things are sustained and suffered from people and rulers,
because of our faithfulness to the Lord, and for declaring against the deceivers.
For nothing, save only the hand of the Lord, and his power, could have preserved us,
and carried us through all this.
Neither for any outward reward, or advantage to ourselves whatsoever,
would we have exposed ourselves to that violence, and those sufferings, and dangers,
which befel us daily.
But the Lord was our exceeding great reward through all these things,
and kept us in the hollow of his hand, and under the shadow of his wings,
and gave us dominion in spirit over all our enemies, and subdued them before us.
And though rulers and people were combined against us,
and executed their injustice and violence upon us, yet the Lord made us to prosper,
and grow exceedingly in strength, wisdom, and number,
and the hearts of the people inclined unto us,
and the witness of God in many stirred for us,
for to that in all consciences in our words and sufferings, and ways,
we did commend ourselves to be known and approved.

And in the beginning we were but few in number,
only a few that thus were carried on and dealt with,
and that had received the power from on high in such a measure, and for such a work.
And no sooner did the Lord appear to us, and with us,
but the devil and his power rose up against us to destroy us; and it wrought in rulers,
priests, and people,
and all the ways and means invented by the devil that could he executed by his servants,
were brought forth to quench the work of the Lord,
and to stop our passage in what we were called to.
Did ye but perfectly know, as we perfectly found, the craftiness, and policy,
and wickedness of the devil, how to overcome this new born babe,
and how to root out forever this plant that was newly sprung forth,
it would make you admire and wonder!
All the priests and rulers were in an uproar.
The priests petitioned to the magistrates,
and run up and down from one session and judiciatory to another, and took wicked oaths,
and slandered the just with lies and reproaches,
on purpose to incense all people against us.
And the magistrates gave forth warrants for the apprehending of some,
and gave orders to break our meetings, and that we should not meet in the night season,
and such men might not pass abroad; and such stir and opposition were made against us,
as can hardly be expressed or declared.
There were uproars in steeple- houses, and uproars in markets,
and often haling before magistrates, and we were abused, and threatened, and slandered,
and all manner of evil done and spoken against us; and great injustice,
cruelty and oppression were acted towards us, wherever we came,
and all by means of the priests,
who spared not to enact and conceive mischief against us,
and sought daily to the magistrates for persecution, preaching in their pulpits,
and praying against us, and setting days apart to seek their God against us,
crying without ceasing, in public and private, heresy, error and blasphemy,
and that we were deceivers, witches, and seducers, and such like,
the worst they could say and imagine, to stir up the hearts of people against us,
running often to the assize and sessions, and courts, to complain,
and inform upon false oaths against us;
and through them were the whole countries in a rage and madness,
rulers and people often imprisoning, and abusing, and resisting us with violence,
banishing us out of towns, and putting of us out of our inns,
and often threatening to burn the houses over our heads;
the whole company of rude people in a town,
often gathering and besetting a house or inn about where we were entered to lodge,
in our travels.
We were often exposed to difficult and hard travels and journeys,
giving ourselves to the cross, to take it up against all that was earthly;
often drinking water and lying in straw in barns, after a hard day`'s journey;
and yet for all these things, the power and presence of the Lord were with us,
and we were carried on in much boldness and faithfulness in courage,
and without fear or doubtings, through the often hazard of our lives many ways,
in uproars, by evil men, and in markets, and steeple-houses,
and also in travels by robbers, and in every way were we exposed to dangers and perils,
but through all and all over all were we carried, and are preserved to this day.

And after this manner it came to pass concerning us; and much more might be said,
but this is in short declared how we were entreated and dealt with by priests, rulers,
and people, through all the northern counties of England, in our first going forth;
through which counties we first journied out of Westmoreland, through Cumberland,
Northumberland, and into some parts of Scotland, Durham, Yorkshire, Lancashire, Cheshire, etc.
And in all these counties much opposition we had, and exceeding sufferings,
and cruel dealings from men of all sorts.
Every jail may witness, in every county, how any of them seldom were without some of us,
or our friends, imprisoned in them these six years;
and scarce one steeple-house or market in all these counties,
but may witness what beating, what bruisings, strikings, and haling, and abusings,
and perils we have suffered and sustained.
And not one priest in all those counties can clear himself from hatred and malice,
and from envying us, and doing mischief in words and works, or thoughts,
or desires against us; nor scarce one justice, nor any officer of the peace,
can be excused in all those counties from plotting and acting injustice upon us,
and threatening and enacting cruelty against us.
And I call heaven and earth to record, and the light in every man`'s conscience,
and do appeal to that in all sorts of people, that by all sorts we suffered evil,
and unjust words and actions from them.
And let the witness of God in all men`'s consciences in all the north,
give testimony what dealings and cruelty we suffered, and how we have been dealt with,
and also of our patience and innocency under all that they have done to us.

But notwithstanding all that was acted against us, and spoken,
many hundreds of the honest and sober people owned us,
and also many rude and ungodly persons were converted to the truth; I say,
many hundreds in all these counties, in two years time,
were brought to the knowledge of the Lord and to own us.
All which time we laboured, and travelled in patience,
giving up ourselves to live or to die, and to all manner of sufferings and reproaches,
and hard trials, that we might fulfill faithfully what we were called unto.
Sufferings without, from open enemies and from our own kindred and relations,
and sufferings within,
for the seed`'s sake--all these made us well acquainted with griefs;
yet in our trials and afflictions, the Lord never forsook us, but his wisdom, love,
and life, and presence increased in us and with us.

Then in the year 1654, as moved of the Lord, we spread ourselves southward,
and entered into these south parts, and came the first of us into this city of London,
in the Fifth-month that year, and laboured in the work of the gospel,
in continual sufferings and oppressions divers ways,
and were oppressed and gainsayed by the wise men, and by the learned,
and had in reproach and contempt by all the high and lofty and proud professors,
and we were set at nought and rejected by the fat beasts of the south.
And it is well known to thousands in this city and south country,
what opposition we have had from all sorts of people; opposed in our own meetings,
and scorned, and slandered by envious and reproachful tongues;
publicly and privately encountered with by all the wisest of the city and country,
challenged, invited, and engaged to disputes by the high priests and church members,
(so called,) and written against, and printed against,
by the chiefest of men accounted wise and religious.
Which of any sect, and of all the wisest in profession,
and the most zealous in practices of religion,
(so called,) have not at some time or other beset us,
and encountered with us in high disputes and controversy, opposing us to our faces,
and gainsaying our doctrines and practices, and denying us, and resisting us wholly,
and crying against us to be deceivers, deluders, heretics, and blasphemers,
and such like, and that our doctrines were deceivable, and error, and factious,
and what not; and that our practices were destructive to men, laws, and government?
These things in the worst nature have been spoken against us without ceasing,
by the wisest, and men of greatest parts and most religious,
(falsely so accounted,) for these certain years, in the south, as well as in the north.
Besides, what loss have we sustained other ways in the south, by beatings, and strikings,
and abuses, and slanders, and false reproaches, and haling before magistrates,
and imprisoning, and all the like dealing from priests, rulers, and people, yea,
the same hard dealing and cruelty from all sorts of people we have suffered,
and do daily, as we did in the north.
Insomuch that we are now accustomed to the yoke,
and well acquainted with sorrows and griefs from all sorts of people.
And were not the Lord on our side, our enemies would swallow us up quick,
and we had been long since devoured by the teeth of the ungodly.
So that I may now call to witness all the jails and prisons in the south,
as in the north, and all the magistrates, and judges, and rulers,
and all officers of the law, what sufferings we have sustained,
and what cruel and hard dealing we have undergone, and what injustice,
and unequal and false judgment have been executed upon us in these five years time.
Which of the jails may appear free,
where some of us have not suffered the loss of our liberties unjustly?
And who of any justice of the peace, or any other officer,
from the judge to the constable, can clear themselves from guilt in this matter,
and have not had a hand in our unjust sufferings?
To the witness of God in all people of all sorts,
through this whole nation and some others, do I appeal concerning this matter,
how we have been dealt withal,
and what we have sustained in our persons and in our names,
and how many acts and words of cruelty and injustice we have borne and suffered.
And these priests have been as the fountain and cause of all this,
and the foremost in all this iniquity and injustice by all that
they could do to incense the rulers and people against us,
by preaching, and praying, and writing, and printing for the space of these seven years.
Notwithstanding all this the mighty power and presence of the Lord have been with us,
and preserved us from dangers great and many, and carried us through trials,
and perplexities, and sufferings; and not only so, but he hath increased us in number,
so that thousands and ten thousands have and may own us,
and the truth which we give witness of, and live therein?
For the eyes of all people are beginning to be opened, and the deaf ear is unstopped,
and the way of life eternal is made manifest, and the Lord is gathering his flock,
which hath been scattered in the cloudy and dark day, whilst these false idle shepherds,
(these priests and teachers I mean,) have fed themselves with the fat,
and clothed themselves with the wool, and laid down in slumber,
and not gathered the flock, nor fed them, but scattered them and driven them away;
and with force and with cruelty have they ruled over the heritage of the Lord.
Woe, woe, unto these shepherds, saith the Lord God,
they shall be confounded and put to shame perpetually,
and they shall be broken down and never builded any more,
and the Lord will pluck them up by the roots, and they shall never again be planted.

And besides all their petitioning the magistrates against us,
and preaching and praying against us, and all the evil and wickedness, in work, word,
and desire brought forth against us from time to time;
here sober reader thou hast a catalogue and whole
number of books printed and written against us,
and abundance of their doctrines uttered against us, and in opposition to us,
gathered up in this volume in a sum, with our answers to them;
and if thy heart and mind be single, thou mayst hereby understand, in measure,
the difference in doctrine between them and us,
and compare each of them with the scriptures,
and see whether their doctrines and principles laid down as the subject of their books,
or our doctrines and principles laid down in answer to theirs, agree with the scriptures.
And if thou be impartial in this business, and single in this search and judgment,
I doubt not, but thou wilt in a great measure satisfy thyself,
and be resolved concerning the priests and professors of England,
and us who are called Quakers.
And when thou hast thus done, own and deny them or us, as the Lord shall persuade thee;
for thou mayst fully perceive we differ in doctrines and principles,
and the one thou must justify, and the other thou must condemn,
as being one clean contrary to the other in principles.
And I wish also thou wouldst measure us, and compare us in life and conversation,
and truly judge,
whether they or we do the more follow Christ and his apostles in practice and conversation.
And in all things lay us and them to the line of true judgment,
and with an upright heart judge accordingly; for know this,
there is not any principle we hold,
nor any work which we practice in our religion and worship, but we are willing,
and fully desire may be brought to the bar of true justice,
and in every particular of principle and practice, examined and tried to the full,
and each of us judged in truth and equity,
whether it be they or we that are of the true religion,
and true faith and true worship of God that the apostles were in;
and which of us it is that is in a wrong way, and in a false religion,
and false faith and worship.
And in this we will join issue with them, in the sight of the whole nation,
if they will come forth to trial; if what already is brought forth by them against us,
and by us against them, for these seven years, in disputes, and in printing,
and otherwise, be not sufficient for all people to try us, and judge us by,
whether they or we be in the right.

And now I do appeal to that of God in the consciences of all people in the nation,
to judge between the priests and professors, and all the sects, and us.
Ye have heard their doctrines, and ye have heard something of ours;
ye have seen their conversation, and ye have seen something of ours;
ye have heard them long, and something of us ye have heard for a little season,
and now give your evidence, is it not with them as we have said?
Are not your priests in the steps of the false prophets and of the deceivers,
and do not they seek for their gain from their quarter,
as they did that Isaiah cried against.
Do not they preach for hire and divine for money, as they did which Micah cried against?
Are not they such by whom you have not been profited, as Jeremiah cried against?
Let that of God in you answer to these things.
And are they not proud men, and covetous men, and envious men, and heady high-minded men,
and given to filthy lucre?
And are they not such as through covetousness make merchandise of souls,
and that by good words and fair speeches deceive the hearts of the simple,
such as Paul and Peter declare against?
And are they not such as the true prophets, Christ, and his apostles cried against?
And do they not bring forth the same fruits as did the false prophets, and false apostles?
I leave it to your consciences to be the judge: compare them,
and lay them to the line of true judgment; if you shut not your eyes,
you may see it is thus.
And have we charged them falsely, or have we not spoken the truth concerning them?
We have said they are false ministers and deceivers, and not true ministers of Christ;
and is it not so?
Let the light in your consciences answer.
We have said they have run, and never were sent,
and that they have not profited the people at all; and is it not so?
To the witness of God in you I do appeal,
and let that testify that we have spoken nothing but the truth.
Examine and try in all things that we have charged them with,
and are they not guilty in all things that we have charged upon them?
Let the witness of God in you testify to this.

And what do you judge of them, are they not of that stock which Christ said should come,
and should be wolves in sheep`'s clothing, and should deceive many,
and which John saw were come in his days, and which the whole world went after?
Are not they in the nature of wolves, devouring and tearing the lambs of Christ?
And do not they tear people by causing their bodies
to be imprisoned and their goods to be spoiled?
And do they not deceive many?
And yet they have the sheep`'s clothing, the saints`' words and their practices,
but inwardly are they not ravening?
And doth not the world go after them,
and hath not the world run after them for many ages; and is it not thus with them?
And have they received the gift of the holy ghost,
or are they not made ministers by the will of man, and not by the will of God?
Do they not differ in call, in practice, in maintenance,
and in fruits and effects from the true ministers and true apostles?
And do they not agree with the false prophets, false ministers, and deceivers,
in their call, practice, maintenance, fruits, and effects?
Search the scriptures, and lay them to that line,
and then let the witness in your consciences judge and answer.
And do not they prepare war against such as put not into their mouths?
And do not they feed with the fat, and clothe with the wool?
Do not they oppress the nation and the creation?
And are not they such whose call, and practices, and maintenance, and whole ministry,
have a dependence upon Popery?
doth it not all savour of Popery, and in the main and principal parts thereof,
ordained by the pope?
This may be fully made manifest.
And are not all professors, and sects of people,
such as have the form but are without the power of godliness?
Are not people still covetous, and earthly-minded, and given to the world,
and proud and vain, even such as profess religion, and to be a separated people?
Are not professors as covetous and proud as such as do not profess?
And are not they given to the world,
and doth it not show that they are not changed nor translated,
but death reigns among them?
And is it not manifest that they have taken up the form
of the apostles`' and Christ`'s words and practices,
and are without the life,
and not guided by the spirit of Christ and the apostles in their praying and preaching?
And are not your souls lean and starved?
To the witness of God in you all I speak; which may testify that,
many people have a show of religion without life,
and therefore have not we spoken the truth of them, in what we have said?
In the day of judgment you shall answer it.

And as concerning the Quakers, what do you say of them?
You have seen their conversation;
few towns but some of them have been and are amongst you.
Do not they fear God?
and do not they walk justly and truly among their neighbours, and speak the truth,
and do the truth in all things, doing to all no otherwise than they would be done unto?
And are they not meek, and humble, and sober?
And do not they take much wrong, rather than give wrong to any?
And are they not such as delight in the ways of the Lord?
And do not they deny the world and its pleasures,
and forsake all iniquity more than yourselves?
And do not they take up the daily cross of Christ to all its ways and earthly glories?
And do not they preach in the power of God, and reach to your consciences,
when you hear them?
And doth not the light in you answer that they speak the truth?
And are not their call, and practice,
and maintenance the same as was the apostles`' and
faithful ministers`'? Compare them with the scripture,
and then judge in your consciences.
And do not they suffer many hard and cruel things,
even all manner of evil spoken and done against them falsely for the name of Christ?
Are you ignorant of their great sufferings through this nation?
And what do you think! is their suffering for evil doing,
or is it not for righteousness`' sake?
What harm do they to any, by work or word?
Why are they reproached, and mocked, and scorned?
And why are they put in prisons, and whipped, and thus sorely abused?
Is it for any evil doing, or is it not because they are the servants of the Lord?
Compare their fruits with the priests`' fruits,
their conversation with the priests`' conversation,
and see which be most like the apostles.
These things I leave with you,
that you may come to consider and judge justly of all things; for the Lord God is risen,
and his light in people`'s consciences is shining forth,
and it shall answer to what I say, in this world or in the day of judgment, when we,
and all mankind, shall appear and come forth to trial,
and every man`'s work shall be tried, and all shall receive according to their deeds.

And so gladly would we be made manifest to all the world,
that if after the reading of this book, any be unsatisfied still in this matter;
and if any, especially of the heads and rulers,
have doubts or jealousies raised in them concerning us and the priests,
and would be further satisfied and resolved; for that end let any wise men propound,
for full satisfaction of all sorts of people,
that we (with the consent of the chief in authority that have power in this nation,
who may preserve peace and safety among people,
and thereby to stop all jealousies) may freely and cheerfully, four, ten, twenty, thirty,
more or fewer of us,
give as many of the wisest and ablest of the priests and professors a meeting for dispute,
at any place in England, at what time,
and for what continuance they shall consent unto and fix,
to dispute and controvert betwixt us and them any such thing,
and every such particular as shall or may be objected by any of the heads and rulers,
or other grave understanding men, wherein they are doubtful betwixt us,
and would thereof be satisfied; that by such dispute and opening of such causes objected,
full, and real, and total satisfaction may be given to the whole nation,
and every particular man and member therein.

Otherwise, let the priests, or professors, or any of them,
object what they can against us, in our principles, profession, faith, and practice,
and our whole religion.
And if they shall affirm and allege any one or more things against us,
that any principle we hold, or practice we are found in throughout all our religion,
are false principles and false practices, and not according to truth nor the scriptures,
but shall affirm that our religion is not the true religion,
nor we of the true church of Christ, they shall have free liberty,
to give their best proof and reason for what they affirm and allege.
Yet by the strength of Christ, and in the power and authority of God,
and according to the scriptures, we shall confute all their proofs and strongest reasons;
and on the contrary we shall join our principles, doctrines, and practices,
and all our religion, and every part and particular thereof, to be the very truth,
and agreeing with the scriptures, and, according to that,
shall maintain by lawful arguments and plea, that our religion and worship,
and all that we profess and practice, are according to the mind of the Lord,
and justified of him,
and that whatsoever is and may be spoken against us upon that account is utterly false,
and to be condemned.
And upon this we will engage with them, and with any of our enemies,
of what sect or profession soever,
to the intent only that truth may be manifest and embraced,
and deceit and error discovered and denied.

And also, upon such an engagement, we should agree to have the liberty,
freely and soberly to object against the priests, concerning their ministry, their call,
their practice, their maintenance, and their fruits and effects;
and concerning their church, and principles, and worship, and whole religion;
and shall hear patiently all that can be said in defence thereof by any or all of them,
and shall prove by the spirit of the Lord, and according to the scriptures,
that their ministry is not the true ministry of Christ,
nor they true and lawful ministers of the gospel;
but shall manifest by evident arguments, that their call, practice, maintenance,
fruits and effects, are not according, but contrary to what the true ministry was,
and its call, practice, maintenance, fruits and effects were in the true apostles,
and among the true churches.
And furthermore, by the grace of God, we shall prove their church, their worship,
and their whole religion, in all parts thereof,
to be degenerated from what the true church was, and the true worship,
and true religion were, in the days of the apostles and true churches of old.
And these things shall we make manifest by faithful
and sound arguments according to the scriptures,
that all the earth may know, and all people perceive who is in the truth,
and of the true worship and religion, and who are in the contrary,
and whether the priests, and that which they profess and practice for religion,
or the Quakers, and that which they profess and practice for religion, be of God,
and according to him, and which are contrary; that the end of this long travel,
and war and controversy may be decided and justly ended between us,
and all people may be resolved and satisfied concerning us, and them that do oppose us.

And let all the priests and professors lay aside and give over their houses of correction,
and imprisoning people, and whipping them, and stocking us,
and dealing in this manner of violence and cruelty,
as for years past they have done in defence of their religion, and resisting of ours.
And let them lay aside their carnal weapons, and fighting against our persons,
and imprisoning us about our religion, and let them come forth in sound arguments,
the best they have, and let us see what spiritual weapons they have to resist us,
and defend themselves;
and let us try whether their spiritual weapons or ours be the strongest,
and the most powerful and mighty; and let theirs that are so prevail against the other,
be it ours or theirs.
And this is the way to try the truth, and to make all things manifest, and to decide,
and end the whole controversy between us and them,
which hath been great these many years.

And let the truth be set up and exalted, wherever it is,
and all deceit thrown down to the ground; and let us war with the weapons of the spirit,
against error and false religion one in the other,
but let us not hurt nor imprison persons, nor stock and whip, and make them to suffer.
But let us thresh deceit, and whip and beat that, and all false opinions,
let us throw them down where they are found, whether in them or in us,
and let us fight with the weapons of the spirit, that are spiritual,
and let them fight no longer with such cruel carnal weapons.
And then let such as get the victory, and overcome,
appear to be in the truth of the church, and such as fall and are overcome,
be manifest to be in the error, and of the false church and religion.
And let us love one another`'s persons,
and let them act no otherwise towards our persons, than we do upon theirs,
and towards them; and let them take the liberty to deal with us and our persons,
as we deal with them and their persons, and no otherwise.

And let such, whether they or we,
that cannot prove ourselves to be the true church of Christ, nor of the true worship,
and true religion, nor in the truth, but are found to be in the error,
and out of the truth,-- let such deny their worship and church,
and renounce all their religion, and confess to all the world, under their hands,
that they are and have been deceived, and forever hereafter stop their mouths,
and never profess nor practice any more what they have done in such religion.
Freely upon these issues and conditions we will join trial with them.
Let them appoint time, place, and proffer terms at their own pleasure,
and then to all the world it shall be manifest, and to all people discovered,
whether we have not good ground and sufficient reason, to war against these priests;
and it may perfectly appear that what we have said and written against them,
these divers years, has been upon a good foundation,
and we have had sufficient cause to speak and write against them as we have done;
and none thenceforth shall have cause to say, or doubt,
that what we have spoken and written against them hath been out of malice or envy,
and without cause or good reason; but on the contrary,
all shall know the ground of quarrel is sufficient, and full of equity on our part.

And upon these or any equal terms and conditions, would we,
and are we willing to engage with these priests, and all or any one of these sects,
in a lawful trial, in disputes or writings, for the trial and searching out of the truth,
and the true religion.
And were it not equal and reasonable,
that we had the same liberty among all these priests,
and in their churches or assemblies freely to declare our minds,
and to let forth ourselves in what we hold and profess, without being violently haled,
and beat, and whipped, and sent to prison as we have been these many years?
Which liberty we do freely grant and allow among us to all, to query,
or declare what is upon them, without such violent dealing, or whipping,
or sending them to prisons and houses of correction;
and the same freedom and no other do we desire of others, in this particular,
to declare the truth and what we hold, than what we do and would allow to others;
and that no weapon be used by them against us, nor dealing towards us,
but the weapons of the spirit, the best they have or can bring forth against us.
And let them let creatures alone, and not hurt nor do violence to them,
and no other weapons shall we use against them, nor deal with them by any other thing,
but the weapons of the spirit of God, which is powerful,
and will bring down strong holds; and as for creatures, we shall not hurt,
nor do violence, nor imprison them.
And whose weapons are the strongest, let such overcome.

And such as are overcome, are not the true church; for the true church of Christ,
which is builded upon the rock, the gates of hell cannot prevail against.
And who do overcome, let it be manifest that God of a truth is with them.
And let them all cease to defend their church, and ministry, and religion, with prisons,
and whips, and houses of correction; for by such things was never the true church,
ministry, and religion defended, but only the power and authority of God preserved them,
and resisted all their enemies; and so it is at this day.
And let all cease to cry deceivers, and being afraid they will be deceived;
for if they be the true church, all,
or any one of these sects and professions of religion, then if we be deceivers,
and come among them, they cannot be deceived, if they be in the election;
for neither deceivers,
nor the gates of hell can prevail against the true church of Christ,
nor against them that are elect, which the devil hath nothing in.
And if we be the true church of Christ, and in the election,
then if all the deceivers upon earth come among us, they cannot prevail against us,
nor deceive us; for the elect cannot be deceived.
And upon these terms we may engage with any people and sect upon earth:
therefore come to this, and join with us;
take you the liberty to declare in soberness what you own and profess,
and you shall not be persecuted, nor your bodies nor persons harmed by violence;
and let us have that liberty to declare in meekness and soberness,
and in God`'s authority, amongst you what we hold and profess,
and let us not be persecuted, and dealt violently withal;
and then let it appear whether we or our enemies have a greater testimony,
and more powerful in the hearts of people.
And were not this a way full of equity for the trial of all things?
But doing contrary, as you have done these many years against us, by violence,
and whipping, and persecuting, it shows you have not the spiritual weapons,
nor the authority of God with you, nor among you;
and that is the cause of running to magistrates, and putting in jails, and whippings,
and all violence, because the authority of God`'s spirit is wanting amongst you,
which all the false sects and false churches, since the days of the apostles,
have wanted, to defend themselves and resist their enemies.
And so all sects have been fighting one with another, and killing persons,
and have defended themselves by prisons, and inquisitions, and destroying of lives;
and all these have been out of the power of God, and in the power of the dragon,
and of the beast, who hath caused all to worship, and them that would not,
he hath had power to kill, and hath killed them, by fires, and tortures,
and cruel deaths.
And all these have lost the spiritual weapons,
and been without the power and spirit of God.
And what a church is this of yours, which hath need to be defended by jails, and prisons,
and whips, and stocks, and violent dealing!
This church is not the church of Christ,
for the power and spirit of God defends her always, and not inquisitions, and prisons,
and whips.
These are Cain`'s weapons, and not the weapons of the spirit of God,
whereby his true church was ever defended.
For because Cain`'s sacrifice was not accepted, therefore he slew his brother,
and persecuted him; and thus you that are of Cain`'s seed do the same,
upon the same ground, because your works are rejected,
and theirs accepted with whom you deal thus in this violent way of persecution and wickedness.

And this is the Protestant church, so called, and her ministers,
with whom I am now dealing, which seems to be the true church,
and more than the church of Rome.
For you Protestant ministers do deny and cry against the church of Rome as a false church,
and her ministers to be deceivers, which in itself is very true,
yet your hypocrisy in this doth appear, and your double mindedness; for let me tell you,
while you cry against the church of Rome as a false idolater,
and a persecutor of the true church, and against her ministers as deceivers,
and contrary to the apostles, your spirits are the same,
and your works the same in nature, and in particular, though not in measure.
This work of yours to imprison people, and whip them, and put them in the stocks,
and beat them, and abuse their persons, who do but speak against you and your religion;
is not this work of the very same nature as the work of the Romish church?
She to defend herself hath inquisitions, and banishment, and many cruel tortures,
and with these things she defends herself,
killing and afflicting the bodies of people that oppose her, and deny her religion;
and you have stocks, and whips, and houses of correction,
and put great fines and tasks upon people, and banish them out of towns,
and spoil their goods,
and cast them into prison who oppose your church and deny your religion.
And is not this equal and justly according in nature
to the persecution that is in the Romish church?
And what difference between the defence of the church of Rome and your church of Protestants?
They have their inquisitions, and you have your houses of correction;
they have their slavery in the gallies, and you have whips and stocks;
they have their divers torments, and cruel dealings towards persons that oppose them,
in one manner,
and you have your torments and cruel dealings towards us in another manner;
though not in the same measure, yet in the same nature:
what difference between you and them?
And herein doth the hypocrisy of the Protestant church and their ministers appear,
in that they cry against and deny the church of Rome
and their persecution and cruelty acted against others,
and yet in nature and manner practice the very same upon us,
as in England this day is witnessed.
And not only in this particular may the church and
ministers of the Protestants be condemned for hypocrisy,
but also in many other things,
even the most of their practices in their worship are of the same nature,
and by the same spirit, which the practices of the church of Rome are acted by and in.
And not only so, but it may be truly proved and made manifest,
that many of your church practices have proceeded from the church and
pope of Rome who did ordain and institute many of your practices,
and a great part of your worship,
which is performed in the church and by the ministry of the Protestants, so called;
and this in its time and season I may make fully appear, and discover to the nations;
and I may show in the particulars,
what particulars of the worship and practice in the Protestant
church had their rise and original in the church of Rome.
Though they are minced with diminishings and addings,
according as their imaginations have guided them,
they still retain the strongest taste and savour of the church of Rome,
and had their beginning and original there.
And though in the performing thereof,
they may be altered and changed in appearance and form,
they are perfectly the same in ground and nature, as springing from the church of Rome,
and she is the mother of the Protestant church,
and of the most of her practices and performances in worship.
And this may be proved, as, God willing, upon occasion, as the Lord moves,
I may show that though the church of the Protestants have deserted the church of Rome,
yet their ministry, its call, and ordination, and its practice and maintenance,
have a dependency upon the church of Rome,
as being the original of that which is by them therein practised,
though in some things deviated from the perfect form and practice thereof.
And also the whole worship, all they, particulars in relation to the Protestant church,
and ministry, and worship, have a dependence upon the church of Rome,
as being the first original thereof.
And though they cry against her and her ministers, and have denied her,
yet is she the mother from whom proceeded the Protestant church, ministry, worship,
and practices; and this may be manifest at full that the Protestant`'s church, ministry,
and worship, chiefly taste and savour of the church and worship of Rome,
and had their original out of her.
And also further may be showed, that the Protestant church, and worship, and ministry,
are not another in nature and being, than the Romish church, ministry, and worship,
but are sprung therefrom as branches out of the same root,
the ground being one and the same though differing in appearance.
For in her beginning and first dissenting from the Romish church,
she did not deny her in ground and being, as not being at all the church of Christ,
but only in some particulars dissented, always, then and to this day,
retaining divers of their practices in worship and church government;
which shows that the Protestant church is not perfectly another, nor her ministry,
government, and worship another; but the same in ground and being,
only digressed and deviated in particulars.
And this may be fully manifest in season, that the Protestant church, and worship,
and ministry, are sprung of the Romish church,-- as a branch out of her,
not contrary to her, nor against her;
and all these things is the Lord discovering and laying open,
that nations and peoples may come to behold the Mother of harlots,
that mystery of iniquity, and all her children,
and may see the state and turning of times and things,
ever since the days of the apostles and true churches; and that all these divers sects,
and all these churches, falsely so called, are risen up one out of another,
from one seed and womb, and though diverse in appearances,
and sundry in practices and professions, yet are they all one in the ground and nature,
sprung from the mother of harlots all of them, and are her children.
And she hath corrupted the earth with her fornications and whoredoms,
and made nations and kingdoms drunk with her cup of idolatry;
but the Lord God is risen and will plead with her, and give her double,
and the holy prophets and apostles shall rejoice over her: and this is coming to pass,
and this I have seen from the Lord, and received it from him,
and thus it came upon me to write.

[verse]
____
The waters have I seen dried up, the seat of that great whore,
Who hath made all nations drunk, through her enticing power;
And caused the whole earth she hath, her fornication cup to take,
Whereby nations have long time err`'d, on whom she long hath sat;
But peoples many are and shall, and multitudes all may,
And nations be converted all, unto another way;
And tongues they are confounded now, and kindreds they must mourn,
And when this all is finished, her whole seat then is torn;
For these all be the great waters, on whom her seat hath been,
And over whom she governed hath, like as a stately queen;
For ages many by-past gone, she hath her whoredoms play`'d,
And kingdoms hath bewitched, which have her power obey`'d,
But now her miseries are seen, her witchcrafts are discover`'d,
And she no more shall men deceive; for day light is appeared:
And the bed woful I have seen, of torments great prepar`'d,
Whereon she must be cast, and plagues must not to her be spared,
But woe to her! the cup of wrath, is fill`'d her to receive,
And as to others she hath done, the same she now shall have:
And drink she must of that full cup of God`'s fierce indignation,
And then shall all her lovers mourn, and make great lamentation,
And I have seen that city great, once populous, rich, and fair,
Laid waste, and all destroyed, and her merchants in despair,
Who through her have gotten gain, themselves for to exalt,
And from afar to traffic come; but now they must lament,
For fire in her is kindled, which must her all consume,
Behold, her smoke ascendeth, day and night, up to heaven.
The antichrist who hath put on, and cover`'d with sheep`'s clothing,
And long rul`'d king, on nations, inwardly ravening;
Who hath devour`'d God`'s heritage, and had a kingdom great,
I have seen him made war against, and truth give him defeat.
Behold, the whore! her flesh is burnt, her beauty doth now fall,
She that is all harlots`' great mother, whose daughters are whores all,
Behold the city great, who once made nations rich and high,
She`'s fallen to the ground and burnt, and none more profit her by,
Behold the antichrist once great, his kingdom is subduing,
The Lord alone forever will rule, his son`'s kingdom is coming;
And the woman that long hath fled, into that place of mourning,
And rested in the wilderness, she is again returning,
And her seed is again springing, and shall replenish nations,
And the man-child must come to rule, forever through generations;
And when this all is come to pass, Oh! then rejoice and sing,
Ye prophets and apostles all, and heavenly children,
When God hath you avenged, upon your enemies all,
Then is the day of praises, for saints both great and small.
____

[.signed-section-closing]
By a servant of Christ,

[.signed-section-signature]
Edward Burrough.

[.signed-section-context-close]
London, the Ninth-mo. 1658.

[.asterism]
'''

Here are the principles of priests, and professors, and pastors in the apostacy,
who have got up since the days of the apostles,
that in this day are risen against the lamb, and against the saints.
For since the days of the apostles, the beast hath had power, the false prophet,
and mother of harlots, which inwardly ravened from the spirit of God,
which have had the sheep`'s clothing, and by that means have deceived the nations,
and got in the kings of the earth, and clothed them with the outside,
whereby the kings of the earth, and the beast, and false prophet, dragon, devil,
mother of harlots, and the great whore have joined together in one against the saints,
overcome them, and cast them into prison, and drunk the blood of the saints,
and prophets, and martyrs.
But now shall the saints and the lamb have the victory,
who kills and slays with the sword, which are the words of his mouth.
Agreeably to the apostle`'s doctrine, "`who wrestle not with flesh and blood.`"
Now the beast, false prophet, and mother of harlots, devil, and antichrist,
that have drunk the blood of the saints, that have the sheep`'s clothing,
these are the killers with the sword, the slayers with the sword,
the imprisoners and persecutors; which was not the work of the true apostles,
true ministers, that kept the faith and patience of Jesus.
The martyrs, the saints, and the prophets suffered.
Now these were in the spirit that gave forth the scriptures,
but the others got the scriptures: antichrists, false prophets, mother of harlots,
the devil, the beast, and all his names, which killed and slew with the sword;
these are inwardly ravening from the spirit of God, the spirit of the lamb,
the spirit of the apostle, who killed and slew with the sword,
"`which are the words of his mouth.`"
So all these names, in the whole christendom amongst all that are called christians,
are got up amongst them since the days of the apostles, which are gone out of the life,
and faith, and spirit they were in, which they had unity in, which was the bond of peace.
These have had the words, but ravened from the life,
and so are all on heaps about the words, and giving one another names.
So look in whole christendom and see what abundance of names there are,
which should be one family; and all these names, horns, and crowns,
and building up and throwing down,
are all a mark among them that have had the words but were out of the life,
which life now is risen, which the apostles lived in,
which they since the days of the apostles have been out of, in many names and heaps,
in the apostacy.
Now with the life is all this fathomed and comprehended, in which is the unity,
which life brings people to know God, and unity with him, and with scriptures,
and one with another; and all are one here, if there be ten thousand times ten thousand.
And ye who read over this book may read and see things
which you never read nor saw printed.
Did ever the lambs worry the wolves?
And did not the wolves get the sheep`'s clothing, and raven after the sheep and lambs,
that they might get among them?
Pride, and wildness, and pleasure have swallowed up people, teachers, and ministers,
that if any be sober and still, presently he is a Quaker! and thus modestly is eaten up.
