[.style-blurb, short="The Quakers Confuted"]
== An answer to many principles held forth by some of those called ministers, teachers, and professors in England; taken out of their several books, with their names to them. And also several other sayings and writings of the priests and professors of this nation, gathered together and answered.

[.heading-continuation-blurb]
Samuel Eaton,
(who calls himself a teacher of the church of Christ, at Stockport in Cheshire,)
in his book called, [.book-title]#The Quakers Confuted,# sent to the Parliament,

Saith in his epistle to the parliament,
then sitting at Westminster "`That they are not to judge of saintship,
according to the large charity of some who are truly good,`" etc.

[.discourse-part]
_Answer._
So here is another doctrine than Christ`'s was, who said,
"`The tree is known by its fruits;`" and '`by their fruits ye shall know them.`'
And the fruits of the spirit are known from the fruits of the flesh.

Again, in the conclusion of his aforesaid epistle he begs pardon of the parliament,
for the thoughts of his heart that he hath spread before them,
and so puts them in the pope`'s place.

Likewise, in his epistle to the reader,
because Richard Waller witnesseth his teacher within,
and bids others to mind the light within them;
and that he was come off from all other teachers, etc. he judgeth this to be delusion;
contrary to John the apostle, who saith, "`Ye need no man to teach you,
but as the same anointing teacheth you, which is truth, and is no lie.`" John 2:27.
And again, in Heb. 8.
'`Ye shall not teach every man his neighbour, and every man his brother, saying,
know the Lord, for they shall all know him from the least to the greatest:
for the Lord will write his law in their hearts, and put his spirit within them,`' etc.

[.discourse-part]
_Principle._
He saith, '`he doth not believe that there is any substantial, essential,
or personal union betwixt the eternal spirit and believers.`'

[.discourse-part]
_Answer._
Although the scripture saith, the spirit dwells in the saints, 1 Cor. 6. and,
'`He that is joined to the Lord is one spirit.`' 1 John
1+++.+++ As though the saints had not union with God,
which the scripture saith they have.

[.discourse-part]
_Principle._ He saith, '`It is palpably false, and blasphemy, to say,
that the saints know all things, and have power to work miracles to the glory of God.`'

[.discourse-part]
_Answer._ Contrary to the minister of Christ, John, who saith,
'`But ye have an anointing from the Holy One,
and know all things.`' 1 John 2:20. And Christ said,
'`Greater things than these shall ye do that believe in me.`'

[.discourse-part]
_Principle._ He saith, '`Though we believe that the spirit of Christ dwells in the saints,
yet we assert the spirit of Christ to be distinct from the saints,`' etc.

[.discourse-part]
_Answer._ How, are they led by the spirit?
how are they led into all truth?
and how are they sanctified by the spirit, and their unity in the spirit?
By which spirit they have unity with God; by which spirit the saints worship him.
And '`He that is joined to the Lord is one spirit;
he that hath not the spirit of Christ is none of his.`' And so they are distinct from it;
but they are not so that have it, and are in unity with it, and one with another.

[.discourse-part]
_Principle._ He saith,
'`Although there be the same spirit in all the saints that gave forth the scriptures,
yet all saints have not the same inspiration of the
spirit that the prophets and apostles had,
so as that they should be able to give forth infallible truths,
and immediately discover the pure and clear will of God,
as the prophets and apostles did.`'

[.discourse-part]
_Answer._ In this he hath showed his ignorance of the spirit, and of the holy ghost.
And himself is the false spirit gone out into the world.
For the spirit of truth shall lead into all truth, and bring to memory Christ`'s words,
and doth inspire into them the things of God,
and doth reveal to every one according to his measure.

[.discourse-part]
_Principle._ '`The spirit doth not communicate according to the capacity in the creature.`'

[.discourse-part]
_Answer._ Then there is none can divide the word aright.
God gives to every man as he will, and reproves the world,
and leads the saints into all truth.

[.discourse-part]
_Principle._ He saith, '`They had not known the signification of the words of Christ,
but by the evangelists,`' etc.

[.discourse-part]
_Answer._ I say, neither he,
nor any one knows the signification of Christ`'s words by the evangelists`' words,
but by the evangelists`' spirit,
and by the same inspiration which thou sayst thou looks not for.

[.discourse-part]
_Principle._ He saith, '`The scriptures do give their own sense, and are a standing rule,`' etc.
And yet thou said a little before, in page 4 '`They are dark,
and are left to you to give a sense.`'

[.discourse-part]
_Answer._ Here then thou confoundest thyself;
the spirit of God is the standing rule which leads them to speak forth scripture,
and not others`' words; and the prophets and apostles`' words,
did not lead to speak forth scripture, but the spirit.

[.discourse-part]
_Principle._ He saith, '`They that had the anointing within them,
had not an infallible judgment,`' etc.

[.discourse-part]
_Answer._ John said, '`They know all things;`' and bid them,
'`Try the spirits,`' whether they were of God.
And said, they had the spirit of God, which spirit is infallible,
and gives an infallible judgment;
which spirit was to try the false prophets that were gone out into the world.

[.discourse-part]
_Principle._ In some places thou said, '`the scriptures were dark, and hard to be understood.`'

[.discourse-part]
_Answer._ And here thou sayst, '`It is plain,
and easily to be understood,`' page 8 Mark thy confusion;
for the scripture is not understood without the spirit.

[.discourse-part]
_Principle._ He saith, '`There is an infallible judgment,
which may be made from the scriptures without the spirit,`' page 9.

[.discourse-part]
_Answer._ Who can judge infallibly without the spirit?
Christ told the Pharisees (who had the scriptures) '`they
were of the devil,`' and judgment they had neglected,
and he did not own their judgment to be infallible.
And the apostle saith, what they knew who were separate from the spirit,
they knew naturally as brute beasts,
Jude 10 and 19. though they spoke high words in hypocrisy.
And there art thou with thy infallible judgment (as thou saidst) without the spirit,
(which is proved fallible.) There is no infallible
judgment to be given that stands without the spirit;
they that judge without the spirit, will judge amiss, and not infallibly,
as the Jews did of Christ, and as the natural brute beasts did which Jude speaks of;
there art thou.

[.discourse-part]
_Principle._ And he further saith in the same page,
'`that the scripture is to be judge of the spirit,
and a light sufficient to judge of doctrine and manners,`' etc.

[.discourse-part]
_Answer._ The Jews had not an infallible judgment that had scripture,
but stood against Christ the light, and judged him to be a devil.
That judgment was not infallible, and their doctrine and manners were not right,
which stood against Christ the light.

[.discourse-part]
_Principle._ He saith, '`The conclusion is,
that the scriptures is the foundation of an infallible
judgment concerning things contained in them,
and not the spirit,`' page 10.

[.discourse-part]
_Answer._ So he hath thrown out God and Christ, and the spiritual man,
who was before the scripture was, who was the cause of the giving them forth,
and the inspiring them through the saints, which the scripture saith,
'`shall judge the world, yea angels.`' And he may say upon this conclusion,
that the world and the devil have the judge, for they will get scripture.

[.discourse-part]
_Principle._ He saith, '`He that can bridle his tongue is not a perfect man.`'

[.discourse-part]
_Answer._ Which is contrary to the apostle James, who saith he is,
and so thou art out of James`' doctrine.

[.discourse-part]
_Principle._ '`But the saints have not Christ in the flesh,`' page 12.

[.discourse-part]
_Answer._ Contrary to Christ and the apostle`'s doctrine, who said,
they were of his flesh and of his bone, and should eat his flesh,
and they that eat his flesh have it in them.

[.discourse-part]
_Principle._ He saith, '`Christ within sufficient for all things to teach them,
and to make them perfect as he is, and as God is.`' '`Now,`' saith he,
'`such a having of Christ as this is, we assume not, nor dare assume.
And we declare against it as a satanical delusion,
and the Quakers are the poor creatures that confess this in them,`' page 13.

[.discourse-part]
_Answer._ And you that are not made perfect by Christ, the truth, you remain out of truth,
in the delusion, and so you are out of the apostles`' doctrine.

[.discourse-part]
_Principle._ The pastor saith, '`that such a voice as comes immediately from God we have not heard,
and such an immediate inspiration as this from God we have not received,
nor do we wait for it,`' page 13.

[.discourse-part]
_Answer._ So showing himself to be of them that God never sent.
So you are as the Jews that could say,
'`Moses heard the voice of God,`' and the prophets heard the Lord`'s voice.
But their own ears were stopped to the voice.
For Christ said,
'`Ye have not heard the voice of God at any time.`' And ye say ye look not for it.
And you that deny immediate inspiration, have denied the power of the spirit,
for that is immediate, and the ministers of Christ witness it.

[.discourse-part]
_Principle._ '`All that pray by the spirit, and speak by the spirit, and do not show a miracle,
are impostors,`' page 14.

[.discourse-part]
_Answer._ Many prayed by the spirit, and spake by the spirit,
that did not show miracles at the tempter`'s command,
though among believers there are miracles in the spirit,
which are signs and wonders to the world, as Isaiah saith.
But these are the impostors that pray, and speak, but not by the spirit of God.

[.discourse-part]
_Principle._ Because the Quakers say, that such as preach and speak, but not by the spirit of God,
are the false prophets which the Lord never sent, this the priest saith an evil design,
wherein lie venom and poison.

[.discourse-part]
_Answer._ They were and are in the evil design, that spoke not,
nor preached not from the spirit of God, and lie in the venom and poison.

[.discourse-part]
_Principle._ He saith, '`though Christ was then in heaven, and spake not,`' page15.

[.discourse-part]
_Answer._ Contrary to the apostle, who said he had spoken to him,
and hath spoken to us by his son, as Acts and Hebrews.

[.discourse-part]
_Principle._ He saith, '`All that are brought to the faith of Christ,
are not built upon an immediate voice that comes from God to themselves,
nor to any others who are their teachers.`' See page 15.

[.discourse-part]
_Answer._ Who shows he never received faith from God, which from him is given,
which faith is immediate: through which faith they have access to God who is immediate.
And he goes about to overthrow all teachers made by the will of God, and by Christ,
and the revelation of Jesus; for how can they be ministers,
if they have not the ministry revealed to them?
So, he that denies revelation, doth not know the son nor the Father;
and denies himself to be any true minister, (but by man`'s will,
which is not immediate,) who minister of the spirit, and are immediate in the spirit,
which thou art not.

[.discourse-part]
_Principle._ He saith,
'`that there may be much fallacy and delusion in revelation.`'
'`That God did not intend immediate teaching,
nor to give out an immediate voice in after ages,
which should direct and guide men in the ways of salvation,`' page 16.

[.discourse-part]
_Answer._ Which is contrary to the scripture, which saith,
'`All the children of the Lord shall be taught of the Lord;`' and,`'
He that is of God heareth God`'s word;`' and that is immediate,
and lives and endures forever.
And there is no fallacy nor delusion in the revelation of God,
but all fallacy and delusion are out of it.

[.discourse-part]
_Principle._ And he saith, '`Timothy had not his knowledge immediately,
and yet he was in the faith.`' And he saith again,
'`The faith which was once delivered immediately from heaven to the saints,
cuts off all from having any faith more delivered from heaven,
and of all other immediate voices from thence.`'

[.discourse-part]
_Answer._ So he hath shut out Christ who is the author of every man`'s faith,
to whom every one is to look, who was before scripture was.
That which was once delivered to the saints, and given to the saints,
the saints now must know, they must know their giver and deliverer,
and must know from whence the faith comes in this age, as well as in the other age.
For if they have but words that speak of the saint`'s faith,
how they had their faith delivered from God;
if the saints now have not their faith delivered to them from God, as those in ages past,
they have but words, as the devil had, who stood against the author of the faith,
Christ the light and the truth, and as the Jews had, but were out of the saint`'s faith,
and stood against them that were in it.
And Timothy had immediate teaching, for he had the testimony of the Lord, 1 Tim.
and thou sayst he had not immediate teaching.

[.discourse-part]
_Principle._ He saith, '`There must not be waiting for an immediate word,
but that word which hath been already to the prophets and apostles;
none have the word spoken as it was to the prophets and apostles,
they must have it mediately,`' etc. page 17.

[.discourse-part]
_Answer._ The word that was spoken to Isaiah, the apostle felt immediately,
which the pastor saith he did not;
for there was no scripture but came by immediate inspiration.
And the word is immediate, and all the ministers of Christ preach the immediate word,
and wait for it, and the outward written words with ink and paper are mediate.

[.discourse-part]
_Principle._ He saith, '`But an overcoming of the body of sin,
such as delivers from all sin in this world,
is expressly against the scriptures,`' etc. page 18.

[.discourse-part]
_Answer._ Contrary to Rom.
6; contrary to the apostle to the Colossians, where he had put off the body of sin;
and contrary to Christ, who saves and cleanses from all sin by his blood,
and blots out all sin.
And '`if Christ be in you, the body is dead because of sin.`'

[.discourse-part]
_Principle._ He saith, '`that Christ is in heaven in his humanity, therefore not to be seen,
not to be heard, not to be handled by us or any others that live upon earth,
and they cannot give their own assurance,`' etc. page 19.

[.discourse-part]
_Answer._ So shows that they were never made ministers by him, who never saw him, nor heard him,
so never handled the word of life from the Father nor the son, nor saw it, nor heard it,
so are the pastors that spoil the flock.
And he is the earthly Adam and humanity,
but Christ the second Adam is the Lord from heaven.

[.discourse-part]
_Principle._ He saith, '`that Timothy was commanded to preach, and yet had not heard, nor seen,
nor handled any thing of Christ,`' etc. page 20.

[.discourse-part]
_Answer._ Contrary to the apostle, who bid him to stir up the gift in him,
and told Timothy he was in the faith, and he was to be strong in the grace of Christ.
And whosoever hath faith, knows Christ to be the author of it,
and knows something from Christ; and so thou hast confuted thyself.

[.discourse-part]
_Principle._ He saith, '`that the saints do not see Christ, for the heavens contain him,`' page 20.

[.discourse-part]
_Answer._ The apostle saith,
'`they sat with Christ in heavenly places;`' so he is contrary to the apostle.
And Christ was in them, and walked in them, and God dwelt in them,
and '`Christ is in you, except ye be reprobates.`'

[.discourse-part]
_Principle._ He saith,
'`The whole mind and will of Christ and God is left them in letters,`' page 21.

[.discourse-part]
_Answer._ The apostle saith, it is past finding out; the unsearchable wisdom,
and the secret things belong to God, and are revealed by the spirit,
and no man knows them but by the spirit.

[.discourse-part]
_Principle._ And he saith, '`The gospel is the letter,`' etc.

[.discourse-part]
_Answer._ The apostle saith, it is the power of God; and the letter kills,
and many may have the form, and deny the power, and so stand against the gospel, which,
is the power of God.

[.discourse-part]
_Principle._ And he saith,
'`The devil shows his spite and spleen in them who say they have the word,
as it was in the beginning, against the scriptures,`' etc. page 22.

[.discourse-part]
_Answer._ That is not so; for they that have the word that was in the beginning,
own the scriptures, and are not against them, but are in that which fulfils them.

[.discourse-part]
_Principle._ He saith, '`that all the saints receive the spirit of Christ,
yet never heard his voice.`'

[.discourse-part]
_Answer._ This is confusion, for the sheep of Christ know his voice.

[.discourse-part]
_Principle._ He saith, '`They are uncovered,`' when commonly they have two caps on their heads:
and the people are covered when they have hats on their heads,`' etc. page 29.

[.discourse-part]
_Answer._ This is according to thy deceitful teaching and learning.

[.discourse-part]
_Principle._ He saith, '`The scriptures is the voice of Christ to them,`' etc.

[.discourse-part]
_Answer._ And Christ said to the Pharisees that had the, scriptures,
they never heard the voice of God at any time.
John 5. For they were not put forth amongst the sheep.
But the sheep heard the voice that gave forth the scripture, and came to the life,
and Christ the end of them.

[.discourse-part]
_Principle._ And he saith, '`There is an immediate voice which speaks within,
which we have never heard, nor do we know it within ourselves experimentally,
and we believe and hope that we never shall know it,`' etc. page 30.

[.discourse-part]
_Answer._ And so shows, that they never knew the spirit of the Father speaking within them,
but follow their own dreams and spirits, and stop their ears against that of God in them;
and that immediate voice within, which is the spirit of inspiration,
and the word of God in their hearts, which men should obey,
they call the voice of the devil, and pray to be delivered from.

[.discourse-part]
_Principle._ And he saith, '`To say Christ is within them,
doing all immediately and infallibly within them,
and so say it is Christ and the spirit within them, and not they.`'

[.discourse-part]
_Answer._ Now this he calls a spirit of delusion.
But the apostle saith, '`I live, yet not I, but Christ in me.`' And,
'`He works all in us, and for us,
after his own good pleasure.`' And this was not a spirit of delusion in them.
And this thou art reprobated from, and found in thy own works.

[.discourse-part]
_Principle._ And he '`said, that which was within them,
was not eternal and infallible,`' when the Quakers asked him, whether it was or not.
He said, '`Nay; that which judged in them was not eternal and infallible;`' and saith,
'`they assert no such thing as that concerning themselves.`' And he saith,
'`Though all the saints have the spirit of Christ dwelling in them,
which is eternal and infallible; yet that this spirit should do all that saints do,
and should say all that saints say,
and should judge for them both of persons and of things after an infallible manner;
and that they should neither say, nor do,
nor judge any thing by any understanding of their own, but the spirit,
all this we deny.`' These are his words, page 31.

[.discourse-part]
_Answer._ Which is contrary to the apostle, who saith, '`As many as are the sons of God,
are led by the spirit of God.`' And Christ acts all in them, and for them;
and '`the fruits of the spirit,`' etc. and '`the spiritual man judgeth all things.`'
And that is it which leads the saints to divide and discern all things,
both temporal and spiritual,
the spiritual wisdom of God which gives them a spiritual understanding,
which men must rule withal, but not with their own, that comes to nought.
And you that have not that which is infallible to judge in you,
know not the spirit of Christ,
neither can you judge of persons or things that have not the infallible judgment,
nor the spiritual man.
Neither have you the word of God in your hearts,
nor Christ which is eternal and infallible, all which the Quakers have,
to judge persons and things.

[.discourse-part]
_Principle._ He saith, '`that children are of the seed as to the church privileges,
and external ordinances of a spiritual nature.`'

[.discourse-part]
_Answer._ (Mark his confusion.) But Christ saith, '`Ye must be born again,
or ye cannot inherit the kingdom of heaven,`' and such be of the church.

[.discourse-part]
_Principle._ He saith, '`If they can but destroy all forms, the power will fall with it;
for the form preserves the power,`' page 37.

[.discourse-part]
_Answer._ Contrary to the apostle; many '`have the form,
but deny the power.`' The power preserves the form, sees the end of forms,
and destroys them, and brings to see before forms were, where forms are not.
For the apostles who lived in the power, denied the Jews`' forms, and Gentiles`' both,
as we do now deny the Popish forms, and yours which you have invented and set up.

[.discourse-part]
_Principle._ '`And an immediate teaching (he saith) of the spirit,
and to wait for secret inspiration of God,
is to subject men to satanical delusions,`' etc. page 40.

[.discourse-part]
_Answer._ Contrary to the apostle, who said,
'`Holy men of God spake as they were moved by the
holy ghost;`' and they were to wait for its revelation,
as in Peter;
and all are in the satanical delusion that are not
in the immediate teachings from the spirit;
and every one that hath this spirit, and the leading of the spirit,
hath that which is immediate.

[.discourse-part]
_Principle._ He saith, '`The prophets and apostles drew people to an outward word,`' etc.

[.discourse-part]
_Answer._ Now, is that which lives and endures forever, outward?
And did not they bring them to Christ the power of God, which is the end of words,
which is immediate?

[.discourse-part]
_Principle._ He saith, '`Is not the gospel an external way,`' etc.

[.discourse-part]
_Answer._ No; the gospel is a living way, which is revealed within,
and is the '`power of God to salvation.`'

[.discourse-part]
_Principle._ '`Are not they seduced (saith he) who are drawn off from the external means,
by which the spirit is given and faith wrought,
to wait for the receiving of the spirit without any word to convey it to them?
Which spirit, when they have it, is not the spirit of truth,
but of delusion,`' etc. page 41.

[.discourse-part]
_Answer._ The spirit and faith are not conveyed to any man without the word,
and they are seduced that rest in the external from the eternal;
and the spirit is not given by external means, neither is faith so wrought.

[.discourse-part]
_Principle._ And he saith, '`They need not any man`'s teaching them,
but as the spirit in the scriptures teaches,
and they need not that any teachings of man should be added.`'

[.discourse-part]
_Answer._ And so by this he hath thrown out himself from being a pastor,
and all other such pastors and teachers.
The spirit is not in the scriptures, but was in them that gave them forth.
And the spirit which gave forth the scriptures, and which was in the saints,
opens the scriptures again, and leads into all truth.

[.discourse-part]
_Principle._ And he saith, '`There is an excess in that scripture which saith,
"`Ye need no man to teach you, but as the anointing teacheth you.`"

[.discourse-part]
_Answer._ And here he speaks as if John did not mean as he spoke, and would make John,
who spoke truth, as false as himself.

[.discourse-part]
_Principle._ And the apostles`' saying to the saints,
'`And ye know all things,`' he calls '`an excessive speech,
for no one knows all things but God,`' page 42.

[.discourse-part]
_Answer._ So contrary to John, the minister of God, and would make him a liar.
So he is in the false spirit gone out into the world.
Contrary to 1 John '`who know all things.`'

[.discourse-part]
_Principle._ He saith, '`Outward teaching is the way and the means whereby the deep, and profound,
and necessary truths of scripture come to be understood, but not immediate,`' page 44.

[.discourse-part]
_Answer._ So he hath denied the spirit to open the scriptures,
immediate inspiration by the spirit, and it teaching;
and set up an outward in the room of it.
Here his spirit is tried again, gone out into the world.
For salvation is immediate, and the means that bring to it,
and none know the scriptures by outward teaching, but immediately by the Lord God.

[.discourse-part]
_Principle._ And he saith, '`Ministerial gifts are not now to be found in the world,
such as the ministers of the gospel had in the primitive time.`'

[.discourse-part]
_Answer._ Therefore no such ministerial work now as was then, nor any such officers as pastors,
teachers, etc. as were then!
He hath proved himself to be one of the false spirits
which went forth from the apostles into the world:
and yet he saith,
'`Christ is with them to the end of the world.`'
And yet saith there is no hearing of his voice,
nor seeing him, nor handling him; so he hath confounded himself,
and showed to all that he hath quenched the spirit.

[.discourse-part]
_Principle._ He saith, '`that the apostle was silent in that point,
that men must be endued with extraordinary gifts.`'

[.discourse-part]
_Answer._ The apostle`'s epistles prove to the contrary, who saith,
'`Without faith ye cannot please God;`' which is a gift, and an extraordinary gift;
and saith,
'`He that hath not the spirit of Christ is none of his,`' which is an extraordinary gift.
So you are another ministry, and other pastors and teachers;
and that which is another gift than the apostle`'s, is not the gift of God.

[.discourse-part]
_Principle._ He saith, '`How comes the apostle to raise up a living to some persons for preaching,
when he saith, that "`they that preach the gospel,
must live of the gospel,`"`' etc. page 48.

[.discourse-part]
_Answer._ It was contrary to the apostle, to preach to raise up a living for preaching;
for he saith,
they were not to preach '`for filthy lucre`'s sake!`' But '`they that preach the gospel,
live of the gospel;`' that is not as you raising livings, who make a trade of the form,
denying the power, which is the gospel.

[.discourse-part]
_Principle._ Here he cries out against gifted men`'s preaching, and saith,
'`Paul prophesied against them,`' page 49. and names
them to be '`such as have itching ears.`'

[.discourse-part]
_Answer._ As he is gone out from the apostles, so he cries up his imagined gifts,
and disowns those gifts which the apostles did not cry against, but said,
every one must minister that had received a gift;
and thou art one of the itching ears gone out from the apostles.

[.discourse-part]
_Principle._ He saith,
'`that their synagogues (commonly called churches)
were not ordained for any spiritual uses,
as for serving God in them,`' etc. page 51.

[.discourse-part]
_Answer._ Which is contrary to all the professed teachers in the nations,
who say they are ordained for the use and service of God, and call them, churches:
but to this I believe he will call his words back again.

[.discourse-part]
_Principle._ And Pharisee-like, he teaches to break Christ`'s command,
'`Be not of men called master,`' and calleth it '`a civil honour.`'

[.discourse-part]
_Answer._ And here he hath proved himself not to be a guide of the way,
and the governor of a man`'s life, for that title, master, belongs to Christ,
and not to any man.
These are his words, and the signification which he gives of that title there;
(see page 52.) And yet he dare presumptuously take it, and plead for it,
(which Christ denied in the Pharisees,) and so impudently break Christ`'s command;
and so hath showed that he walks out of his doctrine, and is a transgressor,
and no minister, but an antichrist.

[.discourse-part]
_Principle._ He saith,
'`The apostle never bred-up any that they needed no man to teach them,`' page 53.

[.discourse-part]
_Answer._ And so giveth John the lie, who saith, '`Ye need no man to teach you,
but as the same anointing teacheth you.`' And the prophet, who saith,
'`Ye need not say every man to his neighbour,
know the Lord,`' etc. and denies the effectual work of the new covenant.
But '`all shall know him from the least to the greatest.`'

[.discourse-part]
_Principle._ He saith, '`Paul denies perfection to himself.`'

[.discourse-part]
_Answer._ Paul did not deny perfection to himself nor others;
but his work was to the perfecting of the saints,
but your work is to keep men from perfection,
and that hath been the ministers`' work since they apostatized from the apostles.
And yet Paul judgeth him again, and saith, '`As many as are perfect are thus minded.`'

[.discourse-part]
_Principle._ He saith, '`There is a contradiction in the letter,`' speaking of the scripture,
page 60.

[.discourse-part]
_Answer._ Showing that he doth not know to what condition it was spoken,
for there is no contradiction in it:
but in them that are out of the spirit that gave it forth, is the contradiction.

[.discourse-part]
_Principle._ And he saith,
'`There is a perfection that respects justification
and not sanctification.`' See page 61.

[.discourse-part]
_Answer._ Now, there is no perfection but where there is sanctification.

[.discourse-part]
_Principle._
And he perverteth the scripture of John, that saith, '`If we say we have no sin,`' etc.
And he saith, '`Whosoever saith he hath no sin, deceives himself.`' See page 62.

[.discourse-part]
_Answer._ So he wrongs John`'s words, and puts he for we, and is charging sin upon the elect,
and so himself is found a liar.
For there is a time for men to see they have sinned,
and a time to confess and forsake sin,
and a time to witness the blood of Christ cleansing from all sin;
and '`he that is born of God doth not commit sin.
And here the children of God are manifest from the children of the devil.`'

And, Eaton, hast thou been preaching and praying all this while,
and never yet heard the voice of God?
The night is upon thee, thou hast no answer from God.

[.small-break]
'''

And as for the rest of Eaton`'s lies, we let them rest upon his own head,
not being worth mentioning;
the witness of God in his conscience shall answer in the day of his judgment.
