[.style-blurb, short="Vindication of a Book Called Some Gospel Truths Opened"]
== John Bunyan, Richard Spenceley, John Burton, and John Childe, in their book that they called [.book-title]#A Vindication of a Book Called Some Gospel Truth`'s Opened,# are these following principles.

And as for Bunyan`'s lies and slanders, they will come upon himself;
they are his own garments.
And for the scriptures which he quotes, they are owned, but not to cover the wolf withal.

In his epistle to the reader he saith,
"`The Quakers will own that salvation was obtained by Christ,`"
('`this is truth,`' saith he,) and but a little before,
he saith, "`They deny that salvation that was obtained by him,`" etc.
And thus he hath shamed his father of confusion that taught him, the father of lies,
who says and unsays; for salvation is owned by Christ and God, and no other.

[.discourse-part]
_Principle._ Again, in the same epistle,
he denies '`that salvation is obtained by Christ within,`' and saith,
'`The scriptures do not prove it,`' and calls it '`fighting against the truth,`' etc.

[.discourse-part]
_Answer._ The apostle saith,
'`Work out your salvation with fear and trembling,`' and that is within.
And '`the ingrafted word is able to save souls,`' and that is within.
And the apostle saith, '`If Christ be not in you,
ye are reprobates.`' And that is not opposite to Christ without them,
nor contrary to the scriptures.
And none know salvation, but who know this '`Christ in you,`' who is the salvation,
and where he is within there is salvation.
And so thou art one of the reprobates, that can talk of Christ without,
and denies him the salvation within.

[.discourse-part]
_Principle._ He saith,
'`The Quakers own Christ Jesus revealed to them in spirit,`' and calls it '`delusion.`'

[.discourse-part]
_Answer._ And yet he saith,
others are carried away with error for not receiving Christ revealed in the spirit;
and this is his patched up stuff, comprehended with the spirit, and with it is judged,
who finds fault with them that have it, and is against them that have it not.

[.discourse-part]
_Principle._ He tells people of the history of the word; and saith,
'`Some have no other witness nor knowledge but the history of the word,
and the relation of others,`' etc.

[.discourse-part]
_Answer._ And yet he is against the revelation of the spirit in the Quakers.
But he is one of the beast`'s officers to fight against the Lamb;
but it is to no purpose, who thus builds up and throws down.

Again, Bunyan is railing against the priests, and runs up into the pulpit himself.
And so the wolf hath got the sheep`'s clothing, and they can speak of Christ without,
who are reprobates, who have him not within.

[.discourse-part]
_Principle._ He saith, '`The Lord Jesus Christ is afar off in his bodily presence.`'

[.discourse-part]
_Answer._ And yet he saith, '`The Lord is at hand.`' And the apostle said,
'`he was in them.`' And Christ said, he would '`dwell with them.`'

[.discourse-part]
_Principle._ He saith, '`They were sealed by Christ`'s death, at his offering upon the cross.`'

[.discourse-part]
_Answer._ And yet Christ must come to save them at the last day!
And the saints witnessed their salvation while they were upon earth,
and said Christ was '`in them,
except they were reprobates.`' And the son of God was come,
and gave them an understanding.

[.discourse-part]
_Principle._ He saith, '`The Quakers witness the teaching within,`' but saith,
'`The apostle witnesseth the contrary,`' etc. page 4.

[.discourse-part]
_Answer._ Why dost thou wrong the apostle, and put thy lies abroad, when the apostle said,
and Christ said, the spirit of the Father spoke in them.
And the apostle said, the law and the covenant of God were in their hearts,
and the anointing was within them, to teach them.
But why fightest thou against the apostle`'s teaching, the apostle`'s doctrine,
and Christ`'s doctrine?
Dost thou not see thy weapon now fails thee?
Thou hast cast thyself without, and have not the apostle and Christ corrected thee here?

[.discourse-part]
_Principle._ And to prove '`that the blood of Christ was shed
before the world was,`' he brings a scripture,
which saith, '`The Lamb slain from the foundation of the world,`' etc.

[.discourse-part]
_Answer._ Here all may see, whether this be a fit man to teach,
or whether he be not one of the novices, I leave it to all to judge,
who have a just measure; for the scripture saith, '`since the world,`' and thou sayst,
'`before the world was.`'

[.discourse-part]
_Principle._ He saith, '`that the son of Mary, God-man, is absent from his church.`'

[.discourse-part]
_Answer._ Contrary to Christ`'s words, '`I in them, and they in me:`' and,
'`I will be with you to the end.`' So one of the blind prophets, contrary to John,
who saith, '`We are in him that is true;`' and thou sayst he is absent from his church.
And the apostle said he was the head of the church.`'
But of your church we believe he is not the head,
but will grind you to powder.
And thy words and thy doctrine are corrected by Christ and the scriptures.
And Christ said, '`Where two or three meet together in my name,
I will be amongst them,`' and the saints were '`flesh of his flesh,
and bone of his bone.`'

[.discourse-part]
_Principle._ He saith, '`To be justified by Christ,
is not to be justified by the spirit within,`' and that
Christ within doth not work out justification for the soul,
but we must look out for salvation unto that man,
that is now absent from his saints on earth;`' these are his words.

[.discourse-part]
_Answer._ Corrected by the apostle, who saith, '`He works all in us,
and for us;`' and yet thou sayst that Christ is absent from his saints on earth,
who art corrected again by the apostle, who saith,
'`Christ is in you,`' and contrary to Christ, who is the saviour of the soul.
And men are justified through faith, and that is within, in the heart,
which is held in a pure conscience.
And Christ is in the saints, who is their justification;
and the apostle preached Christ in them, and where he is, there is justification;
and they who have his light and receive him not, there is condemnation.

[.discourse-part]
_Principle._ And he saith, '`The Quakers are deceived, because they say, Christ is within them,
kept down by something within them.`'

[.discourse-part]
_Answer._ Corrected by the apostle, who saith to the saints,
'`Christ in you the hope of glory;`' and he was pressed
down '`as a cart with sheaves.`' And Christ was in prison,
and they visited him not; and hungry, and ye fed him not;
and thou never knew Christ formed in thee, nor the reigning of the seed,
which is the heir of the promise of God.
How was the Lamb slain from the foundation of the world, but among such as thou art?
And reprobates may talk of justification, in whom Christ is not;
ye who witness him not within, he is not your justification.

[.discourse-part]
_Principle._ And his principle is, '`that the place where Christ shall come to judgment,
is at the mount of Olives, on the east side of Jerusalem.`'

[.discourse-part]
_Answer._ Thou hast put him far enough off from thee, and hast not yet judged thyself,
(and Christ is come to judgment,) and so art one of the false prophets,
who bid people look for him beyond the sea, '`Lo here,
lo there:`' but who are come to Christ, the light, the life, they need not go forth;
they who abide here are sealed by the spirit, and put not off the good and evil day.

[.discourse-part]
_Principle._ He saith, '`It is a delusion of the devil, and a dangerous doctrine,
to bid people follow the light within them.`'

[.discourse-part]
_Answer._ They are in the dangerous doctrine, and the delusions of the devil,
that draw people from the light within.
And thus he opposes the foundation of God,
the '`light which lighteth every man that cometh
into the world,`' and the doctrine of the apostle,
who saith,
'`the light that shines in their hearts`' must '`give them the knowledge of the
glory of God in the face of Jesus.`' So he is one of the devil`'s ministers,
opposing the foundation of God, drawing people from that the apostles drew them to;
for no one comes to the kingdom, but who comes to the light within them.

[.discourse-part]
_Principle._ He saith, '`that every man hath not the spirit of Christ within him.`'

[.discourse-part]
_Answer._ But John said,
'`Every man that cometh into the world is enlightened.`' And Christ said,
'`I will send you the comforter, the spirit of truth,
which shall lead you into all truth; and he shall take of mine, and give it unto you;
and he shall reprove the world of sin;`' the spirit shall.
Mark! '`every man;`' here are saints, disciples, and the world.
Get from under this if thou canst, for under reproof thou art come,
and that which doth reprove the world is manifest to them;
and the wicked quench the spirit, but the saints are led by it; and here are all men.

[.discourse-part]
_Principle._ And again thou sayst, that it is a filthy error to say,
that that light which lighteth every man that cometh into the world,
will lead man to the kingdom of righteousness and peace.`'

[.discourse-part]
_Answer._ Thus he is splitting himself against the rock, and striking against the foundation;
for every man that cometh into the world is enlightened,
that through the light he might believe, and believing in it,
he might not abide in darkness; and this he makes insufficient,
when he that doth not believe in the light is condemned.
And thus the spiritual Sodomite and Egyptian is blind, raging about the door.
And no man comes to the kingdom of righteousness and peace, but by the light within:
and so he is in the filthy error himself, denying the light, and hating it.

[.discourse-part]
_Principle._ Thou sayst, '`Christ is the light of the world,
and yet not in every one that cometh into the world.`'

[.discourse-part]
_Answer._ Corrected by John, who saith,
'`he doth enlighten every man that cometh into the world.`' And '`the
light shines in darkness,`' and the darkness cannot '`comprehend`' it;
and '`he that hates the light`' is enlightened,
and '`will not come to it because it will reprove him.`'
That which doth manifest to man an understanding of reproof,
is within him, and hating it, that condemns him.
And the saints believed in the light, and they abode not in darkness,
which unbelievers do, and stumble, which the others do not.

[.discourse-part]
_Principle._ And he saith, Christ was not in his disciples when he said,
'`I am the light of the world.`'

[.discourse-part]
_Answer._ And so is corrected by Christ, who saith, '`I in you, and you in me.`'

[.discourse-part]
_Principle._ He saith, '`They that will come to justification, must go to Christ`'s grave without,
and to mount Calvary,`' page 9.

[.discourse-part]
_Answer._ The scripture saith, ye need not go up to heaven, nor say,
'`who shall go over the sea for us, and bring it unto us that we may hear it, and do it;
but the word is nigh, in thy heart.`' Deut. 30.
So corrected by the scriptures.
And the angel said unto them that went to the grave without,
'`Why seek ye the living among the dead,
he is risen;`' and the saints '`sit with him in the heavenly
places,`' and need not go to mount Calvary for him.

[.discourse-part]
_Principle._ He saith,
'`The light wherewith Christ doth enlighten every one that cometh into the world,
is but a creature, and is not a spirit,`' page 10.

[.discourse-part]
_Answer._ John saith, '`All things were made by him, (made by the light,) in him was life,
and the life was the light of men:`' and this shines in darkness,
and the darkness cannot comprehend it.
The foundation of God, which was before any creature was made, is the power of God,
Christ Jesus the light; and the prophets`' and John`'s doctrine they stumble at, who say,
the light by which all things were made and created is a creature,
and so thou art corrected by the scripture.

[.discourse-part]
_Principle._ He calls the light '`conscience,`' and a poor
dunghill creature that will convince of sin.`'

[.discourse-part]
_Answer._ Which light was before conscience was, or creature was, or created or made light was.
He made the sun, the moon, etc. and the light which was before these were made;
and he is life and spirit too.
For that which convinceth of sin is above the creature; checks him, and reproves him,
and lets him see when he goeth astray from the Creator, and that is the light of Christ,
with which all men see their salvation, with that which lets them see their sin.

[.discourse-part]
_Principle._ He saith, '`The law doth not lead men to Christ, but under the curse,`' page 17.

[.discourse-part]
_Answer._ That is to them that transgress it.
Solomon said, '`the law was light.`' And David said, '`the law was a light unto his feet,
and a lamp unto his paths,`' and so led him, and will lead them that do it,
from the curse, and redeems from under it, of which law Christ is the end.

[.discourse-part]
_Principle._ He saith, '`It is not the faith and works together that justifies in the sight of God,
but it is faith and good works that justifies in the sight of men only;`' and saith,
'`Works will not justify in the sight of God.`' And he saith,
that '`works are only to justify so far as to show their faith to be true before men.`'

[.discourse-part]
_Answer._ Abraham was not justified to men only by his obedience, but to God,
and where there is faith there is justification, which faith works by love.
And the saints`' faith and works were not only to justify them in the sight of men,
for the work of God is to do what he saith, and his will;
which they who do not are not justified, but to be beaten with stripes.
And they who seek to be justified by their faith and works in the sight of men, are dead,
faith and works both.

[.discourse-part]
_Principle._ He saith, '`They are no christians that do not hold Christ absent from his church;
but antichrists.`'

[.discourse-part]
_Answer._ Which is contrary to the scriptures, which say, they are flesh of his flesh,
and bone of his bone,`' and they are as nigh together as husband and wife.
And thus he is ignorant of the great mystery, Christ and the church,
which Christ is the head of.

[.discourse-part]
_Principle._ He saith,
'`that the light wherewith Christ (as he is God)
hath enlightened every man that cometh into the world,
is not the spirit of Christ,`' page 19.

[.discourse-part]
_Answer._ And so makes that which comes from God and Christ, not spirit,
(as he is God,) and thus the man is beating the air.
He saith, '`Christ was God that lighteth every man,`' etc.
And yet (saith he) not with the spirit!`' How then
come men to be condemned for not believing it?
So thou hast reproved thyself, and art blind, and fallen into the ditch.

[.discourse-part]
_Principle._ And again thou sayst, '`Though Christ, as he is God, doth give every man a light,
(which is conscience,) otherwise called nature!`'

[.discourse-part]
_Answer._ And so thou hast given those new names to the light of Christ,
contrary to the apostles, as thou mayst read, John 1:2. John doth not tell us,
that it is conscience or natural light, as thou dost;
and the light which every man that cometh into the world is enlightened withal,
was before all things, and by it all things were made.
So it was before any naturals were,
and is that which gives all men the wisdom of God to order the naturals;
so by the scriptures thou art reproved.

[.discourse-part]
_Principle._ And he saith, '`Christ will not give his spirit to the world.`'

[.discourse-part]
_Answer._ But Christ said, he would send his spirit to reprove the world,
and that is sent to them;
and that which doth reprove them is manifest to them in the world,
to their own understanding, and in them, which spirit leads the saints into all truth.
There is no man reproved, but it is within him, manifest to his understanding.
And if he quench the spirit that reproveth him, he is not lead by it,
and that is the condemnation of the world, '`that light is come into the world,
and men love darkness,`' etc.
And this thou calls not spirit.
Now this is the condemnation of them whose consciences are seared,
and of them who have the created and natural lights, the sun, the moon, and stars;
which light was before they were.

[.discourse-part]
_Principle._ And thou sayst, '`The scripture plainly denies that conscience can justify,
though it may condemn.`' See page 23.

[.discourse-part]
_Answer._ Which is contrary to plain scripture, where the apostle saith, Rom. 2:15.
'`Their consciences either accusing or excusing.`' And again saith he,
'`Herein do I exercise myself,
to have always a conscience void of offence towards
God and towards men.`' And the light condemns,
which you call conscience.

[.discourse-part]
_Principle._ He saith, '`that the gospel is called the ministration of life,
but not of condemnation.`' Same page.

[.discourse-part]
_Answer._ But they are condemned that obey not the gospel of Christ.
And the scripture speaks of '`a savour of death unto death,
and a savour of life unto life, and the gospel is so, the power of God.

[.discourse-part]
_Principle._ He denies '`that Paul bid the saints listen within,`' etc.
See page 25.

[.discourse-part]
_Answer._ Whereas Paul said, '`that the light shined in their hearts,
to give the knowledge of the glory of God in the face of Jesus Christ.`'
And it was the treasure '`in the earthen vessel;`' and Christ was '`within
them.`' And '`the ingrafted word,`' was able to save their souls:
and the '`hidden man of the heart.`' And he had '`revealed
his son in them,`' and many other scriptures.
And he saith, he '`served the law of God with his mind.`' And yet thou sayst,
'`He did not bid any listen within.`' And he said,
'`the word was in their hearts to obey it, and in their mouths:`' and can they obey that,
and not listen '`within,`' and do that, and not have their minds stayed upon the Lord?

[.discourse-part]
_Principle._ He saith,
'`The light doth not shine in the consciences of them that he lost.`' See page 26.

[.discourse-part]
_Answer._ But John saith, the light shines in darkness, but darkness cannot comprehend it,
and there is that of God in the children of disobedience, and reprobates,
as in Rom. 1. and 2. chap.

[.discourse-part]
_Principle._ And he denies '`that every man hath the light.`'

[.discourse-part]
_Answer._ Contrary to John, who saith,
'`That is the true light which enlighteneth every
man that comes into the world.`' John 1.

[.discourse-part]
_Principle._ He saith, '`It is a counterfeiting of the new birth,
for men to follow the light wherewith men coming into the world are enlightened,`' etc.

[.discourse-part]
_Answer._ None come to the new birth,
but they who come to the light which every man that
comes into the world is lighted withal;
which believing in, they are children of the light.
Believing and receiving it, they receive power to become the sons of God.

[.discourse-part]
_Principle._ He saith, '`To say that Christ is risen within,
there is no scripture to prove it.`' See page 28.

[.discourse-part]
_Answer._ Doth not the apostle say,
'`Christ formed in you?`' And '`Christ in you the
hope of glory?`' which hope purifies as God is pure.
And Christ being within, doth he not arise there before all waves be still?
and shall he not arise with healing under his wings?
How ignorant of the letter are the priests grown, and much more of the mystery?
Gal. 4. and Malachi.

[.discourse-part]
_Principle._ And whereas thou sayst, thou art '`confident,
that while some would persuade others that they have no sin,
their consciences will tell them they lie.`' See page 41.

[.discourse-part]
_Answer._ The apostle told the Romans that they were made free from sin;
and the Romans did not tell the apostle, that their consciences told them he lied,
as thou sayst.

[.discourse-part]
_Principle._ He saith, '`The body of Christ is out of the sight of all his saints,`' etc.
See page 47.

[.discourse-part]
_Answer._ The apostle saith,
'`they sat with Christ in heavenly places:`' and the saints are '`flesh of his flesh,
and bone of his bone,`' and the church which he is head of, is his body.
And every one that eats his flesh, knows his body given for the life of the world;
and the body of Christ is not out of the sight of the saints that are in the church.
Therefore you ministers and teachers, that say Christ`'s body is out of your sight,
are not saints; neither are you of his church, which is his body;
neither have you eaten his flesh,
nor known that which is given for the life of the world,
but are out of the sight of the church which is his body.

[.discourse-part]
_Principle._ And thou sayst, '`They shall have a greater judgment without them,
than they shall have within them,`' etc.
See page 48.

[.discourse-part]
_Answer._ The scripture saith, '`If ye judge yourselves, ye shall not be judged of the Lord.`'

[.discourse-part]
_Principle._ And that place in Jude he brings, to prove '`that all men have not the spirit,`' etc.
See page 49. Where he saith, '`They walk after their own ungodly lusts;
these be they who separate themselves, being sensual, and have not the spirit,
who went in Balaam`'s way.`'

[.discourse-part]
_Answer._ Jude shows that they went forth from the spirit,
and turned the grace of God into wantonness.
And this doth not make for thee or to thy purpose, but rather against thee;
and the same spirit that reproves the world leads the saints into all truth.

[.discourse-part]
_Principle._ He saith, '`that God did not give the law that people should live in it, etc.
See page 49.

[.discourse-part]
_Answer._ And the scripture saith, that they that did the law had life,
and were justified by it: for '`Do this and live,`' saith God to Moses;
and therefore thou wouldst make God a liar, who cannot lie; who sayst,
that God did not give forth his law that men should have life.
Are not the curse and the death in the transgression of it?
Christ is the end of the righteous law,
who is the light that doth enlighten every man that
cometh into the world,`' which believing in,
he comes to be a child of light: which light thou blasphemously calls conscience,
or natural, which light is Christ, the foundation of God,
which doth enlighten every man that comes into the world,
that with the light they might see Christ who hath enlightened them,
the foundation of God, from whom light comes.
And the apostle saith, '`the law is spiritual, and just,
and good;`' and so thou art carnal, not yet come to the law which is spiritual.

[.discourse-part]
_Principle._ He saith,
'`He that will but observe the motions of that light which every man hath within him,
(say they,) so as to obey and close in with it, to follow it,
shall undoubtedly save himself from the wrath to come:
now this is clearly a great error,`' thou sayst.
See page 50.

[.discourse-part]
_Answer._ Contrary to John`'s doctrine, and Christ`'s, who saith,
'`The light that doth enlighten every man that cometh into the world, is the true light,
that men through the light might believe.`' Therefore they are enlightened;
and he that believes in the light shall not abide in darkness, nor in error,
nor in condemnation, but shall have the light of life.
Saith Christ, '`I am the light of the world;`' and he saith moreover,
'`Believe in the light,`' before they be children; '`Believe in the light,
that ye may be children of the light.`' So every man is
enlightened with a light before they are children,
with the true light.
He that believes in the light is a child of the light:
he that doth not believe in the light, the light condemns him.

[.discourse-part]
_Principle._ And whereas thou sayst, '`The law gives not life, nor justifies.`' See page 50.

[.discourse-part]
_Answer._ It is false, thou art mistaken in the scriptures, and rebuked by them.
The law gives life to him that obeys it, and lives in it: and he that doth it lives,
and is justified; the doer of the law is justified, and not the hearer only;
and the law is righteous, and just, and good.
But Christ Jesus, the law and the spirit of life,
which is the end of God`'s righteous law, is the justification to life;
God`'s righteousness, who is the end of the other law.
And the apostle Paul saith, '`The law of the spirit of life in Christ Jesus,
hath made me free from the law of sin and death.`'

[.discourse-part]
_Principle._ And thou wouldst make it an error to say,
the saints are saviours of the world.`' See page 50.

[.discourse-part]
_Answer._ The apostle said, when he wrote to the saints, he should save himself and others,
and this was by the power of Christ.
And Jude saith '`others saving with fear,`' but '`hating
the garments spotted with the flesh.`' Now thou art a deceiver,
and not a saviour both of thyself and others, and ignorant of the power and the spirit.

[.discourse-part]
_Principle._ He saith, there is no such scripture as faith,
'`the light within the conscience.`' See page 52-53

[.discourse-part]
_Answer._ Contrary to the apostle, who saith, the light shines in their hearts,
and is not there the conscience?
2 Cor.
4+++.+++ And Christ saith, "`They will not come to the light,
lest their deeds should be by it manifested, and they by it be reproved,
and this is not conscience, nor nature.
And the apostle Paul saith, '`Our rejoicing is the testimony of our conscience,
that in simplicity and godly sincerity, not with fleshly wisdom, but in the grace of God,
we have had our conversation in the world.`'

[.discourse-part]
_Principle._ '`The new covenant which God promised to write in their
hearts;`' he calls '`the law by nature.`' See page 52.

[.discourse-part]
_Answer._ And thus he is stumbling at the corner stone, and errs in his judgment;
for that which orders nature is above nature, and all naturalists,
and transgressors call it natural.
