[#ch-3.style-blurb, short="Concerning James Parnel`'s Death"]
== Doctor Glisson`'s paper concerning James Parnel`'s death in prison, the lies that are in which are not worth mentioning, but will fall upon themselves; but here is one of their lying slanders taken off. They who strike at the rock, split themselves; and the blood of that innocent, lies upon their heads.

[.discourse-part]
_Principle._ In the preface he saith,
'`that the most knowing part of these Quakers have
received their principles from Rome,`' etc.

[.discourse-part]
_Answer._ It is false, for the instructions which they have received are from Christ,
who was '`glorified with the Father before the world began,`' and before Rome was,
or revilers either, which makes the world to rage.
The corner stone, the light,
'`which lightens every man that comes into the world,`' and was before it was;
which makes the beast, and the false prophet, and the pope,
and you to arm yourselves against the lamb and his light,
which he doth enlighten every man that cometh into the world withal.
And the priests`' instructions have been from Rome,
to set up their schools to make ministers, and temples east and west,
with a cross at the end of them; and the tenth, which they imprison men to death for,
and their preaching by the hour glass,
and naming their colleges and mass houses by the saints`' names:
your instructions have been from Rome to do these things;
but the Lamb shall have the victory.
Glory to the Lord in the highest forever.
