[#ch-4.style-blurb, short="George Emmot"]
== George Emmot, who calls himself a spiritual Quaker converted. Who is turned with the dog to the vomit, and gone in the way of Core, exalting himself, and gainsaying truth, and gone in the way of Cain, into his first birth, and turned against the second.

Did God smite thee for thy pride?
Did God let thee see the false worships in the steeple-houses in the sheep`'s clothing?
Did God let thee see the deceit of the tithes in the priests?
Did God let thee see the vanity of respecting of persons, and honouring of the creatures?
Wast thou turning from these things, as thou confessest,
and art thou now turned to them again?
By whom the way of truth comes to be evil spoken of.
Is not thy latter end worse than the beginning?
Will not all thy words be thy burden, and fall heavy upon thee?
Thy time is not past, George Emmot.

And as for all the revilings, scoffings, and mockings in thy book,
they are not worth mentioning among sober people, and raking in the dust for.
Hast thou turned the grace of God into wantonness,
which had taught thee to deny the ungodly lusts of the world,
and would have brought thee to salvation, and so forsaken the covenant of the Lord God,
the law in thy mind, and in thy heart,
whereby thou might have been taught to know the Lord?
But now thou art run out to teachers that may be removed into a corner,
that will poison thee, and that do put some into corners and prisons,
because they will not give them maintenance.

That which brought thee to leave off thy ribands, and vanities, and lusts of the world,
was the grace of God which thou hast turned into wantonness,
and published it to the nation.
(See page 6.) And thou art turned to that which the grace taught thee to deny.

[.discourse-part]
P+++.+++ He saith, '`The steeple-house is a holy place, more holy than a house,`' see page 8.

[.discourse-part]
A+++.+++ The pope hath taught thee this,
and his teachers and thou are gotten into the holy place like the Pharisees, and,
as says the apostle, have defiled it:
and thus your and the pope`'s doctrine is got up
since you have apostatized from the apostles,
which apostles brought the Jews off the holy places thou speaks of;
and while you and they have been in these holy places, you have been in the unholiness.
