[#ch-5.style-blurb, short="Quaking Principles, Dashed to Pieces"]
== Henoch Howet`'s book, entitled, [.book-title]#The Quaking Principles, Dashed To Pieces by the Standing and Unshaken Truth.#

He hath dashed himself to pieces upon the rock,
as his torn language in his book discovers.
And his principles are here as followeth:
a great part of which book of his is not worth mentioning, but turned back upon himself,
who must bear his own burden in the day that burns as an oven; that his works are tried,
he shall remember; to the witness in him I speak.

[.discourse-part]
_Principle._ He makes '`the scripture to be the only weapon
whereby Christ overthrew the devil.`' See page 3.

[.discourse-part]
_Answer._ Who bruiseth his head, and was before scripture was.
Yet the scripture is for correction and doctrine, furnishing the man of God in his place,
and Christ the seed was before scripture was.
And all them that have scripture and not Christ, cannot overcome the devil,
you and the Papists doing his work; for they that overcome him, it is with the power,
and those have the scriptures of truth, which the devil is out of.

[.discourse-part]
_Principle._ He saith, '`The scriptures is the hope.`' See page 4.

[.discourse-part]
_Answer._ Which is contrary to the scripture, which saith,
'`Christ is the hope;`' and they that had the scripture, stood against the hope, Christ.

[.discourse-part]
_Principle._ He saith, '`There is nothing in man to be spoken to, but man.`' See page 5.

[.discourse-part]
_Answer._ How then ministered the apostle to the spirit?
And Christ spake to the spirits in prison;`' and
Timothy was to stir up the gift that was in him:
and the spirit of the Father speaks within them,
and the light shines '`in the heart,`' which God hath '`commanded to shine out
of darkness.`' And the son of God is revealed '`in me,`' saith the apostle.
Here the scriptures are for correction of thee, and reproof of thee, who said,
'`There is nothing to speak to in man, but man;`' for the apostle saith,
'`That which may be known of God is manifest in man,
for God hath showed it unto them.`' Rom.
1+++.+++ And the apostle was manifest to every one`'s conscience in the sight of God,
and that was of God which the children disobeyed.

[.discourse-part]
_Principle._ He calls that '`a dark delusive light.`'

[.discourse-part]
_Answer._ John calls Christ the light,
'`that lighteth every man that cometh into the world,`' which we speak of,
so he is fighting against the foundation of God that stands sure.
And thus the man is striking at the rock, and splitting himself; and is not come to John,
but is as dark as the Pharisees and heathen,
whose darkness cannot comprehend the light that John saith,
'`lighteth every man that cometh into the world;`' that shineth in the darkness,
that is the true light.
John 1. chap.
So you that deny the light which Christ hath enlightened
every man that cometh into the world withal,
are the enemies of Christ, that would not that he should reign over you,
who are by him to be slain;
and so that scripture which he mentions there in page 10 stands for himself,
who gets his words, and calls him Lord, but doth not do as he saith.
And ye all that are in the darkness stumble at the scriptures,
who see not the '`light that lighteth every man that cometh into the world.`'

[.discourse-part]
_Principle._ He saith, '`They that deny the honour of men, are witches and wizards,`' page 14.

[.discourse-part]
_Answer._ Wilt thou say that Mordecai was a wizard, and had a familiar spirit,
that would not bow to Haman?
And the apostle found fault with them that worshipped the creature more than the Creator,
who is God blessed forever.
And all the familiar spirits and wizards fell down
and worshipped Nebuchadnezzar`'s image,
while Daniel could not bend to their image nor inventions.

[.discourse-part]
_Principle._ And again thou saith, '`They that love God, and love Christ,
keep his commandments.`' See page 14.

[.discourse-part]
_Answer._ And thou art bringing many scriptures to oppose the commands of Christ, who saith,
'`Be ye not of men called master.`' So thou art seen not to be of the spirit of Christ,
but the spirit that is gone out into the world, that is, antichrist,
and opposeth his doctrine who is the end of the prophets, and was before Abraham was;
and so hast given judgment of thyself, that thou neither lovest God nor Christ.

[.discourse-part]
_Principle._ And he here accuseth Paul, and saith, '`Paul saith, he is not perfect.`'

[.discourse-part]
_Answer._ When Paul saith, '`As many of us as are perfect,
are thus minded,`' and brings himself in the number;
and speaks '`wisdom among them that are perfect,`' page 15.
