[#ch-6.style-blurb, short="Apostacy from the Perfect Rule of Scriptures"]
== John Timpson`'s book, called, '`The Quakers`' Apostacy From the Perfect Rule of the Scriptures Discovered.`'

A true title is this, to his book, of his own condition,
as his book doth witness himself in the apostacy,
whose work is to oppose the light which doth '`enlighten every
man that cometh into the world,`' that John bore witness of.
So opposing the covenant of God, of life, and peace,
and the foundation of God which stands sure, Christ Jesus, he may as well say nothing,
or do nothing.
But the stone is set upon his head, and the foundation of God is laid,
witnessed by the prophets, Christ, and the apostles;
and the scriptures are owned by them in scorn called Quakers,
and the light they speak of, who are come out of the apostacy,
and so from among the apostates.
And as for the lies and slanders in his book, they are not worth mentioning,
but they shall turn upon his own head, whose immodesty hath discovered them.

[.discourse-part]
P+++.+++ In his preface to the reader, he saith, '`It is an expression of a dark, deluded mind,
to say that God is not distinguished from the saints.`'

[.discourse-part]
A+++.+++ But God and Christ are in the saints, and dwell in them, and walk in them;
and he in whom Christ is not is a reprobate, and out of the apostle`'s doctrine.

[.discourse-part]
P+++.+++ He saith, '`we have broken the everlasting covenant of God.`'

[.discourse-part]
A+++.+++ Because we own the teaching of God by his spirit,
and the light which doth enlighten every one that cometh into the world,
which is the covenant of God.

[.discourse-part]
P+++.+++ He saith, '`The scriptures is the rule of life.`' See page 4.

[.discourse-part]
A+++.+++ Contrary to Christ, who said,
'`the spirit should lead them into all truth.`' And they that are the sons of God,
'`are led by the spirit of God.`' And the churches were to hear what the spirit saith,
for the spirit led them to speak forth scripture.

[.discourse-part]
P+++.+++ He saith, '`It is a contradiction, and a confused senseless thing,
to preach the word of faith in the mouth, and in the heart.`' See page 6. Again he saith,
'`Most senseless is this profession of Christ in the mouth,
and believing in him with the heart, God that made all things.`' These are his words,
page 8.

[.discourse-part]
A+++.+++ It is not a senseless profession to preach the word of faith in the heart,
and in the mouth; and to say, '`God will dwell in you,`' and '`the word is in the heart,
and in the mouth.`' The word is God; and thou art senseless and fallen into confusion,
in the contradiction, out of the apostle`'s doctrine; for the apostle saith,
'`Christ in you,`' and '`with the mouth confession is made to salvation.`'

[.discourse-part]
P+++.+++ And he calls it '`a notion, to say that Christ lighteth all,
and that therefore the light is Christ.`'

[.discourse-part]
A+++.+++ So here he is kicking and spurning against the light, Christ,
'`that lighteth every man that cometh into the world,`' which is the rock,
the foundation of God, the corner stone, which is fallen upon thy head,
and all are in the notion that are out of it.

[.discourse-part]
P+++.+++ He scoffs at the Quakers, because they say, '`they have the word of God in them.`'

[.discourse-part]
A+++.+++ Christ`'s '`name is called the word of God.`'

[.discourse-part]
P+++.+++ He saith, '`God blessing or blasting his own word to some,
according to the different ends intended by himself.`' See page 9.

[.discourse-part]
A+++.+++ Now the word of God is not blasted: God never blasts his own word,
but it is they that disobey the word that are blasted.
For the word of God doth its service, and accomplisheth the end which it goeth forth for,
and doth not return in vain.
And it the sword of the spirit; and that is not blasted.
It is a '`hammer and a fire,`' and it lives and endures forever.
So thou art blasted, who sayst,
'`God blasts his own word,`' and art to be cut down by the word,
of God for thy blasphemy.

[.discourse-part]
P+++.+++ He saith,
'`The Quakers are deceivers,`' because we say '`that Christ is
not in outward observations and forms.`' And John Bunyan saith,
'`that he is distinct from the saints,`' and would have him in the forms, etc.
See page 13.

[.discourse-part]
A+++.+++ We say he hath triumphed over the ordinances, and blotted them out,
and they are not to be touched; and the saints have Christ in them,
who is the end of outward forms, and thou art deceived,
who thinks to find the living among the dead; and Bunyan is deceived, who said,
'`He is distinct +++[+++separate]
from the saints;`' and so you are a company of pitiful teachers.

[.discourse-part]
P+++.+++ He saith,
'`Every true christian doth believe that the holy scriptures
alone are to be the object of faith,`' etc. page 17.

[.discourse-part]
A+++.+++ So he hath thrown out God the giver of them, and Christ the author of them;
for many have the scriptures, and deny Christ the author and object of faith.

[.discourse-part]
P+++.+++ He asketh, '`Did you ever read of law and testimony in the heart?`' etc.
See page 18.

[.discourse-part]
A+++.+++ Yea, God saith,
'`I will write my law in their hearts.`' The law was in David`'s heart;
the law was in the apostle`'s heart.
'`The testimony of Jesus is the spirit of prophecy,`' and that is in the heart.
See Heb.
8+++.+++ Rev. 19:10.

[.discourse-part]
P+++.+++ He saith, '`The covenant of God is not to all in the church of Christ.`' See page 19.

[.discourse-part]
A+++.+++ Which is contrary to the scriptures; for where the church is, there is the covenant,
the head Christ Jesus.
And God saith, '`I will give him for a covenant to the Gentiles;`' those are the heathen.
And '`I will make a new covenant with the house of Israel,
and with the house of Judah;`' and these are called the people of God.
And therefore thou art in the fall, in ignorance, and a man without understanding,
and affirms thou dost not know what;
and silence would become thee better than to publish thy shame in print,
for they are not in the church of God, that are not in the covenant of God.

[.discourse-part]
P+++.+++ And he saith, '`The scripture is the sure and perfect rule.`' See page 20.

[.discourse-part]
A+++.+++ The scripture saith, Christ is the bishop of the soul;
and God hath all souls in his hand.
And many have scriptures, but the bishop of their souls they know not,
but they remain in death, and the life they want that gave them forth,
and so are all on heaps about the scripture one with another, and calling them the rule;
but the spirit of God that led them to speak forth the scriptures,
was the rule to the saints and holy men of God:
and they that are in the transgression will kill one another about their words,
but the spirit leads to see them again, and brings into unity with them and God.

[.discourse-part]
P+++.+++ He saith, '`It is blasphemy to say, that Christ is in them as God and man,`' etc.
See page 23.

[.discourse-part]
A+++.+++ Doth not the scripture say, '`Christ in you,`' and '`God will dwell in you,
and walk in you?`' And are not the saints of his flesh and of his bone?
And are they not partakers of the divine nature?

[.discourse-part]
P+++.+++ He saith, '`It is a fancy to say, the eternal word of God is in them.`' See page 26.

[.discourse-part]
A+++.+++ Thou art in the fancy in whom the eternal word is not witnessed; and under the fire,
and sword, and hammer, to be hammered down.
And so art corrected by the apostle, who saith,
'`Let the word of God dwell in you richly,`' the '`ingrafted word
which is able to save your souls,`' and the '`immortal word.`'

[.discourse-part]
P+++.+++ He saith, '`The scripture is the only rule of knowing God,`' etc.
See page 26.

[.discourse-part]
A+++.+++ Christ saith,
'`None knoweth the Father but the son,`' who spoke among them that had the scripture;
and so he hath excluded the son, as the rule of knowing the Father, who reveals him.
For many had scriptures who knew not the Father, nor knew the son, nor heard his voice,
as in John 5.

[.discourse-part]
P+++.+++ He saith '`All those that are without the scriptures, are without all comfort,
and hope, and God.`' See page 26.

[.discourse-part]
A+++.+++ Here then is thy doctrine, that none have comfort, none hope, none have God,
but who have scriptures.
Abraham will tell thee otherwise, and Enoch; for those knew God, and walked with him,
and knew hope and comfort: and Joseph and Jacob,
God was with them before the scriptures were written.
And Christ was promised before the scriptures were written;
and many have the scriptures and not the comfort, nor the hope,
but stand against Christ as the Jews did.
And many may have the comfort, that have not read the scriptures.

[.discourse-part]
P+++.+++ He saith, '`The only judge of all error is the scriptures,`' etc.
See page 37.

[.discourse-part]
A+++.+++ So he hath excluded Christ, and the spirit, and the spiritual man, and the saints,
and God the judge of all, who was the author of the scripture.

[.discourse-part]
P+++.+++ He saith, '`The apostle doth not say that God in these last days doth speak,
or will speak unto us by his son; but God hath already in time past spoken by his son,
and that speaking is to these last days, and we are not to look for any other speaking,
or revelation,`' etc.
See page 39.

[.discourse-part]
A+++.+++ And so by this thou hast denied the scriptures, and the authority of them,
which is Christ Jesus, and denied the apostles`' doctrine, and the new covenant,
where the law is written in the heart and mind, and all are taught of God.
Thou hast thrown down and laid waste Christ`'s commands, who saith,
'`Learn of me.`' And the command of God, who saith, '`This is my beloved son,
hear ye him.`' And so art ignorant of the scriptures and the power of God.

[.discourse-part]
P+++.+++ He saith, '`It is abhorred dotage they are bewitched with, to say,
they witness forgiveness within,`' etc.
See page 41.

[.discourse-part]
A+++.+++ Thou shows thou never knew a saint`'s life, and that which cleanseth from all sin,
and the testimony within of forgiveness of sin;
for where it is forgiven it is forgiven within.
The apostle saith, '`If Christ be in you,
the body is dead because of sin.`' And many may speak of Christ without them,
and the body of sin not dead.
And so the wolf may get the form of godliness,
and the devil may confess the son of God in words.

[.discourse-part]
P+++.+++ He saith, '`It matters not much if the sense be in the scriptures,
whether the words be there or not.`' See page 47.

[.discourse-part]
A+++.+++ And yet he saith, the scripture is the rule and the word;
and so by that means have all men run into their senses,
into confusion from the words of the scripture, which is not to be added to,
nor taken from, nor can it be broken, nor is it of any private interpretation;
and the scriptures are the words of God, and Christ is the word, and in him they end,
and the spirit is the rule.

[.discourse-part]
P+++.+++ He saith, '`Doth not Christ approve of the Jews`' opinion,
in thinking that in the scripture they should have eternal life?`' And he said,
'`Christ refers them to the scriptures to find life.`' See page 48.

[.discourse-part]
A+++.+++ Whereas Christ said,
'`They would not come unto him that they might have life;`'
and bid them believe in him whom God had sent,
who was the end of the scriptures.
And Christ did not approve of them that thought to have eternal life in the scriptures.

[.discourse-part]
P+++.+++ He saith, '`to say that the light of Christ is not received from the scriptures,
it is an abominable thing to be asserted.`'

[.discourse-part]
A+++.+++ But the light is received from Christ; and many had the scriptures, as the Jews,
but stood against the light as you do now, and did not receive it,
that had the scriptures which testified of it.
And the light cannot be blotted out, but, it doth condemn,
and it leads to the knowledge of God, and to eternal life.

[.discourse-part]
P+++.+++ He calls it a fancy of an idle brain, to witness the law of God written in the heart,
that is different from the moral law,`' etc.
See page 61.

[.discourse-part]
A+++.+++ The scripture saith, '`I will write my law in their hearts,
and put it in their inward parts,
and I will make a new covenant with the house of Israel,
not according to the old.`' And this is the covenant with Israel,
not according to the old; and so they are in the fancy,
and idle brain that are out of the new covenant of light, Christ, both Jews and Gentiles,
and all false christians.

[.discourse-part]
P+++.+++ He saith, '`This I do deny,
that the perfection of the whole law of God is written in man`'s heart,
so as to know it and do it, as it is written in the prophets and apostles,`' etc.
See page 64.

[.discourse-part]
A+++.+++ Here thou hast discovered thyself to be in, the unbelief, and limitest the Holy One,
as if God is not the same, and Christ the same yesterday, today, and forever.
And none know the prophets and apostles, but who have the same covenant as they had,
and the same law and spirit.
And whereas thou art opposing those that say the word is within them,
and the light is within them, and the spirit is within.
And because they say those are in unity, and are one,
which makes thee appear as one offended, who must be ignorant still.
He that is ignorant, let him be ignorant still;
but the light in thee shall see they are one.

[.discourse-part]
P+++.+++ He saith, '`That none have ever had such attainments of Christ a redeemer,
without the help of the scriptures,`' etc.
See page 65.

[.discourse-part]
A+++.+++ Now Abraham, and Enoch, and Noah,
and Adam had the promise of Christ before scripture was written.
And the gospel is the power of God; and many may have the form and not the power,
and eternal life is not in them, nor the power of God.
For Christ is the power of God, who saith, '`Ye will not come to me,
that ye may have life;`' who was before scripture was,
and all the attainments the scripture speaks of are in him,
and he is not attained to without life.

[.discourse-part]
P+++.+++ He saith, '`Where did ever any say,
that they went through the law to Christ?`' This he judgeth and saith,
'`They be strangers to the life of God that say so,`' etc.
See page 71.

[.discourse-part]
A+++.+++ Contrary to the apostle who saith, '`I through the law am dead to the law,
but alive unto God.`' And '`the law was our schoolmaster
to bring us to Christ.`' And again he saith,
'`The righteousness of the law is fulfilled in us.`'

[.discourse-part]
P+++.+++ He saith, '`All notional light is from Christ whatsoever,`' etc.
See page 72.

[.discourse-part]
A+++.+++ Now notion is imagination, and that is not properly called light,
and therefore thou mistakest, for light is not notion,
but is the thing itself that is from Christ.

[.discourse-part]
P+++.+++ Again he denies, '`that Christ hath enlightened every man that cometh into the world,
with light sufficient, if they obey it, to lead them to eternal life,`' etc.
See page 73.

[.discourse-part]
A+++.+++ Yet thou sayst,
every one hath so much light as shall leave all men without
excuse before the great tribunal of Jesus Christ.
And yet sayst, that which leaves them without excuse is not sufficient,
and so would make God unjust and unrighteous.
But the light which doth enlighten every man in the world,
is sufficient to lead them to eternal life, believing in it and receiving it; and,
not believing in it, is sufficient to condemn them.
But all who believe in it shall see and receive their salvation.

[.discourse-part]
P+++.+++ He saith, '`It is a contradiction in itself, and a speaking lies in hypocrisy,
to deny swearing, and calling of men master, and to witness the teaching of the Lord,
and the spirit to guide into all truth, and to say the spirit is the rule.`'

[.discourse-part]
A+++.+++ They are in the lies and hypocrisy, and transgressors of Christ`'s commands,
that are swearers,
and '`called of men masters;`' and the spirit of truth which leads into all truth,
is the rule and guide of men into truth, as Matt. 5. and 23. chap.
And these are the antichrists, contrary to Christ, that swear,
and are called of men masters; for Christ saith,
'`swear not at all,`' nor be called of men master.

[.discourse-part]
P+++.+++ He saith, '`Christ was in the world, and the world was made by him,
and yet Christ was not in all parts of the world,`' etc.
See page 76.

[.discourse-part]
A+++.+++ He is the light to the Gentiles and Jews, and salvation to the ends of the earth:
and yet he saith, that Christ is not in all parts of the world!

[.discourse-part]
P+++.+++ The light wherewith Christ hath enlightened every one that cometh into the world,
he calls '`a little spark of reason, subject to error and vanity.`'

[.discourse-part]
A+++.+++ Christ is the light, the foundation of God which stands sure,
that which makes manifest all error, and his flesh saw no corruption.
The greater part of his work in his book is to strike at the rock and foundation of God.
There is no error in the light, which enlighteneth every man that comes into the world,
neither is it subject to it, but condemns it, and thee that saith it.

[.discourse-part]
P+++.+++ He saith, page 79. '`All the light is to be understood in words,
and an outward dispensation,`' etc.

[.discourse-part]
A+++.+++ The Jews had outward words and a dispensation, and yet knew not the light Christ,
by the words without life: neither did they understand the dispensation of God.

[.discourse-part]
P+++.+++ He speaks of '`an external ministry,`' etc.
See page 80.

[.discourse-part]
A+++.+++ That which led them to minister was not external,
and the external reaches no further than the external, and that is of men, and by men;
but the eternal reaches to the eternal, which reacheth beyond external.

[.discourse-part]
P+++.+++ John saith,
'`This is the true light that lighteth every man
that cometh into the world;`' and he saith,
'`This is to be understood with limitation:`' and saith,
'`Christ was not in all ages and places of the world.`' See page 81.

[.discourse-part]
A+++.+++ How was he the lamb slain from the foundation of the world?
And how did he minister to the spirits in prison?
And how speaks he in the law?
And how is he the same yesterday, and to day, and forever?
And that is the devil in thee that would have a hold for thee to dwell in,
that would limit Christ the light not to be in every man.
That which darkens every man is the devil, and that which lightens every man is Christ,
without limitation, and he limits that which would limit him, and that understanding.

[.discourse-part]
P+++.+++ He saith, '`he knows not what the true light is, and eternal life,
nor the eternal word, the everlasting gospel, the light which gave forth the scriptures,
and the judge of the world, and the kingdom of heaven within,
and the law of the new covenant, and Christ within,`' these he saith, he knows not, etc.

[.discourse-part]
A+++.+++ We do believe thee.
And yet he goes about to oppose them, and knows not what they are,
and so he fights like a blind man, who knows not the eternal word within, nor the light,
nor the everlasting gospel, which the saints did, and do know within.

[.discourse-part]
P+++.+++ He saith, '`that infants and fools, and such as are born blind,
were never enlightened with the light of Christ,`' which he calls,
'`the light of nature,`' etc.
See page 85.

[.discourse-part]
A+++.+++ Which is contrary to John`'s words, 1 John 9. '`who came for a witness,
to bear witness of the light,
the true light which lighteth every man that cometh
into the world,`' which light is above nature;
and contrary to Isaiah, who said,
'`Fools shall not err in the way.`' And blind men
and infants are enlightened with the light of Christ,
for that is the light in the blind man that reproves
his thoughts and words that are evil;
which believing in, he shall not be condemned, but hath the light of life,
and becomes a child of light.
And in Christ is light, and that is the life of men;
and where there is life in an infant, there is light.

[.discourse-part]
P+++.+++ He calls it '`a fancy and a pernicious error,
to say Christ hath enlightened every man that cometh into the world,`' etc.
See page 88.

[.discourse-part]
A+++.+++ And thus he opposeth John`'s doctrine.
They are in the pernicious error that deny that light that lighteth every man,
according to John`'s doctrine, John 1. who saith,
'`this is the true light that enlighteneth every man that cometh into the world;`'
and the Pharisees stumbled as much at this true light as you do now;
though it shined in their and your darkness, yet your darkness cannot comprehend it,
but it shall be all your condemnation that hate it.

[.discourse-part]
P+++.+++ He saith,
'`The commands of Christ within (Christ and the light)
are inconsistent with the scriptures,`' etc.
See page 89.

[.discourse-part]
A+++.+++ The light within owns the scripture without:
and yet he said it was '`the gift of God,`' and the gift
of God owns the scriptures in their place as they were spoken;
and none know the commands, and scriptures, but with the light within;
and they are in unity, and the light within gives the knowledge of them.
2 Cor.
4.

[.discourse-part]
P+++.+++ He saith, It is a fancy to say the covenant of God is to all men in the world,
and the grace of God hath appeared unto all men,`' etc.
See page 89.

[.discourse-part]
A+++.+++ Contrary to the apostle, who saith,
'`The grace of God which brings salvation hath appeared
unto all men.`' And contrary to the prophet,
who saith, '`I will give him for a covenant to the Gentiles, a light unto the people,
salvation to the ends of the earth,
and a new covenant to the house of Israel and Judah.`'
And they that do not believe this are condemned.

[.discourse-part]
P+++.+++ He saith,
'`It is most desperate and diabolical to talk of a sufficient
light and grace in all to be saved,`' etc.

[.discourse-part]
A+++.+++ And yet thou sayst, in page 73 of thy book,
that every man hath so much light that shall leave men without
excuse before the great tribunal of Jesus Christ,
and men shall only be condemned for not doing things which they
had power and light to do.`' And so thou confoundest thyself;
these are thy words.
And here thou sayst, '`he hath not light sufficient to save.`' Thou calls this '`a fancy,
and prodigious blasphemy,`' page 92. And no man cometh
to salvation but who owneth the light,
which doth enlighten every man that cometh into the world,`' Christ Jesus the saviour.
No man owneth his own salvation,
but who owneth '`the grace of God that brings salvation`' to all,
if they will receive it, to teach them to live soberly, righteously, and godly,
and deny the contrary.
And this grace and light is sufficient, for it brings salvation;
for that which brings salvation is sufficient,
and thou art in the diabolical doctrine that art out of this,
and contrary to what the apostle saith.
And Christ who enlightens all men, says, '`Believe in the light,
and ye shall not abide in darkness, but have the light of life,
and become children of light,`' and so it is sufficient; if not,
how are they condemned by it?

[.discourse-part]
P+++.+++ He saith of the light of Christ,
we '`have made it the corrupt spark of reason.`' See page 92.

[.discourse-part]
A+++.+++ But it is he that calleth it '`the corrupt spark of reason,`' contrary to John,
who saith,
'`it is the true light which lighteth every man that cometh
into the world.`' And we do not make it the corrupt spark,
of reason; for there is no corruption in it, but it leads to true reason,
and there is no true reason but in it; and thy corrupt spark of reason is out of it,
and to be condemned with it.

[.discourse-part]
P+++.+++ He calls it '`an intoxicated notion, and bewitching,
to say that Christ hath enlightened every one that
cometh into the world immediately,`' etc.
See page 93.

[.discourse-part]
A+++.+++ So he would make the light which John bore witness of to the chief priests and Levites,
which doth enlighten every man, etc. not immediate,
and gives these ill-favoured names to them that bear their testimony to it.
But let him split himself against the rock.
Thou art in the intoxicated notions, and in the witchcraft,
that dost not own the light that '`enlighteneth every man that
cometh into the world,`' and art not a witness of Christ,
but contrary to the prophets, and John, who said,
'`This was the true light which lighteth every man that cometh into the
world;`' to which light the apostle bore witness to Jews and Gentiles,
which thou, a reprobate, bears witness against.

[.discourse-part]
P+++.+++ And to bring all people to the light wherewith Christ hath enlightened them,
he calls '`seducing, and sending men to hell, and damnable heresies.`'

[.discourse-part]
A+++.+++ They bring men to hell, and are the seducers, and in the damnable heresy,
and corrupt the reason,
that do not bring men to the light that enlighteneth
every man that cometh into the world,
and so to Christ, but deny it, and such deny life and salvation.

[.discourse-part]
P+++.+++ He saith,
'`that none can be saved by following the light of Christ Jesus,`' which he calls '`corrupt.`'

[.discourse-part]
A+++.+++ The light of Christ Jesus is not corrupt,
who enlighteneth every man that cometh into the world;
that light which they are enlightened withal doth not corrupt,
but lets all men see their corruptions,
which light they are condemned for not believing in,
and believing in which they are saved.
And no man sees salvation, or hath salvation,
but with the light which comes from Christ Jesus, the salvation.
And all that hate the light are corrupt in their doctrines and principles,
ways and words, and such are the antichrists.
