[#ch-7.style-blurb, short="Faithful Discovery of a Treacherous Design"]
== Joseph Kellet, John Pomroy, Paul Glisson, Christopher Feak, John Simpson, George Cocken, and Lawrence Wise; their principles in a book put forth by them, called, [.book-title]#A Faithful Discovery of a Treacherous Design of Mystical Antichrist, Displaying Christ`'s Banners,# are here laid open.

[.discourse-part]
P+++.+++ Ye say, '`God who commanded light to shine out of darkness,`' etc. page 1.

[.discourse-part]
A+++.+++ But ye do not say that the light hath shined '`in your hearts,
to give the knowledge of the glory of God in the face of
Jesus Christ.`' And those were the false apostles,
and devil`'s ministers, and messengers of Satan,
transforming himself into an angel of light, that drew people from the light within,
which gave them the knowledge of the glory of God in the face of Christ,
from whom it came.
It was the work of the true apostles to bring people to the light within,
that shined in their hearts,
to give them the light of the knowledge of the glory God in the face of Christ Jesus;
and they told them,
there was the '`treasure in the earthen vessel.`' So with the false
spirits that are gone out into the world are ye reproved,
ye seven priests.

[.discourse-part]
P+++.+++ They call it '`wine mingled with water,`' to say '`the light doth enlighten
every man that cometh into the world,`' which is Christ,
which brings men off from their teachers, and makes sin manifest.
This ye say '`makes the scriptures unnecessary.`'

[.discourse-part]
A+++.+++ None know the use and value of the scriptures but with light, nor salvation,
nor wine from water.

[.discourse-part]
P+++.+++ And they say,
'`Doth not the light bring men off the glorious mystery of the scriptures,`' etc. page 3.

[.discourse-part]
A+++.+++ We say nay, it brings them to it, to the mystery of Christ Jesus,
from whom light comes; it brings men off from the heathen to God.

[.discourse-part]
P+++.+++ And they say,
'`that the light brings men off the foundation of
the prophets and apostles,`' etc. page 4.

[.discourse-part]
A+++.+++ Which light is Christ, who is the promise to the Gentiles,
the foundation of the prophets and apostles,
which doth enlighten every man that cometh into the world.
And none come to the foundation, but such as come to the light, Christ,
that hath enlightened them.

[.discourse-part]
P+++.+++ They say, '`They are all alienated, and enemies unto God until faith,`' etc.
See page 4.

[.discourse-part]
A+++.+++ So they have denied their schoolmaster, which is until faith,
which will keep them out of the alienation, which is the law.

[.discourse-part]
P+++.+++ And ye call the light, Christ,
who hath enlightened every man that cometh into the world, '`a natural light,`' etc.
See page 5.

[.discourse-part]
A+++.+++ Contrary to John, who saith, it is Christ, by whom all things were made,
before naturals were, sun, moon, or stars.

[.discourse-part]
P+++.+++ To hold forth Christ the light, who lighteth every man that cometh into the world,
they say, is '`to hinder the gospel, pervert the faith,
and at once destroy all good that ever was done,`' etc.
See page 6.

[.discourse-part]
A+++.+++ It is unlikely that it should do so, since Christ is the covenant of God,
who came to save, which light doth lighten every one that cometh into the world,
in which believing they are saved, not believing are damned.
And none come to God nor to the gospel, but who come to the light,
and all men`'s works acted without the light, are to be condemned and destroyed.

[.discourse-part]
P+++.+++ '`To bring people to the light, Christ,
which doth enlighten every man that cometh into the word,
is to bring them from the mediator, and to draw men from eyeing his death, resurrection,
and intercession, etc.`' See page 7.

[.discourse-part]
A+++.+++ Here they are corrected, for none know these things but who come to the light, Christ,
who hath enlightened them; for with the light they see their mediator,
and see his death and resurrection.
And they that come not to the light which lighteth every man that cometh into the world,
may speak of these things but cannot know them;
as the witness in the conscience shall answer in all men;
for the light that shines in the heart gives them the knowledge of them, of the mediator,
death, and resurrection of Christ.
And they say, '`not every man in the world is enlightened,`' and John saith,
'`every man is,`' and so here their spirits are corrected again.
And, '`I will give him for a covenant to the Gentiles,
and for a new covenant to the house of Israel,
and to the house of Judah.`' And they bring these words,
'`Christ in you the hope of glory,`' to oppose John`'s words.

[.discourse-part]
P+++.+++ You say '`none come to God but by Christ,`' and yet do not own
him that doth enlighten every one that cometh into the world.

[.discourse-part]
A+++.+++ And so are not like ever to come to him, though you may talk of him in words,
as the Pharisees and the devils did, and as all the apostate christians do now;
yet not owning his light, with it you are all to be condemned as ministers of Satan,
which are out of the light.

[.discourse-part]
P+++.+++ And you say, '`far be it from you to say that Christ is equally God,`' etc.
See page 8.

[.discourse-part]
A+++.+++ The scriptures say,
he is '`the everlasting Father,`' and his name is called the '`Emmanuel,
God with us:`' and his name is called the word, which is God.
John 1.

[.discourse-part]
P+++.+++ And ye say, '`Whereby man sees the godhead of God,
but nothing of the mystery of the Father, and Christ as mediator.`' See page 9.

[.discourse-part]
A+++.+++ Can any man see the godhead of God, and nothing of the mystery of the Father,
and Christ the mediator?
Doth not he that knows the son know the Father also?
And hath not he that hath seen God, seen the son?
Is not the son in the Father?
Here your spirits are corrected:
for the light that enlightens every man that comes into the world, lets see the one,
and lets see the other.

[.discourse-part]
P+++.+++ You say, '`For a man to say,
the light Christ which enlightens every man that comes into the world, is pure,
and justifies them that obey it, he justifies that which God condemns,`' etc.
See page 9.

[.discourse-part]
A+++.+++ As you say who are with it condemned;
for the light is that which both condemns and justifies, and God doth not condemn it,
for it brings into unity and peace with him, and all are condemned that are out of it,
and none are justified but those that are in it, Christ,
that enlightens every man that cometh into the world,
which is the justification of life to every one that believeth in it;
and every man receiving the light, receives his justification, and hating it,
receives his condemnation to death.

[.discourse-part]
P+++.+++ Again, ye conclude '`the light of Christ is not pure before faith.`' See page 9.

[.discourse-part]
A+++.+++ So have concluded that you seven, Joseph Kellet, John Pomroy, Paul Glisson,
Christopher Feak, John Simpson, George Cocken, Lawrence Wise, never knew law nor gospel,
nor faith from Christ, nor God: for '`the law is light,`' saith Solomon, Prov. 6.
and that is the schoolmaster until faith.
And the law of God is pure, and the law is just, holy, good, and perfect;
and what is just, holy, and good, is pure.
And this ye seven have concluded not pure, the light in the conscience, before faith.
And the law is the light and schoolmaster until faith.
And the light is given to every man to believe,
and '`while ye have the light believe in it.`' And
so men have this light before they believe in it,
and are children.
And this ye conclude is not pure,
so go about to take away that which men should believe in:
they having the light are then afterwards to believe in it;
and with it they see the author of their faith, Christ Jesus, from whom it comes.
So you would destroy the foundation of God, of the prophets and apostles,
which standeth sure; and so are ye found in the spirit of error, and corrected,
knowing neither law nor faith.

[.discourse-part]
P+++.+++ Again they say '`the light,
(which is Christ) with which every man is enlightened that cometh into the world,
doth not discover the sin of unbelief.`' See page 10.

[.discourse-part]
A+++.+++ And did not Christ marvel at their unbelief,
and see and discover the unbelief of the Jews, of whose spirit are ye.
And doth not Christ the light, which doth enlighten every man, discover unbelief?
And do not the unbelievers hate the light, because they know,
the light that manifests their sin will reprove them, which they should believe in?
And yet you say, it doth not discover unbelief,
which is their condemnation that do not believe in it,
but hate it because their deeds are evil.

[.discourse-part]
P+++.+++ And further ye say,
'`that the light that lighteth every man that cometh into
the world bringeth in a legal righteousness,`' etc.

[.discourse-part]
A+++.+++ Doth not the light that enlightens every man that cometh into the world,
bring in the righteousness of God?
and is it not the righteousness of God?
So it corrects you that are in the legal righteousness, and out of Christ,
'`which enlighteneth every man that cometh into the world.`'

[.discourse-part]
P+++.+++ Again you say, '`The righteousness performed by the grace of Christ,
the gospel teacheth to deny it.`' See page 10.

[.discourse-part]
A+++.+++ Now is there any righteousness wrought by the grace of Christ, but what is by Christ,
who is the covenant of grace and the power of God, which is the gospel,
which lighteth every man that cometh into the world?

[.discourse-part]
P+++.+++ They call it '`conscience, or a natural light,`' etc. page 11.

[.discourse-part]
A+++.+++ Which light was before the word conscience was, or a natural light, the sun, moon,
and stars, either; for all things that were made, were made by it.
The natural light, or made lights, are created lights.
He made the sun, the moon, and the stars, they were made.
And here are the natural lights to the natural eye.
And the light that every man is enlightened with that cometh into the world,
was before these were made,
'`glorified with the Father before the world began,`' and before the name conscience was,
or things were made, and named.
And the light doth exercise the conscience towards God and towards man;
which light cometh from Christ the author of faith, which is held in the pure conscience,
who before the world began was glorified with the Father.

[.discourse-part]
P+++.+++ Again, the light which cometh from Christ,
which enlightens every man that cometh into the world, which discovers the evil,
which will give power against it, man walking in it, and brings to the rest,
to the Father, this they call '`free will,`' etc.
See page 12.

[.discourse-part]
A+++.+++ Which light brings out of the will of man, into the will of God, from whom it comes,
to him that is not born by the will of man in which light men do his will,
and know his doctrine.
So here they are corrected again; for the free-will and will-worship,
are out of the light which is Christ, which John speaks of.
And they that hate the light are out of Christ,
and are not made free from the wrath to come;
but they that are in the light are made free from the wrath to come,
in covenant with God.
So you that would set up another light than Christ, are antichrist, in your own wills;
for all will-worship, and feigned humility, are out of the light, in the transgression.

[.discourse-part]
P+++.+++ They say, '`That God made a difference where there was none.`' See page 13.

[.discourse-part]
A+++.+++ And the apostle said,
'`they were all gone astray.`' And God puts a difference
between the precious and the vile,
judgeth righteously, and respects no man`'s person, and makes a difference in judgment.
And they say, '`God checks and chides the wanderings of his people;`' and yet say,
'`God makes a difference where there is none,`' and you are to be checked and chidden.

[.discourse-part]
P+++.+++ Again they say,
'`The children of God are all their life time found groaning under sin,`' etc. page 14.

[.discourse-part]
A+++.+++ The apostle tells you plainly, He that is born of God doth not commit sin,
neither can he, because the seed of God remains in him: and he keepeth himself,
that the wicked one toucheth him not; and these are made free from sin.
And here the apostle corrects you again; for those are not groaning under sin,
when the wicked one toucheth them not, but these reign over it.

[.discourse-part]
P+++.+++ They say,
'`who put men to the light of the eternal word with which they are enlightened,
put men beside the way of life, and put men beside the way of salvation.`' See page 16.

[.discourse-part]
A+++.+++ None know salvation but by the light which comes from the eternal word,
nor the way of life, which is Christ,
which every man that cometh into the world is enlightened withal,
and so the salvation '`to the ends of the earth.`'

[.discourse-part]
P+++.+++ Again they say, '`that the light that lighteth every man that cometh into the world,
shuts up the kingdom of heaven against men,
and takes away the ministration of the gospel, and destroys the ministry of man,`' etc.
See page 17.

[.discourse-part]
A+++.+++ None come into the kingdom of heaven,
but who come into the light which enlighteneth every man that cometh into the world;
it opens the kingdom of heaven, but it destroys man`'s ministration,
and brings in the ministration of God and the gospel.
And this light ye call '`law,`' or '`works,`' that
enlighteneth every man that cometh into the world,
which he that believeth in hath ceased from his own works, as God did from his,
and comes to the end of the law.

[.discourse-part]
P+++.+++ Again they say, '`The scriptures are the means of faith.`'

[.discourse-part]
A+++.+++ And so have thrown out Christ the author of it, and God the giver;
and the scripture is but the declaration of the saints`' faith,
and it saith men had faith before scripture was, as for instance, Abraham and Enoch.

[.discourse-part]
P+++.+++ Again they say,
'`As for the expected dictating the scriptures by the spirit to us as to the writers,
thereof it is groundless,`' etc.
See p. 18.

[.discourse-part]
A+++.+++ So showing of what spirit you are, who with the true spirit are corrected,
that have the scriptures dictated to you,
but not by the same spirit the prophets and apostles had.

[.discourse-part]
P+++.+++ They say,
'`Instruction in the scriptures is the way of sowing the seed in children,`' etc.

[.discourse-part]
A+++.+++ And the scripture saith, '`The seed is the word,`' and Christ is the seeds-man,
who was before scripture was;
and yet '`it doth no good except they eat the book,`' and so they confute themselves.
And many had the scriptures, who stood against the seeds-man as you do now,
and the devil out of the truth makes a cloak of those things,
who will not feed upon the word.

[.discourse-part]
P+++.+++ So the light which lighteth every man that cometh into the world,
which we say is the covenant of God, they say,
'`That is to break down the enclosed garden.`' See page 20.

[.discourse-part]
A+++.+++ This is that which confounds Babylon the great,
and brings it into remembrance with God, and brings the great whore into judgment.
The light, which is the way into the garden of God, breaks down their enclosed garden,
that have apostatized from the apostles.

[.discourse-part]
P+++.+++ They say, '`that the power to jostle out the form is an error,`' etc.
See page 24.

[.discourse-part]
A+++.+++ It was the apostles`' work to bring from the form into the power,
the substance Christ, which was not an error.
But you being in the error, keep people in forms out of the power,
and so not in the apostles`' work.

[.discourse-part]
P+++.+++ Again they here say, '`It is blasphemy to say God is in all,`' etc.
See page 30.

[.discourse-part]
A+++.+++ And the apostle saith, '`God over all, through all, and in you all,
blessed forever.`' Ephes.
4.

[.discourse-part]
P+++.+++ They say, '`It is not a transgression if men pray not, nor preach for many days,
weeks, and months together, though necessity is laid upon them,`' etc.
See page 32.

[.discourse-part]
A+++.+++ Contrary to Christ`'s command,
who bid them '`watch and pray.`' And contrary to the apostle`'s doctrine, who said,
'`Woe be unto him if he did not preach the gospel.`'
Where there comes a woe there is transgression:
so likewise where Christ`'s doctrine is denied.
And the apostle said,
'`Pray always,`' but '`without wrath and doubtings;`' and '`lifting up
holy hands,`' and '`pray for enemies.`' But you pray in the wrath,
and hands full of blood, and persecute Friends, as your jails may witness; so,
as pastor Eaton saith, '`you never heard the voice of God.`' And Micah said,
'`Night is upon priest and prophets, that divine for money,
and preach peace to the people, if they put into their mouths, if not,
they prepare war against them.`' Such have no answer from God.

[.discourse-part]
P+++.+++ They say, '`that apparel is for distinction of qualities of persons,`' etc.
See page 36.

[.discourse-part]
A+++.+++ That is but in the world; for that which distinguisheth persons is the word,
the person of Christ from the persons of Adam in the fall,
and who are in the transgression, and who are out of it,
and who are vessels of honour and dishonour; and your wearing of gold and costly apparel,
distinguisheth you from the apostles`' doctrine.
And the holy women of old who were honourable, it was not the apparel that made them so,
but the hidden man of the heart, which was of great price with the.
Lord; these were brought to do the commands of God.
That honour which is in the world for clothes and respect, God will stain,
which stands in the lust of the eye, and the pride of life, and the lust of the flesh,
and there stands the world`'s honour, in transgression.

[.discourse-part]
P+++.+++ They say, '`It is most true, the Jew inward desires not the praise of men,`' etc.
See page 38.

[.discourse-part]
A+++.+++ Then all that desire the praise of men, and respect to persons,
are not the Jews inward by their own conclusion, but the Jew outward.
And so, priests, judge your work and fruit, how many Jews outward you have begotten;
for that which begets the Jew outward,
which hath the praise of men and respecting of persons, is the outward Jew;
and that which begets the inward Jew, is the Jew within, who hath his praise of God;
and Christ who was the king of the Jews, was not a respecter of persons.

[.discourse-part]
P+++.+++ Again they say,
'`It was not Christ`'s command to give your coats
to the next beggar that asketh them.`' See page 42.

[.discourse-part]
A+++.+++ The scriptures say, '`He that hath two coats,
let him give to him that hath none;`' and the rich will give to the rich,
and thus they affront the scriptures.
God gives wisdom how to distribute, and to whom to distribute,
and how to honour the Lord with the substance;
and so you show yourselves ignorant of Christ`'s doctrine,
in letting so many poor beg at your doors and in the streets,
and yet you will have boot-hose-tops, and double cuffs, and ribands about you,
who are more like stage-players than ministers,
and are not like to give your coat to the next beggar; which double cuffs,
and boot-hose-tops, and ribands,
you have got for tithes of poor people that have hardly a coat to put on;
but they that obey Christ`'s command, that have two coats give to him that hath none.

[.discourse-part]
P+++.+++ Again they say, '`The son of man is not come;
and these are false prophets and false Christs who say he is come.`' See page 43.

[.discourse-part]
A+++.+++ And so they call John a false prophet, who tells that the son of God was come.
1 John 5:`''`For we know that the son of God is come,
and hath given us an understanding.`' And you are
the false prophets and antichrists in the world,
that deny Christ come in the flesh.

Again we say, you are them that come not in by the door,
who draw people from the teachings of God,
from the '`light that doth enlighten every man that cometh into the world.`'

[.discourse-part]
P+++.+++ And you tell them '`it is natural.`' See page 43.

[.discourse-part]
A+++.+++ The light is the door,
'`which doth enlighten every man that cometh into the world;`'
but ye blind Sodomites are groping for the door,
but cannot find it, raging without, and would kill the just who are in the light,
which is the door.
And all are blind, though they say they see,
that do not see the light '`which lighteneth every man that
cometh into the world,`' by whom the world was made.

[.discourse-part]
P+++.+++ Ye say, '`The apostles went out of their own nation without money or two coats,
without a bag either,`' etc.
See page 44.

[.discourse-part]
A+++.+++ Which of all of you in your own nation goes without your stipend, or augmentations,
tithes, or glebe lands?
which of you all will go into your own nation without this?
So not going,
have ye not all judged yourselves by the apostles`' practice which ye speak of?
and with your own words?

[.discourse-part]
P+++.+++ And ye say, '`That the greatest part of the persecution in the nation is ceased,`' etc.

[.discourse-part]
A+++.+++ Ye say so that to persecution are turned,
whose persecuting fruits have been seen more within these late years,
than for several scores, nay these hundred years past;
and you are turned the persecutors of them that will
not put into your mouths that you do no work for,
and for speaking to you, as your jails bears witness.

[.discourse-part]
P+++.+++ Again they say,
'`To be called of men master,`' (and so transgress Christ`'s
command,) '`is but a civil respect to their public employment.`'

[.discourse-part]
A+++.+++ Pharisee-like have they showed that they condemn Christ`'s commands,
and unlike ministers of him, but antichrists, that condemn Christ`'s command,
and call it '`a civil respect in their employments.`' For you do not read of Mr. Paul,
and Mr. Peter, etc.

[.discourse-part]
P+++.+++ Again they say, '`That is it which makes many ears to tingle, and is a desolation,
to say God is coming to teach his people himself,
and to redeem them from all their teachers,`' etc.
See page 47.

[.discourse-part]
A+++.+++ Now are the prophets fulfilling,
'`They shall not need every man to teach his neighbour`' or his brother.
Now are people coming to hear the son, who is the salvation to the ends of the earth,
God`'s covenant.
Now is that coming which shall make your ears tingle;
and now are people come to the anointing,
that they '`need not any man to teach them.`' Now are people
ceasing from men whose breath is in their nostrils,
and looking to Christ the Lord, the salvation to the ends of the earth.

[.discourse-part]
P+++.+++ Again they say, '`that Satan, transformed into an angel of light,
is helping on good motions and fair compliances with rules of right,
to an ill end.`' See page 49.

[.discourse-part]
A+++.+++ That is like your doctrine, that Satan should make use of good motions,
and fair compliances with rules of right!
The rule of right and the good are out of his power.

[.discourse-part]
P+++.+++ Again they say, '`Why may not Satan help on mortification,`' etc.
See page 53.

[.discourse-part]
A+++.+++ Nay, that which mortifies is out of the power of Satan; that goes against his power,
and brings down to the death of Christ and his resurrection,
which they that are out of mortification know not.

[.discourse-part]
P+++.+++ And the persecutors, when they have persecuted the children of light,
'`which light enlightens every man that comes into the world,`' say,
'`they expose themselves to suffering.`'

[.discourse-part]
A+++.+++ And this light is it which torments them.
So striking at the light, they strike at the foundation,
as we find these seven men`'s work is to strike at the light, the foundation,
Christ Jesus, so are Satan`'s ministers.
And abundance of lies is their book stuffed with, which are not worth mentioning,
which will turn upon themselves;
in the day of fire and judgments they shall feel their works:
in their conscience the witness shall answer.
They that prison the just in themselves,
turn against them that are in the covenant of light,
where the prisoner shows himself forth; for there is no persecution in the general,
but men have first stopped their ears against that of God within them,
and gone from the truth in their own particulars,
then they turn against them that are in it; and such were always said to be of the devil,
doing his work, out of the truth.
