[#ch-8.style-blurb, short="The Quaker`'s Catechism"]
== Richard Baxter`'s book, called, [.book-title]#The Quaker`'s Catechism.# His principles follow,

[.heading-continuation-blurb]
And his works, which are to be condemned to the fire.
And as for his lies, and railings, and brawlings, and revilings,
we turn them back to himself; for which his own sorrow will be the greatest.

[.discourse-part]
P+++.+++ He saith, at the beginning of his book, in a letter to a friend, etc.
'`To say that any are perfect, and without sin, is the devil speaking in man,`' etc.

[.discourse-part]
A+++.+++ Contrary to the language of the apostle, and Christ,
who bid them '`be perfect,`' and the apostle spoke
'`wisdom among them that are perfect,`' and said,
they were made '`free from sin.`' And it is the devil speaking
in man that speaks for sin while men are upon earth;
for the devil holds up him who makes men not perfect,
but truth makes men free again from the devil, and speaks in man, and says,
'`Be perfect.`'

[.discourse-part]
P+++.+++ He saith, '`Christ doth not condemn men for being called of men master,
and it is not the title, but,`' etc.

[.discourse-part]
A+++.+++ Contrary to Christ`'s words, who saith, '`Be ye not called of men master,
for ye have a master in heaven, even Christ,
and ye are all brethren.`' And thus he tramples upon the commands,
and makes the commands of Christ of none effect,
which is one of the marks that Christ gave to the multitudes to know the hypocrites by;
and so he not only denies Christ`'s commands, but teaches men to break them:
so crucifies Christ, and says they are his ministers;
but that is the antichrist that abides not in his doctrine, as in 2 John.

[.discourse-part]
P+++.+++ And he saith, '`People are tossed up and down like a bundle of feathers,
and novices,`' etc.

[.discourse-part]
A+++.+++ How should they be otherwise than tossed up and down by you, when ye deny perfection,
and call it the voice of the devil speaking,
that speaks of perfection and overcoming sin?
How should you but be the men that toss people up and down with every slight,
being blown up and down with your windy doctrine that is not perfect,
and so make the nations and people like waters?
For all the imperfection is out of Christ, in the first Adam, in sin and transgression,
and in the devil which is out of the truth;
and all the perfection is in Christ the second Adam; the covenant of God,
out of sin and transgression; and so they who are in Christ are new creatures,
and old things pass away, and all things become new.
And so in the second Adam, in the Lord from heaven, above the earthly the first man,
in the perfection, out of the tossing.
Your imitated church, got up since the days of the apostles, is not the true church.

[.discourse-part]
P+++.+++ He saith, '`A true church is guilty of injury,`' etc.
See page 4.

[.discourse-part]
A+++.+++ Contrary to the scriptures, where the apostle saith,
the church is the pillar and ground of truth, without spot or wrinkle, or blemish,
or any such thing.

[.discourse-part]
P+++.+++ He saith, '`God hath commanded a sufficient maintenance in general, for ministers,
and left it to human prudence to judge what is sufficient,`' etc.
See page 7.

[.discourse-part]
A+++.+++ By this he hath forsaken the spirit as judge, and the wisdom of God,
and run into earthly human prudence.
Therefore is there so much oppression for tithes and maintenance for ministers,
and so much making havoc, and prisoning, and persecuting for the same:
and the power is denied which the apostles had, to eat and to drink,
which Christ gave them.
And so you run into the lust for money which you do not work for, and the earth;
and whilst they coveted after that, they lost the faith;
and that is the cause that people have lost the unity, and run all upon heaps,
through coveting and love of money.
Their teachers have lost the faith in which they should have had unity with God,
and one with another, and have pleased him, and had access to him,
and which would have given them victory over the world, the devil, enmity,
and corruption.

[.discourse-part]
P+++.+++ He saith,
'`All that come into the world are lighted with the light of nature.`' See page 7.

[.discourse-part]
A+++.+++ For so he calls the light,
which John calls the true light (which is Christ)
that lighteth every man that cometh into the world;
so is ignorant of John`'s doctrine, and the scriptures, a man not fit to teach,
but is gotten up by an usurped authority, and is not able to divide the word aright.
But with the scriptures thou art corrected,
and the light that lighteth every man that cometh into the world;
by it the natural lights were made, the sun and moon, and so forth.
And men that are born blind,
are enlightened with that light which was before the sun was,
before all things were made, which came a light into the world to enlighten every man,
that all men through it might believe.
Now all men may see how men are mad against Christ, and the apostles`' doctrine,
that bore witness to the true light, and Christ bid believe in it.

[.discourse-part]
P+++.+++ He talks of, and preaches up '`an external word.`' See page 8.

[.discourse-part]
A+++.+++ Which the scripture speaks nothing of, nor the prophets, nor Christ, but saith,
'`the word that lives, abides,
and endures forever:`' and the scriptures of truth cannot be broken.
And God`'s words, and Christ`'s words, are not external.
This is not agreeable to sound words that cannot be condemned,
but is like his doctrine that knows not the eternal.
The ministers of Christ did not tell people of an external word, but an eternal word;
but you being made by the will of man, speak to the people of an external.

[.discourse-part]
P+++.+++ He saith, '`he hath not seen God in glory, nor any man,`' etc.
See page 9.

[.discourse-part]
A+++.+++ We do believe thee, and the priests have not seen him: but the saints saw him,
and Job saw him, and Isaiah saw him, the Lord of hosts, and Stephen saw him,
and Abraham saw his glory; and the apostle saw him and beheld his glory,
the glory of God.
And you are as the Pharisees, that stand against Christ,
that enlighteneth every man that cometh into the world,
that Christ said never saw the shape of God.

[.discourse-part]
P+++.+++ He saith, '`The word infallible, is the pillar of the Popish kingdom,
and the master point of new religion,`' etc.
See page 9.

[.discourse-part]
A+++.+++ Now thou that calls infallibility a Popish point, a new religion,
thy religion thou hast manifested, and thy points that are not infallible;
contrary to the apostle who had many infallible proofs of the spirit of Jesus Christ,
and they who have not are none of his.
And who have the spirit of Christ, have that which is infallible,
and lets them see infallible proofs, as thou mayst read in scripture.
And who have the spirit of God, have that which is infallible.
And the religion which is out of the infallibility, and out of the spirit of God,
is vain, and there is thine and the popes, as your fruits have declared,
got up since the days of the apostles, in the apostacy, fallible;
but that which is in the spirit of God is infallible.

[.discourse-part]
P+++.+++ And thou sayst,
'`thou hast no such revelation as the apostles had as thou knowest of,`' and '`the apostles
were brought to speak infallibly to the church by an infallible spirit,
and neither thou nor the pope hath any such infallibility as the apostles had,`' etc.
See page 10.

[.discourse-part]
A+++.+++ We do believe you,
for you are the false spirits (you and the pope)
that went forth from the apostles into the world,
that Christ said should come; that inwardly ravened from the spirit,
and went forth from the apostles, and only have had the sheep`'s clothing;
and so are the spirits which the apostles bid the saints try (which
went forth into the world) that had the true spirit,
the record, the spirit of God.
And they that have found the record, the spirit of God, try all your spirits,
and find you fallible, ravened from the spirit of God inwardly,
only having the sheep`'s clothing that hath covered the wolf in you all, the devourer.
And so we do believe, neither the pope nor you have the infallible spirit,
being the false spirits that went forth into the world, and led the world after you.
Nations are come to be like waters, you are all so broken into heaps, and sects,
and want the infallible spirit in which you should have unity.
And so have not the son of God revealed among you,
who have not revelation as the apostles had, which we witness,
who are come to that the apostles were in, and so the son of God reigns.

[.discourse-part]
P+++.+++ He saith, '`The holy scriptures are the temporal word,`' etc.
See page 11.

[.discourse-part]
A+++.+++ Now see if this be not an undervaluing the scriptures of truth,
and the words of God and Christ, and of the prophets and apostles,
which cannot be broken;
he calls them a '`temporal word;`' the scripture teacheth no such doctrine,
but thy lying spirit.

[.discourse-part]
P+++.+++ He saith, '`The gospel or word,
is the external light flowing out unto us from the son,`' etc.
See page 12.

[.discourse-part]
A+++.+++ Contrary to the scripture, which saith,
'`The gospel is the power of God unto salvation to
every one that believes,`' so not temporal,
not a temporal light.
And the light which cometh from the son of God,
that lighteth every man that cometh into the world, that shines in people`'s hearts,
that '`gives the knowledge of the glory of God in
the face of Christ Jesus,`' is not temporal;
thou that sayst so art in the delusion.

[.discourse-part]
P+++.+++ He saith, '`The scriptures are able to make men wise unto salvation,
without any more additions, and there are no more to be expected,`' etc.
See page 12.

[.discourse-part]
A+++.+++ Contrary to the scripture itself; and the apostle`'s doctrine, who saith,
'`Through faith they are able to make wise unto salvation.`'
So there is an addition which the apostles adds,
and all the saints and true believers; which is the faith that thou art reprobated from,
and so no minister of Christ, not in the victory, so in the world`'s lusts.

[.discourse-part]
P+++.+++ He saith, '`The soul of man is a spiritual substance,`' etc.
And Magnus Byne saith, '`The soul is not infinite in itself,
but it is a creature.`' And Richard Baxter saith, '`it is a spiritual substance,`' etc.
See page 13.

[.discourse-part]
A+++.+++ Now consider what a condition these called ministers are in: they say,
that which is a spiritual substance, is not infinite in itself, but a creature.
That which came out from the Creator, is the hand of the Creator, in which the soul is,
which brings it up to the Creator that is infinity itself;
which hand goes against him that does evil, in which hand the soul is,
which hand is immortal and infinite;
the hand is infinite which brings it up to God who is infinite.

[.discourse-part]
P+++.+++ He saith, '`Do not they blasphemously make Christ an idol, that call our temples,
idols`' temples?`' etc.
See page 15.

[.discourse-part]
A+++.+++ Christ`'s body was and is the temple of God;
who ended all outward temples made with hands, and so that is no idol,
but others are idols, held up by you and the pope, Jews and Gentiles,
that prison the seed of God in yourselves.
And Stephen was stoned to death for denying the temple, and for witnessing the substance:
so have you almost stoned many to death for denying your idols`' temples.

[.discourse-part]
P+++.+++ He calls that '`most ignorant and sottish dealing, to own Christ`'s commands that bid,
be not called of men master,`' etc. page 18.

[.discourse-part]
A+++.+++ And thus he shows his ignorance and sottishness;
he doth not read Mr. Paul and Mr. Peter;
and they that do so transgress the doctrine of Christ.
And he hath not the spirit of Christ, but is gone out into the world,
where all the false spirits are opposing Christ`'s commands, and the spirit`'s commands,
and so no minister of Christ.

[.discourse-part]
P+++.+++ He saith, '`All the ministers since the days of the apostles,
were to be ordained and called, which the apostles were not,`' etc.
See page 21.

[.discourse-part]
A+++.+++ Doth not the apostle speak of them that usurped the authority?
Yes, we say that all of you, and the pope, since the days of the apostles,
are called by men, and made by men,
who are the false spirits that went forth into the world, that ravened from the true,
so have not heard the voice of God at any time.
So he hath not sent you, but you have usurped the authority, being made by man.
And as no prophecy of scripture came by the will of man,
therefore all that get the scripture in their own wills, out of the holy ghost,
are made by man; such are out of unity with God, with the scriptures, with one another,
and all on heaps about words; and such men make and set up.

[.discourse-part]
P+++.+++ He saith, '`The scriptures is God`'s law,
and a sufficient rule for doctrine and worship itself,`' etc.
See page 22.

[.discourse-part]
A+++.+++ Now many may have the scriptures,
yet if they have not the spirit that gave them forth,
they do not worship God in the spirit; and they that have the scriptures,
and do not the will of Christ, know not his doctrine.
And '`the law is light.`'

[.discourse-part]
P+++.+++ He saith, '`But I must tell you, that, our bells are not carnal, if they were,
they would scarce sound so well, or last so long,`' etc.
See page 23.

[.discourse-part]
A+++.+++ If they be not carnal, then they are spiritual,
and in that all the world will judge thee, that they are things seen,
and so they are temporal and carnal; and what is temporal is not eternal, nor spirit.
The apostle speaks of '`carnal weapons,`' 2 Cor.
10:4. and carnal ordinances,`' Heb. 9:10.

And whereas thou speakest of '`baptizing your bells,`'
etc. have not many bells in England been baptized?
And was not the pope the first author of it?
And we do say that they are carnal and not spiritual, let them sound never so well,
and last never so long.
Though in many towns you have made them to tune psalms,
yet we cannot say that these are spiritual that can tune psalms, neither dare we,
but do judge them that say they are so.
For the scripture calls those ordinances, which were ordinances of God once,
'`worldly and carnal,`' and the sanctuary is called
'`a worldly sanctuary`' when the substance was come.
And so we see, and say, all your sorts of bells, though they may be tunes of psalms,
yet they are carnal, and not spiritual; though indeed poor people, being ignorant,
may well think so, when such as thou say, '`They are not carnal;`' when they are,
and stir up the fleshly nature in people.

[.discourse-part]
P+++.+++ He saith, '`To say a man is freed from the body of sin while on earth,
is part of the Papists`' dung, which they have taught you to feed upon,`' etc. page 24.

[.discourse-part]
A+++.+++ Contrary to the scriptures and the apostle`'s words, who saith,
'`they were made free from sin,`' which was before you or the Papists were.
And contrary to John, who bids them '`try the spirits,`' who saith,
false spirits are gone out into the world,`' which are you and the Papists.
He saith, '`He that is born of God doth not commit sin, neither can he,
because the seed of God remaineth in him.`' 1 John.
And you are in the Papists`' dung spoken of, who plead for sin;
and thou art contrary to the apostles and Christ,
who preached perfection and freedom from sin.

[.discourse-part]
P+++.+++ Again he saith, '`Christ`'s kingdom is a hospital,
and hath no subjects in it but diseased ones,`' etc.
See page 24.

[.discourse-part]
A+++.+++ We read of no such thing in scripture, that '`Christ`'s kingdom is a hospital,
and his subjects are diseased ones.`' But they that follow the Lamb,
in their mouth is no guile, nor spot, nor fault before the throne of God,
and are the elect which God lays no sin to; and they are the faithful, and called,
and chosen, that overcome the world.
And his kingdom stands in power, and in righteousness, and joy in the holy ghost,
and is not a hospital, nor his subjects diseased ones, for he heals them,
and converts them, and washes them; and therefore thou art a liar,
and a man that dost not divide the word aright.
The diseased, or such as come unto Christ to be healed,
he heals them of what infirmity soever it be, and cures them,
and clothes them in the right mind.
Therefore thou art corrected, and worthy of correction;
and all the diseased ones are in your kingdom, ye physicians of no value.

[.discourse-part]
P+++.+++ What can keep the soul from the enjoyment of God but sin,`' etc.
See page 25.

[.discourse-part]
A+++.+++ It is the unbelief in Christ the light, and the offering, and in his blood,
that keeps from the enjoyment of God, who is the way to God,
which the light gives to see.
