[#ch-9.style-blurb, short="The Quaking Mountebank"]
== The author of the book called, [.book-title]#The Quaking Mountebank,# etc. His principles follow.

[.heading-continuation-blurb]
His words are seen in the light, and are condemned for the fire.
The day is coming that thou (whosoever thou art) wilt suffer,
and the witness in thy conscience shall answer.

[.discourse-part]
_Principle._ He saith,
'`the Quakers are no conjurers,`' and yet he calls them '`mountebanks,`'
in his libel called [.book-title]#The Quaking Mountebank,# etc.
See page 5.

[.discourse-part]
_Answer._ They have discovered his works and fruits, and the fire is over his head,
and he proves that he hath the language of a mountebank, by his revilings and railings,
which, among sober people, are not worth mentioning.
And the Quakers`' mountain is the house of the Lord,
established upon the top of all the mountains in the earth: and their rock is Christ,
which will split all mountebanks, that make war against him, in pieces.
And now is seen what is risen against the Lamb and the saints;
and the mouths of the false prophets are opened,
and the inhabitants of the earth are drunk,
and the beast makes war against the Lamb and the saints,
but the Lamb and the saints shall have the victory.
And Quakers are not mountebanks, but the Lord`'s children.

[.discourse-part]
_Principle._ And this mountebank calls the Quakers '`beasts, that have the spirit of God in them,
feeling it,`' etc.
See page 7.

[.discourse-part]
_Answer._ So that it hath discovered his spirit whither he is gone;
and his words shall be his burden, and the Lord will find him out,
though he has not put forth his name.
And those that know the mind of Christ, such he calls beasts,
and so hath discovered himself that he knows it not;
but the saints know the mind of Christ, and spirit of Christ,
and are the sons and daughters of God.

[.discourse-part]
_Principle._ He maketh the steeple-house '`the ark,`' and calls it '`the house of God,`' etc.
See page 9.

[.discourse-part]
_Answer._ A place which Papists set up for mass;
so he shows his ignorance and profaneness against
the saints whose bodies are the temples of God.

[.discourse-part]
_Principle._ And the mountebank saith,
that '`the Quakers are not akin to the Egyptians,`' but yet he saith,
'`they love darkness rather than light,`' etc.
See page 12.

[.discourse-part]
_Answer._ And thus his spirit is rebuked, they that be in Egypt love not the light.

[.discourse-part]
_Principle._ Again he saith, '`that learning is the prime ornament of the soul.`' See page 13.

[.discourse-part]
_Answer._ And so hath thrown away the power, and Christ the-bishop of the soul,
who is its ornament, in which it hath its joy.
And men with their learning prison the soul which is immortal.

[.discourse-part]
_Principle._ And he saith, '`The Quakers are no Pharisees,`' etc.
See page 10.

[.discourse-part]
_Answer._ And the priests of Newcastle call them Pharisees.
Here is Gog and Magog in battle together against the Lamb,
and the royal seed called Quakers, who witness that which cannot be shaken,
and the royal seed is atop of their head.

[.discourse-part]
_Principle._ He saith, '`The Quakers scorn to creep into houses,`' etc.
See page 19.

[.discourse-part]
_Answer._ Which doth not agree with the rest of his company, who say they do creep into houses.
The Quakers are in the power of God, and in the authority of the Lamb, above all houses,
and into houses creep not, but are upon the throne:
but you that are in the form and deny the power, creep into houses.
