[#ch-10.style-blurb, short="The Quakers`' Whitest Devil"]
== Ellis Bradshaw`'s book, called [.book-title]#The Quakers`' Whitest Devil.# His principles as follow.

[.heading-continuation-blurb]
He hath unveiled himself in what spirit he is,
and that he hath gone from the prophets, and Christ,
and the apostles, fighting against the rock.
But the stone is fallen upon his head, which will grind him to powder,
whose words shall be his burden.

[.discourse-part]
_Principle._ He saith,
'`We do utterly deny all their ways and doctrines
who exclude all teachings of men.`' See page 5.

[.discourse-part]
_Answer._ Contrary to the prophets,
who bid people to cease from men whose breath was in their nostrils;
therefore there is a teaching beyond it.
And who comes to that, shall come to hear the son.
And the apostles went to bring people to the end of the prophets,
and off from the priests,
and off the ordinances which the prophets had established in their place;
and the Lord is come to teach his people himself, where they need not say,
'`know the Lord,`' in the new covenant.

[.discourse-part]
_Principle._ He saith, '`The Quakers`' spirit doth teach them to honour no man,`' etc.
See page 6.

[.discourse-part]
_Answer._ That is a lie, for it teacheth them to have all men in esteem,
and to honour all men in the Lord.
Yet they are convinced by the law to be transgressors, if they respect men`'s persons;
and they are not to hold the faith of our Lord Jesus
Christ with respect of persons as you do.

[.discourse-part]
_Principle._ And whereas thou sayst,
'`The spirit of God doth not teach to judge before the time,`' etc.
See page 6. And others say, '`The saints shall not judge while they are upon the earth.`'

[.discourse-part]
_Answer._ But the spirit did teach the apostle to judge, and his time was come.
And he tells some, '`that they were of old ordained for condemnation,
and their damnation slumbered not,`' and they went on to
'`eternal judgment,`' and it is high time now to judge.

[.discourse-part]
_Principle._ And this he calls '`a mistake, to deny all those that say they have faith in Christ,
and yet their righteousness is not perfect as the righteousness of Christ is perfect.`'

[.discourse-part]
_Answer._ Who hath faith in Christ is in the perfect righteousness,
and so you are in the mistake, that have a faith and a righteousness that is not perfect;
for righteousness and faith which are the gift of God are perfect.

[.discourse-part]
_Principle._ To say, '`that he that saith he hath hope in himself,
and yet is not purified even as he is pure,
is the hope of the hypocrite,`' etc. this he calls '`a mistake.`' See page 8.

[.discourse-part]
_Answer._ And here he is corrected, and his spirit is corrected, as being in the world,
for the hope purifies as God is pure, but the hope of the hypocrite doth not.

[.discourse-part]
_Principle._ He calls it '`a subtle delusion that owns not the law without, in tables and books,
to try the spirits within,`' etc.
See page 8.

[.discourse-part]
_Answer._ The spirit of Christ within is the end of the tables, law, and works, and books.
Therefore in this is discovered his own '`white devil,`'
and he corrected by the spirit he speaks of.
The law is now in the heart, the new covenant is witnessed.
The Pharisees had the law in tables, as thou hast scriptures, and stood against the life,
and in the subtle delusion as thou dost, who brings the external to try the eternal,
whereas it is the eternal that trieth the external, as Christ did the Pharisees,
who told them when they wronged it.
And so are you the wrongers of it, who have not the eternal to try with,
so are as the devil, fallen out of the power.
And it was the eternal that led the saints to speak forth scripture,
and with that they are tried and seen who wrong them,
and wrest them to their own destruction.
And Peter was one of those triers, who was in the spirit of God,
and could not read letters; and the Pharisees had the letter without the life,
and could not try.
