[#ch-11.style-blurb, short="Choice Collections of Scriptures"]
== Francis Blake`'s book called, [.book-title]#Choice Collections of Scriptures, Against the Practice of the Quakers,# etc. His principles follow.

[.discourse-part]
P+++.+++ He saith,
'`Repent and become sinners,`' because the Quakers say they
are made free from sin by Christ.`' See page 6.

[.discourse-part]
A+++.+++ Contrary to the apostle`'s doctrine, who said, '`repent, and forsake sin,
that they might receive the remission of sins,`' etc.
And contrary to the apostle`'s doctrine to Simon Magus.

[.discourse-part]
P+++.+++ Francis Blake hath printed a letter, which shows,
'`that those that are in scorn called Quakers own
the blood of Christ.`' And John Bunyan saith,
'`they deny it.`'

[.discourse-part]
A+++.+++ And thus they are in confusion.
But the blood of Jesus Christ the son of God we own, but their lies we disown;
and we witness the repentance which cannot be repented of; but we say to you,
'`repent and turn from your sins.`' And they that bid people repent and become sinners,
are Satan`'s messengers.
