[#ch-12.style-blurb, short="The Second Beacon Fired"]
== Luke Fawnes, Samuel Gellibrand, Joshua Kirton, John Bothwell, Thomas Underhill, and Nathaniel Webbs, in a book called, [.book-title]#The Second Beacon Fired.#

[.heading-continuation-blurb]
Sent to the protector.
Their thirst is after blood and persecution: over all such spirits we see;
there is that in them shall answer it.

[.discourse-part]
P+++.+++ They say, '`The Quakers principles are blasphemous, Paganish, antichristian,
antiscriptural.`'

[.discourse-part]
A+++.+++ Because we hold forth the foundation of God, Christ Jesus,
who doth enlighten every man that cometh into the world.

[.discourse-part]
P+++.+++ He calls this '`loathsome, poisonous, and blasphemous error,`' etc.
See page 3.

[.discourse-part]
A+++.+++ You are poisoning the people, and are of the whore`'s stock,
who would have blood to drink, which drank of the blood of prophets, and martyrs,
and saints, and so by lies provoke the zeal of the magistrate against them,
as the Pharisees and priests did in past ages.
But that was the blind zeal that persecuted, in all ages; and they are antiscriptural,
antichristian,
and antiministerial that deny the '`light that lighteth every man that
cometh into the world,`' which is the end and substance of the scriptures;
and who are in that, own the scriptures, and are not against them,
and are the true ministers and christians;
and so you are the Pagans and heathens that deny
the light that all men are enlightened with.

[.discourse-part]
P+++.+++ They say that '`the Quakers are in an error, to say,
that none are the ministers of God, and called of him,
who are sent forth by the authority of man,`' etc. page 7.

[.discourse-part]
A+++.+++ So show their ignorance of the apostle`'s doctrine and words;
'`Not of man nor by man`' he saith he had received it,
'`but by the revelation of Jesus Christ;`' and so you who are made by men deny this.

[.discourse-part]
P+++.+++ They say, '`That is another error of the Quakers, to say,
he who is not infallible in his judgment, when he gives counsel and advice,
is no minister of Christ.`' See page 7.

[.discourse-part]
A+++.+++ Now he that is not infallible in his counsel, and judgment, and advice,
is not he in error?
And are not the ministers of Christ the ministers of the spirit?
And is not that out of the error, and infallible in counsel and judgment?
And are they ministers of Christ that are fallible?
and is not the power, the gospel, infallible?
You may well creep and go to the magistrates for help, who deny infallibility,
and so as natural men know not the things of God with the earthly spirit of the world.
I say, that is infallible which must order all the creation to the glory of God,
by which they were made and created.

[.discourse-part]
P+++.+++ You say again,
'`you are laying and spreading their errors and blasphemies before the magistrates,
that they may stop their mouths.`' See page 9.

[.discourse-part]
A+++.+++ Now you show that you have not the spirit of Stephen nor of the apostles,
(whom their enemies could not resist,) but the spirit of them that are against Stephen,
etc. persuading the magistrate; and so your weapons you show are carnal,
not the mighty weapons to pluck down the strong holds and spiritual wickednesses,
which weapons are spiritual.
Ye are fain to fly to the mountains to cover you,
to hide you from the presence of the lamb which is now risen.
And where did ever the apostles go to the magistrates for help,
and complain against errors and blasphemy?
And such as did so, judged truth to be blasphemy,
running to the magistrates as you do now, who are apostatized from the apostles.
But many of the magistrates are come to see you,
and will not be your pack-horses nor executioners any longer.
And your whole intent is to brand the light of Christ Jesus,
with the same expressions of '`error and blasphemy`' as the Jews did in ages past,
who are running to the magistrates with petitions,
provoking and stirring up the blind zeal where it is,
against Christ where he is in his saints, such as keep his testimony;
whose thirst is after blood and persecution,
who would stop the press that truth should not be published to the nation:
thus showing ye have not the spirit that is able to gainsay
or contradict the spirit that is in the Quakers.
Therefore do you beg, with your petitions and feigned humility,
for the powers of the earth to stop them.
But where the spirit of wisdom, and of God, and of a sound mind is ruling,
the intents of your minds are seen, such as were in all ages, that brought upon heaps,
and stirred up tumults, and made insurrections among people,
casting mists before magistrates`' eyes,
whereby they might be blinded and turned against the just.
For which cause God`'s judgments have been brought upon such as you,
and magistrates also, and he hath rebuked kings for his anointed`'s sake.`'
