[#ch-13.style-blurb, short="The Foot Out of the Snare"]
== John Toldervey`'s book called, '`The Foot Out of the Snare.`'

[.heading-continuation-blurb]
His principles: and these whose names were subscribed to the book, viz. Thomas Brooks,
Thomas Jacomb, George Cockayn, William Adderley, John Goodwin,
John Tombes, William Jenkins, and Matthew Poole, priests.

Whose intent, and that of the priests, is,
to father the work of the imagination that was in John Toldervey,
upon the spirit of the living God and of Christ, that is in the Quakers.
But all their work and imaginations are with the light and the spirit of truth judged,
and him and his priests, and all of them, their feet are fast in the snare.
And all that is in this book which is contrary to the truth, and the scriptures,
is judged; but all that is truth, is owned.
And here are some of their principles as followeth.
John Toldervey, and the rest, in the book entitled '`The Foot Out of the Snare`',
would lay all his actions upon the light, but they split themselves against the rock;
and he himself hath split himself upon the rock, which made him recant,
and deny all his foolish actions, and so these great high priests come off with shame.

[.discourse-part]
P+++.+++ He saith,
'`The declaring against all sin is nothing of the
mystery of the gospel of Christ.`' See page 3.

[.discourse-part]
A+++.+++ Ignorant are you; for that which makes manifest sin,
is the light of the glorious gospel of Christ the mystery.
All his will-worships, and his will-actings, his self-righteousness, and obediences,
and motions, and fancies which he followed,
the priests would lay upon the covenant in the heart, and Christ within,
and do not clear the covenant and Christ within from all
those actions which were destructive to the creature;
which Christ, the covenant, preserves, and the creation,
and brings the creature into the liberty of the sons of God:
and here your madness and blindness appear without distinction.

[.discourse-part]
P+++.+++ He saith, '`Not to call any one master, nor to pull off the hat to any one;
not to you any one, but to use the word thee and thou to a single person;
not to use any compliments or greetings to any; not to bow to any man,
to honour the creature; not drinking to any;
and to pull off the points and ribands from his knees, band-strings, and hatband,
and buttons that were unnecessary on his coat, and other things,
and burned divers books,`' etc. the putting off all these things which were unnecessary,
they call '`seduced persuasions,`' etc.
See page 15.

[.discourse-part]
A+++.+++ Now all these that have borne record with thee, under the life are ye come,
and judged, which abides and remains, and forever with it are judged: for,
as for not calling men master, that is the command of Christ.
As for the not fashioning yourselves according to
the world in your former lusts of ignorance,
that is the command of the apostle.
And as for the forsaking of gorgeous apparel, naughtiness, and superfluity,
they are corrected by the scriptures, and judged by the spirit.
And as for '`drinking to one another,`' and tempting one another with beer,
and bowing the hat, and respecting and honouring the creature,
these are earthly Adam`'s honour in the fall, which Christ receiveth not,
the second Adam.
And as for respecting of persons, they that do so, '`commit sin,
and are convinced of the law as transgressors.`' And now see where thou wast,
and all the priests, in your seduced persuasions, and judged good evil, and evil good.
And thou and the priests may see that all this that thou didst from thy own persuasions,
is thy own will.
But that which led thee from sin, and from the world, to righteousness, was owned;
that shall be recorded forever against thee and all the priests,
and stand a witness against you, though now thou art in the flower of thy age.
And it will be hard for thee, John, and the priests,
to get in that which ye have spread abroad;
and the weight of the burden of all thy words, and your words,
ye are not yet come to feel: but when the fire and the heat enter into your flesh,
that ye are scorched with the vehement heat, then remember,
every word that ye have given forth, will come upon you as a burden.
From a lover of your souls, and a cherisher of truth.

And, John, for all the actions which were done in thy will,
and set forth in the same to the view of the world by the priests,
which abused the power, and that which was rising in thee of God,
to the sight of the world, crucifying afresh the son of God,
and so put him to open shame, thou wilt suffer, and the priests;
and that which was done in thy presumption, which abused the power of the Lord God,
that was never accepted of the Lord God, nor owned by the men of God.
But there are a thousand, I do believe, in the nation,
that can see and do see what thou and the priests have recorded to the world,
and are able to judge, when the power moved thee, and when there were imaginations;
and they see that the priests took thy part,
and are one with that nature in thee which betrayed the just, even Judas-like.
And mind and take notice those that Judas betrayed Christ to,
as thou betrayed the just also; see what friends they were to Judas,
after Judas had done, and what friends they will be to thee after thou hast done!
Now come to the just principle in thee, John; thy flight was in the winter.

And as for the word '`thee`' and '`thou`' spoken to a particular,
they show they have forgotten the Latin books, that which they call their learning;
for is it right to call one many, or many one?
Is that a sound speech which cannot be condemned?

And all the people upon the earth that have run out in their imaginations,
whereby truth comes to be hurt, if they have done it willingly,
the greater shall be their punishment; they shall be whipped, however.
But all you that have bent your wills, and given your strength to the adversary of God,
whereby the way of truth cometh to be reproached, you are such as turn,
his grace into wantonness, as cause the way of truth to be evil spoken of,
and such shall have a reward according to their works, thou and you all.

[.discourse-part]
P+++.+++ They say, '`The fashions of the world, and the compliments,
it is not sin to use them,`' etc.
See page 45.

[.discourse-part]
A+++.+++ Which is contrary to the scriptures,
since to use even the ceremonies commanded of God, after the substance was come, was sin,
much more the fashions and customs of the world.
Yea, but say they, this brings in our living, and by the other we lose our livelihood;
so ye may see what mind is up in choosing.
And all the zeal is in the will which runs out before the light, the guide;
and that is that which the priests catch at to make their defence with,
against the truth.
But the Lord will reward them according to their works,
who hath showed mercy to Toldervey, and made him confess, in another book,
that which formerly the priests and he had set forth, and vilified the truth with,
and so it is published to the nation, as the answer to this book called,
'`The Foot Out of the Snare`'.

Such as deny the fashions of the world, which the priests are in, points and ribands,
double cuffs, and boot-hose-tops, and the honour of men, which God will stain,
and are called of men master; such things as these eight great priests justify,
and ensnare people under them; and if any forsake them,
they will say they are snared and deluded.
And it is manifest who is their master, and who they serve,
since the keeping Christ`'s command is a snare to them.
And because we cannot call them master, and keep Christ`'s commands, therefore they rage,
who transgress his command, and then say they are his ministers.
But your fruits and works are seen, praised be the Lord;
your eight priests have discovered yourselves,
who are the false spirits gone out into the world from the apostles,
and out of Christ`'s command. Matt. 23.
Where do you read Mr. Paul, Mr. Peter? etc.
And where do you read that Paul and the messengers
of Christ were hung about with points and double cuffs,
and boot-hose-tops, and ribands, and made such a stir about doffing of hats,
and thee and thou, as the novice teachers do now,
that are found in the lusts and fashions of the world,
which the apostle declares against,
and instructed them to use sound words which could not be condemned,
and to obey the doctrine of Christ, not to be called of men master?
But you are the transgressors that abide not in Christ`'s doctrine,
but are the antichrists (2 John) which the apostle speaks of,
that have reigned from their days, but are now discovered by the spirit;
praised be the Lord God.
And they know in their Latin original,
it is not proper to say '`you`' to a single person,
and they know that to be '`called of men master,`' is against the command of Christ,
and in the transgression, and so usurping that authority which Christ forbids.
