[#ch-14.style-blurb, short="The Looking Glass for Quakers"]
== Thomas Collier`'s book called, '`The Looking Glass For Quakers.`' His principles follow.

[.heading-continuation-blurb]
And as for all his lies, they will be heaped upon his own head, and to his own sorrow.

[.discourse-part]
P+++.+++ He calls James Nayler a liar, because he said, '`That by which the just lives,
is that by which the creature is justified.`' See page 2. And he saith,
'`it is another righteousness,`' because we witness
the righteousness of faith which is in the heart,
which God is the author of, etc. page 3.

[.discourse-part]
A+++.+++ Now that which we say God and Christ is not the author of,
(but gathered from the letter,) is a dead faith and righteousness;
and there is your justification, that stands in the unbelieving state and is condemned;
only speaking of the letter as the Jews did, of a Christ that is come,
as they did of a Christ that was to come; and have not heard his voice,
nor received faith from him, who is the author of it,
through which men are justified and come to have peace with God;
and this faith is in their hearts.

[.discourse-part]
P+++.+++ He calls it '`a hearkening to the voice of Satan,
to hearken to the voice within,`' and saith, '`They cry, the light within,
the voice of Christ, the true word,
which (he saith) is but their own lying fancies at the best,`' etc.
See page 4.

[.discourse-part]
A+++.+++ Now to call the light within, the word within, Christ within,
the word of faith within, which is to be obeyed and done,
'`lying fancies at the best;`' here thou may see, Collier,
that thou divides the word not aright, and art ignorant of the scriptures.
And Christ saith, '`the spirit of the Father speaks in you.`' Is not this all scripture?
And if they hearken to this, do they not hearken to scripture?
and is not the scripture fulfilled in this?
And is thy voice all without thee, only in the letter?
And thou judgest all delusion that hath any speaking within them,
and so hast judged thyself, from the holy men of God, to be one of the dumb prophets,
and so, contrary to the true prophets and apostles.

[.discourse-part]
P+++.+++ He saith, '`If the very Christ of God be within those that are called Quakers,
he cannot come down from heaven,`'. etc.
See same page.

[.discourse-part]
A+++.+++ Here he stands against the promise of Christ,
that he shall come and dwell in you and walk in you.
'`I will come again unto you.`' And he hath '`revealed his son in me,`' saith the apostle.
And thus thou, Thomas Collier, and John Bunyan, are ignorant of plain scripture;
the scripture declares it, and the apostle said,
'`Know ye not that Christ is in you except ye be reprobates,`' and '`the spirit
of the Father speaks in you.`' See how contrary thou art to the prophets,
Christ, and the apostles!

[.discourse-part]
P+++.+++ He saith,
'`The heavenly bodies spoken of in Cor. 15. are the sun, moon, and stars,`' etc.
See page 6.

[.discourse-part]
A+++.+++ Let all people read the scripture and see if it hold forth that.

[.discourse-part]
P+++.+++ Again he saith, '`They abuse the scriptures,
because they say he that is born of God doth not commit sin,`' etc.
See page 6.

[.discourse-part]
A+++.+++ The scripture is witnessed, as it relates and speaks.
And he abuseth it, when he gives private interpretations to it,
and owns it not as it speaks.

[.discourse-part]
P+++.+++ Again he saith, '`He that saith he hath no sin deceived himself,`' etc.
See page 6.

[.discourse-part]
A+++.+++ But the scripture saith, '`If we say we have no sin,`' etc.
So he perverts the scripture,
for it is not '`he;`' if he say '`he,`' he may put it upon Christ, who is without sin:
and upon this principle, he may charge the elect, to whom God lays no sin,
and sees '`no iniquity in Jacob,
nor transgression in Israel.`' And it is Collier`'s
wicked eye that sees sin in the elect,
they that are born of God.
Thus he abuseth the scriptures, and is not able to divide the word aright;
and therefore such spirits are to be kept out of scriptures,
with the spirit that gave forth scripture:
'`for he that is born of God doth not commit sin.`'
And there is a time for men to see they have sin,
and have sinned, and a time to confess it and forsake it;
and there is a time to witness the blood of Christ cleansing from all sin,
and then a time to witness the birth born of God which doth not commit sin.
1 John 4. chap.

[.discourse-part]
P+++.+++ He saith,
'`Here is a strange conceit of a person that fills heaven and earth with his presence,
and dwells in the saints, blindness with a witness,`' etc.
See page 8.

[.discourse-part]
A+++.+++ Here thy ignorance hath appeared again:
for all power in heaven and earth is given to him, Christ Jesus, who is in them,
at the right hand of God, who is dwelling in the saints,
and doth enlighten every man that cometh into the world;
but this to thee is a strange conceit, and blindness with a witness.
Thy witness is blinded with thy conceit, which shows thy ignorance of scripture,
and thy unskillfulness in the word and doctrine; since all things are upheld by his word,
and his power: and there is no creature but is manifest in his sight:
for all things that were made, were made by him,
that he might have a name above every name; and that to his name should every knee bow,
and every tongue confess to the glory of God.
And God will dwell in man, and it is he that seeth the heart.

[.discourse-part]
P+++.+++ He saith, '`sin is in the saints,`' etc.
See page 10.

[.discourse-part]
A+++.+++ Sin is not in the sanctified, but in the unsanctified.
And he that saith sin is in the saints, is blinded, he is of the serpent,
and he and they are in the pollution themselves, which the saints have escaped,
and are washed and cleansed; and so far as any one is sanctified, it is from sin.

[.discourse-part]
P+++.+++ He saith, that '`We will not enter into the kingdom by the blood of the covenant,
that hath been often proved,`' etc.
See page 10.

[.discourse-part]
A+++.+++ And Francis Blake published it in print,
that the Quakers witnessed the blood of Christ that cleanseth from all sin;
and so thou prints against us, and he prints for us;
thou prints that we deny the blood of Jesus,
and he prints that we own the blood of Jesus;
and so ye are devouring the innocent betwixt you.
The blood of the seed we own, which cleanseth from all sin, which you do not own,
who say sin must be in the saints, but make his blood, which cleanseth from all sin,
of none effect.

[.discourse-part]
P+++.+++ He saith, '`The scriptures shall be our judge one day, which we call the letter,`' etc.
See page 11.

[.discourse-part]
A+++.+++ And the scripture saith,
'`All judgment is committed to the son,`' and '`God will judge
the world,`' and the saints and the spiritual man judge all things;
and thus thou art ignorant of the letter, and this shall judge thee at the last.

[.discourse-part]
P+++.+++ He saith, '`That the kingdom is not come,
nor refreshing from the presence of the Lord,`' etc.

[.discourse-part]
A+++.+++ Which shows they are like the Pharisees, unconverted, gazing here and there;
but Christ told them the kingdom was in them.
And they are not turned to the light which comes from Christ the refresher,
whereby refreshing might come; so are not yet come to repentance.

[.discourse-part]
P+++.+++ He saith, '`They that say they have no sin, make God a liar.`' See page 12.

[.discourse-part]
A+++.+++ The scripture saith no such thing, but saith on the contrary,
many were made free from sin.
'`And if Christ be in you the body is dead because of sin;`' and they
that are Christ`'s have crucified the lusts,`' and all things are become
new:`' and they that sin and lie are not in Christ the truth.

[.discourse-part]
P+++.+++ He saith, '`All that have been, are,
or shall be converted since the gospel ministration,
are converted by the apostles`' words,`' etc.
See page 13.

[.discourse-part]
A+++.+++ So he hath thrown out the spirit that doth regenerate,
and Christ the way to the Father, the word that sanctifieth,
and Christ '`the power of God to salvation;`' who said they
would not come to him that they might be converted;
so if they get all the apostles`' words and come not to Christ, they are not converted;
and none are converted by the apostles`' words,
but they who come to the life that the words came from.

[.discourse-part]
P+++.+++ And he opposeth and saith, '`It will be the Quakers`' fall,
because they say there is no other way to bring people to God,
but by '`the light in them,`' etc.
See page 14.

[.discourse-part]
A+++.+++ Which is Christ, the way to God from whom it comes,
not believing in which is man`'s condemnation, and so a saving light.
For saith God, '`I will give him for a covenant, for a light to the Gentiles,
that he may be my salvation to the ends of the earth;`' to wit, the light shall:
and all that are not in the light are in the fall, out of the covenant,
in the unsaved state, and know not their salvation, as the scripture declareth;
so there is death and destruction, talking of the fame of wisdom,
and keeping people out of the light.

[.discourse-part]
P+++.+++ And he saith, '`That Christ is not so the light of the world,
as he is the light of believers.`' See page 14.

[.discourse-part]
A+++.+++ Christ is the light to the world, as to believers,
and he that believeth in it shall not abide in darkness,
but shall have the light of life.
He that follows the light and believes in it, shall have the light of life,
and shall not abide in darkness.
He that follows not the light, but hates it,
he abides in the darkness and the light condemns him, which the believer walks in,
and believes in, and hath the light of life; which light is one and the same,
which enlightens every man that comes into the world, believers and unbelievers.

[.discourse-part]
P+++.+++ He saith, '`That the scriptures are the rule of the saints`'; and he saith,
'`the spirit is the guide to that rule,`' etc.
See page 15.

[.discourse-part]
A+++.+++ And so would have the scripture to go before the spirit.
Now the spirit was the saints`' rule, that led them to speak forth scriptures,
and to let them see to what condition they were spoken,
and so by that they came to the law of faith; and they were not ministers of the letter,
but of the spirit.
So in this ye have proved yourselves not to be ministers of the spirit,
but of the letter, but the spirit was before the letter was.

[.discourse-part]
P+++.+++ He saith, '`That the time of perfection will be when Christ comes from heaven,
and not before; till then the saints must be warring, waiting, groaning,
and mourning,`' etc.
See page 20.

[.discourse-part]
A+++.+++ And David said,
he had '`seen an end of all perfection,`' (contrary to Collier,) and the apostle said,
'`they should hunger no more, nor thirst any more.`' And Christ saith,
'`he that eateth his flesh, and drinketh his blood, shall hunger no more,
and thirst no more.`' He that believeth is entered into his rest,
and shall hunger no more, and thirst no more.
And the apostles and saints witnessed Christ in them, and the kingdom,
while they were upon earth, and the end of groaning and growling which thou art in,
that art out of this, and keeps people who are apostatized from the apostle,
from the light which is the truth.
