[#ch-15.style-blurb, short="A Public Discovery of a Secret Deceit"]
== John Deacon`'s book, called, [.book-title]#A Public Discovery of a Secret Deceit.# His principles follow.

[.heading-continuation-blurb]
And as for the rest of his lies and slanders in his book;
with which it is filled, they will fall upon his own head, and be his sorrow.
And all liars upon the earth, that are given up to believe and tell lies,
are comprehended with the innocency and truth, by which innocency is preserved,
and men shall heap to themselves sorrow by their own lies and inventions.

[.heading-continuation-blurb]
Nevertheless the scriptures of truth are owned in their place,
to the condition that they were spoken to.

[.discourse-part]
P+++.+++ He saith,
'`that the light wherewith every one that cometh into the world is enlightened,
is the light of nature, and reason, and sense,`' etc.
See page 5.

[.discourse-part]
A+++.+++ Which is contrary to John (1:9.) who saith,
'`it was the true light by which all things were made;`' which as, many as received,
he gave them '`power to become the sons of God,`'
which is beyond natural sense and reason.

[.discourse-part]
P+++.+++ He saith, '`that the work of faith, and the growth of faith,
is by the natural use of ordinances,
and calls it deceitful sophistry which denies it,`' etc. page 7.

[.discourse-part]
A+++.+++ Faith is the gift of God, and Christ is the author of it.
It cometh not by the natural use of ordinances:
'`the natural man receiveth not the things that be
of God,`' but faith is the gift of God.
And thou art in the sophistry, and in the poison, that sayst,
the work and growth of faith, are by the natural use of ordinances.

[.discourse-part]
P+++.+++ And he speaks of '`a temporal expressive word of God,`' etc.
See page 8.

[.discourse-part]
A+++.+++ But the scripture tells us of no such thing as a temporal word,
but speaks of the word of God that '`lives and endures
forever;`' and so the other is but his own imagination.

[.discourse-part]
P+++.+++ He saith, '`The Quakers go about to pick forth the right eye of christianity.`'

[.discourse-part]
A+++.+++ Because they hold forth the light that lighteth every man that cometh into the world,
Christ Jesus the covenant of God, which makes all the apostate christians blind.
And your right eye must be plucked out that offends;
and this the christians shall witness when their eyes are open to see the light,
which enlighteneth every man that cometh into the world,`' the covenant of God.

[.discourse-part]
P+++.+++ He saith, '`The Quakers were never heard of till of late years,`' etc.
See page 12.

[.discourse-part]
A+++.+++ Which is contrary to the scriptures, in which they are spoken of before Moses,
by Moses, by the prophets and by the apostles;
and the apostle bids them to '`work out their salvation with fear
and trembling.`' And now the great earthquake John speaks of,
is coming amongst you false prophets, antichrists, harlots,
and apostates from the apostles, compellers to your worship.
And now are you comprehended, and with the spirit of God are you judged,
who are ignorant of the salvation wrought out with fear and trembling.

[.discourse-part]
P+++.+++ He calls them '`subtle deceivers and heretics,
that question the word trinity,`' and says '`it came from Rome,`' etc.
See page 13.

[.discourse-part]
A+++.+++ Which he is justifying, and so he is turning to his teacher the pope,
(and the common-prayer-book,) of whom he hath learned it;
for the scriptures have not taught it him.
And the son and the Father are in unity, and this we own that are called Quakers,
and deny you and your pope, and your common-prayer-book, and your false teachers,
got up since the days of the apostles.

[.discourse-part]
P+++.+++ Again he saith, '`O incomparable hypocritical liars!
Is not this the character Paul gives of a false prophet,
to speak lies in hypocrisy?`' because we preach perfection, etc.
See page 16.

[.discourse-part]
A+++.+++ It is agreeable to scripture, Christ`'s doctrine, and the apostles`' doctrine,
and the life of Christ.
'`We are made free from sin,`' saith the apostle.
And again, '`As he is, so are we in this present world.`' And,
'`As many as are perfect are thus minded,`' etc.
But this thou calls hypocrisy and lies;
and thus thou art out of the apostles`' and Christ`'s doctrine and life,
and like a madman ragest against them that are in it, and hast denied thy own work,
the work of the ministry,
which was '`for the perfecting,`' and so art a physician of no value.

[.discourse-part]
P+++.+++ He saith, '`The enjoyment of immortality is not till they have put off the body,`' etc.
See page 17.

[.discourse-part]
A+++.+++ Contrary to the apostle`'s doctrine, who saith,
'`immortality was brought to light through the gospel.`'
This was when they were upon earth,
and the word of God was in them, and Christ was in them, which was immortal.

[.discourse-part]
P+++.+++ Again he saith,
'`They shall not have power over death and the grave until the natural death,`' etc.
See page 17.

[.discourse-part]
A+++.+++ Contrary to the apostle, who saith, '`O death! where is thy sting?
O grave! where is thy victory?`' And they were '`passed from death to life;`' and '`he
that believes shall never die,`' and such have power over death and the grave.
They that believe shall never die, they have passed from death to life.

[.discourse-part]
P+++.+++ He calls them '`secret deceivers, to grant perfect purity and perfection,`' etc.
See page 18.

[.discourse-part]
A+++.+++ Which is contrary to the apostle`'s doctrine, who brought people to perfection,
and purity, and holiness,
'`without which none shall see the Lord.`' And they were to stir up their pure minds.

[.discourse-part]
P+++.+++ He saith,
'`To witness perfect purity is an alluding to an
enjoyment of heaven upon earth,`' and saith,
'`This is as the world,`' etc.
See page 19.

[.discourse-part]
A+++.+++ Which is contrary to the scriptures,
which witness the kingdom of heaven to be in the saints,
and their conversation in heaven; and thou that bringest to the contrary art a deceiver.

[.discourse-part]
P+++.+++ He saith, '`He dare boldly assert,
that the gospel is not first made known by the seeing within,
but by hearing tidings without,`' etc.

[.discourse-part]
A+++.+++ Contrary to that which they call their original, which saith,
'`the gospel is preached in every creature.`' And none come to hear and see the gospel,
but with the eye within, that which is oppressed.
For the Jews that heard not, and saw not within, stood against the gospel:
and Christ said, '`their ears were stopped,
and their eyes were closed;`' and so they heard words, but the gospel, the power of God,
they could not hear, but stood against Christ;
and so none hear but they that hear within; and he only is a preacher of the gospel,
which is the power of God, that preacheth to the inward eye.

[.discourse-part]
P+++.+++ He confesseth,
'`that none of the saints had ever a particular command;`'
and then again he confesseth they had,
and so he is in confusion, page 26. He saith,
'`It is a lie to preach the kingdom of heaven within unbelievers.`'

[.discourse-part]
A+++.+++ Contrary to Christ`'s words, who told the Pharisees,
'`the kingdom of God was within them.`' Luke 17. So in confusion, in Babylon;
the smoke of the bottomless pit hath blinded his eye,
who is got up since the days of the apostles.
The foundation hath been lost among these inwardly raveners, which is the light,
Christ Jesus, which enlighteneth every man that cometh into the world, the rock of ages.

[.discourse-part]
P+++.+++ He saith again,
'`It is a lie to say that any come to the knowledge of the light
of God by the light that shines in their hearts,`' etc.
See page 28.

[.discourse-part]
A+++.+++ Contrary to the apostle, 2 Cor. 4. who said,
'`the light that shined in their hearts should give them the light of the knowledge
of the glory of God in the face of Christ Jesus;`' and so he is a messenger of Satan,
the devil`'s minister, one that draws from the light that must give people the knowledge;
the witness in thy conscience shall answer.

[.discourse-part]
P+++.+++ And again he saith, '`It is a notorious lie,
to say that Christ preached the kingdom of heaven in unbelievers.`'

[.discourse-part]
A+++.+++ Contrary to Christ, and contrary to Luke 17. who said,
the kingdom of heaven was in the Pharisees,
and so thou art an unlikely man to be a minister of Christ,
who art of the letter ignorant, that knows not the kingdom in thyself,
that knows it not in the unbelieving Pharisees.

[.discourse-part]
P+++.+++ He saith, '`The greatest of the apostles were never exempted from the remnants of sin,
and the saints`' pilgrimage is a continual warfare to heaven,
while they be on this side the grave,`' etc.

[.discourse-part]
A+++.+++ Which is contrary to the apostle, who said,
they were '`made free from sin;`' and said,
'`how could they live any longer therein?`' And said, '`their conversation was in heaven,
and they sat in heavenly places,`' and they witnessed the kingdom wherein was
'`joy in the holy ghost.`' So this was the end of their pilgrimage then;
and thus he shows he is ignorant of the scriptures, and of the apostles`' doctrine.
And it is not a strange thing that the teachers of the world
should cry up imperfection and the body of sin,
who are ravened inwardly from the spirit of God by which it is put it off;
and gone forth from the apostles`' and Christ`'s doctrine.
But those who are come to the spirit of God, which they are ravened from,
put off the body of imperfection and sin.
And so you have corrupted the earth with your windy doctrine;
for what good hath their doctrine done,
that teach people they must be in imperfection and in sin while they are upon earth?
they can but be so if they never come to teach them.
And they are apostatized from the ministers of Christ,
whose work was to the perfecting of the saints,
'`until they came to the perfect man,`' the possibility
of which these apostates`' work is to deny.

[.discourse-part]
P+++.+++ He is judging the apostle, and saying,
'`The prick in the flesh which the apostle received,
was neither through the want or disability of faith,`' etc.
See page 34.

[.discourse-part]
A+++.+++ Why then did the apostle cry out?
answer me that.
And the Lord said, '`His grace should be sufficient for him;
and his strength should be made perfect in his weakness,`' and is not weakness disability?

[.discourse-part]
P+++.+++ He saith, '`That no man by that native light inherent in him,
had power to believe,`' etc.
See page 26.

[.discourse-part]
A+++.+++ The light which doth enlighten every man that cometh into the world,
he calls '`native,`' and '`inherent.`' He gives these names to it,
which is the light which doth enlighten every man,
etc. there is power given in the light to believe.
But he that hateth the light, hateth the power, and so the light is his condemnation.
The names he gives, as '`native`' and '`inherent,`' are his own, out of the truth.

[.discourse-part]
P+++.+++ He saith, '`The scripture doth not set forth a certain allowance for ministers,
but it is left to human prudence,`' etc.
See page 12.

[.discourse-part]
A+++.+++ So he is flown from Christ`'s words and the apostles`',
who with the wisdom of God set down the ministers`' allowance,
and did not leave it to human policy in after ages for maintenance for ministers:
for human policy will feed the false prophets, such as the prophets, and Christ,
and the apostles declare of in scripture,
whose spirits are seen with the spirit that gave forth scripture,
gone out into the earth, who were covetous, and so idolaters,
ordering with the policy which is human and earthly.

[.discourse-part]
P+++.+++ He saith, '`Abraham`'s obedience was not an act of the body,`' etc.

[.discourse-part]
A+++.+++ Which any may read the scripture and see,
and judge thee whose body is out of the action of God, serving him who is not of God.

[.discourse-part]
P+++.+++ He saith, '`God doth not work immediately now,`' etc.
See page 43.

[.discourse-part]
A+++.+++ So all the works of God are mediate now by his principle; then by his conclusion,
none have the spirit of Christ which is immediate, and works immediately.
So then none hear God`'s voice, and none are sent from God,
and Christ is with none of them!
For they who are sent from God hear his voice; and they who have Christ in them,
have that which is immediate.

[.discourse-part]
P+++.+++ He saith,
'`He utterly declares (as others have done) against not praying or preaching,
etc. unless the spirit move,`' etc.
See page 44.

[.discourse-part]
A+++.+++ So here then, thou prayest and the spirit moves not, and preachest,
and the spirit moves not: so the spirit of error is it that moves thee.
And thou art contrary to all them that gave forth the scriptures,
the prophets and ministers of God,
who '`spoke as they were moved by the holy ghost.`'
And thou art never likely to read the scripture,
but by the same that gave them forth, nor know them, nor is any one upon the earth;
nor to know God of whom they learned that gave them forth, and were taught of him;
and so thou art no minister of the spirit.

[.discourse-part]
P+++.+++ He saith, '`Not to preach, nor to pray but as the spirit moves;
in a sort is to shut up the kingdom of God from the sons of men;
and brings men to neglect their duty,
and is the gap where the delusion of Satan comes in, and draws men to sluggishness.
And how can glad tidings be known, unless they be told,`' etc.

[.discourse-part]
A+++.+++ Now they are all in the sluggishness, shutting up the kingdom of heaven against men,
under the delusion of Satan, and none can bring the glad tidings,
but as the spirit moves them.
And they who go when the spirit doth not move them,
are they that run and the Lord never sent them;
and they who pray or speak without the moving of the spirit,
are out of the path of all the holy men of God.

[.discourse-part]
P+++.+++ He saith, '`It is the privilege of the Bereans to try an apostle,`' etc.
Again he saith,
'`They are to put up their supplications when the spirit doth not move them,`' etc.
See page 45.

[.discourse-part]
A+++.+++ Now see if God ever accepted that which was not moved from the spirit:
God who is a spirit never accepted that; and that which tries apostles is the light,
and it gives the Bereans to believe the scriptures which the apostle speaks of.

[.discourse-part]
P+++.+++ And he saith,
'`Far be it from me to imagine that the spirit of
God moved the apostles to preach when they did only,
and not at other times, and that they always waited in silence till then,`' etc.
See same page.

[.discourse-part]
A+++.+++ So he would make out that the apostles preached when the spirit moved them not,
and run without the moving of the spirit, and so would make them like himself.
Peter said,
'`they spake as they were moved by the holy ghost.`' And
they that are the sons of God are led by the spirit of God.
And '`the spirit shall lead them into all truth.`' And the
spirit should '`tell them what they should speak,
and show them things to come;`' and that was their guide and rule.
And thou who speakest, and not as the spirit moves thee, art no minister of the spirit;
and sayst,
'`far be it from thee to imagine the apostles preached
only when they were moved,`' and so with thy imaginations,
dost not own the apostles were the ministers of the spirit.

[.discourse-part]
P+++.+++ And the singing of the saints in the spirit and grace,
is not like the ungodly singing without the spirit.

[.discourse-part]
A+++.+++ And saying,
'`the grace of God hath not appeared unto all men,`' and '`that
all have not the spirit;`' which is contrary to scripture.
It saith,
'`the grace hath appeared unto all men;`' and '`I will pour out my spirit upon
all flesh.`' And the spirit that reproves the world is the saints`' leader;
and you that sing David`'s quakings and prayers, are not in the understanding nor grace,
but distinct from the saints; whose singing must be turned into howling.
How then can ye give them the psalms to sing that have no grace?

[.discourse-part]
P+++.+++ And the priests of Scotland say, '`Cursed is he that says,
grace is free.`' These are the Scottish principles, etc.

[.discourse-part]
A+++.+++ Ye give the psalms to all to sing, and yet say all have not grace,
and all have not the spirit of God, and then can they sing in the grace,
and sing in the spirit?
Is there any prudent reason or good understanding without the spirit?

[.discourse-part]
P+++.+++ He saith, '`we deny the scripture to be the word of God.`'

[.discourse-part]
A+++.+++ The scriptures are the words of God, and Christ is the word, in which the words end.

[.discourse-part]
P+++.+++ And he speaks these detestable words, and says,
'`Is not our tongues oiled with a spirit of confused delusion,`' which is his own, etc.
See page 5.

[.discourse-part]
A+++.+++ Because we say, such as pray or preach, it must be by the moving of the spirit of God;
which they are not in, that are in the spirit of delusion.

[.discourse-part]
P+++.+++ And he is opposing the commands of Christ, who said, '`Be not of men called master,
for ye have one master, even Christ,`' (who conquers death and hell.) And he saith,
'`Why may they not be called master?`'

[.discourse-part]
A+++.+++ It is his master that teacheth him to be called of men master,
that is gone out of the truth; but Christ said,
'`Be not of men called master;`' and woe be to them that are. Matt. 23.
And you are they that are made by the will of man,
that break his commands George Willington`'s book,
called '`The Gadding Tribe Reproved`'. A right title to his own condition is his book,
who, like a wild beast, is gadding up and down; but the Lord rebuke such spirits.
His principles follow.

[.discourse-part]
P+++.+++ He himself falls to judging others, and then cries,
'`O man! who art thou that judgest another,`' etc.
See page 9.

[.discourse-part]
A+++.+++ And doth not see the work that he is doing himself.
But bids others not judge, and falls to judging himself,
which is like all the rest of his gadding tribe;
and how they run with their horns at the righteous, and push at the upright in heart!
But the Lamb is above them all, and the wrath of the Lamb is kindled;
therefore the beast rages, who makes war against the Lamb.
And where judgment is come through into victory, he may judge;
and the hidden things of darkness are brought to light,
and the counsel of the heart made manifest; and the Lord is come,
and '`the spiritual man judgeth all things.`' But he shows
that the counsel of his heart is not made manifest,
nor his hidden things of darkness brought to light, and the Lord is not come to him,
and so cannot judge.
And George Willington hath judged before his time, with which he is charging others,
therefore his words shall be his burden.

[.discourse-part]
P+++.+++ And his principle is, '`that he is justified by faith alone without good works,`' etc.
See page 10.

[.discourse-part]
A+++.+++ What! without the faith that works by love?
Hast thou concluded those works to be the works of Popery,
which are the works of faith that works by love, that gives the victory?
How dost thou gad now?
whither art thou gadding now?
Know, faith that works by love is owned, and he that believes has ceased from his works,
as God did from his, and hath entered into his rest.
And faith gives victory over all the Popish murdering spirits, and thine also,
and your works; which gives to have access to God,
and the works of such are wrought in him.

[.discourse-part]
P+++.+++ He saith, '`Whilst the upstart sect of Quakers look after the light within,
we have a more sure word of prophecy,`' etc. and so would
make the sure word of prophecy not the light within.
See page 12.

[.discourse-part]
A+++.+++ His spirit he hath made manifest, where it is,
amongst them that are gone from the apostles, who stand against the light within.
For they that draw from the anointing within are the seducers,
and they went forth from the apostles that went from the anointing within.
Art not thou and you and the world all gadded from the anointing within you,
and so seducing one another?
Therefore have you so many heaps of teachers, arming yourselves,
and making lies your refuge against them that are come to the anointing,
which you are all gadded from, giving judgment against yourselves,
who will not have people to own the light Christ Jesus,
'`who doth enlighten every man that cometh into the
world.`' And none own the anointing within,
who own not the light, which you who have apostatized from the apostles deny.
And the Quakers are risen up in the night of apostacy,
and discover you all what you are in, and what you went from,
and what hath been lost since the days of the apostles.
And an earthquake is coming upon you that hath not
been since the foundation of the world,
out of which earthquake we are come, into that which cannot be shaken.
The Quakers are not the gadding tribe, they have the anointing in them,
and as it shall teach them, they shall abide in the son of God and in the Father.

But it is manifest that thou and the whole world are gadded
from the anointing within you which should teach you,
and so are turned against the saints and the Lamb.
And have been the harlots, and the mouths of the false prophet,
blaspheming God in his tabernacle, and have drunk the blood of the saints, and martyrs,
and prophets, and made war against the saints to overcome them, and have overcome them;
but the Lamb and the saints shall get the victory.

[.discourse-part]
P+++.+++ And thou tells us of '`a creed and Catholic faith,
commonly called the apostles`' creed, which creed and Catholic faith,
except a man believe, he cannot be saved,`' etc.
See page 16.

[.discourse-part]
A+++.+++ Who taught thee all this language?
Where did the apostles teach thee any such thing as the Catholic creed?
The apostle teacheth us no such thing as a Catholic creed.
Didst thou not learn this of the pope who apostatized from the apostles?

And the twelve apostles taught thee no such doctrine as the Catholic creed,
and thou sayst, they signed it.
Nay, the pope signs thee that creed, and the sacraments; thou hast the pope`'s signature.
But we are come to the foundation of God, which was before the pope was, and we gad not.
Thou shouldst not tell lies, and say they gad that come unto God, the elect of God;
God`'s elect, Christ the light, was the salvation before thou and the pope were.

[.discourse-part]
P+++.+++ And thou sayst, '`Doth any forsake the ministry to follow a new light,`' etc.
See page 17.

[.discourse-part]
A+++.+++ That ministry that deny the light that enlightens
every man that cometh into the world,
(as this gadding tribe of ministers, and professors,
have done and do since the days of the apostle,) deny the foundation of God.
The light we own which every man that cometh into the world is enlightened withal,
which is the foundation of God; and deny them to be any ministers of Christ,
that deny the light that enlighteneth every man that cometh into the world,
and his ministers we own.

[.discourse-part]
P+++.+++ And thou sayst, '`Do not forsake the temple and truth of God,
to follow the bleating of Jeroboam`'s calves in Dan and Bethel,`' etc.

[.discourse-part]
A+++.+++ Now whither art thou gadded?
Art thou not gadded in this from the apostles`' doctrine,
to the temple which the apostles brought the people off from?
where is thy light now?
How ownest thou Christ, who keepest people to the temple?
and tellest them of Jeroboam`'s calves in Dan and Bethel?
Where is there any people gadding thither?
Hast thou lost thy reason and sobriety, to publish thy madness to the nation?
And did not Christ say the temple should be thrown down? Matt. 24.
And Stephen witnessed against it, and was stoned to death:
and thou art calling people to it; and your Popish mass-house,
which you call your temple, and which you have set up since the days of the apostles,
is like unto the idol set up at Dan and Bethel.

[.discourse-part]
P+++.+++ And he saith '`your ancient divines are them that have entered in at the door,`' etc.
See page 20.

[.discourse-part]
A+++.+++ How can you and your ancient divines enter in at the door,
when you deny the light that enlightens every man that comes into the world,
which is Christ the door?
Therefore it makes you to gad up and down without light, in the dark.
Now is the stone fallen upon you, and the rock you are splitting yourselves against.
Now shall the saints know the song of the lamb,
rejoicing over the beast and the false prophets.

[.discourse-part]
P+++.+++ He saith, '`The written word the ingrafted is able to save the soul,`' etc.
See page 21.

[.discourse-part]
A+++.+++ The ingrafted word is able to save the soul, but the letter, the written words,
are not.
The Pharisees had the written words, but stood against the saviour of the soul.
And how art thou gadded here in thy judgment?
How art thou like to own the word that saves the soul, when thou denies the light?

[.discourse-part]
P+++.+++ He is stirring up the magistrate to persecute, his own mouth condemns him,
who pretends '`love,`' etc.

[.discourse-part]
A+++.+++ And thou that gads abroad in thy mind to stir up the magistrate to prosecute,
art not in the life of the apostles, nor Christ, but in the spirit of the false prophets,
and antichrists, and one in that which all persecutors come from, out of the truth.

[.discourse-part]
P+++.+++ Again thou sayst, '`we ought not to judge,`' etc.
See page 23.

[.discourse-part]
A+++.+++ Let all people that read thy gadding tribe, see if thou dost not judge,
and so comest under judgment, by thy own words.
And the time was come to the apostles when they went
on to the '`eternal judgment,`' which we own.
But this is not for such as are crying up temples and persecutors,
nor stumbling at the light: your measures are all too short for this,
your whole gadding tribe that are out of the light that
every man is enlightened with that comes into the world.

[.discourse-part]
P+++.+++ Again thou sayst, '`The apostles were to call the ministers of Christ immediately,
and the immediate call from God is not enough,`' etc.
See page 24.

[.discourse-part]
A+++.+++ So thou hast set up the mediate before the immediate,
and judgest the immediate not sufficient.
But thou art corrected by the scriptures, and the apostle corrects thee, who saith,
'`I received it not of man,
nor by man;`' and bade others look at Jesus the author of their faith.
And the apostle does not say that they were to call men mediately,
he doth not teach such doctrine as that their ministers were called mediately,
nor did he send them forth so, but it is thou that art gadded from the counsel of God.
And the apostle confutes thee,
who said he was '`an apostle not of men nor by men,`' and
all the apostles went forth by the immediate power of God,
and the church of God was gathered by the same power.
But you are the mediate, fallen from the apostles, and made by the will of men;
but now with the immediate you are all comprehended.

[.discourse-part]
P+++.+++ And thou brings many scriptures to oppose Christ`'s commands,
and the apostles`' doctrine, which say, '`Be ye not of men called master,`' etc.
See page 28. For thou sayst, Christ doth not mean as he speaks:
for thou sayst '`the meaning is not, that is unlawful to be called master.`'

[.discourse-part]
A+++.+++ Here thou showest whither thou art gadded:
one that teaches to break Christ`'s commands.
But the woe that is denounced in the same chapter where the command is, belongs to thee.
So an antichrist that teacheth to deny Christ`'s commands, and despiseth his authority;
and one that calls him Lord, and doth not the thing that he commands.
But it is not such that enter into the kingdom:
and this thou shalt witness at last when thy words fall heavy upon thee.
