[#ch-16.style-blurb, short="Antichrist In Man the Greatest Idol"]
== Joshua Miller`'s book called, [.book-title]#Antichrist In Man the Greatest Idol.#

[.heading-continuation-blurb]
Which is a fit title for himself; who calls that antichrist, and mystery Babylon,
that justifies within; contrary to the apostle`'s doctrine who saith,
'`we are justified by faith in Christ Jesus,`' which is in the heart.
As for the rest of his slanders and lies in his book, they are not worth mentioning,
but these that follow.

[.discourse-part]
P+++.+++ He calls them '`devout men`' that denied the light that hath
enlightened every man that cometh into the world,`' etc.
He saith,
'`The Quakers are the saddest and most deplorable spectacles
of revolted professors that ever I heard or read of,
since my knowledge of them,`' etc.
See page 2.

[.discourse-part]
A+++.+++ The Quakers have revolted from you apostates that are inwardly ravened,
as the converted Jews did that were turned to Christ;
for the Jews revolted from the temple and the priests, and turned to Christ,
from the other Jews,
and owned the light which lighteth every man that cometh into the world,
which you revolters deny, that have reigned since the days of the apostles,
and so are ignorant what we are come to, and the apostles were in,
and that which was before you and they were.

[.discourse-part]
P+++.+++ He saith, '`The angels of light, which are holy and without sin, may be devils,`' etc.
See page 3.

[.discourse-part]
A+++.+++ The devil fell from the light, from the holiness, and so he cannot transform into that.
And all holiness which is not in the light, is such as the Pharisees were in,
and the whole world, and is condemned with the light.

[.discourse-part]
P+++.+++ He saith, '`Salvation by the light within is cursed,`' etc.
See page 6.

[.discourse-part]
A+++.+++ Contrary to the apostle, who saith,
'`the light that shineth in the heart gives the light of the knowledge
of the glory of God in the face of Christ Jesus.`' And contrary to John,
who saith,
'`every man that cometh into the world is enlightened;`' '`and as many as received him,
to them he gave power to become the sons of God.`' And the power of God
is the gospel of salvation to every one that believes in the light;
and he that believeth in the light hath the witness in himself.
And the apostle turned them from the darkness to the light.
And the word of faith that saves the soul, was in their hearts;
and there were the glad tidings, the gospel.
And priest Shaw saith, '`The gospel is the four books of Matthew, Mark, Luke,
and John.`' But the apostle saith it is the power of God; and saith, many have the form,
but '`deny the power.`' So now here himself he hath cursed; so this same man is a curser,
as the Papists are.
Both he and they are found out of the doctrine of Christ and the apostles, who say,
'`Bless and curse not.`' And the Scotch priests likewise are cursers,
as in the Scotch principles`' ye may see;
and no one knows salvation but by the light within,
which doth enlighten every man that cometh into the world,
which is the salvation to the ends of the earth.

[.discourse-part]
P+++.+++ And he calls his steeple-house '`St. Andrews.`' See page 7.

[.discourse-part]
A+++.+++ Never did prophets nor apostles give such names to houses, but the pope,
who is his teacher.

[.discourse-part]
P+++.+++ He saith, '`It is an error to say,
that the light which every one hath that cometh into the world,
is sufficient to salvation, without the help of any other means or discovery,`' etc.
See page 9.

[.discourse-part]
A+++.+++ Contrary to Christ, who brought the Jews off from all other helps to himself,
and said, '`Believe in the light while ye have the light;`' and,
that '`they that believed in the light should not abide in darkness.`'
And '`no man cometh to the Father but by me,`' saith Christ.
For he was the way, the truth, the light in men, and the life,
and there is no salvation by any other name but by him.
And none know the blood of Christ which cleanseth,
and the offering for the sins of the whole world,
but with the light which cometh from Christ Jesus, who is sufficient,
who is the salvation to the ends of the earth;
so he is the only means without any other help.
And as the anointing in people doth teach people, they shall continue in Christ:
and as they '`walk in the light as he is in the light,
they shall have fellowship with the Father,`' from whence all helps come;
and Christ will dwell in man, and walk in man, and what need have they any more helps?

[.discourse-part]
P+++.+++ He saith, '`It is an error to say,
we are justified by that which Christ doth in us,`' etc.
See page 9.

[.discourse-part]
A+++.+++ Contrary to the apostle, who saith,
'`We are justified by faith in his blood;`' and the faith is in the heart,
and the blood is in the heart that purifies it, and held in a pure conscience.
And the word of faith is within.
Rom. 10. And faith gives victory over the world, and that which gives victory, justifies.
And Christ is within, who is justification, and sanctification, and condemnation;
each of these is found within; and thou art in the error,
and not fit to talk of these things, which thou understandest not.

[.discourse-part]
P+++.+++ Again he saith, '`It is an error (if not damnable) to say Christ is the means,
and that there is no other means of salvation,`' etc.
See page 13.

[.discourse-part]
A+++.+++ And Christ saith,
'`No man cometh unto the Father but by me;`' and he is able to save to the utmost.
And '`he shall be my salvation to the ends of the earth,`' saith the Lord.
And saith the apostle,
'`God is in Christ reconciling the world unto himself.`' And '`he that
hath the son of God hath life,`' and the Father and the son are one,
and there is no salvation in any other.

[.discourse-part]
P+++.+++ He saith, '`That Christ gives light to no man under that name but believers,`' etc.
See page 13.

[.discourse-part]
A+++.+++ Contrary to John, who saith,
'`he doth enlighten every man that comes into the
world,`' that all might believe through the light.
And contrary to Christ`'s own words, who bid them believe in the light while they had it;
and he that did not believe was condemned already; and he that did believe,
had the witness in himself.

[.discourse-part]
P+++.+++ He saith, '`It flatly contradicts the whole scripture, to say,
that the light wherewith Christ hath enlightened every man, etc. will save,`' etc.
See page 14.

[.discourse-part]
A+++.+++ God saith, '`I will give him for a covenant, for a light to the Gentiles,
and new covenant to the house of Israel and Judah;
and he shall be my salvation to the ends of the earth;`'
and such believing in it are saved,
and not believing are condemned.

[.discourse-part]
P+++.+++ '`The wise heathen philosophers had a greater measure of light in them
(which is the first Adam) than I can think any men have now,`' etc.
See page 15.

[.discourse-part]
A+++.+++ Which shows that he knows nothing of Christ the second Adam, the quickening spirit.
And he knows nothing of a new creature; for they '`who are in Christ are new creatures.
Nor of Christ the covenant of God, of light, of life, of peace,
who was glorified with the Father before the world began, which is beyond the first Adam,
and he hath set forth himself not to be as high as his heathen philosophers.
But many witness Christ in them in this age, as in the days of the apostles,
which is above the heathen philosophers.

[.discourse-part]
P+++.+++ The light which every man that cometh into the world is enlightened withal, Christ,
he saith, This is the light of nature and of reason.`' And saith,
'`It is a damnable doctrine to deny all external means of salvation,`' etc.
See page 16.

[.discourse-part]
A+++.+++ The apostle saith, '`We look not at things which are seen,
but at things which are not seen.
For the things that are seen are temporal,
but the things that are not seen are eternal;`' and that which is to salvation is eternal,
and is not external.

[.discourse-part]
P+++.+++ He saith, What word did Paul and Barnabas preach in the synagogues,
but the prophets?`' etc.
See page 19.

[.discourse-part]
A+++.+++ Nay, they preached Christ the end of the prophets.

[.discourse-part]
P+++.+++ He calls that '`a monstrous opinion, to compare them to the heathen,
who had not known there had been a God but by the scriptures,
and have no more knowledge but by it,`' etc. page 20.

[.discourse-part]
A+++.+++ The Pharisees had scriptures (and heathen men
may get scriptures) but knew not the true God;
for none know the true God but by the spirit of God,
(and the son of God reveals the Father,) though they may have all the scriptures:
and the light that shines in the heart gives the knowledge of him.
And this the apostle spoke to them that had the scriptures.
And who are of faith, are of Abraham,
and in the knowledge of him that knew God before the scripture was written.

[.discourse-part]
P+++.+++ And he saith, '`That the law and the testimony, are Moses and the prophets,`' etc.
See page 21.

[.discourse-part]
A+++.+++ Contrary to the rest of the priests, who say, they are '`the Old and New Testament;
and he and the rest of the priests are contrary to the apostle, who saith,
the law and testimony are the light, and spirit of prophecy.
Many may have the Old and New Testament, yet deny the light and spirit of prophecy,
as priests and professors do now, who say prophecy is ceased.
Here they deny the practice of the church, where edification, learning,
and comforting are, prophesying all one by one.`' Such they prison and persecute;
and they are not like to own prophecy, when they deny the light,
which doth enlighten every man that comes into the world, which is the end of prophecy.
And none own Christ, who own not prophecy.
A prophet is a seer, and they that deny prophets are all blind, and in the dark,
and are such as have ravened from the spirit of God, and have killed the prophets.

[.discourse-part]
P+++.+++ He saith, '`The prophets are more certain than any other revelation.`' See page 21.

[.discourse-part]
A+++.+++ Was not the son of God revealed, the end of the prophets?
Did not God reveal him which came '`in the volume of the book,
to do the will of God?`' And so they that had the prophets, and the law, and types,
and shadows, knew not the son of God that was revealed, that was their end,
spoken of in the prophets and epistles, and who is now revealed.

[.discourse-part]
P+++.+++ He saith,
'`The patriarchs and prophets were justified by conceiving Christ without,`' etc.
See page 24.

[.discourse-part]
A+++.+++ Now the patriarchs and prophets had the spirit that gave them an evidence of him,
and by faith they saw him, which is beyond a conceiving, by which they were justified.

[.discourse-part]
P+++.+++ He saith, '`Justification by works, and inherent grace we call Christ,`' etc.
See page 25.

[.discourse-part]
A+++.+++ We say Christ is the end, the substance,
and who believes in him hath ceased from his own works;
he is the end of gifts and graces, and man`'s own inheriting;
and no one knows justification, but who receives the grace that brings salvation.

[.discourse-part]
P+++.+++ He saith, '`This justification by a righteousness within us, is man`'s grand idol,
and Christ`'s arch-enemy,`' etc.
See page 25.

[.discourse-part]
A+++.+++ '`We are justified by faith in Christ Jesus,`' and that is in us, in the heart.
This he calls an idol, and Christ`'s enemy, which he is the author of.
So the doctrine this man teacheth is contrary to the apostle,
in the error from the apostles; and faith it is that purifies the heart,
by which we are justified, and not by works, which throws down all idols,
and the enemies of Christ, which thou art one;
and none own justification but who witness justification within, faith in the heart;
and Christ being within, there is justification.

[.discourse-part]
P+++.+++ He saith, '`We miserably wrest the scripture,`' because we say,
'`he that respecteth persons commits sin,`' etc.

[.discourse-part]
A+++.+++ Now let all read that in James the apostle,
how that he that respects persons commits sin,
and is convinced by the law as a transgressor;
so he teaches men to transgress the commands of God, contrary to the apostles,
who taught men to keep them.

[.discourse-part]
P+++.+++ He saith,
'`Popery and vain philosophy are the foundation of the Quakers`' religion,`' etc.
See page 30.

[.discourse-part]
A+++.+++ Their foundation is the light of Christ,
'`which lighteth every man that cometh into the world,`'
which was before Popery or philosophy was,
which you are in, as your books, naming of days, and colleges, and steeple-houses,
make it appear.

[.discourse-part]
P+++.+++ He saith, '`And to believe, or think our justification is by something wrought in us,
is that antichrist whose name is mystery, Babylon the great,
the mother of harlots,`' etc.
See page 32.

[.discourse-part]
A+++.+++ The apostle saith, '`We are justified by the faith of Christ Jesus.`' Gal.
2+++.+++ And faith purifies the heart,
and is a '`mystery held in a pure conscience.`' This
justification is by the faith of Christ within,
and this thou calls antichrist, and mystery Babylon, who art there thyself,
that art out of this '`faith that purifies the heart:
for all the holy men of God were justified by their faith, and the faith is in the heart.
And thy belief that is without thee, and faith in Christ, is like unto the Jews`',
who stood against him when he was come.
True faith gives victory over mystical Babylon and the world,
in which faith men please God, in which is unity.
