[#ch-17.style-blurb, short="The Quakers`' Principles Quaking"]
== Ralph Hall`'s book, called [.book-title]#The Quakers`' Principles Quaking.#

[.heading-continuation-blurb]
His principles in it follow, and are turned upon himself,
whose works are for the fire, and to be burned.

[.discourse-part]
P+++.+++ He saith, '`It is delusion to give up to the light within to be the judge,
etc. and calls it an obscure kind of chymistry,`' etc.

[.discourse-part]
A+++.+++ The apostle commands to judge themselves; which they cannot do but with the light,
by which they may see themselves.

[.discourse-part]
P+++.+++ He saith,
'`Doth the light of nature (as he calls it) give liberty to women
to teach?`' and calls it '`gross and palpable darkness,`' etc.

[.discourse-part]
A+++.+++ Contrary to the apostles`' doctrine, and the mind of God, and the prophets, who said,
'`God would pour out his spirit upon all flesh:
and his sons and daughters should prophesy.`' So he is in the darkness,
a limiter of the Holy One, and a quencher of the spirit,
and this is above the light of nature.

[.discourse-part]
P+++.+++ He saith '`The Quakers blame everything; and convince of nothing,`' etc.

[.discourse-part]
A+++.+++ Are ye not all, you hirelings, convinced of your covetousness?
of your respecting men`'s persons for advantage?
of your teaching for filthy lucre, and for your gain from your quarters?
and of your love of money?
Are not ye all convinced?
Have not the Quakers convinced you all of those things, and of your pride, and ambition?
And have you not been corrected by, and reproved for this by Quakers and scripture?

[.discourse-part]
P+++.+++ He saith, '`The spirit of light will be judged by the scripture,
keeping to the scriptures,`' etc.

[.discourse-part]
A+++.+++ Which is contrary to the scriptures, and the apostles`' doctrine.
But he is like the Jews, who had the scriptures, yet judged the spirit of light.
But the spirit of light owns scriptures,
and the scripture doth not judge spiritual light, and they are not one against the other,
but are in unity.

[.discourse-part]
P+++.+++ And whereas he saith, '`Noah`'s ark was a true figure of the church of God,
so Noah`'s dove is a clear emblem of such as through affection of new and unknown paths,
stray from the church of God,`' etc.
See page 1.

[.discourse-part]
A+++.+++ Now you having strayed from the church of God,
are the false prophets which Christ said should come, Matt. 24.
and John saw were come; and the whole world are gone after you.
And ye have brought the nation to be water, and your tongues are waters,
and your multitudes waters, and your peoples waters;
on this account are the doves flying abroad;
and the Quakers found no rest for the soles of their feet amongst you.
For there is nothing but waters among you, the doves find you all waters,
not to set the soles of their feet upon.
But according to the eternal counsel and promise of God,
that the waters should be abated and dried up, they have found the ark of the testimony,
and the opening of the seals, and the tabernacle in heaven,
and the people of God begin to inhabit; and the kings of the earth shall not pass:
and that which you call your church hath been waters.

[.discourse-part]
P+++.+++ And whereas he brings the sayings of scripture, that speak of prophets, and pastors,
etc. and names places of scripture to oppose Christ`'s command, which saith,
'`Be ye not of men called master,`' etc.
See page 7.

[.discourse-part]
A+++.+++ Which is to no purpose but to manifest himself a transgressor
that abides not in the doctrine of Christ,
that hath not the Father and the son.

[.discourse-part]
P+++.+++ And he saith the prophecy of Malachi is upon us, who saith, '`Cursed be the deceiver,
who doth not bring in his tithes and offerings,`' etc.
See page 9.

[.discourse-part]
A+++.+++ We say the priesthood is changed, and the offerings are denied,
and he that holdeth them up is under the curse.

[.discourse-part]
P+++.+++ He saith, '`To take the scriptures as ye speak, brings in all absurdity,
as when the apostle saith the priesthood is changed,
the commandment is disannulled that took tithes.`' Then he saith,
'`he would prove that none had faith, to take the scripture as it is spoken:
for if they had it`' (saith he) '`as a grain of mustard seed,
then they should remove mountains, and heal the sick,`' etc.
See page 10.

[.discourse-part]
A+++.+++ Now by this he hath showed his ignorance; for Christ`'s words and the prophets`',
are true as they speak, and the things they speak of;
the fruits of the faith that they speak of are known, and the fulfilling of the promise.
And that which the apostle speaks of, Heb. 7.
is that the priesthood is changed, and the law disannulled also,
and that another priesthood is come in, not after the order of Aaron,
but after the order of Melchisedeck; without father, without mother,
without beginning of days, or end of life.
You run into all absurdities, that give your meaning to scriptures,
and by private interpretations have brought the world on heaps about the scriptures.
And who are in the faith, are in the healing of the sick, and removing mountains,
and you who are out of the faith have brought whole nations into sickness, mountains,
and rough places.

[.discourse-part]
P+++.+++ He saith, '`The priest`'s work is changed in point of administration only;
but in respect of the order, the priesthood is not changed,`' etc.
See page 11.

[.discourse-part]
A+++.+++ Contrary to the apostle, who said Christ came after another order,
and not after the order of Aaron; but came after the order of Melchisedeck.
So the order, and all things pertaining to it, fall, which Ralph Hall saith do not.

[.discourse-part]
P+++.+++ He saith, '`The matter is not changed in any one of the ceremonies,
only the manner of administration,`' etc.
See page 11.

[.discourse-part]
A+++.+++ The first covenant could make nothing perfect, saith the apostle.
The matter and the manner of all that pertained to the first priesthood changed:
the matter and the manner fell down when the life came in, the second covenant,
through which the new and living way was felt, whereby we enter in unto God,
by the blood and life of Jesus Christ, and the offering; and not by the first priesthood,
first covenant, tithes, offerings, and sacrifices.
So matter and manner all fell; and Christ came out of another tribe, that is, of Judah.
And not after the order of Aaron, but after the order of Melchisedeck,
and so after another matter.

[.discourse-part]
P+++.+++ '`And thou brings that concerning Jacob`'s paying
a tenth to the service of the house of God:
and why may not ye have tenths for the maintenance
of the house of God,`' to wit the steeple-house,
which was the Papist`'s mass-house.
Now see what a suitable measure thou hast, etc.
See page 16.

[.discourse-part]
A+++.+++ There was a time when the ark was maintained, and the tabernacle, and the temple,
and the storehouse, and tithes;
and there is a time when all these things are utterly denied.
So thou art a man that dost not divide thy work aright,
but a workman that may be ashamed of thy work.
Look on thy book, who art, crying up tithes and priests.
And thou sayst the order of Aaron is not changed in the substance,
contrary to the apostle, and yet pleads the order of Melchisedeck,
and so art in confusion.
And as for the order of Melchisedeck, ye are as short of that,
as of Christ in whom Melchisedeck ends.

[.discourse-part]
P+++.+++ He saith, '`The best of God`'s people have sin enough to be repented of,
and to be humbled for,`' etc.
See page 19.

[.discourse-part]
A+++.+++ Contrary to John who saith, '`He that is born of God doth not commit sin:
neither can he, because the seed of God remaineth in him;
and he keepeth himself that the evil one toucheth him not.`' And they were not to '`lay
again the foundation of repentance from dead works.`' And saith the apostle,
'`How can we that are dead unto sin,
live any longer therein?`' So thou art ignorant of the saints`' state;
for sin exalts and doth not humble, for that which brings down sin humbles.

[.discourse-part]
P+++.+++ He saith,
'`he knows not one in the nation that sues at the law those
that will not put into their mouths,`' etc.
And again he saith,
'`if they should not sue at the law such as do not give them maintenance,
they would sin in doing so: for it were to uphold covetous minds,`' etc.
See page 19.

[.discourse-part]
A+++.+++ Now this proves your covetous desires.
And the courts throughout the nation will witness against thee;
for most of the suits that are: in the nation for one particular thing,
are those of the priests against the parishioners,
because for conscience sake they cannot put in their mouths.
Therefore are they worrying of them like wolves,
and destroying them for their dishonest gain, which they do no work for.
And did not the ministers of God, the apostles,
rebuke such as went to law before the unjust, one among another?
And they bid them set up the least in the church to judge such things,
and told them they should '`judge the world,
yea angels;`' and not to go to law one with another about such things.
Then where art thou and thy generation, that say it is a sin if they do not go to law?
if the ministers do not sue for outward things?
Let the least in the church judge thee and them.
How unlike the apostles you are, who kept the gospel without charge,
and coveted no man`'s silver or gold, who preached the gospel, the end of the law,
and brought people from under it.
And you bring people into your inventions, but the day is come that you are seen,
and the night is past to many, and you can deceive none but those who are in the night;
the judgment is gone over your heads, the judge of the world is come.

[.discourse-part]
P+++.+++ He saith, '`Abraham`'s faith was imputed to him for righteousness:
and doubtless Job was a perfect man in God`'s account,
and Christ`'s righteousness is imputed to us,`' etc.

[.discourse-part]
A+++.+++ Yet thou sayst, '`none do good, no not one,`' and bringest that scripture in Rom.
comparing them that were in the faith,
with them that were gone astray both Jews and Gentiles.
See page 21. Now let all try and judge thee here, and see thy false measure.
Art thou a man fit to speak of the saints and their faith,
who puttest them that be astray, Jews and Gentiles, among them that believe,
making no difference between the precious and the vile?
so thou art not a man capable of true reason.

[.discourse-part]
P+++.+++ He saith, '`God`'s furnace is the grave,
where all the remainder of corruption shall be consumed,`' etc.
See page 22.

[.discourse-part]
A+++.+++ Now what differs this from the Papists who hold a purgatory?
And the saints witnessed, and said, '`now they were washed,
now they were cleansed,`' etc. while they were upon earth.
And they were sanctified through the obedience of the spirit, and they were justified,
and sat in heavenly places, on this side the grave, while they were upon earth,
and were made free from sin, and were perfect.

[.discourse-part]
P+++.+++ He saith, '`that Paul disclaimed perfection in himself,`' etc. page 23.

[.discourse-part]
A+++.+++ Paul said,
'`As many of us as are perfect be thus minded.`'
(He wrongs Paul`'s words.) And again he saith,
'`We speak wisdom among them that are perfect.`'

[.discourse-part]
P+++.+++ He saith, '`If a man were free from sin,
he would be free from temporal punishment and afflictions,`' etc.
See page 23.

[.discourse-part]
A+++.+++ Christ was free from sin, and the saints,
and yet he and they were not free from temporal punishment and affliction.
And so here he doth not divide the word aright.

[.discourse-part]
P+++.+++ He saith, '`If we attain to perfection here,
we should attain to a rest here,`' and brings the apostle`'s words,
'`doubtless there remains a rest to the people of God,`' etc.
See page 24.

[.discourse-part]
A+++.+++ The apostle saith there,
'`He that doth believe hath entered into his rest.`'
And so he doth not divide the word aright,
to know what state and condition it was spoken to.
And the apostle said, '`they (the ministers of Christ) were perfect,
and he hath perfected forever them that are sanctified.`'
And so thou art not a sanctified one,
and hast denied the offering that hath perfected forever them that are sanctified,
and so hast denied the covenant that blots out sin and transgression;
and '`the blood of Christ cleanseth from all sin.`'

[.discourse-part]
P+++.+++ But he saith, '`That doth not follow, that he that is dead to sin,
is freed from sin.`' See page 24.

[.discourse-part]
A+++.+++ Thus he is contrary to the apostle, who saith,
'`He that is dead to sin is freed from sin, and can live no longer therein.`'

[.discourse-part]
P+++.+++ He saith, '`The law of God is a standing rule to the world`'s end,`' etc.
And thou that sayst the law is a standing rule, hast denied Christ the end of it.
See page 25.

[.discourse-part]
A+++.+++ But the scripture and Christ say, the law must be fulfilled.
Christ is the everlasting covenant in the heart and in the mind, the end of the law,
who was before the scripture was written,
glorified with the Father before the world began.
Many have the scriptures, and yet are from the law of God written in the heart,
and neglect that which brings into covenant with God,
by which the scriptures are fulfilled.
So here again thou dost not divide the word aright,
and bringest not people into that which doth fulfill scripture.

[.discourse-part]
P+++.+++ He saith, '`Because this light doth not lead us to close with God`'s ordinances,
the sacraments, he looks upon it as a delusion of Satan,`' page 26.

[.discourse-part]
A+++.+++ The scriptures mention no such word;
and the light was before your invented sacraments were, and cannot join with them,
but condemns them, but it owns the scripture and the ordinances of God.
