[#ch-18.style-blurb, short="Justifying Our Call Against the Quakers"]
== Richard Baxter`'s book called '`A Second Sheet To the Ministry, Justifying Our Call Against the Quakers,`' Etc. His principles follow.

[.heading-continuation-blurb]
Because the children of God cannot satisfy his ungodly lusts,
therefore he is complaining to the magistrates.
So he is one of the complainers and murmurers.

[.discourse-part]
P+++.+++ He saith,
'`that Timothy was not to hold fast that which he had immediately received from God,
but that which he had received from Paul,`' etc.
See page 5.

[.discourse-part]
A+++.+++ In this thou art contrary to the apostle, who bid '`stir up the gift that was in him,
and keep the faith,`' (which Christ was the author of,) and that
would not contradict the apostle`'s words who was in the faith:
and that which Timothy received from God, he was to hold fast,
in which he had unity with the apostle.

[.discourse-part]
P+++.+++ He saith, '`The holy ghost is to help us in keeping that which is committed to us,
and not to reveal more.`' See page 4.

[.discourse-part]
A+++.+++ Timothy could not know doctrine but by revelation, and doing the will of Christ.
How art thou exalted, that wouldst put lies upon the apostle, and limit the Holy One,
and set bounds to the just, and be a teacher of the holy ghost,
what it must not reveal! how art thou exalted in this above all that is called God,
and blasphemously sittest in the temple of God!
Thou wouldst be a teacher of the holy ghost, who must be the teacher,
and tell what it must reveal, and what it must not reveal!
Thou must be stopped for thy presumption.
If ye have nothing but what the holy ghost hath given forth, the form of words,
the church of Rome hath the same, and all the false prophets upon earth; and antichrists,
seducers, and devils get the scriptures given forth from the holy ghost,
and hold these words in the unrighteousness, and resist the holy ghost,
and say it must reveal no more.
These come under the judgment of the Almighty; God`'s decree is against them.
But the spirit, the holy ghost '`leadeth into all truth,`' and doth reveal;
and the apostle bids the saints wait for the revelation of Jesus.
And the grace was brought by the revelation of Jesus,
and the secrets are revealed to them that fear God,
and the '`spirit reveals the things of God,`' but thou sayst it reveals no more;
which shows thou dost not know the scriptures, nor God, nor the spirit.

[.discourse-part]
P+++.+++ Whereas thou sayst, '`ye have the scriptures of the prophets and apostles,
and Christ`'s words, and so are not to look for new prophets,
and that would be a question to the church,
and that would show mutability in Christ.`' See page 6.

[.discourse-part]
A+++.+++ In this thou hast showed thyself of what generation thou art;
for there hath been the mother of harlots, that hath drunk the blood of the prophets,
martyrs, and saints.
And such as drink the blood have the form, and get the sheep`'s clothing,
but cry '`prophecy is ceased,
and revelation from heaven is ceased,`' only they have a standing rule,
the scriptures without; and so here they have their clothing, the sheep`'s clothing,
but ravened from the spirit, and so have denied the church in which there is prophecy,
and the spirit of God; for where that is, there is prophecy amongst sons and daughters,
but not amongst you apostates.

[.discourse-part]
P+++.+++ He finds '`fault with a man that will not believe except he see, as instance,
a man will not believe they are ministers of Christ, except they work miracles, etc.
And will not believe there is a parliament, or Holland, or France, or Spain,
except he have been in them,`' etc.
See page 6 and 7.

[.discourse-part]
A+++.+++ Thou and thy wits are compassed,
for revelations and prophecies are now spoken forth and witnessed,
and thou canst not believe, because thou dost not see;
and thou art finding fault with others that do not believe because they do not see.
Thou art seen and disapproved, and so now in that thou judgest others,
thou art judged thyself, who art blind and out of the life.
And many may see there is a Holland, and other countries,
though they have not seen them with an outward eye.
And we believe the ministers of Christ, though they do not work miracles;
but that you are apostatized from them we do believe and see.

[.discourse-part]
P+++.+++ He saith, '`The saints were not to forsake the assembling of themselves together,
as the manner of some was,`' etc.
See page 8.

[.discourse-part]
A+++.+++ That was in the time of the apostles, before the apostacy.
But since the apostacy, the beast, false prophets,
and murderers of the saints are got up, and assemble themselves together,
and deceive the nations, and are breaking the saints`' meetings,
that keep the testimony of Jesus and the spirit of prophecy,
and overcome by the blood of the Lamb and the testimony of Jesus.
Christ is the rock, and his church doth continue:
but they that Christ said should come are come,
the false prophets that should get the sheep`'s clothing.
And John saw they were come, who went forth from them,
and made war against the saints and the Lamb;
but the saints and the Lamb shall get the victory.
And we are come to the assembly of the saints,
to that which was before you were apostatized;
for your assemblies have forsaken the saints, your fruits declare it.

[.discourse-part]
P+++.+++ He saith, '`Because they have the people`'s consent, and the magistrates`' allowance,
therefore that is true ordination,`' etc.
See page 11.

[.discourse-part]
A+++.+++ Balaam had the people`'s consent, and the heathenish magistrates`' allowance,
when he should have cursed the children of Israel, and so this is no proof of ordination.
And the chief priests had the people`'s consent;
and many of the magistrates turned against Christ.
So this is no ordination for ministers of Christ.
And the beast and the false prophet shall rise against the Lamb and the saints,
and yet they shall have sheep`'s clothing; this is no proof of their ordination from God,
but all this proves it from man.
But they who have their ordination from God,
are not owned either by people or magistrates, in their wills; but by those who fear God,
and are come to the spirit of God, they are owned by that to which they minister;
and they never went to the magistrates for their allowance.
And here again you are apostates from the apostles,
and in the steps of the false prophets, whose ordination is by the consent of the people,
and your allowance from the magistrates,
who are from the allowance of Christ that he gives to his ministers,
and the ordination of the apostles, that was not from man, nor by man.

[.discourse-part]
P+++.+++ Thou bids us '`mark the canon of the holy ghost in Timothy.`' See page 11.

[.discourse-part]
A+++.+++ There is no such word as canon in Timothy; and thou tells us of a Catholic church,
and we cannot find any such word in scripture;
but we perceive of whom thou hast learned these words,
and what centre and stock thou comest of, the pope, and not the apostles.

[.discourse-part]
P+++.+++ He saith, '`they have an uninterrupted succession drawn from the apostles,`' etc.
See page 13.

[.discourse-part]
A+++.+++ Your succession is from the pope, apostatized from the apostles,
for ye are out of the apostles`' doctrine,
and in all your whole worship corrected and reproved by scripture.
Did the apostles set up, a temple?
set up tithes?
set up your schools and colleges?
Is not the pope the author of all these?
Are not ye his successors?

[.discourse-part]
P+++.+++ Thou sayst, '`ye are the ministers of Christ,
because ye have the scriptures and books,`' and such like,
'`and that you are not usurpers of the authority,`' etc.
See page 16.

[.discourse-part]
A+++.+++ Now there is not one of you all, that ever durst say,
ye have heard God`'s voice immediately from heaven, or Christ`'s voice,
or have the same spirit the prophets, and apostles, and Christ had,
or immediate revelations from heaven as they had.
So then you are in another ordination than they were in, and usurpers into the ministry,
and intruders into those things you never saw.
And cannot any one be as good a pastor or minister as you,
seeing all your teaching is but from books and other men`'s writings?
Why may not others, learn the same books and writings,
and so come to be teachers and pastors as well as you,
seeing you have nothing but from books and writings, and old authors?
Why may not all that read those be pastors and teachers,
and so then where would be the hearers?
And so with the life are you all judged, the spirit of God which gave forth scriptures,
which was before your old books and authors were.
