[#ch-19.style-blurb, short="The Testimony of the True Jesus"]
== Thomas Higginson`'s book, called, [.book-title]#The Testimony Of the True Jesus.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`The word is not righteousness without the flesh,`' etc.
See page 3.

[.discourse-part]
_Answer._ The word is righteous itself, and the flesh righteous as it became.

[.discourse-part]
_Principle._ He saith, '`Men are presented perfect to God, and without spot, before any work done,
or good whatsoever,`' etc. page 3.

[.discourse-part]
_Answer._ There is none doth the work of God but who believes;
and he that believes overcomes the world, and his works are wrought in God,
and he hath the word of reconciliation in him.
And by this doctrine of thine all the world is presented perfect to God;
for he is the offering for the whole world.
But those that believe are partakers, and those that do not believe are condemned.
Yet I say, the Lord helps the unbelief of many, '`who is the saviour of all men,
especially of them that believe;`' and men are not presented to God while they do evil,
and before they are sanctified and holy.

[.discourse-part]
_Principle._ He saith, '`The invisible things of God, and the eternal power and glory of God,
may be known by that of God in every man,
but not his good pleasure or purpose of grace,`' etc.
See page 4.

[.discourse-part]
_Answer._ Is the glory seen and known, the godhead known, the invisible things of God,
and the eternal power, and not the good pleasure of God, nor his purpose of grace?
Doth not the godhead dwell in Christ, and his fulness, bodily?
And is not Christ the power of God?
And doth not he that knows God, and his glory, and his eternal power and godhead,
know the son?
Consider that; '`For he that hath known the son, hath known the Father also,`' and grace,
and the purpose of God.

[.discourse-part]
_Principle._ He saith, '`Man may know God, and his eternal power, and godhead, and glory,
and yet know nothing of the mystery of Christ,
nor can that (which thou sayst shows these things) lead
unto the mystery of the knowledge of Christ,`' etc.
See page 4.

[.discourse-part]
_Answer._ Where the eternal power and godhead is known, his power, his glory,
and the invisible things of God, there is something of Christ known, the mystery.
For '`there is none knows the Father but the son,
and he to whom the son reveals him.`' And he that knows the Father knows the son.

[.discourse-part]
_Principle._ He saith, '`To say that Christ is within man, is to worship angels,
and not to hold the head Christ,`' etc.
See page 5.

[.discourse-part]
_Answer._ None come to witness Christ the head, but who witness him in them,
that the angels must worship, that died and suffered at Jerusalem;
and they that worship him in them, worship not the angels;
and they that are not worshipping him in them, are worshipping men, devils, or angels.

[.discourse-part]
_Principle._ He saith, '`It is a bewitching of the mind, to preach Christ within the saints,`' etc.

[.discourse-part]
_Answer._ Did not the same apostle that spoke to the Colossians, of '`worshipping of angels,
not holding the head,`' preach Christ in them?
And he told them of '`intruding into things they never saw.`' Did not he say,
'`Christ in you the hope of glory, whom we preach, warning every man,
that we may present every man perfect in Christ Jesus?`' How contrary
to the apostles and Christ Jesus dost thou divide the word,
that callest this doctrine bewitching?
And thou that preachest another doctrine contrary to his, art accurst.

[.discourse-part]
_Principle._ He saith,
'`To say the light in every one (wherewith Christ Jesus hath enlightened
them that come into the world) is the way to Christ and the Father,
and is the sure word of prophecy which people are to take heed unto,
this is to deny the person of Christ, as the object of faith,
and the scriptures as the rule of faith, and faith itself,`' etc.
See page 8.

[.discourse-part]
_Answer._ In this thou hast showed thy ignorance;
for none know the person of Christ but with the light that comes from him:
none know the mediator, none know the author of their faith,
but with the light that comes from Christ:
and none know the scriptures of truth but with the light.
And Christ is the rule of faith, and author of it, and the giver;
and many may have the scriptures and not faith.
So in this thou dividest not the word aright, but art incapable of dividing the word.
And that is the sure word of prophecy that shines in a dark place,
which people are to take heed unto,
'`till the day dawn and the day star arise in their hearts.`'

[.discourse-part]
_Principle._ He saith, '`To say that redemption and righteousness are wrought within,
is to bring Christ down from above out of heaven, or raise him from the dead,
and to make the blood of Christ as another man`'s,`' etc.
See page 9.

[.discourse-part]
_Answer._ Now Christ is not known to be the justification, but as he is known within,
and redemption out of Adam`'s state in the fall.
For '`he that believes hath the witness in himself,`' and '`ceaseth from his own works,
as God did from his,
and enters into his rest.`' The world may profess Christ without them;
but if he be not within them, they are reprobates,
and shall fall short of justification and redemption.
And if they have not the son of God, they have not life; and many will say, Lord,
but do not the thing that he commands.
And one of thy generation of professors that wrote against the Quakers, said,
'`that the blood of Christ was corruptible,`' (and so it was like
the blood of another man,) and thou sayst it is not.
Now we say, that blood which cleanseth from all sin is incorruptible;
and they that witness Christ in them, and justification and redemption, need not say,
'`Who shall raise Christ from the dead, or fetch him from above,`' as thou sayst.

[.discourse-part]
_Principle._ He saith, '`Obedience to the spirit within,
and Christ a worker and a lawgiver in their conscience,
and a worker of it in their persons, but not as a saviour:
and what of God is felt or wrought in them, that they believe.
While the unspeakable righteousness, operation of life in Christ reserved, with faith,
liberty, joy and peace, etc. are hid from their eyes,`' etc.
See page 10.

[.discourse-part]
_Answer._ Now can any be obedient to the spirit within, and to Christ a worker, and a lawgiver,
and feel the work of God in themselves, and yet the unspeakable righteousness,
and the operation of life hid in Christ, and faith, and liberty,
joy and peace be hid from their eyes?
Can a man know all these things, and yet not know Christ to be a saviour?
Here thou art judged, and thy knowledge; for he that knows these things, knows a saviour;
and let the righteous, whose eyes are open, judge how thou divides the word.

[.discourse-part]
_Principle._ He saith, '`Faith holds things as true in Christ,
though hid from sense and feeling,`' etc.
See page 11.

[.discourse-part]
_Answer._ How cometh the just to live then, if there be not a feeling in his faith?
And how then cometh he to have the victory over the world?
And how doth faith purify, if there be not a feeling?
And how is it held in a pure conscience, if there be not a feeling?
And how cometh he to have access to God through faith?
And doth not the scripture speak of them that were in the faith,
felt and handled the word of life?
And was this without the faith of God`'s elect, or of sense?
Therefore in this thou mayst see how incapable thou art to divide, the word.

[.discourse-part]
_Principle._ He saith, '`They that put spiritual working for the grace of Christ,
destroy Christ Jesus.`' See page 11.

[.discourse-part]
_Answer._ They do not destroy Christ Jesus, that put spiritual working for the grace of Christ,
for the works of the spirit do not destroy Christ; for where the works of the spirit are,
there is the grace of Christ Jesus; and none own Christ,
but who are in the works of the spirit, and his graces; and they destroy Christ,
and deny him, that are out of the works of the spirit,
and his graces are spiritual workings.

[.discourse-part]
_Principle._ He saith, '`The sight of the Godhead without faith in Christ,
is the foundation of all false worships,`' etc.
See same page.

[.discourse-part]
_Answer._ Can any have a sight of the Godhead, and not see Christ and have faith in Christ?
And who have faith in Christ,
do they not see that the fulness of the Godhead dwells in him?
And were not their minds turned from that of God in them
(which declared the invisible things of him from the creation,
even his eternal power and godhead) whom the apostle found fault with?
Let all examine and judge, and read the scripture, Rom. 1. and try.

[.discourse-part]
_Principle._ He saith, '`Obedience to Christ within is a sentence of the law, not of grace,
and denying Christ, overwhelming the afflicted in sorrow without hope,
and turning the feet of the lame out of the way.`' And bids beware of such doctrine, etc.
See page 12.

[.discourse-part]
_Answer._ If so,
people must beware of the doctrine of the apostle who told them to whom he preached,
'`Christ was in them except they were reprobates.`' And Christ was within them
the hope of glory.`' They turn people out of the way who keep them reprobates,
without hope, and it is a denying of Christ, not to preach Christ within,
and a keeping people under the law, which Christ is the end of.
And where Christ within is, there is obedience, which is the end of the law,
and there is grace.

[.discourse-part]
_Principle._ He saith, '`The justification and redemption by obeying the light within,
appears to his understanding to be a mystery of iniquity,`' etc.
See page 13.

[.discourse-part]
_Answer._ Thy understanding must come to nought,
for he that believeth is justified from all things, and comes not into condemnation,
and he hath the witness in himself.
And that lets him see his redeemer, his mediator, and saviour, the light, which,
walking in, he is cleansed from all sin, and so no mystery of iniquity,
for the mystery of iniquity is out of the light:
none sees justification and redemption but with the light within,
which comes from Christ who hath enlightened him.

[.discourse-part]
_Principle._ He saith,
'`The ministration of grace cannot he known by the light which Christ
hath enlightened every man that cometh into the world withal,`' etc.
See page 14.

[.discourse-part]
_Answer._ Contrary to John, who saith, '`As many as receiveth him,
to them he gives power to become the sons of God;`'
and no one knows the ministration of grace,
but by the light which comes from Christ the covenant of grace.

[.discourse-part]
_Principle._ He saith, '`None can know the mystery of God in Christ with the light in them,`' etc.
See page 14.

[.discourse-part]
_Answer._ Which is contrary to scripture, '`I will give him for a covenant,
for a light to the Gentiles,
he shall be my salvation to the ends of the earth,`' saith the Lord.
So as this was the salvation, it gives the knowledge of the mystery of salvation;
the light that shines in the heart gives the light of the knowledge
of the glory of God in the face of Christ Jesus,`' who is the mystery
that shines in the heart of them that believe in it;
and them that do not, are condemned with the light.
And so they are reproved with the spirit of truth,
which leads the disciples into all truth, which spirit the world cannot receive,
for they do not receive the light, and so are not like to receive the spirit of truth.

[.discourse-part]
_Principle._ He saith, '`The light of Christ (in natural man) knows nothing of the spirit,`' etc.
And '`the scripture was the image of Christ without,`' etc.
See page 14.

[.discourse-part]
_Answer._ Scriptures without are writings, and endure not forever, but the power,
Christ the power of God, endures forever.
And whoever is in the light, cometh to know Christ in the spirit, him who is the life.
And it leads the natural man from his natural state, that believes in it;
for all by nature are the children of wrath: those who believe in it,
it leads from the nature, and from the wrath,
and these are made free from the wrath to come;
and they that believe not in the light are reproved by the spirit,
and that which reproves them is manifest to them, and so they know it.

[.discourse-part]
_Principle._ He saith,
'`To affirm the light in the conscience (which we say is
the light of Christ) to be the way or guide to Christ,
whereto only we should attend, is a darksome, fleshly,
and most legal principle,`' and calls it '`the grave wherein Christ is buried,`' etc.
See page 15.

[.discourse-part]
_Answer._ This is contrary to Christ`'s doctrine, who saith,
'`He that believes in the light shall not walk in darkness,
but have the light of life.`' And he that does believe in the light,
hath entered into his rest and come to the sabbath, out of the grave, out of the legal,
and out of the fleshly, and out of condemnation.
And none come to the son Christ, but they who come to the light which comes from him,
who hath enlightened them with it.

[.discourse-part]
_Principle._ And again he saith, '`To say the light in every man is Christ the redeemer,
is a two-fold error,`' etc.
See same page.

[.discourse-part]
_Answer._ Contrary to John, who saith,
'`This is the true light which doth enlighten every man
that cometh into the world.`' And '`he was in the world,
and the world knew him not.`' So he shows himself to be one of the stock of the world,
that know not him that was and is in them, the light of the world.
He that believeth in the light hath the light of life, and he that receiveth the light,
receiveth Christ the redeemer.
And he that receiveth Christ, receiveth his spirit.
And he that receiveth not the light that he is enlightened withal,
receiveth not his redeemer, but hates him: it is his condemnation,
and he is in the error.

[.discourse-part]
_Principle._ He saith, '`The light within was not given for righteousness,
neither could it reveal or give life,`' etc.
See page 16.

[.discourse-part]
_Answer._ Contrary to Christ, who saith,
'`He that believes in the light shall have the light of life.`'
So thou art unskilful in the word and doctrine of Christ;
and Christ within is given for righteousness; who reveals the Father and gives life,
and they that have not Christ the light within, are reprobates.

[.discourse-part]
_Principle._ He saith,
'`The light within knows nothing of the precious gospel mystery.`' See page 16.

[.discourse-part]
_Answer._ Contrary to the apostle,
who said the light that shined in their hearts should '`give the knowledge of the glory
of God in the face of Christ Jesus;`' and the light within comes from the mystery,
and is of the mystery itself,
and lets see the precious mystery which none knows but with the light within.
And so the God of the world hath blinded thy mind,
and thou hast showed thyself that thou art of them that hate the light,
and come not to it; for he that comes to it, comes to the mystery,
for the least light of Christ in man is of the mystery, and comes from the mystery.

[.discourse-part]
_Principle._ He saith, '`It is an error to say Christ came to redeem Israel from the law without,
to establish the work within and law in the conscience,
in obedience unto which men come to be redeemed,`' etc.
See page 16.

[.discourse-part]
_Answer._ Contrary to the apostle, who preached the redemption,
and established the law in the heart; and Christ is within,
who redeems men from under the law, who is the end of it;
and the word of faith is in the heart; and they that have not this are in the error,
though they may talk of Christ.

[.discourse-part]
_Principle._ He saith, '`It is the divinity of sophisters,
and a blotting out of the glory of the grace of Christ,
to set forth Christ as a lawgiver, and worker in us,`' etc.
See page 17.

[.discourse-part]
_Answer._ But I say, none know him as a mediator and a lawgiver, nor an offering,
nor his blood that cleanseth them, but as they know him working in them,
and their divinity is in the sophistry that know
not the glory of the grace of Christ working in them.

[.discourse-part]
_Principle._ He saith, '`A man shall not see himself dead and buried with Christ,
and raised up with Christ, by any work or obedience to Christ within,`' etc.
See page 18.

[.discourse-part]
_Answer._ He that believes hath the witness in himself; and there is the work within,
and that is the work of God: and faith is wrought within.
And this is contrary to self, for it gives victory over it, and teacheth to deny self.
So see how thou confounds thyself;
and '`he that believes is past from death to life,`' and '`they
that are dead with Christ seek those things that are from above.`'

[.discourse-part]
_Principle._ He saith again, '`The light within is the spirit of the world,`' etc.
See page 18.

[.discourse-part]
_Answer._ Contrary to John`'s doctrine, who saith, '`he was in the world,
and the world knew him not,`' neither do your worldly spirits know him now,
as the world`'s spirit knew him not then; and the world hates the light,
and darkness cannot comprehend it, though it shines in darkness.
And here thou art meddling with things that are too heavy for thee,
and the corner-stone falls atop of thee,
and the light that enlighteneth every one that cometh into the world,
was before the spirit of the world was.

[.discourse-part]
_Principle._ He saith, '`That they that affirm the light in every man that condemns for sin,
to be Christ the redeemer, have set up an idol,`' etc.
See page 19.

[.discourse-part]
_Answer._ Doth not Christ say, '`I am the light of the world,`' which is '`the true light,
that lighteth every man that cometh into the world,`' who
is the redeemer and the salvation to the ends of the earth?
And he that receiveth it receiveth Christ.
And is not this it that brings off from all idols?
And are not they setting up idols, that are from the light?
And doth not Christ the light come to condemn sin in the flesh?
And is that the idol?
How dare thou say so!
He was manifest in the flesh, to condemn sin in the flesh; and he saith,
'`I am the light,`' and that is not an idol.

[.discourse-part]
_Principle._ He saith, '`Christ comes not down in spirit into our persons to redeem,
but to manifest the redemption;`' and saith,
'`he cometh the second time without sin unto salvation,`' etc.
See page 21.

[.discourse-part]
_Answer._ The apostle bids them '`work out their salvation with
fear and trembling.`' And Christ brings not peace on earth,
but a sword, and judgment, and comes to make blind, who is the redemption,
and makes it manifest by his spirit, and whose light doth condemn him that hates it,
because he will not have that which manifests salvation.
And whosoever knoweth redemption, knoweth it to be manifest in him from Christ.

[.discourse-part]
_Principle._ He saith, '`They who had the light within, and pierced into the invisible things,
and eternal power and godhead, had but the wisdom of this world,`' etc. page 23.

[.discourse-part]
_Answer._ And so he would make the light of Christ the wisdom of this world;
which light cometh from Christ the wisdom of God.
The wisdom of the world, cannot pierce into the eternal power and godhead.

[.discourse-part]
_Principle._ He saith, '`The light within denies all things that God hath done for us in Christ,
which hath no glory, but spreads a veil over,`' etc. page 25.

[.discourse-part]
_Answer._ None know what God hath done for us, nor see the glory in Christ,
but by the light which comes from him, '`who works all both in us and for us,
according to his good will and pleasure,`' and brings not to deny what God worketh in us.
And they nullify it that are against his light, and are against his glorious person;
for the light that is within lets see his glory.

[.discourse-part]
_Principle._ He saith, '`Obedience to the light within is another atonement,
and a denying the atonement of Christ,`' and calls
it '`a mystery of iniquity.`' See page 23.

[.discourse-part]
_Answer._ None know the atonement of Christ but by the light within,
and all are in the mystery of iniquity that are out of the light which cometh from Christ,
the covenant of God to Jews and Gentiles;
and that '`gives them the light of the knowledge of the
glory of God in the face of Christ Jesus.`' Mark! he saith,
the light is that which gives the knowledge;
and the light within doth not set up another atonement;
but they that deny the light within set up another atonement than Christ.

[.discourse-part]
_Principle._ He saith, '`To obey the law within,`' (which we say is the law of the spirit of life,
which makes free from sin and death,) in this, he saith,
'`we agree with the Papists and Pagans.`' See page 30.

[.discourse-part]
_Answer._ Now in this thou mayst see where thou art, out of the apostles`' doctrine.
And neither thou, nor the Papists, nor Pagans own us in this,
that we should he made free from the law of sin and death while we are upon the earth.
And here the blood of Jesus is witnessed, and the atonement, and the Father and the son;
and this is all seen with the light within.

[.discourse-part]
_Principle._ He saith, '`he began by faith to behold the love, joy,
and redemption prepared for him, before any evil or good was done by him,`' etc. page 37.

[.discourse-part]
_Answer._ Dost not thou say, thou beheld it by faith?
And now is not the work good to behold by faith?
And doth not that give victory over the evil?
And doth not that do good that beholds by faith?
And so what is not of faith is sin.

[.discourse-part]
_Principle._ He saith, '`He is in heavenly places,
and yet in the shadow of death with the earthly.`' See page 38.

[.discourse-part]
_Answer._ He that is in heavenly places is in Christ Jesus, is a new creature:
and '`he that believeth in the light,
shall not abide in darkness;`' so comes out of shadows.
And he that believeth, abideth not in condemnation,
and so comes out of the shadow of death,
though they have sat in the shadow of death before belief, and comes out of the earth.
So thou hast proved thyself not a true believer, who comes out of the shadow and death.

[.discourse-part]
_Principle._ He saith, '`To purify the members, as reckoning it our redemption, our righteousness,
all such purity is sin, blindness, and idolatry,`' page 40.

[.discourse-part]
_Answer._ The apostle calls Christ our redemption, and our sanctification,
and our righteousness; and so we can truly say '`Christ is ours,`' and are no idolaters.
And they that cannot say Christ is their sanctification, redemption, righteousness,
and mortification, are in idolatry and sin.

[.discourse-part]
_Principle._ He saith, '`The way to attain the spirit of Christ,
is not by waiting on the light within,`' etc.
See page 52.

[.discourse-part]
_Answer._ Christ saith, '`Believe in the light,
that ye may he children of the light;`' and he that is a
child of the light cometh to the birth born of the spirit.
And Christ doth enlighten every one that cometh into the world;
and '`as many as received him,
he gave them power to become the sons of God.`' And none hear faith,
but who hear the light within, which is Christ within, who is the author of it,
by which the spirit is received.

[.discourse-part]
_Principle._ He saith, '`That doctrine or spirit that calls to the light within,
doth but build up the worship of the world,`' etc. page 53.

[.discourse-part]
_Answer._ Contrary to the apostle, who said,
the light that '`shined in their hearts`' would give them the light of
the knowledge of God in the face of Christ Jesus.`' And Christ saith,
'`they that worship God, must worship him in truth.`' And he is the light,
and he is the truth, that enlighteth every man that comes into the world,
and this throws down all the worship of the world.
And I say, none come out of the worships of the world, and the doctrines of the world,
but who come to the light wherewith Christ hath enlightened every man,
etc. that shines in the darkness, and the darkness comprehends it not.

[.discourse-part]
_Principle._ He saith, '`To believe in God as the light within men, redeeming from sin,
is to deny the witness of the son, and have neither son nor Father,`' etc. page 54.

[.discourse-part]
_Answer._ I say, none own the witness of the son,
but who own the light which comes from the son, with which they are enlightened;
nor none know the Father nor the son, nor receive them,
but who receive the light which Christ the son hath enlightened them withal,
nor know God to be a saviour but by the light within.

[.discourse-part]
_Principle._ He saith, '`They that seek for righteousness by obedience to the light within,
differ nothing from the Jews, but only in the copies of the law,`' etc.
See page 56.

[.discourse-part]
_Answer._ None see the obedience of Christ the second Adam, the end of the law,
and copies of it, but with the light within, which comes from Christ Jesus,
that brings in righteousness, and ends sin and transgression,
who is the end of the righteous law,
with which light man sees the weakness and unprofitableness of it,
and the types and the shadows of it, which Christ is known in the light within,
who ends it.

[.discourse-part]
_Principle._ He saith,
'`To rest in hope that I am saved from sin and wrath by the blood of Christ the head,
and while conscience condemns for sin, this is to hope against hope,`' etc.
See page 57.

[.discourse-part]
_Answer._ Such as are saved from the wrath by Christ the head, and his blood,
they are saved from their sins.
And then they that are saved from their sins, how can conscience condemn,
and the wrath come upon them for sin; and they that are saved from the wrath,
are saved from their sins.
But where conscience doth condemn for sin, there is, wrath;
and such cannot witness a cleansing, nor salvation wrought out,
nor a being saved from sin, but are in the false hope,
and not in the true hope which goes against hope, for the true hope is Christ within.

[.discourse-part]
_Principle._ Thou speaks of Christ`'s working and giving an example,`' etc. page 67.

[.discourse-part]
_Answer._ Yet thou and the rest are offended at those people that are called Quakers,
who say Christ was their example.
And so ye can allow what ye speak yourselves; but if another speak the same words,
it is an offence to you.

[.discourse-part]
_Principle._
He saith, '`Such as preach redemption by the light in every man, are not of God,`' etc.
See page 70.

[.discourse-part]
_Answer._ The redemption is of Christ the light,
that doth enlighten every man that cometh into the world;
and every man that cometh into the world that seeth his redemption, it is by the light,
which he that doth enlighten every man that cometh
into the world hath enlightened him with,
which is Christ the redeemer, the saviour, the second Adam, the way to the Father,
who shall make every tongue to confess him to the glory of God;
but thou that hatest the light art condemned.

[.discourse-part]
_Principle._ He saith, '`Not the light in every man, but the words of the prophets and apostles,
is that which leads to the Lord Jesus,`' etc.
See page 82.

[.discourse-part]
_Answer._ Many may have the words of the prophets and apostles,
but none come to that which leads to the Lord Jesus,
but who come into the light and life that the prophets and apostles were in,
which Christ Jesus is the end of,
'`who doth enlighten every man that cometh into the world.`' Therefore every man that
cometh into the world must come to the light which Christ hath enlightened him withal,
before he come to the end of the prophets and the apostles, Christ Jesus,
the Lord of life and glory.

[.discourse-part]
_Principle._ He saith, '`The scriptures are the image of Christ;
and he that seeks for God out of the humanity of Christ,
he shall lose both God and himself,`' etc.
See page S2.

[.discourse-part]
_Answer._ The scriptures are writings, and the writings will not endure forever;
and the image of Christ is the image of God.
And all who are in the life that gave forth scriptures, are in the image of Christ,
which was before scripture was;
and all that have the scriptures out of the life that gave them forth,
they have not the image.
And he that is out of the truth may have the scriptures; but all are out of the image,
who are out of the truth; but who are, in the truth, are in the image.
And '`God was in Christ, reconciling the world unto himself.`' And '`who knows the son,
knows the Father.`' And he that hath found the son, hath found the Father also.
And he that seeks after God out of Christ, shall never find him.

And as for the rest of thy lies and slanders in thy book, and unsavoury expressions,
which are not worthy of mentioning, upon thy own head they will come one day,
and thy words shall be thy burden.
