[#ch-20.style-blurb, short="Innocency Above Impudency"]
== Jeremiah Ives`' book, called [.book-title]#Innocency Above Impudency, Or the Strength of Righteousness Exalted Above the Quaker`' Weakness and Wickedness.# His principles follow.

[.discourse-part]
P+++.+++ He saith,
'`It is a rare thing to see any of the seed of the
devil grown up to that degree of impudence,
to charge a man, that he hath done that which he never did do,`' etc.

[.discourse-part]
A+++.+++ The seed of the devil always said that which was not true,
so not a rare thing to find them; for the devil and his seed are out of the truth,
and when he speaks a lie, he speaks of himself, and so speaks a thing that is not,
and there thou art.

[.discourse-part]
P+++.+++ He saith, '`The apostle in his catalogue of the evils of the times,`' etc.
Page 1.

[.discourse-part]
A+++.+++ Is it not better to call the scripture a declaration,
(as they call themselves,) than to call them a catalogue?
And some of you will say it is a history, and some a catalogue; and again ye will say,
it is the word of God, whereas the scriptures of truth are words, and God is the Word;
and thou art in the evil time, out of the good, and thy time and day are evil.

[.discourse-part]
P+++.+++ He saith, '`The Quakers give that name (as quaking,) to themselves,
and others do not give it them as a nick name,`' etc.
See page 2.

[.discourse-part]
A+++.+++ The first that ever I heard them called Quakers, and that name given to them,
was by one Gervase Bennet in Darby, a persecutor, called a justice of peace:
though many years before the power of the Lord was witnessed,
yet I never heard them have that name of Quakers given,
before that corrupt justice gave it them, and misnamed them so,
and in scorn called them so, and thou art one of his scholars.
But quaking and trembling we own, though they in scorn call us so;
and the salvation wrought out with fear and trembling we witness.

[.discourse-part]
P+++.+++ He saith, '`The devil speaks truth sometimes,`' etc.
Page 2.

[.discourse-part]
A+++.+++ Christ saith, '`He was a liar from the beginning; and when he speaks a lie,
he speaks of himself,`' and hath no truth in him;
and so he cannot speak truth as it is in him.
And the greatest professors upon the earth are in the situation
of the devil that speaketh the words of truth,
but not as being in it, as Christ said to the Jews,
'`they were of their father the devil,`' they spoke of themselves.
So they that speak the scriptures but not by the
spirit that they did that spake them forth,
they speak of themselves, as the devil doth that abode not in the truth,
'`but was a liar from the beginning.`' And thus the truth comprehended it.
For it is one thing to speak the truth in the truth, and to be in it,
(for he speaks not of himself,
but the truth in him;) but it is another thing to speak of themselves,
and there thou art.

[.discourse-part]
P+++.+++ He chargeth us,
'`whether ever any gave worse words to us than we did to others,`' etc. page 9.

[.discourse-part]
A+++.+++ To speak truth is not to give bad words, to tell a Cain, he is a Cain, an Esau,
he is an Esau, an Ishmael, he is an Ishmael, or a wolf, he is a wolf;
and to tell evil beasts they are evil beasts, that are worse than the common beasts.
And to say, the greedy dogs that can never have enough,
are worse than the common dogs that are biting and tearing;
and are worse than the common beasts that feed in peace, and eat their meat in peace.
Now to speak such words and names as these to them that are not so, is to give bad names,
and wrong names.
But the spirit that gave forth the scriptures,
gave such names to such as were found in those steps.
It gives to see now, and the whole nation may witness,
that Friends may answer to his challenge;
the jails and courts show the greediness of such, and their persecution,
and their malice against the lambs;
and so the saints in the spirit give them their proper names,
according to their properties, among which names thou art found.

[.discourse-part]
P+++.+++ He saith,
'`Much of the scriptures may be understood without the spirit,`' etc. page 12.

[.discourse-part]
A+++.+++ The scriptures were given forth from the spirit of God,
and they are the things of God, and the words of God,
and they are not known nor understood, but by the spirit of God,
for there is a spiritual understanding.
Neither can they understand any of the scripture of truth which cannot be broken,
but by the spirit of God within that gave them forth,
which is of God of whom they were learned.

[.discourse-part]
P+++.+++ He saith, '`Christ was not a minister of the circumcision,`' etc.
See page 14.

[.discourse-part]
A+++.+++ The apostle said, they were '`circumcised with a circumcision made without hands,
in putting off the body of the sins of the flesh;`' they were circumcised with the spirit.
But who was the minister of this circumcision?
For the apostle saith, it was the circumcision of Christ. Col. 2:11.
And again the apostle said, '`We are the circumcision,
that worship God in spirit, and have no confidence in the flesh.`'

[.discourse-part]
P+++.+++ He saith,
'`What man in his right wits would say a wilderness was a city,`' etc. page 14.

[.discourse-part]
A+++.+++ When the people have transgressed the law of God, they are erred from his ways,
they are become a wilderness, and bear the fruit of brambles and briars,
not seeing any way to get out, till the Lord`'s mercy be manifested to them;
which is further than the law of justice.
And thou hast not seen thy wits`' end yet, nor seen the wilderness in thy heart fenced,
though a city; and the children of Israel were called a wilderness, in transgression,
though in cities.

[.discourse-part]
P+++.+++ He saith,
'`he can tell things to come without the spirit of God.`' And that
the Pharisees could tell by the skies what should be the weather,
and what the days should bring forth, and this without the spirit of God,`' etc. page 15.

[.discourse-part]
A+++.+++ That which gives to understand the creation,
and the altering and changing of the creation, either in weather or days,
is the wisdom of God; and his spirit, by which all things were made,
knows these things in the truth; who counts the stars, and numbers them in their kind;
who '`sets the sun to rule the day,
and the moon to rule the night.`' Now who understands these things aright,
it is by the spirit of wisdom; and there may be a wilful rejecting,
and a having these things in the form, yet not a knowing them in truth,
and so Christ calls these hypocrites.
And a man may know things by the spirit, and go into error from the spirit,
and then hold them in his memory.

[.discourse-part]
P+++.+++ He saith,
'`Every man that cometh into the world hath not
the light of Christ in him,`' etc. page 16.

[.discourse-part]
A+++.+++ '`This is the true light that doth enlighten every man that
cometh into the world;`' and it
'`shines in the darkness, and the darkness comprehends it not.`'
Now this light reproves where it is come to;
where men hate it because their deeds are evil, it is their condemnation.
And so, is not that which reproves them, in them; which makes manifest the heart?
and are not those that quench the spirit, the wicked?
and those that are led by the spirit, are not those the good?
And are not here both good and bad?
Thou art that darkness that John speaks of,
that cannot comprehend the light which shines in darkness, like the Pharisees.

[.discourse-part]
P+++.+++ He saith, '`There may be a light to convince people of sin, and yet not within them.`'

[.discourse-part]
A+++.+++ There is no people convinced of sin, but they are convinced within themselves,
and with the light within them;
and it is the light that makes manifest to a man when he is convinced:
it answers to something, and reaches to something in their particulars,
though the words be spoken without them from the light.

[.discourse-part]
P+++.+++ '`That every man in the world should not have his sins pardoned,`' etc. page 17.

[.discourse-part]
A+++.+++ Christ gave himself, his body, for the life of the world;
he was the offering for the sins of the whole world, and paid the debt,
and made satisfaction, and doth '`enlighten every man that comes into the world,
that all through him might believe;`' and he that
doth not believe in the offering is condemned already.

[.discourse-part]
P+++.+++ He saith, '`It is an error to say that every man hath a light within him,
to teach him to worship God,`' etc. page 18.

[.discourse-part]
A+++.+++ Every man that cometh into the world has a light from Christ Jesus the truth;
being in the light which Christ Jesus the truth hath enlightened him withal,
and walking in it, he shall worship God aright in the truth,
and come into that the devil is out of, and worship God in the spirit.
But none worship God aright but they who are in the light which
Christ hath enlightened every man with that cometh into the world;
for who is in the light, is in the truth, for it is truth;
and all other worships out of the light are as the devil is, and there thou art,
condemned with the light.

[.discourse-part]
P+++.+++ He saith, '`that the error he charged us with, is,
to say that the light which doth enlighten every man that cometh into the world,
is within every man,`' etc. page 19.

[.discourse-part]
A+++.+++ In which he shows his ignorance of the scriptures:
'`I will give him for a covenant of light to the Gentiles,`' a leader unto them;
'`and a new covenant to the house of Israel and Judah,`'
and this covenant was written in their hearts.
And as I said before, the light shines in darkness, and the darkness comprehends it not:
and where the light shines out of darkness, it shines in the heart.
He that hates the light is enlightened, and he that loves it;
and it reproves the evil deeds of him that hates it.

[.discourse-part]
P+++.+++ He saith,
'`It is miserable darkness to direct people to the light within them,`' etc. page 26.

[.discourse-part]
A+++.+++ Which was the apostle`'s doctrine;
he was sent to turn people from the darkness to the light.
And he told people,
that '`the light that shined in their hearts would give them the
light of the knowledge of the glory of God in the face of Christ
Jesus!`' And Christ bade them '`walk in the light,
and believe in it:`' and they are in miserable darkness that do not.

[.discourse-part]
P+++.+++ He saith, '`It is a known error, to say, that a man was in hell, and in heaven,`' etc.
See page 21.

[.discourse-part]
A+++.+++ In this he shows his ignorance of scripture;
for it gives testimony of men that witnessed that they had been in hell,
in the nethermost hell; and witnessed again they were in heaven,
and '`sat in heavenly places in Christ Jesus;`' and such
were in heaven as are spoken of in the Revelations.

[.discourse-part]
P+++.+++ '`It is an error to say they have perfection, and they themselves not perfect, etc.
And to say they have communion with the body and blood of
Christ at the Gentiles`' table,`' etc. page 23.

[.discourse-part]
A+++.+++ There are many of the servants and children of God,
whose meat and drink are the body and blood of Christ,
who come among the Gentiles and their tables, to witness against them;
yet nevertheless they have communion with the body and blood of Christ.
And many may witness Christ the perfection, in words, though they are not in it,
as the whole world do; yet who are in Christ, are in the spirit, and are perfect.
So that it is one thing to be in the thing, and another thing to have sight of the thing,
and another thing to profess the thing without the sight.
Yet I say, the sight that seeth Christ is perfect, and sees perfection;
and the faith is perfect, whereby he cometh to the knowledge of the son of God,
and to the measure of the stature of the fulness of Christ.

[.discourse-part]
P+++.+++ He saith, '`The writings of the scriptures may be burned,
but the word of God contained in them cannot be burned,`' etc. page 34.

[.discourse-part]
A+++.+++ If he had said, the word that it speaks of, or testifies of, he had spoken properly,
like scripture: but to say the word is contained in the writing,
while the writing saith it testifies of Christ the word, is not to speak properly.
And here is a proof to thee, that the Quakers are sent of God,
who speak to thee of the scriptures rightly, as they are.

[.discourse-part]
P+++.+++ He saith, '`It is a lie, to say every man hath the light of Christ,`' etc. page 44.

[.discourse-part]
A+++.+++ Contrary to John, who saith,
'`Every man that cometh into the world is enlightened.`' And '`as many as receiveth him,
to them he gives power to become the sons of God?`' And '`he that believes in the light,
shall not abide in darkness, but shall have the light of life,`' and so it is sufficient.
And he that doth not believe, is condemned already;`' and he hath it to believe in,
or to condemn him.

[.discourse-part]
P+++.+++ He saith, '`Thousands stumble because they have no light in them,`' etc. page 44.

[.discourse-part]
A+++.+++ They are such as hate it, and do not receive it which hath enlightened them,
and not walking in it, it is their condemnation; and it shineth in the darkness,
and the darkness comprehends it not: and so they are in darkness,
and here is the unregenerate state.

[.discourse-part]
P+++.+++ He saith,
'`The Pharisees were far enough from having the kingdom of heaven within,`' etc. page 45.

[.discourse-part]
A+++.+++ Contrary to Christ`'s words, who said, it was within them.

[.discourse-part]
P+++.+++ He saith, '`It is a notion to say, the light of Christ is in every one,`' etc. page 47.

[.discourse-part]
A+++.+++ Which is contrary to John`'s doctrine.
It is not a strange thing to the saints for these priests and teachers to question
the light that doth enlighten every man that cometh into the world;
for the Jews, priests, and Levites stumbled at it in the days of John,
and it set them all in an uproar as it does you; and they examined and questioned John,
and he said, '`This is the true light that lighteth every man that cometh into the world,
that all men through him might believe.`'

[.discourse-part]
P+++.+++ He saith, '`None were ever baptized into the name of the Father, son, and holy ghost,
that were not baptized with water,`' etc.
See page 52.

[.discourse-part]
A+++.+++ Where was Matthew, or Mark, or Luke, or John baptized?
and many more whom the apostle said, he thanked God he had not baptized,
etc. although he had begotten many?
Baptizing is making disciples to the Lord Jesus, and baptizing them into his name,
that is, his power.
And he told the saints they were baptized with one spirit, into one body,
and said that he thanked God he had baptized but a few: +++[+++viz. with water.]
But he told of the spirit`'s baptism,
and brought the saints off from things that were seen; and water is seen and its baptism.
And as for all thy rabble from thy contentious spirit, and thy railings,
and unsavoury expressions, they will turn home upon thyself;
and thy own words will be thy burden;
and the witness in thy conscience will answer in the day of thy judgment.
