[#ch-21.style-blurb, short="Queries to the Quakers"]
== Francis Harris`' book, called '`Queries To the Quakers,`' etc. His principles follow.

[.discourse-part]
P+++.+++ Thou sayst, '`Do not these people that pretend to the light,
stumble at noon day as in the night, and there is no gospel light,
we mean of the revealed and written gospel light, in them?`' etc.
See page 9.

[.discourse-part]
A+++.+++ The gospel light is that which doth enlighten every man that cometh into the world:
and they who hate it neglect the gospel light,
and receive not the power from God which is the gospel;
for the gospel light is Christ Jesus,
that doth enlighten every man that cometh into the world.
And they that walk in this light stumble not; they stumble that are out of the light,
which light is the way to the Father.
And many may have the written words, yet be out of the gospel light,
and the power of God which is the gospel, (as Rom.
1.) which brings people where the sheep lie down at noon day.

[.discourse-part]
P+++.+++ He saith, '`What did Christ mean when he bid people search the scriptures,
or Peter when he called the scriptures the sure word of prophecy,
the light shining in the dark place?
And yet scripture without is a dead letter,`' etc.
See page 12.

[.discourse-part]
A+++.+++ And yet they call it the light, and the word,
which is '`a dead letter.`' Christ bids the professors of scripture to search it,
that thought to have had life in it, not that they should find life in it,
but that they should search it, and see how it testified of him who was the life;
that was his end.
And those that were come to Christ the life,
were come to him the scriptures testified of, as John 1:
'`We have found him of whom Moses and the prophets wrote.`'
And those were they that were come from John;
the others were they that stuck in John, and came not to the life,
but went to the scriptures to have had life in the scriptures,
and came not to him the scriptures testified of, but persecuted him.
And Peter means as he speaks;
he tells them of the '`sure word of prophecy,`' and bids them take heed to it,
'`as unto a light that shines in a dark place, until the day dawn,
and the day star arise in their hearts.`' He doth not say,
'`this is the scriptures without;`' which thou sayst,
are '`a dead letter.`' How can that which is dead, shine?

[.discourse-part]
P+++.+++ He saith, '`Doth not this draw people to gross idolatry;
to bid people take heed to the light in you, which you call the pure light of God;
not the light of nature?
And whether you do not delude people,
by saying there is a pure light of God and Christ
in every man and woman by nature,`' etc.
See page 14. 17.

[.discourse-part]
A+++.+++ The light which enlightens every man, etc. leads from all idolatry:
for all that are out of the light, that enlightens every man that comes into the world,
are in the idolatry.
And every man that comes into the light which he is enlightened with,
is in that which was before any natural lights were: and the natural lights are the sun,
the moon, and the stars.
And they delude and deceive people that say,
the light which enlighteneth every man that cometh into the world is a natural light,
and they keep people in idolatry; and so shut up the kingdom against men,
and go not in themselves, nor suffer others; for all idolatry is out of the light.

[.discourse-part]
P+++.+++ He saith, '`To be carried up to the power, and to the spirit which resembles fire,
whether this be not antichrist like a Lamb;
to call fire from heaven to come down in the sight of men?
And whether the power be from God or from Satan,
that brings people into a trembling and shaking like Belshazzar,`' etc.
See page 20, 21.

[.discourse-part]
A+++.+++ That power was not of Satan that broke down the head of gold and the breasts of silver,
neither was that power of Satan that made Belshazzar to shake and quake:
and that power all must know, before the Most High rules in the kingdoms of men.
And to be carried up by the power and spirit of God, is not antichrist,
nor is as the beast which, with his lying wonders, caused fire to come down from heaven,
for the power, the spirit of God fathoms all such things;
and saw those were the spirits that were erred from the apostles,
and the life they lived in, that did so.

[.discourse-part]
P+++.+++ He saith, '`The most righteous man falls seven times a day,
the scripture tells us.`' See page 22.

[.discourse-part]
A+++.+++ The scripture doth not speak any such thing as '`seven times a day,`' but it saith,
'`the just man falleth seven times, and riseth again,
but the wicked fall into mischief.`'

[.discourse-part]
P+++.+++ He saith,
'`such as have fasted till their neighbours who lived nigh them have not known them;
they have been as though they had been come out of the jaws of death:
whether this be not as the Pharisees, and an occasion to Satan?`' etc.
See page 24.

[.discourse-part]
A+++.+++ What would ye have said to David in his days,
when he fasted till he might number his bones,
and was a stranger to all his acquaintance?
was this as hypocrites fast?
And because some now, by the same power, are moved of the Lord so to do,
is this like the Pharisees that appear to do so?
Have not all ministers and teachers showed their ignorance of the scriptures,
and the life that gave them forth, and to be such as cannot divide the word aright,
nor speak a word in season?
But they are rather such as burden and oppress the just, whereby the poor groan and cry;
not distinguishing between the fasting of the servants of God,
and those that appeared to fast.
So in this you show that you put no difference between the precious and the vile,
and are not able to judge of things that differ;
so are judged with that which doth put a difference in things that differ.
And David was a wonder to his neighbours.
