[.style-blurb, short="The Religion of the Northern Quakers"]
== Francis Higginson`'s book, called [.book-title]#A Brief Relation Of the Religion Of the Northern Quakers.# His principles follow.

[.discourse-part]
_Principle._ He saith in his epistle,
'`The great number that are fallen away from the word of God.`'

[.discourse-part]
_Answer._ The falling away from the word of God was before the apostles`' decease,
and the world is since gone after you and them that are fallen away;
and so you put the letter for the word, the scriptures which are words,
and so run into all opinions and sects.
But now are people coming to the light, and so to the word Christ Jesus,
him by whom the world was made; from you apostates, to the word and the apostles,
are we come.

[.discourse-part]
_Principle._ Again he saith, '`I do not detest Popery itself more heartily than I do your religion,
Quakers,`' etc.

[.discourse-part]
_Answer._ I do believe thee, for Popery itself is thy stock: the tithes, the universities,
the steeple-houses, mass-houses.
So I know thou must be a friend to Popery, and detest us before thou canst Popery;
the kingdom would otherwise be divided against itself,
and then it were not like to stand.
But Popery and you have come up in the apostacy since the days of the apostles,
and so with the power of God ye are denied.

[.discourse-part]
_Principle._ He again saith, '`Beware of false prophets; for there shall arise false prophets,
and false Christs, and if it were possible, they should deceive the very elect.`'
Matt. 7. and Matt. 24.

[.discourse-part]
_Answer._ Christ said they should come,
and that they should be '`inwardly ravening wolves,`'
but would be clothed with the sheep`'s clothing;
he told his disciples this,
and before the disciples`' decease they saw that they were come,
the false prophets and the antichrists, as in 1 John 2:4. which went from them.
And in the Revelations he saith,
'`all the world went after them:`' all
'`the world wandered after the beast,`' and the false prophets.
And the beast had power over all nations, and kindreds, and tongues, and peoples.
And the beast and false prophet made war against the saints, and overcame them.
And so you false prophets and antichrists have had the sheep`'s clothing,
but have been the wolves, ravening and devouring the lambs.
Ye could not have deceived, if ye had not had the sheep`'s clothing upon you:
and so the beast hath his names, which hath had power over all nations, kindreds,
and tongues.
So the beast and whore have been upon your tongues,
(which makes you orthodox men,) which John calls waters:
here have been the beast and his names, who have had power over all nations.
And all nations have drunk of the cup of the mother of harlots, the great whore;
the inhabitants of the earth are drunk with the wine of her fornication;
and the kings of the earth have committed fornication with her;
and she sits upon the waters, and the waters are peoples, and tongues, and nations,
and multitudes.
You have told the poor people long, that the false prophets are but now come,
and the antichrists are but now come, and bid them come to Matt. 7. and Matt. 24.
and so have showed your ignorance of the scriptures,
which say they were before the apostles`' decease, as in the first epistle of John;
they went forth from the apostles; these were the false prophets, antichrists,
and false spirits, which Christ said should come,
and the world since has gone after them.
Now doth your ignorance of the scriptures appear,
and that your are not men able to divide the word aright.
The discerning now is risen among people,
that they begin to see and know who divides the word aright.
And to bid people go to Matt. 7. and Matt. 24.
and say false prophets should come, all this hath been but for pretence.
Now we see you to be one with those John spoke of when he said, '`they were come,
and all that dwelt upon the earth went after them.`' Ye have had the form of godliness,
but the power hath been denied; and so you have burst into names, and heaps, and sects.
But now are the vials, and thunders, and plagues, and trumpets sounding and going forth,
and the seven woes going out: and now are the kings of the earth, and false prophets,
and antichrists, and the mother of harlots, and the beast, and his names and horns,
gathering together, with the old deceiver the devil, to battle against the.
Lamb, and the saints of the Lamb.
But the Lamb and the saints have got the victory,
and the rivers of living waters are opening to all that thirst.
Sing and rejoice, let us give glory to God, for now is the marriage of the Lamb come.

[.discourse-part]
_Principle._ Again thou makes a great pudder,
'`that any one should witness he is equal with God,`' etc. page 2.

[.discourse-part]
_Answer._ In a catechism of the assembly of the priests
(called divines) which they put forth to the nation,
they have laid down, (for young children,
and old men and all to learn,) '`that the holy ghost and the son are equal in power
and glory with the Father.`' Yet if any come to witness the son revealed in them,
or come to witness the holy ghost in them, as they that gave forth scriptures;
or witness the mind of Christ, and witness that which is equal with the Father,
that equality which you speak of,
you priests destroy that which you have put forth to the nation,
and cry out '`horrid blasphemy.`' And this ye confound that which you have set up,
and kill that which ye have begotten.

[.discourse-part]
_Principle._ He saith, '`I shall mention their errors.

[.numbered-group]
====

[.numbered]
1+++.+++ They hold their speakings are a declaration of the word Christ in them.

[.numbered]
2+++.+++ That the letter of scripture is carnal.

[.numbered]
3+++.+++ That Jesus Christ is come in their flesh, that he is in them as man.

[.numbered]
4+++.+++ And that the scriptures are not the written word of God.

[.numbered]
5+++.+++ That the soil is a part of God, or a divine essence.

[.numbered]
6+++.+++ That they enjoy God here, and Christ here.

[.numbered]
7+++.+++ And attain to a state of perfection.

[.numbered]
8+++.+++ That sprinkling of infants is a mark of the beast.

[.numbered]
9+++.+++ And our church, and worship, and temple, are idols`' temples, and beast-houses.

[.numbered]
10+++.+++ And not to be called of men master.

[.numbered]
11+++.+++ And the not speaking to a single person in the plural number,`' etc.

====

These he calls errors.

[.discourse-part]
_Answer._ All your temples set up (imitating the temple
Solomon built) since the days of the apostles,
are idols, for God never commanded them.
And have not the Papists had them?
And have they not been mass-houses, and beast-houses, and are they not such?
Is God worshipped in temples made with hands?
Is not he worshipped in the spirit and in the truth?
And the scriptures are words of the prophets, and apostles, and Christ; they are words,
and so called in the scripture; they are not called the written word, but words,
and Christ, the word, cometh to fulfill them.
And all you that do not speak from Christ the word in you,
if your declaration be not from it, you are the spirits gone out into the world,
apostatized from the spirit that was in the prophets, Christ, and the apostles.
The letter is written in paper and ink.
Now paper and ink are not spiritual, but that which it speaks of is spiritual.
And '`thou`' to one, and '`you`' to one,
makes it appear that neither thou nor you ever learned your accidence yet,
neither are perfect in the bible:
for neither the bible nor accidence teacheth to speak
any such language as '`you`' to a particular.
Therefore, ye are pitiful men to go to instruct the nations, and cannot endure sound,
righteous words, nor simplicity of speech, but stumble at it.
And again, '`God will dwell in you,
and walk in you,`' and '`your bodies are temples of the holy ghost.`'
And '`Christ is in you except you be reprobates,`' saith the apostle.
And again, God breathed into man the breath of life,
and he became a living soul.`' For that which came
out from God was the cause that man became alive,
a living soul, and is not this of God?
And God hath all souls in his hand, and Christ is the bishop of the soul;
and is not that of God which comes out from God?
Is not that of his being (who hath the soul in his hand) and so divine?
And is not Christ in man?
And doth not Christ say they must eat his flesh?
And how can any eat Christ`'s flesh, if his flesh be not in them.
And doth not the scripture say, that he was manifest in the apostles`' flesh?
And how can ye call him Christ in man, without the man be there?
And as for sprinkling infants, it is a thing which the scripture doth not hold forth,
but has been got up since the days of the apostles, it is not witnessed by scripture,
but is a tradition of men, an invention of men;
and then all may see if it be not a mark of that
beastly spirit that is erred front the apostles,
and out of the power!
And Christ saith, '`Be not ye called of men master; for ye have one master, even Christ,
and ye are all brethren.`' So thou and you that oppose the commands of Christ,
and teach men to practice the contrary, are antichrists,
and show yourselves in the spirit of error, from Christ`'s spirit.
Now let all read and see if this man divides the word aright to people?

[.discourse-part]
_Principle._ He saith, '`They have an unction, need not that any man teach them,
and wait for the spirit to come down upon them, by inspiration,
and give them utterance.`' And saith, '`they sit silent, and not a whisper among them.
And they do not own David`'s psalms to be sung.`' See page 12, 13, these are errors,
saith he.

[.discourse-part]
_Answer._ Is it not the apostle`'s doctrine,
that they need no man to teach them but as the same
anointing teacheth them that abide in it?
And were not they seducers that drew people from it?
1 John 2. And did not the apostles wait for the receiving the holy ghost, the comforter,
the spirit of truth?
And did not the holy men of God speak as they were moved by the holy ghost?
and so the gospel and the things of God, were revealed to them.
What they had heard, and seen, and had revealed to them,
they spoke as the spirit gave them utterance; and prayed for a door of utterance;
and others were to pray that they might have a door of utterance given to them,
when they were to preach.
And to sing David`'s psalms without David`'s spirit,
is not to sing with the understanding.
Now, in all these things,
have ye not showed and made manifest that your spirits
are the false spirits gone out into the world,
from the apostles`' spirit,
and the holy men`'s spirit that spoke forth the scriptures as they were moved,
and waited for the spirit, which led them into all truth,
and revealed to them the things of God?
So you that are out of this revelation, and preach against this,
you have preached up your spirits, out from the apostles;
and declared your folly to all the nation.
And then because they '`wait in silence,
and not a whisper among them;`' is not that agreeable to the apostles`' doctrine,
and the prophets`'? Is there not a '`learning in silence?`'
And was not whispering forbidden by the apostle?
And do such things as these offend thee?
Thou hast showed thy spirit.

[.discourse-part]
_Principle._ He saith, '`They meet in the night, and make the object of their teaching,
ministers and tithes; and the pure light that is in every man that cometh into the world.
And for any man to know what is in another, by looking at him, or upon him,
or discern his soul,`' this he suspects '`to be an
evil eye.`' And '`that the learned men,
and ministers, and physicians are in the power of Satan,`' etc. pages 16-18.

[.discourse-part]
_Answer._ Here again ye have made manifest your power, who are gone forth from the apostles,
into the mystery of iniquity, which hath long wrought since their days.
But now is the power of God made manifest, which breaks down the mystery of iniquity,
and raiseth up the mystery of godliness; and of this power, neither the learned men,
physicians, nor ministers, are able to judge, but as they own Christ the power of God.
As the learned Rabbi`'s judged of Christ, so do they judge of the power now;
so it is not strange to us.
And '`the saints met in the night,
yea till midnight.`' And we deny the ministry that takes tithes,
and say the priesthood is changed, and the law is changed by which it was made;
and the commandment disannuled that gave tithes.
Heb. 7. And we say Christ is come a priest after the order of Melchisedeck,
the similitude and likeness, who ends the similitude and likeness.
In Christ is the end of similitudes and likenesses, and of wars, in whom is peace.
So no tithes are to be paid to the similitude and likeness.
But all are to come to the son, and to hear the son, and honour the son.
'`I will give him for a covenant of light unto the Gentiles,
and a new covenant to the house of Israel and the house
of Judah.`' Christ told the Jews to whom he was promised,
that he was the light of the world; and the prophet said God would give him,
'`for a covenant of light unto the Gentiles.`' And Christ bid them
believe in the light,`' and they should have the light of life,
and should not walk in darkness.
And John saith, '`if ye walk in the light, then have ye fellowship one with another,
and the blood of the son of God cleanseth you from
all sin.`' So none come out of the darkness,
and out of the stumbling, and have peace with God, but who come to the light.
And art thou offended at this object?
Dost thou stumble at this light?
at the door, the rock, the corner-stone, splitting thyself against it?
But it is fallen upon thy head.

Again, the spiritual man discerns and judgeth all things.
And as face answers face, so doth the spirit of the Lord in man.
And man may discern by the spirit of the Lord God, where the seed is in the death,
and where the seed is not, and where the soul is living,
(in which the Lord hath pleasure,) and where it is in the death,
as the scriptures of truth testify.
The holy men of God discern it, and ye being ignorant of this,
manifest that ye have neither salt, nor savour, nor handling, nor tasting, nor seeing,
nor feeling.
But what ye know, ye know naturally as brute beasts; and so there is the evil eye,
not having spirits of discerning and savouring.
How should ye minister unto people, to their states and conditions,
if ye cannot discern the spirits which are in them?
How are ye ministers of the spirit?
The natural man, though he have all the natural tongues,
doth not receive the things of God, yet the natural man may get the letter:
and if he have not the spirit that gave it forth, he is not a minister of the spirit,
but of the letter, and is erred from the spirit that the apostles were in, as you are,
who have made yourselves manifest.

[.discourse-part]
_Principle._ He saith,
'`The Quakers will have no tools taken out of the shops
of human learning to work withal.`' See page 26. Again,
'`They call our ministers state`'s ministers, or priests;
and some of the Quakers go naked through the streets,`' etc.

[.discourse-part]
_Answer._ How ignorant art thou here of scripture!
Will not all people here judge thy ignorance, and your ignorance?
For the scripture shows that the Lord made his prophet Isaiah to put off his clothes,
and go naked among the Egyptians and Ethiopeans, for a sign to them,
a figure of their nakedness: and if the Lord has made some as figures among you,
or to go naked, as a figure of your nakedness, who are of the spiritual Egypt,
and of their root, and stock;
and of those false spirits that went out into the world from the apostles:
if the Lord make some as signs among you of your nakedness,
how you have ravened from the spirit of God, and want the clothing of it;
look upon your own shame that that may be covered.
Are they not innocent people that go naked among you, and that are an offence unto you,
who see not your shame?
And are not ye state`'s ministers, made by men, and schools,
and colleges set up by the state, are not your maintenance, your tithes from the state?
And ye say '`ye never heard the voice of God,
nor Christ`'s voice immediately from heaven?`' Whose ministers are ye then,
but state`'s ministers?
And ye deny immediate revelation, and inspiration.
How can we say ye are ministers made by the will of God,
when ye tell us ye never heard his voice?
Or how can we say you are ministers of Christ, while ye deny revelation and inspiration,
and immediate voice from heaven, and so know not the son and the spirit that reveals?
As for your '`tools that come out of your shops of human learning,`' the
Quakers deny your shops of tools that come out of the human learning.
And the scripture gives no such expressions as a '`shop of tools,`' nor do we
find that ever the prophets or apostles had a shop of tools of human learning.
But your shops of tools of human learning have come
up in the apostacy since the days of the apostles,
and these are your tools that you work with in the apostacy.
And so ye workmen will fall out with one another`'s work,
and with your tools strike at one another.
Ye have had a shop, that inwardly ravened, that went forth from the apostles,
the false spirits that went out into the world;
ye have had a shop of tools with which ye have worked, and lived in your old authors,
and books, and studies, and fathers; and so burst into many heads and heaps,
one destroying the other about his work!
All your tools ye have wrought with since the apostacy,
have been taken out of the shops of human learning, which are earthly;
this proves ye are apostates, and the spirits that are gone out into the world.
And Luke saith the tongues of Hebrew, Greek, and Latin,
were set up over Christ by Pilate who crucified him.
And John saith the beast had power over all tongues,
and that the whore sits upon the tongues, and that the tongues are waters.
What!
Hath the beast sat upon our tongues?
Upon our orthodox men, our schools, and colleges?
And doth the whore sit on our tongues, upon the original, and upon our tools and shops?
And are these set above Christ?
It is not unlike but that the beast may have power over all these.
The earth was of one language before they built Babel,
and when they imagined to build Babel, God confounded them into many languages.
But the life is risen, '`Christ Jesus, which was before Babel was,
and before Pilate was that set the many languages upon him;
the life is risen over them and you all, which life, Christ,
breaks to pieces both your shops and tools of human learning:
and so your glory is marred, and your pride is stained.
The life is risen, Christ the life is risen over you.
The merchants and the tradesmen rage, who have long had your shops.
Sing and rejoice over them, ye saints!

[.discourse-part]
_Principle._ He saith, '`The apostle said, the last times would be perilous,
there should be false accusers, and fierce.
despisers of them that are good.`' Again he saith,
'`a Turk or an Indian will deny the light within him.`' Again,
'`Christ is in heaven with his carnal body.`' See page 43, 45, 48.

[.discourse-part]
_Answer._ Christ`'s body is a glorified body, and the scripture nowhere says,
that Christ`'s body is a carnal body in heaven.

Again, the perilous times came before the apostles`' decease,
they saw them that were '`false accusers,
and fierce despisers of them that were good;`' they that
'`had the form of godliness, but denied the power,`'
that were '`lovers of themselves and covetous,`'
and these were crept in before the apostles`' decease;
and since the days of the apostles the world has gone after them.
So that covetous, heady, and fierce despisers have ruled;
they have been like Jannes and Jambres, who withstood Moses,
when the children of Israel were to come out of Egypt.
And so do you withstand the truth, who are covetous and high-minded, heady,
'`fierce despisers of them that are good, having a form of godliness,
but denying the power thereof,`' which are to be turned away from;
so you keep people in spiritual Egypt and Sodom.
Are ye not all covetous, and lovers of yourselves?
And do not you all deny the light '`that lighteth every man that cometh into the world,`'
'`Christ the power of God,`' and so keep people under your teaching all their life time,
laden with their sin and divers lusts while they are upon the earth,
telling them that there is no perfection here?
That ministry that tosseth people up and down with your slights, and wiles,
and windy doctrine, never makes them able to come to the knowledge of the truth;
which truth is the light that '`doth enlighten every man that cometh
into the world.`' Are not ye '`fierce despisers of them that are
good?`' Hath not all the blood of the martyrs and saints,
which hath been shed since the days of the apostles, been by the stock that you are in,
who are the false spirits,
erred from the true spirit that the prophets and apostles were in,
and gone out into the world from them?
And ye confess ye have not the same infallible spirit that the prophets, Christ,
and the apostles had: this Eaton the pastor admits.
But neither the Indians nor Turks will deny the light, that convinceth them of sin;
for to the Turks and Indians was the covenant promised, as well as to the Jews,
for they are heathen.
And thus your ignorance appears, both of the scriptures of truth and ministers of God,
and with them you are judged.

[.discourse-part]
_Principle._
Priest Coale saith, '`The light which he is justified by is a created light,`' page 56.

[.discourse-part]
_Answer._ Neither the scriptures of truth which the saints declared, nor Christ,
ever held forth a created light as justifying;
for the saints are justified by Christ the light, by whom all things were created.
That light was not created, that was the saints`' justification.

[.discourse-part]
_Principle._ He saith, '`Who are washed from their sins by the blood of Christ,
and made priests unto God; and in this sense,
if they themselves do not once become priests,
they will become companions of devils forever.`' See page 56.

[.discourse-part]
_Answer._ They that become priests to God, and are washed by the blood of Jesus Christ,
are come out of the devil`'s power and overcome him by the blood of the Lamb,
and own the light to be their justification, which thou denies.

[.discourse-part]
_Principle._ He tells us of '`Paul`'s mediate call,
and that his extraordinary call of itself had not been sufficient.`'

[.discourse-part]
_Answer._ The scripture tells us no such thing as Paul`'s mediate call;
and Paul declares himself a minister '`not of man, nor by man,
but by the will of God,`' and that was sufficient;
which call you are out of since his days, who are called by men.

[.discourse-part]
_Principle._ He saith, '`Christ doth not forbid simply to be called of men master,`' etc. page 62.

[.discourse-part]
_Answer._ It was Christ`'s command plainly to his disciples, '`Be not ye of men called master,
for ye have one master,
even Christ.`' And thus thou stands against Christ`'s doctrine and commands,
and so art a transgressor, and an antichrist.

[.discourse-part]
_Principle._ He saith, '`Christ`'s human nature,`' etc.

[.discourse-part]
_Answer._ Where doth the scripture speak of human?
Where is the word human written?
Tell us that we may search for it.
Now, we do not deny that Christ, according to the flesh, was of Abraham,
but deny the word human.
Christ`'s nature is not human, which is earthly, for that is the first Adam.

[.discourse-part]
_Principle._ Priest Coale saith, '`his justification is not done within him,
but without him in the court of heaven.`'

[.discourse-part]
_Answer._ Reprobates may talk of justification.
Did not Christ work justification without them upon the earth for mankind,
and brought righteousness?
And where Christ is made manifest within,
is not their justification wrought there from heaven, within?
Where faith is witnessed within, doth not that justify?
And none know justification in truth, but where it is wrought within.
See pages 77-78.

[.discourse-part]
_Principle._ Again priest Coale saith, '`the life that he lives is a created life.`'

[.discourse-part]
_Answer._ So thou hast showed thyself a natural, not a spiritual man,
nor a son of God led by the spirit of God, nor in the faith; and dost not live by faith,
nor in the spirit, so hast manifested vain glory.

[.discourse-part]
_Principle._ He calls '`trembling and quaking the shaking of the soul.`'

[.discourse-part]
_Answer._ The power of the Lord God cometh to shake down that nature which prisons the soul,
and set it free.
And as for all thy other complaints, revilings, railings, and lies,
they will turn upon thyself, and will be hard for thee to bear:
and thou shalt cry out with Cain, when thou feelest the burden;
who are out of Christ`'s steps,
who is '`the light that lighteth every man that cometh into
the world.`' As in the day of thy judgment thou shalt witness,
and the witness in thy conscience shall answer.
