[#ch-23.style-blurb, short="A True Relation of a Dispute"]
== Francis Fullwood`'s book, called [.book-title]#A True Relation Of a Dispute.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`The scriptures are able to make wise unto salvation.`' Again,
the son in whom eternal life is, is only found in scripture,
and they are they that testify of him,
and therefore eternal life is found in scripture.`'

[.discourse-part]
_Answer._ Many had the scriptures, but stood against the son of God.
Scriptures signify writings.
The son of God is not writings.
And many may have the scriptures, and not have the son of God, and so not eternal life.
For the devil hath scripture, but hath not eternal life;
'`For he that envyeth his brother,
hath not eternal life abiding in him.`' So who have eternal life,
they have that which the scripture speaks of, it testifies of Christ the life,
of the spirit; they are the words given forth by the spirit of God,
and so are to be fulfilled by the same spirit again.
And the scriptures '`are able to make wise unto salvation through
faith in Christ Jesus.`' For they were not wise unto salvation,
who had the scripture without the faith.

[.discourse-part]
_Principle._ He saith,
'`We attain our gospel another way than Paul did.`' And it is blasphemy
to tell us that what ye deliver is by revelation from heaven,`' etc.

[.discourse-part]
_Answer._ You, who are apostates from the apostles,
have received your gospel another way than Paul did, I do believe.
And is it not blasphemy for you to speak and preach
that which ye have not received from heaven?
and so you have brought yourselves under the curse,
and showed yourselves ministers of another gospel.
For whosoever receiveth the gospel,
which is called '`the power of God,`' it is immediate,
and by immediate revelation from God.
And so your gospel which is of men and after men, is another,
not the power of God received from God; for whosoever receiveth the gospel,
the power of God, must receive it immediately, for the power of God is immediate;
and that is the glad tidings to poor souls, that sets the soul free.

[.discourse-part]
_Principle._ He saith, '`We claim tithes not by the law of God, but by the law of the land,
and tithes seem to be Christ`'s wages,
and Melchisedeck still liveth to receive tithes in Christ,`' etc.

[.discourse-part]
_Answer._ Christ is come, and the everlasting priesthood;
he ends the commandment that gave tithes, and the priests that took them;
they end in him who is after the order of Melchisedeck that received tithes of Abraham,
of whom Christ came according to the flesh.
And Christ doth not any where give his disciples
an order to set up another law in the nations,
to give them tithes, the tithes of men`'s estates;
so you are none of the order of Melchisedeck,
but are of the order of them which Christ said should come, who are inwardly ravened,
which John saw were come, and went forth from them,
the false spirits that went forth into the world, into the earth;
and so ye have set up tithes, temples, schools, and priests by the pope`'s authority.
Had ye not your '`spiritual courts`' not long since?
And was not the pope the first author of your tithes?
And are not you of that order,
and far off from that spirit that leads after the order of Melchisedeck?
For none come to the priesthood after the order of Melchisedeck,
but who come to the spirit of Christ,
and these are '`kings and priests to God forever.`' So ye have received your tithes
after the order of that spirit that went forth from the apostles into the world,
into the earth, that has had the sheep`'s clothing, but ravened and devoured the lambs,
and worried the sheep, the ministers, prophets, and saints.
So all that are of the royal priesthood, after the order of Melchisedeck,
will see your order to be come of the pope`'s stock;
for the apostles and Christ did not set up tithes.

[.discourse-part]
_Principle._ He saith, '`Baptism comes in, in the room of circumcision,
and it is called the circumcision of Christ.`' Again he saith,
that '`thee and thou is a custom.
So if any man be contentious, we have no such custom in the church of God.`'

[.discourse-part]
_Answer._ Circumcision is no where said to be a type of sprinkling infants;
and sprinkling infants is no where said to be the circumcision of Christ.
But the circumcision without, was a type of the circumcision within;
and that the apostle witnessed the fulfilling of in the spirit,
and so denies the outward.
And the baptism of John was a type of that within.
And '`you`' to a particular, is your custom, and the scripture doth not declare to us,
that that custom was in the church of God.
But the apostle bid them '`keep to the form of sound words,
that could not be condemned.`' Now '`you`' to a particular is not a sound word,
as they can tell that have read but the bible or accidence.
And no heathenish customs come into the church of God, that will spot or wrinkle it,
nor does any thing come into it (that is the pillar
and ground of truth) that will be condemned.

[.discourse-part]
_Principle._ And he tells us of a word trinity: and saith,
'`The only ordinary way to know Jesus Christ, is outward revelation;
and to attain to the knowledge of Christ is, by the scriptures;
and that he may be a minister of Christ, though he be partly out of Christ`'s doctrine,
and though he be called of men master.`' He saith, '`The scripture tells us plainly,
that baptism is a christian`'s circumcision.`' Again, '`He that saith,
that light which is in every man is sufficient to discover and lead men to Christ,
is under the darkness of his own fancy, having so far left the true light,
the word of God.`'

[.discourse-part]
_Answer._ The light in every man, which Christ hath enlightened him withal,
loving it and walking in it, is sufficient to discover Christ and salvation;
and they that are out of that, are in the darkness and fancy.
And as for the word trinity, that comes from the old stock, the pope;
the scripture teacheth us no such word.
And none can know Christ by the scriptures; they testify of him,
but none can know Christ but by revelation.
Flesh and blood had not revealed it to Peter: and the son was revealed in the apostle.
And none that deny revelation can preach Christ in truth;
and they that are ministers of Christ, are in his doctrine.
For when they are out of his doctrine and his commands, then they are wrong ministers;
for they minister not for Christ, but preach themselves,
and are antichrists and transgressors.
And the scripture no where says,
that '`baptism is a christian`'s circumcision,`' as sprinkling infants;
but circumcision in the spirit, and baptism in the spirit are all one,
in which the outward ends.

[.small-break]
'''

And as for all thy other silly expressions published to the nation,
it had been better thou hadst kept silent, and all of you,
than to have published your shame to the nation.
But your folly you must bring forth, to make it manifest to all men,
whose eyes are opening.
Are not you in the devil`'s snare, who are out of the discerning?
For you cannot tell what to bring people into.
Alack for you! who are hung about with rags,
and are not covered with the spirit of the Lord, but are all from that which we are in,
and so have kept people in darkness, and not turned them to the light,
being all ravened from it, and so think there is life in the scriptures,
which testify of the life!
So, I say, search them, and see if they do not testify of the life.
And all your words that ye have spoken that have not been from the life,
shall be your burden; the witness in thee shall answer it.
