[#ch-24.style-blurb, short="The Perfect Pharisee"]
== Thomas Weld, Richard Prideaux, Samuel Hammond, William Coale, and William Durant, ministers in Newcastle. Their book, called [.book-title]#The Perfect Pharisee.# Their principles follow.

[.discourse-part]
P+++.+++ They say,
'`if they shall say that every man hath the knowledge of Christ by special revelation,
and that immediate by the spirit,
they say that which is quite contrary to the common knowledge of thousands.`'

[.discourse-part]
A+++.+++ All that ever come to know Christ,
(you and all the people upon the earth,) it must be by revelation;
for no man knows Christ but by revelation.
And all that ever own Christ,
they must own '`the light that doth enlighten every man
that cometh into the world`' to be the covenant of God;
which light men are to believe in; which not believing in, they are reprobated.
And I do believe you,
that neither you nor thousands and thousands who
have had the sheep`'s clothing upon their backs,
and so have covered the wolf with it,
ever knew '`the revelation of the son of God;`' and
as none know the son of God until he be revealed,
so they have not the knowledge of him.
The scriptures testify of him, but they that had the scriptures knew him not,
only those who were in the light, and in the covenant.
So ye have all discovered yourselves to be in the apostacy from the apostles`' spirit;
and all to be the false spirits gone out into the world, for means, for maintenance,
and are all puffed up in your pride.
And that makes all your doctrine to be so dry and so barren,
there being no revelation among you, nor any immediate speaking from God and Christ,
but feeding people with the husk, with the outside.
You have here proved yourselves to be but the wolf in the sheep`'s clothing,
inwardly ravened from the spirit:
(but with it ye are comprehended:) if it had not been so,
you would never have published your folly to the nation.
But the spirit of love, and humility, and meekness,
(which bears all things,) comes to be known by the spirit.

[.discourse-part]
P+++.+++ '`For people to be led with a light within, this is to make the scriptures useless.`'

[.discourse-part]
A+++.+++ No; this lets all see the scriptures in their place, and the fulfilling of them;
which were given forth to be believed, practised, read, and fulfilled,
not for men to make a trade of them, and call people from the light within,
with which they should see the scriptures.
And none come into covenant with God, with their hearts and minds,
that they need say one to another,
'`know the Lord,`' that they may be always living under man`'s teaching.

[.discourse-part]
P+++.+++ '`How clear (say they) the scripture is, that faith cometh by hearing,
and not by minding the light within.`'

[.discourse-part]
A+++.+++ Doth any man know Christ but by the light within?
And is not Christ the word?
Can any see without the light, the word?
Doth it not make manifest?
Nay, doth it not give '`the light of the knowledge of the glory of God in the
face of Christ Jesus?`' (read 2 Cor. 4:1) from whom faith comes;
and so faith comes by minding the light within, Christ, the author of it,
and brings to look at him, and hear him.

[.discourse-part]
P+++.+++ '`And multitudes were converted by those fair epistles written by the spirit.`'

[.discourse-part]
A+++.+++ None are converted but who are in the spirit that gave forth those epistles,
though they may have all the epistles: for that baptizeth, and circumciseth,
and in that is the fellowship and unity.
Your convertings, and the Papists, have been by the epistles, out of the life,
since the days of the apostles, and so made proselytes, Pharisee-like.
People, as I said before, may get the sheep`'s clothing,
that ye have long been covered with, but inwardly have been ravening wolves,
as your fruits have declared, and the northern part of the nation may manifest.
The witness in all your consciences shall answer for me,
and let you see that your own words are your burden;
and a heavy cry will come upon you when ye feel it, who now are fat, and full;
but a day of reckoning is coming,
and inquisition is made for the blood that hath been shed, of all the prophets, martyrs,
and saints since the days of the apostles, and the prisoning,
and the persecuting by you and your offspring got up since the days of the apostles,
the false spirits that went out into the world,
that are now standing against the '`light which doth enlighten every man
that cometh into the world.`' A mark that you are inwardly ravened,
and that you are the antichrists and false prophets!
You are not like to own the light in every man, who are ravened from it,
and are turned against them that walk in the light, and keep the testimony of Jesus.
Here is the beast and the false prophet that make war against the saints,
and overcome them for a time; but the lamb and the saints must have the victory.
And you about Newcastle, ministers and teachers, are like a heap or dunghill,
sogged and mudded; but come to the witness, else eternally you will be condemned.

[.discourse-part]
P+++.+++ They say, '`Blessed are they that hear the word, and keep it;
which is a word spoken and written, not the eternal word.
It is a notion of the word of God, to call the word of God a declaration.
And the holy scriptures are able to make men wise unto salvation.
To the law and testimony.`'

[.discourse-part]
A+++.+++ To the law and to the testimony.
'`The law is light,`' saith Solomon:
and '`the testimony of Jesus is the spirit of prophecy.`'
And many may have the old and new testament,
and yet be out of the light, and out of the testimony, as you are,
and so out of the spirit of prophecy.
For Isaiah had the testimony, before Matthew, Mark, Luke, and John,
and the revelations were written, and bid them come to the law and to the testimony;
and you that do not speak according to that rule,
it is because you hate the light in you.
And Luke calls the scriptures a declaration, who was a minister of the word;
and the scriptures are the words of God, and the words of Christ, and so not the word,
but the words which the word Christ fulfils.
So ye are men not able to divide the word aright,
nor to speak a word in season to the wearied, but lead the halt, and lame,
and blind out of the way; who for so doing must find misery.

Again, they that hear the word of God, hear that which lives and endures forever;
and this word is eternal, which lives and endures forever, which they have within them;
and with that they see that the words, and letters, and writings,
or outward tables may be broken, but still the word remains.
Who would think that the ministers of Newcastle should say,
'`that the scriptures are able to make men wise unto salvation,`' and leave out '`faith!`'
You are no more made wise than the Pharisees were with the scriptures without faith.
They were not made wise unto salvation by the scriptures without the faith,
neither are you.
But who are in the faith, they are made wise to salvation through the scriptures,
and come to Christ the end of them; for it gives to see the scriptures,
and in it (in the faith) is the unity, which scribes, and Pharisees,
and apostates are out of.

[.discourse-part]
P+++.+++ '`That since the time of the apostles the call is mediate,
and that the officers and elders of the church are to be ordained by a mediate way;
the power without the person, government without governor, is a mere fancy.`'

[.discourse-part]
A+++.+++ Christ said, false spirits should come, that inwardly ravened;
they went forth from the apostles, into the world, and the world hath run after them.
They can speak no otherwise but of a mediate call,
and their elders and members are made mediately;
and so have all erred from the power and spirit of God,
and this is since the days of the apostles.
For all elders and officers of the church of God, are made immediately by the spirit;
for the church is spiritual; else how should they see the things that are immediate,
or behave themselves in the church of the living God,
which is the pillar and ground of truth,
the church which is in God the Father of our Lord Jesus Christ?
The power of God rules and orders people when there is no outward government.
Nay, it strikes down the government of men, and governors,
as in the days of Daniel and Pharaoh, and in many other places of scripture is mentioned;
the power of God strikes down government and governors who are out of it,
and this is the power that is honoured,
which strikes down false governors and government, and this is not a fancy,
as you ignorantly say.

[.discourse-part]
P+++.+++ And ye say,
'`Christ doth not forbid to be called of men master in the expression of civil honour;
and we will warrant a pulpit from the scripture -- Ezra`'s example.
'`And ye say,
they that stand praying in the synagogues are reproached as antichrist,`' etc.

[.discourse-part]
A+++.+++ They that pray for money, and preach for money, and get up a pulpit,
and plead Ezra`'s example,
they might have pleaded that the Pharisees`' had the chiefest seat!
They are ignorant of Christ, the light, the life, and the power;
who came to put an end to Ezra, and the pulpit both;
who preached up and down the mountains and wilderness,
and denied the Pharisees`' praying, and all that are got up there without the power.
And that is antichrist that is got up in the long robe, and praying for money,
and pleads Ezra`'s pulpit;
and saith '`it is a civil honour to be called of men master,`'
and so slights and transgresses Christ`'s commands,
and calls it civil respect: these, I say,
are they that have gotten the sheep`'s clothing upon their backs,
but are inwardly ravened from the spirit of God, and deceive the world.
But now their hypocrisy cannot be hid, but must come to light,
and be published upon the house top; and the light must be given to the whole house,
and not put under the bushel; and the children of light shall shine,
that men shall come to glorify their Father which is in heaven.
And you antichrists in the apostacy have got up in Ezra`'s pulpit, which comes to an end.

[.discourse-part]
P+++.+++ They say, '`It is a civil respect to say "`you`" to one.`' Again,
Christ laid down the very reason why his disciples should take neither gold nor scrip,
but wholly depend upon the means due unto them for preaching,`' etc.

[.discourse-part]
A+++.+++ When saw we the Newcastle priests go out in this manner, without gold or scrip,
and wholly depending on the preaching of the gospel?
Or when saw we any them called ministers of England do so?
-- go without a scrip, depending only upon preaching the gospel?
Nay, are not their petition`'s for maintenance,
flying up and down the nation to the magistrates, enough to shame both magistrates,
and church, and themselves too,
if they had any shame! (for it seems that their flock and vineyards will not
Maintain them!) enough to shame all the people that ever they have preached to,
and make them turn their backs on them.
For they cannot say that they have lived upon the gospel,
but they have lived upon the state, and what they have got by ravening.
He that hires upon the gospel gets a flock and gets a vineyard,
but ye are found in the pope`'s maintenance, tithes and offerings from men,
and not in the maintenance which Christ allowed to his disciples,
whom he is with to the end of the world.
Now these are state`'s ministers made by man;
and so have their allowance put in and taken out by men.
So being out of the allowance of Christ, which he gives to his disciples,
you may see ye are out of their steps;
and will appear to all sober people to be in the apostacy,
ravened from the spirit of the living God, and the power the apostles were in.
Paul said, '`Have not I power to eat and to drink;`' not great sums of money, stipends,
and glebelands, and tithes, set forth by the magistrates.
And the apostles often would not use their power to eat, though they had power.
And never did any of the prophets or apostles preach to people by an hourglass,
nor had they, when any spoke within the term of their hourglass, a law to prison them;
that is the beast that doth so, that quencheth the spirit,
and is not the ministry of Christ.
And do not many of you shake the glass, and think the time long?
And you could not tell when to give over,
and would run all into confusion but for a glass.
And is not this carnal glass your limit?
See how ye can preach without it,
and tell well when ye have done without a sickness in your spirits,
which must have a carnal glass to limit them:
which shows man hath not power over his own spirit.
The power of God knows when to speak, and when to keep silent.
And so all your preaching is by the glass, which is a limit of your earthly spirits,
who have gone from the spirit the apostles were in, and preached by;
but that which ye study out of old authors, the sheep`'s clothing,
ye sell yearly by the glass.
Is that your measure?
The priest`'s measure that he measures out to people!
Look in any steeple-house almost and see if the priest have not a measure, or it may be,
measures a day.
Do not call this the weakness of the people; for many people are ashamed of these things,
that you should give them but two glasses a week.
Now would it not be more honourable so lay by your glass, and come into the spirit,
and preach by the spirit, and to speak as it moves and gives utterance,
and quench it not in any?
That so all may learn, and all may be comforted in your church.
And '`you`' to one, is not a form of sound words; so not civil, but to be condemned,
and shows you have not learned your accidence nor grammar.

[.discourse-part]
P+++.+++ '`Such as tremble at the word of God,
and work out their salvation with fear and trembling, are judged to be notorious,
bringing back to the covenant of works.`'

[.discourse-part]
A+++.+++ Nay the power of God, that works out salvation with fear and trembling,
brings off from the covenant of works, and brings above all the powers of wickedness;
and so that is what brings the people of God to be persecuted, and hated,
living in the power and seed of God.
And no one knows salvation but who knows fear and trembling.

[.discourse-part]
P+++.+++ '`It is a delusion for one to witness an immediate call,
and others to witness with them that they are so called.`'

[.discourse-part]
A+++.+++ Were not the apostles and saints written in one another`'s hearts,
and one another`'s epistles there?
and were they not called immediately, and did they not witness one another as it is now?

[.discourse-part]
P+++.+++ And ye say, '`Some of them go naked.
And another came and said,
he had a call immediately from heaven to take away the priest`'s hour glass.`'
And speak of '`their mean apparel.`' And '`the forsaking the world,
though they neglect their families.
And they run up and down in places and streets,
or steeple-houses to vent their doctrine,`' etc.

[.discourse-part]
A+++.+++ These are the marks they give to us,
and to prove us according to the title of their book, '`Perfect Pharisees.`'
The apostles preached as they went up and down, in towns, markets,
and synagogues; and they were not Pharisees, but those were that held up synagogues,
and tithes, and temple, and priests;
so ye have the mark of '`The Perfect Pharisee`'. The name is entered into your bowels,
and hearts.
And as for any being moved of the Lord to take away your glass from you,
by the eternal power it is owned: and to take away your limit,
your carnal limit to your earthly spirits,
that are gone out into the world from the apostles, from the spirit.
And if any have been moved of the Lord, to put off their clothes,
it has been as a sign among you,
to show you you are naked and want the covering of the spirit.
And as for any going in mean apparel, and forsaking the world,
and coming off from costly attire; was not this the apostles`' doctrine?
Are ye like the apostles, the messengers of Christ, or the messengers of Satan,
crying up the world, and its glory, and costly attire?
And who are come to forsake the world,
are come out of the sinful neglect of their families,
into the wisdom of God that preserves the creation, and is not destructive.
And as ye are speaking of perfection, so far as men are perfect,
they are perfect in glory,
and '`changed from glory to glory,`' and witness perfection upon earth,
and see an end of it, as David did, who had outstripped all his teachers.
But among all yours, that are kept under your teaching, there is no talk of perfection,
so you fall short of coining to see the end of it.
And the one offering, and the blood of Christ, and the new covenant, perfect, blot, out,
and cleanse from all sin.

And as for all the rest of your unsavoury, and hard expressions in your book,
judgments and sorrow ye will feel for them;
and in the day you are judged the witness in you shall answer.
