[.style-blurb, short="Holy Scripture Clearing Itself from Scandals"]
== Thomas Pollard, a member of the church about Litchfield, in his book which he calls, [.book-title]#The Holy Scripture Clearing Itself from Scandals.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`It is a cavil to say "`thee`" and "`thou`" to a single person.`'

[.discourse-part]
_Answer._ Which shows that he never learned accidence nor bible;
it is the language that the saints spoke one to another.

P: He saith, '`It is wickedness to call the letter of the scripture,
and what is gotten from the scripture, brain knowledge,`' page 4.

[.discourse-part]
_Answer._ The letter is paper and ink, and the letters are carnal,
and what is gotten from it without the spirit, is brain knowledge.
But the scripture, the thing it speaks of, is spiritual, the word is spirit, etc.

[.discourse-part]
_Principle._ He saith, '`The Lord never said to you as he said to David,
that you are "`after his heart,`" or any of your way, or that ever went in your way;
and do not destroy all by your doctrine,`' page 7.

[.discourse-part]
_Answer._ No; David had outstripped all his teachers; so have we, many of us,
who have trembled as David did, witnessing the new covenant, Christ Jesus,
in which we need not say '`Know the Lord.`' And who witnesseth this,
witnesseth the tabernacle of David built.
Again, our doctrine destroys but men`'s transgressions,
and doth not destroy '`the smoking flax,
and bruised reed;`' and we can say we are after his heart,
and God hath said we are after his heart.

[.discourse-part]
_Principle._ He saith, '`And that people may find rest to their souls,
take the law and testimony.`' See page 9.

[.discourse-part]
_Answer._ Many that have the scriptures,
deny the light that doth enlighten every man that cometh into the world, and say,
prophecy is ceased; so then they may say the spirit is ceased, it is all one:
for '`the law is light,`' saith Solomon, and
'`the, testimony of Jesus is the spirit of prophecy.`'
Now the world cries,
the law and testimony are the Old and New Testament; but many may have these,
and yet deny the law and testimony, which is the light and spirit of prophecy;
for the law and testimony were in the days of Isaiah, before Matthew, Mark, Luke,
and John, and the epistles and revelations were written.
And so they that are not according to the law and the testimony,
are out of the light and spirit, in the darkness, though they have all the scriptures,
which the law and testimony own in their places.
And many may have the scriptures given forth from the spirit of God,
and yet cannot have the comfort and rest to their souls,
till they come to Christ that the scriptures testify of.

[.discourse-part]
_Principle._ He saith, '`Try the spirits whether they be of God,
for many false prophets are gone out into the world,`' page, 11.
And '`Satan transforming himself into an angel of light;
and false apostles and ministers of unrighteousness transforming
themselves as the ministers of righteousness.`' And he saith,
'`If they bring another gospel and doctrine than what is preached,
receive them not into your houses, nor bid them God speed.`'

[.discourse-part]
_Answer._ That which ye now tell people is the gospel, which ye preach,
are the four books of Matthew, Mark, Luke, and John, etc.
As instance priest Shaw of Aldingham in Lancashire who said so;
contrary to the scripture, which saith,
'`the gospel is the power of God.`' And many may have the four books of Matthew, Mark,
Luke, and John, etc. the form, but deny the power, and so deny the gospel,
which is the power of God.
And so they that deny the power have put the four books for it;
and they that have not the Father and the son are not to be received into their houses,
as saith the apostle John; for they come in the form, and deny the light, as you do:
but he that hath the son and the Father, he is in the power, the substance of the form.

Again,
the devil '`transformed himself as an angel of light,`' before the apostles`' decease,
and false apostles, devil`'s messengers, and ministers of unrighteousness,
were got up before the apostles`' decease.
And the '`false prophets were gone out into the world,`' and the false spirits,
before the apostles`' decease, as in John;
and since the days of the apostles they have led the world after them, have been,
received into houses, and corrupted the whole earth, of whom you have been.
Therefore the apostles brought the saints then to the '`anointing within them,`' and
to the '`light that shined in their hearts,`' which would give them '`the light of the
knowledge of the glory of God in the face of Christ Jesus,`' which light you bring from.
And now since the days of the apostles have ye been carried away,
swallowed up by such as have not the Father and the son;
and are the false spirits that went forth into the world, and the false prophets,
and Satan,
who hath '`transformed himself as an angel of light,`' and the ministers of unrighteousness,
and false apostles, who confess they have not the same spirit as the prophets, Christ,
and apostles had, so are erred from them, and are the false spirits, false prophets,
and false apostles; who have been destroying since the days of the apostles.
For the false apostles, Satan`'s ministers, '`transforming:
themselves as angels of light,`' these went all out from the spirit that the prophets,
Christ, and the apostles were in.
So these were the spirits that were to be tried by them that had the anointing in them;
you, who now are tried by them that are come to the anointing in them,
are seen to be gone out from the apostles.

[.discourse-part]
_Principle._ He saith,
'`You put out the eyes of poor souls by bidding them
to hearken to the light within,`' etc. page 14.

[.discourse-part]
_Answer._ The eye that sees the soul is the light which cometh from Christ the bishop of it;
and no one knows the eye of the soul, but who comes to the light within that opens it,
which cometh from Christ the saviour of it,
which gives him '`the light of the knowledge of the
glory of God in the face of Christ,`' 2 Cor. 4. and lets him see his saviour.

[.discourse-part]
_Principle._ He saith,
'`I affirm that no man can have salvation by virtue of his obedience,`' etc. page 17.

[.discourse-part]
_Answer._ He that believes is saved; he hath salvation;
he that doth not '`is condemned already.`' And no man hath salvation but by believing,
and where believing is, there is obedience to the gospel.
They that obey it not are condemned, and neglect their salvation.

[.discourse-part]
_Principle._ He saith, '`They lay in wait to deceive,
who call the breaking of bread carnal,`' page 18.

[.discourse-part]
_Answer._ We cannot say that the outward bread is spiritual,
the bread which perisheth is carnal; and we say Christ is the bread which is spiritual,
and they deceive people who say outward bread is spiritual, and not carnal.

[.discourse-part]
_Principle._ He saith, '`How should we have known sin, to be sin;
and righteousness to be righteousness, and a Christ that died at Jerusalem,
but by the scriptures?`' and saith,
'`nay we could not have known these things,`' page 21.

[.discourse-part]
_Answer._ That which makes sin manifest is light:
and they that had scriptures knew not Christ that died at Jerusalem, but crucified him.
And David and Joshua saw his sufferings, and saw that Judas should betray him.
And they that had scriptures knew not sin from righteousness,
they knew not the sin of unbelief; they knew not Christ`'s righteousness,
and knew not the way to the Father, but turned against the light, the truth,
which makes manifest sin as you do, and as the Pharisees did.

[.discourse-part]
_Principle._ To say, '`The officers of the church are invisible,
is plainly of the Father the devil,`' page 24.

[.discourse-part]
_Answer._ The holy ghost made the officers of the church overseers, and that made the officers,
the overseers, to be invisible: for they saw with an invisible eye;
and so they were in the spirit, which is invisible, and not in the flesh,
else they could not be overseers in the church of God; and you are the visible,
apostatized from them.

[.discourse-part]
_Principle._ He saith, '`That which is contained in the Bible is spirit and life,`' page 25.

[.discourse-part]
_Answer._ That which the Bible declares of, is spirit and life, which is Christ,
which you are ignorant of that have the letter and deny the light,
and so say life is contained in the letter.

[.discourse-part]
_Principle._ He saith, '`The scripture is able to make men wise unto salvation,`' etc. page 25.

[.discourse-part]
_Answer._ Through faith it is: for the Pharisees and chief priests had scriptures,
yet were not wise unto salvation, neither are you who deny the light of Christ.
And the seducers and evil men that the apostles saw coming in,
who should wax worse and worse, and have overgrown the world with hardness, prejudice,
and wickedness, have had the scriptures, but have not been made wise unto salvation.
They have had the scriptures without the faith in Christ Jesus, and so out of unity.

[.discourse-part]
_Principle._ He saith,
'`Paul spoke of some men that should be punished with everlasting
destruction from the presence of the Lord and his glory,
that obey not the gospel of our Lord Jesus Christ.`' See page 36.

[.discourse-part]
_Answer._ Who obey the gospel obey the power of God, and come to the substance,
the end of all the scriptures;
and obey the light which Christ hath enlightened them withal.
And such as disobey the power, disobey the gospel;
and so you have brought judgment upon yourselves who get all the form,
and put the form for the gospel.
From the presence of the glorious God and his power,
doth the power punish them who disobey it, which power is the gospel.
And those were coming up before the apostles`' decease who
have led into disobedience since the apostles`' decease;
but now are by the power of the Lord made manifest.

[.discourse-part]
_Principle._ He saith, '`Christ left us an example, who is our example,`' etc. page 32.

[.discourse-part]
_Answer._ And yet ye are offended at others who say he is their example,
and would have none to own his light:
so he is not your example that deny the light Christ,
but he that is out of the light is your example.

[.discourse-part]
_Principle._ He saith, '`For a perfection in glory to be attained to, on this side the grave,
I utterly disown,`' page 43.

[.discourse-part]
_Answer._ Where glory is in the least degree, it is in perfection, and who have not glory,
and do not attain to glory on this side the grave, are in a sad condition;
for the saints rejoiced with joy unspeakable and full of glory,
and they witnessed the hope of glory within them while they were upon earth,
and of that hope they were to give a reason that was in them,
and they saw the glory of God, and the Father,
and so came to be changed from glory to glory, till they were come into the image of God.
And the apostle saw, before his decease, such as would not endure sound doctrine;
such as were given to fables, and had the itching ears,
and heaped to themselves teachers, and those forsook the faith.
Such have reigned and now reign since the days of the apostles:
wherefore none among them come to see the glory of God,
and to '`need no man to teach them;`' and that they need not say
'`know the Lord.`' None come into the everlasting covenant,
into the power out of the form,
and none come to know all things by the anointing in them;
but they are all on heaps about their heaps of teachers, and itching ears;
and so cannot endure the sound doctrine, that any should come into the covenant of God;
that they need not say '`know the Lord.`' That is the sound doctrine,
to come into the covenant of God, Christ Jesus, the substance of all the prophets,
glorified before the world began; to learn of him who is the way to the Father,
the truth, and the life.
And the heaps of teachers are all erred from him and the apostles,
and so from the true teacher Christ Jesus,
who saith '`learn of me.`' And here people would destroy one another about their teachers,
but Christ teaches otherwise, to love their enemies:
and so men are following their imaginations, and not the Lord,
reprobates concerning the faith in which is the unity, and there you are.

[.discourse-part]
_Principle._ He saith, '`Paul did not commit the church to the light within them: for he told them,
deceivers should come,`' etc.
See page 39.

[.discourse-part]
_Answer._ When deceivers and false prophets were come among the church of the Corinthians,
Paul told the Corinthians that the light that shined in their hearts would give
them the light of the knowledge of the glory of God in the face of Christ Jesus;
and so here thou showest thy ignorance of the scriptures, and of the church,
and of Paul`'s doctrine, whose work was to bring them to the light within them,
when the deceivers were got up, and so committed the church to the light within them,
and told them that that would give them the knowledge, etc.
So they that drew people from the light within,
are the false spirits that the apostle speaks of,
that went out into the world before the apostles`' decease, who led the world after them,
by whom the way of truth came to be evil spoken of.
For the apostle told them,
that the light that shined in their hearts would give them the
knowledge of the glory of God in the face of Christ Jesus,
and not their teachers without them, as you do,
who bring them from the light within them, and so act contrary to the apostles.

[.discourse-part]
_Principle._ He saith, '`To bring people to the light within, is despising the word.`' Again,
'`The light that is in a man, is not able to lead him to happiness,`' etc.
See page 50.

[.discourse-part]
_Answer._ No man cometh to happiness but who cometh to the light within,
which cometh from Christ, the happiness of all mankind, the redeemer,
the restorer of mankind out of the fall, out of the first Adam`'s state to God,
into the second Adam`'s state, who is the covenant of God with men,
in which they have peace.
So in this light stands every man`'s happiness, and he that hath the happiness,
hath Christ the light within him, and the peace with God.
And the light within, which cometh from Christ the word, is not against the word,
nor scriptures, which are the words, but it owns them, and with them hath unity;
and no one sees the word but with the light within.
And as for all the rest of thy unsavoury expressions, and childish speeches,
they are not worth mentioning.
And thou hadst better have let silence cover thee,
than to have published thy nakedness to the nation: for thy words will be thy burden;
in the time of thy necessity, the witness shall answer in thee.
