[#ch-26.style-blurb, short="Satan Enthroned in his Chair"]
== Ralph Farmer`'s book, called [.book-title]#Satan Enthroned in his Chair.# etc. His principles follow.

[.heading-continuation-blurb]
Which is a title suitable to himself,
who is discovered by the children of the day to be Satan`'s seeds-man,
as to the nation he hath declared.
But them that are in the truth, love, and peace, he doth not touch.

[.discourse-part]
_Principle._ He saith, '`We do not pretend to infallibility as you do, which is lying,
and hypocritical,`' etc.

[.discourse-part]
_Answer._ We do believe you, that in the infallible spirit of God you are not,
but in the false fallible spirit gone out into the world,
that went forth from the apostles, who had the spirit of Christ.
And so how can you be ministers of the spirit, and not of the letter,
if ye be not infallible?
for who are in the spirit, are in that which is infallible.
This I say, none are ministers of the spirit, nor in the spirit,
nor have the spirit of Christ, nor the holy ghost,
nor the spirit of the Father speaking in them, but who have that which is infallible,
and are in that which is infallible.
And they are in the lying spirit and hypocrisy that are out of it,
as are all the false spirits that are gone out into the world.
So ye do well to confess that ye have not the infallible spirit; ye are not infallible,
and so no ministers of the spirit.
And how can they but delude people that are not infallible, and are none of Christ`'s,
which have not the spirit which is infallible, and are not ministers of the gospel,
which is the power of God, which is infallible?

[.discourse-part]
_Principle._ He saith, '`We are foretold,
that false teachers that shall bring upon themselves swift destruction,
and evil men and seducers which wax worse and worse, deceiving and being deceived,
should come.
And there should come false Christs and seducing spirits, and the doctrine of devils,
seeking lies in hypocrisy,
such as deceive the hearts of the simple with their feigned speeches,`' etc.
See pages 39, 40.

[.discourse-part]
_Answer._ Hast not thou here brought forth thy ignorance of the scriptures,
which say the seducers, and the false Christs, and the false apostles,
the doctrine of devils, and the feigned words, and fair speeches,
which deceived the hearts of people, came up before the apostles`' decease?
And dost not thou in this show thy spirit to be that spirit that went out into the world,
not able to divide the word aright?
But art telling people they are now come,
when the apostles saw they were come before their decease; among whom,
since the days of the apostles, all the confusion hath been;
and you that deny the light are in distraction.
And yet ye that be not infallible, in the infallible spirit, but fallible,
are crying to people, they are come but now, and so grow worse and worse.
And thou and the priests of Newcastle, and many of the rest of you,
are crying against such as say '`Christ is their example:`'
and yet many of you have published to the nation in print,
that '`Christ is an example,`' and the men are respected who speak
them and not the words simply as they are in themselves;
and that is partiality and respecting of persons, not the truth itself.

[.discourse-part]
_Principle._ He saith, '`If we will but acknowledge their ministry and church according to Christ,
he will write a recantation.`' See page 53.

[.discourse-part]
_Answer._ Your church and your ministry have made themselves
manifest not to be agreeable to the prophets,
Christ, and the apostles; for you say you are not infallible,
and have not the infallible spirit;
and you say you never heard the voice of God immediately from heaven, which the prophets,
Christ, and the apostles did.
And how can you be ministers of the spirit, who are not in the infallible spirit,
but the false spirit gone out into the world?
You are such as are ravened from the spirit of God, and only have the sheep`'s clothing,
and so cannot gather to the church in God, but make the nations like waters.
And you must recant before ever you come into the ministry of God, which the prophets,
Christ, and the apostles were in, and to their church,
and to own '`the light that doth enlighten every one that cometh into the world.`'

[.discourse-part]
_Principle._ He saith, '`The wise men of the east came to Christ by a star,`' etc. page 64.

[.discourse-part]
_Answer._ You say, '`The scriptures bring to Christ:`' but the Jews had the scriptures,
and came not to him, nor knew him, who were out of the spirit that gave them forth;
and so are you by your confession, and so not come to him.

[.discourse-part]
_Principle._ He saith, '`A man is not justified by that which is within him,`' etc. page 65.

[.discourse-part]
_Answer._ We are justified by faith, which is a mystery held in a pure conscience,
that purifies the heart, and this, is within.
And here again thou hast showed thy spirit to be that that went into the world,
which was reprobated concerning the faith held in a pure conscience,
without which men are not justified.
And so ye are broke into heaps, into sects, and opinions,
who are out of this faith which is a mystery held in a pure conscience,
by which people have access unto God, through which faith they are justified,
in which is unity; and it gives victory over sin,
which you plead for while you be upon the earth.

As for all the rest of thy stuff in thy book, it will be thy own garment,
and a heavy load and a burden thou wilt feel it,
whose nakedness might have been covered by thy silence, but thy spirit must be tried.
I say, the Lord forgive thee, for a heavy charge is come upon thee, and you:
for instead of seeking the peace of all men,
you have made yourselves manifest to be neither ministers, nor fathers, nor elders,
nor sober christians, but wolves, that tear and rend to pieces.
Indeed, the ragged righteousness of men, the world`'s clothing which hangs on your back,
ye may have; but the elect, and the saints, and the Lamb`'s clothing,
the righteousness of the saints, ye cannot touch,
but the lambs are lain down in the fold.
