[#ch-27.style-blurb, short="The Scornful Quakers Answered"]
== Magnus Byne`'s book, called, [.book-title]#The Scornful Quakers Answered.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`Beware of false prophets that come to you in sheep`'s clothing,
but inwardly are ravening wolves.
Believe not every spirit, but try the spirits whether they be of God,
because many false spirits are gone out into the world.`'

[.discourse-part]
_Answer._ Must thou show thy ignorance of the letter?
so much a man unlike to divide the word aright?
For Christ saith, false prophets should come, and antichrists,
that should be inwardly ravening wolves, that had the sheep`'s clothing;
these John saw were come before the apostles`' decease; which went forth from them,
and all the world went after them.
And they could not have deceived the world,
if the wolf had not had the sheep`'s clothing upon him.
You may read in the Revelations, how they ravened and devoured,
and drunk the blood of the martyrs, saints, and prophets;
and so you that are crying to the world,
'`they are come but now,`' are the deceivers of the world, as you may read Matt.
vii. and 1 John 2:4. Revel, chap.
xiii.
xiv. xvii.
xviii.
and are not dividing the word aright.
For now are people come from them, and coming to Christ the rock, the foundation of God,
and to that spirit which you have ravened from; which stands sure,
before the world was made, out of the waters.
For the nations are as waters, and the false spirits, the false prophets,
and the mother of harlots have ruled,
and with the sheep`'s clothing have deceived the nations;
but now the Lamb and the saints shall rule:
for ye have confessed that ye have not the infallible spirit, as the prophets, Christ,
and the apostles had: so we say you are ravened from it,
and only have the sheep`'s clothing.
The prophets, Christ, and the apostles, had an infallible spirit,
out of which the false prophets, antichrists, devils, and deceivers always were;
and the mother of harlots, and Babylon, though they might get the sheep`'s clothing.

[.discourse-part]
_Principle._ He saith, '`It is filthy blasphemy to say,
the spirit of Christ that dwells in the son, dwells in man, and he must be infallible,
and he must be perfect, and sinless:`' and saith,
'`Let them alone to their father the devil,`' etc.
See his epistle to the reader.

[.discourse-part]
_Answer._ '`He that hath not the spirit of Christ is none of his;`' and
who hath the spirit of Christ hath that which is infallible,
and this is out of the spirit the devil is in.
And they that were not in the spirit, and are not in the spirit that dwells in the son,
though they have all the scriptures, are in the spirit of blasphemy,
that will blaspheme against the son: and there thou art.
And the false spirits that are in the world are on heaps about the son`'s,
the prophets`', and apostles`' words,
out of the infallible spirit of those that gave them forth, who were perfect and sinless,
as in Rom.
vi. they '`were made free from sin.`' The apostle said they were perfect,
and he '`spoke wisdom among them that were perfect.`' And
this you deny who are ravened from the spirit of God,
and the one offering which '`perfects forever them
that are sanctified;`' and so are the unsanctified.

[.discourse-part]
_Principle._ He saith, '`There are many ways to Zion.`'

[.discourse-part]
_Answer._ There is but one way to God, out of the fall, into the paradise, to the tree of life,
out of the condemnation, and that is Christ the light, the covenant of God.
Now with the light the way to the Father is seen.
In the first Adam are many ways, fighting about their ways,
and destroying one another about their ways; but Christ the light, the way to the Father,
teacheth otherwise, to love enemies and to do good to them,
and to overcome evil with good,
and '`heap coals of fire upon their heads;`' which way is but one,
which you who deny the light are out of, in the many ways, and names, horns, and heads,
and images, which is the beast`'s number, ravened from the spirit of God,
and from the one way, Christ the light, in which is unity.

[.discourse-part]
_Principle._ He saith, '`The scripture may be understood by the help of tongues,`' page 12.

[.discourse-part]
_Answer._ All scripture was given forth by inspiration;
and so without the same inspiration it is not understood again.
Pilate had the tongues, yet did not understand the scripture,
nor Christ the substance of it.
And these your tongues, you have set up since the apostacy, ye raveners from the spirit.

[.discourse-part]
_Principle._ He saith, '`Tithes is not his infirmity, the Lord hath given him tithes:
and he doth take them as the Lord giving him maintenance, and it is his liberty.`'

[.discourse-part]
_Answer._ Tithes to the first priesthood were allotted by God; but Christ,
the second priesthood, ended that priesthood and tithes, and the priests that took them,
made by God`'s law, and disannuled the commandment that gave them.
And Christ is come, the everlasting priesthood, not after the order of Aaron,
but after the order of Melchisedeck, the similitude, in whom the similitude ends,
Christ the end, the substance, the end of war.
So thou that takest tithes art (out of the substance of Melchisedeck
and the first priesthood that took tithes) in the transgression,
and in the imitation, and the veil is over thy heart, and thy liberty is bondage,
in the unsanctified state.
But the sanctification is in the son of God, who ends types and similitudes.
And he it is that sanctifies, and who preacheth the gospel, lives of the gospel.
And the pope hath given thee thy tithes by his command,
and not by the command of the Lord, for Christ and his apostles established them not.

[.discourse-part]
_Principle._ He saith, '`that the scriptures are the sure word of God:
and that the scriptures are a precious light,`' page 17. Again he saith,
'`The son of God is the first principle of the pure religion.`'

[.discourse-part]
_Answer._ The fulness of the godhead dwells in the son, and he is in the Father,
and he is the author of the first principle, and the end of the law,
for he is all and in all; for many have something from him, yet cannot say he is come;
but he that hath him, hath life eternal, hath the substance, the end of things.
And the scripture declares and testifies of the light, which is Christ;
but many may have the scriptures, and stand against the light,
'`for they are they that testify of me,`' the light.
So Christ is the precious light, and the scriptures are the words of God;
but Christ the word was before they were given forth,
the word in whom these words of God end.
So thou mayst see thy ignorance.

[.discourse-part]
_Principle._ He saith, '`While we stay in Sodom, we crucify the Lord of glory.
And Christ is buried in us,`' etc.

[.discourse-part]
_Answer._ And John Bunyan, a teacher there, fights against him;
and thus they are not only against the truth, but one against another.
But he must know the suffering of Christ in the spiritual Sodom in him,
and see the seed that suffers there, before it reign, and he reign with Christ in glory.

[.discourse-part]
_Principle._ He saith, '`It comprehends our suffering in the flesh after his example.`' Page 21.

[.discourse-part]
_Answer._ At this do the priests of Newcastle, and John Bunyan,
and many others of the teachers of the nation, rage;
and here you are one against another; but Christ said,
'`why persecutest thou me?`' And he was in prison,
and it is your work to put him in prison.

[.discourse-part]
_Principle._ He saith, '`he hath the tithes of two parishes;
and it is the old man that minds the earthly things,`' page 23. Again he saith,
'`And those that take tithes are not antichrist.
And the scripture is a choice vessel of the Lord`'s sanctuary,`'
and '`it is the letter and the history,`' etc. page 25.

[.discourse-part]
_Answer._ Well may people be all in confusion, when ye say the scripture is a history,
a declaration, the letter, a vessel, the choice vessel of the Lord`'s sanctuary, a light,
and yet the word of God!
Now is not this to break people to pieces?
The scriptures of truth are the words of God, and they are called a declaration,
and a treatise.
And the choice vessels were those that gave them forth, vessels of mercy, and of honour.
And they that take tithes, and pay them, are out of the substance, Christ,
who is the end of tithes; for he is the sum of tithes,
and all other figures that pertained to the first priesthood, first covenant,
and of all similitudes.
So thou taking tithes of two parishes, hast the mark of the old man.
For the apostles preached up and down in many synagogues where the priest were,
yet they did not seek for the tithes that belonged
to them that pertained to the first priesthood.
They preached the gospel, and lived of the gospel, and said, '`they were evil beasts,
that minded earthly things;`' of whose spirit ye are found, judged by the word,
which is Christ.

[.discourse-part]
_Principle._ He saith, '`He is called of men master through man`'s courtesy,`' and calls them,
'`blind and sinful, and in error, that speak against it.`' Again,
'`it is not oppression in him to take tithes of two parishes,`' etc. page. 28. 30.

[.discourse-part]
_Answer._ Here under the woe of Christ art thou come; who said,
'`Woe unto them that were called of men master;`' and said to his disciples,
'`It shall not be so among you, for ye have all one master,
which is Christ,`' and they abode in his doctrine.
And we do not read of Mr. Paul, Mr. Peter, Timothy, or Titus, or Mr. James or John;
but among you, the apostates, we read of such titles.
And you set up that which Christ, (him by whom the world was made,
before it was made,) came to fulfill and end, in the world, which typed him forth,
Christ the way to the Father out of the world.
And tithes in the first priesthood are not the way, they are oppressors that cry them up,
and builders up of that which Christ ended, so transgressors;
not having the son nor the Father.
And they bring not the glad tidings, for the jails may witness in the nation,
that glad tidings are not brought; and the courts, and the oppressed parishes,
in which ye take treble damages of many people that ye do not work for,
and cast into prison; and so this is not the gospel, this is not the glad tidings.

[.discourse-part]
_Principle._ He saith, '`I find not this power of binding kings with chains,
and nobles with fetters of iron, which is the honour of the saints;
this scripture I find not fulfilled,`' etc. page 35. Again he saith,
'`A saint may be found in that which is sinful,
though this man (the Quaker) will not allow of sin.`' Again,
'`The people of God are more than conquerors in the Lord,
which gives them rest and peace in the midst of their wars.`' Again,
'`Hope keeps the soul groaning and waiting all the
while in the earthly tabernacle,`' etc.

[.discourse-part]
_Answer._ I know the power, and spirit, and sword of the saints that executes the judgments,
to bind, and chain, and fetter kings and nobles; thou art out of it,
but it is now among the saints; and that scripture is fulfilled, yea in England,
among the saints.
And such as are more than conquerors, see the end of wars, and that which causeth wars.
He that is a conqueror may be in the war; but he that is more than a conqueror,
is in that which takes away the occasion of wars,
and is come to that which was before wars were.
And he that hath this hope, (which is Christ,) hath that which purifies himself,
even as he is pure, and comes to witness the kingdom of God that stands in joy, peace,
and righteousness, and so is not always groaning in the earth,
under the earthly tabernacle, while he is upon the earth,
but comes to know the body of sin put off, and a being made free from the body of sin.
And a saint is not sinful, neither do the saints ever allow or approve of sin;
he that allows and approves of that is out of the sanctified state.

[.discourse-part]
_Principle._ '`Notwithstanding thy passing the first and second resurrection,
(as thou sayst,) there remains a torment for thee at the last day, and woe,`' page 42.

[.discourse-part]
_Answer._ They are blessed that have part in the first resurrection,
the second death hath no power over them; but are made free from wrath that is to come,
and are passed from death to life, and are translated into the kingdom of the son of God,
and are in unity with the son of God and the Father both;
and so thou utterest forth lies.

[.discourse-part]
_Principle._ He saith, '`To declare against such as are called of men master,
is a matter of his faith.`'

[.discourse-part]
_Answer._ They had not faith that were called of men master, whom Christ cried woe against;
nor the Jews; neither have you who break his commands.

[.discourse-part]
_Principle._ He saith, '`The spirit that declares in the letter, keeps me from vanity,
frees me from the law of sin and condemnation.`'

[.discourse-part]
_Answer._ The spirit that was in the saints that gave forth the letter,
freed them from the law of sin and condemnation, and kept them from vanity.
The spirit is not in the letter, for many may have that, and not the spirit:
and all are in sin and vanity, and are not freed from the law of condemnation,
but who are in the spirit.

[.discourse-part]
_Principle._ He saith, '`They are to feed the people, who are ordained over a particular place,
over which the holy ghost hath made them overseers;
and they are covetous wretches and worldings that keep back their tithes.
And no more wages he receives than what the gospel allows.
And he is a thief that keeps back the hire from the labourer,
and the Lord gives man tithes as a portion in the earth,`' etc.
See pages 57, 58, 59, 60.

[.discourse-part]
_Answer._ The holy ghost made the apostles and elders overseers of the church.
But you have been made overseers by men, by the pope, by your schools and colleges.
So thus you deceive the people, by telling them the holy ghost made you overseers.
For ye say ye have not the same infallible spirit as the prophets, Christ,
and the apostles had, as witness Samuel Eaton in his book, and divers others.
Tithes were allotted by God to the priests and Levites,
and people in the first covenant and priesthood,
and they were robbers that kept them back; but Christ is come, the everlasting covenant,
who ends the first covenant, tithes, and priesthood, and blots out the ordinances.
Therefore they that are covetous, will take them by violence from the people.
But they that are come to the gospel allowance, '`freely ye have received,
freely give,`' what they set before them, of that they are to eat, preach the gospel,
and live of the gospel.
These triumph and trample upon the first priesthood, types, figures, and shadows;
see that the priesthood is changed, the ordinances blotted out,
the commandment disannuled that gave them;
witness the one offering for the sin of the whole world, and are of the royal priesthood.
Such as these cannot pay tithes; covetous persons and worldlings may take them,
that are apostatized from the apostles, by whom the true seed is oppressed;
who went forth from the apostles by a usurped authority,
under whom you are sheltered for your tithes, which were set up by the pope`'s authority.
But now you are seen and judged by them who are come to the apostles that you went from.

[.discourse-part]
_Principle._ He saith,
'`The Lord hath given tithes for the maintenance
of the ministry of this nation.`' Again he saith,
This light within is turned into utter darkness,`' pages. 62. 65.

[.discourse-part]
_Answer._ It has been the Pope and the apostates from the apostles that have given tithes;
from the spirit that the apostles were in they are ravened that take them,
for the apostles took none.
Their fruits in the nation declare it; if they will not give the priests tithes,
how they cast them into prisons, and dungeons, until death!
Christ`'s maintenance the apostles witnessed; freely they had received,
and they gave again freely;
and he that '`preached the gospel lived of the gospel,`' and coveted no man`'s silver,
goods, nor apparel.
But do not ye covet men`'s silver and goods, when ye take treble damages of them,
and cast them into prison?
Is not this the work of the ministry of the nation?
Is not the overflowing scourge of the Almighty gone over you?
and the rod and the lash come upon you all?

Again, the light within hath led to the light of life, and leads to the light of life,
out of utter darkness,
in which those and thy generation are seen that stand against the light.
So all you apostates are whelmed under in the apostacy since the days of the apostles,
who are out of the allowance of Christ, his wages and maintenance, the giving freely,
which shows they have not received of God, but buy and sell,
yea and after great rates too;
and so are the merchants that John speaks of in the Revelations:
and this cumbers the creation, yea, nations; ye bring not the glad tidings to them,
but burden them: ye are seen and felt.

[.discourse-part]
_Principle._ He saith, '`away with your bodily, fleshly,
literal trembling and quivering.`' See page 70.

[.discourse-part]
_Answer._ Habakkuk`'s lips quivered, David`'s flesh trembled, Daniel trembled, Paul trembled,
David`'s bones quaked; and that man the Lord regards who trembles at his word,
though cast out by thee and thy generation in this age, as in the days of Isaiah.
So thou and thy generation, who say '`away with trembling of the flesh and body,`' say,
away with the power of God that throws down that which defiles the flesh.
Before sin is condemned in the flesh, and the powers of darkness wrought out of it,
you must know trembling; thou and all thy generation,
before the devil be dispossessed of your earthly tabernacles, you must know trembling;
and thou and thy generation have showed your ignorance of the mighty power of God,
the '`salvation that is wrought out with fear and trembling.`' And of that power
that in all ages threw down the nature that captivated the seed of God,
and defiled the flesh, and darkened the understanding, the sense, and reason,
and warred against the soul,
ye have showed your ignorance of that power whereby the body, soul,
and spirit come to be sanctified.
And before this be so, ye must know a bodily trembling and shaking; but he cries,
'`away with it`' before ever he came to it, lest he should be tormented before his time;
who is one of them who ever were against the holy men of God.
But the power of the Lord God has overtaken thee, and with that are ye comprehended,
and ye are in the press, and your cluster is full, and the sickle is gone out.

[.discourse-part]
_Principle._ He saith, '`The priesthood is changed,
but not the tithes abolished by the coming of any substance;
and he that keeps back the tithes of God, hath preferred his mammon before his God,
and is guilty of the sin of Ananias:
and denying to pay tithes is weakening the bands of the ministers:
and God in wisdom hath provided by an outward law, in the absence of the inward,
for the maintenance of the ministry by tithes or other maintenance,
and so they own a tribute unto God; and so they must pay tribute,
and custom to whom custom is due.`' Again he saith, '`custom, tribute, tithes,
etc. love will teach these things are due, therefore covet not another`'s portion.`'

[.discourse-part]
_Answer._ When the apostle had spoken of tithes, before the law,
to Melchisedeck like unto the son of God;
and spoken of tithes to the priesthood made by a law that had a command to take them;
he said the priesthood was changed, the law was changed,
the command was disannuled that gave tithes, the son of God was come,
the end of the similitude and likeness before the law.
'`Now,`' saith he,
'`of the things (tithes were things before the law and in the law) which we have spoken,
this is the sum: Christ a minister of the sanctuary,
and of the true tabernacle which God hath pitched
and not man.`' So there is the sum of the things,
and the substance; and the plenteous redemption, that leads men out of the earth,
that brings them to lay down all at the feet of the apostles,
which is beyond tenths which were due to the service of the Lord.
Here the earth comes to be known to be the Lord`'s, is given up,
and man redeemed out of it.
Of this glorious gospel are ye all ignorant.
And so tithes are not to be compared with Ananias, and not to be viewed as a tribute,
but as a custom which has got up since the days of the apostles, in the apostacy,
the nations having drunk the whore`'s cup, and kings and queens,
that had gone out of the power of Christ which the apostles were in,
into the beast`'s power, have made schools to make their ministers,
and have made laws to set up tenths.
So this custom of the sin hath taken away the sense of it,
that people have been so hardened that they have torn people, spoiled their goods,
and cast them into prison, and taken treble damages, and kept them in prison,
and haled them before courts and sessions, assizes, and benches.
Which is not like the ministers of Christ;
for the law is changed of God that gave tenths,
and since that was changed the law is in the heart, and a new covenant.
And since the apostacy men have got the sheep`'s clothing, ravened from the spirit,
wolves, whose fruits declare it; who have deceived nations, and the world,
and have got up a law from man, and a command from man, the pope being the author.
The law and command of God are changed that gave tithes,
and they have got up the law and command of man to take them,
and the law of God and his command are denied, as spoken by the apostle, Heb.
vii. But all that are in the wisdom of God see over these things, and feel over them,
and judge you all, and execute judgment,
and are in the power and authority to execute judgment, and convince all,
and are in the honour of saints.
So your ministry, if tithes fall, is weakened;
but the ministry of Christ came in when tithes fell,
and that ministry fell that held up tithes,
and that priesthood during which the priests`' lips were to preserve the people`'s knowledge.
So by the fall of that ministry that took tithes, the ministry of Christ came in.
The rise of this ministry is since the days of the apostles in the apostacy,
that is made by kings, bishops, popes, schools, and colleges.
Tithes falling, the hands of this ministry that takes tithes, thou sayst, is weakened;
it is not, therefore, the power of God that strengthens the hand, but the earthly.

Now I say, in the fall of the maintenance, which weakens this ministry,
ye have showed what ye are covered withal,
and in the fall of this is the rise of the Lamb and his ministry,
the preaching of the everlasting gospel;
and the everlasting gospel shall be preached to them that dwell on the earth,
which is the power of God: and though the devil, and the beast, and the false prophets,
and the kings of the earth do make war against the saints and the Lamb,
yet the saints and the Lamb shall get the victory.

[.discourse-part]
_Principle._ He saith, '`Christ without the church doth not comprehend all the elect;
and we are not elected, though we receive Christ,
because we are elected in him,`' etc. page 80.

[.discourse-part]
_Answer._ Thou art meddling with things too weighty for thee,
Christ is the elect whom God upholds, and the election obtains it,
(the victory,) and Christ knows his, and said he had other sheep,
and he knew all the elect.
And he is the wisdom of the Father, the light, the life, and the power of God,
the offering, the sacrifice for the whole world, the redemption of mankind.
And who receive him, and are in him, are the elect, and out of their own works,
and have possessed him, and his image and glory; are come to the throne of grace;
he is in all and over all, the salvation to the ends of the earth,
and they who are elected receive Christ, and are in him.

[.discourse-part]
_Principle._ He saith, '`Thy denial of sin, and Satan, and antichrist,
to be where they are in power and part, is the old trick of the evil one,`' etc. page 83.

[.discourse-part]
_Answer._ They who are come into the Lamb`'s power, are come out of the power of the beast, sin,
and Satan; into the city, the paradise of God, where no unclean thing enters,
but the tree of life is the food; and they are atop of sin, Satan, and antichrist,
and all thy tricks; and witness against all sin.

[.discourse-part]
_Principle._ He saith, '`When the dissolution comes,
he bids farewell to all the saints of God,`' page 94. Again, '`If we say we have no sin,
we deceive ourselves, and the truth is not in us: if we say we have not sinned,
we make him a liar,`' page 89.

[.discourse-part]
_Answer._ The saints are in Christ and God; and at the dissolving of the earthly, or sin,
they do not bid all the saints farewell; for then they come into unity with them,
with the elect.
And John shows there was a time to see they had sinned, and a time to see they had sin,
and a time to confess it and forsake it,
and a time to witness the blood of Jesus Christ to cleanse from all sin,
a time to witness the birth of God born, which doth not commit sin,
and the seed of God remaining in them, that the wicked one could not touch them.

[.discourse-part]
_Principle._ He saith, '`The saints are neither in the fulness of the godhead, nor part:
away with this blasphemy that saith this,`' etc. page 92.

[.discourse-part]
_Answer._ The work of the ministry was to bring people to the knowledge of the son of God,
to a perfect man, to the unity of the faith,
to the measure and stature of the fulness of Christ, and Christ will dwell in the saints,
and God will dwell in them.
And thou sayst they have no part of the fulness of the godhead; but John saith,
'`Of his fulness have we all received;`' in whom dwells the godhead bodily.
And ye are all in the blasphemy that are out of this part of the fulness.

[.discourse-part]
_Principle._ He saith, '`The Quakers know a man whether he be a saint or a devil,
as soon as they see him, or hear him speak, or act,
and they are beyond all our forefathers.
And the apostle saith, "`What man knoweth the things of a man,
saving the spirit of a man that is in him,`" so ye are not as Christ in
this respect.`' And thou sayst '`thou art as Christ in this present world:
and no man can be without sin in this house of clay.`' And sayst,
'`I was shapen in iniquity, and in sin my mother conceived me;
and my flesh is sin`'s freehold,`' etc. pages 94,95.

[.discourse-part]
_Answer._ Here thou hast showed that the Quakers have a spirit given to them beyond
all the forefathers (which we do witness) since the days of the apostles,
in the apostacy.
And they that are in the power and the life of truth, can discern who are saints,
who are devils, and who are apostates, without ever speaking a word.
And the natural man knows not the things that are in another man;
but with the spirit within him may know what is in himself:
but the spiritual man searcheth all things, yea the deep things of God.
Here thou hast made no distinction betwixt the spiritual and natural.
And as Christ '`is, so are we in this present world;`' and where Christ is manifest,
he destroys sin in the flesh; here they come to be as he is,
they come to be above clay and mortal, and fading, and so the flesh,
which thou calls sin`'s freehold, comes to be put off, and the body of it,
and they come to be made free from the law by the body of Christ.
And the creature comes into the liberty of the sons of God.
And this the saints witnessed while they were on earth.
And as thou wast born in iniquity, thou showest thou wast born in the unregeneration;
there were some sanctified from the womb, there are some children clean,
who are believers.
He that can receive it, let him.
So thou art an ignorant man, not able to divide the word aright,
nor canst minister unto the people, not knowing the condition they are in,
unless they tell thee, and so art apostatized from the apostles,
and not one of the ministers of the spirit, that minister to the spirit;
for could not the apostles preach and speak to the Jews and Gentiles,
unless they came and told them what condition they were in?
or did all the Jews and Gentiles come and tell the apostles
what condition they were in before they preached to them?

[.discourse-part]
_Principle._ He saith, '`The light in man is imperfect, a weak, faint light,`' page 97. Again,
'`The light in the Gentiles is called a natural light,`' page 88.

[.discourse-part]
_Answer._ The light that every man hath that cometh into the world, is not an imperfect light,
a weak, nor faint light, nor a natural light; but they who are weak, go from it,
and faint, and hate it, and despise it, as Esau, and run into the earth.
But those who believe it, have the light of life; and who receive it,
become the sons of God.
And the light in the Gentiles, which brought them to do the law, was spiritual,
not natural; whom the apostle sets up to be the circumcision, and the Jew inward;
and throws out the Jew outward, and circumcision both.
And this brings to have '`praise of God,`' which the Jews had not in the outward,
and makes the Jew no Jew, and their circumcision no circumcision, and judges them,
and all professors upon the earth that are from that that doth the law in their heart,
and the Jew inward.
And you are from that, who stand against the light of Christ that doth enlighten, etc.

[.discourse-part]
_Principle._ He saith, '`if any hypocrite reign, his power is of God:
and saints are to yield to the power, and it must be honoured,
and have obedience from the saints,`' page 101. '`And
so they that call them corrupt magistrates,
are the filthy dreamers that Jude speaks of,`' page 102.

[.discourse-part]
_Answer._ Such as are turned into corruption, and are hypocrites,
are gone from the higher power, which the soul should be subject to,
and it is gone over them;
and so for the Lord`'s sake the saints cannot be subject to that power,
but to the power that brings down the hypocrisy, and the corruptions in magistrates;
and as they come to be clothed with the power of God,
they are able to put a difference betwixt the precious and the vile;
and that the saints own; those are a praise to them that do well.
The Jews of old time, that feared God, that lived in the law of God,
could not obey the heathen magistrates, how to their gods, nor to their commands,
nor their power or authority.
Nor could the apostles how to the authority of the Jews,
to their ordinances which Christ came to put an end to, nor the power that held them up,
nor that among the Gentiles, held up by the magistrates.
For Christ was come to reign, who had all power in heaven and earth given to him.
And since the days of the apostles the saints cannot bow to that which the pope,
and kings, and queens set up in the apostacy,
though they call it a supreme power that commands the things.
But who are in the power of God, it destroys that which defiles the flesh,
and the evil speaker, and that is the dignity which the saints own and live in,
and speak not evil of, but they who do so transgress the spirit of God, and go from it,
and are such as Jude speaks of.
Therefore have the martyrs, saints, and prophets suffered,
since the days of the apostles, by the beast, the false prophets, and the great whore,
which have been in the power of the devil that went, out of truth:
and that the saints were not subject to.
But now Christ is come to reign, and the Lamb and the saints shall have the victory;
and the higher power is owned, that is higher than all the transgressors upon earth,
that reaches to the soul,
and the transgressed principle of God in every man upon the earth;
for the beast`'s power hath set up your tithes, temples, and colleges,
and compelled men to worship it, which the saints could not do,
and therefore have suffered by it, who have worshipped God in the spirit and truth,
that the devil is out of; and such were in the higher power.

[.discourse-part]
_Principle._ He saith, '`There is a kind of infiniteness in the soul;
and it cannot be infiniteness in itself,`' page 103.

[.discourse-part]
_Answer._ Is not the soul without beginning, coming from God, returning into God again,
who hath it in his hand, which hand goes against him that does evil,
which throws down that which wars against it?
And Christ the power of God, the bishop of the soul, which brings it up into God,
and which came out from him, hath this a beginning or ending?
And is not this infinite in itself, and more than all the world?

[.discourse-part]
_Principle._ He saith, '`The soul is a creature; and yet it is a noble power, and an essence,
and is the appetite, fancy,`' etc.
Again he saith, '`he knows that the soul is a spiritual thing,
and cannot be divided into parts and powers,
as being one single entire essence,`' page 107.

[.discourse-part]
_Answer._ The soul is in the death in transgression,
so man`'s spirit is not sanctified while the soul is in death.
And fancy, appetite, anger, pleasure,
etc. which thou sayst '`are taken for the soul usually,
and called the soul,`' are they that war against it: thus thou divides the soul,
which is one, into parts, and art ignorant of it,
and yet thou hast said it cannot be divided!
So thou art in confusion in Babylon.
The soul being living, and the spirit sanctified,
that diligent hearkening is come to where the counsel of God is stood in,
his voice heard, his hand felt, that the soul comes up into, that comes from God;
that is living and immortal, and gives a creature its feeling,
and sensibleness to divine things:
and so the covenant of God comes to be received wherein
the soul lives to the bishop of it,
which is immortal, and then that birth of the new creature is known,
whereby the spirit of man is sanctified,
and the God of the spirits of all flesh is known.
Now where the power and life guides up to God the Father of life,
that works down and directs the mind up to God, the immortal to the immortal,
whereby light springs, Christ is known, and the soul praiseth God the saviour, who,
in its low estate, hath regarded and reached down to it.
Now where the light is hated, and that of God within transgressed,
(that doth pertain to the righteous law of God,
and answers it,) the spirit of man is not sanctified;
and man`'s understanding being darkened, the higher power is denied,
the soul comes into death, transgressing of the law is known,
the witness is buried which should guide the mind,
whereby the soul should live in the diligent hearkening.
Hereby man comes to be defiled, and his spirit, and body, and mind,
whereby he glorifies not God in his body, and soul, and spirit,
and glorifies not the God of the spirits of all flesh.
Hereby he comes to be an alien and a stranger to the life of God,
and his ways and covenant.
And thou sayst '`The soul is a spiritual thing, and yet a creature, an appetite,
and fancy.`' Every man that cometh into the world, though they be in the first Adam,
have a light from Christ the second Adam, the bishop of their souls.
So every one being turned to the light which Christ
the second Adam hath enlightened them withal,
they shall see the bishop of their souls, Christ the power of God, which is immortal,
and brings the immortal soul into the immortal God.
Christ is their sanctification, who sanctifies their spirits, and bodies,
and brings the soul up into God, from whom it came, whereby they come to be one soul.
For in the lusts of the world, and the affections of it, is the war against it,
and there are the powers of wickedness.
The soul must be in the higher power, higher than the flesh, which stains the man,
spirit and body, and the powers of wickedness.
So the light being turned to, man receiveth the spirit of God, which sanctifies him,
the spirit of sanctification in Christ Jesus the sanctification and redemption.
So every man that cometh into the world has a light from Christ Jesus,
the way out of the fall, the second Adam,
and receiving the light he receives his redemption and sanctification,
whereby his spirit, body, and soul are sanctified.

[.discourse-part]
_Principle._ He saith,
'`The binding of Satan shall not be by a personal reign of Christ in a body.`' He saith,
'`The Quaker denies the light written in Scripture:`' and saith,
'`When ye pretend most love to Christ within, and light within,
ye deny the Lord that bought you; and the high talk of a light within,
goes out forever into utter darkness.`'

[.discourse-part]
_Answer._ Who own the '`light within,`' and '`Christ within,`' and are come into it,
own the Lord that bought them, Christ, and no other;
and they that receive not this within, are reprobates, without him,
yet talk of him as the devils, false prophets, and deceivers.
And they that go from the light within, go into utter darkness, and stumble,
and do not know whither they go, and want the garments, the Lamb`'s clothing.
And so, '`he that believes in the light within,
hath the witness in himself,`' abides not in the darkness, nor in the condemnation,
but hath the light of life.
And the light within that '`shines in the heart,
gives the light of the knowledge of the glory of God in
the face of Christ Jesus.`' And who know Satan bound,
and the false prophet, antichrist, beast,
and mother of harlots taken and cast into the fire, know Christ to reign,
and know his bodily presence; they know his flesh, and are of his flesh and of his bone,
and his spirit, and mind, and power, who hath all power in heaven and earth given to him;
they are over the devil, over the antichrists, false prophets, beast,
and mother of harlots, reign above their power, triumph, and tread upon their power;
and this is known by the light within.
And now doth Christ reign in his saints, and the paradise of God is known, and Eden,
where all things are sanctified, and blessed, and good; where there is no curse,
but blessing.
And he that went out of this, earthly Adam, transgressed and disobeyed,
which brought the death upon all his posterity.
But who are come in through the obedience of another, the second Adam, Christ Jesus,
who became the curse, and took away the curse, who is the sanctification,
and brings the blessing and redemption,
(by and through whom are many entered into the paradise
of God,) have the right to the tree of life.
And they are not come into this who are yet in the disobedience.
The unbeliever, liar, reviler, whoremonger, and adulterer, hate the light,
in the disobedience, and cannot touch the tree of life,
for the sword turns every way upon them.

[.small-break]
'''

And as for all thy hard expressions and revilings in thy hook,
they come from the disobedience, over which the sword is that keeps it in awe,
over whom goes the higher power,
and that cannot touch nor taste of the tree of life in the paradise of God,
in the Ancient of days.
Thou shalt feel my words to be truth.
