[#ch-28.style-blurb, short="The Church of Christ in Bristol Recovering Her Veil"]
== Robert Simpson, Robert Parnell, John Andrews, Thomas Ewen, Bryan Hanson, and Richard Moon, in their book called, [.book-title]#The Church of Christ in Bristol Recovering Her Veil.# Their principles follow.

[.heading-continuation-blurb]
It is a true word to you: you are recovering the veil more than the life and substance,
that takes away all veils, as your principles in your book make manifest.

[.discourse-part]
_Principle._ You say, '`Now the spirit speaketh expressly,
that in the latter times some shall depart from the faith,
giving heed to seducing spirits, and doctrines of devils.
And also of your own selves shall men arise speaking perverse things,
and draw many disciples after them.
And they went out from us: it is manifest they are not of us.`' 1 John ii, etc.

[.discourse-part]
_Answer._ You have brought these words to show your ignorance;
for the apostles saw such as should '`depart from
the faith,`' and the false prophets and antichrists,
that Christ said should come, John saw were come,
and went forth from them before the apostles`' decease.
They went forth from the church, and departed from the faith,
in which faith the church had unity, and this they apostatized from;
they have had the sheep`'s clothing, and so got up an imagined church with a veil on it,
in the apostacy.
And these were they that drew disciples after them,
who caused the way of truth to be evil spoken of; and the '`seducing spirits,
and the doctrine of devils,`' have been up since the days of the apostles,
which they saw come in before their decease; and such '`went from the faith,
in which is the unity.`' And thus they are in the enmity, destroying, persecuting,
and prisoning one another about religion, church, doctrine, and scriptures,
and Christ`'s, the prophets`', and apostles`' words;
which shows they are out of unity with God, and with the scriptures, and there you are;
and out of the faith that '`works by love,`' by which they
should heap coals of fire on the heads of all the adversaries.
And so this is the dawning of the day, the ending of the night of apostacy;
you who are of the skirts of the great whore are seen,
as you have manifested yourselves by the tale you have told to the world in your book,
who style yourselves, '`the Church of Christ,`' which is made up by the letter.
How want ye the life the saints lived in, that gave forth the scriptures!
Oh! ye want the covering of the spirit of the Lord God.
And now being departed from the faith,
ye are the false spirits and false prophets that Christ said should come,
'`that would get the sheep`'s clothing, but be inwardly ravening wolves,
whose fruits should declare them;`' which John saw were come, which went forth from them,
which led the world after them; and the false apostles,
and Satan`'s ministers and messengers, which the apostle saw come up before his decease.
These, since the days of the apostles, have been the guides and leaders of the world,
and teachers, and gatherers of people into names, into heads, into horns,
whereby one hath been against another; they have gathered people out of peoples,
and brought people to a head, and not to Christ,
and yet all have professed themselves Christians.
So they have had the sheep`'s clothing, but inwardly ravened from the spirit of God,
and so have been wolves, tearing the lambs to pieces, yea,
and many goats and beasts too sometimes,
whose fruits have sufficiently declared them since the days of the apostles,
and in this nation.
And these have deceived the world, and have been the wrestlers against flesh and blood,
strikers at the creature;
such as have '`departed from the faith,`' ravened from the spirit,
gone forth from the apostles, had the sheep`'s clothing,
have been the teachers and gatherers into sects, and names, and heaps;
and every one will cry, '`his church,
his church,`' and all against the light which comes from Christ,
in which the church stands.
But now he is redeeming and recovering that which hath been lost,
since the days of the apostles, in this night of the apostacy.
The light is come, the night is gone, the Lamb and the saints are going on conquering,
and to conquer.
The throne of the Lamb is set up; and all those false prophets, beasts, antichrists,
mother of harlots, great whore, and kings of the earth, and the devil,
are making war against the Lamb and the saints.

Now are all the antichrists appearing, and are in arms,
and rising against Christ and his light.
The Lamb is on the white horse, who slays with his sword,
'`which are the words of his mouth,
and the Lamb and the saints shall have the victory.`' Glory in the highest! and rejoice,
ye holy prophets, over her.

[.discourse-part]
_Principle._ They say, '`The mystical body may sometimes be subject to distempers, and humours,
and wants.`' See page 1.

[.discourse-part]
_Answer._ Are you judges?
Can you judge of the mystical body which the saints are baptized into?
Are the humours, wants, and distempers in the body which the saints are baptized into?
Are they not in your body?
Do you in this divide the word aright?
distinguish things in the ground, and speak aright of things?
And yet ye would not be judged, and say, '`Judge not.`' And is not mystical, spiritual?

[.discourse-part]
_Principle._ You say, '`The scriptures are the word of God.`'

[.discourse-part]
_Answer._ The scripture itself saith,
'`The word is God.`' Christ`'s name is called the
'`word of God,`' and the scriptures are words,
the words of God, the words of Christ,
the declaration which the ministers of the word set forth;
which words end in Christ the word, who fulfils them.
And they are called the scriptures of truth which cannot he broken;
and so ye do not speak as the church did that gave forth scripture.
And the spirit of God was the rule in speaking forth the scriptures,
which brings to know the right use of them again.

[.discourse-part]
_Principle._ They say, '`To call that light in every man Christ,
is to slight Christ`'s glorious person in heaven, and to nullify it.`'

[.discourse-part]
_Answer._ Have you not in this showed your ignorance?
and to be those that went forth from the apostles,
and so are hardened from the spirit they were in; who said,
'`Christ is all in all,`' which '`doth enlighten every man that
cometh into the world?`' And none see the person of Christ in heaven,
but who are in the light that he hath enlightened them withal; yea,
the covenant of light to the Gentiles and heathens as well as Jews,
and so God is not a respecter of persons.
And all that are from this light, are now making war against the Lamb and the saints,
and the accuser of the brethren is cast out,
and the light which enlightens every man who comes into the world, is Christ.

[.discourse-part]
_Principle._ They say,
'`It is a delusion for them that are in the light to see
what men`'s inward states are before God.`' See page 29.

[.discourse-part]
_Answer._ Have ye given yourselves the name '`church of Christ,`'
and is there not a spirit of discerning among you?
Have ye not manifested here that ye are harlotted
from the church of Christ the apostles were of?
And how can ye minister, or teach people, if ye do not discern their states,
how they stand before God?
How can you commend yourselves to every man`'s conscience in God`'s sight?
How can ye present the souls of men to God, and see not how their states are in his sight?
How come ye to have fellowship in the spirit?
How can you, or any, minister to the state and condition that people are in,
and see where they are, and not know how.
they stand in God`'s sight?
In this how have you showed your ignorance of the scriptures,
and the epistles written to the saints,
which speak to the state and conditions the saints were in!
Ye have a name, but how have ye declared yourselves dead from the life!
How have ye stained your own glory, and marred your own beauty,
and set yourselves out of the steps and paths of the church of Christ!

[.discourse-part]
_Principle._ Simpson saith, '`If my heart deceive me not,
I could wish that God would recover you out of the devil`'s
snare.`' See page 40. And ye speak of '`breaking of bread,
and ordinances, and the Lord`'s supper, and baptism.`' See page 35.

[.discourse-part]
_Answer._ The prayers of the faithful that are in the spirit, are acceptable;
but he that doubts, knows not his own heart, and prays without discerning,
being out of that which purifies it.
And for baptism, and ordinances, and the Lord`'s supper,
and the bread that the saints broke,
ye have all been ignorant of them in this night of apostasy since the days of the apostles.
Paul told the Corinthians, '`what he had received of the Lord, he delivered unto them;
and as oft as they did eat that bread, and drink that cup,
they did show forth the Lord`'s death till he came,`'
and they were to do it in remembrance of him.
And afterwards the apostles wrote again to the said Corinthians, and told them,
'`the light that shined in their hearts would give them the light of the
knowledge of the glory of God in the face of Christ Jesus;`' and said,
'`while we look not at things that are seen, but at things that are not seen:
for the things that are seen are temporal, (bread, wine,
and water are seen,) but the things that are not
seen are eternal.`' And bids them examine themselves,
and prove their own selves, and said, '`Know ye not that Christ Jesus is in you,
except you be reprobates?`'

[.discourse-part]
_Principle._ He saith, '`He hath been a preacher of the gospel at Bristol and Wells,
and he hath not need to seek a proof of any man.`' See page 43. And he saith,
'`I am no preacher, to bid every man turn to the light within him,
neither did I ever read or hear,
that any of the apostles or holy men of God preached
such a gospel.`' And they said of Sarah Latchet,
who had been one of them, and was excommunicated,
'`it was fittest to send her to Bridewell.`'

[.discourse-part]
_Answer._ This was not the work of the ministers of the gospel, to wrestle with flesh and blood,
which is yours.
And they in the sight of God had witnesses, and they could seek them;
which thou sayst thou needs not.
And they turned people from the darkness to the light;
and Christ bid them '`believe in the light while they had it,
that they might become the children of the light.`' And the apostle`'s doctrine was,
'`that the light that shined in their hearts,
would give them the light of the knowledge of the glory of God
in the face of Christ Jesus,`' and this thou never heardest of,
as thou sayst.
And thy gospel that is not this, and agrees not to the apostles,`' is another,
and so accursed.
And the saints were one another`'s epistles written in one another`'s hearts,
read and seen of all men.
And thou hast been a bad preacher at Wells and Bristol, that knowest not the light.

[.discourse-part]
_Principle._ They say, '`A man may be a christian, a believer, a converted soul,
he may be in Christ,
and yet not have received the spirit of sealing and establishing,`' page 53.

[.discourse-part]
_Answer._ This is like the rest of their doctrine, who, being out of it themselves,
are not able to judge of the state of babes, believers,
and converted souls who are in Christ.
For they that are in Christ have the spirit; and they that are converted,
are converted by the spirit.
And he that believeth, cometh to be sealed with the spirit of promise.

[.discourse-part]
_Principle._ They say,
'`The light in every man is a notion,`' and yet say '`they seek God by prayer,
solemnly.`' And they shut up the kingdom of heaven against men,
that bid all men turn to the light within them,
and from the believing on the person of Jesus Christ,`' page 60.

[.discourse-part]
_Answer._ None open the kingdom of heaven to all men,
but who turn people to the light '`which Christ Jesus hath enlightened
every man with that cometh into the world.`' And none believe in Christ,
but who believe in the light which Christ, the light,
'`hath enlightened them with;`' and such have the witness in themselves,
and can set to their seals that God is true; and they see their sanctification,
justification, and redemption.
And none ever pray the acceptable prayer of the Lord,
but who are in the light that cometh from Christ;
and such call not the light '`a notion,`' for all
notions are among such as are out of the light,
'`with which Christ doth enlighten every man that
cometh into the world.`' They are from the rock,
the foundation, and sanctification, and see not Christ.
And this is not to deny Christ, but receive him, and believe in him.
And all upon the earth are antichrists,
that deny the light '`that doth enlighten every man
that cometh into the world,`' and are from it..

[.discourse-part]
_Principle._ And as for your speaking of judging, and '`not to judge before the time,
until the Lord do come,`' etc.

[.discourse-part]
_Answer._ That was spoken to the Corinthians, and the apostle adds,
'`who will bring to light the hidden things of darkness,
and make manifest the counsels of the heart.`' Now
the same apostle said to the same Corinthians,
'`that God would dwell in them,
and walk in them,`' and they were not to judge before the time until that he did come.
And he told them the saints should judge the world;
and the world should be judged by them.
Now where the Lord is come, such as have the son, and the Father,
and bring this doctrine, they are to be received;
and they know where sin and transgression are finished, and where it is standing.
So if any man have an ear to hear this, and can receive it, let him.

And as for the rest of the things in your book,
your silence might have covered your shame,
'`for every man`'s words shall be his burden.`' Therefore, he that hath the word of God,
speaks that which shall be so, which now comes to be richly known,
and is known among the saints and believers,
the true church which is come out of the apostacy, since the days of the apostles,
to that the apostles were in.
