[#ch-29.style-blurb, short="A Discover of the Quakers"]
== Jonathan Clapham, '`a labourer of the gospel,`' as he saith, and William Jenkin: their book to the protector, called [.book-title]#A Discovery of the Quakers`' Doctrine.# Their principles, etc.

[.discourse-part]
_Principle._ He saith, '`I dare not say that I am infallible,
as the pope and the Quakers.`' And '`the magistrate
in this external politic kingdom is a mediator,
though he is no officer nor magistrate in the spiritual kingdom of his church.
And if this be received by magistrates,
that they have nothing to do with the worship of God, Christ is little beholding to them.
Then they may protect the worship of Mahomet, as well as Christ`'s.`' And yet ye say,
'`That the magistrate is the officer of Christ.`' See his epistle to the protector.

[.discourse-part]
_Answer._ How is it, then, if the magistrate be no officer of the church,
that you make use of magistrates to prison, to persecute, to give you tithes,
and to quench the spirit when any thing is revealed to '`another that sits by?`'
Were not the magistrates in all ages stirred up by the blind priests,
prophets, and teachers, to persecute and prison such as they judged to be blasphemers?
And so, did not all the saints in all ages suffer, not as for truth,
but as for blasphemy; yea, by them that had the form, covered with the sheep`'s clothing?

Now the magistrate that is in the power of Christ, is beyond an external kingdom,
and sees over the kingdoms of the world; and as he is a help-governor for Christ,
he is a member of the church, and knows who worship God, and who worship idols.
And who worship God are in the power of God,
in that which sees over all external kingdoms;
that is the higher power which the soul must be subject to,
and that is the true magistrate.
And thou not being infallible, art not in the spirit, and so art not a minister,
and art not able to judge of powers, nor magistrates, nor kingdoms, nor churches.
For who is in the infallible, is in the spirit that Christ was in,
and the apostles and prophets that gave forth scriptures.
But we say, that thou, nor the pope, thy elder brother,
(in the apostacy from the apostles,) are either of you infallible,
nor in the infallible spirit that the apostles were in;
but ye are both erred from it in the apostacy, as your fruits declare.

[.discourse-part]
_Principle._ They say, '`The magistrates are to protect the church from the ravenous wolves;
for ye are to stop the freedom of the Quakers in your dominions, and their license,
and the Lord bless your highness.`' See his epistle to the protector.

[.discourse-part]
_Answer._ Before, thou saidst they were not officers in the spiritual church,
and now wouldst thou have them to limit and quench the spirit?
and to be your executioners, by telling them the Quakers seduce people?
Ye have manifested your own spirits, that ye have not the spirit to resist their spirits,
but are crying to the magistrates.
And did John bid the saints call to the magistrates, to the outward powers of the earth,
to try seducers, or did the saints so?
And have not you manifested yourselves to be them that cry,
'`help men!`' against Christ and the saints?
and cry to the mountains to cover you; crying to the magistrates,
'`Help men of Israel! these are the men that will turn the
world upside down,`' and so go to the arm of flesh?
Have not ye here showed your spirits to be them that should come,
who were inwardly ravened, who John saw were come,
and to be the wolves in sheep`'s clothing, and the blasphemers; such as you cannot tear,
yourselves, you would have the magistrates to tear.
But the Lord hath opened an understanding among many of them that they see you.

[.discourse-part]
_Principle._ He saith, '`We dare not contest with the Quakers, they teach men,
by minding the light in the conscience, to attain a moral righteousness,
that is the highest; and as if they had accomplished it wholly now,
and not to be fulfilled in another world.`' See epistle to the protector.

[.discourse-part]
_Answer._ We do believe that you are not able to resist the Quakers,
who have appeared in that that cannot he shaken.
Therefore, is it not a shame to you to say you are a church and ministers,
and to say the magistrate is no officer in the spiritual church;
and yet fly to the magistrate, and tell him you dare not contest with the Quakers,
and bless him if he will but stop them!
Think ye not the magistrates will see you in these things?
And the light which Christ, the righteousness of God,
'`hath enlightened every man that cometh into the world,
withal,`' leads man to the end of the righteousness of the law,
that comes to be fulfilled in all its righteousness whatsoever.
And so the light is too heavy for thee, and too hard for thee;
and it is the precious stone thou stumblest at.
And things fulfilled in another world, the prophecies, the parables, the types,
the figures, the shadows, the gifts, the revelations, the dispensations,
these things were in this world manifested.
And who comes to Christ, who is the end of all,
comes into the power of the world that hath no end.
What is there to fulfill there, in the world that hath no end.
Things are to be fulfilled in this world, that hath an end.
And thus thou hast showed thy ignorance.

[.discourse-part]
_Principle._ He saith, '`The scripture is the word of God.`' And saith,
'`Christ is not properly the word,
but figuratively,`' page 3. '`And the scripture is in more proper sense, without figure,
called the word of God.`' He saith,
'`Without the scripture we do not know how to worship God aright, and serve him,
and therein attain to eternal life.`'

Again they say, '`God is not pleased to use this way of immediate revelation now:
neither indeed is it the work of God`'s holy spirit to discover
things unto us now immediately,`' page 5.

[.discourse-part]
_Answer._ Christ`'s name is called '`the word of God`' properly, and not figuratively,
and more properly than the scripture, as in the Revelations.
And the scriptures are the words of God, and words which Christ the word fulfils.
So it is proper to call the scriptures the words of God,
and proper to call Christ`'s name the word of God,
and '`the word that became flesh,`' that is proper scripture.
And they that had not the scriptures, worshipped God, before the scriptures were written,
as Abraham and Enoch, and others; and they attained to eternal life.
And if people have all the scriptures,
and not the spirit which was before they were given forth, they want the standing rule;
they cannot know the scriptures; they cannot worship God aright;
they cannot find eternal life; they have not unity with God;
neither do any worship God aright, but they who are in the spirit that gave them forth.
And we do believe you,
that immediate revelations now by the holy spirit of God revealing things to you immediately,
ye have not; and you say it is not the work of God`'s spirit now, nor the way of God now, etc.
You that have ravened from the spirit of God inwardly,
have been the wolves which Christ said should come, which John saw were come,
after whom the world hath gone, and ye have burst into names, and heads, and horns,
and sects.
And the power was given to the beast, and the false prophets;
and the great whore hath corrupted the earth.
All nations have drunk her cup of fornication, and the kings of the earth.
So they have fled to the kings for help against the saints, and against the Lamb,
but the Lamb and the saints shall have the victory.
And so when you have been ravened from the spirit of God,
it hath not been likely ye should attain to immediate revelation by the spirit of God.
But now who are come to the Lamb, are come to that ye have ravened from,
they witness immediate revelation.
They are come to that the apostles were in, the spirit of Christ, the spirit of God;
they witness immediate revelation.
Who are come into the fear of God, the things of God are revealed unto them;
who are come into the spirit of God, it reveals to them the deep things of God.
So you that deny immediate revelation by God`'s holy spirit now,
and discovering things to you immediately,
you have showed your spirits to be the false spirits,
unclean spirits that be in the earth,
like the frogs that go out of the mouth of the beast and the false prophet,
which was discovered by John, and revealed to John, discovered and made manifest;
and now with the same holy spirit of God are all you apostates
revealed and discovered to the children of the light,
to the lambs and the saints,
who witness the spirit of God which reveals the things of God to them,
and immediate revelation.
The false prophets, false apostles, false teachers,
in their false prophecies and teachings, who had gotten the form, ever denied the power,
and immediate revelation by God`'s holy spirit.
And was it not they that cried to the powers of the
earth for help against the saints in all ages,
which were discovered and judged by the spirit of God, and must go into the fire.

[.discourse-part]
_Principle._ He saith, '`The scriptures are able to make wise unto salvation,
and they are a more sure word of prophecy than any voice we can hear from
heaven,`' page 6. '`And we will call them the word of God,
whether the Quakers will or not, and we are to go to the law and testimony,`' page 7.

[.discourse-part]
_Answer._ And in this ye are contrary to the ministers of the word,
who call the scriptures the words of God, and Christ the word;
and call the scriptures a declaration and a treatise,
which Christ the word came to fulfill.
And the law and testimony, which you say is the Old and New Testament, many may have,
and yet stand against '`the law`' which '`is light,`' as saith Solomon;
and stand against '`the testimony of Jesus which is the spirit
of prophecy,`' and crucify them that are in the law and testimony,
as witness the ravening wolves that have had the sheep`'s clothing,
but inwardly ravened from the spirit; which Christ said should come,
and John saw were come, went out from the apostles, whom the world have since gone after.
And many may have the scripture, and stand against the voice from heaven,
as the Jews did against him that spoke from heaven, who was more sure;
he that spoke from heaven, was the end of the scriptures, and comes to fulfill them.
And the scriptures are not able '`to make wise unto salvation,`' as you say,
who leave out the faith; but through faith they are.

[.discourse-part]
_Principle._ '`Let the Quakers show wherever Christ or the
apostles bid people look to the light within them.
And the Quakers say they write from the spirit of the Lord,
and speak from God immediately and infallibly, as did the apostles,
and doth not this bring them under the curse in the revelations?`'
page 8. '`And say the letter is a dead and killing letter,`' these
he calls '`wicked errors.`' And '`to say the light within is sufficient,
is an old Popish argument.`'

[.discourse-part]
_Answer._ The light which every man that cometh into the world is enlightened with,
is the salvation to the ends of the earth, and sufficient;
for he that believes in it shall have the light of life,
and come to witness the law of God in his mind and in his heart; and the new covenant,
in which he shall not need to say, '`Know the Lord.`' And the letter of scripture,
paper and ink, is a dead letter: and thou and you all that speak and write,
and not from God immediately and infallibly, as the apostles did, and prophets,
and Christ, but only have gotten the words, you are all under the curse,
in another spirit, ravened from the spirit that was in the apostles,
only have had the sheep`'s clothing, inwardly ravening wolves;
so deceived the world and the nations, and have been held up by the powers of the world,
the powers of the earth.
And the kings of the earth have drunk the cup of fornication,
and they were like to maintain that which they have drunk.
And so power hath been given to the beast over all kindreds, tongues, and nations,
and they should make war against the Lamb and the saints,
and continue it till the words of God were fulfilled.
And the apostles told the Corinthians,
'`that light that shined in their hearts would give them the light
of the knowledge of the glory of God in the face of Christ Jesus.`'
And so all people upon the earth that have gotten a knowledge,
if the light that has shined in their hearts hath not given it them, what they know,
they know naturally; in these things they corrupt themselves.
And so thou and you that are ignorant of the apostles`' doctrine,
the light that gives people the knowledge,
and the immediate infallible spirit that the apostles were in,
and that the scriptures were given forth from, are, together with the pope,
in another spirit than the apostles were in,
comprehended by the spirit that gave forth scriptures.

[.discourse-part]
_Principle._ '`And what a dreadful judgment is upon them that leave the scriptures
to look to the light within them,`' page 9. '`And many deceivers should
come into the world that confess not Christ come in the flesh,
receive them not into your houses.`' And '`the man Christ
is testified against by the light,`' page 13. And he saith,
'`They publicly deny the resurrection of the dead body.`' And saith,
'`The sufferings of Christ in the flesh were but an example and a figure.`'

[.discourse-part]
_Answer._ Christ ended all figures in suffering, and examples, and patterns;
yet he is the saints`' pattern and example, as the scripture witnesses,
and there is no other example nor pattern to be heeded but Christ alone,
which they are to learn of.
But to say he is nothing but a figure, for that thou, and you all, will be judged:
for he ended all figures and is the resurrection, and the life both.
'`And thy dead body shall live with my dead body,`' this is scripture.
And they that said the resurrection was past in the days of the apostles,
overthrew the faith of some.
That which overthrew the faith, denying the resurrection, kept the seed in death,
where it hath been in you all since the days of the apostles; for who are of faith,
are of Abraham, of Christ according to the flesh; and so if the dead arise not,
their preaching is vain, and their faith is vain.
So I say, mortal must put on immortality, and corruption must put on incorruption.
'`The first man was made a living soul, the second was made a quickening spirit;
there are earthly bodies,
and heavenly bodies,`' and there is a resurrection of the just and unjust,
the one to eternal life, the other to condemnation.
And the judge is '`the man Christ Jesus,`' to judge the quick and the dead,
who both died and rose again, that he might be God of the dead and the living.
And the light which every man hath that cometh into the world,
doth not testify against Christ; and the light doth not bring to deny the scriptures,
but to own them.
And none own them aright, nor Christ, but who are in the light which cometh from him.
And all that deny the light that doth enlighten every man, etc. are the wolves,
and the false prophets, and antichrists, that have gotten the sheep`'s clothing;
and such cannot be received into the houses of the saints,
that are from the light which every man is enlightened withal.
And none confess Christ come in the flesh,
but who are in the light which Christ hath enlightened them with.
And so now all professors, and teachers upon the earth, and kings of the earth,
are ravened inwardly from the light which Christ enlightened them all with;
standing against the light, and the Lamb, and the saints, that are in it;
and are not to be received into the houses of the saints, neither to bid them God speed;
for they are out from God that are out of the light
which Christ the son hath enlightened them with.

[.discourse-part]
_Principle._ And he saith, '`Christ hath a human reasonable soul.`' Again, '`Christ,
the eternal son of God, distinct from the Father eternally; before he was made flesh,
his spirit was distinguished from the Father, and was the son from eternity;
and not only when he was manifested by descending on Christ in the likeness of a dove,
or by falling upon the apostles like cloven tongues,`' etc.
See page 17.

[.discourse-part]
_Answer._ Christ saith he is in the Father, and the Father is in him,
and he will send them the spirit of truth, the comforter,
that proceeds from the Father and the son; and Christ saith,
he was glorified with the Father before the world began; and yet ye say,
the son is distinguished from the Father from eternity.
And the son saith he is in the Father, and the Father is in him.
And you say the spirit is distinguished from the Father and the son from eternity,
and Christ saith it proceeds from him and the Father,
and he is the God and father of the spirits of all flesh,
and the substance of all things.
And is not a human soul earthly?
for you say that Christ had a human soul, and is not human earthly?
and hath a human body, and is not a human body an earthly body?
Is not his body of the seed of Abraham according to the flesh?
and is not his body a glorified body?
Was not the first man of the earth, earthly, and had a human body,
the second man the Lord from heaven?
And is not the soul immortal, which cometh out from God who is immortal,
and goes into God again?
and is not human, or earthly, mortal?
And are there not three that bear record in heaven, the Father, the word, and the spirit,
and are not they all one?
How then are they distinct?
And there are three that hear record in earth, the spirit, the water, and the blood,
which agree in one.
And Christ saith, '`I and my Father, are one;`' and '`I in the Father,
and the Father in me,`' and he is in the saints, and so not distinct.

[.discourse-part]
_Principle._
He saith, '`It is impudency in the Quakers to deny the word trinity, and three persons.
And the church ever denied such as deny the doctrine of the trinity.`' See pages 18, 19.

[.discourse-part]
_Answer._ As for the word trinity, and three persons, we have not read it in the Bible,
but in the common-prayer-book, or mass-book, which the pope was the author of.
But as for unity we own it, and Christ being the brightness of the Father`'s glory,
and the express image of his substance (of the Father) we own;
that which agrees with the scriptures, and for that which the scripture speaks not,
which men speak and teach for doctrine, their own words,
that the scriptures speak not nor teach, such the scriptures shut out, and we deny.

[.discourse-part]
_Principle._ He saith, '`That is the weak, ignorant, dark, and the wicked sect of the devil,
that maintain an equality with God; the soul to be one being with God,
or part of God.`' And saith, '`The Quakers say,
there is no scripture speaks of a human soul, and the soul is taken up into God,
and God is all in all.`'

[.discourse-part]
_Answer._ The assembly, or synod of priests, put forth a catechism,
and say that the holy ghost and the son are equal with the Father in power and glory:
and this they put forth that people should learn it: then,
if any come to witness the holy ghost,
they come to witness that which is equal in power and glory with the Father?
if any come to witness the son of God revealed in them, (which he that hath not,
hath not life,) do they not come to witness him who
is equal in power and glory with the Father?
This is your own catechism.
And is it blasphemy to confess your own words, that ye have given people to learn?
God breathed into man the breath of life, and he became a living soul; God,
who hath all souls in his band.
And is not this +++[+++breath of life]
that cometh out from God, which is in God`'s hand, part of God, of God, and from God,
and goes to God again?
which soul Christ is the bishop of.
And dost not thou speak of a human, soul, an earthly soul, and is earthly, immortal?
cannot it, die nor be killed?
And is not that which came out from God, which God hath in his hand,
taken up into God again, which Christ the power of God is the bishop of,
is not this of God`'s being?^
footnote:[George Fox says: "`God breathed into man the breath of life,
and he became a living soul; and is not this of God, of his being, etc.
And is not this, that comes out from God, part of God?`"
G+++.+++ F. intends that divine life, power, and virtue,
by which Adam in soul and body came to live to God: not '`that the soul of man,
as a mere creature, created capacity,
is of God`'s own being and substance.`'`" [.book-title]#Wm. Penn`'s Works, vol.
2,# pp.
521, 522,]
And doth not the scripture say,
'`God is all and in all?`' And how dost thou here divide the word of God aright,
who showest so much ignorance of the letter of scripture?

[.discourse-part]
_Principle._ He saith, '`It is a wretched doctrine to say men have not a human soul in them,
and to say that the soul is a part of the divine essence.`'

[.discourse-part]
_Answer._ Is not that of God that came out from him?
And is not the earthly and human of the ground?
and is not that mortal?
and is that which is immortal human?
And dost thou say it is human, and is not that earthly?
And where doth the scripture of the prophets, Christ or the apostles,
tell people of a human soul; and of Christ having a human body in heaven?
And doth not the apostle speak of his glorified body?

[.discourse-part]
_Principle._ He saith, '`That God should dwell in his saints, and Christ inhabit in believers;
how can this be?
the heaven of heavens cannot contain him, how much less shall the strait heart of man?`'

[.discourse-part]
_Answer._ The scripture saith '`God will dwell in men, and walk in men,
and Christ that fills heaven and earth is in you, except ye be reprobates`' and so,
in this thou hast showed thyself one not able to divide the word aright.
And the bodies of the saints are the temples of God, and God will dwell in them,
and walk in them, and he will be their God, and they shall be his people.

[.discourse-part]
_Principle._ He saith,
'`Nor is it an essential indwelling of the divine nature in God`'s people,`' etc.

[.discourse-part]
_Answer._ Doth not the apostle say, the saints were made partakers of the divine nature?
and that God dwells in the saints, and Christ is in them, except they be reprobates?
And do not the saints come to eat the flesh of Christ?
And if they eat his flesh, is it not within them?

[.discourse-part]
_Principle._ He saith, '`God dwells not in the saints as a personal union,`' etc.
See page 22.

[.discourse-part]
_Answer._ How come the saints then to eat of his flesh; and to be of his flesh and bone?
and to know God dwelling in them?
and to have unity with the son and the Father?
and to be of his body, which is the church, of which Christ is the head?

[.discourse-part]
_Principle._ '`To say a man is justified and made righteous
by God`'s putting righteousness into us,
and by righteousness wrought in the creature,
confounds justification and sanctification,`' etc.
See page 25.

[.discourse-part]
_Answer._ The apostle brought people to the faith that was in their hearts,
by which they were justified, for with the heart man believes unto righteousness, etc.
And they were to believe in the light, that was, Christ.
And the light,
that shined in their hearts gave the light of the knowledge of
the glory of God in the face of Christ Jesus their saviour.
Now justification by the works of the law, was,
'`do this and live.`' They were to circumcise the children; if they did not,
they were to be cut off: and they were to keep the law.
But the faith of Christ ended the works of the law:
for it took away the nature that the law went upon.
Now the Papists, and priests, are out of the works of the law,
and the works of faith that works by love;
for they are slaying one another about religion, though they pretend works,
and this was ever out of the faith of Christ Jesus, to kill one another about religion.
Now the apostles were in the works of faith,
who neither prisoned nor persecuted any that were contrary minded,
nor wrestled against flesh and blood, but against the power that captivated creatures.
And, so all this work about works doth show you and the Papists
both to be out of the faith that works by love,
where love should overcome all things, and bear all things.
I do not measure priests and professors, nor Papists,
by the works of the law which the apostle speaks of,
which the false teachers were bringing people to in the days of the apostles.
Neither do I compare or measure Papists, or priests,
with the works of '`faith that works by love,`' that becomes all to all,
for the winning some of them.
Papists, and priests, and professors will kill one another about their faith,
which is not the faith that works by love;
but contrary to the apostles`' and Quakers`' faith.

[.discourse-part]
_Principle._ He saith, '`Our warfare cannot be expected to be over as long as we are in the body:
and the best of saints do not live free from sin,`' page 27.

[.discourse-part]
_Answer._ The apostles said they were made free from sin,
and that the blood of Jesus Christ the son of God cleanseth us from all sin;
and such as witnessed the everlasting covenant of God,
that blotted out their sins and transgressions.
And they witnessed the one offering that perfected forever them that are sanctified.
And the saints witnessed the kingdom of God, which stands in righteousness, peace,
and joy in the holy ghost, and were new creatures, the old man being put off,
and they were more than conquerors.
So thou art ignorant of the scriptures,
and it is the doctrine of devils to preach that men shall have sin,
and be in a warfare so long as they are on earth;
that is not the doctrine of Christ which brings people to the faith,
which gives the victory, in which they have unity one with another, and please God.

[.discourse-part]
_Principle._ He saith, '`To witness heaven within and hell within, and the resurrection,
is the mystery of iniquity,`' page 31.

[.discourse-part]
_Answer._ Which shows thou never knew heaven in thyself, nor hell there,
nor Christ the resurrection and the life,
which they are blessed that are made partakers of the first resurrection,
on them the second death shall have no power.
And the scriptures do witness heaven within.
And if Christ that was offered up, the resurrection and the life, be not within thee,
thou art a reprobate.

[.discourse-part]
_Principle._ He saith, '`We shall have incorruptible, powerful, glorious,
and spiritual bodies;`' and yet they say '`Christ is in heaven with a human body,`'
(which is earthly,) see page 34. Again '`the spirit can enter into heaven,
while the body is upon the earth,`' etc.
And he saith, '`the fourth commandment commandeth the keeping of a seventh day:
and he that breaketh the least commandment and teacheth men so to do,
is least in the kingdom of heaven,`' page 41.

[.discourse-part]
_Answer._ Have not all the priests and teachers in England denied the Jews`' sabbath,
the seventh day?
and do not you work on it?
and do not you meet together on the first day of the week?
and do not you all teach men to break the commandment there?
And you keep markets and fairs on the seventh day, the Jews`' sabbath;
ye meet together on the first day of the week, which is the eighth day,
and so not one in seven.
And if the saints sat in heavenly places with Christ Jesus;
and if the saints in heaven must have a glorious body, and Christ a human body,
(which I say is earthly,) how doth this agree with scripture,
that says Christ`'s is a glorious body?
And is it an earthly body the saints eat, when they eat the flesh of Christ?
And are not people in their first state, in the earthly,
before they come to witness a spiritual body like unto his glorious body?
How do you divide the word aright?
And they that have the spirit of Christ, their spirits are in heaven,
and they have unity with the Father.

[.discourse-part]
_Principle._ '`We have no such immediate converse with God now,
as to see him face to face,`' page 42.

[.discourse-part]
_Answer._ We do believe you have not,
who are gone from the spirit that the prophets and apostles were in,
ravened from it since the days of the apostles in the apostacy,
and so are not in the counsel of God; and are out of his teaching and instruction,
and so far from having fellowship with God;
for who have fellowship with him come to see him.
And you are not of Abraham`'s seed who saw God face to face,
but are of the Pharisees`' stock, who never saw his shape, John v.

[.discourse-part]
_Principle._ And you say, '`In the last days false prophets should arise,
and show signs and wonders; and if it were possible they should deceive the elect.
And the coming of the man of sin is after the working of Satan, with all power,
and signs, and lying wonders,`' etc. page 44.

[.discourse-part]
_Answer._ Christ said, the false prophets and antichrists should come, which John saw were come;
yea, many antichrists were gone out into the world.
And the apostle Paul saw the man of sin before his decease,
the coming of him with the lying signs and wonders;
which man of sin since the days of the apostles, in this night of apostacy,
has ruled and reigned, with his lying signs and wonders;
and these are not the true signs, but lying.
And when they were ravened from the spirit of God they got
the sheep`'s clothing while inwardly ravening wolves,
'`which if it were possible,
would deceive the very elect;`' which went forth from the apostles in the apostacy;
and since they have deceived the nations, the wolves, the inwardly raveners,
though covered with the sheep`'s clothing.
And here these things have been among you in the apostacy:
and the apostates have reigned and ruled,
and have had the dominion since the days of the apostles.
But now with that which ye all have ravened from, are ye made manifest and comprehended.
So this man of sin, with his lying signs and wonders, who ravened from the spirit of God,
as the devil did, who went from the truth,
is he that compels all his members to plead for the body of sin while they be upon earth,
and so to keep them out of the faith of God`'s elect,
that gives the victory over the world.
And such he cannot deceive, nor any of his members,
that are ravened from the spirit of God.

[.discourse-part]
_Principle._ He saith, '`The Quakers`' despising the fashions of the world,
contemning the honours and pleasures thereof,
and their sober carriage and deportment among men,
and willingness to suffer;`' all these he calls wickedness.`' See pages 49, 50.

[.discourse-part]
_Answer._ But it seemeth this practice of denying the fashions of the world,
and contemning the honours and pleasures thereof, and their sober carriage,
offends him and the world, and the rest of the priests and professors,
and the denying the lusts which they are in.

[.discourse-part]
_Principle._ He saith, '`The devil is not an adulterer,`' page 51.

[.discourse-part]
_Answer._ Did the devil abide in the truth?
Did not he go out of it?
And are not all that go out of the truth with him, adulterers, who begets his own image,
and is the foundation of adultery?

[.discourse-part]
_Principle._ He saith, '`The light that doth enlighten every man that cometh into the world,
is a natural light, or law,`' page 56.

[.discourse-part]
_Answer._ Which light, Christ Jesus, is the end of the law,
before any natural light was made or created;
for all things that were made were made by him,
and he doth '`enlighten every man that cometh into the world.`'

[.discourse-part]
_Principle._ He saith, '`the light will not bring men to salvation,`' page 56.

[.discourse-part]
_Answer._ The light which doth enlighten every man that cometh into the world, is Christ,
the '`salvation to the ends of the earth.`'

[.discourse-part]
_Principle._ He saith again,
'`The light is not sufficient to lead men to salvation,`'
page 60. '`And to witness sanctification within,
and justification there, is to confound justification and sanctification.
And grace and justification is a created thing, and the light within is mere darkness,
which the Quakers speak of.`' See page 61.

[.discourse-part]
_Answer._ The light which every man that cometh into the world is enlightened with,
comprehends all darkness, and leads out of it,
and there is no occasion of stumbling in it; for, '`as many as receive him,
to them he gives power to become the sons of God.`' And the light is not darkness;
but he that saith the light is darkness, is out of the light, in the darkness.
And justification and sanctification being within, doth not confound it without,
but it is the same that is within that is without.
And grace is the gift of God, and sanctification both, Christ Jesus,
who was before any creature was created, and the grace comes from the throne.

[.discourse-part]
_Principle._ He saith,
'`They are the unestablished people that are running after every way of error,
that own the Quakers in these nations,`' page 62.

[.discourse-part]
_Answer._ In that the nation will witness against thee;
for they that own the Quakers are known to have been the most knowing,
seeking people that have been in the nations, and the most sincere people;
and none come out of error, but who come to the Quakers`' light which they follow,
which is Christ.

[.discourse-part]
_Principle._ He saith, '`That Christ hath a human created soul.`' See page 63. Again,
'`And the light in the conscience to be Christ is a false doctrine.
And the Quakers seek to bring people from all other
teaching but the light within them,`' page 65.

[.discourse-part]
_Answer._ The soul of Christ is witnessed: but to say it is human, earthly, and created,
(when the scripture doth not teach us that doctrine,)
we cannot believe nor own your words,
but deny them.
And Christ is the light in the conscience,
which doth enlighten every man that cometh into the world,
who was before any creature was; which he that receiveth comes to him to be his teacher,
and feels him reign.
And all men must come to the light which Christ hath enlightened them withal,
who is the covenant of God, to feel the law written in their hearts, and in their minds,
to bring them off all other teachers, whereby they need not teach one another, nor say,
'`know the Lord.`'

[.discourse-part]
_Principle._ He saith, '`Men may be called of men master, and it is but a cavil to deny it.
And they may deny to be called father, as well as master,`' etc.
See page 68.

[.discourse-part]
_Answer._ Thou hast in this denied the doctrine of Christ, and slightest it, who saith,
'`Be not ye of men called master; for ye have all one master, which is Christ,
and ye are all brethren.`' And thou hast showed thyself out of the brotherhood;
and there is a birth to be born, which can call no man father upon earth,
which thou art ignorant of.

[.discourse-part]
_Principle._ He saith, '`There is lawful respect of persons,
and it is said God himself is the respecter of persons:
and the Quakers overthrow all authority, because they do not respect persons,`' page 71.

[.discourse-part]
_Answer._ '`God is not a respecter of persons,`' as saith the apostle,
for his covenant he gives to the Gentiles as well as to the Jews.
And the faith of God`'s elect is held without respect of persons;
and he that respects persons commits sin, and transgresseth the law.
And so thou dividest not the word aright.

[.discourse-part]
_Principle._ He saith, '`False prophets shall arise, and damnable heresies,
and many shall follow their pernicious ways,
by which the way of truth shall be evil spoken of.`'

[.discourse-part]
_Answer._ The apostles saw them come up,
the false prophets that brought in the damnable heresies, that were, covetous,
etc. and many followed their ways.
And the false prophets go from the light that Christ hath enlightened them with,
and raven from the spirit, and get the sheep`'s clothing, and through their covetousness,
make a trade of that: and you are such as cause the truth to be evil spoken of,
who are come up, since the days of the apostles.

[.discourse-part]
_Principle._ '`And the Quakers are not to be received into their houses, nor bidden God speed,
and such as creep into houses, lead silly women captive, laden with sin,
and led away with divers lusts.`'

[.discourse-part]
_Answer._ The apostle saw such as crept into houses,
and such as transgressed the doctrine of Christ,
that were not to be received into houses;
and saw the deceivers that walked after their ungodly lusts,
before the apostles`' decease; and such as kept people always learning,
and never able to come to the knowledge of the truth, as is manifest now in the world;
they are learning 40, 50, or 60 years,
and yet there is a cry among them that they must have the body of sin,
and live in their sins while they be upon the earth, and that none can be without it;
and this is the height your doctrine leads to,
which is now in the mouths of all people that are
under your teaching that teach that doctrine.
And yet you will say, the work of the ministry is for the perfecting of the saints,
to the edifying of the body of Christ,
till all come into the unity of the faith unto a perfect man,
unto the measure of the stature of the fulness of Christ!
And this work ye have denied yourselves to be in;
but how should it be otherwise with such that are as Jannes and Jambres?
that have ravened from the spirit of God inwardly, that went forth from the apostles,
that are covetous, that keep people '`always learning,
and never able to come to the knowledge of the truth.`' So you are they that keep people
from the light that doth enlighten every man that cometh into the world,
and keep them in spiritual Egypt, Sodom, and Gomorrah, where they are always learning,
having the form of godliness, and never able to come to the knowledge of the truth;
and this to you all will be a sad cup at last.

And as for all thy lies and slanders in thy book, which are not worth mentioning,
they will come sadly upon thyself one day for the
grievous lies thou hast uttered in it unto the nation;
but thousands in the nation, that are not under the name of Quakers,
know and see the contrary of what thou hast published; they will fall upon thy own self,
and be thy own burden.
And then thou shalt say, when thou feelest thy own works burn,
thou hadst better have been silent, and not have published forth thy folly,
and made thy name to stink, and brought thy name upon record,
who hath made lies thy refuge; but the hail is come, and coming,
that will sweep them away.
