[.style-blurb, short="A Vindication of the Scriptures and Ministers"]
== William Thomas, called Minister of the Gospel of Ubley, his book called [.book-title]#A Vindication of the Scriptures and Ministers.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`Christ directs to look for life in the scriptures,
because they testify of him; and that the scriptures are the ground of faith,
and the saints`' rule.`' And again, '`We are justified by Christ without us,
and not within us.`' See his epistle.

[.discourse-part]
_Answer._ Many had the scriptures, and searched them, and found not life in them,
for Christ is the life; and if men have all the scriptures, and have not Christ,
they have not life.
And so Christ did not say they should have life in the scriptures; but he saith,
they thought to have life there, and that they testified of him,
'`and they would not come to him that they might
have life.`' How ignorant art thou of the scriptures,
and of Christ`'s words, to divide them in this manner!
And Christ is the author of the faith.
And many have scriptures, and have not the ground of faith,
until they have Christ the author of it, and God the giver of it;
'`which are able to make wise unto salvation,`' through
the faith which Christ is the author of.
For Enoch, and Abel, etc. had faith before the scriptures were written;
and so before thy ground was.
And the saints had a rule before the scriptures were written;
for the spirit was their rule that led them into all truth,
and to speak forth scriptures; that is the rule that mortifies, circumciseth, baptizeth,
and leads into all truth.
The word of God, that fulfils scriptures, leads into all truth;
that is the truth that leads into all truth.
Now the scriptures cannot lead into all truth, but they testify of that that doth.
And if Christ be not within people, they are reprobates.
And is a reprobate justified?
And if Christ be within, is not the justification there,
and redemption and sanctification witnessed, '`Christ the same yesterday, today,
and forever.`'

[.discourse-part]
_Principle._ He saith,
'`We consider how few there are in the church that belongs to God.`' See his epistle.

[.discourse-part]
_Answer._ This is your own church, which is not the pillar and ground of truth.
For who are in the church of Christ, the pillar and ground of truth,
(where there is not a spot, or wrinkle, or blemish,
nor any such thing,) they are those that belong to God; they are living stones,
built up together a spiritual household; but from this thou art afar off.

[.discourse-part]
_Principle._ He saith, '`We willingly acknowledge we are fallible men, that may be deceived;
and to find infallible teachers is against experience.
None pretend infallibility but the pope.`' See page 9. He saith,
'`The scriptures are the well and living fountain,
from whence living waters have been drawn this hundred or thousand years,`' page 8.

[.discourse-part]
_Answer._ If every one that hath the scriptures hath the fountain, hath the devil the fountain?
for he can bring scriptures; hath he the fountain and well of living waters?
Nay, we say, God and Christ is the fountain of all good.
And saith David, '`all the springs are in him.`' And so, many may have the scriptures,
and yet want the waters, want the fountain;
who have had them since the days of the apostles,
who have had them this many hundreds of years in the apostacy, the sheep`'s clothing,
and have known no other fountain, but them, nor any other well.
So all the leanness of souls hath been among people,
because they have not known the fountain of whom they learned that gave forth scriptures.
And we do believe you, that ye are fallible men,
that say '`the scriptures are the well and fountain
of living waters,`' and you are not infallible.
And it is contrary to your experience to be infallible.
And we say the pope is not infallible neither, though he be your father, the ancient.
Yet we say,
he and you are apostatized from the infallible spirit that the apostles were in,
to which we are come, with which ye are seen and judged,
not to have the spirit of Christ Jesus,
not to have the spirit of the prophets and apostles,
not to he led by '`the spirit of truth into all truth,`' not to
be in the spirit not to speak as ye '`are moved of the holy ghost;`'
but to be such as are ravened from the spirit of God inwardly,
and have gotten the sheep`'s clothing, ye and the pope,
and so have devoured nations for this many hundred years,
so have all been like ravening wolves.
For who witness these conditions that they were in that gave forth the scriptures,
they witness infallibility, an infallible spirit,
which is now possessed and witnessed among those called Quakers:
'`glory to the highest forever,`' that your folly now should be made manifest;
the morning is springing in, the night of apostacy is going.
So I say, the devil, false prophets, antichrists, deceivers, beast, mother of harlots,
none of these can witness an infallible spirit, nor the well nor fountain,
but the letter; though they may get all the sheep`'s clothing,
and come in likeness of a lamb or a sheep to deceive people.
But being out of the spirit that Christ, the prophets and apostles were in,
that gave forth scriptures, they are not infallible as they were,
but with that they are all judged out;
which will answer that which they are all gone from, where the key is known,
and the well was and is, in believers.

[.discourse-part]
_Principle._ '`And the scriptures is the rule;
and the Quakers dream of the light to be their rule to walk by,`' page 14.

[.discourse-part]
_Answer._ The word of God which lives and endures forever, (which came to the saints of old,
which caused them to give forth scriptures,
and to write them,) which fulfils all the words again, is the rule:
which word was spoken to the saints before scripture was written:
which lets all people see that declaration, and fulfils that declaration to them,
Christ the leader of the people, the covenant of God, who is the light;
and they are in the dreams that deny it.

[.discourse-part]
_Principle._ He saith, '`But Christ, by his magistrates,
hath appointed tithes a maintenance for his ministers,`' page 21.

[.discourse-part]
_Answer._ Since the days of the apostles the pope gave tithes;
and other magistrates that followed him: and he hath had the tenths, the tithes,
since this night of apostacy, and the reprobation hath been from the apostles`' doctrine.
And many have had the sheep`'s clothing,
but have been raveners from the life that they lived in that gave it forth:
so have not seen to what state and condition the scriptures were spoken;
being out of the life they were in that gave them forth; and see not the substance,
Christ Jesus, who came to end the first priesthood, and the ministers that took tithes,
tolerated by the first covenant,
(which the apostle witnessed the end of,) and to bring in an everlasting covenant,
and another ministry, and another maintenance to them.
Since the days of the apostles, such as are ravened from the spirit of God,
have lost the maintenance the apostles and Christ gave; and so have set up tithes,
and another ministry, which is neither agreeable to Jews, nor Gentiles; nor Christ`'s,
but more dark.
But the night of apostacy is going over, the true light shines,
and the light of the living is springing in.

[.discourse-part]
_Principle._ He saith,
'`The immediate spirit excludes the word to be the rule,`' page 38. '`And the word,
and the spirit,`' he saith, '`are different things.
And the Pharisees thought right,
that eternal life was laid up in the scriptures,`' page 39.

[.discourse-part]
_Answer._ Christ told the Pharisees they would not come to him that they might have life:
and he was the life, and he was the way, and no one cometh to the Father but by him.
He doth not say he was scripture, but he bids them search it, for it testified of him:
and none have life but who are in him.
And the word and the spirit are one:
and the spirit doth not exclude the word nor the scriptures,
for they were given forth from it, and it owns them again; with it are they seen,
given forth in time, fulfilled in time, and they cannot be broken,
and the saints`' life is hid in Christ who ends them.

[.discourse-part]
_Principle._ He saith, '`Men are saved, but not by Christ within us,`' page 42.

[.discourse-part]
_Answer._ How is man`'s salvation wrought out, but by the power of Christ within?
How is the old man destroyed, but by Christ within?
How is the justification felt, but by Christ within?
And where the seed Christ that suffered without, is made manifest within,
there is redemption, and life.
'`He that hath the son of God, hath life;`' redemption to God out of the first Adam.
And who feels Christ within feels salvation;
and who doth not is a reprobate though he may talk of him.

[.discourse-part]
_Principle._ He saith, '`It is a fond sign to depend upon an unwritten word immediately,
within themselves: and say,
from that word is the life manifested within,`' page 43. '`And
Christ is not come to them in the flesh.`' And he saith,
'`Timothy had the gift of God freely; and elders are called ordinarily,
and not immediately.
This call ordinary is common to all ministers,
to continue to all ages in the church,`' page 47.

[.discourse-part]
_Answer._ All they that have not the unwritten word in their hearts, which is immediate,
know not the word of faith, know not the word of reconciliation;
know not the ingrafted word that is able to save their souls,
know not that which lives and abides and endures forever; know not eternal life,
neither have they it who have not the word, the immediate word within them;
and know not the immortal seed.
And such are in the fondness, that have the scripture and put that for the word,
which is words.
And since the days of the apostles, in your churches, your ministers, your elders,
your makers of your ministers, have been all mediate,
and so it is '`ordinary,`' as ye call it.
But before the apostacy, in the days of the apostles, we say,
neither elders nor ministers were mediate.
But that which made the elders, was the holy ghost, to oversee;
and that which brought them to minister was immediate,
and so they were ministers of the spirit.
And all elders made by the mediate, are carnal, earthly, and their weapons are earthly,
and their rule which they oversee with is earthly.
Therefore hath your church broken into so many pieces,
and they divide (and cannot hold together) like earth,
because ye are not in an immediate spirit.
And so we do see it is so since the days of the apostles;
neither your elders nor your teachers are called immediately,
but only have the sheep`'s clothing, ravened from the spirit of God.
And so are the wolves, tearing one another to pieces about the letter,
and your apprehensions of it.
And Timothy, many of you say had not an immediate call, and yet thou sayst,
he had the gift of God.
Both not that which God gives to men, bring to do his will?
And that which is given from God to man, is not that immediate, and perfect?
And we do believe you,
ye do not witness that ye are '`of his flesh and
of his bone,`' ye have not eaten his flesh,
nor drunk his blood: therefore do you say the scriptures are the fountain of life,
and have been these hundreds of years; which scriptures the Pharisees had in their age,
and had not life.
Ye have had the scriptures,
which ye call the '`well and fountain of life,`' many hundreds of years;
yet though you and the Pharisees have all scriptures,
'`except ye do eat the flesh of Christ, and drink his blood,
ye have no life in you,`' neither you nor the Pharisees; which flesh is our food,
and blood is our drink.
But we do believe you, that these many hundreds of years ye have not eaten his flesh,
nor drunk his blood: and so are not '`of his flesh,
nor of his bone;`' therefore cry ye so much against immediate, and infallibility.

[.discourse-part]
_Principle._ He saith, '`The holiest man that is,
is not able to give an infallible character of another man,`' page 49. '`We do grant,
that our ministers came from antichrist,
and passed through him.`' And he chargeth people
'`for leaving their callings,`' and says,
'`that the Quakers are like to them that flee from the wrath to come.`'

[.discourse-part]
_Answer._ We do believe that your ministers came from antichrist, and through antichrist,
for he was the channel; but the Quakers are neither of you, nor of antichrist,
nor of the pope: but they are of the apostles`' stock, and of Abraham, and of Christ,
before the pope was, antichrist was, or you were,
and so with the spirit of God and the apostles you are fathomed.
And the Quakers do witness they are made free from the wrath to come,
which the Pharisees that fled to John did not.
And there thy measure is too short; all may see it that are in the light,
and thy ignorance of the scriptures thou hast discovered and shown.
And thou sayst,
that '`the holiest man is not able to give an infallible character of another man:`'
hast not thou in this discovered thyself to be no minister of Christ or of the spirit?
If thou canst not give an infallible character of another man,
how canst thou minister to his condition?
How canst thou see where he is?
how canst thou see them that be turned from the darkness, and that be in the darkness?
and distinguish the one from the other, and a holy man, from an unholy man,
that canst not give an infallible character of any man`'s state?
How canst thou know when men are in the spirit;
and that they are epistles written in one another`'s hearts, not with paper and ink,
but with the spirit of the living God?
Oh! a divider of the word aright hath been wanting among you dark ones!
Thou mayst say right enough, your ministers came from antichrist, and through antichrist.
And did not the saints leave their callings?

[.discourse-part]
_Principle._ He saith,
'`It is a fancy to witness the righteousness of Christ
within us,`' page 61. And to maintain persecution,
he brings '`Ahab`'s slaying the false prophets,`' and for the laying on of hands,
he brings '`the practice of the apostles.`' And to stop the liberty of conscience,
he saith, '`Must Saul be permitted to do what he will against Jesus of Nazareth?`'

[.discourse-part]
_Answer._ False prophets are enemies, yet they are not to slay them.
The apostles did not wrestle against flesh and blood with the false prophets,
as you ministers do now; though Saul did, before he was Paul,
and showed himself of your nature unconverted.
And whoever are not in that state to witness Christ in them manifest in their flesh,
and there condemning sin in the flesh,
that they may through him become the righteousness of God, are in their fancies;
and Christ destroys the ground of all fancy,
and brings to see where there is no shadow nor changing,
and brings their conscience into liberty, and washeth and sprinkleth it,
where the mystery of faith is held in it.
And your laying on of hands,
(since the apostacy from the apostles,) is not as the apostles,
who have not an infallible spirit, nor are infallible, nor called immediately,
as they were; none of those you lay your hands on can receive the holy ghost,
when you yourselves are not in the immediate spirit, nor infallible,
nor called immediately.
So you all being in the apostacy from the apostles`' hands and calling,
your folly is made manifest, the light hath discovered you, at which ye are stumbling;
and every one is wrestling against the Lamb and the saints,
that is wrestling against the light: and such are antichrists,
that shall he slain with the sword, the words of his mouth:
and the Lamb and the saints shall have the victory.

[.discourse-part]
_Principle._ He saith, '`Human learning helps to understand heavenly things,`' page 70. Again,
'`Christ enlightens men no more ways but one, to wit,
by a natural light,`' page 71. '`And the righteousness within is not that which justifies,
and we are not freely justified, and saved,
and redeemed (that is) through that redemption and
righteousness that is within us,`' pages 74, 75.
He saith, '`We are justified freely, but not by the grace wrought in us.`'

[.discourse-part]
_Answer._ '`By grace ye are saved, and that not of yourselves,
it is the gift of God;`' and this is manifested in the heart,
before it be known and possessed.
And every one that knows justification, redemption, righteousness, and salvation,
these are all known within us, else people are in the first Adam, driven from God,
not come to the second Adam, not knowing salvation in the ground,
justification in the ground, redemption in the ground.
If Christ, the righteousness of God, redemption, justification, and salvation,
be not felt within people, and found within, they are reprobates.
And the reprobates may talk of it without; but where that is, there is salvation,
righteousness, redemption, justification, etc.
And Christ doth enlighten every man that cometh into the world,
him by whom the world was made, before it was made; which light people are to believe in,
which is not natural: which gives to see over nature, before natural was.
For the natural lights are the sun, moon, and stars,
which may be seen with a visible eye: but Christ the light,
the covenant of light to Jews and Gentiles, the salvation to the ends of the earth,
doth enlighten every one that cometh into the world,
that all men through him might believe.
Here God is no respecter of persons; he that believeth in the light, shall be saved,
and he that doth not, is condemned.
And he comes to be a child of light, who believes in the light:
and now shall the world be reproved for not believing in the light.
And human learning is that which is earthly and natural; that doth not open the heavenly:
that which reveals the things of God, is the spirit of God,
beyond all the world`'s wisdom.
For that you call human learning, and human soul, and human body, is earthly,
not heavenly, nor understands them.
The earth is below, so they that are below measure by the earthly wisdom,
but they that are from above speak of the things above,
and so that which gives to understand the heavenly things, is the spirit of God,
and the spiritual wisdom, which is not of man, nor from man; for saith the apostle,
'`Neither knows any man the things of God, but the spirit of God.`'

[.discourse-part]
_Principle._ '`And the righteousness of Christ by which we
are justified (he saith) is not within us.`' Again,
'`The Lord will pour out his spirit upon all flesh;
but that is not meant that all should have the spirit, for some have not the spirit,
as in Jude.`' Page 79. He saith,
'`he desires God to lighten with a better light than that which lightens every man,
etc. and to lead them out of these gross delusions.`' See page 80.

[.discourse-part]
_Answer._ You that are not justified by that Christ that suffered without,
manifested within you, shall never know justification;
if the justification be not within, you are reprobates.
And the Lord hath fulfilled his promise, by pouring out his spirit upon all flesh,
sons and daughters, handmaids and old men, though they quench it.
And that in Jude proves they had the spirit, who went in Balaam`'s, Cores`',
and Cain`'s way, but had erred from it; where you are, in the sensual state,
in the sects, and not seeing the fulfilment of the promise of the Father,
that he would pour out of the spirit upon all flesh.
Apostatized from the life the apostles were in, and the prophets,
you manifest yourselves to the whole world.
And so you own not the light, Christ Jesus, that God sent into the world,
and gave his only begotten son into the world,
which doth enlighten every man that cometh into the world,
that all through him might believe; but thou that desirest better light of God than he,
(to wit, Christ,) showest thy tempting, and blasphemy.
For there is no other way to the Father but by Christ the light of the world,
that doth enlighten every one,
etc. and he that doth not believe in that light is condemned.

[.discourse-part]
_Principle._ He saith, '`And Christ doth enlighten every man that cometh into the world,
that is meant the church.`' See postscript.
'`Paul and Peter were instructed by immediate Revelation,
which we are not so presumptuous as to expect.`' And saith,
'`Reproaches are cast upon the ministers, because they are not infallible,
and preach not by immediate inspiration as the apostles did.`' Postscript.

[.discourse-part]
_Answer._ You that do not instruct and preach by the same immediate
infallible spirit the prophets and apostles were in,
are all in an usurped authority, out of the spirit, have run, and were not sent from God:
for whom God sends, he sends immediately; and whom he teacheth, he teacheth immediately,
and they know his infallible spirit.
And none know the scriptures of truth but who are in the infallible spirit,
and immediate, which the prophets and apostles were in, from which you are gone forth,
and it is presumption in you to teach without it.
And so neither you nor the pope are reproached,
that are the false prophet and antichrists that Christ said should come,
and the apostle John saw were Come, that inwardly ravened,
and have gotten the sheep`'s clothing,
'`have the form but deny the power.`' You who deny infallibility, and the immediate call,
and the immediate ministry, have denied the power of God,
and so keep people '`always learning,
and never able to come to the knowledge of the truth,`' in the usurped
authority which the apostles stopped and rebuked before their decease.
And so you do not see the '`light that doth enlighten
every man that cometh into the world.`' Christ saith,
'`I am the light of the world,`' not of saints only.
And saith the prophet,
'`I will give him for a covenant to the Gentiles,`'
not '`a new covenant to the house of Israel`' only;
and there he was prophesied of before John came,
the greatest prophet who was born of a woman, who said,
'`This is the true light that doth enlighten every man,`' etc.
And when Christ was come he said he was the light of the world:
and whosoever did believe in him should not abide in darkness,
but should have the light of life.
And so, since ye ravened from the spirit of God, and have only had the sheep`'s clothing,
ye have brought people into heaps and sects:
and they that are not in that which is infallible, are they that reproach;
for they are in the reproachful spirit, but the spirit of God never did reproach,
which was immediate and infallible, which the prophets, Christ, and the apostles were in,
which always judged the reproachers who were strayed from the infallible spirit.

[.discourse-part]
_Principle._ And thou sayst, '`To the law,
and to the testimony,`' and that '`he gave some apostles for the perfecting of the saints,
for the work of the ministry, for the edifying of the body,
till all come into the unity of the faith, to the knowledge of the son of God,
to a perfect man, to the measure of the stature and fulness of Christ.`'

[.discourse-part]
_Answer._ Thou, and you all that have denied infallibility,
and immediate inspiration and teaching,
have shut yourselves out of the law and testimony, and the work of the ministry,
which is '`for the perfecting of the body,`' and bringing them to the unity of the faith,
to '`the knowledge of the son of God,`' etc.
For '`the law is light;`' that is infallible and immediate.
'`The testimony of Jesus is the spirit of prophecy;`' that is infallible and immediate.
And ye may have the Old and New Testament, and say that is the law and testimony;
but the law and testimony was before Matthew, Mark, Luke, and John, the Acts,
the Epistles, and the Revelations were written, even in the days of Isaiah: see Isa.
viii.
chap.
And that which perfects the saints is infallible;
that gift which was given to the ministry is infallible and immediate;
that which edifies the body of Christ is infallible and immediate;
that which brings '`to the knowledge of the son of God,`' is infallible, perfect,
and immediate; that which brings to '`a perfect man,
to the unity of faith,`' is infallible and immediate, and perfect;
that which brings '`to the measure of the stature of the fulness of Christ,`' is perfect,
and infallible, and immediate.
And the infallible and immediate you having denied,
ye have shut yourselves out of the work of the ministry, in the apostacy.

[.small-break]
'''

As for the rest of the lies and slanders in thy book, they will be thy own burden,
who utterest forth thy own folly, and they touch not the saints, but fall off like dust;
they are of no weight.
And the day is come that tries men`'s works infallibly, what is for the fire,
and what not.
