[#ch-31.style-blurb, short="The Quakers Quaking"]
== Jeremy Ives`' book, called [.book-title]#The Quakers Quaking.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`Have a care of slighting your watchmen,
lest the Lord remove them into corners.`'

[.discourse-part]
_Answer._ Christ the teacher is witnessed, who is the end of Moses and the prophets,
the covenant of God with his people,
in which people would know God if all their teachers were removed into corners.
And they that have their teachers in corners, their houses are left desolate,
from the covenant of God they are strangers.
So in this thy ignorance appears of that teacher that cannot be removed into a corner,
who is the '`salvation to the ends of the earth.`'

[.discourse-part]
_Principle._ He saith, '`It is an error to say, the light within is equal with scripture,
and God`'s word.`'

[.discourse-part]
_Answer._ Christ within is the light, and he is above scripture, and is God`'s word,
which was before scripture was given forth.

[.discourse-part]
_Principle._ He saith, '`Is it any more a nickname to call a man a Quaker,
because he quakes by the power of God?`' page 3.

[.discourse-part]
_Answer._ Yes, if the power of God doth make him to quake and tremble.
And he must quake before salvation be wrought out, and man come out of the fall,
out of Adam`'s state in the transgression, in the earth and darkness, corruption,
pollution, and death;
he must know the power of God that shakes that which is to be shaken,
before he knows that raised up that cannot be shaken; which the world is ignorant of,
though they have the form of it.
And the first nicknamer of the Quakers that ever I heard,
was a corrupt justice in the year 1650, whose name was Gervase Bennet, in Darby.
He was the first that ever named the people of God Quakers,
though the mighty power of the Lord God had been known years before.

[.discourse-part]
_Principle._ He saith,
'`It is an error in those men that will allow nothing
to be called God`'s word but Christ,`' page 6.

[.discourse-part]
_Answer._ Christ`'s name is called '`the word of God;`' his name is above every name,
and over all things, words, and names, he must have the preeminence.
Yet I say, the scriptures of truth, given forth from the spirit of truth,
are the words of God: God`'s words which Christ the word fulfilled, in whom they end,
who was before the words were spoken forth.

[.discourse-part]
_Principle._ He saith, '`It is an error to say they are immediately sent of God,
and to have an immediate call from God to go,
out of their countries to preach the gospel,`' etc. page 9.

[.discourse-part]
_Answer._ Thou, and all you that speak, or preach, or go to people,
but not by the immediate spirit, and a call from God,
are they that run and the Lord never sent you; and you profit not the people at all,
as all your fruits, in the nation declare upon the house top.
Therefore are ye wrangling and envying such as are immediately sent from God,
and have left their callings as the saints and prophets did:
I say none upon the earth can preach the gospel, but who are in the immediate call;
for the gospel is the power of God, and that is immediate.
The prophets, Christ, and the apostles who gave forth the scriptures,
all spoke by the immediate spirit of God: and all that are not in that,
are not able to know the scriptures; as that unsavoury Percival saith,
'`he hath not the infallible spirit;`' yet he will bawl of the
scriptures that were given forth from the infallible spirit.
The devil that compasseth the earth, wandered from the truth;
the Pharisees compass sea and land;
the false prophets and antichrists have gone over nations:
now all these may get scriptures, but are out of the life of them.
Such make proselytes, devils, disciples, and messengers:
but such as are in the power of God, and the life that gave forth scriptures,
that comprehends and fathoms the world, they are in that which the devils, antichrists,
false prophets, mother of harlots,
and all their proselytes that have scriptures out of the life, are out of.
Such are the Quakers, therefore doth all the world rage against them,
who witness that which cannot be shaken.

[.discourse-part]
_Principle._ He saith, '`It is an error to say that every man hath a light within him,
that will teach him to worship God aright,`' page 18.

[.discourse-part]
_Answer._ Christ the truth, who hath preeminence,
'`doth enlighten every man that cometh into the world,`' who shall
make every tongue to confess him to the glory of God.
If they love the light which cometh from Christ the truth, who is the life,
it will teach and direct every man to worship God in the truth,
in that which untruth is out of.
So every man has a light sufficient to salvation, for it cometh from the salvation;
Christ the power of God,
'`the salvation to the ends of the earth.`' And this
light will let every one see the son of God,
beyond all external means, wisdom, or knowledge, whatsoever.
It is that which darkness cannot comprehend, which John bears witness of,
'`the true light which lighteth every man that cometh into
the world,`' which the Jews and Levites stumbled at,
which set all Jerusalem in an uproar,
as it doth the wisest priests and professors in this age.
And no one upon the earth shall ever know Christ
but by the light which he hath enlightened him with.
If he have all the scriptures that speak of him come already,
as the Pharisees had those that spoke of him as to come;
yet if they hate the light they shall all be snared, and stumble, and fall,
and split themselves upon the rock.
And such as are now stumbling at the light which
every man that cometh into the world is lighted with,
are the builders with the words, who say,
'`Christ is come,`' as the Pharisees did with the words, that said,
'`he was to come.`' And so both these builders reject the corner stone,
and stumble at the elect stone laid in Zion;
and none see God but with the light they are enlightened with.
And the substance of all the preaching of the apostles,
was to bring people to the covenant of light, both Jews and Gentiles,
to whom he was promised.
And all upon the earth that are from this light that
doth enlighten every man that cometh into the world,
are in the error, out of the covenant of God, and strangers from the covenant of promise.

[.discourse-part]
_Principle._ He saith, '`It is an error to say, the letter of scripture is carnal,`' page 22.

[.discourse-part]
_Answer._ We cannot say the letter of scripture (paper and ink) is spiritual;
but that which it speaks of is spiritual.

[.discourse-part]
_Principle._ He saith, '`It is an error to say they are perfect,
and without sin,`' page 23. '`And another error to say,
that none can come to God and Christ, but they that come to perfection.`'

[.discourse-part]
_Answer._ Whoever comes to Christ and God,
comes in the one offering which '`hath perfected forever
them that are sanctified,`' and whoever comes to Christ,
comes to him that is perfect;
and '`without holiness none can see him.`' And they that
pretend coming to God and Christ out of perfection,
are in the error, and all sin is error, and they who are in it are in the error;
but the apostle said they were made free from sin, and had put off the body of sin,
and by the blood of Christ were cleansed from all sin;
and that by one offering he had perfected forever them that are sanctified.
And so they that say men must have sin while they are upon the earth,
and that plead for it, are not the friends of Christ.
For they who are the friends of Christ are in his power, atop of the power of sin,
and trample it under foot.

[.discourse-part]
_Principle._ He saith, '`that the scripture is the word.
And though Christ be the true light that lighteth every man that cometh into the world,
yet that light in every man doth not direct a man into the worship and service of God,
though it be the true light of Christ,`' page 35.

[.discourse-part]
_Answer._ Nothing can direct men into the worship and service of God but the true light;
for the light is that which doth make manifest,
which every man that cometh into the world is enlightened with; which, he hating it,
and not corning to it '`because his deeds be evil,`' will be his condemnation.
And thou shalt feel it heavy at the last, though now thou mayst roar and rage for a time,
yet the bond is gone over thee, the chain is set, and the sentence is given.

[.discourse-part]
_Principle._ He saith, '`It is an error of such as leave water baptism,
and breaking of bread,`' etc. page 38.

[.discourse-part]
_Answer._ Doth not the apostle bring people off those things that are seen?
And are not outward water and outward bread the things that are seen?
And are not these things temporal, though in their places and service they are owned.
But they who come into the baptism of the spirit, come into that in which the other ends,
the greater.
For many came to John; but when they should have come to receive Christ the light,
which doth enlighten every man, etc. they stood against him, as you do now.
And Christ told them they received '`honour one of another,`' as you do now,
(a mark of the unbeliever,) and the love of God was not in them,
and the word of God was not abiding in them; and they had never heard the voice of God,
nor seen his shape at any time.
And there are you, like the Jews, whose table is a trap, sticking in the outward things,
standing against the light that doth enlighten every man that cometh into the world,
and so stumbling at the corner stone, elect and precious.
But it is fallen upon your heads; and will grind you to powder; fight, bustle,
and do all that you can, it is upon you, and all your compliments will do you no good.
And none seek the honour that comes from above,
but who are in the light that doth enlighten every man, etc.
And none honour the son, but who are in the light that comes from him,
though they have all the scriptures, as the Pharisees had in their age.

[.discourse-part]
_Principle._ He saith, '`Error in life doth not prove error in judgment,`' page 46.

[.discourse-part]
_Answer._ They who err in the life, err in the judgment: for all that err in the judgment,
are erred from the life.
And all the Pharisees had scriptures; yet being erred from the life,
they all erred in their judgment, and knew not Christ the substance of scriptures.
So all you that are in error in life, err in your judgment,
you all stumble at the light with which Christ doth enlighten every man, etc.
And none are out of the error of life, and out of the error of conversation,
but who are in the light which '`doth enlighten every man that cometh into the world.`'

[.discourse-part]
_Principle._ He saith, '`that the Quakers foam at the mouth,`' etc.

[.discourse-part]
_Answer._ It is a shame that ever men should lose their soberness, and come to lose all modesty;
that so many that do call themselves teachers in this nation,
should publish such odious lies and untruths to the nation.
And '`that the Quakers have hung ribands upon one another,
and given ribands to one another, as instance,
G+++.+++ F. should have from M. F.`' Oh! that ever modesty should be so lost,
and shamefacedness quite gone,
which should have been a garment to have covered impudency: that ever men,
and teachers of people, and professors, should make lies their refuge!
But I say, the Lord forgive you, for all these things shall be your own burden;
and a heavy burden is come upon you, and coming upon you all in the nation,
that trust in lies.
But what if you should see every man with his hand on his thigh, in pain to be delivered.

[.discourse-part]
_Principle._ He saith, '`The prophet that shall presume to speak a word in any name,
and I have not commanded him to speak, he shall die.`' See page 26.

[.discourse-part]
_Answer._ Here thou hast brought thyself, and all of you, under thy own judgment,
and given sentence upon yourselves, and all the rest of the teachers,
that say '`they never heard the voice of God immediately from heaven,
nor immediate inspiration nor revelation.`' So ye all want the spirit of God,
and are out of it that the prophets and apostles were in, and with it are all judged.
Though ye may run in pretence of his name,
(with the form,) and say ye never heard his voice;
but '`that prophet shall die,`' thou sayst.
So thou hast judged yourselves, and there are all you teachers, in the apostacy,
since the days of the apostles.

[.discourse-part]
_Principle._ '`And Christ said, many deceivers should come in his name, and deceive many:
and such as serve not the Lord Jesus Christ but their own bellies.
And with good words, and fair speeches deceive the hearts of the simple.`' See title page.

[.discourse-part]
_Answer._ Christ said in Matt.
xxiv.
and in Matt.
vii. that false prophets should come, and antichrists,
which before the apostles`' decease they saw come;
and such as '`served not the Lord Jesus Christ but their
own bellies;`' which went forth from the apostles,
which, in the Revelation, John saw the whole world gone after;
and those got the sheep`'s clothing,
and so with the good words and fair speeches deceive;
who were inwardly ravened from the light which doth
enlighten every man that cometh into the world;
and such have good words and fair speeches, but deceive the hearts of the simple,
and gather people into forms, and heaps, and sects, and ways,
and opinions one against another, which are nothing but the beast and his names,
and all against the light that doth enlighten every man,
etc. and so are making war against the saints of the Lamb.
But the Lamb and the saints shall have the victory, who will slay with his sword,
the words of his mouth.
And judgment is come through unto victory, and set in the earth.
And so the deceivers and antichrists are telling people, '`Now is the last time,
now are they come,`' and bidding them come to Matt.
vii. and Matt.
xxiv.
which indeed Christ did say they should come; but John said they were come,
whereby they knew it was the last time: and in the Revelations he saith,
that all nations have drunk the whore`'s cup,
and the kings of the earth have committed fornication with her,
and the inhabitants of the earth are drunk with the wine of her fornication,
and the earth is corrupted; as ye make it appear, your fruits declare it.
And this is that which hath brought the nations to be as waters, and peoples as waters,
and tongues as waters, and multitudes as waters, ravened inwardly from the spirit of God,
yet have gotten the sheep`'s clothing to deceive the nations.
Such as drunk the blood of the saints, the prophets and martyrs,
did make war against the saints, and overcame them.
But now the saints and the Lamb have the victory; glory to the highest.
And to that which they ravened from, are people come now.
