[#ch-32.style-blurb, short="A Stumbling Stone"]
== William Dell`'s book, called, '`A Stumbling Stone.`' His principles follow.

[.discourse-part]
P+++.+++ He saith,
'`The carnal church is a great enemy to Christ`'s
church.`' And '`they are offended at Christ,
because in him there was no human nor earthly thing,`' page 13.
'`It is the greatest error that reigns under antichrist`'s kingdom,
to affirm that the universities are the foundation of ministers.
And Peter undoubtedly taxeth the universities, with such men to be false doctors,
false prophets, out of which proceed all the teachers in the world,
in their towns and cities, under the whole kingdom of antichrist,
which have such doctors and teachers in the university for the whole world,`' page 27.

[.discourse-part]
A+++.+++ The rest of the priests and teachers which are come from the universities,
and such as have set up themselves to be teachers,
(as in this book ye may see,) say that Christ in heaven hath a human body,
and others say that he hath a human soul, and thou sayst,
there is no human or earthly thing in him.
And forasmuch as thy saying '`it is the greatest error under antichrist`'s kingdom,
to say the universities are the fountains of ministers.`' That is a true word;
it will be well for thee if thou be not caught in this fountain among these errors,
maintaining of them; for such are they that quench the spirit,
and speak the scriptures in that spirit which they came not by.
And these are they that have deceived the whole world.
And all such as make ministers in their wills, quench the spirit, limit the Holy One,
despise prophesying, make a trade of scriptures which came not by the will of man,
for the satisfying of their own wills.
And happy would Dell have been, if he had lived in what he spoke.
