[.style-blurb, short="Stablishing Against Shaking"]
== Gyles Fermin, called pastor of the church at Shalfor in Essex, his book called, [.book-title]#Stablishing Against Shaking.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`Take away learning, and England becomes a dunghill.`'

[.discourse-part]
_Answer._ Peter and John were unlearned men, yet were no dunghill.

[.discourse-part]
_Principle._ He saith, '`True teachers plead hard for their people`'s ears.
The Quakers say we are not ministers, because we preach for hire;
and are covetous and divine for money;
and the apostles took wages and maintenance,`' and saith, '`they eat,
and drank,`' etc. and he saith,
'`The Lord did ever beteem his ministers honourable wages,`' page
5+++.+++ And '`the labourer is worthy of his hire,`' page 6.

[.discourse-part]
_Answer._ When the apostle speaks of taking wages, of eating and drinking,
to them that examined him, he speaks this among the saints, gathered out of the world,
from among Jews and Gentiles.
This was not spoken to such as held up temples, tithes, and priests, but a gathered,
separated people from them.
And the gospel they preached, the power of God,
opened the hearts of the people to give unto them, and not by an outward law.
And the great work of the apostles was not to wrangle about their maintenance,
as is the great work of the man-made ministers now in our age, such as divine for money,
and prophesy for money.
And hire was ever looked upon to be the false prophets wages,
who are without the spirit of God that gave forth the scriptures;
for the spirit of God would never value, equal,
or measure his gift with the earthly things.
And when the apostle speaketh of the labourer being worthy of his hire, he saith,
'`Who goes a warfare at his own charge?`' and they that were taught,
were to communicate every good thing to them.
This still was spoken among the saints, this was not spoken in temples, and synagogues,
and to them that took tithes;
for those were warred against by them that were in the substance:
and the warfare was to bring people to the substance;
out of the first Adam to the second; and out of the shadows.
And that whereby the ministers had the double honour, was the life and the power:
such measured not a gift with earthly things;
which brought them to lay down all their estates at the apostles`' feet;
which was more than tithes.
But this gospel we see not among you, nor this power, the power of God;
neither preachers nor hearers.
And the apostles did not bid the Gentiles,
nor the Jews that were in their forms and inventions, and traditions,
that had elders among them; they did not bid them obey them that had rule over them;
but they brought them from under those rulers, from those elders to Christ the substance,
the elder brother: and so who was grown more than another in the life, was the elder,
and watched over the weak.
And it is manifest that you never received the gift of God,
whose work is thus to jangle for outward things.
For the gift of God which is perfect, would break through the imperfect,
and raise up the witness to give freely.

[.discourse-part]
_Principle._ He saith "`No man can be a good text man unless he have
attained to the languages which hath cost us so much;
and he cannot know the errors but by learning`' And saith,
"`he may thus speak for the necessity of arts,
without which men cannot be sufficient ministers.`'

[.discourse-part]
_Answer._ None are made ministers of Christ by arts, nor by languages;
let them get all the languages upon the earth, they are still but naturalists,
and men learning other men`'s natural language;
he who hath learned but that which is natural, knows but that which is natural,
what another natural man can speak; and all their arts are there.
Now that which makes a minister of Christ is beyond the natural: yea,
all the natural languages upon the earth; and seeth before they were.
Let it cost them never so much, yea gold and silver, a wedge of gold,
and the most precious things upon the earth, cannot purchase,
nor make a minister of Christ; that which makes them is the spirit of God,
and none know the scriptures given forth from the spirit of God,
but with the spirit of God.
Nor do any know the errors but by the spirit of God.
Nov if all men upon the earth have scriptures, in every one of their natural languages;
yet none of these know the errors,
nor the scriptures without the spirit of God from which they were given forth.

[.discourse-part]
_Principle._ He saith,
'`If the magistrates could find out any other way for maintenance for ministers,
they would part with tithes,
which have been these many hundreds of years.`' See page
9+++.+++ And '`there are many ministers will not take their tithes,
but they compound with the people for their tithes.`'
And '`we dare not trust the people for maintenance.
But we see care hath been taken for us many hundred years before we were born,`' etc.
See page 10. '`And why do not the Quakers charge us with idleness,
as well as with taking wages.`'

[.discourse-part]
_Answer._ Are ye not all a company of idle fellows,
bred up at schools in the pride and filthiness of the earth?
And when ye come out ye raven after great benefices, and trouble parishes,
and stir up the people to envy against one another, like a company of madmen, and sue,
and hale people up and down to courts for maintenance.
Are not these the works of belly-gods?
And is the magistrate the lord of the vineyard,
that he must allot a maintenance to the labourers?
Hath not Christ already told his ministers what they must have?
and were not the apostles to go forth without any thing, and to trust the Lord,
and the people, which you dare not trust?
And ye dare not trust the gospel to maintain you; but you have a set benefice,
or augmentation,
or a magistrate`'s power to give you maintenance before you go out to a parish.
Oh! how are ye biting and devouring one another for such things as were not accounted of,
or esteemed among the saints, who suffered joyfully the spoiling of their goods,
by such devourers as you are!
And is that your deceit, to compound with people for their tithes?
and is that your cloak then, to say you do not take tithes?
And since the days of the apostles, in the apostacy, since the power of God, the gospel,
hath been lost, which men should have preached and lived on, have tithes been set up.
So you that have had the form of godliness, denied the power,
(the gospel,) and have ravened from the life of God, your gospel will not maintain you;
and ye cry, '`help magistrate, help law, cast into prison,
summon up to courts,`' and this hath been your work for many hundred years for maintenance.
And so all sober men that stand and look on are ashamed of you.
Thus the poor people are deceived with your false covers, and wolfish spirits.
You have gotten the sheep`'s clothing upon your backs; but now are the vials,
and hail storms fallen upon your heads, which make many of you gnaw your tongues;
and now are the thunders coming out, and the plagues,
which make many of you fret yourselves.

[.discourse-part]
_Principle._ He saith, '`False apostles and deceitful workers,
and Satan transforming himself into an angel of light,`' etc.
See page 11.

[.discourse-part]
_Answer._ Christ said false prophets, and antichrists,
the inwardly raveners in the sheep`'s clothing, should come;
the apostles saw they were come before their decease, who were devouring,
as most of the epistles declare of them; the apostles saw them before their decease;
that made a prey upon the saints;
that served not the Lord Jesus Christ but their own bellies.
Now since the days of the apostles hath the world run after them;
and they have devoured the world,
and they have gotten the sheep`'s clothing upon their backs:
therefore have ye deceived the world.
Now, you have been the skirts, and the suburbs of this great city;
the day hath declared you, your city is besieged,
and the Lamb and the saints have conquered it: by whom the saints have been slain,
and their blood drunk.
In which city hath a trumpet sounded, and the piping hath been,
and the mourners have gone about the city.
But now are come to her lamentation, desolation, and woe, and to all her merchandise,
that hath builded up and thrown down, whereby the world was brought into confusion;
the faith, and truth, and life, and love being reprobated from,
and that the saints were in, that gave forth the scriptures.
That which the apostles saw coming in before their decease,
which Christ said should come, hath ruled and reigned, since their decease,
until this day that Christ hath come and made it manifest.

[.discourse-part]
_Principle._ He saith, '`The devil could not do mischief in the church where the candle is burning,
and light shining: but he gets on his garb:
and the weakest of children are carried about with
every wind of doctrine.`' See page 17. He saith,
'`The prince of darkness is transformed into an angel of light,
he walketh in the churches.`' See page 18.

[.discourse-part]
_Answer._ The church of Christ is the pillar and ground of truth,
which truth the devil is out of, and abode not in it: he walks on the outside,
and is not in the church, and so, children thou knowest not,
that are heirs of the kingdom of Christ, and are of his church,
the pillar and ground of truth.
And the devil, and false prophets, and mother of harlots,
though they have all the sheep`'s clothing,
they cannot get into the church where the candle is, and the burning shining light:
not the devil with all his '`garb,`' as thou callest it.
Let the whore who hath ravened from the spirit of God, be arrayed never so gorgeously,
that is the church, the pillar and ground of truth, that is in the spirit of God,
where the candle is burning and light shining; this the whore, devil, wolves,
false prophets, antichrists, and beast, are out of, raging on the outside, in the earth?
So the church of Christ is the pillar and ground of truth,
and here the elect is known that cannot be deceived.
And the devil, the prince of darkness,
though he transform himself into an angel of light, he doth not walk in the church,
for the church is in God, the pillar and ground of truth, and out of that he is,
and all his apostles, and his messengers, and truth is atop of him, and them all,
and with it they are shut out.

[.discourse-part]
_Principle._ He saith,
'`Honour is the expressing of the inward respect that we bear to
persons,`' and many scriptures he brings for bowing and for master,
page 23. and so stumbles at thee and thou.

[.discourse-part]
_Answer._ Which shows he never learned his accidence, nor Bible,
and is a transgressor of Christ`'s commands, who saith, '`Be not of men called master;
for ye have one master even Christ,
and ye are all brethren;`' and a transgressor of the law,
for '`they that respect persons commit sin,`' and are convinced of the law as transgressors,
and reprobate concerning the faith, which is held without the respect of persons.
And though they bowed in the old time: several bowed before the angels:
yet Christ is come by whom all things were made, the salvation to the ends of the earth;
to whom powers, principalities, thrones, and dominions must be subject: to whom angels,
and thrones must bow; yea things in heaven, and things in earth,
and every tongue confess him to the glory of God,
and '`every knee bow:`' and there people come into the unity,
and there they hold the head.

[.discourse-part]
_Principle._ He saith, '`The Quakers`' light teacheth to forsake the scriptures;
and set up a spirit in man, which will not be examined by scriptures.`' See page 26.

[.discourse-part]
_Answer._ He is out of the truth who speaks it:
for the Quakers have not received the spirit of the world, but the spirit of God;
by which they know the things which are freely given of God,
and know the scriptures given forth from the spirit of God:
and with the same spirit the scriptures are owned again.

[.discourse-part]
_Principle._ He saith, '`Paul swore, after Christ, and the angels swore,`' page 27. And saith,
'`I wonder Paul should so forget himself, and sin so fearfully in swearing,`' etc.
'`so the Quakers`' light that denies swearing, is of Satan,
and not the light of Christ,`' page 28.

[.discourse-part]
_Answer._ Christ the light, (which Satan is out of,) who is the oath of God,
ends all oaths sworn by prophets or angels whatsoever.
And who swear are fallen into the condemnation of the devil;
and it is no where said that the apostle swore; but such as thou art,
matter not what they speak.
So that spirit that preaches for swearing is not the spirit of Christ,
but is the spirit of antichrist,
preaching up that which Christ and the apostles preached down,
who preached condemnation to them that did swear.

[.discourse-part]
_Principle._ He saith, '`The light in the conscience that takes them from the law of God,
is the light of Satan.`'

[.discourse-part]
_Answer._ The light, Christ, in the conscience is the end of the law for righteousness`' sake.
And that which keeps men from that which doth end the law,
is not the doctrine of the true apostles, but the false.

And the light '`which doth enlighten every man that
cometh into the world,`' which is the substance,
leads men off from all types, and figures, and signs: who come to enjoy him,
enjoy the end; who come off from all outward elements, as bread and wine,
and such things, to the substance itself, to look at things that are not seen.
'`For things that are seen are temporal, but the things that are not seen are eternal.`'

[.discourse-part]
_Principle._ He speaks of '`a new creature distinct from Christ,`'
and saith while we live sin lives.`' And saith,
'`I deny that the righteousness of Christ, whereby a believer is justified,
doth dwell in him,`' page 36.

[.discourse-part]
_Answer._ Is not the new creature in Christ?
'`He that is in Christ is a new creature,`' and is not distinct from him;
and how hast thou divided the word here?
And Christ is justification, sanctification, wisdom, and righteousness;
and if he be not within you, ye are reprobates.
And where Christ is, he is not without righteousness.
Therefore they are not without righteousness, and wisdom, justification,
and sanctification, if Christ be within; for, where he is, that is not wanting.
And the apostle said they were '`made free from sin.`' And
'`let not sin have dominion over your mortal bodies;`' mind,
'`mortal bodies,`' which sin was not to have dominion over.
And '`old things pass away, and all things become new.`' Sin is an old thing,
from the old deceiver.
So while any sin is standing, all things are not made new, and sin hath its dominion.

[.discourse-part]
_Principle._ He saith,
'`he hath not read where a believer dwells in Christ`'s righteousness,`' page 37.

[.discourse-part]
_Answer._ Every true believer is born of God;
and '`he that is born of God doth not commit sin.`' And he that dwells in Christ,
dwells in righteousness and truth, in that which sin and the devil are out of,
which blots out sin and transgression, where the body of it comes to be put off.

[.discourse-part]
_Principle._ '`And the light which teacheth men to say they have no sin, is of Satan.`' And saith,
'`The Quakers`' light teacheth them to deny prayer.`'

[.discourse-part]
_Answer._ The apostles`' light taught them to say, they were made free from sin,
they had put off the body of sin, and their sin and transgression were blotted out.
The sins of the '`little children`' were forgiven, they that walked in the light,
'`the blood of Jesus Christ cleansed them from all sin,`' taught
them to know the faith that gave them victory over the world,
that purified their hearts, held in a pure conscience.
And this is the Quakers`' light, which teacheth them the path of the apostles;
and it teacheth men to be holy, as God is holy, and perfect, as he is perfect.
This was the light of Christ, and the apostles bid them to be as Christ is, and said,
'`as he is,
so are we in this present world.`' And the light that guides
the Quakers doth not teach them to deny prayer,
but brings them to pray aright, with the spirit and with the understanding;
without which all prayers are in the hypocrisy.

[.discourse-part]
_Principle._ He saith, '`We acknowledge there is a thousand perfect men in England,
as perfect as children, tossed to and fro,`' page 40. But he saith,
'`I deny that any man hath that perfect knowledge of Christ in this life,`' etc.

[.discourse-part]
_Answer._ '`Christ is in you except ye be reprobates.`' And the
scripture speaks of such as had both the son and the Father.
And all those children that are tossed to and fro,
are carried about with the windy doctrine,
which hath got up in the apostacy since the days of the apostles,
among them that are ravened from the spirit of God.
Such their doctrines are windy, and do not settle, nor perfect,
nor '`bring into the unity of the faith, nor the knowledge of the son of God,
the faith that gives the victory;`' nor to a perfect man,
nor '`to the measure of the stature of the fulness of Christ,`' which
was the work of the true ministry which was before the apostacy.
None come to the knowledge of Christ but by the light.

[.discourse-part]
_Principle._ He saith, '`The church teacheth to pray without ceasing; but you bid,
stay till the spirit moves us,`' etc.

[.discourse-part]
_Answer._ The church, which is the pillar and ground of truth, prays not without the spirit.
And such as pray without the spirit, pray without understanding.
And they that pray as the spirit doth move them, know what they ought to pray for.
So every man that cometh into the world,
'`being in the light that lighteth every man,`' it will direct him to pray,
and to pray aright, and to ask in the name of Christ, '`who is the way to the Father.`'

[.discourse-part]
_Principle._ He saith, '`The children of God never assumed to themselves an infallible spirit.`'

[.discourse-part]
_Answer._ Did not the apostles say,
'`they that had not the spirit of Christ were none of his?`' and was not that infallible?
And were not all the scriptures given forth from the spirit of God,
and is not that infallible?

[.discourse-part]
_Principle._ '`The spirit of Christ is a spirit of wisdom, and a rational spirit.
The light that brags of an infallible spirit, and cannot speak sense nor reason,
is the spirit of Satan,`' page 46.

[.discourse-part]
_Answer._ The spirit of Christ that was in the apostles, which led them to speak to the world,
who were in their own wisdom, knowledge, and understanding,
was always judged foolishness by that wisdom, knowledge, and understanding;
for they ministered to the spirits in prison.
And Christ the covenant of God, who was promised to come,
and who should say to the prisoners,
'`show yourselves forth,`' was accounted as a madman by the wise Jews;
and the apostles and prophets likewise were accounted as fools.
Were not the saints ever judged, by the sense and reason of the world, to be madmen,
and fools?
Christ, a madman?
the prophets, fools?
and the apostles mad, and babblers?
They who are in the spirit of the prophets, of Christ, and the apostles,
by this generation are judged the same.
So is the spirit of the Quakers tried and know of all men;
the witness in all men`'s consciences shall answer them.

[.discourse-part]
_Principle._ '`Thou shalt not muzzle the mouth of the ox that treadeth out the corn.
And they that plough in hope, and thresh in hope, are made partakers of their hope.
And we are denied our corn, and are fain to go to the magistrates, our nursing fathers.
And so we thresh half a year, and can get no wages,
then are we fain to go to the magistrate,`' page 47.

[.discourse-part]
_Answer._ How can you thresh or plough, and have not the infallible spirit?
Can any get out the corn, or the wheat, that have not the infallible spirit?
Now we say, they that have not the infallible spirit cannot get out the corn;
they may beat the air, they may get the sheep`'s clothing upon their backs, and go out,
and beat the air; and so when their gospel will not maintain them,
then they are fain to fly to the magistrate; and to the hills,
that must be beaten as chaff, because they cannot live of the gospel they preach;
which doth not open the hearts of people, doth not get out the seed of God.

[.discourse-part]
_Principle._ He saith,
'`The Quakers`' light condemns such as the light of Christ approves.`' And saith,
'`Tell us what it is to walk holily, as the holy men of God did,`' etc. page 49.

[.discourse-part]
_Answer._ Who walk holily, walk in the spirit that the holy men walked in,
that gave forth the scriptures, which spirit is infallible.
And none walk holily, but who are led by that, out of the self righteousness.
And the light which the Quakers are in,
is the light with which Christ doth enlighten every man that cometh into the world,
which cometh from Christ, and is one with him.
And no one upon the earth owns Christ but who owns the '`light which doth enlighten
every man that cometh into the world,`' which the Quakers are in,
which thou calls a light from Satan.
And they must all come to the Quakers, if ever they own the light,
and if ever they own Christ the way to the Father, and come into the power of godliness.

[.discourse-part]
_Principle._ He saith, '`It is wretchedness to say that Christ hath redeemed them perfectly,
and now lives in them the Lord of all things,
by which they are the sons of God,`' page 50.

[.discourse-part]
_Answer._ The scripture saith, he is '`in all and through all,
who is God blessed forever.`' And are not they who are redeemed,
redeemed into perfection, into Christ?
are not they redeemed perfectly?
are not they redeemed out of imperfection?
And doth not Christ, who is Lord of all, say, he will dwell in the saints?
And are not all they in the wretched state, that will not have him to reign over them?

[.discourse-part]
_Principle._ He saith, '`The ministers of Christ received the gospel not by man,
nor were taught it, but by the revelation of Jesus Christ,
but we own no such revelation as this,`' page 51.

[.discourse-part]
_Answer._ We do believe you, who are apostatized and ravened from the spirit of God,
having only the sheep`'s clothing, and are the wolves gone abroad in the world, who,
if it were possible, would deceive the very elect:
but the elect are kept in the arm of Christ,
ye cannot pluck one of them out of his hands: his Father and he is greater than all.
And none know the gospel, but who know immediate revelation;
for the gospel is the power of God unto salvation, and this is immediate.
And so all you in the apostacy, since the days of the apostles,
are gone from the foundation, Christ Jesus,
that doth enlighten every man that cometh in the world,
with it you are all seen and fathomed, over the world doth the light reach,
answered with that of God in every one, the salvation to the ends of the earth;
which light cometh to fulfill scriptures.
The apostles were judged deceivers;
who came to bring the people to the substance the scriptures spoke of;
so they were judged deceivers.

[.discourse-part]
_Principle._ '`If the Quakers say that the ministers have not
the spirit that the prophets and apostles had,
then positively we say we have not.
And if the Quakers say they have it so,
then I say the prophets and apostles had it not,`' page 53.

[.discourse-part]
_Answer._ We do believe you, that ye have not the same spirit that the prophets, and apostles,
and Christ had: this is made manifest in that ye are all on heaps about their words,
and are fain to run to schools and colleges to be made ministers by men,
and not by the spirit.
But the Quakers witness the spirit that the prophets, and apostles, and Christ had,
with which they own their words;
with which spirit they see you who have gotten their words, and make a trade of them,
and are all on heaps about them, and fall out about church and ministers.

[.discourse-part]
_Principle._ He saith, '`The infallible spirit did not guide Isaac when he blessed Jacob,
for he missed the person,`' page 53.

[.discourse-part]
_Answer._ God with his eternal spirit did direct Isaac what to do,
for that stood in his counsel, though of that spirit thou hast shown thy ignorance,
and thy fallibility,
and thyself to be one of them in whom the devil is transformed into an angel of light;
which Christ said should come, the false prophets, and deceivers, and false apostles;
which the apostles saw were come, which, since their days,
have had the reign over the world.
But now to that which they ravened from, and into the truth,
(in which the devil abode not,) are the saints come;
and the Lamb reigns that is the substance of the scriptures, the end of the scriptures,
that hath dominion.
Glory in the highest forever.

[.small-break]
'''

And as for all the revilings, lies, slanders, vilifying, hard expressions in thy book,
they will fall upon thyself, and to thee they will be sad,
and thou shalt feel that every one of thy own words shall be thy burden,
and they shall come home unto thee;
in the day of thy judgment the witness in thee shall answer.
All along thou hast showed thy ignorance of the infallible spirit,
that is poured upon all flesh; for whosoever prays, or hath a humility, or sings,
and not by the infallible spirit, they sing not with the understanding,
nor pray with the understanding.
And under the judgment of God thou hast brought thyself, and all thy generation.
