[.style-blurb, short="Dialogue between a Minister of the Gospel and a Christian"]
== Thomas Collier`'s book, called [.book-title]#A Dialogue between a Minister of the Gospel, and an Inquiring Christian.# His principles follow.

[.discourse-part]
_Principle._ He saith, '`that the scriptures are the absolute rule of saints,
that are endued with the spirit and faith,`' page 7.

[.discourse-part]
_Answer._ Such as were endued with the spirit and faith,
had a rule before the written scripture was, and they knew the seed,
and they knew the promises,
and they knew Christ more than the Pharisees that had the scriptures:
nay more than the apostates since the days of the apostles that have the scriptures,
and the Epistles, and Revelations.
For by faith they saw the glory, they were in the foundation,
they say Christ the everlasting covenant, and that is the foundation still, Christ Jesus,
him by whom the world was made; and all that have the scriptures, and have not him,
they can do nothing.
And that which ruled the saints before the scriptures were written,
is the saints`' rule after the scriptures are written, to know what is written,
and to know God of whom they learned that gave it forth, or wrote it:
with that they know to what state and condition it was spoken.
And the spirit is the record, and he that hath all the scriptures,
and wants the true record, which is the spirit, he cannot know all things.

[.discourse-part]
_Principle._ '`And the scripture of the New Testament is the saints`' rule,
and rule of judgment,`' page 10.

[.discourse-part]
_Answer._ The scriptures being given forth from the spirit of God,
people know not to what state they were spoken,
but as they come into the spirit that gave them forth.
And besides, the epistles were written to the saints in several conditions,
according to their growth: and some of them grew higher than others,
for in the hearts of some of them the day-star was not risen,
and some of them were children of the day.
So that still was the rule that led them to give forth the epistles,
and revealed to them the states and conditions of the saints, and to ages,
and to generations, and to nations, and the condition the world was in,
and should come upon it, that was the rule,
and is the rule by which all these words are seen again:
and there is the record of the spirit of God.
And he that hath found the true record, the spirit of God,
with this he shall know all the scriptures;
and is come within the book where all things are written,
and which writes all things forth, the spirit.

[.discourse-part]
_Principle._ He saith,
'`The scriptures are that word which makes the devils to stand in awe and tremble.
The written word for after generations,
by which men`'s souls are brought to Christ,`' pages 14, 15. Again,
'`the scriptures are the sword of the spirit,`' page 16.

[.discourse-part]
_Answer._ The Pharisees had the scriptures, which Christ said were of the devil,
and were swallowed up in his power; and they stood against Christ, the life,
the substance.
The devil came with scriptures (who is out of the truth) to tempt Christ the word:
but the word, the substance of scriptures, hammered down the devil,
and the Pharisees that had got the scriptures,
but were out of the life that gave them forth.
And they have the sword that have the word of God,
which was before the scriptures were given forth,
and they are in that the devils are out of.
So if the devil, and wicked men, bring scriptures, they hammer them under,
and redeem the scriptures out of their ungodly mouths.
And the written word brings no soul to Christ the life,
but who comes to the life that the written words speak of: and so it testifies of him,
the life, that brings them to Christ that gave it forth.

[.discourse-part]
_Principle._ '`God is willing that all should be saved;
but he worketh not all into a saving condition.`' See page 21. He saith, '`It is true,
there is a spirit and life in the scriptures.`' See page 22.

[.discourse-part]
_Answer._ The spirit and life are not in the scriptures,
but the spirit and life the scriptures testify of; and the light, Christ Jesus,
(the salvation to the ends of the earth,) doth enlighten
every man that cometh into the world with a saving light.
And the light which every man hath that cometh into the world is saving:
but many hating the light which hath enlightened them, and not coming to it,
neglect and slight their salvation, and not believing in it, they walk in darkness,
and come not to the light of life.
But they that believe in it, come to the light of life, and abide not in the darkness.
And '`the grace of God which brings salvation hath
appeared to all men.`' Such as turn it into wantonness,
and walk despitefully against the spirit of grace, own it not for their teacher,
but set up teachers according to their own lusts;
so turn against that which brings their salvation, and walk despitefully against it,
and follow their own lusts, and trample upon the covenant of grace,
and the blood of the new covenant.
And all that see the bishop of their souls, Christ Jesus the saviour of their souls,
it is with the light that cometh from him; and God wills that all men should be saved.

[.discourse-part]
_Principle._ He saith, '`To use Christ`'s name to catch souls, when indeed it is but juggling,
and to stab him,
and crucify him afresh.`' See page 42. '`If Christ
doth enlighten every man that cometh into the world,
etc. if this were truth, then Christ died in vain,
and in vain hath Christ spoke of himself, saying, I am the way, the truth, the life,
the light,`' etc.
See page 45.

[.discourse-part]
_Answer._ Such as do not believe that Christ doth enlighten
every man that cometh into the world,
such as mention his naive, and are haters of the light that cometh from him,
are in the juggling state, and deceivers of the souls of people.
And none see Christ the one offering, but with the light that cometh from him:
nor do any know the saviour Christ Jesus, but with the light that cometh from him:
and that lets them see the body prepared, Christ who was the seed of Abraham,
according to the flesh, the one offering, that ends all offerings;
and his blood that is the atonement, is the saints`' drink, which, who drinks,
shall live, with which their consciences are purged from dead works,
to serve the living God.
And no one knows the foundation of God that standeth sure, nor feels it, nor sees it,
but with the light which cometh from Christ the foundation,
which breaks down all other foundation; which light that every man is enlightened withal,
gives him the knowledge of the foundation of God.

[.discourse-part]
_Principle._ He saith, '`I do believe that there was never a saint perfectly free from sin here;
but they shall have the body of sin and death,
which will be their burden to keep them humble.`' See page 52.
'`And it doth not appear that they attain purification,
or perfection, before the change of body.`'

[.discourse-part]
_Answer._ That which is the true humiliation bears the sin and iniquity, and is Christ;
such as are not brought down with the judgments for their sinful actings,
never knew the seed that puts off the body,
(from which all the roots proceed,) in that is the true humility,
and the righteousness of Christ, and the glory, revealed.
And the saints witnessed the body of sin and death put off,
while they were upon the earth; and such as were in Christ were new creatures,
all things had become new.
And the apostles spoke wisdom among them that were perfect;
and that was before the change of the body, ye speak of.
And the work of the ministry was '`for the perfecting of the saints,
until they all came into the unity of the faith,
(that gives victory,) and to the knowledge of the son of God;
unto a perfect man unto the measure;
and stature of the fulness of Christ.`' This was the ministers`' work.
Not as children tossed up and down with every slight, and windy doctrine of men,
who lie in wait to deceive.
So ye have tried the work of your ministry, and brought it to the light.

[.discourse-part]
_Principle._ He saith, '`Such a trembling as a way to perfection,
is to set it in the room of Christ, beside the truth,
and slight and undervalue the word of God:
and let all men beware of this trembling.`' See page 78.

[.discourse-part]
_Answer._ All who own the word of God, that reconciles to the Father, and hammers down,
and brings out of the fall, and cuts down and burns up,
must know their salvation wrought out with fear and trembling.
And these own the word of God, and the words of God, the scriptures:
and these own this trembling: there is a cloud of witnesses in the scriptures.
And none will deny this trembling that own the salvation wrought out,
or to be wrought out: but such as are out of the truth; and they that get scriptures,
(being out of the truth,) and deny the power of God, are with it judged.
Those that have the form, but deny the power, deny the trembling,
so they deny the salvation to be wrought out with fear and trembling,
and none know the salvation but they that know trembling.
And such may say,
(that are the devil`'s messengers,) beware of this power that makes to tremble.

[.discourse-part]
_Principle._ He saith, '`The scripture is truly the ministry of the spirit to us.`' See page 67.

[.discourse-part]
_Answer._ Those were the ministers of the spirit that gave forth the scriptures:
and those are the ministers of the letter,
that are out of the spirit that gave forth the scriptures,
and that cannot minister the spirit.

[.discourse-part]
_Principle._ He saith, '`The scriptures do not speak of a general redemption of all,
from the state of sin, and freedom from sin.`' See page 75.

[.discourse-part]
_Answer._ There is a general state and redemption of all, and freedom from sin,
by believing in the one offering, the blood of Jesus Christ; and unbelief shuts out.

[.discourse-part]
_Principle._ He saith, '`Mystical Babylon shall fall by the kings of the earth.
And many precious saints shall destroy Babylon with the sword.`'
See page 84. And he saith,
'`I cannot apprehend that the saints shall have the government of the world.`'
See page 86.
'`And the beast when he ariseth shall give a mark in the right hand,`' etc.

[.discourse-part]
_Answer._ Christ hath all power in heaven and earth given to him; they who believe in him,
and are in his power, who hath all power in heaven and earth given to him,
have the government, and are in the government, the Lamb`'s government:
but the unbelievers are out of it.
And that which slays mystical Babylon is not the kings of the earth,
and the saints that are on the earth slay not with the carnal sword:
for '`they that kill with the sword, must perish with the sword.`' Here is the faith,
and patience of the saints:`' their '`weapons are not carnal, but spiritual,
mighty through God to the pulling down of strong
holds.`' And the Lamb slays and kills with the sword,
and takes the beast, and the false prophet, and the devil,
and casts them alive into the lake of fire, where they shall be tormented forever,
that burns with brimstone, who '`kills and slays with the sword,
which is the words of his mouth.`' And the beast hath been long up, his marks,
and his heads and horns, with his names, but,
the Lamb and the saints are trampling him to pieces under,
and getting the victory over him.
And the everlasting gospel is preaching: and the witnesses you are ignorant of;
but are those that have been the slayers of them.

[.discourse-part]
_Principle._ He saith, '`I do not profess myself infallible,
but I shall freely give my apprehensions.`' See page 110. '`To
contend earnestly for the faith which is the first unto justification
and services of faith.`' See page 111. He saith,
'`False Christs, and false prophets shall come.`' And '`to the law,
and to the testimony,`' etc.

[.discourse-part]
_Answer._ The law is light,
and '`the testimony of Jesus is the spirit of prophecy;`' and men
may have all the scriptures of the Old and New Testament,
yet being from the light, the spirit of prophecy, they know not the law and testimony.
And we do believe thee, that thou art not infallible, but art only in the apprehensions;
and before thou comest to contend for the faith,
and to know that by which the saints are justified,
thou must come into the '`light that doth enlighten every
man,`' etc. which lets see Christ the author of the faith.
And Christ said false prophets and antichrists should come,
which should get the sheep`'s clothing, and say, '`Lo, Christ is here,
and lo he is there!`' These, Christ said to the apostles should come,
who before their decease did come; who, since their decease, the world hath gone after.
So every man that cometh into the world being enlightened,
and having a light from Christ the saviour of the soul,
every man being in the light Christ hath enlightened him withal,
with the light which cometh from Christ, he shall see a saviour, Christ Jesus,
from whom it comes; and shall see the light shining from the east to the west,
and the coming of the son of man, and receive Christ, and so come to the rock.
And so people having been from the '`light which every man is enlightened
withal that cometh into the world,`' they have been all brought on heaps.
But now they are coming to the rock.
And thy words, Thomas Collier, shall be thy own burden,
and for them thou shalt receive judgment.
And this is the word of the Lord God to thee, and thy time is not yet past.
