[#ch-35.style-blurb, short="Strong Comforts for Weak Christians"]
== John Billingsley, who calls himself '`Master of Arts, Minister of the Gospel, and Pastor of the Church at Chesterfield,`' in his book called, [.book-title]#Strong Comforts for Weak Christians.# His principles follow.

[.discourse-part]
_Principle._ He saith,
'`He would have the mayor and aldermen of Chesterfield to show themselves to
be really affected to the cause of Christ and his blessed sabbaths,`' etc.

[.discourse-part]
_Answer._ In this thou hast shown thou art one of those that keep people in darkness,
and not a minister of the gospel of Christ, and the new covenant, but of the law,
and in the signs and shadows.
For the apostles did bring people off from the sabbaths,
and they met together on the first day of the week, and denied the Jews`' sabbath;
and still it is your practice,
and yet thou criest up '`to show themselves for the cause
of the blessed sabbath.`' What blind and dark stuff is this?
For never did pastor or minister of Christ preach up such a doctrine,
as to stir up aldermen and mayors, and great men,
to show themselves zealous for the sabbath.
And thus thou hast showed thyself to be one of them the apostle was afraid of,
that observed the days, which he brought the people off from, to the substance;
they met together on the first day of the week, which Christ rose on,
and so was a cross to the Jews, who met together on the seventh day.
And circumcision was on the eighth day, on that day Christ rose.

[.discourse-part]
_Principle._ He saith, '`The scripture and the spirit are inseparable, (which he calls the word,
page 7,) and that the spirit is always in the scriptures.`' Again,
'`He is in the gall of bitterness, and bond of iniquity,
who calls the spirit a dead letter,`' page 9.

[.discourse-part]
_Answer._ Every one that hath the scriptures cannot say he hath the spirit that gave them forth;
for the devil may have scripture, who is out of the spirit.
And the apostle who said the letter killed, and was old,
was not in the gall of bitterness, and bond of iniquity.
The spirit was in them that gave forth the scriptures:
and the scriptures are the words of God, which end in Christ the word, who fulfils them.

[.discourse-part]
_Principle._ He saith, '`Prize the holy scriptures,
through which are all our hopes of eternal life communicated to us.
And I wonder what any soul hath to show for eternal life but the scriptures.
So I call it God`'s warrant,`' page 13. And '`in the midst
of thoughts prize the covenant of free grace.
And if ye would have substantial comforts from the covenant,
do but lay hold of covenant comforts,`' page 12.

[.discourse-part]
_Answer._ Thou canst not speak a word to the wearied, who art in the presumption thyself,
and to be brought down, who art applying the promises to the wrong nature.
Many may have the scriptures, and many have the scriptures,
and all ignorant of eternal life,
until they come into the life that they were in that gave forth the scriptures.
For the scripture communicates not the life, but God,
of whom they learned that gave forth scripture;
it is the life that testifies of eternal life.
And the soul`'s comfort is Christ, which the scripture speaks of.

[.discourse-part]
_Principle._ He saith, '`The apostle to the Philippians speaks of saints as citizens,
our trading is in heaven.
Now citizens`' great trading is in merchandise, as ships go from London to India, etc.
'`So thousands of souls go towards heaven worth nothing,
a poor empty creature.`' See page 15.

[.discourse-part]
_Answer._ The merchandise is in the earth, in Babylon, and there thou and you all are.
The soul is worth more than all the world; if it goes to heaven, it goes richly,
full of all attire and fruitfulness, and not empty.
Is not an empty creature that into which God breathed the breath of life,
whereby it became a living soul?
And he hath all souls in his hand, and Christ is the bishop of it, the power of God,
and therefore it is not empty;
for the saints had the heavenly treasure in earthen vessels.

[.discourse-part]
_Principle._ He saith, '`The sacrament and baptism is a most refreshing cup, for we walk by faith,
and not by sight,`' page 18. '`I can say frequent mention is made of salvation by Christ,
without mentioning any act of faith in us,`' etc. page 19.

[.discourse-part]
_Answer._ Sacraments, and sprinkling infants, called baptism, who walk after them,
walk by sight, not by faith, for these things are seen;
and they follow their own traditions,
and not the scriptures for either sprinkling infants or sacrament.
And who walk by faith, and not by sight, come off the things that are seen.
For the things that are seen are temporal,
but the things that are not seen are eternal,`' saith the apostle.
And '`he that believeth shall be saved,
and he that believeth not shall be condemned,`' (this is the doctrine
of Christ to the apostles,) they are condemned already.
And where the belief is, there are faith and salvation seen and known;
but where belief is not, there is condemnation, there salvation is not known,
and every one that is saved, believes.

[.discourse-part]
_Principle._ '`I do not say that there is perfect victory against every corruption;
but that grace will be eating out,
and curbing sin in the heart,`' page 21. And '`there is no peace
nor comfort that is maintained without warring and constant combatting, etc.
Yea, peace, and war against sin,
are always inseparable companions,`' page 22. '`All true
comfort hath its foundation from the written word;
they are fancies and flashes, rather than comforts,
from pretended immediate revelations,`' page 23.

[.discourse-part]
_Answer._ None know true comfort but who come to immediate revelation, that is,
to the spirit that reveals the things of God.
If men have all the scriptures, the written words, and not the word in which they end,
they have not comfort, neither can they do any thing without Christ,
neither have the wearied rest, neither is the bishop of the soul known,
neither is the burden and the old yoke gone off, though they have all the scriptures.
But as every one comes to the life that gave forth the scriptures,
with which they see Christ the end, the substance of them,
him by whom the world was made before it was made, these have comfort of the words.
And the scriptures are words, not the word;
and such as are here come to know peace and the end of war,
and the occasion of war taken away.
And sin and corruption are separated from the precious, and contrary to the just.
There is no unity between them.
And there is no true peace until they come into the kingdom which stands in joy,
in peace, in righteousness.
Now where the body is standing, and the root of sin in the heart,
there is not a perfect victory; the circumcision is not known that puts off the body,
and the victory is not known while the body stands.
The apostle witnessed the body of sin put off by the circumcision
of the spirit which was in the inward man,
and he thanked God through Christ who had given him the victory,
who was manifested in his flesh to condemn sin in his flesh,
that he through him became the righteousness of God.
And the life that he lived was by the faith of the son of God.
And such as are made free from sin, and dead to it, and cannot live any longer therein,
these have peace.
And such have not peace where the body of sin is standing, and sin in the heart;
there is the war.
But such as stand in the faith which purifies the heart,
and come to witness the circumcision of the heart, come to have the heart purified,
and the victory over the body, as the apostle declares.

[.discourse-part]
_Principle._ He saith, '`James Nayler deserved to be hanged,`' page 5. And saith,
'`I telling people they cannot be free from sin,
a perfect freedom from the being of corruption in them while they are
on this side heaven,`' page 9. '`And your speaking against ministers,
and speaking in markets is as bad or worse as to bait a bull,`' page 8. And he saith,
'`the steeple-house is the church.`'

[.discourse-part]
_Answer._ The ministers of Christ and the prophets of the Lord, who spoke his word,
spoke in synagogues and in markets, in highways, and under the hedges,
and upon the mountains, which disturbed the world,
and all professors upon the earth that had the words of truth, but were out of the life;
and they disturbed the heathen that knew not God.
And all such ministers of the letter, that have it and not the spirit that gave it forth,
are disturbed by the ministers that are in the spirit,
that preach and speak forth the substance of the scriptures.
And we know you, and do believe you (who say,
'`your people shall not be made free from their corruption;`' and tell them,
'`the steeple-house is the church;`' and say the creature
deserved to be hanged) to be such as inwardly ravened,
which Christ said should come, John saw were come, and the whole world went after;
you are wrestlers against flesh and blood, and strike at creatures,
instead of striking at the power that captivates creatures,
and so have kept people under the bondage of corruption, '`always learning,
and never able to come to the knowledge of the truth,`'
and have kept them in spiritual Egypt,
Sodom, and Gomorrah, and in filthiness, telling them the steeple-house is the church.
Was it not a place for the mass, set up for the mass, with a cross at the end of it?
Look! is it not on yet?
And is the mass-house become thy church?
thou mayst thank the Papists for that.
Were not the pope and the Papists the setters up of all your mass-houses, and colleges,
which have gotten up since the days of the apostles,
among you inwardly raveners from the church which is in God?
So you have got up the mass-house for your church,
and there ye tell people they must have corruptions while they be upon the earth!
So ye are ministers of corruption, which is contrary to the apostles,
who said they '`sat in heavenly places,`' and had escaped the pollutions of the world;
and they were children of the day, and not of the night, and the true light shined.
So you that are ravened from the spirit of God, have got up the mass-house,
got people thither, and tell them they must have their corruptions,
and they must have sin, and they must not be perfect while they are on this side heaven.
Now they can but have sin, and can be but imperfect, if they never came to you,
nor to your mass-houses.
Are not you the devil`'s messengers and ministers that preach up sin, and corruption,
and imperfection, that people must be in, and have sin while they be upon the earth?
The ministers of Christ preached up perfection and an overcoming of sin,
and a being made free from sin;
and '`the blood of Jesus Christ cleanseth from all sin;`' and they had faith,
which gave them victory, and the circumcision that puts off the body of sin,
and the new covenant that blotted out sin and transgression.
And such ministers as you, that make a trade of scriptures, the scripture itself,
the prophets, apostles, and Christ,
manifest your fruits to be contrary to them that gave forth scriptures.
So by the scripture are you disapproved and judged, and by the life that gave it forth.

[.discourse-part]
_Principle._ He saith, '`And it seems to me to be no more sin to bait a bull,
than any other recreation.`' And saith, '`The Quakers came in to the steeple-house,
and bid people to look to the light within them,
and told him that he was an antichrist and blind guide.`' And saith,
'`I had rather be a hireling, such as Christ hath hired in his vineyard,
and receive a penny, than some of the Quakers that go naked in the markets.`'

[.discourse-part]
_Answer._ The Quakers who are in the power of the Lord God,
have been moved of the Lord God to go into the world among apostates,
who are ravened from the spirit of God, and are the wolves that tear and rend,
and are ravening up and down for your benefices,
and would eat one another out if you could, and swallow one another,
like fishes in the sea.
Are you contented every one with your penny from Christ?
Are not you all fighting, and striking, and smiting, and casting into prison for means,
for tithes, which ye do no work for?
Is not Christ come, and hath found you smiting and striking your fellow servants;
eating and drinking, like Sodom; and living in pleasure, like the old world;
some having two hundred, some three hundred pounds, some less, some more?
is this equal?
'`is this to each a penny?`' Are ye like Christ`'s vineyard dressers,
his husband-men in the vineyard?
Blush, and be ashamed!
The stones are thrown now at Babylon, and dash her children to pieces.
And Zion is building, and the tabernacle of David is rearing up.
Come up ye saints, and prophets!
The lamb and the saints have the victory.
And you and all upon the earth are the blind guides and antichrists,
who guide not people to the light within,`' and you who bid them not look at that,
but lead them from the light within, ye lead them in the darkness,
and you are from the light in your own particulars, and so the blind guides;
for the fleece for the earth, out of the apostles`' doctrine, and Christ`'s,
who brought people to the light, and bid them believe in it; who told them,
the light that shined in their hearts would give them '`the light
of the knowledge of the glory of God in the face of Christ Jesus.`'

[.discourse-part]
_Principle._ '`The priests bear rule by their means;
this is the means of the false prophets,`' saith he.
'`If paying tithes be a burden, lay it upon God and the magistrates, and not upon me,
the pastor.`'

[.discourse-part]
_Answer._ Tithes were given to the similitude, Melchisedeck,
and to the priesthood made by the law of God; but Christ is come,
the end of the similitude, the end of the priesthood,
and has disannuled the commandment that gave tithes: and all his ministers, pastors,
and teachers preached down tithes, and preached up the substance,
and preached down the priests that took them, and the law that gave them,
and the authority and the magistrates that held them up.
And so you that have gotten tithes since the days of the apostles,
the root and ground of which are from the Papists in the apostacy,
are such that burden the creation,
and a grief to all true christians that are in the life, power,
and spirit that the apostles were in before the apostacy.

Now if thou wert a true minister of Christ, if the magistrates would give thee tithes,
thou wouldst not take them; which are got up since the apostles came in,
among them that have got the sheep`'s clothing, but are ravened from the spirit of God.
And dost not thou think if the priests that were obedient to the faith,
had turned again to the Jews`' magistrates, they would have given them tithes?
And dost thou think that any of them that were obedient to the faith,
took tithes after they were converted to Christ and his faith, the substance?
And dost thou think that any that are out of the apostacy now,
will take tithes of the magistrates if they would give them?
which were set up since the days of the apostles in the apostacy?
I will warrant thee they will die before they will lose their glory and their crown,
'`they that preach the gospel,
shall live of the gospel.`' And '`the prophets prophesy
falsely and the priests bear rule by their means.`' What!
Doth the priest receive his gift by the false prophet`'s means?
Do not the people love to have it so?
And are not you all found fallen into this ditch,
that are inwardly ravened from the spirit of God?
You are the false spirits gone into the earth for money, and for tithes, for lucre,
for means, for gifts,
'`admiring men`'s persons because of advantage;`'
yet covering yourselves with the sheep`'s clothing.
You have crept into a mass-house and call it a church; and tell people,
'`while they be upon the earth, they must have corruptions,
and the body of sin,`' and this is the work of your ministry: so you are among the liars,
whoremongers, sorcerers, adulterers, out of the kingdom ye are found.

[.small-break]
'''

And as for all the rest of thy rabble, and unsavoury expressions in thy book,
they are not worth mentioning.
But in the day of thy judgment thou shalt feel thy own words thy burden;
in the trial of the fire thy works will burn.
