[#ch-36.style-blurb, short="A Defence of the Scriptures"]
== Immanuel Bourne, who calls himself pastor of a church in Ashover, in his book called [.book-title]#A Defence of the Scriptures, and the Holy Spirit Speaking in Them,# are these principles following. And priest Gifford of Bedford his principle.

[.discourse-part]
P+++.+++ He saith, '`Christ himself sent his hearers to the scriptures,
as the chief judge of controversy, and of faith.`'

[.discourse-part]
A+++.+++ Christ did not put the scriptures above himself; he said,
'`all judgment was committed to the son,
and for judgment he was come into the world.`' And the Pharisees
that had the scriptures could not judge of faith,
nor of controversy, nor knew Christ the author of the faith;
nor can any judge but who are in the spirit that gave forth the scriptures.
And the scriptures were given forth from them that were in the faith of truth;
but such as are not in the faith, know not the scriptures,
neither is it able '`to make them wise unto salvation`' without the faith.
For the Pharisees and chief priests were not made so, though they had scripture;
but they that had scriptures without the life, judged and condemned the author of faith;
and so do all that are out of the life still, that have the scriptures,
judge the author of the faith, Christ Jesus,
'`who doth enlighten every man that cometh into the world.`' And
the holy spirit spake in them that gave forth the scriptures,
and so they spake it forth.

Now they that are from the spirit of God in their
own particulars and know it not speaking there,
know not the spirit that spoke in them that spoke them forth; but such are they that say,
'`The spirit speaks in the scriptures.`' Such are ministers of the letter,
and not of the spirit that gave it forth.
And the spirit that gave forth the scripture is that which judged of all conditions,
which gave the spiritual understanding.
For people have not the spiritual understanding to judge; and to discern,
if they have all the scriptures, unless they be in the spirit that gave them forth.
And so the scripture itself without the spirit that gave it forth,
cannot be the judge of controversy, nor of faith, but is a dead letter in itself;
but the spirit is it that gave forth scriptures.

[.discourse-part]
P+++.+++ He saith,
'`Christ within is inherent holiness.`' And '`George
Fox professed equality with God,`' page 20.

[.discourse-part]
A+++.+++ Christ within is beyond all men`'s righteousness or holiness,
for he is the righteousness itself.
And the assembly of divines gave forth a catechism, presented to the parliament,
for people to learn; wherein they say,
'`that the holy ghost is equal in power and glory with the
Father.`' Now all that come to witness the son of God,
and the holy ghost that gave forth the scriptures,
by your account they witness that which is equal in power and glory with God.
And do not the assembly give forth this in their catechism, that people should learn it?
And is it blasphemy to come to witness this which you have given forth,
and the mind which was in Christ?
Yet nevertheless George`'s words were not spoken as ye preach them;
for his words were spoken beyond all creatures, and out of all creatures,
and he did not say '`George Fox.`'

[.discourse-part]
P+++.+++ He saith, '`No natural man, that is darkness,
is bound to look to the light within him to direct him to salvation;
for it is in vain to look for light in darkness,`' page 22.

[.discourse-part]
A+++.+++ The light which every man that cometh into the world is enlightened with,
is the salvation to the ends of the earth; no man cometh out of darkness,
out of his natural state, but who doth believe in the light.
This was Christ`'s doctrine, '`Believe in the light,
that ye may be the children of the light:`' and '`he that believeth in it shall
not abide in darkness.`' And so they come to see the spending of the night,
and the light shining out of darkness,
giving them '`the light of the knowledge of the glory of God in
the face of Christ Jesus;`' and the light shining in the darkness,
which darkness cannot comprehend it.
And no one upon earth ever sees his salvation,
but with the light which cometh from Christ his saviour,
who doth enlighten every man that cometh into the world,
that all men through the light might believe: he that doth not believe in the light,
is condemned.
And so he that follows the light shall not walk in darkness;
and he that follows not the light walks in darkness.
So with the light thou are comprehended to be a minister of darkness, in the apostacy,
keeping people from the light; and one of the false prophets ravened from the spirit,
which Christ said should come, John saw were come, and the world goes after you,
who tell people the letter is the word, and the spirit is in the scriptures;
which is contrary to scripture, and them that spoke it forth,
who said the spirit of God was within them.
And the scriptures are words of God: and Christ the word, comes to fulfill the words;
who is the word that was before the words were given forth; in whom the words end.

[.discourse-part]
P+++.+++ '`The kingdom of heaven is within you, not as Christ is in every one,
but the kingdom of heaven is within you, or among you,`' page 29.

[.discourse-part]
A+++.+++ Christ is within except ye be reprobates; yea, I say, within all professors is Christ,
in Christendom, Christ is within them all, except they be reprobates.
And if Christ be not within them all, they are all reprobates,
but if Christ be within them all, the body is dead; and where this is so,
there is Christ`'s reign, and his kingdom, and no Babylon, nor antichrist.
And '`the kingdom of heaven is within you,`' said Christ; yea, in the Pharisees:
and that is the kingdom in man that never consents to sin; like a grain of mustard seed,
like unto leaven, that leavens the new lump.
And he that cometh to know that little kingdom,
and receiveth that little kingdom as a little child,
it makes the kingdoms of the world become the son of God`'s kingdom: and know,
that no unrighteousness, nor ungodliness must enter into it.

[.discourse-part]
P+++.+++ '`And Christ spake to the multitude, when he said,
"`Be not ye of men called master,`" and "`Call no man father upon
earth;`" and did not bid the apostles not to be called of men master.`'

[.discourse-part]
A+++.+++ He spoke this to the multitude, and to the disciples both, and said,
the scribes and Pharisees were called of men master, who had scriptures;
whom he cried woe against.
And he said, '`Be not you of men called master; for ye have all one master, even Christ,
and ye are all brethren.`' This was Christ`'s command.
But all ye pastors, and ministers, Bourne, and the rest,
who are apostatized from the apostles`' doctrine, and Christ`'s doctrine,
ye trample upon the commands of Christ, it manifests that ye have the form of godliness,
but deny the power; and are not brethren passed from death to life,
but are all on heaps about the scriptures, Christ`'s, prophets`', and apostles`' words;
and making a trade of them for your own self-ends in the apostacy;
such as Christ said should come, who John saw were come, who should inwardly raven,
and the world is gone after.
But now with that which ye have all ravened from, are ye all comprehended.
And Christ said, '`Call no man father upon earth.`' Where Christ is witnessed,
the seed of God raised up, no earthly man is his father,
and cannot call any man father upon the earth, according to the command of Christ.
He that is heir of the promise of the world that hath no end, of the second Adam,
is born not by the will of man: but he that is of the first Adam is in another state,
and stands against Christ`'s doctrine, and is the son of Adam in the fall.

[.discourse-part]
P+++.+++ He saith, '`Such as pretend Christ within, deny the blood of Christ,
his righteousness for justification.`'

[.discourse-part]
A+++.+++ They who witness Christ within, are not reprobates;
justification and sanctification are possessed,
the thing that was imputed to the believers.

[.discourse-part]
P+++.+++ '`And giving honour to men,`' etc.

[.discourse-part]
A+++.+++ Christ the second Adam, receives not honour of men,
neither doth he respect men`'s persons; his enemies could say so.
They that received honour one of another, were the Pharisees, the great professors,
which was a mark of their unbelief.
But Christ would not receive their honour; the second Adam,
who doth enlighten every man that cometh into the world,
will not receive the honour of men.
Now he that receiveth the honour is out of the light, in the first Adam;
is out of the power.
And where humility is, which goes before honour, there is no want of honour;
for he cometh into the power that maketh him honourable in the hearts of all people,
answering the humble principle in every one; a terror to the evil doer.
And here magistrates that fear God,
attain the honour that is without the respect of persons,
in the humility answering with the higher power the just principle in every man:
so come they to be honoured in the hearts of all people, in the sight of God,
and a praise of them that do well; but he that respects persons, transgresseth the law,
and commits sin, and is convinced of the law as a transgressor.
He that respects persons is out of the faith of the Lord Jesus Christ,
which purifies the heart, which is held in the pure conscience,
and gives victory over the world; and who are of faith are of Abraham.

And so for all thy lies, and slanders, and revilings, and unsavoury and bad expressions,
they are loathsome before all sober people, and stink;
who hast published thy shame to the nation in print,
it shall cover thyself, and be thy own garment;
and every word be thy own burden,
and lay a weight upon thee in the day of thy misery, and calamity,
and in the day of thy judgment when thy works are tried in the fire;
the witness in thy conscience shall answer me.

[.discourse-part]
P+++.+++ Gifford, who is chief priest at Bedford, said openly,
'`That faith was not perfect,`' etc.

[.discourse-part]
A+++.+++ Faith is holy, and the gift of God, and purifies, and justifies, and is a mystery,
in which is the unity, by which God is pleased; and this is perfect,
being the gift of God; and from this he hath showed his reprobation, and his ignorance.
