[#ch-37.style-blurb, short="A Defence Against the Poison of Satan`'s Design"]
== Thomas Moore in his book, called [.book-title]#A Defence Against the Poison of Satan`'s Design.# These are his principles.

[.discourse-part]
_Principle._ He saith, '`Christ Jesus is personally absent from a believer.
And Christ is in and to our hearts the hope, but not the possession,
nor do we possess the glory.`' Again he saith,
'`The grace of God which brings salvation to all men,
instructs them not to look into themselves or to
any light or spirit in them.`' See page 5.

[.discourse-part]
_Answer._ '`Christ in you the hope of glory,`' saith the apostle.
And if the saints sat with him in heavenly places, they are not absent from him.
And if he say, '`I in them, and they in me,`' he is not absent from them.
And the son of God was revealed in the saints.
And '`he that hath not the son of God hath not life.`'
Such may say they are absent from him;
but such as have him revealed, have life, and he is not absent.
And such as are absent from him have not eaten his flesh, nor drunk his blood;
and so are not of his flesh, nor of his bone.
And they may talk of him, and say he is come, as the Jews did that he was to come,
and he not in them, and so reprobates.
And '`the grace of God that brings salvation,`' which hath
appeared unto all men,`' which is the saints`' teacher,
whose hearts are established with grace; this is within them,
which brings them to know the hidden man of the heart, and a strength in the inward.
And these come to look at the light within them, agreeably to the apostle`'s doctrine,
who said '`the light that shined in their hearts,
would give them the light of the knowledge of the glory of God
in the face of Christ Jesus.`' And such as have Christ in them,
have the possession, have the substance,
have the glory which was with the Father before the world began.

[.discourse-part]
_Principle._ He saith, '`There are none here have yet ceased from their own works,
as God did from his.`' See page 9. And the apostles
received the last revelation to be given forth immediately.
And such as slight the word, and call it a dead letter,
and bring people to the light within them, a spirit within them,
this is a strange doctrine.
And if there be not something to be added, and given forth by men,
and another manner of preaching than by the apostles,
what need is there of printing?`' etc.
See page 15.

[.discourse-part]
_Answer._ He that believes hath entered into his rest,
and ceased from his own works as God did from his.
And since the days of the apostles there hath got up another ministry by man and of man,
made by man, (which is not as the apostles, who received it not of man,
nor by man,) and these stand against the light within, and the spirit of God within,
without which none know true teaching, nor true instruction,
nor opening of the scriptures, but as they come every one to the spirit of God in them,
that was in them that gave forth scriptures.
And who are here, have the thing within them, as they had that gave forth the scriptures;
enjoying and possessing it.
And these fathom those who are apostates, out of the apostles`' doctrine;
and witness the preaching that the apostles were in,
which all they since the days of the apostles, that have ravened from the spirit of God,
are out of.
And these do not deny the scriptures, but see them all in their place,
and to what condition they were spoken.
And the letter is a dead letter of itself, and gives not life to any,
but those who come to the spirit of God in their own particulars,
that was in them that gave it forth.
For the Jews had not life, though they had scriptures, until they came to Christ,
which the scripture testified of.

[.discourse-part]
_Principle._ He saith, '`Christ is not natural.`'

[.discourse-part]
_Answer._ Yet some of you say he is human.
And as for thy speaking of his mortality, ye speak, ye do not know what;
Christ is the same today, yesterday, and forever.

[.discourse-part]
_Principle._ He saith, '`It is the apostle`'s sense of them that served their bellies,
they pretended to an inward light: and this is the apostle`'s sense of belly;
who did cause divisions contrary to the doctrine they had learned,
and here their belly may be understood their mind, heart, and spirit,
or also their experience of these inward, etc.
To rejoice in anything under the sun,
is opposite to the apostles who had their conversation in heaven.`' See page 42.

[.discourse-part]
_Answer._ None come to witness their conversation in heaven,
but who are come to witness Christ within them; the substance, the second Adam,
who redeems out of the earth.
And the apostle brought the saints to the light that shined in their hearts,
etc. and walking in this light was not a serving of bellies.
That light shining in them, and believing in the light Christ,
'`out of their belly flowed rivers of living waters;`' and such made not divisions,
but were in unity in the light, and in fellowship.
But those were they that made the divisions that inwardly ravened,
and went from the light, which Christ had enlightened them withal;
and such went from that which should give them the knowledge,
and enjoyed the earthly things, and served not the Lord Jesus Christ,
but their own bellies.
And they act contrary to the apostles`' doctrine; and rejoice in things under the sun,
which who do, serve their own bellies.

[.discourse-part]
_Principle._ He saith, '`Yea, when enlightened by that heavenly light, even from Jesus,
yet they are of themselves deceitful,`' etc.
See page 44. And '`the light is something else besides the light of the knowledge
of the glory of God in the face of Christ Jesus.`' See page 45.

[.discourse-part]
_Answer._ The light which every man is enlightened with, etc. is not deceitful,
but leads men out of all deceit.
And it is of God, that gives them the light of the knowledge of the glory of God,
etc. and it is one and the same that lets see to the beginning and ending;
which comes from the beginning.

[.discourse-part]
_Principle._ He saith,
'`That none may expect to receive the word immediately from Christ as the apostles;
but mediately,`' page 46.

[.discourse-part]
_Answer._ Such as receive not the word of God immediately from Christ as the apostles did;
are not preachers of the living word that lives and abides forever.
And we do believe you, that since the days of the apostles,
ye have not received the word immediately from Christ as the apostles did,
but are only ministers of the letter.
And such were they in all ages that closed their eyes, and stopped their ears,
and inwardly ravened from the spirit, that marred the face of Christ above all men;
who were in the spiritual Sodom and Egypt where Christ is crucified.
These got scriptures, but were from the spirit of God within, that gave them forth,
and such were the hypocrites that judged always the
spirit of God that gave forth the scriptures,
and shut out of the kingdom, in which spirit now ye are found in these last days.

[.discourse-part]
_Principle._ He saith, '`that Christ ascended without material blood,
and the apostle did not preach both the word and faith in the heart,`' page 50.
And '`that the new Jerusalem is not come down from heaven,`' page 51. And,
'`A brief discovery of the wolves in sheep`'s skins,`' etc. page 57.

[.discourse-part]
_Answer._ The blood of Christ which satisfies the Father which the saints drink,
and his flesh which they eat, which in so doing they have life,
is that which the world stumble at; which who drinks, lives forever.
And the apostle preached the word of faith in their hearts, and in their mouths,
and the word reconciles to the Father, and hammers down, and cuts down,
and burns up that which separates from the Father; and over it gives victory.
And as for the word material, the apostle doth not call it so, but precious,
and Jerusalem is come down from heaven and witnessed among the saints,
heavenly Jerusalem, and the babes know their mother.
And who are in Christ, and Christ in them, see it and possess it.
But all such as are against the light within,
which doth enlighten every man that cometh into the world, are the antichrists,
the false prophets, the wolves which have gotten the sheep`'s clothing,
(which may deceive the world, but not the elect,) as thy book hath declared thee.
And such Christ said should come, and John saw were come:
and since the days of the apostles the world hath gone after them.
And they inwardly ravened from the light:
and so have got the kingdoms of the earth into a profession and form,
who are now standing against the light within, and gathering against the Lamb,
and the saints that are in the light, and the light which they ravened from,
making war against them; but the Lamb and the saints shall get the victory.

[.discourse-part]
_Principle._ He saith, '`And the righteousness of God wrought by Christ for us,
need not be wrought over again in us,`' page 58. And '`that
Christ our justification should be in us,
that died, and suffered, that ascended,`' this he calls '`a fancy,
to fancy him in a particular person,`' page 59.

[.discourse-part]
_Answer._ Whosoever hath not Christ within, is a reprobate, and whosoever hath Christ within,
hath, the righteousness.
Now Christ that suffered, Christ that was offered up, is manifest within,
and the saints are of his flesh, and of his bone, and eat his flesh, and drink his blood,
and not another.
The Christ that ended the priesthood, ended the offering, ended the temple,
ended the law, and the first covenant, the seed of God, Christ Jesus,
this is manifest within; he that hath him, hath life, justification, sanctification,
and redemption.
And so Christ, the same today, yesterday, and forever, who is the hope,
and the author of their faith.
And so all are in the fancy that are out of the state
of witnessing Christ (that suffered) within them,
and risen again: and who are in this, are out of the fancy and shadows;
and come to see where there is no changing, but possess righteousness, glory, substance,
the end of their faith, and Christ their hope, that remains and abides.

[.discourse-part]
_Principle._ He saith,
'`There is something of God in man that will render the light which the Quakers speak of,
natural,`' page 67.

[.discourse-part]
_Answer._ That which is of God in man captivated, viz, life and immortality,
who is not come to the light,
will not render the light (when he cometh to it through the gospel) natural,
which the darkness now cannot comprehend, though it shines in it,
and that of God in man will not call Christ (the light) natural,
which the Quakers speak of.

[.discourse-part]
_Principle._ He saith, '`Ye may remember,
in the last times false Christs and false prophets shall arise,
and shall bring in damnable heresies, etc. and will show signs and wonders,
and if it were possible, they would deceive the very elect.
And such as follow strong delusions, and believe lies, and be damned,
who obey not the truth, nor receive it in the love of it,`' page 68.

[.discourse-part]
_Answer._ Christ said false prophets and antichrists should come with signs and wonders,
which the apostles saw were come, which inwardly ravened and went forth from them;
which since the days of the apostles have got the sheep`'s clothing,
and the world are gone after them,
whom they have deceived by their lying signs and wonders,
and have brought them to be all on heaps about religion.
And for the damnable heresy, and the lying signs and wonders, and strange delusions;
ye may look into the whole Christendom, among yourselves, and your own stock of Papists:
for none obey the truth,
but who own the '`light that doth enlighten every man that
cometh into the world,`' which cometh from Christ the truth;
and all false prophets are from that, and all antichrists are from that,
who have reigned since the days of the apostles, in the apostacy; and inwardly ravening,
they have gotten the sheep`'s clothing; have made war against the saints,
and overcome them; but now to that which they ravened from, are the saints come.
And the woman hath been in the wilderness,
and the man-child is brought forth to rule the nations with a rod of iron.
And all such now that are inwardly ravened from the light,
are standing up against the Lamb and the saints.
But the Lamb and the saints have the victory,
and the rejoicing over the beast and false prophet is come,
the Lamb who kills and slays with the sword, which is the words of his mouth.
And the saints which are with him, their weapons are spiritual.
And none lift up the son of God, as the serpent was lifted up in the wilderness,
but as every one is in the light that the son of God hath enlightened him withal,
and then they know him that draws all men after him.
