[#ch-38.style-blurb, short="An Antidote"]
== Thomas Moor, in his book called, [.book-title]#An Antidote,# etc. are these principles following.

[.discourse-part]
P+++.+++ He saith,
'`God doth not give the revelation of these things
now immediately as he did by the first apostles,
nor in such manner as he did to the prophets of old.`' See his epistle.

[.discourse-part]
A+++.+++ All that have the scriptures, and are ministers,
and not by the same power and spirit that the apostles were in, know not the scriptures;
and all who are in it, are in the immediate, and in that which reveals,
and in that which fathoms all the ministers of the letter, who say,
'`God doth not give forth now immediately as he did to the
prophets and apostles.`' Since the days of the apostles,
in the apostacy, such as have ravened inwardly from the spirit of God,
the time of antichrist, beast, and false prophet`'s reign, and the mother of harlots,
who have had the sheep`'s clothing, such immediate revelation hath been hid from them;
and such should continue until the words of God were fulfilled,
and the fulfilling of the prophets.
But now is the fulfilling of the words of God, and that come into,
which the prophets and apostles were in, with which that is seen and known,
and him '`that hath been slain from the foundation of the world.`'

[.discourse-part]
P+++.+++ He saith, '`To look to the light within,
is in opposition to looking at Jesus.`' That '`the light in every man is natural.
And if ye turn your eye inward,
ye shall presently see their mover and teacher:`' and this
he calls foolish and antichristian.`' And saith,
'`that no man hath in him, as of him, that light, spirit,
and wisdom in the inward parts.`' See his epistle.

[.discourse-part]
A+++.+++ All upon the earth that ever come to the knowledge of the glory of God,
come to the light in them,
'`which doth enlighten every man that cometh into the world,`'
which light was before any natural lights were made or created;
which light gives '`the light of the knowledge of the glory of God in
the face of Christ Jesus;`' and this is of him and from him.
And all that are from this are in the foolishness,
and are in the drunken spirit making drunk.
And all that ever come into covenant with God,
to have God`'s law written in their hearts,
must come into the light which Christ Jesus hath enlightened them withal,
which brings them into him who is the life, and into knowledge of Christ;
and there they shall find their teacher within them.

[.discourse-part]
P+++.+++ And he saith, '`To the law and to the testimony.`'

[.discourse-part]
A+++.+++ Many may have the Old and New Testament, yet stand against the law and the testimony,
and put the Old and New Testament for it: for '`the law is light,`' saith Solomon.
And '`the testimony of Jesus is the spirit of prophecy.`' And many may have the scriptures,
and stand against the light, and say prophecy is ceased, as the world doth now,
who are inwardly ravened from the spirit of God; and despise prophecy,
and so quench the spirit.
And the light within doth not deny Jesus: none know him nor own him,
but with the light that comes from him.
And the Pharisees and the Jews were opposite to Christ that
doth enlighten every man that cometh into the world;
and were from that of God in their own particulars, their eyes closed, and their,
ears stopped, as you are now.

[.discourse-part]
P+++.+++ He saith, '`Take away the word of the Lord as declared by the pen,
and then what wisdom is in them.`' Epist.
He saith,
'`If a believer should turn his eye into himself to look for counsel and direction,
he may be led to walk in the flesh as other Gentiles in the vanities of their minds,
and follow their abominations.`'

[.discourse-part]
A+++.+++ None upon the earth hear the counsel of God, or Christ`'s teaching,
but they who are come to the spirit of God within, and to the light within:
and all people upon the earth, that are led from the vanities of their minds,
and from walking in the flesh, are come to the spirit within, and led with it;
which all the Jews and Gentiles were astray from,
while they '`walked after the vanities of their minds,`' and then crucified the just.
And none hear the counsel of God, nor come into the faith of Jesus,
nor '`the grace of God that brings their salvation,`' but they come to feel it within,
the grace in their hearts, and the word in their hearts, and the faith in their hearts;
there is that which purifies.
And all that be from the light and spirit of God
within them are in the vanity of of their own minds,
in the flesh, out of the counsel of God, and the wisdom of God,
which the saints had and were in before the scripture was penned or printed.
And the wisdom of God is Christ Jesus.
They that had the scriptures stood against '`the light that doth enlighten
every man that cometh into the world,`' as all you do now,
and never come into it; but as ye come into it, that doth enlighten every man,
etc. ye come into the wisdom of God; and none come out of sin and evil,
but who come into that: and that is not opposite to the scriptures without,
but owns them given forth from the life in the wisdom of God.

[.discourse-part]
P+++.+++ He calls perfection '`a devilish doctrine.`' '`That the scripture is the absolute
rule and medium of our faith,`' page 2. And '`Timothy did not receive his furniture
and service of the gospel immediately from the person of Christ.`' And he saith,
'`If I had seen Christ as Paul did, I might have received the word in the same manner,
immediately from the person of Christ.`'

[.discourse-part]
A+++.+++ Timothy had faith and the gift of God, and Christ is the author of faith,
and so that is received immediately,
whereby he was '`made wise unto salvation through faith,`' with which he knew scripture,
and so by that he was furnished.
And we do believe thee, and you all, that ye have not seen Christ,
as Paul and the apostles did: so ye are out of the faith, and show he is not in you,
neither do ye sit with him in heavenly places.
Whoever receives faith from Christ, or knows Christ the power, knows immediately;
wherefore thou hast shown thyself a reprobate from God,
and under the judgment of it thou art come.
And the apostle preached perfection; and Christ bid them '`be perfect,
as their heavenly Father is perfect;`' and the saints were to grow to perfection:
and the work of the ministry was for the '`perfecting of the saints,
till they all came unto a perfect man,
to the measure of the stature of the fulness of Christ.`'
And thou in this hast denied the work of the ministry,
that callest the doctrine of perfection '`a devilish
doctrine.`' And the scripture is not the author,
nor the means of it, nor the rule, but Christ who gives it, and he increaseth it;
and faith was before scripture was given forth.
And all they that gave forth scripture had faith from God,
and '`they are able to make wise unto salvation through the faith
which is in Christ Jesus.`' But those that have the scripture,
and deny the light that doth enlighten every man, etc. and hate it, have not faith,
as the Pharisees had not;
and so are such as the apostle spoke of who were
'`reprobate concerning the faith,`' before his decease,
that had got '`the form of godliness,`' as those that say,
'`the scripture is the medium of faith, and absolute rule;`' but that which rules it,
and increaseth it, is Christ.

[.discourse-part]
P+++.+++ He saith, '`Christ`'s grace brings salvation,
but not by any such light or power dwelling in them,`' page 6.

[.discourse-part]
A+++.+++ The grace of God which brings salvation, that teacheth the saints, is in the heart,
and stablisheth it.
That which brings salvation and is their teacher, dwells within them;
which brings them to say,
'`this is the Lord whom I have waited for,`' where the everlasting life runs, and flows.

[.discourse-part]
P+++.+++ He saith, '`Such as cause divisions are to be marked,
that serve not the Lord Jesus Christ, but their own bellies, their lust, will,
or light within them,`' page 12.

[.discourse-part]
A+++.+++ The light which doth enlighten every man, etc.
Christ Jesus the second Adam, leadeth men from their lusts and wills,
and from serving their own bellies, to serve the Lord Jesus Christ from whence it comes,
for such as serve their own bellies are out of the light, in transgression,
in the first Adam, in their own lusts and wills, where thou art,
among the apostates in the deceivableness, the mystery of iniquity,
which the apostle saw was coming in, which since the days of the apostles hath reigned;
but now with the light is discovered and made manifest.
And such as have served their bellies, and serve their bellies,
which the apostles saw coming in before their decease,
are now manifest to be such as deny the light '`that doth enlighten every
man that cometh into the world,`' which is '`the salvation to the ends
of the earth.`' Are they not for '`their own bellies,`' casting into prisons,
and haling before courts such as will not put into their mouths,
that they do no work for?
And these cause divisions among all people.
Do not these serve their bellies?
And are not people come to mark them, what a division they have set among people?
Yea, persecuting and prisoning for tithes and maintenance,
and haling before judges and justices, by writs into courts, and at assizes and sessions?
Do not these that make all this division, serve their bellies, and not Christ?
They deny the light which doth enlighten every man, etc. and so '`deny Christ,
the Lord that bought them.`' But the light that every
man hath that cometh into the world,
the light that shines in the heart,
'`gives the light of the knowledge of the glory of God in the face
of Christ Jesus,`' and brings all off from serving their bellies,
and leads out of the lusts in the fall, which came by Adam in the transgression.

[.discourse-part]
P+++.+++ He saith, '`To speak of the word of God immediately,
and that which I speak I speak it immediately.
I am strengthened against that,
and admonished by God to hold fast the form of sound words.
And that which is able to make men wise unto salvation through faith.
And Timothy was to stir up the gift of God that was in him mediately,
by the putting on of the hands, and not neglect the gift that was in him.
And God hath published his last dispensation,
and nothing more to be added or altered,`' page 15.

[.discourse-part]
A+++.+++ If thou art strengthened by God against speaking his word immediately;
or if thou speaks not immediately, thou being strengthened by God against this,
(as thou sayst,) in this thou shows thou never knew him.
Whoever is strengthened of God, it is by his power, and that is immediate;
whoever speaks his word that lives and endures forever, it is immediate.
In this thou, and you all, have showed yourselves to be ministers of the letter,
and not of the word of God, which is immediate, which lives, and abides,
and endures forever,
'`and is immortal and fades not away;`' and this thou and you speak not immediately,
and therefore have ye indeed put the letter for it,
that are strayed from the word of God in your hearts,
not born again of the immortal seed, the word of God.
And whosoever stirs up the gift of God in him, it is immediate, and by the immediate.
And who ever holds fast the form of sound words, the scriptures,
is made wise unto salvation by them through the faith,
he is in the immediate gift of God.
And the gift which brought Timothy, by laying on of the hands of the presbytery,
to see and divide the word aright, and kept him out of partiality, was immediate,
and it was the immediate word of God that he was to preach in season and out of season.
And, since the days of the apostles, from this have you all been apostatized,
and asleep in the night of apostacy in the great.
city; though there have been pipers among you, and sounding of the trumpets,
and the voice of the bride, and the grinding of mills, and the light of candles.
And the time is coming that Babylon shall fall, and become the habitation of devils,
and the saints shall rejoice and sing over her, etc.

[.discourse-part]
P+++.+++ He saith, '`It is not properly and absolutely, in a full sense, that God is manifest,
or glorified in the flesh of his saints,`' page 29.

[.discourse-part]
A+++.+++ The saints are the temples of God, and God dwells in them, and walks in them;
and they come to witness the flesh of Christ,
and they glorify him in their souls and bodies,
and the Lord is glorified in their bringing forth much fruit.
And they witness the seed, the one offering for sin and transgression,
to be manifest within; and such are not reprobates,
that witness the one offering Christ Jesus; but they that have him not within,
are reprobates.

[.discourse-part]
P+++.+++ He saith, '`The body is dead because of sin, yea,
it is in itself but a wretched vile body,`' page 30. And Christ is in,
or among believers the hope of glory.
And that person Christ, is personally absent from the believers.
And we do not possess the glory of this glory Christ in us,`' page 32.

[.discourse-part]
A+++.+++ I do believe you,
that are not come to the light that '`doth enlighten every man that cometh
into the world;`' ye do not possess the hope of glory in you,
ye are absent from Christ, and do not feel him.
But the saints in the light receive Christ the hope of glory,
and so he is not absent from them; for they have unity with him and the Father,
and know a change in them from glory to glory,
and witness Christ in them as believers in the light, who walk not in darkness,
but have the light of life.
And where the body of sin is destroyed and put off, they glorify God in their souls,
and bodies, and spirits which are the Lords, and those are not wretched.

[.discourse-part]
P+++.+++ He saith, '`Christ is absent from us while we are in the mortal body.`'

[.discourse-part]
A+++.+++ Contrary to the apostle who said,
'`the life of Christ is manifest in their mortal flesh.`'

[.discourse-part]
P+++.+++ He saith, '`Christ is in heaven with a spiritual body.`'

[.discourse-part]
A+++.+++ And priest Higginson said, he is in heaven with a carnal body.
And thus ye are confused, and discerned, who are from the light,
and can speak of the body of Christ by the letter, and tell where he rose by the letter,
as the priests of old could tell Herod where he should be born;
but Christ`'s body is glorified.

[.discourse-part]
P+++.+++ He saith,
'`The first resurrection we desire not to account ourselves to have apprehended,`'
page 44. '`Such as magnify their belly to be some internal operation,
making it with all deceivableness of unrighteousness in them that perish,
glorying in their shame, minding sensual earthly things.
All since the apostles have not the ministry of the gospel immediately,
but mediately from the person of Christ,
in their believing through their word,`' page 46. '`And the text saith not,
the word of faith in the heart.`'

[.discourse-part]
A+++.+++ The word of faith which they preached was in their mouth, and in their heart,
'`nigh them even in their hearts.`' Rom. 10.
And we do believe you have not received the word immediately from Christ,
as the apostles did, who have erred and apostatized from them.
(So none are preachers of the word in the truth,
but who are preachers of it immediately.) And such are all false apostles,
and such as serve not the Lord Jesus Christ, but their own bellies,
who mind earthly things sensually, and are in the deceivableness of unrighteousness,
deceiving the people with good words,
forcing and taking maintenance of people they do no work for,
keeping them all from the immediate teaching of God, they themselves being out of it,
and conclude all in their own dominion,
and all agree in one against the immediate teaching.
And they that are out of the immediate teaching, are under the power of the beast,
and antichrist, and the great whore, the mother of harlots.
And so they served their bellies,
when they went from the immediate teaching into the strong delusion,
as since the days of the apostles it hath appeared.
How are people all on heaps, out of the life, and spirit, and power of God?
And so all that perish in the deceivableness of unrighteousness,
are from the light which '`Christ doth enlighten every man that cometh
into the world withal;`' for none perish who are in the light.
And the saints witnessed they were '`risen with Christ;`'
and they that were risen `'sought the things that were above,
and not the things upon the earth.`' And they that know the first resurrection,
and are in it, are blessed,
'`the second death hath no power over them,`' and they are atop of Adam,
and they are in Christ the resurrection and the life.
And such as are in the first Adam, driven from God, and love to live in the fall,
look not after the first resurrection, neither desired to come into it.

[.discourse-part]
P+++.+++ He saith,
'`The glorious bringing down of the kingdom and glory is yet to be waited for,
even by the disciples,
all the time of this mortality,`' page 54. '`All believers
are personally from Christ in their mortal bodies:
and none of the fathers saw the day of Christ as actually revealed,
accomplished in their time.`'

[.discourse-part]
A+++.+++ He that believes is born of God, and overcomes the world,
and abides in the doctrine of Christ, and hath the son and the Father,
and the spirit of Christ, the life of Christ in the mortal flesh.
And the kingdom of heaven Christ said was in the Pharisees,
and the saints come to and possess the kingdom.
And the kingdom of heaven is within them, and consists in righteousness, in peace,
in joy in the holy ghost, and in power.
And they were changed from glory to glory;
and they rejoiced with joy unspeakable and full of glory; and that was in the kingdom,
and this was while they were upon the earth.
And Enoch and Abraham saw the day of Christ, and David saw the betrayer,
and whose feet should be snared, whose eyes should be blinded,
and whose back should bow down; and he saw Judas that betrayed Christ.
And Isaiah saw the suffering of Christ, and how God laid the iniquity upon him.
And Isaiah saw his name, and how his soul was made an offering for sin.
And Daniel said, the Messiah should be cut off, but not for himself,
which the apostles witnessed fulfilled.

[.discourse-part]
P+++.+++ He saith, '`The scriptures is the power of God unto salvation,`' page 59.

[.discourse-part]
A+++.+++ Many may have the form, but deny the power of God, which is the gospel.
And the letter doth not give life, neither is it the power of God unto salvation.

[.discourse-part]
P+++.+++ He saith, '`That Christ is distinct from every one of us,
and without us in our particular persons,`' page 61.

[.discourse-part]
A+++.+++ The apostle said, '`Christ was in them except they were reprobates;
and they were of his flesh, and of his bone; and they eat his flesh, and drank his blood;
then it was within them; and he is distinct from none but reprobates, who hate the light.

[.discourse-part]
P+++.+++ '`Nor are we to wait for a further revelation to us to be given forth,
than the scriptures.
For the word of God came not first to the Gentiles immediately,
but to the apostles,`' page 77.

[.discourse-part]
A+++.+++ The apostles that preached the word of God,
it was immediate to whomsoever they preached it, for they had received it immediately.
For the word itself is immediate, for '`it is the savour of death to the death,
and of life to the life.`' And none know the scriptures
but by the spirit that doth reveal them.
So all that witness the spirit of God witness the revelation,
and the revealing of the scriptures to them by it.
And the things of God, which are laid up for them that love God, the eye hath not seen;
but the eye may see the scriptures outwardly.
And '`none know the son of God, neither knows any man the Father but the son,
and he to whom the son reveals him.`' And so people may have the scriptures,
but not the revelation of the son of God by them.
For the Pharisees had the scriptures, but not the thing they testified of.

[.discourse-part]
P+++.+++ He saith, '`The scriptures are the word of God, and the key of knowledge,`' page 79,
'`and the opening of all things contained in the scriptures.`'

[.discourse-part]
A+++.+++ The scriptures are the words of God, and that is his word who fulfils them,
Christ Jesus,
whose name is called '`the word of God.`' And that which
opens the scriptures is the spirit that gave them forth,
that is the key of David, who in the light saw more light.
For the Pharisees who crucified Christ, had that which testified of Christ,
the scriptures.
And you that are in the apostacy since the days of the apostles, want the key,
and have taken away the key of knowledge.
And all that dwell upon the earth, that stop their ears,
and close their eyes against that of God in them,
that deny the light that doth enlighten every man that cometh into the world,
want the key of knowledge.

[.discourse-part]
P+++.+++ He saith, '`He gives gifts unto men for the work of the ministry, some prophets,
some evangelists, some pastors and teachers, for the perfecting of the saints,
for the edifying of the body of Christ, until all come into the unity of the faith,
and the knowledge of the son of God unto a perfect man,`' page 81.

[.discourse-part]
A+++.+++ And yet he said before, perfection was a devilish doctrine, and a fancy:
so out of this work and ministry thou hast thrown thyself.
For this work and ministry have been lost since the days of the apostles,
in the apostacy; but now is appearing in the end of Babylon,
the knowledge of the son of God people are coming to, and to the unity of the faith,
from among the apostates who have had the sheep`'s clothing, but all on heaps about it,
being ravened from the spirit of God inwardly.
Among whom the proclamation hath been in the steeple-houses, and pulpits, in markets,
towns, disputes: '`No perfection, no overcoming of sin;
perfection is a doctrine of devils, a devilish doctrine, and a fancy,`' etc.
And this hath been proclaimed among the apostates
in the apostacy since the days of the apostles,
by the beast`'s authority, under Satan`'s power, the deceiver of the nations,
where the mother of harlots is.
But God will reward her double, and shall take the devil,
and with him the beast and false prophet, and cast them alive into the fire.
Rejoice, ye holy prophets and saints, over her, who are come into the unity of the faith,
and to a perfect man, and to the knowledge of the son of God.
And the everlasting gospel shall be preached to them that dwell upon the earth,
and God shall be feared, and glory given to him.
And none come to the knowledge of the son of God, the salvation to the ends of the earth,
the covenant of Jews and Gentiles,
until they come into the light which Christ doth
enlighten every one withal that cometh into the world,
that gives him the knowledge of the son of God, of the author of his faith,
and the taste of his fulness, and to become a perfect man.

[.discourse-part]
P+++.+++ He saith,
'`The scriptures are the means whereby the righteousness
is revealed from faith to faith,`' page 82.

[.discourse-part]
A+++.+++ The Pharisees had the scriptures read every sabbath, and had the form of godliness,
but denied the power,
and were reprobate concerning the faith and the righteousness of Christ Jesus.
And God it is that reveals the faith, and gives the faith, and the righteousness;
and many have the words, and yet not it; they who have it have the word in their hearts,
and the spirit that gave forth the scriptures, and see God the original of all good.
The scriptures cannot reveal it, but they testify of it;
and all must come into the spirit, before they know revelation,
or know the scriptures either.

[.discourse-part]
P+++.+++ He saith,
'`New Jerusalem is not come down from heaven,`' and '`he will make all things new,
not hath made,`' page 83. He saith, '`The body is dead because of sin,
yet there is a remainder of the old man in the members,`' page 84.

[.discourse-part]
A+++.+++ Where the body is dead because of sin,
and that put off by the circumcision of the spirit,
if the root be holy the branches are holy also;
and such come to glorify the Lord in their bodies and souls which are the Lord`'s,
who hath redeemed them out of sin.
So '`they that are Christ`'s have crucified the flesh with
the affections and lusts,`' and all things are become new.
And the New Jerusalem is witnessed come down from heaven among the saints;
for who witness Christ and know Christ, know the tabernacle of God,
and know the New Jerusalem, and know the place where there is no curse.
And many know their mother now, and that which had led captive is gone,
and going into captivity.

[.discourse-part]
P+++.+++ He saith,
'`The apostles gave the last and full revelation of the gospel to all nations.
And Timothy learned doctrine mediately; and since,
none may expect to receive so immediately as Paul did, but all mediately,`' pages 88, 89.
Again, '`God now gives, and teacheth mediately,
and spiritually by the testimony of him mediately,`' page 90. '`It
is a little necessary to show the vanity of their pretence of immediate
revelation from God`'s spirit,`' page 91.

[.discourse-part]
A+++.+++ All those are in a pretence, and in vanity,
that are from the immediate revelation of the spirit of God.
And though people have all Paul`'s declarations,
if they have it not immediately revealed to them by the spirit of God, as Paul had,
they have not the comfort of Paul`'s words,
neither have they the comfort of the revelations.
And John saith,
the everlasting gospel must be preached to them that dwell upon the earth,
since the apostacy from the apostles, (mark that.) And that which Timothy preached,
who was in the faith, the gift of God, and spoke his word, and divided it aright,
it was immediate.
But since the days of the apostles hath the immediate been lost,
and I know ye cannot expect it in the state ye all stand in,
inwardly ravened from the spirit of God and truth.
But now are the saints come to that which ye have ravened from, and the apostles were in,
who witnessed the immediate teachings of God; and God`'s teaching is immediate,
and the testimony of Jesus is immediate, which is the spirit of prophecy.
But many have that which testifies of him,
and are from the immediate spirit that was in them that gave forth the scriptures.
And all upon the earth that are from the immediate spirit of God,
that was in them that gave forth scriptures, their ministry is but mediate,
and they are but in the mediate; they are all ministers only of the letter, made by man,
and what they have it is but from man, and not from God immediately.
Such have nothing but the sheep`'s clothing,
being inwardly ravened from the spirit of God in them.
And here is Babylon the mother of harlots, and the beast, and his names:
but over all have they victory that are in the immediate,
in that which the apostles were in, and answer that in them all which they ravened from.

[.discourse-part]
P+++.+++ He saith, '`Even now, in the days of their adversity, while the person of the Lord,
the fountain of their teaching, for whom they wait,
is personally absent from them,`' page 92.

[.discourse-part]
A+++.+++ All they that hate the light, see not Christ the fountain of teaching,
and these are they that have inwardly ravened.
Such have their teachers in corners, and are in the days of adversity,
and eat not the flesh of Christ, nor drink his blood, and are not of his flesh and bone,
and receive not his spirit.
But all who wait in the light with which Jesus Christ
hath enlightened every man that cometh into the world,
their eyes shall see their teacher that cannot be removed into a corner,
Salvation they shall see, and days of adversity shall end,
and his guiding they shall know, and come to be in unity with Christ, and eat his flesh;
and drink his blood, and be of his flesh and bone.
And thousands do witness this, and the prophet raised up, the end of the prophets;
and they that hear him not are to be cut off.
And none lift up the son of God but who are in the light '`which lighteth every man
that cometh into the world,`' and that brings him to understand the scriptures,
and the substance of them.

[.discourse-part]
P+++.+++ He saith, '`The grace of God that brings salvation,
it is a fancy to say it is stirred up in them;
but it is a thing wrought in another for them.
And to say the word of the Lord is within, and the spirit within,
is men`'s following their own brain, and visions of their own hearts.`' And he saith,
'`Whereas they imagine of a light within them, all that know God,
show the light in them to be darkness itself.`' See postscript.

[.discourse-part]
A+++.+++ All that know God, own the light within them,
'`to give the light of the knowledge of the glory of God in the
face of Christ Jesus,`' which light shines in their hearts;
and all that know God,
own the light that doth enlighten every man that cometh into the world, Christ Jesus,
and believe in the light, and have the witness in themselves.
And all that are from the light within them, are in the darkness, and stumble,
which have been in this night of the apostacy from the apostles`' doctrine.
And all, Gog and Magog, and the beast, and false prophets, and the kings of the earth,
are making war against the light '`that doth enlighten every man;
etc. but the Light shall get the victory.
And all that are from the word of God within, in their hearts and in their mouths,
though they speak of the scriptures without, yet they use their tongues,
and follow their own dreams, and visions of their own hearts and brains,
and are from the word of God, that lives, and abides, and endures forever.
And all that ever witness '`the grace of God that
brings salvation,`' feel it in their hearts,
stablishing them, and seasoning their words,
and know the throne of grace from which it cometh.
And this doth not deny what Christ hath done,
but owns him all along from the foundation of the world; and what he wrought,
and what he did, and what he said for us.
And all upon the earth that have the scriptures,
and are out of the spirit that gave them forth, are all in a confusion here,
and on heaps about words.
And the word of God within, and spirit within,
leads people from following their own dreams, and following fancies of their own brains,
which all have done many hundreds of years past,
in the apostacy since the days of the apostles.

And as for all thy lies and confusion in thy books, they will be thy own burden,
and the witness in thy conscience will answer in the day of thy judgment;
thou shalt feel a smart work thou hast to go through,
who art now in the pack and body of confusion, buried under the body of iniquity.
But thy folly is discovered sufficiently to the nation, and thy spirit is now tried,
who art one of the heads risen up against the Lamb in his day, and against his light;
but it is thy condemnation.
