[#ch-39.style-blurb, short="The Deceiving Quaker Discovered"]
== Matthew Caffin, in his book called, [.book-title]#The Deceiving Quaker Discovered.# His principles follow.

[.discourse-part]
P+++.+++ He saith, '`Nothing will cure the soul but the knowledge of salvation,
which is made known by outward means,
because the will of the Lord in order to the soul`'s peace
and rest was discovered by outward means,`' page 4.

[.discourse-part]
A+++.+++ The Pharisees had outward means, reading, praying, and expounding,
and yet knew not the soul`'s comfort and peace: for Christ bid them come unto him,
that their souls might have rest, all that were weary and heavy laden.
So if people have all the scriptures upon the earth, hearing and praying,
and all the outward means, and are not in the power, which is the gospel,
which is immediate, not outward;
and if they be not in the life that gave forth the scriptures,
they have not their soul`'s comfort and rest; for the soul is in the hand of God,
and Christ is the bishop of it; and the minister of the spirit watcheth for it.
And they that hearkened to what the spirit said, their souls lived,
and this was not outward.
But when men stop their ears, and close their eyes to that of God in them,
as the Jews did, and all the inwardly raveners, false prophets,
and antichrists in the apostacy, since the days of the apostles,
such hearken not diligently, and their souls live not.
And all such as deny the light which doth enlighten every man that cometh into the world,
see not Christ the bishop of their souls, nor their salvation.

[.discourse-part]
P+++.+++ And he saith, '`The Quakers cry,
wait upon the light within you,`' and '`this is another
report than that of the scriptures.`' And he saith,
'`I do not find where it is spoken that God spoke in this people,`'
page 5. '`And the apostle who was to go to preach to all nations,
did not turn the people to a teacher within them, to teach them all things.
And the apostle affirms that they were to give them
the light of the knowledge of the glory of God,
etc. and not their teacher within them,`' page 8.

[.discourse-part]
A+++.+++ It was the Lord that spoke in his prophets, by their mouths, and in his son,
and they were the mouth of the Lord: and where God dwells in his people, he speaks.
And the apostles were to go into all nations to preach the gospel,
and preached the covenant of God; they who came into the thing they preached,
the law written in their hearts, needed not any man to teach them,
nor needed to teach one another, saying,
'`Know the Lord,`' as it had been in the first covenant,
people had been taught to know the Lord,
and the priests`' lips were to preserve the people`'s knowledge.
But they who are come into the covenant of God, Christ Jesus, the second covenant,
are come into the treasury of wisdom and knowledge.
And the apostles told the saints, that '`the light which shined in their hearts,
would give them the light of the knowledge of the glory of God in the
face of Christ Jesus;`' and this is not another report than the scriptures,
but this is the scripture report.
And John told the saints,
'`that the anointing which abide in in them would teach them all
things,`' and '`the word was in their hearts and in their mouths,
to obey it, and do it,`' and this was the ministers`' work;
and to direct the hearing of faith, which Christ is the author of,
whereby they receive the spirit.
And the apostle brought the people to their teacher within them, which is the light,
and turned people '`from the darkness to the light,
and from the power of Satan unto God;`' which light shining in their hearts,
gives them '`the light of the knowledge of the glory of God,`' etc.
See 2 Cor.
iv. Chap.

Now light shines in the darkness, and they being turned from the darkness to the light,
it gives knowledge.
So such come from under the power of Satan unto God; for while they are in the darkness,
they are under the power of Satan.
And nothing gives nor makes manifest the knowledge of the saviour,
but the light which doth enlighten every man that cometh into the world,
which shines in the darkness; and they being turned from the darkness,
and from the power of Satan, such the God of the world cannot blind.
But they in whom this light shines, who are in the darkness, the god of the world blinds,
and the light of the glorious gospel they do not know.

[.discourse-part]
P+++.+++ '`Saith antichrist, if you will believe in the light within you,
it will lead you to Christ.
To wait upon the teacher within,
there will be such an internal light that will make
known all things,`' page 9. '`And the,
quakers exhort all ignorant people in the world to depend upon a light within them.
Wherefore be counselled not to be carried away with strange doctrines,`' page 11.

[.discourse-part]
A+++.+++ The '`light which doth enlighten every man that
cometh into the world,`' is not a strange doctrine;
the light to the Gentiles, the teacher of the Gentiles,
the '`salvation to the ends of the earth,`' the new
covenant to the house of Israel and Judah.
And this doctrine was strange to the Jews and to the Gentiles,
though to them it had been promised.
So this light shines in the darkness, and the darkness not comprehending it,
such are ungodly wicked men, and they must be turned from the darkness to the light,
before they come to retain God in their knowledge,
or come to that which must give them '`the light of the knowledge of the glory of God
in the face of Christ Jesus.`' And all that come to witness their teacher within,
Christ, are possessors of the prophet raised up, Christ Jesus,
the teacher of his people according to the promise.
And they are antichrist and the false apostles, who keep people from the light,
for that was the true Christ, and the true apostles bid people believe in the light,
and walk in the light, and brought them to the light within;
and the true prophet and prophets said,
that God would give him a covenant to the Gentiles;
and this is '`the true light that doth enlighten every man that cometh
into the world,`' and all that deny this are antichrists and deceivers.

[.discourse-part]
P+++.+++ He saith, '`How beautiful are they that preach the gospel,
etc. not by the light within.
And the word of faith cannot be said to be in men`'s hearts and mouths.`'
See page 14. And the sure word of prophecy spoken of in Peter,
are the scriptures, which people must take heed unto,
as unto a light shining in a dark place.
And '`the saints received the words of the apostles not as the words of men,
etc. whereas the Quakers suppose that God himself is their teacher, and so err,
not knowing the scriptures.`' See page 17.

[.discourse-part]
A+++.+++ They that preach the gospel, which is the power of God,
which gives relief to that which was captivated in every creature,
they are in the light in their own particulars, with which they know the glorious gospel,
and answer the light in every man that shines in the darkness,
and life and immortality there comes to light, through the power, which is the gospel;
and this is that which is beautiful.
And the word of faith the apostle preached, was in the heart, and in the mouth,
and is so understood by all the regenerate.
But all they that have only the form, and are inwardly gone from the spirit, know it not,
but are of this ignorant; they cry, '`How should this be so?`' as the Jews said,
'`How is it that thou makest us to doubt?`' Yea, the word was it that made them doubt.
And the sure word of prophecy, which people do well to take heed unto,
as unto a light shining in a dark place, (mark, in the dark place,) '`until the day dawn,
and the day-star arise in their hearts;`' this was it that let them see that '`no prophecy
of scripture came by the will of man:`' and this let them see that such as went in Cain`'s,
Core`'s, and Balaam`'s way, which were preachers of the form but wanted the power,
had lost the holy ghost;
and such '`admired men`'s persons because of advantage,`' and came to be dead,
twice plucked up by the roots; which dead have long lain upon the earth,
whose carcasses stink, since the days of the apostles in the apostacy.
So many may have the scriptures, and quench the spirit of prophecy.

[.discourse-part]
P+++.+++ He saith, '`Christ is not yet so the word,
but he himself testifies the scriptures are the word of God.`' See page 21.

[.discourse-part]
A+++.+++ Christ`'s name is called '`the word of God;`' and the scriptures are the words of God,
which Christ the word of God fulfils, in whom the words all end;
and such in whom the light shines in the darkness, and the darkness comprehends it not,
are not like to see the spirit until they be turned to the light.

[.discourse-part]
P+++.+++ He saith, '`They err, not knowing the scripture,
when they affirm that the only means of faith is the immediate teaching of Christ,
dwelling in them.`' See page 23.

[.discourse-part]
A+++.+++ Could the apostle preach Christ until he was revealed in him,
who is the author of every man`'s faith?
And the doers of the law are justified, and not the hearers only.

[.discourse-part]
P+++.+++ '`The Quakers will not own the scriptures to be the touchstone to try the
spirits withal.`' See page 28. And say the scriptures are not the rule:
Oh shameful deceit!
And George Fox said,
'`that he knew Christ come in him.`' See page 29. '`And this is the deceiving of many;
and this cannot be till first the true faith of his coming be made void,
which these men endeavour to do.`' See page 29.

[.discourse-part]
A+++.+++ The holy men of God before the scriptures were had a rule, and a touchstone;
and the Pharisees had scriptures,
but were out of the life that the holy men were in that gave them forth,
and wanted the rule, and the touchstone; but the apostles that were in the life,
and the substance of what they spoke, had the rule, and touchstone.
And all in the apostacy since the days of the apostles,
that are ravened from the spirit of God, have had only the sheep`'s clothing;
but have lost the touchstone, and so have destroyed one another about scriptures,
the saints`' words,
which was not the work of the '`spirit that gave them forth.`' And '`Christ is in you,
except you be reprobates.`' So reprobates witness it not;
therefore they stand against it, and therefore are against them that witness it.
And all the false Christs, and the destroyers of the faith of people,
are such as draw people from the '`light that doth enlighten every man that cometh
into the world,`' and keep them from witnessing and receiving Christ in them,
the substance and the author of their faith; and such never know him come in the flesh,
nor the spirit.
And such as witness Christ within them, receive the author of their faith,
and destroy the faith of none.
And the spirit was the rule of the saints that led them to give forth scriptures;
and it let them see, in all ages, who got the form of godliness, who used their tongues,
who lived in the spirit, who erred from the spirit,
who run when the Lord had never sent them, to whom the Lord had never spoken:
and this was the rule, and this was the spirit of discerning,
and this was the touchstone to try with.

[.discourse-part]
P+++.+++ And they say, '`they own Christ that suffered,
meaning the spirit within.`' See page 36.

[.discourse-part]
A+++.+++ None know Christ nor his suffering, but with the spirit of God within;
for with the spirit of God in the prophets, and holy men,
they knew Christ that was to come to suffer; with the spirit of God in the apostles,
they knew that was the Christ that did suffer; with the same spirit of God within people,
they now come to see him, and enjoy him, and receive him, the same that did suffer,
which none do that are out of the spirit.
And the Pharisees that had scriptures knew him not, who were gone astray from the spirit,
nor the Gentiles, though they had scriptures.
Neither do the apostates, who are inwardly ravened from the spirit of God,
though they have all the sheep`'s clothing,
know the '`light that doth enlighten every man that
cometh into the world,`' though they be for multitude,
'`as the sands on the sea shore;`' nor do any know it, and receive it,
but who come to that which they ravened from.

[.discourse-part]
P+++.+++ He saith,
'`that Christ is a distinct being from the Father.`' See page 40. '`They
that hold that they are now in the possession of the kingdom of Christ,
and that they have eternal life now in possession,
pervert the right way of the Lord.`' See page 42.

[.discourse-part]
A+++.+++ Christ is not distinct from the Father, '`for he and the Father are one;
the Father is in him,
and he is in the Father,`' and the Father and the son dwell in
the saints who are out of the transgression of his doctrine;
and '`he that hath not the son of God,
hath not Life:`' and '`he that hath the son of God,
hath life eternal,`' really in possession,
and such '`pervert not the right way of the Lord;`' but such as have not the son of God,
they are all in the first Adam, in the crooked ways, and crooked by-paths in the world,
not witnessing life, but standing against the light which shineth in the darkness,
which their darkness cannot comprehend;
which are all the inwardly raveners since the days of the apostles,
among whom hath been the apostacy and the apostates,
from whom the light of life hath been hid.
But he that followeth the light, cometh to have the light of life:
and he that receiveth the light, receiveth life eternal, and receives the son of God:
and he that receiveth the son of God, hath eternal life in substance and possession.

[.discourse-part]
P+++.+++ He saith, '`Death which hath passed over all men,
is not a spiritual death.`' See page 51.

[.discourse-part]
A+++.+++ Thou and all you shall feel it as a spiritual death,
before ye know life and immortality come to light,
and the spiritual wickedness wrestled against, '`whose weapons are spiritual,
and not carnal, that wrestles not against flesh and blood,
but spiritual wickedness in high places.`' And that is it
which causeth the life of all creatures to groan,
and oppresseth it, whereby life and immortality is hid from the eyes,
and the power transgressed,
whereby the spirit and soul of man must be sanctified before he witness thorough purification,
before he come from under the death and spiritual wickedness.
For sin brings death,
and that is the spiritual wickedness that is to be wrestled against;
transgressing the pure law of God, the commands of God, brings death.
And as he entertains the spiritual wickedness, this brings death upon his life,
so comes oppression on his body, and on his spirit,
and his soul is burdened and wearied, and unsanctified, and polluted,
which Christ gives rest to, who is the sanctification, and redemption, and justification.
The law goes upon man, agreeable to that of God in him:
but Christ`'s body makes free from the law, and redeems from under it.
So as the power of God, the gospel is known, and Christ known,
the creature comes from under the bondage of corruption,
and life and immortality comes to the light through the gospel,
whereby the death is known, which who believes shall never die,
and the life is known which shall never die.

[.discourse-part]
P+++.+++ '`The Quakers deny water baptism, and slight it, and call it a carnal thing.`'

[.discourse-part]
A+++.+++ Outward water is not spiritual, but is a carnal thing as it is in itself;
and it is the spirit alone that baptizeth into the body,
which brings off from things that are seen, which are temporal, as the apostle said,
'`while we look not at things that are seen; for the things that are seen,
are temporal,`' etc. and water is seen.

[.discourse-part]
P+++.+++ He saith, '`False prophets and antichrists should come in sheep`'s clothing.`'

[.discourse-part]
A+++.+++ Christ said to his apostles, these should come; and before the apostles`' decease,
they saw they were come.
And the apostles saw before their decease '`the devil transform himself
into an angel of light,`' and Satan`'s messengers and ministers come up,
such as had a feigned humility, and had got up a will-worship,
and the abstaining from meats, neglecting the body; and such as Jannes and Jambres,
and that crept into houses, who had the sheep`'s clothing, the form of godliness.
And such were the seducing spirits, who ran into the strange delusions,
bringing in the damnable heresies and the doctrine of devils; who went in Cain`'s,
Core`'s, and Balaam`'s way.
And they saw the coming of the man of sin; and the apostles all saw by the spirit of God,
before their decease, those who Christ said should come, who inwardly ravened,
after whom, since the days of the apostles, the world hath gone.
All these Christ said should come, and the apostles saw were come and coming,
before the coming of the Just One.
But the Just One now is come, who hath revealed it,
'`the light which doth enlighten every man that cometh into the world.`' Cain, Core,
Balaam, false prophets, antichrists, such as go into strong delusions,
and bring in the damnable heresies, and forbidding the eating of meats, and marriage;
these all inwardly ravened, and these all have been up since the days of the apostles,
and these have been covered with the sheep`'s clothing.
And the false prophets and antichrists, inwardly ravened, and the devil, the man of sin,
went out of the truth, and abode not in it.
He and all they that have the sheep`'s clothing, can get scriptures,
but being inwardly ravened and gone from the spirit of truth in their own particulars,
such are the destroyers of the creatures, and of the creation.
But with that which they all have ravened from, are they manifest and discovered,
and to that are people now come, and coming.
These inwardly raveners have had the sheep`'s clothing, who have been the beast,
and false prophets, devil`'s messengers and ministers out of the truth,
who have reigned since the days of the apostles, and have long deceived the nations.
But now the devil, beast, antichrist,
and false prophets are all discovered with the light, and life, and the truth,
which they all went from.
And the place is seen where there is no curse; and the beast,
and the false prophet are taken, and are cast into the lake of fire,
that they shall deceive the nations no longer, under whose dominion thou art,
whose words shall be thy burden.

[.discourse-part]
P+++.+++ He saith, '`Let us mind the law and testimony.`'

[.discourse-part]
A+++.+++ Then ye must all mind the light; for '`the law is light,`' said Solomon;
then ye must all mind the spirit,
for '`the testimony of Jesus is the spirit of prophecy.`'
Many may have the Old and New Testament,
yet be from the law and testimony; for the law and testimony were before Matthew, Mark,
Luke, John, the Acts, Epistles, and Revelations were written, as in Isaiah viii.
which the prophet minded.
And they that say the Old and New Testament, are the law and testimony,
show themselves to be ignorant of the spirit, and ignorant of the law and testimony.
And the law and testimony doth not deny the scriptures, but owns them in their place,
and sees the fulfilling of them with the testimony of Jesus;
they see Jesus who was before scripture was, and comes to fulfill it.
