[#ch-40.style-blurb, short="Antichrist Made Known"]
== William Jefferies`' book, called [.book-title]#Antichrist Made Known.# In which are these principles following.

[.discourse-part]
P+++.+++ He saith, '`Men are mistaken in saying, the Romish whore of Babylon, is antichrist.
And the chief city of this great whore, the mother of harlots, is the city of Rome,
the pope, cardinals, bishops, and clergy.
The spirit of antichrist denies Christ come in the flesh,
and says the light within is Christ, when at the best it is but the light of nature.
And this is the spirit of error and darkness,
and their light is become darkness.`' See pages 63, 64. 68.

[.discourse-part]
A+++.+++ The light which '`doth enlighten every man that cometh into the world,`' is Christ,
and none can confess him in truth, nor see him, nor lift him up,
as the serpent was lifted up in the wilderness,
but who are in the light which cometh from him.
And by this thou hast overthrown thyself;
for they that confess the light in them to be Christ,
(which Christ saith he is,) these do not deny Christ come in the flesh.
And the devil may confess the son of God, and the Jews may confess he is to come,
as the apostates confess he is come.
But none of all these know him in the flesh,
confess him '`come in the flesh,`' or know his flesh, or the flesh of the son of man,
but who are in the light that comes from him that '`doth enlighten every
man,`' etc. which light was before any natural created lights were made,
'`glorified with the Father before the world began.`' And walking in the light,
it leads into the day, where there is no night,
which light is Christ the covenant of God; and such come to know the darkness past.
Now I say, neither apostates nor Jews, whose ears are stopped,
and eyes closed to that of God in them; nor that are inwardly ravened,
having sheep`'s clothing, who are Babylon, who are the harlot,
who is the mother of them all, who are ravened inwardly from the spirit of God:
none of all these can '`confess Christ come in the flesh,`' but only from the letter;
for these know not his flesh.
The devil is out of the truth, and truth is atop of him.
The Jews`' eyes must be opened, and their ears unstopped before they know his flesh.
The apostates must come all to that which they have ravened from inwardly,
before they come to know Christ`'s flesh, and are of his flesh, and eat his flesh,
and '`confess that Christ is come in the flesh,`' who is the offering,
and the sacrifice of the whole world that makes the peace between God and man,
and '`perfects forever them that are sanctified.`' The top-stone laid atop of all sin,
and transgression, death, hell, and grave, bruised the serpent`'s head.
Here is no Babylon, here is no antichrist,
and this the Quakers confess with the light within them.
And all upon the earth are antichrists, and know not Christ,
not Christ come in the flesh,
that are from the light '`that doth enlighten every
man that cometh into the world,`' and own not that,
but deny it.
And all sects, bishops, mother of harlots, antichrists, popes, cardinals, and clergy,
Babylon, Romish whore, who are gotten up since the days of the apostles,
inwardly ravened, having had the sheep`'s clothing; they are not likely,
any of these that are ravened,
to own the light that doth enlighten every man that cometh into the world.
And to Babylon, and so harlots, and so waters, and so from the rock.

[.discourse-part]
P+++.+++ And he saith, '`The whore will confess Christ come in the flesh.
Satan transforming himself into an angel of light,
he maketh the fountain of waters bitter; the sweet promises, the water of life,
which makes glad the city of God, he makes like wormwood,
and changeth the taste of them,`' page 72. 74.

[.discourse-part]
A+++.+++ Antichrist, the mother of harlots, false prophets, which went forth from the apostles,
as in John`'s epistle; these will confess Christ come in the flesh as ye do,
and all sects upon the earth;
else without the sheep`'s clothing ye could not deceive the nations.
So ye have brought the nations, tongues, people, languages, and multitudes,
to be like waters.
But these are the waters which now begin to grow bitter; for neither the devil,
nor antichrist, nor false prophets, nor mother of harlots, who are gone from the truth,
and are inwardly ravened, though they may have the sheep`'s clothing,
can touch the waters of life, nor the fountain,
to make the waters bitter that make glad the city of God.
For ye that are inwardly ravened, who have got the sheep`'s clothing,
as the devil who went out of the truth, you get scriptures,
and your confession of Christ is as his.
The inward raveners, who, since the days of the apostles, the world hath been after,
have gotten the scriptures; and being out of the truth with the devil,
are the deceivers of the nations.
And there are (out of the truth) the beast, false prophet, antichrist, mother of harlots,
deceivers, man of sin, devil`'s messengers and ministers, and the damnable heresies;
their tongues are waters, their peoples are waters, their nations waters,
and multitudes waters: all on heaps about scriptures,
destroying one another about the prophets`', apostles`', and Christ`'s words,
and ministers`' maintenance.
Now the devil, the beast, false prophets, and antichrist, are taken,
and the mother of harlots, and cast in the lake of fire, and Babylon is confounded,
and the everlasting gospel shall be preached to every nation, kindred, tongue,
and people.

And as for all the rest of the stuff in thy book, thy pack of confusion,
Babylon`'s children, it will fall heavy upon thyself, and be thy own burden,
and press thee under,
which in the day of thy judgment thou shalt remember that I am a friend to all souls.
Their is neither Jew that professeth a Christ was to come,
nor Christian that professeth a Christ is come;
nor any one upon the earth (though ye have all the scriptures) knows the flesh of Christ,
but who owns the light which doth enlighten every man that cometh into the world.
For the Jews knew not the flesh of Christ, though they had scriptures,
(but crucified him,) whose ears were stopped and eyes closed to that of God in them.
The Gentiles knew not the flesh of Christ, who were astray from the life of God;
neither do those called Christians know the flesh of Christ,
who are inwardly ravened from the spirit of God in them,
though they have gotten all the sheep`'s clothing, and talk Christ is come,
and died at Jerusalem, as the Jews could say of him to come, and to be born at Bethlehem;
yet they could not confess him come in the flesh, nor did know his flesh;
no more do these Christians know his flesh, though they have all the form of godliness.
But who come to the seed, Christ himself, they know it in them;
then they shall know the one offering (atop of all
the world`'s sects) for the sins of the whole world;
for none know the flesh of Christ, nor Christ, nor as God was in Christ,
but as they come to the light with which they are enlightened,
which who hate know him not, but it is your condemnation,
and that ye shall all feel at last.
So the one offering, which is Christ, is set over the whole world,
and his flesh the world knows not, nor the princes of the world;
but where the seed is come out of the grave, it knows him, the seed knows him;
and these are of his flesh and of his bone, it is their meat and drink.
And Christ is now come, who treads the winepress alone without the city.
Though all the beasts, and false prophets,
and antichrists upon the earth rise against him,
yet the Lamb and the saints shall have the victory,
and the nations shall be ruled with a rod of iron; and he that was dead, is alive again;
he by whom the world was made is manifest, and he rules in his saints,
and the tabernacle of God is with men.

[.discourse-part]
P+++.+++ And whereas thou sayst '`that antichrist will be a single person.`'

[.discourse-part]
A+++.+++ Which is contrary to the apostle, 1 John 1:18. (who saith,
'`Even now there are many antichrists,
whereby we know it is the last time;`' and '`they went out from us,
but they were not of us;`' the antichrists are they who are against Christ.
