[.style-blurb, short="Ministers in the County of Worcester"]
== The agreement of Divers Ministers of Christ, so called, in the County of Worcester and parts adjacent, which are fifty-eight in number. Some of their principles follow.

[.discourse-part]
_Principle._ They say, '`they have sought God`'s direction out of the scriptures,
which they call his holy word, and what is the greatness of their work, and edification,
and salvation of souls,`' etc.
And do humbly bewail our too great neglect,
who have not frequently and earnestly laboured in so great a work:
and especially that we have done no more in catechising,
and personally instructing,`' etc. page 3.

[.discourse-part]
_Answer._ It was the ministers`' work, before the apostacy, to go from house to house,
and warn all both small and great, yea, with tears;
this was the work of the ministry in the spirit.
And they were in the spirit that gave forth scriptures;
and so brought people into the life that gave them forth,
with which they were able to instruct one another, and to set up the pure in one another.
And the work of the apostles, the ministers of the gospel, and Christ,
was to bring people into the life that gave forth scriptures, and into the substance,
Christ Jesus, that the scriptures testified of.
But you who are fain to seek in the letter for it, in the scripture for it,
and have it not from within,
as they had that gave forth the scripture and received it of God,
are never like to beget to God.
And when truth comes, as it did among the Pharisees, which came to end their forms,
and their shadows, the builders stood up, and rejected it in their forms.
And now, since the days of the apostles, such as have had the scriptures,
but inwardly ravened from flu spirit of God, are standing against the light,
Christ Jesus, that doth enlighten every man that cometh into the world.
And so ye get people into a form, and cover them with sheep`'s clothing;
but now Christ is come, reigns and rules, and his saints with him,
all rise up in arm`'s against him, kings of the earth, beast, and false prophets,
the dragon and his angels.
But the Lamb and the saints shall have the victory; glory to the Highest.
And so that is but the blind zeal that is stirred up in the apostates,
against Christ in this age, as it was in the Jews against Christ in their age.
But Jews must come to that which they closed their eyes and stopped their ears against,
and the apostates must come to that which they have ravened from,
before they be stirred up in the pure zeal.

[.discourse-part]
_Principle._ And you say, '`Aged men are commonly more ignorant than the younger sort,
and our unskillfulness and others`' unfitness for the work,`' etc. page 7.

[.discourse-part]
_Answer._ Your unskillfulness, and the ignorance of your old men,
is because ye have been ignorant of the work of God;
therefore is there so much ignorance among you and the old men;
and this you may publish to the nation to your shame.
And who will be catechised by unskilful men, and ignorant men?
But this is it, that your folly might appear, and that ye might publish it forth,
and set it upon the house tops,
that all that run might read you fifty-eight pastors and teachers,
and your young men as your old men.

[.discourse-part]
_Principle._ You say, '`We receive the public maintenance to this end,
that we may be enabled to lay out our endeavours for the
good of the whole parish from whence we receive it.
And we are further obliged in justice to do our best for their salvation.`'

[.discourse-part]
_Answer._ How can men that are ignorant, and unskilful,
(and the old men are yet foolish,) and of your unfitness,
do good for the salvation of men, when the old men are so ignorant, yea,
more than the young?
But it is the public maintenance that enables you, which did not enable the apostles;
and that is the thing which you in the apostacy have looked at;
for take away that from you, and pluck down your schools and colleges,
and we should have but few ministers in England among you; but few instructors.
So these are all made by men, since the days of the apostles, in the apostacy,
and teach for filthy lucre, and the love of money,
which is disapproved of by Paul and Timothy.
And take away but your public maintenance,
and few of you would be able to preach the gospel freely; if this trial was made,
to prove you, it would be found that your God was your belly, and him it was ye served;
and him it is that helps and enables.
But Christ and God was ever the enabler of his ministers, and prophets, and apostles;
whose the earth was, and they trusted in him; in Christ by whom all things were made,
that were made and created.

[.discourse-part]
_Principle._ '`It astonished us many times +++[+++ye say]
when we have talked with some of our hearers, that they knew so little of our doctrine,
which we have taught to them many years.
It is sad to us to hear many men that can talk so about matters of the world understandingly,
that can scarce speak a word of sense about the matters of their salvation,
or scarce give a reasonable answer to a question
of the fundamentals of christianity,`' page 19.

[.discourse-part]
_Answer._ Thus you have spoken to your shame, and it is manifest that here is, '`like people,
like priest.`' This shows ye have not profited them at all;
and it shows that the apostles`' words are fulfilled among you,
'`the doctrines and commandments of men,
perish in the using.`' And who are greater in the world in striving for the earth,
for maintenance, for tithes, casting into prison, haling before courts and sessions,
than you that have called yourselves pastors, and ministers of the gospel,
who have declared your fruits to all the nation?
And as unlike the ministers of Christ, as your hearers are unlike christians,
(by your own relation,) without reproving one another.
The apostle reproved them that taught for filthy lucre.
Christ reproved them that were called of men master,
and reproved them that taught for money, and for means,
and those that minded earthly things.
But how can ye reprove these things and live in the things yourselves?
how can one reprove another, and be in the same thing himself?
This will stink among all sober men, and set you all on heaps among one another,
as ye are.
So how can ye or your people either, know anything of the fundamentals of religion,
or salvation,
that deny the light that doth enlighten every man that cometh into the world?
Christ Jesus, the foundation of God, the wisdom of God, the end of the prophets,
and of the law, types, figures, and shadows?
Ye have denied the very key that opens to it.
Therefore ye all come short of the glory of God;
and teachers and people are all fallen into ignorance,
since the days of the apostles in the apostacy.
But now Christ is come, and coming to reign.

[.discourse-part]
_Principle._ They say, '`Upon the sad experience of men`'s ignorance,
we have been brought to consideration of our neglect, etc.
And our hearts have been brought low, to think how we have wronged Christ,
lest God should require your blood at our hands,`' page 19.

[.discourse-part]
_Answer._ Repent, repent! for ye have long deceived the people,
and their blood will lie upon you, and the blood of many,
that hath been shed in the nation, who have died in prison, and been whipped, stocked,
and beat through your means: their blood lies upon you all.
Repent! the judgment of the great whore is come.
The magistrates begin to see you, and you shall not ride upon them.
And of your ignorance and that of all your hearers, you may well cry out.
Repent,
and come to the light which Christ Jesus hath enlightened
every one withal that comes into the world,
to give you '`the light of the knowledge of the glory of
God in the face of Christ Jesus,`' out of the ignorance.
And none come to the light of the knowledge of the glory of God,
etc. but who come to the light that shines in their hearts,
(yea in darkness,) which Christ hath enlightened them withal.
Where it shineth out of darkness,
it gives them the light of the knowledge of the glory of God in the face of Christ Jesus.
And all are ignorant who are from the light, and wrong.
Christ,
and you have all wronged him that have denied the light
that doth enlighten every man that cometh into the world,
who are inwardly ravened from it, and have had the sheep`'s clothing:
and so have kept people in ignorance, blindness, and darkness.
But now the true light shines; the day of glory is dawning;
Christ and the saints are reigning and have the kingdom.
Glory to the Lord forever.

[.discourse-part]
_Principle._ They say,
'`Alas! that any reasonable soul should be so brutish!
most of their lives are spent in ignorance,
and worldliness, living in the flesh,`' etc. page 24.

[.discourse-part]
_Answer._ Here are the fruits of your ministry.
Are not ye ashamed to manifest your fruits thus to the whole nation?
Is this like a vineyard, that your people that you have taken maintenance of,
and the magistrates, should give you maintenance all this time,
and your people spend most of their lives, in ignorance, worldliness, and the flesh?
Is this like the fruits of the ministers of Christ, or the fruits of the false prophets,
that have not profited the people at all?
Did not the apostles keep them from those that bewitched them,
and would have brought them into the flesh.
And they ministered to the spirit, and got out the wheat and the corn.
And are not you fifty-eight ministers ashamed to publish such a thing to the nation,
as to say a reasonable soul should be so brutish?
Can that which is reasonable be brutish?
That which is brutish wars against the soul.
But this is but to discover your ministry, and what ye minister to,
and that of the soul ye are ignorant.

[.discourse-part]
_Principle._ They say,
'`Is it not a pity that God should have any reasonable creature that knows not his maker,
or his laws, or his own happiness?
Is it not a pity, that after all that Christ hath done, and suffered for the world,
any that calls themselves disciples, should so little know him and the salvation,
and should set so light by him,`' page 26.

[.discourse-part]
_Answer._ In this all you pastors and teachers have shown your work.
What! do not the creatures yet know their maker?
What!
Are they heathen yet?
What!
Do not the creatures yet know God`'s laws?
What!
Worse than the Jews, and heathens!
They that call themselves the disciples of Christ, and christians, so little know him,
after Christ hath suffered for them?
What hath been your work all this while?
What have ye been doing?
What have ye had wages for, that they so little know him that hath suffered for them,
and their salvation, and should set so light by him?
How can they prize him, or see any light from Christ,
when ye keep them from the light that doth enlighten
every man that cometh into the world?
without which none see salvation; and none see Christ that suffered,
but with it and by it: and none come to see and know Christ`'s end,
and the end of God`'s law, and prize him, and set much by him, but by the light.
And do not reasonable creatures know the law of God?
Are not reasonable creatures in the faith?
Are not the unreasonable out of the faith now, that know not their maker, nor his law,
and little of the suffering of Christ, or their own happiness,
and know little of their salvation, and set light by Christ?
Are not all these your fruits?
Are not all these your hearers, that ye complain of to the nation?
Have not ye now discovered yourselves in this to be those that have the form of godliness,
but deny the power?
That keep people always learning, but never able to come to the knowledge of the truth?
But are such as are led away with divers lusts, and laden with sins.
And now are ye complaining that your people serve the lust of the flesh, and the earth,
not knowing their Maker, nor his laws, nor their salvation, and setting light by Christ:
this ye may complain of with shame,
who are such as crept into houses before the apostles`' decease,
and since ye have gone over the world.
But now ye are discovered with that which gives to see the end of the apostacy and apostates;
which gives to see before the world was made.

[.discourse-part]
_Principle._ They say, '`If the gospel be hid, it is hid to them that are lost;
whom the God of this world hath blinded the minds of them that believe not,
lest the light of the glorious gospel should shine unto them; who is the image of God.
And the people perish, when visions fail,`' etc. page 28.

[.discourse-part]
_Answer._ Who believe not in the light which '`doth enlighten every man that
cometh into the world,`' the God of the world blinds their minds.
Every one that cometh into the world is enlightened,
that through the light they might believe.
And every one that believeth in the light, hath the witness in himself,
and abides not in the darkness, but hath the light of life.
And you that keep people from the light '`that doth enlighten
every one,`' etc. are the messengers of Satan,
out of the truth;
and the God of the world blinds the minds of such as do not believe in
the light that every man that cometh into the world is enlightened withal,
that all through it might believe.
And who believes in it '`that doth enlighten every man,`'
etc. the light of the glorious gospel shines in them,
which is the image of God.

[.discourse-part]
_Principle._ And you say, '`Visions are ceased, and revelations, and immediate inspirations.`'

[.discourse-part]
_Answer._ But I say, '`Repent, every one of you,
and come to the light;`' for the burdensome stone is fallen upon you,
and all that stand against the light '`that doth enlighten every man that
cometh into the world,`' shall split yourselves against the rock,
and be ground to powder.
And every one '`that cometh into the world,`' teachers and professors whatsoever,
must come unto the light which Christ Jesus the salvation, that saveth the soul,
hath enlightened them with, before they come to life,
or know the light of the glorious gospel shining in their hearts,
or come to the end of the law, or end of the prophets, or end of the revelation,
or out of the apostacy, or out of the Jews`' state, whose ears were stopped,
and eyes blinded,
out of the Gentiles`' state that go astray after the vanities of their mind.
So all you, and all upon the earth, Jews, Gentiles, and Christians of what sort soever,
must come to the light '`which every one of you is enlightened with,`'
before every particular comes to see his salvation or satisfaction;
yea, '`the salvation to the ends of the earth,`' the glory of Israel,
the light of the Gentiles.
The apostate Christians have ravened from the spirit of God within them,
have got the form,
but stand against the light '`that doth enlighten every man,`'
etc. such have caused the way of truth to be evil spoken of,
yea among other nations of the heathens.
They have been hot, and broiled in their lusts, '`having had the form of godliness,
and sheep`'s clothing;`' but all standing against '`the light that
doth enlighten every man that cometh into the world,`' smiting,
and striking their fellow servants.
Such must have their portion with the hypocrites.
But now the Lamb is come, and the saints reign with him,
who to every one will give a reward according to their works.
And the Lamb, and the saints shall have victory,
him by whom the world was made before it was made,
'`glorified with the Father before the world began.`'
Now is the seed Christ come to reign,
and the just have preeminence.
And I say to you all, the subscribers to all these books, priests, professors,
teachers whatsoever, your patience would have better covered your shame and folly,
than your heat, extremes, and rashness.
But your folly must come forth, that to all men it might appear.

[.small-break]
'''

Abundance more of stuff is in it, which is not worth mentioning,
whose words shall be your own burden;
the witness in all your consciences in the day of your judgment,
when your works are all tried with fire, shall answer.
I am a friend of your souls, and your eternal good, but judge your fruits, words,
and actions; for the day of the Lord is come that will try every man`'s work.
