[.style-blurb, short="The Reviler Rebuked"]
== John Stalham, who calls himself '`a servant of the great bishop of souls, who watcheth over a flock at Terling in Essex,`' in his book called [.book-title]#The Reviler Rebuked.# These are some of his principles.

[.discourse-part]
_Principle._ He saith, '`Immediate raptures and revelations seduce simple people`'s minds,`' etc.
And '`the perverse principles of their self-adorning light.`'
And '`the Quakers deny all external worship of divine authority,
as not to be found among us.`' And '`let learning be advanced among pious men,
for God hath his witty and learned ones.`' And the life
of their religion is the rule of the holy scriptures,
the glory of the blessed trinity.`' See his epistle to the protector.

[.discourse-part]
_Answer._ The life of religion is the spirit that gave forth scriptures;
for all that have the scriptures, and are out of that, are in the feigned religion.
And the scripture no where speaks of a trinity, but the Papists,
who are apostatized from the life of the scripture.
It speaks of Father, son, and holy ghost, and the water, spirit, and blood;
and the learned ones upon earth never know Christ with all their natural learning.
And if one get all the naturals upon the earth,
and the scriptures in all the natural languages,
and one supreme power of a nation tolerate all these languages to be the original,
and they have the scriptures in all these languages,
these are '`witty ones;`' but these know not God nor Christ by all this,
though they have all the scriptures,
while they are from the spirit of God that gave forth scriptures.
For that which brings to know God, is the revelation of the spirit of God,
the light which doth not deceive the mind;
but their minds are deceived that are from the light.
And all worship that is in the truth,
and in the spirit that gave forth the scriptures called the Old and New Testament,
we own, and is owned among the Quakers.
For God who is a spirit, led his servants, and prophets, and son,
by his spirit to speak forth the scriptures, which Christ the son is come to fulfill;
who saith, '`they that worship God,
must worship him in spirit and in truth,`' and that among the Quakers is owned.
And the light which cometh from Christ leadeth from perverse principles,
and from adorning self, for it leads out of its righteousness.
But perverse men ever stood against it in all ages, and so spurned at the foundation,
and overthrow themselves.

[.discourse-part]
_Principle._ He saith,
'`The spirit speaking in the scriptures.`' And '`them that say they have no sin,
a gracious heart will slight and despise.`' He saith,
'`The kingdom of God is not within them.`' Luke iv.
And saith, '`The soul prepares itself for death.`' See epistle to the church.

[.discourse-part]
_Answer._ Such as had gracious hearts, never despised him that had no sin,
but the ungracious did.
As for example, all the Pharisees against Christ, and against the apostles, and saints.
And the apostle told the Romans,
they were '`made free from sin;`' and they '`that were dead to sin,
how could they live any longer therein?`' he slighted them not, but encouraged them.
So we find thee not to be a minister of Christ,
and have proved and tried thy spirit to be of such as '`say they are apostles,
and are not.`' And the spirit spoke in them that gave forth the scriptures,
so they were declared forth.
And men may have the scriptures,
and not know the spirit that spoke in them that gave forth scriptures.
That is the cause that all people are on heaps about the words, and saying,
'`the spirit speaks in the scriptures,`' which spoke
in the holy men of God that spoke them forth,
and learned of God the Father of spirits.
So who have not the spirit, have but letters, and are ministers of the letter,
and not of the spirit.
And '`the kingdom of heaven is within you,`' said Christ, in Luke xvii.
to the Pharisees; and thou sayst '`with, or among them.`' And I say,
that is the kingdom within them which never consented to sin, and in you all,
which one day ye shall witness; which the eye and ear of the gazer, and observer abroad,
is closed and stopped to, which he must come to, before he be as a little child,
and know the leaven '`that leavens up the new lump;`' and know the kingdom,
'`which is like unto a grain of mustard seed;`' and where the diligent waiting is,
the soul comes to live, and the everlasting covenant is felt.
And thou that brings souls to be prepared for death, thou art more like to do that,
than to present them to God; a slayer and executioner,
so not a servant to the bishop of souls, where the soul liveth, and rejoiceth,
and comes out of death, and magnifies God the saviour.
And so the work of all the ministers of Christ, is to prepare souls out of death,
for life.

[.discourse-part]
_Principle._ He saith, '`The Bible is the soul`'s physic:
and people must depend upon the spirit`'s speaking in the scriptures.`' He saith,
'`the person of Christ is not his manhood:
and the natural light the Quakers call Christ within, and nature grace.`' And saith,
'`The body of sin is in the believer till he lay down the body.`' Epistle.

[.discourse-part]
_Answer._ The soul`'s refreshment is Christ, and its physician Christ; many have the Bible,
and do not know it, and the scriptures, as the Pharisees had;
the soul`'s physician is that which the scriptures speak of: many may have the words,
the Bible, and yet have not the thing it speaks of;
and they that have the thing it speaks of, have both.
And many holy men had their soul`'s physician before
the scriptures were written and printed:
and they that had the spirit that gave forth scriptures, had the soul`'s physic;
and they knew all the springs were in God, and the soul was in the Lord`'s hand.
And such as are in the spirit they depend upon that,
and they come to see the scriptures by the spirit from which they were given forth;
and such come into the unity of the spirit.
And the light, which is Christ within, by which all things were made and created,
was before the natural lights were, and before nature:
for all the naturals that were made, were made by the light, Christ Jesus,
who is the wisdom of God, by which all things were made,
with which wisdom we see over the natural lights, and over nature.
And the grace (that comes from the throne) that brings salvation,
which is the saints`' teacher,
teacheth not to call '`nature grace.`' And '`he that believeth is born
of God,`' and he '`overcometh the world,`' and entereth into his rest,
and shall never die.
And he that believeth hath victory, yea while he is upon the earth;
he cometh to witness the circumcision that puts off the body of sin,
and makes free from it, which the synagogue of Satan cannot witness.

[.discourse-part]
_Principle._ He saith,
'`The scriptures are the word of God,`' page 4. And
'`the spirit is given by the letter.`' And he saith,
'`the spirit proceeds from that which is put within the book or Bible,`'
page 5. And '`I judge them that pretend the spirit without the scriptures.
And the scripture is a more sure rule than visions and revelations,`'
page 7. And '`God that gave the letter,
gives the spirit with it, and by it,`' page 9.

[.discourse-part]
_Answer._ God gave the spirit before he gave forth scriptures.
The devil and wicked men may get scriptures, but they have not the spirit,
and none have it, but as they come to feel it given from God,
as it was given to them that gave forth scriptures.
And so people are to find the spirit of the Father speaking in them,
as it did in them that gave forth scriptures;
then the spirit answers to the spirit that gave forth scriptures;
then there is an unity with the words, and with God of whom they learned;
but many may have the Bible, and not know the spirit that spoke it forth,
but be erred from it.
And the scriptures are the words of God, the words of truth:
'`God spake all these words,`' '`He that adds to these words,`'
'`The words of God are pure.`' Christ is the word,
'`his name is called the word of God,`' who was before the words were spoken forth,
who comes in the volume of the book,`' to fulfill the words.
And the spirit was before the scripture was given forth;
for it led them to speak it all forth, the words of God, as they had learned of God:
so the spirit comes not by the letter, but the letter comes forth from the spirit.
And many had the scriptures, and knew not the revelation,
and judged the revelation of the son of God, and judged Christ who was come,
the end of the vision which was for an appointed time.
So therein thou hast concluded thyself to be among them that have the scriptures,
and set them up beyond the revelation of the son of God, which is the end of scriptures;
and '`none know the Father but the son,
and he to whom the son reveals him,`' though they may have all the scriptures.
And the things of God are revealed by the spirit of God.

[.discourse-part]
_Principle._ And he saith, '`The scriptures are the rule and the guide of saints.`' And saith,
'`the old administration of the covenant of grace is abolished,`' page 13.
He that understands, Matt. 11:2. 27. of immediate revelation only,
shuts out all mediate revelation by the scriptures,
and falsely accuseth the Lord of the scripture,`' page 14. '`And the apostle
saith not that the spirit reveals the deep things of God.
If we should deny the scriptures to be the rule,
we should deny the scriptures of God,`' page 18.

[.discourse-part]
_Answer._ The saints`' rule was the spirit that gave forth the scriptures,
and the word of God which fulfils the scriptures; without him they can do nothing,
if they have all scriptures.
And '`the spirit of truth shall lead into all truth`' And none know the scriptures,
nor God, nor can be a minister of the spirit by a mediate revelation,
but a minister of the letter; for who are ministers of the spirit are immediate,
and are in the immediate revelation of the scriptures
to them by the spirit that gave them forth;
and these minister to the spirit, and bring people to God the father of spirits,
that they may know what to reveal to others they minister to.
And all they that have the scriptures, and not the spirit that gave them forth,
are on heaps about words and want the rule.
And the covenant of grace, which is the end of the old covenant,
is witnessed and established, and cannot be abolished, which ends the decaying covenant.
And as for abolishing the covenant of grace, thou dost not know what thou speaks of.
And the apostle said,
'`The deep things of God were revealed by the spirit of God,`'
and no one knows the scriptures and the things of God,
but as God doth reveal them by his spirit.
In this thou hast shown thy ignorance of that spirit
which guided the saints to God the father of spirits,
which revealed unto them the deep things of God,
with which spirit again the scriptures are known;
and which spirit always ruled the saints, and guided them up to God,
and to speak forth the scriptures.
They did not deny the saints`' words spoken before,
but were in unity with them in the spirit,
and so came '`to the spirits of just men,`' which none do but those
who are come into the saints`' rule that gave forth scriptures.
And so people have had the scriptures, but have been inwardly ravened from the spirit,
thou and the rest of thy fellows, and have been all on heaps about words,
and so void of the revelation that they were in that gave forth scriptures.
For all are unlearned upon the earth that are not in the immediate
inspiration as they were that gave forth the scriptures,
and in the tongue of the unlearned, like the Egyptian Sea.

[.discourse-part]
_Principle._ He saith, '`Printing was a rare invention,
and it was the gift of God,`' page 21. And '`only
God`'s servants preached by the written copies,
and since by the printed volume,`' page 22.

[.discourse-part]
_Answer._ That which men have invented, is not the gift of God.
And men only preaching from the copies written, and since by the volumes printed;
in this hast thou shown that you have had only the sheep`'s clothing,
and that hath been it which hath made you ministers.
For they that were the ministers of the spirit,
their preaching was not from copies and volumes, that did not make them ministers,
but '`what they had received from the Lord,
that they declared,`' and were not ministers of copies and writings only.
But had you the copy and writings of the scripture, in the life that gave them forth,
you would have gathered people into the unity, but being ravened from it,
you bring them all upon heaps.

[.discourse-part]
_Principle._ '`The letter or writing of the spirit of God is the law,
and touchstone,`' page 23. He saith,
'`the scriptures are the spiritual sword,`' page 26. '`And
the scriptures are the ground of all saints`' actions.
And have not I written unto thee excellent things in counsel and knowledge?`' page 32.

[.discourse-part]
_Answer._ The Pharisees had scriptures, and had not the spirit that gave them forth;
so they wanted the word of God, the sword of the spirit,
and stood against the substance of the scriptures.
They had scriptures, but they were out of the saints`' actings;
for they turned against the just: and so do all upon the earth that have the scriptures,
but are out of the spirit that gave them forth;
they are out of the ground of the saints`' actions.
And none know the excellent things written of knowledge nor counsel,
but who are in the spirit that gave forth scriptures.
Though they have the scriptures in their own knowledge and wisdom,
yet they understand not the excellent things written,
but as they come into the spirit that gave them forth.
So thou art a man not dividing the word aright.
And many may have the scriptures, yea, the whole world may have the scriptures,
and not being in the spirit that gave them forth,
they break into sects among one another.
And the devil may come with scriptures, but hath not the spirit to fight withal,
who is out of the truth.

[.discourse-part]
_Principle._ He saith, '`Women are excluded from speaking,
though endued with more than ordinary gifts,
and they are not allowed to teach.`' See page 34. And '`the
canon of the apostles is the key to open the scriptures.
And the sure word of prophecy is the scriptures.`' See page 38,
'`which is a more sure word than an immediate voice from heaven`' He saith,
'`The word which the apostle speaks of to the Romans, in the mouth and in the heart,
is the gospel promises without.
Deut.
xxx. And the scriptures, books, and chapters, is the light that shines in man`'s heart,
and the new creature is too narrow for a rule.`' See page 44.

[.discourse-part]
_Answer._ The new creature is subject to the law of God,
for he is in Christ who is the end of law, types, figures, shadows, and parables;
and there is rule, direction, counsel, wisdom.
And the old man cometh to he subjected, which is not subject to the law of God;
and here comes the blessing and the peace of the Israel of God,
who walk according to the rule of the new creature;
for he walks in the life that gave forth scripture, which the old man walks out of.
And he may say,
'`The scripture is his rule,`' but if he is not subject to the witness of God in himself;
nor owns the light which Jesus Christ hath enlightened him withal, but doth the evil,
and loves the darkness, the light is his condemnation.
And '`the law is light,`' and '`the testimony of Jesus is the spirit
of prophecy.`' And many have had the old and new testament,
and stand against the light, the spirit of prophecy within.
And many may have the scriptures, books, and chapters, and stand against the light,
Christ Jesus, that doth enlighten every one that cometh into the world.
And so put the letter for the light, and walk from the light in their own particulars,
which should lead them into a new life.
Such come not to know the new life, nor the blessing of the Israel of God.
And the woman (the Evah) must be silent, for she was first deceived;
and the woman Jezebel, that calls herself a prophetess,
that must not be suffered to teach, or to usurp authority; but Christ in the male,
and Christ in the female, is beyond the first Adam, or Evah,
or she that calls herself a prophetess,
or the great whore that reigns over the kings of the earth.
There are all their languages under;
Christ in the females shall comprehend this as well as in the males, and give judgment,
and the daughters shall prophesy as well as the sons.
And such as limit or quench the spirit in the males or females,
are they that are apostatized and ravened inwardly from the spirit of God,
and despise prophecy, only have the sheep`'s clothing,
(such as thou and you,) and know not the spirit, but are ravened from it,
the spirit of God that hath power over all flesh, and so make yourselves ignorant of it,
and are such as quench it in others.
And the spirit of God in the apostles being witnessed, it opens the scriptures,
is the key, lets to see what hath been since the days of the apostles,
and has ruled and reigned, and had the dominion, the wolf in the sheep`'s clothing,
which has deceived the nations; and such as have led the world,
and brought them all upon heaps, and have never heard the voice of God,
(as they have published in the nation in print,) nor the voice of Christ,
and have not the same infallible spirit the apostles had,
and no immediate revelation nor inspiration as they had:
so these have taken away the key of knowledge from
among people since the days of the apostles;
and as for the word canon, ye may go to the Papists for that.
The apostles showed the fulfilling of the scriptures, that Christ was come,
and the apostles saw what Christ said should come, those who inwardly ravened,
went forth from them, whom the world hath gone after; we now,
with the same spirit the apostles were in, which you all are ravened from, do see you,
and what hath reigned since the days of the apostles.
Now is the fulfilling of the prophets.
And the word was in the apostles, and in the saints, yea, the word of faith,
and this comes to fulfill the scripture,
this word of faith which was preached in the heart and in the mouth;
and which was promised before.
And the light that shined was in the apostles`' hearts,
and the sure word of prophecy that did let see, and foresee, was in the hearts of people,
which led them to give forth scriptures.
And that which fulfils the scriptures, the prophecy, is of Christ, who ends it;
and the spirit that led them to speak it forth, was the spirit of prophecy:
many may have the scriptures, and not have the more sure word of prophecy.
And many may have the scriptures as the Pharisees had,
and stand against the revelation of the son of God from heaven, which is surer,
for he was before scripture was, who ends the scriptures:
for many may have scriptures and be out of the life,
and not know the revelation of the son of God, as the Jews did not,
and so say the scriptures are more sure than revelation from heaven,
so more sure than the son of God, who is greater than all.
The scripture was given forth by revelation, and none know it but by revelation.

[.discourse-part]
_Principle._ He saith, '`Christ doth not give to every man the light that leadeth to the Father,
and there is not in every man that redeeming light, which leadeth to the Father.
And it is false to say, the light which John speaks of, is a salvation light;`' he saith,
'`The light in every man is but the candle light of natural understanding,`'
page 56. And '`the light which every man hath,
is a low common benefit, and no drop of this immortal seed,`' pages 57, 58.
'`Nor is the light which every man hath, his mediation.`'
And '`I call the light which every man hath, natural,`' page 59.
And '`the light which every man hath, teacheth nothing of the way, truth,
and life of Jesus Christ,`' page 60. And '`the light which is in every man is opposite
to scriptures,`' page 61. This is the light which is in every man`'s conscience,
which is but natural.
And the apostle saith '`he warneth every man, and teacheth every man,
that he might present them perfect in Christ Jesus.`' But he saith,
'`The apostle did not warn every man: he did not level the saints`' light,
with every man`'s,`' page 62. '`It is not meant that every man is enlightened,
but the church.`' See page 63.

[.discourse-part]
_Answer._ '`I am the light of the world,`' that doth enlighten
every man that cometh into the world,
saith Christ the life.
So the light which every man that cometh into the world is enlightened with,
will let them see the life which it cometh from, will let them see their salvation,
Christ Jesus, will let them see their mediator, will let them see the truth,
for the light is truth, which cometh from Christ the truth.
And the light is Christ, the way, the truth, the life,
that enlighteneth every man that cometh into the world.
'`In him was life,
and the life was the light of men,`' in him by whom the world was made,
which light was before any natural lights were; the sun,
moon and stars are natural lights, and these were made by Christ the light,
who doth enlighten every man, etc.
Men having a light from him by whom the world was made, by whom all things were created,
who was before any thing was created, this lets them see before any created light,
or natural light; this gives every one the knowledge of life;
lets every one see the salvation to the ends of the earth;
and lets every one see the covenant of God.
They that love it and believe in it, come to the life Christ,
him from whom the light cometh.
The light is of the immortal seed, of Christ Jesus, one with the saints`' light;
the saints believe in that the world hates, and receive that which the world hates;
so it is the world`'s condemnation: it is the condemnation of them that hate it.
And so was he promised a covenant to the Gentiles, as well as to the Jews,
and so doth enlighten every man that cometh into the world,
according to John`'s testimony to the priests and
Levites who came from Jerusalem to examine him.
So the priests and professors now examine us in this age
respecting the light which the Quakers are witnesses of,
and bear testimony to, which Paul warned every man, and taught every man,
that he might present them perfect in Christ the light.
So the light is one with the saints`' light, that condemns the unbelievers.
And the light every man that cometh into the world is enlightened with,
that through it he might believe; and who believe in it, and receive it,
have the light of life, and they become the sons of God; and who hate it,
it is their condemnation: and they are against scriptures,
but the light is not against scriptures, but owns them.
And so the light is not so low as ye esteem it,
for it was before any thing was made or created.
As for the word trinity, there is no scripture for it;
ye find it in the common-prayer-book.
And the light in the converted shines out of darkness in their hearts,
and gives them the light of the knowledge of the glory of God, etc.
And the light in the unconverted shines in the darkness,
and the darkness comprehends it not.

[.discourse-part]
_Principle._ He saith,
'`that the light without the scriptures is no light,`' page 64. And '`To
call the light that doth enlighten every man the word of God,
is contradiction.`' And '`There was no light before the scriptures,
which is now revealed in scripture,`' page 64. '`God is light,
not the light in every man`'s conscience,`' page 68.
And '`the best light that every man hath, is but created.
Not one man in the world knows God till he find him
in scripture,`' page 69. '`The Lord Christ,
the eternal son, the essential word of the Father,
is more in scripture than in every man, or any man,`' page 70.
'`They that speak from the scripture, rightly understood,
speak more from Christ, than they that speak from the light within them.`'

[.discourse-part]
_Answer._ The light was before scripture was given forth:
the light was before the created lights were, and makes manifest all created lights:
for all created lights were created by it.
And all that ever had the scriptures are not in the light
that doth enlighten every man that cometh into the world.
He knows neither the word of God, nor Father, nor son, nor Christ, nor the Lord,
nor scripture.
And the word, and the Father, and the son, and Christ, these are to be found in man;
the Lord searcheth the heart, and is not to be found in the letter,
but it testifies of these things.
And they that speak so much of Christ from the letter,
which gives not life because it speaks of him, and are from the light within them,
which cometh from Christ, which doth enlighten every man,
etc. they speak as the devil doth.
And the Pharisees preached a Christ is come, as they did he was to come;
and stood against the light that doth enlighten every man that cometh into the world.
And they sent their priests and Levites to examine John,
as they do now who are professors and priests.
And many may have the scriptures, and yet be from the light, and deny the light;
the devil, who is out of the light, may bring scripture, and he hath not the light.
And that is light, and that is the word,
which doth enlighten every man that cometh into the world.
So he is all, and in all, and through all, God over all, blessed forever,
who shall make every tongue to confess, and all to stand guilty before him that hate it,
and say he is righteous.
And Christ is called the word of God,
who doth enlighten every one that cometh into the world.
And many may have the scriptures, and yet never know God,
till they come to the light which comes from the son, who reveals him.

[.discourse-part]
_Principle._ He saith, '`Christ saveth by the declaration, or by scripture;
and makes the declaration saving.`'

[.discourse-part]
_Answer._ Christ is the saviour, and that the scripture declares of and speaks of;
and many may have the scriptures, and declaration, and reject Christ, as the Jews did,
and all do, that deny the light that doth enlighten every man that cometh into the world,
the light that cometh from their saviour, which is not scripture.

[.discourse-part]
_Principle._ And to say, '`The light in every man gave forth scripture,
and will open scripture to us, is palpable darkness,
and contradiction to scripture,`' page 74.

[.discourse-part]
_Answer._ All are in the utter darkness, and know not the scripture,
until they come to the light that every man was in that gave forth scriptures,
for the light lets them see to what they were spoken, and Christ the end of them.

[.discourse-part]
_Principle._ '`And to say every man`'s light is the sure word of prophecy,
is an old fable,`' page 75. '`No man shall be able to spell out a syllable of the gospel,
by all that is written in man`'s heart.`' And '`the
universal light lays waste the free grace of God,
so never was it every man`'s light,
or free gift.`' And '`the light in every man`'s conscience is a bill of condemnation,
discovers no salvation,`' page 76. '`And that which Adam had before the fall was imperfect.`'

[.discourse-part]
_Answer._ The light that every man is enlightened with, is Christ Jesus, the gift of God,
the covenant of God, the way to the Father;
that all through the light might believe in him who is the way to the Father,
out of the state in the fall, the first Adam, who fell from that which was perfect,
and so became imperfect.
And the light which every man that cometh into the world is enlightened with,
which shineth in the darkness, will be his condemnation if he hate it,
and a sure word of prophecy to him he shall find it,
and will condemn him for all his faults;
and it was found in their heart that gave forth scripture,
which brought them to know God.
He goes unto fables who goes from the light: and all ye and the world are in fables.
And the light which every man is enlightened with that cometh into the world,
doth not lay waste the grace of God: but he that is in the light,
seeth the covenant of grace, and receives it.
And all that deny the light trample the new covenant under their feet.
And the light which every man is enlightened withal, is the light of the gospel;
which all men shall be judged according to, and it is it that discovers the saviour,
which doth condemn.

[.discourse-part]
_Principle._ He saith, '`The light is an imperfect light, and it is mixed with darkness.
And if the saints should say they have no sin, no darkness,
they are more dark and sinful,`' page 78. And '`Every man is in Christ
while he hath sin in him,`' page 79. '`And the light in every man is none
of the six principles in the Hebrews,`' page 81.

[.discourse-part]
_Answer._ The saints witnessed that the darkness was past, and the true light shined;
they were not in the night: and the saints were made free from sin;
and the night was over, and they were children of the day, not of the night.
And the light is perfect which doth enlighten every man, etc.
And all lights that were made, were made by the light Christ Jesus,
that was before any thing was made; this is it that discovers them, and shows them,
and this is perfect.
And all are in ignorance that are out of it.
And who is in Christ, doth not commit sin, is a new creature; old things pass away,
the old man and his deeds.
And in the light which every man is enlightened with, all the principles in the law,
in the prophets, in the Hebrews, end: for it was before any words were spoken forth,
glorified with the Father before the world began.

[.discourse-part]
_Principle._ He saith,
'`No man will ever be saved by his best obedience to the light
which doth enlighten,`' etc. page 85. '`Christ hath satisfied,
and merited for a certain number of sinners their deliverance,`' page 87.

[.discourse-part]
_Answer._ No man is saved, or doth witness salvation,
but who is in the light Christ Jesus doth enlighten him with.
And they who are in the light, are in obedience of faith, and neglect not the gospel,
nor the hearing the voice that speaks from heaven.
But they who hate the light, neglect the gospel, and him that speaks from heaven,
and do not come into the obedience of faith, but are in their own works, in the dark,
without light.
Christ is the offering for the sin of the whole world, not for the sins of a people,
but the seed Christ, the second Adam, overthrows all sins,
is the offering for all the sins that were brought in by the first Adam,
and reconciles to the Father, and is the restorer; and nothing shuts out,
but unbelief in the light, for Christ saith,
'`Believe in the light.`' And so Christ is the offering for the sins of the whole world,
and not for some only.

[.discourse-part]
_Principle._ He saith, '`Christ the surety pays the elect`'s debt,`' page 103.

[.discourse-part]
_Answer._ Christ is the surety for all that dwell on the earth,
that believe in him as he doth enlighten every man.
And God lays no charge of sin to the elect,
for it is not possible that they should be deceived.
And the cause of all bringings into sects, is, that people are out of the light,
and so out of unity, and see not the saviour, the redeemer, the substance of all types,
figures, parables, the end of the law, that goes upon the man of strife.
And so being out of the light, they are out of the unity, out of the covenant with God;
in the light is the covenant of God.

[.discourse-part]
_Principle._ He saith, '`The whole soul and body of saints, and every faculty of the soul,
and member of the body, there is some presence of sin in them all their days,`' page 113.

[.discourse-part]
_Answer._ The saints are sanctified, and washed, and cleansed, body, soul, and spirit,
and they are made free from sin, and then can live no longer therein;
and the body of sin is put off.
And they witnessed the darkness was past: so then the works of the true light shined,
and the day was come, and they were of one soul.
And they witnessed that as he was, so were they in this present world.
And he that is in Christ is a new creature.
And where Christ is within, the body is dead because of sin.
And he that is born of God doth not commit sin.
And the saints were upon the earth when they were made free from sin,
and not sin in them all their days, as thou speaks.

[.discourse-part]
_Principle._ He saith, '`sin dwells in the saints; if any saint think otherwise,
he knows not himself: and if he be one really sanctified, he is under a strong delusion,
and drowsy dream,`' page 119.

[.discourse-part]
_Answer._ He that is sanctified is sanctified from sin, and washed, and cleansed;
and he that is out of this sanctification is in the drowsy dream;
for they who are in sanctification, are in Christ the righteousness of God,
and are awakened to righteousness, out of the fall, in the second Adam, and drowsiness,
and dreams, and delusions that come in the first Adam.
And sin, and drowsy dreams,
and delusions dwell in them that pretend they are sanctified ones, and are not really.

[.discourse-part]
_Principle._ He saith, '`It is a Popish tenet that sanctification is wrought within men,
and justification, or a believer`'s being justified from sin, and ungodliness,
and not in it;
but the mystery of iniquity lies in this qualification,`' page 120.
And '`they that are justified by their sanctification, it is a falsehood.`'
And '`that none are justified but saints perfect in holiness,
is a notorious contradiction,`' page 121.

[.discourse-part]
_Answer._ He that is the sanctification, is the justification,
and so by their sanctification are they justified; it is one and the same,
that which sanctifies, justifies.
And every man that cometh into the world has a light that cometh from Christ the sanctification,
redemption, justification: but they that are not in the light, are with it condemned.
And such as are in the light come into perfect holiness,
and their sins are not imputed to them; but they that do not believe in the light,
the spirit of truth that leads the believer into all truth,
reproves them for their unbelief, and their righteousness, and their judgment,
and so doth not justify, but reproves them.
And the justification within, roots out all Popery, and all contradiction.
But to speak of justification and sanctification without, and not manifest within,
ye are yet in the first Adam,
(in the Popery where ye must have a purgatory to
cleanse,) and not in the righteousness of Christ,
and sanctification and justification.
So such are reproved that can talk of it without, sanctification without:
there is the old Adam, in the sin and transgression.
And all falsehood is among them that can talk of justification without them,
and not witness it within them.
For they who witness Christ within them, witness justification there, and sanctification;
for '`Abraham believed,
and it was imputed to him for righteousness;`' and his belief was within,
and he saw Christ`'s glory.
And such as believe come to witness the imputation;
but such as come again to witness that, are nearer than when they did believe;
and to witness that they have received Christ within, is the end of their belief.
There they witness the righteousness itself without imputation, which is the substance,
that which the promise ends in, and all the fathers hoped for,
who stood in the imputation, and all the believers in him.
Christ being come, the end of man`'s belief, the righteousness itself,
here is a justification alone, without the imputation, Christ the righteousness of God:
blessing and glory forever!
And a believer that is justified is a new creature,
is past from the death which came by sin, and comes to enter into his rest,
where sin is not.
And all the falsehood and contradiction are without
the possession of justification and sanctification,
which reprobates and unbelievers talk of in the mystery of iniquity,
who have the sheep`'s clothing, the outside, the clothing of the saints,
yet are ravened from the spirit inwardly.
These have not been like to own justification within, or sanctification there,
that were inwardly ravened from the spirit of God:
and all must come to that which they ravened from, and they themselves,
before they feel the justification, sanctification, Christ within them,
and have received the substance, the thing the scripture speaks of.
Not believing in the light, and going from it, though they get all the sheep`'s clothing,
all the good words, and the form of godliness, and obey not the gospel, the power of God,
yet are they not thereby justified; for none obey the gospel,
but who obey the light within.
And who are justified it is by the faith of Christ Jesus,
and without faith they cannot please him.
And who are in the faith, are the believers in the light,
and so justification and faith do change from the old nature and mind.

[.discourse-part]
_Principle._ He saith, '`They are not justified because they are new born,
nor for their believing,`' page 122. And '`I can say I am crucified with Christ,
and yet I have a corrupt, rotten heart, and an old lying heart,
(as before he with,) and Christ lives in him,
and there is a body of sin and death dwells in him:
and the life that he now lives in the flesh,
is by the faith of the son of God,`' page 124.

[.discourse-part]
_Answer._ '`Where Christ is within,
the body is dead because of sin;`' and where the faith of the son of God is lived in,
it gives victory over sin.
And the life of Christ is out of Adam in the fall, in sin and transgression.
And the circumcision comes to be witnessed that puts off the body of sin.
And where the life of Christ is lived in, the new covenant is there, the new heart,
and the rotten, corrupt, and lying is put off, the old man and his deeds,
with his deceitful lusts.
And '`he that believes is born of God,`' is justified,
and he comes into the faith by which he pleaseth God;
and he that doth not believe is out of the faith,
and it is impossible he should please God, and is out of that which should justify him.

[.discourse-part]
_Principle._ He saith,
'`Christ`'s works in us are not to be joined with our faith in Christ`'s works,
for that brings into the wilderness,`' page 131. And '`to
say that men are justified no farther than they are sanctified,
is to deny Protestant doctrine,`' etc.

[.discourse-part]
_Answer._ Men are justified by the believing, and in the faith and by the faith,
and in believing they overcome, and have victory; and there are mortification,
and sanctification, and redemption, and justification, all possessed together in the one,
which is Christ, and this to the particular satisfaction.
And all Protestants, or whatsoever, that have a justification or sanctification,
and they in the unmortified state, unsanctified, they are out of the faith that purifies,
out of the belief of him that is born of God,
who hath '`passed from death to life,`' and so are out of the substance that justifies,
and are without Christ, and so are reprobates; but where Christ is within,
there is justification, sanctification, and redemption.
And they are they that blaspheme the tabernacle of God, and them that dwell in heaven,
that '`call good evil, and evil good,`' and lead into snares, and into the wilderness,
that go about to confound the justification;
but they split themselves upon the rock that deny the light.
And Christ is the offering for the '`sin of the whole world,`' who doth '`enlighten
every man that cometh into the world,`' that all men might believe in him,
the offering; and they are justified in him from all things which the law could not do.
And here is the covenant of God to the Jews and Gentiles, the light of the Gentiles,
the glory of Israel, the new covenant to the Jews, the law in the heart and in the mind,
by which people should not need to say, '`Know the Lord;
for all should know him from the least to the greatest,`' the '`salvation to the ends
of the earth;`' where the way of redemption is the way for '`the ransomed to walk in;
in which the fools shall not err;`' in which way there is no wilderness,
nor slippery places; but the path of life, the way of the just, and of holiness,
and the way of sanctification, and the way of redemption and justification.

[.discourse-part]
_Principle._ He saith, '`Christ was a sinner by imputation,`' page 132.

[.discourse-part]
_Answer._ The scripture doth not speak such kind of words; but that he '`knew no sin,
no guile was found in his mouth:`' a lamb without spot or blemish,
though it pleased the Father to lay the iniquity upon him,
'`by his stripes we are healed.`' And by the one offering,
he perfected forever them that are sanctified,
made himself an offering for the sins of the whole world;
who breaks down the partition wall between Jews and Gentiles, slays the enmity among men,
reconciles in one unto the Father by his body, his death upon the cross.
Of his body are all the professors, Protestants and Papists upon the earth, ignorant,
of this seed that breaks the enmity; therefore are all in the enmity one among another,
having sheep`'s clothing, but the sheep in you is not put forth;
but the wolf is ravening abroad against the sheep, tearing them where the seed is risen.

[.discourse-part]
_Principle._ '`He that throws off imputed righteousness,
may go shift for his justification where he can get it:
and Christ shall profit him nothing, though he be in faith or love,
and self-denial,`' page 133. And '`it is not the work of
Christ in us that justifies and reconciles our persons.
I can detect this for an error, that Christ`'s works in us,
is that which justifies our persons before God,`' page 134.

[.discourse-part]
_Answer._ Christ works in us faith, and is the author of it,
and by faith is every one justified in the blood of the seed, the flesh of Christ,
the Lord from heaven, shed for the sins of the whole, world.
And this faith is in the blood of the seed, not of the first Adam, nor the beasts,
but the blood of the seed Christ, the precious blood which is the life of saints,
and his flesh which is the food of saints, which whosoever eats and drinks,
hath life in the son of God, and lives in him as he lives in the Father.
And this is wrought within, and no one knows it,
but as it is wrought within by the faith in the blood of the '`Lamb
slain from the foundation of the world,`' the great '`sacrifice
for the sin of the whole world,`' that overthrew death and hell,
bruised the serpent`'s head, devil, and sin, the sacrifice for the whole world,
the blood shed upon the cross for the sins of the whole world.
The blood of the seed, which is the life that cleanseth, and this blood is felt within,
for it purgeth the conscience from dead works to serve the living God.
And here is the great mystery of God, and the wisdom of God,
which covers all the wisdom of the earth,
the knowledge and wisdom of the understanding ones of the earth.
The seed and the blood of '`the Lamb slain from the foundation
of the world,`' which sacrificed and offered up the body prepared,
who fulfilled all types, figures, offerings, ends them and all other bloods,
whom death and the grave could not hold, dead, raised again,
set at the right hand of God, manifest in the saints,
and in the midst of his church singing praise, '`was dead, and is alive,
and lives forevermore,`' manifest in the saints.
And he that hath him hath life, and he that hath not him, hath not life.
And they who witness Christ within, witness the end of imputation,
they witness the thing itself, the end of their belief,
and they possess the sanctification, and such come to know faith and love.
And such as may have all the scriptures,
and preach of justification and sanctification without them, and not within them,
are as the Jews, are as the witches and reprobates.
They are reprobate that witness not Christ within them, nor sanctification there,
nor justification there, and so witness not faith, and love,
nor the faith that works by love; and they are in the error and shifts thou talks of,
and Babylonish; and none come to witness the reconciliation,
but who witness Christ within.
So these are out of justification and sanctification.
If he be not within, they cannot witness reconciliation:
if they are not believers in the light of Christ, they cannot witness justification,
but condemnation.
But in the light, in Christ, Christ received in them, justification, sanctification,
and reconciliation are received, Christ Jesus the light,
that which reconciles to the Father.

[.discourse-part]
_Principle._ He saith, '`The body of sin is the natural body, consisting of flesh, and blood,
and bones,
and the living soul is immortal,`' page 140. And '`sin will dwell in the house,
until the house be plucked down over its head, which is the natural body.
And there is not one saint that is absolutely free from the in-dwelling
and working power of sin,`' page 140. '`To plead for perfection,
is inherent holiness, and to serve under antichrist`'s colours,
and to make void the suffering of Christ.
He that holds the saints perfectly fulfilling all the law,
in all degrees of obedience and conformity to it, in this life before death,
hath drunk antichrist`'s cup,`' page 144.

[.discourse-part]
_Answer._ The saints after they witnessed the body of sin put off,
and a being made free from sin, glorified God in their bodies, souls, and spirits.
And so the body of sin is not the creature, for that causeth the creature to groan,
before it cometh into the liberty of the sons of God, that causeth the body of sin,
the clothing that comes upon the creature, the old man, which cometh by transgression,
the first Adam, the light that leads out of transgression,
brings the creature '`into the liberty of the sons of God,`' and so,
'`who is in Christ is a new creature;`' and '`old things
pass away,`' and the body is the temple of God,
a holy temple.
And the living soul is immortal; yet many of thy generation say it is human, that is,
earthly, yea, that Christ`'s soul was human, as ye may see in this book,
in the principles of them that call themselves teachers and pastors,
whose souls are in death, and in whom life and immortality are not come to light,
through the power of God, which is the gospel.
So you have showed your ignorance of the soul.
And they who witness the perfect holiness, and preach up that,
come from under antichrist`'s kingdom.
They that preach up imperfection, wear antichrist`'s livery, and his colours,
and sound the trumpet of antichrist; and who are in the righteousness,
are in the perfection itself, without a thing merited by man in his will.
And who loves God, keeps his commandments, and to him they are not grievous.
And this was the seed, that kept the commandments of God, that antichrist, beast,
mother of harlots, and false prophets made war against,
as you may read in the Revelations.
But this seed are a burdensome stone unto you all, that keep the commands of God,
that love God; and '`they that are born of God do not commit sin.`' And the natural body,
which is flesh, blood, and bone, is not the body of sin;
it was never read so in the scripture, that that was the body which was to be put off;
for the saints had bodies after they witnessed the body of sin put off,
and were made free from sin.

[.discourse-part]
_Principle._ He saith,
'`That R. F. is against the doctrine of sin continuing
in the godly till death,`' page 148.

[.discourse-part]
_Answer._ That doctrine of sin was never preached up by the apostle,
that it should continue in the godly till death.
I say, it continues not in the godly, for the godly are like God, out of sin;
it continues in the ungodly that are not like God.
And he that is in Christ, is at the end of the law, and the precepts, and the statutes,
and the ordinances, and the commandments, and is in the substance, God`'s righteousness.

[.discourse-part]
_Principle._ He saith, '`The letter is no dead letter, and it hath life in itself.
And '`if there be but this letter or ministry,
it is Christ`'s two-edged sword,`' page 153. 155.
'`It serves unto his design of searching hearts.`'
And '`the apostle would take people off from the conceit of perfect attainments,`'
page 162.
And '`may not filthy hearts transform themselves in the fancy of perfection,
as the devil into an angel of light?`'

[.discourse-part]
_Answer._ The devil transforming himself into an angel of light, or into a similitude,
is like unto all the filthy hearts who fancy perfection without them, not within them,
and speak of Christ without them, not within them, as the devil did.
But it was the doctrine of the apostle, who preached Christ the covenant of God,
to bring people from that which made nothing perfect, to that which was perfect,
and bid them be perfect, and of one mind;
and he '`spoke wisdom among them that were perfect;`'
so he did not bring the people from it,
but to it.
And the letter itself is dead, as it is of paper and ink.
And all ministers of letters and books written in paper and ink,
and who speak from letters of paper and ink,
and have not received from God what they preach, are ministers of the letter,
and they are the ministers of death,
though they minister all the letters written in the scripture,
and have but the sheep`'s clothing, and beget not to God;
but only make proselytes as such ministers did in old time, among the Jews.
But they that were ministers of the spirit that gave forth the scriptures,
had '`the sword of the spirit,`' which the Jews, the ministers of the letter, had not.
They that are out of the spirit, though they have all the scriptures given forth from it,
are out of the spiritual weapons.
And that which searcheth the heart, is that which gave forth the scriptures,
which led all the holy men of God to speak them forth, who is the Lord,
the searcher of the hearts.
Which spirit owns all the words of the scriptures of truth declared forth from the spirit;
but the spirit was before the scripture was given forth.

[.discourse-part]
_Principle._ He saith, '`Men that are redeemed from all earthly worships,
perfectly justified before God, sincere in their sanctification,
yet they are in concupiscence, and blemishes,
and conflicts,`' page 166. And '`the word of God doth not
abide in them that say they have no sin,`' page 179.

[.discourse-part]
_Answer._ They who are redeemed out of all earthly worships, and sanctified,
are redeemed from blemishes, from conflicts, from concupiscence,
and by their redemption they come to witness the kingdom of God that '`stands in righteousness,
peace, and joy in the holy ghost,`' out of conflicts; and they who are in the spirit,
are in that which mortifies sin.
And the word of God makes clean where it dwells; they are sanctified by the word,
and made clean.
It comes, and finds the sin, and takes it away, and makes clean, and hammers it down,
cuts it down, burns it up,
'`reconciles to the Father,`' whom sin and iniquity separated from.

[.discourse-part]
_Principle._ He saith, '`sacramental water, and sprinkling baptism and water,
etc. shows our being ingrafted into the body mystical,`' pages 176. 178.
'`which consists of a sign of a thing signified.`'

[.discourse-part]
_Answer._ Sprinkling infants is a sign of your own making,
and sacramental water the scripture doth not hold forth,
but it is a thing presumed above what is written.
And that sign, a tradition, doth not bring into the body mystical, but leads from it;
neither doth any elementary thing.
But that which baptizeth into the body is the spirit, whereby all come to be one.
And that baptizeth not into an elementary body, but into a glorious body,
the spiritual body.
For there are lying signs come since the days of the apostles,
which are out of the apostles`' practice.
You can show nothing for your sprinkling with your sacramental water.
But the baptism that the scripture declares of, is owned in its place,
and that of the spirit.

[.discourse-part]
_Principle._ He saith, '`Bread and wine are spiritual institutions,
and are not carnal in a sense as set in opposition to spiritual institution:
and that is not mere carnal bread and wine after Christ`'s institution to be used,
nor an ordinary bread and wine.`' And he saith,
'`In the Lord`'s supper is Christ`'s body,
and it is his blood,`' page 188. And '`this is my body and blood,
the word of a command is,
do this,`' page 191. And '`Christ fed not the souls with wheat bread,
and red wine,`' etc.

[.discourse-part]
_Answer._ By all this what differ ye from the Papists?
have not ye laid their foundation, and laid their ground?
Bread and wine, are but bread and wine, temporal things, things seen,
and may turn to ashes; but the body and blood of Christ will not do so.
And bread is not spiritual, and wine is not spiritual, but are things seen and visible.
And who eats the flesh of Christ, and drinks his blood, '`hungers no more,
and thirsts no more;`' but who eats temporal bread and wine, '`hungers more,
and thirsts more.`' And Christ did say, '`as often as ye do eat this bread,
and drink this cup,
ye show the Lord`'s death till he come.`' And that
which the apostle had received of the Lord,
he delivered to the Corinthians.
'`As often as they ate that, and drank that, they were to do it in remembrance of him,
showing the Lord`'s death till he come.`' But then
saith the same apostle to the same Corinthians,
in his last epistle, '`Examine yourselves.
Know you not that Christ is in you, except ye be reprobates?`' And said,
'`while we look not at the things which are seen;
for the things that are seen are temporal.`' So bread and wine are things that are seen,
are things temporal, '`but the things that are not seen,
are eternal.`' Now bread and wine, are but bread and wine,
not spiritual after consecration; it is but the same bread that it was before,
and is no nearer the body of Christ after they have consecrated it, than it was before.
Who is in the life and power of God, that gives every creature its being,
and causeth every creature to come forth, is in the life and virtue of all creatures,
and the being of all creatures, and the wisdom of all the creation, that is spiritual.
He that giveth every creature its being, and causeth every creature to come forth,
and gives the sense and feeling of all creatures, is spiritual.
And here the soul comes to be known, and the seed Christ, and his body, and his blood.

[.discourse-part]
_Principle._ He saith, '`The worship of God in the spirit stands out of man`'s will,
and they must wait in the light to feel the spirit;
but let all lost souls beware of this counsel.
And to bring people to the commands of the spirit
is opposite to the scripture letter,`' page 204.

[.discourse-part]
_Answer._ All true worshippers of God that he seeks to worship him, are in the spirit,
and in the truth, that which the devil is out of, which man`'s will is out of;
and in the spirit that gave forth the scriptures,
all poor souls come to worship God aright, and magnify God, and glorify God,
and to pray in the spirit, and to stand in the counsel of God.
For '`no prophecy of the scriptures came by the will of
man.`' That which led them to speak forth scriptures,
was beyond man`'s will.
So men`'s will getting the scriptures, which no prophecy of it came by,
they cannot worship God in the truth, nor in the spirit, but in their own wills.
But who are in the spirit and truth, that led them to speak forth the scriptures,
that learned of God the Father of spirits, and God of all truth,
this is not will-worship.
Now, will-worship is among them that have the scriptures
given forth by the spirit of God in their own wills,
which no prophecy of it came by: and can sing, pray, preach, and read in their own wills,
and are out of the spirit that gave it forth; they are in a will-worship,
out of the worship of God in the spirit.
And such are opposite to the scriptures,
and cannot agree with the letter of the scriptures, that are fighting about words,
falling into sects and heaps about the words.
But the worship of God is in the spirit that gave forth scriptures,
and they who have learned of God the Father of spirits,
own all the scriptures in their place, and are not opposite to them.

[.discourse-part]
_Principle._ He saith, '`Never were psalms sung as they ought to be,
but they had some musical tune or poetry,`' page 205. And
'`The holy ghost made overseers and elders over the church,
but that was not immediate,`' page 207. '`That no man can read
out of scripture that Paul was free from covetousness,`' etc.

[.discourse-part]
_Answer._ Paul saith, '`Let not covetousness be once named among you,
as becometh saints.`' And that no covetous one should enter into the kingdom;
and he saith,
'`it is idolatry.`' And the apostle lived the life of the son of God through faith,
witnessed he was made free from the body of sin, and had victory over it, and thanks God,
that '`there was no condemnation to them that were in Christ Jesus.`' Paul was in Christ,
where there was no condemnation, which covetousness is out of.
And the holy ghost is immediate that makes the officers in the church.
It is the same that was in them that spoke forth scriptures.
And as the holy ghost, that leads men to speak forth the scriptures,
makes elders and overseers in the church, these are not made by men,
but these see the fulfilling of the scriptures, and come into that which fulfils it,
and are in it.
And for your singing your psalms, and your poetry,
and setting them in frame and a musical way, these are come up since the pope,
as tunes and organs; since men have ravened from the spirit, and gone from that,
they have got up this poetry, and turned David`'s conditions into a metre,
and given them to people who are ignorant of David`'s conditions.
And psalms are spiritual songs,
of which all are ignorant when they are from the spirit of God
that led the holy men of God to speak forth the scripture;
with which spirit of God, all the psalms, and spiritual songs, and hymns are seen,
which from it were given forth, and all the scriptures,
and in that is the singing in the spirit.
And for the ministers`' maintenance, the apostle said, '`Have not I power to eat,
and power to drink?`' (And Christ said, '`Freely ye have received,
freely give.`') This was not spoken to the heathen, nor Jews, nor Gentiles,
who were unconverted, but was spoken among the saints who were a vineyard,
and to whom spiritual things had been sown,
and to such whose hope they were made partakers of.
But hirelings and those that teach for filthy lucre,
'`that mind earthly things,`' that seek for their gain from their quarter,
'`that bear rule by their means,`' are all out from this,
and were judged by the prophets, Christ, and the apostles,
to be such spirits as had got the form, and taught for the earth,
and made the earth a wilderness.
And such got not out the wheat, and ploughed but in vain,
which is the ploughing of the wicked, which is sin.
So there is a great difference between these and those that preached the gospel,
the glad tidings, to all nations, which relieved the oppressed:
for the oppressed being relieved, life and immortality came to light through the gospel:
the wheat was gotten out, the spiritual things sown, the vineyard planted,
the flock was known, the milk was known, the corn gotten out:
among such some used their power to eat, some did not,
(mark,) that power that did not oppress, that did not hurt.
But all you that preach for tithes, and will take money of them that ye do no work for,
by a law, and cast into prison if they will not give it, and take treble damages;
you bring not the glad tidings to the nations, you are the oppressors of the nations,
of the just; and are not helpers and relievers of the oppressed:
and so have made manifest your apostacy; and that you are apostates,
out of the apostles`' doctrine, and out of the gospel, the power of God,
which the apostles were in.
But now shall the gospel be preached that gives liberty to the oppressed,
and strikes down all the oppressors.

[.discourse-part]
_Principle._ He saith, '`God sends either mediately or immediately;
and he sends by man`'s ministry mediately,`' page 211. And saith,
'`they pretend to no such call of an apostle,
an officer in every church as Paul,`' etc. page 213. And
'`Some are converted mediately by those sent by man,
with their mediate call,`' page 214.

[.discourse-part]
_Answer._ All who are converted, are converted with the immediate:
there are none converted upon the earth,
but it is with the immediate spirit of God that mortifies.
And all ministry that is sent of God, and from God, and called of God,
where that speaks to them it is immediate, for whosoever hears his voice,
it is immediate and powerful.
And all ministry of man, sent out by man,
(which is mediate,) never converts any souls to God, for the soul is immediate,
and mediate reacheth not to the immortal soul;
but the immediate ministry reacheth to the immediate immortal soul,
and so preacheth the immediate gospel to it, the power of God.
And all ministers that are sent forth in the power of God,
who are moved of God to speak to any by the power of God, the eternal spirit of God,
the holy ghost, that is immediate, and not of man, and that begets unto God,
and converts them; that is immediate, not mediate,
and they do as the power of God moves them, which is immediate,
and that is for God in that place.
And they shall feel the spirit of God in them witnessing with that power,
and the spirit of God in another, that speaks to them.
And the power of God is eternal, where it moves it is one;
and the spirit of the prophets is subject to the prophets.
And all you since the days of the apostles,
that do not pretend to such a call as the apostles had,
and to have such officers as the apostles in every church,
(which we do believe you have not,) you have shown
that the holy ghost hath not made you overseers;
and you have declared yourselves to the world to
be such as inwardly ravened from the spirit of God:
and all to be but ministers of the letter, not of the spirit,
and so only have the sheep`'s clothing.
So ye are such as have brought people and nations to be all on heaps, and like waters:
not made overseers, as the apostles were, not having the call as the apostles had;
so not by the holy ghost, not by the immediate power of God, not preachers of the gospel,
as the apostles were, who were immediate.
Therefore these things have been wanting, the holy ghost to make you overseers,
and the spirit the apostles were in,
which would cool and quiet all the spirits of the people.
For want of this ye are all on heaps about scripture.
But the holy ghost opens it again to overseers.
And so ye that have ravened from the spirit of God inwardly,
there is no talk among you to have the call as the apostles had, and to be overseers,
as they were; that we do believe, your fruits declare it.
But the spirit is witnessed which the apostles were in,
which hath discovered you and your church.
Glory be to the Lord God forever!

[.discourse-part]
_Principle._ He saith, '`Immediate teaching in the least degree of God immediately,
is contrary to Daniel ix.
and Timothy.`' And saith,
'`I am yet to learn the promise of immediate teaching of God,`' page 216.
And '`Women are excluded from this kind of prophecy,`' 218. He saith,
'`Ministers, pastors, teachers, having the grace of God, gift of prophecy,
called out among brethren to office, to oversee a flock, as bishops,
of the Lord`'s institution: these are not so taught immediately,`' page 220.

[.discourse-part]
_Answer._ All bishops, overseers, and officers, that are of God, are taught immediately,
by the same spirit and power that the apostles were in, and owned and allowed by them:
for the holy ghost is immediate that gives them to oversee;
and all who feel the grace of God, and turn it not into wantonness,
feel that which is immediate.
And such as have turned the grace of God into wantonness,
and walk despitefully against the spirit of grace,
and set up a heap of teachers after their own lusts,
are gone from the immediate grace of God that brings salvation.
And all the teaching of God, in the least degree, is immediate,
which brings them to open parables,
speak forth parables to the nature that is atop of the witness, that spirit is immediate;
though they take a mediate parable or comparison,
yet the spirit is immediate that gives them to understand the parable aright.
And the gift that was in Timothy, that he was not to neglect, was immediate,
whereby he came to discern on whom he was to lay his hands, and on whom he was not,
and not suddenly to lay them upon any man.
And that which brought Daniel to understand by writings in books, was immediate;
and that which brings to understand the scriptures is immediate.
'`I will pour out my spirit upon all flesh,
and your sons and daughters shall prophesy,`' and that is immediate,
and prophecy is not to be quenched in the daughter no more than in the son;
it is one in the male and the female.
And we do believe thee, and you all, who are apostatized from the apostles`' doctrine,
in the apostacy, ravened inwardly from the spirit of God,
that ye are yet to learn the immediate teaching.
So are the antichrists standing against the light which Christ
Jesus hath enlightened every one withal that cometh into the world,
the covenant of God in the heart, with which all people shall come to know the Lord,
and be taught of God, that they need not say, '`Know the Lord.`'

[.discourse-part]
_Principle._ He saith,
'`conclude that immediate teaching did not only furnish
men for a teacher`'s or minister`'s function,
but mediate ways also,`' page 211. And '`The Quakers think it a lie against God to say,
the spirit is in the letter and scripture, and is given by it,
and make a jangling about immediate teaching,`' page 222.

[.discourse-part]
_Answer._ No one is furnished for the work of the ministry of God,
but who is in the immediate spirit of God, which is to minister to the spirit.
And there is no one made a minister.
of God by the mediate, but by the immediate.
For who hath the spirit of God, the spirit of wisdom and understanding,
to sing in the spirit, or pray in the spirit, it is immediate.
And all that are out of that are in the earthly, sensual,
and devilish perishing knowledge, and that understanding must come to nought,
and that wisdom must be confounded.
And as for the word function, it is thy own, and must come to nought.
And the spirit is immediate that led the saints to give forth scripture.
The spirit is not in the letter, but it was in them that gave it forth.
And they that have not the spirit in them, that was in those that gave it forth,
and are disobedient to that, are they that say the spirit is in the letter.
And such say that immediate teaching is jangling,
who are from the spirit that is immediate, ravened from it in their own particulars;
such are never like to beget to God, but are the ministers of the letter,
not of the spirit; and by that which the devil and they are out of,
are they comprehended, who are in the jangling and in the lie.

[.discourse-part]
_Principle._ He saith, '`Christ took up a Bible, and preached on a text.
And as for uses, points, trials, and motives, you must go to Titus 3:16.`'

[.discourse-part]
_Answer._ Christ who came to fulfill, took the book, and read, and said it was fulfilled.
He did not take a text, as you do, and lay half a year in it, as some of you,
and have ten shillings a day, more or less, for your pains; but he said it was fulfilled.
And for that place in Titus, there is not a word of motives, nor points, nor trials,
nor uses, as you pretend;
though he who was in the faith did study to divide the word aright,
in whom was the gift of God which was perfect.
This is not like your divination of your brain, for money, which ye sell weekly;
nor your taking a text, and laying half a year in it.
And thou hast shown thyself and them to be novices.

[.discourse-part]
_Principle._ He saith, '`Though the righteousness be wrought in us by the strength of Christ,
and be found in us that are sanctified; yet as to justification of a person,
Paul would not be found in it for a world.`' See page 229.

[.discourse-part]
_Answer._ '`The righteousness of Christ fulfilled in us,`'
and to be found in the righteousness of Christ,
that was the thing the apostle strove after, in that which ended the law,
not in his own righteousness.
And that righteousness which is wrought in us by the strength of Christ, is Christ`'s,
where sanctification is witnessed; this is Christ`'s, who is the end of the law,
and in this was the apostle found, and this he stood for, which was out of the world.

[.discourse-part]
_Principle._ '`And honour all men.`' And the fifth commandment
he brings '`for bowing the knee,`' and saith,
'`Putting off the hat is but a token of respect.`' See page 234.

[.discourse-part]
_Answer._ '`Honour all men,`' that is, to have all men in esteem; all men are had in esteem,
for Christ '`hath enlightened every man that cometh into
the world,`' that they might all through this light believe,
and he that doth not is condemned.
And that will bring all men that love it to seek the honour that comes from above;
but if they hate the light, they seek the honour that is below,
that is of the first Adam in the transgression, and that is the hat.
But Christ, the light, that doth enlighten every man, etc. receives not honour of men;
and the light of Christ which every man hath, etc. will not receive honour of men.
Now he that receives the honour of men, is of the first Adam, from the light,
in the transgression.
Earthly Adam looks for honour of the earth; these are the marks of an unbeliever.
And the fifth commandment doth not speak of bowing the knee.
And for Jacob`'s bowing, and David`'s bowing to Saul,
etc. there is a time the elder must serve the younger.
And for Joseph and Abraham`'s bowing before the heathen, and the rest of bowings,
which thou speaks of, in the scriptures of the Old Testament; Christ is come,
to whom '`every knee must bow,
and tongue confess to the glory of God;`' and not the angels bowed down to,
nor worshipped.
So ye have shown whose ministers ye are that are crying up bending and bowing the knee;
is not this like kissing of Baal, and bowing the knee to Baal?
Now Christ is come, to whom every knee must bow.
And as for master, ye have thrown yourselves into that transgression,
and excluded yourselves from among the brethren; for Christ saith,
'`Be not ye of men called master, for ye have one master, even Christ,
and ye are all brethren.`'

[.discourse-part]
_Principle._ He saith,
'`Swearing is a part of God`'s worship,`' page 235. And '`Christ was far from
overthrowing the worship of God.`' And '`it was the formal part of an oath,
when the apostle Paul said, God was his witness.`' See page 238.

[.discourse-part]
_Answer._ Christ, who said God was a spirit, and would be worshipped in spirit,
and in the truth, said, '`Swear not at all,`' who was the oath of God that ended oaths;
but said, in all your communication, '`let your yea be yea, and nay, nay,
for whatsoever is more cometh of evil.`' And the apostle,
who abode in the doctrine of Christ, was so far from swearing, that he saith,
'`Above all things, my brethren, swear not at all, neither by heaven, nor by the earth,
nor by any other oath.`' Neither did any of the apostles;
though men that were in strife swore, and their oath ended the strife among them.
And they swore by the greater, that is the true oath; but Christ, in whom is the peace,
the covenant of peace, where souls come to be one, and hearts one,
who are the true burden in him, are in the oath of God, the end of all oaths.
For God, when he could not find a greater, swore by himself that did not change,
concerning his covenant with men that doth not change,
'`in which men come to have peace with God.`' And so men swear by the greater,
whose oaths end their strife and controversy.
But God, who could not find a greater, swore by himself concerning his son,
the covenant of God, which ends the strife among men, and between God and man,
and is the '`peace on earth, and good will towards men.`' Now the swearing of the angels,
the swearing of the priests, the swearing of Jacob, and Joseph, and David, and Solomon,
Christ is the end of all these, the oath of God, in whom their faith stood;
and to whom all the angels must bend and bow, to him that saith,
'`swear not at all.`' But your swearing now is not like to the Jews,
for they swore by the Lord, not by the book of the prophets`' writings;
neither did they swear by the tables in which the law was written.
Neither did the apostles nor the saints swear by the epistles, nor Christ`'s words,
after they were written and recorded.
Now this is worse than the Jews, for they were to swear by the Lord,
from whom the law came; they were to swear by the Lord of whom the prophets learned,
and not by the tables, nor by the prophets`' words.
The heathens were to swear by Moloch, and to swear by Baal, and kissed Baal;
and the children of Israel were to swear by the Lord,
not by any writings or declarations of the prophets, or Moses.
Neither do we read that the saints swore by the Epistles, or the Revelations, or Matthew,
Mark, Luke, or John, and kissed the book.
For the true christians that witnessed Christ, the end of the prophets, the end of Moses,
a greater than Solomon, him by whom the world was made before it was made,
before Abraham was, who reigns over the house of Joseph, and Jacob,
to whom the angels must bow, saith,
'`Swear not at all.`' '`This is my beloved son,`' saith God, '`hear ye him.`'

[.discourse-part]
_Principle._ He saith,
'`A believer hath both the rise and furtherance of
his faith and evidence from what is written.
And if the scripture be a dead letter,
and the word in the heart be one with the scripture,
then that in the heart is dead,`' page 246. '`Let them tell the
world how the scripture is the declaration without contradiction,
and yet the word in the heart.`' See page 247.

[.discourse-part]
_Answer._ The scripture as it lies, and is in itself, is a dead letter;
but as the word is felt in the heart that gave it forth, then it is its own words.
Now to them that are from the word within, to the dead mind, the dead letter.
And so the words themselves give not life, but as the words are raised up within,
as they were in them that gave them forth: and that is it which gives life,
and that sees the scriptures, and the fulfilling of them;
and then that knows the scriptures that cannot be broken, and in that, the word Christ,
the words end.
And that is it that gives life to all people, and saves the soul,
which the letter doth not, as it is in itself, without that which gave it forth,
and that is not dead.
And the author of a believer`'s faith is Christ, and he is the giver of it.
And if he have all that is written, and be not in the light Christ,
who is the author of his faith, he wants the foundation of God that stands sure,
Christ Jesus, that all the fathers and holy men of God rested in,
who were in the faith before any scripture was written; in him stood their faith,
the foundation of God, Israel`'s glory, the light of the Gentiles;
this is that which fulfils all scriptures, and ends the faith, the salvation.
And the ministers of the word took in hand to set forth
in order a declaration of the things wrought among them,
who had a perfect understanding from the very first,
'`of what Christ both said and did.`' And so this declaration was given forth to be read,
believed, fulfilled, and people to enjoy the thing it speaks of,
that which the apostles preached to Jews and Gentiles, the new covenant,
the one offering, the blood of Jesus Christ, him the end of the first priesthood,
that Abraham and David saw, Moses had the type of, and the prophets wrote of.
Now, they who enjoy him that these all spoke of, saw, and preached, have the end,
the comfort of the scriptures.
And here is the declaration seen and known, and here is the substance possessed,
and here are the words of God, and here is the word of God that fulfils the words,
which word was before the words, in which word the words end, and are all summed up in.

[.discourse-part]
_Principle._ '`For to say Christ and faith are not to be found in scriptures,`' he saith,
'`I hope no humble saint will pin his faith upon this,`' etc.
And '`they crying up thee and thou to a particular,`' etc.
See page 247.

[.discourse-part]
_Answer._ Christ was before the scripture was written; and Christ is life,
(not found in a dead letter,) and he is the end of the scriptures,
and the substance of them: many had the scriptures, and could not find faith in them,
nor Christ, nor life.
And Christ told the Pharisees he was the life, the scripture testified of him,
'`but they would not come to him that they might have life,`'
who is the end and substance of the scriptures,
'`by whom the world was made.`' And as for the words thee and thou,
they who are stumbling at them, show they have never learned their accidence nor Bible.
So, short of the language of the spirit,
that teacheth to speak sound words that cannot be condemned,
who are ignorant of the literal knowledge.

[.discourse-part]
_Principle._ He saith, '`The scriptures were breathed forth by the spirit of God;
but we receive the spirit another way than they did that gave forth the scriptures.
And the scriptures were given forth immediately: but thus the scriptures come not to us,
nor the understanding of them.
We have books, and canons, and printed translations in the mother tongue,`' page 248.

[.discourse-part]
_Answer._ Notwithstanding all your books, and canons,
and if ye have all the scriptures printed in all the languages of the world,
and have not the same immediate inspiration that gave them forth,
ye understand not the scriptures.
And we do believe you, that ye have not an immediate inspiration as they had,
nor receive the spirit as they did that gave forth the scriptures,
who are ravened from it.
But whoever knows the scriptures of truth, it is by the same spirit that gave them forth:
with and by this are the scriptures of truth, the excellent words,
known again to what state and condition they were spoken.

[.discourse-part]
_Principle._ He saith, '`The spirit is in the letter,
or the whole scripture,`' page 254. And '`They that
wrote forth the scriptures were imperfectly holy;
but God`'s word was holy.
To conclude, the spirit is in the letter, and given by it,
daily experience demonstrates it.
And they that own not the spirit`'s dwelling in the letter,
have lost their faith of the spirit`'s presence, and run to other gospels and doctrines;
the spirit of error is in all men`'s doctrines,
that have not the spirit in them,`' page 255.

[.discourse-part]
_Answer._ They were holy men of God that gave forth the scriptures,
as they were moved by the holy ghost; the apostle said they were holy,
and we shall believe him before we believe any of you apostate teachers,
who say they were not holy.
And the spirit that was in them that gave forth the scriptures,
was received of God the Father of spirits, and dwells in God.
And they that are from the spirit of God within, which gave forth the scriptures,
are such as follow their own spirits, and use their tongues, and get the good words,
the sheep`'s clothing, deceive the hearts of the simple,
and tell them '`the spirit is in the letter,`' which
never did any of the experienced saints say;
but did conclude the spirit dwelt in their hearts, the faith in their hearts,
the light in their hearts, the word in their hearts, the anointing within them,
God dwelt within them, Christ within them, the law in their hearts,
the witness within them, '`the ingrafted word that saved their souls,`' the gift within,
the hidden man in the heart, strength in the inward man; the holy ghost moved them,
the spirit of the Father spoke in them; this led them to speak forth scriptures.
These never said the spirit was in the letter, as all the filthy dreamers say,
who are in the sensual separation from the spirit of God, and in Cain`'s, Core`'s,
and Balaam`'s way,
'`turning the grace of God into wantonness,`' ravened from the spirit of God inwardly,
only wolves in sheep`'s clothing.
These are such as have got the good words, but deceive the hearts of the simple,
make a trade of them, tell people the spirit is in the letter.
These have ravened from the spirit of God in their own particulars,
and so they deceive people, and keep them from the spirit of God in their particulars.
But the spirit that gave forth scriptures is witnessed, by which they are known;
they cannot deceive any longer:
who are '`reprobates concerning the faith,`' who
crept into houses before the apostles`' decease,
who have kept people '`always learning,
but never able to come to the knowledge of the truth,`' '`led away
with divers lusts.`' So have kept people in spiritual Egypt,
Sodom, and Gomorrah, and have been guarded with magistrates, and powers of the earth,
all over the world.
But now is the light breaking forth and shining, that ye are all discovered.
And so they have set up other.
gospels, and lost the faith,
that tell people '`the spirit is in the letter,`' when the
spirit and the faith were in them that gave it forth,
and are to be in all them that know it again, and know God the giver of it.

[.discourse-part]
_Principle._ He saith, '`He that is born of the spirit,
is born of the holy word written,`' page 257.

[.discourse-part]
_Answer._ He that is born of the spirit, is born of that which gave forth the scriptures,
the word which was before the scriptures were given forth,
which lets him see the end of the words: so cometh to dwell in God,
of whom they learned that gave forth scriptures.

[.discourse-part]
_Principle._ He saith, '`If setting the scripture in the heart of every man,
be nothing else but telling people they have a light of conscience within them,
and stirring up that light which every man hath that cometh into the world,
they delude poor people, who never heard that light called scripture before,`' page 257.

[.discourse-part]
_Answer._ They that never heard the scripture outwardly,
being turned to the light that every man hath that cometh into the world,
with that they will see Christ, with that they will know scripture,
with that they will be led out of all delusion, and come into covenant with God:
with which they will come to worship God in the spirit, and serve him,
and that is more than conscience.

[.discourse-part]
_Principle._ He saith, '`The light which John speaks of,
which doth enlighten every man that cometh into the world, is a dim light;
and it is a piece of the mystery of iniquity, as subtle as any antichrist,
to say that the light shines in the darkness, and shineth out of darkness,
the light of Christ for salvation,`' pages 261, 262. He saith, '`Christ in you,
the light in every man, is a poor, base, beggarly scrap,`' page 264.

[.discourse-part]
_Answer._ The light which doth enlighten every man that cometh into the world,
is Christ the substance, the righteousness of God, and not beggarly;
but all the beggarly are out of the light, and it is not dim,
but all are in the dim that are out of him the light,
that with which he hath enlightened them.
And all are in the mystery of iniquity, and are antichrists,
that see not the light that doth enlighten every one that cometh into the world,
where it shines, and where it shineth out of the darkness.
These are the true ministers who are in the spirit that gave forth the scriptures,
ministers of Christ within, witnessed and seen.
And John was not antichrist, nor Paul, who said,
'`light shined in darkness;`' and who said,
'`light shined out of darkness;`' and who said,
'`This was the true light that lighteth every man that cometh into
the world.`' Now ye are all ignorant of the prophets before John,
who said, '`I will give him for a covenant, for a light unto the Gentiles,
and a new covenant to the house of Israel, and to the house of Judah;`' mark,
here was '`every man.`' And John, the greatest prophet born of a woman, saith,
'`This is the true light that lighteth every one,`' etc.
Christ Jesus, him by whom the world was made before it was made, '`in whom is life,
and the life was the light of men: and the light shined in darkness,
and the darkness comprehended it not.`'

[.discourse-part]
_Principle._ '`The law written in every man`'s heart doth not condemn all sin,
nor the branches of it, nor original sin, nor unbelief,`' page 266. He saith,
'`To say that every man in his first state is natural,
and every man in his first state is as a beast, is a contradiction.
And I everywhere deny the natural light of every man;
but I deny the highest degree of light to be here attainable.
And the saints`' light is not to be seen while we are under the
sun.`' And he saith '`he knows he is more brutish than a man,
and hath not the knowledge of the holy,`' page 272.
And the light that shineth in the scriptures,
that I profess myself to know nothing of;
'`the least degree of it is above the highest degree of the light that
every one that cometh into the world is enlightened withal,`' page 273.

[.discourse-part]
_Answer._ The light which every one that cometh into the world is enlightened withal,
was before degrees, and ends degrees, and is not natural;
for it was before the natural was made or created;
and this bears not witness against the natural, the sun, moon, and stars,
but owns them in their places.
And the light which every one that cometh into the world is enlightened with,
which comes from Christ the son, they not believing in it, it is their condemnation.
And that which doth make manifest and reprove sin, is light; yea, all sin, branches,
and roots, and original, and unbelief, that which doth make it manifest is light;
and where this light is that makes all this manifest, there is the law in the heart,
and new covenant written,
the law and the spirit of life that makes free from the law of sin and death.
And believing and receiving the light which every man is enlightened with,
they come into covenant with God, they come to know the law of God in their hearts;
for that is the law of God in their hearts,
'`the light which doth enlighten every man,`' etc.
And every man is in his first state, in the transgression; many are worse than beasts,
and brutish; and '`what they know they know naturally, as brute beasts.`' And thou,
and all of you, who are ravened from the spirit of God inwardly, what ye have known,
it hath been naturally, as brute beasts;
for ye are gone from the spirit that should give you to know and understand,
and so that is no contradiction.
And we do believe thee that thou art brutish,
who lookest for the light in the letter of scripture,
and sayst the light of scripture is higher in the least degree,
than the '`light which doth enlighten every man that cometh into the world.`'
Alack for thee! the light which doth enlighten every man,
etc. was before scripture was given forth.
And the saints that receive the light that doth enlighten every one,
etc. receive Christ the perfect light, and receive God, and Christ the substance,
the end of degrees.
And thou shalt never see the saints`' light, while thou art looking at the letter,
and art from the life which was in them that gave it forth;
and the light shined in the hearts of them that gave forth the scriptures.

[.discourse-part]
_Principle._ He saith, '`The scripture light, that is a standing rule for our faith,
and there is present light in it to guide men to salvation,
and so are not immediate revelations and teachings.
And the knowledge of Christ and eternal life is given forth in the letter,`' page 283.

[.discourse-part]
_Answer._ They that had scriptures knew not salvation, and they knew not the rule,
being erred from the spirit of God.
And none know salvation,
but by the immediate teaching and revelation of Christ Jesus the son of God,
the salvation.
And if men have all the scriptures given forth from God,
they themselves are not able to make men wise unto salvation without faith,
which Christ is the author of, who is the substance of what the scripture speaks of,
and so they are not able of themselves '`to guide
men to salvation.`' Neither are they a rule of faith,
but Christ is the author of faith, and the spirit the rule that gave them forth;
and all that have them, and are not in the immediate, know them not, neither the gospel.
And none know eternal life, nor Christ (who is the author of life and faith,
who was before scripture was) by the scriptures,
but as they come into the life that they were in that gave them forth.
And there is the life found, Christ found, Christ seen,
him by whom the world was made before it was made;
for the life was in them that gave forth the scriptures,
by which they knew God and eternal life, and Christ the saviour, Abraham, the prophets,
and Moses; so the life must be in all now, before they know scriptures, or Christ,
or God.

[.discourse-part]
_Principle._ He saith, '`If the letter declares of Christ`'s fulfilling,
then we should need to know no more of Christ than what for substance is in the scriptures;
then there is no need of immediate teachings,`' page 284. He saith,
'`new apostles and doctrine discovered, of a righteousness within them,
that is their justification.
And this is as the ringleaders of the Jews among the Galatians,`'
page 286. And '`the salvation which is to be wrought out with fear
and trembling is not the same as made Moses and David,
Habakkuk and Paul tremble,`' page 287.

[.discourse-part]
_Answer._ The power of God is one, which threw down Paul, shook Habakkuk, and Moses, and David,
whereby these all came to know Christ; which power, who cometh into it,
and into the infiniteness of it, which raiseth up the seed, which is Christ,
whereby the salvation is known, and wrought out with fear and trembling.
And when ye all come to know this power that works out the salvation with fear and trembling,
your reproaches will be laid aside,
for reproaching of such whose salvation is wrought out with fear and trembling.
And righteousness within, and sanctification within,
is a new doctrine to you that are inwardly ravened
from the spirit of God since the days of the apostles,
and so from the spirit of faith, from the hearing of faith;
as they that drew the people to the circumcision without,
went from the hearing of faith within, by which they should be justified.
So they that are come to the hearing of faith,
are come to the justification and sanctification within,
and look not to the circumcision and baptism without.
So this is an old doctrine, and not new but to you apostates.
And though the scriptures declare of Christ`'s fulness,
if people have all the scriptures, that speak and declare of his fulness,
(and you say you need know no more of Christ than what for substance is in the scriptures,
and so have no need of immediate teachings,
we believe you,) none know the fulness of Christ
but they who come into the immediate teachings.
Your mouths may be full of scripture,
and you may use your tongues about the saints`' words, and run up and down,
and the Lord never sent you, saying, '`thus saith the Lord, in chap.
and verse, and it is sufficient that the scripture speaks of his fulness;`' yet I say,
neither you, nor any upon the earth, can ever know his fulness,
but as ye come to the light wherewith Christ hath enlightened you,
in every one of your own particulars, though ye may have all the scriptures.
For they that knew the fulness of Christ, and they that gave forth the scriptures,
had the spirit of God in them: so must every one that knows it and them again.

[.discourse-part]
_Principle._ He saith, '`If the scriptures be a rule for thee and thou,
then it is a rule for respect to superiors:
and keeping on the hat shows the pride of the heart, and a lying spirit.`' He saith,
'`they have not a growth of perfection in this life,
but a pressing on,`' page 290. And he saith, '`the prophets took texts,
and raised motives.`' And he saith, '`he that believes not our points from scripture,
shall be damned; that he must tell him from Christ,`' page 299.

[.discourse-part]
_Answer._ They who are standing up against thee and thou, and the hat,
show the pride of their hearts, and are out of the humility,
looking for an earthly honour; but before the honour is the humility.
Nay, the scripture is not a rule for respecting persons,
neither is the faith of our Lord Jesus Christ;
they that respect persons are out of the faith,
and are convinced by the law to be transgressors, and committers of sin,
and so out of the law, and faith.
And David saw the end of all that perfection, so he was past the growth of it,
when he saw its end.
And the scriptures, and Christ, you know not,
who are not come into the immediate teachings, and have no need of it; who say,
the scripture it is sufficient that declares of Christ.
And the prophets did not take texts, and raise motives, and uses, and reasons,
and lay in them half a year together, and sell them for money,
as ye do now since the days of the apostles in the apostacy.
But now I am come to reckon with you, and you shall have a portion,
a reward according to your works: and I will slay you with the sword,
the words of my mouth, saith the Lamb.
And your points, and reasons, and imaginations which ye fetch out of scripture,
are but to lead people under condemnation, and keep them from the immediate teaching,
and the light which doth enlighten every man that cometh into the world.
And James Parnell`'s blood, who died in prison, that righteous man,
his blood lies upon you, and it shall lie upon your heads sparkling,
and from under it ye shall never come, but ye shall own it.
And the spirit of God levels down all the proud and lofty hearts of men,
by which people are brought into unity with God, and one with another.

And the first day in the week which ye call the sabbath,
ye never read it in the scriptures as a strict command among the apostles.

[.discourse-part]
_Principle._ '`And the magistrate is not to level the laws
with the light in every man`'s conscience.`' Again,
'`If the magistrate be in the light, and discern into the mind of Christ,
and understand his law; is he to compel all the nation, and commonwealth,
to come to the practice of his light?`' page 308.

[.discourse-part]
_Answer._ The magistrate of Christ, the help government for him,
is in the light and power of Christ, and he is to subject all under the power of Christ,
into his light, else he is not a faithful magistrate.
And his laws here are agreeable and answerable to that of God in every man;
when men act contrary to it, they do evil: so he is a terror to the evil doers,
discerns the precious and just from the vile, and this is a praise to them that do well.

[.discourse-part]
_Principle._ He saith, '`The scriptures are the more sure word of prophecy,
that shines in the dark heart until enlightened by the law.
And every man`'s light, etc. is the glimmerings of the law, and not of the gospel light:
and it is the voice of the spirit of unbelief that saith,
the spirit and the power are not in the declaration.`' See his appendix.

[.discourse-part]
_Answer._ The spirit and power were in them that gave forth the declaration,
but many have the declaration, and want the spirit, and want the power,
as the Pharisees did; as all you apostates, inwardly ravened from the spirit of God,
have had the declaration, but not found the power in it, nor spirit in it,
and so are in the unbelief, and all on heaps about it.
For if ye had found the power and the spirit in it, ye had been all one,
and quiet before now about religion; yea, whole Christendom would have been in power,
and in the spirit, and in the bond of peace, and in fellowship one with another,
and the scriptures, and the spirit, and God.
And the light '`which doth enlighten every man that cometh into the world,`'
every man being in the light which hath enlightened him,
he shall feel the word of prophecy; he shall feel the light shining in his heart;
he shall feel the day-star arise there in his heart;
he shall see that no prophecy of the scriptures came by the will of man,
but holy men of God spoke them forth.
He shall see that many may have the scriptures,
yet quench the spirit and despise prophesying;
he shall see the scripture is but the letter declared forth from the spirit of prophecy,
by the prophets, and the spirit of God in the son, and in the rest of the apostles.
And the '`light which doth enlighten every one,`' etc. is the end of the law,
and of all glimmering lights, and is the light of the gospel.
And none know the gospel, the power of God, Christ Jesus,
but with the light that cometh from him.
Here every man comes into his particular comfort.
And that is the voice of the unbeliever, that, like the Pharisees,
thinks to have life in the letter, and will not come to Christ the life,
the substance of scriptures, but stops his ear to the light of God in him.

[.discourse-part]
_Principle._ He saith, '`Let all know,
that the work within is not the ground and purchase of true peace.
And that God is more pleased with that which Christ works without for them,
than that which he worketh within them.`' And '`those that Peter speaks of,
that had escaped the pollutions of the world through the knowledge of Christ, yea, clean,
and yet are in the natural state, first and last.`' See appendix.

[.discourse-part]
_Answer._ They that have escaped the pollutions of the world
through the knowledge of Jesus Christ,
and are clean, are out of the natural state,
for they have escaped out of that state which they were in first.
And such as witness their sanctification and justification wrought within them,
witness in this they please God, by the faith in the blood of the son of God.
Now they feel not the comfort, nor the benefit, but by the faith of Christ Jesus,
the one offering, in which God is pleased, which is acceptable,
which is Christ`'s offering; his sacrifice, his flesh, his blood, his life,
his mind must be manifest and received within, before they come to justification,
sanctification, and redemption, and the serving of God in the new life.
And herein is God glorified,
to '`believe in the only begotten son of God;`' and here they honour the son in believing
in him '`whom the Father hath sent.`' And so they that feel not Christ in them,
are reprobates.

[.small-break]
'''

And as for all the rest of thy lies and slanders, and strife and confusions,
who would set one against another; all cool, quiet,
and sober spirits will see thy confusion, and so thy words shall be thy own burden,
and thy lies turn upon thy own self.
And no man shall establish Zion, nor lay a stone there, as he is in himself;
but the elect make up Zion, and the living stones,
where the elect and precious stone is in the midst, (which is Christ,) laid in Zion.
And all thy Babylonish ways, actings, and doings, and all the rest of thy brethren,
and who are begotten with the same spirit of the great whore,
that inwardly ravened from the spirit of God,
who long have had the sheep`'s clothing upon your backs,
who all come from one Popish stock,
are comprehended now by the spirit of God which ye have all ravened from inwardly;
with it are ye all fathomed.
And the whore hath been arrayed with the sheep`'s clothing,
and hath had power over kindreds, tongues, and peoples, and nations, and multitudes,
and brought nations into waters, and peoples, tongues, and multitudes like waters;
which have drunk the blood of the prophets, and the saints, and the martyrs.
And so thou art flattering the authorities of the earth, and crouching under them,
out of whose mouth goes the unclean spirits.
But that is stirred and stirring, and rising in people, which ye are all ravened from,
and gone from, with which ye are all comprehended.

And the judgment of the great whore is come, and her garments shall be plucked off,
and that which ye all have ravened from, high and low, shall answer the judgment,
and it is set atop of you all.
For such as ravened from the spirit of God inwardly, got the sheep`'s clothing,
but turned against the saints, and the woman fled into the wilderness;
but now the Lamb and the saints shall get the victory.
Though now the beast, and false prophets, and mother of harlots; and the devil,
and the kings of the earth make war against him.
He that '`was dead is alive,
and lives forevermore.`' The '`Lamb slain from the
foundation of the world,`' who rides on conquering,
and to conquer, who slays and kills with the sword, which is the words of his mouth.
Now woe to the dragon, and false prophets, beast, and mother of harlots,
and them that worship the beast, the unclean spirits!
Woes, vials, thunders, plagues, and earthquakes are come, and coming upon you!
And he is manifest and come, that treads the wine press alone without the city;
who is the Wonderful, Counsellor, the Prince of peace,
whose name is called '`the word of God.`' With him
are the saints singing victory over the beast,
and over the false prophets, great whore, mother of harlots, Babylon, and antichrists.
'`Babylon is fallen!`' the Lamb and the saints shall have the victory.
In the body of witchcraft thou art found, as all that read thy book,
that are in the spirit of discerning, may see; whose body is redeemed,
and reigns over thine in the glory and victory.
