[#ch-43.style-blurb, short="The Great Mystery of Godliness, and Ungodliness"]
== Ralph Farmer`'s book, called [.book-title]#The Great Mystery of Godliness, and Ungodliness.# In which are these principles following.

[.discourse-part]
P+++.+++ He saith, '`The soul is of an immortal and spiritual nature.
And God hath made man to serve him in an outward and visible way of worship.`'

[.discourse-part]
A+++.+++ Christ saith, '`God is a spirit, and they that worship him,
must worship him in spirit, and in truth;`' and is the spirit without, and visible?
In the spirit, that makes all that is contrary to bend, is God worshipped.
And others that say they are teachers,
(as ye may see in this book,) say '`that the soul is human,`' yea, the soul of Christ,
and thou sayst, the soul of man is immortal, and a spiritual nature.
Now the soul that gives the sense and feeling of all things, is spiritual and immortal,
as it comes out from God, which is in God`'s hand, whom Christ is the bishop of;
the noble principle that guides it, is the light and life.

[.discourse-part]
P+++.+++ He saith, '`The eternal word enlighteneth all men with the common light of nature.`'

[.discourse-part]
A+++.+++ The light which every man that cometh into the world is enlightened with,
is not natural.
For the light was before any thing was made, and all things that were made,
were made by it; which lighteth every man that cometh into the world,
though he be in the first Adam, in the sin and transgression:
which light to him doth make it manifest, which cometh from Christ, the second Adam,
the way to the Father, who was glorified with the Father before the world began:
to restore that which the first lost; and this is the obedient son,
and the other the disobedient one, which brings the death upon him,
and all his posterity and all his house.
So the sons of Adam in the transgression may say, and do say,
that the light which Christ (the second Adam, the redeemer, and restorer,
the salvation to the ends of the earth,) doth enlighten
every one that cometh into the world with,
is natural.
And so that is to deceive people, to keep them from the light,
with which they might all see their salvation, and come to receive Christ,
by which they might have power to become the sons of God.

[.discourse-part]
P+++.+++ '`The measure and degree it must be without thee.
And it is a cheating to tell people of God within, and Christ within, and a word within,
and they are without,`' which he calls '`a mystery of mere confusion,
and emptiness,`' page 27.

[.discourse-part]
A+++.+++ The degrees and measures were in the saints who spoke forth scriptures,
and knew the scriptures; but those that have the scriptures,
and are from their degree and measure in themselves, they are without them.
And Jesus Christ is within except ye be reprobates.
And where Jesus Christ is within, the word is there, and God is there.
And this is the great mystery of godliness.
And where the power of God is set, the cross of Christ is felt:
for the cross is the power of God.
And if it be not the same Christ that did ascend, it is antichrist, it is against him,
and false: but now many hundreds and thousands do witness Christ within,
him the apostles preached; who have their joy and reward;
who do possess that which they long looked for.
And all that stand against Christ within, and God within, and the word within,
and the cross within, the power of God, are reprobates, and in the mystery of confusion.

[.discourse-part]
P+++.+++ '`The apostle bid Timothy to preach the word in season, and out of season,
etc. not immediate revelation,`' page 32. And '`the time will come,
they will not endure sound doctrine,
but after their own lusts they will heap up to themselves teachers, having itching ears,
turning to fables, immediate revelations,`' page 35.

[.discourse-part]
A+++.+++ None can preach the word of truth,
but they who preach it immediately and by the immediate spirit,
and know immediate revelations.
And all that are in the faith, as Timothy was, are in the immediate revelations,
the gift of God.
But the apostle saw that such as would not endure sound doctrine,
but would get up teachers after their own lusts, would be such as were covetous,
and minded earthly things, and evil beasts, that serve not the Lord Jesus Christ,
but their own bellies.
Such the apostle bid Timothy and Titus examine before they ministered, prove them,
and lay hands on no man suddenly, and keep himself clear,
not preferring one before another.
And such as went into their own lusts, got up heaps of teachers,
lost immediate revelation, and the immediate word of God,
and erred from the faith that purifies the heart and gives victory;
in which people have unity.
And such now as are got into the lusts, that cannot endure sound doctrine,
who have lost revelation and speaking the word immediately, have ruled and reigned:
of whose generation thou, Farmer, art.
And people have heaped to themselves teachers after their own lusts;
and that is the cause of all the strife and wars amongst them.
And by denying immediate revelation, and the preaching the word of God immediately,
you teachers have declared yourselves openly to the nation,
to be the false prophets that never heard the voice of God, nor Christ`'s voice;
nor the voice of the spirit, nor had the ministry of the spirit,
which all speak immediately.
And the apostle saw them come up before his decease.
Therefore he chargeth Timothy to preach the word in season, and out of season,
which word is immediate.
And so since the days of the apostles, and of Timothy and Titus, ye have reigned,
and transformed yourselves as apostles, as the ministers of Christ, and gotten the form,
the sheep`'s clothing, the outside, but no immediate revelation:
we do really believe you it is so.
So you are all ministers of the letter in your own lusts,
for the word of God is immediate.
And ye are ignorant of the grace of God which is brought at the revelation of Jesus;
and ignorant of the son of God who reveals the Father; and ignorant of the spirit of God,
which reveals the deep things of God to the ministers of the spirit.
But revelation is ceased, say you, and the rest of your generation do discover it.
And thou sayst they went after the fables, itching ears, '`immediate revelation.`' Nay,
they that went from the immediate revelation and turned unto fables, had itching ears,
as all whole Christendom may witness.
How are the itching ears abroad, their ears are without,
and cannot endure sound doctrine;
and all inwardly ravened from the light which doth
enlighten every man that cometh into the world,
with which every man might see the author of his faith, in which is the unity.
And how have you broken into sects, and heaps, and into fables,
and heaps of teachers after your own lusts, and are burning after them,
and have broken wedlock with Christ: and ready to burn,
and prison one another about churches and ministers`' maintenance,
as whole Christendom discovers.
But I say it is better to marry than to burn.

[.discourse-part]
P+++.+++ He saith, '`that this God who is the creator,
is eternally distinct from all creatures,`' page 53.
'`That Christ being God only in one man`'s person,
remains a distinct person from all creatures and angels,`' page 55.

[.discourse-part]
A+++.+++ This is contrary to scripture.
The saints`' bodies are the temples of God, and he will dwell in them, and walk in them,
and he will be their God, and they shall be his people;
and this is to them that witness the new covenant,
and '`Christ in you the hope of glory;`' and he is within you except ye be reprobates.
And they that eat not his flesh, and drink not his blood, have no life in them:
and they that eat his flesh, have his flesh in them.
And the saints are not distinct from him, for they sit with him in heavenly places,
and he is in them, and they in him.
And '`Christ in you the mystery,`' '`the hope of glory,`' and,
'`he is the head of the church,`' and so not distinct.

[.discourse-part]
P+++.+++ He saith,
'`God is distinct in his being and blessedness from all creatures;`' and '`that
God who is the creator is eternally distinct from all creatures,`' page 62.

[.discourse-part]
A+++.+++ God is a spirit, and he dwells in his saints,
and the heaven of heavens cannot contain him; in him we live, and move,
and have our being, who is '`in all, and through all, and over all,
God blessed forever.`' And the spirit of the Father speaks in the saints,
and he makes his abode with them.
And the saints have fellowship with the Father, and the son, so not distinct +++[+++separate;]
so these keep people from unity with God, and out of his knowledge,
which knowledge of God shall come to cover the earth, as the waters cover the sea.
And while any are separated from the Lord it is their misery; and if distinct from him,
they are from the spirit of God in their own particulars, and are not saints;
but such as come to walk in the spirit, have fellowship with him,
and live in his presence, and see his face, and behold his glory,
and stand in his counsel, and hear instruction, and they are one; '`He that sanctifieth,
and they that are sanctified,
are all of one.`' And so God was in Christ reconciling the world unto himself,
though sin and iniquity had separated; who breaks down iniquity`'s bonds,
and brings light, life, and immortality to the light,
through the power which is the gospel, whereby fellowship and unity with God come,
and his blessing and blessedness are felt; and so not distinct,
for they that have unity with God, have unity with his blessing,
and they that have fellowship with God, know his blessedness.

[.discourse-part]
P+++.+++ He saith,
'`If any man that cometh into the world have a sufficient
light within him to lead him to salvation,
then there is no absolute need of a saviour,
and this is to offer violence to Christ,`' pages 73, 74.

[.discourse-part]
A+++.+++ Every man has a light from Christ the saviour of the soul,
him by whom the world was made before it was made;
and none see the saviour but with the light which comes from him.
And none see the offering, and the blood of the offering,
but with the light which cometh from him, and the blood of the second Adam,
the Lord from heaven.
And all that deny the light that doth enlighten every man that cometh into the world,
know not Christ nor salvation.
But being from the light, and out of the light which Christ hath enlightened them withal,
they are out of the truth, as the devil is.
And so he can confess Christ without as they do, not within: none see salvation,
nor the saviour Christ Jesus, but with the light which he hath enlightened them withal,
and that is within.

[.discourse-part]
P+++.+++ '`That the holy scriptures are the rule of knowing God.`'

[.discourse-part]
A+++.+++ The Pharisees had the scriptures, but knew not God, knew not Christ,
nor do any but who are in the life that they were in that gave forth scriptures,
with which they learned of God the Father of life, and stood in his counsel.

[.discourse-part]
P+++.+++ He saith, '`Christian,
wouldst thou have another righteousness than that of Christ wrought in thee?
I know thou wouldst, and must have, if ever thou be saved;
thou must have the righteousness of Christ wrought within thee for thy sanctification,
but rely upon another righteousness for thy justification,
the righteousness of Christ without thee.`' See page 70.
And it is a blasphemous opinion and filthy puddle,
to say, the righteousness of Christ within.
And '`I had rather to be a Papist than a Quaker.`'

[.discourse-part]
A+++.+++ The righteousness within and sanctification within
have been lost since the days of the apostles,
in the apostacy, amongst you and the Papists;
and they that witness a righteousness within, sanctification within,
are not in the blasphemous opinion, raking in a puddle.
And I know, thou hadst rather turn to the Papists than to the Quakers:
for they were your root which ye came from (the Papists) who first erred from the faith,
and so lost the righteousness within, and justification and sanctification.
And I say, none come to witness salvation, and to be saved,
but who witness Christ within, their sanctification, and justification, and redemption,
and the others are reprobates.
And all upon the earth that can talk of a righteousness without them,
and sanctification and justification without them, and a Christ without them,
and not within them, they are reprobates; for Christ is the righteousness of God,
and the sanctification, and the justification of man from the law and its works,
who stands between God and man.
So he is the redemption, who redeems man out of the fall, which he fell into:
and he doth sanctify him, and he doth justify him; and this is all found within:
and this not being found within, he is reprobate.
And so none are saved but who witness this within.
They have the letter, (the wolves,) the sheep`'s clothing,
the raveners inwardly from the spirit of God, and those are they that deny it within.

[.discourse-part]
P+++.+++ He saith,
'`The spirit speaketh expressly that in the latter
times some shall depart from the faith,
giving heed to seducing spirits, and doctrines of devils, speaking lies in hypocrisy,
having their consciences seared as with a hot iron, forbidding to marry,
and abstaining from divers meats.`' See page 73.

[.discourse-part]
A+++.+++ Before the apostle`'s decease he saw these things come up: and the spirit speaks this;
mark! it '`speaks expressly.`' Now since the apostle`'s
decease the things have been fulfilled;
the faith hath been departed from, the unity among all Christians hath been lost,
in all Christendom; on heaps have they all run,
destroying one another about the scriptures, churches, ministry, yea, for maintenance;
from the spirit ye have departed in speaking, so out of the unity of it,
which is the bond of peace, which would have kept peace in all Christendom;
it would have kept all the professors of Christ in peace, and in it is the unity.
From that ye have ravened, you and the Papists, and all sects upon the earth.
So some are forbidding meats, and forbidding to marry,
whose consciences are seared as with a hot iron: the devil`'s doctrine:
speaking lies in hypocrisy, and giving heed to seducing spirits.
You are the spirits that are inwardly ravened from the spirit of God,
that deny immediate revelation, and hearing the voice of God immediately;
these are the seducing spirits, and keep all people in the burning and heating lusts,
from the marriage of the Lamb; all the seducing spirits do this that deny revelation,
immediate inspiration, and hearing the voice of God immediately from heaven now as ever.
And therefore their fruits declare they are burning one against another,
destroying one another about their religion and ministry,
their consciences seared as with a hot iron, tenderness lost and gone, destroying people,
and casting into prison for their bellies, for maintenance, for tithes.
So ye have got up your church, which was a mass-house, and tithes,
and sprinkling infants, who have had the time of compelling others to worship.
But the day is breaking, the light is springing, life is rising, and glory is appearing,
your torment is coming, and you can be no longer hid.

[.discourse-part]
P+++.+++ He saith, '`Beware of false prophets; there shall be false prophets among the people,
who shall bring in damnable heresies, denying the Lord that bought them,
bringing upon themselves swift destruction, and many shall follow their pernicious ways,
by reason of whom the way of truth shall be evil spoken of.
As Jannes and Jambres withstood Moses, so do these resist the truth:
but they shall proceed no further; for their folly shall be made manifest to all men,
as theirs was.`'

[.discourse-part]
A+++.+++ Christ said to his apostles that antichrist should come,
and false prophets should arise,
and before their decease they saw they were come already, as Peter and John declare,
whereby they knew it was the last time.
And they went forth from them,
(the apostles,) and in the Revelations it is said the whole world went after them,
that the nations came to be like waters, and the peoples waters,
and their tongues waters, and multitudes waters; so many followed their pernicious ways,
by whom the way of truth hath been evil spoken of, by you and them both.
And they brought up the damnable heresy: and are as Jannes and Jambres,
being men of corrupt minds, and reprobates concerning the faith.
But they shall proceed no further, for now is their folly made manifest,
and shall be made manifest to all men.
Doth not the very heathens cry out against Christendom, of the hardness of their hearts,
and of their unrighteous dealings and actions?
And you that are called christians have caused the way of truth to be evil spoken of.
Is not the damnable heresy among you?
Are not you run into all heathenish ways, who have set up temples, and tithes,
and priests, and schools, and colleges, and never heard the voice of God, as ye confess,
as may be seen in this book?
Is not all this trumpery and trash, and these fables come up among the Papists and you,
since the days of the apostles?
And do not you deny the light that doth enlighten every man that cometh into the world?
the grace of God which brings salvation, which hath appeared unto all men,
to bring every man to a teacher?
And doth any one know the Lord that bought him,
but who owns the light that doth enlighten every man that cometh into the world?
Do not all deny the Lord that bought them that deny the light?
Do any see the Lord, and his blood that bought them, and purchased them,
but with the light that cometh from him?
And are not you all as Jannes and Jambres that withstood
Moses to have kept the people in Egypt?
Are not you all denying the light that doth enlighten
every one that cometh into the world?
And were not all they that inwardly ravened, who got the sheep`'s clothing,
who Christ said should come, and the apostles saw were come, who went forth from them,
and whom the whole world went after; were not all these in the witchcraft, sorcery,
enchantment, necromancy?
Are not they wizards, familiar spirits,
and witches that deny the light that doth enlighten every one that cometh into the world?
Have not Babylon, the mother of harlots, beast, false prophet, unclean spirits, dragon,
antichrists, and all deceivers been up since the days of the apostles?
And hath not this been the mystery of iniquity,
which hath ruled since the days of the apostles, that cries,
'`prophecy is ceased,`' and slays the prophets,
and makes war against them that keep the commands of God,
and calls the scriptures '`the law and the testimony,`'
and makes war against them that have the law in their hearts,
and the spirit of prophecy?
And hast not thou manifested thyself to be of this number,
and of the stock of the great whore, that hath drunk the blood of the saints,
and martyrs, and prophets?

[.discourse-part]
P+++.+++ Art not thou crying to magistrates, '`Help;
stop the mouths of blasphemers?`' in page 23. And stirring up the zeal of the magistrates,
and showing them the zeal of the Jews`' magistrates;
'`how they did tear their clothes off at blasphemers,`' in thy 31st page; and sayst,
'`thou could rejoice that they would breathe such
an air throughout all the English quarters,
and wouldst not that the Quakers should have countenance from the magistrates.`'

[.discourse-part]
A+++.+++ Now thou hast made thyself manifest, that thou hast not the spiritual weapons;
and thou mayst well deny immediate revelations.
Was it not in all ages such as pretended to be ministers,
and had not the life that gave forth scriptures, that called to the magistrates,
to stop the mouths of blasphemers?
Was not the mouth of the priests against Christ to the rulers at the council?
And against the apostles, and against the prophets?
and it is your mouth now to your magistrates in the apostacy since the days of the apostles.
But do you think that the magistrates will let you get atop of their backs,
and gallop upon them, to be their executioners?
If ye be ministers that have the spirit of God, stop the mouths of the gainsayers,
for never did the apostles nor the church wrestle against flesh and blood;
but they struck at the power that captivated the creatures,
to the intent that the creatures might come into the liberty of the sons of God.
But thy fruits have stunk about thee, and your fruits.
How barbarously have the saints and true Christians in the spirit, been used among you!
And so they that make war against the saints,
are such as have inwardly ravened from the spirit, and so got the sheep`'s clothing,
and turned against them that had the spirit of God:
ravened from the spirit of God inwardly, lost the spiritual weapons,
and had only the sheep`'s clothing,
and that would not carry them out in the time of need,
and so were fain to fly to magistrates, to carnal weapons.
And so by this means, in all ages,
the righteous have been slain by them that had the scriptures,
but were from the spirit that gave them forth;
and all the saints upon the earth have been slain by them
that have been from that of God in their own particulars;
which now is awakened, by which men come to be turned unto God.
And so you now,
that deny the light that doth enlighten every one that cometh into the world,
that preach, men should have sin while they be upon earth, and the body of it,
and imperfection, are such as have led people captive all their lifetime,
with the form of godliness without the power; and have kept people in spiritual Egypt,
Sodom, and Gomorrah, in filthiness and darkness,
where Christ was crucified by them whose ears were stopped to that of God in them,
and that was spiritual Egypt.
And so, all you that are inwardly ravened from the spirit of God in your own particulars,
that have a form of godliness, but deny the power,
that are ravened inwardly from that of God;
ye are likely to be reprobated concerning the faith;
ye are not likely to lead people to the knowledge of the truth,
but to keep them in the divers lusts, laden with their sins, and '`always learning,
never able to come to the knowledge of truth.`' There are all the witchcraft,
and sorcery, and enchantments, and familiar spirits;
among such as deny the light which doth enlighten every one that cometh into the world.

[.small-break]
'''

And as for thy lies, and all thy slanders, and revilings, they will be thy own clothing,
and wear thy own garments thou must;
and they will cover thee in darkness in the day of thy judgment,
when thy works are tried with fire; the witness in thy conscience shall answer,
I am a friend to thy soul.
And thy shame, and folly, and wickedness thou hast published to the nation.
All sober people see thy folly;
and thy silence had been better to have preached thee a sober man.
But novices and fools must utter their folly.
And the truth is gone over you,
and thou shalt feel it one day when thou and thy works are tried with the fire.
And eternally shalt thou witness, they are judged and condemned.
