[.style-blurb, short="The Duty and Danger of Swearing, Opened"]
== Edward Boules, who calls himself a teacher of the gospel at York, in his book he calls, [.book-title]#The Duty and Danger of Swearing, Opened, (as he saith) in a Sermon Preached at York, the Day of Swearing the Lord Mayor.#

[.heading-continuation-blurb]
This is the title of his book, which he directs to Stephen Watson, lord mayor,
the aldermen, and common council of that city; whose work throughout his book,
that he calls a sermon, is to teach them to break the commands of Christ.

[.discourse-part]
_Principle._ First, he says,
'`Christ brought down the righteousness of the scribes and
Pharisees,`' and '`the Pharisees wrested the scriptures,
or made the scriptures to bend to their own righteousness.`'

[.discourse-part]
_Answer._ This is your own condition, and the Papists`',
who cannot own the scriptures as they speak;
but you will make the scriptures bend to your own wills,
and wrest them as the Pharisees did, and as you and the Papists do Christ`'s words,
who says, '`swear not at all,`' and you say, '`swear.`' How now,
Edward Boules! who makes the scriptures bend now?
Thou teachest men should swear, and Christ said, ye shall not swear at all,
and so art an antichrist, and against the doctrine of Christ,
and teachest thy own tradition for doctrine,
and makest the commandment of Christ of none effect.
He that is against the doctrine of Christ, is an antichrist, and so the Papists,
and Protestants, and Pharisees all are found swearers, out of Christ`'s doctrine,
who says, '`swear not at all;`' and yet in your pride you will make a trade of his words,
and a talking of his words to get money by.

[.discourse-part]
_Principle._ Thou sayst, '`Christ came not to destroy the law: and it hath deceived some to say,
"`Swear not at all.`"
The scripture must not be taken in general terms; for Paul said,
he became all things to all men: and Christ our saviour, his intent is this,
that we should not swear as we were wont to do, "`not at all`" must be interpreted:
so that you see it is the scope and circumstance of this place,
that this "`swear not at all`" be interpreted, vain and unnecessary customs,
and abuse of swearing among the Jews: and it is not unlawful to swear,
but to all men not only a liberty, but in just cases a duty, and part of divine worship,
not ceremonial or mutable, there is no shadow or type in it.
An oath is for confirmation, and the end of strife,
it gives the last peal to all differences, and gives a great honour to God,
and is the proper end of worship, and consequently a great honour.`'

[.discourse-part]
_Answer._ They are deceived that break Christ`'s commands; for when he says,
'`swear not at all,`' he says in all your communication '`let your yea be yea,
and your nay, nay,
for whatsoever is more is evil.`' So he layeth down
no other doctrine that men should practise,
than '`not to swear at all,`' but '`yea, yea, and nay, nay;`' they that go any further,
go into the evil, '`whatsoever is more is evil.`' So mind these three things;
and though the apostle became all things to all men, yet not without the law of Christ,
(mark! the law of Christ,) which was,
'`swear not at all.`' So still that is agreeable to Christ`'s words;
the scripture is to be taken as general, and Christ said,
'`It hath been said to them of old time,
thou shalt perform the oath of the Lord.`' Christ said so that comprehended time,
that was the end of that old time in which had been the swearing:
'`But I say unto you now,
swear not at all;`' and so it was not the frivolous
oaths that were among the Jews that swore,
but it was true oaths that Christ brought them off from,
the oath that was to be performed to the Lord, which Christ the oath of God ended,
who comprehends time, and told them the danger,
if they went any farther than yea and nay.
And so your interpreting the scripture, who are the private interpreters,
is but to wrest them to your own earthly wills;
and that which opposeth the commands and doctrine of Christ, brings not honour to God,
is not a part of his worship, nor is divine, but in that which is out of truth,
(for none worship God but who are in Christ, who says,
'`swear not at all,`' who is the end of the law and the prophets,
and oaths,) and is but one of your dark consequences.
And so it is not men`'s duty in any case to swear;
for the duty of man is to keep the commands of Christ,
and there are none that are just that will swear, who obey the commands of Christ;
but such swear who are unjust, and who are out of that which gives the last peal,
and ends all differences, which ends all oaths, and all strife, and all controversy,
which is Christ Jesus the covenant of God.
For strifes, controversies, and differences are without the covenant of light and life,
Christ Jesus, the oath of God; and so thou art not a minister of Christ,
that brings people back to the law, and tells them it is lawful to swear.
Here the Papists and thee are one, both opposing the commands of Christ,
who would make people believe, they were the frivolous oaths among the Jews,
that Christ brought them off from, and not the true oaths,
and say the oath was not a shadow.
I say, yes, it made peace, and ended the strife amongst men;
the oath of God that was sworn by the Lord; but Christ the oath of God ends the strife,
and ends those oaths that men were to swear by the Lord.
So it was typical and ceremonial, and was to change, and was mutable;
for Christ that comprehends time, says,
'`in the old time the oath must be performed to the Lord; but I say unto you now,
swear not at all.`' So that was to be changed, and it did type forth something.
There you may see the substance of it, Christ the oath of God, in which men have peace,
who ends the strife between men and God, who makes all things new:
and so they that bring men to the swearing, bring men into the evil;
and they that bring men to the law and prophets that speak of swearing,
bring men from Christ, who is the end of the law and prophets, into the old time.

[.discourse-part]
_Principle._ '`The ground and occasion of oaths yet remain,
and so a usefulness of oaths for the ending of controversies,
which must he established by oaths for the end of human societies.
The apostates take for granted that the christian religion did forbid all oaths;
it is false and ridiculous;
for the prophet said "`every tongue shall swear,`" and "`thou shalt swear by my name.`"
Deut.
And "`men verily swear by the greater.`"
And men and angels have made use of oaths to confirm the truth, and avenge falsehood.
I see not how swearing by any creature can be exempted from idolatry.
He that sweareth must do it righteously in a lawful, just matter.
Those that swear falsely are highly guilty of offence against the God of truth.
Can a blackamoor change his skin, or a leopard his spots?`'

[.discourse-part]
_Answer._ Christ, who hath ended oaths, ends controversies amongst men,
and brings them to peace one with another, and with God, and ends the law,
and fulfils it, and doth not break it; and ends the prophets who swear,
and '`Christ is the end of the law to every one that believes.`' And your human societies,
which are of the earth, from the ground, amongst whom are the oaths, the swearing,
are out of the doctrine of Christ, and know not the end of the law and the prophets;
and they are the apostates, and false, and ridiculous,
apostatized from Christ and the apostles`' doctrine, that swear, and teach men so,
and are not the true Christians: and so you that will swear, will forswear,
who are out of the truth; for the truth, Christ, saith,
'`swear not at all.`' And the apostle says, '`Above all things, my brethren,
swear not at all.`' So you are the false brethren, apostatized from the truth,
and are come to be as black as the Ethiopians and the blackamoors,
and your custom of the sin of swearing doth take away the sense of it.

And as for men and angels swearing, and the swearing by the greater:
and '`to the Lord every tongue shall swear,
and perform their oaths to him;`' and they were to swear by the name of the Lord.
Now Christ is he to whom the angels must bow; and as the people had sworn by Baal,
so the prophet brought them to swear by the Lord, to change their form;
to swear by the Lord, as a true oath, and perform it to him.
But Christ is the end of the prophets and the law, as I said before,
and of the true oath; for saith he, '`It hath been said to them of old time,
thou shalt perform thy oath to the Lord;`' that was a true oath, not a false oath;
let all take notice of that! '`but I say unto you,
swear not at all.`' So he came to end the true oath, Christ, the oath of God.
And so, though the angels, or men in strife, or prophets, or Moses, or the law,
said swear; yet Christ, who comprehends time before the world was made,
who came to end that old time, says, '`swear not at all,
but let your communications be yea and nay,
for whatsoever is more than these cometh of evil.`'
And many men are undone by these false oaths,
and by swearing.
And you that call yourselves ministers of the gospel, and teach men to swear,
when Christ says '`swear not at all,`' have brought another doctrine,
and so are to be accursed.

And again, do not you swear by the Bible, by the prophets, and Moses, and Christ`'s,
and the apostles`' words, and by the evangelists?
and Christ says,
'`Swear not at all!`' What a perverse generation of men are ye professors, and teachers,
and people!
What an unchristian spirit have you!
And see, have you not brought the judgment upon yourselves to be the idolaters?
For the true oath was by the Lord, among the Jews, and you swear by the evangelists,
and the bible that tells you you should not swear!
Did ever the prophets swear by Moses`' words?
or Moses by Enoch`'s? or the apostles by the prophets`', or Christ`'s words?
Now is not this a frivolous oath to swear by the bible, which says,
'`Swear not at all?`' And worse than the Jews that swore by the temple,
who were to swear by the Lord, and to perform the oath to him?
Which oath Christ ended, and brought men out of strife, and the earth,
into peace with God, to the beginning,
to '`the glory which was with the Father before the
world was begun,`' who brings the '`peace on earth,
and good will towards men.`' And do not you that swear by the bible,
swear by all that is contained in it, as the Jews swore by the temple?
And so hath not the bible judged you?
Here are Christ`'s words and the apostles`', that tell you ye should not swear,
and yet you swear!
And if ye say, the prophets, and Moses, and Abraham, and Jacob, and Joseph,
and the angels swore, and men of strife swore;
do not Christ and the apostle tell you he is the end of the prophets,
a greater than Solomon?
David called him Lord, before Abraham was; he reigns over the house of Jacob and Joseph;
to him the angels bow, and he says, '`Swear not at all.`' '`This is my beloved son,
hear him,`' is the end of the law and the prophets to him that believes, who hears him.
But it seems you that are the swearers and forswearers will not hear him.
And the apostle brings that concerning an oath`'s
being the end of controversy among men of strife;
and that men swear by the greater, and that they swear by the Lord;
he brings these examples, not that men should swear, but to show how God,
that could not find a greater, sware by himself concerning his son,
who is the oath of God, the end of oaths.
And as to the true oath that men swore, that ended the strife; he brought peace on earth,
and good will towards men, that ended that oath,
and brought men to unity with God and one another, out of the earth to the beginning.

[.discourse-part]
_Principle._ '`That oaths are to be performed if the scriptures were silent:
the law of nature and nations would speak loud in this point,
because of the particular miscarriages in human societies.
Therefore, says the Lord, mine oaths ye despised, and my covenant ye have broken.
It would be a great dishonour to the nature of an oath,
if it should tie any man to disobey the commands of God.
Governors are ready to think it their great security to establish themselves by oaths.`'

[.discourse-part]
_Answer._ Let the law, as ye call it, of nature and nations,
who establish themselves by sin and transgression in the earthly human societies,
cry never so loud for swearing, the commands of Christ forbid swearing.
And I know that the law of nations, and the national laws,
have sanctioned swearing by several heathen gods and idols,
as the Jews swore by the temple, and you by the evangelists;
but '`swear not at all`' Christ says, and his apostle.
And there is a great outcry for oaths, but here is a cry from the Lord Christ,
which says, '`Swear not at all.`' And oaths were in the covenant which was to change,
(mark that!) oaths despised, and covenant broken.
This was the first covenant, in which were the oaths, that was to change and decay;
and Christ came to end both covenant and oaths,
and bid them '`swear not at all,`' and took away the first covenant,
that he might establish the second.
And as the Jews break the first covenant, and despised the Lord`'s oath, which was,
to swear by himself, who is the greater, and to perform it to him;
so you that are teaching men to swear, despise his covenant, his son,
the everlasting covenant, that ends oaths and the first covenant.
And so there is swearing, and forswearing, and lamentable work,
as you may see in your courts, how they will swear a man hath so much,
when he hath not half so much, as the writs and indictments,
and all their bad stuff declare.
And so you that swear do break the commands of Christ;
though it was the command of God in the old time to swear,
yet it is the command of Christ, who makes all things new, '`swear not at all.`'

And the governors that are established by oaths are out of the doctrine of Christ,
that establish themselves by that which Christ denies,
and so establish themselves out of his power, command, and authority,
and do not hear the son, and are not the true christians,
but are apostatized from the true church, have only his name, but are dead to the life.

Now Christ, that takes away oaths, and showed the danger of those that went into oaths,
more than yea and nay in all their communications,
bid them '`swear not at all,`' and that they went into the evil that did,
he established a way;
'`by two or three witnesses every word is established.`'
So they that would have any more than yea and nay,
may take the order of Christ, mind the order of Christ,
'`two or three witnesses,`' that ye may establish every word.
And this is a way for all tradesmen, and magistrates, and all whatsoever,
that they may follow and practise the commands of Christ,
yea and nay in all their communications; and if they will have any more,
'`two or three witnesses,
that every word may be established.`' And such are the true christians,
the true brethren, that abide in the doctrine of Christ, they are not transgressors,
but have the son and the Father, which the others have not;
and that is a practice for all true christians, cities, countries,
and magistrates upon the earth.

[.discourse-part]
_Principle._ Thou sayst, '`Those that be engaged take oaths,
and they must be circumspect in taking of it,`' and this is the word thou adds:
'`And you, my lord mayor and sheriffs,
under the bond of an oath shall execute your office.`'

[.discourse-part]
_Answer._ The command of Christ and the doctrine of the apostles, engage men not to swear,
and do not engage any to swear, and Christ is the end of the law and the prophets;
but you ministers of unrighteousness, and false apostles,
teach men to disobey and transgress the commands of Christ,
who are the false prophets and antichrists which Christ said should come,
John saw were come, which went forth from the apostles,
and since the world is gone after you; and so you have taught the world to swear,
and men to swear, and Christ and his apostles teach them not to swear.
And so here is the land mourning because of oaths;
among boys and girls they are become common in your streets, courts, and houses:
swearing, forswearing, and profane swearing,
and that which is out of the command of Christ is profane; for they bewitch people,
that draw people from the command of God.
The apostle instances circumcision which Christ ended;
and what are they that draw people to those things which Christ forbids,
but such as would not have him to reign, but antichrists,
which have been from the apostles.
And so you and the Papists are one here, doing what you do by an oath;
and the apostle (whom you are apostatized from,) saith, '`Above all things,
swear not at all, neither by heaven, nor by earth, nor by any other oath;`' mark,
this was to the brethren, true christians, true believers,
such as obeyed Christ`'s doctrine; for he tells them the danger,
'`lest ye fall into condemnation.`' '`Let all your communications be yea, yea, and nay,
nay; whatsoever is more, is evil:`' '`Not by heaven, nor by earth,
nor by any other oath.`' Now true, and false, and profane, and all swearing whatsoever,
was comprehended in these words,
'`not by any;`' but keep to '`yea and nay in all your communications.`'
Now tell the apostle he doth not mean as he speaks,
give him the lie, pervert his words, and Christ`'s words, who says,
'`swear not at all,`' and say he means profane oaths.
Christ brought the people off the true oath which was in the old time,
that was performed to the Lord; a profane oath was not performed to the Lord; that,
therefore, was not meant, but such as were sworn by him.
Christ says now, '`swear not at all;`' and so they that break the oath,
break the covenant, the true oath; so they that swear now, do not own the new covenant,
which ends the true oath and covenant in the old time.
The profane oaths were judged by them that lived in the first covenant,
and they did not type out anything, but a true oath did,
which ended controversies among men; which the oath Christ ends,
who is the peace between God and men, and reconciles them to God and one another.
These are true brethren, true christians,
that are come to yea and nay in their communications, and cannot swear '`by heaven,
nor by earth, nor by any other oath,`' lest they come into the evil;
but keep to yea and nay in all their communications, lest they come into condemnation.
So you that teach men to swear have brought them into evil, and under condemnation,
and a great outcry you have raised to break the commands of Christ.
Ye that teach them to swear any oath whatsoever,
cast behind your backs the commands of Christ, and doctrine of the apostles:
and the apostle, that bid the saints keep to yea and nay in all their communications,
and '`swear not at all,`' said, if ye will have any more, take two or three witnesses.

[.small-break]
'''

And for all thy other confusion, and thy perverting and wresting of scriptures,
to bring people into the condemnation and evil of swearing, is not worthy the mentioning,
and will but come upon thyself in the day of thy condemnation and judgment;
thou and all upon the earth that are departed from the apostles
shall witness how ye that have transgressed the commands of Christ,
and teach people to transgress them, and to sin,
have brought them into the evil and condemnation.
So repent, and while ye have time prize it.
