[#ch-45.style-blurb, short="The Quakers`' House Built on the Sands"]
== Samuel Hammond, in his book, called '`The Quakers`' House Built on the Sands.`' A very fit title for himself and the rest of his priests. These are some of his principles.

[.discourse-part]
P+++.+++ '`Young men and women having some convictions and awakenings of the law,
have followed the light of an awakened conscience,
and sit down before they have closed with Christ;
and they make not a distinction between the righteousness imputed,
upon the account of the blood of Christ, and the righteousness inherent,
wrought in us by his spirit: and this inherent righteousness,
the attainments brought forth by the light in every man, they confound with the other,
not being able to distinguish the workings of Satan.`'

[.discourse-part]
A+++.+++ Inherent righteousness is a word of thy own and the Papists`' inventing,
and thou art a man that canst not distinguish between
the workings of Christ and the workings of Satan.
For the light which every one that cometh into the world is enlightened with,
which brings men and women to know the law, and the convictions of it,
brings them to the end of the law, Christ, and to see that appear that cannot be shaken,
and the righteousness imputed to a believer that is felt within:
'`For he that believes hath the witness in himself,`' and feels it there;
and the blood of Christ is felt within,
justifying and cleansing the conscience from dead works.
And the righteousness of faith is found within,
and that righteousness which is wrought within, is found within,
and no man sees this but with the light which Christ hath
enlightened every man that cometh into the world withal;
and this light is that which confounds all thy attainments, for Christ`'s righteousness;
and his blood and spirit are all one, which justifies and sanctifies.

[.discourse-part]
P+++.+++ '`They dream of a perfection by obeying the light within, and this is delusion;
they are not able to distinguish,
between "`justified freely by grace,`" which is the
favour of God upon the account of Christ`'s satisfaction,
and the grace that is wrought by Christ`'s spirit in the soul: that natural light within,
being improved, they call grace.
The work of God upon the soul, leads into the covenant of works;
then it is no other than to tread in the Papists`' steps: so this is delusion,
and the ground of their delusion is their not distinguishing
between saving light given forth by Christ in conversion,
and the light of conscience that every man hath.`'

[.discourse-part]
A+++.+++ None come to the perfection, out of the delusion,
but they who come to the light within, and follow that;
it gives him the light of the knowledge of the glory of God in the face of Jesus Christ.
That which was wrought without is within in the soul,
for '`Christ in you,`' etc. and he is the covenant of grace, of light, of life,
and of peace: and none know him without, nor justification by grace,
but who know it in the heart, and it is one and the same thing, it is not another grace,
nor another covenant, nor another Christ,
but the same '`Christ in you.`' The saints are in his spirit, and in his mind,
and are of his flesh, and of his bone.
And thou who art so full of thy delusions, art out of this,
and thou always hast been in the dreams, and never wilt know perfection,
till thou come to the light within.
And God`'s work in the soul leads to the end of the covenant of works,
who '`works all in us, and for us,`' as says the apostle; who works faith and grace,
commands the light to shine out of darkness,
and shines in the heart to give the knowledge of the son.
And so thou art in the delusion and the Papists`' doctrine, that knows not this within,
but calls it the covenant of works: dost not thou tread in their steps,
and hast crept up in their great mass-houses?
And the light given forth by Christ in conversion, and the light in the conscience,
are one, and it is not natural, it was before natural was;
it exerciseth the conscience towards God and towards man in them that love it;
but they that hate it, are not converted,
but live in the many ways out of the one way to God;
for he that is the covenant of light is the covenant of grace.
And thus thou art blinding people with many things.

[.discourse-part]
P+++.+++ '`The owning not the imputation of Christ as the matter and formal cause of justification,
is damnable doctrine:
to make our reconciliation to God to be wrought by our improving the light within,
and renewing the image of God in us, is damnable doctrine;
to take men off from going to the fulness of Christ at the right hand of God,
and send them to look to a light within, which they say is in every man,
is a damnable doctrine;
this is to forsake the fountain of living waters and dig to themselves broken cisterns:
a dangerous principle is that of perfection by improvement of the light within.`'

[.discourse-part]
A+++.+++ The imputation to a believer is owned, and this imputation is within;
for he that believes is born of God, and hath the witness in himself.
Now Abraham believed, and the Romans,
and to such the imputation was spoken in the belief; and Abraham saw his glory,
who is Christ Jesus the righteousness itself.
And the apostle says, ye are now nearer than when ye believed; and again he says,
'`Christ is in you, and God will dwell in you,
and walk in you.`' So such as have Christ in them, have the righteousness itself;
without imputation, the end of imputation, the righteousness of God itself, Christ Jesus.
No man knows the reconciliation, and his reconciliation made with God,
but by hearing and doing the word of God, that is in the heart and mouth,
which divides thy bad words, (Hammond,) and thy bad thoughts, and cuts them down,
and hammers them down, and burns them up;
that is the word that sanctifies and reconciles to God, and makes clean.
And the word is Christ,
called '`the word of God,`' and Christ is the light that
doth enlighten every man that cometh into the world,
and that is it that renews man into the image of God.
For the light that comes from Christ is the image of God,
'`the light of the glorious gospel which is the image of God,`' and so this is within,
and thou that knowest not this within, and feelest it not, thy lips are polluted,
and thou art in the damnable doctrine, and the light that shines in the darkness,
thou canst not comprehend.
And indeed, thou art too proud, high, and lofty, and must he brought down;
the Lord God will abase thee.
And no man comes into the image of God, and is renewed, and hath reconciliation with God,
but who comes to the light which Christ the word hath enlightened him withal,
and that is within, and they that believe in it have the witness in themselves,
and they that do not, the light condemns them.
And the light that every man that comes into the world is enlightened with,
doth not take them from Christ`'s fulness at the right hand of God;
but the light lets them see him lifted up,
and no one upon the earth comes to Christ at the right hand of God,
to receive of his fulness,
but who comes to the light with which Christ doth
enlighten every man that cometh into the world:
that is the eye, the light, with which he sees Christ, and in that he receives him,
and comes to be ingrafted in him, in the vine Christ Jesus.
And so thou that drawest men from the light within,
which Christ hath enlightened every man that comes into the world with,
thou drawest them from Christ at the right hand of God,
that they cannot receive this his fulness,
and so thou takest away the key of knowledge from people,
who art in the doctrine that is damnable, and to be condemned, that is from the light.
And none come to the fountain of living mercies, but are all broken cisterns,
that are from the light within them,
which comes from Christ the fountain of living mercies,
which doth enlighten every man that cometh into the world,
that with it all might come to see the fountain, and believe in it,
and they that do not are condemned.
And no one knows perfection, nor comes into the perfection of Christ,
but is in the dangerous estate, where thou art,
who doth not come into the light which enlightens every man that comes into the world;
for the imperfection comes by the first Adam and Eve,
and the devil going out from the truth; the perfection comes again by Christ,
who destroys the devil, death, and his works, and sanctifies man,
and reconciles man again to God, who doth enlighten every man that comes into the world,
that in the light all men might see the perfection of God, Christ Jesus;
which none do but such as come to him, the light.

[.discourse-part]
P+++.+++ '`That there is so much light in every man that will reveal Christ,
and save them that believe in it: and that an Indian hath it:
and to direct to this to lead to perfection,
and to neglect the fountain of wisdom at the right hand of God,
is a soul destroying principle.`'

[.discourse-part]
A+++.+++ The light which every man that cometh into the world is enlightened with,
is saving to them that believe in it, they that do not are condemned;
and this light leads to perfection, to the fountain of wisdom,
Christ Jesus the light of the world, to know the bishop of their souls;
and all that are not come to the light in their own particulars,
which comes from him that doth enlighten every man that comes into the world,
their principles are destroying, which thine are that standest against the light,
thou art antichrist, kicking against the light with which Christ hath enlightened thee.
No man knows a saviour, nor sees salvation, but as he comes to the light;
with the same light he comes to see Christ the light and saviour,
to save him from his sins.
And that light is sufficient;
'`I will give him for a covenant of light to the Gentiles;`' and '`I will make
a covenant with the house of Israel and Judah,`' them that had the old,
(and here is all the world,) and he shall be my salvation to the ends of the earth.
And the Gentiles were heathen, call them Indian or what thou wilt:
'`I will give him for a covenant to the Gentiles,
a leader of the people,`' and many Gentiles have found their leader,
the covenant of light; and in this light, Jew and Gentile are one, and in unity.
'`If ye walk in the light as he is in the light,
then have ye fellowship one with another,`' and this breaks all your sects,
the covenant of light between Jew and Gentile,
and brings them to one in believing in the light.

[.discourse-part]
P+++.+++ '`That light that is in every man is the relics of the first
covenant of works which cannot reveal Christ as mediator.`'

[.discourse-part]
A+++.+++ The light which every man that cometh into the world is enlightened with,
which is Christ, by whom the world was made, ends the covenant of works;
the creation was made by him, and he was before it was made,
so he is not a created light, but that by which all things were created.
And thou art in thy works, the covenant of works, and the created lights,
that tallest the light that enlightens every man that cometh
into the world (Christ Jesus) a covenant of works,
or that a natural light, which was before the covenant of works was,
or a natural light was created; which ends the covenant of works.
And thou art to be judged for thy words.
And with that light every man sees the mediator, believing in it; if not, it condemns him.

[.discourse-part]
P+++.+++ '`That all the light they have is but the light of a natural conscience,
and that is a blurred one too.
Nay, how comes it to pass that in old England we see so many hundreds,
that manifest no other but a natural conscience?
and in New England, that have conversed with the Indians,
and never saw the least breaking forth of the light.`'

[.discourse-part]
A+++.+++ The light which doth enlighten every man that cometh into the world,
by whom the world was made, was before natural conscience was, or natural light either,
or the blurred light, as thou callest it.
And many of the Indians do show forth more of the
light in their conversations than you do.
And as for old England, what have you been doing all this while,
if you see so many hundreds manifesting no other light but a natural conscience?
But how should they manifest it, when you keep them from it?
Your work is to keep them from the light within.
But now there are thousands that are manifesting the light on the house-top,
that by which the world was made,
which doth '`enlighten every man that cometh into
the world.`' And you ministers of Satan,
out of the light and truth, are those that stand against it;
for the devil that went out of the light and truth,
who sowed his seed in the hearts of people, would not have them to own the light in them,
he would confess a God without him; and so he teaches them in whom he sows his seed,
not to have the light within them, the seed Christ, the tree of righteousness,
the root of God.

[.discourse-part]
P+++.+++ '`I charge the Quakers to show one scripture that bids look to the light within,
the old trick of error.
The righteousness of faith doth not direct people to look for a Christ within;
the scripture bids weary laden souls, go to Christ; is this to the light within them?
I am amazed at their ignorance.`'

[.discourse-part]
A+++.+++ The righteousness of faith brings people to look at Christ within;
and what abundance of ignorance hast thou shown,
who hast been a teacher of the people these many years,
yet showest how contrary thou art to Christ and the apostles in doctrine, for in 2 Cor.
iv. the apostle tells the Corinthians, '`the light shined in their hearts,
to give them the light of the knowledge of the glory of God in
the face of Christ Jesus.`' This was the work of the true apostles,
when the false apostles, and devil`'s ministers and messengers, were got among them:
for the devil is out of truth, and so are his messengers,
and they will draw people from the light within,
and blind their minds that they should not come to the light within,
to see the glory of God in the face of Christ, from whom it comes.
So thou concludest thyself among the devil`'s ministers,
and false apostles and messengers.
And no wearied soul that is burdened, comes to Christ, who is the soul`'s rest,
but that first comes to the light within,
which comes from Christ who is the soul`'s bishop, with which light they see him;
he shines in their hearts, which gives them the knowledge of him,
and the glory of God in the face of Christ Jesus.
And thou that leadest them from the light within,
leadest them from Christ and the glory of God, who should save them from their sins,
and give them ease, rest, and peace.

[.discourse-part]
P+++.+++ '`I said, looking to the light, and living upon the light within,
will lead men to hell; and is going to, and living upon, a muddy puddle of natural light.
That Christ is the light in all in a saving manner, I deny;
for Christ to be the righteousness of men in justification, differs from this;
and to send a man to live upon a light within, is not to send him to Christ;
and if he live upon it, upon the light as it is justification,
it is a plain covenant of works.`'

[.discourse-part]
A+++.+++ There is no man hath life but in the light which comes from Christ,
the light by whom the world was made, in whom was light,
and this light is the life of men; and this light and life are manifest in us;
for he that hath the son of God, hath light and life:
he that receives not this but hates it, though he be enlightened, hath not life,
but hates it.
Such as lead people from it, go from it in their own particulars;
they lead people into hell, into its gates, which prevail against them;
but they who are in the light, the gates of hell cannot prevail against them;
and they that believe in it are not condemned.
And so they live in the muddy puddle, and go into the natural light,
that deny the light within,
which Christ hath enlightened every man that cometh into the world withal;
they live not upon the life, but in the muddy puddle of darkness, and are antichrist,
out of the light, and are against it in their own particulars,
and against them that walk in it; and such are unlike the ministers of Christ.
Every man that cometh into the world is enlightened with the saving light,
and he that believes in it is saved, he that doth not is condemned.
No one comes out of the covenant of works, but by the light within, which Christ,
the covenant of God, hath enlightened him withal.
And no one lives out of the covenant of works, but who lives in the light;
and who lives in the light, lives in Christ, and Christ in him: '`I in you,
and you in me;`' and they who hate this light, live not in Christ, it condemns them,
for they are in their own covenant of works.
Who believes in the light, hath entered into the rest,
and ceased from his own work as God did from his.
And righteousness and justification are one; where Christ is known and felt in man,
they are both felt in one.
For Christ is the righteousness of God, and the justification, and Christ is in you;
and see if thou canst read this, who sayst, they differ.

[.discourse-part]
P+++.+++ '`What warrant have you to go out to the Quakers?
Shall a man go to hear the Jews and Popish mass, because Paul bid try all things?
No, no.`'

[.discourse-part]
A+++.+++ Paul bids '`quench not the spirit:`' and where the spirit is not quenched,
they may try Papists, Jews, and Protestants; but they who quench the spirit,
and draw people from the light within, draw from that they should see with;
then ye stuff them up with old authors, and lying stories, as you print abroad.

[.discourse-part]
P+++.+++ '`Christ`'s revealed will is the word of reconciliation.`'

[.discourse-part]
A+++.+++ The scriptures are not the word of reconciliation;
but Christ is the word of reconciliation, who reconciles man to God,
and satisfies the Father, and gives men peace with God; and this the scripture declares.
And as for the ministers of Newcastle,
who have persecuted the people of God because they met there,
and banished them out of their town, this doth not show the spirit of Christ,
nor the love of God among you, but the works of the Pharisees and Cain.
And thou never knew the gospel that denies the light of Christ,
that hath enlightened every man that cometh into the world,
but art found among the monkish-holiness thou speaks of,
and the Pharisees and the Papists; for the Pharisees, the Papists, and you,
do not own the light, Christ Jesus, that enlightens every man that cometh into the world.
So with the light you are all comprehended and condemned in one body,
not to be true believers; for they believe in the true Christ the light,
and bid people believe in the '`light that doth enlighten
every man that cometh into the world,
that all men through him might believe;`' that is the end;
that he that doth might be saved, and that he that doth not might be condemned.

[.discourse-part]
P+++.+++ Thou sayst, '`The saints laid down their estates at the apostles`' feet.`'

[.discourse-part]
A+++.+++ You priests say you are ministers of Christ and the gospel,
and you are fain to cast men into prisons, because they will not put into your mouths.
Now all people may see that you have a contrary power to the apostles;
for when did a people, your hearers, lay down all at your feet?
Nay, you are fain to cast into prisons, hale before courts,
a hundred or two hundred miles, and take treble damages.
Now do you not think that most people begin to see
that you are apostatized from the apostles,
and from the power they were in, with which you are fathomed,
and with the life the apostles were in are you judged.

And whereas thou speakest of circumcision,
and tellest people that they that are circumcised cannot be saved;
the Quakers bring no people to circumcision, but that of the spirit,
which puts off the body of sin,
which you say they must have while they are upon the earth,
and so have ravened from the spirit of circumcision;
and such keep people in the covenant of works,
from the spirit within that puts off the body of sin.

And as for all the rest of thy torn, confused stuff,
which is given forth from thy vain thoughts, it is not worth mentioning;
but in the day of thy judgment, the witness in thy conscience shall answer it,
and all thy works are fuel for the fire.
