[#ch-46.style-blurb, short="Looking-glass"]
== Priest Bennet`'s [.book-title]#Looking-glass.# These are some of his principles following.

[.discourse-part]
P+++.+++ '`James asks the question,
Can one fountain send forth sweet water and bitter?`' He says,
'`It is a new fancy to say there is a light in every
man which will guide him to salvation.`' And says,
'`There is a fancy of perfection.`'

[.discourse-part]
A+++.+++ One fountain cannot send forth sweet water and bitter,
and yet it is bitter to them that are in the transgression;
for the righteousness of God revealed to the wicked, is a terror to him;
but the righteousness of God revealed to the saints, is their joy, as is the truth:
but speaking truth to him who is in the deceit, is bitter to him,
but to the just it is not.
And the '`light that doth enlighten every man that
cometh into the world,`' is Christ Jesus,
'`the salvation to the ends of the earth.`' Thou
art in the fancy that stumbles at this corner stone:
and this '`light that enlighteneth every man,`' is the perfection of beauty,
and they that are out of this, are in the fancy of a perfection,
where thou mayst see thyself.
And the Pharisees stood against Christ the light,
the covenant of God promised to Jews and Gentiles, though they had the scriptures;
them thou art like, that art now stumbling at the light as they did.
So thou hast the mark of an unbeliever, one '`that hath the form,
but denies the power,`' and art not a preacher of that which people should believe in,
that is the light.

[.discourse-part]
P+++.+++ '`The scriptures are the lanterns of Israel.
The scriptures are the wisdom of the cross.`'

[.discourse-part]
A+++.+++ The word of God is the lantern of Israel, as says David;
and Christ Jesus is the wisdom of the cross; Christ the wisdom of God;
and the cross of Christ is the power of God.
And Abraham had a lantern, and Enoch and Abel, before the scriptures were written.

[.discourse-part]
P+++.+++ Thou sayst, '`The corruptions of the damned in hell shall never be destroyed;
and it would be good news if the Quakers should go
and preach to the spirits in hell.`' And thou sayst,
'`David would open his mouth in dark sayings of old.`'

[.discourse-part]
A+++.+++ The scriptures, and David`'s words, to thee that art in darkness, are dark,
but not to them that are in the light.
And the Quakers have been among the prisoners that are in hell, and ministered to them,
and the corruptions shall go into the fire that hath no end; and they that do wickedly,
and forget God, shall go into hell, and death and hell shall go into the lake of fire,
and there is yet more in these words than thou canst receive.
For '`God is the salvation of all men,
but especially of them that believe.`' But I must tell thee,
thou and thy flesh are for the fire thou art speaking of;
and when thou art burning in it, remember thy judgment in thy lifetime,
and what thou didst.
And the end of Ezekiel is known, and the prophets, and Moses, Christ Jesus,
the saviour and redeemer of the world.

[.discourse-part]
P+++.+++ '`That a natural man may preach the gospel in
the history.`' And thou brings Judas for an example.
Thou sayst, '`Christ said, destroy ye this temple, and I will build another.`'

[.discourse-part]
A+++.+++ That which led Judas to minister was not natural,
for the same condemned him when he went from Christ.
And a natural man cannot preach the history of the gospel truly,
for he cannot receive it; but natural men are giving other meanings to it,
and this brings all the confusion that is in the world about the scriptures;
for Judas was made partaker of the ministry, and when he went to the priests from Christ,
then he was condemned.
And Christ did not say, '`Destroy ye this temple,`' thou pervertest his words.
Neither did he say he would raise up another of lime, and stone, and wood,
which you dark priests of the world, blind people`'s eyes with;
but he meant the temple of his body, in which God dwelt,
which the outward temple was a figure of.

[.discourse-part]
P+++.+++ '`That it is an absurdity to say the light is in every man to teach him.`'

[.discourse-part]
A+++.+++ The '`light that doth enlighten every man that
cometh into the world,`' which is Christ Jesus,
is the teacher: and he that believes in it, receives Christ,
and it teaches him that hates it to see his evil deeds, to see his evil ways,
and he hates it because it reproves him, because his deeds are evil, and so hates Christ,
and hates his teacher, and sets up teachers without him,
and doth not come to receive the anointing within him,
and so that light is his condemnation, and so he sees not Christ the head.

[.discourse-part]
P+++.+++ Thou sayst,
'`The ministers may receive a courtesy,`' and the scripture thou brings for it is,
'`the earth shall help the woman.`'

[.discourse-part]
A+++.+++ The courtesy the saints received from them whose hearts were opened,
that the Lord had opened by his power, is not condemned,
but your taking tithes from people you do not work for,
and casting into prison till death, for not giving it you.
How are you like the apostles, or like the ministers of Christ,
or like the woman thou speaks of, the church that was persecuted?
Now you persecute, she was persecuted; and you persecute for means,
and hale up and down in courts and sessions, and will take treble damages,
treble tithes of them you do not work for,
and so you will not stand to the courtesy of people,
nor wait for the power to open their hearts;
but are in a power that will take it by compulsion, and by violence, away from people.
So you have given judgment against yourselves,
and are not of the number of them the Lord opened
their hearts that ministered to their necessities,
and so unlike the ministers of Christ that received the courtesies of the people,
whose hearts the Lord opened.

[.discourse-part]
P+++.+++ Thou sayst, '`When people have no guide but what is within,
and that this principle he rooted, it will turn all into Babel.`' And thou questions,
'`whether it be not a principle of sedition to say,
that every man hath a light within him.`'

[.discourse-part]
A+++.+++ All people in the world run into Babel and Babylon,
and are building up and throwing down, and so go into confusion about law and gospel,
prophets, Christ, and the apostles`' words,
when they are from the spirit of truth within,
'`to lead them into all truth,`' and up to God, the Father of truth,
of whom they learned that gave them forth, and with that spirit are they seen;
in which spirit is '`unity,
which is the bond of peace.`' And the '`light which doth enlighten
every man that cometh into the world,`' leads all men out of sedition;
and they are in the sedition that deny it, and say to the contrary, and in darkness,
and cannot comprehend it, as John says; who says,
'`This is the true light that enlightens every man
that cometh into the world.`' And Christ says,
'`Believe in the light.`' And the prophets said,
'`God gave him for a covenant of light to the Gentiles,
and a new covenant to the Jews,`' and he shall be the leader of the people,
and salvation to the ends of the earth;
and every man that comes into the world is enlightened.
'`He that believes is saved, and he that believes not is condemned already.`'

[.discourse-part]
P+++.+++ Thou queries, '`when the act of commission for the ministry was repealed,
since Christ said he would be with them to the end of the world?`' And thou sayst,
'`It is not said simply, they shall teach no more every man his neighbour;
but it is added, "`Know the Lord.`"`' Thou sayst,
'`that every man is enlightened only with a natural reason,
and the elect are enlightened with a saving knowledge.`' Thou sayst,
I bring John 4:23. '`to overthrow all outward worship.`' Thou sayst,
'`you can praise God with your bodies and spirits.`'

[.discourse-part]
A+++.+++ In Matt.
vii. and Matt.
xxiv.
Christ said false prophets should come, and should be inwardly ravening wolves,
having sheep`'s clothing; and John said they were come, chap.
ii. and chap.
iv. And in Rev.
'`all that dwelt upon the earth went after them,`' and such killed the saints.
When they had gotten a head, they killed the saints and the true ministers,
and they that were of the false, killed the true;
and since those days the false have reigned, who have wrestled with flesh and blood,
imprisoning, killing the creatures, and warring against them,
and not with the principalities, and spiritual wickedness, and powers of darkness.
And such have been out of the power, the gospel the apostles were in,
and have killed them that kept the testimony of Jesus, which is the spirit of prophecy.
And it is said plainly, Heb.
viii.
'`They shall not teach every man his neighbour, nor every man his brother, saying,
know the Lord, for they shall all know me from the greatest to the least,
saith the Lord.`' And so thou perverts the scriptures, and art judged by them for it,
that belies them.

And the light '`that doth enlighten every man that cometh into
the world,`' is the same light that the elect live in;
and the world not believing in the light, Christ Jesus, the elect, the covenant of light,
and life, and peace, promised to the world, they are condemned already;
but he that believes in the light, is saved; so that saving is sufficient.
And Christ says, '`they that worship the Father,
must worship him in spirit and in truth:`' not at Jerusalem, not at Samaria,
nor at the mountain.
So say I, not at your mass-houses, with a cross at the end of them,
which the popes and you set up, since the days of the apostles.
So '`they that worship God,
must worship him in spirit and in truth.`' Truth does not change,
neither does the spirit, and these are they the Father seeks to worship him,
and hath found many: and Christ overthrows the outward worship at Samaria and Jerusalem,
and the mountain, and so do we at your Papists`' mass-houses,
and tell you God is worshipped in spirit and in truth;
and those are the true worshippers that God seeks to worship him,
and that will stand when mass-houses, Samaria, and Jerusalem are down,
the spirit and the truth will remain.

'`In the mouth of the wicked,
praise is not comely;`' and as you are singing David`'s conditions,
or the saints`' conditions given forth from the spirit,
when you confess you are not in the spirit, as they were that gave them forth:
so then you are judged by it to be such in whose mouths praises are not comely,
but are in another state than they were that gave forth scriptures.

And Adam`'s state before the fall thou knowest not,
but art found in the steps of the Pharisees and Papists.
As the Pharisees got the words of the true prophets and Moses, out of the life,
so the Papists and you have got the words of Christ and the apostles,
and are out of the life, and persecuting them that are in the life, as the Pharisees did,
and killing the just, the just being imprisoned in your own particulars,
as it was in the Pharisees.
And you, with your dark eyes, have looked upon the scriptures ever since the apostacy,
and ravened from the spirit of God and the pure eye,
and so with that you are comprehended, felt over, and seen over,
and with that shall the principle of God in you all be answered,
that you are apostatized from the apostles in life, and power, and doctrine,
and so are in heaps about their words, out from that which is the ground of communion,
the bond of peace.

And all thy confusion in thy book, is thy own garment, who with it art for the fire;
the witness in thy conscience in the day of thy condemnation shall witness it.
