[#ch-47.style-blurb, short="The Seventh-day Sabbath"]
== Thomas Tillam`'s book called, [.book-title]#The Seventh-day Sabbath.# His principles answered as followeth.

[.discourse-part]
P+++.+++ '`All sacrifices did type out Christ, but the sabbath did never type out Christ,
and therefore never to be abolished nor changed.`'

[.discourse-part]
A+++.+++ Ezekiel saith,
'`The sabbath should be for a sign,`' which is spoken of among the statutes, chap.
xx. And the apostle says, '`Let no man judge you in meats or in drinks;
or in respect of any holy day, or of the new moon, or of the sabbath day,
which are all shadows +++[+++mark]
of good things to come, but the body is Christ.`' Col.
ii.16,17. Now they are called shadows here, the sabbath is called a shadow,
but the body is Christ.
And Ezekiel calls them signs.
And such as rest in those things, in the shadow,
may '`beguile people in a voluntary humility, and worshipping of angels,
intruding themselves into those things that they never saw, not holding the head,
and neglecting the body to the satisfying of the
flesh;`' who would live in the signs and the shadows.
For in the beginning it was not a command to men to keep the sabbath, as to Adam and Eve;
you do not read it was a command given to them: but in the transgression and fall,
when the children of Israel came out of Egypt,
then to them the Lord gave the sabbath as a sign.
'`The Lord said unto Moses, speak to the children of Israel, and say,
nevertheless keep ye my sabbath for a sign between me and you,
in all your generations.`' Now in all the generations of the Jews, in the first covenant,
here was a sign between them and the Lord, and he that defiled it was to die the death.
Now the body is Christ, Christ the sanctification, the end of the sign and the shadow;
so he that goes from Christ, goes from the rest, from the sanctification, and he dies,
for he that hath not him hath not life, and shall die the death,
and shall be cut off from the people.
So when the children of Israel came out of Egypt,
then was the sabbath given to them as a sign, not commanded to Adam and Eve,
the scripture doth not declare it before the fall,
but it was given to the children of Israel after they came out of Egypt,
who received the law, added '`because of transgression`' upon the transgressors;
to such was given the sabbath as a sign amongst them that had the offerings;
and such were to keep it, and to sanctify it.
But before the fall, when the law and power were in man, before the transgression,
there was no mention of a sabbath to keep it.
Now Christ came who was the end of these offerings, and of these sabbaths,
which are the shadows,
for the apostle says (except any will dare tell him he lies) '`the
body is Christ.`' And they are not judged concerning such things,
in respect of sabbaths, and meats, and drinks, who are come to the body, Christ,
who ends all those things,
and was before those things were to him by whom all things were created and made,
Christ the sanctification.
And they who are come to him in whom there is rest,
as the Jews were to rest upon the seventh day, are come into Christ the body, the head,
the substance; they are come into the rest, the sanctification and the glorification;
who was glorified with the Father before the world began;
where no changing nor shadow nor variableness is.
And these need not have a shadow, nor a sign, nor change, who are come to the body,
Christ the substance.
Now, thou sayst, Christ was a sign: yes, but he ends the sign and shadows;
to the unbelievers he was a sign,
as the people of God were signs formerly to such as stood in outward things.
So Christ is the body, the end of the shadow, the head known and felt,
he that is the Lord of the sabbath, Christ, which is a mystery;
so they that are out of him are out of the life,
and die as they died that went from the sabbath; so do they that turn from Christ,
the soul`'s rest, and peace, and life.
And this sabbath was to be observed in the Jews`' generation by an everlasting covenant,
and he that did any work upon the sabbath day was to die the death.
Now this covenant which stood in shadows and types, Christ came to take away,
who is the end; and he that believes in Christ '`hath entered into his rest,
and ceased from his own works, as God did from his.`' And the apostle said,
the first covenant was to decay, as in Heb.

[.discourse-part]
P+++.+++ Thou sayst, '`such as obstruct the gospel privilege of God`'s sabbath,
rectified by the son, and observed by the saints.`'

[.discourse-part]
A+++.+++ But did ever Christ or the apostles,
give a command to the Jews that they should observe it strictly,
as it had been in the law before the substance was come, the body, which was Christ?
Nay, you read no where that among them the apostles preached the gospel to,
they laid any command upon the saints that they should keep the Jews`' sabbath days,
but told them they were shadows, and the body was Christ, and said,
'`Let no man judge another in such things.`' Now
are you not come under the judgment of such things?
And so the Lord of the sabbath ends the types in him, and in the saints,
who are come to him who is the substance, the body and head, Christ Jesus.
Read Col.
ii.

And whereas thou speakest of changing laws or sabbaths,
this thou mightest have charged on the apostles,
who told the saints no where of keeping the sabbath days,
but told them they were shadows, and that such as were there,
were in their will-worships, neglecting the body; for the body and substance was Christ.
And such were intruders,
and so thou art comprehended to be one of the intruders into those things thou never saw,
who art puffed up in thy fleshly mind, not holding the head and the Lord of the sabbath.
The son of man is come, and the saints go not about to blot out the name of the sabbath;
for the pure sabbath, the sanctified day was a sign and a figure of the pure Christ,
the sanctification, by whom the day was made,
and on which day the people and the beasts were to rest, and which was to be sanctified.
And Christ, who was before the day,
was the sanctification in which all the Lord`'s people have rest,
who is Lord of the sabbath, and who was before the day was made, who fulfils the type,
the shadow, the sign; the body is Christ, and the head is held.
So you that are running to observe days and times, are they that the apostle speaks of,
that he was afraid of, and that his labours he had bestowed in vain,
and so are gone from the body into the shadow and the sign.
Neither do you keep it as you ought to do who profess a sabbath;
your horses and your cattle are doing work, drawing you to your worships;
you are making fires through your congregations, you are bearing burdens,
you are gathering your meat on that day that you call your sabbath.
Now to all people you are dissemblers to what you profess,
and pretenders to a thing to which you are not faithful;
and so by the law according to your own judgment, to be cut off,
and to die as sabbath breakers; for they were not to make a fire, gather any meat,
bear any burden, ox or ass, man-servant or maid-servant, or stranger,
but were to keep holy the sabbath of the Lord; if they did, the law took hold of them;
for six days they were to labour, and do all they had to do.
Now the law was received by the disposition of angels.
So now the law, the first covenant, the shadows, types, and figures,
ye may run into those things from the body, and so neglect the head,
and neglect the body, and go into the signs, and so come into the will-worship,
and the worshipping of angels, intruding yourselves into the things you never saw,
neglecting the body to satisfy the flesh, by which your vain minds are puffed up.
Now the enemies of the sabbath are such as neglect the body, the substance,
and him that is Lord of the sabbath.

[.discourse-part]
P+++.+++ And whereas thou sayst, '`They had eaten the bread of Christ,
and they had turned the heel against Christ.`' And thou sayst, '`The Quakers,
some notionists, and others, are against it.`'

[.discourse-part]
A+++.+++ Our rest is in Christ the body, that ends the shadow, that ends the signs,
who is the substance of the shadows and signs, and those notionists are such as thyself,
and so the saints`' rest is in the substance Christ, the end of the signs and shadows,
who was before the sign was, the day was, in him is rest.
Here all men rest from their works,
'`and every soul that believes hath entered into his rest,`' and hath come from shadows,
signs, and types into the body, Christ, that ends them, and holds the head,
and is out of the will-worship, worshipping of angels, and satisfying the flesh;
for such as do these things are blinded as concerning the body,
and come to be judged about the days, and they hold not the head,
as they do who are come to the body and head, Christ Jesus, to whom all angels bow.
For they that neglect the body will satisfy the flesh, and live in signs, and shadows,
and will-worship, and worshipping of angels,
and intrude into those things they never saw, who come to be judged in respect of days,
which are but shadows.
And such as are in those things satisfy the flesh, and keep themselves from the body,
Christ, and hold not the head; and they that will rest in a shadow after the substance,
the son of man, the Lord of the sabbath, is come, will rest in that which decays,
and it is a false rest.

[.discourse-part]
P+++.+++ And whereas thou sayst, '`A filthy shift of God`'s sabbath,
to say Christ is the sabbath.`'

[.discourse-part]
A+++.+++ This sabbath was for rest, and they were to rest on that day,
and it was given as a sign and shadow, and in the first covenant.
But Christ the second covenant, the perpetual and everlasting rest,
the soul`'s rest of his people, says,
'`Come unto me and ye shall have rest;`' and so he is the end, the substance of the sign,
and the shadow, who was, as I said before, before the day was,
in whom is a rest for the people of God; for the sabbath being given as a sign,
wherein all strangers, servants, beasts, horses, oxen, asses,
and all cattle whatsoever might rest, it was given forth, and sanctified.
For the whole creation was burdened, both horse, man, cattle, and servants;
and mankind were oppressed by transgression.
So the sabbath was a sign of rest, yea, to the stranger,
to all that were within the gates, a figure of the restoration, and of the sanctifier,
Christ Jesus, who destroys death, and the power of death, and the devil and his works,
who is the cause and the author of the burden of the whole creation, and of mankind.
So the sabbath was a sign of rest from their labours, of Christ the restorer,
and redeemer, and deliverer of the whole creation,
who brings it to unity and reconciliation again to God,
who is the rest both to man and beast;
and the stranger should rest within the gates of the sabbath, within Christ.
And much more is to he said of these things, of which this is but a touch,
that which is further in the words, which might be declared.

Now as for the ten commandments, amongst which the sabbath is spoken, he that covets,
he that steals, he that commits adultery and kills, he that sets up graven images,
he that covets his neighbour`'s house, wife, or goods, or any thing that is his,
or commits adultery, is departed from that principle of God in his own self;
so the law was added upon him.
He that is led by the spirit doth not transgress, nor doth oppress, nor covet, nor steal,
nor bear false witness, and so love fulfils the law, and its commandments.
And he that believes comes to Christ, the rest, before the day was, by whom it was made:
and so Christ telling them what was done in the old time,
for following the oath to the Lord, he brings them now '`not to swear,`' into himself,
the covenant of God; he brings them to the covenant of God, the oath of God,
and so into himself, who is the restorer, before days were, as I said before.
And the apostle likewise brought them off from circumcision without,
which was an everlasting covenant, as well as the sabbath was a sign,
he brings them off from that to the circumcision within,
and so to that that answers the power, the life of God which hath been transgressed,
where love is felt in the heart, that remains, and so the thing comes inward;
for as it is said,
'`he that believes hath entered into his rest.`' And so Christ came not to break the law,
but to fulfill it every tittle, who is the rest of his people, yea,
and gives rest to the creation, destroys the oppressor of it,
and the foundation of the oppressor;
and so he was the Lord of the sabbath that fulfils it, for the sabbath was in the law,
and '`Christ is the end of the law to every one that believes;`' and he that is in Christ,
who was before days were, profanes no day, is in his rest,
and will give rest to his creatures, will not oppress any thing at all,
and comes into the wisdom of God by which they were created,
to order and use them to God`'s glory.

And whereas thou sayst, '`that Adam being in honour,
did not abide a night,`' and brings Psalms for it, which doth not mention Adam,
nor night nor day; and as I said before, thou who art in the shadow,
art intruding into the things thou never saw;
for thou never saw where Adam was before he fell, and therefore art corrected and judged.

[.discourse-part]
P+++.+++ And thou sayst and confessest, '`The Jews`' sabbath was given to the Jews for a sign.`'

[.discourse-part]
A+++.+++ The apostle will tell thee that the body is Christ:
if the sabbath be a sign to the children of Israel, it was a sign of something to them;
for the other signs given were signs of something,
and so something those signs did signify, which thing did end them.
Sabbath signifyeth rest; for the earth shall enjoy her sabbaths.

[.discourse-part]
P+++.+++ And thou sayst,
that '`the inventions of men`'s hearts have blotted
out the remembrance of the sabbath day,
they first cast it out of paradise, and shut it out till Moses`' time.`' And thou sayst,
'`the sabbath was not all a type, or ceremonial.`'

[.discourse-part]
A+++.+++ What is a shadow is a type, and a shadow and type are ceremonial;
when the substance comes it ends, and in him is no shadow, as in James the first;
who is the body, before the days were.
And thou never read that the sabbath was spoken of from paradise until Moses,
and then it was given unto him for a sign through the generations
of the congregations of the children of Israel,
not to gather meat, make a fire, nor bear burdens: so they who come to Christ, the body,
the end of signs, the rest, who was before days were, bear no burdens,
gather not their meat, make not a fire.

[.discourse-part]
P+++.+++ Thou sayst, '`It is an absurd conclusion,
that we must offer sacrifices if we will keep a sabbath.`'

[.discourse-part]
A+++.+++ '`Thou shalt offer sacrifices made by fire, of a sweet sacrifice unto the Lord,
on a sabbath day.`' Numb.
xxviii.
Now offerings were a shadow of Christ, the offering, and the sabbath was a shadow,
and so if ye will observe one, ye must observe the other, and so deny the body,
the substance Christ, the one offering, and so that is ceremonial.

And thou sayst,
the law justified the disciples for plucking the ears of corn upon the sabbath day,
and bringest Deut.
xxxiii.
which speaks nothing to the thing, and doth not mention the sabbath day:
and so Christ the end of the law, who comes to fulfill it, is the Lord of the sabbath.
And the disciples who followed him, in whom they had rest,
saw over the day and the shadow, to Christ the substance,
who forbade them not gathering meat on that day, the sabbath, the shadow,
that was the law; but Christ the end of the law and shadows, the substance,
the disciples that were in him, plucked the ears of corn on that day.
And so Christ did not break the sabbath, but came to fulfill the shadow,
and was the substance, who was the end of it, the lord of it,
and therefore might do what he would, being the Lord of the sabbath;
what had any to do to question him?

[.discourse-part]
P+++.+++ And whereas thou sayst, '`The cripple carried his bed on the sabbath day,
which the hypocrites speak against our saviour for.`'

[.discourse-part]
A+++.+++ The law says,
'`Thou shalt not bear a burden on the sabbath day.`' Now Christ the end of the law,
and the end of the shadow, that fulfils it, and is rest, often gives rest upon that day:
yet he is not a breaker of the sabbath, but a fulfiller, and convinces the gainsayers,
with this: '`Which of you having an ox or ass fallen into a ditch,
would not pluck him out on that day.`' And the circumcision was to be on the eighth day,
on which Christ rose, and on which the saints met in the circumcision of the spirit,
in the spirit which circumcises, which puts off the body of sin, which hath laden them;
in which spirit they have rest and are led withal up to God the father of spirits,
and so come to know the first day, and him who was before it was made.

[.discourse-part]
P+++.+++ And thou sayst, and bringest the apostle`'s words,
'`one man esteeming one day above another, and another esteeming every day alike.`'

[.discourse-part]
A+++.+++ Now the apostle here did not lay any burden upon the saints,
or tell the saints of the sabbath day, nor burden them concerning it;
that if they did not keep it, they should die, as the law says,
but that every man be fully persuaded in his own mind,
and not to judge one another in such cases,
but that every man stand or fall to his own master.
Now these words were spoken among saints by the apostle,
who was leading from meats and drinks, and days, to the truth, to the body Christ;
and so he judged that judgment that was judging one another about the days,
but brought every one to the truth in his own particular,
wherewith he should stand or fall to his own master.
For until they come to see clearly about shadows and signs,
there is the weakness of the meats, of the days,
before they come to see him who was before the days were, the Lord of the sabbath,
and the everlasting offering, where ends the judgment, in whom they have peace.

[.discourse-part]
P+++.+++ Thou sayst '`the apostle says, ye observe meats, and drinks, and days, and months,
and years.`' And thou sayst,
'`will any be so bold as to say he doth reproach the sabbath?`'

[.discourse-part]
A+++.+++ The apostle does not tell the Galatians who were running into circumcision and days,
that they were to keep the outward sabbath; for circumcision was an everlasting covenant,
as well as the sabbath, to the Jews, throughout all their generations:
so they that draw people to circumcision without, and to days, draw them from the body,
(mark his judgment!) and the apostle was not a reproacher,
and was out of the nature of a reproacher.

[.discourse-part]
P+++.+++ Thou sayst, '`Let no man judge you in meats and drinks, and in respect of any feast,
new moons or sabbaths, which are shadows of things to come, but the body is Christ;
but in this bold absurdity some will cast off the sabbath, the seventh day.`'

[.discourse-part]
A+++.+++ The apostle says,
'`the body was Christ,`' and the sabbath was a sign and a shadow of good things to come:
so then this fulfils Moses`' words.
The body is Christ, the sabbath is a sign: so the good things being come, Christ,
the substance, ends the shadow, the sign; and Christ rose on the first day,
on which the saints met, and the apostle doth not call that a sabbath,
nor doth establish the other sabbath among the Christians, nor bid them keep it,
that ye read of any where.
For if that day had been observed as it was in the law time, the seventh,
which signifies perfection, the apostle would have spoken of it somewhere;
for those things that were observable were often spoken of in law and gospel,
but this is no where spoken of,
nor to the saints that they should keep the seventh day as a sabbath,
for offerings were on that day.
But the offerings being changed, the law also changed, and the offering, Christ Jesus,
being come, the law came to be within, and the circumcision within:
and Christ the rest is the Lord of the sabbath, and the rest for the people of God.
And he that holds up sabbaths and offerings, holds up circumcision and works,
and so keeps people from the body and the head, in the signs and shadows,
and so in the works of the law, which the law commands.

[.discourse-part]
P+++.+++ And thou sayst, '`Six days shalt thou labour, and do all thy works of sin,
but the sabbath day thou shalt not sin, thou nor thy son, thy daughter, thy cattle,
and stranger within thy gates.`'

'`To keep thy son, daughter, and stranger from sin;
as for the poor cattle they are nor capable of such a rest.`'

[.discourse-part]
A+++.+++ In the six days thou wast to do that which was just, that which the law commanded,
which was justice, and to do to all men as thou wouldst be done to.
Not to covet, steal, bear false witness, nor kill; the seventh day was the rest,
that signified Christ Jesus, the end of the law, the rest.
If any man can receive this, let him.

And the sabbath day, that all servants, strangers, cattle,
son and daughter might rest upon the seventh day, the sign, the shadow,
which Christ the body ends, was a figure, a sign,
and a shadow of the restoration of the creation to the rest,
whereby the gospel might again be preached to every creature under heaven.
This is a touch of the thing, more might be said of it.

The sabbath was everlasting to the state wherein it was,
and circumcision was everlasting to the state wherein it was, through their generations,
and it was in the first covenant of shadows, types, and figures; but the body is Christ,
that came to do the will of God, which ends them all, and sanctifies man,
and brings him to rest and peace with God, before days were.

[.discourse-part]
P+++.+++ And thou sayst, '`J. E. was instructed in the Old Testament,
which is able to make wise unto salvation through faith;
therefore be instant in season and out of season.
Now the only moral season the scriptures enjoin us is the Seventh-day sabbath,
never changed till the little horn arose.
And the holy spirit in the apostles highly approves us in our fulfilling the royal law,
which, as to the season of worship, is none other than the Seventh-day sabbath.`'

[.discourse-part]
A+++.+++ They who are made able and wise to salvation, know the scriptures through the faith,
they see the substance of them, Christ Jesus; and they see while Moses was read,
the veil was upon their hearts; for the sabbath was a sign and type,
and so was circumcision, and this was in Moses, and this was the sign read,
the shadow was read, the type was read, and the figure read,
the veil being over the heart.
Now as the seed, Christ, the body, comes to be known, the sign, the shadow,
the type is ended, the body is known that doth the will of God,
that brings people to the rest.
So they who know the '`scripture that is able to make wise unto salvation,`'
(mark that word,) through the faith that is in Christ Jesus,
have salvation, which are able to make wise unto salvation that testifies of it;
and so Christ, the seed, the body, that ends the types, figures, and shadows,
takes off the veil from men`'s hearts.
And such as come to know the fulfilling of the royal law according to scriptures,
come to the body, Christ, in which the law ends to every one that believes;
and so they that are in days and sabbaths which Moses says were a sign,
and which Ezekiel and the apostle said were a shadow,
are not yet come to the body which is Christ, who was before any days were,
who is the sanctification and rest of his people, and who are in him that is the truth,
worship God in the truth and in the spirit, which never change.
But shadows and signs of a thing are not the things signified;
for signs and shadows will change, but the spirit and truth do not change,
in that is God worshipped.

[.discourse-part]
P+++.+++ And thou sayst, '`It cannot be that horn, except he change your times also,
and that he had no time to change but the Seventh-day sabbath,
and the sabbath is perpetual, a rule of righteousness.`'

[.discourse-part]
A+++.+++ Christ made all things new; he ends the law, and brings it in the heart;
he ends the covenant, and changes things that were in the old time,
changing circumcision, offerings, priests, and ends the sabbath,
which was perpetual to the Jews in that generation, among the types, as the covenant was,
and circumcision, and the law was a rule of righteousness for them; but Christ,
who is the end of the law, comes to redeem them that are under the law,
and ends their covenant, and ends their shadows, and changes those times;
he by whom time was made.
And so thou that knowest not the time in his hands,
showest thou art not in the time that is in his hands, and so not of the body, of Christ.

[.discourse-part]
P+++.+++ And whereas thou sayst, '`No other time but simply the seventh part, must,
from week to week, he devoted to God`'s worship;
for whensoever the seventh part of time is altered, the morality must be destroyed.`'

[.discourse-part]
A+++.+++ They worshipped God, that said the body was Christ,
and the sabbath day was a shadow of good things to come;
and so they that worship God must worship him in spirit and in truth,
and in that which doth end all figures, and shadows, and signs,
in the spirit and truth before they were, and not one day in seven,
a signification of rest, of sanctification,
the Lord`'s sign which he gave to the people in transgression.
Before transgression, ye do not read it was given to men as a command to the first Adam,
but of the earth, earthly; but who comes to the second Adam, the Lord from heaven,
he by whom the world was made, comes into that that ends all types, figures, and shadows,
and so doth destroy nothing of the law, but comes to that which ends it.

[.discourse-part]
P+++.+++ And thou sayst, '`It is a great stumbling block as to believers in Christ,
because christians violated the sabbath.`'

[.discourse-part]
A+++.+++ Christ is the body, that ends the shadows and the signs, and fulfils the law;
he who was before the world was made, in him are the christians,
the body that ends the shadows and the signs, in whom the veil is come off their hearts;
and so Christ did not break the law, but fulfilled it, and in him that fulfils it,
the saints met, who met together in him, and gather together in him, who is the body;
they are the members, he is the head, who are the church, whom he is in the midst of.

[.discourse-part]
P+++.+++ And thou sayst, '`So that to produce the world of wonder,
manifest it is that night was the beginning of time.`'

[.discourse-part]
A+++.+++ That is false; the beginning of time was God and Christ,
and times and seasons are in his hands, and God is light; read that who can.

[.discourse-part]
P+++.+++ And thou sayst, '`Thou supposest it will not be questioned in Moses`' time.`'

[.discourse-part]
A+++.+++ This was while Moses was read, while the body was not come, Christ Jesus,
that ends the sign, the shadow, the type,
and blots out the ordinances and commandments that held them up,
from which veil the apostle brought the people, to the body, Christ Jesus,
where no shadow was, nor changing.
Now days are changing, but Christ doth not change who is the body.
And you that hold up the sign, the shadow, the type, the figure, you hold up the dead,
and come not to Christ the life, the body, the sanctification itself, before days were,
by whom they were made.

[.discourse-part]
P+++.+++ And thou sayst, '`The unthankful christian ought to sanctify the sabbath.`'

[.discourse-part]
A+++.+++ Here thou bringest them into days, from the body which is Christ,
and so bringest them into days, and shadows, and types,
where the veil is over their hearts.
And the false christian may run into signs and days who is out of Christ`'s life,
and the apostles`'; but who are in the life of Christ and the apostles,
that are in the body, out of the signs and shadows, and offer up spiritual sacrifices,
such are in the rest, and have the high priest, the everlasting priest, Christ.

Now if ye have the sabbath, ye must have the offerings, and the priest to offer,
and your altars, and ye must offer upon that day; but the christians witnessed the body,
Christ Jesus, the one offering, who comes as it is written in the volume of the book,
to do the will of God, who is the substance that the shadow, and signs,
and figures gave forth, who ends them all,
and brings people to see to the end of the shadow, to perfection, to Christ Jesus.

[.discourse-part]
P+++.+++ Thou sayst,
'`We should not grudge to give God every First-day
as an addition to God`'s Seventh-day sabbath.`'

[.discourse-part]
A+++.+++ The priests call it a sabbath, and you call it a First-day,
and you would have a sabbath besides.
Now this is your cover, but the life takes away all your shadows.
It is true, the saints did meet together every first day of the week;
and the saints do so, though they do not say it was a command.
And so the apostles brought people off from observing days and times,
and told them the body was Christ, and the sabbath was a shadow of good things to come.
Thou mayst say, the apostle was the little horn that changed times;
we find no where he commands the saints to observe it, but brings people,
as you may read in the Romans, from the law, being justified by the law;
for if they kept the sabbath they were justified; if not, they were condemned.
So Christ the body, the end of types, figures, signs, and shadows,
is the justification without the works of the law, and the sanctification itself,
and sanctifies man to God.
And so the christians no where, as you may read through the epistles,
did observe the days, the shadows, who were believers in Christ, who owned the body.

[.discourse-part]
P+++.+++ Thou sayst, '`Since the blessed Creator celebrated the seventh day,
man thinks to be wiser than his Maker, in altering and disobeying,
pretending spiritual observances; poor worm, dust, and ashes.
Christ, in expounding his own law, sums up all in this: be ye therefore perfect,
as your heavenly Father is perfect, that is in quality, not in quantity.`'

[.discourse-part]
A+++.+++ He that is perfect, as his heavenly Father is perfect, is perfect as he is perfect.
If thou or any have an ear to hear, let them hear;
and lay away thy qualities and quantities, and take the words as they are.
And all that are come into Christ, are come into life, from the dust and ashes,
and are spiritual men.
But they that talk of celebrating days, and sabbaths,
who are celebrating signs and shadows, are in their own works, from the body of Christ,
and keeping others there.
Such, if they do not all the works contained in the law, are accursed.

[.discourse-part]
P+++.+++ And thou sayst, '`Christ confirms the Seventh-day sabbath,
and assures us it shall continue, every jot and tittle,
and Paul says he established the law, which cannot be ceremonial:
therefore let such as slight the Seventh-day sabbath, take warning,
and make sure work that it be not broken, in no point of the law,
of which every jot and tittle is established by Christ and his apostles;
when the Lord of the sabbath, and the saints,
endeavoured to observe every jot and tittle of it to the end of the world,
and our Redeemer particularly owns the sabbath, above all other days, by his works,
and miracles, and great wonders on that day.
And God forbid that saints should side with evil seducers,
and reproach our saviour for putting on his glory on that day,
but rather let that sabbath be celebrated.`'

[.discourse-part]
A+++.+++ Christ came not to break the law; the apostle said the law was good in its place,
and he established it; yet the apostle says that the sabbath was a shadow,
but the body was Christ, and he brings them to the law in the heart, in the mind,
and there he established it.
And Christ did not come to break one jot or tittle of it, but (mark) to fulfill it;
and he said,
'`not one jot or tittle of the law should be broken until fulfilled.`' And Christ,
who is the rest to the Jew, who had the sabbath day, a sign of rest,
gave the people rest on that day often, that were bound, burdened,
or wearied on that day; and Christ, who did give them rest on that day, and the apostle,
who establishes the law, which was good in its place,
neither of them doth bid keep the sabbath day.
Christ doth not say, the sabbath day must be kept; and after him,
the apostle nowhere commands it, but says it was a shadow, and the body was Christ.
And so they that came to the body, Christ, in the days of the apostles,
were come to the end of the shadows, in that age, in their day; and for example,
thou may see it, for some did observe a day, and some did not,
and they were not to judge one another about those things.
And Christ giving rest on that day which the people were to rest on,
was a figure of the everlasting rest, and of the restoration;
who did the work of God on that day, and gave rest to the burdened on that day,
that signifies an inward rest; for Christ was the rest, and Lord of the sabbath,
the rest to the people of God.
And they that celebrate the sabbath day, must celebrate a sign,
and live in the shadow that keeps them from the body, and so from the church,
which Christ is the head of.
And who are celebrating sabbaths must also bring their offerings,
and then they must have the first priesthood to offer,
and so deny the body that doth the will of God, the everlasting priesthood,
and the one offering, and hold with the first covenant that must decay,
in which those things stood; and deny the everlasting covenant,
and him that blotted out ordinances, and ended types and shadows.
And so Christ is the end of the law to every one that believes, in every jot, and tittle,
and print of it; and the signs and shadows that were held up by the law,
Christ is the end of; yet the life of the law, the power, remains,
though the outward changing shadows and things, end,
the body is that which ends them all.

[.discourse-part]
P+++.+++ Thou sayst, '`The sabbath was honoured with the conversion of souls on this day,
and the day before did they break bread together.`'

[.discourse-part]
A+++.+++ Was that the sabbath day that Christ and his disciples break bread together on?
Did the apostles and the saints establish the sabbath day, when they said,
it was but a shadow, and brought them to the body, which is Christ?

[.discourse-part]
P+++.+++ Thou sayst, '`The sabbath is mentioned with new moons, and sacrifices;
that the actions, baptism, and breaking of bread, are the signs of a Christian sabbath;
it is high presumption to alter the word of God,
in calling every day the Lord`'s sabbath, and honouring any other day as the sabbath.
So if we be followers of God, as dear children, and take the spirit to be our guide,
we must honour the sabbath with all holy devotion.`'

[.discourse-part]
A+++.+++ The sabbath is mentioned with new moons and sacrifices,
but the apostle says they were shadows of good things to come; when this is come,
which was before the shadows were, which is the body, Christ, who was before days,
new moons, or sacrifices were, the body, who be in that ends them all:
and to that the apostle brought people, and not to the days.
Now there were some brought them to observe days,
and he was afraid of them that did observe them, and he brought them to the body, Christ,
to whom all the angels did bow; for they that observe days, new moons, and sabbaths,
and are worshipping of angels, neglecting the body, which is Christ,
and this was for the satisfying of the flesh.
And now what art thou satisfying, who art teaching to observe days, signs, and shadows,
which the apostle brought people off, to the body, and to the head, Christ Jesus?
and to worship God in spirit, and brought them into that that ended all shadows;
for the devil will lurk in a shadow, or a type, or a sign, or figure,
and creeps into those things, after the substance is come, to keep people from the body,
and will persecute such as will not bend to the shadow, and come from the substance.
And breaking bread, and baptism, are no sign of the sabbath day,
of the Jewish sabbath day.
The sabbath was a figure of the rest, and sanctification of the creation;
and breaking of bread among the saints was a figure of the bread, Christ,
of which the saints eat, and live forever.
And the word of God cannot be altered, and the word of God cannot change; man may alter,
but the word of God cannot be altered, but abides and lives forever.

And the saints who come to the body, Christ, come to honour him who ends the sabbath,
which is a sign, and a shadow; and such honour God the Redeemer and Creator, and Christ,
by whom all things were created and made.
And who are the dear children of God the apostle speaks of,
he did not bring them into days, and to observe sabbaths, and signs,
but brings them to the body, Christ, the Lord of the sabbath;
and doth not set up that which thou calls devotion, in holding up the Jewish sabbath,
on which they should rest, and which was a sign; the rest of the creation,
and the rest of all mankind, cattle, and beasts;
that God would restore and redeem all things by Christ, who is the word, and gives rest;
and is the sanctification, and gives rest to the whole creation.

[.discourse-part]
P+++.+++ Thou sayst, '`This is the time of God`'s worship, observing the seventh day.
Christian, look well to thy walkings,
see that thou make all things according to the pattern in the mount.`'

[.discourse-part]
A+++.+++ They that worship God, come into Christ, the truth, the body,
who ends the sign and the shadow, and who is the end of Moses, who made a pattern,
which was a figure of that which was to come, and he made it at the command of God.
And Christians are not to make the pattern, which was showed to Moses in the mount,
for while Moses is read, the veil is upon the hearts of Christians,
and of all people whatsoever that are in the sign, shadows, and figures:
the body is not seen, nor come to, which is Christ.
And Paul, and the saints, the true Christians, worshipped God in spirit and in truth,
who witnessed they were in the body, that ended the shadows, and types, and Moses,
the law, and the prophets, in Christ Jesus, him by whom the world was made,
who was before it was made; and a pattern is not the thing,
there is the thing the pattern is of, and that ends the pattern and lives in the thing,
and they need not have the pattern, for the pattern was made of a thing that was to come.

[.discourse-part]
P+++.+++ Thou sayst, '`If the apostle of the Gentiles, who was the rejecter of the ceremonies,
did constantly celebrate the Seventh-day sabbath,
then much more those apostles among the Jews:
there is not a plainer precept in all the scriptures, than Paul`'s practice herein,
for the Seventh-day sabbath.
If we tread in the steps of Paul, he was but a man, and sometimes a very angry man,
and he strictly requires all believers to follow his example, as he followed Christ,
and certainly in observing the sabbath.
And Paul reasoned with the Jews on the sabbath day, and Christ`'s custom, and Paul`'s,
was to go into the synagogue on the sabbath day, and was there difference betwixt,
Christ`'s preaching and Paul`'s? and where is the
difference between Christ`'s observing the sabbath,
and Paul`'s?`'

[.discourse-part]
A+++.+++ The apostle never taught the Christians, either Jews or Gentiles,
to celebrate the seventh day, nor ever mentions it to them to keep it;
in all the epistles there is not such a thing; but he tells them they were shadows,
and that the body was Christ;
and Christ`'s and the apostles`' going into the synagogues
and temple on the sabbath days,
was to fulfill, and show the fulfilling of the types, and figures of him,
and to bring to the substance of the signs, types, and shadows; not to hold up days,
times, and offerings, but to bring them to the body, Christ; as Col.
ii. And so Paul and Christ do not disagree, for he preached Christ the end of the law,
and the substance; and though Paul went among the Jews, and circumcised,
and did several things; though he went into the temple,
yet that was not to hold up the temple, or to hold up the offerings, types, and shadows,
but to bring them to the substance.
And mind what the anger was that Paul was in, and Paul followed the substance,
and was more than a man, there was more in him than a man.
Neither Paul nor the apostles any where commands
the saints to observe the Jews`' sabbath day,
though he went unto the Jews,
and consented to many things to the intent to bring them out of them,
not to keep them in them, but to bring them to the substance,
and that was the end of Paul`'s going into the Jews`' synagogues and temple,
to bring them out of the shadows, types, and signs, to the substance;
and the end of Christ`'s going thither, was to bring them to the substance,
that which was typed forth, that people might believe in him, who was the body,
who was before heaven or earth was, who fulfils every jot and tittle of the law.
And to him did the apostle bring the people, to this body, which types,
signs and shadows, signed, shadowed, and typed forth, the body of which is Christ;
and in thy principles thou art confused.
And so who follows the apostle comes to the body, out of the sign, and the types,
and figures, and shadows, as every believer follows him, he comes to the body,
and from the observing of signs, and shadows, and sabbath days, to Christ the son,
the end of them all.

[.discourse-part]
P+++.+++ Thou sayst, '`Fancy is no fuel for a christian faith.`'

[.discourse-part]
A+++.+++ Fancy and fuel are out of a christian faith; which thou art in,
that art got among the signs, types, and shadows in the fancy,
and so from the body Christ.

[.discourse-part]
P+++.+++ And thou sayst, '`If the Lord be thy God;
thou must observe the Seventh-day sabbath.`' And thou sayst,
'`It is antichrist that persuades to change the day,`' and thou chargest
them '`to do no manner of work on that day,`' and thou sayst,
'`It is not ceremonial, but was before Jew or ceremony had a being.`'

[.discourse-part]
A+++.+++ The sabbath was not before Adam was; and the apostles,
that had the law of God written in their hearts, served the Lord God, he was their God,
and they his people, who witnessed the end of the first covenant,
which stood in ceremonies; and so shadows and signs are ceremonies.
And the sabbath was spoken of before ceremonies were, that is true;
but not as a command then, but when ceremonies came up in the days of Moses,
the sabbath was given as a sign amongst the other signs,
and a shadow amongst the other shadows; and he tells you plainly,
if you will believe him, the body of all is Christ.
And this sabbath,
which was before ceremonies were given among them that had the ceremonies,
a day of rest for cattle, man and beast, strangers and servants,
which the body of this shadow and sign is the rest, that gives rest to all the creation,
man and beast, stranger and servant, and so rest to the whole creation.

And the apostle was not antichrist, that said the body was Christ,
and the sabbath was a shadow, and brought them off from days and from signs, types,
and ceremonies, and from the first priesthood, first covenant and offerings,
to the body Christ, that ended them all,
and takes off the veil that is upon the hearts of people while Moses is read.
Now they are the antichrists that are setting up signs and shadows,
and bringing people from the body, which is Christ, the substance,
and are keeping people in the observing of a day
in which people should have rest for a day,
the cattle rest for a day, servants rest for a day, not minding the substance, the body,
Christ, who restores the creation into unity, as it was in the beginning;
and gives rest to man and beast, servant, stranger, and cattle, and is rest to them all.
They that are come to the body know the substance, the end of the sabbath-day`'s work.

But then again thou sayst in thy charge,
'`ye may not do any work on that day.`' How is it
then that ye make fire through all your congregations?
How is it you keep markets on the sabbath day, which God commanded?
How is it that ox and horse bear burdens on that day, and you both?
How is it that you gather sticks and make fires on that day,
and gather your meat on that day, when meat was not to be gathered on that day,
and he that gathered sticks was stoned to death?
And how is it that ye profess a day, and do not observe it according to the day?
Are ye not all hypocrites in this, professing that which ye do not practise?
For by the law ye should be stoned to death, ye should die all.
And how is it that you professors, likewise,
that profess the first day to be the sabbath, yet will not go to your worships,
abundance of you, except ye be drawn with horses?
Why pollute you the sabbath day?
Ye are all polluters, according to your own words.
And why gather ye your meat, and make fires on that day?
Keep it according to the law, and be not dissemblers and mockers of God and man.
If ye will keep a sabbath, go according to scripture and the law of God.

And the poor creatures must bear a burden to lug you to your worships;
and yet if a poor man be found but carrying a loaf of bread,
or a burden of sticks to make him a fire, he is, it may be, fined for it.
Now by the law of God, he should he stoned to death,
and your horses should do no work on that day.
And you will fine some for going to a meeting of the Lord`'s people,
yet you must have your horses and coaches, and coachmen,
and put them to labour to draw you to your worships; and so here is your confusion.
And so you are judging one another in days, which was not the saints`' work,
nor the apostles`', who witnessed the body was Christ,
and met together in him who was the end of days.

[.discourse-part]
P+++.+++ Whereas thou sayst, '`The sabbath is perpetual, and fenced above all other laws.`'

[.discourse-part]
A+++.+++ If it had been perpetual, the apostle would not have said it was a sign,
and that the body was Christ; but to the Jews that had the types, it was perpetual.
By them it was highly to be observed; but Christ that ends the law, ends that,
and the things that are in the law, the shadow and sign that are in the law,
who was the body of it.

[.discourse-part]
P+++.+++ '`The Jews received the lively oracles from mount Sinai.
Whether was it given us to be broken or kept, slighted or observed?
If to be kept and observed,
then we must either deny the Seventh-day sabbath
to be one of mount Sinai`'s lively oracles,
or deny Stephen`'s doctrine, delivered to the Jews.
We must sanctify this lively oracle of the Seventh-day sabbath.`'

[.discourse-part]
A+++.+++ Stephen preaches Christ, the end of the law, of types, figures, and shadows,
who is the substance, and showed the Jews that they had not kept the law,
in which were the shadows of Christ, and so Christ is the end of the law, and the signs,
and the similitudes, and the days.

And Stephen saw the end; Hagar or Sinai is a mount in Arabia,
and answers to Jerusalem which now is, and is in bondage with her children.
Now read where you all are.
But '`Jerusalem above is free, which is the mother of us all.`' Now mark, us all,
who are come to the body, Christ, the end of the signs, shadows, and figures,
(Jerusalem below had types, had figures, had shadows,
had signs,) when that resteth that is in bondage, Hagar with her children.
And here you may come to know the allegory of these two covenants;
and so who is come to the son, to the body, is come to the end of all shadows,
and before any shadows were.

And Stephen held not up the shadows, but preached Christ, the end of them,
only he judged the Jews that had not kept the law,
which Christ is the end of to every one that believes.
And Stephen was a believer, and they accused him for speaking against the law and Moses,
who witnessed the end of it.

[.discourse-part]
P+++.+++ Thou sayst, '`There is a conceit, that the disciples in assembling on the First-day,
did celebrate the sabbath.
And they were so far from believing that Christ was risen,
that it seemed to them as idle tales.
The First-day was finished before they believed,
and so they could not have faith to do any such thing.`'

[.discourse-part]
A+++.+++ The scriptures speak no such thing, and tell us no such conceit,
that the disciples did celebrate the first-day to be the sabbath;
but this is thine and your imaginations, got up among you that own not the body Christ,
who ends all signs, types, and shadows.
Christ was before days were, and who lives in him doth not celebrate days.

[.discourse-part]
P+++.+++ Thou sayst, '`John intends a single day, it is much like it was the sabbath day;
and he speaks of the Lord`'s day, judgment day, and this he calls the day,
and this day he must show unto John in the vision.
The ancient Christians who call it the Lord`'s day, did never term it the sabbath.
But religiously celebrated the Seventh-day with it.`'

[.discourse-part]
A+++.+++ John doth not call it the sabbath day,
nor did the Christians celebrate the sabbath with it,
but said the old was signs and shadows, the body of them was Christ;
but since the days of the apostles and the apostacy, ye have wanted the body Christ,
and ye have fallen into the days; for Christ saw those that should come up,
and draw people into the days.
And the day of the Lord is light, and in the day of the Lord was John.

[.discourse-part]
P+++.+++ Thou sayst, '`Old things are passed away, and all things are become new.`'

[.discourse-part]
A+++.+++ Then the sabbath was a thing, and it must pass away; and it was a rest,
and we most have a new rest: and the sabbath was in the old time given as a sign,
and a command, and given by God to be kept since the fall.

[.discourse-part]
P+++.+++ Thou sayst,
'`There remains therefore the celebrating the sabbath to the people of God.`'

[.discourse-part]
A+++.+++ But the scripture of the New Testament doth not say so.
The apostle says,
'`There remains therefore a rest for the people of
God,`' such as come off the signs to Christ the body,
the soul`'s rest; there remains in him a rest for the people.
And such as celebrate the sabbath, rest in the shadow,
and do not come to the body Christ,
and such are not the believers that do enter into the rest Christ.
And such as rest in the sign and shadow, and there remain, celebrating the sabbath,
come not into the body, Christ, the rest of God`'s people.

[.discourse-part]
P+++.+++ Thou sayst, '`Christ rested, or ceased from his great work, and entered into his rest,
and this is laid down as a gospel reason why the sabbath remains to the people of God.
And he lays the believer under a double engagement to sanctify the Seventh-day sabbath.`'

[.discourse-part]
A+++.+++ Christ speaks no such thing, nor the apostles either,
that they should sanctify the Seventh-day, he speaks no such thing to the believers;
but the apostle brings them off from the shadows, from the signs,
and shows them the body of all, and he does not mention a double engagement;
and the sabbath, the Jews were to rest on, which was death if not kept,
was a figure of the redemption, Christ Jesus, the rest,
who was put to death on the Sixth-day.
Man was made on the Sixth-day, and he was put to death on the Sixth-day,
and he was crucified through the means of them that had the shadows, the outward day,
the outward rest, from which day they should have come, from the signs and shadows,
to the body Christ, who was the rest and restoration of the creation.

[.discourse-part]
P+++.+++ And thou sayst,
'`To hold forth the passage over of that rest which prevented
the women from the application of their spices,
that was the sabbath, and I am satisfied the Seventh-day is the sabbath day.`'

[.discourse-part]
A+++.+++ Now though the women did rest on the sabbath day,
and came with their spices on the First-day,
there were many of them did question whether this was the man that should redeem Israel;
and so that is no ground at all to hold up the Jews`' types and shadows,
for Peter denied him; therefore that is no ground.
But what did they do after the holy ghost was come to endue them with power from on high?
And what says Paul?
He brings them off from the signs and shadows to Christ the body.
Though there is much more to be said to this; for while the questioning stands,
the questioning part doth pertain to the shadows and types, which the body ends,
and with that is felt and seen, in which there is no changing, nor shadow,
nor variableness, nor altering, and that overthrows the questioner, unbeliever, stumbler.
The great stumbler was the Jew that was resting in the shadows, types, and signs,
he stood against the body Christ Jesus.

[.discourse-part]
P+++.+++ Whereas thou sayst,
'`The Seventh-day sabbath is one of the lively oracles Israel received from Sinai,
given to us.
O christian! Remember it, and love it in thy bosom.`'

[.discourse-part]
A+++.+++ Here thou wouldst bring the children from her mother above, which is Jerusalem,
to Jerusalem below, and Sinai, and so to Hagar, into the shadow;
but the christians witnessed the end of the shadows and sabbaths,
and witnessed the body Christ Jesus, and Jerusalem that is above, and came to Christ,
the end of the law, and into God by him, from whom the law came.
And so christians that have Christ within them, cannot put signs in their bosoms;
no type, shadow, or figure in their bosom; and cannot touch the doctrines, commandments,
and ordinances of men, which have a show of wisdom in the will-worship; and the Jew,
the outward Jew, had types, shadows and figures; the Jews inward witnessed the substance,
who are the true christians, the law in their hearts, and circumcision there,
and the end of the law they came into, and entered into the rest, Christ Jesus,
that is not an outward Seventh-day; but entered into rest,
'`ceased from their works as God did from his;`' these that enter into rest,
cease from their own works, and the type, the figure, the Seventh-day sabbath.
'`Do no work, thou, nor strangers,
nor the cattle,`' and so the sabbath was a rest from all.
This was a type, and God gave them the sabbath for a sign,
(who hath ceased from his own works,
enters into his rest,) a figure of the restoration of the creation of Christ, the rest,
the restorer, redeemer, and saviour, that brings peace on earth.
And so they that believe have entered into him, into the rest Christ,
the rest to all wearied souls, who helps all creatures upon the earth, man and beast,
and destroys the cause of all oppression; and so many are come from Hagar.
And though the Seventh-day in the law was a rule among the Jews, a true type,
yet the apostle that preaches Christ, the end of the law, brings people to the body,
Christ.

[.discourse-part]
P+++.+++ Thou sayst, '`Circumcision nor uncircumcision, but keeping the commands of God,
viz. of sanctifying God`'s sabbath.`' And thou sayst,
'`The seventh angel sounded forth the ancient of glory, the Lord`'s sabbath,
swearing that time should be no longer.`'

[.discourse-part]
A+++.+++ Circumcision was a command of God, and so was the sabbath, and they that love God,
keep his commandments.
And did not the apostle bring people off circumcision, and from the signs and shadows,
the sabbath days, and told them the body was Christ?
And were not offerings and sacrifices the commands of God?
Now they that love God, keep his commands,
and those are believers that have passed from death to life,
and have come to the end of the law and the prophets.
And the angel in the Revelations, makes no mention of a sabbath there;
but many are come to witness him to whom the angels must bow down,
who saw the end of time, and the beginning of time, and the supper of the Lord,
and the rest, and the temple of God with them,
and heavenly Jerusalem '`come down from above.`'

[.discourse-part]
P+++.+++ Thou sayst,
'`It cannot be but God`'s people must bethink themselves
of this doctrine delivered by Stephen,
to the sanctification of the Lord of the sabbath.`'

[.discourse-part]
A+++.+++ Stephen no where mentions the sabbath day in his examination,
though he judged the Jews for not keeping the law, which they had received,
but persecuted the Just One: so he preached the substance, Christ, the end of the law,
and said they had not kept the law, but turned against the Just, and persecuted him.
He did not establish the Jews in their ceremonies, signs, and types;
but Stephen brings them to the substance.
And so God that gave forth the law with types and figures and shadows
in it to the weak capacity of people in their transgression,
sent his son to redeem them from it, and to end the types, figures,
and shadows in the first covenant; who is the new and living way,
in whom is no changing and shadows, no variableness nor altering, no turning.

[.discourse-part]
P+++.+++ And thou sayst, '`sin is double on the sabbath day?`' And thou sayst,
'`conceive a sabbath-day`'s journey is so far as
a person may ride to go without toil to a meeting.
So where there is no law there is no transgression,
and the extent is left to the conscience.`'

[.discourse-part]
A+++.+++ How now, must the beast bear a burden?
Where doth the scripture say that thou wast to ride upon the sabbath day?
Do the beasts work then?
He says, '`Thou shalt do no manner of work: but six days shalt thou labour,
and do all thou hast to do.`' And you that make sabbaths, and set up the old sabbath,
and do not keep it according to the law of God,
with the law of God you are judged and condemned, if ye do not fulfill it in every point;
and they that believe Christ is the end of the law, to them he is the body,
which is the end of the shadow.

[.discourse-part]
P+++.+++ Thou sayst, '`That the Jews that were not to make a fire on the sabbath day,
this was mentioned of the ceremonial law, and so concerns not christians,
and so not in danger of stoning.
It is the revealed will of God,
that we should not turn our foot to the defiling the sabbath.
When the six days are done, be sure thou do not turn thy foot to pollute the sabbath.`'

[.discourse-part]
A+++.+++ And dost not thou confound thyself in this, and turn thy foot to pollute it,
and sayst, it is the ceremonial law that commands it?
And they that gathered sticks, and made a fire, were stoned to death:
did not they pollute it?
And dost not thou say it doth not concern the christians,
and they were not in danger of stoning?
And so hast not thou taught them to break the law and the sabbath both, and pollute it,
and so hast overthrown all thy doctrine in thy book, and confounded thyself?
And doth not he that goes out and gathers sticks and makes a fire,
turn his foot from the sabbath?
For he that went out to gather sticks, broke the sabbath day, and was cursed,
and stoned to death: for no fire, no meat,
no burdens were to be borne on that day of rest, a figure of the everlasting rest,
wherein no meat is gathered, no fire is made, no burden is borne,
and there is no turning the foot, but all walking in rest and peace;
and so I find thee neither in law nor gospel.

[.discourse-part]
P+++.+++ Thou sayst, '`But to be sure the law was made for Christ`'s disciples.
Whosoever boasts of a light within, and speaks against this law of the sabbath,
hath no light in him.`' And thou sayst,
'`Quakers will not admit of this royal law as a rule of righteousness,
but pervert the scriptures, which say, the law was not made for a righteous man.`'

[.discourse-part]
A+++.+++ The disciples of Christ,
the law was not made for them that came to witness Christ the end of the law;
for they said plainly,
'`the law was not made for the righteous.`' And '`Christ is the end of the law
to them that believe for righteousness`' sake.`' And the Quakers witness Christ,
the end of the law, for their rule of righteousness, and do not pervert the scriptures,
but are the believers in him who ends the law, and who was before it was,
and is the body which ends the types, shadows, and figures;
and they that draw people under the law, and the types, and shadows,
and figures from the light within, do not know law or gospel; for the law is light,
and the gospel is the power of God, and such as witness Christ the end of the law,
witness the end of the sabbath.

[.discourse-part]
P+++.+++ Thou sayst, '`Among all God`'s laws,
none sets the soul more at liberty than the fourth lively oracle.`'

[.discourse-part]
A+++.+++ And yet thou sayst, men may make a fire and not be stoned,
and so thou teachest to break it; and thy horse may bear a burden.
And so dost not thou pollute it here, and destroy thy own soul by thy own judgment?
But I tell thee, Christ is the bishop of the soul, who ends the law,
and brings the law within, into the mind and heart:
so now the soul being subject to the higher power,
the power by which all the changeable things are held up,
that power remains when all the changeable fails, and decays, and ends,
and the soul witnesses that, and the body of Christ, the power, stands.

[.discourse-part]
P+++.+++ The sabbath '`was intended to righteous Stephen and all his followers,
and is designed to all persons, to whom the supper, is joined; the sabbath is a precept,
ancient and universal, both for Adam a public person, and for all his posterity,
but none can sanctify the sabbath saving Christ`'s disciples.`'

[.discourse-part]
A+++.+++ Stephen suffered death for witnessing against the shadows,
and witnessing the substance, and the apostle no where joins the sabbath with the supper,
but Stephen saw Christ the body, in whom was the rest, in whom he entered;
and the saints that come to sup with the Lord, and are supping with him,
come into the body, which is the end of all types, and shadows, and signs,
as are sabbaths, and have seen them flee away, and are come to the beginning,
before the world was made, him who was before signs, shadows, and types were.

The sabbath was not given to Adam in the beginning,
who had the dominion over all creatures living, but to Adam`'s posterity in the fall,
a sign when they came to receive the law of God, the types, and shadows, and figures,
which they were to rest on, a sign of rest.
But when Christ came he gave rest to the day from
the inward burdens that men were bound under;
the apostle that preached him who was the body,
that took off the nature which caused the oppression and transgression,
preached the end of the shadows, types, and figures.
And so the disciples which were in the rest, Christ, in the body,
they were in the sanctification;
and the apostle no where speaks that the disciples
did sanctify the seventh day and bid people do it.
But thou dost not sanctify the seventh day, that bids people make a fire,
and so art a breaker of it, and preaches up that people should break that,
which thou affirms should be kept holy.

[.discourse-part]
P+++.+++ Thou sayst, '`There are already many signs of displeasure upon sabbath breakers,
against the oracle of God; labouring with all their might against it,
in the birth upon Quakers: yea, the Galileans were great sinners, but I tell you,
except you repent ye shall all likewise perish.
'`And thou compares them to the sow wallowing in
the mire`' that go from the sabbath of the Lord.`'

[.discourse-part]
A+++.+++ This thou mightest turn upon the apostles who brought the people off from types,
figures, signs and shadows, to the body, Christ, and to the end of the law,
and told them all things must become new, +++[+++mark]
'`all things become new.`' What! Wouldst hold up any old thing?
What! A new sabbath then?
and have the Quakers been persecuted, for witnessing the body Christ?
is he persecuted?
They go in the wallowing mire like swine, and like the prodigal feeding upon the husk,
who go into the signs and shadows, and from the body, Christ, the life, the substance,
and come not to the rest, the body, and hold not the head.
And so they satisfy the flesh, and run into the mire, and wallow there,
and are satisfying it; and such are the intruders, worshipping angels, will-worshippers,
without the body.

[.discourse-part]
P+++.+++ Thou sayst, '`The seventh day is a perpetual royal rest,
established by precept and precedent, for God`'s praise and saints`' privilege:
the unchangeableness of the Seventh-day sabbath.`'

[.discourse-part]
A+++.+++ It was so to the Jews in their generation;
perpetual to them in the generation where they were, and so was circumcision,
and so were the offerings; but Christ by whom the world was made,
came to end the offerings, who is the rest to weary souls and takes off all burdens;
who is the everlasting rest, and restores the creation,
and ends the Jewish signs given as a sign and shadow of the body, Christ,
him by whom the world was made, who was before it was made,
and so he changes the covenant and priesthood, and ends the law, ends the shadows,
who believe in the body Christ, are entered into his rest,
and there is the saints`' privilege.

[.discourse-part]
P+++.+++ Thou sayst, '`When will the new moon be gone that we may sell corn,
and the Sabbath day that we may set forth wheat?
All the discipline of the gospel calls for self denial,
as this weekly duty of the holy sabbath;
the christian complains for want of spiritual enjoyments with Christ,
and acquaintance with Christ; the sabbath opens the door of the holy of holies,
and is as a spring of spiritual joys.`'

[.discourse-part]
A+++.+++ In the time of the law and prophets, they were crying up new moons, and sabbaths,
which were shadows, types, and signs: but the saints denied themselves,
and were come to the body, and did not set up weekly duties of the holy sabbath,
but said they were shadows, and came to see the end of sabbaths, and new moons,
and witnessed the body, Christ, who was before the day was made, in whom is the rest.
And the christians who are complaining for want of spiritual enjoyments,
and acquaintance with Christ, are such as are among you that are in the shadows,
and come not to the body Christ, in whom there is communion and life;
for the body is the light of the world:
the body is the life given for the life of the world in whom there is rest, yea,
to them that had the true sabbath, which was the sign they were to rest on.
A sign, a shadow, is of something that is to come;
therefore the sign and shadow is not the thing;
and they that live upon the sign and shadow,
and cry them up,
keep from the door of holies where all the springs of spiritual joys are,
in which all the signs, and shadows, and types, and figures ended, in Christ,
who was before they were; in Christ, by whom the world was made,
before shadows and types were.
And a great deal more confusion is there in thy book not worth mentioning,
but will fall into the mire and the dirt with thyself.
Therefore now thou hast time, prize it, and give over deceiving the people;
for thou art wallowing in the mire thou speaks of, and would bring people thither,
into the shadows from Christ, the body, the substance, and life.
