[.style-blurb, short="Some Gospel Truths Opened"]
== John Burton, and John Bunyan, who call themselves ministers of the gospel, in their book called, [.book-title]#Some Gospel Truths Opened.# Their principles are as followeth.

[.discourse-part]
_Principle._ They say, '`To witness Christ manifest in our flesh,
is to deny Christ come in the flesh.`' And say,
'`that Christ saith he shall be absent from his apostles touching his body.`'

[.discourse-part]
_Answer._ Contrary to Christ, who said that they might eat his flesh;
and contrary to the apostle, who said that they were of his flesh and bone.
So they do not divide the word aright.
And to witness Christ within is not to deny him come in the flesh, but to witness him,
and such are not absent from him.

[.discourse-part]
_Principle._ And they say,
'`Others have been depending upon something that
they call the righteousness of Christ within,
and Christ within them;`' and this they say '`is opposite to Christ
without,`' and this they call '`the spirit of the devil.`'

[.discourse-part]
_Answer._ Which is not agreeable to the apostle`'s doctrine, but contrary to the apostle,
who said, '`he was manifest in his flesh, to condemn sin in the flesh,
that he through him might become the righteousness of God.`'
And this is not opposite to Christ that died at Jerusalem;
but it is the same that is manifest, and not the spirit of the devil,
but that which destroys him; for the devil and reprobates may talk of him without,
but the apostle said, that Jesus Christ was in them (that is, the Emmanuel,
God with us) except they were reprobates, and none know righteousness but within.

[.discourse-part]
_Principle._ And they say, '`This is one of the devil`'s lies, to deceive,
to bid people follow the light.`'

[.discourse-part]
_Answer._ That is contrary to the prophets, Christ, and the apostles,
who bid them walk in the light; and Christ, who bids them believe in the light.
And '`I will give him for a covenant of light, a leader of the people.`' And Christ said,
'`I am the light; he that followeth me shall not walk in darkness,
but shall have the light of life:`' and that is the
devil and the liar that leads people from the light,
for he abode not in it.

[.discourse-part]
_Principle._ They say, '`Faith is not perfect in respect of its degree and measure in us.`'

[.discourse-part]
_Answer._ The faith of God is the gift of God,
and it is perfect in us in its measure and degree,
though thy measure and degree are not perfect;
and here thou hast tried thy faith and thy gift, which is not perfect,
for the gift of God is perfect.

[.discourse-part]
_Principle._ And yet they say, '`The work of this faith is for purifying and justifying,
and not perfect in the degree and measure of it in us.`'

[.discourse-part]
_Answer._ Can an imperfect thing purify and justify?
And doth not the scripture speak of one faith that gives victory?
And doth not the apostle say, that faith abides?
And can that abide which is not perfect?
And Christ saith, '`He that hath faith as a grain of mustard seed,
shall remove mountains,`' and is not that perfect?
Now here all men may see if you, who call yourselves ministers, divide the word aright.
We say, faith is perfect in the least measure and degree, the righteousness of faith, Rom. 10.
And it is that with which men please God, which faith works by love,
and so brings off the works of the law, by which faith men are justified,
which is in the heart.

[.discourse-part]
_Principle._ They say, '`It is a manifestation of the deluding of poor souls,
to hold forth a crucified Christ within, risen within, ascended within,
and scriptures within,`' and say, '`this is a new gospel.`'

[.discourse-part]
_Answer._ If Christ that is crucified be not within, and Christ that is risen be not within,
I say that you all are reprobates; and if the scripture be not within,
which was spoken forth from within, you all want the spirit that gave it forth,
and Christ the substance of it, and you have not eaten his flesh,
neither are you of his bone; and this is not opposite to Jesus Christ without,
that died at Jerusalem, but the same; for they who eat his flesh have it within them,
and this is not a new gospel.

[.discourse-part]
_Principle._ And they say,
'`False Christs have a new false faith to apprehend this crucified Christ within.`'

[.discourse-part]
_Answer._ Which is contrary to the faith of the apostles,
who preached Christ that is crucified within, and not another,
him that was raised up from the dead, was risen, that Lord Jesus Christ within,
'`the same yesterday, today, and forever,`' by whom the world was made,
glorified with the Father before the world began.
It was he that was manifest in the saints that was, and is, and not another,
for the other is the antichrist.

[.discourse-part]
_Principle._ And they say,
'`It is a scripture of the devil`'s making to apprehend this crucified Christ within.`'

[.discourse-part]
_Answer._ Now I say, if there be any other Christ but he that was crucified within,
he is the false Christ; and the scripture holds forth this, and the devil never made it,
but he and his messengers are against it.
And he that hath not this Christ that was risen and crucified within, is a reprobate,
though devils and reprobates may make a talk of him without.

[.discourse-part]
_Principle._ They say, '`The light of revelation renders God`'s Christ odious.`'

[.discourse-part]
_Answer._ None know the son of God but by revelation, and with the light,
and they are those that render Christ odious that
are out of the light of revelation of the son,
as the Pharisees did, and as now the beast and false prophets do,
in making war against the saints in light, and the Lamb;
but the Lamb and the saints shall get the victory: glory to the Highest.
They that walk in the light are not opposite to Christ,
but to the beast and the false prophets, but are in unity with the son,
and with the Father.

[.discourse-part]
_Principle._ And they say, '`What a sad doctrine is that which saith,
follow the light with which Christ hath enlightened all who come into the world.`'

[.discourse-part]
_Answer._ This is contrary to the apostle`'s doctrine,
who was to go into all nations to turn people from darkness to light,
and preach the new covenant to Jews and Gentiles,
'`the salvation to the ends of the earth,
a leader of the people;`' and contrary to the apostle`'s doctrine,
who bid the saints walk in the light,
'`and they should have fellowship one with another,`' and so not sad, but fellowship.
But thou and you that are apostates, are gone from this light,
and that which doth make manifest is light,
and with it are you that are apostates from it, seen.
And you follow not the light that every one is enlightened
with that comes into the world,
and so are out of unity one with another, and fellowship with the son,
and with the Father, and are out of his covenant, all on heaps in the apostacy,
that walk not in the light, but call it a sad doctrine to bid others follow it.
The children of the light are the light of the world: '`Let your light shine before men,
that they may glorify your Father which is in heaven,`' like lamps burning,
'`for ye are as a city set on a hill that cannot be hid.`' And Christ saith,
'`He that followeth the light shall not walk in darkness.`'

[.discourse-part]
_Principle._ They say, '`It is a rendering of the scriptures odious, and law,
to tell of the scripture within, which Christ never taught, nor his disciples:
but God hath given them up to a reprobate mind.`'

[.discourse-part]
_Answer._ Were not all the scriptures from the spirit within?
and were they not there before they came out?
And must not all upon the earth have the spirit within that gave it forth,
before they can understand the scripture without,
given forth from the spirit of God within others?
And was not the apostles`' and Christ`'s preaching of the scripture within,
the law in the heart, and the word in the heart?
and the kingdom within, and the spirit within, leading into all truth,
the spirit of the Father speaking in you, and Christ within?
and is not this extolling scripture of truth?
and are not all they reprobates that have scripture without, and not within?

[.discourse-part]
_Principle._ And they say, '`But this is the devil`'s design,
to pretend that people may attain a more excellent way by following
what is made known to them from the light within them.`'

[.discourse-part]
_Answer._ I never read such a doctrine that the devil taught,
that any should follow that which the light made known within them,
and I know he did not; for he is out of the light, and that which it makes known within;
for the light which shines within makes known '`the
glory of God in the face of Jesus Christ,
whereby men come to be changed from glory to glory,
till they come into the image of God,`' and this the light makes known within.
2 Cor.
iv.

[.discourse-part]
_Principle._ And they say, '`God hath a Christ distinct from all other things whatsoever,
whether they be spirits or bodies.`'

[.discourse-part]
_Answer._ God`'s Christ is not distinct from his saints, nor their bodies,
for he is within them; nor distinct from their spirits, for their spirits witness him:
and '`God was in Christ,
reconciling the world to himself,`' who is the head of every creature.
'`And there is not any creature but it is manifest
in his sight;`' and he is in the saints,
and they eat his flesh, and sit with him in heavenly places.

[.discourse-part]
_Principle._ They say,
'`They are deceived that think to obtain salvation by the conviction
of the law which they call Christ,`' pages 37 and 39.

[.discourse-part]
_Answer._ Christ is the end of the law, and they who follow him are not deceived,
but come to witness the law of life, and him revealed in them;
and they are deceived that call the law without Christ, that doth convict,
and give it that name;
but who follow Christ the end of the law have the righteousness
of God revealed in them from faith to faith,
which the just live by, and Christ revealed in them, as the apostle witnessed,
whereby they have eternal life.

[.discourse-part]
_Principle._ And they say, '`The Quakers would obtain salvation by the obedience of Christ,
the law which gives the knowledge of sin.`'

[.discourse-part]
_Answer._ The Quakers`' obedience is Christ, God`'s righteousness, the end of the law,
which makes them free from the law of sin and death: Christ the seed, the second Adam.

[.discourse-part]
_Principle._ They say,
'`Now every man that cometh into the world receives a light from Christ as he is God,
which light is conscience, and this will show a man that there is a God,
and discover the eternal God, which some falsely call Christ.`'

[.discourse-part]
_Answer._ Christ saith,
'`I am the light of the world,`' and he doth '`enlighten
every man that cometh into the world,`' as saith John;
and doth not say that it is conscience, for the light was before conscience was;
which shows thy ignorance: not knowing what conscience is.
For conscience was since the world; but light was before the world was made,
and he that doth evil hates the light; and so conscience is seared,
and so light condemns.
And the light which every man that cometh into the world is enlightened with,
is God`'s covenant to Jews and Gentiles, and his salvation to the ends of the earth.
So you have given Christ a new name, that call him conscience, contrary to scripture;
and is conscience that may be seared, eternal?
and will that show that which is eternal?
will conscience blot out sin and transgression?
Christ will, God`'s covenant, that doth enlighten every man that cometh into the world,
believing in which light, they serve Christ the author of their faith,
which faith is a mystery held in a pure conscience.

[.discourse-part]
_Principle._ And they say, '`that every man hath not the spirit of Christ;
and he brings Jude to prove it.`'

[.discourse-part]
_Answer._ That proves that they had it, but went from it;
and the spirit that leads the disciples reproves the world.

[.discourse-part]
_Principle._ John Burton saith, '`John Bunyan is furnished with spiritual gifts,
which gifts the ministers of Christ must have, whether learned or unlearned as to human.
And John Bunyan`'s preaching, he saith, is not by human art;
yet he saith Christ is human.`'

[.discourse-part]
_Answer._ The scripture hath neither taught John Burton nor John Bunyan this language,
to say this knowledge is not human, and yet to affirm Christ is human,
is to say thy knowledge is not from Christ.
But we shall try his gifts whether they are from God,
and whether or not he divides the word aright,
and whether they are agreeable to the scripture,
who fills up his book with mentioning the word human twenty times over.
Human is from the earth; to say Christ is human, thy knowledge is from the ground,
earthy, and he hath no scripture for it.

[.discourse-part]
_Principle._ He saith, '`that the soul is immortal.`' And he saith,
'`It is the devil that keeps people to live and die in their sins,`' and
'`he that cries free grace through the death of the man Christ Jesus;
that sinners do attain to eternal life.
And to deny his own righteousness, he saith, is a notion,
and saith he is empty of sanctified grace.`'

[.discourse-part]
_Answer._ The grace that comes from Christ seasons the heart, and the words are sanctified,
and this is not a notion, but all are in the notion that speak of the thing,
and are out of the grace and salvation.
And you that believe people must have sin, whilst they are upon the earth,
are they that keep people in their sins,
and so thou hast judged thyself to be the minister of sin,
as thou mayst read the fruits in thy own book.

[.discourse-part]
_Principle._ John Bunyan saith, '`he that confesseth Christ came in the flesh, and was crucified,
taken from the cross, and has risen, he that believes this is not antichrist.`'

[.discourse-part]
_Answer._ The pope, and all the profane people in Christendom called Christians,
will confess this in the form without them, and they that deny the power,
(for Christ is the power of God,) and that I say is antichrist,
he that hath not Christ in him is a reprobate.
And so thou wouldst make thyself, and all professors, the pope and all hirelings,
not to be antichrist, and are all on heaps one amongst another:
that is a mark of antichrist: though they may have all in the form,
Christ and the prophets`' words: who deny the power, yet confess Christ without;
he that denies the power, denies Christ,
and so he is antichrist who denies the light which Christ hath enlightened him withal.

[.discourse-part]
_Principle._ '`Man at his coming into the world hath conscience,
but he hath not the spirit of Christ.`'

[.discourse-part]
_Answer._ Man at his coming into the world hath a light from Christ,
him by whom the world was made, which is more than conscience;
but he that hates the light abides in darkness, and so is not like to receive the spirit,
but is reproved with it.

[.discourse-part]
_Principle._ They say, '`They that are carried away by the convictions of conscience,
are misinformed by the devil.`'

[.discourse-part]
_Answer._ This light that doth enlighten every man that cometh into the world,
which he calls conscience, teaching and misinforming by the devil,
is the light that doth enlighten every man that cometh into the world,
that through it they might believe; and is not conscience.
And '`he that believes hath the witness in himself,`' and all may hear the son,
and confess him to the glory of God;
and therefore are enlightened by him who was glorified
with the Father before the world began.
And Christ bids them believe in the light, which believing in,
they have the light of life, but he that believes not is condemned already;
and they that hate the light are they that are misinformed by the devil.

[.discourse-part]
_Principle._ Now they say, '`He converts a new birth,
persuading them it is wrought by following the light,
and this he says is like Baal`'s priests.`'

[.discourse-part]
_Answer._ That is contrary to Christ, who saith, '`I am the light,
and he that followeth me shall not walk in the darkness,
but shall have the light of life.`' He that believes
in the light shall become a child of the light,
and this is far above Baal`'s priests, and all that hate it hate Christ,
and these are Baal`'s priests that hate the light.

[.discourse-part]
_Principle._ And they say,
'`that the spirit of Christ convinceth of sin,`' and yet they say '`all
have it not,`' and yet '`it shall convince and reprove the world.`'

[.discourse-part]
_Answer._ Now it is one thing to be reproved,
and another thing to receive that which doth reprove;
for the believer in the light is led by the spirit of truth into all truth,
and he that believes not in the light, is with the spirit of truth reproved.

[.discourse-part]
_Principle._ They say, '`For one to be convinced of his sins against the law,
and have some power against them,`' these they call '`miserable blind Pharisees.`'

[.discourse-part]
_Answer._ They that were blind Pharisees, transgressed the law of God, lived out of the power,
and that which convinced of the transgression of the law: so they said and did not,
and woe was pronounced against them, and so judgment came to be neglected,
and the doers of the law were justified, and not called blind Pharisees.
And the law was in its place, but Christ is the end of the law for righteousness`' sake,
to them that believe;
and those were not called blind Pharisees who followed
that which showed them the transgression of the law,
for those were the doers.

[.discourse-part]
_Principle._ They say,
'`The spirit shall convince all men and women sufficiently
of that righteousness which Christ fulfilled.`'

[.discourse-part]
_Answer._ That which doth convince of righteousness, all men and women, as thou confessest,
if they believe in the light which Christ hath enlightened them withal,
it will lead them from their own righteousness, and be their teacher,
and they come to be taught of God.

[.discourse-part]
_Principle._ They say, '`The light convinceth of sin against the law,
but will not show a soul a saviour or deliverer.`'

[.discourse-part]
_Answer._ That is contrary to the apostle, who saith,
'`the light that shined in their hearts will give the light of the knowledge
of the glory of God in the face of Jesus Christ,`' who is the saviour;
and '`he shall be my salvation to the ends of the
earth,`' the covenant to Jews and Gentiles.

[.discourse-part]
_Principle._ They say, '`The light will not show a man his lost condition, nor the righteousness,
blood, death, resurrection, and intercession of Jesus Christ.`'

[.discourse-part]
_Answer._ There is nothing makes manifest but light.
And none know the blood, death, righteousness, and resurrection of Jesus Christ,
but with the light which comes from Jesus Christ,
who hath enlightened every man that cometh into the world,
and that is it shall give every man assurance that he is raised from the dead;
the light of the body is the eye, that lets see salvation.

[.discourse-part]
_Principle._ They say, '`Christ went away into heaven from his disciples,
and so is not within them.`'

[.discourse-part]
_Answer._ Did not he say he would come again to them?
did he not say he was in them,
'`I in you?`' and did not the apostle say Christ was in them, the hope of glory,
except they were reprobates?
was not he revealed in the apostle, and so in him?
and did not the apostle preach Christ within?
and you preach Christ without.

[.discourse-part]
_Principle._ They say, '`that those believers that are in the body now at this day,
are absent from the Lord.`'

[.discourse-part]
_Answer._ Doth not the apostle say, that Christ is in them except they be reprobates,
and that he is in them the hope of glory, and they have fellowship with God,
and God will dwell in them, and walk in them?
And he that believes, believes in him, in Christ, so is not absent.

[.discourse-part]
_Principle._ And they say, '`He is absent from them, as touching his flesh.`'

[.discourse-part]
_Answer._ Doth not the apostle say that they are of his flesh, and of his bone,
and he that eats not his flesh, hath no life in him,
and they sit in heavenly places with him?
and he that eats his flesh hath it within him.

[.discourse-part]
_Principle._ They say, '`that there is not any heaven within,
into which the man Christ is ascended; nor can any man contain a man four foot long?`'

[.discourse-part]
_Answer._ Christ is a mystery, and is not he to be revealed within, who is a mystery?
he who did ascend to be revealed and made manifest in his saints, in flesh and spirit,
he that did descend; who is now manifested, that the world wonders at,
who is ascended far above the heavens, who is the saints`' life, living bread, and drink.
And where ever used the ministers of Christ any such expressions as thou dost?
which shows that Christ is yet to thee a mystery.

[.discourse-part]
_Principle._ They say, '`stars falling from heaven,
are professors falling from the faith to the earth.`'

[.discourse-part]
_Answer._ This is fulfilled upon you all, who have given judgment upon yourselves;
and so you are from the faith in which is the unity,
in which men please God and have victory over the world;
and this you may read since the days of the apostle,
who are fallen all down into the earth for money and stipends.

[.discourse-part]
_Principle._ They say, '`that God hath given assurance to all men,
and commands all to repent everywhere,
in that he will judge the world in righteousness by the man Christ Jesus.`'

[.discourse-part]
_Answer._ Every man that cometh into the world is enlightened by Christ the light of the world,
him by whom it was made,
who will give them a reward according to their works that deny his light,
and are found in the works of darkness.

[.discourse-part]
_Principle._ They say, '`that the end of Christ`'s coming is,
that the people of God should shine as the sun,
and the cause that hinders them from shining is the body of death.`'

[.discourse-part]
_Answer._ The righteous and the saints come to witness the body of sin put off, and thank God,
who hath given them victory, and come into the second Adam, the Lord from heaven,
(out of the first Adam,) where the shining state is witnessed, the holy mount of God,
the city that cannot be hid.

[.discourse-part]
_Principle._ They say, '`If a man`'s obedience flow not from the faith,
it is but sin in the sight of the great God.`'

[.discourse-part]
_Answer._ And yet they say, faith is not perfect in the measure and degree!

[.discourse-part]
_Principle._ And they say, '`Four times Christ ascended away from his disciples,
and was not in them.`'

[.discourse-part]
_Answer._ And Christ said, '`I in you,
and you in me;`' and that he would come and dwell in them, and make his abode with them,
which the apostles came to witness, and sat with him in heavenly places.

[.discourse-part]
_Principle._ They say, '`That the man Christ that was crucified,
his body is now in the presence of his Father, absent from his people,
as touching his bodily presence.`'

[.discourse-part]
_Answer._ Doth not the apostle say he is the head of the church?
And doth not the apostle say, they are of his flesh and bone,
and sit with him in heavenly places, with Christ.
And Christ saith, they must eat his flesh, and he is in them.

[.discourse-part]
_Principle._ And they say, '`That Christ is absent from the saints in the world, is clear.`'

[.discourse-part]
_Answer._ When the apostle saith, Christ was in the saints;
and '`Christ in you the hope of glory.`' And the
apostle said he had revealed the son in him.
And '`he that hath not the son of God hath not life.`' And after,
the same Christ which was crucified and risen, came to be manifest in his saints,
and not another.
And so the saints come to feed upon his flesh, and drink his blood which is their life,
which body Christ gives for the life of the world,
and which blood appeaseth the wrath of the Almighty.
And as for the rest of John Burton and John Bunyan`'s lies and slanders,
they are not worth mentioning; but the scriptures are owned.
And John, art thou finding fault, because men wear no hat-bands,
and eat and drink bread and water, and cast by their pride?
Now thou mayst see who thou hast taken part with, and who is the scoffer,
and showest thyself, and who is thy master, short of all good.
And as for all your bad names, and misconstruing of scriptures,
it will come upon yourselves.
And thou hast shown in all thy book, that thou art not able to divide the word aright,
nor an instructer of babes.

[.discourse-part]
_Principle._ And thou sayst, '`that Christ died for the sins of the elect.`'

[.discourse-part]
_Answer._ And the scripture saith, he was an offering for the sins of the whole world;
and who shall lay charge to God`'s elect whom he justifies.

[.discourse-part]
_Principle._ And thou speaks of God '`destroying men for their ignorance,`'
and '`they shall find no favour in the day of judgment.`'

[.discourse-part]
_Answer._ Whereas the scripture saith, '`the time of ignorance God winked at,
but now he commands all men everywhere to repent,`' and '`every man that cometh into
the world is enlightened.`' And the spirit of truth shall '`reprove the world of sin,
of righteousness, and of judgment,`' which leads believers into all truth.
And '`the grace of God which brings salvation hath
appeared to all men,`' but they turn it into wantonness,
which is the saints`' teacher.
And this shall make every tongue to confess to the glory of God,
and every knee to bow at his name, which is the Emmanuel;
and so none shall plead ignorance, as thou said, who art in the ignorance thyself,
but inexcusable, because convicted.
And thou hast rejected the tender mercies,
who hast lifted up thyself against the saints and the Lamb;
but a stone is set over thy head that shall grind thee to powder,
and the saints shall have the victory, and the kingdom that is an everlasting kingdom.
The witness in thy conscience shall witness against thee for all thy hard speeches,
and let thee know that you and thou had better have been silent,
than to fight against the Lord, the Lamb and his saints:
that is the word of the Lord God to thee and you all.
When ye are judged, the witness in all your consciences shall answer.
