[#ch-49.style-blurb, short="Recording to Truth, that Quakes Not, Nor Quails"]
== W. P`'s. Principles, in his book entitled, [.book-title]#Recording to Truth, that Quakes Not, Trembles Not, Nor Quails.#

[.discourse-part]
P+++.+++ They say, '`If the apostles had been put to preach upon a short text, or methodically,
as by a long practice in the church, is expected from us,
they might oft times have studied for it.`'

[.discourse-part]
A+++.+++ In this you have showed your spirits,
and made manifest you are void of the revelation from God,
and your ignorance of the scriptures; for the holy ghost shall not speak of itself,
but take of his.
And the apostles, what they had seen and heard they declared.
And Christ, what he had received of the Father, he declared.
And the spirit is that which speaks in the church,
and it shows the fulfilling of the scriptures, and it keeps not people long in texts,
as the world doth, that wrests scriptures up and down, and keeps people in sects.
And so, there is the spirit leading into all truth,
and the spirit of the Father speaking within,
and the holy ghost that moved men to give forth scripture,
that teacheth to divide the word aright, which is the spirit of prophecy in the church,
not studying.

[.discourse-part]
P+++.+++ They say, '`Every man that hath the spirit in some measure,
doth not attain to the great height and degree that they did that gave forth scriptures,
therefore may not lawfully and infallibly teach as they did.`'

[.discourse-part]
A+++.+++ Every man that hath a measure of the spirit of God, in the least measure or degree,
it is infallible, and so far may they teach infallibly, and know scriptures;
but they cannot know all scriptures,
but as they attain to the full measure of the spirit of the prophets and apostles,
and to the measure, and stature, and fulness of Christ.
And if they do not attain to all this, they are not able to know all the scriptures;
and the work of the ministers of God was to bring people to this, to the measure,
and stature, and fulness of Christ; and the apostle saith,
'`Let every one minister as he hath received the grace.`'
And take heed of any of you going beyond your measure.
And they that deny the grace of God appearing to all men, cannot minister.

[.discourse-part]
P+++.+++ They say, '`The greater part of professors in the visible church were, and always are,
earthly-minded, nor can rightly value spiritual and heavenly things.`'

[.discourse-part]
A+++.+++ In this you and your ministers have showed your fruits like Balaam`'s,
which wither and are earthly; such as Jude speaks of, that separated themselves, sensual,
and had not the spirit, but went forth from the apostles,
that were got up since the days of the apostles, church and ministry, like priest,
like people; and to be such as were coming up before the apostles`' decease,
as he speaks of in Timothy, '`who minded earthly things;`' like teacher, like people;
that pierced themselves through with many hurtful lusts.
While they coveted after money, they lost the faith,
and so came people to be all on heaps (out of unity) in the earth,
being out of the faith of God`'s elect.
So this is all in the apostacy since the apostles.

[.discourse-part]
P+++.+++ And he saith, '`that he is not a hireling that takes wages.
The wages are allotted to him for his work.`'

[.discourse-part]
A+++.+++ But do not all you preach for hire?
and is it not for hire you preach?
Now the least in the truth may see you.
Is there ever a priest in the nation but he is hired to work, or if he have it not,
he will not stay?
Now to prove that you do preach for hire;
where there are many steeple-houses in many parishes that have no priest,
thither you go not, because there is but a little benefice,
and they have souls as well as others;
and where there is an agreement for so much a year, thither you go; is not this for hire?
And so the prophet`'s words are fulfilled,
'`the priests preach for hire.`' And all these great
sums of money which have lifted you up,
and a great deal of it has been gathered out of poor men`'s labours;
this hath been the undoing of you all and of nations, and many poor people,
because they cannot put into your mouths.
But now is God come to judgment upon you all apostates, in the apostacy.

[.discourse-part]
P+++.+++ And thou calls the steeple-house a church.

[.discourse-part]
A+++.+++ Which is the church that is come up since the days of the apostles, in the apostacy;
for the church is the people of God, the elect seed, which Christ is the head of,
who in the midst of this church doth sing praises,
which is the pillar and ground of truth, without spot or wrinkle.
Whereas the steeple-house you call your church, will spot, wrinkle, and blemish,
and decay, and fall down, and wicked men may prevail against it;
but the gates of hell cannot prevail against that church which is built upon the rock.

[.discourse-part]
P+++.+++ And thou sayst,
'`Thou dost not speak in that degree of the holy ghost as
the prophets and apostles did that spoke forth scriptures.`'

[.discourse-part]
A+++.+++ Then thou must take heed of exalting thyself above thy measure;
for thou canst not know scripture,
but by the same degree of the spirit the prophets and apostles had.

[.discourse-part]
P+++.+++ And he saith, '`He hath no command in scripture to sprinkle infants,
and he holds it not absolutely necessary, and he hath no command in scripture against it,
and he hath a commandment of the governors,
and so he is subject to every ordinance of man.`'

[.discourse-part]
A+++.+++ An ordinance of man that is of absolute necessity,
consider what it is! and that which the scripture no where commands,
nor thou hast any example for, consider what that is!
And as to saying the scripture no where forbids it,
it forbids all the traditions and doctrines of men:
so that is judged by the spirit of God that is set up by men.

[.discourse-part]
P+++.+++ Thou sayst, '`The Lord may, with the outward washing, give the spirit to the child.`'

[.discourse-part]
A+++.+++ Can man receive the spirit of God by following traditions of men and outward things?
Were not they all from it, and from the spirit?
and doth it not judge them for setting up such things as God never commanded?

[.discourse-part]
P+++.+++ And he speaks of '`David`'s Psalms given to the world suitably.`'

[.discourse-part]
A+++.+++ The world must repent and be in the spirit,
(for it lies in wickedness,) before they can know David`'s singing;
for the prophet saith, their songs must be turned into howling,
and David`'s condition is not the world`'s.

[.discourse-part]
P+++.+++ He saith, '`men may respect persons in their places.`'

[.discourse-part]
A+++.+++ That is contrary to the apostle, who said, God was without respect of persons,
and that the Gentiles should be accepted as well as the Jews.
He that doth righteousness is accepted with God;
who holds the faith of Christ it is without respect of persons, it is in the unity,
and they that are out of that, are out of the unity.
So thou who hast pleaded for that, art out of his doctrine.
'`He that respects persons commits sin,
and is convinced of the law as a transgressor,`' saith the apostle.
W+++.+++ P. thy works are tried and weighed, and found too light, and condemned for the fire,
as the witness in thy conscience shall answer; but now in thy security thou art asleep,
but the wrath of the Lamb shall find thee out.

[.small-break]
'''

And as for all the lies and slanders thou heaps up in thy book,
they are not worth mentioning, but will come upon thy own self,
for they are thine own covering, which are judged, the witness in thee shall answer.
