[#ch-50.style-blurb, short="An Antidote Against the Infections of the Times"]
== The Elders and Messengers of the several Churches of Ilston, Abergevenny, Tredingnoge, Caermarthen, Hereford, Bredwerden, Cledacke, and Liangors, meeting at Brecknocke, whose book is titled, '`An Antidote Against the Infections of the Times.`'

[.heading-continuation-blurb]
Who have shown yourselves full of poison, and such as infect the times,
but with the spirit of truth ye are comprehended and judged.
Your principles are as followeth.

[.discourse-part]
P+++.+++ You say, you are '`conceived in sin, and brought forth in iniquity.`' Ps. 51:1.

[.discourse-part]
A+++.+++ David doth not say, '`you who were conceived in sin,`' but '`I;`' and W. P. saith,
'`John was sanctified from the womb;`' and the scripture
speaks of such as were sanctified from the womb,
and children that were clean.
And so you do not speak as elders and messengers of true churches,
or men dividing the word aright; but you are one against another,
though you are all against them you call Quakers; that are in the truth.

[.discourse-part]
P+++.+++ They say, '`they observe the design of Satan to cast down the walls of Zion,
and to remove the living stones thereof from the sure foundation, the rock of ages,
the Lord Jesus Christ, and draw them to build upon the sands.`'

[.discourse-part]
A+++.+++ Is this likely that the elect should be deceived?
that living stones should be drawn from the sure foundation, the rock of ages,
the Lord Jesus Christ?
For these living stones to be built upon the sand, and drawn from the rock of ages,
doth not sound like the doctrine of men of understanding;
for the living stones are the spiritual household, and the royal priesthood;
and theirs is the foundation that stands sure,
the rock which the gates of hell cannot prevail against.
You in your notions should let living stones alone,
for none can pluck them out of the Father`'s hand.

[.discourse-part]
P+++.+++ And they say, '`No man can redeem the soul of his brother.`'

[.discourse-part]
A+++.+++ Solomon saith, '`The fruits of the righteous is a tree of life;
and he that wins souls is wise.`' And '`he that saves a man from his evil ways,
saves a soul from a multitude of sins.`' Again thou sayst, '`No man, the greatest of men,
can redeem the soul of his brother.`' Ye should not have left out Christ the saviour,
the redeemer, the man Christ Jesus, the elder brother;
so you are a company of blind pastors, contrary to them that gave forth scriptures.

[.discourse-part]
P+++.+++ '`To say heaven and glory are in man, which were before man was,
they are sottish and blind.`'

[.discourse-part]
A+++.+++ There are none have a glory and a heaven but within them,
which was before man had a being.

[.discourse-part]
P+++.+++ '`Wherefore, take heed of depending upon any righteousness within you,
or any righteousness done by you.`'

[.discourse-part]
A+++.+++ This is a strange doctrine, that men must take heed of any righteousness done by them,
or within them!
This is contrary to scripture, which saith, the kingdom of heaven is within,
that stands in righteousness, peace, and joy in the holy ghost.
And the fruits of the spirit are righteousness and goodness;
and this is that which ends the righteousness of the law.
And '`He that doth righteousness is righteous, and Christ, the righteousness of God,
is with them.`'

[.discourse-part]
P+++.+++ '`Man hath received a light from Christ as a creature, but not as a redeemer.`'

[.discourse-part]
A+++.+++ That is false; for whosoever hath received a light from Christ,
hath received a redeemer, and a saviour, and he that doth believe in it is saved,
and he that doth not is condemned.

[.discourse-part]
P+++.+++ And they say, '`If you love your souls, beware of such delusions,
lest ye perish eternally,
that say it is the true light that enlightens every man that cometh into the world,
and that following it, it is sufficient to bring men to heaven;
which light is natural reason and conscience.`'

[.discourse-part]
A+++.+++ The light that every man that cometh into the world is enlightened withal,
cometh from the salvation, Christ, who is the way to the Father,
whose throne is in heaven; and Christ saith, '`Believe in the light,
that ye may become the children of the light,`' and '`he that believes
in the light shall not come into condemnation.`' All men are enlightened,
that through the light they might believe.
So you are not able to divide the word aright, and all that are from this light,
are '`lo here, lo there:`' and so are in the natural reason and conscience,
which the light is not; the light was before they were.

[.discourse-part]
P+++.+++ They say, '`None should ever have known a justification or a sanctification,
if it had not been written.`'

[.discourse-part]
A+++.+++ I do believe you had not, but here you have laid aside the holy ghost:
how knew they before they gave scripture forth?
Here thou hast denied revelation of the spirit; for though a man has all the writings,
yet he knows nothing of God, but by the spirit of God,
and the light which comes from him; nor of sanctification, nor justification,
which is Christ.

[.discourse-part]
P+++.+++ You say,
'`You are fallen into the last times prophesied of by Christ,`' and you
are '`to contend earnestly for the faith once delivered to the saints.`'

[.discourse-part]
A+++.+++ The faith once delivered to the saints, ye are out of, in respecting persons,
and are apostates from it; and the last times which Christ spoke of that should come,
John saw were come, when the false prophets which Christ prophesied of, were come,
who went forth from the apostles, who, since their days, the world went after;
and now from them is the Lord God bringing his people to the rock of ages,
into the faith they are out of.

[.discourse-part]
P+++.+++ '`Foolish man would have his righteousness in himself.`'

[.discourse-part]
A+++.+++ Every one that hath Christ hath the righteousness of God wrought in him,
and none own the righteousness of Christ but who own the
light that enlighteneth every man that cometh into the world;
and they are foolish that know not this, and the righteousness of faith in them.

[.discourse-part]
P+++.+++ '`It is blasphemy,`' they say, '`and colourable pretences,
to witness an infallible spirit in them.`'

[.discourse-part]
A+++.+++ The spirit that leads the saints into all truth, is infallible,
and that shall reprove the world; and he that hath the spirit of Christ,
hath that which is infallible, and he that hath not the spirit of Christ is none of his,
but is in the colourable pretences.

[.discourse-part]
P+++.+++ They say, '`The scriptures are the quick and powerful word.`'

[.discourse-part]
A+++.+++ Many may have the scriptures and the form, and deny the power;
and the scriptures are words of God, and the word is God; and this word is in the heart,
which led them to speak forth scripture.
And many scriptures they bring to oppose the doctrine of Christ, who saith,
'`Be not ye called of men master; for ye have one master,
even Christ,`' to whom every knee shall bow, and every tongue confess,
to the glory of God.
Will men receive worship, when angels would not receive it, but bade them worship God!

[.discourse-part]
P+++.+++ They say,
'`They rail and cavil at the lawful maintenance that God hath ordained for them.`'

[.discourse-part]
A+++.+++ God hath suffered the beast to make havoc, and spoil the saints`' goods:
but where doth God ordain that you should take tithes and treble damages,
easter reckonings, and midsummer dues, and that you should sue men at the law,
and cast them in prison till death, where did God command this?
They that preach the gospel should live on the gospel,
and they bring glad tidings to people, and this is not glad tidings,
to cast into prison till death, and hale up and down to courts and sessions,
for outward maintenance.
Let the spiritual judge whether these men bring glad tidings,
or whether they do not make their folly manifest to all men that can but read the scripture.

[.discourse-part]
P+++.+++ They say, '`Such as trust in their own inherent righteousness,
compass sea and land to make proselytes.`'

[.discourse-part]
A+++.+++ It was so in the days of the Pharisees,
it hath been so since the days of the apostles,
since the beast and the false prophet got up,
who deny the light that doth enlighten every one that cometh into the world,
God`'s righteousness, (Christ.) And such as denied the light had the form;
and such gather people into the form of Moses, the prophets, Christ,
and the apostles`' words; establishing their own righteousness,
and denying the righteousness of God,
the light that doth enlighten every one that cometh into the world.
And all you that deny the light that doth enlighten every man that cometh into the world,
have trodden the blood of the covenant under foot.
And you tell us of human and inherent righteousness,
but the scripture tells us no such words.
And as for all the rest of the lies in this book,
we let them go home again upon their own heads; every word shall be their own burden,
and that in their conscience shall witness.
And the scriptures are owned by the Quakers, and denied by you,
but owned for your own ends, that deny the light.
