[#ch-51.style-blurb, short="The Quakers`' Cause"]
== A book entitled, '`The Quakers`' Cause.`' No name is found in it, but it is a book of darkness, railing, and lies. And because some leave father, and mother, and wife, therefore he rages, who is out of the light and doctrine of Christ. The principles in it are as followeth.

[.discourse-part]
P+++.+++ Such as forsake husband and wife, to do the will of God,
this he calls '`a breaking of relations.`'

[.discourse-part]
A+++.+++ And thus ignorantly speaks evil of those things he knows not.
Thus, ignorant of the command of Christ and the scriptures,
he hath showed himself to be a member of the world, and not of Christ, who saith,
'`he that doth not forsake father and mother, wife and children, is not worthy of me.`'

[.discourse-part]
P+++.+++ He saith, '`Because he saith thou to God,
it doth not follow that he should say thou to his earthly father,
to speak to God as he doth to man.`'

[.discourse-part]
A+++.+++ Now mind what proud flesh would have,
of whom thou hast learned to speak you to an earthly man, or to a particular person,
which the scripture hath taught no such language, nor the accidence.
That which teacheth thee to give more to man than to God is the spirit of the world,
but the spirit of God teaches to speak righteously, and when there is but one,
not to say as of many, but thou to one, and you to many.
And so here is the form of sound words that cannot be condemned:
now you may see where your original stands, who cannot endure the form of sound words.

[.discourse-part]
P+++.+++ He saith, '`To he justified by grace, which is Christ in them,
this is a kind of Popery.`'

[.discourse-part]
A+++.+++ Contrary to the scripture and the apostles`' doctrine, (before the pope,
and them too,) which saith,
'`Christ was in them,`' '`who are justified by faith;`' and faith was in the heart;
and '`justified in the spirit,`' and who witness the spirit, it is the spirit of grace;
and '`by grace ye are saved,`' and that which saves, justifies;
and '`being justified by grace.`' And thou art of the pope, and in the apostacy,
that deniest this.

[.discourse-part]
P+++.+++ To say, '`Christ is within, is never to mention Christ without.`'

[.discourse-part]
A+++.+++ There is none knows Christ within, but he knows him without, the same yesterday,
today, and forever; and there are none know him but they know him within,
revealed of the Father, which is beyond flesh and blood.

[.discourse-part]
P+++.+++ And he says, '`To run upon new birth, self-denial, light within, Christ within man,
if this be not a kind of Popery, and a fair gate for Rome, he is deceived.`'

[.discourse-part]
A+++.+++ Light within, Christ within, new birth,
and self-denial are out of your works and Rome`'s,
which was the doctrine that the apostles held forth and the saints witnessed,
Christ within, light within, and new birth.
Such were they that came into the kingdom of God, over the kingdoms of the world.
And because some have been moved of the Lord to go naked among you,
a figure of your nakedness and want of clothing, you rage at it;
that you may appear more naked of the spirit of God.
And as for all thy lies and slanders and hard expressions in thy book,
though thou hast hid thy name, yet truth will bring thy works upon thee,
and make the witness in thee to answer; who and which are for the fire,
and to thee this shall be thy burden, who art like a man that scorns and scoffs,
and yet thou hidest thyself.

[.discourse-part]
P+++.+++ And thou sayst, '`That good woman called who went naked.`'

[.discourse-part]
A+++.+++ Thou hast justified her to be good, and thou canst not say,
that that which was good called that which was good beastly or bad, that went naked,
which was your figure.
Then thou talkest of higher power, and honour of men; like thy brethren the Pharisees,
and not like one that knew the higher power, which respects no man`'s person.
And the good women are those that fear God,
that have the adorning of the hidden man of the heart, that have the array of Sarah.
