[#ch-52.style-blurb, short="Strength in Weakness"]
== John Jackson`'s book entitled, [.book-title]#Strength in Weakness.# His principles are as followeth.

[.discourse-part]
_Principle._ '`One that is kept groaning and waiting for the adoption,
because of the adversary`'s assaults and contests within her;
and yet she is in the kingdom, (thou sayst,) and union with Christ,
and spiritual sonship.`'

[.discourse-part]
_Answer._ Spiritual sonship, and in the kingdom, and yet groaning for adoption!
How hast thou brought thyself to the light to be judged;
for the least in the kingdom was greater than John.
He that is in the kingdom is in righteousness, peace, and joy in the holy ghost,
and thou sayst,
'`in the kingdom of grace groaning;`' that is but a notion
of the kingdom that keeps them groaning for adoption.

[.discourse-part]
_Principle._ And as thou sayst, '`False prophets, and Christs, and deceivers many should come:
if it were possible to deceive the very elect.`'

[.discourse-part]
_Answer._ Yea Christ told his apostles they should come, who before their decease did come,
and went forth from them; who Christ said should inwardly raven,
and get the sheep`'s clothing;
and since the days of the apostles all the world went after them,
as thou mayst read in the Revelation.
And now are people but coming from them to the rock,
and now shall the everlasting gospel be preached to them that dwell upon the earth,
over the heads of the beast and the false prophet, and they shall be taken,
and the Lamb and the saints shall have the victory.

[.discourse-part]
_Principle._ He saith,
'`hope you will not condemn the generation of the righteous because they are not perfect.`'

[.discourse-part]
_Answer._ That which condemns is righteous, it condemns that which is not perfect,
and that which is righteous is perfect,
and the generation is righteous and not to be condemned.

[.discourse-part]
_Principle._ '`A son or daughter that is translated into the kingdom of the dear son,
hath filthiness and pollutions of flesh and spirit to put off,
and the members to be mortified.`'

[.discourse-part]
_Answer._ How is he translated into the kingdom of the dear son of God, or grace,
if he have that before mentioned to put off?
and what is he translated out of,
if when he is translated into the kingdom he hath
filthiness of the flesh and spirit to put off,
and the members to mortify?
which filthiness of flesh and spirit, and unmortified members, come not into the kingdom:
for they are mortified in their passage to it,
for no unrighteousness enters into the kingdom, as saith the apostle,
nor any unmortified thing;
for the kingdom of God consists of joy and peace in the holy ghost,
and unrighteousness and all filth of flesh and spirit, are without it.

[.discourse-part]
_Principle._ '`It is the comforter that convinceth the world of sin,
but all men have not the spirit, neither are they convinced so of their unbelief.`'

[.discourse-part]
_Answer._ Every man that cometh into the world is enlightened, that he may believe in the light,
and he that believes in the light receives the comforter,
and he that believes not in the light, the spirit of truth reproves him for his unbelief,
for his righteousness, and his judgment.
And I say,
the light that doth enlighten every man that cometh into the world is sufficient,
and those who believe in it shall have the light of life,
and shall not abide in darkness, and come to the rock, Christ.
And all being in the light that doth enlighten every man that cometh into the world,
shall in the light see their salvation to the ends of the earth;
and need not say, '`Lo here,`' or '`Lo there.`'
And as for all the wrangling stuff in thy book,
what he said, and what she said, and what thou sayst,
(a garment to cover,) you had been better silent
and not have laid open your nakedness to the nation.
I say unto thee, this stuff, and bush, will burn in the fire,
and the witness in thee shall answer, which shall witness me,
and judge thy contentious spirit, which shows thou art far from the kingdom.
And silence had preached more, and patience,
than the strife which stands in self-justification,
and justifying that which is to be mortified and put off,
which never came into the kingdom.
And all men that do not believe in the light '`that doth enlighten every
man that cometh into the world,`' the spirit doth convince them,
and is manifest to them and in them.
