[#ch-53.style-blurb, short="Hosanna to the Son of David"]
== A book, title page called, [.book-title]#Hosanna to the Son of David.#

[.heading-continuation-blurb]
But the book is nameless, and so the writer reviles and rails, and hides himself in the dark.
His intent and drift in his book,
is to make the light that '`doth enlighten every
man that cometh into the world,`' a covenant of works,
or law without; whereas Christ the light is the covenant of God,
the end of the first covenant and its works, and end of the law to Jews and Gentiles,
in which they have peace one with another, and with God.
And secondly, he goes about to make the Comforter above Christ the light,
that doth enlighten every man that cometh into the world; which Christ the light saith,
that he will send to them, the light, the Comforter, and he shall take of his,
and give to them, and not speak of himself; as Christ had not spoken of himself;
but as he had heard and saw of the Father, he spoke.
And the rest of his principles follow.

[.discourse-part]
P+++.+++ Thou sayst, '`The lying murderer, he hath sent forth his instruments,
which go under the name of Quakers,
and disguised with piety and purity to preach the everlasting gospel:
and they hold forth a light, which doth enlighten every man that cometh into the world,
what it doth in every man, and what it is in every man;
and how it will lead man to purity and righteousness, and from drunkenness,
and taking God`'s name in vain, and check them when they do wrong,
and make manifest all ungodliness and worldly lusts,
and it will bring to worship God.`' These things
among others are the scope of the lying murderer,
and he bids them, '`believe not every spirit, but try them,
whether they be of God or not; for many false prophets are gone out into the world.`'

[.discourse-part]
A+++.+++ The false prophets and antichrists, which Christ said should come,
came up in the days of the apostles before their decease,
and went forth from them into the world, which since the world went after.
And they had the sheep`'s clothing, but ravened from the spirit,
and so are broken into sects and heaps one amongst another,
which made war against the saints and overcame them;
but then again the beast and false prophets, and the kings of the earth,
the Devil and the dragon should make war against the lamb and the saints;
but the lamb and the saints should get the victory over them,
and the everlasting gospel should be preached to them that dwell upon the earth.
So it is not a strange thing to us that the whole
world should be standing against the light,
and against the saints and the lamb, but their garments they cannot touch.
And so wickedness hath budded forth into a rod;
but he is brought forth to rule the nations with a rod of iron,
'`who was dead and is alive.`' And ye discern not the times, like the Pharisees;
and the light which leads men from the world, from their lusts,
from taking God`'s name in vain, and from all ungodliness.
You never came into this, the devil never came into this,
nor do any come into it but they who are in that which the devil is out of.
Nor do any see the salvation which is to the ends of the earth,
but who are in the light that John bore testimony of;
the witness in thy conscience shall answer it, and condemn thee for thy hard speeches.
And the light by which all things are made,
'`which doth enlighten every man that cometh into the world,`' is the end of the law,
and before a natural light was,
and changes men who believe in it from their natural estate,
into the covenant of life and peace with God.
I say, the law of God that came by Moses, is above conscience,
much more Christ the end of the law,
that doth enlighten every man that cometh into the world, the righteousness of God.
And the devil is out of piety and purity, who is the lying murderer,
and never brought people to the light within, who himself is out of it,
and he cannot disguise himself, nor thee neither, from the children of light.

[.discourse-part]
P+++.+++ '`And the light simply considered, makes not any thing that is done good or evil.`'

[.discourse-part]
A+++.+++ Did not Christ the light testify against the world that their works were evil?
And doth not the light make manifest evil?
And is not he that hates the light reproved, and so with it condemned?
And doth not the scripture say,
'`the law is light?`' And doth not that make evil of that which is evil,
and own that which is good, and judge it?
Nay, and doth not evil grieve the spirit of God?
They that act contrary to the Lord, did not God bring evil upon them that did evil?
'`Is there any evil in the city, and I have not done it?`' Though it was evil to them,
yet it was justice, for they went from that of God in them first.
And doth not Christ the light distinguish between the good and the evil?
And doth not Christ make that which is good to be good, and that which is evil to be evil?

[.discourse-part]
P+++.+++ He saith, '`The law of faith did not make void the law of works, but established it.`'

[.discourse-part]
A+++.+++ That is contrary to the apostle, who said the law was changed,
and the first covenant was to decay; so with it, their outward works,
whereby the law of faith came in, which works by love, where the boaster is excluded,
and the law of life witnessed; and there comes the living in the spirit,
which makes free from the law of sin and death.

[.discourse-part]
P+++.+++ He saith, '`Neither the new man nor the renewed man,
is endued with the principle of light and life,
according to the image of him that created him.`'

[.discourse-part]
A+++.+++ In this thou hast shown thy ignorance of the saints`' conditions;
for they were in the image of God, of him that created them;
and they were not in the flesh, but in the spirit.
And the apostle tells them, that they were renewed,
and '`the light that shined in their hearts`' was to give them '`the light of knowledge
of the glory of God in the face of Christ Jesus.`' And the saints put on '`the new man,
which is renewed in knowledge after the image of him that created them!
And he that believes has the light of life;
and if they have not the spirit of Christ they are none of his.
And God will dwell in man, and walk in man; and Christ in them,
the brightness of the Father`'s glory, the express image of his substance.`'

[.discourse-part]
P+++.+++ '`The natural man retains not the things of the new covenant.`'

[.discourse-part]
A+++.+++ That is while natural men are from the light and that of God in them:
there is that in the natural man, which hearkening to,
will bring him to do the thing contained in the law,
who shall be justified before the professors of the law that are not doers of it;
which is one with that which ye professors act contrary to.
But '`no man can know the things of God,
save with the spirit of God.`' So the natural man`'s eyes are in that which is natural,
from that which is spiritual;
but there is that in the natural man which answers the law of God, which is spiritual,
though he be sold under sin; and as he comes to see the seed,
(Christ,) he shall see the end of all that, and of a natural man`'s estate,
and of the law of sin and death, by the faith in Christ;
and there are our justification and life,
though the other things are owned in their place.

[.discourse-part]
P+++.+++ '`Man is not able to discern the things of God till he be born again.`'

[.discourse-part]
A+++.+++ And the scripture speaks of discerning the eternal power and godhead,
and that was a thing of the spirit of God; and the apostle saith not,
they were born again.
And yet I say, that '`none knows the things of God,
but the spirit of God,`' and '`that which may be known of God is manifest in them,`'
which '`God hath showed unto them;`' for that of God in them was of his spirit,
who is the God of the spirits of all flesh,
who brings them to discern his eternal power and godhead.

[.discourse-part]
P+++.+++ He saith, '`that the light by which all things were made,
which doth enlighten every man that cometh into the world,
is not the powerful word of faith.`'

[.discourse-part]
A+++.+++ Is not the word, Christ, the author of faith,
by which all things were made and created?
Is not that the powerful word of faith?
Is not he the author of it?
which faith that comes from him gives victory over the world.
And is not the son of God him whom the Father hath sealed,
'`that doth enlighten every man that cometh into the world?`'
And '`whosoever believeth in him shall not perish,
but have eternal life,`' and are sealed.
So every man in the light shall see the new covenant, and the mediator,
before he hath power to become the son of God;
and there is prophecy before the son is born, and openings from the Lord,
and those are things of God.

[.discourse-part]
P+++.+++ '`No man can ever see God, who is invisible,
with the light by which all things were made,`' and calls it '`a little light.`'

[.discourse-part]
A+++.+++ This is contrary to John, who saith,
he that walks in the light shall have fellowship with the son and with the Father,
and so sees him; and it is not a little light by which all things were made and created.

[.discourse-part]
P+++.+++ '`The unction in every man is not the light.`'

[.discourse-part]
A+++.+++ It is far from the apostle, to say that the unction in men is not the light.
If the unction be Christ in man, it is the light;
and every man that comes into the world must receive
the light that Christ hath enlightened him with,
before he can receive the unction, and he that hath the unction, hath the light of life.

[.discourse-part]
P+++.+++ '`The sure word of prophecy the apostle speaks of, is the prophecy of scripture,
or scriptures.`'

[.discourse-part]
A+++.+++ Doth the scripture shine in a dark place until the day dawn?
Are they that which must be taken heed unto, as unto a light?
Can any see the scripture, and know the scripture, but with the light within?
Cannot a Cain, a Balaam, or a Core, that is gone from the spirit of prophecy within,
bring scripture, and then put the letter for the spirit?

[.discourse-part]
P+++.+++ '`They know not absolute perfection, that are admitting of measures and degrees;
nor come to the day, nor is the bright morning star risen.`'

[.discourse-part]
A+++.+++ Did not the apostle say that they were children of the day, and the night was over?
And he knew the whole body, and yet said he would not go beyond his measure.
And doth he not speak of the stature, and measure, and fulness of Christ?
And were not they come to perfection?
and did they not speak wisdom amongst them that were perfect?

[.discourse-part]
P+++.+++ He saith, '`The evil done, can never appear to be evil by the light.`'

[.discourse-part]
A+++.+++ Doth not the light make it manifest, and reprove the evil done, and condemn it?

[.discourse-part]
P+++.+++ He saith, '`It is not in the power of the light to call any thing that is done,
good or evil.`'

[.discourse-part]
A+++.+++ This is contrary to scripture, that saith,
'`whatsoever doth make manifest and reprove,
is light;`' and there is power in that which doth make manifest and reprove,
to call that which is evil, evil, and that which is good, good.

[.discourse-part]
P+++.+++ He saith, '`The light convinceth man not, for not believing in Christ.`'

[.discourse-part]
A+++.+++ It condemns him, and convinceth him, and reproves him.

[.discourse-part]
P+++.+++ He saith, '`The light, or law, as he calls it, will convince a man of sin,
and there leave him inexcusable before God.`'

[.discourse-part]
A+++.+++ Christ is the end of the law for righteousness`' sake,
to every one that believes in the light,
and so comes to witness the law of faith and of life;
the hope and the promise of this bring from under the schoolmaster to the sonship,
and to know and see salvation, which none do but with the light.

[.discourse-part]
P+++.+++ He saith, '`That scripture in John is misapplied, which saith,
that Christ doth enlighten every man that cometh into the world.`' And saith,
'`It meddles with none but the children of the new covenant.`'

[.discourse-part]
A+++.+++ This is contrary to scripture, that saith,
one loves the light that doth enlighten every one that cometh into the world,
and the other hates it.
He that hates it, it condemns him, and so he hath it;
but to the other it is the light of life.
And he is a covenant, a light to the Gentiles and to the Jews, whether they own it,
or believe in it, or receive it or not; he is so nevertheless,
according to the promise of God.
And to every man that believes in it, it is the covenant of light,
and he shall not need to say, '`Know the Lord;`' for he shall find the law in his mind,
and the law in his heart.
And the saints witnessed the light shining in their hearts,
and that gave them the knowledge of the glory of God,
and they were passed from death to life, and from darkness to light;
and the unbeliever abides in darkness, and in the death,
and the light shines in the darkness, and the darkness doth not comprehend it;
and there thou art; and such know nothing as they ought to know,
but naturally as brute beasts.

[.discourse-part]
P+++.+++ He saith, '`The light in every man which cometh into the world,
will not open all scripture, nor lead men out of the fall to God the Father,
and to eternal life.`'

[.discourse-part]
A+++.+++ The light which doth enlighten every man that cometh into the world,
is the substance of all scriptures, and the way out of the fall up to eternal life,
out of the first Adam; and is the life that opens all scriptures,
and that all scriptures end in.
Man being in the fall, in the first Adam driven from God, in the sin and transgression,
Christ the second Adam, which doth enlighten every one that cometh into the world,
who is the way again to God, is he who bringeth in righteousness, life, and immortality,
and finisheth sin and transgression, and ends the prophets, types, figures, and shadows,
and opens all scriptures.

[.discourse-part]
P+++.+++ He saith, '`The light tumbles men into the grave, and rolls a stone upon them,
and tumbles them in transgression, and he shall act against the anointed ones of God,
and against the Lord.`'

[.discourse-part]
A+++.+++ Nay, the light leads men out of transgression, and from wallowing in their blood,
and is that whereby they have life; and leads them out of the grave,
and from under their stony hearts and rocks, whereby the new covenant of light is known,
and the new heart which is pure, with which God is seen.
And the light which every man that cometh into the world is enlightened with,
will prick them that persecute the anointed ones, and act against the Lord,
though they kick against it.

[.discourse-part]
P+++.+++ He saith, '`To what purpose should Christ be preached dead and risen,
to be believed on for life, if the light be in every one.`'

[.discourse-part]
A+++.+++ Mankind being in the fall, Christ was made manifest to witness that he should come,
and made manifest to many witnesses when he was come;
and John came to bear witness to the true light,
which doth enlighten every man that cometh into the world.
Then these witnesses that did believe that Christ was come,
were to go into all the world, to all nations, Jews, and Gentiles,
and preach the everlasting covenant of God to them, which was promised,
and were witnesses of his resurrection: and to turn people '`from darkness to light,
and from the power of Satan to God;`' and then told them,
'`the light that shined in their hearts would give them the light of the
knowledge of the glory of God.`' And the law was in their hearts,
and the word was within them, and the anointing;
and such had the '`gifts for the work of the ministry, for perfecting the saints,
for the edifying the body of Christ,
till they all came to the knowledge of the glory of God,
and to a perfect man in Christ Jesus.`'

[.discourse-part]
P+++.+++ He saith, '`Christ is without his saints in respect of his bodily presence.`'

[.discourse-part]
A+++.+++ How then are they of his flesh and of his bone, and eat his flesh, and drink his blood?
And how have the saints his mind and spirit, and he with them, and they with him,
and sit with him in heavenly places?
And he is the head of the church, how then is he absent?
Ye poor apostates from him, who feel not Christ with you!
But he is with the saints, and they feel him.

[.discourse-part]
P+++.+++ He saith, '`salvation and faith are the gifts of God distinct from Christ.`'

[.discourse-part]
A+++.+++ They are all of him, and from him, and with him: and how is he the author of faith,
in whom it ends, from whence it comes?

[.discourse-part]
P+++.+++ He saith, '`The light which discovers sin and iniquity in man`'s heart,
is not Christ the light, the door.`'

[.discourse-part]
A+++.+++ The first Adam was the door where all sin and transgression entered.
Christ, the second Adam,
'`the light which doth enlighten every man that cometh into the world,`' saith,
'`I am the door, the way, and the life;`' which finisheth sin and transgression,
and brings in everlasting righteousness, and the way of life out of death,
which light discovers sin.

[.discourse-part]
P+++.+++ He saith, '`To call Christ the light, the gift, the door, the way,
is to take the gardener for Christ, as Mary did.`'

[.discourse-part]
A+++.+++ We do not put Christ,
the light that doth enlighten every man that cometh into the world, for the gardener.
We know him, and as many as receive him, he gives them power to become the sons of God;
and this thou sayst is not used power, but prerogative authority,
and thus thou art wresting scripture.
So thou shouldst have been more meek and low in thy heart,
and then thou wouldst have bridled thy tongue, and have learned of Christ,
and so have come to the light, the sure foundation, out of the error of thy ways,
and have kept in the footsteps of the flock.
And if thy tongue had been shorter, and thy bridle straighter,
then wouldst thou not have mixed the covenant of God with man`'s spirit,
and have compared it to the law of works,
which Christ the light '`which doth enlighten every
one that comes into the world,`' is the end of.
And man`'s spirit in the fall is polluted, and his body; but as the light is believed in,
and the mind changed, his spirit and body are sanctified,
and so he comes to be a child of the light,
and his spirit witnesseth with our spirits that we
are the sons of God.`' And none own the door,
the mediator, the life, the way,
but with the light which Christ doth enlighten every man that comes into the world withal,
which light is the door, the way, and the life.
