[#ch-54.style-blurb, short="The Quakers`' Quaking Principles"]
== Ellis Bradshaw`'s book, called [.book-title]#The Quakers`' Quaking Principles,# which he directs to the protector. His principles follow.

[.discourse-part]
_Principle._ He saith, '`That Christ who doth enlighten every man that cometh into the world,
doth it not by an immediate illumination, not the elect themselves,
to bring them to salvation.`'

[.discourse-part]
_Answer._ Doth not Christ say, '`I am the way, the truth, and life?`' And he is the door,
and no man cometh to the Father but by him, and we are to learn of him.
'`This is my beloved son: hear ye him,`' said God.
And is not he the new covenant in the heart, by which men need not say,
'`Know the Lord?`' And there is no other name by which men can be saved,
but by the name of Christ, who doth enlighten every man that cometh into the world,
that all through him might believe.
And he that believes in the light, abides not in darkness, but hath the light of life;
and they that believe not in it, but hate it, the light is their condemnation;
and the light '`that doth enlighten every one that cometh into the world,`' is the salvation,
though men neglect it, which the elect walk in, which condemns the unbeliever,
which is immediate; and no man sees salvation but who comes to the light.

[.discourse-part]
_Principle._ He saith, '`The word that was made flesh is visible, and the word is the letter,
and they never received the spirit of life from it, and that is the Quakers`' error.`'

[.discourse-part]
_Answer._ Such as had the scriptures, which were the words of God to them in old time,
and the ordinances, the apostle calls carnal, which the Jews stuck in,
and would not come to him that they might have life, would not come to Christ.
And so if men have all the scriptures, and have not Christ, they have not life.
For the devil may have the scripture, and hath he therefore life?
And the power of God, Christ,
'`his name is called the word of God.`' The word of God lives and endures forever,
and the spirit is not in the letter, and the letter is not the word which was made flesh;
and they are in the error that think so, for the word is invisible.

[.discourse-part]
_Principle._ '`Paul adviseth not only to the light within, but is bidding them bring his cloak,
books, and parchments, and give attendance to reading.`'

[.discourse-part]
_Answer._ The apostle told the saints,
that the light that shined in their hearts would give them
the light of the knowledge of the glory of God,
and bids them walk in the light.
And Christ bids them believe in the light, and they should not walk in darkness;
and there is no other name under heaven by which men can be saved,
but by the name of Christ.
And none see the substance of the scriptures, nor the fulfilling of them,
but who walk in the light, whom God speaks to by his son, who is the end of the prophets,
and there is the true reading and knowing of all books and parchments;
for none know the scriptures, but by the light which comes from Christ, in whom they end.

[.discourse-part]
_Principle._ And again thou sayst, '`There are more words than one.`'

[.discourse-part]
_Answer._ God is the word, and the scriptures of truth are his words, which Christ fulfils.

[.discourse-part]
_Principle._ He saith, '`They have fellowship with the Father,
but not in the like measure of the gifts of grace the apostles had.`'

[.discourse-part]
_Answer._ Then you are not likely any of you to understand the apostles`' words,
nor to be judges of them;
but as you do come into the like measure and gifts as they were in, else,
you will not be able to judge of their conditions, nor know their words.

[.discourse-part]
_Principle._ He saith, '`There is no man justified through the faith in Christ,
that owns the scriptures to be but a dead letter;
but that owns them to be the word of God, in which there is spirit and spiritual life,
as words of eternal life.`'

[.discourse-part]
_Answer._ The spirit and the life are not in the scriptures,
but were in those that gave them forth, and many have the scripture,
and not the spirit of life.
The devil may get scripture, and therefore hath he spirit and life, who is out of it?
This is like the Pharisees, that thought they had had life in the scriptures,
but would not come to Christ, the life which the scripture testified of.
And the scriptures are words of God, but many have the words, and deny the word itself:
and none are justified that have the scriptures,
and are out of the life that gave them forth.

[.discourse-part]
_Principle._ He saith, '`It is a sottish doctrine to direct people only to the light within;
and what an absurd thing it is to tell our children of the light within their conscience,
and to bid them obey and follow it,
that light and word that is in their hearts and mouths,
and so fully neglect the teaching of the scriptures.`'

[.discourse-part]
_Answer._ Is not this Saul`'s zeal, kicking against the pricks, who had scripture!
And it is not to neglect to teach the scriptures, nor the apostles`' doctrine,
to bring people and children to the light within,
and the word in their hearts and mouths, to obey and do it,
which was the apostles`' doctrine; and they are sottish that are out of it;
and they were those that made proselytes, that brought not people to the word within,
nor to the light within, but from it.

[.discourse-part]
_Principle._ He saith, '`The apostle thought to do many things against the church,
and thought he ought to do so, and the light within did not inform his conscience.`'

[.discourse-part]
_Answer._ Did not Christ say it was hard for him to kick against that which pricked him?
And was not that within him that pricked him?

[.discourse-part]
_Principle._ And thou sayst thou art '`too ignorant of the ways of God,
and witnessing the meaning of his spirit.`'

[.discourse-part]
_Answer._ We do believe thee; therefore thou hadst better have been silent,
and have hearkened to the light within thee, and the word within thee,
and the word of faith and wisdom; which none hear, but who come to the light within.

[.discourse-part]
_Principle._ Thou sayst thou art '`too much troubled with carnal thoughts and vain imaginations,
and addicted to the world.`'

[.discourse-part]
_Answer._ Those dictates are not likely to own the light within, word within.
It is not a strange thing that thy spirit should stand against the apostles`' doctrine,
that is, light within.
Cor. ii.
4.

[.discourse-part]
_Principle._ Thou sayst, '`It is disparaging the scriptures to direct people to the light within,
rather than the scriptures, to direct them to eternal life.`'

[.discourse-part]
_Answer._ The scriptures many may have,
and may be from the light and spirit of God that was in those that gave them forth;
but none have eternal life, but who come to the light within,
and the spirit that was in them that gave forth the scriptures;
and to you this is the word of the Lord.

[.discourse-part]
_Principle._ Thou sayst, '`The light within is gross darkness,
and what darkness and blindness is there where the scriptures are not minded and known.`'

[.discourse-part]
_Answer._ The apostle, who directed to the light within,
did not call that gross darkness nor blindness; but turned people from darkness to light,
from the power of Satan to God.
And Abraham and Enoch were not in gross darkness and ignorance,
who had not the scripture to mind,
who were in the spirit and faith that they were in that gave forth the scripture.
They who come to witness the same spirit that was in them that gave forth the scriptures,
shall come to witness the covenant of God written in their hearts,
and shall not need to say, '`Know the Lord;`' these cease from man,
whose breath is in his nostrils; and they that come into this, own the scripture without,
and are in Abraham`'s faith.

[.discourse-part]
_Principle._ He saith, '`The elect may be deceived,
and fall from their own steadfastness for a time,
and come under death and the power of Satan.`'

[.discourse-part]
_Answer._ The elect seed is in the grave, which it is not possible to deceive;
and the elect shall be brought from under all the deceivers, and death, and bonds,
and shall come over the gates of hell, although the seed hath been in captivity.
And it is not possible to deceive the elect, it is the world that is deceived;
that which hath led captive shall go into captivity.
Eve, and the first Adam, may be brought into transgression; but Christ the second Adam,
the seed in you all, you must know, which is that which bruiseth the serpent`'s head,
and the ground of all deceiving.
And so the elect may lie under for a time, and suffer; but the election shall obtain,
and not him that wills, nor him that runs,
but come over to the crown of honour and glory.

[.discourse-part]
_Principle._ He saith, '`Satan deceives men into bringing them to a self-denying posture.`'

[.discourse-part]
_Answer._ It is not the devil that brings men to be humble, and to deny themselves:
that which teacheth self-denial is Christ;
that which keeps out of self-denial is the devil, for that he went from himself,
out of the truth.

[.discourse-part]
_Principle._ He says, '`They can never be clear of a degree of blasphemy,
that have the spirit of God in them and speak against ministry, magistrates,
and ordinances, and bid people listen to the light within them,
and to the spirit`'s teaching, and that they are all taught of God.`'

[.discourse-part]
_Answer._ They that witnessed the spirit and light within were taught of God,
and were moved of the Lord to declare both against ministers, magistrates,
and ordinances, that stood against Christ the power of God;
and these were called blasphemers, who were not, the scripture declares it;
but owned the power that ended all changeable things,
which upon all the heads of the transgressors and blasphemers came,
which power was a praise to them that did well.

[.discourse-part]
_Principle._ He saith, '`They say, that scripture may be bought and sold, and it doth not profit;
but the light within is of an eternal nature, an infallible guide; so obeying it,
they shall be sure of perfection and eternal life.
Now (saith he) those that say so are the poor, ignorant, and unstable souls.`'

[.discourse-part]
_Answer._ Cannot ye buy and sell the scriptures, and your sermons, and prayers?
And can any have the comfort of the scriptures, and an infallible guide, perfection,
and eternal life, and the soul established, and come out of ignorance,
but who come into the light and spirit of God within that gave forth the scriptures,
with which they come to know God the Father of spirits,
of whom they learned that gave forth the scriptures, and so come into the spirit,
and the bond of peace, and unity with the scriptures, with God, and one with another?
And the spirit of God doth not bring men to a dislike of scriptures,
nor ministers of Christ, but to see what estate and condition they were spoken forth to.

[.discourse-part]
_Principle._ Thou sayst, '`The measure of Christ must be so,
that you ought to lay down your lives for the brethren, and love one another,
much more to lay down your estates.`'

[.discourse-part]
_Answer._ When was there a priest in the nation that did lay down
his estate for the love of Christ or his brethren?
But he had a selfish principle in another thing.
Or when saw you a priest lay down his estate to save others out of prison?
But he is rather casting into prison till death, because they cannot give him tithes.
The apostle doth not say, have not we power to take tithes, but,
'`have not we power to eat and drink.`' And '`they that preach
the gospel live of the gospel.`' And they bring glad tidings;
but that is not glad tidings to cast into prison, and hale before courts;
and they that preached the gospel lived on the gospel,
that opened the hearts of people without men`'s compelling power.

[.discourse-part]
_Principle._ He saith, '`You must not give ear to the Quakers,
for they tell you your ministers look for their gain from their quarters,
and are hirelings,`' and this, he saith, '`is deceiving, and the depth of Satan,
and a lying, malicious spirit.`'

[.discourse-part]
_Answer._ The prophets`' spirit was not a lying and malicious spirit,
that cried against them that sought for their gain from their quarters,
and said they were hirelings, in which spirit are the Quakers,
and they see you walk in the same steps.
And take away your gain from you, and your hire, and you are suing in the courts,
and haling up and down,
which shows your spirits to be the false spirits the apostle speaks of,
which went out into the earth.

[.discourse-part]
_Principle._ Thou sayst, '`Above all things, beware of covetousness.`'

[.discourse-part]
_Answer._ If you had heeded that, you would have been better examples to the nations about you;
but in covetousness you are swallowed up,
and so are excommunicated out of the life which the prophets, Christ,
and the apostles were in; and so your reward from him you shall have.
And you are finding fault that the people are covetous,
and thus complain to the whole nation.
You should have complained of yourselves for being out of
the power of God that should have struck down that,
and that you are not in the life and power the apostles were in;
and so your teaching hath not such an effect with it as the apostles`' had.
So you have manifested and shown your spirits to the nations,
and show you want your covering.
And the apostles did not write abroad to the world, that their church was covetous,
and send to the magistrates, and complain to them.
Had not they here dishonoured the power of their church, if they had done so,
and shamed it, as you do yours?

[.discourse-part]
_Principle._ He saith, '`Many false prophets are gone out into the world; believe not every spirit;
and Satan transforms himself into an angel of light.`'

[.discourse-part]
_Answer._ These things the apostles saw come into the world before their decease,
the devil transforming himself into an angel of light,
and false prophets and false spirits gone out into the world,
and since the days of the apostles all that dwelt
upon the earth went after them and the beast,
but those who have their names written in the Lamb`'s
book of life before the foundation of the world.
And the apostle,
when Satan was transforming himself into an angel of light among the Corinthians,
brought them to the light in them,
which would '`give them the light of the knowledge of the glory of God in the
face of Jesus Christ.`' And John saw they that Christ said should come were come,
the false prophets and false spirits, and bid them not go after them;
and John told them '`they had the anointing within them, to teach them,
and needed not any man to teach them,
but as the same anointing taught them;`' and they '`should continue in the son,
and in the Father,`' where no false spirit was.
These false spirits, prophets, and antichrists, which Christ said should come,
which John saw were come, and went forth from them, have drawn tongues, peoples,
multitudes, and nations to be waters, and these are their fruits,
as Rev. 17:18. And now are people but coming from these waters and false spirits,
to the rock.
And these are they that draw the nations to be as waters
that have turned against the saints and the Lamb;
but the Lamb and the saints shall have the victory.
Nevertheless, these false prophets, beasts, antichrists, false spirits,
all inwardly ravened from the true spirit, have had the sheep`'s clothing,
else they could not have deceived the world, and led the world after them,
and could not have brought nations to be as waters;
and herein hath been the beast`'s power over all kindreds, tongues, and nations,
and his heads and names in the nations, and among the tongues.
Yet all these heads and names have agreed together in one against Christ,
the light which '`enlighteneth every man that cometh into the world.`' And the devil,
beast, and false prophets, made war against the saints and overcame them;
but the saints and the Lamb shall overcome them, and the devil shall be taken,
and with him the beast, and the false prophet, and Babylon shall be confounded,
and the Lamb and the saints have the victory.
Rejoice, ye saints and holy prophets, over them!
The Lamb and the saints shall have the kingdom, and power over all kindreds, tongues,
and nations, who are redeemed from them, and from the earth, to reign with Christ,
and atop of the devil and his angels, which cannot get into the seed.

[.discourse-part]
_Principle._ He saith, '`It is a boast of the Quakers,
to say that they have the eternal spirit of God in them,`' and saith,
'`they may properly use the word you to one; and taking off the hat is reverend, due,
and honour; and he must not quench the smoking flax, but be courteous;
and custom to whom custom; and to the law, and to the testimony.`'

[.discourse-part]
_Answer._ '`He that hath not the spirit of Christ is none of his,`' and that is eternal;
and he that saith you to one, shows he hath neither learned accidence nor the bible;
and the hat is the honour of men below, in the earth,
Adam`'s honour in the transgression, but Christ, the second Adam, saith,
'`I receive not honour of men.`' '`How can ye believe that receive honour one of another,
and seek not that honour that is of God only?`' And so this is the mark of an unbeliever.
And the apostles did not observe the Jews`' customs, nor the heathen`'s customs,
for if they had, they needed not have been persecuted by them.
To be courteous, is to do one another good; but how is this practised amongst you,
when you cast into prison those that cannot put into your mouths,
and for whom you do no work?
Where is your courteousness, here?
They break not the bruised reed nor quench the smoking flax,
that own the light that doth enlighten every man that cometh into the world,
and these neglect not their salvation;
but they that deny the light that enlighteneth every man that cometh into the world,
neglect their salvation, and such are they that break the bruised reed,
and quench the smoking flax.
The light brings to own the law and testimony; but many may have the scriptures,
and not the law and testimony;
for '`the law is light,`' and '`the testimony of Jesus is the spirit
of prophecy,`' and this was before the New Testament was written,
as Isaiah viii.
and that was before Matthew, Mark, Luke, and John, or any of the epistles were written.
And as for the rest of thy lies, slanders, and hard speeches,
they shall fall upon thyself, and be thy own burden;
the witness in thy conscience shall answer me in the day of thy judgment.
And they that have not the eternal spirit are none of his.
