[#ch-55.style-blurb, short="A Discovery of a Generation of Men Called Quakers"]
== Thomas Weld, Richard Prideaux, Samuel Hammond, William Coles, and William Durant, their book called, '`A Discovery of a Generation of Men Called Quakers.`' In it are the following principles.

[.discourse-part]
P+++.+++ First, '`that the soul is a part of the divine essence.`'

[.discourse-part]
A+++.+++ That which comes from God, which God hath in his hands, which Christ is the bishop of,
is of God, and divine and immortal, which many of the priests say is appetite, lust,
and pleasure; and '`the soul of Christ,`' say they, '`is human,`' which is earthy.
And so you that are come from one mother are not agreed here among yourselves,
and people begin to see you; the time hath been they knew not which of you to believe,
but now they believe in Christ, who is the bishop of their souls.

[.discourse-part]
P+++.+++ '`There lies a mystery of iniquity in saying,
"`the world calls them so,`" by such and such names,
or gives them their christian name.`'

[.discourse-part]
A+++.+++ There are names given by the heathen, the heathen outwardly, by which men are called,
and there is a new name, which the world knows not, written in the book of life;
here is the new man known, created after God in righteousness and true holiness.
Now who is this new man?
And this new name?
The world may call him by the old.
So it is not a mystery of iniquity to say the world calls him so.

[.discourse-part]
P+++.+++ '`It is a sinful neglecting of their families to wander
up and down.`' And the forsaking of changeable apparel,
he calls '`monkish holiness.`'

[.discourse-part]
A+++.+++ When people run into transgression from the life of God, into the earth,
then comes up the lust of the eye, the lust of the world, and the pride of life,
which leads them into all the fashions of the world; '`which is not of the Father,
but of the world.`' Now the lusts and affections must be mortified,
which have outwardly transgressed the pure principle of God within,
whereby the mind hath gone out into the creatures,
and things without whereby it falls under the creatures,
and so conies thereby to worship the creatures more than the creator,
who is God blessed forevermore;
being gone from the principle of God in their own particulars.
That is it which mortifies the world, when men turn to it;
and this brings off from all the lusts of the world, and excess, and affections,
and professions, whether they be such as thou calls monkish, or those of notionists,
or whatsoever; it brings into the possession, into the life which mortifies.
For this which thou calls '`monkish holiness,`' is like your own,
who have not the spirit that they lived in who gave forth the scriptures;
all holiness which stands out of that, is self-righteousness.
And the apostles, and the faithful in all ages, that wandered up and down,
did the will of God, spoke the word of God, were commanded and moved of the Lord,
forsook all for Christ.
Christ did not teach men sin.
And he that doth not forsake all, is not worthy of him, house, lands, wife, children,
whatsoever, he that esteems any of those more than Christ, lives still below,
he lives still, not given up, he is not worthy of him.
And they that do not forsake all and come out of all,
are in the sinful neglect of the family of the Lord of heaven and earth,
and they stick below in their own ceiled houses, habitations, nests, holes, and rocks,
calling unto the mountains, and there garnishing the sepulchres,
and living in all fashions, customs, honours and pleasures of the world.
And the priests`' work hath been this, to teach the people to keep in the lust,
and not to forsake and come out of all their lusts to Christ,
(who are not worthy of him,) and if any do,
they look upon them to be sinful neglecters of their family;
which wisdom was before all things were made,
and is the preserver and finisher of all things, and not the destroyer,
but that it rebukes, and in this are men ordered to God`'s glory.

[.discourse-part]
P+++.+++ The Quakers deny imputed righteousness, prayer, baptism; church government, ministry.

[.discourse-part]
A+++.+++ That ever ye five that are called ministers should
thus publish your lies to the nation!
The higher powers; the one government; the church, the pillar and ground of truth;
the ministry that is in the spirit, that ministers to the spirit in the prison;
baptism with the spirit into the one body; prayer in the spirit; the Lord`'s supper,
who dwells in the saints and walks in them, and sups in them; the gospel,
the power of God, and imputed righteousness to the believer, are owned.
'`Abraham believed,
and it was accounted to him for righteousness;`' and '`Christ
come,`' and '`Christ in you,`' is the end of the belief,
who is the justification itself, and righteousness itself,
nigher than when they did believe.
And so here is justification itself without imputation, the righteousness of God;
here the belief ends.
And all these things are owned according to the scriptures;
but all such teachers that are in the earth, and teach for money and means, we deny;
and you who baptize, and sell your prayers, and preaching, and supper for money, we deny.

[.discourse-part]
P+++.+++ '`Will a discerning of the gospel mysteries prove a power
to discern the state and condition of the soul,
what it shall be to all eternity?
Is not this a large ignorance?`'

[.discourse-part]
A+++.+++ The ministers of the spirit watched for the soul,
the prophets and apostles knew its state, and knew Christ the bishop of it,
and saw when the soul was in death, and saw when God had pleasure in it, when it lived,
and saw the soul in God`'s hand.
For who have the mysteries of the gospel, which is the power of God,
which gives liberty to the captive soul; this is glad tidings to the just.
Such a one is a true workman, that divides his work aright,
and is not ashamed of his work, of his building, but presents the soul to God,
and knows when it is in death, and when it is living.
And so they who are come up into the bishop, Christ, are one soul,
they know the hand of God which, the soul lives in,
(which is the power,) and so know it from eternity to eternity.
And so ye priests who do not discern the soul and its state to eternity and from eternity,
ye are not in the mystery of the gospel which gives liberty to it, neither have ye it;
for ye are stumbling at the light which enlighteneth
every man that cometh into the world,
which comes from Christ the bishop of the soul,
and so your darkness cannot comprehend that.
And so what fellowship hath the light with darkness?
It hath no fellowship with it, for your darkness cannot comprehend it,
though it shines in your darkness.
So for you to talk of saints judging the world, and meddle with such things,
who are to be judged by the saints,
who are in that darkness which cannot comprehend the light that shines in you,
you have not light to comprehend the saints that are in the light,
who have the just weight, measure, and balance, who are the judges of the world,
reaching, measuring, answering agreeable to that of God in every man.
And you are stumbling at such as are become the sons of God, adopted sons and heirs,
and of the flesh and bone of Christ, and of his mind and spirit,
who are in the possession of the scriptures, the durable life of the saints,
which makes you (that cannot comprehend the light in your own particulars) to rage;
for none come to witness the sonship and heirship,
but who come to the light in their own particulars, and receive it,
and with it comprehend darkness, which the light expels away.
Such see over the night, and are the children of the day.
And you five priests have shamed yourselves,
that do not know the soul from eternity to eternity.

[.discourse-part]
P+++.+++ '`It is blasphemy to say the soul is a part of the divine essence.`'

[.discourse-part]
A+++.+++ Ye may read in this book that some of the rest of the priests that are called ministers,
say Christ is human, and the soul is a creature.
Some again say, it is a part of the divine essence, it is immortal; and again,
it is appetite and pleasure; and in this now is their confusion made manifest.
The soul is that which came out from God, and is in God`'s hand,
which hand goes against him that doth evil,
and transgresseth against the principle of God that is in him,
which goes against the lust which wars against the soul, which hand the soul being in,
praises God, the hand is felt,
the power felt that turns against that which wars against it.
Here the soul magnifies God, rejoiceth in God the saviour, and praiseth God.
Here is God`'s pleasure.
The living Lord taketh pleasure in the living soul.
And appetite and pleasure are human; these are not immortal, which the soul is.
And so you five have judged yourselves to be blasphemers,
who said the soul was part of the divine essence, and yet it is blasphemy to say so.

[.discourse-part]
P+++.+++ '`Christ is to rule as a king; but in all he doth not.`'

[.discourse-part]
A+++.+++ Those, and you, that hate the light, will not hear him,
nor have him to rule over you and them; such are for the sword,
and to be slain before him.

[.discourse-part]
P+++.+++ '`And the light which doth enlighten every man that cometh into the world,
is not sufficient to salvation, nor gives a light sufficient to bring to the gospel,
to know the mediator; and that light which hath enlightened all men, is not the way,
but a created light by Christ.`'

[.discourse-part]
A+++.+++ All lights were made and created by the light which doth
enlighten every man that comes into the world,
and this is the eye of the soul, which gives to see Christ the bishop of it,
from whom it comes.
And this light is the covenant of God which doth
enlighten every man that cometh into the world;
and this light doth let see the mediator, the salvation, the gospel.
And all that are from the light are out of the truth; they that went out of the truth,
the god of the world hath blinded their eyes,
lest the light of the glorious gospel should shine in them, which is the image of God.
So created lights were created by it; and none know the truth but by this light;
and all men`'s professions are but from that nature,
that are out of this light which hath enlightened every man that cometh into the world,
which all men must come into, before they come into unity with God.
And none can know the mediator, nor Christ, by the created and made lights,
which were made by the light Christ;
but as they come into the light by which they were made,
that gives them the wisdom of the creation, and lets them see how they were made.
And so they that hate the light, receive not the spirit of God,
but remain in their natural state; and what such know, they know naturally, from books,
authors, and studies.
So men who hate the light, come not to Christ the author of their faith.

[.discourse-part]
P+++.+++ '`How ridiculous is it to say, Christ dwells in all, so is in all.`'

[.discourse-part]
A+++.+++ Christ is the light that doth enlighten every man that cometh into the world;
and the scripture saith, Christ is searching the hearts of the wicked,
and trying their reins,
and bringing their thoughts to the light that shines in the darkness,
and the darkness comprehends it not.
He was in the saints, and the saints were in the light, so he '`is in all, over all,
and through all,`' and blindness and darkness comprehend him not,
who fills heaven and earth.
'`If thou goest to the utmost parts of the earth he is there; if thou goest to the deep,
and to the nethermost hell, he is there;
where wilt thou fly from his presence?`' Have not the holy men of God found this?
Are all ye ministers of the letter so ignorant of the letter?
so short of the state that gave it forth?
And I say, such as sit under the shadow of darkness shall feel,
if they do but hearken and listen;
and such whose hearts are bad shall feel him searching and checking them.
And such as go down to the nethermost hell, and to the utmost parts of the earth,
shall feel him present, if they never stirred forth,
and should not need to wander for a habitation; but should feel their habitation.
Such then should come to know their soul`'s progress, which is an inward travail,
before it come into its bishop, Christ, the rest, him by whom the world was made,
who was before it was made, glorified with the Father before the world began.

[.discourse-part]
P+++.+++ '`And it is an error to say, that the righteousness of Christ, justification,
sanctification, and redemption, are all within.`'

[.discourse-part]
A+++.+++ If Christ be not within, they are reprobates; and reprobates can talk of Christ,
and they that are out of the truth and the life, can talk of Christ,
and bring the scriptures; but they who have Christ within, have sanctification,
redemption, and justification, they have the wisdom and power of God;
for reprobates are talkers without, but he that hath Christ hath all the other,
redemption, sanctification, wisdom, righteousness,
and the work is known within as he comes out of the fall of the first Adam.

[.discourse-part]
P+++.+++ '`It is error to say, the light that discovers sin, justifies.`'

[.discourse-part]
A+++.+++ The light which is the covenant of God,
that doth enlighten every man that cometh into the world, discovers sin,
makes it manifest, blots it out, justifies, sanctifies, redeems,
and condemns them that hate it.

[.discourse-part]
P+++.+++ '`It is an error that the light within men will bring men to the fear of God,
and lead men to justification, sanctification, and righteousness.`'

[.discourse-part]
A+++.+++ None come to justification, to righteousness, who are out of the fear of God,
nor to receive his righteousness; but they who come to the light within,
which comes from Christ the righteousness, the wisdom, come to the justification,
and sanctification;
and ye are in the error that are not in this light that lets see and leads from it.

[.discourse-part]
P+++.+++ '`Perfection in holiness cannot be attained in this life,
for Adam was under such a covenant, he had no mediator upon the breach of the command.`'

[.discourse-part]
A+++.+++ God said to Adam, '`the seed of the woman should bruise the serpent`'s head,`' Christ,
the promise, the mediator, made the way, which was the way in again to God,
the way of man`'s redemption,
and got down the serpent`'s head which got up in transgression,
that Christ the head should bear rule; that the seed of the woman should have dominion,
the second Adam, the seed Christ Jesus, the Lord from heaven.
Perfection is not to be attained to by the life ye live,
until ye come to the principle of God in you;
but the life that David lived in saw an end of all perfection.
And all who come to Christ the second Adam, come to perfection;
and all who attain to him, attain to perfection in the life of God out of the first Adam;
but who deny the light '`that enlighteneth every man that
cometh into the world,`' and rest in the first Adam,
the life they live in, denies perfection, and they never own it in the life they live in.
But those who come into perfection, come into Christ, a new life,
out of Adam in the fall, in transgression.
All physicians to sick men are to make them perfect.
And do ye say, make none whole, make none perfect, makes never a man perfect?
For being made whole, they are made perfect, for sin wounds;
for the ministry of God was to bring people to the perfect man,
to '`present them perfect.`' These were physicians of value and of worth,
whereby the body, soul, spirit, and all, were cured,
'`and they glorified God in the body and spirit.`'

Now ye, that say they shall not be perfect,
and that none shall be without sin upon the earth, no perfection in the life we live in,
are physicians of no value; ye are not worthy to have the name of physicians, ministers,
nor teachers, Thomas Weld, Richard Prideaux, Samuel Hammond, William Cole,
and William Durant;
for ye are pleading that while men are upon earth they must have a body of sin,
and that he that saith otherwise is a deceiver.
And so ye keep them in their wounds and sores, putrifying and imperfect,
and are not makers up of the breach, and binders up of the wound.
And the Lord saith, '`Though their sins be as red as crimson,
I will make them as white as wool,
and will blot out sin and transgression.`' And this tender love and kindness of the Lord,
and mercifulness to sinners and transgressors,
hath the Lord made manifest amongst them whom the world in scorn calls Quakers.
And it is not a strange thing that you would not
have people to forsake the fashions of the world,
who are thus hung about with ribands, and cuffs, and scarfs,
and your double boot-hosetops, more like stage-players than ministers.

[.discourse-part]
P+++.+++ '`Perfection is a fancy.
Those were not words of true physicians who brought men to a perfect man,
to the growth up in perfection amongst the perfect ones who speak wisdom.`' They say,
'`It is no where said that the law is fulfilled in any saints in this life.`'

[.discourse-part]
A+++.+++ They that love God keep his commandments.
Christ '`is the end of the law to every one that believes,`'
and who are in him are in the end of the law.
And all that dwell in love, dwell in God, and love is the fulfilling of the commandment;
they who are of the seed of God keep the words of God,
but the beast and false prophets since the days of the apostles,
who have inwardly ravened, are turned against the royal seed of God,
that keep the commandments of God;
and none of you that raven from the spirit of God can keep God`'s commandments,
though ye have all the saints`' words; for the saints witness the end of the law,
and witness perfection and a perfect man, and spoke wisdom among them that were perfect,
and growing up to perfection.

[.discourse-part]
P+++.+++ '`That Christ gives to every man a saving light, we utterly deny.`'

[.discourse-part]
A+++.+++ He is '`the true light that enlightens every man that comes into the
world,`' (saith John the minister of God,) and he is '`salvation to the
ends of the earth,`' and they that hate the light,
neglect their salvation,
and turn '`the grace of God into wantonness,`' and deny the Lord that bought them.
And '`every one that hath heard and learned of the Father
cometh to the son;`' and none hear or come to the Father,
that come not to the son;
none but they who come to the thing that is transgressed in them,
and the light that every man that cometh into the world is enlightened with;
nor do they hear or learn of the Father, or come to the son, but by that;
and the light that lighteth every one that cometh
into the world is the salvation to him that believes,
and he that doth not, it is his condemnation.

[.discourse-part]
P+++.+++ '`But how dare these men lift up themselves in their blasphemous pride,
to say they are pure as God.`'

[.discourse-part]
A+++.+++ Doth not Christ say,
'`Be ye perfect as your heavenly Father is perfect?`' Is that blasphemy?
And is it not said, '`Be ye holy, for I am holy?`' is that blasphemy?
Whose ministers are you?
Was not this the work of Christ and the apostles?
'`Without holiness ye shall never see God,`' and
'`as he is so are we in this present world.`'

[.discourse-part]
P+++.+++ '`The word of God is contained in the scriptures.`'

[.discourse-part]
A+++.+++ The scripture saith God is the word,
and '`the heaven of heavens cannot contain him.`' Are ye not more like men void of reason,
than ministers, whose ignorance of the scriptures thus appears?
They say God is the word, and the scripture is the word,
and Christ is the word who fulfils them.

[.discourse-part]
P+++.+++ '`The scriptures were given forth, some more darkly, some plainer.`'

[.discourse-part]
A+++.+++ They who gave forth scripture, and they that are in that in which it ends,
to them the scripture is not dark;
but such as are from the principle of God in their ownselves, they are in darkness,
which blinds their minds, and the scriptures were not given forth darkly,
but in the light, but you who are from the light are dark.

[.discourse-part]
P+++.+++ '`The apostles ordained them elders by a mediate call:
and we are convinced clearly of a mediate call to
the work of the ministry and of the word.`'

[.discourse-part]
A+++.+++ That which made the officers and overseers in the church amongst the saints,
before the apostacy, was the holy ghost, which holy men spoke scripture from;
that was what made them overseers, and that was not mediate but immediate,
that did oversee in the church of God.
And we do believe that you elders, and members, and those called ministers,
are all mediate, and your order and gospel since the days of the apostles;
who are such as Christ said should come, inwardly ravening forth from the spirit of God,
and have got sheep`'s clothing;
since the days of the apostles people have walked after you,
and you have deceived the world and nations.
But we see, that the false ministers, the worshippers of the beast, antichrist,
and the deceivers, among whom is the devil to deceive, are now taken,
with the false prophet, the beast, and the mother of harlots,
and confounded and cast into the lake of fire,
and the Lamb and the saints shall have the victory.
And the gospel is immediate, and he is cursed that preacheth another; the word, I say,
is immediate, it lives, abides, and endures forever.
And the ministers that are in the spirit are immediate,
and these are furnished with the mysteries of the gospel, and their calling is immediate.
And the overseers of the church which the holy ghost makes, are immediate;
and all that are in the life that gave forth scripture,
(and none know the scriptures but by it,) are immediate;
that which doth convince of sin is immediate.
But now your call is mediate, your ministry, your overseers, knowledge, word, gospel,
people, and church are mediate.
We do believe you,
all this is so amongst you since the days of the apostacy from the apostles`' doctrine,
power, life, and spirit, with which ye are judged,
and who are in the life they are in that which gave forth scriptures,
which you are ravened from, and are not like to talk of immediate.

[.discourse-part]
P+++.+++ '`The scripture is the word and the rule.`'

[.discourse-part]
A+++.+++ The scriptures are the words of God, and Christ is the word in whom they end;
and the word of God is the end which fulfils all scriptures, which came to the prophets,
which the apostles preached, by which they discerned and spoke forth the words,
and saw the fulfilling of the words; and the scriptures of truth cannot be broken,
but are fulfilled by Christ the word.
And the spirit is the rule that gave forth scriptures,
and that led the saints into all truth.

[.discourse-part]
P+++.+++ '`Thomas Castel went naked in the streets of Kendal,
and Thomas Holmes of Kirkby Steven.`'

[.discourse-part]
A+++.+++ This hath been a figure of your nakedness, who are Egypt spiritual,
and the Ethiopian black.
And '`the prophet Isaiah did not put off all his clothes,`' say they,
contrary to the prophet`'s words.
He was to go among all the transgressors in Ethiopia and Egypt,
a figure of their nakedness.
So, since the days of the apostles and the apostacy, ye have gone from the spirit of God,
and inwardly ravening from that, ye have wanted the clothing with the spirit,
ye have had only the outside, the sheep`'s clothing, but have been naked of the life;
therefore the Lord hath moved his servants to give a true sign amongst you,
and not a lying one; who have their clothing of the spirit, which ye want;
and ye shall witness the truth of the Lord God in the sign,
if ever ye come into the true clothing of the spirit of God.

[.discourse-part]
P+++.+++ '`And ye say Christ did not mean as he spake, when he said,
Be not ye called of men masters.`'

[.discourse-part]
A+++.+++ Which shows they are none of his ministers who trample upon his commandments,
and teach people that it is lawful to break them,
pleading the lawfulness of their being called of men masters.
So as for their being called of men masters, standing praying in the synagogues,
their long robes, salutations, their tithes, and their pulpits,
these are the works of the perfect Pharisees; all people may look upon their fruits,
their works, and practices, and see the very image,
and that they have their very garments and places, according to their condition, fruits,
and works.
And as for all the rest of their hard speeches, lies, slanders,
vilifying and railing words which they have poisoned people with,
they will be their own burden, and fall heavy upon them, and turn upon their own heads.
Their way is compassed, their bounds are set, and their limits,
and in this the day of their account, every one shall feel his words to he his burden.
And their patience had been better then to have uttered forth their folly,
and published it to the nation.
But the day is come that tries every man`'s work; and a witness is rising in people,
the day-star is risen, the morning is broke, the sun is rising,
that people may not make lies their refuge, neither feed upon them, nor upon any thing,
but what comes from God, the living bread that comes from God above;
which who eats of lives forever.
Many have their bread and their water, that hunger no more, and thirst no more.
