[#ch-56.style-blurb, short="The Worcestershire Petition to the Parliament"]
== '`The Worcestershire Petition to the Parliament,`' which is said to be signed by six thousand.

[.discourse-part]
P+++.+++ '`He hath made a law commanding all people to whom we
preach the gospel to allow us a sufficient maintenance,
that we may not be hindered from or in his work.`'

[.discourse-part]
A+++.+++ The scriptures and the apostles do not speak of
any such thing as that Christ made a law for them,
commanding all the world to whom they preached to allow them a sufficient maintenance,
that they might not be hindered from or in their work.
What!
Will maintenance hinder them if they have it not?
Was it not the command of Christ to give freely as they from him had received freely?
And then if any set meat before them they might eat.
But if a law commanding all the world to give a sufficient maintenance
and allowance to the apostles and disciples had been first,
they might have been sure of maintenance,
and this had been the way to have clogged the people`'s minds,
and have brought them into trouble; whereas the gospel was always glad tidings.
But if the apostles had not preached to the world, without this law which ye speak of,
commanding all the world to give them sufficient maintenance,
what a condition would all people have been in.
But they that had received freely, were to give freely.
So you have manifested your spirits, to be the deceivers of the people for means.
That ever six thousand people should say he made a law commanding all the world to whom
they preach the gospel to allow them sufficient maintenance! when Christ saith,
they (the disciples) were to preach as they went;
and they were to preach if they did not receive them;
and they were to go into all nations.
Yet the apostles did not plead a law where they came,
that they were all to maintain them; no, they were in fasting often,
and would not use their power to eat among many people; though they had power,
yet they would not use it.
And so the maintenance did not hinder the apostles from their work,
for they preached often in fastings,
and sometimes their own friends communicated to them when they
were up and down among the heathen in other nations preaching.
The apostles did not plead a law to the nations whom they preached to;
and thus they brought glad tidings, keeping the gospel from charge.
Are not you six thousand men ashamed to petition for a maintenance for your ministers,
that you should publish in a petition your nakedness to a supreme power of a nation,
that you are not able to maintain your ministry!
That the churches are not able to maintain their ministers!
Doth not this show your beggarliness, and that you are of the seed that is begging bread?
When the scriptures saith, '`The righteous are not forsaken,
nor their seed begging bread.`' And in this have you not shamed your ministers,
that they have no better vineyards, ploughs, and flails?
Did ever the apostles or their hearers, when they came into a nation,
petition to the powers of the earth for means?

[.discourse-part]
P+++.+++ And ye say, '`Where any man will not do justly,
and pay the labourer the wages he owes him, the magistrate must see justice done,
or else I know not what he hath to do.`'

[.discourse-part]
A+++.+++ The apostles, ambassadors, and messengers of the Lord Jesus Christ,
who were to go to all nations to preach the gospel,
had not a law at the magistrates`' hands to give them wages,
did not hale their hearers before them to give them wages,
or put up petitions before every supreme of the nation before whom they came;
this was not the work of the apostles, messengers, and disciples,
who were to go into all nations to preach the gospel.
When they had preached the gospel to the nation,
they did not petition to the supreme powers of the nation, powers, or principalities,
or kings, for maintenance from their hearers, as you do now.
Oh! this stinks, and shows it is out of the power which the apostles, disciples,
and messengers of the Lord Jesus Christ were in.

For they would have made their gospel to have stunk,
if they had come into all nations to preach the gospel,
and then after they had preached it,
if their hearers would not have given them maintenance,
to have petitioned to the supreme authority of the nation,
and have haled their hearers into courts, to assizes, sessions, and benches.
Would this have been glad tidings to the nations, or trouble to the nations?
They would have been but deceivers, and pretenders of glad tidings,
and bringers of trouble to the nation, and seekers of themselves, and for themselves.
And this would not have been to do the work which the Lord Jesus Christ sent them about.
They would not have been preachers of the gospel that '`live of
the gospel,`' such as might use their power and would not.
And the power of God is the same now as ever it was,
and it tries all the spirits that are gone out into the world,
which have apostatized since the days of the apostles, out of the apostles`' power;
and now with the power the apostles were in, are they comprehended,
which are gone out of the power which the apostles were in.

[.discourse-part]
P+++.+++ '`And ye speak of Jonas`' temptation, and yet of your comfort in your studies.`'

[.discourse-part]
A+++.+++ The power that Jonas was in, ye are far from,
or those that are to divide the word aright,
but are swallowed up in the great temptation of the world, pride and covetousness,
in that are ye drowned, and in hard-heartedness, as the jails in the nation witness.
Such as cannot give you maintenance,
and such as are moved of the Lord God to come and speak to you,
are cast by you into jail,
which shows that you are in another power than the apostle was in, who said,
'`Quench not the spirit;`' and than the prophet was in, who said,
'`Limit not the Holy One;`' and denying prophecy.
So now your power and authority to your ministry
with the spirit of the Lord God are fathomed,
and you to be out of the spirit the apostles were in,
and to be spirits that are gone out into the world, and into the earth and fall;
and so you usurp the authority, and usurp the ministry in usurping the authority,
as yourselves may see.
Read the scripture of the prophets and apostles,
and there read the fruits of your ministry and actions; try them by plain scripture.

[.discourse-part]
P+++.+++ '`Ye say that the ministry hath no power to put you out of the vineyard,
but to persuade others to do it.`'

[.discourse-part]
A+++.+++ Are the ministry in the vineyard of God, and have they no power,
have they no authority there in the vineyard?
Are the magistrates then to put them into the vineyard, and to take them out?
All those that are labourers in the vineyard must persuade to put into the vineyard.
Do not you in this show your ignorance of the apostles`' doctrine, and of their work,
who rebuked, stopped the mouths of gainsayers, had power to silence,
had power to try spirits, had power to judge, had power to defend?
Now have you not in this (if you be ministers) dishonoured your power and authority;
and have shown that you are out of the power, and are those that cry to the mountains,
'`fall on us,
and hide us from the glorious presence of the Lord,`'
which is arising to shake terribly the earth.

[.discourse-part]
P+++.+++ '`So if the ministers`' maintenance be taken away,
there is little likelihood of a ministry long.`'

[.discourse-part]
A+++.+++ It seems the maintenance hath been that which hath caused them to preach,
and held them up, so take away their maintenance, down falls their ministry.
But I say the power will stand, and the administration of the spirit,
and the hearing of Christ, and the teaching of God,
if men take away all their maintenance, and cast them into prison for speaking.
But this holding up of ministers by maintenance is
that which came up before the apostles`' decease,
among those who taught for filthy lucre`'s sake,
and through covetousness made merchandise of the people;
through the love of money they erred from the faith,
and pierced themselves through with many hurtful lusts,
and admired men`'s persons because of advantage, and taught for gifts and rewards:
these were come up before the apostles`' decease.
Now these teachers who admired men`'s persons, taught for filthy lucre,
the love of money, and covetousness, the apostle saw before his decease,
after whom the world hath since run.
Take away their money and their lucre, and their gifts,
and see how long these will preach.
Now have you showed your root, your offspring is found out.
Now, the apostles preached, and were ministers that stood,
who judged the root from whence ye are sprung,
for your root was come up before the apostles`' decease.
But now ye cry, if maintenance be taken away,
there is no likelihood the ministry will stand long.
And we say so too, we know that take away your maintenance, and down falls the preacher.
Therefore,
with petitions are you troubling the courts and magistrates for your livelihood,
but if ye were true ministers ye would be in the work, in the vineyard of God,
and would be ashamed of such things, and with the power of God cover your nakedness,
and not be beggars, and petition for outward things;
ye dishonour the power of the Lord God,
and cause his name to be blasphemed among the heathen.
And so, for shame! let your mouths be stopped forever, for saying ye are ministers.
The power would open the hearts of people if ye were in it, and make them to give you,
that there would he no want; and then the gospel would be preached and you live in that,
and glad tidings be known to all nations, and men would not be cumbered about courts,
and put in prison by you, whom you do no work for.

[.discourse-part]
P+++.+++ Ye say, '`shall men have leave to preach,
railing against Christ`'s ministers and church?
A reproach to the world.`' And '`hath Gyles Calvert owned his name
at them?`' And ye speak of your '`liberty of the pulpit;
but that the pulpit should not be Satan`'s oracle; as apothecary shops keep open poison,
so Gyles Calvert doth poison for souls.`'

[.discourse-part]
A+++.+++ This is not the way by railing, to stop poison;
but your pulpits have been like shops of poison, even to poison nations;
for have you not poisoned many people and made their minds envious?
And most of your stuff hath been railing one against another; but had ye been ministers,
or spoken the truth in the love of it, it would have preserved people in peace and unity,
and ye would not have sought yourselves.

And Gyles Calvert`'s,
(which you call an apothecary shop,) hath been a place where many
of your actions and fruits have been discovered and made manifest;
not against the church of God, not against the ministers of God and Christ,
not against the magistrates that live in the fear, life, and power of God,
but against injustice and persecution,
and the apostates got up since the days of the apostles,
as ye confess if your maintenance be taken away, the ministry will fall.
Now the power is that which causeth people to minister to any that ministereth to them,
not by compulsion, but freely, and this is acceptable and pleasing to God,
which the Lord loves.
And so all your poison of your pulpits, as Satan`'s oracles, hath been like such a thing;
for the pulpiters are those who have caused the great
persecution and imprisoning for speaking to them,
and because they will not give them maintenance; and so you quench the spirit,
and that which quenches the spirit is not of God;
for in the true church '`all may prophesy one by one;
and if any thing be revealed to him that sits by, the other must hold his peace,
that all may learn and be comforted.`' The spirits
of the prophets are subject to the prophets.
And this was the order in the churches of God, before the apostles`' decease.
But since their decease, amongst you that are apostatized from them, this is disorder,
and sets you all in an uproar and confusion.
So your church and pulpit are more like Satan`'s oracle than the church of God;
and you have been in your pulpits more like women`'s scolding to the cuckstool,
which you speak of, than men that preach the gospel;
as the parishes may witness how they have been burdened with your
railing against other people who have not been present with you.
And when any of them have come to you, you have cried, take them away, they disturb you.

Is not this worse than women`'s scolding;
for women will stand and scold one with another, but ye will scold behind their backs,
and cannot endure to speak to their faces, but cry, to prison with them.

But the rod is gone over you, and you are come under the scourge, the whip, and the lash,
for your evil words, which have corrupted your manners.
When ye should have been preaching the peaceable way to the kingdom of God,
ye have been bringing people to strife,
throwing them into prison for speaking a word to you,
and such as cannot give you maintenance, whom you do no work for.
But the sentence spoken in Matthew is coming upon you;
ye cast into prison till death because they cannot give you maintenance,
therefore ye are far short of visiting them who are in prison.
And these covers will not cover you.
And all your hard speeches which you have vented forth in your book,
are not worth mentioning; but they will come upon yourselves;
for every one of your words shall be your burden.
Now fools may subscribe their hands to things they know not,
and go with a multitude to do evil;
but wise men consider and ponder the things beforehand.
So all your petitions, the holy scriptures of, the prophets, Christ, and the apostles,
read and try them,
whether ye have ever an example amongst any of the ministers of the gospel,
that ever put up a petition to any supreme of a nation;
or that Christ ever gave them any such command,
that his disciples should go and beg with a petition
to the supreme powers of the nation for maintenance?
Have not you in this dishonoured the gospel and christianity,
and showed that you are not of the royal priesthood, nor of the royal seed,
nor everlasting covenant?
nor you ministers to be those that do freely give, who have freely received?
but to be such whose spirits are in the earth,
and that you petitioners are not able to maintain them!
Which all magistrates that stand in the fear of the Lord God will judge,
and so see that you have shamed yourselves, your ministry, and church,
and that you are not a vineyard, that you have not a flock to give you milk,
but they must be fain to give you; and the magistrates must give your ministers milk.
And so ye have showed the slothfulness of them that have ploughed,
and are not made partakers of their hope, but have lost it.
In vain have they ploughed, and thrashed, and not got out the corn.
And in all this have you not showed your idleness,
that ye have not laboured and got a vineyard, and thrashed and got corn,
and have not ploughed and sowed the seed?
And will not the magistrates see you in this?
And have not they wronged you in maintaining you in idleness?
Will not the magistrates see that they have done so, and will be packhorses no longer,
nor executioners for you, who have executed your malice upon them you do no work for,
neither have hired you,
and cast them into prison when they have spoken to you to repent and fear God.
And so it is time for the magistrates to do justice,
and execute the law upon you idle vagabonds.
