[#ch-57.style-blurb, short="Railing Rebuked, or a Defence of the Ministers"]
== William Thomas, a minister of the gospel at Ubley, (so called,) in his book called, [.book-title]#Railing Rebuked, or a Defence of the Ministers.# His principles follow.

[.discourse-part]
P+++.+++ He saith, '`his epistle reflects upon two sorts of persons;
and that many false prophets have risen.`'

[.discourse-part]
A+++.+++ The work of the ministers of the gospel was not to reflect upon persons,
or strike at creatures, (as thou sayst,
two sorts of persons,) but they struck at the power which captivated the creature,
to the intent that the creature might come into the liberty of the sons of God.
And so thou that art reflecting upon persons,
dost show a mark of thy being a false prophet; instead of speaking of the power,
thou art reflecting upon persons.
And this reflecting upon persons was never the way to beget to God;
but that which strikes at the power which captivates creatures,
reacheth to the witness in prison,
and brings people into unity with God and one another in the spirit,
which is the bond of peace.

[.discourse-part]
P+++.+++ '`To love the word for the good parts,
that in regard of the Christian is a dangerous thing, and in regard of the word of God,
a dishonourable thing.`'

[.discourse-part]
A+++.+++ Where the good parts are not in the Christian,
that is a dishonourable thing to the word,
and causeth the word of God to be evil spoken of as the
whole assembly of you ministers have done by your bad conversations,
earthly, covetous, impatient spirits,
that cannot endure any should speak but yourselves in your places.
So by you hath the word of God been dishonoured, and not honoured;
for the apostles wrote that they were to show themselves patterns
and examples to the flock of God in life and conversation,
that the word of God might not be evil spoken of.
Now where the word is evil spoken of, and the bad parts in a Christian proceed,
this grieves the righteous, and causeth the truth to be evil spoken of;
and the word makes them vessels of honour in whom it is.

[.discourse-part]
P+++.+++ '`Now when Christians leave the word, and sacraments, and sabbaths,
it is a dangerous pride, lifting up the light within, as they do.`'

[.discourse-part]
A+++.+++ The Christians that denied the sabbaths, and witnessed Christ the substance, the rest,
said,
'`The light that shined in their hearts would give them the light of the knowledge of
the glory of God in the face of Jesus Christ.`' And they lifted up Christ the light,
and they walked in him, the covenant of God and of light, to the Jews and Gentiles;
which who walk in, are in peace with God, and unity one with another,
and have the light of life, and rest,
and all are in the dangerous state that are out of that.
And as for the word sacrament, there is no scripture for it,
but it is one of the Papists`' common words, and the light brings off from it,
and the Jewish sabbath.

[.discourse-part]
P+++.+++ '`Buy the truth, and sell it not,
not pleading for sufficiency of a common light.`' And '`leaving
their callings as the monks.`' And '`their books flying abroad,
their wings unclipped.`' And '`no mention of eternal
salvation from the wrath to come.`' And he saith,
'`he loves the word, sacraments, sabbaths, and ministry.`'

[.discourse-part]
A+++.+++ Christ came to put an end to the Jewish sabbaths, and the apostles preached their end,
and forsook all for Christ; and so, to revile such as are in the same power,
and to call it by the unsavoury expression, '`monkish,`' thou and you are more like that,
that tell of sacraments that are from the monkish holiness.
And for speaking of clipping the wings of our books that fly abroad,
that is another unsavoury expression, and shows your spirit,
that it is not able to resist that spirit that gives forth the books.
As for the word and ministry, thou hast shown thyself against them,
though thou professes the scripture to be the word.
But those are the words of God, which Christ the word fulfilled,
and this the ministers of Christ witness.
And ye never read that the ministers of the gospel said they loved the Jewish sabbaths,
and held up the sabbaths; these were the ministers of the law that held up the sabbaths,
which Christ, the rest, came to put an end to, by whom the world was made,
who was before it was made,
'`glorified with the Father before the world began.`' And you sell the truth,
and take the world,
who deny the light that lighteth every man that cometh into the world,
which is sufficient to him that believes in it.

[.discourse-part]
P+++.+++ '`We exercise and order our preaching for the getting of money and maintenance:
and the greetings in the markets, are but that which humanity requires,
nor to be called of men rabbi, else Christ would not have taken it.
Must a minister lose the members of his church, and the maintenance of his place,
both at once?`'

[.discourse-part]
A+++.+++ Christ said to his disciples, they should know the false prophets by their fruits,
and said, '`Be not ye called of men master, for one is your master,
even Christ,`' and denied the Pharisees`' greetings in the markets,
which thou calls human right.
And the apostles ordered not their preachings to get money by them;
but they laboured to keep the gospel without charge;
and the ministers of Christ brought the people off the Jews`' assemblies,
and their maintenance both.
And ye that are found out of the apostles`' doctrine, in the apostacy, such as leave you,
that you do no work for, how can you expect that they should give you maintenance?
Or how can you in righteousness take maintenance of them that you do no work for?
So if ye lose the members, will ye take the maintenance?
which of the apostles did so?
Nay, is it not the way to gain members, to deny the maintenance?
Is not that the way whereby the power of God may be known that raiseth the seed of God,
whereby the hearts of people may be opened, and whereby the seed is known?
And the apostle declared against such as taught for filthy lucre,
and made merchandise of the word;
and that which thou callest '`humanity,`' is your earthly right,
seeing your conversation is in earth, and not in heaven.

[.discourse-part]
P+++.+++ '`It cannot be concluded that there is a light in every man leading unto Christ,
and unto salvation.
And if Christ put a light in every man that cometh into the world,
to guide him unto the Father, and unto life, I deny that to be true;
for that is a natural light which is only the light
which Christ the word communicates to all men.
Nay, the light that all men have, though it seem to make them to know God, as God,
yet it is not sufficient to make them to know that there is a Father, or a son,
or the holy ghost, or that there is a gospel.`' And saith,
'`I am the light of the world that doth enlighten every man that cometh into the world;
that is, both Jews and Gentiles.
And he that walks in the light shall have the light of life.
Now here lies the deceit.`'

[.discourse-part]
A+++.+++ The light which every man that cometh into the world is enlightened with,
the covenant of God to Jews and Gentiles,
doth enlighten every man that cometh into the world; and they that walk in the light,
walk in Christ, and come to see before any natural light was.
And he that walks in the light shall not abide in the darkness,
but shall have the light of life; and with the light he shall know God,
he shall know the son, he shall know the gospel, he shall know the holy ghost,
and that light is not natural.
And he that knoweth God, knoweth the Father;
and none know him but with the light of Christ Jesus who reveals him;
for God is the Father.
And '`I will give him for a covenant, a light to the Gentiles,
a new covenant to the house of Israel and Judah,`' who doth
enlighten every man that cometh into the world,
a leader of the people, a leader of them from death to life, to God, out of the fall,
out of the first man Adam, a bringer in of righteousness, peace, and joy, and truth,
and grace, to all that believe and receive him;
but they that hate the light it is their condemnation.
The light, Christ, the covenant of God, is the leader of the people out of the fall,
out of all deceit unto God, and it is sufficient.
It is the end of the prophets`' and the apostles`' teaching, the fountain of life,
in which every one sees life.

[.discourse-part]
P+++.+++ '`Hath every man a light sufficient to bring him to God,
when none come to God but by Christ?
If there be a light sufficient within for the enjoyment of life,
for direction to the Father the fountain of life.
The holy ghost saith,
"`Ye shall teach no more every man his neighbour,`"
"`ye need not that any man teach you.`"
He doth not speak absolutely and strictly.`'

[.discourse-part]
A+++.+++ To Jews and Gentiles who witness the new covenant of God promised,
the law in their hearts, it is absolute; they need not say to one another,
'`Know the Lord,`' in the covenant of life and peace with God,
in him by whom the world was made before it was made.
But they that have these words in a form,
are they that set to themselves heaps of teachers.
And the apostles in their teachings to all nations were ambassadors of this covenant,
declaring the substance, to the bringing people off from all teachers,
that they needed not be taught by any man to know the Lord.
And the light, Christ,
'`which doth enlighten every man that comes into
the world,`' is sufficient to guide to eternal life,
and he that believeth in it shall not abide in darkness,
but shall have the light of life, and shall come out of condemnation;
and he that hates it abides in darkness, and knows not whither he goes.
And it is sufficient to let every man see his salvation.
For '`I will give him, for a covenant of light,`' said God,
'`he shall be my salvation to the ends of the earth,`' the covenant of light,
'`that doth enlighten every man that cometh into the world.`'

[.discourse-part]
P+++.+++ '`What Christ, and the apostles say, "`Swear not at all, neither by heaven, nor earth,
nor any other oath,`" they did not mean as they spoke, but that men should swear;
and they did not speak against all swearing.
And the Quakers may blush,
for it is as if God should not speak as he meant by Moses in the law.`'

[.discourse-part]
A+++.+++ Christ and the apostles meant as they spoke; to what state and condition they spoke,
the words were truth to that state, if it was by parables, or patterns, or figures.
Now Christ being the end of oaths and types, saith,
'`Swear not at all,`' who is the covenant of God, the end of the prophets, of Abraham,
of David, of Solomon, of Jacob, of Joseph, of oaths and swearing.
And angels must bow to him, who saith,
'`swear not at all.`' And the apostles preached this covenant, this oath of God,
Christ Jesus; and the apostle that was in the doctrine of Christ, bid them,
'`Above all things, my brethren,
swear not at all,`' but in all your communication let your '`yea be yea, and your nay,
nay, for whatsoever is more cometh of evil.`' And they spoke as they meant;
for they came into condemnation that broke the doctrine of Christ.
Now apostates, and hypocrites, and false brethren may swear, that are out of the light,
the covenant of God, that have the form of godliness, and deny the power;
and such are antichrists, against his doctrine,
and wrest the scriptures to their own destruction, and say, that Christ, and God,
and the apostles, did not mean as they spoke.
But God did mean as he spoke, when he spake to Abraham.
And Christ meant as he spoke,
when he said '`swear not at all.`' And the apostle meant as he spoke, '`my brethren,
above all things, swear not at all.`'

[.discourse-part]
P+++.+++ '`We are ministers under the new covenant, and have the allowance of the gospel,
and the tithes only being designed unto us, we may with a good conscience take them.
And the tithes are not in themselves ceremonial.
Abraham paid tithes to Melchisedeck.
If there be not a maintenance settled out to the ministry,
we know we cannot subsist to do service to their souls without a worldly support,
a sufficient maintenance.
They call us greedy dogs,
because nursing fathers and mothers have provided
for our nourishment a maintenance for us.
To work or to beg are two straits, whereof the world might be ashamed,
but especially the saints.`'

[.discourse-part]
A+++.+++ The world would not he ashamed, nor the saints, to see you work,
who have taken the people`'s bread for whom you do no work;
and the saints do witness against you.
The prophets, Christ, and the apostles, declare such to be greedy dogs,
that can never have enough.
And Christ came to put an end to tithes before the law, to tithes in the law,
to a priesthood made by the law, which had a command to take tithes,
whose is a priesthood forever after the order of Melchisedeck,
who was the similitude and likeness,
(and not after the order of Aaron,) who continues a priest forever.
And so when the first priesthood was ended, tithes and all ended,
and the command that gave them, and the priesthood.
Christ reigns over the house of Jacob, who was before Abraham was,
and Melchisedeck that Abraham paid tithes to, the similitude and likeness,
which Christ is the end of.
Here is the rock, and the substance.
'`This is my beloved son, hear him,`' (saith God,) who was in the bosom of the Father.
So they that know him, come to preach the gospel, and live of the gospel;
who breaks down the earthly part, and opens the hearts of people;
who breaks down the earthly part, and reaches to the seed.
And as for your nursing fathers and mothers, such as give you maintenance,
else you could not continue your ministry without a worldly support,
that is it which hath held you up long, and who are fain to fly to the old worship,
among whom the tenths were paid,
and so are roving up and down in sheep`'s clothing for your own ends to get maintenance;
and if that falls, your ministry falls.
And your nursing father and mother was the pope,
the pope was the author that set forth your tenths at the first,
since the apostacy from the apostles, and since the apostles`' doctrine hath been lost.
Therefore that life the apostles were in, are people now come to,
by which ye are seen and comprehended.
And a worldly support is not that which holds up the ministry, but Christ,
'`who is with them to the end of the world;`' and they that preach his gospel,
live of it, and they are far above shaming the saints or the world either,
for maintenance.
But ye have both shamed yourselves, and the saints are ashamed of you,
and many of the world and your own hearers are ashamed of you,
and will not justify your practices.
And so ye have showed your consciences who take the tenths,
that you are not exercised with the light, neither are in the mystery of the faith,
which gives to see the end of all changeable things.
And are not you begging with your petitions for more maintenance?
With your petitions flying up and down for glebelands and augmentations,
to the powers of the earth?
And sending for writs, summoning up to the courts people that you do no work for?
And this hath been the end of your fruits.

[.discourse-part]
P+++.+++ '`He that scorns to make use of the labours of
men for his improvement in the things of God,
shows himself proud.
If there be occasion to make use of human authors, which we offer to our hearers.`'

[.discourse-part]
A+++.+++ Human authors are from the earth, from the fallible nature;
to mix and mingle that with that which is received from God,
shows that he hath not discerning,
and makes that not sufficient which he hath received from God;
and this is contrary to the apostles.
What the saints of the Lord had delivered,
they did not mix it with men`'s enticing words of wisdom,
neither did they speak it in the words which man`'s wisdom taught,
but which the holy ghost did teach them.
Therefore, this is to teach from men`'s labours or human authors; for men`'s labours,
and the human authors`' inventions come out of that nature which prisons the seed of God.
And so that is not agreeable to that which is received from God;
but every one`'s words there shall be his burden:
and so human authors are not to be mixed with the word of God, for the word is pure,
and nothing is to be added to, or taken from it; he that doth shall be proved a liar;
and the higher power is not human nor infallible.

[.discourse-part]
P+++.+++ '`Paul and Peter were instructed by an immediate revelation,
which we are not so presumptuous as to expect,
or to make the apostles`' condition our condition.
Human learning will not acquaint us with the mind of God, yet being sanctified,
it is a great assistance to that end.`'

[.discourse-part]
A+++.+++ Are not ye in the presumption, and do ye not usurp authority, to preach or to teach,
that have not immediate revelation as the apostles had,
but have got their words and are out of their power?
Are not all who are not in the power of the words of the apostles,
such as are to be turned away from, by the command of the apostle?
And are not all who are in the power of God, and the life that the prophets, Christ,
and the apostles were in, in the immediate revelation of God?
Can any know the scriptures, or the truth given forth from the spirit of truth,
learned of God the Father of truth, but by the immediate revelation of the spirit of God,
which reveals the things of God?
And thou speakest of study and prayer; can any divide the word aright, or pray aright,
but in the spirit?
And where that is, is not there immediate revelation from God?
And this thou calls presumption, to be in the revelation that the apostles were in;
but it is presumption to meddle with their words,
and not to be in the condition they were in; that is presumption, and to usurp authority.
And so ye are those that are got up since the days of the apostles,
ravening inwardly from the spirit of God that they were in, and have sheep`'s clothing,
who Christ said should come, and John saw were come, and went forth from them.
And since the days of the apostles, the world have gone after you,
all but those who have their names written in the
book of life before the foundation of the world,
and keep Jesus`' testimony.
And human learning doth not help in the way and things of God, as it is in itself,
but as the spirit doth open through all things, and beyond all things,
and comprehends all languages, and sees before languages were;
that is it that ministers to the spirits in prison,
and that is not called human learning, which sees over languages and beyond languages,
and comes to have power over tongues, languages, and speeches, and sees before they were.

[.discourse-part]
P+++.+++ '`Custom hath made it the civility of our language, to say _you_ to one,
and not to say _thou_ to a superior, except it be a familiar.
It is no great fault to respect men`'s persons.
And the scripture only, makes men wise to salvation.
And it is a pernicious error in placing justification
and salvation in righteousness within.`'

[.discourse-part]
A+++.+++ '`That the righteousness of Christ might be fulfilled
in us;`' and where Christ is within,
there is sanctification, and there is justification, and there is salvation known;
for there is no salvation known nor felt without, but first it is found within.
Faith evidenceth it, the spirit witnessing, the spirit comes to witness it,
the light sees it, and this is within.
And so they that have these words, of righteousness, of sanctification,
of justification without, and not within, are in the error; and none know them without,
but first they know them within.
And '`__you__ to a superior, and _thou_ to a familiar;`'
is not God the superior, the supreme? and dost thou say you to God?
dost thou esteem man higher, in a place beyond God?
Is not this ambition, and pride, and presumption, and foolishness!
Must thou not come to be judged here, and be humbled for thy miscarriages?
And '`__thou__ to a familiar,`' a person of low degree;
canst thou speak more familiarly to God than to man?
Thou to him, and you to man is this righteous and sound speech that cannot be condemned?
Dost thou not in this show that thou never learned either the accidence or bible?
'`He that respects persons, commits sin;`'
thou dost respect the poor and the rich in thy words,
and art by the law reproved to be a transgressor,
and art out of the faith that is held '`without respect of persons.`'
And as for the rest of all thy lies and hard expressions in thy book,
they shall come upon thyself, and to thee be a heavy burden.
And the day hastens upon thee apace; to the witness of God in thy conscience I speak,
which will let thee see that it had been better for thee,
if thou had never opened thy mouth, than to have exposed thy nakedness to the nation.
And this is not the way to convert souls, to rail; for railing never converted any,
but brought them into a form out of the power,
and so increased knowledge which was their sorrow.
