[#ch-58.style-blurb, short="R. Sherlock"]
== R. Sherlock`'s principles, as followeth.

[.discourse-part]
_Principle._ He saith,
'`They do not attain the knowledge and understanding of the gospel
by the same means as the apostles did.`' Saith he,
'`We preach the same gospel as the apostles preached,
but do not attain to the knowledge and understanding of this gospel by the same means.`'

[.discourse-part]
_Answer._ That which the apostles received, they received from God;
so ye receiving it not by the same means, have received it from men, and not from God.

[.discourse-part]
_Principle._ He saith, '`The apostles were eye-witnesses,
and understood by immediate revelation from God,
inspired with the gift of the spirit more than any
man could hope for since.`' And he saith,
'`they do not pretend any such gift,
nor depend upon any such immediate miraculous revelation from heaven.`'

[.discourse-part]
_Answer._ Then all may see now in this that what ye have received, it hath been from man,
not from heaven immediately, not the gifts of the spirit,
nor have received the gospel by the same means the apostles did,
who are not the eye-witnesses, as the apostles were.
Neither have ye attained to the same knowledge and understanding that the apostles did,
nor received it from heaven.
Now let all people question, whether it is the same gospel,
which is not received from heaven, nor immediately, nor by revelation;
for the gospel is immediate, which is the power of God.
Rom. i. They that understand the gospel, are in the same power, understanding, knowledge,
and immediate revelation from heaven, that the apostles were in,
and they that are in another, cannot understand that gospel.
He confesseth to the nation, in his answer to some queries,
and in his discourse upon the holy spirit, that they have not the same knowledge, gift,
nor immediate revelation, as the apostles had; so he hath made himself manifest,
(and the rest of the priests,) that he is in the apostacy,
and has not the gospel the apostles had.

[.discourse-part]
_Principle._ He saith, page 11,
'`An external means enables them to open the meaning of the gospel.`'

[.discourse-part]
_Answer._ An external opens not the eternal; this all may judge that are in the fear of God,
and that is it which keeps them from being deceived and seduced.
He saith, '`the external opens the eternal,`' which is false;
for the eternal opens the external, and the gospel is eternal,
and that which reacheth to the soul, which is immortal;
and all they are seduced and seducers,
that think and say the external must open the eternal.

[.discourse-part]
_Principle._ He saith, '`Learned men are those who must give the sense of the scripture.`'

[.discourse-part]
_Answer._ Pilate was a learned man, and had Hebrew, Greek, and Latin,
and knew not the sense of the scripture, who crucified Christ.
And the learning of God is that which knows the scriptures
by the spirit that gave them forth,
and not the confounded natural languages.
And the query to him was, whether any were to be called master?`' His answer is,
'`Master is a title of civil honour.`' A Pharisee, a transgressor of Christ`'s commands,
Matt.
xxiii.
that tramples upon Christ`'s command and his doctrine,
and makes the doctrine of Christ uncivil.
And this is your lordship and usurped authority, who would lord it over God`'s heritage;
but he is throwing you out as dung upon the face of the earth.

[.discourse-part]
_Principle._ He saith, '`The Pharisees paid tithes when they neglected the law of God.`'

[.discourse-part]
_Answer._ Do not all you so?
Is not this your condition that take tithes, whose fruits in the nation make it manifest?
And the apostle said the priesthood was changed that took tithes,
and the apostles denied the Pharisees that took them;
but you take them by compulsion and carry to prison till death, if you cannot get them;
and in this you are worse than the Pharisees and first priesthood that took tithes,
who denied Christ was come in the flesh.

[.discourse-part]
_Principle._ He saith, '`that children are of the kingdom of God,
and yet they must be born again before they can enter into the
kingdom of God,`' page 17. and `'sprinkling of infants is baptism.`'

[.discourse-part]
_Answer._ Which there is no scripture for.
He saith,
'`Christ commanded both his disciples and them to take and
eat this,`' and yet they never heard his voice!

[.discourse-part]
_Principle._ He saith, '`To give an answer without imagination or consequence,
is without reason or judgment.`'

[.discourse-part]
_Answer._ There is a reason and a judgment out of imaginations and consequences to be given,
which is in truth, and out of the doubtful dispute.

[.discourse-part]
_Principle._ He saith, '`While men be upon the earth the body of sin is not wholly subdued.`'

[.discourse-part]
_Answer._ Contrary to the apostle`'s doctrine, who saith,
they were '`made free from sin.`' And this is to deny the
circumcision which puts off the body of sin;
this is to keep out of Christ the second Adam, in the first Adam, in the fall.

[.discourse-part]
_Principle._ He saith,
'`The contents of the gospel are things of the spirit of God attained by external means;
and the apostles were called of God immediately,
which (he saith) no man must hope for since.`'

[.discourse-part]
_Answer._ Then you have all followed your own spirits,
and are found amongst the number of the false prophets,
and those that ran and the Lord never spake to them;
and the things of the gospel and of the spirit, are not attained by external means.

[.discourse-part]
_Principle._ He saith,
'`We must not look for an immediate extraordinary miraculous teaching from the Lord.`'

[.discourse-part]
_Answer._ Yet he saith, '`all men are taught of God;`' what confusion is here!
The grace of God which brings salvation hath appeared unto all men, and teacheth us,
and this he calls an outward teaching by the Lord Jesus Christ.
Is that which brings salvation outward?
All in truth may judge this and try thy spirit.
And the teachings of the Lord are not mediate but extraordinary, above all yours,
who are men got up since the days of the apostles.

[.discourse-part]
_Principle._ He saith, '`They shall teach no more every man his neighbour, saying, know the Lord,
but they shall all know me from the least to the greatest;`' and he saith again,
'`The most knowing man hath not attained such a perfection of knowledge in his gift,
as not to need teaching.`'

[.discourse-part]
_Answer._ So he is one that believes not in the promise.
They that love, are of God, and they that love know God, and they that love not God,
know not God.
Here are the spirits of the world made manifest, and the spirit of God in his saints,
from thy confusion; so they that know God are taught of him.

[.discourse-part]
_Principle._ He saith, '`The anointing within people, is a measure of spiritual wisdom.`'

[.discourse-part]
_Answer._ And yet they attain to the gospel by external means!
It is only those that give heed to such spirits as these,
that go from the anointing within them, and do not take heed to the anointing;
so go from the eternal means to the external means,
and from the immediate to the mediate.
But by the immediate they are now tried and seen to be such as the apostle saw come in,
who have since been over the world.
But they are now made manifest.

[.discourse-part]
_Principle._ He saith, '`Sprinkling of infants is God`'s ordinance.`'

[.discourse-part]
_Answer._ For which they have no scripture, but a tradition,
which hath been taught men for a doctrine,
by those who cannot show where God commanded it.

[.discourse-part]
_Principle._ He saith, page 31, '`For the spirit within,
we are not so blindfolded to follow the dictates
thereof.`' And '`we draw men from the spirit within.
It is human learning that distinguishes the naked truth,
whereby it is clearly seen.`' And calls them '`blind that say otherwise:
and cannot distinguish persons from houses.`' He
confesseth '`it is contentious to go to law.`'

[.discourse-part]
_Answer._ Here he hath given judgment upon all the priests, the rest of his fellows,
who in most parts of the nation are troubling people for tithes, and their maintenance.
And you are blindfolded who lead people from the spirit within, who are ravened from it,
and have the sheep`'s clothing.
Human learning is from the earth, from the ground,
and that cannot distinguish the naked truth,
and with that the Pharisees could not see Christ,
as you cannot see the light which hath enlightened every man that cometh into the world,
nor the sons of God who are led by the spirit.

[.discourse-part]
_Principle._ He saith, '`The scripture was given forth in the Hebrew, Greek, and Latin,
which we truly say is the original.
And to attain spiritual wisdom by depending upon miraculous revelation from heaven,
is tempting the good spirit of God.`'

[.discourse-part]
_Answer._ And here he is contrary to the apostle.
What he had received from the Lord he declared, and David, and all the prophets of God,
waited upon the Lord for counsel, and teaching, and revelation;
and this he calls a temptation, whereas no one knows the son but by revelation,
nor the Father, nor the scripture; not a Hebrew, nor a Greek, nor a Latinist;
but they that think to find it out by natural languages are in the temptation,
from the spirit of God which reveals the deep things of God,
which to all you inward raveners, is miraculous.
And as for the rest of thy confusion and lies, they are not worth the mentioning,
but shall cover thyself.
In the day of thy judgment, the witness shall answer and manifest thy clothing.
