[#ch-59.style-blurb, short="John Wallace, William Moore, priest Kellet, priest Walker"]
== John Wallace, priest of Kendal; William Moore, priest of Kellet; and priest Walker. Their principles as followeth.

[.discourse-part]
P+++.+++ They say, '`that the devil is transforming himself into an angel of light,
and this is to oppose the light of Christ.`'

[.discourse-part]
A+++.+++ The light which every man that cometh into the world is enlightened with,
is that which Satan is out of, and in you that are out of the light,
which Christ doth enlighten every man that cometh into the world with,
may Satan transform himself, who transformed before the apostles`' decease,
and since their decease it hath been he that hath made this work among all creatures,
under whose power you are, in the night of the apostacy.
And he hath been the cause of destroying people,
who is out of the light in which is the unity.
To sing without the spirit, to sing words made ready to hand, the Jews could do that,
whose songs were to be turned into howling; but to sing in the spirit,
there is the melody made to the Lord, where hymns, psalms, and spiritual songs are known.
But to say that Christ and the apostles sung David`'s
psalms turned into metre as you do now,
a thing made ready to their hands,
this would make as though the apostles and Christ could not sing without David`'s psalms,
and would put every one beside the spirit; for Christ was Lord of David,
and the apostles preached the end of David, and in that they sung.
And every man that cometh into the world hath a light from Christ,
and that which may be known of God is manifested within man,
though Jews and Gentiles be from it, guiding all minds,
it will bring them to sing in the spirit, as David, Solomon, Christ, the apostles,
and the saints; and in this let all make melody to the Lord in their hearts,
all having motion and breath from the Lord.
So let all praise the Lord in the spirit, and in it unto him sing, who in him move,
and live, and have their being.
