[#ch-61.style-blurb, short="Ambrose Dickinson"]
== Ambrose Dickinson`'s principles, as followeth.

[.discourse-part]
P+++.+++ He saith, '`That there is nothing within man,
but what puts him on a covenant of works.`'

[.discourse-part]
A+++.+++ There is faith within man that works by love, and there is Christ within man,
and God will dwell in man, and walk in man, and the son of God is revealed within.
Dost thou liken all these to things without in the covenant of works,
which ends them all, and was before they were?

[.discourse-part]
P+++.+++ He saith, '`There is no knowledge of Christ in this generation but by the scripture.`'

[.discourse-part]
A+++.+++ Many may have the scriptures, and not know Christ;
they will not give the knowledge of Christ.
That which comes from him, and shines in the heart,
doth give the knowledge of Christ the light.
And the Jews had the scriptures, but had not the knowledge of Christ,
as you do not know the '`light that doth enlighten every man that cometh
into the world,`' the ear being stopped to that of God in you,
and your eyes closed.
And it is not the spirit, and the letter of it cannot give life.

[.discourse-part]
P+++.+++ John Stockdale said, '`The scriptures must try the spirits.`'

[.discourse-part]
A+++.+++ The spirit was before the scriptures were; and the Jews had the scriptures,
yet knew not Christ, but crucified him;
and that must try the spirits that gave forth scriptures.

[.discourse-part]
P+++.+++ He saith, '`The spirit and the scriptures, are one and the same thing.`'

[.discourse-part]
A+++.+++ Scriptures are writings, as the priests and professors say,
and Christ was before they were given forth, which owns it,
and is when it ends and is fulfilled.

[.discourse-part]
P+++.+++ Priest Heywood in Lancashire said,
'`it was blasphemy to say that the church was in God.`'

[.discourse-part]
A+++.+++ Contrary to the apostle, 1 Thess. 1:1. who said, '`the church was in God.`'

[.discourse-part]
P+++.+++ Again he said, '`It was blasphemy to say, that God dwelt or walked in his saints.`'

[.discourse-part]
A+++.+++ Contrary to the apostle, 2 Cor. 6:16. Eph. 4:6. who saith,
'`God will dwell in you, and walk in you;`' and '`ye are the temples of God.`'
