[#ch-62.style-blurb, short="Quakery Slain"]
== Christopher Wade`'s book, called '`Quakery Slain.`' His principles follow.

[.discourse-part]
_Principle._ He saith in page 3,
'`Oh horrible! to say the infallible spirit must open the scriptures.`'

[.discourse-part]
_Answer._ He hath shut himself out from the spirit, that gave forth scriptures,
and must open them again, in which is the unity, and that is infallible.
And he that hath the spirit of God, hath that which is infallible,
and he that hath not the spirit is none of his; so out of the infallibility,
where thou art, in the horrible state.

[.discourse-part]
_Principle._ He saith, '`It is whimsical to say, Christ, God and man, flesh and spirit,
is in them.`'

[.discourse-part]
_Answer._ Contrary to the apostles`' doctrine, who said, they were of his flesh and of his bone;
and '`Christ in you,`' and he would walk in them.
And '`he that hath not the spirit of Christ is none
of his,`' and they are of his flesh and of his bone,
and '`Christ in you, the hope of glory.`'

[.discourse-part]
_Principle._ He saith, '`It is a devilish doctrine not to forsake quaking and trembling.`'

[.discourse-part]
_Answer._ So in this thou mayst say, it is a devilish doctrine to say,
salvation must be wrought out by trembling and quaking:
so thou showest thou never knew salvation; for before men have salvation wrought out,
they must know trembling and quaking.
And so thou hast shut thyself out from Moses`' and David`'s condition;
and such as the Lord regards, tremble at his word.

[.discourse-part]
_Principle._ He saith, '`Flesh and bone cannot be a measure in one, and a measure in another.`'

[.discourse-part]
_Answer._ Whereas the apostle saith,
'`We are of his flesh and of his bone.`' Here thou art contrary to the apostle,
and they were more than one that had the flesh of Christ, and his bone, and his spirit.

[.discourse-part]
_Principle._ He cries, '`Oh Luciferian pride to save souls!`'

[.discourse-part]
_Answer._ What good doth all your preaching do?
Here thou spoilest all the rest of the priests,
and showest thyself to be contrary to the apostles, who watched for the soul,
and saved souls; that turned people from a multitude of sins.

[.discourse-part]
_Principle._ He saith, '`God the Father never took upon him human nature.`'

[.discourse-part]
_Answer._ Contrary to the scripture, which saith,
'`God was in Christ reconciling the world unto himself;`'
and thou art ignorant of the great mystery,
'`God manifest in the flesh;`' and his name is called
'`the everlasting Father.`' As for the word human,
which is from the ground, it comes from thy own knowledge, which is earthly.
And Christ took upon him the seed of Abraham and David, according to the flesh;
and this is scripture language.

[.discourse-part]
_Principle._ He saith, '`The holy ghost is a person,
and that there was a trinity of three persons before Christ was born.`'

[.discourse-part]
_Answer._ Thou knowest not him that is in the Father, and the Father in him,
glorified with the Father before the world began.
And the scriptures do not tell people of a trinity, nor three persons;
but the common-prayer-mass-book speaks of three persons,
brought in by thy father the pope; and the Father, son, and holy spirit was always one.

[.discourse-part]
_Principle._ He compares immediate revelation from heaven,
'`to the false prophets`' dreams.`' And again he saith,
'`The scriptures is the word of God.`'

[.discourse-part]
_Answer._ Here he fights with the rest of his fellows, who say, scriptures signify writings,
and writings are not God; but the scriptures of truth are God`'s words, which Christ,
the word, fulfils.
They are not the word of God which thou hast blasphemously affirmed,
but Christ is the word of God; and they that deny revelations,
are out of the fear of God and the spirit, and know not the son nor the Father,
but are among the false prophets and false dreamers.

[.discourse-part]
_Principle._ He saith, '`The scriptures are the, word,
except you dare to deny Christ is God.`' And he brings a scripture.
'`Let the word of God dwell in you richly.`'

[.discourse-part]
_Answer._ So he makes the scripture Christ, and God, and he doth not say,
'`let Christ dwell in you,`' but means the scripture.
And God dwells in you; and the apostle said,
'`Let Christ dwell in your hearts by faith;`' and God will dwell in you; but thou sayst,
Christ doth not dwell in them personally.
Doth not Christ dwell in his saints, as he is in the person of the Father, the substance?
And are not they of his flesh, and of his bone?

[.discourse-part]
_Principle._ '`They that hear the word of God do not hear the son,
the holy scriptures are the mediate word of God.`'

[.discourse-part]
_Answer._ Now, all people, where ever did you read of a mediate word of God?
Doth not the word of God endure forever, and is it mediate?
And he calls God heavenly Father, and admits he never heard his voice, nor his son`'s,
and denies immediate teachings.
He that knows the spirit that gave forth scriptures, hears the son.

[.discourse-part]
_Principle._ He saith, '`God limits the supreme Holy One by the inspired writings of the apostles;
and that is his third dispensation of his mind to men.`' And he saith,
'`They are taught by inspired scriptures, which is mediate; not by letter,
which is literally, the letters or letter.`'

[.discourse-part]
_Answer._ Inspired scriptures, and yet mediate.
'`The testimony of Jesus is the spirit of prophecy;`' and the spirit inspires,
which the letter doth not.
And God`'s teaching is by his spirit,
and the Holy One is not limited by the words of the apostles, who fulfils them;
and many words the apostles spoke which were not written.

[.discourse-part]
_Principle._ And he calls '`the devil the tutor, to say, not made minister of the letter.`'

[.discourse-part]
_Answer._ So we speak the apostle`'s words, and he makes the devil the apostle`'s tutor,
who was not a minister of the letter, but of the spirit, who said, '`The letter killeth,
but the spirit gives life.`' And whoever says this,
that makes the devil the apostle`'s tutor, it is a lie, and his own;
and the devil is the tutor of the ministers of the letter, and not of the spirit;
who can run into it, who are out of the truth.

[.discourse-part]
_Principle._ '`He speaks of a moral law.`'

[.discourse-part]
_Answer._ Which he hath no scripture for, the scripture speaks no such thing;
but he darkens counsel by his words.

[.discourse-part]
_Principle._ He saith, '`The scripture contains the mediate inspired teachings,
written word of God, that was and is God.`'

[.discourse-part]
_Answer._ The scriptures say,
'`the heaven of heavens cannot contain him;`' and
God and Christ were before any written words were.
And the mediate teaching of the whole scripture letter he speaks of,
which he calls God and Christ, and all the mediate teaching is carnal;
and the scriptures do not continue the immediate teachings of God`'s inspiration,
but testifies of those things.

[.discourse-part]
_Principle._ He saith,
'`The written word is the sword of the spirit.`'
And he makes another rule '`besides the scriptures,
false.`'

[.discourse-part]
_Answer._ Which we say is the spirit that gave them forth,
whereby peace is known upon the Israel of God.
And the Pharisees had the scriptures, but had not the sword of the spirit.
The scriptures testify of the sword of the spirit.

[.discourse-part]
_Principle._ He saith, '`It is a lie to say the saints shall judge the world.`'

[.discourse-part]
_Answer._ So he would make Christ and the apostles liars,
and would take the judgment from the son, and make Christ at a distance from the saints;
so he is ignorant of the saints and Christ both,
and knows not the time of the saints`' judging when the Lord is come;
but stands in the counsels of his own heart, and in the hidden things of darkness.

[.discourse-part]
_Principle._ He saith, '`No saint can be a judge of the world.`'

[.discourse-part]
_Answer._ Contrary to Cor.
vi. where the apostle said,
'`Do ye not know the saints shall judge the world?`' And '`they
abide not in the truth that affirm it,`' as thou sayst;
so hast shown thy ignorance, and art one of them that are judged by the saints.

[.discourse-part]
_Principle._ He denies '`the son of God to be revealed in man only
by adoption,`' and cries against '`equality with the Father.`'

[.discourse-part]
_Answer._ And that is contrary to the apostle, who had the son of God revealed in him.
And the assembly of divines gave forth a catechism, which children, old and young,
were to learn, and said, '`the holy ghost and son were equal in substance, and power,
and glory with the Father.`' What! then all that have the son and the holy ghost,
have that which is equal in power and glory with the Father.
In this thou hast not only judged thyself,
but all the '`assembly of divines at Westminster,`' 1649.

[.discourse-part]
_Principle._ '`It is a false thing to say Christ`'s person is in man.`'

[.discourse-part]
_Answer._ Which is as much as to say, none are of his flesh, of his bone, nor eat it,
nor had his substance.

[.discourse-part]
_Principle._ '`For denying all meritorious works that cast men out
from enjoying any thing from God for their salvation.`'

[.discourse-part]
_Answer._ And here they are turned to the pope, who are in their own meritorious works,
out of the faith that works by love.

[.discourse-part]
_Principle._ '`And there is no other way to salvation but by meritorious works.`'

[.discourse-part]
_Answer._ And there is no man attains to salvation by his own meritorious works in his will,
but they that attain salvation come to the light
which Christ hath enlightened them withal.

[.discourse-part]
_Principle._ He calls that '`satanical,`' to say, '`as he is, so are we in this present world.`'

[.discourse-part]
_Answer._ Contrary to John, who saith, '`As he is,
so are we in this present world;`' so thou hast denied John`'s words.

[.discourse-part]
_Principle._ '`That God doth exclude all works wrought in man and by man, by what spirit soever.`'

[.discourse-part]
_Answer._ So here is thy spirit tried; here works are totally excluded without any distinction,
and so the works of God and Christ his son, are excluded by thee.
And the apostle bids them '`work out their salvation
with fear and trembling;`' which he opposeth,
and gives another sense to it.
And the works of God, Christ, and the spirit are not denied by us,
as thou dost by the devil which is in thee.

[.discourse-part]
_Principle._ To be '`justified by Christ alone,`' he calls it a '`justified self-Quaker.`'

[.discourse-part]
_Answer._ There is no man self-denied and justified in the light of God, but by Christ alone.
And they that are not justified by Christ alone, are in themselves.

[.discourse-part]
_Principle._ '`It is against the scriptures to say men must be without sin,
and that men must be perfect.`'

[.discourse-part]
_Answer._ That is contrary to the scriptures; for they mention that there were just men,
perfect men, and holy men upon earth;
they that gave forth scriptures were '`holy men;`' and Paul spoke '`wisdom amongst
them that were perfect;`' and Joseph was '`a just man.`' And '`the blood of Christ
cleanseth from all sin,`' and are perfected by the one offering forever,
(mark the word are,) and '`he that is born of God doth not commit sin.`'

[.discourse-part]
_Principle._ He makes people believe, '`that false prophets and antichrists are come but now.`'

[.discourse-part]
_Answer._ Which Christ said should come in Matt.
xxiv.
and John saw they were come.
1 Epis.
ii. And in the Revelation he saw the world go after them, one of whom he is;
but the Quakers own but one Christ, which is the seed,
which is now risen on top of them all, and witness the Lamb.
He that was dead, is alive, and lives forevermore.

[.discourse-part]
_Principle._ '`That the Quakers are of the devil.`'

[.discourse-part]
_Answer._ But it hath been the devil in him that hath testified against the Quakers,
and so makes his kingdom divided against itself; and it is Christ that is in the Quakers,
and hath appeared, that cannot be shaken, whom he calls Beelzebub,
like some of his old fathers, but his reward will be according to his works.

[.discourse-part]
_Principle._ He saith, '`No other people upon the earth go about to save souls but the Quakers.`'

[.discourse-part]
_Answer._ So he hath judged himself, and all the people upon the face of the earth,
to be deceivers of souls, and not savers of souls; but the Quakers are so,
(the preservers and savers of souls,) and yet he calls them equivocating,
deluding hypocrites.
But he hath proved himself, and all others to be so, except Quakers.

[.discourse-part]
_Principle._ He denies, and says, '`that the saints`' bodies are not Christ`'s body.`'

[.discourse-part]
_Answer._ And how are they Christ`'s? How dwells he in them?
And how then are they of his flesh and of his bone?
And how brutish are you become in knowledge!
Hath not he bought them with a price?
And are they not his?

[.discourse-part]
_Principle._ He saith, '`that neither God`'s essence, nor the heaven,
nor Christ`'s person was in Peter`'s holy body.`'

[.discourse-part]
_Answer._ But the apostle said, '`God will dwell in you,
and walk in you;`' and '`Christ in you.`' And again he saith,
'`Our conversation is in heaven.`' And here thou
art striving against the apostle`'s doctrine;
and the beast is blaspheming against the tabernacle of God,
and them that dwell in heaven.
And thus thou wranglest with the apostle, who said Christ was in them;
and is not his power that which thou callest his essence?

[.discourse-part]
_Principle._ He says, '`There is not whole Christ, God and man, in men.`'

[.discourse-part]
_Answer._ Then how must men grow up in the measure of the fulness of the stature of Christ?
And Christ and God will dwell in man, and walk in man; God that made all things,
and Christ by whom all things were made.

[.discourse-part]
_Principle._ He saith, '`It is a shame for the Quakers to say, As he is,
so are we in this present world.`'

[.discourse-part]
_Answer._ Which are the apostle`'s words, and the apostle was not ashamed to speak them,
but thou that livest in the power of darkness art ashamed to hear them.

[.discourse-part]
_Principle._ He saith, '`Christ hath not appeared unto the saints in his second coming to them,
much less in them.`'

[.discourse-part]
_Answer._ Contrary to the apostle`'s doctrine, Col.
ii. And Christ said, he would dwell in them.
And the apostle said, the son of God was come.
And Christ said, he would come again to the apostles, which he did,
according to his word; and God did dwell in them, and walk in them.
And John in his epistle said, the son of God was come.

[.discourse-part]
_Principle._ And he saith, '`The saints are not as Christ is.`'

[.discourse-part]
_Answer._ So he denies John`'s doctrine, who said, '`As he is, so are we in this present world.`'

[.discourse-part]
_Principle._ And he saith, the righteous man sins seven times a day;
and that David nor no man living was justified in the sight of God at any time,
so long as he was a living man upon earth;
and that the prophets were not made free from sin.

[.discourse-part]
_Answer._ There is no scripture that saith, a righteous man sins seven times a day;
and David said his sins were removed from him as far as the east is from the west,
and yet thou sayst, David was never at any time free from sin,
of having sin in him while he was upon the earth.
And God said, '`I have found David a man after my own heart,
fulfilling all my will.`' So here he was justified.
And the apostle said in Rom.
vi. that they were made free from sin, and were justified by faith in Christ Jesus.

[.discourse-part]
_Principle._ He saith, '`Paul was not made free from all sin.`'

[.discourse-part]
_Answer._ Paul said he had '`kept the faith,`' he had kept that which purifies,
and gives victory over sin; and yet he goes about to disprove Paul`'s words, and saith,
'`Paul had sin when he had finished his course.`'
So his great work is to prove the saints sinners,
but they witness against him.
And he charges Job, Paul, and David with sin, whom God justified, and said,
'`Job did not sin with his mouth`' And though Paul did cry out of the body of sin,
yet he found victory over the body of sin,
and knew the redemption which the creatures waited for,
the '`liberty of the sons of God;`' and said, they were '`made free from sin,`' in Rom.
vi. and they were '`justified from all things;
and by the one offering forever he had sanctified.

Because the Quakers own the light Christ,
and are come into the spirit that gave forth scriptures,
and have heard the voice of the son of God,
and deny all them that say they have not heard the voice of the son of God,
and Christ to lie in them; therefore he saith, they have forsaken the truth;
because they deny them that have the form, and are out of the life,
and despise and deny the power that shakes that which is to be shaken;
for no one knows salvation but by the light.

[.discourse-part]
_Principle._ He said,
'`God did not come in his spiritual essence with his son on the earth.`' And saith,
that '`God the Father was not in his spirit with his son upon the earth.`'

[.discourse-part]
_Answer._ The scripture saith,
'`The fulness of the godhead dwelt in him bodily;`' and the Father is in the son,
and the son is in the Father, '`I in thee, and thou in me;`' so he was not alone,
but the Father was with him.

[.discourse-part]
_Principle._ He saith, '`The Quakers are lying deluders,
in saying the kingdom of heaven is within them.`'

[.discourse-part]
_Answer._ That is contrary to Luke xvii.
which saith, '`The kingdom of heaven is within you.`'

[.discourse-part]
_Principle._ '`And he hath not heard of any other people in the world taught immediately by Christ,
but the Quakers.`'

[.discourse-part]
_Answer._ And the two witnesses, as he calls them, he brings against truth,
who opposed truth in London: so showing where he and all people are,
who are taught by a mediate use of the scriptures; all may judge where that is.
And the devil rules such that are from the immediate;
and all that are not taught immediately, are not taught by God, nor by his spirit.

[.discourse-part]
_Principle._ '`This sort of people are for immediate revelation,
and it is dangerous for any man to trust to immediate revelations,
and preach Christ within man.`' And '`the two witnesses
preached Christ without.`' And this he saith,
'`is a hellish snare to please every man`'s palate.`'

[.discourse-part]
_Answer._ And thus he may charge all the people of the Lord who were taught,
and are taught of the Lord.
And thus he fights against those that were taught immediately; and his teachings,
and man`'s teachings, are mediate,
and they are in the snare that are out of the immediate teaching;
and all that know God and the son,
are taught immediately by the spirit that is immediate.
And so it is not a very strange thing that he should
give forth so many ill-savoured railing expressions,
of which his book is stuffed full, against the people of God;
his work in it is to charge the elect with sin, but we say, the Lord rebuke him.

[.discourse-part]
_Principle._ And he saith, '`The saints are not any time without sin,
even when they were born of God.`'

[.discourse-part]
_Answer._ So not knowing the creature`'s coming into the liberty of the sons of God,
nor the birth born of God.

[.discourse-part]
_Principle._ And saith, '`sin is in the saints for their humiliation.`'

[.discourse-part]
_Answer._ Contrary to the scripture, which saith, Christ is their humiliation,
and bears their sins, and destroys it; which humility is not like man`'s,
being brought down by sin, for sin exalts.

[.discourse-part]
_Principle._ '`That the inward man, and the power of God in man,
never brings the outward man so subject as to be without sin.`'

[.discourse-part]
_Answer._ This we say, God wrought salvation by Christ alone, without man`'s works;
and who believe in him, are saved, and who do not, are condemned;
and the power of God and Christ subdues sin in man, and destroys it,
that man becomes the temple of God.

[.discourse-part]
_Principle._ His query is, '`Whether God could not have saved man without Christ`'s dying?`'

[.discourse-part]
_Answer._ God can do what he will, who was in Christ reconciling the world to himself;
and Christ did not save the world without God.
And thou hast shown in thy book stuffed with lies,
by the filthy air that has come out of thee, how thou hast been tormented,
and that the devil was in thee.
And thou sayst, thou art saved by Christ without thee,
and so hast recorded thyself to be a reprobate,
and ignorant of the mystery of Christ within thee;
for without that thou dost not know salvation.
And these before mentioned are thy principles,
which thou hast published in print to the nation, and all sober people may judge thee.
As for thy lies they are not worth mentioning, neither are they worth reading;
but upon thy own head will they fall, and a heavy burden thou must bear,
who goest about to sow discord among the brethren.
But the accuser of the brethren is cast out.
The witness shall answer me in the day of thy judgment.
Christopher Wade calls his book, [.book-title]#Quakers Slain Irrecoverably,#
but he hath slain himself irrecoverably,
and the same judgment wherewith he judgeth us, he hath brought upon himself;
and the Quakers are recovered out of his snare, and have taken him in his own,
and have chained him and bound him.
