[#ch-63.style-blurb, short="The Holy Scripture Clearing Itself"]
== Henry Hagger`'s Book, called [.book-title]#The Holy Scripture Clearing Itself.# His principles in it follow.

[.discourse-part]
_Principle._ '`David never boasted of perfection, nor Paul, nor John,
and such as say they are free from sin,
it is their whole work to carry away poor souls from truth.`'

[.discourse-part]
_Answer._ There is none comes into the truth, nor any soul comes out of the deceived estate,
but who comes out of sin, and is made free from it, as the apostle speaks to the Romans;
such as served God in a new life, were made free from sin.
And God said Job was a perfect man, and eschewed all evil,
(mark all,) and David said he had seen the end of all perfection,
and Paul spoke '`wisdom among them that were perfect,`' and said
the life that he lived was by the faith of the son of God.
Though the apostle had cried out of a body of sin,
yet he saith Christ was manifest in his flesh to condemn the sin in his flesh,
and through Christ he had victory,
and witnessed the circumcision that put off the body of sin;
and saw where there is no condemnation.

[.discourse-part]
_Principle._ '`The scripture was the sure word of prophecy,`' and
'`the scripture will bring men to the knowledge of God.`'

[.discourse-part]
_Answer._ The spirit was their rule that gave forth the scripture,
and the word of God gave them to discern and to savour who spoke the word of the Lord,
and who stole their word from their neighbour, when the Lord had never spoken to them;
where the spirit was in the prison; where the spirit was out of prison,
with whom they had unity; and who had the form of godliness, but denied the power;
and who were the false spirits that went out into the world, and the antichrists,
and the false prophets; and such as were turned from the faith,
and such as lived in the faith, and such as quenched the spirit and despised prophecy,
and such as despised the Holy One, and slaughtered the seed of God,
and such as cast the law of God behind their backs:
this was the spirit and the word of God which was their rule,
that led them to discern and savour, to try, and taste, and handle;
this was the touch-stone, and this was the rule,
and this brought them to the knowledge of God.
And they that had the scriptures had not the knowledge of God without this, nor prophecy;
as the Pharisees had scriptures, yet knew not Christ.

[.discourse-part]
_Principle._ '`To the law and to the testimony.`'

[.discourse-part]
_Answer._ Yea, as we say, to the law and to the testimony, the law is the light,
'`the testimony of Jesus is the spirit of prophecy.`' But it is cried in this our day,
'`the letter is the light,`' amongst the ministers of the letter, against the light;
and they say '`prophecy is ceased,`' and so put the Old and New Testament for it,
and bring Isa.
viii.
for the law and testimony, which was before Matthew, Mark, Luke, and John.
But this is that their ignorance may appear.

[.discourse-part]
_Principle._ And likewise he saith, '`There is not a just man upon the earth that sinneth not.`'

[.discourse-part]
_Answer._ Read the words above in the 16th verse, '`Be not just overmuch,
neither make thyself overwise.`' Now mark, this just, this wise man upon the earth,
of whom it is said, '`There is not a just man upon the earth,
that doeth good and sinneth not;`' that was the estate of the law,
which Christ is the end of, who is a greater than Solomon, who is the Just,
and righteousness itself, and makes men free from sin.

[.discourse-part]
_Principle._ '`I do not affirm that any man can have salvation,
by virtue of his obedience;`' and '`thus you put out the eye of poor souls,
and bid them hearken to a light within them.`'

[.discourse-part]
_Answer._ The eye of the soul is the light, which cometh from Christ the bishop of it,
and he that believeth is saved, and there is his obedience, and he that doth not,
is condemned already;
and he hath the promise of life and salvation that believes in the light.

[.discourse-part]
_Principle._ He saith, '`The commission of Christ holds to the end of the world,
who gave some prophets, some evangelists, and some pastors,
for the perfecting of the saints, and the edifying of the body of Christ,
till all come to the faith and knowledge of the son of God,
and to a perfect man in measure, and stature, and fulness of Christ.`'

[.discourse-part]
_Answer._ Have you not all denied this work of pastors, teachers, and prophets,
the perfecting of the saints, and bringing to a perfect man,
saying that none must be perfect while they are upon earth?
and denied bringing to the unity of the faith,
which both you and your teachers are all on heaps about?
and have you not said that none must witness the measure, and stature,
and fulness of Christ, and the knowledge of the son of God,
that none must have him revealed?
have you not denied revelation?
How have you been in this work tossing people to and fro like chaff,
and carrying them about with every wind of doctrine!
And that is your wind that is not perfect,
that is not in the spirit that gave forth scriptures,
and there lodgeth all men`'s subtlety, cunning, and craft within,
lying and waiting to deceive.
This doctrine was coming up before the apostles`' decease,
which since hath reigned in the world,
as all the heaps of profession in all christendom discover it,
how people are tossed to and fro, and changed about,
and every one stands against perfection and overcoming sin while they be upon earth;
so excluding themselves from the work that the ministers of Christ were in,
apostatized from it, you have denied the ministers`' work, which is the perfecting,
and cry, '`no perfection.`'

[.discourse-part]
_Principle._ He saith, '`They call breaking of bread carnal.
Faith comes by hearing of the scriptures, and it is the way to teach men Christ,
and to convince and convert souls; how should we know sin to be sin,
or righteousness to be righteousness, but by scripture?
Scripture hath been a fit rule to walk by, and guide into truth and peace.`'

[.discourse-part]
_Answer._ Breaking of outward bread is not spiritual; the Papists say it is spiritual,
and you say it is not carnal; what differs priests and Baptists from Papists?
And you say it is not as other bread is; and thus you deceive people,
and make them believe a lie.
And the Pharisees had scriptures, but knew not the way of truth and peace,
nor were guided in it; neither are any upon the earth,
except they be in the life that gave it forth.
And the Pharisees had scriptures read every day among them,
and hearing not the word that was in them, which they heard that gave forth scriptures,
they heard not the word of faith, and the faith they had not,
for faith comes by hearing the word, the word preached, not by hearing the letter:
he that hath the word of God may speak it daily.
For they were ministers of the letter who begot people into a form,
in which they were tenfold more the children of the
devil than they were before there was any profession.
And none upon the earth can know righteousness to be righteousness,
but as they have the life that gave forth scriptures; for the Pharisees, chief priests,
and Jews had the scriptures and read them every sabbath day among them,
and they knew not righteousness to be righteousness,
nor Jesus Christ the righteousness of God; neither did they know sin to be sin,
for they crucified the Lord of life, that denied the light, the covenant of God,
the covenant of light.
So none know sin to be sin, but by the light which comes from the Lord Jesus Christ,
that makes it manifest; and Abraham and Enoch knew sin before scripture was.

[.discourse-part]
_Principle._ Again he saith, '`Try their own hearts by scriptures.`'

[.discourse-part]
_Answer._ They that tried their hearts, it was by the spirit of the Lord that searcheth them,
which led them to speak forth scriptures; for before the scriptures were given forth,
there was that in the heart to try it,
which led all holy men of God to speak forth scriptures.
If all men upon earth had the scriptures, and have not that which gave it forth,
they have not that which will try the heart; for the Pharisees had the scriptures,
and they could not try their own hearts, and so they turned against the light,
as the world do now, that have the scriptures.
For that is it which brings those to stand approved of God who try their hearts with it.

[.discourse-part]
_Principle._ He saith, '`The overseers of the church are visible.`'

[.discourse-part]
_Answer._ That which did oversee, and made to be overseers, was the holy ghost,
before the apostles deceased, which was invisible; but since the days of the apostles,
men have made officers by the letter, and such are visible,
therefore have all men come into divers forms, out of the unity,
and have lost the bond of peace.

[.discourse-part]
_Principle._ Likewise he saith, '`That which is contained in the bible, is spirit and life.`'

[.discourse-part]
_Answer._ This is as much as to say, that spirit is in the letter, and life is in the letter.
Now hadst thou said, that which is declared of is spirit and life,
and the letter itself death, these words had been true;
and that the life was in them that gave it forth, is sound.
Now the people have it among them as a general word, that the bible is a history,
or a treatise, or a catalogue, or the letter;
these are the common words among professors and preachers.
Now we say, the scriptures are the words of God, and a declaration of the prophets,
Christ, and the apostles, and Christ is the word in whom they end;
and that is agreeable and according to scripture which cannot be broken, and sound words.

[.discourse-part]
_Principle._ '`And the word was confirmed to them by signs.`'

[.discourse-part]
_Answer._ They that had the scriptures knew not the word;
by signs and wonders they were declared,
and signs and wonders were shown unto them that had the scriptures, from the word.
Now them that had the scriptures, to whom the word had shown miracles,
when they desired a sign of the word, he told them,
that no sign should be given to them but that of Jonas.

[.discourse-part]
_Principle._ '`And they say thee and thou to a particular is a proper speech,
but it is not a sin to say otherwise, and so not to give offence to Jew nor Gentile,
but you is the national speech; and the devil said thou, and Cain said thou,
and this was the bad men`'s language as well as the good.`'

[.discourse-part]
_Answer._ Though the devil and bad men got the form of true words,
yet the form of sound words is to be held fast; and though Paul said,
'`give no offence to Jew or Gentile,`' yet we do not find
that Paul spoke out of the form of sound words,
as you to one.
And because it is a national form of speech,
ye who are not come into the form of sound words, who have professed the scriptures,
Christ, and the apostles, show that you and they never learned either,
nor came into the practice of either.
You to one is not righteous, and all unrighteousness is sin: for one to say,
'`Thou Henry Hagar, art many men,`' wouldst not thou say they spoke unrighteously?
Now judge thyself.

[.discourse-part]
_Principle._ '`You call all men dead and carnal, and in the serpent`'s nature, in what form soever,
if they differ from you.`'

[.discourse-part]
_Answer._ All that are not in the light that enlighteneth every man that cometh into the world,
which is the way to the Father, differ from us.
Such are dead, such are carnal, in the serpent`'s nature: for none come to the life,
but who come to the light, in what form soever they be, and such as differ from us,
differ from Christ,
for none come from under the serpent`'s head and nature but they who come to the light.

[.discourse-part]
_Principle._ Likewise he saith,
'`But for a perfection in glory to be attained on this side the grave,
I utterly disallow.`'

[.discourse-part]
_Answer._ We do believe thee; but a perfection in glory is attained to,
while the saints are upon the earth,
for they were '`changed from glory to glory.`' There is a perfection in the least glory,
and that glory which the saints were changed from into glory, was not glorious,
but as it was in the perfection in the least degree or measure as it is in itself.
And so for the rest of thy lies and slanders, and unsavoury expressions,
which are not worth mentioning, they will clothe thyself and not cover thy shame,
but make it manifest.
They shall be thy own wounds in the day of thy indignation:
the witness within thee shall answer me, and thy silence had been better,
than to have uttered forth thy folly to the nation.
And whereas thou speakest of the church, that is a mystery to thee,
which is the pillar and ground of truth;
but men have gathered together a form in the apostacy, and the seed in the grave,
since the days of the apostles.
But now is the seed risen,
which treadeth such out and down that are gathered together in the words of scriptures,
but out of the spirit that they were in that gave it forth.
And that is the seed which all the promises are to;
he doth not say it is to the visible church, but to the seed,
and who are of the seed are of the church of Christ,
which is the pillar and ground of truth.
And so it is not the running up and down the scriptures, from place to place,
and bringing people chapter and verse, and telling people what the prophets said and did,
and what the apostles said and did, and so to be approved of in the sight of men,
but such are approved of in the sight of God,
that are in the life that they were in that gave forth scriptures,
and are in unity with the saints that gave them forth, with Christ the substance of them,
and with God.

[.discourse-part]
_Principle._ He saith, '`An unlearned question to ask, whether your baptizers cast out devils,
and drink any deadly thing and it not hurt you?
And whether the house where you meet was ever shaken?
And where he did give the holy ghost to you?`'

[.discourse-part]
_Answer._ This shows that you are not believers, nor in the power that the apostles were in.
And as for your saying the apostles said, that wicked men should grow worse and worse,
deceiving and being deceived: since the days of the apostles,
who saw those things come up,
those wicked men '`being deceived and deceiving,`' now since their days it is manifest,
that they have grown worse and worse, till they have grown all into heaps,
and killed one another about religion; the whole Christendom can witness it.
Such as have had the form of godliness but denied the power,
have been out of the power and life that gave forth the scriptures,
and out of the bond of peace, in the poison, one poisoning another,
and out of the holy ghost that gave forth scriptures, and out of the healing,
and the belief that casts out devils, and the devil, the murderer.
But he hath been your teacher to murder one another about your religion,
which did not Christ teach, but to love enemies, and to save men`'s lives.
