[#ch-64.style-blurb, short="Discourse"]
== Thomas Leadger`'s book, called [.book-title]#Discourse,# his principles in it follow.

[.discourse-part]
_Principle._ He saith, '`Such are in an error that set up a light within above the scripture,
or equal with the scripture, and know no Christ but a Christ within.

[.discourse-part]
_Answer._ The light, Christ, by which all things were made and created,
glorified with the Father before the world began, which the scripture testifies of,
is above the scripture, before the scripture was.
They that are not in this '`Christ within,`' are reprobates,
in which the scripture ends and which it testifies of; and so it is Christ,
the same today, yesterday, and forever, that the saints come to witness within them,
not another Christ, neither many Christs.
And they that profess a Christ without them, that have a Christ without them,
and another Christ within them, here are two;
for if it be not the same Christ that ended all types, and figures, and shadows;
if it be not him that is within, they have not the possession, the substance,
nor the comfort of the true Christ.
But they who have not Christ, the end of the types, shadows, and figures, in them,
are among antichrists and false christs;
and they that have the form of godliness can confess a Christ without them,
and not within them.

[.discourse-part]
_Principle._ Again he saith, '`The saints have a glorious light within them,
but imperfect.`' And '`it is an error to say they have an infallible light within them,
that they must follow,
which will show them all things.`' And '`to judge of scripture that it must be fulfilled
in them.`' And '`these are they that are brought up in dark places of the earth,
that are as Sauls that go to the witch and not to the law and testimony.`'

[.discourse-part]
_Answer._ None come to the law and to the testimony, though they have the Old and New Testament,
but those who come to the light in them, for the law is the light,
and those who come to the spirit within them, which is the spirit of prophecy;
and all that go from this, go into dark places of the earth,
and such are they that go in the path of Saul,
such spirits as go from the light within them,
and the spirit that is the testimony of Jesus, and the light.
And the glorious light of the saints which they are enlightened withal is Christ,
which is perfect, and they are changed from glory to glory;
and so the light which thou sayst the saints are in, and yet not perfect,
and yet glorious!
Mind thy words, consider thy measure, thy judgment.
The infallible light which every one that comes into the world is enlightened with,
is the leader of the people, and the light they are to follow,
and it is the way to the Father,
out of the way from the Father that is in the first Adam, in the transgression;
which light is Christ the second Adam,
that every man that comes into the world is enlightened with.
And they who follow this, and believe in it, and walk in it, abide not in darkness,
but have the light of life.
And the light within, and the spirit of God within, that gave forth the scripture,
is the trial of the scripture of truth; for men without that may wrest the words,
and wrong translate them.
So the light within, the spirit of God,
is the judge of the scriptures and knows scripture, which gave it forth, and is the rule,
and ruled and led them to speak them forth,
and is the rule that leads them to open them again, and to lead into all truth,
as saith Christ.

[.discourse-part]
_Principle._ He saith, '`That which they set up above the scriptures is heathenish;
and the scriptures are the ground of faith, without them faith cannot act;
and faith hath no bottom to rest upon but scripture; and scripture is more than faith,
the sure word of prophecy, the balm of the conscience; it satisfies doubts, heals wounds,
discerns the thoughts.`'

[.discourse-part]
_Answer._ The Pharisees and the chief priests, were not healed, except they came to Christ;
they found no rest for their souls; though they had the scripture,
yet they came not to Christ the light, which was before the scripture was given forth.
The Pharisees had the scriptures, but they had not faith;
they stood against the author and the ground of it, Christ.
The Pharisees had the scriptures,
but it was Christ and God that showed them their thoughts;
so the scripture knew not their thoughts,
but who are in the spirit that gave forth the scriptures, it shows men`'s thoughts.
Enoch and Abraham had faith, and had not scripture.
All are heathens that are not in the light which was before scripture was written,
though they have all the scripture.
And the holy men of God acted in the faith, in obedience to it,
before the scripture was given forth,
and they were all in the faith that gave forth the scripture,
and they did not act as from the scripture, but from the spirit of whom they had learned,
who is the author of faith which the just live by, and God and Christ,
the substance of the scripture.

[.discourse-part]
_Principle._ '`And the scripture is an infallible rule of worship.`'

[.discourse-part]
_Answer._ The Jews and Pharisees had the scriptures,
and the apostates since the days of the apostles have had the scriptures,
and have been out of the life that gave them forth; they want the rule,
which is the spirit, in which God the father of spirits is worshipped,
and that was the rule which all the holy men of God were led by to give forth scripture,
in which they worshipped God;
for the Pharisees had the scriptures and not the spirit which gave them forth,
that worshipped they did not know what.
They wanted the rule, the spirit of God that was in them that gave forth the scriptures,
in which they should have worshipped God; so saw not the substance, the ground of faith,
and author of faith, Christ Jesus.

[.discourse-part]
_Principle._ '`They will not put off their hats; they write thee and thou one to another;
they will not say master.`'

[.discourse-part]
_Answer._ The honour of the hat, the putting of it off,
is an earthly honour of the earthly Adam in the fall, in the transgression,
which Christ the second Adam, the Lord from heaven, not of the earthly,
comes to redeem man out of; he receives it not, he will have none of it,
but the honour that comes from above, and cometh to stain the honour that is from below,
and sees it a mark of earthly Adam in the transgression, and not of the second,
the heavenly.
And as for thee and thou, you to a number, and thou to a singular,
they who stumble at this, show they have neither learned accidence nor bible;
so are short of the spirit that spoke the sound words that cannot be condemned,
and speaks proper words, which is the plant of renown.
And as for being called of men master, Christ saith, '`Be not you called of men master,
for ye have one master, even Christ,
and you are all brethren;`' and they are in error
that slight his commands and trample them under feet;
and they are hypocrites, who, after they have trampled his commands under foot,
make a profession of his words.
Thomas Leadger, thou professest thou esteemest the scripture highly, above ordinances,
above angels, and is not this scripture which saith,
'`Be ye not called of men master,`' and is it not Christ`'s command?
Yet thou deniest these scriptures and tramplest them under thy feet.

[.discourse-part]
_Principle._ '`The scripture is the lantern of obedience,
and it directs men to Jesus.`' And he calls the scripture '`the word of God,
the sum of truth.`' And '`they could not have known there had been a Christ,
or a mediator, or grace, or glory, or worship, or Father, or spirit, or light,
but as it is declared in scripture.`'

[.discourse-part]
_Answer._ I do believe that you who are got up since the days of the apostles, in the apostacy,
inwardly ravening from the spirit of God, had not known there had been a Father,
or spirit, or grace, or worship, if the scripture had not declared it;
but they that had not scripture, had faith, had the holy ghost, had the Father,
knew the Father, knew Christ, knew the spirit; they that had the scripture,
the Pharisees, knew not the father, knew not the holy ghost, nor the redeemer,
but resisted (as it was in Steven) him that was born of the spirit.
Now they that had not the scriptures knew all these things,
that had the spirit that gave them forth, while they that had the scriptures,
and not the spirit, knew not these things, they that had the spirit of error,
that were in heaps about the saints`' words.
Now the Pharisees had the scriptures, yet walked in darkness,
had not David`'s lantern to their feet, and so could not see Christ as David did.
Saith the apostle, their table was their trap, there they stuck.
David that had the life that gave forth the scriptures, had the lantern to his feet;
and had not they a lantern before the scripture was written?
Abraham, Enoch, what led them all to give forth scripture?
Are not all they that have the scripture and are
out of that which they were in that gave them forth,
out of the light, and out of the lantern?
And they had a rule of obedience before the scripture was given forth, the word of God,
that lives, and abides, and endures forever; that is the word of faith,
in which the scripture, the words of God, ends.
And those that had the scripture and were from the life,
that they were in that gave it forth, knew not Christ.

[.discourse-part]
_Principle._ '`The gospel is the scripture.`'

[.discourse-part]
_Answer._ Many may have the scripture and deny the power of God which is the gospel,
and many had the scripture and the form, and stood against the son, the truth,
Christ Jesus, the power of God, the gospel.

[.small-break]
'''

And as for thy other lies and slanders which are not worth mentioning,
which come from thy drunken spirit, when the spirit is awakened that suffers by it,
thou shalt feel every word thy burden,
and thou that dost set the scriptures above Christ, and God, and the spirit,
art a heathen.
