[#ch-65.style-blurb, short="Antiquakers`' Assertions"]
== Thomas Leadger`'s [.book-title]#Antiquakers`' Assertions.# His principles in it follow.

[.discourse-part]
_Principle._ He saith, '`The divine nature is without mixture of sin,
but it doth not destroy wholly the sinful nature that is in us;`' and '`the being
of sin dieth not until the body die;`' and '`sin hath been in us to humble us.`'

[.discourse-part]
_Answer._ Sin is that which doth not humble, but lifts up.
That which humbles people, and brings down the sin,
is the humility which bears the sin and iniquity, which is Christ.
And the saints were made free from sin while they were upon the earth,
and had the body of sin put off.
And they who have received the divine nature, know it,
and have escaped the pollutions that are in the world, and the lust of it;
and so the divine nature destroys sin in its being.

[.discourse-part]
_Principle._ Again he saith, '`The scripture is a quickening spirit, the wisdom of God,
the power of God unto salvation, the words of the blessed scriptures every line of it.
I have had (saith he) the righteousness of God revealed in my soul;
I have had the love of God, the grace of Christ,
the communion of the holy ghost manifest in me, but I trample upon all attainments,
the highest, as dung.`'

[.discourse-part]
_Answer._ Many had the scriptures, and stood against the wisdom of God,
and stood against the power of God, yea,
killed and persecuted the Lord of life and glory;
they that had the dead letter without the life.
And many got the form, and denied the power, and denied the quickening spirt.
And the spirit of Christ doth not bring to trample upon attainments,
not upon the love of Christ, nor the righteousness of Christ.
The love of Christ, the grace of Christ, the righteousness of Christ,
were never esteemed as the dung, nor trampled upon as the dung.
Such as were transgressors were as dung, and they trampled upon the love of Christ,
the righteousness of Christ, but who come into this, trample upon their own notion.

[.discourse-part]
_Principle._ He saith again, '`That perfection is a golden dream,
and the scriptures are the word of God.`'

[.discourse-part]
_Answer._ Perfection is over all dreams be they never so golden, and it ends them all,
and is above them all.
And Christ`'s '`name is called the word of God,`'
and the scriptures are the words of God,
which Christ, the word of God, by which all things were made, came to fulfill.
