[#ch-66.style-blurb, short="A Serious Review of Some Principles of the Quakers"]
== A book called [.book-title]#A Serious Review of Some Principles of the Quakers.#

[.discourse-part]
P+++.+++ '`No man hath reason to say that the spiritual substance is in the creature,
the divine essence is subject to change as is the soul of man,
and every one is enlightened that comes into the world by the light of Christ,`' and
this he calls '`a natural light.`' And '`that some persons are come up out of the fall,
is an error.
I do not own a perfection without sin,
and it is an error to say there is any perfection without sin.`'

[.discourse-part]
A+++.+++ All erring is in the fall,
and that which is come up out of the fall is come out of the error, into the second Adam,
where no error is, which many witness, for all error is in the first Adam in the fall,
and in him that tempted.
And the light which doth enlighten every man that cometh into the world,
by which the world was made, which was before the world was made,
by which all things were made and created, in whom is life,
and this life is the light of men;
and men being in the light which they are enlightened with,
and coming by the light to him from whom the light doth come,
they come into the perfection, out of sin;
for all sin and imperfection are in the first Adam, in the earth.
And perfection is in the second Adam, Christ Jesus, who bruiseth the serpent`'s head,
the author of imperfection.
And they who are in him, are in a perfection without sin,
and there is no sin in perfection, nor any error in the perfection of Christ.
And all who are in the unreasonableness are ignorant of the spiritual substance,
and power of God, and holy ghost, the spirit of truth, the spirit of Christ,
the nature that dwells in the saints, all which are substance and not shadow,
and the divine power, and the power of the Lord God.
And God doth not change, nor his spirit, nor the soul, nor his power; so read thyself.
God doth not change in his being, neither doth that which comes from him,
that which he hath in his hand, and in his power.

[.discourse-part]
P+++.+++ He saith, '`That which is imperfect can be reconciled to God,
and that they are poor blind creatures that say the light
doth enlighten every man that cometh into the world,
and need no light and discovery to help,
and the scripture doth no where call Christ the word, but the scripture is the word,
and so these poor creatures err, not knowing the scripture.
To speak in the singular number is nonsense,
and they that translated the words thee and thou, might have translated them you.`'

[.discourse-part]
A+++.+++ The spirit gave to speak the proper language, singular and plural;
and spake such words as cannot be condemned.
And if translators that are out of that,
translate the words given forth from the spirit into what form soever they will,
yet the spirit will find it out;
and the light which '`doth enlighten every man that cometh
into the world,`' by which all things were made,
the made lights, and created lights, Christ Jesus the light,
which doth enlighten every one that cometh into the world,
need not have these outward lights or discoveries; they were all made by the light,
which light was before these were made.
And they who are come into the reconciliation with God, are in perfection,
out of the imperfection, from under the wrath.
And the word reconciles, hammers down, cuts down, and burns up that which is contrary,
and sanctifies, and makes clean.
And Christ Jesus, his name is called the word of God; the scripture saith so;
and they say that the scriptures are the word, but they are the words of God,
and Christ the word, which was before they were given forth, comes to fulfill them;
and that which is imperfect is done away.

[.discourse-part]
P+++.+++ '`To say that God is substantially in man, as essentially one with him,
can be no other but the man of sin, the devil himself,
having transformed himself into an angel of light,
and if it were possible would deceive the very elect.`'

[.discourse-part]
A+++.+++ The scripture saith, that God will dwell in man, and walk in him,
and the saints had unity with the Father and the son;
and all that hate the light which Christ the light hath enlightened them with,
have not the Father and the son.
In such the man of sin reigns, and in such the devil may transform;
but the elect he cannot deceive, the elect have the victory and dominion,
who were elected in him before the foundation of the world.
Glory forever!

[.small-break]
'''

And as for all the other words in thy book, they are not worth mentioning,
they will be thy own burden,
they will fall heavy upon thee in the day when thou shalt give an account to God.
