[#ch-67.style-blurb, short="Antichrist in Spirit"]
== James Brown`'s book, called, [.book-title]#Antichrist in Spirit.# His expressions and principles as followeth.

[.discourse-part]
_Principle._ '`That the light in every man is a certain guide and rule in all things;
this is the means whereby scriptures are slighted.`'

[.discourse-part]
_Answer._ No one knows nor owns the scriptures,
but as the light of Christ that doth enlighten every man that cometh into the world,
doth guide and teach him, the light of Christ within,
which gives them '`the knowledge of the glory of God in
the face of Christ Jesus,`' and of the scriptures,
and to see the scriptures, and doth not slight them.

[.discourse-part]
_Principle._ '`To witness God, and Christ`'s glorious resurrection, and heaven,
and the happiness of New Jerusalem,`' this is looked upon as an error.

[.discourse-part]
_Answer._ Christ is within, who is the resurrection, the glory, the kingdom of heaven is there;
and David who witnessed him was in hell, he was upon the earth too,
and he that witnessed the New Jerusalem, and that happiness, was upon the earth.
And they that have all these words, not possessing the life,
they have no comfort in what they speak, nor in what they profess;
and the babes and the children that are free, know their mother that is from above.

[.discourse-part]
_Principle._ '`If there be no outward means but light within, what need of the scriptures?`'

[.discourse-part]
_Answer._ The light, Christ within, was in the saints before the scriptures were, given forth,
and that was it which was their guide to give forth the scriptures, wherein they walked,
and did not stumble; and that is it which gives to see the scriptures again,
to what condition they are spoken, and the use of them.

[.discourse-part]
_Principle._ '`The day is not yet dawned, nor the day-star, the bright and morning-star.`'

[.discourse-part]
_Answer._ The apostle tells the saints of the day-star, and they were children of the day,
and the night was over, the true light shined, and the darkness was past.
Though some indeed were not come to the day-star, and the light shined in the darkness,
and the darkness comprehended it not.
Where darkness rules, there are the works that are out of the light;
and among such as have apostatized since the days of the apostles,
the day-star is not risen to them, they see it not;
but amongst the children of light it is seen, and they that see it not, are comprehended.
The day-star is risen, and they are children of the day.

[.discourse-part]
_Principle._ '`And them that bring people to look at the light within them, are as Korah, Dathan,
and Abiram.`'

[.discourse-part]
_Answer._ All that go from the light within them are as Korah, Dathan,
and Abiram amongst the Lord`'s prophets, exalting themselves, and persecuting.

[.discourse-part]
_Principle._ '`All men are not so taught of God as they shall be at Israel`'s return.`'

[.discourse-part]
_Answer._ All men are taught of God that are in the covenant, whether Israel hear or not.

[.discourse-part]
_Principle._ '`I know that many of the Quakers are temperate, sober, self-denying people,
but this is but the tithing of herbs.`'

[.discourse-part]
_Answer._ It was the doctrine of the apostle, who preached Christ the end of tithing and herbs;
and self-denial, soberness, and temperance were not called the tithing of herbs,
for the spirit that gave forth the scriptures brought to these.

[.discourse-part]
_Principle._ '`And the light within is darkness;
and I never read of the churches of the saints that spoke by two.`'

[.discourse-part]
_Answer._ The apostles`' doctrine to the Corinthians was, that they might speak by two or three;
and the light within, which is the light of Christ,
which doth '`enlighten every man that cometh into
the world,`' the darkness cannot comprehend it,
though it shine in it, till it shine forth in the heart,
'`to give the knowledge of the glory of God in the face of Jesus Christ.`'

[.discourse-part]
_Principle._ '`And that the kingdom that is in the saints, is in the Pharisees, I deny.`'

[.discourse-part]
_Answer._ The same that is in the saints is in the Pharisees, in measure,
though it be but as a grain of mustard seed, which is like to the leaven, little.

[.discourse-part]
_Principle._ '`The state of arising from sin to grace is never called a resurrection.`'

[.discourse-part]
_Answer._ They that arise from sin to grace, out of the first Adam into the second Adam,
come into the resurrection, and the second death shall have no power over them;
and the saints come to judge the world.

[.discourse-part]
_Principle._ '`Such as trust to a light within them, forsake the holy oil,
the Lord`'s spirit that speaks in the scriptures.`'

[.discourse-part]
_Answer._ The Lord`'s spirit spoke in them that gave forth the scriptures, who had the holy oil,
the light within them.
And the spirit speaks not from the scripture, but by that which gave it forth,
which is the author of it.

[.discourse-part]
_Principle._ '`I deny that any have a light within them to attain to the measure of God and Christ,
as they that have the writings.`'

[.discourse-part]
_Answer._ None attain to the mystery of God but by the light which comes from Christ the mystery,
though they may have the scriptures.

[.discourse-part]
_Principle._ '`They that will not put off the hat, but say thee and thou to people,
this is a sin of their own devising.`'

[.discourse-part]
_Answer._ Thee and thou is proper language, and a form of sound words;
the hat is earthly Adam`'s honour, that is earthly,
which the second Adam never looked for, but gives this mark to know an unbeliever by,
who seeks it and looks for the honour below.

[.discourse-part]
_Principle._ '`Is it not a shame for a boy to say thou to his father, and thou to his mother?`'

[.discourse-part]
_Answer._ Jephtha`'s daughter thoued her father, the judge of Israel,
and he did not look upon it as a shame.
And the children of God thoued their Father, and the Lord never rebuked them for it,
as we read in scripture.

[.small-break]
'''

And as for all the rest of the lies and slanders in thy book,
they are not worth mentioning, but to redeem truth from them;
and that none at all may make them their refuge, for they shall feel it, if they do,
at the day of judgment.
