[.style-blurb, short="Philip Bennet"]
== Some of Philip Bennet`'s principles, called Minister at Cartmel in Lancashire.

[.discourse-part]
_Principle._ He saith, '`That none know another to be the child of God.`'

[.discourse-part]
_Answer._ Which is contrary to the scripture.
1 John iii.
'`Ye are the sons of God.`' And the apostles knew others to be the children of God,
as the ministers of God do now.

[.discourse-part]
_Principle._ Again he saith,
'`that he did not know why God did make a difference amongst men,`' etc.

[.discourse-part]
_Answer._ So is ignorant of the ministry,
which puts a difference betwixt the precious and the vile.

[.discourse-part]
_Principle._ And he said, '`None can give a reason of the election, or know the elect of God.`'

[.discourse-part]
_Answer._ And so is out of the apostle`'s doctrine, who said,
'`they were elected before the foundation of the world;`' and ignorant of the scriptures,
which say, Christ is the elect.

[.discourse-part]
_Principle._ Again he said,
'`he would never exhort people to take heed to that
of God which is made manifest in them.`'

[.discourse-part]
_Answer._ Contrary to the apostles`' doctrine, Rom.
i., Cor.
ii. 4., Colos.
i., 1 John 2:27., Rom. 10:8., who brought people to the light within them,
and to the son within them, Christ within them.
