[#ch-69.style-blurb, short="Adam Sands"]
== Some of Adam Sands`' principles.

[.discourse-part]
_Principle._ He said, '`He hated "`that which may he known of God is made manifest in man,
which God hath showed unto him,`"`' and said,
'`that was the Quakers`' foundation.`' And it was
told him they were the apostle Paul`'s words,
and he was showed the place in the Bible, and bid look at it; he said again,
'`he hated it.`'

[.discourse-part]
_Answer._ So he is found in the nature of the Jews and Gentiles that went astray,
who were not like to retain God in their knowledge,
while they were reprobates from that which may be known of God, made manifest in them,
and hated it.
Neither art thou, nor any professor upon the earth, like to receive God or Christ,
spirit or faith, while thou hatest that of God in thee.

[.discourse-part]
_Principle._ And he called those with him,
'`brethren and servants of God;`' and yet a little before said,
'`they had no grace in them.`'

[.discourse-part]
_Answer._ Contrary to the apostle, who said,
'`the brethren`'s hearts were stablished with grace:
and the grace of God which brought salvation appeared
to all men,`' which taught the saints,
which you have turned into wantonness.

[.discourse-part]
_Principle._ And he confessed, '`that they were more and more ignorant of God,
and blinder and blinder every day than other.`'

[.discourse-part]
_Answer._ We do believe it.
How should it be otherwise with you, who say ye are brethren, and have no grace in you,
and hate that of God in people?
But '`the grace of God which brings salvation hath
appeared to all men,`' which lets them see ungodliness.
So in that the liar speaks in thee;
for that which lets every one see ungodliness is the grace.
