[#ch-72.style-blurb, short="George Johnson"]
== George Johnson, priest of Orford, said,

[.discourse-part]
P+++.+++ '`That the light which John bare testimony to, is the light of nature.`'

[.discourse-part]
A+++.+++ Which is contrary to the scriptures;
for the light which doth enlighten every man that cometh into the world,
was before any natural lights or created lights were.

[.discourse-part]
P+++.+++ '`That the Americans were never ordained for grace and salvation;
and that the grace of God had never appeared to the Americans.`'

[.discourse-part]
A+++.+++ Which is contrary to the scriptures, which say,
'`The grace of God which brings salvation hath appeared to all men,`' etc.
And, '`I will give him for a light, a covenant to the Gentiles,
a new covenant to the house of Israel and Judah,
and that he may be my salvation to the ends of the earth.`'
And many in America have received truth and salvation.

[.discourse-part]
P+++.+++ '`That none can be free from sin, nor perfect, whilst they live upon the earth;
and that none are able to keep the commands of God.`'

[.discourse-part]
A+++.+++ So he hath denied the one offering, and shown himself to be out of the love of God,
and the circumcision of the spirit, which puts off the body of sin,
and out of the blood of the new covenant.
