[#ch-74.style-blurb, short="George Larcum"]
== George Larcum, priest of Cockermouth, in Cumberland. His principles as followeth.

[.discourse-part]
P+++.+++ He said, '`He would come to Christ, and never own the light within him.`'

[.discourse-part]
A+++.+++ None come out of transgression to the second Adam, but who come to the light within,
which is the way to the Father,
and that is it which gives '`the light of the knowledge of the
glory of God in the face of Jesus Christ,`' which comes from him.

[.discourse-part]
P+++.+++ George Larcum said, '`I would to God I had power, thou shouldst be severely punished.`'

[.discourse-part]
A+++.+++ Here thou hast showed thou art limited, and thy weapons and thy armour,
and art not a minister of Christ, in the armour of God, the shield of faith,
nor shod with the gospel; but such are the priests and false prophets,
who are in the form but deny the power of God, who get the magistrates on their side,
that they may be ready to help them against the truth whenever it ariseth.

Thomas Warwicke, priest, came to the meeting of those called Quakers, on a green,
and struck John Grave, and plucked him off the green; and his wife struck and beat sore,
and drew blood of Friends.
And the same priest said, '`If the law were rightly executed, thou might not stand there,
it would cut off all your necks.`'

Thomas Dentham, priest, called me out of the meeting to him,
and said he would stand to prove his practice, and then went his way,
and bade the people take me away, hang me; and at his words the people did beat me,
and pulled the hair off my head.

John Grave,
witness.

[.discourse-part]
A+++.+++ You show yourselves not to be ministers of Christ,
but to be such that ever were out of the saints`' life,
who were found in the spirit of murderers and persecutors;
of him you are that is cut of the truth, that would drink the blood of the saints:
this is the mark of the beast and false prophets, that would kill creatures,
and wrestle with flesh and blood.

[.discourse-part]
P+++.+++ '`That the devil is a minister of Christ in some sense.`'

[.discourse-part]
A+++.+++ Christ the seed of the woman, bruises the serpent`'s head, and destroys death,
and him that hath the power of it, and destroys the works of the devil,
and judges the prince of this world, and takes him,
together with the false prophets and the beast,
and casts them alive into the lake of fire, that he shall deceive the nations no more.
And so he will not suffer the devil to minister;
and thus the devil and his apostles are bound under with the truth, which he is out of.

[.discourse-part]
P+++.+++ '`The scribes and Pharisees were ministers of Christ in the same sort as Moses was,
when Christ commands to hear them, though in a lower degree of manifestation.`'

[.discourse-part]
A+++.+++ The scribes and Pharisees were not as Moses; for Moses was in the life and light,
with which he saw Christ.
The Pharisees had the words of Moses, and the law and prophets,
but were out of the life that Moses and the prophets were in;
though got up in Moses`' chair, they stood against Christ, and saw him not as Moses did;
Christ cried woe against them.
So they were not the ministers of Christ, but against him who was the end of the prophets.
