[#ch-75.style-blurb, short="John Owen`'s Catechism"]
== John Owen, who calls himself a Minister of the Gospel, in his Catechism, which he gives forth, 1657, has these principles.

[.discourse-part]
_Principle._ '`All truth concerning God and ourselves, is to be learned from the holy scripture,
the word of God.`'

[.discourse-part]
_Answer._ There was truth learned before the scriptures were written;
and the scriptures of truth are the words of God, which end in Christ the word;
and there is no truth learned, but as the spirit doth lead into all truth,
which comes from Christ the truth, which was before the scripture was written.
And the spirit of truth leads into all truth of the scripture.
And many have the scriptures, but know not Christ the truth,
but as the spirit leads them, and reveals him;
and so he hath excluded Christ and the spirit.

[.discourse-part]
_Principle._ '`There is one God in three persons,`' etc.

[.discourse-part]
_Answer._ Where doth the apostle tell us of three persons, but tells us of Father, son,
and holy ghost; but thou and you get this out of the mass-book,
and old common-prayer-book, who are the mutterers about three persons.

[.discourse-part]
_Principle._ '`I am conceived in sin, and born in iniquity.`'

[.discourse-part]
_Answer._ Then thy parents were not believers, so children unholy.
For, '`by nature children of wrath,`' that is in the unconverted state,
in the transgression, unbelievers; for they who by nature are children of wrath,
are not born of the believers; for the unbelievers are sanctified by the believers,
else were their children unholy, but now are they clean.

[.discourse-part]
_Principle._ '`We have not kept the commandments of God, but are all sinners,
and transgressors of them.`'

[.discourse-part]
_Answer._ We do believe thee, John Owen, and the rest of you,
who call yourselves ministers of the gospel, and yet have not kept the ten commandments,
and would include all men with you to be sinners and transgressors of them.
Nay, John was separated from you, who said, '`He that loves God,
keeps his commandments.`' But what!
Are you not false witness bearers that call yourselves ministers of the gospel?
and coveters after other men`'s goods, houses,
etc.? Are not you committers of adultery and stealing?
Are not you murdering men in holes for goods, like a troop of robbers,
as the company of priests did in the day of the law and prophets?
Do not you live in dishonouring your parents and God, and taking it to yourselves?
And do not you all come short of keeping the sabbath, who are bearing of burdens,
making a fire, gathering your meat when you should be at rest?
Are not you all taking God`'s holy name in vain, both in pulpit, town-house, ale-house,
streets, market houses, and naming Christ`'s name in your iniquity,
so not held guiltless?
Are not you all making images, and graven images,
and hanging them up in your steeple-houses, and on signs, and in houses, and gardens,
and highways, of things above, and things that are beneath?
And do you think that people do not believe you, when you tell people in your catechism,
that you have broken all the ten commandments, when we see your fruits have declared it?
And are you not ashamed to set forth such a catechism,
who say you keep not the commandments?

[.discourse-part]
_Principle._ '`The sacraments are the seals of the covenant of grace.`'

[.discourse-part]
_Answer._ It is God that seals the son, and sent him into the world, and not outward shadows.
And as for thy word sacraments, the pope was the author of them in his common-prayer-book.
And as for the rest of thy work in thy book of catechism,
it is like unto the old doctors of the Jews that broke the commands of God,
that loved him not, whom Christ cried woe against.
