[#ch-76.style-blurb, short="The Form of Sound Words"]
== S. Palmer, and R. Hooke, who say they are the Servants of Christ, their principles in a book, called '`The Form of Sound Words;`' and who direct their book to the Friends, Neighbours, and Parishioners of Gedling and Sowdham.

[.discourse-part]
P+++.+++ '`That henceforth ye be not children tossed to and fro,
and carried about with the slights of men;`' which is in reference to false prophets,
of whom this land is now full.
You say, '`that a man cannot be made free from sin,
and cannot keep the commandments of God perfectly.`'

[.discourse-part]
A+++.+++ Are not you in the tossing to and fro, and tossing people to and fro?
And are not you the false prophets who Christ said should come, who John said were come,
and the world hath been after you,
who tell the people that they cannot keep the commandments perfectly?
Contrary to John, who saith, he that loves God keeps the commandments of God.
And '`the beast made war against them that kept the commandments
of God;`' and '`herein is the love of God perfect.`'

[.discourse-part]
P+++.+++ You tell people of '`a sacrament, a creed, and three persons.`'

[.discourse-part]
A+++.+++ The scripture tells no such thing, but the common-prayer-book doth,
and so you do not teach the form of sound words in your catechism.

[.discourse-part]
P+++.+++ '`Out of the scriptures we may learn the knowledge of the true God.`'

[.discourse-part]
A+++.+++ That which gives the knowledge of the true God
is the spirit that gave forth the scriptures;
for the Pharisees that had the scriptures knew not God.

[.discourse-part]
P+++.+++ '`The state of man in this life is threefold, creation, corruption, regeneration.`'

[.discourse-part]
A+++.+++ In regeneration the life is changed out of that life which is in the fall.
So regeneration and corruption are not one in the new life.

[.discourse-part]
P+++.+++ '`A man by his own power cannot get into regeneration,
for they are dead in sins and trespasses.`'

[.discourse-part]
A+++.+++ Some are sanctified from the womb, and some children are holy;
so all are not dead in sins and trespasses, for they that are so, are but unbelievers.

[.discourse-part]
P+++.+++ '`All men have not salvation by Christ,
and there are many that have no share in the salvation purchased by Christ.`'

[.discourse-part]
A+++.+++ This is contrary to scripture, which saith,
that he is the offering for the sins of the whole world, and the saviour of all men,
and especially of those that believe.
And they that turn the grace of God into wantonness, deny their salvation;
and they who hate the light which enlightens every man that cometh into the world,
hate their '`salvation to the ends of the earth.`'

[.discourse-part]
P+++.+++ '`The scripture is the word, and God is in his word,
and God in the scripture offers Christ: God in his word offers Christ,
which you call scriptures.`'

[.discourse-part]
A+++.+++ The scriptures of truth are the words of God,
and Christ the word comes to fulfill them; and God was in them that gave forth scriptures,
and Christ was in them who gave forth scriptures, and the scriptures testify of him;
and the scripture doth not say that God is in the dead letter, paper and ink.
But his power ye are ignorant of, and err, not knowing the scriptures;
and the scriptures are not God.

[.discourse-part]
P+++.+++ You say, '`that God works inwardly by his spirit, and outwardly by his word,
and our faith is summed up in the apostles`' creed.`'

[.discourse-part]
A+++.+++ Christ is the author of faith; and the apostle doth not tell us of a creed.
The spirit and the word are one, and they are inwardly known, sanctifying.

[.discourse-part]
P+++.+++ '`The rule of Christian obedience is the law of God.`'

[.discourse-part]
A+++.+++ That which is the end of the law, is a Christian`'s life and rule,
who comes to the obedience of faith, in which he pleases God, and is justified,
but no flesh by the works of the law is justified.

[.discourse-part]
P+++.+++ '`Brethren, be perfect, be of good comfort; be of one mind.
No man is able to keep the commandments of God, we break them daily in thought, word,
and deed; in the best of our duties we are unprofitable servants.`'

[.discourse-part]
A+++.+++ Here is your confusion laid open; those that were perfect had a new mind,
and their deeds were wrought in God,
and their thoughts were changed that witnessed repentance,
and they kept the commands of God; and their fruits were of the spirit and of faith,
which are not unprofitable.
But your works and fruits, who are out of the faith, and out of the spirit of God,
are unprofitable, who break the commandments, but they that love God,
keep his commandments.

[.discourse-part]
P+++.+++ '`Christians must attend upon God`'s ordinances and sacraments,
to know their duty toward their neighbour,
which sacraments are the seal of the covenant.`'

[.discourse-part]
A+++.+++ The apostles tell us of no such signs or sacraments, nor such words;
but that which fulfils law is Christ the son of God,
which brings man to do his duty towards God, and towards his neighbour.

[.discourse-part]
P+++.+++ '`There are two sacraments,
and the covenant of grace is to all that believe and receive Christ;
and the two sacraments are baptism and the Lord`'s supper, which are visible signs.`'

[.discourse-part]
A+++.+++ The scripture doth not any where call them visible signs, nor sacraments;
and the covenant of grace is to all, whether they believe, or do not believe; receive,
or do not receive;
and the scripture doth not call baptism and the Lord`'s supper sacraments.

[.discourse-part]
P+++.+++ '`Because infants of the Jews were circumcised, therefore are children baptized:
Christ hath ordained this sacrament of bread and wine,
and the sacrament is the food of the soul.`'

[.discourse-part]
A+++.+++ This is a Popish doctrine; that which feeds the soul is immortal,
and that is the soul`'s food which it finds rest in, Christ the bread of life,
the food for the soul.
And the scriptures do not tell us that the bread and wine are a sacrament;
and the scriptures do not tell us that circumcision outward was a type of outward baptism,
but of the inward.
And you bring a scripture, which is the xxiii.
of Luke and the 43 verse, and say, that it saith,
'`that the souls of the wicked are cast into hell,`'
but that scripture speaks no such thing.

[.discourse-part]
P+++.+++ '`We are not to seek for happiness in this life.`'

[.discourse-part]
A+++.+++ The saints were and are made partakers of the heavenly riches,
and of Christ`'s fulness, and of his joy unspeakable and full of glory in his kingdom,
which is in them, while upon the earth.
And for the rest of your lies and confusions, they are not worth answering.
