[.style-blurb, short="One Sheet for Ministers"]
== Richard Baxter`'s principles, in that which he calls, [.book-title]#One Sheet for the Ministers,# which is two sheets, in whose mouth is found a lie, as in his title page is to be seen.

[.discourse-part]
_Principle._ '`That we are hated of all men for the name of Christ who are but ministers,
who gave some pastors, some teachers; appointed for the perfecting of the saints,
for the work of the ministry, for the edifying of the body of Christ,
till we all come to a perfect man; to disciple nations, baptize, and teach them.
So cut down the ministers, the pillars, and the buildings will fall.`'

[.discourse-part]
_Answer._ In the steps of the ministers of Christ you are not found,
but in the steps of the scribes and Pharisees,
'`called of men masters,`' in '`the chiefest seats`' of assemblies, in your long robes,
'`and uppermost rooms at feasts,`' causing the ministers
of Christ to be haled out of your synagogues,
and thrust out, and persecuted, and prisoned,
who are in the generation of serpents that should fulfill Christ`'s words.
Matt.
xxiii.
And the work of the ministry, and pastors, and teachers, you exclude yourselves from,
who received their gifts from Christ;
you who deny perfection while men are upon the earth, or coming to a perfect man,
you are not with them that edify the body of Christ,
but throw yourselves out of that work.
And you are not them that are for the perfecting of the saints,
for none are the ministers of Christ, but who bring people to a perfection,
out of imperfection, and to a perfect man; and these were the ministers that were,
haled by those priests that had the law, and tithes, and temples, and synagogues,
that made nothing perfect.
But your temple and tithes, and synagogues,
have been invented by such as went forth from the apostles, whose successors you are,
that had the form of godliness, but denied the power,
and so they denied that which was perfect; and this you have held since the apostles,
in the apostacy, whose work, and ministry, and foundation,
are to be overthrown with the power of God,
having been that which hath drunk the blood of the
saints and martyrs since the days of the apostles.
But in the rising of the lamb and the saints, you are all overthrown, and rejoiced over,
and slain with the sword which is the words of his mouth.
Though you all, beast, false prophet, and antichrist, may rise in battle against him,
the Lamb and the saints shall have the victory.
You have been the pillars that have held up antichrist`'s kingdom,
in the usurped authority, out of the power and life the apostles were in,
who were sent to preach and baptize; but you baptize and then preach,
which is quite contrary to all reason and true understanding;
for they must first be preached to before they be baptized.
Did not John rebuke the vipers, and asked them,
who had forewarned them '`to flee from the wrath to come,`'
and bid them '`bring forth fruits meet for repentance,
and think not to say you are of Abraham,
for God is able of these stones to raise up children
unto Abraham?`' Now where is your measure,
you priests?

[.discourse-part]
_Principle._ He saith, '`I send thee to open the eyes of the blind,
and to turn them from darkness to light;
how many millions of souls would these wretches sweep away to hell,
if they had their will, while thousands are in damnation for want of the light?`'

[.discourse-part]
_Answer._ All you priests and teachers who call yourselves ministers,
since the days of the apostles, who are inwardly ravened from the spirit of God,
are turning and have turned all people from the light to the darkness,
and so have kept thousands and millions of souls in damnation,
and have been turning them and keeping them in the path and way unto hell;
who are Satan`'s messengers and ministers, stopping the eyes of people from the light,
and their ears from hearing the word;
and this hath been the work of your ministry and
hath been ever since the days of the apostles,
and as at this, day, the people of the whole nations have witnessed, and may witness.
Now Christ`'s ministers were sent to turn people from darkness to light,
and to bring them to perfection, to a perfect man, out of that which was not perfect.
Satan, who went out of truth, the work of his ministers and messengers,
whom he sends out from his authority, is to turn people from the light to the darkness,
and keep them there.
And this hath been your work, as your pulpits and the nations declare.
So you bring not people into unity and fellowship one with another,
which is in the light, but set people at enmity one with another,
and keep them from the light, who are with it condemned.

[.discourse-part]
_Principle._ '`The enemies of the ministers of Christ are playing the papists`' game;
that it will be easier for Sodom and Gomorrah in the day of judgment,
than for them who despise the ministers of Christ.
Touch not, mine anointed, and do my prophets no harm.
And the enemies do reproach the ministers of Christ, which is the devil`'s game,
and the sects are against the ministers of Christ,
and do the same work the drunkards and whoremongers do,`' etc.

[.discourse-part]
_Answer._ This thou hast brought upon thine and your own heads,
though thou art blind and seest not thyself.
And all drunkards, whoremongers, idolaters, and the proud and covetous,
have joined with you called priests, against them called Quakers,
the only ministers of Christ not made by men, but by the will of God.
Are not all sects joined with you against them?
Are you not reviling them, and railing upon them in your pulpits,
and is not this the devil`'s game you are doing?
And if come amongst you to prove you, either in season, or out of season,
you are they that cannot endure sound doctrine, nor able to resist their spirits,
or stand against them, but cry,
'`take them away;`' so they are beat and knocked down in your steeple-houses,
sent to stocks or prison.
Are you not like Sodom and Gomorrah in this, and like the Pharisees, and the beast,
and the mother of harlots,
and false prophets which John speaks of who take the blood of the saints,
doing their game?
Hath not the Lord reproved many of you, yea, and magistrates too,
for harming his prophets, yet you go quite contrary to scripture, which saith,
'`Do my prophets no harm.`' And is not this the papists`' game, to prison and persecute?
and was it not the papists`' game to set up your mass-houses which you call churches?
and their game to call out, and to persecute,
and make a law and decree that none should speak to them in their time of preaching,
reading, or singing, mass?
And are not you quenching the spirit, when any are moved of the Lord to speak to you?
Was not this the papists`' game, which you are now doing?
Did ever the apostles hale any out of the synagogues, but were so done unto themselves?
But the Jews`' game, and the papists`' game, and your game are like one another here.
Unlike the true Christians, Christ and the apostles,
who wrestled not with flesh and blood, not striking at the creatures,
but at the powers which captivated creatures,
to the intent that the creatures might come into the liberty of the sons of God.
So you that are striking the creatures, wrestling with flesh and blood,
are playing the devil`'s game, like your mother from the beginning.
Was it not the papists`' game to set up all your schools and colleges,
and give your names to them, and your houses, and set them in the figure of the temple?
And when altered you them?
do you not go on in the papists`' game?
Was it not the papists`' game to set up tithes?
and are not you playing the same game in taking them?
Was it not the papists`' game to set up your hour-glasses, and preach by the hour,
and marking with your cross, and setting your godfathers and godmothers?
and are not many of you playing this game yet?
What game are you playing in your steeple-houses, but the papists have, taught you it?
The papists were persecutors, and so are you.
They haled out of synagogues, and so do you.
They took tithes, and so do you.
They preached by the hour-glass, and quenched the spirit, and so do you.
They preached for means and glebe-lands, and so do you.
They had the cross on the top of steeple-houses, and so have you in many places.
They had Trinity College, Emmanuel College, and Christ`'s College, and so have you.
They named the saints`' days, and so you follow them.
They called their houses by the name of Trinity, Jesus, Emmanuel, and their mass-houses,
by Peter, and Paul, and Mary, and so do you.
Is not this the papists`' game?
Do not they called Quakers deny this game, and you both?
And Christ thou art ignorant of, who is come to reign, and rule,
and teach his people himself.

[.discourse-part]
_Principle._ '`Ministers are spurring on the magistrates,
to cast out the bad and scandalous ministers.
Have not lawyers and physicians an easier life, and more honourable in the world,
than the ministers?
and have not the ministers been the principal instruments to pluck down deans and chapters,
bishops, etc.? We ministers break our health and all our worldly interests for you.
And I had rather be a ploughman or the meanest tradesman, but for the greatest necessity,
and the truth`'s sake.`'

[.discourse-part]
_Answer._ Have not all you ministers in this manifested yourselves?
Did ever the apostles fly to the magistrates,
or spur them up to cast out scandalous ministers?
Had not the apostles authority, and the spirit and power, to cast out, reprove,
and rebuke in the church?
Had they not denied their power if they had gone
to the magistrates and fallen on the mountains,
which is the papists`' game,
and not the apostles`'? Was it not the soldiers that
were the cause of pulling down your rails and surplices,
and your deans, and chapters, and bishops?
was it not the magistrates`' work?
But have you had a hand in it?
Have you killed and taken possession?
Have you put out bishops, and got into their places, who are in the bishops`',
and deans`', and chapters`' maintenance?
Will you needs make yourselves so foul and odious to all people?
Were not many of you tradesmen and ploughmen`'s sons, poor men,
and yet now gotten up into great interests, and taking great sums of people,
of many whom you do no work for?
How can you for shame say you leave your worldly interests,
when you are but running into them when you come to be priests and ministers?
Who are the proudest people in the parishes,
in the glories and vanities of the world and honour of it, but the priests,
and their wives, and their children?
Are not you worse than lawyers and physicians, taking the people`'s money,
and yet cannot make them perfect men, but say they must not be perfect?
The physician is to make one perfect.
Do they take money of people they do nought for?
Are they not ashamed to do so?
But you take money of them you do no work for!
Are you not worse than the lawyers, who are bad?
Do you not take money of such people as you do not work for, and sue them,
and cast them into prison?
Are you not the most unreasonable men upon the earth?
And this is the devil`'s game you are playing.
And do you not live in more honour in the world, greater gain, and no work done for it,
than any other people in the nation, as the jails may witness your fruits!

[.discourse-part]
_Principle._ '`All nations that are of the Christian world, are for the ministers to this day,
and they that are not, are the dry branches that are out from the church.
Oh! how have I besought the Lord that he would convert
you to remember them that have the rule over you;
they that have spoken the word of God and rule well, are worthy of double honour.`'

[.discourse-part]
_Answer._ You are apostatized from those elders among the apostles, and from the apostles,
in an usurped authority, ministers made by the will of men, at schools and colleges,
not by the will of God, as the apostles were.
So your honour must be defaced; and you are the dry branches,
cut off from the true church,
your church and ministry both wanting the virtue and life of God;
so are broken into heaps, and sects, and names among yourselves,
wanting the unity and bond of peace.
The nations have gotten the name of Christians, but are dead, are from the life;
and your prayers are as the Pharisees, you being found in their steps, as Matt.
xxiii.
read you all.
You say none must be perfect upon earth, how then converted?
Who are converted are converted into Christ, who is perfect, out of the first,
which is not perfect.

[.discourse-part]
_Principle._ '`The enemies of the ministers are the forerunners of the heavy wrath of God;
and the Jews were quite cut off from the church and made vagabonds upon the earth;
they mocked the messengers of God, until wrath came upon the people.
Ministers are either their fathers or nurses in the Lord.
Their sin is killed, and grace is quickened by the ministers`' means.`'

[.discourse-part]
_Answer._ It was the forerunner of the wrath of God upon the Jews,
that they had temples and tithes, and stood against the ministers of Christ;
it is so to you, as it was with them that saw not the substance,
that now stand against the light, and fight against it.
And were not railers, envious men, and persecutors always the vagabonds?
And are not all you vagabonds from the life of the apostles,
as the Jews were from the law of God?
And are you not all on heaps about words and scriptures, showing you are without life?
And are not the wrath and plagues of God, and overflowing scourge,
come upon you who are thus standing against his ministers in this
his day that are sent among you cages of unclean birds,
who comfort not the people, kill not their sins, quicken not their grace,
keeping the people in their sins, telling them they must have the body of sin,
while they are upon earth!
Are not you mocking the messengers and ministers of Christ?
Hath not the wrath come upon you?
Many of the people stricken dead for so doing?
You are out of, and apostatized from the church of the apostles,
that are persecuting and mocking the ministers of Christ who in scorn are called Quakers,
who are sent freely amongst you, not for glebe-lands, tithes, Easter-reckonings,
nor midsummer-dues; nor like you that put the Papists out of glebe-lands, tithes,
Easter-reckonings and midsummer-dues, and get into them yourselves;
that put Papists out of their mass-houses and run into them yourselves.
So in this you are not like the ministers of Christ, who seek not these but them;
but you are seeking these, not them, but are putting them out;
this causeth plagues to come upon you.
And so it is because Papists and drunkards, and them that are now called ministers,
are seeking the people`'s means, not the people,
that makes the true ministers of Christ odious, who are in scorn called Quakers,
who seek not theirs but them.
And you are neither the true fathers nor the true nurses, but in the apostacy from them,
and kicking against that which pricks you, going in Saul`'s steps,
who went with priests that had tithes, who were strayed from the life,
and saw not the substance, as you raveners from the spirit of God have set up tithes,
who see not the substance; you harden yourselves, not hearing the voice,
from whose eyes repentance is hid, posting on for your earthly interests and means,
posting to courts, sessions, assizes, and benches.
And this is the work you are doing, as the courts, sessions, and assizes declare,
hurrying the people thither, seeking theirs not them; your spirits are tried at courts,
sessions, and assizes, to be the false spirits that went forth into the world,
which Peter, Jude, and John speak of, which went forth from them,
and separated themselves, which the world since went after, who have been in Cain`'s,
Core`'s, and Balaam`'s way.

[.discourse-part]
_Principle._ '`Tradesmen and princes`' labour preserves health, but mine consumes it.`'

[.discourse-part]
_Answer._ Here thou hast shown that thy labour, work, and ministry are not of God,
that preserves health and strength;
for the work of the ministry is to bring into the saving health, and preserve it,
and not consume it, as thy work doth; that they may honour God with their substance,
and serve him with all their strength.

[.discourse-part]
_Principle._ '`The law gives tithes,`' say the priests, and allow '`we may forbear,
working,`' and we '`are content with food and raiment; and to give away our tithes,
if the people will allow us food and raiment for us and our children,
as is fit to make them serviceable, yet the Quakers call the ministers covetous.`'

[.discourse-part]
_Answer._ The Jews`' priests who were made obedient to the faith, had a commandment,
while they were under the priesthood, to take tithes according to the law,
but the ministers now turn again from the faith to the law,
and say the law of God gives it them,
and say the tithes are not the people`'s but the Lord`'s. Did not
the apostles cut off tithes before the law and in the law,
the priesthood and law both?
And have not you here shown yourselves apostatized from the apostles, so in the apostacy,
who have set up a law, the first author whereof was the pope,
and say the law gives it us,
and that you would not leave tithes unless the people
would make a bargain with you to maintain you,
your wives and children?
Was this the work of the apostles`' ministry?
What shameless words are these!
What!
Set yourselves thus that all people may view your folly?
What the apostles did give, was it upon condition,
that the people should give them food and raiment for it?
Did not the apostles say,
'`He that will not work let him not eat?`' But from the
whole practice of the apostles you are apostatized.
And are not your covetous practices discovered through all the courts, sessions,
and assizes in the nation?
You posting up thither, and suing,
and causing them to go thither you do no work for
what is this but covetousness and unrighteousness?

[.discourse-part]
_Principle._ '`The Quakers say,
that the priests are persecutors like the priests and Pharisees of old;
but they shall be taught one day to know, that if the magistrate stops their mouths,
he does no more persecute them, than a thief when he is hanged,`' etc.
You say, '`you wish all the Lord`'s people were prophets.`'

[.discourse-part]
_Answer._ This is a lie found in your mouths; for you say prophesying is ceased;
this you sound abroad all the world over, as far as you can.
This shows that you are not able to stop their mouths,
nor resist the spirits of those of whom you say,
it will be no more persecution for the magistrate to stop their mouths,
than to hang a thief.
And thus to all magistrates that fear God, you appear with shame;
and all may see what you crouch for under the mountains, for blood, Jezebel like,
and make the magistrates your pack-horses, and the executioners of your malice.
But the Lord God of heaven and earth, in his wisdom, is opening the eyes of many;
that moderation appears in such in whose hearts the fear of the Lord is placed,
that tries many of you, and turns many of you to your own weapons,
to see what weapons you have, and they find you but wrestlers against flesh and blood,
striking at the creatures, not at the power which captivates them,
to bring them out of it into the liberty of the sons of God.
The true ministers`' work was to beat down blasphemers, errors, and false prophets;
to stop the mouths of gainsayers; rebuke, exhort, teach, instruct with all authority,
and cut off occasions with spiritual weapons.
And this power had they in the church, and cried not to the magistrate, '`take them away,
they disturb me.`' Oh! shameless! shame thyself before all the people in the congregation!
This was not the work of the ministers of Christ to do so.
And this authority in the church, before mentioned,
which the ministers of Christ had to stop the mouths of gainsayers,
and silence false prophets and blasphemers, they had from God,
and looked not at men to help them; but they who apostatized from the apostles,
the beast, the false prophet, the mother of harlots, that deceived the nations,
that were out of the power of the apostles and Christ, have had their power from men;
all the false ministers upon earth are seeking to them to stop blasphemers as they imagine,
being but contrary to their minds, while they themselves are the blasphemers,
as weighed and judged by the scriptures and spirit of truth.
And the magistrates`' work, the power which he receives from God,
is to punish profane open sins;
and the ministers`' work is to bring people from under that occasion.

[.discourse-part]
_Principle._ '`The magistrates set their guards at our doors, and let in none but whom they please.
Let the kings of the earth show an uninterrupted succession,
giving them right to their crowns,
and I will show a more undoubted succession to the ministry.
All the Christians in our parishes are our flock,
we undertake to prove the truth of such churches.`'

[.discourse-part]
_Answer._ Your church is guarded with carnal weapons,
and the succession of your ministry is like unto the succession of earthly kings`' crowns,
which are all made by the will of men.
And the magistrates have been but your servants,
and through ignorance have quenched the spirit.
And your work hath been to destroy the order concerning edification, practice,
and doctrine of the apostles in the true church, who said, '`Let all speak one by one.
If any thing be revealed to another that sits by, let the first hold his peace.
The spirit of the prophets is subject to the prophets.`' From this you are apostatized,
and have gotten a law to stop the practice of this in your church apostacy, whose doors,
many of them, you keep with clubs and staves,
lest any should be moved from the spirit of the Lord to speak amongst you from the Lord.
And your parishes and flock which you undertake to prove to be a true church;
alack for you!
That people should be so impudent as to say these are the pillars and ground of truth,
or that the steeple-houses are the pillars and ground of truth!
A company of drunkards, swearers, covetous, proud persons, given to pleasures, you are,
like them that said they were Jews, and were not, but the synagogue of Satan,
a nest of unclean birds.

[.discourse-part]
_Principle._ '`We expect not perfect unity, till we have perfect knowledge and holiness.`'

[.discourse-part]
_Answer._ Have you cried up yourselves to be the ministers of Christ all this while,
and have not perfect knowledge, perfect holiness, perfect unity?
The least unity is perfect in the spirit, and the least knowledge,
and the least holiness in the spirit; and you acknowledge you have not perfect unity,
perfect knowledge, perfect holiness,
and this hath been the cause you have kept all people since the apostles in blindness,
out of the unity, in that which is unholy, who say you have not the perfect knowledge,
for the least degree of holiness is perfect, and in the holiness is the unity,
in which is the perfect knowledge, though in the least degree.
And this thou hast confessed you have not, and we do believe you;
and from thy own words thou and you are proved unsanctified;
for who are sanctified have perfect unity, perfect knowledge, perfect holiness.

[.discourse-part]
_Principle._ '`I use notes as much as any man, when I am lazy or busy,`' etc.

[.discourse-part]
_Answer._ This is what holds up your lazy minds, what you gather out of books,
selling it again by the hour-glass;
and you make that day you call the sabbath your market day,
selling both prayers and preaching,
who have not the spirit of the Lord to lead you to speak as it moves,
and to lead you to all truth as it did the disciples.
So it is laziness indeed that hath set up your notes,
and you read them by the glass for money,
and have learned seven years out of books and colleges,
and then gather up notes out of your authors and books, and thus make a trade of them,
and then tell the people you are sent, and it is the word of the Lord,
when it is but from the reading of books!
And yet you tell people you never heard the voice of God, if any ask you;
and thus deluders are judged out of their own mouths, who have a law,
if any are moved of the spirit of the Lord, while they are reading their notes,
or speaking before or after,
none are to speak against what they have gathered out of their books and studies;
which was not the work of the true ministry,
but the work of those who were out from the true spirit,
and so were ministers of the letter, and old authors, and notes.

[.discourse-part]
_Principle._ He saith, '`They are unmerciful men that say, more glorious days are appearing,
and that the saints shall rule the world.`'

[.discourse-part]
_Answer._ In this thou hast judged thyself, and there need no more words be spoken to it.
And the rest of thy lies and slanders in thy book, are not worth mentioning,
they will fall upon thy own head.
