[#ch-78.style-blurb, short="John Cole"]
== John Cole`'s Book, (printed 1658,) his principles in it follow.

[.discourse-part]
_Principle._ '`It is a common thing for the young harlot to say, mind the light within.`'

[.discourse-part]
_Answer._ The light which doth enlighten every man who cometh into the world,
draws from all harlots, and they are out of it; and such may beget proselytes,
and father them upon God, who are not in the truth;
but the day is come that all things are made manifest, and by it do appear.
And the light which every man which cometh into the world is enlightened withal,
is the offence to all the evil doers who are out of salvation and the covenant of God,
and none see salvation but by it.

[.discourse-part]
_Principle._ '`The young harlot can but mend evil old Adam by her exhortations, and instructions,
and doings, and threatenings, and she doth fright some to her obedience.`'

[.discourse-part]
_Answer._ The harlot is in that which evil old Adam is in, in the transgression;
and so they who are harloted from the spirit of God cannot mend and instruct the transgressor,
they themselves being in the transgression.
They may tell them of the saints`' words, and speak them, as the devil doth,
who is out of the truth; but thou, John Cole, art fallen into the earth,
and there art quarrelling.

And as for the rest of the stuff in thy book it is not worth mentioning;
but when thou feels the root and tree burn and fall into a fire about thee,
and thou in it, then remember thou hast not that which doth savour, as thy confused,
childish works do make appear, which in print thou hast published to the world.
