[#ch-79.style-blurb, short="A View of All Religions"]
== Alexander Ross`'s Book, which he calls, [.book-title]#A View of All Religions.# His Lies and Principles.

[.discourse-part]
P+++.+++ '`God is not in the quaking of the body.`'

[.discourse-part]
A+++.+++ Was it not God that made the body of David to quake?
and Daniel, and Habakkuk, and Job?
And the mountains quaked at the giving forth of his law.
And doth not God say, '`he doth not shake the earth,
but heaven also?`' Now dost not thou manifest thyself to
be one of them that cast those out that tremble at the word,
and tell them that God is not among them?

And as for Alexander Ross`'s lies and slanders, in saying the Quakers said,
Christ had failings, and distrusted God;
which thousands of thousands that can witness to thy face thou art a liar,
it is a sufficient proof to them that thy book is made up of such stuff, of lies,
which is thy view from the creation.
And the rest of thy book is much like unto that.
And the false prophets`' studying a divination of their own brain,
to get money by we deny; but such as divide the word aright we own.
And all that pray, and preach, and sing for money,
and make a trade of the scripture to get money by, we disown;
but such as pray and sing by the spirit we own.
And all your readings for money we deny; but who read freely we own.
And all your ceremonies we do deny, and are come to the substance Christ Jesus,
who was before the world was made.

[.discourse-part]
P+++.+++ '`The leaves of a tree are not the fruits thereof,
and yet without them the fruit would not prosper.`'

[.discourse-part]
A+++.+++ Art thou a fit man to give a view from the creation of the world,
who errest thus in naturals?
For, pluck off the leaves of the vines, and see if the grapes will not prosper?
Art thou a fit man to give a view of religion, and blasphemy, and error,
from the creation, who art not able to give a true view of the naturals?

[.discourse-part]
P+++.+++ Thou sayest, '`It is horrid blasphemy to say the scripture is not the word of God,
and to say the soul is a part of God.`'

[.discourse-part]
A+++.+++ The scriptures are the words of God in Exodus, and the four books of the Revelations,
but Christ is the word in whom they end;
and it is not horrid blasphemy to say the soul is a part of God, for it came out of him,
and that which came out of him, is of him, and rejoiceth in him.

Why wilt thou lie, in saying the Quakers deny the word?
We say, it sanctifies them.

[.discourse-part]
_His lies._
'`Christ is not ascended into heaven; that there is no heaven, nor hell,
nor resurrection of the body; that we have no sacrament nor trinity.`'

[.discourse-part]
A+++.+++ As for the words sacrament and trinity, they are from the pope, the mass-book,
and the bishops`' common prayer; but unity and the Lord`'s supper are owned; and heaven,
hell, Christ, and ascension, and resurrection are owned by the Quakers,
as the scriptures declare them.
And your old mass-house, with the cross atop of it, which you call your church,
the beast hath set up since the days of the apostles,
with his lying sign at the end of it, the pope`'s cross.
And Christ came to destroy self, and reconcile into one;
and Christ forbid men to be called of men master, and said the Pharisees did so.
And magistrates are owned in their place;
but all those ministers that teach for filthy lucre,
that serve an apprenticeship at schools and colleges like tradesmen, such we deny,
such are not fit to study nor expound scripture;
for they bring people into heats and into blood, as their fruits in christendom declare.
But the prophets, Christ, and his apostles and ministers, their practices are owned,
and elders, and their honour;
but the honour of the false prophets and apostles is defaced by the true.
And the scripture doth not speak a word of sprinkling of infants,
but the baptism of the spirit is owned.
And all your prayers in your mass-house, Pharisee like,
and your songs in the temple shall be turned into howling;
but that which is according to the spirit of God is owned;
and private and public instructions are owned that are in the spirit of God;
and David`'s psalms in their place are owned,
and the saints`' singing with understanding also we own.

[.discourse-part]
P+++.+++ They say, '`The Church is in God, therefore God is not in the church, they may say.`'

[.discourse-part]
A+++.+++ This is like thy reason, and thy measure and weight.
The church is in God, and God is in the church;
and where two or three are gathered together, he is in the midst of them.

[.discourse-part]
P+++.+++ He says, '`We speak against tithes and clerks`' wages for saying, Amen,
and this thou sayst is an absurd opinion.`'

[.discourse-part]
A+++.+++ Tithes before the law, and in the law, were owned,
that they should give the tenth of the spoil and the tenth of the earth,
for the services that were required, for widows, strangers, fatherless,
and Levi who had no portion in the earth, that there might not be a beggar among them;
these tenths preserved them from beggars, and this was the law.
And Melchizedek, who was without father or mother, took the tenth of the spoil,
before the law; and Christ the end of the law, puts an end to all spoils,
and redeems men out of the ninth and tenth parts of the earth to God;
and here the day of salvation is known to reign upon the earth.
For when man transgressed, being drove from God into the earth, then the law came,
that was over all transgression, and led out of it;
by that law were they to offer up the tenth;
and Melchizedek before the law had the tenth of the spoils,
but Christ who ends the wars, ended the spoils, and the tenths,
who is the heir of all things, the covenant of God; who reconciles all things in one,
things in heaven, and things in earth.
And this the apostles preached, who were in the power of God,
who brought men out of the ninths of the earth and tenths too,
and brought men out of the occasion of the wars into that which ended them,
which was the power of God.
But they who went forth from the apostles into the earth,
that had the form of godliness and denied the power thereof,
who led the world after them, set up ninths and tenths,
unlike the ministers of the gospel,
who brought them out of the ninths and tenths into unity with the power of God,
and the son, and to reign upon the earth.
And they that take tithes now, are unlike them that took tithes under the law,
or before the law, that Abraham gave the tenths of the spoil to,
who met them with bread and water, but these now have no storehouse for widows,
strangers, and fatherless, that there need not be a beggar among them.
So they who are called christian priests, who cannot get their tenths without prisons,
courts, and writs, and treble damages, and casting into prison until death for them,
are worse than the Jews.
These are called christian practices in our days by them
who are apostatized from the true apostles and church,
and from the power of God they were in!
But the maintenance that Christ speaks of to his ministers is owned,
but all that make a trade of the words of the prophets, Christ, and the apostles,
who laid down their lives for speaking them forth, we deny.
And the apostles did not give a clerk wages to say amen,
but that came up since the apostles`' days, and is judged by the spirit of truth,
and whosoever will make Alexander Ross`'s lies in his book called,
[.book-title]#A View of Religion,# their refuge, are in a sad condition, both which,
he and his lies, are condemned to the fire and lake by the power of God.
Glory in the highest!
Rejoice over them ye saints.
