[#ch-80.style-blurb, short="Richard Mayo"]
== Richard Mayo, Priest of Kingston, his Doctrine and Principles, as follow.

[.discourse-part]
P+++.+++ '`That the light within is the light of nature,
which teacheth to do all things that the law commands,
and to deny all things that the law forbids.`'

[.discourse-part]
A+++.+++ That which teacheth to do all things the law commands, and deny what the law forbids,
is above nature; that is it which keeps nature in its course,
that it shall not be of a fire; but we see thy nature is gone out of its course;
and is all on fire among you priests and professors.

[.discourse-part]
P+++.+++ '`That God set up a dim light in every man.`'

[.discourse-part]
A+++.+++ The light that God set up in every man is not dim,
but men grow dim when they transgress the light, which God hath set in them,
to give them the knowledge and feeling of himself.

[.discourse-part]
P+++.+++ '`He said the devil was the power of God,
and that Christ was made manifest to destroy the power of God,
and to destroy him that was the power of God.`'

[.discourse-part]
A+++.+++ The devil that went out of the truth, went out of the power of God,
and Christ was manifest to destroy the works of the devil, and not the power of God,
though Christ came to put an end to all figures, types and shadows, priests,
first covenant, and temple; Christ, who is the power of God,
did not come to destroy the power of God, the power of God is not divided against itself;
and the devil that went out of the truth, the power of God went against him:
so he is not the power of God, that went out of the truth,
that tempted others out of the truth to transgress and to sin, by which came death,
by which the devil, that went out of the truth, hath the power of death.
So it is the power of death, which Christ the power of God destroys,
and him that hath the power of it.

[.discourse-part]
P+++.+++ Mayo saith, '`To say the gospel is the power of God, is but a metaphorical speech.`'

[.discourse-part]
A+++.+++ The apostle doth not say so; for the Apostle saith,
'`The gospel is the power of God unto salvation,
to every one that believes,`' in plain words.
Rom. 1 chapter.

[.discourse-part]
P+++.+++ He said, '`that by that lantern or light, spoken of in the Psalms,
which was a light unto David`'s path, was not meant Christ the word.`'

[.discourse-part]
A+++.+++ Why then doth the apostle often bring David`'s
words to prove that David did speak of Christ;
and spake of the sure mercies of David, of the everlasting covenant of light,
and that in his light he should see more light, and called him Lord?
And David saw his flesh that should see no corruption, and his resurrection;
and many other scriptures might be brought to prove this.

[.discourse-part]
P+++.+++ He said, '`The scriptures were the seed which the sower went forth to sow,`' Mat.
13.

[.discourse-part]
A+++.+++ The seed is that which the scripture speaks of, which Christ said is the word;
and many who have the scripture, know not the seed, nor the thing it speaks of,
nor the seed that is sown, which is the word, as instance the Jews and you Christians,
who put scripture for it; for if the scripture be the seed, it is sown already,
it is printed, and what need you go out to sow it?

[.discourse-part]
P+++.+++ He saith, '`that Paul in the v. the Ephes. 18.
exhorts the Ephesians to follow a light which
was not the light of the gospel,`' and he said,
'`he could not prove in plain scripture in so many words,
that any of the ministers of Christ exhort the saints
to follow a light which was the light of the gospel.`'

[.discourse-part]
A+++.+++ We herein see his confusion, who confounds himself;
and that in the Ephesians which he saith was not the light of the gospel,
let all people read, where Paul bids them not to be drunk with wine,
but be filled with the spirit; and this is the light of the gospel,
which '`doth enlighten every man that cometh into
the world,`' which darkness cannot comprehend,
where the God of the world hath blinded the minds of the infidels,
lest the light of the glorious gospel should shine into them;
as the minds of all the priests in the world do appear
to be blinded by the god of the world,
that the light of the glorious gospel, which is the image of God,
which shines in the hearts of believers, they do not behold,
and though the light shines in darkness, their darkness comprehendeth it not.
Therefore they rage like the Jews, and are professing the letter as the Jews did,
standing against the light, with which light they are comprehended,
which was before ages were.

[.discourse-part]
P+++.+++ He saith,
'`that Paul`'s persecuting the saints was a righteous
thing in the sight of men,`' and he said,
that '`he denied that any doer of the law is justified, so as to be saved.`'

[.discourse-part]
A+++.+++ Paul`'s persecuting the saints was not a righteous thing among righteous men,
that were in the righteousness of God; for Christ the righteousness of God saith, '`Paul,
why persecutest thou me?`' Now Paul`'s persecuting
was justified by them who were in the self-righteousness,
out of the righteousness of Christ;
and such as are in that righteousness may justify thee and thy persecution.
And the doers of the law are justified, and they who are justified are saved,
and Christ the end of the law, who redeems from under it,
they come to know to be salvation itself.
So I through the law, am dead to it, and know it a schoolmaster,
and the righteousness of the law fulfilled in me.

[.discourse-part]
P+++.+++ '`That a man may be a righteous man, and not a godly man.`'

[.discourse-part]
A+++.+++ A righteous man in the righteousness of Christ, is a godly man,
who has the righteousness of the law fulfilled in him,
but a righteous man in self-righteousness is ungodly.

[.discourse-part]
P+++.+++ '`That a man may be justified by God, and yet condemned by his own conscience;
and justified by his own conscience and condemned by God.`'

[.discourse-part]
A+++.+++ A man that is justified by God is not condemned by his own conscience,
for the mystery of faith is held in a pure conscience,
in which men are justified in the sight of God.
And a man that is condemned in his own conscience, is not justified in the sight of God;
that which condemns is the light, and that is the cause of condemnation,
the bating of it, and not believing of it,
and that is the cause the conscience comes to be seared, whereby comes condemnation;
and that in the Romans, proves no such thing as thou layest down.

[.discourse-part]
P+++.+++ '`That every believer hath not the witness in him.`'

[.discourse-part]
A+++.+++ That is contrary to scripture and the ministers of Christ`'s doctrine, who say,
he that believes hath the witness in himself, (mark, he,) and after he believes,
he comes to be sealed with the spirit of promise,
and can set to his seal that God is true, and comes to believe the record of his son,
which is the spirit that recordeth all things.

[.discourse-part]
P+++.+++ '`That the gospel is not the power of God.`'

[.discourse-part]
A+++.+++ The gospel is the power of God;
in this thou art contrary to the ministers of the gospel, who said,
the gospel was the '`power of God to salvation to every one that
believes,`' and in this thou hast proved thyself to be an unbeliever.

[.discourse-part]
P+++.+++ '`He would make Christ speak blasphemy; leaving out half his words.`'

[.discourse-part]
A+++.+++ That is false: thou couldst not make Christ, the power of God, the light, the life,
the truth, speak blasphemy in leaving out many of his words;
for all blasphemy is out of the truth, and the power of God,
and in the power and life of God there is no blasphemy.

[.discourse-part]
P+++.+++ '`That a man may persecute Christ in the saints, and be a righteous man,
and that the scriptures save instrumentally.`'

[.discourse-part]
A+++.+++ A man cannot persecute the saints, and be in the righteousness of God,
or the righteousness of the law, but they that persecute Christ,
are in their own self-righteousness.
And the scripture saves not instrumentally, but as men are in the faith;
and men know not salvation, but as they are in the life that gave the scriptures forth,
and Christ, the saviour they speak of;
and there is the instrumental saving that the scripture owns,
for Christ asked them that had the scriptures how
they could escape the damnation of hell,
that were out of the life.

[.discourse-part]
P+++.+++ '`They that did not swear broke the law of God and man.`'

[.discourse-part]
A+++.+++ They that swear are not come to Christ the end of the law,
and they are out of Christ`'s doctrine and the apostles`', who said '`swear not at all,
not by heaven, nor by earth, nor any other oath; but let your communication be yea, yea,
nay; nay, lest ye fall into condemnation,
for whatsoever is more than this cometh of evil.`' So all swearers are in the evil,
they are false brethren, they fall into condemnation,
they are out of the doctrine of Christ, and break his command,
and are none of his ministers.

[.discourse-part]
P+++.+++ '`He did believe in a Christ that died at Jerusalem, but not in a Christ within.`'

[.discourse-part]
A+++.+++ He that believes not in a Christ within, doth not believe in a Christ at Jerusalem,
and he that doth not believe in a Christ within, and preach Christ within,
is a reprobate, and out of the apostles`' doctrine, Col.
ii., 2 Cor.
xiii.
and he is not: a true believer of Christ without, who believes not in a Christ within,
but is in the devil`'s belief, and believes as the devil doth.

[.discourse-part]
P+++.+++ '`That if there be one grace within, it is created,
and he believes not in any created thing.`'

[.discourse-part]
A+++.+++ The grace that is within, that establisheth the heart,
is brought by the revelation of Jesus; the loins of the mind being girded up,
it knows the grace by which it is saved, which brings salvation, which is sufficient:
this comes from the Creator; which grace teacheth us, said the saints,
to deny ungodly lusts, and to live soberly.

[.discourse-part]
P+++.+++ '`That light which Christ hath enlightened every man with, is carnal and darkness.`'

[.discourse-part]
A+++.+++ The light which Christ hath enlightened every man that is come into the world with,
was before carnal or darkness was; and believing in it,
it leads every man from darkness and his carnal estate, into unity with God:
for no man sees his carnal estate and darkness, but by the light which makes it manifest.
And the light which lighteth every man that cometh into the world,
is that which all professors that were without life, in all ages stumbled at.

[.discourse-part]
P+++.+++ He knew '`no scripture that the world was in the
heart of man,`' and that it was '`nonsense.`'

[.discourse-part]
A+++.+++ Thou art ignorant of Solomon`'s words, who saith 3 Eccles.
'`hath set the world in their hearts,
that they cannot find the beginning or ending of the work of God.`'
And here thou hast showed thyself of the bottomless pit,
without the beginning or ending of the work of God;
and he is in the nonsense that is not in the beginning or ending of the work of God.

[.discourse-part]
P+++.+++ '`That men cannot be saved that have no other light.`'

[.discourse-part]
A+++.+++ The light which hath enlightened every man that is come into the world,
is the saviour, and no man is condemned, but for not believing in that light,
and no man is saved but who believes in that light.

[.discourse-part]
P+++.+++ '`That there is no perfection attainable in this life.`'

[.discourse-part]
A+++.+++ There is no perfection but in wickedness, in the life of Adam in the transgression,
and there men live in sin, and have it in their body,
and carry a body of sin and transgression, which came by the devil; but Christ,
the second Adam, destroys the devil and his works, and the power of death,
who saves men from sin, and blots out the sin and transgression,
and redeems from the earth; and they who are in Christ, the second Adam,
are in perfection, and in that which is perfect, and makes free from sin,
and the body of it, and death, and him that hath the power of death,
and they come to be perfect as their heavenly Father is perfect.
And the work of the ministers of Christ, was to the perfecting of the saints,
and thou that Most deny perfection, hast denied the ministers of Christ`'s work,
who preach Christ within, and preached every one perfect in him.

[.discourse-part]
P+++.+++ '`That the scripture is the word of God.`'

[.discourse-part]
A+++.+++ The scriptures are the words of God, as you may read, Exod.
Matth.
and Revel.
and Christ is the word of God, in whom the words end, before the words were spoken forth;
and man without the Spirit cannot interpret scriptures.

[.discourse-part]
P+++.+++ '`That the ministers of this nation, are the ministers of Christ and the gospel,
and that it is a sin to despise them.`'

[.discourse-part]
A+++.+++ The ministers of this nation, or any where else,
are not the ministers of Christ and the gospel,
that deny the light that enlightens every man that comes into the world,
and hold up swearing.
Neither are they the men that are to interpret scriptures;
for they cannot see without the light which enlighteneth
every man that cometh into the world,
and which was before the world was made, which is the end of the prophets,
by which the prophets`' words are seen and the end of them.
And so such before mentioned are to be turned from, that turn from the light;
and it is no sin to obey the apostles`' commands, 2. Tim.
iii. to deny them who have come up since the apostles`' decease,
having the form but denying the power.

[.discourse-part]
P+++.+++ '`That they may lawfully take tithes of the people.`'

[.discourse-part]
A+++.+++ And you that take tithes of the people, are of the pope`'s tribe,
got up since the days of the apostles,
who said the priesthood was changed that took the tithes,
the law was changed by which the priesthood was made,
and the commandment disannulled that gave tithes.
And Christ was the sum, the end of all similitudes,
who was before Abraham was that paid tithes, Heb.
7+++.+++ The pope is your author in taking tithes,
in the apostacy since the days of the apostles, and Christ is the end of the law.

[.discourse-part]
P+++.+++ Richard Mayo saith, '`that it is not unlawful to say you to a single person.`'

[.discourse-part]
A+++.+++ In this thou showest thou never read the Accidence or Bible;
and it is unlawful to speak unrighteously,
and do say there are many when there is but one, to call one many, or say you to one.

[.discourse-part]
P+++.+++ '`That ministers may exhort men to walk by the light of reason,
as well as the light of the gospel.`'

[.discourse-part]
A+++.+++ No man walks by the light of reason but he who is in the faith,
who is in the light of the gospel, and all other reason is as the beasts of the field;
that which makes men reasonable, is faith, and all that are in the faith,
are in the light of the gospel, and this is one, which all unreasonableness is out of,
and in the transgression; for none are in the reasonableness,
but such as come out of transgression;
and such as are reasonable walk by the light of the gospel.

[.discourse-part]
P+++.+++ '`That the gospel itself is but a dead letter.`'

[.discourse-part]
A+++.+++ The gospel itself is the power of God, that which the letter speaks of,
and many may have the letter, the form, and deny the power of God,
and so have not the gospel.

[.discourse-part]
P+++.+++ '`That the gospel is no more the power of God,
than the rose cake that lay in his window.`'

[.discourse-part]
A+++.+++ The gospel is the power of God preached in every creature, more than a rose cake;
the gospel gives every creature its living and being; for it relieves the oppressed,
and turns against the oppressor; so it is called glad tidings,
for the gospel is preached unto every creature in heaven.
The gospel is the power of God which turns against that which bondageth, to wit,
the corruptions, and so gives liberty and freedom to the captives; and this,
which is the power of God, is glad tidings, and is more than any creature,
and all the creatures; that which gives liberty and freedom to all, is glad tidings.

Richard Mayo further said,
'`it was no matter to him if the devil was the original of tithes,
if the law of the land would give it him, he would have it.`'

[.discourse-part]
A+++.+++ We do believe thee; his servant thou art,
thy seared conscience and hardness of heart discover it.
But the ministers of Christ and the gospel never preached nor held forth such doctrine,
nor would ever act any thing from that which the devil was the original of,
and thou dost say thou wouldst take tithes though he was the original of them,
if the law of the land would give them to thee!
He hath been the original of them, and the pope`'s laws first set them up,
whereby the saints`' goods are strained, and spoiled, and made havock of;
and you are not contented with the spoiling of their goods,
but you bring their bodies into your priests`' den; and thus you eat up people,
and swallow up the needy for a thing of nought, as they did of old,
as your forefathers did transgress for a pair of shoes.

[.discourse-part]
P+++.+++ He saith, '`Cain was no vagabond after he had built a city,`' and he said,
'`there was no scripture that the apostles had no certain dwelling
place;`' and that '`the steeple-house was the church.`'

[.discourse-part]
A+++.+++ This is contrary to scripture; for Cain, though he builded a city, was a vagabond,
and disobeyed the command of God, and lost his habitation in God;
so all great men upon the earth, though they build a city, and are lords, and earls,
and dukes, and princes, and kings, if they disobey the command of God,
and do not dwell in him, they have no habitation, but are all vagabonds.
And though Paul had no certain dwelling place, 1 Cor. 4:11.
yet he had a habitation in God, and was no vagabond.
And the steeple-house is no church, but the old mass-house,
set up since the days of the apostles, since they lost the true church, Thess. 1.
