[#ch-81.style-blurb, short="Seth Bushel"]
== Priest Bushel`'s principles. These words were given forth by Seth Bushel, priest of Whitley, as follows, the 25th day of the first month, 1658.

[.discourse-part]
_Principle._ '`Men are not converted by the light within them`"

[.discourse-part]
_Answer._ If Christ be not in you, the body is dead, and he is light within.
And the light that shines in the heart gives '`the light of the knowledge of the glory
of God in the face of Christ Jesus.`' And none are converted but they that are in him,
and they are converted by him within; and the light that shines in the heart,
gives the knowledge of conversion and unconversion;
and there are none come to conversion but by it, the light, which is Christ.

[.discourse-part]
_Principle._ He saith,
'`that he denies that the light that lighteth every man is Christ,`' as John speaks,
John 1.

[.discourse-part]
_Answer._ In this thou hast denied John`'s doctrine, who said,
'`He is the true light which doth enlighten every man that
cometh into the world.`' '`And as many as received him,
he gave them power to become the sons of God.`' And thus thou art ignorant of the scriptures,
much more of the power of God.

[.discourse-part]
_Principle._ He saith, '`The light which every man is enlightened withal,
never converted any man to God.`'

[.discourse-part]
_Answer._ Here thou goest about in thy doctrine to prove that Christ never brought any to God,
who is the light '`that lighteth every man that cometh
into the world,`' who is the way to the Father,
who saves men from sin, and destroys death, and he that hath the power of it,
and brings men into that which the devil is out of.
Thou and thy doctrines are comprehended and condemned by the light;
and no man is converted to God but by the light '`which
hath enlightened every man that cometh into the world.`'

[.discourse-part]
_Principle._ He saith, '`That the light which lighteth every man is the broad way.`'

[.discourse-part]
_Answer._ Here people may all see this priest to be a minister of darkness and wickedness;
for the light which doth enlighten every man is Christ Jesus,
who is the way to the Father, and leads people out of the broad way,
which is come up by Adam, sin, the devil, and transgression;
and all are in the broad way that deny the light.
