[#ch-82.style-blurb, short="Edward Price and Philip Langford"]
== Hereford, the 8th day of the first month, 1658, these words were spoken in a meeting by Edward Price and Philip Langford, which are their principles.

[.discourse-part]
_Principle._ Philip Langford said, '`Paul was not freed from the act of sin whilst in this life.`'

[.discourse-part]
_Answer._ Paul thanks God he was made free from the body of sin,
and saw there was no condemnation; and thus he wrestles and fights against Paul,
who said he was made free from sin, and could live no longer therein;
and the body of sin was put off; and his conversation was in heaven.

[.discourse-part]
_Principle._ '`We do affirm, that they that are in this faith that turns from sin,
are subject to sin, the act of sin, whilst in this mortal body.`'

[.discourse-part]
_Answer._ This is confusion and contradiction, and not sound doctrine;
for faith that purifies the heart from sin, gives victory over it,
in which men please God, and have access to him,
by the which they are justified whilst on earth, and by faith the just live;
and the life the saints come to live, which gives them victory over the world,
is by the faith of the son of God.

[.discourse-part]
_Principle._ Priest Price saith,
'`Faith in Christ Jesus purifies not from the indwellings of sin whilst in this body.`'

[.discourse-part]
_Answer._ In this the scripture hath corrected thee; for it saith,
'`faith purifies the heart;`' that which purifies, takes away sin, which,
being unclean in itself, makes unclean.

[.discourse-part]
_Principle._ He saith, '`The guilt of sin may be taken away, but the act of sin may remain.`'

[.discourse-part]
_Answer._ A silly man!
One of the old doctors the scriptures speak of.
Dost thou act sin, and dost not thou feel the guilt of it?
Thou bringest the whole world upon thy head,
the principle of God in them all will witness against thee.
And ask all the thieves that are condemned to the gallows, and the drunkards,
and such as act sin, such as profess scriptures, which are not in the life of it,
whether or not they have not a guilt upon them for acting sin.
But this is one of the blind priests`' principles; none but mad men will believe them;
wicked liars against that of God in their own conscience!
And thus they preach up the devil`'s doctrine of lies.

[.discourse-part]
_Principle._ Edward Price saith, '`that all men should be judged by the scriptures,
and that the scriptures are the power of God.`'

[.discourse-part]
_Answer._ The scripture saith, '`Christ is the power of God;`' and the apostle said,
'`The letter kills;`' and '`all judgment is committed
to the son,`' say the ministers of Christ.
And the scriptures are the words of God, and Christ is the word, and judge,
in whom the words end, whom thou hast thrown out, and set scripture in his room:
and as for the rest of his words, they are not worth mentioning.
