[.style-blurb, short="Thomas Hodges"]
== Thomas Hodges, rector in Oxfordshire, bachelor in divinity, saith,

[.discourse-part]
_Principle._ '`That the holy ghost speaks in the scriptures.`'

[.discourse-part]
_Answer._ Here all may see his ignorance,
whether this man be fit to be a rector who is thus corrected with the scriptures,
which say, that the holy ghost moved in them that gave forth scriptures; but said,
'`the letter was dead, and did not give life.`' And thus he directs into darkness,
in telling the people the holy ghost is in scripture,
when the scripture never gave forth that speech,
but said it was in them that gave it forth; for many may have the scriptures,
and want the holy ghost, as the Pharisees.

[.discourse-part]
_Principle._ '`To the law and to the testimony;
and thou shalt not make to thy self any graven image that is in heaven or in earth.`'

[.discourse-part]
_Answer._ I say, to the law and to the testimony, before Matthew, Mark, Luke, and John,
Epistles, and the Revelations were written.
'`The law is light,`' '`the testimony of Jesus the
spirit of prophecy,`' as in former days,
Isaiah the 8. And you have told the people that it is the Old and New Testament;
but the New was not written in his days, in the days of Isaiah.
And why do you make likenesses of things in heaven and in earth,
and hang up in your houses, and on signs, yet thou sayst we should not make them,
for it is a breach of God`'s command:
of whom have you learned to make all these images of things in heaven,
and things in the earth, since the days of the apostles,
but of them that went forth from the apostles, the pope`'s tribe; of whom ye are.
