[#ch-85.style-blurb, short="Richard Heath"]
== Richard Heath, Priest in Shrewsbury. His Principles as follows.

[.discourse-part]
P+++.+++ '`That drawing people to a light within them, you draw them from God to themselves,
from the instruction of the spirit.`'

[.discourse-part]
A+++.+++ Here thou art a minister unlike to the apostle,
who brought people to a light within them, Cor.
ii. 4. and told them,
'`that the light that shined in their hearts would give them the
light of the knowledge of the glory of God in the face of Jesus
Christ.`' And so none come to the knowledge of the spirit,
but such as come to the light within,
(and from themselves,) though they have the scriptures as the Jews had.

[.discourse-part]
P+++.+++ '`If we ministers should send people from all other lights to the light within them,
we should then turn them from light to darkness, from God to the power of Satan.`'

[.discourse-part]
A+++.+++ None come to God, but they who come to the light within,
from the power of Satan and darkness; and God will dwell in them, and walk in them,
and make his abode in them, who is light, and the end of all other lights,
before they were.
And ye that turn people from the light, turn people into darkness, the power of Satan,
and there keep people under his dominion,
from the light Christ Jesus that hath enlightened every man that cometh into the world,
with which they might see their saviour.
