[#ch-86.style-blurb, short="Daniel Gaudry"]
== Daniel Gaudry, Priest of great Billing in Northamptonshire. His Principles follow.

[.discourse-part]
_Principle._ '`That the saints are partly sinful, and failing in their best works,
and subject to continual lustings one against another.`'

[.discourse-part]
_Answer._ The life of the saints is Christ, not sinful at all;
and they are ceased from their own works, and are true believers.
And the works of faith are not sinful, nor the works of the spirit,
by which the saints are led; and they come into Christ in whom they have peace,
and do not lust one against another, but live in the spirit in which there is unity,
in which is the bond of peace;
and the lusting one against another is in the transgression against the spirit of God.
So they who are in Christ, are in peace; and they who are in the world are in trouble,
in wars; but they who are in Christ, are in him who was before wars were,
inward or outward, of whom thou art ignorant.

[.discourse-part]
_Principle._ '`The blood of Christ cleanseth from all sin, from the guilt of it,
instantly and perfectly; from the stain and power of it, gradually.`'

[.discourse-part]
_Answer._ Where sin is, there the guilt of it is felt at that instant;
but whoever feels the sin, shall feel the guilt of it.
And the blood of the seed cleanseth, it makes free from that which the law takes hold of;
and the blood of the seed cleanseth from sin, from the power and stain of it,
and then the guilt of it is gone;
the seed destroys death and him that hath the power of it, which is the devil;
and where this is known the fulness is known which is above degrees,
that which degrees end in.

[.discourse-part]
_Principle._ '`It is the tang of popery, that a man may fall from saving grace.`'

[.discourse-part]
_Answer._ '`The grace of God that has appeared to all men, which brings salvation,`' is saving,
and such thou and many papists turns into lasciviousness and wantonness.
That which brings salvation is saving.
So you are turned to be murderers of one another about scriptures,
which was not the practice of them who lived soberly, righteously, and godly,
who denied the worldly lusts and ungodliness,
but their hearts were established in grace which was their teacher;
but you and papists that live wildly, and ungodly, and unrighteously,
in the lusts of the world, that are fallen from the saving grace, your fruits,
your actions daily declare and show it; and so you are talkers of grace,
which is turned into wantonness both among you and the papists;
your unseasoned hearts and words make it appear.

[.discourse-part]
_Principle._ '`We shall not see Christ as he is till he comes to judgment,
then and not before we shall see him.`' And then he adds,
'`Every man that hath this hope purifies himself,
which also argues that he is not pure and perfect, but only in hope.`'

[.discourse-part]
_Answer._ You, where you are, see him not, nor know him as he is, we do believe you;
but the saints, the true church whom he is the head of, whom he is in the midst of,
and in whom he is.
And Christ told his disciples, they had known him; they knew the son, and had the son,
and they had the Father also; and he that had not, had not life.
And they had handled and seen.
And hope in itself is pure, and that is it which purifies man, and makes him pure,
as God is pure.
The hope now is pure in itself, a distinct thing,
and that is to make man pure as God is pure.

[.discourse-part]
_Principle._ '`God may justly require his due of man, though man cannot give it.`'

[.discourse-part]
_Answer._ God requires no more of man than he gives.

[.discourse-part]
_Principle._ '`That the Quakers send men to the light within them to be perfected,
which is no better than darkness.`'

[.discourse-part]
_Answer._ Thou that sendest men to any thing, but not to the light within them,
thou keepest them out from perfection in utter darkness;
and none come out of utter darkness to perfection, but by the light within them;
and so growing up in the light, they grow up in that which is perfect,
and so in the fulness which is Christ, which is the perfection of God.

[.discourse-part]
_Principle._
'`Christ saves his people from the guilt of their sins here in the state of justification:
the state of the best saints here, is imperfect.`'

[.discourse-part]
_Answer._ Who are justified are saved from the guilt of sin; and who commit sin feel the guilt,
and cannot say they are justified in the committing of it; for he that saves, sanctifies,
redeems, and destroys the devil and his works, and death, where he hath power,
where he keeps up his authority.
And if the best saints here are imperfect,
then they are not brought out of Adam`'s state in the transgression;
for a saint is one that is sanctified, and one that is redeemed,
and one that comes to know the works of the devil destroyed, and that is washed,
and cleansed, and sanctified through the name of the Lord;
and that which justifieth takes away both sin and its guilt; for, as it is written,
'`he shall save his people from their sins,`' and from the guilt,
and from the wretched state.

[.discourse-part]
_Principle._ '`Surely they cannot be perfect here or hereafter in equality, but only in quality.`'

[.discourse-part]
_Answer._ Christ makes no distinction in his words, but saith, '`Be ye perfect,
even as your heavenly Father is,
and be ye merciful as he is;`' and '`as he is so
are we.`' And that which is perfect and merciful,
as he is perfect and merciful,
is in equality with the same thing which is of God and from him.

[.discourse-part]
_Principle._ '`The saints were come to the spirits of just men made perfect, but not on earth.`'

[.discourse-part]
_Answer._ The just men`'s spirits that led them to give forth scriptures was the spirit of God,
and that was perfect;
and was that which while they were upon earth the saints were come to,
which was Christ the end of all words, and so to God, the Judge of all the earth.
