[#ch-87.style-blurb, short="The Quakers`' Rounds"]
== Philip Taverner, called Preacher of the Word, in his book called '`The Quakers`' Rounds.`' These are his Principles.

[.discourse-part]
P+++.+++ '`We distinguish between the essential word, and the declarative word;
we own Christ to be the essential, and the scripture to be the letter.`'

[.discourse-part]
A+++.+++ The scripture tells us that Christ is the word;
the scriptures of truth that were given forth from the spirit of truth,
were the words of God, in whom they end, in Christ the word.
And you talk of a declarative word, and the scripture you call a history;
and you call it a creed, and you call it a catalogue;
and these titles and names you have given to the scripture of truth, the words of God;
as I said before, the scriptures of truth are the words of God,
given forth from the spirit of God, which end in Christ;
and they do not speak of a declarative word, but you in your nicety.

[.discourse-part]
P+++.+++ '`There is a two-fold coming of the gospel, the one in word, the other in power.`'

[.discourse-part]
A+++.+++ The blind people thou wouldest here make believe that the word was not the power,
which word and power are one, for Christ is the word, and Christ is the power of God;
his name is called the power of God, and he that ministers the word,
ministers the power of God, and the gospel.

[.discourse-part]
P+++.+++ '`The saints that stood upon mount Zion, that followed the Lamb,
those saints that were without guile before the throne of God,
are to be understood in the justification and not in sanctification,
that are spoken of in the Revelations.`'

[.discourse-part]
A+++.+++ Here thou hast manifested thyself to be an accuser of the brethren who are justified,
and said to be without fault.
Now they who are justified, are sanctified and justified; it was said,
in their mouths was no guile; they were not defiled; and now these that have no guile,
and are justified, and were not defiled with women, such are sanctified.
So that thou judgest of things that are too mighty for thee;
and meddlest with things that are too weighty, and bringest judgment upon thy own head;
whose measure is measured, and weights are tried;
and thou art of them that are found too light.

[.discourse-part]
P+++.+++ '`He that is born of God sins not after the same sort as them that are of the devil.`'

[.discourse-part]
A+++.+++ He that commits sin is the servant of sin, and he that commits sin is of the devil;
and he that is born of God doth not commit sin, for he cannot, because he is born of God,
born of that nature which cannot sin: and those who sin are of the devil,
of the same nature of their father;
but he that is born of God doth commit sin at no rate,
for he is of the same nature of his Father.

[.discourse-part]
P+++.+++ '`As John saith: as he is, so are we in this present world, that scripture, saith he,
cannot be so in the latitude of it.`'

[.discourse-part]
A+++.+++ I believe you; for from the men of your generation, it was not given forth:
but they that are the sons of God understand it as it is, and believe it as it speaks.

[.discourse-part]
P+++.+++ '`Christ was holy from his conception, so are not we,`' saith he,
'`but we are sanctified in time.
Christ was holy, and so are not we, for there still remains the indwelling of sin in us.`'

[.discourse-part]
A+++.+++ And some were sanctified from the womb,
and some children were holy that were born of the believers.
Christ in the male and in the female, is as he was in his eternal generation;
and is the same, and remains; and is the sanctification,
and he sanctifies the unsanctified sons of Adam in the transgression,
and Christ changeth them, and makes them like himself;
and they who have sanctification without and not within, are hypocrites.

[.discourse-part]
P+++.+++ '`That the saints are complete in point of justification, and not in sanctification.`'

[.discourse-part]
A+++.+++ They that are not complete in sanctification, are not complete in justification,
for they are one; they that are complete in the one, are complete in the other;
and so far as a man is sanctified, so far is he justified, and no farther;
for the same that sanctifies a man justifies him;
for the same that is his sanctification, is his justification, and his wisdom,
and his redemption.
He that knows one of them, knows all: he that doth not feel one of them,
feels none of them at all, for they are all one.

[.discourse-part]
P+++.+++ '`Faith justifies only instrumentally;
neither doth it justify instrumentally as a work wrought in us by the spirit.`'

[.discourse-part]
A+++.+++ The man is blind; he is angry there,
and fretting himself about things that are too weighty for him,
about things that he knows not; for faith is the gift of God which purifies the heart,
which brings people to have access to God: in that, and by that which purifies men,
men are justified, and in that is virtue; by the hearing of that, men receive the spirit.
So that this is confusion, and contrary to the scripture, and confuted by it;
for ye are justified through faith, and by the spirit, in which men please God,
and without which they cannot; therefore that is instrumental.
And in that they have victory, and in that they have unity one with another,
and in it have access to God.
But saith he,
'`faith doth not justify instrumentally by any virtue that is in
it any more than is in love.`' Love and faith are one,
without faith there is not love: love is the fruit of faith, flows from it,
without it there is no unity, and without faith there is no victory,
and without victory there is no love; and it justifies, and is wrought by the spirit.

[.discourse-part]
P+++.+++ '`A perfect conformity to the law of God written, in the strength and power of grace,
the spirit working all in us and for us;
all this is no more than the righteousness of the law.`'

[.discourse-part]
A+++.+++ That is the end of the law that brings to the righteousness of the law,
and to a perfect conformity to it, and fulfils it; that is the seed,
Christ in the male and in the female, by whom grace comes, by Jesus Christ,
which brings to live in the righteousness of it, which is the righteousness of faith,
by which the spirit is received, which works all in people, and for them,
and which ends the law.
