[#ch-88.style-blurb, short="The Brownists`' Principles"]
== The Brownists`' Principles.

[.discourse-part]
P+++.+++ '`They never heard God`'s voice from heaven, nor saw his shape:`' and yet they affirm,
'`they have the same power and spirit that the apostles had,
though much below;`' and that '`they have the word abiding in them.`'

[.discourse-part]
A+++.+++ You that never heard the voice of God, nor saw his shape,
have not seen him who is a spirit, nor have you his power, nor his word abiding in you;
for they who have the spirit of God, and the power of God,
and the word of God abiding in them; with the spirit of God, with the power of God,
see God`'s shape; and they who have God`'s word abiding in them, hear the voice of God;
for God is the word, and God will dwell in them, and walk in them.

[.discourse-part]
P+++.+++ '`That they are brought to the church that is in God, the pillar and ground of truth,
where there is neither spot nor wrinkle, nor any such thing.`'

[.discourse-part]
A+++.+++ And yet you never heard the voice of God!
And how can you be brought to the church that is in God, and never heard the voice of God?
For none come to the son but through the drawings of the Father;
and none know the drawings of the Father, but they who hear his voice.
The Jews that came not to the son, Christ told them, they had not known the voice of God;
and none come to him, but who the Father draweth.

[.discourse-part]
P+++.+++ '`We do not look for any such thing as revelation from heaven,
or speaking as they are moved, or waiting for the power, as the apostles did;
we say we do not look for any such thing.`'

[.discourse-part]
A+++.+++ This shows that you have not received the grace, for the grace comes by revelation;
and that you have not received the son, for the son comes by revelation;
nor have you known the Father whom the son reveals;
you are not come to the holy ghost whom the saints witnessed,
that led them to speak forth scriptures,
for no prophecy of the scriptures came by the will of man.
So you are among those men that have the scriptures in their wills,
and want the thing that the scriptures were given forth by, that is, the holy ghost;
for holy men of God were moved to speak them forth,
who learned them of God and spake them forth as the spirit gave them utterance.
Therefore, how can ye say, that you are come to the church in God,
and wait neither for the power nor revelation as the saints did, and were in?
For if you have all the scriptures, and have not that, you have not revelation,
and have not the holy ghost; for the scriptures, are not known but by revelation,
and they are revealed by the spirit that gave them forth:
and though men have all the scriptures,
yet the son is not known but by revelation of the Father.

[.discourse-part]
P+++.+++ '`The scripture is the gospel, the scripture is the light, the scripture is the word.`'

[.discourse-part]
A+++.+++ The scriptures are the words of God given forth from the spirit of God,
learned from him: the gospel is the power of God, the scripture declares it.
A man may have the form and deny the power, and so deny the gospel.
Christ is the light of the world, the life and the light of men,
by whom the world was made; and many have the scriptures, but deny the light,
the life and power of it, Christ Jesus, who is the life, and power,
and authority of them.

[.discourse-part]
P+++.+++ '`That they knew no law of God against praying and preaching by an hour-glass;
and that the apostles did perform the ordinances of God at set times;
and Daniel and David prayed customarily, and how this can be said to be will-worship,
and to be seen of men, we shall leave it to the Lord.`'

[.discourse-part]
A+++.+++ The Lord judgeth it to be will-worship,
that which limits the holy one to an hour-glass;
and the spirit of the Lord that taught the saints to pray,
never limited itself to an hour-glass.
So you by an hourglass pray and preach as the Papists with their beads,
so that which limits the Lord to a set time,
are traditions and vain customs of the heathen, and traditions of men,
which always limited the spirit; which spirit gave freedom to the Just in every one,
who said, quench it not, nor limit it;
but knocked down vain customs and traditions of men,
which were set up by men who had quenched the spirit in themselves,
and would limit the Holy One in others.
And such were always judged of the Lord, and by them that had his spirit,
to be idolaters, and in the will-worship, and not in the spirit,
which are got up since the days of the apostles.
