[#ch-90.style-blurb, short="The Ranter`'s Principles"]
== The Ranters`' Principles.

[.discourse-part]
P+++.+++ '`Christ without comes to destroy Christ within.`'

[.discourse-part]
A+++.+++ Christ is but one, and it is the devil that he destroys and his works,
the antichrist and not the true Christ, who is the true seed in male and female;
and it is the false Christ he destroys in the male and female,
and he comes to end the types and figures and shadows that people might live in him,
the end of the types, and figures, and shadows, the substance.

[.discourse-part]
P+++.+++ '`And the woman that Paul speaks of that is forbidden to speak in the church,
but must learn of her husband at home,
is the whore that drinks the blood of the saints in Revelations.`'

[.discourse-part]
A+++.+++ That is false; for the woman the apostle speaks of there, that must learn in silence,
and must be in subjection, and ask her husband at home, is in the state of Eve,
who must not teach, but learn in silence, as also said the law,
for she was first found in the transgression.
Now the woman here hath a husband to ask at home,
and she is not to usurp authority over the man; but Christ in the male as in the female,
who redeems from under the law, and makes free from the law, may speak,
Christ in the male and female who are in the spirit of God, who are not under the law.
But the whore who drinks the blood of the saints, is gone from her husband,
from under the law, to ask the whoremaster, that doth drink the blood of the saints,
which Christ the seed judgeth, upon whom he gives judgment.

[.discourse-part]
P+++.+++ '`And the outward creatures which God hath made and created, and blessed,
are the serpent`'s meat,`' as the old Ranter of Bristow,
when he was gnawing a piece of plum pudding, said he was eating the serpent`'s meat.

[.discourse-part]
A+++.+++ The serpent`'s meat is dust, and he goes on his belly,
and so he hath proved himself to be a serpent, who eats his meat;
which the children of God, the seed, do not; and Christ who ate of the bread,
did not eat the serpent`'s meat, he did not call it serpent`'s meat,
and that which doth so is cursed and judged.
