[.style-blurb, short="The Fulness and Freenes of God`'s Grace"]
== Francis Duke`'s Book, entitled, [.book-title]#The Fulness and Freeness of God`'s Grace.# His Principles are as follow.

[.discourse-part]
_Principle._ '`God made man perfection of parts in this life, but not perfection in degrees.`'

[.discourse-part]
_Answer._ Perfection of parts is perfection of degrees;
for where there is a part there is a degree,
so in this thou meddlest with things that are too heavy for thee.

[.discourse-part]
_Principle._ '`That God did elect that drop of human seed to be personal God-man, as the text is;
the seed of the woman shall bruise the serpents`' head.`'

[.discourse-part]
_Answer._ The elect is Christ, the seed; Christ the second Adam, is not human,
for human is earthly, so thou errs in thy judgment, for as Christ the seed says,
'`he that is born of the flesh, is flesh,
and he that is born of the spirit is spirit,`' and the election obtains it,
and he that is of the earth is earthly, but he that is from above, is heavenly.

[.discourse-part]
_Principle._ '`Men may obey imperfectly, but truly.`'

[.discourse-part]
_Answer._ Truth is perfect; Christ who is perfect, is truth, and they that obey truly,
obey perfectly, for perfect obedience, and true obedience are one.

[.discourse-part]
_Principle._ '`The seed of the serpent and the devil`'s seed
remains in the best of men in this life,
for without this seed of the devil issuing in human nature,
it is not capable of eternal life.`'

[.discourse-part]
_Answer._ This seed of the devil hinders men from being capable of eternal life,
and such as were sanctified from the womb, were capable of eternal life;
and such as were made free from sin and the body of death and sin put out of them,
could not sin, because the seed of God remained in them, and Christ in them,
who witnessed redemption, and the works of the devil destroyed,
and Christ manifested in their flesh, who condemned sin in their flesh,
the body being dead because of sin.
They who were born of God, did not commit sin, they were passed from death to life;
for sin brought death, and the devil, which went out of the truth, had the power of it,
but the seed hath destroyed death, and him that hath the power of it, which is the devil.
And God, the God of all peace, hath bruised Satan under the saints`' feet;
such are a-top of the seed of the devil, and they are capable of eternal life,
and tell thee thy doctrine is a lie.

[.discourse-part]
_Principle._ '`Man may believe truly, but never rightly.`'

[.discourse-part]
_Answer._ He that believeth truly, and is in the true belief, believes rightly;
and he that believes truly is born of God, and he whose belief is false,
is not born of God, it is as his belief that is out of the truth, which is not right,
and the true belief in truth is over him, in that the devil is out of,
and all his generation that stand in an outward belief.

[.discourse-part]
_Principle._ '`The will of man remains in good men and bad men in heaven, and in hell,
and on earth.`'

[.discourse-part]
_Answer._ No prophecy of the scriptures came by the earthly will of man,
but man`'s will must be subdued, and denied with the cross and power of God,
whereby he that doth the will of God abides forever;
but he that doth his own will abides not ever,
and flesh and blood enter not into the kingdom of God, and they that go down into hell,
go down in their own wills and willfulness,
but man must be born again before he can enter into God`'s kingdom;
he that is born of the flesh is flesh,
and will persecute him that is born after the spirit, for there are the two wills,
and earth is their footstool.

[.discourse-part]
_Principle._ '`The saints affirm themselves that they are all unclean things,
and their righteousness as filthy rags.`'

[.discourse-part]
_Answer._ The saints are clean, and are sanctified, and are washed, and are cleansed.
'`Now are you clean,`' saith the Lord; ye were such, and such;
and the saints`' righteousness is Christ, such as never will grow ragged,
which was before the world was made, which was before rags, and ragged righteousness was;
this is the saints`' and true believers`' righteousness,
and the saints are not unclean things, for it is the unsanctified that are unclean.

[.discourse-part]
_Principle._ '`The saints have a twofold righteousness in this world.`'

[.discourse-part]
_Answer._ The righteousness of the saints is one in Christ, and is one in God,
from whence all righteousness comes,
and the true believers`' righteousness is Christ Jesus, the end of the law.

[.discourse-part]
_Principle._ Thou sayst that,
'`James envies those that brag of their faith without works,`' and sayst,
'`the Lord attributes that to the eye, which is not proper,
the eye is the light of the body,
but yet the eye hath no light in itself to enlighten the body;
so he attributes that to the eye which is proper to the light.`'

[.discourse-part]
_Answer._ James did not envy, for envy was of Cain, and of the devil, and of the wicked one,
he did not envy them whose faith was dead without works.
And Christ`'s speech was proper, who said the light of the body was the eye,
and without the eye the body hath not light; look at it, either inward or outward;
it is proper within, and proper without, for when the eye is blinded within,
the body is full of darkness; when the eye is blinded without, the body is dark,
and it wants the light; and the light of the body is the eye, that being single,
the body is full of light, and that is perfect.

[.discourse-part]
_Principle._ '`That God redeems his church with his blood, yet bleeds not.`'

[.discourse-part]
_Answer._ Here again thou cavillest with the apostle`'s words,
and art a perverter of the scriptures, who art corrected by them;
the apostle speaks of the blood of God, and the blood shed,
and the conscience sprinkled with the blood.

[.discourse-part]
_Principle._ '`Justifying faith, simply considered in itself, as to justification of a sinner,
is but a dark body till it hath received Christ, and his righteousness.`'

[.discourse-part]
_Answer._ Where justification and justifying faith are,
there Christ and his righteousness are felt, for he is the justification;
and this is not a dark body, neither justifying faith, nor justification of a sinner,
but thou art the dark body, that hast so judged, for it is all one.

[.discourse-part]
_Principle._ '`It is but perfection of parts, not of degrees, that people attain to:
beware you dream not that you attain to perfection of degrees, as the Quakers do,
for when you so think of yourselves, that is the hour and power of darkness,
and you fall into temptations and abominations.`'

[.discourse-part]
_Answer._ Where perfection is in parts, there are degrees,
and that which is perfect keeps out of darkness, out of the temptation and abomination;
he that speaks of perfection of parts, and not of degrees,
doth not know what he speaks of, but is in a dream,
and in the hour of temptation and the power of darkness,
and in the temptation and abomination, and doth not know what he Speaks of;
for perfection of parts is perfection of degrees.

[.discourse-part]
_Principle._ '`The saints`' inherent righteousness, is but imperfection of parts, as filthy rags.`'

[.discourse-part]
_Answer._ Where dost thou read of the word inherent righteousness?
But the righteousness of Christ wrought in us, is not filthy rags,
but that which thou pretends to work in thyself, by dreaming imaginations,
is filthy rags, and not the true righteousness of Christ, which is without rags;
but where dost thou read of inherent righteousness, but of thy father the Pope?

[.discourse-part]
_Principle._ '`Job had too high esteem of his uprightness wrought by the spirit of Christ in him,
who also assisted him to perfect patience.`'

[.discourse-part]
_Answer._ A man cannot have too high an esteem of uprightness,
wrought by the spirit of Christ in him, which will assist to perfect patience;
and thus thou confoundest thyself.

[.discourse-part]
_Principle._ '`If Job had hanged himself, he might have said in this case,
it is not I but my deep distemper which strangled me.`'

[.discourse-part]
_Answer._ Thou wicked liar, of thy father the devil, the murderer,
had Job consented to the wicked one with his mind to have done this thing,
then it had been Job; and this is not comparable to Paul`'s state, he saith,
it was no more he, but sin that dwelt in him, who did not consent with his mind.
So thou art no true measurer, but a false measurer,
to say it had been the infirmity of the members, but not Job;
yet there is the eye which was before the word Job was, which the devil hath nought in;
so both thou and thy measure are judged according
to scriptures which came not by the will of man,
which are of no private interpretation.

[.discourse-part]
_Principle._ '`That the written scripture is a more sure word of prophecy,
than the excellent speech from heaven to Jesus upon the Mount,
as your Quaking doctrines teach, which are bottomed upon the light within,
which what it is, neither you nor any man else know.`'

[.discourse-part]
_Answer._ The voice that spake upon the Mount, and the excellent speech were the same,
and was to them that gave forth the scriptures.
Now, the written scriptures many may have, and deny the spirit of prophecy,
and know not the light shining in the dark place, until the day dawn,
and the daystar arise in their hearts; which is the Quakers`' light within,
which thou sayst neither thou nor any man else knows what it is;
then why do you judge of things you do not know?
We do believe that your darkness cannot comprehend it, though it shineth in the darkness;
but where light hath shined out of darkness and shines in the heart,
it gives the light of the knowledge of the glory of God in the face of Christ Jesus.
And all that are in the light, and walk in it, have fellowship one with another,
and know what light is, and come to the life Christ, from whence the light comes,
which you nor no man can know what it is, who are ravened from the spirit of God,
and so know not Christ the light.

[.discourse-part]
_Principle._ '`The scripture is the ground of faith.`'

[.discourse-part]
_Answer._ The ground of faith was before scripture was written.
God and Christ Jesus were the givers of faith, and the authors of it; as Abel, Enoch,
and Abraham had faith before that which you call your ground of faith was written.
But I say the scripture is able to make wise to salvation through faith in Christ Jesus,
who is the author of it; thou goest abut to lay another ground than God and Christ Jesus,
that gave forth to them that spoke forth the scriptures of truth.

[.discourse-part]
_Principle._ '`You call a light within, and tell us it is God`'s word,
and call the thing everlasting word, and spiritual king, and Christ,
and this lie is the ground of your faith.`'

[.discourse-part]
_Answer._ The word is light, and Christ is light, and the everlasting word, and king;
and he rules the hearts of the saints, and is in the midst of his church,
and dwells in his people, and he makes his abode in them, and all that are not in this,
are in the lie, and are not on the true foundation, Jesus Christ.

[.discourse-part]
_Principle._ When Christ told the devil, that man should not live by bread alone,
but by every word that proceedeth out of the mouth of God,
that was believing the scriptures; and this, the word of God in the scriptures,
was the ground of Christ`'s faith, and so to all that were his.`'

[.discourse-part]
_Answer._ Many may have the scriptures, and never hear the voice of God, as the Jews,
in the fifth of John; they said they believed the scriptures,
though they were out of the true belief: but receiving the word from God,
as they did that gave forth the scriptures, is that which man lives by,
and not by bread alone, and so knows him which was before scripture was given forth.
And as for saying that the scripture is the ground of Christ`'s faith,
he was before the scripture was written, and fulfils their words,
and is the author and finisher of the saints`' faith,
which was before the scripture was given forth;
he by whom the world was made is the author of the saints`' faith,
that bruised the serpent`'s head under his feet, before scripture was.

[.discourse-part]
_Principle._ '`For the Lord Jesus Christ himself, who was personally God-man,
simply created nothing, yet you would have your light, called Christ, to be a creator.`'

[.discourse-part]
_Answer._ God was in Christ, and they are one, the creator, the Father in the son,
and the son in the Father, and Christ in you, and God in Christ, the creator,
the maker of all things.
And God will dwell in the saints as the creator; he creates in them right minds,
new hearts, new spirits; gives them understanding and knowledge, to know him,
which is eternal life and wisdom; to walk in his ways which are perfect;
where God`'s dwelling is in saints, there is light,
and they have fellowship one with another in it, and with the son and the Father.

[.discourse-part]
_Principle._ '`That although the essence of God be within,
yet it no way conducts to the happiness of man.`'

[.discourse-part]
_Answer._ Man feels not the happiness but as he is in the power of God,
in which he has communion with him, and thou speaks thou dost not know what.

[.discourse-part]
_Principle._ '`John said he had heard and handled Christ, and looked upon him,
but your idol Christ, your light and everlasting word, you say is within,
so that neither you nor any man else can say what it is, except by whimsies.`'

[.discourse-part]
_Answer._ Thou that hast not handled, seen, nor heard Christ, nor felt him within,
art in the idol`'s whimsies and blasphemy; for we witness that Christ,
and have handled him, and seen him, and heard him, and know the everlasting word,
and him within, which torments thee and thy ground, and thy seed, because he cannot,
reign; but Christ is come to take possession, to destroy him and his works, and reign;
and none see this, but they that own the light within, which comes from Christ the king.

[.discourse-part]
_Principle._ '`By letters and witness without, we will oppose your lying light within,
there to maintain, against the best men whatsoever, your light within is a lie,
for you say the light within is Christ.
I deny the scriptures bear witness to your light within, which is your idol,
and this word of God within to be no more nor less than a lie.`'

[.discourse-part]
_Answer._ The scripture bears witness to the light within, for I know that is thy work,
and the devil`'s, who is out of the light and the truth, to oppose it,
who rules in the children of disobedience, but cannot rule in the children of light.
And the scripture saith, Christ in you, and God will dwell in you;
he is light and they are light, '`the light that shines in your hearts,
to give you the light of the knowledge of the glory of God in the
face of Christ Jesus;`' and this the scripture bears witness to,
as in Cor. ii. 4. 13. And '`the word is nigh thee, in thy heart, and in thy mouth,`' Rom. 10.
And as for all the rest of thy stuff and confused parcel of ignorance in thy hook,
as this before mentioned, it is not worth setting pen to paper;
but for the sake of the simple ones it is given forth:
for the day has appeared that all your works are seen and come to the light.
Praises and glory to the Lord God in the highest, forever.
In the day of thy fulness thou hast been in the mischief of iniquity,
but in the day of thy poverty, when the witness of God stirs and rises in thee,
and judgment enters upon thee, then remember,
when thy works burn and thou art in the fire, what thou didst in the world,
in thy lifetime, against the saints and the elect,
and spoke of things thou couldst not know nor weigh, but which were too heavy for thee;
and how thou actedst against the light of Christ within,
which would have led thee to salvation.
