[#ch-92.style-blurb, short="The Doctrine of the Light Within"]
== Enoch Howet of Lincoln. His principles as followeth, in his book which he calls, [.book-title]#The Doctrine of the Light Within.#

[.discourse-part]
_Principle._ '`I have taken upon me as my duty, to forewarn all men of their doctrine,
that teach men to look at the light within them.`'

[.discourse-part]
_Answer._ We do believe thee; here thou art not only antichrist, but anti-apostle, that is,
against him who taught people to look to the light within them,
and told them that the light shined in their hearts to give them '`the
light of the knowledge of the glory of God in the face of Christ Jesus;`'
and this is the doctrine which thou forewarnest all men of,
and sayst it is thy duty; so thou mayst see who thou servest,
that turnest men from light, and warnest people of the apostles`' doctrines;
so that all may judge what thou turnest them to, and whose duty thou art doing,
and whose messenger and minister thou art: they that are in the fear of God see thee.

[.discourse-part]
_Principle._ '`To look to the light within, is to look at the deceitful heart,
and it will offer thee darkness for light; and it is evident,
if thou look to that which thou callest the light within,
it brings thee to take counsel of a corrupt heart, the prince of the air,
the prince of darkness.`'

[.discourse-part]
_Answer._ The light that shines in the heart, that thy darkness cannot comprehend,
is not the prince of darkness, nor the prince of the air, nor the deceitful,
corrupt heart; but by the light within all is discovered and made manifest,
for it is the light within that discovers a man`'s thoughts,
and the counsels of man`'s heart.
And Christ within is light; and the apostle bid the Corinthians examine themselves,
and prove themselves, and know themselves,
'`how that Jesus Christ was in them except they were
reprobates.`' Now where Christ is within,
there is light.
Now reprobates cannot endure to hear it talked of within, but call it blasphemy,
corrupt heart, and deceitful heart,
etc. and the apostle told the saints that God would write his law in their hearts,
and put it in their minds, and the law is light;
and God would dwell in them, and walk in them, and where God is, there is light,
and in him there is no darkness and the saints are his temple;
and this doctrine of the light within,
it is thy work and ministry to warn all men against.

[.discourse-part]
_Principle._ '`To look at the light within, leads men to look at a judgment here in this life,
and to take off men from eternal judgment.`'

[.discourse-part]
_Answer._ None see the judgment in this life, nor the eternal judgment,
but with the light within; for the light makes manifest what must be judged,
and what must not.
Oh, that thou shouldst be so blind!
And they who judge themselves shall not be judged.

[.discourse-part]
_Principle._ '`The people who depended upon light within, fell into shameful enormities,
and when they pretended the light within, they pretended an angel of light,
which cozens us,
which at the best is but a broken cistern.`' The Ephesians '`were sometimes darkness.`'

[.discourse-part]
_Answer._ They are the broken cisterns that cannot hold the water of life,
and they are under the pretended angel of light, that deny the light of Christ within;
and shameful enormities are out of the light which makes manifest all those things;
and though the Ephesians were darkness, yet the light shined in the darkness,
and the darkness could not comprehend it.
John 1.

[.discourse-part]
_Principle._ '`The light within draws from the expecting of the assurance of Christ,
by working in our hearts, the children of disobedience;
so that we wait not upon God for assurance, but to trust to the light within.`'

[.discourse-part]
_Answer._ None come to the assurance of Christ Jesus,
but they who come to the light that shines in their hearts,
which Christ Jesus hath enlightened them with, which is the way to him;
none come from under the power of the prince of the air out of the disobedience,
to the thing they had disobeyed, but they who come to the light within,
which shines in their hearts,
which gives them '`the light of the knowledge of the glory of God in the face
of Christ Jesus,`' and none know the working of Christ but by the light within.

[.discourse-part]
_Principle._ '`When they were pricked in their hearts,
the apostle did not bid them look to the light within them.`'

[.discourse-part]
_Answer._ Did not the apostle bid them repent?
And was not there something in them that did give them to
understand their transgression that they might repent,
and come to receive remission for their sins by Christ the light,
who lighteth every man that cometh into the world, which light shines in the darkness,
and the darkness comprehends it not;
which light gives the light of the knowledge of God in the heart,
and that which pricks them is within them.

[.discourse-part]
_Principle._ '`To look at the light within, puts us by the experience of the created word.`'

[.discourse-part]
_Answer._ The light within brings to look at Christ,
whose '`name is called the word of God,`' by whom all things were created;
and the light within gives experience of him,
which is beyond all created experiences that are changeable;
and the scripture doth not tell us of the created word.

[.discourse-part]
_Principle._ '`To follow the light within the natural man, that is said to lead to perfection,
draws from and puts us from waiting upon the commands of God.`'

[.discourse-part]
_Answer._ No natural man comes out of his natural state to perfection,
to know the commands of God;
that which discovers all these things to him is the light within,
which comes from Christ, and brings him to know the covenant of God;
they who are kept from the light within, are kept from perfection,
and the commands of God, and the covenant of God, and Christ.

[.discourse-part]
_Principle._ '`There can be no reproof for breaking of a law if it were not written.`'

[.discourse-part]
_Answer._ Adam broke the law before it was written, and was reproved.

[.discourse-part]
_Principle._ '`Light within, and watching in that light to bring us to perfection,
will be a vain watch.`'

[.discourse-part]
_Answer._ None see perfection, nor come to the true watch,
but they who come to the light within,
which doth manifest that which must be stood against, and not received;
and all watches are vain that are not in the light within,
for they will put evil for good, and good for evil; darkness for light,
and light for darkness, that watch not in the true light that shines in their hearts,
which makes manifest.

[.discourse-part]
_Principle._ '`Let us leave leaning on the light within for direction.`'

[.discourse-part]
_Answer._ Then you turn yourselves from the apostles`' doctrine,
the light that shines in your hearts,
to give you the light of the knowledge of the glory
of God in the face of Christ Jesus,`' 2 Cor.
iv. and you turn into darkness from that which should give you the knowledge.

[.discourse-part]
_Principle._ '`To look to the light within draws us from,
or puts us past the blood of the new covenant, and the application of it.`'

[.discourse-part]
_Answer._ He that sees the new covenant, Christ Jesus, to Jews and Gentiles,
the covenant of light, which doth enlighten every man that cometh into the world,
and the blood of it, he that sees this, his eye is opened, and he is a believer;
for he who sees the blood of Christ and his righteousness,
and comes to the blood of Christ who hath enlightened him, comes to life;
and no one comes to life,
but he who comes to the light which Christ hath enlightened him withal.
For '`in him was life,
and the life was the light of men;`' and the light shines in darkness,
and the darkness comprehends it not, though all things were made by him.
And they that live in the darkness, hate the light, and do not believe in it,
and so they are condemned by the light.

[.discourse-part]
_Principle._ '`That this doctrine, the light within, draws us from Christ.`'

[.discourse-part]
_Answer._ None come to Christ, nor are drawn unto Christ, but by the light, and that is within,
and gives them to know what they are come from, and what they are come to,
for it gives them the knowledge of the glory of God in the face of Christ Jesus.

[.small-break]
'''

As for all thy other works of darkness in thy book, they are not worth mentioning.
But as to whose messenger he is, the day doth bring him to light,
the witness of God in his conscience shall answer
in the day of his condemnation and judgment,
who is under the spiritual wickedness, and in whom are the high places of it,
who stands against, and denies the doctrine of the light within.
The saints and apostles have judged him to be a messenger of Satan, a false apostle,
a minister of unrighteousness, out of the light, the truth,
as you may read in the Corinthians; for the true messengers, ministers,
and apostles of Christ Jesus, made by the will of God,
brought people to the light within, that shines in their hearts, and told them,
that the light '`would give them the light of the knowledge
of the glory of God in the face of Christ Jesus.`'
