[#ch-93.style-blurb, short="Priest Fergison"]
== Priest Fergison`'s principles as followeth, who is a teacher in Kent, confessed to Ambrose Rigge.

[.discourse-part]
_Principle._ '`That the scripture was the law and testimony.`'

[.discourse-part]
_Answer._ This is contrary to the scripture, for the scripture saith, '`the law is light,`' Prov.
vi. and '`the testimony of Jesus is the spirit of prophecy;`'
and the law and testimony were before Matthew,
Mark, Luke, and John, the Epistles and Revelations were written, as in Isaiah viii.

[.discourse-part]
_Principle._ '`That the scripture is the rule of life and doctrine,
and that it was the word of God.`'

[.discourse-part]
_Answer._ Adam, Abel, Enoch, Abraham, and the holy men of God,
had a rule for their lives before the scripture was written;
the spirit was the rule of their lives, that led saints to speak forth scripture.
And they that have the scripture, and not the spirit of Christ, are none of his;
and the Jews had scripture, but wanted the rule of life.
Nevertheless the scripture which was given forth from the spirit of God,
is profitable for doctrine; and the scriptures of truth are the words of God,
learned of God, and not the word;
and Christ who was before the scriptures were given forth, by whom the world was made,
is the word of God, who fulfilled the words; the scriptures end in him,
who was before they were spoken forth.

[.discourse-part]
_Principle._ '`That the scripture is the way to God,
and that the scripture was the ground of faith.`'

[.discourse-part]
_Answer._ The ground of faith is Christ; the apostle bids the saints look to him,
who was the author and finisher, not to the scripture,
but to Christ the author of their faith, the ground of it.
And Abraham, and Enoch, and Abel had faith before scripture was written:
so they who have faith, are of Abraham, and they witness Abraham`'s ground.
And the Jews had scriptures, but had not faith, nor the ground:
so your faith that hath no other ground but the scriptures,
is like unto the Jews`'. And Christ is the way to God,
who was before the scriptures were written, who fulfils the prophets, Abraham,
and David`'s words.
And the Jews had scriptures, but stood against Christ Jesus the light, the way to God,
as all you do that stand against the light.
And Abraham, and Abel, and Enoch had the way to God before the scripture was written,
and Christ Jesus is the way to God.
Christ saith, '`I am the way,`' to the Jews who had the scriptures.

[.discourse-part]
_Principle._ '`That there is no perfection to be attained to, while people live upon earth.`'

[.discourse-part]
_Answer._ Then by thy doctrine Christ is not attained to while man lives,
which is contrary to the apostle`'s and Christ`'s own doctrine, who said, '`I in you,
and you in me:`' and,
'`Christ in you the hope of glory.`' And then none abide in the vine by thy account,
which is Christ; and none bear fruit to the glory of God who abide not in the vine,
and who abide in the vine, abide in the perfection of God;
and thou art contrary to the ministers of Christ,
whose work was for the perfecting of the saints.

[.discourse-part]
_Principle._ '`That justification and sanctification differs.`'

[.discourse-part]
_Answer._ Justification and sanctification are one;
for Christ who is the justification and sanctification is one,
and it is thou that differest from him.

[.discourse-part]
_Principle._ '`That the word of faith in the heart, spoken of in Romans x. is the scriptures.`'

[.discourse-part]
_Answer._ The apostle doth not say so; for many had the scriptures, and were under the law,
and knew not the word of faith, the gift of God.

[.discourse-part]
_Principle._ He said, '`The scripture leads into all truth.`'

[.discourse-part]
_Answer._ This is contrary to scripture; for the scripture saith,
'`the spirit of truth shall lead you into all truth;`' this is the promise of Christ,
and Christ`'s words.
And Abraham and Enoch had their leader, to Christ and to God,
before the scripture was given forth.
Oh! that ever men should be set up to be teachers,
that are so blind concerning the scriptures,
and receive so many thousand pounds a year for teaching!
And the Jews had scriptures, and, as you Christians are now, were not led into all truth;
therefore are you all in heaps about them,
wanting the spirit to lead you into all the truths of them.

[.discourse-part]
_Principle._ He said, '`that Christ, and the Father, and the holy ghost, are not one;
but they are three, therefore distinct.`'

[.discourse-part]
_Answer._ This is the denying of Christ`'s doctrine, who said,
'`I and my Father are one;`' and the holy ghost proceeds from the Father and the son,
and he was conceived by the holy ghost, and they are all one, and not distinct,
but one in unity; that which comes out from him, leads the saints into all truth,
(that ever was given forth from the spirit of truth,)
and so up unto God the Father of truth,
and so goes back again from whence it came.

[.discourse-part]
_Principle._ '`It is blasphemy to say the son is one with the Father, and not distinct from him.`'

[.discourse-part]
_Answer._ The Father and the son are one, the son is in the Father, and the Father in the son,
so that which is in him, is not distinct from him;
and they blaspheme that say the son is not in the Father, and deny Christ`'s doctrine.

[.discourse-part]
_Principle._ He said, '`The Father is a distinct incommunicable being from the son,
and the son a distinct incommunicable being from the Father,
and the holy ghost a distinct incommunicable being from the son.`'

[.discourse-part]
_Answer._ The son is one, and in unity with the Father, and not distinct, but equal,
and thought it not robbery.
The holy ghost is in unity with the son and the Father, which proceeds from them,
and they are one in unity, and not distinct.
Thy doctrine is dross, and you priests are not fit to judge in such things as they are,
they are too weighty, and too heavy for you.

[.discourse-part]
_Principle._ '`He affirmed, that the scripture is the power of God,
and that the scripture is the gospel.`'

[.discourse-part]
_Answer._ The power of God led them that spoke forth the scriptures;
and the power of God is Christ, and the power of God endures forever;
but scripture is writing, and doth not; and the gospel is the power of God,
say the scriptures, and they do not say that the scripture is the gospel;
for many had that, and witnessed not the glad tidings.
And so thou art here distinct from the ministers of the gospel,
and art not a minister of it, which is the power of God, but puts writings for it;
which power of God was before writings were.

[.discourse-part]
_Principle._ He affirmed, '`that the Father was the Creator, and not God.`'

[.discourse-part]
_Answer._ This is contrary to the scripture.
For '`in the beginning God created the heavens and
the earth;`' the Father and God is one,
the maker of all things; for God the Father that made the world, saith the apostle, Gal. 4:6.
is '`one God and Father of all.`'

[.discourse-part]
_Principle._ He said, '`that Christ was not his rule, but the scripture was his rule.`'

[.discourse-part]
_Answer._ I do believe thee that Christ is not thy rule; so life is not thy rule,
wisdom is not thy rule, truth is not thy rule; and so Christ not being thy rule,
thou art ignorant of scriptures, and knowest them not;
for he who is the substance of the scriptures, is not thy rule; so thou knowest them not,
neither art subject to them.

[.discourse-part]
_Principle._ He saith, '`that God justifieth them that are not sanctified.`'

[.discourse-part]
_Answer._ He that is justified is sanctified, for he that justifieth, sanctifieth.

[.discourse-part]
_Principle._ '`And another priest saith, '`that Christ was not the resurrection of the body.`'

[.discourse-part]
_Answer._ Christ is the resurrection and the life, and the saviour of the body,
who brings the creature into the liberty of the sons of God.
