[#ch-95.style-blurb, short="Edward Briggs"]
== The professors`' principles at Westmoreland. Edward Briggs the leader of them, said,

[.discourse-part]
P+++.+++ '`It was heresy and deceiving the people, to bid people believe in the power of God.`'

[.discourse-part]
A+++.+++ Then they must not believe in Christ who is the power of God;
and it is not heresy nor deceiving of people, to bid them believe in the power of God,
which is Christ, but they are in the heresy and deceiving state,
that do not believe in the power of God; and are deceiving people,
and keep them all in heaps under the power of the devil, and so to believe in that,
which is the cause of people`'s destroying and persecuting one another.

[.discourse-part]
P+++.+++ '`And others of the professors said,
'`that God had no hand in working out his salvation.`'

[.discourse-part]
A+++.+++ This is contrary to scripture,
'`for God was in Christ reconciling the world to
himself.`' And God is the author of salvation,
who sent his son into the world to be a leader, a captain, a teacher, and a redeemer,
and a covenant.
And there is no name by which men must be saved, but by this name.
