[.style-blurb, short="Priest Fowler, of Reading"]
== Priest Fowler, of Reading, his principle.

[.discourse-part]
_Principle._ He said, '`that the scripture was the foundation of foundations.`'

[.discourse-part]
_Answer._ Here thou hast thrown out Christ, who is the tried stone, and the sure foundation,
and not the scripture; but the scriptures declare of it by the prophets and the apostles;
and no other foundation can any man lay but what is laid, Christ Jesus.
And thou hast laid another foundation, and so art contrary to the prophets and apostles,
and thy work will come into the fire; for God laid the foundation of the waters,
which is not scripture.
God laid the foundation, so that all men in the lost state,
all the sons of Adam that are in the transgression,
might come to build upon him the foundation, Christ Jesus.
When wise men are turned backward, and the soothsayers and enchanters are gone mad,
and the chaff scattered, and all makers of trades of Christ and the apostles`' words,
Babel, and the builders fall, the foundation of God, Christ Jesus, remains;
they who are built on him are sure, and remain.

[.discourse-part]
_Principle._ Priest Goodgroom, and the priest of Ware, affirmed and said,
'`the scriptures were both the writings and the thing signified.`'

[.discourse-part]
_Answer._ By this the scripture is Christ, and God, and spirit, and life, and saviour,
and devil, and hell, and error, and blasphemy by your principle and doctrine,
which is all false, for the scripture is not error, nor blasphemy, nor heaven, nor hell,
nor Christ, but declares of these things.
How have you led people in the ditch, ye blind guides,
they are wallowing in their sins in the mire, and crying out of them,
and then you tell them they shall never be made free from them while they are upon earth,
making a trade of saints`' words!

[.discourse-part]
_Principle._ '`That Christ justified persons,
excluding and setting aside the new birth and work of sanctification.`'

[.discourse-part]
_Answer._ Justification sets not aside the work of sanctification, nor the new birth,
but is one with it; for justification is sanctification; for they who are justified,
it is by Christ, who is the sanctifier, and they who are in him, witness the new birth;
for as many as receive him, Christ,
who doth enlighten every one that comes into the world: as many as receive him,
to them he gives the '`power to become the sons of God.`' And those
who hate the light which they are enlightened with,
this is their condemnation: '`for this is the condemnation,
that light is come into the world; but men love darkness rather than light,
because their deeds are evil.`'

[.discourse-part]
_Principle._ '`That the letter is the word:`' and denies '`that
any were converted by a light within.`'

[.discourse-part]
_Answer._ The principle of God hath been transgressed within,
so comes unconversion and going from God,
and the higher power added upon the transgressor.
The law, and they who had it, had the types, figures, and shadows,
which made nothing perfect; but the bringing in of a better hope did,
which hope is Christ within; and none are converted to God out of types, figures,
and shadows, out of transgression, out of Adam`'s state in the fall,
and know the renewing of the inward man, life and immortality come to light,
but as they come to know the light within, Christ, who is the way to God;
and he who is in him, is in conversion, translation, and regeneration, in a new life,
serving God.
And the scripture or letter is not the word, Christ is the word;
and they that had the letter, killed him who was before the letter was;
who were the blind priests and Pharisees, like yourselves.

[.discourse-part]
_Principle._ '`That Christ justified sinners as sinners.`'

[.discourse-part]
_Answer._ Christ justifies them as they have been sinners, and come from it, in the faith;
for by faith are they justified: and faith purifies them from their sin,
but they that hate the light which Christ hath enlightened them withal,
are condemned by it, and that is the world`'s condemnation, the light,
in which light the saints witness their justification,
and see Christ the author of their faith.
