[.style-blurb, short="Lamb in the city of London"]
== Lamb in the city of London, the Baptists`' teacher, and some of his company. Their principles as follows.

[.discourse-part]
_Principle._ He affirmed, '`that the scripture was the kingdom of heaven,
and that the scripture was the light of the Lamb.`'

[.discourse-part]
_Answer._ The kingdom of heaven is within people, as in Luke xvii.
And the Pharisees had scripture, and knew not the kingdom of heaven within them,
but were gazing for it without them; as thou art gazing without, and sayst,
the scripture is it, when the scripture doth but declare of it,
and tells people it is within them, and saith, Christ is the light,
and the scripture is a declaration of it.

[.discourse-part]
_Principle._ Two of the Baptists said,
'`that the light which doth enlighten every one that
comes into the world is a natural light,
and Christ was a natural man.`'

[.discourse-part]
_Answer._ The light which doth enlighten every one that
comes into the world is Christ the covenant of God,
which was before the sun and moon and stars were, which were made by him,
which are natural lights; and Christ is not a natural man, nor was not;
for a natural man receiveth not the things of God, but they are foolishness unto him;
and the things of God Christ did receive, and they were not foolishness unto him.

[.discourse-part]
_Principle._ Two Baptists affirmed, '`the Quakers denied the scriptures,
because they did not speak with a book in their hands.`'

[.discourse-part]
_Answer._ This is ignorance; for a man may speak the scripture,
and have never a book in his hand, though he does not name chapter and verse,
which are set up by men`'s wits;
for the spirit that gave them forth did not set them
in a frame to please men`'s wills withal.
And the Quakers do not deny the scriptures,
because they do not tell people chapter and verse, and hold a book in their hand,
but are come into that which it speaks of, into that which cannot be shaken:
and here the blind ignorance of the teacher appears,
who can get no farther than the chapter and verse, and book in the hand.
And this is like the horse which can find the pasture again when he hath been there:
so when he hath seen chapter and verse, he can find it again.
This is not like them who gave forth the scriptures, which they learned of God,
and what they had received of God, afterwards recorded;
which now you and the priests fall out about, and are in heaps,
and have no unity with it nor God, nor one with another,
and would tear one another`'s flesh to pieces about it; and here your spirits are tried.
