[#ch-99.style-blurb, short="William Greenhill"]
== William Greenhill, priest of Stepny, who makes a trade of the scripture, his principle as followeth.

[.discourse-part]
_Principle._ '`The scripture is the divine word and wisdom of God.`'

[.discourse-part]
_Answer._ Thou hast thrown out Christ in this, and put scripture in his place,
and given the scripture his name, who is the word, as in the Revelation,
'`Whose name is called the word of God,`' who is the wisdom of God,
and this the scripture testifies of, as in the Corinthians, John, and the Revelations.

[.discourse-part]
_Principle._ William Stanley, a tutor to children, said, '`that some had a privilege to sin,
and yet were free from the condemnation of the law by the sufferings of Jesus.`'

[.discourse-part]
_Answer._ But none have a privilege to sin from God, but from the devil;
for it is contrary to the law of God; for the law doth not tolerate any such thing,
nor the son of God, who was made manifest to destroy the devil and his works,
and to condemn sin in the flesh,
so no one hath a privilege to commit sin but from the devil,
and there is no privilege to sin, from God.
