[.style-blurb, short="The Relation of Quakers`' Shaking"]
== A book called, [.book-title]#The Relation of the Quakers`' Shaking,# those whose names are to it, are John Gilpin, Thomas Craster, Thomas Sands, John Archer, Edw. Turner, priest Walker.

Who are like unto Jannes and Jambres who resist the truth, being men of corrupt minds,
who blaze abroad in the nation to make truth odious, and to possess the hearts of people,
by means of some that turn from truth.
First, John Gilpin, who was made by truth to confess his sin, and had openings,
and then turned from the truth again, to the persecutors,
this Gilpin was these men`'s convert,
who were most of them the greatest persecutors in the north.
And after John Gilpin had turned from the people called Quakers,
to these men whose names are to the book, he turned drunkard, and being drunk,
a warrant was granted out for him, by a justice of the peace;
and yet these men whose names are to this book,
styled this man one of their high converts,
but according to their works their reward will be.

[.discourse-part]
_Principle._ John Gilpin said, '`While he was with the Quakers,
he never found such effects among the ministers of England,
as he did amongst the Quakers, of the discovery of his sin,
in particular of his covetousness,
which had a great long root in him.`' And all these men whose names are in the book,
term this of the devil, and this is their judgment,
because John Gilpin ran out in his imaginations;
therefore that which discovers to a man all his sins and his covetousness,
is of the devil.
Oh no, my friends, you have wrong judged,
and you will fail at last in what you have judged, and what you have justified;
and that which discovers your sin and filth, and covetousness,
that which discovers the devil, who is the author of it,
is the light and life of Jesus Christ.
And so instead of saying the Quakers are shaking, you are shaking yourselves,
and your foundation made known, not to be the foundation of Jesus Christ,
the light that discovers sin.
And when the true thing did convince and work in John Gilpin,
then his imaginations ran out; and you and he,
call it delusion to hearken to the voice within, and yet you and John Gilpin say,
that he was in some measure raised to believe that God would deliver him,
and yet it is delusion, to hearken to the voice within.

[.discourse-part]
_Answer._ What confusion is here amongst you and your convert!
Doth any believe or come to deliverance or faith, but he who hears the light within,
and who hears the voice within, that bears witness within?
Doth not he that believes hearken to the witness in himself, and hath he not it there?
And is not faith in the heart?
And is any deliverance known, but what is known from that within?
And thus you poor deluded creatures are glad to trust in lies, and make them your refuge.

[.discourse-part]
_Principle._ He saith, '`he began to consider how he had offended God,
by his neglect of the use of external means, reading, hearing, and prayer,
and rejecting the revealed will of God in his word,
and hearkening to the voice of God only within.`'

[.discourse-part]
_Answer._ Are reading and praying in the spirit external means?
Is this your judgment, all you priests, and teachers, and great professors,
found in this book?
Can any pray but in the spirit, and read the scriptures so as to know them again,
but in the spirit?
And is not that eternal?
Can any man know the revealed will of God, and his word, but by the spirit?
Is not the word in God?
Is not Christ the word?
'`His name is called the word of God,`' and can any
know these things but by the voice within?
Which voice is the spirit, the spirit of the Father speaking in believers, the saints,
which led them to speak forth the scriptures.
So when that voice was neglected, then was John confused,
as you all are now that speak against it; so that whatsoever filth and dirt you run into,
you will father it upon the voice within, or the light, and Christ within.
But you are comprehended and seen,
who are now flown to those external means you tell people of,
and that your prayers and reading are external; we do believe you,
who are all out of the spirit.
But if ever any of you come to know God, and true praying in the spirit,
you will deny your principle.
And we do believe your means are external, and your prayers external,
without the spirit of God.
And this Gilpin who had been thus a covetous and grievous sinner,
whom the Lord smote that he came to be almost a distracted man,
after he had got a little ease from under the judgment, his flight being in the winter,
he goes to the priests and professors, who are here mentioned in the book,
enemies of all righteousness, and presently turns a drunkard;
and a justice of the peace granted a warrant to set him in the stocks,
and so he passed away about thirty miles off to Cacebie.
And this is Gilpin`'s Lord; who was convicted, by the truth, of his covetousness,
and his sin, who run into his imaginations, whose latter end is worse than his beginning.
And this is the convert of these many persecuting professors and teachers,
who to their shame have published it, which comes atop of their own heads,
and truth is clear, and filth is wiped and wiping away,
and the refuge of lies is flying away that people shall not make them their refuge.
And those persecuting professors and priests take occasion to speak of one James Milner,
in whom the Lord did open true prophecies, and mighty things to him,
but in some things his mind ran out, and that he condemns;
and yet these wicked men will go tell the nation of it,
so what will they have more of a man but his life,
for abundance they have cast into prison.
And again these persecuting professors and priests have published
in one of their books to the world of one Hugh Bisbrowne of buggery,
who had some time come to the Quakers`' meetings, but was turned from them,
and durst not meet them, for he had been judged by the Quakers,
before such things were heard of him by them;
and yet these filthy men will vilify truth with such things,
that they might make it odious to the world.
But the sober people see all these things are but their envy.
And again these persecuting professors and teachers have put in their book,
that they have published to the world, one Cotten Crossland,
and they say he was a professed Quaker,
and that he knew higher things than the ministers, and that he hanged himself,
and he was buried in a cross way, and a stake was driven through him,
that passengers might take heed of quaking.
This man I saw once at a meeting, and another time in the rude multitude.
The first time he said little,
and the second time he spoke something amongst the rude multitude,
which the Quakers did not own; and he raised a grievous lie against G. F. and said,
he said he was Christ, which was on a market day among the market people.

This was the third time that ever I saw him amongst any of the Quakers;
and he told G. F. he had witness to prove it, and G. F. told him, he was Judas;
and he went away, and after awhile hanged himself.
And Christ in the male and female, he spoke of, was Christ the seed,
and the seed was Christ; but he did not speak it, as of a creature.
And here is the priests`' and prefessors`' Quaker, who turned against the Quakers,
and would have betrayed them.
But quaking we own, and trembling, which you all must do,
before you know your salvation wrought out with fear and trembling.
And many lies you have gathered up together and stuffed up your book withal,
and make them your refuge, and think the world will take refuge under them,
but alack for you!
People begin to see it was nothing but envy in you.
And it was known that Gilpin was never long a Quaker,
though the devil was made to tremble in him.
And the Lord will reward you according to your work.
The witness in your conscience shall answer it in you all in the day of your judgment.
