[#ch-101.style-blurb, short="Saints through the Immortal Seed"]
== Thomas Collier, Nathaniel Strange, Thomas Glasseys; who call themselves servants of Christ, in their paper to all the churches, called '`Saints through the Immortal Seed.`'

[.heading-continuation-blurb]
The churches and saints who are of the immortal seed
have viewed your paper and your principles in it, as follows.

[.discourse-part]
P+++.+++ You say, '`You have taken upon you to speak to God,
though dust and ashes,`' and yet you said, you '`are saints through the immortal seed.`'

[.discourse-part]
A+++.+++ You have forgotten what you have written before in your preface:
who have taken upon you to speak to God, though dust and ashes,
yet say you are saints through the immortal seed:
such as are saints through the immortal seed, are not dust and ashes;
for the immortal seed lives, and abides, and endures forever.

[.discourse-part]
P+++.+++ You say, '`you have been bewailing congregation iniquity, family iniquity,
personal iniquity, and close iniquity;
for by your search you have found Zion full of unsoundness
from the crown of the head to the sole of the foot,
all putrified sores; and now you call upon them that tremble at the word of God,
to come to you.`'

[.discourse-part]
A+++.+++ You have cast them out that tremble at the word of God,
and have made them your by-word, and written and printed against them,
but the Lord hath appeared to their glory: and what kind of saints are you,
with your close iniquity, family iniquity, congregation iniquity, and personal iniquity,
and Zion from the head to the foot all full of putrified sores,
and no soundness from the head to the foot and now
do you call to them that tremble at the word of God,
whom you have cast out, whom in scorn you have called Quakers?
Will you now turn Quakers?
Do you begin to be ashamed?

[.discourse-part]
P+++.+++ '`Oh! come and sit down in the dust,
and weep bitterly before the Lord for your abomination!
You have, as it were, but played with God, you have not trembled at his presence;
you have been wanton before him,
and have forgotten what manner of men and women you were;
and thought no more of your prayers.
Oh! how often have you mocked God: how doth the world canker your affections,
while you have been asleep, in the lap of this Delilah!`'

[.discourse-part]
A+++.+++ Thou hast even shamed thy church dost thou call them saints through the immortal seed,
and say they mock God, and are asleep in the lap of this Delilah?
and that the world hath cankered their affections?
Thou hast shamed thy church, calling them saints through the immortal seed,
and yet they must weep bitterly for their abominations, and sit down in dust and ashes!
Are these like saints, sanctified ones, of the immortal seed?
Or like transgressors, the unsanctified ones, not worthy to have the name saints?
For such as mocked God, and were in abominations, and must lament for it,
were not sanctified, nor were they come to know the immortal seed:
but the saints and the immortal seed, reigned over all mockers,
and over such as were cankered with the world, and mocked God,
and were in their abominations; they came to reign over all that in the wisdom of God,
with which they ordered the creation to his glory.
You call yourselves servants of Christ.
If your people be cankered and mockers of God, and in the abominations,
you have laboured in vain, and this shows you have not profited them at all,
but are false teachers.

[.discourse-part]
P+++.+++ You say you have '`reigning abominations, cruelty to servants and children,
exacting labours, taking no time to counsel them,
and have mourned that you have had so great a hand in this trespass,
and not borne testimony against your ministers.`'

[.discourse-part]
A+++.+++ This hath been your condition; your fruits have declared it:
therefore it is time for you to repent, and amend your lives and doings,
and turn to the Lord; for while you have time, prize it,
for you that have stood against '`the light that doth enlighten every
man that comes into the world,`' are not of the church of Christ;
for none come to it, but through the light.

[.discourse-part]
P+++.+++ '`Though slavish fear had stopped our mouths,
until the mouth of iniquity hath almost devoured the poor church of Christ.`'

[.discourse-part]
A+++.+++ The church of Christ is the pillar and ground of truth,
it cannot be devoured by the mouth of iniquity,
the gates of hell cannot prevail against it; but through your mouth of iniquity, enmity,
and envy, you have almost slain yourselves, who are turned against the truth:
who have not been slavish for it, but against it; mad in your blind zeal;
the mouth of iniquity hath been open in you, with all the world, against the truth,
but by the truth in a great measure it is stopped.

[.discourse-part]
P+++.+++ '`These evils have been so strong that they have wrested
all weapons out of the hands of saints and ministers,
that have been formed against them.`'

[.discourse-part]
A+++.+++ These have been pitiful weapons, that you ministers and saints have had in your hands,
that the evil wrested them out: they have been carnal, not spiritual;
for the spiritual weapons the evil one cannot wrest
out of the hands of saints and ministers of God;
but by them his holds, and high places, and spiritual wickedness, are plucked down;
the evil dares not come nigh the saints`' weapons, which are spiritual.

[.discourse-part]
P+++.+++ You say, '`We desire no longer to rest in a testimony of words,
but to take an effectual course,
that sin and sinners may be purged out of the house of God;
we desire the church would set some days apart wherein
they may bewail iniquity and pollution;
that ministering brethren would, without respect of persons, from house to house,
night and day, bear their testimony to fly from those abominations.`'

[.discourse-part]
A+++.+++ The church of God you know not, which is the pillar and ground of truth,
which Christ purchased with his blood, without spot or wrinkle, or blemish;
and the house of God you know not, who talk of purging it;
which is established atop of all the mountains.
And all your abominations, and pollutions and respecting of persons,
are out of both the church and the law, and you are transgressors of it,
and it is time to begin to stir up yourselves and turn from the evil of your ways,
to Christ the light, who hath enlightened you,
that you may bear testimony against yourselves, and your ministers,
and against lightness and abominations in your own families.
And do not say it is the house of God, and the church of God, but amongst yourselves;
and we do believe your testimony is but the testimony of words,
who have denied the light, and so denied the power.

[.discourse-part]
P+++.+++ '`They may deliver themselves from the blood of souls,
having declared the whole counsel of God.`'

[.discourse-part]
A+++.+++ Can dust and ashes, and cankered ones, and pollutions, and abominations,
can such declare the whole counsel of God?
Such are out of it, for they that come into the counsel of God declare that;
and come out of pollutions, and from being cankered with the world,
to him by whom the world was made, who is perfect,
and makes them perfect who declare his perfect will and counsel.

[.discourse-part]
P+++.+++ '`Another evil we thought to have spread before you, but wanting opportunity,
we shall now omit, and that from Chard; we have laboured in vain,
that which hath been brought forth hath been to little purpose.`'

[.discourse-part]
A+++.+++ This you may speak to your shame,
and you show forth your own nakedness that you have laboured in vain,
and that which you have brought forth hath been to little purpose;
in this the church of Christ believes you, who are they that have beaten the air.
And why do you print abroad that there is another
evil among you which you have not laid open?
Had you not better have held your tongues, except you had mentioned it?
Is not this Ham`'s spirit who lays open one another`'s nakedness to the world in print?
But how can you do otherwise who have denied the light '`that hath enlightened
every man that comes into the world,`' which comes from Christ Jesus;
and so want the covering.
And as for all your dirt, and dross, and dung, which is not worth mentioning,
in your epistle, and confused words, which you have set forth, thinking it to your glory,
but it is to your shame; had you been in the life that gave forth the scriptures,
which the saints that were of the church were in, you would have covered your nakedness,
and would not have said that pollution was in the church, and in the house of God.
But for all these things you are judged, you and your epistle,
and your words to be unsavoury;
they are judged by the life of God that gave forth the scriptures,
and by them that are of the house of God, and the church of God,
where no pollution nor canker is, nor comes;
the witness in your conscience shall answer it in the day of the Lord.
