[#ch-102.style-blurb, short="The Judgment and Advice of the Assembly of the Associated Ministers"]
== A paper, called '`The Judgment and Advice of the Assembly of the Associated Ministers. By us, Richard Baxter, etc. Pastor of the Church of Kidderminster.`' Their principles in it follow.

[.discourse-part]
P+++.+++ '`That ever there should be so much to do among christians, yea,
the leaders of Christ`'s flock, to bring them to so clear a duty,
that after all their labour, there is no more done!`'

[.discourse-part]
A+++.+++ You have been them that God never sent,
and are found to be such as Christ cried woe against,
and so you have not profited the people at all,
and you have not been the leaders of Christ`'s flock, but have been such,
as turned against them; that hath been your duty; therefore are all the people on heaps.

[.discourse-part]
P+++.+++ '`That all men must know that we are Christ`'s followers, if we love one another;
for he that saith he loves God and hates his brother, is a liar.`'

[.discourse-part]
A+++.+++ In this, poor men, you have judged your ownselves; for are not debate, and strife,
and vain glory, and persecution, and prisoning, found among you?
Cain turning against his brother Abel, and slaying and killing him,
whose blood cries for vengeance upon you?
So it is a proof that you are out of the faith that works by love,
in which are the community and love with God, and one with another.
And so instead of making up breaches, you are wounding, and bringing confusion,
being out of the faith and life that Christ and the apostles were in;
so you are in heaps about their words.

[.discourse-part]
P+++.+++ '`It is not our business to change men`'s minds,
from infidels and heresy to the faith;
but to bring the churches of Christ to understand each other to be true churches,
which take the holy scriptures for our rule of faith and life,
and believe it to be the infallible word of God; and this rule is divine,
so our faith is divine; had we but a human rule we could have but a human faith;
proud men thrust their opinions into the church`'s creed.`'

[.discourse-part]
A+++.+++ Your business, it is true, is not to change men from infidels and heresy,
and to bring them to the faith, so not into the unity; for you bring no people into that,
nor to the faith, and you do not bring the churches to know one another in the faith,
and the churches of Christ know each other to be true churches,
and you whose business is not to bring men off from heresy to faith,
know not the church of Christ, which is the pillar and ground of truth,
built upon Christ, who is the author of faith.
And the scriptures, which signify writings, outward writings, with paper and ink,
are not, as you say, infallible, nor are they divine, but human,
and men get a human knowledge from them;
and so writings with paper and ink are not infallible,
nor is the scripture the ground of faith, but Christ,
who was before the scripture was written; this the scripture tells you,
and that God is divine; and the scriptures are the words of God, which Christ, the word,
ends, who is the author of the faith.
And Abraham and Enoch had a rule, and had faith, before scripture was written,
and the spirit is the rule that leads people into all truth, so saith Christ;
and you put the letter for the ground of your faith, your rule is paper and ink,
that will come to dust, it is human as you call it,
and you give it that which the scripture doth not.
And as for your creed, that you have learned of your father the pope,
the scriptures tell you not that, neither do they teach you the word human;
so you and the Papists have crept into the apostles`' words, but are out of the life,
and are proud and covetous.

[.discourse-part]
P+++.+++ '`That it is heresy to say there is another rule of faith than the scriptures,
and if any are proved to teach any doctrine contrary to scriptures,
let the ministers and pastors do their parts to correct and restrain them.`'

[.discourse-part]
A+++.+++ You by your judgment have judged yourselves to
be corrected by the ministers and pastors,
and to be restrained by your own judgment, who have taught contrary to the scriptures;
for the scriptures say Christ is the author of faith, and faith is the gift of God.
And you say scripture is the rule, but Abraham, and Enoch, and Abel,
will tell you they had faith before they had the scripture, which you say is your rule.
So, have you not thrown out the true rule of faith, and the giver of it,
and put the words in the place?
and so are ye not corrected here by the true pastor, Christ the author of faith?
And faith is the gift of God.
The apostle did not say scripture was the ground of it,
but bid look to Jesus the author of it;
and the apostles did not turn such to the ministers to be corrected that opposed them,
or did not believe them, nor receive them as they spoke, or that went from them.
And all they are in the heresy that have not Christ, the author of their faith,
which was before the scripture was given forth; and though they have all the scriptures,
they are not in the life of them that gave them forth, in which was the unity.
And therefore you, being out of this faith and unity, and from the author of it,
put the letter for the rule, are all on heaps about the saints`' words,
being out of the life that they had that spoke forth the scriptures,
which were afterwards written and printed.
And so ye wolves in sheep`'s clothing put that for the rule of your dead faith,
and have no other, and are killing and mangling one another about it,
and so death and destruction talk of the fame of the scriptures,
and know not the author of faith, nor would have known that there had been a faith,
had not the scripture declared it; the priests confess it.

[.discourse-part]
P+++.+++ '`We deny not,
that in order to teach people and young ministers to stop the mouths of slanderous adversaries,
to cure the jealousies of distempered minds, we all are ready in every Protestant church,
to give men a full account of our faith, in plain confession: but with this protestation,
that the holy scriptures only are the rule of faith:
if any thing in our confession be found disagreeable to that rule, we are ready,
when we understand so much, to disown it, and to correct it.`'

[.discourse-part]
A+++.+++ How do you stop their mouths in haling them before magistrates,
and casting them into prisons, is this your stopping?
Is not this your work?
Let the jails and the houses of correction witness how you have stopped their mouths,
and convinced gainsayers!
Now, that which is truth, and they who speak plainly to you,
ye call adversaries or slanderers.
Now it is not a slander to call a lamb, a lamb, a dog, a dog, or swine, swine;
but to say a lamb is a swine, a dog is a sheep, that is a lie; or that a wolf is a sheep,
though he hath got a sheep`'s clothing on him,
and therefore would be called a sheep that he may deceive,
and would not be called a wolf, though his fruits declare it.
Notwithstanding his reviling, devouring, having sheep`'s clothing,
and casting into prison, yet he is offended if ye call him not a sheep,
or a minister of the gospel of Christ.

Nay, the truth, the lambs, the sheep cannot do so, but they must speak the truth to you;
and though you devour them, and tear them, they will not tear you again:
and though you wolves have on the sheep`'s clothing,
you cast into prison because they will not feed you.
Did ever the lambs do so, the ministers of Christ?
Were not they fed in his pasture?
Followed him, and knew his voice, and did not want?
But how have you cured the jealousies and diseased minds all this while?
You have wounded them, made them sick, and filled them full of jealousies;
therefore are the people broken into heaps and sects,
which are the fruit of jealousies one of another.
And how have you been ready, you who are called teachers,
who are apostatized from the apostles,
to render to every Protestant church a full account of your faith in plain confession,
when many hundreds have been moved of the Lord God
to come into those places called churches,
and ask you a question, you have cried, '`Take him away, magistrate; to prison with him;
he hath broken the law, neighbours;`' and this hath showed your faithlessness.
And many have been moved to come to the steeplehouse, and look the priest in the face,
and he hath cried, '`take him away, I cannot go forward,
I cannot speak as long as he stands there;`' and
here you have showed your faithlessness again,
wanting the weapons, the shield of faith.

But you say again, they must own the holy scriptures to be the rule of faith.
So then not Christ, not God, the author!
What rule might Abraham, and Abel, and Enoch own?
Was not God the author of their faith?
And is he not the same now?
Had not the Pharisees the scriptures?
Had not they the rule, who stood against Christ the author of faith,
and who is the rule which the saints looked at?
Are not they that are of faith, of the faith of Abraham,
which was before the scripture was written?
Was the scripture the ground of this?
Nay, the ground of these was that which was before the scripture was written,
and they were in the faith that stood in God that gave forth the scriptures;
and so here both you and your churches are corrected by the scriptures.
For all may speak one by one in the true church; but this authority you have thrown down,
who are such as preach for the fleece, and the filthy lucre, and gain from your quarters,
who are called of men masters, suing for tithes, going to law about earthly things,
which the apostles did not, but rebuked such: and so you are corrected by the scriptures,
and you are judged with the life of the prophets, Christ, and the apostles;
and both church and ministers are departed from it.
