[#ch-103.style-blurb, short="Ministers in the County of Cork"]
== The agreement and resolution of several of the associated ministers in the county of Cork, for the ordination of ministers. Their principles in it as follow.

[.discourse-part]
_Principle._ '`To minister the spirit,
it is not promised to teach anything but what Christ hath spoken.
John makes it an infallible trial of spirits to convince gainsayers and stop their mouths.`'

[.discourse-part]
_Answer._ Many may have Christ`'s words, all that ever he hath spoken,
and if they have not the spirit of Christ they are none of his.
And gainsayers that gainsay the spirit may have Christ`'s words,
and the light that comes from them: so the spirit that gave forth the scriptures,
tries the spirits and lets men see whether they pervert Christ`'s words.
For Christ saith, that the false prophets would get the sheep`'s clothing;
therefore could antichrist and the false prophets try spirits?
Nay, they put them to death that were in the spirit:
and he who hath the spirit of Christ, can tell who wrongs Christ`'s words.
And why did not the ministers of Ireland,
who had Christ`'s and the prophets`' and apostles`' words,
stop the mouths of Edward Burrough and Francis Howgill,
but suffered or caused them to be banished out of the nation.
You looked upon them to be gainsayers, who are the servants of the Lord;
and yet you were not able to stop their mouths, though you had all the sheep`'s clothing,
neither were able to resist their spirit; which shows your spirit,
and that you are not fit to send forth ministers, nor make ministers, nor try ministers.
And the apostle doth not say, that the letter is the only rule or trial;
but if people have not the spirit of Christ, they are none of his,
and if they have not Christ in them they are reprobates.
And we do witness that the spirit is come, whereby we are ministers of that,
not of the letter: for the spirit that once established circumcision,
the same spirit ended it again.
Now the Jews that tried by the letter, judged the apostle to be a deceiver.
And those that have the sheep`'s clothing, and have not the spirit of Christ Jesus,
they are crying, '`lo he is here,`' and '`lo he is there.`'

[.discourse-part]
_Principle._ '`You tell us of a sacrament, and that the world lies in wickedness,
in gross Egyptian darkness, and of false apostles and Jezebel,
making herself a prophetess to teach and seduce,
and men loving preeminence are to be called masters.`'

[.discourse-part]
_Answer._ In this state you are called of men masters, loving preeminence, Jezebel like,
usurping authority, setting up yourselves to teach, keeping your fasts,
persecuting and banishing the righteous, you are in the steps of the false apostles,
in spiritual Egypt, in gross thick darkness,
rejoicing with the world that lies in wickedness, telling people of your sacraments,
which you had from your father the pope, and the false apostles your forefathers,
who were got up before the apostles`' decease,
and so you are judged with the life of the apostles and Christ,
and by them that are in it; which shall answer the witness of God in you all.
And the wickedness of the world declares your fruits,
that you have not profited the people at all.
And your Jezebel`'s doings hath declared itself, and your loving preeminence,
being called of men masters, which the apostle judged, and Christ cried woe against:
these marks are found in your foreheads, that all that can read the scripture,
may read you to be out of the life of Christ and the apostles.

[.discourse-part]
_Principle._ '`Unless some preacher of righteousness be then
living to warn the sinful world of their wickedness.`'

[.discourse-part]
_Answer._ Such as are the preachers of righteousness,
who warn you and the sinful world of their wickedness, you banish, these are your fruits.

[.discourse-part]
_Principle._ '`The purest grain hath its chaff, the best needs a fan to cleanse them,
the best needs a Nathan, all flesh is liable to fly-blows.
To run without office and power argues presumption.`'

[.discourse-part]
_Answer._ The wheat that is gotten out of the chaff, hath not its chaff,
that comes into the garner: and such as are cleansed, need not the fan to cleanse them.
'`They that are born of God do not commit sin,`' for the seed of God remains in them,
that they cannot.
And all need not a Nathan, all are not adulterers;
and the flesh of Christ which sees not corruption, is not fly-blown:
and the saints of Christ are of his flesh and his bone;
and you run without the power that the apostles were in,
so you judge yourselves by the presumptuous ones.

[.discourse-part]
_Principle._
'`The sheep are apt to wander; ordinary ministers receive their ministry from the Lord.
Paul chosen immediately by God, Stephen mediately.`'

[.discourse-part]
_Answer._ In the cloudy dark day, the sheep wandered, who were made a prey of by you,
who seek for the fleece.
Ezek.
xxxiv.
But the Lord will seek them, and gather them, and feed them atop of the mountains.
And the sheep of Christ hear his voice, and follow him, so saith Christ;
so they do not wander.
And they that receive their ministry from the Lord,
are above all your ordinary ministers of the world made by men.
And Paul was made immediately,
and all the ministers of Christ and God that in the spirit, it makes them immediately.
But all you, since the days of the apostles, that have got the sheep`'s clothing,
and ravened from the spirit of God, are mediate.

[.discourse-part]
_Principle._ '`Such are in the self-conceit that are against ordinances and sabbaths.`'

[.discourse-part]
_Answer._ Every one that is in the spirit of Christ sees
him who hath blotted out the hand writing of ordinances,
and triumphed over them, and therefore cannot touch them;
and such as are come to the body of Christ, see the end of new moons and sabbaths.
And such as are out of the body, and do not see that,
are crying up their ordinances and sabbath, which the body of Christ comes to end,
who is the substance and end of them, and was before they were.
Now antichrist cries up that which the apostle preached down,
who are blind and see not the body, and set up sabbaths of their own making,
and keep markets and fairs on that day which the Lord commanded,
and call it Saturn`'s day, which was the Jews`' sabbath,
which was given to them as a sign; but the body is Christ.

[.discourse-part]
_Principle._ '`Vice may be nourished with the milk of virtue, the gospel ministers;
and we find that the harvest is great, and the labourers are few.
We conclude with a few words to the readers of our principles and intended practices.`'

[.discourse-part]
_Answer._ The readers have viewed your practices and principles both,
and tell you that they are corrupt, the milk of virtue doth not nourish vice.
This was not the ministers of Christ`'s language;
the milk of virtue nourisheth the babes;
and the labourers that have been sent amongst you from the Lord God,
you have banished out of the nation.
But if one come in his own name, him you will regard and receive;
but if one come in the name of the Lord, him you put out.
So you will not have the Lord, nor his Christ, to reign,
neither his servants to labour in his vineyard.

[.discourse-part]
_Principle._ '`Ministry is like a mighty tree,
whose fruit the Lord hath appointed for the healing of the nations.`'

[.discourse-part]
_Answer._ But your and the Papists`' ministry hath been got up since the days of the apostles,
that brings nations all into heaps, and into blood, and doth not heal the nations,
but wounds, and burdens, and kills, and casts into prison, as this your fruit declares,
who casts into prison such as you do no work for.

[.discourse-part]
_Principle._ '`To the law and to the testimony;
pray to the Father of lights that he would enlighten us with his truth,
and show us the way that he would have us to walk in;
and pray for us who watch for your souls, as those that must give account.`'

[.discourse-part]
_Answer._ The testimony of Jesus is the spirit of prophecy:`' and '`the
law is light,`' and the law and testimony was before Matthew,
Mark, Luke, and John, and before the Epistles were written, and the Revelations,
which outward books you call law and testimony; but the scripture saith,
'`The testimony of Jesus is the spirit of prophecy;`' and '`the law is light.`' Prov.
vi. Are you them that are the makers of ministers, and ministers,
who watch for the souls of people,
and yet do you bid people pray to the Father that he would enlighten you with his truth,
and show you the way that you may walk in?
How can you present souls to God, that do not know the way,
and are yet to be enlightened, and yet to have the way showed to you,
that you might walk in it?
Is this the conclusion of all you ministers in Ireland?
Now I say, Christ hath enlightened every man who comes into the world, which is the way,
and though your darkness cannot comprehend it, yet you pray that he would enlighten you.
John saith, he doth enlighten every man that cometh into the world,
and that is the true light.
Have you the light to seek, and the way to seek, and truth to seek,
and yet are you watchers for souls?
And you that are called ministers say, the soul is human; yea, the soul of Christ;
the soul of man is appetite, and lust, and pleasure, and human, from the earth,
from the ground.
Is Christ`'s soul from the ground?
and appetite, lust, and pleasure war against the soul,
in them that are in the unreasonableness.
You that have the light to seek, truth to seek, and way to seek, are in the earth,
and so give the soul the name of that which comes from the ground.
Now the soul is immortal; '`God breathed into man the breath of life,
and he became a living soul.`' It is that which came out from God,
who hath all souls in his hand, that is his power; which goes against him that doth evil.
And Christ the power of God, which is immortal, is the soul`'s bishop,
from whence it hath its nourishment, and which is able to save the immortal soul.

And as for all the rest of your ignorance and nonsense in your book,
which comes from your confused earthly spirit, who are found in the nature, spirit,
and stock of your father the pope, who hath apostatized since the days of the apostles;
with all the rest of your stuff, which is but fuel for the fire,
in the day of your account, the witness in all your consciences shall answer it.
