[#ch-104.style-blurb, short="Margin Notes"]
== John Stillom`'s book, called [.book-title]#Margin Notes.# His principles as follow.

[.discourse-part]
P+++.+++ He calls it the '`Quakers adoring their own light,
magnifying the light of nature.`' '`The church is
ashamed of your doctrine and walking,`' saith he.

[.discourse-part]
A+++.+++ The Quakers`' light is Christ the truth, in whom they worship God;
which light was before natural lights were; and this the church owns,
and is not ashamed of; in which stands the doctrine,
by which light the church is gathered up unto God the Father of light;
but the imitated churches in the apostacy are ashamed of it.

[.discourse-part]
P+++.+++ '`Not any man knows him,`' speaking of Christ, '`to be God,
until he find him in scripture,`' and saith,
'`as deep things as the spirit hath revealed, they are all in the scripture.`'

[.discourse-part]
A+++.+++ Many knew God, and knew Christ,
and yet had not written scripture to tell them of those things, as Enoch and Abel;
and many again have scripture speaking of God and Christ,
and yet do not know God and Christ, and do not find him in scripture.
As for instance, the Pharisees who had the scripture, knew not God and Christ,
and had not life, until they came to Christ the scripture speaks of;
and many things the spirit did reveal which were not written in the scriptures,
and were spoken to the saints.

[.discourse-part]
P+++.+++ '`John meaneth not that there was any substantial
truth necessary to be known to salvation,
which is not revealed in the written word;
but the spirit ordered the copies and mysteries of the gospel
to be contracted within a narrow compass of lines.`'

[.discourse-part]
A+++.+++ Many knew their salvation, as in the days of Noah, Enoch and David,
who had not the written scriptures.
And though people have the copies that speak of the gospel,
and of the mysteries of the gospel, put together,
and compassed and contracted into lines, yet they do not know the gospel,
nor the mysteries of it, nor the word, though the scriptures testify of these things;
and the Pharisees did not, that had scripture;
which scripture doth not tell us of written words, but that the word is Christ and God,
which was in the beginning before words were given forth.
And the gospel, and salvation, and the mysteries of it, are known by the spirit,
and the light which comes from Christ Jesus, and none knows them but by that.

[.discourse-part]
P+++.+++ Stillom adds, '`not only heart rising prophecy, nor breast prophecy in the mind,
but written down in books.
The apostle excludes not heart prophecy, so he includes scripture prophecy;
but till the daystar did arise in their minds by reading and heeding of the scriptures;
that is plain meaning.`'

[.discourse-part]
A+++.+++ The scriptures were given forth by prophecy, and the spirit of it,
and no man knows them but by the same spirit;
and the apostle did not exclude heart prophecy;
and the day-star doth not rise in the heart by men`'s
reading and heeding the scriptures in their own wills,
and having them written down in books;
but as men come to the life and spirit that they were in who gave them forth,
and heed that, with that they heed scripture, and know scripture,
and with that they know the day-star, and Christ who is the end of them;
and so men must come to take heed to the light that shines in a dark place,
before they know the day-star arise.
For the Jews had scripture, and did not heed that;
for the spirit of prophecy within doth not deny any title of the scripture without.
And in thy principle thou hast confounded thyself, who sayst, '`Not heart prophecy,
heart rising, breast prophecy; and yet thou sayst,
the apostle doth not exclude heart prophecy.`' And thus thou with thy new names,
and thy words, darkenest counsel and knowledge; but the children of light see thee.

[.discourse-part]
P+++.+++ '`The Father, word, and spirit, are to justify the word trinity,
not to make the holy spirit and the saints one person.`'

[.discourse-part]
A+++.+++ The word trinity is not in the scripture, but in your old father`'s book,
the canon book, the pope; and the Father, son, and spirit are one,
and the saints are in the spirit; and those who are joined to the Lord, are one spirit.
And the scripture doth not tell us of three persons; but, as I said before,
the old canon book of thy father, the great apostate, the pope.

[.discourse-part]
P+++.+++ '`The light that Adam was qualified with before the fall,
which every man hath a spark of since the fall,
was and is given from the creation by things that are made.`'

[.discourse-part]
A+++.+++ The light Adam had before the fall, did not come by the creation,
nor by the things that are made; if it were given from the creation, it comes by nature.
This word is contrary to scripture; for God made man in his image,
and placed him over all the creatures, and gave him an understanding capable of his law,
and to know dominion; but when man lost his dominion, he transgressed his law;
and that light that he had before the fall, was of God, from him that made all things.

[.discourse-part]
P+++.+++ '`The scripture is the means of regeneration.
If the blind lead the blind, what will follow?
It is proof sufficient against absolute perfection in this life, as Adam and the angels.`'

[.discourse-part]
A+++.+++ They that had the scriptures, and were out of the life that gave them forth,
were the blind, and what followed then?
And though Adam and the angels fell, he who is in Christ, the perfection of God,
shall never fall, as also saith the apostle.

[.discourse-part]
P+++.+++ He saith, '`It is ignorance that saith, the light that makes sin manifest,
condemns sin.`'

[.discourse-part]
A+++.+++ And that which makes a man`'s sin manifest, and he hates it, that condemns him;
and he is ignorant that sees not Christ`'s doctrine, and believes not in it.

[.discourse-part]
P+++.+++ '`To deny that sin dwelleth or remaineth in all the saints upon earth,
hath been the Quakers`' doctrine,
the consequence whereof is to disclaim all godly sorrow for sin dwelling in them.`'

[.discourse-part]
A+++.+++ It is the Quakers`' doctrine to deny all sin dwelling in the saints upon the earth,
and to know Christ who destroys the devil the author of all sin;
and the saints come to witness their joy and pleasures forevermore over their sin,
and the body of it put off,
and a kingdom which stands in joy and peace in the holy ghost,
and the godly sorrow before they come to this; and they do know victory over their sin;
and Christ had the godly sorrow, who had no sin, and that many of the saints know.

[.discourse-part]
P+++.+++ '`His word is not his spirit.`'

[.discourse-part]
A+++.+++ The word and the spirit are one,
which word was before the written words were given forth by the spirit of God,
in which word they all end; and the word lives, and abides, and endures forever,
and that is spiritual.
And so the mystery of iniquity is found in thy doctrine who art blind, and reads blindly,
not with the spirit which was in them that gave forth scriptures.
And so thou art found a false prophet, in the steps of the Pharisees,
one of the masters that Christ sets the woe on their heads,
who art ravening with the sheep`'s clothing upon thy back to deceive;
but now the lambs and the sheep have discovered thee,
who art got up since the days of the apostles into their words, not into their life,
with that thou art judged.
And whereas thou art offended because Edward Burrough speaks chapter and verse,
the spirit that gave forth scriptures will lead to speak it all over again without offence,
but to the evil doers.

[.discourse-part]
P+++.+++ '`And if your teacher cannot but be public,
how will you find him in so private a place as your beds?`'

[.discourse-part]
A+++.+++ The spirit that leads men to speak forth publicly,
or to minister to themselves and others,
the same is a private teacher to them on their beds, as with David,
whom the Lord instructed in the night season;
and that which the minister of the spirit doth minister unto,
is a private teacher to every particular in his own particular.
And the anointing which abideth in people, John said, was their teacher,
and they needed no man to teach them, but as it did teach them,
and they should continue in the son of God and the Father.
And here was public and private teaching, which thou being blind canst not see.

[.small-break]
'''

And all thy lies and heap of confusion which thou wouldst blind people with,
shall stand upon thy head; for the sun is risen, and the mist is gone and going:
in the day of thy judgment, the witness in thy conscience shall answer.
