[.style-blurb, short="Philip Taverner"]
== Philip Taverner of West Drayton, in the county of Middlesex, his principles as follows, in a reply to a book to Edward Burrough, whom he in scorn calls Quaker.

[.discourse-part]
_Principle._ '`Who art thou that judgest another man`'s servant?
Such who lord it over the faith and consciences of their brethren,
a spirit wholly disowned by the apostle.
Not that we have dominion over your faith;
and in this sin is that of Christ to be understood.
Call no man your father upon earth, neither be ye called of men master; that is,
have no men`'s persons in admiration, as to count them your oracles in things of faith.`'

[.discourse-part]
_Answer._ Such as serve the man of sin, are to be judged.
We judge that man and servant both.
And such as are spoken of in the Romans, who judge another man`'s servant in the truth,
standing and falling to his master, every one in his measure, such we do not judge;
but every one shall stand or fall to his master, who are scrupling about meats,
and drinks, and days, that the life is leading through.
And you that are called of men master, who are counted great oracles amongst the people,
you lord it over men`'s faiths and consciences both;
therefore hath so much blood been shed through you, and so many cast into prison by you,
who are lording it over men`'s faiths and consciences, being, Pharisee like,
called of men master, who would have dominion over the apostles`' faith,
and over the saints`' faith,
who are '`admiring men`'s persons because of advantage,`' to help you.
And this people see, how you and the Papists, since the days of the apostles,
have lorded it over men`'s faiths, as your jails, inquisition, and prisons may witness,
how you would lord it over men`'s faith and conscience.
Those that cannot give you tithes, you will cast into prison;
are you not here lording it over men`'s faiths?
Do not your practices show it, and so another spirit than the apostles`' is in you,
who are got up since the days of the apostles.
And such as are born of God, and begotten of him,
cannot call any man father upon the earth, such as are born of the immortal seed,
heirs of the world which hath no end.

[.discourse-part]
_Principle._ '`We through patience and comfort of the scriptures have hope.`'

[.discourse-part]
_Answer._ He who hath Christ in whom the scriptures end,
hath the hope and comfort of the scriptures,
Christ who was before the scriptures were given forth.
He who hath not Christ Jesus hath not comfort.

[.discourse-part]
_Principle._ '`The scriptures are able to make wise unto salvation.`'

[.discourse-part]
_Answer._ Without the faith the scriptures are not, for the Pharisees had the scriptures,
and were not wise unto salvation, but were out of the faith,
and knew not Christ the salvation.

[.discourse-part]
_Principle._ '`Fear hath its rise from faith and hope in God,
by the means of Christ which is made known in the scriptures.`'

[.discourse-part]
_Answer._ The scriptures testify of faith, of God, of fear; but people receive not hope,
nor faith, nor God, nor fear, from the scriptures, but from God,
as they did that gave forth the scriptures, who feared him.
For many that had the scriptures, were out of the true fear of the Lord,
and called Christ a devil, and were from true hope and true fear,
though they had the scriptures given forth from them that were in hope and fear;
but their ears and eyes were stopped to that of God in them,
and such are never like to receive God and Christ until
their ears and eyes are open to that of God in them.

[.discourse-part]
_Principle._ '`If we say we have no sin, we deceive ourselves, and the truth is not in us;
and there is not a just man upon earth that doth good and sinneth not;
and in many things we offend all.
And the state is not attained in this life,
but that men shall be groaning under weaknesses.
The highest attainments of saints, is but a spark, but the dawning of the day;
that highest enjoyments are not to the attainment of desires.`'

[.discourse-part]
_Answer._ It is the truth that lets men see they have sinned,
and lets them see they have sin within them, and it brings them to confess it,
and forsake it; and '`the blood of Jesus Christ, the son of God,
cleanseth from all sin.`' Then '`he that is born of God doth not commit sin,
neither can he, because the seed of God remains in him:
herein the children of God are manifest,
and the children of the devil,`' which makes him to roar.
He that is born of God doth not commit sin, and cannot, because he is born of God,
he is not born of the devil, nor by the will of man, nor by flesh and blood.
And what Solomon saith, in Eccles.
vii. speaking of the just man, is, that he doth no good under the law, by which,
saith the apostle, no flesh is justified.
But he that comes to Christ, the end of the law, his faith gives him victory over sin,
whereby he becomes dead to it, and comes to the end of the law;
which faith the just live by, by the life and the faith of the son of God.
And the apostle saith in the epistle to the twelve tribes,
'`In many things we offend all.`' Mark, in many things we offend all;
but we are come to the one thing, Christ Jesus, the end of the many things,
and in him there is no sin.
And he sins not who is in him, who put an end to the many things that must end and change.
And the saints were come to the day, further than a spark,
and were the children of the day; and they witnessed the night was gone;
and some again were not come to the day-star, according to their growth.
And the saints again were made free from sin, Rom.
vi. And had put off the body of sin, by the circumcision of the spirit.
Coloss.
ii. And they were complete in Christ; and they witnessed the kingdom of heaven,
that stood in joy, and peace in the holy ghost, and so were not groaning always.
And the saints witnessed the marriage of the lamb and Christ in them,
and their bodies to be the temple of God, and attained the end of their desires;
and so were not always desiring, but they witnessed their bread from above,
which they that ate of should hunger no more, nor thirst any more.

[.discourse-part]
_Principle._ '`The light which is in every man is but darkness,
being compared with a revelation of Christ in the saints.
Our justification hath its rise from what Christ hath done and suffered for us,
not from what he hath done in us.
Justification and sanctification are ever distinct in their nature,
distinct one from the other; justification is not sanctification,
nor sanctification justification, but two things, really distinct in their nature.`'

[.discourse-part]
_Answer._ The light which every man that cometh into the world is lightened withal, is Christ,
and this light reveals Christ, and is the saints`' light,
and this light is condemnation to the world, which hates it.
And no man knoweth justification, but as he knoweth it wrought within, from Christ.
And no man knows the seed that was offered, the sacrifice of the whole world,
but as he knows it within, through the faith;
and they who are of the faith are of Abraham, they are of the flesh of Christ,
the flesh of him that suffered.
And if men have not Christ within them, they have not justification;
and though they may talk of him without, and have him not within,
yet such are reprobates that have not Christ within them, reprobate from Christ,
from justification and sanctification both,
and are of the generation that caused him to suffer.
And justification and sanctification are one,
not distinguished the one from the other in their natures, but are one in nature,
not two things really distinct in their nature, but really one;
for Christ our sanctification and justification, is he that sanctifies and justifies;
they are one in nature; Christ is sanctification and justification both,
and thou art rebuked who makes two of them, and distinct, when they are but one thing;
the same that justifies, sanctifies.

[.discourse-part]
_Principle._ '`If the fulfilling of the righteous law in us be justification,
then Christ died in vain.
Justification is the direct opposite to condemnation;
that which makes a change in the heart of the creature,
is sanctification and justification;
faith doth not save nor justify by virtue of any worth or excellency found in it,
nor merely because Christ is the object of it.`'

[.discourse-part]
_Answer._ He that fulfils the righteousness of the law in us, is Christ the justification;
hereby men come to know him to redeem them from under the law,
and they are led by the spirit; and they know he is their intercession,
and that he died not in vain: and he ends the law, who fulfils it.
And he is the justification to every one that believes.
And this is known in us, that believe to the justification of it,
whereby a tittle of the law is seen not to be broken, whereby the body of Christ is seen,
which makes free from the law.
And Christ is the light that condemns him that hates it,
that will not come to it because his deeds are evil, nor believe in it;
and '`this is the condemnation of the world, that light is come into it,
and men love darkness rather than light,
because their deeds are evil.`' And he that believes in the light is justified
from all things from which the law could not justify him,
and comes not into condemnation, but lives in that which doth condemn; so these are one,
and not directly opposite, that doth condemn the unbeliever, and justify the believer.
And people are saved and justified through faith, and faith is the gift of God;
and there is an excellency in it, and a worth, because it comes from Christ,
and from God who is the author of it, in which faith men please God,
and are justified and are saved through and by this faith, as the scripture witnesseth.

[.discourse-part]
_Principle._ '`Faith doth not save or justify by its virtue,
but by the gracious good pleasure of God who hath appointed faith.`'

[.discourse-part]
_Answer._ That which God hath given to men as his gift, in that faith there is virtue,
and the grace is known with which men are justified and saved,
and there is virtue in the gift of God;
and so through this faith he knows the purpose of the Lord, and his counsel,
and Christ is the author of this faith,
and no man is justified but through faith that is received, nor wise unto salvation,
but through faith in Christ Jesus.

[.discourse-part]
_Principle._
'`The ministers in England in many places are no better than wolves in sheep`'s clothing,
and the ministers taking what the states allow them of particular persons,
this is not preaching for hire, divining for money.`'

[.discourse-part]
_Answer._ The ministers, who are so called in England, have gotten the name,
but are found the ministers of unrighteousness,
and are wolves indeed in sheep`'s clothing, out of the lives of the apostles;
for how are they tearing the lambs before courts and into prisons for speaking to them,
whom they do no work for!
What greedy dumb dogs are these!
How do they worry the people!
And where is there any one of them, that has the sheep`'s clothing,
if the people do not put into his mouth, but will tear them into courts, and dens,
and prisons?
How unlike the apostle are these, who would not use his power often times to eat!
And thyself art found in the number of them.
And do not the states and particular men set you out so much a year for your preaching?
And is not this preaching for hire, and divining for money?
Do you not know how much a year you must have?
And is not this preaching for hire?
And if they do not give you money, so much a year, you will not divine,
and yet will you make people believe, that you are not diviners for money,
and preachers for hire?
Alack for ye!
You cannot be hid,
and are not you here judged with the life of Christ
and his apostles to be his hirelings that will fly?
Whose sheep are none of your own, who care not for the sheep,
except you make a prey upon them!
To all people who are in the fear of God,
your lives are discovered to be contrary to the saints.
Let the states and the great men take away your maintenance,
and we shall find but few diggers, thrashers, and planters among you,
who are a company of idle men.
So the judgment of the apostle is come upon you, that those that would not work,
should not eat.

[.discourse-part]
_Principle._ '`Christ made use of the scripture to resist the devil.`'

[.discourse-part]
_Answer._ In Christ the scripture ends,
and the devil who was out of the scriptures is left out of the scriptures: so Christ,
who was before scripture was, bruised his head.
And as for the rest of thy stuff in thy book, it is not worth mentioning,
and it will come upon thy own head; the witness in thy conscience shall answer it.
