[#ch-106.style-blurb, short="The World`'s Wonder"]
== Edward Skip, teacher, who said that he is a servant in the gospel services, his book called [.book-title]#The World`'s Wonder.# His principles, as followeth.

[.discourse-part]
P+++.+++ '`Who saith there shall be false Christs, and false prophets,
and they shall show you great signs and wonders, insomuch, if it were possible,
they should deceive the very elect.`'

[.discourse-part]
A+++.+++ Christ said false prophets should come, Matt. 7:24. and John saw they were come,
1 John ii.
and iv.
chap.
they went forth from them.
In the Revelation all that dwelt upon the earth went after them,
and when they had gotten a head, they killed the saints;
then power was given to the beast over all tongues, kindreds, and nations,
and that which whored from the spirit of God sat upon the beast,
and all nations drank of her cup, and she hath corrupted the earth,
and made the inhabitants drunk,
and the kings of the earth have committed fornication with her.
And the woman fled into the wilderness, and the man child was caught up unto God.
And the whore sits upon the waters, and the waters are people, and nations,
and multitudes, and tongues, and these have been the mystery of Babylon,
with all their merchandise,
which have deceived the nations by their lying signs and wonders.
And again, the judgment of the great whore should come,
the man-child should be brought forth into the world
to rule the nations with a rod of iron,
and she should be taken and cast into the fire, who had set as a queen,
and had seen no sorrow; and the beast should be taken,
and with him the false prophet that sets up the lying signs and wonders,
and with him the devil that deceived the nations, the man of sin,
that the apostle before his decease saw coming up, as in Thessalonians.
These should be taken and cast alive into the fire,
(and the Lamb and the saints shall have the victory,)
that they should deceive the nations no more;
for the elect it is impossible they should deceive,
with all their lying signs and wonders which they
have got up since the days of the apostles.
And Christ said they should come, which the disciples saw were come before their decease,
which signs the world have been after, but which have not been able to deceive the elect;
for the elect reigns over all that, and over thee and them: amongst whom thou art found.
Now hath the Lamb and the saints the victory, and the tabernacle of God is with men.

[.discourse-part]
P+++.+++ '`I have presented to thee my new-year`'s gift,
and desire thy judgment towards it to me.`' And thou said,
'`The Lord had delivered thy soul from under those observances that thou mightest
stay and direct an unstable soul of those horrible delusions and mysterious deceits,
for false apostles, translating themselves into apostles of Christ, deceitful workers,
and Satan`'s ministers, transforming into the ministers of righteousness!`'

[.discourse-part]
A+++.+++ In this thou art among the false apostles and ministers of unrighteousness,
deceitful workers, transforming yourselves into the apostles`' and Christ`'s words,
and into the true ministers`' words,
whose souls are under horrible delusions and mysterious deceits,
under the observances of the world, who would beguile the soul that is not stablished;
but light is broke, forth, that few you can deceive.
And thy new-year`'s gift is judged, and proceeds from Cain,
and is his sacrifice from the earth;
for the apostle saw such as were transforming themselves
into the false apostles and false ministers,
and he brings the saints to the light that shined in their hearts,
to '`give them the knowledge of the glory of God
in the face of Christ Jesus,`' which you deny.
So the false are transformed into their words, and are judged with their spirit,
who brought people to the light within, and you bring them from it; so,
from that which should give them the knowledge of
the glory of God in the face of Christ Jesus.

[.discourse-part]
P+++.+++ '`The devil is called the prince of darkness, because he lives in the darkness,
as to the apprehension of divine love, an enemy to all the image of God,
which is light and purity; and the devil transformeth himself into the likeness of God,
under a fair pretence, heavenly words, self-denial actions, righteous conversations.`'

[.discourse-part]
A+++.+++ This is like your fruits, who have deceived the people; but is your love to the devil,
who is out of the truth?
Doth not Christ come to destroy him and his works?
And can any apprehend the love of God, but they who are in the truth?
And the devil cannot transform himself to be like God,
not in his image nor in his righteousness, that is out of truth;
and his conversation that is out of truth is altogether unrighteous,
and is but in the pretence of self-denial, but is not the thing;
though he and you may get the words that are heavenly,
and stand against the light and image of God, and purity itself,
for all you are of the devil that deny the light that doth
enlighten every man that cometh into the world,
for you come not into the truth which the devil is out of,
nor into the pure conversation which is in heaven, nor into purity.

[.discourse-part]
P+++.+++ Thou saidst,
'`thou hast many occasions offered by the Quakers upon thy poor weak and sinful heart;
the Lord hath filled my heart with moderation in giving my own once uncomfortable experiences.`'

[.discourse-part]
A+++.+++ We believe thee, that thy heart is weak and sinful,
and a weak and sinful heart is not filled with moderation.
And thy experiences which are uncomfortable, are not the experiences of the saints,
for the saints`' experiences are comfortable, and their hearts are pure,
and filled with moderation; and the Quakers will torment all sinful and corrupt hearts,
for such the Lord is against, that take his words into their mouths,
and so are his saints.

[.discourse-part]
P+++.+++ Thou sayst, '`thou hatest hypocrisy when thou livest in the light, life,
and power of the first Adam,
and because the Quakers say they know my conscience better than myself,
I see they are acted through delusion; I am able to speak this truth from my own heart,
which is better known to me.
I do know that a natural man may make a large progress
in the gospel profession and conversion;
and that which the Quakers call backsliding, is my turning to my God.`'

[.discourse-part]
A+++.+++ In the light, and life, and power of the first Adam, in which he was in the beginning,
before the fall, thou art not; and the apostles knew the state and condition of Jews,
and Gentiles, and people, better than they did themselves,
and so do the Quakers that are in their spirit; and this is not delusion.
And thou dust not know thy own heart as thou oughtest, nor the truth;
thou must first come to the light that doth enlighten
every man that comes into the world,
which is the truth.
And a natural man doth not make a progress into the gospel,
nor come into the conversation of it, whilst he lives in the natural estate.
And the God thou art turned to, is the god of the world,
that all hirelings and diviners for money, and teachers for filthy lucre turned to,
that went forth from the spirit of the apostles, and prophets, and Christ,
and backslid from them, and so went from the true God;
and thou servest the god of the world for love of thy benefice,
and see if thou wilt not look upward, and downward, and curse thy god.

[.discourse-part]
P+++.+++ '`I would have all the world to observe the Quakers,
how that antichrist hath cast that blindness upon their understandings,
for their reproving men sharply, and rebuking them, crying woe to the hypocrites;
it is the devil`'s policy to keep close to the scriptures.
G+++.+++ F. used arguments to people to look for the glorious way,
and discovery of the divine light and power to be brought
forth among all the children of the Most High.
Oh! this delusion of mystery Babylon.`'

[.discourse-part]
A+++.+++ Here is thy confession, for where the spirit of God is, it doth rebuke,
reprove sharply, and tell them that are hypocrites, the woe is to them;
and as to the Quakers, antichrist cannot blind them,
they are come from under his power and authority;
but you are they that cannot hear reproof.
And the Lord may send a man, as he did Philip, to such a place,
and he not know what he shall do, nor whom he shall speak to,
till he come to such a place.
And the devil is out of the life that gave forth the scriptures,
though he and you who may get them, may pervert the words,
but not own them as they speak; and thou callest good evil, and evil good,
for the children of the Most High wait for the most
glorious discovery of divine light and power,
which delusion and mystery Babylon are out of;
and so the Quakers are come to that which antichrist is ravened from,
with that they comprehend him.

[.discourse-part]
P+++.+++ And thou sayst, '`These people, that thou callest the Quakers,
will send most railing accusations against the pillars of the church of Christ.`'

[.discourse-part]
A+++.+++ That is false; but antichrist`'s church and his pillars, which are waters,
which you call tongues, your original, and which John calls waters,
the Quakers do judge according to truth, and declare it in full power and majesty,
and can make it good; which you call railing, but which they deny;
for a company of greedy dumb dogs can never have enough,
that will prison and persecute men till death for speaking to them and for means;
such are apostatized from the true church, are a false church,
who have transformed themselves into the true church`'s words.
But now the true church hath discovered you to be the false, apostatized from the true,
who have reigned since the days of the apostles.

[.discourse-part]
P+++.+++ '`I see no conviction the Quakers have wrought by their speaking,
or any subjection of fear or love, or any such thing wrought by them.
And to tell such that are praying, reading, or in meditation,
to say it is the power of the first Adam; Oh! mystery of deceit,
the deceitful unfolding of antichrist, to say that Christ saith the hour is coming,
and now is, that, neither at this mountain, nor at Jerusalem,
shall the Father be worshipped, but he that worships him,
must worship him in spirit and in truth!`'

[.discourse-part]
A+++.+++ Thousands in the nation may witness the work the Quakers have wrought,
and thousands are convinced that you are the gainsayers of the truth,
and the antichrist come up since the days of the apostles; and all your praying, reading,
and meditations, is but the first Adam`'s state in the fall,
where the mystery of deceit is, for you are not yet come to own the light, Christ Jesus,
the second Adam, that doth enlighten every man that comes into the world,
and so you are the antichrists, standing against Christ the light, the truth,
and so are not come into the worship of God in the truth and in the spirit,
but are crying up that at your mass-houses is God worshipped,
as the Jews said of the temple at Jerusalem, and the mountain of Samaria;
but Christ said, not at the mountain, nor Jerusalem, but in spirit and in truth,
and so we say, not at your mass-houses, nor at Samaria, nor Jerusalem, nor the mountain,
but God hath sought us to worship him in spirit and in truth,
and therefore you rage that hate the light.

[.discourse-part]
P+++.+++ '`They reckon it their perfection and happiness to be deprived of all:
the spirit doth neither so act or so teach: and I was kept from this temptation,
and they that are overcome by it, are brought into bondage.
A vain deceitful waiting for a power, when the apostle saith to the Thessalonians,
ye must pray without ceasing, and not quench the spirit.
They must cease from their own words,
and wait for the immediate striving and working of the spirit, as they fancy it.`'

[.discourse-part]
A+++.+++ This thou calls fancy, who sayst the spirit of God doth not teach men,
to be deprived of all things; yes,
I say to thee thou must be deprived of all things before thou come to happiness;
and thou art in the bondage, and in the temptation, that hast not forsaken all things,
and come to Christ the one thing; and thou praying and prophesying,
and not waiting for the spirit and power to pray withal, art in the fancy,
and following thy own spirit, and out of the perfection of Christ.

[.discourse-part]
P+++.+++ '`It is blasphemy to say we must fill up the sufferings of Christ.`'

[.discourse-part]
A+++.+++ And so thou art unlike the apostles,
and hast not drunk the cup of the wrath and judgment of the Almighty,
and that thou must drink before thou comest to know the seed of
God come from under all the power of wickedness in thee,
and that is the world; and Christ, who bore the sin of the whole world, and felt it,
and was under it, was offered, and is over it all, and makes his enemies his footstool.

[.discourse-part]
P+++.+++ '`The false interpretation of the enemy,`' he saith '`that
every man`'s work must be tried with fire,
what sort it is,`' and '`you shall hardly gain a speech of one sort or other, sometimes,
from the Quakers,`' and this thou calls '`dumb devil.`'

[.discourse-part]
A+++.+++ And thus thou showest where thou art, who hast not known a time to be silent,
before thou didst know a time to speak.
And the dumb devil hath been found amongst yourselves, you priests;
for when many of the Quakers have been moved of the
Lord to come to speak to you in your pulpits,
you have proved the dumb devils, turned your backs, and have gone your ways,
and spoken never a word to them.
And thy works and all men`'s shall be tried by the fire,
and that is not perverting scripture, as also saith the apostle.
And thou never hast passed through the wrath of God, but it is yet to come,
and the sufferings of Christ thou knowest not.

[.discourse-part]
P+++.+++ '`And it will be a lie and delusion,
for the spirit when it sanctifies the hearts to go
about to tear their hearts out of their bodies,
when David`'s bones were broken, and his flesh would scarcely cleave;
it is far from me to think that this was under the apprehension of wrath;
shall a man think that he suffered for his sanctification?`'

[.discourse-part]
A+++.+++ The spirit of God tears out the old hearts, and so,
before man is sanctified throughout he must know suffering, and his wretched state;
yet sanctification brings peace in the end, and life.
And David`'s condition thou art ignorant of, and knowest not;
for he was sensible of the wrath before his sins
were removed as far as the east is from the west,
and he had joy and peace;
but trembling and quaking is become a mock and scoff amongst you,
for there is a trembling and rejoicing, and there is a trembling in the sorrow.

[.discourse-part]
P+++.+++ '`When the Quakers are commanded many times to go,
they have not that leisure to dress them: this is a hard master surely, not Christ,
therefore Satan,
for the Lord is not wont to do things ignorantly to deceive his servants.
And they are brought to fast from all manner of food three nights and three days,
most feeble, wretched creatures, contrary to the law of nature;
so they are not capable of bearing the glory of God, so ministers of antichrist,
and they are made to deny their callings and possessions.
I would eat more than I desired, because I would give no offence.`'

[.discourse-part]
A+++.+++ In this thou hast showed thy ignorance of the scriptures, and Christ;
for he that is on the house top, let him not come down to put on his clothes.
And they that went on his message were not to take two coats:
and when they went on his message,
they did not go to dress themselves with boot-hose-tops, and double cuffs, and ribands,
and rings, as the priest doth; and what God doth, it is in his wisdom,
beyond the ignorance of mankind, and they that receive it must be in his fear.
And Christ is not a hard master, as thou thinkest, because some go,
not dressing them in their apparel, who go to do his command;
but thou who art wicked and slothful, hast so judged with the wrong and false judgment.
And many of the saints have fasted till they might number their bones; and Christ fasted,
and this was not contrary to the law of nature,
and did not make them incapable of receiving the glory of God; neither was it antichrist.
And thou who art of him, canst eat and drink more than thou hast desire,
because thou wouldst not offend others, and that is contrary to the law of nature.
And the saints forsook their callings and possessions, and the world;
but you priests run into great possessions, which you get out of poor people`'s labours;
so you are like the false apostles and antichrist, not like Christ and his apostles.

[.discourse-part]
P+++.+++ '`They have a gloss put upon Christ`'s words to his disciples,
when he bids them that they should take no care what to speak,
it should be given them in the same hour.
And of their going naked,
I never knew the mind of the Lord discovering by any of his servants,
neither under the old nor new covenant.
And these dreamers go to a place,
and do not know what to say till they come to the place.`'

[.discourse-part]
A+++.+++ Philip was sent to a place, and then it was told him what to say, when he came to it.
And he was not a dreamer, but thou art, who goes without a command from God,
and runs when he never sent thee, and follows thy own spirit.
And they that speak as the spirit gives them utterance, and moves them, take no thought,
but it is given them in the same hour; and thou that art out of this, art in the glosses.
It was the mind of the Lord for Isaiah to go naked,
and to strip himself in Egypt and Ethiopia,
as many are moved of the Lord to go naked among you of spiritual Egypt and Ethiopia,
and to put off their clothes; which is a figure to you,
that the sheep`'s clothing must be taken off of your ravening wolves`' backs.

[.discourse-part]
P+++.+++ Thou sayst, '`For the present thou dost not apprehend any thing more,
but that the devil shall transform himself into an angel of light.
And there are hardly a people to be found that cry out more against sin,
and the appearance of sin, and unrighteousness, than they do, as far as I know,
or have heard, to declare them to be carried forth as ministers of righteousness.`'

[.discourse-part]
A+++.+++ Thy apprehension is vain, and judgment false;
for the devil transformed himself into an angel of light before the apostles`' decease,
and so is transformed in you, who have the words, but out of the life;
for the devil could not transform into the apostles, while they were in the life.
And you are antichrist that are crying out against sin and unrighteousness,
and live in it; but the Quakers are the enemies of sin, and the friends of souls,
who are the ministers of righteousness, and declared so to be in all your consciences,
to be in the life of all the prophets, apostles, and Christ,
and they do see that you are transformed into their words, but out of the life,
and with that judged.

[.discourse-part]
P+++.+++ '`I am persuaded the Quakers do not tell a lie,
that Satan he will either choose to do some things, as healing some infirmity,
and turning water into wine, and the like; this is a deceitful way enough,
that all the belly-gods in England may become Quakers;
this labour of mine may make thousands to refuse their errors and delusions,
because it can be done through a great light that is in antichrist.`'

[.discourse-part]
A+++.+++ The Quakers are in the truth, and out of the lie, and they see you are in it,
for antichrist is turned from the light;
and the devil is not he that turns water into wine, and heals the sick and infirmities,
nor antichrist, but the true Christ; where did you read that they turned water into wine,
or healed the sick?
Therefore, thou and you, by your delusions and errors, labour to deceive thousands.
And thou hast cleared the Quakers from being in the error or delusion, for thou sayst,
'`they dare not lie,`' then they are not of the devil,
who is the ground of all error and delusion.
And you priests are the greatest belly-god sin the nation,
for you devour up the tenths of the nation, of poor husband-men,
and so you cannot endure the power that makes to tremble, so cannot endure the salvation.

[.discourse-part]
P+++.+++ '`What if one of these Quakers should be sent to a blind leader of the people,
and a man is not able to reply a word, and it may be, a good scholar.`'

[.discourse-part]
A+++.+++ They you in scorn call Quakers have been moved by the power of the Lord God,
to come against such as thou art, leaders of the blind,
though you have been great scholars,
and when you have not been able to resist their spirit,
but found naked from the spirit of the Lord,
you have cried to your rulers and magistrates, to help take them away,
cast them into prison; and these have been your weapons,
and antichrist`'s court and fort, and the wolves in the sheep`'s clothing,
strong against them that are in the apostles`' and Christ`'s power, and life,
and doctrine, and now you are discovered.

[.discourse-part]
P+++.+++ '`The crucifying the son of God afresh, that is, Christ without,
or else in the heart of another,
not in his own that doth it,`' and thou sayst '`thou engages thy affections to the seekers,
because of their attainments.`'

[.discourse-part]
A+++.+++ He that crucifies Christ afresh to himself, first crucifies him his own heart,
before he crucifies him in another`'s heart without him;
and it is the affections that thou art joined with to people, and not with the spirit,
to the notional attainments; for hadst thou been in the spirit,
thou wouldst not have written such a book as this is against the truth;
or hadst thou answered the principle of God in the seekers, or minded the life in them;
or in thy own particular, you might have lived in unity with God and scripture.
But whither art thou turned now, to thy great fat benefice?
And didst steal some words from the seekers,
and sell them to poor people to make a trade of them.

[.discourse-part]
P+++.+++ '`Thou sayst thou wouldst have all people take a right way in opposing the Quakers,
with a strong understanding in the scriptures to reason with them.`'

[.discourse-part]
A+++.+++ All your understanding and your reasoning, if you get all the scriptures,
are not able, being out of the life that gave forth the scriptures,
to resist the spirit of the Quakers,
which is that which was in them that gave forth scriptures,
though you may gainsay and oppose like Cain, Core, and Balaam; but woe unto you!

[.discourse-part]
P+++.+++ '`I shall give my consent, if the Quakers transgress our laws,
they might have double punishment;
and if you will not believe the truth that comes from them,
I hope you will believe it as it comes from the mouth of God;
with speed forsake the Quakers`' society wholly, public and private.`'

[.discourse-part]
A+++.+++ Here is thy confession again, and judgment, and thy injustice;
wouldst thou have double punishment inflicted upon them that break the law?
And dost thou say that the Quakers are the mouth of God,
and if you will not believe the truth as it comes from them,
believe it as it comes from the mouth of God;
and yet must people wholly forsake the society of the Quakers, public and private,
and call this overcoming strong questions?
This is the strengthening of strong questions, overcoming you that are in the deceit,
who are to be judged.

[.discourse-part]
P+++.+++ '`That God is all, and in all.`'

[.discourse-part]
A+++.+++ The scripture saith so, God is all, and in all, and through you all, and over you all,
blessed forever; and this is not to justify any profaneness nor wicked actions,
but it is you that would not have the Lord to have room in your hearts,
that would not have him to be in people, nor have him there to reign.

[.discourse-part]
P+++.+++ '`I have some time told the Quakers,
that I did conceive the design of antichrist was to bring
them in the end to work all manner of uncleanness;
I now judge they are carried from one degree to another to act righteousness.`'

[.discourse-part]
A+++.+++ Here thou confounds thy imagination,
and hast showed thou hast followed thy own spirit;
and thy false prophecy is come to an end, and thou hast proved thyself to be a dreamer,
for they are in the righteousness, which comprehends thee.

[.discourse-part]
P+++.+++ Thou sayst, '`The Lord doth not regain any of our age to walk so,
they that are called the Anabaptists, and yet thou ownest them.`'

[.discourse-part]
A+++.+++ Dost thou own that which the Lord doth not require?
And do they practise that which the Lord doth not require?
And so thou hast given judgment upon thyself and them both.

[.discourse-part]
P+++.+++ I having also communion with my former society,
which is broken off through the mysterious working of antichrist,
I would have spared my pen for a few lines, but for the sake of a very few in the nation;
and I have not time to write one line, from first to last, twice;
expect not from me an army of reasons and arguments.

[.discourse-part]
A+++.+++ Thou hadst better have spared thy pen and tongue both,
than have written that which thou hast written,
whose communion is with the mysterious working of antichrist,
and there are but few in the nation but will see thy work is but fuel for the fire.
And abundance of stuff thou hast in thy book, which is not worth mentioning,
but will fall upon thy head.
In the day of thy judgment the witness shall answer.
