[.style-blurb, short="Priest Tombes, Baptist, of Leominster"]
== Priest Tombes, Baptist, of Leominster. His principles as followeth.

[.discourse-part]
_Principle._ '`The words John 1:9. +++[+++enlighteneth every man,]
are meant of a natural life or light.`'

[.discourse-part]
_Answer._ Christ that doth enlighten every man that cometh into the world,
this light is not natural, neither is he natural that is called the power of God;
who was before all natural lights, sun, moon, and stars, were made;
and so this light doth enlighten every man that believes in it,
and is their condemnation that doth not believe in it; that is above all natural:
for the light that '`doth enlighten every man that
comes into the world,`' that all men might believe,
is not natural life or light, but of the divine nature, which is above nature;
for '`in him was life,
and the life was the light of men,`' and he is the salvation to the ends of the earth.
And in this thou hast showed thy ignorance,
and dost not preach that which people are to believe in.

[.discourse-part]
_Principle._ Thou sayst, '`the ministers of Christ may seek what they shall have by the year,
and are not to go up and down to towns, and eat and drink what is before them,
as those did.`' Luke 10:7.

[.discourse-part]
_Answer._ We do believe such apostate ministers from the
doctrine of Christ and his apostles as you are,
who have thrown aside the doctrine of Christ, and trampled it under your feet,
and set up yourselves in great benefices, who live in a town,
do not go up and down to eat and drink such things as are set down before them;
but how are you then those that Christ said he would be with to the end of the world?
and how do you then observe all things that he hath commanded?
For '`Lo I am with you to the end of the world,`'
and they were to observe all things that were commanded.
And how are you here out of Christ`'s doctrine?
And are you not the wolves among the sheep, with sheep`'s clothing, deceiving the world,
but not the sheep?
And how are you them that Christ said were to go into all nations?
And '`lo I am with you to the end of the world;`'
and this is not your work as you say,
and so you are judged to be out of the apostles`' practices and Christ`'s doctrine.

[.discourse-part]
_Principle._ Thou sayst '`that in 1 Cor. 9:14. is meant of natural food,
which is to be obtained by civil laws,`' and '`our
declaring against such shepherds as in Isa.
lvi. doth not touch thee,`' and '`that thou hast received the gospel
from the epistles of Paul,`' and '`that thou owns not revelations,
tremblings, and quakings.`'

[.discourse-part]
_Answer._ The saints, and the ministers of Christ did not, by civil laws,
or the laws of the nation, get maintenance,
neither doth the scripture thou brings say they did.
Read it over again, and let all sober people read it.
And the gospel thou hast received from the epistles,
the epistles do not give thee the power of God, and the gospel is the power of God:
here thou hast showed thy ministry is of the letter, and of man, and not from God,
for the gospel is the power of God to salvation to every one that believes,
preached to Abraham before the epistles were written; and this gospel is everlasting,
not received from epistles.
And Paul was an apostle, not of men, nor by men, but by the revelation of Jesus Christ;
and thou that denies revelation denies the son of God,
and the grace that was brought by revelation, and denies knowing the Father;
for none know the Father, but they to whom the son reveals him.
And thou hast denied the fear of God, and the Lord`'s secrets;
'`for the secrets of the Lord are with them that fear him,`' they are revealed to them.
And thou that denies trembling and quaking hast denied thy salvation,
and the apostle`'s doctrine, and denied thyself to be a minister of Christ;
for the apostle says,
'`work out your salvation with fear and trembling,`' and thou that denies trembling,
denies salvation that is wrought out by it.
And Isa.
Ivi. doth judge thee, for thou art one that seeks thy gain from thy quarter,
a greedy dumb dog, that can never have enough, as witness thy eggs,
and how thou didst hale before the justice for not paying of them.

[.discourse-part]
_Principle._ Thou sayst, '`thou dost not uphold such as Mic.
iii. speaks of.`'

[.discourse-part]
_Answer._ Art thou not one that divines for money, that prophesies and preaches for money?
and if people will not put into thy mouth, thou prepares war against them;
as I said before, witness thy eggs, and they that give thee eggs,
thou wilt say they are good churchmen, and thus they stop thy mouth with eggs,
but if not, thou hast them before magistrates.

[.discourse-part]
_Principle._ Thou sayst, '`If any of the church, joined to me, leave me because I take maintenance,
it will be their sin.`'

[.discourse-part]
_Answer._ The true prophets left the false prophets, and the true apostles did the false,
such as taught for covetousness, and means, and declared against them;
and such as go out from the spirit go into the earth, and such as come to the spirit,
come from the earth: and teaching for gifts, rewards and hire, as thou Tombes dost,
upon whom is thy old garment.

[.discourse-part]
_Principle._ Thou sayst, '`thou denies an absolute degree of perfection in this life.`'

[.discourse-part]
_Answer._ In this thou hast denied the work of the ministry, which is for the perfecting;
and do none come to perfection in a degree of perfection?
do none come to Christ who is perfect?
do none come to the spirit?
Who come to the spirit, come to be perfect;
for who come to the spirit and to Christ come to that which is perfect;
they who come to the kingdom of heaven in them, come to be perfect, yea,
to be perfect men, and that is above any degree,
and thus thou art blind and ignorant of that which the scriptures declare.

[.discourse-part]
_Principle._ '`Thou wouldst have it proved that they are false
prophets that declare the true prophets`' words.`'

[.discourse-part]
_Answer._ They that make merchandise of the words of the true prophets, are the beast,
false prophets, and great whore, but they that speak freely as they have received,
are the true prophets and true apostles,
and such in all ages were distinct from each other, known by the spirit of the Lord:
they who had received from the Lord what they spoke and declared freely,
and they who had got the saints`' words, and had not received them from the Lord,
but spake them forth for money, these were distinct one from another.
