[#ch-108.style-blurb, short="A Form of Sound Words"]
== A paper I have received, the title of which is, '`A form of Sound Words, containing the first principles of the oracles of God, framed for the use and benefit of the inhabitants of two adjacent parishes in the county of Nottingham.`' Their principles in it as followeth.

[.discourse-part]
_Principle._ '`When for the time you ought to be teachers, you have need that one teach you again,
which are the first principles.`'

[.discourse-part]
_Answer._ How can you teach the first principle of pure religion,
when you deny the light that Christ hath enlightened every man
that comes into the world with?`' And this may whole England witness,
and so your doctrines that you have taught them, and commandments, are such as perish;
being not men sent of God, you have not profited the people at all.

[.discourse-part]
_Principle._ And you say,
'`False teachers this age is too full of:`' and '`that you may henceforth be no more
children tossed to and fro,`' and you entreat to '`accept a word from us your ministers;
for what profiteth a man to gain the whole world and lose his own soul.`'

[.discourse-part]
_Answer._ Who have tossed people more up and down than you,
and carried them about with your windy doctrines?
And so the world have been too full of you, the multitudes of the false teachers,
since the days of the apostles.
Who are more for gaining the whole world than you, that call yourselves ministers?
have not and do not your fruits declare it to the whole nation?
In prisons, there lie your fruits,
for where may people see the priests`' fruits but in prisons?
And how your congregations are all on heaps,
when any come in the name of the Lord amongst them! and you have
showed that your exhortation hath not profited the people at all.

[.discourse-part]
_Principle._ '`We entreat you to take heed of that dangerous deceit,
in hoping to be saved by your own works, or in any thing in yourselves.`'

[.discourse-part]
_Answer._ He that believes hath ceased from his own works, so is not saved by them,
and he that believes is saved, and this belief is within him, in Christ.
And the ingrafted word is able to save the soul,
and Christ the saviour is revealed and manifested within.

[.discourse-part]
_Principle._ '`Out of the holy scriptures, Old and New Testament, which are the word of God,
we may learn the true knowledge of God.`'

[.discourse-part]
_Answer._ The Jews had scriptures, and did not know God nor Christ, nor did know themselves.
And the scriptures are not the word, but the words of God, and so you teach parishes,
and your children to lie, as you may read in Exodus, '`God spake all these words,
and said.`' And '`whosoever shall add to these words,`' Revelations.
And Christ saith,
'`my words.`' And would you make people believe the scriptures were but a word,
when they say they are words?
And Christ is the word, as in the Revelation.
And so that which brings to the knowledge of God is the spirit; and the son reveals him,
Christ Jesus,
who is the light which '`doth enlighten every man that comes into the
world,`' and every man that comes into the world receiving the light,
Christ will reveal the Father to him.

[.discourse-part]
_Principle._ '`There are three persons, Father, son, and holy ghost.
And we entreat you to take heed of the natural Popish conceit.`'

[.discourse-part]
_Answer._ The word three persons is the natural Popish conceit,
which is out of thy father the pope`'s canon-books, where thou hast learned it.
But Father, son, and holy ghost, that is sound scripture;
but thou canst not take it as it speaks, but thou must add three persons to it,
so brings the plague upon thee.

[.discourse-part]
_Principle._ '`There are many that have share in the salvation purchased by Christ.`'

[.discourse-part]
_Answer._ Christ was the offering for the sin of the whole world.
And he gave his body for the life of the whole world.
And he came a light into the world,
and doth enlighten every man that comes into the world;
he that died for the sin of the whole world, was an offering for the sin of the world,
that all through this light might believe.
And so many are condemned for not believing,
that which they should believe in condemns them.

[.discourse-part]
_Principle._ '`God works faith in us inwardly by his spirit, and outwardly by his word.`'

[.discourse-part]
_Answer._ Here thou goest about to make the spirit and the word not one;
is not the word spiritual?
and is not Christ called the word, who is the author of the faith,
the mystery of which is held in a pure conscience?
And is not this word of faith in the heart?

[.discourse-part]
_Principle._ '`The whole word of God in general is summed up in the apostles`' creed.`'

[.discourse-part]
_Answer._ Where hast thou got the word creed, but out of the mass-book, and pope`'s canon-book?
not out of the apostles`' epistles.
And the apostles`' epistles, and the saints`' writings, declare of the word,
and say it was in the beginning, and say the letter kills; for the Jews had the letter,
and did not find the word in it, but stood against it; and you have the letter,
the apostles`' words, but you do not find the word in it: it speaks of the word,
the word was in the beginning, and in the heart, before the words.

[.discourse-part]
_Principle._ '`Brethren, be perfect, be of good comfort;
no man can be made free from sin in this life; God`'s children have sin in them.`'

[.discourse-part]
_Answer._ The devil`'s doctrine, and his ministers`' doctrine, is,
that men shall not be perfect while they are upon earth;
but you say they must be perfect, and yet must have sin, that makes them imperfect.
And the children of God that were born of God, did not commit sin, neither could they,
because the seed of God remained in them, and they were made free from sin,
and had put off the body of sin, as in Romans the vi.
and John the iii.

[.discourse-part]
_Principle._ '`No man is able to keep the commands of God perfectly;
we break them daily in thought, word, and deed.
And in all our best duties we are unprofitable servants`'

[.discourse-part]
_Answer._ Here you show that you do not love God, for he who loves God keeps his commandments,
and love fulfils them:
and in all your best duties and deeds you are but unprofitable servants,
in that we do believe you.
So your preaching and praying are unprofitable, so you,
judge yourselves out of your own mouths; singing, instructing, praying,
all are unprofitable, and you are the slothful servants,
who are reprobates to every good work.
But the saints prayed, preached, and sung in the spirit; such were profitable,
that loved God and kept his commandments, but you that do not love God,
do not keep his commandments;
so your fruits are unprofitable that keep not the commandments of God.
And there is your mark that you do not love him.

[.discourse-part]
_Principle._ '`The law is a rule for a believer`'s life; we must attend unto the sacraments.`'

[.discourse-part]
_Answer._ Christ is the end of the law for righteousness`' sake unto every one that doth believe;
so Christ is the rule who ends the law to believers;
and thy sacraments must go again to the common-prayer-book, to the mass-book;
the scripture doth not teach us those words, as sacrament and creed,
but the old mass-book; thou art running to it, and so leaving the scriptures.
So thou art judged with the life of God.

[.discourse-part]
_Principle._ '`Who are ordained lawfully, are called to the ministry.`'

[.discourse-part]
_Answer._ Your ordination and call is by men, contrary to the apostles and Christ, who saith,
'`not by man nor of man,`' and Christ said,
'`pray to the Father that he may send labourers into the vineyard,`' and such you persecute.
And thou sayst there are two sacraments in the gospel,
but the apostles tell us of no such thing, but the pope in his mass-book.

[.discourse-part]
_Principle._ '`We may not learn to seek for happiness in this life;
these words I command thee this day shall be in thy heart, to teach thy children,
and to talk of them in thy house.`'

[.discourse-part]
_Answer._ These words have spoken long in your hearts,
therefore have you led the world into wickedness;
but the children of God find happiness in this life,
being changed from the old nature in this life, they find God, and Christ,
and find rest for their souls.
And who is in Christ is a new creature, and such hath happiness.

[.discourse-part]
_Principle._ '`This form of sound words is taken out of the
best and soundest catechisms that we could meet withal,
and our mouth is opened boldly.`'

[.discourse-part]
_Answer._ This is your form of unsound words, and if this be the best stuff you can find,
out of your best catechisms, it is pitiful, dirty, dark stuff,
and you had better have kept your mouth shut.
If these be your catechisms, they are for the fire;
the children of light who are come into the light
comprehend and see the catechisms and you both,
and you are to be catechized;
and if you will but read over the priests`' and professors`' catechism,
you may learn something out of it.
