[#ch-109.style-blurb, short="Dispute in Branspirth Castle"]
== This is a relation of some particulars and principles, affirmed by some of the priests of Bishopric, at a public dispute in Branspirth Castle upon the 21st day of the 7th month, 1658.

[.discourse-part]
_Principle._ Josias Dorker affirmed,
'`that immediate revelation or inspiration is not to be expected in these days.`'

[.discourse-part]
_Answer._ Then you are from the spirit, that say so, the spirit of God which doth reveal;
you are they that have ravened, the false prophets and antichrists,
that have inwardly ravened from the spirit of God, having the sheep`'s clothing,
and in the darkness; the king of the bottomless pit hath been your king,
for the King of kings, and Lord of lords is not known but by revelation,
for none know the son, but the Father, and he to whom he doth reveal him;
which shows that you are out of the fear of God, for where the fear of God is,
God reveals his secrets.
But the fear of God is now witnessed, and the son of God is now witnessed,
and revelations are now witnessed, in our days as they were in the apostles`',
but not amongst you, who have inwardly ravened from the spirit of God,
who have apostatized from the apostles.

[.discourse-part]
_Principle._ '`That it is needless, and also diabolical, (that is to say,
devilish,) to expect any such thing now.`'

[.discourse-part]
_Answer._ And so you are in the diabolical, devilish spirit, that expect not that now,
which was in the days of the apostles, and you are out of the fear of God;
and the spirit which doth reveal, and the son you know not, who said to the Pharisees,
that knew him not, '`they were of the devil,`' and so he is known by revelation.

[.discourse-part]
_Principle._ '`That they had the scripture and the gospel, (as he confessed,) not from God,
but from men.`'

[.discourse-part]
_Answer._ You nor any man upon the earth, know not the scriptures,
but as you know them from God and the spirit, as they did that gave them forth,
who learned them of God; and so, he who knows scripture,
must know revelation and the gospel, for they are not known,
but by the spirit which gave them forth.

[.discourse-part]
_Principle._ '`That the bible was the gospel.`'

[.discourse-part]
_Answer._ The gospel is the power of God, which was before the scripture was written,
preached to Abraham.
And many may have the bible, but not the power of God, the gospel,
which is glad tidings to the salvation of every one that believes.
And the scripture is a testification of the gospel, of the glad tidings,
and it is not called the power of God,
but Christ and the gospel are called the power of God; and many had scripture,
but would not come to Christ, the power of God, and so not to the gospel.

[.discourse-part]
_Principle._ '`That the flesh of Christ is not in them.`'

[.discourse-part]
_Answer._ The saints eat his flesh, and they that eat his flesh, have it within them.

[.discourse-part]
_Principle._ '`That Christ had, and hath a carnal body.`'

[.discourse-part]
_Answer._ Christ`'s body is not carnal, but spiritual; the first man was of the earth, earthly,
the second man is the Lord from heaven, heavenly, and is a glorious body,
and the saints are made like unto his glorious body: therefore,
the first state is carnal, the second glorious; so there is a natural body,
and there is a spiritual body.

[.discourse-part]
_Principle._ '`That Christ is now in heaven with a carnal body.`'

[.discourse-part]
_Answer._ Carnal indeed is death, saith scripture,
and it saith that corruption must put on incorruption, and mortal, immortality;
so Christ`'s body that is in heaven is a glorious body, and not carnal, nor of the flesh,
corruptible.

[.discourse-part]
_Principle._ '`That Christ hath a carnal human body, united to his divinity.`'

[.discourse-part]
_Answer._ Carnal, human, is from the ground, the first Adam`'s body, was human, earthly,
and Christ was not from the ground,
(let all people read what thou sayst,) but he was from heaven,
his flesh came down from above, his flesh which was the meat, came down from heaven.

[.discourse-part]
_Principle._ '`That Timothy retained his ministry, not from God, but from Paul.`'

[.discourse-part]
_Answer._ Timothy did retain his ministry from God, and knew the gift,
that which he did retain from Paul was not as man,
but Timothy was in the faith which Christ was the author of, and he had the gift,
and every good and perfect gift comes from God, and this was not by man, nor of man.

[.discourse-part]
_Principle._ '`That there is as much difference between a spirit and a body,
as there is between light and darkness.`'

[.discourse-part]
_Answer._ Christ`'s body is spiritual, and that which is spiritual,
does not differ from the spirit; and so there is a spiritual body,
and there is a natural body, and there is a spiritual man, and there is a natural man,
and each hath their body.

[.discourse-part]
_Principle._ Henry Liver said,
'`that they knew no such thing as prophesying by
immediate revelation or inspiration in these days.`'

[.discourse-part]
_Answer._ Then thou never knew the scriptures, for none know the scripture, as I said before,
but by the spirit of revelation, which doth reveal the words; the spirit of prophecy,
lets see into the words, and he that hath not the spirit of Christ is none of his;
and he that hath the spirit of Christ hath immediate revelation, and prophecy.
And the spirit of God is immediate, and it doth reveal; and the gospel,
which is the power of God, is immediate.

[.discourse-part]
_Principle._ Richard Frankling said, '`they had it by scripture.`'

[.discourse-part]
_Answer._ And it was the spirit that brought them to give forth scripture,
which things of God were revealed to them by it;
and the scripture does not reveal the spirit, but the spirit the scripture.

[.discourse-part]
_Principle._ '`That the light which lighteth every man was not sufficient to lead up to Christ.`'

[.discourse-part]
_Answer._ The light, Christ, that doth enlighten every man that comes into the world,
that which he doth enlighten every one withal, which they are to believe in,
is sufficient to lead up to Christ; for they that believe in the light,
become the children of light, they pass from death to life, from darkness to light,
and come out of condemnation, and shall never die, and so it is sufficient:
so that he that doth not believe in the light, by it is condemned,
for '`this is the condemnation, that light is come into the world,
and men love the darkness rather than the light,
because their deeds are evil.`' And so you and they
that love the darkness rather than the light,
because your deeds are evil, and will not come to it, because it will reprove you,
are they that live in the form of godliness, and deny the power, and teach people to say,
that the light is not sufficient that every man that
comes into the world is lighted with,
that all might believe; who are not condemned by; and the light that comes from him,
is sufficient to lead up to him.

[.discourse-part]
_Principle._ '`That grace was not conveyed from the Lord to any man,
without the ordinary outward means.`'

[.discourse-part]
_Answer._ The grace of God hath appeared to all men, which teacheth the saints,
and the grace is brought by the revelation of Jesus, as saith Peter by revelation,
and the grace is the gift of God, and not attained by outward means, by man`'s will;
and they that turn the grace of God that hath appeared into lasciviousness,
are they that deny the Lord that bought them, who go from the grace,
which is the saints`' teacher, which brings salvation.

[.discourse-part]
_Principle._ '`That the scriptures are that only which they are to have recourse unto,
to inform the minds of people from.`'

[.discourse-part]
_Answer._ Before the scripture was written or given forth, Abraham, Enoch,
and Abel had that which informed their minds, and let them see Christ;
and the Jews had scripture, and knew not Christ, they had the testification,
and did not come to him they testified of, and so had not life.
So that which is to inform the minds of all people is the spirit
and the light which Christ hath enlightened them with;
and their ears and eyes must be open to the spirit of God in themselves,
before they hear his voice, which spirit informs their minds,
and then they shall come to know the operation of the spirit,
for many may have the scriptures, and not know that.
And that which is to teach people is the grace of God, Christ, the light and life,
and that it is which informs the mind to know scripture.

[.discourse-part]
_Principle._ Priest Dorker said,
'`that the word of God was the ordinary outward means,`'
and '`that the scripture is the word,`' they all affirmed.

[.discourse-part]
_Answer._ The word of God is not outward nor ordinary, but extraordinary,
it is that which lives, abides, and endures forever;
and the scriptures are to be fulfilled, and that which doth fulfill them is the word;
and the scriptures of truth learned of God, the Father of truth, are the words of God,
not a word.
'`God spake all these words, and said,`' in Exodus; and '`my words,`' saith Christ;
and '`whosoever shall add to-these words,`' saith John in the Revelations:
and so the words are the scriptures of truth, that cannot be broken,
Christ the word fulfils them, who was in the beginning,
before the words were spoken forth, who is and remains to the end of words,
who fulfils them, in whom they end.
