[#ch-110.style-blurb, short="Daniel Roberts"]
== Daniel Roberts, teacher to the Baptists at Reading, in Berkshire, did affirm,

[.discourse-part]
P+++.+++ '`That baptism of water, that is to say, elementary water, doth wash away sin.`'

[.discourse-part]
A+++.+++ Here thou puts water in the room of Christ`'s blood, which cleanseth from all sin,
and what need of that, if water doth it; outward water can but wash the outward.

[.discourse-part]
P+++.+++ '`That God had committed all judgment to the scriptures.`'

[.discourse-part]
A+++.+++ That is contrary to the apostle, who saith,
'`God will judge the world by the man Christ Jesus,
according to the gospel,`' and that is the power;
and '`all judgment is committed to the son.`' Mark, to the son;
and '`the saints shall judge the world,`' and he is in them.

[.discourse-part]
P+++.+++ '`That the new covenant is the words of Christ and the apostles,
and every one that hath the Bible in his house, hath the new covenant.`'

[.discourse-part]
A+++.+++ The new covenant is Christ the scriptures speak of,
and the Jews had the scriptures that stood against the covenant,
and many may have the Bible, and not in the thing it speaks of.

[.discourse-part]
P+++.+++ '`Another Baptist said at the same time, if they had not had scriptures,
they had not known how to walk nor order their conversation.`'

[.discourse-part]
A+++.+++ How knew those to order their conversation, and walk, before scripture was given forth?
The life which led them to give forth the scripture,
did order them to walk acceptable to him.
And the Pharisees had the scriptures given forth from the life,
but being out of the life, their conversations were not ordered by it.

[.discourse-part]
P+++.+++ Daniel Roberts affirmed,
'`that he knew no other spirit than what was in the scripture,
and that he carried it in his pocket.`'

[.discourse-part]
A+++.+++ The spirit is not in the scriptures, but in them that gave it forth,
and that the scriptures testify of.
Many got the scriptures, but wanted that which gave them forth,
and so were not in unity with the scriptures, nor with one another, nor with God;
and in all Christendom, so called, this is wanting, the unity of the spirit,
in which is the bond of peace, for many have the words, but not the spirit.
