[#ch-111.style-blurb, short="Timothy Trever"]
== In answer to Timothy Trever`'s principles, propounded by way of queries.

[.discourse-part]
P+++.+++ '`That the light in every man, as in every man,
teacheth not the way to the kingdom of God, nor giveth the hope of eternal life.`'

[.discourse-part]
A+++.+++ The light in every man which doth enlighten every man,
doth teach the way to the kingdom of God,
and no other way it teacheth but to the kingdom; and though men hate it,
and will not come to it, because their deeds are evil,
yet that is the teacher in all men that gives them the sense of transgression,
and an understanding of reproof, and if they come to that, they are reproved,
and there is the kingdom in men;
and that is it which lets all men see the Most High reigning,
and shall make every tongue confess Christ to the glory of God;
and it is that which gives every man assurance,
that God hath raised Christ from the dead, who hath enlightened them,
and that is it which gives every man the hope of eternal life,
and in the light it is received.

[.discourse-part]
P+++.+++ '`That the seed to whom the promise of salvation is made, are, or have been sinners.`'

[.discourse-part]
A+++.+++ The promise of God is to the seed,
which hath been laden as a cart with sheaves by the sinner, which seed is the hope,
Christ, that purifies even as God is pure;
and here is the creature come to know its liberty amongst the sons of God.
And the seed, Christ, never sinned in the male nor in the female,
in the Jews nor in the Gentiles,
and of this mystery were the great high professors ignorant,
that stood at a distance from the Gentiles, so that Christ had no room among them,
but in the stable, in the manger, though they talked of him with their lips:
and such Christ calls graves and sepulchres, and whited walls;
and the wall is not the seed, nor the sepulchre, nor the grave, but the seed is Christ;
so this promise is not unto seeds, as many, but to one, the seed, which is Christ.

[.discourse-part]
P+++.+++ '`That there is no man doth possess the kingdom of God,
whilst he is in the mortal body.`'

[.discourse-part]
A+++.+++ In this thou art like Nebuchadnezzar, who must graze like the ox, thy mouth downward,
who knows not the Most High ruling in the children of men; and God will dwell in you,
and walk in you, and where God dwells and walks in men, they are his temples,
which are holy; there is his kingdom, his power, his authority,
and the tabernacle of God is with men, and he will dwell in them, and walk in them;
and this is the state of thousands that are in the new covenant,
that know the power of God, of the Most High, his law put in their minds and hearts;
and they that do not know that they are the temples of God, and God dwelling in them,
and walking in them, are worse than the Corinthians.

[.discourse-part]
P+++.+++ '`That he that doth not preach the death and resurrection, and the man Christ Jesus,
that rose from the dead at Jerusalem, preacheth not the gospel,
whatsoever else he doth declare.`'

[.discourse-part]
A+++.+++ He that preacheth Christ, must preach that Christ that died at Jerusalem,
for he is the same today, yesterday, and forever,
the lamb slain from the foundation of the world; which seed, Christ,
breaks the serpent`'s head, and destroys death, and the devil,
that went out of the truth; and death being destroyed, the captivated one comes out,
by the power which is the gospel, and the prisoner of hope shows himself forth,
and then the covenant of light and life is felt, and peace with God.
But the reprobate, devil, death and destruction, antichrist, the beast and false prophet,
may talk of Christ without, and he be not felt within; such are then the reprobates.
And as to thy saying, the seed is not in all men, first know it in thyself;
he is not in the man of sin, that is to be destroyed, who hath blinded thy mind,
and hath taken possession of thy heart; and so first judge thyself.

[.discourse-part]
P+++.+++ '`He that doth not expect the resurrection from the dead, of his own person,
as Christ rose from the dead, literally understood,
hath no true hope of eternal life born in his understanding.`'

[.discourse-part]
A+++.+++ The saints`' rising is in Christ, and he is the resurrection; they are of his flesh,
and of his bone, and of his spirit;
and the saints are of the flesh of Christ that saw no corruption, and of his bone,
and have the hope of eternal life promised of the Father.
And now the flesh of Christ, the Jews did not know,
that were the idolaters and fornicators;
for Christ according to the flesh was of Abraham,
who came out of all that idolatry and generation of fornicators,
and in this the saints rise, live, and remain with Christ forever,
and such come to know the resurrection of the just and unjust,
according to the scriptures, the one to eternal life, and the other to condemnation.

[.discourse-part]
P+++.+++ '`That Christ by his death overcame him that had the power of death,
and thereby made way to life.`'

[.discourse-part]
A+++.+++ But how is death overcome in thee, when thou dost not see the kingdom of God in thee,
and sayst it shall not be while men are in their mortal bodies,
and how short art thou of the holy ghost, and the power, and the joy,
and the righteousness, which the kingdom stands in!
And Christ who overcame death, is the life, and the way to God, the Father of life,
which doth enlighten every man that cometh into the world,
that by the light they might see it and believe in it,
that they might be children of light, and come to the light of life;
and they that do not believe in it, are condemned by the light.

[.discourse-part]
P+++.+++ '`That the unchangeableness of God`'s purpose, of his love,
is the only ground of man`'s obedience and stability, or continuance in obedience,
not man`'s obedience the ground of his stability.`'

[.discourse-part]
A+++.+++ Man`'s stability is Christ, the light, the life,
the foundation of God that stands sure, the hope that remaineth in him,
the faith given to him of God,
in which the seed comes to be known in the male and in the female,
the son of God who abideth in the house forever, who is the heir of the promise;
and there the unchangeableness of God is known, he that doth not change is seen,
that has appeared, which cannot be shaken, that seeth an end of all changeable things,
and variableness, and turnings; and here the obedience is felt.

[.discourse-part]
P+++.+++ '`God hath ordained to eternal life every one that is
or shall be saved before they had a being in this world,
but none come to possession of this salvation but through the obedience of the spirit.`'

[.discourse-part]
A+++.+++ The ground of man`'s belief and obedience is Christ,
who doth enlighten him to the intent that he might believe and obey the truth,
and he who knows the seed, knows the election, before the world was made.

[.discourse-part]
P+++.+++ '`That the seed of Israel are men, and not only something in man;
that the seed of the serpent are men, and not only something in man.`'

[.discourse-part]
A+++.+++ If the seed of Israel be men,
then by thy account the seed of Israel is the seed of the serpent, for they are men;
and Christ, who came to destroy the work of the devil,
and him that hath the power of death, is said to have come to destroy all Israel,
and all men upon the earth.
But thou errs in thy judgment, and in thy understanding;
for I know it is the seed of the serpent that speaks in thee,
that puts no difference between the precious and the vile.
And when Israel thought Christ had called them serpents,
many of them were converted to the faith; their outward creatures were not destroyed.
Thou talks foolishly, and art given up to the devil`'s power,
who works wickedness and mischief.
And if men are the serpent`'s seed, as thou dost say, who shall be saved,
for the serpent and his seed must be destroyed?
and if men are the seed of the serpent,
then must the seed of the serpent obey the spirit, and must not the spirit destroy him,
and the brightness and breath of the Lord consume him?
And it is men that are captivated by the seed of the serpent,
whose lives Christ came to save, and redeem, and turn from the power of Satan, to God.
And thou must be thrashed, and feel the weight of the Lord`'s hand,
before thou art humbled.
And what hast thou to do to talk of ordination before man had a being in the world,
and would make men to be like thyself, and say they are the serpent`'s seed,
for man is not so, as he is man.
And we and thousands witness election and salvation
before the foundation of the world was laid,
and are come into that which comprehends time and being, which are since time;
in which power the elect reigns, where salvation is known.

[.discourse-part]
P+++.+++ '`The woman that the serpent deceived, her seed breaks the serpent`'s dominion.`'

[.discourse-part]
A+++.+++ The seed of the woman doth bruise the serpent`'s head wherever he is found,
in any male or female, that Christ may rise in the male and in the female;
and this seed is atop of thy head, and thou hast no power but to reach to his heel,
and thou art in the house of darkness, and the seed is yet in Egypt, not come forth yet;
and there is a strong man must bow himself, and they that keep the house must tremble,
that have kept thy heart from the Lord God, and have carried it a whoring abroad.
And a stronger he is, than he that keeps the house,
that spoils his goods and takes possession, who comes to rule, and will rule and reign.

[.discourse-part]
P+++.+++ '`That the manifestation of the spirit is given
to every man in the church to profit withal,
and not to every man in the world.`'

[.discourse-part]
A+++.+++ The manifestation is given to every man to profit withal, without distinction.
'`I will pour out my spirit upon all flesh,`' for '`the
spirit of truth shall lead the saints into all truth,
and he shall reprove the world,`' and that which doth reprove the world,
is manifest to the world.

[.discourse-part]
P+++.+++ '`That no man hath received a measure of the spirit of Christ,
but such as believe in Christ,
and that no man doth believe in Christ but such as Christ is revealed to in time,
and that he is revealed to none, but by the manifestation of his spirit.`'

[.discourse-part]
A+++.+++ The true believers that believe in Christ the revelation,
knew him in time and out of time, and the unbelievers are reproved.

[.discourse-part]
P+++.+++ '`Which of the people of God, prophets, or apostles,
did direct all people to a true light within them for their instruction and guide,
before the manifestation of the spirit unto them,
or the work of regeneration wrought in them?`'

[.discourse-part]
A+++.+++ The prophet said,
'`I will give him for a covenant of light unto the Gentiles,`' and '`a new covenant
with the house of Israel and with the house of Judah will I make,
and write my law in their hearts,
and put them into their minds;`' and this was in general
directed to them before they were converted and regenerated,
and this light was to enlighten the Gentiles,
whereby the prisoners should come out of the pit where there is no water;
and the new covenant was held to the Jews before they were converted,
that all may see who can read but the outward letter;
and the apostle was sent to turn people from darkness to light;
and John the highest prophet born of woman, said,
'`that was true light which doth enlighten every man that
cometh into the world,`' which he was a witness of;
and '`the light shined in the darkness,
and the darkness comprehended it not.`' And Christ directed the Pharisees
which were not converted to the kingdom of heaven in them.
Read the pearl, and the lost piece of silver; read the talent,
and the pearl hid in the field; read the slothful servant, his talent,
and then read thyself, how blind and ignorant thou art in the things of God,
and be silent, that thou mayst come to know the Lord, and his fear,
that the witness of God may stir in thee,
that thou mayst do righteously in the sight of God and men,
lest the judgment of God be upon thy head;
for thou art manifest to all that are in the light.
