[#scotland.style-blurb, short="Doctrines and Principles of the Priests of Scotland"]
== The Doctrines and Principles of the Priests of Scotland, Contrary to the Doctrine of Christ and the Apostles.

[.heading-continuation-blurb]
Here all may see, the priests of Scotland, and their church,
and their persecution against the saints, and lambs, servants, and children of God,
whom the Lord moved to go among them,
to visit the seed of God in that dark wilderness country,
who have been as sheep among wolves.

[.heading-continuation-blurb]
Also, how pure religion is turned upside down, and vain religion got in its place.
And the pure doctrine of Christ and the apostles, which saith, '`entertain strangers,
love enemies,`' is lost among you: instead of entertaining strangers, and loving enemies,
they imprison and persecute, and have made their church unsavoury.
And the teachers`' fruits declare them to be false,
who were wrestlers against flesh and blood, and strikers at creatures,
which Christ and the apostles did not.

[.heading-continuation-blurb]
George Weare, John Hart, William Grey, William Lowry, William Mitchell,
and Richard Isamaell.

[.numbered-group]
====

[.numbered]
_First,_ these Presbyterian priests of Scotland,
who excommunicate and put out of the synagogues, know not the Father and the son,
John 16. so are no true christians;
for how can they be true christians that know not the son of God, nor the Father?

[.numbered]
_Secondly,_ they are no ministers of Christ; for Christ saith,
'`when they curse, bless ye;`'
so they are out of Christ`'s doctrine and teaching, not blessing,
but cursing, and giving forth curses,
and '`all the people must say amen to their curses.`'

[.numbered]
_Thirdly,_ they are out of the apostle`'s doctrine, who saith,
'`Bless and curse not;`' Rom 12:14. so are no ministers of Christ,
that curse and give forth their curses to the people to say amen to them:
and here they are shut out of the apostle`'s doctrine,
and Christ`'s. All people mark and take notice, they are those that curse,
but the apostle saith, '`Bless and curse not;`' these are the cursers and not blessers,
that excommunicate you out of the synagogues.

====

[.offset.emphasized]
Hugh Archball, priest of Stravan; John Hume, priest of Lesmahaga; William Hambleton,
priest of Glasford; James Durram, priest of Glasgow; John Castaires, priest of Glasgow;
Francis Ard, priest of Discert; Matthew Mackel, priest of Bothell; Henry Foreside,
priest of Lingiah; James Nesmith, priest of Hambleton; Robert Semple,
priest of Lesmahaga; Thomas Garony, priest of Edenbrough; John Burnet,
priest of Hilbride.
