[.style-blurb, short="Hugh Archball"]
== Hugh Archball, priest of Stravan, in Anandale. These are his principles.

[.discourse-part]
_Principle._ '`That Christ hath not enlightened every one that comes into the world.`'

[.discourse-part]
_Answer._ Which is contrary to John`'s doctrine. John 1:9.

[.discourse-part]
_Principle._ '`That Christ doth enlighten none but those that do receive him.`'

[.discourse-part]
_Answer._ Contrary to John iii.
speaking of them that hate the light, and are enlightened, and will not come to it,
because the light will reprove them; so he that hates the light is enlightened,
and will not receive Christ.

[.discourse-part]
_Principle._ '`That it is blasphemy to say,
that the true light doth enlighten and condemn the world.`'

[.discourse-part]
_Answer._ Contrary to John 1:9. and 3:19. that saith,
'`This is the true light that lighteth every man that cometh into
the world.`' And '`this is the condemnation of the world,
that light is come into the world.`'

[.discourse-part]
_Principle._ '`To say, that which reproves for sin is from heaven, is blasphemy.`'

[.discourse-part]
_Answer._ Contrary to John 16:8. who saith it is the spirit that reproves,
which comes from the Father and the son, which is from heaven.

[.discourse-part]
_Principle._ '`He crieth up a natural light, as sun, moon, and stars,
and the light of Christ was before these were made, and saith, '`it is blasphemy to say,
they that did the things contained in the law,
were blessed in the deed;`' and the apostle said,
'`the doers of the law were justified;`' and said,
'`he would leave the Friends that spake to him, to the mercy of the people.`'

[.discourse-part]
_Answer._ Upon which they struck bitterly with books, fists, and stones, to destroy,
but some moderate people and soldiers stayed the persecution.
