[.style-blurb, short="John Hume"]
== John Hume, Priest of Lesmahaga. His Principles as follows, who got into a steeple-house, and shut the door upon him; thus he taught the people.

[.discourse-part]
_Principle._ '`That which was to be known of God, was manifest by the things that are created.`'

[.discourse-part]
_Answer._ Contrary to the apostle`'s doctrine, Rom. 1:19.
'`For whatsoever may be known of God is manifest in them;
for the invisible things of him from the creation of the world are clearly seen,
being understood by the things that are made, even his eternal power and godhead,
so that they are without excuse.`' So with that of God in them
they know the invisible things from the foundation of the world,
and with that they see the godhead.

[.discourse-part]
_Principle._
'`That God was to be known by the things that were made, as the sun, moon, and stars.`'

[.discourse-part]
_Answer._ But Jesus Christ said, Matt. 11:27. '`No man knows the Father but the son,
and he to whomsoever the son will reveal him,`' and the heathens know not God,
nor had the Jews seen his shape.
And his servants and workmen did throw water, stones, and lime, and persecuted,
and dirtied, and abused the people called Quakers,
and threw a pan full of water on a soldier`'s neck,
and he the said priest never reproved them;
and these are the fruits of him and his own family, instead of gravity:
well may the whole parish be out of order, when his own family is thus.
So he is one that is reproved by the apostle`'s doctrine, 1 Tim.
iii. who saith, '`If you cannot rule your own family,
how can you take care for the church of God?`'
