[.style-blurb, short="Henry Foreside"]
== Henry Foreside, priest of the parish of Lingiah in Dunbartonshire, said in his preaching to the people,

[.discourse-part]
_Principle._ '`They had christian zeal they would stone them whom they call Quakers.`'

[.discourse-part]
_Answer._ It is the blind zeal that stones, not the zeal of the christian,
that has the life of Christ; for the christian zeal is to pray for them that persecute, Matt. 5:44.
and not to stone them; and to love enemies.
It was the Jews`' zeal that took up stones to stone Christ, John 8:59.
they stoned Stephen, Acts 7:5. 8. and stoned the apostles, Acts 14:19.
In this the Presbyterians have proved
their christianity to be out of Christ and the apostles.

[.discourse-part]
_Principle._ '`If Paul and the rest of the apostles had been alive,
they would have stoned the Quakers.`'

[.discourse-part]
_Answer._ Here all may see his work to be the work of the envious man in Cain`'s way, Jude xi.
who would murder, and wrong the apostle, who never taught nor intended any such doctrine,
but said, '`Overcome evil with good.`' Rom. 12:21. And love bears all things. 1 Cor. 13:7.
Now see whose minister this man is, that cannot bear,
but would have them stoned, and would have the apostle as bad as himself,
which apostle said, '`Christ was his example,
who laid down his life for his enemies,`' Rom. 5:8.
who suffered the contradiction of sinners; who would render evil to no man, but,
on the contrary, says,
the Lord Jesus '`forgive them.`' Luke 23:34. And the apostle said,
they wrestled not against flesh and blood. Eph. 6:12.
But you and they that stone, do ye not wrestle against flesh and blood?
And if the apostles would have stoned,
would they not have wrestled against flesh and blood?
And if the apostles should have stoned all that were contrary to their minds,
and bid the people stone them, and told them it was christian zeal,
what work would they have made?
As the said Henry Foreside, called minister, doth.
Where would have been long suffering? Gal. 5:22.
And loving enemies? Matt. 5:44.
And where would he have had any to be converted?
And who would have been persecutors?
And who would have prayed for persecutors?
Ye may see what a pit ye are fallen into.
And how should they have convinced gainsayers, Titus 1:9. and loved them,
when they had stoned them?
And this is the Presbyterian`'s zeal of Scotland, and not christian zeal,
who would stone, and stir up his congregation to do so!
For Christ, who is clothed with zeal, Isa. 59:17. said,
'`Love your enemies,`' but ye are clothed with madness and folly.
And the apostle that was in his zeal according to knowledge, said,
'`Overcome evil with good,`' Rom.
xii, 21. and '`vengeance is the Lord`'s,
and he will repay it.`' Rom. 12:19. And love bears all things;
but his blind zeal cannot bear anything, but cries stone them out of the way,
and so wickedly and devilishly calls it christian zeal, which is false; that is,
the devil`'s zeal.
Now the apostles wrestled not against flesh and blood,
but against the powers of darkness, Eph. 6:12. but the Presbyterians,
called ministers, are striking against flesh and blood; whilst ye would stone them,
spiritual wickedness lies within you.
So ye Presbyterian priests are as a troop of robbers
that would murder in the way by consent. Hos. 6:9.
