[.style-blurb, short="James Dorranz"]
== James Dorranz, called minister of Glasgow, his principles.

[.discourse-part]
_Principle._ '`That the believer`'s, even the real godly, are not without sin in this life.`'

[.discourse-part]
_Answer._ Here is one that is charging the elect,
and laying sin to the elect that God justifies, Rom. 8:33,
that in the godly there should be sin.
Sin is out of the godly, but in the ungodly, who turn the grace of God into wantonness;
and what good doth his preaching do them,
if they must never be without sin whilst they are upon earth,
they can be but in their sin if they never preach to them.
But the scripture saith, '`He that believes is born of God,
and he that is born of God cannot sin,
because his seed remains in him,`' 1 John 3:9. But this is of another world to him,
who is called James Dorram, minister of Glasgow, minister of darkness,
who puts no difference between the children of God, and the children of the devil. 1 John 3:10.
They would have sin whilst they are upon the earth, and it is darkness,
but the apostles said they were made free from sin, Rom. 6:22.
whilst they were upon the earth.

[.discourse-part]
_Principle._ '`Christ being sinless, separates him from all others.`'

[.discourse-part]
_Answer._ Christ being separated from sinners, Heb. 7:26,
they who are in Christ are separate from sinners and sin both, 2 Cor. 6:17.
But this James Dorram hath made the offering of none effect,
Heb. 10:14, which hath perfected forever them that are sanctified.
And hath made the blood of Jesus of none effect, which cleanseth from all sin, 1 John 1:7.
And he hath made the everlasting covenant
of none effect which blots out all sins and trespasses.
And he hath made the faith of the son of God of none effect, which purifies the heart,
and gives victory over the world, Acts 15:9.
1 John 5:5. Thou dost herein preach and hold up sin,
and dost not preach it down, and yet thou sayst thou preachest not to hold it up,
and yet thou preachest they must have it whilst they are upon the earth;
here is confusion in thy tongue, Prov. 17:20. Thou shouldst have preached it down,
and if thou were a true minister,
have brought them to a church where there is neither spot nor wrinkle, nor blemish,
nor any such thing, Eph. 5:27, but your church is full of spots, and blemishes,
and wrinkles, whilst ye are preaching up zeal to stone people, and sin while they live,
as Henry Foreside and James Dorram do.

[.discourse-part]
_Principle._ '`God be thanked the scripture speaks nothing for freedom from sin and perfection.`'

[.discourse-part]
_Answer._ Thou thankest God that thou mayst live in thy sin and imperfection,
and art glad of this thy false hope; but thou art a liar,
thou art out of the truth in this, for the scripture saith they were made free from sin, Rom. 6:26.
And they preached wisdom among them that were perfect, 1 Cor. 2:6,
and he hath perfected forever them that are sanctified, Heb. 10:14.
So the scripture speaks of freedom from sin, and of perfection.

[.discourse-part]
_Principle._ '`That the condemning power of sin is taken away.`'

[.discourse-part]
_Answer._ The believer doth not sin, 1 John 5:1., 1 John 3:9,
but he that the believer overcomes commits sin, 1 John 3:8 and 1 John 5:5,
and if the believer commits sin, who overcomes the believer?
And so he that commits sin is under the condemning power of sin,
which thou and all others shall witness.

[.discourse-part]
_Principle._ '`The believer is not in sin as the unbeliever is,
he sins not as the unbeliever doth;`' and in another place he saith,
'`the law is the same to the believer that it is to the unbeliever.`'

[.discourse-part]
_Answer._ Here any may read thy confusion; but I say unto thee,
he that believeth doth not commit sin, but unbelief is sin, Rom. 11:20,
and Christ is the end of the law to every one that believes for righteousness`' sake,
Rom. 10:4, and yet thou puts both believers and unbelievers under the law.
