[#ch-117.style-blurb, short="Lodowick Simerell"]
== Lodowick Simerell, priest of the new parish of Munckland, his Principles and Doctrines.

[.discourse-part]
_Principle._ '`That it is blasphemy to say that the light in man, which reproves of sin,
is the light of God, is perfect, is the gift of God.`'

[.discourse-part]
_Answer._ Contrary to scripture, contrary to Christ`'s words,
and contrary to the apostles`' words are thy doctrine and principle,
for every gift of God is perfect, Isa. 1:17.
Isa. 49:6. John 1:3. John 4. For Christ is the gift of God,
and he will give him for a covenant of light to the Jews and Gentiles,
which doth enlighten every man that cometh into the world,
which every one that doth truth comes to, but every one that doth evil hates the light,
and will not come to the light because the light will reprove him; and so,
'`this is the condemnation of the world, that light is come into the world,
and men love darkness rather than light,
because their deeds are evil.`' So this light is perfect,
which doth reprove every man of sin, and is from above, and it is the gift of God,
and thou art blind and in darkness that comprehends it not.
And the light which doth enlighten every man that cometh into the world,
Christ Jesus the gift of God, he by whom the world was made,
this light was before any natural light was made, sun, moon, or stars;
for all things that were made, were made by the light, which came a light into the world,
that all through him might believe, for he that believes not in the light,
is condemned already, and he that does believe in the light hath the witness in himself,
to set to his seal that God is true;
and the spirit of truth that doth reprove the world is perfect, and of God.

The light which every one that cometh into the world is enlightened with,
is not conscience, for the light was before any thing was made, or conscience named:
So the light is that which exerciseth the conscience towards God, and towards man,
where it is loved, and the voice heard; but where it is hated, and the voice not heard,
the conscience is seared, and the light is their condemnation,
whose consciences are seared, which light was before conscience was.

The priest would not have thee and thou to be a single person,
and so is the man that would not endure sound words, that cannot be condemned.
Thee and thou was the language between God and his saints, and one another,
and you is to many, and thou was to one.
And this was the language between Jephtha and his daughter,
and between the saints and the kings; this shows,
that thou hast not learned the accidence nor bible,
nor art come to the form of sound words.
