[.style-blurb, short="John Castaires"]
== John Castaires, called Minister of Glasgow, his Principles.

[.discourse-part]
_Principle._ '`This is natural folks`' duty to pray to God and worship him,
although they sinfully keep themselves under a sinful
necessity to sin against God through ignorance.`'

[.discourse-part]
_Answer._ This hath been your work, to keep people in ignorance, which you may be ashamed of.
A natural man cannot worship God, for he cannot receive the things of God,
nor a sinful man, but worships the devil, for he that commits sin, serves him,
and he that serves sin, serves the devil; and worships him, John 8:34.
And Christ said the Pharisees should receive the greater damnation,
for their pretended long prayers, Matt. 23:14.
and so he did not justify them in their long prayers, but rebuked them,
and said, '`woe unto them who drew near with their lips,
when their hearts were far off,`' Isa. 29:13. And they that pray and worship God,
must pray in the spirit, 1 Corinthians 14:15, and worship in the spirit,
which the devil is out of, John 4:21.

[.discourse-part]
_Principle._ '`If the first command be in force, and if it be in force negatively,
it is also in force positively, thou shalt have me for thy God,
and oughtest to worship me; and if they pray not as they should, let them answer for it,
for it is not sin of itself.`'

[.discourse-part]
_Answer._ The children of Israel, that the commandments were given to, knew God,
but the heathen know him not: here all may see what measure thou measures with.
And further thou sayst, if they pray as they should not, yet it is not sin:
is praying as they should, and as they should not, one?
By this to call upon God with their lips, and the heart not right,
and the prayers and sacrifice of the wicked are justified, Prov.
xv. S. And if any pray as they should not, are they not condemned for it?
and if praying as they should not, be not sin, then they do as they should.

[.discourse-part]
_Principle._ '`If folks should not pray because they are incapable,
then a believer not finding himself in a good frame, may let his prayers alone.`'

[.discourse-part]
_Answer._ A believer is a babe of God, and his cry is right, his prayer is right,
and his groan is right, 1 John 5:1. And every man that cometh into the world,
being enlightened, and coming into the light which hath enlightened him, 1 John 1:7,
in that he is to watch and pray, which leads him beyond naturals,
which will be accepted in the degree, but he that hates the light,
his prayer is not accepted, but is in the hypocrisy.

[.discourse-part]
_Principle._ '`The apostle bade Simon Magus, an old witchcarl, pray;
and now is there any reason to say we are bidding folk sin, when we bid them pray,
although they be grossly ignorant?`'

[.discourse-part]
_Answer._ The apostle bade him repent, Acts 8:22, and he was sensible he had sinned:
and that which makes a man sensible of sin, brings him to pray aright,
and turns him from witchcraft;
and so thou dost put no difference between the precious and the vile, Ezek. 22:26,
the accepted and unaccepted.

And Henry Foreside, who would have had his people to stone the Quakers,
and calls it christian zeal, he would have his wall up that he might live in safety,
who murders, and would be preserved in the murderous estate,
and would have the powers of the earth to be his executioners and pack-horses;
but the Lord is opening their eyes, that they will not execute his malice,
though he is stirring up the people to do so.
So all may see this is not the work of our Lord Jesus Christ,
but the work of the murderer, and one that makes himself drunk with the blood of saints,
Rev. 17:6, till he reel again in his madness.
And Christ called them that took up stones to stone him, of their father the devil,
for doing his lust, John 8:44. And thou who would have the people to stone,
and calls it christian zeal, hast manifested thy father, and to be of the devil,
who was a murderer from the beginning.
But you are the serpents and vipers that would kill to fill the measure of your fathers,
Matt. 23:32, and persecute from city to city.
And hale out of the synagogues, John 16:2, that all the righteous blood shed,
from righteous Abel, might come upon you, Matt. 23:35.
And you are they that kill the bodies of the saints,
and are shedders of the righteous blood, (mark,
the righteous blood,) that the righteous blood might be upon you.
And Cain slew Abel, because Abel`'s sacrifice was accepted, and his not, Gen.
iv. So it is about the sacrifice and worship, ye would murder and slay:
so ye are in Cain`'s way, a company of vagabonds,
whose sacrifice God hath no respect unto.
If we were your enemies, you would not teach the people to stone us,
if ye were ministers of Christ, but love us, Matt. 5:44. and do good to us.
If the apostles should have taught the people to
stone all that were contrary to their mind,
and Christ should have taught his disciples to stone
all that were contrary to their mind,
and told them that were christian zeal;
but ye may see Christ and his apostles taught another doctrine,
'`love your enemies,`' and thou teachest to stone them, who are in scorn called Quakers,
contrary to Christ and his apostles; we do conclude it to be the doctrine of the devil,
and not the doctrine of Christ.
For the true christian zeal never taught to stone, but were stoned.

The priests called Presbyterians,
summoned some people called Quakers to come before them,
and they came into the steeple-house where they met, and James Nasmith,
priest of Hambleton, bade them remove, or else he would make them remove by club law.
And they asked the Presbyterian priests for their accusers, and Francis Ard,
one of the priests, said, they were both accusers and judges.
Now whether this be equity,
that the same that summons should be both accusers and judges;
and when they have summoned, accused, and judged,
say they will make them remove by club law: whether these be not brutes, and beasts,
and not justices?
They are not fit to judge, nor to have the name of ministers, and judges,
that will remove people by club law; and the said Quakers could not own them as judges,
nor do look on them as men of equity,
but would have had them to have given them a meeting in any place,
whereby the truth might be cleared and come to light, which they had scandalized,
which they refused; and that lawful witnesses might hear, but they did refuse,
and caused them to be put in prison by the hand of a bailiff, by name Nasmith.

And this is the authority of the Presbyterian priests,
who have summoned with club law! but it is denied by the apostle`'s doctrine, 1 Tim.
iii. they must not be strikers, nor false accusers.
These are the Presbyterian priests of Scotland`'s weapons, club law,
which is contrary to the ministers of Christ; they said,
'`we wrestle not against flesh and blood,
and they must not be strikers,`' Eph. 6:12. And
after they had violently thrust them into prison,
after their wills were satisfied with violence, they thrust them out again;
there ye may feel the spirit of wickedness.

And these Presbyterian priests petition the magistrates,
with a pretence they might not be guilty of other`'s blood;
which pretence is in their petitions, to take away their fear,
that their wicked peace might not be disturbed, not regarding their blood:
witness James Nasmith, priest, who would make them remove by club law.
So their petition is but flattery and deceit,
in pretence of not being guilty of their blood, in whose heart it is to shed blood,
as witness Henry Foreside, priest, who stirred up the people in zeal to stone them.

Those Presbyterian priests set up club law and persecution against the Quakers,
and would not have any to receive them into their houses.
So this is abominable doctrine, contrary to the apostle,
whose doctrine you have trodden under your feet, who said,
'`Be not forgetful to entertain strangers,
for thereby some have entertained angels unawares.`' Heb. 13:2.

And they say again, they have, no certain dwelling places.
These Presbyterians, with their club law and excommunications,
who say the Quakers have no certain dwelling places, may inform against the apostles,
who had no certain dwelling places, and against Christ,
who had not whereon to lay his head, Luke 9:58. and against Abraham,
who had not a foot of ground, Gen.
xii. But Cain built a city, the vagabond, of whose flock and offspring you are, Gen. 4:17.
And said David, let their children be vagabonds,
Ps. 109:10. and so this is fulfilled upon you.

And you Presbyterian priests, with your club law,
who would club those people scornfully called Quakers away;
you would have an order from the justices,
that none should receive the Quakers into their houses, and stop them of their liberty;
and this is contrary to the law of the nations.
And this is damnable doctrine, wherewith ye poison the people,
and stir them up with madness and folly.
And instead of teaching them peace, you teach them strife;
and instead of loving one another, you teach them to fight one with another.

And Henry Foreside, priest, cries, stone them.
And James Nasmith, priest, cries for club law.
And William Hambleton, priest of Glasford, said to Andrew Brown, if the laws were right,
they would chop off all the Quakers`' heads.
By William Hambleton`'s words the law is wrong,
because it doth not fulfill his purpose and envy.

Here all may see that you are doing the devil`'s work, hunting after blood, whose envy,
madness, and folly appear to all men.
What ye cannot do yourselves, ye exhort the people to do;
and what ye and the people cannot do, ye petition the magistrates to do,
that all unrighteous blood may come upon you, Matt. 23:35.

Alas, for you, ye poor silly priests, and mad Presbyterians!
Is this your work to set people to stone, and cry up club law,
and law to chop off their heads?
Is this the way to convert them?
Is not this the popish way of converting them?
Ye should go to convert them, instruct them, convince them, love them,
heap coals of fire upon them, Mat.
v, Rom.
xx. '`Overcome evil with good,`' Rom. 12:21. Pray for them, Matt. 5:44. No,
cry you, chop off their heads,
begging by petitions that none may receive them into their houses, stone them,
fall upon them by club law, that your folly and madness may be made manifest;
and you imprison them, and such as receive them into their houses.
As for instance, ye caused John Hart, of the heads of Glasford, and Jennet Hambleton,
widow of Westmanies, to be imprisoned for entertaining them in their houses.
Here ye have proved yourselves to be the wolves the sheep are sent among, Matt. 10:16.
that are ravening to devour them;
which is one of the marks that ye are the false prophets Christ said should come, Matt. 7:5.
And you are haling out of the synagogues, and excommunicating,
and ye never show for what; which practice ye are in, which is a work of darkness.

And upon this bargain, that the magistrates would grant them an order,
that none should receive them into their houses,
and that they might not have their liberty, and their servants would be much refreshed,
who cry stone them, let us have a law against them, and if the laws were right,
they would chop off their heads, and make them remove by club law.
But how were these priests the magistrates`' servants at Dunbar fight,
when they excommunicated and cursed their army and magistracy?
But now they would be their servants, if they would execute their wills upon the innocent!
Surely these things cannot but stink to all magistrates that fear God.

These are the servants and servers of the times, that the prophets call enchanters, Lev. 19:16.
and for their own false ends.
Ye can never read that the apostles nor Christ did ever
teach any such doctrine that the people should be stoned,
or have their heads chopped off, or be driven away by club law,
which shows you are apostates from the apostles, and of the Jewish nature.

The synod at Glasgow, in the second month,
did ordain concerning these persons in Clidedale, formerly excommunicated,
who are called Quakers, that no other people in other parishes should bargain with them,
or suffer them to come within their houses, or have entertainment for money.
Upon which the people persecuted and stoned them,
and haled them out of their houses in several places,
viz. Three of those people called Quakers, were, in the night time,
betwen ten and eleven o`'clock, drawn by force out of an inn,
in the town of New-mills in Ayreshire,
and stoned out of the town into the fields to shift for their lodging.
And others, three several times, were beaten, stoned, and shamefully treated,
and persecuted in Strawan.
And others at Lithmahaga.
And others shamefully abused in the town of of Kirkantillough.
And others stoned at Kilbride.
And others pitifully stoned, beaten, and abused; and some blood shed at Glasford.
And at many other places much harm has been done.
These are the priests`' fruits, the bloody presbytery, who would have them stoned,
and their heads chopped off;
some of the magistrates did stop the people from abusing them,
so that the priests`' malice was not altogether satisfied.

Andrew Brown and John Lowcock of Glasford, were cast into prison,
for asking him a question when he was catechising;
and admonished them when they were far absent, and if they come before them,
they will cast them into prison; this makes them peepers and mutterers,
to admonish them when they are not present.
And is this like to change them, or do they intend to change them,
who admonish them when they are out of hearing,
and did excommunicate them when they were in prison?
What an unmanly part is this in this wicked, devilish, envious, and unchristian ministry.

And John Hart went to a steeple-house to hear the priest`'s admonition,
for the priest said he would admonish him, and he went to hear him;
and when he had admonished him, he spake to him,
and bid him prove himself in the doctrine of Christ,
and they whom he admonished out of it, and then gave them a bill of divorcement.
But the priest went to the court, and got a warrant from the justice,
and so cast him into prison, and when he was in prison, excommunicated him,
and said he disturbed him.
And here his devilish wicked art and doctrines appear, which shows him of Cain`'s stock,
where is nothing but persecution, murder, and envious slayers, vagabonds,
and cursed speakers, that went on in the way of Balaam, or Core;
that make merchandize of the people through their covetousness,
and feigned words to the people; and give forth their curses in their congregations,
and all the people are to say amen, to them as follows:

=== The priests`' first curse, that all the people were to say amen to.

'`Cursed be all they that say grace is free, and let all the people say, amen.`'

[.discourse-part]
_Answer._ And so they curse the apostles, and the apostles`' doctrine,
and all that witness to it, who said, the free grace of God, which bringeth salvation,
hath appeared to all men,`' Titus 2:11. and was the saints`' teacher.
These things the apostles commanded to teach with all authority, Titus 2:15.
but the ungodly men turn this grace of God into wantonness,
who are of old ordained for condemnation.

Ye are the raging waves of the sea, sending and foaming out your own shame,
whose fruits wither, neglecting the common salvation; read Jude.
Ye are like to Sodom and Egypt, clouds without water,
who run greedily after the wages of Balaam, going in the way of Cain,
and shall perish in the gainsaying of Core,
and walking despitefully against the spirit of grace;
and they that turn the grace of God into wantonness, deny the Lord that bought them,
2 Pet.
ii. Jude 11.

Ye are the trees without fruit, wells without water, carried about with tempests,
cursed speakers; teaching the people to say amen to your cursing the apostles`' doctrine,
and so willingly ignorant, that your damnation may be just,
that your madness and folly might appear to all; and so you are sensual,
not having the spirit, waves of the sea, wandering stars,
reserved for blackness of darkness; read Jude.

'`The grace of God which bringeth salvation hath appeared to all men,`' Titus
2:11. So that which brings salvation and hath appeared to all men,
ye curse; that which is the grace of God, which ye with your damnable doctrine,
and doctrine of devils, curse, them that witness it, 2 Pet. 2:1 Tim.
iv. upon whose consciences the hot iron hath come,
which hardened them that went to the doctrine of devils,
to them that did not hold forth the saviour of all men,
1 Tim. 4:10 '`These things command and teach, let no man despise thy youth.`'

Now they that went to the doctrine of devils, from the saviour of men,
but especially them that believed,
and from the grace of God which hath appeared to all men, which brings salvation,
are they which have turned the grace of God, which is the light, into wantonness,
who are ordained of old for condemnation, Jude iv.
Such are in Cain`'s way, from the command of God; Core`'s way from the truth,
and Balaam`'s way from the spirit;
those are the clouds and tempests upon whose heads comes the woe.

=== The priests`' second curse, which all the people were to say amen to.

'`Cursed be all they that say the scripture is not the word of God;
and let all the people say amen.`'

[.discourse-part]
_Answer._ Here they have cursed Luke, who calls the scripture a declaration of the word,
Luke 1:1; and Acts 1:1, where it is called a treatise.
And they have cursed their own company, who say the scriptures sinify writings;
and they have cursed John, who did not say the scripture was the word, who said,
'`In the beginning was the word,`' John 1:1, and the scripture is words,
as in the last of Revelations,
'`he that addeth to the words;`' and Christ`'s name is called the word of God; Rev.
xix, 13. And the scriptures are words, not a word, Exod.
xx, and which words Christ came to fulfill.

=== The priests`' third curse, to which all the people were to say amen.

'`Cursed be all they that say faith is without sin, and let all the people say amen.`'

[.discourse-part]
_Answer._ Faith is the gift of God, and the gift of God is without sin, Eph. 2:8.
Faith is that which gives the victory, John 3:4.
And that which gives victory is without sin.
And here they have cursed the apostles and their doctrine, who say, faith is without sin,
and faith is precious, 1 Pet. 1:7, and that which is precious is without sin.
Faith is the gift of God, and the gift of God is perfect,
and that which is perfect is without sin, and gives victory over sin,
Without faith a man cannot please God, and that which men please God in, is without sin, Heb. 1:6.
And so ye have cursed the apostle and his doctrine,
the just and that which is pure, that by which they were healed,
through faith they were justified, Rom. 3:28, and what is not of faith is sin, Rom. 14:23.
So what is of faith is not sin, and what is righteous is not sin,
and the scripture speaks of the righteousness of faith, Rom. 4:13.
Faith is not of sin, but what is not of faith is sin,
faith gives victory over sin, 1 John 3:4, in which faith man is justified,
and hath peace with God, Rom. 5:1, and it is a mystery held in a pure conscience, 1 Tim. 3:9.

=== The priests`' fourth curse, to which all the people were to say amen.

'`Cursed are all they that say every man hath a light sufficient to lead him to Christ,
and that within him, and let all the people say amen.`'

[.discourse-part]
_Answer._ Here they have cursed the apostle`'s doctrine, who said, God would dwell in them,
2 Cor. 6:16, and '`Christ in you the hope of glory,`' Col. 1:27,
and God is light, 1 John 1:5. And they have cursed the prophets, who said,
'`I give him for a covenant, a leader of the people.
I will dwell in them, and walk in them,`' saith God, Jer. 31:31.
Heb. 10:16. And he saith, '`I will send you the spirit of truth,
and it shall lead you into all truth,`' John 14:17. John 16:13.
'`And I will be their God,`' to rule them,
'`and they shall be my people,`' Jer. 31:33. Thy curses are but wind,
for we are redeemed from the curse; and the apostles said,
'`the light that shined in their hearts was to give them the knowledge
of the glory of God in the face of Jesus Christ,`' 2 Cor. 4:6.
And they that are led by the spirit of God are the sons of God,
Rom. 8:14, and the light to guide our feet in the way of peace;
and '`he that hath the son hath the father also.`' And if any bring another doctrine,
receive them not into your houses, neither bid them God speed, 2 John 9:30.
You have here showed yourselves in the cursed estate,
out of the apostles`' rule,
the same spirit of truth that led the disciples into all truth,
that shall reprove the world of sin, John 16:13-8.

=== The priests`' fifth curse, to which all the people were to say amen.

'`Cursed be all they that deny the Sabbath-day, and let all the people say, amen.`'

[.discourse-part]
_Answer._ Here they have cursed themselves, and all the apostles, and the saints,
and their own generation;
have not you and your own generation denied the Sabbath-day the Jews met on,
which is the Sabbath- day according to the scripture?
Do not ye meet together upon the first day?
And was not Christ crucified on the sixth day?
And did not he arise on the first day?
And did the saints meet together on the first day?
And not keep the Jews`' Sabbath-day?
Do not you work upon it yourselves, and keep markets and fairs on it?
But, as it is said before, we are redeemed from the curse.

These are the particular sentences whereupon Matthew Markell,
and the rest of the priests present with him,
did excommunicate those people called Quakers, in the presence of many witnesses,
and he required his hearers to say amen to every particular sentence.
