[.style-blurb]
== John Humes, Priest.

[.discourse-part]
P+++.+++ '`They who have not the scriptures, know not the attributes of God,
by the light of nature,
but the scriptures declare the great mystery of the three persons in trinity,
which they who want the scriptures know not.`'

[.discourse-part]
A+++.+++ Thy principle is a lie, and who had not the scriptures knew God and Christ,
as Abraham and Enoch, and the scripture doth not declare of the three persons,
nor of the trinity; and '`the natural man receives not the things of the spirit of God.`'

[.discourse-part]
P+++.+++ '`That the scriptures reveal the great mystery of election,
the great works of the creation, and the work of redemption.`'

[.discourse-part]
A+++.+++ There thou hast set up the scripture instead of God, and before God and the son,
for it is God that doth reveal to babes and sucklings, Matt. 11:25,
and God did reveal by his spirit, 1 Cor. 2:10, and God shall reveal, Phil. 3:15,
and the things of God are hid from the wise and prudent
(Matt. 11:25) that have the Scriptures;
the Jews had the scriptures: and God reveals his secrets to the prophets, his servants, Amos 3:7.
No man knows the Father saving to whom the son shall reveal him, Matt. 11:17.
Now the son reveals, and the Father reveals,
and the things of God are revealed by his spirit, 1 Cor. 2:10.
The Jews had the scriptures, and knew not the son, 1 Cor. 2:8,
nor the Father, as in John, nor the things of God by a natural light, as they call it.
The Jews had the scriptures, and did not know the election, Isa.
xxiv, because they were from the Spirit.
So it is God that reveals the son, and redemption, and election, and not the scripture;
the scripture was given forth from them that had the revelation from God.

[.discourse-part]
P+++.+++ '`That we and the Papists and Jesuites, and priests, do agree all together,
that the scripture is the word of God that liveth and endureth forever.`'

[.discourse-part]
A+++.+++ I do believe that you and the Papists and Jesuits, agree all in one;
but ye do not agree with the apostles and ministers of the word,
for the ministers of the word call the scripture a declaration,
as ye may read Luke i. And ye do not agree with them that set forth the Acts,
that called it a treatise, Acts i. Likewise ye do dot agree with some of your own,
who say the scriptures signify writings, and writings will not endure forever.
So ye are Babylon, and do not agree with Christ, nor with John, Rev.
xxii.
who saith '`the words;`' nor with Moses, nor God, who '`spake all these words,`' Exod.
xx. In the beginning was the word, and the word is God,
and the word liveth and abideth forever; but the scripture is words,
and the scripture cannot be broken.
