[#ch-120.style-blurb, short="John Nasmith"]
== John Nasmith, Priest of Hambleton, his Principles.

[.discourse-part]
P+++.+++ '`That the soul of man is a reasonable sinful substance.`'

[.discourse-part]
A+++.+++ How can that which is sinful he reasonable?
And if that which is unsinful be reasonable, and sinful be reasonable both,
then they are one, in unity.
The Lord will take the soul for an offering for sin;
doth the Lord take that which is sinful for an offering?
Isai.
liii.
See how thou and the prophet agree here!
But what is that soul that the wicked are not able to kill?
Is it not that which God hath in his hand?
And this is a lie, to sap that which is reasonable is sinful;
thou puttest light for darkness.
God, who hath all souls in his hand, '`breathed into man the breath of life,
and he became a living soul,`' and the soul is immortal
and Christ the bishop of it is immortal,
and God hath it in his hand, which goeth against him that doth evil,
whose hand is immortal; but man transgressing the commands of God,
the soul lies in death.
So Christ is the bishop of souls: so they that came to know Christ,
their souls rejoiced in God their saviour, Luke i.

[.discourse-part]
P+++.+++ '`That the evil spirits are both sinful and reasonable.`'

[.discourse-part]
A+++.+++ This is a lie, for reasonable is not sinful, but unreasonable is sinful, 2 Thes.
iii. they have not the faith: and if the evil spirit be reasonable,
and the good reasonable, they are both one, who then is unreasonable?
If the evil spirit be reasonable,
thou puttest no difference between the precious and the vile;
thou hast the mark of a blind guide, and a false prophet in the forehead.

[.discourse-part]
P+++.+++ '`That one of the Quakers is worse than the devil.`'

[.discourse-part]
A+++.+++ This is a lie, with his strange wonder, for there is nothing worse than the devil,
whose children ye are; for when he speaks a lie he speaks of himself,
and he is the father of it.
