[.style-blurb, short="Henry Foreside"]
== Henry Foreside, Priest of Lingiah in Dunhartonshire, his doctrine and Principles.

[.discourse-part]
_Principle._ '`That God commands all men everywhere to repent,
to the end that they should not have it to say but they were warned,
but not that he would give them grace to repent.`'

[.discourse-part]
_Answer._ Here thou makest God that he does not intend that which he speaks,
and so thou wouldst make him unrighteous;
though the Lord commands all men everywhere to repent, Acts 17:30,
who hath made all nations of men of one blood to dwell upon the earth,
and all being concluded under sin and unbelief, that he might have mercy upon all, Rom. 3:9.
For both Jews and Gentiles, all were under sin, and none of them did good,
no not one.
And God`'s intent is, that when he calls men to repentance, they should repent,
and many did repent; and you are not fit men to be ministers of Christ, or of God.

Now if God command all men everywhere to repent, and, as thou sayst,
does not intend they should repent, thou and you go about to make God unjust.
The Lord desireth not the death of a sinner,
but that he should turn from his wickedness and live, Ex. 33:11.
Now in turning from his wickedness he lives,
but in going on in his wickedness, he dies; so repentance was preached from dead works,
to serve the living God, Heb. 6:1, and Christ came to call sinners to repentance,
not the righteous; for the whole need not the physician, but the sick, Matt. 9:12-13.

And as for saying God did not intend to give them grace,
though he calls them to repentance, that is a lie, and unrighteous doctrine,
for '`the grace of God, which brings salvation,
hath appeared unto all men,`' Titus 2:11, and so as he calls them to repentance,
he gives them grace, that grace which brings salvation, which men are justified by;
so it is saving grace that brings salvation, and teacheth to deny ungodliness.

Now they that live ungodly, turn the grace of God into wantonness, Jude 4,
and these are the wells without water, in Cain`'s way, Balaam`'s way, and Core`'s way,
Jude 11. who speak high words in hypocrisy;
and these are they that separate themselves from the apostles, who are sensual,
having not the spirit, Jude 19, and are of old ordained to condemnation,
who separated from the light, who turn the grace of God into wantonness;
so these are they that neglect the common salvation.
It was the charge of the apostle to Timothy before his decease, 1 Tim. 4:2.
2 Tim. 4:7. he then told him perilous times should come,
and doctines of devils, and men speaking lies in hypocrisy; he said unto them,
that they should trust in the living God, who is the saviour of all men,
and especially of them that believe, 1 Tim. 4:10.
But the devil`'s doctrine leads
them from their saviour and from the grace, 2 Tim. 4:1.
And they that are not in the doctrine, are from the light,
which Christ hath enlightened them with, John 1:9.
And have turned the grace of God into wantonness by their pernicious ways,
and draw others from it, and we do conclude that to be the doctrine of the devils,
which says, God calls all men to repent, and intends not to give them grace,
nor would have them to repent: as thou Henry Foreside dost say;
for it was the charge of the apostle to Titus to speak sound words, and sound doctrine,
and could not be condemned, Titus ii.
and told him that '`the grace of God which brings salvation had appeared
to all men,`' which taught them to '`deny ungodliness and worldly lust,
and to live godly, soberly, and righteously in this present evil world;
these things speak and exhort with all authority,`' Titus i. But, as I said before,
ungodly men that turn the grace of God into wantonness,
are of old ordained to this condemnation, and '`this is the condemnation of the world,
that light is come into the world, and men love darkness rather than light,
because their deeds are evil,`' John 3:19, he that loves the light, it is his saviour,
but he that hates the light, it is his condemnation.

[.discourse-part]
_Principle._ '`That the two parts of the church must be profane and godless.`'

[.discourse-part]
_Answer._ The church is the pillar and ground of truth, 1 Tim. 3:15.
The church of the living God; for.
the ungodly, and that which is ungodly, are out of its grounds.
The church is the pillar and ground of truth, and there are no ungodly in it,
and the church is without wrinkle or spot, holy, and without blemish, Eph. 5:27.
And the church is in God, 1 Thess. 1:1.
That which is in God is in the light, and out of the ungodly.

[.discourse-part]
_Principle._ '`That God before the world was,
had ordained one little part of the people for eternal life,
that sin or do all the evil they could,
they could not lose that which was ordained for them.`'

Here thou goest about to make Christ a liar,
for he that commits sin is the servant of sin, John 8:34.
He that commits sin is of the devil, saith the apostle;
and thou wouldest make God partial,
and hast taught a doctrine contrary to the scriptures;
for God is no respecter of persons, Rom. 2:11,
who will give to every one a reward according to their works, Ps. 62:12.
And he that works iniquity must depart, cursed from Christ,
Matt. 7:23,
and Matt. 25:41. And he that sinneth after he hath received the truth,
there remains no more sacrifice for sin, but a fearful looking for of judgment, Heb. 10:27.
And the elect doth not commit sin,
and who shall lay any thing to the charge of God`'s elect, Rom. 8:33,
and the elect is Christ, Isa. 42:1, who was elected before the world was.
'`He that is born of God doth not commit sin, neither can he,
because his seed remains in him,`' 1 John 3:9. And he that commits sin is of the devil,
and never knew God, ver. 6. And herein the children of God are manifest,
and the children of the devil, 1 John 3:10. And God hears not sinners,
and them that regard iniquity, Ps. 66:18. John 9:31. Prov. 15:3.

[.discourse-part]
_Principle._ '`That the great part of the world was ordained for hell, that let them repent,
or do all that they are commanded to do, they would not obtain salvation,
because God had ordained them to hell.`'

[.discourse-part]
_Answer._ Then he was asked, wherefore he preached?
his answer was to save the elect: he was answered again, if it was so,
there was no need of that, seeing they could not be lost.
Then he was asked, wherefore he preached to them that were ordained to hell?
He answered, to make their damnation hotter.
It was answered him, that they had small friends of them,
and they could not make it hotter, seeing they were ordained before.
The priest aforesaid was asked, who had the blame that men went to hell?
His answer was, '`seeing ye desire to know, I shall tell you;
there is one part of the blame in man, and another part of the blame in the Almighty,
that men went to hell.`'

[.discourse-part]
_Answer._ In this there is confusion.
Thou sayst, '`God hath ordained them;`' that he has done it, then thou sayst,
'`there is part in man,`' and thou saidst before, it was in God.
Now if it be in God, that he hath ordained them to hell,
repent or do all that they are commanded to do, thy preaching is needless:
and thou canst not make hell hotter or colder.
Therefore thy preaching is done and ceased.
And thou sayst part of the blame that men go to hell is in God;
here thou wouldst make God unrighteous, who desires not the death of a sinner.
God is not to be blamed in any thing he doth, but to be praised,
who is righteous in all his judgments: and God is not to be blamed, for God is truth,
so let God be true, and every man a liar, Rom. 3:4. Thou wicked one,
man`'s destruction is of himself, Hosea 13:9, and God wills not the death of a sinner,
but rather that he would repent; so no fault in God,
who saith,`'Let the unrighteous man forsake his unrighteousness, and he shall live,
so let the righteous man forsake his righteousnes,
and he dies,`' Ezek. 18:22. So my ways are equal,
the Lord hath no pleasure at all that the wicked should die,
but that he should return and live; so man`'s destruction is of himself.
And whereas thou sayst,
'`God hath ordained a great part to hell,`' what makest
thou of Christ who came to be a saviour of the world?
John 4:42, he doth not say the elect only, but to save the world, and not to condemn it.
And '`God so loved the world`' (mark the words,) Jo. iii.19, he doth not say,
so hated it, '`that he gave his only begotten son into the world,
that whosever believed in him should not perish,
but have everlasting life.`' And he came not to condemn the world,
but that the world through him might have life.
But they that hate the light and do not believe in it, are by the light condemned,
but thou sayst otherwise, that he condemns a great part of the world.
And he doth not say he loves the elect only,
but '`God so loved the world,`' and '`God was in Christ
reconciling the world to himself,`' 2 Cor. 5:19,
he does not say the elect only.
And he through death hath destroyed the power of death, the devil, Heb. 2:14,
And thou art to be reproved for thy judgment, for thy unbelief, for thy unrighteousness,
for thy sin, because of thy unbelief, because the prince of this world is judged,
John xvi.
And so Christ doth not say, I am the light of the saints, of the elect only,
but I am the light of the world, John 8:12, and saith,
that '`light is come into the world, and this is the condemnation of the world,
that light is come into the world, and men love darkness rather than it,
because their deeds are evil,`' John 3:19. So it is unbelief that shuts out, Rom. 11:20.
So the gates stand open night and day, and every one that doth evil,
hates the light and will not come to it, because it will reprove him,
and he will not come into the gate, for he that comes to the gate comes to the light,
and he that comes to the light comes out of condemnation,
and comes to be a child of the light,
he that hates the light will not come into the kingdom of God.
And as for thy saying, '`God hath ordained a great part of the world to hell,
let them repent and do all that ever he hath commanded
them;`' he that doth the things that Christ commands,
enters the kingdom; he that repents, his mind is changed,
and whosoever believeth shall not perish, and this command is general, John 10:28,
through the whole world, therefore thou, with the devil`'s doctrine,
shuts up the kingdom of heaven against others, and wilt not go in thyself, who says,
let men repent, and do all that ever they can, they must go to hell,
when God wills not the death of a sinner but rather
that he should turn from his wickedness and live,
Ezek. 33:11, but he is merciful, and judges not as thou dost, whose eyes are blinded,
and whose hands are full of blood.
So I say, whosoever repents, and doth the things he is commanded shall be saved;
and that which thou sayst to the contrary, we conclude to be the devil`'s doctrine:
and whosoever resists the thing that is commanded, that will be their condemnation,
who hate the light which was before the world was,
which lighteth every man that cometh into the world, that all through him might believe,
for he that believes in the light shall not abide in darkness, John 8:12,
shall not come into condemnation, shall come to be a child of light, John 12:36,
and they shall have the light of life.
And so the light is sufficient to save them, and to condemn them if they believe not,
John 3:18. 14. Isa. 4:12,
and every one that cometh into the light that he
is enlightened with comes into the election,
and into the covenant of God.
Evil consciences thou mayst frighten, them that hate the light,
which is their condemnation, but the elect thou canst neither save nor deceive.
Thanks be to God, Christ reigns, who will give to every man according to his works,
who doth enlighten every man that cometh into the world;
and he who doth not believe is condemned, and shut out.
And such turn the grace of God into wantonness,
and are ordained of old that hate the light,
which lighteth every man that cometh into the world,
and such are in Cain and Balaam`'s way, persecuters and murderers,
and turn the grace of into wantonness.

[.discourse-part]
_Principle._ From the words of Jude iv, '`they were of old ordained;`' from these words he said,
that God had predestinated one to life, without any cause in the creature less or more,
and the other wicked man to hell, without any cause in the creature less or more;
and both wicked men.
And before thou saidst part of the cause that God
cast into hell was in the man and part in God.
In this 7th principle and doctrine thou said there is no cause in the creature,
that God casts into hell and condemns him, and in the other thou saidst,
there was part blame in man, and part in God; and here is the devil`'s doctrine,
a lie found in thy mouth.
And thou hast wrested, perverted, and wronged that scripture in Jude, who sayest,
there is no part in man causeth condemnation, that all may see that you are liars,
whereas Jude saith, they were ungodly,
they turned the grace of god that brings salvation into lasciviousness,
and denied the Lord that bought them.
Jude xi.2. Pet.
ii. 1. They were covetous, made merchandise of the people, through feigned words,
and no covetous person nor idolater shall enter into the kingdom of God, 1 Cor. 6:9,
And all deny the Lord that bought them, but they who own the light that comes from him,
which doth enlighten every man that comes into the world, and none see him,
but with the light that comes from him; and they go in Core`'s way,
and gainsay the truth,
who go from the light that Christ hath enlightened them within the particular,
and he that gainsayeth the truth, there a fault in him; and they go in Cain`'s way,
that are from the command of God, who said, '`If thou dost well,
shalt thou not be accepted?`' and if he did not well, sin lay at the door.
Now these were of old ordained unto condemnation,
who turned the grace of God into wantonness, who were in Cain`'s way, Core`'s way,
and broke the commands as Cain did, and in Balaam`'s way, erring from the spirit,
and admiring men`'s persons because of advantage, which Balaam did,
and loved the wages of unrighteousness;
and so these do not the things they are commanded,
Cain did not do the thing that he was commanded, nor Core and his company,
that offered strange fire.
Num. xvi.
So these of old were ordained for this condemnation, which condemnation is the light,
John iii.
light foresees them and sees over them, and condemns them,
when they arise and go out from the spirit of God in them.
And here all may see, here was fault worthy of condemnation:,
And those were they that sensually separated themselves from the apostles,
and had not the spirit, Jude x ix.
in their days, who were covetous, who went for the gift and reward,
who were like raging waves of the sea, who were spots in feasts of charity, feasting,
feeding without fear 2 Peter ii.
Who admired men`'s persons because of advantage, and spoke high words in hypocrisy,
'`wells without water, trees without fruit, raging waves of the sea,
foaming out their own shame, clouds without water, carried about with tempests,
spots in the feasts of charity, like unto Sodom and Gomorrah`' in filthiness,
who go from the, light that does convince them; so there is the self-separation,
and there is the condemnation that comes over them, the light;
and these are they that separated from the apostles; who said,
'`love your enemies,`' Matt. 5:44. who are men gone into the world,
who are in Cain`'s way in envy, in Core`'s way gainsaying the light;
they are like raging, waves of the sea, foaming out their shame in their pulpits.
So you are the men that separate from the apostles, that are in Cain`'s way,
and Core`'s way, who are out of the life and sacrifice the saints were in,
who would murder,
who gainsay the light that doth enlighten every man that cometh into the world,
so are against the common salvation.

And ye are like Cain, foaming and raging in your pulpits,
and would murder all that are contrary to you, whose sacrifice God accepts,
and yours he does not; and God would have accepted Cain, if he had done well.
Gen. iv.
So God is merciful and a just God, but Cain did not well;
therefore woe went out from God against him, and so there was fault in him and not in God,
which was the cause of his condemnation.
So you that are in Balaam`'s way, loving the wages of unrighteousness,
admiring men`'s persons because of advantage,
ye are out of the faith that is held without respect of persons, James ii.
and so separated from the apostles, to whom Christ said, '`Freely ye have received,
freely give;`' and you will not give freely, who are raging and foaming,
without you have augmentations, stipends, glebe-lands, or tithes, great sums of money,
gifts or rewards from great houses:
so you deny the light that enlighteneth every man that cometh into the world,
and so gainsay the common salvation.
Jude i. You gainsay the truth, that doth enlighten every man that cometh into the world,
so you are in Core`'s way; and would have the persons of saints murdered,
so in Cain`'s way;
and as ye confess that ye have not the spirit that gave forth the scripture,
so you are in the self-separation;
and ye deny the light that enlighteneth every man that cometh into the world,
which is the Lord, John 8:12. and so deny the Lord that bought you. 2 Pet. 2:1.
And so are for condemnation,
who are of that stock that separate themselves from the apostles, sensual,
having not the spirit, who are in Cain`'s way, that would kill and murder,
and out of the apostle`'s way, who said, '`love your enemies;`' who are in Balaam`'s way,
for gifts and rewards, and admiring men`'s persons because of advantage;
to them speaking high words in hypocrisy;
and out of the apostle`'s way to whom Christ said, '`Freely ye have received,
freely give.`' Matt. 10:6. And out of the prophet`'s way, who said,
'`come without a price.`' Isa. 4:1. 2. And ye will have the price,
or else you will not come.
Let all that can, read Jude over,
and see if there was not cause in man of his condemnation, and not in God;
and so have not you proved yourselves in the doctrine of the devils, and in lies,
and would make God unrighteous, and the apostles unrighteous?
For there was fault in Cain, fault in Balaam, and fault in Core, and fault in Sodom,
and fault in them that turned the grace of God into wantonness,
which were of old ordained for this condemnation.
Jude iv.
Which condemnation is, that light is come into the world,
and men love darkness rather than light, because their deeds are evil.
And so the apostles taught that there was fault in man, as ye may read in Jude,
and thou hast taught that there is none; so then thou art unrighteous,
who would make God and the apostles unrighteous, like thyself.
Let all that fear God, who are now come to the judgment seat before the Almighty God,
judge who have been they that have erred from the apostles`' doctrine;
with it you are judged, and you must have a reward according to your works.
And he that comes to life, comes out of his wickedness,
and the wicked man enters not into the kingdom of God.
Rev. xxi.
And the promise is to the seed, and he that works iniquity departs from the seed. Gal. 3:16.
And the election obtains it. Rom. 11:7.
Not he that wills, nor runs, but God that shows mercy.
And whereas thou sayst '`the wicked man is ordained to life,
without any cause in the creature less or more:`'
this is just the devil`'s doctrine again,
to bring every one to hide his talent, and none either to watch or pray;
for there is in the creature, that which brings him to lay aside wickedness,
and to depart from sin, and iniquity, and covetousness, and drunkenness,
which lets him see it, through the obedience of the spirit;
and that is in the creature which brings him to confess his sin, and forsake it,
whereby mercy is showed; '`the power of God worketh in us,`' saith the apostle.
And as they had been servants to unrighteousness,
so came to yield themselves servants unto righteousness.
Rom. vi.
How come the commands of God to be obeyed,
if there be not something in the creature that causes him to obey it?
For thou sayst '`without any cause in the creature:`'
why were all these expressions spoken in scripture,
that they should obey all things that Christ commanded? Matt. 28:20.
And all the statutes and ordinances spoken of in the scriptures,
if there be not something in man to cause him to obey them?
But thy intent is to make God unrighteous who respects no man`'s person,
but gives to every man a reward according to his works, Rev. 2:23.
the one as well as the other;
and all shall appear before the judgment of Christ. 2 Cor. 9:10.
He will judge the world in righteousness.
And there is something in the creature that enlightens
every man that cometh into the world,
whereby he is capable of obeying or disobeying, and not believing comes to be condemned,
and in believing he is saved; he hath the witness in himself. John 3:8.
1 John 5:10. For he that commits sin is the servant of sin. John 8:24.
And there is no respect of persons with God,
but whosoever doth righteousness is accepted of him. Acts 10:34-35.
The apostle said,
'`he perceived God was no respecter of persons;`'
but whosoever doth wickedly hates the light,
and is condemned, but '`whosoever doth the truth,
cometh to the light,`' John 3:21. and so is out of condemnation:
so thou teaches another doctrine.
So as I said before, '`The promise is to the seed, the seed is Christ,
and Christ is all and in all.`' 1 Cor. 15:28. And all
ungodly and wicked men are shut out of the kingdom of God,
into which no wicked men enter,
and man must be turned again from wickedness before he enters. Rev. 21:8.

[.discourse-part]
_Principle._ '`He being asked, what he would do with Quakers, said,
if he had been a civil magistrate,
he would have thought it good service to have cut off all their heads.`'

[.discourse-part]
_Answer._ There ye may all see if he be not of Cain`'s stock,
and what envy proceeds out of his mouth, and unchristian spirit;
and how would he convert them if they were out of the way?
and how would he convince them, who would cut off their heads?
Hath not this proved the Quakers to be in the truth, and he out of it?
And is not the command of Christ, that ye should love your enemies? Matt. 5:44.
Now ye may see, he is out of the command and example,
but follows the example of Cain the murderer.
And doth not he show his envy as much against the magistrates as against the Quakers,
because they will not execute his malice, and slay them for him, and be his executioners?
And were not these priests as mad against the magistrates,
as they are now against the Quakers, at Dunbar fight?
and would not they have had their heads off?
Let their pulpits witness, though now they admire their persons because of advantage,
Jude xvi.
who cannot hold in, but their shame must be uttered forth,
who would slay the persons of men as Cain did.
So woe from the Lord God is gone out against you, who are envious,
and strive to make the people envious;
but the life of God is risen in the hearts of his people,
with which they shall see you all; and the Quakers are out of the way of Cain,
who are in the light of Christ Jesus the saviour of the soul,
in which they come to have a habitation in God, the saviour of all men,
especially of them that believe. 1 Tim. 4:10.
So you that are out of the light are vagabonds,
though ye have great habitations in the earth, for Cain built a city, yet was a vagabond.
Gen. iv.

[.discourse-part]
_Principle._ '`It was asked him of a foreordained number to destruction,
and for what Christ wept over Jerusalem?
He said, '`As he was human he mourned, but his godhead decreed them to hell.`'

[.discourse-part]
_Answer._ This is a lying doctrine of the devil,
for afterwards many of them of Jerusalem came to be converted, as ye may read in Acts ii.
And many of the priests came to be obedient to the faith;
for all being gone astray both Jews and Gentiles, Rom. 3:9. and concluded under sin,
the pure, the eternal, tendered over them,
who had stopped their ears and closed their eyes to that which was pure of God in them,
that they might have come to that which is pure,
and have been gathered under Christ`'s wings, (Matt. 23:37) who is pure,
and so have been converted and healed, and have heard with their ears,
and have seen with their eyes.
And as for the word human, that is not scripture language, it speaks not that language.
And there were converted many thousands of the Jews, and they were pricked to the heart,
when the apostle said, that he was both Lord and Christ whom ye have crucified.
Acts ii.
Mark ye, here thou may see thyself to be a liar;
for here were of the Jews and of Jerusalem, that he had wept over.
Thou sayst he had ordained those to hell (as he was God) who were converted afterwards;
so thou wouldst make God unequal, that the son is not in the Father, and divideth them,
that the son should weep over them, and the godhead decree them to hell.
And did not Christ command his apostles that they should not depart from Jerusalem?
And was not the mighty conversion at Jerusalem?
So did not Christ weep over Jerusalem,
and afterwards was there not a mighty conversion there?
And thou sayst, that as God, he condemned them to hell;
there thou mayst see thyself to be in the devil`'s doctrine. 1 Tim. 4:1.
Many thousands were converted at Jerusalem, which Christ wept over,
before the apostles departed from thence, where he gave them command to stay.
So thy doctrine is damnable, and thou errs from the scriptures.
Let thy mouth forever be stopped.
And are not ye found in the steps of them, Matt.
xxiii.
that Christ gives the mark of blind guides to the multitude, unto the disciples?
Which mark was such as the multitude might take notice of,
and I believe the multitude will take notice of, and know you.
Ye bind heavy burdens upon men`'s shoulders; ye are sayers and not doers;
and '`all their works they do to be seen of men.`' Matt.
vi. They love the uppermost rooms at feasts, and the chief seats in the assemblies,
and greeting in the markets; they stand praying in the synagogues,
and are called of men masters; they were swearers, they scourged in their synagogues,
and persecuted, and do not ye put out of your synagogues?
Christ should send prophets and wise men among them, and they should persecute,
and put out of the synagogues. Matt. 23:34.
They should '`shut up the kingdom of heaven
against men,`' and do not ye do so that deny the light,
'`that lighteth every one that cometh into the world?`' Do any come to the kingdom,
but they who come to the light,
which every man that cometh into the world is enlightened with?
May not the multitude take notice of these things?
You are called of men master, stand praying in the synagogues, having long robes,
love salutations in the markets and the uppermost rooms at feasts,
put out of the synagogues, and are swearers, when Christ said,
'`swear not at all.`' Matt. 5:34. '`And be ye not called of men master,
for one is your master, even Christ,
and all ye are brethren.`' Now here are the marks of the blind guides, as ye may read,
Matt.
xxiii.
Are they not a company of swearers, and will they not swear for their own advantage?
And were not the priests always envious, and false accusers,
provoking the magistrates against the disciples, and against Christ Jesus?
Did not the priests say, Jesus should die for crying against them?
Jer. xxvi.
And were not the priests at work, when any of the saints were murdered,
to stir up the multitude or the magistrates against them?
Were not the chief priests and elders seeking false witness to put Jesus to death? Matt. 26:30.
And did not the high priests say he had spoken blasphemy?
It was Pilate that put him to death;
did not the chief priests persuade their multitude to ask Barabbas, Matt. 27:29.
and crucify Jesus?
And did not they mock him?
See how the priests were always busy for blood,
that all the righteous blood shed upon the earth, might come upon them. Matt. 23:35.
And did not the priests give money to Judas to betray Christ?
And did not the priests give large money to the soldiers to tell a lie,
and say his disciples stole him away by night? Matt. 28:11-13.
Had not Paul authority from the high priest to persecute? Acts 9:1-2.
And so you get your authority from the magistrates,
and the people get their authority from you to persecute.
And would not the chief priests have murdered Paul afterwards, when he was converted?
Acts xxiii.
ii. 7. Did not a company come with swords and staves
from the priests with Judas to take Christ? Mark 14:13.
'`As a troop of robbers wait for a man,
so loth a company of priests murder in the way by
consent,`' and have not ye consented together? Hosea 6:2.

[.discourse-part]
_Principle._ '`That Christ scorned men when he bade them he perfect,
because he knew it was impossible for them.`'

[.discourse-part]
_Answer._ This is wickedness and impudency to say Christ scorned men when he bade them be perfect.
This is antichrist and the devil`'s doctrine,
to say that Christ did command that which men could not come to;
for neither Christ nor God commanded any thing, but what should be attained unto;
and it will be attained unto, and hath been attained unto, Christ said,
be perfect as your heavenly Father is perfect, Matt. 5:4.
he knew that they might be perfect if they came into the kingdom of God,
for there no imperfect thing must enter.
Rev. xxi.
And so he did speak that which he knew people should come into,
if they ever came into the kingdom of God.
What is this to thee who cannot love enemies?
For they that love enemies, shall know perfection,
and perfect love and patience have their perfect work. James 1:4.
The apostles spoke wisdom to them that were perfect,
but not the world`'s wisdom, which comes to nothing, 1 Cor. 2:6.
and the work of the ministry was for the perfecting of the saints,
till they all came into the unity of the faith, unto the knowledge of the son of God,
unto a perfect man, and unto the measure, and stature, and fulness of Christ.
Eph. iv.
And they should not be any more tossed to and fro with the windy doctrines of men,
nor cunning craftiness wherewith they lie in wait to deceive;
and thus art thou tossed up and down with every wind,
and far off the work of the ministry, when thou sayst blasphemously,
'`Christ scorned men when he bade them be perfect.`' Christ did not scorn them,
but thy doctrine is imperfect,
and thou and you that transgress and abide not in the doctrine of Christ are antichrist,
as ye may read, 2 John 9:10.

[.discourse-part]
_Principle._ '`When it was asked him,
of the words that Peter spake of concerning them that brought in damnable heresies,
and denied the Lord that bought them,
he said they did but think the Lord had bought them, but they were not bought,
but they thought they had been so.`'

[.discourse-part]
_Answer._ Here again with thy damnable doctrine,
thou dost go about to make Peter and Jude liars, who speakest contrary to scripture,
and pervertest their doctrine; and the words of Peter are thus,
'`even denying the Lord that bought them.`' 2 Pet. 2:1. and the words of Jude iv.
'`denying the only Lord God,
and our Lord Jesus Christ.`' And thou sayst the Lord had not bought them,
but they thought he had bought them: woe and misery will be thy portion,
that thou shouldst so wickedly pervert the apostles`' doctrine and the scripture, Acts 13:10.
and bring in such damnable and devilish doctrine,
and speak such lies in hypocrisy, whose conscience is seared with a hot iron.
1 Tim.
iv. It is time for people to turn away from you, who have so long deceived them.

[.discourse-part]
_Principle._ Concerning these words of Ezekiel 18:28. '`If
the righteous man turn away from his righteousness,
his former righteousness shall be no more remembered;`' and he said,
'`the meaning of that scripture was, they thought they had been righteous,
but they were not, but supposed it had been so.`'

[.discourse-part]
_Answer._ Here in this thou art a minister of unrighteousness;
thou goest about to make God a liar, and the prophets, and pervertest the scriptures;
for if the righteous man forsakes his righteousness, and commits sin and iniquity,
and trespasses, he shall die, and not live in the former righteousness;
but if he forsake his sin, trespasses, and transgressions,
in the righteousness that he hath done, and doth, he shall live;
so God`'s ways are equal.
Ezek.
xviii.
And thou sayst, they thought they had been righteous, but it was not so.
And the Lord by the prophet saith it was so,
that they should live in their righteousness, and should die if they departed from it,
and transgressed: here thou art a diminisher from the prophets and apostles`' words,
whose name is diminished out of the book of life; read Rev. 22:19.

[.discourse-part]
_Principle._ '`He denied that Christ died for all men, but for the elect.`'

[.discourse-part]
_Answer._ Contrary to John`'s doctrine, who saith, '`He is the propitiation for our sins,
and not for our sins only,
but for the sins of the whole world.`' 1 John 2:2. And so it is the unbelievers
that are shut out by not believing in the light that men are enlightened with,
with which light they might see the one offering, who tasted death for every man, Heb. 2:9.
and which doth enlighten every man that cometh into the world,
that all through him might believe.
And they that believe not in the light are condemned, John 3:18.
but believing in the light, they shall come out of condemnation.
And he is the saviour of all men, but especially of them that believe. 1 Tim. 4:10.
And '`the grace of God which brings salvation
hath appeared to all men,`' which was the saints`' teacher, Titus 2:11-12.
and they that turn it into wantonness, shall be condemned by it,
Jude iv.
And they that heap up teachers, 2 Tim. 4:3. after their own lusts,
as they did that went out from the apostles`' doctrine, before the apostles`' decease, 1 John 2:19.
such have turned the grace of God that brings salvation into wantonness,
and say it hath not appeared unto all men.
And Christ Jesus doth enlighten every man that cometh into the world,
that they might believe and walk after him, and saith,
'`they that follow him shall not abide in darkness,
but shall become the children of light,
and have the light of life.`' John 8:12. Now they that hate the light say,
it is not sufficient, it is not a saving light,
but they shall find it sufficient to condemn them, and their unbelief,
for not believing in it; for by believing in it, they come to have the light of life. John 8:12.
and John 12:36.

[.discourse-part]
_Principle._ '`He being asked who were hirelings, if they were not that did take hire?
His answer was, they were hirelings that did not take hire, and to prove it,
he brought that scripture in Philippians of them that preached Christ of envy and strife.`'

[.discourse-part]
_Answer._ Now all may see what doctrine he brings to pervert or wrest the scriptures, Phil. 1:15.
to prove them hirelings that do not take hire!
That in the Philippians doth not prove that they were hirelings,
neither did they take hire, so that makes nothing for his purpose,
though for this purpose he brings that scripture,
but that his folly and darkness might appear, and be made manifest by the light,
for his deeds are now come to it, who is unfit to talk of the scripture.

[.discourse-part]
_Principle._ '`He said it was the clear mark of the devil to go up
and down from place to place to preach as the Quakers do.`'

[.discourse-part]
_Answer._ Now here in this he may charge all the prophets, Christ, and his apostles,
who went up and down from place to place, Heb.
xi. that this is the mark of the devil; but this doth manifest and bring to light,
and discover the Presbyterian priests of Scotland, who lie in dens and corners,
and fat benefits, and there stick in the earth, and have crept into houses;
who say it is the devil`'s mark to go up and down to preach,
but in this they manifest themselves to be judged
by the practice of Christ and his apostles,
that their folly might appear unto all men. Luke 9:5.
8+++.+++ Heb.
xi. The Presbyterian priests are turned like Ranters, who say, whatsoever man doth,
God hath a hand in doing it, whether good or evil; if a man commit ever so much sin,
and live ever so wickedly, he shall go to heaven if he be ordained there to come.
How was God grieved when David sinned?
The Lord was angry; the Lord was wroth when the children of Israel sinned against him;
it grieved the Lord that he had made man, when all flesh had corrupted his way, Gen. 6:6.
and thou and you go about to make God the author of sin,
and say God hath a hand in whatsoever a man doth here.
Again, you and thou are in the doctrines of devils: what!
Shall we say that God is the author of sin?
God forbid. Rom. 6.
They that transgress the commandments of God, provoke him to anger,
and though God created the evil, Isa. 49:7. yet his commandment was to man,
that he should not go into it, Gen. 2:17. Gen. 4:7. Ezek. 18.
but when he did, he transgressed the command of God.
So he who saith, if ye murder, God is the author of it; if ye persecute,
God is the author of it; if ye do unrighteously, God is the author of it;
you that murder, persecute, and do not righteously,
are of him that kept not the command of God, of whom ye are, John xliv.
that would persecute and murder.
Thou art gone out of the command of God, and joined with the devil, 1 John 3:8.
that went out of the truth.
The devil went out of his estate, and the woman hearkened to him,
and went out of her estate, and man hearkened to the woman. Gen. 3.
The Jews went out of their state, when they persecuted, Matt. 27:25.
Cain went out of his state when he murdered,
and Balaam went out of his state when he coveted the wages of unrighteousness. Gen. 4.
The christians went out of their estate, since the days of persecution,
and admired men`'s persons.
Numb. 22. Jude 11.
Core went out of his state when he gainsaid the truth.
Numb. 16. Jude 11.
The false prophet, and antichrist, which is the beast, and the mother of harlots,
went forth from the state of the apostles, 1 John 2:19.
which hath been since the days of the apostles.
And so all wars, and fightings, and adversaries, arise from being out of the truth,
James 4. there is pride, and Lucifer. Isa. 14.
and that is it, that is of old ordained to condemnation, Jude iv.
and to be kept down and to be condemned everlastingly,
and there the time shall be witnessed when it shall be fit for the fire,
and death and hell, and the false prophet,
and the dragon, and the serpent, cast into it. Rev. 20:14.
But the leaven is known that leavens into the new lump, 1 Cor. 5:7.
the everlasting fire that burns forever, Mark 9:46.
How have the professions, forms, and religions, fallen from,
and lost the state that Christ was in, the prophets were in, Abraham was in,
David was in, Moses and the apostles were in: and remain in a form of their words, 2 Tim. 3:5.
and murder them that enjoy their life, and persecute them.
The devil abode not in the truth. John 8:44.
Adam and Eve abode not in the truth, but transgressed. Gen. 3.
Cain abode not in the truth when he murdered Abel. Gen. 4.
The Jews abode not in the truth, but crucified the just. James 5:6.
Antichrist, and the false prophets, since the days of the apostles,
and the beast, abode not in the truth, 1 John 2:19. that made war against the saints.
Rev. 13.
And here are the murderers, the envious, the persecutors, and fighters,
whose sacrifice God never accepted, Gen. 4:5. in all ages:
and these are they that persecuted those that were in the truth,
whose sacrifice God accepted.
To the witness for God in you all, I speak; that you may see your fall from the truth,
out of the prophets`' life, Christ`'s life, and the apostles`' life;
so you are out of the commands, and fallen from God,
and then say that none can keep the commandments,
that is the word that shall stand forever;
for ye are they that love not God, John 14:13.
1 John 2:4. but are of the beast and false prophet
that make war against them that keep the commands of God, Rev. 22:11.
So that he who saith, none can keep the commandments,
is fallen out of the truth, and the commandments of God. 1 John 2:4.
John 8:44. And to him the truth is death, and the commands of God,
in which the saints live, to whom the commandments are not grievous. 1 John 5:3.
