[#ch-122.style-blurb, short="Thomas Garwine"]
== Thos. Garwine, priest of Edenborough, his doctrine and principles.

[.discourse-part]
_Principle._ '`That the child that is not sprinkled with outward water, is in a damnable state,
and worse than an infidel.`'

[.discourse-part]
_Answer._ Now here he and the rest of the Presbyterian priests of Scotland may say,
Abraham was in a damnable state, Isaac was in a damnable state,
Jacob was in a damnable state, and Joseph was in a damnable state,
and David was in a damnable state, and John the Baptist was in a damnable state,
who were not sprinkled by a priest with outward water, nor named by the priest;
but thou and you, with your traditions, say a child is in a damnable state,
if ye do not sprinkle it with water.
And the apostle bids them not look at the things that are seen.
And you are in the damnable state, and the damnable doctrine, and are teachers of lies;
and many simple people have been deceived by you and given over to believe you,
but God is taking the veil off their hearts that you begin to be seen:
and their salvation they shall know, stands not in elements, as though you,
by your sprinkling infants with outward water, could bring out of the damnable state;
O! ye deceivers! did not the apostle say, they that were circumcised,
Christ profited them nothing? Gal. 5:2.
Ye have long deceived people with your beggarly rudiments, and elements,
and doctrines, and traditions, Col.
ii. hatched up at schools, and never commanded by God; and say,
if people will not observe your traditions, or your elements,
which you call (a Popish word) sacraments, which are perishing,
they not observing them are in a damnable state, and worse than the heathen and infidels.
An infidel is a heathen, one that knows not God;
but your generation say it is blasphemy to say any have known God, or have seen God,
or spoken to God.
So you yourselves have concluded to be heathen: the heathen know not God:
the heathen observe traditions;
and they that know God cannot observe the traditions of the heathen:
but obey the apostles`' doctrine, and touch not, taste not,
and handle not the traditions of men and ordinances which will perish, so are not saving.
So they that observe not traditions are not worse than heathen:
but they that observe traditions are as the heathens,
and are out of the apostles`' doctrine, in their own traditions and rudiments,
and are offended at those that will not touch them.
Robert Semple, priest of Lesmahaga, came to George Weare, of Saffield,
to reason with him,
and he laid down these following things for his doctrine and principles:
his first doctrine and principle was,
to prove the lawfulness of being called of men master,
standing praying in the synagogues, going in long robes;
and he mentioned Ezra`'s pulpit of wood, upon which he stood,
and read the law to the people; and for the rest he said nothing,
for his mouth was stopped concerning these things,
being found in the steps of the Pharisees, Matt.
xxiii.
We do grant that Ezra had a pulpit of wood,
but you profess yourselves ministers of the gospel and Presbyterians,
and are ye fain to run to Ezra in the law, for a pulpit?
Now you have showed yourselves what you are, and brought your deeds to the light.
But the priesthood was made by the law of God; so were you never.
That priesthood is changed, and the law changed also by which it was made,
and pulpit and tithes ended; and Christ the everlasting priesthood witnessed:
so thou and you have proved yourselves no ministers of the gospel of Christ Jesus,
the power of God, and the wisdom of God, the everlasting priesthood,
who is the end of priests, pulpits, and tithes, that were true in their place.
So you that have got up another pulpit, tithes, temple, like readers of the law,
and not like ministers of the gospel, are separated from the apostles,
and are in the delusion, and from Christ the everlasting priesthood, Heb.
vii. and are those that Jude 19. and 2 Pet.
ii. speak of.
You are they that separate themselves,
having not the spirit that they were in who witnessed against pulpit, tithes,
and priesthood, and witnessed Christ the everlasting priesthood; which pulpit, tithes,
and priesthood ye are crying up, and so are antichrist.

George Weare bade him prove his practice for sprinkling of infants,
and whether or no they were not to believe before they were baptized.
He said, the promise was to Abraham and his seed.
George answered him, it was not to seeds, as to many, but to thy seed, which is Christ.
Robert, the priest, said, '`That seed, Christ,
was natural,`' contrary to the apostle`'s doctrine, Gal. 3:16. who said,
Christ was the power of God, 1 Cor. 1:14-15. and Christ the mystery, Col. 1:2.
7+++.+++ The first man is of the earth, earthly,
the second man is the Lord from heaven, heavenly, Cor.
xv. The spiritual man judgeth all things, 1 Cor. 2:15.
The seed of the woman bruiseth the serpent`'s head, Gen. 3:15.
And the promise is to the seed, and the seed is Christ the power of God.
And Christ the seed is the spiritual man, and so not natural,
but the priest said the seed is natural.
Now let all see in this whether he be not given
up to delusion to speak lies in hypocrisy, 1 Tim. 4:1.
to delude and deceive people for dishonest gain, Ezek. 22:13.
Which seed, he and all the Presbyterians shall find spiritual, to judge them,
and bruise the heads of them,
and break their wicked cords and bonds of iniquity which they have laid upon the people,
Matt. 23. Ezek. 34. Acts 15.
The day is at hand that their judgment is come by that man whom God hath ordained, Acts 17:31.
to judge the world in righteousness,
and to give to every man a reward according to his works, Ps. 62:12. Rev. 22:12.
who shall give to him an account of every idle word that they shall speak,
in the day of judgment, Matt. 12:36. And William Kennedy came to George Weare,
and promised him that he should have a public hearing,
he hearing what the priest and the rest of the elders charged him withal.
And when he came they would not give him a hearing; and so found them truce-bearers,
that are to be turned away from, 2 Tim. 3.
and such as creep into houses, and are boasters, proud, high-minded,
as Jannes and Jambres, who have a form of godliness, and deny the power,
who are to be turned away from.
And after that,
the said priest did excommunicate George Weare in another parish without any hearing,
nor would let him know for what they excommunicated him,
which was a work of darkness to make the people`'s minds envious against the just.
Upon which George Weare went to their meeting place to read a paper to him,
to show why he denied him; and two priests, Robert Semple and John Hume, being there,
bade the people to knock down that excommunicated swinger, which is, in English, rogue;
upon which the people did obey the priest, and did beat,
and knock George Weare down to the ground; and might have murdered the man,
had not the Lord`'s mercy been seen.
So they are in Cain`'s way, in envy, Gen.
iv. Jude xi.
And George got up again, and the priests bade the people strike him;
and they did beat him, and plucked him by the hair of the head; and the priests bade,
beat them away; and they did so.
And afterwards the priest summoned George to the court;
and told the bailiff he would prove by the scripture, that he must be stoned to death.
Now here is the murdering Jews`' nature, that stoned the prophets, and the apostles;
and stoned Steven, and took up stones to stone Christ, Matt. 23:24.
John 8:59. Acts 7:58. And ye are bloody butchers, and man slayers,
and no ministers of Christ:
did not the false prophets go always with the beast to war (Rev.
xiii.
Rev. vi.) against saints and the Lamb?
And did not the chief priests stir up the rulers against Christ,
and had not the priests a hand to murder?
And were not the priests at the examination of Stephen,
and gave counsel that he should be stoned to death?
And did not the priests stir up the rulers and magistrates to persecute?
though they themselves did not often do it, who had not the power,
but they stirred up the magistrates to do it.
And they came to be their slaughterers, to execute their malice,
and be their executioners.
Ye do not, ye may say, it is the magistrates that ye stir up to do it.
It is not said, the priests did slay and crucify Christ, but Pilate;
but the priests had power amongst the multitude to
persuade the multitude to ask the murderer,
Matt.
xxvii.
(who had murder in their hearts,) and Pilate did the thing.
And did not God overthrow Jerusalem, and destroy the power of the magistrates there,
and priests both?
and hath not God done it in many ages for executing the priests`' malice,
and their envy against the just, and his anointed?
Have not ye many examples set down in the scripture,
in which ye may all take notice of it?
Therefore take heed, all ye magistrates, how you execute and avenge the malice,
and wickedness, and envy of any one against the just: for '`the envy of the envious,
and the wickedness of the wicked shall slay himself,`' Ps. 24:21.
and the righteous shall see it.
Therefore, you that are called Christian magistrates, execute not,
neither be ye executioners of the madness,
and envy of those who call themselves ministers of Christ; that would have you to slay,
to stone, to stock, to prison, and to put to death them that are contrary to them.
Those are murderers in Cain`'s way, manslayers, wrestlers against flesh and blood,
and not ministers of the gospel, which saith, love enemies;
and render to no man evil for evil, Matt. 5:44.
And this differs from the scribes and Pharisees, who loved their own,
and persecuted others, and stoned others, and drew the magistrates to do it.
But, say the ministers of Christ, '`we wrestle not with flesh and blood,
but against principalities and powers,
and spiritual wickedness in high places.`' Eph. 6:12.
Now those ministers that would have the persons of men slain,
are like Cain that slew Abel, and Jezebel, the beast, and false prophets.
Gen. 4:1 Kings xxi.
They who stone, imprison, and put to death, are as the Jews`' priests,
and those magistrates that execute their malice are as the Jews`' magistrates,
unchristian magistrates.
And so those are they that are wrestling, stoning, imprisoning,
and striking against flesh and blood.
And in the mean time spiritual wickedness rules among them;
and rulers of darkness in high places, where flesh and blood are wrestled against.
So in this state both ministry and magistracy are blind, and are out of the fear of God;
they turn their sword backward whilst they are executing the priests`' malice,
and the priests will strengthen the hands of evil doers.
And provoking to slay, and wrestling against flesh and blood,
and so do not profit the people at all, but stir up the multitude against the just,
that they may keep themselves in their place for their own ends,
admiring the magistrates`' persons, and men`'s, because of their advantage, Jude xvi.
and respect their persons; who show they are out of the faith,
(James ii.) which gives victory over the world, 1 John 5:4.
and out of the doctrine of Christ and the apostles.
Now the magistrates are for the punishment of evil doers,
and for the praise of them that do well: who walk in the life,
which he that doth evil goes from;
where the rulers of darkness and spiritual wickednesses are.
And this magistrate can see; he turns not the sword backward,
he answers that of God in every one, and is for a praise to them that do well, 1 Pet. 2:14.
So every evil doer acts contrary to that of God in him.
Now a minister of Christ wrestles not against flesh and blood,
but against spiritual wickedness in high places;
so every one that does evil acts contrary to that of God in him,
so the higher power goes above him. Rom. 13:1.
So the higher power is above him, and before he was,
all power in heaven and in earth is given to the son of God, John 5:22.
who is above all the powers of the earth,
who lighteth every man that cometh into the world, John 1:9.
But they who do evil go from the light,
and so the higher power goes against them.
The magistrates that are in the power,
are a terror to the evil doers that act contrary to the light wherewith
every one that cometh into the world is enlightened.
The magistrates are in that power which goes over him,
and is a praise to them that are in the light;
and the ministers of God are to bring from under the occasion of the magistrates`' sword.

George Weare being, with his friend, standing in the field near Foord meetinghouse,
as they call it, he neither speaking nor acting any thing against any man,
but standing in the fear of the Lord, with his friend; William Lowry and John Hambleton,
called justices, committed him and his friend to prison,
where they lay twenty and three days: and here is his innocency preached.

The original righteousness was before the fall;
the original of self-righteousness was that which fell, and is in the fall;
that transgressed.

And in the catechism which is tolerated by the general assembly,
and in the catechism of Scotland, called a short catechism, they say,
that the word of God is contained in the scriptures.

[.discourse-part]
_Answer._ The scriptures are writings; and they say, God is the word, John 1:1.
1 Kings 8:27. Solomon saith,
'`the heaven of heavens cannot contain him,`' and you say he is contained in the scriptures.
And you say there are three persons; and the scripture doth not speak of three persons;
and the Jews had the scriptures, and knew not Christ, the word of God.
Then ye tell people of an outward ordinary means,
by which Christ communicates the benefit of redemption; and of the word sacraments.
The scripture doth not speak of three persons, and sacraments; they are Papists`' words;
of them ye have learned them.
The means of salvation are not ordinary or outward; but Christ is the salvation,
who is eternal, Heb. 5:9. and they that come to him, come to the end of the outward, Col. 1:27.
Ye say the sacraments are the effectual means to salvation;
and ye say again, they are not as they themselves,
but only by the blessing of Christ and his spirit in them: so here is confusion.
How do ye differ from the Papists?
For they say he is in them; and ye say his spirit is in them, and where his spirit is,
is not he?
O blind!
Are ye found out?
Go ye home to your mother the Papist.
Where Christ`'s spirit is, he is.
And ye say your two sacraments are baptism and the Lord`'s supper.
The scripture doth not call baptism and the Lord`'s supper two sacraments;
and those names which you have given to them, you and the Papists adore and worship.
Again, you in your catechism, call the first day of the week, the sabbath day.
Where did ever any of the ministers of Christ or the christians unapostatized, call it so?
Are not you come unto the breach,
and guilty of your own judgment of the third commandment,
when ye give another name to the scriptures than they give themselves,
in calling them the word, and calling baptism and the supper the sacraments?
Exod.
xx. Moses saith, '`God spake all these words,`' when he gave the commandments; mark,
words, and the words of Christ are spirit and life, John 6:63. God is the word, John 1:1.
and Christ is the word, Rev. 19:13. and the word became flesh,
and dwelt among us. John 1:14.
And those who had the words of the scriptures, which cannot be broken,
(John 10:35) the law and the prophets,
knew not Christ the word before they were brought
to the light that Christ had enlightened them with,
and were brought to the spirit. John 5:37.
John 8:9. Can the whole world say the Lord`'s prayer in truth,
or was it taught his disciples, or to the world?
do not people draw nigh to God with their lips that say it? Isa. 20:13.
and are not in the light which every
man that cometh into the world is lighted withal.
Can ye say the Lord`'s prayer, which is,
'`forgive us our trespasses as we forgive them that trespass against us,`' without hypocrisy?
How do ye forgive them when ye would have them persecuted and stoned?
You that are teachers of the people; how do ye love your neighbours as yourselves?
how do ye fulfill the law and the prophets, Matt. 7:12. to do as you would be done by?
To you Presbyterians of Scotland I speak, that are teachers,
whose principles are to stone, chop off heads,
and persecute them that are contrary minded to you:
would ye have those that are contrary to your minds stone you to death,
chop off your heads, imprison, and banish you, and persecute, and excommunicate you?
This is the law and the prophets, to do as you would be done by:
as others should do to you, so do unto them.
But Christ, who is the end of the law and the prophets, Rom. 10:4.
saith his doctrine is to love enemies. Matt. 5:54.
and saith, '`if men persecute you, pray for them,
and bless them that curse you, do good to them that hate you,
and pray for them that persecute you, and despitefully use you,
that you may be the children of your Father which is in heaven:
who makes the sun to shine upon the evil and the good,
and the rain to descend upon the just and the unjust.
if ye love them that love ye, what reward have ye?
the publicans and Pharisees do so.`' And the apostatized christians,
who are got into the forms of words, but out of the life of the saints,
of Christ and the apostles, are saluting their brethren only; but saith Christ,
'`Be ye perfect as your heavenly Father is perfect,`' which you stand against.
So ye are they that have denied the one offering
which hath perfected forever them that are sanctified. Heb. 10:14.
And make the blood of Christ of no effect, which cleanseth from all sin;
and the new covenant, which blots out all sin and transgression.
And all upon the earth, professors and worshippers, that call yourselves brethren,
and christians, and offerers, of what sort soever, that have but the name,
before ye offer, be reconciled to your brethren, go leave the gift at the altar,
and be reconciled to your brethren, and then come and offer your gift, Matt. 5:24.
then will the Lord accept your offering.
And all upon the earth that pray, see that ye forgive others that trespass against you,
as you would have the Lord forgive you your trespasses.

Oh!
How is the beauty of the church of the Presbyterians marred and deformed!
Oh! how are they become cages of unclean birds, synagogues of Satan!
Oh! how are their teachers become envious men and murderers, of Cain`'s stock,
in whom the eternal life is not abiding! that would slay, stone,
and chop off heads of strangers, servants, and sons and daughters of the Lord God,
and excommunicate them and put them out of their synagogues.
'`These things have I spoken unto you,
that ye should not be offended,`' John 16:2.
'`they shall excommunicate you, yea,
the time cometh that they that kill you shall think they do God good service;
these things will they do unto you, because they neither know the Father nor me.
These things have I told you before,
that when the time comes ye may remember that I told you of them.`' John 16:4.
So the sayings of Christ are fulfilled by you that excommunicate
and ye are like them that put out of the synagogues of the Jews;
and these are their marks, that they neither know the Father nor the son of God.
These temples, pulpits, priests, that are set up since the days of the apostles,
are amongst the false prophets that Christ said should come, Matt. 7. Matt. 24.
and John saw were come, 1 John 2:18-19. and 1 John 4:1-3. who went forth from them;
whom all the world went after, Rev. 13:3. And these excommunications from you, are,
that none should buy nor sell, but such as worship the beast, and receive his marks. Rev. 13:14.
And it was the beast, and the dragon, and the false prophets,
that would kill and destroy them that kept the testimony of Jesus. Rev. 12.
Here is the patience and faith of the saints that overcome by the blood of the Lamb,
that have the testimony of Jesus, and have kept the commands of God.
So the Jews excommunicated, who had the true temple, true tithes, and true priests,
who had the figure, the type; Christ being come the substance, Heb. 10:34.
the everlasting priesthood, Heb. 7. the everlasting covenant, and the one offering, Heb. 10.
they that went from the priesthood to Christ,
the Jews did excommunicate them out of the synagogues.
Now they did not know the son nor the Father, that did excommunicate, John xvi.
though they had the figures and types of the son of God.
They held up their outward things,
and saw not the son of God the substance when he was come.
So these knew not the son of God nor the Father,
that excommunicated and put out of the synagogues.
And Christ bade them that were to be put out of the synagogues,
not be offended at those things; he told them before they came to pass,
'`that when these things come to pass ye may remember that I told
you.`' Now those are they that Christ said should come,
and the apostles saw were come, that went forth from them; who have got up tithes,
and temples, and pulpits, and priests;
and the priests are excommunicating out of their synagogues.
And these must neither buy nor sell with them, nor eat, nor drink,
nor have any thing to do with them, except they will worship the beast, or his image,
and fall down to him.
And this is the worship of the beast, got up since the apostles,
by them who apostatized from the true church, and went forth from them,
which all the world wondered after and worshipped, and received his mark and his image,
who buy and sell, and let others do so with them,
who are they that make war against them that keep
the testimony of Jesus and the commands of God,
and against the saints and the Lamb; but the Lamb and the saints shall have the victory.
But the Lamb of God, the seed of God, is risen;
the beast and the false prophet are taken, which hath long deceived the nations.
Revelations ii.
The old dragon, the serpent, the murderer, the deceiver, the devourer, Babylon,
the mother of harlots, which hath made all nations drunk with her fornications,
which hath corrupted the earth, Rev.
xiv. which the beasts and the false prophets that deceive the nations, and antichrist,
say are come but now.
These are deceivers of the nations, that say they are come but now;
for Christ said they should come, and John said they were come before his decease,
whereby he said he knew it was the last time.
And in the Revelations he said, all the world went after them;
and all nations have drunk of the wine of her fornications,
and the kings of the earth have committed fornications with her, Rev. 17:2.
(mark the word have,) and the false prophets say, they come but now,
and now is the last time.
And these are the deceivers of the nations that say so.
Now are people but coming from them; and now is the judgment of the great whore come;
and now are the vials of wrath to be poured upon her that hath corrupted the earth,
and now shall they go into captivity.
Rev. xiii.
Rev. i. '`and 18. And now shall people come to that which the false prophets, the beast,
and the mother of harlots, went from, all these heads, and horns, and crowns,
will turn against others with their tongues, languages, and Babylon,
that have been amongst them.
And now is the seed of God risen,
which overthrows all the excommunicators upon the earth, both beast, and false prophets,
and Jews, which seed of God brings to see to the beginning.
Glory to the Highest forever; the seed is at the top of them all, Jews and Gentiles,
beasts and false prophets, and the corner stone is laid.

John Castairs, and James Durram, priests of Glasgow,
when the fast was appointed by the English, kept their houses,
and caused their servants to work,
and took notice of all those that countenanced the English fast;
and the first day they preached afterwards,
said it was necessary that a day of humiliation should be,
and that all people should be humbled for the powers they saw now ruling in the land,
for they were giving liberty and toleration to all sects, and blasphemies,
as Anabaptists, Independents;
and said that the Baptists denied all worship and ordinances,
as they were and ought to be according to the ecclesiastical government,
which government is the true hedge of the church of Christ.

Lodowick Simerell, priest of Munkland, said, before several persons,
that '`no true justice had been, or was, since those enemies came to this nation,
neither would be until the Lord removed them in his own time.`' Henry Foreside,
priest of Lingiah, said,
'`if Paul had been alive he would have stoned the Quakers;`' and '`it
was christian zeal to stone them.`' And many Friends are stoned and beat,
and blood is shed.
Such were those that stoned the apostles and saints,
and haled them before judgment seats and magistrates;
and the chief priests had a hand in putting Christ to death,
persuaded the people so to do,
and the chief priests had a hand in stoning Stephen to death,
and the priests had a hand in casting Jeremy into the dungeon, and into the stocks,
and said he was worthy of death.
And the high priest Ananias examined Paul,
and Peter and John were examined by the priests,
and put out of the temple by the priests and rulers, and charged,
no more to speak in that name.
And such were these who had a form of godliness, but denied the power;
and such ever stirred up the people to blood and tumults against the harmless,
and innocent in the truth.
Therefore come to the light, you that have tasted of the power of the Lord God,
that with it you may see and judge how the priests blinded the magistrates by flattery,
and so came to be the enemies of truth.

How do you receive strangers, ye Presbyterians of Scotland!
And obey the commands of God, and the apostles`' commands, which were,
be not forgetful to entertain strangers; for some have entertained angels unawares?
When ye would have the servants of the Lord prisoned, and stocked, and stoned to death,
or their heads chopped off!
So you are they that are in Cain`'s way, vagabonds from the spirit of God.
Now a vagabond hath not a habitation in God, but wanders from the witness of God in him,
like Cain, who built a city and called it after his son`'s name. Heb. 13:2.
Gen.
iv.

'`I am the light of the world,
that lighteth every one that cometh into the world,`'
saith Christ the saviour of your souls.
You that go from the light ye are enlightened with, are vagabonds,
and have not a habitation in God; and so go into Cain`'s way, are envious,
and would slay; Balaam`'s and Core`'s way, who are with the light condemned;
and like unto those Jews, that haled out of the synagogues, that Christ spake of,
that go in long robes, and are called of men master, but Christ saith,
'`Be ye not called of men master, for one is your master, even Christ.`' Matt. Xxiii.

Christ said, they that went in long robes, loved the chiefest places in the assemblies;
should hale out of the synagogues,
and they that do these things are gone from the light. John 3:19.
John 16:2.

All this persuading of corrupt magistrates to persecute
them that reprove sin in the gates,
in the steeple-houses, streets, and highways, is, because men have a selfish end,
and a private interest to themselves, both professors of scriptures and teachers;
and they that persecute have a selfish honour, and an interest to themselves:
and so the selfish professors, teachers, and magistrates that persecute for them,
have a form of godliness, but the witness lies slain in them.
And they matter not for that rising; for in that rising all the deeds, words,
and actions come to the light, and then, if the witness of God arise in them,
they will not be offended at such as reprove sin in their gates, markets, steeple-houses,
and streets.
For all upon the earth, while they are from the witness of God in them, are corrupted,
and they may get the form of godliness, the form of Christ`'s, the prophets`',
and the apostles`' words, and live out of the power,
and are in the religion that is vain;
for none upon the earth come to the power of godliness,
but they must first come to the witness of God in them,
and there are none upon the earth that ever come
to the first principle of the pure religion,
but they must first come to the witness of God in them.
None know the scriptures given forth from the power and spirit of God,
which was in the saints, but first they are brought to the spirit of God in their own.
particulars.
Come, all you officers and soldiers, now,
after ye have ease and have overcome your enemies without;
take heed lest you sit down in your ease and fulness, and fall down into the earth,
and flesh, and feastings, and fulness, and pride, and so corrupt the earth,
and yourselves, and not come down to the witness of God in you;
whereby the enemy of God and of your own souls might be slain,
that you might come to find rest and peace in God, after your outward wars,
and so come to the inward wars, which take away the cause of the outward,
whereby you may all come into true understanding, to answer that of God in every one;
for they that do evil, act contrary to that of God in them;
to such the sword is a terror, but a praise to them that do well,
who are led by the spirit of God, up to God, who is pure, and out of the evil.
And all magistrates`' swords upon the earth,
should reach to that which is pure in every one to the soul,
so it takes away that which wars against it, that breaks the outward.
So the soul comes to be subject to the higher power that is above the transgressor,
which all the magistrates and rulers upon the earth must give an account to.
And there are none upon the earth that come to worship God in spirit and in truth,
but they first come to own that of God in them;
and there are none upon the earth that are like to retain God in their knowledge,
nor his covenant, while their minds are reprobated from that of God in them.

There all may see the covenant of grace to all men,
and the covenant of light and life with the Father;
he gave him for a covenant of light to the Gentiles, to the heathen,
'`I will make a new covenant with the house of Israel and Judah,`' the people of God,
'`I will write my law in their hearts,
and their minds,`' so saith Christ the covenant of God,
'`I am the light of the world,`' and doth enlighten every one that cometh into the world,
that all men through the light of the covenant of God might believe;
it is the covenant of God, that every man that cometh into the world is enlightened with,
and every one that hates the light wherewith he is enlightened, hates the covenant,
and the light condemns him;
and here all men may see that the free grace of God
that brings salvation hath appeared unto all men.
They that turn the grace of God into wantonness,
and walk despitefully against the spirit of grace, neglect their salvation,
and bring punishment and condemnation upon.
them, as it is written in Jude.

Concerning election, and what is elected.
'`The grace of God which brings salvation hath appeared
to all men,`' to the clearing God`'s justice,
and the fault is in man for his condemnation.

There is a precious thing in these Scots, but there is a filthy, beastly,
dirty thing lyeth over.
