[.style-blurb, short="A Catechism of Christian Religion"]
== A book I have received out of Holland, the title of which is called [.book-title]#A Catechism of Christian Religion,# printed at Amsterdam by John Frederick, stationer, at the sign of the Hope, 1639. The principles in it as followeth.

[.discourse-part]
_Principle._ '`Out of the law, they say,
they learn they should love the Lord God with all their strength, and mind, and soul,
and their neighbour as themselves.`'

[.discourse-part]
_Answer._ Now these words are said, but where these words are performed,
the commandment is known, and God is loved, and his neighbour as himself,
so he loves the creation, the workmanship of God: but where these words are talked of,
and not done, and they say they have not power,
then they are out of that state that the Jews were in that came out of Egypt,
who had power and ability to answer the law of God; to whom the law was committed.
And God is equal and righteous, and commands nothing but what is equal and just,
and measurable, and reasonable, according to that which men may perform;
and such as be gives the law to, he gives power, but if men transgress the law,
they abuse the power, and such were not justified; and may say they had not power,
but that is false, it is a lie.

[.discourse-part]
_Principle._ They say, '`they are not able to keep the word of God perfectly, that is to say,
to love their neighbours as themselves, and love God;
for man is prone to evil-hatred by nature.`'

[.discourse-part]
_Answer._ That which brings men to keep the commandments of God is beyond nature,
to order nature, and to rule nature, and is above nature,
and it is to subject that which is prone to evil, and that nature that the law goes upon;
so he that looks into the law and loves God, is turned from the evil nature,
for the evil makes the nature corrupt.
Man in the beginning had the law, of God within, the commandment;
man in the fall had the commandment given to him, and there he had power,
as man had in the beginning the law and the power;
but they both transgressing abused the power, so became unrighteous.
But God is not unrighteous, or a hard task master, to lay more upon a man than he can do,
as the corrupt wills of men, and the slothful servants look upon God so to do,
as to command them to do the thing they cannot, so make God unreasonable,
they that love the darkness, and their pleasures and lusts more than God,
and so have not regard to God and their neighbour.
For man in the beginning, lost his uprightness by transgressing the law,
and so the devil`'s seed comes to be sowed in mankind, and the image of God lost,
and the image of the devil is set up in man, and so come darkness, hardness, mists,
dimness, and blindness.
And death reigned from Adam to Moses; so then came the law by Moses,
that went over all transgressors,
answered the principle of God in all men that was transgressed,
and the Lord that gave man the law, gave him power and ability,
who said his ways were equal, and righteous,
and they were then to love God with their strength, and their souls,
and their neighbour as themselves.
And such were preservers of the creation, and lovers of the workmanship of God,
but such as were transgressors were destroyers and defacers of the workmanship of God,
and not lovers of God, nor of their neighbour.

[.discourse-part]
_Principle._ '`That the anger of God is most dreadful for the sins wherein they were born.`'

[.discourse-part]
_Answer._ Then you are not the believers, who were born in the sin, nor of believing parents,
if you own the apostle`'s doctrine, for the unbelieving is sanctified by the believing,
'`else were their children unholy,
but now are they clean,`' saith the apostle the minister of God,
if you can believe his doctrine, and bear it, and receive it.
But if you do object and say,
'`born in sin and transgression,`' and '`all by nature the children of wrath;`' yea,
I say, this is the estate the apostle speaks of among unbelievers,
Jews and Gentiles gone astray from the life of God, from the covenant of promise;
but they who come into the life of God, and the covenant of promise, are believers;
'`the believing wife or the believing husband sanctifies the unbelieving,
else were their children unholy, but now are they clean.`' He that can receive this,
let him.
This was the apostles`' doctrine.

[.discourse-part]
_Principle._ '`Because the justice of God requires that the same nature of man which had sinned,
do itself make recompense for sin.`'

[.discourse-part]
_Answer._ All that makes the recompense for sin, is he that never sinned, Christ,
the second Adam, and not the first; so in this your blindness and darkness have appeared.
And it is not the same nature that hath sinned, that destroys sin,
but it is Christ that cleanseth the nature of man
that hath sinned and destroys sin itself,
that is to say, the devil that hath defiled the nature of man,
and so Christ is called the sanctification, justification, redemption,
cleansing man`'s nature, and blotting out the sin and transgression.

[.discourse-part]
_Principle._ '`Salvation is not offered to all men who perished in Adam,
but only to those men who are grafted in him by true faith.`'

[.discourse-part]
_Answer._ Salvation is purchased to all men that perished in Adam though they do not believe it;
for he is the saviour of all men, especially of them that do believe,
and an offering for the sin of the whole world, mark, the world,
and doth enlighten every man that cometh into the world,
that all through him might believe.
And he that believes not, is condemned by Christ the light, the life, the sacrifice,
the offering, who through death hath destroyed that which in them was the power of death,
the devil, and his power, and so entered into his glory.
All that believe in him have life, and all that do not, and receive him not,
have not life, but are condemned through unbelief.
Now if you say that in Adam all died, I say yes;
and that in Christ all shall be made alive to the justification of life, I say yes,
as in Adam all died, so in Christ they come to be made alive.
So they that are believers are holy, so are the believers`' children; a new creation,
a new generation, new creatures, out of Adam in the fall;
the believers passed from death, that came by Adam, to life,
and so in that is a clean creation and holy generation.

[.discourse-part]
_Principle._ '`All things contained in the gospel are summed up in the apostles`' creed.`'

[.discourse-part]
_Answer._ The apostles do not tell us of a creed, but the pope`'s canon-book,
and common-prayer-book; and many things the apostles had to say,
which were not lawful to utter, and many things Christ had to say,
which they could not bear; but the gospel is the power of God,
and that the scripture speaks of, but doth not say the epistles are it.

[.discourse-part]
_Principle._
'`God hath manifested himself in his word, that these three distinct persons are one.`'

[.discourse-part]
_Answer._ Neither the word nor the scripture doth tell us of three distinct persons,
but it tells us of Father, and of son, and of holy ghost; but indeed, as I said before,
the pope`'s canon-book, and mass-book doth so;
for the holy ghost is not distinct from the son,
and the son is not distinct from the Father, but they are all in one.

[.discourse-part]
_Principle._ '`Having our chief hope placed in God,
being assured that nothing may withdraw us from his love.`'

[.discourse-part]
_Answer._ Yet you say you are not able to keep the commandments of God perfect;
then you are drawn from the living God, and you are from the chief hope, Christ;
for they who love God keep his commandments, and such have the chief hope, Christ,
in whom the commandment ends; here love goes forth out of the pure heart:
but are not riches your hope?
And do not riches, and the glory of the world, and the fashions thereof,
draw your hearts away?
And do not your love and hope stand in them,
and have taken up the possession of your hearts more than God?
Therefore, they who keep them not perfectly, keep them not at all.

[.discourse-part]
_Principle._ '`You say Christ hath ransomed your bodies and your souls from sin,
and by that one sacrifice of his body he hath redeemed you.`'

[.discourse-part]
_Answer._ Are your bodies redeemed, and your souls and your spirits that are immortal,
sanctified, and do you glorify God in your bodies, souls,
and spirits which are the Lord`'s? And is there not sin in your bodies,
and are not your spirits corrupted?
Now, they who witness redemption of the body and soul from sin,
these are out of the first Adam`'s state, and are the holy ones,
and these are in the end of the law, and that which fulfils the law, Christ Jesus.
But now if you come to say that you have not sin in your bodies,
and the fruits show themselves by persecution, or envy, rage, malice, pride,
or such wickedness, this shows not the fruits of redemption.

[.discourse-part]
_Principle._ '`You say, that God in Christ loath put out the remembrance of your sins,
and of your corruptions within you, wherein you must fight all your lifetime.`'

[.discourse-part]
_Answer._ Whilst the sins you are fighting with are not blotted out in your own particulars,
this is not the life of the saints, they are not fighting all their lifetime,
but come to the kingdom of God, witnessing sin and iniquity blotted out,
and the everlasting covenant of peace and life with God.

[.discourse-part]
_Principle._ You say, '`You are righteous before God through faith,
though your consciences accuse you for your trespasses against the commands of God,
being prone to evil, yet notwithstanding embrace the benefits of Christ,
as if you never had committed any sin or corruption,
and this is as if you yourselves had perfectly completed the obedience.`'

[.discourse-part]
_Answer._ Where the conscience accuses it is impure, and that the true faith is out of,
for the mystery of faith is held in a pure conscience, and that receives Christ,
and which is not prone to evil, nor transgresseth the commands of God.
But you are out of the perfect obedience, and the faith both, and are in the corruption,
and are not the lovers of God, nor come to Christ the end of the commandments,
who is loved in a pure heart.
And you talk of conscience accusing, and yet say, you are righteous through faith,
that is your ignorance, for faith is held in a pure conscience,
the conscience doth not accuse any but the unsanctified.

[.discourse-part]
_Principle._ '`Not that we please God through the worthiness of our faith, for our works,
the best of them, are imperfect in this life, defiled with sin.`'

[.discourse-part]
_Answer._ It is faith that brings men to please God, which faith comes from him,
and gives victory over that men have lived in and not pleased God;
so there is a worthiness in faith, it is the gift of God, by which men please God,
and have access to him, and by which they are justified,
and through it they overcome and subdue mountains, and raise the dead;
your best works being imperfect, and defiled with sin in this life,
are not wrought in God, but are out of him, in the darkness, they are works of darkness,
imperfect and defiled with sin.
Are not the works of darkness to be condemned for the fire,
and to be out of the law and gospel?
But the works of the saints that are in the faith, created to good works,
are wrought in love, are perfect, because they are wrought in God;
these are distinct from the imperfect, defiled with sin,
and these good works the saints witnessed when they were upon the earth,
which are the works of faith that works by love.

[.discourse-part]
_Principle._ '`Infants that are baptized belong as well to the covenant and church of God,
as they of full age, they by baptism being grafted into the church of God,
so discerned from the children of infidels, so this baptism succeeds circumcision.`'

[.discourse-part]
_Answer._ Then by this all christendom that are baptized
are the church and grafted into the church,
Papists and Protestants and all!
And how is it that your church is in so much confusion then?
for you say they are grafted into the church of God;
and in the church of God there is no confusion, it is the pillar and ground of truth,
without spot or wrinkle; and how is it there is such killing one another in this church,
Papists, and Protestants, Lutherans, and Calvinists, so called?
how is it they are not of one body, but are broken into so many heads?
Now, the baptism of the spirit brings all into one body,
in which spirit is the fellowship and the unity, which spirit is the bond of peace.
And circumcision outwardly was a figure of circumcision within, and that it typed forth.
And baptism without typed forth baptism within; and many may run into the outward water,
that doth decrease, and do not come to the body of Christ the light,
as you may read in the fifth of John; for none are grafted into Christ the body,
but they who come to the light John bare witness of.

[.discourse-part]
_Principle._ '`You say, though Christ is in heaven, and you on earth, you are flesh of his flesh,
and bone of his bone.`'

[.discourse-part]
_Answer._ And yet before you said your consciences accused you,
and your best works in this life were sinful and imperfect,
and you could not keep the commands of God; now this is confusion,
they who are of the flesh and bone of Christ are with him,
and sit with him in heavenly places, for their conversation is in heaven.

[.discourse-part]
_Principle._ '`We are grafted into Christ by the holy ghost now,
according to his human nature on earth.`'

[.discourse-part]
_Answer._ Human nature is from the ground, this is old Adam, but Christ, according to the flesh,
was of Abraham and of David.
The scripture doth not tell us of human nature, for human is from the ground,
but Christ is from above;
and though he were a lamb slain from the foundation of the world,
yet his nature was not corrupted, nor his flesh saw no corruption.
He that is made of the dust is human, he that is the Lord from heaven, is not human;
so you err in your understandings that do not distinguish.

[.discourse-part]
_Principle._ '`Teaching the gospel and ecclesiastical discipline,
by which the heaven is opened to believers and shut against the unbelievers.`'

[.discourse-part]
_Answer._ Christ hath the key which opens to believers,
and '`he is the light which doth enlighten every man that
comes into the world,`' that through it they might believe,
and they that do not believe in the light which Christ hath enlightened them with,
heaven is shut to them, light condemns them, and they neglect the gospel;
upon whom the wrath comes, which gospel is the power of God.
And as for ecclesiastical discipline, it is got up since the days of the apostles,
in the apostacy, which shuts up the kingdom of heaven against men,
that which they should have believed in; that is,
the light Christ hath enlightened them withal, which is the key.

[.discourse-part]
_Principle._ '`And such you say that are wicked men, the sacrament is to them forbidden,
and they are shut out of the congregation.`'

[.discourse-part]
_Answer._ Do you not call baptism sacrament, and have you given them it,
and did not you say they are grafted into the church by baptism?
and cannot Judas take the sop?
But for the word sacrament you may look in the old canon-book, the mass-book,
and such like.
You give your sacrament to the covetous and proud, to the lovers of gold,
and to them that are surfeited and drunk with the cares of this life,
and such as are in superfluity, such you will give it to;
and common outward drunkards you will keep it from: now are not all, those forbidden,
and out of the church of God?
Read and judge yourselves, and amend your lives, and repent,
that you may come into the spirit that baptizeth into the body of Christ.

[.discourse-part]
_Principle._ You say, '`Christ hath redeemed you by his blood,
and renewed you by his spirit to his image.`'

[.discourse-part]
_Answer._ And yet your works before were sinful, and you break the command of God.
Now this shows still, that you have but the form, and are unrenewed in spirit, unchanged,
unconverted, and not in the image of God,
and not in the thankfulness of God out of a pure heart.

[.discourse-part]
_Principle._ '`To mortify the old man is to be sorry for your sins.`'

[.discourse-part]
_Answer._ A man may be sorry for the sin he hath acted, but that which puts off the body of sin,
is the spirit, and that which purifies the heart is the faith,
and that which cleanseth from all sin, is the blood of Jesus,
and that which blots out all sin and transgression, is Christ the covenant of God;
and Christ within, manifest in the flesh, condemns sin in the flesh;
so having him within, the body is dead because of sin.

[.discourse-part]
_Principle._ '`Thou shalt not make to thyself any graven image,
the likeness of any thing in heaven above, or in the earth beneath, or worship them,
or bow down to them; thou shalt not take the name of the Lord in vain, etc.
And remember thou keep holy the sabbath day,
for six days thou shalt labour and do all thou hast to do, but on the sabbath thou,
nor thy ox, servant, or stranger shall do no manner of work.`'

[.discourse-part]
_Answer._ Do you not make graven images and pictures of things in heaven,
and of things in the water, and of things in the earth,
and so make similitudes and representations, and adore them,
and set them up in your houses?
And is not this quite contrary to the commandment of God?
And have not the Papists been your examples for these things, and not the apostles?
And do ye not take the Lord`'s name in vain daily in your streets and markets,
in your buying and selling?
And do you not take the Lord`'s name in vain, when you call upon him with your lips,
but your hearts are in your covetous practices, and full of hatred, envy, pride,
voluptuousness, ambition, self-honour, and deceit?
And this is taking the Lord`'s name in vain, to call on God with your lips,
while your hearts are after this manner.
Do your servants, or strangers, or cattle rest on the seventh day?
and do you not keep markets and fairs on that day,
which the Lord gave to the children of Israel, after the fall of Adam,
for a sign of the restoration of the creation, that neither man nor servant, nor family,
nor ox, nor ass should work on that day, but rest so it was a sign; the apostle saith,
'`the sabbath day was a shadow of good things to come,
which was Christ,`' the good thing who restores the creation,
and giveth the liberty to horse, ass, ox, and all the creation, unto man, and stranger,
and servant, and redeems man up into the image of God, and renews it,
which hath been lost; and so is restoring the creation,
and giving rest to his people and all the creation, and destroying the devil, death,
and all his works.
Christ, who is the restorer, gives rest to the creation, who was before days were,
by whom all things were made.

[.discourse-part]
_Principle._ You say, '`Thou shalt do no murder, thou shalt not steal,
thou shalt not covet thy neighbour`'s goods, house, or servant,
nor any thing that is his, his wife, or ox, or ass,`' etc.

[.discourse-part]
_Answer._ Do you do no murder?
That was the law without; do you fulfill it in christendom?
Then you do not murder the just principle of God in your particulars.
Do you not quench the spirit in people, and suffer it not to have liberty?
Do you not do murder to the just of God in you, in your own particulars?
And so, then stop it in the general, for opening its mouth, with all your force and might?
And are you not murderers there?
And do you not steal by sea and land, and cozen, and cheat, and wrong one another?
Nay, do you not steal the words from your neighbour, and the prophets, and the apostles,
and Christ, which you never came into the life of; is not this called theft and robbery?
For you have not received it from the Lord God, as the prophets and the apostles,
as his son and servants did: so all your profession, church,
and ministry stand in the robbery, and have not received it as they did,
as the true apostles, prophets, and ministers did; ye all stand in the robbery.
And do not you covet your neighbour`'s goods, oxen, cattle, and servants, and wife?
and one getting from another goods, and getting servants one from another;
is not this out of the love in which the commandment ends,
where there is serving one another in love?
And are not all covetous idolaters shut out of the love in which the commandment ends?
And hath not this been the practice in the whole Christendom, coveting men`'s goods,
servants, cattle, and that which is not theirs?
Is not that out of the law and gospel, and out of a pure heart,
where the commandment is known and done?
And that which it ends in is Christ, and love keeps the commands of Christ,
they that love do not covet, and they are not idolaters.

[.discourse-part]
_Principle._ '`We are not to make any images to be tolerated in the churches and chapels,
or figures of things made, for it is not seemly,
for God will have his church be taught by living preaching.`'

[.discourse-part]
_Answer._ How is it that your churches so called,
are so full of pictures and images of males and females,
representing a figure of Adam and Eve, the apostles, and Christ in your houses,
and on signs, of fish in the sea, and lions and other creatures upon the earth,
and of things as you imagine in heaven?
Are not all these your inventions, your works and inventions,
you have learned of the Papists, and they from the heathen, not from the apostles?
And you have daubed your churches, and flourished them with your pictures;
these things you call your churches, but the church is in God,
which the gates of hell cannot prevail against, but a shower of rain, or an earthquake,
or a great wind, will prevail against your church,
and the devil may come with his carnal weapons and throw it down,
but the church of Christ, the pillar of truth, is that which the devil is out of.

[.discourse-part]
_Principle._ '`You say a man may swear before a magistrate,
and that this kind of swearing is ordained by God`'s word,
therefore well used of the saints,
and it is not lawful to swear by the saints or other creatures.`'

[.discourse-part]
_Answer._ Here ye are out of the doctrine of Christ, who saith,
'`swear not at all,`' and out of the magistrates`' state the apostle speaks of,
and out of Christ`'s doctrine and the apostles`',
and have broken the commands of Christ and the apostles`' doctrine, which say,
swear not at all: so you wrong Christ Jesus, and the word of God you deny.
And though Abraham sware, and Jacob and Joseph sware, the prophets and Moses sware,
David sware, and the angels sware, and men in strife swear by the greater,
and the oath ended the strife and controversy amongst men; yet Christ saith,
'`before Abraham was I am,`' he reigns over the house of Joseph and Jacob,
he is the end of the prophets, he is the end of Moses, he is the end of men of strife,
and brings peace on the earth.
The angels must bow down to him,
that saith '`swear not at all,`' who was before Abraham was, and David called him Lord,
who was greater than Solomon, And '`this is my beloved son,
hear ye him.`' Now which of you hear him?
They said in the old time, perform thy vows to the Lord; this was the old time,
the day of Abraham, David, the prophets, Moses, and Solomon; but Christ,
who was before all time, by whom all things were made, the oath of God, ends the time,
and saith, '`swear not at all;`' so do his true ministers and the apostles,
'`Above all things, my brethren, swear not at all, neither by heaven, nor by earth,
lest you fall into condemnation.`' Now here were true brethren,
that kept the doctrine of Christ and the apostles, and his commands,
which swearers break, who are got up since the days of the apostles,
who are the false brethren apostatized from the true.
So now the fruits of false and true brethren are seen, who keep the commands of Christ,
and walk in the doctrine of the apostles, and who do not.

[.discourse-part]
_Principle._ You say,
'`that in the fourth commandment God doth command that the ministers of the gospel,
and the schools of learning, should be maintained,
and on the sabbath frequent studiously divine assemblies, hear the word diligently,
using the sacraments.`'

[.discourse-part]
_Answer._ Your schools, your sacraments, your sabbath, your studies by men,
your ministers at your schools, you have made since the apostles, and not by the Lord,
but among yourselves, who are apostatized from his spirit;
for the apostles had not schools.
And the apostle said, '`let no man judge you in meats or drinks, new moons,
and sabbath days,
etc. for the body is Christ,`' and he brought them off from these services to Christ,
the substance, the body, who ended the sabbath days, and the offerings upon them,
who was before days, who is the rest for his people, and did not bring people into days,
but into Christ, by whom all things were made, who was Lord of the sabbath.
And such meet on the first day of the week, and are taught of God,
and outstrip all your teachers made in schools, and by the learning of men;
and so are not of man, nor by man, but the outward schools are of men, and by men.

[.discourse-part]
_Principle._ You say,
'`The fifth commandment enjoins you to yield obedience to
the faithful commandments of them that are over you,
and the catechism.`'

[.discourse-part]
_Answer._ The fifth commandment enjoins that men should obey the command of God, not of men,
nor the catechism, nor such stuff as is in this catechism,
but they who are come to Christ come to the end of the commandments, the end of the law,
him by whom the world was made, and who was before it was made.

[.discourse-part]
_Principle._ You say, '`The meaning of the seventh commandment is, that you should live temperate,
modest, and chaste, and holy in wedlock.`'

[.discourse-part]
_Answer._ Is this so, have you not broken wedlock both with God and man,
and lost the chaste virgin state; and so got up into intemperance, immodesty,
unchasteness, into uncleanness, and filthiness,
and so show by your fruits that you neither come to keep this commandment,
nor to Christ the end of it?

[.discourse-part]
_Principle._ You say, '`The eighth commandment doth not only forbid robbery,
but covetousness after other men`'s goods, evil, witchcraft,
devices to seek after other men`'s goods.`'

[.discourse-part]
_Answer._ Then are you not all found in this seeking and
endeavouring by force after other men`'s goods,
and hath not this been much of your practice both by sea and land,
of many people in the whole Christendom,
who have been found in this witchcraft you speak of?
And is not all this to be judged with the spirit of the Lord God to be out of his commands,
and out of the love of God and Christ the end of the law?
Therefore repent, and amend all your ways, doings, and lives,
that you may return to the Lord, and find peace and rest in the time of need.

[.discourse-part]
_Principle._ You say, '`The ninth commandment saith, bear not false witness against any man,
and you should shun lying, and not falsify any man`'s word, nor backbite, nor reproach,
and shun all careless kind of lives,`' etc.

[.discourse-part]
_Answer._ How is it then that there are so many false witnesses, backbiters, reproachers,
rash condemners, men living in such careless kind of lives and deceit, among you,
which is the devil`'s works?
This is all out of the commands of God and the law, and short of Christ the end of it,
and the fruits of this have now showed themselves.

[.discourse-part]
_Principle._ You say, '`No one that is converted unto God perfectly,
observes and keeps his commandments.`'

[.discourse-part]
_Answer._ Then no man loves God amongst you, nor are you converted;
neither are you of the seed of the woman that keep the commands of God;
neither are you the children of God that John speaks of,
that keep the commandments of God, that love God; neither are you believers,
for Christ is the end of the law to them that believe.

[.discourse-part]
_Principle._ You say, '`There is no man in this life able to keep the law of God,
and why then should God`'s law be so exact and severe?`'

[.discourse-part]
_Answer._ The law of God is just, is not so exact, nor so severe, but is just and equal,
and righteous, and perfect, and good, and not, as you look upon it, exact and severe.
Now Christ the righteousness of God is the end of the law,
and the man that loves God keeps his commandments,
and comes to the end of the commandments, that is, love out of a pure heart.

[.discourse-part]
_Principle._ You say, '`Christ teacheth you to call God Father, in the beginning of your prayers.`'

[.discourse-part]
_Answer._ Christ taught that to his disciples who were his children, his sheep,
but that was not spoken to the world that did not believe in '`the light that enlightens
every man that comes into the world;`' for the Pharisees could call him Father and Lord,
but did not the things he commanded them, and such Christ said were of the devil,
and the prayers of such he rebukes; the disciples could pray this in truth.
So you must be born again of God, not committing sin,
when you call God Father you must be like him, else you are bastards,
begotten of the wicked one, children of the transgressor, sons of the sorcerer.
The prophet speaks of children of God distinct from such as call him Father in the transgression,
whom he hath not begotten, the transgressor`'s birth, that is a bastard,
a false conception.

[.discourse-part]
_Principle._ You say, '`Forgive us, as we forgive them that trespass against us.`'

[.discourse-part]
_Answer._ Is it so?
Do ye do so?
And would you be forgiven no otherwise,
but as ye forgive others that have trespassed against you?
Would you have God forgive you who trespass against him, no other ways,
but as you forgive trespasses against you?
Mark, whether you would have as you say?
And whether here be not justice?
And whether you can witness you are forgiven that do not forgive others?
Whether you have the assurance within you?

[.discourse-part]
_Principle._ You say, '`The particle amen, means the things sure, out of doubt,
for your prayers are much more certainly heard of God,
than you feel in your hearts that you unfeignedly desire the same.`'

[.discourse-part]
_Answer._ Amen, or so be it, for the promise is to the seed, yea and amen,
which fetches up the seed out of time who hath been in prison in time,
and brings it by the power of God where there is no time, and there is yea and amen;
and the Lord accepts no prayer from the corrupt heart, or such whose works are sinful,
whose best works are sinful, for it is the praying, preaching, singing, hearing, tasting,
discerning, handling, and feeling in the spirit the Lord accepts.
The Lord knows the mind of the spirit, where it groans, which spirit guiding the man,
gives him an understanding of the signification of it,
and so every man being reproved with the spirit, if he hears it and is in unity with it,
and turns to it, it will bring him to turn to God, and be at unity with God,
and here his prayers are acceptable to him;
and so every man being enlightened that comes into the world,
every man that turns to the light Christ hath enlightened him with, is turned to Christ,
from whom it comes, which brings him to know Christ, and to ask in his name,
who is the way to the Father, and is in the Father, who is God, Emmanuel, Christ Jesus,
and so forth, to the end.
