[#ch-124.style-blurb, short="Fifteen Priests in and about the Island of Wight"]
== Robert Tuchin, John Barnes, Edward Buckler, Robert Dingly, James Crosswick, John Martin, Vincent Sparke, Joshua Tompkins, Simon Pole, Thomas Clarke, William Harby, Martin Wells, William Bignall, Richard Beminster, Matthew Herne. Their principles are as followeth, who are teachers in and about the Island of Wight; and these fifteen priests are in the rear of the army of Babylon against the Lamb.

[.discourse-part]
_Principle._ '`That the good things, which the glorious gospel of Jesus Christ brings to sinners,
was first heard at Jerusalem.`'

[.discourse-part]
_Answer._ The gospel, which is the power of God, which is the glad tidings to sinners,
was preached to Abraham, before ever it was heard at Jerusalem,
and the shepherds in the field received the message of the
good tidings of the glorious gospel from the angel,
which was sent to them of the Lord; who said, '`Behold,
I bring you good tidings of great joy,`' and this
was before the gospel was heard at Jerusalem.
And all the fathers and prophets, that heard the power of God, heard the gospel;
for the gospel is the power of God, glad tidings to the seed,
and great joy to the poor captives.
And this gospel was preached to Adam;
the seed of the woman was promised to bruise the serpent`'s head, and that was, and is,
the power of God, the glorious gospel;
but as for such as know no gospel in manifestation nor operation,
but only the scriptures which do but declare of the gospel, show that they are without,
in the world, and have no other knowledge of the gospel, but natural knowledge,
which is not unto eternal life, nor can edify the body of Christ, which is immortal.

[.discourse-part]
_Principle._ '`The good tidings, which the glorious gospel of Jesus Christ brings to sinners,
was a great mercy to the Jews,
and a very gracious dispensation to us sinners of the Gentiles.`'

[.discourse-part]
_Answer._ The good tidings, the glorious gospel, is in itself a mercy to all;
but only a mercy in manifestation and operation to them that receive it,
whether Jews or Gentiles, and it is a judgment and a condemnation,
to all that do not receive it, both Jews and Gentiles.
But as for you fifteen priests, you have included yourselves among the sinners,
showing that you are yet unconverted to the precious faith,
which brings out of all sin and gives victory over it.
And they who are converted are changed and renewed from being sinners, to be righteous,
and these are not sinners of the Gentiles,
(as is manifest you yet are,) but they are believers of the Gentiles,
who are made righteous in the righteousness of the second Adam,
who hath quickened them from death to life, and from sin to God;
but upon such that remain sinners of the Gentiles, and receive not the gospel which,
is the power of God, the dispensation of it is judgment and condemnation;
and this shall the testimony of God in every man give witness to.

[.discourse-part]
_Principle._ '`Dark we are since the cloud of sin overshadowed our minds,
our brightest notions are stained, our light eclipsed by nature,
we are chained up into a cave of darkness; taking mere notions to be things substantial,
and substance to be shadows; and as our eyes are dim and cannot see much,
so our sloth is great and heedlessness inexcusable,
our ignorance of God may be charged on the want of meditation in all men,
the sins of teachers being teachers`' sins.
Admit the minister be sinful, shall the people despise his doctrine?
Scripture is scripture though uttered by Satan.`'

[.discourse-part]
_Answer._ The ministers of Christ Jesus who were called and sent of him, were light in the Lord,
and were translated from darkness to the light, and from Satan`'s power to God,
and the cloud of sin was not over them, for that was removed,
and they were as a city set on a hill, and were the lights of the world,
and their minds were spiritual and enlightened,
and not overshadowed with the darkness nor with the cloud of sin,
as it is with these fifteen priests, whose brightest notions are stained,
and their light eclipsed by nature, as they confess.
But thus it was not with Christ`'s ministers, for their knowledge was in the spirit,
and what they knew, was in, and through the spirit, and they were changed in nature.
And their light, which was Christ, was above nature, and beyond nature,
and not eclipsed thereby; neither were they chained up in a cave of darkness,
but were as candles lighted, and as a city set on a hill that could not be hid,
and they delivered forth to the world the pure truths of the gospel of Christ,
which were not stained nor polluted, but pure and holy.
And in that you take notions to be substance, and substance to be shadows,
this is your great ignorance and blindness; but thus do not the true ministers of Christ,
neither are their eyes dim, but the Lord is their light,
and this promise is fulfilled to his ministers whom he hath sent,
the Lord is become their everlasting light; but to you his promise is not fulfilled,
whose eyes are dim, and sloth great, and heedlessness inexcusable;
as it was with the false prophets and dreamers of old, whom the Lord never sent,
and thus it is with these fifteen priests, according to their own confession!
But the ministers of Christ were not so, neither were they in sin, nor in ignorance,
but had received the knowledge of God, and were known of him;
and if the minister be sinful, he is not sent of God, but hath run and never was sent,
and his doctrine is despised, and not profitable,
for scripture in the mouth of the devil, is but a temptation,
no more is the doctrine of sinful men, as taught by them; for if the minister be sinful,
he cannot convert sinners to God, nor turn them from darkness to light,
nor from Satan`'s power to God,
which is the work of the true ministers that have received the gift of the holy ghost;
as it is manifest these men have not by their own confession.

[.discourse-part]
_Principle._ '`We are presented with a necessity of acknowledging that the
light of the moon with us is as the light of the sun,
and the light of the sun as the light of seven days.`'

[.discourse-part]
_Answer._ How doth this confession of yours answer to your last?
Let all wise and sober people judge, how confusion hath uttered forth itself.
What!
Your light eclipsed, and you chained up in a cave of darkness, and your eyes dim,
and yet the light of the sun with you as the light of seven days!
Is there any thing in both these confessions, except ignorance, and a heap of confusion,
and plain contradictions, that all may see your own confusions, out of your own mouths?
But to them who are come to the fulfilling of the promises of God
where the light of the sun is as the light of seven days,
sin and iniquity are blotted out, and transgression is done away,
and life and immortality are brought to light, and the glory of the Lord is revealed;
and they that are in this promise, are come out of the apostacy,
and out of the beast`'s kingdom of darkness, where you yet remain, as is manifest;
for you are such as Christ said should come, and as John saw were come,
who went into the world and deceived nations,
but now the nations are gathering from you again,
into the fellowship of the mystery of the gospel,
which gospel hath been lost (I mean the receiving of it by the holy ghost,
and the preaching of it as the spirit of God gave utterance) for many generations.
But that gospel again is to be preached, and it is going forth to nations, tongues,
and people, and great Babylon shall be confounded,
and all her merchants shall weep and lament for her fall.

[.discourse-part]
_Principle._ '`We the unworthy ministers of Christ whose names are under written,
having waited upon God in a way of earnest prayer,
have jointly agreed to communicate our thoughts,`' etc.

[.discourse-part]
_Answer._ They that are true ministers of Christ are not unworthily so, nor in the unworthiness;
and being unworthy, to what purpose do ye wait upon the Lord?
For who are in the unworthiness, God doth not hear nor regard,
nor give his answer to such; and ye having no answer from God,
you must needs agree in your thoughts.
But have you nothing to communicate to your people, but your thoughts, which are vain?
How shall thoughts convert any to God, or establish any in him?
And your prayers that are in darkness are not accepted of him;
for they who are heard of the Father, are in Christ Jesus, and are new creatures,
being changed from death to life.

[.discourse-part]
_Principle._ '`Our deep sense of the ignorance of our hearers puts us upon our prayers to God,
and counsel one to another, what further course to take.`'

[.discourse-part]
_Answer._ Indeed a sad complaint may be taken up concerning this matter, for ignorance abounds,
and many other grievous evils, in your church, and amongst your hearers,
showing that your church is not the true church of Christ,
nor you Christ`'s faithful ministers.
But where or what is the ground of this ignorance that is amongst your hearers?
is not the ministry in a great measure the cause thereof,
and doth not the blind lead the blind,
and have not you been unjust and unrighteous in taking
money and wages of people for teaching of them,
and yet they have not received knowledge, but continue in ignorance?
And as for your prayers and counsel,
the Lord takes no notice thereof till you purge yourselves of your iniquities;
and how should you profit the people, and bring them to the knowledge of God,
while as yet yourselves are shut up in a cave of darkness, as you confess.

[.discourse-part]
_Principle._ "`Speaking of your children, you say,
do not they come into the world with souls naked as their bodies?
nothing but filth upon the one, and nothing but sin upon the other.`'

[.discourse-part]
_Answer._ It is manifest then that you are unbelievers and have not received the faith of Christ,
but are yourselves in an unconverted estate;
for the apostle saith concerning the believers`' children, that they were holy.
If you can receive it, you may.
But as for the soul, that is immortal, for '`God breathed into man the breath of life,
and made man a living soul,`' and sin came by disobedience,
and that separates between man and God, who is pure, and hath all souls in his hand.
But as for you who are in a cave of darkness, the mystery of the soul is hidden from you,
but you confess it is by your means that sin is conveyed to your children, yea,
take it to yourselves, it is your work, and the Lord hath no hand in it, not in sin,
nor in making sinners; and it is manifest you are out of the power of God,
remaining in iniquity, and are out of the covenant of reconciliation.

[.discourse-part]
_Principle._ '`For sending children to us,
we shall briefly offer the duty of it in these particulars:
we are to feed the lambs of Christ as well as the sheep,
they are part of our charge who are to watch over souls.`'

[.discourse-part]
_Answer._ What!
Are children now the lambs of Christ.
and were they in the last, having nothing but sin upon their souls,
being begotten and born in sin?
Sinners are not the lambs of Christ, but children of wrath;
the lambs of Christ are such as are regenerated and born again.
And as for feeding the lambs, how can ye do it, who are taking substance to be shadows,
and shadows to be substance?
The bread of life ye know not, which feeds the lambs and the sheep.
But how many sheep and lambs are found in your flocks?
Do not they by their fruits rather appear to be in the nature of wolves and swine?
Let their fruits witness against them.
And as for your charge, who committed any charge to you?
And as for watching over the soul, the soul is immortal, which you watch not for,
but for money and hire, and casting people into prison if they will not give it you,
and causing the servants of the Lord to be persecuted;
these and such like are the fruits of the priests of England;
but if you watched for the soul, it would be otherwise with you.
But who can gather grapes of thorns, or figs of thistles?

[.discourse-part]
_Principle._ '`We should be full of affection to ourselves if we desired to work upon our hearers;
and our authority in preaching is marred by unholy living.`'

[.discourse-part]
_Answer._ We do believe you;
and it is manifest to the whole nation that your unholy living mars your preaching;
for unholy men have not received commission from the Lord to preach his word.
So you have run and not been sent,
and there is no possibility of working upon your hearers by words,
who give them so evil examples by your practices, by your unholy lives:
and no authority of God`'s presence can be in your preaching to convert sinners,
till you repent and come to live holily and like God.
And this confession of yours hath shamed you;
for Christ`'s ministers never made such a confession;
but they witnessed the authority of God`'s presence in their preaching,
whereby they wrought upon their hearers,
and they answered their preaching by a holy conversation,
and did not mar their preaching by unholy living, as ye confess ye do.

[.discourse-part]
_Principle._ '`Sad one day will be the account of sleepy watchmen, blind seers, and dumb dogs,
that cannot bark to fright the wolves or warn the sheep.`'

[.discourse-part]
_Answer._ Then look to yourselves;
for blind seers are such as do not convert the people
who speak imaginations of their own hearts,
and not from the mouth of the Lord, and use their tongues,
when the Lord hath not spoken unto them, and preach for hire and divine for money,
and seek for gain from their quarter;
and that cry peace to them that put into their mouths,
and prepare war against them who do not: such are blind seers, sleepy watchmen,
and dumb dogs, of whom you speak; whose account indeed will be sad one day.
And these are the wolves that must be frighted, that do put on the sheep`'s clothing,
but inwardly are raveners and devourers,
which went out from the apostles in the days of John,
and which Christ prophesied should come; of whose generation you are,
and not of the generation of the sheep, who ever were persecuted;
and the Lord is beginning to affright you and to gather his sheep,
and this is the Lord fulfilling in this day.

[.discourse-part]
_Principle._ '`Many congregations still continue waste;
none compassionate to tell them of the fire and brimstone from heaven for their sins;
how many shoot off a few pop-guns against their gross sins,
and then lick them whole with ill applied promises,
but the blood of the people shall be required at their hands.`'

[.discourse-part]
_Answer._ Many congregations are waste, and ten thousands of people are as a wilderness,
untilled or unploughed, or unplanted, in the way of righteousness,
and the guilt of this will be laid upon the teachers,
who have long been teaching and have been well paid for the work,
and yet left whole congregations waste.
But it was not so in the apostles`' days,
nor among their churches who were in the faith of Christ Jesus;
but when the wolves in sheep`'s clothing entered, then began congregations to lie waste,
which has continued for many generations,
even while the beast and the whore have ruled over the nations;
all nations have laid waste and been void of truth to the Lord.
And who is it except yourselves that shoot pop-guns against their gross sins,
and then lick them whole?
is it not common to cry peace to them that put into your mouths,
and to prepare war against them that do not?
And is it not common amongst you to apply justification
by Christ to people that are uncovered and unrenewed,
and to apply the promises to that birth that is not heir of the kingdom?
And this is ill applied.
And though you may cry against their unholy lives, yet yourselves being unholy,
this is but hypocrisy, and sewing pillows under arm holes;
and the blood of the people will God require at the hand of such teachers and such shepherds.

[.discourse-part]
_Principle._ '`The most faithful messengers of Christ will
acknowledge they came short of their duty.`'

[.discourse-part]
_Answer._ They that are faithful messengers of Christ, have the answer, '`well done,
thou good and faithful servant.`' Where did Paul, or John,
or Peter acknowledge they came short of their duty?
Have not you slandered the servants of the Lord, thinking them to be like yourselves,
and falsely accusing them that you may seem justified, who are false messengers,
and come in his name when you have no commission from him?
And you come short of every good work, but thus it is not with Christ`'s true messengers,
for they fulfill his will that sent them:
and it is the Lord that worketh in them whose they are,
and whose duty they perform by his spirit.

[.discourse-part]
_Principle._ '`The best of us have stammering tongues in this great work,
and oftentimes we do it coldly and by halves, like Pellifer we see but with one eye;
like Milkes, hear but with one ear; like unicorn, push against sin but with one horn.
Place not good preaching in large speaking, judge of a minister by his brains, not lungs,
by his heart, not throat.`'

[.discourse-part]
_Answer._ This is confessed to your own shame, who do your work coldly and by halves:
it shows you have not the same spirit that was amongst the apostles, who were zealous,
and faithful in the work of the Lord, and did it not coldly nor by halves as you do.
And they saw with their eyes and heard with their ears, and their hearts God had opened,
and they were a terror to all unrighteousness wherever it appeared.
And the way to judge of a true minister is not by his brains, nor lungs, nor throat,
but whether he hath received the holy ghost,
and whether they have the same spirit that was amongst the apostles,
and whether the presence of the Lord be with them, and effect his own work through them?
These are the signs of Christ`'s ministers to judge them by:
so you have missed the true character to judge justly,
and your judgment is false, and it shows you are not guided by the infallible spirit of God.

[.discourse-part]
_Principle._ '`We must attend to the words of the minister, though he himself be fruitless;
in which sense we may be said to gather grapes of thorns, and figs of thistles:
unsanctified ministers may possibly convert and comfort sinners,
though our candle be in a dark lantern, and the saints know not what God is a doing.`'

[.discourse-part]
_Answer._ Christ said, '`Either make the tree good, and his fruit good,
or the tree nought and his fruit nought,`' and '`none can gather
grapes of thorns or figs of thistles;`' but you say the contrary:
and are pleading for fruitless ministers that they should be attended to,
but the apostle exhorted to turn from them that had the form of godliness,
but not the power.
And judge in your own selves how your words agree with Christ`'s and the apostles,
they appear to be quite contrary.
And unsanctified men are not Christ`'s ministers,
nor did Christ ever send unsanctified persons, and they that run and were not sent,
should not profit, nor did profit the people at all,
could neither comfort saints nor convert sinners.
But you are pleading for unsanctified ministers and for sinful ministers,
and say that people should not despise their doctrine; yea,
the doctrine and words of unbelievers are despised and rejected by the saints,
and though you say, '`scripture is scripture though uttered by Satan,`' yet I say,
scripture in the mouth of Satan is temptation and not edification;
and it is true your hearts are dark, and minds are dark, even as a dark lantern,
we do believe it; and the light in you shines in darkness,
and is held in the dark lantern, and no light in you appears unto the dark world,
but your unholy lives and unsanctified spirits, and you know not what God is a doing,
who are unbelievers.
But the saints have the mind of Christ, and know what God is doing;
for his spirit dwells in them,
but you have shut out yourselves that you are ignorant of God and what he is doing;
but Christ`'s ministers, their light shines among men, and their good works are seen,
but you have showed your folly and ignorance to all the world.

[.discourse-part]
_Principle._ '`But what if somewhat in the lives of ministers, contradict the word they preach;
disorderly teachers are pretty well purged out; if any continue,
it is the fault of them that do not bring their wickedness to light,
that such may be rooted out, who make the offering to be abhorred,
the sins of the teachers being teachers`' sins.`'

[.discourse-part]
_Answer._ The true ministers of Christ, their conversations were in heaven,
and their good works and holy lives were agreeable to the word they preached;
but disorderly teachers are not purged out.
To preach for hire, is a disorder, and to cause people to be put into prison,
and to be persecuted, and to be whipped, and to have their goods spoiled,
these are disorderly practices, and such are disorderly teachers,
many of whom there are yet unpurged out.
But now the Lord God is arisen to try and to purge, and to bring wickedness to light,
and to condemn the sins of teachers, and teachers for their sins,
and such shall be rooted out, whose offering is abhorred of the Lord,
because iniquity lodges in their hearts, and their lives are unsanctified,
contradicting in their practices what they preach in words;
such are hypocrites whom God will judge,
and the law will utterly root you out in his season; you that are disorderly,
and out of the order of the true church of Christ.

[.discourse-part]
_Principle._ '`We do not thunder in our pulpits, nor lighten in our conversations as we might;
our thunderings are no more heard by glorifying Christ
than their hallelujahs are by us.`'

[.discourse-part]
_Answer._ You want the word of the Lord, which is terrible, it is not in your mouths,
but the words of your own imaginations;
and your words answer not to the witness of God in the people`'s consciences,
but you are like the dreamers the apostle speaks of;
whose conversations are bad examples to all that look upon you;
your unholy lives give an ill savour, and do not enlighten any man in the way of truth;
and saints, that are glorified, do deny you, and hear you not,
excepting to give their witness against you:
neither do you know what the saints`' hallelujahs are,
who rejoice over the whore that hath made all nations drunk;
but of these things are you ignorant,
and you are shut out from the assembly of them that
can sing hallelujah to God and the Lamb forevermore.

[.discourse-part]
_Principle._ '`It is treason to undertake an embassage without commission: I sent them not,
yet they run, saith the Lord, not knowing why, nor whither,
they can tell no tidings for climbing on high,
with the ape they do but show their own deformity.`'

[.discourse-part]
_Answer._ There is none more guilty than yourselves of this treason,
and out of your own mouths will the Lord judge you.
Where is your commission, and what is it?
Any other except such as the pope gave to his ministers?
having your degrees in your schools and attaining from one art and office to another,
till at last you profess to be attained to the ministry:
but this is not God`'s way of commissioning, but antichrist`'s way,
and the Lord God is risen who will confound it.
For the Lord hath not spoken to you, neither hath he revealed his glory to you,
you have neither seen his shape nor heard his voice, neither are the tidings you bring,
effectual to convert sinners; for you are climbed up another way,
and enter not in at the door, and the ape is truly your figure,
for your deformity appears to the saints,
and all the children of light do see you and your original,
which came up in the falling away of the true churches, when antichrist took the throne,
and the man of sin got up into the temple,
who for many generations amongst you hath shown himself to be God,
and hath been worshipped as God.

[.discourse-part]
_Principle._ '`The accomplices of Korah, Dathan, and Abiram, who usurped the priests`' office,
were destroyed, a warning piece for such as usurp the ministerial function uncalled,
and unordained; let them take heed, when they presume to vent their illiterate,
rude incoherence, and blasphemous stuff.`'

[.discourse-part]
_Answer._ This belongs to yourselves, ye men of unholy lives,
who have usurped the ministry uncalled and unordained of the Lord, and by his spirit;
and you may take warning at Korah`'s destruction,
whom the Lord shall as surely destroy with the fire of his jealousy.
For while the beast hath had power over nations, and the whore made nations drunk,
all this time hath your authority been exalted, by which you have been set up,
and your ministers, without the life that the true ministers were in,
and without that call and ordination which they had, for you are of man and by man,
and you effect not the work of the true ministry of Christ, but are left desolate,
and are desolate of the presence of God,
being yourselves unlearned in the doctrine of Christ,
venting your imaginations out of the truth, and out of the power of God,
and there stands your ministry.

[.discourse-part]
_Principle._ '`Unsanctified ministers may possibly convert to God.`'

[.discourse-part]
_Answer._ No, he that is unsanctified is out of the power of God,
and the word of God abides not in him, and he runs and is not sent,
and it is not possible that such can convert sinners,
who are themselves unconverted from their iniquities.

[.discourse-part]
_Principle._ '`That some learned Christians have been able to squeeze the greatest
mysteries of our religion out of the writings of some heathens.`'

[.discourse-part]
_Answer._ This is the sum of your principles, you fifteen priests,
and here is the sum of your ignorance and wretchedness discovered,
and the vanity of your religion, whose foundation is the writings of heathens,
and the heathens that knew not God; out of their writings is your religion made up,
as you confess.
This is the whore`'s religion that sits upon the beast,
that the world hath long wondered after,
and not the true religion which the apostles and true churches were in.
And they are no christians, no saints,
nor true christians that go to the writings of heathens to squeeze out mysteries;
they that do so, are the christians in the apostacy,
who are fallen from the life of righteousness, such as you and thousands are,
at this day, being without the spirit, and without Christ;
therefore you run to the heathen for knowledge, and shame true christianity,
and true christians, in reputing the heathen wiser than yourselves,
who are fain to run to their writings to make up your mysteries.
And such is your religion, deceit, and vanity, and the mystery thereof, studied for,
out of the heathens`' writings!
This is christianity in the apostacy,
and the religion apostatized from the life of true christianity;
for the true christian religion, the foundation thereof is Christ,
who is the mystery of God, and of life, and salvation,
and the mysteries of our true christian religion,
which we live in that are come out of the apostasy,
are revealed to us by the spirit of the Father that dwells in us,
and is in all that are in the true christian religion,
who deny the heathens and your apostatized christians,
and are come into the mysteries of eternal salvation,
which are not squeezed by imaginations of men, but revealed by the spirit of God;
the great mystery, Christ in us, and the mystery of the kingdom,
all this is made manifest to us, and to true christians,
whose religion stands in the power of God, and not in the tradition of men,
nor fetched from the heathens`' writings.
And this religion will stand forever, but your religion, and ministry, and church,
will the Lord confound, the author of which is the heathens`' writings;
and how then shalt it stand?
It is out of the bottomless pit, and ariseth out of that,
and thither shall it be turned into the pit that hath no bottom.
Oh! how have you blind leaders led the blind, that have been professing to teach Christ,
and faith in him, these many years.
And have you taken so much money of the nations,
and do you now tell us that the greatest mysteries of your
religion are squeezed out of the heathens`' writings?
O ye unrighteous men, blind leaders! the Lord God Almighty is now risen,
and the nations can no longer be satisfied with this religion,
but the Lord is gathering out of your mouths, and you must howl and lament;
all the idle dumb shepherds shall be confounded, and souls delivered,
of which they have made a prey;
for the souls of men have been the merchandise of Babylon`'s merchants,
they have bought and sold the souls of men, they have blinded the eye of the soul,
and trodden it down,
and the immortal soul hath not been respected otherwise than to make merchandise thereof,
to get gain thereby.
There have been many traffickers since the days of the apostles,
that have made merchandise of souls, but the judgment of the great whore is come,
and of Babylon the mother of harlots,
and the Lord God and the Lamb will plead against her,
and the jaws of the wicked shall be broken,
and their hearts shall utterly fail in the midst of them,
and the Lord will reveal his righteousness from heaven,
and by his judgments shall he be known in the earth, a mighty God, and a dreadful;
and his dread and terror shall take hold upon your consciences.
Come down and sit in the dust, for the Lord`'s controversy is against you;
he will bruise you with an iron rod, he will break you as a potter`'s vessel,
and his hand ye shall not escape;
for ye are but like briars and thorns in battle before him,
and like the stubble in which the fire is kindled,
and you will be as the dross in the time of purging, and as reprobate silver:
the Lord God hath said it.
