[#ch-125.style-blurb, short="A Parson`'s Guide, Concerning Tithes and the Law of Tithes"]
== W. S.`'s book, called '`A Parson`'s Guide, Concerning Tithes and the Law of Tithes.`'

[.discourse-part]
P+++.+++ And he saith he supposes, '`that taking away tithes from ministers,
but not taking away tithes from other men,`' etc.

[.discourse-part]
A+++.+++ The law that hath set up tithes, since the days of the apostles, is from the pope,
the false church, the whore.
The true church set up none among the apostles;
and so tithes must be taken away from men as well as ministers,
for they have been set up since the days of the apostles, by the pope`'s law,
and not by the law of God, but by the false church, the whore,
who have set up their tenths, and keep people in the ninths of the earth,
with all their images; for the true priesthood that took tithes,
among whom were all the figures, and types, and shadows,
who took the tenths of the earth, among them was a storehouse for all widows,
and strangers, and fatherless, to come and be filled within their gates.
But there is no such thing among the pope`'s church, not in christendom,
no such storehouse for widows, and strangers, and fatherless; but the widows,
and strangers, and fatherless beg up and down at the mass houses`' doors.
They who set up their lying signs and wonders, who have tithes in the earth,
that take tenths, and keep people in the ninths of the earth, God hath discovered them,
and the false church that set them up, and their law,
since the true church went into the wilderness.
And the apostles that preached Christ witnessed the seed of God,
which ended all the figures, and types, and shadows, and the tenths, and ninths,
and priesthood, and all types, and figures, and shadows, and bowings,
and brought to the beginning, to know the election before the world was made,
and so they witnessed redemption, that brings up out of the earth,
into the everlasting priesthood and covenant, out of the ninths, as well as tenths,
all being offered up to God.
For signs were given to man since the fall,
and tithes since man was driven into the earth;
so man who comes to Christ and the church, comes out of the earth to the beginning,
to reign upon the earth.
And so the Papists are they who lead the people into the earth,
with all their earthly images set up by the earthly,
such as went forth from the apostles, who have set up tithes since the apostles,
and bring people quite into the earth with all their earthly images.
But the apostle brought them up out of the earth, and into the redemption, out of types,
figures, and shadows, and out of tithes, to the election before the world was made,
and so into the everlasting priesthood.
Now the false prophet, beast, and antichrist, the great whore, this woman,
the false church which went forth from the apostles, bring people into the earth,
from the life and election both, that none there are assured of it;
but they bring them into images, and into lying signs and wonders,
and into ninths and tenths, and there nations stick in the earth,
out of the image of God, and this hath been set up by the beast, dragon, whore,
and false prophets, who had the sheep`'s clothing, who are out of the sheep`'s life,
and who are now with that seen, and with that judged.

[.discourse-part]
P+++.+++ And thou sayst, '`Tithes by our law were counted an ecclesiastical inheritance,
oblation, obvention, offerings, this was called mere spiritual,
as were offered to God and holy church.`'

[.discourse-part]
A+++.+++ Here thou hast drunken the whore`'s cup,
who came up since the church went into the wilderness:
and do men hold their estates by ecclesiastical laws, and ecclesiastical inheritance?
Indeed it is a Popish, superstitious inheritance,
and so you may see whence your inheritance comes, and who hath given it you;
but the church of Christ never required any such thing,
but these things have been set up since the days of the apostles, your oblations,
obventions, offerings; and this hath been your cover,
to say they were offered to God and holy church, and thou sayst, tithes, the tenth part,
have been given by the law, to the ministers of the gospel.

By the ecclesiastical law it hath been given to clerks, and vicars, and parsons,
and their curates,
and thou sayst our laymen by the common law could not have had their inheritance
of tithes descendable and grantable as of other temporal possessions,
neither will they pass by the same words in grant, as other temporal possessions will do.
Then men do not hold their temporal possessions by ecclesiastical laws,
but by that which you call your common law.
So all these laws the pope, the whore, the false church were the author of;
which have been got up since the days of the apostles,
by them that went forth from the apostles, into the earth,
who keep people in the lying signs and wonders in the earth, under the false prophets,
and the people must give them their tenths, and put into their mouths,
and they live in the ninths, though they have no storehouses for widows, fatherless,
and strangers; and this is done by the corruptible mystery Babylon,
got up since the days of the apostles and their church: by us she is judged,
and all their ecclesiastical laws and government, by them that are in the law of Christ,
the law of life, that witness the judgment of the great whore to be come,
and the lamb and the saints have the victory,
who are come into the power that the apostles were in.
And these witness the marriage of the lamb, Christ Jesus,
in whom there is no shadow of turning, him by whom the world was made before it was made,
who was glorified with the Father before the world began, who ends the first priesthood,
and its tithes and storehouse, and redeems men out of the earth up to God,
from whence they have been drawn, to know the word of life, which was in the beginning,
by which all things were made.
And who are in it, are in the life,
and the word of wisdom by which all things were made and created,
with which wisdom they know how to use all things
again to the glory of him that created them.
And thus men glorify God, in their bodies, soul, and spirit, which are the Lord`'s,
amongst whom the blessing of God is felt, who in his kingdom reigns,
and among whom the life and power of God dwell.
