[#ch-126.style-blurb, short="Scripture Catechism"]
== Thomas Hodges, bachelor of divinity, rector of Soldren in Oxfordshire, his principles in a book, called [.book-title]#Scripture Catechism,# as followeth, where he goes about to confute errors, who confutes himself among them.

[.discourse-part]
_Principle._ Thou sayst,
'`What godly heart without sorrow should see Christ`'s witnesses prophesy in sackcloth.`'

[.discourse-part]
_Answer._ Instead of sorrowing, you are they that kill them, and persecute them,
and prison them, as you have done many that have prophesied in sackcloth,
and with ashes on their heads in this nation amongst you, the false church,
who are in sheep`'s clothing, since the woman went into the wilderness;
so instead of sorrowing, you persecute, and so thou confutest thyself,
and art finding fault with the Papists and bishops of Rome, and speaking of their errors,
and art found in them.
Did not they set up the tithes, and the mass-houses,
and the colleges where thou wast made a minister,
and give you the names of rectors and curates,
and your means to your colleges and old mass-houses?
Art not thou found in them and among them, their errors, false church, and great whore,
since the true church went into the wilderness,
among them that drink the blood of the saints, with sheep`'s clothing,
having not the spirit as the sheep had, nor in their nature, so in the error?

[.discourse-part]
_Principle._ Thou sayst, '`The scripture speaks of God after the manner of men.`'

[.discourse-part]
_Answer._ The scripture speaks of God after the manner of the spirit, and to the spirit,
whereby men might receive him, and know him by the spirit, which natural men cannot.

[.discourse-part]
_Principle._ Thou queries to know, '`whether the holy ghost be a distinct person,
and the worship of God in three persons.`'

[.discourse-part]
_Answer._ Art thou going about to confute the Papists`' errors, and hold them up,
and justify them, which the scripture doth not?
Matt.
xxviii.
But the Papists`' common-prayer-book, and old canon-book speak of three persons,
but the scripture speaks of Father, son, and holy ghost; and thou speakest of Christ,
but yet are not come to the light which Christ hath
enlightened every man who comes into the world with.
And thou speakest of Adam`'s being the image of God,
and yet art not come to Adam`'s state as he was in the beginning;
so therefore knowest not redemption, nor predestination, nor election,
but art found in Adam`'s state, in the fall and reprobation.
Thou speakest of ordinances, and yet art a transgressor of the commands of Christ,
who art called of men master, and art an imitator of the Pharisees`' doctrines.
Thou speakest of the church,
but art found one of those that are dressed with the whore`'s rags,
since the true church went into the wilderness.
Thou speakest of the magistrates, yet art not in the higher power, which goes,
over all sin and transgression,
which answers the transgressed in every man upon the earth.
Thou speakest of dogs, and evil workers, seducers, and heretics,
who art doing their work,
as your jails and prisons may witness in the nation and whole Christendom,
the fruits of dogs and evil workers, and seducers, and heretics,
which was not Christ`'s work nor the apostles`'. Thou speakest of the commonwealth,
but yet art out of that which is the general good to all men, Christ,
the light of the world, who is the saving health:
all power in heaven and earth is given to him, in whom men have wisdom,
by whom all things were made and created,
to order the things by the wisdom by which they were created.
Thou speakest of soldiers, and yet art not come to John, a man sent from God,
but art from the colleges, the Papists`' houses,
since the church went into the wilderness; and made by the will of man,
and set up by the dragon`'s power,
so art not come to the light that John came to bear witness to,
that did enlighten every man that comes into the world;
so art short of rectifying the soldiery,
who stoppest up the eye by which they should see.
Thou speakest of the error of the Quakers, who art found in error thyself;
not come to see that which must be shaken, before that do appear which cannot be shaken,
nor come to the trembling of the devils;
not knowing the strong man bow himself that hath kept the house, who is at peace,
who is the author and ground of the error,
and he that is stronger than he that kept the house, to make the devil tremble,
and shake the earth where he hath had his foundation, yea, and the heavens also.
Thou also speakest of the first birth, whose habitation is in the earth,
and property there; '`Who made me a divider of men`'s inheritances,`' me,
who am the end of the law?
For the law is just among you to divide to every man his right,
but I who am the end of the law, redeem you from under the law, and out of the earth,
but you who are found in this first birth in the earth, have set up your tenths,
and keep people in the ninths, your greediness of it your presence declares.
Thou speakest of mine and thine in collections, so, self you are found in,
and your coldness in collections for the blind and lame, fatherless and widows,
the streets in London declare you, and the countries abroad.
Yet you are all Christians and baptized, and you wear rings and scarfs, and points,
and others are crying for bread.
Thou speakest of buying and selling,
etc. who art arming thyself to hold up the honour of the beast;
and as for your buying and selling,
the fruits of the great whore have declared themselves, who make merchandise of souls,
and all other things, being out of the law of equity, which who acts in,
acts in the will of God.
Thou speakest of good-morrow and good-evening, and would blind the world,
though thou broughtest scripture for it,
and makest them believe it is the Quakers`' error to say the contrary.
The morning is good, and the evening is good, and all is good that God created and made,
as it was in the beginning, but by transgression they come to be vile and evil,
by going out of the truth, as things were created,
and standing in the truth are all blessed.
Thou speakest of giving of thanks, and craving a blessing,
and yet you say you must have a body of sin whilst you are upon earth;
so your thanks and your blessings are from unclean lips,
in the mouth that blesses and curses, and so proceed from the bad fountain.
Thou speakest of christian magistrates, and higher powers,
and thou speakest of saluting and honouring, and bowing down before men,
who art not come to Christ the power of God,
who hath all power in heaven and earth given to him.
Thou art not come to the light that doth enlighten every man that comes into the world,
and hath all power, who subjects all magistrates to himself,
who doth enlighten them to see him; and you are not come to the angel`'s state,
that said to John, see that he did not bow to the angel, but worshipped God,
John saw all the world worshipping the beast.
In the old time they had bowed to the angel, but Christ is come,
to whom the angels must bow, and who is in him, hath life and worship;
and that is honourable which is in the truth, for he who honours God, God will honour,
but honour to a fool is not seemly, but like snow in summer.
And thou speaks of Christ`'s freemen,
and thy choosing it rather than to serve idolatrous masters,
and these freemen that have chosen their freedom, and cannot serve you who are idolaters,
who are spiritual Egypt, to work in the earth for you,
to make you brick to set up your building, you persecute them as idolaters,
you imprison them.
You have the form of godliness, and deny the power;
who will talk of the words but deny the freedom thou speakest of;
one sitting and another standing to serve at meat,
and so you put yourselves among the Pharisees;
and doth not Christ serve the children at the table who is the master?
But in the world there is the lordship and exercising authority,
and men do not know their own brethren; but masters and servants,
as the scriptures declare, is owned, as Paul to Philemon.
Thou speakest of Cain`'s and Abel`'s offerings, you who are the persecutors, and slayers,
and prisoners of the just, offerers up of the earth,
and are the city got up since the true woman went into the wilderness;
but the city of the living God is known again, and you are judged, and your false church.
Thou speakest of salutations, and saluting enemies;
how do you salute those that you imprison till death for your tithes?
What a salutation is that!
And cause them to be whipped and imprisoned for speaking to you!
This is like Judas`' salutation to Christ when he betrayed him,
and not the salutation of the saints.
Thou speakest '`of calling days by other names than the first, second,`' etc. yes,
you and your mother, the Papists`' church, and the heathens, contrary to the Jews,
and true apostles, and true christians, call them Moonsday, and Sunsday, and Friday,
after the name of the great idol in England, and Wodensday and Saturnsday;
and this is contrary to the scripture and the form of sound words,
and contrary to the law of God, which judges the heathen,
and every day is the Lord`'s. And many names you give to your months,
which the heathen are fain to teach you.
Thou speakest of interpreting the word, and giving sense and meanings,
and thus with your interpretations, and senses, and meanings,
you have brought whole Christendom into heaps;
your fruits declare it to be out of the scriptures,
to be out of the spirit that gave it forth:
so your own spirits give the meaning in which lodges the envy,
and serve your own bellies.
But it is the spirit that leads into all truth and not you.
Thou speakest of singular and plural, as though thou neither knew scripture nor accidence.
Thou speakest of the ministers going without gold and silver, brass, or purse, or scrip,
etc. yet you will not go without augmentations, tithes.
And glebe-lands, amongst them you call brethren, your baptized people.
And thou speakest of taking a purse, and scrip, and sword,
and selling his garment to buy one; Christ did so to fulfill the law,
and bids them put it up again, and said it was enough, who ends it;
so you are out of the faith and patience of the saints.
Thou speakest of good men, and calling them good; yes, I say,
such as are full of the holy ghost and of faith; but wicked men, wolves,
and beasts would have this title, persecutors, warriors, and devourers,
in sheep`'s clothing,
therefore is that angry which is exalted above all that is called God,
who sits in the temple of God, that man of sin in you, all,
who cannot have that given to him which is given to God,
by them that are in the discerning.
Thou goest about to prove the word landlord, and would thrust that into the scripture,
when the scripture speaks no such word;
but the law of righteousness which comes from God which is equal and just,
and the prophets, to do as you would be done by.
Thou art speaking of the angels that said, nay, they would tarry all night in the street,
and yet went in; the angels are servants, and their time is not come,
and they may say nay, and yet afterwards see their time to go in.
Thou speakest of perfect, and yet in your doctrine say,
none shall be perfect while they are upon the earth,
and so you have denied the work of the ministry, so profit people not at all.
And thou sayst, '`who can understand the error of his ways;`' and that which thou dost,
thou allowest not, and sin remains in a man, then there the devil hath a habitation,
and there is death; but he that believes is passed from death, and so from the sin.
And that which gives a man to understand his error, turns him from his sin;
such as come to know the anointing within them,
that teaches them that continue in the son of God, and in the Father,
these know all things, but such as are in the transgression, not denying themselves,
know not the error of their ways, as you may see yourselves what you have run into,
whose fruits are come to public view.

[.discourse-part]
_Principle._ Thou speakest '`of Christ speaking in the synagogue, and false Christs,
and false teachers in corners and chambers, and ministers must prove by scripture,
for with that they convince the Jews.`'

[.discourse-part]
_Answer._ Christ went into the synagogues, and the apostles, to show the fulfilling,
and him who was come to fulfill that which they had in the synagogues,
and the apostles showed them out of the prophets and the law that Jesus was the Christ.
And the apostle was not a false Christ, nor a false teacher,
who preached in his own hired house; nor the saints that met in several houses,
who were come off from the Jews and the synagogues;
but they are the false teachers and false Christs that deny the
light that doth enlighten every man that is come into the world,
which Christ hath enlightened them with;
and they are those that draw people into corners, and chambers, and deserts, and say, lo,
Christ is here, and lo, Christ is there,
that are gone and ravened from the light in their ownselves,
that Christ hath enlightened them with.
And such are the corrupt trees that cumber the earth,
whose fruits have sufficiently declared themselves,
who are to be thrown down into the fire,
who will be condemned by the light which they have ravened from in their own particulars;
and to thee this is the word of the Lord; in the day of thy visitation,
the witness in thy conscience shall answer it.
And as for all the rest of thy stuff to the Papists,
who would make people believe thou wast not found among them,
for the errors in this book, first came out of the Papist`'s work,
before thou find fault with them and cry against them,
consider whether thou art not one of them that kill and take possession?
But the time is come when you are all comprehended,
and you and the Papists found in one bond, one cord, one city against the elect.
But he is set over you all, and the judgment of the great whore is come,
who is got up since the true woman fled into the wilderness,
and the man-child was caught up to God;
but now is the man-child come again to rule the nations with a rod of iron, and the lamb,
and the bride, the lamb`'s wife, is known, and the mystery of iniquity is discovered,
and the mystery of godliness is revealed, and the saints shall have the victory,
and the beast, and the false prophet, and the old dragon shall be taken,
and cast alive into the lake of fire;
and the everlasting gospel shall be preached to them that dwell upon the earth,
to all nations, and kindreds and tongues, which is the power of God,
which brings people into unity with God and the scriptures,
and the mystery of God is revealed, and the mystery of iniquity discovered,
and he that was dead is alive again, and lives forevermore.
