[.style-blurb]
== Several scriptures corrupted by the translators.

Jude 14. '`Behold,
the Lord cometh with ten thousands of his saints;`' in the Greek it is,
// lint-disable invalid-characters
in ten thousands,`' ἐν ἁγίαις μυριάσιν Heb. 1:3.
// lint-disable invalid-characters
Express image of his person,`' Gr. substance, or subsistence, ὑποστάσεως
Heb. 2:16.
He took not on him the nature of angels, in the Greek,
// lint-disable invalid-characters
Οὐ γὰρ δή που ἀγγέλων ἐπιλαμβάνεται, which is by true interpretation,
he doth not take hold of angels.
As for the word nature, which is in our English copies,
there is nothing for it in the Greek.
Matt. 3:11.
In Beza`'s Latin Testament, and our English copies, it is tendered,
'`I indeed baptize you with water,`' and from the word, with water,
is the act of sprinkling pleaded for; in the Greek it is, I dip, plunge,
// lint-disable invalid-characters
or baptize you in water, in it, ἐν ὕδατι Col. 1:23.
In the Latin and English copies it is thus:
'`which was preached to every creature which is under heaven;`' in the Greek, it is,
// lint-disable invalid-characters
'`in every creature,`' ἐν πάσῃ κτίσει τῇ
Luke 16:15.
In the Latin and English copies, it is,
'`that which is highly esteemed among men;`'
// lint-disable invalid-characters
in the Greek, it is in men, ἐν ἀνθρώποις 1 Cor. 15:31.
In our English copies it is, I protest by your rejoicing, etc.
Now, _I protest_ is added, for there is nothing for it in the Greek,
// lint-disable invalid-characters
καθ`' ἡμέραν ἀποθνῄσκω 1 Cor. 2:6.
'`We speak wisdom among them that are perfect,`' in the Greek it is,
// lint-disable invalid-characters
_in them that are perfect,_ ἐν τοῖς τελείοις Rom. 8:29.
In the English and Latin copies it is,
'`that he might be the first born among many brethren,`' in the Greek it is,
// lint-disable invalid-characters
_in many brethren,_ ἐν πολλοῖς ἀδελφοῖς Matt. 28:19.
In the English and Latin copies it is,
'`baptizing them in the name,`' in the Greek it is, _into the name,_
// lint-disable invalid-characters
βαπτίζοντες αὐτοὺς εἰς τὸ ὄνομα Matt. 6:7.
In the English copies it is,
'`for they think they shall be heard for their much speaking,`' in the Greek it is,
// lint-disable invalid-characters
in their much speaking, ἐν τῇ πολυλογίᾳ 1 Tim. 3:16.
In our English and Latin copies it is,
'`great is the mystery of godliness, God was manifest in the flesh,
justified in the spirit, seen of angels,
preached unto the Gentiles;`' in the Greek it is, _preached in the Gentiles,_
// lint-disable invalid-characters
ἐκηρύχθη ἐν ἔθνεσιν Rom. 11:2.
In the Latin and English copies it is,
'`wot ye not what the scripture saith of Elias;`' but in the Greek it is, _in Elias,_
// lint-disable invalid-characters
ἐν Ἠλίᾳ Heb. 1:1.
// lint-disable invalid-characters
'`God, etc. spoke to the Fathers, by the prophets;`' in the Greek it is,
// lint-disable invalid-characters
_God spoke to the fathers in the prophets,_ ἐν τοῖς προφήταις

'`Hath in the last days spoken unto us, by his son;`' in the Greek it is,
// lint-disable invalid-characters
_hath spoken unto us, in his son,_ ἐν Υἱῷ Rom. 15:6.
'`That you may with one mind, and one mouth, glorify God;`'
// lint-disable invalid-characters
in the Greek it is, _in one mouth,_ ἐν ἑνὶ στόματι Rom. 1:19.
In the Greek, Latin, and English copies it is,
(speaking of the Gentiles,) '`that which is known of God, is manifest in them,`' or,
// lint-disable invalid-characters
made known in them, φανερόν ἐστιν ἐν αὐτοῖς; though some dare say, and do say,
among them. Amos 3:6.
'`shall there be evil in a city,
and the Lord hath not done it?`' This is the English translation; in the Hebrew it is,
'`shall there be evil in a city, and shall not the Lord do somewhat?`'

Heb. 5. last verse.
'`Strong meat belongeth to them that are of full age:`' in the Greek it is,
// lint-disable invalid-characters
'`strong meat belongeth to them that are perfect,`' τελείων John 8:6.
In our English copies it is, '`Jesus stooped down,
and with his finger wrote on the ground, as though he heard them not,`' as for the words,
(as though he heard them not,) they are added by the translators,
// lint-disable invalid-characters
for there is nothing in the Greek for them, τῷ δακτύλῳ κατέγραφεν εἰς τὴν γῆν
John 1:14.
The word became flesh, and dwelt amongst us; in the Greek it is, in us,
// lint-disable invalid-characters
ἐσκήνωσεν ἐν ἡμῖν By true interpretation it is, the word became flesh,
and pitched his tent in us. Heb. 10:20.
In the English copies it is,
'`by a new and living way;`' in the Greek it is, '`of late slain,
// lint-disable invalid-characters
and living way,`' πρόσφατον properly signifies _recens mactatus,_ lately,
or of late slain, saith Leigh and Pasor.

'`If any one want light, let him look upon the law and the testimony,
whether they speak after this meaning; if he do not this, he stumbles and suffers hunger,
and if he suffer hunger, he is not patient, but blasphemeth his king and his God;
then looketh he upward and downward to the earth, and behold,
there is trouble and darkness; vexation is round about him, and the cloud of error,
and out of such adversity shall he not escape,
even like as in time past it hath been seen well.`' This is the old translation.
Isa. viii.

New translation thus.
'`To the law and to the testimony, if they speak not according to this word,
it is because there is no light in them;
and they shall pass through it hardly bestead and hungry,
and it shall come to pass that when they shall be hungry,
they shall fret themselves and curse their king and their God, and look upward,
and they shall look unto the earth, and behold trouble and darkness,
and dimness of anguish, and they shall be driven to darkness.`' Isa. 8:20-22.

Old translation, Prov. 23.
'`When thou sittest at the table with a lord,
order thyself mannerly with the things set before thee; measure thine appetite,
and if thou wilt rule thy ownself, be not over greedy of his meat,
for meat beguiles and deceives.`'

New translation thus.
'`When thou sittest to eat with a ruler, consider diligently what is before thee,
and put a knife to thy throat if thou be a man given to appetite.
Be not desirous of his dainties, for they are deceitful meat.`' Prov. 23:1-3.

Old translation, Amos 3.
'`Cry they out alarum with the trumpet in the city, and the people not afraid?
Cometh there any plague in a city without it be the Lord`'s doing?`'

New translation thus.
'`Shall a trumpet be blown in the city, and the people not be afraid?
shall there be evil in a city, and the Lord hath not done it?`' verse 6.

In the first chapter of the Heb. 3.
in the new translation it is said, '`Who being the brightness of his glory,
and the express image of his person.`'

But in the old translation it reads thus: '`Being the brightness of his glory,
and the very image of his substance.`'

The 2 Cor. 2. chapter, the last verse, in the English it is,
'`We do not corrupt the word,`' but in the Latin it is,
'`We do not sell the word for money.`'
