[#sauls-errand, short="Saul`'s Errand to Damascus"]
== Saul`'s Errand to Damascus, / with his Packet of Letters from the High Priests Against the Disciples of the Lord. or,

[.heading-continuation-blurb]
A faithful transcript of a petition contrived by some persons in Lancashire,
who call themselves ministers of the gospel,
breathing out threatenings and slaughter against a peaceable and godly people there,
by them nick-named _Quakers._

[.heading-continuation-blurb]
Together with the defence of the persons thereby traduced,
against the slanderous and false suggestions
of that petition and other untruths charged upon them.

[.heading-continuation-blurb]
Published to no other end but to draw out the bowels of tender compassion
from all that love the poor despised servants of Jesus Christ,
who have been the scorn of carnal men in all ages.

[quote.section-epigraph]
____
"`Blessed are they which are persecuted for righteousness:
for theirs is the kingdom of heaven.
Blessed are ye when men shall revile you and persecute you,
and say all manner of evil against you, falsely, for my sake.
Rejoice, and be exceeding glad; for great is your reward in heaven:
for so persecuted they the prophets which were before you.`" -- Matt. 5:10-12.
____

[.section-date]
London, printed 1654.

=== To All that Love the Lord Jesus Christ.

Dear Hearts,--You love the Lord Jesus Christ, and not him alone, but Christ,
with all his train.
Great shall be your compensation: for your love you shall have loves,
(Song. 7:12) _Amores,_ a plurality and infinity of loves;
which none but God in Christ hath to bestow.
The best of his relations upon earth,
have but single love (and it is happy they have love) to the brethren;
but Christ hath loves for the meanest of you, the least of his.
May you and all his, (in whom there are yet but buds,
scarce visible appearances of graces,) prove fruitful vines, grow from buds to blossoms,
from blossoms to abundance of fruits;
that when the Lord shall get up early to visit his vineyard,
you may feast him with pleasant fruits, new and old;
you may bless him for his loves of former and latter days, and be ever to him an humble,
holy, and thankful, and to his brethren a comforting people.
Glory in your habit; you wear the signal favours of the King of kings, and Lord of hosts,
the great and mighty Jehovah, LOVE: by which I know to whom ye belong,
because ye love the brethren.

=== To the contrivers and subscribers of the petition.

Poor Hearts,--Is this a time to chide and be angry, and pick quarrels?
and (if you must needs do so) can you find no other objects of your indignation,
but the Lord`'s disciples?
But peaceable, holy, humble, self-denying men?
Is not the work of the ministry to preach the gospel?
Is not the sword of the magistrate appointed to the punishment of evil doers,
and to the praise of them that do well?
Are you incumbent in your duties?
Are you laying out your talents to the end they were given you,
or are you mistaken in the thing?
When did you proclaim war against drunkards, swearers, common blasphemers,
enemies to the Lord and his people?
Have you none of those amongst you?
or are your high-flown contending spirits gone beyond such slender wrestlings,
that you scorn to encounter with any below the degree of a saint?
The Lord open your eyes and let you see,
and give you hearts to consider your several duties.
But tell me, ye sons of Levi,
(as ye call yourselves,) ye that pretend a _Jus Divinum_ to persecution; what will ye say,
when the son of man shall come in his glory, and all the holy angels with him,
and shall sit upon the throne of his glory, and all nations shall be gathered before him?
Mind ye what will be the great work of that great day;
your petition will surely then be heard.
I beseech you read the paper of causes set down to be first heard at that tribunal,
in Matt. 25:31. to the end of the chapter:
and the Lord let it dwell upon your hearts forever.

=== To the Christian Reader.

These are to let thee know that the only wise God
at this time hath so by his providence ordered it,
in the north parts of Lancashire,
that many precious christians (and so for many years accounted,
before the nickname Quakers was heard of) have, for some time past,
forborne to concorporate in parochial assemblies,
wherein they profess themselves to have gained little of the knowledge of Jesus Christ.
And it is,
and hath been put upon their hearts to meet often (and on
the Lord`'s day constantly) at convenient places,
to seek the Lord their redeemer, and to worship him in spirit and in truth,
and to speak of such things,
(tending to mutual edification,) as the good spirit of the Lord shall teach them;
demeaning themselves without any offence given to any that truly fear the Lord.

But true it is that some men and interests of those parts do take great offence at them,
and their christian and peaceable exercises; some,
because they have witnessed against pride and luxuriant fulness,
have therefore come armed with sword and pistols (men that never
drew a sword for the interest of the commonwealth of England,
perhaps against it) into their assemblies in time of their christian performances,
and have taken him whom the Lord at that instant had moved to speak to the rest,
and others of their assembly,
(after they had haled and beaten them,) and carried
them bound hand and feet into the open fields,
in the cold of the night, and there left them to the hazard of their lives,
had not the Lord of life owned them, which he did in much mercy.
Others have had their houses broken in the night, and entered by men armed as aforesaid,
and disguised,
when they have been peaceably waiting upon God with their own and neighbouring families.
And yet these humble persecuted Christians would not (even
in these cases of gross and intolerable affronts,
acted equally against the peace of the nation as against them) complain,
but expressed how much (in measure) of their master`'s patience was given them,
in breathing out their master`'s gentle words, '`Father, forgive them;
they know not what they do.`' Who have at any time
borne such unheard of persecution with so mild spirits?
Only they in whom persecuted Christ dwells:
these poor creatures know how their master fared, and rejoice to suffer with him,
by whom alone they hope to be glorified; and are as well content to suffer,
as to reign with Christ.
But how unwillingly do we deny ourselves, and take up our cross and follow Christ:
and yet a necessity lies upon us, if we will be the Lord`'s disciples,
to take up our cross daily, and follow him.
How is it then, that the crown of pride is so long upon the head of persecutors?
How is it that such men should dare to divide the people of England,
to trouble the council of state (in the throng of business concerning the management
and improvement of all the mighty series of glorious providences made out to
this infant commonwealth) with such abominable misrepresentations of honest,
pious, peaceable men,
who desire nothing more than to glorify their God in their generation,
and are and have been more faithful to the interest of God`'s people in the nation,
than any of the contrivers of the petition,
as will easily be made appear if we may take for evidence what
they themselves have often said of the parliament and army,
and their friends and servants, publicly and privately;
and it is well known their judgments are the same;
but that the publication thereof will not safely
consist with the enjoyment of their large vicarages,
parsonages, and augmentations, whereby they are lifted up above their brethren,
and exalt themselves above all that are called God`'s people in these parts.

However, reader, we need not fear; we hope the Lord will never suffer that monster,
persecution, again to enter within the gates of England`'s Whitehall.
They that sit in council there,
know well enough who it was that so often assembled to consult
how they might take Jesus by subtlety and kill him:
they were men of no lower condition than chief priests, scribes,
and elders of the people:
and if ever these petitioners should but appear before
them to whom they have directed their petition,
my heart deceives me if they be not accounted such.

Reader,
I would not preface thee into a good opinion of these
suffering objects of such men`'s wrath;
but read their paper here put into thy hand, by them written,
upon the occasion of this petition, and several snares and temptations laid before them,
on purpose to entrap them;
and if by them thou canst find cause to pity these oppressed little ones,
have them in thy remembrance when thou goest to the throne of grace,
where my prayers shall meet thine, for them.

=== To the Right Honourable the Council of Slate.

The humble petition of several gentlemen, justices of peace, ministers of the gospel,
and people, within the county of Lancaster, whose names are subscribed, showeth,

That George Fox and James Nayler, are persons disaffected to religion,
and the wholesome laws of this nation; and that since their coming into this country,
have broached opinions tending to the destruction
of the relation of subjects to their magistrates,
wives to their husbands, children to their parents, servants to their masters,
congregations to their ministers, and of a people to their God:
and have drawn much people after them; many whereof, (men, women,
and little children,) at their meetings, are strangely wrought upon in their bodies,
and brought to fall, foam at the mouth, roar, and swell in their bellies.
And that some of them affirmed themselves to be equal with God, contrary to the late act,
as hath been attested at a late quarter sessions, holden at Lancaster,
in October last past; and since that time, acknowledged before many witnesses;
besides many other dangerous opinions, and damnable heresies,
as appears by a schedule hereunto annexed; with the names of the witnesses subscribed.

May it therefore please your honours, upon the consideration of the premises, to provide,
(as your wisdom shall think fit,) that some speedy course
may be taken for the speedy suppressing of these evils.
And your petitioners shall ever pray, as in duty bound.

[.numbered-group]
====

[.numbered]
1+++.+++ George professed and avowed that he was equal with God.

[.numbered]
2+++.+++ He professed himself to be the eternal judge of the world.

[.numbered]
3+++.+++ He said he was the judge of the world.

[.numbered]
4+++.+++ He said he was the Christ, the way, the truth, the life.

[.numbered]
5+++.+++ He said, whosoever took a place of scripture, and made a sermon of it, and from it,
was a conjuror, and his preaching conjuration.

[.numbered]
6+++.+++ He said that the scripture was carnal.

====

James Milner, a follower of the said Fox, professeth himself to be God and Christ;
and gives out prophecies.

[.numbered-group]
====

[.numbered]
1+++.+++ That the day of judgment shall be the 15th day of November.

[.numbered]
2+++.+++ That there shall never judge sit at Lancaster again.

[.numbered]
3+++.+++ That he must ere long shake the foundations of the great synagogue,
meaning the parliament.

====

Leonard Fell professeth that Christ had never any body but his church.

Richard Huberthorn wrote, that Christ`'s coming in the flesh was but a figure.

=== The answer of George Fox, to the matters falsely charged upon him, by the petition and schedule aforesaid.

[.discourse-part]
_Object._
'`That George Fox and James Nayler, are persons disaffected to religion.`'

[.discourse-part]
_Answer._
Whereas we are accused as persons disaffected to religion, it is false;
for pure religion we own in our souls, which is, '`to visit the fatherless,
and relieve the widows,
and to keep ourselves unspotted from the world,`' and dwelling in purity;
this we own in our souls.
But '`he that doth seem to be religious, and hath not power over his own tongue,
his religion is vain;`' and that religion we do deny:
and all those that do profess the scriptures in words, and live not the life of them,
but live in drunkenness, and uncleanness, envy, and maliciousness;
and all they that do profess religion, and make a trade of the scriptures,
both priests and people, we do deny.

[.discourse-part]
O+++.+++ '`Disaffected to the wholesome laws of the nation.`'

[.discourse-part]
A+++.+++ Justice (the wholesome law of God) we own; and this is a terror to the unjust,
unwholesome, and unclean, and he that bears that sword is a minister of God;
and who doth not obey the law of God within, then that takes hold upon him without,
but who doth obey the law of God within,
it brings him from under the occasions of all laws without: for it will not let man lie,
nor let him be drunk, nor proud, nor follow oaths, nor cursed speaking, nor whoredoms,
quarrelling, fighting, wrangling, nor railing.
And every one who walketh in the law of God, denies all that which is unwholesome,
and that which is according to the course of the world; and they are all of one heart,
and are all one in unity, if ten thousand; and have all one law written in their hearts;
which those that live in uncleanness cast behind their backs;
and yet they profess a law in words, but are not subject to the power of God.
And such are they who do accuse their brethren who walk in the law of God;
and yet they pretend justice: but their souls are not subject;
for that soul that is subject to the higher power which is of God,
denies all filthiness and corruption.

[.discourse-part]
O+++.+++ '`That since their coming into this country,
they have broached opinions tending to the destruction
of the relation of subjects to their magistrates,
wives to their husbands, children to their parents, servants to their masters,
congregations to their ministers, and of a people to their God.`'

[.discourse-part]
A+++.+++ We were moved of the Lord to come into this country, and the Lord did let us see,
that he had a people here before we came into it.
But as for broaching opinions, we deny; but those that profess truth,
and walk in it up to God, we own.

Opinions do tend to break the relation of subjects to their magistrates,
wives to their husbands, children to their parents, servants to their masters,
congregations to their ministers, and of a people to their God; but opinions we deny,
for they are without God; and there you are.
And justice and purity are but one, and that we set up and own:
purity and walking in the spirit, doth make a separation from all uncleanness,
and can have no fellowship with them who are unfruitful workers of darkness;
but there is a separation from them.
The one hath fellowship with God, and the other hath fellowship with darkness,
which is unfruitful: the one is separated to God, the other is separated from God.

[.discourse-part]
O+++.+++ '`Have drawn much people after them, many whereof, men, women, and little children,
at their meetings, are strangely wrought upon in their bodies, and brought to fall,
foam at the mouth, roar, and swell in their bellies.`'

[.discourse-part]
A+++.+++ The meetings of the people of God, were ever strange to the world;
for it was as though some strange thing had happened to the saints,
as ye read in the scripture; which shows ye are in the same generation,
wondering and stranging at the work of the Lord, despising and casting scandals,
slanders, and false reports upon them; and where the works of God are now,
they think them strange things now, as was then, who are alive in the flesh.
It would be a strange thing to see one now fall down, as Paul fell down and trembled,
and as Daniel fell down and trembled; and to see one as Habakkuk, his belly to tremble,
and his lips to quiver, and as David, to lie roaring all the day long,
who cried till '`his sight was grown dim,
and his flesh failed of fatness,`' and till he could
'`number his bones;`' and to see one as Isaiah,
to '`rent his garment and his mantle,`' and '`pluck his hair off his head,
and off his beard, and sit down astonished.`'
And would it not be strange to see such an assembly as came to Isaiah,
who had all trembling hearts? Isa. 66:5.
'`Hear the word of the Lord, all ye that tremble at his word;`'
'`work out your salvation with fear and trembling;`'
'`before their faces the people shall be much pained:
all faces shall gather blackness.`' The prophets and ministers of God have all one spirit,
(according to measure,) and did encourage those that did tremble;
wherein it shows that you have not the same spirit, but seek to persecute,
and fix scandals, and accuse them falsely.
The ministry of truth ever drew from all the ministry of the world,
and from under all the laws of the world, up to God, and from all the gods of the earth;
and then they witnessed that the Lord was their lawgiver, the Lord was their king,
the Lord was their judge.

[.discourse-part]
O+++.+++ '`George Fox professed and avowed that he was equal with God.`'

[.discourse-part]
A+++.+++ It was not so spoken, as that George Fox was equal with God:
but the Father and the son are one:
'`I and my Father are one.`' John 14:10-9. and where the same is revealed,
this is witnessed: but where the same is not made manifest and revealed,
Christ is persecuted; for the world knows him not.
'`Let the same mind be in you that was also in Christ Jesus,
who being in the form of God, thought it not robbery to be equal with God,
and yet made himself of no reputation.`' Phil. 6:7. And this I witness to be fulfilled;
for the same spirit where it is, is equal with God;
for '`he that sanctifieth and they that are sanctified are
all of one.`' Heb. 2:11. and it is God that sanctifieth.
He that hath the word of God hath God, for God is the word;
and '`our fellowship is with God.`' John 1:1. '`There is a natural man,
and there is a spiritual man: the first is of the earth, earthly,
the second is the Lord from heaven.`' 1 Cor. 15:47-48. '`The new man,
which is created after God in righteousness and true
holiness;`' and '`he that doth righteousness is righteous,
even as he is righteous.`' 1 John 3:7. And this I witness what the scripture saith,
'`Let no man deceive you.`'

[.discourse-part]
O+++.+++ '`He professeth himself to be the eternal judge of the world.`'

[.discourse-part]
A+++.+++ He that was a minister of God said, '`that the saints should judge the world, yea,
angels.`' 1 Cor. 6:2-3. Herein they show themselves to be no ministers of God,
who seek to persecute them who are judged of God, and justified by him;
where '`judgment is brought forth unto victory,`' Matt.
xii 20. and set in the earth; and that which is eternal,
hath judged all the carnal nature in himself;
and where it is judged there is no unity with it where it is alive;
and he that hath not true judgment, and hath not salt in himself to savour withal,
is good for nothing,
and he cannot endure that Christ should speak where he is made manifest.
'`I am the way,`' saith Christ; Christ is but one in all his saints,
and he speaks in them. 1 Cor. 11:3.
But he doth not say that George Fox is Christ.
'`I am the way, the truth, and the life.`' Christ is the light, and ye are the light;
and Christ liveth in you, and Christ is the head of the man;
and it is the spirit of the Father that speaketh in you, and spoke in Christ,
and he is but one in all his saints.
Without are many Christs;
'`lo here,`' and '`lo there;`' but '`know you not that Christ is in you,
except ye be reprobates?
and if Christ be in you,
the body is dead because of sin;`' and there Christ Jesus speaks,
'`the same Christ today, yesterday, and forever.`' And thy judgment which is not eternal,
is carnal; and with evil thoughts thou judgest; thou puttest darkness for light,
and light for darkness; and here thou showest thy judgment to be carnal,
and no minister of God, but a minister of the letter, and not of the spirit;
for the ministers of the spirit have true judgment, and did imprison none, nor persecute,
as you do; but it is, that fools may utter forth their folly.

[.discourse-part]
O+++.+++ '`He said he was the way, the truth, the life.`'

[.discourse-part]
A+++.+++ The old man cannot endure to hear the new man speak, which is Christ;
and Christ is the way: and if Christ be in you, must not he say, '`I am the way,
the truth, and the life?`' John 10:4. Now if antichrist speak,
he is owned of the world; but he cannot witness it; while the old man reigns,
the voice of God is not known, nor Christ himself to speak in man,
but Christ`'s sheep know his voice.

[.discourse-part]
O+++.+++ He said, '`whosoever took a place of scripture, and made a sermon of it, or from it,
was a conjuror, and his preaching was conjuration.`'

[.discourse-part]
A+++.+++ He that puts the letter for the light, when the letter saith Christ is the light,
he is blind; and they that say the letter and the spirit are inseparable,
when the spirit saith the letter is death, and killeth,
and all that do study to raise a living thing out of a dead,
to raise the spirit out of the letter, are conjurors, and draw points and reasons,
and so speak a divination of their own brain; they are conjurors and diviners,
and their teaching is from conjuration, which is not spoken from the mouth of the Lord,
and the Lord is against all such, and who are of God are against all such;
for that doctrine doth not profit the people at all,
for it stands not in the counsel of God, but is a doctrine of the devil,
and draws people from God, but he that speaks from the mouth of the Lord,
turns people from their wickedness, but that ministry which God hath not sent,
and that assembly must be disaffected:
for the Lord is coming to teach his people himself by his spirit.

[.discourse-part]
O+++.+++ '`George Fox said the scripture was carnal.`'

[.discourse-part]
A+++.+++ The letter of the scripture is carnal, and the letter is death, and killeth,
but the spirit giveth life, which was in them that gave forth the scriptures,
and that I witness, which is eternal and not carnal: for the Jews who had the letter,
persecuted Jesus Christ the substance;
and so do you now who have the letter and not the substance.
There were ministers of the letter then, and ministers of the spirit, so there are now.
The same Christ being made manifest, is unknown to the world:
for the whole world lieth in wickedness, and Christ Jesus is a mystery to the world,
and is hid, though you may profess him, because the letter speaketh of him;
but ye persecute him where he is made manifest,
and where he is made manifest the works of the devil are destroyed,
and there he speaks and is king, and is the way, and is the truth, and is the life;
and he that hath the son hath life, and he that hath not the son hath not life:
and he that hath the same spirit that raised up Jesus Christ, is equal with God.
And the scripture saith, that God will dwell in man, and walk in man.
As Jesus Christ which is the mystery, hath passed before,
so the same spirit takes upon it the same seed,
and is the same where it is made manifest: according to the flesh,
I am the son of Abraham, according to the spirit, the son of God, saith Christ.
All the plotting of the priests is, and ever was, against Christ,
where he is made manifest: '`And the beast shall make war with the saints,
and with the lamb;`' but the lamb shall get the victory: praises,
praises be to our God forever, and forevermore.

[.discourse-part]
O+++.+++ '`Richard Huberthorn wrote, that Christ`'s coming in the flesh was but a figure.`'

[.discourse-part]
A+++.+++ Christ in his people is the substance of all figures, types, and shadows,
fulfilling them in them, and setting them free from them:
but as he is held forth in the scripture letter without them,
and in the flesh without them, he is their example or figure, which are both one,
that the same things might be fulfilled in them, that were in Christ Jesus:
'`For even hereunto were ye called, because Christ hath suffered for us,
leaving us an example that we should follow his steps:
forasmuch as Christ hath suffered for us,
arm yourselves likewise with the same mind.`' Christ
was our example in suffering and in holiness,
and '`as he which hath called you is holy, so be ye holy in all manner of conversation,
because it is written, be ye holy as I am holy.`' He is our example in humility:
'`I have given you an example,
(saith Christ,) that ye should do even as I have done unto you:
and as he is so are we in this world.`' He is our forerunner, captain of our salvation,
and in all things our example.
'`As they have done unto me,
so shall they do unto you.`' But all they who have not Christ dwelling in them,
go about to persecute him in all them in whom he is made manifest;
they neither follow him as an example themselves,
nor suffer others to follow him as an example and walk in the same steps:
but deny him both as the substance and example of his people.
But they who are taught of him do confess him both as he is the substance of all things,
and their example in all things: for '`without me ye can do nothing,`' saith Christ:
and it is so, I witness it.

And as for James Milner, though his mind did run out from his condition,
and from minding that light of God which is in him,
whereby the world takes occasion to speak against the truth,
and many Friends stumble at it: yet there is a pure seed in him.

[.discourse-part]
O+++.+++ '`Leonard Fell said that Christ had no body but his church.`'

[.discourse-part]
A+++.+++ '`There is one body, and one spirit,
even as ye are called into one hope of your calling;`'
and '`Christ Jesus is the head of the body,
the church;`' and ye are made free from sin by the body of Christ.
And Christ came to redeem his church.
'`God was in Christ reconciling the world to himself,`' for his body`'s sake,
which is his church.
'`For we are members of his body, of his flesh, and of his bones:
this is a great mystery; but I speak concerning Christ and his church.
And hath put all things under his feet,
and gave him to be the head over all things to the church, which is his body.
The fulness of him that filleth all in all.
In whom also we are builded up together, for a habitation of God through the spirit.`'

=== More objections against George Fox, charged upon him, by the contrivers of the aforesaid petition; and answered by him, as followeth:

[.discourse-part]
_Object. 1._
'`That he did affirm that he had the divinity essentially in him.`'

[.discourse-part]
_Answer._
For the word essential, it is an expression of their own:
but that the saints are the temples of God, and God doth dwell in them,
that the scriptures do witness, 2 Cor. 6:1.
Eph. 4:6. 2 Pet. 1:4. And if God dwell in them,
then the divinity dwells in them; and the scripture saith,
ye shall be partakers of the divine nature; and this I witness: but where this is not,
they cannot witness it.

[.discourse-part]
O+++.+++ 2. '`That both baptism and the Lord`'s supper are unlawful.`'

[.discourse-part]
A+++.+++ As for that word unlawful, it was not spoken by me: but the baptism of infants I deny;
and there is no scripture that speaks of a sacrament,
but that baptism that is into Christ, with one spirit into one body, Gal. 3:27.
that I confess according to scripture.
And the Lord`'s supper I confess,
and that the bread the saints break is the body of Christ;
and that cup which they drink is the blood of Christ, this I witness.

[.discourse-part]
O+++.+++ 3. '`He did dissuade men from reading the scriptures, telling them that it is carnal.`'

[.discourse-part]
A+++.+++ For dissuading men from reading the scriptures, that is false,
for they were given to be read as they are, but not to make a trade upon.
The letter is carnal, and killeth; 1 Cor. 2:10. 16.
but that which gave it forth is spiritual, eternal, and giveth life;
and this I witness.

[.discourse-part]
O+++.+++ 4. '`That he was equal with God.`'

[.discourse-part]
A+++.+++ That was not so spoken; but that '`He that sanctifieth, and they that are sanctified,
are of one,`' Heb. 2:11. and the saints are all one in the Father and the son,
of his flesh and of his bone; this the scripture doth witness.
And '`ye are the sons of God,`' and the Father and the son are one;
and '`they that are joined to the Lord, are one spirit,
and they that are joined to a harlot are one flesh.`'

[.discourse-part]
O+++.+++ '`That God taught deceit.`'

[.discourse-part]
A+++.+++ That is false, and was never spoken by me; God is pure.

[.discourse-part]
O+++.+++ '`That the scriptures are antichrist.`'

[.discourse-part]
A+++.+++ That is false, but that they who profess the scriptures,
and live not in the life and power of them, as they did that gave them forth,
that I witness to be antichrist.

[.discourse-part]
O+++.+++ '`That he was the judge of the world.`'

[.discourse-part]
A+++.+++ '`That the saints shall judge the world,`' the scripture witnesseth it, 1 Cor. 6:2-3.
wherefore I am one, and I witness the scripture fulfilled.

[.discourse-part]
O+++.+++ '`That he was as upright as Christ.`'

[.discourse-part]
A+++.+++ Those words were not so spoken by me;
but that '`as he is so are we in this present world.`' 1 John 4:17.
That the saints are made '`the righteousness of God;`' that the
saints are one in the Father and the son;
that we shall be like him, 1 John 3:2.
and that all teaching which is given forth by Christ,
is to bring the saints to perfection,
even to the measure of the stature of the fulness of Christ:
this the scripture doth witness, and this I witness.
Where Christ dwells, must not he speak in his temple?

=== Queries propounded to George Fox, by some of the contrivers of the petition, and by him answered.

[.discourse-part]
_Query--__'`Whether there be one individual God distinguished into the Father, son,
and holy ghost, or not?`'

[.discourse-part]
A+++.+++ Herein thou wouldst know, whether God be individual, yea or no,
which is but a busy mind;
for hadst thou the witness in thyself thou wouldst know what he is;
but the heathen know not God, and all that know him not, are heathen,
living in the wicked imaginations of their own hearts; and that is thy condition.
For '`God is a spirit,`' and none know him but the son,
and he to whom the son is revealed; the son and word are one.
'`He that hath ears to hear, let him hear what the spirit saith,`' for thou, natural man,
knowest not the things of God.

[.discourse-part]
Q+++.+++ '`Whether a believer be justified by Christ`'s righteousness imputed, yea, or no?`'

[.discourse-part]
A+++.+++ He that believeth is born of God;`' and he that
is born of God is justified by Christ alone,
without imputation.

[.discourse-part]
Q+++.+++ '`Whether he that believeth that Christ hath taken away his sin,
is clean without sin in this life, as Christ himself, or not?`'

[.discourse-part]
A+++.+++ '`He that believeth is born of God,`' and '`he that is born of God sins not,
neither can he sin, because his seed remaineth in him:`' '`as he is,
so are we in this present evil world.`'

[.discourse-part]
Q+++.+++ '`Whether a believer be without all sin in this life, or not?`'

[.discourse-part]
A+++.+++ Christ being made manifest, is made manifest to take away sin,
and '`in him is no sin at all; he that abideth in him, sins not;
he that sins is of the devil, and hath not seen him, neither known him;
herein are the children of God made manifest,
and the children of the devil.`' All you that read these queries,
read these things in yourselves, whether ye be the children of God,
or the children of the devil; and whether ye understand what ye write, yea, or no.

[.discourse-part]
Q+++.+++ '`Whether his works, as well as his person, be perfectly holy and good or no?`'

[.discourse-part]
A+++.+++ '`A good tree cannot bring forth evil fruit;`' and '`if the root be holy,
the branches will be holy also;`' and '`every one that doth righteousness is righteous,
even as he is righteous.`' But as for that person,
it is a busy mind in thee that askest thou knowest not what:
for '`God is no respecter of persons:`' he that respecteth persons commits sin,
and he that commits sin transgresseth the law.

[.discourse-part]
Q+++.+++ '`Whether saints in this life, without any addition hereafter, are perfectly just,
perfectly holy, completely glorious in this life,
and are not capable of any addition after death, in the least degree,
but only of manifestation?`'

[.discourse-part]
A+++.+++ If that thou knowest what a saint is, thou wouldst know a saint`'s life,
for they passed through death to life; but thou art yet alive to sin,
and dead to righteousness; see if it be not so;
but he that is dead to sin is alive to righteousness; and lives in God; and God in him.
The Lord is our righteousness, and he saith, '`Be ye holy,
as I am holy:`' for '`without holiness no man shall see the Lord.`' '`Be not deceived,
God will not be mocked.`' Thou hypocrite, dissemble not with him:
he that is perfectly holy is perfectly just: where this is revealed,
there needs no addition; for the man of God is perfect.

[.discourse-part]
Q+++.+++ '`Whether the two sacraments, baptism and the breaking of bread,
ought necessarily to continue in the church, or not?`'

[.discourse-part]
A+++.+++ Thou askest thou knowest not what, concerning two sacraments,
which there is no scripture for.
Thou askest a question, which is an addition to the scripture; and thou that dost add,
the plagues of God are added to thee.
Who come into the true church, are baptized with one spirit into one body,
but as for sprinkling infants, there is no scripture for it; I deny it;
in the true church of God there is no talk of such carnal things.
Thou sot, the bread which the saints break is of the body of Christ;
he is the bread of life.
The church is not the steeple- house, but the church is in God,
and those that eat the bread of life live forever: the church is in God,
and the bread of life is there, and it shall continue forever.

[.discourse-part]
Q+++.+++ '`Whether Christ in the flesh be a figure or not; and if a figure, how and in what?`'

[.discourse-part]
A+++.+++ Christ is the substance of all figures; and his flesh is a figure;
for every one passeth through the same way as he did,
who comes to know Christ in the flesh; there must be a suffering with him,
before there be a rejoicing with him.
Christ is an example for all to walk after; and if thou knewest what an example is,
thou wouldst know what a figure, is to come up to the same fulness.

[.discourse-part]
Q+++.+++ '`Whether there be any heaven or hell, for the elect or reprobate after death,
but in man in this life, or not?`'

[.discourse-part]
A+++.+++ There is no knowledge of heaven or hell, but through death:
'`The wicked shall be turned into hell,
and all them that forget God,`' there to be tormented.
There is a hell, thou shalt find it.
Heaven is God`'s throne; and heavenly notions within shall be shaken; for God is pure,
and nothing that is unclean shall stand before him;
and he hath said he will dwell in man.

[.discourse-part]
Q+++.+++ '`Whether the ministration of the ministry by man, is to continue till the end,
or not.`'

[.discourse-part]
A+++.+++ The ministration of the world is the ministry of man, and doth not lead to an end,
but keeps in time, and that must have an end, for it is not of God.
The ministry of God is to draw people up to himself; but that is '`not of man,
nor by man,
nor according to man;`' for Paul was '`made a minister according
to the will of God,`' who had not received it of man,
neither was it taught him of man; and was a minister of the spirit.
But the ministers of the world receive their learning at Oxford and Cambridge,
and are taught of men, and speak a divination of their own brain, which is conjuring;
and bewitch the people with those things which are carnal: as, to sprinkle infants,
and tell them of a sacrament, which there is no scripture for;
and saying they are the ministers of Christ, and act those things which he forbids; as,
to have '`the chiefest place in the assemblies,
the uppermost room at feasts,`' the '`greetings in markets,`' and '`to be called
of men masters,`' and '`with pretence make long prayers,`' which Christ forbids,
and profess and say, they are the ministers of Christ:
wherein they show themselves to be antichrist.
And see if thou do not uphold these antichrists, and say,
they are the ministers of Christ.

[.discourse-part]
Q+++.+++ '`Whether the written word, I mean the scriptures, be the power of God unto salvation,
to every one that believes, or not?`'

[.discourse-part]
A+++.+++ The written word is not the power of God, nor are the scriptures the salvation;
but he that doth believe, hath the life of them.
Who is born of God shall never die, as it is written; he that believeth is born of God;
and he that is born of God hath the witness in himself,
that God is the cause of man`'s salvation, and not the scripture nor the letter.

=== James Nayler`'s answer and declaration, touching some things charged upon him by the men aforesaid.

Having heard of divers untruths cast upon me,
by some of the priests in their high places,
though I stand only to the Lord in respect of myself;
yet lest any that love the truth should be led on by these false reports to '`speak
evil of these things they know not;`' I shall lay open the truth,
as it is revealed in me, touching those things whereof I have been falsely accused.

[.numbered-group]
====

[.numbered]
_First,_ concerning Jesus Christ, that he is the eternal word of God,
'`by whom all things were made,`' and are upheld; which was before all time,
but manifested to the world in time, for the recovery of lost man.
Which '`word became flesh, and dwelt amongst`' the saints; who is '`the same yesterday,
today, and forever;`' who did and doth dwell in the saints; who suffered, and rose again,
and ascended into heaven, and is set at the right hand of God,
to whom '`all power is given in heaven and in earth;`' who fills all places,
is the light of the world, but known to none but to those that receive and follow him,
and those he leads up to God, out of all the ways, works, and worships of the world,
by his pure light in them,
whereby he reveals '`the man of sin;`' and by his power casts him out,
and so prepares the bodies of the saints a fit temple for the pure God to dwell in;
with whom dwells no unclean thing.
And thus he reconciles God and man, and the image of God,
which is in purity and holiness, is renewed: and the image of Satan,
which is all sin and uncleanness, is defaced.
And none can witness redemption, further than Christ is thus revealed in them,
to set them free from sin: which Christ I witness to be revealed in me in measure. Gal. 1:16.
2 Cor. 13:5. Col. 1:27.

[.numbered]
2+++.+++ Concerning the scriptures.
That they are a true declaration of that word which was in them that spoke them forth,
and are of '`no private interpretation,`' but were
given forth to be read and fulfilled in the saints,
as they were given forth by the holy ghost, without adding or diminishing;
and were not given forth for men to make a trade of to get money by.
But as they are, they are '`profitable for doctrine, for reproof, for correction,
for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto every good work.`' But they who trade in the letter,
and are ignorant of the mystery, deny all perfection.
And none can rightly understand the scriptures,
but they who read them with the same spirit that gave them forth;
for '`the natural man understands not the things of God:
for they are spiritually discerned.`'

[.numbered]
3+++.+++ Concerning baptism.
The true baptism is that of the spirit, '`with the holy ghost,
and with fire.`' '`Baptized by one spirit into one
body not the washing away the filth of the flesh,
but the answer of a good conscience towards God by the resurrection
of Jesus Christ;`' without which no other baptism can save us,
they being but figures or shadows; but this baptism of Christ is the substance,
whereby we are baptized into his death;
and those '`that are baptized into Christ have put on Christ.`'

[.numbered]
4+++.+++ Concerning the Lord`'s supper.
The true supper of the Lord is the spiritual eating and
drinking of the flesh and blood of Christ spiritually;
which the spiritual man only eateth, and is thereby nourished up unto eternal life:
without which eating there can be no life in the creature, profess what you will.
And all who eat of this bread, and drink of this cup,
have real communion in Christ the head, and also one with another, as members;
and are of one heart, and one mind, a complete body in Christ.
Now the world, who take only the outward signs,
and are not brought into '`discerning of the Lord`'s body,
eat and drink damnation to themselves,`' and become '`guilty
of the body and blood of Christ;`' and call this a communion,
but live in envy, strife, and debate, fighting, and going to law one with another,
for earthly things.

[.numbered]
5+++.+++ Concerning the resurrection.
That all shall arise to give an account,
and receive at the last day '`according to their works,
whether good or evil.`' These bodies that are dust, shall turn to dust,
'`but God shall give a body as pleaseth him;
that which is sown in corruption shall be raised in incorruption;
it is sown a natural body, it is raised a spiritual body;
and as we have borne the image of the earthly,
so we shall bear the image of the heavenly:`' but
'`flesh and blood cannot inherit the kingdom of heaven;
neither doth corruption inherit incorruption;
for we must be changed.`' But they who cannot witness
the first resurrection within themselves,
know nothing of the second, but by hearsay; and therefore, say some of your teachers,
that Christ is in heaven with a carnal body.
Now that Christ, who is the first fruits, should be in heaven with a carnal body,
and the saints with a spiritual body, is not proportionable.

[.numbered]
6+++.+++ Concerning magistracy.
It is an ordinance of God, ordained '`for the punishment of evil doers,
and an encouragement for them that do well;`' where
justice and righteousness are the head,
and ruleth without partiality, that land is kept in peace;
and those that judge for the Lord, I honour as my own life, not with a flattering honour,
putting off the hat and bowing of the knee, which is the honour of the world,
'`having men`'s persons in admiration because of advantage,`' for self-ends;
but from my heart, for conscience`' sake, as to the power which is of God,
not to men`'s persons.
For the scripture saith, '`he that respects persons commits sin,
and is convinced of the law as a transgressor;`'
and the apostle James commands the saints,
'`not to have the faith of our Lord Jesus Christ, the Lord of glory,
with respect of persons;`' for, saith he, '`such are partial in themselves,
and become judges of evil thoughts.`' And saith Paul,
'`Let every soul be subject to the higher power; for,`' saith he,
'`there is no power but of God:
the powers that be are ordained of God;`' and that '`whosoever resisteth the power,
resisteth the ordinance of God;`' and saith, '`We must needs be subject,
for conscience`' sake.`' And therefore,
though the prophets were often sent by the Lord to pronounce judgment against unjust men,
who had the power committed to them, and did not judge for God, but for self-ends;
yet they never attempted any violence against them,
but used all means to persuade them to '`love mercy, do justice,
and walk humbly with God,`' that they might be established,
and the wrath of God turned from them;
for those that be of God cannot rejoice in the sufferings of any,
but would have all to turn and find mercy.

[.numbered]
7+++.+++ Concerning the ministry.
The true ministers of Jesus Christ have always been, and are still,
such as come not by the will of man, but by the will of God;
neither are they fitted for the work by any thing of man, but by God alone;
for the true ministry is the gift of Jesus Christ,
and needs no addition of human help and learning: but as the work is spiritual,
and of the Lord, so they are spiritually fitted only by the Lord,
and therefore he chose herdsmen, fishermen, and ploughmen, and such like.
And as he gave them an immediate call, without the leave of man,
so he fitted them immediately without the help of man;
and as they received the gift freely, so they were to give freely.
And whenever they found any of the false ministry, that taught for hire,
they cried out against them, and pronounced woes against them,
and showed them that they lay in iniquity,
because they '`thought that the gift of God could be bought and sold for money.`'
And Christ calls them '`hirelings,`' and saith they '`care not for the sheep.`'
And Micah cries out against the priests that taught for hire;
and, (saith he,) '`they build up Zion with blood,
and Jerusalem with iniquity.`' And Jeremiah cried out against the priests in his days,
that '`bare rule by their means,`' and calls it '`a horrible thing;`' and saith that,
'`from least the of them to the greatest,
they are all given to covetousness.`' And Isaiah cries out against those in his days,
and calls them '`greedy dogs, that can never have enough;`' and, saith he,
'`they all look for their gain from their quarter.`'
And Peter saith of such as should come,
that they '`through covetousness should make merchandise`' of the people; and saith,
'`they have hearts exercised with covetous practices, who have forsaken the right way,
and have followed the way of Balaam,
who loved the wages of unrighteousness.`' And Jude cries, '`Woe unto them,
for they go on in the way of Cain,`' in his murder,
'`and run greedily after the error of Balaam`' for reward.
But those that were sent out by Christ,
counted it their gain to '`make the gospel without
charge;`' neither ever had they any set means,
but went about, having no certain dwelling place; never were masters,
but '`servants to all for Christ`'s sake:`' nor ever went to law for tithes,
or any other earthly thing.

====

Now all people, try your priests by the scriptures,
whether they be of God or of the world,
and never think to hear the word of the Lord from their mouths,
who walk contrary to the scriptures.
For such were never sent of God:
for had they been sent of God they would abide in his doctrine; and saith John,
such have not God, but '`he that abideth in the doctrine of Christ,
hath both the Father and the son.`' '`And if there come any to you,
and bring not this doctrine,`' '`you are forbidden to receive them into your house,
or bid them God speed:`' for if you do, you are partakers of their evil deeds.
And unto the wicked, God saith, '`What hast thou to do to declare my statutes,
or that thou shouldst take my covenant into thy mouth?
Seeing thou hatest instruction,
and castest my words behind thy back,`' and art a partaker with the thief, the adulterer,
evil-speaking, slandering, and deceit; and such as these,
'`think God to be like themselves.`'

=== Divers particulars of the persecutions of James Nayler, by the priests of Westmoreland.

James being at a meeting at Edward Briggs`' on the First-day, where many people met,
he was desired by divers Friends to meet the day following at widow Cocks`' house,
about a mile from Kendal, whereof the priests having notice,
raised the town of Kendal against him; but being long in gathering together,
the meeting was done.
But spies being out upon the steeple top, and other places,
notice was given what way James passed from thence; and coming down towards Kendal,
two priests, accompanied with a justice of peace, and some other magistrates of the town,
with an exceeding great multitude of people following them, met him, one of them saying,
'`Nayler, I have a message from the Lord Jesus Christ to thee,
but that there is not a convenient place.`'

To which James answered,
'`The Lord Jesus Christ is no respecter of places.`' The message that he had to declare,
was this:
'`I conjure thee that thou tell me by what power thou inflictest
such punishment upon the bodies of creatures.`' James answered,
'`Dost thou remember who it was that did adjure Christ to tell if he were the son of God,
and asked by what authority he did those things?`'
for James saw him to be one of that generation,
But the priest still conjuring him to tell by what power he did it; James answered,
'`Dost thou acknowledge it to be done by a power?`' '`Yea,`' said he,
'`I have the spirit of God, and thereby I know it is done by a power.`' James said,
'`If thou have the spirit of God, as thou sayst thou hast,
then thou canst tell by what power it is done.`' The priest said, '`When God comes,
he comes to torment the souls and not the bodies.`' James said,
'`He comes to redeem the souls.`'

But after much jangling the priest began to accuse
him before the justice and magistrates of many things;
as, '`that he taught people to burn their bibles, children to disobey their parents,
wives their husbands, people to disobey the magistrates,
and such like accusations.`' To which James answered, '`Thou art a false accuser:
prove one of these things if thou canst, here,
before the magistrates.`' But not being able to prove any one,
he began to accuse James for holding out a light that doth convince of sin,
'`which,`' said the priest, '`all have not.`' To which James said,
'`Put out one in all this great multitude that dare say he hath it not?`' Said the priest,
'`These are all christians, but if a Turk or Indian were here,
he would deny it.`' James said, '`Thou goest far for a proof: but if a Turk were here,
he would witness against thee.`'

The people beginning to fight, the priest turned away, saying,
'`Here will be a disturbance.`' Said James, '`These are thy christians,
and these are the fruits of thy ministry.`' But the justice, with some others,
did endeavour to keep the rude people off him,
so that they could not come to their purpose there: but he being to pass over the bridge,
and through the town, they that were of the priests`' party ran before,
swearing they would throw him off the bridge into the water;
but coming thither and seeing their purpose, he was encouraged in his God,
who gave him assurance of protection, and did wonderfully keep him,
and those that were him: for when he came unto the bridge,
the word of the Lord came unto him, and he was made to cry out against their rage;
and the power of the Lord was with him, so that he received no harm,
though he was made to speak all along, and in the market-place,
and till he came out of the town.
But the raging people continued shouting, crying,
and throwing of stones at him a quarter of a mile out of the town:
but such was the power of the Lord, that neither he nor any with him, received any harm.
The work was wonderful, and we were brought much to admire it, and praise the Lord,
who is blessed forever and ever.

Another time, James being desired of many christian friends to be at a meeting at Orton,
there to wait upon the Lord for what he would make known to his people, did accordingly;
and many Friends and brethren accompanied him;
but the priests having intelligence some days before,
five of them were gathered together, and many people from all quarters.
A Friend in the town desired James to come to his house; and being come into his house,
a message was sent from the priests, desiring him to come into the field,
under pretence of a more convenient place for the great multitude.
To which James answered, '`It is my desire that all may be edified:
and coming into the field the priests came with a great multitude,
and asked him '`by what authority he came thither,
and had gathered together so many people to break the peace;`' and tempting him, said,
'`Wilt thou be bound that none here shall break the peace?`' To which James answered,
'`We come not hither to create offences, but if any break the law,
let him suffer by the law: for he perceived they intended violence,
as it appeared afterwards.

But seeing they could not prevail in that,
another of them desired him to go into the church, as he called it, tempting him, saying,
'`The people may all sit and hear better.`' But James perceiving their deceit, said,
'`All places were alike to him;
he would abide in the field.`' Whereon they pulled out an ordinance of parliament,
forbidding any to speak but such as were authorized to speak either in church or chapel,
or any public place; and bade him speak at his peril,
as he would answer the contempt of it.
To which he answered, saying,
'`This is not a public place.`' '`No,`' said one of the priests,
is not this a public place,
the town field!`' and charged the constable of the town to do his office;
and examined his authority.
James answered,
'`Those that are sent to declare the things of God have not their
authority from men.`' But they bade him prove that.
He said, '`Paul received not his commission from man,
nor by man.`' To which one of them answered, That was his gospel,
but they would prove that Paul had a call from man to preach and for that
end he named that place in Acts 13:2. where the holy ghost said,
'`Separate me Barnabas and Saul:`' and the apostles laid their hands upon them,
'`which,`' said one of them,
'`was the laying on of hands of the presbytery.`' But when he had found that place,
James asked him if that was Paul`'s call to the ministry?
(three times,) but he answered nothing.
Then said James, '`If, that was his call,
he had preached long without a call before that;`' and instanced to prove it, Gal. i.

Whereupon that business ended; but another priest stood up, and said,
'`Thou oughtest to give an account of thy faith to every
one that asketh;`' whereupon he asked divers questions;
whereunto James answered, insomuch that some that stood by, cried out, '`Answer not all,
but ask him some.`' A while after, James asked him,
'`how he would prove himself a minister of the gospel,
and live upon tithes?`' To which he would not answer.
Then, said James, '`Neither will I answer thee, if thou ask me twenty more.`'

The next question he asked, was, '`Whether Christ was ascended or not?`' but James said,
'`I will not answer thee.`' Whereupon he cried out to the people, and said,
'`He denies the humanity of Christ,`' and made a great outcry among the people of it.
But the people cried out, saying, '`Let us hear him;
you have often told us many things against him; let him speak,
and then if he speak not truth, you may then reprove him.`' James,
hearing the desire of the people, began to speak; and the people gave audience,
and were very silent.
But beginning to hold out Christ alone to be the
teacher of his people in spirit and truth,
one of the priests cried out,
'`I cannot endure to hear this seducer any longer.`' Upon which James said,
'`Prove me a seducer before all this people,
or else thou art a false accuser.`' But he had not
one word to say against any thing that he had spoken:
but said, '`If thou wilt not answer me that question I asked thee,
I will call thee a seducer as long as I live.`'

Whereupon, seeing there could be no peace there, nor liberty to speak,
they desired James to go into the house; and they kept close about him,
to keep him from violence of some that came along with the priests:
but they raged so that he and other Friends received stripes,
and with much ado got to the house.
But the raging Sodomites waited about the door to do mischief,
and kept shouting about the house all the while he was speaking;
but the house being filled with people, they could not come to their purpose:
and the Lord so ordered it in the evening, we came away without any more harm.
But not long after, there came some of the priests`' party about the house,
and asked if Nayler was gone: and when they heard he was gone, they said,
'`He may thank God for that.`' Thus, by the wisdom of God,
he escaped their violence at that time.

But the priests, missing of their purpose there, the next First-day after,
they prepared their sermons suitable to what they intended,
possessing the people that he was a blasphemer, and denied the resurrection,
and the humanity of Christ, and all authority:
and that the parliament had opened a gap for blasphemy, and,
as it was said by some of their hearers,
they did God good service that would knock him down.
Thus having stirred up the ruder sort,
the next day they prevailed with one called a justice of the peace:
the priest`'s son got him to come twelve miles from his own house: he was one,
as some say, that had been in actual arms against the parliament,
for bringing in the Scots.
And having armed a great multitude against the next morning,
they came very early to the house where he was,
where many christian Friends should have met that day, and asked for Nayler,
threatening to knock out his brains against the stones in the wall,
and that they would pull down the house, if he would not come out:
though the door was never shut against them.
But some of them came into the house, and commanded him to come forth,
under pretence to dispute with the priest.
But James, seeing what they intended, answered,
'`You did not use me so civilly the last time I was amongst you;
but if any have a mind they may come in,
the doors are open.`' Which answer they told the priests,
whereupon they rushed violently in, and took him by the throat,
haled him out of the door into a field, where was a man whom they called a justice,
and with a pitchfork struck off his hat,
and commanded him to answer to such questions as the priests would ask him.
Whereupon the priest began to ask many questions, as concerning the resurrection,
the humanity of Christ, the scriptures; and divers other questions, as the sacrament,
and such like, to which he answered, and proved by scripture.
But at last being asked, if Christ was in him, he said,
'`he witnessed him in him in measure.`' The priest asked,
'`if Christ was in him as man.`' James said,
'`Christ is not divided.`' But he urged him to tell
whether Christ as man was in him or not.
He answered, '`Christ is not divided; for if he be, he is no more Christ;
but I witness that Christ in me who is God and man, in measure.`' But the priest said,
'`Christ is in heaven with a carnal body.`' To which said James,
'`Christ filleth heaven and earth, and is not carnal but spiritual:
for if Christ be in heaven with a carnal body, and the saints with a spiritual body,
that is not proportionable;
neither was that a carnal body which came in among the disciples, the doors being shut;
for Christ is a mystery, and thou knowest him not.`'

Then after much jangling and tempting,
the priest not having got the advantage he waited for,
he cried out unto the people not to receive him into their houses,
and alleged that in the second epistle of John 5:10. Now,
how suitable that place was for his purpose, all people may see, who have eyes;
for there they are forbidden to receive any into their houses
but such who '`abide in the doctrine of Christ,
and confess themselves that they had both the Father and the son,
and preach that doctrine:`' but the priests say that is blasphemy.

Then the priest turned away from him:
upon which the armed multitude began to be violent
against divers Friends that were there.
James hearing Friends cry out, said to the justice,
'`You will surely set us peaceably into the house again;`' but seeing him to go away,
and leave them in the hands of the rude multitude, he gave himself up, saying,
'`The will of the Lord be done.`'

Upon which the justice turned again, saying,
'`We will see him in the house again:`' and going toward the house,
many Friends kept close about James,
exposing their own bodies to the danger of their weapons, to save him harmless;
and so with much ado we got into the house, not receiving much harm.
Which being done,
and as James was praising the Lord for his wondrous
deliverance from their malicious intents,
some heard them say, '`If we let him go thus,
all people will run after him.`' Whereupon they agreed
that he should be brought before the justice again;
and came with violence, and haled him out again.
Then the justice and the priest getting on horseback,
they caused him to run after them to an ale-house on the other side the water,
where they went in, not suffering one Friend to go in with James:
and when he came before the justice, he told him if he would not put off his hat,
he would send him to prison, and also because he thoued him; for the justice said,
'`My commission runs ye.`' To which James answered, '`I do it not in contempt;
for I own authority, and honour it according to the scriptures;
but I find none such honour commanded in scripture,
but forbidden.`' Then they concluded to commit him for that,
and also as a wandering person, and said none there knew him whence he came;
for those who knew him were kept out.
Then, said he to Arthur Scaife, '`Thou knewest me;
I was in the army with thee eight or nine years.`' '`It is no matter,`' said the justice,
'`thou art no soldier now.`'

Then they wrote a mittimus to send him to prison,
and carried him to Kirkby Steven that night, and shut him up in a chamber,
and set a guard upon him; but divers of our friends following into the town,
where a great multitude was gathered together for meeting,
then did the people come from the steeple-house, where another had been preaching;
for divers of the priests were gathered together that day; some preaching, some plotting,
and some persecuting.
Jezebel`'s fast was a preparation for Naboth`'s death.
But Friends not being suffered to go into the house where James was,
they abode in the streets; and some of them being moved to speak to the people,
the priests perceiving the people to give audience to what was spoken, made complaint.
Whereupon, some were sent forth, and with violence fetched in one Francis Howgill,
a Friend, who was speaking to the people, and brought him into the high priest`'s hall,
where were five priests assembled, with many others of their party, but not one Friend.
And bringing him before the justice, he was commanded to put off his hat.
He answered, '`I know no such law.`' The priest said,
'`He will tread both ministry and magistracy under his feet.`' He said,
'`Thou art a false accuser; prove wherein.`' But one that stood by, took off his hat,
and cast it into the fire.
Then said the justice, '`What is this thou speakest against the ministers?`' He answered,
'`What hast thou to accuse me of?`' Whereupon one affirmed that he said,
'`all the ministers that taught for hire, and in steeple-houses, were enemies,
and liars against Jesus Christ,
and no ministers of Jesus Christ.`' Upon that the justice said,
'`Thou speakest against the law; for the law gives them their maintenance.`' He said,
'`I meddle not with the law, but with their practice.`' Then said Francis to the priest,
'`Didst thou ever know a minister of Jesus Christ that was a persecutor,
or did labour to imprison any?`' And after some more discourse, he said to the priest,
'`I have seen a great deal of tyranny and persecution in
this day`'s actions.`' Then said the justice to the people,
'`Take notice,`' he saith,
'`the law I act by is tyranny and persecution.`' To which the people assented.
Then said Francis, '`Thou mayst give out to the people what thou wilt,
but I speak not of the law, but of your actions.`' Upon that, he was sent to prison;
a guard of eight men were set over them, who spent the night in drinking, swearing,
and filthy and unclean talking;
and the more they were desired by the people to take heed of sin,
the more filthy they did appear;
but these are the fittest instruments for acting the priests`' intentions,
being members of their churches.
The next day they were guarded to Appleby: but some Friends following,
could not be suffered to pass on the streets that way,
so great was their envy against all that set their face that way.
And the prisoners being brought thither,
much means was used that none should come at them, but such as were sent to tempt them.
There they were kept until the sessions;
in which time they sent up and down the country to seek
for any who would witness any thing against them,
and improved their utmost interest for their advantage.
A jury was chosen, divers of them were resolved on the business,
so that it was told the prisoners what would become of them,
before the day of examination came; and it was accordingly.
For the day came, and judgment passed;
but the prisoners never saw their accusers nor know who they are; but against that day,
the priests had prepared three large petitions stuffed
with most filthy untruths and slanders,
raised out of the bottomless pit; but not one of them proved,
though one of the justices said to them,
'`It is fit they should be proved;`' neither was there anything
in them which they could charge upon the prisoners,
save only what the power of the Lord had manifested at their meetings,
in shaking proud flesh, and pouring out his spirit upon many, especially, as they said,
upon little children; which the priests concluded was sorcery and witchery,
and of the devil;
hereby declaring themselves to be of that generation '`who called the good man of the
house Beelzebub;`' and if they should not do the same to them of his household,
the words of Christ could not be fulfilled.

Likewise they had gathered up all reports, true or false,
of things done by many that the prisoners had not seen the faces of, nor ever knew;
thinking thereby to make them odious to the people.
They also brought two priests out of Lancashire,
to swear things that another man had spoken in the
presence of four justices of the peace,
and for which the man had been tried and cleared.
And these they brought,
thinking to '`add afflictions to the prisoners`'
bonds.`' But he is kept in great peace and joy,
having not any comfort from man, but from God,
who hath appeared to him in this condition, and hath given him assurance of his love,
in whom he rests.
To whom be praise, honour, and glory, forever.
Amen.

=== The examination of James Nayler, upon an indictment of blasphemy, at the sessions Appleby, in January, 1652.

[.discourse-part]
_Justice Pearson._
Put off your hats.

[.discourse-part]
_James._
I do it not in contempt of authority: for I honour the power as it is of God,
without respecting persons, it being forbidden in scripture.
He that respects men`'s persons commits sin,
and is convinced of the law as a transgressor.

[.discourse-part]
_Just.
Pear._
That is meant of respecting persons in judgment.

[.discourse-part]
_James._
If I see one in goodly apparel and a gold ring, and see one in poor and vile raiment,
and say to him in fine apparel, sit thou in a higher place than the poor, I am partial,
and judged of evil thoughts.

[.discourse-part]
_Col.
Brigs._
If thou wert in the parliament house, wouldst thou keep it on?

[.discourse-part]
_Jam._
If God should keep me in the same mind I am in now I should.

[.discourse-part]
_Col.
Brigs._
I knew thou wouldst contemn authority.

[.discourse-part]
_Jam._
I speak in the presence of God, I do not contemn authority;
but I am subject to the power as it is of God, for conscience`' sake.

[.discourse-part]
_Just.
Pear._
Now authority commands thee put off thy hat, what sayest thou to it?

[.discourse-part]
_Jam._
Where God commands one thing, and man another, I am to obey God rather than man.

[.discourse-part]
_Col.
Benson._
See whether the law commands it, or your own wills.
The indictment was read,
wherein James was indicted for saying that '`Christ was
in him,`' and '`that there was but one word of God.`'

[.discourse-part]
_Col.
Brigs._
Where wast thou born?

[.discourse-part]
Jam.
At Ardislaw, two miles from Wakefield.

[.discourse-part]
_Col.
Brigs._
How long livedst thou there?

[.discourse-part]
Jam.
Until I was married; then I went unto Wakefield parish.

[.discourse-part]
_Col.
Brigs._
What profession wast thou of?

[.discourse-part]
_Jam._
A husbandman.

[.discourse-part]
_Col.
Brigs._
Wast thou a soldier?

[.discourse-part]
Jam.
Yea; I was a soldier betwixt eight and nine years.

[.discourse-part]
_Col.
Brigs._
Wast thou not at Burford among the levellers?

[.discourse-part]
_Jam._
I was never there.

[.discourse-part]
_Col.
Brigs._
I charge thee by the Lord that thou tell me whether thou wast or not?

[.discourse-part]
_Jam._
I was then in the north,
and was never taxed for any mutiny or any other thing while I served the parliament.

[.discourse-part]
_Col.
Brigs._
What was the cause of thy coming into these parts?

[.discourse-part]
_Jam._
If I may have liberty I shall declare it.
I was at the plough, meditating on the things of God, and suddenly I heard a voice,
saying unto me,
'`Get thee out from thy kindred and from thy father`'s
house;`' and I had a promise given in with it.
Whereupon I did exceedingly rejoice,
that I had heard the voice of that God which I had professed from a child,
but had never known him.

[.discourse-part]
_Col.
Brigs._
Didst thou hear that voice?

[.discourse-part]
_Jam._
Yea, I did hear it; and when I came home, I gave up my estate, cast out my money;
but not being obedient in going forth, the wrath of God was on me,
so that I was made a wonder to all, and none thought I would have lived;
but (after I was made willing) I began to make some preparation; as apparel,
and other necessaries, not knowing whither I should go.
But shortly afterward going from my own house toward the gate with a Friend,
having an old suit, without any money, having neither taken leave of wife or children,
not thinking then of any journey, I was commanded to go into the west,
not knowing whither I should go, nor what I was to do there:
but when I had been there a little while.
I had given me what I was to declare; and ever since I have remained,
not knowing today what I was to do tomorrow.

[.discourse-part]
_Col. Brigs._
What was the promise thou hadst given?

[.discourse-part]
_Jam._
That God would be with me; which promise I find made good every day.

[.discourse-part]
_Col. Brigs._
I never heard such a call as this is, in our time.

[.discourse-part]
_Jam._
I believe thee.

[.discourse-part]
_Just. Pears._
Is Christ in thee?

[.discourse-part]
_Jam._
I witness him in me; and if I should deny him before men,
he would deny me before my Father which is in heaven.

[.discourse-part]
_Just. Pears._
Spiritual, you mean.

[.discourse-part]
_Jam._
Yea, spiritual.

[.discourse-part]
_Just. Pears._
By faith, or how?

[.discourse-part]
_Jam._
By faith.

[.discourse-part]
_Just. Pears._
What difference then between the ministers and you?

[.discourse-part]
_Jam._
The ministers affirm Christ to be in heaven with a carnal body,
but I with a spiritual body.

[.discourse-part]
_Just. Pears._
Which of the ministers say Christ is in heaven with a carnal body?

[.discourse-part]
_Jam._
The minister so called of Kirkby Steven.

[.offset]
Priest Higginson stood up, and affirmed it again openly before all the court.

[.discourse-part]
_Jam._
If Christ be in heaven with a carnal body, and the saints with a spiritual body,
it is not proportionable;
neither was that a carnal body which appeared among the disciples, the doors being shut,
and appeared in divers shapes.

[.discourse-part]
_Quest._
Was Christ man, or not?

[.discourse-part]
_Jam._
Yea, he was, and took upon him the seed of Abraham, and was real flesh and bone;
but is a mystery not known to the carnal man; for he is begotten of the _immortal seed,_
and those that know him, know him to be spiritual;
for it was '`the word`' that '`became flesh,
and dwelt amongst us;`' and if he had not been spiritual he had not wrought my redemption.

[.discourse-part]
_Just. Pears._
Is Christ in thee as man?

[.discourse-part]
_Jam._
Christ filleth all places, and is not divided: separate God and man,
and he is no more Christ.

[.discourse-part]
_Just. Pears._
If we stand to dispute these things, we should have the ministers.

[.discourse-part]
_Jam._
Perceiving priest Higginson offended,
because he had told of his saying that Christ was in heaven with a carnal body,
James said, '`Friend, I had not accused thee,
had I not been asked what was the difference between the ministers and me:
for I am not come to accuse any; for I am against accusations.`'

[.discourse-part]
_Col. Brigs._
Wast thou not of a Kirk about Sawrby?

[.discourse-part]
_Jam._
I was a member of an Independent church at Weedchurch.

[.discourse-part]
_Col. Brigs._
Wast thou not excommunicated for thy blasphemous opinions?

[.discourse-part]
_Jam._
I know not what they have done since I came forth; but before I was not to my knowledge.

[.offset]
Col.
Brigs called to Mr. Coale, saying, '`Did you ever hear such a call as this?
Did you hear it?`'

[.discourse-part]
_Coale._
Yea, I heard part of it.

[.discourse-part]
_Col. Brigs._
Didst not thou write a paper, wherein was mentioned,
that if thou thinkest to be saved by that Christ which died at Jerusalem,
thou art deceived?

[.discourse-part]
_Jam._
If I cannot witness Christ nearer than Jerusalem, I shall have no benefit by him;
but I own no other Christ but that who '`witnessed a good confession before
Pontius Pilate;`' which Christ I witness suffering in me now.

[.discourse-part]
_Col. Brigs._
Wilt thou deny thy hand?

[.discourse-part]
_Jam._
I will not deny my hand, if I may see it; and I desire that I may so much savour,
that that paper may be kept as an evidence either with or against me.

[.offset]
A large petition being read, wherein was something against quaking and trembling.

[.discourse-part]
_Just. Pear._
How comes it to pass that people quake and tremble?

[.discourse-part]
_Jam._
The scriptures witness the same condition in the saints formerly; as David, Daniel,
Habakkuk, and divers others.

[.discourse-part]
_Just. Pear._
Did they fall down?

[.discourse-part]
_Jam._
Yea, some of them did so.

[.discourse-part]
_Coale._
David said all his bones were broken, but these were whole.

[.discourse-part]
_James._
So are these now.

[.discourse-part]
_Coale._
Moses trembled; for he saw the face of God, and all Israel.

[.discourse-part]
_James._
Did all Israel see the face of God?
That crosseth the scriptures.

[.discourse-part]
_Coale._
They saw his glory.
I shall see the Lord with these eyes; putting his fingers to his eyes.

[.discourse-part]
_James._
They must first be made spiritual: he cannot be seen with carnal eyes,
for he is a spirit; and no flesh can see God, and live.

[.discourse-part]
_Coale._
That light by which I am justified, is a created light.

[.discourse-part]
_James._
That light by which I am justified, is not a created light.

[.discourse-part]
_Coale._
That is true.

[.discourse-part]
_Just. Pears._
To the word: what sayst thou to the scriptures?
Are they the word of God?

[.discourse-part]
_James._
They are a true declaration of the word that was in them who spoke them forth.

[.discourse-part]
_Higginson._
Is there not a written word?

[.discourse-part]
_James._
Where readest thou in the scriptures of a written word?
The word is spiritual, not seen with carnal eyes: but as for the scriptures,
they are true, and I witness them true, in measure fulfilled in me,
as far as I am grown up.

[.discourse-part]
_Just. Pears._
Why dost thou disturb the ministers in their public worship.

[.discourse-part]
_James._
I have not disturbed them in their public worships.

[.discourse-part]
_Just. Pears._
Why dolt thou speak against tithes, which are allowed by the states?

[.discourse-part]
_James._
I meddle not with the states; I speak against them that are hirelings,
as they are hirelings; those that were sent of Christ, never took tithes,
nor ever sued any for wages.

[.discourse-part]
_Just. Pears._
Dost thou think we are so beggarly as the heathens,
that we cannot afford our ministers maintainance?
We give them it freely.

[.discourse-part]
_James._
They are the ministers of Christ, who abide in the doctrine of Christ.

[.discourse-part]
_Just. Pears._
But who shall judge?
How shall we know them?

[.discourse-part]
_James._
By their fruits you shall know them; they that abide not in the doctrine of Christ,
make it appear they are not the ministers of Christ.

[.discourse-part]
_Just. Pears._
That is true.

=== Accusations against John Lawson, by him answered.

That John Lawson of Lancaster did affirm, December the 4th, 1652,

[.discourse-part]
O+++.+++ '`That he was dead, and rose again.`'

[.discourse-part]
A+++.+++ Thou art a witness against him that is risen from the dead,
whereof the apostles were witnesses.
Here thou showest thyself to be a witness against the living,
and showest thyself to be in the death, and no minister of Christ:
for the ministers of Christ justified them who were raised from the dead:
'`Even when we were dead in trespasses and sins hath he quickened us together with Christ,
and hath raised us together, and hath made us to sit in heavenly places in Christ Jesus.
Likewise reckon you also yourselves to be dead indeed unto sin, but alive unto God,
through Jesus Christ: for in that he died, he died once unto sin; in that he lives,
he lives unto God.
Here thou showest thyself to be no minister of Jesus Christ.
He that believeth, hath passed from death to life,
because he loveth his brethren:`' here thou showest thou dost not believe,
but art in the death, and art in envy; so thou showest forth thyself to be Cain,
and hatest thy brethren.
'`We know that we are translated from death unto life, because we love our brethren;
he that loveth not his brother, abideth in the death;`' and there thou art.
'`Whosoever hateth his brother, is a manslayer;
and you know that no manslayer hath eternal life abiding in him.`' 1 John iii.
And this is thy condition, and here thou art an antichrist in the world,
envying those who are raised from the dead; and thou seekest to bring them to the death,
whom God hath raised from the death.
Thou hast not seen thyself to be the prodigal; yet the scripture saith,
'`This my son was dead, and is alive again:`' but thou art without God in the world.

[.discourse-part]
O+++.+++ 2. '`That the day of judgment was past.`'

[.discourse-part]
A+++.+++ Christ speaks, '`The bruised reed he will not break,
the smoking flax he will not quench,
till he bring forth judgment into victory.`' Here
thou showest thyself to be ignorant of the scripture;
but only as a hearsayer thou speakest, and the outside of the letter, and not Christ;
and canst not witness him, who brings forth judgment into victory,
but standest as a witness against them who witness the scriptures fulfilled in them,
and Christ bringing forth judgment into victory:
and here thou showest thyself to be unacquainted with Christ,
and thy nakedness and ignorance thou makest appear.

[.discourse-part]
O+++.+++ 3. '`That he had been in hell, and is now in heaven.`'

[.discourse-part]
A+++.+++ Here thou showest thyself to be a witness against the holy men of God.
Jonah saith, '`Out of the belly of hell cried I,
and thou heardest my voice,`' and the Lord delivered him out of hell;
and might not he confess it, thou hypocrite?
'`For thou wilt not leave my soul in hell,
neither wilt thou suffer thy holy one to see corruption.
Thou hast delivered my soul out of death: bless the Lord, my soul,
and all that is within me bless his holy name.`' How darest thou profess the scriptures,
and the holy men of God`'s conditions, which were raised and brought out of death;
and if any witness the holy men of God`'s condition, thou persecutest them?
O thou blind hypocrite! here thou showest thou never sawest hell`'s mouth yet,
therefore thou never criedst in hell yet.

[.discourse-part]
O+++.+++ 4. '`That he was come to the infinite company of the first born,
and the spirits of just men made perfect.`'

[.discourse-part]
A+++.+++ Paul said, (who was a minister of God,) but ye are come to Mount Zion,
and unto the city of the living God, the heavenly Jerusalem,
'`and to an innumerable company of angels,
to the general assembly and church of the first born, which are written in heaven;
unto God the judge of all, and to the spirits of just men made perfect.
Paul was a minister of Jesus Christ by the will of God,`'
who encouraged the saints who were brought hither;
but thou now perscutest them,
and art a witness against them that confess they are brought hither; here thou showest,
thou hast the spirit of error, openly: and art no minister of God, no, not of the letter;
but art against the letter as it speaks, persecuting them that have the life of it.

[.discourse-part]
O+++.+++ 5. That he had heard the last trumpet sound, and seen the new Jerusalem.

[.discourse-part]
A+++.+++ Here thou showest forth thy spite and venom: if John was here,
which saw the great city and holy Jerusalem descend out of heaven from God (John said,
I saw the holy city, New Jerusalem,
come down from God out of heaven) thou wouldst be a witness against him;
and thou showest thyself in the generation that were ever persecutors, slanderers,
and opposers of the power of truth.
Where the same spirit is that was in John, he sees these things now, as he did then,
but where the same spirit is not, which thou showest thou hast not,
but a contrary spirit that persecutes them which do see
those things this is as a dog to bite and devour.
John saw the trumpet sound, which shows thou art not come to the first.
Blow the trumpet in Zion, sound an alarm in my holy mountain;
let all the inhabitants of the earth tremble.
Here be thou a witness against thyself, that thou art a witness against the truth,
and in the generation of them that ever slew the righteous seed.

[.discourse-part]
O+++.+++ 6. That John Lawson said he had God face to face.

[.discourse-part]
A+++.+++ Here thou showest thyself to be a witness against them that know God,
and makest thyself manifest to be a heathen: for all are heathens that do not know God;
and no man knoweth God, saving he that is born of God; and who are born of God,
are owners of the truth, and not against it, but against the deceit.
Jacob said, I have seen God face to face.
Isaiah said, mine eyes have seen the king, the Lord of hosts.
Job said, I have heard of thee by the hearing of the ear;
but now mine eyes have seen thee.
And God spake to Moses face to face.
Here you may take your oaths, and swear against Jacob, against Isaiah, against Job,
and against Moses.
Where the same spirit is made manifest; and who are born of God, know God face to face,
as they did; but they who are born of the flesh,
persecute them who are born of the spirit;
and here you show yourselves to be taking oaths and swearing against them that know God,
seeking to bring them to prison or bondage: so you never read in all the scriptures,
that the prophets or the apostles took their oaths
against any which confessed they had seen God,
or put up a petition to the magistrates, or witnessed it with oaths against any of them:
the ministers of God said, swear not at all.
And here you show yourselves to be no ministers of God, but without God;
for the ministers of God are to bring people to know God, and to the church in God,
and to the heavenly Jerusalem, and to the innumerable company of angels,
and minister to that which is in prison, and in death:
but if any come to witness these things fulfilled,
you are witnesses against them with oaths,
and would bring the bodies of such into prison,
where the seed of God is raised out of prison within;
showing yourselves to be antichrists, persecutors of the power of truth,
and beasts which shall make war against the saints, and against the Lamb,
but the Lamb shall get the victory.

Job cried when the Lord hid his face, and David cried when the Lord hid his face,
and said, O Lord, I will seek thy face.
And here you show, you neither know his face, nor have seen it;
but are persecutors of them who know it and seek it.

Praises, praises be to the Lord forever.

[.the-end]
End of Vol. III
