== Note From The Friends Library

Since the original publication of The Journal of George Fox in 1694,
many abridged memoirs and shortened journals have
appeared at various times and in various forms.
The version you are now reading is the complete, original,
two-volume journal (first compiled and edited by Thomas Ellwood),
which was divided into chapters,
and supplied with numerous historical and biographical footnotes by William
Armistead in 1852.
This document has not been abridged or edited in any way,
except (as far as I am aware) for slight modernizations
of spelling done by Armistead himself.
There is, however, a substantial supplement appended to this document,
from which I removed the lengthy
"`Chronological Register of the Places Visited by the Author,`"
and the "`Texts of Scripture Occurring in This Journal.`"

This edition is in public domain, and PDF scans of the two volumes are available online.
This particular copy was obtained by copying the text from PDFs,
pasting into a word processor document,
and then formatting the text and fixing the thousands
of errors that inevitably result from this process.
Most errors have been found and fixed (by comparing them to the text of a printed copy),
but there are doubtless some that have been missed.

Volume I and II are combined in this one document.

Before beginning,
I'd like to recommend to you not to overlook
Armistead's interesting a valuable footnotes,
and to suggest a quick perusal of the terms defined below.

[.signed-section-signature]
Jason R. Henderson

[.signed-section-context-close]
May, 2018

[.asterism]
'''

[.alt]
=== Short Glossary of Terms:

Papist::
Roman Catholic

Popery::
Roman Catholicism

Professor::
One who professes faith in Christ.
This word has nothing to do with teachers or scholars.

Want or wanting::
Lack or lacking (i.e. "`God's manifest love was not wanting.`")

Principle::
This word is often used to denote the Seed or Word or
Measure of Christ`'s Spirit or Grace sown in the heart of man.

Suffer::
Often means to allow or permit.
(i.e. He would not suffer me to enter.)

Conversation::
A person's conduct, manner of living.

Loath::
Reluctant or unwilling (i.e. "`He was loath to go with me`")

To Own::
To acknowledge, approve, recognize (i.e. "`We could not own him as one of us`")

Forms::
Outward ceremonies, structures, ordinances, practices in religion.

Premunire::
Premunire was a legal judgment designed to disenfranchise
those who refused to formally swear allegiance to the King of England.
Those under a sentence of premunire were considered traitors to their country.
They lost all rights to property and possessions,
were removed from under the kings protection, and were often imprisoned for life.

Assizes::
Court sessions

Mittimus::
Court Order

Apostasy::
falling away, departure, desertion of original Christianity.

Viz.::
Namely, i.e.

Physic::
Medicine

Conventicle::
An unlawful religious gathering

Naked Rapier::
An unsheathed dagger or sword

Victuals::
Food

Writ of Habeas Corpus::
A legal recourse in law through which a person can
report and possibly be liberated from an unlawful detention or imprisonment.
