== Introduction To the Seventh Edition

The present re-issue of the Journal of George Fox has, in a great measure,
resulted from the concern of a Friend lately deceased,
who was actively engaged in the last edition,
and who provided a handsome sum towards the further
republication of this valuable Testimony to the Truth.

Assisted by the above bequest, and prompted by the encouragement of many Friends,
the Editor of this Seventh Edition of the Journal has endeavoured to
increase its usefulness by issuing it in a manner considerably more adapted,
than heretofore, for general usefulness, and calculated, he hopes,
to insure a still more extended circulation.

In printing from the last edition (which was collated with the first and third),
some further slight improvements in the style have been made, and redundancies omitted,
with an occasional transposition in the construction of a sentence,
or the omission or insertion of a word to impart clearness to the sense of the author,
care being taken in every instance not in the least to misrepresent his meaning.
In addition to this, the work has now, for the first time, been divided into chapters;
a general table of contents has been supplied; and a considerable number of Notes,
chiefly biographical and historical, have been added,
which must materially increase its interest.

Though highly approved as a standard work,
there is reason to believe that the Journal of George Fox has not
obtained that attention which its real worth justly demands,
even from the members of the Society which the
author was so eminently instrumental in forming.
Let those who have not perused it be induced to
make themselves acquainted with its contents;
and may those who are of ability,
be stimulated to expend a portion of their means in promoting the circulation of a
work recording the labours of so eminent a servant of the Lord,
concerning whom the following character was given by one of his
contemporaries--not the less truthful and applicable from having been
often quoted--that "`He was indeed a heavenly-minded man,
zealous for the name of the Lord, and preferred the honour of God before all things.
He was valiant for the Truth, bold in asserting it, patient in suffering for it,
unwearied in labouring in it, steady in his testimony to it, immovable as a rock.`"

The many and important truths unfolded in this work,
though conveyed in a style not always suited to the taste of the present day, will,
if patiently and seriously perused, amply compensate the reader,
of whatever denomination, for the time and attention he may bestow upon it.
Sir James Mackintosh says,
it "`is one of the most extraordinary and instructive narratives in the world,
which no reader of competent judgement can peruse without revering the
virtue of the writer;`" and Coleridge in his Biographia Literaria observes:
"`There exist folios on the human understanding, and the nature of man,
which would have a far juster claim to their high rank and celebrity, if,
in the whole huge volume, there could be found as much fulness of heart and intellect,
as bursts forth in many a simple page of George Fox.`"

In every point of view, George Fox was a character of no ordinary rank.
Though a stranger to the polish of human learning, he possessed a truly enlightened mind,
connected with sound practical knowledge; and fearlessly inculcated,
amongst persons of all ranks, sentiments and views on various points,
equally conducive to the immediate comfort,
and to the amelioration and advancement of the various classes of civil society.
These views, though then rejected by many as visionary,
have since met with very general acceptance,
and in some cases have even obtained the favourable attention of government.

But what is of still more importance, he was well taught in the school of Christ.
He was thoroughly versed in the Holy Scriptures, which, to use his own expression,
were "`very precious`" to him, and he always held them in high estimation.
He firmly believed in the Son of God--in the
atoning efficacy of his sacrifice upon the cross,
and in all his offices and works both for us, and in us; and,
by obedience to the Light of Life, the illuminating,
renovating power of the Holy Spirit--to Christ in his spiritual appearance,
he realized in himself the benefits conferred upon
mankind by the sufferings and death of the Saviour.
By a variety of preparatory baptisms, he was, on the one hand,
given to see the depths of Satan, and on the other,
richly instructed in the mysteries of the everlasting kingdom of God.
Thus trained and exercised he became abundantly furnished,
and qualified to enter upon the arduous service,
to which he believed himself Divinely called; and proved himself to be,
as his Journal largely testifies, "`a workman that needed not to be ashamed,
rightly dividing the Word of Truth.`"

Contemplating the character of George Fox in this twofold light, the Editor may,
in conclusion, say with his predecessors,
that he "`indulges a hope that the history of the author`'s life, written by his own hand,
unfolding the energy and operation of that grace by which he was what he was,
will be found interesting to persons of every class,
especially to the really religious of whatever denomination,
and still more peculiarly so to those who profess to believe in the
same doctrines he was engaged so strenuously in preaching.
To the promulgation of these doctrines he steadily devoted upwards of forty years
of his life--a life which exhibited throughout '`an example of suffering affliction,
and of patience;`' evincing him to be, both in principle and in practice,
a genuine disciple of his crucified Lord--a real CHRISTIAN.`"

[.signed-section-signature]
Wilson Armistead

[.signed-section-context-close]
Leeds, 1852.

P+++.+++ S.--The Editor is also desirous of directing the special
attention of the reader to the admirable Preface to this work,
by William Penn.
