== Volume I.

[discrete]
=== Chapter I.

[.chapter-synopsis]
* 1624-1647.
* George Fox`'s birth and parentage
* his gravity and piety in youth. Apprenticed to a shoemaker, who is also a grazier, etc.
* his integrity in dealing. Refuses to drink healths
* his exercises of mind commence
* he lives retired
* is tempted to despair. His sorrows continue for some years
* has a sense of Christ`'s sufferings. Confutes a people who held women to be devoid of souls
* begins to travel on Truth`'s account
* meets with Elizabeth Hooton
* fasts often, and retires to solitary places with his Bible
* his exercises intermit. Sees why none but Christ could speak to his condition. Visits a woman who had fasted twenty-two days
* first declares the Truth at Duckingfield and Manchester. Preaches at a great meeting at Broughton. His troubles wear off, and he weeps for joy
* sees things which cannot be uttered
* is reported to have a discerning spirit
* overcomes his temptations through the power of Christ.

That all may know the dealings of the Lord with me, and the various exercises, trials,
and troubles through which he led me,
in order to prepare and fit me for the work unto which he had appointed me,
and may thereby be drawn to admire and glorify his infinite wisdom and goodness,
I think fit (before I proceed to set forth my public travels in the
service of Truth) briefly to mention how it was with me in my youth,
and how the work of the Lord was begun, and gradually carried on in me,
even from my childhood.

I was born in the month called July, 1624, at Drayton-in-the-clay, in Leicestershire.
My father`'s name was Christopher Fox: he was by profession a weaver, an honest man;
and there was a seed of God in him.
The neighbours called him Righteous Christer.
My mother was an upright woman; her maiden name was Mary Lago,
of the family of the Lagos, and of the stock of the martyrs.

In my very young years I had a gravity and stayedness of mind and spirit,
not usual in children; insomuch,
that when I saw old men behave lightly and wantonly towards each other,
I had a dislike thereof raised in my heart, and said within myself,
"`If ever I come to be a man, surely I shall not do so, nor be so wanton.`"

When I came to eleven years of age, I knew pureness and righteousness;
for while a child I was taught how to walk to be kept pure.
The Lord taught me to be faithful in all things, and to act faithfully two ways, viz.,
inwardly to God, and outwardly to man; and to keep to Yea and Nay in all things.
Tor the Lord showed me, that though the people of the world have mouths full of deceit,
and changeable words, yet I was to keep to Yea and Nay in all things;
and that my words should be few and savoury, seasoned with grace;
and that I might not eat and drink to make myself wanton, but for health,
using the creatures in their service, as servants in their places,
to the glory of Him that created them; they being in their covenant,
and I being brought up into the covenant,
and sanctified by the Word which was in the beginning, by which all things are upheld;
wherein is unity with the creation.

But people being strangers to the covenant of life with God,
they eat and drink to make themselves wanton with the creatures,
wasting them upon their own lusts, and living in all filthiness, loving foul ways,
and devouring the creation; and all this in the world, in the pollutions thereof,
without God: therefore I was to shun all such.

Afterwards, as I grew up, my relations thought to make me a priest;
but others persuaded to the contrary: whereupon I was put to a man, a shoemaker by trade,
but who dealt in wool, and was a grazier, and sold cattle;
and a great deal went through my hands.
While I was with him, he was blessed; but after I left him he broke, and came to nothing.
I never wronged man or woman in all that time; for the Lord`'s power was with me,
and over me to preserve me.
While I was in that service, I used in my dealings the word Verily,
and it was a common saying among people that knew me, "`If George says Verily,
there is no altering him.`"
When boys and rude people would laugh at me, I let them alone, and went my way;
but people had generally a love to me for my innocency and honesty.
When I came towards nineteen years of age, being upon business at a fair,
one of my cousins, whose name was Bradford, a professor,
and having another professor with him,
came to me and asked me to drink part of a jug of beer with them, and I, being thirsty,
went in with them; for I loved any that had a sense of good,
or that sought after the Lord.
When we had drunk each a glass, they began to drink healths, calling for more,
and agreeing together, that he that would not drink should pay all.
I was grieved that any who made profession of religion, should do so.
They grieved me very much, having never had such a thing put to me before,
by any sort of people; wherefore I rose up to go, and putting my hand into my pocket,
laid a groat on the table before them, and said, "`If it be so, I will leave you.`"
So I went away; and when I had done what business I had to do, I returned home,
but did not go to bed that night, nor could I sleep, but sometimes walked up and down,
and sometimes prayed and cried to the Lord, who said unto me,
"`Thou seest how young people go together into vanity, and old people into the earth;
thou must forsake all, both young and old, and keep out of all,
and be a stranger unto all.`"

Then at the command of God, on the ninth day of the seventh month, 1643,
I left my relations, and broke off all familiarity or fellowship with old or young.
I passed to Lutterworth, where I stayed some time; and thence to Northampton,
where also I made some stay: then to Newportpagnell, whence, after I had stayed a while,
I went to Barnet, in the fourth month, called June, in 1644.
As I thus travelled through the country, professors took notice,
and sought to be acquainted with me; but I was afraid of them,
for I was sensible they did not possess what they professed.
Now during the time that I was at Barnet, a strong temptation to despair came upon me.
Then I saw how Christ was tempted, and mighty troubles I was in;
sometimes I kept myself retired in my chamber, and often walked solitary in the chace,^
footnote:[Open Fields]`" to wait upon the Lord.

I wondered why these things should come to me; and I looked upon myself and said,
"`Was I ever so before?`" Then I thought, because I had forsaken my relations,
I had done amiss against them;
so I was brought to call to mind all the time that I had thus spent,
and to consider whether I had wronged any.
But temptations grew more and more, and I was tempted almost to despair;
and when Satan could not effect his design upon me that way, he laid snares for me,
and baits to draw me to commit some sin,
whereby he might take advantage to bring me to despair.
I was about twenty years of age when these exercises came upon me;
and I continued in that condition some years, in great trouble,
and fain would have put it from me.
I went to many a priest to look for comfort, but found no comfort from them.

From Barnet I went to London, where I took a lodging,
and was under great misery and trouble there;
for I looked upon the great professors of the city,
and I saw all was dark and under the chain of darkness.
I had an uncle there, one Pickering, a Baptist (and they were tender then),
yet I could not impart my mind to him, nor join with them; for I saw all, young and old,
where they were.
Some tender people would have had me stay, but I was fearful,
and returned homewards into Leicestershire again,
having a regard upon my mind unto my parents and relations, lest I should grieve them;
who, I understood, were troubled at my absence.

When I was come down into Leicestershire, my relations would have had me marry,
but I told them I was but a lad, and I must get wisdom.
Others would have had me into the auxiliary band among the soldiery, but I refused;
and I was grieved that they proffered such things to me, being a tender youth.
Then I went to Coventry, where I took a chamber for a while at a professor`'s house,
till people began to be acquainted with me;
for there were many tender people in that town.
After some time I went into my own country again, and was there about a year,
in great sorrows and troubles, and walked many nights by myself.

Then the priest of Drayton, the town of my birth, whose name was Nathaniel Stevens,
came often to me, and I went often to him; and another priest sometimes came with him;
and they would give place to me to hear me, and I would ask them questions,
and reason with them.
And this priest Stevens asked me a question, viz., Why Christ cried out upon the cross,
"`My God, my God, why hast thou forsaken me?`" and why he said, "`If it be possible,
let this cup pass from me; yet not my will,
but thine be done?`" I told him that at that time the sins of all mankind were upon him,
and their iniquities and transgressions with which he was wounded, which he was to bear,
and to be an offering for, as he was man, but he died not as he was God; and so,
in that he died for all men, and tasted death for every man,
he was an offering for the sins of the whole world.
This I spoke, being at that time in a measure sensible of Christ`'s sufferings,
and what he went through.
And the priest said, "`It was a very good, full answer,
and such a one as he had not heard.`"
At that time he would applaud and speak highly of me to others;
and what I said in discourse to him on the week-days, he would preach on the first-days;
for which I did not like him.
This priest afterwards became my great persecutor.

After this I went to another ancient priest at Mancetter, in Warwickshire,
and reasoned with him about the ground of despair and temptations;
but he was ignorant of my condition; he bade me take tobacco and sing psalms.
Tobacco was a thing I did not love, and psalms I was not in a state to sing;
I could not sing.
Then he bid me come again, and he would tell me many things;
but when I came he was angry and pettish, for my former words had displeased him.
He told my troubles, sorrows, and griefs to his servants;
which grieved me that I had opened my mind to such a one.
I saw they were all miserable comforters; and this brought my troubles more upon me.
Then I heard of a priest living about TajiWorth, who was accounted an experienced man,
and I went seven miles to him; but I found him only like an empty hollow cask.
I heard also of one called Dr. Cradock, of Coventry, and went to him.
I asked him the ground of temptations and despair,
and how troubles came to be wrought in man? He asked me,
Who was Christ`'s father and mother? I told him, Mary was his mother,
and that he was supposed to be the Son of Joseph, but he was the Son of God.
Now, as we were walking together in his garden, the alley being narrow, I chanced,
in turning, to set my foot on the side of a bed, at which the man was in a rage,
as if his house had been on Are.
Thus all our discourse was lost, and I went away in sorrow, worse than I was when I came.
I thought them miserable comforters, and saw they were all as nothing to me;
for they could not reach my condition.
After this I went to another, one Macham, a priest in high account.
He would needs give me some physic, and I was to have been let blood;
but they could not get one drop of blood from me,
either in arms or head (though they endeavoured to do so), my body being, as it were,
dried up with sorrows, grief and troubles,
which were so great upon me that I could have wished I had never been born,
or that I had been born blind, that I might never have seen wickedness or vanity;
and deaf, that I might never have heard vain and wicked words,
or the Lord`'s name blasphemed.
When the time called Christmas came, while others were feasting and sporting themselves,
I looked out poor widows from house to house, and gave them some money.
When I was invited to marriages (as I sometimes was), I went to none at all,
but the next day, or soon after, I would go and visit them; and if they were poor,
I gave them some money;
for I had wherewith both to keep myself from being chargeable to others,
and to administer something to the necessities of those who were in need.

About the beginning of the year 1646, as I was going to Coventry,
and approaching towards the gate, a consideration arose in me,
how it was said that "`all Christians are believers,
both Protestants and Papists;`" and the Lord opened to me that, if all were believers,
then they were all born of God, and passed from death to life,
and that none were true believers but such; and though others said they were believers,
yet they were not.
At another time, as I was walking in a field on a first-day morning,
the Lord opened unto me,
"`that being bred at Oxford or Cambridge was not enough to fit and
qualify men to be ministers of Christ;`" and I wondered at it,
because it was the common belief of people.
But I saw it clearly as the Lord opened it to me, and was satisfied,
and admired the goodness of the Lord who had opened this thing unto me that morning.
This struck at priest Steven`'s ministry, namely,
"`that to be bred at Oxford or Cambridge was not enough
to make a man fit to be a minister of Christ.`"
So that which opened in me, I saw struck at the priest`'s ministry.
But my relations were much troubled that I would not go with them to hear the priest;
for I Would get into the orchards, or the fields, with my Bible, by myself.
I asked them, Did not the apostle say to believers,
that "`they needed no man to teach them,
but as the anointing teacheth them?`" And though they knew this was Scripture,
and that it was true,
yet they were grieved because I could not be subject in this matter,
to go to hear the priest with them.
I saw that to be a true believer was another thing than they looked upon it to be:
and I saw that being bred at Oxford or Cambridge did
not qualify or fit a man to be a minister of Christ:
what then should I follow such for? So neither these, nor any of the Dissenting people,
could I join with, but was a stranger to all, relying wholly upon the Lord Jesus Christ.

At another time it was opened in me, "`That God, who made the world,
did not dwell in temples made with hands.`"
This at first seemed a strange word,
because both priests and people used to call their temples or churches, dreadful places,
holy ground, and the temples of God.
But the Lord showed me clearly,
that he did not dwell in these temples which men had commanded and set up,
but in people`'s hearts: for both Stephen and the apostle Paul bore testimony,
that he did not dwell in temples made with hands,
not even in that which he had once commanded to be built, since he put an end to it;
but that his people were his temple, and he dwelt in them.
This opened in me as I walked in the fields to my relations`' house.
When I came there, they told me that Nathaniel Stevens, the priest, had been there,
and told them "`he was afraid of me, for going after new lights.`"
I smiled in myself,
knowing what the Lord had opened in me concerning him and his brethren;
but I told not my relations, who though they saw beyond the priests,
yet they went to hear them, and were grieved because I would not go also.
But I brought them Scriptures, and told them,
there was an anointing within man to teach him,
and that the Lord would teach his people himself.
I had also great openings concerning the things written in the Revelations;
and when I spoke of them, the priests and professors would say that was a sealed book,
and would have kept me out of it: but I told them, Christ could open the seals,
and that they were the nearest things to us;
for the epistles were written to the saints that lived in former ages,
but the Revelations were written of things to come.

After this, I met with a sort of people that held, women have no souls,
(adding in a light manner,) no more than a goose.
But I reproved them, and told them that was not right; for Mary said,
"`My soul doth magnify the Lord, and my spirit hath rejoiced in God my Saviour.`"

Removing to another place, I came among a people that relied much on dreams.
I told them, except they could distinguish between dream and dream,
they would confound all together; for there were three sorts of dreams;
multitude of business sometimes caused dreams;
and there were whisperings of Satan in man in the night-season;
and there were speakings of God to man in dreams.
But these people came out of these things, and at last became Friends.

Now though I had great openings,
yet great trouble and temptation came many times upon me; so that when it was day,
I wished for night, and when it was night, I wished for day:
and by reason of the openings I had in my troubles, I could say as David said,
"`Day unto day uttereth speech, and night unto night showeth knowledge.`"
When I had openings, they answered one another, and answered the Scriptures;
for I had great openings of the Scriptures: and when I was in troubles,
one trouble also answered to another.

About the beginning of the year 1647, I was moved of the Lord to go into Derbyshire,
where I met with some friendly people, and had many discourses with them.
Then passing further into the Peak-country, I met with more friendly people,
and with some in empty, high notions.
Travelling on through some parts of Leicestershire and into Nottinghamshire,
I met with a tender people, and a very tender woman, whose name was Elizabeth Hooton;^
footnote:[Elizabeth Hooton was born at Nottingham about the year 1600;
was the wife '`of a person who occupied a respectable position in society.
In 1647, when George Fox first met with her,
she formed one of a company of serious persons, who occasionally met together.
Little is known of her,
but "`the meetings and discourses`" she had with George Fox appear to have
been the means of convincing her of the spiritual views of Friends.
Sewel says in 1650--"`From a true experience of the Lord`'s work in man,
she felt herself moved publicly to preach the way of salvation to others.`"
She was therefore not only the first of her sex,
but the second individual who appeared in the character
of a minister amongst the newly-gathered society.
The preaching of women was not at this period considered singular,
several being thus engaged among the various religious sects then in England.
Elizabeth Hooton had not long publicly testified as a minister,
before her sincerity and faithfulness were tested by persecution.
Besides suffering in other ways, she endured several imprisonments,
sometimes for months together.
As a gospel minister, she stood high in the estimation of her friends,
and in advanced life performed two religious visits to America and the West Indies,
the latter of which occupied her several years.
She was one who travelled with George Fox amongst the West India Islands,
as related elsewhere in these volumes, being suddenly taken ill in Jamaica,
where she died the day following, aged about 71 years, a minister 21 years.]
and with these I had some meetings and discourses.
But my troubles continued, and I was often under great temptations; I fasted much,
and walked abroad in solitary places many days, and often took my Bible,
and went and sat in hollow trees and lonesome places till night came on; and frequently,
in the night, walked mournfully about by myself:
for I was a man of sorrows in the times of the first workings of the Lord in me.

During all this time I was never joined in profession of religion with any,
but gave myself up to the Lord, having forsaken all evil company,
and taken leave of father and mother and all other relations,
and travelled up and down as a stranger, in the earth,
which way the Lord inclined my heart;
taking a chamber to myself in the town where I came, and tarrying sometimes a month,
more or less in a place; for I durst not stay long in any place,
being afraid both of professor and profane, lest, being a tender young man,
I should be hurt by conversing much with either.
For which reason I kept myself much as a stranger,
seeking heavenly wisdom and getting knowledge from the Lord;
and was brought off from outward things, to rely wholly on the Lord alone.
Though my exercises and troubles were very great,
yet were they not so continual but that I had some intermissions,
and was sometimes brought into such a heavenly joy,
that I thought I had been in Abraham`'s bosom.
As I cannot declare the misery I was in, it was so great and heavy upon me;
so neither can I set forth the mercies of God unto me in all my misery.
O, the everlasting love of God to my soul,
when I was in great distress! when my troubles and torments were great,
then was his love exceedingly great.
"`Thou, Lord, makest a fruitful field a barren wilderness,
and a barren wilderness a fruitful field; thou bringest down and settest up;
thou killest and makest alive; all honour and glory be to thee, O Lord of glory;
the knowledge of thee in the Spirit, is life; but that knowledge which is fleshly,
works death.`"
While there is this knowledge in the flesh, deceit and self-will conform to anything,
and will say yes, yes, to that it doth not know.
The knowledge which the world hath of what the prophets and apostles spoke,
is a fleshly knowledge; and the apostates from the life,
in which the prophets and apostles were, have gotten their words, the Holy Scriptures,
in a form, but not in the life nor Spirit that gave them forth.
So they all lie in confusion, and are making provision for the flesh,
to fulfil the lusts thereof;
but not to fulfil the law and command of Christ in his power and Spirit: this, they say,
they cannot do; but to fulfil the lusts of the flesh, that they can do with delight.

Now after I had received that opening from the Lord,
that "`to be bred at Oxford or Cambridge was not sufficient to fit a
man to be a minister of Christ,`" I regarded the priests less,
and looked more after the Dissenting people.
Among them I saw there was some tenderness;
and many of them came afterwards to be convinced, for they had some openings.
But as I had forsaken the priests, so I left the separate preachers also,
and those esteemed the most experienced people;
for I saw there was none among them all that could speak to my condition.
When all my hopes in them and in all men, were gone,
so that I had nothing outwardly to help me, nor could I tell what to do; then,
O! then I heard a voice which said, "`There is one, even Christ Jesus,
that can speak to thy condition;`" and when I heard it, my heart did leap for joy.
Then the Lord let me see why there was none upon
the earth that could speak to my condition,
namely, that I might give Him all the glory; for all are concluded under sin,
and shut up in unbelief, as I had been, that Jesus Christ might have the pre-eminence,
who enlightens, and gives grace, and faith, and power.
Thus when God doth work, who shall hinder it? and this I knew experimentally.
My desires after the Lord grew stronger, and zeal in the pure knowledge of God,
and of Christ alone, without the help of any man, book, or writing.
For though I read the Scriptures that spoke of Christ and of God; yet I knew Him not,
but by revelation, as He who hath the key did open,
and as the Father of Life drew me to his Son by his Spirit.
Then the Lord gently led me along, and let me see his love,
which was endless and eternal,
surpassing all the knowledge that men have in the natural state,
or can obtain from history or books; and that love let me see myself,
as I was without him.
I was afraid of all company, for I saw them perfectly where they were,
through the love of God, which let me see myself, I had not fellowship with any people,
priests or professors, or any sort of separated people, but with Christ,
who hath the key, and opened the door of Light and Life unto me.
I was afraid of all carnal talk and talkers, for I could see nothing but corruptions,
and the life lay under the burden of corruptions.
When I myself was in the deep, shut up under all,
I could not believe that I should ever overcome; my troubles, my sorrows,
and my temptations were so great, that I thought many times I should have despaired,
I was so tempted.
But when Christ opened to me, how He was tempted by the same devil,
and overcame him and bruised his head, and that through him and his power, light, grace,
and Spirit, I should overcome also, I had confidence in him;
so He it was that opened to me, when I was shut up, and had no hope nor faith.
Christ, who had enlightened me, gave me his light to believe in; he gave me hope,
which he himself revealed in me, and he gave me his Spirit and grace,
which I found sufficient in the deeps and in weakness.
Thus, in the deepest miseries, and in the greatest sorrows and temptations,
that many times beset me, the Lord in his mercy did keep me.
I found that there were two thirsts in me; the one after the creatures,
to get help and strength there; and the other after the Lord, the Creator,
and his Son Jesus Christ.
I saw all the world could do me no good; if I had had a king`'s diet, palace,
and attendance, all would have been as nothing; for nothing gave me comfort,
but the Lord by his power.
I saw professors, priests, and people,
were whole and at ease in that condition which was my misery;
and they loved that which I would have been rid of.
But the Lord stayed my desires upon himself, from whom came my help,
and my care was cast upon him alone.
Therefore, all wait patiently upon the Lord, whatsoever condition you be in;
wait in the grace and truth that came by Jesus: for if ye so do,
there is a promise to you, and the Lord God will fulfil it in you.
Blessed are all they that do indeed hunger and thirst after righteousness,
they shall be satisfied with it.
I have found it so, praised be the Lord who filleth with it,
and satisfieth the desires of the hungry soul.
O let the house of the spiritual Israel say, "`His mercy endureth forever!`"
It is the great love of God to make a wilderness of that which
is pleasant to the outward eye and fleshly mind;
and to make a fruitful field of a barren wilderness.
This is the great work of God.
But while people`'s minds run in the earthly, after the creatures and changeable things,
changeable ways and religions, and changeable, uncertain teachers,
their minds are in bondage, they are changeable,
tossed up and down with windy doctrines and thoughts, and notions and things;
their minds being out of the unchangeable truth in the inward parts,
the Light of Jesus Christ, which would keep them to the unchangeable.
He is the way to the Father;
and in all my troubles he preserved me by his Spirit and power;
praised be his holy name for ever!

Again, I heard a voice which said, "`Thou serpent! thou dost seek to destroy the life,
but canst not; for the sword which keepeth the tree of life, shall destroy thee.`"
So Christ, the Word of God, that bruised the head of the serpent, the destroyer,
preserved me; my inward mind being joined to his good Seed,
that bruised the head of this serpent, the destroyer.
This inward life sprung up in me, to answer all the opposing professors and priests,
and brought Scriptures to my memory to refute them with.

At another time, I saw the great love of God,
and I was filled with admiration at the infinitude of it;
I saw what was cast out from God, and what entered into God`'s kingdom; and how by Jesus,
the opener of the door, with his heavenly key, the entrance was given; and I saw death,
how it had passed upon all men, and oppressed the seed of God in man, and in me;
and how I in the seed came forth, and what the promise was to.
Yet it was so with me, that there seemed to be two pleading in me;
questionings arose in my mind about gifts and prophecies;
and I was tempted again to despair, as if I had sinned against the Holy Ghost.
I was in great perplexity and trouble for many days;
yet I gave up myself to the Lord still.
One day when I had been walking solitarily abroad, and was come home,
I was wrapped up in the love of God,
so that I could not but admire the greatness of his love.
While I was in that condition, it was opened unto me by the eternal light and power,
and I saw clearly therein, "`that all was done, and to be dons, in and by Christ;
and how he conquers and destroys this tempter, the Devil, and all his works,
and is above him; and that all these troubles were good for me,
and temptations for the trial of my faith, which Christ had given me.`"
The Lord opened me, that I saw through all these troubles and temptations;
my living faith was raised, that I saw all was done by Christ, the life,
and my belief was in Him.
When at any time my condition was veiled, my secret belief was stayed firm,
and hope underneath held me, as an anchor in the bottom of the sea,
and anchored my immortal soul to its Bishop, causing it to swim above the sea, the world,
where all the raging waves, foul weather, tempests, and temptations are.
But, O! then did I see my troubles, trials, and temptations,
more clearly than ever I had done.
As the light appeared, all appeared that is out of the light; darkness, death,
temptations, the unrighteous, the ungodly; all was manifest and seen in the light.
After this, a pure fire appeared in me;
then I saw how he sat as a refiner`'s fire and as fullers`' soap;
--then the spiritual discerning came into me,
by which I did discern my own thoughts, groans, and sighs;
and what it was that veiled me, and what it was that opened me.
That which could not abide in the patience, nor endure the fire,
in the light I found it to be the groans of the flesh,
that could not give up to the will of God; which had so veiled me,
that I could not be patient in all trials, troubles, and perplexities;--,
could not give up self to die by the cross, the power of God,
that the living and quickened might follow him;
and that that which would cloud and veil from the presence of
Christ--that which the sword of the Spirit cuts down,
and which must die, might not he kept alive.
I discerned also the groans of the Spirit, which opened me, and made intercession to God;
in which Spirit is the true waiting upon God,
for the redemption of the body and of the whole creation.
By this Spirit, in which the true sighing is, I saw over the false sighings and groanings.
By this invisible Spirit I discerned all the false hearing, the false seeing,
and the false smelling which was above the Spirit, quenching and grieving it;
and that all they that were there, were in confusion and deceit,
where the false asking and praying is, in deceit,
in that nature and tongue that takes God`'s holy name in vain,
wallows in the Egyptian sea, and asketh, but hath not;
for they hate his light and resist the Holy Ghost; turn grace into wantonness,
and rebel against the Spirit; and are erred from the faith they should ask in,
and from the Spirit they should pray by.
He that knoweth these things in the true Spirit, can witness them.
The divine light of Christ manifesteth all things; the spiritual fire trieth all things,
and severeth all things.
Several things did I then see as the Lord opened them to me;
for he showed me that which can live in his holy refining fire,
and that can live to God under his law.
He made me sensible how the law and the prophets were until John;
and how the least in the everlasting kingdom of God is greater than John.
The pure and perfect law of God is over the flesh, to keep it and its works,
which are not perfect, under, by the perfect law; and the law of God that is perfect,
answers the perfect principle of God in every one.
This law the Jews, and the prophets, and John were to perform and do.
None know the giver of this law but by the Spirit of God; neither can any truly read it,
or hear its voice, but by the Spirit of God; he that can receive it, let him.
John, who was the greatest prophet that was horn of a woman,
did bear witness to the light, which Christ, the great heavenly prophet,
hath enlightened every man that cometh into the world withal;
that they might believe in it, and become the children of light,
and so have the light of life, and not come into condemnation.
For the true belief stands in the light that condemns all evil, and the Devil,
who is the prince of darkness, and would draw Out of the light into condemnation.
They that walk in this light, come to the mountain of the house of God,
established above all mountains, and to God`'s teaching, who will teach them his ways.
These things were opened to me in the light.

I saw also the mountains burning up; and the rubbish,
the rough and crooked ways and places, made smooth and plain,
that the Lord might come into his tabernacle.
These things are to be found in man`'s heart.
But to speak of these things being within, seemed strange to the rough, and crooked,
and mountainous ones.
Yet the Lord saith, "`O Earth, hear the word of the Lord!`"
The law of the Spirit crosseth the fleshly mind, spirit, and will,
which lives in disobedience, and doth not keep within the law of the Spirit.
I saw this law was the pure love of God, which was upon me,
and which I must go through though I was troubled while I was under it;
for I could not be dead to the law, but through the law which did judge and condemn that,
which is to be condemned.
I saw many talked of the law, who had never known the law to be their schoolmaster;
and many talked of the gospel of Christ,
who had never known life and immortality brought to light in them by it.
You that have been under that schoolmaster, and the condemnation of it,
know these things; for though the Lord in that day opened these things unto me in secret,
they have since been published by his eternal Spirit, as on the house top.
And as you are brought into the law, and through the law to be dead to it,
and witness the righteousness of the law fulfilled in you,
ye will afterwards come to know what it is to be brought into the faith,
and through faith from under the law; and abiding in the faith,
which Christ is the author of, ye will have peace and access to God.
But if ye look out from the faith, and from that which would keep you in the victory,
and look after fleshly things or words, ye will be brought into bondage to flesh again,
and to the law, which takes hold upon the flesh and sin, and worketh wrath,
and the works of the flesh will appear again.
The law of God takes hold upon the law of sin and death; but the law of faith,
or the law of the Spirit of life, which is the love of God,
and which comes by Jesus (who is the end of the law for righteousness`' sake),
makes free from the law of sin and death.
This law of life fleshly-minded men do not know; yet they will tempt you,
to draw you from the Spirit into the flesh, and so into bondage.
Therefore ye, who know the love of God, and the law of his Spirit,
and the freedom that is in Jesus Christ, stand fast in him,
in that divine faith which he is the author of in you;
and be not entangled with the yoke of bondage.
For the ministry of Christ Jesus, and his teaching, bring into liberty and freedom;
but the ministry that is of man, and by man, and which stands in the will of man,
bringeth into bondage, and under the shadow of death and darkness.
Therefore none can be ministers of Christ Jesus but in the eternal Spirit,
which was before the Scriptures were given forth; for if they have not his Spirit,
they are none of his.
Though they may have his light to condemn them that hate it,
yet they can never bring any into unity and fellowship in the Spirit,
except they be in it; for the Seed of God is a burdensome stone to the selfish, fleshly,
earthly will, which reigns in its own knowledge and understanding that must perish,
and in its wisdom that is devilish.
And the Spirit of God is grieved, and vexed,
and quenched with that which brings into the fleshly bondage;
and that which wars against the Spirit of God, must be mortified by it;
for the flesh lusteth against the Spirit, and the Spirit against the flesh;
and these are contrary the one to the other.
The flesh would have its liberty, and the Spirit would have its liberty;
but the Spirit is to have its liberty and not the flesh.
If therefore ye quench the Spirit, and join to the flesh, and be servants of it,
then ye are judged and tormented by the Spirit;
but if ye join to the Spirit and serve God in it,
ye have liberty and victory over the flesh and its works.
Therefore keep in the daily cross, the power of God,
by which ye may witness all that to be crucified which is contrary to the will of God,
and which shall not come into his kingdom.
These things are here mentioned and opened for information, exhortation,
and comfort to others, as the Lord opened them unto me in that day.
In that day I wondered that the children of Israel should murmur for water and
victuals for I could have fasted long without murmuring or minding victuals.
But I was judged at other times,
that I was not contented to be sometimes without the water and bread of life,
that I might learn to know how to want, and how to abound.

I heard of a woman in Lancashire, that had fasted two and twenty days,
and I travelled to see her; but when I came to her I saw that she was under a temptation.
When I had spoken to her what I had from the Lord, I left her,
her father being one high in profession.
Passing on, I went among the professors at Duckingfield and Manchester,
where I stayed a while, and declared truth among them.
There were some convinced, who received the Lord`'s teaching,
by which they were confirmed and stood in the truth.
But the professors were in a rage, all pleading for sin and imperfection,
and could not endure to hear talk of perfection, and of a holy and sinless life.
But the Lord`'s power was over all; though they were chained under darkness and sin,
which they pleaded for, and quenched the tender thing in them.

About this time there was a great meeting of the Baptists, at Broughton,
in Leicestershire, with some that had separated from them;
and people of other notions went thither, and I went also.
Not many of the Baptists came, but many others were there.
The Lord opened my mouth, and the everlasting truth was declared amongst them,
and the power of the Lord was over them all.
For in that day the Lord`'s power began to spring,
and I had great openings in the Scriptures.
Several were convinced in those parts, and were turned from darkness to light,
from the power of Satan unto God; and many were raised up to praise God.
When I reasoned with professors and other people, some became convinced.

I was still under great temptations sometimes, and my inward sufferings were heavy;
but I could find none to open my condition to but the Lord alone,
unto whom I cried night and day.
I went back into Nottinghamshire,
and there the Lord showed me that the natures of those things,
which were hurtful without, were within, in the hearts and minds of wicked men.
The natures of dogs, swine, vipers, of Sodom and Egypt, Pharaoh, Cain, Ishmael, Esau,
etc; the natures of these I saw within, though people had been looking without.
I cried to the Lord, saying, "`Why should I be thus,
seeing I was never addicted to commit those evils?`" and the Lord answered,
"`That it was needful I should have a sense of all conditions,
how else should I speak to all conditions!`" and in this I saw the infinite love of God.
I saw also, that there was an ocean of darkness and death;
but an infinite ocean of light and love, which flowed over the ocean of darkness.
In that also I saw the infinite love of God, and I had great openings.
And as I was walking by the steeple-house,^
footnote:[The term "`steeple-house`" occurs not unfrequently in this _Journal,_
and in the early writings and records of Friends.
Though it may sound harsh,
and appear to savour of the scurrility and intolerance of that zealous age, yet this,
or any other mode of speech adopted by Friends,
was by no means taken up for the purpose of opprobrium,
but rather significantly to discover the little veneration or
distinction they could show for these buildings more than others;
believing that the Almighty is equally present everywhere,
to bless and to sanctify every place and everything to
those that walk uprightly on the earth,
his footstool.
{footnote-paragraph-split}
One of the chief points of George
Fox`'s ministry was to overturn that insidious reverence for names and things which
is too frequently substituted for the worship that is "`in spirit and in truth.`"
Few instances more distinctly exhibit this sort of covert idolatry,
than the general notion of _sanctity_ which is
attached to the building called a "`church.`"
The word __"`church`"__ is, in the Holy Scriptures,
never applied to an outward temple or building, but to a company of believers,
whether generally or particularly.
The use of this term appears to have crept in among Christians,
and with it a superstitious consecration of those places,
as possessing some latent quality not affecting other works of art or nature.
To this Stephen the martyr evidently alluded.
when he said, "`Howbeit the Most High dwelleth not in temples made with hands,`" etc,
Acts 7:48. Clemens of Alexandria says, "`Not the place,
but the congregation of the elect, I call a church,`" Stromat, vii, 715 B.]
in Mansfield, the Lord said unto me, "`That which people trample upon, must be thy food.`"
And as the Lord spoke he opened it to me,
that people and professors trampled upon the life, even the life of Christ;
they fed upon words, and fed one another with words; but they trampled upon the life;
trampled underfoot the blood of the Son of God, which blood was my life,
and lived in their airy notions, talking of him.
It seemed strange to me at first,
that I should feed on that which the high professors trampled upon;
but the Lord opened it clearly to me by his eternal Spirit and Power.

Then came people from far and near to see me;
but I was fearful of being drawn out by them; yet I was made to speak,
and open things to them.
There was one Brown, who had great prophecies and sights upon his death-bed of me.
He spoke only of what I should be made instrumental by the Lord to bring forth.
And of others he spoke, that they should come to nothing, which was fulfilled on some,
who then were something in show.
When this man was buried, a great work of the Lord fell upon me,
to the admiration of many, who thought I had been dead;
and many came to see me for about fourteen days.
I was very much altered in countenance and person,
as if my body had been new moulded or changed.
While I was in that condition, I had a sense and discerning given me by the Lord,
through which I saw plainly, that when many people talked of God and of Christ, etc,
the serpent spoke in them; but this was hard to be borne.
Yet the work of the Lord went on in some, and my sorrows and troubles began to wear off,
and tears of joy dropped from me,
so that I could have wept night and day with tears of joy to the Lord,
in humility and brokenness of heart.
I saw into that which was without end, things which cannot be uttered,
and of the greatness and infinitude of the love of God,
which cannot be expressed by words.
For I had been brought through the very ocean of darkness and death,
and through and over the power of Satan, by the eternal, glorious power of Christ;
even through that darkness was I brought, which covered over all the world,
and which chained down all, and shut up all in death.
The same eternal power of God, which brought me through these things,
was that which afterwards shook the nations, priests, professors, and people.
Then could I say I had been in spiritual Babylon, Sodom, Egypt, and the grave;
but by the eternal power of God I was come out of it, and was brought over it,
and the power of it, into the power of Christ.
I saw the harvest white, and the seed of God lying thick in the ground,
as ever did wheat that was sown outwardly, and none to gather it;
for this I mourned with tears.
A report went abroad of me, that I was a young man that had a discerning spirit;
whereupon many came to me, from far and near, professors, priests, and people.
The Lord`'s power broke forth; and I had great openings and prophecies;
and spoke unto them of the things of God, which they heard with attention and silence,
and went away, and spread the fame thereof.
Then came the tempter, and set upon me again, charging me,
that I had sinned against the Holy Ghost; but I could not tell in what.
Then Paul`'s condition came before me, how,
after he had been taken up into the third heavens,
and seen things not lawful to be uttered, a messenger of Satan was sent to buffet him.
Thus, by the power of Christ, I got over that temptation also.
