== Chapter II

[.chapter-synopsis]
* 1618-1649.
* Begins to have great meetings
* at Mansfield he is moved to pray
* the Lord`'s power so great the house is shaken
* cannot pray in his own will
* a temptation besets him that there is no God, which is dissipated by an inward voice
* he afterwards disputes with and confounds some Atheists
* goes to courts and steeple-houses, etc, to warn against oppression and oaths
* reproves a notorious drunkard, who is reformed
* sees who are the greatest deceivers
* shows how people read and understand the Scriptures
* various mysteries are revealed to him
* he is sent to turn people to the Inward Light, Spirit, and Grace, the Divine Spirit which he infallibly knew would not deceive
* priests and professors rage at these innovations
* he cries for justice in courts and against various wrong things denounces the trade of preaching
* is sent to preach freely.

In the year 1648,
as I was sitting in a friend`'s house in Nottinghamshire (for by this time the power
of God had opened the hearts of some to receive the word of life and reconciliation)
I saw there was a great crack to go throughout the earth,
and a great smoke to go as the crack went;
and that after the crack there should be a great shaking:
this was the earth in people`'s hearts,
which was to be shaken before the seed of God was raised out of the earth.
And it was so; for the Lord`'s power began to shake them,
and great meetings we begun to have,
and a mighty power and work of God there was amongst people,
to the astonishment of both people and priests.

And there was a meeting of priests and professors at a justice`'s house,
and I went among them.
Here they discoursed how Paul said, "`He had not known sin, but by the law, which said,
Thou shalt not lust:`" and they held that to be spoken of the outward law.
But I told them, Paul spoke that after he was convinced;
for he had the outward law before, and was brought up in it,
when he was in the lust of persecution; but this was the law of God in his mind,
which he served, and which the law in his members warred against;
for that which he thought had been life to him, proved death.
So the more sober of the priests and professors yielded,
and consented that it was not the outward law, but the inward,
which showed the inward lust which Paul spoke of after he was convinced:
for the outward law took hold upon the outward action;
but the inward law upon the inward lust.

After this I went again to Mansfield, where was a great meeting of professors and people;
here I was moved to pray; and the Lord`'s power was so great,
that the house seemed to be shaken.
When I had done, some of the professors said it was now as in the days of the apostles,
when the house was shaken where they were.
After I had prayed, one of the professors would pray,
which brought deadness and a veil over them:
and others of the professors were grieved at him and told him,
it was a temptation upon him.
Then he came to me, and desired that I would pray again;
but I could not pray in man`'s will.

Soon after there was another great meeting of professors, and a captain,
whose name was Amor Stoddard, came in.
They were discoursing of the blood of Christ; and as they were discoursing of it, I saw,
through the immediate opening of the invisible Spirit, the blood of Christ.
And I cried out among them, and said,
"`Do ye not see the blood of Christ? See it in your hearts,
to sprinkle your hearts and consciences from dead works,
to serve the living God:`" for I saw it, the blood of the New Covenant,
how it came into the heart.
This startled the professors, who would have the blood only without them, and not in them.
But Captain Stoddard was reached, and said, "`Let the youth speak;
hear the youth speak;`" when he saw they endeavoured to bear me down with many words.

There was also a company of priests, that were looked upon to be tender;
one of their names was Kellett; and several people that were tender, went to hear them.
I was moved to go after them, and bid them mind the Lord`'s teaching in their inward parts.
That priest Kellett was against parsonages then; but afterwards he got a great one,
and turned a persecutor.

Now, after I had had some service in these parts,
I went through Derbyshire into my own county, Leicestershire, again,
and several tender people were convinced.
Passing thence, I met with a great company of professors in Warwickshire,
who were praying, and expounding the Scriptures in the fields.
They gave the Bible to me, and I opened it on the fifth of Matthew,
where Christ expounded the law; and I opened the inward state to them,
and the outward state; upon which they fell into a fierce contention, and so parted;
but the Lord`'s power got ground.

Then I heard of a great meeting to be at Leicester, for a dispute, wherein Presbyterians,
Independents, Baptists, and Common-prayer-men were said to be all concerned.
The meeting was in a steeple-house; and thither I was moved by the Lord God to go,
and be amongst them.
I heard their discourse and reasonings, some being in pews, and the priest in the pulpit;
abundance of people being gathered together.
At last one woman asked a question out of Peter, What that birth was, viz.,
a being born again of incorruptible seed, by the Word of God,
that liveth and abideth for ever? And the priest said to her,
"`I permit not a woman to speak in the church;`" though
he had before given liberty for any to speak.
Whereupon I was wrapped up, as in a rapture, in the Lord`'s power;
and I stepped up and asked the priest,
"`Dost thou call this (the steeple-house) a church? Or dost thou call
this mixed multitude a church?`" For the woman asking a question,
he ought to have answered it, having given liberty for any to speak.
But, instead of answering me, he asked me what a church was? I told him,
"`The church was the pillar and ground of truth, made up of living stones,
living members, a spiritual household, which Christ was the head of:
but he was not the head of a mixed multitude,
or of an old house made up of lime, stones, and wood.`"
This set them all on fire: the priest came down out of his pulpit,
and others out of their pews, and the dispute there was marred.
But I went to a great inn,
and there disputed the thing with the priests and professors of all sorts;
and they were all on a fire.
But I maintained the true church, and the true head thereof, over the heads cf them all,
till they all gave out and fled away.
One man seemed loving, and appeared for a while to join with me;
but he soon turned against me, and joined with a priest,
in pleading for infants`' baptism, though he himself had been a Baptist before;
and so left me alone.
Howbeit, there were several convinced that day;
and the woman that asked the question was convinced, and her family;
and the Lord`'s power and glory shone over all.

After this I returned into Nottinghamshire, and went into the Vale Of Beavor.
As I went, I preached repentance to the people;
and there were many convinced in the Vale of Beavor, in many towns;
for I stayed some weeks amongst them.
One morning, as I was sitting by the fire, a great cloud came over me,
and a temptation beset me; but I sat still.
And it was said, "`All things come by nature;`" and the elements and stars came over me,
so that I was in a manner quite clouded with it.
But as I sat still, and silent, the people of the house perceived nothing.
And as I sat still under it, and let it alone, a living hope arose in me,
and a true voice, winch said, "`There is a living God who made all things.`"
And immediately the cloud and temptation vanished away, and life rose over it all;
my heart was glad, and I praised the living God.
After some time, I met with some people who had a notion that there was no God,
but that all things came by nature.
I had a great dispute with them, and overturned them,
and made some of them confess that there is a living God.
Then I saw that it was good that I had gone through that exercise.
We had great meetings in those parts,
for the power of the Lord broke through in that part of the country.
Returning into Nottinghamshire, I found there a company of shattered Baptists,
and others; and the Lord`'s power wrought mightily, and gathered many of them.
Afterwards I went to Mansfield and thereaway,
where the Lord`'s power was wonderfully manifested both
at Mansfield and other neighbouring towns.
In Derbyshire the mighty power of God wrought in a wonderful manner.
At Eton, a town near Derby, there was a meeting of Friends,
where there was such a mighty power of God that they were greatly shaken,
and many mouths were opened in the power of the Lord God.
Many were moved by the Lord to go to steeple-houses, to the priests and to the people,
to declare the everlasting truth unto them.

At a certain time, when I was at Mansfield,
there was a sitting of the justices about hiring of servants;
and it was upon me from the Lord to go and speak to the justices,
that they should not oppress the servants in their wages.
So I walked towards the inn where they sat; but finding a company of fiddlers there,
I did not go in, but thought to come in the morning,
when I might have a more serious opportunity to discourse with them,
not thinking that a seasonable time.
But when I came again in the morning, they were gone, and I was struck even blind,
that I could not see.
I inquired of the innkeeper where the justices were to sit that day; and he told me,
at a town eight miles off.
My sight began to come to me again; and I went and ran thitherward as fast as I could.
When I was come to the house where they were, and many servants with them,
I exhorted the justices not to oppress the servants in their wages,
but to do that which was right and just to them;
and I exhorted the servants to do their duties, and serve honestly, etc.
They all received my exhortation kindly; for I was moved of the Lord therein.

Moreover, I was moved to go to several courts and steeple-houses at Mansfield,
and other places, to warn them to leave off oppression and oaths,
and to turn from deceit to the Lord, and do justly.
Particularly at Mansfield, after I had been at a court there,
I was moved to go and speak to one of the most wicked men in the country,
one who was a common drunkard, a noted whore-master, and a rhyme-maker;
and I reproved him in the dread of the mighty God, for his evil courses.
When I had done speaking, and left him, he came after me, and told me,
that he was so smitten when I spoke to him,
that he had scarcely any strength left in him.
So this man was convinced, and turned from his wickedness, and remained an honest,
sober man, to the astonishment of the people who had known him before.
Thus the work of the Lord went forward,
and many were turned from the darkness to the light,
within the compass of these three years, 1646, 1647, and 1648.
Divers meetings of Friends, in several places, were then gathered to God`'s teaching,
by his light, Spirit, and power;
for the Lord`'s power broke forth more and more wonderfully.

Now was I come up in Spirit through the flaming sword, into the paradise of God.
All things were new; and all the creation gave another smell unto me than before,
beyond what words can utter.
I knew nothing but pureness, and innocency, and righteousness,
being renewed into the image of God by Christ Jesus, to the state of Adam,
which he was in before he fell.
The creation was opened to me;
and it was showed me how all things had their names given them,
according to their nature and virtue.
I was at a stand in my mind, whether I should practise physic for the good of mankind,
seeing the nature and virtues of things were so opened to me by the Lord.
But I was immediately taken up in Spirit,
to see into another or more steadfast state than Adam`'s innocency,
even into a state in Christ Jesus, that should never fall.
And the Lord showed me that such as were faithful to him,
in the power and light of Christ,
should come up into that state in which Adam was before he fell;
in which the admirable works of creation, and the virtues thereof, may be known,
through the openings of that divine Word of wisdom and power, by which they were made.
Great things did the Lord lead me into, and wonderful depths were opened unto me,
beyond what can by words be declared;
but as people come into subjection to the Spirit of God,
and grow up in the image and power of the Almighty, they may receive the Word of Wisdom,
that opens all things, and come to know the hidden unity in the Eternal Being.

Thus I travelled on in the Lord`'s service, as the Lord led me.
And when I came to Nottingham, the mighty power of God was there among Friends.
From thence I went to Clawson in Leicestershire, in the Vale of Beavor,
and the mighty power of God was there also,
in several towns and villages where Friends were gathered.
While I was there, the Lord opened to me three things,
relating to those three great professions in the world, physic, divinity (so called),
and law.
He showed me that the physicians were out of the wisdom of God,
by which the creatures were made; and so knew not their virtues,
because they were out of the Word of Wisdom; by which they were made.
He showed me that the priests were out of the true faith, which Christ is the author of;
the faith which purifies and gives victory, and brings people to have access to God,
by which they please God; which mystery of faith is held in a pure conscience.
He showed me also, that the lawyers were out of the equity, and out of the true justice,
and out of the law of God, which went over the first transgression, and over all sin,
and answered the Spirit of God, that was grieved and transgressed in man.
And that these three, the physicians, the priests, and the lawyers,
ruled the world out of the wisdom, out of the faith,
and out of the equity and law of God; the one pretending the cure of the body,
the other the cure of the soul, and the third the property of the people.
But I saw they were all out of the wisdom, out of the faith,
out of the equity and perfect law of God.
And as the Lord opened these things unto me, I felt his power went forth over all,
by which all might be reformed, if they would receive and bow unto it.
The priests might be reformed, and brought into the true faith, which was the gift of God.
The lawyers might be reformed, and brought into the law of God,
which answers that of God, which is transgressed, in every one,
and brings to love one`'s neighbour as himself.
This lets man see, if he wrongs his neighbour he wrongs himself;
and this teaches him to do unto others as he would they should do unto him.
The physicians might be reformed, and brought into the wisdom of God,
by which all things were made and created;
that they might receive a right knowledge of them, and understand their virtues,
which the Word of Wisdom, by which they were made and are upheld, hath given them.
Abundance was opened concerning these things; how all lay out of the wisdom of God,
and out of the righteousness and holiness that man at the first was made in.
But as all believe in the light, and walk in the light,
which Christ hath enlightened every man that cometh into the world withal,
and so become children of the light, and of the day of Christ;
in his day all things are seen, visible and invisible, by the divine light of Christ,
the spiritual, heavenly man, by whom all things were made and created.

Then I saw concerning the priests, that although they stood in deceit,
and acted by the dark power, which both they and their people were kept under;
yet they were not the greatest deceivers spoken of in the Scriptures;
for these were not come so far as many of them had come.
But the Lord opened to me who the greatest deceivers were, and how far they might come;
even such as came as far as Cain, to hear the voice of God;
and such as came out of Egypt, and through the Red Sea,
and to praise God on the banks of the sea-shore;
such as could speak by experience of God`'s miracles and wonders;
such as were come as far as Korah and Dathan, and their company;
such as were come as far as Balaam, who could speak the word of the Lord,
who heard his voice and knew it, and knew his Spirit, and could see the star of Jacob,
and the goodliness of Israel`'s tent; the second birth,
which no enchantment could prevail against:
these that could speak so much of their experiences of God,
and yet turned from the Spirit and the Word, and went into the gainsaying; these were,
and would be, the great deceivers, far beyond the priests.
Likewise among the Christians, such as should preach in Christ`'s name,
and should work miracles, cast out devils, and go as far as a Cain, a Korah,
and a Balaam, in the gospel times, these were and would be the great deceivers.
They that could speak some experiences of Christ and God, but lived not in the life:
these were they that led the world after them, who got the form of godliness,
but denied the power; who inwardly ravened from the Spirit,
and brought people into the form, but persecuted them that were in the power,
as Cain did; and ran greedily after the error of Balaam, through covetousness,
loving the wages of unrighteousness, as Balaam did.
These followers of Cain, Korah, and Balaam have brought the world,
since the apostles`' days, to be like a sea.
And such as these, I saw, might deceive now, as they had in former ages:
but it is impossible for them to deceive the elect, who are chosen in Christ,
who was before the world began, and before the deceiver was;
though others may be deceived in their openings and prophecies,
not keeping their minds to the Lord Jesus Christ, who doth open and reveal to his.

I saw the state of those, both priests and people, who, in reading the Scriptures,
cry out much against Cain, Esau, and Judas, and other wicked men of former times,
mentioned in the Holy Scriptures; but do not see the nature of Cain, of Esau, of Judas,
and those others, in themselves.
These said, it was they, they, they, that were the bad people;
putting it off from themselves: but when some of these came,
with the light and Spirit of truth, to see into themselves, then they came to say, I, I,
I, it is I myself, that have been the Ishmael, and the Esau, etc.
For thou they came to see the nature of wild Ishmael in themselves; the nature of Cain,
of Esau, of Korah, of Balaam, and of the son of perdition in themselves,
sitting above all that is called God in them.
Thus I saw it was the fallen man that was got up into the Scriptures,
and was finding fault with those before mentioned; and, with the backsliding Jews,
calling them the sturdy oaks, and tall cedars, and fat bulls of Bashan, wild heifers,
vipers, serpents, etc.; and charging them that it was they that closed their eyes,
and stopped their ears, and hardened their hearts, and were dull of hearing:
that it was they that hated the light, and rebelled against it; that quenched the Spirit,
and vexed, and grieved it; that walked despitefully against the Spirit of grace,
and turned the grace of God into wantonness:
and that it was they that resisted the Holy Ghost, that got the form of godliness,
and turned against the power: and they were the inwardly ravening wolves,
that had got the sheep`'s clothing; they were the wells without water,
and clouds without rain, and trees without fruit, etc.
But when these, who were so much taken up with finding fault with others,
and thought themselves clear from these things, came to look into themselves, and,
with the light of Christ, thoroughly to search themselves,
they might see enough of this in themselves; and then the cry could not be, it is he,
or they, as before; but I, and we are found in these conditions.

I saw also, how people read the Scriptures without a right sense of them,
and without duly applying them to their own states.
For, when they read that death reigned from Adam to Moses;
that the law and the prophets were until John;
and that the least in the kingdom is greater than John;
they read these things and applied them to others,
but they did not turn in to find the truth of these things in themselves.
As these things came to be opened in me,
I saw death reigned over them from Adam to Moses; from the entrance into transgression,
till they came to the ministration of condemnation, which restrains people from sin,
that brings death.
Then, when the ministration of Moses is passed through,
the ministry of the prophets comes to be read and understood,
which reaches through the figures, types, and shadows unto John,
the greatest prophet born of a woman; whose ministration prepares the way of the Lord,
by bringing down the exalted mountains, and making straight paths.
And as this ministration is passed through,
an entrance comes to be known into the everlasting kingdom.
Thus I saw plainly that none could read Moses aright, without Moses`' spirit,
by which Moses saw how man was in the image of God in Paradise, and how he fell,
how death came over him, and how all men have been under this death.
I saw how Moses received the pure law, that went over all transgressors;
and how the clean beasts, which were figures and types, were offered up,
when the people were come into the righteous law that went over the first transgression.
Both Moses and the prophets saw through the types and figures, and beyond them,
and saw Christ, the great prophet, that was to come to fulfil them.
I saw that none could read John`'s words aright, and with a true understanding of them,
but in and with the same divine Spirit by which John spoke them; and by his burning,
shining light, which is sent from God.^
footnote:[Archbishop Seeker says,
"`Before any one can peruse the sacred Scriptures to profit,
the Lamb must open the seven seals.`"]
For by that Spirit their crooked natures might be made straight,
and their rough natures smooth,
and the exacter and violent doer in them might be cast out;
and they that had been hypocrites might come to bring forth fruits meet for repentance,
and their mountain of sin and earthliness might be laid low,
and their valley exalted in them,
that there might be a way prepared for the Lord in them:
then the least in the kingdom is greater than John.
But all must first know the voice crying in their wilderness, in their hearts, which,
through transgression, were become as a wilderness.
Thus I saw it was an easy matter to say death reigned from Adam to Moses;
and that the law and the prophets were until John;
and that the least in the kingdom is greater than John;
but none could know how death reigned from Adam to Moses, etc,
but by the same Holy Spirit that Moses, the prophets, and John were in.
They could not know the spiritual meaning of Moses'`, the prophets'`, and John`'s words,
nor see their path and travels, much less see through them,
and to the end of them into the kingdom, unless they had the Spirit and light of Jesus;
nor could they know the words of Christ and of his apostles, without his Spirit.
But as man comes through, by the Spirit and power of God, to Christ,
who fulfils the types, figures, shadows, promises, and prophecies that were of him,
and is led by the Holy Ghost into the truth and substance of the Scriptures,
sitting down in him who is the author and end of them; then are they read,
and understood, with profit and great delight.

Moreover, when I was brought up into his image in righteousness and holiness,
and into the paradise of God, He let me see how Adam was made a living soul:
and also the stature of Christ, the mystery that had been hid from ages and generations;
which things are hard to be uttered, and cannot be borne by many.
For, of all the sects in Christendom (so called) that I discoursed withal,
I found none that could bear to be told that any should come to Adam`'s perfection,
into that image of God, that righteousness and holiness that Adam was in before he fell;
to be clear and pure without sin, as he was.
Therefore,
how should they be able to bear being told that any should
grow up to the measure of the stature of the fulness of Christ,
when they cannot bear to hear that any should come, whilst upon earth,
into the same power and Spirit that the prophets and
apostles were in? Though it is a certain truth,
that none can understand their writings aright,
without the same Spirit by which they were written.

Now the Lord God opened to me by his invisible power,
"`that every man was enlightened by the divine light of Christ;`"
and I saw it shine through all;
and that they that believed in it came out of condemnation to the light of life,
and became the children of it; but they that hated it, and did not believe in it,
were condemned by it, though they made a profession of Christ.
This I saw in the pure openings of the light, without the help of any man;
neither did I then know where to find it in the Scriptures, though afterwards,
searching the Scriptures, I found it.
For I saw in that Light and Spirit which was before the Scriptures were given forth,
and which led the holy men of God to give them forth, that all must come to that Spirit,
if they would know God, or Christ, or the Scriptures aright,
which they that gave them forth were led and taught by.

But I observed a dulness and drowsy heaviness upon people, which I wondered at:
for sometimes, when I would set myself to sleep, my mind went over all to the beginning,
in that which is from everlasting to everlasting.
I saw death was to pass over this sleepy, heavy state;
and I told people they must come to witness death to that sleepy, heavy nature,
and a cross to it in the power of God,
that their minds and hearts might be on things above.

On a certain time, as I was walking in the fields, the Lord said unto me:
"`Thy name is written in the Lamb`'s book of life,
which was before the foundation of the world;`" and, as the Lord spoke it, I believed,
and saw it in the new birth.
Then, some time after, the Lord commanded me to go abroad into the world,
which was like a briery, thorny wilderness; and when I came, in the Lord`'s mighty power,
with the word of life into the world, the world swelled, and made a noise,
like the great raging waves of the sea.
Priests and professors, magistrates and people, were all like a sea,
when I came to proclaim the day of the Lord amongst them,
and to preach repentance to them.

I was sent to turn people from darkness to the light,
that they might receive Christ Jesus: for, to as many as should receive him in his light,
I saw that he would give power to become the sons of God;
which I had obtained by receiving Christ.
I was to direct people to the Spirit, that gave forth the Scriptures,
by which they might be led into all truth, and so up to Christ and God,
as they had been who gave them forth.
I was to turn them to the grace of God, and to the truth in the heart,
which came by Jesus; that by this grace they might be taught,
which would bring them salvation, that their hearts might be established by it,
and their words might be seasoned, and all might come to know their salvation nigh.
I saw that Christ died for all men, and was a propitiation for all;
and enlightened all men and women with his divine and saving light;
and that none could be a true believer, but who believed in it.
I saw that the grace of God, which bringeth salvation, had appeared to all men,
and that the manifestation of the Spirit of God was given to every man, to profit withal.
These things I did not see by the help of man, nor by the letter,
though they are written in the letter,
but I saw them in the light of the Lord Jesus Christ,
and by his immediate Spirit and power, as did the holy men of God,
by whom the Holy Scriptures were written.
Yet I had no slight esteem of the Holy Scriptures, but they were very precious to me,
for I was in that Spirit by which they were given forth: and what the Lord opened in me,
I afterwards found was agreeable to them.
I could speak much of these things, and many volumes might be written,
but all would prove too short to set forth the infinite love, wisdom, and power of God,
in preparing, fitting, and furnishing me for the service he had appointed me to;
letting me see the depths of Satan on the one hand, and opening to me, on the other hand,
the divine mysteries of his own everlasting kingdom.

Now, when the Lord God and his Son Jesus Christ sent me forth into the world,
to preach his everlasting gospel and kingdom,
I was glad that I was commanded to turn people to that inward light, Spirit, and grace,
by which all might know their salvation, and their way to God;
even that Divine Spirit which would lead them into all truth,
and which I infallibly knew would never deceive any.

But with and by this divine power and Spirit of God, and the light of Jesus,
I was to bring people off from all their own ways, to Christ, the new and living way;
and from their churches, which men had made and gathered, to the church in God,
the general assembly written in heaven, which Christ is the head of:
and off from the world`'s teachers, made by men, to learn of Christ, who is the way,
the truth, and the life, of whom the Father said, "`This is my beloved Sod,
hear ye Him;`" and off from all the world`'s worships,
to know the Spirit of Truth in the inward parts, and to be led thereby;
that in it they might worship the Father of spirits, who seeks such to worship him;
which Spirit they that worshipped not in, knew not what they worshipped.
And I was to bring people off from all the world`'s religions, which are vain;
that they might know the pure religion, might visit the fatherless, the widows,
and the strangers, and keep themselves from the spots of the world;
then there would not be so many beggars, the sight of whom often grieved my heart,
as it denoted so much hard-heartedness amongst them that professed the name of Christ.
I was to bring them off from all the world`'s fellowships, and prayings, and singings,
which stood in forms without power; that their fellowship might be in the Holy Ghost,
and in the Eternal Spirit of God; that they might pray in the Holy Ghost,
and sing in the Spirit, and with the grace that comes by Jesus;
making melody in their hearts to the Lord,
who hath sent his beloved Son to be their Saviour,
and caused his heavenly sun to shine upon all the world, and through them all,
and his heavenly rain to fall upon the just and
the unjust (as his outward rain doth fall,
and his outward sun doth shine on all), which is God`'s unspeakable love to the world.
I was to bring people off from Jewish ceremonies, and from heathenish fables,
and from men`'s inventions and worldly doctrines,
by which they blew the people about this way and the other way, from sect to sect;
and from all their beggarly rudiments,
with their schools and colleges for making ministers of Christ,
who are indeed ministers of their own making, but not of Christ`'s;
and from all their images and crosses, and sprinkling of infants,
with all their holy-days (so called) and all their vain traditions,
which they had instituted since the apostles`' days, which the Lord`'s power was against:
in the dread and authority of which, I was moved to declare against them all,
and against all that preached and not freely,
as being such as had not received freely from Christ.

Moreover, when the Lord sent me forth into the world,
he forbade me to "`put off my hat`" to any, high or low;
and I was required to Thee and Thou all men and women,
without any respect to rich or poor, great or small.
And as I travelled up and down, I was not to bid people Good morrow, or Good evening;
neither might I bow or scrape with my leg to any one;
and this made the sects and professions to rage.
But the Lord`'s power carried me over all to his glory,
and many came to be turned to God in a little time;
for the heavenly day of the Lord sprung from on high, and broke forth apace,
by the light of which many came to see where they were.

But O! the rage that then was in the priests, magistrates, professors,
and people of all sorts; but especially in priests and professors! for, though Thou,
to a single person, was according to their own learning, their accidence,
and grammar rules, and according to the Bible, yet they could not bear to hear it:
and as to the hat-honour, because I could not put off my hat to them,
it set them all into a rage.
But the Lord showed me that it was an honour below, which he would lay in the dust,
and stain;--an honour which proud flesh looked for,
but sought not the honour which came from God
only;--an honour invented by men in the fall,
and in the alienation from God, who were offended if it were not given them;
and yet they would be looked upon as saints, church-members, and great Christians:
but Christ saith, "`How can ye believe, who receive honour one of another,
and seek not the honour that cometh from God only?`" "`And I (saith
Christ) receive not honour of men:`" showing that men have an honour,
which men will receive and give; but Christ will have none of it.
This is the honour which Christ will not receive, and which must be laid in the dust.
O! the rage and scorn, the heat and fury that arose!
O! the blows, punchings, beatings, and imprisonments that we underwent,
for not putting off our hats to men! for that soon
tried all men`'s patience and sobriety what it was.
Some had their hats violently plucked off and thrown away, so that they quite lost them.
The bad language and evil usage we received on this account are hard to be expressed,
besides the danger we were sometimes in, of losing our lives for this matter,
and that by the great professors of Christianity,
who thereby evinced that they were not true believers.
And though it was but a small thing in the eye of man,
yet a wonderful confusion it brought among all professors and priests: but,
blessed be the Lord,
many came to see the vanity of that custom of putting off the hat to men,
and felt the weight of Truth`'s testimony against it.

About this time I was sorely exercised in going to their courts to cry for justice,
and in speaking and writing to judges and justices to do justly;
in warning such as kept public-houses for entertainment,
that they should not let people have more drink than would do them good;
and in testifying against their wakes or feasts, may-games, sports, plays, and shows,
which trained up people to vanity and looseness, and led them from the fear of God;
and the days they had set forth for holy-days were usually the
times wherein they most dishonoured God by these things.^
footnote:[By a royal proclamation of James I., issued in 1618 (for Lancashire),
these pastimes were made lawful recreations for the First-day of the week,
provided they did not interfere with the times appointed for worship.
Many of the clergy at first refused to promulgate the proclamation,
though by so doing they acted contrary to their canonical obedience,
and laid themselves open to penalties.
In the seventh year of Charles I., this proclamation,
at the instigation of Archbishop Laud, was revived, and extended to the whole nation,
and was enjoined to be published and advocated from the pulpit by all ministers,
to their disgrace.
By the revival of this offensive proclamation,
these disorderly revels had arrived to such a height of licentious depravity,
that some well-disposed justices, in the county of Somerset,
petitioned the judges on the western circuit, Sir Thomas Richardson, Lord Chief Justice,
and Baron Denham, to suppress them.
For so doing, they were summoned before the King and Council, by Archbishop Laud,
for illegally interfering with the ecclesiastical jurisdiction,
and the council rescinded the prohibitions,
and cashiered the judges.--(See Fuller`'s Church Hist. Book x. p. 74; and Book xi. p. 147.)]
In fairs, also, and in markets,
I was made to declare against their deceitful merchandise, cheating, and cozening;
warning all to deal justly, to speak the truth, to let their yea be yea,
and their nay be nay; and to do unto others as they would have others do unto them;
forewarning them of the great and terrible day of the Lord,
which would come upon them all.
I was moved also to cry against all sorts of music,
and against the mountebanks playing tricks on their stages,
for they burthened the pure life, and stirred up people`'s minds to vanity.
I was much exercised, too, with schoolmasters and school-mistresses,
warning them to teach their children sobriety in the fear of the Lord,
that they might not be nursed and trained up in lightness, vanity, and wantonness.
Likewise I was made to warn masters and mistresses,
fathers and mothers in private families,
to take care that their children and servants
might be trained up ha the fear of the Lord;
and that they themselves should be therein examples and
patterns of sobriety and virtue to them.
For I saw that as the Jews were to teach their
children the law of God and the old covenant,
and to train them up in it, and their servants, yea,
the very strangers were to keep the Sabbath amongst them, and be circumcised,
before they eat of their sacrifices; so all Christians,
and all that made a profession of Christianity,
ought to train up their children and servants in the new covenant of light, Christ Jesus,
who is God`'s salvation to the ends of the earth, that all may know their salvation:
and they ought to train them up in the law of life, the law of the Spirit,
the law of love and of faith; that they might be made free from the law of sin and death.
And all Christians ought to be circumcised by the Spirit,
which puts off the body of the sins of the flesh,
that they may come to eat of the heavenly sacrifice, Christ Jesus,
that true spiritual food,
which none can rightly feed upon but they that are circumcised by the Spirit.
Likewise, I was exercised about the star-gazers, who drew people`'s minds from Christ,
the bright and the morning-star; and from the Sun of righteousness, by whom the sun,
and moon, and stars, and all things else were made, who is the wisdom of God,
and from whom the right knowledge of all things is received.

But the earthly spirit of the priests wounded my life;
and when I heard the bell toll to call people together to the steeple-house,
it struck at my life; for it was just like a market-bell, to gather people together,
that the priest might set forth his ware to sale.
O! the vast sums of money that are gotten by the
trade they make of selling the Scriptures,
and by their preaching, from the highest bishop to the lowest priest!
What one trade else in the world is comparable to it?
notwithstanding the Scriptures were given forth freely,
and Christ commanded his ministers to preach freely,
and the prophets and apostles denounced judgment
against all covetous hirelings and diviners for money.
But in this free Spirit of the Lord Jesus was I sent forth to
declare the Word of life and reconciliation freely,
that all might come to Christ, who gives freely, and who renews up into the image of God,
which man and woman were in before they fell,
that they might sit down in heavenly places in Christ Jesus.
