== Chapter III.

[.chapter-synopsis]
* 1649–1650.
* George Fox is first imprisoned at Nottingham, where the sheriff is convinced
* he is liberated and quiets a distracted woman-many miracles were wrought in those days, beyond what that unbelieving age would receive or bear
* he is cruelly treated at Mansfield-Woodhouse
* is taken before the magistrates at Derby
* acknowledges that he is sanctified
* is temptingly asked if he were Christ, which he denies, yet is committed for blasphemy
* his mittimus to Derby prison
* writes to the priests of Derby against preaching for hire, etc.
* also against persecution
* to Barton and Bennet, justices, on the same subject-to Justice Bennet against covetousness
* to Justice Barton, a preacher and a persecutor
* to the mayor of Derby against persecution and oppression
* to the court of Derby against oaths and oppression
* to the bell-ringers of Derby against vanities and worldly pleasures
* his jailer is convinced-Justice Bennet first gives Friends the name of Quakers in derision
* writes to Friends and others, to open their understandings, and to direct them to their true Teacher within themselves
* to the convinced people, directing them to internal silence and to true obedience
* an encouragement to the faithful
* to the justices of Derby against persecution, thrice repeated
* to the priests of Derby, on the same subject
* to the justices of Derby, to prize their time, and to depart from evil
* the like to Colonel Barton, justice, and warning of the plagues and vengeance hanging over the oppressor.

Now as I went towards Nottingham on a First-day in the morning,
with Friends to a meeting there, when I came on the top of a hill in sight of the town,
I espied the great steeple-house; and the Lord said unto me,
"`thou must go cry against yonder great idol, and against the worshippers therein.`"
I said nothing of this to the Friends that were with me,
but went on with them to the meeting, where the mighty power of the Lord was amongst us;
in which I left Friends sitting in the meeting, and I went away to the steeple-house.
When I came there, all the people looked like fallow-ground,
and the priest (like a great lump of earth) stood in his pulpit above.
He took for his text these words of Peter, "`We have also a more sure Word of prophecy,
whereunto ye do well that ye take heed, as unto a light that shineth in a dark place,
until the day dawn, and the day-star arise in your hearts.`"
And he told the people that this was the Scriptures,
by which they were to try all doctrines, religions, and opinions.
Now the Lord`'s power was so mighty upon me, and so strong in me, that I could not hold,
but was made to cry out and say, "`O no,
it is not the Scriptures;`" and I told them what it was, namely, the Holy Spirit,
by which the holy men of God gave forth the Scriptures, whereby opinions, religions,
and judgments were to be tried; for it led into all truth,
and so gave the knowledge of all truth.
The Jews had the Scriptures, and yet resisted the Holy Ghost, and rejected Christ,
the bright morning-star.
They persecuted Christ and his apostles,
and took upon them to try their doctrines by the Scriptures, but erred in judgment,
and did not try them aright, because they tried without the Holy Ghost.
As I spoke thus amongst them, the officers came and took me away,
and put me into a nasty, stinking prison;
the smell whereof got so into my nose and throat, that it very much annoyed me.

But that day the Lord`'s power sounded so in their ears,
that they were amazed at the voice;
and could not get it out of their ears for some time after,
they were so reached by the Lord`'s power in the steeple-house.
At night they took me before the mayor, aldermen, and sheriffs of the town;
and when I was brought before them, the mayor was in a peevish, fretful temper,
but the Lord`'s power allayed him.
They examined me at large; and I told them how the Lord had moved me to come.
After some discourse between them and me, they sent me back to prison again;
but some time after the head sheriff, whose name was John Reckless,
sent for me to his house.
When I came in, his wife met me in the hall, and said, "`Salvation is come to our house.`"
She took me by the hand, and was much wrought upon by the power of the Lord God;
and her husband, and children, and servants were much changed,
for the power of the Lord wrought upon them.
I lodged at the sheriff`'s, and great meetings we had in his house.
Some persons of considerable condition in the world came to them,
and the Lord`'s power appeared eminently amongst them.
This sheriff sent for the other sheriff,
and for a woman they had had dealings with in the way of trade;
and he told her before the other sheriff,
that they had wronged her in their dealings with
her (for the other sheriff and he were partners),
and that they ought to make her restitution.
This he spoke cheerfully; but the other sheriff denied it;
and the woman said she knew nothing of it.
But the friendly sheriff said it was so, and that the other knew it well enough;
and having discovered the matter, and acknowledged the wrong done by them,
he made restitution to the woman, and exhorted the other sheriff to do the like.
The Lord`'s power was with this friendly sheriff, and wrought a mighty change in him,
and great openings he had.
The next market-day, as he was walking with me in the chamber, in his slippers, he said,
"`I must go into the market, and preach repentance to the people;`"
and accordingly he went into the market,
and into several streets, and preached repentance to the people.
Several others also in the town were moved to speak to the mayor and magistrates,
and to the people, exhorting them to repent.
Hereupon the magistrates grew very angry, and sent for me from the sheriff`'s house,
and committed me to the common prison.
When the assize came on, there was one moved to come and offer up himself for me,
body for body; yea, life also: but when I should have been brought before the judge,
the sheriff`'s man being somewhat long in fetching me to the sessions-house,
the judge was risen before I came.
At which I understood the judge was somewhat offended, and said,
"`he would have admonished the youth,
if he had been brought before him;`" for I was then imprisoned by the name of A Youth.
So I was returned to prison again, and put into the common jail.
The Lord`'s power was great among Friends; but the people began to be very rude;
wherefore the governor of the castle sent down soldiers, and dispersed them;
and after that they were quiet.
But both priests and people were astonished at the wonderful power that broke forth;
and several of the priests were made tender,
and some did confess to the power of the Lord.

Now, after I was released from Nottingham jail, where I had been kept prisoner some time,
I travelled as before, in the work of the Lord.
Coming to Mansfield-Woodhouse, there was a distracted woman under a doctor`'s hand,
with her hair loose all about her cars.
He was about to bleed her, she being first bound, and many people being about her,
holding her by violence; but he could get no blood from her.
I desired them to unbind her, and let her alone,
for they could not touch the spirit in her, by which she was tormented.
So they unbound her; and I was moved to speak to her,
and in the name of the Lord to bid her be quiet and still; and she was so.
The Lord`'s power settled her mind, and she mended; and afterwards she received the truth,
and continued in it to her death.
The Lord`'s name was honoured; to whom the glory of all his works belongs.
Many great and wonderful things were wrought by the heavenly power in those days;
for the Lord made bare his omnipotent arm,
and manifested his power to the astonishment of many,
by the healing virtue whereof many have been delivered from great infirmities,
and the devils were made subject through his name;
of which particular instances might be given,
beyond what this unbelieving age is able to receive or bear.
But blessed for ever be the name of the Lord, and everlastingly honoured,
and over all exalted and magnified be the arm of his glorious power,
by which he hath wrought gloriously;
let the honour and praise of all his works be ascribed to him alone.

Now while I was at Mansfield-Woodhouse, I was moved to go to the steeple-house there,
and declare the truth to the priest and people;
but the people fell upon me in great rage, struck me down,
and almost stifled and smothered me;
and I was cruelly beaten and bruised by them with their hands, Bibles, and sticks.
Then they haled me out, though I was hardly able to stand, and put me into the stocks,
where I sat some hours; and they brought dog-whips and horse-whips,
threatening to whip me.
After some time they had me before the magistrate, at a knight`'s house,
where were many great persons; who, seeing how evilly I had been used,
after much threatening, set me at liberty.
But the rude people stoned me out of the town, for preaching the word of life to them.
I was scarcely able to move or stand, by reason of the ill usage I had received;
yet with considerable effort I got about a mile from the town,
and then I met with some people who gave me something to comfort me,
because I was inwardly bruised; but the Lord`'s power soon healed me again.
That day some people were convinced of the Lord`'s truth, and turned to his teaching,
at which I rejoiced.

Then I went into Leicestershire, several Friends accompanying me.
There were some Baptists in that country whom.
I desired to see and speak with, because they were separated from the public worship.
So one Oates, who was one of their chief teachers, and others of the heads of them,
with several others of their company, came to meet us at Barrow;
and there we discoursed with them.
One of them said, "`What was not of faith was sin.`"
Whereupon I asked them,
What faith was? and how it was wrought in man? But they turned off from that,
and spoke of their baptism in water.
Then I asked them,
Whether their mountain of sin was brought down and laid low in them? and
their rough and crooked ways made smooth and straight in them? for they
looked upon the Scriptures as meaning outward mountains and ways.
But I told them they must find them in their own hearts; which they seemed to wonder at.
We asked them who baptized John the Baptist? and who baptized Peter, John,
and the rest of the apostles? and put them to prove by
Scripture that these were baptized in water;
but they were silent.
Then I asked them, "`Seeing Judas, who betrayed Christ,
and was called the Son of Perdition, had hanged himself,
what Son of Perdition was that which Paul spoke of, that sat in the temple of God,
exalted above all that is called God? and what temple of God
that was in which this Son of Perdition sat? and whether he,
that betrays Christ within in himself, be not one in nature with that Judas,
that betrayed Christ without?`" But they could not tell what to make of this,
nor what to say to it.
So after some discourse we parted; and some of them were loving to us.

On the First-day following we came to Bagworth, and went to a steeple-house,
where some Friends were got in; and the people locked them in, and themselves too,
with the priest.
But after the priest had done, they opened the door, and we went in also,
and had a service for the Lord amongst them.
Afterwards we had a meeting in the town, amongst several people that were in high notions.
Passing from thence, I heard of a people that were in prison in Coventry for religion.
And as I walked towards the jail, the word of the Lord came to me saying,
"`My Love Was Always To Thee, And Thou Art In My Love.`"
And I was ravished with the sense of the love of God,
and greatly strengthened in my inward man.
But when I came into the jail, where the prisoners were,
a great power of darkness struck at me, and I sat still,
having my spirit gathered into the love of God.
At last these prisoners began to rant, and vapour, and blaspheme,
at which my soul was greatly grieved.
They said they were God; but we could not bear such things.
When they were calm, I stood up and asked them, whether they did such things by motion,
or from Scripture; and they said, from Scripture.
A Bible being at hand, I asked them to point out that Scripture;
and they showed me the place where the sheet was let down to Peter,
and it was said to him, what was sanctified he should not call common or unclean.
When I had showed them that that Scripture proved nothing for their purpose,
they brought another, which spoke of God`'s reconciling all things to himself,
things in heaven, and things in earth.
I told them I owned that Scripture also,
but showed them that that was nothing to their purpose either.
Then seeing they said they were God, I asked them,
if they knew whether it would rain to-morrow? they said they could not tell.
I told them, God could tell.
Again, I asked them if they thought they should be always in that condition,
or should change? and they answered they could not tell.
Then said I unto them, God can tell, and God doth not change.
You say you are God; and yet you cannot tell whether you shall change or not.
So they were confounded, and quite brought clown for the time.
After I had reproved them for their blasphemous expressions, I went away;
for I perceived they were Banters.
I had met with none before;
and I admired the goodness of the Lord in
appearing so unto me before I went amongst them.
Not long after this, one of these Ranters, whose name was Joseph Salmon,
put forth a paper, or book of recantation; upon which they were set at liberty.

From Coventry I went to Atherstone; and it being their lecture-day,
I was moved to go to their chapel to speak to the priests and people.
They were generally pretty quiet; only some few raged,
and would have had my relations to have me bound.
I declared largely to them, how that God was come to teach his people himself,
and to bring them off from all their man-made teachers to hear his Son.
Some were convinced there.

Then I went to Market-Bosworth, and there was a lecture there also.
He that preached that day was Nathaniel Stevens,
who was priest of the town where I was born.
He raged much when I spoke to him and to the people, and told them I was mad.
He had said before, to one Colonel Purfoy,
that there was never such a plant bred in England; and he bid the people not to hear me.
So the people, being stirred up by this deceitful priest, fell upon us,
and stoned us out of the town; yet they did not do us much hurt.
Howbeit, some people were made loving that day, and others were confirmed,
seeing the rage of both priests and professors; and some cried out,
that the priest durst not stand to prove his ministry.

As I travelled through markets, fairs, and divers places,
I saw death and darkness in all people,
where the power of the Lord God had not shaken them.
As I was passing on in Leicestershire, I came to Twy-Cross, where there were excise-men.
I was moved of the Lord to go to them, and warn them to take heed of oppressing the poor;
and people were much affected with it.
There was in that town a great man, that had long lain sick,
and was given up by the physicians;
and some Friends in the town desired me to go to see him.
I went up to him in his chamber, and spoke the word of life to him,
and was moved to pray by him; and the Lord was entreated, and restored him to health.
But when I was come down stairs, into a lower room, and was speaking to the servants,
and to some people that were there, a serving-man of his came raving out of another room,
with a naked rapier in his hand, and set it just to my side.
I looked steadfastly on him, and said, "`Alack for thee,
poor creature! what wilt thou do with thy carnal weapon:
it is no more to me than a straw.`"
The standers-by were much troubled, and he went away in a rage, and full of wrath.
But when the news of it came to his master, he turned him out of his service.
Thus the Lord`'s power preserved me, and raised up the weak man,
who afterwards was very loving to Friends; and when I came to that town again,
both he and his wife came to see me.

After this I was moved to go into Derbyshire,
where the mighty power of God was among Friends.
And I went to Chesterfield), where one Britland was priest.
He saw beyond the common sort of priests, for he had been partly convinced,
and had spoken much on behalf of Truth, before he was priest there;
but when the priest of that town died, he got the parsonage, and choked himself with it.
I was moved to speak to him and the people in the great love of God,
that they might come off from all men`'s teaching unto God`'s teaching;
and he was not able to gainsay.
But they had me before the Mayor, and threatened to send me, with some others,
to the House of Correction; and kept us in custody till it was late in the night.
Then the officers, with the watchmen, put us out of the town,
leaving us to shift as we could.
So I bent my course towards Derby, having a friend or two with me.
In our way we met with many professors; and at Kidsey-Park many were convinced.

Then coming to Derby, I lay at a doctor`'s house, whose wife was convinced;
and so were several more in the town.
As I was walking in my chamber, the +++[+++steeple-house]
bell rung, and it struck at my life at the very hearing of it;
so I asked the woman of the house what the bell rung for? She
said there was to be a great lecture there that day,
and many of the officers of the army, and priests, and preachers were to be there,
and a colonel, that was a preacher.
Then was I moved of the Lord to go up to them;
and when they had done I spoke to them what the Lord commanded me,
and they were pretty quiet.
But there came an officer and took me by the hand,
and said I must go before the magistrates, and the other two that were with me.
It was about the first hour after noon that we came before them.
They asked me, Why we came thither; I said, God moved us so to do; and I told them,
"`God dwells not in temples made with hands.`"
I told them also, All their preaching, baptism, and sacrifices,
would never sanctify them; and bid them look unto Christ in them, and not unto men;
for it is Christ that sanctifies.
Then they ran into many words;
but I told them they were not to dispute of God and Christ, but to obey him.
The power of God thundered amongst them, and they flew like chaff before it.
They put me in and out of the room often, hurrying me backward and forward;
for they were from the first hour till the ninth at night in examining me.
Sometimes they would tell me, in a deriding manner, that I was taken up in raptures.
At last they asked me, Whether I was sanctified? I answered, Yes;
for I was in the paradise of God.
Then they asked me, If I had no sin? I answered, "`Christ, my Saviour,
has taken away my sin, and in him there is no sin.`"
They asked, How we knew that Christ did abide in us? I said, By his Spirit,
that he has given us.
They temptingly asked, If any of us were Christ? I answered,
Nay, we were nothing, Christ is all.
They said, If a man steal, is it no sin? I answered, All unrighteousness is sin.
So when they had wearied themselves in examining me,
they committed me and one other man to the House of Correction in Derby for six months,
as blasphemers; as appears by the following mittimus:--

[.salutation]
To the Master of the House of Correction in Derby, greeting.

We have sent you herewithal the bodies of George Fox, late of Mansfield,
in the county of Nottingham, and John Fretwell, late of Staniesby,
in the county of Derby, husbandman, brought before us this present day,
and charged with the avowed uttering and broaching of divers
blasphemous opinions contrary to a late act of Parliament,
which, upon their examination before us, they have confessed.
These are therefore to require you forthwith, upon sight hereof, to receive them,
the said George Fox and John Fretwell, into your custody,
and them therein safely to keep during the space of six months,
without bail or mainprize,
or until they shall find sufficient security to be of good behaviour,
or be thence delivered by order from ourselves.
Hereof you are not to fail.
Given under our hands and peals this 30th day of October, 1650.

[.signed-section-signature]
Ger. Bennet,

[.signed-section-signature]
Nath. Barton.

Now did the priests bestir themselves in their pulpits to preach up sin for term of life;
and much of their work was to plead for it; so that people said,
never was the like heard.
After some time, he that was committed with me, not standing faithful in his testimony,
got in with the jailer,
and by him made way to the justice to have leave to go to see his mother;
and so got his liberty.
It was then reported, that he said I had bewitched and deceived him;
but my spirit was strengthened when he was gone.
The priests and professors, the justices and the jailer,
were all in a great rage against me.
The jailer watched my words and actions, and would often ask me questions to ensnare me;
and sometimes asked me such silly questions as, Whether the door was latched,
or not? thinking to draw some sudden, unadvised answer from me,
whence he might take advantage to charge sin upon me; but I was kept watchful and chaste,
so that they could get no advantage of me, which they wondered at.

[.offset]
Not long after my commitment,
I was moved to write both to the priests and magistrates of Derby.
And first to the priests.

O friends, I was sent unto you to tell you, that if you had received the gospel freely,
you would minister it freely without money or price:
but you make a trade and sale of what the prophets and the apostles have spoken;
and so you corrupt the truth.
And you are the men that lead silly women captive, who are ever learning,
and never able to come to the knowledge of the truth; you have a form of godliness,
but you deny the power.
Now as Jannes and Jambres withstood Moses, so do you resist the truth,
being men of corrupt minds, reprobate concerning the faith.
But you shall proceed no further;
for your folly shall be made manifest to all men as theirs was.
Moreover, the Lord sent me to tell you, that he doth look for fruits.
You asked me, If Scripture was my rule? but it is not your rule, to rule your lives by,
but to talk of in words.
You are the men that live in pleasures, pride, and wantonness, in fulness of bread,
and abundance of idleness: see if this be not the sin of Sodom.
Lot received the angels, but Sodom was envious.
You show forth the vain nature; you stand in the steps of them that crucified My Saviour,
and mocked him; you are their children; you show forth their fruit.
They had the chief place in the assemblies, and so have you;
they loved to be called Rabbi, and so do you.

[.signed-section-signature]
G+++.+++ F.

I wrote to the magistrates who committed me to this effect:--

[.salutation]
Friends,

I am forced, in tender love unto your souls, to write unto you,
and to beseech you to consider what you do, and what the commands of God call for.
He requires justice and mercy, to break every yoke, and to let the oppressed go free.
But who calleth for justice, or loveth mercy,
or contendeth for the truth? Is not judgment turned backward,
and doth not justice stand afar off? Is not truth silenced in the streets,
or can equity enter? And do not they that depart from evil
make themselves a prey? Oh! consider what ye do in time,
and take heed whom ye imprison;
for the magistrate is set for the punishment of evil-doers,
and for the praise of them that do well.
Now, I entreat you, in time take heed what you do; for surely the Lord will come,
and will make manifest both the builders and the work.
If it be of man, it will fail; but if it be of God, nothing will overthrow it.
Therefore I desire and pray, that you would take heed, and beware what you do,
lest ye be found fighters against God.

[.signed-section-signature]
G+++.+++ F.

Now, after I had thus far cleared my conscience to them, I waited in holy patience,
leaving the event to God, in whose will I stood.
After some time I was moved to write again to the justices that had committed me,
to lay their evils before them, that they might repent.
One of them, Nathaniel Barton, was a colonel, a justice, and a preacher.

[.salutation]
Friends,

You spoke of the good old way which the prophet spoke of;
but-the prophet cried against the abominations which you hold up.
Had you the power of God, ye would not persecute the good way.
He that spoke of the good way was set in the stocks.
The people cried, '`Away with him to the stocks,`' for speaking the truth.
Ah! foolish people, who have eyes and see not, ears and hear not,
without understanding!`' Fear ye not me,`' saith the Lord,
'`and will ye not tremble at my presence?`' O your pride
and abominations are odious in the eyes of God!
You that are preachers have the chief place in the assemblies,
and are called of men, Master.
Such were and are against my Saviour and Maker:
they shut up the kingdom of heaven from men, and neither go in themselves,
nor suffer others.
Therefore ye shall receive the greater damnation, who have their places,
and walk in their steps.
You may say, if you had been in the days of the prophets, or Christ,
you would not have persecuted them; wherefore be ye witnesses against yourselves,
that ye are the children of them, seeing ye now persecute the way of truth.
O consider, there is a true judge,
that will give every one of you a reward according to your works.
O mind where you are,
you that hold up the abominations which the true prophet cried against!
O come down, and sit in the dust!
The Lord is coming with power, and he will throw down every one that is lifted up,
that he alone may be exalted.

[.offset]
As I had thus written unto them jointly, so, after some time,
I wrote to each of them by himself.
To Justice Bennet thus:--

[.salutation]
Friend,

Thou that dost profess God and Christ in words, see how thou followest him.
To take off burthens, to visit them that are in prison, to show mercy,
clothe thy own flesh, and deal thy bread to the hungry; these are God`'s commandments.
To relieve the fatherless, and to visit the widows in their afflictions,
and to keep thyself unspotted of the world; this is pure religion before God.
But if thou dost profess Christ, and follow covetousness, and greediness,
and earthly-mindedness, thou deniest him in life, and deceivest thyself and others,
and takest him for a cloak.
Woe be to you, greedy and rich men; weep and howl, for your misery that shall come.
Take heed of covetousness and extortion; God doth forbid that.
Woe be to the man that coveteth an evil covetousness, that he may set his nest on high,
and cover himself with thick clay.
O! do not love that which God forbids.
His servant thou art, whom thou dost obey, whether it be of sin unto death,
or of obedience unto righteousness.
Think of Lazarus and Dives; the one fared sumptuously every day, the other was a beggar.
See if thou be not Dives: be not deceived, God is not mocked with vain words;
evil communication corrupteth good manners; awake to righteousness, and sin not.

[.signed-section-signature]
G+++.+++ F.

That to Justice Barton was in these words:--

[.salutation]
Friend,

Thou that preachest Christ, and the Scriptures in words,
when any come to follow that which thou hast spoken of,
and to live the life of the Scriptures, then they that speak the Scriptures,
but do not lead their lives according thereunto, persecute them that do.
Mind the prophets, and Jesus Christ, and his apostles, and all the holy men of God;
what they spoke was from the life; but they that had not the life, but the words,
persecuted and imprisoned them that lived in the life,
which those had backslidden from.

[.signed-section-signature]
G+++.+++ F.

Having written to the justices and to the priests,
it was upon me to write to the Mayor of Derby also; who,
though he did not sign the mittimus, had a hand with the rest in sending me to prison.
To him I wrote after this manner:--

[.salutation]
Friend,

Thou art set in place to do justice; but, in imprisoning my body,
thou hast done contrary to justice, according to your own law.
O take heed of pleasing men more than God,
for that is the way of the Scribes and Pharisees;
they sought the praise of men more than God.
Remember who said, '`I was a stranger, and ye took me not in; I was in prison,
and ye visited me not.`' O friend, thy envy is not against me,
but against the power of truth.
I had no envy to you, but love.
O take heed of oppression, '`for the day of the Lord is coming,
that shall burn as an oven; and all the proud, and all that do wickedly,
shall be as stubble; and the day that cometh, shall burn them up,
saith the Lord of Hosts; it shall leave them neither root nor branch.`' O friend,
if the love of God were in thee, thou wouldst love the truth, hear the truth spoken,
and not imprison unjustly.
The love of God beareth, and suffereth, and envieth no man.
If the love of God had broken your hearts, you would show mercy;
but you show forth what ruleth you.
Every tree doth show forth its fruit; you do show forth your fruits openly.
For drunkenness, swearing, pride, and vanity, rule among you,
from the teacher to the people.
O friend, mercy, and true judgment, and justice, are cried for in your streets!
Oppression, unmercifulness, cruelty, hatred, pride, pleasures, wantonness, and fulness,
are in your streets; but the poor are not regarded.
O! take heed: '`Woe be to the crown of pride!
Woe be to them that drink wine in bowls, and the poor is ready to perish.
O! remember Lazarus and Dives!
One fared deliciously every day, and the other was a beggar.
O friend, mind these things, for they are near;
and see whether thou be not in Dives state.

[.offset]
I wrote also to the court at Derby thus:--

"`I am moved to write unto you, to take heed of oppressing the poor in your courts,
or laying burthens upon poor people, which they cannot bear; and of imposing false oaths,
or making them to take oaths which they cannot perform.
The Lord saith, '`I will come near to judgment,
and will be a swift witness against the sorcerers, against the false swearers,
and against the idolaters,
and against those that oppress widows and fatherless.`'
Therefore take heed of all these things betimes.
The Lord`'s judgments are all true and righteous; and he delighteth in mercy.
So love mercy, dear people, and consider in time.`"

[.offset]
Likewise to the ringers of the bells in the steeple-house, called St. Peter`'s, in Derby,
I sent these few lines:--

[.salutation]
Friends,

Take heed of pleasures, and prize your time now, while you have it,
and do not spend it in pleasures, or earthliness.
The time may come, that you will say you had time, when it is past.
Therefore look at the love of God now, while you have time;
for it bringeth to loathe all vanities and worldly pleasures.
O consider! Time is precious.
Fear God, and rejoice in him, who hath made heaven and earth.

[.asterism]
'''

While I was in prison, divers professors came to discourse with me; and I had a sense,
before they spoke, that they came to plead for sin and imperfection.
I asked them, Whether they were believers, and had faith? and they said, Yes.
I asked them, In whom? and they said, In Christ.
I replied, If ye are true believers in Christ, you are passed from death to life;
and if passed from death, then from sin that bringeth death.
And if your faith be true, it will give you victory over sin and the devil,
purify your hearts and consciences (for the true faith is held in a pure conscience),
and bring you to please God, and give you access to him again.
But they could not endure to hear of purity, and of victory over sin and the devil;
for they said they could not believe that any
could be free from sin on this side the grave.
I bid them give over babbling about the Scriptures, which were holy men`'s words,
whilst they pleaded for unholiness.
At another time a company of professors came, and they also began to plead for sin.
I asked them, Whether they had hope? and they said, Yes:
God forbid but we should have hope.
I asked them, What hope is it that you have?
Is Christ in you the hope of your glory?
Doth it purify you, as he is pure?
But they could not abide to hear of being made pure here.
Then I bid them forbear talking of the Scriptures, which were holy men`'s words.
For the holy men, that wrote the Scriptures, pleaded for holiness in heart, life,
and conversation here; but since you plead for impurity and sin, which is of the devil,
what have you to do with the holy men`'s words?

Now the keeper of the prison, being a high professor, was greatly enraged against me,
and spoke very wickedly of me: but it pleased the Lord one day to strike him so,
that he was in great trouble and under great terror of mind.
As I was walking in my chamber I heard a doleful noise; and standing still,
I heard him say to his wife, "`Wife, I have seen the day of judgment,
and I saw George there, and I was afraid of him, because I had done him so much wrong,
and spoken so much against him to the ministers and professors, and to the justices,
and in taverns and ale-houses.`"
After this, towards the evening, he came up into my chamber, and said to me,
"`I have been as a lion against you; but now I come like a lamb,
and like the jailer that came to Paul and Silas trembling.`"
And he desired that he might lodge with me; I told him that I was in his power,
he might do what he would: but he said nay, he would have my leave,
and he could desire to be always with me, but not to have me as a prisoner;
and he said "`he had been plagued, and his house had been plagued for my sake.`"
So I suffered him to lodge with me; and then he told me all his heart,
and said he believed what I had said of the true faith and hope to be true;
and he wondered that the other man that was put into prison with me did not stand to it;
and said, "`That man was not right, but I was an honest man.`"
He confessed also to me,
that at times when I had asked him to let me go forth
to speak the word of the Lord to the people,
and he had refused to let me, and I had laid the weight thereof upon him,
that he used to be under great trouble, amazed,
and almost distracted for some time after;
and in such a condition that he had little strength left him.
When the morning came, he rose, and went to the justices, and told them,
"`that he and his house had been plagued for my sake:`"
and one of the justices replied (as he reported to me),
that the plagues were on them too for keeping me.
This was Justice Bennet of Derby, who was the first that called us Quakers,
because I bid them tremble at the word of the Lord.
This was in the year 1650.^
footnote:[The designation "`Quakers,`" which was at first applied in scorn,
has ever since been used by the world to distinguish
Friends from other professors of religion.
The first use of the term in the records of Parliament,
occurs in the journals of the House of Commons in 1654.]

After this the justices gave leave that I should have liberty to walk a mile.
I perceived their end, and told the jailer if they would show me how far a mile was,
I might walk it sometimes; for I believed they thought I would go away.
And the jailer confessed afterwards, that they did it with that intent,
to have me escape, to ease them of their plague; but I told him I was not of that spirit.

This jailer had a sister, a sickly young woman.
She came up into my chamber to visit me; and after she had stayed some time,
and I had spoken the words of truth to her, she went down,
and told them that we were an innocent people, and did none any hurt,
but did good to all,
even to them that hated us and she desired them to use kindness towards me.

[.offset]
As my restraint prevented my travelling about,
to declare and spread truth through the country, it came upon me to write a paper,
and send it forth to be spread abroad both amongst Friends and other tender people,
for the opening of their understandings in the way of truth,
and directing them to the true teacher in themselves.
It was as follows:--

"`The Lord doth show unto man his thoughts,
and discovereth all the secret workings in man.
A man may be brought to see his evil thoughts, running mind, and vain imaginations,
and may strive to keep them down, and to keep his mind in; but he cannot overcome them,
nor keep his mind within, to the Lord.
In this state and condition submit to the Spirit of the Lord, which will discover them,
and will bring to wait upon Him, and destroy them.
Therefore stand in the faith of the Lord Jesus Christ,
who is the author of the true faith, and mind Him;
for he will discover the root of lusts, evil thoughts, and vain imaginations,
and how they are begotten, conceived, and bred; then how they are brought forth,
and how every evil member doth work.
He will discover every principle from its own nature and root.

"`So mind the faith of Christ, and the anointing which is in you, to be taught by it,
which will discover all workings in you; and as he teacheth you, so obey and forsake;
else you will not grow up in the faith, nor in the life of Christ,
where the love of God is received.
Now love begetteth love, its own nature and image: and when mercy and truth meet,
what joy there is!
Mercy triumphs in judgment; and love and mercy bear the judgment,
of the world in patience.
That which cannot bear the world`'s judgment is not the love of God;
for love beareth all things, and is above the world`'s judgment;
for the world`'s judgment is but foolishness.
Though it is the world`'s judgment and practice to cast all the
world`'s filthiness that is among themselves upon the saints,
yet their judgment is false.
Now the chaste virgins follow Christ, the Lamb that takes away the sins of the world;
but they that are of that spirit which is not chaste,
will not follow Christ the Lamb in his steps, but are disobedient to him in his commands.
So the fleshly mind doth mind the flesh, and talketh of the flesh;
its knowledge is fleshly and not spiritual;
and savours of death and not of the Spirit of life.
Some men have the nature of swine wallowing in the mire.
Some the nature of dogs to bite both the sheep and one another.
Some of lions, to tear, devour, and destroy.
Some of wolves, to tear and devour the lambs and sheep of Christ;
and some men have the nature of the serpent (that old adversary),
to sting, envenom, and poison.
'`He that hath an ear to hear, let him hear,`' and learn these things within himself.
Some men have the natures of other beasts and creatures,
minding nothing but earthly and visible things, and feeding without the fear of God.
Some have the nature of a horse, to prance and vapour in their strength,
and to be swift in doing evil; and some have the nature of tall, sturdy oaks,
to flourish, and spread in wisdom and strength; who are strong in evil,
which must perish and come to the fire.
Thus the evil is but one in all, but worketh many ways;
and whatsoever a man`'s or woman`'s nature is addicted to, that is outward,
the evil one will fit him with that,
and will please his nature and appetite to keep his mind in his inventions,
and in the creatures from the Creator.
O! therefore, let not the mind go forth from God; for if it do, it will be stained,
venomed, and corrupted.
If the mind go forth from the Lord it is hard to bring it in again;
therefore take heed of the enemy, and keep in the faith of Christ.
O! therefore mind that which is eternal and invisible,
and Him who is the Creator and Mover of all things;
for the things that are made are not made of things that do appear;
for the visible covereth the invisible sight in you.
But as the Lord, who is invisible, opens you by his invisible Power and Spirit,
and brings down the carnal mind in you,
so the invisible and immortal things are brought to light in you.
O! therefore you, that know the light,
walk in the light! for there are children of darkness,
that will talk of the light and of the truth, and not walk in it.
The children of the light love the light, and walk in the light;
but the children of darkness walk in darkness, and hate the light;
and in these the earthly lust, and the carnal mind choke the seed of faith;
and this bringeth oppression on the seed and death over themselves.
O! therefore, mind the pure Spirit of the everlasting God,
which will teach you to use the creatures in their right place,
and which judgeth the evil.
'`To thee, O God, be all glory and honour, who art Lord of all, visible and invisible!
To thee be all praise, who bringest out of the deep, to thyself; O powerful God,
who art worthy of all glory!`' For the Lord, who created all,
and gives life and strength to all, is over all, and merciful to all.
'`So thou, who hast made all, and art over all, to thee be all glory!
In thee is my strength, my refreshment, and life, my joy and my gladness,
my rejoicing and glorying for evermore!^
footnote:[How vain are bonds and imprisonments, or any other human infliction,
to the soul thus magnifying the Lord in a strain of thanksgiving, affectingly fervent.
To the soul that can thus rejoice in God, its Saviour, there is but one language,
"`It is well!`" 2 Kings 4:26.]
To live and walk in the Spirit of God is joy, and peace, and life;
but the mind going forth into the creatures, or into any visible things from the Lord,
this bringeth death.
Now when the mind is got into the flesh, and into death, the accuser gets within,
and the law of sin and death gets into the flesh.
Then the life suffers under the law of sin and death;
and then there is straitness and failings.
For then the good is shut up, and the self-righteousness is exalted.
Then man doth work in the outward law, though he cannot justify himself by the law,
but is condemned by the light; for he cannot get out of that state,
but by abiding in the light, resting in the mercy of God and believing in him,
from whom all mercy flows.
For there is peace in resting in the Lord Jesus.
This is the narrow way that leads to him, the life; but few will abide in it;
keep therefore in the innocency, and be obedient to the faith in him;
and take heed of conforming to the world, and of reasoning with flesh and blood,
for that bringeth disobedience;
and then imaginations and questionings arise to
draw from obedience to the truth of Christ.
But the obedience of faith destroyeth imaginations, and questionings,
and all the temptations in the flesh, and buffetings, and lookings forth,
and fetching up things that are past.
By not keeping in the life and light,
and not crossing the corrupt will by the power of God, the evil nature grows up in man,
and then burdens will come, and man will be stained with that nature.
But Esau`'s mountain shall be laid waste, and become a wilderness, where the dragons lie:
but Jacob, the second birth, shall be fruitful, and shall arise.
For Esau is hated, and must not be lord: but Jacob, the second birth,
which is perfect and plain, shall be lord; for he is beloved of God.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
I wrote another paper about the same time,
and sent it forth amongst the convinced people as follows:

"`The Lord Is King over all the earth!
Therefore, all people, praise and glorify your King in true obedience, in uprightness,
and in the beauty of holiness.
O! consider, in true obedience, the Lord is known,
and au understanding from him is received.
Mark and consider in silence, in lowliness of mind,
and thou wilt hear the Lord speak unto thee in thy mind.
His voice is sweet and pleasant; his sheep hear his voice,
and they will not hearken to another.
When they hear his voice, they rejoice and are obedient; they also sing for joy.
O, their hearts are filled with everlasting triumph!
They sing, and praise the eternal God in Zion; their joy man shall never take from them.
Glory to the Lord God for evermore!`"

[.offset]
But many that had been convinced of the truth, turned aside,
because of the persecution that arose;
whereupon I wrote a few lines for the comfort and encouragement of the faithful, thus:--

"`Come, ye blessed of the Lord,
and rejoice together! keep in unity and oneness of spirit;
triumph above the world! be joyful in the Lord, reigning above the world,
and above all things that draw from the Lord; that in clearness, righteousness, pureness,
and joy, you may be preserved to the Lord.
O hear! O hearken to the call of the Lord!
Come out of the world, and keep out of it for evermore!
Come, sing together, ye righteous ones, the song of the Lord, the song of the Lamb;
which none can learn, but they who are redeemed from the earth, and from the world.`"

[.asterism]
'''

While I was in the House of Correction, my relations came to see me:
and being troubled for my imprisonment,
they went to the justices that cast me into prison,
and desired to have me home with them; offering to be bound in one hundred pounds,
and others of Derby with them in fifty pounds each,
that I should come no more thither to declare against the priests.
So I was had up before the justices; and because I would not consent, that they,
or any should be bound for me (for I was innocent from any ill behaviour,
and had spoken the word of life and truth unto them), Justice Bennet rose up in a rage;
and as I was kneeling down to pray to the Lord to forgive him, he ran upon me,
and struck me with both his hands, crying,
"`Away with him, jailer, take him away, jailer.`"
Whereupon I was had again to prison, and there kept,
until the time of my commitment for six months was expired.
But I had now the liberty of walking a mile by myself, which I made use of,
as I felt freedom.
Sometimes I went into the market, and streets,
and warned the people to repent of their wickedness; and so returned to prison again.
And there being`' persons of several sorts of religion in the prison,
I sometimes went and visited them in their meetings on first-days.

[.offset]
After I had been before the justices,
and they had required sureties for my good behaviour
(which I could not consent should be given, to blemish my innocency),
it came upon me to write to tho justices again;
which I did as follows:--

[.salutation]
"`Friends,

"`See what it is in you that doth imprison; see, who is head in you; and see,
if something do not accuse you? Consider, you must be brought to judgment.
Think of Lazarus and Dives; the one fared sumptuously every day, the other was a beggar.
Now you have time, prize it, while you have it.
Would you have me to be bound to my good behaviour? I am bound to my good behaviour;
and cry for good behaviour of all people, to turn from the vanities and pleasures,
the oppression and deceits, of this world;
and there will come a time that you shall know it.
Therefore take heed of pleasures, and deceits, and pride; and look not at man,
but at the Lord; for '`Look unto me, all ye ends of the earth, and be ye saved,
saith the Lord.`'`"

[.offset]
Some little time after I wrote to them again:--

[.salutation]
"`Friends,

"`Would you have me to be bound to my good behaviour from drunkenness, or swearing,
or fighting, or adultery, and the like? The Lord hath redeemed me from all these things;
and the love of God hath brought me to loathe all wantonness, blessed be his name!
Drunkards, and fighters, and swearers, have their liberty without bonds;
and you lay your law upon me, whom neither you,
nor any other can justly accuse of these things; praised be the Lord!
I can look to no man for my liberty, but to the Lord alone,
who hath all men`'s hearts in his hand.`"

[.offset]
And after some time, not finding my spirit clear of them, I wrote to them again,
as follows:--

[.salutation]
"`Friends,

"`Had you known who sent me to you, ye would have received me;
for the Lord sent me to warn you of the woes that are coming upon you;
and to bid you look at the Lord, and not at man.
But when I told you my experience, what the Lord had done for me,
then your hearts were hardened, and you sent me to prison,
where you have kept me many weeks.
If the love of God had broken your hearts, then would ye see what ye have done;
ye would not have imprisoned me, had not my Father suffered you;
and by his power I shall be loosed; for he openeth and shutteth; to him be all glory!
In what have I misbehaved myself,
that any should be bound for me? All men`'s words will do me no good,
nor their bonds either, to keep my heart, if I had not a guide within,
to keep me in the upright life to God.
But I believe in the Lord, that through his strength and power,
I shall be preserved from ungodliness and worldly lusts.
The Scripture saith, '`receive strangers,`' but you imprison such.
As you are in authority, take heed of oppression and oaths, of injustice,
and gifts or rewards, for God doth loathe all such.
But love mercy, and true judgment, and justice, for that the Lord delights in.
I do not write with hatred to you; but to keep my conscience clear;
take heed how you spend your time.`"

[.offset]
I was moved also to write again to the priests of Derby:--

[.salutation]
"`Friends,

"`You profess to be the ministers of Jesus Christ in words,
but you show by your fruits what your ministry is.
Every tree shows its fruit; the ministry of Jesus Christ is in mercy and love,
to loose them that are bound, to bring out of bondage,
and to let them that are in captivity go free.
Where is your example, if the Scriptures be your rule,
to imprison for religion? Have you any command for it from Christ? If that were in you,
which you profess, you would walk in their steps, who wrote the Scriptures,
'`But he is not a Jew who is one outwardly, whose praise is of men;
but he is a Jew who is one inwardly,
whose praise is of God.`' But if you build upon the prophets and apostles in words,
and pervert their life, remember the woes which Jesus Christ spoke against such.
They that spoke the prophets`' words, but denied Christ, they professed a Christ to come;
but had they known him they would not have crucified him.
The saints, whom the love of God did change,
were brought thereby to walk in love and mercy; for he that dwelleth in love,
dwelleth in God.
But where envy, pride, and hatred rule, the nature of the world rules,
and not the nature of Jesus Christ.
I write with no hatred to you; but that you may weigh yourselves,
and see how you pass your time.`"

[.offset]
Thus having cleared my conscience to the priests,
it was not long before a concern came upon me to write again to the justices,
which I did as follows:--

"`I am moved to warn you to take heed of giving way to your own wills.
Love the cross; and satisfy not your own minds in the flesh; but prize your time,
while you have it, and walk up to that you know, in obedience to God;
then you shall not be condemned for that you know not; but for that you do know,
and do not obey.
Consider betimes, weigh yourselves, and see where you are, and whom you serve.
For if ye blaspheme God, and take his name in vain; if ye swear and lie;
if ye give way to envy and hatred, to covetousness and greediness,
to pleasures and wantonness, or any other vices,
be assured that ye do serve the Devil But if ye fear the Lord, and serve him,
ye will loathe all these things.
He that loveth God, will not blaspheme his name; but where there is opposing God,
and serving the Devil, that profession is sad and miserable.
O prize your time, and do not love that which God forbids; lying, wrath, malice, envy,
hatred, greediness, covetousness, oppression, gluttony, drunkenness, whoredom,
and all unrighteousness God doth forbid.
So consider, and be not deceived;
'`Evil communication corrupts good manners.`' Be not deceived,
God will not be mocked with vain words;
the wrath of God is revealed from heaven against all ungodliness.
Therefore obey that which convinces you of all evil,
and tells you that you should do no evil; it will lead you to repentance,
and keep you in the fear of the Lord.
O look at the mercies of God, and prize them, and do not turn them into wantonness.
O eye the Lord, and not earthly things!`"

[.offset]
Besides this, I wrote the following to Colonel Barton,
who was both a justice and a preacher, as was hinted before:--

[.salutation]
"`Friend,

"`Do not cloak and cover thyself; there is a God, who knoweth thy heart,
and will uncover thee; he seeth thy way.
'`Woe be to him that covereth, and not with my Spirit,`' saith the Lord.
Dost thou do contrary to the law,
and then put it from thee? Mercy and true judgment thou neglectest;
look what was spoken against such.
My Saviour said to such, '`I was sick and in prison, and ye visited me not; I was hungry,
and ye fed me not; I was a stranger, and ye took me not in.`' And when they said,
'`When saw we thee in prison, and did not come to thee,`' etc, he replied,
'`Inasmuch as ye did it not to one of these little ones,
ye did it not to me.`' Thou hast imprisoned me for
bearing witness to the life and power of truth,
and yet thou professest to be a minister of Christ; but if Christ had sent thee,
thou wouldst bring out of prison, and out of bondage, and wouldst receive strangers.
Thou hast been wanton upon earth, thou hast lived plenteously, and nourished thy heart,
as in a day of slaughter; thou hast killed the Just.
O look where thou art, and how thou hast spent thy time!
O remember thyself, and now, whilst thou hast time, prize it.
Do not slight the free mercy, or despise the long-suffering of God,
which is great salvation; but mind that in thee which doth convince,
and would not let thee swear, nor lie, nor take God`'s name in vain.
Thou knowest thou shouldst do none of these things;
thou hast learned that which will condemn thee; therefore obey the light,
which doth convince thee, forsake thy sins, and look at the mercies of God;
and prize his love in sparing thee till now.
The Lord saith, '`Look unto me, all ye ends of the earth, and be ye saved; cease from man,
whose breath is in his nostrils.`' Prize thy time, and see whom thou servest;
for his servant thou art whom thou dost obey, whether of sin unto death,
or of obedience unto righteousness.
If thou serve God, and fear him, thou wilt not blaspheme his name, or curse, or swear,
or take his name in vain, or follow pleasures and wantonness, whoredom, and drunkenness,
or wrath, or malice, or revenge, or rashness, or headiness, pride or gluttony,
greediness, oppression, or covetousness, or foolish jestings, or vain songs.
God doth forbid these things, and all unrighteousness.
If thou profess God, and act any of these things, thou takest him for a cloak,
and servest the Devil.
Consider with thyself, and do not love that which God hateth.
He that loveth God, keepeth his commandments.
The Devil will tell thee, it is a hard thing to keep God`'s commandments;
but it is an easy thing to keep the Devil`'s commandments,
and to live in all unrighteousness and ungodliness,
turning the grace of God into wantonness.
But let the unrighteous man forsake his ways, and turn unto me, saith the Lord,
and I will have mercy.
'`Turn ye, why will ye die? saith the Lord.`'

"`Howl, ye great ones, for the plagues are pouring out upon you!
Howl, ye oppressors, for recompense and vengeance is coming upon you!
Woe unto them that covetously join one house to another;
and bring one field so nigh unto another that the poor can get no more ground,
and that ye may dwell upon the earth alone;
these things are in the ears of the Lord of Hosts.
Woe unto him that covetously getteth evil-gotten goods into his house,
that he may set his nest on high, to escape from the power of evil.`"
