== Chapter IV.

[.chapter-synopsis]
* 1650-1651.
* A trooper visits George Fox from an inward intimation
* declines a commission in the army, and is put in the dungeon
* confutes one who denied Christ`'s outward appearance, from whence a slander is raised against Friends
* testifies against capital punishments for small matters
* writes for more speedy justice to prisoners
* intercedes for the life of a young woman, imprisoned for stealing, who is brought to the gallows but reprieved, and afterwards convinced
* again refuses to bear arms, and is committed close prisoner
* writes to Barton and Bennet, justices, against persecution
* addresses the convinced and tender people against hirelings
* to the magistrates of Derby against persecution, and foretelling his own enlargement and their recompense
* is greatly exercised for the wickedness of Derby
* sees the visitation of God`'s love pass away from the town, and writes a lamentation over it
* a great judgment fell upon the town
* he is liberated after a year`'s imprisonment
* visits Lichfield
* preaches repentance through Doncaster
* many dread "`the man with leather breeches`"
* goes to steeple-houses, as the apostles did to the temples, to bring people off from them
* is denied entertainment, and ill-treated at some places
* refuses to inform against his persecutors
* many are convinced in Yorkshire, amongst others, Richard Karnsworth, James Nayler, William Dewsbury, Justice Hotham, and Captain Pursloe.

While I was yet in the House of Correction, there came unto me it trooper, and said,
as he was sitting in the steeple-house, hearing the priest,
exceeding great trouble came upon him; and the voice of the Lord came to him saying,
"`Dost thou not know that my servant is in prison? Go to him for direction.`"
So I spoke to his condition, and his understanding was opened.
I told him, that which showed him his sins, and troubled him for them,
would show him his salvation; for he that shows a man his sin,
is the same that takes it away.
While I was speaking to him, the Lord`'s power opened him,
so that he began to have a good understanding in the Lord`'s truth,
and to be sensible of God`'s mercies;
and began to speak boldly in his quarters amongst the soldiers, and to others,
concerning truth (for the Scriptures were very much opened to him),
insomuch that he said, "`his colonel was as blind as Nebuchadnezzar,
to cast the servant of the Lord into prison.`"
Upon this his colonel had a spite against him; and at Worcester fight, the year after,
when the two armies were lying near one another, two came out from the king`'s army,
and challenged any two of the Parliament army to fight with them;
his colonel made choice of him and another to answer the challenge.
And when in the encounter his companion was slain,
he drove both his enemies within musket-shot out of the town,
without firing a pistol at them.
This, when he returned, he told me with his own mouth.
But when the fight was over, he saw the deceit and hypocrisy of the officers;
and being sensible how wonderfully the Lord had preserved him,
and seeing also to the end of fighting, he laid down his arms.

Now the time of my commitment to the house of correction being nearly ended,
and there being many new soldiers raised,
the commissioners would have made me captain over them;
and the soldiers said they would have none but me.^
footnote:[The English nation at this period was much engrossed
with the great subjects of religion and politics,
and both were mingled together in strange conjunction.
The chief rulers of the Commonwealth, more especially Oliver Cromwell,
had contrived to interweave their own views on
spiritual matters into the minds of the soldiers;
who, in those days, commonly united, with the profession of arms,
the profession also of Christianity.
The unsettled state of the country caused them to be stationed in
considerable numbers in most of the principal towns of the north,
where several of them had made acquaintance with George Fox during his imprisonment,
and were so much impressed in his favour, that it appears they were desirous,
as the time of his release drew near, to engage him in the capacity of their captain.]
So the keeper of the house of correction was commanded to bring me
before the commissioners and soldiers in the marketplace;
and there they offered me that preferment, as they called it, asking me,
if I would not take up arms for the Commonwealth against Charles Stuart? I told them,
I knew from whence all wars arose, even from the lust, according to James`'s doctrine;
and that I lived in the virtue of that life and
power that took away the occasion of all wars.
But they courted me to accept their offer, and thought I did but compliment them.
But I told them, I was come into the covenant of peace,
which was before wars and strifes were.
They said, they offered it in love and kindness to me, because of my virtue;
and such like flattering words they used.
But I told them, if that was their love and kindness, I trampled it under my feet.
Then their rage got up, and they said,
"`Take him away, jailer, and put him into the dungeon amongst the rogues and felons.`"
So I was had away and put into a lousy, stinking place, without any bed,
amongst thirty felons, where I was kept almost half a year, unless it were at times;
for they would sometimes let me walk in the garden,
having a belief that I would not go away.
Now when they had got me into Derby dungeon,
it was the belief and saying of people that I should never come out;
but I had faith in God, and believed I should be delivered in his time;
for the Lord had said to me before, that I was not to be removed from that place yet,
being set there for a service which he had for me to do.

After it was noised abroad that I was in Derby dungeon,
my relations came to see me again;
and they were much troubled that I should be in prison;
for they looked upon it to be a great shame to them for me to be imprisoned for religion;
and some thought I was mad, because I advocated purity, and righteousness,
and perfection.

Among others that came to see, and discourse with me, was a person from Nottingham,
a soldier, that had been a Baptist (as I understood), and with him came several others.
In discourse he said to me, "`Your faith stands in a man that died at Jerusalem,
and there never was any such thing.`"
I was exceedingly grieved to hear him say so; and I said to him,
"`How! did not Christ suffer without the gates of Jerusalem through the professing Jews,
and chief priests, and Pilate?`" And he denied that ever Christ suffered there outwardly.
Then I asked him whether there were not chief priests, and Jews,
and Pilate there outwardly? and when he could not deny that, then I told him,
as certainly as there was a chief priest, and Jews, and Pilate there outwardly,
so certainly was Christ persecuted by them, and did suffer there outwardly under them.
Yet from this man`'s words was a slander raised upon us,
that the Quakers denied Christ that suffered and died at Jerusalem;
which was all utterly false, and the least thought of it never entered our hearts;
but it was a mere slander cast upon us, and occasioned by this person`'s words.
The same person also said, that never any of the prophets, or apostles,
or holy men of God, suffered any thing outwardly; but all their sufferings were inward.
But I instanced to him how many of them suffered, and by whom they suffered:
and so was the power of the Lord brought over his wicked imaginations.

There came also another company to me, that pretended they were triers of spirits;
I asked them what was the first step to peace,
and what it was by which a man might see his salvation?
and they were presently up in the airy mind, and said I was mad.
Thus they came to try spirits, who did not know themselves, nor their own spirits.

[.offset]
In this time of my imprisonment,
I was exceedingly exercised about the proceedings of the
judges and magistrates in their courts of judicature.
I was moved to write to the judges concerning their putting men to death for cattle,
and money, and small matters;
and to show them how contrary it was to the law of God in old time;
for I was under great suffering in my spirit because of it,
and under the very sense of death; but standing in the will of God,
a heavenly breathing arose in my soul to the Lord.
Then did I see the heavens opened, and I rejoiced, and gave glory to God.
So I wrote to the judges as follows:--

"`I am moved to write unto you to take heed of putting
men to death for stealing cattle or money,
etc.; for thieves in the old time were to make restitution;
and if they had not wherewith, they were to be sold for their theft.
Mind the laws of God in the Scriptures, and the Spirit that gave them forth;
let them be your rule in executing judgment; and show mercy,
that you may receive mercy from God, the judge of all.
Take heed of gifts and rewards, and of pride; for God doth forbid them;
they blind the eyes of the wise.
I do not write to give liberty to sin; God hath forbidden it;
but that you should judge according to his laws, and show mercy:
for he delighteth in true judgment and in mercy.
I beseech you to mind these things, and prize your time, now you have it: fear God,
and serve him; for he is a consuming fire.`'

[.offset]
Besides this, I wrote another letter to the judges, to this effect:--

"`I am moved to write unto you that ye do true justice to every man;
and see that none be oppressed, or wronged, or any oaths imposed;
for the land mourneth because of oaths, and adulteries, and sorceries, and drunkenness,
and profaneness.
O consider, ye that are men set in authority: be moderate,
and in lowliness consider these things.
Show mercy to the fatherless, to the widows, and to the poor;
and take heed of rewards or gifts, for they blind the eyes of the wise;
the Lord doth loathe all such.
Love mercy and true judgment, justice, and righteousness, for the Lord delighteth therein.
Consider these things in time, and take heed how ye spend your time.
Now ye have time, prize it; and show mercy, that ye may receive mercy from the Lord;
for he is coming to try all things, and will plead with all flesh, as by fire.`"

[.small-break]
'''

Moreover, I laid before the judges what an hurtful thing it was,
that prisoners should lie so long in jail;
showing how they learned wickedness one of another in talking of their bad deeds:
and therefore speedy justice should be done.
For I was a tender youth, and dwelt in the fear of God,
and being grieved to hear their bad language,
I was often made to reprove them for their wicked words,
and evil conduct towards each other.
People admired that I was so preserved and kept;
for they could never catch a word or action from me, to make any thing of against me,
all the time I was there;
for the Lord`'s infinite power upheld and preserved me all that time;
to him be praises and glory forever!

While I was here in prison,
there was a young woman in the jail for robbing her master of some money.
When she was to be tried for her life, I wrote to the judge and to the jury about her,
showing them how it was contrary to the law of God in
old time to put people to death for stealing,
and moving them to show mercy.
Yet she was condemned to die, and a grave was made for her;
and at the time appointed she was carried forth to execution.
Then I wrote a few words, warning all people to beware of greediness or covetousness,
for it leads from God; and exhorting all to fear the Lord, to avoid all earthly lusts,
and to prize their time while they have it: this I gave to he read at the gallows.
And though they had her upon the ladder, with a cloth bound over her face,
ready to be turned off, yet they did not put her to death,
but brought her back again to prison:
and in the prison she afterwards came to be convinced of God`'s everlasting truth.

There was also in the jail, while I was there, a prisoner, a wicked, ungodly man,
who was a reputed conjuror.
He threatened how he would talk with me, and what he would do to me;
but he never had power to open his mouth to me.
And once the jailer and he falling out, he threatened that he would raise the Devil,
and break his house down, so that he made the jailer afraid.
Then I was moved of the Lord to go in his power, and rebuke him, and say unto him,
"`Come let us see what thou canst do; do thy worst:`"
and I told him the Devil was raised high enough in him already,
but the power of God chained him down: so he slunk away from me.

Now the time of Worcester fight coming on,
Justice Bennet sent the constables to press me for a soldier,
seeing I would not voluntarily accept of a command.
I told them that I was brought off from outward wars.
They came down again to give me press-money, but I would take none.
Then I was brought up to Sergeant Holes, kept there a while, and then taken down again.
After a while the constables fetched me up again,
and brought me before the commissioners, who said I should go for a soldier;
but I told them that I was dead to it.
They said I was alive.
I told them, where envy and hatred are, there is confusion.
They offered me money twice, but I would not take it: then they were angry,
and committed me close prisoner, without bail or mainprize.
Whereupon I wrote to them again,
directing my letter to Colonel Barton (who was a preacher),
and the rest that were concerned in my commitment.
I wrote thus:--

[.small-break]
'''

"`You who are without Christ, and yet use the words which he and his saints have spoken;
consider, neither he nor his apostles did ever imprison any;
but my Saviour is merciful even to the unmerciful and rebellious.
He brings out of prison and bondage; but men, while the carnal mind rules,
oppress and imprison.
My Saviour saith, '`Love your enemies, and do good to them that hate you,
and pray for them that despitefully use you and persecute you;`'
for the love of God doth not persecute any,
but loveth all where it dwelleth.
'`He that hateth his brother is a murderer.`' You profess to be Christians,
and one of you a minister of Jesus Christ; yet you have imprisoned me,
who am a servant of Jesus Christ.
The apostles never imprisoned any, but were imprisoned themselves.
Take heed of speaking of Christ in words, and denying him in life and power.
O friends, the imprisoning of my body is to satisfy your wills;
but take heed of giving way to your wills, for that will hurt you.
If the love of God had broken your hearts, ye would not have imprisoned me;
but my love is to you, as to all my fellow creatures; and that you may weigh yourselves,
and see how you stand, is this written.`"

[.offset]
About this time I was moved to give forth the following,
to go amongst the convinced and tender people, to manifest the deceits of the world,
and how the priests have deceived the people:--

[.blurb]
=== To all you that love the Lord Jesus Christ with a pure and naked heart, and the generation of the righteous.

"`Christ was ever hated; and the righteous for his sake.
Mind who they were that did ever hate them:
he that was born after the flesh did persecute him that was born after the Spirit;
and so it is now.
Mind who were the chiefest against Christ; even the great, learned men,
the heads of the people, rulers and teachers, that professed the law and the prophets,
and looked for Christ.
They looked for an outwardly glorious Christ, to hold up their outward glory;
but Christ spoke against the works of the world, and against the priests, and scribes,
and Pharisees, and their hypocritical profession.
He that is a stranger to Christ, is a hireling;
but the servants of Jesus Christ are free men.
The false teachers always laid burdens upon the people;
and the true servants of the Lord spoke against them.
Jeremiah spoke against hirelings, and said, It was a horrible thing;
What will ye do in the end? for the people and priests were given to covetousness.
Paul spoke against such as made gain upon the people;
and exhorted the saints to turn away from such as were covetous men and proud,
such as loved pleasures more than God--such as had a form of godliness,
but denied the power thereof; '`for of this sort,`' said he,
'`are they that creep into houses, and lead captive silly women, who are ever learning,
but never able to come to the knowledge of the truth; men of corrupt minds,
reprobate concerning the faith; and as Jannes and Jambres withstood Moses, so,`' said he,
'`do these resist the truth; but they shall proceed no further,
for their folly shall be made manifest unto all men.`' Moses
forsook honours and pleasures which he might have enjoyed.
The apostle in his time saw this corruption entering, which now is spread over the world,
of having a form of godliness, but denying the power.
Ask any of your teachers whether you may ever overcome
your corruptions or sins? None of them believe that;
but, '`as long as man is here, he must,`' they say,
'`carry about with him the body of sin.`' Thus pride is kept up,
and that honour and mastership, which Christ denied, and all unrighteousness;
yet multitudes of teachers! heaps of teachers! the golden cup full of abominations!
Paul did not preach for wages, but laboured with his hands,
that he might be an example to all them that follow him.
O people, see who follow Paul!
The prophet Jeremiah said, '`The prophets prophesy falsely,
and the priests bear rule by their means;`' but now the
priests bear rule by the means they get from the people:
take away their means, and they will bear rule over you no longer.
They are such as, the apostle said, '`intruded into those things which they never saw,
being vainly puffed up with a fleshly mind;`' and
as the Scriptures declare of some of old,
'`They go in the way of Cain, who was a murderer, and in the way of Balaam,
who coveted the wages of unrighteousness.`' The prophet Micah
also cried against the judges that judged for reward,
and the priests that taught for hire, and the prophets that prophesied for money;
and yet leaned on the Lord, saying,
'`Is not the Lord amongst us?`' Gifts blind the eyes of the wise.
The gift of God was never purchased with money.
All the holy servants of God did ever cry against deceit;
and where the Lord hath manifested his love, they do loathe it,
and that nature which holdeth it up.`"

[.offset]
Again a concern came upon me to write to the magistrates of Derby;
which I did as follows:--

[.embedded-content-document.letter]
--

[.salutation]
"`Friends,

"`I desire you to consider in time whom ye do imprison;
for the magistrate is set for the punishment of evil-doers,
and for the praise of them that do well.
But when the Lord doth send his messengers unto you,
to warn you of the woes that will come upon you, except you repent,
then you persecute them, and put them in prison; and say, '`We have a law,
and by our law we may do it.`' For you indeed justify yourselves before men;
but God knoweth your hearts.
He will not be worshipped with your forms and professions, and shows of religion.
Therefore consider, ye that talk of God, how ye are subject to him;
for they are his children that do his will.
What doth the Lord require of you but to do justice, to love and show mercy,
to walk humbly with him,
and to help the widows and fatherless to their
right? But instead thereof ye oppress the poor.
Do not your judges judge for rewards,
and your priests teach for hire? The time is coming, that he who seeth all things,
will discover all your secrets: and know this assuredly,
the Lord will deliver his servants out of your hands,
and he will recompense all your unjust dealings towards his people.
I desire you to consider of these things; search the Scriptures,
and see whether any of the people of God did ever imprison any for religion.
They were themselves imprisoned.
I desire you to consider, that it is written, '`When the church is met together,
ye may all prophesy one by one, that all may learn, and all may be comforted;`' and then,
'`if anything be revealed to another that sitteth by,
let the first hold his peace.`' Thus it was in the true church;
and thus it ought to be now.
But it is not so in your assemblies; he that teaches for hire may speak,
and none may contradict him.
Again, consider the liberty that was given to the apostles,
even among the unbelieving Jews; when after the reading of the law and the prophets,
the rulers of the synagogue said unto them, '`Ye men and brethren,
if ye have any word of exhortation for the people,
say on.`' I desire you to consider in stillness, and strive not against the Lord;
for he is stronger than you.
Though ye hold his people fast for a time, yet when he cometh,
he will make known who are his;
for his coming is like the refiner`'s fire and like fuller`'s soap.
Then the stone that is set at nought by you builders,
shall be the headstone of the corner.
O friends, lay these things to heart, and let them not seem light things to you.
I write to you in love, to mind the laws of God and your own souls,
and to do as the holy men of God did.`"

--

Great was my exercise and travail in spirit, during my imprisonment here,
because of the wickedness that was in this town; for though some were convinced,
yet the generality were a hardened people;
and I saw the visitation of God`'s love pass away from them.
I mourned over them;
and it came upon me to give forth the following lamentation for them:--

[.embedded-content-document.address]
--

"`O Derby! as the waters run away when the flood-gates are up,
so doth the visitation of God`'s love pass away from thee, O Derby!
Therefore look where thou art, and how thou art grounded; and consider,
before thou art utterly forsaken.
The Lord moved me twice,
before I came to cry against the deceits and vanities that are in thee,
and to warn all to look at the Lord, and not at man.
The woe is against the crown of pride; the woe is against drunkenness and vain pleasures,
and against them that make a profession of religion in words,
yet are high and lofty in mind, and live in oppression and envy.
O Derby! thy profession and preaching stink before the Lord.
Ye profess a Sabbath in words, and meet together, dressing yourselves in fine apparel;
you uphold pride.
Thy women go with stretched-forth necks and wanton eyes, etc,
which the true prophet of old cried against.
Your assemblies are odious, and an abomination to the Lord: pride is sot up,
and bowed down to; covetousness abounds; and he that doeth wickedly is honoured:
so deceit bears with deceit; and yet they profess Christ in words.
O the deceit that is within thee! it doth even break my
heart to see how God is dishonoured in thee, O Derby!`"

--

After I had seen the visitation of God`'s love pass away from this place,
I knew that my imprisonment here would not continue long;
but I saw that when the Lord should bring me forth,
it would be as the letting of a lion out of a den amongst the wild beasts of the forest.
For all professions stood in a beastly spirit and nature, pleading for sin,
and for the body of sin and imperfection, as long as they lived.
They all raged, and ran against the life and Spirit which gave forth the Scriptures,
which they professed in words.
And so it was, as will appear hereafter.

There was a great judgment upon the town,
and the magistrates were uneasy about it but they could not agree what to do with me.
One while they would have me sent up to the parliament;
another while they would have banished me to Ireland.
At first they called me a deceiver, and a seducer, and a blasphemer: afterwards,
when God had brought his plagues upon them, they said I was an honest, virtuous man.
But their good report or bad report, their well speaking or their ill speaking,
was nothing to me; for the one did not lift me up, nor the other cast me down:
praised be the Lord!
At length they were made to turn me out of jail,
about the beginning of Winter in the year 1651,
after I had been a prisoner in Derby almost a year;
six months in the House of Correction,
and the rest of the time in the common jail and dungeon.

Thus being set at liberty again, I went on, as before, in the work of the Lord,
passing through the country, first, into my own country of Leicestershire,
and had meetings as I went; and the Lord`'s Spirit and power accompanied me.
Afterwards I went near to Burton-on-trent, where some were convinced;
and so to Bushel-house, where I had a meeting.
I went up into the country, where there were friendly people;
yet an outrageous wicked professor had an intent to do me a mischief,
but the Lord prevented him.
Blessed be the Lord!

As I was walking along with several Friends, I lifted up my head,
and I saw three steeple-house spires, and they struck at my life.
I asked them what place that was? and they said, Lichfield.
Immediately the word of the Lord came to me, that I must go thither.
Being come to the house we were going to, I wished the Friends that were with me,
to walk into the house, saying nothing to them whether I was to go.
As soon as they were gone, I stepped away, and went by my eye over hedge and ditch,
till I came within a mile of Lichfield; where, in a great field,
there were shepherds keeping their sheep.
Then I was commanded by the Lord to pull off my shoes.
I stood still, for it was Winter; and the word of the Lord was like a fire in me.
So I put off my shoes, and left them with the shepherds;
and the poor shepherds trembled and were astonished.
Then I walked on about a mile, and as soon as I was within the city,
the word of the Lord came to me again, saying, "`Cry,
Woe unto the bloody city of Lichfield.`"
So I went up and down the streets, crying with a loud voice,
"`Woe To The Bloody City Of Lichfield!`"
It being market-day, I went into the market-place,
and to and fro in the several parts of it, and made stands, crying as before,
"`Woe To The Bloody City Of Lichfield!`"
And no one laid hands on me; but as I went thus crying through the streets,
there seemed to me to be a channel of blood running down the streets,
and the market-place appeared like a pool of blood.
When I had declared what was upon me, and felt myself clear,
I went out of the town in peace; and returning to the shepherds, gave them some money,
and took my shoes of them again.
But the fire of the Lord was so in my feet, and all over me,
that I did not matter to put on my shoes any more,
and was at a stand whether I should or not, till I felt freedom from the Lord so to do;
and then, after I had washed my feet, I put on my shoes again.
After this a deep consideration came upon me, why, or for what reason,
I should be sent to cry against that city, and call it The Bloody City.
For though the parliament had the minster one while, and the king another,
and much blood had been shed in the town, during the wars between them,
yet that was no more than had befallen many other places.
But afterwards I came to understand, that in the Emperor Dioclesian`'s time,
a thousand Christians were martyred in Lichfield.
So I was to go, without my shoes, through the channel of their blood,
and into the pool of the blood in the market-place,
that I might raise up the memorial of the blood of those
martyrs which had been shed above a thousand years before,
and lay cold in their streets.
So the sense of this blood was upon me, and I obeyed the word of the Lord.
Ancient records testify how many of the Christian Britons suffered there.
Much I could write of the sense I had of the blood of the martyrs
that hath been shed in this nation for the name of Christ,
both under the ten persecutions and since; but I leave it to the Lord, and to his book,
out of which all shall be judged; for his book is a most certain record,
and his Spirit a true recorder.^
footnote:[Various constructions have been put upon the act here recorded.
It appears to have afforded a feeling of satisfaction to the mind of the actor,
in having performed a service which he believed required of him,
which may have been a test of his faith and obedience.
It certainly affords a striking example of that
undaunted courage George Fox evinced on all occasions,
where his sense of religions duty called upon him to
yield implicit obedience to its injunctions.]

Then I passed up and down through the countries,
having meetings amongst friendly people in many places;
but my relations were offended at me.
After some time I returned into Nottinghamshire, to Mansfield, and went into Derbyshire,
visiting Friends.
Then passing into Yorkshire, I preached repentance through Doncasteb,
and several other places; and after came to Balby, where Richard Farnsworth^
footnote:[Richard Farnsworth became an eminent minister,
and many were turned to God by him.
He was mighty in discourses with priests and professors,
and laboured much in the gospel.
He was twelve months imprisoned at Banbury in 1655,
and after great sufferings and persecutions,
he finished his testimony in London, in 1666.
A short time before his death, sitting up in bed;
he spoke in as much power and strength of spirit
as he had done at any time in his health,
testifying that he was filled with the love of God more than he was able to express.
He published many small works in defence of truth.]
and some others were convinced.
So travelling through several places, preaching repentance,
and the word of life to the people, I came into the parts about Wakefield,
where James Nayler lived; he and Thomas Goodyear came to me, and were both convinced,
and received the truth.
William Dewsbury^
footnote:[William Dewsbury, often mentioned in this Journal,
became a valiant minister of the gospel, travelling extensively in its advocacy.
Whiting says, "`he was an extraordinary man many ways,
and I thought as exact a pattern of a perfect man as ever I knew.`"
His health became impaired through the sharp persecutions he passed through,
consisting of many long imprisonments, beatings, and bruisings.
In 1688, going up to London to visit the brethren,
he was taken ill of a distemper contracted in prison.
Returning home, he died shortly after, leaving a heavenly testimony behind him,
expressed about a week before he died.
This, with other information, is recorded in _Piety Promoted_, vol. i. pp. 163-168,
and further particulars in Whiting`'s _Memoirs,_ p. 25, and at pp. 376-387.
His works were published in 1 vol. quarto, in 1689.]
also and his wife, with many more, came to me, who were convinced, and received the truth.
From thence I passed through the country towards Captain Pursloe`'s house by Selby,
and visited John Leek, who had been to visit me in Derby prison, and was convinced.
I had a horse, but was fain to leave him, not knowing what to do with him;
for I was moved to go to many great houses,
to admonish and exhort the people to turn to the Lord.
Thus passing on, I was moved of the Lord to go to Beverley steeplehouse,
which was then a place of high profession; and being very wet with rain,
I went first to an inn, and as soon as I came to the door,
a young woman of the house came to the door, and said, "`What,
is it you? come in,`" as if she had known me before;
for the Lord`'s power bowed their hearts.
So I refreshed myself and went to bed; and in the morning, my clothes being still wet,
I got ready, and having paid for what I had had in the inn,
I went up to the steeple-house, where was a man preaching.
When he had done, I was moved to speak to him, and to the people,
in the mighty power of God, and turned them to their teacher, Christ Jesus.
The power of the Lord was so strong, that it struck a mighty dread amongst the people.
The mayor came and spoke a few words to me;
but none of them had any power to meddle with me.
So I passed away out of the town,
and in the afternoon went to another steeple-house about two miles off.
When the priest had done, I was moved to speak to him, and to the people very largely,
showing them the way of life and truth, and the ground of election and reprobation.
The priest said, he was but a child, and could not dispute with me;
I told him I did not come to dispute,
but to hold forth the word of life and truth unto them,
that they might all know the one Seed, which the promise of God was to,
both in the male and in the female.
Here the people were very loving, and would have had me come again on a week-day,
and preach among them; but I directed them to their teacher, Christ Jesus,
and so passed away.
The next day I went to Crantsick, to Captain Pursloe`'s,
who accompanied me to Justice Hotham`'s. This Justice Hotham was a tender man,
one that had some experience of God`'s workings in his heart.
After some discourse with him of the things of God, he took me into his closet; where,
sitting together, he told me he had known that principle these ten years,
and was glad that the Lord did now publish it abroad to the people.
After a while there came a priest to visit him,
with whom also I had some discourse concerning Truth.
But his mouth was quickly stopped, for he was nothing but a notionist,
and not in possession of what he talked of.

While I was here,
there came a great woman of Beverley to speak to Justice Hotham about some business;
and in discourse she told him,
that the last Sabbath-day (as she called it) there came
an angel or spirit into the church at Beverley,
and spoke the wonderful things of God, to the astonishment of all that were there;
and when it had done, it passed away, and they did not know whence it came,
nor whither it went; but it astonished all, both priest, professors,
and magistrates of the town.
This relation Justice Hotham gave me afterwards,
and then I gave him an account how I had been that day at Beverley steeple-house,
and had declared truth to the priest and people there.

There were in the country thereabouts some noted priests and doctors,
with whom Justice Hotham was acquainted.
He would fain have them speak with me, and offered to send for them,
under pretence of some business he had with them, but I wished him not to do so.

When the First-day of the week was come,
Justice Hotham walked out with me into the field; and Captain Pursloe coming up after us,
Justice Hotham left us and returned home,
but Captain Pursloe went with me into the steeple-house.
When the priest had done, I spoke both to priest and people;
declared to them the word of life and truth,
and directed them where they might find their teacher, the Lord Jesus Christ.
Some were convinced, received the truth, and stand fast in it;
and have a fine meeting to this day.

In the afternoon I went to another steeple-house about three miles off,
where preached a great high-priest, called a doctor,
one of them whom Justice Hotham would have sent for to speak with me.
I went into the steeple-house, and stayed till the priest had done.
The words which he took for his text were these, "`Ho, every one that thirsteth,
come ye to the waters; and he that hath no money, come ye, buy and eat, yea come,
buy wine and milk without money and without price.`"
Then was I moved of the Lord God to say unto him, "`Come down, thou deceiver;
dost thou bid people come freely, and take of the water of life freely,
and yet thou takest three hundred pounds a year of them,
for preaching the Scriptures to them.
Mayest thou not blush for shame? Did the prophet Isaiah, and Christ do so,
who spoke the words, and gave them forth freely? Did not Christ say to his ministers,
whom he sent to preach, '`Freely ye have received, freely give?`'`" The priest,
like a man amazed, hastened away.
After he had left his flock, I had as much time as I could desire to speak to the people;
and I directed them from the darkness to the light, and to the grace of God,
that would teach them, and bring them salvation;
to the Spirit of God in their inward parts, which would be a free teacher unto them.

Having cleared myself amongst the people,
I returned to Justice Hotham`'s house that night, who, when I came in,
took me in his arms, and said his house was my house,
for he was exceedingly glad at the work of the Lord, and that his power was revealed.
Then he told me why he went not with me to the steeple-house in the morning,
and what reasonings he had in himself about it; for he thought,
if he had gone with me to the steeple-house, the officers would have put me to him;
and then he should have been so put to it, that he should not have known what to do.
But he was glad, he said, when Captain Pursloe came up to go with me;
yet neither of them was dressed, nor had his band about his neck.
It was a strange thing then to see a man come into a steeple-house without a band;
yet Captain Pursloe went in with me without his band,
the Lord`'s power and truth had so affected him that he minded it not.

From hence I passed on through the country,
and came at night to an inn where was a company of rude people.
I bid the woman of the house, if she had any meat, to bring me some;
but because I said Thee and Thou to her she looked strangely on me.
Then I asked her if she had any milk; and she said, No.
I was sensible she spoke falsely,
and being willing to try her further, I asked her if she had any cream;
she denied that she had any.
Now there stood a churn in the room, and a little boy playing about it,
put his hands into it, and pulled it down,
and threw all the cream on the floor before my eyes.
Thus was the woman manifested to be a liar.
She was amazed, and blessed herself, and taking up the child, whipped it sorely;
but I reproved her for her lying and deceit.
After the Lord had thus discovered her deceit and perverseness,
I walked out of the house, and went away till I came to a stack of hay,
and lay in the hay-stack that night in rain and snow,
it being but three days before the time called Christmas.

The next day I came into York, where were several people that were very tender.
Upon the First-day of the week following,
I was commanded of the Lord to go to the great minster,
and speak to priest Bowles and his hearers in their great cathedral.
Accordingly I went: and when the priest had done,
I told them I had something from the Lord God to speak to the priest and people.
"`Then say on quickly,`" said a professor that was among them, for it was frost and snow,
and very cold weather.
Then I told them, This was the word of the Lord God unto them, that they lived in words;
but God Almighty looked for fruits amongst them.
As soon as the words were out of my mouth, they hurried me out,
and threw me down the steps; but I got up again without hurt, and went to my lodgings.
Several were convinced there:
for the very groans that arose from the weight and
oppression that was upon the Spirit of God in me,
would open people, and strike them,
and make them confess that the groans which broke forth through me did reach them;
for my life was burdened with their profession without possession,
and words without fruit.

After I had done my present service in York, and several were convinced there,
received the truth of God, and were turned to his teaching, I passed out of York,
and looking towards Cleveland,
I saw there was a people that had tasted of the power of God.
I saw then there was a seed in that country, and that God had an humble people there.
Passing onwards that night, a Papist overtook me, and talked to me of his religion,
and of their meetings; and I let him speak all that was in his mind.
That night I stayed at an ale-house.
The next morning I was moved of the Lord to speak the word of the Lord to this Papist.
So I went to his house, and declared against his religion,
and all their superstitious ways;
and told him that God was come to teach his people himself.
This put the Papist into such a rage,
that he could not then endure to stay in his own house.

The next day I came to Burraby, where a priest and several friendly people met together.
Many of the people were convinced, and have continued faithful ever since;
and there is a great meeting of Friends in that town.
The priest also was forced to confess to the truth, though he came not into it.

The day following I went into Cleveland,
amongst those people that had tasted of the power of God.
They had formerly had great meetings, but were then all shattered to pieces,
and the heads of them turned Banters.
I told them that after they had had such meetings,
they did not wait upon God to feel his power, to gather their minds inward,
that they might feel his presence and power amongst them in their meetings,
to sit down therein, and wait upon him; for they had spoken themselves dry;
they had spent their portions, and not living in that which they spoke of,
they were now become dry.
They had some kind of meetings still;
but they took tobacco and drank ale in their meetings, and were grown light and loose.
But my message unto them from the Lord was, That they should all come together again,
and wait to feel the Lord`'s power and Spirit in themselves, to gather them to Christ,
that they might be taught of him who says, "`Learn of me.`"
For when they had declared that which the Lord had opened to them,
then the people were to receive it;
and both the speakers and hearers were to live in that themselves.
But when these had no more to declare, but went to seek forms without life,
that made themselves dry and barren, and the people also;
and from thence came all their loss:
for the Lord renews his mercies and his strength to them that wait upon him.
The heads of these people came to nothing: but most of them came to be convinced,
and received God`'s everlasting truth, and continue a meeting to this day,
sitting under the teaching of the Lord Jesus Christ their Saviour.

Upon the First-day of the next week,
the word of the Lord came to me to go to the steeple-house there, which I did.
When the priest had done I spoke the truth to him and the people,
and directed them to their teacher within, Christ Jesus, their free teacher,
that had bought them.
The priest came to me, and I had a little discourse with him;
but he was soon stopped, and silent.
Then being clear of the place, I passed away,
having had several meetings amongst those people.

Though at this time the snow was very deep, I kept travelling;
and going through the country, came to a market-town, where I met with many professors,
with whom I had much reasoning.
I asked them many questions, which they were not able to answer; saying,
they had never had such deep questions put to them in all their lives.

From them I went to Stath, where also I met with many professors, and some Ranters.
I had large meetings amongst them, and a great convincement there was.
Many received the truth; amongst whom, one was a man of an hundred years of age;
another was a chief constable; and a third was a priest, whose name was Philip Scafe.
Him the Lord, by his free Spirit, did afterwards make a free minister of his free gospel.

The priest of this town was a lofty one, who much oppressed the people for his tithes.
If they went a-fishing many leagues off,
he would make them pay the tithe-money of what they made of their fish,
though they caught them at a great distance, and carried them as far as Yarmouth to sell.
I was moved to go to the steeple-house there, to declare the truth, and expose the priest.
When I had spoken to him, and laid his oppression of the people before him, he fled away.
The chief of the parish were very light and vain;
so after I had spoken the word of life to them, I turned away from them,
because they did not receive it, and left them.
But the word of the Lord, which I had declared amongst them, remained with some of them;
so that at night some of the heads of the parish came to me,
and most of them were convinced and satisfied, and confessed to the truth.
Thus the truth began to spread in that country, and great meetings we had;
at which the priest began to rage, and the Banters to be stirred;
and they sent me word that they would have a dispute with me, both the oppressing priest,
and the leaders of the Ranters.
A day was fixed, and the Ranter came with his company; and another priest, a Scotchman,
came; but not the oppressing priest of Stath.
Philip Scafe, who had been a priest, and was convinced, was with me;
and a great number of people met.
When we were seed, the Ranter, whose name was T. Bushel,
told me he had had a vision of me; that I was sitting in a great chair,
and that he was to come and put off his hat, and bow down to the ground before me;
and he did so: and many other flattering words he spoke.
I told him it was his own figure, and said unto him, "`Repent, thou beast.`"
He said it was jealousy in me to say so.
Then I asked him the ground of jealousy,
and how it came to be bred in man? and the nature of a beast, what made it,
and how it was bred in man? For I saw him directly in the nature of the beast;
and therefore I wished to know of him how that nature came to be bred in him?
I told him he should give me an account of the things done in the body,
before we came to discourse of things done out of the body.
So I stopped his mouth, and all his fellow Ranters were silenced;
for he was the head of them.
Then I called for the oppressing priest, but he came not; only the Scotch priest came,
whose mouth was soon stopped with a very few words;
he being out of the life of what he professed.
Then I had a good opportunity with the people.
I laid open the Ranters, ranking them with the old Ranters in Sodom.
The priests I manifested to be of the same stamp with their fellow-hirelings,
the false prophets of old,
and the priests that then bore rule over the people by their means,
seeking for their gain from their quarter, divining for money,
and teaching for filthy lucre.
I brought all the prophets, and Christ, and the apostles, over the heads of the priests,
showing how the prophets, Christ, and the apostles,
had long since discovered them by their marks and fruits.
Then I directed the people to their inward teacher, Christ Jesus their Saviour;
and I preached up Christ in the hearts of his people,
when all these mountains were laid low.
The people were all quiet, and the gainsayers`' mouths were stopped;
for though they broiled inwardly, yet the power bound them down,
that they could not break out.

After the meeting,
this Scotch priest desired me to walk with him on the top of the cliffs;
whereupon I called a brother-in-law of his, who was in some measure convinced,
and desired him to go with me,
telling him I desired to have somebody by to hear what was said, lest the priest,
when I was gone, should report anything of me which I did not say.
We went together; and as we walked, the priest asked me many things concerning the light,
and concerning the soul; to all which I answered him fully.
When he had done questioning, we parted, and he went his way;
and meeting with Philip Scafe, he broke his cane against the ground in madness, and said,
if ever he met with me again, he would have my life, or I should have his; adding,
that he would give his head, if I was not knocked down within a month.
By this, Friends suspected that his intent was, in desiring me to walk with him alone,
either to thrust me down from off the cliff, or to do me some other mischief;
and that when he saw himself frustrated in that, by my having one with me,
it made him rage.
I feared neither his prophecies nor his threats; for I feared God Almighty.
But some Friends, through their affection for me,
feared much that this priest would do me some mischief, or set on others to do it.
Yet after some years this very Scotch priest, and his wife also,
came to be convinced of the truth; and about twelve years after this,
I was at their house.

After this, there came another priest to a meeting where I was,
one that was in repute above all the priests in the country.
As I was speaking in the meeting, that the gospel was the power of God,
and how it brought life and immortality to light in men,
and was turning people from darkness to the light,
this high-flown priest said the gospel was mortal.
I told him, the true minister said, the gospel was the power of God,
and would he make the power of God mortal? Upon that the other priest, Philip Scafe,
that was convinced, and had felt the immortal power of God in himself,
took him up and reproved him; so a great dispute arose between them;
the convinced priest holding that the gospel was immortal,
and the other priest that it was mortal.
But the Lord`'s power was too hard for this opposing priest, and stopped his mouth;
and many people were convinced, seeing the darkness that was in the opposing priest,
and the light that was in the convinced priest.

Then another priest sent to have a dispute with me,
and Friends went with me to the house where he was: but when he understood we were come,
he slipped out of the house, and hid himself under a hedge.
The people went to seek him, and found him, but could not get him to come to us.
Then I went to a steeple-house hard by, where the priest and people were in a great rage:
this priest had threatened Friends what he would do; but when I came he fled;
for the Lord`'s power came over him and them.
Yea, the Lord`'s everlasting power was over the world,
and reached to the hearts of people, and made both priests and professors tremble.
It shook the earthly and airy spirit,
in which they held their profession of religion and worship,
so that it was a dreadful thing unto them, when it was told them,
"`The man in leather breeches is come.`"^
footnote:[The leathern garments worn by George Fox were
chosen by him for their simplicity and durability;
and though they often subjected their wearer to ridicule and abuse,
he had no motive beyond the above-mentioned for choosing such a garb.
Many persons have been amused,
if not offended at him for having worn such a dress when he was a young man.
In those days leathern garments for working men
may not have been so singular as some suppose.
It is a well authenticated fact, that an eminent merchant of the city of London,
about 150 years ago, travelled on foot from Newcastle, in search of a livelihood,
clad in a coat of leather.
He opened a warehouse in London for the sale of heavy articles of iron,
which were manufactured in the neighbourhood of Newcastle.
In a few years he became prosperous, accumulated a large fortune,
and ranked with the magnates of the city,
sharing in all the civic honours of the corporation.
The firm which he established still continues to conduct a flourishing business,
at a warehouse in Thames Street,
which is familiarly known in the trade by
"`The Leathern Doublet;`" a representation of the founder`'s original dress
being fixed as a sign in front of the building.]
At the hearing thereof the priests, in many places, would get out of the way;
they were so struck with the dread of the eternal power of God;
and fear surprised the hypocrites.

From this place we passed to Whitby and Scarborough,
where we had some service for the Lord; there are large meetings settled there since.
From thence I passed over the Wolds to Malton, where we had great meetings;
as we had also at the towns thereabouts.
At one town a priest sent me a challenge to dispute with me; but when I came,
he would not come forth; so I had a good opportunity with the people,
and the Lord`'s power came over them.
One, who had been a wild, drunken man, was so reached therewith,
that he came to me as lowly as a lamb;
though he and his companions had before sent for drink, to make the rude people drunk,
on purpose that they might abuse us.
When I found the priest would not come forth, I was moved to go to the steeple-house;
the priest was confounded, and the Lord`'s power came over all.

On the First-day following, came one of the highest Independent professors, a woman,
who had let in such a prejudice against me, that she said before she came,
she could willingly go to see me hanged: but when she came, she was convinced,
and remains a Friend.

Then I turned to Malton again, and very great meetings there were;
to which more people would have come, but durst not for fear of their relations;
for it was thought a strange thing then to preach in houses, and not go to the church,
as they called it; so that I was much desired to go and speak in the steeple-houses.
One of the priests wrote to me, and invited me to preach in the steeple-house,
calling me his brother.
Another priest, a noted man, kept a lecture there.
Now the Lord had showed me, while I was in Derby prison,
that I should speak in steeple-houses, to gather people from thence;
and a concern sometimes would come upon my mind
about the pulpits that the priests lolled in.
For the steeple-houses and pulpits were offensive to my mind,
because both priests and people called them the house of God, and idolized them;
reckoning that God dwelt there in the outward house.
Whereas they should have looked for God and Christ to dwell in their hearts,
and their bodies to be made the temples of God; for the apostle said,
"`God dwelleth not in temples made with hands:`" but by
reason of the people`'s idolizing those places,
it was counted a heinous thing to declare against them.
When I came into the steeple-house, there were not above eleven hearers,
and the priest was preaching to them.
But after it was known in the town that I was in the steeple-house,
it was soon filled with people.
When the priest that preached that day had done,
he sent the other priest that had invited me thither, to bring me up into the pulpit;
but I sent word to him, that I needed not to go into the pulpit.
Then he sent to me again, desiring me to go up into it; for, he said,
it was a better place, and there I might be seen of the people.
I sent him word again, I could be seen and heard well enough where I was;
and that I came not there to hold up such places, nor their maintenance and trade.
Upon my saying so, they began to be angry, and said,
"`these false prophets were to come in the last times.`"
Their saying so grieved many of the people; and some began to murmur at it.
Whereupon I stood up, and desired all to be quiet; and stepping upon a high scat,
I declared unto them the marks of the false prophets,
and showed that they were already come; and set the true prophets, and Christ,
and his apostles over them;
and manifested these to`' be out of the steps of the true prophets,
and of Christ and his apostles.
I directed the people to their inward teacher, Christ Jesus,
who would turn them from darkness to the light.
And having opened divers Scriptures to them,
I directed them to the Spirit of God in themselves, by which they might come to him,
and by which they might also come to know who the false prophets were.
So having had a large opportunity among them, I departed in peace.

After some time, I came to Pickering,
where in the steeple-house the justices held their sessions,
Justice Robinson being chairman.
I had a meeting in the school-house at the same time;
and abundance of priests and professors came to it, asking questions,
which were answered to their satisfaction.
It being sessions-time,
four chief constables and many other people were convinced that day;
and word was carried to Justice Robinson that his priest was overthrown and convinced,
whom he had a love to, more than to all the priests besides.
After the meeting, we went to an inn.
Justice Robinson`'s priest was very lowly and loving, and would have paid for my dinner,
but I would by no means suffer it.
Then he offered that I should have his steeple-house to preach in, but I refused it,
and told him and the people, that I came to bring them off from such things to Christ.

The next morning I went with the four chief constables, and others,
to visit Justice Robinson, who met me at his chamber door.
I told him, I could not honour him with man`'s honour.
He said he did not look for it.
So I went into his chamber, and opened to him the state of the false prophets,
and of the true prophets; and set the true prophets, and Christ,
and the apostles over the other; and directed his mind to Christ his teacher.
I opened to him the parables, and how election and reprobation stood;
as that reprobation stood in the first birth, and election stood in the second birth.
I showed also what the promise of God was to, and what the judgment of God was against.
He confessed to it all; and was so opened with the truth,
that when another justice that was present, made some little opposition, he informed him.
At our parting, he said it was very well that I exercised that gift,
which God had given me.
He took the chief constables aside, and would have given them some money for me, saying,
he would not have me at any charge in their country;
but they told him that they could not persuade me to take any;
and so accepting his kindness, I refused his money.

From thence I passed up into the country,
and the priest that called me brother (in whose
school-house I had the meeting at Pickering),
went along with me.
When we came into a town to bait, the bells rang.
I asked what they rang for: and they said, for me to preach in the steeplehouse.
After some time I felt drawings that way; and as I walked to the steeple-house,
I saw the people were gathered together in the yard.
The old priest would have had me to go into the steeple-house; but I said,
it was no matter.
It was something strange to the people,
that I would not go into that which they called the house of God.
I stood up in the steeplehouse yard, and declared to the people,
that I came not to hold up their idol temples, nor their priests, nor their tithes,
nor their augmentations, nor their priests`' wages,
nor their Jewish and heathenish ceremonies and traditions (for I denied all these),
and told them that that piece of ground was no more holy than another piece of ground.
I showed them that the apostles`' going into the Jews`' synagogues and temples,
which God had commanded, was to bring people off from that temple, and those synagogues,
and from the offerings, and tithes, and covetous priests of that time;
that such as came to be convinced of the truth, and converted to it,
and believed in Jesus Christ, whom the apostles preached,
met together afterwards in dwelling-houses; and that all who preach Christ,
the Word of life, ought to preach freely, as the apostles did, and as he had commanded.
So I was sent of the Lord God of heaven and earth to preach freely,
and to bring people off from these outward temples made with hands,
which God dwelleth not in;
that they might know their bodies to become the temples of God and of Christ:
and to draw people off from all their superstitious ceremonies,
and Jewish and heathenish customs, traditions, and doctrines of men;
and from all the world`'s hireling teachers, that take tithes and great wages,
preaching for hire, and divining for money, whom God and Christ never sent,
as themselves confess, when they say they never heard God`'s voice, nor Christ`'s voice.
Therefore I exhorted the people to come off from all these things,
and directed them to the Spirit and grace of God in themselves,
and to the light of Jesus in their own hearts, that they might come to know Christ,
their free teacher, to bring them salvation, and to open the Scriptures to them.
Thus the Lord gave me a good opportunity amongst them to open things largely unto them.
All was quiet, and many were convinced; blessed be the Lord!

I passed on to another town, where there was another great meeting,
the old priest before mentioned going along with me;
and there came professors of several sorts to it.
I sat on a haystack, and spoke nothing for some hours;
for I was to famish them from words.
The professors would ever and anon be speaking to the old priest,
and asking him when I would begin, and when I would speak.
He bade them wait; and told them,
that '`the people waited upon Christ a long while before he spoke.
At last I was moved of the Lord to speak; and they were struck by the Lord`'s power;
the word of life reached to them, and there was a general convincement amongst them.

From hence I passed on, the old priest being still with me, and several others.
As we went along, some people called to him, and said,
"`Mr. Boyes, we owe you some money for tithes, pray come and take it.`"
But he threw up his hands, and said, he had enough, he would have none of it;
they might keep it; and he praised the Lord he had enough.

At length we came to this old priest`'s steeple-house in the Moors;
and when we were come into it, he went before me, and held open the pulpit door;
but I told him I should not go into it.
This steeple-house was very much painted.
I told him and the people, that the painted beast had a painted house.
Then I opened to them the rise of all those houses, and their superstitious ways;
showing them, that as the end of the apostles`' going into the temple and synagogues,
which God had commanded, was not to hold them up, but to bring the people to Christ,
the substance; so the end of my coming there, was not to hold up these temples, priests,
and tithes, which God had never commanded,
but to bring themselves off from all these things, to Christ the substance.
I showed them the true worship, which Christ had set up;
and distinguished Christ the true way, from all the false ways,
opening the parables to them, and turning them from darkness to the true light,
that by it they might see themselves, their sins, and Christ their Saviour;
that believing in him, they might be saved from their sins.

After this we went to one Birdet`'s house, where I had a great meeting,
and this old priest accompanied me still, leaving his steeple-house;
for he had been looked upon as a famous priest, above Common-Prayermen, and Presbyters,
and Independents too.
Before he was convinced, he went sometimes into their steeple-houses and preached;
for he had been a zealous man in his way.
And when they complained of him to Justice Hotham,
he bid them distrain his horse for travelling on the Lord`'s day (as he called it);
but Hotham did that only to put them off, for he knew the priest used no horse,
but traveled on foot.

Now I came towards Crantsick, to Captain Pursloe`'s and Justice Hotham`'s,
who received me kindly, being glad that the Lord`'s power had so appeared;
that truth was spread, and so many had received it;
and that Justice Robinson was so civil.
Justice Hotham said, If God had not raised up this principle of light and life,
which I preached, the nation had been overrun with Ranterism,
and all the justices in the nation could not have stopped it with all their laws;
because (said he) they would have said as we said, and done as we commanded,
and yet have kept their own principle still.
But this principle of truth, said he, overthrows their principle,
and the root and ground thereof; and therefore,
he was glad the Lord had raised up this principle of life and truth.

From thence I travelled up into Holderness, and came to a justice`'s house,
whose name was Pearson, where there was a very tender woman, that believed in the truth,
and was so affected therewith,
that she said she could have left all and have followed me.

Thence I went to Oram, to one George Hartise`'s, where many of that town were convinced.
On the First-day I was moved to go into the steeple-house,
where the priest had got another to help him;
and many professors and contenders were assembled together.
But the Lord`'s power was over all; the priests fled away,
and much good service I had for the Lord amongst the people.
Some of those great professors were convinced, and became honest, faithful Friends,
being men of account in the place.

The next day, Friends and friendly people having left me, I travelled alone,
declaring the day of the Lord amongst people in the towns where I came,
and warning them to repent.
One day, I came towards night into a town called Patrington;
and as I walked along the town,
I warned both priest and people (for the priest was in the street) to repent,
and turn to the Lord.
It grew dark before I came to the end of the town;
and a multitude of people gathered about me, to whom I declared the word of life.
When I had cleared myself, I went to an inn, and desired them to let me have a lodging;
but they would not.
Then I desired them to let me have a little meat, or milk, and I would pay them for it;
but they would not.
So I walked out of the town, and a company of fellows followed me, and asked me,
what news? I bid them repent, and fear the Lord.
After I had gone some distance, I came to another house,
and desired the people to let me have a little meat and drink, and lodging for my money;
but they denied me.
Then I went to another house, and desired the same; but they refused me also.
By this time it was grown so dark, that I could not see the highway;
but I discerned a ditch, and got a little water and refreshed myself.
Then I got over the ditch, and being weary with travelling,
sat down among the furze-bushes till it was day.
About break of day I got up and passed over the fields.
A man came after me with a great pike-staff, and went along with me to a town;
and he raised the town upon me, with the constable and chief constable,
before the sun was up.
I declared God`'s everlasting truth amongst them, warning them of the day of the Lord,
that was coming upon all sin and wickedness; and exhorted them to repent.
But they seized me, and had me back to Patrington, about three miles,
guarding me with pikes, staves, and halberds.
Now when I was come back to Patrington, all the town was in an uproar,
and the priest and people were consulting together;
so I had another opportunity to declare the word of life amongst them,
and warn them to repent.
At last a professor, a tender man, called me into his house,
and there I took a little milk and bread, not having eaten for some days before.
Then they guarded me about nine miles to a justice.
When I was come near his house, a man came riding after us,
and asked me whether I was the man that was apprehended?
I asked him wherefore he asked? He said,
for no hurt; and I told him I was; so he rode away to the justice before us.
The men that guarded me said, It was well if the justice was not drunk,
before we got to him; for he used to be drunk early.
When I was brought in before him, because I did not put off my hat, and said Thou to him,
he asked the man that rode thither before me, whether I was not mazed or fond;
but the man told him, no, it was my principle.
Then I warned him to repent, and come to the light,
which Christ had enlightened him with,
that by it he might see all his evil words and actions;
and to return to Christ Jesus whilst he had time; and that whilst he had time,
he should prize it.
"`Ay, ay,`" said he, "`the light, that is spoken of in the third of John.`"
I desired him that he would mind it, and obey it.
As I admonished him, I laid my hand upon him,
and he was brought down by the power of the Lord; and all the watchmen stood amazed.
Then he took me into a little parlour with the other man,
and desired to see what I had in my pockets, of letters or intelligence.
I plucked out my linen, and showed him that I had no letters.
He said, He is not a vagrant by his linen; and then he set me at liberty.
I went back to Patrington, with the man that had ridden before me to the justice;
for he lived at Patrington.
When I came there, he would have had me have a meeting at the Cross; but I said,
it was no matter, his house would serve.
He desired me to go to bed, or lie down upon a bed; which he did, that they might say,
they had seen me in a bed, or upon a bed;
for a report had been raised that I would not lie on any bed,
because at that time I lay many times out of doors.
Now when the First-day of the week was come, I went to the steeple-house,
and declared the truth to the priest and people; and the people did not molest me,
for the power of God was come over them.
Presently after I had a great meeting at the man`'s house where I lay,
and many were convinced of the Lord`'s everlasting truth,
who stand faithful witnesses of it to this day.
They were exceedingly grieved that they did not receive me, nor give me lodging,
when I was there before.

From hence I travelled through the country, even to the furthest part thereof,
warning people, in towns and villages, to repent, and directing them to Christ Jesus,
their teacher.

On the First-day of the week I came to one Colonel Overton`'s house,
and had a great meeting of the prime of the people of that country;
where many things were opened out of the Scriptures, which they had never heard before.
Many were convinced, and received the word of life, and were settled in the truth of God.

Then I returned to Patrington again, and visited those Friends that were convinced there;
by whom I understood that a tailor, and some wild blades in that town,
had occasioned my being carried before the justice.
The tailor came to ask my forgiveness, fearing I would complain of him.
The constables also were afraid, lest I should trouble them.
But I forgave them all, and warned them to turn to the Lord, and to amend their lives.
Now that which made them the more afraid was this:
when I was in the steeple-house at Oram not long before, there came a professor,
who gave me a push on the breast in the steeple-house, and bid me get out of the church;
"`Alas, poor man!`" said I,
"`dost thou call the steeple-house the church? The church is the people,
whom God hath purchased with his blood, and not the house.`"
It happened that Justice Hotham came to hear of this man`'s abuse,
sent his warrant for him, and bound him over to the sessions;
so affected was he with the truth, and so zealous to keep the peace.
And indeed this Justice Hotham had asked me before,
whether any people had meddled with me, or abused me;
but I was not at liberty to tell him anything of that kind, but was to forgive all.
