== Chapter V.

[.chapter-synopsis]
* 1652.
* George Fox visits great men`'s houses, warning them to repent
* is accused of calling himself Christ
* refutes the charge, and tells the accuser that Judas`'s end would be his, which shortly came to pass; hence a slander is raised against Friends
* is stoned at Doncaster
* a scoffing priest made to tremble at the Lord`'s power
* a slandering priest cut off in his wickedness
* a murderous man seeks George Fox, but misses him
* he lays in a wood all night
* the influence of one man or woman, who lives in the same spirit that the prophets and apostles were in, is to be felt within a circuit of ten miles
* George Fox ascends Pendle Hill, whence he sees the place of a great gathering of people
* on descending, refreshes himself at a spring of water, having taken little sustenance for several days
* foreSees a great people in white raiment about Wensleydale and Sedbergh
* a wicked man designs to injure him, but is prevented
* many are convinced in Dent, and a meeting is settled at Sedbergh, where he had seen a people in white raiment
* preaches for several hours in the steeple-house yard there
* preaches on a rock, near Firbank chapel, to 1000 people, for three hours
* the family of Judge Fell convinced, and a meeting settled at his house, and continued for forty years
* preaches through Lancaster streets
* at a meeting of priests at Ulverstone he speaks in great power, so that one of them said, "`the church shook`"
* disputes with priest Lampitt
* Justice Sawrey is the first persecutor in the north
* forty priests appear against George Fox at Lancaster Sessions for speaking blasphemy; they are confounded, and he is cleared of the charge
* James Nayler`'s account of George Fox`'s trial at Lancaster Sessions
* priest Jackus is reproved from the bench for his blasphemy
* these priests are reproved by the populace
* Col. West defends and protects George Fox against the machinations of the priests, and the design of Judge Windham, at the risk of losing his place.

From Patrington I went to several great men`'s houses, warning them to repent.
Some received me lovingly, and some slighted me.
Thus I passed on, and at night came to another town, where I desired lodging and meat,
and I would pay for it; but they would not lodge me, except I would go to the constable,
which was the custom (they said) of all lodgers at inns, if strangers.
I told them I should not go; for that custom was for suspicious persons,
but I was an innocent man.
After I had warned them to repent, declared unto them the day of their visitation,
and directed them to the light of Christ and Spirit of God,
that they might come to know salvation, I passed away;
and the people were something tendered, and troubled afterwards.
When it grew dark, I spied a hay-stack, and went and sat under it all night, till morning.

The next day I passed into Hull, admonishing and warning people, as I went,
to turn to Christ Jesus that they might receive salvation.
That night I got a lodging, but was very sore with travelling on foot so far.

Afterwards, I came to Balby, and visited Friends up and down in those parts;
and then passed into the edge of Nottinghamshire, visiting Friends there;
and so into Lincolnshire, and visited Friends there.
And on the First-day of the week I went to a steeple-house on this side of Trent;
and in the afternoon to one on the other side of Trent,
declaring the word of life to the people, and directing them to their teacher,
Christ Jesus, who died for them that they might hear him, and receive salvation by him.
Then I went further into the country, and had several meetings.
To one meeting came a great man, and a priest, and many professors;
but the Lord`'s power came over them all, and they went their ways peaceably.
There came a man to that meeting, who had been at one before,
and raised a false accusation against me, and made a noise up and down the country,
reporting that I had said, I was Christ; which was utterly false.
And when I came to Gainsborough, where a Friend had been declaring truth in the market,
the town and market-people were all in an uproar.
I went into a friendly man`'s house, and the people rushed in after me;
so that the house was filled with professors, disputers, and rude people.
This false accuser came in, and charged me openly before all the people, that I had said,
I was Christ, and he had got witnesses to prove it.
This set the people into such a rage, that they had much to do to keep their hands off me.
Then was I moved of the Lord God to stand up on the table, and,
in the eternal power of God, to tell the people "`That Christ was in them,
except they were reprobates; and that it was Christ the eternal power of God,
that spoke in me at that time unto them; not that I was Christ.`"
And the people were generally satisfied, except himself, a professor,
and his own false-witnesses.
I called the accuser Judas, and was moved to tell him, that Judas`'s end would be his;
and that that was the word of the Lord and of Christ, through me, to him.
So the Lord`'s power came over all, and quieted the minds of the people,
and they departed in peace.
But this Judas went away, and shortly after hanged himself,
and a stake was driven into his grave.
Afterwards the wicked priests raised a scandal upon us,
and reported that a Quaker had hanged himself in Lincolnshire,
and had a stake driven through him.
This falsehood they printed to the nation, adding sin to sin;
which the truth and we were clear of:
for he was no more a Quaker than the priest that printed it,
but was one of their own people.
But notwithstanding this wicked slander, by which the adversary designed to defame us,
and turn people`'s minds against the truth we held forth,
many in Lincolnshire received the gospel,
being convinced of the Lord`'s everlasting truth,
and sat down therein under the Lord`'s heavenly teaching.

After this I passed, in the Lord`'s power, into Yorkshire, came to Warmsworth,
and went to the steeple-house in the forenoon,^
footnote:[The circumstance of Friends entering the public
places of worship in the times of the Commonwealth,
is one which has been much misunderstood, and greatly misrepresented.
For these acts of dedication they have been calumniated
as disturbers of religious congregations,
and as outraging the peace and order of the churches.
This estimate, doubtless, has been formed with reference to usages of more modern date;
but to decide upon the conduct of Friends in this particular,
from a consideration of present circumstances, would be exceedingly erroneous.
In preaching in the national places of worship,
they did but avail themselves of a common liberty,
in a period of extraordinary excitement on religious things.
There were numerous other religious meetings held in those times,
but into none of these did Friends obtrude themselves.
Some probably will argue,
that the fact of their being so severely punished for persisting in this practice,
may be adduced in support of its irregularity; but it may be answered,
that the preaching of Friends almost everywhere, at that time,
whether in steeple-houses or private houses, in-doors or out of doors,
equally called down the rigour of ecclesiastical vengeance.
It was not, in fact,
because Friends preached in these places so much
as for what they preached that they suffered.
When George Fox was committed to Derby prison in 1650,
after preaching in the steeple-house at "`a great
lecture,`" the mittimus states his offence was,
for "`uttering and broaching of divers blasphemous opinions.`"
In 1659, Gilbert Latey went to Duustan`'s steeple-house in the west,
where the noted Dr. Manton preached.
At the conclusion of the sermon,
Gilbert Latey addressed the assembly relative to some errors in Manton`'s sermon,
for which he was seized by a constable and taken before a magistrate; who, however,
gave G. Latey leave to speak for himself.
The statement he made satisfied the justice, and he replied,
that he had heard the people called Quakers, were a sort of mad, whimsical folks;
"`but,`" said he, "`for this man, he talks very rationally, and I think, for my part,
you should not have brought him before me.`"
To which the constable replied, "`Sir, I think so too.`"
This occurred eleven years after G. Fox first visited a steeple-house, and,
during that time, Friends had suffered very much for speaking in them,
yet now a magistrate declares,
that speaking rationally after the preacher had finished in a steeple-house,
is not an offence for which a man ought to be brought before him.
But the ministry of Friends struck at the very foundation of all hierarchical systems,
and the discovery of this circumstance prompted the
priests to call in the aid of the civil power,
to suppress the promulgation of views so opposed to ecclesiastical domination.]
but they shut the door against me; yet after a while they let in Thomas Aldam,
and then shut it again; and the priest fell upon him, asking him questions.
At last they opened the door, and I went in.
As soon as I was in the priest`'s sight, he discontinued preaching,
though I said nothing to him, and asked me,
"`What have you to say?`" and presently cried out, "`Come, come,
I will prove them false prophets in Matthew;`" but he was so confounded,
he could not find the chapter.
Then he fell on me, asking me many questions, and I stood still all this while,
not saying any thing amongst them.
At last I said, "`Seeing here are so many questions asked, I may answer them.`"
But as soon as I began to speak, the people violently rushed upon me,
and thrust me out of the steeple-house again, and locked the door on me.
As soon as they had done their service, and were come forth, the people ran upon me,
and knocked me sorely with their staves, threw clods and stones at me,
and abused me much; the priest also, being in a great rage,
laid violent hands on me himself.
But I warned them and him of the terrible day of the Lord, and exhorted them to repent,
and turn to Christ.
Being filled with the Lord`'s refreshing power,
I was not sensible of much hurt I had received by their blows.
In the afternoon I went to another steeplehouse,
but the priest had done before I got thither;
so I preached repentance to the people that were left,
and directed them to their inward teacher, Jesus Christ.

From hence I went to Balby, and so to Doncaster,
where I had formerly preached repentance on the market-day;
which had made a noise and alarm in the country.
On the First-day I went to the steeple-house, and after the priest had done,
I spoke to him and the people what the Lord had commanded me;
and they were in a great rage, hurried me out, threw me down,
and haled me before the magistrates.
A long examination they made of me, and much work I had with them.
They threatened my life if ever I came there again;
and that they would leave me to the mercy of the people.
Nevertheless, I declared truth amongst them,
and directed them to the light of Christ in them;
testifying unto them that "`God was come to teach his people himself,
whether they would hear or forbear.`"
After a while they put us out (for some Friends were with me) among the rude multitude,
and they stoned us down the street.
An innkeeper, that was a bailiff, came and took us into his house;
and they broke his head, that the blood ran down his face,
with the stones that they threw at us.
We stayed a while in his house, and showed the more sober people the priest`'s fruits.
Then we went to Balby, about a mile off, and the rude people laid wait for us,
and stoned us down the lane; but, blessed be the Lord, we did not receive much hurt.

The next First-day I went to Tickhill,
whither the Friends of that side gathered together,
and in the meeting a mighty brokenness by the power of God was amongst the people.
I went out of the meeting, being moved of God to go to the steeple-house;
and when I came there,
I found the priest and most of the chief of the parish together in the chancel.
So I went up to them, and began to speak; but they immediately fell upon me;
and the clerk took up his Bible, as I was speaking, and struck me on the face with it,
so that it gushed out with blood, and I bled exceedingly in the steeple-house.
Then the people cried,
"`Let us have him out of the church;`" and when they had got me out,
they beat me exceedingly, and threw me down, and over a hedge;
and afterwards they dragged me through a house into the street,
stoning and beating me as they drew me along,
so that I was besmeared all over with blood and dirt.
They got my hat from me, which I never obtained again.
Yet when I was got upon my legs again, I declared to them the word of life,
and showed them the fruits of their teacher, and how they dishonoured Christianity.
After a while I got into the meeting again amongst Friends;
and the priest and people coming by the house, I went forth with Friends into the yard,
and there I spoke to the priest and people.
The priest scoffed at us, and called us Quakers.
But the Lord`'s power was so over them,
and the word of life was declared in such authority and dread to them,
that the priest began trembling himself; and one of the people said,
"`Look how the priest trembles and shakes, he is turned a Quaker also.`"
When the meeting was over, Friends departed; and I went without my hat to Balby,
about seven or eight miles.
Friends were much abused that day by the priest and his people;
insomuch that some moderate justices hearing of it, two or three of them came,
and sat at the town, to hear and examine the business.
And he that had shed my blood was afraid of having his hand cut off,
for striking me in the church (as they called it); but I forgave him,
and would not appear against him.

In the beginning of this year 1652 great rage got up in priests and people,
and in some of the magistrates of the West-Biding of Yorkshire,
against the truth and Friends;
insomuch that the priest of Warmsworth procured a
warrant from the justices against me and Thomas Aldam,
to be executed in any part of the West-Biding of Yorkshire.
At the same time I had a vision of a bear and two great mastiff dogs;
that I should pass by them, and they should do me no hurt; and it proved so:
for the constable took Thomas Aldam and carried him to York.
I went with Thomas Aldam twenty miles towards York:
and the constable had the warrant for me also, and said, "`he saw me,
but he was loath to trouble men that were strangers;
but Thomas Aldam was his neighbour.`"
So the Lord`'s power restrained him, that he had not power to meddle with me.
We came to Lieutenant Roper`'s, where we had a great meeting of many considerable men;
and the truth was powerfully declared amongst them,
and the Scriptures wonderfully opened,
and the parables and sayings of Christ were expounded,
and the state of the church in the apostles`' days was plainly set forth,
and the apostacy since from that state discovered.
The truth had great dominion that day,
so that those great men that were present did generally confess to it, saying,
"`they believed that this principle must go over the whole world.`"
There were at this meeting James Nayler, Thomas Goodyear,^
footnote:[Thomas Goodyear became a faithful minister,
and suffered much persecution and imprisonment.
'`When in Oxford jail (for refusing to swear), the jailer put irons on his legs,
which being too small hurt him, and besides other abuse,
would not let him and other Friends have straw to lie on.
The jailer also told the other prisoners if they wanted coats,
they might take those of the Friends off their backs;
but one of the prisoners answered he would go naked first.
{footnote-paragraph-split}
Thomas Goodyear was the author of
_A Plain Testimony to the Ancient Truth and Work of God._
He died at Selby, in 1693.]
and William Dewsbury, who had been convinced the year before; and Richard Farnsworth also.
And the constable stayed with Thomas Aldam till the meeting was over,
and then went towards York prison; but did not meddle with me.

From hence I went to Wakefield; and on the First-day after, I went to a steeple-house,
where James Nayler had been a member of an Independent church;
but upon his receiving truth, he was excommunicated.
When I came in, and the priest had done,
the people called upon me to come up to the priest, which I did;
but when I began to declare the word of life to them,
and to lay open the deceit of the priest, they rushed upon me suddenly,
thrust me out at the other door, punching and beating me, and cried,
"`Let us have him to the stocks.`"
But the Lord`'s power restrained them, that they were not suffered to put me in.
So I passed away to the meeting,
where were a great many professors and friendly people gathered,
and a great convincement there was that day;
for the people were mightily satisfied that they were
directed to the Lord`'s teaching in themselves.
Here we got some lodging; for four of us had lain under a hedge the night before,
there being then few Friends in that place.

The same day Richard Farnsworth went to another great steeple-house,
belonging to a high priest, and declared the word of truth unto the people;
and a great service he had amongst them;
for the Lord`'s dread and power was mightily over all.

The priest of that church which James Nayler had been a member of,
whose name was Marshall, raised many wicked slanders about me, as,
"`that I carried bottles with me, and made people drink of them,
which made them follow me;`" and, "`that I rode upon a great black horse,
and was seen in one country upon it in one hour,
and at the same hour in another country threescore miles off;`" and,
"`that I would give a fellow money to follow me, when I was on my black horse.`"
With these lies he fed his people,
to make them think evil of the truth which I had declared amongst them.
But by these lies he preached many of his hearers away from him;
for I was then travelling on foot, and had no horse at that time;
which the people generally knew.
The Lord soon after cut off this envious priest in his wickedness.

After this I came to High-town,
where dwelt a woman who had been convinced a little before.
We went to her house, and had a meeting; and the people gathered together,
and we declared the truth to them, and had some service for the Lord amongst them;
they passed away again peaceably.
But there was a widow woman, named Green, who, being filled with envy,
went to one that was called a gentleman in the town,
(who was reported to have killed two men and one woman,) and informed him against us,
though he was no officer.
The next morning we drew up some queries to be sent to the priest.
When we had done, and were just going away,
some of the friendly people of the town came running up to the house where we were,
and told us that this murdering man had sharpened a pike to stab us,
and was coming up with his sword by his side.
We were just passing away, and so missed him.
But we were no sooner gone, than he came to the house where we had been;
and the people generally concluded if we had not been gone,
he would have murdered some of us.
That night we lay in a wood, and were very wet, for it rained exceedingly.
In the morning I was moved to return to the town,
when they gave us a full relation of this wicked man.

From hence we passed to Bradford, where we met with Richard Farnsworth again,
from whom we had parted a little before.
When we came in, they set meat before us; but as I was going to eat,
the word of the Lord came to me, saying,
"`Eat not the bread of such as have an evil eye.`"
Immediately I arose from the table, and ate nothing.
The woman of the house was a Baptist.
After I had exhorted the family to turn to the Lord Jesus Christ,
and hearken to his teachings in their own hearts, we departed thence.

As we travelled through the country, preaching repentance to the people,
we came into a town on the market-day.
There was a lecture there that day; and I went into the steeple-house,
where were many priests, professors, and people.
The priest that preached, took for his text those words of Jeremiah, chap. 5. ver. 31:
"`My people love to have it so,`" leaving out the foregoing words, viz.,
"`The prophets prophesy falsely, and the priests bear rule by their means.`"
So I showed the people his deceit, and directed them to Christ, the true teacher within;
declaring, "`that God was come to teach his people himself,
and to bring them off from all the world`'s teachers and hirelings,
that they might come to receive freely from him.`"
Then warning them of the day of the Lord, that was coming upon all flesh,
I passed from thence without much opposition.

At night we came to a country place, where there was no public-house near.
The people desired us to stay all night; which we did, and had good service for the Lord,
declaring his truth amongst them.

The next day we passed on; for the Lord had said unto me,
"`If but one man or woman were raised up by his power,
to stand and live in the same Spirit that the prophets and apostles were in,
who gave forth the Scriptures,
that man or woman should shake all the country in their profession for ten miles round.`"
For people had the Scriptures, but were not in that same light, and power, and Spirit,
which they were in that gave forth the Scriptures; and so they neither knew God,
nor Christ, nor the Scriptures aright; nor had they unity one with another,
being out of the power and Spirit of God.
Therefore as we passed along we warned all people, wherever we met them,
of the day of the Lord that was coming upon them.

As we travelled we came near a very great hill, called Pendle-hill,
and I was moved of the Lord to go up to the top of it; which I did with difficulty,
it was so very steep and high.
When I was come to the top, I saw the sea bordering upon Lancashire.
From the top of this hill the Lord let me see in
what places he had a great people to be gathered.
As I went down, I found a spring of water in the side of the hill,
with which I refreshed myself, having eaten or drunk but little for several days before.^
footnote:[The spring here alluded to is called George Fox`'s well to this day.]

At night we came to an inn, and declared truth to the man of the house,
and wrote a paper to the priests and professors, declaring the day of the Lord,
and that Christ was come to teach people himself,
by his power and Spirit in their hearts,
and to bring people off from all the world`'s ways and teachers, to his own free teaching,
who had bought them, and was the Saviour of all them that believed in him.`"
The man of the house spread the paper abroad, and was mightily affected with the truth.
Here the Lord opened unto me,
and let me see a great people in white raiment by a river side, coming to the Lord;
and the place that I saw them in was about Wensleydale and Sedbergh.

The next day we travelled on, and at night got a little fern or brackens to put under us,
and lay upon a common.
Next morning we reached a town, where Richard Parnsworth parted from me;
and then I travelled alone again.
I came up Wensleydale, and at the market-town in that Dale,
there was a lecture on the market-day.
I went into the steeple-house; and after the priest had done,
I proclaimed the day of the Lord to the priest and people,
warning them to turn from darkness to the light, and from the power of Satan unto God,
that they might come to know God and Christ aright, and to receive his teaching,
who teacheth freely.
Largely and freely did I declare the word of life unto them,
and had not much persecution there.
Afterwards I passed up the Dales, warning people to fear God,
and preaching the everlasting gospel to them.
In my way I came to a great house, where was a schoolmaster;
and they got me into the house.
I asked them questions about their religion and worship;
and afterwards I declared the truth to them.
They had me into a parlour, and locked me in,
pretending that I was a young man that was mad, and had run away from my relations;
and that they would keep me till they could send to them.
But I soon convinced them of their mistake, and they let me forth,
and would have had me to stay; but I was not to stay there.
Then having exhorted them to repentance, and directed them to the light of Christ Jesus,
that through it they might come unto him and be saved, I passed from them,
and came in the night to a little ale-house on a common,
where there was a company of rude fellows drinking.
Because I would not drink with them, they struck me with their clubs;
but I reproved them, and brought them to be somewhat cooler;
and then I walked out of the house upon the common in the night.
After some time one of these drunken fellows came out,
and would have come close up to me, pretending to whisper to me;
but I perceived he had a knife; and therefore I kept off him, and bid him repent,
and fear God.
So the Lord by his power preserved me from this wicked man;
and he went into the house again.
The next morning I went on through other Dales,
warning and exhorting people everywhere as I passed, to repent and turn to the Lord:
and several were convinced.
At one house that I came to,
the man of the house (whom I afterwards found to be a
kinsman of John Blakelin`'s) would have given me money,
but I would not receive it.

As I travelled through the Dales, I came to a man`'s house, whose name was Tennant.
I was moved to speak to the family, and declare God`'s everlasting truth to them;
and as I was turning away from them, I was moved to turn again,
and speak to the man himself; and he was convinced, and his family,
and lived and died in the truth.
Thence I came to Major Bousfield`'s, who received me, as did also several others;
and some that were then convinced have stood faithful ever since.
I went also through Grisdale, and several others of those Dales,
in which some were convinced.
And I went into Dent, where many were convinced also.
From Major Bousfield`'s I came to Richard Robinson`'s,
and declared the everlasting truth to him.

The next day I went to a meeting at Justice Benson`'s,
where I met a people that were separated from the public worship.
This was the place I had seen, where a people came forth in white raiment.
A large meeting it was, and the people were generally convinced,
and continue a largo meeting still of Friends near Sedbergh;
which was then first gathered through my ministry in the name of Jesus.

In the same week there was a great fair, at which servants used to be hired;
and I declared the day of the Lord through the fair.
After I had done so, I went into the steeple-house yard,
and many of the people of the fair came thither to me,
and abundance of priests and professors.
There I declared the everlasting truth of the Lord,
and the word of life for several hours,
showing that the Lord was come to teach his people himself,
and to bring them off from all the world`'s ways and teachers, to Christ the true teacher,
and the true way to God.
I laid open their teachers,
showing that they were like them that were of old condemned by the prophets,
and by Christ, and by the apostles.
I exhorted the people to come off from the temples made with hands;
and wait to receive the Spirit of the Lord,
that they might know themselves to be the temples of God.`"
Not one of the priests had power to open his mouth against what I declared:
but at last a captain said,
"`Why will you not go into the church? this is not a fit place to preach in.`"
I told him, I denied their church.
Then stood up one Francis Howgill, who was a preacher to a congregation:
he had not seen me before, yet he undertook to answer that captain,
and soon put him to silence.
Then said Francis Howgill of me,
"`This man speaks with authority, and not as the scribes.`"
After this I opened to the people,
that that ground and house was no holier than another place;
and that that house was not the church, but the people, whom Christ is the head of.
After a while the priests came up to me, and I warned them to repent.
One of them said I was mad, and so they turned away.
But many people were convinced there that day, and were glad to hear the truth declared,
and received it with joy.
Amongst these was one Captain Ward, who received the truth in the love of it,
and lived and died in it.

The next First-day I came to Firbank Chapel, in Westmorland, where Francis Howgill,
before named, and John Audland,^
footnote:[Francis Howgill and John Audland were both religiously inclined,
and were convinced during the present year.
They became eminent ministers, travelling in the gospel,
and suffering fines and imprisonments for its sake, turning many to God.
Howgill, for refusing to swear, was sent to Appleby jail,
the following sentence being passed against him:--"`You are
put out of the king`'s protection and the benefit of the law;
your lands are confiscated to the king during your life,
and your goods and chattels for ever; and you to be a prisoner during your life.`"
He praised God for the many sweet enjoyments and
refreshments he received on his prison bed,
whereon he lay, freely forgiving all.
His end was in great peace, in 1676.
See _Piety Promoted_, i. 64-67.
{footnote-paragraph-split}
Audland also laboured much in the gospel,
for which he suffered persecution and imprisonments.
In his last sickness he was exceedingly filled with high praises to God,
being overcome with a sense of his love and joy.
When he grew weaker he was helped on his knees,
and upon his bed fervently supplicated the Lord on behalf of all his people
that they might be preserved in the truth out of the evil of the world.
See _Piety Promoted_, i. 41-44; and
_Memoirs of F. Howgill,_ by James Backhouse.]
had been preaching in the morning.
The chapel was full of people, so that many could not get in.
Francis Howgill said, he thought I looked into the chapel,
and his spirit was ready to fail, the Lord`'s power did so surprise him;
but I did not look in.
They made haste, and had quickly done, and they and some of the people went to dinner,
but abundance stayed till they came again.
Now John Blakelin and others came to me, and desired me not to reprove them publicly;
for they were not parish teachers, but pretty tender men.
I could not tell them whether I should or not (though I had
not at that time any drawings to declare publicly against them)
but I said they must leave me to the Lord`'s movings.
While the others were gone to dinner, I went to a brook and got a little water;
and then came and sat down on the top of a rock hard by the chapel.
In the afternoon the people gathered about me, with several of their preachers.
It was judged there were above a thousand people;
amongst whom I declared God`'s everlasting truth and word of life freely and largely,
for about the space of three hours, directing all to the Spirit of God in themselves,
that they might be turned from darkness to the light, and believe in it,
that they might become the children of it; and might be turned from the power of Satan,
which they had been under, unto God;
and by the Spirit of truth might be led into all truth,
and sensibly understand the words of the prophets, and of Christ, and of the apostles;
and might all come to know Christ to be their teacher to instruct them,
their counsellor to direct them, their shepherd to feed them,
their bishop to oversee them, and their prophet to open divine mysteries to them;
and might know their bodies to be prepared, sanctified,
and made fit temples for God and Christ to dwell in.
In the openings of heavenly life, I explained unto them the prophets, and the figures,
and shadows, and directed them to Christ, the substance.
Then I opened the parables and sayings of Christ, and things that had been long hid,
showing the intent and scope of the apostles`' writings,
and that their epistles were written to the elect.
When I had opened that state,
I showed also the state of the apostacy since the apostles`' days;
that the priests have got the Scriptures,
but are not in that Spirit which gave them forth,
and have put them into chapter and verse, to make a trade of holy men`'s words;
and that the teachers and priests now are found in the steps of the false prophets,
chief priests, scribes, and Pharisees of old, and are such, as the true prophets, Christ,
and his apostles cried out against,
and so are judged and condemned by the Spirit of the true prophets, and of Christ,
and of his apostles; and that none, who are in that Spirit, and guided by it now,
can own them^
footnote:[If these remarks appear harsh and unqualified, we must bear in mind,
that one of the strongest features of this period was a
time-serving spirit amongst the priesthood;
a trait in the character of too many of them,
which was curiously exhibited by the fact that several veered
round with all the changes of those inconstant times;
being Episcopalians with the first Charles and his bishops;
Presbyterians with Oliver and the Parliament;
again on the side of the Episcopacy at the Restoration;
and probably would have been as ready to unite with the Papists,
if Charles II. had established Popery instead of Protestantism.
Some of these instances are recorded in Neale`'s _History of the Puritans._
After the Restoration of Charles II. so general was the
flood of riotous dissipation spread over the land,
that Bishop Burnet complains of the unworthy lives of many of the clergy;
and states that in Scotland more particularly, their conduct was so flagrantly bad,
that they were even despised by the drunken and licentious troopers, who,
under their orders,
spread rapine and distress throughout the western provinces of that country.
One of their commanders, Sir John Turner,
"`confessed it often went against the grain with him to
serve such a debauched and worthless company,
as the clergy generally were.`"--Burnet`'s _Own Times._]

Now there were many old people, who went into the chapel and looked out at the windows,
thinking it a strange thing to see a man preach on a hill, and not in their church,
as they called it; whereupon I was moved to open to the people, that the steeple-house,
and the ground whereon it stood, were no more holy than that mountain;
and that those temples, which they called the dreadful houses of God,
were not set up by the command of God and of Christ; nor their priests called,
as Aaron`'s priesthood was; nor their tithes appointed by God,
as those amongst the Jews were; but that Christ was come,
who ended both the temple and its worship, and the priests and their tithes;
and that all should now hearken unto him; for he said,
'`Learn of me;`' and God said of him, '`This is my beloved Son, in whom I am well pleased,
hear ye him.`' I declared unto them that the Lord God had sent me to
preach the everlasting gospel and word of life amongst them,
and to bring them off from all these temples, tithes, priests,
and rudiments of the world, which had been instituted since the apostles`' days,
and had been set up by such as had erred from
the Spirit and power the apostles were in.`"
Very largely was I opened at this meeting,
and the Lord`'s convincing power accompanied my ministry,
and reached the hearts of the people, whereby many were convinced;
and all the teachers of that congregation (who were many),
were convinced of God`'s everlasting truth.

After the meeting was over I went to John Audland`'s,
and from thence to Preston-patrick chapel, where a great meeting was appointed;
to which I went,
and had a large opportunity amongst the people to preach the everlasting gospel,
opening to them (as to others on the like occasion),
that the end of my coming into that place was, not to hold it up,
no more than the apostles`' going into the Jewish synagogues and temple was,
to uphold those; but to bring them off from all such things,
as the apostles brought the saints of old from
off the Jewish temple and Aaron`'s priesthood,
that they might come to witness their bodies to be the temples of God,
and Christ in them to be their teacher.

From this place I went to Kendal, where a meeting was appointed in the town-hall;
in which I declared the word of life amongst the people,
showing them how they might come to the saving knowledge of Christ,
and have a right understanding of the Holy Scriptures;
opening to them what it was that would lead them into the way of reconciliation with God,
and what would be their condemnation.`"
After the meeting I stayed a while in the town; several were convinced there,
and many appeared loving.
One, whose name was Cock, met me in the street,
and would have given me a roll of tobacco, for people then were much given to smoking:
I accepted his love, but did not receive the tobacco.

From thence I went to Underbarrow, to one Miles Bateman`'s;
and several people going along with me, great reasonings I had with them,
especially with Edward Burrough.^
footnote:[Edward Burrough was a religious and promising young man,
had left the Episcopal church, for which he had been educated as a minister,
and joined the Presbyterians, with whom he was a preacher of great account.
After several discussions with George Fox, he became fully convinced, and joined Friends,
to the great displeasure of his parents and relatives.
He became a most active and zealous gospel labourer, being both a great writer,
and a powerful and awakening preacher.
In 1662, he was taken from a meeting in London,
and for "`testifying to the name of the Lord Jesus,`" was committed to prison,
where he lay with above 100 of his friends imprisoned on the same account,
being shut up among felons in nasty places, so that, for want of room,
many of them sickened and died.
Amongst these was Edward Burrough, whose sickness increased daily.
He was heard often in prayer, day and night,
not forgetting to intercede for his persecutors.
The morning before he died, he said,
"`Now my soul and spirit is entered into its own being with God,
and this form of person must return from whence it was taken.`"
His works were collected and printed in 1672, and have recently been republished.]
At night the priest and many professors came to the house,
and much disputing I had with them.
Supper being provided for the priest and the rest of the company,
I had not freedom to eat with them, but told them,
if they would appoint a meeting for the next day at the steeple-house,
and acquaint the people with it, I might meet them.
They had a great deal of reasoning about it; some being for it, and some against it.
In the morning I went out, after I had spoken again to them concerning the meeting;
and as I walked upon a bank by the house, there came several poor people, travellers,
asking relief, who I saw were in necessity; and they gave them nothing,
but said they were cheats.
It grieved me to see such hard-heartedness amongst professors; so,
when they were gone in to their breakfast,
I ran after the poor people about a quarter of a mile, and gave them some money.
Meanwhile some of them that were in the house, coming out again,
and seeing me a quarter of a mile off,
said I could not have gone so far in such an instant, if I had not had wings.
Hereupon the meeting was like to have been put by;
for they were filled with such strange thoughts concerning me,
that many of them were against having a meeting with me.
I told them I ran after those poor people to give them some money,
being grieved at their hard-heartedness, who gave them nothing.
Then came Miles and Stephen Hubbersty, who being more simple-hearted men,
would have the meeting held.
So to the chapel I went, and the priest came.
A great meeting there was, and the way of life and salvation was opened;
and after a while the priest fled away.
Many of Crook and Underbarrow were convinced that day, received the word of life,
and stood fast in it under the teaching of Christ Jesus.
After I had declared the truth to them for some hours, and the meeting was ended,
the chief-constable,
and some other professors fell to reasoning with me in the chapel-yard;
whereupon I took a Bible, and opened to them the Scriptures,
and dealt tenderly with them, as one would do with a child.
They that were in the light of Christ, and Spirit of God, knew when I spoke Scripture,
though I did not mention chapter and verse, after the priest`'s form unto them.

From hence I went along with an aged man, whose heart the Lord had opened,
and he invited me to his house; his name was James Dickinson; he was convinced that day,
received the truth, and lived and died in it.

I came the next day to James Taylor`'s, of Newton, in Cartmell, in Lancashire.
And on the First-day of the week I went to the chapel,
where one priest Camelford used to preach;
and after he had done I began to speak the word of life to the people.
But this priest was in such a rage, and was so peevish, that he had no patience to hear;
but stirred up the rude multitude, who haled me out, struck and punched me,
and threw me headlong over a stone wall; yet, blessed be the Lord,
his power preserved me.
He that did this violence to me was a wicked man, one John Knipe,
whom afterwards the Lord cut off.
There was a youth in the chapel, writing after the priest; I was moved to speak to him,
and he came to be convinced, and received a part of the ministry of the gospel;
his name was John Braithwaite.

Then went I up to an ale-house,
to which many people resorted between the time of their morning and afternoon preaching.
I had much reasoning with the people there, declaring to them,
that "`God was come to teach his people himself,
and to bring them off from all false teachers, such as the prophets, Christ,
and the apostles cried against.`"
Many received the word of life at that time, and abode in it.

In the afternoon I went about two or three miles to another steeplehouse or chapel,
called Lyndal.
When the priest had done, I spoke to him and the people what the Lord commanded me;
and there were great opposers; but afterwards they came to be convinced.
After this I went to one Captain Sands,
who with his wife seemed somewhat affected with truth;
and if they could have held the world and truth together they would have received it;
but they were hypocrites, and he a very chaffy light man.
Wherefore I reproved him for his lightness, and for his jesting,
telling him it was not seemly in a great professor, as he was.
He told me he had a son, who upon his death-bed had also reproved him for it,
and warned him of it.
But he neither regarded the admonition of his dying son,
nor the reproofs of God`'s Spirit in himself.

From hence I went to Ulverstone, and so to Swarthmore to Judge Fell`'s;
whither came up one Lampitt, a priest, who was a high notionist.
With him I had much reasoning; for he talked of high notions and perfection,
and thereby deceived the people.
He would have owned me, but I could not own nor join with him, he was so full of filth.
He said, he was above John; and made as though he knew all things.
But I told him, "`Death reigned from Adam to Moses, that he was under death,
and knew not Moses, for Moses saw the paradise of God;
but he knew neither Moses nor the prophets, nor John.`"
For that crooked and rough nature stood in him, and the mountain of sin and corruption;
and the way was not prepared in him for the Lord.
He confessed he had been under a cross in things; but now he could sing psalms,
and do anything: I told him, "`now he could see a thief, and join hand in hand with him,
but he could not preach Moses, nor the prophets, nor John, nor Christ,
except he were in the same Spirit that they were in.`"
Margaret Fell had been absent in the day-time; and at night her children told her,
that priest Lampitt and I had disagreed; which somewhat troubled her,
because she was in profession with him; but he hid his dirty actions from them.
At night we had much reasoning, and I declared the truth to her and her family.
The next day Lampitt came again, and I had much discourse with him before Margaret Fell,
who then clearly discerned the priest.
A convincement of the Lord`'s truth came upon her and her family.
Soon after a day was to be observed for a humiliation,
and Margaret Fell asked me to go with her to the steeple-house at Ulverstone,
for she was not wholly come off from them; I replied,
"`I must do as I am ordered by the Lord.`"
So I left her, and walked into the fields; and the word of the Lord came to me, saying,
"`Go to the steeple-house after them.`"
When I came, Lampitt was singing with his people; but his spirit was so foul,
and the matter they sung so unsuitable to their states, that after they had done singing,
I was moved of the Lord to speak to him and the people.
The word of the Lord to them was, "`He is not a Jew that is one outwardly,
but he is a Jew that is one inwardly, whose praise is not of man, but of God.`"
Then, as the Lord opened further, I showed them,
"`that God was come to teach his people by his Spirit,
and to bring them off from all their old ways, religions, churches, and worships;
for all their religions, worships, and ways, were but talking with other men`'s words;
but they were out of the life and Spirit which they were in who gave them forth.`"
Then cried out one, called Justice Sawrey,
"`Take him away;`" but Judge Fell`'s wife said to the officers,
"`Let him alone, why may not he speak as well as any other?`"
Lampitt also, the priest, in deceit said,
"`Let him speak.`"
So at length, when I had declared some time,
Justice Sawrey caused the constable to put me out;
and then I spoke to the people in the grave-yard.

The First-day after, I was moved to go to Aldenham steeple-house;
and when the priest had done, I spoke to him; but he got away.
Then I declared the word of life to the people, and warned them to turn to the Lord.

From thence I passed to Rampside, where was a chapel,
in which Thomas Lawson used to preach, who was an eminent priest.
He very lovingly acquainted his people in the morning of my coming in the afternoon;
by which means very many people were gathered together.
When I came, I saw there was no place so convenient as the chapel; so I went into it,
and all was quiet.
Thomas Lawson went not up into his pulpit, but left all the time to me.
The everlasting day of the eternal God was proclaimed that day,
and the everlasting truth was largely declared,
which reached and entered into the hearts of people,
and many received the truth in the love of it.
This priest came to be convinced, left his chapel, threw off his preaching for hire,
and came to preach the Lord Jesus and his kingdom freely.
After that some rude people cast scandals upon him,
and thought to have done him a mischief; but he was preserved over all,
grew in the wisdom of God mightily, and proved very serviceable in his place.

I returned to Swarthmore again, and on the next First-day went to Dalton steeple-house;
where, after the priest had done, I declared the word of life to the people,
that they might be turned from darkness to light, and from the power of Satan to God,
and might come off from their superstitious ways, and from their teachers made by man,
to Christ, the true and living way, to be taught of him.

From thence I went into the island of Walney; and after the priest had done,
I spoke to him, but he got away.
Then I declared the truth to the people, but they were rude.
I went to speak with the priest at his house, but he would not be seen.
The people said he went to hide himself in the haymow;
and they went to look for him there, but could not find him.
Then they said he was gone to hide himself in the standing corn,
but they could not find him there either.
I went to James Lancaster`'s, who was convinced in the island;
and thence I returned to SwarthMore,
where the Lord`'s power came upon Margaret Fell and her daughter Sarah,
and several others.

Then I went to Becliff, where Leonard Fell was convinced,
and became a minister of the everlasting gospel.
Several others were convinced there, and came into obedience to the truth.
Here the people said, they could not dispute,
and would fain have put some other to converse with me; but I bid them fear the Lord,
and not in a light way talk of the Lord`'s words, but put the things in practice.
I directed them to the divine light of Christ and his Spirit in their hearts,
which would discover to them all the evil thoughts, words and actions, they had thought,
spoken, and acted; by which light they might see their sin, and also their Saviour,
Christ Jesus, to save them from their sins.
This, I told them, was their first step to peace,
even to stand still in the light that showed them their sins and transgressions;
by which they might come to see how they were in the fall of old Adam,
in darkness and death, strangers to the covenant of promise,
and without God in the world; and by the same light they might see Christ,
that died for them, to be their Redeemer and Saviour, and their way to God.`"

After this I went to a chapel beyond Gleaston, which was built,
but no priest had ever preached in it.
Thither the country people came, and a quiet, peaceable meeting it was,
in which the word of life was declared,
and many were convinced of the truth about Gleaston.

From thence I returned to Swarthmore.
After I had stayed a few days, and most of the family were convinced,
I went again into Westmorland,
where priest Lampitt had been amongst the professors on Kendal side,
and had mightily incensed them against me; telling them I held many strange things;
I met with those he had so incensed, and sat up all night with them at James Dickinson`'s,
and answered all their objections.
They were both thoroughly satisfied with the truth that I had declared,
and dissatisfied with him and his lies,
so that he clearly lost the best of his hearers and followers,
who thus came to see his deceit, and forsook him.

I passed on to John Audland`'s and Gervase Benson`'s,
and had great meetings amongst those people that had been convinced before;
then to John Blakelin`'s^
footnote:[John Blakelin, mentioned elsewhere in this Journal,
became a faithful minister of the gospel, travelling much on truth`'s account,
for which he also suffered imprisonments, and great loss of goods.
He died without sigh or groan, in 1705, aged about 80. He expressed, in his old age,
"`the comfort he had in the Lord`'s peace and presence with him,
that his day`'s work was nigh done, and his reward and rest with God sure.`"
See [.book-title]#Piety Promoted#, ii., 42-46.]
and Richard Robinson`'s, and had mighty meetings there; and so up towards Grisdale.

Soon after, Judge Pell being come home, Margaret Fell his wife sent to me,
desiring me to return thither; and, feeling freedom from the Lord so to do,
I went back to Swarthmore.
I found the priests and professors, and that envious Justice Sawrey,
had much incensed Judge Fell and Captain Sands against the truth by their lies;
but when I came to speak with him, I answered all his objections;
and so thoroughly satisfied him by the Scriptures, that he was convinced in his judgment.
He asked me if I was that George Fox,
whom Justice Robinson spoke so much in commendation of
amongst many of the parliament men.
I told him, I had been with Justice Robinson, and with Justice Hotham in Yorkshire,
who were very civil and loving to me,
and that they were convinced in their judgment by the Spirit of God,
that the principle which I bore testimony to, was the truth,
and they saw over and beyond the priests of the nation; so that they, and many others,
were now come to be wiser than their teachers.
After we had discoursed some time together, Judge Fell himself was satisfied also,
and came to see, by the openings of the Spirit of God in his heart,
over all the priests and teachers of the world,
and did not go to hear them for some years before he died;
for he knew It was the truth that I declared,
and that Christ was the teacher of his people, and their Saviour.
He sometimes wished that I were a while with Judge Bradshaw to discourse with him.
There came to Judge Fell`'s, Captain Sands before-mentioned,
endeavouring to incense the judge against me; for he was an evil-minded man,
and full of envy against me; and yet he could speak high things,
and use the Scripture words, and say, "`Behold, I make all things new.`"
But I told him, then he must have a new God, for his God was his belly.
Besides him, came also that envious justice, John Sawrey.
I told him "`his heart was rotten, and he was full of hypocrisy to the brim.`"
Several other people also came, whose states the Lord gave me a discerning of;
and I spoke to their conditions.
While I was in those parts,
Richard Farnsworth and James Nayler came to see me and the family; and Judge Fell,
being satisfied that it was the way of truth, notwithstanding all their opposition,
suffered the meeting to be kept at his house;
and a great meeting was settled there in the Lord`'s power,
which continued near forty years, until the year 1690,
that a new meeting-house was erected near it.

After I had stayed a while, and the meeting there was well settled,
I went to Underbarrow, where I had a great meeting.
From thence to Kellet, and had a great meeting at Robert Widders`'s,
to which several came from Lancaster, and some from York; and many were convinced there.
On the market-day I went to Lancaster,
and spoke through the market in the dreadful power of God,
declaring the day of the Lord to the people,
and crying out against all their deceitful merchandize.
I preached righteousness and truth unto them, which they should all follow after,
and walk and live in;
directing them how and where they might find and
receive the Spirit of God to guide them thereinto.
After I had cleared myself in the market, I went to my lodging,
whither several people came, and many were convinced,
who have stood faithful to the truth.

On the First-day following, in the forenoon,
I had a great meeting in the street at Lancaster, amongst the soldiers and people,
unto whom I declared the word of life, and the everlasting truth.
I opened unto them, "`that all the traditions they had lived in,
and all their worships and religions, and the profession they made of the Scriptures,
were good for nothing,
while they lived out of the life and power which
they were in who gave forth the Scriptures.
I directed them to the light of Christ, the heavenly Man,
and to the Spirit of God in their own hearts,
that they might come to be acquainted with God and with Christ,
receive him for their teacher, and know his kingdom set up in them.`"

In the afternoon I went to the steeple-house at Lancaster,
and I declared the truth both to the priest and people;
laying open before them the deceits they lived in,
and directing them to the power and Spirit of God, which they wanted.
But they haled me out, and stoned me along the street, till I came to John Lawson`'s house.

Another First-day I went to a steeple-house by the water side,
where one Whitehead was priest, to whom, and to the people,
I declared the truth in the dreadful power of God.
There came to me a doctor, who was so full of envy,
that he said he could find in his heart to run me through with his rapier,
though he should be hung for it the next day;
yet this man came afterwards to be convinced of the truth,
so far as to be loving to Friends.
Some people were convinced thereabouts,
who willingly sat down under the ministry of Christ their teacher:
and a meeting was settled there in the power of God, which has continued to this day.

After this I returned into Westmorland, and spoke through Kendal, on a market-day.
So dreadful was the power of God upon me,
that people flew like chaff before me into their houses.
I warned them of the mighty day of the Lord,
and exhorted them to hearken to the voice of God in their own hearts,
who was now come to teach his people himself.
When some opposed, many others took my part, insomuch,
that at last some of the people fell to fighting about me; but I went and spoke to them,
and they parted again.
Several were convinced.

On the First-day after I had a very large meeting in Underbarrow,
at Miles Bateman`'s house, where I was moved to declare,
"`that all people in the fall were gone from the image of God, righteousness,
and holiness, and were become as wells without the water of life,
as clouds without the heavenly rain, as trees without the heavenly fruit,
and were degenerated into the nature of beasts, and of serpents, and of tall cedars,
and of oaks, and of bulls, and of heifers:
so that they might read the natures of these creatures within,
as the prophet described them to the people of old that were out of truth.
I opened to them how some were in the nature of dogs and swine, biting and rending;
some in the nature of briars, thistles, and thorns;
some like the owls and dragons in the night; some like wild asses and horses,
snuffing up the wind; and some like mountains and rooks, and crooked and rough ways.
Wherefore I exhorted them to read these things within, in their own natures,
as well as without; and that, when they read without of the wandering stars,
they should look within, and see how they wandered from the bright and morning star.
And they should consider, that as the fallow ground in their fields must be ploughed up,
before it would bear seed to them,
so must the fallow ground of their hearts be ploughed up,
before they could bear seed to God.
Now all these names and things I showed them, were spoken of, and to man and woman,
since they fell from the image of God;
but as they come to be renewed again into the image of God,
they come out of the natures of these things, and so out of the names thereof.`"
Many more such things were declared to them, and they were turned to the light of Christ,
by which they might come to know Christ, to receive him,
and to witness him to be their substance and their way, their salvation and true teacher.
Many were convinced at that time.

After I had travelled up and down in those countries, and had had great meetings,
I came to Swarthmore again.
And when I had visited Friends in those parts,
I heard of a great meeting the priests were to have at Ulverstone, on a lecture-day.
I went to it, and into the steeple-house in the dread and power of the Lord.
When the priest had done, I spoke among them the word of the Lord, which was as a hammer,
and as a fire amongst them.
And though Lampitt, the priest of the place,
had been at variance with most of the priests before,
yet against the truth they all joined together.
But the mighty power of the Lord was over all;
and so wonderful was the appearance thereof,
that priest Bennett said "`the church shook,`" insomuch that he was afraid and trembled.
And when he had spoken a few confused words, he hastened out,
for fear it should fall on his head.
Many priests got together there; but they had no power as yet to persecute.

When I had cleared my conscience towards them, I went up to Swarthmore again,
whither came four or five of the priests.
Coming to discourse, I asked them,
"`whether any one of them could say he ever had the word of the Lord to go
and speak to such or such a people?`" None of them durst say he had;
but one of them burst out into a passion, and said,
"`he could speak his experiences as well as I.`" I told him experience was one thing;
but to receive and go with a message, and to have a word from the Lord,
as the prophets and apostles had and did, and as I had done to them,
this was another thing.
And therefore I put it to them again,
"`could any of them say he had ever had a command or word from the
Lord immediately at any time?`" but none of them could say so.
Then I told them, the false prophets, the false apostles, and antichrists,
could use the words of the true prophets, the true apostles, and of Christ,
and would speak of other men`'s experiences,
though they themselves never knew or heard the voice of God or Christ;
and such as they might obtain the good words and experiences of others;
this puzzled them much, and laid them open.
At another time, when I was discoursing with several priests at Judge Fell`'s house,
and he was by, I asked them the same question,
"`whether any of them ever heard the voice of God or Christ,
to bid him go to such and such a people,
to declare his word or message unto them?`" for any one, I told them,
that could but read, might declare the experiences of the prophets and apostles,
which were recorded in the Scriptures.
Hereupon Thomas Taylor,^
footnote:[Thomas Taylor, born in 1616, was educated at Oxford university,
and became a preacher among the Puritans, at or near Skipton, and also at Richmond.
He discontinued preaching for hire, and joined Friends,
becoming a valiant minister of Christ.
He also wrote much in support of the truth.
He suffered many imprisonments, but the Lord was with him,
and upheld him by his mighty power,
in the hardships and opposition he met with for truth`'s sake.
He died in peace at Stafford, in 1681.]
an ancient priest, did ingenuously confess before Judge Fell,
"`that he had never heard the voice of God, nor of Christ, to send him to any people,
but he spoke his experiences, and the experiences of the saints in former ages,
and that he preached.`"
This very much confirmed Judge Fell in the persuasion he had,
"`that the priests were wrong;`" for he had thought formerly,
as the generality of people then did, "`that they were sent from God.`"

Thomas Taylor was convinced at this time, and travelled with me into Westmorland.
Coming to Crossland steeple-house, we found the people gathered together;
and the Lord opened Thomas Taylor`'s mouth (though he was convinced but the day before),
so that he declared amongst them,
"`how he had been before he was convinced;`" and like
the good scribe that was converted to the kingdom,
he brought forth things new and old to the people,
and showed them how "`the priests were out of the way;`" which tormented the priest.
Some little discourse I had with them, but they fled away;
and a precious meeting there was, wherein the Lord`'s power was over all;
and the people were directed to the Spirit of God,
by which they might come to know God and Christ, and to understand the Scriptures aright.
After this I passed on, visiting Friends, and had very large meetings in Westmorland.

Now began the priests to rage more and more, and as much as they could,
to stir up persecution.
James Nayler and Francis Howgill were cast into prison in Appleby jail,
at the instigation of the malicious priests;
some of whom prophesied "`that within a month we should be all scattered again,
and come to nothing.`"
But, blessed for ever be the worthy name of the Lord,
the work of the Lord went on and prospered.
For about this time John Audland, Francis Howgill, John Camm,^
footnote:[John Camm, after joining Friends, became an eminent minister,
travelling in the service of truth.
He was a man of weak constitution,
but richly furnished with the gifts of the Holy Spirit, clear in judgment,
and a sharp reprover of wickedness.
His ministry was deep and weighty.
Having an estate of his own, he suffered the spoiling of his goods joyfully.
He often called his children together, and exhorted them to fear the Lord,
and would wonderfully praise God for his goodness,
counting his bodily weakness a happiness, saying,
"`How great a benefit do I enjoy beyond many,
I have such a large time of preparation for death, being daily dying,
that I may live forever with my God, in that kingdom that is unspeakably full of glory.
My outward man daily wastes and moulders down, and draws towards its place and centre;
but my inward man revives and mounts upwards,
towards its place and habitation in the heavens.`"
See _Piety Promoted_, i., 3-6.]
Edward Burrough, Richard Hubberthorn,^
footnote:[Richard Hubberthorn, who is frequently mentioned in this _Journal,_
and whose name often occurs in the early part of the history of Friends,
became an able gospel minister, and patient sufferer for the truth.
He was a native of Lancashire, the only son of a yeoman of good repute.
In his youth he obtained a post in the Parliamentary army, which,
on his embracing the truth, he quitted, and testified publicly against it;
becoming a valiant soldier under the banner of the Prince of peace.
After passing through many inward probations,
he became qualified to direct others in their way to the kingdom of heaven,
and was one of the first of our Society who travelled in the work of the ministry.
{footnote-paragraph-split}
Richard Hubberthorn was a man of much meekness,
humility, patience, and brotherly kindness, clear in judgment,
and quick of understanding; and, although he was of low stature,
and had au infirm constitution and weak voice, he was a powerful and successful minister,
and great numbers were convinced by him,
and brought over to the faith and practice which he preached.
He travelled in the exercise of his gilt nine years,
and shared at different times in the sufferings to which the early Friends were exposed.
In 1662, he was violently haled from a meeting in London,
and taken before that implacable persecutor, Alderman Brown, who,
after abusing him with his own hands, committed him to Newgate.
Here the throng was so great, and the air so impure, that he soon fell sick.
His disorder increased upon him, and, within two months from the time of his commitment,
with an unclouded prospect of a resting place "`where the
wicked cease from troubling,`" he was released by death.
He wrote many treatises, which were collected and published in 1 vol.
quarto, in 1663.]
Miles Hubbersty, and Miles Halhead,^
footnote:[This is the only mention of Miles Halhead in this Journal.
His name occurs frequently in Sewell`'s _History_,
from which it appears he travelled largely and suffered much on Truth`'s account,
being the first of the Quakers imprisoned at Kendal.]
with several others, being endued with power from on high,
came forth in the work of the ministry,
and approved themselves faithful labourers therein, travelling up and down,
and preaching the gospel freely; by means whereof multitudes were convinced,
and many effectually turned to the Lord.
Amongst these, Christopher Taylor^
footnote:[Christopher Taylor, after writing and preaching much on Truth`'s account,
removed to America about the year 1683, and died at Philadelphia in 1686.
See account of him in Whiting`'s _Memoirs,_ pp.
352-55.]
was one, brother to Thomas Taylor before-mentioned;
and who had been a preacher to a people as well as his brother;
but after they had received a knowledge of the truth,
they soon came into obedience thereunto, and left their preaching for hire or rewards.
And having received a part of the ministry of the gospel, they preached Christ freely;
being often sent by the Lord to declare his word in steeple-houses and in markets;
and great sufferers they were.

After I had visited friends in Westmorland, I returned into Lancashire,
and went to Ulverstone, where W. Lampitt was priest; who,
though he had preached of a people that should own the teachings of God, and had said,
"`that men and women should come to declare the gospel;`" yet afterwards,
when it came to be fulfilled, he persecuted both it and them.
To this priest`'s house I went,
where abundance of priests and professors were got together after their lecture,
with whom I had great disputings concerning Christ and the Scriptures;
for they were loath to let their trade go down, which they made of preaching Christ`'s,
and the apostles`' and prophets`' words.
But the Lord`'s power went over the heads of them all,
and his word of life went forth amongst them;
though many of them were exceedingly envious and devilish.
Yet after this many priests and professors came to me from far and near; of whom,
they that were innocent and simple-minded were satisfied, and went away refreshed;
but the fat and full were fed with judgment, and sent empty away:
for that was the word of the Lord to be divided to them.

Now when meetings were set up, and we met in private houses,
Lampitt the priest began to rage; and he said, "`we forsook the temple,
and went to Jeroboam`'s calves`' houses;`" so that many professors began to
see how he had declined from that which he had formerly held and preached.
Hereupon the case of Jeroboam`'s calves was opened to the professors, priests, and people;
and it was manifested unto them,
"`that their houses (which they called churches)
were more like Jeroboam`'s calves`' houses,
even the old mass-houses which were set up in the darkness of Popery; and which they,
who called themselves Protestants, and professed to be more enlightened than the Papists,
did still hold up; although God had never commanded them: whereas that temple,
which God had commanded at Jerusalem, Christ came to end the service of;
and they that received and believed in him, their bodies came to be the temples of God,
and of Christ, and of the Holy Ghost, to dwell in them, and to walk in them.
And all such were gathered into the name of Jesus, whose name is above every name,
and there is no salvation by any other name under the whole heaven,
but by the name of Jesus.
And they that were thus gathered met together in several dwelling-houses,
which were not called the temple, nor the church;
but their bodies were the temples of God, and the believers were the church,
which Christ was the head of.
So that Christ was not called the head of an old house, which was made by men`'s hands,
neither did he come to purchase and sanctify, and redeem with Iris blood, an old house,
which they called their church, but the people of whom he is the head.`"
Much work I had in those days with priests and people, concerning their old mass-houses,
which they called their churches;
for the priests had persuaded the people that it was the house of God;
whereas the apostle says, "`whose house we are,`" etc.
Heb. 3:6. So the people are God`'s house, in whom he dwells.
And the apostle saith,
"`Christ purchased his church with his own blood;`"
and Christ calls his church his spouse,
his bride, and the Lamb`'s wife; so that this title, church and spouse,
was not given to an old house, but to his people, the true believers.

After this, on a lecture-day, I was moved to go to the steeple-house at Ulverstone,
where were abundance of professors, priests, and people.
I went up near to priest Lampitt, who was blustering on in his preaching;
and after the Lord had opened my mouth to speak,
John Sawrey the justice came to me and said,
"`if I would speak according to the Scriptures, I should speak.`"
I wondered at his speaking so to me, for I did speak according to the Scriptures,
and I told him, "`I should speak according to the Scriptures,
and bring the Scriptures to prove what I had to say;
for I had something to speak to Lampitt and to them.`"
Then he said, I should not speak, contradicting himself who had said just before,
"`I should speak, if I would speak according to the Scriptures.`"
The people were quiet, and heard me gladly,
until this Justice Sawrey (who was the first stirrer up of
cruel persecution in the North) incensed them against me,
and set them on to hale, beat, and bruise me.
Suddenly the people were in a rage,
and fell upon me in the steeple-house before his face; knocked me down, kicked me,
and trampled upon me; and so great was the uproar,
that some tumbled over their seats for fear.
At last he came and took me from the people, led me out of the steeple-house,
and put me into the hands of the constables and other officers,
bidding them whip me and put me out of the town.
They led me about a quarter of a mile, some taking hold of my collar,
and some by my arms and shoulders, and shook and dragged me along.
Many friendly people being come to the market,
and some of them to the steeple-house to hear me, divers of these they knocked down also,
and broke their heads, so that the blood ran down from several of them;
and Judge Pell`'s son running after, to see what they would do with me,
they threw him into a ditch of water, some of them crying,
"`knock the teeth out of his head.`"
Now when they had haled me to the common moss-side, a multitude of people following,
the constables and other officers gave me some blows over my back with their willow-rods,
and so thrust me among the rude multitude, who, having furnished themselves,
some with staves, some with hedge-stakes, and others with holm or holly-bushes,
fell upon me, and beat me on my head, arms, and shoulders,
till they had deprived me of sense; so that I fell down upon the wet common.
When I recovered again, and saw myself lying in a watery common,
and the people standing about me, I lay still a little while;
and the power of the Lord sprang through me, and the Eternal Refreshings refreshed me,
so that I stood up again in the strengthening power of the Eternal God;
and stretching out my arms amongst them, I said with a loud voice,
"`Strike again; here are my arms, my head, and my cheeks.`"
There was in the company a mason, a professor, but a rude fellow;
he with his walking rule-staff gave me a blow with all his might,
just over the back of my hand, as it was stretched out;
with which blow my hand was so bruised, and my arm so benumbed,
that I could not draw it unto me again; so that some of the people cried out,
"`he hath spoiled his hand for ever having the use of it any more.`"
But I looked at it in the love of God (for I was in the love of God to them all,
that had persecuted me), and after a while the Lord`'s power sprang through me again,
and through my hand and arm, so that in a moment I recovered strength in my hand and arm,
in the sight of them all.
Then they began to fall out among themselves,
and some of them came to me, and said, if I would give them money,
they would secure me from the rest.
But I was moved of the Lord to declare to them the word of life,
and showed them their false Christianity, and the fruits of their priest`'s ministry;
telling them they were more like heathens and Jews, than true Christians.
Then was I moved of the Lord to come up again through the midst of the people,
and go into Ulverstone market.
As I went, there met me a soldier, with his sword by his side; "`Sir,`" said he to me,
"`I see you are a man, and I am ashamed and grieved that you should be thus abused;`"
and he offered to assist me in what he could.
But I told him the Lord`'s power was over all;
so I walked through the people in the market,
and none of them had power to touch me then.
But some of the market-people abusing some Friends in the market,
I turned me about and saw this soldier among them with his naked rapier,
whereupon I ran in amongst them, and catching hold of his hand that his rapier was in,
I bid him put up his sword again, if he would go along with me;
for I was willing to draw him out from the company, lest some mischief should be done.
A few days after seven men fell upon this soldier, and beat him cruelly,
because he had taken part with Friends and me;
for it was the manner of the persecutors of that country,
for twenty or forty people to run upon one man.
And they fell so upon Friends in many places, that they could hardly pass the highways,
stoning, beating, and breaking their heads.
When I came to Swarthmore,
I found the friends there dressing the heads and hands of Friends and friendly people,
which had been broken or hurt that day by the professors and hearers of Lampitt,
the priest.
My body and arms were yellow, black, and blue,
with the blows and bruises I received amongst them that day.
Now began the priests to prophesy again,
that within half a year we should be all put down and gone.^
footnote:[The priests reckoned wrong in this, for, as Sewell justly observed,
it fared with the early Friends as with trees, which grow best when most lopped.
"`Duris ut ilex tonsa bipennibus, per damna, per caedes, ab ipso,
ducit opes aninumque ferre.`"
`    "`As by the lopping axe, the sturdy oak
     Improves her shade, and thrives beneath the stroke;
     Tho`' present loss and wounds severe she feel,
     She draws fresh vigour from the invading steel.`" `]
About two weeks after this I went into Walney island, and James Nayler went with me.
We stayed one night at a little town on this side, called Cockan,
and had a meeting there, where one was convinced.
After a while there came a man with a pistol, whereupon the people ran out of doors.
He called for me; and when I came out to him, he snapped his pistol at me,
but it would not go off.
This caused the people to make a great bustle about him;
and some of them took hold of him, to prevent his doing mischief;
but I was moved in the Lord`'s power to speak to him;
and he was so struck by the power of the Lord, that he trembled for fear,
and went and hid himself.
Thus the Lord`'s power came over them all, though there was a great rage in the country.

Next morning I went over in a boat to James Lancaster`'s. As soon as I came to land,
there rushed out about forty men with staves, clubs, and fishing-poles, who fell upon me,
beating and punching me, and endeavouring to thrust me backward into the sea.
When they had thrust me almost into the sea,
and I saw they would have knocked me down in it, I went up into the midst of them;
but they laid at me again, and knocked me down, and stunned me.
When I came to myself,
I looked up and saw James Lancaster`'s wife throwing stones at my face,
and her husband James Lancaster was lying over me,
to keep the blows and the stones off one.
For the people had persuaded James Lancaster`'s wife that I had bewitched her husband;
and had promised her, that if she would let them know when I came thither,
they would be my death.
And having got knowledge of my coming,
many of the town rose up in this manner with clubs and staves to kill me;
but the Lord`'s power preserved me, that they could not take away my life.
At length I got up on my feet, but they beat me down again into the boat;
which James Lancaster observing, he presently came into it,
and set me over the water from them; but while we were on the water within their reach,
they struck at us with long poles, and threw stones after us.
By the time we were come to the other side, we saw them beating James Nayler;
for whilst they had been beating me, he walked up into a field,
and they never minded him till I was gone; then they fell upon him,
and all their cry was, "`Kill him, kill him.`"

When I was come over to the town again, on the other side of the water,
the townsmen rose up with pitchforks, flails, and staves,
to keep me out of the town, crying,
"`Kill him, knock him on the head, bring the cart, and carry him away to the churchyard.`"
So after they had abused me, they drove me some distance out of the town,
and there left me.
Then went James Lancaster back to look after James Nayler; and I being now left alone,
went to a ditch of water, and having washed myself (for they had besmeared my face,
hands, and clothes, with miry dirt), I walked about three miles to Thomas Hutton`'s house,
where lodged Thomas Lawson, the priest that was convinced.
When I came in, I could hardly speak to them, I was so bruised;
only I told them where I left James Nayler; so they took each of them a horse,
and went and brought him thither that night.
The next day Margaret Fell hearing of it, sent a horse for me;
but so sore I was with bruises,
I was not able to bear the shaking of the horse without much pain.
When I was come to Swarthmore, Justice Sawrey, and one Justice Thompson of Lancaster,
granted a warrant against me; but Judge Fell coming home, it was not served upon me;
for he was out of the country all this time, that I was thus cruelly abused.
When he came home, he sent forth warrants into the isle of Walney,
to apprehend all those riotous persons; whereupon some of them fled the country.
James Lancaster`'s wife was afterwards convinced of the truth,
and repented of the evils she had done me;
and so did others of those bitter persecutors also;
but the judgments of God fell upon some of them,
and destruction is come upon many of them since.
Judge Fell asked me to give him a relation of my persecution;
but I told him they could do no otherwise in the spirit wherein they were,
and that they manifested the fruits of their priest`'s ministry,
and their profession and religion to be wrong.
So he told his wife I made light of it,
and that I spoke of it as a man that had not been concerned; for, indeed,
the Lord`'s power healed me again.

After I was recovered, I went to Yelland, where there was a great meeting.
In the evening there came a priest to the house, with a pistol in his hand,
under pretence to light a pipe of tobacco.
The maid of the house seeing the pistol, told her master; who,
clapping his hands on the door-posts, told him he should not come in there.
While he stood there, keeping the door-way, he looked up,
and spied over the wall a company of men coming, some armed with staves,
and one with a musket.
But the Lord God prevented their bloody design; so that seeing themselves discovered,
they went their way, and did no harm.

The time for the sessions at Lancaster being come, I went thither with Judge Fell;
who on the way told me, he had never had such a matter brought before him before,
and he could not well tell what to do in the business.
I told him, when Paul was brought before the rulers,
and the Jews and priests came down to accuse him,
and laid many false things to his charge, Paul stood still all that while.
And when they had done, Festus, the governor, and king Agrippa,
beckoned to him to speak for himself; which Paul did,
and cleared himself of all those false accusations; so he might do with me.
Being come to Lancaster,
Justice Sawrey and Justice Thompson having granted a warrant to apprehend me,
though I was not apprehended by it, yet hearing of it, I appeared at the sessions;
where there appeared against me about forty priests.
These had chosen one Marshall, priest of Lancaster, to be their orator;
and had provided one young priest, and two priests`' sons, to bear witness against me,
who had sworn beforehand that I had spoken blasphemy.
When the justices were sat,
they heard all that the priests and their witnesses could say and charge against me;
their orator Marshall, sitting by, and explaining their sayings for them;
but the witnesses were so confounded,
that they discovered themselves to be false witnesses;
for when the court had examined one of them upon oath, and then began to examine another,
he was at such loss he could not answer directly, but said the other could say it.
Which made the justices say to him, "`have you sworn it,
and given it in already upon your oath,
and now say that he can say it? It seems you did not hear those words spoken yourself,
though you have sworn it.`"

There were then in court several people who had been at that meeting,
wherein the witnesses swore I spoke those blasphemous words,
which the priests accused me of;
and these being men of integrity and reputation in the country,
declared and affirmed in court, that the oath, which the witnesses had taken against me,
was altogether false; and that no such words as they had sworn against me,
were spoken by me at that meeting.
Indeed, most of the serious men of that part of the country,
that were then at the sessions, had been at that meeting,
and had heard me both at that and other meetings also.
This was taken notice of by Colonel West, who, being a justice of the peace,
was then upon the bench; and having long been weak in body, blessed the Lord, and said,
"`the Lord had healed him that day;`" adding,
that he never saw so many sober people and good faces together in all his life.
And then, turning himself to me, he said in the open sessions,
"`George, if thou hast anything to say to the people, thou mayest freely declare it.`"
I was moved of the Lord to speak; and as soon as I began, priest Marshall,
the orator for the rest of the priests, went away.
That which I was moved to declare was this:
"`that the Holy Scriptures were given forth by the Spirit of God,
and all people must first come to the Spirit of God in themselves,
by which they might know God and Christ, of whom the prophets and the apostles learnt;
and by the same Spirit know the Holy Scriptures;
for as the Spirit of God was in them that gave forth the Scriptures,
so the same Spirit of God must be in all them that come to understand the Scriptures;
by which Spirit they might have fellowship with the Son, and with the Father,
and with the Scriptures, and with one another;
and without this Spirit they can know neither God nor Christ, nor the Scriptures,
nor have right fellowship one with another.`"
I had no sooner spoken these words, than about half a dozen priests that stood behind me,
burst out into a passion; and one of them, named Jackus,
amongst other things that he spoke against the truth, said,
that the Spirit and the letter were inseparable.
I replied, "`then every one that hath the letter hath the Spirit;
and they might buy the Spirit with the letter of the Scriptures.`"
This plain discovery of darkness in the priest,
moved Judge Fell and Colonel West to reprove them openly, and tell them,
that according to that position they might carry the Spirit in their pockets,
as they did the Scriptures.
Upon this the priests being confounded and put to silence,
rushed out in a rage against the justices,
because they could not have their bloody ends upon me.
The justices, seeing the witnesses did not agree,
and perceiving that they were brought to answer the priests`' envy,
and finding that all their evidences were not
sufficient in law to make good their charge against me,
discharged me.
And after Judge Fell had spoken to Justice Sawrey and Justice
Thompson concerning the warrant they had given forth against me,
and showed them the errors thereof,
he and Colonel West granted a supersedeas to stop the execution of it.
Thus was I cleared in open sessions of all those lying
accusations which the malicious priests had laid to my charge;
and multitudes of people praised God that day, for it was a joyful day to many.
Justice Benson^
footnote:[Gervase Benson, once a colonel in the army, and, at this date,
a Justice of the peace, appears, from the burial register of Friends,
to have been resident at Kendal.
He died in 1679.
In Barclay`'s Letters, etc, of Early Friends,
is a letter from him to George Fox and James Nayler.
It is dated at London, 11th Month, 29th, 1653.
He appears to have gone up to that city under a sense of duty.
"`Pray to the Lord for me,`" he writes, "`that I may be kept in all faithfulness,
with boldness to bear witness to the truth,
against all deceits as they are made manifest in me,
to the praise of his free grace and love to me, which I find daily flowing into my sold,
to the refreshing thereof.`"]
of Westmorland, was convinced; and Major Ripan, mayor of Lancaster, also.
It was a day of everlasting salvation to hundreds of people; for the Lord Jesus Christ,
the way to the Father, and the free teacher, was exalted and set up,
and his everlasting gospel was preached and the word of
eternal life was declared over the heads of the priests,
and all such money-preachers.
For the Lord opened many mouths that day to speak his word to the priests,
and several friendly people and professors reproved the priests in their inns,
and in the streets; so that they fell, like an old rotten house;
and the cry was among the people, that the Quakers had got the day,
and the priests were fallen.
Many people were convinced that day, amongst whom was Thomas Briggs,
who before had been averse to Friends and truth,
insomuch that discoursing with John Lawson, a Friend, concerning perfection,
Thomas Briggs said to him,
"`dost thou hold perfection?`" at the same time lifting
up his hand to give the Friend a box on the ear.
But this Thomas Briggs, being convinced of the truth that day,
declared against his own priest, Jackus;
and afterwards became a faithful minister of the gospel,
and stood so to the end of his days.^
footnote:[Thomas Briggs, from being a persecutor and an opposer,
became an eminent minister amongst Friends,
and his name occurs frequently in Sewell`'s _History_, and in Whiting`'s _Memoirs,_
to which the reader is referred for some account of his labours.
He was very instrumental in turning men from darkness to light,
and from the power of Satan unto God.
Not only did he suffer personally, by imprisonment and violence,
but was fined five times, for having meetings in his house,
to the extent of 50. He travelled much in Wales, and other places,
often accompanying George Fox.
He went with him to the West Indies in 1671.
A short time before his death, he wrote to George Fox,
in which he signified his perseverance in godliness.
He bore a large testimony the First-day before his decease,
being aged about seventy-five; a minister thirty-two years.]

When the sessions were over, James Nayler, who was present,
gave a brief account of the proceedings in a letter,
which Soon after he wrote to Friends;
and which is here added for the reader`'s further satisfaction in this matter:--

[.small-break]
'''

"`Dear friends and brethren in the Lord Jesus Christ, my dear love unto you all,
desiring you may be kept steadfast in the Lord Jesus Christ,
and in the power of his love, boldly to witness forth the truth,
as it is revealed in you by the mighty working of the Father:
to whom alone be everlasting praise and honour for evermore!
Dear friends, the Lord doth much manifest his love and power in these parts.
On the Second-day of last week, my brother George and I were at Lancaster;
there were abundance of Friends from all parts: and a high sort,
which sided with the priests, giving out,
they now hoped to see a stop put to that great work which had gone on so fast,
and with such power, that their kingdom is much shaken.
We were called before Judge Pell, Colonel West, Justice Sawrey, etc,
to answer what was charged against George.
There were three witnesses to eight particulars,
but they were much confused in themselves; which gave much light to the truth;
whereby the justices did plainly see that it was envy; and they many times told them so.
One of the witnesses was a young priest, who confessed he should not have meddled,
had not another priest sent for him, and set him to work.
The other witnesses were two priests`' sons:
it was proved there by many that heard one of them say,
'`if he had power he would make George deny his profession,
and that he would take away his life.`' This was a single witness to
one of the greatest untruths that was charged against George;
and the justices told him, that they saw, because he could not take away his life,
he went about to take away his liberty.
There was one priest chosen out of the whole number, as an orator to plead against us;
who spared no pains to show forth his envy against the truth:
and when he could not prevail, he went down in a rage;
and there came up a number of them into the room, among whom was one Jackus.
George was then speaking in the room, one of the justices having desired him,
if he had anything to say, he would speak, at which priest Jackus was in such a rage,
that he broke forth into many high expressions against
the truth spoken by my dear brother George;
amongst which this was one that the letter and the Spirit were inseparable.
Hereupon the justices stood np, and bid him prove that, before he went any further.
Then seeing himself caught, he would have denied it; and when he could not get off so,
the rest of the priests would have helped him to a meaning for his words;
but the justices would admit no other meaning than the plain sense of the words,
and told him he had laid down a position, and it was fit he should prove it;
pressing the matter close upon him.
Whereupon the priests, being put to silence, went down in a greater rage than before;
and some of them, after they were gone down, being asked what they had done,
lied and said, they could not get into the room; thereby to hide their shame,
and keep the people in blindness.
The justices, Judge Fell and Colonel West, were much convinced of the truth,
and set up justice and equity; and have much silenced the rage of the people.
Many bitter spirits were at Lancaster to see the event,
but went home and cried the priests had lost the day:
everlasting praises be to him who fought the battle for us, who is our King for ever!
There were others called,
whom the witnesses confessed were in the room when the
things charged on George were said to have been spoken;
but they all, as one man, denied that any such words were spoken;
which gave much light to the justices, and they durst rely on what they witnessed;
for they said they knew many of them to be honest men.
There was a warrant granted against us at Appleby;
but Justice Benson told them it was not according to law, and so it ceased.
I hear he is a faithful man in the truth.
The priests began to preach against the justices, and said,
they were not to meddle in these things,
but to end controversy between neighbour and neighbour.
They are not pleased with the law, because it is not in the statute to imprison us,
as the priest that pleaded against us said.
The justices bid him put it into the statute, if he could; he said,
it should want no will of his.
They are much afraid that they shall lose all; they are much discontented in these parts;
and some of them cry, '`all is gone.`'
Dear Friends, dwell in patience, and wait upon the Lord, who will do his own work.
Look not at man, in the work; nor at man, who opposeth the work;
but rest in the will of the Lord, that so ye may be furnished with patience,
both to do and to suffer what ye shall be called unto;
that your end in all things may be his praise.
Take up his cross freely, which keeps low the fleshly man;
that Christ may be set up and honoured in all things, the light advanced in you,
and the judgment set up,
which must give sentence against all that opposeth the
truth;--that the captivity may be led captive,
and the prisoner set free to seek the Lord;--that righteousness may rule in you,
and peace and joy may dwell in you, wherein consisteth the kingdom of the Father;
to whom be all praise for ever!
Dear Friends, meet often together;
and take heed of what exalteth itself above its brother; but keep low,
and serve one another in love for the Lord`'s sake.
Let all Friends know how it is with us, that God may have the praise of all.`"

[.signed-section-signature]
J+++.+++ N.

[.signed-section-context-close]
Written from Kellet, the 30th of the 8th Month, 1652.

At this time I was in a fast, and was not to eat until this work of God,
which then lay weighty upon me, was accomplished.
But the Lord`'s power was wonderfully exalted,
and gave truth and Friends dominion therein over all, to his glory.
This gospel was freely preached that day, over the heads of about forty hireling priests.
I stayed two or three days afterwards in Lancaster, and had some meetings there;
and the rude and baser sort of people plotted together to draw me out of the house,
and to throw me over Lancaster bridge, but the Lord prevented them.
Then they invented another mischief, which was this:
after a meeting at Lancaster they brought down a distracted man,
and another with him with bundles of birchen rods, bound together like besoms,
with which they would have whipped me:
but I was moved to speak to them in the Lord`'s mighty power,
which chained down the distracted man, and the other also, and made them calm and quiet.
Then I bid him throw his rods into the fire, and burn them; and he did so.
Thus the Lord`'s power being over them, they departed quietly.

But the priests, fretting to see themselves overthrown at the sessions at Lancaster,
got some of the envious justices to join with them; and,
at the following assize at Lancaster, informed Judge Windham against me.
Whereupon the judge made a speech against me in open court; and commanded Colonel West,
who was clerk of the assize, to issue forth a warrant for the apprehending of me:
but Colonel West told the judge of my innocency, and spoke boldly in my defence.
Yet the judge commanded him again, either to write a warrant, or go off from his seat:
then he told the judge plainly that he would not do it;
but that he would offer up all his estate, and his body also, for me.
Thus he stopped the judge; and the Lord`'s power came over all;
so that the priests and justices could not get their envy executed.
That same night I came into Lancaster, it being the assize time,
and hearing of a warrant to he given out against me,
I judged it better to show myself openly, than for my adversaries to seek me.
So I went to Judge Fell`'s and Colonel West`'s chambers.
As soon as I came in they smiled on me; and Colonel West said,
"`What! are you come into the dragon`'s mouth?`" I
stayed in town till the judge went out of town;
and I walked up and down the town, but no one meddled with me, or questioned me.
Thus the Lord`'s blessed power, which is over all,
carried me through and over this exercise, gave dominion over his enemies,
and enabled me to go on in his glorious work and service for his great name`'s sake.
For though the beast maketh war against the saints, yet the Lamb hath got, and will get,
the victory.
