== Chapter VI.

[.chapter-synopsis]
* 1652-1653.
* George Fox is branded by the priests as a witch
* writes to Justice Sawrey, prophesying of the judgments impending over him
* warning to priest Lampitt
* exhortation to the people of Ulverstone
* to the followers of Lampitt, against a hireling ministry, etc.
* a rebuke to Adam Sands for his wickedness
* to priest Tatham, against his hireling ministry and his suing for tithes
* foretells the dissolution of the Long Parliament
* fasts ten days
* James Milner and Richard Myer create a schism, which is soon healed
* the latter is miraculously healed of his lameness, but afterwards disobeys the Lord, and dies not long after
* Anthony Pearson, an opposer, is convinced
* the priests are shown to be Antichrist
* George Fox preaches at John Wilkinson`'s steeple-house three hours
* admonishes a professor for praising him
* reproves Wilkinson for speaking against his conscience
* many hundreds are convinced
* discerns an unclean spirit in a woman, and speaks sharply to her
* the like of some other women
* speaks sharply to an envious Baptist
* preaches in the steeple-house at Carlisle, where the Lord`'s power was such that the people trembled
* committed to Carlisle prison as a blasphemer, heretic, and seducer
* the priests who come to see him are exceedingly rude
* Anthony Pearson`'s remonstrance to the Judges of assize against the unjust imprisonment and detention of George Fox
* he is put in the dungeon, a filthy place, where a woman is found eaten to death with vermin
* here James Parnell visits him
* a challenge to professors to declare their objections to George Fox`'s ministry
* it being reported that George Fox was to die for religion, the Little Parliament write to the sheriff respecting him
* he himself expostulates with Justices Craston and Studholm on their imprisoning him
* A. Pearson and the governor visit the prison, blame the magistrates, require sureties of the jailer, and put the under-jailer in the dungeon for his cruelty to George Fox, who is soon after liberated
* George Fox has great meetings, and thousands are convinced
* visits Gilsland, a noted country for thieving
* has a glorious meeting of many thousands, near Langlands, on the top of a hill
* great convincement in the six northern counties.

From Lancaster I returned to Robert Widders`'s,
and from thence I went to Thomas Leper`'s to a meeting in the evening;
and a very blessed meeting we had there;
after which I walked in the evening to Robert Widders`'s again.
No sooner was I gone than there came a company of disguised men to Thomas Leper`'s,
with swords and pistols; who suddenly entering the house put out the candles,
and swung their swords about amongst the people of the house,
who held up the chairs before them to save themselves from being cut and wounded.
At length they drove all the people out of the house, and then searched it for me; who,
it seems, was the only person they looked for:
for they had laid wait before on the highway,
by which I should have gone had I rode to Robert
Widders`'s. And not meeting with me on the way,
they thought to find me in the house, but the Lord prevented them.
Soon after I was come to Robert Widders`'s,
some friends came from the town where Thomas Leper lived,
and gave us a relation of this wicked attempt:
and they were afraid lest they should come and search Robert Widders`'s house also for me,
and do me a mischief; but the Lord restrained them that they came not.
Though these men were in disguise the friends perceived some of them to be Frenchmen,
and supposed them to be servants belonging to one called Sir Robert Bindlas;
for some of them had said,
that in their nation they used to tie the Protestants to trees,
and whip and destroy them.
His servants used often to abuse Friends, both in their meetings,
and going to and from them.
They once took Richard Hubberthorn and several others out of one,
and carried them a good way off into the fields; and there bound them,
and left them bound in the Winter season.
At another time one of his servants came to Francis Fleming`'s house,
and thrust his naked rapier in at the door and windows;
but there being at the house a kinsman of Francis Fleming`'s, one who was not a Friend,
he came with a cudgel in his hand, and bid the serving-man put up his rapier;
which when the other would not, but vapoured at him with it, and was rude,
he knocked him down with his cudgel, and took his rapier from him;
and had it not been for Friends, he would have run him through with it.
So the Friends preserved the life of him that would have destroyed theirs.

From Robert Widders`'s I went to visit Justice West, Richard Hubberthorn accompanying me.
Not knowing the way, or the danger of the sands, we rode where,
as we were afterwards told, no man ever rode before,
swimming our horses over a very dangerous place.
When we were come in,
Justice West asked us if we did not see two men riding over the sands:
"`I shall have their clothes anon,`" said he,
"`for they cannot escape drowning, and I am the coroner.`"
But when we told him that we were the men, he was astonished,
and wondered how we escaped drowning.
Upon this the envious priests and professors raised a slanderous report concerning me,
that neither water could drown me, nor could they draw blood of me;
and that therefore surely I was a witch; indeed,
sometimes when they beat me with great staves, they did not much draw my blood,
though they bruised my body ofttimes very sorely.
But all these slanders were nothing to me with respect to myself,
though I was concerned on the truth`'s behalf, which, I saw,
they endeavoured by these means to prejudice people against;
for I considered that their forefathers, the apostate Jews,
called the master of the house Beelzebub;
and these apostate Christians from the life and power of God,
could do no less to his seed.
But the Lord`'s power carried me over their slanderous tongues,
and their bloody murderous spirits; who had the ground of witchcraft in themselves,
which kept them from coming to God and to Christ.

[.small-break]
'''

Having visited Justice West, I went to Swarthmore, visiting Friends;
and the Lord`'s power was over all the persecutors there.
I was moved to write several letters to the magistrates, priests, and professors,
thereabouts, who had raised persecution before;
that which I sent to Justice Sawrey was after this manner:--

[.salutation]
"`Friend,

"`Thou wast the first beginner of all the persecution in the North;
thou wast the beginner and the maker of the people tumultuous.
Thou wast the first stirrer of them up against the righteous seed,
and against the truth of God;
the first strengthener of the hands of evil-doers against the innocent and harmless;
and thou shalt not prosper.
Thou wast the first stirrer up of strikers, stoners, persecutors, stockers, mockers,
and imprisoners in the North, and of revilers, slanderers, railers, and false accusers.
This was thy work, and this thou stirredst up! so thy fruits declare thy spirit.
Instead of stirring up the pure mind in people, thou hast stirred up the wicked,
malicious, and envious, and taken hand with the wicked.
Thou hast made the people`'s minds envious up and down the country; this was thy work.
But God hath shortened thy days, and limited thee; hath set thy bounds,
and broken thy jaws; discovered thy religion to the simple and babes,
and brought thy deeds to light.
How is thy habitation fallen, and become the habitation of devils!
How is thy beauty lost, and thy glory withered!
How hast thou showed thy evil, that thou hast served God but with thy lips,
thy heart being far from him, and thou in hypocrisy!
How hath the form of thy teaching declared itself to be the mark of the false prophets,
whose fruit declares itself! for by their fruits they are known.
How are the wise men turned backward!
View thy ways, and take notice with whom thou hast taken part.
That of God in thy conscience will tell thee; the Ancient of Days will reprove thee.
How hath thy zeal appeared to be the blind zeal of a persecutor,
which Christ and his apostles forbade Christians to follow!
How hast thou strengthened the hands of evil-doers, and been a praise to them,
and not to them that do well!
How like a madman and blind man, didst thou turn thy sword backward against the saints,
against whom there is no law!
How wilt thou be gnawed and burned one day,
when thou shalt feel the flame and have the plagues of God poured upon thee,
and thou begin to gnaw thy tongue for pain, because of the plagues!
Thou shalt have thy reward according to thy works.
Thou canst not escape; the Lord`'s righteous judgment will find thee out,
and the witness of God in thy conscience shall answer it.
How hast thou caused the heathen to blaspheme, gone on with the multitude to do evil,
and joined hand and hand with the wicked!
How is thy latter end worse than thy beginning, who art come with the dog to bite,
and art turned as a wolf, to devour the lambs!
How hast thou discovered thyself to be a man
more fit to be kept in a place to be nurtured,
than to be set in a place to nurture!
How wast thou exalted and puffed up with pride! and now art thou fallen down with shame,
that thou comest to be covered with that which thou stirredst up and broughtest forth.
Let not John Sawrey take the words of God into his mouth till he be reformed;
let him not take his name into his mouth till he depart from iniquity;
let not him and his teacher make a profession of the saints`' words,
except they intend to proclaim themselves hypocrites,
whose lives are so contrary to the lives of the saints;
whose church hath made itself manifest to be a cage of unclean birds.
You, having a form of godliness, but not the power,
have made them that are in the power your derision, your by-word,
and talk at your feasts.
Thy ill savour, John Sawrey, the country about have smelled,
and of thy unchristian carriage all that fear God have been ashamed;
and to them thou hast been a grief; in the day of account thou shalt know it,
even in the day of thy condemnation.
Thou wast mounted up, and hadst set thy nest on high,
but never gottest higher than the fowls of the air.
Now thou art run amongst the beasts of prey, and art fallen into the earth;
so that earthliness and covetousness have swallowed thee up.
Thy conceitedness would not carry thee through, in whom was found the selfish principle,
which hath blinded thy eye.
Thy back must be bowed down always; for thy table is already become thy snare.`"

[.signed-section-signature]
G+++.+++ F.

This Justice Sawrey, who was the first persecutor in that country, was afterwards drowned.

[.offset]
I wrote also to William Lampitt, the priest of Ulverstone, thus:--

"`The word of the Lord to thee, O Lampitt! who art a deceiver,
surfeited and drunk with the earthly spirit, rambling up and down in the Scriptures,
and blending thy spirit amongst the saints`' conditions; who hadst a prophecy,
as thy father Balaam had, but art erred from it, as thy father did;
one whose fruit hath withered (of which I am a witness),
and many who have known thy fruit, have seen the end of it, that it is withered,
and do see where thou art in the blind world, a blind leader of the blind;
as a beast wallowing and tumbling in the earth, and in the lust;
one that is erred from the Spirit of the Lord, of old ordained for condemnation.
Thou art in the seat of the Pharisees, art called of men master,
standest praying in the synagogues, and hast the chief seat in the assemblies;
a right hypocrite in the steps of the Pharisees, and in the way of thy fathers,
the hypocrites, which our Lord Jesus Christ cried woe against.
Such with the light thou art seen to be, and by the light art comprehended;
which is thy condemnation, who hatest it, and will be so eternally, except thou repent.
To thee this is the word of God; for in Christ`'s way thou art not, but in the Pharisees'`,
as thou mayest read, Matt.
xxiii., and all that own Christ`'s words may see thee there.
Christ, who died at Jerusalem, cried woe against such as thou art;
and Christ is the same yesterday, to-day, and for ever.
The woe remains upon thee, and from under it thou canst never come, but through judgment,
condemnation, and true repentance.
To thee this is the word of God; to that of God in thy conscience I do speak,
which will witness the truth of what I write, and will condemn thee.
And when thou art in thy torment (though now thou swellest in thy vanity,
and livest in wickedness), remember thou wast warned in thy lifetime.
When the eternal condemnation is stretched over thee,
thou shalt witness this to be the word of the Lord God unto thee;
and if ever thy eye shall see repentance,
thou wilt witness me to have been a friend of thy soul.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
Having thus cleared my conscience to the justice, and to the priest of Ulverstone,
who had raised the first persecution in that country,
it was upon me to send this warning in writing to the people of Ulverstone in general.

"`Consider, O people! who are within the parish of Ulverstone;
I was moved of the Lord to come into your public places to speak among you,
being sent of God to direct your minds to him,
that you might know where you might find your teacher;
that your minds might be staid alone upon God,
and you might not gad abroad without you for a teacher;
for the Lord God alone will teach his people; and he is coming to teach them,
and to gather them from idols`' temples, and from the customary worships,
which all the world is trained up in.
God hath given to every one of you a measure of his Spirit, according to your capacity;
liars, drunkards, whoremongers, and thieves, and who follow filthy pleasures,
you all have this measure in you.
This is the measure of the Spirit of God, that shows you sin, and evil, and deceit;
which lets you see that lying is sin; and theft, drunkenness, and uncleanness,
all to he the works of darkness.
Therefore mind your measure (for nothing that is
unclean shall enter into the kingdom of God),
and prize your time while you have it, lest the time come that you say with sorrow,
we had time, but it is past.
O! why will ye die? why will ye choose your own ways? why will
ye follow the course of the world? and why will ye follow envy,
malice, drunkenness,
and foolish pleasures? know ye not in your consciences that
all these are evil and sin? and that they who act such things,
shall never enter into the kingdom of God? O! that ye would consider,
and see how you have spent your time, and mind how ye do spend it,
and observe whom you serve; for '`the wages of sin is death.`' Do not ye know,
that whatsoever is more than yea and nay, cometh of evil?
O! ye drunkards, who live in drunkenness,
do ye think to escape the fire and the judgment of God? Though ye swell in venom,
and live in lust for a while, yet God will find you out, and bring you to judgment.
Therefore love the light, which Christ hath enlightened you withal, who saith,
'`I am the light of the world,`' and who doth
enlighten every one that cometh into the world.
One loves the light, and brings his works to the light,
and there is no occasion at all of stumbling; the other hates the light,
because his deeds are evil, and the light will reprove him.
Thou that hatest this light, thou hast it; thou knowest that lying drunkenness, swearing,
whoredom, theft, all ungodliness, and all unrighteousness, are evil.
Christ Jesus hath given thee light enough to let thee see these are evil.
This light, if thou lovest it, will teach thee holiness and righteousness,
without which none shall see God; but if thou hatest this light, it is thy condemnation.
Thus are Christ`'s words found to be true, and fulfilled among you;
you that hate this light, set up hirelings, and idols`' temples,
and such priests as bear rule by their means; such shepherds as hold up such things;
who are called of men masters, and have the chiefest place in the assemblies,
whom Christ cried woe against, Matt. 23;
such as go in the way of Cain in envy, and after the error of Balaam for wages,
gifts, and rewards; these have been your teachers; and these you have held up.
But they who love the light, are taught of God;
and the Lord is coming to teach his people himself,
and to gather his own from the hirelings,
and from such as seek for their gain from their quarter,
and from such as bear rule by their means.
The Lord is opening the eyes of people, that they may see such as bear rule over them.
But all, whose eyes are shut, are such as the prophet spoke of,
that '`have eyes and see not,`' but are foolish, upholding such things.
Therefore, poor people, as ye love your own souls,
consider the love of God to your souls, while ye have time,
and do not turn the grace of God into wantonness.
That which shows you ungodliness and worldly lusts, should and would be your teacher,
if ye would hearken to it;
for the saints of old witnessed the grace of God to be their teacher,
which taught them to live soberly and godly in this present world.
Ye that are not sober, this grace of God hath appeared unto you,
but you turn it into wantonness, and so set up teachers,
who are not sober, not holy, not godly.
Here you are left without excuse,
when the righteous judgment of God shall be revealed upon all who live ungodly.
Therefore to the light in you I speak;
and when the book of conscience shall come to be opened,
then shall you witness what I say to be true, and you all shall be judged out of it.
God Almighty direct your minds (such of you especially who love honesty and sincerity),
that you may receive mercy in the time of need.
Your teacher is within you; look not forth; it will teach you both lying in bed,
and going abroad, to shun all occasion of sin and evil.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
As the foregoing was directed to all the inhabitants of Ulverstone in general,
so it was upon me to write also to those more particularly,
that most constantly followed W. Lampitt, the priest.
To these I wrote thus:--

"`The word of the Lord God to all the people that follow priest Lampitt,
who is a blind guide.
Ye are such as are turned from the light of Christ within,
which he hath enlightened you withal;
ye are such as follow that which Christ cried woe against, that go not in Christ`'s way,
but in the Pharisees`' way, as ye may read, Matt. 23,
which our Lord Jesus Christ cried woe against.
He is the same yesterday, to-day, and for ever: but him ye own not,
while ye follow such as he cried woe against; though under a colour ye make a profession,
and Lampitt, your priest, makes a trade of Christ`'s and the saints`' words,
as his fathers, the Pharisees, made a profession of the prophets`' and of Moses`'s words.
"`Woe was unto them who had not the life,
so woe is unto you who have not the life that gave forth the Scriptures,
as your fruits have made manifest.
For when the Lord hath moved some to come amongst you to preach the truth freely,
you have knocked them down, beat, and punched, and haled them out of your assemblies.
Such a people serve thee, O Lampitt, to make a prey upon, and these are thy fruits.
O! let shame, shame, strike thee and you all in the faces,
who make a profession of Christ`'s words, and yet are stoners, and strikers, and mockers,
and scoffers.
Let all see, if this be not a cage of unclean birds, spoken of in the Scriptures,
by those who had the life of the Scriptures.
Such a company of people thou deceivest, and feedest them with thy fancies;
thou makest a trade of the Scriptures, and takest them for thy cloak.
But thou art manifest to all the children of light; for that cloak will not cover thee;
thy skirts are seen, and thy nakedness appears.
The Lord made one to go naked among you, a figure of thy nakedness,
and of your nakedness, and as a sign amongst you, before your destruction cometh;
that you might see that you were naked, and not covered with the truth.
To the light in all your consciences I speak,
which Christ Jesus doth enlighten you withal It will show you the time you have spent,
and all the evil deeds you have done in that time; who follow such a teacher,
that acts contrary to this light, and leads you into the ditch.
When you are in the ditch together, both teacher and people, remember,
ye were warned in your lifetime.
If ever your eye come to see repentance, and you obey the light of Jesus Christ in you,
you will witness me to have been a friend of your souls,
and that I have sought your eternal good, and written this in dear love to you.
Then will you own your condemnation; which you must all own,
before you can come into that blessed life, of which there is no end.
But ye, who hate the light, because your deeds are evil, this light is your condemnation.
O! that ye would love this light, and hearken to it!
It would teach you, both in your daily occupations, and as you lie upon your beds,
and would never let you speak a vain word.
In loving it, you love Christ; in hating it,
you bring condemnation thereof upon yourselves.
To you this is the word of God, from under which you can never pass,
nor ever escape the terror of the Lord, in the state you are in, who hate the light.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
Amongst the chief hearers and followers of this priest Lampitt of Ulverstone,
was one Adam Sands, who was a very wicked, false man,
and would have destroyed truth and its followers if he could.
To him I was moved to write thus:--

[.salutation]
"`Adam Sands,

"`To the light in thy conscience I appeal, thou child of the Devil,
thou enemy of righteousness; the Lord will strike thee down,
though now for a while in thy wickedness thou mayest reign.
The plagues of God are due to thee,
who hardenest thyself in thy wickedness against the pure truth of God.
With the pure truth of God, which thou hast resisted and persecuted,
thou art to be thrashed down, which is eternal, and doth comprehend thee;
and with the light, which thou despisest, thou art seen; and it is thy condemnation.
Thou as one brutish, and thy wife as an hypocrite, and you both as murderers of the just,
in that which is eternal, are seen and comprehended; and your hearts searched, and tried,
and condemned by the light.
The light in thy conscience will witness the truth of what I write to thee;
and will let thee see that thou art not born of God, but art from the truth,
in the beastly nature.
If ever thy eye see repentance, thou wilt witness me a friend of thy soul,
and a seeker of thy eternal good.`"

[.signed-section-signature]
G+++.+++ F.

This Adam Sands afterwards died miserably.

[.offset]
I was moved also to write to priest Tatham.

"`The word of the Lord to thee, priest Tatham,
who art found out of the doctrine of Christ; having the chiefest place in the assembly,
being called of men, master,
and standing praying in the synagogue in the steps of the Pharisees,
which our Lord Jesus Christ cried woe against.
In his way thou art not, but in the way of the scribes and Pharisees,
as thou mayest read, Matt. 23.
There Christ`'s words judge thee, and the Scriptures of truth condemn thee.
For thou art such a one as sues men at the law for tithes,
and yet professest thyself to be a minister of Christ;
which Christ never empowered his to do;
neither did any of his apostles or ministers ever do so.
Here I charge thee in the presence of the living God, to be out of their doctrine;
and that as one of those evil beasts the Scripture speaks of,
thou mindest earthly things, which the life of the Scriptures is against.
Thou art for destruction in the state wherein thou standest;
and it will be thy portion eternally, if thou dost not repent.
To that of God in thy conscience I speak, which will witness the truth of what I say.
Thou goest in Cain`'s way, in envy, an enemy to God, and from the command of God.
Thou goest in Balaam`'s way, from the Spirit of God, for gifts and rewards,
the wages of unrighteousness.
Thou son of Balaam, thou art worse than thy father,
for though he loved the wages of unrighteousness, yet he durst not take them;
but thou not only takest them, but suest men at the law if they will not give them thee,
which no true minister of Jesus Christ ever did; therefore stop thy mouth for ever,
and never make mention of them, or profess thyself one of them.
With the light thou art seen and comprehended, who art light and vain,
and speakest a divination of thy own brain, and deceivest the people.
That in thy conscience will witness what I say, and will condemn thee,
who art one of those that bear rule by their means,
which the Lord sent Jeremiah to cry against, Jer. 5;
and so thou boldest up '`the horrible and filthy thing that is committed in
the land.`' They that do not tremble at the word of the Lord,
are the foolish people that hold thee up; they are sottish children,
and have no understanding; they are wise to do evil, but not to do good,
who are deceived by thee.
Thou art one of those that seek their gain from their quarter; a greedy dumb dog,
that never hath enough, as thy practice makes manifest,
which the Lord sent Isaiah to cry against, Isa. 56:11-12.
And thou art such a one as the Lord sent Ezekiel to cry against,
who feedest of the fat, and clothest with the wool, and makest a prey of the people.
But the Lord is gathering his sheep from thy mouth,
that to thee they shall be a prey no longer.
Thou enemy of God, here this prophecy is fulfilled upon thee, Ezek. 34, and thou art one of them;
I charge it upon thee in the presence of the living God; a hireling thou art,
and they that put not into thy mouth, thou preparest war against them.
Thou hatest the good, and lovest the evil, which the Lord sent Micah to cry against, Mic.
iii. Cover thy lips, and stop thy mouth for ever, thou child of darkness;
for with the light thou art comprehended,
and seen to be among them which the holy men of God cried woe against;
and by the Spirit of the Living God thou art judged.
In the light, which is thy condemnation, thou art comprehended; thy race is seen,
and thy compass known, who art out of the commands of Christ,
and out of the doctrine and life of the apostles.
Thou art proved and tried: to thee this is the word of the Lord,
to thee it shall be as a hammer, a fire, and a sword,
and from under it thou shalt never come, unless thou repent;
who art with the light to be condemned in that state wherein thou standest:
and if ever thy eye see repentance, this thy condemnation thou must own.`"

[.signed-section-signature]
G+++.+++ F.

I wrote also to Burton, priest of Sedbergh, much to the same purpose,
he being in the same evil ground, nature, and practice.
Many other epistles also and papers I wrote about that time,
as the Lord moved me thereunto, which I sent among the priests, professors,
and people of all sorts, for the laying their evil ways open before them,
that they might see and forsake them; and opening the way of truth unto them,
that they might come to walk therein;
which are too many and large to be inserted in this place.

After I had cleared my conscience at that time to the priests and people near Swarthmore,
I went again into Westmorland.
A company of men with pikes and staves laid wait for me at a bridge in the way,
and they met with some Friends, but missed me.
Afterwards they came to the meeting with their pikes and staves:
but Justice Benson being there, and many considerable people besides,
they were prevented from doing the mischief they intended.
So they went away in a great rage, without hurting any one.

I went from the meeting to Grayrigg, and had a meeting there at Alexander Dixon`'s house,
to which the priest (who was a Baptist, and a chapel priest) came to oppose;
but the Lord confounded him by his power.
Some of the priest`'s people tumbled down some
milk-pails which stood upon the side of the house,
which was much crowded; whereupon the priest, after he and his company were gone away,
raised a slander, "`that the Devil frightened him,
and took away a side of the house while he was in the meeting.`"
And though this was a known falsehood,
yet it served the priests and professors to feed on for a while;
and so shameless they were, that they printed and published it.

Another time this priest came to a meeting, and fell to jangling.
First he said, "`the Scriptures were the word of God.`"
I told him they were the words of God, but were not Christ, who is the Word;
and bid him prove by Scripture what he said.
Then he said it was not the Scripture that was the word;
and setting his foot upon the Bible, he said it was but copies bound up together.
Many unsavoury words came from him, but after he was gone we had a blessed meeting,
and the Lord`'s power and presence was preciously manifested and felt amongst us.
Soon after he sent me a challenge to meet me at Kendal.
I sent him word he need not go so far as Kendal, for I would meet him in his own parish.
The hour being fixed, we met, and abundance of rude people gathered together,
besides the baptized people who were his own members;
and they had intended to do mischief, but God prevented them.
When we were met, I declared the day of the Lord to them,
and directed them to Christ Jesus.
Then the priest out with his Bible, and said it was the word of God.
I told him it was the words of God, but not God, the Word.
His answer was, he would prove the Scriptures to be the word before all the people.
I let him go on, having a man there that could take down in writing both what he said,
and what I said.
When he could not prove it (for I kept him to Scripture proof, chapter and verse for it),
the people gnashed their teeth for anger, and said he would have me anon;
but in going about to prove that one error, he ran into many.
And when at length he saw he could not prove it,
then he said he would prove it to be a God: so he toiled himself afresh,
till he perspired again, but could not prove what he had affirmed.
And he and his company were full of wrath;
for I kept his assertions on the head of him and them all,
and told them I owned what the Scriptures said of themselves, namely,
that they were the words of God but Christ was the Word.
So the Lord`'s power came over all, and they being confounded went away.
The Lord disappointed their mischievous intentions against me;
and Friends were established in Christ,
and many of the priest`'s followers saw the folly of their teacher.

After this, priest Bennet, of Cartmel, sent a challenge to dispute with me.
Hereupon I came to his steeple-house on a First-day, and found him preaching.
When he had done, I spoke to him and his people;
but the priest would not stand the trial, but went his way.
After he was gone, I had much discourse with the people;
and when I was come out into the steeple-house yard,
and was discoursing further with the professors, and declaring truth unto them,
one of them set his foot behind me, and two of them ran against my breast,
and threw me down backwards against a grave-stone,
wickedly and maliciously seeking to hurt me; but I got up again,
and was moved of the Lord to speak to them.
Then I went up to the priest`'s house,
and desired him to come forth that I might discourse with him,
seeing he had challenged me; but he would not be seen.
So the Lord`'s power came over them all, which was greatly manifested at that time.
Amongst the priest`'s hearers was one Richard Roper,
one of the bitterest professors the priest had:
he was very fierce and hot in his contention;
but afterwards he came to be convinced of God`'s eternal truth, became a minister thereof,
and continued faithful to his death.

It was now about the beginning of the year 1653, when I returned to Swarthmore;
and going to a meeting at Gleaston, a professor challenged a dispute with me.
I went to the house where he was, and called him to come forth;
but the Lord`'s power was over him, so that he durst not meddle.
Then I departed thence, and visited the meetings of Friends in Lancashire,
and came back to Swarthmore.
Great openings I had from the Lord, not only of divine and spiritual matters,
but also of outward things, relating to the civil government.
For being one day in Swarthmore-hall,
when Judge Fell and Justice Benson were talking of the news,
and of the parliament then sitting, which was called the Long Parliament,
I was moved to tell them,
that before that day two weeks the parliament should be broken up,
and the speaker plucked out of his chair.
And that day two weeks Justice Benson coming thither again, told Judge Fell,
that now he saw George was a true prophet; for Oliver had broken up the parliament.

About this time I was in a fast for about ten days,
my spirit being greatly exercised on truth`'s account;
for James Milner and Richard Myer went out into imaginations,
and a company followed them.
This James Milner and some of his company, had true openings at first;
but getting into pride and exaltation of spirit, they ran out from truth.
I was sent for to them, and was moved of the Lord to go, and show them their outgoings:
and they were brought to see their folly, and condemned it,
and came into the way of truth again.
After some time I went to a meeting at Arn-side, where Richard Myer was,
who had been long lame of one of his arms.
I was moved of the Lord to say unto him, amongst all the people,
"`Stand up on thy legs`" (for he was sitting down): and he stood up,
and stretched out his arm that had been lame a long time, and said,
"`Be it known unto you, all people, that this day I am healed.`"
Yet his parents could hardly believe it; but after the meeting was done,
they had him aside, took off his doublet, and then saw it was true.
He came soon after to Swarthmore meeting,
and then declared how that the Lord had healed him.
Yet after this the Lord commanded him to go to York with a message from him,
but he disobeyed the Lord; and the Lord struck him again,
so that he died about three-quarters of a year after.

Now were great threatenings given forth in Cumberland, that if ever I came there again,
they would take away my life.
When I heard it, I was drawn to go into Cumberland, and went to Miles Wennington`'s,
in the same parish, from which those threatenings came;
but they had not power to touch me.

About this time Anthony Pearson was convinced, who had been an opposer of Friends.^
footnote:[Justice Pearson,
who "`was convinced as he sat on the bench,`" became the author of an approved work,
_The Great Case of Tithes._
A striking letter from him, dated in 1653, respecting his religious state,
is inserted in _Letters of Early Friends_, pages 10-12.]
He came over to Swarthmore; and I being then at Colonel West`'s, they sent for me.
Colonel West said, "`Go, George, for it may be of great service to the man.`"
So I went, and the Lord`'s power reached him.

About this time also the Lord opened several mouths to
declare the truth to priests and people,
so that many were cast into prison.
I went again into Cumberland, and Anthony Pearson and his wife, and several Friends,
went with me to Bootle, where Anthony Pearson left me, and went to Carlisle sessions;
for he was a Justice of the peace in three counties.
On a First-day, I went into the steeple-house at Bootle; and when the priest had done,
I began to speak.
But the people were exceeding rude, and struck and beat me in the yard:
one gave me a very great blow over my wrist,
so that the people thought he had broken my hand to pieces.
The constable was very desirous to keep the peace,
and would have set some of them by the heels that struck me,
if I would have given way to it.
After my service amongst them was over, I went to Joseph Nicolson`'s house,^
footnote:[Joseph Nicholson was one of those who, with his wife,
suffered in the New England persecution, being imprisoned there and laid in irons.
He was also immured within the walls of Dover Castle in 1661.
See Bowden`'s _History of Friends in America_, vol. i., pp. 203-206, and 208, etc.]
and the constable went a little way with us, to keep off the rude multitude.
In the afternoon I went again; and then the priest had got another priest to help him,
that came from London, and was highly accounted of.
Before I went into the steeple-house, I sat a little upon the Cross, and Friends with me;
but the Friends were moved to go into the steeplehouse, and I went in after them.
The London priest was preaching; who gathered up all the Scriptures he could think of,
that spoke of false prophets, and antichrists, and deceivers, and threw them upon us:
but when he had done I recollected all those Scriptures,
and`' brought them back upon himself.
Then the people fell upon me in a rude manner;
but the constable charged them to keep the peace, and so made them quiet again.
Then the priest began to rage, and said I must not speak there:
I told him he had his hour-glass, by which he had preached, and he having done,
the time was free for me, as well as for him, for he was but a stranger there himself.
So I opened the Scriptures to them, and let them see that those Scriptures,
that spoke of the false prophets, and antichrists, and deceivers,
described them and their generation,
and belonged to them who were found walking in their steps,
and bringing forth their fruits; and not unto us, who were not guilty of such things.`"
I manifested to them, that they were out of the steps of the true prophets and apostles;
and showed them clearly, by the fruits and marks,
that it was they of whom those Scriptures spoke, and not we.
And I declared the truth, and the word of life to the people,
and directed them to Christ their teacher.
All was quiet while I was speaking; but when I had done, and was come out,
the priests were both of them in such a rage,
that they foamed at the mouth for auger against me.
The priest of the place made an oration to the people in the steeple-house yard,
and said, "`This man hath gotten all the honest men and women in Lancashire to him;
and now,`" said he, "`he comes here to do the same.`"
Then said I unto him, "`What wilt thou have left? and what have the priests left them,
but such as themselves? For if it be the honest that receive the truth,
and are turned to Christ, then it must be the dishonest that follow thee,
and such as thou art.`"
Some also of the priest`'s people began to plead for their priest, and for tithes;
but I told them it were better for them to plead for Christ,
who had ended the tithing-priesthood and tithes,
and had sent forth his ministers to give freely, as they had received freely.
So the Lord`'s power came over them all, put them to silence,
and restrained the rude people, that they could not do the mischief they intended.
When I came down again to Joseph Nicholson`'s house, I saw a great hole in my coat,
which was cut with a knife, but it was not cut through my doublet,
for the Lord had prevented their mischief.
And the next day a rude wicked man would have done violence to a Friend,
but the Lord`'s power stopped him.

Now was I moved to send James Lancaster to appoint a meeting
at John Wilkinson`'s steeple-house near Cockermouth,
who was a preacher in great repute, and had three parishes under him;
wherefore I stayed at Millom-in-Bootle till he came back again.
In the meantime some of those called the gentry
of the country had formed a plot against me,
and had given a little boy a rapier, to do me a mischief with it.
They came with the boy to Joseph Nicholson`'s house to seek me;
but the Lord had so ordered it, that I was gone into the fields.
They met with James Lancaster, but did not much abuse him;
and not finding me in the house, after a while they went away again.
So I walked up and down in the fields that night,
and did not go to bed as very often I used to do.
The next day we came to the steeple-house,
where James Lancaster had appointed the meeting.
There were at this meeting twelve soldiers and their wives,
who were come thither from Carlisle; and the country people came in,
as if it had been to a fair.
I lay at a house a short distance from the place,
so that many Friends were there before me.
When I came, I found James Lancaster speaking under a yew tree;
which was so full of people that I feared they would break it down.
I looked about for a place to stand upon, to speak to the people;
for they lay all up and down like people at a leaguer.
After I was discovered, a professor came to me, and asked,
if I would not go into the church;
seeing no place convenient to speak to the people from, I told him,
"`Yes;`" whereupon the people rushed in; so that when I came in,
the house and even the pulpit was so full of people, that I had much ado to get in;
and they that could not get in, stood about the walls.
When the people were settled, I stood up on a scat;
and the Lord opened my mouth to declare his everlasting truth, and his everlasting day;
and to lay open all their teachers, their rudiments, traditions, and inventions,
that they had been in, in the night of apostacy since the apostles days.
I turned them to Christ the true teacher, and to the true spiritual worship;
directing them where to find the Spirit and truth, that they might worship God therein.
I opened Christ`'s parables unto them,
and directed them to the Spirit of God in themselves,
that would open the Scriptures unto them.
And I showed them, how all might come to know their Saviour,
and sit under his teaching;--might come to be heirs of the kingdom of God,
and know both the voice of God and of Christ,
by which they might discover all the false shepherds and teachers they had been under;
and be gathered to the true shepherd, priest, bishop, and prophet, Christ Jesus,
whom God commanded all to hear.`"
So when I had largely declared the word of life unto them, for about three hours,
I walked from amongst the people, and they passed away very well satisfied.
Among the rest a professor followed me, praising and commending me;
but his words were like a thistle to me.
At last I turned about, and bid him "`fear the Lord:`" whereupon priest Larkham,
of Cockermouth (for several priests were got together
on the way who came after the meeting was over),
said to me, "`Sir, why do you judge so; you must not judge.`"
But I turned to him and said, "`Friend,
dost not thou discern an exhortation from a judgment? I admonished him to fear God;
and dost thou say I judge him?`" So this priest and I falling into discourse,
I manifested him to be amongst the false prophets and covetous hirelings.
And several people being moved to speak to him,
he and two others of the priests soon got away.
When they were gone, John Wilkinson, who was preacher of that parish,
and of two other parishes in Cumberland,
began to dispute against his own conscience for several hours,
till the people generally turned against him; for he thought to have tired me out,
but the Lord`'s power tired him out, and the Lord`'s truth came over him and them all.
Many hundreds were convinced that day, and received the Lord Jesus Christ,
and his free teaching, with gladness; of whom some have died in the truth,
and many stand faithful witnesses thereof.
The soldiers also were convinced, and their wives, and continued with me till First-day.

On First-day I went to the steeple-house at Cockermouth, where priest Larkham lived.
When he had done, I began to speak, and the people began to be rude;
but the soldiers told them we had broken no law, and they became quiet.
Then I turned to the priest, and laid him open among the false prophets and hirelings;
at which word the priest went his way, and said,
"`He calls me hireling;`" which was true enough, and all the people knew it.
Then some of the great men of the town came to me, and said, "`Sir,
we have no learned men to dispute with you.`"
I told them I came not to dispute, but to show the way of salvation to them,
the way of everlasting life.
I declared largely the way of life and truth, and directed them to Christ their teacher,
who had died for them, and bought them with his blood.

When I had done,
I went about two miles to another great steeplehouse of John Wilkinson`'s, called Brigham;
where the people, having been at the other meeting, were mightily affected,
and would have put my horse into the steeple-house yard; but I said, "`No,
the priest claims that; take him to an inn.`"
When I came into the steeple-house yard, I saw the people coming in great companies,
as to a fair; and abundance were already gathered in the lanes,
and about the steeple-house.
I was very thirsty, and walked about a quarter of a mile to a brook,
where I got some water, and refreshed myself.
As I came up again, I met Wilkinson, who as I passed by him said, "`Sir,
will you preach to-day? If you will,`" said he,
"`I will not oppose you in word or thought.`"
I replied, "`Oppose if thou wilt; I have something to speak to the people.`"
"`And,`" said I, "`thou carriedst thyself foolishly the other day,
and spoke against thy conscience and reason;
insomuch that thy hearers cried out against thee.`"
So I left him, and went on; for he saw it was in vain to oppose,
the people were so affected with the Lord`'s truth.
When I came into the steeplehouse yard, a professor came to me, and asked,
if I would not go into the church, as he called it.
And I seeing no convenient place to stand to speak to the people from, went in,
and stood up on a seat, after they were settled.
The priest came in also, but did not go up to his pulpit.
The Lord opened my mouth, and I declared his everlasting truth,
and word of life to the people; directing them to the Spirit of God in themselves,
by which they might know God and Christ, and the Scriptures,
and come to have heavenly fellowship in the Spirit.
I declared to them, that every one that cometh into the world,
was enlightened by Christ the life; by which light they might see their sins, and Christ,
who was come to save them from their sins, and died for them.
And, if they came to walk in this light,
they might therein see Christ to be the author of their faith, and the finisher thereof;
their Shepherd to feed them, their Priest to teach them,
and their great Prophet to open divine mysteries unto them,
and to be always present with them.
I explained also unto them, in the openings of the Lord, the first covenant,
explaining to them the types, and the substance of those figures;
and so bringing them on to Christ, the new covenant.
I also manifested unto them,
that there had been a night of apostacy since the apostles`' days;
but that now the everlasting gospel was preached again,
which brought life and immortality to light; and the day of the Lord was come,
and Christ was come to teach his people himself by his light, grace, power, and Spirit.`"
A fine opportunity the Lord gave me to preach truth
among the people that day for about three hours;
and all was quiet.
Many hundreds were convinced; and some of them praised God and said,
"`Now we know the first step to peace.`"
The preacher also said privately to some of his hearers,
that I had broken them and overthrown them.

After this I went to a village, and many people accompanied me.
As I was sitting in a house full of people, declaring the word of life unto them,
I cast mine eye upon a woman, and discerned an unclean spirit in her.
And I was moved of the Lord to speak sharply to her,
and told her she was under the influence of an unclean spirit;
whereupon she went out of the room.
Now, I being a stranger there, and knowing nothing of the woman outwardly,
the people wondered at it, and told me afterwards that I had discovered a great thing;
for all the country looked upon her to be a wicked person.
The Lord had given me a spirit of discerning,
by which I many times saw the states and conditions of people,
and could try their spirits.
For not long before, as I was going to a meeting, I saw some women in a field,
and I discerned an evil spirit in them;
and I was moved to go out of my way into the field to them,
and declare unto them their conditions.
At another time there came one into Swarthmore-hall in the meeting time;
and I was moved to speak sharply to her,
and told her she was under the power of an evil spirit;
and the people said afterwards she was generally accounted so.
There came also at another time another woman, and stood at a distance from me,
and I cast mine eye upon her, and said,
"`Thou hast been an harlot;`" for I perfectly saw the condition and life of the woman.
The woman answered and said, many could tell her of her outward sins,
but none could tell her of her inward.
Then I told her her heart was not right before the Lord,
and that from the inward came the outward.
This woman came afterwards to be convinced of God`'s truth, and became a Friend.

From the aforesaid village we came up to Thomas Bewley`'s, near Coldbeck; and from thence,
having had some service for the Lord there, I passed to a town,
where I had a meeting at the Cross; and all was pretty quiet.
When I had declared the truth unto them, and directed them to Christ their teacher,
some received the truth.
We had another meeting upon the borders, in a steeple-house yard,
to which many professors and contenders came; but the Lord`'s power was over all;
and when the word of life had been declared amongst them,
some received the truth there also.

From thence we came to Carlisle, and the pastor of the Baptists,
with most of his hearers, came to me to the abbey, where I had a meeting,
and declared the word of life amongst them; and many of the Baptists,
and of the soldiers, were convinced.
After the meeting, the pastor of the Baptists, a high notionist, and a flashy man,
came to me, and asked me, "`what must be damned;`" I was moved immediately to tell him,
"`that which spoke in him was to be damned.`"
This stopped his mouth; and the witness of God was raised up in him.
I opened to him the states of election and reprobation,
so that lie said he never heard the like in his life.
He also came afterwards to be convinced.

Then I went up to the castle among the soldiers, who beat a drum,
and called the garrison together.
I preached the truth amongst them,
"`directing them to the Lord Jesus Christ to be their teacher,
and to the measure of his Spirit in themselves,
by which they might be turned from darkness to the light,
and from the power of Satan unto God, I warned them all,
that they should do no violence to any man, but should show forth a Christian life;
telling them, that he who was to be their teacher, would be their condemner,
if they were disobedient to him.`"
So I left them, having no opposition from any of them except the Sergeants,
who afterwards came to be convinced.

On the market-day I went up into the market to the market-cross.
Now the magistrates had both threatened and sent their Sergeants;
and the magistrates`' wives had said that if I came there,
they would pluck the hair off my head; and that the Sergeants should take me up.
Nevertheless I obeyed the Lord God, and went upon the Cross,
and there declared unto them,
"`that the day of the Lord was coming upon all their deceitful ways and doings,
and deceitful merchandize; and that they should put away all cozening and cheating,
and keep to yea and nay, and speak the truth one to another;
so the truth and the power of God was set over them.`"
After I had declared the word of life to the people,
the throng being so great that the Sergeants could not get to me,
nor the magistrates`' wives come at me, I passed away quietly.
Many people and soldiers came to me, and some Baptists, that were bitter contenders;
amongst whom one of their deacons, being an envious man,
and finding the Lord`'s power was over them, cried out for very anger.
Whereupon I set my eyes upon him, and spoke sharply to him in the power of the Lord;
and he cried, "`Do not pierce me so with thy eyes; keep thy eyes off me.`"

On the First-day following I went into the steeple-house; and after the priest had done,
I preached the truth to the people, and declared the word of life amongst them.
The priest got away, and the magistrates desired me to go out of the steeple-house.
But I still declared the way of the Lord unto them, and told them,
"`I came to speak the word of life and salvation from the Lord amongst them.`"
The power of the Lord was dreadful amongst them in the steeple-house,
so that the people trembled and shook, and they thought the steeple-house shook;
and some of them feared it would fall down on their heads.
The magistrates`' wives were in a rage, and strove mightily to be at me;
but the soldiers and friendly people stood thick about me.
At length the rude people of the city rose,
and came with staves and stones into the steeple-house,
crying "`Down with these round-headed rogues;`" and they threw stones.
Whereupon the governor sent a file or two of musketeers into the steeple-house,
to appease the tumult, and commanded all the other soldiers out.
So those soldiers took me by the hand in a friendly manner,
and said they would have me along with them.
When we came forth into the street, the city was in an uproar,
and the governor came down;
and some of those soldiers were put in prison for standing by me, and for me,
against the town`'s-people.
A lieutenant, that had been convinced, came, and brought me to his house,
where there was a Baptists`' meeting, and thither came Friends also,
and we had a very quiet meeting; they heard the word of life gladly,
and many received it.
The next day, the justices and magistrates of the town being gathered in the townhall,
they granted a warrant against me, and sent for me to come before them.
I was then gone to a Baptist`'s house; but hearing of it I went up to the hall to them,
where many rude people were; some of whom had sworn strange, false things against me.
I had much discourse with the magistrates,
wherein I laid open the fruits of their priests`' preaching,
and showed them how void they were of Christianity; and that,
though they were such great professors (for they were Independents and
Presbyterians) they were without the possession of that which they professed.
After a large examination they committed me to prison as a blasphemer, a heretic,
and a seducer; though they could not justly charge any such thing against me.
The jail at Carlisle had two jailers, an upper and an under,
who looked like two great bear-wards.
Now when I was brought in, the upper jailer had me up into a great chamber, and told me,
I should have what I would in that room.
But I told him, he should not expect any money from me,
for I would neither lie in any of his beds, nor eat any of his victuals.
Then he put me into another room; where after a while, I got something to lie upon.
There I lay till the assizes came; and then all the talk was, that I was to be hanged.
The high sheriff, whose name was Wilfred Lawson,
stirred them much up to take away my life; and said,
he would guard me to my execution himself.
They were in a great rage, and set three musketeers for a guard upon me;
one at my chamber door, another at the stairs`' foot, and a third at the street door;
and they would let none come at me, except one sometimes,
to bring me some necessary things.
At night they would bring up priests to me, sometimes as late as the tenth hour;
who were exceedingly rude and devilish.
There was a company of bitter Scotch priests, Presbyterians, made up of envy and malice,
who were not fit to speak of the things of God, they were so foul-mouthed; but the Lord,
by his power, gave me dominion over them all,
and I let them see both their fruits and their spirits.
Great ladies also (as they were called) came to see the man that they said was to die.
While both the judge, justices, and sheriff,
were contriving together how they might put me to death,
the Lord disappointed their design by an unexpected way;
for the judge`'s clerk (as I was informed) started a question among them,
which confounded all their counsels;
so that after that they had not power to call me before the judge.

Anthony Pearson being then in Carlisle,
and perceiving that they did not intend to bring me, as was expected, upon my trial,
wrote a letter to the judges, directed as follows:--

[.blurb]
=== To the Judges of Assize and Jail-delivery for the Northern Parts, sitting at Carlisle.

"`You are raised up to do righteousness and justice,
and sent forth to punish him that doth evil, and to encourage him that doth well,
and to set the oppressed free.
I am therefore moved to lay before you the condition of George Fox,
whom the magistrates of this city have cast into prison,
for words that he is accused to have spoken, which they call blasphemy.
He was sent to the jail, till he should be delivered by due course of law;
and it was expected he should have been proceeded
against in the common-law course at this assizes.
The informations against him were delivered into court;
and the act allows and appoints that way of trial.
How hardly and unchristianly he hath been hitherto dealt with, I shall not now mention;
but you may consider, that nothing he is accused of is nice and difficult.
And, to my knowledge, he utterly abhors and detests every particular,
which by the act against blasphemous opinions, is appointed to be punished;
and differs as much from those people against whom the law was made,
as light from darkness.
Though he is committed, judgment is not given against him;
nor have his accusers been face to face,
to affirm before him what they have informed against him;
nor was he heard as to the particulars of their accusations; nor doth it appear,
that any word they charge against him, is within the act.
But, indeed, I could not yet so much as see the information, no, not in court,
though I desired it, both of the clerk of the assizes and of the magistrates`' clerk;
nor hath he had a copy of them.
This is very hard; and that he should be so closely restrained,
that his friends may not speak with him, I know no law nor reason for.
I do therefore claim for him a due and lawful hearing,
and that he may have a copy of his charge, and freedom to answer for himself;
and that rather before you, than to be left to the rulers of this town,
who are not competent judges of blasphemy, as by their mittimus appears;
who have committed him upon an act of parliament,
and mention words as spoken by him at his examination, which are not within the act,
and which he utterly denies.
The words mentioned in the mittimus he denies to have spoken;
and hath neither professed nor avowed them.`"

[.signed-section-signature]
Anthony Pearson.

Notwithstanding this letter,
the judges were resolved not to suffer me to be brought before them;
but reviling and scoffing at me behind my back, left me to the magistrates of the town;
giving them what encouragement they could to exercise their cruelty upon me.
Whereupon (though I had been kept up so close in the jailer`'s
house that Friends were not suffered to visit me,
and Colonel Benson and Justice Pearson were denied to see me, yet) the next day,
after the judges were gone out of town,
an order was sent to the jailer to put me down into the dungeon among the mosstroopers,^
footnote:[Moss-troopers were the remnant of a kind of freebooters,
who infested the borders of England and Scotland in feudal times,
making incursions on each other, less for the purpose of contention in arms,
than for committing depredations on cattle and property.]
thieves, and murderers, which accordingly he did.
A filthy nasty place it was,
where men and women were put together in a very uncivil manner,
and not even a house of convenience to it;
and the prisoners so lousy that one woman was almost eaten to death with lice.
Yet, as bad as the place was, the prisoners were all made very loving and subject to me;
and some of them were convinced of the truth, as the publicans and harlots were of old;
so that they were able to confound any priest, that might come to the grates to dispute.
But the jailer was very cruel,
and the under-jailer very abusive to me and to Friends that came to see me;
for he would beat Friends with a great cudgel,
that did but come to the window to look in upon me.
I could get up to the grate, where sometimes I took in my meat;
at which the jailer was often offended.
One time he came in a great rage, and beat me with a great cudgel,
though I was not at the grate at that time; and as he beat me, he cried,
"`Come out of the window,`" though I was then far enough from it.
While he struck me, I was made to sing in the Lord`'s power;
and that made him rage the more.
Then he fetched a fiddler, and brought him in where I was, and set him to play,
thinking to vex me thereby; but while he played,
I was moved in the everlasting power of the Lord God to sing;
and my voice drowned the noise of the fiddle, and struck and confounded them,
and made them give over fiddling and go their way.

Justice Benson`'s wife was moved of the Lord to come to visit me,
and to eat no meat but what she ate with me at the bars of the dungeon window.
She was afterwards herself imprisoned at York, when she was great with child,
for speaking to a priest; and was kept in prison, and not suffered to go out,
when the time of her travail was come; so she was delivered of her child in the prison.
She was an honest, tender woman, and continued faithful to the truth until she died.

Whilst I was in the dungeon at Carlisle, James Parnell,
a little lad of about sixteen years of age, came to see me, and was convinced:
and the Lord quickly made him a powerful minister of the word of life,
and many were turned to Christ by him, though he lived not long: for,
travelling into Essex, in the work of the ministry, in the year 1655,
he was committed to Colchester castle,
where he endured very great hardships and sufferings;
being put by the cruel jailer into a hole in the castle-wall, called the oven,
so high from the ground, that he went up to it by a ladder;
which being six feet too short,
he was obliged to climb from the ladder to the hole by a rope that was fastened above.
And when Friends would have given him a cord and a basket, to draw up his victuals in,
the inhuman jailer would not suffer them,
but forced him to go down and up by that short ladder and rope, to fetch his victuals,
(which for a long time he did) or else he might Have famished in the hole.
At length, his limbs being much benumbed with lying in that place,
yet being constrained to go down to take up some victuals,
as he came up the ladder again with his victuals in one hand,
and caught at the rope with the other, he missed the rope,
and fell down from a very great height upon the stones;
by which fall he was exceedingly wounded in his head and arms,
and his body was so much bruised, that he died in a short time after.^
footnote:[James Parnell, according to the historian Sewell,
was trained up in the schools of literature.
Though young, he became a valiant soldier of the Lamb;
"`In age a stripling, but in service old;`" and died a true martyr in a dungeon`'s gloom.
Particulars of his barbarous treatment, and consequent death in jail,
may be found in Sewell`'s _History_, vol. i., under date 1655;
and fuller information in his _Life_ by Callaway.
In Barclay`'s _Letters of Early Friends_ is one from James Parnell,
written from Colchester Castle, wherein he says,
"`They have laboured to make my bonds grievous, but my strength the Philistines know not:
I am kept and nourished in the midst of mine enemies; glory be to God the Highest,
who hath counted me worthy to bear the bonds of the gospel.`"]
When he was dead, the wicked professors, to cover their own cruelty, wrote a book of him,
and said, "`he fasted himself to death;`" which was an abominable falsehood,
and was manifested so to be by another book, which was written in answer to that,
and was called "`The Lamb`'s Defence against Lies.`"

Now when I saw that I was not likely to be brought to a public
hearing and trial (although I had before answered,
in writing, the particular matters charged against me,
at the time of my first examination and commitment),
I was moved to send the following paper,
as a public challenge to all those that belied the truth and me behind my back,
to come forth and make good their charge:--

"`If any in Westmorland, or Cumberland, or elsewhere, that profess Christianity,
and pretend to love God and Christ, are not satisfied concerning the things of God,
which I, who am called George Fox, have spoken and declared,
let them declare and publish their dissatisfaction in writing, and not back-bite,
nor lie, nor persecute, in secret:
this I demand of you all in the presence of the living God, as ye will answer it to him.
For the exaltation of the truth, and the confounding of deceit, is this given forth.
To that of God in your consciences I speak;
declare or write your dissatisfaction to any of them, whom you call Quakers,
that truth may be exalted, and all may come to the light,
with which Christ hath enlightened every one that cometh into the world:
that nothing may be hid in darkness, in prisons, holes, or corners,
but that all things may be brought to the light of Christ,
and by the light of Christ may be tried.
This am I moved of the Lord to write,
and send forth to be set upon the marketcrosses in Westmorland, and elsewhere.
To the light of Christ in you I speak,
that none of you may speak evil of the things of God, which you know not;
nor act contrary to the light, that gave forth the Scriptures;
lest you be found fighters against God,
and the hand of the Lord be turned against you.`"

[.signed-section-signature]
G+++.+++ F.

While I thus lay in the dungeon at Carlisle, the report raised at the time of the assize,
"`that I should be put to death,`" was gone far and near;
insomuch that the parliament then sitting, which, I think,
was called the Little Parliament, hearing,
that a young man at Carlisle was to die for religion,
caused a letter to be sent to the sheriff and magistrates concerning me.
About the same time I wrote also to the justices at Carlisle,
that had cast me into prison,
and that persecuted Friends at the instigation of the priests for tithes;
expostulating the matter with them thus:--

[.salutation]
"`Friends, Thomas Craston and Cuthbert Studholm,

"`Your noise is gone up to London before the sober people: what imprisoning,
what gagging,
what havoc and spoiling of the goods of people have you made within these few years!
Unlike men; as though you had never read the Scriptures, or had not minded them!
Is this the end of Carlisle`'s religion? is this the end of your ministry;
and is this the end of your church,
and of your profession of Christianity? you have shamed it by your folly, your madness,
and blind zeal.
Was it not always the work of the blind guides, watchmen, leaders, and false prophets,
to prepare war against them that would not put into their mouths? And have not you
been the priests`' pack-horses and executioners? When they spur you up,
to bear the sword against the just, do not you run on against the creatures,
that cannot hold up such as the Scriptures did always
testify against? Yet will you lift up your unholy hands,
and call upon God with your polluted lips, and pretend a fast,
who are full of strife and debate.
Did your hearts never burn within you? Did you never come to question
your conditions? Are you wholly given up to do the Devil`'s lusts,
to persecute? Where is your loving of enemies? Where is your
entertaining of strangers? Where is your overcoming evil with good?
Where are your teachers that can stop the mouths of gainsayers,
and can convince gainsayers and such as oppose
themselves? Have you no ministers of the Spirit,
no soldiers with spiritual weapons displaying Christ`'s colours?
But all the dragon`'s, the murderer`'s, the persecutor`'s arm of flesh;
Cain`'s weapons, chief priests taking counsel;
Judas and the multitude with swords and staves;
Sodom`'s company raging about Lot`'s house, like the priests and princes against Jeremiah;
like the dragon, beast, and great whore, and the false church, which John saw,
should cast into prison, and kill,
and persecute? Whose weapons are you bearing? doth not the false church, the whore,
make merchandize of cattle, corn, wine, and oil,
even to the very souls of men? And hath not all this been since the
true church went into the wilderness? Read Revelations the 12th,
with the 18th: do you not read and see what a spirit you are of,
and what a bottomless pit you are in? And have not you dishonoured the place
of justice and authority? What! turned your sword backward like madmen,
who are a praise to the evil-doer, and would be a terror to the good,
with all force and might to stop the way of justice!
Doth not the Lord, think you,
behold your actions? How many have you wronged?
how many have you imprisoned and persecuted,
and put out of your synagogues?
Are you they that must fulfil the prophecy of Christ, Matt. 23. John 16?
Read the Scriptures, and see how unlike you are to the prophets, Christ,
and his apostles; and what a visage you have,
like unto them that persecuted the prophets, Christ and the apostles.
You are found in their steps, wrestling with flesh and blood,
and not with principalities, and powers, and spiritual wickedness,
and your teachers imprisoning and persecuting for outward things,
you being their executioners; the like whereof hath not been in all the nations.
The havoc that hath been made, the spoiling of the goods of people,
taking away their oxen and fatted beeves, their sheep, corn, wool, and household goods,
and giving them to the priests, that have done no work for them;
more like moss-troopers than ministers of the gospel, they take them from Friends;
sueing them in your courts, and fining them,
because they will not break the commands of Christ; that is, because they will not swear.
Thus you act against them that do not lift up a hand against you;
and as much as you turn against them, you turn against Christ.
But he is risen that will plead their cause, and you cannot be hid;
for your works are come to light, and the end of your ministry is seen,
what it is for--for means.
You have dishonoured the truth, the gospel,
and are they that make it chargeable? You have lost your glory.
You have dishonoured yourselves.
Persecution was ever blind and mad.
Read the apostle, what he saith of himself, when he was in your nature.
Exaltation and pride, and your lifting up yourselves, hath brought you to this;
not being humble, not doing justice, not loving mercy.
When such as have been beaten and bruised by your rude company,
to whom you are a praise and encouragement, have come, and laid things before you,
that you might do justice, preserve and keep peace, you, knowing they could not swear,
have put an oath to them.
This hath been your trick and cover, that ye might not do justice to the just;
but by this means you have gone on still further to encourage the evil-doer.
But the Lord sees your hearts!
If ye were not men past feeling,
ye would fear and tremble before the God of the whole earth, who is risen,
and will stain your glory, mar your pride, deface your beauty, and lay it in the dust.
Though for a time you may swell in your pride, glory in your shame,
and make a mock of God`'s messengers, who, for reproving sin in the gate,
are become your prey, you will feel the heavy hand of God, and his judgments at the last.
This is from a lover of the truth, and of righteousness, and of your souls;
but a witness against all such as make a trade of the prophets'`, Christ`'s,
and the apostles`' words,
and are found in the steps of them that persecuted the prophets'`, Christ`'s,
and the apostles`' life; who will persecute them, that will not hold you up,
and put into your mouths, and give you means.
Tithes were before the law, and tithes were in the law; but tithes,
since the days of the apostles, have been only since the false church got up.
Now Christ, who is come to end the law, and to end war,
redeems men out of the tenths and out of the nines also.
The redeemed of the Lord shall reign upon the earth,
and know the election which was before the world began.
Since the days of the apostles, tithes have been set up by the Papists,
and by them that went forth from the apostles into the world;
so set up by the false church, that made merchandize of people,
since the true church went into the wilderness.
But now is the judgment of the great whore come, and the beast and false prophet,
the old dragon, shall be taken and cast into the fire,
and the Lamb and his saints shall have the victory.
Now is Christ come, who will make war in righteousness,
and destroy with the sword of his mouth all these inventors and inventions,
that have got up, and been set up since the days of the apostles,
and since the true church went into the wilderness.
And the everlasting gospel, which is the power of God,
shall be preached again to all nations, and kindreds, and tongues,
in this the Lamb`'s day, before whom you shall appear to judgment.
You have no way to escape.
For he hath appeared, who is '`the first and the last, the beginning and the ending,
the Alpha and the Omega; he that was dead, is alive again, and lives for evermore!`'`"

[.offset]
I mentioned before, that Gervase Benson and Anthony Pearson,
though they had been justices of the peace,
were not permitted to come to me in the prison;
whereupon they jointly wrote a letter to the magistrates, priests,
and people at Carlisle, concerning my imprisonment; which was thus:--

"`Him, who is called George Fox, who is persecuted by rulers and magistrates,
by justices, by priests, and by people,
and who suffers imprisonment of his body at this present, as a blasphemer, and a heretic,
and a seducer, him do we witness, who in measure are made partakers of the same life,
that lives in him, to be a minister of the eternal word of God,
by whom the everlasting gospel is preached;
by the powerful preaching whereof the eternal
Father of the saints hath opened the blind eyes,
hath unstopped the deaf ears, hath let the oppressed go free,
and hath raised up the dead out of the graves.
Christ is now preached in and among the saints, the same that ever he was;
and because his heavenly image is borne up in this his faithful servant,
therefore doth fallen man (rulers, priests, and people) persecute him.
Because he lives up out of the fall, and testifies against the works of the world,
that the deeds thereof are evil he suffers by you magistrates; not as an evil-doer.
For thus it was ever, where the seed of God was kept in prison under the cursed nature,
that nature sought to imprison them in whom it was raised.
The Lord will make him to you as a burthensome stone;
for the sword of the Spirit of the Almighty is put into the hands of the saints,
which shall wound all the wicked,
and shall not be put up till it hath cut down all corrupt judges, justices, magistrates,
priests, and professors; till he hath brought his wonderful thing to pass in the earth;
which is to make new heavens and a new earth, wherein shall dwell righteousness;
which now he is about to do.
Therefore fear the Lord God Almighty, ye judges, justices, commanders, priests,
and people; ye that forget God, suddenly will the Lord come,
and destroy you with an utter destruction, and will sweep your names out of the earth,
and will restore his people judges, as at the first, and counsellors,
as at the beginning.
And all persecutors shall partake of the plagues of the whore,
who hath made the kings of the earth and the great men
drunk with the wine of her fornications,
and hath drunk the blood of the saints;
and therefore shall you be partakers of her plagues.
We are not suffered to see our friend in prison,
whom we witness to be a messenger of the living God.
Now, all people, consider whether this be according to law, or from the wicked, perverse,
envious will of the envious rulers and magistrates,
who are of the same generation that persecuted Jesus Christ; for, said he,
'`as they have done to me, so will they do to you.`'
And as he took the love, the kindness,
and service that was showed and performed to any of his
afflicted ones in their sufferings and distress,
as done unto himself,
so the injuries and wrongs that were done by any to any of his little ones, he resented,
as done unto himself also.
Therefore you, who are so far from visiting him yourselves in his suffering servant,
that ye will not suffer his brethren to visit him, ye must depart,
ye workers of iniquity, into the lake that burns with fire.
The Lord is coming to thrash the mountains, and will beat them to dust;
and all corrupt rulers, corrupt officers, and corrupt laws,
the Lord will take vengeance on,
by which the tender consciences of his people are oppressed.
He will give his people his law, and will judge his people himself,
not according to the sight of the eye, and hearing of the ear, but with righteousness,
and with equity.
Now are your hearts made manifest to be full of envy against the living truth of God,
which is made manifest in his people, who are contemned and despised of the world,
and scornfully called Quakers.
You are worse than the heathens, that put Paul in prison,
for none of his friends or acquaintance were hindered to come to him by them;
therefore they shall be witnesses against you.
Ye are made manifest to the saints,
to be of the same generation that put Christ to death,
and that put the apostles in prison on the same pretence that you act under,
in calling truth error, and the ministers of God blasphemers, as they did.
But the day is dreadful and terrible, that shall come upon you, ye evil magistrates,
priests, and people, who profess the truth in words outwardly,
and yet persecute the power of truth, and them that stand in and for the truth.
While ye have time prize it, and remember what is written Isa. 54:17.`"

[.signed-section-signature]
Gervase Benson.

[.signed-section-signature]
Anthony Pearson.

Not long after this, the Lord`'s power came over the justices,
and they were made to set me at liberty.
But some time previous, the governor, and Anthony Pearson,
came down into the dungeon to see the place where I was kept,
and understand what usage I had.
They found the place so bad, and the savour so ill,
that they cried shame on the magistrates for suffering the jailer to do such things.
They called for the jailers into the dungeon,
and required them to find sureties for their good behaviour; and the under-jailer,
who had been such a cruel fellow, they put into the dungeon with me,
amongst the moss-troopers.

After I was set at liberty, I went to Thomas Bewley`'s,
where came a Baptist teacher to oppose me; but he was convinced.
Robert Widders being with me, was moved to go to Coldbeck steeple-house,
and the Baptist teacher went along with him the same day.
The people fell upon them, and almost killed Robert Widders;
and took the Baptist`'s sword from him, and beat him sorely.
This Baptist had the inheritance of an impropriation of tithes; and he went home,
and gave it up freely.
Robert Widders was sent to Carlisle jail, where having lain a while,
he was set at liberty again.^
footnote:[Robert Widders is often mentioned in this Journal,
having travelled with George Fox in Scotland, as also in many parts of America.
They went through great perils by sea and land, in the wilderness and in woods,
in danger of wild beasts; yet, through all the Lord supported him,
and kept him faithful to the end.
He was valiant for God`'s truth, establishing many in the faith.
He was a great sufferer from persecutors; once, at Coldbeck,
he was thrown down on the ground, and kicked and beaten so cruelly,
that blood gushed out of his mouth, and he was supposed to be dead.
At Lamplugh, his clothes were torn on his back, and the hair from off his head; and,
at Bishop-Auckland, he was stoned and sorely bruised.
His cattle, corn, and household goods were also swept away by wholesale,
yet he was not at all dejected or concerned, knowing well for what he suffered.
He was much resigned during his last sickness, i often saying on his death-bed,
"`his heart was filled with the love of God;`"
and he departed this life in great peace in 1686,
aged sixty-eight years.]
William Dewsbury also went to another steeple-house hard by,
and the people almost killed him, they beat him so; but the Lord`'s power was over all,
and healed him again.
In that day many Friends went to the steeplehouses,
to declare the truth to the priests and people, and great sufferings they underwent;
but the Lord`'s power sustained them.

Now I went into the country, and had mighty great meetings.
The everlasting gospel and word of life flourished,
and thousands were turned to tile Lord Jesus Christ, and to his teaching.
Several that had taken tithes, as impropriators, denied the receiving of them any longer,
and delivered them up freely to the parishioners.
Passing on into Westmorland, I had many great meetings.
At Strickland-head I had a large meeting, where a justice of peace out of Bishoprick,
whose name was Henry Draper, came, and many contenders were there.
The priests and magistrates were in a great rage against me in Westmorland,
and had a warrant to apprehend me, which they renewed from time to time, for a long time;
yet the Lord did not suffer them to serve it upon me.
I travelled on amongst Friends, visiting the meetings till I came to Swarthmore,
where I heard that the Baptists and professors
in Scotland had sent to have a dispute with me.
I sent them word, that I would meet them in Cumberland, at '`Thomas Bewley`'s house,
whither accordingly I went, but none of them came.
Some dangers at this time I underwent in my travels; for at one time,
as we were passing from a meeting, and going through Wigton on a market-day,
the people of the town had set a guard with pitch-forks;
and although some of their own neighbours were with us, they kept us out of the town,
and would not let us pass through it, under the pretence of preventing the sickness;
though there was no occasion for any such thing.
However, they fell upon us, and had like to have spoiled us and our horses;
but the Lord restrained them, that they did not much hurt; and we passed away.
Another time, as I was passing between two Friends`' houses,
some rude fellows lay in wait in a lane, and exceedingly stoned and abused us;
but at last, through the Lord`'s assistance, we got through them, and had not much hurt.
But this showed the fruits of the priest`'s teaching,
which shamed their profession of Christianity.

After I had visited Friends in that county, I went through the county into Durham,
having large meetings by the way.
A very large one I had at Anthony Pearson`'s, where many were convinced.
From thence I passed through Northumberland to Derwent-water,
where there were great meetings; and the priests threatened that they would come,
but none came.
The everlasting word of life was freely preached, and freely received;
and many hundreds were turned to Christ, their teacher.

In Northumberland many came to dispute, of whom some pleaded against perfection;
unto whom I declared, "`that Adam and Eve were perfect before they fell;
and all that God made was perfect; and that the imperfection came by the Devil,
and the fall; but Christ, that came to destroy the Devil, said,
'`Be ye perfect.`'`" One of the professors alleged that Job said,
"`Shall mortal man be more pure than his Maker? The heavens are not clean in his sight.
God charged his angels with folly.`"
But I showed him his mistake, and let him see, "`that it was not Job that said so,
but one of those that contended against Job; for Job stood for perfection,
and held his integrity; and they were called miserable comforters.`"
Then these professors said, the outward body was the body of death and sin.
I showed them their mistake in that also;
for "`Adam and Eve had each of them an outward body,
before the body of death and sin got into them; and that man and woman will have bodies,
when the body of sin and death is put off again;
when they are renewed up into the image of God again by Christ Jesus,
which they were in before they fell.`"
So they ceased at that time from opposing further;
and glorious meetings we had in the Lord`'s power.

Then we passed on to Hexham, where we had a great meeting at the top of a hill.
The priest threatened he would come, and oppose us, but he came not;
so that all was quiet; and the everlasting day,
and renowned truth of the everliving God was sounded over those dark countries,
and his Son exalted over all.
It was proclaimed amongst the people that "`the day was now come,
wherein all that made a profession of the Son of God, might receive him;
and that to as many as would receive him, he would give power to become the sons of God,
as he had done to me.`"
And it was further declared, that "`he that had the Son of God, had life eternal;
but that he that had not the Son of God (though he professed all the Scriptures,
from the first of Genesis to the last of the Revelations), had not life.`"
After all were directed to the light of Christ,
by which they might see him and receive him, and know where their true teacher was;
and the everlasting truth had been largely declared amongst them,
we passed away through Hexham peaceably, and came to Gilsland,
a country noted for thieving.

Here a Friend seeing the priest, went to speak to him;
whereupon the latter came down to our inn, and the town`'s-people gathered about us.
The priest said, he would prove us deceivers out of the Bible,
but could find no Scripture for his purpose.
Then he went into the inn; and after a while came out again,
and brought some broken sentences of Scripture,
that mention "`the doctrines and commandments of men, etc, and, touch not, taste not,
etc, for they perish with the using.`"
All which, poor man! was his own condition; whereas we were persecuted,
because we would not taste, nor touch, nor handle their doctrines and traditions,
which we knew perished with the using.
I asked him what he called the steeple-house? "`O,`" said he,
"`the dreadful house of God, the temple of God.`"
Then I showed him, and the poor dark people,
that their bodies should be the temples of God;
and that Christ never commanded these temples, but ended that temple at Jerusalem,
which God had commanded.
While I was speaking, the priest got away;
and afterwards the people appeared as if they feared we would take their purses,
or steal their horses; judging us like themselves, who are naturally given to thieving.

The next day we came through the country into Cumberland again,
where we had a general meeting of many thousands
of people at the top of a hill near Langlands.
A glorious and heavenly meeting it was; for the glory of the Lord did shine over all;
and there were as many as one could well speak over, the multitude was so great.
Their eyes were fixed on Christ their teacher; and they came to sit under their own vine;
insomuch that Francis Howgill, coming afterwards to visit them,
found they had no need of words; for they were sitting under their teacher Christ Jesus;
in the sense whereof, he sat down amongst them, without speaking anything.
A great convincement there was in Cumberland, Durham, Northumberland, Westmorland,
Lancashire, and Yorkshire; and the plants of God grew, and flourished,
the heavenly rain descending, and God`'s glory shining upon them,
so that many mouths were opened by the Lord to his praise; yea,
to babes and sucklings he ordained strength.
