== Chapter VII.

[.chapter-synopsis]
* 1653-1654.
* George Fox disputes most of the day with priest Wilkinson
* many Friends lose their business for declining the world`'s salutations, but afterwards their tried faithfulness and integrity procure them more than their neighbours.
* George Fox issues an address to Friends everywhere
* two persecuting justices at Carlisle are cut off, and a third disgraced
* George Fox passes through Halifax, a rude town of professors
* at Synderhill-Green he has a mighty meeting of some thousands, and there was a general convincement
* about sixty ministers are now raised up in the north, to travel towards the south, the east, and the west, in Truth`'s service
* George Fox`'s address to Friends in the ministry
* Rice Jones and many other false prophets rise up against Friends and are blasted
* a wicked man binds himself with an oath to kill George Fox, but is prevented
* great convincement in Lincolnshire
* at Swannington George Fox has much controversy with professors
* has a great dispute with priest Stevens, and seven other priests at Drayton
* his father being present was convinced, and said, "`Truly I see he that will but stand to the truth it will carry him out.`"
* Priest Stevens propagates lies respecting George Fox, which the Lord swept away
* is taken before Col. Hacker, who sends him to the Protector
* speaks prophetically to the Colonel
* has a friendly conference with the Protector
* is dismissed by him very friendly refuses his entertainment
* Captain Drury scoffs at trembling, but is made to tremble in a remarkable manner
* George Fox prays with some officers, who are greatly shaken by the Lord`'s power
* priests and professors greatly disturbed because many of their people are convinced, and moved to declare against the rest.

After my release from Carlisle prison,
I was moved to go to priest Wilkinson`'s steeple-house again at Brigham;
and being got in before him, when he came in, I was declaring the truth to the people,
though they were but few;
for the most and the best of his hearers were turned to Christ`'s free teaching;
and we had a meeting of Friends hard by,
where Thomas Stubbs was declaring the word of life amongst them.
As soon as the priest came in, he opposed me; and there we stayed most part of the day;
for when I began, he opposed me; so if any law was broken, he broke it.
When his people would be haling me out, I manifested his fruits to be such,
as Christ spoke of, when he said,
"`they shall hale you out of their synagogues;`" and then he would be ashamed,
and they would let me alone.
There he stood till it was almost night, jangling and opposing me,
and would not go to his dinner; for he thought to weary me out.
But at last, the Lord`'s power and truth came so over him,
that he packed away with his people.
When he was gone, I went to the meeting of Friends, who were turned to the Lord,
and by his power established on Christ,
the rock and foundation of the true prophets and apostles, but not of the false.

About this time the priests and professors fell to prophesying against us afresh.
They had said long before, that we should be destroyed within a month; and after that,
they prolonged the time to half a-year; but that time being long expired,
and we mightily increased in number, they now gave forth,
that we would eat out one another.
For often after meetings, many tender people having a great way to go,
tarried at Friends`' houses by the way,
and sometimes more than there were beds to lodge in;
so that some have lain on the hay-mows;
hereupon Cain`'s fear possessed the professors and world`'s people.
For they were afraid, that when we had eaten one another out,
we would all come to be maintained by the parishes, and be chargeable to them.
But after a while, when they saw that the Lord blessed and increased Friends,
as he did Abraham, both in the field and in the basket, at their goings forth,
and comings in, at their risings up and lyings down,
and that all things prospered with them;
then they saw the falseness of all their prophecies against us;
and that it was in vain to curse, where God had blessed.
At the first convincement, when Friends could not put off their hats to people,
or say You to a single person, but Thou and Thee;--when they could not bow,
or use flattering words in salutations, or adopt the fashions and customs of the world,
many Friends, that were tradesmen of several sorts, lost their customers at first;
for the people were shy of them, and would not trade with them;
so that for a time some Friends could hardly get money enough to buy bread.
But afterwards, when people came to have experience of Friends`' honesty and faithfulness,
and found that their yea was yea, and their nay was nay;
that they kept to a word in their dealings, and that they would not cozen and cheat them;
but that if they sent a child to their shops for anything,
they were as well used as if they had come themselves;
the lives and conversation of Friends did preach,
and reached to the witness of God in the people.
Then things altered so, that all the inquiry was, "`where is there a draper,
or shopkeeper, or tailor, or shoemaker, or any other tradesman,
that is a Quaker?`" Insomuch that Friends had more trade than many of their neighbours,
and if there was any trading, they had a great part of it.
Then the envious professors altered their note, and began to cry out,
"`if we let these Quakers alone, they will take the trade of the nation out of our hands.`"
This has been the Lord`'s doing to and for his people! which my desire is, that all,
who profess his holy truth, may be kept truly sensible of, and that all may be preserved,
in and by his power and Spirit, faithful to God and man; first to God,
in obeying him in all things; and then in doing unto all men,
that which is just and righteous, to all men and women, in all things,
that they have to do or deal with them in;
that the Lord God may be glorified in their practising truth, holiness, godliness,
and righteousness, amongst people in all their lives and conversation.

Friends being now grown very numerous in the northern parts of the nation,
and many young-convinced ones coming daily in among us,
I was moved of the Lord to write the following epistle, and send it forth amongst them,
in order to stir up the pure mind,
and raise a holy care and watchfulness in them over themselves, and one another,
for the honour of truth:--

[.embedded-content-document.epistle]
--

[.blurb]
=== "`To you all, Friends everywhere, scattered abroad.

"`In the measure of the life of God, wait for wisdom from God, even from Him,
from whom it comes.
And all ye, who are children of God, wait for living food from the living God,
to be nourished up to eternal life, from the one fountain, from whence life comes;
that ye may all be guided and walk in order; servants in your places,
young men and women in your places, and rulers of families; that every one,
in your respective places, may adorn the truth, in the measure of it.
With it let your minds be kept up to the Lord Jesus, from whom it comes,
that ye may be a sweet savour to God,
and in wisdom ye may all be ordered and ruled;--that a
crown and a glory ye may be one to another in the Lord.
And that no strife, bitterness, or self-will, may appear amongst you; but with the Light,
in which is unity, all these may be condemned.
And that every one in particular, may see to, and take care of,
the ordering and ruling of his own family;
that in righteousness and wisdom it may be governed,
the fear and dread of the Lord being set in every one`'s heart;
that the secrets of the Lord every one may come to receive;
that stewards of his grace you may come to be,
to dispense it to every one as they have need;
and so in savouring and right-discerning you may all be kept; that nothing,
that is contrary to the pure life of God, may be brought forth in you, or among you;
but all that is contrary to it, may be judged by it; so that in light, in life, and love,
ye may all live, and all that is contrary to the light, and life, and love,
may be brought to judgment, and by that light condemned.
And that no fruitless trees be among you; but all cut down and condemned by the light,
and cast into the fire; so that every one may bear and bring forth fruit unto God,
and grow fruitful in his knowledge, and in his wisdom;
and that none may appear in words beyond what they are in the life,
that gave forth the words.
Here none shall be as the untimely figs;
none shall be of those trees whose fruit withers; such go in Cain`'s way, from the light,
and by it are condemned.
Let none amongst you boast yourselves above your measure; for if you do,
out of God`'s kingdom you are excluded; for in that boasting part gets up the pride,
and the strife, which is contrary to the light, that leads to the kingdom of God,
and gives an entrance thereinto,
and an understanding to know the things that belong to the kingdom of God.
There the light and life of man every one receives, even Him who was,
before the world was, by whom it was made, who is the righteousness of God,
and his wisdom; to whom all glory, honour, thanks, and praise belong,
who is God blessed forever.
Let no image or likeness be made; but wait in the light,
which will bring condemnation on that part that would make the images;
for that prisons the just.
So to the lust yield not the eye, nor the flesh;
for the pride of life stands in that which keeps out the love of the Father;
and upon which his judgments and wrath remain,
where the love of the world is sought after, and a crown that is mortal.
In this ground the evil enters, which is cursed; which brings forth briars and thorns,
where death reigns, and tribulation and anguish are upon every soul,
and the Egyptian tongue is heard; all which is by the light condemned.
There the earth is, which must be removed; by the light it is seen,
and by the power it is removed, and out of its place it is shaken;
to which the thunders utter their voices, before the mysteries of God be opened,
and Jesus revealed.
Therefore all ye, whose minds are turned to this light,
wait upon the Lord Jesus for the crown that is immortal, and that fadeth not away.`"

[.signed-section-signature]
G+++.+++ F.

--

"`This is to be sent amongst all Friends in tie truth, the flock of God,
to be read at their meetings.`"

[.small-break]
'''

While Friends abode in the northern parts, a priest of Wrexham, in Wales,
whose name was Morgan Floyd, having heard reports concerning us,
sent two of his congregation into the North to inquire concerning us, to try us,
and bring him an account of us.
But when these triers came down amongst us, the power of the Lord overcame them,
and they were both convinced of the truth.
So they stayed some time with us, and then returned into Wales;
where afterwards one of them departed from his convincement; but the other,
whose name was John-ap-John, abode in the truth, and received a part in the ministry,
in which he continued faithful.

Now were the priests greatly disturbed at Newcastle, at Kendal,
and in most of the northern counties.
There being one Gilpin, that had sometimes come amongst us at Kendal,
and soon run out from the truth into vain imaginations,
the priests made what evil use they could of him against us;
but the Lord`'s power confounded them all.
And the Lord God cut off two of the persecuting justices at Carlisle; and the other,
after a time, was turned out of his place, and left the town.

About this time the oath or engagement to Oliver Cromwell was tendered to the soldiers;
many of whom were disbanded, because, in obedience to Christ, they could not swear.
John Stubbs was one, who was convinced when I was in Carlisle prison,
and became a good soldier in the Lamb`'s war, and a faithful minister of Christ Jesus,
travelling much in the service of the Lord in Holland, Ireland, Scotland, Italy, Egypt,
and America.
And the Lord`'s power preserved him out of the hands of the Papists,
though many times he was in great danger of the Inquisition.
But some of the soldiers who had been convinced in their judgments,
but had not come into obedience to the truth, took Cromwell`'s oath;
and going afterwards into Scotland, and coming before a garrison there,
the garrison thinking they had been enemies, fired at them, and killed many of them;
which was a sad event.

[.small-break]
'''

When the churches were settled in the North,
and Friends were sat down under Christ`'s teaching,
and the glory of the Lord shone over them,
I passed from Swarthmore to Lancaster (about the
beginning of the year 1654) and so through the counties,
visiting Friends till I came to SynderHill-green,
where a meeting was appointed three weeks before; leaving the North fresh and green,
under Christ their teacher.
But before I came to Synderhill-Green, we passed through Halifax,
a rude town of professors, and came to one Thomas Taylor`'s, who had been a captain,
where we met with some janglers; but the Lord`'s power was over all;
for I travelled in the motion of God`'s power.
When I came to Synderhill-Green, there was a mighty meeting,
some thousands of people (as it was supposed). Many persons of note were there,
as captains and other officers; and there was a general convincement;
for the Lord`'s power and truth was over all, and there was no opposition.

About this time did the Lord move upon the spirits of many, whom he had raised up,
and sent forth to labour in his vineyard, to travel southwards, and spread themselves,
in the service of the gospel, to the eastern, southern, and western parts of the nation;
as Francis Howgill and Edward Burrough to London; John Camm and John Audland to Bristol;
Richard Hubberthorn and George Whitehead^
footnote:[George Whitehead, who was convinced when about seventeen years old,
became a valiant minister for about sixty-eight years, till the time of his decease,
which took place, in great peace, after an illness of some weeks.
He waited, patiently resigned to the will of God,
desiring to be dissolved and be with Christ; saying,
"`he felt the sting of death to be taken away.`"
He was a preacher of the gospel in life and power,
and turned many from darkness to light,
being a chief instrument in gathering a people to the Lord in and about Norwich.
At one meeting he had in those parts,
it is recorded that "`nearly the whole congregation was
convinced by the mighty power of God,
through his lively and piercing testimony and prayer.`"
He suffered great hardships, long and sore imprisonments,
and severe whipping for his testimony to the truth,
much of which is recorded in his published Journal, with his travels and other services,
to which the reader is referred.]
towards Norwich; Thomas Holmes^
footnote:[Thomas Holmes was serviceable in his day and generation,
suffering imprisonment on Truth`'s account.
In 1656, he was in jail, at Chester, with seven or eight other Friends.
Some of his services in Wales are related, in a letter from him (probably to George Fox),
in Barclay`'s _Letters of Early Friends_, p. 232.]
into Wales, and others different ways; for above sixty ministers had the Lord raised up,
and now sent abroad out of the North country.
The sense of their service being very weighty upon me,
I was moved to give forth the following paper:--

[.embedded-content-document.letter]
--

[.letter-heading]
To Friends in the Ministry

"`All Friends everywhere, Know the Seed of God, which bruiseth the seed of the serpent,
and is above the seed of the serpent; which Seed sins not,
but bruiseth the serpent`'s head, that doth sin, and tempts to sin;
which Seed God`'s promise and God`'s blessing is to;
and which is one in the male and in the female.
Where it is head, and hath bruised the head of the other, to the beginning you are come;
and the younger is known, and he that is servant to the younger.
And the promise of God, which is to the Seed, is fulfilled and fulfilling;
the Scriptures come to be opened and owned; the flesh of Christ known,
who took upon him the seed of Abraham according to the flesh;
and the everlasting priesthood known, the everlasting covenant.
Christ takes upon him the seed of Abraham,
and is a priest after the order of Melchizedek; without father, without mother,
without beginning of days (mark) or end of life; this is the priest that ever lives;
the covenant of life, of light, and peace.
And the everlasting offering here is known once for all,
which offering overthrows that nature which offered; out of which the priesthood arose,
that could not continue by reason of death.
And here is the other offering known,
the everlasting offering which perfects forever them that are sanctified;
which offering blotted out the hand-writing of ordinances, triumphs over them,
and ascends above all principalities and powers.
Now he that hath the Spirit of Jesus, sees this; and here is the love of God received,
that doth not rejoice in iniquity, but leads to repent of it.
This is the word of the Lord God to you all, Friends everywhere scattered abroad,
Know the power of God in one another, and in that rejoice;
for then you rejoice in the cross of Christ, who is not of the world;
which cross is the power of God to all them that are saved.
You, that know the power, and feel the power, you feel the cross of Christ,
you feel the gospel,
which is the power of God unto salvation to every one that believeth.
Now, he that believes in the light, believes in the everlasting covenant,
in the one offering; comes to the life of the prophets and Moses;
comes to see Christ the hope, the mystery, which hope perisheth not,
but lets you see the hope that perisheth, which is not that mystery;
and the expectation in that perishing hope fades.
Where this never-failing hope is witnessed, the Lord comes to be sanctified in the heart,
and you come to the beginning, to Christ the hope, which perisheth not;
but the other hope, and the other expectation perisheth.
So all of you, know the perishing of the other,
and the failing of the expectation therein; and know that which perisheth not;
that you may be ready to give a reason of this hope with meekness and fear,
to every man that asketh you.
Christ the hope, the mystery, that perisheth not; the end of all perishing things,
the end of all changeable things, the end of the decaying covenant,
the end of that which waxeth old and doth decay; the end of the first covenant, of Moses,
and of the prophets; the righteousness of God, Christ Jesus the Son;
his throne ye will know, heirs with him ye will be;
who makes his children kings and priests to him,
and brings them to know his throne and his power.
There is no justification out of the light, out of Christ;
justification is in the light in Christ; here is the doer of the will of God,
here is the entering into the kingdom.
He that believes in the light, becomes a child of light;
and here the wisdom is received that is justified of her children.
Here believing in the light, you shall not abide in darkness,
but shall have the light of life;
and come every one to witness the light that shines in your hearts,
which light will give you the light of the knowledge of the glory of God,
in the face of Jesus Christ.
With which light you will see him reign, who is the prince of life and of peace;
which light turns from him, that is out of the truth, and abode not in it;
where the true peace is not.

"`Friends, be not hasty; for he that believes in the light, makes not haste.
Here the grace is received, by which you come to be saved; the election is known,
which obtains the promise; the will is seen that wills;
the mind is known that runs and obtains not, but stops and becomes dull.
Now, that with the light being seen, and judged, and stopped,
the patience is here known which obtains the crown, and the immortality is come to light.
So all they now that act contrary to the light, and do not believe in it,
do not come to justification.
And, all Friends, if you go from the light,
from wanting to have the promise of God fulfilled to the Seed,
whereby you may know Christ to reign,
you thereby bring on yourselves changeable garments,
and come to wear the changeable garments, and the strange flesh, which leads to adultery,
which the law goes upon, which shuts out of the kingdom:
and out of this will doth proceed the work or building, that is for the fire;
whereby you may come to suffer loss.
Therefore love the light, which doth condemn that, and receive the power from tie Lord,
with which you stand over that, and condemn it;
feeling and seeing that which gives you the victory over the world,
and to see out of time, to before time.
Again, Friends, know Abraham, that must obey the voice of Sarah, that bears seed;
which casts forth the bond-woman and her son: do not go forth,
there will the wildness lodge.
Know that which bears the wild son, and its mother, who is not Sarah;
for the promise is to the Seed, not of many, but one, which seed is Christ:
and this Seed now you come to witness stand above all, yea, on the head of the serpent.
And so all, as I said before, who come to feel and witness this, come to the beginning;
and this to all the seed of God, the church, that it you all may come to know,
where there is no blemish, nor spot, nor wrinkle, nor any such thing.
This is that which is purchased by the blood of Jesus,
and to the Father presented out of all that defiles;
which is the pillar and ground of truth.
None come to this, but such as come to the light of Christ, who purchased this church.
They who go from the light are shut out and condemned,
though they profess all the Scriptures declared from, it.
Therefore walk in the light, that you may have fellowship with the Son,
and with the Father; and come all to witness his image, his power, and his law,
which is his light, which hath converted your souls,
and brought them to submit to the higher power, above that which is out of the truth:
that you may know here the mercy and truth, and the faith that works by love,
which Christ is the author of, who lighteth every one of you;
which faith gives the victory.
Now that which gives the victory is perfect;
and that which the ministers of God received from God, is that which is perfect;
and that which they are to minister is for the perfecting of the saints,
till they all come in the unity of the faith unto a perfect man.
This is the word of the Lord God to you all; every one in the measure of life wait,
that with it all your minds may be guided up to the Father of life,
tho Father of Spirits; to receive power from him, and wisdom,
that with it you may be ordered to his glory; to whom be all glory forever!
All keep in the light and life,
that judgeth down that which is contrary to the light and life.
So the Lord God Almighty be with you all.
And keep your meetings everywhere, being guided by that of God;
by that you may see the Lord God among you,
even him who lighteth every man that cometh into the world: by whom the world was made;
that men, who are come into the world, might believe.
He that believeth not the light condemns him: he that believeth,
cometh out of condemnation.
So this light, which lighteth every man that cometh into the world,
and which they that hate it stumble at, is the light of men.

"`All Friends, that speak in public, see that it be in the life of God;
for that begets to God: the fruits of that shall never wither.
This sows to the Spirit, which is in prison, and of the Spirit reaps life;
and the other sows to the flesh, and of the flesh reaps corruption.
And this you may see all the world over, amongst these seeds-men,
what may be reaped in the field, that is, the world.
Therefore in the Spirit of the Lord God wait, which cuts down and casts out all this,
the root and branches of it.
In that wait to receive power, and the Lord God Almighty preserve you in it;
whereby you may come to feel the light, that comprehends time and the world,
and fathoms it; which, believed in, gives you victory over the world.
And here the power of the Lord is received, which subdues all the contrary,
and puts off the garments that will stain and pollute.
With this light you come to reach the light in every man,
which Christ enlightens every man that cometh into the world withal:
and here the things of Christ come to be known, and the voice of Christ heard.
Therefore keep in the light, the covenant of peace, and walk in the covenant of life.
There is that which maketh merry over the witness of God:
and there is that which maketh merry in the Lord;
which rejoiceth over that which hath made merry over it: of that take notice,
you who are in the light.
Such the Lord doth beautify, whose trust is in his strength: and the Lord doth see such,
and them that are in his light.
But such as are from the light, whose eyes are after their abominations and idols,
their eyes are to be blinded; and their beautiful idols,
and their abominations to be destroyed, and by the light condemned,
which they have made from the life, in their own strength; which with the light is seen,
and overthrown by the power of God.
'`If you can change my covenant,`' saith the Lord, '`which keeps the day in its season,
and the night in its season (mark, my covenant, the light); if you can change this,
then may you change the covenant of God with his seed.`' So all Friends,
that are turned to the light, which cometh from him, by whom the world was made, who was,
before it was made, Christ Jesus, the Saviour of your souls; abide in the light,
and you will see your salvation to be walls and bulwarks against that,
which the light discovers to be contrary to it.
Waiting in the light, you will receive the power of God, which is the gospel of peace;
that you may be shod with it, and know that in one another,
which raiseth up the seed of God, sets it over the world and the earth,
and crucifies the affections and lusts: then the truth comes to reign,
which is the girdle.`"

[.signed-section-signature]
G+++.+++ F.

--

About this time Rice Jones of Nottingham (who had been a Baptist, and was turned Banter),
and his company, began to prophesy against me, giving out,
that I was then at the highest, and that after that time I should fall down as fast.
He sent a bundle of railing papers from Nottingham to Mansfield, Clawson,
and the towns thereabouts,
judging Friends for declaring the truth in the markets and in steeple-houses;
which papers I answered.
But his and his company`'s prophecies came upon themselves;
for soon after they fell to pieces, and many of his followers became Friends,
and continued so.
And through the Lord`'s blessed power, truth and Friends have increased,
and do increase in the increase of God: and I, by the same power,
have been and am preserved, and kept in the everlasting Seed, that never fell,
nor changes.
But Rice Jones took the oaths that were put to him,
and so disobeyed the command of Christ.
Many such false prophets have risen up against me, but the Lord hath blasted them,
and will blast all who rise against the blessed Seed, and me in that.
My confidence is in the Lord; for I saw their end, and how the Lord would confound them,
before he sent me forth.

I was now at Synderhill-green, where I had had a large meeting in the daytime;
and at night we had a great meeting again in Thomas Stacey`'s house;
for people came from far, and could not soon depart.
The high sheriff of the county told Captain Bradford,
that he intended to come up with half a dozen of his troopers to the meeting;
but the Lord prevented him.
When I had attended some meetings thereabouts, I travelled up and down in Yorkshire,
as far as Holderness, and to the land`'s end that way,
visiting Friends and the churches of Christ;
which were finely settled under Christ`'s teaching.
At length I came to Captain Bradford`'s house,
whither many Banters came from York to wrangle; but they were confounded and stopped.
Thither came also she who was called the Lady Montague, who was then convinced,
and lied and died in the truth.

Then I came again to Thomas Taylor`'s, within three miles of Halifax,
where was a meeting of about two hundred people; amongst which were many rude people,
and divers butchers,
several of whom had bound themselves with an oath before they came out,
that they would kill me (as I was told);
one of those butchers had been accused of killing a man and a woman.
They came in a very rude manner, and made a great disturbance in the meeting.
The meeting being in a field, Thomas Taylor stood up, and said unto them,
"`If you will be civil, you may stay, but if not,
I charge you to be gone from off my ground.`"
But they were the worse, and said they would make it like a common; and they yelled,
and made a noise, as if they had been at a bear-baiting.
They thrust Friends up and down; and Friends being peaceable,
the Lord`'s power came over them.
Several times they thrust me off from the place I stood on,
by the crowding of the people together against me;
but still I was moved of the Lord to stand up again, as I was thrust down.
At last I was moved of the Lord to say unto them,
"`if they would discourse of the things of God, let them come up to me one by one;
and if they had anything to say or to object, I would answer them all,
one after another;`" but they were all silent, and had nothing to say.
And then the Lord`'s power came so over them all, and answered the witness of God in them,
that they were bound by the power of God; and a glorious, powerful meeting we had,
and his power went over all,
and the minds of the people were turned by the Spirit of God in them to God,
and to Christ their teacher.
The powerful word of life was largely declared that day;
and in the life and power of God we broke up our meeting;
and that rude company went their way to Halifax.
The people asked them, why they did not kill me, according to the oath they had sworn;
and they maliciously answered, that I had so bewitched them, that they could not do it.
Thus was the devil chained at that time.
Friends told me, that they used to come at other times, and be very rude;
and sometimes break their stools and seats, and make frightful work amongst them;
but the Lord`'s power tad now bound them.
Shortly after this, the butcher,
that had been accused of killing a man and a woman before,
and who was one of them that had then bound himself by an oath to kill me,
killed another man, and was sent to York jail.
Another of those rude butchers, who had also sworn to '`kill me,
having accustomed himself to thrust his tongue out of his mouth, in derision of Friends,
when they passed by him, had it so swollen out of his mouth,
that he could never draw it in again, but died so.
Several strange and sudden judgments came upon many of these conspirators against me,
which would be too large here to declare.
God`'s vengeance from heaven came upon the blood-thirsty, who sought after blood;
for all such spirits I laid before the Lord, and left them to him to deal with them,
who is stronger than all; in whose power I was preserved, and carried on to do his work.
The Lord hath raised a fine people in these parts, whom he hath drawn to Christ,
and gathered in his name; who feel Christ amongst them, and sit under his teaching.

After this I came to Balby; from whence several Friends went with me into Lincolnshire;
of whom some went to the steeple-houses, and some to private meetings.
There came to the meeting where I was, the sheriff of Lincoln,^
footnote:[The sheriff of Lincoln, Richard Craven, was afterwards convinced,
and travelled with George Fox.]
and several with him, who made great contention and jangling for a time.
But at length the Lord`'s power struck him, that he was convinced of the truth,
and received the word of life, as did several others also that had opposed,
and continued among Friends till they died.
Great meetings there were, and a large convincement in those parts.
Many were turned to the Lord Jesus, and came to sit under his teaching;
leaving their priests, and their superstitious ways;
and the day of the Lord flourished over all.
Amongst them that came to our meetings in that country, was one called Sir Richard Wrey,
who was convinced; as was also his brother, and his brother`'s wife,
who abode in the truth, and died therein, though he afterwards ran out.

Having visited these countries, I came into Derbyshire; the sheriff of Lincoln,
who was lately convinced, being with me.
In one meeting we had some opposition,
but the Lord`'s glorious power gave dominion over all.
At night there came a company of bailiffs and serving-men, and called me out.
I went out to them, having some Friends with me.
They were exceedingly rude and violent; for they had plotted together,
and intended to carry me away with them in the dark of the evening by force:
and then to do me a mischief: but the Lord`'s power went over them, and chained them,
so that they could not effect their design; and at last they went away.
The next day,
Thomas Aldam understanding that the serving-men belonged to one called a knight,
who lived not far off, went to his house,
and laid before him the bad conduct of his servants.
The knight rebuked them, and did not allow of their evil carriage towards us.

After this we came into Nottinghamshire to Skegby,
where we had a great meeting of divers sorts of people:
and the Lord`'s power went over them, and all was quiet.
The people were turned to the Spirit of God, by which many came to receive his power,
and to sit under the teaching of Christ, their Saviour.
A great people the Lord hath in those parts.

I passed towards Kidsley Park, where came many Banters; but the Lord`'s power checked them.
From thence I went into the Peak Country towards Thomas Hammersley`'s,
where came the Banters of that country, and many high professors.
The Banters opposed me, and began swearing.
When I reproved them for it, they would bring Scripture for it, and said, Abraham,
and Jacob, and Joseph swore; and the priests, Moses, the prophets, and the angels swore.
Then I told them, "`I confessed all these did so, as the Scripture records; but, said I,
Christ (who said, '`Before Abraham was, I am'`) saith,
'`Swear not at all.`' And Christ ends the prophets, and the old priesthood,
and the dispensation of Moses, and reigns over the house of Jacob and of Joseph;
and he says.
'`Swear not at all.`' And God, when he bringeth in the first-begotten into the world,
saith, '`Let all the angels of God worship him,`' to wit, Christ Jesus, who saith,
'`Swear not at all.`' And as for the plea that men make for swearing to end their strife,
Christ, who says, '`Swear not at all,`' destroys the Devil and his works,
who is the author of strife, for that is one of his works.
And God said, '`This is my beloved Son, in whom I am well pleased;
hear ye him.`' So the Son is to be heard, who forbids swearing.
And the apostle James, who heard the Son of God, followed him, and preached him,
forbids all oaths,^
footnote:[See Gurney on Oaths, p. 334.]
James 5:12.`" So the Lord`'s power went over them:
and his Son and his doctrine was set over them.
The word of life was fully and richly preached, and many were convinced that day.
This Thomas Hammersley being summoned to serve upon a jury,
was admitted to serve without an oath; and when he, as foreman of the jury,
brought in the verdict, the judge declared, "`that he had been a judge many years,
but never heard a more upright verdict than that Quaker had then brought in.`"
Much might be written of things of this nature, which time would fail to declare.
But the Lord`'s blessed power and truth was exalted over all,
who is worthy of all praise and glory forever!

Travelling through Derbyshire,
I visited Friends till I came to Swannington in Leicestershire,
where was a general meeting, to which many Ranters, Baptists, and other professors came;
for great contests there had been with them, and with the priests in that town.
To this meeting several Mends came from various parts, as John Audland, Francis Howgill,
and Edward Pyot from Bristol, and Edward Burrough from London:
and several were convinced in those parts.
The Ranters made a disturbance, and were very rude,
but at last the Lord`'s power came over them, and they were confounded.
The next day Jacob Bottomley, a great Banter, came from Leicester;
but the Lord`'s power stopped him, and came over them all.
There came a priest too, but he also was confounded by the mighty power of the Lord.
About this time the priests, Baptists, Banters, and other professors, were very rude,
and stirred up the rude people against us.
We sent to the Banters to come forth, and try their God.
Abundance of them came, who were very rude, and sung, and whistled, and danced;
but the Lord`'s power so confounded them, that many of them came to be convinced.

After this I went to Twycross, whither came some Banters, who sung and danced before me.
But I was moved in the dread of the Lord to reprove them;
and the Lord`'s power came over them, so that some of them were convinced,
and received the Spirit of God; and are become a fine people,
living and walking soberly in the truth of Christ.
I went to Anthony Brickley`'s in Warwickshire, where there was a great meeting;
several Baptists and other people came and jangled; but the Lord`'s power came over them.

Then I went to Drayton in Leicestershire to visit my relations.
As soon as I was come in, Nathaniel Stephens the priest, having got another priest,
and given notice to the country, sent to me to come to them,
for they could not do anything till I came.
Having been three years away from my relations, I knew nothing of their design.
But at last I went into the steeple-house yard, where the two priests were;
and they had gathered abundance of people.
When I came there, they would have me go into the steeple-house.
I asked them what I should do there; and they said, Mr. Stephens could not bear the cold.
I told them, he might bear it as well as I. At last we went into a great hall,
Richard Farnsworth being with me; and a great dispute we had with these priests,
concerning their practices, how contrary they were to Christ and his apostles.
The priests would know, where tithes were forbidden or ended.
I showed them out of the seventh chapter to the Hebrews, "`that not only tithes,
but the priesthood that took tithes, was ended; and the law was ended and disannulled,
by which the priesthood was made, and tithes were commanded to be paid.`"
Then the priests stirred up the people to some lightness and rudeness.
I had known Stephens from a child, therefore I laid open his condition,
and the manner of his preaching; and "`how that he, like the rest of the priests,
did apply the promises to the first birth, which must die.
But I showed that the promises were to the Seed, not to many seeds, but to one Seed,
Christ; who was one in male and female;
for all were to be born again before they could enter into the kingdom of God.`"
Then he said, I must not judge so: but I told him,
"`he that was spiritual judged all things.`"
Then he confessed, that that was a full Scripture; "`but, neighbours,`" said he,
"`this is the business; George Fox is come to the light of the sun,
and now he thinks to put out my star-light.`"
I told him, "`I would not quench the least measure of God in any,
much less put out his star-light,
if it were true star-light--light from the morning star.`"
But I told him, "`if he had anything from Christ or God, he ought to speak it freely,
and not take tithes from the people for preaching,
seeing Christ commanded his ministers to give freely, as they had received freely.`"
So I charged him to preach no more for tithes, or any hire.
But he said, he would not yield to that.
After a while the people began to be vain and rude; so we broke up;
yet some were made loving to the truth that day.
Before we parted, I told them that, if the Lord would,
I intended to be at the town again that day week.
In the interim I went into the country, and had meetings,
and came thither again that day week.
Against that time this priest had got seven priests to help him:
for priest Stephens had given notice at a lecture on a market-day at Adderston,
that such a day there would be a meeting and a dispute with me.
I knew nothing of it; but had only said, I should be in town that day week again.
These eight priests had gathered several hundreds of people,
even most of the country thereabouts, and they would have had me into the steeple-house;
but I would not go in, but got on a hill, and there spoke to them and the people.
There were with me Thomas Taylor, who had been a priest, James Parnell,
and several other Friends.
The priests thought that day to trample down truth; but the truth came over them.
Then they grew light, and the people rude; and the priests would not stand trial with me;
but would he contending here and there a little, with one Friend or other.
At last one of the priests brought his son to dispute with me;
but his mouth was soon stopped.
When he could not tell how to answer, he would ask his father:
and his father was confounded also, when he came to answer for his son.
So, after they had toiled themselves,
they went away in a rage to priest Stephen`'s house to drink.
As they went away, I said,
"`I never came to a place where so many priests
together would not stand the trial with me.`"
Whereupon they and some of their wives came about me, laid hold of me,
and fawningly said, "`what might I have been, if it had not been for the Quakers!`"
Then they began to push Friends to and fro, to thrust them from me,
and to pluck me to themselves.
After a while several lusty fellows came, took me up in their arms,
and carried me into the steeple-house porch,
intending to carry me into the steeple-house by force; but the door being locked,
they fell down on a heap, having me under them.
As soon as I could, I got up from under them, and went to the hill again:
then they took me from that place to the steeple-house wall,
and set me on something like a stool; and all the priests being come back,
stood under with the people.
The priests cried, "`Come, to argument, to argument:`" I said,
"`I denied all their voices, for they were the voices of hirelings and strangers.`"
And they cried, "`Prove it, prove it.`"
Then I directed them to the tenth of John, where they might see what Christ said of such;
he declared, "`he was the true shepherd that laid down his life for his sheep,
and his sheep heard his voice, and followed him; but the hireling would fly,
when the wolf came, because he was a hireling.`"
I offered to prove that they were such hirelings.
Then the priests plucked me off from the stool again;
and they themselves got all upon stools under the steeple-house wall.
Then I felt the mighty power of God arise over all, and told them,
"`if they would but give audience, and hear me quietly,
I would show them by the Scriptures, why I denied those eight priests or teachers,
that stood before me; and all the hireling teachers of the world whatsoever;
and I would give them Scriptures for what I said.`"
Whereupon both priests and people consented.
Then I showed them out of the prophets Isaiah, Jeremiah, Ezekiel, Micah, Malachi,
and others,
that they were in the steps of such as God sent his true prophets to cry against; for,
said I, "`You are such as the prophet Jeremiah cried against, chap. 5. when he said,
'`The prophets prophesy falsely, and the priests bear rule by their means;`'
which he called a horrible filthy thing.
You are such as they that used their tongues and said, Thus saith the Lord,
when the Lord never spoke to them: and such as followed their own spirits,
and saw nothing; but spoke forth a divination of their own brain;
and by their lies and their lightness had caused the people to err, Jer. 14.
You are such as they were, that sought for their gain from their quarter;
that were as greedy, dumb dogs, that could never have enough,
whom the Lord sent his prophet Isaiah to cry against, Isaiah 56.
You are such, as they were, who taught for handfuls of barley, and pieces of bread;
who sewed pillows under people`'s arm-holes, that they might lie soft in their sins, Ezek. 13.
Yon are such as they that taught for the fleece, and the wool,
and made a prey of the people, Ezek. 34.
But the Lord is gathering his sheep from your mouths, and from off your barren mountains;
and is bringing them to Christ, the one Shepherd, which he hath set over his flocks;
as by his prophet Ezekiel he then declared he would do.
You are such as they that divined for money, and preached for hire;
and if a man did not put into their mouths, they prepared war against him,
as the prophet Micah complained, chap. 3.`"
Thus I went through the prophets, too largely to be here repeated.
Then coming to the New Testament, I showed from thence,
"`that they were like the chief priests, and scribes, and Pharisees of old,
such as Christ cried woe against, Matt. 23.
And that they were such false apostles, as the true apostles cried against,
such as taught for filthy lucre; such antichrists and deceivers, as they cried against,
that minded earthly things, and served not the Lord Jesus Christ, but their own bellies:
for they that served Christ gave freely, and preached freely, as he commanded them.
But they that will not preach without hire, tithes, or outward means,
serve their own bellies, and not Christ; and through the good words of the Scriptures,
and feigned words of their own, they made merchandize of the people then,
as (said I) ye do now.`"
So when I had largely quoted the Scriptures, and showed them,
wherein they were like the Pharisees, loving to be called of men masters,
and to go in long robes, and to stand praying in the synagogues,
and to have the uppermost rooms at feasts, and the like;
and when I had thrown them out in the sight of the people amongst the false prophets,
deceivers, scribes, and Pharisees, and showed at large,
how such as they were judged and condemned by the true prophets, by Christ,
and by the apostles, "`I directed them to the light of Christ Jesus,
who enlightens every man that Cometh into the world; that by it they might see,
whether these things were not true, as had been spoken.`"
When I appealed to that of God in their consciences, the light of Christ Jesus in them,
they could not bear to hear of it; they were all quiet till then;
but then a professor said, "`George, what! wilt thou never have done?`" I told him,
I should have done shortly.
So I went on a little longer, and cleared myself of them in the Lord`'s power.
When I had done, all the priests and people stood silent for a time:
at last one of the priests said, they would read the Scriptures that I had quoted.
I told them, with all my heart.
They began to read the 23rd of Jeremiah,
and there they saw the marks of the false prophets, that he cried against.
When they had read a verse or two, I said,
"`Take notice, people:`" but the priests said, "`Hold thy tongue, George.`"
I bid them read the whole chapter throughout; for it was all against them:
then they stopped, and would read no further; but asked me a question.
I told them, I would answer their question,
the matter being first granted that I had charged them with, viz.,
that they were false prophets, false teachers, antichrists, and deceivers,
such as the true prophets, Christ, and the apostles cried against.
A professor said Nay to that; but I said, Yea; for you leaving the matter,
and going to another thing, seem to consent to the proof of the former charge.
Then I answered their question, which was this;
Seeing those false prophets were adulterated,
whether I did judge Stephens to be an adulterer? To which.
I answered, he was adulterated from God in his practice,
like those false prophets and the Jews.
They would not stand to vindicate him, but broke up the meeting.
Then the priests whispered together; and priest Stephens came to me,
and desired that my father and brother and I might go aside with him,
that he might speak to me in private;
and the rest of the priests should keep the people from coming to us.
I was very loath to go aside with him; but the people cried,
"`Go, George; do, George, go aside with him.`"
I was afraid, if I did not go, they would say, I was disobedient to my parents;
so I went, and the rest of the priests were to keep the people off; but they could not,
for the people being willing to hear, drew close to us.
I asked the priest what he had to say; and he said, "`if he was out of the way,
I should pray for him: and if I was out of the way, he would pray for me:
and he would give me a form of words to pray for him by.`"
I replied, "`It seems thou dost not know whether thou art in the right way or not;
neither dost thou know whether I am in the right way, or not:
but I know that I am in the everlasting way, Christ Jesus, which thou art out of.
And thou wouldest give me a form of words to pray by,
and yet thou deniest the Common Prayer-Book to pray by, as well as I;
and I deny thy form of words, as well as it.
If thou wouldst have me pray for thee by a form of words,
is not this to deny the apostle`'s doctrine and practice of praying by the Spirit,
as it gave words and utterance?`" Here the people fell a laughing:
but I was moved to speak more to him.
And when I had cleared myself to him and them, we parted, after I had told them,
that I should (God willing) be in the town that day week again.
So the priests packed away, and many people were convinced;
for the Lord`'s power came over all.
Though they thought to have confounded truth that day, many were convinced of it;
and many that were convinced before, were by that day`'s work confirmed in the truth,
and abode in it; and a great shake it gave to the priests.
My father, though he was a hearer and follower of the priest, was so well satisfied,
that he struck his cane upon the ground, and said, "`Truly, I see,
he that will but stand to the truth, it will carry him out.`"
I passed about in the country till that day week, and then came again;
for we had appointed a meeting at my relations`' house.
Now priest Stephens having had notice beforehand thereof, had got another priest to him;
and they had a company of troopers with them, and sent for me to come to them.
But I sent them word our meeting was appointed, and they might come to it, if they would.
The priests came not; but the troopers came, and many rude people.
They had laid their plot, that the troopers should take every one`'s name,
and then command them to go home; and such as would not go, they should take,
and carry them away with them.
Accordingly they began, and took several names, charging them to go home;
but when they came to take my name, my relations told them, I was at home already:
so they could not take me away that time.
Nevertheless they took my name: but the Lord`'s power was over them, and they went away,
both professors and troopers, crossed and vexed, because they obtained not their end.
But several were convinced that day, and admired the love and power of God.
This was that priest Stephens, who once said of me,
"`never was such a plant bred in England:`" yet afterwards he reported,
"`that I was carried up into the clouds, and found again full of gold and silver;`" and many lies,
and false reports he raised respecting me: but the Lord swept them all away.
The reason why I would not go into their steeple-house was,
because I was to bear my testimony against it, and to bring all off from such places,
to the Spirit of God;
that they might know their bodies to be the temples of the Holy Ghost;
and to bring them off from all the hireling teachers, to Christ their free teacher,
who died for them, and purchased them with his blood.

[.small-break]
'''

After this I went into the country, and had several meetings, and came to Swannington,
where the soldiers came again; but the meeting was quiet, the Lord`'s power was over all,
and the soldiers did not interfere.
Then I went to Leicester, and then to Whetstone.
There came about seventeen troopers of Colonel Hacker`'s regiment, with his marshal,
and took me up before the meeting, though Friends were beginning to gather together;
for there were several Friends come from various parts.
I told the marshal, "`he might let all the Friends go,
I would answer for them all;`" so he took me, and let them go, except Alexander Parker,
who went with me.^
footnote:["`Alexander Parker,`" says Whiting, "`was an eminent servant of God,
and minister of Jesus Christ; from near Bolton, in Lancashire, well-educated,
and had a gentleman-like carriage and deportment, for I knew him well.`"
He travelled extensively in the service of the gospel, often in company with George Fox,
being frequently mentioned in this Journal.
He suffered fines, imprisonments, and persecution,
being once pulled down as he was preaching in London,
and fined for it 20. He died in great peace in 1689,
having written many books and epistles, in which, though being dead, he yet speaketh.]
At night they had me before Colonel Hacker, his major, and captains,
a great company of them; and much discourse we had about the priests, and meetings,
for at this time there was a rumour of a plot against Oliver Cromwell.
Much reasoning I had with them about the light of Christ,
which enlighteneth every man that cometh into the world.
Colonel Hacker asked,
whether it was not this light of Christ that made Judas betray his master,
and afterwards led him to hang himself? I told him, "`No;
that was the spirit of darkness, which hated Christ and his light.`"
Then Colonel Hacker said, I might go home, and keep there, and not go abroad to meetings.
I told him, "`I was an innocent man, free from plots, and denied all such work.`"
His son Needham said,
"`Father, this man hath reigned too long, it is time to have him cut off.`"
I asked him,
"`For what? what had I done? or whom had I wronged from
a child? for I was bred and born in that country,
and who could accuse me of any evil from a child?`"
Then Colonel Hacker asked me again,
if I would go home, and stay there? I told him, "`if I should promise him that,
it would manifest that I was guilty of something, to go home, and make my home a prison;
and if I went to meetings, they would say, I broke their order.`"
I told them, "`I should go to meetings, as the Lord should order me,
and therefore could not submit to their requirings;`" but I said,
"`we were a peaceable people.`"
"`Well then,`" said Colonel Hacker, "`I will send you to my Lord Protector,
by Captain Drury, one of his life-guards.`"
That night I was kept a prisoner at the Marshalsea; and the next morning by six o`'clock,
I was delivered to Captain Drury.
I desired he would let me speak with Colonel Hacker before I went,
and he had me to his bedside.
Colonel Hacker set upon me presently again, to go home and keep no more meetings.
I told him, "`I could not submit to that, but must have my liberty to serve God,
and to go to meetings.`"
"`Then,`" said he, "`you must go before the Protector.`"
"`Whereupon I kneeled by his bedside, and besought the Lord to forgive him,
for he was as Pilate, though he would wash his hands;
and when the day of his misery and trial should come upon him,
I bid him then remember what I had said to him.`"
But he was stirred up, and set on by priest Stephens,
and the other priests and professors, wherein their envy and baseness was manifest; who,
when they could not overcome me by disputes and arguments,
nor resist the Spirit of the Lord that was in me, then they got soldiers to take me up.

Afterwards, when this Colonel Hacker was in prison in London,
a day or two before he was executed,
he was put in mind of what he had done against the innocent; and he remembered it,
and confessed to it to Margaret Fell, saying he knew well whom she meant;
and he had a trouble upon him for it.
So his son, who told his father I had reigned too long,
and that it was time to have me cut off,
might observe how his father was cut off afterwards, he being hanged at Tyburn.

Now was I carried up a prisoner by Captain Drury from Leicester;
and when we came to Harborough, he asked me,
if I would go home and stay a fortnight?`" I should have my liberty,`" he said,
"`if I would not go to, nor keep meetings.`"
I told him, "`I could not promise any such thing.`"
Several times upon the road did he ask, and try me after the same manner,
and still I gave him the same answers.
So he brought me to London,
and lodged me at the Mermaid over-against the Mews at Charing-Cross.
As we travelled, I was moved of the Lord to warn people at the inns and places,
where I came, of the day of the Lord that was coming upon them.
William Dewsbury and Marmaduke Storr being in prison at Northampton,
he let me go and visit them.

After Captain Drury had lodged me at the Mermaid, he left me there,
and went to give the Protector an account of me.
When he came to me again, he told me,
the Protector required that I should promise not to take up a
carnal sword or weapon against him or the government,
as it then was, and that I should write it in what words I saw good,
and set my hand to it.
I said little in reply to Captain Drury.
But the next morning I was moved of the Lord to write a paper to the Protector,
Oliver Cromwell; "`wherein I did in the presence of the Lord God declare,
that I denied the wearing or drawing of a carnal sword, or any other outward weapon,
against him or any man;
and that I was sent of God to stand a witness against all violence,
and against the works of darkness; and to turn people from darkness to light;
and to bring them from the causes of war and fighting, to the peaceable gospel,
and from evil-doers, which the magistrates`' swords should be a terror to.`"
When I had written what the Lord had given me to write, I set my name to it,
and gave it to Captain Drury to hand to Oliver Cromwell, which he did.
After some time Captain Drury brought me before the Protector himself at Whitehall.
It was in a morning, before he was dressed, and one Harvey,
who had come a little among Friends, but was disobedient, waited upon him.
When I came in, I was moved to say, "`Peace be in this house;
and I exhorted him to keep in the fear of God, that he might receive wisdom from him,
that by it he might be directed, and order all things under his hand to God`'s glory.`"
I spoke much to him of truth, and much discourse I had with him about religion;
wherein he carried himself very moderately.
But he said, we quarrelled with priests, whom he called ministers.
I told him, "`I did not quarrel with them, but they quarrelled with me and my friends.
But,`" said I, "`if we own the prophets, Christ, and the apostles,
we cannot hold up such teachers, prophets, and shepherds, as the prophets, Christ,
and the apostles declared against;
but we must declare against them by the same power and Spirit.`"
Then I showed him, "`that the prophets, Christ, and the apostles declared freely,
and against them that did not declare freely; such as preached for filthy lucre,
and divined for money, and preached for hire, and were covetous and greedy,
that can never have enough; and that they that have the same Spirit, that Christ,
and the prophets, and the apostles had, could not but declare against all such now,
as they did then.`"
As I spoke, he several times said, it was very good, and it was truth.
I told him, "`that all Christendom (so called) possessed the Scriptures,
but wanted the power and Spirit that they had, who gave forth the Scriptures,
and that was the reason they were not in fellowship with the Son, nor with the Father,
nor with the Scriptures, nor one with another.`"
Many more words I had with him, but people coming in, I drew a little back;
and as I was turning, he caught me by the hand, and with tears in his eyes, said,
"`Come again to my house, for if thou and I were but an hour a day together,
we should be nearer one to the other;`" adding,
that he wished me no more ill than he did to his own soul.
I told him, "`if he did,
he wronged his own soul;`" and I bid him "`hearken to God`'s voice,
that he might stand in his counsel and obey it; and if he did so,
that would keep him from hardness of heart; but if he did not hear God`'s voice,
his heart would be hardened.`"
He said, it was true.
Then I went out; and when Captain Drury came out after me, he told me,
"`his lord Protector said, I was at liberty, and might go whither I would.`"
Then I was brought into a great hall, where the Protector`'s gentlemen were to dine;
and I asked them, what they brought me thither for f they said,
it was by the Protector`'s order, that I might dine with them.
I bid them let the Protector know, I would not eat of his bread, nor drink of his drink.
When he heard this, he said, "`Now I see there is a people risen and come up,
that I cannot win either with gifts, honours, offices, or places;
but all other sects and people I can.`"
It was told him again, "`that we had forsaken our own,
and were not likely to look for such things from him.`"

Being set at liberty I went to the inn again, where Captain Drury had at first lodged me.
This Captain Drury, though he sometimes carried fairly, was an enemy to me and to truth,
and opposed it;
and when professors came to me (while I was under his custody) and he was by,
he would scoff at trembling, and call us Quakers,
as the Independents and Presbyterians had nick-named us before.
But afterwards he once came to me, and told me, that,
as he was lying on his bed to rest himself in the day-time,
a sudden trembling seized on him, that his joints knocked together,
and his body shook so that he could not rise from his bed; he was so shaken,
that he had not strength enough left to rise.
But he felt the power of the Lord was upon him, and he fell off his bed,
and cried to the Lord, and said, he never would speak against the Quakers more,
or such as trembled at the word of God.

During the time I was prisoner at Charing-Cross, there came abundance to see me,
people of almost all sorts, priests, professors, officers of the army, etc.
And one time a company of officers being with me, desired me to pray with them.
I sat still, with my mind retired to the Lord.
At last I felt the power and Spirit of God move in me,
and the Lord`'s power did so shake and shatter them, that they wondered,
though they did not live in it.

Among those that came to see me, was one Colonel Packer, with several of his officers;
and while they were with me, came in one Cobb, and a great company of Ranters with him.
The Ranters began to call for drink and tobacco;
but I desired them to forbear it in my room, telling them,
if they had such a desire for it, they might go into another room.
One of them cried, "`all is ours;`" and another said, "`all is well.`"
I replied, "`how is all well, while thou art so peevish, and envious,
and crabbed?`" for I saw he was of a peevish nature.
I spoke to their conditions, and they were sensible of it, and looked upon one another,
wondering.

Then Colonel Packer began to talk with a light, chaffy mind, concerning God, and Christ,
and the Scriptures; it was a great grief to my soul and spirit,
when I heard him talk so lightly; so that I told him,
"`he was too light to talk of the things of God,
for he did not know the solidity of a man.`"
Thereupon the officers raged, and said, would I say so of their colonel.
This Packer was a Baptist,
and he and the Ranters bowed and scraped to one another very much;
for it was the manner of the Ranters to be exceedingly complimental (as they call it),
so that Packer bid them give over their compliments; but I told them,
"`they were fit to go together, for they were both of one spirit.`"

This Colonel Packer lived at Theobald`'s near Waltham, and was made a justice of peace.
He set up a great meeting of the Baptists at Theobald`'s Park;
for he and some other officers had purchased it.
They were exceedingly high, and railed against Friends and truth,
and threatened to apprehend me with their warrants if ever I came there.
Yet after I was set at liberty, I was moved of the Lord God to go down to Theobald`'s,
and appoint a meeting hard by them; to which many of his people came,
and divers of his hearers were convinced of the way of truth, and received Christ,
the free teacher, and came off from the Baptist; and that made him rage the more.
But the Lord`'s power came over him, so that he had not power to meddle with me.
Then I went to Waltham close by him, and had a meeting there;
but the people were very rude, and gathered about the house and broke the windows.
Whereupon I went out to them, with the Bible in my hand, and desired them to come in;
and told them, "`I would show them Scripture both for our principles and practices.`"
And when I had done so, I showed them also,
"`that their teachers were in the steps of such, as the prophets, and Christ,
and the apostles testified against.`"
Then I directed them to the Light of Christ, and Spirit of God in their own hearts,
that by it they might come to know their free teacher, the Lord Jesus Christ.
The meeting being ended, they went away quieted and satisfied,
and a meeting hath since been settled in that town.
But this was some time after I was set at liberty by Oliver Cromwell.

When I came from Whitehall to the Mermaid at Charing-Cross, I stayed not long there;
but went into the city of London, where we had great and powerful meetings;
so great were the throngs of people,
that I could hardly get to and from the meetings for the crowds;
and the truth spread exceedingly.
Thomas Aldam and Robert Craven, who had been sheriff of Lincoln, and many Friends,
came up to London after me; but Alexander Parker abode with me.

After a while I went to Whitehall again,
and was moved "`to declare the day of the Lord amongst them,
and that the Lord was come to teach his people himself;`"
so I preached truth both to the officers,
and to them that were called Oliver`'s gentlemen, who were of his guard.
But a priest opposed, while I was declaring the word of the Lord amongst them;
for Oliver had several priests about him, of which this was his news-monger;
an envious priest, and a light, scornful, chaffy man.
I bid him repent; and he put it in his newspaper the next week,
that I had been at Whitehall, and had bid a godly minister there repent.
When I went thither again, I met with him; and abundance of people gathered about me.
I manifested the priest to be a liar in several things that he had affirmed;
and so he was silenced.
He put in the news, that I wore silver buttons, which was false,
for they were but alchymy.
Afterwards he said in the news, that I hung ribands on people`'s arms,
which made them follow me; this was another of his lies,
for I never wore or used ribands in my life.
Three Friends went to examine this priest, that gave forth this false intelligence,
and to know of him where he had that information.
He said, it was a woman that told him so; and if they would come again,
he would tell them her name.
When they returned, he said, it was a man, but would not mention his name then;
but if they would come again, he would tell them his name, and where he lived.
They went the third time, and then he would not say who told him; but offered,
if I would give it under my hand, that there was no such thing,
he would put that into the news.
Thereupon the Friends carried it to him under my hand; but when they came,
he broke his promise, and would not insert it; but was in a rage,
and threatened them with the constable.
This was the deceitful doing of this forger of lies;
which he spread over all the nation in the news, to render truth odious,
and to put evil into people`'s minds against Friends and truth;
of which a more large account may be seen in a book printed soon after this time,
for the clearing of Friends and truth from the slanders, lies,
and false reports raised and cast upon them.
These priests, the news-mongers, were of the Independent sect, like those in Leicester;
but the Lord`'s power came over all their lies, and swept them away;
and many came to see the wickedness of these priests.
The God of heaven carried me over all in his power,
and his Messed power went over the nation: insomuch,
that many Friends about this time were moved to go up and down,
to sound forth the everlasting gospel in most parts of it, and also in Scotland;
and the glory of the Lord was felt over all to his everlasting praise.
A great convincement there was in London, and some in the Protector`'s house and family;
I went to see him again, but could not get access to him,
the officers were grown so rude.

The Presbyterians, Independents, and Baptists, were greatly disturbed;
for many of their people turned to the Lord Jesus Christ,
and sat down under his teachings: they received his power, and felt it in their hearts:
and then they were moved of the Lord to declare against the rest of them.

I appointed a meeting in the fields near Acton, in which the word of life,
the saving truth, was declared freely.
The Lord`'s power was eminently manifested, and his blessed day exalted over all.
