== Chapter VIII.

[.chapter-synopsis]
* 1654-1655.
* Address to professors of Christianity against persecution
* to such as follow the world`'s fashions
* to the Pope, and all kings, and rulers in Europe, against persecution
* to the justices appointed for trying ministers of religion, being a testimony against hireling ministers
* Samuel Fisher and others are convinced at a meeting at Bomney, where the Lord`'s power is marvellously displayed
* a large meeting at Coggeshall of about two thousand people, which lasted several hours
* many reproaches are cast upon the truth, and lying slanderous books published, which are answered, and the truth set over the gainsayers
* to those who scorn trembling and quaking
* great rage is manifested against the truth and Friends, and their plainness is contemned
* to the churches gathered into outward forms, opening their state and warning of the woes coming upon them
* to the Protector, respecting the imprisonment of Friends for refusing to take oaths and pay tithes, etc.
* to Friends, to offer themselves to lie in prison for a brother or sister
* an encouragement to Friends in their several exercises.

About this time I was moved to write a paper, and send it among the professors;
as follows:--

[.embedded-content-document.paper]
--

[.blurb]
=== "`To all professors of Christianity.

"`All they that professed Jesus Christ in words, and yet heard him not when he was come,
said, he was a deceiver and a devil.
The chief priests called him so.
The Jews said, '`He hath a devil, and is mad; why do ye hear him?`' But others said,
'`These are not the words of him that hath a devil:
can a devil open the eyes of the blind?`' The Jews then doubted,
whether he was the Christ or not; and so all, like the Jews, in the knowledge,
in the notion, that profess Christ without only, where Christ is risen within,
do not own him, but doubt of him; though Christ is the same now and forever.
Jesus Christ said, '`I and my Father are one:`' then the Jews took up stones to stone him.
And where Jesus Christ is now spiritually come and made manifest,
such as are Christians in outward profession only,
have the same hard hearts inwardly now, as the Jews had then;
and cast stones at him where he is risen.
Jesus said, '`For which of these good works do ye stone me?`' The Jews answered,
'`For thy good works we stone thee not; but for blasphemy, in that thou being a man,
makest thyself God.`' Jesus answered them, '`Is it not written in your law, I said,
Ye are gods? and the Scripture cannot be broken.
Say ye of him, whom the Father hath sanctified, and sent into the world,
Thou blasphemest, because I said, I am the Son of God?`' The Jews said to him,
'`Say we not well, that thou hast a devil?`' Jesus answered, '`I honour my Father,
and ye dishonour me.
And they that were in the synagogue rose up, and thrust him out of the city;
and took him up to the edge of the hill whereon their city was built,
to cast him down headlong.
The Pharisees said of him, '`He casteth out devils,
by the prince of devils.`' Jesus Christ was called a glutton and a wine-bibber,
a friend of publicans and sinners; but wisdom is justified of her children.
The officers, when the high-priests and Pharisees asked them,
'`Why have ye not brought him?`' said, '`Never man spake like this man.`' The Pharisees said,
'`Are ye also deceived? Do any of the rulers or of the
Pharisees believe on him?`' but this people,
which know not the law, are accursed.
Nicodemus (he that came unto Jesus by night), said unto them,
'`Doth our law judge any man, before it hear him?`' When Stephen confessed Jesus,
the substance of all figures and types,
and was brought before the chief priests to his trial, he told them,
'`The Most High dwelleth not in temples made with hands:`'
and brought the prophets`' words to witness,
and told them they were stiff-necked, and uncircumcised in heart and ears,
and always resisted the Holy Ghost, as their fathers had done.
Stephen was full of the Holy Ghost, and said he saw Jesus,
and they ran upon him and stoned him to death, as he was calling upon the Lord.
When Paul confessed Jesus Christ and his resurrection, Festus said he was mad.
When Paul preached the resurrection, some mocked; the Jews persuaded the people,
and they stoned him, and drew him out of the city, thinking he had been dead.
They stirred up the Gentiles to make their minds evil-affected towards the brethren.
They stirred up the devout and honourable women, and the chief of the city,
and raised persecution against Paul and Barnabas, and expelled them out of their coasts;
and there was an assault made both of the Gentiles and of the Jews with their rulers,
to use them despitefully and to stone them.
In like manner all in the nature of those Jews now, whose religion stands in notions,
stir up the rulers, and ignorant people, and incense them against Jesus Christ,
to stone all with one consent, in whom he is risen.
This is, that the Scriptures might be fulfilled,
and the blindness of the people discovered.
The same power now is made manifest, and doth overturn the world,
as did then overturn the world, to the exalting of the Lord,
and to the pulling down of the kingdom of Satan and of this world,
and setting up his own kingdom, to his everlasting praise.
The Lord is now exalting himself, and throwing down man`'s self.
The proud one`'s head is aloft, fearing he should lose his pride and his crown.
The priests incense the ignorant people, for fear their trade should go down;
and the professors show forth what is in them, being full of rage;
which proves that Jesus Christ, the substance, is not there;
but a stony heart to stone the precious, where it is risen.
The carnal mind feeds upon the outward letter; earth feeds upon earth;
and that vineyard is not dressed, but is full of briars and nettles; and ravenous beasts,
swine and dogs, wolves and lions, and all venomous creatures lodge in that habitation.
That house is not swept.
These are the persecutors of the just, enemies of the truth, and of Christ;
blasphemers of God and his truth.
These call upon God with their lips, but their hearts are far from him.
These feed on lies, priests and people.
These incense the people, and stir up envy; for it begets its own, one like itself.
These are as the waves of the sea, foaming out their own shame.
These have double eyes, whose bodies are full of darkness.
These paint themselves with the prophets'`, with Christ`'s,
and with the apostles`' words most fair.
Whited walls ye are; painted sepulchres; murderers of the just.
Your eyes, your minds, your hearts are double.
Ye flatterers, repent and turn from your carnal ends, who are full of mischief,
pretending God and godliness, taking him for your cloak; but he will uncover you,
and he hath uncovered you to his children.
He will make you bare, discover your secrets, and take off your crown;
he will take away your mantle and your veil, and strip you of your clothing,
that your nakedness may appear, and how you sit deceiving the nations.
Your abomination and your falseness is now made manifest to them, who are of God;
who in his power triumph over you, rejoice over you, the beast, the dragon,
the false prophet, the seducer, the hypocrite, the mother of all harlots.
Now thou must have thy cup double, give it to her double.
Sing over her, ye righteous ones, sing over them all ye saints; triumph in glory,
triumph over deceit; sing the song of the Lamb, triumph over the world;
spread the truth abroad.
Come ye captive ones out of prison, and rejoice with one accord,
for the joyful days are coming.
Let us be glad and rejoice forever! singleness of heart is come,
pureness of heart is come, joy and gladness is come.
The glorious God is exalting himself; truth hath been talked of, but now it is possessed.
Christ hath been talked of; but now he is come and is possessed.
The glory hath been talked of; but now it is possessed, and the glory of man is defacing.
The Son of God hath been talked of; but now he is come, and hath given us understanding.
"`Unity hath been talked of; but now it is come.
Virgins have been talked of; but now they are come with oil in their lamps.
He will be glorified alone.
Where pride is thrown down, earth and the fleshly will is thrown down,
and the pure is raised up; there alone is the Lord exalted.
Let the heavens bow down to him, and the earth reel to and fro, and stagger up and down.
The Lord is setting up his throne and his crown, and throwing down the crown of man,
and he alone will be glorified; to whom be all honour and glory,
all praises and all thanks!
Who gives his children wisdom and strength, knowledge and virtue, power and riches,
blessings and durable substance; an eye to discern, and an ear to hear things singly;
and brings down the pride of man`'s heart, and turns the wicked out of the kingdom.
The righteous inherit righteousness; the pure, pureness; the holy, holiness.
Praises, praises be to the Lord, whose glory now shines, whose day is broken forth;
which is hid from the world, hid from all worldly-wise ones,
and from all the prudent of this world; hid from the fowls of the air,
hid from all vultures`' eyes, all venomous beasts, all liars, all dogs, and all swine.
But to them that fear his name, the secrets of the Lord are made manifest,
the treasures of wisdom are opened, and the fulness of knowledge: for thou, O Lord,
dost make thyself manifest to thy children.`"

[.signed-section-signature]
G+++.+++ F.

--

My spirit was greatly burdened to see the pride, that existed in the nation,
even among professors,
and in the sense thereof I was moved to give forth the following paper,^
footnote:[The address of George Fox,
"`to such as follow the world`'s fashions,`" a popular writer observes,
"`draws a vivid picture of a fine lady and gentleman of the Commonwealth,
in which their habiliments, vanities, and pastimes are minutely depicted.`"]
directed--

[.embedded-content-document.paper]
--

[.blurb]
=== "`To such as follow the World`'s Fashions.

"`What a world is this! how doth the devil garnish himself!
and how obedient are people to do his will and mind!
They are altogether so carried away with fooleries and vanities, both men and women,
that they have lost the hidden man of the heart, and the meek and quiet spirit;
which with the Lord is of great price.
They have lost the adorning of Sarah; they are putting on gold and gay apparel;
women plaiting the hair, men and women powdering it;
making their backs look like bags of meal.
They look so strange, that they can scarce look at one another,
they are so lifted up in pride.
Pride is flown up into their head, and hath so lifted them up, that they snuff up,
like wild asses; like Ephraim, they feed upon wind; and are like wild heifers,
who feed upon the mountains.
Pride hath puffed up every one of them: they are out of the fear of God, men and women,
young and old: one puffs up another.
They must be in the fashion of the world, else they are not in esteem;
else they shall not be respected, if they have not gold or silver upon their backs,
or if the hair be not powdered.
But if he have store of ribands hanging about his waist, and at his knees,
and in his hat, of divers colours, red, white, black, or yellow,
and his hair be powdered, then he is a brave man; then he is accepted, he is no Quaker,
because he has ribands on his back, and front, and knees, and his hair powdered.
This is the array of the world.
But is not this from the lust of the eye, the lust of the flesh,
or the pride of life? Likewise the women having their gold, their patches on their faces,
noses, cheeks, foreheads; having their rings on their fingers, wearing gold,
having their cuffs double, under and above, like unto a butcher with his white sleeves;
having their ribands tied about their hands,
and three or four gold laces about their clothes; this is no Quaker, say they.
This attire pleaseth the world: and if they cannot get these things,
they are discontented.
But this is not the attire of Sarah, whose adorning was the hidden man of the heart,
the ornament of a quiet and meek spirit.
This is the adorning of the heathen, not of the apostle, nor of the saints,
whose adorning was, not wearing of gold, nor plaiting of hair,
but a meek and quiet spirit; which was and is of great price with the Lord.
Here was the sobriety and good ornament, which was accepted of the Lord.
This was Paul`'s exhortation and preaching; but we see,
the talkers of Paul`'s words live out of Paul`'s command, and out of the example of Sarah;
and are found in the steps of the great heathen,
who comes to examine the apostles in his gorgeous apparel.
Now, are not these, that have got their ribands hanging about their arms, hands, back,
waists, knees, hats,
like unto fiddlers`' boys? This shows that you are got
into the basest and most contemptible life,
who are in the fashion of the fiddlers`' boys and stage-players,
quite out of the paths and steps of solid men;
and in the very steps and paths of the wild heads,
who give themselves up to every invention and vanity of the world that appears,
and are inventing how to get it upon their backs, heads, feet, and legs, and say,
if it be out of the fashion it is nothing worth.
Are not these the spoilers of the creation, who have the fat and the best of it,
and waste and destroy it? Do not these cumber God`'s
earth? Let that of God in all consciences answer,
and who are in the wisdom, judge.
And further, if one get a pair of trousers like a coat, and hang them about with points,
and up almost to the middle, a pair of double cuffs upon his hands,
and a feather in his cap, here is a gentleman; bow before him, put off your hats,
get a company of fiddlers, a set of music, and women to dance.
This is a brave fellow.
Up in the chamber; up in the chamber without, and up in the chamber within.
Are these your fine Christians? Yea, say they, they are Christians. Yea!
But, say the serious people, they are out of Christ`'s life,
and out of the apostles`' command, and out of the saints`' ornament.
And to see such as are before described,
as are in the fashions of the world before-mentioned, a company of them playing at bowls,
or at tables, or at shuffle-board; or each taking his horse,
that has bunches of ribands on his head, as the rider has on his own (who, perhaps,
has a ring in his ear too) and so go to horse-racing, to spoil the creatures; O,
these are gentlemen indeed, these are bred up gentlemen, these are brave fellows,
and they must take their recreation; for pleasures are lawful.
These in their sports set up their shouts, like wild asses.
They are like the kine or beasts, when they are put to grass, lowing when they are full.
Here is the glorying of those before mentioned; but it is in the flesh, not in the Lord.
These are bad Christians, and show that they are gluttoned with the creatures,
and then the flesh rejoiceth.
Here is bad breeding of youth and young women,
who are carried away with the vanities of the mind in their own inventions, pride,
arrogancy, lust, gluttony, uncleanness.
They eat and drink, and rise up to play.
This is the generation which God is not well-pleased with;
for their eyes are full of adultery, and cannot cease from evil.
These be they that live in pleasures upon earth;
these be they who are dead while they live; who glory not in the Lord, but in the flesh.
These be they that are out of the life, that the Scriptures were given forth from;
who live in the fashions and vanities of the world, out of truth`'s adorning,
in the devil`'s adorning (who is out of the truth); and not in the adorning of the Lord,
which is a meek and quiet spirit, which is with the Lord of great price.
But this ornament and this adorning is not put on by them that adorn themselves,
and have the ornament of him that is out of the truth.
That is not accepted with the Lord, which is accepted in their eye.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
Moreover it came upon me about this time from the Lord,
to write a short paper and send forth, as an exhortation and warning to the Pope,
and all kings and rulers in Europe; as follows:--

[.embedded-content-document.paper]
--

[.salutation]
"`Friends,

"`Ye heads, and rulers, kings, and nobles of all sorts, be not bitter,
nor hasty in persecuting the lambs of Christ,
neither turn yourselves against the visitation of God,
and his tender love and mercies from on high, who sent to visit you;
lest the Lord`'s hand, arm, and power, take hold swiftly upon you;
which is now stretched over the world.
It is turned against kings, and shall turn wise men backward,
and will bring their crowns to the dust, and lay them low and level with the earth.
The Lord will be king, who gives crowns to whomsoever obey his will.
This is the age wherein the Lord God of heaven and earth is staining the pride of man,
and defacing his glory.
You that profess Christ, and do not love your enemies,
but on the contrary shut up and imprison those who are his friends;
these are marks that you are out of his life, and do not lore Christ,
who do not the things he commands.
The day of the Lord`'s wrath is kindling,
and his fire is going forth to burn up the wicked;
which will leave neither root nor branch.
They that have lost their habitation with God, are out of the Spirit,
that gave forth the Scriptures,
and from the light that Jesus Christ hath enlightened them withal;
and so from the true foundation.
Therefore be swift to hear, slow to speak, and slower to persecute:
for the Lord is bringing his people to himself, from all the world`'s ways,
to Christ the way; and from all the world`'s churches, to the church which is in God,
the Father of our Lord Jesus Christ; and from all the world`'s teachers,
to teach his people himself by his Spirit; from all the world`'s images,
into the image of himself; and from their likenesses into his own likeness;
and from all the world`'s crosses of stone or wood, into his power,
which is the cross of Christ.
For all these images, crosses, and likenesses, are among them,
that are apostatized from the image of God, the power of God, the cross of Christ,
which now fathoms the world, and is throwing down that which is contrary to it;
which power of God never changes.

"`Let this go to the kings of France, and of Spain, and to the Pope,
for them to prove all things, and to hold that which is good.
And first to prove, that they have not quenched the Spirit:
for the mighty day of the Lord is come, and coming upon all wickedness, and ungodliness,
and unrighteousness of men, who will plead with all flesh by fire and by sword.
And the truth, the crown of glory,
and the sceptre of righteousness over all shall be exalted;
which shall answer that of God in every one upon the earth, though they be from it.
Christ is come a light into the world,
and doth enlighten every one that cometh into the world;
that all through him might believe.
He that feeleth the light that Christ hath enlightened him withal,
he feeleth Christ in his mind, and the cross of Christ, which is the power of God;
he shall not need to have a cross of wood or stone, to put him in mind of Christ,
or of his cross, which is the power of God manifest in the inward parts.`"

[.signed-section-signature]
G+++.+++ F.

--

Besides this I was moved to write a letter to the Protector,
to warn him of the mighty work the Lord hath to do in the nations,
and of the shaking of them; and to beware of his own wit, craft, subtlety, and policy,
or seeking any by-ends to himself.

[.small-break]
'''

There was about this time an order for the trying of ministers (so called),
and for approving, or ejecting them out of their places or benefices;
whereupon I wrote a paper to the justices, and other commissioners,
who were appointed to that work, as follows:--

[.embedded-content-document.paper]
--

[.salutation]
"`Friends,

"`You that are justices, and in commission to try ministers,
who have long been in the vineyard of God,
see whether they be such as are mentioned in the Scriptures, whom the prophets, Christ,
and the apostles, disapproved of.
And if they be such as they disapproved,
see how ye can stand approved in the sight of God, to let such go into his vineyard,
and approve of them who will admire your persons, because of advantage,
and if you do not give them advantage, they will not admire your persons.
Such Jude speaks of.
See if they be not such as teach for filthy lucre, for the love of money, covetous,
such as love themselves, who have a form of godliness, but deny the power;
from such the apostles bid to '`turn away.`' The
apostle said their mouths should be stopped,
who served not the Lord Jesus, but their own bellies, being evil,
who mind earthly things.
Paul gave Timothy a description to try ministers by; he said, '`they must not be covetous,
nor given to wine, nor filthy lucre, nor novices; lest being lifted up into pride,
they fall into the condemnation of the devil:`'
these he was to try and prove without partiality.
Now take heed of approving such as he disapproved;
for since the apostles`' days such as he disapproved have had their liberty;
and they have told us, the tongues were their original, and that they were orthodox men;
and that the steeple-house, with a cross on the top of it,
was the church (the Papist`'s mass-house, you may look on the top of it,
and see the sign). But the Scriptures tell us,
'`all the earth was of one language before the building
of Babel;`' and when Pilate crucified Christ,
he set the tongues, Hebrew, Greek, and Latin, over his head.
And John tells us, that the beast had power over the tongues, kindreds, and nations;
and that the whore sits upon the tongues, of whose cup all nations have drunk,
and the kings of the earth have committed fornication with her.
John also said the tongues are waters.
Christ gives marks to his disciples, and to the multitude,
how to try such as these that you are to try.
They are called of men master; they love the chiefest seat in the assemblies;
they are sayers but not doers; and, said he, they shall put you out of the synagogues.
Seven woes he denounced against them, and so disapproved them.
Christ said, false prophets should come; and John saw they were come;
for they went forth from them, and the world since hath gone after them.
But Babylon must be confounded, the mother of harlots; and the Devil must be taken;
and with him the beast, and the false prophet must be cast into the lake of fire;
for the Lamb and his saints over all must reign, and have the victory.
The Lord God sent his prophets of old, to cry against the shepherds,
that sought for the fleece, Ezek. 34,
and to cry against such shepherds as seek for their gain from their quarter,
and never have enough, Isa. 5:6;
and to cry against the prophets that prophesied falsely,
and the priests that bore rule by their means; which was the filthy and horrible thing, Jer. 5.
And if you would forbear to give them means,
you would see how long they would bear rule.
There was in old time a storehouse for the fatherless, strangers, and widows,
to come to and be filled;
and they did not prosper then who did not bring their tithes to the storehouse.
But did not Christ put an end to that priesthood, tithes, temple,
and priests? And doth not the apostle say, that the priesthood is changed,
the law is changed,
and the commandment disannulled?
Might not they have pleaded the law of God that gave them tithes?
Have ever any of the priests prospered that take tithes since, by the law of man?
Was not the first author of them, since Christ`'s time, the Pope, or some of his church?
Did the apostles cast men into prison for tithes, as your ministers do now?
As instance; Ralph Hollingworth, priest of Phillingham,
for petty tithes, not exceeding six shillings,
has cast into Lincoln prison a poor thatcher, named Thomas Bromby;
where he has been about eight and thirty weeks, and still remains a prisoner.
And the priest petitioned the judge that the poor man might not labour in the city,
to get a little money towards his maintenance in prison.
Is this a good savour amongst you,
that are in commission to choose ministers? Is this glad tidings,
to cast into prison a man that is not his hearer,
because he could not put into his mouth? Can such as are in the fear of God,
and in his wisdom, own such things.
The ministers of Christ are to plant a vineyard, and then eat of the fruit; to plough,
sow, and thrash, and get the corn; and then let them reap;
but not cast them into prison for whom they do no work.
Christ, when he sent forth his ministers, bid them give freely,
as they had received freely; and into what city or town soever they came,
inquire who were worthy and there abide; and what they set before you, said he, that eat.
And when these came back again to Christ, and he asked them if they wanted anything,
they said No. They did not go to a town, and call the people together,
to know how much they might have by the year, as these that are in the apostacy do now.
The apostle said, '`have I not power to eat and to drink?`' But he did not say,
to take tithes, Easter-reckonings, Midsummer-dues, augmentations,
and great sums of money; but '`have I not power to eat and to drink?`'
Yet he did not use that power among the Corinthians.
But they that are apostatized from him, will take tithes, great sums of money,
Easter-reckonings, and Midsummer-dues;
and cast them into prison that will not give it them, whom they do no work for.
The ox`'s mouth must not be muzzled that treads out the corn;
but see if the corn be trodden out in you, and the wheat be in the garner.
This is from a lover of your souls, and one that desires your eternal good.`"

[.signed-section-signature]
G+++.+++ F.

--

After I had made some stay in the city of London,
and cleared myself of what service lay upon me at that time there,
I was moved of the Lord to go down into Bedfordshire to John Crook`'s house, at Luton,
where there was a great meeting, and people generally convinced of the Lord`'s truth.
When I was come thither,
John Crook told me that next day several of those that
were called the gentlemen of the country,
would come to dine with him and to discourse with me.
They came, and I declared to them God`'s eternal truth.
Several Friends went to the steeplehouses that day.
And there was a meeting in the country, which Alexander Parker went to;
and towards the middle of the day it came upon me to go to it,
though it was several miles off.
John Crook went with me.
When we arrived, there was one Gritton, who had been a Baptist,
but was got higher than they, and called himself a trier of spirits.
He told people their fortunes,
and pretended to discover to them when their goods were stolen or houses broken up,
who the persons were that did it;
by which he had got into the affections of many people thereabouts.
This man was in that meeting, speaking,
and making a hideous noise over the young-convinced Friends, when I came in;
and he bid Alexander Parker give a reason of his hope.
Alexander Parker told him, Christ was his hope;
but because he did not answer him so soon as he expected, he boastingly cried,
"`his mouth is stopped.`"
Then Gritton directed his speech to me,
for I stood still and heard him express many things,
which were not agreeable to Scripture.
I asked him, whether he could make those things out by Scripture which he had spoken,
and he said, Yes, yes.
Then I bid the people take out their Bibles to search
the places he should quote for proof of his assertions;
but he could not make good by Scripture that which he had said.
So he was ashamed and fled out of the house, and his people were generally convinced;
for his spirit was discovered, and he came no more amongst them.
When his people were convinced and settled in God`'s truth,
they gave forth a book against him, and denied his spirit and his false discoveries.
Many were turned to Christ Jesus that day, and came to sit under his teaching;
insomuch that the judges were in a great rage,
and many of the magistrates in Bedfordshire,
because there were so many turned from the hireling
priests to the Lord Jesus Christ`'s free teaching.
But John Crook was kept by the power of the Lord;
yet he was discharged from being a justice.^
footnote:[John Crook was a Justice of the Peace,
and a man of note in the county of Bedford.
He became an eminent preacher of the gospel, in which he laboured extensively,
and many were the seals of his ministry.
He suffered many imprisonments, which he bore with patience,
as also his bodily infirmities,
often expressing the inward joy and peace he had with the Lord.
He died in 1699, in the eighty-second year of his age,
having been a minister about forty-four years,
and his writings were published in 1701, entitled,
_The design of Christianity testified in the Books, Epistles, and MSS. of John Crook._]

After some time I returned to London again,
where Friends were finely established in the truth, and great comings-in there were.
About this time several Friends went beyond sea to declare the everlasting truth of God.
When I had stayed a while in the city, I went into Kent.
When we came to Rochester, there was a guard kept to examine passengers,
but we passed by, and were not stopped.
So I went to Cranbrook, where there was a great meeting; several soldiers were at it,
and many were turned to the Lord that day.
After the meeting, some of the soldiers were somewhat rude,
but the Lord`'s power came over them.
Thomas Howsigoe, an Independent preacher, who lived near Cranbrook, was convinced,
and became a faithful minister for the Lord Jesus.
Some Friends had travelled into Kent before, as John Stubbs and William Caton,
and the priests and professors had stirred up
the magistrates at Maidstone to whip them,
for declaring God`'s truth unto them;
as may be seen at large in the Journal of William Caton`'s life.
Captain Dunk was also convinced in Kent.
He went with me to Rye, where we had a meeting; to which the mayor and officers,
and several captains came.
They took down what I said in writing, which I was well pleased with.
All was quiet, and the people affected with the truth.

From Rye I went to Romney, where,
the people having had notice of my coming some time before,
there was a very large meeting.
Thither came Samuel Fisher, an eminent preacher among the Baptists,
who had had a parsonage reputed worth about two hundred pounds a year,
which for conscience sake he had given up.
There was also the pastor of the Baptists, and abundance of their people.
The power of the Lord was so mightily over the meeting, that many were reached thereby,
and one greatly shaken, and the life sprung up in many.
One of the pastors of the Baptists, being amazed at the work of the Lord`'s power,
bid one of our friends that was so wrought upon, have a good conscience;
whereupon I was moved of the Lord to bid him take heed of hypocrisy and deceit;
and he was silent.
A great convincement there was that day;
many were turned from darkness to the divine light of Christ,
and came to see their teachers`' errors,
and to sit under the Lord Jesus Christ`'s teaching, to know him their way,
and the covenant of light, which God had given to be their salvation;
and they were brought to the one baptism, and to the one baptizer, Christ Jesus.
When the meeting was over, Samuel Fisher`'s wife said,
"`Now we may discern this day between flesh and spirit,
and distinguish spiritual teaching from fleshly.`"
The people were generally well satisfied with what had been declared;
but the two Baptist teachers and their company, when they were gone from the meeting,
fell to reasoning amongst the people.
Samuel Fisher, with many others, reasoned for the word of life,
which had been declared that day; and the other pastor and his party reasoned against it;
so it divided them asunder, and cut them in the midst.
A friend came and told me, that the Baptists were disputing one with another;
and desired me to go up to them; but I said "`let them alone, the Lord will divide them;
and they that reason for truth, will be too hard for the other;`" and so it was.
Samuel Fisher received the truth in the love of it, became a faithful minister,
preached Christ freely, and laboured much in the service of the Lord,
being moved to go and declare the word of life at Dunkirk and in Holland,
and in divers parts of Italy, as Leghorn, and Rome itself;
yet the Lord preserved him and his companion John Stubbs, out of their Inquisitions.^
footnote:[Sewell states that Samuel Fisher and John Stubbs, when at Rome,
conversed with some of the cardinals, and testified against Popish superstitions.
They also spread books among the friars,
some of whom expressed their contents to be true; but, said they,
if we should acknowledge this publicly, we might expect to be burned for it.
{footnote-paragraph-split}
Whiting records the death of Samuel Fisher in 1665.
"`Other Friends,`" he says, "`were transported; and many died in Newgate,
and on shipboard, in order to transportation, to the number of 122, in London,
Westminster, and Southwark; particularly Samuel Fisher, etc.,
faithful ministers and labourers in the work of the Lord,
taken at meetings died in the White Lion prison, Southwark, 1665,
in the time of the pestilence +++[+++plague+++]+++,
which began in the time of the persecution of Friends under the Conventicle Act,
as a signal token of the Lord`'s displeasure.
It broke out first in a house next to that of the first man that was banished,
who lived to return to London, and died at a great age.`"]

From Romney I passed to Dover, and had a meeting, where several were convinced.
Near Dover a governor and his wife were convinced, who had been Baptists;
and the Baptists thereabouts were much offended, and grew very envious;
but the Lord`'s power came over all.
Luke Howard of Dover was convinced some time before,
and became a faithful minister of Christ.^
footnote:[For some account of Luke Howard, see _Piety Promoted_, Part ix.
He was several times imprisoned; once in Dover Castle, for sixteen mouths,
for going to meetings.
At this time, he employed six men in his trade,
but was obliged to shut up his shop for six months.
He obtained the use of an entry to the prison grate, where meat was drawn up with a cord,
and he worked a little there.
He suffered another long confinement in 1684.
Speaking of his imprisonments, he says, "`I had perfect peace, joy,
and content in it all; the Lord made it good unto me, both within and without.`"]

Returning from Dover I went to Canterbury,
where a few honest-hearted people were turned to the Lord,
who sat down under Christ`'s teaching.
Thence I passed to Cranbrook again, where I had a great meeting.
A friend went to the steeple-house, and was cast into prison;
but the Lord`'s power was manifested, and his truth spread.

From thence I passed into Sussex, and lodged near Horsham,
where there was a great meeting, and many were convinced.
Also at Steyning we had a great meeting in the market-house, and several were convinced;
for the Lord`'s power was with us.
I had several meetings in the neighbourhood; and among the rest,
one was appointed at a great man`'s house,
and he and his son went to fetch several priests that had threatened to come and dispute.
But none of them came; for the Lord`'s power was mighty in us; a glorious meeting we had.
The man of the house and his son were vexed, because none of the priests would come.
So the hearts of people were opened by the Spirit of God,
and they were turned from the hirelings to Christ Jesus their shepherd,
who had purchased them without money, and would feed them without money or price.
Many that came, expecting to hear a dispute, were convinced;
amongst whom Nicholas Beard was one.^
footnote:[Nicholas Beard was an early seeker of the Lord in his youth,
and would often travel many miles to hear the best reputed teachers of the times.
He became a faithful minister of Christ, and a large sufferer for his sake.
For one year`'s tithes he had taken from him twelve oxen, six cows, and one bull,
which were sold for £111, 5s., but worth more.
For worshipping God, and refusing to swear or bear arms,
he was prosecuted on the statute for £20 a month,
and underwent imprisonment several years,
and loss of goods to more than £1000. Yet it pleased
the Lord to support and bless him and a large family,
so that on his deathbed he was heard to say, "`O Lord, my soul blesseth thee,
and all that is within me magnifieth thy holy name!`"
He often desired to depart and be with Christ, and died in great peace, in 1702,
aged eighty, a minister about thirty years.]

Thus the Lord`'s power came over all, and his day many came to see.
There were abundance of Ranters in those parts,
and professors that had been so loose in their lives, that they began to be weary of it,
and had thought to go into Scotland to live privately.
But the Lord`'s net caught them, and their understandings were opened by his light,
Spirit, and power, through which they came to receive the truth,
and to be settled upon the Lord; and so became very sober men,
and good friends in the truth.
Great blessing and praising of the Lord there was amongst them,
and great admiration in the country.

Out of Sussex I travelled to Reading,
where I found a few that were convinced of the way of the Lord.
There I stayed till First-day, and had a meeting in George Lamboll`'s orchard;
and a great part of the town came to it.
A glorious meeting it proved; a great convincement there was,
and the people were mightily satisfied.
Thither came two of Judge Fell`'s daughters to me, and George Bishop, of Bristol,
with his sword by his side, for he was a captain.^
footnote:[This Captain Bishop, who is mentioned as wearing his sword,
soon discontinued it, being convinced, and joining Friends.
He was the author of _An Account of the Persecution in New England,_
and he issued a prophetic warning to the King and Parliament, in 1664,
for banishing Friends, which was fulfilled.
See Sewell`'s _History_; Index.]
After the meeting many Baptists and Ranters came privately, reasoning and discoursing;
but the Lord`'s power came over them.
The Ranters pleaded, that God made the Devil; I denied it, and told them,
"`I was come into the power of God, the seed Christ, which was before the Devil was,
and braised the head of him; and he became a Devil by going out of truth,
and so became a murderer and a destroyer.
So I showed them that God did not make the Devil; for God is a God of truth,
and he made all things good, and blessed them: but God did not bless the Devil.
And the Devil is bad, and was a liar and a murderer from the beginning,
and spoke of himself and not from God.`"
And so the truth stopped them, and bound them,
and came over all the highest notions in the nation, and confounded them.
For by the power of the Lord God I was manifest,
and sought to be made manifest to the Spirit of God in all; that by it (which they vexed,
and quenched, and grieved) they might be turned to God;
as many were turned to the Lord Jesus Christ by the Holy Spirit,
and were come to sit under his teaching.

After this meeting at Beading I passed up to London, where I stayed a while,
and had large meetings, then into Essex, and came to Coggeshall,
where was a meeting of about two thousand people, as it was supposed,
which lasted several hours, and a glorious meeting it was;
for the word of life was freely declared,
and people were turned to the Lord Jesus Christ, their teacher and their Saviour,
the way, the truth, and the life.

On the sixth day of that week I had a meeting near Colchester,
to which many professors and the Independent teachers came.
After I had done speaking, and was stepped down from the place on which I stood,
one of the Independent teachers began to make a jangling; which Amor Stoddart perceiving,
said to me, "`Stand up again, George; for I was going away,`"
and did not at first hear them.
But when I heard the jangling Independent, I stood up again;
and after a while the Lord`'s power came over him and his company;
and they were confounded, and the Lord`'s truth went over all.
A great flock of sheep hath the Lord Jesus Christ in that country,
that feed in his pastures of life.
On the First-day following we had a very large meeting, near Colchester,
wherein the Lord`'s power was eminently manifested,
and the people were very well satisfied; for they were turned to Christ`'s free teaching,
and received it gladly.
Many of these people had been of the stock of the martyrs.

As I passed through Colchester, I went to visit James Parnell in prison,
but the cruel jailer would hardly let us come in, or stay with him.
Very cruel they were to him; the jailer`'s wife threatened to have his blood;
and in that jail they destroyed him,
as the reader may see in a book printed soon after his death,
giving an account of his life and death;
and also in an epistle printed with his collected books and writings.

From Colchester I went to Ipswich, where we had a little meeting, and very rude;
but the Lord`'s power came over them.
After the meeting I said,
"`if any had a desire to hear further, they might come to the inn;`"
and there came in a company of rude butchers,
that had abused Friends;
but the Lord`'s power so chained them that they could not do mischief.
Then I wrote a paper, and gave it forth to the town,
"`warning them of the day of the Lord, that they might repent of the evils they lived in;
directing them to Christ, their teacher, and way;
and exhorting them to forsake their hireling teachers.`"

We passed from Ipswich to Mendelsham, in Suffolk, where Robert Duncan lived.
There we had a large quiet meeting, and the Lord`'s power was preciously felt amongst us.
Then we passed to a meeting at Captain Lawrence`'s in Norfolk; where, it was supposed,
were above a thousand people; and all was quiet.
Many persons of note were present, and a great convincement there was;
for they were turned to Christ, their way and their teacher,
and many of them received him, and sat down under him, their vine.
Here we parted with Amor Stoddart and some other Friends,
who intended to meet us again in Huntingdonshire.

About two in the morning we took horse for Norwich, where Christopher Atkins had run out,
and brought dishonour upon the blessed truth and name of the Lord.
But he had been denied by Friends;
and afterwards he gave forth a paper of condemnation of his sin and evil.
We came to Yarmouth, and there stayed a while; where there was a Friend, Thomas Bond,
in prison for the truth of Christ.
There we had some service; and some were turned to the Lord in that town.
From thence we rode to another town, about twenty miles off,
where were many tender people; and I was moved of the Lord to speak to them,
as I sat on my horse, in several places as I passed along.
We went to another town about five miles from thence, and set up our horses at an inn,
Richard Hubberthorn and I having travelled five and forty miles that day.
There were some friendly people in the town; and we had a tender,
broken meeting amongst them, in the Lord`'s power, to his praise.

We bid the hostler have our horses ready by three in the morning;
for we intended to ride to Lynn, about three and thirty miles, next morning.
But when we were in bed at our inn, about eleven at night,
the constable and officers came, with a great rabble of people, into the inn,
and said they were come with a hue and cry from a justice of peace,
that lived near the town about five miles off,
where I had spoken to the people in the streets, as I rode along,
to search for two horsemen, that rode upon gray horses, and in gray clothes;
a house having been broken up on the seventh-day before at night.
We told them "`we were honest, innocent men, and abhorred such things;`"
yet they apprehended us,
and set a guard with halberts and pikes upon us that night;
making some of those friendly people, with others, to watch us.
Next morning we were up betimes,
and the constable with his guard carried us
before a justice of peace about five miles off.
We took two or three of the sufficient men of the town with us,
who had been with us at the great meeting at Captain Lawrence`'s,
and could testify that we lay both the Seventh-day night, and the First-day night,
at Captain Lawrence`'s;
and it was the Seventh-day night that they said the house was broken up.
The reader is to be informed,
that during the time that I was a prisoner at the Mermaid at Charing-Cross,
this Captain Lawrence brought several Independent justices to see me there,
with whom I had much discourse; which they took offence at.
For they pleaded for imperfection, and to sin as long as they lived;
but did not like to hear of Christ teaching his people himself,
and making people as clear, whilst here upon the earth,
as Adam and Eve were before they fell.
These justices had plotted together this mischief against me in the country,
pretending a house was broken up; that they might send their hue and cry after me.
They were vexed also, and troubled,
to hear of the great meeting at John Lawrence`'s aforesaid;
for a colonel was convinced there that day, who lived and died in the truth.
But Providence so ordered,
that the constable carried us to a justice about
five miles onward in our way towards Lynn,
who was not an independent justice, as the rest were.
When we were brought before him, he began to be angry,
because we did not put off our hats to him.
I told him, I had been before the Protector, and he was not offended at my hat;
and why should he be offended at it,
who was but one of his servants? Then he read the hue and cry; and I told him,
"`that that night, wherein the house was said to be broken up,
we were at Captain Lawrence`'s house;
and that we had several men present who could testify the truth thereof.`"
Thereupon the justice, having examined us and them, said,
"`he believed we were not the men that had broken the house; but he was sorry,`" he said,
"`that he had no more against us.`"
We told him, "`he ought not to be sorry for not having evil against us;
but rather to be glad; for to rejoice, when he got evil against people,
as for housebreaking, or the like, was not a good mind in him.`"
It was a good while yet, before he could resolve, whether to let us go,
or send us to prison; and the wicked constable stirred him up against us, telling him,
"`we had good horses, and that if it pleased him, he would carry us to Norwich jail.`"
But we took hold of the justice`'s confession,
that "`he believed we were not the men that had broken the house;`"
and after we had admonished him to fear the Lord in his day,
the Lord`'s power came over him, so that he let us go; so their snare was broken.
A great people were afterwards gathered to the Lord in that town,
where I was moved to speak to them in the street; and from whence the hue and cry came.

Being set at liberty, we travelled to Lynn; where we arrived about three in the afternoon.
Having set up our horses, we met with Joseph Fuce,^
footnote:[Joseph Fuce was one of those faithful ministers who died in White Lion prison,
Southwark, in 1665, during the time of the plague.]
who was an ensign;
and we wished him to speak to as many of the
people of the town as he could that feared God;
and to the captains and officers to come together: which he did.
We had a very glorious meeting amongst them, and turned them to the Spirit of God,
by which they might know God and Christ, and understand the Scriptures;
and so learn of God and of Christ, as the prophets and apostles did.
Many were convinced there; and a fine meeting there is,
of them that are come off from the hirelings`' teaching,
and sit under the teaching of the Lord Jesus Christ.

Lynn being then a garrison,
we desired Joseph Fuce to get us the gate opened by three next morning,
for we had forty miles to ride next day.
By that means getting out early, we came next day by eleven or twelve to Sutton,
near the Isle of Ely, where Amor Stoddart, and the Friends with him, met us again.
A multitude of people was gathered there, and no less than four priests.
The priest of the town made a great jangle; but the Lord`'s power so confounded him,
that he went away: the other three stayed; and one of them was convinced.
One of the other two, whilst I was speaking, came to lean upon me;
but I bid him sit down, seeing he was so slothful.
A great convincement there was that day;
and many hundreds were turned from darkness to the light,
from the power of Satan unto God, and from the spirit of error to the Spirit of truth,
to be led thereby into all truth.
People came to this meeting from Huntingdon, and beyond;
and the mayor`'s wife of Cambridge was there also.
A glorious meeting it was, and many were settled under Christ`'s teaching, and knew him,
their Shepherd, to feed them; for the word of life was freely declared,
and gladly received by them.
The meeting ended in the power of the Lord, and in peace;
and after it I walked out and went into a garden; where I had not been long,
before a Friend came to me,
and told me several justices were come to break up the meeting.
But many of the people were gone away; so they missed of their design:
and alter they had stayed a while, they went away also, in a fret.

That evening I passed to Cambridge.
When I came into the town, the scholars hearing of me, were up, and were exceedingly rude.
I kept on my horse`'s back, and rode through them in the Lord`'s power;
but they unhorsed Amor Stoddard before he could get to the inn.
When we were in the inn, they were so rude in the courts, and in the streets,
that miners, colliers, and carters could never be ruder.
The people of the house asked us "`what we would have for supper.`"
"`Supper!`" said I, "`were it not that the Lord`'s power is over them,
these rude scholars look as if they would pluck us in pieces, and make a supper of us.`"
They knew I was so against the trade of preaching,
which they were there as apprentices to learn,
that they raged as much as ever Diana`'s craftsmen did against Paul.
At this place John Crook met us.
When it was within night, the mayor of the town, being friendly,
came and fetched me to his house; and as we walked through the streets,
there was a bustle in the town; but they did not know me, it being darkish.
They were in a rage, not only against me, but against the mayor also;
so that he was almost afraid to walk the streets with me, for the tumult.
We sent for the friendly people, and had a fine meeting there in the power of God;
and I stayed there all night.
Next morning, having ordered our horses to be ready by six,
we passed peaceably out of town; and the destroyers were disappointed;
for they thought I would have stayed longer, and intended to do us mischief;
but our passing away early in the morning frustrated their evil purposes against us.

Then we rode to Bishop-Stortford, where some were convinced: and so to Hertford,
where also there were some convinced; and where there is now a large meeting.
From thence we returned to London, where Friends received us gladly;
the Lord`'s power having carried us through many snares and dangers.
Great service we had for the Lord;
for many hundreds were brought to sit under the teaching of the Lord Jesus Christ,
their Saviour, and to praise the Lord through him.
James Nayler also was come up to London;
and Richard Hubberthorn and I stayed some time in the city,
visiting Friends and answering gainsayers;
for we had great disputes with professors of all sorts.
Many reproaches they cast upon truth;
and lying slanderous books they gave forth against us: but we answered them all,
cleared God`'s truth, and set it over them; and the Lord`'s power was over all.

[.offset]
Amongst other services for the Lord, which then lay upon me in the city,
I was moved to give forth a paper to those that made a scorn of trembling and quaking;
which is as follows:--

[.embedded-content-document.paper]
--

"`The word of the Lord to all you that scorn trembling, and quaking; who scoff at, scorn,
stone, and belch forth oaths against, those who are trembling and quaking;
threatening them, and beating them.
Strangers ye are to all the apostles and prophets;
and are of the generation that stoned them, and mocked them in those ages.
Ye are the scoffers of whom they spoke, that are come in the last times.
Be ye witnesses against yourselves.
To the light in all your consciences I speak,
that with it you may see yourselves to be out of the life of the holy men of God.

"`Moses, who was judge over all Israel, trembled, feared, and quaked:
when the Lord said unto him, '`I am the God of Abraham, the God of Isaac,
and the God of Jacob, then Moses trembled, and durst not behold.`' This,
which makes to tremble now, ye teachers and people scoff at,
and scorn them in your streets who witness the power of the Lord.
Moses forsook the pleasures of the world, which he might have enjoyed for a season.
He might have been called the son of Pharaoh`'s daughter; he refused it,
and forsook Pharaoh`'s house; yet was no vagabond.
David, a king, trembled; he was mocked; they made songs on him;
they wagged their heads at him.
Will you profess David`'s words, and Moses`'s words,
who are in the generation of your fathers, mockers, scoffers, wonderers, and despisers,
who are to perish?
O blush! be ashamed of all your profession, and be confounded!
Job trembled, his flesh trembled, and they mocked him:
so do you now mock them in whom the same power of God is made manifest;
and yet you profess Job`'s words.
O deceitful hypocrites! will ye not own Scripture?
O shame! never profess Scripture words,
and deny the power, which, according to Scripture,
makes the keepers of the house to tremble, and the strong man to bow himself.
These things both priests, magistrates, and people scoff at;
but with the power ye are judged, and by the power and life condemned.

"`The prophet Jeremiah trembled, he shook, his bones quaked, he reeled to and fro,
like a drunken man, when he saw the deceits of the priests and prophets,
who were turned from the way of God; they were not ashamed, neither could they blush.
Such were gone from the light; and such were they that ruled over the people.
But he was brought to cry, O foolish people! that had eyes, and could not see;
that had ears, and could not hear; that did not fear the Lord,
and tremble at his presence, who placed the sands for bounds to the sea,
by a perpetual decree, that the waves thereof cannot pass!
And he said, '`A horrible thing is committed in the land; the prophets prophesy falsely,
and the priests bear rule by their means.
Shall not I visit for these things, saith the Lord?
Shall not my soul be avenged upon such a nation as this?
They were such as did not tremble at the word of the Lord;
therefore he called them a foolish people.
Hear all ye the word of the Lord, ye foolish people, who scorn trembling and quaking.
Give over professing the prophet Jeremiah`'s words, and making a trade of them;
for with his words you are judged to be among the scoffers, scorners, and stockers.
For he was stocked by your generation;
and you now stock them that tremble at the word of the Lord,
at the power of the mighty God, which raises up the seed of God,
and throws down the earth which hath kept it down.
So, you who`' are in the fall where death reigneth, who are enemies of the truth,
despising the power of God, as those of your generation ever did,
woe and misery is your portion, except you speedily repent.

"`Isaiah saith, '`Hear the word of the Lord, ye that tremble at his word.`' Again,
'`To this man will I look, even to him that is poor, and of a contrite spirit,
and trembleth at my word.`' Isa. 65:2.
'`Your brethren that hated you,
that cast you out for my name`'s sake, said, Let the Lord be glorified;
but he shall appear to your joy, and they shall be ashamed.`' Isa. 66:5.
Now all ye scoffers and scorners,
that despise trembling, you regard not the word of the Lord;
they are not regarded by you, that tremble at the word; who are regarded by the Lord:
therefore you are contrary to Isaiah`'s words.
Profess him and his words no more, for shame, nor make a trade of his words,
ye that seek for your gain from your quarter, ye greedy, dumb dogs,
that never have enough; ye are they that despise trembling;
ye are such as Isaiah cried against, who himself witnessed trembling.
Here therefore be ye witnesses against yourselves,
that with the light in your consciences ye may
see ye are out of the prophet Isaiah`'s spirit,
and are haters of them that tremble, whom the Lord regards; such you regard not,
but hate and persecute, mock and rail against them.
It is manifest that you walk in the steps of your forefathers,
that persecuted the prophets.

"`Habakkuk, the prophet of the Lord, trembled.
And Joel, the prophet of the Lord, said, '`Blow the trumpet in Zion,
and let all the inhabitants of the earth tremble: the people shall tremble,
and all faces shall gather blackness,
and the people shall be much pained.`' And now this
trembling is witnessed by the power of the Lord.
This power of the Lord is come; the trumpet is sounding; the earth is shaking,
the inhabitants of the earth are trembling; the dead are arising,
and the living are praising God; the world is raging, and the scoffers are scorning;
and they that witness trembling and quaking wrought in them by the power of the Lord,
can scarcely pass up and down the streets, but with stones and blows, fists and sticks,
or dogs set at them; or they are pursued with mockings and reproaches.
Thus you vent forth your malice against them that witness the power of the Lord,
as the prophets did; who are come to the broken heart and contrite spirit,
who tremble at the word of the Lord, and whom the Lord regards:
these you stone and stock, and set your dogs at; these you scoff and scorn,
these you revile and reproach: but these reproaches are our riches;
praised be the Lord who hath given us power over them.
If you see one, as Habakkuk, whose '`lips quivered,`' whose '`belly shook,`' who said,
'`rottenness was entered into his bones,`' and who '`trembled in
himself;`' if you see such a one in this condition now,
ye say, he is bewitched.
Here again you show yourselves strangers to that power, to that life,
that was in the prophet: therefore, for shame, never make a profession of his words,
nor a trade of his words; nor of Joel`'s, who witnessed trembling,
which ye scorn and scoff at.
Ye proud scoffers and scorners, misery, misery is your end, except you speedily repent.

"`Daniel, a servant of the most high God, trembled;
his strength and his breath were gone: he was imprisoned, he was hated,
he was persecuted.
They laid baits and snares for him, in whom the Holy Spirit of God was.
Now for shame, you that make a profession of Daniel`'s words, give over your profession;
priests and people, who scorn and scoff at trembling,
with the light you are seen to be out of Daniel`'s life,
and by the same power you are judged, at which you scorn and scoff.
Here again be ye witnesses against yourselves,
that ye are scorners and scoffers against the truth;
and with the Scripture ye are judged to be contrary to the life of the holy men of God.

"`Paul, a minister of God, made, by the will of God, a messenger of the Lord Jesus,
a vessel of the Lord, to carry his name abroad into several nations, trembled;
and when the dark, blind world, having got some of his words and epistles,
you teachers make a trade of them, and obtain great sums of money by it,
and so destroy souls for dishonest gain; making a trade of his words,
and of the rest of the apostles`' and prophets'`, and of Christ`'s words,
but denying the Spirit and life that they were guided by;
and that power which shook the flesh and the earth, which the apostle witnessed,
who said, when he came among the Corinthians, that '`he was with them in weakness,
and in fear,
and in much trembling,`' that their faith might not stand in the wisdom of men,
but in the power of God; in that power which made him to tremble.
This power it is that the world, and all the scoffing teachers,
scoff at and scorn in your towns, in your villages, in your assemblies,
in your ale-houses.
For shame, lay aside all your profession of the apostle`'s words and conditions!
Some of them that scoff at this power, call it the power of the devil.
Some persecute, stone and stock, imprison and whip them,
in whom that power is made manifest, and load them with reproaches,
as not worthy to walk on the earth; hated and persecuted,
as the off-scouring of all things.
Here you may see you are in the steps of your forefathers, who persecuted the apostles,
and acted so against them; stocked them, mocked them, imprisoned them, stoned them,
whipped them, haled them out of the synagogues, reproached them,
and shamefully entreated them.
Do not you here fulfill the Scripture, and Christ`'s saying, who said,
'`If they kill you, they will think they do God service?`'
Yet you make a profession of Christ`'s words,
of the prophets`' and apostles`' words, and call yourselves churches,
and ministers of the gospel.
I charge you, in the presence of the living God, to be silent who act such things!
Mind the light in your consciences, ye scoffers and scorners,
which Christ hath enlightened you withal: that with it ye may see yourselves,
what ye act, and what ye have acted;
for they who act such things shall not inherit the kingdom of God:
all such things are by the light condemned.

"`You who have come to witness trembling and quaking,
the powers of the earth to be shaken, the lustful nature to be destroyed,
the scorning and scoffing nature judged by the light;
wait in it to receive power from him who shakes the earth.
That power we own, and our faith stands in it, which all the world scoffs at;
the lofty ones, the proud, the presumptuous, who live in presumption,
and yet make a profession of the Scriptures, as your fathers the Pharisees did,
who were painted sepulchres and serpents; and as the scribes did,
who had the chiefest places in the assemblies, stood praying in the synagogues,
and were called of men masters, which Christ cried woe against.
These are not come so far as the trembling of devils, who believed and trembled.
Let that judge you.
The light and life of the Scripture is seen and made manifest,
and with it all you scoffers and scorners, all you persecutors and railers are seen.

"`Take warning, all ye powers of the earth,
how ye persecute them whom the world nickname and call Quakers,
who dwell in the eternal power of God; lest the hand of the Lord be turned against you,
and ye be all cut off.
To you this is the word of God.
Fear and tremble, and take warning! for this is the man whom the Lord doth regard,
who trembles at his word; whom you, who are of the world, scoff and scorn, stock,
persecute, and imprison.
Here ye may see ye are contrary to God and to the prophets;
and are such as hate what the Lord regards; which we, whom the world scorns,
and calls Quakers, own.
We exalt and honour that power, that makes the devils tremble, shakes the earth,
and throws down the loftiness and the haughtiness of man;
which makes the beasts of the field to tremble, and the earth to reel to and fro;
which cleaves the earth asunder, and overturneth the world.
This power we own, and honour, and preach; but all scoffers and persecutors,
railers and scorners, stockers and whippers,
we deny by that power which throweth down all that nature;
seeing that all who act such things, without repentance,
shall not inherit the kingdom of God, but are for destruction.

"`Rejoice all ye righteous ones, who are persecuted for righteousness`' sake;
for great is your reward in heaven.
Rejoice, ye that suffer for well-doing; for ye shall not lose your reward.
Wait in the light, that you may grow up in the life that gave forth the Scriptures;
that with it you may see the saints`' conditions,
and all that which they testified against;
and there with it ye will see the state of those that reproached and scoffed at them;
that mocked and persecuted them; that whipped and stocked them,
and haled them out of the synagogues before magistrates.
To you, who are in the same light and life, the same things do they now;
that they may fill up the measure of their fathers.
With the light now they are seen, where the light, and life,
and power of God is made manifest; for as they did unto them, so they will do unto you.
Here is our joy; the Scripture is fulfilled, and fulfilling; and with the light,
which was before the world was, which is now made manifest in the children of light,
they see the world, and comprehend it, and the actions of it;
for he that loves the world, and turns from the light, is an enemy to God;
he turneth into wickedness; for the whole world lieth in wickedness.
He who turns from the light, turns into the works of evil,
which the light of Christ testifies against; and by this light,
where it is made manifest, all the works of the world are seen and made manifest.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
This is to go abroad among the scattered ones, and among the world.

--

Great was the rage and enmity of professors, as well as profane,
against the truth and people of God at this time;
and great the contempt and disdain they showed of Friends`' plainness.
Wherefore I was moved to write the following, and sent it forth:--

[.embedded-content-document.epistle]
--

[.blurb]
=== "`An Epistle to Churches gathered into outward forms, upon the earth.

"`All ye churches gathered into outward forms upon the earth,
the Son of God is come to reign; he will tread and trample,
will shake and make you quiver, you that are found out of his light,
without his life and power.
His day hath appeared; mortar and clay, will you be found.
Breaking, shaking,
and quaking are coming among you! your high building is to be laid desolate;
your professed liberty shall be your bondage;
the mouth of the Lord of hosts hath spoken it.
Tremble, ye hypocrites, ye notionists! the fenced cities shall be laid desolate,
the fruitful fields shall become a wilderness;
your false joy shall become your heaviness;
the time of weeping and desolation draweth nigh!
Come, ye witty ones, see how ye can stand before the Almighty,
who is now come to plead with you; you will fall like leaves, and wither like weeds!
Come, you that have boasted of my name, saith the Lord, and have gloried in the flesh,
ye shall fade like a flower; who have slain my witness, yet boast of my words,
which have been as a song unto you.
Come, ye novelists, who love novelties, changeable suits of apparel,
who are in the fashions, outward and inward, putting on one thing this day,
and another the other day.
'`I will strip thee,`' saith the Lord, '`I will make thee bare, I will make thee naked,
and thou shalt know that I am the Lord.
What! hast thou professed the prophets`' words?
hast thou professed the apostles`' words, and my Son`'s words?
hast thou covered thyself with their expressions?
thinkest thou not that I see thee out of my life? thinkest thou,
thou witty one, to hide thyself where none can see thee? thinkest thou,
if thou fliest to the uttermost parts of the earth,
that I am not there? Is not the earth mine, and the fulness of it, saith the Lord?`' Come,
all ye that have trusted in your own conceited notions, and knowledge, and wisdom,
who were never yet out of the earth, and the lusts of it;
never yet got the load of thick clay off you; never were out of the drunken spirit,
whose imperfection appears, which must be come upon, as a potter`'s vessel;
broken cisterns; ye that have been made wise in your own conceit, wise in your own eyes,
in which pride hath lifted you up, and not the humility; you must be abased.
You have run on, every one after his own invention;
every man hath done the thing that was right in his own eyes, that which pleased himself.
This hath been the course of people upon earth.
Ye have run on without a king, without Christ, the light of the world,
which hath enlightened every one that is come into the world.
But now is truth risen, now are your fruits withering.

"`And you that are fortified, and have fortified your strong houses,
called your churches, make ye your cords strong, the Lord will break you asunder,
ye that are gathering in, and ye that are gathered.
For the Lord is risen to scatter you; his witness is risen in the hearts of his people,
they will not be fed with dead words, nor with that which dies of itself;
nor will they be satisfied with the husks which the swine feed upon.
All ye priests in the nation, and teachers, that now stand against the light,
your envy shows that ye are in Cain`'s way;
your greediness shows that ye are in Balaam`'s way;
your standing against the light which hath
enlightened every man that cometh into the world,
doth manifest that you are in Korah`'s way, that spoke the great high words of vanity; ye,
whose consciences are seared as with a hot iron, whose judgment doth not linger,
whose damnation doth not slumber, who serve not the Lord Jesus Christ,
but your own bellies; who are the evil beasts spoken of,
which have destroyed many families, taken away their cattle, their horses, their goods,
even their household goods; destroyed many poor men, even whole families,
taking their whole estates from them, whom you do no work for.
O! the grievous actions that are done by you, the ministers of unrighteousness;
whose fruits declare to the whole nation that you are
the devil`'s messengers! your actions declare it;
your taking tithes, augmentations, treble damages, Midsummer-dues (as ye call them),
of them ye do no work for, nor minister to.

"`All ye powers of the earth, beware of holding such up as are unrighteous.
Let not the words of the unrighteous overcome you, lest God,
the righteous judge of heaven and earth, take hold upon you;
whose judgment is according to that of God in you,
which will let you see when you transgress.
Come you proud and lofty ones, who have not considered the handy-works of the Lord,
but have destroyed them; nor have regarded the way of the Lord,
but have had plenty of the creatures, and have therewith fattened yourselves,
and forgotten the Lord and his way: O let shame cover your faces here upon earth!
Come, ye that are given to pleasures, and spend your time in sports, and idleness,
and fulness; your fruits declare the sins of Sodom; yet you will talk of my name,
and of my saints`' words.
'`But I behold you afar off,`' saith the Lord; you are proud and lofty;
you are evil patterns, bad examples, full, rich, and idle; who say, others are idle,
that cannot maintain your lusts.
O! the unrighteous balances that are among people!
O! the iniquity in measuring!
O! the oppression in ruling and governing!
Because of these things my hand shall come upon you, saith the Lord.
For the oppression is entered into the ears of the Lord, who gives rest to the wearied,
to the burdened, to the oppressed; who feeds the hungry, and clothes the naked;
who brings the mighty from their seats, beats the lofty to the ground,
and makes the haughty bend.

"`Come, saith the Lord, ye mockers, scorners, and rebellious ones, light and wild people,
vain and heady; you have had your day of joy, you have scoffed,
you have mocked and derided my messengers and my ambassadors,
who have preached in your streets, and cried in your synagogues and temples;
a day of trembling and lamentation shall come upon you, when you are not aware.
I will take away your pride and your height; I will shake you as a leaf,
and bring you to be as men distracted.
I will distract you, and make you that you shall not trust one another in the earth,
who have joined hand in hand against my servants in the truth.
I will smite you with terrors, and bring fear upon you;
the cup of my indignation and fury shall you drink.
Where will you appear when repentance is hid from your eyes, when profane Esau,
your father, is set before you, and Ishmael and Cain, wild and envious,
whose fruits declare the stock?

"`Come, ye proud priests, who have eaten up the fat of the nation,
who by violence have taken other men`'s goods, whose envy hath slain many,
whose wickedness and darkness hath abounded, and whose unrighteousness daily appears;
your fruits every day declare it,
in summoning up by writs and subpoenas from most
parts of the nation for wages and tithes,
such as you do no work for.
O abominable unrighteousness! how is the state of man lost,
that they do not take these things to heart to feel them! what
havoc is made in most parts of the nation with such!
And all ye priests and teachers, who are railing and brawling in the pulpit,
setting people at variance one against another, haters and hateful,
provoking people to hate one another, here is the seed of enmity seen,
which you have sown and are sowing, whose seed must be bruised by the seed of the woman,
which above your heads is set.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
This year came out the oath of abjuration, by which many Friends suffered;
and several went to speak to the Protector about it; but he began to harden.
And sufferings increasing upon Friends,
by reason that envious magistrates made use of that oath as a snare to catch Friends in,
who, they knew, could not swear at all; I was moved to write to the Protector,
as follows:--

[.embedded-content-document.letter]
--

"`The magistrate is not to bear the sword in vain,
who ought to be a terror to evil-doers;
but as the magistrate that doth bear the sword in vain, is not a terror to evil-doers,
so he is not a praise to them that do well.
Now hath God raised up a people by his power, whom people, priests, and magistrates,
who are out of the fear of God, scornfully call Quakers,
who cry against drunkenness (for drunkards destroy God`'s creatures),
and against oaths (for because of oaths the land mourns),
and these drunkards and swearers, to whom the magistrate`'s sword should be a terror, are,
we see, at liberty; but for crying against such, many are cast into prison;
as also for testifying against their pride and filthiness,
their deceitful merchandize in markets, their cozening and their cheating,
their excess and naughtiness, their playing at bowls and shuffle-boards,
at cards and at dice, and their other vain and wanton pleasures.
They who lire in pleasures, are dead while they live; and they who live in wantonness,
kill the just.
This we know by the Spirit of God, which gave forth the Scriptures,
which the Father has given to us, and hath placed his righteous law in our hearts;
which law is a terror to evil-doers,
and answers that which is of God in every man`'s conscience.
They who act contrary to the measure of God`'s Spirit in every man`'s conscience,
cast the law of God behind their backs,
and walk despitefully against the Spirit of grace.
The magistrate`'s sword, we see, is borne in vain,
whilst the evil-doers are at liberty to do evil; and they that cry against such,
are for so doing punished by the magistrate,
who hath turned his sword backward against the Lord.
Now the wicked one fenceth himself,
and persecutes the innocent as vagabonds and wanderers, for crying against sin,
and against unrighteousness and ungodliness openly, in the markets and in the highways;
or as railers,
because they tell them what judgment will come upon them that follow such practices.
Here they that depart from iniquity are become a prey, and few lay it to heart.
But God will thrash the mountains, beat the hills, cleave the rocks,
and cast into his press, which is trodden without the city,
and will bathe his sword in the blood of the wicked and unrighteous.
You that have drunk the cup of abominations, a hard cup have you had to drink;
you are the enemies of God, and of you he will be avenged.

"`Now ye, in whom something of God is remaining, consider;
if the sword was not borne in vain, but turned against the evil-doers,
then the righteous would not suffer, and be cast into holes, dungeons, corners, prisons,
and houses of correction, as peace-breakers, for testifying against sin openly,
as they are commanded of the Lord, and against the covetousness of the priests,
and their false worships; who exact money of poor people, whom they do no work for.
O! where will you appear in the day of the Lord? or how will you
stand in the day of his righteous judgment? How many jails and houses
of correction are now made places to put the lambs of Christ in,
for following him, and obeying his commands, which are too numerous to mention.
The royal law of Christ, '`to do as ye would be done by,`' is trodden down under foot;
so that men can profess him in words, but crucify him wheresoever he appears,
and cast him into prison,
as the talkers of him always did in the generations and ages past.
The labourers, which God, the master of the harvest, hath sent into his vineyard,
do the chief of the priests, and the rulers now take counsel together against,
to cast them into prison: and here are the fruits of priests, and people, and rulers,
without the fear of God.
The day is come and coming, that every man`'s work doth appear, and shall appear;
glory be to the Lord God forever.
So see, and consider the days you have spent, and do spend;
for this is your day of visitation.
Many have suffered great fines, because they could not swear,
but obey Christ`'s doctrine, who saith,
'`Swear not at all`' and are made a prey upon for abiding in the command of Christ.
Many are cast into prison because they cannot take the oath of abjuration,
though they denied all that is abjured in it;
and by that means many of the messengers and ministers of the Lord
Jesus Christ are cast into prison because they will not swear,
nor go out of Christ`'s command.
Therefore, O man, consider; to the measure of the life of God in thee I speak.
Many also lie in jails, because they cannot pay the priest`'s tithes;
many have their goods spoiled, and treble damages taken of them;
and many are whipped and beaten in the house of correction, without breach of any law.
These things are done in thy name, in order to protect them in these actions.
If men fearing God bore the sword, if covetousness were hated,
and men of courage for God were set up, then they would he a terror to evil-doers,
and a praise to them that do well; and not cause them to suffer.
Here equity would be heard in our land, and righteousness would stand up and take place;
which giveth not place to the unrighteous, but judgeth it.
To the measure of God`'s Spirit in thee I speak, that thou mayest consider,
and come to rule for God;
that thou mayest answer that which is of God in every man`'s conscience; for this is that,
which bringeth to honour all men in the Lord.
Therefore consider for whom thou dost rule,
that thou mayest come to receive power from God to rule for him;
and all that is contrary to God may by his light be condemned.

[.signed-section-closing]
"`From a lover of thy soul, who desires thy eternal good.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
But sufferings and imprisonments continuing and increasing,
and the Protector (under whose name they were inflicted),
hardening himself against the complaints that were made to him,
I was moved to issue the following amongst Friends,
to bring the weight of their sufferings more heavy upon the heads of the persecutors:--

[.embedded-content-document.letter]
--

"`Who is moved by the power of the Lord to offer
himself to the justice for his brother or sister,
that lies in prison, and to go lie there in their stead,
that his brother or sister may come out of prison,
and so offer his life for his brother or sister? Where any lie in prison for tithes,
witnessing the priesthood changed, that took tithes,
and the unchangeable priesthood come; if any brother in the light,
who witnesseth a change of the old priesthood that took tithes,
and a disannulling of the commandment for tithes,
be moved of the Lord to go to the priest or impropriator,
to offer himself to lie in prison for his brother, and to lay down his life,
that he may come forth, he may cheerfully do it,
and heap up coals of fire upon the head of the adversary of God.
Likewise where any suffer for the truth by them who are in the untruth,
if any Friends be moved of the Lord to go to the magistrate, judge, general,
or protector, and offer up themselves to lay down their lives for the brethren;
as Christ hath laid down his life for you, so lay down your lives one for another.
Here you may go over the heads of the persecutors, and reach the witness of God in all.
And this shall rest a judgment upon them all forever,
and be witnessed to by that which is of God in their consciences.
Given forth from the Spirit of the Lord through,`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
Besides this, I wrote also a short epistle to Friends,
as an encouragement to them in their several exercises; which was as follows;--

[.embedded-content-document.epistle]
--

[.salutation]
"`My Dear Friends,

"`In the power of the everlasting God, which comprehends the power of darkness,
and all temptation, and that which comes out of it, in this power of God dwell.
It will bring and keep you to the Word in the beginning; it will keep you up to the life,
to feed thereupon, in which you are over the power of darkness,
and in which you will find and feel dominion and life.
And that will let you see, before the tempter was, and over him;
and into that the tempter cannot come; for the power and truth he is out of.
Therefore in that life dwell, in which you will know dominion;
and let your faith be in the power, and over the weakness and temptations,
and look not at them: but in the light and power of God look at the Lord`'s strength,
which will be made perfect in your weakest state.
In all temptations look at the grace of God to bring your salvation,
which is your teacher to teach you: for when you look or hearken to the temptations,
you go from your teacher, the grace of God;
and so are darkened in going from that teacher, the grace of God,
which is sufficient in all temptations, to lead out of them, and to keep over them.`"

[.signed-section-signature]
G+++.+++ F.

--
