== Chapter IX.

[.chapter-synopsis]
* 1655-1656.
* Friends slandered by Presbyterians and Independents, suffer much from them and the Baptists for refusing to pay tithes
* the priests hunt after a fallen benefice like crows after carrion
* great miracles wrought through several
* an Independent preacher convinced, but relapses
* address to the convinced in Ireland
* a sick woman at Baldock restored
* George Fox parts and reconciles two furious combatants
* to the seven parishes at the Land`'s End, recommending attention to the Inward Light
* George Fox parts with James Nayler, and has a presentiment of his fall
* Major Ceely places George Fox and Edward Pyot under arrest
* they are sent to Launceston jail
* put into Doomsdale, and suffer a long and cruel imprisonment
* a paper against swearing
* Peter Ceely`'s mittimus
* George Fox has great service in jail
* many are convinced, and opposers are confounded
* experiences some remarkable preservations
* Edward Pyot writes an excellent letter to Judge Glynne on the liberty of the subject, and on the injustice and illegality of their imprisonment
* Truth spreads in the west by the very means taken to prevent it
* exhortation and warning to magistrates
* answer to the Exeter general warrant for taking up and imprisoning Friends
* exhortation to Friends in the ministry
* warning to priests and professors
* cruel jailer imprisoned in Doomsdale, and further judgments upon him follow
* a Friend offers to lie in prison instead of George Fox
* Edward Pyot to Major-General Desborough, in answer to Ms conditional offer of liberty
* George Fox to the same
* he and his Friends are soon after liberated.

After clearing myself of those services for the Lord, which lay upon me in London,
I passed into Bedfordshire and Northamptonshire.
At Wellingborrough, I had a great meeting,
in which the Lord`'s everlasting power and truth was over all;
and many in that country were turned to the Lord.
Great rage was amongst the professors, for the wicked priests, Presbyterians,
and Independents, falsely reported "`that we carried bottles about with us,
which we gave people to drink of; which made them follow us:`" but the Power, and Spirit,
and Truth of God kept Friends over the rage of the people.
Great spoiling also there was of Friends`' goods for tithes,
by the Independent and Presbyterian priests, and some Baptist priests,
that had got into the steeple-houses.

Prom Wellingborough I went into Leicestershire, where Colonel Hacker had threatened,
that if I came there he would imprison me again,
though the Protector had set me at liberty:
but when I was come to Whetstone (the meeting from
which he took me before) all was quiet there.
Colonel Hacker`'s wife, and his marshal came to the meeting, and were convinced:
for the glorious powerful day of the Lord was exalted over all,
and many were convinced that day.
There were at that meeting two justices of the peace, that came out of Wales,
whose names were Peter Price and Walter Jenkin; who came both to be ministers of Christ.

I went from thence to Silebt, to William Smith`'s, where was a great meeting,
to which several Baptists came; one of them, a Baptist teacher, was convinced,
and came to sit under the Lord`'s teaching by his Spirit and power.
This Baptist said, he had baptized thirty in a day.

From thence I went to Drayton, my native town,
where so many priests and professors had formerly gathered together against me;
but now not a priest or professor appeared.
I asked some of my relations where all the priests and professors were? They said,
the priest of Nun-Eaton was dead,
and eight or nine of them were seeking to get his benefice.
"`They will let you alone now,`" said they, "`for they are like a company of crows,
when a sheep is dead, they all gather together to pull out the puddings;
so do the priests for a fallen benefice.`"
These were some of their own hearers that said so of them;
but they had spent their venom against me,
and the Lord delivered me by his power out of their snares.

Then I went to Badgley, where was a great meeting.
Many came far to it; and were convinced and turned to the Lord;
who came under Christ`'s teaching, and were settled upon him,
their foundation and their rock.

From thence I passed into Nottinghamshire, and had large meetings there;
and into Derbishire, where the Lord`'s power came over all;
and many were turned from darkness to light, and from the power of Satan unto God,
and came to receive the Holy Ghost.
Great miracles were wrought in many places by the power of the Lord through several.

In Derbyshire James Nayler met me, and told me,
seven or eight priests had challenged him to a dispute.
I had a travail in my spirit for him, and the Lord answered me,
and I was moved to bid him go on, and God Almighty would be with him,
and give him the victory in his power.
And the Lord did so; insomuch that the people saw the priests were foiled,
and they cried, "`a Nailer, a Nailer hath confuted them all.`"
After the dispute, he came to me again, praising the Lord.
Thus was the Lord`'s day proclaimed and set over all their heads,
and people began to see the apostacy and slavery they
had been under to their hireling teachers for means;
and they came to know their teacher, the Lord Jesus, who had purchased them,
and made their peace between God and them.
While we were here, Friends came out of Yorkshire to see us,
and were glad of the prosperity of truth.

After this I passed into Warwickshire, through Friends, visiting their meetings;
and so into Worcestershire.
I had a meeting at Birmingham, as I went,
where several were convinced and turned to the Lord.
At length I came to one Cole`'s house in Worcestershire, near Chattan.
This Cole had given an Independent preacher a meeting-place,
and the Independent came to be convinced,
and after he was convinced he laid aside his preaching;
whereupon the old man Cole gave him a hundred pounds a-year.
I had a meeting there, and a very great one it was,
inasmuch that the meeting-place would not hold the people:
and many were turned to the Lord that day.
Afterwards, when the time of trials came,
this Independent did not stand to that which had convinced him, but turned back,
whereupon the old man took away his hundred pounds a-year from him again.
But Cole himself died in God`'s truth.

I heard that at Evesham the magistrates had cast several Friends into prison; and that,
hearing of my coming, they made a pair of high stocks.
I sent for Edward Pittaway, a Friend that lived near Evesham,
and asked him the truth of the thing; and he said it was so.
I went that night with him to Evesham, and in the evening we had a large,
precious meeting, wherein Friends and people were refreshed with the word of life,
and with the power of the Lord.
Next morning I rode to one of the prisons, and visited Friends there, and encouraged them.
Then I rode to the other prison, where there were several prisoners;
and amongst them was Humphrey Smith,^
footnote:[Humphrey Smith became an able gospel minister, turning many to righteousness.
He had a vision of the destruction of London by fire, six years before it happened,
which vision he made known as a warning to the people to repent.
(See _Piety Promoted_, vol. i. p. 39 and his published works).
He had also a clear foresight of his own sufferings and death thereby.
He died a prisoner for the testimony of Jesus in Winchester jail, in 1663,
where he fell ill after a year`'s imprisonment.
'`Whilst he was very ill in prison, he said,
"`My heart is filled with the power of God;`" and then added,
"`It is good for a man at such a time as this, to have the Lord to be his friend.`"
Near his departure, he prayed earnestly, saying, "`Hear me, O Lord,
uphold and preserve me.
I know that my Redeemer liveth: Thou art strong and mighty, O Lord;`" and prayed,
"`that the Lord would deliver his people from their cruel
oppressors;`" and for those who had been convinced by him,
"`that the Lord would be their teacher.`"]
who had been a priest, but was now become a free minister of Christ.
When I had visited the Friends at both prisons,
and was turned away from the prison to go out of town,
I espied the magistrates coming to seize me.
But the Lord frustrated their intent, the innocent escaped their snare,
and God`'s blessed power came over them all.
But exceedingly rude and envious were the priests and
professors about this time in those parts.

I went from Evesham to Worcester, and had a precious meeting there, and quiet.
But after it, as we came down the street towards our inn,
some of the professors fell to discourse with Friends,
and were like to have made a tumult in the city.
As we went into the inn, they all cluttered into the yard; but I went among them,
and got them quieted.
Next day I walked into the town, and had much discourse with some of the professors,
concerning Christ and the way of truth.
One of them denied that Christ was of Abraham, according to the flesh,
and that he was declared to be the Son of God, according to the Spirit;
but I proved from Rom. 1 that he was of the seed of Abraham,
being made of the seed of David according to the flesh;
and that according to the Spirit he was declared to be the Son of God.
Afterwards I wrote a paper concerning it.

From Worcester we went to Tewkesbury, where in the evening we had a great meeting;
to which came the priest of the town with a great rabble of rude people.
He boasted, that he would see whether he or I should have the victory.
"`I turned the people to the divine light, which Christ, the heavenly and spiritual man,
enlighteneth them withal; that with that light they might see their sins,
and that they were in death and darkness, and without God in the world;
and that with the same light they might also see Christ from whom it comes,
their Saviour and Redeemer, who shed his blood and died for them,
and who is the way to God, the truth, and the life.`"
Here the priest began to rage against the Light, and denied it;
for neither priest nor professor could endure to hear the Light spoken of.
So the priest having railed at the Light went away,
and left Ills rude company amongst us; but the Lord`'s power came over them,
though mischief was in their hearts.

Leaving Tewkesbury, we came to Warwick,
where in the evening we had a meeting at a widow`'s house, with many sober people.
A precious meeting we had in the Lord`'s power,
and several were convinced and turned to the Lord.
After it, as I was walking out, a Baptist in the company began to jangle;
and the bailiff of the town with his officers came in, and said,
"`What do these people here at this time of night?`" So he secured John Crook,
Amor Stoddart, Gerrard Roberts,^
footnote:[Gerrard Roberts, a merchant of London,
was one of the most active members of the Society in making the needful
arrangements for the visits of its ministers to foreign parts.]
and myself, but we had leave to go to our inn, and to be forth-coming in the morning.
Next morning many rude people came to the inn and into our chambers, desperate fellows;
but the Lord`'s power gave us dominion over them.
Gerrard Roberts and John Crook went up to the bailiff to speak with him,
and to know what he had to say to us.
He said we might go our ways, for he had little to say to us.
As we rode out of town, it lay upon me to ride to his house to let him know,
"`that the Protector having given forth an instrument of government,
in which liberty of conscience was granted, it was very strange that,
contrary to that instrument of government,
he would trouble peaceable people that feared God.`"
The Friends went with me, but the rude people gathered about us with stones;
and one of them took hold of my horse`'s bridle and broke it;
but the horse drawing back threw him under him.
Though the bailiff saw this, yet he did not stop,
nor so much as rebuke the rude multitude,
so that it was much we were not slain or hurt in the streets;
for the people threw stones, and struck at us, as we rode along the town.

When we were quite out of the town, I told Friends, "`it was upon me from the Lord,
that I must go back into it again;
and if any one of them felt any thing upon him from the Lord, he might follow me,
and the rest that did not, might go on to Dun-Cow.`"
So I passed up through the market in the dreadful power of God,
declaring the word of life to them, and John Crook followed me.
Some struck at me; but the Lord`'s power was over them, and gave me dominion over all.
I showed them their unworthiness of the name of Christians,
and the unworthiness of their teachers who had not brought them into more sobriety;
and what a shame they were to Christianity!

Having cleared myself, I turned back out of the town again, and passed to Coventry;
where we found the people closed up with darkness.
I went to a professor`'s house that I had formerly been at, and he was drunk,
which grieved my soul so, that I did not go into any house in the town;
but rode into some of the streets, and into the market-place.
I felt the power of the Lord God was over the town.

Then I went on to Dun-cow, and had a meeting there in the evening,
and some were turned to the Lord by his Spirit, as also at Warwick and Tewkesbury.
We lay at Dun-Cow that night, and there we met with John Camm,
a faithful minister of the everlasting gospel.
In the morning there gathered a rude company of priests and people,
who behaved more like beasts than men;
for some of them came riding on horseback into the room where we were;
but the Lord gave us dominion over them.

Prom thence we passed into Leicestershire,
where we had a great meeting at the place where I had been taken formerly;
and after that we came to Badgley in Warwickshire.
Here William Edmundson,^
footnote:[William Edmundson was the first person who
publicly espoused the principles of Friends in Ireland.
He was some time a soldier in Cromwell`'s army,
but the strivings of the Holy Spirit drew him out of the corruptions of the world,
to a nearer acquaintance with God.
He left the army, and joined the people called Quakers,
though they were much spoken against.
His life and property were given up to the service of the gospel,
and many were his trials and sufferings on its account,
which he bore with exemplary patience.
During the civil wars, he had on one occasion twenty of his cows driven away from him.
His house was also beset by some hundreds of banditti,
and the shots they fired into the house were heard at two miles`' distance.
After it was plundered and burned, himself and two sons were led away prisoners,
bareheaded, and barefooted, and nearly naked,
except they gave William Edmundson an old blanket of his own to wrap about him.
{footnote-paragraph-split}
After a toilsome night, journeying through bushes, rough stones, mire,
and water knee-deep, they were taken to a wood, and,
after a mock show of justice, condemned to death;
the young men to be hanged, and their father, in compliment to his courage, to be shot.
Though death was no terror to this pious man, he expostulated with his persecutors;
reminding them of his services in behalf of their countryfolk.
Several of them confessed they knew him to be an honest man;
yet justice and mercy were disregarded, and they prepared to execute their purpose.
The youths were hoodwinked, in order to hang them;
and two firelocks made ready to shoot their father,
whom they were about to hoodwink also;
but he told them they need not, for he could look them in the face,
and was not afraid to die.
{footnote-paragraph-split}
At this juncture arrived a lieutenant,
a brother of one whose life William Edmundson had saved,
when the English soldiers were about to hang him.
Thus the Lord interposed, and would not suffer them to take their lives.
The officer released the prisoners from death, but did not restore them to liberty,
taking them to Athlone, not from a grateful sense of remembered services,
but from a hope of preferment thereby.
On entering the town, the high sheriff, soldiers, and rabble, gave them abusive language;
and their lives were endangered,
had not a lieutenant of the Irish army who recognized William Edmundson,
declared aloud his knowledge of him, and of his worth, and thus quieted the tumult.
They were then brought to the Irish colonel, before whom he appeared, wrapped in his blanket.
Though the colonel was personally acquainted with him,
he did not, in these circumstances, know him;
but when he said, I am old William Edmundson, the colonel rose,
and with tears in his eyes, expressed his sorrow to see him in that condition.
After reprimanding the lieutenant,
he committed them to the care of one of his captains,
sent them food and money, and they met with better treatment.
{footnote-paragraph-split}
Great sufferings was it the lot of this faithful man to endure;
who was unwearied in his Master`'s service for upwards of fifty years of his life,
counting nothing too near or dear to part with, or too great to suffer,
if he could but win Christ and the souls of his fellow-men.
Yet in these and many other great exercises and straits,
the Lord`'s arm and generous providence, says he, have preserved and supported me.
He spared not himself, even to old age,
in performing travels and services as a gospel minister,
beyond the ordinary course of nature,
often saying the Lord was his song and his strength,
and had carried him through many and various exercises and perils.
As a fixed star in the firmament of God`'s power did
he continue to hold his integrity to the last, being enabled to say,
"`O death! where is thy sting? O grave! where is thy victory?`"]
a Friend who lived in Ireland,
having some drawings upon his spirit to come over into England to see me, met with me;
by whom I wrote to the few Friends then convinced in the north of Ireland, as follows:--

[.embedded-content-document.letter]
--

[.salutation]
"`Friends,

"`In that which convinced you, wait; that you may have that removed you are convinced of.
And all my dear Friends, dwell in the life, and love, and power, and wisdom of God,
in unity one with another, and with God;
and the peace and wisdom of God fill all your hearts,
that nothing may rule in you but the life, which stands in the Lord God.`"

[.signed-section-signature]
G+++.+++ F.

--

When these few lines were read amongst the Friends in Ireland at their meeting,
the power of the Lord came upon all in the room.

From Badgley we passed to Swannington and Higham,
and so into Northamptonshire and Bedfordshire, having great meetings;
and many were turned to the Lord by his power and Spirit.
When we came to Baldock in Hertfordshire, I asked, if there was nothing in that town,
no profession; and it was answered me, there were some Baptists and a Baptist woman sick.
John Rush of Bedfordshire went with me to visit her.
When we came in, there were many tender people about her.
They told me she was not a woman for this world,
but if I had any thing to comfort her concerning the world to come, I might speak to her.
I was moved of the Lord God to speak to her;
and the Lord raised her up again to the astonishment of the town and country.
This Baptist woman and her husband, whose name was Baldock, came to be convinced,
and many hundreds of people have met at their house since.
Great meetings and convincements were in those parts afterwards;
many received the word of life, and sat down under the teaching of Christ, their Saviour.

When we had visited this sick woman, we returned to our inn,
where were two desperate fellows fighting so furiously,
that none durst come nigh to part them.
But I was moved, in the Lord`'s power, to go to them; and when I had loosed their hands,
I held one of them by one hand, and the other by the other,
showed them the evil of their doings, and reconciled them one to the other,
and they were so loving and thankful to me, that people admired at it.^
footnote:[The circumstance above related is reminding
of a somewhat similar one recorded of Edward Burrough.
{footnote-paragraph-split}
"`At London,`" says Sewell the historian,
"`there is a custom in summer-time, when the evening approaches,
and tradesmen leave off working, that many lusty fellows meet in the fields,
to try their skill and strength in wrestling,
where generally a multitude of people stand gazing in a ring.
{footnote-paragraph-split}
"`Now it so fell out, that Edward Burrough passed by the place where they were wrestling,
and standing still among the spectators,
saw how a strong and dexterous fellow had already thrown three others,
and was waiting for a fourth champion, if any durst venture to enter the lists.
At length, none being bold enough to try, Edward Burrough stepped into the ring,
which was commonly made up of all sorts of people;
and having looked upon the wrestler with a serious countenance,
the man was not a little surprised, instead of an airy antagonist,
to meet with a grave and awful young man; and all stood amazed as it were at this sight,
eagerly expecting what would be the issue of this combat.
But it was quite another fight Edward Burrough aimed at.
For having already fought against spiritual wickedness,
that had once prevailed over him, and having overcome in measure,
by the grace of God, he now endeavoured also to fight against it in others,
and to turn them from the evil of their ways.
With this intention, he began very seriously to speak to the bystanders,
and that with such a heart-piercing power, that he was heard by the mixed multitude,
with no less attraction than admiration;
for his speech tended to turn them from darkness to the light,
and from the power of Satan unto God.
To effect this, he laboured with convincing words,
showing how God had not left himself without a witness,
but had given to man a measure of his grace, and enlightened every one with the light of Christ.
{footnote-paragraph-split}
"`Thus zealously he preached; and though many might look upon this as a novelty,
yet it was of such effect, that some were convinced of the truth;
for Burrough was a breaker of stony hearts,
and therefore by a certain author not unjustly called '`a son of thunder;`'
though he omitted not in due season to speak a word of
consolation to those that were of a broken heart, and of a contrite spirit.`"]

From thence I passed to Market-street, where God had a people,
and through Alban`'s to London, where Friends were glad of the prosperity of truth,
and the manifestation of the Lord`'s glorious power which had delivered us,
and carried us through many dangers and difficulties.
I also rejoiced to find truth prosper in the city,
and all things well amongst Friends there.
Only there was one John Toldervey, who had been convinced of truth, and run out from it,
and the envious priests took occasion from thence to write a wicked book against Friends,
which they stuffed with many lies, to render truth and Friends odious.
They entitled their book, "`The Foot out of the Snare.`"
But this poor man came to see his folly and returned, condemned his backsliding,
answered the priest`'s book, and exposed all their lies and wickedness.
Thus the Lord`'s power came over them, and his everlasting Seed reigned,
and reigns to this day.

Now after I had tarried some time in London, and had visited Friends in their meetings,
I went out of town, leaving James Nayler in the city.
As I passed from him I cast my eyes upon him, and a fear struck me concerning him;
but I went away, and rode down to Ryegate in Surrey, where I had a little meeting.
There the Friends told me of one Thomas Moore, a justice of peace,
that lived not far from Ryegate, a friendly, moderate man;
I went to visit him at his house, and he came to be a serviceable man in truth.

We passed on to Thomas Patchings'`, of Binscombe in Godalming, where we had a meeting,
to which several Friends came from London,
and John Bolton and Ins wife came on foot in frost and snow.
After this we went towards Horsham-park; and having visited Friends,
passed on to Arundel and Chichester, where we had meetings.
At Chichester many professors came in, and made some jangling,
but the Lord`'s power was over them.
The woman of the house where the meeting was, though convinced of truth,
yet not keeping her mind close to that which convinced her,
fell in love with a man of the world, who was there that time.
When I knew it, I took her aside, and was moved to speak to her, and to pray for her;
but a light thing got up in her mind, and she slighted it.
Afterwards she married the man, and soon after went distracted;
for he was greatly in debt, and she greatly disappointed.
Then was I sent for to her, and the

Lord was entreated, raised her up again, and settled her mind by Ms power.
Afterwards her husband died;
and she acknowledged the just judgments of God were come upon her,
for slighting the exhortation and counsel I had given her.

After we left Chichester, we travelled to Portsmouth.
There the soldiers had us to the governor`'s house.
After some examination, the Lord`'s power came over them, and we were set at liberty,
and had a meeting in the town.
After which we came to Ringwood, where in the evening we had a meeting,
at which several were convinced, and turned to the Spirit of the Lord,
and to the teaching of Christ Jesus, their Saviour.

From Ringwood we came to Poole; and having set up our horses at an inn,
we sent into the town to inquire for such as feared the Lord, and such as were worthy;
and had a meeting with several sober people.
William Baily, a Baptist teacher, was convinced there at that time.^
footnote:[William Bailey (or Bayley) whose writings were published in one volume,
4to, in 1676, and of whom there is a brief account in _Piety Promoted_, vol. i. p. 83,
is stated to have been "`mighty in the Scriptures,`"
and not only a believer and preacher of the word of faith,
but a sufferer for the same.
On one occasion, he was thrown down and dragged upon the ground by the hair of his head,
his persecutors endeavouring to rend and break asunder his jaws,
so that the ground whereon he lay was besmeared with his blood.
As if this butchering had not been enough to make him a sacrifice,
a heavy man stamped on his breast with his feet,
endeavouring to beat the breath out of his body.
When this persecutor had done his pleasure,
he told the jailer to take him away and put him in some nasty hole,
for his entertainment and cure.
{footnote-paragraph-split}
William Bailey, being master of a ship,
often crossed the mighty waters for the maintenance of his family,
and many beyond the seas were comforted by his ministry.
He was taken ill at sea on his return from visiting Friends in Barbadoes,
and died on board _the Samuel_ of London, in latitude 46° 38`' N.
He died in great peace, as if he had fallen asleep,
exhorting those around him to fear God.]
The people received the truth in the inward parts,
and were turned to the Lord Jesus Christ, their rock and foundation,
their teacher and Saviour;
and there is become a great gathering in the name of Jesus of a very tender people,
who continue under Christ`'s teaching.

We went also to Southampton and had a meeting; several were convinced there also.
Edward Pyot of Bristol travelled with me all this western journey.

From thence we went to Dorchester, and alighted at an inn, a Baptist`'s house;
we sent into the town to the Baptists, to let ms have their meeting-house to meet in,
and to invite the sober people to the meeting; but they denied it us.
We sent to them again, to know why they would deny us their meeting-house;
so the thing was noised in the town.
Then we sent them word, if they would not let us come to their house, they,
or any people that feared God, might come to our inn, if they pleased.
They were in a great rage; and their teacher and many of them came up,
and slapped their Bibles on the table.
I asked them, why they were so angry;
were they angry with the Bible? But they fell into a discourse about their water-baptism.
I asked them, whether they could say, they were sent of God to baptize people,
as John was;
and whether they had the same Spirit and power that the apostles had?
They said, they had not.
Then I asked them, how many powers there are;
whether there are any more than the power of God, and the power of the devil?
They said, there was not any other power than those two.
Then said I, "`if you have not the power of God that the apostles had,
then you act by the power of the devil.`"
Many sober people were present, who said, "`they have thrown themselves on their backs.`"
Many substantial people were convinced that night;
a precious service we had there for the Lord, and his power came over all.
Nest morning, as we were passing away, the Baptists, being in a rage,
began to shake the dust off their feet after us.
"`What,`" said I, "`in the power of darkness!
We, who are in the power of God, shake off the dust of our feet against you.`"

Leaving Dorchester, we came to Wermouth; where also we enquired after the sober people;
and about four score of them gathered-together at a priest`'s house.
Most of them received the word of life, and were turned to their teacher Christ Jesus,
who had enlightened them with his divine light, by which they might see their sins,
and him who saveth from sin.
A blessed meeting we had with them of several hours,
and they received the truth in the love of it, with gladness of heart.
The state of their teachers and the apostacy was opened to them;
and the state of the apostles, and of the church in their days; and the state of the law,
and of the prophets before Christ, and how Christ came to fulfil them;
how he was their teacher in the apostles`' days,
and how he was come now to teach his people himself by his power and Spirit.
All was quiet, the meeting broke up peaceably, and the people were very loving;
and a meeting is continued in that town to this day.
Many are added to them; and some that had been Ranters came to own the truth,
and to live very soberly.`'

There was a captain of horse in the town, who sent to me,
and would fain have had me to stay longer; but I was not to stay.
He and his man rode out of town with me about seven miles, Edward Pyot also being with me.
This captain was the fattest, merriest man, the most cheerful,
and the most given to laughter, that ever I met with;
insomuch that I was several times moved to speak
in the dreadful power of the Lord to him;
and yet it was become so customary to him,
that he would presently laugh at any thing he saw.
But I still admonished him to come to sobriety, sincerity, and the fear of the Lord.
We stayed at an inn that night; and in the morning I was moved to speak to him again,
when he parted from us.
Next time I saw him, he told me, that when I spoke to him at parting,
the power of the Lord so struck him, that before he got home he was serious enough,
and had discontinued his laughing.
He afterwards was convinced, and became a serious and good man, and died in the truth.

Parting from him we went to Honiton;
and at our inn inquired what people there were in the town that feared God,
and sent for them.
There came to us some of the Particular Baptists, with whom we had much reasoning.
I told them, "`they held their doctrine of particular election in Esau`'s, Cain`'s,
and Ishmael`'s nature; not in Jacob, the second birth; but they must be born again,
before they could enter the kingdom of God.
And that as the promise of God was to the Seed, not as many, but as one, which is Christ;
so the election stands in Christ; and they must he such as walk in his light, grace,
Spirit, and truth.`"

From thence we passed to Tops Ham, and stayed over the First-day;
but the innkeeper and his people were rude.
Next morning we gave forth some queries to the priests and professors;
whereupon some rude professors came into our inn; and had we not gone when we did,
they would have stopped us.
I wore a girdle, which through forgetfullness I left behind me at the inn,
and afterwards sent to the innkeeper for, but he would not let me have it again.
Afterwards, when he was tormented in his mind about it, he took it and burnt it,
lest he should be bewitched by it, as he said; yet when he had burnt it,
he was more tormented than before.
Some, notwithstanding the rudeness of the place, were convinced;
and a meeting was afterwards settled in that town, which has continued ever since.

After this we passed to Totness, a dark town.
We lodged at an inn, and at night Edward Pyot was sick, but the Lord`'s power healed him,
so that next day we got to Kingsbridge,
and at our inn inquired for the sober people of the town.
They directed us to Nicholas Tripe and his wife, and we went to their house.
They sent for the priest, with whom we had some discourse; but he being confounded,
quickly left us.
Nicholas Tripe and his wife were convinced;
and there is since a good meeting of Friends in that country.
In the evening we returned to our inn; and there being many people drinking in the house,
I was moved of the Lord to go amongst them, and to direct them to the light,
which Christ, the heavenly Man, had enlightened them withal;
by which they might see all their evil ways, words, and deeds,
and by the same light they might also see Jesus Christ their Saviour.
The innkeeper stood uneasy, seeing it hindered his guests from drinking;
and as soon as the last words were out of my mouth, he snatched up the candle, and said,
"`Come, here is a light for you to go into your chamber.`"
Next morning, when he was cool, I represented to him
"`what an uncivil thing it was for him to do so;`"
then warning him of the day of the Lord,
we got ready and passed away.

We came next day to Plymouth, and after having refreshed ourselves at our inn,
we went to Robert Cary`'s house, where we had a very precious meeting.
At this meeting was one Elizabeth Trelawny, daughter to a baronet;
she being somewhat dull of hearing came close to me,
and placed her car very near me while I spoke; and she was convinced.
After the meeting some jangling Baptists came in, but the Lord`'s power came over them,
and Elizabeth Trelawny gave testimony thereto.
A fine meeting was settled there in the Lord`'s power, which has continued ever since;
where many faithful Friends have been convinced.

From thence we passed into Cornwall, and came to an inn in the parish of Menheniot.
At night we had a meeting at Edward Hancock`'s house, to which came one Thomas Mounce,
and a priest, with many people.
We made the priest confess he was a minister made and maintained by the state;
and he was confounded and went his way; but many of the people stayed.
I directed them to the "`light of Christ, by which they might see their sins,
and their Saviour Christ Jesus, the way to God,
and their Mediator to make peace between God and them; their Shepherd to feed them,
and their Prophet to teach them.
I directed them also to the Spirit of God in themselves,
by which they might know the Scriptures, and be led into all truth;
by which they might know God, and in it have unity one with another.`"
Many were convinced at that time, and came under Christ`'s teaching,
and there are fine gatherings in the name of Jesus in those parts at this day.

We travelled thence through Penryn to Helston;
but could not obtain knowledge of any sober people,
through the badness of the innkeepers.
At length we came to a village where some Baptists and sober people lived,
with whom we had some discourse; and some of them were brought to confess,
that they stumbled at the light of Christ.
They would have had us to stay with them, but we passed thence to Market-jew;
and having taken up our lodging at an inn,
we went out over-night to inquire for such as feared the Lord.
Next morning the mayor and aldermen gathered together,
with the high-sheriff of the county;
and they sent first the constables to bid us come before them.
We asked them for their warrant, and they saying they had none,
we told them we should not go along with them without.
Upon the return of the constables without us, they sent their serjeants,
and we asked them for their warrant.
They said, they had none; but they told us, the mayor and aldermen stayed for us.
We told them, the mayor and his company did not well to trouble us in our inn,
and we should not go with them without a warrant.
So they went away and came again; and when we asked them for their warrant,
one of them pulled his mace from under his cloak;
we asked them whether this was their custom to molest and trouble strangers in
their inns and lodgings? After some time Edward Pyot went to the mayor and aldermen,
and had much discourse with them; but the Lord`'s power gave him dominion over them all.
When he returned, several of the officers came to us,
and we laid before them the incivility and unworthiness of their conduct towards us,
who were the servants of the Lord God, thus to stop and trouble us in our lodgings;
and what an unchristian act it was.
Before we left the town I wrote a paper,
to be sent to the seven parishes at the Land`'s End.
A copy of which follows:--

[.small-break]
'''

[.embedded-content-document.paper]
--

"`The mighty day of the Lord is come, and coming,
wherein all hearts shall be made manifest,
and the secrets of every one`'s heart shall be revealed by the light of Jesus,
who lighteth every man that cometh into the world,
that all men through him might believe, and that the world might have life through him,
who saith, '`Learn of me,`' and of whom God saith, '`This is my beloved Son,
hear ye him.`' Christ is come to teach his people himself;
and every one that will not hear this Prophet, which God hath raised up,
and which Moses spoke of, when he said, '`Like unto me will God raise you up a Prophet,
him shall you hear every one (I say) that will not hear this Prophet, is to be cut off.
They that despised Moses`'s law, died under the hand of two or three witnesses;
but how much greater punishment will come upon them that neglect this great salvation,
Christ Jesus, who saith, '`Learn of me: I am the way, the truth,
and the life;`' who lighteth every man that cometh into the world;
and by his light lets him see his evil ways and his evil deeds.
But if you hate this light, and go on in evil, this light will be your condemnation.
Therefore, now ye have time, prize it; for this is the day of your visitation,
and salvation offered to you.
Every one of you hath a light from Christ, which lets you see you should not lie,
nor do wrong to any, nor swear, nor curse, nor take God`'s name in vain, nor steal.
It is the light that shows you these evil deeds; which if you love,
and come unto it and follow it, will lead you to Christ, who is the way to the Father,
from whom it comes; where no unrighteousness enters, nor ungodliness.
If you hate this light, it will be your condemnation; but if you love it and come to it,
you will come to Christ;
and it will bring you off from all the world`'s teachers and ways, to learn of Christ,
and will preserve you from the evils of the world, and all the deceivers in it.`"

[.signed-section-signature]
G+++.+++ F.

--

This paper a Friend who was then with me had;
and when we were gone three or four miles from Market-Jew towards the West,
he meeting with a man upon the road, gave him a copy of the paper.
This man proved to be a servant to one Peter Ceely, major in the army,
and a justice of peace in that county;
and he riding before us to a place called St. Ives, showed the paper to his master,
Major Ceely.
When we came to Ives, Edward Pyot`'s horse having cast a shoe, we stayed to have it set;
and while he was getting his horse shod, I walked down to the sea-side.
When I returned I found the town in an uproar;
and they were haling Edward Pyot and the other Friend before Major Ceely.
I followed them into the justice`'s house, though they did not lay hands upon me.
When we came in, the house was full of rude people;
whereupon I asked whether there were not an officer
among them to keep the people civil? Major Ceely said, he was a magistrate.
I told him, "`he should show forth gravity and sobriety then,
and use his authority to keep the people civil; for I never saw any people ruder:
the Indians were more like Christians than they.`"
After a while they brought forth the paper aforesaid,
and asked whether I would own it? I said, Yes.
Then he tendered the oath of abjuration to us;
whereupon I put my hand in my pocket and drew forth the answer to it,
which had been given to the Protector.
After I had given him that, he examined us severally, one by one.
He had with him a silly, young priest, who asked us many frivolous questions;
and amongst the rest he desired to cut my hair, which then was pretty long;
but I was not to cut it though many times many were offended at it.
I told them, "`I had no pride in it, and it was not of my own putting on.`"
At length the justice put us under a guard of soldiers, who were hard and wild,
like the justice himself; nevertheless
"`we warned the people of the day of the Lord, and declared the truth to them.`"
The next day he sent us, guarded by a party of horse with swords and pistols, to Redruth.
On First-day the soldiers would have taken us away;
but we told them it was their Sabbath, and it was not usual to travel on that day.
Several of the town`'s-people gathered about us,
and whilst I held the soldiers in discourse, Edward Pyot spoke to the people;
and afterwards he held the soldiers in discourse, whilst I spoke to the people;
and in the mean time the other Friend got out the back way,
and went to the steeple-house to speak to the priest and people.
The people were exceedingly desperate, in a mighty rage against him, and abused him.
The soldiers also missing him, were in a great rage, ready to kill us;
but I declared the day of the Lord,
and the word of eternal life to the people that gathered about us.
In the afternoon the soldiers were resolved to have us away, so we took horse.
When we were got to the town`'s-end, I was moved of the Lord to go back again,
to speak to the old man of the house; the soldiers drew out their pistols,
and swore I should not go back.
I heeded them not, but rode back, and they rode after me.
I cleared myself to the old man and the people, and then returned with them,
and reproved them for being so rude and violent.

At night we were brought to a town called Smethick then, but since Falmouth.
It being the evening of the First-day,
there came to our inn the chief constable of the place, and many sober people,
some of whom began to inquire concerning us.
We told them we were prisoners for truth`'s sake;
and much discourse we had with them concerning the things of God.
They were very sober, and loving to us.
Some were convinced, and stood faithful ever after.

After the constable and these people were gone, other people came in,
who also were very civil, and went away very loving.
When all were gone we went to our chamber to go to bed,
and about eleven o`'clock Edward Pyot said,
"`I will shut the door, it may be some may come to do us a mischief.`"
Afterwards we understood that Captain Keat, who commanded the party,
had purposed to do us some mischief that night; but the door being bolted,
he missed his design.
Next morning Captain Keat brought a kinsman of his, a rude, wicked man,
and put him into the room, he himself standing without.
This evil-minded man, walking huffing up and down the room, I bid him fear the Lord;
whereupon he ran upon me, struck me with both his hands; and placing his leg behind me,
would fain have thrown me down, but he could not, for I stood stnT and still,
and let him strike.
As I looked towards the door,
I saw Captain Keat look on and see his kinsman thus beat and abuse me.
Whereupon I said, "`Keat, dost thou allow this?`" and he said, he did;
"`Is this manly or civil,`" said I,
"`to have us under a guard and put a man to abuse and beat us? is this manly, civil,
or christian?`" I desired one of our friends to send for the constables, and they came.
Then I desired the captain to let the constables see his warrant or order,
by which he was to carry us; which he did;
and his warrant was to conduct us safe to Captain Fox, governor of Pendennis Castle;
and if the governor should not be at home, he was to convey us to Launceston jail.
I told him, he had broken his order concerning us; for we, who were his prisoners,
were to be safely conducted, but he had brought a man to beat and abuse us;
so he having broken his order, I wished the constable to keep the warrant.
Accordingly he did, and told the soldiers they might go,
for he would take charge of the prisoners;
and if it cost twenty shillings in charges to carry us up,
they should not have the warrant again.
I showed the soldiers the baseness of their carriage towards us;
and they walked up and down the house, being pitifully blank and down.
The constables went to the castle,
and told the officers what they had done The officers showed
great dislike of Captain Keat`'s base carriage towards us;
and told the constables that Major-General Desborough was coming to Bodmin,
and that we should meet him; and it was likely he would free us.
Meanwhile our old guard of soldiers came by way of entreaty to us,
and promised that they would be civil to us, if we would go with them.
Thus the morning was spent till it was about eleven o`'clock;
and then upon the soldiers`' entreaty, and promise to be more civil,
the constables gave them the order again, and we went with them.
Great was the civility and courtesy of the constables and people of that town towards us,
who kindly entertained us; and the Lord rewarded them with his truth;
for many of them have since been convinced thereof,
and are gathered into the name of Jesus, and sit under Christ, their teacher and Saviour.

Captain Keat, who commanded our guard, understanding that Captain Fox,
who was the governor of Pendennis Castle, was gone to meet MajorGeneral Desborough,
did not take us thither; but went with us directly to Bodmin.
We met Major-General Desborough on the way;
the captain of his troop that rode before him, knew me, and said,
"`O, Mr. Fox, what do you here?`" I replied, "`I am a prisoner.`"
"`Alack,`" said he, "`for what?`" I told him, "`I was taken up as I was travelling.`"
"`Then,`" said he, "`I will speak to my lord, and he will set you at liberty.`"
So he came from the head of his troop, rode up to the coach,
and spoke to the major-general.
We also told him how we were taken.
He began to speak against the light of Christ, for which I reproved him;
then he told the soldiers they might carry us to Launceston;
for he could not stay to talk with us, lest his horses should take cold.

So to Bodmin we were conveyed that night; and when we were come to our inn, Captain Keat,
who was in before us, put me into a room, and went his way.
When I was come in, there stood a man with a naked rapier in his hand.
Whereupon I turned out again, called for Captain Keat, and said unto him, "`What now,
Keat, what trick hast thou played now,
to put me into a room where there is a man with his
naked rapier? what is thy end in this?`" "`O,`" said he,
"`pray hold your tongue; for if you speak to this man we cannot all rule him,
he is so devilish.`"
"`Then,`" said I,
"`Dost thou put me into a room where there is such a man with a naked rapier,
that thou sayest, you cannot rule him? What an unworthy,
base trick is this! and to put me singly into this room from the rest of my friends,
that were my fellow-prisoners with me!`"
Thus his plot was discovered, and the mischief they intended was prevented.
Afterwards we got another room, where we were together all night;
and in the evening we declared the truth to the people;
but they were hardened and dark people.
The soldiers also, notwithstanding their fair promises,
were very rude and wicked to us again, and sat up drinking and roaring all night.

Next day we were brought to Launceston, where Captain Keat delivered us to the jailer.
Now was there no friend, nor friendly people near us;
and the people of the town were dark and hardened.
The jailer required us to pay seven shillings a-week for our horse-meat,
and seven for our diet a-piece.
But after some time, several sober people came to see us,
and some of the town were convinced; and many friendly people,
out of several parts of the country, came to visit us, and were convinced.
Then arose a great rage among the professors and priests against us; and they said,
this people Thou and Thee all men without respect, and they will not put off their hats,
nor bow the knee to any man: this made them fret.
But, said they, we shall see, when the assize comes,
whether they will dare to Thou and Thee the judge, and keep on their hats before him.
They expected we should be hanged at the assize.
But all this was little to us;
for we saw how God would stain the world`'s honour and glory,
and were commanded not to seek that honour, nor give it;
but we knew the honour that comes from God only, and sought that.

It was nine weeks from the time of our commitment to the assizes,
to which abundance of people came from far and near to hear the trial of the Quakers.
Captain Bradden lay with his troop of horse there,
whose soldiers and the sheriffs men guarded us up to the court
through the multitude of people that filled the streets;
and much ado they had to get us through them.
Besides, the doors and windows ware filled with people looking out upon us.
When we were brought into the court, we stood sometime with our hats on,
and all was quiet; and I was moved to say, "`Peace be amongst you!`"
Judge Glynne, a Welchman, then chief justice of England,
said to the jailer, "`what be these you have brought here into the court?`"
"`Prisoners, my Lord,`" said he.
"`Why do you not put off your hats?`" said the judge to us: we said nothing.
"`Put off your hats,`" said the judge again.
Still we said nothing.
Then said the judge, "`The court commands you to put off your hats.`"
Then I spoke, and said, "`Where did ever any magistrate, king, or judge,
from Moses to Daniel, command any to put off their hats,
when they came before them in their courts, either amongst the Jews, the people of God,
or amongst the heathens? and if the law of England doth command any such thing,
show me that law either written or printed.`"
Then the judge grew very angry, and said, "`I do not carry my law-books on my back.`"
"`But,`" said I, "`tell me where it is printed in any statute-book, that I may read it.`"
Then said the judge, "`Take him away, prevaricator! I`'ll _ferk_ him.`"
So they took us away, and put us among the thieves.
Presently after he calls to the jailer, "`Bring them up again.`"
"`Come,`" said he,
"`where had they hats from Moses to Daniel; come, answer me: I have you fast now,`" said he.
I replied, "`Thou mayest read in the third of Daniel,
that the three children were cast into the fiery furnace by Nebuchadnezzar`'s command,
with their coats, their hose, and their hats on.`"
This plain instance stopped him: so that not having any thing else to say to the point,
he cried again, "`Take them away, jailer.`"
Accordingly we were taken away, and thrust in among the thieves,
where we were kept a great while; and then, without being called again,
the sheriff`'s men and the troopers made way for us
(but we were almost spent) to get through the crowd of people,
and guarded us to the prison again, a multitude of people following us,
with whom we had much discourse and reasoning at the jail.
We had some good books to set forth our principles, and to inform people of the truth;
which the judge and justices hearing of, they sent Captain Bradden for them,
who came into the jail to us, and violently took our books from us,
some out of Edward Pyot`'s hands, and carried them away; so we never got them again.

In the afternoon we were had up again into the court by the jailer and sheriffs men,
and troopers, who had a mighty toil to get us through the crowd of people.
When we were in the court, waiting to be called, I seeing both the jurymen,
and such a multitude of others swearing, it grieved my life,
that such as professed Christianity should so openly
disobey and break the command of Christ and the apostle.
And I was moved of the Lord to give forth a paper against swearing, which I had about me,
to the grand and petty juries; which was as follows:--

[.embedded-content-document.paper]
--

[.blurb]
=== "`Concerning Swearing.

"`Take heed of giving people oaths to swear: for Christ our Lord and Master saith,
'`Swear not at all; but let your communications be yea yea, and nay nay;
for whatsoever is more than these cometh of evil.`' If any man was to suffer death,
it must be by the hand of two or three witnesses;
and the hands of the witnesses were to be first put upon him, to put him to death.
And the apostle James saith, "`My brethren, above all things swear not,
neither by heaven, nor by earth, nor by any other oath,
lest ye fall into condemnation.`' Hence you may see,
those that swear fall into condemnation,
and are out of Christ`'s and the apostle`'s doctrine.
Therefore, every one of you having a light from Christ, who saith,
'`I am the light of the world,`' and doth enlighten every man that cometh into the world;
who also saith, '`Learn of me,`' whose doctrine is, not to swear;
and the apostle`'s doctrine is, not to swear; '`let your yea be yea, and your nay be nay,
in all your communications; for whatsoever is more, cometh of evil.
Then, they that go into more than yea and nay, go into evil,
and are out of the doctrine of Christ.

"`Now if you say,
'`that the oath was the end of controversy and strife,`' they who are in strife,
are out of Christ`'s doctrine; for he is the covenant of peace: and they who are in it,
are in the covenant of peace.
And the apostle brings that but as an example: as, men swearing by the greater;
and the oath was the end of controversy and strife among men; and said, verily,
men swear by the greater: but God could not find a greater, but swears by himself,
concerning Christ; who, when he was come, taught not to swear at all.
So such as are in him, and follow him, cannot but abide in his doctrine.

"`If you say, '`they swore under the law,
and under the prophets,`' Christ is the end of the law, and of the prophets,
to every one that believeth for righteousness`' sate.
Now mark; if you believe, '`I am the light of the world,
which doth enlighten every man that cometh into the world,`' saith Christ,
by whom it was made;
and every man of you that is come into the world is
enlightened with a light that comes from Christ,
by whom the world was made, that all of you through him might believe;
that is the end for which he doth enlighten you.
Now if you do believe in the light, as Christ commands, and saith, '`believe in the light,
that you may be children of light,`' you believe in Christ,
and come to learn of him who is the way to the Father.
This is the light which shows the evil actions you have all acted,
the ungodly deeds you have committed, and all the ungodly speeches you have spoken;
and all your oaths, cursed speaking, and ungodly actions.
Now if you attend to this light,
it will let you see all that you have done contrary to it; and loving it,
it will turn you from your evil deeds, evil actions, evil ways, evil words, to Christ,
who is not of the world;
who is the light which lighteth every man that cometh
into the world;--who testifies against the world,
that the deeds thereof are evil.
So doth the light in every man, that he hath received from him,
testify against his works and deeds that are evil, that they are contrary to the light;
and each shall give an account at the day of judgment for every idle word that is spoken.
This light shall bring every tongue to confess, yea,
and every knee to bow at the name of Jesus; in which light, if you believe,
you shall not come into condemnation, but come to Christ,
who is not of the world;--to him by whom it was made;
but if you believe not in the light, this, the light, is your condemnation,
saith Christ.`"

[.signed-section-signature]
G+++.+++ F.

--

This paper passing among them from the jury to the justices,
they presented it to the judge; so that when we were called before the judge,
he bade the clerk give me that paper; and then asked me,
"`whether that seditious paper was mine;`" I told him,
"`If they would read it up in open court, that I might hear it,
if it was mine I would own it, and stand by it.`"
He would have had me to take it, and look upon it in my own hand;
but "`I again desired that it might be read, that all the country might hear it,
and judge whether there was any sedition in it or not;
for if there were I was willing to suffer for it.`"
At last the clerk of the assize read it with an audible voice,
that all the people might hear it: and when he had done, I told them, "`it was my paper;
I would own it; and so might they too, except they would deny the Scripture:
for was not this Scripture language, and the words and commands of Christ,
and the apostle,
which all true Christians ought to obey?`"
then they let fall that subject;
and the judge fell upon us about our hats again, bidding the jailer take them off,
which he did, and gave them to us; and we put them on again.
Then we asked the judge and the justices,
what we had lain in prison for these nine weeks,
seeing they now objected nothing to us but about our hats;
and as for putting off our hats, I told them,
that was the honour which God would lay in the dust,
though they made so much to do about it; the honour which is of men,
and which men seek one of another, and is the mark of unbelievers.
For "`how can ye believe,`" saith Christ,
"`who receive honour one of another, and seek not the honour that cometh from God only?`"
and Christ saith, "`I receive not honour from men;`"
and all true Christians should be of his mind.
Then the judge began to make a great speech,
how he represented the lord Protector`'s person;
who had made him lord chief justice of England, and sent him to come that circuit, etc.
We desired him then, that he would do us justice for our false imprisonment,
which we had suffered nine weeks wrongfully.
But instead of that, they brought in an indictment, that they had framed against us;
so strange a thing, and so full of lies,
that I thought it had been against some of the thieves; that we came
"`by force and arms, and in a hostile manner into the court;`"
who were brought, as aforesaid.
I told them, "`it was false;`" and still we cried for justice for our false imprisonment,
being taken up in our journey without cause by Major Ceely.
Then Peter Ceely spoke to the judge, and said, "`May it please you, my lord,
this man (pointing to me, went aside with me,
and told me how serviceable I might be for his design;
that he could raise forty thousand men at an hour`'s warning,
and involve the nation in blood, and so bring in King Charles.
I would have aided him out of the country, but he would not go.
If it please you, my lord, I have a witness to swear it.`"
So he called upon his witness; but the judge not being forward to examine the witness,
I desired that he would be pleased to let my mittimus
be read in the face of the court and country,
in which my crime was signified, for which I was sent to prison.
The judge said, "`it should not be read.`"
I said, "`it ought to be, seeing it concerned my liberty and my life.`"
The judge said again, "`It shall not be read;`" but I said, "`it ought to be read;
for if I have done anything worthy of death, or of bonds, let all the country know it.`"
Then seeing they would not read it, I spoke to one of my fellow-prisoners,
"`Thou hast a copy of it, read it up,`" said I. "`It shall not be read,`" said the judge;
"`Jailer,`" said he, "`take him away, I will see whether he or I shall be master.`"
So I was taken away; and a while after called for again.
I still cried to have my mittimus read; for that signified the cause of my commitment:
wherefore I again spoke to the friend, my fellow-prisoner, to read it.
He did read it, and the judge, justices, and whole court were silent;
for the people were eager to hear it.
It was as follows:--

[.embedded-content-document.paper]
--

[.blurb]
=== Peter Ceely, one of the Justices of the Peace of this County, to the Keeper of His Highness`'s Jail at Launceston, or his lawful Deputy in that behalf. Greeting:--

"`I send you herewithal by the bearers hereof, the bodies of Edward Pyot of Bristol,
and George Fox of Drayton-in-the-Clay, in Leicestershire, and William Salt of London,
which they pretend to be the places of their habitations,
who go under the notion of Quakers, and acknowledge themselves to be such;
who have spread several papers, tending to the disturbance of the public peace,
and cannot render any lawful cause of coming into these parts,
being persons altogether unknown,
and having no pass for their travelling up and down the country,
and refusing to give sureties of their good behaviour,
according to the law in that behalf provided; and refuse to take the oath of abjuration, etc.
These are therefore, in the name of his Highness the lord Protector,
to will and command you, that when the bodies of the said Edward Pyot, George Fox,
and William Salt, shall be unto you brought, you them receive,
and in his highness`'s prison aforesaid you safely keep them,
until by due course of law they shall be delivered.
Hereof fail you not, as you will answer the contrary at your perils.
Given under my hand and seal, at St. Ives, the eighteenth day of January, 1655.`"

[.signed-section-signature]
P+++.+++ Ceely.

--

When it was read I spoke thus to the judge and justices:
"`Thou that sayest thou art chief justice of England, and you justices know,
that if I had put in sureties, I might have gone whither I pleased;
and have carried on the design (if I had had one),
which Major Ceely hath charged me with: and if I had spoken those words to him,
which he hath here declared, judge ye,
whether bail or mainprize could have been taken in that case.`"
Then, turning my speech to Major Ceely, I said,
"`When or where did I take thee aside? Was not thy house full of rude people,
and thou as rude as any of them at our examination:
so that I asked for a constable or some other officer,
to keep the people civil? But if thou art my accuser,
why sittest thou on the bench? This is not a place for thee to sit in;
for accusers do not use to sit with the judge: thou oughtest to come down,
and stand by me, and look me in the face.
Besides, I would ask the judge and justices whether or
not Major Ceely is not guilty of this treason,
which he charges against me,
in concealing it so long as he hath done? Does he understand his place
either as a soldier or a justice of the peace? For he tells you here,
that I went aside with him, and told him what a design I had in hand,
and how serviceable he might be for my design:
that I could raise forty thousand men in an hour`'s time, and bring in King Charles,
and involve the nation in blood.
He saith, moreover, he would have aided me out of the country, but I would not go;
and therefore he committed me to prison for want of sureties for the good behaviour,
as the mittimus declares.
Now do not you see plainly that Major Ceely is
guilty of this plot and treason that he talks of,
and hath made himself a party to it, by desiring me to go out of the country,
and demanding bail of me, and not charging me with this pretended treason till now,
nor discovering it? But I deny and abhor his words,
and am innocent of his devilish design.`"
So that business was let fall: for the judge saw clearly enough,
that instead of ensnaring me, he had ensnared himself.

Major Ceely then got up again and said, "`If it please you, my lord, to hear me:
this man struck me, and gave me such a blow, as I never had in my life.`"
At this I smiled in my heart, and said, "`Major Ceely, thou art a justice of peace,
and a major of a troop of horse,
and tells the judge here in the face of the court and country,
that I (who am a prisoner) struck thee, and gave thee such a blow,
as thou never hadst the like in thy life? What! art thou not ashamed? Prithee,
Major Ceely?`" said I,
"`where did I strike thee? and who is thy witness for
that? who was by?`" He said it was in the Castle-Green,
and that Captain Bradden was standing by, when I struck him.
"`I desired the judge to let him produce his witness for that,
and I called again upon Major Ceely to come down from off the bench, telling him,
it was not fit that the accuser should sit as judge over the accused.`"
When I called again for his witnesses, he said Captain Bradden was his witness.
Then, I said, "`Speak, Captain Bradden, didst thou see me give him such a blow,
and strike him, as he saith?`" Captain Bradden made no answer;
but bowed his head towards me.
I desired him to speak up, if he knew any such thing: but he only bowed his head again.
"`Nay,`" said I, "`speak up, and let the court and country hear,
and let not bowing of the head serve the turn.
If I have done so, let the law be inflicted on me; I fear not sufferings,
nor death itself, for I am an innocent man concerning all this charge.`"
But Captain Bradden never testified to it:
and the judge finding those snares would not hold, cried, "`Take him away,
jailer:`" and then, when we were taken away,
he fined us twenty marks a-piece for not putting off our hats;
and to be kept in prison till we paid it: so he sent us back to the jail.

At night Captain Bradden came to see us, and seven or eight justices with him,
who were very civil to us, and told us,
they believed neither the judge nor any in the court gave credit to the charges
which Major Ceely had brought forward against me in the face of the country.
And Captain Bradden said,
Major Ceely had an intent to take away my life if he could have got another witness.
"`But,`" said I, "`Captain Bradden, why didst not thou witness for me, or against me,
seeing Major Ceely produced thee for a witness,
that thou saw me strike him? and when I desired
thee to speak either for me or against me,
according to what thou saw or knew, thou wouldst not speak.`"
"`Why,`" said he, "`when Major Ceely and I came by you,
as you were walking in the Castle-Green, he put off his hat to you, and said,
'`How do you do, Mr. Fox? Your servant, Sir.`' Then you said to him, '`Major Ceely,
take heed of hypocrisy, and of a rotten heart: for when came I to be thy master,
and thou my servant? Do servants cast their masters into
prison?`' This was the great blow he meant you gave him.`"
Then I called to mind that they walked by us, and that he spoke so to me, and I to him;
which hypocrisy and rotten-heartedness he manifested openly,
when he complained of this to the judge in open court, and in the face of the country;
and would have made them all believe, that I struck him outwardly with my hand.

Now we were kept in prison, and many came from far and near, to see us;
of whom some were people of account in the world;
for the report of our trial was spread abroad,
and our boldness and innocency in our answers to the
judge and court were talked of in town and country.
Among others came Humphrey Lower to visit us, a grave, sober, old man,
who had been a justice of peace; he was very sorry we should lie in prison;
telling us how serviceable we might be if we were at liberty.
We reasoned with him concerning swearing;
and having acquainted him how they tendered the oath of abjuration to us, as a snare,
because they knew we could not swear,
we showed him that no people could be serviceable to God,
if they disobeyed the command of Christ;
and that they that imprisoned us for the hat-honour, which was of men,
and which men sought for, prisoned the good,
and vexed and grieved the Spirit of God in themselves,
which should have turned their minds to God.
So we directed him to the Spirit of God in his heart, and to the light of Christ Jesus;
and he was thoroughly convinced, and continued so to his death,
and became very serviceable to us.^
footnote:[Humphrey Lower, who resided near Bodmin, in Cornwall,
was an influential magistrate, his name appearing as such in the history of the county,
under Charles I. He could, however, say with Paul, "`What things were gain unto me,
those I counted loss for Christ.`"
In 1658, for not attending the national worship,
and refusing to enter into bond to appear at the assizes,
on a presentment made against him by the constable of the parish, H. Lower was,
on his non-appearance, committed, notwithstanding his age and high character,
to Launceston jail, where he continued till the assizes;
and then was put forth without examination or trial,
or any satisfaction for such rough treatment.
In 1660, he was sent for by a warrant, to appear before two justices at '`Wadebridge,
when one of them, Koscarrock, tendered him the oath of supremacy;
and for M9 refusing to take it,
a mittimus was made out and subscribed by Lira and two other magistrates,
who acted very unwillingly.
Thereupon he was again sent to Launceston jail, where he remained about two weeks,
and then was freed by Sir J. Coryton and E. Hearle.
It is stated that H. Lower, when himself in the commission of the peace,
had more obliged the said Koscarrock than any other man,
by doing him many singular offices of justice and courtesy.
The return was a very ungrateful one.
{footnote-paragraph-split}
G+++.+++ Fox mentions large and satisfactory meetings held at his house in 1663 and 1668,
and says that he continued serviceable till his death,
the date of which event is not recorded.]

There came also to see us one Colonel Rouse, a justice of peace,
with a great company with him.
He was as full of words and talk as ever I heard any man in my life,
so that there was no speaking to him.
At length I asked him,
"`whether he had ever been at school, and knew what belonged to questions and answers;`"
(this I said to stop him). "`At school!`" said he,
"`Yes.`" "`At school!`" said the soldiers;
"`doth he say so to our colonel, that is a scholar?`"
Then said I,
"`If he be so, let him be still, and receive answers to what he hath said.`"
Then I was moved to speak the word of life to him in God`'s dreadful power;
which came so over him that he could not open his mouth:
his face swelled and was red like a turkey; his lips moved, and he mumbled something;
but the people thought he would have fallen down.
I stepped to him, and he said he was never so in his life before:
for the Lord`'s power stopped the evil power in him; so that he was almost choked.
The man was ever after very loving to Friends, and not so full of airy words to us;
though he was full of pride; but the Lord`'s power came over him,
and the rest that were with him.

Another time there came an officer of the army, a very malicious, bitter professor,
whom I had known in London.
He was full of his airy talk also, and spoke slightingly of the light of Christ,
and against the truth, and against the Spirit of God being in men,
as it was in the apostles`' days; till the power of God that bound the evil in him,
had almost choked him as it did Colonel Rouse:
for he was so full of evil that he could not speak, but blubbered and stuttered.
But from the time that the Lord`'s power struck him, and came over him,
he was ever after more loving to us.

The assize being over, and we settled in prison upon such a commitment,
that we were not likely to be soon released,
we discontinued giving the jailer seven shillings a-week each for our horses,
and seven for ourselves; and sent our horses out into the country.
Upon which he grew very wicked and devilish; and put us down into Doomsdale, a nasty,
stinking place, where they put murderers, after they were condemned.
The place was so noisome,
that it was observed few that went in ever came out again in health.
There was no house of office in it;
and the excrements of the prisoners that from time to time had been left there,
had not been carried out (as we were told) for many years.
So that it was all like mire,
and in some places to the top of the shoes in water and urine;
and he would not let us cleanse it, nor suffer us to have beds or straw to lie on.
At night some friendly people of the town brought us a candle and a little straw,
and we burnt some of it to take away the stink.
The thieves lay over our heads, and the head jailer in a room by them, over us also.
It seems the smoke went up into the jailer`'s room; which put him into such a rage,
that he took the pots of excrements of the thieves,
and poured them through a hole upon our heads in Doomsdale;
whereby we were so bespattered, that we could not touch ourselves nor one another.
And the stink increased upon us, so that what with that, and what with smoke,
we had nearly been choked and smothered.
We had the stink under our feet before, but now we had it on our heads and backs also;
and he having quenched our straw with the filth he poured down,
had made a great smother in the place.
Moreover he railed at us most hideously, calling us hatchet-faced dogs,
and such strange names as we had never heard.
In this manner were we fain to stand all night, for we could not sit down,
the place was so full of filthy excrements.^
footnote:[We who live in the middle of the 19th century,
when the impartial administration of justice extends to all ranks of society,
and when the accommodations of our prisons are so vigilantly looked into,
can scarcely credit that respectable Englishmen should be
subjected to such gross abuse in pestilential dungeons.
But the early annals of Friends abound with similar cases,
many of them still more aggravated.
Take the following example:--
{footnote-paragraph-split}
During the close imprisonment of Friends at Aberdeen,
Patrick Livingstone often preached to the people through the prison windows,
exhorting them to fear God.
This practice was highly displeasing to the magistrates.
They, therefore, sought to prevent it,
by causing some of them to be separated from the rest of their companions,
and violently thrust into a close-vaulted cell,
on the top of the jail, called the "`ironhouse,`"
where the worst of felons and murderers were usually confined.
They had neither light nor air, except through a long hole in the thick wall,
which had a double grating of iron on the outside, and another within.
Here they were kept night and day, in the heat of the summer of 1678,
when the filthiness of the place, and the corruption of the air so closely pent-up,
produced a multitude of worms, called white maggots, and other vermin,
which swarmed about even upon their beds and victuals,
and manifestly tended to the extreme danger of their health and lives.]
A great while he kept us in this manner, before he would let us cleanse it,
or suffer us to have any victuals brought in but what we had through the grate.
Once a girl brought us a little meat, and he arrested her for breaking his house,
and sued her in the town-court for breaking the prison.
Much trouble he put her to, whereby others were so discouraged,
that we had much to do to get water or victuals.
Near this time we sent for a young woman, Ann Downer, from London, that could write,
and take things well in short-hand, to buy and dress our meat for us,
which she was very willing to do,
it being also upon her spirit to come to us in the love of God;
and she was very serviceable to us.

This head-jailer, we were informed, had been a thief,
and was branded in the hand and in the shoulder:
his wife too had been branded in the hand.
The under-jailer had been branded in the hand and shoulder; and his wife in the hand also.
Colonel Bennet, who was a Baptist teacher,
having purchased the jail and lands belonging to the castle,
had placed this head-jailer therein.
The prisoners, and some wild people, talked of spirits that haunted Doomsdale,
and how many had died in it; thinking perhaps to terrify us therewith.
But I told them, that if all the spirits and devils in hell were there,
I was over them in the power of God, and feared no such thing; for Christ, our priest,
would sanctify the walls and the house to us, he who bruised the head of the devil.
The priest was to cleanse the plague out of the walls of the house under the law,
which Christ, our priest, ended;
who sanctifies both inwardly and outwardly the walls of the house,
the walls of the heart, and all things to his people.

By this time the general quarter-sessions drew nigh;
and the jailer still carrying himself basely and wickedly towards us,
we drew up our suffering case, and sent it to the sessions at Bodmin.
On the reading of which the justices gave order, "`that Doomsdale door should be opened,
and that we should have liberty to cleanse it, and to buy our meat in the town.`"
We also sent a copy of our sufferings to the Protector,
setting forth how we were taken and committed by Major Ceely;
and abused by Captain Keat as aforesaid, and the rest in order.
The Protector sent down an order to Captain Fox, governor of Pendennis Castle,
to examine the matter about the soldiers abusing us, and striking me.
There were at that time many of the gentry of the country at the castle;
and Captain Keat`'s kinsman, that struck me, was sent for before them,
and much threatened.
They told him "`that if I should change my principle,
I might take the extremity of the law against him,
and might recover sound damages of him.`"
Captain Keat also was checked, for suffering the prisoners under his charge to be abused.
This was of great service in the country;
for afterwards Friends might have spoken in any market or steeple-house thereabouts,
and none would meddle with them.
I understood that Hugh Peters, one of the Protector`'s chaplains,
told him they could not do George Fox a greater service
for the spreading of his principles in Cornwall,
than to imprison him there.
And indeed my imprisonment there was of the Lord, and for his service in those parts;
for after the assizes were over, and it was known we were likely to continue prisoners,
several Friends from most parts of the nation came into the country to visit us.
Those parts of the West were very dark countries at that time;
but the Lord`'s light and truth broke forth, shone over all,
and many were turned from darkness to light, and from Satan`'s power unto God.
Many were moved to go to the steeple-houses; and several were sent to prison to us;
and a great convincement began in the country.
For now we had liberty to come out, and to walk in the Castle-Green;
and many came to us on first-days, to whom we declared the word of life.
Great service we had among them, and many were turned to God, up and down the country;
but great rage got up in the priests and professors against the truth and us.
One of the envious professors had collected many Scripture sentences,
to prove that we ought to put off our hats to the people;
and he invited the town of Launceston to come into the castle-yard to hear him read them:
amongst other instances that he there brought, one was,
that Saul bowed to the witch of Endor.
When he had done, we got a little liberty to speak;
and we showed both him and the people, "`that Saul was gone from God,
and had disobeyed God, like them, when he went to the witch of Endor:
that neither the prophets, nor Christ,
nor the apostles ever taught people to bow to a witch.`"
The man went away with his rude people; but some stayed with us,
and we showed them that this was not gospel instruction,
to teach people to bow to a witch.
For now people began to be affected with the truth, and the devil`'s rage increased;
so that we were often in great danger.

One time there came a soldier to us;
and whilst one of our friends was admonishing and exhorting him to sobriety, etc,
I saw him begin to draw his sword.
Whereupon I stepped to him,
and told him what a shame it was to offer to draw his sword upon a naked man,
and a prisoner; and how unfit and unworthy he was to carry such a weapon;
and that if he should have offered such a thing to some men,
they would have taken his sword from him, and have broken it to pieces.
So he was ashamed, and went his way; and the Lord`'s power preserved us.

Another time, about eleven at night, the jailer being half drunk,
came and told me he had got a man now to dispute with me (this was when we
had leave to go a little into the town.)
As soon as he spoke these words,
I felt there was mischief intended to my body.
All that night and the next day I lay down on a grass-plat to slumber,
and I felt something still about my body; and I started up,
and struck at it in the power of the Lord, and yet still it was about my body.
Then I arose and walked into the CastleGreen, and the under-keeper came to me,
and told me there was a maid would speak with me in the prison.
I felt a snare in his words too, therefore I went not into the prison, but to the grate,
and looking in, I saw a man that was lately brought to prison for being a conjuror,
and he had a knife in his hand.
I spoke to him, and he threatened to cut my chaps; but being within the jail,
he could not come at me.
This was the jailer`'s great disputant.
I went soon after into the jailer`'s house, and found him at breakfast;
and he had then got his conjuror out with him.
I told the jailer his plot was discovered.
Then he got up from the table, and east his napkin away in a rage;
and I left them and went away to my chamber; for at this time we were out of Doomsdale.
At the time the jailer had said the dispute should be,
I went down and walked in the court (the place appointed) till about eleven,
but nobody came.
Then I went up to my chamber again, and after a while I heard one call for me.
I stepped to the stairs`' head, and there I saw the jailer`'s wife upon the stairs,
and the conjuror at the bottom of the stairs, holding his hand behind his back,
and in a great rage.
I asked him,
"`Man, what hast thou in thy hand behind thy back? Pluck thy hand before thee,`"
said I; "`let us see thy hand, and what thou hast in it.`"
Then in a rage he plucked forth his hand with a naked knife in it.
I showed the jailer`'s wife the wicked design of her husband and herself against me;
for this was the man they had brought to dispute of the things of God.
But the Lord discovered their plot, and prevented their evil design; they both raged,
and the conjuror threatened.
Then I was moved to speak sharply to him in the dreadful power of the Lord,
which bound him down, so that he never after durst appear before me to speak to me.
I saw it was the Lord alone that preserved me out of their bloody hands;
for the devil had a great enmity to me, and stirred up his instruments to seek my hurt.
But the Lord prevented them;
and my heart was filled with thanksgivings and praises unto him.

Now while I was exercised with people of divers sorts,
that came some out of good will to visit us, some out of an envious,
carping mind to wrangle and dispute, and some out of curiosity to see us, Edward Pyot,
who before his convincement had been a captain in the army,
and had a good understanding in the laws and rights of the people,
being sensible of the injustice and envy of Judge Glynne to us at our trial,
and willing to lay the weight thereof upon him, and make him sensible thereof also,
wrote an epistle to him on behalf of us all, thus:--

[.embedded-content-document.epistle]
--

[.blurb]
=== "`To John Glynne, Chief Justice of England.

[.salutation]
"`Friend,

"`We are free men of England, free born; our rights and liberties are according to law,
and ought to be defended by it: and therefore with thee,
by whose hand we have so long suffered, and still suffer,
let us reason a little plainly concerning thy proceedings against us,
whether they have been according to law, and agreeable to thy duty and office,
as chief minister of the law, or justice of England.
And in meekness and lowliness abide,
that the witness of God in thy conscience may be heard to speak and judge in this matter:
for thou and we must all appear before the judgment-seat of Christ,
that every one may receive according to what he hath done, whether it be good or bad.
Therefore, friend, in moderation and soberness, weigh what is herein laid before thee.

"`In the afternoon, before we were brought before thee at the assize at Launceston,
thou didst cause many scores of our books to be violently
taken from us by armed men without due process of law;
which being perused to see if any thing in them could be found to be laid to our charge,
who were innocent men, and then upon our legal issue,
thou hast detained from us to this very day.
Now our books are our goods, and our goods are our property;
and our liberty is to have and enjoy our property;
and of our liberty and property the law is the defence, which saith,
'`No free man shall be disseized of his freehold, liberties, or free customs, etc,
nor any way otherwise destroyed.: and we shall not pass upon him,
but by lawful judgment of his peers, or by the law of the land.`'
Magna Charta, cap. 29. Now friend, consider, is not the taking away of a man`'s goods violently,
by force of arms, as aforesaid, contrary to the law of the land?
Is not the keeping of them so taken away, a disseizing him of his property,
and a destroying of it and his liberty, yea, his very being,
so far as the invading of the guard the law sets about him, is in order thereunto?
Calls not the law this, a destroying of a man?
Is there any more than one common guard or defence to property, liberty, and life,
viz. the law?
And can this guard be broken on the former (viz. property and liberty),
and the latter (viz. life), be sure?
Doth not he that makes an invasion upon a man`'s property and liberty (which he doth, who,
contrary to law, which is the guard, acts against either),
make an invasion upon a man`'s life; since that which is the guard of the one,
is also of the other?
If a penny, or a penny`'s worth, be taken from a man contrary to law,
may not by the same rule all that a man hath be taken away?
If the bond of the law be broken upon a man`'s property,
may it not on the same ground be broken upon his person?
And by the same reason, as it is broken on one man, may it not be broken upon all,
since the liberty, and property, and beings of all men under a government are relative,
a communion of wealth, as the members in the body,
but one guard and defence to all, the law?
One man cannot be injured therein, but it redounds to all.
Are not such things in order to the subversion and dissolution of government?
Where there is no law, what is become of government?
And of what value is the law made,
when the ministers thereof break it at pleasure upon men`'s properties, liberties,
and persons?
Canst thou clear thyself of these things, as to us?
To that of God in thy conscience, which is just, do I speak.
Hast thou acted like a minister, the chief minister, of the law,
who hast taken our goods, and yet detainest them,
without so much as going by lawful warrant, grounded upon due information,
which in this our case thou couldst not have; for none had perused them,
whereby to give thee information?
Shouldst thou exercise violence and force of arms on prisoners`' goods,
in their prison-chamber, instead of proceeding orderly and legally,
which thy place calls upon thee, above any man, to tender, defend,
and maintain against wrong, and to reserve entire the guard of every man`'s being,
liberty, life, and livelihood?
Shouldst thou, whose duty it is to punish the wrong-doer, do wrong thyself?
who ought to see that the law is kept and observed, break the law,
and turn aside the due administration thereof?
Surely from thee, considering thou art chief justice of England,
other things were expected, both by us and by the people of this nation.

"`And when we were brought before thee, and stood upon our legal issue,
and no accuser or accusation came in against us,
as to what we had been wrongfully imprisoned, and in prison detained for nine weeks,
shouldst not thou have caused us to be acquitted by proclamation?
Saith not the law so?
Oughtest thou not to have examined the cause of our commitment?
And there not appearing a lawful cause, oughtest thou not to have discharged us?
Is it not the substance of thy office and duty,
to do justice according to the law and custom of England?
Is not this the end of the administration of the law?
of the general assizes?
of the jail delivery?
of the judges going the circuits?
Hast not thou by doing otherwise, acted contrary to all these, and to Magna Charta?
which, chap. 29, saith, '`We shall sell to no man, we shall deny or defer to no man,
either justice or right.`'
Hast thou not both deferred and denied to us, who had been so long oppressed,
this justice and right?
And when of thee justice we demanded, saidst thou not, '`If we would be uncovered,
thou wouldst hear us, and do us justice?`'--'`We shall sell to no man,
we shall deny or defer to no man, either justice or right,`' saith Magna Charta,
as aforesaid.
Again, '`We have commanded all our justices, that they shall henceforth do even law,
and execution of right to all our subjects, rich and poor,
without having regard to any man`'s person;
and without letting to do right for any letters or commandments,
which may come to them from us, or from any other, or by any other cause, etc,
upon pain to be at our will, body, lands, and goods, to do therewith as shall please us,
in case they do contrary,`' saith Stat. 20. Edw. III. cap. 1.
Again, '`Ye shall swear that ye shall do even law and execution of right to all,
rich and poor, without having regard to any person;
and that ye deny to no man common right by the king`'s letters, or other man`'s,
nor for any other cause.
And in case any letter come to you contrary to the law,
that ye do nothing by such letter, but certify the king thereof,
and go forth to do the law notwithstanding those letters.
And in case ye be from henceforth found in default in any of the points aforesaid,
ye shall be at the king`'s will of body, lands, and goods, thereof to be done,
as shall please him,`' saith the oath,
appointed by the statute to be taken by all the judges, Stat. 18. Edw. III.
But none of these,
nor any other law hath such an expression or condition in it as this, viz.,
'`provided he will put off his hat to you,
or be uncovered:`' nor doth the law of God so say, or that your persons be respected;
but the contrary.
From whence then comes this new law, '`If ye will be uncovered, I will hear you,
and do you justice?`'
This hearing complaint of wrong, this doing of justice, upon condition,
wherein lies the equity and reasonableness of that?
When were these fundamental laws repealed, which were the issue of much blood and war;
to uphold which cost the miseries and blood of the late wars, that we shall now be heard,
as to right, and have justice done us but upon condition,
and that too such a trifling one as putting off the hat?
Doth thy saying so, who art commanded, as aforesaid, repeal them,
and make them of none effect, and all the miseries undergone,
and the blood shed for them of old, and of late years?
Whether it be so or not indeed, and to the nation, thou hast made it so to us,
to whom thou hast denied the justice of our liberty (when we were before thee,
and no accuser, nor accusation came in against us),
and the hearing of the wrong done to us, who are innocent, and the doing us right.
And bonds hast thou cast, and continued upon us until this day,
under an unreasonable and cruel jailer, for not performing that thy condition,
for conscience-sake.
But thinkest thou that this thine own conditional justice maketh void the law?
or can it do so?
or absolve thee before God or man?
or acquit the penalty mentioned in the laws aforesaid?
unto which hast thou not consented and sworn?
viz., '`And in case ye be from henceforth found in default,
in any of the points aforesaid, ye shall be at the king`'s will, of body, lands,
and goods, thereof to be done as shall please him.`'
And is not thy saying, '`If ye will be uncovered (or put off your hats), I will hear you,
and do you justice;`' and because we could not put them off for conscience-sake,
thy denying us justice, and refusing to hear us, as to wrong,
who had so unjustly suffered, a default in thee against the very essence of those laws,
yea, an overthrow thereof,
for which thing`'s sake (being of the highest importance to the well-being of men),
so just, so equal, so necessary, those laws were made, and all the provisions therein?
To make a default in any one point of which provisions, exposeth to the said penalty.
Dost not thou by this time see where thou art?
Art thou sure thou shalt never be made to understand and feel the justice thereof?
Is thy seat so high, raid thy fence so great,
and art thou so certain of thy time and station, above all that have gone before thee,
whom justice hath cut down, and given them their due,
that thou shalt never be called to an account,
nor with its long and sure stroke be reached?
Deceive not thyself,
God is come nearer to judgment than the workers of iniquity in this age imagine;
who persecute and evil-entreat those that witness the Just and Holy One,
for their witnessing of him who is come to reign for ever and ever.
Saith he not, he will be a swift witness against the false swearers?
God is not mocked.

"`Surely, friend,
that must needs be a very great offence which deprives a man of justice,
of being heard as to wrong, of the benefit of the law, and of those laws afore-rehearsed;
to defend the justice and equity of which a man hath
adventured his blood and all that is dear to him.
But to stand covered (or with the hat on), in conscience to the command of the Lord,
is made by thee such an offence (which is none in law),
and rendered upon us (who are innocent, serving the living God),
effectual to deny us justice, though the laws of God, and of man, and the oath,
equity and reason, say the contrary, and on it pronounce such a penalty.
'`If ye will be uncovered (uncovered, saidst thou), I will hear you,
and do you justice;`' but justice we had not, nor were we heard, because Jesus Christ,
who is the higher power, the lawgiver of his people,
in our consciences commanded us not to respect persons,
whom we choose to obey rather than man.
And for our obedience unto him hast thou cast us into prison,
and continue us there till this very day, having showed us neither law for it,
nor Scripture, nor instances of either, nor example of heathens nor others.
Friend, come down to that of God, that is just in thee, and consider,
was ever such a thing as this heard of in this nation?
What is become of seriousness, of true judgment, and of righteousness?
An unrighteous man, standing before thee with his hat off, shall be heard;
but an innocent man, appearing with his hat on in conscience to the Lord,
shall neither be heard nor have justice.
Is not this regarding of persons contrary to the laws aforesaid,
and the oath and the law of God?
Understand and judge: Did we not own authority and government oftentimes before the court?
Didst not thou say in the court,
thou wast glad to hear so much from us of our owning magistracy?
Pleaded we not to the indictment,
though it was such a new-found one as England never heard of before?
Came we not when thou sent for us?
Went we not when thou bade us go?
And are we not still prisoners at thy command and at thy will?
If the hat had been such an offence to thee,
couldst not thou have caused it to be taken off, when thou heard us so often declare,
we could not do it in conscience to the commands of the Lord,
and that for that cause we forbore it, not in contempt of thee or of authority,
nor in disrespect to thine, or any man`'s person (for we said,
we honoured all men in the Lord, and owned authority, which was a terror to evil-doers,
and a praise to them that do well;
and our souls were subject to the higher powers for conscience-sake):
as thou caused them to be taken off, and to be kept so,
when thou called the jury to find us transgressors without a law?
What ado hast thou made to take away the righteousness of the righteous from him,
and to cause us to suffer further,
whom thou knew to have been so long wrongfully in prison contrary to law?
Is not liberty of conscience a natural right?
Had there been a law in this case,
and we bound up in our consciences that we could not have obeyed it,
was not liberty of conscience there to take place?
For where the law saith not against, there needs no plea of liberty of conscience;
but the law have we not offended, yet in thy will hast thou caused,
and dost thou yet cause us to suffer for our consciences,
where the law requires no such thing;
and yet for liberty of conscience hath all the blood been spilt,
and the miseries of the late wars undergone, and (as the Protector saith),
this government undertakes to preserve it; and a natural right, he saith, it is;
and he that would have it, he saith, ought to give it.
And if it be a natural right, as is undeniable, then to attempt to force it,
or to punish a man for not doing contrary to it, is to act against nature; which,
as it is unreasonable, so it is the same as to offer violence to a man`'s life.
And what an offence that is in the law thou knowest; and how,
by the common law of England, all acts, agreements, and laws, that are against nature,
are mere nullities;
and all the judges cannot make one case to be law that is against nature.
But put the case, had our standing with our hats on been an offence in law,
and we wilfully, and in contempt,
and not out of conscience had stood so (which we deny as aforesaid),
yet that is not a ground wherefore we should be denied justice,
or be heard as to the wrong done to us.
'`If ye will not offend in one case,
I will do you justice in another;`' this is not the language of the law, or of justice,
which distributes to every one right; justice to whom justice is due,
punishment to whom punishment is due.
A man who does wrong may also have wrong done to him;
shall he not have right wherein he is wronged, unless he right him whom he hath wronged?
The law saith not so; but the wrong-doer is to suffer,
and the sufferer of wrong to be righted.
Is not to do otherwise a denying, letting,
or stopping of even law and execution of justice,
and a bringing under the penalties aforesaid?
Mind and consider.

"`And shouldst thou have accused, when no witness appeared against us,
as in the particulars of striking Peter Ceely,
and dispersing books (as thou saidst) against magistracy and ministry,
with which thou didst falsely accuse one of us?
Saith not the law, '`the judge ought not to be the accuser?`'
much less a false accuser?
And wast not thou such a one, in affirming,
that he dispersed books against magistracy and ministry,
when as the books were violently taken out of our
chamber (as hath been said,) undispersed by him, or any of us?
Nor didst thou make it appear in one particular,
wherein those books thou didst so violently cause to be taken away,
were against magistracy or ministry?
or gave one instance, or reply, when he denied what thou charged therein,
and spoke to thee to bring forth those books and make thy charge appear.
Is not the sword of the magistrate of God to pass upon such evil-doing?
And according to the administration of the law,
ought not accusations to be by way of indictment, wherein the offence is to be charged,
and the law expressed against which it is?
Can there be an issue without an indictment?
Or can an indictment be found before proof be made of the offence charged therein?
And hast thou not herein acted contrary to the law and the administration thereof,
and thy duty as a judge?
What just cause of offence gave George Fox to thee, when,
upon thy producing a paper concerning swearing,
sent by him (as thou said) to the grand jury, and requiring him to say,
whether it was his handwriting?
he answered, '`read it up before the country, and when he heard it read, if it were his,
he would own it?`'
Is it not equal, and according to law,
that what a man is charged with before the country,
should be read in the hearing of him and of the country?
When a paper is delivered out of a man`'s hand,
alterations may be made in it to his prejudice, which, on a sudden looking over it,
may not presently be discerned, but by hearing it read up, may be better understood,
whether any such alterations have been made therein?
Couldst thou in justice have expected or required him to do otherwise?
Considering also, that he was not insensible how much he had suffered already,
being innocent, and what endeavours were used to cause him further to suffer?
Was not what he said, as aforesaid, a plain and single answer, and sufficient in the law?
Though (as hath been demonstrated) thou didst act contrary to law, and to thy office,
in being his accuser therein, and producing the paper against him.
And his liberty it was, whether he would have made thee any answer at all,
to what thou didst exhibit, or demand, out of the due course of law;
for to the law answer is to be made, not to thy will.
Wherefore then wast thou so filled with rage and fury at his reply?
Calmly, and in the fear of the Lord, consider, wherefore didst thou revile him,
particularly with the reproachful names of juggler and prevaricator?
Wherein did he juggle?
wherein did he prevaricate?
Wherefore didst thou use such threatening language, and such menacings to him and us,
saying, thou wouldst ferk us, with such like?
Doth not the law forbid reviling, and rage, and fury, threatening,
and menacing of prisoners?
Soberly mind, is this to act like a judge or a man?
Is not this transgression?
Is not the sword of the magistrate of God to pass on this as evil-doing,
which the righteous law condemns, and the higher power is against, which judgeth for God?
Take heed what ye do, for ye judge not for man, but for the Lord,
who is with you in the judgment.
'`Wherefore now, let the fear of the Lord be upon you; take heed, and do it:
for there is no iniquity with the Lord our God, nor respect of persons,
nor taking of gifts,`' said Jehoshaphat to the judges of Judah.
Pride and fury, passion and rage, reviling and threatening, are not the Lord`'s; these,
and the principle out of which they spring, are for judgment,
and must come under the sword of the magistrate of God; and it is of an ill savour,
especially such an expression, as to threaten to ferk us.
Is not such a saying more becoming a schoolmaster with his rod and ferule in his hand,
than thee, who art the chief justice of the nation,
who sittest in the highest seat of judgment, who ought to give a good example,
and so to judge that others may hear and fear?
Weigh it soberly and consider, doth not threatening language demonstrate an inequality,
and partiality in him, who sits as judge?
Is it not a deterring of a prisoner from standing to,
and pleading the innocency of his cause?
Provides not the law against it?
Saith it not, that irons and all other bonds shall be taken from the prisoner,
that he may plead without fear, and with such freedom of spirit,
as if he were not a prisoner?
But when he, who is to judge according to the law,
shall beforehand threaten and menace the prisoner contrary to the law,
how can the mind of the prisoner be free to plead his innocency before him?
or expect equal judgment from him who, before he hears him,
threatens what he will do unto him?
Is not this the case between thee and us?
Is not this the measure we have received at thy hands?
Hast thou herein dealt according to law?
or to thy duty?
or as thou wouldst be done unto?
Let that of God in thy conscience judge.

"`And didst thou not say, there was a law for putting off the hat,
and that thou wouldst show a law?
and didst not thou often so express thyself?
But didst thou produce any law, or show where that law might be found?
or any judicial precedent, or in what king`'s reign, when we so often desired it of thee,
having never heard of, nor known any such law, by which thou didst judge us?
Was not what we demanded of thee reasonable and just?
Was that a savoury answer, and according to law, which thou gave us, viz.,
'`I am not to carry the law-books at my back, up and down the country;
I am not to instruct you?`'
Was ever such an expression heard before these days to come out of a judge`'s mouth?
Is he not to be of counsel in the law for the prisoner, and to instruct him therein?
Is it not for this cause that the prisoner, in many cases,
is not allowed counsel by the law?
In all courts of justice in this nation, has it not been known so to have been?
And to the prisoner has not this been often declared when he demanded counsel,
alleging his ignorance in the law, by reason of which his cause might miscarry,
though it were righteous, viz., '`the court is of counsel for you?`'
Ought not he that judgeth in the law, to be expert in the law?
Couldst thou not tell by what act of parliament it was made,
or by what judicial precedent, or in what king`'s reign,
or when it was adjudged so by the common law
(which are all the grounds the law of England has)
had there been such a law, though the words of the law thou couldst not remember?
Surely, to inform the prisoner when he desired it,
especially as to a law which was never heard of, by which he proceeds to judge him,
that he may know what law it is by which he is to be judged,
becomes him who judgeth for God;
for so the law was read to the Jews by which they were to be judged, yea,
every Sabbath-day; this was the commandment of the Lord.
But instead thereof to say,
'`I am not to carry the law-books at my back up and down the country;
I am not to instruct you:`' to say, '`there is a law,`' and to say,
'`thou wilt show it,`' and yet not to show it, nor to tell where it is to be found;
consider whether it be consistent with truth or justice?

"`Have not thy whole proceedings against us made it evidently appear,
that thy desire was to cause us to suffer, not to deliver us, who, being innocent,
suffered; to have us aspersed and reproached before the country,
not to have our innocency cleared and vindicated?
Doth not thy taking away our books as aforesaid,
and perusing them in such haste before our trial, and accusing us with something,
which thou said was contained in them, make it to appear,
that matter was sought out of them, wherewithal to charge us,
when the Et Cetera warrant would not stand in law, by which we stood committed,
and were then upon our delivery, according to due course of law?
Doth it not further appear,
by thy refusing to take from our hands a copy of the strange Et Cetera warrant,
by which we were committed, and of the paper for which we were apprehended,
to read it or cause it to be read,
that so our long sufferings by reason of both might be looked into,
and weighed in the law, whether just or righteous,
and tho country might as well see our innocency and sufferings without a cause,
and the manner of dealing with us as to hear such reports as went of us,
as great offenders, when we called upon thee often so to do,
and which thou ought to have done, and said, thou would do, but did it not;
or so much as take notice before the country that we had been falsely imprisoned,
and had wrongfully suffered?
But what might asperse and charge us, thou brought in thyself, contrary to law,
and called to have us charged therewith.
Is not this further manifest, in that thou didst cause us on a sudden to be withdrawn,
and the petty jury to be called in with their verdict,
whereupon Peter Ceely`'s falsely accusing George
Fox with telling him privately of a design,
and persuading him to join therein,
it was by G. Fox made so clear to be a manifest falsehood,
and so plainly to be perceived,
that the cause of our sufferings was not any evil we had done,
or law that we had transgressed, but malice and wickedness?
And is it not abundantly clear from thy not permitting us to '`answer,
and clear ourselves of the many foul slanders
charged upon us in the new-found indictment,
of which no proof was made; but when we were answering thereunto,
and clearing ourselves thereof, thou didst stop us, saying,
'`thou minded not those things, but only the putting off the hat;`' when as,
before the country, the new-found indictment, charged us with those things,
and the petty jury brought in their verdict,
'`guilty of the trespasses and contempts mentioned therein;
of which (except as to the hat) not one witness or evidence was produced;
and as to the hat, not any law, or judicial precedent,
upon the transgression of which all legal indictments are only to be grounded?
Now the law seeks not for causes whereby to make the innocent suffer,
but helps him to right who suffers wrong, relieves the oppressed,
and searches out the matter, whether that, of which a man stands accused, be so or not,
seeking judgment, and hastening righteousness; and it saith,
'`the innocent and the righteous slay thou not.`'
But whether thou hast done so to us, or the contrary,
let the witness of God in thee search and judge,
as these thy fruits do also make manifest.

"`And, friend, consider how abominably wicked, and how highly to be abhorred, denied,
and witnessed against, and how contrary to the laws such a proceeding is,
to charge a man with many offences in an indictment, which they who draw the indictment,
they who prosecute, and they who find the bill, know to be false,
and to be inserted purposely to reproach and wound his good name,
whom with some small matter which they can prove, they charge and indict;
as is the common practice at this day.
Prove but one particular charge in the indictment,
and it must stand (say they) for a true bill,
though there be ever so many falsehoods therein, purposely to wrong him,
who is maliciously prosecuted: this is known to the judges,
and almost every man who has to do with, and attends, their courts.
How contrary is this to the end and righteousness of the law, which clears the innocent,
and condemns the guilty, and condemns not the righteous with the wicked?
Much it is cried out against; but what reformation is there thereof?
How else shall clerks of assize, and other clerks of courts,
fill up their bags (out of which perhaps their master must have a secret consideration),
and be heightened in pride and impudence;
that even in open court they take upon them to check and revile men; men without reproof,
when a few lines might serve instead of a hundred?
How else shall the spirit that is in men, that lusteth unto envy, malice, strife,
and contention, be cherished and nourished to feed the lawyers, and dependents on courts,
with the bread of men`'s children, and the ruin of their families,
to maintain their long suits and malicious intentions.
For a judge to say, '`I mind not these things;
I will not hear you clear yourselves of what you are falsely accused:
one thing I mind in your charge, the rest are but matter of form,
set there to render you such wicked men before the country,
as the thing that is to be proved against you is not sufficient to make out.`'
O! abominable wickedness, and perverting of the righteous end of the law,
which is so careful and tender of every man`'s peace and innocency.
How is the law in the administration thereof adulterated by lawyers,
as the Scriptures are mangled by priests!
And that which was made to preserve the righteous, and to punish the wicked,
perverted to the punishing of the righteous, and the preserving of the wicked!
An eye for an eye; a tooth for a tooth; life for life; burning for burning;
wound for wound; a stripe for a stripe;
he that accuseth a man falsely to suffer the same as he should have suffered,
who was falsely accused, if he had been guilty; this saith the righteous law of God,
which is agreeable to that of God in every man`'s conscience.
Are not such forms of iniquity to be denied,
which are so contrary to the law of God and man?
which serve for gendering strife, and kindling contention?
and of this nature was not that, with which thou didst cause us to be indicted?
and this form didst thou not uphold,
in not permitting us to answer to the many foul slanders therein; saying,
'`Those things thou mindest not.`'
Will not the wrath of God be revealed from heaven
against all ungodliness and unrighteousness of men,
who hold the truth in unrighteousness; who are so far from the power of godliness,
that they have not the form, but the form of iniquity, which is set and held up,
instead of, and as a law, to overthrow and destroy the righteousness of the righteous,
and so to shut him up, as by the law he can never get out?
Is not the cry, thinkest thou, gone up?
'`It is time for thee to set to thine hand, O Lord,
for thine enemies have made void thy law!`' Draws not the hour nigh?
Pills not up the measure of iniquity apace?
Surely the day is coming, and hasteneth.
Ye have been warned from the presence, and by the mouth of the Lord;
and clear will he be when he cometh to judgment, and upright when he giveth sentence.
That of God in every one of your consciences shall so to him bear witness and confess,
and your mouths shall be stopped, and before your judge shall ye be silent,
when he shall divide you your portion, and render unto you according to your deeds.
Therefore, whilst thou hast time, prize it, and repent: for verily '`Our God shall come,
and shall not keep silence; a fire shall devour before him,
and it shall be very tempestuous round about him.
He shall call to the heavens from above, and to the earth that he may judge his people;
and the heavens shall declare his righteousness: for God is judge himself.
Consider this, ye that forget God, lest he tear you in pieces,
and there be none to deliver.`'

"`And, friend, shouldst thou have given judgment against us
(wherein thou didst fine us twenty marks a-piece, and imprisonment till payment),
without causing us, being prisoners,
to be brought before thee, to hear the judgment,
and to move what we had to say in arrest of judgment?
Is not this contrary to the law,
as is manifest to those who understand the proceedings thereof?
Is not the prisoner to be called before judgment be given?
and is not the indictment to be read?
and the verdict thereupon?
And is not liberty to be given him to move in arrest of judgment?
And if it be a just exception in the law, ought not there to be an arrest of judgment?
For the indictment may not be drawn up according to law, and may be wrong placed,
and the offence charged therein may not be a crime in law;
or the jury may have been corrupted, or menaced, or set on by some of the justices;
with other particulars, which are known to be legal and just exceptions.
And the judgment ought to be in the prisoner`'s hearing, not behind his back,
as if the judge were so conscious of the error thereof,
that he dare not give it to the face of the prisoner.
But these privileges of the law, this justice,
we (who had so long and so greatly suffered contrary to law), received not,
nor could have at thy hands; no,
not so much as a copy or sight of that long and new-found
indictment (which in England was never heard of before,
nor that the matter contained therein was an offence in law, nor ever was there any law,
or judicial precedent, that made it so);
though two friends of ours in our names and our behalf, that night, next day,
and day following, often desired it of the clerk of the assize, his assistants,
and servants; but they could not have it, nor so much liberty as to see it.
And it is likely not unknown, or unperceived by thee, that, had we been called,
as we ought to have been, or known when it was to be given,
three or four words might have been a sufficient, legal arrest,
of the judgment given on that new-found indictment, and the verdict thereupon.
Therefore, as our liberties, who are innocent,
have not (in thy account) been worth the minding,
and esteemed fit for nothing but to be trampled under foot and destroyed, so,
if we find fault with what thou hast done,
thou hast taken care that no door be left open to us in the law, but a writ of error;
the consideration whereof, and the judgment to be given thereon,
is to be had only where thyself art chief; of whom such complaint is to be made,
and the error assigned for the reverse of thy judgment.
And what the fruit of that may be well expected to be, by what we have already mentioned,
as having received at thy hands, thou hast given us to understand.
And here thou mayest think thou hast made thyself secure,
and sufficiently barred up our way of relief,
against whom (though thou knew we had done nothing contrary to the law,
or worthy of bonds, much less of the bonds and sufferings we had sustained):
thou hast proceeded as has been rehearsed;
notwithstanding that thou art (as are all the judges of the nation) entrusted,
not with a legislative power, but to administer justice,
and to do even law and execution of right to all, high and low, rich and poor,
without having regard to any man`'s person; and art sworn so to do, as has been said:
and wherein thou dost contrary art liable to punishment, as ceasing from being a judge,
and becoming a wrongdoer and an oppressor; which what it is to be,
many of thy predecessors have understood, some by death, others by fine and imprisonment.
And of this thou mayest not be ignorant,
that to deny a prisoner any of the privileges the law allows him, is to deny him justice,
to try him in an arbitrary way, to rob him of that liberty which the law gives him,
which is his inheritance as a free man;
to do which is in effect to subvert the fundamental laws and government of England,
and to introduce an arbitrary and tyrannical government against law;
which is treason by the common law;
and treasons by the common law are not taken away by the statutes of 25 Edw.
III. 1 Henry IV. 1, 2, m. See O. St. Johns, now chief justice of the common pleas,
his argument against Strafford, fol. 65, in the case.

"`These things we have laid before thee in all plainness,
that (with the light of Jesus Christ, who lighteth every one that cometh into the world,
a measure of winch thou hast, which showeth the evil, and reproveth thee for sin,
for which thou must be accountable) thou mayest consider and
see what thou hast done against the innocent;
that shame may overtake thee, and thou mayest turn unto the Lord,
who now calleth thee to repentance by his servants, whom,
for witnessing his living truth in them, thou hast cast into, and yet continues under,
cruel bonds and sufferings.`"

[.signed-section-signature]
Edward Pyot.

[.signed-section-context-close]
From the Jail in Launceston, the 14th day of the 5th Month, 1656.

--

By this letter the reader may observe how contrary to law we were made to suffer:
but the Lord, who saw the integrity of our hearts to him,
and knew the innocency of our cause, was with us in our sufferings, bore up our spirits,
and made them easy to us;
and gave us opportunities of publishing his name and truth amongst the people;
so that several of the town came to be convinced, and many were made loving to us.
Friends from many parts came to visit us; amongst whom were two out of Wales,
who had been justices of peace.
Also Judge Hagget`'s wife, of Bristol, who was convinced, with several of her children;
and her husband was very kind and serviceable to Friends, and had a love to God`'s people,
which he retained to his death.

Now in Cornwall, Devonshire, Dorsetshire, and Somersetshire,
truth began to spread mightily,
and many were turned to Christ Jesus and his free teaching:
for many Friends that came to visit us,
were drawn forth to declare the truth in those countries;
which made the priests and professors rage,
and they stirred up the magistrates to ensnare Friends.
They placed watches in the streets and highways,
on pretence of taking up all suspicious persons;
under which colour they stopped and took up the Friends
that travelled in and through those countries,
coming to visit us in prison; which they did,
that they might not pass up and down in the Lord`'s service.
But that by which they thought to stop the truth,
was the means of spreading it so much the more;
for then Friends were frequently moved to speak to one constable,
and to the other officer, and to the justices they were brought before;
and this caused the truth to spread the more amongst them in all their parishes.
And when Friends got among the watches,
it would be a fortnight or three weeks before they could get out of them again;
for no sooner had one constable taken them and carried them before the justices,
and they had discharged them, than another would take them up,
and carry them before other justices;
which put the country to much needless trouble and charges.

As Thomas Rawlinson was coming out of the north to visit us,
a constable in Devonshire took him up,
and at night took twenty shillings out of his pocket; and after being thus robbed,
he was cast into Exeter jail.
They cast Henry Pollexfen also into prison in Devonshire for being a Jesuit,
who had been a justice of peace for nearly forty years before.
Many Friends were cruelly beaten by them; nay,
some clothiers that were going to the mill with their cloth,
and others about their occupations, were taken up and whipped,
though men of about eighty or a hundred pounds a year,
and not above four or five miles from their families.

The mayor of Launceston, too, was a very wicked man, for he took up all he could get,
and cast them into prison; and he would search substantial grave women,
their petticoats and their head-clothes.
A young man having come to see us, who came not through the town,
I drew up all the gross, inhuman,
and unchristian actions of the mayor (for his carriage
was more like a heathen than a Christian),
to him I gave it, and bid him seal it up, and go out again the back way;
and then come into the town through the gates.
He did so; and the watch took him up, and carried him before the mayor,
who presently searched his pockets and found the letter,
wherein he saw all his actions characterized.
This shamed him so, that from that time he meddled little with the servants of the Lord.

Now from the sense I had of the snare that was laid, and mischief intended,
in setting up those watches at the time to stop and take up Friends,
it came upon me to give forth the following, as--

[.embedded-content-document.paper]
--

[.blurb]
=== "`An Exhortation and Warning to the Magistrates.

"`All ye powers of the earth, Christ is come to reign, and is among you,
and ye know him not; who doth enlighten every one of you,
that ye all through him might believe in him, who is the light,
who treads the wine-press alone without the city, and whose feet are upon it.
Therefore see all, and examine with the light, what ye are ripe for;
for the press is ready for you.

"`Before honour is humility.
You that would have honour before ye have humility (mark, before ye have humility),
are ye not as the heathen are?
Ye would have honour before ye have humility;
did not all the persecutors that ever were upon the earth want this humility?
They wanted the honour, and yet would have the honour before they had the humility,
and had learned that.
So ye that are out of the humility, are out of the honour;
and ye are not to have the honour, who have not the humility;
for before honour is humility; mark, before it.

"`Now ye pretend liberty of conscience; yet one shall not carry a letter to a friend,
nor men visit their friends, nor prisoners, nor carry a book about them,
either for their own use, or for their friends.
Men shall not see their friends; but watches are set up to catch and stop them;
and these must be well-armed men too, against an innocent people,
that have not so much as a stick in their hands, who are in scorn called Quakers.
Yet by such as set up these watches is pretended liberty of conscience; who take up them,
whose consciences are exercised towards God and men,
who worship God in spirit and in truth; which they that are out of the light call heresy.
Now these set up the watches against them, whom they in scorn call Quakers,
because they confess and witness the true light,
that lighteth every one that cometh into the world, amongst people,
as they pass through the country, or among their friends.
This is the dangerous doctrine which watchmen are set up against, to subdue error,
as they call it,
which is the light that doth enlighten every man that cometh into the world--Him,
by whom the world was made; who was glorified with the Father before the world began.
For those whom they in scorn call Quakers, have they set their watches, able men,
well-armed; to take up such as bear this testimony either in words, books, or letters.
So that is the light you hate, which enlightens every man that cometh into the world;
and these that witness to this light you put in prison;
and after you have imprisoned them,
you set your watches to take up all that go to visit them, and imprison them also;
so that by setting up your watches, ye would stop all relief from coming to prisoners.
Therefore this is the word of the Lord God to you, and a charge to you all,
in the presence of the living God of heaven and earth;
every man of you being enlightened with a light that cometh from Christ,
the Saviour of people`'s souls; to this light, all take heed,
that with it you may see Christ, from whom the light cometh, to be your Saviour,
by whom the world was made, who saith, '`Learn of me.`'
But if ye hate this light, ye hate Christ, who doth enlighten you all,
that through him you might believe.
But not believing in, nor bringing your deeds to the light,
which will make them manifest and reprove them, this is your condemnation,
even the light.
Remember, you are warned in your life-time, for this light is your way to salvation,
if you walk in it; and your condemnation, if you reject and hate it.
You can never come to Christ, the Second Priest, unless you come to the light,
which the Second Priest hath enlightened you withal.
So ye that come not to the light, ye go to the priests that take tithes,
as did the first priesthood;
and hale out of your synagogues and temples (as some call them),
as that priesthood did that took tithes;
which they that were of the second priesthood did not.
Was there ever such a generation! or did ever such a generation of men appear,
as in this age, who are so full of madness, envy, and persecution,
that they stand up in watches, with weapons against the truth, to persecute it,
as the towns and countries do declare; which rings as Sodom, and like Gomorrah!
And this hath its liberty, and truth is stood against;
and to reprove sin is accounted a breach of the peace,
as they say who are out of the truth, and set up their watches against it.`"

[.signed-section-signature]
G+++.+++ F.

--

Besides this general warning,
there coming to my hand a copy of a warrant issued from the Exeter sessions,
in express terms, "`for apprehending all Quakers,`"
wherein truth and Friends were reproached and vilified,
I was moved to write an answer thereunto, and send it abroad,
for clearing truth and Friends from the slanders therein cast upon them,
and to manifest the wickedness of that persecuting spirit from whence it proceeded;
which was after this manner:--

[.small-break]
'''

[.embedded-content-document.letter]
--

"`Whereas a warrant was granted last sessions, held at Exeter,
on the eighteenth day of the fifth month, 1656,
which warrant is '`for apprehending and taking up all such as are Quakers,
or call themselves Quakers, or go under the notion of Quakers;
and is directed to the chief constables, to be sent by them to the petty constables,
requiring them to set watches, able men with bills,
to take up all such Quakers as aforesaid.`'
And whereas in your said warrant,
you speak of the Quakers spreading seditious books and papers; I answer,
They whom ye in scorn call Quakers, have no seditious books or papers;
but their books are against sedition, and seditious men, and seditious books,
and seditious teachers, and seditious ways.
Thus ye have numbered them, who are honest, godly, and holy men, that fear God,
amongst beggars, rogues, and vagabonds;
thus putting no difference between the precious and the vile.
You are not fit to judge, who have set up your bills, and armed your men,
to stand up together in battle against innocent people, the lambs of Christ,
who have not lifted up a hand against you.
But if ye were sensible of the state of your own country, your cities, your towns,
your villages, how the cry of them is like Gomorrah, and the ring like Sodom,
and the sound like the old world, where all flesh had corrupted its way,
which God overthrow with the flood;--if you did consider this with yourselves,
you would find something to turn the sword against,
and not against the lambs of Christ;--you would not make a mock of the innocent,
that stand a witness against all sin and
unrighteousness in your towns and steeple-houses.
Noah, the eighth person, a preacher of righteousness,
was grieved with the filthy conversation of the wicked; so are we now.
So likewise just Lot was grieved with their unmerciful deeds,
and the filthy conversation of Sodom.
And were not these hated of the world, and of them that lived in filthiness?
And whereas you speak of those, whom you in scorn call Quakers,
that they are a grief to those whom you call pious and religious people,
and their religion.
To such as are in the religion that is vain, whose tongues are not bridled,
I believe the Quakers are a grief;
but they are not a grief to such as are in the pure religion,
which keepeth unspotted from the world; which sets not up bills, nor watches,
to maintain it by the world; for they are not of the world who are in the pure religion,
which keeps them unspotted of the world; mark, the '`pure religion,
which keeps unspotted of the world.`'
But to such as are in the religion that is not pure, who have a form of godliness,
and not the power--to such as you call pious, the truth itself was always a grief;
and so it is in this age.
And now your fruits appear, the end of your religion and profession,
and what you possess; but you are in error, and have been but in the profession,
out of the possession of the Spirit, who are not in the Spirit of truth.
Tor where did that ever set stints and bounds,
and number the just and innocent with the wicked?
But the wicked set stints, and bounds, and limits to the just,
and number them among the wicked; yea, they spoke all manner of evil of them,
as ye are doing now of us.
Nay, according as it was foretold in the Scripture, such as tremble at the word of God,
you cast out and hate, you that have your temple-worship.
You say, the Quakers come to disturb you in your churches (as you call them);
was it not the practice of the apostles to go into the synagogues and temples,
to witness against the priesthood that took tithes,
and was it not the practice of the Jews to hale them out, persecute and stone them,
that witnessed Christ the second priest,
and went to bring people off from the first priesthood?
Was it not the practice of the prophets, to go and cry against the high places?
And was it not the practice of the Jews, when they were backslidden, and of the heathen,
to imprison and persecute the prophets, and send after them into other countries?
And is this not the practice of you now, who are holding up your high places,
which the Papists erected, which ye now call your churches; where ye beat and persecute?
What kind of religious people are you, that are filled with so much madness?
Did not Paul confess he was mad, while he was in your practice, haling, beating,
imprisoning, putting out of the synagogues, having his authority from the chief priests?
And are not the chief priests the cause of this?
Was there ever such a cry made in any ago past, as there is now in the pulpits,
railing against an innocent people, whom in scorn ye call Quakers,
who lift not up a hand against you; but who are indeed the pious,
that are of the pure religion, who fear God, worship him in Spirit and in truth,
and cannot join with you in your religion?
And do not the ministers of God say, that the Scriptures are a declaration,
which you call the word?
Do you not rob Christ of his title, and of his honour, and give it to the letter,
and show yourselves out of the doctrine of the ministers of God,
who call the Scriptures by the name of writings and treatises, and declarations;
and who said, Christ`'s name is called the Word of God?
Are not you here in the error you speak of, which is your common talk among you?
There was talk among some of you of your gospel-shining;
doth your gospel which you profess persecute?
Did ever any of them, that did possess it,
cast into prison and not suffer others to go to visit them?
Are you like Christians in this, or like heathens,
who set bounds and watches over the land,
that they should not pass to visit them that are in prison?
Was ever the like heard in any age?
Search and see, if you have not outstripped them all in your watches,
in your persecution, and imprisonments.
O! never talk, that we are a grief to them that are in the pure religion.

"`And whereas in your warrant we are represented as disaffected to government; I say,
the law, which is a terror to the evil-doer, we own,
the higher power to which the soul must be subject; but we deny the evil-doer,
the malicious man reigning, and the envious man seeking for his prey,
whose envy is against the innocent; who raiseth up the country against honest men,
and so becomes a trouble to the country, in raising them up to take the innocent;
but that we leave to the Lord to judge.
Your false accusations of heresy and blasphemy we deny.
You should have laid them down in particulars, that people might have seen them,
and not have slandered us behind our backs.
The law saith, the crime should be mentioned in the warrant.
Then for your saying,
'`we deny the godly ministers to be a true ministry of Christ,`' that is false; for we say,
that the godly ministers are the ministers of Christ.
But which of your ministers dare say, that they are truly godly?
And your charging us

with seducing many weak people, is false also; we seduce none; but you,
that deny the light, which lighteth every man that cometh into the world,
are seduced from the anointing which should teach you; and if ye would be taught by it,
ye would not need that any man should teach you.
But such as are taught by the anointing, which abideth in them, and deny man`'s teaching,
these ye call seducers, quite contrary to John`'s doctrine, 1 John ii.
You speak quite contrary to him; that which is truth, ye call seducing;
and that which he calls seducing, you call truth; read the latter part of the chapter.
Beware, I warn you all from the Lord God of glory, set not any bound against him;
stint him not; limit not the Holy One of Israel;
for the Lord is rising in power and great glory,
who will rule the nations with a rod of iron,
which to him are but as the drop of a bucket.
He that measures the waters in the hollow of his hand,
will dash the nations together as a potter`'s vessel.
And know, you that are found in this his day blaspheming his work,
that God hath brought forth, calling it blasphemy, fighting against it,
setting up your carnal weapons, making your bonds strong;
God will break asunder that which your carnal policy hath invented,
and which by your carnal weapons ye would uphold;
and make you to know there is a God in heaven, who carries his lambs in his arms,
which are come among wolves, and are ready to be torn in pieces in every place, yea,
in your steeple-houses; where people have appeared without reason, and natural affection.
Therefore all ye petty constables, sheriffs, and justices, take warning; take heed,
what ye do against the lambs of Christ; for Christ is come, and coming,
who will give to every one of you a reward according to your works,
you who have the letter, which speaks of Christ;
but now ye are persecuting that which the Scripture speaks of;
as your fruits make manifest.
Therefore every one, sheriffs, justices, constables, etc., consider what ye do possess,
and what a profession ye are now in,
that all these carnal weapons are now set up against the innocent, yea,
against the truth; which shows that ye have not the spiritual weapons,
and that ye want the counsel of Gamaliel, yea,
ye want the counsel of such a man among you, who said, '`Let the apostles alone;
if it be of God, it will stand; if it be not, it will come to nought.`'
But ye may see yourselves on the contrary, in the spirit of them that came with Judas,
with swords and staves from the chief priests against Christ; still it is against Christ,
where he is made manifest.
Paul (while Saul) went against him, though he professed a Christ that was to come;
and the Jews professed a Christ that was to come; yet Paul persecuted him,
where he was manifested in his saints.
So ye profess a Christ that is come, but persecute him where he is manifest.
You that have the letter, the high places, the synagogues, you persecute him,
where he is made manifest in his saints, as the Jews did.
They who were in the letter, out of the life,
persecuted them that were in the life of that which they profess in the letter;
so now do you persecute them that are in the life, and are yourselves strangers to it,
as your fruits make appear.
You have numbered the people of God amongst transgressors;
but have you imprisoned any of the rogues and transgressors you speak of?
You have imprisoned the innocent, and let the others go free.`"

[.signed-section-signature]
G+++.+++ F.

--

When I had sent abroad the foregoing,
so great a sense came upon me of the veil of darkness that was
over the priests and professors of Christianity,
that I was moved to give forth the following, as an awakening warning to them:--

[.small-break]
'''

[.embedded-content-document.letter]
--

"`Blindness hath happened to the professed Christians of the
letter now-a-days,-as blindness happened to the Jews,
who professed the letter, but owned not the life which the letter speaks of;
as the Christians now, to whom this blindness hath happened, who profess the Scripture,
but own not the life, which the Scripture speaks of.
For against the life the Jews stood, who professed the letter of the Scripture,
but they were blind; they gathered counsel against the life;
they were in an uproar when the babe was born in Bethlehem,
Herod and all the chief priests.
And Herod sought to destroy all the young children in Bethlehem, yet missed the babe;
Herod, that fox, though he put John to death.
You may here see how the literal professors stood up, not for the truth,
but quite against it.
Furthermore, the chief priests consulted together how they might take Jesus by subtilty,
and put him to death; mark, by their subtilty.
The professors of a Christ that was to come, preached of a Messiah, of a Christ,
of a Saviour; but denied the life, when he was made manifest.
The chief priests, when they were assembled with the ciders, and had taken counsel,
gave large money unto the soldiers, to declare that '`his disciples came by night,
and stole him away.`'
Likewise in the day, when the children of Israel were in Egypt,
and they with their children began to spread and multiply, '`Come,`' said the Egyptians,
'`let us deal wisely with them to afflict them, and tax them;`' which held,
until the Lord overthrew their oppressors,
and brought out his seed by his mighty power from under the oppressor,
and exalted his Son above all, though the heathen raged,
and the people imagined vain things.
He made his power known,
that all might see that there was no God upon the earth but himself.
This power now hath brought forth the work of the Lord!
Many who are turned to Christ, the light, have received the power of God,
and are thereby become the sons of God.
Now this birth, that is born of God,
are all the powers of the world joined together to crucify;
to put to death those Jews in the Spirit,
as they put Christ to death in the flesh formerly.
This is the birth that all the wicked world is enraged against;
against this they set their watches,--this birth,
brought forth by the Mighty God of Jacob, who rides upon the high places of the earth.
This is the birth that the professed Christians
without the life in our days rage against,
and lay out all their wisdom about.
Are not the chief priests and wise men of the earth
consulting together how they may destroy this birth?
Is not this the birth, that is banished out of your hearts,
you that profess the Scripture, and are talkers of it,
but do not own the light and life which the Scripture speaks of, as the Jews would not;
and so you will not have Christ to reign over you, as they would not?
Do you not hale out of your synagogues, and before magistrates?
Do you not herein fulfil Christ`'s words, who said to his disciples,
They should be haled out of the synagogues, and before rulers?
Do you not persecute them from city to city?
Do you not almost fill your prisons with them?
And now set your watches, that none may visit them, whom ye have put into prison?
Is not this an unchristian spirit?
How can you for shame say you are upholders of truth?
Or how can you for shame say that truth hath been professed among you?
Yet we grant that you have talked of it.
And how can you for shame say the gospel shines among you,
when you will not own the life of it; when you call it error, and the evil seed?
Yea, the very truth, the very life of truth ye have blasphemed against now,
as the Jews did against Christ, calling him a devil; you now call it error,
and the evil seed, and stand up against it, and turn the sword against it.
As in the days of the Jews, it was the Jews outward in the flesh,
not the Jews in the Spirit, who turned the sword against Christ;
so in these days it is those Christians who profess the Scripture,
but are out of the Life of it.
And is it not a shame to all the ministers of the Gospel (as they are called),
that they can find no better way to maintain
that which they call the truth and their Gospel,
than by carnal weapons, stocks and prisons, whips, watches, and wards,
and powers of the earth?
Were these the apostles`' weapons?
Carnal watches and wards, stocks and prisons, and haling out of the synagogues,
when they came to speak?
Judge`' yourselves, what an anti-Christian spirit you have.
Never talk of defending truth with that which is against truth.
For are you not setting up the rabble of the world against it?
Do they not join with you with swords and staves against it?
Is this the life of Christians?
Is not this the life of error, and of the evil seedsman?
Surely, ye would find work enough, if ye were in the fear of the Lord,
to turn your swords against profaneness,
the oaths and wickedness that are in your streets and highways.
How do they ring like Sodom, and give a sound like Gomorrah!
But these are become a prey in this your age, that reprove in your gates sin, wickedness,
and profaneness; they are become your by-word.
Against them your councils are gathered, them you cast into prison,
and hale out of your synagogues;
and cast them likewise into prison that write and speak against it,
and set your guards to stop and hinder any from visiting them whom you cast into prison,
and give them the names of vagabonds and wanderers.
Was ever the like heard, in the days of the heathen,
against the apostles who witnessed the gospel?
Did they set guards and watches in every town, in every city, to take the disciples,
the brethren, the believers, that heard that the apostles were cast into prison,
and came to see what they wanted?
Show ye not as much rage and fury now in your age, as was in those in that age?
And how can you talk of the gospel, and of defending the gospel,
when you are setting guards and watches against it,
and are defending that which stands against it;
and the lambs of Christ are almost torn to pieces amongst you, who are like wolves?
for the Lord hath now sent his lambs amongst wolves.
Have not you professed the words of Christ, of the prophets and apostles,
as the Jews had long professed the Scriptures, the words of Moses and of the prophets,
that prophesied of Christ that was to come, and stood against him when he was come?
as you do in this day of his reign, in this day of his glorious gospel,
who are persecuting the messengers of it, imprisoning them,
persecuting them in your streets and highways;
and are setting up your watches against them,
who bring you the glad tidings of peace to your souls,
whose feet are beautiful on the top of the mountains; mark, on the top of the mountains,
that against which the mountains rage and swell.
But God will make them melt; the sun is risen, which will make them melt.
God will cleave the rocks and mountains asunder, and make the hills to bow perpetually;
for his Son he will exalt, and his glory he will give to Him and not to another.`"

"`Therefore be awakened, ye rulers of the earth, and take counsel of the Lord;
take not counsel together against him.
Make not your bonds strong; set not yourselves in battle against him,
for ye will be found but as briars and thorns before him, which the fire shall consume.
Therefore be awakened, all ye talkers of the Scripture,
that gather yourselves together by your multitudes and meetings,
and have had your teachers; but not having the Spirit that gave forth the Scriptures,
the Lord God of glory, the Father of spirits, will scatter you.
All your bonds will not hold you together, who are out of the Spirit,
which is the bond of peace.
The thrashing instrument is gone forth, which will beat the hills to pieces.
Sion is risen to thrash.
Out of the holy mountain is the trumpet sounded.
Stand not up against the Lord; for all nations are with the Lord as the drop of a bucket.
He that measures the waters in the hollow of his hand, and weighs the earth in scales,
the Lord of hosts is his name,
who is now risen and rising to plead the cause of the innocent; who is exalting his Son,
and bringing his sheep to him.
Now are they seen and known that feed upon wind, that are lifted up,
given up to believe lies; who report, and say, '`Report, and we will report it.`'
Now are they seen who have a form of godliness, but deny the power; so Christ is denied,
the power itself is denied; for Christ is the power of God.
And the power being denied by you, that have a form of godliness,
that have the words of the Scriptures, the gospel is denied;
for the gospel is the power of God.
Thus it is among you, that have the knowledge and wisdom that is sensual, earthly,
and devilish.
Doth it not appear so?
Let your jails and watches witness your fruits in every town.
Your wisdom is earthly, sensual, and devilish; you have a knowledge and wisdom,
but not that which is from above; for that is pure and gentle, so is not your knowledge;
but to know Christ is life eternal.
Now your fruits have manifested that you are not of this; and so out of the power of God,
which is the cross of Christ; for you are found in the world, out of the power of God,
out of the cross of Christ, persecuting.
So that which doth persecute, and send forth writings and decrees to stop all,
and take up all, and set watches, and prepare bonds to stint the Lord;
to imprison and persecute, and suffer none to go to visit them;
this shows you are not Christians, but stand against a Christian`'s life,
which brings to love enemies.
Where is your heaping up coals of fire; your love to your enemies;
who are thus persecuting your friends?
'`He came to his own,
and his own received him not;`' here is a turning of the sword against the just.
Do you show here a Christian`'s life, or yourselves Christians,
who are filling your jails with Christians in Spirit,
you that are in the letter (in shadows),
as the Jews in the letter put the Jews in the Spirit into prison?
Is not this the fruit in our days of the Christians in the letter,
to put the Christians in the Spirit into prison?
Doth not this show that your decrees, which you have sent forth, proceed from death,
who thus act against the life, and them that are in it;
which the Scriptures were given forth from?
Is it not here as it was with Saul, when he went to persecute, to hale to prison,
and bind all that he could find calling upon that name, who were Christians in the life,
the Spirit, such as you are now persecuting, because they are in the life,
though you profess their words?
Are not your decrees gone forth from the same spirit of envy,
against the same Spirit of Christ they were in?
Is it not manifest to all that fear God,
and to the sober-minded and honest-hearted people that see your practices, your decrees,
your letters, to stop, to molest, to hinder,
to imprison them that are moved of the Lord to do his will,
or to go to visit prisoners whom you have imprisoned?
Doth this show you to have a spirit like Paul, yea or nay?
or are you not quite contrary, like unto them that persecuted Paul?
The day hath declared it.
To that of God in you all I speak,
which shall witness it at the last day,--the day of judgment.
Persecution was blind in all ages; and madness and folly led it:
yet persecution got always a form or pretence of godliness,--a talk of religion,
as in the days of Moses, of Jeremiah, of Christ, and of the apostles.
'`Come,`' saith the council, '`let us crush them while they are young,
they have almost overspread the nation in every corner.`'
This is as much as to say, '`Let us put this birth to death,
as Pharaoh and Herod did the children.`'
But the Lord caused his truth the more to spread.
For you may read, what numbers came out of Egypt! and what multitudes followed Christ!
Therefore, with consideration read these lines, and not with fury.
Let not foolishness appear; but consider in humility the paths you go in,
what spirit you are of, and what the end of your conversation is;
for in love to your souls I write,
that in the day of your visitation you may consider it.

"`From him who loveth righteousness, and the establishing of it, and truth, peace,
and faith,
which is by Christ Jesus (Mercy and peace be multiplied
among such!) but a witness against all hypocrites,
and all who have a profession, but live out of the possession,
in an hypocritical religion, in the lusts and fashions of the world,
having a form of godliness, but standing against the power with might and main,
sword and staff.
Which things declare your conversation and practices to be out of Christ`'s life,
against the gospel practice, and contrary to the manner and order of the saints.`"

[.signed-section-signature]
G+++.+++ F.

--

We continued in prison till the next assize; before which time divers Friends,
both men and women, were sent to prison, that had been taken up by the watches.
When the assize came on, several of these were called before the judge, and indicted;
and though the jailer brought them into court, yet they indicted them,
that they came in "`by force of arms and in an hostile manner;`"
and the judge fined them,
because they would not put off their hats.
But we were not called before the judges any more.

Great work we had, and service for the Lord, both between the assizes and after,
amongst professors and people of all sorts;
for many came to see us and to reason with us.
Elizabeth Trelawny of Plymouth (who was the daughter of a baronet)
being convinced (as was formerly mentioned),
the priests and professors, and some great persons of her kindred were exasperated,
and wrote letters to her.
She being a wise and tender woman, and fearing to give them any advantage,
sent their letters to me; and I answered them, and returned them to her again,
for her to answer.
Which she did: till growing in the power, and Spirit, and wisdom of God,
she came herself to be able to answer the wisest priest and professor of them all;
and had a dominion over them in the truth, through the power of the Lord,
by which she was kept faithful to her death.

While I was in prison here, the Baptists and Fifth-monarchy-men prophesied,
"`That this year Christ should come, and reign upon earth a thousand years.`"
And they looked upon this reign to be outward;
when he was come inwardly in the hearts of his people, to reign and rule there,
and these professors would not thus receive him.
So they failed in their prophecy and expectation, and had not the possession of him.
But Christ is come, and doth dwell in the hearts of his people, and reign there.
Thousands, at the door of whose hearts he hath been knocking, have opened to him;
and he is come in, and doth sup with them and they with him;
the heavenly supper with the heavenly and spiritual man.
So many of these Baptist and Monarchy-people turned the
greatest enemies to the professors of Christ;
but he reigns in the hearts of his saints over all their envy.

At the assize divers justices came to us and were pretty civil,
and reasoned of the things of God soberly, expressing a pity towards us.
Captain Fox, governor of Pendennis Castle, came and looked me in the face,
and said not a word; but went to his company, and told them,
"`he never saw a simpler man in his life.`"
I called after him, and said, "`Stay, we will see who is the simpler man.`"
But he went his way; a light chaffy man.

Thomas Lower^
footnote:[Thomas Lower was son-in-law to Judge Fell, having married his daughter Mary.]
also came to visit us, and offered us money, which we refused;
accepting his love nevertheless.
He asked us many questions concerning our denying the Scriptures to be the word of God;
and concerning the sacraments, and such like; to all which he received satisfaction.
I spoke particularly to him, and he afterwards said,
"`my words were as a flash of lightning, they ran so through him.`"
He said, "`he never met with such men in his life;
for they knew the thoughts of his heart,
and were as the wise master-builders of the assemblies,
that fastened their words like nails.`"
He came to be convinced of the truth, and remains a Friend to this day.
When he came home to his aunt Hambley`'s, where he then lived,
and made report to her concerning us, she, with her sister Grace Billing,
hearing the report of truth, came to visit us in prison, and was convinced also.
Great sufferings and spoiling of goods both he
and his aunt have undergone for the truth`'s sake.

[.offset]
About this time I was moved to give forth the following
exhortation to Friends in the ministry:--

[.embedded-content-document.epistle]
--

[.salutation]
"`Friends,

"`In the power of life and wisdom, and dread of the Lord God of life, and heaven,
and earth, dwell; that in the wisdom of God over all ye may be preserved,
and be a terror to all the adversaries of God, and a dread,
answering that of God in them all, spreading the truth, awakening the witness,
confounding deceit, gathering out of transgression into the life,
the covenant of light and peace with God.
Let all nations hear the sound by word or writing.
Spare no place, spare no tongue, nor pen; but be obedient to the Lord God;
go through the work; be valiant for the truth upon earth;
and tread and trample upon all that is contrary.
Ye have the power, do not abuse it; and strength and presence of the Lord, eye it,
and the wisdom; that with it you may all be ordered to the glory of the Lord God.
Keep in the dominion; keep in the power over all deceit;
tread over them in that which lets you see to the world`'s end,
and the uttermost parts of the earth.
Reign and rule with Christ, whose sceptre and throne are now set up,
whose dominion is over all to the ends of the earth;
whose dominion is an everlasting dominion; whose throne is an everlasting throne;
whose kingdom is an everlasting kingdom; and whose power is above all powers.
Therefore this is the word of the Lord God to you all: keep in the wisdom of God,
that spreads over all the earth; the wisdom of the creation, that is pure, from above,
not destructive.
For now shall salvation go out of Zion, to judge the mount of Esau:
and now shall the law go forth from Jerusalem, to answer the principle of God in all;
to hew down all inventors and inventions.
For all the princes of the earth are but as air to the power of the Lord God,
which you are in, and have tasted of: therefore live in it;
this is the word of the Lord God to you all, do not abuse it; keep down and low;
and take heed of false joys, that will change.

"`Bring all into the worship of God.
Plough up the fallow ground.
Thrash and get out the corn; that the seed, the wheat, may be gathered into the barn;
that to the beginning all people may come--to Christ, who was, before the world was made.
For the chaff is come upon the wheat by transgression; he that treads it out,
is out of transgression, and fathoms transgression;
puts a difference between the precious and the vile;
and can pick out the wheat from the tares, and gather into the garner:
so brings to the lively hope, the immortal soul into God, out of which it came.
None worship God but who come to the principle of God, which they have transgressed.
None are ploughed up but he who comes to the principle of God in him,
that he hath transgressed.
Then he doth service to God; then is the planting and the watering;
and the increase from God cometh.
So the ministers of the Spirit must minister to the Spirit that is in prison,
which hath been in captivity in every one; that with the Spirit of Christ,
people may be led out of captivity up to God, the Father of Spirits, do service to him,
and have unity with him, with the Scriptures, and one with another.
This is the word of the Lord God to you all,
and a charge to you all in the presence of the living God; be patterns,
be examples in all your countries, places, islands, nations, wherever you come;
that your carriage and life may preach among all sorts of people, and to them:
then you will come to walk cheerfully over the world, answering that of God in every one;
whereby in them ye may be a blessing, and make the witness of God in them to bless you:
then to the Lord God you will be a sweet savour, and a blessing.

"`Spare no deceit.
Lay the sword upon it; go over it: keep yourselves clear of the blood of all men,
either by word, or writing; and keep your, selves clean,
that you may stand in your throne, and every one have his lot,
and stand in the lot in the Ancient of Days.
The blessing of the Lord be with you,
and keep you over all the idolatrous worships and worshippers.
Let them know the living God; for teachings, churches, worships,
set up by man`'s earthly understanding, knowledge, and will,
must be thrown down by the power of the Lord God.
All this must be overthrown by that winch gave forth Scripture; and who are in that,
reign over it all: that is the word of the Lord God to you all.
In that is God worshipped, that brings to declare his will;
and brings to the church in God, the ground and pillar of truth:
for now has the mighty day of the Lord appeared,
and the arrows of the Almighty are gone forth,
which shall stick in the hearts of the wicked.
Now will I arise, saith the Lord God Almighty, to trample and thunder down deceit,
which hath long reigned, and stained the earth:
now will I have my glory out of every one.
The Lord God Almighty over all in his strength and power keep you, to his glory,
that you may come to answer that of God in every one.
Proclaim the mighty day of the Lord of fire and sword,
who will be worshipped in spirit and in truth;
and keep in the life and power of the Lord God,
that the inhabitants of the earth may tremble before you;
that the Lord`'s power and majesty may be admired among the hypocrites and heathens,
and ye in the wisdom, dread, life, terror, and dominion preserved to his glory:
that nothing may rule or reign, but power and life itself;
and in the wisdom of God ye may be preserved in it.
This is the word of the Lord God to you all.
The call is now out of transgression; the Spirit bids, '`come.`'
The call is now from all false worships and gods, and from all inventions and dead works,
to serve the living God.
The call is to repentance, to amendment of life,
whereby righteousness may be brought forth; which shall go throughout the earth.
Therefore ye that are chosen and faithful, who are with the Lamb,
go through your work faithfully, and in the strength and power of the Lord:
and be obedient to the power;
for that will save you out of the hands of unreasonable men,
and preserve you over the world to himself.
Hereby you may live in the kingdom, that stands in power, which hath no end;
where glory and life is.`"

[.signed-section-signature]
G+++.+++ F.

--

After the assizes, the sheriff, with some soldiers, came to guard a woman to execution,
that was sentenced to die; and we had much discourse with them.
One of them wickedly said,
that "`Christ was as passionate a man as any that lived upon the earth;`"
for which we rebuked him.
Another time we asked the jailer what doings there were at the sessions; and he said,
"`Small matters; only about thirty for bastardy.`"
We thought it very strange,
that they who professed themselves Christians should make small matters of such things.
But this jailer was very bad himself; I often admonished him to sobriety;
but he abused people that came to visit us.
Edward Pyot had a cheese sent him from Bristol by his wife;
and the jailer took it from him, and carried it to the mayor,
to search it for treasonable letters, as he said;
and though they found no treason in the cheese, they kept it from us.
This jailer might have been rich if he had carried himself civilly;
but he sought his own ruin; which soon after came upon him;
for the next year he was turned out of his place,
and for some wickedness cast into the jail himself; and there begged of our Friends.
And for some unruliness in his conduct, he was, by the succeeding jailer,
put into Doomsdale, locked in irons, and beaten;
and bid to "`remember how he had abused those good men, whom he had wickedly,
without any cause, cast into that nasty dungeon;`" and told,
"`that now he deservedly should suffer for his wickedness;
and the same measure he had meted to others, should be meted out to himself.`"
He became very poor, and died in prison; and his wife and family came to misery.

While I was in prison in Launceston, a friend went to Oliver Cromwell,
and offered himself, body for body, to lie in Doomsdale in my stead;
if he would take him, and let me have liberty.
Which thing so struck him, that he said to his great men and council,
"`Which of you would do so much for me if I were in the same condition?`"
And though he did not accept of the Friend`'s offer, but said,
"`he could not do it, for that it was contrary to law;`"
yet the truth thereby came mightily over him.
A good while after this he sent down Major-General Desborough,
pretending to set us at liberty.
When he came, he offered us our liberty, if we would say,
"`we would go home, and preach no more;`" but we could not promise him.
Then he urged, that we should promise
"`to go home, if the Lord permitted;`"
whereupon Edward Pyot wrote him the following letter:--

[.embedded-content-document.letter]
--

[.blurb]
=== "`To Major-General Desborough.

[.salutation]
"`Friend,

"`Though much might be said as to the liberty of Englishmen to
travel in any part of the nation of England,
it being as the Englishman`'s house by the law, and he to be protected in any part of it;
and if he transgress the law, the penalty upon the transgressor is to be inflicted.
And as to liberty of conscience, which is a natural right, and a fundamental;
the exercise of it, by those who profess faith in God by Jesus Christ,
is to be protected; as by the instrument of government appears,
though they differ in doctrine, worship, and discipline;
provided the liberty extend not to Popery, to prelacy, nor to licentiousness.
Where these rights, which are the price of much blood and treasure in the late wars,
are denied us, our liberty is infringed.
Yet in the power of God over all, by which all are to be ruled, are we, and in it dwell,
and by it alone are guided to do the will of God; whose will is free; and we,
in the freedom of his will, walk by the power, either as it commands or permits,
without any condition or enforcement thereunto by men;
but as the power moves either by command or permission.
And although we cannot covenant or condition to go forth of these parts,
or to do this or that thing,
if the Lord permit for that were to do the will of man by God`'s permission),
yet it is probable we may pass forth from these parts in the liberty of the will of God,
as we may be severally moved, guided by the pure power, and not of necessity.
We, who were first committed, were passing homewards when we were apprehended; and,
as far as I know, we might pass, if the prison doors were commanded to be opened,
and we freed of our bonds.
Should we stay, if the Lord commands us to go; or should we go,
if the Lord commands us to stay; or having no command to stay,
but being permitted to pass from hence, the pure power moving thereto, and yet we stay;
or go, when as before commanded to stay; we should then be wanderers indeed;
for such are wanderers, who wander out from the will and power of God, abroad, at large,
in their own wills and earthly minds.
And so, in the fear of the Lord God, well weigh and consider,
with the just weight and just balance,
that justice thou mayest do to the just and innocent in prison.`"

[.signed-section-signature]
Edward Pyot.

--

Some time having elapsed after the foregoing was delivered him,
and he not giving any order for our discharge, I also wrote to him, as follows:--

[.embedded-content-document.letter]
--

[.blurb]
=== "`To Major-General Besborough.

[.salutation]
"`Friend,

"`We who are in the power of God, the ruler and upholder of all things,
who know and dwell in his power, to it we must be obedient;
which brings us to stand out of all men`'s wills, unlimited.
To say, '`we will, if the Lord permit,`' in a case of buying and selling to get gain,
if the intent be so to do, may be done;
but we standing in the power of God to do his will, and to stand out of man`'s will,
if man propose, '`we shall have our liberty if we will say we will go to our outward home,
if the Lord permit,
or if it be the will of God;`' and because we cannot say these words in this case,
shall not have our liberty, when we know that the will of God is,
we shall '`go to speak at some other place;`' here we cannot say these words truly.
For to say, '`we will go to our outward habitation,
if it be according to the will of God,`' when we know the will of God is otherwise,
we cannot speak so truly and clearly.
Neither can any man say so to him, that requires it of him; who stands in the power,
and knows the power of God to lead him, according to God`'s will,
when it leads him to another place than his outward home.
But the Son of God, who came to do, and did, the will of God,
had no place whereon to lay his head; and the apostles,
and many of the followers of Christ, had no certain dwelling place.
Now, if these should have been restrained, because they could not say,
they would go to their outward homes, if it were the will of God,
when they knew it was the will of God they should not;
and they could not do the will of God in doing so;
and therefore could not speak those words to satisfy man`'s mind and will,
would not such restraint have been evil?
Abraham could not do the will of God, but in going from his native country;
and who are of faith are of Abraham, of whom Christ came according to the flesh.
Now, if you allege, '`this is to let all loose, and at liberty to idleness,`' I say, no;
such as are in the power of God, who do the will of God, come to receive his wisdom,
by which all his creatures, were created; and by which they are used to his glory.
This I shall say; whoever are moved by the Lord God of glory and power,
to go to their outward habitations, such of us may go to our outward homes,
and there be diligent in serving the Lord,
that they may be a blessing from the Lord God in their generation;
diligently serving him in life and doctrine, in manners, in conversation, in all things.
And who are moved of the Lord to go to any other place, we standing in his will,
and being moved by his power, which comprehends all things, and is not to be limited,
we shall do his will, as we are commanded to do.
So the Lord God open your understandings, that you may see this great power of the Lord,
which he is now manifesting among his children in this his day;
that ye may not withstand it in our Friends, that are come into the power of God,
and to God, and know him by whom the world was made;
by whom all things were created that were created; and there was not anything made,
but what was made for him, and to him, and by him; who is the power of God,
and doth enlighten every man that Cometh into the world.
Friends being come to this light, which cometh from Christ,
and having received power from him, by whom all things were created,
who hath all power in heaven and earth given to him, who is the wisdom of God,
we have received wisdom and power from him;
by which the Lord doth give us to know how to use and order the
creatures to the glory of him who is the Creator of all things.
Friends here are taught of the Lord to be diligent, serving him;
and who come into the life, the Scriptures were given forth from,
are given up to serve the Lord; and of this I have in all your consciences a witness.
So, if thou open the prison door, we shall not stay there.
If thou send a liberate, and set us free, we shall not stay in prison;
for Israel is to go out free, whose freedom is purchased by the power of God,
and the blood of Jesus.
But who goeth out of the power of God, loseth his freedom.

[.signed-section-signature]
"`George Fox,`"

[.signed-section-context-close]
"`and the rest who are sufferers for the truth in Launceston jail.`"

[.signed-section-context-close]
"`The 13th of the 6th Month, 1656.`"

--

After this Major Desborough came to the Castle-Green,
and played at bowls with the justices and others.
Several Friends were moved to go, and admonish them not to spend their time so vainly;
desiring them to consider, that "`though they professed themselves to be Christians,
yet they gave themselves up to their pleasures,
and kept the servants of God meanwhile in prison;`" and telling them,
"`the Lord would plead with them, and visit them for such things.`"
But notwithstanding what was written or said to him, he went away, and left us in prison.
We understood afterwards, that he left the business to Colonel Bennet,
who had the command of the jail.
For sometime after Bennet would have set us at liberty,
if we would have paid his jailer`'s fees.
But we told him, "`we could give the jailer no fees, for we were innocent sufferers;
and how could they expect fees of us, who had suffered so long wrongfully?`"
After a while Colonel Bennet coming to town, sent for us to an inn,
and insisted again upon fees, which we refused.
At last the power of the Lord came so over him,
that he freely set us at liberty on the 13th day of the seventh month, 1656.
We had been prisoners nine weeks at the first assize, called the Lent-assize,
which was in the spring of the year.
