== Chapter X.

[.chapter-synopsis]
* 1656-1657
* Address to those who are given to pleasures and wantonness
* to the bowlers in the Castle-Green at Launceston
* George Fox visits Friends imprisoned at Exeter, amongst whom is James Nayler, who has apostatized, but afterwards returned into the Truth
* at a meeting in the orchard at Bristol about 10,000 persons are present
* Paul Gwin, a rude Baptist, creates a disturbance, but is reproved and silenced
* meeting of two or three thousand persons at N. Crips`'s
* Justice Stooks prevents the magistrates from apprehending George Fox
* speaks to the Protector at Hyde-Park, who invites him to his house
* accordingly goes; to Whitehall, and speaks to the Protector about Friends`' sufferings
* travels through most parts of the nation after his liberation from Launceston jail
* this year, 1656, there were seldom fewer than one thousand Friends in prison
* to Friends, on the schism of J. Nayler
* to Friends, to keep up their meetings
* on judging the ministry, etc
* an answer to a high-flown professor
* to professors, priests, and teachers, on immediate revelation and universal grace, etc., etc.
* at Cardiff, George Fox sends word to some who had run out that "`the day of their visitation was over`"
* at Brecknock, his companion, John-ap-John, preaches in the streets
* at night, there is a great uproar, like that of Diana`'s craftsmen
* at William Gandy`'s has a large meeting of two or three thousand persons
* Cromwell proclaims a fast for rain, and is told by George Fox that the drought was a sign of their barrenness
* concerning the true fast and the false
* preaches three hours at a great meeting in Radnorshire, and many are convinced
* their horses are twice robbed of their oats
* from a high hill sounds the day of the Lord, and foretells where God would raise up a people to himself, which came to pass
* travels through every county in Wales, where there is a brave people, who sit under Christ`'s teaching
* has a large meeting on the top of a lull near Liverpool
* at Manchester is taken into custody, but soon released.

Observing, while I was a prisoner at Launceston,
how much the people (especially they who are called the
gentry) were addicted to pleasures and vain recreations,
I was moved, before I left the place, to give forth several papers as a warning to them,
and all that so misspend their time.
One of which was thus directed:--

[.embedded-content-document.paper]
--

[.blurb]
=== "`This is to go abroad among them who are given, to pleasure and wantonness.

"`The sins of Sodom and Gomorrah were pride, fulness of bread, and abundance of idleness.
Their filthy conversation vexed the righteous soul of just Lot day by day,
and they would not take warning: on whom God therefore sent fire,
and turned them into ashes.
And in spiritual Sodom and Egypt was our Lord Jesus Christ crucified; and it is written,
'`The people sat down to eat and to drink, and rose up to play;
with whom God was not well pleased; and there fell three and twenty thousand in one day.`'
These the apostle commanded the saints they should not follow;
for these things happened to them for examples, and are written for our admonition,
God spared not the old world; but reserving Noah,
a preacher of righteousness brought the flood upon the world of the ungodly,
making them an example to all that after should lire ungodly.
Mark, ye ungodly ones, who are as natural brute beasts,
who speak great swelling words of vanity, alluring through the lusts of the flesh,
through much wantonness, as they that count it pleasure to riot in the day-time,
sporting yourselves with your own deceivings;
ye shall receive the reward of unrighteousness.
Ye are as dogs and swine turned to the vomit, and wallowing in the mire,
speaking evil of things that ye know not; and unless ye repent,
ye shall utterly perish in your own corruptions.
Ye have lived in pleasure on the earth, and been wanton;
ye have nourished your hearts as in a day of slaughter:
ye have condemned and killed the '`just, and he doth not resist you.
Go to, weep and howl, for the misery that is coming upon you.
She that liveth in pleasures, is dead while she liveth.
God condemned the cities of Sodom and Gomorrah,
making them an example to all those that after should live ungodly, in the wicked,
filthy conversation: mark, here is your example.
Hear this, ye that are given to pleasures, and read your examples.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
Another paper,
upon my taking notice of the bowlers that came to sport themselves in the Castle-Green,
was as follows:--

[.embedded-content-document.paper]
--

"`The word of the Lord to all you vain and idle-minded people, who are lovers of sports,
pleasures, foolish exercises, and recreations, as you call them; consider of your ways,
what it is you are doing.
Was this the end of your creation?
Did God make all things for you, and you to serve your lusts and pleasures?
Did not the Lord make all things for you, and you for himself,
to fear and worship him in spirit and in truth, in righteousness and true holiness?
But where is your service of God, so long as your hearts run after lusts and pleasures?
Ye cannot serve God, and the foolish pleasures of the world, as bowling, drinking,
hunting, hawking, and the like: if these have your hearts, God will not have your lips:
consider, for it is true.
Therefore from the Lord must you all witness woe and misery, tribulation and wrath,
who continue in the love and practice of your vain sports, lusts, and pleasures.
Now is the day, when all everywhere are exhorted to repentance.
O foolish people,
wicked and slow of heart to believe the threatenings of
the great Jehovah against the wicked!
What will ye do in the day of the Lord`'s fierce wrath,
that makes haste to come upon the world of ungodly men!
What good have your foolish sports and delights done you now they are past?
Or what good will they do you, when the Lord calls for your souls?
Therefore all now awake from sleep, and see where you are:
and let the light of Jesus Christ, that shines in every one of your consciences,
search you thoroughly; and it will let you clearly see, for all your profession of God,
Christ, and the Scriptures, you are ignorant of them, and enemies to them all,
and your own souls also: and being found living in pleasures,
you are dead while you live.
Therefore doth the Lord by many messengers forewarn you,
and call you to repentance and deep humiliation,
that you may forsake the evil of your doings, own this day of your visitation,
and while you have time, prize it;
lest the things which belong to your peace be hid from your eyes,
for your disobedience and rebellion against the Holy One.
And then had it been good that you never had been born.
Repent, for the kingdom of heaven is at hand: again I say, repent!`"

[.signed-section-context-close]
Given forth in Launceston Jail, in Cornwall.

[.signed-section-context-close]
To the Bowlers in the Green.

--

Being released from our imprisonment we got horses and rode towards Humphrey Lower`'s,
and met him on the road.
He told us, "`he was much troubled in his mind concerning us, and could not rest at home,
but was going to Colonel Bennet to seek our liberty.`"
When we told him, "`we were set at liberty,
and were going to his house,`" he was exceedingly glad.
To his house we went, and had a fine precious meeting; many were convinced,
and turned by the Spirit of the Lord to Christ`'s teaching.

From his house we went to Loveday Hambley`'s, where we also had a fine large meeting.
The Lord`'s power was over all; many were convinced there also,
and turned to the Lord Jesus Christ, their teacher.

After we had tarried there two or three days, we came to Thomas Mounce`'s,
where we had a general meeting for the whole county; which, being very large,
was held in his orchard.
Friends from Plymouth were there, and from many places.
The Lord`'s power was over all;
and a great convincement there was in many parts of the county.
Their watches were down, and all was plain and open; for the Lord had let me see,
before I was set at liberty, that he would make all the country plain before us.
Thomas and Ann Curtis, with an alderman of Reading, who was convinced,
had come to Launceston to see us while I was a prisoner: and when Ann,
and the other man returned, Thomas Curtis stayed behind in Cornwall,
and had good service for the Lord at that time.^
footnote:[Thomas Curtis became a faithful minister, and sufferer for Christ`'s sake.
In 1666, he is mentioned in a letter from Alexander Parker to Margaret Fell as
being a prisoner with thirty-two or thirty-three others.
His wife, Ann Curtis, was a daughter of a sheriff of Bristol.
See a letter of T. Curtis to George Fox, in _Letters of Early Friends,_ p. 240.]

From Thomas Mounce`'s we passed to Launceston again,
and visited that little remnant of Friends that
had been raised up there while we were in prison;
and the Lord`'s plants grew finely, and were established on Christ,
their rock and foundation.
As we were going out of town again,
the constable of Launceston came running to us with the
cheese that had been taken from Edward Pyot;
which they had kept from us all this while, and were tormented with it.
But being now set at liberty, we would not receive it.

From Launceston we came to Okington +++[+++Oakhampton], and lodged at an inn,
which the mayor of the town kept.
He had stopped and taken up several Friends, but was very civil to us;
and was convinced in his judgment.

From thence we came to Exeter, where many Friends were in prison;
and amongst the rest James Nayler.
For a little before we were set at liberty, James had run out into imaginations,
and a company with him, which raised up a great darkness in the nation.^
footnote:[James Nayler was a monument of human frailty.
His gift in the ministry was eminent; his experience in divine things truly great.
He fell through unwatchfulness,
but was restored through deep sufferings and unfeigned repentance.
His own writings are the most clear and lively
description of the various dispensations he underwent;
some of them deserve to be transmitted to the latest posterity.
His address to his brethren bespeaks the real repentance of his heart; in that he says,
"`My heart is broken this day for the offence I have
occasioned to God`'s truth and people,--I beseech you,
forgive wherein I evilly requited your love in that day.
God knows my sorrow for it!`" etc.
A few hours before his death,
he spoke in the presence of several witnesses the following remarkable words:--
{footnote-paragraph-split}
There is a spirit which I feel,
that delights to do no evil, nor to revenge any wrong;
but delights to endure all things,
in hope to enjoy its own in the end.
Its hope is to outlive all wrath and contention,
and to weary out all exaltation and cruelty,
or whatever is of a nature contrary to itself.
It sees to the end of all temptations; as it bears no evil in itself,
so it conceives none in thought to any other.
If it be betrayed, it bears it;
for its ground and spring is the mercy and forgiveness of God.
Its crown is meekness; its life is everlasting love unfeigned.
It takes its kingdom with entreaty, and not with contention,
and keeps it by lowliness of mind.
In God alone it can rejoice, though none else regard it, or can own its life.
It is conceived in sorrow, and brought forth without any to pity it;
nor doth it murmur at grief and oppression.
It never rejoiceth, but through sufferings; for with the world`'s joy it is murdered.
I found it alone; being forsaken.
I have fellowship therein, with those who lived in dens and desolate places in the earth;
who through death obtained this resurrection, and eternal, holy life!`"
{footnote-paragraph-split}
Such was the end of James Nayler; who,
in his forty-fourth year, "`chastened, but not killed--cast down,
but not destroyed`"--through much tribulation, entered, we may humbly hope,
"`into the kingdom of God.`"--(For full particulars,
see his Life by Joseph Gurney Bevan.)]
He came to Bristol, and made a disturbance there:
and from thence he was coming to Launceston to see me; but was stopped by the way,
and imprisoned at Exeter; as were also several others; one of whom, an honest tender man,
died in prison there, whose blood lieth on the heads of his persecutors.

The night we came to Exeter, I spoke with James Nayler; for I saw he was out and wrong;
and so was his company.
Next day, being First-day, we went to visit the prisoners,
and had a meeting with them in the prison;
but James Nayler and some of them could not stay the meeting.
There came a corporal of horse into the meeting, and was convinced,
and remained a very good Friend.
The next day I spoke to James Nayler again; and he slighted what I said, and was dark,
and much out; yet he would have come and`' kissed me.
But I said, "`since he had turned against the power of God,
I could not receive his show of kindness;`" the Lord moved me to slight him,
and to "`set the power of God over him.`"
So after I had been warring with the world,
there was now a wicked spirit risen up amongst Friends to war against.
I admonished him and his company.
When he was come to London, his resisting the power of God in me,
and the truth that was declared to him by me, became one of his greatest burdens.
But he came to see his out-going, and to condemn it;
and after some time he returned to truth again;
as in the printed relation of his repentance, condemnation, and recovery,
may be more fully seen.

We passed from Exeter through Collumpton and Taunton, visiting Friends;
and had meetings amongst them.
From thence we came to Puddimoor, to William Beaton`'s;
where on the First-day we had a very large meeting.
A great convincement there was all through that country; many meetings we had,
and the Lord`'s power was over all; many were turned, by the power and Spirit of God,
to the Lord Jesus Christ, who died for them, and came to sit under his free teaching.

From thence we went to John Dander`'s, where we had another precious meeting.
The Lord`'s power was over all, and many were convinced of God`'s eternal truth.
Contention was raised by professors and Baptists in some places,
but the Lord`'s power came over them.
From thence we came to Edward Pyot`'s house near Bristol.
It was the Seventh-day at night that we came thither;
and it was quickly noised over the town that I was come.
I had never been there before.

On First-day morning I went to the meeting in Broadmead at Bristol;
which was large and quiet.
Notice was given of a meeting to be in the afternoon in the orchard.
There was at Bristol a rude Baptist, named Paul Gwin,
who had before made great disturbance in our meetings,
being encouraged and set on by the mayor, who, it was reported,
would sometimes give him his dinner to encourage him.
Such multitudes of rude people he gathered after him,
that it was thought there had been sometimes ten
thousand people at our meeting in the orchard.
As I was going into the orchard, the people told me, that Paul Gwin,
the rude jangling Baptist, was going to the meeting.
"`I bid them never heed, it was nothing to me who went to it.`"
When I was come into the orchard,
I stood upon the stone that Friends used to stand on when they spoke;
and I was moved of the Lord to put off my hat, and to stand a pretty while,
and let the people look at me; for some thousands of people were there.
While I thus stood silent, this rude Baptist began to find fault with my hair;
but I said nothing to him.
Then he ran on into words; and at last, "`Ye wise men of Bristol,`" said he,
"`I strange at you, that you will stand here,
and hear a man speak and affirm that which he cannot make good.`"
Then the Lord opened my mouth (for as yet I had not spoken a word),
and I asked the people, "`whether they ever heard me speak;
or ever saw me before:`" and I bid them "`take notice what kind of
man this was amongst them that should so impudently say,
that I spoke and affirmed that which I could not make good;
and yet neither he nor they had ever heard me or seen me before.
Therefore that was a lying, envious, malicious spirit, that spoke in him;
and it was of the Devil, and not of God.
I charged him in the dread and power of the Lord to be silent:
and the mighty power of God came over him, and all his company.
Then a glorious, peaceable meeting we had, and the word of life was divided amongst them;
and they were turned from darkness to the light,--to Jesus their Saviour.
The Scriptures were largely opened to them; and the traditions, rudiments, ways,
and doctrines of men were laid open before the people;
and they were turned to the light of Christ, that with it they might see them,
and see him to lead them out of them.
I opened also to them the types, figures, and shadows of Christ in the time of the law;
and showed them that Christ was come, and had ended the types, shadows, tithes,
and oaths, and put down swearing; and had set up yea and nay instead of it,
and a free ministry; for he was now come to teach people himself,
and his heavenly day was springing from on high.`"
For many hours did I declare the word of life amongst them in the eternal power of God,
that by him they might come up into the beginning, and be reconciled to him.
And having turned them to the Spirit of God in themselves,
that would lead into all truth, I was moved to pray in the mighty power of God;
and the Lord`'s power came over all When I had done, this fellow began to babble again;
and John Audland was moved to bid him repent, and fear God.
So his own people and followers being ashamed of him, he passed away,
and never came again to disturb the meeting.
The meeting broke up quietly, and the Lord`'s power and glory shone over all:
a blessed day it was, and the Lord had the praise.
After a while this Paul Gwin went beyond the seas;
many years after I met with him again at Barbadoes: of which in its place.

From Bristol we returned to Edward Pyot`'s, where we had a great meeting.
The Lord`'s power was over all, truth was declared and spread abroad,
and many were turned to Christ Jesus, their life, their prophet to teach them,
their shepherd to feed them, and their bishop to oversee them.
After the meeting, I had reasoning with some professors;
and the Lord`'s truth and power came over them.

From Edward Pyot`'s we passed to Slattenford,
where we bad a very large meeting (Edward Pyot and another Friend being still with me);
great turning of people there was to the Lord Jesus Christ, their teacher:
and people were glad that they were brought to know their way, their free teacher,
and their Saviour, Christ Jesus.

The First-day following we went to Nathaniel Crips`'s house,
who had been a justice of peace in Wiltshire,
where it was supposed there were between two and three thousand people at a meeting;
and all was quiet.
The mighty power of God was manifest,
and people were turned to the grace and truth in their hearts, that came by Jesus Christ,
which taught them to deny all ungodliness and worldly lust,
and to live soberly and godly in this present world;
so that every man and woman might know the grace of God, which had appeared to all men,
and which was saving, and sufficient to bring their salvation.
This teacher, the grace of God, would teach them how to live, what to do,
and what to deny; it would season their words, and establish their hearts.
This was a free teacher to every one of them;
that they might come to be heirs of this grace, and of Christ, by whom it came;
who hath ended the prophets, and the priests that took tithes, and the Jewish temple.
And as for the hireling priests that take tithes now,
and their temples (which priests were made at schools and colleges of man`'s setting up,
and not by Christ), they, with all their inventions, were to be denied.
For the apostles denied the true priesthood and temple, which God had commanded,
after Christ had put an end thereto.
The Scriptures, and the truths therein contained, were largely opened,
and the people turned to the Spirit of God in their hearts;
that by it they might be led into all truth, and understand the Scriptures,
and know God and Christ, and come to have unity with them,
and one with another in the same Spirit.
They went away generally satisfied, and were glad that they were turned to Christ Jesus,
their teacher and Saviour.

Next day we went to Marlborough, where we had a little meeting.
The sessions being held that day, they were about to grant a warrant to send for me;
but one Justice Stooks being at the sessions, stopped them,
telling them there was a meeting at his house yesterday, at which were several thousands.
So the warrant was stopped, and the meeting was quiet;
and several received Christ Jesus their teacher, came into the new covenant,
and abode in it.

From hence we went to Newbury, where we had a large, blessed meeting,
and several were convinced.
Then we passed to Reading, where we had a large, precious meeting in the Lord`'s power,
amongst the plants of God.
Many of other professions came in, and were reached, and added to the meeting.
All was quiet, and the Lord`'s power was over all.
We went next to Kingston-on-thames,
where a few came in to us that were turned to the Lord Jesus Christ:
but it is since become a larger meeting.

Leaving Kingston, we rode to London.
When we came near Hyde Park, we saw a great concourse of people,
and looking towards them, espied the Protector coming in his coach.
Whereupon I rode to his coachside; and some of his life-guards would have put me away,
but he forbade them.
So I rode by with him, declaring what the Lord gave me to say of his condition,
and of the sufferings of Friends in the nation; showing him,
how contrary this persecution was to Christ and his apostles, and to Christianity.
When we arrived at James`'s Park-gate, I left him;
and at parting he desired me to come to his house.
Next day, one of his wife`'s maids, whose name was Mary Sanders, came to me at my lodging,
and told me her master came to her, and said he would tell her some good news.
When she asked him what it was, he told her, George Fox was come to town.
She replied that was good news indeed (for she had received truth), but she said,
she could hardly believe him, till he told her how I met him,
and rode from Hyde Park to James`'s Park with him.

After a little time Edward Pyot and I went to Whitehall: and when we came before him,
Dr. Owen, vice-chancellor of Oxford, was with him.
We were moved "`to speak to Oliver Cromwell concerning the sufferings of Friends,
and laid them before him; and directed him to the light of Christ,
who enlighteneth every man that cometh into the world.`"
He said it was a natural light; but we "`showed him the contrary,
and manifested that it was divine and spiritual, proceeding from Christ,
the spiritual and heavenly man; and that which was called the _life_ in Christ the Word,
was called the _light_ in us.`"
The power of the Lord God arose in me,
and I was moved in it "`to bid him lay down his crown at the feet of Jesus.`"
Several times I spoke to him to the same effect.
Now I was standing by the table, and he came and sat upon the table`'s side by me,
and said he would be as high as I was;
and so continued speaking against the light of Christ Jesus;
and went away in a light manner.
But the Lord`'s power came over him, so that when he came to his wife and other company,
he said, "`I never parted so from them before;`" for he was judged in himself.

After he had left us, as we were going out, many great persons came about us;
and one of them began to speak against the light, and against the truth;
and I was made to slight him, for speaking so lightly of the things of God.
Whereupon, one of them told me he was the Major-General; of Northamptonshire.
"`What!`" said I, "`our old persecutor,
that has persecuted and sent so many of our friends to prison,
and is a shame to Christianity and religion!
I am glad I have met with thee,`" said I. So I was moved to
speak sharply to him of his unchristian carriage,
and he slunk away: for he had been a cruel persecutor in Northamptonshire.

Now, after I had visited the meetings of Friends in and about London,
I went into Buckinghamshire, and Edward Pyot with me;
and in several places in that county many received the truth.
Great meetings we had, and the Lord`'s power was eminently manifested.
I passed through Northamptonshire and Nottinghamshire, into Lincolnshire.
After having had several meetings in Lincolnshire,
I had at last a meeting where two knights, one called Sir Richard Wrey,
and the other Sir John Wrey, with their wives, were at the meeting.
One of their wives was convinced, received the truth, and died in it.
When the meeting was over we passed away; and it being evening, and dark,
a company of wild serving-men encompassed me about,
with intent (as I apprehended) to do me some mischief.
But I spoke aloud to them, and asked, "`What are ye? highwaymen?`"
Whereupon some Friends and friendly people that were behind, came up to us,
and knew some of them.
So I reproved them for their uncivil and rude carriage, and exhorted them to fear God;
and the Lord`'s power came over them, and stopped their mischievous design:
blessed be his name for ever!

Then I turned into Huntingdonshire: and the mayor of Huntingdon came to visit me,
and was very loving, and his wife received the truth.

Thence I passed into Cambridgeshire, and the Fen-country, where I had many meetings,
and the Lord`'s truth spread.
Robert Craven (who had been sheriff of Lincoln) and Amor Stoddart,
and Alexander Parker were with me.
We went to Crowland, a very rude place;
for the townspeople were collected at the inn we went to, and were half drunk,
both priest and people.
"`I reproved them for their drunkenness, and warned them of the day of the Lord,
that was coming upon all the wicked; exhorting them to leave their drunkenness,
and turn to the Lord in time.`"
Whilst I was thus speaking to them, and showing the priest the fruits of his ministry,
he and the clerk broke out into a rage, and got up the tongs and fire shovel to us;
so that had not the Lord`'s power preserved us, we might have been murdered amongst them.
Yet, for all their rudeness and violence, some received the truth then,
and have stood in it ever since.

Thence we passed to Boston, where most of the chief of the town came to our inn,
and the people seemed much satisfied.
But there was a raging man in the yard, and Robert Craven was moved to speak to him,
and told him he shamed Christianity, which with some few other words so stopped the man,
that he went away quiet.
Some were convinced there also.

Thus we had large meetings up and down, for I travelled into Yorkshire,
and returned out of Holderness, over Humber, visiting Friends;
and then returning into Leicestershire, Staffordshire, Worcestershire, and Warwickshire,
among Friends, I had a meeting at Edge-hill.
There came to it Ranters, Baptists, and several sorts of rude people;
for I had sent word about three weeks before to have a meeting there,
so that hundreds of people were gathered thither, and many Friends came far to it.
The Lord`'s everlasting truth and word of life reached over all;
the rude and unruly spirits were chained down;
and many that day were turned to the Lord Jesus Christ, by his power and Spirit,
and came to sit under his blessed, free teaching, and to be fed with his eternal,
heavenly food.
All was peaceable; the people passed quietly away, and some of them said it was a mighty,
powerful meeting; for the presence of the Lord was felt,
and his power and Spirit amongst them.

From hence I passed to Warwick and to Bagley, having precious meetings;
and then into Gloucestershire, and so to Oxford, where the scholars were very rude;
but the Lord`'s power came over them.
Great meetings we had up and down as we travelled.
Then I went to Colonel Grimes`'s, where there was a very large meeting;
and thence to Nathaniel Crips`'s, where came another justice to the meeting,
who was also convinced.
At Cirencester we had a meeting, which is since much increased;
and so we came to Evesham again, where I met John Camm.

[.small-break]
'''

Thus having travelled over most part of the nation, I returned to London again,
having cleared myself of that which lay upon me from the Lord.
For after I was released out of Launceston jail,
I was moved of the Lord to travel over the nation, the truth being now spread,
and finely planted in most places, that I might answer,
and remove out of the minds of people some objections,
which the envious priests and professors had raised and spread abroad concerning us.
For what Christ said of false prophets and antichrists coming in the last days,
they applied to us; and said, We were they.

Therefore was I moved to open this through the nation,
and to show "`That they who said we were the false prophets, antichrists, and deceivers,
that should come in the last days, were indeed themselves they.
For when Christ told his disciples in the 7th and 24th of Matthew,
that false prophets and antichrists should come in the last times,
and (if it were possible) should deceive the very elect; he said,
'`By their fruits ye shall know them;`' for they should be inwardly ravening wolves,
having the sheep`'s clothing.
'`And,`' said he, '`do men gather grapes of thorns, or figs of thistles?`'
as much as to say, their nature and spirit should be like a thorn, or like a thistle.
And he bid his disciples not go after them.
But before the disciples were deceased, the antichrists, false prophets,
and deceivers were come.
For John in his first epistle said, '`Little children, it is the last time;
and as ye have heard that antichrist shall come, even now there are many antichrists,
whereby we know that it is the last time.`'
So here, as Christ said to his disciples they should come,
the disciples saw they were come; as may be seen at large in Peter, Jude, John,
and other places of Scripture; '`whereby,`' says John, '`we know it is the last time.`'
And this last time began above sixteen hundred years since.
John said, '`they went out from us;`' the false prophets, antichrists, seducers,
and deceivers, went out from the church;`' '`but you,`' said he, to the church,
'`have an anointing, which abideth in you; and you need not that any man teach you,
but as the same anointing teacheth you of all things; and as it hath taught you,
ye shall abide in him.`'
Christ said to his disciples, '`Go not after them,
for they are inwardly ravening wolves;`' and John
exhorts the saints to the anointing within them;
and the rest of the apostles exhort the churches to the grace, the light, the truth,
the Spirit, the word of faith, and to Christ in their hearts, the hope of glory.
Christ told the saints that the Spirit of truth, the Holy Ghost,
should be their leader into all truth;
and Jude exhorts the church to '`pray in the Holy Ghost,`' and '`to be
built up in their most holy faith,`' which Christ was the author of.
Christ, by his servant John,
'`exhorted the seven churches to hear what the Spirit
said to the churches,`' and this was an inward,
spiritual hearing.
Christ says, the inwardly ravening wolves should have the sheep`'s clothing.
Paul speaks of some in his time, that had '`a form of godliness, but denied the power.`'
John said, '`they went out from us.`'
Jude said, '`they go in Cain`'s way, and in Balaam`'s, and Corah`'s way.
By all which it may be clearly seen, that the false prophets and antichrists,
which Christ foretold should come, the apostles saw were come;
and in their day it was the last time; and these went forth from them into the world,
and the world went after them.
These were the foremen, the leaders of the world,
that brought them into a form of godliness,
but inwardly ravened from the power and Spirit.
These have the sheep`'s clothing, the words of Christ, of the prophets,
and of the apostles;
but are inwardly ravened from the power and Spirit that they were in,
who gave forth the Scriptures.
These have made up the beast and the whore!
These have got the dragon`'s power, the murdering, destroying, persecuting power!
And these are they that the world wonders after!
These have drunk the blood of the martyrs, prophets, and saints,
and persecuted the true church into the wilderness!
These have set up the false, compelling worships, and have drunk the blood of the saints,
that will not drink of their cup!
These have made the cage for the unclean birds,
that have their several unclean notes in their cage;
which cage is made up by the power of darkness, and uncleanness;
and the birds of the cage deny the Holy Ghost, and the power of God,
which the apostles were in, to be now manifested in the saints!
Thus since Christ said, the false prophets and antichrists should come,
and the apostle said, they were come,
the beast`'s and the dragon`'s worship hath been set up;
and the whore is got up with her false prophets, and her cage hath been made,
and all nations have drunk of her cup of fornication;
the blood of the martyrs and saints they have drunk,
and the true church hath fled into the wilderness; and all this since the apostles`' days.
Yet the blind deceivers, the antichrists and false prophets of our age,
would make us and people believe, that the false prophets, antichrists,
and deceivers are come but now,
though John and other of the apostles tell us
they were come above sixteen hundred years ago.
And ye may see what work and confusion they have made in the world;
how much blood these Cains have drunk that went in Cain`'s way;
which blood cries to God for vengeance upon Christendom!
And how these Balaams,
that have erred from the power and Spirit which the apostles were in,
have coveted after other men`'s estates, the many jails, courts,
and spoilings of goods will bear witness.
And how the Corahs have gainsayed the life, power, and spirit,
which the apostles and true church were in,
and the free teaching of Christ and his apostles, and the work of their ministry,
which was '`to present every man perfect in Christ Jesus,`' hath been evident.

"`Therefore in the name and power of the Lord Jesus was
I sent to preach again the everlasting gospel,
which had been preached before unto Abraham, and in the apostles`' days;
which was to go over all nations, and be preached to every creature.
For as the apostacy hath gone over all nations since the apostles`' days,
so that the nations are become as waters, unstable,
being gone from Christ the foundation; so must the gospel, the power of God,
go over all nations again.
We find the false prophets, antichrists, deceivers, whore, false church, beast,
and his worship in the dragon`'s power,
have got up in the times between the apostles and us.
For Christ said,
'`they should come;`' and the apostles saw '`they were come,`' and coming in their days;
and that they went forth from them, and the world went after them.
And now hath the Lord raised us up beyond them,
and set us over them in the everlasting gospel, the power of God;
that as all have been darkened by the beast, whore, false prophets, and antichrists,
so the everlasting gospel may be preached again by us to all nations,
and to every creature, which will bring life and immortality to light in them,
that they may see over the devil and his false prophets, antichrists, seducers,
and deceivers, and over the whore and beast, and to that which was before they were.
This message of the glorious everlasting gospel was I sent forth to declare and publish,
and thousands by it are turned to God, having received it;
and are come into subjection to it, and into the holy order of it.
And since I have declared this message in this part of the world, and in America,
and have written books on the same, to spread it universally abroad; the blind prophets,
preachers, and deceivers,
have given over telling us the false prophets should
'`come in the last times;`' for a great light is sprung up,
and shines over their heads;
so that every child in truth sees the folly of their sayings.

"`Then they raised other objections against us,
and invented shifts to save themselves from truth`'s stroke.
For when we blamed them for taking tithes, which came from the tribe of Levi,
and were set up here by the Romish church, they would plead,
'`that Christ told the scribes and Pharisees they ought to pay tithes of mint, anise,
and cumin, though they had neglected the weightier matters;`' and that Christ said,
'`the scribes and Pharisees sat in Moses`'s seat, therefore all that they bid you do,
that do and observe.`'
And when we told them they were envious, persecuting priests, they would reply,
that '`some preached Christ of envy, and some of contention, and some of good-will.`'
Now these Scriptures,
and such like they would bring to darken the minds of their hearers,
and to persuade them and us, '`that we ought to do as they say,
though they themselves were like the Pharisees;
and that we should rejoice when envious men and men of strife preached Christ;
and that we should give them the tithes, as the Jews did to the tribe of Levi.`'
These were fair glosses; here was a great heap of husks, but no kernel.
Now this was their blindness; for the Levitical priesthood Christ hath ended,
and disannulled the commandment that gave them tithes, and the law,
by which those priests were made.
Christ did not come after that order,
neither did he send forth his ministers after that order;
for those of that order were to take tithes for their maintenance;
but his ministers he sent forth _freely._
And as for hearing that the Pharisees, and the Jews paid tithes of mint, anise,
and cumin, that was before Christ was sacrificed and offered up;
the Jews were then to do the law, and perform their offerings and sacrifices,
which the Jewish priests taught them.
But after Christ was offered up, he bid them then,
'`go into all nations and preach the gospel; and lo,`' said he,
'`I will be with you to the end of the world;`' and in another place he saith,
'`I will be in you.`'
So he did not bid them go to hear the Pharisees then, and pay tithe of mint, anise,
and cummin then; but '`Go preach the gospel, and believe in the Lord Jesus, and be saved,
and receive the gospel,`' which would bring people off from the Jews, the tithes,
the Levitical law, and the offerings thereof, to Christ, the one Offering,
made once for them all of what work had the
apostle with both the Galatians and the Romans,
to bring them off the law to the faith in Christ!

"`And as for the apostle`'s saying, '`Some preached Christ of envy and strife,`' etc,
that was at the first spreading of Christ`'s name abroad,
when they were in danger not only to be cast out of the synagogues,
but to be stoned to death, that confessed the name of Jesus,
as may be seen by the uproars that were among the Jews
and Diana`'s worshippers at the preaching of Christ.
So the apostle might well rejoice, if the envious, and men of strife and contention,
preached Christ at that time, though they thought thereby to add affliction to his bonds;
but afterwards, when Christ`'s name was spread abroad,
and many had got a form of godliness, but denied the power thereof, '`envious, proud,
contentious men, men of strife,
covetous teachers for filthy lucre,`' the apostles commanded the saints to turn from,
and not have any fellowship with them.
And the deacons and ministers were first to be proved,
to see if they were in the power of godliness,
and the Holy Ghost made them overseers and preachers.
So it may be seen how the priests have abused these Scriptures for their own ends,
and have wrested them to their own destruction, to justify envious, contentious men,
and men of strife.`'
Whereas the apostle says, '`the man of God must be patient,
and apt to teach;`' and they were to follow Christ, as they had him for their example.
The apostle indeed was very tender to people, while he saw them walk in simplicity;
as in the case of them that were scrupulous about meats and days;
but when the apostle saw that some drew them into the observation of days,
and to settle in such things, he then reproves them sharply, and asks them,
'`who had bewitched them?`'
So in the case of marrying he was tender,
lest their minds should be drawn from the Lord`'s joining;
but when they came to forbid marriage, and to set up rules for meats and drinks,
he called it '`a doctrine of devils,`' and an '`erring from the true faith.`'
So also he was tender concerning circumcision,
and in tenderness suffered some to be circumcised;
but when he saw they went to make a sect thereby,
and set up circumcision as a standing practice, he told them plainly,
'`if they were circumcised, Christ would profit them nothing.`'
In like manner he was tender concerning baptizing with water;
but when he saw they began to make sects about it, some crying up Paul, others Apollos,
he judged them, and called them carnal, and thanks God he had baptized no more,
but such and such; declaring plainly, that '`he was sent to preach the gospel,
and not to baptize;`' and brought them to the one baptism by the one Spirit,
into the one body, which Christ, the spiritual man, is the head of;
and exhorted the church '`all to drink into that one Spirit.`'
For he set up in the church one faith, which Christ was the author of; and one baptism,
which was that of the Spirit, into the one body; and one Lord Jesus Christ,
the spiritual baptiser, whom John said should come after him.
And further the apostle declared, that they who worshipped and served God in the Spirit,
were of the circumcision of the Spirit, which was not made with hands;
by which '`the body of the sins of the flesh was put off;
'` which circumcision Christ is the minister of.^
footnote:[For a full declaration of the doctrines of Friends as regards Baptism,
"`the sacrament of bread and wine,`" etc, see Bates`' _Doctrines,_ Barclay`'s _Apology,_
Joseph John Gurney`'s _Distinguishing Views of Friends,_
and Jacob Post`'s _History and Mystery of those called the Sacraments._]

"`Another great objection they had,
'`That the Quakers denied the sacrament (as they called it) of bread and wine,
which,`' they said, '`they were to take,
and do in remembrance of Christ to the end of the world.`'
Much work we had with the priests and professors about this,
and the several modes of receiving it in Christendom, so called;
for some take it kneeling, and some sitting; but none of them all,
that ever I could find, take it as the disciples took it.
For they took it in a chamber, after supper; but these generally take it before dinner:
and some say, after the priest hath blessed it, it is '`Christ`'s body.`'
But as to the matter, Christ said, '`Do this in remembrance of me.`'
He did not tell them how often they should do it, or how long;
neither did he enjoin them to do it always, as long as they lived,
or that all believers in him should do it to the world`'s end.
The apostle Paul, who was not converted till after Christ`'s death, tells the Corinthians,
that he had received of the Lord that which he
delivered unto them concerning this matter:
and he relates Christ`'s words concerning the cup thus;
'`This do ye,`' as oft as ye drink it, in '`remembrance of me:`' and himself adds,
'`For as often as ye eat this bread, and drink this cup,
ye do show the Lord`'s death till he come.`'
So according to what the apostle here delivers,
neither Christ nor he enjoined people to do this always;
but leave it to their liberty (as oft as ye drink it,
etc). Now the Jews used to take a cup, and to break bread,
and divide it among them in their feasts; as may be seen in the Jewish Antiquities:
so that the breaking of bread, and drinking of wine, were Jewish rites,
which were not to last always.
They also baptized with water;
which made it not seem a strange thing to them when John the
Baptist came with his decreasing ministration of water-baptism.
But as to the bread and wine, after the disciples had taken it,
some of them questioned whether Jesus was the Christ; for some of them said,
after he was crucified,
'`We trusted that it had been he which should have redeemed Israel,`' etc.
And though the Corinthians had the bread and wine, and were baptized in water,
the apostle told them they were '`reprobates,
if Christ was not _in_ them;`' and bid them '`examine themselves.`'
And as the apostle said, '`As oft as ye do eat this bread, and drink this cup,
ye do show forth the Lord`'s death +++[+++till he come]: so Christ had said before,
that he '`was the bread of life,
which came down from heaven;`' and that '`he would come and
dwell _in_ them;`' which the apostles did witness fulfilled;
and exhorted others to seek for that which comes down from above:
but the outward bread and wine, and water, are not from above, but from below.
Now ye that eat and drink this outward bread and wine in remembrance of Christ`'s death,
and have your fellowships in that, will ye come no nearer to Christ`'s death,
than to take bread and wine in remembrance of it?
After ye have eaten in remembrance of his death, ye must come _into_ his death,
and _die_ with him, as the apostles did, if ye will _live_ with him.
This is a nearer and further advanced state,
to be with him in the fellowship of his death,
than only to take bread and wine in remembrance of his death.
You must have fellowship with Christ in his sufferings: if ye will reign with him,
ye must suffer with him; if ye will live with him, ye must die with him;
and if ye die with him, ye must be buried with him:
and being buried with him in the true baptism, ye also rise with him.
Then having suffered with him, died with him, and been buried with him,
if ye are risen with Christ, '`seek those things which are above,
where Christ sitteth on the right hand of God.`'
Eat the bread which comes down from above, which is not outward bread;
and drink the cup of salvation which he gives in his kingdom, which is not outward wine.
And then there will not be a looking at the
things that are seen (as outward bread and wine,
and water are): for, as says the apostle, '`The things that are seen are temporal,
but the things that are not seen are eternal.`'

So here are many states and conditions to be gone through,
before people come to see and partake of that, which '`cometh down from above.`'
For first,
there was a taking of the outward bread and wine in remembrance of Christ`'s death:
this was temporary, and not of necessity, but at their liberty; as oft as ye do it, etc.
Secondly, there must be a coming into his death, a suffering with Christ;
and this is of necessity to salvation, and not temporary, but continual:
there must be a dying daily.
Thirdly, a being`' buried with Christ.
Fourthly, a rising with Christ.
Fifthly, after they are risen with Christ, then a seeking those things which are above;
a seeking the bread that comes down from heaven,
a feeding on and having fellowship in that.
For outward bread, wine, and water, are from below, visible and temporal:
but saith the apostle, '`We look not at things that are seen;
for the things that are seen are temporal, but the things that are not seen are eternal.`'
So the fellowship that stands in the use of bread, wine, water, circumcision,
outward temple, and things seen, will have an end:
but the fellowship which stands in the gospel, the power of God,
which was before the Devil was, and which brings life and immortality to light,
by which people may see over the Devil, that has darkened them;
this fellowship is eternal, and will stand.
And all that are in it seek that which is heavenly and eternal,
which comes down from above,
and are settled in the eternal mystery of the fellowship of the gospel,
which is hid from all eyes, that look only at visible things.
The apostle told the Corinthians, who were in disorder about water, bread and wine,
that he desired to know nothing amongst them but Jesus Christ, and him crucified.`"

Thus were the objections, which the priests and professors had raised against Friends,
answered and cleared; and the stumbling-blocks,
which they had laid in the way of the weak, removed.
And as things were thus opened, people came to see over them and through them,
and to have their minds settled upon the Lord Jesus Christ, their free teacher:
which was the service for which I was moved to travel over the
nation after my imprisonment in Launceston jail.
In this year the Lord`'s truth was finely planted over the nation,
and many thousands were turned to the Lord;
insomuch that there were seldom fewer than one thousand
in prison in this nation for truth`'s testimony;
some for tithes, some for going to the steeple-houses,
some for contempts (as they called them), some for not swearing,
and others for not putting off their hats, etc.

[.offset]
Now after I had visited most parts of the nation, and was come to London again,
finding that evil spirit at work, which had drawn J. N. and his followers out from truth,
to run Friends into heats about him, I wrote a short epistle to Friends, as follows:--

[.embedded-content-document.epistle]
--

"`To all the elect seed of God called Quakers, where the death is brought into the death,
and the elder is servant to the younger, and the elect is known,
which cannot be deceived, but obtains victory.
This is the word of the Lord God to you all: Go not forth to the aggravating part,
to strive with it out of the power of God; lest ye hurt yourselves,
and run into the same nature, out of the life.
For patience must get the victory; and to answer that of God in every one,
it must bring every one to it, to bring them from the contrary.
Let your moderation, and temperance,
and patience be known unto all men in the Seed of God.
For that which reacheth to the aggravating part without life,
sets up the aggravating part, and breeds confusion; and hath a life in outward strife,
but reacheth not to the witness of God in every one,
through which they might come into peace and covenant with God,
and fellowship one with another.
Therefore that which reacheth this witness of God in yourselves, and in others,
is the life and light; which will out-last all, is over all, and will overcome all.
And therefore in the Seed of life live, which bruiseth the Seed of death.`"

[.signed-section-signature]
G+++.+++ F.

--

I also wrote another short epistle to Friends,
to encourage them to keep up their meetings in the Lord`'s power;
of which epistle a copy here follows:--

[.embedded-content-document.epistle]
--

[.salutation]
"`Dear Friends,

"`Keep your meetings in the power of the Lord,
which is over all that is in the fall and must have an end.
Therefore be wise in the wisdom of God, which is from above,
by which all things were made and created; that that may be justified among you,
and you all kept in the solid life, which was before death was; and in the light,
which was before the darkness was with all its works.
In which light and life ye all may feel, and have the heavenly unity and peace,
possessing the gospel fellowship, that is everlasting: which was before that,
which doth not last for ever; and will remain when that is gone.
For the gospel being the power of God, is pure and everlasting.
Know it to be your portion: in which is stability, and life, and immortality,
shining over that which darkens the mortal.
So be faithful every one to God, in your measures of his power and life,
that ye may answer God`'s love and mercy to you, as obedient children of the Most High;
dwelling in love, unity, and peace, and in innocency of heart towards one another;
that God may be glorified in you, and you kept faithful witnesses for him,
and valiant for the truth on earth.
God Almighty preserve you all to his glory, that ye may feel his blessing among you,
and be possessors thereof.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
About this time many mouths were opened in our meetings,
to declare the goodness of the Lord,
and some that were young and tender in the truth would
sometimes utter a few words in thanksgiving and praises to God.
That no disorder might arise from this in our meetings,
I was moved to write an epistle to Friends, by way of advice in that matter.
And thus it was:--

[.embedded-content-document.epistle]
--

"`All my dear friends in the noble Seed of God, who have known his power, life,
and presence among you,
let it be your joy to hear or see the springs of life break forth in any;
through which ye have all unity in the same, feeling life and power.
And above all things, take heed of judging any one openly in your meetings,
except they be openly profane or rebellious, such as be out of the truth;
that by the power, life, and wisdom ye may stand over them,
and by it answer the witness of God in the world, that such,
whom ye bear your testimony against, are none of you:
that therein the truth may stand clear and single.
But such as are tender, if they should be moved to bubble forth a few words,
and speak in the Seed and Lamb`'s power, suffer and bear that; that is, the tender.
And if they should go beyond their measure,
bear it in the meeting for peace and order`'s sake,
and that the spirits of the world be not moved against you.
But when the meeting is done, if any be moved to speak to them, between you and them,
one or two of you, that feel it in the life,
do it in the love and wisdom that is pure and gentle from above:
for love is that which edifies, bears all things, suffers long, and fulfils the law.
In this ye have order and edification,
ye have wisdom to preserve you all wise and in patience;
which takes away the occasion of stumbling the weak,
and the occasion of the spirits of the world to get up: but in the royal Seed,
the heavy stone, ye keep down all that is wrong; and by it answer that of God in all.
For ye will hear, see, and feel the power of God preaching,
as your faith is all in it (when ye do not hear words), to bind, to chain, to limit,
to frustrate; that nothing shall rise, nor come forth but what is in the power:
with that ye will hold back, and with that ye will let up, and open every spring, plant,
and spark; in which will be your joy and refreshment in the power of God.

"`Now ye that know the power of God, and are come to it, which is the cross of Christ,
that crucifies you to the state that Adam and Eve were in, in the fall,
and so to the world;
by this power of God ye come to see the state they were in before they fell;
which power of God is the cross, in which stands the everlasting glory;
which brings up into the righteousness, holiness, and image of God,
and crucifies to the unrighteousness, unholiness, and image of Satan, that Adam and Eve,
and their sons and daughters, are in, in the fall.
Through this power of God, ye come to see the state they were in before they fell; yea,
I say, and to a higher state, to the Seed Christ, the second Adam,
by whom all things were made.
For man hath been driven from God: all Adam and Eve`'s sons and daughters,
being in the state of the fall, in the earth, are driven from God.
But it is said, The church is in God, the Father of our Lord Jesus Christ:
so they who come to the church, which is in God the Father of Christ,
must come to God again; and so out of the state that Adam and Eve,
and his children are in, in the fall, out of the image of God,
of righteousness and holiness, and they must come into the righteousness, true holiness,
and image of God; and so out of the earth, whither man hath been driven,
when they come to the church which is in God.
The way to this, is Christ, the Light, the Life, the Truth, the Saviour, the Redeemer,
the Sanctifier, and the Justifier; in and through whose power, light, and life,
conversion, regeneration, and translation, are known from death to life,
from darkness to light, and from the power of Satan to God again.
These are members of the true church,
who know the work of regeneration in the operation and feeling of it;
and being come to be members of the church in God,
they are indeed members one of another in the power of God,
which was before the power of darkness was.
So they that come to the church, that is in God and Christ,
must come out of the state that Adam was in, in the fall, driven from God,
to know the state that he was in before he fell.
But they that live in the state that Adam was in, in the fall,
and cannot believe a possibility of coming into the state he was in before he fell,
come not to the church, which is in God; but are far from that,
and are not passed from death to life; but are enemies to the cross of Christ,
which is the power of God.
For they mind earthly things, and serve not Christ, nor love the power,
which should bring them up to the state that Adam was in before he fell,
and crucify them to the state that man is in in the fall;
that through this power they might see to the beginning,
the power that man was in before the heavenly image, and holiness,
and righteousness was lost; by which power they might come to know the Seed, Christ,
which brings out of the old things, and makes all things new;
in which life eternal is felt.
For all the poorness, emptiness, and barrenness is in the state that man is in,
in the fall, out of God`'s power; by which power he is made rich, and hath strength again;
which power is the cross, in which the mystery of the fellowship stands:
and in which is the true glorying, which crucifies to all other gloryings.

"`And, Friends, though ye may have been convinced, and tasted of tho power,
and felt the light; yet afterwards ye may feel a winter storm, tempest and hail,
frost and cold, and temptation in the wilderness.
Be patient and still in the power, and in the light, that doth convince you,
to keep your minds to God; in that be quiet, that ye may come to the summer;
that your flight be not in the winter.
For if ye sit still in the patience, which overcomes in the power of God,
there will be no flying.
The husbandman, after he hath sowed his seed, is patient.
And by tho power, being kept in the patience, ye will come by the light to see through,
and feel over winter storms and tempests, and all the coldness, barrenness,
and emptiness: and the same light and power will go over the tempter`'s head;
which power and light was before he was.
So standing still in the light, ye will see your salvation,
ye will see the Lord`'s strength, feel the small rain, and the fresh springs,
your minds being kept low in the power and light:
for that which is out of the power lifts up.
But in the power and light ye will feel God, revealing his secrets, inspiring your minds,
and his gifts coming in unto you:
through which your hearts will be filled with God`'s love,
and praises to him that lives for evermore:
for in his light and power his blessing is received.
So in that, the eternal power of the Lord Jesus Christ preserve and keep you!
Live every one in the power of God, that ye may all come to be heirs of that,
and know it to be your portion; even the kingdom, that hath no end, and the endless life,
which the Seed is heir of.
Feel that set over all, which hath the promise and blessing of God for ever.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
About this time I received some lines from a high professor,
concerning the way of Christ, to which I returned the following answer:--

[.embedded-content-document.letter]
--

[.salutation]
"`Friend,

"`It is not circumstances we contend about, but the way of Christ and his light,
which are but one; though the world hath imagined many ways, and all out of the light;
which by the light are condemned.
He who preached this light, said, '`He that knoweth God, heareth us;
he that is not of God, heareth us not: hereby know we the Spirit of Truth,
and tho spirit of error.`'
It is the same now, with them that know the truth;
though the whole world lies in wickedness.
All dispensations and differences, that are not one in the light, we deny;
and by the light, that was before separation,
do we see them to be self-separations in the sensual, having not the Spirit.
Their fruits and end are weighed in the even balance, and found to be in the dark,
the lo-here, and lo-there thou tellest of.
The presence of Christ is not with them, though the blind see it not;
who see not with the pure eye, which is single; but with the many eyes,
which lead into the many ways.
Nor are any the people of God, but they who are baptized into this principle of light;
by which all the faithful servants of the Lord were ever guided in all ages,
since the apostacy, and before.
For the apostacy was and is from the light; and all that oppose the light are apostates.
They who contest against the truth, are enemies to it,
and are not actuated by the Spirit; but have another way than the light.
All such are in the world, its words, fashions, and customs, though of several forms,
as to their worship; yet all under the god of this world,
opposing the light and appearance of Christ, which should lead out from under his power,
of what form soever they are: yet are they all joined against the light.
All these are of the world; and fighting against them who are not of the world,
but are gathered and gathering out of it; and so it ever was against the people of God,
under what name soever.
They only are saints by calling, who are called into the light; and sons of Sion,
who vary not from the light, to which the Spirit is promised,
which is not tied to any forms out of the light;
wherein all inherit who are co-heirs with Christ; which many talk of,
who inherit the earthly instead of the heavenly.
And whereas thou speakest of Christ and his apostles clothing
themselves with the sayings and words of the prophets;
and of their being your example in so doing; I say,
wolves will take the sheep`'s clothing; but the light and life finds them out,
and judges (not by their stolen words, but) by their works.
Nor did Christ cover himself with any words, but what were fulfilled in him;
neither do any of Christ`'s boast in other men`'s lines made ready without them:
to which rule if ye be obedient, fewer words and more life will be seen among you.
Then ye will not count it straitness to silence the flesh, and hear what he saith,
who speaks peace, '`that his people turn no more to folly.`'
If ye once know that what is stolen must be restored fourfold,
the mouth of the false prophet will be stopped, which builds up in deceit,
but not in righteousness.
And whereas thou sayest,
'`The Spirit of truth affords nothing but endless varieties;`' I say,
the Spirit of truth thou knowest not: for the Spirit of truth said,
'`there is but one thing needful;`' and to speak the same thing again,
is safe for the hearers.
But that spirit, which affords nothing but endless varieties, is not the Spirit of truth;
but is gone out into curious notions:
and the number of his names and colours is read nowhere,
but in the unity of the Spirit of truth.
All others call truth deceit, and deceit truth, as the blind, that opposed the light,
ever did; who are ever learning endless varieties,
but never able to come to the knowledge of the truth, nor to an end of their labours:
but when they are out of one form, get into another;
so long as they can find a green tree without.
Thus ye are kept at work all your life, and to the grave in sorrow, as the dumb priests,
thou tellest of, have been before you: only ye have got a finer image, but less life.
And thou, whose teaching hath no end, art in the horse-mill thou speakest of.
I have read the epistles to Timothy, and to the Hebrews;
and there I find the duty of all believers is,
to see the law of the new covenant written in the heart, whereby all may know God,
from the least to the greatest.
I know the Holy Scriptures are profitable for the man of God;
but what is that to the man of sin, to the first-born, who is out of the light,
and being unstable and unlearned, wrest them to his own destruction;
but to the life cannot come?
And for your two ordinances thou speakest of, I say,
upon the same account ye deny the priests of the world therein, we deny you;
being both of you not only out of the life, but out of the form too.
That command, Matt. 28:19, ye never had, nor its power; which was,
'`to baptize into the name of the Father, Son, and Holy Ghost.`'
What Paul received of the Lord, that body, and that bread, ye know as little,
but what ye have found in the chapter; nor the coming of Christ neither,
who cannot believe Ids light.
And whereas thou speakest of preaching Christ of envy, and pleadest for it; I say,
such preachers we have enough of in these days.
What else art thou doing, who sayest, Paul was sent to baptize;
though Paul says he was not: and so thou wouldst prove him a liar,
if any would believe thee before him.
Thou sayest also, '`for ought thou knowest, he might baptize thousands.`'
Thou mightest as easily have said millions, and as soon have proved it.
Thou mayest say the same of circumcision also, and on the same ground.
As for the signs that followed those that believed, which thou sayest are ceased; I say,
they who cannot receive the light cannot see the signs,
nor could believe them if they should see them to carp at;
no more than formerly they could do, who opposed the light in former ages.
They cannot properly be said to cease to such, who never had them;
but have only heard or read, that others long ago had them.
But that the power, and signs, and presence of God is not the same that ever it was,
in the measure, wherein he is received in the light, that I deny;
and declare it to be false, and from a spirit that knows not God, nor his power.
And as for the gospel foundation thou speakest of, I say,
it is to be laid again in all the world.
Ye never were on it, since the man of sin set up his forms without power.
Till ye can own the light of Christ, which the saints preached,
and their life and practice; for shame cease to talk of their foundation,
or glorious work, or quakings and tremblings, which are the saints`' experiences,
which the world knows not, nor can own:
though ye cannot read that ever any came aright to declare how they knew God,
or received his word, without them.
In thy exhortation thou biddest me '`love Christ,
wheresoever I see him:`' but hadst thou told me where one might come to see him,
or how one might know him, thou hadst showed more of a Christian in that,
than in all thou hast spoken.
But it seems, ye are not all of one mind: some of you say, '`he is gone,
and will be no more seen,
till doomsday but if ever ye come to see Christ to your comfort,
while ye oppose his light, then God hath not spoken by me.
This thou shalt remember, when thy time thou hast spent.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
Great opposition did the priests and professors make
about this time against the light of Christ Jesus,
denying it to be universally given; and against the pouring forth of the Spirit,
and sons and daughters prophesying thereby.
Much they laboured to darken the minds of people,
that they might keep them still in a dependence on their teaching.
Wherefore I was moved of the Lord to give forth the following lines,
for the opening of the minds and understandings of people,
and to manifest the blindness and darkness of their teachers:--

[.embedded-content-document.address]
--

"`To all you professors, priests, and teachers, who are in darkness,
and know not the Spirit in prison, nor the light that shines in darkness,
and which the darkness doth not comprehend; but are the infidels,
whom the god of the world hath blinded, and to whom the gospel is hid.
For though ye have the four books, yet the gospel is hid to you;
who are now wondering at the work of God,
and do not believe that Christ hath enlightened every one that cometh into the world.
I offer you some Scriptures to read, which will prove your spirits, and try them,
how contrary they are to the apostles`' spirit, the Spirit of Christ and of the saints.
Christ went and '`preached to the spirits in prison,`' 1 Pet. 3:19. He that readeth,
let him understand, whether this was a measure of the Spirit, yea or nay,
or the Spirit without measure, which he ministered to?`'
For he whom God hath sent, speaketh the words of God;
for God giveth not the Spirit by measure unto him,`' John 3:34.
Here Christ had not the Spirit given to him by measure.
The apostle said,`' We will not boast of things without (or beyond) our measure.`'
2 Cor. 10:13. So here was measure, and not by measure.
Christ, who received not the Spirit by measure,
told his disciples he would '`send them the Comforter, the Spirit of Truth,
that should guide them into all truth: for he should not speak of himself,
but whatsoever he shall hear, that shall he speak, and he will show you things to come.
He shall glorify me: for he shall receive of mine, and show it unto you, '` John 16:13, 14.
Mind, read, and learn; the Comforter shall receive of mine, saith Christ,
and shall show it unto you: who hath the measure,
receives of his who hath not by measure.
The Comforter, when he comes, is to '`reprove the world of sin, and of righteousness,
and of judgment,`' ver. 8.
Now mind the great work of God: the Spirit of Truth,
which leads the saints into all truth, which receives of Christ`'s,
and shows it unto the disciples, who are in the measure,
he shall reprove the world of sin, because they do not believe, etc.
The Comforter, whom Christ will send, takes of his, and shows it to the disciples;
the same reproves the world.
Mind now, whether this be a measure, yea or nay, which comes from him,
who received not the Spirit by measure.
He that leads the believer into all truth, reproves the unbeliever in the world, of sin,
of righteousness, and of judgment; so he that is led into all truth,
sees that which is reproved, by the Spirit of Truth that leads him.
Now Christ saith, '`He shall take of mine, and show it unto you.`'
Is this a measure, yea or nay, from him to whom God gave the Spirit not by measure?

"`Again, the Lord said, both by his prophet, Joel 2:28, and his apostle,
Acts 2:17-18, '`It shall come to pass in the last days,
I will pour out of my Spirit upon all flesh, your sons and your daughters shall prophesy,
your young men shall see visions, and your old men shall dream dreams:
and on my servants, and handmaidens, I will pour out in those days of my Spirit,
and they shall prophesy.`'
Look, ye deceivers; here the Lord saith, he will pour out of his Spirit; mark the word,
Of the Lord`'s Spirit upon all flesh.
What! young men, old men, sons and daughters, and maidens,
all these to have the Spirit of God poured forth upon them?
Here, say they, these deny the means then: nay, that is the means.
And the great and notable day of the Lord is coming, wherein it shall come to pass,
that whosoever shall call on the name of the Lord shall be saved.
The God of the spirits of all flesh is known; '`And,`' saith the apostle,
who would not boast of things beyond his measure,
'`that which may be known of God is manifest in them;
for God hath showed it unto them,`' Rom. 1:19.
By this which was of God manifest in them,
they knew covetousness, maliciousness, murder, deceit, and ungodliness;
and knew that the judgments of God were upon such things;
and that they were worthy of death not only that did the same,
but who had pleasure in them that did them.
Therefore said the apostle,
'`the wrath of God is revealed from heaven against all ungodliness,
and unrighteousness of men,`' etc.
Now this of God manifest in them, which God showed unto them,
by which they know unrighteousness, and God`'s judgments thereupon,
and that they which commit such things are worthy of death; whether this be a measure,
yea or nay, which is of God, and which he hath showed to them?
What was that in them that did by nature the things contained in the law,
which showed the work of the law written in their heart,`' Rom.
ii. Ii, 15. Mark, '`written!`' Shall not this judge them that have the outward law,
but are out of the life of it?
The apostle saith,
'`the manifestation of the Spirit is given to every man to
profit withal`' 1 Cor. 12:7. There are diversities of gifts,
but the same Spirit;
but '`the manifestation of it is given to every man to profit withal.`'
Mark, '`to one is given by the Spirit, the word of wisdom;
to another the word of knowledge by the same Spirit; to another faith by the same Spirit;
to another the gifts of healing by the same Spirit; to another the working of miracles;
to another prophecy; to another discerning of spirits;
to another divers kinds of tongues; to another the interpretation of tongues:
but all these worketh that one and the self-same Spirit,
dividing to every man severally as he will.`'
Mark that, to every man severally as he will.

"`Again, the apostle saith, '`the grace of God that bringeth salvation,
hath appeared unto all men, teaching us, that denying ungodliness and worldly lusts,
we should live soberly, righteously,
and godly in this present world,`' Tit. 2:11-12. Now ye,
that turn this grace which bringeth salvation, into lasciviousness, deny it, and say,
that which teacheth the saints, who by grace are saved, hath not appeared to all men.
Jude saith, '`Behold, the Lord cometh with ten thousands of his saints,
to execute judgment upon all, and to convince all that are ungodly among them,
of all their ungodly deeds which they have committed, and of all their hard speeches,
which ungodly sinners have spoken against him, verse 15. Here mark again;
him that cometh with ten thousands of his saints,
to convince all of their ungodly deeds and hard speeches; here it is,
All of their ungodly deeds, and All of their hard speeches; none left out,
but All to be convinced and judged,
the world reproved by him who comes with ten thousands of his saints, and will reign,
and be king and judge.
And have not ye all something in you, that doth reprove you for your hard speeches,
and your ungodly deeds, the ungodliest of you all,
who live in your hard speeches against him,
and his light and spiritual appearance in his people?

"`Again, the apostle, writing to the Gentiles, saith,
'`But unto every one of us is given grace,
according to the measure of the gift of Christ,`' Eph. 4:7.
Now mark, here is the measure of the gift of Christ,
'`who lighteth every man that cometh into the world,`' John 1:9,
'`that all men through him might believe.
He that believeth on him is not condemned, but he that believeth not is condemned, etc.
And this is the condemnation, that light is come into the world,`' etc,
John 3:18-19. Now every man that cometh into the world being enlightened, one loves it,
and brings his deeds to the light,
that with the light he may see whether they be wrought in God; the other hates the light,
'`because his deeds are evil;`' and he will not bring his deeds to the light,
because he knows the light will reprove him.
So he that hates the light, wherewith Christ hath enlightened him,
knows the light will reprove him for his evil deeds; and, therefore,
he will not come to the light.

"`Again, the Lord by his prophet said concerning Christ,
'`I will give him for a light to the Gentiles,
that he may be my salvation to the ends of the earth,`' Isa. 49:6. And what is that,
which the children that walk '`according to the course of this world,
according to the prince of the power of the air,
the spirit that now worketh in the children of disobedience,`' Eph. 2:2,
are disobedient to?
Mark, and read for yourselves, who being disobedient,
walk according to the course of the world,
according to the power of the prince of the air; mark, I say,
what it is that all such are disobedient to?
He that hath an ear, let him hear.
The apostle saith to the Colossians,
'`the wrath of God cometh upon the children of disobedience,`' Col. 3:6. Come,
ye professors, let us see, is not this something of God that is disobeyed?
Is it not that which is of God manifest in them, which God hath shown them,
which lets them see God`'s judgments are upon such, when they act unrighteously?
Is not this the measure of God (mark), the Spirit that is in prison?
and the Spirit of God that is grieved?

"`And ye professors, come, let us read the parable of the talents, and reckon with you,
and see who it is that hath hid the Lord`'s money in the earth?
Come, ye that have gained, enter ye into your master`'s joy.
Go, thou that hast hid the Lord`'s money in the earth, into utter darkness;
'`take it from him, and give it to him that hath;`' every man shall have his reward.
For the Lord hath given '`to every man according to his several ability,`' Matt. 25:15;
mark that, '`to every man according to his several ability?`'
read this, if you can.
Now is the Lord coming to call every man severally to account,
to whom he hath given severally according to his ability.
Now the wicked and slothful servant, who hid the Lord`'s money in the earth,
will be found out; and the Lord`'s money will be taken from him,
although he hath hidden it.
To him the Lord`'s commands have been grievous; but to us they are not,
who love God and keep his commandments.
'`And,`' saith the apostle to the Romans, '`I say, through the grace given unto me,
to every man that is among you,
not to think of himself more highly than he ought to think, but to think soberly,
according as God hath dealt to every man the
measure of faith,`' Rom. 12:3. Read and mark,
here is a measure of faith.

"`'`And,`' saith another apostle, '`as every one hath received the gift,
even so minister the same one to another,
as good stewards of the manifold grace of God,`' 1 Pet. 4:10,
'`For the grace of God hath appeared unto all men.`'
The good stewards can give their account with joy; but ye bad stewards,
that turn the grace of God into lasciviousness, now ye will be reckoned withal;
now ye shall have your reward.
'`But,`' say the world, '`must every one minister as he hath received the gift?`'
'`Yea,`' say I, '`but let him speak as the oracles of God;
and let him do it as of the ability which God
giveth,`' verse 11. John in the Revelation saith,
'`They were judged every man according to their works,`' Rev. 20:13. Christ saith,
'`Every idle word that men shall speak,
they shall give account thereof in the day of judgment,`' Matt. 12:36. So '`ye,
that name the name of Christ,
depart from iniquity,`' 2 Tim. 2:19. '`The Son
of man shall come in the glory of his Father,
with his angels;
and then he shall reward every one according to his works,`'
Matt. 16:27. He who is gone into a far country,
and hath given the talents to every one of you, according to your several ability,
'`will render to every man according to his deeds,
'` Rom. 2:6. '`And further I say unto you,
if any man have not the Spirit of Christ, he is none of his.
And if Christ be in you, the body is dead because of sin, but the Spirit is life,
because of righteousness,
Rom. 8:10-9. So let the light which cometh from Christ examine;
for the Lord is appearing.
Ye that have received according to your ability, smite not your fellow servant;
and think not that the Lord delayeth the time of his coming.
Be not as they that said, '`Let us eat and drink, for tomorrow we shall die.`'

"`The apostle tells the Ephesians,
that unto him '`this grace was given--to make all
men see what is the fellowship of the mystery,
which from the beginning of the world hath been hid in God,
who created all things by Jesus Christ,
Eph. 3:9. Read and understand every one with the light which comes from Christ,
the mystery, which will be your condemnation, if ye believe not in it.
This is to all, who stumble at the work of the Spirit of God, the manifestation of it,
'`which is given to every man, to profit withal.`'
Come, ye professors, who stumble at it; let us read the parables.
'`A sower went forth to sow; and some seed fell on the highway ground,
and some on stony ground, and some on thorny ground; the Seed is the Word,
the Son of man is the seedsman.
He that hath an ear, let him hear, Matt. 13.
Now look, all ye professors, what ground ye are?
and what ye have brought forth?
and whether the wicked seedsman hath not got his seed into your ground?
'`He that hath an ear, let him hear.
And come, read another parable, of the householder,
hiring labourers to go into the vineyard, and agreeing with every man for a penny, Matt. 20.
Every man is to have his penny, the last that went in, as well as the first;
and the last shall be first, and the first shall be last; for many are called,
but few are chosen.
He that hath an ear, let him hear.`'
There is a promise spoken to Cain, that if he did well he should be accepted,
Gen. 4:7. And Esau had a birthright, but despised it.
Yet it is '`not of him that willeth, Rom. 9:16; '`but by grace ye are saved,
Eph. 2:8. And stand still, and see your salvation,
Ex. 14:13. And ye that are children of light, put on the armour of light,
that ye may come into '`the unity of the faith, and of the knowledge of the Son of God,
unto a perfect man, unto the measure of the stature of the fulness of Christ;
that henceforth ye be no more children tossed to and fro,
Eph. 4:13. '`And the Lord said, he would make a new covenant,
by '`writing his law in people`'s hearts, and putting his Spirit in their inward parts;
whereby they should all come to know the Lord--Him by whom the world was made.
Now every one of you, mind the law written in your hearts,
and this Spirit put in your inward parts, that it need not be said to you,
'`know the Lord; but that ye may witness the promise of God fulfilled in you.`'
But, say the world, and professors,
'`if every one must come to witness the law of God written in their hearts,
and the Spirit put in the inward parts, what must we do with all our teachers?`'
As we come to witness that, we need not any man to teach us to know the Lord,
having his law written in our hearts, and his Spirit put in our inward parts.
This is the covenant of life, the everlasting covenant, which decays not, nor changes;
and here is the way to the Father, without which no man cometh unto the Father.
And here is the everlasting priesthood, the end of the old priesthood,
whose lips were to preserve knowledge; but now, saith Christ, '`Learn of me;
who is the high-priest of the new priesthood.`'
'`And,`' saith the apostle, '`that ye may grow up in the knowledge of Jesus Christ,
in whom are hid the treasures of wisdom and knowledge.`'
So we are brought off from the old priesthood that changed, to Christ,
to the new priesthood, that changeth not; and off from the first covenant,
that doth decay, to the everlasting covenant that doth not decay, Christ Jesus,
the covenant of Light, from whom every one of you have a light,
that ye might believe in the covenant of Light.
If ye believe not, ye are condemned; for light is come into the world,
and men love darkness rather than light, because their deeds are evil.
'`I am come a light into the world,`' saith Christ, '`that whosoever believeth in me,
should not abide in darkness, but have the light of life,`' John 12:46. And,
'`believe in the light, that ye may be children of the light.
But ye who do not believe in the light, but hate it,
because it manifests your deeds to be evil, ye are they that are condemned by the light.
Therefore, while ye have time, prize it; seek the Lord while he may be found,
and call upon him while he is near; lest he say, '`time is past;
for the rich glutton`'s time was past.
Therefore, while time is not quite past, consider, search yourselves,
and see if ye be not they that hate the light;
and so are builders that stumble at the cornerstone; for they that hated the light,
and did not believe in the light, did so in ages past.
'`I am the light of the world,`' saith Christ,
'`who enlighteneth every man that cometh into the world;`' and he also saith,
'`learn of me;`' and of him God saith, '`this is my beloved Son, hear ye him.`'
Here is your teacher.
But ye that hate the light, do not learn of Christ,
and will not have him to be your king, to reign over you;--Him,
to whom all power in heaven and earth is given,
who bears his government upon his shoulders, who is now come to reign;
who lighteth every man that cometh into the world, and will give to every man a reward,
according to his works, whether they be good or evil.
So every man, with the light that comes from Christ, will see his deeds,
both he that hates it, and he that loves it.
And he that will not bring his deeds to the light, because it will reprove him,
that is his condemnation; and he shall have a reward according to his deeds.
For the Lord is come to reckon with you.
He looks for fruits; now the axe is laid to your root,
and every tree of you that bears not good fruit, must be hewn down,
and cast into the fire.`"

[.signed-section-signature]
G+++.+++ F.

--

Having stayed some time in London,
and visited the meetings of Friends in and about the city,
and cleared myself of what services the Lord had at that time laid upon me there,
I travelled into Kent, Sussex, and Surrey, visiting Friends,
amongst whom I had great meetings;
and many times met with opposition from Baptists and other jangling professors;
but the Lord`'s power went over them.

We stayed one night at Farnham, where we had a little meeting,
and the people were exceedingly rude; but at last the Lord`'s power came over them.
After it we went to our inn, and gave notice that any that feared God might come to us:
and there came abundance of rude people, the magistrates of the town also,
and some professors.
I declared the truth unto them; and those of the people that behaved rudely,
the magistrates put out of the room.
When they were gone, there came another rude company of professors,
and some of the chief of the town.
They called for faggots and drink, though we forbade them;
and were as rude a people as ever I met with.
The Lord`'s power chained them, that they had not power to do us any mischief;
but when they went away,
they left all their faggots and beer which they had called for into the room,
for us to pay for in the morning.
We showed the innkeeper what an unworthy thing it was, but he told us,
"`we must pay it;`" and we did.
Before we left the town, I wrote a paper to the magistrates and heads of the town,
and to the priest, showing them and him how he had taught his people,
and laying before them their rude and uncivil
conduct to strangers that sought their good.

Leaving that place we came to Basingstoke, a very rude town;
where they had formerly very much abused Friends.
There I had a meeting in the evening, which was quiet,
for the Lord`'s power chained the unruly.
At the close of it I was moved to put off my hat,
and pray to the Lord to open their understandings; upon which they raised a report,
that "`I put off my hat to them, and bid them good night,`" which was never in my heart.
After the meeting, when we came to our inn, I sent for the innkeeper (as I used to do),
and he came into the room to us, and showed himself a very rude man.
I admonished him to be sober and fear the Lord;
but he called for faggots and a pint of wine, and drank it off himself;
then called for another, and called up half a dozen men into our chamber.
Thereupon I bid him go out of the chamber, and told him he should not drink there,
for we sent for him up to speak to him concerning his eternal good.
He was exceedingly mad, rude, and drunk.
When he continued his rudeness, and would not be gone,
I told him the chamber was mine for the time I lodged in it, and I called for the key.
Then he went away in great rage.
In the morning he would not be seen;
but I told his wife of his unchristian and rude behaviour towards us.

After this we came to Bridport, having meetings in the way.
We went to an inn, and sent into the town for such as feared God;
and there came a shopkeeper, a professor, and put off his hat to us,
and seeing we did not the same to him again, but said Thou and Thee to him, he told us,
"`he was not of our religion;`" and after some discourse with him he went away.
Then he went and stirred up the priest and magistrates against us,
and after a while sent to the inn to desire us to come to his house,
for there were some that would speak with us, be said.
Thomas Curtis was with me, and he went to the man`'s house; where, when he came,
the man had laid a snare for him, for he had got the priest and magistrate thither,
and they boasted much that they had caught George Fox, taking him for me.
When they perceived their mistake, they were in great rage;
yet the Lord`'s power came over them, so that they let him go again.
Meanwhile I had an opportunity of speaking to some sober people that came to the inn.
When Thomas was come back, and we were passing out of the town,
some of them came to us, and said,
"`the officers were coming to fetch me;`" but the Lord`'s power came over them all,
so that they had not power to touch me.
There were some convinced in the town, who were turned to the Lord,
and have stood faithful in their testimony to the truth ever since,
and a fine meeting there is there.

Passing hence we visited Portsmouth and Poole, where we had glorious meetings;
and many were turned to the Lord.
At Ringwood we had a large general meeting, where the Lord`'s power was over all.
At Weymouth we had a meeting; and thence came through Dorchester to Lyme,
where the inn we went to was taken up with mountebanks,
so that there was hardly any room for us or our horses.
In the evening we drew up some queries concerning the ground of all diseases,
and the natures and virtues of medicinal things, and sent them to the mountebanks;
letting them know, "`if they would not answer them,
we would stick them on the cross next day.`"
This brought them down, and made them cool, for they could not answer them;
but in the morning they reasoned a little with us.
We left the queries with some friendly people, that were convinced in the town,
to stick upon the market-cross.
The Lord`'s power reached some of the sober people in that place,
who were turned by the Light and Spirit of Christ to his free teaching.

We then travelled to Exeter; and at the sign of the Seven Stars,
an inn at the bridge foot,
had a general meeting of Friends out of Cornwall and Devonshire;
to which came Humphrey Lower, Thomas Lower, and John Ellis^
footnote:[John Ellis, who is only twice mentioned in this journal,
was an able gospel minister, preaching in the authority of divine life,
to the reaching of God`'s witness in many hearts.
His doctrine was sound,
flowing from the living fountain and divine spring of life and heavenly wisdom.
His preaching was full of reproof and caution,
but in that meekness which made it edifying.
Whilst tender of the good in all, he was terrible against the workers of iniquity.
He was a man of great kindness, a visitor of the widows and fatherless in their distress,
feeding the hungry and clothing the naked, according to his ability.
He laboured greatly in the gospel in several counties, often saying,
"`His Father`'s business must not be neglected, or done negligently.`"
As he was travelling in the service of Truth, he was taken ill,
and died in great peace in 1707, saying, "`I am ready, for I have a sure foundation.`"]
from the Land`'s End, Henry Pollexfen, and Friends from Plymouth, Elizabeth Trelawny,
and divers other Friends.
A blessed heavenly meeting we had, and the Lord`'s everlasting power came over all,
in which I saw and said, "`that the Lord`'s power had surrounded this nation round about,
as with a wall and bulwark, and his seed reached from sea to sea.`"
Friends were established in the everlasting Seed of life, Christ Jesus, their life, rock,
teacher, and shepherd.

Next morning Major Blackmore sent soldiers to apprehend me;
but I was gone before they came.
As I was riding up the street, I saw the officers going down;
so the Lord crossed them in their design, and Friends passed away peaceably and quietly.
The soldiers examined some Friends after I was gone,
"`what they did there;`" but when they told them they were in their inn,
and had business in the city, they went away without meddling any further with them.

From Exeter I took meetings as I went, till I came to Bristol,
and was at the meeting there.
After which I did not stay in the town, but passed into Wales,
and had a meeting at the Slone.
Thence going to Cardiff, a justice of the peace sent to me,
desiring I would come with half a dozen of my friends to his house.
So I took a friend or two, and went up to him,
and he and his wife received us very civilly.
The next day we had a meeting at Cardiff in the town-hall,
and that justice sent about seventeen of his family to the meeting.
There came some disturbers, but the Lord`'s power was over them,
and many were turned to the Lord.
To some that had run out with James Nayler, and did not come to meetings, I sent word,
that "`the day of their visitation was over,`" and they never prospered after.

We travelled from Cardiff to Swansea, where we had a blessed meeting;
and a meeting was settled there in the name of Jesus.
In our way thither we passed over in a boat, with the high-sheriff of the county,
and next day I went to speak with him, but he would not admit me.

"`We went to another meeting in the country, where the Lord`'s presence was much with us.
Thence to a great man`'s house, who received us very lovingly;
but next morning he would not be seen; one that in the mean time had come to him,
had so estranged him, that we could not get to speak with him again.

We still passed on through the countries, having meetings and gathering people,
in the name of Christ, to Him their heavenly teacher, till we came to Brecknock;
where we set up our horses at an inn.
There went with me Thomas Holmes and John-ap-John,
who was moved of the Lord to "`speak in the streets.`"
I walked out a little into the fields, and when I came in again,
the town was in an uproar.
When I came into the chamber in the inn, it was full of people,
and they were speaking in Welsh; I desired them to speak in English, which they did,
and much discourse we had.
After a while they went away;
but towards night the magistrates gathered together in the streets,
with a multitude of people, and they bid them shout, and gathered up the town;
so that for about two hours together, there was such a noise,
that the like we had not heard; and the magistrates set them on to shout again,
when they had given over.
We thought it looked like the uproar, which we read was amongst Diana`'s craftsmen.
This tumult continued till night; and if the Lord`'s power had not limited them,
they seemed likely to have pulled down the house, and us to pieces.

At night, the woman of the house would have had us go to supper in another room,
but we discerning her plot, refused.
Then she would have had half a dozen men come into the room to us,
under pretence of discoursing with us.
We told her, no persons should come into our room that night, neither would we go to them.
Then she said, we should sup in another room; but we told her we would have no supper,
if not in our own room.
At length, when she saw she could not get us out,
she brought lip our supper in a great rage.
So she and they were crossed in their design, for they had an intent to do us mischief;
but the Lord God prevented them.
Next morning I wrote a paper to the town concerning their unchristian conduct,
showing the fruits of their priests and magistrates;
and as I passed out of the town I spoke to the people, and told them,
they were a shame to Christianity and religion.

From this place we went to a great meeting in a steeple-house yard where was a priest,
and Walter Jenkin, who had been a justice, and another justice.
A blessed glorious meeting we had.
There being many professors, I was moved of the Lord "`to open the Scriptures to them,
and to answer their objections (for I knew them very well); and to turn them to Christ,
who had enlightened them;
with which light they might see the sins and trespasses they had been dead in,
and their Saviour, who came to redeem them out of them, who was to be their way to God,
the truth and the life to them, and their priest made higher than the heavens,
so that they might come to sit under his teaching.`"
A peaceable meeting we had; many were convinced and settled in the truth that day.
After it, I went with Walter Jenkin to the other justice`'s house; and lie said to me,
"`You have this day given great satisfaction to the people,
and answered all the objections that were in their minds.`"
For the people had the Scriptures, but were not turned to the Spirit,
which should let them see that, which gave them forth, the Spirit of God,
which is the key to open them.

From hence we passed to Richard Hamborow`'s, at Pontemoil, where was a great meeting;
to which came another justice of peace, and several great people,
whose understandings were opened by the Lord`'s Spirit and power,
and they were turned to the Lord Jesus Christ, from whence it came.
A great convincement there was; a large meeting was gathered in those parts,
and settled in the name of Jesus.

After this we returned to England, and came to Shrewsbury, where we had a great meeting,
and visited Friends all over the countries in their meetings,
till we came to William Gaudy`'s, in Cheshire,
where we had a meeting of between two and three thousand people, as it was thought;
and the everlasting word of life was held forth, and received that day.
A blessed meeting it was, for Friends were settled by the power of God upon Christ Jesus,
the rock and foundation.

At this time there was a great drought; and after this general meeting was ended,
there fell so great a rain, that Friends said, they thought we could not travel,
the waters would be so risen.
But I believed the rain had not extended so far, as they had come that day to the meeting.
Next day in the afternoon, when we turned back into some parts of Wales again,
the roads were dusty, and no rain had fallen there.

When Oliver Cromwell sent forth a proclamation for a fast throughout the nation,
for rain, when there was a very great drought, it was observed,
that as far as truth had spread in the north,
there were pleasant showers and rain enough, when in the south, in many places,
they were almost spoiled for want of rain.
At that time I was moved to write an answer to the Protector`'s proclamation,
wherein I told him, "`if he had come to own God`'s truth, he should have had rain;
and that drought was a sign unto them of their barrenness,
and want of the water of life.`"
About the same time was written the following paper,
to distinguish between true and false fasts:--

[.embedded-content-document.paper]
--

[.blurb]
=== Concerning the true Fast and the false.

"`To all you that are keeping fasts, who`' smite with the fist of wickedness,
and fast for strife and debate;`' against you hath a voice cried aloud, like a trumpet,
that you may come to know the true fast, '`which is accepted; and the fast,
which is in the strife and the debate, and smiting with the fists of wickedness;
which fast is not required of the Lord.
'`Behold, in the day of your fast, you find pleasure, and exact all your labours.
Behold (mark, take notice),
ye fast for strife and debate and to smite with the fist of wickedness;
ye shall not fast, as ye do this day, to make your voice heard on high.
Is it such a fast, that I have chosen, saith the Lord,
a day for a man to afflict his soul?
Is it to bow down his head like a bulrush, and to spread sackcloth and ashes under him?
Wilt thou call this a fast and an acceptable day to the Lord?

"`Consider all you that fast, see, if it be not '`hanging down the head for a day,
like a bulrush:`' and fasting for '`strife and debate,`'
and to '`smite with the fists of wickedness,
to make your voice be heard on high?
But this fast is not accepted of the Lord: but that which leads you from strife,
from debate, from wickedness; which is not to '`bow down the head,
as a bulrush for a day,`' and yet live in exacting and pleasure;
this is not accepted of the Lord:
but that which separates from all these before-mentioned.
That which separates from '`wickedness, debate, strife, pleasures,
smiting with the fist of wickedness,`' brings to know the true fast,
which '` breaks the bonds of iniquity, and deals bread to the hungry;
brings the poor that are cast out to his own house, and when he sees any naked,
he covers them, and hides not himself from his own flesh.`'
Here is the true fast, which separates from them,
where the bonds of iniquity are standing,
and the heavy burdens of the oppressed remaining, and the yoke not broken;
who deal not bread to the hungry, and bring not the poor to their own house;
who see the naked, but let him go unclothed, and hide themselves from their own flesh.
Yet such will make their voice to be heard on high, as Christ speaks of the Pharisees,
who '`sounded a trumpet before them,
and disfigured their faces,`' to appear to men to fast;
but the bonds of iniquity were standing, strife and debate were standing,
striking with the fists of wickedness standing; these made their voice heard on high,
who had their reward.

"`But that which brings to the true fast, which appears not to men to fast,
but unto the Father '`who seeth in secret; the Father that seeth in secret,
shall reward this openly.`'
This fast separates from the Pharisees`' fast, and them that bow the head for a day,
like a bulrush.
This is it which brings '`to deal bread to the hungry,
and clothe thine own flesh when thou seest them naked; to bring the poor to thine house,
and to loose the bonds of wickedness;`' mark, this is the fast;
and '`to undo every heavy burden (mark again),
and to let the oppressed go free;`' this is the fast: and '`to break every yoke.`'
When thou observest this fast, '`then shall thy light break forth as the morning,
and thine health shall spring forth speedily, and thy righteousness shall go before thee;
the glory of the Lord shall be thy reward.
Then shalt thou call, and the Lord shall answer; thou shalt cry, and he shall say,
Here I am: if thou take away from the midst of thee the yoke,
the putting forth of the finger, and speaking vanity;
and if thou draw out thy soul to the hungry, and satisfy the afflicted soul,
then shall thy light arise m obscurity, and thy darkness be as the noon-day.`'
The light brings to know this fast; and walking in it this fast is kept:
and he that believeth in the light, abides not in darkness.
And again; '`the Lord shall guide thee continually, and satisfy thy soul in drought,
and make fat thy bones; and thou shalt be like a watered garden,
and like a spring of water,
whose waters fail not,`' Isa. 58:11. These are they
that are guided by the light which comes from Christ,
where the springs are.

"`And again; '`they that shall be of thee (that keep this fast),
shall build the old waste places,
and thou shalt raise up the foundations of many generations;
and thou shalt be called The repairer of the breach,
The restorer of the paths to dwell in,`' Isa. 58:12. Now
that which gives to see the foundations of many generations,
is the light which separates from all, which is out of the light:
and they that go out of the light, though they may pretend a fast,
and bow down the head for a time, yet they are far from this fast,
that doth raise up the foundations of many generations,
and is the repairer of the breach, and restorer of the paths to dwell in.
That which doth give to see these foundations of many generations,
and these breaches that are to be repaired and restored, and paths to dwell in,
is the light which brings to know the true fast; and where this fast is known,
which is from wickedness, debate, strife, pleasures, from exacting,
from the voice that is heard on high, from the speaking of vanity,
from the bonds of iniquity, which breaks every yoke, and lets the oppressed go free;
here the health grows; here the morning is known, and righteousness goes forth;
the glory of the Lord is the reward, and the light riseth;
the soul is drawn out to the hungry, and satisfies the afflicted soul;
and the springs of living water are known and felt.
The waters fail not here; the Lord guides continually,
and the foundations of many generations come to be seen and raised up:
The repairer of breaches is here witnessed, The restorer of paths to dwell in.

"`But all such as are out of the light which the prophets were in,
with which they saw Christ, and such as are in fasts, where was strife, wickedness,
debate, and bowing down the head like a bulrush for a day, lifting their voice on high,
and the bonds of wickedness yet standing, and the burdens unloosed,
and the oppressed not let go free, and the yoke not broken, the nakedness not clothed,
the bread not dealt to the hungry,
and these foundations of many generations not raised up;
until these things before-mentioned be broken down,--on
such the light breaks not forth as the morning,
and the Lord hears them not.
Such have their reward; their iniquities have separated them from their God,
their sins have hid his face from them, that he will not hear:
their hands are defiled with blood, and their fingers with iniquity,
whose lips have spoken lies, and tongues muttered perverseness.
'`None calleth for justice, nor do any plead for truth; they trust in vanity,
and speak lies; they conceive mischief, and bring forth iniquity.
They hatch cockatrice-eggs, and weave the spider`'s-web: he that eateth of their eggs,
dies; and that which is crushed breaks out into a viper:
their webs shall not become garments,
neither shall they cover themselves with their works.`'
Observe; '`their works are works of iniquity, and the act of violence is in their hands:
their feet run to do evil, and they make haste to shed innocent blood.
Their thoughts are thoughts of iniquity; wasting and destruction are in their paths;
the way of peace they know not, and there is no judgment in their doings.
They have made them a crooked path; whosoever goeth therein shall not know peace mark;
such go from the light, therefore is judgment far off; neither doth justice overtake.
Here is obscurity, walking in darkness; groping like blind men,
as though they had no eyes, and stumbling at noon-day in desolate places, like blind men.
Here is the roaring like bears, and mourning sorely like doves;
here judgment is looked for, but there is none, and salvation is put far off:
for the light is denied, which gives to see it.
But here are the multiplying of transgression, and their sins testifying against them;
the transgression that was within them, and their iniquities,
which they knew in transgressing and lying against the Lord,
speaking the things they should not, when they knew by that of God in them,
that they should not speak it.
So departing from the way of God, speaking oppression, revolting,
conceiving and uttering forth from the heart words of falsehood;
here judgment is turned away backward, and justice stands afar off;
truth is fallen in the streets, and equity cannot enter.
Yea, truth faileth; and he that departeth from evil makes himself a prey.
The Lord saw it, and it displeased him.
These are such as are in the fast, which God doth not accept; not in the true fast,
whose '`light breaks forth as the morning:`' but these are such as are in the false fast,
who grope, like blind men.

"`That winch gives to know the true fast, and the false fast, is the Light,
which gives the eye to see each fast, where the true judgment is,
and the iniquity standeth not, nor the transgressor, nor the speaker of lies;
but that is judged and condemned with the Light, which makes it manifest.
And when they who are in this fast call upon the Lord, the Lord will answer them,
Here am I. Here truth is pleaded for, and falsehood flies away.
But they who are out of this fast, in the perverseness,
whose tongues utter perverse things, who are stumbling and groping like blind men,
out of the light, in the iniquity which separates from God,
who hides his face from them that he will not hear;--these going from the light,
go from the Lord and his face.
So this is it which must be fasted from; for it separates from God;
and here comes the reward openly, which condemns all that is contrary to the light;
injustice, iniquity, transgression, vanity, and that which bringeth forth mischief,
which hatcheth the cockatrice-eggs, and weaves the spider`'s web:
he that eateth of these eggs dies.
Mark, '`that which is crushed breaks out into a viper;`' mark again,
'`their webs shall not become garments,
neither shall they cover themselves with their works of vanity;
acts of violence are in their hands.`'
This is all out of the light, in the wickedness.
'`Their feet run to do evil, and they make haste to shed innocent blood;
their thoughts are thoughts of vanity; wasting and destruction are in their path.`'
This is all far from the light.
Again, '`the way of peace they know not, there is no judgment in their goings;
they have made them crooked paths, whosoever go therein, shall not know peace.`'
Mark; who go in their way, that know not the way of peace, shall they know peace?`'
Whose path is crooked, where there is no judgment in their goings;`' take notice,
'`no judgment in their goings;`' this is all from the light,
which manifesteth that which is to be judged; where the covenant of peace is known,
where all that which is contrary to it is kept out.
All who live in those things contrary to the light, in the false fast,
stumbling and groping like blind men, may mark their path, and behold their reward.
They that are in the true fast, are separated from all these;
from their words and actions, their fruits, and their fast:
but of those whose fast breaks the bonds of iniquity, whom the Lord hears,
and to whom righteousness springs forth, and goes before them,
the glory of the Lord is the reward.`"

[.signed-section-signature]
G+++.+++ F.

--

We passed into Wales through Montgomeryshire, and so into Radnorshire,
where there was a meeting like a leaguer, for multitudes.
I walked a little aside, whilst the people were gathering;
and there came to me John-ap-John, a Welshman, whom I desired to go to the people;
and if he had anything upon him from the Lord to them, he might speak to them in Welsh,
and thereby gather them more together.
Then came Morgan Watkins^
footnote:[Morgan Watkins, who is only mentioned in this place,
became a sufferer for the truth.
About eight years from the above date, we find him in the Gatehouse prison,
near Westminster abbey, with nineteen others on the same account,
being committed by warrant from the Duke of Albemarle,
"`for being at a meeting in St. John`'s.`" This
was during the time the plague visited London.
In Barclay`'s _Letters of Early Friends_, are two from Morgan Watkins,
one of them dated from the Gatehouse prison, in which he says,
"`Blessed be His name who hath kept me, and nineteen more in this close place,
all in health, above these five weeks;
notwithstanding three have been buried out of this prison of
the sickness.--Good is the hand of the Lord to his own,
whose death is gain.`"
{footnote-paragraph-split}
In a letter written about three months after the above,
he mentions the release of himself and Friends, and adds,
"`I have been weak since I came out into the air, but through the great love of my God,
I am wonderfully preserved, to the praise of his name.
But the two imprisonments in Newgate, and the one at the Gatehouse,
have much weakened my body, in which I have had several battles with death;
but the power of my God arising,
gave me dominion over the distemper and weakness of the flesh.
The day was dreadful to all flesh, and few were able to abide it,
and stand in the judgment; but the Lord was very merciful to the remnant of his people,
and his blessed seed is arising in many.]
to me, who was then become loving to Friends, and said, "`the people lie like a leaguer,
and the gentry of the country are come in.`"
I bid him go up also, and leave me,
for I had a great travail upon me for the salvation of the people.
When they were well gathered, I went into the meeting,
and stood upon a chair about three hours.
I stood a while before I began to speak;
after some time I felt the power of the Lord over the whole assembly;
and his everlasting life and truth shone over all.
The Scriptures were opened to them, and their objections answered.
"`They were directed to the light of Christ, the heavenly man;
that by it they might all see their sins, and Christ Jesus to be their Saviour,
their Redeemer, their Mediator, and come to feed on him, the bread of life from heaven.`"
Many were turned to the Lord Jesus, and his free teaching that day;
and all were bowed down under the power of God;
so that though the multitude was so great, that many sat on horseback to hear,
there was no opposition.
A priest who sat with his wife on horseback, heard attentively, and made no objection.
The people parted peaceably and quietly, with great satisfaction;
many of them saying they never heard such a sermon before, or the Scriptures so opened.
For "`the new covenant was opened, and the old, and the nature and terms of each;
and the parables were explained.
The state of the church in the apostles`' days was set forth, and the apostacy laid open;
and the free teaching of Christ and the apostles was set over
the hireling teachers;`" and the Lord had the praise of all,
for many were turned to him that day.

I went back thence to Leominster, where was a great meeting in a field;
many hundreds of people being gathered together.
There were about six congregational preachers and priests among them; and Thomas Taylor,
who had been a priest, but was now become a minister of Christ, was with me.
I stood up, and declared about three hours;
and none of the priests were able to open their mouths in opposition;
the Lord`'s power and truth so reached them, and bound them down.
At length one priest went off about a bow-shot from me,
drew several of the people after him, and began to preach to them.
So I kept our meeting, and he kept his.
After a while Thomas Taylor was moved to go and speak to him: and he gave over; and he,
and the people he had drawn off, came to us again;
and the Lord`'s power went over them all.
At last a Baptist, that was convinced, said, "`Where`'s priest Tombs?
how chance he doth not come out?`"
This Tombs was priest of Leominster.
Hereupon some went and told the priest;
who came with the bailiffs and other officers of the town.
When he was come, they set him upon a stool over against me.
Now I was speaking of the heavenly, divine light of Christ,
with which he "`enlightens every one that cometh into the world,
to give them the knowledge of the glory of God
in the face of Christ Jesus their Saviour.`"
When priest Tombs heard this, he cried out, "`That is a natural light, and a made light.`"
Then I desired the people to take out their Bibles;
and I asked the priest whether he affirmed that that was a created, natural, made light,
which John, a man that was sent from God, did bear witness to, and spoke of,
when he said, "`In him (to wit, in the Word) was life,
and that life was the light of men,`" John 1:4. "`Dost thou affirm and mean,`" said I,
"`that this light here spoken of, was a created, natural, made light?`"
And he said, "`Yes.`"
Then I showed by the Scriptures, that the natural, created, made light,
is the outward light in the outward firmament, proceeding from the sun, moon, and stars.
"`And dost thou affirm,`" said I,
"`that God sent John to bear witness to the light of the sun, moon, and stars?`"
Then said he, "`Did I say so?`"
I replied, "`Didst thou not say it was a natural, created, made light,
that John bore witness unto?
If thou dost not like thy words, take them again and mend them.`"
Then he said, "`That light which I spoke of, was a natural, created light.`"
I told him, "`he had not at all mended his cause; for that light which I spoke of,
was the very same that John was sent of God to bear witness to,
which was the life in the Word, by which all the natural lights,
as sun, moon, and stars, were made.
'`In him (to wit, the Word) was life,
and that life was the light of men.`'`" So "`I directed
the people to turn to the place in their Bibles,
and recited to them the words of John, how that '`In the beginning was the Word,
and the Word was with God, and the Word was God.
The same was in the beginning with God; all things were made by him,
and without him was not anything made, that was made.
(So all natural, created lights were made by Christ the Word.) In him was life,
and the life was the light of men; and that was the true light,
which lighteth every man that cometh into the world.`'`" And Christ saith of himself,
John 8:12, "`I am the light of the world;`" and bids them "`believe in the light,`" John 12:36.
And God said of him by the prophet Isaiah,
chap. 49:6, "`I will also give thee for a light to the Gentiles,
that thou mayest be my salvation to the ends of the earth.`"
So Christ in his light is saving.
And the apostle said, "`The light, which shined in their hearts,
was to give them the light of the knowledge of the glory of
God in the face of Jesus Christ;`" and that was their
"`treasure in their earthen vessels,`" 2 Cor. 4:6-7.

When I had thus opened the matter to the people, the priest cried to the magistrates,
"`Take this man away, or else I shall not speak any more.`"
"`But,`" said I, "`Priest Tombs, deceive not thyself, thou art not in thy pulpit now,
nor in thy old mass-house; but we are in the fields.`"
So he was shuffling to be gone; and Thomas Taylor stood up,
and undertook to make out our principle by Christ`'s parable concerning the sower, Matt. 13.
Then said the priest, "`Let that man speak, and not the other.`"
So he got into a little jangling for a while;
till the Lord`'s power stopped and confounded him.
Afterwards a Friend stood up and told him, how he had sued him for tithe eggs,
and other Friends for other tithes; for he was an Anabaptist preacher,
and yet had a parsonage at Leominster, and had several journeymen under him.
He said "`he had a wife, and he had a concubine; and his wife was the baptized people,
and his concubine was the world.`"
But the Lord`'s power came over him and them all,
and the everlasting truth was declared that day;
and many were turned by it to the Lord Jesus Christ their teacher and way to God.
Of great service that meeting was in those parts.
Next day Thomas Taylor went to this priest, and reasoned with him;
and overcame him by the power of the Word.

From this place I travelled on in Wales, having several meetings, till I came to Tenby;
where, as I rode up the street, a justice of peace came out of his house,
desired me to alight, and stay at his house; and I did so.
On First-day the mayor and his wife, and several of the chief of the town,
came in about ten, and stayed all the time of the meeting.
A glorious one it was.
John-ap-John being then with me, left it, and went to the steeple-house;
and the governor cast him into prison.
On the Second-day morning the governor sent one of his
officers to the justice`'s house to fetch me;
which grieved the mayor and the justice;
for they were both with me in the justice`'s house when the officer came.
So the mayor and the justice went up to the governor before me;
and a while after I went up with the officer.
When I came in, I said, "`Peace be unto this house.`"
And before the governor could examine me, I asked him why he cast my friend into prison.
He said, "`For standing with his hat on in the church.`"
I said, "`Had not the priest two caps on his head, a black one and a white one?
Cut off the brims of the hat, and then my friend would have but one,
and the brims of the hat were but to defend him from weather.`"
"`These are frivolous things,`" said the governor.
"`Why then,`" said I, "`dost thou cast my friend into prison for such frivolous things?`"
Then he asked me, whether I owned election and reprobation; "`Yes,`" said I,
"`and thou art in the reprobation.`"
At that he was in a rage, and said he would send me to prison till I proved it;
but I told him I would prove that quickly, if he would confess truth.
Then I asked him, whether wrath, fury, rage, and persecution,
were not marks of reprobation; for he that was born of the flesh,
persecuted him that was born of the Spirit;
but Christ and his disciples never persecuted nor imprisoned any.
Then he fairly confessed that he had too much wrath, haste, and passion in him.
I told him Esau was up in him, the first birth, not Jacob, the second birth.
The Lord`'s power so reached and came over him, that he confessed to truth;
and the other justice came, and shook me kindly by the hand.

As I was passing away, I was moved to speak to the governor again,
and he invited me to dine with him, and set my friend at liberty.
I went back to the other justice`'s house; and after some time the mayor and his wife,
and the justice and his wife, and divers other Friends of the town,
went about half a mile out of town with us, to the water-side, when we went away;
and there, when we parted from them, I was moved of the Lord to kneel down with them,
and pray to the Lord to preserve them.
So after I had recommended them to the Lord Jesus Christ, their Saviour and free teacher,
we passed away in the Lord`'s power, and the Lord had the glory.
A meeting continues in that town to this day.

We travelled to Pembrokeshire, and in Pembroke had some service for the Lord.
Thence we passed to Haverford-west, where we had a great meeting, and all was quiet.
The Lord`'s power came over all, and many were settled in the new covenant, Christ Jesus,
and built upon him, their rock and foundation;
and they stand a precious meeting to this day.
Next day, being their fair-day, we passed through it, and "`sounded the day of the Lord,
and his everlasting truth amongst them.`"

After this we came into another county, and at noon came into a great market-town,
and went into several inns, before we could get any meat for our horses.
At last we came to one where we got some.
Then John-ap-John being with me, went and spoke through the town,
declaring the truth to the people; and when he came to me again,
he said he thought all the town were as people asleep.
After a while he was moved to go and declare truth in the streets again;
then the town was all in an uproar, and cast him into prison.
Presently after, several of the chief of the town came, with others,
to the inn where I was, and said, "`They have cast your man into prison.`"
"`For what?`" said I, "`He preached in our streets,`" said they.
Then I asked them, "`What did he say?
had he reproved some of the drunkards and swearers, and warned them to repent,
and leave off their evil doings, and turn to the Lord?`"
I asked them, who cast him into prison?
They said, the high-sheriff and justices, and the mayor.
I asked their names, and whether they understood themselves?
and whether that was their conduct to travellers that passed through their town,
and strangers that admonished and exhorted them to fear the Lord,
and reproved sin in their gates?
These went hack, and told the officers what I said;
and after a while they brought down John-ap-John, guarded with halberts,
in order to put him out of the town.
Being at the inn door, I bid the officers take their hands off him.
They said, "`the mayor and justices had commanded them to put him out of town.
I told them I would talk with their mayor and justices,
concerning their uncivil and unchristian carriage towards him.
So I spoke to John to go look after the horses, and get them ready,
and charged the officers not to touch him.
And after I had declared the truth to them, and showed them the fruits of their priests,
and their incivility and unchristian-like carriage, they left us.
They were a kind of Independents; a very wicked town, and false.
We bid the innkeeper give our horses a peck of oats;
and no sooner had we turned our backs, than the oats were stolen from our horses.
After we had refreshed ourselves a little, and were ready, we took horse,
and rode up to the inn, where the mayor, sheriff, and justices were.
I called to speak with them, and asked them why they had imprisoned John-ap-John,
and kept him in prison two or three hours?
But they would not answer me a word; they only looked out at the windows upon me.
So I showed them how unchristian their carriage was to strangers and travellers,
and manifested the fruits of their teachers; and I declared the truth unto them,
and warned them of the day of the Lord, that was coming upon all evildoers;
and the Lord`'s power came over them, that they looked ashamed;
but not a word could I get from them in answer.
So when I had warned them to repent, and turn to the Lord, we passed away;
and at night came to a little inn, very poor, but very cheap;
for our own provision and our two horses, cost but eightpence;
but the horses would not eat their oats.
We declared the truth to the people of the place,
and sounded the day of the Lord through the countries.

Thence, we came to a great town, and went to an inn.
Edward Edwards went into the market, and declared the truth amongst the people;
and they followed him to the inn, and filled the yard, and were exceedingly rude;
yet good service we had for the Lord amongst them;
for the life of Christianity and the power of it tormented their chaffy spirits,
and came over them, so that some were reached and convinced;
and the Lord`'s power came over all.
The magistrates were bound; they had no power to meddle with us.

After this we came to another great town on a market-day;
and John-ap-John declared the everlasting truth through the streets,
and proclaimed the day of the Lord amongst them.
In the evening many people gathered about the inn; and some of them, being drunk,
would fain have had us into the street again; but seeing their design, I told them,
if there were any that feared God, and desired to hear the truth,
they might come into our inn; or else we might have a meeting with them next morning.
Some service for the Lord we had amongst them, both over night and in the morning;
and though the people were hard to receive the truth, yet the seed was sown;
and thereabouts the Lord hath a people gathered to himself.
In that inn also I turned but my back to the man that was giving oats to my horse;
and looking round again, I observed he was filling his pockets with the provender.
A wicked, thievish people, to rob the poor dumb creature of his food.
I would rather they had robbed me.

Leaving this town and travelling on, a great man overtook us on the way,
and he purposed (as he told us afterwards) to take us up at the next town for highwaymen.
But before we came to the town, I was moved of the Lord to speak to him.
What I spoke reached to the witness of God in the man, who was so affected therewith,
that he had us to his house, and entertained us very civilly.
He and his wife desired us to give them some Scriptures,
both for proof of our principles and against the priests.
We were glad of the service, and furnished them with Scriptures enough;
and he wrote them down, and was convinced of the truth,
both by the Spirit of God in his own heart, and by the Scriptures,
which were a confirmation to him.
Afterwards he set us on our journey, and as we travelled we came to a hill,
which the people of the country say, is two or three miles high;
from the side of this hill I could see a great way.
And I was moved to set my face several ways, and to sound the day of the Lord there;
and I told John-ap-John (a faithful Welsh minister) in
what places God would raise up a people to himself,
to sit under his own teaching.
Those places he took note of, and a great people have since been raised up there.
The like I have been moved to do in many other rude places;
and yet I have been moved to declare the Lord had a seed in those parts,
and afterwards there have been a brave people raised up in the covenant of God,
and gathered in the name of Jesus; where they have salvation and free teaching.

From this hill we came to Dolgelly, and went to an inn.
John-ap-John declared through the streets,
and the town`'s people rose and gathered about him.
There being two Independent priests in the tow-n,
they came out and discoursed with him together.
I went up to them, and finding them speaking in Welsh, I asked them,
"`what was the subject they spoke upon, and why they were not more moderate,
and spoke not one by one?
For the things of God,`" I told them, "`were weighty,
and they should speak of them with fear and reverence.`"
Then I desired them to speak in English, that I might discourse with them,
and they did so.
They affirmed, "`that the light which John came to bear witness of, was a created,
natural, made light.`"
But I took the Bible, and showed them (as I had done to others before),
"`that the natural lights, which were made and created, were the sun, moon, and stars;
but this light, which John bare witness to, and which he called '`the true light,
that lighteth every man that cometh into the world,`' is the life in Christ the Word,
by which all things were made and created.
The same that is called the life in Christ, is called the light in man;
and this is a heavenly divine light, which lets men see their evil words and deeds,
shows them all their sins, and, if they would attend unto it, would bring them to Christ,
from whom it comes, that they might know him to save them from their sin,
and to blot it out.
This light, I told them, shone in the darkness of their hearts,
and the darkness in them could not comprehend it;
but in those hearts where God had commanded it to shine out of darkness,
it gave unto such the knowledge of the glory of God,
in the face of Christ Jesus their Saviour.
Then I opened the Scriptures largely to them,
and turned them to the Spirit of God in their hearts,
which would reveal the mysteries in the Scriptures to them,
and would lead them into all truth as they became subject thereunto.
I directed them to that which would give every one of them the knowledge of Christ,
who died for them, that he might be their way to God,
and make peace between God and them.`"
The people were attentive,
and I spoke to John-ap-John to stand up and speak it in Welsh to them, which he did;
and they generally received it, and with hands lifted up blessed and praised God.
The priests`' mouths were stopped, so that they were quiet all the while,
for I had brought them to be sober at the first,
by telling them that "`when they speak of the things of God and of Christ,
they should speak with fear and reverence.`"
Thus the meeting broke up in peace in the street,
and many of the people accompanied us to our inn,
and rejoiced in the truth that had been declared unto them;
that they were turned to the light and Spirit in themselves,
by which they might see their sin, and know salvation from it.
When we went out of the town, the people were so affected,
that they lifted up their hands, and blessed the Lord for our coming.
A precious seed the Lord hath thereaway,
and many people in those parts are since gathered to the Lord Jesus Christ,
to sit down under his free teaching; and they have suffered much for him.

From hence we passed to Caernarvon, a city like a castle.
When we had put up our horses at an inn, and refreshed ourselves,
John-ap-John went forth, and spoke through the streets; which were so strait and short,
that one might stand in the midst of the town and see both the gates.
I followed him, and a multitude of people were soon gathered;
amongst whom a very dark priest began to babble; but his mouth was soon stopped.
When John had cleared himself, I declared the word of life amongst the people;
directing them to "`the light of Christ in their hearts,
that by it they might see all their own ways, religions, and teachers,
and might come off from them all, to Christ, the true and living way,
and the free teacher.`"
Some of them were rude, but the greater part were civil,
and told us they had heard how we had been persecuted and abused in many places,
but they would not do so to us there.
I commended their moderation and sobriety, and warned them of "`the day of the Lord,
that was coming upon all sin and wickedness;`" testifying unto them,
"`that Christ was now come to teach his people himself, by his Spirit and by his power.`"

From hence we went to Beaumaris; a town wherein John-ap-John had formerly been preacher.
After we had put up our horses at an inn, John went forth and spoke through the street;
and there being a garrison in the town, they took him and put him into prison.
The innkeeper`'s wife came and told me that the governor and
magistrates were sending for me to commit me to prison also.
I told her, they had done more than they could answer already;
and had acted contrary to Christianity in imprisoning him for
reproving sin in their streets and for declaring the truth.
Soon after came other friendly people, and told me,
if I went out into the street they would imprison me also;
and therefore they desired me to keep at the inn.
Upon this I was moved to go and walk up and down the streets; and told the people,
"`what an uncivil and unchristian thing they had done,
in casting my friend into prison.`"
And, they being high professors, I asked them,
"`if this was the entertainment they had for strangers;
if they would willingly be so served themselves; and whether they,
who looked upon the Scriptures to be their rule,
had any example therein from Christ or his apostles, for what they had done?`"
So after a while they set John-ap-John at liberty.

Next day, being market-day, we were to cross a great water:
and not far from the place where we were to take boat,
many of the market-people drew to us; amongst whom we had good service for the Lord,
declaring the word of life and everlasting truth unto them,
and proclaiming the day of the Lord amongst them, which was coming upon all wickedness;
and directing them to the light of Christ, which he had enlightened them with?
by which they might see all their sins, and false ways, religions, worships,
and teachers: and by the same light might see Christ Jesus, who was come to save them,
and lead them to God.
After the Lord`'s truth had been declared to them in the power of God,
and Christ the free teacher set over all the hireling teachers,
I bid John-ap-John get his horse into the boat, which was then ready.
But there being a company of wild gentlemen, as they called them, got into it,
whom we found very rude, and far from gentleness, they, with others,
kept his horse out of the boat.
I rode to the boat`'s side and spoke to them,
showing them "`what unmanly and unchristian conduct it was;
and told them they showed an unworthy spirit, below Christianity or humanity.`"
As I spoke, I leaped my horse into the boat amongst them,
thinking John`'s horse would have followed, when he had seen mine go in before him;
but the water being deep, John could not get his horse into the boat.
Wherefore I leaped out again on horseback into the water,
and stayed with John on that side till the boat returned.
There we tarried from eleven in the forenoon, to two in the afternoon,
before the boat came to fetch us; and then we had forty-two miles to ride that evening:
and when we had paid for our passage, we had but one groat left between us in money.
We rode about sixteen miles, and then got a little hay for our horses.
Setting forward again, we came in the night to a little ale-house,
where we intended to stay and bait; but finding we could have neither oats nor hay there,
we travelled on all night;
and about five in the morning got to a place within six miles of Wrexham;
where that day we met with many Friends, and had a glorious meeting;
and the Lord`'s everlasting power and truth was over all:
and a meeting is continued there to this day.
Very weary we were with travelling so hard up and down in Wales;
and in many places we found it difficult to get meat either for our horses or ourselves.

Next day we passed thence into Flintshire,
sounding the day of the Lord through the towns; and came into Wrexham at night.
Here many of Floyd`'s people came to us; but very rude, wild, and airy they were,
and little sense of truth they had: yet some were convinced in that town.
Next morning one called a lady sent for me, who kept a preacher in her house.
I went, but found both her and her preacher very light and airy;
too light to receive the weighty things of God.
In her lightness she came and asked me, if she should cut my hair:
but I was moved to reprove her,
and bid her cut down the corruptions in herself with the sword of the Spirit of God.
So after I had admonished her to be more grave and sober, we passed away:
and afterwards in her frothy mind, she made her boast that
"`she came behind me and cut of the curl of my hair;`" but she spoke falsely.

From Wrexham we came to Chester; and being the fair time, we stayed a while,
and visited Friends.
For I had travelled through every county in Wales,
preaching the everlasting gospel of Christ; and a brave people there is now,
who have received it, and sit under Christ`'s teaching.
But before I left Wales,
I wrote to the magistrates of Beaumaris concerning the imprisoning of John-ap-John;
letting them see their conditions, and the fruits of their Christianity,
and of their teachers.
Afterwards I met with some of them near London;
but oh how ashamed they were of their action!

From Chester we came to Liverpool, where was at that time a fair also.
As I rode through the fair, there stood a Friend upon the cross,
declaring the truth to the people: who seeing me ride by,
and knowing I had appointed a meeting next day upon a hill not far off,
gave notice to the people "`that George Fox, the servant of the Lord,
would have a meeting next day upon such hill; and if any feared the Lord,
they might come and hear him declare the word of life to them.`"
We went that night to Richard Cubban`'s, who himself was convinced, though not his wife;
but at that time she became convinced also.

Next day we went to the meeting on the top of the hill, which was very large.
Some rude people with a priest`'s wife came, and made a noise for a while,
but the Lord`'s power came over them, the meeting became quiet,
and the truth of God was declared amongst them.
Many were that day settled upon the rock and foundation of Christ Jesus,
and under his teaching; who made peace between God and them.

We had a small meeting, with a few Friends and people at Malpas.
Thence we came to another place, where we had another meeting.
There came a bailiff with a sword, and was rude: but the Lord`'s power came over him,
and Friends were established in the truth.

Thence we came to Manchester; and the sessions being there that day,
many rude people were come out of the country.
In the meeting they threw at me coals, clods, stones, and water:
yet the Lord`'s power bore me up over them, that they could not strike me down.
At last, when they saw they could not prevail by throwing water, stones, and dirt at me,
they went and informed the justices in the sessions;
who thereupon sent officers to fetch me before them.
The officers came in while I was declaring the word of life to the people,
plucked me down, and haled me up into their court.
When I came there, all the court was in disorder and noise.
Wherefore I asked, where were the magistrates that they did not keep the people civil?
Some of the justices said they were magistrates.
I asked them, why then they did not appease the people, and keep them sober?
for one cried, "`I`'ll swear,`" and another cried, "`I`'ll swear.`"
I declared to the justices how we were abused in our meeting by the rude people,
who threw stones, and clods, dirt, and water; and how I was hauled out of the meeting,
and brought thither, contrary to the instrument of government, which said,
"`none should be molested in their meetings that professed God
and owned the Lord Jesus Christ;`" which I did.
So the truth came over them,
that when one of the rude fellows cried "`he would swear,`"
one of the justices checked him,
saying, "`What will you swear? hold your tongue.`"
At last they bid the constable take me to my lodging; and there be secured till morning,
till they sent for me again.
So the constable had me to my lodging; and as we went the people were exceedingly rude;
but I let them see "`the fruits of their teachers, and how they shamed Christianity,
and dishonoured the name of Jesus, which they professed.`"
At night we went to a justice`'s house in the town, who was pretty moderate;
and I had much discourse with him.
Next morning we sent to the constable to know if he had anything more to say to us.
And he sent us word
"`he had nothing to say to us, but that we might go whither we would.`"
The Lord hath since raised up a people to stand for his name
and truth in that town over those chaffy professors.

We passed from Manchester, having many precious meetings in several places,
till we came to Preston; between which and Lancaster I had a general meeting:
from which I went to Lancaster.
There at our inn I met with Colonel West, who was very glad to see me:
who meeting with Judge Pell, told him I was mightily grown in the truth;
when indeed he was come nearer to the truth, and so could better discern it.

We came from Lancaster to Robert Widders`'s. On the
First-day after I had a general meeting near Sand-side,
of Friends of Westmorland and Lancashire, when the Lord`'s everlasting power was over all;
in which the word of eternal life was declared,
and Friends were settled upon the foundation, Christ Jesus, under his free teaching;
and many were convinced, and turned to the Lord.

Next day I came over the Sands to Swarthmore, where Friends were glad to see me.
I stayed there two First-days, visiting Friends in their meetings thereaways.
They rejoiced with me in the goodness of the Lord,
who by his eternal power had carried me through,
and over many difficulties and dangers in his service: to him be the praise for ever!
