== Chapter XI.

[.chapter-synopsis]
* 1657.
* Exhortation to Friends to take heed to the Light of Christ
* an expostulation with persecutors
* to Friends to be valiant for the truth
* in parts of Cumberland the priests are so forsaken that some steeple-houses stand empty
* John Wilkinson, the priest, is so deserted, that he sets up a meeting in his own house
* then a silent meeting, and at last joins Friends, and becomes an able minister
* George Fox travels into Scotland with Col. Osburn and Robert Widders
* the latter was a thundering man against the rottenness of the priests`' hypocrisy and deceit
* Lady Hamilton is convinced
* the Scotch priests raise the war-cry, and draw up their curses, which George Fox answers
* they are in a rage and panic when he comes there, thinking "`that all was gone`"
* some Baptists, with their logic and syllogisms, are confuted by George Fox`'s logic
* he is banished Scotland by the council, but disregards their order
* George Fox and William Osburn are waylaid by thieves, who are admonished by the former, and overawed by the Lord`'s power
* the Highlanders run at them with pitchforks
* at Johnstons they are banished the town
* on hearing that the council of Edinburgh had issued warrants against him, George Fox goes thither, and is not molested.

Having got a little respite from travel, I was moved to write an epistle to Friends,
as follows:--

[.embedded-content-document.epistle]
--

"`All Friends of the Lord everywhere, whose minds are turned in towards the Lord,
take heed to the light within you, which is the light of Christ; which, as ye love it,
will call your minds inward, that are abroad in the creatures:
so your minds may be renewed by it, and turned to God in this which is pure,
to worship the living God, the Lord of Hosts over all the creatures.
That which calls your minds out of the lusts of the world,
will call them out of the affections and desires,
and turn you to set your affections above.
That which calls the mind out of the world,
will give judgment upon the world`'s affections and lusts,
and is the same that calls out your minds from the world`'s teachers, and the creatures,
to have your minds renewed.
There is your obedience known and found; there the image of God is renewed in you;
and ye come to grow up in it.
That which calls your minds out of the earth, turns them towards God,
where the pure Babe is born of the virgin; and the Babe`'s food is known,
the children`'s bread, which comes from the living God, and nourishes up to eternal life.
These babes and children receive their wisdom from above, from the pure living God,
and not from the earthly one: for that is trodden under foot with such.
All who hate this light, whose minds are abroad in the creatures, in the earth,
and in the image of the devil, get the words of the saints,
that received their wisdom from above, into the old nature, and their corrupted minds.
Such are murderers of the just, enemies to the cross of Christ,
in whom the prince of the air lodgeth: sons of perdition, betrayers of the just.
Therefore take heed to that light, which is oppressed with that nature; which light,
as it arises, shall condemn all that cursed nature, shall turn it out,
and shut it out of the house: and so ye will come to see the candle lighted,
and the house sweeping and swept.
Then the pure pearl ariseth; then the eternal God is exalted.
The same light that calls in your minds out of the world, turns them to God,
the Father of lights.
Here in the pure mind is the pure God waited upon for wisdom from above;
the pure God is seen night and day; and the eternal peace,
of which there is no end, enjoyed.
People may have openings, and yet their minds go into the lusts of the flesh;
but there the affections are not mortified.
Therefore hearken to that, and take heed to that,
which calls your minds out of the affections and lusts of the world,
to have them renewed.
The same will turn your minds to God; the same light will set your affections above,
and bring you to wait for the pure wisdom of God from on high,
that it may be justified in you.
Wait all in that, which calls in your minds, and turns them to God;
here is the true cross.
That mind shall feed upon nothing that is earthly;
but be kept in the pure light of God up to God, to feed upon the living food,
which comes from the living God.
The Lord God Almighty be with you all, dear babes,
and keep you all in his strength and power to his glory,
over all the world,--you whose minds are called out of it, and turned to God,
to worship the Creator, and serve him, and not the creature.
The light of God, which calls the mind out of the creatures, and turns it to God,
brings into a being of endless joy and peace.
Here is always a seeing God present, which is not known to the world,
whose hearts are in the creatures, whose knowledge is in the flesh,
whose minds are not renewed.
Therefore all Friends, the Seed of God mind and dwell in, to reign over the unjust:
and the power of the Lord dwell in, to keep you clear in your understandings,
that the Seed of God may reign in you all;--the Seed of God, which is but one in all,
which is Christ in the male and in the female, which the promise is to.
Wait upon the Lord for the just to reign over the unjust,
and for the Seed of God to reign over the seed of the serpent, and be the head;
and that all that is mortal may die; for out of that will rise presumption.
So fare ye well, and God Almighty bless, and guide, and keep you in his wisdom.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
About this time Friends,
that were moved of the Lord to go to the steeple-houses and markets, to "`reprove sin,
and warn people of the day of the Lord,`" suffered much hardship from rude people,
and also from the magistrates; being commonly pulled down, buffeted, beaten,
and frequently sent to prison.
Wherefore I was moved to give forth the following expostulation,
to be spread amongst people, to show them,
how contrary they acted therein to the apostles`' doctrine and practice,
and to bring them to more moderation.
Thus it was:--

[.embedded-content-document.address]
--

"`Is it not better for you,
that have cast into prison the servants and children of the Lord God,
for speaking as they are moved, in steeple-houses or markets?
Is it not better, I say, for you to try all things, and hold fast that which is good?
Is it not of more honour and credit, to prove all things, and try all things,
than to pluck down in the steeple-houses, and pull off the hair of their heads,
and cast them into prison?
Is this an honour to your truth and gospel you profess?
Doth it not show that ye are out of the truth,
and are not ready to instruct the gainsayers?
Hath not the Lord said, '`He will pour out of his Spirit upon all flesh,
and his sons and his daughters shall prophesy; old men shall dream dreams,
and young men see visions; and on his handmaids he will pour forth of his Spirit?`'
Was not this prophecy in past ages stood against
by the wise learned men in their own wisdom,
and by the synagogue teachers?
Were not those haled out of the synagogues and temples,
who witnessed the Spirit poured forth upon them?
Doth not this show, that ye have not received the pourings forth of this Spirit upon you,
who fill the jails with so many sons and daughters,
and hold up such teachers as are bred up in learning at Oxford and Cambridge,
and are made by the will of man?
Doth not this show, that ye, who are bred up there,
who are made teachers by the will of man, and who persecute for prophesying,
are strangers to the Spirit that is '`poured forth upon sons and daughters,`'
by which Spirit they come to '`minister to the spirits that are in prison?`'
The Lord hath a controversy with you,
who are found prisoning and persecuting such as
the Lord hath poured forth of his Spirit upon.
Do not your fruits show, in all the nation where ye come; in towns, cities, villages,
and countries, that ye are the seedsmen made by the will of man, who sow to the flesh,
of which nothing but corruption is reaped?
Ye are looked upon, and your fruits, and that which may be gathered,
is seen by all that are in the light, as they pass through your countries, towns, cities,
and villages, that ye are all the seedsmen that have sown to the flesh.
Mark, and of this take notice, ye who are of that birth that is born of the flesh,
sow to your own, persecuting him that is born of the Spirit.
Sow to the Spirit, and of the Spirit reap life eternal; such ye cast into prison.
Do ye not hale out of the synagogues, persecute and beat in them, and knock down?
Are not these the works of the flesh?
Have not many been almost murdered and smothered in your synagogues?
Have not some been haled out of them, for but looking at the priest,
and after cast into prison?
Doth not all this make manifest what spirit ye are of, and your fruits to be of the flesh?
What pleasures and sports in every town are to be seen among your flocks,
that sow to the flesh and are born of it!

"`Whereas the ministers of the Spirit cried against such,
as '`sported in the daytime such as ate and drank,
and rose up to play such as lived wantonly upon earth in pleasures;
such as lived in fulness of bread and idleness; such as defile the flesh:
such did God overthrow and destroy,
and set them forth as examples to all them that after should live ungodly.
But are not the fruits of this reaped in every town?
Cannot we hence see, that here is sowing to the flesh?
Again, what scorning and scoffing, what mocking, derision, and strife!
What oaths and drunkenness, uncleanness and cursed speaking!
What lust and pride are seen in the streets!
These fruits we see are reaped of the flesh.
So here we see the seedsman, him that sows to this flesh,
of which nothing but corruption is reaped; as the countries, towns, cities,
and villages make manifest.
But the ministers of the Spirit, who sow to the Spirit, come to reap eternal life.
These discern the other seedsman, who sows to the flesh,
and of the flesh reaps corruption.
For the day hath manifested each seedsman, and what is reaped from each is seen;
glory be to the Lord God forever!
The ministers of the Spirit, who are born of the Spirit, sons and daughters,
who have the Spirit poured forth upon them,
and witness the promise of God fulfilled in them,
by the Spirit of God preach and minister to the Spirit in prison in every one,
in the sight of God, the Father of Spirits.
God`'s hand is turned against you all, that have destroyed God`'s creatures upon your lust.
God`'s hand is turned against you that have wronged by unjust dealing, defrauded,
and oppressed the poor,
and respected the persons of the proud (such as are in gay apparel);
and lend not your ear to the cry of the poor.
The Lord`'s hand is turned against you,
and his righteous judgment and justice upon you will be accomplished and repaid:
who shall have a reward, every one according to his works.

"`O! the abomination, the hypocritical profession that is upon the earth,
where God and Christ, Faith, Hope, the Holy Spirit, and truth are professed;
but the fear of God, and the faith that purifies and gives victory over the world,
are not lived in!
Doth it not appear, that the wisdom that rules in all those,
whom the seedsman that sows to the flesh, sows for, and who are born of the flesh,
is from below, earthly, sensual, and devilish; that their understanding is brutish,
and their knowledge natural, as the brute beasts?
For men and women in that state,
have not patience to speak one to the other of the Scriptures,
without much corruption and flesh appearing, yet they have a feigned humility,
a will-worship, and righteousness of self; but they own not the light,
which '`lighteth every man that cometh into the world,`' Christ Jesus,
the righteousness of God; which being owned, self, and the righteousness of self,
come to be denied.
Here is the humility that is contrary to the light, that is from below and feigned:
here is the wisdom that is earthly, sensual, and devilish;
for people can scarce speak one to another, without destroying one another,
prisoning and persecuting one another, when they speak of the Scriptures.
Now, this is the devilish wisdom, murdering and destroying:
this is not the wisdom that is from above, which is pure and peaceable;
gentle and easy to be entreated, full of mercy and good fruits.
Here all may read each seedsman, which hath each wisdom.
He that sows to the flesh, and is born of that, hath the wisdom that is earthly, sensual,
and devilish; he that sows to the Spirit, a minister of the Spirit,
hath the wisdom from above, which is pure, peaceable, gentle,
and easy to be entreated;--the wisdom by which all things were made and created.
Now is each wisdom discovered, and each seeds-man; the day, which is the light,
hath discovered them.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
I was also moved to give forth the following epistle to Friends,
to stir them up to be bold and valiant for the truth,
and to encourage them in their sufferings for it:--

[.embedded-content-document.epistle]
--

"`All Friends and brethren everywhere, now is the day of your trial,
now is the time for you to be valiant,
and to see that the testimony of the Lord doth not fall.
Now is the day for the exercise of your gifts, of your patience, and of your faith.
Now is the time to be armed with patience, with the light, with righteousness,
and with the helmet of salvation.
Now is the trial of the slothful servant, who hides his talent,
and will judge Christ hard.

"`Now, happy are they that can say, '`the earth is the Lord`'s and the fulness thereof,
and he gives the increase and therefore, who takes it from you?
Is`' it not the Lord still that suffers it?
For the Lord can try you as he did Job, whom he made rich, whom he made poor,
and whom he made rich again; who still kept his integrity in all conditions.
Learn Paul`'s lesson,`' in all states to be content;`' and have his faith,
that nothing is able to separate us from the love of God, which we have in Christ Jesus.`'
Therefore be rich in life, and in grace, which will endure, ye who are heirs of life,
and born of the womb of eternity, that noble birth,
that cannot stoop to that which is born in sin, and conceived in iniquity;
who are better bred and born; whose religion is from God,
above all the religions that are from below; and who walk by faith,
by that which God hath given you, and not by that which men make, who walk by sight,
from the Mass-Book to the Directory.
Such are subject to stumble and fall, who walk by sight and not by faith.
Therefore mind him that destroys the original of sin, the devil and his works,
and cuts off the entail of Satan, viz., sin;
who would have by entail an inheritance of sin
in men and women from generation to generation,
and pleads for it by all his lawyers and counsellors.
For though the law, which made nothing perfect, did not cut it off;
yet Christ being come destroys the devil and his works, and cuts off the entail of sin.
This angers all the devil`'s Lawyers and counsellors,
that Satan shall not hold sin by entail in thy garden,
in thy field, in thy temple, thy tabernacle.
So keep your tabernacles,
that there ye may see the glory of the Lord appear at the doors thereof.
And be faithful; for ye see,
what the worthies and valiants of the Lord attained unto by faith.
Enoch by faith was translated.
Noah by faith was preserved over the waters in his ark.
Abraham by faith forsook his father`'s house and religion,
and all the religions of the world.
Isaac and Jacob by faith followed his steps.
See also how Samuel, with other of the Lord`'s prophets, and David,
by faith were preserved to God, over God`'s enemies!
Daniel and the three children by faith escaped the lions and the fire,
and preserved their worship clean, and by it were kept over the worships of the world.
The apostles by faith travelled up and down the world,
were preserved from all the religions of the world,
and held forth the pure religion to the dark world, which they had received from God;
and likewise their fellowship was received from above,
which is in the gospel that is everlasting.
In this, neither powers, principalities, nor thrones, dominions nor angels,
things present, nor things to come, nor heights, nor depths, nor death, mockings,
nor spoiling of goods, nor prisons, nor fetters,
were able to separate them from the love of God, which they had in Christ Jesus.
And Friends, '`quench not the Spirit, nor despise prophesying,`' where it moves;
neither hinder the babes and sucklings from crying Hosanna;
for out of their months will God ordain strength.
There were some in Christ`'s day that were against such, whom he reproved;
and there were some in Moses`'s day, who would have stopped the prophets in the camp,
whom Moses reproved, and said, by way of encouragement to them, '`Would God,
that all the Lord`'s people were prophets!`' So I say now to you.
Therefore ye, that stop it in yourselves, do not quench it in others,
neither in babe nor suckling; for the Lord hears the cries of the needy,
and the sighs and groans of the poor.
Judge not that, nor the sighs and groans of the Spirit, which cannot be uttered,
lest ye judge prayer;
for prayer as well lies in sighs and groans to the Lord as otherwise.
Let not the sons and daughters, nor the hand-maidens be stopped in their prophesyings,
nor the young men in their visions, nor the old men in their dreams;
but let the Lord be glorified in and through all, who is over all, God blessed forever!
So every one may improve his talents, every one exercise his gifts,
and every one speak as the Spirit gives him utterance.
Thus every one may minister as he hath received the grace,
as a good steward to him that hath given it him;
so that all plants may bud and bring forth fruit to the glory of God;
'`for the manifestation of the Spirit is given to every one to profit withal.`'
See, that every one hath profited in heavenly things: male and female,
look into your own vineyards, and see what fruit ye bear to God;
look into your own houses, see how they are decked and trimmed, and see what odours,
myrrh, and frankincense ye have therein,
and what a smell and savour ye have to ascend to God, that he may be glorified.
Bring all your deeds to the light, which ye are taught to believe in by Christ,
your Head, the heavenly Man; and see how they are wrought in God.
Every male and female, let Christ dwell in your hearts by faith,
and let your mouths be opened to the glory of God the Father,
that he may rule and reign in you.
We must not have Christ Jesus, the Lord of life, put any more in a stable,
amongst the horses and asses; but he must now have the best chamber, the heart,
and the rude, debauched spirit must be turned out.
Therefore let Him reign, whose right it is, who was conceived by the Holy Ghost,
by which ye call him Lord, in which ye pray,
and have comfort and fellowship with the Father and with the Son.
Therefore know the triumph in it, and in God and his power (which the devil is out of),
and in the seed, which is first and last, the beginning and ending,
the top and corner-stone; in which is my love to you, and in which I rest--Your friend,

[.signed-section-signature]
G+++.+++ F.`"

[.postscript]
"`Postscript--And, Friends, be careful how ye set your feet among the tender plants,
that are springing up out of God`'s earth; lest ye tread upon them, hurt, bruise,
or crush them in God`'s vineyard.`"

--

After I had tarried two First-days at Swarthmore,
and had visited Friends in their meetings thereabouts, I passed into Westmorland,
in the same work, till I came to John Audland`'s, where there was a general meeting.
The night before I had a vision of a desperate creature, that was coming to destroy me,
but I got victory over it.
And next day in meeting time came one Otway, with some rude fellows.
He rode round about the meeting with his sword or rapier,
and would fain have got in through the Friends to me; but the meeting being great,
the Friends stood close, so that he could not easily come at me.
When he had rode about several times raging, and found he could not get in,
being limited by the Lord`'s power, he went away.
It was a glorious meeting, ended peaceably,
and the Lord`'s everlasting power came over all.
This wild man went home, became distracted, and not long after died.
I sent a paper to John Blaykling to read to him, while he lay ill,
showing him his wickedness; and he acknowledged something of it.

From hence, I went through Kendal, where a warrant had long lain to apprehend me;
and the constables seeing me, ran to fetch their warrant,
as I was riding through the town; but before they could come with it, I was gone past,
and so escaped their hands.

I travelled northwards, visiting Friends`' meetings, till I came to Strickland-head,
where I had a great meeting.
Most of the gentry of that country being gathered to a horse-race,
not far from the meeting, I was moved to go and declare the truth unto them;
and a chief-constable, that was there, also admonished them.
Our meeting was quiet, and the Lord was with us; and by his word and power,
Friends were settled in the eternal truth.

From hence we passed into Cumberland, where we had many precious living meetings.
After we had travelled to Gilsland, and had a meeting there, we came to Carlisle,
where they used to put Friends out of the town;
but there came a great flood while we were there, that they could not put us out;
so we had a meeting there on First-day.
After which we passed to Abbey-holm, and had a little meeting there.
This is a place, where I told Friends long before,
a great people would come forth to the Lord; which hath since come to pass,
and a large meeting is gathered to the Lord in those parts.

I passed hence to a general meeting at Langlands in Cumberland, which was very large;
for most of the people had so forsaken the priests,
that the steeple-houses in some places stood empty.
And John Wilkinson,^
footnote:[This was not that John Wilkinson who joined
with Storey in creating a schism in the Society.]
a preacher, I have often named before, who had three steeple-houses,
had so few hearers left, that, giving over preaching in them,
he first set up a meeting in his house, and preached there to them that were left.
Afterwards he set up a silent meeting (like Friends), to which came a few;
for most of his hearers were come to Friends.
Thus he held on till he had not past half a dozen left; the rest still forsaking him,
and coming to Friends.
At last, when he had so very few left,
he would come to Pardsey Crag (where Friends had a meeting of several hundreds of people,
who were all come to sit under the Lord Jesus Christ`'s teaching),
and he would walk about the meeting on First-days,
like a man that went about the commons to look for sheep.
During this time I came to Pardsey Crag meeting,
and he with three or four of his followers, that were yet left to him,
came to the meeting that day, and were all thoroughly convinced.
After the meeting, Wilkinson asked me two or three questions,
which I answered him to his satisfaction; and from that time he came amongst Friends,
became an able minister, preached the gospel freely,
and turned many to Christ`'s free teaching.
And after he had continued many years in the free ministry of Jesus, he died in 1675.

I had for some time felt drawings on my spirit to go into Scotland;
and had sent to Colonel William Osburn of Scotland, desiring him to come and meet me;
and he, with some others, came out of Scotland to this meeting.
After the meeting was over (which, he said,
was the most glorious one he ever saw in his life),
I passed with him and his company into Scotland; having Robert Widders with me,
a thundering man against hypocrisy, deceit, and the rottenness of the priests.

The first night we came into Scotland we lodged at an inn.
The innkeeper told us, an Earl lived about a quarter of a mile off,
who had a desire to see me; and had left word at his house,
that if ever I came into Scotland, he should send him word.
He told us there were three drawbridges to his house,
and that it would be nine o`'clock before the third bridge was drawn.
Finding we had time in the evening, we walked to his house.
He received us very lovingly; and said, he would have gone with us on our journey,
but he was previously engaged to go to a funeral.
After we had spent some time with him, we parted very friendly, and returned to our inn.
Next morning we travelled on, and passing through Dumfries came to Douglas,
where we met with some Friends; and thence passed to the Heads,
where we had a blessed meeting in the name of Jesus, and felt him in the midst.

Leaving Heads, we went to Badcow, and had a meeting there;
to which abundance of people came, and many were convinced;
amongst whom was one, called a lady.
From thence we passed towards the Highlands to William Osburn`'s house,
where we gathered up the sufferings of Friends, and the principles of the Scotch priests,
which may be seen in a book called _The Scotch Priests`' Principles._

Afterwards we returned to Heads, Badcow, and Garshore,
where the said Lady Margaret Hambleton was convinced;
who afterwards went to warn Oliver Cromwell and Charles
Fleetwood of the day of the Lord that was coming upon them.

On First-day we had a great meeting, and several professors came to it.
Now, the priests had frightened the people with the doctrine of election and reprobation,
telling them "`that God had ordained the greatest part of men and women for hell;
and that, let them pray, or preach, or sing, or do what they could,
it was all to no purpose,
if they were ordained for hell;--that God had a certain number elected for heaven,
let them do what they would, as David an adulterer, and Paul a persecutor,
yet elected vessels for heaven.
So the fault was not at all in the creature, less or more, but God had ordained it so.`"
I was led to open to the people the falseness and folly of their priests`' doctrines,
and showed how they had abused those Scriptures they brought and quoted to them,
as in Jude, and other places.
For whereas they said, there was no fault at all in the creature,
I showed them that they whom Jude speaks of, to wit, Cain, Korah, and Balaam, who,
he says, were ordained of old to condemnation, the fault was in them.
For did not God warn Cain and Balaam, and put the question to Cain, "`If thou doest well,
shalt thou not be accepted?`'
And did not the Lord bring Korah out of Egypt and his company?
yet did not he gainsay both God and his law, and his prophet Moses?
Here people might see that there was a fault in Cain, Korah, and Balaam,
and so there is in all that go in their ways.
For if they who are called Christians, resist the gospel, as Korah did the law;
if they err from the Spirit of God, as Balaam did, and do evil, as Cain did,
is not here a fault?
"`Which fault is in themselves, and is the cause of their reprobation, and not God.
Doth not Christ say, "`Go, preach the gospel to all nations?`"
Which is the gospel of salvation.
He would not have sent them into all nations, to preach the doctrine of salvation,
if the greatest part of men had been ordained for hell.
Was not Christ a propitiation for the sins of the whole world,
for those that become reprobates, as well as for the saints?
He died for all men, the ungodly as well as the godly, as the apostle bears witness,
2 Cor. 5:15; Rom. 5:6.
And he "`enlightens every man that cometh into the world,`"
that through him they might all believe.
And Christ bids them believe in the light; but all they that hate the light,
which Christ bids all believe in, are reprobated.
Again, "`the manifestation of the Spirit of God is given,
to every man to profit withal;`" but they that vex, quench, and grieve it,
are in the reprobation; and the fault is in them,
as it is also in them that hate his light.
The apostle says, "`The grace of God which brings salvation, hath appeared unto all men,
teaching us that, denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present world,`" Tit. 2:11-12.
Now when men and women live ungodly,
and in the lusts of the world, turn this grace of God into wantonness,
and walk despitefully against it, and so deny God, and the Lord Jesus Christ,
that bought them; the fault is in all such as thus turn the grace of God into wantonness,
and walk despitefully against that which would bring their salvation,
and save them out of the reprobation.
But the priests, it seems, can see no fault in such as deny God,
and the Lord Jesus Christ, that hath bought them--such as deny his light,
which they should believe in, and his grace, which should teach them to live godly,
and which should bring them their salvation.
Now all that believe in the light of Christ, as he commands, are in the election,
and sit under the teaching of the grace of God, which brings their salvation.
But such as turn this grace into wantonness, are in the reprobation;
and such as hate the light, are in the condemnation.
Therefore I exhorted all the people to believe in the light, as Christ commands,
and own the grace of God, their free teacher;
and it would assuredly bring them their salvation; for it is sufficient.
Many other Scriptures were opened concerning reprobation,
and the eyes of the people were opened; and a spring of life rose up among them.

These things soon came to the priests`' ears;
for the people that sat under their dark teachings, began to see light,
and to come into the covenant of light.
The noise was spread over Scotland, amongst the priests, that I was come thither;
and a great cry was among them, that all would be spoiled; for, they said,
I had spoiled all the honest men and women in England already,
so according to their own account, the worst were left to them.
Upon this they gathered great assemblies of priests together,
and drew up a number of curses to be read in their several steeple-houses,
that all the people might say "`Amen`" to them.
Some few of these I will here set down,
the rest may be read in the book before mentioned, of _The Scotch Priests`' Principles._

The first was, "`Cursed is he that saith,
every man hath a light within him sufficient to lead him to salvation;
and let all the people say, Amen.`"

The second, "`Cursed is he that saith, faith is without sin;
and let all the people say, Amen.`"

The third, "`Cursed is he that denieth the Sabbath-day;
and let all the people say, Amen.`"
^
footnote:[It is justly observed by a writer, not of the Society of Friends,
that these "`place the Presbyterian Christianity
of that day in a most unfavourable light,
and show how deeply it was imbued with a sour persecuting spirit of Popery.`"]

In this last they make the people curse themselves;
for on the Sabbath-day (which is the seventh-day of the week,
which the Jews kept by the command of God to them) they kept markets and fairs,
and so brought the curse upon their own heads.

As to the first, concerning the light, Christ saith, "`Believe in the light,
that ye may become children of the light;`" and "`he that believeth shall be saved;
he that believeth shall have everlasting life;
he that believeth passes from death to life, and is grafted into Christ.`"
And "`ye do well,`" said the apostle,
"`that ye take heed unto the light that shines in the dark place, until the day dawn,
and the day-star arise in your hearts.`"
So the light is sufficient to lead unto the day-star.

And as concerning faith, it is the gift of God; and every gift of God is pure.
The faith, which Christ is the author of, is precious, divine, and without sin.
This is the faith which gives victory over sin, and access to God;
in which faith they please God.
But they are reprobates themselves concerning this faith, and are in their dead faith,
who charge sin upon this faith under pain of a curse;
which faith gives victory over their curse, and returns it into their own bowels.

A company of Scots near Badcow, challenged a dispute with some of our Scotch Friends,
for with me they would not dispute;
so some of the Scotch Friends met them at the market-place.
The dispute was to be concerning the Sabbath-day,
and some other of their principles before-mentioned;
and I having got their principles and assertions,
showed the Friends where they might easily be overthrown, and a Scotch Friend, a smith,
overthrew them clearly.

There were two Independent churches in Scotland, in one of which many were convinced;
but the pastor of the other was in a great rage against truth and Friends.
They had their elders,
who sometimes would exercise their gifts amongst the church-members,
and were sometimes pretty tender;
but their pastor speaking so much against the light and us, the friends of Christ,
he darkened his hearers, so that they grew blind, and dry, and lost their tenderness.
He continued preaching against Friends, and against the light of Christ Jesus,
calling it natural; at last one day in his preaching, he cursed the light, and fell down,
as if dead, in his pulpit.
The people carried him out, and laid him upon a grave-stone,
and poured strong waters into him, which brought him to life again;
and they carried him home, but he was mopish.
After a while he stripped off his clothes, put on a Scotch plaid,
and went into the country amongst the dairy-women.
When he had stayed there about two weeks, he came home, and went into the pulpit again.
Whereupon the people expected some great manifestation or revelation from him; but,
instead thereof, he began to tell them what entertainment he had met with;
how one woman gave him skimmed-milk, another gave him butter-milk,
and another gave him good milk;
so the people were fain to take him out of the pulpit again, and carry him home.
He that gave me this account was Andrew Robinson, one of his chief hearers,
who came afterwards to be convinced, and received the truth.
He said he never heard that he recovered his senses again.
By this people may see what came upon him that cursed the light;
which Light is the Life in Christ, the Word; and it may be a warning to all others,
that speak evil against the Light of Christ.

Now were the priests in such a rage,
that they posted to Edinburgh to Oliver Cromwell`'s council there,
with petitions against me.
The noise was, "`that all was gone;`" for several Friends were
come out of England and spread over Scotland,
sounding the day of the Lord, preaching the everlasting gospel of salvation,
and turning people to Christ Jesus, who died for them,
that they might receive his free teaching.
After I had gathered the principles of the Scotch priests, and the sufferings of Friends,
and had seen the Friends in that part of Scotland settled, by the Lord`'s power,
upon Christ their foundation, I went to Edinburgh, and in the way came to Linlithgow;
where, lodging at an inn, the innkeeper`'s wife, who was blind,
received the word of life and came under the teaching of Christ Jesus, her Saviour.
At night there came in abundance of soldiers and some officers,
with whom we had much discourse; some were rude.
One of the officers said, "`he would obey the Turk`'s or Pilate`'s command,
if they should command him to guard Christ to crucify him.`"
So far was he from all tenderness, or sense of the Spirit of Christ,
that he would rather crucify the just, than suffer for or with the just;
whereas many officers and magistrates have lost their places,
before they would turn against the Lord and his Just One.

When I had stayed a while at Edinburgh, I went to Leith,
where many officers of the army came in with their wives, and many were convinced.
Among these Edward Billing`'s wife was one; she brought a great deal of coral in her hand,
and threw it on the table before me, to see whether I would speak against it or not.
I took no notice of it, but declared the truth to her, and she was reached.
There came in many Baptists, who were very rude, but the Lord`'s power came over them,
so that they went away confounded.
Then there came in another sort, and one of them said, "`he would dispute with me;
and for argument`'s sake, would deny there was a God.`"
I told him, "`he might be one of those fools that said in his heart, There is no God,
but he should know him in the day of his judgment.`"
So he went his way; and a precious time we had afterwards with several people of account;
and the Lord`'s power came over all.
William Osburn was with me.
Colonel Lidcot`'s wife and William Welch`'s wife, and several of the officers themselves,
were convinced.
Edward Billing and his wife at that time lived apart; and she being reached by truth,
and become loving to Friends, we sent for her husband, who came;
and the Lord`'s power reached unto them both, they joined in it,
and agreed to live together in love and unity, as man and wife.

After this we returned to Edinburgh, where many thousands were gathered together,
with abundance of priests among them, about burning a witch,
and I was moved to declare the day of the Lord amongst them.
When I had done, I went to our meeting, whither many rude people and Baptists came.
The Baptists began to Taunt with their logic and syllogisms;
but I was moved in the Lord`'s power to thrash their chaffy, light minds;
and showed the people that, after that fallacious way of discoursing,
they might make white seem black, and black white; as, that because a cock had two legs,
and each of them had two legs, therefore they were all cocks.
Thus they might turn any thing into lightness and vanity;
but it was not the way of Christ or his apostles, to teach, speak, or reason,
after that manner.
Hereupon those Baptists went their way, and after they were gone,
we had a blessed meeting in the Lord`'s power, which was over all.

I mentioned before, that many of the Scotch priests,
being greatly disturbed at the spreading of truth,
and the loss of their hearers thereby, were gone to Edinburgh,
to petition the council against me.
Now, when I came from the meeting to the inn where I lodged,
an officer belonging to the council brought me the following order:--

[.embedded-content-document.legal]
--

[.signed-section-context-open]
"`Thursday, the 8th of October, 1657, at his Highness`'s Council in Scotland.

[.salutation]
Ordered,

That George Fox do appear before the Council on Tuesday, the 13th of October next,
in the forenoon.

[.signed-section-signature]
E+++.+++ Dowsing, Clerk of the Council.

--

When he had delivered me the order, he asked me, "`whether I would appear or not?`"
I did not tell him whether I would or not;
but asked him "`if he had not forged the order:`" he said, "`no,
it was a real order from the council, and he was sent, as their messenger, with it.`"
When the time came I appeared, and was conducted into a large room,
where many great persons came and looked at me.
After a while the door-keeper had me into the council-chamber; and as I was going in,
he took off my hat.
I asked him "`why he did so, and who was there, that I might not go in with my hat on?`"
for I told him "`I had been before the Protector with it on.`"
But he hung it up, and had me in before them.
When I had stood a while, and they said nothing to me, I was moved of the Lord to say,
"`Peace be amongst you; wait in the fear of God,
that ye may receive his wisdom from above, by which all things were made and created;
that by it ye may all be ordered,
and may order all things under your hands to God`'s glory.`"
They asked me, "`what was the occasion of my coming into that nation?`"
I told them, "`I came to visit the seed of God,
which had long lain in bondage under corruption; and the intent of my coming was,
that all in the nation that professed the Scriptures, the words of Christ,
and of the prophets, and apostles, might come to the light, Spirit, and power,
which they were in, who gave them forth;
that so in and by the Spirit they might understand the Scriptures,
know Christ and God aright, and have fellowship with them, and one with another.`"
They asked me, "`whether I had any outward business there?`"
I said, "`nay.`"
Then they asked me how long I intended to stay in the country?
I told them "`I should say little to that; my time was not to be long,
yet in my freedom in the Lord, I stood in the will of him that sent me.`"
Then they bid me withdraw, and the door-keeper took me by the hand, and led me forth.
In a little time they sent for me again, and told me,
"`I must depart the nation of Scotland by that day seventh night.`"
I asked them, "`why, what had I done?
What was my transgression,
that they passed such a sentence upon me to depart out of the nation?`"
They told me, "`they would not dispute with me.`"
Then I desired them "`to hear what I had to say to them;`" but they said,
"`they would not hear me.`"
I told them, Pharaoh heard Moses and Aaron, and yet he was a heathen and no Christian,
and Herod heard John the Baptist; and they should not be worse than these.
But they cried, "`withdraw, withdraw.`"
Whereupon the door-keeper took me again by the hand, and led me out.
Then I returned to my inn, and continued still in Edinburgh,
visiting Friends there and thereabouts, and strengthening them in the Lord.
After a little time, I wrote a letter to the council,
to lay before them their unchristian dealing in banishing me, an innocent man,
that sought their salvation and eternal good; a copy of which letter here follows:--

[.embedded-content-document.letter]
--

[.letter-heading]
To the Council of Edinburgh

"`Ye that sit in council, and bring before your judgment seat the innocent, the just,
without showing the least cause what evil I have done,
or convicting me of any breach of law;
and afterward banish me out of your nation and country, without telling me why,
or what evil I had done; though I told you,
when ye asked me how long I would stay in the nation,
that my time was not long (I spoke it innocently), and yet ye banish me.
Will not all, think ye, that fear God, judge this to be wickedness?
Consider, did not they sit in council about Stephen, when they stoned him to death?
Did not they sit in council about Peter and John, when they haled them out of the temple,
and put them out of their council for a little season, and took council together,
and then brought them in again and threatened them,
and charged them to speak no more in that name?
Was not this to stop the truth from spreading in that time?
And had not the priests a hand in these things with the magistrates?
and in examining Stephen, when he was stoned to death?
Was not the council gathered together against Jesus Christ to put him to death?
and had not the chief priests a hand in it?
When they go to persecute the just, and crucify the just,
do they not then neglect judgment, and mercy, and justice,
and the weighty matters of the law, which is just?
Was not the apostle Paul tested up and down by the priests and the rulers?
Was not John the Baptist cast into prison?
are not ye doing the same work, showing what spirit ye are of?
Now do not ye show the end of your profession, the end of your prayers,
the end of your religion, and the end of your teaching,
who are now come to banish the truth, and him that is come to declare it unto you?
Doth not this show that ye are but in the words, out of the life, of the prophets,
Christ, and his apostles?
for they did not use such practice as to banish any.
How do ye receive strangers, which is a command of God among the prophets, Christ,
and the apostles?
Some by that means have entertained angels at unawares;
but ye banish one that comes to visit the Seed of God,
and is not chargeable to any of you.
Will not all that fear God, look upon this to be spite and wickedness against the truth?
How are ye like to love enemies, that banish your friend?
How are ye like to do good to them that hate you, when ye do evil to them that love you?
How are ye like to heap coals of fire on their heads that hate you,
and to overcome evil with good, when ye banish thus?
Do ye not manifest to all that are in the truth, that ye have not the Christian spirit?
How did ye do justice to me, when ye could not convict me of any evil, yet banish me?
This shows that truth is banished out of your hearts,
and ye have taken part against the truth with evil-doers; with the wicked,
envious priests, and stoners, strikers, and mockers in the streets; with these,
ye that banish, have taken part.
Whereas ye should have been a terror to these, and a praise to them that do well,
and succourers of them that are in the truth;
then might ye have been a blessing to the nation,
ye would not have banished him that was moved of the Lord to visit the Seed of God,
and thereby have brought your names upon record, and made them to stink in ages to come,
among them that fear God.
Were not the magistrates stirred up in former ages to persecute or banish,
by the corrupt priests?
and did not the corrupt priests stir up the rude multitude against the just in other ages?
Therefore are your streets like Sodom and Gomorrah.
Did not the Jews and the priests make the Gentiles`' minds envious against the apostles?
Who were they that would not have the prophet Amos to prophesy at the king`'s chapel;
but bid him fly his way?
And when Jeremiah was put in the prison, in the dungeon, and in the stocks,
had not the priests a hand with the princes in doing it?
Now see all that were in this work of banishing, prisoning, persecuting,
whether they were not all out of the life of Christ, the prophets, and apostles?
To the witness of God in you all I speak.
Consider whether they were not always the blind magistrates,
who turned their sword backward, that knew not their friends from their foes,
and so hit their friends?
Such magistrates were deceived by flattery.`"

[.signed-section-signature]
G+++.+++ F.

--

When this was delivered, and read amongst them, some of them, I heard,
were troubled at what they had done,
being made sensible that they would not be so served themselves.
But it was not long before they that banished me, were banished themselves,
or glad to get away; who would not do good in the day when they had power,
nor suffer others that would.

After I had spent some time among Friends at Edinburgh, and thereabouts,
I passed to Heads again, where Friends had been in great sufferings;
for the Presbyterian priests had excommunicated them,
and given charge that none should buy or sell, or eat or drink with them.
So they could neither sell their commodities, nor buy what they wanted;
which made it go very hard with some of them;
for if they had bought bread or other victuals of any of their neighbours,
the priests threatened them so with curses,
that they would run and fetch it from them again.
But Colonel Ashfield being a justice of peace in that country,
put a stop to the priests`' proceedings.
This Colonel Ashfield was afterwards convinced himself,
had a meeting settled at his house, declared the truth, and lived and died in it.

After I had visited Friends at Heads and thereaways, and had encouraged them in the Lord,
I went to Glasgow, where a meeting was appointed; but not one of the town came to it.
As I went into the city, the guard at the gates took me before the governor,
who was a moderate man.
Much discourse I had with him; but he was too light to receive the truth,
yet he set me at liberty; so I passed to the meeting.
But seeing none of the town`'s-people came, we declared truth through the town,
and so passed away; and having visited Friends in their meetings thereabouts,
returned towards Badcow.
Several Friends declared truth in their steeple-houses,
and the Lord`'s power was with them.
Once as I was going with William Osburn to his house,
there lay a company of rude fellows by the way-side, hid under the hedges and in bushes.
Seeing them, I asked him "`what they were?`"
"`O,`" said he, "`they are thieves.`"
Robert Widders, being moved to go and speak to a priest, was left behind,
intending to come after.
So I said to William Osburn, "`I will stay here in this valley,
and do thou go look after Robert Widders;`" but he was unwilling to go,
being afraid to leave me there alone, because of those fellows, till I told him,
"`I feared them not.`"
Then I called to them, asking them,
"`what they lay lurking there for,`" and I bid them come to me;
but they were loath to come.
I charged them to come up to me, or else it might be worse with them;
then they came trembling, for the dread of the Lord had struck them.
I admonished them to be honest, and directed them to the light of Christ in their hearts,
that by it they might see what an evil it was to follow after theft and robbery;
and the power of the Lord came over them.
I stayed there till William Osburn and Robert Widders came up,
and then we passed on together.
But it is likely that, if we two had gone away before,
they would have robbed Robert Widders when he had come after alone,
there being three or four of them.

We went to William Osburn`'s house,
where we had a good opportunity to declare the truth to several people that came in.
Then we went among the Highlanders, who were so devilish,
they had like to have spoiled us and our horses; for they ran at us with pitch-forks;
but through the Lord`'s goodness we escaped them, being preserved by his power.

Thence we passed to Stirling, where the soldiers took us up, and had us to the main-guard.
After a few words with the officers, the Lord`'s power coming over them,
we were set at liberty: but no meeting could we get amongst them in the town,
they were so closed up in darkness.
Next morning there came a man with a horse that was to run a race,
and most of the town`'s-people and officers went to see it.
As they came back from the race,
I had a brave opportunity to declare the day of
the Lord and his word of life amongst them.
Some confessed to it, and some`' opposed;
but the Lord`'s truth and power came over them all.

Leaving Stirling, we came to Burntisland,
where I had two meetings at one Captain Pool`'s house; one in the morning,
the other in the afternoon.
Whilst they went to dine, I walked to the sea-side, not having freedom to eat with them.
Both he and his wife were convinced, and became good Friends afterward,
and several officers of the army came in and received the truth.

We passed thence through several other places, till we came to Johnstons,
where were several Baptists that were very bitter, and came in a rage to dispute with us:
vain janglers and disputers indeed they were.
When they could not prevail by disputing, they went and informed the governor against us;
and next morning raised a whole company of foot, and banished me, and Alexander Parker,
also James Lancaster, and Robert Widders out of the town.
As they guarded us though the town,
James Lancaster was moved to sing with a melodious sound in the power of God;
and I was moved to proclaim the day of the Lord,
and preach the everlasting gospel to the people.
For they generally came forth, so that the streets were filled with them:
and the soldiers were so ashamed that they said,
"`they would rather have gone to Jamaica than have guarded us so.`"
But we were put into a boat with our horses, carried over the water, and there left.
The Baptists, who were the cause of our being thus put out of this town, were themselves,
not long after, turned out of the army;
and he that was then governor was discarded also when the king came in.

Being thus thrust out of Johnstons, we went to another market-town, where Edward Billing^
footnote:[Edward Billing was a faithful sufferer for the truth.
Henry Tell, in a letter to Margaret Fell, in 1660, mentions Friends being beat very sore,
and exceedingly abused in the streets.
"`They pulled me out of meeting,`" he says, "`beat me much,
knocked me down in the street, and tore all my coat.
Edward Billing and his wife were much abused,
he especially.`"
{footnote-paragraph-split}
Edward Billing was one of the three Friends,
who, in 1659, appeared before the bar of the House of Commons,
to present an address describing the sufferings of Friends,
and signed by 164 of the Society, wherein they make an offer of their own bodies,
person for person,
to lie in prison instead of such of their brethren as were then under confinement,
and might be in danger of their lives through extreme durance.
(See _Letters of Early Friends_, pp. 62-68.)
Although little or no apparent effect appeared to be produced
at the time in the House from the above-mentioned appeal,
it appears, from the journals of the Commons in the month following,
a committee was appointed,
"`to consider of the imprisonment of such persons who
continue committed for conscience sake,
and how, and in what manner they are, and continue committed,
together with the whole cause thereof, and how they may be discharged;
and to report the same to the Parliament.`"]
and many soldiers quartered.
We went to an inn, and desired to have a meeting in the town,
that we might preach the everlasting gospel amongst them.
The officers and soldiers said, we should have it in the town-hall;
but the Scotch magistrates in spite appointed a meeting
there that day for the business of the town.
When the officers of the soldiery understood this,
and perceived that it was done in malice,
they would have had us to go into the town-hall nevertheless.
But we told them, "`by no means,
for then the magistrates might inform the governor against them, and say,
they took the town-hall from them by force,
when they were to do their town business therein.`"
We told them, "`we would go to the market-place;`" they said,
"`it was market-day;`" we replied, "`it was so much the better;
for we would have all people to hear truth, and know our principles.`"
Alexander Parker went and stood upon the marketcross with a Bible in his hand,
and declared the truth amongst the soldiers and market-people; but the Scots,
being a dark, carnal people, gave little heed, and hardly took notice of what was said.
After a while I was moved of the Lord to stand up at the cross,
and declare with a loud voice the everlasting truth,
and the day of the Lord that was coming upon all sin and wickedness.
Whereupon the people came running out of the town-hall, and they gathered so together,
that at last we had a large meeting; for they sat in the court only for a pretence,
to hinder us from having the hall to meet in.
When the people were come away, the magistrates followed them.
Some walked by, but some stayed and heard; and the Lord`'s power came over all,
and kept all quiet.
"`The people were turned to the Lord Jesus Christ, who died for them,
and had enlightened them, that with his light they might see their evil deeds,
be saved from their sins by him, and come to know him to be their teacher.
But if they would not receive Christ and own him, it was told them, that this light,
which came from him, would be their condemnation.`"

Several of them were made loving to us, especially the English people,
and some came afterwards to be convinced.
But there was a soldier that was very envious against us; he hated both us and the truth,
spoke evil of it, and very despitefully against the light of Christ Jesus,
to which we bore testimony.
Mighty zealous he was for the priests and their hearers.
As this man was hearing the priest, holding his hat before his face,
while the priest prayed, one of the priest`'s hearers stabbed him to death;
so he who had rejected the teachings of the Lord Jesus Christ,
and cried down the servants of the Lord,
was murdered amongst them whom he had so cried up, and by one of them.

We travelled from this town to Leith, warning and exhorting people, as we went,
to turn to the Lord.
At Leith the innkeeper told me, that the council had granted warrants to apprehend me,
"`because I was not gone out of the nation, after the seven days were expired,
that they had ordered me to depart in.`"
Several friendly people also came and told me the same; to whom I said,
"`What do ye tell me of their warrants against me?
if there were a cart-load of them I do not heed them,
for the Lord`'s power is over them all.`"

I went from Leith to Edinburgh again,
where they said the warrants from the council were out against me.
I went to the inn where I had lodged before, and no man offered to meddle with me.
After I had visited Friends in the city, I desired those that travelled with me,
to get ready their horses in the morning, and we rode out of town together;
there were with me at that time Thomas Bawlinson, Alexander Parker, and Robert Widders.
When we were out of town, they asked me, "`whither I would go?`"
I told them it was upon me from the Lord to go back again to
Johnstons (the town out of which we had been lately thrust),
to set the power of God and his truth over them also.
Alexander Parker said,
"`he would go along with me;`" and I wished the other two to stay at a town,
about three miles from Edinburgh, till we returned.
Then Alexander and I got over the water, about three miles across,
and rode through the country; but in the afternoon,
his horse being weak and not able to hold up with mine,
I put on and got into Johnstons just as they were drawing up the bridges;
the officers and soldiers never questioning me.
I rode up the street to Captain Davenport`'s house, from which we had been banished.
There were many officers with him; and when I came amongst them,
they lifted up their hands, wondering that I should come again; but I told them,
"`the Lord God had sent me amongst them again;`" so they went their way.
The Baptists sent me a letter, by way of challenge, "`to discourse with me next day.`"
I sent them word, "`I would meet them at such a house, about half a mile out of the town,
at such an hour.`"
For I considered, if I should stay in town to discourse with them, they might,
under pretence of discoursing with me, have raised men to put me out of the town again,
as they had done before.
At the time appointed I went to the place, Captain Davenport and his son accompanying me,
where I stayed some hours, but not one of them came.
While I stayed there waiting for them, I saw Alexander Parker coming; who,
not being able to reach the town, had lain out the night before;
and I was exceedingly glad that we were met again.

This Captain Davenport was then loving to Friends;
but afterwards coming more into obedience to truth, he was turned out of his place,
for not putting off his hat, and for saying Thou and Thee to them.

When we had waited beyond reasonable ground to expect any of them coming, we departed;
and Alexander Parker being moved to go again to the town,
where we had the meeting at the market-cross,
I passed alone to Lieutenant Foster`'s quarters,
where I found several officers that were convinced.
From thence I went up to the town, where I had left the other two Friends,
and we went back to Edinburgh together.

When we were come to the city, I bid Robert Widders follow me;
and in the dread and power of the Lord we came up to the first two sentries;
and the Lord`'s power came so over them, that we passed by them without any examination.
Then we rode up the street to the market-place,
by the main-guard out at the gate by the third sentry, and so clear out at the suburbs,
and there came to an inn and set up our horses, it being the seventh-day of the week.
Now I saw and felt that we had rode, as it were, against the cannon`'s mouth,
or the sword`'s point;
but the Lord`'s power and immediate hand carried us over the heads of them all.
Next day I went to the meeting in the city, Friends having notice that I would attend it.
There came many officers and soldiers to it, and a glorious meeting it was;
the everlasting power of God was set over the nation,
and his Son reigned in his glorious power.
All was quiet, and no man offered to meddle with me.
When the meeting was ended, and I had visited Friends,
I came out of the city to my inn again; and next day, being the second-day of the week,
we set forward towards the borders of England.

As we travelled along the country I spied a steeple-house, and it struck at my life.
I asked "`what steeple-house it was,`" and was answered, that it was Dunbab.
When I came thither, and had put up at an inn, I walked to the steeple-house,
having a friend or two with me.
When we came into the yard, one of the chief men of the town was walking there.
I spoke to one of the friends that were with me, to go to him and tell him,
"`that about nine next morning there would be a meeting
there of the people of God called Quakers;
of which we desired he would give notice to the people of the town.`"
He sent me word, "`that they were to have a lecture there at nine;
but that we might have our meeting there at eight, if we would.`"
We concluded so, and desired him to give notice of it.
Accordingly in the morning both poor and rich came;
and there being a captain of horse quartered in the town, he and his troopers came also,
so that we had a large meeting; and a glorious one it was,
the Lord`'s power being over all.
After some time the priest came, and went into the steeplehouse;
but we being in the yard, most of the people stayed with us.
Friends were so full, and their voices so high in the power of God,
that the priest could do little in the steeple-house, but came quickly out again,
stood a while, and then went his way.
I opened to the people, "`where they might find Christ Jesus, turned them to the light,
which he had enlightened them withal, that in the light they might see Christ,
that died for them, turn to him, and know him to be their Saviour and free teacher.
I let them see, that all the teachers they had hitherto followed, were hirelings,
who made the gospel chargeable; showed them the wrong ways they had walked in,
in the night of apostacy, directed them to Christ, the new and living way to God;
manifested unto them,
how they had lost the religion and worship which Christ set up in spirit and truth,
and had hitherto been in the religions and worships of men`'s making and setting up.
After I had turned the people to the Spirit of God,
which led the holy men of God to give forth the Scriptures; and showed them,
that they must also come to receive, and be led by,
the same Spirit in themselves (a measure of which was given unto every one of them),
if ever they came to know God and Christ, and the Scriptures aright;
perceiving the other Friends that were with me
to be full of the power and word of the Lord,
I stepped down,
giving way for them to declare what they had from the Lord unto the people.`"
Towards the latter end of the meeting some professors began to jangle;
whereupon I stood up again, and answered their questions,
so that they seemed to be satisfied, and our meeting ended in the Lord`'s power,
quiet and peaceable.
This was the last meeting I had in Scotland;
the truth and the power of God was set over that nation, and many,
by the power and Spirit of God, were turned to the Lord Jesus Christ,
their Saviour and teacher, whose blood was shed for them;
and there is since a great increase, and great there will be in Scotland.
For when first I set my horse`'s feet upon Scottish ground,
I felt the Seed of God to sparkle about me, like innumerable sparks of fire.
Not but that there is abundance of thick, cloddy earth of hypocrisy and falseness above,
and a briary, brambly nature, which is to be burnt up with God`'s Word,
and ploughed up with his spiritual plough,
before God`'s Seed brings forth heavenly and spiritual fruit to his glory.
But the husbandman is to wait in patience.
