== Chapter XII.

[.chapter-synopsis]
* 1657-1659.
* George Fox journeys from Scotland to England
* dissuades a person from setting up a college at Durham to make ministers
* has a meeting with Rice Jones and his people
* attends a general Yearly Meeting for the whole nation, held at John Crook`'s, which continued three days
* address to Friends in the ministry
* disputes with a Jesuit
* writes to Lady Claypole
* writes to Cromwell respecting the fast on account of persecution abroad, whilst there was much of it at home
* writes a reproof to Parliament for their hypocrisy
* speaks to the Protector in Hampton-Court Park about Friends`' sufferings
* the Protector invites Fox to his house
* he goes next day, but the Protector being sick he does not see him
* the Protector died soon after
* writes to encourage Friends to faithfulness
* has a foresight of the King`'s restoration long before the event occurred, as well as several others
* Friends are disseized of their copyhold lands for refusing to swear
* cautions Friends to avoid plots, etc.
* against bearing arms
* great places in the army are offered to Friends, but invariably refused
* priest Townsend fails to substantiate his charge of error and blasphemy against George Fox, and is signally defeated
* George Fox`'s vision of the city of London is realized
* he gives a final warning to those in authority before their overthrow.

From Dunbar we came to Berwick, where we were questioned a little by the officers;
but the governor was loving towards us; and in the evening we had a little meeting,
in which the power of the Lord was manifested over all.

Leaving Berwick, we came to Morpeth, and so through the country, visiting Friends,
to Newcastle, where I had been once before.
The Newcastle priests had written many books against us; and one Ledger,
an alderman of the town, was very envious against truth and Friends.
He and the priests had said, "`the Quakers would not come into any great towns,
but lived in the Fells, like butterflies.`"
So I took Anthony Pearson with me, and went to this Ledger,
and several others of the aldermen, desiring to have a meeting amongst them,
seeing they had written so many books against us, for we were now come, I told them,
into their great town.
But they would not allow we should have a meeting,
neither would they be spoken to withal, save only this Ledger and one other.
I queried, "`had they not called Friends butterflies, and said,
we would not come into any great towns?
and now we were come into their town, they would not hear us,
though they had printed books against us;
'`Who are the butterflies now?`'`" said I. Then Ledger began to plead for the Sabbath-day;
but I told him they kept markets and fairs on that which was the Sabbath-day,
for that was the seventh day of the week; whereas that day,
which the professed Christians now met on, and call their Sabbath,
is the first day of the week.
As we could not have a public meeting among them,
we got a little one among Friends and friendly people, at Gateshead;
where a meeting is continued to this day, in the name of Jesus.
As I was passing by the market-place, the power of the Lord rose in me,
"`to warn them of the day of the Lord, that was coming upon them.`"
And not long after, all those priests of Newcastle and their profession, were turned out,
when the king came in.

From Newcastle we travelled through the countries,
having meetings and visiting Friends as we went, in Northumberland and Durham.
A very good one we had at Lieutenant Dove`'s,
where many were turned to the Lord and his teaching.
After the meeting I went to visit a justice of peace, a very sober, loving man,
who confessed to the truth.

Thence we came to Durham, where was a man come from London, to set up a college there,
to make ministers of Christ, as they said.
I went, with some others, to reason with him, and to let him see,
"`that to teach men Hebrew, Greek, and Latin, and the seven arts,
which were all but the teachings of the natural man,
was not the way to make them ministers of Christ.
For the languages began at Babel; and to the Greeks, that spoke Greek,
as their mother-tongue, the preaching of the cross of Christ was foolishness;
and to the Jews, that spoke Hebrew as their mother-tongue, Christ was a stumbling-block.
The Romans, who had the Latin, persecuted the Christians; and Pilate,
one of the Roman governors, set Hebrew, Greek, and Latin over Christ,
when he crucified him.
So he might see the many languages began at Babel, and they set them above Christ,
the Word, when they crucified him.
John the divine, who preached the Word, that was in the beginning, said,
'`that the beast and the whore have power over tongues and languages,
and they are as waters.`'
Thus I told him he might see,
the whore and beast have power over the tongues and the
many languages which are in mystery Babylon;
for they began at Babel;
and the persecutors of Christ Jesus set them over him,
when he was crucified by them;
but he is risen above them all, who was before them all.
'`Now,`' said I, to this man,
'`dost thou think to make ministers of Christ by these natural,
confused languages, which sprung from Babel, are admired in Babylon,
and set above Christ, the Life, by a persecutor?`' O no!`"
The man confessed to many of these things.
Then we showed him further, "`that Christ made his ministers himself,
gave gifts unto them, and bid them '`pray to the Lord of the harvest,
to send forth labourers.`'
And Peter and John,
though unlearned and ignorant (as to school-learning) preached Christ Jesus, the Word,
which was in the beginning, before Babel was.
Paul also was made an apostle, not of man, nor by man,
neither received he the gospel from man, but from Jesus Christ, who is the same now,
and so is his gospel, as it was at that day.`"
When we had thus discoursed with the man, he became very loving and tender; and,
after he had considered further of it, declined to set up his college.

From Durham we went to Anthony Pearson`'s: thence into Cleveland,
passed through Yorkshire to the further end of Holderness, and had mighty meetings,
the Lord`'s power accompanying us.

After we left Anthony Pearson`'s, we went by Hull and Pontefract,
to George Watkinson`'s house, and visited most of the meetings in those parts,
till we came to Scale-house, and so to Swarthmore;
the everlasting power and arm of God carrying us through and preserving us.
After I had visited Friends thereaways, I passed into Yorkshire again, and Cheshire,
and so through other counties into Derbyshire and Nottinghamshire:
glorious meetings we had, the Lord`'s presence being with us.

At Nottingham I sent to Rice Jones, desiring him to make his people acquainted,
that I had something to say to them from the Lord, He came and told me,
"`many of them lived in the country, and he could not tell how to send to them.`"
I told him, "`he might acquaint those about the town of it,
and send to as many in the country as he could.
Next day we met at the castle, there being about fourscore people,
to whom I declared the truth for about two hours; and the Lord`'s power was over them all,
so that they were not able to open their mouths in opposition.
When I had done, one of them asked me a question, which I was loath to answer,
for I saw it might lead to dispute, and I was unwilling to go into jangling,
for some of the people were tender; yet I could not well tell how to escape it.
Wherefore I answered the question, and was moved forthwith to speak to Rice Jones,
and lay before him,
"`that he had been the man that had scattered such as had been tender,
and some that had been convinced, and had been led out of many vanities of the world,
which he had formerly judged; but now he judged the power of God in them, and they,
being simple, turned to him; and so he and they were turned to be vainer than the world:
for many of his followers were become the greatest
foot-ball players and wrestlers in the country.
I told him, it was the serpent in him, that had scattered,
and done hurt to such as were tender towards the Lord.
Nevertheless, if he waited in the fear of God, for the Seed of the woman, Christ Jesus,
to bruise the serpent`'s head in him, that had scattered and done the hurt,
he might come to gather them again by this heavenly Seed;
though it would be a hard work for him to gather them
again out of those vanities he had led them into.`"
At this Rice Jones said,
"`Thou liest, it is not the Seed of the woman that bruises the serpent`'s head.`"
"`No!`" said I, "`what is it then?`"
"`I say it is the law,`" said he.
"`But,`" said I, "`the Scripture, speaking of the Seed of the woman, saith,
'`It shall bruise thy head, and thou shalt bruise his heel.`'
Now, hath the law an heel,`" said I, "`to be bruised?`"
Then Rice Jones and all his company were at a stand,
and I was moved in the power of the Lord to speak to him, and say, "`This Seed,
Jesus Christ, the Seed of the woman, which should bruise the serpent`'s head,
shall bruise thy head, and break you all to pieces.`"
Thus did I leave on the heads of them the Seed, Christ;
and not long after he and his company scattered to pieces,
several of whom came to be Friends, and stand to this day.
Many of them had been convinced about eight years before,
but had been led aside by this Rice Jones; for they denied the inward cross,
the power of God, and so went into vanity.
It was about eight years since I had been formerly amongst them;
in which time I was to pass over them, and by them,
seeing they had slighted the Lord`'s truth and power,
and the visitation of his love unto them.
But now I was moved to go to them again, and it was of great service,
for many of them were brought to the Lord Jesus Christ, and were settled upon him,
sitting down under his teaching and feeding, where they were kept fresh and green;
and the others that would not be gathered to him, soon after withered.
This was that Rice Jones who some years before had said, "`I was then at the highest,
and should fall.`"
But, poor man! he little thought how near his own fall was.

We left Nottingham, and went into Warwickshire,
and thence passing through some parts of Northamptonshire and Leicestershire,
visiting Friends, and having meetings with them as we travelled, came into Bedfordshire,
where we had large gatherings in the name of Jesus.
After some time we came to John Crook`'s house,
where a general Yearly Meeting for the whole nation was appointed to be held.^
footnote:[The first Yearly Meeting of the Society appears to have been held in 1658,
at Scalehouse, or Scarhouse, about three miles from Skipton.
At that meeting, the expenses incurred by the early missions being considerable,
the subject of the visits of Friends "`beyond the sea,`" claimed much attention,
and it was agreed to recommend general collection in aid of these gospel missions.
An epistle was issued to that effect, and the appeal was liberally responded to,
and considering the value of money at that period, a large amount was raised.
The epistle, with particulars of the collection and its disbursement,
may be seen in Bowden`'s _History of friends in America,_ vol. i., p. 58-60.
{footnote-paragraph-split}
Yearly Meetings were held
in different parts of England to the number of twenty-six,
at which were reported the number of prisoners;
the various sufferings on account of the Truth; those who died for it;
and the number of ministers deceased.
The affairs of truth were also considered,
and the members of the church had blessed opportunities
of heavenly correspondence and fellowship,
one with another.
For full particulars of the setting up of General and Yearly Meetings,
and of the institution and objects of the Discipline in the Society,
see _Letters, etc, of Early Friends,_ part ii., pp. 275-353.]
This meeting lasted three days,
and many Friends from most parts of the nation came to it;
so that the inns and towns around were filled, for many thousands of people were at it.
And although there was some disturbance by rude people that had run out from truth;
yet the Lord`'s power came over all, and a glorious meeting it was.
The everlasting gospel was preached, and many received it,
which brought life and immortality to light in them, and shined over all.

I was moved by the power and Spirit of the Lord, to open unto them "`the promise of God,
that it was made to the Seed, not to seeds, as many, but to One, which Seed was Christ;
and that all people, both male and female, should feel this Seed in them,
which was heir of the promise; that so they might all witness Christ in them,
the hope of glory, the mystery, which had been hid from ages and generations,
which was revealed to the apostles, and is revealed again now,
after this long night of apostacy.
So that all might come up into this Seed, Christ Jesus, and walk in it,
and sit down together in the heavenly places in Christ Jesus,
who was the foundation of the prophets and apostles, and the rock of ages;
and is our foundation now.
All sitting down in him, sit down in the substance, the first and the last,
that changes not, the Seed that bruises the serpent`'s head, and was before he was,
who ends all types, figures, and shadows, and is the substance of them all;
in whom there is no shadow.`"
Now these things were upon me to open unto all,
that they might mind and see what it is they sit down in.

"`For, First, They that sit down in Adam in the full, sit down in misery, in death,
in darkness, and corruption.

"`Secondly, They that sit down in types, figures, and shadows,
and under the first priesthood, law, and covenant,
sit down in that which must have an end, and which made nothing perfect.

"`Thirdly, They that sit down in the apostacy, that hath got up since the apostles`' days,
sit down in spiritual Sodom and Egypt, and are drinking of the whore`'s cup,
under the beast`'s and dragon`'s power.

"`Fourthly, They that sit down in the state in which Adam was before he fell,
sit down in that which may be fallen from; for he fell from that state,
though it was perfect.

"`Fifthly, They that sit down in the prophets, sit down in that which must be fulfilled;
and they that sit down in the fellowship of water, bread, and wine,
these being temporal things, sit down in that which is short of Christ,
and of his baptism.

"`Sixthly, To sit down in a profession of all the Scriptures,
from Genesis to Revelations, and not to be in the power and Spirit which they were in,
that gave them forth; that was to be turned away from,
by them that came into the power and Spirit which they
were in that gave forth the Scriptures.

"`Seventhly, They that sit down in heavenly places in Christ Jesus,
sit down in him that never fell nor ever changed.
Here is the safe sitting for all his elect, his church, his spiritual members,
of which he is the living head, his living stones, the household of faith;
of which house he is the corner-stone, that stands and abides all weathers.
'`For,`' as the apostle said, '`he hath quickened us, '`who were dead in sins and trespasses,
etc. and made us to sit together in heavenly places in Christ Jesus;
that in ages to come he might show the exceeding riches of his grace,
in his kindness towards us, through Jesus Christ.`'
Now, the ages are come,
that his kindness and exceeding riches towards us through Jesus Christ,
are truly manifested in us, as in the apostles`' days, even in us,
who have been dead in sins and trespasses as they were, but now are quickened,
and made to sit together in heavenly places in Christ Jesus, the First and the Last,
by whom all things were created; who is ascended above all, and is over all,
and whose glorious presence is now known.
All that sit down here in Christ Jesus, see where all other people sit, and in what.
The promise of God being to the Seed, which is one, Christ Jesus,
every man and woman must come to witness this Seed, Christ in them,
that they may be heirs of the promise; and inheriting that, they will inherit substance.
These things were largely declared of; the state of the church,
the state of the false church since the apostles`' days, opened;
and how the true church fled into the wilderness; and the state of the false prophets,
which Christ said should come, and John saw were come,
and how all the world wondered after them;
how they had filled the world with false doctrines, ways, worships, and religions;
and how the everlasting gospel was now preached again to all nations, kindreds, tongues,
and people; for all they had drunk the whore`'s cup, and she was over them,
and sat upon them.
In this night of apostacy, the pure religion and worship in Spirit,
which was in the apostles`' days, the way of life and living faith,
and the power and Holy Ghost were lost;
but now they came to be set up again by Christ Jesus,
his messengers and ministers of the gospel, as in the apostles`' days.
For as Christ sent his disciples to go and preach the gospel in all the world,
and after that the false prophets and antichrists went over the world,
and preached their false doctrines and traditions, and heathenish and Jewish rudiments:
so now again, the everlasting gospel must be preached to all nations,
and to every creature, that they may come into the pure religion,
to worship God in Spirit and in truth, that they may know Christ Jesus, their way to God,
to be the author of their faith, and receive the gospel from heaven, and not from men;
in which gospel, received from heaven, is the heavenly fellowship,
which is a mystery to all the fellowships in the world.`"
Now after these things had been largely opened,
with many other things concerning Christ Jesus and his kingdom,
and the people were turned to the divine light of Christ, and his Spirit,
by which they might come both to know God and Christ, and the Scriptures,
and to have fellowship with them, and one with another in the same Spirit,
I was moved to declare and open many other things to
those Friends who had received a part of the ministry,
concerning the exercise of their spiritual gifts in the church; which,
being taken in writing by one that was present, was after this manner:--

[.embedded-content-document.epistle]
--

[.salutation]
"`Friends,

"`Take heed of destroying that which ye have begotten;
for that which destroys, goes out, and is the cast-away.
And though that be true, yea, and may be the pure truth which such a one speaks,
yet if he doth not remain in that, and live in that in his own particular, but goes out,
the same which he is gone out from, cometh over him.
So that which calms and cools the spirits, goes over the world, and brings to the Father,
to inherit the life eternal: and reaches to the spirits in prison in all.
Therefore in the living, immoveable word of the Lord God dwell,
and in the renown thereof; and remain on the foundation that is pure, and that is sure:
for whosoever goes out from the pure, and ministers not in and from that,
comes to an end, and doth not remain; though he may have had a time,
and may have been serviceable for a time, while he lived in the thing.

"`Take heed of many words; what reacheth to the life, settles in the life.
That which cometh from the life, and is received from God, reaches to the life,
and settles others in the life: for the work is not now as it was at first;
the work now is, to settle and stay in the life.
For as Friends have been led to minister in the power, and the power hath gone through,
so that there hath grown an understanding among both people of the world and Friends;
so Friends must be kept in the life which is pure,
that with that they may answer the pure life of God in others.
If Friends do not live in the pure life which they speak of,
to answer the life in those they speak to, the other part steps in;
and so there comes up an outward acquaintance, and such let that come over them.
But as every one is kept living in the life of God, over all that which is contrary,
they are in their places; then they do not lay hands on any suddenly,
which is the danger now; for if any one do, he may lose his discerning,
and may lay hands on the wrong part, and so let the deceit come too near him;
and the deceit will steal over, so that it will be a hard thing for him to overcome it.
There is no one who strikes his fellow servants,
but first he is gone from the pure in his own particular;
for when he goeth from the light he is enlightened withal, then he strikes;
and then he hath his reward; the light which he is gone from, Christ,
comes and gives him his reward.
This is the state of the evil servants; the boisterous, the hasty, and rash,
beget nothing to God; but the life, which doth reach the life,
is that which begets to God.
When all are settled in the life, they are in that which remains forever:
and what is received there, is received from the Lord;
and what one receiveth from the Lord, he keepeth; and so he sitteth still, and cool,
and quiet in his own spirit, and gives it forth as he is moved; but to the harlots,
judgment.

"`Friends, this is the word of the Lord to you all,
be watchful and careful in all meetings ye come into;
for where Friends are sitting together in silence,
they are many times gathered into their own measures.
When a man is come newly out of the world, from ministering to the world`'s people,
he cometh out of the mire; and then he had need take heed that he be not rash.
For now, when he comes into a silent meeting, that is another state; then he must come,
and feel his own spirit, how it is, when he comes to them that sit silent.
If he be rash, they will judge him, that having been in the world, and amongst the world,
the heat is not yet off him.
For he may come in the heat of his spirit out of the world;
whereas the others are still and cool;
and his condition in that not being agreeable to theirs, he may rather do them hurt,
by begetting them out of the cool state into the heating state,
if he be not in that which commands his own spirit, and gives him to know it.

"`There is a great danger too in travelling abroad in the world.
The same power that moves any to go forth, is that which must keep them.
For it is the greatest danger to go abroad, except a man be moved of the Lord,
and go in the power of the Lord; for then, he keeping in the power,
is kept by it in his journey, and in his work;
and it will enable him to answer the transgressed, and keep above the transgressor.
Every one feeling the danger to his own particular in travelling abroad,
there the pure fear of the Lord will be placed, and kept in.
Though they that travel may have openings when they are abroad, to minister to others,
yet, for their own particular growth,
they must dwell in the life which doth open;
and that will keep down that which would boast.
For the minister comes into the death to that which is in the death and in prison,
and so returns up again into the life, and into the power, and into the wisdom,
to preserve him clean.

"`This is the word of the Lord God to you all;
feel that ye stand in the presence of the Lord: for every man`'s word shall be his burden;
but the Word of the Lord is pure, and answers the pure in every one.
The Word of the Lord is that which was in the beginning, and brings to the beginning.
It is a hammer, to beat down the transgressor (not the transgressed),
and as a fire to burn up that which is contrary to it.
Friends, come into that which is over all the spirits of the world,
fathoms all the spirits of the world, and stands in the patience; with that,
ye may see where others stand, and reach that which is of God in every one.
Here is no strife, no contention, out of transgression; for he that goeth into strife,
and into contention, is from the pure Spirit.
For where any goeth into contention, if anything hath been begotten by him before,
then that contentious nature doth get ahead, spoileth that which was begotten,
and quencheth his own prophesying.
So if that which would arise into strife,
be not subjected by the power in the particular, that is dangerous.

"`If any have a moving to any place, and have spoken what they were moved of the Lord,
let them return unto their habitation again, and live in the pure life of God,
and in the fear of the Lord;
so will ye be kept in the life--in the solid and seasoned spirit,
and preach as well in life,
as with words (for none must be light or wild). For the Seed of God is weighty,
brings to be solid, and leads into the wisdom of God,
by which the wisdom of the creation is known.
But if that part be up, which runs into imaginations, and that part be standing,
in which the imaginations come up,
and the pure spirit be not thoroughly come up to rule and reign, then that will run out,
that will glory, boast, and vapour;
and so will such a one spoil that which opened to him: this is for condemnation.
Let every one mind that, which feels through and commands his spirit,
whereby every one may know what spirit he is of; for he should first try his own spirit,
and then he may try others; he should first know his own spirit,
and then he may know others.
Therefore that which doth command all these spirits,
where the heats and burnings come in and get up, in that wait,
which chains them down and cools: that is the elect, the heir of the promise of God.
For no hasty, rash, brittle spirits (though they have prophecies) have held out,
and gone through, they not being subjected in the prophecy.
The earthly will not abide, for it is brittle;
and in that state the ministry was another`'s, not the Son`'s;
for the Son hath life in himself, and the Son hath the power,
which man being obedient to, he may be serviceable; but if he go from the pure power,
he falls, and abuses it.
Therefore let your faith stand in the pure power of the Lord God, and do not abuse it;
but let that search through, and work through;
and let every one stand in the power of the Lord, which reacheth the Seed of God;
which is the heir of the promise of life without end.
Let none be hasty to speak; for ye have time enough,
and with an eye ye may reach the witness: neither let any be backward when ye are moved;
for that brings destruction.

"`Now, truth hath an honour in the hearts of those who are not Friends;
so that all Friends being kept in the truth, they are kept in the honour,
they are honourable, for that will honour them; but if any lose the power,
they lose the life, they lose their crown, they lose their honour, they lose the cross,
which should crucify them, and they crucify the just; and by losing the power,
the Lamb comes to be slain.
And as it is here, so will it be in other nations; for all Friends, here and there,
are as one family; the seed, the plants, they are as a family.
Now all being kept in that which subjects all, and keeps all under, to wit,
the Seed itself, the life itself, that is the heir of the promise;
that is the bond of peace; for there is the unity in the Spirit with God,
and with one another.
For he that is kept in the life, hears God, and sees man`'s condition;
and with that he answers the life in others, that hear God also;
thus one Friend that is come into that, comprehends the world.
But that which Friends speak, they must live in; so may they expect,
that others may come into that which they speak, to live in the same.
For the power of the Lord God hath been abused by some,
and the worth of truth hath not been minded; there hath been a trampling on,
and marring with the feet, and that abuseth the power.
But now every Friend is to keep in the power, and to take heed to it;
for that must be kept down, which would trample and mar with the feet,
and the pure life and power of God is to be lived in over that,
that none with the feet may foul or mar,
but every one may be kept in the pure power and life of the Lord.
Then the water of life cometh in; then he that ministereth, drinketh himself,
and giveth others to drink.

"`When any shall be moved to go and speak in a steeple-house or market,
turn in to that which moves, and be obedient to it, that that which would not go,
may be kept down; for that which would not go, will he apt to get up.
And take heed on the other hand, that the lavishing part do not get up,
for it is a bad savour; therefore that must be kept down, and be kept subject.
Wait in the light of the Lord, that ye may be all kept in the wisdom of God.
For when the Seed is up in every particular, there is no danger;
but when there is an opening and prophecy, and the power stirs before the seed comes up,
then there is something that will be apt to run out rashly; there is the danger,
and there must be the patience in the fear.
For it is a weighty thing to be in the work of the ministry of the Lord God,
and to go forth in that.
It is not as a customary preaching;
but it is to bring people to the end of all outward preaching.
For when ye have declared the truth to the people, and they have received it,
and are come into that which ye speak of, the uttering of many words,
and long declarations out of the life, may beget them into a form.
And if any should run on rashly into words again, without the savour of life,
then they that are come into the thing that he spoke of, will judge him;
whereby he may hurt again that which he had raised up before.
So Friends, ye must all come into the thing that is spoken
in the openings of the heavenly life among you,
and walk in the love of God, that ye may answer the thing spoken to.

'`And take heed all of running into inordinate affections; for when people come
to own you, there is danger of the wrong part getting up.
There was a strife among the disciples of Christ, who should be the greatest;
Christ told them, '`The heathen exercise lordship, and have dominion over one another;
but it shall not be so among you.`'
For Christ the Seed was to come up in every one of them; so then, where is the greatest?
for that part in the disciples which looked to be the greatest,
was the same that was in the Gentiles.
But as any one comes here, to live in the word that sanctified him,
having the heart sanctified, the tongue and lips sanctified,
living in the word of wisdom that makes clean the heart, and reconciles to God,
all things being upheld by the Word and power;--
as there is an abiding in the Word of God,
that upholds times and seasons, and gives all things increase,
and a dwelling in the Word of wisdom;
if there be but two or three agreed in this on earth,
it shall be done for them in heaven.
So in this must all things be ordered by the Word of wisdom and power,
that upholds all things, the times and the seasons, that are in the Father`'s hand,
to the glory of God, whereby his blessing may be felt among you;
and this brings to the beginning.
So this is the word of the Lord God to you all, Keep down, keep low,
that nothing may rule or reign in you, but life itself.

"`Now, the power being lived in, the cross is lived in;
and wherever Friends come in this, they draw the power and the life over;
they leave a witness behind them, answering the witness of God in others.
And where this is lived in, there is no want of wisdom, of power, of knowledge;
but he that ministereth in this, seeth with the eye which the Lord openeth in him,
what is for the fire, and what for the sword, what must be fed with judgment,
and what be nourished.
This brings all down, and to be low, every one keeping to the power;
for let a man get up ever so high, yet he must come down again to the power,
where he left; what he went from, he must come down again to that.
Before all these wicked spirits be got down, which are rambling abroad,
Friends must have patience, must wait in patience, in the cool life;
and he who is in this, doing the work of the Lord,
hath the tasting and the feeling of the Lamb`'s power and authority.
Therefore all Friends, keep cool and quiet in the power of the Lord God;
and all that is contrary will be subjected; the Lamb hath the victory, in the Seed,
through the patience.

"`If any have been moved to speak, and have quenched that which moved them,
let none such go forth afterwards into words,
until they feel the power arise and move them thereto again;
for after the first motion is quenched, the other part will be apt to get up;
and if any go forth in that, he goeth forth in his own,
and the betrayer will come into that.
And all Friends, be careful not to meddle with the powers of the earth;
but keep out of all such things; and as ye keep in the Lamb`'s authority,
ye will answer that of God in them, and bring them to do justice,
which is the end of the law.
Keep out of all jangling; for all that are in the transgression,
are out from the law of love, but all that are in the law of love,
come to the Lamb`'s power, in the Lamb`'s authority, who is the end of the law outward.
For the law being added because of transgression, Christ,
who was glorified with the Father, before the world began, is the end of the law,
bringing them that live in the law of life, to live over all transgression;
which every one must feel in himself.`"

--

More was then spoken to many of these particulars,
which was not taken at large as delivered.

[.small-break]
'''

After this meeting was over, and most of the Friends were gone away,
as I was walking in John Crook`'s garden, there came a party of horse,
with a constable, to seize me.
I heard them ask "`who was in the house,`" and somebody answered, "`I was there.`"
They said, "`I was the man they looked for;`" and went forthwith into the house,
where they had many words with John Crook, and some few Friends that were with him.
But the Lord`'s power so confounded them,
that they never came into the garden to look for me, but went their way in a rage.
When I came into the house, Friends were very glad to see them so confounded,
and that I had escaped them.
Next day I passed thence, and after I had visited Friends in several places as I went,
came to London, the Lord`'s power accompanying me, and bearing me up in his service.

I had not been long in London, before I heard that a Jesuit,
who came over with an ambassador from Spain,
had challenged all the Quakers to dispute with them at the Earl of Newport`'s house:^
footnote:[The Earl of Newport, it would appear,
was very favourably inclined towards Friends.
In a letter from E. Burrough to F. Howgill, 4th of 7th Month +++[+++9th Month+++]+++
1658, he observes, "`This night, at Woodcock`'s, at the meeting, was the Earl of Newport;
he is truly loving to us.`"
In the same letter, E. Burrough says, "`Truth spreads and grows.
The Earl of Pembroke has been with us; there is a principle of God stirring in him.`"]
whereupon Friends let him know that some would meet him.
Then he sent us word
"`he would meet with twelve of the wisest and most learned men we had:`"
a while after he sent us word "`he would meet with but six;`" and after that,
he sent us word again, "`he would have but three to come.`"
We hastened what we could, lest, after all his great boast,
he should put it quite off at last.
When we were come to the house, I bid Nicholas Bond and Edward Burrough go up,
and enter into discourse with him; and I would walk a while in the yard,
and then come up after them.
I advised them to state this question to him, Whether or not the church of Rome,
as it now stood, was not degenerated from the true church,
which was in the primitive times, from the life and doctrine,
and from the power and Spirit that they were in?
They stated the question accordingly; and the Jesuit affirmed,
"`that the church of Rome now was in the virginity and purity of the primitive church.`"
By this time I was come to them.
Then we asked him, "`whether they had the Holy Ghost poured out upon them,
as the apostles had?`"
He said, "`No.`" "`Then,`" said I,
"`if ye have not the same Holy Ghost poured forth upon you,
and the same power and Spirit that the apostles had,
then ye are degenerated from the power and Spirit which the primitive church was in.`"
There needed little more to be said to that.
Then I asked him, "`what Scripture they had for setting up cloisters for nuns,
abbeys and monasteries for men, for all their several orders;
and for their praying by beads, and to images; for making crosses,
for forbidding meats and marriages, and for putting people to death for religion?
If,`" said I, "`ye are in the practice of the primitive church,
in its purity and virginity, then let us see by Scriptures,
wherever they practised any such things.`"
(For it was agreed on both hands,
that we should make good by Scriptures what we said.) Then he told us of a written word,
and an unwritten word.
I asked him "`what he called his unwritten word:`" he said,
"`The written word is the Scriptures,
and the unwritten word is that which the apostles spoke by word of mouth;
which,`" said he, "`are all those traditions that we practise.`"
I bid him prove that by Scripture.
Then he brought the Scripture, where the apostle says (2 Thess. 2:5),
"`When I was with you, I told you these things.`"
"`That is,`" said he, "`I told you of nunneries, and monasteries,
and of putting to death for religion, and of praying by beads, and to images,
and all the rest of the practices of the church of Rome, which,`" he said,
"`was the unwritten word of the apostles, which they told then,
and have since been continued down by tradition unto these times.`"
Then "`I desired him to read that Scripture again,
that he might see how he had perverted the apostle`'s words;
for that which he there tells the Thessalonians '`he had
told them before,`' is not an unwritten word,
but is there written down, namely, that the man of sin, the son of perdition,
shall be revealed, before that great and terrible day of Christ,
which he was writing of, should come:
so this was not telling them any of those things that the church of Rome practises.
In like manner the apostle, in the third chapter of that epistle,
tells the church of some disorderly persons, he heard were amongst them, busy-bodies,
who did not work at all; concerning whom he had commanded them by his unwritten word,
when he was among them, that if any would not work, neither should he eat;
which now he commands them again in his written word in this epistle, 2 Thess.
iii. So this Scripture afforded no proof for their invented traditions;
and he had no other Scripture-proof to offer.`"
Therefore I told him,
"`this was another degeneration of their church into such inventions
and traditions as the apostles and primitive saints never practised.`"

After this he came to his sacrament of the altar, beginning at the paschal-lamb,
and the shew-bread; and so came to the words of Christ,
"`This is my body,`" and to what the apostle wrote of it to the Corinthians; concluding,
"`that after the priest had consecrated the bread and wine, it was immortal and divine,
and he that received it, received the whole Christ.`"
I followed him through the Scriptures he brought,
till I came to Christ`'s words and the apostle`'s;
and I showed him that the same apostle told the Corinthians,
after they had taken bread and wine in remembrance of Christ`'s death,
that they were reprobates, if Christ was not in them:
but if the bread they ate was Christ, he must of necessity be in them,
after they had eaten it.
Besides, if this bread and this wine, which the Corinthians ate and drank,
was Christ`'s body, then how hath Christ a body in heaven?`"
I observed to him also, "`that both the disciples at the supper,
and the Corinthians afterwards, were to eat the bread,
and drink the wine in '`remembrance of Christ,`' and to show forth his death, till he come;
which plainly proves, the bread and wine which they took was not his body.
For if it had been his real body that they ate, then he had been come,
and was then there present;
and it had been improper to have done such a thing in remembrance of him,
if he had been then present with them; as he must have been, if that bread and wine,
which they ate and drank, had been his real body.`"
Then as to those words of Christ,
"`This is my body,`" I told him Christ calls himself a vine, and a door,
and is called in Scripture, a rock;
"`Is Christ therefore an outward rook, door, or vine?`"
"`O,`" said the Jesuit, "`those words are to be interpreted:`"
"`So,`" said I, "`are those words of Christ, '`this is my body.`'`"
Now having stopped his mouth as to argument,
I made the Jesuit a proposal thus:
"`That seeing,`" he said "`the bread and wine was immortal and divine,
and the very Christ, and that whosoever received it, received the whole Christ;
let a meeting be appointed between some of them (whom the Pope
and his cardinals should appoint) and some of us;
and let a bottle of wine and a loaf of bread be brought, and divided each into two parts,
and let them consecrate which of those parts they would.
And then set the consecrated and the unconsecrated bread and wine in a safe place,
with a sure watch upon it, and let trial thus be made,
Whether the consecrated bread and wine would not lose its goodness,
and the bread grow dry and mouldy, and the wine turn dead and sour,
as well and as soon as that which was unconsecrated.
By this means, said I, the truth of this matter may be made manifest.
And if the consecrated bread and wine change not, but retain their savour and goodness,
this may be a means to draw many to your church: if they change, decay,
and lose their goodness, then ought you to confess, and forsake your error,
and shed no more blood about it: for much blood hath been shed about these things,
as in Queen Mary`'s days.`"
To this the Jesuit made this reply: "`Take,`" said he, "`a piece of new cloth,
and cut it into two pieces, and make two garments of it;
and put one of them upon king David`'s back, and the other upon a beggar`'s,
and the one garment shall wear away as well as the other.`"
"`Is this thy answer?`"
said I; "`Yes,`" said he.
"`Then,`" said I,
"`by this the company may all be satisfied that
your consecrated bread and wine is not Christ.
Have ye told people so long that the consecrated bread and wine was immortal and divine,
and that it was the very and real body and blood of Christ,
and dost thou now say it will wear away, or decay, as well as the other?
I must tell thee, Christ remains the same today as yesterday, and never decays;
but is the saints`' heavenly food in all generations, through which they have life.`"
He replied no more to this, being willing to let it fall;
for the people that were present saw his error, and that he could not defend it.
Then I asked him "`why their church persecuted and put people to death for religion.`"
He replied, "`it was not the church that did it, but the magistrates.`"
I asked him "`whether those magistrates were not
counted and called believers and Christians.`"
He said, "`Yes:`" "`Why then,`" said I, "`are they not members of your church?`"
"`Yes,`" said he.
Then I left it to the people to judge from his own concessions,
whether the church of Home doth not persecute, and put people to death for religion.
Thus we parted; and his subtlety was comprehended by simplicity.

During the time I was at London, many services lay upon me;
for it was a time of much suffering.
I was moved to write to Oliver Cromwell, and lay before him the sufferings of Friends,
both, in this nation and in Ireland.
There was also a rumour about this time of making Cromwell king:
whereupon I was moved to go to him, and warned him against it, and of divers dangers;
which, if he did not avoid,
"`he would bring a shame and ruin upon himself and his posterity.`"
He seemed to take well what I said to him, and thanked me:
yet afterwards I was moved to write to him more fully concerning that matter.

About this time the Lady Claypole^
footnote:[Lady Claypole was the favourite daughter of Oliver Cromwell,
who deeply felt her loss,
for she died shortly after the period of
receiving the letter George Fox addressed to her.
Nor was it long before Oliver himself followed her;
both he and his daughter dying in the same year.]
(so called) was sick and much troubled in mind,
and could receive no comfort from any that came to her; which when I heard of,
I was moved to write to her the following letter:--

[.embedded-content-document.letter]
--

[.salutation]
"`Friend,

"`Be still and cool in thy own mind and spirit from thy own thoughts,
and then thou wilt feel the principle of God to turn thy mind to the Lord,
from whom cometh life;
whereby thou mayest receive his strength and power to allay all storms, and tempests.
That is it which works up into patience, innocency, soberness, into stillness,
staidness, quietness up to God, with his power.
Therefore mind; that is the word of the Lord God unto thee,
that thou mayest feel the authority of God, and thy faith in that,
to work down that which troubles thee; for that is it which keeps peace,
and brings up the witness in thee, which hath been transgressed,
to feel after God with his power and life, who is a God of order and peace.
When thou art in the transgression of the life of God in thy own particular,
the mind flies up in the air, the creature is led into the night,
nature goes out of its course, an old garment goes on, and an uppermost clothing;
and thy nature being led out of its course, it comes to be all on fire,
in the transgression; and that defaceth the glory of the first body.
Therefore be still a while from thy own thoughts, searching, seeking, desires,
and imaginations, and be stayed in the principle of God in thee,
that it may raise thy mind up to God, and stay it upon God,
and thou wilt find strength from him, and find him to be a God at hand,
a present help in the time of trouble, and of need.
And thou being come to the principle of God, which hath been transgressed,
it will keep thee humble; and the humble, God will teach his way, which is peace,
and such he doth exalt.
Now as the principle of God in thee hath been transgressed, come to it,
that it may keep thy mind down low to the Lord God; and deny thyself;
for from thy own will, that is, the earthly, thou must be kept.
Then thou wilt feel the power of God, which will bring nature into its course,
and give thee to see the glory of the first body.
There the wisdom of God will be received, which is Christ,
by which all things were made and created,
and thou wilt thereby be preserved and ordered to God`'s glory.
There thou wilt come to receive and feel the physician of value,
who clothes people in their right mind, whereby they may serve God, and do his will.
For all distractions, unruliness, and confusion are in the transgression;
which transgression must be brought down, before the principle of God,
which hath been transgressed against, be lifted up: whereby the mind may be seasoned,
and stilled, and a right understanding of the Lord may be received;
whereby his blessings enter, and are felt, over all that is contrary,
in the power of the Lord God, which raises up the principle of God within,
gives a feeling after God, and in time gives dominion.
Therefore, keep in the fear of the Lord God; that is the word of the Lord unto thee.
For all these things happen to thee for thy good,
and for the good of those concerned for thee, to make you know yourselves,
and your own weakness, and that ye may know the Lord`'s strength and power,
and may trust in him.
Let the time that is past be sufficient to every one,
who in anything hath been lifted up in transgression out of the power of the Lord;
for he can bring down and abase the mighty, and lay them in the dust of the earth.

Therefore, all keep low in his fear,
that thereby ye may receive the secrets of God and his wisdom,
may know the shadow of the Almighty, and sit under it, in all tempests, and storms,
and heats.
For God is at hand, and the Most High rules in the children of men.
This then is the word of the Lord God unto you all; whatever temptations, distractions,
confusions, the light doth make manifest and discover, do not look at these temptations,
confusions, corruptions; but look at the light, which discovers them,
and makes them manifest; and with the same light you may feel over them,
to receive power to stand against them.
The same light which lets you see sin and transgression,
will let you see the covenant of God, which blots out your sin and transgression,
which gives victory and dominion over it, and brings into covenant with God.
For looking down at sin, and corruption, and distraction, ye are swallowed up in it:
but looking at the light, which discovers them, ye will see over them.
That will give victory; and ye will find grace and strength:
there is the first step to peace.
That will bring salvation; by it ye may see to the beginning,
and the '`glory that was with the Father before the
world began;`' and so come to know the Seed of God,
which is the heir of the promise of God, and of the world which hath no end;
which bruises the head of the serpent, who stops people from coming to God.
That ye may feel the power of an endless life, the power of God, which is immortal;
which brings the immortal soul up to the immortal God, in whom it doth rejoice.
So in the name and power of the Lord Jesus Christ, God Almighty strengthen thee.`"

[.signed-section-signature]
G+++.+++ F.

--

When the foregoing paper was read to Lady Claypole, she said,
it stayed her mind for the present.
Afterwards many Friends got copies of it, both in England and Ireland,
and read it to people that were troubled in mind;
and it was made useful for the settling of the minds of several.^
footnote:[The counsels contained in this letter of George Fox`'s to Lady Claypole,
though worded in his own peculiar phraseology, and at first sight not very perspicuous,
are such as must be valuable to every spiritual mind, in seasons of trial.]

About this time came forth a declaration from Oliver Cromwell, the Protector,
for a collection towards the relief of divers Protestant Churches, driven out of Poland;
and of twenty Protestant families, driven out of the confines of Bohemia.
And there having been a like declaration published some time before,
to invite the nation to a day of solemn fasting and humiliation,
in order to a contribution being made for the
suffering Protestants of the valleys of Lucerne,
Angrona, etc. who were persecuted by the Duke of Savoy,
I was moved to write to the Protector and chief magistrates on this occasion,
both to show them the nature of a true fast (such as God requires and accepts),
and to make them sensible of their injustice and self-condemnation,
in blaming the Papists for persecuting the Protestants abroad, while they themselves,
calling themselves Protestants,
were at the same time persecuting their Protestant neighbours and friends at home.
That which I wrote to them was after this manner:--

[.embedded-content-document.address]
--

[.blurb]
=== "`To the Heads and Governors of this Nation, who have put forth a Declaration for keeping a day of solemn, Fasting and Humiliation, for the persecution (as you say) of divers people beyond the seas, professing the Reformed religion, which, ye say, hath been transmitted unto them from their ancestors.

"`A Profession of the Reformed religion may be transmitted to generations,
and so holden by tradition; and in that, wherein the profession and tradition are holden,
is the day of humiliation kept; which stands in the will of man.
This is not the fast that the Lord requires,
'`to bow down the head like a bulrush for a day,`' and the day
following be in the same condition that they were the day before.
To the light of Christ Jesus in your consciences do I speak,
which testifieth for God every day, and witnesseth against all sin and persecution;
which measure of God, if ye be guided by it, doth not limit God to a day,
but leads to the fast which the Lord requires, which is,
'`To loose the bonds of wickedness, to undo the heavy burdens, to break every yoke,
and to let the oppressed go free.`' Isa. 58. 6, 7.
This is the fast that the Lord requires;
and this stands not in the transmission of times, nor in the traditions of men;
but in that which was before times were, which leads out of time,
and shall be when time shall be no more.
These that teach for doctrine the commandments of men,
are they that ever persecuted the life and power when it came.
And whereas ye mention a decree or edict that
was made against the said persecuted Protestants,
all such decrees proceed from the ground of the Pope`'s religion and supremacy,
and therein stands his tyranny and cruelty, acted in that will,
which is in that nature which exerciseth lordship over one another (as ye may read,
Mark 10:42; Luke 22:25), as all the heathen do, and ever did;
and in the heathenish nature is all the tyranny and persecution exercised,
by them that are out of the obedience to the light of Christ Jesus,
which is the guide and leader of all who are tender of that of God in the conscience.
But they who are not led by this, know not what it is to suffer for conscience`' sake.
Now, whereas ye take into your consideration the sad persecution, tyranny,
and cruelty exercised upon them, whom ye call your Protestant brethren,
and contribute to administer to their wants outwardly; this is good in its place,
and we approve it; and see it good to administer to the necessities of others,
and to do good to all: and we who are sufferers by a law derived from the Pope,
are willing to join and to contribute with you to their outward necessities.
For '`the earth is the Lord`'s, and the fulness thereof;`'
who is good and gracious to all,
willing that all should be saved, and come to the knowledge of the truth.
But in the meantime, while ye are doing this, and taking notice of others`' cruelty,
tyranny, and persecution, turn your eye upon yourselves,
and see what ye are doing at home.
To the light of Christ Jesus in all your consciences I speak, which cannot lie, nor err,
nor bear false witness; but which bears witness for God, and cries for equity, justice,
and righteousness to be executed.
See what ye are doing, who profess the Scriptures,
which were given forth by the saints in light,
who dwelt in the light and in the life of them.
For them who now witness the same light, life, and power, that gave forth the Scriptures,
which ye in words profess,
ye persecute;--them ye hale out of your synagogues and markets;--beat, stock,
and imprison.
Now let that of God in your consciences, which is just, righteous, and equal,
examine and try, whether ye have any example or precedent to exercise this persecution,
which now many in this nation suffer under, who are a people harmless and innocent,
walking in obedience towards God and man.
And though ye account the way of truth they walk in, heresy,
yet therein do they exercise themselves,
to have always '`a conscience void of offence towards God and
man,`' as ye may read the saints of old did (Acts 24:14-16);
wronging no man, neither giving any just cause of offence;
only being obedient to the commands of the Lord, to declare,
as they are moved by the Holy Ghost; and standing for the testimony of a good conscience,
speaking the truth in Christ, their consciences bearing them witness that they lie not;
for this do they suffer under you,
who in words profess the same thing for which they suffer.
Now see if any age or generation did ever persecute as ye do;
for ye profess Christ Jesus, who reveals the Father,
and persecute them that witness the revelation of the Father by Christ Jesus unto them.
Ye profess Christ Jesus, who is '`the light of the world,
that enlightens every man that cometh into the world;`' yet persecute
them that bear witness and give testimony to this light.
Ye profess that the Word is become flesh, yet persecute them that witness it so.
Ye profess that whosoever confesseth not that Jesus Christ is come in the flesh,
is an antichrist; yet persecute them that do confess him come in the flesh,
and call them antichrists and deceivers.
Ye profess that the kingdom of Christ is come; yet persecute them that witness it come.
Ye profess Christ Jesus, the resurrection and the life;
yet persecute them that witness him to be so.
If ye say, '`How shall we know that these people, who say they witness these things,
do so, or not?
I answer, Turn your minds to the light, which Christ Jesus hath enlightened you withal,
which is one in all; and if ye walk in the light, ye shall have the light of life;
then ye will know and see what ye have done,
who have persecuted the Lord of glory (in his people) in whom is life,
and the life is the light of men.
To no other touchstone shall we turn you, than into your own consciences;
there shall ye find the truth of what we have declared unto you,
and of what we bear testimony to, according to the holy Scriptures.
When the books of consciences are opened, and all judged out of them,
then shall ye witness us to be of God, and our testimony to be true.
Though now ye may stop your ears, and harden your hearts, while it is called today;
but then ye shall know what ye have done,
and against whom ye have transgressed;--then ye will see that no persecutors,
in any age or generation before you, ever transgressed against that light,
and measure of God made manifest, as ye have done.
For though Christ and the apostles were persecuted in their times, the Jews,
for the most part, did not know that he was the Christ, when he came,
notwithstanding they had the Scriptures, which prophesied of him;
neither did they believe that he was risen again,
when the apostles preached his resurrection.
But ye say, '`ye believe he is come;
ye believe his resurrection;`' yet ye persecute those that witness him come in the flesh,
those that are buried with him in baptism, that are conformable to his death,
and know the power of his resurrection; these ye persecute, hale before magistrates,
and suffer to be beaten in your synagogues; these ye cause to be whipped and stocked,
shamefully entreated, and cast into prison;
as many jails in this nation at this day testify to your faces.
Therefore honestly consider what ye are doing,
while ye are taking notice of others`' cruelties, lest ye overlook your own.
There is some difference in many things,
between the Popish religion and that which ye call the Protestant,
but in this persecution of yours there is no difference;
for ye will confess that the foundation of your religion is grounded upon the Scriptures;
yet ye are persecuting them that are in the same life which they were in,
who gave forth the Scriptures,
yourselves being the meanwhile under a profession of the words they spoke;
and this ye shall one day witness.
So ye have a profession and form, and persecute them that are in the possession,
life, and power.
Therefore know assuredly that ye must come to judgment; for he is made manifest,
to whom all judgment is committed.
Therefore to the light of Christ Jesus in your own consciences,
which searcheth and trieth you, turn your minds; stand still,
and wait there to receive the righteous law,
which is according to that of God in the conscience, which is now rising,
and is bearing witness against all ungodliness and unrighteousness of men;
and they whom ye persecute are manifest to God,
and that of God in all consciences shall bear witness for us, that we are of God;
this ye shall one day witness, whether ye will hear or forbear.
Our rejoicing is in the testimony of our consciences,
that in simplicity and godly sincerity, not with fleshly wisdom, but by the grace of God,
we have had our conversation in the world, not handling the word of God deceitfully,
but in the manifestation of the truth,
commending ourselves to every man`'s conscience in the sight of God;
and if our gospel be hid, it is hid to them that are lost.
For witnessing the holding of the mystery of faith in a pure conscience, do we suffer,
and are subject for conscience`' sake.
This is thankworthy, if a man, for conscience`' sake,
endure griefs and sufferings wrongfully.
In this is our joy and rejoicing, having a good conscience,
that whereas we are evil spoken of, as evil-doers,
they may be ashamed that falsely accuse our good conversation in Christ;
which is not only the putting away of the filth of the flesh,
but the answer of a good conscience towards God, by the resurrection of Jesus Christ.
This we witness made manifest (eternal praises to the living God!) and bear
testimony to that which spoke it in the apostle in life and power.
Therefore do we bear witness and testify against those, who,
being in a form and profession of it, persecute the life and power.
To the eternal light of Christ Jesus, the searcher and trier of all hearts,
turn your minds, and see what ye are doing; lest ye overturn your foundation,
whereon ye pretend to stand, while ye are professing the Scriptures,
and persecuting the life, light, and power, which they were in who gave them forth.
For the stone, cut out of the mountains without hands,
is now striking at the feet of the image, the profession, which is set up,
and stands in the will of man.
Now is that made manifest unto which all must answer;
all must appear before the judgment seat of Christ,
that every one may receive the things done in the body, according to that he hath done,
whether it be good or bad.
Knowing therefore the terror of the Lord, we persuade men;
but we are made manifest unto God, and shall be made manifest in all your consciences,
which ye shall witness.`"

[.signed-section-signature]
G+++.+++ F.

--

Divers times, both in the time of the Long Parliament,
and of the Protector (so called) and of the Committee of Safety,
when they proclaimed fasts, I was moved to write to them, and tell them,
their fasts were like unto Jezebel`'s; for commonly, when they proclaimed fasts,
there was some mischief contrived against us.
I knew their fasts were for strife and debate, to smite with the fist of wickedness;
as the New England professors soon after did, who, before they put our Friends to death,
proclaimed a fast also.

Now it was a time of great sufferings; and many Friends being in prisons,
many other Friends were moved to go to the parliament,
to offer up themselves to lie in the same dungeon, where their friends lay,
that they that were in prison might go out, and not perish in the stinking jails.
This we did in love to God and our brethren, that they might not die in prison;
and in love to those that cast them in,
that they might not bring innocent blood upon their own heads;
which we knew would cry to the Lord, and bring his wrath, vengeance,
and plagues upon them.
But little favour could we find from those professing parliaments;
instead thereof they would rage,
and sometimes threaten those Friends that thus attended them, that they would whip them,
and send them home.
Then commonly soon after the Lord would turn them out, and send them home;
who had not a heart to do good in the day of their power.
But they went not off without being forewarned, for I was moved to write to them,
in their several turns, as I did to the Long Parliament, unto whom I declared,
before they were broken up, that "`thick darkness was coming over them all,
even a day of darkness that should be felt.`"

And because the parliament that now sat was made up mostly of high professors, who,
pretending to be more religious than others,
were indeed greater prosecutors of them that were truly religious,
I was moved to send them the following lines, as a reproof of their hypocrisy:--

[.embedded-content-document.address]
--

"`O Friends, do not cloak and cover yourselves;
there is a God that knoweth your hearts, and that will uncover you.
He seeth your way.
Woe be to him that covereth, but not with my Spirit, saith the Lord.`'
Do ye act contrary to the law, and then put it from you?
Mercy and true judgment ye neglect.
Look, what was spoken against such: my Saviour spoke against such: '`I was sick,
and ye visited me not; I was hungry, and ye fed me not; I was a stranger,
and ye took me not in; I was in prison, and ye visited me not.`'
But they said, '`When saw we thee in prison, and did not come to thee?`'
'`Inasmuch as ye did it not unto one of these little ones, ye did it not unto me.`'
Friends, ye imprison them that are in the life and power of truth,
and yet profess to be the ministers of Christ.
But if Christ had sent you, ye would bring out of prison, and bondage,
and receive strangers.
Ye have lived in pleasure on the earth, and been wanton; ye have nourished your hearts,
as in a day of slaughter; ye have condemned, and killed the just,
and he doth not resist you.`"

[.signed-section-signature]
G+++.+++ F.

--

After this, as I was going out of town, having two Friends with me,
when we were little more than a mile out of the city,
there met us two troopers belonging to Colonel Hacker`'s regiment, who took me,
and the Friends that were with me, and brought us back to the Mews,
and there kept us prisoners.
But the Lord`'s power was so over them, that they did not take us before any officer;
but shortly after set us at liberty again.
The same day, taking boat, I went to Kingston, and thence to Hampton Court,
to speak with the Protector about the sufferings of Friends.
I met him riding into Hampton-Court Park, and before I came to him,
as he rode at the head of his life-guard,
I saw and felt a waft (or apparition) of death go forth against him;
and when I came to him, he looked like a dead man.
After I had laid the sufferings of Friends before him, and had warned him,
according as I was moved to speak to him, he bid me come to his house.
So I returned to Kingston, and next day went to Hampton Court, to speak further with him.
But when I came, he was sick, and Harvey, who was one that waited on him,
told me the doctors were not willing I should speak with him.
So I passed away, and never saw him more.

From Kingston I went to Isaac Penington`'s, in Buckinghamshire,
where I had appointed a meeting,
and the Lord`'s truth and power were preciously manifested amongst us.
After I had visited Friends in those parts, I returned to London,
and soon after went into Essex,
where I had not been long before I heard that the Protector was dead,
and his son Richard made Protector in his room.
Whereupon I came up to London again.

Before this time the church-faith (so called) was given forth,
which was said to have been made at the Savoy in eleven days`' time.
I got a copy before it was published, and wrote an answer to it;
and when their book of church-faith was sold in the streets,
my answer to it was sold also.
This angered some of the parliament-men, so that one of them told me,
"`they must have me to Smithfield.`"
I told him, "`I was above their fires, and feared them not.`"
And reasoning with him, I wished him to consider,
"`Had all people been without a faith these sixteen hundred years,
that now the priests must make them one?
Did not the apostle say, that Jesus was the author and finisher of their faith?
And since Christ Jesus was the author of the apostles`' faith,
of the church`'s faith in primitive times, and of the martyrs`' faith,
should not all people look unto him to be the author and finisher of their faith,
and not to the priests?`"
Much work we had about the priest-made faith; for they called us house-creepers,
leading silly women captive, because we met in houses,
and would not hold up their priests and temples, which they had made and set up.
I told them, that it was they who led silly women captive, and crept into houses,
who kept people always learning under them, who were covetous,
and had a form of godliness, but denied the power and Spirit which the apostles were in.
Such began to creep in the apostles`' days;
but now they had got the magistrates on their side, who upheld those houses for them,
which they had crept into, their temples, with their tithes:
whereas the apostles brought people off even from that temple,
and those tithes and offerings, which God had for a time commanded.
And the apostles met in several private houses,
being to preach the gospel to all nations; which they did freely,
as Christ had commanded them.
Thus do we, who bring people off from these priests, temples,
and tithes which God never commanded, to meet in houses, or on mountains,
as the saints of old did, who were gathered in the name of Jesus,
Christ being their Prophet, Priest, and Shepherd.

Major Wiggan, a very envious man, was present,
yet he bridled himself before the parliament-men,
and some others that were there in company.
He took upon him to make a speech, and said, "`Christ had taken away the guilt of sin,
but had left the power of sin remaining in us.`"
I told him, that was strange doctrine,
for Christ came to destroy the devil and his works, and the power of sin,
and so to cleanse men from sin.

So Major Wiggan`'s mouth was stopped at that time.
But next day, desiring to speak with me again, I took a friend or two with me,
and went to him.
Then he vented much passion and rage, beyond the bounds of a Christian or moral man;
whereupon I reproved him; and having brought the Lord`'s power over him,
and let him see what condition he was in, I left him.

After some time I passed out of London,
and had a meeting at Serjeant Birkhead`'s at Twickenham, to which many people came,
and some of considerable quality in the world.
A glorious meeting it was, wherein the Scriptures were largely and clearly opened,
and Christ exalted above all, to the great satisfaction of the hearers.

But there was great persecution in many places,
both by imprisoning and breaking up of meetings.
At a meeting about seven miles from London,
the rude people usually came out of several parishes round about, to abuse Friends,
and often beat and bruised them exceedingly.
One day they abused about eighty Friends, who went to that meeting out of London,
tearing their coats and cloaks off their backs, and throwing them into ditches and ponds;
and when they had besmeared them with dirt, they said they looked like witches.
The next First-day I was moved of the Lord to go to that meeting,
though I was then very weak.
When I came there, I bid Friends bring a table, and set it in the field,
where they used to meet, to stand upon.
According to their wonted course, the rude people came.
Having a Bible in my hand, I showed them their and their priests`' and teachers`' fruits:
and the people became ashamed, and were quiet.
I opened the Scriptures to them, and our principles agreeing therewith;
I turned the people from darkness to the light of Christ and his Spirit,
by which they might understand the Scriptures, see themselves and their sins,
and know Christ Jesus to be their Saviour.
So the meeting ended quietly, and the Lord`'s power came over all to his glory.
But it was a time of great sufferings;
for besides the imprisonments (through which
many died) our meetings were greatly disturbed.
They have thrown rotten eggs and wild-fire into our meetings,
and have brought in drums beating, and kettles, to make noises with,
that the truth might not be heard; and among these, the priests were as rude as any:
as may be seen in the book of the fighting priests,
wherein a list is given of some of them that had actually beaten and abused Friends.

Many also of our Friends were brought up to London prisoners,
to be tried before the committee; where Henry Vane,^
footnote:[Vane was a conspicuous character at this period.
He was strongly attached to a republican government,
and opposed Cromwell in his progress towards
assuming the reins of government as protector.
He was said to be one of the leaders of the Independents.
Bishop Burnet, the historian,
says of him:--"`Though he set up a form of religion in a way of his own,
yet it consisted rather in a withdrawing from all other forms,
than in any new or particular forms and opinions;
from which he and his party were called Seekers,
and seemed to wait for some new and clearer manifestations.`"
James Nayler, in a letter to Margaret Fell, speaks of Vane as "`very loving to Friends,
but drunk with imaginations.`"]
being chairman, would not suffer Friends to come in,
except they would put off their hats: but at last the Lord`'s power came over him,
so that, through the mediation of others, they were admitted.
Many of us having been imprisoned upon contempts (as
they called them) for not putting off our hats,
it was not a likely thing that Friends, who had suffered so long for it from others,
should put off their hats to him.
But the Lord`'s power came over them all, and wrought so,
that several Friends were set at liberty by them.
Now, inasmuch as sufferings grew very sharp,
I was moved of the Lord to write a few lines, and send amongst Friends,
to encourage them to go on faithfully and boldly, through the exercises of the day;
of which a copy here follows:--

[.embedded-content-document.epistle]
--

"`My dear Friends, wherever scattered abroad, in prison or out of prison; fear not,
because of the reports of sufferings;
let not the evil spies of the good land make you afraid,
if they tell you the walls are high, and there are Anakims in the land;
for at the blowing of the rams`' horns did the walls of Jericho fall;
and they that brought the evil report, perished in the wilderness.
But dwell ye in the faith, patience, and hope, having the Word of Life to keep you,
which is beyond the law; and having the oath of God, his covenant, Christ Jesus,
which divides the waters asunder, and makes them to run all on heaps; in that stand:
and ye will see all things work together for good to them that love God.
In that triumph, when sufferings come, whatever they may be.
Your faith, your shield, your helmet, your armour, you have on;
ye are ready to skip over a mountain, a wall, or a hill,
and to walk through the deep waters, though they be as heaps upon heaps.
The evil spies of the good land may preach up hardness; but Caleb,
which signifies a heart, and Joshua, a Saviour, triumph over all.`"

[.signed-section-signature]
G+++.+++ F.

--

After a while I went to Reading, where I was under great sufferings and exercises,
and in great travail of spirit for about ten weeks.
For I saw there was great confusion and distraction amongst the people,
and that the powers were plucking each other to pieces.
And I saw how many were destroying the simplicity, and betraying the truth.
Much hypocrisy, deceit, and strife, was got uppermost in the people,
so that they were ready to sheath their swords in one another`'s bowels.
There had been tenderness in many of them formerly, when they were low;
but when they were got up, had killed, and taken possession,
they came to be as bad as others; so that we had much to do with them about our hats,
and saying Thou and Thee to them.
They turned their profession of patience and moderation into rage and madness;
and many of them were like distracted men for this hat-honour.
For they had hardened themselves by persecuting the innocent,
and were at this time crucifying the Seed, Christ, both in themselves and others;
till at last they fell to biting and devouring one another,
until they were consumed one of another; who had turned against, and judged,
that which God had wrought in them, and showed unto them.
So shortly after God overthrew them, turned them upside down,
and brought the king over them,
who were often surmising that the Quakers met together to bring in King Charles,
whereas Friends did not concern themselves with the outward powers, or government.
But at last the Lord brought him in, and many of them,
when they saw he would be brought in, voted for bringing him in.
So with heart and voice praise the name of the Lord, to whom it doth belong;
who over all hath the supremacy, and who will rock the nations, for he is over them.
I had a sight and sense of the king`'s return a good while before, and so had some others.
I wrote to Oliver several times,
and let him know that while he was persecuting God`'s people,
they whom he accounted his enemies were preparing to come upon him.
When some forward spirits that came amongst us, would have bought Somerset-House,
that we might have meetings in it, I forbade them to do so:
for I then foresaw the king`'s coming in again.
Besides, there came a woman to me in the Strand,
who had a prophecy concerning King Charles`'s coming in, three years before he came:
and she told me, she must go to him to declare it.
I advised her to wait upon the Lord, and keep it to herself;
for if it should be known that she went on such a message,
they would look upon it to be treason: but she said, she must go, and tell him,
that he should be brought into England again.
I saw her prophecy was true, and that a great stroke must come upon them in power;
for they that had then got possession were so exceeding high,
and such great persecution was acted by them, who called themselves saints,
that they would take from Friends their copyhold lands,
because they could not swear in their courts.
Sometimes when we laid these sufferings before Oliver Cromwell, he would not believe it.
Wherefore Thomas Aldam^
footnote:[Thomas Aldam died in 1660,
and as this is the last mention of him in this journal,
the following particulars may be added:--He resided at Warmsworth, in Yorkshire,
and was convinced by George Fox, in 1651,
having been previously a great follower of the priests and teachers of the times.
But his hungering and thirsting soul not being satisfied amongst them, he left them,
and having received the Truth, became valiant for the same,
giving up his strength and substance to serve the Lord.
Many beatings, reproaches, imprisonments,
much spoiling of goods and other sufferings he endured, for Christ`'s sake.
He was one of the first called a Quaker imprisoned in York castle, in 1652,
where he was kept two years and six months, not being suffered once to go home,
nor permitted to see his wife, children, or relatives, when they went to visit him.
He was also fined during that imprisonment 40, at the assize,
for appearing before the judge with his hat on, and saying thee and thou to him.
During the same imprisonment for tithes, he was sued at law for treble damages,
his property being taken to the value of 42,
not leaving one cow to give milk for his young children and family.
Many other sufferings did he undergo,
which made him have a tender sympathy for others who were sufferers for the Truth,
whose cause he often pleaded.
He wrote several small works in defence of Truth, and his son, Thomas Aldam,
who was also a faithful minister, published a testimony concerning him, in 1690.
See _Piety Promoted,_ vol. i., pp. 25-28 vol. iii., p. 58.]
and Anthony Pearson were moved to go through all the jails in England,
and to get copies of Friends`' commitments under the jailer`'s hands,
that they might lay the weight of their sufferings upon Oliver Cromwell.
And when he would not give order for the releasing of them,
Thomas Aldam was moved to take his cap from off his head,
and to rend it in pieces before him, and to say unto him,
"`So shall thy government be rent from thee and thy house.`"
Another Friend also, a woman,
was moved to go to the parliament (that was envious
against Friends) with a pitcher in her hand,
which she broke into pieces before them, and told them,
"`so should they be broken to pieces:`" which came to pass shortly after.
And in my great suffering and travail of spirit for the nation,
being grievously burdened with their hypocrisy, treachery, and falsehood,
I saw God would bring that over them, which they had been above;
and that all must be brought down to that which convinced them,
before they could get over that bad spirit within and without: for it is the pure,
invisible Spirit, that doth and only can work down all deceit in people.

While I was under that sore travail at Reading, by reason of grief and sorrow of mind,
and the great exercise that was upon my spirit, my countenance was altered,
and I looked poor and thin; and there came a company of unclean spirits to me,
and told me, "`the plagues of God were upon me.`"
I told them, it was the same spirit spoke that in them, that said so of Christ,
when he was stricken and smitten; they hid their face from him.
But when I had travailed with the witness of God, which they had quenched,
and had got through with it,
and over all that hypocrisy which the outside professors were run into,
and saw how that would be brought down, and turned under,
and that life would rise over it, I came to have ease, and the light, power,
and Spirit shone over all.
And then having recovered, and got through my travails and sufferings,
my body and face swelled, when I came abroad into the air; and then the bad spirits said,
"`I was grown fat,`" and they envied at that also.
So I saw, that no condition nor state would please that spirit of theirs.
But the Lord preserved me by his power and Spirit through and over all,
and in his power I came to London again.

[.offset]
Now was there a great bother made about the image or
effigies of Oliver Cromwell lying in state;
men standing and sounding with trumpets over his image, after he was dead.
At this my spirit was greatly grieved, and the Lord, I found, was highly offended.
Then did I write the following lines, and sent among them, to reprove their wickedness,
and warn them to repent:--

[.embedded-content-document.address]
--

"`O friends, what are ye doing!
What mean ye to sound before an image!
Will not all sober people think ye are like madmen?
O, how am I grieved with your abominations!
O, how am I wearied!
My soul is wearied with you, saith the Lord: will I not be avenged of you, think ye,
for your abominations?
O, how have ye plucked down and set up!
How are your hearts made whole, and not rent!
How are ye turned to fooleries!
Which things in times past, ye stood over.
How have ye left my dread, saith the Lord!
Fear therefore, and repent, lest the snare and the pit take you all.
The great day of the Lord is come upon all your abominations;
the swift hand of the Lord is turned against them.
The sober people in these nations stand amazed at your doings, and are ashamed,
as if ye would bring in Popery.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
About this time great stirs were in the nation, the minds of people being unsettled.
Much plotting and contriving there was by the several factions,
to carry on their several interests.
And a great care being upon me, lest any young or ignorant people,
that might sometimes come amongst us, should be drawn into that snare,
I was moved to give forth the following epistle as a warning unto all such:--

[.embedded-content-document.epistle]
--

"`All Friends everywhere, keep out of plots and bustling, and the arm of flesh;
for all these are amongst Adam`'s sons in the fall,
where they are destroying men`'s lives like dogs, beasts, and swine, goring, rending,
and biting one another, destroying one another, and wrestling with flesh and blood.
Whence arise wars and killing but from the lusts?
Now all this is in Adam in the fall, out of Adam that never fell,
in whom there is peace and life.
Ye are called to peace, therefore follow it; and that peace is in Christ,
not in Adam in the fall.
All that pretend to fight for Christ, are deceived; for his kingdom is not of this world,
therefore his servants do not light.
Fighters are not of Christ`'s kingdom, but are without Christ`'s kingdom;
his kingdom stands in peace and righteousness, but fighters are in the lust;
and all that would destroy men`'s lives, are not of Christ`'s mind,
who came to save men`'s lives.
Christ`'s kingdom is not of this world; it is peaceable: and all that are in strife,
are not of his kingdom.
All that pretend to fight for the gospel, are deceived;
for the gospel is the power of God, which was before the devil, or fall of man was;
and the gospel of peace was before fighting was.
Therefore, they that pretend fighting, are ignorant of the gospel;
and all that talk of fighting for Zion, are in darkness; for Zion needs no such helpers.
All such as profess themselves to be ministers of Christ, or Christians,
and go about to beat down the whore with outward, carnal weapons,
the flesh and the whore are got up in themselves, and they are in a blind zeal;
for the whore got up by the inward ravening from the Spirit of God;
and the beating down thereof,
must be by the inward stroke of the sword of the Spirit within.
All such as pretend Christ Jesus, and confess him,
and yet run into the use of carnal weapons, wrestling with flesh and blood,
throw away the spiritual weapons.
They that would be wrestlers with flesh and blood, throw away Christ`'s doctrine;
the flesh is got up in them, and they are weary of their sufferings.
Such as would revenge themselves, are out of Christ`'s doctrine.
Such as being stricken on one cheek, would not turn the other,
are out of Christ`'s doctrine: and such as do not love one another, nor love enemies,
are out of Christ`'s doctrine.
Therefore, ye that are heirs of the blessings of God,
which were before the curse and the fall were, come to inherit your portions;
and ye that are heirs of the gospel of peace, which was before the devil was,
live in the gospel of peace, seeking the peace of all men, and the good of all men;
and live in Christ, who came to save men`'s lives, out of Adam in the fall,
where they destroy men`'s lives, and live not in Christ.
The Jews`' sword outwardly, by which they cut down the heathen,
was a type of the Spirit of God within, which cuts down the heathenish nature within.
So live in the peaceable kingdom of Christ Jesus.
Live in the peace of God, and not in the lusts, from whence wars arise.
Live in Christ, the Prince of Peace, the way of God, who is the second Adam,
that never fell; but live not in Adam in the fall, in the destruction,
where they destroy one another.
Therefore come out of Adam in the fall, into the second Adam that never fell.
Live in love and peace with all men; keep out of all the bustlings in the world;
meddle not with the powers of the earth; but mind the kingdom, the way of peace.
Ye that are heirs of grace, heirs of the kingdom, heirs of the gospel,
heirs of salvation, saints of the Most High, and children of God,
whose conversation is in heaven, that is, above the combustions of the earth;
let your conversation preach to all men, and your innocent lives,
that they who speak evil of you, beholding your godly conversation,
may glorify your Father which is in heaven.
All Friends everywhere, this I charge you,
which is the word of the Lord God unto you all, '`Live in peace,
in Christ the way of peace,`' and therein seek the peace of all men, and no man`'s hurt.
In Adam in the fall, is no peace; but in Adam out of the fall, is peace: so,
ye being in Adam which never fell, it is love that overcomes, and not hatred with hatred,
nor strife with strife.
Therefore live all in the peaceable life, doing good to all men,
and seeking the good and welfare of all men.`"

[.signed-section-signature]
G+++.+++ F.

--

Not long after this, George Booth rose in arms in Cheshire, and Lambert went against him.
At which time some foolish, rash spirits, that came sometimes amongst us,
were ready to take up arms; but I was moved of the Lord to warn and forbid them,
and they were quiet.
In the time of the Committee of Safety (so called),
we were invited by them to take up arms,
and great places and commands were offered some of us; but we denied them all,
and declared against it both by word and writing; testifying,
that our weapons and armour were not carnal, but spiritual.
And lest any that came amongst us, should be drawn into that snare,
it came upon me from the Lord, to write a few lines on that occasion,
and send them forth, as a caution to all amongst us.
Of which this is a copy:

[.embedded-content-document.epistle]
--

"`All Friends everywhere, take heed to keep out of the powers of the earth,
that run into wars and fightings, which make not for peace, but destroy it;
such will not have the kingdom.
And, Friends, take heed of joining with this or the other, or meddling with any,
or being busy with other men`'s matters; but mind the Lord, his power, and his service.
Let Friends keep out of other men`'s matters,
and keep in that which answers the witness in them all, out of the man`'s part,
where they must expect wars and dishonour.
Friends everywhere, dwell in your own, in the power of the Lord God,
to keep your minds up to the Lord God, from falling down to the strength of Egypt,
or going thither for strength, after ye are come out of it,
like the children of Israel after they were come out of outward Egypt.
But dwell in the power of the Lord God,
that ye may keep over all the powers of the earth,
amongst whom the just hand of God is come; for they have turned against the just,
disobeyed the just in their own particulars, and so gone on in one against the just;
therefore the just sets them one against another.
Now he that goes to help among them, is from the just in himself, in the unstaid state,
and doth not know, by the All-Seeing Eye (that beholdeth),
him that recompenseth and rewardeth, and lives not in the hand, in the power,
that mangles and overturns, which vexeth the transgressors, that come to be blind,
and zealous for they do not know what.
Therefore keep in peace, and in the love and power of God,
and in unity and love one to another, lest any go out, and fall with the uncircumcised:
that is, they that are from the Spirit in themselves, and they that go from it,
go into the pit together.
Therefore stand (it is the word of the Lord God to you
all) in the fear and dread of the Lord God,
his power, life, light, seed, and wisdom, by which ye may take away the occasion of wars,
and so know a kingdom which hath no end, and fight for that with spiritual weapons,
which takes away the occasion of the carnal; and there gather men to war,
as Many as ye can, and set up as many as ye can with these weapons.`"

[.signed-section-signature]
G+++.+++ F.

--

After I had stayed some time in London,
and had visited Friends`' meetings there and thereabouts,
and the Lord`'s power was set over all, I travelled into the counties again,
passing through Essex and Suffolk into Norfolk, visiting Friends, till I came to Norwich,
where we had a meeting about the time called Christmas.
The mayor of Norwich, having got previous notice of the meeting I intended to have there,
granted a warrant to apprehend me.
When I was come thither, and heard of the warrant,
I sent some Friends to the mayor to reason with him about it.
His answer was, the soldiers should not meet; and did we think to meet?
He would have us to go and meet without the city; for he said,
the town`'s-people were so rude that he could hardly order them, and he feared,
that our meeting would make tumults in the town.
But our Friends told him, we were a peaceable people,
and that he ought to keep the peace; for we could not but meet to worship God,
as our manner was.
So he became moderate, and did not send his officers to the meeting.
A large one it was, and abundance of rude people came, with an intent to do mischief;
but the Lord`'s power came over them, so that they were chained by it,
though several priests were there, and professors and Ranters.
Among the priests, one, whose name was Townsend, stood up and cried, '`Error, blasphemy,
and an ungodly meeting!`' I bid him not burden
himself with that which he could not make good;
and I asked him what was our error and blasphemy; for I told him,
he should make good his words, before I had done with him, or be shamed.
As for an ungodly meeting, I said,
I believed there were many people there that feared God,
and therefore it was both unchristian and uncivil in him, to charge civil,
godly people with an ungodly meeting.
He said, my error and blasphemy was, in that I said,
that people must wait upon God by his power and Spirit,
and feel his presence when they did not speak words.
I asked him then,
whether the apostles and holy men of God did not hear God speak to them in their silence,
before they spoke forth the Scripture, and before it was written?
He replied, Yes, David and the prophets heard God, before they penned the Scriptures,
and felt his presence in silence, before they spoke them forth.
Then said I, All people take notice,
he said this was error and blasphemy in me to say these words;
and now he hath confessed it is no more than the
holy men of God in former times witnessed.
So I showed them, that as the holy men of God,
who gave forth the Scripture as they were moved by the Holy Ghost,
heard and learned of God, before they spoke them forth;
so must they all hearken and hear what the Spirit saith,
which will lead them into all truth, that they may know God and Christ,
and may understand the Scriptures.
O, said the priest, this is not that George Fox I would speak withal;
this is a subtle man, said he.
So the Lord`'s power came over all, and the rude people were made moderate,
and were reached by it; and some professors that were there, called to the priests,
saying, "`Prove the blasphemy and errors which ye have charged them with;
ye have spoken much against them behind their backs,
but nothing ye can prove now (said they) to their faces.`"
But the priest began to get away; whereupon I told him,
we had many things to charge him withal,
therefore let him set a time and place to answer them; which he did and went his way.
A glorious day this was, for truth came over all,
and people were turned to God by his power and Spirit, and to the Lord Jesus Christ,
their free teacher, who was exalted over all.
And as we passed away, people`'s hearts were generally filled with love towards us; yea,
the ruder sort of them desired another meeting,
for the evil intentions they had against us were thrown out of their hearts.
At night I passed out of town to a Friend`'s house, and thence to Colonel Dennis`'s,
where we had a great meeting; and afterwards travelled on, visiting Friends in Norfolk,
Huntingdonshire, and Cambridgeshire.
But George Whitehead and Richard Hubberthorn stayed about Norwich to meet the priest,
who was soon confounded, the Lord`'s power came so over him.

After I had travelled through many counties in the Lord`'s service,
and many were convinced, notwithstanding the people in some places were very rude,
I returned to London, when General Monk was come up thither,
and the gates and posts of the city were pulling down.
Long before this I had a vision, wherein I saw the city lie in heaps and the gates down;
and it was then represented to me, just as I saw it several years after, lying in heaps,
when it was burned.

Divers times, both by word and writing, had I forewarned the several powers,
both in Oliver`'s time and after, of the day of recompense that was coming upon them;
but they rejecting counsel, and slighting those visitations of love to them,
I was moved now, before they were quite overturned, to lay their backsliding, hypocrisy,
and treacherous dealing before them, thus:

[.embedded-content-document.address]
--

"`Friends, now are the prophecies fulfilled and fulfilling upon you,
which have been spoken to you by the people of God in your courts, steeplehouses, towns,
cities, markets, highways, and at your feasts, when ye were in your pleasures,
and puffed up, that ye would neither hear God nor man;
when ye were in your height of authority, though raised up from a mean state,
none might come nigh you without bowing, or the respect of persons,
for ye were in the world`'s way, compliments, and fashions, which,
for conscience sake towards God they could not go into, being redeemed therefrom;
therefore they were hated by you for that cause.
But how are ye brought low, who exalted yourselves above your brethren,
and threw the just and harmless from among you, until at last God hath thrown you out;
and when ye cast the innocent from among you,
then ye fell to biting one another until ye were consumed one of another.
And so the day is come upon you, which before was told you,
though ye would not believe it.
And are not your hearts so hardened, that ye will hardly yet believe,
though ready to go into captivity?
Was it not told you, when ye spilt the blood of the innocent in your steeple-houses,
markets, highways, and cities, yea, and even in your courts also,
because they said the word '`Thou`' to you, and could not put off their hats to you,
that if something did not arise up amongst yourselves,
to avenge the blood of the innocent, there would come something from beyond the seas,
which lay reserved there, which being brought by the arm of God,
the arm of flesh and strongest mountain cannot withstand?
Yet ye would not consider, regard, or hear; but cried, peace, peace,
and feasted yourselves, and sat down in the spoil of your enemies,
being treacherous both to God and man; and who will trust you now?
Have ye not made covenants and oaths?
and broken covenants and oaths between God and man,
and made the nations breakers both of covenants and oaths; so that nothing but hypocrisy,
rottenness, and falsehood under fair pretence, was amongst you?

"`When ye pretended to set up the old cause, it was but yourselves;
for which ye long stuck to sober people, who saw ye would do no good.
But it was a joy for any of you to get up into authority, that ye might have praise,
honour, and respect; and they that were in the self-denial, were a derision to you,
from amongst whom that was banished.
Thus ye became the nation`'s masters, and not servants;
whereas the greatest of all should be the servants of all.
But there ye lost your authority, not considering your estates, from whence ye were,
and to what end God had raised you up; but forgot the Lord,
and quenched that which was good in yourselves, and persecuted them that lived in it;
and so are grown so gross and perverse, that at last ye are fit for neither God nor man.
Have not ye called the Quakers the fanatic people, and the giddy heads?
But whither now are ye giddying?
into Cain`'s city Nod, which signifies fugitive, or wandering?
Have not ye persecuted and imprisoned to death such as God had respect to,
and is now reproving you for their sakes, by them whom ye have hated?
Were not many amongst you cut off for your persecution,
and yet the rest of you would not take warning?
Was there not a book of examples sent out unto you,
of what sudden and strange deaths happened to the persecutors of the innocent?
And yet ye would not take warning, until the overflowing scourge is now coming upon you.
Are not ye they that have killed like Cain, who have killed about your sacrifice,
and mingled the blood of the innocent with it?
Hath not God now vagabonded you, that ye should become a curse upon the earth,
who have persecuted Friends to death?
Did not the blood of the righteous cry out of the ground for vengeance?
And will not the blood of the righteous be required?
Could ye think that the Lord would let you sit
always with bloody hands and fists of wickedness?
Ah! what is become of all your feasts and your fasts,
the prayers and blessings of your priests?`"

[.signed-section-signature]
G+++.+++ F.

--
