== Chapter XIII.

[.chapter-synopsis]
* 1659-1660.
* Address to the Cornish people, respecting shipwrecks
* the soldiers at Bristol are punished for disturbing Friends`' meetings
* several thousands attend a general meeting at Edward Pyot`'s
* General Monk also restrains his soldiers
* great drunkenness at elections for Parliament-men
* the Yearly Meeting is held at Balby
* and a general meeting of discipline for several counties held at Skipton
* a Friend goes naked (divested of the upper garments) through the town, declaring Truth, and is much abused
* general meeting at Arnside for three counties
* George Fox is committed to Lancaster Castle by Major Porter
* writes an answer to his mittimus
* Margaret Fell writes to the magistrates thereon
* address on true religion
* against persecution
* to Friends, on the change of government
* to Charles II., exhorting him to exercise mercy and forgiveness towards his enemies, and to restrain profaneness
* the Sheriff of Lancashire`'s return to George Fox`'s writ of Habeas Corpus
* M. Fell and Ann Curtis speak to the King on the subject
* the King orders his removal to London by Habeas Corpus, and there sets him at liberty.

Being now clear of the city of London,
and finding my spirit drawn to visit Friends in the western parts of England,
passing first into Surrey and Sussex,
I came to a great town where there was a large meeting,
to which several Friends from Reading came, and a blessed one it was.
The priest of the town was in a great rage, but did not come out of his house; wherefore,
hearing him make a great noise in his house, as we were passing from the meeting,
we bid him come out into the street, and we would discourse with him; but he would not.
So the Lord`'s power being over all, Friends were refreshed therein.
Thence I went to another market-town, where in the evening we had a precious meeting,
and the fresh sense of the presence of the Lord was sweetly felt amongst us.
Then turning into Hampshire and Dorsetshire,
I went to Ringwood and Poole visiting Friends in the Lord`'s power,
and had great meetings amongst them.

At Dorchester we had a great meeting in the evening at our inn,
which many soldiers attended, and were pretty civil.
But the constables and officers of the town came, under pretence to look for a Jesuit,
whose head (they said) was shaved; and they would have all put off their hats,
or they would take them off, to look for the Jesuit`'s shaven crown.
So they took off my hat (for I was the man they aimed at), and looked very narrowly,
but not finding any bald or shaven place on my head they went away with shame;
and the soldiers, and other sober people, were greatly offended with them.
But it was of good service for the Lord, and all things wrought together for good;
for it affected the people; and after the officers were gone, we had a fine meeting,
and people were turned to the Lord Jesus Christ, their teacher, who had bought them,
and would reconcile them to God.

Thence we passed into Somersetshire,
where the Presbyterians and Other professors were very wicked,
and often disturbed Friends`' meetings.
One time especially (as we were then informed) there was a very wicked man,
whom they got to come to the Quakers`' meeting; this man put a bear`'s skin on his back,
and undertook with that to play pranks in the meeting.
Accordingly, setting himself just opposite to the Friend that was speaking,
he lolled his tongue out of his mouth, having his bear`'s skin on his back,
and so made sport to his wicked followers, and caused a great disturbance in the meeting,
But an eminent judgment overtook him, and his punishment slumbered not;
for as he went back from the meeting,
there was a bull-baiting in the way which he stayed to see;
and coming within the bull`'s reach,
he struck his horn under the man`'s chin into his throat,
and struck his tongue out of his mouth, so that it hung lolling out,
as he had used it before, in derision in the meeting.
And the bull`'s horn running up into the man`'s head,
he swung him about upon his horn in a most remarkable and fearful manner.
Thus he that came to do mischief amongst God`'s people, was mischiefed himself;
and well would it be, if such apparent examples of Divine vengeance,
would teach others to beware.^
footnote:[Many were the judgments which overtook the persecutors of the Early Friends,
as related in their journals, and the histories of the Society.
The following occurred in Scotland, as related in Jaffray`'s diary:--"`James Skene,
who was generally known by the name of '`White James,`' to distinguish
him from a very abusive and wicked man of the same name,
called '`Black James,`' took great delight in inventing malicious slanders against Friends.
On one occasion, whilst he was repeating some wicked verses,
which he had composed on purpose to defame a worthy and innocent person,
he was in that instant suddenly struck down as one dead,
and was for some time deprived of his senses.
When he recovered, he acknowledged the just judgment of God upon him,
confessed the offence he had committed against this innocent people,
and gave proof of repentance by ever after abstaining from such practices.`"]

We travelled through Somersetshire and Devonshire, till we came to Plymouth,
and so into Cornwall, visiting the meetings of Friends to the Land`'s End.
Many precious and blessed meetings we had all along as we went,
wherein they that were convinced were established, and many others were added to them.
At the Land`'s End, there was an honest fisherman convinced,
who became a faithful minister of Christ; I took notice of him to Friends, and told them,
"`he was like Peter.`"^
footnote:[The honest fisherman mentioned here was Nicholas Jose,
who was a great sufferer for Christ`'s sake,
both in loss of goods and imprisonments in Launceston jail,
Pendenuis castle, and other places;
indeed scarcely a year passed over without his being called on to suffer
severely in some way or other for the testimony of a good conscience.
He was imprisoned with twenty-four other Friends, about the year 1689,
and continued in confinement till 1695.
For an interesting account of this worthy man,
see _Select Miscellanies,_ vol. iv., 250-255.]

While I was in Cornwall, there were great shipwrecks about the Land`'s End.
Now it was the custom of that country, that at such a time both rich and poor went out,
to get as much of the wreck as they could, not caring to save the people`'s lives;
and in some places, they call shipwrecks, God`'s grace.
These things troubled me; it grieved my spirit to hear of such unchristian actions,
considering how far they were below the heathen at Melita, who received Paul,
made him a fire, and were courteous towards him,
and them that had suffered shipwreck with him.
Wherefore I was moved to write a paper, and send it to all the parishes, priests,
and magistrates, to reprove them for such greedy actions,
and to warn and exhort them that, if they could assist to save people`'s lives,
and preserve their ships and goods, they should use their diligence therein;
and consider, if it had been their own condition, they would judge it hard,
if they should be upon a wreck,
and people should strive to get what they could from them, and not regard their lives.
A copy of this paper here follows:--

[.embedded-content-document.paper]
--

[.salutation]
"`Friends And People,

"`Take heed of greediness and covetousness, for that is idolatry;
and the idolater must not enter into the kingdom of God.
Take heed of drunkenness, oaths, and cursings, for such are destroyers of the creation,
and make it to groan.
Lay aside all fighting, quarreling, brawling, and evil speakings,
which are the works of the flesh, and not of the Spirit;
for they who follow such things are not likely to inherit the kingdom of God.
Put away all corrupt words, which are unsavoury, and misnaming one another;
for ye must give an account of every idle word.
Lay aside all profession and religion that is vain; and come to the possession,
and the pure religion, which is to visit the fatherless, the widow, and the stranger,
and receive them; for some thereby may entertain angels,
or the servants of the Lord unawares,
as Paul was entertained after the shipwreck at Melita.
Do not take people`'s goods from them by force out of their ships, seamen`'s or others'`,
neither covet ye them; but rather endeavour to preserve their lives,
and their goods for them; for that shows a spirit of compassion,
and the spirit of a Christian.
But if ye be greedy and covetous of other men`'s goods,
not mattering what becomes of the men, would ye be served so yourselves?
If ye should have a ship cast away in other places,
and the people should come to tear the goods and ship in pieces,
not regarding to save the men`'s lives,
but be ready to fight one with another for your goods,
do not ye believe such goods would become a curse to them?
And may ye not as surely believe, such kind of actions will become a curse unto you?
When the spoil of one ship`'s goods is idly spent, and consumed upon the lusts,
in ale-houses, taverns, and otherwise, then ye gape for another.
Is this to '`do as ye would be done by,`' which is the law and the prophets?
Therefore, priest Hull, are these thy fruits?
What dost thou take people`'s labour and goods for?
Hast thou taught them no better manners and conversation,
who are so brutish and heathenish?
Now all such things we judge in whomsoever.
But if any Friend, or others, preserve men`'s lives,
and endeavour to save their goods and estates,
and restore what they can of a wreck to the owners;
if they consider such for their labour,
doing in that case unto them what they would have done unto themselves, that we approve.
And if they buy or sell, and do not make a prey, that is allowed of still,
in the way of '` doing as ye would be done by, keeping to the law and to the prophets:
that is, if ye should be wrecked in another country,
ye would have other people to save your lives and goods,
and have your goods restored to you again, and you would commend them for so doing.
All that do otherwise, that wait for a wreck, and get the goods for themselves,
not regarding the lives of the men; but if any of them escape drowning,
let them go begging up and down the country; and if any escape with a little,
sometimes rob them of it;--all that do so, are not for preserving the creation,
but for destroying it; and those goods which are so gotten, shall be a curse, a plague,
and a judgment to them, and the judgments of God will follow them for acting such things;
the witness in your consciences shall answer it.
Therefore, all ye who have done such things,
'`do so no more lest a worse thing come unto you.`'
But that which is good, do; preserve men`'s lives and estates,
and labour to restore the loss and breach; that the Lord requires.
Be not like a company of greedy dogs, and worse than heathens,
as if ye had never heard of God, nor Christ, nor the Scriptures, nor pure religion.

"`And priest Hull, have people spent their money upon thee, for that which is no bread?
for a thing of nought, that thou hast such fruits?
All such teachers we utterly deny as make a trade of the Scriptures,
which are given forth from the Spirit of God, that they may be believed, read,
and practised, and that Christ, whom they testify of, may be enjoyed.
We own Christ, and are come off from all your steeple-houses,
which were the old mass-houses; for there are their bad fruits harboured.
Come to the church which is in God (1 Thess. 1),
and to the light, which Christ Jesus hath enlightened you withal,
which shows you all your ungodly words, ungodly thoughts, and ungodly actions.
This will be your teacher, if ye love it; your condemnation, if ye hate it;
for the mighty day of the Lord is coming upon all wickedness and ungodliness;
therefore lay aside your whoredoms and fornications.

"`And ye magistrates, who are to do justice, think ye not,
that the hand of the Lord God is against you, and that his judgments will come upon you,
who do not look after these things and stop them with the law, which is,
'`to do unto all men,
as they would have done unto them,`' whereby ye might be good savour in your country?
Is not the law to preserve men`'s lives and estates, '`doing unto all men,
as they would that men should do unto them?`'
For all men would have their lives and estates preserved; therefore,
should not ye preserve others, and not suffer them to be devoured and destroyed?
The evil of these things will lie upon you, both priests and magistrates.`"

[.signed-section-signature]
G+++.+++ F.

"`__Postscript.--__All dear Friends who fear the Lord,
keep out of the ravenous world`'s spirit, which leads to destroy,
and which is out of the wisdom of God.
When ships are wrecked,
do not run to destroy and make havoc of ship and goods with the world;
but to save the men, and the goods for them; and so deny yourselves,
'`and do unto them as ye would that they should do unto you.`'`"

[.signed-section-signature]
G+++.+++ F.

--

This paper had good service among the people;
and Friends have endeavoured much to save the lives of the crews in times of wrecks,
and to preserve the ships and goods for them.
And when some that have suffered shipwreck, have been almost dead and starved,
Friends have taken them to their houses, to succour and recover them;
which is an act to be practised by all true Christians.

[.small-break]
'''

I had many precious, blessed, living meetings in Cornwall,
several eminent people being convinced in that county,
whom neither priests nor magistrates, by spoiling goods or imprisonments,
could make to forsake their Shepherd, the Lord Jesus, who bought them; and all Friends,
who were turned to Christ, their Teacher and Saviour,
being settled in peace and quietness upon him, their foundation,
we left them to the Lord Jesus Christ`'s teaching and ordering, fresh and green.
Thomas Lower, who had accompanied me through all that county,
brought me over Horse-bridge into Devonshire again; and after several meetings there,
we came into Somersetshire, where we had divers large and peaceable meetings;
and so passed through the county, visiting Friends, till we came to Bristol.

I entered Bristol on the seventh day of the week.
The day before, the soldiers came with their muskets into the meeting,
and were exceedingly rude, beating and striking Friends with them,
and drove them out of the orchard in a great rage, threatening what they would do,
if Friends came there again.
For the mayor and the commander of the soldiers had, it seems,
combined together to make a disturbance amongst Friends.
When Friends told me what a rage there was in the town,
how they were threatened by the mayor and soldiers,
and how unruly the soldiers had been the day before, I sent for several Friends,
as George Bishop, Thomas Gouldney, Thomas Speed, and Edward Pyot,
and desired them to go to the mayor and aldermen, and request them,
seeing he and they had broken up our meetings,
to let Friends have the town-hall to meet in;
and for the use of it Friends would give them twenty pounds a-year,
to be distributed amongst the poor;
and when the mayor and aldermen had business to do in it, Friends would not meet in it,
but only on First-days.
These Friends were astonished at this,
and said the mayor and aldermen would think that they were mad.
I said, nay; for this would be a considerable benefit to the poor.
And it was upon me from the Lord to bid them go.
At last they consented, and went, though in the cross to their own wills.
When they had laid the thing before the mayor, he said,
"`for his part he could consent to it, but he was but one:`"
and he told Friends of another great hall they might have,
but that they did not accept, it being inconvenient.
So Friends came away, leaving the mayor in a very loving frame towards them;
for they felt the Lord`'s power had come over him.
When they came back,
I spoke to them to go also to the colonel that commanded the soldiers,
and lay before him the rude conduct of his soldiers,
how they came armed amongst innocent people, who were waiting upon,
and worshipping the Lord; but they were backward to go to him.

Next morning, being first day, we went to the meeting in the orchard,
where the soldiers had so lately been so rude.
After I had declared the truth some time in the meeting,
there came in many rude soldiers and people, some with drawn swords.
The innkeepers had made some of them drunk; and one had bound himself with an oath,
to cut down and kill the man that spoke.
He came pressing in, through all the crowd of people, to within two yards of me,
and stopped at those four Friends before mentioned (who should
have gone to the colonel as I would have had them),
and began jangling with them.
Suddenly I saw his sword was put up and gone: for the Lord`'s power came over all,
and chained him with the rest.
We had a blessed meeting,
and the Lord`'s everlasting power and presence was felt amongst us.
On the day following, the four Friends went and spoke with the colonel,
and he sent for the soldiers, and cut and slashed some of them before the Friends`' faces;
which when I heard of I blamed the Friends for letting him do so,
and also that they did not go on the seventh day, as I would have had them,
which might have prevented this cutting of the soldiers,
and the trouble they gave at our meeting.
But thus the Lord`'s power came over all those persecuting, bloody minds,
and the meeting there was held in peace for a good while after without disturbance.

I had then also a general meeting at Edward Pyot`'s, near Bristol,
at which it was supposed were several thousands;
for besides Friends from many parts thereabouts, some of the Baptists and Independents,
with their teachers, came to it, and many of the sober people of Bristol;
insomuch that the people that stayed behind said,
"`the city looked naked,`" so many were gone out of it to this meeting.
It was very quiet, many glorious truths were opened to the people,
and the Lord Jesus Christ was set up,
who was the end of all figures and shadows of the law, and the first covenant.
It was declared to the people that all figures and shadows were given to man,
after he fell; and that all the rudiments and inventions of men,
which have been set up in Christendom, many of which were Jewish and heathenish,
were not set up by the command of Christ;
and all images and likenesses man has made to himself, or for himself,
whether of things in heaven or things in earth,
have been since he lost the image and likeness of God, which God made him in.
But now Christ is come to redeem, translate, convert,
and regenerate man out of all these things that he hath set up in the fall,
out of the true types, figures, and shadows also, and out of death and darkness,
into the light, life, and image of God again,
which man and woman were in before they fell.
Therefore all now should come, and all might come to receive, Christ Jesus,
the substance, by his light, Spirit, grace, and faith; and should live and walk in him,
the Redeemer and Saviour.

And as we had much work with priests and professors, who pleaded for imperfection,
I was opened to declare and manifest unto them,
that Adam and Eve were perfect before they fell; and God saw that all that he had made,
was good, and he blessed it.
But imperfection came in by the fall, through man and woman`'s hearkening to the devil,
who was out of truth.
And though the law made nothing perfect,
yet it made way for the bringing in of the better hope, which hope is Christ,
who destroys the devil and his works, that made man and woman imperfect.
Christ saith to his disciples, "`Be ye perfect,
even as your heavenly Father is perfect:`" and he, who himself was perfect,
comes to make man and woman perfect again,
and brings them again to the state which God made them in.
So he is the maker up of the breach, and the peace between God and man.
That this might the better be understood by the lowest capacities,
I used a comparison of two old people, that had their house broken down by au enemy,
so that they, with all their children, were liable to all storms and tempests.
And there came some to them that pretended to be workmen,
and offered to build up their house again, if they would give them so much a-year:
but when they had got their money, they left their house as they found it.
After this manner came a second, third, fourth, fifth, and sixth,
each with his several pretence, to build up the old house,
and each got the people`'s money; and then cried, "`they could not rear up the house,
nor could the breach be made up; for there is no perfection here, cry they;
the house can never be perfectly built up again in this life;`"
though they had taken the people`'s money for the doing of it.
For all the sect-masters in Christendom (so called)
have pretended to build up Adam and Eve`'s fallen house,
and when they have got people`'s money,
they tell them the work cannot be perfectly done here; and so their house lies as it did.
But I told the people, Christ was come to do it freely, who, by one offering,
hath perfected for ever all them that are sanctified,
and renews them into the image of God, which man and woman were in before they fell,
and makes man and woman`'s house as perfect again as God made them at the first: and this,
Christ, the heavenly man, doth freely.
Therefore all are to look unto him, and all that have received him, are to walk in him,
the life, the substance, the first and the last, the rock of ages,
and foundation of many generations.
Largely were these, and many other things, opened and declared unto the people,
the word of life was preached, which doth live and abide;
and all were exhorted to hear and obey that which liveth and abideth,
that by it all might be born again of the immortal Seed,
and feed on the milk of the Word.
A glorious meeting there was, wherein the Lord`'s everlasting Seed, Christ Jesus,
was set over all, and Friends parted in the power and Spirit of the Lord,
in peace and in his truth, that is over all.

About this time the soldiers under General Monk`'s command were
rude mid troublesome at Friends`' meetings in many places,
whereof complaint being made to him, he gave forth the following order,
which somewhat restrained them:--

[.embedded-content-document.legal]
--

[.signed-section-context-open]
"`St. James`'s, the 9th of March,1659.

"`I do require all officers and soldiers to forbear to
disturb the peaceable meetings of the Quakers,
they doing nothing prejudicial to the Parliament or Commonwealth of England.

[.signed-section-signature]
"`George Monk.`"

--

After the meeting at Edward Pyot`'s I passed to Oldeston, to Nails-Worth,
and to Nathaniel Crisp`'s; where there was a large meeting,
and several soldiers at it, but quiet.
From thence we passed to Gloucester, visiting meetings.
In Gloucester we had a peaceable meeting, though the town was very rude, and divided;
for one part of the soldiers were for the king, and another for the parliament.`'
As I passed out of the town, over the bridge, Edward Pyot being with me,
the soldiers there said, "`they were for the king;`" but after we were past them,
and they understood it was I, they were in a great rage that I had escaped them,
and said, "`had they known it had been I, they would have shot me with hail-shot,
rather than I should have escaped them.`"
But the Lord prevented their devilish design,
and brought me safe to Colonel Grimes`'s house, where we had a large general meeting,
and the Lord`'s truth and power was set over all; Friends were established upon the Rock,
and settled under the Lord Jesus Christ`'s teaching.

We passed thence to Tewkesbury, and so to Worcester,
visiting Friends in their meetings as we went.
And in all my time I never saw the like drunkenness as in the towns,
for they had been choosing parliament-men.
At Worcester the Lord`'s truth was set over all, people were finely settled therein,
and Friends praised the Lord; nay, I saw the very earth rejoiced.
Yet great fears and troubles were in many people, and a looking for the king`'s coming in,
and all things being altered.
They would ask me what I thought of times and things.
I told them the Lord`'s power was over all, and his light shone over all;
that fear would take hold only on the hypocrites, such as had not been faithful to God,
and on our persecutors.
For in my travail and sufferings at Reading, when people were at a stand,
and could not tell what might come in, and who might rule,
I told them the Lord`'s power was over all (for I had travelled through in it),
and his day shined, whosoever should come in; and whether the king came in or not,
all would be well to them that loved the Lord, and were faithful to him.
Therefore I bid all Friends fear none but the Lord,
and keep in his power that was over all.

From Worcester I visited Friends in their meetings, till I came to Badgley,
and thence I went to Drayton, in Leicestershire, to visit my relations.
While there, one Burton, a justice, hearing I had a good horse,
sent a warrant to search for me and my horse; but I was gone before they came;
and so he missed of his wicked end.
I passed on to Twy-Cross, Swannington, and Derby, where I visited Friends,
and found my old jailer amongst them,
who had formerly kept me in the house of correction there, now convinced of the truth,
which I then suffered under him for.
Passing into Derbyshire and Nottinghamshire, I came to Synderhillgreen,
visiting Friends through all those parts in their meetings,
and so on to Balby in Yorkshire,
where our Yearly Meeting at that time was held in a great orchard of John Killam`'s,
where it was supposed some thousands of people and Friends were gathered together.
In the morning I heard that a troop of horse was sent from York, to break up our meeting,
and that the militia, newly raised, was to join them.
I went into the meeting, and stood up on a great stool, and after I had spoken some time,
two trumpeters came up, sounding their trumpets near me,
and the captain of the troop cried, "`Divide to the right and left,
and make way;`" then they rode up to me.
I was declaring the everlasting truth, and word of life, in the mighty power of the Lord.
The captain bid me "`come down, for he was come to disperse our meeting.`"
After some time I told him they all knew we were a peaceable people,
and used to have such great meetings; but if he apprehended that we met in a hostile way,
I desired him to make search among us,
and if he found either sword or pistol about any there, let such suffer.
He told me, "`he must see us dispersed, for he came all night on purpose to disperse us.`"
I asked him, "`what honour it would be to him,
to ride with swords and pistols amongst so many unarmed men and women as there were?
If he would be still and quiet,
our meeting probably might not continue above two or three hours; and when it was done,
as we came peaceably together, so we should part;
for he might perceive the meeting was so large,
that all the country thereabouts could not entertain them,
but that they intended to depart towards their homes at night.`"
He said, "`he could not stay to see the meeting ended,
but must disperse them before he went.`"
I desired him then, if he himself could not stay,
that he would let a dozen of his soldiers stay,
and see the order and peaceableness of our meeting.
He said, "`he would permit us an hour`'s time;`" and left half a dozen soldiers with us.
Then he went away with his troop, and Friends of the house gave the soldiers that stayed,
and their horses, some meat.
When the captain was gone, the soldiers that were left told us,
"`we might stay till night if we would.`"
But we stayed but about three hours after, and had a glorious, powerful meeting;
for the presence of the living God was manifest amongst us; the Seed, Christ,
was set over all, and Friends were built upon him, the foundation,
and settled under his glorious, heavenly teaching.
After the meeting, Friends passed away in peace,
greatly refreshed with the presence of the Lord, and filled with joy and gladness,
that the Lord`'s power had given them such dominion.
Many of the militia soldiers stayed also,
and were much vexed that the captain and troopers had not broken up our meeting,
and cursed them.
It was reported that they intended to do us some mischief that day; but the troopers,
instead of assisting them, were rather assistant to us, in not joining with them,
as they expected, but preventing them from doing the mischief they designed.
Yet this captain was a desperate man, for it was he that had said to me in Scotland,
that "`he would obey his superior`'s commands;
and if it were to crucify Christ he would do it;
or execute the great Turk`'s commands against the Christians, if he were under him.`"
So that it was an eminent power of the Lord, which chained both him and his troopers,
and those envious militia-soldiers also, who went away,
not having power to hurt any of us, nor to break up our meeting.
Next day we had a heavenly meeting at Warmsworth
of Friends in the ministry and several others;
and then Friends parted.
As they passed through the country, several were taken up.
For the day that our first meeting was held on, Lambert was routed,
and it made great confusion in the country;
but Friends were not kept long in prison at that time.
As I went to this meeting at Balby,
there came several to me at Skegby in Nottinghamshire,
that were then going to be soldiers under Lambert, and would have bought my horse of me;
and because I would not sell him, they were in a great rage against me,
using many threatening words; but I told them,
"`God would confound and scatter them;`" and within two or three days after,
they were scattered indeed.

From Warmsworth I passed in the Lord`'s power to Barton-Abbey where I had a great meeting;
and thence to Thomas Taylor`'s, and so to Skipton,
where there was a general meeting of men Friends out of many counties,
concerning the affairs of the church.^
footnote:[General Meetings and Yearly Meetings appear
to have been somewhat similar in their character,
They were held in various parts.
The first of which we have any account took place at Swannington,
in Leicestershire, in 1654.]
A Friend went naked, divested of the upper garments through the town, declaring truth,
and he was much beaten.
Some others also came to me all bloody.
As I walked in the street, a desperate fellow had an intent to do me a mischief;
but he was prevented, and our meeting was quiet.
To this meeting came many Friends out of most parts of the nation;
for it was about business relating to the church,
both in this nation and beyond the seas.
Several years before, when I was in the North,
I was moved to recommend the setting up of this meeting for that service;
for many Friends suffered in divers parts of the nation,
their goods were taken from them contrary to the law,
and they understood not how to help themselves, or where to seek redress.
But after this meeting was set up, several Friends who had been magistrates,
and others that understood something of the law, came thither,
and were able to inform Friends, and to assist them in gathering np the sufferings,
that they might be laid before the justices, judges, or Parliament.
This meeting had stood several years,
and divers justices and captains had come to break it up;
but when they understood the business Friends met about,
and saw their books and accounts of collections for relief of the poor,
how we took care one county to help another, and to help our friends beyond the seas,
and provide for our poor, that none of them should be chargeable to their parishes, etc.,
the justices and officers confessed we did their work,
and passed away peaceably and lovingly, commending Friends`' practice.
Sometimes there would come two hundred of the poor of other people,
and wait there till the meeting was done (for all the country
knew we met about the poor) and after the meeting,
Friends would send to the bakers for bread,
and give every one of these poor people a loaf, how many soever there were of them;
for we were taught to "`do good unto all; though especially to the household of faith.`"

After this meeting I visited Friends in their meetings, till I came to Lancaster;
whence I went to Robert Widders`'s, and so to Arnside,
where I had a general meeting for all the Friends in Westmorland, Cumberland,
and Lancashire.
It was quiet and peaceable, and the living presence of the Lord was amongst us.
I went back with Robert Widders; and Friends all passed away,
fresh in the life and power of Christ, in which they had dominion,
being settled upon him, the heavenly rock and foundation.
After the meeting, there came several rude fellows, serving-men,
belonging to one called Sir George Middleton, a justice that lived near,
to make some disturbance, as it was thought.
The meeting being ended, they did nothing there;
but lighting on three women Friends going from it,
they set upon them with impudent scoffs,
and one of them carried himself very abusively and immodestly towards them.
The same man abused other Friends also,
and was so outrageous that he would have cut them with an axe;
but was restrained by some of his fellows.
Another time the same man set upon six Friends that were going to meeting, at Yelland,
and beat and abused them very much, so that he bruised their faces,
and shed much of their blood, wounding them very sore,
one of them in several parts of his body; yet they lifted not up a hand against him,
but gave him their backs and their cheeks to beat.

From Robert Widders`'s I went next day to Swarthmore,
Francis Howgill and Thomas Curtis being with me.
I had not been long there before Henry Porter, a justice,
sent a warrant by the chief constable and three petty constables to apprehend me.
I had a sense of this beforehand;
and being m the parlour with Richard Richardson and Margaret Fell, her servants came,
and told her there were some come to search the house for arms;
and they went up into the chambers under that pretence.
It came upon me to go out to them; and as I was going by some of them, I spoke to them;
whereupon they asked me my name.
I readily told them my name; and then they laid hold on me, saying,
"`I was the man they looked for,`" and led me away to Ulverstone.
They kept me all night at the constable`'s house,
and set a guard of fifteen or sixteen men to watch me; some of whom sat in the chimney,
for fear I should go up it; such dark imaginations possessed them.
They were very rude and uncivil, and would neither suffer me to speak to Friends,
nor suffer them to bring me necessaries; but with violence thrust them out,
and kept a strong guard upon me.
Very wicked and rude they were, and a great noise they made about me.
One of the constables, whose name was Ashburnham, said,
"`He did not think a thousand men could have taken me.`"
Another of the constables, whose name was Mount, a very wicked man, said,
"`He would have served Judge Fell himself so, if he had been alive,
and he had had a warrant for him.`"
Next morning, about six,
I was putting on my boots and spurs to go with them before some justice;
but they pulled off the latter, took my knife out of my pocket,
and hastened me away along the town, with a party of horse and abundance of people,
not suffering me to stay till my own horse came down.
When I was gone about a quarter of a mile with them, some Friends,
with Margaret Fell and her children, came towards me;
and then a great party of horse gathered about me in a mad rage and fury, crying out,
"`Will they rescue him? Will they rescue him?`"
Whereupon I said unto them,
"`Here is my hair, here is my back, here are my cheeks, strike on!`"
With these words their heat was a little assuaged.
Then they brought a little horse, and two of them took up one of my legs,
and put my foot in the stirrup, and two or three lifting over my other leg,
set me upon it behind the saddle, and so led the horse by the halter;
but I had nothing to hold by.
When they were come some distance out of the town, they beat the little horse,
and made him kick and gallop; whereupon I slipped off him, and told them,
"`They should not abuse the creature.`"
They were much enraged at my getting off, and took me by the legs and feet,
and set me upon the same horse, behind the saddle again; and so led it about two miles,
till they came to a great water called the Carter-ford.
By this time my own horse was come to us, and the water being deep,
and their little horse scarcely able to carry me through, they let me get upon my own,
through the persuasion of some of their own company, leading him through the water.
One wicked fellow kneeled down, and lifting up his hands, blessed God, that I was taken.
When I was come over the Sands,
I told them I heard I had liberty to choose what justice I would go before;
but Mount and the other constables cried, "`No, I should not.`"
Then they led me to Lancaster, about fourteen miles,
and a great triumph they thought to have had; but as they led me,
I was moved "`to sing praises to the Lord, in his triumphing power over all.`"

When I was come to Lancaster, the spirits of the people being mightily up,
I stood and looked earnestly upon them; and they cried, "`Look at his eyes!`"
After a while I spoke to them; and then they were pretty sober.
Then came a young man, and took me to his house;
and after a little time the officers had me to Major Porter`'s, the justice,
and who had sent forth the warrant against me; he had several others with him.
When I came in, I said, "`Peace be amongst you!`"
Porter asked me, "`Why I came down into the country that troublesome time?`"
I told him, "`To visit my brethren.`"
"`Then,`" said he, "`you have great meetings up and down.`"
I told him though we had, our meetings were known throughout the nation to be peaceable,
and we were a peaceable people.
He said, "`We saw the devil in people`'s faces.`"
I told him, "`If I saw a drunkard, or a swearer, or a peevish, heady man,
I could not say I saw the Spirit of God in him.`"
And I asked him, "`If he could see the Spirit of God?`"
He said, "`We cried against their ministers.`"
I told him, while we were as Saul, sitting under the priests,
and running up and down with their packets of letters,
we were never called pestilent fellows, nor makers of sects;
but when we were come to exercise our consciences towards God and man,
we were called pestilent fellows, as Paul was.
He said, we could express ourselves well enough, and he would not dispute with me;
but he would restrain me.
I desired to know, "`for what,
and by whose order he sent his warrant for me;`" and I complained to
him of the abuse of the constables and other officers,
after they had taken me, and in their bringing me thither.
He would not take notice of that, but told me, "`He had an order,
but would not let me see it; for he would not reveal the king`'s secrets;`" and besides,
"`a prisoner,`" he said, "`was not to see for what he was committed.`"
I told him, that was not reason; for how should he make his defence then?
I said, "`I ought to have a copy of it;`" but he said,
"`There was a judge once that fined a man for
letting a prisoner have a copy of his mittimus;
and,`" said he, "`I have an old clerk, though I am a young justice.`"
Then he called to his clerk, saying, "`Is it not ready yet?
Bring it,`" meaning the mittimus; but it not being ready, he said to me,
"`I was a disturber of the nation.`"
I told him, I had been a blessing to the nation,
in and through the Lord`'s power and truth,
and the Spirit of God in all consciences would answer it.
Then he charged me as "`an enemy to the king; that I endeavoured to raise a new war,
and imbrue the nation in blood again.`"
I told him, I had never learned the postures of war,
but was clear and innocent as a child concerning those things, and therefore was bold.
Then came the clerk with the mittimus, and the jailer was sent for,
and commanded to take and put me into the Dark-house, and to let none come to me;
but keep me there a close prisoner, till I should be delivered by the king or parliament.
Then the justice asked the constables where my horse was; "`for I hear,`" said he,
"`that he has a good horse; have ye brought it?`"
I told him where my horse was, but he did not meddle with him.
As they took me to the jail, the constable gave me my knife again,
and then asked me to give it him; but I told him, nay, he had not been so civil to me.
So they put me into the jail, and the under-jailer, one Hardy, a very wicked man,
was exceedingly rude and cruel, and many times would not let me have meat brought in,
but as I could get it under the door.
Many people came to look at me, some in great rage, and very uncivil and rude.
Once there came two young priests, and very abusive they were;
the worst of people could not be worse.
Amongst those that came in this manner, did Preston`'s wife, of Howker, was one.
She used many abusive words, telling me,
"`My tongue should be cut out,`" and that "`I should be hanged;`" showing me the gallows.
But the Lord God cut her off, and she died in a miserable condition.

Being now a close prisoner in the common jail at Lancaster,
I desired Thomas Cummins and Thomas Green to go to the jailer,
and desire of him a copy of my mittimus, that I might know what I stood committed for.
They went; and the jailer answered, "`he could not give a copy of it,
for another had been fined for so doing;`" but he gave them liberty to read it over.
To the best of their remembrance the matters therein charged against me were,
"`that I was a person generally suspected to be
a common disturber of the peace of the nation,
an enemy to the king, and a chief upholder of the Quakers`' sect; and that,
together with others of my fanatic opinion,
I have of late endeavoured to raise insurrections in these parts of the country,
and to embroil the whole kingdom in blood.
Wherefore the jailer was commanded to keep me in safe custody,
until I should be released by order of the king and parliament.`"

When I had thus got the heads of the charge contained in the mittimus,
I wrote a plain answer, in vindication of my innocency in each particular; as follows:--

[.embedded-content-document.letter]
--

"`I am a prisoner at Lancaster, committed by Justice Porter.
A copy of the mittimus I cannot get, but such expressions I am told are in it,
as are very untrue;
as '`that I am generally suspected to be a common disturber of the nation`'s peace,
an enemy to the king, and that I, with others,
endeavour to raise insurrections to embroil the nation in blood,
all which is utterly false, and I do, in every part thereof, deny it.
For I am not a person generally suspected to be a disturber of the nation`'s peace,
nor have I given any cause for such suspicion;
for through the nation I have been tried for these things formerly.
In the days of Oliver, I was taken up on pretence of raising arms against him,
which was also false; for I meddled not with raising arms at all.
Yet I was then carried up a prisoner to London, and brought before him;
when I cleared myself, and denied the drawing of a carnal weapon against him,
or any man upon the earth; for my weapons are spiritual,
which take away the occasion of war, and lead into peace.
Upon my declaring this to Oliver, I was set at liberty by him.
After this I was taken, and sent to prison by Major Ceely in Cornwall, who,
when I was brought before the judge, informed against me, '`that I took him aside,
and told him, that I could raise forty thousand men in an hour`'s time,
to involve the nation in blood, and bring in King Charles.`'
This also was utterly false, and a lie of his own inventing, as was then proved upon him:
for I never spoke any such word to him.
I never was found in any plot; I never took any engagement or oath;
nor ever learned war-postures.
As those were false charges against me then, so are these now,
which come from Major Porter, who is lately appointed to be justice,
but wanted power formerly to exercise his cruelty against us;
which is but the wickedness of the old enemy.
The peace of the nation I am not a disturber of, nor ever was; but seek the peace of it,
and of all men, and stand for all nations`' peace, and all men`'s peace upon the earth,
and wish all knew my innocency in these things.

"`And whereas Major Porter says, '`I am an enemy to the king:`' this is false;
for my love is to him and to all men, though they be enemies to God, to themselves,
and to me.
And I can say, it is of the Lord that he is come in,
to bring down many unrighteously set up;
of which I had a sight three years before he came in.
It is much he should say I am an enemy to the king, for I have no reason so to be,
he having done nothing against me.
But I have been often imprisoned and persecuted these eleven or twelve years
by them that have been against both the king and his father,
even the party that Porter was made a major by, and bore arms for;
but not by them that were for the king.
I was never an enemy to the king, nor to any man`'s person upon the earth.
I am in the love that fulfils the law, which thinks no evil, but loves even enemies,
and would have the king saved, and come to the knowledge of the truth,
and be brought into the fear of the Lord, to receive his wisdom from above,
by which all things were made and created;
that with that wisdom he may order all things to the glory of God.

"`Whereas he calls me, '`a chief upholder of the Quakers`' sect.`'
I answer: the Quakers are not a sect, but are in the power of God,
which was before sects were; they witness the election before the world began,
and are come to live in the life, which the prophets and apostles lived in,
who gave forth the Scriptures; therefore are we hated by envious, wrathful, wicked,
and persecuting men.
But God is the upholder of us all by his mighty power,
and preserves us from the wrath of the wicked, that would swallow us up.

"`And whereas he says, '`that I, together with others of my fanatic opinion,
as he calls it, have of late endeavoured to raise insurrections,
and to embroil the whole kingdom in blood:`' I say this is altogether false;
to these things I am as a child, and know nothing of them.
The postures of war I never learned: my weapons are spiritual and not carnal:
for with carnal weapons I do not fight: I am a follower of him who said,
'`My kingdom is not of this world.`'
And though these lies and slanders are raised upon me,
I deny the drawing of any carnal weapon against the king or parliament,
or any man upon earth; for I am come to the end of the law, '`to love enemies,
and wrestle not with flesh and blood but am in that which saves men`'s lives.
A witness I am against all murderers, plotters,
and all such as would '`imbrue the nation in blood for
it is not in my heart to have any man`'s life destroyed.
And as for the word fanatic, which signifies furious, foolish, mad, etc,
he might have considered himself, before he had used that word,
and have learned the humility which goes before honour.
We are not furious, foolish, or mad;
but through patience and meekness have borne lies and slanders,
and persecutions many years, and have undergone great sufferings.
The spiritual man that wrestles not with flesh and blood, and the Spirit,
that reproves sin in the gate, which is the Spirit of truth, wisdom, and sound judgment;
this is not mad, foolish, furious, which fanatic signifies; but all are of a mad,
furious, foolish spirit, that wrestle with flesh and blood, with carnal weapons,
in their furiousness, foolishness, and rage.
This is not the Spirit of God, but of error, that persecutes in a mad, blind zeal,
like Nebuchadnezzar and Saul.

"`Now, inasmuch as I am ordered to be kept prisoner,
till I be delivered by order from the king or parliament,
therefore have I written these things to be laid before you, the king and parliament,
that ye may consider of them before ye act any thing therein; that ye may weigh,
in the wisdom of God, the intent and end of men`'s spirits,
lest ye act the thing that will bring the hand of the Lord upon you, and against you,
as many have done before, who have been in authority, whom God hath overthrown,
in whom we trust, whom we fear and cry unto day and night;--who hath heard us, doth,
and will hear us, and avenge our cause.
For much innocent blood has been shed;
and many have been persecuted to death by such as have been in authority before you,
whom God hath vomited out, because they turned against the just.
Therefore consider your standing, now that ye have the day,
and receive this as a warning of love to you.

[.signed-section-closing]
"`From an innocent sufferer in bonds, and close prisoner in Lancaster Castle, called

[.signed-section-signature]
"`George Fox.`"

--

Upon my being taken and forcibly carried away from Margaret Fell`'s house,
and charged with things of so high a nature, she was concerned,
looking upon it to be an injury offered to herself.
Whereupon she wrote the following lines, and distributed them:--

[.embedded-content-document.letter]
--

[.blurb]
=== "`To all Magistrates, concerning the wrong taking up, and imprisoning of George Fox at Lancaster.

"`I do inform the governors of this nation, that Henry Porter, mayor of Lancaster,
sent a warrant, with four constables, to my house,
for which he had no authority or order.
They searched my house, and apprehended`' George Fox in it,
who was not guilty of the breach of any law, or of any offence against any in the nation.
After they had taken him, and brought him before the said Henry Porter, bail was offered,
what he would demand, for his appearance, to answer what could be laid to his charge;
but he contrary to law, if he had taken him lawfully) refused to accept of any bail,
and put him in close prison.
After he was in prison, a copy of his mittimus was demanded,
which ought not to be denied to any prisoner,
so that he may see what is laid to his charge; but it was denied him:
a copy he could not have, they were suffered only to read it over.
Everything that was there charged against him was utterly false;
he was not guilty of any one charge in it,
as will be proved and manifested to the nation.
Let the governors consider it.
I am concerned in this thing, inasmuch as he was apprehended in my house;
and if he be guilty, I am too.
So I desire to have this searched out.

[.signed-section-signature]
"`Margaret Fell.`"

--

After this Margaret Fell determined to go to London,
to speak with the king about my being taken, and to show him the manner of it,
and the unjust dealing and evil usage I had received.
When Justice Porter heard of this, he vapoured, that he would go and meet her in the gap.
But when he came before the king,
having been a zealous man for the parliament against the king,
several of the courtiers spoke to him concerning his plundering their houses;
so that he quickly had enough of the court, and soon returned into the country.
Meanwhile the jailer seemed very fearful, and said,
he was afraid Major Porter would hang him, because he had not put me in the Dark-house.
But when the jailer waited on him, after his return from London,
he was very blank and down, and asked,
"`how I did,`" pretending he would find a way to set me at liberty.
But having overshot himself in his mittimus,
by ordering me "`to be kept a prisoner till I should be delivered by the king or
parliament,`" he had put it out of his power to release me if he would.
He was the more down also upon reading a letter which I sent him;
for when he was in the height of his rage and threats against me,
and thought to ingratiate himself into the king`'s favour by imprisoning me,
I was moved to write to him, and put him in mind,
"`how fierce he had been against the king and his party,
though now he would be thought zealous for the king.`"
Among other things in my letter, I called to his remembrance,
that when he held Lancaster Castle for the parliament against the king,
he was so rough and tierce against those that favoured the king, that he said,
"`he would leave them neither dog nor cat,
if they did not bring him provision to the castle.`"
I asked him also, "`whose great buck`'s horns those were, that were in his house;
and where he had both them and the wainscot from that he ceiled his house withal;
had he them not from Hornby Castle?`"

About this time Ann Curtis, of Reading, came to see me;
and understanding how I stood committed, it was upon her also to go to the king about it.
Her father, who had been sheriff of Bristol,
had been hung near his own door for endeavouring to bring in the king;
on which consideration she had some hopes the king might hear her on my behalf.
Accordingly, when she returned to London,
she and Margaret Pell went to the king together, who,
when he understood whose daughter she was, received her kindly.
And her request to him being "`to send for me up,
and hear the cause himself,`" he promised her he would,
and commanded his secretary to send down an order for bringing me up.
But when they came to the secretary for the order, he, being no friend to us, said,
"`it was not in his power; he must act according to law,
and I must be brought up by an _habeas corpus_ before the judges.`"
So he wrote to the judge of the King`'s Bench, signifying that it was the king`'s pleasure,
that I should be sent up by an _habeas corpus_.
Accordingly a writ was sent down, and delivered to the sheriff;
but because it was directed to the chancellor of Lancaster,
the sheriff put it off to him; on the other hand,
the chancellor would not make the warrant upon it, but said the sheriff must do that.
At length both chancellor and sheriff were got together; but being both enemies to truth,
they sought occasion for delay, and found, they said, an error in the writ, which was,
that being directed to the chancellor, it stated,
"`George Fox in prison under your custody,`" whereas the prison I was in was not,
they said, in the chancellor`'s custody, but in the sheriff`'s;
so the word your should have been his.
On this they returned the writ to London, only to have that one word altered.
When it was altered, and brought down again, the sheriff refused to carry me up,
unless I would seal a writing to him, and become bound to pay for the sealing,
and the charge of carrying me up; which I refused,
telling them I would not seal anything to them, nor be bound.
So the matter rested a while, and I continued in prison.
Meanwhile the assize came on; but as there was a writ for removing me up,
I was not brought before the judge.
At the assize many people came to see me;
and I was moved to speak out of the jail window to them,
and show them "`how uncertain their religion was; and that every sort, when uppermost,
had persecuted the rest.
When Popery was uppermost, people had been persecuted for not following the mass;
and they who then held up the mass cried, '`It was the higher power,
and people must be subject to the higher power.`'
Afterwards, they that set up the Common Prayer persecuted others for not following that;
saying, '`It was the higher power then also, and we must be subject to that.`'
Since that, the Presbyterians and Independents cried each of them,
'`We must be subject to the higher power, and submit to the directory of the one,
and the church-faith of the other.`'
Thus all, like the apostate Jews, have cried, '`Help, men of Israel,
against the true Christians.`'
So people might see, how uncertain they are of their religions.
But I directed them to Christ Jesus, that they might be built upon him,
the rock and foundation, that changeth not.`"
Much on this wise I declared to them, and they were quiet and very attentive.
Afterwards I gave forth a paper concerning True Religion, as follows:--

[.embedded-content-document.paper]
--

"`True Religion is the true rule, and right way of serving God;
a pure stream of righteousness, flowing from the image of God;
the life and power of God planted in the heart and mind by the law of life,
which bringeth the soul, mind, spirit, and body to be conformable to God,
the Father of spirits, and to Christ;
so that they come to have fellowship with the Father and the Son,
and with all his holy angels and saints.
This religion is from above, pure and undefiled before God,
leads to visit the fatherless, widows, and strangers,
and keeps from the spots of the world.
This religion is above all the defiled, spotted religions in the world,
that keep not their professors from defilement, but leave them impure, below,
and spotted; whose fatherless, and widows, and strangers beg up and down the streets.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
Soon after I gave forth a paper against persecution, as follows:--

[.embedded-content-document.paper]
--

"`The Papists, Common-Prayer-men, Presbyterians, Independents,
and Baptists persecute one another about their own inventions, their mass, common-prayer,
directory, and church-faith, which they have made, and framed, and not for the truth;
for they know not what spirit they are of, who persecute,
and would have men`'s lives destroyed about church-worship and religion, as saith Christ;
who also said, '`He came not to destroy men`'s lives, but to save them.`'
Now we cannot trust our bodies, souls,
or spirits into the hands of those that know not what spirit they are of,
but will persecute and destroy men`'s lives, and not save them;
they know not what spirit they are of themselves,
therefore they are not fit to be trusted with others.
They would destroy by a law, as the disciples once would have done by prayer,
who would have commanded '`fire to come down from heaven`'
to destroy them that would not receive Christ.
But Christ rebuked them, and told them they did not know what spirit they were of.
If they did not know what spirit they were of,
do these who have persecuted about church and religion since the apostles`' days,
who would compel men`'s bodies, goods, lives, souls,
and estates into their hands by a law, or make them suffer?
Those that destroy men`'s lives are not the ministers of Christ, the Saviour;
and seeing they know not what spirit they are of, the lives, bodies,
and souls of men are not to be trusted in their hands.
And ye that persecute shall have no resurrection to life with God, except ye repent.
But they that know what spirit they are of themselves, are in the unrebukable zeal,
and by the Spirit of God they offer up their spirits, souls, and bodies to the Lord,
which are his, to keep them.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
Whilst I was kept in Lancaster jail, I was moved to give forth the following paper,
"`for staying the minds of any such as might be hurried
or troubled about the change of government:`"--

[.embedded-content-document.paper]
--

"`All Friends, let the dread and majesty of God fill you!
And as concerning the changing of times and governments, let not that trouble any of you;
for God hath a mighty work and hand therein.
He will yet change again, until that come up, '`which must reign;
in vain shall powers and armies withstand the Lord,
for his determined work shall come to pass.
But it is just with the Lord that what is now come up should be so,
and he will be served by it.
Therefore let none murmur, nor distrust God;
for he will provoke many to zeal against unrighteousness, and for righteousness,
through things which are suffered now to work for a season; yea many,
whose zeal was even dead, shall revive again, shall see their backslidings,
and bewail them bitterly.
For God shall thunder from heaven, and break forth in a mighty noise;
his enemies shall be astonished, the workers of iniquity confounded,
and all that have not the garment of righteousness shall be
amazed at the mighty and strange work of the Lord,
which shall be certainly brought to pass.
But, my babes, look ye not out, but be still in the light of the Lamb;
and he shall fight for you.
The Almighty Hand, which must break and divide your enemies,
and take away peace from them, preserve and keep you whole,
in unity and peace with itself, and one with another.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
I was moved also to write to the king,
to "`exhort him to exercise mercy and forgiveness towards his enemies,
and to warn him to restrain the profaneness and
looseness that had got up in the nation on his return.`"
It was thus:--

[.embedded-content-document.letter]
--

[.blurb]
=== "`To the King.

[.salutation]
"`King Charles,

"`Thou earnest not into this nation by sword, nor by victory of war,
but by the power of the Lord.
Now if thou live not in it, thou wilt not prosper.
If the Lord hath showed thee mercy and forgiven thee,
and thou dost not show mercy and forgiveness, the Lord God will not hear thy prayers,
nor them that pray for thee.
If thou stop not persecution and persecutors,
and take away all laws that hold up persecution about religion; if thou persist in them,
and uphold persecution, that will make thee as blind as those that have gone before thee;
for persecution hath always blinded those that have gone into it.
Such God by his power overthrows, doth his valiant acts upon,
and bringeth salvation to his oppressed ones.
If thou bear the sword in vain, and let drunkenness, oaths, plays, may-games,
with such like abominations and vanities be encouraged or go unpunished,
as setting up may-poles, with the image of the crown on the top of them, etc.,
the nations will quickly turn like Sodom and Gomorrah, and be as bad as the old world,
who grieved the Lord until he overthrew them; and so he will you,
if these things be not suppressed.
Hardly was there so much wickedness at liberty before, as there is at this day,
as though there was no terror nor sword of magistracy;
which doth not grace the government, nor is a praise to them that do well.
Our prayers are for them that are in authority, that under them we may live a godly life,
in which we have peace, and that we may not be brought into ungodliness by them.
Hear, and consider, and do good in thy time, whilst thou hast power;
be merciful and forgive; this is the way to overcome, and obtain the kingdom of Christ.`"

[.signed-section-signature]
G+++.+++ F.

--

It was long before the sheriff would yield to remove me to London,
unless I would seal a bond to him, and bear their charges; which I still refused to do.
Then they consulted how to convey me,
and first concluded to send up a party of horse with me.
I told them, "`If I were such a man as they had represented me to be,
they had need send a troop or two of horse to guard me.`"
When they considered what a charge it would be
to them to send up a party of horse with me,
they altered their purpose,
and concluded to send me up guarded only by the jailer and some bailiffs.
But, upon further consideration, they found that would be a great charge to them also,
and therefore sent for me to the jailer`'s house, and told me, if I would put in bail,
that I would be in London such a day of the term,
I should have leave to go up with some of my own friends.
I told them, I would neither put in bail, nor give one piece of silver to the jailer;
for I was an innocent man, and they had imprisoned me wrongfully,
and laid a false charge upon me.
Nevertheless, I said,
if they would let me go up with one or two of my friends to bear me company,
I might go up, and be in London such a day, if the Lord should permit;
and if they desired it, I, or any of my friends that went with me,
would carry up their charge against myself.
At last, when they saw they could do no otherwise with me, the sheriff yielded,
consenting that I should come up with some of my friends,
without any other engagement than my word,
to appear before the judges at London such a day of the term, if the Lord should permit.
Whereupon I was let out of prison, and went to Swarthmore,
where I stayed two or three days, and then to Lancaster again, and so to Preston,
having meetings amongst Friends, till I came into Cheshire to William Gandy`'s,
where there was a large meeting out of doors,
the house not being sufficient to contain it.
That day the Lord`'s everlasting Seed was set over all, and Friends were turned to it,
who is the Heir of the Promise.
Thence I came into Staffordshire and Warwickshire, to Anthony Bickliffs;
and at Nun-Eaton, at the house of a priest`'s widow, we had a blessed meeting,
wherein the everlasting Word of Life was powerfully declared, and many settled in it.
Then travelling on, visiting Friends`' meetings,
in about three weeks from my coming out of prison, I reached London,
Richard Hubberthorn and Robert Widders being with me.

When we came to Charing-Cross,
multitudes of people were gathered together to see the
burning of the bowels of some of the old king`'s judges,
who had been hung, drawn, and quartered.

We went next morning to Judge Mallet`'s chamber, who was putting on his red gown,
to go sit upon some more of the king`'s judges.
He was very peevish and froward, and said I might come another time.
We went again to his chamber, when Judge Foster was with him,
who was called the lord chief justice of England.
With me was one called Esquire Marsh, who was one of the bedchamber to the king.
When we had delivered to the judges the charge that was against me,
and they had read to those words,
"`that I and my friends were embroiling the nation in blood,`" etc.,
they struck their hands on the table.
Whereupon I told them, "`I was the man whom that charge was against,
but I was as innocent of any such thing as a new-born child,
and had brought it up myself; and some of my friends came up with me,
without any guard.`"
As yet they had not minded my hat, but now seeing it on, they said, "`What,
did I stand with my hat on!`"
I told them I did not so in any contempt of them.
Then they commanded it to be taken off;
and when they called for the marshal of the King`'s Bench, they said to him,
"`You must take this man, and secure him; but let him have a chamber,
and not put him amongst the prisoners.`"
"`My lord,`" said the marshal, "`I have no chamber to put him into;
my house is so full I cannot tell where to provide a
room for him but amongst the prisoners.`"
"`Nay,`" said the judge, "`you must not put him amongst the prisoners.`"
But when he still answered, he had no other place to put me in, Judge Foster said to me,
"`Will you appear tomorrow about ten o`'clock at
the King`'s Bench bar in Westminster-Hall?`"
I said, "`Yes, if the Lord give me strength.`"
Then said Judge Foster to the other judge, "`If he says yes, and promises it,
you may take his word;`" so I was dismissed.
Next day I appeared at the King`'s Bench bar at the hour appointed, Robert Widders,
Richard Hubberthorn, and Esquire Marsh going with me.
I was brought into the middle of the court; and as soon as I came in,
was moved to look round, and turning to the people, said,
"`Peace be among you;`" and the power of the Lord sprang over the court.
The charge against me was read openly.
The people were moderate, and the judges cool and loving;
and the Lord`'s mercy was to them.
But when they came to that part which said,
"`that I and my friends were embroiling the nation in blood, and raising a new war,
and that I was an enemy to the king,`" etc, they lifted up their hands.
Then, stretching out my arms, I said,
"`I am the man whom that charge is against j but I am
as innocent as a child concerning the charge,
and have never learned any war-postures.
And,`" said I,
"`do ye think that if I and my friends had been such men as the charge declares,
that I would have brought it up myself against myself?
Or that I should have been suffered to come up with only one or two of my friends with me?
Had I been such a man as this charge sets forth,
I had need to have been guarded with a troop or two of horse.
But the sheriff and magistrates of Lancashire thought
fit to let me and my friends come up with it ourselves,
nearly two hundred miles, without any guard at: all; which, ye may be sure,
they would not have done, had they looked upon me to be such a man.`"
Then the judge asked me, whether it should be filed, or what I would do with it.
I answered, "`Ye are judges, and able, I hope, to judge in this matter,
therefore do with it what ye will; for I am the man these charges are against,
and here ye see, I have brought them up myself; do ye what ye will with them,
I leave it to you.`"
Then Judge Twisden beginning to speak some angry words,
I appealed to Judge Poster and Judge Mallet, who had heard me over-night.
Whereupon they said, "`They did not accuse me, for they had nothing against me.`"
Then stood up Esquire Marsh, who was of the king`'s bedchamber, and told the judges,
"`It was the king`'s pleasure, that I should be set at liberty,
seeing no accuser came up against me.`"
They asked me, "`Whether I would put it to the king and council?`"
I said, "`Yes, with a good will.`"
Thereupon they sent the sheriff`'s return, which he made to the writ of _habeas corpus_,
containing the matter charged against me in the mittimus, to the king,
that he might see for what I was committed.
The return of the sheriff of Lancaster was thus:--

[.embedded-content-document.legal]
--

"`By virtue of his Majesty`'s writ, to me directed, and hereunto annexed, I certify,
that before the receipt of the said writ, George Fox, in the said writ mentioned,
was committed to his Majesty`'s jail at the castle of Lancaster, in my custody,
by a warrant from Henry Porter, Esq.,
one of his Majesty`'s justices of peace within the county palatine aforesaid,
bearing date the fifth of June now last past; for that he, the said George Fox,
was generally suspected to be a common disturber of the peace of this nation,
an enemy to our sovereign lord the king, and a chief upholder of the Quakers`' sect;
and that he, together with others of his fanatic opinion,
have of late endeavoured to make insurrections in these parts of the country,
and to embroil the whole kingdom in blood.
And this is the cause of his taking and detaining.
Nevertheless, the body of the said George Fox I have ready before Thomas Mallet, knight,
one of his Majesty`'s justices, assigned to hold pleas before his Majesty,
at his chamber in Serjeant`'s Inn, in Pleet-Street,
to do and receive those things which his Majesty`'s said
justice shall determine concerning him in this behalf,
as by the aforesaid writ is required.

[.signed-section-signature]
'`George Chetham, Esq., Sheriff.`"

--

[.offset]
On perusal of this, and consideration of the whole matter, the king,
being satisfied of my innocency,
commanded his secretary to send an order to Judge Mallet for my release; which he did,
thus:--

[.embedded-content-document.legal]
--

"`It is his Majesty`'s pleasure, that you give order for releasing,
and setting at full liberty, the person of George Fox, late a prisoner in Lancaster jail,
and commanded hither by an _habeas corpus_.
And this signification of his Majesty`'s pleasure shall be your sufficient warrant.
Dated at Whitehall, the 24th of October, 1660.

[.signed-section-signature]
"`Edward Nicholas.`"

[.signed-section-context-close]
For Sir Thomas Mallet, Knight, one of the Justices of the King`'s Bench.

--

[.offset]
When this order was delivered,
Judge Mallet forthwith sent his warrant to the
marshal of the King`'s Bench for my release,
as follows:--

[.embedded-content-document.legal]
--

"`By virtue of a warrant, which this morning I have received from the Right Hon.
Sir Edward Nicholas, Knight, one of his Majesty`'s principal secretaries,
for the releasing and setting at liberty of George Fox,
late a prisoner in Lancaster jail, and from thence brought hither by _habeas corpus_,
and yesterday committed unto your custody;
I do hereby require you accordingly to release and set the said prisoner, George Fox,
at liberty; for which this shall be your warrant and discharge.
Given under my hand, the 25th day of October, in the year of our Lord God, 1660.

[.signed-section-signature]
"`Thomas Mallet.`"

[.signed-section-context-close]
To Sir John Lenthal, Knight, Marshal of the King`'s Bench, or his deputy.

--

Thus, after being a prisoner more than twenty weeks,
I was freely set at liberty by the king`'s command,
the Lord`'s power having wonderfully wrought for the clearing of my innocency; Porter,
who committed me,
not daring to appear to make good the charge he had falsely suggested against me.
