== Chapter XIV.

[.chapter-synopsis]
* 1660-1662.
* George Fox writes an epistle of consolation to Friends unjustly imprisoned in consequence of the insurrection of the Fifth-Monarchy Men
* Friends`' declaration against war and plots
* John Perrot and Charles Bailey create a schism
* some Friends in New England are put to death, a sense whereof is given to George Fox at the time
* the King`'s mandamus to the Governor of New England and others, to restrain them from executing Friends
* the _Battledore_ is published, showing, by examples from thirty languages, that "`Thou`" and "`Thee`" are proper to one person
* on true worship
* George Fox disputes with some Jesuits, and with all other sects
* John Perrot`'s heresy condemned
* on judicial swearing
* George Fox and Richard Hubberthorn write to the King, showing the number of Friends imprisoned prior to, and during the first year of, the Restoration, and the number who died in prison during the Commonwealth
* Thomas Sharman, jailer at Derby, convinced, and writes to George Fox
* George Fox applies to Lord D`'Aubeny on behalf of two Friends imprisoned in the Inquisition at Malta, who procures their liberation
* the ground and rise of persecution set forth
* great service at Bristol, where also he has a vision
* visits Captain Brown and his wife; the former had fled from persecution, and was judged in himself, but afterwards convinced
* George Fox and several others are arrested by Lord Beaumont, and sent to Leicester jail
* they are suddenly liberated
* To Friends on the death of Edward Burrough
* Escapes from persecutors
* Friends established on Christ, the Rock of Ages.

When it was known I was discharged from Lancaster Castle, a company of envious,
wicked spirits were troubled, and terror took hold of Justice Porter;
for he was afraid I would take advantage of the
law against him for my wrong imprisonment,
and thereby undo him, his wife, and children.
Indeed I was pressed by some in authority to make him and the rest examples; but I said,
"`I should leave them to the Lord; if the Lord forgave them,
I should not trouble myself with them.`"

Now did I see the end of the travail which I had had in my sore exercise at Reading;
for the everlasting power of the Lord was over all, and his blessed truth, life,
and light shone over the nation, and great and glorious meetings we had, and very quiet;
and many flocked in unto the truth.
Richard Hubberthorn had been with the king, who said,
"`None should molest us, so long as we lived peaceably,`"
and promised this to us upon the word of a king,
telling him we might make use of his promise.^
footnote:[Some interesting particulars of what passed during Richard
Hubberthorn`'s interview with the king are related in Sewell`'s _History,_
for which see the index of that work.]
Some Friends also were admitted into the House of Lords,
and had liberty to declare their reasons, why they could not pay tithes, swear,
or go to the steeple-house worship, or join with others in worship,
and they heard them moderately.
And there being about seven hundred Friends in prison in the nation,
who had been committed under Oliver`'s and Richard`'s government,
upon contempts (as they call them), when the king came in, he set them all at liberty.
There seemed at that time an inclination and intention
in the government to grant Friends liberty,
because they were sensible that we had suffered as well as they under the former powers.
But still, when anything was going forward in order thereto, some dirty spirits or other,
that would seem to be for us, threw something in the way to stop it.
It was said, there was an instrument drawn up for confirming our liberty,
and that it only wanted signing;
when suddenly that wicked attempt of the Fifth-monarchy-people broke out,
and put the city and nation in an uproar.
This was on a First-day night, and very glorious meetings we had had that day,
wherein the Lord`'s truth shone over all, and his power was exalted above all;
but about midnight, or soon after, the drums beat, and the cry was, "`Arm, Arm!`"
I got up out of bed, and in the morning took boat, and landing at Whitehall-stairs,
walked through Whitehall.
They looked strangely at me there, but I passed through them, and went to Pali-Mall,
where divers Friends came to me, though it had now become dangerous passing the streets;
for by this time the city and suburbs were up in arms,
and exceedingly rude the people and soldiers were; insomuch that Henry Fell,^
footnote:[Henry Fell was an eminent minister in the Society.
In 1656 and 1658 he visited the West India isles.
During the first visit, he was absent from home about a year.
From 1659 to 1662, he was mostly engaged in gospel labours in England,
and from this period we lose all trace of him.
He is mentioned in Whiting`'s Catalogue as having died in America.
His home was in Lancashire,
and there is reason to believe he was a near relative of Judge Fell.
He appears to have received an education considerably above most of his day.
Some of his letters are given in Bowden`'s _History of Friends in America_,
and in Barclay`'s _Letters of Early Friends_.]
going to a Friend`'s house, the soldiers knocked him down, and he would have been killed,
had not the Duke of York come by.
Great mischief was done in the city this week; and when the next First-day came,
as Friends went to their meetings, many were taken prisoners.
I stayed at Pall-Mali, intending to be at the meeting there; but on Seventh-day night,
a company of troopers came and knocked at the door.
The servant letting them in, they rushed into the house, and laid hold of me;
and there being amongst them one that had served under the parliament,
he put his hand to my pocket, and asked, "`whether I had any pistols?`"
I told him, he knew I did not carry pistols, why therefore ask such a question of me,
whom he knew to be a peaceable man?
Others of the soldiers ran into the chambers, and there found in bed Esquire Marsh, who,
though he was one of the king`'s bedchamber, out of his love to me,
came and lodged where I did.
When they came down again, they said,
"`Why should we take this man away with us? We will let him alone.`"
"`O,`" said the parliament soldier, "`he is one of the heads, and a chief ringleader.`"
Upon this the soldiers were taking me away, but Esquire Marsh hearing of it,
sent for him that commanded the party, and desired him to let me alone,
for he would see me forthcoming in the morning.
In the morning before they could fetch me, and before the meeting was gathered,
there came a company of foot soldiers to the house, and one of them drawing his sword,
held it over my head.
I asked him, "`why he drew his sword at an unarmed man?`"
at which his fellows being ashamed, bid him put up his sword.
These foot soldiers took me away to Whitehall, before the troopers came for me.
As I was going out, several Friends were coming in to the meeting,
whose boldness and cheerfulness I commended, and encouraged them to persevere therein.
When I was brought to Whitehall, the soldiers and people were exceedingly rude,
yet I declared truth to them; but some great persons coming by,
who were very full of envy, "`What,`" said they, "`do ye let him preach?
Put him into such a place, where he may not stir.`"
So into that place they put me, and the soldiers watched over me.
I told them, though they could confine my body and shut that up,
yet they could not stop the Word of Life.
Some came, and asked me, "`What I was?`"
I told them, "`A preacher of righteousness.`"
After I had been kept there two or three hours, Esquire Marsh spoke to Lord Gerrard,
and he came and bid them set me at liberty.
The marshal, when I was discharged, demanded fees.
I told him, I could not give him any, neither was it our practice;
and asked him how he could demand fees of me, who was innocent.
Then I went through the guards, the Lord`'s power being over them;
and after I had declared truth to the soldiers,
I went up the streets with two Irish colonels that came from Whitehall, to an inn,
where many Friends were at that time prisoners under a guard.
I desired these colonels to speak to the guard to let me go in to visit my friends,
that were prisoners there; but they would not.
Then I stepped to the sentry, and desired him to let me go up; and he did so.
While I was there, the soldiers went to Pail-Mall again to search for me there;
but not finding me, they turned towards the inn,
and bid all come out that were not prisoners; so they went out.
But I asked the soldiers that were within,
"`Whether I might not stay there a while with my friends?`"
They said, "`Yes.`"
I stayed, and so escaped their hands again.
Towards night I went to Pall-Mall, to see how it was with the Friends there;
and after I had stayed a while, I went up into the city.
Great rifling of houses there was at this time to search for people.
I went to a private friend`'s house, and Richard Hubberthorn was with me.
There we drew up a declaration against plots and fightings,
to be presented to the king and council; but when finished, and sent to print,
it was taken in the press.

On this insurrection of the Fifth-monarchy men,
great havoc was made both in city and country,
so that it was dangerous for sober people to stir abroad for several weeks after;
men or women could hardly go up and down the streets to
buy provisions for their families without being abused.
In the country they dragged men and women out of their houses,
and some sick men out of their beds by the legs.
Nay, one man in a fever, the soldiers dragged out of bed to prison,
and when he was brought there he died.
His name was Thomas Pachyn.

Margaret Fell went to the king,
and told him what sad work there '`was in the city and nation,
and showed him we were an innocent, peaceable people,
and that we must keep our meetings as heretofore, whatever we suffered;
but that it concerned him to see that peace was kept,
that no innocent blood might be shed.

The prisons were now everywhere filled with Friends, and others, in the city and country,
and the posts were so laid for the searching of letters, that none could pass unsearched.
We heard of several thousands of our Friends being cast
into prison in several parts of the nation,
and Margaret Fell carried an account of them to the king and council.
Next week we had an account of several thousands more being cast into prison;
and she went and laid them also before the king and council.
They wondered how we could have such intelligence,
having given strict charge for the intercepting of all letters;
but the Lord so ordered it, that we had an account, notwithstanding all their stoppings.
In the deep sense I had of the grievous sufferings Friends underwent,
and of their innocency towards God and man,
I was moved to send the following epistle to them, as a word of consolation,
and advised them to send up an account of their sufferings:--

[.embedded-content-document.epistle]
--

[.salutation]
"`My Dear Friends,

"`In the immortal seed of God, which will plead its own innocency,
who are inheritors of an everlasting kingdom that is incorruptible,
and of a world and riches that fade not away,
peace and mercy be multiplied amongst you in all your sufferings;
whose backs were not unready, but your hair and cheeks prepared;
who never feared suffering, knowing it is your portion in the world,
from the foundation of which the Lamb was slain, who reigns in his glory,
which he had with his Father before the world began.
He is your rock in all floods and waves, upon which ye can stand safe,
with a cheerful countenance, beholding the Lord God of the whole earth on your side.
So in the Seed of God, which was before the unrighteous world, in which sufferings are,
live and feed; wherein the Bread of Life is felt,
and no cause to complain of hunger or cold.
Friends, I would have you all, that are or have been lately in prison,
to send up an account of your sufferings, and how things are amongst you,
that it may be delivered to the king and his council;
for things are pretty well here after the storm.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 28th of the 11th Month, 1660.

--

Having lost our former declaration in the press,
we hastily drew up another against plots and fighting, got it printed,
and sent some copies to the king and council; others were sold in the streets,
and at the Exchange.
Which declaration was some years after reprinted, and is as follows:--

[.embedded-content-document.address]
--

[.blurb]
=== A Declaration from the harmless and innocent people of God, called Quakers, against all sedition, plotters, and fighters in the world: for removing the ground of jealousy and suspicion from magistrates and people concerning tears and fightings.

[.signed-section-context-open]
Presented to the King upon the 21st day of the 11th Month, 1660.

"`Our principle is, and our practices have always been, to seek peace and ensue it;
to follow after righteousness and the knowledge of God; seeking the good and welfare,
and doing that which tends to the peace of all.
We know that wars and fightings proceed from the lusts of men, as James 4:1-3,
out of which the Lord hath redeemed us, and so out of the occasion of war.
The occasion of war, and war itself (wherein envious men,
who are lovers of themselves more than lovers of God, lust, kill,
and desire to have men`'s lives or estates) ariseth from lust.
All bloody principles and practices, as to our own particulars, we utterly deny;
with all outward wars and strife, and fightings with outward weapons, for any end,
or under any pretence whatsoever; this is our testimony to the whole world.
And whereas it is objected:

"`But although you now say '`that you cannot fight, nor take up arms at all,
yet if the Spirit move you, then you will change your principle,
and you will sell your coat, and buy a sword, and fight for the kingdom of Christ.`'

"`To this we answer, Christ said to Peter,
'`Put up thy sword in his place;`' though he had said before,
he that had no sword might sell his coat and buy one
(to the fulfilling of the law and the Scripture),
yet after, when he had bid him put it up, he said, '`he that taketh the sword,
shall perish with the sword.`'
And further, Christ said to Pilate,
'`Thinkest thou, that I cannot now pray to my Father,
and he shall presently give me more than twelve legions of angels?`'
And this might satisfy Peter, Luke 22:36, after he had put up his sword,
when he said to him, '`He that took it, should perish by it;`' which satisfieth us,
Matt. 26:51-53. And in the Revelation, it is said, '`He that kills with the sword,
shall perish with the sword; and here is the faith and the patience of the saints.`'
And so Christ`'s kingdom is not of this world, therefore do not his servants fight,
as he told Pilate, the magistrate, who crucified him.
And did they not look upon Christ as a raiser of sedition?
and did not he pray, '`Forgive them?`'
But thus it is that we are numbered amongst transgressors, and fighters,
that the Scriptures might be fulfilled.

"`That the Spirit of Christ, by which we are guided, is not changeable,
so as once to command us from a thing as evil, and again to move unto it;
and we certainly know, and testify to the world, that the Spirit of Christ,
which leads us into all truth,
will never move us to fight and war against any man with outward weapons,
neither for the kingdom of Christ, nor for the kingdoms of this world.

"`First, Because the kingdom of Christ God will exalt, according to his promise,
and cause it to grow and flourish in righteousness; '`not by might,
nor by power (of outward sword), but by my Spirit, saith the Lord.
Zech. 4:6. So those that use any weapon to fight for Christ,
or for the establishing of his kingdom or government,--their spirit, principle,
and practice we deny.

"`Secondly, We do earnestly desire and wait, that, by the Word of God`'s power,
and its effectual operation in the hearts of men,
the kingdoms of this world may become the kingdoms of the Lord, and of his Christ;
that he may rule and reign in men by his Spirit and truth; that thereby all people,
out of every profession, may be brought into love and unity with God,
and one with another; and that they may all come to witness the prophet`'s words,
who said, '`Nation shall not lift up sword against nation,
neither shall they learn war any more,`' Isa. 2:4. Mic. 4:3.

"`So we, whom the Lord hath called into the obedience of his truth,
have denied wars and fightings, and cannot more learn them.
This is a certain testimony unto all the world,
of the truth of our hearts in this particular,
that as God persuadeth every man`'s heart to believe, so they may receive it.
For we have not, as some others, gone about with cunningly devised fables,
nor have we ever denied in practice what we have professed in principle;
but in sincerity and truth, and by the word of God,
have we laboured to manifest unto all men,
that both we and our ways might be witnessed in the hearts of all.
And whereas all manner of evil hath been falsely spoken of us,
we hereby speak the plain truth of our hearts, to take away the occasion of that offence;
that so being innocent, we may not suffer for other men`'s offences,
nor be made a prey of by the wills of men`' for that of which we were never guilty;
but in the uprightness of our hearts we may,
under the power ordained of God for the punishment of evil-doers,
and for the praise of them that do well, live a peaceable and godly life,
in all godliness and honesty.
For although we have always suffered, and do now more abundantly suffer,
yet we know that it is for righteousness`' sake; '`for our rejoicing is this,
the testimony of our consciences, that in simplicity and godly sincerity,
not with fleshly wisdom, but by the grace of God,
we have had our conversation in the world,`' 2 Cor. 1:12,
which for us is a witness for the convincing of our enemies.
For this we can say to all the world, we have wronged no man,
we have used no force nor violence against any man; we have been found in no plots,
nor guilty of sedition.
When we have been wronged, we have not sought to revenge ourselves;
we have not made resistance against authority;
but wherein we could not obey for conscience`' sake,
we have suffered the most of any people in the nation.
We have been counted as sheep for the slaughter, persecuted and despised, beaten, stoned,
wounded, stocked, whipped, imprisoned, haled out of synagogues,
cast into dungeons and noisome vaults, where many have died in bonds,
shut up from our friends, denied needful sustenance for many days together,
with other the like cruelties.
And the cause of all these sufferings is not for any evil,
but for things relating to the worship of our God, and in obedience to his requirings.
For which cause we shall freely give up our bodies a sacrifice,
rather than disobey the Lord; for we know, as the Lord hath kept us innocent,
so he will plead our cause, when there is none in the earth to plead it.
So we, in obedience unto his truth, do not love our lives unto death,
that we may do his will, and wrong no man in our generation,
but seek the good and peace of all men.
He who hath commanded us that we shall not swear at all, Matt. 5:34,
hath also commanded us that we shall not kill, Matt. 5;
so that we can neither kill men, nor swear for or against them.
This is both our principle and practice, and has been from the beginning;
so that if we suffer, as suspected to take up arms, or make war against any,
it is`' without any ground from us; for it neither is, nor ever was in our hearts,
since we owned the truth of God; neither shall we ever do it,
because it is contrary to the Spirit of Christ, his doctrine,
and the practices of his apostles; even contrary to him, for whom we suffer all things,
and endure all things.

"`And whereas men come against us with clubs, staves, drawn swords, pistols cocked,
and beat, cut, and abuse us, yet we never resisted them; but to them our hair, backs,
and cheeks, have been ready.
It is not an honour to manhood or nobility to run upon harmless people,
who lift not up a hand against them, with arms and weapons.

"`Therefore consider these things, ye men of understanding; for plotters,
raisers of insurrections, tumultuous ones, and fighters, running with swords, clubs,
staves, and pistols, one against another; these, we say, are of the world,
and have their foundation from this unrighteous world,
from the foundation of which the Lamb hath been slain;
which Lamb hath redeemed us from this unrighteous world, and we are not of it,
but are heirs of a world of which there is no end,
and of a kingdom where no corruptible thing enters.
Our weapons are spiritual, and not carnal, yet mighty through God,
to the pulling down of the strongholds of sin and Satan, who is the author of wars,
fighting, murder, and plots.
Our swords are broken into plough-shares, and spears into pruning-hooks,
as prophesied of in Micah 4.
Therefore we cannot learn war any more,
neither rise up against nation or kingdom with outward weapons,
though you have numbered us amongst the transgressors and plotters.
The Lord knows our innocency herein, and will plead our cause with all people upon earth,
at the day of their judgment, when all men shall have a reward according to their works.

"`Therefore in love we warn you for your souls`' good, not to wrong the innocent,
nor the babes of Christ, which he hath in his hand,
which he cares for as the apple of his eye; neither seek to destroy the heritage of God,
nor turn your swords backward upon such as the law was not made for, i. e.,
the righteous; but for sinners and transgressors, to keep them down.
For those are not peacemakers, nor lovers of enemies,
neither can they overcome evil with good,
who wrong them that are friends to you and all men, and wish your good,
and the good of all people on the earth.
If you oppress us, as they did the children of Israel in Egypt,
and if you oppress us as they did when Christ was born,
and as they did the Christians in the primitive times; we can say,
'`The Lord forgive you;`' and leave the Lord to deal with you, and not revenge ourselves.
If you say, as the council said to Peter and John,
'`speak no more in that name;`' and if you serve us,
as they served the three children spoken of in Daniel, God is the same that ever he was,
that lives for ever and ever, who hath the innocent in his arms.

"`O, Friends! offend not the Lord and his little ones, neither afflict his people;
but consider and be moderate.
Do not run on hastily, but consider mercy, justice, and judgment;
that is the way for you to prosper, and obtain favour of the Lord.
Our meetings were stopped and broken up in the days of Oliver,
under pretence of plotting against him;
in the days of the Committee of Safety we were
looked upon as plotters to bring in King Charles;
and now our peaceable meetings are termed seditious.
O! that men should lose their reason, and go contrary to their own conscience;
knowing that we have suffered all things,
and have been accounted plotters from the beginning,
though we have declared against them both by word of mouth and printing,
and are clear from any such thing!
We have suffered all along, because we would not take up carnal weapons to fight,
and are thus made a prey, because we are the innocent lambs of Christ,
and cannot avenge ourselves!
These things are left on your hearts to consider; but we are out of all those things,
in the patience of the saints; and we know, as Christ said, '`He that takes the sword,
shall perish with the sword;`' Matt. 26:52; Rev. 13:10.

"`This is given forth from the people called Quakers,
to satisfy the king and his council, and all those that have any jealousy concerning us,
that all occasion of suspicion may be taken away, and our innocency cleared.`"

"`__Postscript.--__Though we are numbered amongst transgressors,
and have been given up to rude, merciless men, by whom our meetings are broken up,
in which we edified one another in our holy faith,
and prayed together to the Lord that lives for ever, yet he is our pleader in this day.
The Lord saith, '`They that feared his name spoke often together`' (as in Malachi);
which were as his jewels.
For this cause, and no evil-doing, are we cast into holes, dungeons,
houses of correction, prisons (neither old nor young being spared, men nor women),
and made a prey of in the sight of all nations, under the pretence of being seditious,
etc, so that all rude people run upon us to take possession.
For which we say, '`The Lord forgive them that have thus done to us;`' who doth,
and will enable us to suffer;
and never shall we lift up hand against any that thus use us;
but desire the Lord may have mercy upon them, that they may consider what they have done.
For how is it possible for them to requite us for the wrong they have done to us?
Who to all nations have sounded us abroad as seditious,
who were never found plotters against any,
since we knew the life and power of Jesus Christ manifested in us,
who hath redeemed us from the world, all works of darkness, and plotters therein,
by which we know the election, before the world began.
So we say, the Lord have mercy upon our enemies and forgive them,
for what they have done unto us!

"`O! do as you would be done by; do unto all men as you would have them do unto you;
for this is the law and the prophets.

"`All plots, insurrections, and riotous meetings we deny,
knowing them to be of the devil, the murderer; which we in Christ,
who was before they were, triumph over.
And all wars and fightings with carnal weapons we deny, who have the sword of the Spirit;
and all that wrong us, we leave to the Lord.
This is to clear our innocency from the aspersion cast upon us,
that we are seditious or plotters.`"

--

[.embedded-content-document.letter]
--

[.blurb]
=== Added in the reprinting.

[.salutation]
"`Courteous Reader,

"`This was our testimony above twenty years ago;
since then we have not been found acting contrary to it, nor ever shall; for the truth,
that is our guide, is unchangeable.
This is now reprinted to the men of this age, many of whom were then children,
and doth stand as our certain testimony against
all plotting and fighting with carnal weapons.
And if any by departing from the truth should do so,
this is our testimony in the truth against them, and will stand over them,
and the truth will be clear of them.`"

--

This declaration somewhat cleared the dark air that was over the city and country.
And soon after the king gave forth a proclamation,
"`That no soldiers should search any house without a constable.`"
But the jails were still full, many thousands of Friends being in prison;
which mischief was occasioned by the wicked rising of the Fifth-monarchy-men.
But when those that were taken came to be executed,
they did us the justice to clear us openly from
having any hand in or knowledge of their plot.
After that, the king being continually importuned thereunto, issued a declaration,
"`That Friends should be set at liberty without paying fees.`"
But great labour, travail, and pains were taken, before this was obtained;
for Thomas Moor and Margaret Fell went often to the king about it.^
footnote:[Among the Swarthmore collection of MSS.
has been found a narrative of an interview Thomas Moor had with the king,
which has been printed in _Letters of Early Friends_, p. 92,
to which the reader is referred.
It is endorsed by George Fox thus:--"`What the king said to T. Moor,
1660,14th of 10th month.`"
It will be remembered Thomas Moor was formerly a justice of the peace,
and was convinced by George Fox, as related in the early part of this journal.]

Much blood was shed this year, many of the old king`'s judges being hung, drawn,
and quartered.
Amongst them that so suffered, Colonel Hacker was one,
who sent me prisoner from Leicester to London in Oliver`'s time,
of which an account is given before.
A sad day it was, and a repaying of blood with blood.
For in the time of Oliver Cromwell, when several men were put to death by him,
being hung, drawn, and quartered for pretended treasons, I felt from the Lord God,
that their blood would be required; and I said as much then to several.
And now upon the king`'s return, when several that had been against him were put to death,
as the others that were for him had been before by Oliver, this was sad work,
destroying people contrary to the nature of Christians,
who have the nature of lambs and sheep.
But there was a secret hand in bringing this day
upon that hypocritical generation of professors,
who, being got into power, grew proud, haughty, and cruel beyond others,
and persecuted the people of God without pity.
Therefore when Friends were under cruel persecutions
and sufferings in the Commonwealth`'s time,
I was moved of the Lord to write to Friends to draw up accounts of their sufferings,
and lay them before the justices at their sessions; and if they would not do justice,
then to lay them before the judges at the assize; and if they would not do justice,
then to lay them before the parliament, the protector and his council,
that they might all see what was done under their government;
and if they would not do justice, then to lay it before the Lord,
who would hear the cries of the oppressed,
and of the widows and fatherless whom they had made so.
For that which we suffered for, and for which our goods were spoiled,
was our obedience to the Lord in his Power and in his Spirit,
who was able to help and to succour, and we had no helper in the earth but him.
And he heard the cries of his people,
and brought an overflowing scourge over the heads of all our persecutors,
which brought a dread, and a fear amongst and on them all:
so that those who had nicknamed us (who are the
children of light) and in scorn called us Quakers,
the Lord made to quake;
and many of them would have been glad to have hid themselves amongst us;
and some of them, through the distress that came upon them,
did at length come to confess to the truth.
O! the daily reproaches, revilings, and beatings we underwent amongst them,
even in the highways, because we could not put off our hats to them,
and for saying Thou and Thee to them!
O! the havoc and spoil the priests made of our goods,
because we could not put into their mouths and give them tithes;
besides casting into prisons, and laying great fines upon us, because we could not swear!
But for all these things did the Lord God plead with them.
Yet some were so hardened in their wickedness,
that when they were turned out of their places and offices, they said,
"`If they had power, they would do the same again.`"
And when this day of overturning was come upon them, they said,
"`It was all on account of us.`"
Wherefore I was moved to write to them, and ask them,
"`Did we ever resist them when they took away our ploughs and plough-gears,
our carts and horses, our corn and cattle, our kettles and platters from us, whipped us,
set us in the stocks, and cast us into prison,
and all this only for serving and worshipping God in spirit and truth,
and because we could not conform to their religions, manners, customs, and fashions?
Did we ever resist them?
Did we not give them our backs to beat, and our cheeks to pull off the hair,
and our faces to spit on?
Had not their priests, that prompted them on to such work,
pulled them with themselves into the ditch?
Why then would they say,
'`It was all through of us,`' when it was owing to themselves and their priests,
their blind prophets, that followed their own spirits,
and could foresee nothing of these times and things that were come upon them,
which we had long forewarned them of, as Jeremiah and Christ had forewarned Jerusalem.
They had thought to weary us out, and undo us, but they undid themselves.
Whereas we could praise God, notwithstanding all their plundering of us,
that we had a platter, a horse, and plough still.`"

Many ways were these professors warned, by word, by writing, and by signs;
but they would believe none, till it was too late.
William Sympson^
footnote:[This is probably the Friend of whom there is some
account in _Piety Promoted,_ vol. i., p. 71.
He was born in Lancashire, and receiving the Truth,
became a faithful minister of it, for which he was often imprisoned,
and underwent cruel and hard sufferings.
In 1670, he went to Barbadoes with John Burnyeat, to preach the gospel in that island,
but after having some service there, he was taken ill of a fever,
during which he felt great peace and consolation of spirit,
and signified "`he should die.`"
He was often praising and glorifying God after this manner:
"`O! all that is within me praise and magnify the Lord God,
who is worthy for ever of all glory; everlasting praises to the God of my life,
who only is worthy, and lives over all, and is above all, God blessed for ever. Amen.`"
He died in much peace and quietness.]
was moved of the Lord to go, several times for three years,
naked and barefoot before them, as a sign unto them, in markets, courts, towns, cities,
to priests`' and great men`'s houses, telling them,
"`So should they be stripped naked, as he was stripped!`"
And sometimes he was moved to put on sackcloth, and besmear his face, and tell them,
"`So would the Lord God besmear all their religion, as he was besmeared.`"
Great sufferings did that poor man undergo,
sore whippings with horse-whips and coach-whips on his bare body,
grievous stonings and imprisonments, in three years`' time, before the king came in,
that they might have taken warning; but they would not:
they rewarded his love with cruel usage.
Only the mayor of Cambridge did nobly to him, for he put his gown about him,
and took him into his house.

Another Friend, Robert Huntingdon,
was moved of the Lord to go into Carlisle steeple-house, with a white sheet about him,
amongst the great Presbyterians and Independents there,
to show them that the surplice was coming up again: and he put a halter about his neck,
to show them that a halter was coming upon them;
which was fulfilled upon some of our persecutors not long after.

Another, Richard Sale, living near Chester, being constable of the place where he lived,
had a Friend sent to him with a pass,
whom those wicked professors had taken up for a vagabond,
because he travelled in the work of the ministry;
and this constable being convinced by the Friend, that was thus brought to him,
gave him his pass and liberty, and was afterwards himself cast into prison.
After this, on a lecture-day, Richard Sale was moved to go to the steeple-house,
in the time of their worship,
and to carry those persecuting priests and people a lantern and candle,
as a figure of their darkness; but they cruelly abused him,
and like dark professors as they were, put him into their prison called Little-Ease;
and so squeezed his body therein, that not long after he died.^
footnote:[Richard Sale, the constable who became convinced,
was an undaunted reproacher of vice.
The place in which he lost his life,
called "`Little Ease,`" is described to have been "`a hole hewed out in a rock;
the breadth across, seventeen inches; from the back to the inside of the great door,
at the top, seven inches; at the shoulders, eight inches; at the breast,
nine inches and a half; from the top to the bottom, one yard and a half,
with a device to lessen the height, as they are minded to torment the persons put in,
by draw-boards which shoot over the two sides to a yard height,
or thereabout.`"
{footnote-paragraph-split}
In this place they tormented many of those who were induced,
with Christian courage, to reprove the vices, either of ministers, magistrates,
or people.
Richard Costrop, for preaching repentance in the streets,
was put in Little Ease till next day, and then, by the Mayor, sent to Bridewell.
Thomas Yarwood, who, as the Mayor and Aldermen were going to a customary feast,
with music playing before them, dared to remind them wherein real Christianity stood,
viz., in true holiness and the fear of the Lord, was sent to Little Ease,
and kept there five hours; by which he, being but a weak sickly man,
was much bruised and hurt.
William Sympson, attempting, in Christian love, to exhort the people,
after their public preacher had ended his sermon, was first put in the stocks,
and afterwards kept in Little Ease nine hours.
When, next morning, he complained to the Mayor of his cruel usage,
he was sent again to the same place, after the Sheriff, in the Mayor`'s presence,
had struck him in the face, so that he bled very much.
Edward Morgan,
complaining to the Mayor against a drunken fellow who had grossly abused him,
was sent to Little Ease for not putting off his hat when he made that complaint,
and the drunkard went unpunished; as did also a servant who had robbed his master,
a Friend, the master being, by this same magistrate, imprisoned eleven weeks,
because he would not swear to the fact of the robbery.
{footnote-paragraph-split}
Into this place was the Friend above named (Richard Sale) put several times,
in 1656-1657, for three, four, five, and eight hours together.
Being corpulent, it required the strength of four men to thrust him in.
In doing which, they crushed him till the blood gushed out of his mouth and nose.
He survived the last torture but two months,
and died imputing his death to the cruelty of his persecutors.]
Many warnings of many sorts were Friends moved, in the power of the Lord,
to give to that generation; which they not only rejected, but abused Friends,
calling us giddy-headed Quakers;
but God brought his judgments upon those persecuting priests and magistrates.
For when the king came in, most of them were turned out of their places and benefices,
and the spoilers were spoiled: and then we could ask them,
"`Who were the giddy heads now?`"
Then many confessed we had been true prophets to the nation, and said,
"`Had we cried against some priests only, they should have liked us then;
but crying against all made them dislike us.`"
But now they saw those priests, which were then looked upon to be the best,
were as bad as the rest.
For indeed, some of those that were counted the most eminent,
were the bitterest and greatest stirrers up of the magistrates to persecution;
and it was a judgment upon them to be denied the free
liberty of their consciences when the king came in,
because when they were uppermost,
they would not have liberty of conscience granted to others.
One Hewes, of Plymouth, a priest of great note in Oliver`'s days,
when some liberty was granted,
prayed "`that God would put it into the hearts of the chief magistrates of the nation,
to remove this cursed toleration.`"
Others of them prayed against it under the name of Intolerable Toleration.
But a while after, when the king was come in,
and priest Hewes turned out of his great
benefice for not conforming to the Common Prayer,
a Friend of Plymouth meeting with him, asked,
"`Whether he would account toleration accursed now?`"
and "`Whether he would not now be glad of a toleration?`"
To which the priest returned no answer, save by the shaking of his head.
But as stiff as these men were then against toleration,
it is well known that many of them petitioned the king for toleration,
and for meeting-places, and paid for licenses too.
But to return to the present time, the latter end of the year 1600 and beginning of 1601.

Although those Friends that had been imprisoned on the
rising of the Monarchy-men were set at liberty,
meetings were much disturbed, and great Bufferings Friends underwent.
For besides what was done by officers and soldiers,
many wild fellows and rude people often came in.
There came one time, when I was at Pall-Mail,
an ambassador with a company of Irishmen and rude fellows;
the meeting was over before they came, and I was gone up into a chamber,
where I heard one of them say, "`He would kill all the Quakers.`"
I went down to him, and was moved in the power of the Lord to speak to him.
I told him, "`The law said, '`an eye for an eye,
and a tooth for a tooth;`' but thou threatenest to kill all the Quakers,
though they have done thee no hurt.
But,`" said I, "`here is gospel for thee: here is my hair, here is my cheek,
and here is my shoulder,`" turning it to him.
This came so over him, that he and his companions stood as men amazed, and said,
if that was our principle, and if we were as we said,
they never saw the like in their lives.
I told them, what I was in words, I was the same in life.
Then the ambassador, who had stood without, came in;
for he said that Irish colonel was such a desperate man,
that he durst not come in with him, for fear he should do us some mischief;
but truth came over him, and he carried himself lovingly towards us;
as also did the ambassador; for the Lord`'s power was over them all.

At Mile-End Friends were kept out of their meeting-place by soldiers,
but they stood nobly in the truth, valiant for the Lord`'s name;
and at last the truth gave them dominion.

About this time we had an account that John Love, a Friend,
that was moved to go and bear testimony against the idolatry of the Papists,
was dead in prison at Rome: it was suspected he was privately put to death in prison.
John Perrot was also a prisoner there, and being released,
came over again 5 but after his arrival here, he, with Charles Baily and others,
turned aside from the unity of Friends and truth.
Whereupon I was moved to issue a paper,
declaring how the Lord would blast him and his followers,
if they did not repent and return,
and that they should wither like the grass on the house-top, which many of them did;
but others returned and repented.

Also before this time we received account from New England,
that the government there had made a law to banish the Quakers out of their colonies,
upon pain of death, in case they returned; and that several Friends,
having been so banished, and returning, were taken, and actually hung;
and that many more were in prison,
in danger of the like sentence being executed upon them.^
footnote:[The persecution of the Quakers in New England,
by the Puritans and Independents,
who had themselves fled from home to enjoy religious liberty, formed a dreadful scene,
the very recital of which is revolting to humanity.
Some they caused to have their ears cut off; and, amongst many other cruelties,
which would fill a volume, they ordered three Quaker women to be stripped to the waist,
and flogged through eleven towns, a distance of eighty miles,
in all the severity of frost and snow.
But, as if this was not enough,
they actually hanged three men and one woman for Christ`'s sake,
who all acquitted themselves, at their awful exit,
with that firmness and submission which a Christian martyr is
enabled to sustain at such an hour of nature`'s extremity,
giving full proof of their sincerity and trust in the goodness and support of Him,
who had called them to make a public profession of his
name before a wicked and perverse generation.
Their names were--William Robinson, Marmaduke Stevenson, William Leddra,
and Mary Dyer.
{footnote-paragraph-split}
On the day appointed for the execution of these innocent victims,
they were led to the gallows by military officers,
accompanied by a band of about 200 armed men,
besides many horsemen--a measure which plainly indicated that
some fear of popular indignation was apprehended;
and, that no appeal might be made to the feelings of the multitude,
a drummer was appointed to march before the condemned persons, to beat the drum,
especially when any of them attempted to speak.
{footnote-paragraph-split}
Glorious signs of heavenly joy and gladness were
visible in the countenances of these holy martyrs,
who walked hand in hand to the place where they were to suffer.
"`This is to me an hour of the greatest joy,`" exclaimed Mary Dyer; adding,
that no eye could see, no ear could hear, no tongue could utter,
no heart could understand,
the sweet refreshings of the Spirit of the Lord which she then felt.
{footnote-paragraph-split}
Being come to the ladder,
and having taken leave of each other with lender affection,
they yielded up their lives into the hands of their enemies, Robinson`'s last words being,
"`I suffer for Christ, in whom I live, and for whom I die;`" and those of Stevenson,
"`This day shall we be at rest with the Lord.`"
William Leddra,
patiently submitting himself whilst the executioner put the halter round his neck, said,
"`I commit my righteous cause unto thee, O God;`" and, as he was turned off,
died with these words, "`Lord Jesus, receive my spirit!`"
When Mary Dyer ascended the ladder,
she was told by some of the standers-by that even now, if she would obey them,
she might come down and save her life.
But this magnanimous sufferer shrank not from her doom, well knowing in whom,
and for whom she was about to die; she contentedly laid down her life, saying,
"`In obedience to the will of the Lord, I abide faithful unto death.`"
`    "`We, too, have had our martyrs. Such wert thou,
         Illustrious woman! though the starry crown
     Of martyrdom has sat on many a brow,
         In the world`'s eye, of far more wide renown.
     - - - - - - - - - - - - - - - - - - - - - - -
     Yet the same spirit graced thy fameless end,
         Which shone in Latimer and his compeers;
     Upon whose hallowed memories still attend
         Manhood`'s warm reverence, childhood`'s guileless tears.
     - - - - - - - - - - - - - - - - - - - - - - -
     Well did they win them; may they keep them long!
         Their names require not praise obscure as mine,
     Nor does my muse their cherish`'d memories wrong,
         By this imperfect aim to honour thine.
     - - - - - - - - - - - - - - - - - - - - - - -
     Heroic martyr of a sect despised!
         Thy name and memory to my heart are dear:
     Thy fearless zeal (in artless childhood prized)
         The lapse of years has taught me to revere.
     - - - - - - - - - - - - - - - - - - - - - - -
     Thy Christian worth demands no poet`'s lay,
         Historian`'s pen, nor sculptor`'s boasted art;
     What could the proudest tribute these can pay
         To thy immortal spirit, now impart?
     - - - - - - - - - - - - - - - - - - - - - - -
     Yet seems it like a sacred debt to give
         The brief memorial thou mayst well supply;
     Whose life display`'d how Christians ought to live.
         Whose death--how Christian martyrs calmly die.`" `
For further particulars of the New England persecution,
the reader is referred to Sewell`'s _History_;
Bowden`'s _History of Friends in America_;
Kelty`'s _Early Days in the Society of Friends;_
Hodgson`'s _Historical Memoirs,_ etc.]
When those were put to death, I was in prison at Lancaster,
and had a perfect sense of their sufferings, as though it had been myself,
and as though the halter had been put about my own neck;
though we had not at that time heard of it.
But as soon as we heard of it, Edward Burrough went to the king, and told him,
"`There was a vein of innocent blood opened in his dominions, which,
if it were not stopped, would overrun all.`"
To which the king replied, "`But I will stop that vein.`"
Edward Burrough said, "`Then do it speedily,
for we do not know how many may soon be put to death.`"
The king answered, "`As speedily as ye will.
Call,`" said he to some present, "`the secretary, and I will do it presently.`"
The secretary being called, a mandamus was forthwith granted.
A day or two after, Edward Burrough going again to the king,
to desire the matter might be expedited, the king said,
"`He had no occasion at present to send a ship thither, but if we would send one,
we might do it as soon as we chose.`"
Edward Burrough then asked the king,
"`if it would please him to grant his deputation to one called a Quaker,
to carry the mandamus to New England?`"
He said, "`Yes, to whom ye will.`"
Whereupon E. B. named Samuel Shattock, who being an inhabitant of New England,
was banished by their law, to be hung if he came again;
and to him the deputation was granted.
Then he sent for Ralph Goldsmith, an honest Friend, who was master of a good ship;
and agreed with him for £300, goods or no goods, to sail in ten days.
He forthwith prepared to set sail, and, with a prosperous gale,
in about six weeks arrived before the town of Boston, in New England,
upon a First-day morning.
Many passengers went with him, both of New and Old England, Friends,
whom the Lord moved to go to bear testimony against those bloody persecutors,
who had exceeded all the world in that age in their persecutions.

The townsmen at Boston seeing a ship come into the bay with English colours,
soon came on board, and asked for the captain.
Ralph Goldsmith told them, he was the commander.
They asked him, if he had any letters?
He said, "`Yes.`"
They asked, if he would deliver them?
He said, "`No, not today.`"
So they went on shore, and reported there was a ship full of Quakers,
and that Samuel Shattock was among them, who, they knew, was, by their law,
to be put to death, for coming again after banishment; but they knew not his errand,
nor his authority.
So all being kept close that day, and none of the ship`'s company suffered to land,
next morning, Samuel Shattock, the king`'s deputy, and Ralph Goldsmith,
the commander of the vessel, went on shore;
and sending back to the ship the men that landed them,
they two went through the town to the governor`'s (John Endicott) door, and knocked.
He sent out a man to know their business.
They sent him word, their business was from the king of England,
and they would deliver their message to none but the governor himself.
They were then admitted, and the governor came to them;
and having received the deputation and the mandamus, he put off his hat,
and looked upon them.
Then going out, he bid the Friends follow him.
He went to the deputy-governor, and after a short consultation, came out to the Friends,
and said, "`We shall obey his Majesty`'s commands.`"
After this the master gave liberty to the passengers to land;
and presently the noise of the business flew about the town,
and the Friends of the town and the passengers of the ship met together,
to offer up their praises and thanksgivings to God,
who had so wonderfully delivered them from the teeth of the devourer.
While they were thus met, a poor Friend came in, who,
being sentenced by their bloody law to die, had lain some time in irons,
expecting execution.
This added to their joy, and caused them to lift up their hearts in high praises to God,
who is worthy for ever to have the praise, the glory, and the honour;
for he only is able to deliver, to save,
and to support all that sincerely put their trust in him.
Here follows a copy of the mandamus:--

[.embedded-content-document.legal]
--

[.salutation]
"`Charles R.

"`Trusty and well beloved, we greet you well.
Having been informed that several of our subjects amongst you, called Quakers,
have been and are imprisoned by you, whereof some have been executed, and others,
as hath been represented unto us, are in danger to undergo the like,
we have thought fit to signify our pleasure in that behalf for the future;
and do hereby require, that if there be any of those people called Quakers amongst you,
now already condemned to suffer death or other corporal punishment,
or that are imprisoned, and obnoxious to the like condemnation,
you are to forbear to proceed any further therein;
but that you forthwith send the said persons, whether condemned or imprisoned,
over into this our kingdom of England,
together with the respective crimes or offences laid to their charge:
to the end such course may be taken with them here,
as shall be agreeable to our laws and their demerits.
And for so doing, these our letters shall be your sufficient warrant and discharge.
Given at our Court at Whitehall, the 9th day of September, 1661,
in the thirteenth year of our reign.`"

Subscribed: "`To our trusty and well beloved John Endicott, Esq.,
and to all and every other the governor or governors of our plantations of New England,
and of all the colonies thereunto belonging, that now are, or hereafter shall be:
and to all and every the ministers and officers
of our plantations and colonies whatsoever,
within the continent of New England.`"
By his Majesty`'s command.

[.signed-section-signature]
"`William Morris.`"

--

Some time after this several New England magistrates came over, with one of their priests.
We had several discourses with them concerning their murdering our Friends,
the servants of the Lord; but they were ashamed to stand to their bloody actions.
On one of these occasions I asked Simon Broadstreet, one of the New England magistrates,
"`Whether he had not a hand in putting to death those four servants of God,
whom they hung for being Quakers only, as they had nicknamed them?`"
He confessed he had.
I then asked him and the rest of his associates that were present,
"`Whether they would acknowledge themselves to be subject to the laws of England;
and if they did, by what laws they had put our Friends to death?`"
They said, "`They were subject to the laws of England;
and had put our Friends to death by the same law
that the Jesuits were put to death in England.`"
I asked them then, "`Whether they believed those Friends of ours,
whom they had put to death, were Jesuits or jesuitically affected?`"
They said, nay.
"`Then,`" said I, "`ye have murdered them,
if ye have put them to death by the law that Jesuits are put to death here in England,
and yet confess they were no Jesuits.
By this it plainly appears ye have put them to death in your own wills, without any law.`"
Then Simon Broadstreet, finding himself and his company ensnared by their own words,
asked, "`Did we come to catch them?`"
I told them, they had caught themselves,
and they might justly be questioned for their lives;
and if the father of William Robinson, one of them that were put to death, were in town,
it was probable he would question them, and bring their lives into jeopardy.
Here they began to excuse themselves, saying,
"`There was no persecution now amongst them:`"
but next morning we had letters from New England,
giving us account that our Friends were persecuted there afresh.
We went again, and showed them our letters, which put them both to silence and to shame;
and in great fear they seemed to be, lest some one should call them to account,
and prosecute them for their lives, especially Simon Broadstreet; for he had at first,
before so many witnesses, confessed he had a hand in putting our Friends to death,
that he could not get off from it; though he afterwards through fear shuffled,
and would have unsaid it again.
After this, he and the rest soon returned to New England again.

I went also to Governor Winthrop, and discoursed with him on these matters;
he assured me, "`He had no hand in putting our Friends to death,
or in any way persecuting them; but was one of them that protested against it.`"
These stingy persecutors of New England were a
people that fled thither out of Old England,
from the persecution of the bishops here;
but when they had got power into their own hands,
they so far exceeded the bishops in severity and cruelty,
that whereas the bishops had made them pay twelve pence a
Sunday (so called) for not coming to their worship here,
they imposed a fine of five shillings a-day upon such
as should not conform to their will-worship there;
and spoiled the goods of Friends that Could not pay it.
Besides, many they imprisoned, divers they whipped, and that most cruelly;
of some they cut Off the ears, and some they hanged;
as the books of Friends`' sufferings in New England largely show,
particularly that written by George Bishop, of Bristol, entitled, New England Judged.
Some of the old royalists were earnest with Friends to prosecute them, but we told them,
we left them to the Lord, to whom vengeance belongeth, and he would repay it.
And the judgments of God have since fallen heavy on
them for the Indians have been raised up against them,
and have cut off many of them.

About this time I lost a very good book, being taken in the printer`'s hands;
it was a useful teaching work, containing the signification and explanation of names,
parables, types, and figures in the Scriptures.
They who took it were so affected with it, that they were both to destroy it;
but thinking to make a great advantage of it, they would have let us have it again,
if we would have given them a great sum of money for it; which we were not free to do.

Before this, while I was prisoner in Lancaster castle,
the book called the _Battledore_ was published, which was written to show,
that in all languages Thou and Thee is the proper and
usual form of speech to a single person;
and You to more than one.
This was set forth in examples or instances taken from the Scriptures,
and books of teaching, in about thirty languages.
J+++.+++ Stubbs and Benjamin Furly took great pains in compiling it, which I set them upon;
and some things I added to it.
When it was finished, copies were presented to the king and his council,
to the bishops of Canterbury and London, and to the two universities one each;
and many purchased them.
The king said, it was the proper language of all nations; and the bishop of Canterbury,
being asked what he thought of it, was at a stand, and could not tell what to say to it.
For it did so inform and convince people, that few afterwards were so rugged toward us,
for saying Thou and Thee to a single person,
for which before they were exceedingly fierce against us.
Thou and Thee was a sore cut to proud flesh, and them that sought self-honour, who,
though they would say it to God and Christ,
could not endure to have it said to themselves.
So that we were often beaten and, abused, and sometimes in danger of our lives,
for using those words to some proud men, who would say,
"`What! you ill-bred clown, do you Thou me?`"
as though Christian breeding consisted in saying You to one;
which is contrary to all their grammars and teaching books,
by which they instructed their youth.

[.offset]
Now the bishops and priests being busy and eager to set up their form of worship,
and compel all to come to it, I was moved to give forth the following paper,
to open the nature of the true worship, which Christ set up, and which God accepts:--

[.embedded-content-document.paper]
--

"`Christ`'s worship is free in the Spirit to all men;
and such as worship in Spirit and in truth, are they whom God seeks to worship him;
for he is the God of truth, and is a Spirit, and the God of the spirits of all flesh.
He hath given to all nations of men and women breath and life, to live, and move,
and have their being in him;
and hath put into them an immortal soul So all are to be temples for him to dwell in;
and they that defile his temple will he destroy.
Now as the outward Jews, while they had their outward temple at Jerusalem,
were to go up thither to worship (which temple God hath long since thrown down,
and destroyed that Jerusalem, the vision of peace;
and cast off the Jews and their worship;
and instead thereof hath set up his gospel-worship in Spirit and in truth),
so now all are to worship in Spirit and in truth.
This is a free worship; for where the Spirit of the Lord is, and ruleth,
there is liberty; the fruits of the Spirit are seen, and will manifest themselves;
and the Spirit is not to be limited, but lived and walked in, that its fruits may appear.
The tares are such as hang upon the wheat, and thereby draw it down to the earth;
yet the tares and the wheat must grow together, till the harvest,
lest they that take upon them to pluck up the tares,
should pluck up the wheat with the tares.
The tares are such as worship not God in Spirit and in truth; but grieve the Spirit,
vex and quench it in themselves, and walk not in the truth;
yet will hang about the wheat, the true worshippers in the Spirit and in the truth.
Christ`'s church was never established by blood, nor held up by prisons;
neither was the foundation of it laid by carnal-weaponed men,
nor is it preserved by such.
But when men departed from the Spirit and truth,
they took up carnal weapons to maintain their outward forms,
and yet they cannot preserve them with their carnal weapons;
for one plucketh down another`'s form with his outward weapons.
And this work hath been among nominal Christians, since they lost the Spirit,
and spiritual weapons, and the true worship which Christ set up,
that is in Spirit and in truth, which they that worship in, are over all the tares.
All that would be plucking up the tares are forbidden by Christ,
who hath all power in heaven and earth given to him;
for the tares and the wheat must grow together till the harvest,
as Christ hath commanded.
The stone that smote the image became a great mountain, and filled the whole earth; now,
if the stone fill the whole earth, all nations must be temples for the stone.
All that say they travail for the seed,
and yet bring forth nothing but a birth of strife, contention, and confusion,
their fruit shows their travail to be wrong; for by the fruit,
the end of every one`'s work is seen, of what sort it is.`"

[.signed-section-signature]
G+++.+++ F.

--

About this time many Papists and Jesuits began to fawn upon Friends,
and talked where they came,
that of all sects the Quakers were the best and most self-denying people; and said,
"`It was a great pity they did not return to the holy mother church.`"
Thus they made a buzz among the people, and said,
"`They would willingly discourse with Friends.`"
But Friends were loth to meddle with them, because they were Jesuits,
looking upon it to be both dangerous and scandalous.
But when I understood it, I said to Friends,
"`Let us discourse with them, be they what they will.`"
So a time being appointed at Gerrard Roberts`'s house,
there came two of them like courtiers.
When we were met together, they asked our names, which we told them;
but we did not ask their names, for we understood they were called Papists,
and they knew we were called Quakers.
I asked them the same question that I had formerly asked a Jesuit, namely,
"`Whether the church of Rome was not degenerated from the primitive church,
from the Spirit, power, and practice, of the apostles`' times?`"
He to whom I put this question being subtle, said, "`He would not answer it.`"
I asked him, "`Why?`"
But he would show no reason.
His companion said, he would answer me; and said,
"`They were not degenerated from the primitive church times.`"
I asked the other, whether he was of the same mind?
He said, "`Yes.`"
Then I told them, that for better understanding one another,
and that there might be no mistake,
I would repeat my question over again after this manner,
"`Whether the church of Rome now was in the same purity, practice, power, and Spirit,
that the church in the apostles`' time was in?`"
When they saw we would be exact with them, they flew off, and denied that, saying,
"`It was presumption in any to say,
they had the same power and Spirit that the apostles had.`"
"`But I told them,
it was presumption in them to meddle with the words of Christ and his apostles,
and make people believe they succeeded the apostles,
and yet be forced to confess they were not in
the same power and Spirit the apostles were in.
This,`" said I, "`is a spirit of presumption, and rebuked by the apostles`' Spirit.`"
I showed them how different their fruits and practices were from those of the apostles.
Then one of them said, "`Ye are a company of dreamers.`"
"`Nay,`" said I, "`ye are the filthy dreamers, who dream ye are the apostles`' successors;
and yet confess ye have not the same power and Spirit they were in.
And are not they defilers of the flesh, who say, '`It is presumption in any to say,
they have the same power and Spirit the apostles had?`'
Now,`" said I, "`if ye have not the same power and Spirit the apostles had,
then it is manifest that ye are led by another power and
spirit than the apostles and primitive church were led by.`"
Then I began to tell them how that evil spirit, which they were led by,
had led them to pray by beads and images; to set up nunneries, friaries, and monasteries,
and to put people to death for their religion; and this practice of theirs,
I showed them, was below the law, and far short of the gospel, in which is liberty.
They were soon weary of this discourse, went away, and gave a charge, as we heard,
to the Papists, "`That they should not dispute with us,
or read any of our books;`" so we were rid of them.
But we had reasonings with all the other sects, as Presbyterians, Independents, Seekers,
Baptists, Episcopalians, Socinians, Brownists, Lutherans, Calvinists, Arminians,
Fifth-monarchy-men, Familists, Muggletonians, and Ranters;
none of which would affirm they had the same power and Spirit the apostles had,
and were in; so in that power and Spirit the Lord gave us dominion over them all.

As for the Fifth-monarchy men, I was moved to give forth a paper,
to manifest their error to them;
for they looked for Christ`'s personal coming in an outward form and manner,
and fixed the time to the year 1666;
at which time some of them prepared themselves when it thundered and rained,
thinking Christ was then come to set up his kingdom;
and they imagined they were to kill the whore without them.
But I told them, the whore was alive in them, and was not burned with God`'s fire,
nor judged in them with the same power and Spirit the apostles were in.
And their looking for Christ`'s coming outwardly to set up his kingdom,
was like the Pharisees`' "`Lo here`" and "`Lo there.`"
But Christ was come,
and had set up his kingdom above sixteen hundred years ago
(according to Nebuchadnezzar`'s dream and Daniel`'s prophecy),
and he had dashed to pieces the four monarchies, the great image, with its head of gold,
breast and arms of silver, belly and thighs of brass, legs of iron,
and feet part of iron and part of clay; and they were all blown away with God`'s wind,
as the chaff in the summer thrashing-floor.
And when Christ was on earth, he said,
"`His kingdom was not of this world;`" if it had been, his servants would have fought,
but it was not; therefore his servants did not fight.
Therefore all the Fifth-monarchy men, that are fighters with carnal weapons,
are none of Christ`'s servants, but the beast`'s and the whore`'s. Christ said,
"`All power in heaven and in earth is given to me:`" so then
his kingdom was set up above sixteen hundred years ago,
and he reigns.
"`And we see Jesus Christ reign,`" said the apostle; and he shall reign,
till all things be put under his feet; though all things are not yet put under his feet,
nor subdued.

This year several Friends were moved to go beyond the seas,
to publish Truth in foreign countries.
John Stubbs, and Henry Fell,
and Richard Costrop were moved to go towards China and Prester John`'s country;
but no masters of ships would carry them.
With much ado they got a warrant from the king;
but the East India Company found ways to avoid it,
and the masters of their ships would not carry them.
Then they went into Holland, hoping to get passage there,
but none could they get there either.
Then John Stubbs and Henry Fell took shipping for Alexandria in Egypt,
intending to go by the caravans from thence.
Meanwhile Daniel Baker being to go to Smyrna, drew Richard Costrop,^
footnote:[This Richard Costrop (or Scostrop) was born in 1628.
He was originally a sore persecutor of Friends,
but becoming convinced of the soundness of their principles,
he at length joined the Society, and preached the faith which once he destroyed,
travelling for this object into various parts of Europe.
He seems to have been chiefly instrumental in establishing the meeting at Scalehouse.
He appears to have been a man of some estate, but left all,
and spent his days in the service of the Gospel.
In a document issued by Friends of Settle Monthly Meeting in 1704, it is said of him,
"`his memory is sweet this day among the brethren.`"
See _Life, etc. of William and Alice Ellis,_ by James Backhouse, pp.
278, 279, etc.]
contrary to his own freedom, to go along with him;
and in the passage Bichard falling sick, Daniel Baker left him so in the ship,
where he died: but that hard-hearted man afterwards lost Ms own condition.

John Stubbs and Henry Fell reached Alexandria;
but they had not been long there before the English consul banished them:
yet before they came away, they dispersed many books and papers,
for opening the principles and way of truth to the Turks and Grecians.
They gave the book called, The Pope`'s Strength Broken, to an old friar,
for him to give or send to the Pope; which, when the friar had perused,
he placed his hand on his breast, and confessed, "`What was written therein was truth;
but,`" said he, "`if I should confess it openly, they would burn me.`"
John Stubbs and Henry Fell, not being suffered to go further, returned to England,
and came to London again.
John had a vision, that the English and Dutch, who had joined together not to carry them,
would fall out one with the other: and so it came to pass.

Having now stayed in London some time, I felt drawings to visit Friends in Essex.
So I went down to Colchester, where I had very large meetings; and thence to Coggeshall;
not far from which a priest was convinced, and I had a meeting at his house.
Travelling a little up and down in those parts, and visiting Friends in their meetings,
I returned pretty quickly to London, where I found great service for the Lord;
for a large door was opened, many flocked in to our meetings,
and the Lord`'s truth spread mightily this year.
Yet Friends had great travail and sore labour,
the rude people having been so heightened by the Monarchy-men`'s rising a little before.
But the Lord`'s power was over all, and in it Friends had dominion;
though we had not only those sufferings without, but sufferings within also,
by John Perrot and his company; who, giving heed to a spirit of delusion,
sought to introduce among Friends that evil and uncomely
practice of "`keeping on the hat in time of public prayers.`"
Friends had spoken to him and many of his followers about it,
and I had written to them concerning it;
but he and some others rather strengthened themselves against us.^
footnote:[John Perrot was one who at this time caused great
distress and trouble to the faithful members of the Society,
from giving way to self-importance and extravagant notions.
For particulars, the reader is referred to Sewell`'s _History;_
and to Hodgson`'s _Historical Memoirs._
{footnote-paragraph-split}
Whilst the Society kept steadily pursuing its path,
and increasing in numbers,
notwithstanding the persecutions to which its members were everywhere subjected,
it was not to be expected that every individual who was found within its precincts
should have been rightly prepared for the station which he might have assumed.
It would have been indeed remarkable, if,
in the multitude of those who went forth in that day of zeal,
in the service of the ministry,
there had not been instances of men who had taken upon them
(perhaps mistakenly) the office of a gospel minister,
without waiting for the preparation and the call.
And it would have been still more surprising if such forward
spirits had proved firm in the day of outward trial,
or of inward fascinations and snares of the enemy.]
Wherefore feeling the judgment of truth rise against it,
I gave forth the following as a warning to all that were concerned therein

[.embedded-content-document.epistle]
--

"`Whosoever is tainted with this spirit of John Perrot, it will perish.
Mark his and their end,
who are turned into those outward things and janglings about them,
and that which is not savoury;
all which is for perpetual judgment--is to be swept and
cleansed out of the camp of God`'s elect.
This is to that spirit,
that is gone into jangling about that which is below (the rotten
principle of the old Ranters)---gone from the invisible power of God,
in which is the everlasting fellowship;
and thus many who now clamour and speak against them that are in the power of God,
are become like the untimely figs, and like the corn on the house-top.
O! consider! the light and power of God goes over you all,
and leaves you in the fretting nature,
out of the unity which is in the everlasting light, life, and power of God.
Consider this, before the day be gone from you; and take heed,
that your memorial be not rooted out from among the righteous.`"

[.signed-section-signature]
G+++.+++ F.

--

Among the exercises and troubles Friends had from without,
one was regarding Friends`' marriages, which sometimes were called in question.
This year there was a cause tried at the assize at Nottingham concerning one.
The case was thus.
Some years before two Friends were joined together in marriage amongst Friends,
and lived together as man and wife about two years.
Then the man died, leaving his wife with child, and an estate in lands of copyhold.
When the woman was delivered, the jury presented the child heir to its father`'s lands,
and accordingly the child was admitted; afterwards another Friend married the widow.
After that, a man that was near of kin to her former husband,
brought his action against the Friend that had last married her,
endeavouring to dispossess them, and deprive the child of the inheritance,
and to possess himself thereof as next heir to the woman`'s first husband.
To effect this, he endeavoured to prove the child illegitimate, alleging,
"`the marriage was not according to law.`"
In opening the cause, the plaintiff`'s counsel used unseemly words concerning Friends,
saying, "`That they went together like brute beasts,`" with other ill expressions.
After the counsels on both sides had pleaded,
the judge (viz. Judge Archer) took the matter in hand, and opened it to the jury,
telling them,
that "`There was a marriage in Paradise when Adam took Eve and Eve took Adam,
and that it was the consent of the parties that made a marriage.
As for the Quakers,`" he said, "`he did not know their opinions,
but he did not believe they went together as brute beasts, as had been said of them,
but as Christians; and therefore he believed the marriage was lawful,
and the child lawful heir.`"
And the better to satisfy the jury,
he brought them a case to this purpose:--"`A man that was weak of body, and kept his bed,
had a desire in that condition to marry,
and declared before witnesses that he took such a woman to be his wife,
and the woman declared that she took that man to be her husband.
This marriage was afterwards called in question;
and (as the judge said) all the bishops at that
time concluded it to be a lawful marriage.`"
Hereupon the jury gave in their verdict for the Friend`'s child,
against the man that would have deprived it of its inheritance.

[.offset]
About this time the oaths of allegiance and supremacy were tendered to Friends,
as a snare, because it was known we could not swear, and thereupon many were imprisoned,
and divers premunired.
Upon that occasion Friends published in print "`The grounds and reasons why
they refused to swear;`" besides which I was moved to issue these few lines,
to be given to the magistrates:--

[.embedded-content-document.address]
--

"`The world saith, '`Kiss the book;`'
but the book saith, '`Kiss the Son, lest he be angry.`'
And the Son saith,
'`Swear not at all,`' but keep to Yea and Nay in all your communications;
for whatsoever is more than this cometh of evil.
Again, the world saith, '`Lay your hand on the book,`' but the book saith,
'`Handle the word;`' and the word saith, '`Handle not the traditions,`' nor the inventions,
nor the rudiments of the world.
And God saith, '`This is my beloved Son, hear Him,`' who is the life, the truth, the light,
and the way to God.`"

[.signed-section-signature]
G+++.+++ F.

--

Now there being very many Friends in prison in the nation,
Richard Hubberthorn and I drew up a paper concerning them,^
footnote:[About this time persecution was very hot,
and from estimates deduced from documents of the period, it is probable that,
in 1661 or 1662, there were no less than 4500 Friends in prison, in England and Wales,
at one time, for meeting to worship God, refusing to swear, etc.
And in such prisons too I They who would know what the
miseries of prisoners have been in England,
let them read Sewell`'s _History,_
which exhibits such a scene of savage persecution on the one hand,
and firmness and patience in suffering on the other, as is not easily paralleled.
Little known as these things are, it will hardly be credited now,
that to such a length was hatred carried against the Quakers, that few of them,
except those below the cognizance of the magistrates, were not in prison,
at one time or other,
for their religious faith.
{footnote-paragraph-split}
The interruption of family ties,
the breaking up of households, the loss to many of all means of support,
were hard and cruel sufferings for conscience`' sake,
but they were grievously aggravated at this period by
the damp and filthy condition of the prisons,
holes, and dungeons in which the sufferers were confined,
as well as by their very crowded condition.
And to all these circumstances of trial, must be added those of personal abuse, fines,
distraints, and, it may strictly be said, of wholesale robberies they endured.
Some died of the beatings which they received in the breaking up of their meetings,
and many from the filthy and close state of the prisons,
in some of which they were so closely packed
that they had to take it by turns to stand up,
whilst others sat or lay down.
They were also often overrun with lice and other vermin.]
and got it delivered to the king,
that he might understand how we were dealt with by his officers.
It was directed thus:--

[.embedded-content-document.letter]
--

[.letter-heading]
For the King

[.salutation]
"`Friend,

"`Who art the chief ruler of these dominions,
here is a list of some of the sufferings of the people of God, in scorn called Quakers,
that have suffered under the changeable powers before thee,
by whom there have been imprisoned,
and under whom there have suffered for good conscience`' sake,
and for bearing testimony to the truth as it is in Jesus,
'`three thousand one hundred and seventy-three persons and there lie yet in prison,
in the name of the Commonwealth, '`seventy-three persons that we know of.
And there died in prison in the time of the Commonwealth, and of Oliver and Richard,
the protectors, through cruel and hard imprisonments, upon nasty straw and in dungeons,
'`thirty-two persons.`'
There have been also imprisoned in thy name, since thy arrival,
by such as thought to ingratiate themselves thereby with thee,
'`three thousand sixty and eight persons.`'
Besides this, our meetings are daily broken up by men with clubs and arms,
though we meet peaceably,
according to the practice of God`'s people in the primitive times,
and our Friends are thrown into waters, and trod upon,
till the very blood gushes out of them; the number of which abuses can hardly be uttered.
Now this we would have of thee,
to set them at liberty that lie in prison hi the names of the Commonwealth,
and of the two Protectors, and them that lie in thy own name, for speaking the truth,
and for good conscience`' sake, who have not lifted up a hand against thee or any man;
and that the meetings of our Friends, who meet peaceably together in the fear of God,
to worship him, may not be broken up by rude people with their clubs, swords, and staves.
One of the greatest things that we have suffered for formerly, was,
because we could not swear to the Protectors and all the changeable governments;
and now we are imprisoned because we cannot take the oath of allegiance.
Now, if our yea be not yea, and nay, nay, to thee, and to all men upon the earth,
let us suffer as much for breaking that, as others do for breaking an oath.
We have suffered these many years, both in lives and estates,
under these changeable governments, because we cannot swear, but obey Christ`'s doctrine,
who commands, '`we should not swear at all`' (Matt. 5. James 5.),
and this we seal with our lives and estates, with our yea and nay,
according to the doctrine of Christ.
Hearken to these things, and so consider them in the wisdom of God,
that by it such actions may be stopped; thou that hast the government, and mayest do it.
We desire that all that are in prison may be set at liberty,
and that for the time to come they may not be
imprisoned for conscience and for truth`'s sake;
and if thou question the innocency of their sufferings,
let them and their accusers be brought up before thee,
and we shall produce a more particular and full account of their sufferings,
if required.`"^
footnote:[An abruptness of style,
and an apparent deficiency of courtesy due from subjects to their sovereign,
pervade the foregoing address.
When we take into consideration the long catalogue of
grievous and unjustifiable wrongs therein enumerated;
that these had been reiterated by the suffering party with scarcely a shadow of redress;
and that all these evils were now inflicted in direct
contradiction to the king`'s proclamation from Breda,
and also of his own royal word of promise to the Quakers after his restoration;
it is quite possible the style was intentional on the part of the writers, who,
like the rest of his subjects,
had by this time found out that the fair promises of
Charles II. were not to be relied upon;
and therefore, in this instance,
felt it their duty to confine themselves to a manly and
straightforward statement of the truth of their grievances.
It offers an exception to the generally respectful tenor of the addresses of Friends,
which are by no means wanting in proper courtesy.--(Marsh.)]

[.signed-section-signature]
G+++.+++ F. and R. H.

--

I mentioned before, that in the year 1650,
I was kept prisoner six months in the house of correction at Derby,
and that the '`keeper of the prison, a cruel man,
and one that had dealt very wickedly towards me, was smitten in himself,
the plagues and terrors of the Lord falling upon him because thereof.
This man, being afterwards convinced of truth, wrote me the following letter:--.

[.embedded-content-document.letter]
--

[.salutation]
"`Dear Friend,

"`Having such a convenient messenger,
I could do no less than give thee an account of my present condition, remembering,
that in the first awakening of me to a sense of life and of the inward principle,
God was pleased to make use of thee as an instrument.
So that sometimes I am taken with admiration
that it should come by such a means as it did;
that is to say, that Providence should order thee to be my prisoner,
to give me my first real sight of the truth.
It makes me many times think of the jailer`'s conversion by the apostles.
O happy George Fox! that first breathed that
breath of life within the walls of my habitation!
Notwithstanding my outward losses are since that time such,
that I am become nothing in the world,
yet I hope I shall find that all these light afflictions, which are but for a moment,
will work for me a far more exceeding and eternal weight of glory.
They have taken all from me, and now, instead of keeping a prison,
I am rather waiting the time when I shall become a prisoner myself.
Pray for me, that my faith fail not, but that I may hold out unto death,
that I may receive a crown of life.
I earnestly desire to hear from thee, and of thy condition,
which would very much rejoice me.
Not having else at present but my kind love unto thee,
and all Christian Friends with thee, in haste, I rest, thine, in Christ Jesus,

[.signed-section-signature]
"`Thomas Shabman.`"

[.signed-section-context-close]
Derby, 22nd of 4th Month, 1662.

--

There were two of our Friends in prison in the Inquisition at Malta, both women;
Catherine Evans and Sarah Cheevers.^
footnote:[Catherine Evans and Sarah Cheevers suffered a dreadful
confinement for about four years in the Inquisition at Malta,
of which a full account has been published.
A more condensed one may be seen in _Select Miscellanies,_ v. p. 56-68.
`    "`--These ministers of Christ did leave
     Their homes in England, faithfully to hew
     The Saviour`'s message into Eastern lands;
     And here, at Malta, they were seized upon
     By bigoted intolerance, and shut
     "`Within this fearful engine of the Pope.
     Priests and inquisitors assail them there,
     And urge the claims of Popery. The rack
     And cruel deaths are threatened; and again
     Sweet liberty is offered, as the price
     Of their apostacy. All, all in vain!
         For years these tender women have been thus
     Victims of cruelty. At times apart,
     Confined in gloomy, solitary cells.
     But all these efforts to convert them failed;
     The inquisition had not power enough
     To shake their faith and confidence in Him,
     "`Whose holy presence anciently was seen
     To save his children from devouring flames;
     He from this furnace of affliction brought
     These persecuted women, who came forth
     Out of the burning, with no smell of fire
     Upon their garments, and again they trod
     Their native land, rejoicing.`" `
Some idea of the sufferings of these poor creatures may be formed from the fact
of their __often lying down before the crevice of their prison-door,
to inhale what air could be obtained from it.__
In this state their skin was parched, the hair fell off their heads,
and they frequently fainted;
and, in moments when the strength and glory of the Divine presence
was not so feelingly experienced as at others,
it cannot occasion surprise that, through human weakness, they wished for death;
their distress sometimes being such, that when it was day they longed for night,
and yet when night came it was only to prompt the constant sigh for returning light.
Yet the heavenly content which, on the whole,
was the portion of these sufferers for Christ`'s sake,
in this dark and cloudy day, was remarkable.
One of them, in writing to her relatives in England, says,
"`We are witnesses that the Lord can provide a table in the wilderness,
both spiritual and temporal.
In all our afflictions and miseries, the Lord remembered mercy,
and did not leave nor forsake us, nor suffer his faithfulness to fail;
but caused the sweet drops of his mercy to distil upon us,
and the brightness of his glorious countenance to shine into our hearts.`"
{footnote-paragraph-split}
The other of these suffering captives writes that she could not, by pen and paper,
set forth the extent of the love of God to her soul,
in fulfilling his gracious promises to her in the wilderness.
They were indeed enabled to "`sing the Lord`'s song in a strange land;`"
and, in the midst of heaviness,
"`their mouths were often filled with laughter, and their tongues with joy,`"
being strong in the faith, giving praises and glory to God.
{footnote-paragraph-split}
The following, composed by them in the Inquisition,
affords a view of the motives and abilities of these devoted women:
`    "`In prisons strong, and dungeons deep.
     To God alone we cry and weep;
     Our sorrows none can learn nor read,
     But those that in our path do tread.
         But He whose beauty shineth bright.
     Who turneth darkness into light,
     Makes cedars bow, and oaks to bend,
     To him that`'s sent to the same end;
     He is a fountain pure and clear,
     His crystal streams run far and near
     To cleanse all those that come to Him
     For to be healed of their sin:
     All them that patiently abide,
     And never swerve nor go aside,
     The Lord will free them out of all
     Bondage, captivity, and thrall.`" `
It was not in the Inquisition only that these women suffered,
but much also in England.
In 1657, Catherine Evans was stripped, and tied to a whipping-post
in the market-place at Salisbury, and there whipped,
for exhorting the people to repentance.
Her husband, a man of property, also suffered several imprisonments,
and at last died in prison for obeying our Saviour`'s command, "`Swear not at all.`"]
I was told that one, called the Lord D`'Aubeny +++[+++a Roman Catholic priest],
could procure their liberty, so I went to him;
and having informed him concerning their imprisonment,
desired him to write to the magistrates there for their release.
He readily promised he would; and,
"`if I would come again within a month, he would tell me of their discharge.`"
I went again about that time, and he said,
"`he thought his letters had miscarried, because he had received no answer.`"
But he promised he would write again, and he did so; and they were both set at liberty.

With this great man I had much reasoning about religion,
and he confessed that Christ hath enlightened every man that cometh into the world,
with his spiritual light; that he tasted death for every man; that the grace of God,
which brings salvation, hath appeared to all men,
and that it would teach them and bring their salvation, if they obeyed it.
Then I asked him, "`what would they (the Papists) do with all their relics and images,
if they should own and believe in this light,
and receive the grace to teach them and bring their salvation?`"
He said, "`those things were but policies, to keep people in subjection.`"
He was very free in discourse; I never heard a Papist confess so much as he did.

[.offset]
Though several about the court began to grow loving to Friends,
yet persecution was very hot, and several Friends died in prison.
Whereupon I gave forth a little paper concerning the grounds and rise of persecution;
which was thus:--

[.embedded-content-document.paper]
--

"`All the sufferings of the people of God in all ages were,
because they could not join in the national religions and worships,
which men had made and set up;
and because they would not forsake God`'s religion and his worship, which he had set up.
You may see through all chronicles and histories,
that the priests joined with the powers of the nation; the magistrates, soothsayers,
and fortune-tellers, all united against the people of God,
and imagined vain things against them in their councils.
When the Jews did wickedly, they turned against Moses;
and when the Jewish kings transgressed the law of God, they persecuted the prophets,
as may be seen in the prophets`' writings.
When Christ, the substance, came, the Jews persecuted Christ, his apostles, and disciples.
And when the Jews had not power enough of themselves to
persecute answerably to their wills,
they got the heathen Gentiles to help them against Christ,
and against his apostles and disciples, who were in the Spirit and power of Christ.`"

[.signed-section-signature]
G+++.+++ F.

--

After I had made some stay in London,
and had cleared myself of those services that at that time lay upon me there,
I went into the country, having with me Alexander Parker and John Stubbs.
We travelled through the country, visiting Friends`' meetings, till we came to Bristol.
There we understood the officers were likely to come and break up the meeting;
yet on First-day we went to the meeting at Broadmead,
and Alexander Parker standing up first,
while he was speaking the officers came and took him away.
After he was gone,`' I stood up,
and declared the everlasting truth of the Lord God in his eternal power,
which came over all; the meeting was quiet the rest of the time, and broke up peaceably.
I tarried till the First-day following, visiting Friends, and being visited by them.
On First-day morning several Friends came to Edward
Pyot`'s house (where I lay the night before),
and used great endeavours to persuade me not to go to the meeting that day,
for the magistrates, they said, had threatened to take me,
and had raised the trained bands.
I wished them to go to the meeting, not telling them what I intended to do;
but I told Edward Pyot I intended to go,
and he sent his son to show me the way from his house by the fields.
As I went I met divers Friends who were coming to me to prevent my going,
and did what they could to stop me.
"`What!`" said one, "`wilt thou go into the mouth of the beast?`"
"`Wilt thou go into the mouth of the dragon?`" said another.
I put them by and went on.
When I came to the meeting, Margaret Thomas was speaking; and when she had done,
I stood up.
I saw a concern and fear upon Friends for me; but the power of the Lord,
in which I declared, soon struck the fear out of them; life sprang,
and a glorious heavenly meeting we had.
After I had cleared myself of what was upon me from the Lord to the meeting,
I was moved to pray; and after that to stand up again, and tell Friends,
"`how they might see there was a God in Israel that could deliver.`"
A very large meeting this was, and very hot; but truth was over all,
the life was exalted, which carried through all, and the meeting broke up in peace.
The officers and soldiers had been breaking up another meeting,
which had taken up their time, so that our meeting was ended before they came.
But I understood afterwards they were in a great rage, because they had missed me;
for they were heard to say one to another before,
"`I`'ll warrant we shall have him;`" but the Lord prevented them.
I went from the meeting to Joan Hily`'s, where many Friends came to see me,
rejoicing and blessing God for our deliverance.
In the evening I had a fine fresh meeting among
Friends at a Friend`'s house over the water,
where we were much refreshed in the Lord.
After this I stayed most part of that week in Bristol,
and at Edward Pyot`'s. Edward was brought so low and weak with an ague,
that when I first came, he was looked upon as a dying man;
but it pleased the Lord to raise him up again, so that before I went away,
his ague left him, and he was finely well.

Having been two First-days together at the meeting at Broadmead,
and feeling my spirit clear of Bristol,
I went next First-day to a meeting in the country not far distant.
And after the meeting, some Friends from Bristol told me,
that the soldiers that day had beset the meeting-house round at Bristol,
and then went up, saying, "`they would be sure to have me now;`" but when they came,
and found me not there, they were in a great rage,
and kept the Friends in the meeting-house most part of the day,
before they would let them go home; and queried of them, which way I was gone,
and how they might send after me; for the mayor,`" they said,
"`would fain have spoken with me.`"
I had a vision of a great mastiff dog, that would have bitten me,
but I put one hand above his jaws, and the other hand below, and tore his jaws in pieces.
So the Lord by his power tore their power to pieces, and made way for me to escape them.
Then I passed through the country, visiting Friends in Wiltshire and Berkshire,
till I came to London, having great meetings amongst Friends as I went.
The Lord`'s power was over all,
and a blessed time it was for the spreading of his glorious truth.
It was indeed his immediate hand and power that
preserved me out of their hands at Bristol,
and over the heads of all our persecutors; and the Lord alone is worthy of all the glory,
who did uphold and preserve for his name and truth`'s sake.

At London I did not stay long, being drawn in spirit to visit Friends northward,
as far as Leicestershire, John Stubbs being with me.
So we travelled, having meetings amongst Friends as we went; at Skegby we had a great one.
Thence passing on, we came to a place called Barnet-Hills, where lived Captain Brown,
a Baptist, whose wife was convinced of truth.
This Captain Brown, after the act for breaking up meetings came forth,
being afraid lest his wife should go to meetings, and be cast into prison,
left his house at Barrow, and took one`' on these hills, saying,
"`his wife should not go to prison.`"
And this being a free place, many, both priests and others, got thither as well as he.
But he who would neither stand to truth himself, nor suffer his wife,
was in this place where he thought to be safe, found out by the Lord,
whose hand fell heavy upon him for his unfaithfulness; so that he was sorely plagued,
and grievously judged in himself for flying,
and drawing his wife into that private place.
We went to see his wife, and being come into the house, I asked him, "`how he did?`"
"`How do I?`" said he, "`the plagues and vengeance of God are upon me,
a runagate, a Cain as I am.
God may look for a witness for me, and such as me;
for if all were not more faithful than I, God would have no witness left in the earth.`"
In this condition he lived on bread and water, and thought it was too good for him.
At length he returned again with his wife to his own house at Barrow,
where he afterwards came to be convinced of God`'s eternal truth, and died in it.
A little before his death he said,
"`though he had not borne a testimony for truth in his life,
he would bear a testimony in his death,
and would be buried in his orchard;`" and he was so.
He was an example to all the flying Baptists in the time of persecution,
who could not bear persecution themselves, yet persecuted us when they had power.

From Barnet-Hills we came to Swannington in Leicestershire,
where William Smith and some other Friends came to me; but they went away towards night,
leaving me at a Friend`'s house in Swannington.
At night, as I was sitting in the hall, speaking to a widow woman and her daughter,
there came one called Lord Beaumont with a company of soldiers, who,
slapping their swords on the door,
rushed into the house with swords and pistols in their hands, crying,
"`Put out the candles, and make fast the doors.`"
Then they seized upon the Friends in the house, and asked,
"`if there were no more about the house?`"
The Friends told them, there was one man more in the hall.
There being some Friends out of Derbyshire, one of them was named Thomas Fauks;
and this Lord Beaumont, after he had asked all their names,
bid his man set down that man`'s name Thomas Fox; but the Friend said,
his name was not Fox, but Fauks.
In the meantime some of the soldiers came, and brought me out of the hall to him.
He asked me my name; I told him, my name was George Fox,
and that I was well known by that name.
"`Ay,`" said he, "`you are known all the world over.`"
I said, "`I was known for no hurt, but for good.`"
Then he put his hands into my pockets to search them, and pulled out my comb-case,
and afterwards commanded one of his officers to search further for letters,
as he pretended.
I told him, I was no letter-carrier, and asked him,
Why he came amongst a peaceable people with swords and pistols, without a constable,
contrary to the king`'s proclamation, and to the late act?
For he could not say, there was a meeting,
I being only talking with a poor widow woman and her daughter.
By reasoning thus with him, he came somewhat down; yet sending for the constables,
he gave them charge of his, and to bring us before him next morning.
Accordingly the constables set a watch of the town`'s-people upon us that night,
and had us next morning to his house, about a mile from Swannington.
When we came before him, he told us "`we met contrary to the act.`"
I desired him to show us the act.
"`Why,`" says he, "`you have it in your pocket.`"
I told him, he did not find us in a meeting.
Then he asked us, "`whether we would take the oaths of allegiance and supremacy?`"
I told him, I never took any oath in my life, nor engagement, nor covenant.
Yet still he would force the oath upon us.
I desired him to show us the oath,
that we might see whether we were the persons it was to be tendered to,
and whether it was not for the discovery of Popish recusants.
At length he brought a little book; but we called for the statute-book.
He would not show us that, but caused a mittimus to be made, which mentioned,
"`that we were to have had a meeting.`"
With this he delivered us to the constables to convey us to Leicester jail.
But when they had brought us back to Swannington, being harvest time,
it was hard to get anybody to go with us;
for the people were loath to go with their neighbours to prison,
especially in such a busy time.
They would have given us our mittimus, to carry it ourselves to the jail;
for it had been usual for constables to give Friends
their own mittimuses (for they durst trust Friends),
and they have gone themselves with them to the jailer.
But we told them, though our Friends had sometimes done so,
yet we would not take this mittimus, but some of them should go with us to the jail.
At last they hired a poor labouring man to go with us, who was loath to go, though hired.
So we rode to Leicester, being five in number;
some carried their Bibles open in their hands, declaring the truth to the people,
as we rode, in the fields and through the towns, and telling them,
"`we were prisoners of the Lord Jesus Christ,
going to suffer bonds for his name and truth`'s sake.`"
One woman Friend carried her wheel on her lap to spin on in prison;
and the people were mightily affected.
At Leicester we went to an inn.
The master of the house seemed troubled that we should go to the prison;
and being himself in commission, he sent for lawyers in the town to advise with,
and would have taken up the mittimus, and kept us in his own house,
and not have let us go into the jail.
But I told Friends, it would be a great charge to lie at an inn;
and many Friends and people would be coming to visit us,
and it might be hard for him to bear our having meetings in his house; besides,
we had many Friends in the prison already, and we had rather be with them.
So we let the man know, that we were sensible of his kindness, and to prison we went;
the poor man that brought us thither, delivering both the mittimus and us to the jailer.
This jailer had been a very wicked, cruel man.
Six or seven Friends being in prison before we came,
he had taken some occasion to quarrel with them,
and thrust them into the dungeon amongst the felons,
where there was hardly room for them to lie down.
We stayed all that day in the prison-yard,
and desired the jailer to let us have some straw.
He surlily answered, "`you do not look like men that would lie on straw.`"
After a while William Smith, a Friend, came to me, and he being acquainted in the house,
I asked him, "`what rooms there were in it,
and what rooms Friends had usually been put into,
before they were put into the dungeon?`"
I asked him also, Whether the jailer or his wife was master?
He said, The wife was master; and that though she was lame, and sat mostly in her chair,
being only able to go on cratches,
yet she would beat her husband when he came within her reach,
if he did not do as she would have him.
I considered, probably many Friends might come to visit us, and that,
if we had a room to ourselves, it would be better for them to speak to me,
and me to them, as there should be occasion.
Wherefore I desired William Smith to go speak with the woman, and acquaint her,
if she would let us have a room, suffer our Friends to come out of the dungeon,
and leave it to us, to give her what we would, it might be better for her.
He went, and after some reasoning with her, she consented; and we were had into a room.
Then we were told,
that the jailer would not suffer us to have any drink out of the town into the prison,
but that what beer we drank, we must take of him.
I told them, I would remedy that,
for we would get a pail of water and a little wormwood once a day,
and that might serve us; so we should have none of his beer,
and the water he could not deny us.

Before we came, when the few Friends that were prisoners there,
met together on First-days, if any of them was moved to pray to the Lord,
the jailer would come up with his quarter-staff in his hand,
and his mastiff dog at his heels, and pluck them down by the hair of the head,
and strike them with his staff; but when he struck Friends, the mastiff dog,
instead of falling upon them, would take the staff out of his hand.
When the First-day came, I spoke to one of my fellow-prisoners,
to carry a stool and set it in the yard, and give notice to the debtors and felons,
that there would be a meeting in the yard,
and they that would hear the word of the Lord declared might come thither.
So the debtors and prisoners gathered in the yard, and we went down,
and had a very precious meeting, the jailer not meddling.
Thus every First-day we had a meeting as long as we stayed in prison;
and several came in out of the town and country.
Many were convinced, and some received the Lord`'s truth there,
who have stood faithful witnesses for it ever since.

When the sessions came, we were brought before the justices, with many more Friends,
sent to prison whilst we were there, to the number of about twenty.
Being brought into the court,
the jailer put us into the place where the thieves were put,
and then some of the justices began to tender
the oaths of allegiance and supremacy to us.
I told them, I never took any oath in my life, and they knew we could not swear,
because Christ and his apostle forbade it; therefore they put it but as a snare to us.
We told them, if they could prove, that after Christ and the apostle had forbid swearing,
they did ever command Christians to swear, then we would take these oaths;
otherwise we were resolved to obey Christ`'s command and the apostle`'s exhortation.
They said, "`we must take the oath, that we might manifest our allegiance to the king.`"
I told them, I had been formerly sent up a prisoner by Colonel Hacker,
from that town to London,
under pretence that I held meetings to plot to bring in King Charles.
I also desired them to read our mittimus,
which set forth the cause of our commitment to be,
that "`we`" were to have a meeting;`" and I said,
Lord Beaumont could not by that act send us to jail,
unless we had been taken at a meeting, and found to be such persons as the act speaks of;
therefore we desired they would read the mittimus,
and see how wrongfully we were imprisoned.
They would not take notice of the mittimus, but called a jury,
and indicted us for refusing to take the oaths of allegiance and supremacy.
When the jury was sworn and instructed, as they were going out,
one that had been an alderman of the city, spoke to them, and bid them,
"`have a good conscience;`" and one of the jury, being a peevish man, told the justices,
there was one affronted the jury; whereupon they called him up,
and tendered him the oath also, and he took it.

While we were standing where the thieves used to stand,
a cut-purse had his hand in several Friends`' pockets.
Friends declared it to the justices, and showed them the man.
They called him up before them, and upon examination he could not deny it;
yet they set him at liberty.^
footnote:[Cases similar to the above are not rare in the early history of the Society;
even thieves being allowed to escape, whilst the party robbed,
being unwilling to swear to the known fact, have been made to suffer.
In 1660, the following occurrence took place at Reading assizes:--Henry Hodges,
a poor smith, lost three cows,
which were found in the possession of the thief who stole them.
He was brought to trial, and Hodges appeared to claim his cows.
The judge told him they must be proved on oath before he could have them again.
He replied that he could not swear for conscience sake.
The judge said, if any of his neighbours would swear they were his,
they should be returned to him; upon which one of his neighbours took his oath,
and the judge promised that they should be returned.
Thus far the proceedings appeared just and equal,
but many thought the judge too rigorous, when,
having observed the sincerity and tenderness of the poor man`'s conscience,
who could not swear in a case of his own property,
he caused the oath of allegiance to be tendered him in court; and,
for his refusing to take it, sent him to jail.--(Besse)]

It was not long before the jury returned, and brought us in guilty; and then,
after some words, the justices whispered together,
and bid the jailer take us down to prison again;
but the Lord`'s power was over them and his everlasting truth,
which we declared boldly amongst them.
There being a great concourse of people, most of them followed us;
so that the cryer and bailiffs were fain to call the people back again to the court.
We declared the truth as we went down the streets all along, till we came to the jail,
the streets being full of people.
When we were in our chamber again, after some time the jailer came to us,
and desired all to go forth that were not prisoners.
When they were gone, he said, "`Gentlemen, it is the court`'s pleasure,
that ye should all be set at liberty, except those that are in for tithes; and you know,
there are fees due to me; but I shall leave it to you to give me what you will.`"

Thus were we all set at liberty suddenly, and passed every one into his service.
Leonard Fell stayed with me, and we two went again to Swannington.
I had a letter from Lord Hastings, who hearing of my imprisonment,
had written from London to the justices of the sessions to set me at liberty.
I had not delivered this letter to the justices,
but whether they had any knowledge of his mind from any other hand,
which made them discharge us so suddenly, I know not.
But this letter I carried to Lord Beaumont who had sent us to prison;
and when he had broken it open, and read it, he seemed much troubled;
but at last came a little lower; yet threatened us,
if we had any more meetings at Swannington,
he would break them up and send us to prison again.
But notwithstanding his threats, we went to Swannington,
and had a meeting with Friends there, and he neither came, nor sent to break it up.

From Swannington we came to Twy-cross, where that great man formerly mentioned,
whom the Lord God raised up from his sickness in the year 1649 (and
whose serving-man came at me with a drawn sword to do me a mischief),
and his wife came to see me.
Thence we travelled through Warwickshire, where we had brave meetings;
and into Northamptonshire and Bedfordshire, visiting Friends till we came to London.

I stayed not long in London, but went into Essex, and so into Norfolk,
having great meetings.
At Norwich, when I came to Captain Lawrence`'s,^
footnote:[This Captain Lawrence, who has been mentioned before,
was a man of some note in the days of the Commonwealth.
After he joined Friends, he became a faithful sufferer for Christ.
In 1660, with his brother Joseph Lawrence, and George Whitehead,
he was imprisoned in Norwich castle, in a small narrow cell called the Vice,
where they endured much hardship.
In speaking of this imprisonment, George Whitehead says, "`I remember one morning,
Joseph Lawrence, after his pleasant manner, said to his brother John, '`O,
Captain Lawrence, I have seen the day that thou wouldst not have lain there!`'`"]
there was a great threatening of disturbance; but the meeting was quiet.
Passing thence to Sutton, and so into Cambridgeshire,
I heard of Edward Burrough`'s decease.
And being sensible bow great a grief and
exercise it would be to Friends to part with him,
I wrote the following lines for the staying and settling of their minds:--

[.embedded-content-document.epistle]
--

[.salutation]
"`Friends,

"`Be still and quiet in your own conditions,
and settled in the Seed of God that doth not change,
that in that ye may feel dear E. B. among you in the Seed,
in which and by which he begat you to God, with whom he is;
and that in the Seed ye may all see and feel him,
in which is the unity with him in the life;
and so enjoy him in the life that doth not change, which is invisible.`"

[.signed-section-signature]
G+++.+++ F.

--

Thence I passed to Little Port and the Isle 0f Fly; where the ex-mayor, with his wife,
and the wife of the then mayor of Cambridge, came to the meeting.
Travelling into Lincolnshire and Huntingdonshire, I came to Thomas Parnell`'s,
where the mayor of Huntingdon came to see me, and was very loving.
Thence I came into the Fen-country, where we had large and quiet meetings.
While I was in that country, there came so great a flood that it was dangerous to go out,
yet we did get out, and went to Lynn, where we had a blessed meeting.
Next morning I went to visit some prisoners there; and then back to the inn,
and took horse.
As I was riding out of the yard, the officers came to search the inn for me.
I knew nothing of it then,
only I felt a great burden come upon me as I rode out of the town,
till without the gates.
When some Friends that came after, overtook me, they told me,
that the officers had been searching for me in the inn,
as soon as I was gone out of the yard.
So by the good hand of the Lord, I escaped their cruel hands.
After this we passed through the countries, visiting Friends in their meetings.
The Lord`'s power carried us over persecuting spirits, and through many dangers;
his truth spread and grew, and Friends were established therein;
praises and glory to his name for ever.
