== Chapter I.

[.chapter-synopsis]
* 1663-1666.
* George Fox visits London
* taken up at Tenterden and examined by the magistrates, but liberated
* precious meetings in Wales
* at Derwentwater meets with an old woman whose husband was aged 122 years
* apprehended and taken before the magistrates at Holker Hall, but liberated on his parole to appear at the sessions
* appears accordingly, and is committed to Lancaster jail
* many poor Friends imprisoned there at the same time, whose families become chargeable in consequence
* one of them (Oliver Atherton) dies in jail, where he was immured by the Countess of Derby for tithes
* George Fox has the oath tendered him at the assizes, and is re-committed
* Margaret Fell is also imprisoned there
* the prisoners in Lancaster jail to Justice Fleming
* a brief warning to the same by George Fox
* George Fox disputes with Major Wiggan (who was also a prisoner), and confutes him
* writes to the judges against giving nicknames
* writes a warning to all high professors
* also a warning against the spirit of John Perrot
* at the assizes he points out many fatal errors in his indictment, and it is quashed in consequence, but the judge ensnares him with the oath, and he is again remanded to prison
* suffers much from the badness of the prison
* at the next assizes he again points out fatal errors in his indictment, and is immediately hurried away to jail, and sentence is passed on him in his absence
* a testimony against tithes
* he is removed to Scarbro`' Castle
* has several conferences and disputes with divers persons there
* writes to the king respecting his imprisonment, and is set at liberty
* copy of his discharge and passport
* the day after George Fox`'s liberation the great fire broke out in London, a vision of which he had in Lancaster Castle
* the hand of the Lord turned against persecutors.

Having passed through Norfolk, Suffolk, Essex, and Hertfordshire,
we came to London again; where I stayed a while, visiting Friends in their meetings,
which were very large, and the Lord`'s power was over all.
After some time I left the city again, and travelled into Kent,
having Thomas Briggs with me.
We went to Ashford, where we had a quiet, and a very blessed meeting;
and on First-day we had a very good and peaceable one at Cranbrook.
Then we went to Tenterden, and had one there,
to which many Friends came from several parts, and many other people came in,
and were reached by the truth.
When the meeting was over, I walked with Thomas Briggs into a field,
while our horses were got ready; and turning my head, I espied a captain coming,
and a great company of soldiers with lighted matches and muskets.
Some of them came to us, and said, "`we must go to their captain.`"
When they had brought us before him, he asked,
"`where is George Fox? which is he?`"
I said, "`I am the man.`"
Then he came to me and was somewhat struck, and said,
"`I will secure you among the soldiers.`"
So he called for them to take me.
He took Thomas Briggs, and the man of the house, with many more;
but the power of the Lord was mightily over them all.
Then he came to me again, and said,
"`I must go along with him to the town;`" and he carried himself pretty civilly,
bidding the soldiers bring the rest after.
As we walked, I asked him,
"`why they did thus for I had not seen so much to do a great
while,`" and I bid him be civil to his peaceable neighbours.
When we were come to the town, they had us to an inn that was the jailer`'s house;
and after a while the mayor of the town, and this captain, and the lieutenant,
who were justices, came together and examined me,
"`why I came thither to make a disturbance?`"
I told them, I did not come to make a disturbance, neither had I made any since I came.
They said, "`there was a law against the Quakers`' meetings, made only against them.`"
I told them, I knew no such law.
Then they brought forth the act that was made against Quakers and others; I told them,
that was against such as were a terror to the king`'s subjects, and were enemies,
and held principles dangerous to the government, and therefore that was not against us,
for we held truth; and our principles were not dangerous to the government,
and our meetings were peaceable, as they knew,
who knew their neighbours were a peaceable people.
They told me, "`I was an enemy to the king.`"
I answered, We loved all people and were enemies to none; that I, for my own part,
had been cast into Derby dungeon, about the time of Worcester fight,
because I would not take up arms against him,
and that I was afterwards brought by Colonel Hacker to London,
as a plotter to bring in King Charles,
and was kept prisoner there till set at liberty by Oliver.
They asked me, "`whether I was imprisoned in the time of the insurrection?`"
I said, yes; I had been imprisoned then, and since that also,
and had been set at liberty by the king`'s own command.
I opened the act to them, and showed them the king`'s late declaration;
gave them the examples of other justices,
and told them also what the House of Lords had said of it.
I spoke also to them concerning their own conditions,
exhorting them to live in the fear of God,
to be tender towards their neighbours that feared Him, and to mind God`'s wisdom,
by which all things were made and created, that they might come to receive it,
be ordered by it, and by it order all things to God`'s glory.
They demanded bond of us for our appearance at the sessions; but we,
pleading our innocency, refused to give bond.
Then they would have us promise to come no more there; but we kept clear of that also.
When they saw they could not bring us to their terms, they told us,
"`we should see they were civil to us,
for it was the mayor`'s pleasure we should all be set at liberty.`"
I told them their civility was noble, and so we parted.

Then leaving Tenterden we went to Newick in Sussex, where we visited some Friends.
Thence we passed through the country, visiting Friends, and having great meetings;
all quiet and free from disturbance, except by some jangling Baptists,
till we came into Hampshire.
After a good meeting at Southampton, we went to Pulner, in the parish of Ringwood,
where was a monthly meeting next day, to which many Friends came from Southampton, Poole,
and other places; and the weather being very hot,
some of them came pretty early in the morning.
I took a friend and walked out with him into the orchard,
inquiring of him how the affairs of truth stood amongst them;
(for many of them had been convinced by me,
before I was a prisoner in Cornwall.) While we were conversing,
a young man came and told us the trained bands were raising,
and he heard they would come and break up the meeting.
It was not yet meeting-time for about three hours,
and there being other Friends walking in the orchard,
the Friend that I was discoursing with before,
desired me to walk into a corn field adjoining it, which we did.
After a while the young man that spoke of the trained bands left us,
and when he was gone some distance, he stood and waved his hat.
Whereupon I spoke to the other young man that was with me, to go and see what he meant.
He went, but did not return; for the soldiers were come into the orchard.
And as I kept walking I could see the soldiers, and some of them, as I heard afterwards,
saw me, but had no mind to meddle.
Coming so long before the meeting-time, they did not tarry;
but took what Friends they found at the house, and some whom they met in the lane coming,
and led them away.
After they were gone, it drew towards eleven, Friends began to come in apace,
and a large and glorious meeting we had;
for the everlasting Seed of God was set over all,
and the people were settled in the new covenant of life, upon the foundation,
Christ Jesus.
Towards the latter part of the meeting, there came a man in gay apparel,
and looked in while I was declaring, and went away again presently.
This man came with an evil intent; for he went forthwith to Ringwood,
and told the magistrates "`they had taken two or three men at Pulner,
and had left George Fox there preaching to two or three hundred people.`"
Upon this the magistrates sent the officers and soldiers again;
but the meeting being nearly ended when the man looked in,
and he having about a mile and a half to go, with his information, to fetch the soldiers,
and they as far to come, after they had received their orders,
before they came our meeting was over; ending about three o`'clock peaceably and orderly.
After the meeting I spoke to the Friends of the house where it
was held (the hostess lying then dead in the house),
and then some Friends conducted me to another Friend`'s at a little distance; where,
after we had refreshed ourselves, I took horse,
having about twenty miles to ride that afternoon to one Frye`'s house in Wiltshire,
where a meeting was appointed for the next day.

After we were gone, the officers and soldiers came in a great heat,
and when they found they were too late, and had missed their prey,
they were much enraged; and the officers were offended with the soldiers,
because they had not seized my horse in the stable the first time they came.
But the Lord, by his good providence, delivered me,
and prevented their mischievous design.
For the officers were envious men, and had an evil mind against Friends;
but the Lord brought his judgments upon them,
so that it was taken notice of by their neighbours.
For "`whereas before they were wealthy men, after this their estates wasted away;
and John Line, the constable,
who was not only very forward in putting on the soldiers to take Friends,
but also carried those that were taken to prison,
and took a false oath against him at the assize,
upon which they were fined and continued prisoners, was a sad spectacle to behold.
For his flesh rotting away while he lived, he died in a very miserable condition,
wishing he had never meddled with the Quakers,
and confessing that he had never prospered since he had had a hand in persecuting them;
and that he thought the hand of the Lord was against him for it.`"

At Frye`'s, in Wiltshire, we had a very blessed meeting, and quiet,
though the officers had purposed to break it up,
and were on their way in order thereunto.
But before they got to it, word was brought them,
that there was a house just broken up by thieves,
and they were required to go back again with speed, to search after and pursue them;
by which means our meeting escaped disturbance, and we were preserved out of their hands.

We passed through Wiltshire into Dorsetshire, having large and good meetings.
The Lord`'s everlasting power was with us, and carried us over all;
in which we sounded forth his saving truth and word of life, which many gladly received.
Thus we visited Friends, till we came to Topsham in Devonshire,
travelling some weeks eight or nine score miles a week, and had meetings every day.
At Topsham we met with Margaret Fell and two of her daughters, Sarah and Mary,
and with Leonard Fell and Thomas Salthouse.^
footnote:[Thomas Salthouse of Lancashire,
but who afterwards resided in the south of England, was born about 1630,
and convinced when George Fox first came to Swarthmore.
He became an eminent minister of the gospel, for which he suffered much.
In 1655 he, and Miles Halhead,
being pressed in spirit to visit the Friends imprisoned at Plymouth,
they were taken up on suspicion of having a hand in an
insurrection which broke out a little before;
and though the high sheriff confessed he did not believe them concerned in it,
he caused them to be kept close prisoners at Exeter fourteen days,
and then sent them from officer to officer towards home.
In going towards Bridgewater, the officer who conducted them fell down,
and lay grovelling on the ground in the sight of many people,
and was able to go no further.
So they returned to the justice to tell him what had befallen the officer,
and to know what further he would do with them.
But he declined to interfere with them again; set them at liberty,
and desired the Lord to be with them.
{footnote-paragraph-split}
For further particulars of Thomas Salthouse,
the reader is referred to Whiting`'s _Memoirs,_
p. 452-460. Whiting concludes his account by saying,
"`He was a pleasant man in conversation,
which rendered him acceptable to many others as well as Friends, had a large capacity,
and an excellent gift in the ministry.
He wrote some notable books, and excellent epistles to Friends,
though never collected as they deserve.
He died, at his own house in Cornwall in 1690, about sixty years of age,
in peace with the Lord;
and is no doubt at rest with him from all his labours and sufferings,
and his works follow him.`"]
Thence we passed to Totness, where we visited some Friends, then to Kingsbridge,
and to Henry Pollexfen`'s, who had been an ancient justice of peace.
There we had a large meeting.
This old justice accompanied us to Plymouth, and into Cornwall to Justice Porter`'s,
and thence to Thomas Mount`'s, where we had another large meeting.
After which we went to Humphrey Lower`'s, where also we had a large meeting,
and thence to Loveday Hambley`'s, where we had a general meeting for the whole country;
and all was quiet.

A little before this, Joseph Hellen and G. Bewley, had been at Loo to visit Blanch Pope,
a Ranting woman, under pretence to convince and convert her; but before they left her,
she had so darkened them with her principles, that they seemed to be like her disciples,
especially Joseph Hellen; for she had asked them, "`who made the devil; did not God?`"
This idle question so puzzled them, that they could not answer her.
They afterwards asked me that question.
I told them, no; for all that God made was good and was blessed; so was not the devil.
He was called a serpent before he was called a devil and an adversary,
and then he had the title of devil given to him.
Afterwards he was called a dragon, because he was a destroyer.
The devil abode not in the truth, and by departing from the truth, he became a devil.
So the Jews, when they went out of the truth, were said to be of the devil,
and were called serpents.
Now there is no promise of God to the devil, that ever he shall return to truth again;
but to man and woman, who have been deceived by him, the promise of God is,
that "`the Seed of the woman shall bruise the serpent`'s head,`"--
shall break his power and strength to pieces.
Now when these things were opened more at large to the satisfaction of Friends,
those two who had let up the spirit of that ranting woman, were judged by the truth;
and one of them, Joseph Hellen, ran quite out, and was disowned by Friends;
but George Bewley was recovered, and afterwards became serviceable.

We passed from Loveday Hambley`'s to Francis Hodges`'s, near Falmouth and Penryn,
where we had a large meeting.
Thence we went to Helstoke that night, where some Friends came to visit us;
and next day passed to Thomas Teage`'s, where we had another large meeting,
at which many were convinced.
I was led to open "`the state of the church in the primitive times,
the state of the church in the wilderness,
and the state of the false church that was got up since,
and to show that now the everlasting gospel was
preached again over the head of the whore,
beast, false prophets, and antichrists, which had got up since the apostles`' days;
and now the everlasting gospel was received and receiving,
which brought life and immortality to light,
that they might see over the devil that had darkened them.`"
The people received the gospel and the word of life gladly,
and a glorious blessed meeting we had for the exalting
of the Lord`'s everlasting truth and his name.
After the meeting was over I walked out,
and as I was coming in again I heard a noise in the court, and coming nearer,
I found the man of the house speaking to the tinners and others, and telling them,
"`it was the everlasting truth that had been declared there that day;`"
and the people generally confessed to it.

From thence we passed to the Land`'s-end, to John Ellis`'s, where we had a precious meeting.
Here was a fisherman, one Nicholas Jose, that was convinced.
He spoke in meetings, and declared the truth amongst the people,
and the Lord`'s power was over all.
I was glad that the Lord had raised up his standard in those dark parts of the nation,
where there is since a fine meeting of honest-hearted Friends;
many are come to sit under Christ`'s teaching;
and a great people the Lord will have in that country.

Thence we returned to Redruth, and next day to Truro, where we had a meeting.
Next morning, some of the chief of the town desired to speak with me,
amongst whom was Colonel Rouse.
I went and had much discourse with them concerning the things of God.
In their reasoning, they said,
"`the gospel was the four books of Matthew, Mark, Luke, and John;`"
and they called it natural.
I told them, "`the gospel was the power of God, which was preached before Matthew, Mark,
Luke, and John, or any of them were printed or written;
and it was preached to every creature (of which a great
part might never see or hear of those four books),
so that every creature was to obey the power of God; for Christ, the spiritual man,
would judge the world according to the gospel, that is, according to his invisible power.
When they heard this, they could not gainsay; for the truth came over them.
I directed them to their Teacher, the Grace of God,
and showed them the sufficiency of it, which would teach them how to live,
and what to deny; and being obeyed, would bring them salvation.
So to that grace I recommended them, and left them.

Then we returned through the country, visiting Friends,
and had meetings at Humphrey Lower`'s again,
and at Thomas Mount`'s. Afterwards at George Hawkins`'s, at Stoke, we had a large meeting,
to which Friends came from Launceston and several other places.
A living, precious meeting it was,
in which the Lord`'s presence and power was richly manifested amongst us;
and I left Friends there under the Lord Jesus Christ`'s teaching.

In Cornwall I was informed there was one Colonel Robinson, a very wicked man, who,
after the king came in, was made a justice of peace,
and became a cruel persecutor of Friends, of whom he sent many to prison.
Hearing that they had some little liberty, through the favour of the jailer,
to come home sometimes to visit their wives and children,
he made great complaint thereof to the judge at the assize against the jailer;
whereupon the jailer was fined a hundred marks,
and Friends were kept very strictly up for a while.
After he was come home from the assize, he sent to a neighbouring justice,
to desire him to go a fanatic-hunting with him.
On the day that he intended, and was prepared to go,
he sent his man about with his horses,
and walked himself on foot from his dwelling-house to a tenement,
where his cows and dairy were kept, and where his servants were then milking.
When he came there he asked for his bull.
The maidservants said, they had shut him into the field,
because he was unruly amongst the kine, and hindered their milking.
Then he went into the field to the bull,
and having formerly accustomed himself to play with him,
he began to fence at him with his staff.
But the bull snuffed at him, and passed a little back; then turning upon him again,
ran fiercely at him and struck his horn into his thigh, and heaving him upon his horn,
threw him over his back, and tore up his thigh to his belly.
When he came to the ground again he gored him with his horns,
run them into the ground in his rage and violence, roared,
and licked up his master`'s blood.
The maid-servant, hearing her master cry out, ran into the field,
and took the bull by the horns to pull him off from her master.
The bull, without hurting her, put her gently by with his horns,
but still fell to goring him and licking up his blood.
Then she ran and got some men, that were at work not far off,
to come and rescue her master; but they could not at all beat off the bull,
till they brought mastiff dogs to set on him; and then he fled in great rage and fury.
Upon hearing of it his sister came, and said to him, "`Alack! brother,
what a heavy judgment is this that has befallen you!`"
He answered, "`Ah! sister, it is a heavy judgment indeed.
Pray let the bull be killed, and the flesh given to the poor,`" said he.
They carried him home, but he died soon after.
The bull was grown so fierce that they were forced to shoot him;
for no man durst come near to kill him.
Thus does the Lord sometimes make some examples of his
just judgment upon the persecutors of his people,
that others may fear, and learn to beware.

After I had cleared myself of Cornwall,
and Thomas Lower had brought us over Horsebridge into Devonshire again,
we took our leave of him.
Thomas Briggs, Robert Widders, and I, came to Tiverton; and it being their fair,
and many Friends there, we had a meeting amongst them.
The magistrates gathered in the street, but the Lord`'s power stopped them.
I saw them in the street over against the door,
but they had not power to come in to meddle with us,
though they had will enough to do it.

After the meeting we passed to Collumpton and Wellington,
for we had appointed a meeting five miles off,
where we had a large one at a butcher`'s house, and a blessed meeting it was.
The people were directed to their Teacher, the Grace of God,
which would bring them salvation, and many were settled under its teaching.
The Lord`'s presence was amongst us, and we were refreshed in him,
in whom we laboured and travailed; and the meeting was quiet.
There had been very great persecution in that country and town a little before,
insomuch that some Friends questioned the peaceableness of our meeting;
but the Lord`'s power chained all, and his glory shone over all.
Friends told us how they had broken up their meetings by warrants from the justices,
and how by their warrants they were required to carry Friends before the justices;
and Friends bid them "`carry them then.`"
The officers told Friends, "`they must go:`" but Friends said, nay;
that was not according to their warrants, which required them to carry them.
Then they were forced to hire carts, and waggons, and horses,
and to lift Friends into their wagons and carts, to carry them before a justice.
When they came to a justice`'s house, sometimes he happened to be from home,
and if he were a moderate man, he would get out of the way,
and then they were obliged to carry them before another,
so that they were many days carting and carrying Friends up and down from place to place.
And when afterwards the officers came to lay their charges for this upon the town,
the town`'s-people would not pay it, but made them bear it themselves;
which broke the neck of their persecution there for that time.
The like was done in several other places,
till the officers had shamed and tired themselves, and then they were glad to give over.

At one place they warned Friends to come to the steeple-house.
Friends met to consider of it, and finding freedom to go to the steeple-house,
they met together there.
Accordingly when they came thither,
they sat down to wait upon the Lord in his power and Spirit,
and minded the Lord Jesus Christ, their Teacher and Saviour;
but did not mind the priest When the officers saw that,
they came to them to put them out of the steeple-house again; but the Friends told them,
it was not time for them to break up their meeting yet.
A while after, when the priest had done, they came to the Friends again,
and would have had them go home to dinner; but the Friends told them,
they did not choose to go to dinner, they were feeding upon the bread of life.
So there they sat, waiting upon the Lord, and enjoying his power and presence,
till they found freedom in themselves to depart.
Thus the priest`'s people were offended,
because they could not get them to the steeple-house: and when there, they were offended,
because they could not get them out again.

From the meeting near Collumpton we went to Taunton, where we had a large meeting.
The next day we came to a general meeting in Somersetshire, which was very large;
and the Lord`'s everlasting word of life and truth was largely declared.
The people were refreshed thereby, and settled upon Christ, their Rock and Foundation,
and brought to sit under his teaching; the meeting was peaceable.
But about the second hour of the night there
came a company of men who knocked at the door,
and bid us open it, or they would break it open;
for they wanted a man that they came to search the house for.
I heard the noise, and got up,
and at the window saw a man at the door with his sword by his side.
When they had let him in, he came into the chamber where I was, and looked on me,
and said, "`You are not the man I look for:`" and went his way.

We came thence to Street, and to William Beaton`'s, at Puddimoor,
where we had a very large general meeting,
wherein the Lord`'s everlasting truth was declared, the people refreshed, and all quiet.
Thence we went to John Dandy`'s, where we had another large and very precious meeting;
and then passed on to Bristol, where we had good service for the Lord, and all quiet.
Here we met with Margaret Fell and her daughters again.
After some time we went to Slattenford in Wiltshire,
where was a very large meeting in a great barn.
Good service we had there; for the truth, as it is in Jesus, was published amongst them,
and many were gathered by it into the name of the Lord.

After this I passed into Gloucestershire and Herefordshire, having large meetings in each.
In Hereford I had a meeting in the inn.
When I was gone, the magistrates, hearing there had been a meeting,
came to search the inn for me, and were vexed that they had missed me.
But the Lord so ordered it, that I escaped their hands;
and Friends were established upon Christ, their Foundation, the Rock of Ages.

Then I went into Radnorshire, in Wales, and had several precious meetings there.
The Lord`'s name and standard was set up, and many were gathered to it,
and settled under the teaching of Christ Jesus, their Saviour, who bought them.

After I was clear of Wales, I came to a market-town between England and Wales,
where there was a great fair that day; and several Friends being at the fair,
we went to an inn, and they came to us.
After we had had a fine opportunity with Friends, we parted from them,
and went on our way.
The officers of the town took notice, it seems, of our being there,
and of Friends gathering to us.
They began also to meet together to consult among themselves how to ensnare us,
though it was the fair time;
but before they could do anything we were gone on our journey, and so escaped them.

Thence we came into Shropshire, where we had a large and precious meeting.
After many meetings in those parts we came into Warwickshire, and visited Friends there,
and so into Derbyshire and StaffordShire, visiting Friends`' meetings as we went.
At Whitehaugh we had a large, blessed meeting, and quiet;
after which we rode about twenty miles that night to Captain
Lingard`'s. We heard afterwards that when we were gone,
the officers came to seize us, and were much disturbed that they missed us;
but the Lord disappointed them, and Friends were joyful in the Lord that we escaped them.

At Captain Lingard`'s we had a blessed meeting,
the Lord`'s presence being wonderfully amongst us.
After this we passed through the Peak-Country in Derbyshire,
and went to Synderhill-Green, where we had a large meeting.
Here John Whitehead^
footnote:[John Whitehead was a very eminent minister amongst the early Friends,
valiant for the truth, and a great sufferer for it.
His life and writings have recently been published, to which the reader is referred.
He wrote a very beautiful and encouraging epistle to Friends, dated Aylesbury prison,
12th month, 1660, which is inserted in _Letters etc., of Early Friends,_
382-387. William Penn, in his Preface to _Whitehead`'s Works,_ says,
"`He was among the most eminent for his sound mind and capacity, great zeal and boldness,
and as great humility, patience, and labour in word, doctrine, and charity.`"]
and several other Friends came to me.
Then I passed through the country, visiting Friends,
till I came to the farther end of Holderness, and so passed by Scarbro'`, Whitby,
and Malton, to York, having many meetings in the way;
and the Lord`'s everlasting power was over all.

We went from York to Boroughbridge, where I had a glorious meeting.
Thence we passed into Durham to one Richmond`'s, where there was a general meeting;
and the Lord`'s power was over all,
though people were grown exceedingly rude about this time.
After the meeting we went to Henry Draper`'s, where we stayed all night.
Next morning a Friend came to me, as I was passing away, and told me,
"`if the priests and justices (for many priests were made
justices in that country at that time) could find me,
they would destroy me.`"

Being clear of Durham, I went over Stainmore into Yorkshire, and to Sedbergh,
where having visited Friends, I went into Westmorland, visiting Friends there also.
Thence I passed into Lancashire and came to Swarthmore.
Here I stayed but a little while before I went over the Sands to Arnside,
where I had a general meeting.
After it was ended, there came some men to break it up;
but understanding before they arrived that the meeting was over, they turned back.
I went to Robert Widders`'s, and thence to Underbarrow, where I had a glorious meeting,
and the Lord`'s power was over all.
Thence I passed to Grayrigg, and having visited Friends there, I went to Ann Audland`'s,
where they would have had me to stay their meeting next day;
but I felt a stop in my spirit.
It was upon me to go to John Blakelin`'s in Sedbergh,
and to be next day at the meeting there; which is large, and a precious people there is.
We had a very good meeting next day at Sedbergh;
but the constables went to Ann Audland`'s meeting to look for me.
Thus by the good hand and disposing Providence of the Lord, I escaped their snare.

I went from John Blakelin`'s with Leonard Fell to Strickland-head,
where on First-day we had a very precious meeting on the common.
That night we stayed amongst Friends there, and next day passed into Northumberland.
After the justices had heard of this meeting at Stricklandhead, they made search for me;
but by the good hand of the Lord, I escaped them again,
though there were some very wicked justices.
We went to Hugh Hutchinson`'s house in Northumberland, a Friend in the ministry,
whence we visited Friends thereabouts, and then went to Derwentwater,
where we had a very glorious meeting.
There came an ancient woman to me, and told me her husband remembered his love to me;
she said, I might call him to mind by this token,
that I used to call him "`the Tall White Old Man.`"
She said, he was six score and two years old, and that he would have come to the meeting,
but his horses were all employed upon some urgent occasion.
I heard he lived some years after.

When I had visited Friends in those parts, and they were settled upon Christ,
their Foundation, I passed through Northumberland,
and came to old Thomas Bewley`'s in Cumberland.
Friends came about me, and asked, "`would I come there to go into prison?`"
For there was great persecution in that country at that time;
yet I had a general meeting at Thomas Bewley`'s, which was large and precious,
and the Lord`'s power was over all.

One Musgrave was at that time deputy-governor of Carlisle.
Passing along the country, I came to a man`'s house that had been convinced,
whose name was Fletcher; and he told me, "`if Musgrave knew I was there,
he would be sure to send me to prison, he was such a severe man.`"
But I stayed not there, only calling on the way to see this man;
and then I went to William Pearson`'s, near Wigton, where the meeting was,
which was very large and precious.
Some Friends were then prisoners at Carlisle, whom I visited by a letter,
which Leonard Fell carried.
From William Pearson`'s I visited Friends, till I came to Pardshaw-Crag,
where we had a general meeting, which was large; all was quiet and peaceable,
and the glorious, powerful presence of the everlasting God was with us.

So eager were the magistrates about this time to stir up persecution in those parts,
that some offered five shillings, and some a noble a day,
to any that could apprehend the speakers amongst the Quakers;
but it being now the time of the quarter sessions in that county,
the men who were so hired were gone to the sessions to get their wages,
and so all our meetings were at that time quiet.

From Pardshaw-Crag we went into Westmorland, calling on the way upon Hugh Tickell,^
footnote:[Hugh Tickell was born in Cumberland about the year 1610.
Being convinced by George Fox when he first visited Cumberland in 1633,
he gave up his house for meetings, and entertained the Lord`'s messengers.
He became a faithful and eminent minister,
travelling up and down in the service of the Gospel, suffering much for it,
both in the spoiling of his goods and in imprisonments.
In 1664 he was cast into Carlisle jail, with four other Friends,
by priest Marshall of Crosthwaite, and though he kept him in prison three years,
yet he took tithe of his land.
But afterwards this priest fell down stairs and broke his skull, upon which he died.
Hugh Tickell was again imprisoned in Carlisle jail, when about sixty-eight years old,
by Kichard Lowry, another priest of Crosthwaite, because he could not pay him tithes,
who kept him prisoner about nine months, part of it in a cold winter,
and in a damp nasty place not fit for men to lie in.
This priest Lowry was suddenly stricken, and had the use of one side of his tongue,
and his understanding much taken from him,
and so continued a long time--a remarkable judgment.
{footnote-paragraph-split}
Hugh Tickell patiently bore all his sufferings,
and willingly endured them for the testimony of Jesus and a good conscience.
But in his last imprisonment he contracted a distemper of body, which,
increasing upon him after he came home, he grew weak, but continued in great patience;
and being sensible his end drew nigh, set his house in order, and,
taking leave of friends and neighbours, he sweetly departed in great peace in 1680,
being above seventy years of age.]
near Keswick, and upon Thomas Laythes, where

Friends came to visit us; and we Lad a fine opportunity to be refreshed together.
We went that night to Francis Benson`'s, in Westmorland, near Justice Fleming`'s house.
This Justice Fleming was at that time in a great rage against Friends,
and me in particular; insomuch that in the open sessions at Kendal just before,
he had bid five pounds to any man that should take me, as Francis Benson told me.
And it seems, as I went to this Friend`'s house,
I met one man coming from the sessions that had this five pounds offered him to take me,
and he knew me; for as I passed by him, he said to his companion, that is George Fox;
yet he had not power to touch me, for the Lord`'s power preserved me over them all.
The justices being so eager to have me, and I being so often near them,
and yet they missing me, tormented them the more.

I went thence to James Taylor`'s at Cartmel, where I stayed First-day,
and had a precious meeting; and after it I came over the Sands to Swarthmore.

When I came there, they told me,
Colonel Kirby had sent his lieutenant thither to take me,
and that he had searched trunks and chests for me.
That night as I was in bed, I was moved of the Lord to go next day to Kirby-hall,
which was Colonel Kirby`'s house, about five miles off, to speak with him, and I did so.
When I came thither, I found the Flemings,
and several others of the gentry (so called) of the country,
come to take their leave of Colonel Kirby,
he being about to go up to London to the parliament.
I was shown into the parlour amongst them; but Colonel Kirby was not then within,
being gone out; so they said little to me, nor I much to them.
But presently he came in, and I told him, that understanding he was desirous to see me,
"`I came to visit him, to know what he had to say to me,
and whether he had any thing against me.`"
He said, before all the company, "`As he was a gentleman, he had nothing against me.
But,`" said he, "`Mistress Fell must not keep great meetings at her house,
for they meet contrary to the act.`"
I told him, "`that act did not take hold on us, but on such as met to plot and contrive,
and to raise insurrections against the king, whereas we were no such people;
for he knew that they that met at Margaret Fell`'s house, were his neighbours,
and a peaceable people.`"
After many words had passed, he shook me by the hand, and said again,
"`he had nothing against me;`" and others of them said, I was a deserving man.
So we parted, and I returned to Swarthmore.

Shortly after, when Colonel Kirby was gone to London,
there was a private meeting of the justices and deputy-lieutenants at Holker-Hall,
where Justice Preston lived; and there they granted a warrant to apprehend me.
I heard over-night both of their meeting and of the warrant,
and so could have escaped out of their reach if I would;
for I had not appointed any meeting at that time, and I had cleared myself of the north,
and the Lord`'s power was over all.
But I considered, there being a noise of a plot in the north, if I should go away,
they might fall upon Friends; but if I gave up myself to be taken, it might stop them,
and the Friends should escape the better.
So I gave up to be taken, and prepared myself against they came.
Next day an officer came with sword and pistols to take me.
I told him, "`I knew his errand before, and had given up myself to be taken;
for if I would have escaped their imprisonment,
I could have gone forty miles off before he came; but I was an innocent man,
and so cared not what they could do to me.`"
He asked me "`how I heard of it, seeing the order was made privately in a parlour.`"
I said it was no matter, it was sufficient that I heard of it.
I asked him to let me see his order; whereupon he laid his hand on his sword, and said,
"`I must go with him before the lieutenants,
to answer such questions as they should propose to me.`"
I told him it was but civil and reasonable for him to let me see his order;
but he would not.
Then said I, I am ready.
So I went along with him, and Margaret Fell accompanied us to Holker-hall.
When we came thither, there was one Rawlinson, a justice,
and one called Sir George Middleton, and many more that I did not know,
besides old Justice Preston who lived there.
They brought Thomas Atkinson, a Friend of Cartmel, as a witness against me,
for some words which he had told to one Knipe, who had informed them; which words were,
"`that I had written against the plotters, and had knocked them down.`"
These words they could not make much of, for I told them I had heard of a plot,
and had written against it.
Old Preston asked me, whether I had a hand in that script?
I asked him what he meant?
He said, in the Battledore.
I answered, Yes.
Then he asked me, whether I understood languages.
I said, sufficient for myself; and that I knew no law that was transgressed by it.
I told them also, that to understand outward languages, was no matter of salvation;
for the many tongues began but at the confusion of Babel;
and if I did understand anything of them,
I judged and knocked them down again for any matter of salvation that was in them.
Thereupon he turned away, and said, "`George Fox knocks down all the languages:
come,`" said he, "`we will examine you of higher matters.`"

Then said George Middleton, "`You deny God, and the church, and the faith.`"
I replied, "`Nay, I own God and the true church, and the true faith.
But what church dost thou own?`"
said I, (for I understood he was a Papist). Then he turned again and said,
"`you are a rebel and a traitor.`"
I asked him to whom he spoke, or whom did he call rebel:
he was so full of envy that for a while he could not speak, but at last he said,
"`he spoke it to me.`"
With that I struck my hand on the table, and told him,
"`I had suffered more than twenty such as he, or than any that was there;
for I had been cast into Derby dungeon for six months together,
and had suffered much because I would not take
up arms against this king before Worcester fight.
I had been sent up prisoner out of my own country by Colonel Hacker to Oliver Cromwell,
as a plotter to bring in King Charles in the year 1654;
and I had nothing but love and good-will to the king,
and desired the eternal good and welfare of him and all his subjects.`"
"`Did you ever hear the like,`" said Middleton.
"`Nay,`" said I, "`ye may hear it again if ye will.
For ye talk of the king, a company of you, but where were ye in Oliver`'s days,
and what did ye do then for him?
But I have more love to the king for his eternal good and welfare than any of you have.`"

Then they asked me, "`whether I had heard of the plot?`"
and I said, "`yes, I had heard of it.`"
They asked me, how I had heard of it, and whom I knew in it?
I told them, I had heard of it through the highsheriff of Yorkshire,
who had told Dr. Hodgson that there was a plot in the north;
that was the way I heard of it; but I never heard of any such thing in the south,
nor till I came into the north.
And as for knowing any in the plot, I was as a child in that, for I knew none of them.
Then said they, "`why would you write against it,
if you did not know some that were in it.`"
I said, "`my reason was,
because you are so forward to mash the innocent and guilty together,
therefore I wrote against it to clear the truth from such things,
and to stop all forward, foolish spirits from running into such things.
I sent copies of it into Westmorland, Cumberland, Durham, and Yorkshire, and to you here.
I sent another copy of it to the king and his council,
and it is likely it may be in print by this time.`"
One of them said, "`O, this man hath great power!`"
I said, "`yes, I had power to write against plotters.`"
Then said one of them, "`you are against the laws of the land.`"
I answered, "`nay, for I and my Friends direct all people to the Spirit of God in them,
to mortify the deeds of the flesh.
This brings them into well-doing, and from that which the magistrate`'s sword is against,
which eases the magistrates, who are for the punishment of evil-doers.
So people being turned to the Spirit of God,
which brings them to mortify the deeds of the flesh,--this
brings them from under the occasion of the magistrate`'s sword;
and this must needs be one with magistracy, and one with the law,
which was added because of transgression, and is for the praise of them that do well.
In this we establish the law, are an ease to the magistrates, and are not against,
but stand for, all good government.`"

Then George Middleton cried,
"`Bring the book and put the oaths of allegiance and supremacy to him.`"
Now he himself being a Papist, I asked him, "`whether he had taken the oath of supremacy,
who was a swearer?
As for us, we could not swear at all, because Christ and the apostle had forbidden it.`"
Some of them would not have had the oath put to me, but Lave set me at liberty.
But the rest would not agree to that; for this was their last snare,
and they had no other way to get me into prison,
as all other things had been cleared to them.
This was like the Papist`'s sacrament of the altar, by which they ensnared the martyrs.
So they tendered me the oath, which I could not take;
whereupon they were about to make my mittimus to send me to Lancaster jail;
but considering of it, they only engaged me to appear at the sessions,
and so for that time dismissed me.
I went back with Margaret Fell to Swarthmore; and soon after Colonel West came to see me,
who was at that time a justice of peace.
He told us, "`he acquainted some of the rest of the justices,
that he would come over to see me and Margaret Fell; but it may be,`" said he,
"`some of you will take offence at it.`"
I asked him,
"`What he thought they would do with me at the sessions;`" and
he said "`they would tender the oath to me again.`"

Whilst I was at Swarthmore, William Kirby came into Swarthmore meeting,
and brought the constables with him.
I was sitting with Friends in the meeting, and he said to me,
"`How now, Mr. Fox! you have a fine company here.`"
"`Yes,`" said I, "`we meet to wait upon the Lord.`"
So he began to take the names of Friends,
and them that did not readily tell him their names,
he committed to the constables`' hands, and sent some to prison.
The constables were unwilling to take them without a warrant,
whereupon he threatened to set them by the heels; but one of the constables told him,
"`he could keep them in his presence, but after he was gone,
he could not keep them without a warrant.`"

The sessions coming on, I went to Lancaster, and appeared according to my engagement.
There was upon the bench Justice Fleming,
who had bid five pounds in Westmorland to any man that would apprehend me;
for he was a justice both in Westmorland and Lancashire.
There were also Justice Spencer, Colonel West, and old Justice Rawlinson the lawyer,
who gave the charge, and was very sharp against truth and Friends;
but the Lord`'s power stopped them.
The session was large, and the concourse of people great; and way being made for me,
I came up to the bar and stood there with my hat on, they looking earnestly upon me,
and I upon them for a pretty space.
Proclamation being made for all to keep silence upon pain of imprisonment,
and all being quiet, I said twice, "`Peace be among you.`"
The chairman asked, "`if I knew where I was;`" I said, "`yes, I do,
but it may be,`" said I, "`my hat offends you; that is a low thing,
that is not the honour that I give to magistrates, for the true honour is from above;
which I have received,
and I hope it is not the hat which ye look upon to be the honour.`"
The chairman said, "`they looked for the hat too,`" and asked,
"`wherein I showed my respect to magistrates, if I did not put off my hat?`"
I replied, "`in coming when they called me.`"
Then they bid one, "`take off my hat.`"
After which it was some time before they spoke to me,
and I felt the power of the Lord to arise.
After some pause, old Justice Rawlinson, the chairman, asked me,
"`if I knew of the plot?`"
I told him, "`I had heard of it in Yorkshire by a Friend,
that had it from the high-sheriff.`"
Then they asked me, "`whether I had declared it to the magistrates.`"
I said, "`I had sent papers abroad against plots and plotters, and also to you,
as soon as I came into the country,
to take all jealousies out of your minds concerning me and my friends;
for it was and is our principle to declare against such things.`"
They asked me then, "`if I knew not of an act against meetings.`"
I said, "`I knew there was an act that took hold of such
as met to the terrifying of the king`'s subjects,
and were enemies to the king, and held dangerous principles; but I hoped,
they did not look upon us to be such men,
for our meetings were not to terrify the king`'s subjects,
neither are we enemies to him or any man.`"
Then they tendered me the oaths of allegiance and supremacy.
I told them, "`I could not take any oath at all,
because Christ and his apostle had forbid it;
and they had had sufficient experience of swearers, first one way, then another;
but I had never taken any oath in my life.`"
Then Rawlinson asked me, "`whether I held it was unlawful to swear?`"
This question he put on purpose to ensnare me; for by an act that was made,
such were liable to banishment or a great fine, that should say,
it was "`unlawful to swear.`"
But I seeing the snare, avoided it, and told him,
"`that in the time of the law amongst the Jews, before Christ came,
the law commanded them to swear; but Christ, who doth fulfil the law in his gospel-time,
commands, '`not to swear at all;`' and the apostle James forbids swearing,
even to them that were Jews, and had the law of God.`"
After much discourse, they called for the jailer, and committed me to prison.

I had about me the paper which I had written as a testimony against plots,
which I desired they would read, or suffer to be read, in open court; but they would not.
So being committed for refusing to swear, "`I bid them and all the people take notice,
that I suffered for the doctrine of Christ, and for my obedience to his command.`"
Afterwards I understood the justices said,
they had private instructions from Colonel Kirby to prosecute me,
notwithstanding his fair carriage and seeming kindness to me before,
when he declared before many of them "`that he had nothing against me.`"
Several other Friends were committed to prison, some for meeting to worship God,
and some for not swearing; so that the prison was very full.
Many of them being poor men,
that had nothing to maintain their families by but their labour,
which now they were taken from,
several of their wives went to the justices who had committed their husbands,
and told them, "`if they kept their husbands in jail for nothing but the truth of Christ,
and for good conscience`' sake,
they would bring their children to them to be maintained.`"
A mighty power of the Lord rose in Friends, and gave them great boldness,
so that they spoke much to the justices.
Friends also that were prisoners wrote to the justices,
laying the weight of their sufferings upon them,
and showing them both their injustice and want
of compassion towards their poor neighbours,
whom they knew to be honest, conscientious, peaceable people,
that in tenderness of conscience could not take any oath;
yet they sent them to prison for refusing to take the oath of allegiance.
Several who were imprisoned on that account were known
to be men that had served the king in his wars,
and had hazarded their lives in the field in his cause, and had suffered great hardships,
with the loss of much blood for him,
and had always stood faithful to him from first to last,
and had never received any pay for their service.
To be thus requited for all their faithful services and sufferings,
and that by them that pretended to be the king`'s friends, was hard, unkind,
and ungrateful dealing.
At length the justices being continually attended with complaints of grievances,
released some of the Friends, but kept divers of them still in prison.

Amongst those that were then in prison, there were four Friends for tithes,
who had been sent at the suit of the Countess of Derby,
and had lain near two years and a half.
One of these, Oliver Atherton, a man of a weakly constitution, was,
through his long and hard imprisonment in a cold, raw, unwholesome place,
brought so low and weak in his body, that there appeared no hope of his life,
unless he might be removed.
Wherefore a letter was written on his behalf to the Countess,
and sent by his son Godfrey Atherton,
wherein were laid before her "`the reasons why he and the rest could not pay tithes;
because, if they did, they should deny Christ come in the flesh,
who by his coming had put an end to tithes,
and to the priesthood to which they had been given,
and to the commandment by which they had been paid under the law.
His weak condition of body was also laid before her,
and the apparent likelihood of his death if she continued to hold him there;
that she might be moved to pity and compassion,
and also warned not to draw the guilt of his innocent blood upon herself.`"
When his son went to her with his father`'s letter, a servant of hers abused him,
plucked off his cap, and threw it away, and put him out of the gate.
Nevertheless the letter was delivered into her own hand,
but she shut out all pity and tenderness, and continued him in prison till death.
When his son returned to his father in prison, and told him, as he lay on his dying bed,
that the Countess denied his liberty, he only said,
"`She hath been the cause of shedding much blood,
but this will be the heaviest blood that ever she spilt;`" and soon after he died.
Friends having his body delivered to them to bury,
as they carried it from the prison to Ormskirk, the parish wherein he had lived,
they stuck up papers upon the crosses at Garstang, Preston, and other towns,
through which they passed, with this inscription:--"`__This is Oliver Atherton,
of Ormskirk parish,
persecuted to death by the Countess of Derby for
good conscience`' sake towards God and Christ,
because he could not give her tithes,__`" etc.;
setting forth at large the reasons of his refusing to pay tithes,
the length of his imprisonment, the hardships he had undergone,
her hard-heartedness towards him, and the manner of his death.

After his death, Richard Cubban, another of her prisoners for tithes,
wrote a large letter to her, on behalf of himself and his fellow-prisoners at her suit,
laying their innocency before her; and "`that it was not out of wilfulness, stubbornness,
or covetousness, that they refused to pay her tithes,
but purely in good conscience towards God and Christ; and letting her know that,
if she should be suffered to keep them there till they every one died,
as she had done their fellow-sufferer Oliver Atherton, they could not yield to pay her.
And therefore desired her to consider their case in a Christian spirit,
and not bring their blood upon herself also.`"
But she would not show any pity or compassion towards them,
who had now suffered hard imprisonment about two years and a half under her.
Instead thereof she sent to Garstang, and threatened to complain to the king and council,
and bring them into trouble,
for suffering the paper concerning Oliver Atherton`'s death to be stuck upon their cross.
The rage that she expressed made the people take the more notice of it,
and some of them said, "`the Quakers had given her a bone to pick.`"
But she, that regarded not the life of an innocent sufferer for Christ,
lived not long after herself;
for that day three weeks that Oliver Atherton`'s
body was carried through Ormskirk to be buried, she died;
and her body was carried that day seven weeks through the same town to her burying-place.
Thus the Lord pursued the hard-hearted persecutor.

I was kept till the assize; and Judge Turner and Judge Twisden coming that circuit,
I was brought before Judge Twisden on the 14th day of the month called March,
in the year 1663.
When I was set to the bar, I said, "`Peace be amongst you all.`"
The judge looked upon me, and said, "`What! do you come into the court with your hat on?`"
Upon which, the jailer taking it off, I said,
"`The hat is not the honour that comes from God.`"
Then said the judge to me, "`Will you take the oath of allegiance, George Fox?`"
I said, "`I never took any oath in my life, nor any covenant or engagement.`"
"`Well,`" said he, "`will you swear or not?`"
I answered, "`I am a Christian,
and Christ commands me '`not to swear,`' and so does the apostle James,
and whether I should obey God or man, do thou judge.`"
"`I ask you again,`" said he, "`whether you will swear or not?`"
I answered again, "`I am neither Turk, Jew, nor heathen, but a Christian,
and should show forth Christianity.`"
And I asked him, "`if he did not know that Christians in the primitive times,
under the ten persecutions, and some also of the martyrs in Queen Mary`'s days,
refused swearing, because Christ and the apostle had forbidden it?`"
I told him also, "`they had had experience enough,
how many men had first sworn for the king and then against him.
But as for me, I had never taken an oath in my life;
and my allegiance did not lie in swearing, but in truth and faithfulness;
for I honour all men, much more the king.
But Christ, who is the great Prophet, and King of kings, who is the Saviour of the world,
and the great Judge of all the earth, saith, '`I must not swear.`'
Now, whether must I obey Christ or thee?
For it is in tenderness of conscience,
and in obedience to the commands of Christ that I do not swear;
and we have the word of a king for tender consciences.`"
Then I asked the judge, "`if he owned the king?`"
"`Yes,`" said he, "`I do own the king.`"
"`Why then,`" said I, "`dost thou not observe his declaration from Breda,
and his promises made since he came into England,
'`that no man should be called in question for matters of religion,
so long as he lived peaceably?`'
If thou ownest the king,`" said I, "`why dost thou call me into question,
and put me upon taking an oath, which is a matter of religion,
seeing neither thou nor any else can charge me with unpeaceable living?`"
Upon this he was moved, and looking angrily at me, said, "`Sirrah, will you swear?`"
I told him, "`I was none of his sirrahs, I was a Christian; and for him,
an old man and a judge, to sit there and give nick-names to prisoners,
it did not become either his grey hairs or his office.`"
"`Well,`" said he, "`I am a Christian too.`"
"`Then do Christian works,`" said I. "`Sirrah!`" said he,
"`thou thinkest to frighten me with thy words.`"
Then catching himself, and looking aside, he said,
"`Hark! I am using the word +++[+++sirrah] again;`" and so checked himself.
I said, "`I spoke to thee in love; for that language did not become thee, a judge.
Thou oughtest to instruct a prisoner in the law, if he were ignorant and out of the way.`"
"`And I speak in love to thee too,`" said he.
"`But,`" said I, "`love gives no nick-names.`"
Then he roused himself up, and said, "`I will not be afraid of thee, George Fox;
thou speakest so loud, thy voice drowns mine and the court`'s;
I must call for three or four criers to drown thy voice: thou hast good lungs.`"
"`I am a prisoner here,`" said I, "`for the Lord Jesus Christ`'s sake;
for his sake do I suffer, for him do I stand this day;
and if my voice were five times louder, I should lift it up,
and sound it for Christ`'s sake,
for whose cause I stand this day before your judgment-seat, in obedience to Christ,
who commands not to swear;
before whose judgment-seat you must all be brought and must give an account.`"
"`Well,`" said the judge,
"`George Fox, say, whether thou wilt take the oath, yea or nay?`"
I replied, "`I say, as I said before, whether ought I to obey God or man, judge thou?
If I could take any oath at all, I should take this; for I do not deny some oaths only,
or on some occasions, but all oaths, according to Christ`'s doctrine,
who hath commanded his followers not to swear at all.
Now if thou or any of you, or your ministers or priests here,
will prove that ever Christ or his apostles, after they had forbid all swearing,
commanded Christians to swear, then I will swear.`"
I saw several priests there, but not one of them offered to speak.
"`Then,`" said the judge, "`I am a servant to the king,
and the king sent me not to dispute with you, but to put the laws in execution;
therefore tender him the oath of allegiance.`"
"`If thou love the king,`" said I, "`why dost thou break his word,
and not keep his declarations and speeches,
wherein he promised liberty to tender consciences?
I am a man of a tender conscience, and, in obedience to Christ`'s command,
I cannot swear.`"
"`Then you will not swear,`" said the judge; "`take him away, jailer.`"
I said, "`It is for Christ`'s sake that I cannot swear,
and for obedience to his command I suffer, and so the Lord forgive you all.`"
So the jailer took me away; but I felt the mighty power of the Lord was over them all.

The sixteenth day of the same month I was brought before Judge Twisden again:
he was somewhat offended at my hat;
but it being the last morning of the assize before he was to leave town,
and not many people there, he made the less of it.
He asked me, "`whether I would traverse, stand mute, or submit.`"
But he spoke so fast that it was hard to know what he said.
However, I told him, "`I desired I might have liberty to traverse the indictment,
and try it.`"
Then said he, "`Take him away, I will have nothing to do with him, take him away.`"
I said, "`Well, live in the fear of God, and do justice.`"
"`Why,`" said he, "`have not I done you justice?`"
I replied, "`That which thou hast done has been against the command of Christ.`"
So I was taken to the jail again, and kept prisoner till the next assizes.

Some time before this assize,
Margaret Fell was sent prisoner to Lancaster jail by Fleming Kirby, and Preston,
justices; and at the assize the oath was tendered to her also,
and she was again committed to prison, to lie till the next assize.

Now Justice Fleming being one of the fiercest
and most violent justices in persecuting Friends,
and sending his honest neighbours to prison for religion`'s sake,
and many Friends being at this time in Lancaster jail committed by him,
and some having died in prison,
we that were then prisoners had it upon us to write to him, as follows:--

[.salutation]
"`O Justice Fleming!

"`Mercy, compassion, love, and kindness adorn and grace men and magistrates.
O! dost thou not hear the cry of the widows, and the cry of the fatherless,
who were made so through persecution!
Were they not driven, like sheep, from constable to constable,
as though they had been the greatest transgressors or malefactors in the land?
Which grieved and tendered the hearts of many sober people,
to see how their innocent neighbours and countrymen, who were of a peaceable carriage,
and honest in their lives and conversations amongst men, were used and served!
One more is dead whom thou sent to prison, having left five children,
both fatherless and motherless.
How canst thou do otherwise than take care of these fatherless infants,
and also of the other`'s wife and family?
Is it not thy place?
Consider Job (c. xxix). He was a father to the poor, he delivered the poor that cried,
and the fatherless that had none to help.
He broke the jaws of the wicked, and plucked the spoil out of his teeth.
But oh! measure thy life and his, and take heed of the day of God`'s eternal judgment,
which will come, and the sentence and decree from Christ,
when every man must give an account, and receive a reward according to his deeds.
Then it will be said, '`O, where are the months that are past!`' Again, Justice Fleming,
consider, when John Stubbs was brought before thee,
having a wife and four small children, and little to live on,
but what they honestly got by their own diligence,
as soon as he appeared thou criedst out, '`Put the oath to that man.`'
And when he confessed that he was but a poor man, thou hadst no regard;
but cast away pity, not hearing what he would say.
And now he is kept in prison, because he could not swear,
and break the command of Christ and the apostle;
it is to be hoped thou wilt take care for his family, that his children do not starve;
and see that they do not want bread.
Can this be allegiance to the king, to do that which Christ and his apostle say is evil,
and brings into condemnation?
Would not you have cast Christ and the apostle into prison,
who commanded '`not to swear,`' if they had been in your days?

"`Consider also thy poor neighbour, William Wilson,^
footnote:[Of the William Wilson here alluded to,
the following particulars have been gathered:--He was a man of an innocent life,
and though he had little outward learning, God was pleased to teach him himself,
and called him to bear a testimony to his name, which he did faithfully,
not only in many parts of England, but in Germany and Scotland,
which he visited several times.
He was of a lowly and meek spirit, upright and just among his neighbours,
which caused them often to submit their differences to his arbitration,
in which he was careful to find out the real truth, and would never countenance deceit.
In this service he was successful, seldom missing his desired end, viz., to restore peace.
He was faithful in his testimony for the truth,
and a sufferer for the same in prison at Kendal, in 1666, and several times afterwards,
as well as by distress on his goods.
Besides which he suffered cruel mockings, stoning, blows, and wounds,
both from priests and people, particularly at Eskdale,
where he exhorted the people "`to mind that of God in their consciences,
and turn to that holy light and law which he had put into their inward parts,
that by the same they might come to know the will of God, and do it.`"
Because of these and like words, one Parker, a priest, beat and wounded him,
and with one of his crutches broke his head, causing the blood to run down his shoulders.
The priest being lame, and not able as he would to effect his cruel purpose,
caused his horse to be brought, on which he mounted,
and in the sight of the people broke his staff
in three pieces upon William Wilson`'s bare head,
which made them cry out against such merciless behaviour.
Before the priest got home, he was overtaken with sickness,
and never came more to the steeple-house.
During the time of his sickness he was very loathsome,
and so died.
{footnote-paragraph-split}
A few weeks after,
William Wilson went to the same place at Eskdale, and for speaking to the people,
one Fogo, a priest, took him by the hair of the head, pulled him to the ground,
and drew him out.
In rage and cruelty he also abused his brother Michael Wilson; but a few months after,
this same Fogo, riding over some sands, accompanied by several people,
fell into a quicksand,
and was immediately smothered.
{footnote-paragraph-split}
William Wilson left behind him a widow and two daughters,
to whom he was a true husband and a tender father,
instructing his children "`to keep in the fear of the Lord,
and to walk in the way of truth, which he walked in himself;`" often saying to them,
"`it would be the best portion that they could enjoy.`"
His last illness was short.
Having recently returned from a long journey, wherein his body was much spent and weak,
he said, "`I have not served the Lord unfruitfully; I have no trouble upon me;
and I am very sensible that all is well with me.`"
Again he said, "`He was content, whatsoever way the Lord pleased; he felt as a dove,
harmless; and as a lamb, innocent.`"
A few hours before he died, at which time he walked several times over the room, he said,
as he had often before,
"`My peace far exceeds my pain;`" and standing upon his feet between two Friends,
he said, "`O that every one would mind the Lord, that they might keep life.`"
He then sat down,
and drew breath no more.
{footnote-paragraph-split}
He died at his own house at Langdale,
the 10th of the 5th month, 1682.]
who was known to all the parish and neighbours to be an industrious man,
and careful to maintain his wife and children; yet had little,
but what he got with his hands in diligence and travels to supply himself.
How should his wife maintain her children, when thou hast cast her husband into prison,
and thereby made him incapable of working for them?
Therefore it may be expected, thou wilt have a care of his wife and children,
and see they do not want; for how should they live, having no other way to be sustained,
but by the little that he got?
Surely the noise of this is in the very markets, the death of thy two neighbours;
and the cry of the widows and fatherless is heard.
All those fatherless and widows are made so for righteousness`' sake.
For might not John Stubbs and William Wilson have had their liberty still,
if they would have sworn,
though they had been such as go after mountebanks and stage-plays, or run a hunting?
O! consider, for the Lord`'s mind is otherwise; he is tender.
And the king hath declared his mind to be,
that there should be no cruelty inflicted upon his peaceable subjects.
Besides, several poor, honest people were fined,
who had need to have something given them;
and it had been more honourable to have given them something,
than to fine them and send them to prison;
some of whom live upon the charity of other people.
What honour or grace can it be to thee,
to cast thy poor neighbours into prison who are peaceable,
seeing thou knowest these people cannot do that which thou requirest of them,
if it were to save their lives, or all that they have?
Because in tenderness they cannot take any oath, thou makest that a snare to them.
What, thinkest thou, do the people say concerning this?`'
We know,`' say they, '`the Quakers`' principle, that keep to Yea and Nay;
but we see others swear and forswear.`'
For many of you have sworn first one way and then another.
So we leave it to the Spirit of God in thy conscience, Justice Fleming,
who wast so eager for the taking of George Fox,
and so offended with them that had not taken him,
and now hast fallen upon thy poor neighbours.
But, oh! where is thy pity for their poor, fatherless children, and motherless infants?
O, take heed of Herod`'s hard-heartedness, and casting away all pity!
Esau did so, not Jacob.

"`Here is also Thomas Walters, of Bolton, cast into prison,
and the oath imposed on him through thee; and for denying to swear at all,
in obedience to Christ`'s command, he is continued in prison; having five small children,
and his wife near confinement.
Surely thou shouldst take care for them also,
and see that his wife and small children do not want; who are as fatherless,
and she as a widow, through thee.
Dost thou not hear in thy ears the cry of the fatherless, and the cry of the widows,
and the blood of the innocent speak, who through thee have been persecuted to prison,
and are now dead?
O, heavy sentence at the day of judgment!
How wilt thou answer,
when thou and thy works come to be judged,--when thou shalt be
brought before the judgment-seat of the Almighty,
who in thy prosperity hast made widows and fatherless for righteousness`' sake,
and for tenderness of conscience towards God?
The Lord knows and sees it!
O man! consider in thy life-time,
how thou hast stained thyself with the blood of the innocent!
When thou hadst power, and might have done good amongst thy peaceable neighbours,
and would not, but used thy power not to a good intent,
but contrary to the Lord`'s mind and to the king`'s. The king`'s favour, his mercy,
and clemency to sober people, and to tender consciences,
have been manifested by declarations and proclamations,
which thou hast abused and slighted by persecuting his peaceable subjects.
For at London, and in other parts, the Quakers`' meetings are peaceable;
and if thou look but as far as Yorkshire, where the plot hath been,
Friends`' innocency hath cleared itself in the hearts of sober justices;
and for you here to fall upon your peaceable neighbours and people,
and to be rigorous and violent against them that are tender, godly, and righteous,
it is no honour to you.
How many drunkards and swearers, fighters, and such as are subject to vice,
have you caused to be brought before your courts?
It were more honourable for you to look after such;
for the law was not made for the righteous, but for sinners and transgressors.
Therefore, consider, and be humbled for these things;
for the Lord may do to thee as thou hast done to others;
and thou dost not know how soon there may be a cry in thy own family,
as the cry is amongst thy neighbours,
of the fatherless and widows that are made so through thee.
But the Quakers can and do say, '`the Lord forgive thee,
and lay not these things to thy charge, if it be his will.`"'`^
footnote:[We cannot be surprised at the hard language sometimes used by the early
Friends in protesting against the unchristian conduct of their persecutors.
The rapacity of their enemies in the early periods of
the Society carried their plunder to so great an excess,
as not only to involve many in total ruin,
but subjected them to long and cruel imprisonments, which,
in many cases of particular hardship,
terminated in death.
{footnote-paragraph-split}
It has already been stated
that at one time there were 4500 Quakers in prison in England and Wales at one time.
In 1622, twenty died in different prisons in London,
and seven more after their liberation, from ill treatment.
In 1664, twenty-five died, and in 1665, fifty-two more.
The number which perished in this way, throughout the whole kingdom,
amounted to 369. But for fuller particulars of the
cruelties practised against the early Quakers,
the reader is referred to the two closely printed folio volumes,
entitled Besse`'s _Sufferings._]

Besides this, which went in the name of many,
I sent him also a line subscribed by myself only, and directed--

[.letter-heading]
To Daniel Fleming.

[.salutation]
"`Friend,

"`Thou hast imprisoned the servants of the Lord, without the breach of any law;
therefore take heed what thou doest, for in the light of the Lord God thou art seen,
lest the hand of the Lord be turned against thee!`"

[.signed-section-signature]
G+++.+++ F.

It was not long after this ere Fleming`'s wife died,
and left him thirteen or fourteen motherless children.

When I was prisoner at Lancaster, there was prisoner also one Major Wiggan,
a Baptist preacher.
He boasted much beforehand what he would say at the assize,
if the oath should be put to him; and that he would refuse to swear.
But when the assize came, and the oath was tendered him,
he desired time to consider of it; and that being granted him till the next assize,
he got leave to go to London before the assize came again,
and stayed there till the plague broke forth,
and there both he and his wife were cut off.
He was a very wicked man, and the judgments of God came upon him;
for he had published a book against Friends, full of lies and blasphemies;
the occasion of which was this.
Whilst he was in Lancaster castle he challenged Friends to a dispute.
Whereupon I got leave of the jailer to go up to them;
and entering into discourse with him, he affirmed,
"`that some men never had the Spirit of God, and that the true light,
which enlighteneth every man that cometh into the world, is natural.`"
For proof of his assertion he instanced Balaam, affirming,
that "`Balaam had not the Spirit of God.`"
I affirmed and proved, "`that Balaam had the Spirit of God,
and that wicked men have the Spirit of God; else how could they quench it, and vex it,
and grieve it, and resist the Holy Ghost, like the stiffnecked Jews?`"
To his second affirmation I answered, "`that the true light,
which enlighteneth every man that cometh into the world, was the life in the Word,
and that was divine and eternal, and not natural;
and he might as well say that the Word was natural,
as that the life in the Word was natural.
And wicked men were enlightened by this light, else how could they hate it?
Now it is expressly said, that they did hate it;
and the reason given why they hated it was,
because '`their deeds were evil;`' and they would not come to it, because it reproved them;
and that must needs be in them, that reproved them.
Besides, that light could not be the Scriptures of the New Testament,
for it was testified of before any part of the New Testament was written;
so it must be the divine light, which is the life in Christ, the Word,
before the Scriptures were.
And the grace of God, which brought salvation, had appeared unto all men,
and taught the saints; but they that turned it into wantonness,
and walked despitefully against the Spirit of grace, were the wicked.
Again, the Spirit of Truth, the Holy Ghost, the Comforter,
which leads the disciples of Christ into all truth,
the same should reprove the world of sin, of righteousness, of judgment,
and of their unbelief.
So the wicked world had it to reprove them;
and the true disciples and learners of Christ,
that believed in the light as Christ commands, had it to lead them.
But the world that did not believe in the light, though they were lighted;
but hated the light which they should have believed in,
and loved the darkness rather than it,--this world had a righteousness and a judgment,
which the Holy Ghost reproved them for, as well as for their unbelief.`"
Having proved that the good and the bad were enlightened,
that the grace of God had appeared unto all, and that all had the Spirit of God,
else they could not vex and grieve it, I told Major Wiggan,
the least babe there might see him; and presently one Richard Cubham stood up,
and proved him an antichrist and a deceiver by Scripture.
Then the jailer had me away to my prison again.
Afterwards Wiggan wrote a book of this dispute, and put in abundance of abominable lies;
but it was soon answered in print, and himself not long after was cut off, as aforesaid.

This Wiggan was poor, and while he was a prisoner at Lancaster, he sent into the country,
and got money gathered for relief of the poor people of God in prison;
and many people gave freely, thinking it had been for us, when indeed it was for himself.
But when we heard of it, we laid it upon him, and wrote also into the country,
that Friends might let the people know the truth of the matter,
that it was not our manner to have collections made for us;
and that those collections were only for Wiggan and another,
a drunken preacher of his society.

[.offset]
After this it came upon me to write to the judges, and other magistrates,
concerning their "`giving evil words and nicknames to such as
were brought before them;`" which was after this manner:--

[.blurb]
=== "`To all judges, or other officers whatsoever, in the whole world, who profess yourselves to be Christians.

[.salutation]
"`Friends,

"`Herein and by reading the Scriptures, ye may see both your own words and behaviour,
and the words and practice of both Jews and Heathens, and of the King of kings,
the great Lawgiver and Judge of the whole world.
First, for the words and carriage of the Jews,
when such as were worthy of death were brought before the rulers amongst them.
When Achan had taken the Babylonish garment, and the two hundred shekels of silver,
and the wedge of gold of fifty shekels weight, and Joshua, who was then judge of Israel,
had by the lot found him out, he did not say unto him, Sirrah,^
footnote:[The word Sirrah must not be confounded with Sir.
It was no doubt made use of strictly in the sense of
the only meaning Walker gives to it in his Dictionary,
viz., "`A compellation of reproach and insult.`"]
nor, you rascal, knave, rogue, as some, that are called Christian magistrates,
are too apt to do.
But Joshua said unto Achan, '`My son`' (mark his clean language,
his savoury expression and gracious words), '`My son,`' said he, '`give, I pray thee,
glory to the Lord God of Israel, and make confession unto him,
and tell me now what thou hast done; hide it not from me.`'
Then Achan confessed, that he had sinned against the Lord God of Israel,
and thus and thus he had done.
Then Joshua the judge said, '`Why hast thou troubled Israel?
The Lord shall trouble thee this day.`'
And they stoned him and his with stones, and burnt his goods with fire.
But there was no unsavoury word given to him that we read of,
though he was worthy of death. Josh. 7.

"`So when the man that gathered sticks upon the
Sabbath-day was taken and brought before Moses,
the judge of Israel, and put in ward until the mind of the Lord was known concerning him,
we read not of any reviling language given him, but the Lord said to Moses,
and Moses to the people, '`The man shall surely be put to death,`' Num. 15:35.

"`Likewise in the rebellion of Korah, Dathan, and Abiram,
where Moses called them to trial, he did not sirrah them or miscall them,
but said to Korah and the rest, '`Hear, I pray you,
ye sons of Levi,`' Num. 16:8. And when he gave the sentence against them, he said,
'`If these men die the common death of all men,`' etc.
He did not say, If these rascals or knaves,
as many that profess themselves Christians now do.

"`When Elihu spoke to Job, who was a judge, and to his friends, and said,`' Let me not,
I pray you, accept any man`'s person, neither let me give flattering titles unto man,
for I know not to give flattering titles:
in so doing my Maker would soon take me away,`' Job 32.
Job did not say, '`Sirrah, hold thy tongue,`' nor give him any unsavoury expression.
Then for the words of David and Solomon, and other kings and officers,
see in the books of the Kings and Chronicles the savoury
language that they gave to them that were brought before them;
nay, though Shimei cursed David the king, yet neither did David then, or afterwards,
nor Solomon, when he caused him to be put to death, give him any reproachful language,
or so much as call him sirrah; 2 Sam. 16. and 1 Kings 2.

"`Read the prophecies of Isaiah and Micah, Jeremiah, Ezekiel,
and the Test of the prophets, who prophesied to several people, and against rulers,
kings, and magistrates; yet where can it be found,
that they had any bad language given them, as sirrah, or the like,
by any ruler either of the Jews or heathens?
Nay, though Jeremiah was cast into prison, and into the dungeon,
yet there was no such word as sirrah, or knave given to him. Jer. 37.

"`Then for the words and carriage of the heathens:
when Abraham was brought before Abimelech, who was a king,
he gave Abraham no unsavoury expressions, Gen. 20.
And when Isaac came before Abimelech, he gave him no taunting language either, Gen. 26.
When Joseph was cast into prison, and that in Egypt,
we do not read that he had any railing language given him, Gen. 39.
Neither did Pharaoh, when Moses and Aaron appeared before him, give them bad language,
as sirrah, knave, or the like.

"`When Nebuchadnezzar sentenced the three children to the fiery furnace,
there was no such language given them as sirrah, knave, rascal;
but he called them by the names they were known by, Dan.
iii. And when Daniel was brought before Darius,
and sentenced to be cast into the lions`' den, he had no such names given him,
as many give now, who call those rulers heathens, but themselves Christians.

"`If ye look into the New Testament, in the parable of the wedding supper, the king,
that came to view his guests,
did not say unto him that was found without a wedding-garment, '`Sirrah,
how earnest thou in hither?`'
But, '`Friend, how earnest thou in hither?`' etc.,
though he was one that was to be bound hand and foot, and cast into outer darkness, Matt. 22.
Nay, when Judas had betrayed his master, Christ Jesus, the Lord of life,
and had sold him to the priests, Christ did not call him sirrah,
when he came to apprehend him, but friend: Matt. 26:50. Stephen in his examination,
sentence, and death,
had no such reproachful word given him as sirrah, or knave, Acts 6. and 7.
When the apostles Peter and John were brought
before the high-priest and rulers of the Jews,
and commanded not to preach in the name of Jesus, Acts 4., they were not called sirrah,
or knaves, nor had they any such ill names given them.
And when Paul and Silas were cast into prison by the magistrates,
there was no such word given them in their examination, nor in their sentence, Acts xvi.
They called them men, not rogues, sirrahs, or knaves.
And when the magistrates had done contrary to law, they feared.
So ye may see how short of this example many are, that call themselves Christian rulers,
who are not afraid to cast innocent people into prison, and give them ill names besides,
below both Jews and Heathens.

"`When the uproar was at Ephesus about Diana`'s shrine, Demetrius,
who bore great sway among the craftsmen, did not call Paul sirrah, but Paul, Acts xix.
And when Paul was brought prisoner before the high-priest Ananias,
and the council of the Jews, and told them,
he had lived in all good conscience towards God until that day, though they,
who professed the Scriptures but lived out of the life of them,
could not bear to hear of living in a good conscience,
as professors of the Scriptures now, that live not in the life,
cannot bear to hear of living in a good conscience nowadays:
but Ananias caused Paul to be smitten on the mouth;
yet he did not call him knave nor sirrah, Acts xxiii.
The apostate Jews indeed, who, though they professed Scripture,
were out of the life thereof, and had rejected Christ,
in accusing Paul before the Roman magistrates,
did once call him a '`pestilent fellow,`' Acts 24., as the accusing professors,
who live out of the life, will sometimes call us now.
But Felix gave Paul no such language; neither did Festus nor King Agrippa,
in all their examinations of him, give him any such words as sirrah, rascal, knave,
or the like, but heard him patiently.
So now Christians may see through all the Scriptures,
that when any persons were brought before rulers, kings, or magistrates,
whether Jews or Heathens, they did not use to call them evil names, as sirrah, rascal,
knave, and the like; they had no such foul-mouthed language in their courts,
nor did they use to say to them, '`Sirrah, put off your hat.`'
Now, ye that profess Christianity, and say the Scripture is your rule, may see,
that more corrupt words proceed out of your mouths,
than either out of the Jews or Heathens, if ye will try your practice by the Scriptures.
And doth not the apostle tell you,
that no corrupt communication should proceed out of your mouths,
and that your words should be gracious?
Now I query, where and whence ye, that call yourselves Christians,
have got all these bad words and names, seeing neither God, nor Christ, nor the prophets,
nor the judges, nor kings, nor rulers, ever gave any such names,
so far as appears by Scripture, either amongst Heathens, Jews, or Christians?`"

[.signed-section-signature]
G+++.+++ F.

Before the next assizes, there was a quarter-sessions held at Lancaster by the justices;
to which though we were not brought,
I put Friends upon drawing up an account of their sufferings,
and laying them before the justices in their open sessions.
For Friends had suffered deeply by fines and distresses,
the bailiffs and officers making great havock and spoil of their goods;
but no redress was afforded.

And because some evil-minded magistrates would
tell us sometimes of the late plot in the North,
we gave forth the following paper to stop their mouths,
and to clear truth and Friends therefrom.

[.blurb]
=== "`A Testimony from the people of God, whom the world calls Quakers, to all magistrates and officers of what sort soever, from the highest to the lowest.

"`We are peaceable, and seek the peace, good, and welfare of all,
as in our lives and peaceable conduct is manifested;
and we desire the eternal good and welfare of all, and their souls`' everlasting peace.
We are become heirs of the blessing before the curse was,
and of the power of God before the devil was, and before the fall of man.
We are heirs of the gospel of peace, which is the power of God;
and we are heirs of Christ, who have inherited him and his everlasting kingdom,
and do possess the power of an endless life.
Knowing this our portion and inheritance,
this is to remove all jealousies out of your minds,
and out of the minds of all people concerning us, that all plots and conspiracies,
plotters and conspirators against the king, and all aiders and assisters thereunto,
we always did and do utterly deny to be of us,
or to be of the fellowship of the gospel of Christ`'s kingdom, or his servants.
For Christ said, '`his kingdom was not of this world; if it were,
his servants would fight.`'
And therefore he bid Peter '`put up his sword, for,`' said he, '`he that taketh the sword,
shall perish by the sword.`'
Here is the faith and patience of the saints, to bear and suffer all things,
knowing that vengeance is the Lord`'s, and he will repay it to them that hurt his people,
and wrong the innocent.
Therefore we cannot avenge, but suffer for his name`'s sake.
We know that the Lord will judge the world in righteousness,
according to their deeds, and that,
when every one shall give an account to him of the '`deeds done in the
body,`' then will the Lord give every man according to his works,
whether they be good or evil.
Christ said, he came not to '`destroy men`'s lives;`'
and when his disciples would have had '`fire to come down from heaven,`'
to consume them that did not receive him, he told them,
'`they knew not what spirit they were of,`' that would have men`'s lives destroyed,
and therefore he rebuked them and told them, '`that he came not to destroy men`'s lives,
but to save them.`'
We are of Christ`'s mind, who is the great Prophet, whom all ought to hear in all things,
who saith to his, '`if they strike thee on one cheek, turn the other;
and render to no one evil for evil.`'
This doctrine of his we have learned, and not only confess him in words,
but follow his doctrine; therefore we suffer all manner of reproaches, scandals,
slanders, spoiling of goods, buffetings, whippings, stripes, and imprisonments,
for these many years; and can say, '`the Lord forgive them that have thus served us,
and lay not these things to their charge.`'
And we know that the Jews`' outward sword, by which they cut down the Heathen outwardly,
was a type of the inward sword of the Spirit, which cuts down the inward Heathen,
the raging nature in people.
The blood of bulls, lambs, rams, and other offerings,
and that priesthood which offered them, together with other things in the law,
were types of Christ, the one offering, and of his blood,
who is the everlasting priest and covenant, our life and way to God,
the great prophet and shepherd, the head of his church,
and the great bishop of our souls, whom we witness come;
and he doth oversee and keep his flock.
For in Adam, in the fall, we know the striving, quarrelling,
unpeaceable spirits are in the enmity one with another, and not in peace;
but in Christ Jesus, the second Adam, that never fell, is peace, rest, and life.
The doctrine of Christ, who never sinned, is,
to '`love one another;`' and they who are in this doctrine, hurt no man, in which we are,
in Christ, who is our life.
Therefore it is well for you to distinguish between the precious and the vile,
between them that fear God and serve him, and them that do not;
and to make a difference between the innocent and the guilty,
between him that is holy and pure, and the ungodly and profane; for they that do not so,
bring troubles, burthens, and sorrows upon themselves.
This we write in love to your souls, that ye may consider these things;
for we cannot say that they who hate enemies and one another, are of God,
or in Christ`'s doctrine, but are opposers of it.
And such as wrestle with flesh and blood, with carnal weapons, are gone into the flesh,
out of the Spirit.
They are not in our fellowship in the Spirit, in which is the bond of peace;
neither are they of us, nor have we unity with them in their fleshly state,
and with their carnal weapons.
For our unity and fellowship stand in the gospel, which is the power of God,
before the devil was, the liar, and the murderer, the man-slayer, and the envious.
Christ`'s mind and his doctrine being to save men`'s lives, we, who are of Christ`'s mind,
are out of, and above these things.
And our desire is, that in the fear of the Lord, ye may all live,
and receive God`'s wisdom, by which all things were created,
that by it all may be ordered to His glory.

"`This is from them that love all your souls, and seek your eternal good.`"

[.offset]
Being now a prisoner in Lancaster castle,
a deep sense came upon me of a day of sore trial and exercise that was come
and coming upon all who had been in high profession of religion;
and I was moved to give forth the following paper as a warning to such:--

"`Now is the day that every one`'s faith and love to God and Christ will be tried;
they who are redeemed out of the earth, and they who are in the earth,
will be manifested; and who is the master they serve,
and whether they will run to the mountains to cover them.
Now will it appear who are the stony ground, who are the thorny ground,
and who are the highway ground, in whom the fowls of the air take away the seed,
and the thorns and cares of the world choke,
and the heat of persecution scorches and burns up your green blade;
for the day trieth all things.
Therefore let not such as forsake truth, for saving the earth,
say that your brother priest only '`serveth not the Lord Jesus Christ, but his own belly,
and mindeth earthly things,`' for such themselves also do the same,
and hug and embrace self, and not the Lord.
Now it will be made manifest, who is every one`'s God, Christ, and Saviour,
and their love will be manifest, whether it be of the world, or of God;
for if it be the love of the world, it is enmity,
and the enmity will manifest itself what it is;
and the day will try every spirit and his fruits.
Therefore, my dear friends, in the everlasting Seed of God live,
that is over all the house of Adam and his works in the fall;
and so dwelling in the Seed, Christ, that never fell, in him you all have virtue, life,
and peace, and through him ye will overcome all that is in the fall.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
I wrote also another epistle to Friends, to warn them to keep out of the spirit,
that wrought in John Perrot and his company against the truth:--

[.salutation]
"`Dear Friends,

"`Dwell in the love of God, and in his righteousness;
that will preserve you above all changeable spirits, that dwell not in the truth,
but in quarrels.
Avoid such, and keep your habitations in the truth.
Dwell in the truth, and in the Word of God, by which ye are reconciled to him.
Keep your meetings in the name of Jesus Christ, who never fell;
then ye will see over all the gatherings of Adam`'s sons and daughters,
you being met in the life over them all, in which are your unity, peace,
and fellowship with God, and one with another, in the life,
in which ye may enjoy God`'s presence among you.
So remember me to all Friends in the everlasting Seed of God.
The fellowship of all those that are got into fellowship in outward things,
will corrupt and wither away.
Therefore live in the gospel, the power of God, which was before the devil was.
This fellowship in the gospel, the power of God,
is a mystery to all the fellowships of the world.
So look over all outward sufferings, and look at the Lord, and the Lamb,
who is the First and the Last, the Amen; in whom farewell.`"

[.signed-section-signature]
G+++.+++ F.

In the sixth month, the assizes were held again at Lancaster, and the same judges,
Twisden and Turner, came that circuit again;
but Judge Turner then sat on the crown bench, and so I was brought before him.
Before I was called to the bar,
I was put among the murderers and felons for about two hours, the people, the justices,
and the judge also gazing upon me.
After they had tried several others, they called me to the bar, and empannelled a jury.
Then the judge asked the justices,
"`whether they had tendered me the oath at the sessions.`"
They said, "`they had.`"
Then he bid, "`give them the book,
that they might swear they had tendered me the oath at the sessions.`"
They said, "`they had.`"
Then he bid, "`give them the book,
that they might swear they had tendered me the oath according to the indictment.`"
Some of the justices refused to be sworn; but the judge said, he would have it done,
to take away all occasion of exception.
When the jury were sworn,
and the justices had sworn that "`they had tendered me the
oath according to the indictment,`" the judge asked me,
"`whether I had not refused the oath at the last assizes?`"
I said, "`I never took an oath in my life, and Christ,
the Saviour and Judge of the world, said,
'`Swear not at all.`'`" The judge seemed not to take notice of my answer, but asked me,
"`whether or not I had refused to take the oath at the last assizes?`"
I said, "`the words that I then spoke to them were, that if they could prove,
either judge, justices, priest, or teacher,
that after Christ and the apostle had forbidden swearing,
they commanded that Christians should swear, I would swear.`"
The judge said he was not at that time to dispute, whether it was lawful to swear,
but to inquire whether I had refused to take the oath or not.
I told him, "`those things mentioned in the oath, as plotting against the king,
and owning the Pope`'s, or any other foreign power, I utterly deny.`"
"`Well,`" said he, "`you say well in that, but did you deny to take the oath?
what say you?`"
"`What wouldst thou have me to say?`"
said I; "`for I have told thee before what I did say.`"
Then he asked me, "`if I would have these men to swear, that I had taken the oath?`"
I asked him, "`if he would have those men to swear, that I had refused the oath?`"
at which the court burst out into laughter.
I was grieved to see so much lightness in a court, where such solemn matters are handled,
and thereupon asked them, "`if this court was a play-house?
where is gravity and sobriety,`" said I, "`for this behaviour doth not become you.`"
Then the clerk read the indictment, and I told the judge,
"`I had something to speak to it;`" for I had
informed myself of the errors that were in it.
He told me, "`he would hear afterwards any reasons that I could allege,
why he should not give judgment.`"
Then I spoke to the jury, and told them,
"`that they could not bring me in guilty according to that indictment,
for the indictment was wrong laid, and had many gross errors in it.`"
The judge said, "`I must not speak to the jury,
but he would speak to them,`" and he told them,
I had denied to take the oath at the last assizes; and, said he,
"`I can tender the oath to any man now,
and premunire him for not taking it;`" and he said, they must bring me in guilty,
seeing I refused to take the oath.
Then said I, "`What do ye do with a form?
ye may throw away your form then.`"
And I told the jury, "`it lay upon their consciences,
as they would answer it to the Lord God before his judgment-seat.`"
Then the judge spoke again to the jury, and I called to him to "`do me justice.`"
The jury brought me in guilty.
Whereupon I told them, that "`both the justices and they had forsworn themselves,
and therefore they had small cause to laugh, as they did a little before.`"
O! the envy, rage, and malice that appeared against me, and the lightness;
but the Lord confounded them, and they were wonderfully stopped.
So they set me aside, and called up Margaret Fell, who had much good service among them;
and then the court broke up near the second hour.

In the afternoon we were brought again to have sentence passed upon us.
Margaret Fell desired, that sentence might be deferred till the next morning.
I desired nothing but law and justice at his hands, for thieves had mercy;
only I requested the judge to send some one to see my prison, which was so bad,
they would put no creature they had in it; and I told him, that Colonel Kirby,
who was then on the bench, said, "`I should be locked up,
and no flesh alive should come to me.`"
The judge shook his head, and said, "`when the sentence was given,
he would leave me to the favour of the jailer.`"
Most of the gentry of the country were gathered together, expecting to hear the sentence;
and the noise among the people was, "`that I should be transported.`"
But they were all crossed at that time;
for the sentence being deferred till next morning, I was sent to prison again.
Upon my complaining of the badness of my prison, some of the justices,
with Colonel Kirby, went up to see it; but when they came, they durst hardly go in,
the floor was so bad and dangerous, and the place so open to wind and rain.
Some that came up said, "`sure it was a jakeshouse.`"
When Colonel Kirby saw it, and heard what others said of it,
he excused the matter as well as he could, saying,
"`I should be removed ere long to some more convenient place.`"

Next day, towards eleven, we were called again to hear the sentence;
and Margaret Fell being called first to the bar, had counsel to plead,
who found many errors in her indictment; whereupon,
after the judge had acknowledged them, she was set by.
Then the judge asked, "`what they could say to mine?`"
I was not willing to let any man plead for me, but to speak to it myself; and indeed,
though Margaret had some that pleaded for her,
yet she spoke as much herself as she would.
But before I came to the bar, I was moved in my spirit to pray,
that God would confound their wickedness and envy, set his truth over all,
and exalt his Seed.
The Lord heard and answered, and confounded them in their proceedings against me;
and though they had most envy against me,
yet the most gross errors were found in my indictment.

Now, I having put by others from pleading for me, the judge asked me,
"`what I had to say, why he should not pass sentence upon me?`"
I told him, "`I was no lawyer, but I had much to say, if he would have patience to hear.`"
At that he laughed, and others laughed also, and said, "`Come, what have you to say?
he can say nothing.`"
"`Yes,`" said I, "`I have much to say, have but the patience to hear me.`"
Then I asked him, "`whether the oath was to be tendered to the king`'s subjects,
or to the subjects of foreign princes?`"
He said, "`to the subjects of this realm.`"
"`Then,`" said I, "`look at the indictment,
and ye may see that ye have left out the word, subject;
so not having named me in the indictment as a subject,
ye cannot premunire me for not taking the oath.`"
Then they looked over the statute and the indictment, and saw that it was as I said;
and the judge confessed it was an error.
I told him,
"`I had something else to stop his judgment;`" and I desired him to look what day
the indictment said the oath was tendered to me at the sessions there.
They looked, and said, "`it was the eleventh day of January.`"
"`What day of the week were the sessions held on?`"
said I. "`On a Tuesday,`" said they.
"`Then,`" said I, "`look at your almanacs,
and see whether there were any sessions held at Lancaster on the eleventh day of January,
so called?`"
So they looked, and found that the eleventh day was the day called Monday,
and that the sessions were on the day called Tuesday,
which was the twelfth day of that month.
"`Look now,`" said I,
"`ye have indicted me for refusing the oath in the quarter
sessions held at Lancaster on the eleventh day of January last,
and the justices have sworn that they tendered
me the oath in open sessions here that day,
and the jury upon their oaths have found me guilty thereupon;
and yet ye see there were no sessions held in Lancaster that day.`"
Then the judge, to cover the matter, asked,
"`whether the sessions did not begin on the eleventh?`"
But some in the court answered, "`no; the sessions held but one day,
and that was the twelfth.`"
Then the judge said, "`this was a great mistake, and an error.`"
Some of the justices were in a great rage at this, and were ready to quit the bench;
they stamped and said,
"`who hath done this? somebody hath done it on purpose;`"
and a great heat was amongst them.
"`Then,`" said I, "`are not the justices here, that have sworn to this indictment,
forsworn men in the face of the country?
But this is not all,`" said I,
"`I have more yet to offer why sentence should not be given against me.`"
Then I asked, "`in what year of the king the last assize here was holden,
which was in the month called March last?`"
The judge said, "`it was in the sixteenth year of the king.`"
"`But,`" said I, "`the indictment says it was in the fifteenth year.`"
They looked, and found it so.
This also was acknowledged to be another error.
Then they were all in a fret again, and could not tell what to say;
for the judge had sworn the officers of the court,
that the oath was tendered to me at the assize mentioned in the indictment.
"`Now,`" said I, "`is not the court here forsworn also,
who have sworn that the oath was tendered to me at the
assize holden here in the fifteenth year of the king,
when it was in his sixteenth year, and so they have sworn a year false?`"
The judge bid them look whether Margaret Fell`'s indictment was so or not.
They looked, and found it was not so.
I told the judge, "`I had more yet to offer to stop sentence;`" and asked him,
"`whether all the oath ought to be put into the indictment or not?`"
"`Yes,`" said he, "`it ought to be all put in.`"
"`Then,`" said I, "`compare the indictment with the oath,
and there thou mayest see these words, viz. +++[+++or by any authority derived,
or pretended to be derived from him, or his see]
left out of the indictment, which is a principal part of the oath,
and in another place the words +++[+++heirs and successors]
are left out.`"
The judge acknowledged these also to be great errors.
"`But,`" said I, "`I have something further to allege.`"
"`Nay,`" said the judge, "`I have enough, you need say no more.`"
"`If,`" said I, "`thou hast enough, I desire nothing but law and justice at thy hands,
for I don`'t look for mercy.`"
"`You must have justice,`" said he, "`and you shall have law.`"
Then I asked,
"`Am I at liberty and free from all that hath ever been done against me in this matter?`"
"`Yes,`" said the judge, "`you are free from all that hath been done against you.
But then,`" starting up in a rage, he said, "`I can put the oath to any man here,
and I will tender you the oath again.`"
I told him, "`he had examples enough yesterday of swearing and false-swearing,
both in the justices and the jury; for I saw before mine eyes,
that both justices and jury had forsworn themselves.`"
The judge asked me, "`if I would take the oath?`"
"`I bid him do me justice for my false imprisonment all this while;
for what had I been imprisoned so long for?
and I told him I ought to be set at liberty.`"
"`You are at liberty,`" said he, "`but I will put the oath to you again.`"
Then I turned me about and said, "`All people, take notice, this is a snare,
for I ought to be set free from the jailer and from this court.`"
But the judge cried, "`Give him the book;`" and the sheriff and the justices cried,
"`Give him the book.`"
Then the power of darkness rose up in them, like a mountain,
and a clerk lifted up a book to me.
I stood still and said, "`if it be a Bible, give it me into my hand.`"
"`Yes, yes,`" said the judge and justices, "`give it him into his hand.`"
So I took it and looked into it, and said, "`I see it is a Bible, I am glad of it.`"
Now he had caused the jury to be called, and they stood by;
for after they had brought in their former verdict, he would not dismiss them,
though they desired it; but told them, "`he could not dismiss them yet,
for he should have business for them,
and therefore they must attend and be ready when they were called.`"
When he said so, I felt his intent, that if I was freed, he would come on again.
So I looked him in the face, and the witness of God started up in him,
and made him blush when he looked at me again, for he saw that I saw him.
Nevertheless, hardening himself, he caused the oath to be read to me,
the jury standing by; and when it was read, he asked me,
"`whether I would take the oath or not?`"
Then said I, "`ye have given me a book here to kiss and to swear on,
and this book which ye have given me to kiss, says,
'`Kiss the Son;`' and the Son says in this book,
'`Swear not at all;`' and so says also the apostle James.
Now, I say as the book says, and yet ye imprison me;
how chance ye do not imprison the book for saying so?
How comes it that the book is at liberty amongst you, which bids me not swear,
and yet ye imprison me for doing as the book bids me?
Why don`'t ye imprison the book?`"
As I was speaking this to them, and held up the Bible open in my hand,
to show them the place in the book, where Christ forbids swearing,
they plucked the book out of my hand again; and the judge said,
"`Nay, but we will imprison George Fox.`"
Yet this got abroad over all the country as a by-word,
"`that they gave me a book to swear on,
that commanded me '`not to swear at all and that the Bible was at liberty,
and I in prison for doing as the Bible said.`"
Now when the judge still urged me to swear, I told him, "`I never took oath, covenant,
or engagement in my life,
but my yea or nay was more binding to me than an oath was to many others;
for had they not had experience how little men regarded an oath;
and how they had sworn one way and then another;
and how the justices and court had forsworn themselves now?`"
I told him, "`I was a man of a tender conscience,
and if they had any sense of a tender conscience, they would consider,
that it was in obedience to Christ`'s command that I could not swear.
But,`" said I, "`if any of you can convince me,
that after Christ and the apostle had commanded not to swear,
they altered that command and commanded Christians to swear;
then ye shall see I will swear.`"
There being many priests by, I said,
"`if ye cannot do it, let your priests stand up and do it.`"
But not one of the priests made any answer.
"`O,`" said the judge, "`all the world cannot convince you.`"
"`No,`" said I, "`how is it like the world should convince me;
for '`the whole world lies in wickedness;`' but bring out your spiritual men,
as ye call them, to convince me.`"
Then both the sheriff and the judge said, "`the angel swore in the Revelations.`"
I replied, "`when God bringeth in his first-begotten Son into the world, he saith,
'`Let all the angels of God worship Him;`' and He saith,`'
swear not at all.`'`" "`Nay,`" said the judge,
"`I will not dispute.`"
Then I spoke to the jury, telling them,
"`it was for Christ`'s sake that I could not swear,
and therefore I warned them not to act contrary to that of God in their consciences,
for before his judgment seat they must all be brought.`"
And I told them, "`that as for plots and persecution for religion and Popery,
I do deny them in my heart; for I am a Christian,
and shall show forth Christianity amongst you this day.
It is for Christ`'s doctrine I stand.`"
More words I had both with the judge and jury before the jailer took me away.

In the afternoon I was brought up again, and put among the thieves some time,
where I stood with my hat on till the jailer took it off.
Then the jury having found this new indictment against
me "`for not taking the oath,`" I was called to the bar;
and the judge asked me, "`what I would say for myself:`" I bid them read the indictment,
for I would not answer to that which I did not hear.
The clerk read it, and as he read the judge said,
"`take heed it be not false again;`" but he read it in such a
manner that I could hardly understand what he read.
When he had done, the judge asked me, "`what I said to the indictment?`"
I told him, "`at once hearing so large a writing read,
and at such a distance that I could not distinctly hear all the parts of it,
I could not well tell what to say to it; but if he would let me have a copy,
and give me time to consider it, I would answer it.`"
This put them to a little stand;
but after a while the judge asked me "`what time I would have?`"
I said, "`till the next assize.`"
"`But,`" said he,
"`what plea will you now make? are you guilty or not guilty?`"
I said, "`I am not guilty at all of denying swearing obstinately and wilfully;
and as for those things mentioned in the oath, as jesuitical plots and foreign powers,
I utterly deny them in my heart; and if I could take any oath, I should take that;
but I never took any oath in my life.`"
The judge said, "`I said well; but,`" said he, "`the king is sworn,
the parliament is sworn, I am sworn, the justices are sworn,
and the law is preserved by oaths.`"
I told him, "`they had had sufficient experience of men`'s swearing,
and he had seen how the justices and jury had sworn wrong the other day;
and if he had read in the _Book of Martyrs_ how many of the martyrs had refused to swear,
both within the time of the ten persecutions and in Bishop Bonner`'s days, he might see,
that to deny swearing in obedience to Christ`'s command was no new thing.`"
He said, "`he wished the laws were otherwise.`"
I said, "`Our Yea is yea, and our Nay is nay; and if we transgress our yea and our nay,
let us suffer as they do, or should do, that swear falsely.`"
This, I told him, we had offered to the king; and the king said, "`it was reasonable.`"

After some further discourse, they committed me to prison again,
there to lie till the next assize; and Colonel Kirby gave order to the jailer,
"`to keep me close, and suffer no flesh alive to come at me,
for I was not fit,`" he said, "`to be discoursed with by men.`"
Then I was put into a tower, where the smoke of the other prisoners came up so thick,
that it stood as dew upon the walls,
and sometimes it was so thick that I could hardly see the candle when it burned;
and I being locked under three locks, the under-jailer, when the smoke was great,
would hardly be persuaded to come up to unlock one of the uppermost doors,
for fear of the smoke, so that I was almost smothered.
Besides, it rained in upon my bed, and many times,
when I went to stop out the rain in the cold winter season,
my shirt was wet through with the rain that came in upon me,
while I was labouring to stop it out.
And the place being high and open to the wind, sometimes as fast as I stopped it,
the wind blew it out again.
In this manner did I lie, all that long cold winter, till the next assize;
in which time I was so starved with cold and rain, that my body was greatly swelled,
and my limbs much benumbed.

The assize began on the 16th day of the month called March, 1664-5; The same Judges,
Twisden and Turner, coming that circuit again,
Judge Twisden sat this time on the crown-bench, and before him I was brought.
I had informed myself of the errors in this indictment also.
For though at the assize before, Judge Turner had said to the officers in court,
"`Pray see that all the oath be in the indictment, and that the word, subject, be in,
and that the day of the month and the year of the king be put in right;
for it is a shame that so many errors should be seen and found
in the face of the country;`" yet there were many errors,
and those great ones, in this indictment, as well as in the former.
Surely the hand of the Lord was in it, to confound their mischievous work against me,
and to blind them therein; insomuch,
that although after the indictment was drawn at the former assize,
the judge examined it himself and tried it with the clerks, yet the word, subject,
was left out of this indictment also, the day of the month was put in wrong,
and several material words of the oath were left out;
yet they went on confidently against me, thinking all was safe and well.
When I was set to the bar, and the jury called over to be sworn, the clerk asked me,
first, "`whether I had any objection to make against any of the jury?`"
I told him, "`I knew none of them.`"
Then, having sworn the jury,
they swore three of the officers of the court to prove
"`that the oath was tendered to me at the last assizes,
according to the indictment.`"
"`Come, come,`" said the judge, "`it was not done in a corner.`"
Then he asked me, "`what I had said to it,
or whether I had taken the oath at the last assize?`"
I told him, what I had said, viz., "`that the book they gave me to swear on, says,
'`swear not at all;`'`" and I repeated more of what I had formerly said to them,
as it now came to my remembrance.
Whereupon the judge said, "`I will not dispute with you, but in point of law.`"
"`Then,`" said I, "`I have something to speak to the jury concerning the indictment.`"
He told me, I must not speak to the jury, but if I had anything to say,
I must speak to him.
Then I asked him, "`whether the oath was to be tendered to the king`'s subjects only,
or to the subjects of foreign princes?`"
He replied, "`to the subjects of this realm; for I will speak nothing to you,`" said he,
"`but in point of law.`"
"`Then,`" said I, "`look in the indictment, and thou mayest see that the word, subject,
is left out of this indictment also.
And therefore seeing the oath is not to be
tendered to any but the subjects of this realm,
and ye have not put me in as a subject,
the court is to take no notice of this indictment.`"
I had no sooner spoken than the judge cried, "`Take him away, jailer, take him away.`"
So I was presently hurried away.
The jailer and people looked when I should be called for again;
but I was never brought to the court any more,
though I had many other great errors to assign in the indictment.
After I was gone, the judge asked the jury, "`if they were agreed?`"
They said, "`yes,`" and found for the king against me, as I was told.
But I was never called to hear sentence given, nor was any given against me,
that I could hear of.
I understood that when they had looked more narrowly into the indictment,
they saw it was not good; and the judge having sworn the officers of the court,
that the oath was tendered me at the assize before, such a day,
according as was set in the indictment, and that being the wrong day,
I should have proved the officers of the court forsworn men again,
if the judge would have suffered me to plead to the indictment;
which was thought to be the reason why he hurried me away so soon.
The judge had passed sentence of premunire upon Margaret Fell, before I was brought in;
and it seems, when I was hurried away, they recorded me as a premunired person,
though I was never brought to hear the sentence, or knew of it; which was very illegal.
For they ought not only to have had me present to hear the sentence given,
but also to have asked me first,
"`what I could say why sentence should not be given against me?`"
But they knew I had so much to say, that they could not give sentence, if they heard it.

While I was prisoner in Lancaster castle,
there was a great noise and talk of the Turks overspreading Christendom,
and great fears entered many.
But one day, as I was walking in my prison chamber,
"`I saw the Lord`'s power turn against him, and that he was turning back again.`"
And I declared to some what the Lord had let me see,
when there were such fears of his over-running Christendom;
and within a month after the news came, that they had given him a defeat.

Another time, as I was walking in my chamber, with my eye to the Lord,
"`I saw the angel of the Lord with a glittering drawn sword stretched southward,
as though the court had been all on fire.`"
Not long after the wars broke out with Holland, the sickness broke forth,
and afterwards the fire of London; so the Lord`'s sword was drawn indeed.

By reason of my long and close imprisonment in so bad a place,
I was become very weak in body; but the Lord`'s power was over all,
supported me through all, and enabled me to do service for him,
and for his truth and people, as the place would admit.
For while I was in Lancaster prison, I answered several books, as the _Mass,_
the _Common-Prayer,_ the _Directory,_ and the _Church-Faith;_
which are the four chief religions that are got up since the apostles`' days.
And there being several Friends in prison at Lancaster
and other prisons for not paying tithes,
I was moved to give forth the following lines concerning tithes:--

[.small-break]
'''

"`In the time of the law, they that did not bring their tithes into the store-house,
robbed God; then there was not meat in their house;
therefore the Lord commanded '`to bring them into his house,
that there might be meat in the store-house, which was to fill the fatherless, stranger,
and widow.`'
But these priests, who are counterfeits, who take people`'s tithes now by a law,
are from the beast; and if any will not pay them, they imprison them,
or make them pay treble.
These rob the poor, rob the fatherless; and the stranger and the widow are not filled;
so their cry is gone up to heaven against these.
Many are made almost beggars by these oppressing priests,
their cattle and corn being taken away, and they cast into prison.
Others are sued at law by them, and have treble damage taken from them;
yet such priests are cried up to be ministers of the gospel.
Though when the unchangeable priest was come, the priesthood that was changeable,
was denied, as we now deny these.
But if any be moved now to cry against them, they are stocked, beat, or imprisoned.
Many are now in prison at Lancaster, and in other places, by a national law;
the like whereof was never done by the law of God, which was delivered to Moses.
For we do not read, that under Moses`'s law any suffered imprisonment,
or spoiling of their goods for not paying tithes, or had to pay treble damage.
Surely, surely, the cry for vengeance will be heard,
which arises from the oppressed souls that lie under the altar.
There are many prisoners at Kendal, because they cannot pay tithes, as Captain Ward,
Thomas Robertson,^
footnote:[Of Thomas Robertson not much is known,
but he appears to have been a faithful labourer in his day.
Ambrose Rigge, in the _Account of his Life,_ states,
"`A fellow labourer was prepared for me, which was Thomas Robertson of Westmorland;
who was made willing to leave his dear wife and tender babes,
to go with me into the lord`'s harvest.`"
In _Letters, etc., of Early Friends,_ p. 226,
is a letter from Thomas Robertson to Margaret Fell, under date 1655.]
and the widow Garland, who has many small children;
these suffer because they cannot pay tithes.
Others are in Kendal prison, who were moved of the Lord to speak to the priests,
one to go in sackcloth, and with ashes upon her head.
Others have been moved to go in sackcloth,
as a lamentation for the miserable estate of this nation,
seeing so much crying up of the preaching of the gospel, and yet so much strife, debate,
and oaths, and dissension among people.
But where the gospel is received indeed, strife and contention are ended,
and oppression is taken off.
O! the land mourns, because of the oppression of those called ministers!
And though the cry of the oppressed hath not entered into the ears of the magistrates;
yet is the cry of the poor, oppressed people of God,
entered into the ears of the Lord of Sabaoth,
who now will be avenged of all his adversaries.
You unjust lawgivers, and unjust judges, to that in all your consciences I speak,
to be cleared, when ye are judged by the just Judge of heaven and earth;
whose terror is gone forth against all the ungodly,
and all the oppressors of God`'s people whatsoever, whether ye will hear or forbear.`"

[.signed-section-signature]
G+++.+++ F.

After the assize,
Colonel Kirby and some other justices were very uneasy with my being at Lancaster;
for I had galled them sore at my trials there,
and they laboured much to get me removed to some remote place.
Colonel Kirby threatened I should be sent far enough, and sometimes said,
I should be sent beyond sea.
About six weeks after the assizes,
they got an order from the king and council to remove me from Lancaster;
and with it they brought a letter from the Earl of Anglesea, wherein was written,
"`that if those things were found true against me, which I was charged withal,
I deserved no clemency or mercy;`" yet the greatest matter they had against me was,
because I could not disobey the command of Christ, and swear.

When they had prepared for my removal, the under-sheriff and the head-sheriffs man,
with some bailiffs, came and fetched me out of the castle,
when I was so weak with lying in that cold, wet, and smoky prison,
that I could hardly go or stand.
They had me into the jailer`'s house, where were William Kirby, a justice,
and several others, and they called for wine to give me.
I told them, "`I would have none of their wine.`"
Then they cried, "`Bring out the horses.`"
I desired them first to show me their order, or a copy of it,
if they intended to remove me; but they would show me none but their swords.
I told them, "`there was no sentence passed upon me, nor was I premunired,
that I knew of; and therefore I was not made the king`'s prisoner, but was the sheriff`'s;
for they and all the country knew, that I was not fully heard at the last assize,
nor suffered to show the errors that were in the indictment,
which were sufficient to quash it, though they had kept me from one assize to another,
to the end they might try me.
But they all knew, there was no sentence of premunire passed upon me;
and therefore not being the king`'s prisoner but the sheriff`'s,
I desired to see their order.`"
Instead of showing me their order, they haled me out,
and lifted me upon one of the sheriff`'s horses.
When I was on horseback in the street, the town`'s-people being gathered to gaze upon me,
I told the officers, I had received neither Christianity, civility, nor humanity,
from them.
They hurried me away about fourteen miles to Bentham, though I was so very weak,
I was hardly able to sit on horseback; and my clothes smelt so of smoke,
that they were loathsome to myself.
The wicked jailer, one Hunter, a young fellow, would come behind,
and give the horse a lash with his whip, and make him skip and leap; so that I,
being weak, had difficulty to sit him; and then he would come and look me in the face,
and say, "`How do you, Mr. Fox?`"
I told him, "`it was not civil in him to do so.`"
The Lord cut him off soon after.

When we were come to Bentham, there met us many troopers, and a marshal;
and many of the gentry of the country were come in,
and abundance of people to stare at me.
I being very weak and weary, desired them to let me lie down on a bed,
which the soldiers permitted me; for they that brought me thither,
gave their order to the marshal, and he set a guard of his soldiers upon me.
When they had stayed a while, they pressed horses, and raised the bailiff of the hundred,
and the constables, and others, and had me to Giggleswick that night;
but exceedingly weak I was.
There they raised the constables with their clog-shoes,
who sat drinking all the night in the room by me, so that I could not get much rest.
Next day we came to a market-town, where several Friends called to see me;
and Robert Widders and divers Friends came to me on the road.
The next night I asked the soldiers, "`whither they intended to carry me,
and whither I was to be sent?`"
Some of them said, "`beyond sea;`" others said, "`to Tynemouth Castle.`"
A great fear there was amongst them, lest some one should rescue me out of their hands;
but that fear was needless.
Next night we came to York, where the marshal put me into a great chamber,
where most part of two troops came to see me.
One of these troopers, an envious man, hearing that I was premunired, asked me,
"`what estate I had, and whether it was copyhold or free land?`"
I took no notice of his question,
but was moved to declare the word of life to the soldiers,
and many of them were very loving.
At night the Lord Frecheville (so called), who commanded these horse, came to me,
and was very civil and loving.
I gave him an account of my imprisonment,
and declared many things to him relating to truth.
They kept me at York two days,
and then the marshal and four or five soldiers were sent to convey me to Scarbro`' Castle.
Indeed these were very civil men, and carried themselves civilly and lovingly to me.
On the way we baited at Malton, and they permitted Friends to come and visit me.
When we were come to Scarbro'`, they had me to an inn, and gave notice to the governor,
who sent six soldiers to be my guard that night.
Next day they conducted me into the castle, put me into a room, and set a sentry on me.
Being very weak and subject to fainting,
they let me go out sometimes into the air with the sentry.
They soon removed me out of this room, and put me into an open one,
where the rain came in; and smoked exceedingly, which was very offensive to me.
One day the governor, Sir John Crossland, came to see me,
and brought with him Sir Francis Cobb.
I desired the governor to go into my room, and see what a place I had.
I had got a little fire made in it, and it was so filled with smoke,
that when they were in, they could hardly find their way out again;
and he being a Papist, I told him, that was his Purgatory which they had put me into.
I was forced to lay out about fifty shillings to stop out the rain,
and keep the room from smoking so much.
When I had been at that charge, and made it somewhat tolerable,
they removed me into a worse room, where I had neither chimney nor firehearth.
This being to the sea-side and lying much open, the wind drove in the rain forcibly,
so that the water came over my bed, and ran about the room,
that I was fain to skim it up with a platter.
And when my clothes were wet, I had no fire to dry them;
so that my body was benumbed with cold, and my fingers swelled,
that one was grown as big as two.
Though I was at some charge in this room also, I could not keep out the wind and rain.
Besides they would suffer few Friends to come to me, and many times not any, no,
not so much as to bring me a little food;
but I was forced for the first quarter to hire
one of another society to bring me necessaries.
Sometimes the soldiers would take it from her, and she would scuffle with them for it.
Afterwards I hired a soldier to fetch me water and bread,
and something to make a fire of, when I was in a room where a fire could be made.
Commonly a threepenny loaf served me three weeks, and sometimes longer,
and most of my drink was water with wormwood steeped or bruised in it.
One time when the weather was very sharp, and I had taken great cold,
I got a little elecampane beer, and I heard one of the soldiers say to the other,
that they would play me a trick, for they would send for me up to the deputy-governor,
and in the meantime drink my strong beer out; and so they did.
When I came back, one of the soldiers came to me in a jeer,
and asked-me for some strong beer.
I told him they had played their pretty trick; and so I took no further notice of it.
But inasmuch as they kept me so very strait,
not giving liberty for Friends to come to me,
I spoke to the keepers of the castle to this effect:
"`I did not know till I was removed from Lancaster castle,
and brought prisoner to this castle of Scarbro'`, that I was convicted of a premunire;
for the judge did not give sentence upon me at the assizes in open court.
But seeing I am now a prisoner here, if I may not have my liberty,
let my friends and acquaintance have their liberty to come and visit me,
as Paul`'s friends had among the Romans, who were not Christians but Heathens.
For Paul`'s friends had their liberty; all that would, might come to him,
and he had his liberty to preach to them in his hired house;
but I cannot have liberty to go into the town, nor for my friends to come to me here.
So you that go under the name of Christians,
are worse in this respect than those Heathens were.`"

But though they would not let Friends come to me, they would often bring others,
either to gaze upon me, or to contend with me.
One time a great company of Papists came to discourse with me; they affirmed,
"`the Pope was infallible, and had stood infallible ever since Peter`'s time.`"
But I showed them the contrary by history; for one of the bishops of Rome,
(Marcellinus by name), denied the faith and sacrificed to idols;
therefore he was not infallible.
I told them, If they were in the infallible spirit, they need not have jails, swords,
and staves, racks and tortures, fires and faggots, whips and gallows,
to hold up their religion, and to destroy men`'s lives about it;
for if they were in the infallible spirit they would preserve men`'s lives,
and use none but spiritual weapons about religion.
I told them also what one that had been of their society told me.
A woman who lived in Kent, had not only been a Papist herself,
but had brought over several to that religion; but coming to be convinced of God`'s truth,
and turned by it to Christ her Saviour, she exhorted the Papists to the same.
One of them, a tailor, being at work at her house,
while she opened to him the falseness of the Popish religion,
and endeavoured to draw him from it to the truth, drew his knife,
and got between her and the door; but she spoke boldly to him,
and bid him put up his knife, for she knew his principle.
I asked the woman, "`what she thought he would have done with his knife?`"
She said, "`he would have stabbed her.`"
"`Stabbed thee,`" said I, "`what would he have stabbed thee for?
thy religion?`"
"`Yes,`" said she, "`it is the principle of the Papists, if any turn from their religion,
to kill them if they can.`"
This story I told those Papists,
and that I had it from a person that had been one of them,
but had forsaken their principles and discovered their practices.
They did not deny this to be their principle; but said,
"`What! would I declare this abroad?`"
I told them, "`yes, such things ought to be declared abroad;
that it might be known how contrary their religion was to true Christianity.`"
Whereupon they went away in a great rage.

Another Papist came to discourse with me, who said all the patriarchs were in hell,
from the creation till Christ came, and that when Christ suffered he went into hell,
and the Devil said to him, "`What comest thou hither for,
to break open our strongholds?`"
And Christ said, "`to fetch them all out.`"
So he said, "`Christ was three nights and three days in hell, to bring them out.`"
I told him that was false, for Christ said to the thief,
"`This day thou shalt be with me in paradise.`"
And Enoch and Elijah were translated into heaven.
And Abraham was in heaven, for the Scripture saith, Lazarus was in his bosom;
and Moses and Elias were with Christ upon the Mount before he suffered.
These instances stopped the Papist`'s mouth, and put him to a stand.

Another time came Dr. Witty, who was esteemed a great doctor of physic,
with Lord Falconbridge; with these came also the governor of Tynemouth castle,
and several knights.
Being called to them, Witty undertook to discourse with me, and asked me,
"`what I was in prison for?`"
I told him, "`because I would not disobey the command of Christ, and swear.`"
He said, "`I ought to swear my allegiance to the king.`"
He being a great Presbyterian, I asked him, "`whether he had not sworn against the King,
and House of Lords, and taken the Scotch covenant?
and had he not since sworn to the king?
and what then was his swearing good for?
But my allegiance,`" I told him, "`did not consist in swearing,
but in truth and faithfulness.`"
After some further discourse, I was sent away to my prison again.
And afterwards this Dr. Witty boasted in the town amongst his patients,
that he had conquered me.
When I heard of his boasting, I told the governor,
"`it was a small boast in him to say he had conquered a bondman.`"
I desired to bid him visit me again, when he came to the castle.
He came again a while after, with sixteen or seventeen great persons;
and ran himself worse on ground than before.
For he affirmed before them all,
"`that Christ hath not enlightened every man that cometh into the world;
and that the grace of God, that bringeth salvation, hath not appeared unto all men;
and that Christ died not for all men.`"
I asked him, "`what sort of men those were whom Christ had not enlightened?
and to whom his grace had not appeared?
and for whom he had not died?`"
He said, "`Christ did not die for adulterers, and idolaters, and wicked men.`"
I asked him, "`whether adulterers and wicked men were not sinners?`"
He said, "`Yes.`"
"`And did not Christ die for sinners?`"
said I. "`Did he not come to call sinners to repentance?`"
"`Yes,`" said he.
"`Then,`" said I, "`thou hast stopped thy own mouth.`"
So I proved that the grace of God hath appeared unto all men,
though some turn it into wantonness, and walk despitefully against it;
and that Christ hath enlightened all men, though some hate the light.
Several of the people that were present, confessed it was true;
but he went away in a great rage, and came no more to me.

Another time the governor brought a priest, but his mouth was soon stopped.
Not long after he brought two or three parliament-men, who asked me,
"`whether I owned ministers and bishops?`"
I told them, "`yes, such as Christ sent, such as had freely received,
and would freely give, such as were qualified,
and were in the same power and Spirit that the apostles were in.
But such bishops and teachers as theirs were,
that would go no farther than a great benefice, I did not own;
for they were not like the apostles.
Christ saith to his ministers, '`Go ye into all nations,
and preach the gospel;`' but ye parliament-men,
who keep your priests and bishops in such great fat benefices, have spoiled them all.
For do ye think they will go into all nations to preach;
or any farther than a great fat benefice?
Judge yourselves whether they will or not.`"

There came another time the widow of old Lord Fairfax, and with her a great company;
one of whom was a priest.
I was moved to declare the truth to them, and the priest asked me, "`why we said,
Thou and Thee to people?
for he counted us but fools and idiots for speaking so.`"
I asked him, "`whether they that translated the Scriptures,
and that made the grammar and accidence, were fools and idiots,
seeing they translated the Scriptures so, and made the grammar so, Thou to one,
and You to more than one, and left it so to us.
If they were fools and idiots, why had not he, and such as he,
that looked upon themselves as wise men,
and that could not bear Thou and Thee to a singular, altered the grammar, accidence,
and Bible, and put the plural instead of the singular.
But if they were wise men that had so translated the Bible,
and had made the grammar and accidence so,
I wished him to consider whether they were not fools and idiots themselves,
that did not speak as their grammars and Bibles taught them; but were offended with us,
and called us fools and idiots for speaking so?`"
Thus the priest`'s mouth was stopped, and many of the company acknowledged the truth,
and were pretty loving and tender.
Some of them would have given me money, but I would not receive it.

After this came Dr. Cradock, with three priests more,
and the governor and his lady (so called), and another that was called a lady,
and a great company with them.
Dr. Cradock asked me, "`what I was in prison for?`"
I told him, "`for obeying the command of Christ and the apostle, in not swearing.
But if he, being both a doctor and a justice of peace, could convince me,
that after Christ and the apostle had forbidden swearing,
they commanded Christians to swear, then I would swear.
Here was the Bible,`" I told him, "`he might, if he could, show me any such command.`"
He said, "`it is written, '`Ye shall swear in truth and righteousness.`'`" "`Ay,`" said I,
"`it was written so in Jeremiah`'s time;
but that was many ages before Christ commanded '`
not to swear at all;`' but where is it written so,
since Christ forbade all swearing?
I could bring as many instances out of the Old Testament for swearing as thou,
and it may be more;
but of what force are they to prove swearing lawful in the New Testament,
since Christ and the apostle forbade it?
Besides,`" said I, "`in that text where it is written, ye shall swear, what ye was this?
Was it ye Gentiles, or ye Jews?`"
To this he would not answer.
But one of the priests that were with him answered,
"`it was to the Jews that this was spoken.`"
Then Dr. Cradock confessed, it was so.
"`Very well,`" said I, "`but where did God ever give a command to the Gentiles to swear?
For thou knowest that we are Gentiles by nature.`"
"`Indeed,`" said he,
"`in the gospel-times everything was to be established out of the mouths of
two or three witnesses j but there was to be no swearing then.`"
"`Why then,`" said I, "`dost thou force oaths upon Christians,
contrary to thy own knowledge, in the gospel-times.
And why dost thou excommunicate my friends?`"
(for he had excommunicated abundance, both in Yorkshire and Lancashire). He said,
"`for not coming to church.`"
"`Why,`" said I, "`ye left us above twenty years ago,
when we were but young lads and lasses, to the Presbyterians, Independents, and Baptists,
many of whom made spoil of our goods, and persecuted us,
because we would not follow them.
Now we being but young, knew little then of your principles;
and if ye had intended to keep the old men that did know them, to you,
and your principles alive, that we might have known them,
ye should either not have fled from us as ye did,
or ye should have sent us your epistles, collects, homilies, and evening-songs;
for Paul wrote epistles to the saints, though he was in prison.
But they and we might have turned Turks or Jews for any collects, homilies, or epistles,
we had from you all this while.
And now thou hast excommunicated us, both young and old, and so have others of you done:
that is, ye have put us out of your church before ye have got us into it,
and before ye have brought us to know your principles.
Is not this madness in you, to put us out before we were brought in?
Indeed, if ye had brought us into your church, and when we had been in,
if we had done some bad thing,
that had been something like a ground for excommunication or putting out again.
But,`" said I, "`what dost thou call the church?`"
"`Why,`" said he, "`that which you call the steeple-house.`"
Then I asked him, "`whether Christ shed his blood for the steeple-house;
and purchased and sanctified the steeple-house with his blood?
And seeing the church is Christ`'s bride and wife, and that he is the head of the church,
dost thou think the steeple-house is Christ`'s wife and bride,
and that he is the head of that old house, or of his people?`"
"`No,`" said he, "`Christ is the head of the people, and they are the church.`"
"`Then,`" said I, "`but you have given the title, church, which belongs to the people,
to an old house, and you have taught people to believe so.`"
I asked him also, "`why he persecuted Friends for not paying tithes?
And whether God ever gave a command to the Gentiles, that they should pay tithes?
And whether Christ had not ended tithes,
when he ended the Levitical priesthood that took tithes?
And whether Christ, when he sent forth his disciples to preach,
had not commanded them to preach freely, as he had given them freely?
And whether all the ministers of Christ are not bound to observe this command of Christ?`"
He said,
"`he would not dispute that;`" neither did I find he was willing to stay on that subject,
for he presently turned to another matter, and said, "`you marry, but I know not how.`"
I replied, "`It may be so; but why dost thou not come and see?`"
Then he threatened that he would use his power against us, as he had done.
"`I bid him take heed; for he was an old man.`"
I asked him also, "`where he read from Genesis to the Revelations,
that ever any priest did marry any?`"
And I wished him to show me some instance thereof,
if he would have us come to them to be married; "`for,`" said I,
thou hast excommunicated one of my friends two years after he was dead,
about his marriage.
And why dost thou not excommunicate Isaac, and Jacob, and Boaz, and Ruth?
Why dost thou not use thy power against these;
for we do not read that they were ever married by the priests;
but they took one another in the assemblies of the righteous,
in the presence of God and his people; and so do we.
So that we have all the holy men and women,
that the Scripture speaks of in this practice, on our side.`"
Much discourse we had, but when he found he could get no advantage over me,
he went away with his company.

With such people I was much exercised while I was there;
for most that came to the castle would desire to speak with me,
and great disputes I had with them.
But, as to Friends, I was as a man buried alive; for though many came far to see me,
yet few were suffered to come to me;
and when any Friend came into the castle about business,
if he looked towards me they would rage at him.
At last the governor came under some trouble himself;
for he having sent out a privateer to sea,
they took some ships that were not enemies`' ships, but their friends'`;
whereupon he was brought into trouble; after which he grew somewhat more friendly to me.
For before I had a marshal set over me, on purpose to get money out of me;
but I was not free to give him a farthing;
and when they found they could get nothing off me, he was taken away again.
The officers often threatened that I should be hanged over the wall.
Nay, the deputy-governor told me once that the king,
knowing I had great interest in the people, had sent me thither,
that if there should be any stirring in the nation,
they should hang me over the wall to keep the people down.
There being, a while after, a marriage at a Baptist`'s house,
upon which occasion a great many of them were met together,
they talked much then of hanging me.
But I told them, "`if that was what they desired, and it was permitted them, I was ready;
for I never feared death nor sufferings in my life, but I was known to be an innocent,
peaceable man, free from all stirrings and plottings,
and one that sought the good of all men.`"
Afterwards, the governor growing kinder,
I spoke to him when he was going to London to the Parliament,
and desired him to speak to Esquire Marsh, Sir Francis Cobb, and some others;
and let them know how long I had lain in prison, and for what; and he did so.
When he came down again, he told me, that Esquire Marsh^
footnote:[The person whom George Fox here and elsewhere styles Esquire Marsh,
was a gentleman attached to the court of Charles
II. He always remained attached to George Fox,
and ever retained a most friendly interest for the Society in general.
From his station at court and office as a magistrate,
he had frequent opportunities of interposing his authority to protect
the early Friends from the unjust oppression of their persecutors.]
said he would go a hundred miles barefoot for my liberty, he knew me so well;
and several others, he said, spoke well of me.
From which time the governor was very loving to me.

There were, amongst the prisoners, two very bad men,
that often sat drinking with the officers and soldiers;
and because I would not sit and drink with them too, it made them the worse against me.
One time when these two prisoners were drunk,
one of them (whose name was William Wilkinson, a Presbyterian, who had been a captain),
came to me and challenged me to fight with him.
Seeing what condition he was in, I got out of his way; and next morning,
when he was more sober, showed him,
"`how unmanly a thing it was in him to challenge a man to fight, whose principle,
he knew, it was not to strike; but if he was stricken on one ear to turn the other.
I told him, if he had a mind to fight, he should have challenged some of the soldiers,
that could have answered him in his own way.
But however, seeing he had challenged me,
I was now come to answer him with my hands in my pockets;
and (reaching my head towards him) '`here,`' said I, '`here is my hair, here are my cheeks,
here is my back.`'`" With that he skipped away from me, and went into another room;
at which the soldiers fell a laughing; and one of the officers said,
"`you are a happy man, that can bear such things.`"
Thus he was conquered without a blow.
After a while he took the oath, gave bond, and got out of prison;
and not long after the Lord cut him off.

There were great imprisoments in this, and the former year,
while I was prisoner at Lancaster and Scarbro'`.
At London many Friends were crowded into Newgate,
and other prisons, where the sickness was; and many died in prison.^
footnote:[The sickness here alluded to was the "`Plague,`" which visited London in 1665.
The state of the city during this dreadful visitation seems to have been most deplorable.
The following striking description is from _Ellis`'s Original Letters in the British Museum._
The letter is one addressed to Dr. Sancroft from J. Tillison, dated Sept. 14, 1665:--
{footnote-paragraph-split}
The desolation of the city is very great.
That heart is either of steel or stone, that will not lament this sad visitation,
and will not bleed for those unutterable woes!
What eye would not weep to see so many habitations uninhabited--the
poor sick not visited--the hungry not fed--the grave not satisfied!
Death stares us continually in the face in every infected person that passes by us,
in every coffin which is daily and hourly carried along the streets.
The custom was in the beginning to bury the dead in the night only;
but now both night and day will hardly be time enough to do it.
The Quakers (as we are informed) have buried, in their piece of ground,
a thousand for some weeks together past.`"
{footnote-paragraph-split}
George Whitehead relates the satisfaction and
comfort many innocent Friends expressed on their deathbeds,
both in Newgate and other noisome places during the plague.
Death was truly gain to these; "`it being through death,`" says Whitehead,
"`that the Lord had appointed the final deliverance of
many from the cruelties and rod of their oppressors,
and from the miseries and evil to come.`"--"`Whilst the
plague was raging in the city,`" he adds,
"`our persecutors took fifty-five of our Friends (men and women) out of Newgate,
where the distemper also prevailed, and forced them on board a ship for banishment,
which lay for some time in the river.
They were so crowded on board, and the distemper breaking out amongst them,
most of them were infected, and twenty-seven of them soon died.
I visited them, and had a meeting with them on board, and the Lord my God preserved me,
both from the distemper and also from banishment,
wherein I did humbly confess his power and special
providence to his own praise and glory,`"]
Many also were banished, and several sent on shipboard by the king`'s order.
Some masters of ships would not carry them, but set them on shore again;
yet some were sent to Barbadoes, to Jamaica, and to Nevis,
and the Lord blessed them there.
One master of a ship was very wicked and cruel
to Friends that were put on board his vessel;
for he kept them down under decks, though the sickness was amongst them;
so that many died of it.
But the Lord visited him for his wickedness;
for he lost most of his seamen by the plague,
and lay several months crossed with contrary winds,
though other ships went out and made their voyages.

At last he came before Plymouth,
and there the governor and magistrates would not suffer him, or any of his men, to land,
though he wanted many necessaries for his voyage; but Thomas Lower, Arthur Cotton,
John Light, and other Friends,
went to the ship`'s side and carried necessaries
for tho Friends that were prisoners on board.
The master being thus crossed and vexed, cursed them that put upon him this freight,
and said, "`he hoped he should not go far before he was taken.`"
And the vessel was but just out of sight of Plymouth
before she was taken by a Dutch man-of-war,
and carried into Holland.
When they came there, the States sent the banished Friends back to England,
with a passport, and a certificate, "`that they had not made an escape,
but were sent back by them.`"
In time the Lord`'s power wrought over this storm,
and many of our persecutors were confounded and put to shame.^
footnote:[See extraordinary occurrences in an attempt to
banish a number of Friends recorded in a note in
_Letters, etc., of Early Friends,_ p. 142-145.]

After I had lain prisoner above a year in Scarbro`' Castle, I sent a letter to the king,
in which I gave him "`an account of my imprisonment,
and the bad usage I had received in prison; and also that I was informed,
no man could deliver me but he.`"
After this, John Whitehead being at London, and being acquainted with Esquire Marsh,
went to visit him, and spoke to him about me; and he undertook,
if John Whitehead would get the state of my case drawn up,
to deliver it to the master of requests, Sir John Birkenhead,
and endeavour to get a release for me.
So John Whitehead and Ellis Hookes^
footnote:[Ellis Hookes was employed in London as
a recording clerk to the Society of Friends.
It was he who commenced the _Record of Sufferings_
(mentioned to George Fox in a letter bearing date 1660,
inserted in _Letters, etc., of Early Friends,_ p. 80, 87),
which were written out into large folio volumes,
still preserved among the Society`'s records in London.
These are continued down to the present day in forty or more of these large volumes.
The clear and excellent writing of Ellis Hookes extends
over a large portion of the first of these bulky folios.
To the narratives of sufferings and persecutions,
were added accounts of what were regarded as judgments upon persecutors; which were,
doubtless in that day, ordered to be recorded, under a sense of the fear of God,
and in testimony unto his overruling power.
{footnote-paragraph-split}
Ellis Hookes died in 1681.
In the London _Register of Burials,_ he is described "`of Horslydown in Southwark,
scrivenor;`" and "`died the 12th of the 9th month, 1681,
of a consumption (having been clerk to Friends in London about
twenty-four years)--he was buried in Checker Alley.`"]
drew up a relation of my imprisonment and sufferings, and carried it to Marsh;
and he went with it to the master of requests,
who procured an order from the king for my release.
The substance of the order was, "`that the king being certainly informed,
that I was a man principled against plotting and fighting,
and had been ready at all times to discover plots, rather than to make any, etc.,
therefore his royal pleasure was,
that I should be discharged from my imprisonment,`" etc.
As soon as this order was obtained, John Whitehead came to Scarbro`' with it,
and delivered it to the governor; who, upon receipt thereof,
gathered the officers together,
and without requiring bonds or sureties for my peaceable living,
being satisfied that I was a man of a peaceable life, he discharged me freely,
and gave me the following passport:--

[.small-break]
'''

"`Permit the bearer hereof, George Fox, late a prisoner here,
and now discharged by His Majesty`'s order, quietly to pass about his lawful occasions,
without any molestation.
Given under my hand at Scarbro`' Castle, this first day of September, 1666.`"

[.signed-section-signature]
Jordan Croslands,

[.signed-section-context-close]
Governor of Scarbro`' Castle.

After I was released,
I would have made the governor a present for the
civility and kindness he had of late showed me;
but he would not receive anything; saying,
"`whatever good he could do for me and my friends he would do it,
and never do them any hurt.`"
And afterwards,
if at any time the mayor of the town sent to him
for soldiers to break up Friends`' meetings,
if he sent any down he would privately give them a charge "`not to meddle.`"
He continued loving to his dying day.
The officers also and the soldiers were mightily changed,
and became very respectful to me, and when they had occasion to speak of me,
they would say, "`he is as stiff as a tree, and as pure as a bell;
for we could never bow him.`"

The very next day after my release, the fire broke out in London,
and the report of it came quickly down into the country.^
footnote:[The great fire of London occurred towards the latter end of 1666.
The narratives given in the Diaries of Evelyn and Pepys, who were eye-witnesses of it,
are sad indeed.
Evelyn writes--"`Sept. 3. The fire continued all this night (if I may call that night,
which was light as day for ten miles about),
after a dreadful manner--when conspiring with a fierce eastern wind,
in a very dry season.
I went on foot to the Bankside in Southwark,
and saw the whole south part of the city burning from Cheapside to the Thames,
and all along Cornhill, Tower Street, Gracious Street, and so along to Bainard`'s Castle,
and was now taking hold of St. Paul`'s Church.
The conflagration was so universal, and the people so astonished,
that from the beginning (I know not by what despondency
or fate) they hardly stirred to quench it;
so that there was nothing heard or seen but crying out and lamentation,
and running about like distracted creatures.
O! the miserable and calamitous spectacle! such as happily the
world had not seen the like since the foundation of it,
nor to be outdone till the universal conflagration.
All the sky was of a fiery aspect, like the top of a burning oven, the light +++[+++being+++]+++
seen above forty miles round about for many nights.
The poor inhabitants were dispersed about St. George`'s Fields and Moorfields,
as far as Highgate, and several miles in circle--some under tents,
some under miserable huts and hovels, many without a rag or necessary utensils,
bed or board; who, from delicateness, riches,
or easy accommodations in stately and well-furnished houses,
were now reduced to extremest misery and poverty,`" etc., vol.
i. p. 372-374.]
Then I saw the Lord God was true and just in his word,
which he had showed me before in Lancaster jail,
when I saw the angel of the Lord with a glittering sword drawn southward,
as before expressed.
The people of London were forewarned of this fire; yet few laid it to heart,
or believed it; but rather grew more wicked, and higher in pride.
For a Friend was moved to come out of Huntingdonshire a little before the fire,
to scatter his money, and turn his horse loose on the streets,
to untie the knees of his trousers, let his stockings fall down,
and to unbutton his doublet, and tell the people, "`so should they run up and down,
scattering their money and their goods, half undressed, like mad people,
as he was a sign to them;`" and so they did, when the city was burning.
Thus hath the Lord exercised his prophets and servants by his power,
showed them signs of his judgments, and sent them to forewarn the people; but,
instead of repenting, they have beaten and cruelly entreated some,
and some they have imprisoned, both in the former power`'s days and since.
But the Lord is just, and happy are they that obey his word.
Some have been moved to go naked in their streets, in the other power`'s days, and since,
as signs of their nakedness;
and have declared amongst them
"`that God would strip them of their hypocritical professions,
and make them as bare and naked as they were.`"
But instead of considering it, they have many times whipped, or otherwise abused them,
and sometimes imprisoned them.
Others have been moved to go in sackcloth,
and to denounce the woes and vengeance of God
against the pride and haughtiness of the people;
but few regarded it.
And in the other power`'s days, the wicked, envious, and professing priests,
put up several petitions both to Oliver and Richard, called protectors,
and to the parliaments, judges, and justices, against us, full of lies,
vilifying words and slanders; but we got copies of them, and,
through the Lord`'s assistance, answered them all,
and cleared the Lord`'s truth and ourselves of them.
But O! the body of darkness that rose against
the truth in them that made lies their refuge.
But the Lord swept them away; and in and with his power, truth, light, and life,
hedged his lambs about, and preserved them as on eagles`' wings.
Therefore we all had, and have great encouragement to trust the Lord, who,
we saw by his power and Spirit,
overturned and brought to naught all the confederacies and counsels
that were hatched in darkness against his truth and people;
and by the same truth gave his people dominion, that therein they might serve him.

Indeed I could not but take notice,
how the hand of the Lord turned against the persecutors,
who had been the cause of my imprisonment, or had been abusive or cruel to me in it.
The officer that fetched me to Holker-Hall wasted his estate,
and soon after fled into Ireland.
And most of the justices that were upon the
bench at the sessions when I was sent to prison,
died in a while after; as old Thomas Preston, Rawlinson, Porter, and Matthew West,
of Borwick.
And Justice Fleming`'s wife died, and left him thirteen or fourteen motherless children,
who had imprisoned two Friends to death, and thereby made several children fatherless.
Colonel Kirby never prospered after.
The chief constable, Richard Dodgson, died soon after, and Mount, the petty constable,
and the wife of the other petty constable John Ashburnham, who railed at me in her house,
died soon after.
William Knipe, the witness they brought against me, died soon after also.
Hunter, the jailer of Lancaster, who was very wicked to me while I was his prisoner,
was cut off in his young days:
and the under-sheriff that carried me from Lancaster prison towards Scarbro'`,
lived not long after.
And Joblin, the jailer of Durham, who was prisoner with me in Scarbro`' castle,
and had often incensed the governor and soldiers against me, though he got out of prison,
yet the Lord cut him off in his wickedness soon after.
When I came into that country again, most of those that dwelt in Lancashire were dead,
and others ruined in their estates; so that, though I did not seek revenge upon them,
for their actings against me contrary to the law,
yet the Lord had executed his judgments upon many of them.
