== Chapter II.

[.chapter-synopsis]
* 1666-1669.
* George Fox visits a man above one hundred years old, who had been convinced
* refutes a slander that Friends love none but themselves
* has a meeting at Captain Taylor`'s +++[+++at Brighouse], where a neighbouring knight threatens again to imprison him
* comes to London, and finds the city in ruins as he had seen it in a vision some years before
* is moved to recommend the setting up of monthly meetings to take care of God`'s glory, and to admonish and exhort such as walk disorderly
* travels through the nation for this purpose
* meets with opposition in Huntingdonshire and Bedfordshire
* when at Shrewsbury it was rumoured that "`the great Quaker of England was come to town`"
* the hypocrisy of the Presbyterians detected
* they and the Independents persecute when in power, but flinch in time of persecution by other powers
* George Fox recommends certain regulations to be observed relative to Friends`' marriages
* he also recommends the establishment of a school at Waltham for boys, and one at Shacklewell for girls
* the meetings for discipline are the means of a great reformation among the people
* George Fox discovers a cheat, writes a prophetic warning to Friends
* monthly meetings settled throughout the nation
* the order and good results thereof
* George Fox disputes with a Papist
* confers with Esquire Marsh (Justice), and shows him how to distinguish between Friends and other dissenters who refused the oath
* Justice Marsh is afterwards very serviceable to Friends in screening them from suffering, and recommends the king to grant liberty of conscience
* fourteen monthly meetings are settled in Yorkshire
* Isaac Lindley to George Fox
* when at Scarbro`' the governor presses George Fox to accept his hospitality
* large and precious meetings.

Being now freed from my imprisonment in Scarbro`' castle,
I went about three miles to a large general meeting at a Friend`'s house,
that had been a chief constable; and all was quiet and well.
On the fourth day after, I returned to Scarbro'`,
and had a meeting in the town at Peter Hodgson`'s house.
To this came one called a lady, and several other great persons, also a young man,
son to the bailiff of the town, who had been convinced, while I was there in prison.
That lady (so called) came to me, and said, "`I spoke against the ministers.`"
I told her, "`such as the prophets and Christ declared against formerly,
I declared against now.`"

From hence I went to Whitby; and, having visited Friends there, passed to Burlington,
where I had another meeting.
Thence to Oram, where I had another meeting: and thence to Marmaduke Storr`'s,
and had a large meeting at a constable`'s house,
on whom the Lord had wrought a great miracle.

Next day, two Friends being to take each other in marriage,
there was a very great meeting, which I attended.
I was moved to open to the people the state of our marriages,
declaring how the people of God took one another in the assemblies of the elders,
and that it was God who joined man and woman together before the fall.
And though men had taken upon them to join in the fall,
yet in the restoration it was God`'s joining, that was the right and honourable marriage:
but never any priest did marry any, that we read of in the Scriptures,
from Genesis to the Revelations.
Then I showed them the duty of man and wife, how they should serve God,
being heirs of life and grace together.

I passed thence to Grace Barwick`'s, where I had a general meeting, which was very large.
I came next to Richard Shipton`'s, where I had another meeting;
and so to a priest`'s house, whose wife was convinced, and himself grown very loving,
and glad to see me.
This was that priest, who, in the year 1651, threatened, "`if ever he met me again,
he would have my life, or I should have his;`" and said, "`he would lose his head,
if I were not knocked down in a month.`"
But now he was partly convinced, and become very kind.
I went from his house towards the sea, where several Friends came to visit me;
and amongst others, Philip Seafe, who had formerly been a priest, but,
having received the truth, was now become a preacher of Christ freely, and continued so.
Passing on, I called to see an ancient man, who was convinced of truth,
and was above a hundred years old.
Then I came to a Friend`'s house, where I had a great meeting, and quiet.
I had a great meeting near Malton; and another large one near Hull;
from which I went to Howden-dyke.
As we went into the town, the watchmen questioned me and those that were with me;
but not having any warrant to stay us, we passed by them,
who in a rage threatened they would search us out.
I went to the house of one called the Lady Montague, where I lodged that night;
and several friends came to visit me.
Next morning, being up early, I walked into the orchard,
and saw a man about sunrise go into the house in a great cloak.
He stayed not long; but came soon out again, and went away, not seeing me.
I felt something strike at my life; and went into the house,
where I found the maid-servant affrighted and trembling.
She told me, "`that man had a naked rapier under his cloak.`"
By which I perceived he came with an intent to do mischief, but the Lord prevented him.

I then visited Friends till I came to York, where we had a large meeting.
After which I went to visit Justice Robinson, an ancient justice of the peace,
who had been very loving to me and Friends from the beginning.
There was a priest with him, who told me, "`it was said of us,
that we loved none but ourselves.`"
I told him, "`we loved all mankind, as they were God`'s creation,
and as they were children of Adam and Eve by generation;
and we loved the brotherhood in the Holy Ghost.`"
This stopped him.
After some other discourse, we parted friendly, and passed away.

About this time I wrote a book, entitled, _Fear God, and Honour the King;_
in which I showed, "`that none could rightly fear God, and honour the king,
but they that departed from sin and evil.`"
This book affected the soldiers much, and most people.

Having visited Friends at York, we passed to a market town,
where we had a meeting at George Watkinson`'s, formerly a justice.
A glorious, blessed meeting it was, and very large, and the Seed of life was set over all.
We should have been troubled to get into this town, had not Providence made way for us;
for the watchmen stood ready to stop us.
But a man riding just before us, the watchmen questioned him first;
and perceiving he was a justice of peace, they let him pass;
and we riding close after him, by that means escaped.

Prom this place we passed to Thomas Taylor`'s, formerly a captain,
where we had a precious meeting.
Hard by Thomas Taylor`'s lived a knight,
who was much displeased when he heard I was likely to be released out of prison;
and threatened that, "`if the king set me at liberty,
he would send me to prison again the next day.`"
But though I had this meeting so near him,
yet the Lord`'s power stopped him from meddling, and the meeting was quiet.
Colonel Kirby also,
who had been the chief means of my imprisonment at Lancaster and Scarbro`' castles,
when he heard I was set at liberty, got another order for taking me up; and said,
"`he would ride his horse forty miles to take me,
and would give forty pounds to have me taken.`"
A while after I came so near as to have a meeting within two miles of him;
he was then struck with the gout, and kept his bed,
so that it was thought he would have died.

From Thomas Taylor`'s I visited Friends till I came to Synderhillgreen,
where I had a large, and general meeting.
The priest of the place hearing of it, sent the constable to the justices for a warrant,
and they rode their horses so hard, that they almost spoiled them;
but the notice they had being short, and the way long,
the meeting was ended before they came.
I did not hear of them till I was going out of the house, after meeting was over,
and then a Friend came and told me, "`they were searching another house for me,
the one I was then going to.`"
As I went along the fields towards it, I met the constables, wardens,
and the justice`'s clerk.
I passed through them, they looking at me, and went to the house they had been searching.
Thus they lost their design; for the Lord`'s power bound them, and preserved me over them;
and Friends parted, and all escaped them.
The officers went away as they came; for the Lord had frustrated their design;
praised be his name for ever.

After this I went into Derbyshire, where I had a large meeting.
Some Friends were apprehensive of the constables coming;
for they had great persecution in those parts; but our meeting was quiet.
A justice of peace in that county had taken away much of Friends`' goods;
whereupon Ellen Fretwell had made her appeal to the sessions;
and the rest of the justices granted her her goods again,
and spoke to the persecuting justice, that he should not do so any more.
She was moved to speak and warn him; whereupon he bid her,
"`come and sit down on the bench.`"
"`Ay,`" said she, "`if I may persuade you to do justice to the country,
I will sit down with you.`"
"`No,`" said he, "`then you shall not; get out of the court.`"
As she was going out, she was moved of the Lord to turn again, and say,
"`she should be there, when he should not.`"
After the sessions were ended, he went home, and drove away her brother`'s oxen,
for going to meetings.
Then Susan Frith, a Friend of Chesterfield, was moved of the Lord to tell him,
that "`if he continued in persecuting the innocent,
the Lord would execute his plagues upon him.`"
Soon after which he fell distracted, and died.
This relation I had from Ellen Fretwell herself.

I travelled into Nottinghamshire, and had a large meeting at Skegby,;
from thence I went to Mansfield, where also I had a meeting; thence to another town,
where there was a fair, at which I met with many Friends.
"`Then passing through the forest in a`' very thundering and rainy day,
I came to Nottingham.
So great was the tempest many trees were torn up by the roots, and some people killed;
but the Lord preserved us.
On First-day following I had a large meeting in Nottingham, very quiet;
Friends were come to sit under their teacher, the Grace of God,
which brought them salvation, and were established upon the rock and foundation,
Christ Jesus.
After the meeting I went to visit the Friend who had been sheriff about the year 1049,
whose prisoner I then was.

From Nottingham I passed into Leicestershire and came to Sileby, where we had a large,
blessed meeting.
After which I went to Leicester to visit the prisoners there, and then to John Penford`'s,
where we had a general meeting, large and precious.
From thence I passed, visiting Friends and my relations, till I came to Warwick,
where having visited the prisoners, I passed to Badgley,
and had a precious meeting there.
Then I travelled through Northamptonshire, Bedfordshire, Buckinghamshire,
and Oxfordshire, visiting Friends in each county.
In Oxfordshire the devil had laid a snare for me, but the Lord broke it;
his power came over all, his blessed truth spread, and Friends were increased therein.
Thus after I had passed through many counties, visiting Friends,
and had many large and precious meetings amongst them, I came to London.
But I was weak with lying almost three years in cruel and hard imprisonments;
my joints and my body were so stiff and benumbed,
that I could hardly get on my horse or bend my joints;
nor could I well bear to be near the fire or to eat warm meat,
I had been kept so long from it.
Being come to London, I walked a little among the ruins, and took good notice of them.
I saw the city lying,
according as the word of the Lord came to me concerning it several years before.

After I had been a time in London, and visited Friends`' meetings through the city,
I went into the country again, and had large meetings at Kingston, Heading,
and in Wiltshire, till I came to Bristol, where also I had many large meetings.
Thomas Lower came thither out of Cornwall to meet me:
and Friends were there from several parts of the nation, it being then the fair time.
After I was clear of Bristol, I left that city and went to Nathaniel Crisps`'s;
and so through the country to London again,
having large meetings in the way and all quiet, blessed be the Lord.
Thus, though I was very weak, yet I travelled up and down in the service of the Lord,
who enabled me to go through in it.

About this time some, that had run out from truth and clashed against Friends,
were reached unto by the power of the Lord, which came wonderfully over,
and made them "`condemn and tear their papers of controversies to pieces.`"
Several meetings we had with them, and the Lord`'s everlasting power was over all,
and set judgment on the head of that which had run out.
In these meetings, winch lasted whole days,
several who had run out with John Perrot and others, came in again,
and condemned that spirit which led them to "`keep on their hats, when Friends prayed,
and when they themselves prayed.`"
Some of them said, "`that Friends were more righteous than they,`" and that,
"`if Friends had not stood, they had been gone, and had fallen into perdition.`"
Thus the Lord`'s power was wonderfully manifested, and came over all.

Then I was moved of the Lord to recommend the setting up of
five monthly meetings of men and women in the city of London
(besides the women`'s meetings and the quarterly meetings),
to take care of God`'s glory,
and to admonish and exhort such as walked disorderly or carelessly,
and not according to truth.
For whereas Friends had had only quarterly meetings, now truth was spread,
and Friends were grown more numerous,
I was moved to recommend the setting up of monthly meetings throughout the nation.^
footnote:[For some very interesting particulars respecting the setting up of
Monthly and other disciplinary Meetings and their object,
see _Letters of Early Friends_, p. 288-292.]
And the Lord opened to me what I must do,
and how the men`'s and women`'s monthly and quarterly meetings
should be ordered and established in this and in other nations;
and that I should write to those where I did not come, to do the same.
After things were well settled at London, and the Lord`'s truth, power, seed,
and life reigned and shone over all in the city, I went into Essex.
After the monthly meetings were settled in that county, I went into Suffolk and Norfolk,
Thomas Dry being with me.
When we had visited Friends in those parts, and the monthly meetings were settled,
we went into Huntingdonshire, where we had very large and blessed gatherings;
and though we met with some opposition, the Lord`'s power came over all,
and the monthly meetings were established there also.
When we came into Bedfordshire, we had great opposition;
but the Lord`'s power came over it all.
Afterwards we went into Nottinghamshire, where we had many precious gatherings,
and the monthly meetings were settled there.
Then passing into Lincolnshire we had a meeting of some
men Friends of all the meetings in the county,
at his house who had formerly been sheriff of Lincoln, and all was quiet.
After this we passed over Trent into Nottinghamshire again,
the ex-sheriff of Lincoln being with me,
where we had some of all the meetings in that county together.
Our meeting was glorious and peaceable; and many precious meetings we had in that county.

At that time William Smith was very weak and sick,
and the constables and others had seized all his goods, to the very bed he lay upon,
for truth`'s sake.
These officers threatened to break up our meeting; but the Lord`'s power chained them,
so that they had not power to meddle with us, blessed be his name.
After it, I went to visit William Smith,
and there were constables and others watching his corn and beasts,
that none of them might be removed.^
footnote:[The William Smith mentioned here was
originally pastor of an Independent congregation,
living after the strictest manner of that people.
He was convinced about the year 1658, and became a faithful labourer in the gospel.
Many were turned to God by him, for he proved himself a minister of Jesus Christ,
in labours, in travails, in watchings, necessities, and distresses,
suffering much loss of goods and long and tedious imprisonments.
For not paying tithes he was imprisoned twenty-one weeks among felons in Nottingham jail;
and another time had the value of £42 taken from him, whilst he was in prison,
for £7 demanded by the priest of Elton.
{footnote-paragraph-split}
In the times of his frequent imprisonments,
William Smith wrote several books, which were printed together in a folio volume in 1675,
entitled _Balm from Gilead, etc._
When at liberty he travelled abroad strengthening the brethren,
and though often visited by sickness, he was kept in patience and content,
much of the power and presence of God appearing in him
many times when he was in great weakness of body,
to the admiration of beholders.
Daring his last sickness, one evening, many Friends being in the room sitting in silence,
he turned in his bed towards them, and plentifully declared of the love of God,
by which they were much refreshed and tendered.
He also testified of a large portion which he had in life eternal.
Then he spoke to Friends "`to be mindful of truth, and of their service therein,
more than of their daily food; and so committed them to the grace of God.`"
The day before he died he called his children (six or seven),
and tenderly exhorted them "`to keep in the fear of God, and to love the truth,
and God would be a father and portion to them.`"]

Thence we passed into Leicestershire and Warwickshire, where we had many Messed meetings.
The order of the gospel was set up,
and the men`'s monthly meetings established in all those counties.
Then we went into Derbyshire, where we had several large and blessed meetings.
In many places we were threatened by the officers, but,
through the power of the Lord we escaped their hands.
Leaving things well settled in Derbyshire, we travelled over the Peak hills,
which were very cold (for it was then frost and snow), and came into Staffordshire.
At Thomas Hammersley`'s we had a general men`'s meeting;
where things were well settled in the gospel order,
and the monthly meetings established also.
But I was so exceedingly weak, I was hardly able to get on or off my horse`'s back;
but my spirit being earnestly engaged in the work the Lord had concerned me in,
and sent me forth about, I travelled on therein, notwithstanding the weakness of my body,
having confidence in the Lord, that he would carry me through, as he did, by his power.
We came into Cheshire, where we had several blessed gatherings,
and a general men`'s meeting,
wherein all the monthly meetings for that county were settled,
according to the gospel order, in and by the power of God.
After the meeting I passed away.
But when the justices heard of it, they were very much troubled,
that they had not come and broken it up, and taken me; but the Lord prevented them.
After I had cleared myself there in the Lord`'s service, I passed into Lancashire,
to William Barnes`'s, near Warrington,
where met some of most of the meetings in that county;
and there all the monthly meetings were established in gospel order.
From thence I sent papers into Westmorland by Leonard Fell and Robert Widders,
and also into Durham, Cleveland, Northumberland, Cumberland, and Scotland,
to exhort Friends to settle the monthly meetings in the Lord`'s power in those places;
which they did.
So the Lord`'s power came over all, and the heirs of it came to inherit it.
For the authority of our meetings, is the power of God, the gospel,
which brings life and immortality to light;
that all may see over the devil that hath darkened them,
and that all the heirs of the gospel may walk according to the gospel,
and glorify God with their bodies, souls, and spirits, which are the Lord`'s;
for the order of the glorious gospel is not of man, nor by man.
To this meeting in Lancashire, Margaret Fell, being a prisoner, got liberty to come,
and went with me to Jane Milner`'s in Cheshire, where we parted.
I passed into Shropshire, and from thence into Wales,
and had a large general men`'s meeting at Charles Lloyd`'s, where some opposers came in,
but the Lord`'s power brought them down.
Having gone through Denbighshire and Montgomeryshire we passed into Merionethshire,
where we had several blessed meetings; and then went to the sea-side,
where we had a precious meeting.
And Friends in these parts, being established on Christ, their foundation,
and the monthly meetings settled in the power of God, we left Wales,
and returned into Shropshire, where the Friends of the country gathering together,
the monthly meetings were established there also.
Then coming into Worcestershire, after many meetings amongst Friends in that county,
we had a general men`'s meeting at Henry Gibb`'s house, at Pashur,
where also the monthly meetings were settled in gospel order.

The sessions were held that day in the town,
and some Friends were concerned lest they should send officers to break up our meeting;
but the Lord`'s power restrained them, so that it was quiet;
through which power we had dominion.
I had several meetings amongst Friends in that county till I came to Worcester;
and it being the fair time, we had a precious meeting there.
There was then in Worcester one Major Wild, a persecuting man;
and after I was gone out of town, some of his soldiers inquired after me;
but having left Friends there settled in good order, we passed to Droitwich,
and thence to Shrewsbury, where also we had a very precious meeting.
The mayor hearing that I was in town, got the rest of the officers together,
to consult what to do against me; for they said,
"`the great Quaker of England was come to town.`"
But when they were come together, the Lord confounded their councils, so that,
when some were for imprisoning me, others opposed it;
and so being divided among themselves, I escaped their hands.

We went also into Radnorshire, where we had many precious gatherings,
and the monthly meetings were settled in the Lord`'s power.
As we came out of that county, staying a little at a market-town,
a justice`'s clerk and other rude fellows combined together to do us mischief on the road.
They followed us out of town, and soon overtook us;
but there being many market-people on the way,
they were somewhat hindered from doing what they intended.
Yet observing two of our company ride at some distance behind, they set upon them;
and one of them drew his sword, and cut one of those two Friends,
whose name was Richard Moor, Surgeon, of Shrewsbury.
Meanwhile another of these rude fellows came galloping
after me and the other Friend that was with me;
and having to pass over a narrow bridge,
in his eagerness to get before us he rode into the brook,
and plunged his horse into a deep hole in the water.
I saw the design, and stopped, desiring Friends to be patient, and give them no occasion.
By this time Richard Moor came up to us, with the other Friend that was with him,
who knew the men and their names.
Then we rode on, and a little further met another man on foot much in liquor,
with a naked sword in his hand.
And not far beyond him we met two men and women,
one of whom had his thumb cut off by the drunken man; for he, being in drink,
attempted rudeness to one of the women; and this man withstanding him, and rescuing her,
he drew his sword and cut off his thumb.
Now this drunken man had a horse, which, being loose, followed him some way behind.
I rode after it, and having caught it, brought it to the man that had his thumb cut off;
and bid him take the horse to the next justice of peace,
by which means they might find out, and pursue the man that had wounded him.

On this occasion I wrote to the justices,
and to the judge of the assize which was then at hand;
and employed some Friends to carry it to the justices first.
The justice to whom the clerk belonged, rebuked his clerk and the others also,
for abusing us on the highway;
so that they were glad to come and entreat
Friends not to appear against them at the assize;
which, on their submission and acknowledgement of their fault, was granted.
This was of good service in the country, for it stopped many rude people,
who before had been forward to abuse Friends.

We passed into Herefordshire, where we had several blessed gatherings;
and we had a general men`'s meeting also, where all the monthly meetings were settled.
There was about this time a proclamation against meetings;
and as we came through Herefordshire,
we were told of a great meeting there of the Presbyterians,
who had engaged themselves to stand and give up all, rather than forsake their meetings.
When they heard of this proclamation, the people came, but the priest was gone,
and left them at a loss.
Then they met in Leominster privately, and provided bread, cheese,
and drink in readiness, that if the officers should come,
they might put up their Bibles and fall to eating.
The bailiff found them out, and came in among them, and said,
"`their bread and cheese should not cover them, he would have their speakers.`"
They cried, "`what then would become of their wives and children?`"
But he took their speakers and kept them a while.
This the bailiff told Peter Young, and said,
"`they were the veriest hypocrites that ever made a profession of religion.`"

The like contrivance they had in other places.
For there was one Pocock at London, that married Abigail Darey, who was called a lady;
and she being convinced of truth, I went to his house to see her.
This Pocock had been one of the triers of the priests; and, being a high Presbyterian,
and envious against us, he used to call our Friends house-creepers.
He being present, she said to me,
"`I have something to speak to thee against my husband.`"
"`Nay,`" said I, "`thou must not speak against thy husband.`"
"`Yes,`" said she, "`but I must in this case.
Last First-day,`" said she, "`he and his priests and people, the Presbyterians, met;
they had candles and tobacco-pipes, bread, cheese, and cold meat on the table;
and they agreed beforehand, that if the officers should come in upon them,
then they would leave their preaching and praying, and fall to their cold meat.`"
"`O,`" said I to him, "`is not this a shame to you, who persecuted and imprisoned us,
and spoiled our goods, because we would not join you in your religion,
and called us house-creepers, that now ye do not stand to your own religion yourselves?
Did ye ever find our meetings stuffed with bread and cheese and tobacco-pipes?
Or did you ever read in the Scriptures of any such practice among the saints?`"
"`Why,`" said the old man, "`We must be as wise as serpents.`"
I replied, "`this is the serpent`'s wisdom indeed.
But who would have thought that you Presbyterians and Independents,
who persecuted and imprisoned others, spoiled their goods,
and whipped such as would not follow your religion, should now flinch yourselves,
and not dare to stand to your own religion, but cover it with tobacco-pipes,
flagons of drink, cold meat, and bread and cheese!`"
But this, and such-like deceitful practices, I understood afterwards,
were too common amongst them in times of persecution.

After we had travelled through Herefordshire, and meetings were well settled there,
we passed into Monmouthshire, where I had several blessed meetings;
and at Walter Jenkins`'s, who had been a justice of the peace, we had a large gathering,
where some were convinced; this meeting was quiet.
But to one before this, came the bailiff of the hundred, almost drunk,
pretending he was to take up the speakers.
There was a mighty power of God in the meeting, so that, although he raged,
the power of the Lord limited him, that he could not break it up.
When it was over, I stayed a while, and he stayed also.
After some time I spoke to him, and so passed quietly away.
At night some rude people came, and shot off a musket against the house,
but did not hurt anybody.
Thus the Lord`'s power came over all, and chained down the unruly spirits,
so that we escaped them.
We came to Ross that night, and had a meeting at James Merrick`'s.

After this we came into Gloucestershire and had a
general men`'s meeting at Nathaniel Crips`'s house,
where all the monthly meetings were settled in the Lord`'s everlasting power;
and the heirs of salvation were exhorted to take their possessions in the gospel,
the power of God, which was and is the authority of their meetings.
Many blessed gatherings we had up and down in that county, before we came to Bristol.
And after several powerful seasons,
the men`'s and women`'s meetings were settled there also.

As I was in bed at Bristol, the word of the Lord came to me,
that I must go back to London.
Next morning Alexander Parker and several others came to me: I asked them,
"`what they felt?`"
They in like manner asked me, "`what was upon me?`"
I told them, "`I felt I must return to London.`"
They said, "`the same was upon them.`"
So we gave up to return to London; for whatever way the Lord moved and led us,
thither we went in his power.
Leaving Bristol, we passed into Wiltshire,
and established the men`'s monthly meetings in the Lord`'s power there;
and visited Friends till we came to London.

After we had visited Friends in the city,
I was moved to exhort them to bring all their
marriages to the men`'s and women`'s meetings,
that they might lay them before the faithful;
that care might be taken to prevent those disorders that had been committed by some.
For many had married contrary to their relations`' minds; and some young,
raw people that came amongst us, had mixed with the world.
Widows had married without making provision for their children by their former husbands,
before their second marriage.
Yet I had given forth a paper concerning marriages about the year 1653,
when truth was but little spread over the nation;
advising Friends who might be concerned in that case,
"`that they might lay it before the faithful in time, before anything was concluded,
and afterwards publish it in the end of a meeting, or in a market,
as they were moved thereto.
And when all things were found clear,
they being free from all others and their relations satisfied,
they might appoint a meeting on purpose for the taking of each other,
in the presence of at least twelve faithful witnesses.`"
Yet these directions not being observed, and truth being now more spread over the nation,
it was therefore ordered, by the same power and Spirit of God,
"`that marriages should be laid before the men`'s monthly and quarterly meetings,
or as the meetings were then established;
that Friends might see that the relations of those that proceeded to marriage,
were satisfied; that the parties were clear from all others;
and that widows had made provision for their first husbands`' children,
before they married again; and what else was needful to be inquired into;
that all things might be kept clean and pure,
and be done in righteousness to the glory of God.`"
Afterwards it was ordered, in the wisdom of God, "`that if either of the parties,
that intended to marry, came out of another nation, county, or monthly meeting,
they should bring a certificate from the monthly meeting to which they belonged;
for the satisfaction of the monthly meeting before
which they came to lay their intentions of marriage.`"^
footnote:[Some interesting documents,
exhibiting the early care of the Society with regard to marriages,
may be referred to in _Letters, etc., of Early Friends,_ p. 259, 279, 283, etc.
So early as 1659, at a meeting of Friends from four comities,
an _Epistle of Counsel and Advice_ was issued on this, and other subjects;
recommending "`that no marriage take place hastily or rashly;
but in the fear of the Lord, and in presence of many witnesses,
according to Scripture example; that so no scandal or blemish may be laid upon the truth,
but that all may be brought to the light; that a record in writing of the day, place,
and year, be kept within the meeting where a marriage occurs,
of which one or both are members; under which the witnesses may set their names.`"]

These things, with many other services for God, being set in order,
and settled in the churches in the city, I passed out of London,
in tho leadings of the Lord`'s power, into Hertfordshire.
After I had visited Friends, and the men`'s monthly meetings were settled there,
I had a great meeting at Baldock, of many sorts of people.
Then returning towards London by Waltham,
I advised the setting up of a school there for teaching boys;
and also a girls`' school at Shacklewell for instructing
them in whatsoever things were civil and useful.^
footnote:[In the establishment of the schools at Waltham and at Shacklewell,
at the suggestion of George Fox,
we have evidence of his desire that a useful education should be imparted to youth.
It is an error to suppose the early Friends depreciated human learning,
and they must be exonerated from any such charge.
They exhibited in their own persons the practicability
of the union of knowledge and virtue.
While they were, many of them, eminent for their learning,
they were distinguished for the piety of their lives.
They were indeed the friends of both,
but did not patronize the one to the prejudice and expulsion of the other.
They always maintained (as Friends continue to do) that
learning is not necessary to make a gospel minister,
and here it is that many have mistaken their meaning.
{footnote-paragraph-split}
Barclay, in his celebrated _Apology,_ nowhere condemns the propriety,
or usefulness of human learning,
or denies it to be promotive of the temporal comforts of man.
He says the knowledge of Latin, Greek, and Hebrew, or of Logic and Philosophy,
of Ethics or of Physics and Metaphysics, is not necessary.
But mark his meaning.
Not necessary to make a minister of the gospel.
But where does he say that knowledge,
which he himself possessed to such a considerable extent, was not necessary;
or that it did not contribute to the innocent pleasures of life?
What would have been the character of his own book,
or what would have been its Comparative value and usefulness,
had he not been able to quote so many authors to his purpose in their original texts,
or to have detected so many classical errors, introduced such apposite history,
or to have drawn up his propositions with so much
logical and mathematical clearness and precision;
or if he had not been among the first literary characters of
his day?
{footnote-paragraph-split}
William Penn was
equally celebrated with Barclay as a scholar.
His works afford abundant proof of his erudition, and of the high cultivation of his wind.
Like the rest of his associates,
he was no advocate for learning as a qualification for a minister of the gospel;
but he was yet a friend to it, on the principle that it enlarged the understanding,
and that it added to the innocent pleasures of the mind.
He entreated his wife,
in the beautiful letter he left her before he embarked on his first voyage to America,
"`not to be sparing of expense in procuring learning for his children;
for that by such parsimony all was lost that was saved.`"
And he recommended also, in the same letter,
a mathematical and philosophical education.
{footnote-paragraph-split}
Penn`'s Secretary,
James Logan, was also a patron of learning among the early Friends.
He was a correspondent of Sir Hans Sloane and other literati of Europe,
a contributor to the Philosophical Transactions, and bequeathed his library,
of 3000 volumes, on arts and sciences in various languages, to the city of Philadelphia,
with an endowment to preserve it for public use.
{footnote-paragraph-split}
Thomas Ellwood,
the companion of Milton,
was so sensible of the disadvantages arising from a want of knowledge,
that he revived his learning with great industry after he had become a Friend.
"`I mentioned before,`" says he in his Journal,
"`that when I was a boy I made some progress in learning,
and that I lost it all again before I came to be a man.
Nor was I rightly sensible of my loss therein, till I came amongst Friends.
But there I both saw my loss and lamented it,
and applied myself with the utmost diligence at all leisure times to recover it.
So false I found that charge to be,
which in those times was cast as a reproach on the Society,
that they despised and decried all human learning,
because they denied it to be essentially necessary to a gospel ministry,
which was one of the controversies of those times.`"
Ellwood`'s friend, Isaac Pennington, assisted him in this matter,
and through his influence with Dr. Paget,
procured him the means of improvement in becoming a reader to Milton.]

After I had had several precious meetings in the country, I came to London again,
where I stayed a while in the work and service of the Lord;
and then went into Buckinghamshire, where I had many precious meetings.
At John Brown`'s, of Weston near Aylesbury,
some of the men Friends of each meeting being gathered together,
the men`'s monthly meetings for that county were established, in the order of the gospel,
the power of God; and the power of the Lord confirmed it in all that felt it,
and they came thereby to see and feel,
that the power of God was the authority of their meetings.
Then after the monthly meeting was settled there in the order of the gospel,
and upon the foundation of Christ Jesus, I went to Nathaniel Ball`'s,
at North Newton near Banbury, in Oxfordshire, who was a Friend in the ministry.
And there being a general meeting, where some from all the meetings were present,
the monthly meetings for that county were then settled in the power of God;
and Friends were very glad of them; for they came into their services in the church,
to take care for God`'s glory.
After this meeting, we passed into Gloucestershire,
visiting Friends till we came into Monmouthshire, to Richard Hambery`'s;
where meeting with some from all the meetings of that county,
the monthly meetings were settled there also in the Lord`'s power,
that all might take care of God`'s glory,
and admonish and exhort such as did not walk as became the gospel.
And indeed these meetings made a great reformation amongst people,
insomuch that the justices took notice of their usefulness.

Richard Hambery and his wife accompanied us a day`'s journey visiting Friends,
till we came to a widow`'s house, where we staid that night.
Thence we passed over the hills next day,
visiting Friends and declaring truth to the people, till we came to another widow`'s,
where we had a meeting.
She could not speak English, yet she praised the Lord for sending us to visit them.

We travelled till we came to Swansea,
where on the First-day we had a large and precious meeting,
the Lord`'s presence being eminently amongst us.
On a week day afterwards we had a general meeting beyond Swansea,
of men Friends from Swansea, Tenby, Haverfordwest, and other places;
and there the monthly meetings were settled in gospel order,
and received by Friends in the power of the Lord; and the Lord`'s truth was over all.

From thence we endeavoured to go by water into Cornwall,
and returned through Swansea to Mumbles, thinking to get passage there,
but the captain deceived us; for though he had promised to carry us,
yet when we came he would not.
We went to another place where there was a passage-boat, into which we got our horses;
but some rude men in the boat (though called gentlemen) threatened to pistol the master,
if he took us in, who, being afraid of them, turned our horses out again;
which put us out of hopes of getting over that way.
Wherefore turning back into the country, we stayed up all night,
and about two in the morning took horse, and travelled till we came near Cardiff,
where we stayed one night.
The next day we came to Newport; and it being market-day there,
several Friends came to us, with whom we sat a while;
and after a refreshing season together, we parted from them, and went on our way.

Beyond this market-town we overtook a man, who lingered on the way,
as if he stayed for somebody; but when we came up to him, he rode along with us,
and asked us many questions.
At length meeting with two others, who seemed to be pages to some great persons,
he made acquaintance with them, and I heard him tell them he would stop us,
and take us up.
We rode on; being in our way; and when he came to us, and would have stopped us,
I told him, "`none ought to stop us on the king`'s highway,
for it was as free for us as for them; and I was moved to exhort him to fear the Lord.
Then he galloped away before us;
and I perceived his intent was to stop us at Shipton in Wales, which was a garrison town,
through which we were to pass.
When we were come to Shipton, John-ap-John being with me,
we walked down the hill into the town, leading our horses.
It being the market-day there, several Friends met us, and would have had us to an inn.
But we were not to go into any inn;
so we walked directly through the town over the bridge,
and then we were out of the limits of that town.
Thus the Lord`'s everlasting arm and power preserved us,
and carried us on in his work and service.

The next First-day we had a large meeting in the Forest Of Dean; and all was quiet.
Next day we passed over the water to Oldstone; where, after we had visited Friends,
we came again to William Yeoman`'s house, at Irb`'s Court in Somersetshire.
From thence we went to a meeting at Portshead,
whither several Friends from Bristol came to us.
After this we went further up into the country, and had several large meetings;
and the Lord`'s living presence was with us,
supporting and refreshing us in our labour and travel in his service.

We came to a place near Minehead,
where we had a general meeting of the men Friends in Somersetshire.
There came also a cheat,
whom some friendly people would have had me to take along with me.
I saw he was a cheat; and therefore bid them bring him to me,
and see whether he could look me in the face.
Some were ready to think I was too hard towards him,
because I would not let him go along with me; but when they brought him to me,
he was not able to look me in the face, but looked hither and thither;
for he was indeed a cheat, and had cheated a priest by pretending to be a minister;
he had got the priest`'s suit and went away with it.

After the meeting we passed to Minehead, where we tarried.
In the night I had an exercise upon me, from a sense of a dark spirit,
working and striving to get up to disturb the church of Christ.
Next morning I was moved to write a few lines to Friends as a warning thereof,
as follows:--

[.salutation]
"`Dear Friends,

"`Live in the power of the Lord God, in his Seed that is set over all,
and is over all trials that you may have with the dark spirit,
which would be owned in its actings, and thrust itself amongst you;
which is not come as yet: but in the power of the Lord God, and his Seed, keep over it,
and bring it to condemnation.
For I felt a kind of dark spirit thrusting itself up towards you,
and heaving up last night; but you may keep it down with the power of God,
that the witness may arise to condemn its actings,
so far as it hath spread its dark works, before it have any admittance.
So no more, but my love in the Seed of God, which changeth not.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Minehead in Somersetshire, 22nd of 4th Month, 166S.

Next day several Friends of Minehead accompanied us as
far as Barnstaple and Appledon in Devonshire,
where we had a meeting.
Barnstaple had been a bloody, persecuting town.
There were two men Friends of that place, who had been a great while at sea;
and coming home to visit their relations, one of them having a wife and children,
the mayor of the town sent for them, under pretence to converse with them;
and he put the oaths of allegiance and supremacy to them.
Because they could not swear, he sent them to Exeter jail,
where Judge Archer premunired them, and kept them till one of them died in prison.
When I heard of this, I was moved to write a letter to Judge Archer,
and another to the mayor of Barnstaple,
laying their wicked and unchristian actions upon their heads,
and letting them know,`" that the blood of that man would be required at their hands.`"

After a precious meeting at Appledon among some faithful Friends there,
we passed to Stratton, and stayed at an inn all night.
Next day we rode to Humphrey Lower`'s, where we had a very precious meeting;
and next day to Truro; visiting Friends till we came to the Land`'s-end.
Then coming up by the south part of that county,
we visited Friends till we came to Tregangeeves,
where at Loveday Hambley`'s we had a general meeting for all the county;
in which the monthly meetings were settled in the Lord`'s power,
and in the blessed order of the gospel;
that all who were faithful might admonish and exhort
such as walked not according to the gospel;
that so the house of God might be kept clean, and righteousness might run down,
and all unrighteousness be swept away.
Several that had run out, were brought to condemn what they had done amiss;
and through repentance came in again.

Being clear of the county of Cornwall, we came into Devonshire,
and had a meeting amongst Friends at Plymouth.
Whence passing to Richard Brown`'s, we came to the widow Phillips`'s,
where we had some men Friends from all the meetings together;
and there the men`'s monthly meetings were settled in the heavenly order of the gospel,
the power of God; which answered the witness of God in all.
There was a great noise of a troop of horse coming to disturb our meeting;
but the Lord`'s power prevented it, and preserved us in peace and safety.

After things were well settled, and the meeting over, we came to King`'s-bridge,
and visited Friends there.
Then leaving Friends in those parts well settled in the power of God,
we passed to Topsham, and Membury, visiting Friends, and having many meetings in the way,
till we came to Ilchester in Somersetshire.
Here we had a general men`'s meeting,
and therein settled the men`'s monthly meetings
for that county in the Lord`'s everlasting power;
and Friends being refreshed and comforted in the Lord`'s power,
and established upon Christ, their rock and foundation, we passed to Puddimoor; where,
at William Beaton`'s, we had a blessed meeting, and all was quiet;
though the constables had threatened before.

When we had visited most of the meetings in Somersetshire,
we passed into Dorsetshire to George Harris`'s house, where we had a large men`'s meeting.
There all the men`'s monthly meetings for that county
were settled in the glorious order of the gospel,
that all in the power of God might "`seek that which was lost,
and bring again that which was driven away; cherish the good, and reprove the evil.`"

Then we came to Southampton, where we had a large meeting on First-day.
Thence we went to Captain Beeves`'s,
where the general men`'s meeting for Hampshire was appointed;
to which some of all the county came, and a blessed time we had.
There the men`'s monthly meetings for that county were settled in the order of the gospel,
which had brought life and immortality to light in them.
But there came a rude company of Banters, who had opposed and disturbed our meetings much.
One of the women had lain with a man, who declared it at the market-cross,
and gloried in his wickedness.
A company of these lewd people lived together at
a house hard by the place where our meeting was.
I went to it, and told them of their wickedness.
The man of the house said, "`Why! did I make so strange of that?`"
Another of them said, "`It was to stumble me.`"
I told them, "`their wickedness should not stumble me, for I was above it.`"
And I was moved of the Lord to tell them,
"`that the plagues and judgments of God would overtake them, and come upon them.`"
Afterwards they went up and down the country,
till at last they were cast into Winchester jail,
where the man that had lain with the woman stabbed the jailer, but not mortally.
And after they were let out of jail,
this fellow that had stabbed the jailer hung himself;
the woman also had like to have cut a child`'s throat, as we were informed.
These people had formerly lived about London; and when the city was fired,
they prophesied,
"`that all the rest of London should be burnt
within fourteen days,`" and hastened out of town.
Though they were Ranters, great opposers of Friends, and disturbers of our meetings,
yet in the country where they came, some people that did not know them,
would be apt to say they were Quakers.
Wherefore I was moved of the Lord to write a paper,
to be dispersed among the magistrates and people of Hampshire,
to clear Friends and truth of these lewd people and their wicked actions.

After the men`'s monthly meetings in those parts were settled,
and the Lord`'s blessed power was over all,
we went to a town where we had a meeting with Friends.
Thence we came to Farnham, where we met many Friends, it being the market-day.
We had many precious meetings up and down that country.
Friends in those parts had formerly been plundered, and their goods much spoiled,
both for tithes, and for going to meetings;
but the Lord`'s power at this time preserved both them
and us from falling into the persecutor`'s hands.

We passed thence, and had a general men`'s meeting at a Friend`'s house in Surrey,
who had been plundered so extremely, that he had scarcely a cow, horse, or swine, left.
The constables threatened to come and break up our meeting, but the Lord restrained them.
At this meeting the men`'s monthly meetings were
settled in the authority of the heavenly power.
After we had visited Friends in that county, and had many large and precious gatherings,
we passed to a Friend`'s house in Sussex,
where the general meeting for the men Friends of that county was appointed to be held;
and thither came several Friends from London to visit us.
We had a blessed meeting;
and the men`'s monthly meetings for that county
were then settled in the Lord`'s eternal power.
There were at that time great threatenings of disturbance; but the meeting was quiet.
We had several large meetings in that county,
though Friends were then in great sufferings there, and many in prison.
I was sent for to visit a Friend that was sick, and went to see those that were prisoners.
There was danger of my being apprehended; but I went in the faith of God`'s power,
and thereby the Lord preserved me in safety.

Having visited Friends through the country, we passed into Kent, where,
after we had been at several meetings,
we had a general meeting for the men Friends of that county.
There also the men`'s monthly meetings for that county were settled in the power of God,
and established in the order of the gospel,
for all the heirs of it to enter into their services,
and care in the church for the glory of God.
Friends rejoiced in the order of the gospel, and were glad of the settlement thereof,
which is not of man nor by man.
After this I visited Friends in their meetings in Kent;
and when I had cleared myself of the Lord`'s service in that county, I came up to London.

Thus were the men`'s monthly meetings settled through the nation;
for I had been in Berkshire before,
where most of the ancient Friends of that county were in prison;
and when I had informed them of the service of these monthly meetings,
they were settled amongst them also.
The quarterly meetings were generally settled before.
I wrote also into Ireland by faithful Friends, and into Scotland, Holland, Barbadoes,
and several parts of America,
advising Friends to settle their men`'s monthly meetings in those countries.
For they had their general quarterly meetings before;
but now that truth was increased amongst them,
they should settle those men`'s monthly meetings in the power and Spirit of God,
that first convinced them.
Since these meetings have been settled, and all the faithful in the power of God,
who are heirs of the gospel, have met together in the power of God,
which is the authority of them, to perform service to the Lord therein,
many mouths have been opened in thanksgivings and praise,
and many have blessed the Lord God, that ever he sent me forth in this service; yea,
with tears have many praised the Lord.
For now all coming to have a concern and care for God`'s honour and glory,
that his name be not blasphemed, which they profess;
and to see that all who profess the truth, walk in the truth, in righteousness,
and in holiness, which becomes the house of God,
and that all order their conversation aright, that they may see the salvation of God;
all having this care upon them for God`'s glory,
and being exercised in his holy Power and Spirit,
in the order of the heavenly life and gospel of Jesus, they may all see and know,
possess and partake of, the government of Christ,
of the increase of which there is to be no end.
Thus the Lord`'s everlasting renown and praise
are set up in every one`'s heart that is faithful;
so that we can say, the gospel order established amongst us, is not of man, nor by man,
but of and by Jesus Christ, in and through the Holy Ghost.
This order of the gospel, which is not of man, nor by man, but from Christ,
the heavenly man, is above all the orders of men in the fall, whether Jews, Gentiles,
or apostatized Christians, and will remain when they are gone.
For the power of God, which is the everlasting gospel, was before the devil was,
and will be and remain for ever.
And as the everlasting gospel was preached in the apostles`' days to all nations,
that all nations might come into the order of it, through the divine power,
which brings life and immortality to light, that they who are heirs of it,
might inherit the power and authority of it; so now,
since all nations have drunk the whore`'s cup,
and all the world hath worshipped the beast (but they whose names are
written in the book of life from tho foundation of the world,
who have worshipped God in spirit and in truth, as Christ commanded),
the everlasting gospel is to be, and is, preached again,
as John the divine foresaw it should, to all nations, kindreds, tongues, and people.
This everlasting gospel torments the whore, and makes her and the beast to rage,
even the beast that hath power over the tongues, which are called the original,
to order them, by which they make divines, as they call them.
But all that receive the gospel, the power of God,
which brings life and immortality to light, come to see over the beast, devil, whore,
and false prophet, that darkened them and all their worships and orders,
and come to be heirs of the gospel, the power of God, which was before the beast, whore,
false prophet, and devil were, and will be,
when they are all gone and cast into the lake of fire.
And they that are heirs of this power and of this gospel,
inherit the power which is the authority of this order, and of our meetings.
These come to possess the joyful order of the joyful gospel,
the comfortable order of the comfortable gospel,
the glorious order of the glorious gospel,
and the everlasting order of the everlasting gospel, the power of God,
which will last for ever, and will out-last all the orders of the devil,
and that which is of men or by men.
These shall see the government of Christ,
who hath all power in heaven and earth given to him; and of the increase of his glorious,
righteous, holy, just government, there is no end;
but his government and his order will remain; for he who is the author of it,
is the first and the last, the beginning and ending, the foundation of God,
which over all stands sure, Christ Jesus, the Amen.

[.small-break]
'''

Being returned to London, I stayed some time there,
visiting Friends`' meetings in and about the city.
While I was in London, I went one day to visit Esquire Marsh,
who had showed much kindness both to me and to Friends;
I happened to go when he was at dinner.
He no sooner heard my name, than he sent for me up,
and would have had me sit down with him to dinner; but I had not freedom to do so.
Several great persons were at dinner with him;
and he said to one of them who was a great Papist, "`Here is a Quaker,
whom you have not seen before.`"
The Papist asked me, "`whether I owned the christening of children?`"
I told him, "`there was no Scripture for any such practice.`"
"`What,`" said he, "`not for christening children?`"
I said, "`nay.`"
I told him, "`the one baptism by the one Spirit into one body we owned;
but to throw a little water on a child`'s face,
and say that was baptizing and christening it, there was no Scripture for that.`"
Then he asked me, "`whether I owned the Catholic faith?`"
I said, "`yes,`" but added,
that "`neither the Pope nor the Papists were in that Catholic faith;
for the true faith works by love, and purifies the heart,
and if they were in that faith that gives victory,
by which they might have access to God,
they would not tell the people of a purgatory after they were dead.`"
So I undertook to prove that "`neither Pope nor Papists that held a purgatory hereafter,
were in the true faith; for the true, precious, divine faith,
which Christ is the author of, gives victory over the devil and sin,
that had separated man and woman from God.
And if they, the Papists, were in the true faith, they would never use racks, prisons,
and fines, to persecute and force others to their religion, that were not of their faith.
This was not the practice of the apostles and primitive Christians,
who witnessed and enjoyed the true faith of Christ;
but it was the practice of the faithless Jews and Heathens so to do.
But,`" said I, "`seeing thou art a great and leading man among the Papists,
and hast been taught and bred up under the Pope, and seeing thou sayest,
'`there is no salvation but in your church,`' I desire to know of thee,
what it is that doth bring salvation in your church?`"
He answered, "`a good life.`"
"`And nothing else,`" said I. "`Yes,`" he said, "`good works.`"
"`And is this it that brings salvation in your church, a good life and good works?
Is this your doctrine and principle?`"
said I. "`Yes,`" said he.
"`Then,`" said I, "`neither thou, nor the Pope,
nor any of the Papists know what it is that brings salvation.`"
Then he asked me, what brought salvation in our church?
I told him, "`that which brought salvation to the church in the apostles`' days,
the same brought salvation to us, and not another; namely, '`the Grace of God, which,
the Scripture says, brings salvation, and hath appeared to all men,
which taught the saints then, and teaches us now.
This Grace which brings salvation, teaches to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly.
So it is not the good works nor the good life that brings salvation, but the Grace?`"
"`What!`" said the Papist, "`doth this Grace that brings salvation, appear unto all men?`"
"`Yes,`" said I. "`Then,`" said he, "`I deny that.`"
I replied, "`all that deny that, are sect-makers, and are not in the universal faith,
grace, and truth, which the apostles were in.`"

Then he spoke to me about the mother-church.
I told him, "`the several sects in Christendom had accused us, and said,
'`we forsook our mother-church.`'
The Papists charged us with forsaking their church, saying,
'`Rome was the only mother-church.`'
The Episcopalians taxed us with forsaking the old Protestant religion, alleging,
'`theirs was the reformed mother-church.`'
The Presbyterians and Independents blamed us for leaving them, each of them pretending,
'`theirs was the right reformed church.'`" But, I said,
"`if we could own any outward city or place to be the mother-church,
we should own Jerusalem,
where the gospel was first preached by Christ himself and his apostles,
where Christ suffered, where the great conversion to Christianity by Peter was,
where the types, figures, and shadows, which Christ ended,
and where Christ commanded his disciples to '`wait until
they were endued with power from on high.`'
If any outward place deserved to be called the mother,
that was the place where the first great conversion to Christianity was.
But the apostle saith, Gal. 4:25-27, '`Jerusalem, which now is,
is in bondage with her children; but Jerusalem which is above, is free,
which is the mother of us all.
For it is written, Rejoice, thou barren, that bearest not; break forth and cry,
thou that travailest not;
for the desolate hath many more children than she which hath an husband.`'
The apostle does not say, outward Jerusalem was the mother,
though the first and great conversion to Christianity was there.
And there is less reason for the title +++[+++mother]
to be given to Rome, or to any other outward place or city, by the children of Jerusalem,
that is above and free; neither are they Jerusalem`'s children that is above and free,
who give the title of mother either to outward Jerusalem, to Rome,
or to any other place or sect of people.
And though this title +++[+++mother]
hath been given to places and sects amongst and by the degenerate Christians,
yet still we say, as the apostle said of old, '`Jerusalem that is above,
is the mother of us all.`'
And we can own no other, neither outward Jerusalem nor Rome,
nor any sect of people for our mother, but Jerusalem which is above, which is free,
the mother of all that are born again, and are become true believers in the light,
grafted in Christ, the Heavenly Vine.
For all who are born again of the immortal Seed, by the Word of God,
which lives and abides for ever, feed upon the milk of the Word, the breast of life,
and grow by it in life,
and cannot acknowledge any other to be their mother but Jerusalem which is above.`"
"`O,`" said Esquire Marsh to the Papist, "`You do not know this man,
if he would but come to church now and then, he would be a brave man.`"

After some other discourse, I went aside with Justice Marsh into another room,
to speak with him concerning Friends; for he was a justice of peace for Middlesex,
and being a courtier, the other justices put much of the management of affairs upon him.
He told me "`he was in a strait how to act between us and some other Dissenters.
For,`" said he, "`you cannot swear, and the Independents, Baptists,
and Fifth-monarchy people say also they cannot swear; therefore,`" said he,
"`how shall I know how to distinguish betwixt you and them,
seeing they and you all say it is for conscience`' sake that you cannot swear?`"
I answered, "`I will show thee how to distinguish.
They, or most of them, thou speakest of, can and do swear in some cases,
but we cannot swear in any case.
If a man should steal their cows or horses,
and thou shouldst ask them whether they would swear they were theirs;
many of them would readily do it.
But if thou try our Friends, they cannot swear for their own goods.
Therefore, when thou puttest the oath of allegiance to any of them, ask them,
'`whether they can swear in any other case, as for their cow or horse; which,
if they be really of us, they cannot do,
though they can bear witness to the truth.'`" Hereupon
I gave him a relation of a trial in Berkshire,
which was thus: A thief stole two beasts from a Friend of ours,
the thief was taken and cast into prison,
and the Friend appeared against him at the assizes.
But somebody having informed the judge, that the prosecutor was a Quaker,
and could not swear, the judge, before he heard what the Friend could say, said,
"`Is he a Quaker? and will he not swear?
Then tender him the oaths of allegiance and supremacy.`"
So he cast the Friend into prison, and premunired him,
and set the thief at liberty that had stolen his goods.
Justice Marsh, said, "`that judge was a wicked man.`"
"`But,`" said I, "`if we could swear in any case,
we would take the oath of allegiance to the king,
who is to preserve the laws that are to support every man in his estate.
Whereas others, that can swear in some cases to preserve a part of their estates,
if they be robbed, will not take this oath to the king,
who is to preserve them in their whole estates and bodies also.
So that thou mayest easily distinguish,
and put a difference between us and those people.`"
Justice Marsh was afterwards very serviceable to Friends in this and other cases;
for he kept several, both Friends and others, from being premunired.
When Friends were brought before him in time of persecution,
he set many of them at liberty; and when he could not avoid sending to prison,
he sent told him, "`he had sent some of us to prison contrary to his conscience,
and he could not do so any more.`"
Wherefore he removed his family from Limehouse, where he lived,
and took lodgings near St. James`'s Park.
He told the king that "`if he would be pleased to give liberty of conscience,
that would quiet and settle all; for then none could have any pretence to be uneasy.`"
And indeed he was a very serviceable man to truth and Friends in his day.

We had great service at London this year; the Lord`'s truth came over all,
and many that had gone out from truth came in again,
confessing and condemning their outgoings.
After I had stayed some time in London, I visited Friends in Surrey and Sussex,
and in other places that way, and afterwards travelled northward,
having Leonard Fell with me.
We visited Friends till we came to Warwick, where many were in prison;
and we had a meeting in the town.
I passed thence to Birmingham and Badgley.
At Badgley I had a large meeting; after which I came to Nottingham,
where on First-day we had a precious meeting,
but not without danger of being apprehended,
the constables having threatened to take up Friends.

I passed thence, visiting Friends, till I came to Balby, and so to York,
to the quarterly meeting; and a blessed time we had.
Friends in Yorkshire had seven monthly meetings before;
and they were so sensible of the service of them,
that they desired to have seven more added to them,
for truth was much spread in that county.
So they were established; and now they have fourteen monthly meetings in that county.^
footnote:[The fourteen monthly meetings mentioned above
as settled in Yorkshire so early as 1669,
were York, Balby, Pontefract, Brighouse, Knaresbro'`, Settle, Malton, Thirsk, Richmond,
Gisbro'`, Scarbro'`, Kelke, Oustwick, and Elloughton.]

It being the assizes at York, I met with Justice Hotham, a well-wisher to Friends,
who had been tender, and very kind to me from the first.

After I had finished my service for the Lord in York, I passed into the country.
As I went a great burthen fell upon me, but I did not presently know the reason of it.
I came to a meeting on First-day at Richard Shipton`'s, which was very large,
but there being one the same day at another place also, the priest of that place,
being misinformed that I was to be there, got a warrant,
and made great disturbance at that meeting; of which Isaac Lindley, who was there,
gave me an account in the following letter:--

[.salutation]
"`G. F.,

"`When thou went from York, the First-day after thou wast at Richard Shipton`'s,
that day I had appointed a meeting ten miles from York,
where there had not been one before.
But the priest and the constable got a warrant on the seventh day,
and put thy name only in the warrant, for they had heard that thou wast to be there.
They came with weapons and staves, and cried, '`Where is Mr. Fox?`'
over and over; many Friends being there, they concluded thou wast among them.
But those raveners, being disappointed, plucked me down and abused me,
and beat some Friends, and then took me before a magistrate, but he set me at liberty.`"

[.signed-section-signature]
Isaac Lindley.

Then I visited Friends at Whitby and Scarbro'`. When at Scarbro'`,
the governor hearing I was come, sent to invite me to his house, saying,
"`surely I would not be so unkind as not to come and see him and his wife.`"
After the meeting I went up to visit him,
and he received me very courteously and lovingly.

Having visited most of the meetings in Yorkshire, the Wolds, and Holderness,
I came to Henry Jackson`'s, where I had a great meeting.
Thence to Thomas Taylor`'s, and so to John Moor`'s at Eldreth,
where we had a very large meeting;
the Lord`'s power and presence were eminently amongst us.
Not far from this place lay Colonel Kirby, lame of the gout,
who had threatened that "`if ever I came near, he would send me to prison again;
and had bid forty pounds to any man that could take me;`" as I was credibly informed.

After this I came into Staffordshire, and Cheshire,
where we had many large and precious meetings.
I had a very large one at William Barnes`'s house, about two miles from Warrington;
and though Colonel Kirby was out again, as violent in breaking up meetings as before,
and was then at Warrington, the Lord did not suffer him to come to this meeting;
and so we were preserved out of his hands.
