== Chapter III.

[.chapter-synopsis]
* 1609-1671.
* George Fox sails for Ireland in company with several other Friends
* he there sends a challenge to the Popish priests to try their God, which is not accepted
* he contrasts them with Baal`'s priests
* the authorities of Cork threaten him, and issue warrants for his apprehension
* he rides publicly through the city, and is seen by the mayor but not molested
* writes to Friends in the ministry there
* discourses with professors on election and reprobation
* returns to England
* a report is spread that George Fox is turned Presbyterian, through a trick to obtain a congregation for John Fox, the Presbyterian, which however turns to the advantage of Friends
* George Fox is married to Margaret Fell at Bristol
* writes to the quarterly meetings about putting children apprentices
* Margaret Fox is cast into prison
* two of her daughters go to the king, and obtain a promise of their mother`'s liberty
* on the passing of the Conventicle Act, George Fox writes a declaration against seditious conventicles
* writes to Friends to strengthen them in their trials
* is apprehended at a meeting at Gracechurch Street
* taken before the mayor, who discourses with him and sets him at liberty
* visits Friends in Reading jail
* undergoes great travail of spirit, loses his sight and hearing, and becomes as a sign
* persecution becoming hot, some meetinghouses are pulled down, and Friends are much abused
* George Fox endures great mental conflict
* the faithfulness of Friends is said by some professors to have preserved the nation from debauchery
* George Fox writes an encouraging letter to Friends
* as persecution abates he recovers
* writes a warning to the rulers of the nation
* recommends certain regulations respecting marriage
* writes a prayer.

Now was I moved of the Lord to go over into Ireland,
to visit the seed of God in that nation.
There went with me Robert Lodge, James Lancaster, Thomas Briggs, and John Stubbs.
We waited near Liverpool for shipping and wind.
After waiting some days, we sent James Lancaster to take passage, which he did,
and brought word the ship was ready, and would take us in at Black Rock.
We went thither on foot; and it being some distance, and the weather very hot,
I was much spent with walking.
When we arrived, the ship was not there; so we were obliged to go to the town,
and take shipping.
When we were on board, I said to the rest of my company, "`Come,
ye will triumph in the Lord, for we shall have fair wind and weather.`"
Many passengers in the ship were sick, but not one of our company.
The captain and many of the passengers were very loving;
and we being at sea on the first day of the week,
I was moved to declare truth among them; whereupon the captain said to the passengers,
"`Here are things that you never heard in your lives.`"
When we came before Dublin, we took boat and went ashore; and the earth and air smelt,
methought, of the corruption of the nation,
so that it yielded another smell to me than England did;
which I imputed to the Popish massacres that had been committed,
and the blood that had been spilt in it, from which a foulness ascended.
We passed through among the officers of the custom four times,
yet they did not search us; for they perceived what we were:
some of them were so envious they did not care to look at us.
We did not soon find Friends; but went to an inn, and sent out to inquire for some;
who when they came to us were exceedingly glad of our coming,
and received us with great joy.
We stayed there the weekly meeting, which was a large one,
and the power and life of God appeared greatly in it.
Afterwards we passed to a province meeting, which lasted two days,
there being one about the poor, and another meeting more general;
in which a mighty power of the Lord appeared.
Truth was livingly declared, and Friends were much refreshed therein.

Passing thence about four and twenty miles, we came to another place,
where we had a very good refreshing meeting; but after it,
some Papists that were there were angry, and raged very much.
When I heard of it, I sent for one of them, who was a schoolmaster; but he would not come.
Whereupon I sent a challenge to him, with all the friars and monks, priests and Jesuits,
to come forth, and "`try their God and their Christ,
which they had made of bread and wine,`" but no answer could I get from them.
Wherefore I told them, "`they were worse than the priests of Baal;
for Baal`'s priests tried their wooden god,
but these durst not try their god of bread and wine;
and Baal`'s priests and people did not eat their god as these did,
and then make another.`"

We went to New Garden, where there was a great meeting.
Thence we travelled on among Friends, till we came to Bandon Bridge and the Land`'s End,
having many meetings as we went, in which the mighty power of the Lord was manifested,
Friends were well refreshed, and many people were affected with the truth.
At Bandon, the mayor`'s wife being herself convinced,
desired her husband to come to the meeting; but he bid her, for her life,
not to make known that I was at a meeting there.

He that was then mayor of Cork was very envious against truth and Friends,
and had many Friends in prison; and knowing that I was in the country,
he had issued four warrants to take me;
wherefore Friends were desirous that I might not ride through Cork.
But being at Bandon, there appeared to me, in a vision, "`a very ugly visaged man,
of a black and dark look: my spirit struck at him in the power of God;
and it seemed to me, that I rode over him with my horse,
and my horse set his foot on the side of his face.`"
When I came down in the morning, I told a friend that was with me,
that the command of the Lord was to me to ride through Cork; but bid him tell no man.
So we took horse, many Friends being with me; and when we came near the town,
they would have showed me a way on the backside of the town; but I told them,
my way was through the streets.
Wherefore taking one of them along with me, whose name was Paul Morrice,
to guide me through the town, I rode on; and as we rode through the market-place,
and by the mayor`'s door, he seeing me ride by, said,
"`there goes George Fox;`" but he had not power to stop me.
When we had passed through the sentinels, and were come over the bridge,
we went to a Friend`'s house and alighted.
There the Friends told me what a rage was in the town,
and how many warrants were granted to take me.
While I was sitting there with Friends, I felt the evil spirit at work in the town,
stirring up mischief against me;
and I felt the power of the Lord strike at that evil spirit.
By and by some other Friends coming in, told me that it was over the town,
and amongst the magistrates, that I was in the town.
I said, "`let the devil do his worst.`"
After a while, that Friends were refreshed one in another,
and we travellers had refreshed ourselves, I called for my horse,
and having a Friend to guide me, we went on our way.
But great was the rage, that the mayor and others of Cork were in,
that they had missed me; and great pains they afterwards took to take me,
having their scouts abroad upon the roads, as I understood, to observe which way I went.
Afterwards there was scarcely a public meeting I came to,
but spies came to watch if I were there.
And the envious magistrates and priests sent informations one to another concerning me,
describing me by my hair, hat, clothes, and horse,
so that when I was near a hundred miles from Cork, they had an account concerning me,
and description of me, before I came amongst them.
One very envious magistrate, who was both a priest and a justice,
got a warrant from the judge of the assize to apprehend me;
which warrant was to go over all his circuit, which reached near a hundred miles.
Yet the Lord disappointed all their counsels, and defeated all their designs against me;
by his good hand of Providence preserved me out of all their snares,
and gave us many sweet and blessed opportunities to visit Friends,
and spread truth through that nation.
For meetings were very large, Friends coming to them far and near;
and other people flocking in.
The powerful presence of the Lord was preciously felt with and amongst us;
whereby many of the world were reached, convinced, and gathered to the truth;
the Lord`'s flock was increased,
and Friends were greatly refreshed and comforted in feeling the love of God.
O, the brokenness that was amongst them in the flowings of life!
So that, in the power and Spirit of the Lord, many together broke out into singing,
even with audible voices, making melody in their hearts.

[.offset]
At which time I was moved to declare to Friends in the ministry, as follows:--

[.embedded-content-document.epistle]
--

"`Sound, sound abroad, ye faithful servants of the Lord, and witnesses in his name,
ye prophets of the Highest, and angels of the Lord!
Sound ye all abroad in the world, to the awakening and raising of the dead,
that they may be awakened, and raised up out of the grave,
to hear the voice that is living.
For the dead have long heard the dead, the blind have long wandered among the blind,
and the deaf amongst the deaf.
Therefore sound, ye servants, prophets, and angels of the Lord, ye trumpets of the Lord,
that you may awaken the dead, and them that are asleep in their graves of sin,
death and hell, sea and earth, and who lie in the tombs.
Sound abroad, ye trumpets, and raise up the dead,
that they may hear the voice of the Son of God, of the second Adam that never fell;
the voice of the Light and of the Life; the voice of the Power,
and the voice of the Truth; the voice of the Righteous, and of the Just.
Sound ye the trumpets, the melodious sound abroad,
that all the deaf ears may be opened to hear the
pleasant sound of the trumpet to judgment and life,
to condemnation and light.
Sound your trumpets all abroad, ye angels of the Lord, sons and daughters,
prophets of the Highest,
that all who are dead and asleep in the graves--
who have been long dreaming and slumbering,
may be awakened,
and hear the voice of the Lamb;--that all who have long heard the voice of the beast,
may now hear the voice of the Bridegroom and of the Bride;--that they may now hear
the voice of the great Prophet and King--the Shepherd and Bishop of their souls.
Sound, sound it all abroad, ye trumpets, among the dead in Adam; for Christ is come,
the second Adam, that they might have life, yea have it abundantly.
Awaken the dead, awaken the slumberers, the dreamers, them that are asleep,
awaken them out of their graves, out of their tombs, out of their sepulchres,
out of the seas!
Sound abroad, ye trumpets that awaken the dead,
that they may all hear the sound of it in the graves, and they that hear may live,
and come to the Life, that is, the Son of God.
He is risen from the dead; the grave could not hold nor contain him,
neither could all the watchers of the earth, with all their guards, keep him therein.
Sound, ye trumpets of the Lord, to all the seekers of the living among the dead,
that he is risen from the dead; to all the seekers of the living among the dead,
and in the graves that the watchers keep; he is not in the grave, he is risen;
there is that under the grave of the watchers of the outward grave,
which must be awakened and come to hear His voice, who is risen from the dead,
that they may come to live.
Therefore sound abroad, ye trumpets of the Lord, that the grave may give up her dead,
and hell and the sea give up their dead; that all may come forth to judgment,
to the judgment of the Lord before his throne,
and have their sentence and reward according to their works.`"

[.signed-section-signature]
G+++.+++ F.

--

To James Hutchinson`'s in Ireland came many great persons,
desiring to discourse with me about election and reprobation.
I told them, "`though they judged our principle foolish, it was too high for them,
they could not with their wisdom comprehend it;
therefore I would discourse with them according to their capacities.
You say (said I), that God hath ordained the greatest part of men for hell,
and that they were ordained so before the world began; for which your proof is in Jude.
You say Esau was reprobated, and the Egyptians, and the stock of Ham.
But Christ saith to his disciples, '`Go,
teach all nations,`' and '`go into all nations and
preach the gospel of life and salvation.`'
Now, if they were to go to all nations,
were they not to go to Ham`'s stock and Esau`'s stock?
Did not Christ die for all?
then for the stock of Ham, of Esau, and the Egyptians.
Doth not the Scripture say, God would have all men to be saved?`'
Mark, all men, then the stock of Esau and of Ham also.
Doth not God say, '`Egypt, my people?`'
and that he would have an altar in Egypt? Isa. 19.
Were there not many Christians formerly in Egypt?
And doth not history say, that the Bishop of Alexandria would formerly have been Pope?
And had not God a church in Babylon?
I confess, '`the word came to Jacob, and the statutes to Israel;
the like was not to other nations.`'
For the law of God was given to Israel; but the gospel was to be preached to all nations,
and is to be preached.
The gospel of peace and glad tidings to all nations, '`he that believes, is saved;
but he that doth not believe,
is condemned already;`' so the condemnation comes through unbelief.
And whereas Jude speaks of some,
that were of old ordained (or written of before) to condemnation, he doth not say,
before the world began; but, '`written of old,`' which may be referred to Moses`'s writings,
who wrote of those whom Jude mentions, namely, Cain, Korah, Balaam,
and the angels that kept not their first estate.
And such Christians as followed them in their way,
and apostatized from the first state of Christianity,
were and are ordained for condemnation by the light and truth, which they are gone from.
And though the apostle speaks of God`'s loving Jacob and hating Esau;
yet he tells the believers, '`we all were by nature children of wrath as well as others.`'
This includes the stock of Jacob,
of which the apostle himself and all believing Jews were.
Thus both Jews and Gentiles were all concluded under sin, and so under condemnation,
that God might have mercy upon all, through Jesus Christ.
The election and choice stands in Christ; and '`he that believes, is saved;
and he that believes not, is condemned already.`'
Jacob typifies the second birth, which God loved;
and both Jews and Gentiles must be born again, before they can enter the kingdom of God.
When you are born again, ye will know election and reprobation;
for the election stands in Christ, the Seed, before the world began;
but the reprobation lies in the evil seed, since the world began.`"
After this manner, but somewhat more largely,
I discoursed with those great persons on this matter,
and they confessed they had never heard so much before.

After I had travelled over Ireland, and had visited Friends in their meetings,
as well for business as for worship,
and had answered several papers and writings from monks, friars,
and Protestant priests (for they all were in a rage against us,
and endeavoured to stop the work of the Lord;
and some Jesuits swore in the hearing of some of us,
that we came to spread our principles in that nation, but we should not do it),
I returned to Dublin to take passage for England.
When I had stayed the First-day meeting there (which was very large and precious),
a ship being ready and the wind serving, we took our leave of Friends,
parting in much tenderness and brokenness, in the sense of the heavenly life and power,
manifested amongst us.
So having put our horses and necessaries on board in the morning,
we went ourselves in the afternoon, many Friends accompanying us to the ship; and divers,
both Friends and friendly people,
came after us in boats when we were near a league at sea, their love drawing them,
though not without danger.
A good, weighty, and true people there is in that nation,
sensible of the power of the Lord God and tender of his truth;
and very good order they have in their meetings,
for they stand up for righteousness and holiness, which dams up the way of wickedness.
A precious visitation they had, and there is an excellent spirit in them,
worthy to be visited.
Many things more I could write of that nation, and of my travels in it,
which would be large to mention particularly; but this I have thought good to signify,
that the righteous may rejoice in the prosperity of truth.

James Lancaster, Robert Lodge, and Thomas Briggs came back with me;
John Stubbs having further service there, stayed behind.
We were two nights at sea; in one of which a mighty storm arose,
that put the vessel in great danger.
But I saw the power of God went over the winds and storms; he had them in his hand,
and his power bound them.
And the same power of the Lord God which carried us over, brought us back again;
and in his life gave us dominion over all the evil spirits that opposed us there.

We landed at Liverpool, and went to Richard Johnson`'s. Whence departing the next day,
we passed to William Barnes`'s house, and so to William Gandy`'s, visiting Friends,
and having many precious meetings in Lancashire and Cheshire.
When we came into Gloucestershire, we met with a report at Nailsworth,
which was spread about that country, "`that George Fox was turned Presbyterian;
that they had prepared a pulpit for him, and set it in a yard,
and that there would be a thousand people there the next day to hear him.`"
I thought it strange that such a report should be raised of me; yet as we went further,
from one Friend`'s house to another, we met with the same.
We passed by the yard where the pulpit was, and saw it,
and went on to the place where Friends`' meeting was to be next day,
and there we stayed that night.
Next day, being First-day, we had a very large meeting,
and the Lord`'s power and presence were amongst us.

The occasion of this strange report (as I was informed) was this.
There was one John Fox, a Presbyterian priest, who used to go about preaching;
and some changing his name (as was reported) from John to George,
gave out that George Fox had changed his religion,
and was turned from a Quaker to be a Presbyterian,
and would preach at such a place such a day.
This begot so great a curiosity in the people,
that many went thither to hear this Quaker turned Presbyterian,
who would not have gone to hear John Fox himself.
By this means, it was reported, they had got together above a thousand people.
But when they came there, and perceived they had a trick put upon them,
and that he was but a counterfeit George Fox,
and understood that the real George Fox was hard by,
several hundreds of them came to our meeting, and were sober and attentive.
I directed them to the grace of God in themselves, which would teach them,
and bring them salvation.
When the meeting was over, some of the people said,
"`they liked George Fox the Quaker`'s preaching better
than George Fox the Presbyterian`'s.`" Thus,
by my providential coming into those parts at that time,
was this false report discovered; and shame came over the contrivers of it.

Not long after this, John Fox was complained of in the House of Commons,
for "`having a tumultuous meeting,
in which treasonable words were spoken;`" which (according to the best information
I could get of it) was thus:--He had formerly been priest of Mansfield in Wiltshire;
and being put out of that place,
was afterwards permitted by a Common-Prayer
priest to preach sometimes in his steeple-house.
At length this Presbyterian priest,
presuming too far upon the parish priest`'s former grant,
began to be more bold than welcome, and attempted to preach there,
whether the parish priest would or not.
This caused a great bustle and contest in the steeple-house between the two priests,
and their hearers, on each side;
in which contest the Common-Prayer-Book was cut to pieces,
and some treasonable words were spoken by some of the followers of John Fox.
This was quickly put in the news;
and some malicious Presbyterians caused it to be worded
as if it had proceeded from George Fox the Quaker,
when I was above two hundred miles from the place where this bustle happened.
When I heard of it,
I soon procured certificates from some of the members of the House of Commons,
who knew this John Fox, and gave it under their hands, that it was John Fox,
who had formerly been parson of Mansfield in Wiltshire,
that was complained of to the House of Commons,
to be the chief ringleader in that unlawful assembly.

And indeed this John Fox discovered himself to be an ill man; for when some,
who had been his followers, came to be convinced of truth, and thereupon left him,
he came to some of their houses to talk with them about it, and they telling him,
"`he was in the steps of the false prophets, preaching for hire and filthy lucre,
like them whom Christ cried woe against, and the apostles declared against,
such as served not the Lord Jesus Christ, but their own bellies; and telling him also,
Christ said, '`freely ye have received,
freely give;`' and therefore he should not take money of people for preaching,
especially now times were so hard;`" he replied, "`God bless preaching,
for that brings in money, let times go how they will.
Fill my belly with good victuals; and then call me false prophet, or what you will,
and kick me about the house when ye have done, if ye will.`"
This relation I had from a man and his wife, who had been formerly his hearers,
and whom this John Fox, with others, caused deeply to suffer.
For he and some other Presbyterian priests, using to resort to a widow-woman`'s house,
who had the impropriation, and took the tithes of the parish, she told them,
there was a Quaker in that parish that would not pay her tithes,
and asked what she should do with him.
They advised her "`to send workmen to cut down and carry away his corn;`" which she did,
and thereby impoverished the man.
But to proceed--

After this meeting in Gloucestershire was over, we travelled till we came to Bristol;
where I met with Margaret Fell, who was come to visit her daughter Yeomans.
I had seen from the Lord a considerable time before,
that I should take Margaret Fell to be my wife.
And when I first mentioned it to her, she felt the answer of Life from God thereunto.
But though the Lord had opened this thing to me,
yet I had not received a command from the Lord for the accomplishing of it then.
Wherefore I let the thing rest,
and went on in the work and service of the Lord as before, according as he led me;
travelling up and down in this nation, and through Ireland.
But now being at Bristol, and finding Margaret Fell there, it opened in me from the Lord,
that the thing should be accomplished.
After we had discoursed the matter together, I told her,
"`if she also was satisfied with the accomplishing of it now,
she should first send for her children;`" which she did.
When the rest of her daughters were come, I asked both them and her sons-in-law,
"`if they had anything against it,
or for it;`" and they all severally expressed their satisfaction therein.
Then I asked Margaret,
"`if she had fulfilled and performed her husband`'s will to her children.`"
She replied, "`the children knew that.`"
Whereupon I asked them, "`whether, if their mother married, they should not lose by it?`"
And I asked Margaret, "`whether she had done anything in lieu of it,
which might answer it to the children?`"
The children said, "`she had answered it to them, and desired me to speak no more of it.`"
I told them, "`I was plain, and would have all things done plainly;
for I sought not any outward advantage to myself.`"
So after I had thus acquainted the children with it,
our intention of marriage was laid before Friends, both privately and publicly,
to their full satisfaction, many of whom gave testimony thereunto that it was of God.
Afterwards, a meeting being appointed for the accomplishing thereof,
in the meetinghouse at Broad-Mead in Bristol, we took each other,
the Lord joining us together in the honourable marriage,
in the everlasting covenant and immortal Seed of life.
In the sense whereof, living and weighty testimonies were borne thereunto by Friends,
in the movings of the heavenly power which united us together.
Then was a certificate, relating both the proceedings and the marriage, openly read,
and signed by the relations, and by most of the ancient Friends of that city,
besides many others from divers parts of the nation.^
footnote:[The date of the marriage of George Fox and Margaret Fell,
in the Bristol Register of Friends, is 27th of 8th Month, 1669.
{footnote-paragraph-split}
Margaret Fell, it will be remembered,
was the widow of Judge Fell of Swarthmore Hall.
It is remarkable with what high esteem and Christian love this devoted woman
appears to have been regarded by our early and most eminent Friends.
She seems to have been generally acknowledged as a faithful nursing-mother of the flock;
and she often addressed them, when in bonds or otherwise,
with letters of consolation and encouragement.
(See numerous letters to and from her in Barclay`'s _Letters, etc, of Early Friends_).
It is also probable she contributed largely
from her means to the relief of their outward necessities.
Having faithfully fulfilled her allotted labours, she died much beloved and lamented,
at her own house at Swarthmore, in 1702, being near the eighty-eighth year of her age,
and having survived George Fox about twelve years.
{footnote-paragraph-split}
Some remarkable expressions of assured
happiness fell from her lips during her last illness,
if that could be called an illness, which was the decay of nature.
At one time, under the meltings of heavenly love, she said,
"`Oh my sweet Lord! into thy holy bosom do I commit myself freely;
not desiring to live in this troublesome,
painful world--it is all nothing to me--for my Maker is my husband.`"
A little before her departure she called her daughter Rachel to her, saying,
"`Take me in thy arms`"--after which she said, "`I am in peace!`"]

We stayed about a week in Bristol, and then went together to Oldstone;
where taking leave of each other in the Lord, we parted,
betaking ourselves to our several services, Margaret returning homewards to the north,
and I passing on in the work of the Lord, as before.
I travelled through Wiltshire, Berkshire, Oxfordshire, and Buckinghamshire,
and so to London, visiting Friends;
in all which counties I had many large and precious meetings.

Being in London, it came upon me to write to Friends throughout the nation,
about "`putting out poor children to trades.`"
Wherefore I sent the following epistle to the
quarterly meetings of Friends in all counties:--

[.embedded-content-document.epistle]
--

[.salutation]
"`My Dear Friends,

"`Let every quarterly meeting make inquiry through all the monthly and other meetings,
to know all Friends that are widows, or others,
that have children fit to put out to apprenticeships;
so that once a quarter you may set forth an apprentice from your quarterly meeting;
and so you may set forth four in a year in each county, or more, if there be occasion.
This apprentice, when out of his time, may help his father or mother,
and support the family that is decayed; and in so doing,
all may come to live comfortably.
This being done in your quarterly meetings,
ye will have knowledge through the county in the monthly and particular meetings,
of masters fit for them, and of such trades as their parents or you desire,
or the children are most inclinable to.
Thus being placed out with Friends, they may be trained up in truth;
and by this means in the wisdom of God, you may preserve Friends`' children in the truth,
and enable them to be a strength and help to their families,
and nursers and preservers of their relations in their ancient days.
Thus also things being ordered in the wisdom of God,
you will take off a continual maintenance, and free yourselves from much cumber.
For in the country, ye know,
ye may set forth an apprentice for a little to several trades, as bricklayers, masons,
carpenters, wheelrights, ploughwrights, tailors, tanners, curriers, blacksmiths,
shoemakers, nailers, butchers, weavers of linen and woollen, stuffs and serges, etc.
And you may do well to have a stock in your quarterly meetings for that purpose.
All that is given by any Friends at their decease
(except it be given to some particular use,
person, or meeting), may be brought to the public stock for that purpose.
This will be a way for the preserving of many that are poor among you,
and it will be a way of making up poor families.
In several counties it is practised already.
Some quarterly meetings set forth two apprentices;
and sometimes the children of others that are laid on the parish.
You may bind them for fewer or more years, according to their capacities.
In all these things the wisdom of God will teach you,
by which ye may come to help the children of poor Friends,
that they may come to support their families, and preserve them in the fear of God.
So no more, but my love in the everlasting Seed,
by which ye will have wisdom to order all things to the glory of God.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, 1st of 11th Month, 1669.

--

I stayed not long in London; but having visited Friends,
and finding things there quiet and well, the Lord`'s power being over all,
I passed into Essex, and Hertfordshire, where I had many precious meetings.
Intending to go as far as Leicestershire, I wrote a letter to my wife,
before I left London, to acquaint her therewith,
that if she found it convenient to her she might meet me there.
From Hertfordshire I turned into Cambridgeshire, thence into Huntingdonshire,
and so into Leicestershire; where, instead of meeting with my wife,
I heard that she was haled out of her house to Lancaster prison again,
by an order obtained from the king and council,
to fetch her back to prison upon the old premunire;
though she had been discharged from that imprisonment by their order the year before.
Wherefore, having visited Friends as far as Leicestershire,
I returned by Derbyshire into Warwickshire, and so to London,
having had many large and blessed meetings in the several counties I passed through,
and been sweetly refreshed amongst Friends in my travels.

As soon as I reached London,
I hastened Mary Lower and Sarah Fell (two of my wife`'s daughters) to the king,
to acquaint him how their mother was dealt with,
and see if they could obtain a full discharge for her,
that she might enjoy her estate and liberty without molestation.
This was somewhat difficult, but by diligent attendance they at length obtained it;
the king giving command to Sir John Otway,
to signify his pleasure therein by letter to the sheriff,
and others concerned therein in the country.
Which letter Sarah Fell going down with her brother and sister Rous,
carried with her to Lancaster; and by them I wrote to my wife, as follows:--

[.embedded-content-document.letter]
--

[.salutation]
"`My Dear Heart In The Truth And Life, That Changeth Not,

It was upon me that Mary Lower and Sarah should
go to the king concerning thy imprisonment,
and to Kirby, that the power of the Lord might appear over them all in thy deliverance.
They went, and then they thought to come down;
but it was upon me to stay them a little longer,
that they might follow the business till it was effected; which it now is,
and is here sent.
The late declaration of mine hath been very serviceable,
people being generally satisfied with it.
So no more, but my love in the holy Seed.`"

[.signed-section-signature]
G+++.+++ F.

--

The declaration here mentioned was a printed sheet,
written upon occasion of a new persecution stirred up.
For by the time I was returned out of Leicestershire to London, a fresh storm was risen,
occasioned (it was thought) by that tumultuous meeting
in a steeple-house in Wiltshire or Gloucestershire,
mentioned a little before; from which, it was said,
some members of parliament took advantage to get
an act passed against seditious conventicles;^
footnote:[The "`Conventicle Act`" so called, first passed in 1664,
was renewed at the above time (1670), with increased rigour.
The penalties were £5, or three months to the house of correction,
for the first offence of attending a conventicle, if above sixteen years of age; £10,
or six months, for the second; _transportation_ for seven years for the third,
with sequestration of estate, or distraint for the charges;
and _five years`' slavery in the colonies,_ by contract between the sheriff and a purchaser,
on being sent abroad, in defect of property to distrain upon;
_or out of which to pay £100 as a liberating fine._
This fine to be repeated, and £100 added as oft as he should offend afterwards,
or _transportation,_ etc. (with _death_ for returning),
and the forfeiture of his _life-interest in his estate._
{footnote-paragraph-split}
_Conventicles to be broken up by an armed force,_
under the direction of lieutenants of counties, sheriffs, etc.
Even a _femme covert_ could not escape; but must be redeemed by her husband,
at the price of £40; or go to prison, or be transported with him.
Nor could a _peer of the realm:_ he must be fined £10 for the first offence,
£20 for the second, and for the third, be tried by his peers.
The fines to be levied by distress, by warrant of any two justices,
or a chief magistrate.
{footnote-paragraph-split}
The force of this Act was directed against the _Quakers,_
by inserting, in the latter part of it, three sections,
which brought _their refusal to take an oath_ under its full penalties;
and they suffered dreadfully through it!
In the streets, or where they met to assert their religious rights,
they were dragooned; in court they had oaths tendered,
and were convicted under this Act upon their refusal.
{footnote-paragraph-split}
"`This Act,`" says Besse,
"`was forthwith put into a rigorous execution,
and many hungry informers +++[+++for the sake of their _third_ of the penalties+++]+++
_made it their business_ to live upon the spoil and ruin of conscientious people.`"
Friends were great sufferers thereby,
of the nature of which the reader may have some idea by reference to
"`Sufferings under the Conventicle Act;`" _Select Miscellanies,_ vol. iii., pp. 220-245.]
which soon after came forth and was turned against us,
who of all people were free from sedition and tumult.
Whereupon I wrote a declaration, showing from the preamble and terms of the act,
that we were not such a people, nor our meeting such as were described in that act.
I wrote also another short paper on the occasion of that act against meetings,
opening our case to the magistrates, as follows:--

[.embedded-content-document.paper]
--

"`O Friends, consider this act, which limits us to five.
Is this doing as ye would be done by?
Would ye be so served yourselves?
We own Christ Jesus as well as you, his coming, death, and resurrection;
and if we be contrary-minded to you in some things,
is not this the apostle`'s exhortation, '`to wait till God hath revealed it?`'
Doth not he say, '`what is not of faith, is sin?`'
Seeing we have not faith in things, which ye would have us to do,
would it not be sin in us, if we should act contrary to our faith?
Why should any man have power over another man`'s faith, seeing Christ is the author of it?
When the apostles preached in the name of Jesus, and great multitudes heard them,
and the rulers forbade them to speak any more in that name,
did not they bid them judge whether it were better to obey God or man?
Would not this act have taken hold of the twelve apostles and seventy disciples;
for they met often together?
If there had been a law made then, that not above five should have met with Christ,
would not that have been a hindering of him from meeting with his disciples?
Do ye think that He, who is the wisdom of God, or his disciples, would have obeyed it?
If such a law had been made in the apostles`' days,
that not above five might meet together,
who had been different minded from either the Jews or the Gentiles,
do ye think the churches of Christ at Corinth, Philippi, Ephesus, Thessalonica,
or the rest of the gathered churches, would have obeyed it?
O therefore consider! for we are Christians, and partake of the nature and life of Christ.
Strive not to limit the Holy One; for God`'s power cannot be limited,
and is not to be quenched.
Do unto all men as ye would have them do unto you; for that is the law and the prophets.`"

"`This is from those who wish you all well,
and desire your everlasting good and prosperity, called Quakers;
who seek the peace and good of all people, though they afflict us,
and cause us to suffer.`"

[.signed-section-signature]
G+++.+++ F.

--

As I had endeavoured to soften the magistrates,
and to take off the sharpness of their edge in the execution of the act,
so it was upon me to write a few lines to Friends "`to
strengthen and encourage them to stand fast in their testimony,
and bear, with Christian patience and content, the suffering that was coming upon them.`"
This I did in the following epistle:--

[.embedded-content-document.epistle]
--

"`My dear Friends, Keep in the faith of God above all outward things, and in his power,
that hath given you dominion over all.
The same power of God is still with you to deliver you as formerly;
for God and his power is the same; his Seed is over all, and before all; and will be,
when that which makes to suffer, is gone.
Be of good faith in that which changeth not; for whatsoever any do against the truth,
it will come upon themselves, and fall as a millstone on their heads.
If the Lord suffer you to be tried, let all be given up;
and look at the Lord and his power, which is over the whole world,
and will remain when the world is gone.
In the Lord`'s power and truth rejoice over that which makes to suffer, in the Seed,
which was before it was; for the life, truth, and power of God is over all.
All keep in that; and if ye suffer in that, it is to the Lord.

"`Friends, the Lord hath blessed you in outward things; and now the Lord may try you,
whether your minds be in outward things, or with the Lord that gave you them?
Therefore keep in the Seed, by which all outward things were made,
and which is over them all.
What! shall not I pray, and speak to God, with my face towards heavenly Jerusalem,
according to my wonted time?
Let not any one`'s Delilah shave his head, lest he lose his strength;
neither rest in its lap, lest the Philistines be upon you.
For your rest is in Christ Jesus; therefore rest not in anything else.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, 12th of 2nd Month, 1670.

--

On the First-day after the act came in force,
I went to the meeting at Grace-church-street,
where I expected the storm was most likely to begin.
When I came there, I found the street full of people,
and a guard set to keep Friends out of their meetinghouse.
I went to the other passage out of Lombard Street, where also I found a guard;
but the court was full of people, and a Friend was speaking amongst them;
but he did not speak long.
When he had done, I stood up, and was moved to say, "`Saul, Saul, why persecutest thou me?
it is hard for thee to kick against that which pricks thee.
Then I showed that it is Saul`'s nature that persecutes still,
and that they who persecute Christ in his members now, where he is made manifest,
kick against that which pricks them.
That it was the birth of the flesh that persecuted the birth born of the Spirit;
and that it was the nature of dogs to tear and devour the sheep,
but that we suffered as sheep that bite not again; for we were a peaceable people,
and loved them that persecuted us.`"
After I had spoken a while to this effect,
the constable came with an informer and soldiers; and as they pulled me down, I said,
"`Blessed are the peacemakers.`"
The commander of the soldiers put me among the soldiers, and bid them secure me,
saying to me, "`You are the man I looked for.`"
They took also John Burnyeat and another Friend, and led us away first to the Exchange,
and afterwards towards Moorfields.
As we went along the streets the people were very moderate;
some of them laughed at the constable, and told him, "`we would not run away.`"
The informer went with us unknown, till falling into discourse with one of the company,
he said, "`It would never be a good world till all people came to the
good old religion that was two hundred years ago.`"
Whereupon I asked him, "`Art thou a Papist?
What! a Papist informer;
for two hundred years ago there was no other religion but that of the Papists.`"
He saw he had ensnared himself, and was vexed at it; for as he went along the streets,
I spoke often to him, and manifested what he was.
When we were come to the mayor`'s house, and were in the court-yard,
several of the people that stood about, asked me, "`how and for what I was taken?`"
I desired them to ask the informer, and also know what his name was;
but he refused to tell his name.
Whereupon one of the mayor`'s officers looking out at a window, told him,
"`he should tell his name before he went away;
for the lord mayor would know by what authority he intruded himself with soldiers
into the execution of those laws which belonged to the civil magistrate to execute,
and not to the military.`"
After this, he was eager to be gone; and went to the porter to be let out.
One of the officers called to him, saying,
"`Have you brought people here to inform against,
and now will you go away before rny lord mayor comes?`"
Some called to the porter not to let him out; whereupon he forcibly pulled open the door,
and slipped out.
No sooner was he come into the street, than the people gave a shout,
that made the street ring again, crying out, "`a Papist informer! a Papist informer!`"
We desired the constable and soldiers to go and rescue him out of the people`'s hands,
fearing lest they should do him a mischief.
They went, and brought him into the mayor`'s entry, where they stayed a while;
but when he went out again, the people received him with another shout.
The soldiers were fain to go and rescue him once more,
and they led him into a house in an alley,
where they persuaded him to change his periwig, and so he got away unknown.

When the mayor came, we were brought into the room where he was,
and some of his officers would have taken off our hats, which he perceiving,
called to them, and bid them, "`let us alone, and not meddle with our hats;
for,`" said he, "`they are not yet brought before me in judicature.`"
So we stood by while he examined some Presbyterian and Baptist teachers;
with whom he was somewhat sharp, and convicted them.
After he had done with them, I was brought up to the table where he sat;
and then the officers took off my hat; and the mayor said mildly to me, "`Mr. Fox,
you are an eminent man amongst those of your profession; pray,
will you be instrumental to dissuade them from meeting in such great numbers?
for, seeing Christ hath promised that where two or three are met in his name,
he will be in the midst of them,
and the king and parliament are graciously pleased to
allow of four to meet together to worship God;
why will not you be content to partake both of Christ`'s promise to two or three,
and the king`'s indulgence to four?`"
I answered to this purpose:
"`Christ`'s promise was not to discourage many from meeting together in his name,
but to encourage the few, that the fewest might not forbear to meet,
because of their fewness.
But if Christ hath promised to manifest his
presence in the midst of so small an assembly,
where but two or three were gathered in his name,
how much more would his presence abound where
two or three hundred are gathered in his name?
I wished him to consider, whether this act would not have taken hold of Christ,
with his twelve apostles and seventy disciples, if it had been in their time,
who used to meet often together, and that with great numbers?
However, I told him this act did not concern us;
for it was made against seditious meetings, of such as met,
under colour and pretence of religion, to contrive insurrections,
as (the act says) late experience had shown but we had been sufficiently tried and proved,
and always found peaceable,
and therefore he should do well to put a
difference between the innocent and the guilty.`"
He said, "`the act was made against meetings,
and a worship not according to the liturgy.`"
I told him, "`according to`" was not the very same thing: and I asked him,
"`whether the liturgy was according to the Scriptures?
and whether we might not read Scriptures, and speak Scriptures?`"
He said "`Yes.`"
I told him, "`this act took hold only of such, as met to plot and contrive insurrections,
as late experience had shown; but they had never experienced that by us.
Because thieves are sometimes on the road, must not honest men travel?
And because plotters and contrivers have met to do mischief, must not an honest,
peaceable people meet to do good?
If we had been a people that met to plot and contrive insurrections, etc.,
we might have drawn ourselves into fours;
for four might do more mischief in plotting than if there were four hundred,
because four might speak out their minds more
freely one to another than four hundred could.
Therefore, we being innocent, and not the people this act concerns,
we keep our meetings as we used to do: and, I said,
I believed that he knew in his conscience we were innocent.`"
After some more discourse, he took our names and the places where we lodged,
and at length, as the informer was gone, set us at liberty.

Being set at liberty, the Friends with me asked me "`whither I would go?`"
I told them, "`to Gracechurch Street meeting again, if it were not over.`"
When we came there, the people were generally gone; only some few stood at the gate.
We went into Gerrard Roberts`'s house;
and from thence I sent out to know how the other meetings in the city were.
I understood that at some of the meeting-places Friends were kept out;
at others they were taken, but set at liberty again a few days after.
A glorious time it was, for the Lord`'s power came over all,
and his everlasting truth got renown.
For as fast as some that were speaking were taken down,
others were moved of the Lord to stand up and speak, to the admiration of the people;
and the more, because many Baptists and other sectaries left their public meetings,
and came to see how the Quakers would stand.
As for the informer aforesaid, he was so frightened,
that there durst hardly any informer appear publicly again in London for some time after.
But the mayor, whose name was Samuel Starling,
though he carried himself smoothly towards us,
proved afterwards a very great persecutor of our Friends,
many of whom he cast into prison, as may be seen in the trials of W. Penn, W. Mead,
and others, at the Old Bailey this year^
footnote:[The celebrated trial of Penn and Mead at the Old Bailey, above alluded to,
may be seen at full length in Clarkson`'s _Life of Penn_--"`a trial which,
for the good it has done to posterity,
ought to be engraved on tablets of the most durable marble.`"
It was certainly one of those events which, in conjunction with others of a similar sort,
by showing the inadequacy of punishment for religion to its supposed end,
not only corrected and improved the notions of succeeding ages in this respect, but,
by so doing, lessened the ravages of persecution, and the enmity between man and man.
Nor ought posterity to be less grateful for it as a monument
of the ferocity and corrupt usages of former times;
for, contrasting these with the notions and customs of our own age,
we see the improvement of our social and moral condition.
Newgate is no longer the receptacle of innocent
individuals suffering for conscience`' sake.
In our courts of law we see an order, a decorum, and an administration of justice,
unknown at the period of this memorable trial.
Nor will the prospect be less grateful, if we quit the present for a moment,
and direct our eyes to the future.
We have the best reason to hope, on contemplating the signs of the times,
that the day is rapidly approaching when the Christian religion,
which is capable of cementing men in the strongest possible union,
and for the noblest purposes,
will be stripped of its mischievous appendages--restored to its primitive purity,
and made a blessing to all the dwellers upon the earth.]

After some time the heat of persecution in London began to abate,
and meetings were quieter there.
Being now clear of the city, I went to visit Friends in the country;
and attended several meetings in Middlesex, Buckinghamshire, and Oxfordshire,
which were quiet, though in some places there was much threatening.
At Reading most of the Friends were in prison, and I went to visit them.
When I had been a while with them, the Friends that were prisoners gathered together,
and several other persons came in; so that I had a fine opportunity amongst them,
and "`declared the Word of Life, encouraging them in the truth;
and they were refreshed in feeling the presence and power of the Lord amongst them.`"
When the meeting was ended, the jailer understanding that I was there,
the Friends were concerned how to get me out safe again;
for they feared lest he should stop me.
But after I had stayed a while, and eaten with them, I went downstairs,
and the jailer being at the door, I put my hand in my pocket,
which he had such an eye to, hoping to get something off me,
that he asked me no question.
So I gave him something, and bade him "`be kind and civil to my Friends in prison,
whom I came to visit;`" and he let me pass out without interruption.
But soon after Isaac Penington coming to visit them, he stopped him,
and caused him to be made a prisoner.^
footnote:[Isaac Penington has been mentioned before, but only cursorily,
in the whole of this Journal.
Little is known of his history,
beyond what is to be gathered from testimonies given forth concerning him at his death,
and a few other incidental notices of him.
He was well descended as to his worldly parentage,
being the eldest son of Alderman Pennington,
who was two years successively Mayor of London,
and a noted member of the Long Parliament.
Born about the year 1617, he received a liberal education, having, according to Penn,
"`all the advantages the schools and universities of his own country could give,
joined with the conversation of some of the most learned and considerable
men of that time.`"
{footnote-paragraph-split}
From childhood,
Isaac Penington was religiously inclined, and, in a paper written by himself,
and found after his death amongst his writings,
we have such a living portrait of a deeply-exercised mind,
as demonstrates that godliness with him was indeed the "`one thing needful.`"
"`In the sense of my lost estate,`" he writes, "`I sought after the Lord;
I read the Scriptures; I watched over mine own heart;
and whatever I read in the Scriptures, as the way of God, to my understanding,
I gave myself to the faithful practice of.
He became fully convinced of the principles of Friends,
and joined that despised people--becoming a faithful sufferer for the
cause of Christ.`"
`    "`Early believers in the light of Truth
     Dwelt not at ease in Zion. They endured
     Conflicts and trials, and imprisonments.
     Even the humble Penington, whose mind
     Seemed purged and purified from dross
     Of human nature--who appeared as meek
     And harmless as an infant--was compelled
     To dwell in loathsome prisons.`" `
He was six times in jail,
some of his imprisonments being long,
yet borne with great quietness and constancy of mind.
His first imprisonment was in Aylesbury jail in 1661 and 1662,
being committed there for worshipping God in his own house.
He was kept there seventeen weeks,
great part of it in winter--in a cold and very incommodious room without a chimney,
from which usage he contracted so severe an indisposition,
that for several weeks after he was unable to turn himself in his bed.
{footnote-paragraph-split}
In the sixty-third year of his age "`he died as he lived,
in the faith that overcomes the world.`"]

Next morning I rode about fourteen miles to a meeting at Baghurst in Hampshire,
Thomas Briggs being with me.
When we came into the parish, some sober people told us,
that "`the priest of the town was a envious man, and threatened us.`"
We went on to the meeting, which was large;
and after some time Thomas Briggs stood up and spoke.
It seems the priest had got a warrant, and sent the constables and other officers with it.
They came to the house, stayed a while, and then went away again,
without coming into the meeting; so we in the meeting did not know of their being there.
After Thomas Briggs had done speaking, I was moved of the Lord to stand up,
and declare the Word of Life to the people; and a precious meeting we had.
When it was ended and risen, I heard a great clatter in the yard; and when we came out,
the man of the house told us, "`that the officers had been in the house before,
but did not come into the meeting, going away without doing anything;
and that now the priest in a great rage had sent them again,
and his own servant with them.`"
But the meeting being ended before they came, they could do nothing.
Thus the good providence of the Lord preserved
us from the wicked design of the envious priest.

Thence we went to a Friend`'s house on the edge of Berkshire,
where several Friends came to visit us.
Afterwards we passed into Surrey, and had many precious meetings,
till we came to Stephen Smith`'s, near Guildford, where great persecution had been,
and very much property taken away from Friends for their meetings;
and under great threatenings they were at that time;
yet we had several blessed meetings thereabouts, and the Lord`'s power was over all,
in and by which we were preserved.

We went into Sussex, by Richard Baxe`'s, where we had a large, precious, quiet meeting,
though the constables had given out threatenings before.
I had many more meetings in that county; and though there were some threatenings,
they were peaceable; and Friends were refreshed,
and established upon the foundation of God, that stands sure.
When I had thoroughly visited Sussex, I went into Kent,
and had many glorious and precious meetings in several parts of that county.
I went to a meeting near Deal, which was very large;
and returning from thence to Canterbury, visited Friends there.
I then passed into the Isle Of Sheppy, where I stayed two or three days;
and thither came Alexander Parker, George Whitehead, and John Rous to me.

Next day, finding my service for the Lord finished there, we passed towards Rochester.
On the way, as I was walking down a hill,
a great weight and oppression fell upon my spirit; I got on my horse again,
but the weight remained so that I was hardly able to ride.
At length we came to Rochester, but I was much spent,
being so extremely laden and burdened with the world`'s spirits,
that my life was oppressed under them, I got with difficulty to Gravesend,
and lay at an inn there; but could hardly either eat or sleep.
The next day John Rous and Alexander Parker went for London;
and John Stubbs being come to me, we went over the ferry into Essex.
We came to Hornchurch, where was a meeting on First-day.
After it I rode with great uneasiness to Stratford, to a Friend`'s house,
whose name was Williams, and who had formerly been a captain.
Here I lay exceedingly weak, and at last lost both hearing and sight.
Several Friends came to me from London: and I told them,
that "`I should be as a sign to such as would not see,
and such as would not hear the truth.`"
In this condition I continued some time.
Several came about me; and though I could not see their persons,
I felt and discerned their spirits, who were honest-hearted, and who were not.
Divers Friends who practised physic, came to see me, and would have given me medicines,
but I was not to meddle with any; for I was sensible I had a travail to go through;
and therefore desired none but solid, weighty Friends might be about me.
Under great sufferings and travails, sorrows and oppressions, I lay for several weeks,
whereby I was brought so low and weak in body, that few thought I could live.
Some that were with me went away,
saying "`they would not see me die;`" and it was
reported both in London and in the country,
that I was deceased; but I felt the Lord`'s power inwardly supporting me.
When they that were about me had given me up to die,
I spoke to them to get a coach to carry me to Gerrard Roberts`'s, about twelve miles off;
for I found it was my place to go thither.
I had now recovered a little glimmering sight,
so that I could discern the people and fields as I went, and that was all.
When I came to Gerrard`'s, he was very weak; and I was moved to speak to him,
and encourage him.
After I had stayed about three weeks there, it was with me to go to Enfield.
Friends were afraid of my removing; but I told them I might safely go.
When I had taken my leave of Gerrard, and was come to Enfield,
I went first to visit Amor Stoddart, who lay very weak, and almost speechless.
I was moved to tell him, "`he had been faithful as a man, and faithful to God;
and that the immortal Seed of life was his crown.`"
Many more words I was moved to speak to him, though I was then so weak,
I was hardly able to stand; and within a few days after, Amor died.
I went to the widow Dry`'s at Enfield, where I lay all that winter,
warring in spirit with the evil spirits of the world,
that warred against truth and Friends.
For there were great persecutions at this time; some meetinghouses were pulled down,
and many were broken up by soldiers.
Sometimes a troop of horse, or a company of foot came; and some broke their swords,
carbines, muskets, and pikes, with beating Friends; and many they wounded,
so that their blood lay in the streets.
Amongst others that were active in this cruel persecution at London,
my old adversary Colonel Kirby was one; who, with a company of foot,
went to break up several meetings;
and he would often inquire for me at the meetings he broke up.
One time as he went over the water to Horsleydown,
there happening some scuffle between some of his soldiers and some of the watermen,
he bid his men "`fire at them.`"
They did so, and killed some.

I was under great sufferings at this time, beyond what I have words to declare.
For I was brought into the deep, and saw all the religions of the world,
and people that lived in them, and the priests that held them up,
who were as a company of men-eaters, eating up the people like bread,
and gnawing the flesh from off their bones.
But as for true religion and worship, and ministers of God, alack!
I saw there were none amongst those of the world that pretended to it.
For they that pretended to be the church, were but a company of men-eaters,
men of cruel visages, and of long teeth; and,
though they had cried against the men-eaters in America,
I saw they were in the same nature.
And as the great professing Jews did "`eat up God`'s people like bread,`"
and the false prophets and priests then preached peace to people,
so long as they "`put into their mouths and fed them but if they fed them not,
they prepared war against them, they ate their flesh off their bones,
and chopped them for the caldron;`" so these that profess
themselves Christians now (both priests and professors),
and are not in the same power and Spirit that Christ
and the holy prophets and apostles were in,
are in the same nature that the old professing Jews were in,
and are men-eaters as well as they.
These stirred up persecution and set the wicked informers to work;
so that a Friend could hardly speak a few words in a private family,
before they sat down to eat meat, but some were ready to inform against them.
A particular instance of which I have heard as follows:--

At Droitwich John Cartwright came to a Friend`'s house,
and being moved of the Lord to speak a few words before he sat down to supper,
there came an informer, and stood hearkening under the window.
When he had heard the Friend speak, hoping to get some gain to himself,
he went and informed, and got a warrant to distrain his goods,
under pretence that there was a meeting at his house;
whereas there were none in the house at that time, but the Friend, the man of the house,
his wife, and their maidservant.
But this evil-minded man, as he came back with his warrant in the night,
fell off his horse, and broke his neck.
So there was a wretched end of a wicked informer,
who hoped to enrich himself by spoiling Friends; but the Lord prevented him,
and cut him off in his wickedness.

Now, though it was a cruel, bloody, persecuting time, yet the Lord`'s power went over all,
and his everlasting Seed prevailed;
and Friends were made to stand firm and faithful in the Lord`'s power.
Some sober people of other professions would say, "`if Friends did not stand,
the nation would run into debauchery.`"

Though by reason of my weakness, I could not travel amongst Friends as I used to do,
yet in the motion of life,
I sent the following lines as an encouraging testimony to them:--

[.embedded-content-document.epistle]
--

[.salutation]
"`My Dear Friends,

"`The Seed is above all.
In it walk; in which ye all have life.
Be not amazed at the weather; for always the just suffered by the unjust,
but the just had the dominion.
All along ye may see, by faith the mountains were subdued; and the rage of the wicked,
and his fiery darts, were quenched.
Though the waves and storms are high,
yet your faith will keep you so as to swim above them; for they are but for a time,
and the truth is without time.
Therefore keep on the mountain of holiness, ye who are led to it by the light,
where nothing shall hurt.
Do not think that anything will outlast the truth, which standeth sure;
and is over that which is out of the truth; for the good will overcome the evil;
the light, darkness; the life, death; virtue, vice; and righteousness, unrighteousness.
The false prophet cannot overcome the true; but the true prophet, Christ,
will overcome all the false.
So be faithful, and live in that which doth not think the time long`"

[.signed-section-signature]
G+++.+++ F.

--

After some time it pleased the Lord to allay the heat of this violent persecution;
and I felt in spirit an overcoming of the spirits of those men-eaters,
that had stirred it up, and carried it on to that height of cruelty,
though I was outwardly very weak.
And I plainly felt, and those Friends that were with me, and that came to visit me,
took notice, that as the persecution ceased,
I came from under the travails and sufferings, that had lain with such weight upon me;
so that towards the spring I began to recover, and to walk up and down,
beyond the expectation of many, who did not think I could ever have gone abroad again.

Whilst I was under this spiritual suffering, the state of the New Jerusalem,
which comes down out of heaven, was opened to me;
which some carnal-minded people had looked upon to be
like an outward city dropped out of the elements.
I saw the beauty and glory of it, the length, the breadth, and the height thereof,
all in complete proportion.
I saw, that all who are within the light of Christ, and in his faith,
which he is the author of; and in the Spirit, the Holy Ghost,
which Christ and the holy prophets and apostles were in; and within the grace, and truth,
and power of God, which are the walls of the city;--such are within the city,
are members of it, and have right to eat of the tree of life,
which yields her fruit every month, and whose leaves are for the healing of the nations.
But they that are out of the grace, truth, light, Spirit, and power of God;
they who resist the Holy Ghost, quench, vex, and grieve the Spirit of God;
who hate the light, turn the grace of God into wantonness,
and do despite to the Spirit of Grace; they who have erred from the faith,
and made shipwreck of it and of a good conscience, who abuse the power of God,
and despise prophesying, revelation,
and inspiration;--these are the dogs and unbelievers that are without the city.
These make up the great city Babylon, confusion, and her cage, the power of darkness;
and the evil spirit of error surrounds and covers them over.
In this great city Babylon are the false prophets, in the false power and false spirit;
the beast, in the dragon`'s power,
and the whore that is gone a whoring from the Spirit of God, and from Christ her husband.
But the Lord`'s power is over all this power of darkness, false prophets,
and their worshippers, who are for the lake which burns with fire.
Many things more did I see concerning the heavenly city, the New Jerusalem,
which are hard to be uttered, and would be hard to be received.
But, in short, this holy city is within the light, and all that are within the light,
are within the city;
the gates whereof stand open all the day (for there is no night there),
that all may come in.
Christ`'s blood being shed for every man, he tasted death for every man,
and enlighteneth every man that cometh into the world;
and his grace that brings salvation having appeared to all men,
there is no place or language where his voice may not be heard.
The Christians in the primitive times were called by Christ,
"`a city set upon a hill;`" they were also called "`the light of the world,`"
and "`the salt of the earth;`" but when Christians lost the light,
and salt, and power of God, then they came to be trodden under foot, like unsavoury salt.
Even as the Jews, who while they kept the law of God, were preserved above all nations;
but when they turned their backs on God and his law,
they were trodden under foot of other nations.
Adam and Eve, while they obeyed God, were kept in his image and in the paradise of God,
in dominion over all the works of his hands; but when they disobeyed God,
they lost his image, the righteousness and the holiness in which they were made;
they lost their dominion, were driven out of paradise;
and so fell under the dark power of Satan, and came under the chains of darkness.
But the promise of God was, "`that the Seed of the woman, Christ Jesus,
should bruise the serpent`'s head,`"--should break his power and authority,
which had led into captivity, and had held man therein.
So Christ, who is the first and the last, sets man free,
and is the resurrection of the just and unjust, the judge of the quick and dead;
and they that are in him are invested with everlasting rest and peace,
out of all the labours, and travails, and miseries of Adam in the fall.
So he is sufficient and of ability to restore
man into the state he was in before he fell;
and not into that state only, but into that also that never fell, even to himself.

[.offset]
I had also in this time a great exercise and travail of spirit upon me,
concerning the powers and rulers of these nations,
from the sense I had of the many tender visitations and faithful warnings,
that had been given them, and of their great abuse thereof, who had refused to hear,
and rejected the counsel of the Lord.
And though I knew Friends would be clear of their blood,
yet I could not but mourn over them,
and gave forth these few lines following concerning them:--

[.embedded-content-document.address]
--

"`We have given them a visitation, have faithfully warned them,
have declared to them our innocency and uprightness,
and that we never did any hurt to the king, nor to any of his people.
We have nothing in our hearts but love and good-will to him and his people,
and desire their eternal welfare.
But if they will not hear, the day of judgment and of sorrow, of torment, misery,
and sudden destruction, will come from the Lord upon them,
that have been the cause of the sufferings of many thousands of simple, innocent,
harmless people that have done them no hurt,
nor have had any ill-will towards him or them;
but have desired their eternal good for the eternal truth`'s sake.
Destruction will come upon them that turn the sword backward.
Therefore do not blind your eyes,
the Lord will bring swift destruction and misery upon you; surely he will do it,
and will relieve his innocent people,
who have groaned for deliverance from under your oppression,
and have also groaned for your deliverance out of wickedness.
Blessed be the Lord God, that he hath a people in this nation,
that seek the good of all men upon the face of the earth;
for we have the mind of the Lord Jesus Christ, that desires not the death of a shiner,
but the salvation and good of all.
Blessed be the name of the Lord our God forever.`"

[.signed-section-signature]
G+++.+++ F.

--

[.offset]
While I continued at Enfield, a sense came upon me of a hurt that sometimes happened,
by persons under the profession of truth coming out of one country into another,
to take a husband or wife amongst Friends, where they were strangers,
and it was not known whether they were clear and orderly, or not.
And it opened in me to recommend the following method
unto Friends for preventing such inconveniences:--

[.embedded-content-document.epistle]
--

"`All Friends that marry, whether they be men or women,
if they come out of another nation, island, or county,
let them bring a certificate from the men`'s meeting of that county, nation,
or island from which they came,
to the men`'s meeting where they propose their intention of marriage.
For the men`'s meeting being made up of the faithful,
this will stop all wrong spirits from roving up and down.
When any come with a certificate,
or letter of recommendation from one men`'s meeting to another,
one is refreshed by another, and can set their hands and hearts to the thing.
This will prevent a great deal of trouble.
And then what ye have to say to them in the power of God,
in admonishing and instructing them, ye are left to the power and Spirit of God to do it,
and to let them know the duty of marriage, and what it is;
that there may be unity and concord in the Spirit, and power, and light,
and wisdom of God, throughout all the men`'s meetings in the whole world, in one,
in the life.

"`Let copies of this be sent to every county, and nation, and island where Friends are,
that so all things may be kept holy, and pure, and righteous, in unity and peace;
and God over all may be glorified among you, his lot, his people and inheritance,
who are his adopted sons and daughters, and heirs of his life.
So no more, but my love in that which changeth not.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
14th of 1st Month, 1670-1671.

--

When I had recovered, so that I could walk a little,
I went from Enfield to Gerrard Roberts`'s again,
and thence to the women`'s school at Shacklewell,
and so to the meeting at Grace-church-street, London; where, though I was yet but weak,
the Lord`'s power upheld and enabled me to declare his eternal Word of life.

[.offset]
About this time I was moved to pray to the Lord as follows:--

[.embedded-content-document.prayer]
--

"`O Lord God Almighty!
Prosper truth, and preserve justice and equity in the land!
Bring down all injustice and iniquity, oppression and falsehood,
cruelty and unmercifulness in the land; that mercy and righteousness may flourish!

"`O Lord God!
Set up and establish verity, and preserve it in the land!
Bring down in the land all debauchery and vice, whoredoms and fornication,
and this raping spirit, which causeth people to have no esteem of thee,
O God! nor of their own souls or bodies; nor of Christianity, modesty, or humanity.

"`O Lord!
Put it in the magistrates`' hearts to bring down all this ungodliness, violence,
and cruelty, profaneness, cursing, and swearing;
and to put down all those lewd houses and play-houses, which corrupt youth and people,
and lead them from thy kingdom, where no unclean thing can enter, neither shall come!
Such works lead people to hell! Lord!
In mercy bring down all these things in the nation, to stop thy wrath,
O God! from coming on the land.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
This Prayer was written at night, the 17th of the 2nd Month, 1671.

--
