== Chapter IV.

[.chapter-synopsis]
* 1671-1672.
* His wife being still detained a prisoner, George Fox puts two women Friends upon going to the king to procure her discharge, which he granted under the broad seal, to clear her person and estate after being a prisoner under premunire ten years
* he sails for the plantations in America with several other Friends
* chased by a Sallee man-of-war
* the master in a strait asks advice of George Fox, who seeks counsel of the Lord, and is assured of their preservation
* the event verifies the prediction
* they land at Barbados after a seven weeks`' passage
* a man in the island, who was greatly incensed against George Fox without just cause, and who had threatened his life, died a few days before his landing
* is laid up for some weeks
* writes to Friends in England
* exhorts Friends to care and watchfulness in regard to marriages, keeping registers and records, providing burial grounds, etc.
* to deal mildly with their negroes, and, after certain years of servitude, to set them free
* writes a further exhortation to Friends in England
* visits the governor, who is very kind
* has many large meetings, and there is a great convincement; Colonel Lyne testifies how much Friends exalt Christ in all his offices beyond what he had ever heard
* the priests rage, and try in vain to stir up persecution
* there is much clamour and cavilling against Friends, and many slanders and false reports are issued, which George Fox answers in a paper addressed to the governor
* the governor visits him
* writes to his wife
* sails for Jamaica, where he has many meetings, and many are convinced
* Elizabeth Hooton dies there.

I mentioned before, that, upon the notice I received of my wife`'s being imprisoned again,
I sent two of her daughters to the king,
and they procured his order to the sheriff of Lancashire, for her discharge.
But though I expected she would be set at liberty thereby,
this violent storm of persecution coming suddenly on,
the persecutors there found means to hold her still in prison.
But now the persecution a little ceasing,
I was moved to speak to Martha Fisher and another woman Friend,
to go to the king about her liberty.
They went in faith, and in the Lord`'s power, who gave them favour with the king,
so that he granted a discharge under the broad-seal, to clear both her and her estate,
after she had been ten years a prisoner, and premunired;
the like whereof was scarcely to be heard of in England.
I sent down the discharge forthwith by a Friend; by whom also I wrote to her,
informing her how to get it delivered to the justices,
and acquainting her that it was upon me from the
Lord to go beyond the seas to visit America;
and therefore desired her to hasten to London, as soon as she could conveniently,
after she had obtained her liberty, because the ship was then fitting for the voyage.
In the meantime I got to Kingston, and stayed at John Rous`'s till my wife came up,
and then I began to prepare for the voyage.
But the Yearly Meeting being near at hand, I stayed till that was over.
Many Friends came up to it from all parts of the nation,
and a very large and precious meeting it was; for the Lord`'s power was over all,
and his glorious everlastingly-renowned Seed of life was exalted above all.

After this meeting was over, and I had finished my services for the Lord in England,
the ship and the Friends that intended to go with me being ready,
I went to Gravesend on the 12th of 6th month,
my wife and several Friends accompanying me to the Downs.
We went from Wapping in a barge to the ship, which lay a little below Gravesend,
and there we found the Friends that were bound for the voyage with me,
who had gone down to the ship the night before.
Their names were Thomas Briggs, William Edmundson, John Rous, John Stubbs,
Solomon Eccles, James Lancaster, John Cartwright, Robert Widders, George Pattison,
John Hull, Elizabeth Hooton, and Elizabeth Miers.
The vessel was a yacht, called the Industry; the captain`'s name Thomas Forster,
and the number of passengers about fifty.
I lay that night on board, but most of the Friends at Gravesend.
Early next morning the passengers,
and those Friends that intended to accompany us to the Downs, being come on board,
we took our leave in great tenderness of those that came with us to Gravesend only,
and set sail about six in the morning for the Downs.
Having a fair wind, we out-sailed all the ships that were outward-bound,
and got thither by evening.
Some of us went ashore that night, and lodged at Deal; where, we understood,
an officer had orders from the governor to take our names in writing;
which he did next morning, though we told him they had been taken at Gravesend.
In the afternoon, the wind serving, I took leave of my wife and other Friends,
and went on board.
Before we could sail, there being two of the king`'s frigates riding in the Downs,
the captain of one of them sent his press-master on board us,
who took three of our seamen.
This would certainly have delayed, if not wholly prevented, our voyage,
had not the captain of the other frigate, being informed of the leakiness of our vessel,
and the length of our voyage, in compassion and much civility,
spared us two of his own men.
Before this was over,
a custom-house officer came on board to peruse packets and get fees;
so that we were kept from sailing till about sunset;
during which delay a very considerable number of merchantmen, outward-bound,
were got several leagues before us.
Being clear, we set sail in the evening,
and next morning overtook part of that fleet about the height of Dover.
We soon reached the rest, and in a little time left them all behind;
for our yacht was counted a very swift sailor.
But she was very leaky, so that the seamen and some of the passengers did,
for the most part, pump day and night.
One day they observed,
that in two hours`' time she sucked in sixteen inches of water in the well.

When we had been about three weeks at sea,
one afternoon we spied a vessel about four leagues astern of us.
Our master said it was a Sallee man-of-war, that seemed to give us chase.
Our master said, "`Come, let us go to supper, and when it grows dark we shall lose him.`"
This he spoke to please and pacify the passengers,
some of whom began to be very apprehensive of the danger.
But Friends were well satisfied in themselves, having faith in God,
and no fear upon their spirits.
When the sun was gone down, I saw the ship out of my cabin making towards us.
When it grew dark, we altered our course to miss her; but she altered also,
and gained upon us.
At night the master and others came into my cabin, and asked me, "`what they should do?`"
I told them, "`I was no mariner;`" and I asked them, "`what they thought was best to do?`"
They said, "`There were but two ways, either to outrun him, or tack about,
and hold the same course we were going before.`"
I told them, "`if he were a thief, they might be sure he would tack about too;
and as for outrunning him, it was to no purpose to talk of that,
for they saw he sailed faster than we.`"
They asked me again, "`what they should do?
for,`" they said, "`if the mariners had taken Paul`'s counsel,
they had not come to the damage they did.`"
I answered, "`it was a trial of faith,
and therefore the Lord was to be waited on for counsel.`"
So retiring in spirit, the Lord showed me,
"`that his life and power was placed between us and the ship that pursued us.`"
I told this to the master and the rest,
and that the best way was to tack about and steer our right course.
I desired them also to put out all their candles, but the one they steered by,
and to speak to all the passengers to be still and quiet.
About eleven at night the watch called and said, "`they were just upon us.`"
That disquieted some of the passengers; whereupon I sat up in my cabin,
and looking through the port-hole, the moon being not quite down,
I saw them very near us.
I was getting up to go out of the cabin; but remembering the word of the Lord,
"`that his life and power was placed between us and them,`" I lay down again.
The master and some of the seamen came again, and asked me,
"`if they might not steer such a point?`"
I told them, "`they might do as they would.`"
By this time the moon was quite down, a fresh gale arose, and the Lord hid us from them;
and we sailed briskly on and saw them no more.
The next day, being the first day of the week, we had a public meeting in the ship,
as we usually had on that day throughout the voyage,
and the Lord`'s presence was greatly among us.
And I desired the people "`to mind the mercies of the Lord, who had delivered them;
for they might have been all in the Turks`' hands by that time,
had not the Lord`'s hand saved them.`"
About a week after,
the master and some of the seamen endeavoured to persuade the passengers,
that it was not a Turkish pirate that chased us, but a merchantman going to the Canaries.
When I heard of it, I asked them, "`Why then did they speak so to me?
why did they trouble the passengers?
and why did they tack about from him and after their course?`"
I told them "`they should take heed of slighting the mercies of God.`"

Afterwards, while we were at Barbados, there came in a merchant from Sallee,
and told the people, "`that one of the Sallee men-of-war saw a monstrous yacht at sea,
the greatest that ever he saw, and had her in chase, and was just upon her,
but that there was a spirit in her that he could not take.`"
This confirmed us in the belief that it was a Sallee-man we saw make after us,
and that it was the Lord that delivered us out of his hands.

I was not sea-sick during the voyage, as many of the Friends and other passengers were;
but the many hurts and bruises I had formerly received,
and the infirmities I had contracted in England by extreme cold and hardships,
that I had undergone in many long and sore imprisonments, returned upon me at sea;
so that I was very ill in my stomach, and full of violent pains in my bones and limbs.
This was after I had been at sea about a month;
for about three weeks after I came first to sea, I perspired abundantly, chiefly my head,
and my body broke out in pimples, and my legs and feet swelled extremely,
so that my stockings and slippers could not be
drawn on without difficulty and great pain.
Suddenly the sweating ceased, so that when I came into the hot climate,
where others perspired most freely, I could not perspire at all; but my flesh was hot,
dry, and burning; and that which before broke out in pimples,
struck in again to my stomach and heart, so that I was very ill,
and weak beyond expression.
Thus I continued during the rest of the voyage, which was about a month;
for we were above seven weeks at sea.

On the third of the eighth month, early in the morning,
we discovered the island of Barbados,
but it was between nine and ten at night ere we came to anchor in Carlisle-bay.
We got on shore as soon as we could, and I, with some others, walked to a Friend`'s house,
a merchant, whose name was Richard Forstall, above a quarter of a mile from the bridge.
But being very ill and weak, I was so tired with that little walk,
that I was in a manner spent by the time I got thither.
There I abode very ill for several days,
and though they several times gave me things to make me perspire,
they could not effect it.
But what they gave me did rather parch and dry up my body,
and made me probably worse than otherwise I might have been.
Thus I continued about three weeks after I landed, having much pain in my bones, joints,
and whole body, so that I could hardly get any rest; yet I was pretty cheerful,
and my spirit kept above it all.
Neither did my illness take me off from the service of truth,
but both while I was at sea, and after I came to Barbados,
before I was able to travel about,
I gave forth several papers (having a Friend to write for me),
some of which I sent by the first conveyance for England to be printed.

After I had rested three or four days at Richard Forstall`'s,
where many Friends came to visit me, John Rous^
footnote:[Thomas Rous was a wealthy sugar-planter of Barbados.
John Rous was his son, and son-in-law to George Fox,
having married his wife`'s eldest daughter.
John Rous visited New England as a gospel minister when a young man,
and suffered whipping and imprisonment there.
After his release from Boston jail in 1658,
except a visit which he paid to the island of Nevis towards the close of that year,
we lose all trace of him until his marriage with Margaret, eldest daughter of Judge Fell,
at Swarthmore Hall, in 1662.
After his marriage he settled in London, in which, and in its vicinity,
he appears to have resided during the remainder of his life.
But few particulars respecting him are preserved,
except a visit to the county of Kent in 1670,
accompanied by Alexander Parker and George Whitehead;
and to Barbados the following year with George Fox, as related in this Journal.
Besides this, and a visit to the counties of York and Durham in 1689,
we know nothing of his gospel labours after he settled in England.
In his will, dated from Kingston in Surrey in 1692, he describes himself as a merchant,
and his property, which, it appears was considerable, lay chiefly in Barbados.
It is singular no record of his death has been found, but as his will was proved in 1695,
it probably took place in that year.]
having borrowed a coach of Colonel Chamberlain, came to fetch me to his father,
Thomas Rous`'s house.
But it was late ere we could get thither, and little or no rest could I take that night.
A few days after, Colonel Chamberlain, who had so kindly lent his coach, paid me a visit,
and was very courteous towards me.

Soon after I came into the island, I was informed of a remarkable passage,^
footnote:[The words "`passage`" and "`passages`" occur frequently in
the journals and other writings of the early Friends.
In this instance it signifies a remarkable occurrence,
but is generally applied to gospel services, travels, etc.]
wherein the justice of God did eminently appear; it was thus:
There was a young man of Barbados,
whose name was John Drakes (a person of some note in the world`'s account,
but a common swearer and wicked man), who, when in London,
had a mind to marry a Friend`'s daughter, left by her mother very young,
and with a considerable portion, to the care and government of several Friends,
whereof I was one.
He made application to me, that he might have my consent to marry this young maid.
I told him, "`I was one of her overseers appointed by her mother, who was a widow,
to take care of her;
that if her mother had intended her for a match to any man of another profession,
she would have disposed of her accordingly; but she committed her to us,
that she might be trained up in the fear of the Lord,
and therefore I should betray the trust reposed in me,
if I should consent that he who was out of the fear of God, should marry her;
which I would not do.`"
When he saw that he could not obtain his desire,
he returned to Barbados with great offence of mind against me, but without just cause.
Afterwards, when he heard I was coming to Barbados, he swore desperately,
and threatened, that "`if he could possibly procure it,
he would have me burned to death when I came there.`"
Which, a Friend hearing, asked him, "`what I had done to him,
that he was so violent against me?`"
He would not answer, but said again, "`I`'ll have him burned.`"
Whereupon the Friend replied, "`Do not march on too furiously,
lest thou come too soon to thy journey`'s end.`"
About ten days after, he was struck with a violent burning fever, of which he died;
and by which his body was so scorched, that the people said,
"`it was as black as a coal.`"
Three days before I landed, his body was laid in the dust.
This was taken notice of as a sad example.

While I continued so weak, that I could not go abroad to meetings,
the other Friends that came over with me, bestirred themselves in the Lord`'s work.
The day but one after we landed, they had a great meeting at the bridge,
and after that several others in different parts of the island;
which alarmed the people of all sorts, so that many came to our meetings,
and some of the chief rank.
For they had got my name, understanding I was come upon the island,
and expected to see me at those meetings, not knowing that I was unable to go abroad.
And indeed, my weakness continued the longer on me,
by reason that my spirit was much pressed down at first with
the filth and dirt and unrighteousness of the people,
which lay as a heavy weight and load upon me.
But after I had been above a month upon the island, my spirit became somewhat easier,
and I began to recover in some measure my health and strength,
and to get abroad among Friends.
In the meantime, having opportunity to send to England, I wrote to Friends there,
to let them know how it was with me, as follows:--

[.salutation]
"`Dear Friends,

"`I have been very weak these seven weeks past, and not able to write myself.
My desire is to you and for you all, that ye may live in the fear of God,
and in love one unto another, and be subject one to another in the fear of God.
I have been weaker in my body than ever I was in my life that I remember, yea,
my pains have been such as I cannot express; yet my heart and spirit is strong.
I have hardly perspired these seven weeks past, though I am come into a very hot climate,
where hardly any but are well nigh continually perspiring; but as for me, my old bruises,
colds, numbness, and pains, struck inwardly, even to my very heart.
So that I have taken little rest,
and the chief things that were comfortable to my stomach,
were a little water and powdered ginger;
but now I begin to drink a little beer as well as water,
and sometimes a little wine and water mixed.
Great pains and travails I have felt, and in measure am under; but it is well,
my life is over all.
This island was to me as all on a fire ere I came to it,
but now it is somewhat quenched and abated.
I came in weakness amongst those that are strong, and have so continued;
but now I am got a little cheery, and over it.
Many Friends, and some considerable persons of the world, have been with me.
I tired out my body much when amongst you in England;
it is the Lord`'s power that helps me;
therefore I desire you all to prize the power of the Lord and his truth.
I was but weak in body when I left you, after I had been in my great travail amongst you;
but after that, it struck all back again into my body,
which was not well settled after so sore travails in England.
Then I was so tired at sea, that I could not rest,
and have had little or no stomach a long time.
Since I came into this island, my life hath been very much burdened; but I hope,
if the Lord give me strength to manage his work, I shall work thoroughly,
and bring things that have been out of course, into better order.
So, dear Friends, live all in the peaceable truth, and in the love of it,
serving the Lord in newness of life;
for glorious things and precious truths have been manifested among you plentifully,
and to you the riches of the kingdom have been handed.
I have been almost a month in this island,
but have not been able to go abroad or ride out; only very lately I rode out twice,
a quarter of a mile at a time, which wearied me much.
My love in the truth is to you all.`"

[.signed-section-signature]
G+++.+++ F.

Because I was not well able to travel,
the Friends of the island concluded to have their men`'s and
women`'s meeting for the service of the church at Thomas Kous`'s,
where I lay; by which means I was present at each of their meetings,
and had very good service for the Lord in both.
For they had need of information in many things,
divers disorders having crept in for want of care and watchfulness.
I exhorted them, more especially at the men`'s meeting,
"`to be watchful and careful with respect to marriages,
to prevent Friends marrying in near kindreds,
and also to prevent over-hasty proceedings towards second marriages,
after the death of a former husband or wife;
advising that a decent regard might be had in such
cases to the memory of the deceased husband or wife.
As to Friends`' children marrying too young, as at thirteen or fourteen years of age,
I showed them the unfitness thereof,
and the inconveniences and hurts that attend such childish marriages.
I admonished them to purge the floor thoroughly, to sweep their houses very clean,
that nothing might remain that would defile, and to take care that nothing be spoken,
out of their meetings, to the blemishing or defaming one of another.
Concerning the registering of marriages, births, and burials,
I advised them to keep exact records of each in distinct books for that only use;
and also to record in a book for that purpose,
the condemnations of such as went out from truth into disorderly practices,
and the repentance and restoration of such of them as returned again.
I recommended to their care the providing of convenient burying-places for Friends,
which in some parts were yet wanting.
Some directions also I gave them concerning wills,
and the ordering of legacies left by Friends for public uses,
and other things relating to the affairs of the church.
Then as to their blacks or negroes,
I desired them to endeavour to train them up in the fear of God, those that were bought,
and those born in their families, that all might come to the knowledge of the Lord;
that so, with Joshua, every master of a family might say, '`As for me and my house,
we will serve the Lord.`'
I desired them also that they would cause their
overseers to deal mildly and gently with their negroes,
and not use cruelty towards them, as the manner of some hath been and is;
and that after certain years of servitude, they would make them free.`"^
footnote:[The interest of Friends in behalf of the
Negro may be dated from the rise of the Society,
at least from the time of their acquaintance with them at the above date.
In proportion as intercourse was more frequently maintained with the distant colonies,
and the abominations of Slavery were more generally known,
Friends were more decided in their opposition to it.
In 1727 the whole Society, at their Yearly Meeting in London,
passed a general resolution:
"`That the importing of Negroes from their native
country is not a commendable or allowable practice,
and is therefore censured by this meeting.`"
At several subsequent meetings, through a series of years,
minutes were passed to the same effect, but gradually increasing in strength.
In 1758, the practice was declared to be in direct violation of the gospel rule,
and Friends were warned carefully to avoid being in any way concerned in
reaping the unrighteous profits arising from so iniquitous a practice.
In 1761 all were disowned who persisted in a practice so repugnant to Christianity,
and so reproachful to a Christian profession.
{footnote-paragraph-split}
Clarkson,
in alluding to this subject, observes, "`I must beg leave to stop here for a moment,
just to pay the Quakers a due tribute of respect for the proper estimation
in which they have uniformly held these miserable outcasts of society.
What a contrast does it afford to the sentiments of many others concerning them!
How have we been compelled to prove, by a long chain of evidence,
that Negroes have the same feelings and capacities as ourselves!
How many, professing themselves enlightened, even now view them as of a different species.
But by the Friends we have seen them uniformly represented,
as persons '`ransomed by one and the same Saviour,`" '`as visited by one and the same
light for salvation,`' and '`as made equally for immortality as others.`'
These practical views of mankind,
as they are highly honourable to the members of this Society,
so they afford a proof both of the reality and of the
consistency of their religion.`"
{footnote-paragraph-split}
See Clarkson`'s _History of the Abolition of the Slave Trade,_
and Copley`'s _History of Slavery._]
Many sweet and precious things were opened in these meetings by the Spirit,
and in the power of the Lord, to the edifying, confirming, and building up of Friends,
both in the faith and holy order of the gospel.

[.offset]
After these meetings, the vessel bound for England not being gone,
I was moved to write another epistle to Friends there, as follows:--

"`Dear Friends and brethren, to whom is my love in that which never changeth,
but remains in glory, which is over all, the top and cornerstone.
In this all have peace and life, as ye dwell in the blessed Seed,
wherein all is blessed over that which brought the curse;
where all shortness and narrowness of spirit, brittleness and peevishness are.
Therefore keep the holy order of the gospel.
Keep in this blessed Seed, where all may be preserved in temperance, patience, love,
meekness, righteousness, holiness, and peace, in which the Lord may be seen amongst you,
and no ways dishonoured, but glorified by you all.
In all your meetings, in cities, towns, and countries, let righteousness flow among you,
and the holy truth be uppermost; the pure Spirit your guide and leader,
and the holy wisdom from above your orderer, which is gentle, and easy to be entreated.
Keep in the religion that preserves from the spots of the world,
which is pure and undefiled in God`'s sight.
Keep in the pure and holy worship, in which the pure and holy God is worshipped, to wit,
in the Spirit and in the truth, which the devil is out of,
who is the author of all unholiness and of that
which dishonours God. Be tender of God`'s glory,
of his honour, and of his blessed and holy name, in which ye are gathered.
All who profess the truth, see that ye walk in it, in righteousness, godliness,
and holiness; for '`holiness becomes the house of God, the household of faith.`'
And that which becomes God`'s house, God loves;
for he loves righteousness--the ornament which becomes his house, and all his family.
Therefore see that righteousness run down in all your assemblies, that it flow,
to drive away all unrighteousness.
This preserves your peace with God; for in righteousness,
ye have all peace with the righteous God of Peace, and one with another.

"`Every one that bears the name of the Anointed, that high title of being a Christian,
named after the Heavenly Man, see that ye be in the divine nature,
made conformable unto his image, even the image of the Heavenly Divine Man,
who was before that image which Adam and Eve got from Satan in the fall;
so that in none of you that fallen image may appear, but his image,
and you made conformable unto him.
Here translation is showed forth in life and conversation, not in words only; yea,
and conversion and repentance,
which is a change of the nature of the mind and of the heart,
of the spirit and affections, which have been below, and come to be set above;
and so receive the things that are from above, and have your conversation in heaven,
not that conversation which is according to the power of the prince of the air,
that now rules in the disobedient.
So be faithful; this is the word of the Lord God unto you all.
See that godliness and holiness, righteousness and truth, virtue,
and the fruits of the good Spirit, flow over the bad and its fruits,
that ye may answer that which is of God in all;
for your heavenly Father is glorified in that you bring forth much fruit.
Therefore ye, who are plants of his planting, and his trees of righteousness,
see that every tree be full of fruit.
Keep in true humility, and in the true love of God, which doth edify his body;
that the true nourishment from the head, the refreshings, and springs,
and rivers of water, and bread of life, may be plenteously known and felt amongst you;
that so praises may ascend unto God.
Be faithful to the Lord God, and just and true in all your dealings and doings with men.
Be not negligent in your men`'s meetings to admonish, to exhort,
and reprove in the spirit of love and of meekness; to seek that which is lost,
and to bring back again that which hath been driven away.
So let all minds and spirits, souls and hearts,
be bended down under the yoke of Christ Jesus, the power of God.

"`Much I could write, but am weak, and have been mostly since I left you.
Burdens and travails I have been under, and gone through many ways; but it is well.
The Lord Almighty knows my work,
which he hath sent me forth to do by his everlasting arm and power;
which is from everlasting to everlasting.
Blessed be his holy name, which I am in, and in which my love is to you all.`"

[.signed-section-signature]
G+++.+++ F.

After I was able to go about, and had been a little amongst Friends,
I went to visit the governor; Lewis Morice, Thomas Rous,
and some other Friends being with me.
He received us very civilly, and treated us very kindly, making us dine with him;
and keeping us most part of the day before he let us go away.

The same week I went to Bridge-town.
There was to be a general meeting of Friends that week;
and the visit I had made to the governor, and the kind reception I had with him,
being generally known to the officers, civil and military,
many came to this meeting from most parts of the island,
and those not of the meanest rank; several being judges or justices,
colonels or captains; so that a very great meeting we had, both of Friends and others.
The Lord`'s blessed power was plentifully with us;
and although I was somewhat straightened for time,
three other Friends having spoken before me,
yet the Lord opened things through me to the general
and great satisfaction of them that were present.
Colonel Lewis Morice came to this meeting, and with him a neighbour of his,
a judge in the country, whose name was Ralph Fretwell; who was very well satisfied,
and received the truth.

Paul Gwin, a jangling Baptist, came into the meeting, and asked me, "`How I spelt Cain?
and whether I had the same spirit as the apostles had?`"
I told him, "`Yes.`"
And he bade the judge take notice of it.
I told him, "`He that had not a measure of the same Holy Ghost as the apostles had,
was possessed with an unclean spirit.`"
And then he went his way.

I went home with Lewis Morice that night, being about nine or ten miles,
going part of the way by boat, the rest on horseback.
The place where his plantation was, I thought to be in the finest air of the island.
The next day Thomas Briggs and William Edmundson came to see me,
intending to leave the island the day following,
to go on the Lord`'s service to Antigua and Nevis.
Lewis Morice went with them; at Antigua they had several good meetings,
to which there was a great resort of people; and many were convinced.
But when they went to Nevis, the governor, an old persecutor,
sent soldiers on board the vessel, to stop them, and would not suffer them to land.
Wherefore, after Friends of the place had been on board the vessel with them,
and they had been sweetly refreshed together,
feeling the Lord`'s power and presence amongst them, they returned to Antigua;
where having stayed a while longer, they came back again to Bardadoes,
Thomas Briggs being weak and ill.

Of the other Friends that came over with me from England, James Lancaster,
John Cartwright, and George Pattison, were gone some time before to Jamaica,
and others to other places, so that few remained in Barbados with me.
We had many great and precious meetings,
both for worship and for the affairs of the church;
to the former of which many of other societies came.
At one of these meetings Colonel Lyne, a sober person,
was so well satisfied with what I declared, that he said,
"`Now I can gainsay such as I have heard speak evil of you; who say,
you do not own Christ, nor that he died;
whereas I perceive you exalt Christ in all his
offices beyond what I have ever heard before.`"^
footnote:[The faith of the early Friends in the divinity and
offices of our Saviour being called in question by some,
they boldly resented such an inference.
From a work published by Samuel Crisp, in 1704,
take the following extracts:--
{footnote-paragraph-split}
"`Our faith is,
and always has been in that Christ, the Son of God, who, according to the flesh,
was crucified without the gates of Jerusalem: He is the object of our faith,
to the merit of whose death and passion, with the work of his Spirit in our hearts,
we trust only for life and salvation;
with his stripes we are healed.`"
{footnote-paragraph-split}
"`As to what he (a libeller) says of our forcing ourselves to speak
with a seeming reverence and respect of the outward Christ,
his death and sufferings,
I would hope that he knows better in his own conscience than thus to represent us.
We bear a true reverence and respect to Jesus Christ, his death and sufferings,
and can never be sufficiently thankful to him who was pleased to humble himself to death,
even the death of the cross; that all that believe in him might, through the cross,
be made heirs of life and immortality.`"
{footnote-paragraph-split}
For further elucidation of the soundness of the early Friends in
their belief as to the divinity and offices of Christ,
see Evans`' _Exposition of the Faith of the Society of Friends,_
especially John Banks`' "`Testimony concerning his faith in
Christ,`" and an "`Essay drawn up by John Burnyeat and John
Watson in 1685,`" contained in the above-mentioned work.]
This man, observing a person take in writing the heads of what I delivered,
desired to have a copy of it; and stayed another day with us;
so great a love was raised in him to the truth.
Indeed a very great convincement there was in most parts of the island;
which made the priests and professors rage.
Our meetings were very large, and free from disturbance from the government,
though the envious priests and some professors
endeavoured to stir up the magistrates against us.
When they found they could not prevail that way,
some Baptists came to the meeting at the town,
which was full of people of several ranks and qualities.
A great company came with them; and they brought a slanderous paper,
written by John Pennyman, with which they made a great noise.
But the Lord gave me wisdom and utterance to answer their cavils;
so that the auditory generally received satisfaction,
and those quarrelsome professors lost ground.
When they had wearied themselves with clamour, they went away; but the people staying,
the meeting was continued;
the things they cavilled about were further opened and cleared;
and the life and power of God came over all.
But the rage and envy in our adversaries did not cease;
they endeavoured to defame Friends with many false and scandalous reports,
which they spread abroad through the island.
Whereupon we drew up a paper, to go forth in the name of the people called Quakers,
for the clearing of truth and Friends from those false reports.
It was directed thus:--

[.blurb]
=== "`For the Governor of Barbados, with his Council and Assembly, and all others in power, both civil and military, in this Island; from the people called Quakers.

"`Whereas many scandalous lies and slanders have been cast upon us, to render us odious;
as that '`We deny God, and Christ Jesus, and the Scriptures of truth,`' etc.
This is to inform you, that all our books and declarations,
which for these many years have been published to the world,
clearly testify the contrary.
Yet, for your satisfaction, we now plainly and sincerely declare,
'`that we do own and believe in the only wise, omnipotent, and everlasting God,
the Creator of all things both in heaven and in earth,
and the preserver of all that he hath made; who is God over all, blessed forever;
to whom be all honour and glory, dominion, praise, and thanksgiving,
both now and forevermore!`'

"`And we own and believe in Jesus Christ, his beloved and only begotten Son,
in whom he is well pleased; who was conceived by the Holy Ghost,
and born of the Virgin Mary; in whom we have redemption through his blood,
even the forgiveness of sins; who is the express image of the Invisible God,
the first-born of every creature, by whom were all things created that are in heaven,
and in earth, visible and invisible, whether they be thrones, or dominions,
principalities, or powers, all things were created by him.
And we own and believe that He was made a sacrifice for sin, who knew no sin,
neither was guile found in his mouth; that he was crucified for us in the flesh,
without the gates of Jerusalem; and that he was buried,
and rose again the third day by the power of his Father, for our justification;
and that he ascended up into heaven, and now sitteth at the right hand of God.
This Jesus, who was the foundation of the holy prophets and apostles, is our foundation;
and we believe that there is no other foundation to be laid than that which is laid,
even Christ Jesus; who tasted death for every man, shed his blood for all men,
and is the propitiation for our sins, and not for ours only,
but also for the sins of the whole world; according as John the Baptist testified of him,
when he said, '`Behold the Lamb of God, that taketh away the sins of the world.`'
John 1:29. We believe that he alone is our Redeemer and Saviour,
even the Captain of our Salvation, who saves us from sin, as well as from hell,
and the wrath to come, and destroys the devil and his works; he is the Seed of the woman,
that bruises the serpent`'s head, to wit, Christ Jesus, the Alpha and Omega,
the First and the Last.
He is (as the Scriptures of truth say of him) our wisdom and righteousness,
justification and redemption; neither is there salvation in any other,
for there is no other name under heaven given among men whereby we may be saved.
He alone is the Shepherd and Bishop of our souls; He is our Prophet,
whom Moses long since testified of, saying,
'`A prophet shall the Lord your God raise up unto you of your brethren, like unto me;
Him shall ye hear in all things, whatsoever he shall say unto you;
and it shall come to pass, that every soul that will not hear that prophet,
shall be destroyed from among the people.`'
Acts 3:22-23.

"`He it is that is now come in the Spirit,
and hath given us an understanding that we may know him that is true.
He rules in our hearts by his law of love and of life,
and makes us free from the law of sin and death.
We have no life but by him; for he is the quickening Spirit, the second Adam,
the Lord from heaven, by whose blood we are cleansed,
and our consciences sprinkled from dead works to serve the living God.
He is our Mediator,
that makes peace and reconciliation between God offended and us offending,
He being the oath of God, the new covenant of light, life, grace, and peace;
the author and finisher of our faith.
This Lord Jesus Christ, the heavenly Man, the Emmanuel, God with us,
we all own and believe in; him whom the high-priest raged against, and said,
he had spoken blasphemy;
whom the priests and the elders of the Jews took counsel together against,
and put to death; the same whom Judas betrayed for thirty pieces of silver,
which the priests gave him as a reward for his treason,
who also gave large money to the soldiers to broach a horrible lie, namely,
'`that his disciples came and stole him away by night, whilst they slept.`'
After he was risen from the dead, the history of the Acts of the Apostles sets forth,
how the chief priests and elders persecuted the disciples of this Jesus,
for preaching Christ and his resurrection.
This, we say, is that Lord Jesus Christ, whom we own to be our life and salvation.

"`Concerning the Holy Scriptures,
we do believe that they were given forth by the Holy Spirit of God,
through the holy men of God, who (as the Scripture itself declares,
2 Pet. 1:21) '`spake as they were moved by the Holy Ghost.`'
We believe they are to be read, believed, and fulfilled
(he that fulfils them, is Christ);
and they are '`profitable for doctrine, for reproof, for correction,
and for instruction in righteousness, that the man of God may be perfect,
thoroughly furnished unto all good works,`' 2 Tim. 3:16,
and are '`able to make wise unto salvation, through faith in Christ Jesus.`'
We believe that the Holy Scriptures are the words of God; for it is said, Ex. 20:1,
'`God spake all these words, saying,`' etc.,
meaning the ten commandments given forth upon Mount Sinai.
And in Rev. 22:18, saith John,
'`I testify to every man that heareth the words of the prophecy of this book:
if any man addeth unto these,
and if any man shall take away from the words of
the book of this prophecy`' (not the word), etc.
So in Luke 1:20, '`Because thou believest not my words.`'
And in John 5:47; 15:7; 15:23; and 12:47.
So that we call the Holy Scriptures, as Christ and the apostles called them,
and holy men of God called them, viz., the words of God.

"`Another slander which they have cast upon us is,
'`that we teach the negroes to rebel;`' a thing we utterly abhor in our hearts;
the Lord knows it, who is the searcher of all hearts, and knows all things,
and can testify for us, that this is a most abominable untruth.
For that which we have spoken to them is, '`to exhort and admonish them to be sober,
and to fear God; to love their masters and mistresses,
and to be faithful and diligent in their masters`' service and business;
and then their masters and overseers would love them,
and deal kindly and gently with them; also, that they should not beat their wives,
nor the wives their husbands, neither should the men have many wives;
that they should not steal, or be drunk,--should not commit adultery,
or fornication,--should not curse, swear, lie, or give bad words to one another,
or to any one else: for there is something in them that tells them,
they should not practise these or any other evils.
But if, notwithstanding, they should do them,
then we let them know there are but two ways, the one that leads to heaven,
where the righteous go; and the other that leads to hell, where the wicked and debauched,
whoremongers and adulterers, murderers and liars go.
To the one the Lord will say, '`Come, ye blessed of my Father,
inherit the kingdom prepared for you from the
foundation of the world;`' but to the other he will say,
'`Depart, ye cursed, into everlasting fire,
prepared for the devil and his angels:`' so '`the wicked go into everlasting punishment,
but the righteous into life eternal.`' Matt. 25.

"`Consider, Friends,
it is no transgression for a master of a family to instruct his family himself,
or for some others to do it in his behalf;
but rather it is a very great duty incumbent upon them.
Abraham and Joshua did so: of the first the Lord said, Gen. 18:19,
'`I know that Abraham will command his children and his household after him;
and they shall keep the way of the Lord, to do justice and judgment,
that the Lord may bring upon Abraham the things that he hath spoken of him.`'
And the latter said, Josh. 24:15, '`Choose ye this day whom ye will serve;
but as for me and my house, we will serve the Lord.`'
We declare that we esteem it a duty incumbent on us to pray
with and for those in and belonging to our families,
and to teach, instruct, and admonish them; this being a command of the Lord,
disobedience whereunto will provoke his displeasure; as may be seen, Jer. 10:25,
'`Pour out thy fury upon the heathen that know thee not,
and upon the families that call not upon thy name.`'
Now Negroes, Tawnies, Indians, make up a very great part of the families in this island;
for whom an account will be required by him who comes to judge both quick and dead,
at the great day of judgment,
when every one shall be '`rewarded according to the deeds done in the body,
whether they be good or whether they be evil:`' at that day, we say,
of the resurrection both of the good and of the bad, of the just and of the unjust,
when '`the Lord Jesus shall be revealed from heaven with his mighty angels,
in flaming fire, taking vengeance on them that know not God,
and obey not the gospel of our Lord Jesus Christ,
who shall be punished with everlasting destruction from the presence of the Lord,
and from the glory of his power, when he shall come to be glorified in his saints,
and admired in all them that believe in that day.`'
2 Thess. 1:8, etc. See also 2 Pet. 3:3, etc.`"

[.small-break]
'''

This wicked slander (of our endeavouring to make the
negroes rebel) our adversaries took occasion to raise,
from our having had some meetings with and amongst the negroes;
for both I and other Friends had several meetings with them in several plantations,
wherein we exhorted them to justice, sobriety, temperance, chastity, and piety,
and to be subject to their masters and governors;
which was altogether contrary to what our envious
adversaries maliciously suggested against us.

As I had been to visit the governor as soon as I was well able, after I came thither; so,
when I was at Thomas Rous`'s, the governor came to see me,
carrying himself very courteously.

Having been three months or more in Barbados, and having visited Friends,
thoroughly settled meetings,
and dispatched the service for which the Lord brought me thither,
I felt my spirit clear of that island, and found drawings to Jamaica.
When I had communicated this to Friends, I acquainted the governor also,
and divers of his council, that I intended shortly to leave the island,
and go to Jamaica.
This I did, that as my coming thither was open and public, so my departure also might be.
Before I left the island, I wrote the following letter to my wife;
that she might understand both how it was with me, and how I proceeded in my travels:--

[.salutation]
"`My Dear Heart,

"`To whom is my love, and to all the children in the Seed of Life that changeth not,
but is over all; blessed be the Lord forever.
I have undergone great sufferings in my body and spirit, beyond words;
but the God of heaven be praised, his truth is over all I am now well; and,
if the Lord permit, within a few days I pass from Barbados towards Jamaica;
and I think to stay but little there.
I desire that ye may be all kept free in the Seed of Life, out of all cumbrances.
Friends are generally well.
Remember me to Friends that inquire after me.
So no more, but my love in the Seed and Life that changeth not.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Barbados, 6th. of 11th Month, 1671.

I set sail from Barbados to Jamaica on the 8th of the 11th month, 1671; Robert Widders,
William Edmundson, Solomon Eccles, and Elizabeth Hooton, going with me.
Thomas Briggs and John Stubbs remained in Barbados;
with whom were John Rous and William Bailey.
We had a quick and easy passage to Jamaica,
where we met with our Friends James Lancaster, John Cartwright,
and George Pattison again, who had been labouring there in the service of truth;
into which we forthwith entered with them, travelling up and down through the island,
which is large; and a brave country it is, though the people are, many of them,
debauched and wicked.
We had much service.
There was a great convincement, and many received the truth;
some of whom were people of account in the world.
We had many meetings there, which were large, and very quiet.
The people were civil to us, so that not a mouth was opened against us.
I was twice with the governor, and some other magistrates,
who all carried themselves kindly towards me.

About a week after we landed in Jamaica, Elizabeth Hooton, a woman of great age,
who had travelled much in truth`'s service, and suffered much for it, departed this life.
She was well the day before she died; and departed in peace, like a lamb,
bearing testimony to truth at her departure.

When we had been about seven weeks in Jamaica,
had brought Friends into pretty good order, and settled several meetings amongst them,
we left Solomon Eccles there; the rest of us embarked for Maryland,
leaving Friends and truth prosperous in Jamaica, the Lord`'s power being over all,
and his blessed Seed reigning.

Before I left Jamaica, I wrote another letter to my wife, as follows:--

[.salutation]
"`My dear Heart,

"`To whom is my love, and to the children, in that which changeth not, but is over all;
and to all Friends in those parts.
I have been in Jamaica about five weeks.
Friends here are generally well; and there is a convincement:
but things would be too large to write of.
Sufferings in every place attend me; but the blessed Seed is over all:
the great Lord be praised, who is Lord of sea and land, and of all things therein.
We intend to pass from hence about the beginning of next month, towards Maryland,
if the Lord please.
Dwell all of you in the Seed of God; in his truth I rest in love to you all.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Jamaica, 23rd of 12th Month, 1071.
