== Chapter V.

[.chapter-synopsis]
* 1672-1673.
* George Fox embarks for Maryland, where he arrives after a seven weeks`' voyage, and having experienced some remarkable deliverances
* attends a General Meeting for Maryland, which held four days
* several meetings for discipline established
* has meetings with the Indian kings
* travels towards New England
* attends the half year`'s meeting on Long Island, which continued four days
* has a meeting with some opposers
* visits Rhode Island, where the Yearly Meeting for New England is held, which continued six days
* attends a marriage there, and has a meeting with some Ranters
* also one with some Indians on Shelter Island
* one of his companions thrown from his horse and lays apparently dead, but soon recovers in an unexpected manner
* they reach Maryland after nine days`' travel overland between three and four hundred miles
* visits a judge who is ill, but recovers
* attends the General Meeting for Maryland, which held five days
* sails for Virginia, and arrives in three days, a distance of 200 miles
* thence proceeds towards Carolina
* visits the Indians, and shows them that God made but one woman for one man
* returns to Virginia
* sails for Maryland
* endures great extremes of heat and cold within a very short period
* speaks to a woman who had been many years in trouble, and entreats the Lord for her, and she is thereupon restored
* attends the General Meeting for Maryland, to the edification and comfort of Friends
* sails for England, and arrives safe, after a six weeks`' passage.

We went on board on the 8th of 1st Month, 1671-1672; and having contrary winds,
were a full week sailing forwards and backwards,
before we could get out of sight of Jamaica.
A difficult voyage this proved, and dangerous,
especially in passing through the Gulf of Florida,
where we met with many trials by winds and storms.
But the great God, who is Lord of the sea and land,
and who rideth upon the wings of the wind,
did by his power preserve us through many and great dangers,
when by extreme stress of weather our vessel was many times likely to be upset,
and much of her tackling broken.
And indeed we were sensible that the Lord was a God at hand,
and that his ear was open to the supplications of his people.
For when the winds were so strong and boisterous, and the storms and tempests so great,
that the sailors knew not what to do, but let the ship go which way she would;
then did we pray unto the Lord, who graciously heard us, calmed the winds and the seas,
gave us seasonable weather, and made us to rejoice in his salvation;
blessed and praised be the holy name of the Lord, whose power hath dominion over all,
whom the winds and the seas obey.

We were between six and seven weeks in this passage from Jamaica to Maryland.
Some days before we came to land, after we had entered the bay of Patuxent River,
a great storm arose, which cast a boat upon us for shelter,
in which were several people of account in the world.
We took them in; but the boat was lost, with five hundred pounds`' worth of goods in it,
as they said.
They continued on board us several days, not having any means to get off;
and we had a very good meeting with them in the ship.
But provisions grew short, for they brought none in with them; and ours,
by reason of the length of our voyage, were well nigh spent when they came to us;
so that with their living with us too, we had now little or none left.
Whereupon George Pattison took a boat, and ventured his life to get to shore;
the hazard was so great, that all but Friends concluded he would be cast away.
Yet it pleased the Lord to bring him safe to land; and in a short time after,
the Friends of the place came to fetch us to land also, in a seasonable time,
for our provisions were quite spent.

We partook also of another great deliverance in this voyage,
through the good providence of the Lord, which we came to understand afterwards.
For when we were determined to come from Jamaica, we had our choice of two vessels,
that were both bound for the same coast.
One of these was a frigate, the other a yacht.
The master of the frigate, we thought, asked unreasonably for our passage;
which made us agree with the master of the yacht,
who offered to carry us ten shillings a-piece cheaper than the other.
We went on board the yacht, and the frigate came out together with us,
intending to be consorts during the voyage; and for several days we sailed together;
but what with calms and contrary winds, we were in a while separated.
After that, the frigate, losing her way, fell among the Spaniards;
by whom she was taken and plundered, and the master and mate made prisoners; afterwards,
being retaken by the English, she was sent home to her owners in Virginia.
Which when we came to understand, we saw and admired the providence of God,
who preserved us out of our enemies`' hands;
and he that was covetous fell among the covetous.

Here we found John Burnyeat^
footnote:[John Burnyeat, a fellow-labourer in the gospel with George Fox,
and who is several times named in this Journal,
was born in Cumberland about the year 1631.
He was well educated, and religiously inclined from his youth,
and convinced by George Fox when he first came into Cumberland in 1653.
He became an unwearied traveller in the gospel, both in this country and in America,
boldly proclaiming the glad tidings of salvation,
for which he fell in for his share of abuse and imprisonments.
Once at Kipon,
when visiting twenty-four of his friends imprisoned there for the testimony of Jesus,
speaking a few words to them he was haled away before the mayor,
and several times knocked off his knees when at prayer,
being sent to prison to his friends,
and kept there fourteen weeks.
{footnote-paragraph-split}
He married and settled in Ireland,
where his service mostly lay in his latter days.
In 1683 he was imprisoned in the Marshalsea in Dublin two months,
for meeting and preaching.
His wife died in 1688; and he, having finished his course, and kept the faith,
departed in peace in 1690.
His works, and testimonies concerning him, with an account of his convincement,
and journal of his travels, was published in a 4to volume,
to which the reader is referred.
Also, _Piety Promoted,_ vol. i. p. 179; and Whiting`'s _Memoirs,_ p. 416-430.]
intending shortly to sail for England; but on our arrival he altered his purpose,
and joined us in the Lord`'s service.
He had appointed a general meeting for all the Friends in the province of Maryland,
that he might see them together, and take his leave of them,
before he departed out of the country;
and it was so ordered by the good providence of God,
that we landed just in time to reach that meeting;
by which means we had a very seasonable opportunity of
taking the Friends of the province together.
A very large meeting this was, and held four days; to which, besides Friends,
came many other people, many of whom were of considerable quality in the world`'s account;
for there were amongst them five or six justices of the peace,
a speaker of their parliament or assembly, one of the council, and divers others of note;
who seemed well satisfied with the meeting.
After the public meetings were over, the men`'s and women`'s meetings began;
wherein I opened to Friends the service thereof to their great satisfaction.
After this we went to a place called the Cliffs,
where another general meeting was appointed.
We went some part of the way by land, the rest by water; and a storm arising,
our boat was run on ground, in danger to be beaten to pieces;
and the water came in upon us.
I perspired much, having come very hot out of a meeting before,
and was now wet with the water beside; yet having faith in the divine power,
I was preserved from taking hurt; blessed be the Lord.
To this meeting also many people came, and received the truth with reverence.
We had also a men`'s meeting and a women`'s meeting,
at which most of the backsliders came in again;
and several of those meetings were established
for taking care of the affairs of the church.

After these two general meetings, we parted company,
dividing ourselves unto several coasts, for the service of truth.
James Lancaster and John Cartwright went by sea for New England;
William Edmundson and three other Friends sailed for Virginia,
where things were much out of order; John Burnyeat, Robert Widders, George Pattison,
and I, with several Friends of the province, went over by boat to the eastern shore,
and had a meeting there on the First-day;
where many people received the truth with gladness, and Friends were greatly refreshed.
A very large and heavenly meeting it was;
and several persons of quality in that country were at it,
two of whom were justices of the peace.
It was upon me from the Lord,
to send to the Indian emperor and his kings to come to that meeting;
the emperor came and was at it; but his kings, lying further off,
could not reach in time; yet they came after with their cockarooses.
I had in the evening two good opportunities with them;
they heard the word of the Lord willingly, and confessed to it.
What I spoke to them, I desired them to speak to their people; and let them know,
that "`God was raising up his tabernacle of witness in their wilderness country,
and was setting up his standard and glorious ensign of righteousness.`"
They carried themselves very courteously and lovingly,
and inquired "`where the next meeting would be,
and they would come to it;`" yet they said,
"`they had had a great debate with their council about their coming,
before they came now.`"

Next day we began our journey by land to New England;
a tedious journey through the woods and wilderness, over bogs and great rivers.
We took horse at the head of Tredhaven Creek, and travelled through the woods,
till we came a little above the head of Miles River; by which we passed,
and rode to the head of Wye River, and so to the head of Chester River; where,
making a fire, we took up our lodging in the woods.
Next morning we travelled through the woods till we came to Saxifrax River,
which we went over in canoes (or Indian boats), causing our horses to swim by.
Then we rode to Bohemia River; where in like manner swimming our horses,
we ourselves went over in canoes.
We rested a little while at a plantation by the way, but not long,
for we had thirty miles to ride that afternoon, if we would reach a town;
which we were desirous to do, and therefore rode hard for it.
I with some others, whose horses were strong, got to the town that night,
exceedingly tired, and wet to the skin;
but George Pattison and Robert Widders being weaker-horsed,
were obliged to lie in the woods that night also.
The town we went to, was a Dutch town, called Newcastle,
whither Robert Widders and George Pattison came to us next morning.
We departed thence and got over the River Delaware,
not without great danger of some of our lives.
When we were over, we were troubled to procure guides;
who were hard to get and very chargeable.
Then had we that wilderness country to pass through, since called West Jersey,
not then inhabited by English; so that we have travelled a whole day together,
without seeing man or woman, house or dwelling-place.
Sometimes we lay in the woods by a fire, and sometimes in the Indians`' wigwams or houses.
We came one night to an Indian town, and lay at the king`'s house,
who was a very worthy man.
Both he and his wife received us very lovingly,
and his attendants (such as they were) were very respectful to us.
They laid us mats to lie on; but provision was very short with them,
having caught but little that day.^
footnote:[The instances of heathen kindness and hospitality,
experienced by George Fox and others who have visited the Indians in a friendly manner,
contrast very favourably in comparison with the many acts of bigoted intolerance
and cruelty recorded in these volumes on the part of those professedly civilized
and Christian.
{footnote-paragraph-split}
Many incidents might be related in
proof of Indian kindness when unprovoked to opposite conduct.
When the Quakers were under a cruel persecution by the magistrates of Boston,
in New England, Nicholas Upshal,
"`a man of an unblameable conversation,`" and a church member of their communion,
showed the sufferers kindness,
by giving five shillings a week to the jailer to let those
confined in prison have the sustenance necessary for life--
__the magistrates having caused the jail window to be boarded up,
that none might communicate with, or help them.__
He proceeded afterwards to reason with the magistrates,
and warn them not to be found fighting against God, for which he was fined £20,
imprisoned, and then banished; though a weakly old man,
and the season the depth of winter.
In his banishment in the wilderness, he met an Indian, who,
having understood how he had been dealt with, took compassion on him,
and very kindly told him, _if he would live with him he would make him a warm house;_
and further said, "`What a God have these English,
who deal so with one another about their God!`"
`    See here the Red Indian`'s kindly care
     Though he the name of _savage_ bear.
     Christian, more savage thou than he,
     Blush for thy cruel deeds of infamy:
     The Indian`'s unasked cup of charity
     Is larger than as mixed by thee.
     The white man ag`'d, through frost and snows
     A banish`'d exile to his country goes,
     Full many a welcome does he say,
     To his warm house whate`'er the day.
     More Christian he who thus does prove
     By practice kindred with a God of love.
     More Christian he than they who thus pollute
     Their faith, and for their God a brother persecute. `]
At another Indian town where we stayed, the king came to us,
and he could speak some English.
I spoke to him much, and also to his people, and they were very loving to us.
At length we came to Middletown, an English plantation in East Jersey,
where there were some Friends,
but we could not stay to have a meeting there at that time,
being earnestly pressed in our spirits,
to get to the half-year`'s meeting of Friends at Oyster-Bay in Long Island,
which was very near at hand.
We went with a Friend, Richard Hartshorn, brother to Hugh Hartshorn, the upholsterer,
in London, who received us gladly at his house, where we refreshed ourselves,
and then he carried us and our horses in his own boat over a great water,
which occupied most part of the day getting over, and set us upon Long Island.
We got that evening to Friends at Gravesand, with whom we tarried that night,
and next day got to Flushing, and the day following reached Oister-bay;
several Friends of Gravesand and Flushing accompanying us.
The half-year`'s meeting began next day, which was the first day of the week,
and lasted four days.
The first and second days we had public meetings for worship,
to which people of all sorts came; on the third day were the men`'s and women`'s meetings,
wherein the affairs of the church were taken care of.
Here we met with some bad spirits, who had run out from truth into prejudice, contention,
and opposition to the order of truth, and to Friends therein.
These had been very troublesome to Friends in
their meetings there and thereabouts formerly,
and likely would have been so now;
but I would not suffer the service of our men`'s and women`'s
meetings to be interrupted and hindered by their cavils.
I let them know,
that "`if they had anything to object against the order of truth which we were in,
we would give them a meeting another day on purpose.`"
And indeed I laboured the more, and travelled the harder to get to this meeting,
where it was expected many of these contentious people would be;
because I understood they had reflected much upon me, when I was far from them.
The men`'s and women`'s meetings being over,
on the fourth day we had a meeting with these discontented people,
to which as many of them as chose came, and as many Friends as desired were present also;
and the Lord`'s power broke forth gloriously to the confounding of the gainsayers.
Then some of those that had been chief in the mischievous work
of contention and opposition against the truth,
began to fawn upon me, and to cast the blame upon others;
but the deceitful spirit was judged down and condemned,
and the glorious truth of God was exalted and set over all;
and they were all brought down and bowed under.
Which was of great service to truth, and to the satisfaction and comfort of Friends;
glory to the Lord forever!

After Friends were gone to their several habitations,
we stayed some days upon the island; had meetings in several parts thereof,
and good service for the Lord.
When we were clear of the island, we returned to Oyster-Bay,
waiting for a wind to carry us to Rhode Island,
which was computed to be about two hundred miles.
As soon as the wind served we set sail,
and arrived there on the thirtieth day of the third month;
and were gladly received by Friends.
We went to Nicholas Easton`'s house, who at that time was governor of the island;
where we rested, being very weary with travelling.
On First-day following we had a large meeting,
to which the deputy-governor and several justices came,
who were mightily affected with the truth.
The week following,
the Yearly Meeting for all the Friends of New England and the other colonies adjacent,
was held in this island; to which, besides very many Friends who lived in those parts,
came John Stubbs from Barbados,
and James Lancaster and John Cartwright from another way.
This meeting lasted six days,
the first four days being general public meetings for worship,
to which abundance of other people came; for they having no priest in the island,
and so no restriction to any particular way of worship;
and both the governor and deputy-governor,
with several justices of the peace daily frequenting the meetings;
this so encouraged the people that they flocked in from all parts of the island.
Very good service we had amongst them, and truth had a good reception.
I have rarely observed people, in the state wherein they stood, hear with more attention,
diligence, and affection, than generally they did, during the four days together;
which also was taken notice of by other Friends.
After these public meetings were over, the men`'s meeting began, which was large,
precious, and weighty; and the day following was the women`'s meeting,
which also was large and very solemn.
These two meetings being for ordering the affairs of the church,
many weighty things were opened and communicated to them, by way of advice, information,
and instruction in the services relating thereunto; that all might be kept clean, sweet,
and savoury amongst them.
In these two meetings, several men`'s and women`'s meetings for other parts,
were agreed and settled, to take care of the poor, and other affairs of the church;
and to see, that all who profess truth, walk according to the glorious gospel of God.
When this great general meeting in Rhode Island was ended,
it was somewhat hard for Friends to part; for the glorious power of the Lord,
which was over all, and his blessed truth and life flowing amongst them,
had so knit and united them together,
that they spent two days in taking leave one of another,
and of the Friends of the island; and then,
being mightily filled with the presence and power of the Lord,
they went away with joyful hearts to their various habitations,
in the several colonies where they lived.^
footnote:[See Bowden`'s _History of Friends in America_, vol. i., p. 250-254.]

When Friends had taken their leave one of another, we, who travelled amongst them,
dispersed ourselves into our several services, as the Lord ordered us.
John Burnyeat, John Cartwright, and George Pattison,
went into the eastern parts of New England,
in company with the Friends that came from thence,
to visit the particular meetings there;
whom John Stubbs and James Lancaster intended to follow awhile after,
in the same service; but they were not yet clear of this island.
Robert Widders and I stayed some time longer also upon this island;
finding service still here for the Lord, through the great openness of the people,
and the daily coming in of fresh people from other colonies,
for some time after the general meeting;
so that we had many large and serviceable meetings among them.

During this time a marriage took place amongst Friends in this island;
and we were present.
It was at a Friend`'s house, who had formerly been governor of the island;
three justices of the peace, and many others not in profession with us, were there;
and both they and Friends said, they never saw so solemn an assembly on such an occasion,
so weighty a marriage and so comely an order.
Thus truth was set over all.
This might serve for an example to others,
for there were some present from many other places.

After this I had a great travail in spirit concerning the Ranters in those parts,
who had been rude at a meeting which I was not at.
Wherefore I appointed a meeting amongst them,
believing the Lord would give me power over them; which he did to his praise and glory;
blessed be his name forever.
There were at this meeting many Friends, and other people;
some of whom were justices of the peace, and other officers,
who were generally well affected.
One of the justices, who had been one twenty years, was convinced,
and spoke highly of the truth; and more highly of me,
than is fit for me to mention or take notice of.

Then we had a meeting at Providence, which was very large,
consisting of many sorts of people; I had a great travail upon my spirit,
that it might be preserved quiet, and that truth might be brought over the people,
might gain entrance, and have a place in them; for they were generally above the priests,
in high notions; and some of them came on purpose to dispute.
But the Lord, whom we waited upon, was with us, and his power went over them all;
and his blessed Seed was exalted and set above all.
The disputers were silent, and the meeting was quiet, and ended well; praised be the Lord!
The people went away mightily satisfied, much desiring another meeting.
This place (called Providence) was about thirty miles from Rhode Island;
and we went to it by water.
The governor of Rhode Island, and many others, went with me thither;
and we had the meeting in a great barn, which was thronged with people,
so that I was exceedingly hot, and perspired much; but all was well;
the glorious power of the Lord shone over all; glory to the great God forever!

After this we went to Narraganset, about twenty miles from Rhode Island;
and the governor went with us.
We had a meeting at a justice`'s house, where Friends had never had any before.
It was very large, for the country generally came in;
and people came also from Connecticut, and other parts round about,
amongst whom were four justices of the peace.
Most of these people had never heard Friends before;
but they were mightily affected with the meeting,
and a great desire there is after the truth amongst them;
so that our meeting was of very good service, blessed be the Lord forever!
The justice at whose house the meeting was, and another justice of that country,
invited me to come again; but I was then clear of those parts,
and going towards Shelter Island.
But John Burnyeat and John Cartwright, being come out of New England into Rhode Island,
before I was gone, I laid this place before them; and they felt drawings thither,
and went to visit them.
At another place, I heard some of the magistrates said among themselves,
"`if they had money enough, they would hire me to be their minister.`"
This was, where they did not well understand us, and our principles;
but when I heard of it, I said, "`it was time for me to be gone;
for if their eye was so much to me, or any of us,
they would not come to their own teacher.`"
For this thing (hiring ministers) had spoiled many,
by hindering them from improving their own talents;
whereas our labour is to bring every one to his own teacher in himself.

I went from hence towards Shelter Island, having with me Robert Widders, James Lancaster,
George Pattison, and John Jay, a planter of Barbados.
We went in a sloop; and passing by Point Juda and Block Island,
we came to Fisher`'s Island, where at night we went on shore;
but were not able to stay for the mosquitoes which abound there,
and are very troublesome.
Wherefore we went into our sloop again, put off from the shore, and cast anchor;
and so lay in our sloop that night.
Next day we went into the Sound,
but finding our sloop was not able to live in that water, we returned again,
and came to anchor before Fisher`'s Island, where we lay in our sloop that night also.
There fell abundance of rain, and our sloop being open, we were exceedingly wet.
Next day we passed over the waters called the Two Horse Races,
and then by Garner`'s Island; after which we passed by the Gull`'s Island,
and so got at length to Shelter Island; which,
though it was but about twenty-seven leagues from Rhode Island,
yet through the difficulty of passage we were three days in reaching.
The day after, being First-day, we had a meeting there.
In the same week, I had another among the Indians; at which were their king, his council,
and about a hundred Indians more.
They sat down like Friends, and heard very attentively,
while I spoke to them by an interpreter, an Indian that could speak English well.
After the meeting they appeared very loving,
and confessed that what was said to them was truth.
Next First-day we had a great meeting on the island,
to which came many people who had never heard Friends before.
They were very well satisfied with it, and would not go away when it was over,
till they had spoken with me; wherefore I went amongst them,
and found they were much taken with the truth; good desires were raised in them,
and great love.
Blessed be the Lord, his name spreads, and will be great among the nations,
and dreadful among the heathen.

While we were in Shelter Island, William Edmundson came to us,
who had been labouring in the work of the Lord in Virginia.
From whence he travelled through the desert-country,
through difficulties and many trials, till he came to Roan-oak,
where he met with a tender people.
After seven weeks`' service in those parts, sailing over to Maryland and so to New York,
he came to Long Island, and so to Shelter Island; where we met with him,
and were very glad to hear from him the good service he had had for the Lord,
in the several places where he had travelled since he parted from us.

We stayed not long in Shelter Island,
but entering our sloop again put to sea for Long Island.
We had a very rough passage, for the tide ran so strong for several hours,
that I have not seen the like; and being against us, we could hardly get forwards,
though we had a gale.
We were upon the water all that day and the night following;
but found ourselves next day driven back near to Fisher`'s Island.
For there was a great fog, and towards day it was very dark,
so that we could not see what way we made.
Besides, it rained much in the night, which in our open sloop made us very wet.
Next day a great storm arose, so that we were fain to go over the Sound,
and got over with much difficulty.
When we left Fisher`'s Island, we passed by Faulcon Island, and came to the Main,
where we cast anchor till the storm was over.
Then we crossed the Sound, being all very wet; and much difficulty we had to get to land,
the wind being strong against us.
But blessed be the Lord God of heaven and earth, and of the seas and waters, all was well.
We got safe to Oyster-Bay in Long Island, on the seventh of sixth month,
very early in the morning, which is about two hundred miles from Rhode Island.
At Oyster-Bay we had a very large meeting.
The same day James Lancaster and Christopher Holder ^
footnote:[This is the only mention of Christopher Holder in these volumes.
He was a great sufferer in the New England persecution.
In 1657 he and another Friend being at Salem, went to the Puritan place of worship there,
and after the priest had concluded, Christopher Holder addressing the assembly,
was not allowed to proceed; one of the commissioners, with much fury,
"`seizing him by the hair of his head,`" and violently
thrusting a glove and handkerchief into his mouth.
These two Friends were subsequently sentenced,
under "`the law against Quakers,`" to receive thirty lashes.
The brutal manner in which this sentence was carried out,
was in accordance with the spirit that prompted the rulers to pass the cruel law.
A three-corded knotted whip was used on the occasion; and the executioner,
to make more sure of his blows,
"`measured his ground,`" and then "`fetched his strokes with all his might.`"
Thirty strokes thus inflicted, as will be readily imagined,
left the sufferers miserably torn and lacerated;
and in this state they were conveyed to their prison cell.
Here, without any bedding, or even straw to lie on,
the inhuman jailer kept them for three days without food or drink; and,
in this dismal abode, often exposed to damp and cold,
were these faithful men confined for the space of nine weeks.
We may wonder that, under such aggravated cruelties, their lives were spared; but He,
for whose holy cause they thus suffered, was near to support and console them.
His ancient promise was fulfilled in their experience,
and they rejoiced in the comforting presence of his living power.--
Bowden`'s _History of Friends in America._
{footnote-paragraph-split}
Previous to this,
Christopher Holder and his companion had been banished from Rhode Island.
The governor having hired an Indian to convey them off the island,
ordered the Friends to pay for the passage themselves.
But not being willing to facilitate their own banishment,
and not feeling that it was their Divine Master`'s will for them to leave the island,
they declined to go, or to pay the Indian who was hired to take them.
The governor directed the constable forcibly to
obtain the requisite sum from the strangers,
and gave peremptory orders to the natives to take them away in their canoes.
The Algonquins, however,
not being in any great haste to execute the bidding of the governor,
contrary to the will of the Friends, and at a time too when the weather was stormy,
entertained them for three days with marked kindness and hospitality.
A change in the weather then taking place,
and the banished ones feeling that it was no
longer required of them to stay on the island,
the Indians, at their own request, prepared to take them across.
Before leaving the island,
the Friends offered to remunerate the natives for their kindness, but these poor people,
from the generous impulses of their hearts, acting more in unison with the spirit of
Christianity than those who were wont to be their teachers,
declined to receive any reward.
"`You are strangers,`" they replied, "`and Jehovah hath taught us to love strangers.`"
Such simple and feeling language from the lips of North American Indians,
was a striking rebuke to the bigotry and intolerance which marked the
conduct of their highly professing teachers.--
Bowden`'s _History of Friends in America._]
went over the Bay to Rye,
on the continent, in Governor Winthrop`'s government, and had a meeting there.
From Oyster-Bay we passed about thirty miles to Flushing,
where we had a very large meeting; many hundreds of people being there,
some of whom came about thirty miles to it.
A glorious and heavenly meeting it was (praised be the
Lord God!) and the people were much satisfied.
Meanwhile Christopher Holder and some other Friends went to a town in Long Island,
called Jamaica, and had a meeting there.
We passed from Flushing to Gravesand, about twenty miles,
and there had three precious meetings; to which many would have come from New York,
but the weather hindered them.
Being clear of this place, we hired a sloop; and the wind serving,
set out for the New Country, now called Jersey.
Passing down the Bay by Conny Island, Natton Island, and Stratton Island,
we came to Richard Hartshorn`'s, at Middletown-harbour, about break of day,
the 27th of sixth Month.
Next day we rode about thirty miles into the
country through the woods and over very bad bogs,
one worse than all the rest; the descent into which was so steep,
that we were fain to slide down with our horses, and then let them lie and breathe,
before they could go on.
This place the people of the country called Purgatory.
We got at length to Shrewsbury in East Jersey,
and on First-day had a precious meeting there,
to which Friends and other people came from far;
and the blessed presence of the Lord was with us.
The same week we had a men`'s and women`'s meeting out of most parts of New Jersey.
They are building a meeting-place in the midst of them,
and there is a monthly and general meeting set up;
which will be of great service in those parts,
in "`keeping up the gospel order and government of
Christ Jesus (of the increase of which there is no end),
that they who are faithful,
may see that all who profess the holy truth live in the pure religion,
and walk as becometh the gospel.`"

While we were at Shrewsbury an accident befell, which, for the time,
was a great exercise to us.
John Jay, a Friend of Barbados, who came with us from Rhode Island,
and intended to accompany us through the woods to Maryland, being to try a horse,
got upon his back; and the horse fell a-running, and cast him down upon his head,
and broke his neck, as the people said.
They that were near him took him up as dead, carried him a good way,
and laid him on a tree.
I got to him as soon as I could; and feeling him, concluded he was dead.
As I stood by him, pitying him and his family, I took hold of his hair,
and his head turned any way, his neck was so limber.
Whereupon I took his head in both my hands, and setting my knees against the tree,
I raised his head, and perceived there was nothing out or broken that way.
Then I put one hand under his chin, and the other behind his head,
and raised his head two or three times with all my strength, and brought it in.
I soon perceived his neck began to grow stiff again,
and then he began to rattle in the throat, and quickly after to breathe.
The people were amazed; but I bid them have a good heart, be of good faith,
and carry him into the house.
They did so, and set him by the fire.
I bid them get him something warm to drink, and put him to bed.
After he had been in the house a while he began to speak;
but did not know where he had been.
The next day we passed away (and he with us,
pretty well) about sixteen miles to a meeting at Middletown, through woods and bogs,
and over a river; where we swam our horses, and got over ourselves upon a hollow tree.
Many hundred miles did he travel with us after this.

To this meeting came most of the people of the town.
A glorious meeting we had, and the truth was over all;
blessed be the great Lord God forever!
After the meeting we went to Middletown-harbour about five miles,
in order to take our long journey next morning, through the woods towards Maryland;
having hired Indians for our guides.
I determined to pass through the woods on the other side of Delaware-Bay,
that we might head the creeks and rivers as much as possible.
On the 9th of the 7th month we set forwards, and passed through many Indian towns,
and over some rivers and bogs; and when we had rode about forty miles,
we made a fire at night, and laid by it.
As we came among the Indians, we declared the day of the Lord to them.
Next day we travelled fifty miles, as we computed; and at night, finding an old house,
which the Indians had forced the people to leave, we made a fire and stayed there,
at the head of Delaware-Bay.
Next day we swam our horses over a river about a mile, at twice,
first to an island called Upper Dinidock, and then to the mainland;
having hired Indians to help us over in their canoes.
This day we could reach but about thirty miles, and came at night to a Swede`'s house,
where we got a little straw, and stayed that night.
Next day, having hired another guide, we travelled about forty miles through the woods,
and made a fire at night, by which we lay, and dried ourselves;
for we were often wet in our travels.
The next day we passed over a desperate river,
which had in it many rocks and broad stones, very hazardous to us and our horses.
Thence we came to Christian River, where we swam over our horses,
and went over ourselves in canoes; but the sides of this river were so bad and miry,
that some of the horses had like to have been laid up.
Thence we came to Newcastle, heretofore called New Amsterdam; and being very weary,
and inquiring in the town where we could buy some corn for our horses,
the governor came and invited me to his house; and afterwards desired me to lodge there,
saying he had a bed for me, and I should be welcome.
So I stayed there, the other Friends being taken care of also.
This was on the seventh day of the week; and he offering his house for a meeting,
we had the next day a pretty large one; for most of the town were at it.
There had never been a meeting here before, nor any within a great way of it;
but this was a very precious one, many of the people were tender,
and confessed to the truth; and some received it: blessed be the Lord forever!

On the 16th of the 7th month we set forward again, and travelled,
as near as we could compute, about fifty miles, through woods and over bogs,
heading Bohemia and Saxierax Rivers.
At night we made a fire in the woods, and lay there all night;
and it being rainy weather, we got under some thick trees for shelter,
and afterwards dried ourselves again by the fire.
Next day we waded through Chester River, a very broad water,
and after passing through many bad bogs, lay that night also in the woods by a fire;
not having gone above thirty miles that day.
The day following we travelled hard; and though we had some troublesome bogs in our way,
we rode about fifty miles; and got safe that night, but very weary, to Robert Harwood`'s,
at Miles River in Maryland.
This was the eighteenth of the month; and though we were very weary,
and much dirted with getting through the bogs in our journey,
yet hearing of a meeting next day, we went to it, and then to John Edmundson`'s;
from whence we went three or four miles by water to a meeting the First-day following.
Here was a judge`'s wife, who had never been at any of our meetings before;
who was reached, and said after,
"`she had rather hear us once than the priests a thousand times.`"
Many others also were very well satisfied;
for the power of the Lord was eminently with us; blessed forever be his holy name!
We passed thence about twenty-two miles, and had a meeting upon the Kentish shore,
to which one of the judges came; and a good meeting it was.
Then, after another meeting hard by, at Henry Wilcock`'s house,
where also we had good service for the Lord,
we went by water about twenty miles to a very large meeting,
where were some hundreds of people, four justices of the peace,
the high-sheriff of Delaware, an Indian emperor or governor, and two chiefs.
With these Indians I had a good opportunity the night before.
I spoke to them by an interpreter; they heard the truth attentively, and were very loving.
A blessed meeting this was, and of great service,
both for convincing and establishing in the truth them that were convinced of it.
Blessed be the Lord, who causeth his blessed truth to spread!
After the meeting a woman came to me,
whose husband was one of the judges of that part of the country,
and a member of the assembly, and told me, "`her husband was sick, not likely to live;
and desired me to go home with her to see him.`"
It was three miles to her house; and being just come hot out of the meeting,
it was hard for me then to go; yet considering the service, I got a horse, went with her,
visited her husband, and spoke what the Lord gave me to him.
The man was much refreshed, and finally raised up by the power of the Lord;
and he afterwards came to our meetings.
I went back again to the Friends that night;
and next day we departed thence about twenty miles to Tredhaven-Creek,
to John Edmundson`'s again; whence, on the 3rd of the 8th month,
we went to the general meeting for all Maryland Friends.

This held five days; the first three meetings for public worship,
to which people of all sorts came; the other two men`'s and women`'s meetings.
To the public meetings came many Protestants of divers sorts, and some Papists;
amongst these were several magistrates and their wives,
and other persons of chief account in the country.
There were so many, besides Friends,
that it was thought there were sometimes a thousand people at one of these meetings.
So that, though they had not long before enlarged their meeting-place,
and made it as large again as it was before, it could not contain the people.
I went by boat every day four or five miles to it,
and there were so many boats at that time passing upon the river,
that it was almost like the Thames.
The people said, "`there were never so many boats seen there together before.`"
And one of the justices said,
"`he never saw so many people together in that country before.`"
It was a very heavenly meeting,
wherein the presence of the Lord was gloriously manifested,
and Friends were sweetly refreshed, the people generally satisfied, and many convinced;
for the blessed power of the Lord was over all;
everlasting praises to his holy name forever!
After the public meetings were over, the men`'s and women`'s meetings began,
and were held the other two days;
for I had something to impart to them which concerned the glory of God,
the order of the gospel, and the government of Christ Jesus.
When these meetings were over, we took our leave of Friends in those parts,
whom we left well established in the truth.

On the 10th of the 8th Month we went thence about thirty miles by water,
passing by Cranes Island, Swan Island, and Kent Island,
in very foul weather and much rain;
whereby (our boat being open) we were not only very much wet,
but in great danger of being overset;
insomuch that some thought we could not escape being cast away,
till they saw us come to shore next morning.
But blessed be God, we were very well.
Having got to a little house, dried our clothes by the fire,
and refreshed ourselves a little, we took to our boat again; and put off from land,
sometimes sailing and sometimes rowing; but having very foul weather that day too,
we could not get above twelve miles forward.
At night we got to land, and made a fire; some lay by that,
and some by a fire at a house a little way off.
Next morning we passed over the Great-bay, and sailed about forty miles that day.
Making to shore at night, we lay there, some in the boat, and some at an ale-house.
Next morning, being First-day, we went six or seven miles to a Friend`'s house,
who was a justice of the peace; where we had a meeting:
this was a little above the head of the Great-Bay.
We were almost four days on the water, weary with rowing, yet all was very well:
blessed and praised be the Lord.
We went next day to another Friend`'s house, near the head of Hatton`'s Island,
where we had good service amongst Friends and others;
as we had also the day following at George Wilson`'s,^
footnote:[This George Wilson, at whose house George Fox was entertained,
is not mentioned elsewhere in the Journal.
He was originally from Great Britain,
and a great sufferer for the truth during the New England persecution.
In 1661, it appears he was amongst twenty-seven other Friends in prison in Boston,
who were liberated that year by an order from the home government.
But these faithful messengers of the Lord,
who were thus unexpectedly released from bondage, were concerned,
almost immediately on leaving the jail,
to preach to the inhabitants those truths for which they had suffered.
The magistrates, already at their wits`' end,
in fruitlessly endeavouring to arrest the spread of Quaker principles,
being impatient at this fresh manifestation of devotedness,
ordered a guard of soldiers to drive all the Friends
out of their territory into the wilderness;
an order which was speedily executed.
George Wilson was among those who were thus forcibly expelled; but,
undismayed by the new law for the application of the whip,
they returned at once to their homes.
There they were quickly apprehended,
and were sentenced to undergo a flogging through three towns,
and to be put out of the limits of the colony.
The executioner,
desirous of lending his ingenuity to increase the severity of the sentence,
provided himself with a singularly constructed whip, or as it is called,
a "`cruel instrument,`" with which he "`miserably tore`" the bodies of the sufferers.
Such was the new and barbarous character of the weapon used on this occasion,
that Friends endeavoured, though unsuccessfully, to obtain it to send to England,
as another proof of the malignant cruelty which actuated the
rulers of Massachusetts towards the new Society.
At the conclusion of this whipping at Boston, George Wilson,
in the midst of his persecutors,
knelt in solemn supplication to the Most High.
{footnote-paragraph-split}
Being on a gospel mission in Virginia,
George Wilson became a victim to the reigning intolerance,
and was incarcerated in the dungeon at James`' Town.
The circumstances of his case evinced great barbarity on the part of his persecutors.
The place of his imprisonment was an extremely loathsome one,
without light or ventilation.
Here, after being cruelly scourged and heavily ironed for a long period,
he had to feel the heartlessness of a persecuting and dominant hierarchy; until, at last,
his flesh actually rotted from his bones, and,
within the cold damp walls of the miserable dungeon of James`' Town,
he laid down his life a faithful martyr for the testimony of Jesus.
{footnote-paragraph-split}
The patience and resignation with
which George Wilson bore his aggravated sufferings,
and his faithfulness unto death,
form a striking instance of the inflexible adherence to conscientious conviction,
which so remarkably characterized the early Friends.
Living near to Him who is the fountain and fulness of love,
his enemies also became the objects of his solicitude; and,
whilst lingering in the wretched dungeon,
his heart was lifted up in prayer for his persecutors.
"`For all their cruelty,`" he writes, "`I can truly say, Father, forgive them,
for they know not what they do.`"--Bowden`'s _History of Friends in America_.]
a Friend that lived about three miles further; where we had a very precious meeting,
there being great tenderness amongst the people.

After this meeting we sailed about ten miles to James Frizby`'s, a justice of the peace,
where, on the 16th, we had a very large meeting, at which, besides Friends,
were some hundreds of people it was supposed; amongst whom were several justices,
captains, and the sheriff, with other persons of note.
A blessed, heavenly meeting this was; a powerful,
thundering testimony for truth was borne therein;
a great sense there was upon the people, and much brokenness and tenderness amongst them.
We stayed after meeting till about eleven at night, that the tide turned for us;
then taking boat, we passed that night and next day about fifty miles,
to another Friend`'s house.
The two next days we made short journeys, visiting Friends,
and on the twentieth we had a great meeting at a place called Severn,
where there was a meetinghouse, but not large enough to hold the people.
Divers chief magistrates were at it, and many other considerable people,
and it gave them generally great satisfaction.
Two days after we had a meeting with some that walked disorderly, and had good service.
Then spending a day or two in visiting Friends, we passed to the Western-Shore;
and on the twenty-fifth had a large and precious meeting at William Coale`'s,^
footnote:[William Coale, a Friend of Maryland, was convinced about the year 1657.
He was a man of an innocent and tender spirit;
and a living and weighty minister of the gospel of Christ.
He visited Friends in Virginia with George Wilson, and was very serviceable,
some being turned to the Lord through his ministry, and many established in the truth.
He suffered cruel imprisonment for the gospel,
which injured him so much that he never recovered it.
In the time of his last illness he was cheerful, freely given up to die, saying,
"`The living presence of the Lord is with me;`" with many more words
of the great satisfaction he had from the Lord concerning his peace;
adding, "`I bless the Lord, I have finished my course,
and I have nothing to do but to wait on the Lord and die.`"
He departed very peaceably and quietly about the year 1678.]
where the speaker of their assembly, his wife, a justice,
and several other people of quality were present.
Next day we had a meeting six or seven miles further, at Abraham Birkkead`'s,
where many of the magistrates and upper sort of people were,
and the speaker of the assembly for that country was convinced: a blessed meeting it was,
praised be the Lord!
We travelled next day; and the day following, the 28th,
had a large and very precious meeting at Peter Sharp`'s, on the Cliffs,
between thirty and forty miles distant from the former.
Many of the magistrates and people of upper rank were at this meeting,
and a heavenly meeting it was.
The wife of one of the governor`'s council was convinced,
and her husband was very loving to Friends.
A justice from Virginia was convinced, and had a meeting afterwards at his house.
Some Papists were at this meeting, and one of them threatened before he came,
that he would dispute with me; but he was reached, and could not oppose.
Blessed be the Lord, the truth reached into the hearts of people beyond words,
and it is of a good savour amongst them!
After the meeting we went about eighteen miles, to James Preston`'s,
a Friend that lived on Patuxent river; and thither came to us an Indian king,
with his brother, to whom I spoke, and found they understood what I spoke of.
Having finished our service in Maryland, and intending for Virginia,
we had a meeting at Patuxent on the 4th of the 9th Month, to take our leave of Friends.
Many people of all sorts were at it, and a powerful meeting it was.

On the 5th we set sail for Virginia, and in three days came to a place called Nancemum,
about two hundred miles from Maryland.
In this voyage we met with foul weather, storms, and rain,
and lay in the woods by a fire in the night.
At Nancemum lived a Friend, called the widow Wright.
Next day we had a great meeting there, of Friends and others.
There came to it Colonel Dewes, with several other officers and magistrates,
who were much taken with the truth declared.
After this, we hastened towards Carolina; yet had several meetings by the way,
wherein we had good service for the Lord; one about four miles from Nancemum Water,
which was very precious; and there was a men`'s and women`'s meeting settled,
for taking care of the affairs of the church.
Another very good one also we had at William Yarrow`'s, at Pagan Creek,
which was so large, that we were fain to be abroad,
the house not being large enough to contain the people.
A great openness there was, the sound of truth spread abroad,
and had a good savour in the hearts of people: the Lord have the glory forever!

After this our way to Carolina grew worse, being much of it plashy,
and pretty full of great bogs and swamps; so that we were commonly wet to the knees,
and lay abroad at nights in the woods by a fire; saving one night we got to a poor house,
at Sommertown, and lay by the fire.
The woman of the house had a sense of God upon her.
The report of our travel had reached thither,
and drawn some that lived beyond Sommertown, to that house,
in expectation to see and hear us (so acceptable was the sound
of truth in that wilderness country), but they missed us.
The next day, the 21st of the 9th Month, having travelled hard through the woods,
and over many bogs and swamps, we reached Bonner`'s Creek;
and there we lay that night by the fireside, the woman lending us a mat to lie on.

This was the first house we came to in Carolina; here we left our horses,
over-wearied with travel.
From hence we went down the creek in a canoe, to Macocomocock River;
and came to Hugh Smith`'s house,
where the people of other professions came to see us
(for there were no Friends in that part of the country),
and many of them received us gladly.
Amongst others came Nathaniel Batts, who had been governor of Roan-Oak;
he went by the name of Captain Batts, and had been a rude, desperate man.
He asked me about a woman in Cumberland, who, he said, he was told,
had been healed by our prayers, and laying on of hands, after she had been long sick,
and given over by the physicians; and he desired to know the certainty of it.
I told him we did not glory in such things,
but many such things had been done by the power of Christ.

Not far from hence we had a meeting among the people, and they were taken with the truth:
blessed be the Lord!
Then passing down the river Maratick in a canoe, we went down the bay Connie-oak,
and came to a captain`'s house, who was very loving, and lent us his boat,
for we were much wet in the canoe, the water splashing in upon us.
With this boat we went to the governor`'s house;
but the water in some places was so shallow that the boat being laden, could not swim;
so that we were fain to put off our shoes and stockings,
and wade through the water some distance.
The governor, with his wife, received us lovingly;
but a doctor there would needs dispute with us.
And truly his opposing us was of good service,
giving occasion for the opening of many things to the people,
concerning the light and Spirit of God, which he denied to be in every one;
and affirmed that it was not in the Indians.
Whereupon I called an Indian to us, and asked him, "`Whether or not, when he lied,
or did wrong to any one, there was not something in him that reproved him for it?`"
he said, "`There was such a thing in him, that did so reprove him;
and he was ashamed when he had done wrong, or spoken wrong.`"
So we shamed the doctor before the governor and the people;
insomuch that the poor man ran out so far,
that at length he would not own the Scriptures.
We tarried at the governor`'s that night;
and next morning he very courteously walked with
us himself about two miles through the woods,
to a place whither he had sent our boat about to meet us.
Taking leave of him, we entered our boat,
and went that day about thirty miles to Joseph Scott`'s,
one of the representatives of the country.
There we had a sound, precious meeting; the people were tender,
and much desired after meetings.
Wherefore at a house about four miles further, we had another meeting,
to which the governor`'s secretary came, who was chief secretary of the province,
and had been formerly convinced.

I went from this place among the Indians, and spoke unto them by an interpreter;
showing them, "`that God made all things in six days, and made but one woman for one man;
and that God drowned the old world, because of their wickedness.
Afterwards I spoke to them concerning Christ, showing them, that he died for all men,
for their sins, as well as for others; and had enlightened them as well as others;
and that if they did that which was evil, he would burn them, but if they did well,
they should not be burned.`"
There was among them their young king; and others of their chief men,
who seemed to receive kindly what I said to them.
Having visited the north part of Carolina,
and made a little entrance for truth upon the people there,
we began to return towards Virginia, having several meetings in our way,
wherein we had very good service for the Lord,
the people being generally tender and open; blessed be the Lord.
We lay one night at the secretary`'s house, to which we had much to do to get;
for the water being shallow, we could not bring our boat to shore;
but the secretary`'s wife seeing our strait,
came herself in a canoe (her husband being from home) and brought us to land.
Next morning our boat was sunk; but we got her up, mended her,
and went away in her that day about twenty-four miles, the water being rough,
and the winds high; but the great power of God was seen,
in carrying us safe in that rotten boat.
In our return we had a very precious meeting at Hugh Smith`'s;
praised be the Lord forever!
The people were very tender, and very good service we had amongst them.
There was at this meeting an Indian captain who was very loving,
and acknowledged it to be truth that was spoken.
There was also one of the Indian priests, whom they call a Pawaw,
who sat soberly among the people.
On the 9th of the 10th Month we got back to Bonner`'s Creek, where we had left our horses;
having spent about eighteen days in North Carolina.

Our horses having rested, we set forward for Virginia again,
travelling through the woods and bogs, as far as we could well reach that day;
and at night lay by a fire in the woods.
Next day we had a tedious journey through bogs and swamps,
and were exceedingly wet and dirty all the day, but dried ourselves at night by a fire.
We got that night to Sommertown.
When we came near the house, the woman of the house seeing us,
spoke to her son to fasten up their dogs (for both in Virginia and
Carolina they generally keep great dogs to guard their houses,
living lonely in the woods); but the son said, "`he need not,
for the dogs did not use to meddle with these people.`"
Whereupon, when we were come into the house, she told us,
"`we were like the children of Israel,
whom the dogs did not move their tongues against.`"
Here we lay in our clothes by the fire, as we had done many a night before.
Next day, before we went away, we had a meeting; for the people having heard of us,
had a great desire to hear us; and a very good meeting we had among them,
where we never had one before; praised be the Lord forever!
After the meeting we hasted away.
When we had rode about twenty miles, calling at a house to inquire the way,
the people desired us to tarry all night with them, which we did.
Next day we came among Friends,
after we had travelled about a hundred miles from Carolina into Virginia;
in which time we observed a great variety of climates,
having passed in a few days from a very cold, to a warm and spring-like country.
But the power of the Lord is the same in all, is over all,
and doth reach the good in all; praised be the Lord forever!

We spent about three weeks in travelling through Virginia, mostly among Friends,
having many large and precious meetings in several parts of the country;
as at the widow Wright`'s, where a great many magistrates, officers,
and other high people came.
A most heavenly meeting we had, wherein the power of the Lord was so great,
that it struck a dread upon the assembly and chained all down,
and brought a reverence upon the people`'s minds.
Among the officers was a major, kinsman to the priest; he told me,
"`the priest threatened to come and oppose us.`"
But the Lord`'s power was too strong for him, and stopped him;
we were quiet and peaceable,
and the people were wonderfully affected with the testimony of truth;
blessed be the Lord forever!
Another very good meeting we had at Crickatrough, at which many considerable people were,
many of whom had never heard a Friend before;
and they were greatly satisfied with the meeting, praised be the Lord!
We had also a very good and serviceable meeting at John Porter`'s,
which consisted mostly of other people;
in which the power of the Lord was gloriously seen and felt,
and it brought the truth over all evil walkers and talkers; blessed be the Lord!
Divers other meetings we had,
and many opportunities of doing service for the Lord amongst the people where we came.
The last week we stayed, we spent some time and pains among Friends,
sweeping away that which was to be swept out,
and working down a bad spirit that was got up in some;
blessed forever be the name of the Lord! he it is that gives victory over all.

Having finished what service lay upon us in Virginia,
on the 30th we set sail in an open sloop for Maryland.
But having a great storm, and being much wet, we were glad to get to shore before night;
and, walking to a house at Willoughby Point, we got lodging there that night.
The woman of the house was a widow, and a very tender person;
she had never received Friends before; but she received us very kindly,
and with tears in her eyes.
We returned to our boat in the morning, and hoisted up our sail,
getting forward as fast as we could; but towards evening a storm rising,
we had much to do to get to shore; and our boat being open the water splashed often in,
and sometimes over us, so that we were completely wet.
Being got to land, we made a fire in the woods, to warm and dry us,
and there we lay all night, the wolves howling about us.
On the 1st of the 11th Month we sailed again, but the wind being against us,
we made but little way, and were fain to get to shore at Point Comfort,
where yet we found but small comfort; for the weather was so cold,
that though we made a good fire in the woods to lie by, our water,
that we had got for our use, was frozen near the fireside.
We made to sea again next day; but the wind being strong and against us,
we advanced but little, but were glad to get to land again,
and travel about to find some house, where we might buy some provisions,
for our store was spent.
That night also we lay in the woods; and so extremely cold was the weather,
the wind blowing high, and the frost and snow being great,
that it was hard for some to abide it.
On the 3rd, the wind setting pretty fair, we fetched it up by sailing and rowing,
and got that night to Milford-haven, where we lay at Richard Long`'s,
near Quince`'s Island.
Next day we passed by Rappahannock River, where dwell much people;
and Friends had a meeting there-aways at a justice`'s house,
who had formerly been at a meeting where I was.
We passed over Potomac River also, the winds being high, the water very rough,
our sloop open, and the weather extremely cold; and having a meeting there-aways also,
some people were convinced; and when we parted thence,
some of our company went amongst them.
We steered our course for Patuxent River, I sat at the helm most part of the day,
and some of the night.
About the first hour in the morning we reached James Preston`'s house, on Patuxent River,
which is about two hundred miles from Nancemum in Virginia.
We were very weary; yet the next day, being the first of the week,
we went to the meeting not far from thence.
The same week we went to an Indian king`'s cabin, where several of the Indians were,
with whom we had a good opportunity to discourse;
and they carried themselves very lovingly.
We went also that week to a general meeting;
then about eighteen miles further to John Geary`'s, where we had a very precious meeting;
praised be the Lord God forever!
After this the cold grew so exceedingly sharp, the frost and snow so extreme,
beyond what was usual in that country, that we could hardly endure it.
Neither was it easy or safe to stir out; yet we got, with some difficulty,
six miles through the snow to John Mayor`'s,
where we met with some Friends come from New England,
whom we had left there when we came away; and glad we were to see each other,
after so long and tedious travels.
By these Friends we understood, that William Edmundson,
having been at Rhode Island and New England, was returned to Ireland;
that Solomon Eccles, coming from Jamaica and landing at Boston in New England,
was taken at a meeting there, and banished to Barbados;
that John Stubbs and another Friend were gone into New Jersey,
and several other Friends to Barbados, Jamaica, and the Leeward Islands.
It was matter of joy to us,
to understand that the work of the Lord went on and prospered,
and that Friends were unwearied and diligent in the service.

On the 27th we had a very precious meeting in a tobacco-house;
and next day returned to James Preston`'s, about eighteen miles distant.
When we came there, we found his house was burnt to the ground the night before,
through the carelessness of a servant; so we lay three nights on the ground by the fire,
the weather being very cold.
We made an observation, which was somewhat strange, but certainly true;
that one day in the midst of this cold weather, the wind turning into the South,
it grew so hot that we could hardly bear it; and the next day and night,
the wind changing back into the North, we could hardly endure the cold.

The 2nd of 12th month we had a glorious meeting at Patuxent;
and after it went to John Geary`'s again,
where we waited for a boat to carry us to the monthly meeting at the Cliffs,
and a living one it was; praised be the Lord!
This was on the 6th: another meeting we had on the 9th,
wherein the glory of the Lord shone over all;
blessed and magnified be his holy name forever!

On the 12th month we set forward in our boat; and, travelling by night,
ran aground in a creek near Hanaco River.
There we were fain to stay till morning, when the tide came and lifted her off.
In the meantime sitting in an open boat, and the weather being bitter cold,
some of us had like to have lost the use of our hands,
they were so frozen and benumbed with cold.
In the morning, when the tide had set us afloat again, we got to land,
and made a good fire, at which we warmed ourselves well.
Then returning to our boat,
we passed on about ten miles further to a Friend`'s house;
where next day we had a very precious meeting,
at which some of the chief of the place were.
I went after it to a Friend`'s house, about four miles off, at the head of Anamessy River,
where, on the day following,
the judge of the country and the justice with him came to me, and were very loving,
and much satisfied with Friends`' order.
The next day we had a large meeting in the justice`'s barn,
for his house could not hold the company.
There were several of the great folks of that country, and among the rest an opposer;
but all was preserved quiet and well; a precious meeting it was,
and the people were much affected with the truth; blessed be the Lord!
We went next day to see Captain Colburn, who was also a justice,
and there we had some service; then returning again,
we had a very glorious meeting at the same justice`'s, where we met before;
to which came many people of account in the world, magistrates, officers, and others.
It was large, and the power of the Lord was much felt,
so that the people were generally well satisfied, and taken with the truth;
and there being several merchants and masters of ships from New England,
the truth was spread abroad; blessed be the Lord!

A day or two after, we travelled about sixteen miles through the woods and bogs,
heading Anamessy River and Ahoroca River, part of which last we went over in a canoe,
and came to Manaoke, to a friendly woman`'s house; where, on the 24th,
we had a large meeting in a barn.
The Lord`'s living presence was with us, and among the people;
blessed be his holy name forevermore!
Friends had never had a meeting in those parts before.
After this we passed over the River Wicocomaco,
through many bad and watery swamps and marshy ways, and came to James Jones`'s, a Friend,
and a justice of the peace; where we had a large and very glorious meeting;
praised be the Lord God!
Then passing over the water in a boat,
we took horse and travelled about twenty-four miles through woods and troublesome swamps,
and came to another justice`'s house, where we had a very large meeting, much people,
and many of considerable account being present;
and the living presence of the Lord was amongst us, praised forever be his holy name!
This was on the 3rd of the 1st month, 1672-1673;^
footnote:[The difference implied here and elsewhere in
the date is between the old style and the new.
The above may be read either, the 3rd of the 11th month, 1672;
or the 3rd of the 1st month, 1673.
It would appear that an alteration in the mode of reckoning did not
take place generally till made by Act of Parliament in 1752,
when the Friends also adopted a change in the mode of reckoning the months,
which is explained at large in the _Book of Discipline,_ p. 73.]
and on the 5th we had another living and heavenly meeting,
at which divers of the justices, with their wives, and many other people, were;
amongst whom we had very good service for the Lord; blessed be his holy name!
At this meeting was a woman that lived at Anamessy,
who had been many years in trouble of mind,
and sometimes would sit moping near two months together,
and hardly speak or mind anything.
When I heard of her, I was moved of the Lord to go to her, and tell her,
"`that salvation was come to her house.`"
After I had spoken the word of life to her, and entreated the Lord for her, she mended,
went up and down with us to meetings, and is since well, blessed be the Lord!

Being now clear of these parts, we left Anamessy on the 7th,
and passing by water about fifty miles, came to a friendly woman`'s house at Hunger River.
We had very rough weather in our passage to this place, and were in great danger,
for the boat had nearly been turned over;
but through the good providence of God we got safe thither; praised be his name!
At this place we had a meeting; and amongst the people were two Papists,
a man and a woman; he was very tender, and she confessed to the truth.
This meeting was not so large as it would have been, if many, who had intended,
could have got to it; but the weather was so foul, and the water,
by reason of high winds, so rough, that it was not safe to pass over it.
I had no Friend now with me but Robert Widders,
the rest having dispersed themselves into several parts
of the country in the service of truth.

As soon as the wind would permit, we passed hence about forty miles by water,
rowing most part of the way, and came to the head of Little Choptauk Kiveb,
to Dr. Winsmore`'s, who was a justice, lately convinced.
Here we met with some Friends, with whom we stayed a while;
and then went on by land and water, and had a large meeting out of doors,
for the house we were at could not receive the people.
Divers of the magistrates and their wives were present, and a good meeting it was;
blessed be the Lord, who is making his name known in that wilderness country!
We returned thence to a Friend`'s house, named William Stephens,
where we met the Friends that had been travelling in other parts;
and were much refreshed in the Lord together,
imparting to each other the good success we had had in the Lord`'s work,
and the prosperity and spreading of truth in the places where we travelled.
John Cartwright and another Friend had been in Virginia,
where there were great desires in people after truth; and being now returned,
they stayed a little with us here, and then set forward for Barbados.
Before we left this place we had a very glorious meeting, at which were very many people;
amongst others, the judge of that country, three justices, and the high-sheriff,
with their wives.
Of the Indians was one called their emperor, an Indian king and their speaker,
who all sat very attentive, and carried themselves very lovingly.
An establishing, settling meeting it was.
This was on the 23rd of 1st month.

On the 24th we went by water ten miles to the Indian town where this emperor dwelt,
whom I had acquainted before of my coming,
and desired him to get their kings and councils together.
In the morning the emperor came himself, and had me to the town;
and they were generally come together,
and had their speaker and other officers with them, and the old empress sat among them.
They sat very grave and sober, and were all very attentive, beyond many called Christians.
I had some with me that could interpret to them,
and we had a very good meeting with them, and of very great service it was;
for it gave them a good esteem for truth and Friends; blessed be the Lord.

After this we had many meetings in several parts of that country,
one at William Stephens`'s, which was a general meeting once a month;
others at Tredhaven Creek, Wye, Reconow Creek,
and at Thomas Taylor`'s in the Island of Kent.
Most of these were large, there being many people at them,
divers of them of the most considerable account.
The Lord`'s power and living presence were with us,
and plenteously manifested amongst the people;
by which their hearts were tendered and opened to receive the truth,
which had a good savour amongst them; blessed be the Lord God over all forever.
Being clear of that side,
we passed over the bay about fourteen miles to a Friend`'s house,
where we met with several Friends.
I sent for Thomas Thurston thither, and had a meeting with him,
to bring the truth over his bad actions.

Having travelled through most parts of that country, and visited most of the plantations,
having sounded the alarm to all people where we came,
and proclaimed the day of God`'s salvation amongst them,
we found our spirits began to be clear of these parts of the world,
and draw towards Old England again.
Yet we were desirous, and felt freedom from the Lord,
to stay over the general meeting for the province of Maryland (which drew
nigh) that we might see Friends generally together before we departed.
Wherefore spending our time, in the interim, in visiting Friends and friendly people,
in attending meetings about the Cliffs and Patuxent,
and in writing answers to cavilling objections,
which some of truth`'s adversaries had raised and spread abroad,
to hinder people from receiving the truth, we were not idle,
but laboured in the work of the Lord, until that general provincial meeting came on,
which began on the 17th of the 3rd month, and lasted four days.
On the first of these, the men and women had their meetings for business,
wherein the affairs of the church were taken care of,
and many things relating thereto were opened unto them, to their edification and comfort.
The other three days were spent in public meetings for the worship of God,
at which divers of considerable account in the government, and many others, were present,
who were generally satisfied, and many of them reached; for it was a wonderful,
glorious meeting, and the mighty presence of the Lord was seen and felt over all;
blessed and praised be his holy name forever, who over all giveth dominion!

After this meeting we took our leave of Friends, parting in great tenderness,
in the sense of the heavenly life and virtuous power of the Lord,
that was livingly felt amongst us;
and went by water to the place where we were to take shipping,
many Friends accompanying us thither and tarrying with us that night.
Next day, the 21st of the 3rd month, 1673, we set sail for England;
the same day Richard Covell came on board our ship,
having had his own taken from him by the Dutch.
We had foul weather and contrary winds, which caused us to cast anchor often,
so that we were till the 31st ere we could get past the
capes of Virginia and come out into the main sea.
But after this we made good speed,
and on the 28th of the 4th month cast anchor at King`'s Road,
which is the harbour for Bristol.
We had on our passage very high winds and tempestuous weather,
which made the sea exceedingly rough, the waves rising like mountains;
so that the masters and sailors wondered at it, and said they never saw the like before.
But though the wind was strong, it set for the most part with us,
so that we sailed before it; and the great God who commands the winds,
who is Lord of heaven, of earth, and the seas, and whose wonders are seen in the deep,
steered our course and preserved us from many imminent dangers.
The same good hand of Providence that went with us, and carried us safely over,
watched over us in our return, and brought us safely back again;
thanksgiving and praises be to his holy name forever!
Many sweet and precious meetings we had on board
the ship during this voyage (commonly two a week)
wherein the blessed presence of the Lord did greatly refresh us,
and often break in upon and tender the company.
