== Chapter VI.

[.chapter-synopsis]
* 1673-1675.
* George Pox writes to his wife from Bristol
* has a glorious powerful meeting there, in which he declares of three estates and three teachers
* at Slattenford meets with much opposition to the settlement of women`'s meetings
* the chief opposer, struck by the Lord`'s power, condemns his error
* at Armscott is arrested by Justice Parker, and sent to Worcester jail with Thomas Lower
* writes to his wife
* he and T. Lower write to Lord Windsor and other magistrates, with a statement of their case
* they are examined at the sessions, but George Fox is ensnared with the oath, and re-committed for refusing to take it
* Thomas Lower is discharged, and afterwards visits Justice Parker, and gives the priest of the parish (who instigated their imprisonment) a severe rebuke in his presence, though unknown
* George Fox disputes with Dr. Crowder on swearing
* he is removed to London by Habeas Corpus
* but ultimately remanded to Worcester
* is examined at the assizes by Judge Turner, but the case is referred to the sessions
* disputes with a priest on perfection
* brought up at the sessions and re-committed, but has liberty till the next sessions
* is again removed by Habeas Corpus, and tenders in court a declaration instead of the oath
* attends the Yearly Meeting in London
* appears again at the sessions of Worcester, and points out the flaws in his indictment
* yet he is brought in guilty and premunired
* writes to the king respecting the principle of Friends
* is seized with illness, and his life almost despaired of
* Justice Parker writes to the jailer to relax the rigour of his imprisonment
* his wife intercedes with the king for his release, which he is willing to grant by a pardon
* this George Fox could not accept, as it implied guilt
* he is once more removed by Habeas Corpus
* the under-sheriff quarrels with him for calling their ministers priests
* he is brought before the judges, and Counsellor Corbet starts a new plea, that the Court cannot imprison on a premunire
* The indictment is quashed for error, and he is freed by proclamation after nearly fourteen months`' imprisonment
* he writes many papers and pamphlets in Worcester jail.

When we came into Bristol Harbour, there lay a man-of-war,
and the press-master came on board us to press our men.
We had a meeting at that time in the ship with the seamen before we went to shore,
and the press-master sat down with us and stayed the meeting,
and was very well satisfied with it.
I spoke to him to leave two of the men he had
pressed in our ship (for he had pressed four),
one of whom was a lame man; and he said, "`at my request, he would.`"

We went on shore that afternoon, and got to Shirehampton, where we obtained horses,
and rode to Bristol that night, where Friends received us with great joy.
In the evening I wrote a letter to my wife, to give her notice of my landing;
as follows:--

[.salutation]
"`Dear Heart,

"`This day we came into Bristol near night, from the sea;
glory to the Lord God over all for ever, who was our convoy,
and steered our course! the God of the whole earth, of the seas and winds,
who made the clouds his chariot, beyond all words, blessed be his name for ever!
He is over all in his great power and wisdom, Amen.
Robert Widders and James Lancaster^
footnote:[This is nearly the last mention of James Lancaster,
whose name occurs so often in these volumes.
Perhaps there was no one who associated so much in gospel labours with George Fox us he;
not only accompanying him throughout his visit to the western hemisphere,
but was also with him during his visit to Scotland in 1657, and to Ireland in 1669,
and on these occasions it appears that he frequently acted as his amanuensis.
James Lancaster`'s residence was on the island of Walney, in Lancashire,
and he was convinced by George Fox during his first visit to that county in 1652.
In the following year he came forth as a minister, and in 1654,
went on a gospel mission to Scotland with Miles Halhead.
In 1665, he visited many of the midland counties of England.]
are with me, and we are well; glory to the Lord for ever,
who hath carried us through many perils, perils by water, and in storms,
perils by pirates and robbers,
perils in the wilderness and amongst false professors!
praises to him whose glory is over all for ever, Amen!
Therefore mind the fresh life, and live all to God in it.
I intend (if the Lord will) to stay a while this away; it may be till the fair.
So no more, but my love to all Friends.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Bristol, 28th of 4th Month, 1673.

Between this and the fair, my wife came out of the North to Bristol to me,
and her son-in-law Thomas Lower, with two of her daughters^
footnote:[When George Fox married the widow of Judge Fell, she had one son;
and seven daughters; viz., Margaret, who married John Rous; Bridgett,
married to John Draper; Isabel; Sarah, married to William Mead; Mary,
married to Thomas Lower; Susanna, married to--Ingram; and Rachel,
married to Daniel Abraham.]
came with her.
Her other son-in-law John Rous, W. Penn and his wife, and Gerrard Roberts,
came from London, and many Friends from several parts of the nation, to the fair;
and glorious, powerful meetings we had at that time,
for the Lord`'s infinite power and life was over all.
In the fresh openings whereof, I was moved to declare of

[.blurb]
=== Three Estates, and Three Teachers,

Viz: "`God was the first teacher of man and woman in Paradise;
and as long as they kept to and under his teaching, they kept in the image of God,
in his likeness, in righteousness and holiness,
and in dominion over all that he had made; in the blessed state, in the paradise of God.
But when they hearkened to the serpent`'s false teaching (who was out of truth),
disobeyed God and obeyed the serpent, in feeding upon that which God forbade them,
they lost the image of God, the righteousness and holiness,
came under the power of Satan, and were turned out of Paradise,
out of the blessed into the cursed state.
Then the promise of God was,
'`that the Seed of the woman should bruise the serpent`'s
head,`' break his power that man and woman were under,
and destroy his works.
So here were '`three states and three teachers.`'
God was the first teacher in Paradise; and whilst man kept under his teaching,
he was happy.
The serpent was the second teacher; and when man followed his teaching,
he fell into misery, into the fall from the image of God,
from righteousness and holiness,
and from the power that he had over all that God had made; and came under the serpent,
whom he had power over before.
Christ Jesus was the third teacher; of whom God saith, '`This is my beloved Son,
in whom I am well pleased, hear ye him;`' and who himself saith, '`Learn of me.`'
This is the true gospel-teacher, who bruises the head of the serpent, the false teacher,
and the head of all false teachers, and of all false religions, false ways,
false worships, and false churches.
Now Christ, who said, '`Learn of me`' and of whom the Father said, '`Hear ye Mm,`' said,
'`I am the Way to God, I am the Truth, I am the Life, and the true Light.`'
So as man and woman come to God, and are renewed up into his image, righteousness,
and holiness by Christ, thereby they come into the Paradise of God,
the state which man was in before he fell; and into a higher state than that,
to sit down in Christ that never fell.
Therefore the Son of God is to be heard in all things,
who is the Saviour and the Redeemer; who laid down his life,
and bought his sheep with his precious blood.
We can challenge all the world.
Who hath anything to say against our way?
our Saviour?
our Redeemer?
our Prophet, whom God hath raised up that we may hear,
and whom we must hear in all things?
Who hath anything against our Shepherd, Christ, Jesus, who leads and feeds us,
and we know his heavenly voice?
Who hath anything against our Bishop, in whose mouth was never guile found,
who doth oversee us in his pasture of life, that we do not go astray from God,
and out of his fold?
Who hath anything against our Priest, Christ Jesus, made higher than the heavens,
who gives us freely, and commands lis to give freely?
Who hath anything to say against our Leader and Counsellor, Christ Jesus,
who never sinned; but is holy, harmless, and separate from sinners?
God hath commanded us to hear Him; and He saith,
'`Learn of me;`' and if we should disobey God`'s and Christ`'s command,
we should be like our father Adam and mother Eve, who disobeyed God`'s command,
and hearkened to the serpent`'s teaching.
Man commands, and would force us to hear the hirelings,
who plead for sin and the body of death to the grave;
which doctrine savours of the devil`'s teaching, not of Christ`'s;
but we resolve to hear the Son, as both he and the Father command,
and in hearing the Son we hear the Father also, as the Scripture testifies.
For the author to the Hebrews says, '`God, who at sundry times, and in divers manners,
spake in time past unto the fathers by the prophets,
hath in these last days spoken unto us by his Son;`' mark that,
God hath spoken unto us (his apostles, disciples, church), by his Son.
And whereas some have objected,
that although Christ did speak both to his disciples and to the Jews,
in the days of his flesh, yet since his resurrection and ascension he doth not speak now.
The answer is, that '`as God did then speak by his Son in the days of his flesh,
so the Son, Christ Jesus, doth now speak by his Spirit.`'
Wherefore John saith in the Revelations, '`He that hath an ear let him hear,
what the Spirit saith to the churches,`' Rev. 2.
And Christ is said to '`speak from heaven,`' Heb. 12:25.
'`See that ye refuse not him that speaketh;
for if they escaped not who refused him that spake on earth,
much more shall not we escape, if we turn away from Him that speaketh from heaven.`'
They that resisted Moses`' law, who spake on earth, died for it without mercy,
which was a natural death; but they that refuse Him that speaks from heaven,
neglect and slight their own salvation,
and so die a spiritual death through unbelief and hardness of heart.
Therefore was the exhortation given of old, '`Today, if ye '`will hear his voice,
harden not your hearts, as in the provocation,`' etc.
Heb. 3:15, etc.
So that they who neglect or refuse to hear the voice of Christ,
now speaking from heaven in this his gospel-day, harden their hearts.
Let all therefore mark well these three estates and teachers;
the God of Truth was the first teacher, while man was in Paradise and in innocency.
The serpent was the second teacher, the false teacher,
who by his false teaching came to be the god of the world, which lies in wickedness.
Christ Jesus, that bruises the serpent`'s head, is the third teacher, who saith,
'`Learn of me`' and of whom God saith, '`This is my beloved Son, in whom I am well pleased,
hear ye him;`' and of whom the testimony of the saints of old was,
'`That God hath in these last days spoken unto us by his Son.`'
Thus they that come to be renewed up again into the divine, heavenly image,
in which man was at first made, will know the same God,
that was the first teacher of Adam and Eve in Paradise, to speak to them now by his Son,
who changes not; glory be to his name for ever!`"

[.small-break]
'''

Many deep and precious things were opened in those meetings by the Eternal Spirit,
which searcheth and revealeth the deep things of God.
After I had finished my service for the Lord in that city,
I departed thence into Gloucestershire, where we had many large and precious meetings;
and the Lord`'s everlasting power flowed over all.
From Gloucestershire I passed into Wiltshire, where also we had many blessed meetings.
At Slattenford, in Wiltshire, we had a very good meeting,
though we met there with much opposition from some who
had set themselves against Women`'s Meetings;
which I was moved of the Lord to recommend to Friends,
for the benefit and advantage of the church of Christ.
"`That faithful women, who were called to the belief of the truth,
being made partakers of the same precious faith,
and heirs of the same everlasting gospel of life and salvation that men are,
might in like manner come into the possession and practice of the gospel order,
and therein be meet-helps unto the men in the restoration, in the service of truth,
in the affairs of the church, as they are outwardly in civil, or temporal things.
That so all the family of God, women as well as men, might know, possess, perform,
and discharge their offices and services in the house of God,
whereby the poor might be better taken care of, the younger instructed, informed,
and taught in the way of God;
the loose and disorderly reproved and admonished in the fear of the Lord;
the clearness of persons proposing marriage more
closely and strictly inquired into in the wisdom of God;
and all the members of the spiritual body, the church,
might watch over and be helpful to each other in love.`"
But after these opposers had run into much contention and wrangling,
the power of the Lord struck down one of the chief of them, so that his spirit sunk,
and he came to be sensible of the evil he had done in opposing God`'s heavenly power,
and confessed his error before Friends;
and afterwards gave forth a paper of condemnation, wherein he declared,
"`that he did wilfully oppose (although I often warned him to take heed),
until the fire of the Lord did burn within him;
and he saw the angel of the Lord with his sword drawn in his hand,
ready to cut him off,`" etc.

Notwithstanding the opposition at the meeting at Slattenford,
yet a very good and serviceable one it was;
for occasion was thereby administered to answer their objections and cavils,
and to open the services of women in and for the church.
At this the women`'s meetings, for that county,
were established in the blessed power of God.

After this I went to Marlborough and had a meeting there,
to which some of the magistrates came, and were civil and moderate.
Then passing to Bartholomew Maylin`'s, I had a very precious meeting there;
and then went a little beyond Ore, where we had a blessed meeting, and very large,
as we had also soon after upon the border of Hampshire.
Then turning into Oxfordshire, we visited Friends there; and then went to Reading,
where we had a large meeting.
Thence passing into Buckinghamshire, we had many precious meetings in that county.
After which we visited Friends till we came to Kingston-Upon-Thames,
where my wife and her daughter Rachel met me.

I made no long stay at Kingston, but went to London,
where I found the Baptists and Socinians, with some old apostates, grown very rude,
having printed many books against us; so that I had a great travail in the Lord`'s power,
before I could get clear of that city.
But blessed be the Lord, his power came over them, and all their lying, wicked,
scandalous books were answered.
I made a short journey into some parts of Essex and Middlesex,
visiting Friends at their meetings, and their children at their schools,
and returned soon to London.
After some service there among Friends, I went to Kingston,
and thence to Stephen Smith`'s in Surrey, where was a very large meeting,
many hundreds of people attending it.
I stayed in those parts till I had cleared myself of
the service the Lord had given me to do there,
and then returned by Kingston to London, whither I felt my spirit drawn;
having heard that many Friends were taken before the magistrates,
and divers imprisoned in London and other towns,
for opening their shop-windows on holidays and fast-days (as they were called),
and for bearing testimony against all such observations of days.
Which Friends could not but do,
knowing that the true Christians did not observe
the Jews`' holidays in the apostles`' times,
neither could we observe the Heathens`' and Papists`' holidays (so
called) which have been set up amongst those called Christians,
since the apostles`' days.
For we were redeemed out of days by Christ Jesus,
and brought into the day which hath sprung from on high,
and are come into Him who is Lord of the Jewish Sabbath,
and the substance of the Jews`' signs.

After I had stayed some time in London,
labouring for some relief and ease to Friends in this case,
I took leave of Friends there, and went into the country with my wife,
and her daughter Rachel, to Hendon, in Middlesex,
and thence to William Penn`'s at Rickmansworth, in Hertfordshire, whither Thomas Lower,
who married another of my wife`'s daughters,
came next day to accompany us in our journey northward.
After we had visited Friends thereabouts, we passed to a Friend`'s house near Aylesbury,
and thence to Bray Doily`'s at Adderbury, in Oxfordshire, where, on First-day,
we had a large and precious meeting.
Truth being well spread, and Friends in those parts much increased in number,
two or three new meetings were then set up.

At night, as I was sitting at supper, I felt I was taken;
yet I said nothing then to any one of it.
But getting out next morning, we travelled into Worcestershire,
and went to John Halford`'s, at Armscott,
where we had a very large and precious meeting in his barn,
the Lord`'s powerful presence being eminently with and amongst us.
After the meeting, Friends being most of them gone, as I was sitting in the parlour,
discoursing with some Friends, Henry Parker, a justice, came to the house,
and with him one Rowland Hains, a priest of Hunniton, in Warwickshibe.
This justice heard of the meeting by means of a woman Friend,
who being nurse to a child of his,
asked leave of her mistress to go to the meeting to see me;
and she speaking of it to her husband,
he and the priest plotted together to come and break it up and apprehend me.
But from their sitting long at dinner, it being the day on which his child was sprinkled,
they did not come till the meeting was over, and Friends mostly gone.
But though there was no meeting when they came, yet I being in the house,
who was the person they aimed at, Henry Parker took me,
and Thomas Lower for company with me; and though he had nothing to lay to our charge,
sent us both to Worcester jail, by a strange sort of mittimus;
a copy of which here follows:--

[.blurb]
=== "`To the constables of Tredington, in the said county of Worcester, and to all constables and tithing-men of the several townships and villages within the said parish of Tredington, and to the keeper of the jail for the county of Worcester.

"`Complaint being made to me,
being one of His Majesty`'s justices of the peace for the said county of Worcester,
that within the said parish of Tredington in the same county,
there has of late been several meetings of divers persons,
to the number of four hundred persons and upwards at a time,
upon pretence of exercise of religion,
otherwise than what is established by the laws of England.
And many of the said persons, some of them were teachers, and came from the North,
and others from the remote parts of the kingdom;
which tends to the prejudice of the reformed and established religion,
and may prove prejudicial to the public peace.
And it appearing to me that there was, this present day, such a meeting as aforesaid,
to the number of two hundred or thereabouts, at Armscott,
in the said parish of Tredington, and that George Fox of London,
and Thomas Lower of the parish of Creed, in the county of Cornwall,
were present at the said meeting,
and the said George Fox was teacher or speaker of the said meeting;
and no satisfactory account of their settlement or place of habitation appearing to me,
and forasmuch as the said George Fox and Thomas Lower refused to give sureties to
appear at the next sessions of the peace to be holden for the said county,
to answer the breach of the common laws of England,
and what other matters should be objected against them; these are, therefore,
in His Majesty`'s name, to will and require you, or either of you,
forthwith to convey the bodies of the said George Fox and
Thomas Lower to the county jail of Worcester aforesaid,
and there safely to be kept,
until they shall he from thence delivered by due course of law;
for which this shall be your sufficient warrant in that behalf.
Dated the 17th day of December, in the 25th year of His Majesty`'s reign over England,
etc.`"

[.signed-section-signature]
Henry Parker.

Being thus made prisoners,
without any probable appearance of being released before the quarter sessions at soonest,
we got some Friends to acompany my wife and her daughter into the North,
and we were conveyed to Worcester jail.
From whence, by that time I thought my wife could be got home,
I wrote her the following letter:--

[.salutation]
"`Dear Heart,

"`Thou seemedst to be a little grieved when I was speaking of prisons,
and when I was taken; be content with the will of the Lord God.
For when I was at John Rous`'s at Kingston, I had a sight of my being taken prisoner,
and when I was at Bray Doily`'s in Oxfordshire, as I sat at supper, I saw I was taken;
and I saw I had a suffering to undergo.
But the Lord`'s power is over all; blessed be his holy name for ever!`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
"`When we had been some time in the jail,
we thought fit to lay our case before the Lord Windsor,
who was lord-lieutenant of Worcestershire,
and before the deputy-lieutenants and other magistrates:
which we did by the following letter:--

"`These are to inform you, the lord-lieutenant (so called), and the deputy-lieutenants,
and the justices of the county of Worcestershire,
how unchristianly and inhumanly we have been dealt withal by Henry Parker,
a justice (so called), in our journey towards the North.
We coming to our Friend, John Halford`'s house, on the 17th of the 10th month, 1673,
and some Friends bringing us on the way, and others coming to visit us there,
towards night there came the aforesaid justice, and a priest, called Rowland Hains,
of Hunniton, in Warwickshire, and demanded our names and places of abode.
And though we were not in any meeting, but were discoursing together when they came in,
yet he made a mittimus to send us to Worcester jail.
Now, whereas he says in his mittimus,
'`that complaint had been made to him of several by-past
meetings of many hundreds at a time,`' we know nothing of that,
nor do we think that concerns us.
And whereas he says further, '`that no satisfactory account of our settlement,
or place of habitation appeared unto him.`'
This he contradicts in his own mittimus,
mentioning therein the places of our abode and habitation,
the account of which we satisfactorily and fully gave him.
And one of us (Thomas Lower) told him,
that he was going down with his mother-in-law (who is George Fox`'s wife),
and with his sister,
to fetch up his own wife and child out of the North into his own country.
And the other of us (George Fox) told him,
that he was bringing forward his wife on her journey
towards the North (who had been at London,
to visit one of her daughters that had lately lain in).
And having received a message from his mother,
an ancient woman in Leicestershire,
that she earnestly desired to see him before she died, he intended,
as soon as he had brought his wife on her journey as far as Causal, in Warwickshire,
to turn into Leicestershire, to visit his mother and relations there,
and then to return to London again.
But by his interrupting us on our journey, taking the husband from his wife,
and the son from his mother and sister,
and stopping him from visiting his wife and child so remote,
we were forced to get strangers, or whom we could, to help them on their journey,
to our great damage and their hinderance.
We asked the priest, '`whether this was his gospel,
and their way of entertaining strangers?`'
And we desired the justice to consider, '`whether this was doing as he would be done by?`'
But he said, '`he had said it, and he would do it.`'
And whereas he says,
'`we refused to give sureties;`' he asked only George Fox for sureties; who replied,
'`he was an innocent man,
and knew no law he had broken;`' but he did not ask Thomas Lower for any,
as if it had been crime and cause enough for his commitment,
that he came out of Cornwall.
If we were at a meeting, as he says in his mittimus,
he might have proceeded otherwise than by sending us to jail,
to answer the breach of the common laws; though he showed us no breach of any;
as may be seen in the mittimus.
We thought fit to lay before you the substance of his proceedings against us,
hoping there will more moderation and justice appear in you towards us,
that we may prosecute our intended journey.`"

[.signed-section-signature]
George Fox.

[.signed-section-signature]
Thomas Lower.

But no enlargement did we receive by our application to the Lord Windsor (so
called). And although Thomas Lower received several letters from his brother,
Dr. Lower, who was one of the king`'s physicians, concerning his liberty, and one,
by his procurement, from Henry Savile, who was of the king`'s bed-chamber, to his brother,
called the Lord Windsor, to the same effect;
yet seeing it related only to his enlargement, not mine,
so great was his love and regard to me that he would not seek his own liberty singly,
but kept the letter by him unsent.
So we were continued prisoners till the next general quarter sessions;
at which time divers Friends from several places being in town,
spoke to the justices concerning us, who answered fair, and said we should be discharged.
For many of the justices seemed to dislike the
severity of Parker`'s proceedings against us,
and declared an averseness to ensnare us by the tender of the oaths.
Some Friends also had spoken with Lord Windsor, who likewise answered them fair,
so that it was the general discourse that we should be discharged.
We heard also that Dr. Lower had procured a letter from Colonel Sands at London,
to some of the justices in favour of us.
Some of the justices also spoke to some Friends to acquaint us,
that they would have us speak but little in the court,
lest we should provoke any of the bench; and they would warrant we should be discharged.

We were not called till the last day of the sessions,
which was the 21st of the 11th month, 1673.
When we came in, they were stricken with paleness in their faces,
and it was some time before anything was spoken;
insomuch that a butcher in the hall said, "`What, are they afraid?
Dare not the justices speak to them?`"
At length, before they spoke to us, Justice Parker made a long speech on the bench,
much to the same effect as was contained in the mittimus;
often mentioning the common laws, but not instancing any that we had broken; adding,
"`that he thought it a milder course to send us two to jail,
than to put his neighbours to the loss of two hundred pounds,
which they must have suffered, had he put the law in execution against conventicles.`"
But in this he was either very ignorant or very deceitful,
for there being no meeting when he came, nor any to inform,
he had no evidence to convict us, or his neighbours by.

When Parker had ended his speech the justices spoke to us, and began with Thomas Lower,
whom they examined as to the cause of his coming into that country;
of which he gave them a full and plain account.
Sometimes I put in a word while they were examining him, and then they told me,
"`they were upon his examination, but that when it came to my turn,
I should have free liberty to speak, for they would not hinder me;
but I should have full time, and they would not ensnare us.`"
When they had done with him, they asked me an account of my travel, which I gave them,
as is mentioned before, but more largely.
And whereas Justice Parker, to aggravate the case,
had made a great noise of "`there being some from London, some from the North,
some from Cornwall, and some from Bristol, at the house when I was taken;`" I told them,
that "`this was in a manner all but one family, for there was none from London,
but myself; none from the North, but my wife and her daughter; none from Cornwall,
but my son-in-law, Thomas Lower; nor any from Bristol but one Friend, a merchant there;
who met us, as it were, providentially,
to assist my wife and her daughter in their journey homewards,
when by our imprisonment they were deprived of our company and help.`"
When I had spoken, the chairman, whose name was Simpson, an old Presbyterian, said,
"`Your relation or account, is very innocent.`"
Then he and Parker whispered a while together,
and after that the chairman stood up and said, "`You, Mr. Fox, are a famous man,
and all this may be true which you have said; but, that we may be the better satisfied,
will you take the oaths of allegiance and supremacy?`"
I told them, "`they had said they would not ensnare us; but this was a plain snare;
for they knew we could not take any oath.`"
However, they caused the oath to be read; and when they had done, I told them,
"`I never took an oath in my life, but I had always been true to the government;
that I was cast into the dungeon at Derby, and kept a prisoner six months there,
because I would not take up arms against King Charles at Worcester fight;
and for going to meetings was carried up out of Leicestershire,
and brought before Oliver Cromwell, as a plotter to bring in King Charles.
And ye know,`" said I, "`in your own consciences, that we, the people called Quakers,
cannot take an oath, or swear in any case, because Christ hath forbidden it.
But as to the matter or substance contained in the oaths, this I can and do say,
that I do own and acknowledge the king of England to be
the lawful heir and successor to the realm of England;
and do abhor all plots and plotters, and contrivances against him;
and I have nothing in my heart but love and good-will to him and all men,
and desire his and their prosperity; the Lord knows it, before whom I stand,
an innocent man.
And as to the oath of supremacy, I deny the Pope, and his power, and his religion,
and abhor it with my heart.`"
While I was speaking, they cried, "`give him the book;`" and I said, "`the book saith,
'`Swear not at all.`'`" Then they cried, "`take him away,
jailer;`" and I still speaking on, they were urgent upon the jailer, crying,
"`take him away, we shall have a meeting here; why do you not take him away?
that fellow (meaning the jailer) loves to hear him preach.`"
Then the jailer drew me away, and as I was turning from them, I stretched out my arm,
and said, "`the Lord forgive you,
who cast me into prison for obeying the doctrine of Christ.`"
Thus they apparently broke their promise in the face of the country;
for they promised I should have free liberty to speak, but now they would not give it me;
and they promised they would not ensnare us,
yet now they tendered me the oaths on purpose to ensnare me.

After I was had away Thomas Lower was stayed behind in the court, and they told him,
"`he was at liberty.`"
Then he would have reasoned with them, asking them,
"`why I might not be set at liberty as well as he, seeing we were both taken together,
and our case was alike?`"
But they told him, "`they would not hear him,`" saying,
"`you may be gone about your business, for we have nothing more to say to you,
seeing you are discharged.`"
And this was all he could get from them.
Wherefore after the court was risen, he went to speak with them at their chamber,
desiring to know, "`what cause they had to detain his father,
seeing they had discharged him;`" and wishing
them to consider whether this was not partiality,
and would be a blemish to them.
Whereupon Simpson threatened him, saying, "`if you be not content,
we will tender you the oaths also, and send you to your father.`"
To which he replied, "`they might do that, if they thought fit;
but whether they sent him or not, he intended to go,
and to wait upon his father in prison, for that was now his business in that country.`"
Then said Justice Parker to him, "`Do you think, Mr. Lower,
that I had not cause to send your father and you to prison,
when you had so great a meeting, that the parson of the parish complained to me,
that he has lost the greatest part of his parishioners; so that when he comes among them,
he has scarcely any auditors left?`"
"`I have heard,`" replied Thomas Lower,
"`that the priest of that parish comes so seldom to visit his flock (but once, it may be,
or twice in a year, to gather up his tithes),
that it was but charity in my father to visit so forlorn and forsaken a flock;
and therefore thou hadst no cause to send my father to prison for visiting them,
or for teaching, instructing, and directing them to Christ, their true teacher,
who had so little comfort or benefit from their pretended pastor,
who comes amongst them only to seek for his '`gain from
his quarter.`'`" Upon this the justice fell a laughing,
for it seems Dr. Crowder (who was the priest they spoke of) was then in the room,
sitting among them, though Thomas Lower did not know him;
and he had the wit to hold his tongue,
and not undertake to vindicate himself in a matter so notoriously known to be true.
But when Thomas Lower was come from them, the justices did so play upon Dr. Crowder,
that he was pitifully ashamed,
and so nettled with it that he threatened to sue Thomas Lower in the bishop`'s court,
upon an action of defamation.
Which when Thomas Lower heard, he sent him word, that he would answer his suit,
let him begin it when he would; and would bring his whole parish in evidence against him.
This cooled the doctor.
Yet some time after, he came to the prison,
pretending that he had a mind to dispute with me,
and to talk with Thomas Lower about that business; and he brought another with him,
he himself being then a prebendary at Worcester.

When he came in, he asked me, "`What I was in prison for?`"
"`Dost thou not know that?`"
said I. "`Wast not thou upon the bench when Justice
Simpson and Parker tendered the oath to me?
And hadst not thou a hand in it?`"
Then he said, "`It is lawful to swear;
and Christ did not forbid swearing before a magistrate; but swearing by the sun,
and the like.`"
I bid him prove that by the Scriptures, but he could not.
Then he brought that saying of Paul`'s,
"`All things are lawful unto me,`" 1 Cor. 6:12. "`And if,`" said he,
"`all things were lawful unto him, then swearing was lawful unto him.`"
"`By this argument,`" said I, "`thou mayest also affirm, that drunkenness, adultery,
and all manner of sin and wickedness is lawful also, as well as swearing.`"
"`Why,`" said Dr. Crowder, "`do you hold that adultery is unlawful?`"
"`Yes,`" said I, "`that I do.`"
"`Why then,`" said he, "`this contradicts the saying of St. Paul.`"
Thereupon I called to the prisoners and the jailer,
to hear what doctrine Dr. Crowder had laid down as orthodox, viz., "`that drunkenness,
swearing, adultery, and such like things, were lawful.`"
Then he said, "`he would give it under his hand;`" and took a pen,
but wrote another thing than that which he had spoken.
Then, turning to Thomas Lower, he asked him,
"`whether he would answer what he had there written?`"
who undertook it.
Whereupon, when he had threatened Thomas Lower to sue him in the bishop`'s court,
for speaking so abusively (as he called it) of him before the justices,
and Thomas had bid him begin when he pleased, for he would answer him,
and bring his parishioners in evidence against him, he went away in a great fret,
grumbling to himself as he went.
A few days after Thomas Lower sent him an answer
to the paper he had written and left with him;
which answer a Friend of Worcester carried to him; and he read it and said,
"`he would reply to it;`" but never did, though he often sent him word he would do it.

Soon after the sessions, the term coming on,
an _habeas corpus_ was sent down to Worcester for the
sheriff to bring me up to the King`'s Bench bar.
Whereupon, the under-sheriff, having made Thomas Lower his deputy to convey me to London,
we set out the 29th of the 11th Month, 1673, and came to London the 2nd of the 12th;
the ways being very deep, and the waters out.
Next day, notice being given that I was brought up,
the sheriff was ordered to bring me into court.
I went accordingly, and appeared before Judge Wild;
and both he and the lawyers were pretty fair, so that I had time to speak,
to clear my innocency, and show my wrong imprisonment.
After the return of the writ was entered,
I was ordered to be brought into court again next day,
the order of court being as follows:--

[.small-break]
'''

[.signed-section-context-open]
Worcester. The King against George Fox.

[.signed-section-context-open]
Thursday, next after the morrow of the Purification of the Blessed Virgin Mary,
in the 26th Year of King Charles the Second.

The defendant being brought here into court, upon a writ of _habeas corpus_ ad subjiciend,
etc, under the custody of the sheriff of the county aforesaid; it is ordered,
That the Return unto the _habeas corpus_ be filed,
and the defendant is committed unto the marshal of this court, to be safely kept until,
etc.

[.signed-section-signature]
"`By motion of Mr. G. Stroude. By the Court.`"

In the morning, I walked in the hall,
till the sheriff came to me (for he trusted me to go whither I would),
and it being early, we went into the court of the King`'s Bench,
and sat there among the lawyers almost an hour, till the judges came in.
When they came in, the sheriff took off my hat; and after a while I was called.
The Lord`'s presence was with me, and his power I felt was over all.
I stood and heard the king`'s attorney, whose name was Jones,
who indeed spoke notably on my behalf, as did also another counsellor after him;
and the judges, who were three, were all very moderate,
not casting any reflecting words at me.
I stood still in the power and Spirit of the Lord, seeing how he was at work.
When they had done, I applied to the chief justice to speak; and he said, I might.
Then I related the cause of our journey, the manner of our being taken and committed,
and the time of our imprisonment until the sessions;
with a brief account of our trial there, and what I had offered to the justices then,
as a declaration, that I could make or sign,
instead of the oaths of allegiance and supremacy.
When I had done, the chief justice said, "`I was to be turned over to the King`'s Bench,
and the sheriff of Worcester to be discharged of me.`"
He said also "`they would consider further of it;
and if they found any error in the record, or in the justice`'s proceedings,
I should be set at liberty.`"
So a tipstaff was called to take me into custody,
and he delivered me to the keeper of the King`'s Bench, who let me go to a Friend`'s house,
where I lodged, and appointed to meet me at Edward Man`'s in Bishopsgate-Street, next day.
But after this, Justice Parker, or some other of my adversaries,
moved the court that I might be sent back to Worcester.
Whereupon another day was appointed for another hearing,
and they had four counsellors that pleaded against me.
George Stroude, a counsellor, pleaded for me,
and was pleading before I was brought into court; but they bore him down,
and prevailed with the judges to give judgment,
that "`I should be sent down to Worcester sessions.`"
Only they told me, I might put in bail to appear at the sessions,
and to be of good behaviour in the meantime.
I told them, "`I never was of ill behaviour in my life; and that they, the four judges,
might as well put the oath to me there,
as send me to Worcester to be ensnared by the justices, in their putting the oath to me,
and then premuniring me, who never took oath in my life.`"
But I told them, "`if I broke my Yea and Nay,
I was content to suffer the same penalty that they should who break their oaths.`"
This alteration of the judges`' minds in my case, proceeded, as was thought,
from some false informations, that my adversary, Justice Parker, had given against me;
for between the times of my former appearance and this,
he had spread abroad a very false and malicious story, viz.,
"`that there were many substantial men with me, out of several parts of the nation,
when he jtook me; and that we had a design or plot in hand;
and that Thomas Lower stayed with me in prison, long after he was set at liberty,
to carry on our design.`"
This was spoken in the parliament house, insomuch,
that if I had not been brought up to London when I was,
I should have been stopped at Worcester, and Thomas would have been recommitted with me.
But although these lies were easily disproved, and laid open to Parker`'s shame,
yet would not the judges alter their last sentence, but remanded me to Worcester jail;
only this favour was granted, that I might go down my own way, and at my own leisure;
provided I would be without fail there by the assize,
which was to begin on the 2nd of the 2nd month following.
I stayed in and about London till toward the latter end of the 1st Month, 1674,
and then went down leisurely (for I was not able to bear hasty and hard travelling),
and came into Worcester on the last day of the 1st Month, 1674,
being the day before the judges came to town.
On the 2nd of the 2nd Month, I was brought from the jail to an inn near the hall,
that I might be in readiness if I should be called.
But not being called that day, the jailer came to me at night, and told me,
"`I might go home`" (meaning to the jail). Whereupon
Gerrard Roberts of London being with me,
he and I walked down together to the jail without any keeper.

Next day being brought up again, they set a little boy of about eleven years old,
to be my keeper.
I came to understand that Justice Parker and the clerk of the peace had given order,
that I should not be put into the calendar,
that so I might not be brought before the judge;
wherefore I got the judge`'s son to move in court,
that "`I might be called;`" and thereupon I was called,
and brought up to the bar before Judge Turner, my old adversary,
who had tendered me the oaths and premunired me once before at Lancaster.
After silence made, he asked me, "`what I desired?`"
I answered, "`My liberty, according to justice.`"
He said, "`I lay upon the oath;`" and asked, "`if I would take it.`"
I desired he would hear the manner of my being taken and committed, and he being silent,
I gave him an account thereof at large, as is before set down, letting him also know,
that "`since my imprisonment I had understood that my mother, who was an ancient,
tender woman, and had desired to see me before she died,
hearing that I was stopped and imprisoned in my journey,
so that I was not likely to come to see her, was so struck by it,
that she died soon after: which was a very hard thing to me.`"
When I had done speaking,
he again asked me "`to take the oaths;`" I told him I
could not take any oath for conscience`' sake,
and that I believed he and they all knew in their consciences,
that it was for conscience`' sake I could not swear at all.
I declared amongst them what I could say, and what I could sign,
in owning the king`'s right to the government,
and in denying the Pope and his pretended powers, and all plotters, plots,
and conspiracies against the government.
Some thought the judge had a mind to set me at liberty,
for he saw they had nothing justly against me; but Parker, who committed me,
endeavoured to incense him against me, telling him, "`that I was a ringleader;
that many of the nation followed me,
and he knew not what it might come to;`" with many more envious words,
which some that stood near took notice of;
who also observed that the judge gave him no answer to it.
However, the judge, willing to ease himself,
referred me and my case to the sessions again,
bidding the justices make an end of it there,
and not trouble the assizes any more with me.
So I was continued prisoner chiefly (as it seemed) through the means of Justice Parker,
who, in this case, was as false as envious; for he had promised Richard Cannon,
of London, who had acquaintance with him,
that he would endeavour to have me set at liberty;
yet he was the worst enemy I had in court, as some of the court observed and reported.
Other justices were very loving, and promised that I should have the liberty of the town,
and to lodge at a Friend`'s house till the sessions; which accordingly I had,
and the people were very civil and respectful to me.

Between this time and the sessions, I had some service for the Lord,
with several people that came to visit me.
At one time three nonconformist priests and two lawyers came to discourse with me;
and one of the priests undertook to prove,
"`that the Scriptures are the only rule of life.`"
Whereupon, after I had plunged him about his proof,
I had a fit opportunity to open unto them "`the right and proper use, service,
and excellency of the Scriptures; and also to show, that the Spirit of God,
which was given to every one to profit withal--the grace of God,
which bringeth salvation, and which hath appeared unto all men,
and teacheth them that obey it to deny ungodliness and worldly lusts,
and to live soberly, righteously, and godly in this present world; that this, I say,
is the most fit, proper, and universal rule, which God hath given to all mankind to rule,
direct, govern, and order their lives by.`"

Another time came a Common-Prayer priest, and some people with him.
He asked me, "`if I was grown up to perfection?`"
I told him, "`what I was, I was by the grace of God.`"
He replied, "`it was a modest and civil answer.`"
Then he urged the words of John, "`If we say that we have no sin, we deceive ourselves,
and the truth is not in us.`"
And he asked, "`what did I say to that?`"
I said, with the same apostle, "`If we say that we have not sinned, we make Him a liar,
and His word is not in us;`" who came to destroy sin, and to take away sin.
So there is a time for people to see that they have sinned,
and there is a time for them to see that they have sin;
and there is a time for them to confess their sin, and to forsake it,
and to know "`the blood of Christ to cleanse from all sin.`"
Then the priest was asked, "`whether Adam was not perfect before he fell?
and whether all God`'s works were not perfect?`"
The priest said, "`there might be a perfection, as Adam had, and a falling from it.`"
But I told him, "`there is a perfection in Christ, above Adam, and beyond falling;
and that it was the work of the ministers of Christ,
to present every man perfect in Christ;
and for the perfecting of whom they had their gifts from Christ; therefore,
they that denied perfection, denied the work of the ministry,
and the gifts which Christ gave for the perfecting of the saints.`"
The priest said, "`we must always be striving.`"
But I told him, "`it was a sad and comfortless sort of striving,
to strive with a belief that we should never overcome.`"
I told him also, "`that Paul, who cried out of the body of death, did also '`thank God,
who gave him the victory, through our Lord Jesus Christ.`'
So there was a time of crying out for want of victory,
and a time of praising God for the victory.
And Paul said,
'`there is no condemnation to them that are in Christ Jesus.`'`"
The priest said, "`Job was not perfect.`"
I told him, "`God said, Job was a perfect man, and that he did shun evil:
and the Devil was forced to confess that '`God had set a
hedge about him,`' which was not an outward hedge,
but the invisible heavenly power.`"
The priest said, "`Job said, '`He chargeth his angels with folly,
and the heavens are not clean in his sight.`'`" I told him, "`that was his mistake;
for it was not Job who said so, but Eliphaz, who contended against Job.`"
"`Well but,`" said the priest, "`what say you to that Scripture,
'`The justest man that is sinneth seven times a day.`'`" "`Why truly,`" said I, "`I say,
there is no such Scripture;`" and with that the priest`'s mouth was stopped.
Many other services I had with several sorts of
people between the assizes and the sessions.

The next quarter sessions began the 29th of the 2nd month,
and I was called before the justices.
The chairman`'s name was Street, who was a judge in the Welsh circuit;
and he misrepresented me and my case to the country, telling them,
"`that we had a meeting at Tredington, from all parts of the nation,
to the terrifying of the king`'s subjects, for which we had been committed to prison:
that for the trial of my fidelity the oaths were put to me;
and having had time to consider of it, he asked me,
'`if I would now take the oaths?`'`" I desired liberty to speak for myself;
and having obtained that,
began first to clear myself from those falsehoods he had charged on me and Friends,
declaring "`that we had not any such meeting from all parts of the nation,
as he had represented it; but that (except the Friend from whose house we came,
and who came with us to guide us thither, and one Friend of Bristol,
who came accidentally, or rather providentially,
to assist my wife homewards after we were taken) they
that were with me were part of my own family,
being my wife, her daughter, and her son-in-law.
And we did not meet in any way that would occasion terror to any of the king`'s subjects,
for we met peaceably and quietly, without arms;
and I did not believe there could any one be produced,
that could truly say he was terrified with our meeting.
Besides, I told them, we were but in our journey,
the occasion whereof I now related as before.
Then as to the oaths,
I showed why I could not take them (seeing Christ hath forbidden all swearing),
and what I could say or sign in lieu of them, as I had done before.`"
Yet they caused the oaths to be read to me again, and afterwards read an indictment also,
which they had drawn up in readiness, having a jury ready also.
When the indictment was read, the judge asked me, "`if I was guilty?`"
I said, "`Nay, for it was a great bundle of lies,
which I showed and proved to the judge in several particulars, which I instanced;
asking him, if he did not know in his conscience that they were lies?`"
He said, "`it was their form.`"
I said, "`it was not a true form.`"
He asked me again, "`whether I was guilty?`"
I told him "`nay, I was not guilty of the matter, nor of the form;
for I was against the Pope and Popery,
and did acknowledge and should set my hand to that.`"
Then the judge told the jury what they should say, and what they should do,
and what they should write on the backside of the indictment; and as he said, they did.
But before they gave in their verdict, I told them, "`that it was for Christ`'s sake,
and in obedience to his and the apostle`'s command, that I could not swear; and therefore,
said I, take heed what ye do, for before his judgment seat ye shall all be brought.`"
The judge said, "`this is canting.`"
I said, "`If to confess our Lord and Saviour, and to obey his command,
be called '`canting`' by a judge of a court,
it is to little purpose for me to say more among you:
yet ye shall see that I am a Christian, and shall show forth Christianity,
and my innocency shall be manifest.`"
So the jailer led me out of the court; and the people were generally tender,
as if they had been in a meeting.
Soon after I was brought in again, and the jury found the bill against me,
which I traversed; and then I was asked to put in bail till the next sessions,
and the jailer`'s son offered to be bound for me.
But I stopped him, and warned Friends not to meddle; for I told them,
"`there was a snare in that:`" yet I told the justices, that I could promise to appear,
if the Lord gave health and strength, and I were at liberty.
Some of the justices were loving, and would have hindered the rest from indicting me,
or putting the oath to me; but Justice Street, who was the chairman, said,
"`he must go according to law.`"
So I was sent to prison again; yet within two hours after,
through the moderation of some of the justices,
I had liberty given me to go at large till next quarter-sessions.
These moderate justices, it was said,
desired Justice Parker to write to the king for my liberty, or for a Noli prosequi,
because they were satisfied I was not such a dangerous person as I had been represented.
This, it was said, he promised them to do; but he did it not.

After I had got a copy of the indictment, I went to London, visiting Friends as I went.
When I came there,
some that were earnest to get me out of the hands of those envious justices,
that sought to premunire me at Worcester, would needs be tampering again,
to bring me before the judges of the King`'s Bench;
whereupon I was brought again by a _habeas corpus_ before them.
I tendered them a paper,
in which was contained what I could say instead of the oaths of allegiance and supremacy,
as follows:--

[.small-break]
'''

"`This I do in the truth, and in the presence of God declare,
that King Charles the Second is lawful king of this realm,
and of all other his dominions; that he was brought in,
and set up king over this realm by the power of God:
and I have nothing but love and good will to him and all his subjects,
and desire his prosperity and eternal good.
I do utterly abhor and deny the Pope`'s power and supremacy,
and all his superstitions and idolatrous inventions; and do affirm,
that he hath no power to absolve sin.
I do abhor and detest his murdering of princes or other people, by plots or contrivances.
And likewise I do deny all plots and contrivances,
and plotters and contrivers against the king and his subjects;
knowing them to be the works of darkness, the fruits of an evil spirit,
against the peace of the kingdom, and not from the Spirit of God,
the fruit of which is love.
I dare not take an oath, because it is forbidden by Christ and the apostle;
but if I break my Yea or Nay,
let me suffer the same penalty as they that break their oaths.`"

[.signed-section-signature]
George Fox.

But the business being so far proceeded in at Worcester, they would not meddle in it,
but left me to appear again before the justices,
at the next general quarter-sessions at Worcester.

Meanwhile the Yearly Meeting of Friends came on,
at which (through the liberty granted me till the sessions) I was present,
and exceedingly glorious the meetings were beyond expression; blessed be the Lord.

After the Yearly Meeting I set forward for Worcester, the sessions drawing on,
which were held in the 5th month.
When I was called to the bar, and the indictment read,
some scruple arising among the jury concerning it, the judge of the court,
Justice Street, caused the oaths to be read and tendered to me again.
I told him, "`I came now to try the traverse of my indictment,
and that his tendering me the oaths anew, was a new snare.`"
I desired him to answer me a question or two; and asked him,
"`whether the oaths were to be tendered to the king`'s subjects,
or to the subjects of foreign princes?`"
He said, "`to the subjects of this realm.`"
"`Then,`" said I, "`you have not named me a subject in the indictment,
and therefore have not brought me within the statute.`"
The judge cried, "`read the oath to him:`" I said, "`I require justice.`"
Again I asked him,
"`Whether the sessions ought not to have been
held for the king and the body of the county?`"
He said, "`Yes.`"
"`Then,`" said I, "`you have there left the king out of the indictment;
how then can you proceed upon this indictment to a trial between the king and me,
seeing the king is left out?`"
He said, "`the king was in before.`"
But I told him, "`the king`'s name being left out,
here was a great error in the indictment, and sufficient, as I was informed, to quash it.
Besides,`" I told him, "`that I was committed by the name of George Fox, of London;
but now I was indicted by the name of George Fox, of Tredington,
in the county of Worcester: and I wished the jury to consider,
how they could find me guilty upon that indictment,
seeing I was not of the place the indictment mentioned?`"
The judge did not deny that there were errors in the indictment; but said,
"`I might take my remedy in the proper place.`"
I answered, "`ye know we are a people that suffer all things, and bear all things;
and therefore ye thus use us, because we cannot revenge ourselves;
but we leave our cause to the Lord.`"
The judge said, "`the oath has been tendered to you several times,
and we will have some satisfaction from you concerning the oath.`"
I offered them the same declaration instead of the oath,
which I had offered to the judges above; but it would not be accepted.
Then I desired to know, seeing they put the oath anew to me,
whether the indictment was quashed or not?
Instead of answering me, the judge told the jury, "`they might go out.`"
Some of the jury were not satisfied; whereupon the judge told them,
"`they had heard a man swear that the oath was tendered to me
the last sessions:`" and then he told them what they should do.
I told him, "`he should leave the jury to their own consciences.`"
However, the jury, being put on by him, went forth, and soon came in again,
and found me guilty.
I asked the jury "`how they could satisfy themselves to
find me guilty upon that indictment,
which was laid so false, and had so many errors in it?`"
They could make but little answer; yet one, who seemed to be the worst of them,
would have taken me by the hand; but I put him by, saying, "`How now Judas,
hast thou betrayed me, and dost thou now come with a kiss?`"
So I bid him and them repent.
Then the judge began to tell me, "`how favourable the court had been to me.`"
I asked him, "`how he could say so?
Was ever any man worse dealt by than I had been in this case,
who was stopped in my journey, when travelling upon my lawful occasions,
and imprisoned without cause; and now had the oaths put to me only for a snare?`"
And I desired him to "`answer me in the presence of the Lord,
in whose presence we all were, whether this oath was not tendered me in envy?`"
He would not answer that, but said,
"`Would you had never come here to trouble us and the country.`"
I told him, "`I came not thither of myself, but was brought, being stopped in my journey.
I did not trouble them, but they had brought trouble upon themselves.`"
Then the judge told me, "`what a sad sentence he had to tell me.`"
I asked him, "`Whether what he was going to speak was by way of passing sentence,
or of information?
For,`" I told him, "`I had many things to say,
and more errors to assign in the indictment, besides those I had already mentioned,
to stop him from giving sentence against me upon that indictment.`"
He said, "`He was going to show me the danger of a premunire,
which was the loss of my liberty, and of all my goods and chattels,
and to endure imprisonment during life.`"
But he said, "`he did not deliver this as the sentence of the court upon me,
but as an admonition to me.`"
Then he bid the jailer take me away.
I expected to be called again to hear the sentence; but when I was gone,
the clerk of the peace (whose name was Twittey) asked him, as I was informed,
"`whether that which he had spoken to me should stand for sentence?`"
And he, consulting with some of the justices, told him, "`Yes, that was the sentence,
and should stand.`"
This was done behind my back, to save himself from shame in the face of the country.
Many of the justices, and the generality of the people, were moderate and civil;
and John Ashley, a lawyer, was very friendly, both the time before and now,
speaking on my behalf, and pleading the errors of the indictment for me;
but Justice Street, who was the judge of the court, would not regard, but overruled all.
This Justice Street said to some Friends in the morning before my trial,
"`that if he had been upon the bench the first sessions,
he would not have tendered me the oath;
but if I had been convicted of being at a conventicle,
he would have proceeded against me according to that law;
and that he was sorry that ever I came before him;`" and yet
he maliciously tendered the oath to me in the court again,
when I was to have tried my traverse upon the indictment.
But the Lord pleaded my cause, and met with both him and Justice Simpson,
who first ensnared me with the oath at the first sessions;
for Simpson`'s son was arraigned not long after, at the same bar, for murder.
And Street, who, as he came down from London,
after the judges had returned me back from the King`'s Bench to Worcester, said,
"`Now I was returned to them, I should lie in prison and rot,`" had his daughter,
whom he so doted on that she was called his idol, brought dead from London in a hearse,
to the same inn where he spoke those words,
and brought to Worcester to be buried within a few days after.
People took notice of the hand of God, how sudden it was upon him;
but it rather hardened than tendered him, as his conduct afterwards showed.

After I was returned to prison, several came to see me; and amongst others,
the Earl of Salisbury`'s son, who was very loving,
and troubled that they had dealt so wickedly by me.
He stayed about two hours with me,
and took a copy of the errors in the indictment in writing.

The sessions being now over, and I fixed in prison by a premunire,
my wife came out of the North to be with me; and the assizes coming on, in the 6th month,
the state of my case being drawn up in writing,
she and Thomas Lower delivered it to Judge Wild.
In it were set forth the occasion of my journey;
the manner of my being taken and imprisoned;
the proceedings of the several sessions against me;
and the errors in the indictment by which I was premunired.
When the judge had read it, he shook his head, and said,
"`We might try the validity or invalidity of the errors,
if we would;`" and that was all they could get from him.

While I lay in prison, it came upon me to state our principle to the king;
not with particular relation to my own sufferings,
but for his better information concerning our principle, and us as a people.

[.salutation]
"`To the King.

"`The principle of the Quakers is the Spirit of Christ, who died for us,
and is risen for our justification; by which we know that we are his.
He dwelleth in us by his Spirit;
and by the Spirit of Christ we are led out of unrighteousness and ungodliness.
It brings us to deny all plottings and contrivings against the king, or any man.
The Spirit of Christ brings us to deny all manner of ungodliness, as lying, theft,
murder, adultery, fornication, and all uncleanness, debauchery, malice, hatred, deceit,
cozening, and cheating whatsoever, and the Devil and his works.
The Spirit of Christ brings us to seek the peace and good of all men,
and to live peaceably;
and leads us from such evil works and actions as the magistrates`' sword takes hold upon.
Our desire and labour are, that all, who profess themselves Christians,
may walk in the Spirit of Christ; that they, through the Spirit,
may mortify the deeds of the flesh,
and by the sword of the Spirit cut down sin and evil in themselves.
Then the judges and other magistrates would not have so
much work in punishing sin in the kingdom;
neither then need kings or princes fear any of their subjects;
if they all walked in the Spirit of Christ; for the fruits of the Spirit are love,
righteousness, goodness, temperance, etc.
If all, that profess themselves Christians,
walked in the Spirit of Christ and by it did mortify sin and evil,
it would be a great ease to the magistrates and rulers, and would free them,
from much trouble; for it would lead all '`to do unto others,
as they would have others to do unto them;`' and
so the royal law of liberty would be fulfilled.
For if all, that are called Christians, did walk in the Spirit of Christ,
by it to have the evil spirits and its fruits mortified and cut down in them; then,
not being led by the evil spirit, but by the good Spirit of Christ,
the fruits of the good Spirit would appear in all.
For as people are led by the good Spirit of Christ, it leads them out of sin and evil,
which the magistrates`' sword takes hold of, and so would be an ease to the magistrates.
But as people err from this good Spirit of Christ, and follow the evil spirit,
which leads them into sin and evil; that spirit brings the magistrate into much trouble,
to execute the law upon the sinners and transgressors of the good Spirit.
That Spirit which leads people from all manner of sin and evil,
is one with the magistrates`' power, and with the righteous law;
for the law being added because of transgression,
that Spirit that leads out of transgression,
must needs be one with that law that is against transgressors.
So that Spirit which leads out of transgression, is the good Spirit of Christ,
and is one with the magistrates in the higher power, and owns it and them;
but that spirit which leads into transgression, is the bad spirit, is against the law,
against the magistrates, and makes them much troublesome work.
Now the manifestation of the good Spirit is given to every man to profit withal;
and no man can profit in the things of God, but by the Spirit of God,
which brings to deny all sin and evil.
It is said of Israel, Neh.
ix., '`The Lord gave them his good Spirit to instruct them, yet they rebelled against it.`'
But if all people did mind this manifestation of the Spirit,
which God hath given to instruct them,
it would lead them to forsake all manner of sin and evil, enmity, hatred, malice,
and all manner of unrighteousness and ungodliness, and to mortify it.
And then in the Spirit of Christ they would have fellowship and unity,
which is the bond of peace; then would love and peace,
which are the fruits of the good Spirit, flow among all that are called Christians.

"`We are a people, who,
in tenderness of conscience to the command of Christ and his apostle, cannot swear;
for we are commanded in Matt. 5. and James 5. to keep to Yea and Nay,
and '`not to swear at all; neither by heaven,
nor by the earth, nor by any other oath, lest we go into evil,
and fall into condemnation.`'
The words of Christ are these,
'`Ye have heard that it hath been said by (or to) them of old time,
Thou shalt not forswear thyself, but shalt perform unto the Lord thine oaths.`'
These were true and solemn oaths, which they who made,
ought to have performed in old time;
but these Christ and his apostle forbid in the gospel times,
as well as false and vain oaths.
If we could take any oath at all, we could take the oath of allegiance,
as knowing that King Charles was by the power of God brought into England,
and set up king of England, etc., over the heads of our old persecutors;
and as for the Pope`'s supremacy, we do utterly deny it.
But Christ and the apostle having commanded us not to swear, but to keep to Yea and Nay,
we dare not break their commands; and therefore many have put the oaths to us,
as a snare, that they might make a prey of us.
Our denying to swear is not in wilfulness, stubbornness, or contempt,
but only in obedience to the command of Christ and his apostle; and we are content,
if we break our Yea and Nay,
to suffer the same penalty that they should who break their oaths.
We desire, therefore, that the king would take this into consideration,
and also how long we have suffered in this case.
This is from one who desires the eternal good and prosperity of the king,
and of all his subjects in the Lord Jesus Christ.`"

[.signed-section-signature]
G+++.+++ F.

About this time I had a fit of sickness, which brought me very low and weak in my body;
and I continued so a pretty while,
insomuch that some Friends began to doubt of my recovery.
I seemed to myself to be amongst the graves and dead corpses;
yet the invisible power did secretly support me,
and conveyed refreshing strength into me, even when I was so weak,
that I was almost speechless.
One night, as I was lying awake upon my bed in the glory of the Lord, which was over all,
it was said unto me, "`that the Lord had a great deal more work for me to do for him,
before he took me to himself.`"

Endeavours were used to get me released, at least for a time, till I was grown stronger;
but the way of effecting it proved difficult and tedious;
for the king was not willing to release me by any other way than a pardon,
being told he could not legally do it; and I was not willing to be released by a pardon,
which he would readily have given me,
because I did not look upon that way as agreeable with the innocency of my cause.
Edward Pitway, a Friend, having occasion to speak with Justice Parker,
upon some other business, desired him to give order to the jailer, that,
in regard of my weakness, I might have liberty to go out of the jail into the city.
Whereupon Justice Parker wrote the following letter to the jailer,
and sent it to the Friend to deliver.

[.salutation]
"`Mr. Harris,

"`I have been much importuned by some friends to George Fox to write to you.
I am informed by them, that he is in a very weak condition, and very much indisposed;
what lawful favour you can do for the benefit of the air for his health, pray show him.
I suppose, the next term they will make application to the king.

[.signed-section-closing]
"`I am, Sir, your loving friend,

[.signed-section-signature]
Henry Parker.

[.signed-section-context-close]
Evesham, the 8th of October, 1674.

After this, my wife went to London, and spoke to the king,
laying before him my long and unjust imprisonment, with the manner of my being taken,
and the justices`' proceedings against me, in tendering me the oath as a snare,
whereby they had premunired me; so that I being now his prisoner, it was in his power,
and at his pleasure, to release me, which she desired.
The king spoke kindly to her, and referred her to the lord-keeper; to whom she went,
but could not obtain what she desired; for he said,
"`the king could not release me otherwise than by a
pardon;`" and I was not free to receive a pardon,
knowing I had not done evil.
If I would have been freed by a pardon, I need not have lain so long,
for the king was willing to give me pardon long before, and told Thomas Moore,
"`that I need not scruple being released by a pardon, for many a man,
that was as innocent as a child,
had had a pardon granted him;`" yet I could not consent to have one.
For I had rather have lain in prison all my days,
than have come out in any way dishonourable to truth;
wherefore I chose to have the validity of my indictment tried before the judges.
And thereupon,
having first had the opinion of a counsellor upon it (Thomas Corbet of London,
whom Richard Davies of Welchpool was well acquainted with, and recommended to me),
an _habeas corpus_ was sent down to Worcester to
bring me up once more to the King`'s Bench bar,
for the trial of the errors in my indictment.
The under-sheriff set forward with me the 4th of the 12th Month,
there being with us in the coach the clerk of the peace and some others.
The clerk had been my enemy all along, and now sought to ensnare me in discourse;
but I saw, and shunned him.
He asked me, "`what I would do with the errors in the indictment?`"
I told him, "`they should be tried, and every action should crown itself.`"
He quarrelled with me for calling their ministers priests.
I asked him, "`if the law did not call them so?`"
Then he asked me, "`what I thought of the church of England?
were there no Christians among them?`"
I said, "`they are called so, and there are many tender people amongst them.`"
We came to London on the 8th,
and on the 11th I was brought before the four judges at the King`'s Bench,
where Counsellor Corbet pleaded my cause.
He started a new plea; for he told the judges,
"`that they could not imprison any man upon a premunire.`"
Whereupon Chief Justice Hale said, "`Mr. Corbet, you should have come sooner,
at the beginning of the term, with this plea.`"
He answered, "`we could not get a copy of the return and the indictment.`"
The judge replied, "`you should have told us,
and we would have forced them to make a return sooner.`"
Then said Judge Wild, "`Mr. Corbet, you go upon general terms; and if it be as you say,
we have committed many errors at the Old Bailey, and in other courts.`"
Corbet was positive that by law they could not imprison upon a premunire.
The judge said, "`there is summons in the statute.`"
"`Yes,`" said Corbet, "`but summons is not imprisonment;
for summons is in order to a trial.`"
"`Well,`" said the judge,
"`we must have time to look in our books and consult the statutes.`"
So the hearing was put off till the next day.

The next day they chose rather to let this plea fall,
and begin with the errors of the indictment; and when they came to be opened,
they were so many and gross,
that the judges were all of opinion that "`the indictment was quashed and void,
and that I ought to have my liberty.`"
There were that day several great men, lords and others,
who had the oaths of allegiance and supremacy tendered to them in open court,
just before my trial came on; and some of my adversaries moved the judges,
that the oaths might be tendered again to me, telling them,
"`I was a dangerous man to be at liberty.`"
But Judge Hale said, "`He had indeed heard some such reports,
but he had also heard many more good reports of me;`" and so he and
the rest of the judges ordered me to be freed by proclamation.
Thus after I had suffered imprisonment a year and almost two months for nothing,
I was fairly set at liberty upon a trial of the errors in my indictment,
without receiving any pardon, or coming under any obligation or engagement at all;
and the Lord`'s everlasting power went over all, to his glory and praise.
Counsellor Corbet, who pleaded for me, obtained great fame by it,
for many of the lawyers came to him,
and told him he had brought that to light which had not been known before,
as to the not imprisoning upon a premunire; and after the trial a judge said to him,
"`You have attained a great deal of honour by pleading George Fox`'s cause so in court.`"

During the time of my imprisonment in Worcester,
notwithstanding my illness and want of health,
and my being so often hurried to and fro to London and back again,
I wrote several books for the press; one of which was called, _A Warning to England._
Another was, _To the Jews, proving, by the Prophets, that the Messiah is come._
Another, _Concerning Inspiration, Revelation, and Prophecy._
Another, _Against all Vain Disputes._
Another, _For all Bishops and Ministers to try themselves by the Scriptures._
Another, _To such as say, "`We love none but ourselves.`"_
Another entitled, _Our Testimony concerning Christ._
And another little book, _Concerning Swearing;_
being the first of those two that were given to the parliament.
Besides these,
I wrote many papers and epistles to Friends to
encourage and strengthen them in their services for God,
which some, who had made profession of truth, but had given way to a seducing spirit,
and were departed from the unity and fellowship of the gospel, in which Friends stand,
endeavoured to discourage them from,
especially in their diligent and watchful care for the well-ordering
and managing of the affairs of the church of Christ.
