== Chapter VII.

[.chapter-synopsis]
* 1675-1677.
* George Fox attends the Yearly Meeting, and afterwards sets forward towards the North
* attends the Quarterly Meeting at Lancaster, and goes thence to Swarthmore
* writes many books and papers for the Truth
* the titles of several named
* writes to Friends in 'Westmorland to keep in the power of God, and thereby avoid strife
* writes an epistle to the Yearly Meeting
* makes a collection and arrangement of his various papers and writings, and of the names of divers Friends engaged in particular service, or against the Truth
* some meetings for discipline established in the North in 1653
* recites his labours and travels for establishing meetings for discipline
* a spirit of discord and separation appears in the church
* the separatists are rebuked and reproved
* the establishment of men's and women's meetings is much opposed
* a narrative of the spreading of Truth, and of the opposition from the worldly powers
* death of Priest Lampitt, a persecutor
* George Fox travels again towards the South
* writes to his wife from York
* finds some slack in their testimony against Tithes
* writes an epistle to Friends on the subject
* attends the Yearly Meeting
* with John Burnyeat, and other Friends, visits Wm. Penn at his house at Worminghurst, in Sussex
* sets things in order for visiting Holland
* precious meeting.

Being now at liberty, I visited Friends in London; and having been very weak,
and not yet well recovered, I went, to Kingston.
I did not stay long, but having visited Friends there, I returned to London,
wrote a paper to the parliament, and sent several books to them.
A great book against Swearing had been delivered to them a little before;
the reasonableness whereof had so much influence upon many of them,
that it was thought they would have done something towards our relief,
if they had sat longer.
I stayed in and near London till the Yearly Meeting,
to which Friends came from most parts of the nation, and some from beyond the sea.
A glorious meeting we had in the everlasting power of God.

This meeting being over,
and the parliament also risen (who had done nothing for or against Friends),
I was clear of my service for the Lord at London.
And having taken my leave of Friends there,
and had a glorious meeting with some of them at John Elson's in the morning,
I set forward with my wife and her daughter Susan,
by coach (for I was not able to travel on horseback) towards the North;
many Friends accompanying us as far as Highgate, and some to Dunstable,
where we lodged that night.
We visited Friends, and were visited by them, at Newport-Pagnel, Northampton, and Cossel,
where, amongst others, came a woman, and brought her daughter,
for me to see how well she was; putting me in mind, "`that when I was there before,
she had brought her to me, much troubled with the disease called the King's evil,
and had then desired me to pray for her;`" which I did, and she grew well upon it,
praised be the Lord!
From Cossel we went on by John Simcock's and William Gandy's, to Warrington and Preston,
and so to Lancaster.

I had not been at Lancaster since I was carried
prisoner from thence by the under-sheriff and jailer,
towards Scarbro' Castle.
I found the town full of people; for it was both the fair time,
and the trained bands were met upon a general muster.
Many Friends were also in town from several parts of the county,
because the Quarterly Meeting was to be there the next day.
I stayed two nights and a day at Lancaster,
and visited Friends both at their men's and women's meetings, which were very full,
large, and peaceable; for the Lord's power was over all, and none meddled with us.
Here met us Thomas Lower and his wife, Sarah Fell, James Lancaster, and Leonard Fell,
Next day after the meeting, being the 25th of the 4th Month, we went over the Sands,
with several other Friends, to Swarthmore.

After I had been a while at Swarthmore,
several Friends from divers parts of the nation came to visit me,
and some out of Scotland;
by whom I understood that four young students of Aberdeen were convinced there this year,
at a dispute held there by Robert Barclay, and George Keith,
with some of the scholars of that university.^
footnote:[Some particulars of the controversy here alluded to,
may be seen in Barclay's _Works;_ also in Jaffray's _Diary,_
p. 328-330. The students who were convinced issued a written declaration,
stating the grounds of their change, which remains on record.]

Among others Colonel Kirby paid me a visit, who had been one of my great persecutors;
but now, he said, he came to bid me welcome into the country;
and carried himself in appearance very lovingly.
Yet before I left Swarthmore, he sent for the constables of Ulverstone,
and ordered them to tell me, "`that we must have no more meetings at Swarthmore;
for if we had, they were commanded by him to break them up;
and they were to come the next First-day.`"
That day we had a very precious meeting, the Lord's presence was wonderfully amongst us,
and the constables did not come to disturb us.
The meetings have been quiet since, and have increased.

The illness I got in my imprisonment at Worcester had so much weakened me,
that it was long before I recovered my natural strength again.
For which reason, and as many things lay upon me to write,
both for public and private service,
I did not stir much abroad during the time that I now stayed in the North;
but when Friends were not with me, spent much time in writing for truth's service.
While I was at Swarthmore, I gave several books to be printed.
One, Concerning Swearing.
Another, showing, "`that none are successors to the Prophets and Apostles,
but who succeed them in the same power and Holy Ghost that they were in.`"
Another, "`that Possession is above Profession,
and how the professors now do persecute Christ in Spirit,
as the professing Jews did persecute him outwardly in the days of his flesh.`"
Also the eight following books, viz.:--
_To the Magistrates of Dantzic; Cain against Abel;_ or,
_an Answer to the New Englandmen's Laws;_
__To Friends at Nevis, concerning Watching;__^
footnote:[See _Selections from the Epistles of George Fox,_ by Samuel Tuke.]
_A General Epistle to all Friends in America; Concerning Caesar's due, and God's due,_ etc.;
_Concerning the Ordering of Families;_
_The Spiritual Man judgeth all things;_
_Concerning the Higher Power._

Besides these, I wrote several epistles to Friends, both in England, and beyond the seas;
and answers to divers papers concerning "`the running out of some,
who had opposed the order of the gospel,
and had stirred up much strife and contention in Westmorland.`"
Wherefore I was moved to write a few lines, particularly to Friends there.

[.alt]
=== "`This is for Friends in Westmorland.

"`All live in the power of God, in his Light and Spirit, which first convinced you;
that in it ye may keep in the ancient unity, in humility, in the fear of the Lord,
and his gentle and peaceable wisdom, which is easy to be entreated;
that in the same Power, Light, and Spirit of God,
ye may all be serviceable in your men's and women's meetings,
in the possession of the gospel-order; which gospel, the power of God,
hath brought life and immortality to light;
that in this ye may see over him that hath darkened you.
In this power, the glorious gospel, no apostates can come;
for the power of God was before apostates were, or the fall of man and woman was,
or the devil either, and will be when he is gone.
Therefore praise God in the eternal fellowship of the everlasting gospel of Jesus Christ,
which is not of man, nor by man.
And therefore, all Friends in Westmorland, keep in the power of God,
which will and must preserve and cover you, if ye be preserved.
Let your faith stand in the power of God, and not in the wisdom of men's words,
lest ye fall.
In God's power ye have peace, life, and unity; and for want of keeping in God's power,
and in his righteousness and Holy Ghost, is all this strife come among you.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
I also wrote the following general epistle to Friends at the Yearly Meeting in London:--

[.salutation]
"`My Dear Friends And Brethren,

"`Whom the Lord hath preserved by his eternal power to this day,
over and through many troubles, storms, tempests, and prisons.
Let, therefore, every one's faith stand in the power of God, which is over the Devil,
and was before him.
So your faith standing in the invisible power of God,
stands in that which does not change; and the faith, that Christ Jesus, the power of God,
is the author of, must stand in the power of God;
so then it stands in that which is over all, in which they are established.
To this the apostle brought the church, the true Christians;
and so now the faith of all true Christians, which Christ is the author of,
must stand in the power of God, in which the everlasting kingdom stands.
As every one's faith stands in the power of God, it keeps all in the power of godliness.

"`For as it was in the days of the apostles, when some were crying up Paul and Apollos,
and so forth, he judged them as carnal; and exhorted and admonished them,
that their faith should not stand in men, nor in the words of man's wisdom,
but in the power of God.
He said 'he would not know the speech of them, but the power amongst them;
for the kingdom of God is not in word, but in power.'
So it is to be now.
Every one's faith must stand in the power of God, and not in men,
nor in their speeches or good words.
For we have seen by experience, when any begin to cry up men,
and their faith stands in them, such men as would have people's faith stand in them,
love popularity, and bring not people's faith to stand in the power of God.
Such cannot exalt Christ; and when such fall, they draw a great company after them.
Therefore the apostle would not know such after the flesh,
but would know them that were in the power and Spirit;
and struck down every one's faith that stood hi the words of man's wisdom,
that they might stand in the power of God.
So it must be now.
They whose faith doth not stand in the power of God,
cannot exalt his kingdom that stands in power;
therefore every one's faith must stand in the power of God.

"`The apostle denied popularity, when he judged the Corinthians,
for looking at Paul and Apollos, to be carnal; such are carnal still.
Therefore all should know one another in the Spirit, life, and power, and look at Christ;
this keeps all in humility.
They, whose faith stands in men, will make sects;
as in the days of J. N. and J. P. and others.
The faith of such Christ is not the author of; and if he hath been,
they have erred from it, and made shipwreck of it.
All that are in the true faith, that stands in the power of God,
will judge them as carnal, and judge down that carnal part in them,
that cries up Paul or Apollos; that their faith may stand in the power of God,
and that they may exalt Christ, the author of it.
For every one's eye ought to be to Jesus;
and every just man and woman may live by their faith,
which Jesus Christ is the author and finisher of.
By this faith every man and woman may see God, who is invisible;
this faith gives the victory, and by it he hath access to God.
So every one's faith and hope standing in the power of God, all therein have unity,
victory, and access to God's throne of grace; in which faith they please God.
By this faith they are saved;--by this faith they obtain the good report,
and subdue all the mountains that have been betwixt them and God.

"`This power hath preserved Friends over their persecutors, over the wrath of men,
and above the spoilings of their goods, and imprisonments;
as seeing God who 'created all--who gives the increase of all,
and upholds all by his word and power.'
Therefore let every one's faith be in his power.
In this no schism or sect can come; for it is over them, before they were,
and will be when they are gone.
But perfect unity is in the truth, in the Spirit, that circumcises the body of death,
that puts off the sins of the flesh, and plunges it down with the Spirit.
In the Spirit of God, there is perfect fellowship;
and Christ is the minister of this circumcision and baptism.

"`This is upon me from the Lord, to write unto you, that every one of you,
whose faith Jesus is the author of, may stand in the power of God.
Prom the Lord I warn you, and all everywhere, of the same.
For if a star should fall, which has been a light,
either the earth or the sea does receive it; that is, the earthly mind, or the foaming,
raging people; though neither the seed, light, power, nor truth ever fell,
nor the faith itself, the gift of God; but men going from it, become unsavoury.

"`Adam, whilst he kept in truth, and obeyed the command of God, was happy;
but when he disobeyed the Lord, he fell under the power of Satan, and became unhappy,
though he might talk after of his experiences in Paradise; but he lost his image,
his power and dominion, in which God had created him.

"`The Jews received the law of God, and as long as they kept the law, which was just,
holy, good, and perfect, it kept them good, just, holy, and savoury;
but when they turned their backs on the Lord, and forsook his law,
then they came under the power of darkness, under the powers of the earth,
and were trodden under as unsavoury.

"`So the Christians were called 'a city set on a hill, the light of the world,
and the salt of the earth;' but when they forsook the power of God,
and their faith stood in words and men, and not in the power, then their walls fell down,
though the power in itself stood; and they lost their hill, their saltness,
and their shining.
And as Christendom now does confess,
they are not in the same power and spirit that the apostles were in;
so not in the same salt, nor upon the same hill.
So they came to be trodden under; and the beast, the whore,
and the false prophet are uppermost, the unsavoury.
Their dead faith is in men, and in words; therefore they are full of sects,
and one against another.

"`And now the everlasting gospel, the power of God, is preached again,
which was before the devil was, that darkened man; and by this power of God,
life and immortality are brought to light again.
Therefore every one's faith is to stand in this power,
that hath brought life and immortality to light in them,
that so all may come to be heirs of the power of God, the gospel.
Herein all have a right to the power of God,
which is the authority of the men's and women's meetings,
and of all other meetings set up thereby.

"`Now, as the gospel is preached again, if your faith does not stand in the power,
but in men, and in the wisdom of words, you will grow carnal; and such are for judgment,
who cry up Paul or Apollos, and not Christ, the author of your faith.
They who love to be popular, would have people's faith to stand in them;
and such do not preach Christ, but themselves.
But such as preach Christ and his gospel,
would have every man and woman to be in the possession of it,
and every man and woman's faith to stand in Christ, the author of it,
and in the power of God.
And as their faith stands in the power of God, nothing can get between them and God;
for if any should fall amongst us, as too many have done, that +++[+++love of popularity]
leads its followers either into the waters, or into the earth.

"`If any should go from-the spirit of prophecy, that did open to them,
and from the power, they may speak their experiences,
which the power opened to them formerly.
So might Adam and Eve speak of what they saw and enjoyed in Paradise;
so might Cain and Balaam of what they saw; and also the Jews, Korah and Dathan,
who praised God on the banks, saw the victory over Pharaoh, ate of the manna,
drank of the rock, came to Mount Sinai, and saw the glory of the Lord.
So also might the false apostles speak of their experiences,
and all those false Christians, that turned from the apostles and Christ.
And so may those do now, that err from the Spirit,
that are come out of Egypt (in spirit) and Sodom,
and have known the raging of the Sodomites, as Lot did the outward;
and the pursuit of the spiritual Egyptians,
as the outward Jew did of the outward Egyptians;
yet if they do not walk in the Spirit of God, in the light, unft in the grace,
which keeps their hearts established, and their words seasoned,
and also their faith in the power of God, in which the kingdom stands;
they may go forth like the false Christians, like the Jews, like Adam and Eve, Cain,
Korah, and Balaam, and be wandering stars, trees without fruit, wells without water,
and clouds without rain; and so come to be unsavoury and trodden down;
as Adam who lost Paradise, and the Jews who lost the Holy Land, not walking in the law,
and keeping the command of God; and as the Christians who lost the city, the hill,
the salt, and the light since the apostle's days, and came to be unsavoury,
and to be trodden under foot of men.

"`Therefore, let every one's faith stand in the Lord's power, which is over all;
through which they may be built upon the Rock, the Foundation of God,
the Seed Christ Jesus.
So all in Christ may be always fresh and green;
for he is the green tree that never withers.
All are fresh and green that are grafted into and abide in him,
bringing forth heavenly fresh fruits to the praise of God.
And though Adam and Eve fell from Paradise, the Jews fell from the law of God,
and many of the Christians fell from their prophecies, and erred from the faith,
the Spirit, and the grace; and the stars have fallen, as was spoken in the Revelations:
yet the Spirit, grace, faith, and power of God remain.

"`Many such states have I seen within these twenty-eight years;
though there is a state that shall never fall, nor be deceived,
in the Elect before the world began.
These are come to the end of the prophecies, are in Him where they end,
and renewed by Christ into the image of God which man was in before
he fell,--in that power where he had dominion over all that God made:
and not only so, but they 'attain to a perfect man,
unto the measure of the stature of the fulness of Christ,' who never fell.
In him is the sitting down in life eternal,
where there feet stand sure and fast in the gospel, his power.
Here their bread is sure; and he that cats this bread lives for ever.

"`And all Friends and brethren, that declare God's eternal truth, and word of life,
live in it; be seasoned with grace, and salted with the heavenly salt,
that your lives and conversations may preach
wherever you come;--that there be no rawness,
no quenching of the Spirit, no despising of prophecy either in men or women.
For all must meet in the faith that Jesus is the author of,
and in the light that comes from Jesus, and be so grafted into the life,
that your knowledge may be there one of another, in Christ;
and that there may be none slothful, nor sitting down in earthly things, minding them,
like Demas of old;
lest you clothe yourselves with another clothing than you had at first;
but all keep chaste; for the chaste follow the Lamb.

"`And Friends, that are ministers, possess, as if ye did not; be married,
as if ye were not; and be loose to the world in the Lord's power;
for God's oil will be above all visible things, which makes his lamps burn,
and give light afar off.
Let none strive nor covet to be rich in this world,
in these changeable things that will pass away; but let your faith stand in the Lord God,
who changes not, who created all, and gives the increase of all.

"`Now Friends, concerning faithful men's and women's meetings,
which were set up in God's counsel; whoever oppose them, oppose the power of God,
which is the authority of them.
They are no ministers of the gospel, nor of Christ, that oppose his power,
which all are to possess.
The gospel is to be preached to all nations: as deceit is gone over all nations,
and all nations have drunk the whore's cup, and she hath them in her cage,
her unclean power from the beast and dragon, out of the power of God, and out of truth,
and the Spirit of God the apostles were in;
the power of God must come over all this again;
and all the true ministers that preach the gospel, the power of God,
must bring people into the possession of it again.
I say, whosoever preaches the gospel of Christ and him to people or nations,
those people and nations receiving the gospel, receive the power of God,
that brings life and immortality to light in them;
they see over the devil that hath darkened them, and over the beast, the whore,
and her cage.
So, by the power of God, life and immortality are brought to light in them;
then these men and women, being heirs of this power, the gospel,
are heirs of authority and power over the devil, beast, whore, and dragon.

"`This is their possession and portion;
and they are to labour in their possession and portion,
and do God Almighty's business and service in the possession of the power of God,
the gospel, which is a joyful, glorious, everlasting order.
And here is the authority of our men's and women's meetings,
and other meetings in the name of Jesus, the gospel of Christ, the power of God,
which is not of man, nor by man.
In this are all to meet and to worship God; by this are all to act;
and in this all have fellowship, a joyful fellowship, a joyful and comfortable assembly.
This is the day when, in the eternal light,
all are to take their possession of the gospel and its order, that power of God,
which they are heirs of.
All faithful men and women in every country, city, and nation,
whose faith stands in the power of God, the gospel of Christ, who have received,
and are in the possession of, this gospel, the power of God,
have all right to the power in these meetings; for they are heirs of the power,
which is the authority of the men's and women's meetings.

"`So here is God's choice (and not man's) by his power, of his heirs;
and they have all freedom in this gospel, the power of God, to go to the meetings,
the men to the men's, and the women to the women's; for they are heirs of the power,
which is received in the Holy Ghost; and they see over enmity, and before it was,
by the light, by the life, and immortality, which are brought to light in them.

"`The devil, the author of enmity, cannot get into this authority, power, order,
nor fellowship of the gospel; nor into this life, light, nor unity of the faith,
which gives victory over him that hath separated man from God.
Into the unity of this faith the serpent cannot come,
nor into the worship of God in Spirit and truth can the devil come, or any enmity.
And they that are in this, are in unity over him.
Therefore, let every one's faith stand in the power of God, the glorious gospel;
and let all walk as becomes the gospel, and the order of it.
As every one hath received Christ Jesus, the Lord, so walk in him,
and let him be their Lord and Orderer.
For the preaching of the gospel of Christ Jesus is to
the intent that all may come to be heirs of the gospel,
and into the possession of it; and to be heirs of Christ and of his government,
of the increase of which there is no end; who is over all in his righteousness,
and over all in his light, life, power, and dominion.
Therefore know one another in his power, his gospel,
which is the authority of your meetings; know one another in Christ Jesus,
who is able to restore man out of the state of the fall, into the image of God,
into that power and dominion that man had before he fell, and into Himself,
that never fell, whence they shall go no more forth.
Here is the rock and foundation of God that stands sure.

"`And, Friends, be tender to the tender principle of God in all.
Shun vain disputes and janglings, both amongst yourselves and others;
for that many times is like a blustering wind,
that hurts and bruises the tender buds and plants.
For the world, though they have the words, are out of the life;
and the apostle's disputing with them, was to bring them to the life.
And those disputers, that were amongst the Christians, about genealogies, circumcision,
and the law, meats, drinks, and days, came to be the worst sort of disputers,
whom the apostles judged; for such destroyed people from the faith.
Therefore the apostles exhorted the churches,
that every one's faith should stand in the power of God, and to look at Jesus,
the author of it.
There every graft stands in Christ, the vine, quiet;
where no blustering storms can hurt them; there is safety.
There all are of one mind, one faith, one soul, one spirit,
baptized into one body with the one Spirit, and made all to drink into one Spirit,
one church, one head, that is heavenly and spiritual; one faith in this head, Christ,
who is the author of it, and hath the glory of it; one Lord to order all,
who is the baptiser into this one body.
So Christ hath the glory of this faith out of every man and woman;
and God through him hath his glory, the Creator of all in his power,
the gospel that hath brought life and immortality to light in them;
and their faith standing in it, they know the immortal God, serve and worship him,
in his Spirit and in his truth; by which they are made God's free men and women,
from him that is out of the truth.

"`Now, Friends, you that have long been labourers,
and have known the dealings of the Lord these twenty years (more or less),
as I have often said to you, draw up what you can,
of those passages and sufferings which the Lord hath carried you through by his power,
and how by Him ye have been supported from the first;
that the Lord may be exalted by his power now, and in ages to come,
who hath been the only support, defence, and stay, of his people all along,
over all to himself; to whom be all glory and praise for ever and ever, Amen.
He deserves it in his church throughout all ages, from his living members,
who return the praise to the living God, who lives and reigns over all, blessed for ever;
who is the life, and strength, and health, and length of days of all his people.
Therefore let there be no boasting, but in the Lord, and in his power and kingdom;
this keeps all in humility.

"`And, Friends, in the Lord's power and truth,
what good you can do for Friends in prison, or sufferers, by informing or helping them,
every one bend yourselves to the Lord's power and spirit,
to do his will and his business;
and in that all will have a fellow-feeling of one another's condition, in bonds,
or in what trials and tribulations soever; you will have a fellow-feeling one of another,
having one head, one Lord, and being one body in him.
For God's heavenly flail hath brought out his seed,
his heavenly plough hath turned up the fallow ground,
and his heavenly seed is sown by the heavenly man,
which brings forth fruits to the heavenly sower, in some fifty, sixty,
and a hundred fold in this life;
and such in the world without end will have life eternal.
O, therefore, all keep within; let your lights shine, and your lamps burn,
that you all may be wells full of the living water,
and trees full of the living fruit of God's planting, whose fruit is unto holiness,
and the end everlasting life.

"`The Lord God of power preserve you all in his power.
Let your faith stand therein, that you may have unity in the faith, and in the power;
and by this faith and belief you may be all grafted into Christ, the sure root,
where the eternal Sun of Righteousness shines, in the heavenly and eternal day,
upon his plants and grafts.
This sun never goes down; and the heavenly springs of life,
and showers are known to water and nourish the grafts, and plants, and buds,
that they may always be kept fresh and green, and never wither;
bringing forth fresh and green, and living fruit, which is offered up to the living God,
who is glorified in that you bear much fruit.
The Lord God Almighty keep you, and preserve you all in his power, light, and life,
over death and darkness; that therein you may spread his truth abroad,
and be valiant for it upon the earth, answering that of God in all; that with it,
the minds of people may be turned to him,
so that with it they may come to know the Lord Christ Jesus in the new covenant,
in which the knowledge of the Lord shall cover the earth as the waters do the sea.
His life must go over death, and his light must go over darkness,
and the power of God must go over the power of Satan.

"`So, all ye that are in the light, life, and power,
keep the heavenly fellowship in the heavenly power,
the heavenly unity in the heavenly divine faith, and the unity of the Spirit,
which is the bond of the heavenly Prince of princes' peace;
who bruises the head of the enemy, the adversary, and reconciles man to God,
and all things in heaven and in the earth: a blessed reconciliation!
Let every one's faith stand in the power of God, which Jesus Christ is the author of;
that all may know their crown of life.
For all outward things without the substance, life, and power,
are as the husk without the kernel, and do not nourish the immortal soul,
nor the new-born babe; but that by which it is nourished, is the milk of the Word,
whereby it groweth in the heavenly life, strength, and wisdom.
The gospel is not of man, nor by man, but is the power of God,
and answers the truth in all;
all the possessors of it are to see that all walk according to it;
which everlasting order is ordained of God already,
and all the possessors of him possess their joy, their comfort, and salvation.
My love unto you all, with him that reigns and is over all,
from everlasting to everlasting.

"`Dwell in the love of God, which passeth knowledge,
and edifieth the living members of the body of Christ;
which love of God come to be built up in, and in the holy faith.
This love of God will bring you to bear all things, endure all things,
and hope all things.
From this love of God which you have in Christ Jesus,
nothing will be able to separate you; neither powers nor principalities,
heights nor depths, things present nor things to come, prisons nor spoiling of goods,
neither death nor life.
The love of God keeps above all that which would separate from God,
and makes you more than conquerors in Christ Jesus.
Therefore in this love of God dwell, that with the same love you may love one another,
and all the workmanship of God--that you may glorify God with your bodies, souls,
and spirits, which are the Lord's. Amen.`"

[.signed-section-signature]
G+++.+++ F.

"`All Friends sit low in the life, the Lord's power.
Keep your place in it,
till the Lord and Master of the feast bid you '
sit higher lest you take the highest place,
and be put down with shame.
He that hath au car, let him hear.`"

[.signed-section-signature]
G+++.+++ F.

"`Friends,
take heed of speaking the things of God in the words that men's wisdom hath taught;
for those words will lift up the foolish, that have erred from the Spirit of God;
which words and wisdom are for condemnation, and that which is lifted up by them,
and they that thereby speak the things of God in them.
So that old house, with its goods, must be thrown under the foot of the new birth.

"`And, Friends, I desire that you may all keep the holy order, which is in the gospel,
the glorious order in the power of God, which the devil is out of;
which was before all his orders were, and before the world made any.

"`This joyful order keeps all hearts pure to God, in everlasting peace, unity, and order;
feel it, and keep the order of it, both men and women,
and come to be heirs of the gospel, which brings life and immortality to light;
and to see over that power of darkness, by Him who was before the power of death was.
In this is the holy order of love and peace.
So keep in this, that keeps you always pure; what men and women act in this,
they act in that which will stand when the world is gone.

"`There hath been some scruple about men's and women's meetings.
Men and women in the gospel are heirs of the power, which was before the devil was;
heirs of this, then enter into the possession of it, and do the Lord's business therein.
Every one take care of God's honour, and keep all things in righteousness,
in holiness which becomes God's house, and in that which honours the Lord God.
It eased me, when those meetings were set up; for men and women,
that are heirs of the gospel, have right to the gospel order; and it belongs to them.
Then take your possessions, and practise in it; be not talkers only,
but live and walk in the gospel, the power of God,
which is the authority of your meetings.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 28th of the 2nd Mouth, 1676.

+++[+++Read at the Yearly Meeting in London, the 17th of the 3rd Month, 1676.]

During this time I collected together as many as I could,
of the epistles I had written in former years to Friends.
I made a collection of the several papers that I had written to O. Cromwell,
and his son Richard, in the time of their protectorships;
and to the parliaments and magistrates that were in their times.
I collected also the papers I had written to King Charles II. since his return,
and to his council and parliaments, and the justices or other magistrates under him.
I made another collection of certificates,
which I had received from divers governors of places, judges, justices, parliament-men,
and others, for the clearing of me from many slanders,
which the envious priests and professors, both here and beyond the seas,
had cast upon me.
This I did for the truth's sake, as knowing that their design in slandering me,
was to defame the truth published by me,
and hinder the spreading thereof amongst the people.
Besides these, I made two books of collections; one was,
a list or catalogue of the names of those Friends who went out of the North of England,
when truth first broke forth there, to proclaim the day of the Lord through this nation.
The other was of the names of those Friends that
went first to preach the gospel in other nations,
countries, and places, in what years, and to what parts they went.

I made another collection, in two books;
one of epistles and letters from Friends and others, on several occasions, to me;
the other of letters of mine to Friends and others.

I wrote also a book of the types and figures of Christ, with their significations;
and many other things, which will be of service to truth and Friends in time to come.

I took notice also of those who had run out from truth, drawn others out after them,
and turned against truth and Friends at several times since
the first breaking forth of truth in this latter age,
and what became of them;
noting particularly the repentance and return of
such of them as came back to truth again.
Some ran quite out, and never returned,
but were cut off in their gainsaying and rebellion;
for the word and power of God hath blasted and is blasting them,
and the holy seed hath ground, and is grinding them to pieces.
I have observed, that they who have been convinced,
and have not lived and walked in the truth, have been the worst enemies to the truth,
and done most hurt amongst Friends in the truth, and to others.
In these I have seen fulfilled what the Lord did long since show me,
"`that such should be greater deceivers than all the priests and professors.`"
For such as came as far as Cain, Balaam, Korah, and Dathan,
and could "`preach Christ,`" and say,
"`they had preached in his name;`" such as came to be apostles,
and had tasted of the power of Christ, and then turned from it,
could yet speak their old experiences, and have good words, like Korah and Balaam:
but not keeping in the life and truth, they deceived the hearts of the simple.
Such come to be of the devil, who abode not in the truth; as Cain, and all the Jews,
that abode not in the truth, were.
For though Cain did sacrifice to God, and did talk with God;
and the Jews could talk of Abraham, Moses, and the prophets, yet Christ told them,
"`they were of their father, the devil.`"
In like manner, though they who are called Christians, can talk of Christ,
and use his and his apostles' and disciples' words, yet not abiding in the truth,
and power, and Spirit, that the apostles were in, they are of the devil, out of truth,
and do his work.
So are all those that have been convinced of God's eternal truth
since it sprang up in this nation, that have not abode in the light,
and in the Spirit and power of Christ Jesus; but have turned against the power,
and have opposed the work thereof; though they may retain their former experiences,
and be able to speak many good words,
yet not living in the life and power that gave them those experiences,
they live in the power of darkness, which is of the devil:
and by the light and truth both he and they are condemned;
and must own their condemnation if ever they come to truth again.
For to resist the heavenly power,
and to oppose the workings and divine manifestations thereof through any,
is not a light matter.

As I had been moved of the Lord to travel in his power round this nation,
and in other parts, to preach the everlasting gospel, and to declare the Word of Life,
which was in the beginning, through many imprisonments, hardships, sufferings,
and trials; so I was afterwards moved to travel, in the same heavenly power,
about the nation again (and to write to such places where I came not) to recommend
to Friends the "`setting up of the quarterly and monthly meetings in all counties,
for looking after the poor, taking care for orderly proceedings in marriages;
and other matters relating to the church of Christ;`" though some
meetings for this end were settled in the North of England,
in the year 1653.

After this also, truth still spreading further over the nation,
and Friends increasing in number, I was moved, by the same eternal power,
to recommend the setting up of women's meetings also; that all, both male and female,
who had received the gospel, the Word of eternal Life,
might come into the order of the gospel, brought forth by the power of God,
and might act for God in the power,
and therein do business and service for him in his church.
All the faithful must labour in God's vineyard, they being his hired servants,
and he having given them the earnest of his Spirit.
For a master that hires a servant, and gives him the earnest of his hire,
expects he should do his work, after he knows his will, in the outward creation;
so all God's people, that are of the new creation,
and have received the earnest of his Spirit, ought to labour with, by, and in his Spirit,
power, and grace, and faith, in the light, in God's vineyard,
that they may have their wages when they have done God's work and business in his day,
which is eternal life.
But none can labour in his vineyard, and do his work and will,
but as they walk in the heavenly divine light, grace, and Spirit of Christ;
which it hath been, and is, my travail and labour in the Lord to turn all to.

Some that professed truth, and had made a great show therein,
being gone from the simplicity of the gospel into jangling, division,
and a spirit of separation, endeavoured to discourage Friends (especially the women),
from their godly care and watchfulness in the church over one another in the truth;
opposing their meetings, which, in the power of the Lord,
were set up for that end and service.
Wherefore I was moved of the Lord to write the following epistle,
and send it among Friends, for the discovering of that spirit,
by which those opposers acted, its work and way, by which it wrought,
and to warn Friends of it, that they might not be betrayed by it:--

[.small-break]
'''

"`All my dear Friends, Live in the seed of peace, Christ Jesus, in whom ye have life.
That spirit that comes amongst you to raise up strife, is out of Christ;
for it is the spirit that is not easy to be entreated, not gentle,
so not of the wisdom of God, which is justified of her children.
They that follow that spirit, are none of Wisdom's children.
There is a spirit that hath made a separation,
and has been against men's and women's meetings;
yet those of this spirit have set up one of their own, to which they have given power,
and allow none to sit amongst them but such as they give power to,
looking upon others as usurpers of authority.
This spirit and its work is not of God, though it has made a jumble amongst some;
and the path it may travel in, is through the earthly affections,
amongst the unestablished, or apostates.
But all that are in the life, Spirit, and light, in the grace, truth, and power of God,
bar it out; and such as sit under their own vine, Christ Jesus, and are grafted into him,
have no need of their exhortation or counsel;
for the true believers are entered into their rest.
Therefore all keep in the gospel of peace; and you that are heirs of the kingdom,
keep in your possession of it.

"`Some of this spirit have said to me, 'they see no service in women's meetings.'
My answer is, and hath been to such, if they be blind and without sight,
they should not oppose others; for none impose anything upon them.
God never received the blind for a sacrifice, neither can his people.
But Christ has enlightened all; and to as many as receive him,
he gives 'power to become the sons of God.'
Such as are heirs of his power, and of his gospel,
which brings life and immortality to light, can see over him that has darkened them;
and all such keep the order of the gospel, the power of God, and their meetings therein,
which preserves them in life and immortality.
These see the great service of men's and women's meetings, in the order of the gospel,
the power of God; for they are meet-helps in this power,
which is the authority of their meetings.
Now I say to all of you, that are against women's meetings or the men's, and say,
'you see no service for the women's meetings,' and oppose them,
you are therein out of the power of God, and his Spirit you live not in.
For God saw a service for the assemblies of the women in the time of the law,
about those things that appertained to his worship and service,
and to the holy things of his tabernacle;
and so they in his Spirit see now their service in the gospel;
many things in these meetings being more proper for the women than the men;
and they in the power and wisdom of God may inform the
men of such things as are not proper for them;
and the men may inform the women of such things as are not proper for them,
as meet-helps to each other.
For in the time of the law, the women were to offer as well as the men;
so in the time of the gospel much more are they to offer their spiritual sacrifices;
for they are all called, both men and women, a royal priesthood;
they are of the household of faith;
they are the living stones that make up the spiritual building,
which Christ is the head of; and are to be encouraged in their labour in the gospel;
for all things that they do, both men and women, are to be done in the power of God.
All such as see no service for these women's meetings, or the men's, but oppose them,
and make strife amongst Friends, are in the spirit of the world, that is against,
and forbids our other meetings;--are in the same spirit of the world, that hath been,
and is against women's speaking in meetings, and say, 'they must be silent,' etc.,
though the same apostle commands,
'that men should keep silence as well as the women,' if there were not an interpreter.
Therefore, you may see that the spirit of the world hath entered such opposers,
though they come under another colour; for they would not have us to meet at all.
And these are against the women's meetings, and some of them against the men's also,
and say, 'they see no service for them;' then they may hold their tongues,
and not oppose them that do see their service for God in these meetings.

"`Therefore, all you that feel the power of God, and your service for God in them,
both men and women, keep your meetings in the power of God, the authority of them,
as they were settled in it;
then ye will be preserved both over this spirit that opposes them,
and over the spirit of the world that opposes your other meetings;
for it is all one in the ground, and would bring you into bondage.
Such are out of the peaceable gospel, who oppose its order;
out of the faith that works by love; out of the wisdom that is gentle, easy,
and peaceable, etc., and out of the kingdom that stands in peace and joy.
Therefore, keep over that spirit that sows discord or dissension,
and would draw you from your habitation and possession in the order of the gospel;
for it is the same spirit that deceived Adam and Eve,
by which they lost their habitation in righteousness and holiness, and their dominion;
so that spirit got over them; and so it would get over you.
One while it will tell you,
'it sees no service for your meetings,' and another time oppose you.
But I say, this is the blind spirit, which is out of the power of God,
and which the power of God is over.
Therefore, keep in the power, that ye may stand up for your liberty in Christ Jesus,
males and females, heirs of him and of his gospel, and his order.
Stand up for your liberty in the gospel, and in the faith,
which Christ Jesus hath been the author of; for if ye lose it,
and let another spirit get over you, ye will not soon regain it.
I knew the devil would bestir himself in his instruments,
when men's and women's meetings came to be set up in the power, light, and truth,
and the heirs of the gospel, to take their possession of it in every county and city,
therein to walk, and to watch one over another, to take care of God's glory and honour,
and his precious truth; and to see that all walk in the truth, and as becomes the gospel,
and that nothing be lacking; and so to exhort all whatsoever is decent, modest, virtuous,
lovely, comely, righteous, and of good report, to follow after;
to admonish all that are not faithful, and to rebuke all that do evil.
I knew this would give such a check to all loose speakers, talkers, and walkers,
that there would be an opposition against such meetings.
But never heed, truth will come over them all, and is over them all,
and faith must have the victory; for the gospel and its order is everlasting;
the Seed (Christ) is the beginning and the ending, and will outlast all; the Amen,
in whom ye have peace.
I say all that oppose the men's and women's meetings,
or that marriages should be laid before them,
or the recording of condemnations of sin and evil,
or admonishing or exhorting such as walk not in the truth, are of a loose spirit,
and their spirits tend to looseness.
Let those take them that will; truth will not have them, nor any of their sacrifice;
for nothing is accepted of God, but what is done in truth, and in his Spirit,
which is peaceable.
The authority of our men's and women's meetings is the power of God;
and all the heirs of the gospel are heirs of that authority and dignity; this is of God,
and shall answer the witness of God in alL The
greatest opposers of this practice and work,
are such as have been convinced of God's truth, but have not lived in it.
Such were the greatest troublers of the church in Moses' day,
and in the days of the apostles; but mark their end, and read what became of them all.
And therefore, all keep your habitation in the truth,
and therein ye may see what has become of all the opposers of it for twenty years past;
they are all gone, and the truth lives and reigns; the Seed is over all,
and all are one in it, in rest, peace, and life everlasting;
and therein they sit down together in the heavenly places in Christ Jesus, the Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 5th of the 8th Month, 1676.

[.alt]
=== Narrative of the spreading of Truth, and of the opposition thereto.

"`The truth sprang up first to us, so as to be a people to the Lord,
in Leicestershire in 1644, in Warwickshire in 1645, in Nottinghamshire in 1646,
in Derbyshire in 1647, and in the adjacent counties in 1648, 1649, and 1650;
in Yorkshire in 1651, in Lancashire and Westmorland in 1652; in Cumberland, Durham,
and Northumberland in 1653; in London, and most of the other parts of England, Scotland,
and Ireland, in 1654.

"`In 1655 many went beyond sea, where truth also sprang up,
and in 1656 it broke forth in America and many other places.

"`In the authority of this divine truth,
Friends stood all the cruelties and sufferings that
were inflicted upon them by the Long Parliament;
to the spoiling of goods, imprisonment, and death, and over all reproaches, lies,
and slanders; as well as those in Oliver Cromwell's time,
and all the acts made by him and his parliament; his son Richard after him,
and the Committee of Safety;
and afterwards withstood and outlasted all the acts and proclamations since 1660,
that the king came in.

"`Friends never feared their acts, prisons, jails, houses of correction, banishment,
nor spoiling of goods, nay, nor the loss of life itself;
nor was there ever any persecution that came,
but we saw in the event it would be productive of good;
nor were there ever any prisons that I was in, or sufferings,
but it was for the bringing multitudes out of prison;
though they who imprisoned the truth, and quenched the Spirit in themselves,
would imprison and quench it without them;
so that there was a time when so many were in prison,
that it became as a by-word,' truth is scarce anywhere to be found but in jails.'

"`And after the king came in, divers Friends suffered much,
because they would not drink his health, and say,
'God bless the king;' so that many Friends were
in danger of their lives from rude persons,
who were ready to run them through with their swords for refusing it,
until the king gave forth a proclamation against drinking healths;
for we were and are against drinking any healths, and all excess,
both before his coming in and after; and we desire the king's good,
and that the blessing of God might come upon him and all his subjects,
and all people upon the face of the earth;
but we desired people not to drink the king's health, but let him have his health,
and all people else; and to drink for their own health and necessity only;
for that way of drinking healths, and to excess, was not for the king's health,
nor their own, nor any others';
which excess often brought forth quarrelling and destroying one another;
for they destroyed the creation and one another; and this was not for the king's wealth,
nor health, nor honour,
but might grieve him to have the creatures and his subjects destroyed;
and so the Lord's power gave us dominion over that also, and all our other sufferings.
But,

"`O! the number of sufferers in the Commonwealth's and Oliver Cromwell's days, and since;
especially those who were haled before the courts for not paying tithes,
refusing to swear on their juries, not putting off their hats,
and for going to meetings on the First-days; under pretence of breaking the Sabbath;
and to meetings on other days of the week;
who were abused both in meetings and on the highways.

"`O! how great were the sufferings we then sustained upon these accounts! for
sometimes they would drive Friends by droves into the prison-houses like penfolds,
confine them on the First-days, and take their horses from them,
and keep them for pretended breach of their Sabbath,
though they would ride in their coaches and upon their
fat horses to the steeple-houses themselves,
and yet punish others.
And many Friends were turned out of their copyholds and customary tenements, because,
in obedience to the command of Christ and his apostle, they could not swear;
and as they went to meetings, they have been stoned through the streets,
and otherwise cruelly abused.
Many were fined with great fines, and lay long in prison for not putting off their hats,
which fines Friends could never pay,
though they kept them in prison till they had satisfied their own wills,
and at last turned them out, after keeping them a year or more in prison.

"`Many books I gave forth against tithes,
showing how the priesthood was changed that took them;
and that Christ sent forth his twelve, and afterwards seventy disciples,
saying unto them, 'Freely ye have received, freely give.'
So all who do not obey the doctrine and command of Christ therein, we cannot receive them.

"`I was also moved to give forth several books against swearing,
and that our Yea and Nay might be taken instead of an oath, which, if we broke,
let us suffer the same punishment as they who broke their oaths.
And in Jamaica the governor and the assembly granted the thing;
it is also granted in some other places;
and several of the parliament-men in England
have acknowledged the reasonableness thereof.
The magistrates, after some time, when they saw our faithfulness in Yea and Nay,
they who were moderate, both before and since the king came in,
would put Friends into offices without an oath;
but the cruel and envious would fine Friends to get money off them,
though they could not pay them any.

"`Thus the Lord's power hath carried us through all, and over all,
to his everlasting glory and praise; for God's power hath been our hedge,
our wall and our keeper (the preserver of his plants and vineyard),
who have not had the magistrates' sword and staff to help us,
nor ever trusted in the arm of flesh, but have gone without these, or Judas' bag,
to preach the Word of life, which was in the beginning before they were;
which reconciles to God.
And thousands have received this Word of reconciliation,
and are born again of the immortal Seed, by the Word of God;
and are feeding upon the milk of the Word, which lives and abides for ever.

"`Many have suffered death for their testimony, in England and beyond the seas,
both before and since the king came in;
which may be seen in an account given to the king and both houses of parliament;
being 'A brief, plain,
and true relation of the late and sad sufferings
of the people of God in scorn called Quakers,
for worshipping and exercising a good conscience towards God and man.'

"`By reason whereof eighty-nine have suffered till death;
thirty-two of whom died before the king came into England, and fifty-seven since,
by hard imprisonment and cruel usage.
Forty-three have died in the city of London and
Southwark since the Act made against meetings,
etc., about 1661, of which a more particular account was given,
with the names of the sufferers, to the king and parliament, about 1663.

"`And though divers laws were designed against us,
yet never could any of them justly touch us,
being wrested and misapplied in their execution by our adversaries,
which some have been made to confess.
All those laws that were made, and the oath which they imprisoned us for, because,
in obedience to the command of Christ Jesus, we could not swear at all,
were not originally intended against us; and yet we suffered by the several powers,
and their laws, both spoiling of goods and imprisonment, even to death.
And the governor of Dover castle,
when the king asked him if he had dispersed all the sectaries' meetings?
said, that 'he had; but the Quakers, the devil himself could not;
for if he did imprison them, and break up their meetings, they would meet again;
and if he should beat them or knock them down, or kill some of them, all was one,
they would meet, and not resist again.'
Thus the Lord's power supported and kept them over their persecutors,
and made them to justify our patience and lamb-like nature.
This was about 1671.

"`Since the king came in, three acts have been made against us,
besides the proclamations, by which many have suffered imprisonment and banishment,
and many to death.
And yet for all these acts and proclamations, persecutions, sufferings, banishments,
faithful Friends are as fresh as ever in the Lord's power,
and valiant for his name and truth.

"`Some weak ones there were, when the king came in, who took the oath;
but after they had so done,
they were sore troubled for disobeying the command of Christ and the apostle,
and went to the magistrates, condemned themselves, and offered to go to prison.

"`Thus the Lord, in his everlasting power, hath been the support and stay of his people;
and still his Seed reigns, his truth is over all,
and exceedingly spreads unto this year 1676.

[.small-break]
'''

In 1676, while I was at Swarthmore, died William Lampitt,
the old priest of Ulverstone (which parish Swarthmore is in). He was an old deceiver,
a perverter of the right way of the Lord, and a persecutor of the people of God.
Much contest I had with him, when I first came into those parts.
He had been an old false prophet;
for in 1652 he prophesied (and said he would wage his life upon it),
"`that the Quakers would all vanish,
and come to nought within half a year:`" but he came to nought himself.
For he continued in his lying and false accusing of God's people,
till a little before he died, and then he cried for a little rest.
To one of his hearers that came to visit him before he died, he said,
"`I have been a preacher a long time, and thought I had lived well;
but I did not think it had been so hard a thing to die.`"

After I had finished the services which lay upon me then to do,
feeling my spirit drawn again towards the south (though I was yet but weakly,
and not able to travel far in a day), I left Swarthmore the 26th of the 1st Month, 1677,
and went to Thomas Pearson's at Poobank, in Westmorland,
where I had a meeting the next day; and thence to Thomas Camm's,^
footnote:[Thomas Camm, of Camsgill, in Westmorland, was born in 1641,
and had a good education.
He was from childhood inclined to be religious,
was early convinced of Friends' principles,
and after some time called to the work of the ministry.
He counted nothing too near or dear to part with for truth's sake,
but left all to follow the Lord, and, with his whole strength and substance,
was given up to serve him.
He was an able preacher, diligent and laborious in the work of the Lord,
and instrumental to convince and establish many in the way of truth.
His doctrine was sound,
and his delivery in the demonstration of that Divine power which reached the
witness of God in the hearts of his hearers.
{footnote-paragraph-split}
Great and many were the sufferings he met with and went through,
as, imprisonments, spoiling of goods, mockings and scoffings from those without,
and suffering among false brethren; in all which, he stood firm and faithful,
approving himself a true follower of Jesus Christ,
suffering joyfully for his name's sake, who had counted him worthy not only to believe,
but suffer for him.
During an illness of some continuance,
many were the weighty expressions that fell from him,
often magnifying the Lord to the tendering of all hearts present.
When grown very weak, being asked how he felt, he would say, "`Weak of body,
but strong in the Lord;`" saying also, "`In Abraham's bosom there is sweet repose.`"
Seeming to be faint, a friend gave him a little wine, thinking it might refresh him,
but his stomach could not bear it; then looking at him he said,
"`Thou seest these things will not do; but one cup of new wine in the heavenly kingdom,
with my dear and blessed Lord and Saviour Jesus Christ,
will make up all.`"--for further particulars, see _Piety Promoted,_ vol ii., p. 101-108.]
at Cam's-gill, where Robert Widders with his wife,
and several other Friends came to see me before I left the country,
and to attend the meeting there next day, which was very large,
and in which I was largely drawn forth in testimony to the truth.
I had much discourse with some of that meeting,
who were not in unity with the quarterly meeting they belonged to;
but afterwards several of them that were somewhat tender, came to see their error,
and gave forth condemnations against themselves.
Next day John Blakelin came to Thomas Camm's,
to bring me to his house at Drawell in Sedbebgh, whither I went with him,
visiting Friends in the way.
I stayed at Drawell two or three nights, having meetings there and thereabouts;
for while I was there the men's and women's meetings were held there,
which were very large and precious.
The First-day following I had a meeting at Bigflats,
to which came most of the Friends from the several meetings round about,
and a great concourse of others also;
it was thought there were five or six hundred people.
A very good meeting it was, wherein truth was largely declared and preciously opened,
to the comforting and refreshing of the faithful,
and the drawing near of them that were afar off.
I had another meeting at John Blakelin's,
at which were many Friends that were going to the quarterly meeting at Kendal.
With them my wife went back, who, with her daughter Rachel, had accompanied me thus far;
and I, having Leonard Fell with me, passed on through Sedbergh and Garsdale,
into Wensleydale, visiting Friends as we went.
At night I reached Richard Robinson's at Counterside,
where several Friends came to me that evening;
some of whom went with me next day over the hills to the widow Tenant's at Scarhouse,
in Langstroth-Dale, which we had much difficulty to reach, the snow lay so deep,
though it was a week in the 2nd Month.
Here, on First-day, we had a large meeting,
Friends coming to it from several parts round about;
and the Lord gave me a very seasonable testimony to bear amongst them,
which I did for several hours, to their great satisfaction and comfort.
Thence passing through Bishopdale, Middleham, Barton, and so by Bedale and Northallerton,
I came to George Robinson's at Burrowby; where also Friends coming out of several parts,
we had a very large and good meeting, and very peaceable.
But not long after, an envious justice, who lived not far off,
hearing that I had a great meeting there, troubled Friends about it,
and made them appear at the sessions, where he asked them many ensnaring questions;
for he knew not how to convict them, because he had no proof against them.
When he saw his questions did not catch them, he told them,
"`he had heard that George Fox was at a large meeting with them, and they all sat silent,
and none spoke in the meeting.`"
This false story he cunningly feigned,
thinking thereby to draw out some of the Friends to contradict him, and say,
"`that I had spoken in the meeting;`" that so he
might convict them upon their own confession, and fine them.
But Friends standing in the wisdom of God, did not answer him according to his desire,
and so escaped his snare.
But two Friends that came out of Ireland, and were at this meeting,
having another that evening about three miles off,
this evil-minded justice got information thereof, and fined Friends,
and plundered them very sorely for it.

I went from Burrowby to Isaac Lindley's, calling upon Friends as I went.
Robert Lodge and other Friends being with me, we passed next day to York,
and the day following, being First-day, I was at Friends' meeting there,
which was large and peaceable.
Second day also I stayed in York, and had two meetings with Friends at John Taylor's;^
footnote:[John Taylor was an able minister amongst the early Friends,
but a very brief account is preserved of his religious labours.
He was born in Huntingdonshire (?) about the year 1638.
He embarked on a gospel mission to America in 1660,
being then only in the twenty-second year of his age.
How long he was occupied there is not stated,
but his religious services were not confined to the English settlers.
Trusting to the never-failing arm of Divine guidance and protection,
he travelled alone among the Indian tribes,
and "`had meetings in the woods and wilderness,
to declare the truth to them,`" as he remarks,
"`and to turn them from darkness to the light of Christ Jesus in their own hearts.`"
By these untutored sons of the forest the stripling preacher was "`received
with kindness,`" and in their wigwams he became a welcome guest,
"`They heard me soberly,`" he says, "`and confessed to the truth I spoke,
by an interpreter;
and they were loving and kind afterwards to Friends.`"
{footnote-paragraph-split}
On his return from America,
John Taylor, being on gospel service in London,
was taken from a meeting and committed to prison.
He visited America a second time, and resided some time in Jamaica, also in Barbadoes,
where he became a merchant, but finally returned to England,
and settled at York as a sugar-refiner.
After which,
he was also largely engaged in the ministry in different parts of the nation,
and died in 170S, aged about seventy,
a minister about fifty years.
{footnote-paragraph-split}
John Taylor is described by a contemporary as "`an able minister of the New Testament;
in the publishing of which, the Spirit of God and of glory rested upon him,
to the comforting and true refreshment of the churches, where the Lord ordered him,
or his lot was cast.`"]
whence I wrote to my wife, as follows:--

[.salutation]
"`Dear Heart,

"`To whom is my love, and to thy daughters, and to all Friends that inquire after me.
My desires are, that ye all may be preserved in the Lord's everlasting Seed,
in whom ye will have life and peace,
dominion and settlement in the everlasting home or
dwelling in the house built upon the foundation of God.
In the power of the Lord I am brought to York, having had many meetings in the way.
The road was many times deep and bad with snow, our horses sometimes were down,
and we were not able to ride; and sometimes we had great storms and rain;
but by the power of the Lord I went through all.
At Scarhouse there was a very large meeting, and another at Burrowby,
to which Friends came out of Cleveland and Durham; and many other meetings we have had.
At York, yesterday, we had a very large meeting, exceedingly thronged,
Friends being at it from many parts, and all quiet, and well satisfied:
O! the glory of the Lord shone over all.
This day we have had a large men's and women's meeting, many Friends, both men and women,
being come out of the country, and all was quiet;
and this evening we are to have the men's and women's meeting of the Friends of the city.
John Whitehead is here, with Robert Lodge^
footnote:[Robert Lodge, mentioned before, was of Masham, in Yorkshire,
born about the year 1636.
He was religiously inclined from his youth, was convinced about 1658,
and became a valiant gospel minister.
He was very serviceable in gathering many out of the ways of the world,
into the way of life, travelling up and down in the service of his Lord,
enduring many trials, exercises, and imprisonments, for his sake.
John Whiting says of him, "`He was an excellent minister;
he had a fine refreshing testimony, and an extraordinary gift in prayer.
He was instrumental to turn many to righteousness,
and to build them up in the most holy faith.
His testimony reached to the witness of God in the consciences of many;
and was a consolation to the watering and refreshing many weary souls.
He kept his first love and habitation in the truth to the last; and,
towards his latter end, laboured much with and for the young generation,
that they might come up in the footsteps of those who were gone before.
He was a man of a sweet disposition, and left a good savour behind him.
Much might be said of him,
but I refer to the __Several Living Testimonies
given forth by divers Friends concerning him,
and his Faithful Labours and Travels,__ printed in 1691.`"]
and others; Friends are mighty glad, above measure.
So I am in my holy element, and holy work in the Lord, glory to his name for ever!
To-morrow I intend to go out of the city towards Tadcaster,
though I cannot ride as in days past;
yet praised be the Lord that I can travel as well as I do!
So with my love in the fountain of life, in which as ye all abide,
ye will have refreshment of life,
that by it ye may grow and gather eternal strength to serve the Lord, and be satisfied.
To the God of all power, who is all-sufficient to preserve you,
I commit you all to his ordering.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
York, the 16th of the 2nd Month, 1677.

Leaving York, I visited Friends at Tadcaster, Knottingley, Doncaster, and Balby,
having meetings as I went.
At Balby I stayed the First-day meeting,
and went next day to Thomas Stacy's at Ballowfield, where in the evening I had a meeting,
to compose a difference that had happened between some that professed truth,
and they were reconciled.
Next day I came to Stainsby in Derbyshire,
in which county I had formerly lived about the first breaking forth of truth.
Here I had a good meeting with Friends,
and afterwards passed to Skegby in Nottinghamshire, and from thence to Nottingham,
to John Reckless's. I had a meeting with Friends at his house that evening,
and another next day in Friends' public meeting-house, which was peaceable and well.

I went the day following to John Fox's at Wimeswould in Leicestershire,
where I had a meeting that evening; and next day to William Smith's at Sileby, where,
it being First-day, we had a very large meeting; for besides Friends from several places,
many of the town's-people hearing I was there, came to it,
and heard the truth declared gladly.
Next day I went to Leicester, where finding many Friends come out of the country,
to be at the horse-fair next day, I had a very good meeting with them that night;
and another next evening at William Wells's house at Knighton,
about a mile from Leicester.
Next day I passed to Swannington, and had a meeting there;
thence to Samuel Fretwell's at Hartshorn in DerbyShire, where I had a meeting also;
then to Henry Sidon's, at Badgley in Warwickshire, and stayed the meeting there, which,
it being First-day, was very large and peaceable,
notwithstanding a justice had threatened to come and break it up.
Having stayed a while with Friends,
I went in the evening to Richard Baal's of Whittington,
where several Friends came to visit me.
Next day I went to Nathaniel Newton's at Hartshill, where several Friends met me,
with whom I had good service.
After this I passed on, visiting Friends in divers places, till I came to Dingley,
where a meeting was appointed before, which was very large,
and truth was largely opened to the people.
It was peaceable and quiet, and the people generally sober;
saving that while I was showing how Christendom (so called)
was gone from the pure religion that is undefiled,
etc., one man rushed out in a furious manner, and said, "`I deny that.`"
After this meeting I went with Thomas Charles to his house at Adingworth,
and next day to Northampton, where I stayed the First-day meeting,
which was very large and peaceable.
I had much service among Friends besides.
Next day Edward Cooper of Northampton, accompanied me to Olney in Buckinghamshire,
where I stayed at James Brierlie's, several Friends coming to see me in the evening.
Next day I went to a meeting at Turvey in Bedfordshire,
to which Friends came from several parts; so that it was very large.
Here I met with William Dewsbury,
who after the meeting took me to his son-in-law John Bush's of Kempston,
where I stayed with William that night and most of next day,
passing thence towards evening through Ampthill, to Thomas Gamboll's of Bullock's Hill.
William Dewsbury went along with me, and several Friends came to visit us.
Next day, passing through Luton, I went to Market Street,
William Dewsbury accompanying me part of the way, and the day following Leonard Fell^
footnote:[The above is the last mention of Leonard Fell,
whose name has frequently occurred in the progress of this Journal.
Very little is known of him but that he was a faithful minister amongst the early Friends.
I feel inclined to insert an anecdote respecting him,
as an instance among others that might be adduced,
of the carrying out of the non-resistant principle.
The conduct of several "`Friends`" who, having "`fallen among thieves,`" were, of course,
precluded from retaliating violence, even in their own defence,
affords an exemplification of this feature in the Christian character.
{footnote-paragraph-split}
Leonard Fell, when travelling alone, was attacked by a highwayman, who demanded his money,
which he gave him; then he desired to have his horse;
Leonard dismounted and let him take it.
Then feeling the power of truth rise in his mind, he turned to the robber, and,
under its authority, solemnly warned him of the evil of his ways;
but he flying into a passion, asked the Friend why he preached to him,
and threatened to blow out his brains.
But Leonard replying to this effect,
"`Though I would not give my life for my money or my horse,
I would give it to save thy soul,`" so struck the astonished robber, that he declared,
if he was such a man as that, he would take neither his money nor his horse from him;
and, returning both to the faithful Friend, went his way,
leaving Leonard to the enjoyment of that peace,
attending the honest discharge of his conscience,
to obtain which he had not counted his life dear.
{footnote-paragraph-split}
The courage and presence of mind exhibited by the true soldier of Jesus Christ,
when permitted, in the course of Divine Providence,
to be cast into straits and trying situations, is often conspicuous.
He not only knows the strength of that preserving arm,
which rules or overrules all circumstances for the good of those that are faithful,
he not only is furnished for all occasions,
and "`out of weakness is made strong,`" so as even to "`stop the
mouths of lions,`" and "`quench the violence of fire`" (Heb.
xi.), but is abundantly furnished with resignation to submit unto the Lord in all things;
and, with one who was "`in perils of robbers,`" and "`in deaths oft,`" he can say,
"`Whether we live or die, we are the Lord's.`" (Rom. 14:8).]
and I had a meeting at Kensworth, which was pretty large and peaceable.
After it we went to Alban's, where we visited Friends;
and next day passing through South Mims and Barnet, where also we visited Friends,
we came that night to widow Hayley's at GuttersHedge in Hendon, in Middlesex.
Next day, being First-day, we had a very large meeting there,
several Friends coming from London.
I stayed there Second-day, and on third went to William Mead's house at Highgate,
with whom next day I went to London.
It being Fourth-day, I went to the meeting at Gracechurch Street,
where Friends and I were greatly refreshed in each other in the Lord,
and the Lord's power and Seed were set over all, blessed be his name for ever!

Thus it pleased the Lord to bring me safe to London, though much wearied,
for though I rode not very far in a day, yet through weakness of body,
continual travelling was hard to me.
Besides, I had not much rest at night to refresh nature;
for I often sat up late with Friends, where I lodged,
to inform and advise them in things wherein they were wanting; and when in bed,
I was often hindered of sleep by great pains in my head and teeth, occasioned,
as I thought, from cold taken by riding often in the rain.
But the Lord's power was over all, and carried me through all, to his praise.

In my journey I observed a slackness and shortness in some that professed the truth,
in keeping up the ancient testimony against tithes;
for wherever that spirit got entrance, which wrought division in the church,
and opposed the men's and women's meetings,
it weakened those that received it in their testimony against tithes.
Wherefore I was moved of the Lord to issue a short "`
Epistle to Friends,`" to stir up the pure mind,
and to encourage and strengthen them in their Christian
testimony against that antichristian yoke and oppression:--

[.salutation]
"`My Dear Friends,

"`Be faithful to the Lord in your testimony for Jesus,
who ended the Levitical priesthood of Aaron, that took tithes,
and sent his ministers forth freely,
to give freely that which they had received of him freely, without a bag or a staff.
Christ's disciples could not join with those that made a trade of preaching.
And as there was a testimony to be borne against those tithes which were commanded,
in the law, for Levi and Aaron, so there is a testimony to be borne against these tithes,
which have been set up by man, in the dark time of Popery, and not by God or Christ.
Now to cry against the priests in words, and yet to give them means,
and put into their mouths, that they may not prepare war against you, is a contradiction.
Therefore take heed; for if the Lord bless you with outward creatures,
and you bestow them upon Baal's priests,
he may justly require the outward things from you again, which he hath given you:
who saith, that his ministers should freely give, as they have freely received.
So all the preachers for tithes and money, and the takers and payers of tithe,
must be testified against in the Lord's power and Spirit;
that all may stand up in their testimony for Jesus Christ, in his power and Spirit,
against the tithe-mongers.
Consider how many faithful servants and valiants of the Lord,
have laid down their lives against them, in this day of the Lord;
and in the days of the martyrs they did witness against them.
Consider also what judgments have come upon those that spoiled Friends' goods,
and cast them into prison for tithes and maintenance.
Therefore in the power of the Lord, maintain the war against the beast,
and do not put into his mouth, lest he cry peace to you;
which peace you must not receive; but it must be broken,
and thrown out by the Spirit of God.
Then in the same Spirit, ye will receive from the Son of Peace,
that peace which the beast, and the whore, and the world,
with all their earthly teachers for the earth, made by man, cannot receive,
nor bereave you of.
Therefore keep your authority and dominion in the power, Spirit, and name of Jesus,
in whom my love is to you.'

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
3rd Month, 1677.

I came to London on the 23rd of the 3rd Month,
ten or twelve days before the Yearly Meeting,
in which time I fell in with Friends there in the service of truth,
visiting them at the meetings.
The parliament then sitting, we prepared something to lay before them,
concerning the seizing of the third part of Friends' estates, as Popish recusants,
which was a great suffering, and a grievance we complained of;
but we obtained no redress.

To the Yearly Meeting many Friends came from most parts of the nation;
and some out of Scotland, Holland, etc., and very glorious meetings we had,
wherein the Lord's powerful presence was very largely felt;
and the affairs of truth were sweetly carried on in the unity of the Spirit,
to the satisfaction and comfort of the upright-hearted; blessed be the Lord for ever!
After the Yearly Meeting, having stayed a week or two with Friends in London,
I went down with William Penn^
footnote:[A close intimacy existed between William Penn and George Fox,
which enabled the former to indite so admirable an introduction to these volumes.
The name of William Penn occurs frequently in these pages.
Scarcely any name is more generally known or respected
by those of other religious persuasions than his;
indeed, so familiar are most readers with his history,
that it would be superfluous to enter into much relating to him.
{footnote-paragraph-split}
It may suffice briefly
to state that his birth and education were both good;
he being the son of Admiral Penn, who was knighted by Charles II;
and became a great favourite with the Duke of York, afterwards James II. William,
his son, was born at London in 1644.
He imbibed religious impressions as early as his twelfth year.
In his fifteenth year he entered a student at Christ church, Oxford.
On his return home he exhibited a religious seriousness and manner of deportment,
which (as likely to stand in the way of his worldly preferment) was so
displeasing to his father that he turned him out of doors.
{footnote-paragraph-split}
Ultimately he joined the despised Quakers,
a step which highly displeased his father the Admiral;
but he became quite reconciled to him before his death.
Penn continued to advance in religious growth, became a minister amongst the Quakers,
and a considerable writer in defence of their principles,
suffering persecution and imprisonment in consequence.
It was whilst he was imprisoned in the Tower that he wrote that excellent work,
_No Cross, No Crown._
{footnote-paragraph-split}
The
persecution of Dissenters continuing to rage in England,
notwithstanding their repeated applications to parliament for sufferance and protection,
William Penn turned his thoughts towards a settlement in the New World,
as a place where himself and his friends might enjoy
their religious opinions without molestation,
and where an example might be set to the nations of a just and righteous government.
He therefore, in 1681, obtained a patent from Charles II.,
for a province in North America, in consideration of his father's services,
and of a debt still due to him from the crown.
He founded the colony of Pennsylvania,
and watched it with a paternal eye till his death in 1718.
Its prosperity is a lasting monument of his wisdom as a politician and a legislator.
For further particulars, the reader is referred to Clarkson's _Life of William Penn,_
a cheap edition of which has recently been published by Bradshaw and Blacklock,
Manchester.
It is a highly interesting work, well worthy of perusal.]
to his house in Sussex; John Burnyeat and some other Friends being with us.
As we passed through Surrey, hearing the quarterly meeting was that day, William Penn,
John Burnyeat, and I, went from the road to it;
and after the meeting returning to our other company,
went with them to William Penn's that night; which is forty miles from London.
I stayed at Worminghurst about three weeks;
in which time John Burnyeat and I answered a very envious and wicked book,
which Roger Williams,
a priest of New England (or some colony thereabouts)
had written against truth and Friends.
When we had finished that service,
we went with Stephen Smith to his house at Warpledon in Surrey,
where we had a large meeting.
Friends thereaway had been exceedingly plundered
about two months before on the priest's account;
for they took from Stephen Smith five kine (being all
he had) for about fifty shillings' tithes.
Thence we went to Kingston, and so to London, where I stayed not long;
for it was upon me from the Lord to go into Holland,
to visit Friends and to preach the gospel there, and in some parts of Germany.
Wherefore setting things in order for my journey as fast as I could,
I took leave of Friends at London;
and with several other Friends went down to Colchester,
in order to my passage for Holland.
Next day, being First-day, I was at the public meeting of Friends there,
which was very large and peaceable.
In the evening I had another large one, but not so public, at John Furly's house,
where I lodged.
The day following I was at the women's meeting there, which also was very large.
Thence next day we passed to Harwich, where Robert Duncan,
and several other Friends out of the country, came to see us;
and some from London came to us there, that intended to go over with me.
The packet in which we were to go not being ready, we went to the meeting in the town,
and a precious opportunity we had together; for the Lord,
according to his wonted goodness, by his overcoming, refreshing power,
opened many mouths to declare his everlasting truth, and to praise and glorify him.
