== Chapter VIII.

[.chapter-synopsis]
* 1677.
* George Fox sails for Holland, with several other Friends, and lands at Briel
* attends the Quarterly Meeting at Amsterdam
* writes an epistle to Friends against the spirit of separation
* writes to the Princess Elizabeth
* her answer
* a Monthly Meeting is established at Frederickstadt
* Friends are imprisoned and banished from Embden, and suffer greatly
* a Monthly Meeting settled at Harlingen
* a priest assents to the doctrine promulgated by George Fox
* he is questioned for it by his hearers
* George Fox writes an epistle to Friends respecting the seducing spirit
* he writes an epistle of encouragement to Friends under suffering at Dantzic
* and again to Friends respecting the spirit of separation
* spends considerable time at Amsterdam in writing on Truth`'s account
* a warning to the magistrates and people of Oldenburg
* an epistle concerning fasts, prayers, honour, persecution, true liberty, and the observance of days and times
* a warning to the magistrates, priests, and people of Hamburg
* to the ambassadors met to effect a treaty of peace in the city of Nimeguen
* completes his travels in Holland
* writes a book addressed to the Jews.

After the meeting at Harwich we returned to John Vandewall`'s, where I had lodged;
and when the boat was ready, taking leave of Friends, we that were bound for Holland,
went on board about nine in the evening, on the 25th of the 5th Month, 1677.

The Friends that went over with me, were William Penn, Robert Barclay,
George Keith and his wife, John Furly and his brother, William Tailcoat, George Watts,
and Isabel Yeomans, one of my wife`'s daughters.
About one in the morning we weighed anchor, having a fair brisk wind,
which by next morning brought us within sight of Holland.
But that day proving very clear and calm we got forward little,
till about four in the afternoon, when a fresh gale arose,
which carried us within a league of land.
Then being becalmed again, we cast anchor for that night,
it being between the hours of nine and ten in the evening:
but William Penn and Robert Barclay,
understanding that Benjamin Furly was come from Rotterdam to the Briel to meet us,
got two of the boatmen to let down a small boat that belonged to the packet,
and row them to shore; but before they could reach it the gates were shut;
and there being no house without the gates, they lay in a fisherman`'s boat all night.
As soon as the gates were opened in the morning, they went in, and found Benjamin Furly,
with other Friends of Rotterdam, that were come thither to receive us;
and they sent a boat, with three young men in it, that lived with Benjamin Furly,
who brought us to the Briel, where the Friends received us with great gladness.

We stayed about two hours to refresh ourselves, and then took boat,
with the Holland Friends, for Rotterdam, where we arrived about eleven that day,
the 28th of the Month.
I was very well this voyage, but some of the Friends were sea-sick.
A fine passage we had, and all came safe and well to land;
blessed and praised be the name of the Lord forever!

Next day, being First-day, we had two meetings at Benjamin Furly`'s,
where many of the town`'s-people and some officers came in, and all were civil.
Benjamin Furly or John Claus, a Friend of Amsterdam, interpreted,
when any Friend declared.
I spent the next day in visiting Friends there.
The day following, William Penn and I, with other Friends,
went towards Amsterdam with some Friends of that city,
who came to Rotterdam to conduct us thither.
We took boat in the afternoon, and, passing by Overkirk, came to Delft,
through which we walked on foot; and then took boat again to Leyden,
where we lodged that night at an inn.
This is six Dutch miles from Rotterdam, which are eighteen English miles,
and five hours`' sail or travelling;
for our boat was drawn by a horse that went on the shore.
Next day taking boat again, we went to Haarlem, fourteen miles from Leyden,
where we had appointed a meeting, which proved very large;
for many of the town`'s-people came in, and two of their preachers.
The Lord gave us a blessed opportunity, not only with respect to Friends,
but to other sober people, and the meeting ended peaceably and well.
After it we passed to Amsterdam,
accompanied by several Friends of that city and of Alkmaar.

Next day was the quarterly meeting at Amsterdam,
to which came Friends from Haarlem and Rotterdam, and with them those of our company,
whom we had left at Rotterdam, viz.: Robert Barclay, George Keith and his wife, etc.
The meeting was at Gertrude Dirick Nieson`'s house.
A very large and serviceable one it was;
for both William Penn and I were drawn to open
many things concerning the order of the gospel,
and to show the benefit and service of yearly, quarterly,
and monthly meetings of men and women.
We had another meeting at Gertrude`'s the next day, more public, and very large,
at which were professors of several sorts,
unto whom the way of life and salvation was largely and livingly opened;
which they hearkened very attentively to, none making any objection to what was declared.
In the afternoon we had another meeting in the same place, but less, and more private.
The day following we had a meeting of Friends only,
wherein by joint agreement were settled several meetings; to wit, monthly, quarterly,
and a yearly meeting,
to be held at Amsterdam for Friends in all the United Provinces of Holland,
and in Embden, the Palatinate, Hamburg, Frederickstadt, Dantzic,
and other places in and about Germany; which Friends were glad of,
and it has been of great service to truth.

Next day an exercise came upon me concerning that deceitful spirit,
which wrought in some to make divisions in the church;
and the care of the churches being upon me,
I was moved to write a few lines to warn Friends of it, as follows:--

"`All Friends, keep over that spirit of separation and division, in the peaceable truth,
and in the Seed of life, which will wear it all out and outlast it.
For the Lamb will have the victory over all the spirits of strife,
as it hath had since the beginning; and they will wither, as others have done;
but all that keep in the Seed, which is always green, shall never wither;
as Friends have been to this day kept.
And if any have backslidden, and thrown off the cross, are grown loose and full,
and are gone into strife and contention with their earthly spirits,
and therein plead for liberty, this spirit taketh with loose, earthly spirits,
and cries imposition to such as admonish them to come to the life, light, Spirit,
and power of God, that they may be alive, and may live again with the living.
Upon this admonition, their spirits rise into contention, strife, and separation,
turning against the living, in their loose, earthly spirits,
which would have the name of truth, but are not in the nature of it,
but are for eternal judgment of the living Seed.
This is it which doth deceive; but it is judged by that which doth undeceive and save.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam in Holland, the 5th of the 6th Month, 1677.

This being First-day, we had a very large meeting again,
there coming to it a great concourse of people of different opinions, as Baptists,
Seekers, Socinians, Brownists, and some of the collegians.
Robert Barclay, George Keith, William Penn, and I,
declared the everlasting truth among them; opening the state of man in the fall,
and showing by what way man and woman may come into the restoration by Christ Jesus.
Indeed, the mystery of iniquity, and the mystery of godliness,
were very plainly laid open; and the meeting ended quietly and well.

The day following, George Keith, Robert Barclay, and William Penn,
leaving me and some other Friends at Amsterdam, set forward towards Germany;
where they travelled many hundred miles, and had good service for the Lord;
Benjamin Furly going with them and interpreting.

That day and the next I stayed at Amsterdam, visiting Friends,
and assisting them in some business concerning their meetings.
Three Baptists came to discourse with me, to whom I opened things to their satisfaction,
and they parted from me in kindness.
I wrote a letter also to the Princess Elizabeth, which Isabel Yeomans delivered to her,
when George Keith`'s wife and she went to visit her:--

[.salutation]
"`Princess Elizabeth,

"`I have heard of thy tenderness towards the Lord and his holy truth,
by some Friends that have visited thee, and also by some of thy letters,
which I have seen:
it is indeed a great thing for a person of thy quality to have
such a tender mind after the Lord and his precious truth;
seeing so many are swallowed up with voluptuousness, and the pleasures of this world;
yet all make an outward profession of God and Christ one way or other,
but without any deep, inward sense and feeling of him.
For it is not many mighty, nor wise of the world,
that can become fools for Christ`'s sake,
or can become low in the humility of Christ Jesus from their mighty state,
through which they might receive a mightier estate,
and a mightier kingdom through the inward Holy Spirit--the divine light and power of God;
and a mightier wisdom which is from above, pure and peaceable.
This wisdom is above that which is below; that is earthly, sensual, and devilish,
by which men destroy one another, yea, about their religions, ways, worships,
and churches; but this they have not from God nor Christ.
The wisdom which is from above, by which all things were made and created,
which the holy fear of God in the heart is the beginning of, keeps the heart clean:
and by this wisdom are all God`'s children to be ordered,
and with it to order all things to God`'s glory.
This is the wisdom that is justified of her children.
In this fear of God and this wisdom, my desire is,
that thou mayest be preserved to God`'s glory.
For the Lord is come to teach his people himself, and to set up his ensign,
that the nations may flow unto it.
There hath been an apostaoy since the apostles`' days, from the divine light of Christ,
which should have given them '`the light of the knowledge of the glory of God,
in the face of Christ Jesus;`' and from the Holy Spirit,
which would have led them into all truth;
and therefore have people set up so many leaders without them, to give them knowledge;
and also from the holy and precious faith,
which Jesus Christ is the author and finisher of; which purifies the heart,
and gives victory over that which separates from God;
through which faith they have access to God, and in which they please God;
the mystery of which is held in a pure conscience.
And also from the gospel which was preached in the
apostles`' days (which gospel is the power of God),
which brings life and immortality to light in man and woman,
by which people should have seen over the devil that has darkened them;
which gospel will preserve all them that receive it, in life and immortality.
For the eyes of people have been after men, and not after the Lord,
who writes his law in the hearts, and puts it into the minds,
of all the children of the new covenant of light, life, and grace,
through which they all come to know the Lord, from the least to the greatest;
so that the knowledge of the Lord may cover the earth, as the waters do the sea.
This work of the Lord is beginning again, as it was in the apostles`' days;
people shall come to receive an unction in them again from the Holy One,
by which they shall know all things, and shall not need any man to teach them,
but as the anointing doth teach them; and also to know,
what the righteousness of faith speaks, the Word nigh in the heart and mouth,
to obey it and to do it.
This was the Word of faith the apostles preached;
which is now received and preached again,
and which it is the duty of all true Christians to receive.
So now people are coming out of the apostasy to the light of Christ and his Spirit,
and to receive faith from him, and not from men; to receive the gospel from him,
their unction from him, the Word; and as they receive him, they declare him freely,
as his command was to his disciples, and is still to the learners and receivers of him.
For the Lord God, in his Son Jesus Christ, is come to teach his people,
and to bring them from all the world`'s ways to Christ, the way, the truth, and the life,
who is the way to the Father; and from all the world`'s teachers and speakers,
to him the Speaker and Teacher, as Heb. 1:1; and from all the world`'s worshippers,
to worship God in the Spirit and in the truth,
which worship Christ set up above sixteen hundred years ago,
when he put down the Jews`' worship at the temple at Jerusalem,
and the worship at the mountain where Jacob`'s well was;
to bring people from all the world`'s religions,
which they have made since the apostles`' days,
to the religion that was set up by Christ and his apostles,
which is pure and undefiled before God, and keeps from the spots of the world;
to bring them out of all the world`'s churches and fellowships,
made and set up since the apostles`' days, to the church that is in God,
the Father of our Lord Jesus Christ; Thess. 1:1,
and to bring to the unity and fellowship in the Holy Spirit, that doth mortify,
circumcise, and baptize, to plunge down sin and corruption,
that has got up in man and woman by transgression.
In this Holy Spirit there is a holy fellowship and unity: yea,
it is the bond of the Prince of princes, and King of kings, and Lord of lords`' peace;
which heavenly peace all true Christians are to maintain with spiritual weapons,
not with carnal.

"`And now, my friend,
the holy men of God wrote the Scriptures as they were moved by the Holy Ghost;
and all Christendom are on heaps about those Scriptures,
because they are not led by the same Holy Ghost
as those were that gave forth the Scriptures;
which Holy Ghost they must come to in themselves, and be led by,
if they come into all the truth of them, and to have the comfort of God, of Christ,
and of them.
For none can call Jesus Lord, but by the Holy Ghost;
and all that call Christ Lord without the Holy Ghost, take his name in vain.
Likewise all that name his name are to depart from iniquity;
then they name his name with reverence, in truth and righteousness.
O therefore, feel the grace and truth in thy heart, that is come by Jesus Christ,
that will teach thee how to live, and what to deny.
It will establish thy heart, season thy words, and bring thy salvation;
it will be a teacher unto thee at all times.
By it thou mayest receive Christ from whom it comes; and as many as receive him,
to them he gives power, not only to stand against sin and evil,
but to become the sons of God; if sons, then heirs of a life, a world, and kingdom,
without end, and of the eternal riches and treasures thereof.
So in haste, with my love in the Lord Jesus Christ, who tasted death for every man,
and bruises the serpent`'s head, who is between man and God,
that through Christ man may come to God again, and praise him through Jesus Christ,
the Amen;
who is the spiritual and heavenly rock and foundation for all God`'s people to build upon,
to the praise and glory of God, who is over all, blessed forevermore.`"

[.signed-section-signature]
George Fox.

[.signed-section-context-close]
Amsterdam, the 7th of the 6th Month, 1677.

"`__Postscript.--__The bearer hereof is a daughter-in-law of mine,
that comes with Gertrude Dirick Nieson and George Keith`'s wife, to visit thee.`"

[.signed-section-signature]
G+++.+++ F.

[.blurb]
=== The Princess Elizabeth`'s Answer.

[.salutation]
"`Dear Friend,

"`I cannot but have a tender love to those that love the Lord Jesus Christ,
and to whom it is given, not only to believe in him, but also to suffer for him;
therefore your letter and your friends`' visit have been both very welcome to me.
I shall follow their and your counsel as far as God will afford me light and unction;
remaining still your loving friend,

[.signed-section-signature]
"`Elizabeth.`"^
footnote:[Elizabeth, Princess of the Rhine, was the eldest daughter of Frederick V.,
Elector Palatine, and king of Bohemia--her mother being
a daughter of king James I. of England.
This excellent princess is spoken of as a woman
of great amiability and religious character.
She possessed only a small territory; but she governed with great judgment,
and attention to the happiness of her subjects.
She made it a rule to hear, one day in the week,
all such causes as were brought before her.
On these occasions, her wisdom, justice, and moderation were very conspicuous.
She frequently remitted forfeitures, in cases where the parties were poor,
or in any respect worthy of favour.
It was remarkable that she often introduced religious considerations,
as motives to persuade the contending parties to harmony and peace.
She was greatly beloved and respected by her subjects;
and also by many persons of learning and virtue not resident in her dominions;
for she patronised men of this character,
whatever their country or their religious profession.
{footnote-paragraph-split}
The respect in which this exemplary Christian held Friends and their principles,
was unreservedly expressed in her letters to
individuals connected with the English court;
and her good offices were more than once exerted to preserve
this persecuted people from the penalties of those laws which
interdicted the exercise of public worship in conventicles,
as all meetinghouses were then denominated.
William Penn and Robert Barclay paid her two visits.
She received them with great openness, and was much affected by the interview which,
on the second visit, took place, as is related by William Penn.
They went from Amsterdam to Herwerden,
the residence of the Princess and of her intimate acquaintance, Anna Maria,
Countess de Hornes, who dwelt much in her house, and was, as well as herself,
a woman seeking after the best things,
and a favourer of such (says Penn) as separate themselves from the world for
the sake of righteousness.
{footnote-paragraph-split}
The visitors were welcomed by the Princess and her friend the day after their arrival,
and were invited to dine with them.
They held a religious meeting together,
which was so satisfactory that the Princess desired another might be appointed,
at which several persons were present.
William Penn thus speaks of it:--"`The eternal word showed itself as a hammer this day;
yea, sharper than a two-edged sword, dividing asunder between the soul and the spirit,
between the joints and the marrow.
Let my right hand forget its cunning, and my tongue cleave to the roof of my mouth,
when I shall forget the lovingkindness of the Lord, and the sure mercies of our God,
to us that day.`"
The following day they paid two visits at this little court; and the day after,
which was the first of the week, they held a meeting there,
appointed by the direction of the Princess,
which several others attended besides those of her household.
Of this meeting Penn says:
"`The quickening power and life of Jesus wrought and reached them; and virtue from him,
in whom dwelleth the Godhead bodily, went forth.`"
After this meeting, which was held late in the evening, the visitors took their leave,
but not before they had been witnesses of the tender disposition of mind of the Princess;
who, attempting to set forth her sense of the power and presence of God prevalent among them,
could not proceed, but turned herself to the window, and said,
"`My heart is full, I cannot speak to you.`"
Penn, on another occasion, says,
"`I cannot forget her last words when I took my leave of her:
'`Let me desire you to remember me, though I live at so great a distance,
and you should never see me more.
I thank you for this good time.
Be assured, though my condition subjects me to divers temptations,
yet my soul has strong desires after the best things.`'`"
{footnote-paragraph-split}
The Princess Elizabeth lived to the age of 60,
departing this life in 1680, as much lamented, as she had been beloved, by her people.]

[.signed-section-context-close]
Hertford, the 30th of August, 1677.

Next day John Claus and I took a boat and passed to Buyckslote, thence to Purmerent,
where having refreshed ourselves, we went by wagon to Alkmaar,
about thirty miles from Amsterdam.
We went to a Friend`'s house there, whose name was Willem Willems,
where I had a meeting that night.
I had another next day, which was larger; for several professors came,
and all was quiet and well.
After the meeting, I visited some Friends; and then, taking boat, passed to Hoorn,
which is counted the chief city in North Holland.
We lodged at an inn; and, taking wagon early next morning, passed to Enckhuysen,
where we took ship for Friesland; and landing in the afternoon at Workum,
took wagon and rode upon the high bank of the Friezen Seas,
till we met two Friends coming with a wagon to meet us;
with whom (discharging our wagon at Mackum, a village hard by) we went to Harlingen,
the chief seaport town in Friesland.
We went to Hessel Jacobs`', whither several Friends came to visit us that night.
Next day we visited the Friends of the place; and I wrote a paper,
"`To all them that persecute Friends for not observing their fast-day.`"

The day following being First-day, Friends had a meeting there, to which we went,
and many professors came to it.
I declared the everlasting gospel amongst them, John Claus interpreting.
They were all very civil, and heard attentively; and when it was done,
departed peaceably, without making any opposition.
After meeting I went to Hessel Jacobs`' again,
whither after a while came a Calvinist to ask me some questions,
which I answered to his satisfaction; and he departed friendly.
Soon after he was gone, a preacher of the collegians came to discourse with me,
who seemed well satisfied also, and we parted lovingly.
That evening I had another meeting with the Friends there, and next morning,
when we had taken our leave of them, we passed to Leeuwarden,
the chief city in Friesland, and lodged that night at a Friend`'s house there,
whose name was Sybrand Dowes.

Next morning early, taking boat, we passed to Dockum, and walking through the city,
took boat again to Strobus, which is the utmost part of Friesland.
There we baited at a commissary`'s house; and then taking boat again, passed to Groningen,
the chief city of the province of Groningland.
One of the magistrates of that city came with us from Leeuwarden,
with whom I had some discourse on the way, and he was very loving.
We walked nearly two miles through the city, and then took boat for Delfziel;
and passing in the evening through a town called Appingdalem,
where had been a great horse-fair that day;
there came many officers rushing into the boat, and being somewhat in drink,
they were very rude.
I spoke to them, exhorting them to "`fear the Lord, and beware of Solomon`'s vanities.`"
They were boisterous fellows; yet somewhat more civil afterwards.
We landed at Delfziel about ten at night,
having travelled about fifty English miles that day.
We went to an inn to lodge, and as we passed through the guards,
they examined John Claus, whether I was not a militia soldier;
and when he had told them I was not, they let us pass peaceably.

Delfziel stands on the river Embs, over which we passed next day to Embden,
a place where Friends had been cruelly persecuted,
and from which they had been often banished.
I went to an inn, where I dined with some men that understood English,
with whom I had a fine time, and they were loving.
Meanwhile John Claus went with his wife to her father`'s, in Embden; whither,
after I had dined, I went also, understanding the old man was desirous to see me.
In the afternoon John Claus and I walked through the city to the place where the wagon,
which he had hired, was to meet us; and while we waited for it,
the Friends that were in the city came to the house where we were,
and we had a little meeting.
When it was over, and the wagon came not, we sent to know the reason.
The master of it sent us word, that he durst not let it go;
for the bishop of Munster`'s soldiers were up in the country,
and he was afraid they would take away his horses.
So being disappointed of our passage, we returned to Jokn Claus`'s father-in-law`'s house,
where I left him, and went to my inn at night.

We took shipping next day, and passed about fifteen miles upon the river Embs,
to a market-town in East-Friesland, called Leer,
where lived a Friend that had been banished from Embden.
When we had visited him, we hired a wagon in that town, and passed to a garrisoned town,
called Strikehuysen, where the guards examined us; and then went on to Deieren, where,
hiring another wagon, we passed to another garrisoned town,
where we were very strictly examined.
Thence we passed to Apre, in Denmark, where we lodged that night.
In our travelling this day, we met the Earl of Oldenburg,
going to the treaty of peace at Lembachie.

Next day, we passed by wagon to Oldenburg, lately a great and famous place,
but then burnt down, and but few houses left standing in it.
At this place we hired another wagon, and went to Delmenhurst; where,
after we had been examined by the guards, we went to a burgher-master`'s to lodge,
whose house was an inn.
There being many people, I declared the way of truth to him and them,
warning them of the day of the Lord that was coming upon all evil-doers.

We passed next day by wagon to Bremen, a stately city in Germany; and thence,
after a double examination, we went to a water called Overdeland,
and there took boat to Fisherholder; where, finding many people together,
I declared the way of God to them, and exhorted them to fear the Lord.
There we took wagon again, and travelled in the bishop of Munster`'s country,
to Closierseven; and having no inclination to stay there, got fresh horses,
intending to travel all night.
We went a little way, but it quickly grew so dark, and rained so hard,
that we thought it best to turn back again; for our wagon being open,
we had no defence against the rain,
and our clothes were already wet with what had fallen for several days before.
So we went to an inn, and got a little fresh straw,
upon which we lay till about break of day; and then set out and travelled to Buxteiiuee.

The people in the bishop of Munster`'s country were very dark.
As we passed amongst them, I preached truth to them,
warning them of the great and notable day of the Lord; and exhorting them to soberness,
and to mind the good Spirit of God in themselves.

It was on a First-day that we went through Buxtehude;
and without the walls there was a great fair of sheep and geese that day.
We stayed a little to refresh ourselves, and went on as fast as we could to Hamburg,
partly by wagon, and partly by water.

We got to Hamburg in time enough to get a meeting there that evening;
and a good and glorious one it was.
There were at it, amongst others, a Baptist teacher and his wife,
and a great man of Sweden and his wife; and all was quiet, blessed be the Lord,
whose power was exalted over all.
Yet a dark, hard place this is, and the people are much shut up from truth.

At Hamburg was a woman that had spoken against me in John Perrot`'s time,
though she had never seen me till now.
She had been troubled for it ever since;
and now was glad of an opportunity to acknowledge her fault; which she very readily did,
and I as readily and freely forgave her.

We stayed that night at Hamburg,
encouraging and strengthening the Friends there in their testimony to the truth;
and betimes next morning set forward towards Frederickstadt,
two long days`' journey from Hamburg.
We went the first day to Elmshoorn, where we baited;
and then rode on through a garrison-town of the king of Denmark`'s;
and passing by the monument of the Earl of Rantzow, came to the city of Itzeho,
where we lodged that night.
I had some service in the evening among the people in the inn,
whom I exhorted to soberness, and to live in the fear of the Lord.
Next morning we travelled to Hoghenhorn,
where we dined at an inn with one of the council of Frederickstadt; to whom,
and to the rest of the people present, I declared the truth,
with which they seemed to be affected.
Then travelling on, we came to a river called Eyder,
where we took boat and so went to Frederickstadt, to William Paul`'s,
where several Friends came to us, for there is a pretty company of Friends in that city.
We had a fine refreshing meeting together that evening,
which made us forget our weariness; for we were indeed very weary,
having travelled hard two days, and being wet through our clothes,
having had much rain in our open wagons.
But the Lord made all easy and good to us; and we were well, and glad to see Friends;
blessed be his holy name forever!

This city is in the Duke of Holstein`'s country,
who would have banished Friends out of the city and country,
and sent to the magistrates of the city to do it; but they said,
they would lay down their offices rather than do it;
inasmuch as Friends came to that city to enjoy liberty of conscience.
Friends still enjoy their liberty there,
and truth and they are of good report amongst the people, both in city and country.

On First-day I had a meeting here, to which many people came, and some rough spirits;
but the power of the Lord bound them down, and the Seed of life was set over all.
While I was here I had a discourse with a Jew that was a Levite,
concerning the coming of the Messiah, and he was much confounded in what he said;
yet he carried himself lovingly, and invited me to his house.
I went, and there I discoursed with another Jew,
who showed me their Talmud and many other Jewish books; but they are very dark,
and do not understand their own prophets.

There was at this city a Baptist teacher, who had reproached and belied Friends;
wherefore John Claus went with two Friends of the town, to the house where he lodged,
and cleared truth and Friends from his reproaches;
and laid his lies and slanders upon his own head, to his shame.

Before we left this place I had another meeting with the Friends only,
wherein I laid before them the usefulness and benefit of a monthly meeting,
for looking after the poor, and taking care that marriages,
and all other things relating to the church, were performed in an orderly manner.
The thing answered the witness of God in their consciences,
so that they readily agreed to have monthly meetings thenceforward among themselves,
that both men and women might take care of the outward concerns of the church.

After this meeting, feeling my spirit clear of that place,
we took leave of Friends there, whom we left in good order,
and turned back again for Hamburg.
When we had travelled one day`'s journey, and were come to an inn at night to lodge,
I inquired whether there were any tender people in the town that feared God,
or that had a mind to discourse of the things of God?
The innkeeper told me there were few such in that town.
Next night we got to Hamburg; and having passed the guards, went to a Friend`'s house,
being very weary; for we had been up those two mornings before three,
and had travelled each day hard and late.
Here we met with John Hill, an English Friend, who had been travelling in Germany,
and being in a ship bound for Amsterdam, that waited for a wind,
he had lain sick on board about two weeks.
Hearing I was in the country, he left the ship and came hither to meet me,
and go along with me.

The day after we came to Hamburg we had a very good meeting, and very peaceable.
After it I had discourse with a Swede, an eminent man in his own country; who,
having been banished thence on the account of his religion, was come to Hamburg,
and was at the meeting I had there before.
When I had done with him,
I had another discourse with a Baptist concerning the sacraments, so called;
in both which I had good service, having opportunity thereby to open truth unto them.

Being clear of Hamburg, we took leave of Friends there, whom we left well;
and taking John Hill with us, passed by boat to a city in the Duke of Luneburg`'s country;
where, after we were examined by the guards, we were had to the main-guard,
and there examined more strictly; but after they found we were not soldiers,
they were civil, and let us pass.
In the afternoon we travelled by wagon, and the waters being much out,
by reason of heavy rains, when it drew towards night,
we hired a boy on the way to guide us through a great water we had to pass.
When we came to it, the water was so deep before we could come at the bridge,
that the waggoner had to wade, and I drove the wagon.
When we were come on the bridge, the horses broke part of it down,
and one of them fell into the water,
the wagon standing upon that part of the bridge which remained unbroken;
and it was the Lord`'s mercy to us that the wagon did not run into the brook.
When they had got the horse out, he lay a while as if dead;
but at length they got him up, put him to the wagon again, and laid the planks right;
and then, through the goodness of the Lord to us, we got safe over.

After this we came to another water, which finding to be very deep,
and it being in the night, we hired two men to help us through,
who put cords to the wagon to hold it by,
that the force of the water might not drive it from the way.
But when we came into it, the stream was so strong,
that it took one of the horses off his legs, and was carrying him down the stream.
I called to the waggoner to pluck him to him by his reins, which he did,
and the horse recovered his legs, and with much difficulty we got over the bridge,
and went to Borner-Haven, the town where the waggoner lived.
It was the last day of the 6th month that we escaped these dangers;
and it being about eleven at night when we came in here,
we got some fresh straw and lay upon it, till about four in the morning.
Then getting up, we set forward again towards Bremen, by wagon and boat.
On the way I had good opportunities to publish truth among the people,
especially at a market-town, where we stayed to change our passage;
where I declared the truth to the people, warning them of the day of the Lord,
that was coming upon all flesh; and exhorting them to righteousness, telling them,
"`that God was come to teach his people himself,`" and that they should turn to the Lord,
and hearken to the teachings of his Spirit in their own hearts.

At Bremen, after we were examined, we went to an inn,
and stayed till another wagon was provided to carry us further.
Though I felt the Lord`'s power was over the city,
and kept the wicked and unruly spirits down,
yet my spirit suffered much in this place for the people`'s sake.
When our wagon was ready, we left Bremen and travelled to Keby,
where we lodged at an inn, and early next morning set out for Oldenburg.
It was a lamentable sight to see so great and brave a city burnt down.
We went to an inn, and though it was First-day, the soldiers were drinking,
and playing at shovel-board; and at the few houses that were left, the shops were open,
and the people trading one with another.
I was moved to declare the truth among them, and warn them of the judgments of God;
and though they heard me quietly, and were civil,
yet I was burdened with their wickedness.
Many times in mornings, noons, and nights, at the inns and on the ways as I travelled,
I spoke to the people, preaching the truth to them, warning them of the day of the Lord,
and exhorting them to turn to the light and Spirit of God in themselves,
that thereby they might be led out of evil.

Next day, passing through many great waters, we came at night to Leee,
and the day following to Embden, where John Claus`'s wife`'s father lived; at whose house,
when we went into Germany, we left a young man sick, who travelled with me,
and used to write for me; whom now we found pretty well recovered.
John Claus went to his father-in-law`'s; John Hill and I to an inn, where we dined.
After dinner we went also to John Claus`'s father`'s,
and had a good meeting there in the evening.

The day following we took shipping at Embden, passed to Delfziel, and went to an inn,
where a Friend came to us that then lived there, having been often banished from Embden;
he was a goldsmith, and had a house and shop in Embden; and still as they banished him,
he went again.
Then they imprisoned him, and fed him with bread and water;
and at length took his goods from him, and banished him, his wife, and children,
leaving them neither place to come to, nor anything to subsist on.
We comforted and encouraged him in the Lord, exhorting him to be faithful,
and stand steadfast in the testimony committed to him.
When we had taken leave of him, we took boat, and passed the same day to Groningen,
where we met with Cornelins Andries,
a Friend that had also suffered much by imprisonment and banishment at Embden.
We went with him to his house, and next day had a good meeting in that city,
to which several professors came, who were very peaceable and attentive.
After meeting we passed by boat to Strobtts, and so to Dockum, where we lodged at an inn.
Taking boat again next morning we passed to Leeuwarden, the chief city of Friesland,
where I found my daughter Yeomans, who was come from Amsterdam to meet me.
That day we had a precious meeting at Sybrand Dowes`'s house.
After the meeting I had discourse with some that were at it,
who had been formerly convinced of truth, but were not come into obedience to it.
We stayed there that night; but John Hill left us, and went that day to Harlingen,
and so to Amsterdam.

Next day we passed down the river to the lake of Hemfen-Sarmer,
and thence by the lake Lugmer, and so to a town called Anderigo;
whence sailing through the lake Whispool, we came to Gardick within night.
We lodged at an inn; and next day, being First-day, we were at Friends`' meeting there,
which was very large, many of the town`'s-people coming in;
amongst whom I declared the truth, in the power of the Lord that was upon me,
which tendered the people, and they were very sober.
After it we stayed a little while to refresh ourselves, and then went to take boat again;
but the people observing us, gathered together at a bridge, which we were to pass;
and there I spoke unto them again, declaring the way of life and salvation;
and they were very attentive and civil.

We went back that evening to Leeuwarden, twenty-seven miles;
but before we could reach it, the gates were shut, and the bridges drawn up,
so that we could not get into the city, but lay in the boat all night.
Next morning, there having been a man killed in the city that night,
it was late before the gates were opened.
When we could get in, we went to a Friend`'s house, where we stayed a while;
then taking boat again, we passed through Franeker to Harlitngen, to Hessel Jacobs`'s,
where we found several Dutch Friends, who were come to be at the meeting there next day.
In the evening William Penn came to us from Amsterdam;
who having returned two or three days before out of Germany,
had been at a large meeting at Amsterdam on First-day; and after it,
understanding I was at Harlingen, he came thither to me.

The next day was the monthly meeting for the men and women, to which we went;
it was large and good.
And there it was agreed, that "`a meeting should be held there once a month,
both for the men and for the women, to take care of the outward concerns of the church.`"

In the afternoon we had a public meeting, to which came people of several sorts,
Socinians, Baptists, Lutherans, etc., amongst whom were a doctor of physic and a priest.
After I had declared the truth pretty largely to the people,
opening the happy state that man and woman were in,
whilst they kept under God`'s teaching, and abode in the Paradise of God;
and on the other hand,
the woe and misery that came upon them when they went from God`'s teaching,
hearkening to the Serpent`'s--when they transgressed God`'s command,
and were driven out of Paradise; and then came to set forth the way,
whereby man and woman might come into that happy state again; the priest, an ancient,
grave man, stood up, just as I had done speaking, and putting off his hat, said,
"`I pray God to prosper and confirm that doctrine, for it is truth,
and I have nothing against it.`"
He would willingly have stayed till the meeting ended, but having to preach that evening,
lie could not stay longer, the time for his own worship being come.
Wherefore when he had made confession to the truth, he hastened away,
that he might come again; and did come, it seems, to the meeting-place,
but the meeting was ended first.
After meeting we went to Hessel Jacobs`'s, where I had a meeting with Friends,
and the doctor of physic came thither to discourse with William Penn,
who had a good opportunity to open truth to him.
By this doctor the priest sent his love to me, wishing him to tell me,
that he had left preaching that evening half an hour sooner than he used to do,
that he might come to our meeting again, to hear more of that good doctrine.
I heard afterwards that his hearers questioned him, for what he had said in our meeting;
and that, he standing by his words,
they had complained of him for it to the other priests of the city,
who called him to account about it; but the result I could not learn.

Early next morning William Penn, taking John Claus with him,
passed from Harlingen for Leeuwarden, where he had appointed a meeting;
intending after that, to travel into some other parts of Germany,
to visit a tender people there.
I with those Friends that were with me, took ship the same day for Amsterdam,
where we arrived a little after midnight, but the gates being shut,
we lay on board till morning; then went to Gertrude Dirick Nieson`'s,
where many Friends came to see us, being glad of our safe return.
Next day, feeling a concern upon my mind,
with relation to those seducing spirits that made division among Friends,
and being sensible that they endeavoured to
insinuate themselves into the affectionate part,
I was moved to write a few lines to Friends concerning them, as follows:--

"`All these that set up themselves in the affections of the people, set up themselves,
and the affections of the people, and not Christ.
But Friends, your peaceable habitation in the truth, which is everlasting,
and changes not, will outlast all the habitations of those that are out of the truth,
be they ever so full of words.
So they that are so keen for J. S. and J. W. let them take them, and the separation;
and you, that have given your testimony against that spirit, stand in your testimony,
till they answer by condemnation.
Do not strive, nor make bargains with that which is out of the truth;
nor save that alive to be a sacrifice for God, which should be slain,
lest you lose your kingdom.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam, the 14th of the 7th Month, 1677.

On the First-day following, I was at Friends`' meeting at Amsterdam,
to which many people came, and were very civil and attentive,
hearing truth declared several hours.
John Roeloffs interpreted for me.

Before this time, several of the Friends that came over with me,
were returned to England, as Robert Barclay,^
footnote:[This being the last mention of Robert Barclay in these volumes,
the following brief particulars may interest the reader
who is not already acquainted with his history.
He was the son of Colonel David Barclay, descended from the Barclays of Mathers,
an ancient and honourable Scotch family, and of Katharine Gordon,
from the Gordons of the house of the Duke of Gordon.
He was born at Edinburgh in 1648, educated in France, and returned to Scotland in 1664.
His father having joined the despised Quakers, Robert Barclay,
though uninfluenced by him, soon followed his example,
and came forth a zealous witness for the truth, receiving a gift in the ministry,
in which he laboured to bring others to God.
He was much exercised in controversy, from the many contradictions that fell upon truth,
and upon him for its sake.
He published several works in defence of the principles he had espoused,
which he believed to be those of the New Testament,
as promulgated by Christ and his apostles.
His chief work was his _Apology for the True Christian Divinity,_
which has gone through many editions,
and remains incontrovertible.
{footnote-paragraph-split}
In common with the early Friends,
Robert Barclay suffered imprisonments and ill usage,
which he bore with exemplary patience.
He travelled extensively to spread the gospel of Christ,
for he loved the truth above all the world; not ashamed of it before men,
but bold and able in maintaining it, sound in judgment, strong in argument,
of a pleasant disposition, yet solid and exemplary in his conversation.
He was a learned man, a good Christian, an able minister, a tender and careful father,
and a good and kind neighbour and friend.
His last illness was short.
James Dickenson of Cumberland, in his journey in Scotland,
visiting him when on his deathbed, as he sat by him,
the Lord`'s power and presence bowed their hearts together,
and Robert Barclay was sweetly melted in the sense of God`'s love, and, with tears,
expressed his love to all faithful brethren in England;
and adding a message of love to dear George Fox, he said, "`God is good still,
and though I am under great weight of sickness and weakness as to my body,
yet my peace flows, and this I know, whatever exercises may be permitted to come upon me,
it shall tend to God`'s glory and my salvation,
and in that I rest.`"
{footnote-paragraph-split}
He died at his own house, at Ury,
in Scotland, in 1690, aged forty-two, leaving behind him four sons and three daughters.]
George Keith`'s wife, and others; and now my daughter Yeomans went back also;
so that I was left alone at Amsterdam.
While I was there,
it came upon me to visit my suffering Friends at Dantzic with a few lines,
to encourage and strengthen them in their sufferings, as follows:--

[.salutation]
"`Dear Friends,

"`To whom is my love in the Lord`'s truth, that is over all,
and by which all God`'s people are made free men and women,
being thereby set free from him that is out of the truth; that walking in the truth,
they may answer the witness of God in all people; which truth all must come to,
if they be made free.
Therefore be faithful unto what the Lord makes known unto you.
I am glad the Lord hath witnesses in that city, to stand for his glory and name,
and for Christ Jesus, the great Prophet, whom God hath raised up,
who is to be heard in all things; so that ye need none of the prophets,
which men have raised up.
Therefore, stand faithful to Christ Jesus, your Shepherd, that he may feed you;
hear his voice, and follow him, who laid down his life for you:
but follow none of the shepherds and hirelings, that are made by men,
though they be angry, because ye will not follow them to their dry and barren mountains;
who have been, and are, the thieves, persecutors, and robbers, that climb up another way,
than by Christ.
Set up Christ to be your Counsellor and Leader, and then,
ye will have no need of any of the counsellors and leaders of the world;
for Christ is sufficient, whom God has given you.
Set up Christ Jesus to be your Bishop and Overseer, who is sufficient to oversee you,
that ye go not astray from God;
by which ye may see over all the hireling-overseers made by men, who keep the people,
that they do not go astray from the rudiments and formalities,
fashions and customs of the world; which hath been and is their work.
I am glad ye are come to own Christ Jesus, your High Priest, who is holy, harmless,
separate from sinners, and made higher than the heavens,
as the church and the apostle owned him in their days, Heb.
vii., who is the High-Priest over the household of faith;
which faith Jesus Christ is the author and finisher of:
and this do all the children of the new covenant witness,
who walk in the new and living way.
Therefore my desire is, that ye all may be steadfast, whether in bonds or out,
in the faith of Christ Jesus, which is the gift of God;
by which faith all the valiants overcame the devil and all their enemies;
in which faith they had victory and access to God; and in that was their unity:
which mystery of faith is held in a pure conscience, hidden from the world.
I do believe,
that your imprisonments and sufferings in that place will be for good in the end,
as it hath been in other places, ye standing faithful to the Lord, who is all-sufficient.
For your sufferings and trials will try their teachers and religions,
churches and worships, and make manifest what birth they are of;
even that which persecutes him that is born of the Spirit: for ye know,
that there is no salvation by any other name under the whole heaven,
than by the name of Jesus; therefore it is time to leave them,
when there is no salvation by or in any of them.

"`Now, Friends,
I desire that you would take a list of the names
of all those that belong to the king of Poland,
and where they live, and how ye may send books or epistles to them,
and keep a correspondence with them:
also the name of the bishop or cardinal that I heard was with you; and, if ye can,
get any of them that belong to the king to come and visit the prisoners,
that they may inform the king of their cruel sufferings.
Also I desire you to get as many books of mine as you can dispose of,
that set forth your sufferings, and the cruelty of the magistrates of Dantzic;
and give them to the king, his council, attendants, and bishops.
And some of the women may speak to the queen, if they can,
that she may signify to the king their cruel sufferings;
and especially some of the sufferers`' wives, if there be any of a capacity to do it.
You may likewise give his attendants any other Friends`' books; what books ye lack,
send for to Amsterdam, where ye may be furnished with them,
to answer every tender desirer, and inquiring mind after the Lord.
So let all your minds be bended with the Lord`'s power, to spread his truth abroad;
and where ye hear of any,
or have any correspondence in outward trading with any sober people, far or near,
send them books, that their understandings may be opened after the Lord.
The Lord God Almighty preserve you!
To his protection, in his eternal power, do I commend you all, in bonds or at liberty,
with my love to you in the everlasting Seed of God, Christ Jesus,
who bruises the head of the serpent, that makes you suffer.
Christ is over him, and will be when he is gone; who is First and Last, over all,
from everlasting to everlasting, in whom ye have life, knowledge, wisdom, and salvation;
and through him live to the praise and glory of God, who is blessed forevermore.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam, the 18th of the 7th Mouth, 1677, English style.

Next day, the fourth of the week and 19th of the month,
I had a large meeting at Amsterdam, many professors being at it;
and truth was largely opened to them, in the demonstration of the heavenly power.
The day following I went by boat from Amsterdam, many Friends going with me,
to Landsmeer in Waterland (a town in which, they say, there are above a hundred bridges),
where I had a very good meeting, to which several professors came.
After it I returned with Friends to Amsterdam,
where I stayed till the First-day following, and went to their meeting, which was large.
Many professors of several sorts were at it,
and heard the truth declared with great attention.

I tarried there next day,
and in the night following had a great exercise
upon my spirit concerning that loose spirit,
that was run out into strife and contention among Friends,
and had drawn some after it into division and separation; the way, work,
and end whereof the Lord opened to me: wherefore feeling the motion of life upon me,
I got up in the morning and wrote the following epistle to Friends:--

[.salutation]
"`My Dear Friends,

"`Keep your first love in the truth, power, and Seed of life in Christ Jesus;
for this last night, as I was lying in my bed at Amsterdam,
I had a great travail in the holy Seed of life and peace,
and my spirit was troubled with that spirit of strife and separation.
I saw it was a destroying spirit, and did seek not only to get over the Seed,
but to destroy it,
and to eat out the minds of the people from it by strife and contention; and,
under pretence of standing for the ancient truth, its work is to root it out,
and destroy the appearance of it, to set up itself.
It is a creeping spirit, seeking whom it can get into;
and what it cannot do itself it stirreth up others to do,
and setteth their spirits afloat, with the dark wisdom to destroy the simple.
This spirit is managed by the prince of the air,
and leadeth some to do things which they would have been ashamed to have done as men,
which doth unman them;
and they would not have suffered them if they had kept to the tender principle of God,
which leadeth to peace.
It is a despising, backbiting, secret-whispering spirit, a sower of dissension,
and a taker of advantage of all prejudiced spirits,
that are disobedient to their first principle, and love of truth,
and begetteth into hatred; so it begetteth all into that spirit,
whose work is to destroy both the good within, and the good order without.
Nay, it would, if it could, destroy the government of Christ,
and the order of the gospel, to set up its own will and spirit, which is not of God; and,
under pretence of crying down man, is setting up man,
and gathering into a separation of disobedient men, who float above their conditions.
This spirit, which neither liveth in the truth nor its order, but opposeth them that do,
I cannot express it, as I see it and its work, whose end will be accordingly.
Therefore, Friends, I am to warn you all, that have not lost your simplicity,
not to touch it, nor to have any unity with it, lest you be defiled,
and lose your eternal estate and everlasting portion; and that your inward man,
which is after God, may be preserved, and Christ may reign in all your hearts.
It will be very hard for those that are joined with them,
ever to come down to truth in themselves, to see their own conditions,
and to have that spirit of strife and contention
(which eateth as a canker) brought down in them;
which is carnal, and slayeth the tender babe, which was once begotten in themselves.
The Philistine is got up in them, that stoppeth the wells and springs,
maketh a great bustle, and is crying up men, and pleading for them, instead of Christ.
So, Friends, strive not with them, but let those take them that cry them up.
Keep you to the Lord Jesus Christ with his light, that cometh from him,
that he may be your Lord; and ye in him may be all in unity, in one light, life, power,
and dominion, in Christ, your head.
The God of peace and power preserve you all in Christ Jesus, your Saviour;
and out of and from that mischievous spirit,
which is idle and slothful as to the work of the power, and Spirit,
and light of God and Christ.
Its very act worketh strife and disturbance against the peace of the church of Christ.
It thinks, in its willfulness, stubbornness, and unruliness, to set up itself,
and in that to have peace; but destruction will be the end of it,
and it is sealed for the fire and eternal judgment.
Therefore, let Christ, the Seed, be the head and crown of every one of you,
that nothing may be between you and the Lord God.
Be not deceived with vain, feigned, or rough words; for Satan is transforming himself,
as an angel of light, to deceive; but God`'s foundation standeth sure,
and God knoweth who are his, and will preserve them upon the rock and foundation of life,
in his peaceable truth and habitation, that in the same they may grow.
Keep out of strife and contention with it,
after ye have borne your testimony in the Lord`'s power and truth against it,
then keep in the truth; for it hath a life in scribbling, strife, and jangling,
because it would enlarge itself, and bring others into its misery with the airy power,
and would get power over the good, disjoin people from it,
and so commit rapes upon the simplicity by its subtlety.
But I do believe the Lord will defend his people,
though he may try them and exercise them with this spirit for a time,
as he hath done in days past, in other vessels it hath made use of,
as it doth of these now; who have a more seeming fair outside, but foul, rough,
and rugged enough within, against the Seed of Christ,
as ever were the Pharisees to destroy it.
They, under a pretence of preaching Christ, are destroyers and crucifiers of him,
and killers of the just, not only in themselves, but are endeavouring,
with all their might, to destroy it in others, where it is born.
Pharaoh and Herod slay the young Jews in the Spirit, as the old did;
I feel it worrying them.
That is got up to be king which knew not suffering Joseph.
But God will plague him, and the Seed will have more rest,
and be better entertained in Egypt, than under Herod,
into whom old Pharaoh`'s spirit is entered.
He that hath an ear to hear, let him hear; and an eye to see, let him see,
how this spirit hath transformed in all ages against the just and righteous; but mark,
what hath been its end?
The Seed reigneth; glory to the Lord God over all forever!
His truth spreadeth, and Friends here are in unity and peace, and of good report,
answering the good, or that of God in people.
My desires are, that all God`'s people may do the same in all places,
that the Lord may be glorified in their bringing
forth much fruit that is heavenly and spiritual.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam, the 25th of the 7th Month, 1677.

After I had given forth the foregoing epistle,
whereby my spirit was in some measure eased of the weight that lay upon it,
I went in the afternoon to the monthly meeting of Friends at Amsterdam,
where the Lord was present with us, and refreshed our spirits together in himself.

I had thought to go next day to Haarlem; but a fast being appointed to be kept that day,
I was stopped in my spirit, and moved to stay at Friends`' meeting that day at Amsterdam.
We had a very large meeting, a great concourse of people coming to it,
and amongst them many great persons.
The Lord`'s power was over the meeting;
and in the openings thereof I was moved to declare to the people, "`that no man,
by all his wit and study, nor by reading history in his own will,
could declare or know the generation of Christ, who was not begotten by the will of man,
but by the will of God.`"
After I had largely opened this unto them,
"`I showed them the difference between the true fast and the false; manifesting,
that the professed Christians, Jews, and Turks, were out of the true fast,
and fasted for strife and debate,
being under the band and fists of iniquity and oppression,
wherewith they were smiting one another; but the pure hands were not lifted up to God.
And though they did all appear to men to fast,
and did hang down their heads for a day like a bulrush,
yet that was not the fast which God did accept;
but in that state all their bones were dry, and when they called upon the Lord,
he did not answer them, neither did their health grow;
for they kept their own fast and not the Lord`'s. I exhorted them to keep the Lord`'s fast,
which was to fast from sin and iniquity, from strife and debate,
from violence and oppression, and to abstain from every appearance of evil.`"
These things were opened to the astonishment of the fasters;
and the meeting ended peaceably and well.

I went to Haarlem the day following, having before appointed a meeting.
Peter Hendricks and Gertrude Dirick Nieson went with me; and a blessed meeting we had.
There were professors of several sorts, and a priest of the Lutherans,
who sat very attentive for several hours, while I declared the truth amongst them,
Gertrude interpreting.
When the meeting was done,
the priest said "`he had heard nothing but what was according to the Word of God;
and desired that the blessing of the Lord might rest upon us, and our assemblies.`"
Others also confessed to the truth, saying,
"`they had never heard things so plainly opened to their understandings before.`"

We stayed that night at Haarlem at a Friend`'s house, whose name was Dirick Klassen; and,
returning next day to Amsterdam, went to Gertrude`'s house; where we had not been long,
before a priest of great note, who had formerly belonged to the Emperor of Germany,
and with him another German priest came, desiring to have some conference with me.
I took the opportunity to declare the way of truth unto them,
opening unto them "`how they might come to know God and Christ,
and his law and gospel;`" and showing them that "`they could never know it by study,
nor by philosophy, but by divine revelation through the Spirit of God,
opening to them in the stillness of their minds.`"
The men were tender, and went away well satisfied.

On the First-day following I was at Friends`' meeting at Amsterdam; where,
amongst several sorts of professors that were present, was a doctor from Poland,
who for his religion was banished the place he lived in;
and being affected with the testimony of truth in the meeting,
he came afterwards to have some discourse with me;
and after we had been some time together, and I had opened things further to him,
he went away very tender and loving.

While I was at Amsterdam, I spent much of my time in writing books, papers,
or epistles on truth`'s behalf.
I wrote several epistles from Amsterdam to Friends in England and elsewhere,
on several occasions, as the Lord moved me by his Spirit thereunto.
I wrote also from thence, "`A Warning to the Inhabitants of the City of Oldenburg,
which was lately burnt down;`" also,
"`A Warning to the Inhabitants of the City of Hamburg,`" both of which were as follows

[.blurb]
=== A Warning to the Magistrates and People of the City of Oldenburg.

[.salutation]
"`Friends,

"`Have you not seen and felt the judgments of God upon your city,
the Lord sending lightning from heaven that destroyed and burnt it?
As I passed through your city on a First-day of the week, which you call your Sabbath,
I saw some drinking, and soldiers playing at shuffle-board,
and others with their shops open and trading,
when they should have been waiting upon God and worshipping him;
and your people were light and vain, without any sense of God`'s judgments or repentance.
O therefore repent, lest the all-seeing God, who sees all your actions and is over all,
bring swift judgment upon you in his wrath, fury, and indignation.
Repent, and lay aside all manner of evil and wickedness, ungodliness,
and unrighteousness; for the day of the Lord will come upon all that do evil,
all the workers of iniquity.
This mighty day of the Lord will find them all out, and will burn as an oven,
and burn up all the proud and wicked, and neither leave them root nor branch.
Therefore, all ye magistrates, priests, and people,
search in yourselves to find out the cause, and what evil you have committed,
that has brought the wrath, vengeance, and judgment of God upon you and your city,
in burning it.
All return, and come to the light of Christ in your hearts, and to God`'s Spirit,
and to the grace and truth in your hearts, that comes by Jesus Christ;
that with it ye may search your hearts.
Do not grieve, nor vex, nor quench God`'s good Spirit in your hearts,
and walk not despitefully against the Spirit of grace, nor turn from it into wantonness;
and yet make a profession of God and Christ in words, when your hearts are afar off,
living in pleasures and wantonly upon the earth, sporting yourselves, killing the just,
crucifying to yourselves Christ afresh, and putting him to open shame;
and so dishonouring God, and Christ, and Christianity,
and making a profession and a trade of the Scriptures, keeping people always learning,
that they maybe always paying.

"`Cease from man, whose breath is in his nostrils, and look unto the Lord,
all ye ends of the earth, and be saved; for the Lord God of heaven, and earth is come,
to teach his people himself by his light, Spirit, grace, and truth,
and to bring them off all the world`'s teachers.
God hath raised up Christ Jesus, his Prophet, whom people should hear; and saith,
'`This is my beloved Son, hear ye Him,`' and Christ saith, '`Learn of me, I am the way,
the truth, and the life; and no man comes to the Father, but by me.`'
There is no salvation by any other name under the whole heaven than by the name of Jesus,
who saith, '`I am the good Shepherd, and have laid down my life for my sheep;
and my sheep hear my voice and follow me, and will not follow the hireling;
for Christ feeds them in the pastures of life, that will never wither.
God hath anointed Christ Jesus to preach, if you will hear him;
and God hath given Christ for a Counsellor and a Leader,
if you will be led and counselled by him;
and God hath given Christ for a Bishop to oversee you, and a King to rule you,
if you will be overseen and ruled by him.
You that will not have Christ to rule over you, who never sinned,
nor was guile found in his mouth,
you may read his sentence in the New Testament upon such.
Is not Christ a sufficient teacher, whose blood was shed for you,
and who tasted death for every man?
Doth not Christ say to his ministers, '`Freely ye have received, freely give?`'
And the apostle saith, '`We covet no man`'s gold, silver, or apparel.`'
They laboured with their hands, and kept the gospel without charge.
Have they that are called ministers amongst you done the same,
and kept this command of Christ Jesus?
Let them be examined and examine themselves.
Have you not trimmed your outsides?
but look within with the light and Spirit of Christ Jesus,
and see if your insides be not black and foul.
For Christ Jesus, who doth enlighten every man that cometh into the world,
with the life in himself, saith, '`Believe in the light,
that ye may become children of the light.`'
With the light ye may see all the evil and ungodly deeds that ye have committed;
all your ungodly words you have spoken; and all your ungodly thoughts ye think;
that ye may turn from them to Christ, from whom the light comes;
who is your Saviour and Redeemer, who hath given you a light to see your sin,
and that you are dead in Adam; that with the same light you may see Christ,
the quickening Spirit, who makes you alive to God, and saves you from your sin.
But if you hate the light, which is the life in Christ, the Prince of Life,
and love the darkness and the prince of darkness
more than the light or the life in Christ,
because it will reprove you; Christ tells you,
'`This light will be your condemnation,`' John 3.

"`Therefore be warned now in your day, and while you have time, turn to the Lord.
Do not quench the Spirit of the Father, by which he draws to his Son;
nor hate the light of Christ; for if you do, you hate the life in Christ,
and so remain under condemnation from God and Christ with the light,
who now speaks to his people by his Son, as he did in the apostles`' days; the same God,
that was the speaker by the prophets to the fathers,
and speaker to Adam and Eve in Paradise; and happy had Adam and Eve, and the Jews,
and all Christians been, if they had kept to this speaker, and not followed the serpent,
that false speaker, and his instruments.
And now God is the true speaker by his Son, who bruises the head of the serpent,
the false teacher, who is the head of all false ways, false prophets, false churches,
and false religions and worships.
So God in Christ is bringing people to the pure and undefiled religion,
that will keep them from the spots of the world, into the new and living way,
Christ Jesus; and to the church in God, which Christ is the head of,
as he was in the apostles`' days; and to worship God in the Spirit and in truth,
which worship Christ set up above sixteen hundred years since.
Therefore must all people come to the grace and Spirit of truth in their own hearts,
to know the God of truth, who is a Spirit; and in the Spirit and truth to worship, serve,
honour, and glorify the living God, who is over all, and worthy of all,
blessed forevermore. Amen.

"`Ye magistrates and officers, read this in all your assemblies,
and cause all your priests to read it in their churches; that they and you,
and all people may hear and fear the God of heaven,
as you will answer it at the great and terrible day of judgment,
and vengeance of the Lord God Almighty.
This is in love to your souls, and for your temporal and eternal good.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam, the 19th of the 7th Month, 1677

[.blurb]
=== "`A Warning to the Magistrates, Priests, and People, of the City of Hamburg, to humble themselves before the Lord, and not be high-minded.

[.salutation]
"`Friends,

"`You have painted and garnished the inside of your outward houses and high places;
but look within your hearts with the light of Christ,
which he hath enlightened you and every man that cometh into the world withal,
and with it you may see how foul your hearts and insides are with sin and evil,
which Christ tells you ye should make clean;
who told the Pharisees how they '`painted the sepulchres of the righteous,`'
and they themselves were full of rottenness and corruption.
Therefore look into yourselves, and your own hearts, what you are full of.
To paint the sepulchres of the righteous apostles,
and make a trade and a profession of their words, without the same Holy Ghost, and power,
and light, and truth which they were in, will not stand the day of God`'s vengeance.
Therefore repent while you have time, turn to the Lord with your whole hearts,
and do not think yourselves secure, without his immediate, almighty protection.
For not all your works, nor all your own strength, and power, and defence,
can protect you; it is not for you to look at them, and think yourselves secure,
to sit down in your security, and in it let your hearts be merry, and at rest and ease.
But when the Lord brings a scourge upon you, that you are filled with terrors and fears,
remember you were warned, that you were set down, but not in the true rest.
Then all your own strength and force will stand you in no stead;
and you will acknowledge that it must be God that must protect you.
Therefore take warning; for your priests and people are too high,
and are swallowed up too much in this world.
The vanities of it carry your minds away from God,
and your care is more for the world than for God,
and more after the riches of this world,
than after the riches of the world that has no end.
Know you not, that all your heaps of outward treasure must have an end,
and that you must leave them all behind you?
Therefore I am to warn and advise you, both high and low, priests and people,
to come to the grace, light, and truth, that comes by Jesus Christ;
to the manifestation of the good Spirit of God, which is given to you to profit withal;
that with this grace, and truth, light, and Spirit of Christ,
you may turn to Christ Jesus, from whence it comes, who saith,
'`Learn of me;`' and God saith, '`This is my beloved Son, hear ye Him.`'
So all the children of the new covenant, that walk in the new and living way,
hear Christ their Prophet, that God has raised up,
and anointed to be their Teacher and Priest.
So now, God doth speak to his people by his Son, as he did in the apostles`' days.
The Lord is come to teach his people himself by his grace, light, truth, and Spirit,
and to bring them off all the world`'s teachers
that are made by men since the apostles`' days;
who have kept people always learning, that they may be always paying them.
He is come to bring them off all the world`'s religions,
to the religion that he set up in the apostles`' days, in the new covenant,
which is pure and undefiled before God in his sight,
and keeps from the spots of the world, etc.
And the Lord is come to bring them off all the world`'s churches, to the church in God,
which Christ the heavenly man is head of; and to bring them off all the world`'s worships,
to worship God in Spirit and in truth,
which Christ set up above sixteen hundred years since.
So all men and women must come to the Spirit and truth in their hearts,
by which they must know the God of truth, who is a Spirit;
and then in the Spirit and in truth they will worship him,
and know what and whom they worship.
Also the Lord is come to bring his people off all the world`'s temples,
that with the Spirit they may know their bodies to be the temples of the Holy Ghost.
And the Lord is come to bring his people off all the world`'s crosses, pictures, images,
and likenesses, to know that the power of God is the cross of Christ,
which crucifies them to the world, and brings them up into the likeness and image of God,
that man and woman were in before they fell; and so to Christ that never fell.
This work must all know in their hearts, by the light of Christ Jesus,
who '`is the true light, that lighteth every man that cometh into the world.`'
It is called the light in man and woman, and the life in Christ the Word:
and Christ saith, '`Believe in the light, that ye may be the children of light.`'
And the light lets you see all your evil actions, that you have committed;
your ungodly ways you have walked in; and your ungodly words and thoughts.
If you hate this light, and love the darkness, and the prince of it,
more than this light, which is the life in Christ, the Prince of Life,
and will not come to it, because your deeds are evil, it will reprove you;
Christ tells you, '`this light is your condemnation.`'
Then what is all your profession good for,
when you remain under the condemnation of the true light, in which you should believe;
and so become children of light, and out of condemnation?
Therefore every one must believe in the light, if they receive Christ Jesus;
and as many as receive him, he gives them '`power to become the sons of God.`'
He that hath the Son of God, hath life; and they that have not the Son of God,
have not life: if then you have not life,
what good doth all your profession of the Scriptures from Genesis to Revelations do you,
any more than the Jews, Scribes, and Pharisees, that would not receive Christ the life,
upon whom God brought his overflowing scourge.
Therefore do you take heed, for your strength will be no better than theirs,
if you have not God and Christ`'s supporting power, when God`'s scourge comes upon you,
and you are filled with horrors and fears.
My desires are, that you may all repent, even from the highest to the lowest,
and not grieve, nor quench, nor vex, nor rebel against, God`'s good Spirit in you,
nor '`walk despitefully against the Spirit of Grace,`' which would teach you,
and bring your salvation; nor turn from it unto wantonness.
If you do, how can you escape the overflowing scourge of the Almighty,
and the wrath of the Lamb?
My desires are, that you may all obey God`'s good Spirit of truth,
which will lead you out of all evil into all truth,
and reprove you for your own righteousness, and for your own judgment and sin.
It will bring you to cleave to that which is good, to forsake that which is evil,
and to turn to the Lord, who will receive you in his mercy and kindness;
by which means you may escape the overflowing scourge in the day of vengeance,
which dreadful day is coming upon all evil-doers.
This is a warning to you, both for your temporal and eternal good;
to read in your assemblies, and your priests in their churches,
that all people may hear and fear;
as you will answer it at the terrible and dreadful day of judgment.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam, the 19th of the 7th Month, 1677.

I wrote also an Epistle to the ambassadors that were treating about a peace at Nimeguen,^
footnote:[These ambassadors were deputies from the King of France,
the United Netherlands, and several other potentates of Europe,
who met to consult the peace of Christendom.
George Fox`'s _Epistle_ to them was translated and printed in Latin.
Robert Barclay also wrote a treatise in Latin,
which was addressed and presented to each of the ambassadors,
with a copy of his principal work, _An Apology for the True Christian Divinity._
In the former,
Barclay strongly urged them to promote the good work for which they were assembled,
pointing out the true causes of war, and its incompatibility with Christian principles.
Before the year ended, a peace was concluded.]
as follows:--

[.blurb]
=== "`For the Ambassadors, that are met to treat for Peace at the City of Nimeguen, in the States`' dominions.

"`Christ Jesus saith, '`Blessed are the peace-makers,
for they shall be called the children of God,`' Matt. 5:9,
so all Christian men are to forsake evil, and do good, to seek peace and follow it,
if they will '`love life,
and see good days,`' 1 Pet. 3:11. God hath called all true Christians unto peace, 1 Cor. 7,
and therefore all Christians ought to follow this peace, which God calls them to.
They should let the peace of God rule in all their hearts;
which is above the peace of this world, that is so soon broken.
For the apostle commands the Christians to let the peace of God rule in their hearts,
to which all Christians should be subject.
The practice of this should be among all that profess Christianity;
and this peace is above that, which Christ takes from the earth, Rev. 6,
which is the peace of the wicked.
And the apostle saith to the Christians, '`Be at peace among yourselves,`' 1 Thess. 5.
Now all Christians should obey this command, and be at peace among themselves;
not in wars and strife.
And further, the apostle exhorts the Christians to '`keep the
unity of the Spirit in the bond of peace.`'
So this unity, this bond of peace,
should be kept (and not be broken) by all that bear that noble name, Christian.
They should keep the unity of the Spirit of Christ in the bond of the Prince of princes,
King of kings, and Lord of lords`' peace,
which is the duty of all true Christians to keep.
Herein they may honour Christ, in bringing forth the fruits of peace,
which are love and charity.
For the apostle tells you, '`The fruit of the good Spirit is love, joy, peace,
long-suffering, gentleness, goodness,`' etc. Gal. 5.

"`And the apostle exhorts the Christians, and saith, '`If it be possible,
as much as lieth in you,
live peaceably with all men:`' this should be the endeavour of all Christians.
For it is no honour to Christ, that Christians should war and destroy one another,
that profess his name, who saith, '`He came to save men`'s lives, and not to destroy them.`'
Christians have enemies enough abroad without them,
and therefore they should love one another, as Christ commands, who saith,
'`By this ye shall be known to be my disciples, if ye love one another.`'
For Christians are commanded to love enemies; therefore much more, one another.
And Christ saith, '`As the Father hath loved me, so I have loved you:
continue ye in my love,`' John 15:8,
and '`By this shall all men know that ye are my disciples,
if ye love one another,`' John 13:35. But if Christians war and destroy one another,
this will make Jews, Turks, Tartars, and Heathens say,
that you are not disciples of Christ.
Therefore, as you love God, and Christ, and Christianity, and its peace, all make peace,
as far as you have power, among Christians, that you may have the blessing.
You read, that Christians were called the household of faith, the household of God,
a holy nation, a peculiar people:
and they are commanded to be '`zealous of good works,`' not of bad:
and Christians are also commanded not to bite and devour one another,
lest they be consumed one of another.

"`Is it not a sad thing for Christians to be biting and
consuming one another in the sight of the Turks,
Tartars, Jews, and Heathens, when they should '`love one another, and do unto all men,
as they would have them do unto them?`'
Such devouring work as this, will open the mouths of Jews and Turks,
Tartars and Heathens, to blaspheme the name of Christ, who is the King of kings,
and Lord of lords, and cause them to speak evil of Christianity,
for them to see how the unity of the Spirit is broken among such,
as profess Christ and Christ`'s peace.
Therefore all Christians are to mind God and Christ`'s teaching,
who teacheth Christians to love one another, yea enemies;
and persuade all kings and princes,
to give liberty to all tender consciences in matters of religion and worship,
they living peaceably under every government: so that for the time to come,
there may be no more imprisonment and persecution among Christians,
for tender consciences about matters of faith, worship, and religion, that the Jews,
Turks, Tartars, and Heathens,
may not see how Christians are persecuting one another for religion: seeing,
from Christ and the apostles, Christians have no such command, but on the contrary,
to love one another; and knowing,
that Christ said to such as would have been plucking up tares,
'`Let the tares and the wheat grow together till the harvest (which is
the end of the world) lest they plucked up the wheat;`' and at the end
of the world Christ would send forth his angels,
and they should sever the wheat from the tares.
So Christ tells you, that it is the angels`' work at the end of the world,
and not men`'s work, before the harvest at the end of the world.
Hath not all this persecution, banishing, and imprisoning, and putting to death,
concerning religion, been the pretence of plucking up tares?
and hath not all this been before the harvest, before the end of the world?
And therefore, have not all these been actors against the express command of Christ,
the King of Heaven?
All kings and rulers, especially they that call themselves Christians,
should obey their Lord and Saviour`'s command: '`Let the tares and the wheat grow together,
till the harvest;`' and the harvest is the end of the world.
Christ also told some of his disciples,
that in their zeal would have had fire to come down from heaven,
to destroy such as would not receive him,
'`That they did not know what spirit they were of:`' and rebuked them, and said,
'`He came not to destroy men`'s lives, but to save them.`'
And therefore all such as have destroyed men`'s lives concerning religion,
and the worship of God, have they known what spirit they have been of?
Have they not done that which they should not do?
done that which Christ forbade, who saith,
'`Lest ye should pluck up the wheat with the tares,`' and saith,
'`It is the angels`' work at the end of the world?`'
And hath not God showed unto man what is good, and his duty, '`To love mercy,
to do justly, and to walk humbly with his God?`'
which man is to mind.

"`And the apostle exhorts Christians, '`To follow peace with all men, and holiness,
without which no man shall see the Lord,`' Heb. 12:14. Why
should Christians war and strive one with another,
seeing they all own in words one King, Lord, and Saviour, Christ Jesus, whose command is,
that they should '`love one another;`' which is a mark that they shall be known by,
to be Christ`'s disciples, as I said before.
And Christ, who is the King of kings, and Lord of lords, saith, '`This is my commandment,
that ye love one another, as I have loved you,`' John 15:12, and John xiii.
And the apostle saith,
Christians ought to '`be patient towards all men,`' 1 Thess. 5:14.

"`From him, who is a lover of truth, righteousness, and peace,
who desires your temporal and eternal good; and that in the wisdom of God,
that is from above, pure, gentle, and peaceable, you may be ordered,
and order all things, that God hath committed to you, to his glory;
and stop those things among Christians, so far as you have power, which dishonour God,
Christ, and Christianity!`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Amsterdam, the 21st of the 7th Month, 1677.

To the magistrates and priests of Embden I wrote,
showing them their unchristian practices in persecuting Friends.^
footnote:[William Penn also addressed the Council and Senate of the city of Embden,
relative to the sufferings of Friends there.
Though these appeals did not procure any immediate relief, yet, in about ten years after,
Friends enjoyed perfect liberty there.
See Sewell`'s _History,_ vol. ii., 420-425.]
And several other books I wrote, in answer to priests and others of Hamburg, Dantzic,
and other places, to clear the truth and Friends from their charges and false slanders.

[.blurb]
=== "`An Epistle concerning true Fasting, true Prayer, true Honour, and against Persecution, and for the true Liberty in Christ Jesus; that all may have a care, that the apostle hath not bestowed his labour in vain upon you in your observing of Days, Months, Times, Feasts, and Years, and of coming under the beggarly elements and the yoke of bondage again, and of bringing and forcing people into them.

"`Where did ever Christ or his apostles command any believers
or Christians to observe holidays or feast-days?
Let us see where it is written in the Scriptures of the New Testament,
in the four Evangelists, or the Epistles, or the Revelation,
that ever Christ or his apostles commanded
Christians to observe the time called Christmas,
or a day for Christ`'s birth?
or to observe the time called Easter, or Whitsuntide, or Peter`'s or Paul`'s, Mark`'s,
Luke`'s, or any other saint`'s day?

"`You, that profess yourselves to be the reformed churches from the Papists, Jews,
and Heathens, and the Scriptures to be your rule, and are professors of the new covenant,
where do you prove out of the New Testament,
that the apostles and the primitive church practised or forced any such thing,
or that Christ and his apostles gave any such command to the
churches that they should practise and observe any such days?
Let us see where this command is written.
Did not the apostle say unto the Galatians in the fourth chapter, '`But now,
after that ye have known God, or rather ye are known of God,
how turn ye again to the weak and beggarly elements,
whereunto ye desire again to be in bondage?
Ye observe days, and months, and times, and years; I am afraid of you,
lest I have bestowed upon you labour in vain.`'
And in the third of Galatians it is said, '`O foolish Galatians, who hath bewitched you,
that you should not obey the truth,`' etc.
And in Galatians the fifth,
the apostle exhorts them to '`stand fast in the liberty
wherewith Christ had made them free;`' and moreover said,
'`Be not entangled again with the yoke of bondage.`'

"`Now doth not this manifest, that there were some teachers,
that were drawing the church of the Galatians into these beggarly elements,
and bringing them again into bondage, in observing days, months, times, and years?
It was the apostle`'s work to bring them out of those bondages and beggarly elements;
and therefore, when they were going back again into observing days, months, times,
and years,
he was afraid that he had '`bestowed his labour upon them in vain;`' and he exhorts
them to '`stand fast in the liberty wherewith Christ Jesus hath made them free,
and not to be entangled again with the yoke of bondage,`' and again signifies,
that '`they had been once entangled with that yoke of bondage and beggarly elements.`'
But O! how are people, called Christians, since the apostles`' days,
gone again under this yoke of bondage, and these beggarly elements, in observing days,
months, times, and years, let their practice declare.
Nay, do not both Papists and Protestants force people to observe days, months, and times?
And therefore is not the apostle`'s labour and travail bestowed upon Christendom in vain,
which was to bring people from under such beggarly elements,
and that yoke of bondage (which the law did require),
to '`stand fast in the liberty wherewith Christ hath made them free,
and not to be entangled again with the yoke of bondage?`'
It was and is Christ,
that hath made and doth make his people free from these beggarly elements; therefore,
they that are redeemed,
are to '`stand fast in that liberty wherewith Christ hath made them free.`'
This liberty all true Christians are to stand fast in;
they are made free by Christ and not by man; for man,
without the Spirit and mind of Christ, seeks to force and compel Christ`'s followers,
such as are made free from the yoke of bondage, to outward things that the law commanded,
to the observing of days, months, times, feasts, and years.
From such weak, beggarly elements, they that know God, or are known of God and Christ,
are to stand fast in their liberty, and not come under,
nor be entangled with the yoke of bondage to such things again,
seeing he hath made them free.
For they that are in such things, and would force others to them,
are gone from that which gives the knowledge of God,
and have not stood fast in the liberty wherewith Christ makes free.

"`Concerning Prayer,
we do not read that ever Christ or his apostles did
seek by force to compel any to fast or pray with them.
But Christ taught them how they should pray, and be distinct from the hypocrites.
His words are as follows:--'`When thou prayest, thou shalt not be as the hypocrites are;
for they love to pray standing in the synagogues, and in the corners of the streets,
that they may be seen of men,`' etc.
'`But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door,
pray to thy Father, which is in secret, and thy Father which seeth in secret,
shall reward thee openly.
But when ye pray, use not vain repetitions, as the heathen do;
for they think they shall be heard for their much speaking.
Be not ye therefore like unto them; for your Father knoweth what things ye have need of,
before ye ask him,`' etc.
As the apostles and saints did, so do we; we pray in secret, and we pray in public,
as the Spirit gives us utterance, which helps our infirmities,
as it did the apostles and true Christians; after this manner we pray for ourselves,
and for all men both high and low.

"`Concerning Fasting, Christ saith, '`Moreover when ye fast, be not as the hypocrites,
of a sad countenance; for they disfigure their faces,
that they may appear unto men to fast.
But when thou fastest, anoint thy head and wash thy face,
that thou appear not unto men to fast, but unto thy Father which is in secret;
and thy Father, which seeth in secret, shall reward thee openly.`'

"`You may see in Isaiah the 58th, what the true fast is which the Lord requires;
where it is said to the prophet, '`Cry aloud, and spare not,
lift up thy voice like a trumpet, and show my people their transgression,
and the house of Jacob their sins; yet they seek me daily,
and delight to know my ways as a nation that did righteousness,
and forsook not the ordinance of their God; they ask of me the ordinances of justice;
they take delight in approaching to God.
Wherefore have we fasted, say they, and thou seest not?
wherefore have we afflicted our soul, and thou takest no knowledge?
Behold, in the day of your fast ye find pleasure, and exact all your labours.
Behold, ye fast for strife and debate, and to smite with the fist of wickedness,
ye shall not fast, as ye do this day, to make your voice to be heard on high.
Is it such a fast that I have chosen?
A day for a man to afflict his soul?
Is it to bow down his head as a bulrush, and to spread sackcloth and ashes under him?
Wilt thou call this a fast, and an acceptable day to the Lord?
Is not this the fast that I have chosen, saith the Lord;
to loose the hands of wickedness, to undo the heavy burdens,
and to let the oppressed go free, and that ye break every yoke?`'
So this fast that the Lord requires, is not to lay yokes, to oppress,
and lay heavy burdens, and to make fast the bands of wickedness;
but to loose and to break such things.

"`And further, concerning the true fast the Lord requires,
'`Is it not to deal thy bread to the hungry, and that thou bring the poor,
that are cast out, to thy house?
When thou seest the naked, that thou cover him,
and that thou hide not thyself from thy own flesh?
(Do you keep this true fast?) Then shall thy light break forth as the morning,
and thine health shall spring forth speedily; and thy righteousness shall go before thee,
the glory of the Lord shall be thy reward.
Then shalt thou call, and the Lord shall answer; thou shalt cry, and he shall say,
Here I am; if thou take away from the midst of thee the yokes,
the putting forth of the finger and speaking vanity;
and if thou draw out thy soul to the hungry, and satisfy the afflicted soul,
then shall thy light arise out of obscurity, and thy darkness be as the noon-day.
And the Lord shall guide thee continually, and satisfy thy soul in drought,
and make fat thy bones; and thou shalt be like a watered garden,
and like a spring of water, whose waters fail not,`' etc.

"`Now here is the practice of the true fast the Lord requires of his people;
and to them that observe this fast, the Lord saith, '`When they call, he will answer.`'
You may see what glorious and happy comforts they receive from the Lord,
that keep this true fast; but such as fast for strife and debate,
smite with the fists of wickedness, and make their voices to be heard on high;
who afflict their souls for a day, bow down their head as a bulrush,
and loose not the bands of wickedness; who do not undo every heavy burden,
break not off every yoke, nor let the oppressed go free;
who do not deal their bread to the hungry, clothe not the naked,
nor bring the poor to their house,
but hide themselves from their own flesh:--such
fasts and fasters the Lord doth not accept,
neither hath he chosen them.
But these appear to men with their disfigured faces,
and hang down their heads as a bulrush for a day, like the hypocrites, to fast,
as Christ speaks in Matt. 6.

"`And is it not the command of Christ,
that in their fast they should not appear unto men to fast?
And now you that would force us to shut up our shops on fasting-days, or for a day,
does not this fast appear to men?
and is not this the fast that the Lord saith in Isaiah, he '`doth not accept?`'
for he saith, '`Is this the fast that I have chosen, a day for a man to afflict his soul,
and bow down his head as a bulrush,`' etc.
'`Wilt thou call this a fast, and an acceptable day to the Lord?`' Isa. 58.

"`Therefore all God`'s people are to keep the
true fast of the Lord from debate and strife,
and the fists of wickedness; that fast that breaks the bands of wickedness,
and undoes every heavy burden; breaks every yoke, and lets the oppressed go free;
deals bread to the hungry, clothes the naked,
and brings the poor that are cast out to his own house.
Every one that keeps this true fast, their health shall grow, and when they call,
the Lord will hear them; he will be their guide continually,
satisfy their souls in drought, and make their bones fat;
and they shall be like a watered garden, and like a spring of water,
whose waters fail not.
Now you, that keep not this true fast,
when you call upon the Lord on your own fasting days, does the Lord answer you, and say,
'`Here I am?`'
Doth the Lord guide you continually?
Are your bones made fat by him, and your souls satisfied in drought?
Are you like a watered garden, and like a spring, whose waters fail not?
But you that keep not this true fast, do you not want these waters, which fail not?
so your souls are not satisfied in drought, but your bones are lean,
and you hear not the voice of the Lord, who saith,
'`Here I am;`' so you lose the heritage of Jacob, and ride not upon the high places there;
but come under.
Therefore every man and woman, shut your hearts against all manner of evil whatsoever,
and trade not with Babylon`'s merchants of confusion;
but keep the supernatural day of Christ that is sprung from on high,
that is kept by believing and walking in the light of Christ, and being grafted into him.
This will bring you to the true fast, from feeding upon any evil,
and to the true praying in the Spirit, as Christ and the apostles have taught.
The fruit of the Spirit is love, etc.
The birth of the Spirit is not a persecuting birth; but he that is born of the flesh,
will persecute him that is born of the Spirit,
because he will not follow the birth of the flesh, with its weak, beggarly elements,
that entangles with its yoke of bondage, and its observing of days, months, times, fasts,
feasts, and years;
which the birth of the Spirit is to stand fast against
in the liberty wherewith Christ hath made it free.

"`Do you not know, that the Turks keep their Sabbath on the sixth day,
the Jews upon the seventh day,
and the Christians meet together on the First-day of the week?
And that day which the Turks keep, the Jews`' and Christians`' shops are open;
and that day the Jews keep, Christians`' and Turks`' shops are open;
and the First-days that the Christians keep, both Jews`' and Turks`' shops are open?
The Turk does not force the Jews nor the Christians to
shut up their shops on their meeting-days,
but lets them have their liberty in Turkey.
And where do you read,
that ever the Turks forced any Christians to observe any of their holidays, fasts,
or feasts?
If not, should not Christians be beyond the Turks in giving
liberty to all tender consciences to serve God,
seeing Christ and the apostles command not, nor force people to observe holidays,
or times, or months, or years, but that they should pray always in the Spirit,
and fast always from strife and debate, from all manner of sin and evil;
and that will keep down the fist of wickedness, and the bond of iniquity, etc.
Why should not people of a tender conscience have their
liberty to exercise their consciences towards God,
that they may have '`a good conscience always towards
God and man,`' to perform that which God requires,
and to '`do unto all men, as they would have them to do unto them,
and to love their neighbours as themselves;`' seeing so many debauched, evil,
and seared consciences, as with a hot iron,
have liberty in their loose lives and conversations, and in their loose words,
whose tongues are at liberty to swear and curse,
and their spirits at liberty in drunkenness and uncleanness?
Let the magistrates look and see, how this evil,
seared conscience hath its liberty to be exercised in all manner of evil
things all Christendom over, which is a great shame and dishonour to God,
and Christ, and Christianity, yea, and humanity.
Therefore why should not God`'s people have their liberty to
exercise their good and tender consciences towards God and man?
For the mystery of faith, which Jesus Christ is the author and finisher of,
is held in a pure conscience;
and should not the work of the true Christian magistrate be to
encourage the exercise of this pure conscience towards God and man,
and to discourage the exercise of this evil, seared conscience,
that dishonours both God and Christ, and true Christianity?
If not, how are they a praise to them that do well, and a terror to evil-doers?

"`Concerning the not putting off our hats to men.
Many that go under the name of Christians, have taken offence at us,
because we could not put off our hats, and bow down to them;
for which we find no command from Christ or his apostles, but rather to the contrary.
For Christ saith, '`I receive not honour of men`' (mark, he did not receive honour of men);
and further Christ saith, '`How can ye believe which receive honour one of another,
and seek not the honour that comes from God only?`'
Now Christ declares it to be a mark of unbelievers,
that seek '`honour one of another,`' and seek not that '`honour
that comes from God only;`' and is not the putting off the hat,
and bowing with it, an honour to men, which they seek one of another,
and are offended if they have it not?
Nay, have they not fined, persecuted, and imprisoned some,
because they did not put off their hats to them?
Nay, do not the very Turks mock at the Christians in their proverb,
saying that '`the Christians spend much of their time in putting off their hats,
and showing their bare head to one another?`'
But should not those be beyond the Turks, that bear the noble name of Christian,
above seeking honour one of another, and persecuting them that will not give it,
when all true believing Christians should seek the honour that comes from God only?
which is the duty of all true believers in Christ Jesus,
for he would not receive honour of men.
And '`He that believeth on the Son of God, hath everlasting life;
and he that believeth not the Son, shall not see life;
but the wrath of God abideth on him,`' John 3:36. Is
not the Turks`' proverb a reproach to the Christians,
who say '`that the Christians spend much of their time in putting off their hats,
and showing their bare heads one to another?`'
Have you not fined and imprisoned many, because they would not put off their hats to you,
and show you their bare heads?
Nay, in many of your courts they shall not have right and justice,
nor liberty and freedom in cities or states, though they have truly served their time,
and are honest and civil men,
unless they will put off their hats and show their bare heads?
Have you not made a law against such, that they must forfeit two guilders if they do not?
Do you not seek to compel and force them to do it, and fine such as do not,
as at Lansmeer in Waterland?
Is not this the honour that you seek one of another?
Did not the Pharisees and Jews do the same?

"`As for your saying, '`the apostle commands to honour all men;
and such as rule well are worthy of double honour.`'
If this '`honouring all men,`' were to put off their hats to all men,
and show all men their bare heads, then this command you break yourselves;
for you do not this to all men generally;
and if they that rule well must have double hat-honour,
then they must put off their hats twice; and show them their bare heads.
If this hat-honour, and showing the bare head, be an invention of men, and not from God,
and ye cannot prove it by Scripture, yet say,
'`it is your rule;`' then you act beside the rule,
and compel people to act contrary to your rule.
For where did ever the prophets, Christ, or the apostles command any such thing?
Let us see a command, a practice, and an example for it.
Nebuchadnezzar, who was a persecutor,
and cast the three children of Israel into the fire with their hose, cloaks, and hats,
we do not read that he was offended at them, because they did not put off their hats,
and show him their bare heads; but because they would not bow to his image.
And is it not said in the margin of the Bible, where it is said,
'`honour all men,`' '`have all men in esteem?`'
Then they that rule well are worthy of double esteem;
and this esteem must be truly in the heart, without any envy, malice, or hatred.
As all men are the workmanship of God,
they are to be esteemed in the heart with the Spirit of God; and they that rule well,
are worthy of double esteem; here is true honour from the heart, both to God, and man,
his workmanship.
For people may put off their hats,
and show their bare heads one to another once or twice to the officers and magistrates,
and yet be full of envy, and malice, and hatred,
and murder in their hearts one against another; and give them that honour,
as you call it, and yet speak or wish bad things to them,
when they have turned their backs on them.
The true honour or esteem in the heart to all men, as they are God`'s creation,
is without any evil wish or thought in the heart to any men,
and especially to them that rule well, who have the double esteem,
whom God hath placed over people.
There is no evil in the heart that gives this respect, esteem, or honour,
and brings them to love their neighbours as themselves, and to '`do unto all men,
as they would have them do unto them;`' in that they esteem all men,
and have a double esteem for them that rule well.
This is beyond all the honour of putting off the hats once to all men,
and twice to them that are worthy of the double honour, as you may call it.
But we would ask Christians that practise this hat-honour,
and show one another their bare heads, Who invented this single honour and double honour,
seeing they cannot prove,
that ever Christ or the apostles did command or practise any such thing,
or Moses in the time of the law?
Now, do not say or think,
that we had this practice of not putting off our hats from the Turk;
for we were moved by the Spirit of the Lord,
before ever we heard of the Turks`' proverb and practice,
to leave the honour that is below, and seek the honour that comes from above,
when we came to be true believers in Christ Jesus.

"`Now concerning persecuting, imprisoning, and banishing God`'s people,
in whom Christ is manifest, and dwells in their hearts; doth not Christ tell you,
that in so doing you imprison him?
Then do you not banish him, and persecute him out of your cities and corporations?
And how can you enter into, and have a share in his kingdom,
though you may profess him in words?
Are not such to go into everlasting punishment, that do not visit Christ in prison?
Then what will become of you that banish and imprison him,
where he is manifest in his members,
and suffer them not to meet together to enjoy him amongst them, according to his promise?
Therefore you, that will not let Christ reign in his people,
and have his liberty in them, in your cities and countries, to exercise his offices,
you will not have your liberty in heaven.
You that will not let Christ reign in your hearts,
nor suffer him to reign in his people here upon the earth, in this world,
in your kingdoms;--you will not reign with Christ in heaven in his kingdom,
nor in the world without end.

"`You, that banish the truth out of your cities or countries, or his people for its sake,
banish the truth and Christ out of your hearts from ruling there;
so you yourselves are not the temples of God.
When you have banished Christ and his truth out of your own hearts,
you banish such in whom he rules out of your estates and country:
then see what judgments the Lord doth bring upon you, when you are left to yourselves;
yea, fears and troubles, one judgment after another, come upon you;
you are even filled with them.
But the banished, the sufferers for truth and Christ`'s sake,
have a peaceable habitation in the truth, which the devil is out of, and cannot get into;
which habitation will outlast all the habitations of the wicked and persecutors,
though they be ever so full of words without life and truth.
The life and the truth will outlast all airy notions, and Christ,
the Lamb and patient Seed, will overcome the devourer and the impatient seed;
and they that have the garment, the righteousness of Christ, which is the fine linen,
will find it to outlast all the rags and inventions of men.
For Christ saith to his learners, '`Be of good cheer,
I have overcome the world,`' the persecuting world.
He said also to his disciples, '`If the world hate you,
ye know that it hated me before it hated you.`'
Therefore let all that profess themselves
Christians lay aside persecution about religion,
churches, or worship, fasting or praying days;
for you have no command from Christ and his apostles to persecute any.
Christ, who is the King of kings and Lord of lords, when they called him a deceiver,
and blasphemed him, and said, '`He had a devil,`' did not persecute any of them for it,
nor force or compel any to hear and believe him, nor the apostles after him;
but he bade them, that would have been plucking np the tares,
'`Let the tares and wheat grow together until the harvest.`'
So you have no command from Christ or his apostles to persecute, imprison, banish,
or spoil the goods of any, for matter of pure conscience and religion, worship, faith,
and church, in the gospel-times.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Harlingeu in Friesland, the 11th of the 6th Month, 1677.

After some time George Keith and William Penn came back from Germany to Amsterdam,
and had a dispute with one Galenus Abrahams (one of the most noted Baptists in Holland),
at which many professors were present; but not having time to finish the dispute then,
they met again two days after, and the Baptist was much confounded,
and truth gained ground.^
footnote:[It appears that Galenus Abrahams asserted that nobody in
the present day could be accepted as a messenger of God,
unless he confirmed his doctrine by miracles.
See Sewell`'s _History,_ vol. ii., 366-368.]
Between these two disputes we had a very great meeting at Friends`' meeting-place,
at which many hundreds of people were, and some of high rank in the world`'s account.
An earl, a lord, and divers other eminent persons, were present,
who all behaved themselves very civilly.
But when the meeting was ended, some priests began to make opposition; which,
when William Penn understood, he stood up again,
and answered them to the great satisfaction of the people,
who were much affected with the several testimonies they had heard declared.
After the meeting several of them came to Gertrude`'s, where we were,
with whom George Keith had much discourse in Latin.

Having now finished our service at Amsterdam, we took leave of the Friends there,
and passed by wagon to Leyden, about twenty-five miles; where we stayed a day or two,
seeking out and visiting some tender people we heard of there.
We met with a German, who was partly convinced.
He informed us of an eminent man that was inquiring after truth.
Some sought him out, and visited him, and found him a serious man; I also spoke to him,
and he owned the truth.
William Penn and Benjamin Furly went to visit another great man,
that lived a little out of Leyden, who, they said,
had been general to the King of Denmark`'s forces.
He and his wife were very loving to them, and heard the truth with joy.

From Leyden we went to the Hague, where the Prince of Orange kept his court;
and we visited one of the judges of Holland, with whom we had pretty much discourse.
He was a wise, tender man, and put many objections and queries to us; which,
when we had answered, he was satisfied, and parted with us in much love.
Leaving the Hague, we went to Delft, and thence to Rotterdam that night,
where we stayed some days, and had several meetings.
While I was here I gave forth a book for the Jews; with whom, when I was at Amsterdam,
I had a desire to have some discourse, but they would not.
Here also I reviewed several other books and papers which I had given forth before,
and which were now transcribed.
