== Chapter IX.

[.chapter-synopsis]
* 1677--1680.
* George Fox, with other Friends, sails for England, and lands at Harwich, after a hazardous voyage of three days
* has a large meeting at Colchester, and proceeds thence to London
* writes to his wife
* receives further accounts of persecution in New England
* travels into Buckinghamshire, and meets with some false brethren, who are unruly and troublesome at meetings
* Friends have a special meeting with them afterwards
* at Reading meets with opposition to the settlement of a women`'s meeting
* visits Bristol during the fair, where are many Friends from various parts
* the separatists there are very rude and abusive
* he aids Friends in drawing up a breviat of their sufferings, to present to the judges at Gloucester assizes
* meets with some separatists at Finchcomb
* is engaged with other Friends in soliciting Parliament to grant them relief from the statutes made against Popish recusants
* attends the Yearly Meeting, which was a glorious and heavenly one
* Friends greatly united in testifying against the spirit of separation
* not one mouth opened on its behalf
* the Truth prospers at home and abroad
* George Fox writes to his wife
* writes to the king of Poland to dissuade him from persecution
* to Friends in Amsterdam
* Friends again press their suit for relief from the statutes made against Popish recusants without success
* are much exercised with the spirit of separation, which opposes the order and discipline of the church
* George Fox writes a paper to open the understandings of the weak, and as a reproof to a censorious judging spirit
* has conferences with some of the opposers at Hertford
* writes again to Friends to warn them of this spirit of false liberty
* visits Friends in prison at Leicester
* advises Friends how to end their differences
* writes an epistle to Friends in London
* writes to Friends in prison to console them under suffering
* writes an epistle to the Yearly Meeting
* an encouragement to Friends to be valiant for the Truth
* also a caution to Friends to keep in humility
* travels again towards the South
* visits prisoners in York Castle
* recommends Friends to lay their sufferings before the judge at the assizes
* attends the Yearly Meeting in London
* writes to the Great Turk and to the Dey of Algiers
* to the latter particularly respecting Friends who are captives there
* at Hertford meets with John Story (the schismatic) and some of his party, but the Truth prevails
* has a meeting with some of the opposers
* solicits the Parliament to grant relief to Friends under suffering
* writes a paper against plots and plotters.

Finding our spirits clear of the service which the Lord had given us to do in Holland,
we took leave of Friends of Rotterdam, and passed by boat to the Briel,
in order to take passage that day for England;
several Friends of Rotterdam accompanying us, and some of Amsterdam,
who were come to see us again before we left Holland.
But the packet not coming in till night, we lodged that night at the Briel; and next day,
being the 21st of the 8th month, and the First-day of the week, we went on board,
and set sail about ten, viz., William Penn, George Keith, and I,
and Gertrude Dirick Nieson, with her children.

We were in all about sixty passengers, and had a long and hazardous passage;
for the winds were contrary, and the weather stormy; the boat also was very leaky,
insomuch that we had to have two pumps continually going, day and night; so that,
it was thought, there was quite as much water pumped out as the vessel would have held.
But the Lord, who is able to make the stormy winds to cease,
and the raging waves of the sea calm, yea, to raise them and stop them at his pleasure,
He alone did preserve us: praised be his name for ever!
Though our passage was hard, yet we had a fine time,
and good service for truth on board among the passengers, some of whom were great folks,
and were very kind and loving.
We arrived at Harwich on the 23rd, at night,
having been two nights and almost three days at sea.
Next morning William Penn and George Keith took horse for Colchester; but I stayed,
and had a meeting at Harwich; and there being no Colchester coach there,
and the post-master`'s wife being unreasonable in her demands for a coach,
and deceiving us of it also after we had hired it,
we went to a Friend`'s house about a mile and a half in the country, and hired his wagon,
which we bedded well with straw, and rode in it to Colchester.

I stayed there till First-day, having a desire to be at Friends`' meeting that day;
and a very large and weighty one it was; for Friends, hearing of my return from Holland,
flocked from several parts of the country, and many of the town`'s-people coming in also,
it was thought there were about a thousand people at it; and all was peaceable.
Having stayed a day or two longer at Colchester, I travelled through Essex,
visiting Friends at Halstead, Braintree, Felstead, and Saling,
and having meetings with them.
At Chelmsford I had a meeting in the evening; and there being many Friends prisoners,
they got liberty and came to the meeting; and we were all refreshed together in the Lord.
Next day, the 9th of the 9th month, I got to London,
where Friends received me with great joy;
and on the First-day following went to Gracechurch Street meeting,
where the Lord visited us with his refreshing presence,
and the glory of the Lord surrounded the meeting: praised be the Lord.

After I had been a little while in London, I wrote the following letter to my wife:--

[.salutation]
"`Dear Heart,

"`To whom is my love, and to the children, and to all the rest of Friends,
in the Lord`'s truth, power, and Seed, that is over all; glory to the Lord,
and blessed be his name for ever beyond all words! who hath
carried me through and over many trials and dangers,
in his eternal power!
I have been twice at Gracechurch Street meeting;
and though the opposite spirits were there, yet all was quiet;
the dew of heaven fell upon the people, and the glory of the Lord shone over all.
Every day I am fain to be at meetings about business, and sufferings,
which are great abroad; and now many Friends are concerned with many persons about them:
so in haste, with my love to you all--`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 24th of the 9th Month, 1677.

About this time I received letters from New England,
which gave account of the magistrates`' and rulers`' cruel and
unchristian-like proceedings against Friends there,
whipping and abusing them very shamefully; for they whipped many women Friends.
One woman they tied to a cart, and dragged her along the street, stripped above the waist.
They whipped some masters of ships that were not Friends,
only for bringing Friends thither.
And at that very time, while they were persecuting Friends in this barbarous manner,
the Indians slew threescore of their men, took one of their captains,
and flayed the skin off his head while he was alive, and earned it away in triumph;
so that the sober people said "`the judgments of God came upon them
for persecuting the Quakers;`" but the blind dark priests said,
"`it was because they did not persecute them enough.`"^
footnote:[For full particulars of the great intolerance and spirit of
persecution manifested by the Puritans of New England towards the Quakers,
the reader is referred to Bowden`'s _History of Friends in America_, vol. v.,
from the commencement to p. 308.]
Great exercise I had in seeking relief here for our poor suffering Friends there,
that they might not lie under the rod of the wicked.

Upon this and other services for truth, I stayed in London a month or five weeks,
visiting meetings,
and helping and encouraging Friends to labour for the
deliverance of their suffering brethren in other parts.
Afterwards I went down to Kingston, and visited Friends there and thereaway.
Having stayed a little among Friends there,
looking over a book I had then ready to go to press, I went into Buckinghamshire,
visiting Friends, and having several meetings amongst them, as at Amersham, Hunger-hill,
Jordans, Hedgerly, Wickham, and Turville-heath.
In some of which, they that were gone out from the unity of Friends in truth into strife,
opposition, and division, were very unruly and troublesome;
particularly at the men`'s meeting at Thomas Ellwood`'s at Hunger-hill,
where the chief of them came from Wickham, endeavouring to make disturbance,
and to hinder Friends from proceeding in the business of the meeting.
When I saw their design I admonished them to be sober and quiet,
and not trouble the meeting by interrupting its service; but rather,
if they were dissatisfied with Friends`' proceedings, and had anything to object,
let a meeting be appointed on purpose some other day.
So Friends offered them to give them a meeting another day:
and at length it was agreed to be at Thomas Ellwood`'s^
footnote:[Thomas Ellwood is only mentioned twice incidentally in these volumes.
It was he who, after the death of George Fox,
transcribed this excellent work for the press.
(See _Letters, etc., of Early Friends,_ p. 213.) He was also the author of several works,
including _A Life of David,_ in verse; a work on tithes; a _Sacred History,_ etc.
Ellwood was born in 1639, at Crowell, in Oxfordshire,
and joined Friends when about twenty years of age.
Brought up in ease, luxury, and fashion, he had much to learn; much to unlearn,
much to forsake, of the manners, the pride, and the willworship of the world;
and to follow alter that plainness and purity of
life unto which the spirit of truth leads.
Nothing but religion could have enabled one,
with a disposition naturally so high and resolute as his, to submit, as he did,
to buffetings, beatings, cruel treatment, and persecution,
with becoming meekness and patience.
{footnote-paragraph-split}
In 1662, Ellwood became the companion of the poet Milton,
and it was he who suggested to the latter the writing of _Paradise Regained._
He had a peculiar gift for government in the church, and was very serviceable therein;
an ornament to the meeting he belonged to, and much missed when he died.
According to his biographer, he was "`a man of a comely aspect,
of a free and generous disposition, of a courteous and affable temper,
and pleasant conversation; a gentleman born and bred; a scholar, a true Christian,
an eminent author, a good neighbour, a kind friend.`"
He proved a very useful and acceptable elder in the church,
devoting nearly the whole of his time and talents to its service.
He died in 1713, and was buried at Jordans,
leaving behind him a most interesting autobiography,
to which the reader is referred for further particulars.]
the week following.
Accordingly Friends met them there, and the meeting was in the barn;
for there came so many, that the house could not receive them.
After we had sat a while they began their jangling.
Most of their arrows were shot at me; but the Lord was with me,
and gave me strength in his power to cast back their
darts of envy and falsehood upon themselves.
Their objections were answered, and things were opened to the people;
a good opportunity it was, and serviceable to the truth; for many that before were weak,
were now strengthened and confirmed; some that were doubting and wavering,
were satisfied and settled;
and faithful Friends were refreshed and comforted in the springings of life amongst us.
For the power arose, and life sprung,
and in the arising thereof many living testimonies were borne against that wicked,
dividing, rending spirit, which those opposers were joined to, and acted by;
and the meeting ended to the satisfaction of Friends.
That night I lodged with other Friends, at Thomas Ellwood`'s;
and the same week had a meeting again with the opposers at Wickham,
where they again showed their envy, and were made manifest to the upright-hearted.

After I had visited Friends in that upper side of Buckinghamshire,
I called upon Friends at Henley in Oxfordshire,
and afterwards went by Corsham to Heading, where I was at meeting on First-day,
and in the evening had a large meeting with Friends.
Next day there being another meeting about settling a women`'s meeting,
some of them that had let in the spirit of division, fell into jangling,
and were disorderly for a while, till the weight of truth brought them down.
After this I passed on, visiting Friends, and having meetings in several places,
through Berkshire and Wiltshire, till I came to Bristol,
which was on the 21st of the 11th Month, just before the fair.

I stayed at Bristol all the time of the fair, and some time after.
Many sweet and precious meetings we had;
many Friends being there from several parts of the nation, some on account of trade,
and some in the service of truth.
Great was the love and unity of Friends that abode faithful in the truth,
though some who were gone out of the holy unity, and were run into strife, division,
and enmity, were rude and abusive,
and behaved themselves in a very unchristian manner towards me.
But the Lord`'s power was over all; by which being preserved in heavenly patience,
which can bear injuries for his name`'s sake, I felt dominion therein over the rough,
rude, and unruly spirits; and left them to the Lord, who knew my innocency,
and would plead my cause.
The more these laboured to reproach and vilify me, the more did the love of Friends,
that were sincere and upright-hearted, abound towards me;
and some that had been betrayed by the adversaries, seeing their envy and rude behaviour,
broke off from them; who have cause to bless the Lord for their deliverance.

When I left Bristol, I went with Richard Snead to his house in the country,
and thence to Hezekiah Coale`'s at Winterbourne, in Gloucestershire,
whither came several Friends that were under great sufferings for truth`'s sake,
whom I had invited to meet me there.
Stephen Smith,^
footnote:[This being the last mention of Stephen Smith, it may be added,
that he was born in 1023, and being convinced in 1655,
suffered both in person and estate by imprisonment and spoiling of goods,
for his testimony on behalf of Christ.
He was a man of account in the world, who, in his younger years, travelled much abroad,
having resided some time at Scanderoon, in Syria, as a merchant,
and afterwards published a work called, _Wholesome Advice and Information,_
wherein he shows how much some of the Turks exceeded some Christians in their
dealings.
{footnote-paragraph-split}
He was an honest upright man,
one that feared God and was of good report,
being a preacher of righteousness in his daily conduct, ever ready to do good.
He became a valiant gospel minister,
and spoke to the comfort and encouragement of those that heard him,
travelling in many parts of England in gospel service.
He died in peace at his own house, near Guildford, in Surrey, in 1678.
He wrote many serviceable works, which were collected and published in an 8vo volume,
entitled, _The True Light Discovered to all who Desire to Walk in the Day._]
Richard Snead, and I, drew up a breviat of their sufferings,
setting forth the illegal proceedings against them,
which was delivered to the judges at the assizes at Gloucester;
and they promised to put a stop to those illegal proceedings.
Next day we passed to Sudbury, and had a large meeting in the meeting-house there,
which at that time was of very good service.
We went next day to Nathaniel Crips`'s at Tedbury, and thence passed on to Nailsworth;
where on First-day we had a brave meeting, and large.
Thence we went to the quarterly meeting at Finchcomb,
where were several of the opposite spirit, who, it was thought,
intended to make some disturbance amongst Friends; but the Lord`'s power was over,
and kept them down, and good service for the Lord we had at that meeting.
We returned from Finchcomb to Nailsworth, and had another very precious meeting there,
to which Friends came from the several meetings thereabouts;
which made it very large also.

We went from Nailsworth the 1st of the 1st Month, 1678,
and travelled through the country visiting
Friends and having many meetings at Cirencester,
Crown-Allins, Cheltenham, Stoke-orchard, TewkeBury, etc., so went to Worcester,
where I had formerly suffered imprisonment above a year for truth`'s sake;
and Friends rejoiced greatly to see me there again.
Here I stayed several days, and had many very precious meetings in the city,
and much service amongst Friends.
After which, I had meetings at Pershore and Evesham;
and then struck to Kagley in Warwickshire, to visit the Lady Conway,^
footnote:[Lady Conway was a person of great piety, and a favourer of Friends.
In a letter to the learned and excellent Dr. Henry More, who was her particular friend,
she thus expresses herself concerning them:--
{footnote-paragraph-split}
Your conversation with them (the Friends) at London might be,
as you express it, charitably intended,
like that of a physician frequenting his patients for
the increase or confirmation of their health;
but must confess, that my converse with them is,
to receive health and refreshment from them.`"--See Appendix
to Barclay`'s second edition of _Isaac Pennington`'s Letters,_ p. 311.]
who I understood was very desirous to see me, and whom I found tender and loving,
and willing to detain me longer than I had freedom to stay.
About two miles hence I had two meetings at a Friend`'s house,
whose name was John Stanley, whither William Dewsbury came,
and stayed with me about half a day.
Afterwards I visited Friends in their meetings, at Stratford, Lamcoat,
and Armscott (whence I was sent prisoner to Worcester in 1673),
and thence passed into Oxfordshire, visiting Friends, and having meetings at Sibford,
North Newton, Banbury, Adderbury, etc.
Then visiting Friends through Buckinghamshire, at Long-crendon, Ilmere, Mendle, Weston,
Cholsberry, Chesham, etc., I came to Isaac Pennington`'s, where I stayed a fewdays;
and then turning into Hertfordshire, visited Friends at Charlewood, Watford, Hempstead,
and Market-street, at which places I had meetings with Friends.
From Market-Street I went in the morning to Luton in Bedfordshire, to see John Crook,
with whom I spent good part of the day, and went towards evening to Alban`'s,
where I lay that night at an inn.
And visiting Friends at South-Mims, Barnet, and Hendon, where I had meetings,
I came to London the 8th of the 3rd Month.
It being the fourth day of the week, I went to Gracechurch-Street meeting,
which was peaceable and well; and many Friends, not knowing I was come to town,
were very joyful to see me there; and the Lord was present with us,
refreshing us with his living virtue; blessed be his holy name!

The parliament was sitting when I came to town,
and Friends having laid their sufferings before them,
were waiting on them for relief against the laws made against Popish recusants,
which they knew we were not;
though some malicious magistrates took advantages to prosecute
us in several parts of the nation upon those statutes.
Friends attending on that service when I came, I joined them therein;
and there was some probability that something might be
obtained towards Friends`' ease and relief in that case,
many of the parliament-men being tender and loving towards us,
believing we were much misrepresented by our adversaries.
But when I went down one morning with George Whitehead to the parliament house,
to attend upon them on Friends`' behalf, suddenly they were prorogued,
though but for a short time.

About two weeks after I came to London, the Yearly Meeting began,
to which Friends came up out of most parts of the nation,
and a glorious heavenly meeting we had.
O the glory, majesty, love, life, wisdom, and unity, that were amongst us!
The power reigned over all,
and many testimonies were borne therein against that ungodly spirit,
which sought to make rents and divisions amongst the Lord`'s people;
but not one mouth was opened amongst us in its defence, or on its behalf.
Good and comfortable accounts also we had, for the most part,
from Friends in other countries; of which I find a brief account in a letter,
which soon after I wrote to my wife, the copy whereof here follows;--

[.salutation]
"`Dear Heart,

"`To whom is my love in the everlasting Seed of life that reigns over all.
Great meetings here have been, and the Lord`'s power hath been stirring through all,
the like hath not been.
The Lord hath in his power knit Friends wonderfully together,
and his glorious presence did appear among them.
And now the meetings are over, blessed be the Lord! in quietness and peace.
From Holland I hear things are well there: some Friends are gone that way,
to be at their Yearly Meeting at Amsterdam.
At Embden, Friends that were banished are got into the city again.
At Dantzic, Friends are in prison,
and the magistrates threatened them with harder imprisonment;
but the next day the Lutherans rose, and plucked down (or defaced) the Popish monastery;
so they have work enough among themselves.
The King of Poland received my letter, and read it himself;
and Friends have since printed it in High Dutch.
By letters from the half-yearly meeting in Ireland,
I hear that they are all in love there.
At Barbadoes, Friends are in quietness, and their meetings settled in peace.
At Antigua also and Nevis, truth prospers,
and Friends have their meetings orderly and well.
Likewise in New England and other places, things concerning truth and Friends are well;
and in those places the men`'s and women`'s meetings are settled; blessed be the Lord!
So keep in God`'s power and Seed, that is over all,
in whom ye all have life and salvation; for the Lord reigns over all in his glory,
and in his kingdom; glory to his name for ever, Amen.
In haste, with my love to you all, and to all Friends.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 26th of the 3rd Month, 1678.

[.offset]
The letter to the King of Poland mentioned is as follows:--

[.blurb]
=== "`To Johannes III. King of Poland, etc.

[.salutation]
"`O King!`"

"`We desire thy prosperity both in this life and that which is to come.
And we desire that we may have our Christian liberty to
serve and worship God under thy dominion;
for our principle leads us not to do anything prejudicial to the king or his people.
We are a people that exercise a good conscience towards God through his Holy Spirit,
and it do serve, worship, and honour him;
and towards men in the things that are equal and just,
doing to them as we would have them do unto us; looking unto Jesus,
who is the author and finisher of our faith; which faith purifies our hearts,
and bring us to have access to God; without which we cannot please him;
by which faith all the just live, as the Scripture declares.
That which we desire of thee, O king, is,
that we may have liberty of conscience to serve and worship God,
and to pray unto him in our meetings together in the name of Jesus, as he commands,
with a promise that he will be in the midst of them.
The king, we hope, cannot but say that this duty and service is due to God and Christ;
and we give Caesar his due, and pay our tribute and custom equal with our neighbour,
according to our proportion.
We never read in all the Scriptures of the New Testament,
that Christ or his disciples banished or imprisoned any
that were not of their faith or religion,
and would not hear them, or gave them any such command; but, on the contrary,
let the tares and the wheat grow together, till the harvest;
and the harvest is the end of the world.
Then Christ will send his angels to sever the wheat from the tares, etc.
He rebuked such as would have had fire from heaven to
consume those that would not receive Christ;
and told them that they did not know what spirit they were of.
He came not to destroy men`'s lives, but to save them.

"`We desire the king to consider how much persecution there has been in Christendom,
since the apostles`' days, concerning religion.
Christ said, they should go into everlasting punishment,
that did not visit him in prison;
then what will become of them that imprison him in his members, where he is manifest?
None can say that the world is ended;
and therefore how will Christendom answer the
dreadful and terrible God at his day of judgment,
that have persecuted one another about religion, before the end of the world,
under pretence of plucking up tares; which is not their work, but the angels'`,
at the end of the world?
Christ commands men to love one another, and to love enemies,
and by this they should be known to be his disciples.
O! that all Christendom had lived in peace and unity, that they might,
by their moderation, have judged both Turks and Jews;
and let all have their liberty that do own God and Jesus,
and walk as becomes the glorious gospel of the Lord Jesus Christ.
Our desires are,
that the Lord God of heaven may soften the king`'s heart to all tender consciences,
that fear the Lord, and are afraid of disobeying him.

"`We entreat the king to read some of the noble expressions of several kings and others,
concerning liberty of conscience; and especially Stephanus, king of Poland`'s sayings,
viz.: '`It belongeth not to me to reform the consciences;
I have always gladly given that over to God, which belongeth to him;
and so shall I do now, and also for the future.
I will suffer the weeds to grow till the time of harvest,
for I know that the number of believers is but small: therefore,`' said he,
when some were proceeding in persecution, '`I am king of the people,
not of their consciences.`'
He also affirmed, that '`religion was not to be planted with fire and sword.`'
_Chron. Liberty of Religion,_ part 2.

"`Also a book written in French by W. M., anno 1576, hath this sentence, viz.:
'`Those princes that have ruled by gentleness and clemency, added to justice,
and have exercised moderation and meekness towards their subjects,
always prospered and reigned long; but, on the contrary,
those princes that have been cruel, unjust, prejudiced, and oppressors of their subjects,
have soon fallen, they and their estates, into danger, or total ruin.`'

"`Veritus saith, '`Seeing Christ is a Lamb, whom you profess to be your head and captain,
then it behoveth you to be sheep, and to use the same weapons that he made use of;
for he will not be a shepherd of wolves and wild beasts, but only of sheep.
Wherefore, if you lose the nature of sheep,`' said he,
'`and be changed into wolves and wild beasts, and use fleshly weapons,
then will you exclude yourselves out of his calling, and forsake his banner;
and then will he not be your captain,`' etc.

"`Also we find it asserted by King James, in his speech to the parliament,
in the year 1609, '`That it is a pure rule in divinity,
that God never planted his church with violence of blood.`'
And furthermore he said, '`it was usually the condition of Christians to be persecuted,
but not to persecute.`'

"`King Charles said, in his prayer to God,
'`Thou seest how much cruelty amongst Christians is acted under the colour of religion;
as if we could not be Christians unless we crucified one another.`'

"`Page 28, '`Make them at length seriously to consider,
that nothing violent nor injurious can be religious.`'

"`Page 70,
'`Nor is it so proper to hew out religious reformation by the
sword as to polish them by fair and equal disputations among
those that are most concerned in the differences;
whom not force, but reason, must convince.`'

"`Page 66, '`Take heed,
that outward circumstances and formalities in religion devour not all.`'

"`Pages 91, 92, '`In point of true conscientious tenderness I have so often declared,
how little I desire my laws and sceptre should entrench on God`'s sovereignty,
who is the only King of conscience.`'

"`Page 123, '`Nor do I desire any man should be further subject unto me,
than all of us may be subject unto God.`'

"`Page 200, '`O thou Sovereign of our souls, the only Commander of our consciences!`'

"`Page 346 (In his '`Meditations on Death'`),
'`It is indeed a sad state to have his enemies to be his accusers, parties, and judges.`'

"`The Prince of Orange testified, anno 1579,
'`That it was impossible the land should be kept in peace,
except there was a free toleration in the exercise of religion.`'

"`' Where hast thou read in thy day (said Menno) in the writings of the apostles,
that Christ or the apostles ever cried out to the magistrates for
their power against them that would not hear their doctrine,
nor obey their words?
I know certainly,`' said he, '`that where a magistrate shall banish with the sword,
there is not the right knowledge, spiritual word, nor church of Christ; it is,
Invocare brachinm seculare (to invoke the secular arm).`'

"`'`It is not Christian-like, but tyrannical (said D. Philipson),
to banish and persecute people about faith and religion;
and they that so do are certainly of the Pharisaical generation,
who resisted the Holy Ghost.`'

"`Erasmus said, '`That though they take our money and goods,
they cannot therefore hurt our salvation; they afflict us much with prisons,
but they do not thereby separate us from God.`'--In de Krydges wrede, fol. 63.

"`Lucernns said, '`He that commandeth anything, wherewith he bindeth the conscience,
this is an antichrist.`'--In de Bemise Disp. fol. 71.

"`Irenffius affirmed, '`that all forcing of conscience,
though it was but a forbidding of the exercise which is
esteemed by one or another to be necessary to salvation,
is in no wise right nor fitting.`'
He also affirmed,
'`that through the diversity of religions the kingdom
should not be brought into any disturbance.`'

"`Constuntins, the emperor, said,
'`That it was enough that he preserved the unity of the faith,
that he might be excusable before the judgment seat of God;
and that he would leave every one to his own understanding,
according to the account he will give before the judgmentseat of Christ.
Hereto may we stir up people (said he), not compel them;
beseech them to come into the unity of the Christians,
but to do violence to them we will not in any wise.`'--Sebast. Frank, Chron. fol. 127.

"`Augustinus said,
'`Some disturbed the peace of the church while they went
about to root out the tares before their time;
and through this error of blindness (said he) are they themselves
separated so much the more from being united unto Christ.`'

"`Retnaldus testified, '`That he who, with imprisoning and persecuting,
seeketh to spread the gospel, and greaseth his hands with blood,
shall much rather be looked upon for a wild hunter, than a preacher,
or a defender of the Christian religion.`'

"`I have for a long season determined (said Henry IV., king of France,
in his speech to the parliament, 1599), to reform the church, which, without peace,
I cannot do: and it is impossible to reform or convert people by violence.
I am king, as a shepherd, and will not shed the blood of my sheep,
but will gather them through the mildness and goodness of a king,
and not through the power of tyranny:
and I will give them that are of the reformed
religion right liberty to live and dwell free,
without being examined, perplexed, molested,
or compelled to anything contrary to their consciences;
for they shall have the free exercise of their religion, etc.`'--
+++[+++Vid. Chron. Van de Underg. 2. deel, p. 1514.]

"`Ennins said, '`Wisdom is driven out when the matter is acted by force.
And therefore the best of men, and most glorious of princes,
were always ready to give toleration.`'

"`Eusebius, in his second book of the life of Constantine,
reports these words of the emperor: '`Let them which err,
with joy receive the like fruition of peace and quietness with the faithful;
with the restoring of communication and society
may bring them into the right way of truth-:
let none give molestation to any; let every one do as he determines in his mind.
And indeed, there is great reason for princes to give toleration to disagreeing persons,
whose opinions cannot by fair means be altered; for if the persons be confident,
they will serve God according to their persuasions: and if they be publicly prohibited,
they will privately convene: and then all those inconveniences and mischiefs,
which are arguments against the permission of conventicles,
are arguments for the public permission of differing religions, etc.,
they being restrained and made miserable, endears the discontented persons mutually,
and makes more hearty and dangerous confederations.`'

"`The like counsel, in the divisions of Germany at the first reformation,
was thought reasonable by the Emperor Ferdinand, and his excellent son Maximilian;
for they had observed, '`that violence did exasperate, was unblessed, unsuccessful,
and unreasonable; and therefore they made decrees of toleration.`'

"`The Duke of Savoy,
repenting of his war undertaken for religion against the Piedmontese,
promised them toleration; and was as good as his word.

"`It is remarkable, that till the time of Justinian the emperor, Anno Domini 525,
the Catholics and Novatians had churches indifferently permitted, even in Rome itself.

"`And Paul preached the kingdom of God,
teaching those things which concerned the Lord Jesus Christ, with all confidence;
and no man forbade him:
and this he did for the space of two years in his own hired house at Home,
and received all that came to him.

"`Now, O king,
seeing these noble testimonies concerning liberty of conscience from kings, emperors,
and others, and the liberty that Paul had at Rome in the days of the heathen emperor,
our desire is,
that we may have the same liberty at Dantzic to meet together in our own hired houses;
which cannot be any prejudice, either to the king or the city,
for us to meet together to wait upon the Lord, and pray unto him,
and to serve and worship him in Spirit and in truth in our own hired houses;
seeing our principle leads us to hurt no man, but to love our enemies,
and to pray for them: yea, them that persecute us.
Therefore, O king, consider, and the city of Dantzic,
would you not think it hard for others to force you from your religion to another,
contrary to your consciences?
And if it be so, that you would think it hard to you,
then '`do you unto others as you would have them
do unto you;`' do not you that unto others,
which you would not have them do unto you; for that is the royal law,
which ought to be obeyed.
And so in love to thy immortal soul, and for thy eternal good, this is written.`"

[.signed-section-signature]
G+++.+++ F.

"`__Postscript.--__'`Blessed be the merciful, for they shall obtain mercy.`'
And remember, O king, Justin Martyr`'s two Apologies to the Roman emperors,
in the defence of the persecuted Christians; and that notable Apology,
which was written by Tertullian, upon the same subject;
which are not only for the Christian religion,
but against all persecution for religion.`"

[.blurb]
=== "`Dear Peter Hendricks, John Claus, J. Rawlins, and all the rest of Friends in Amsterdam, Friesland, and Rotterdam, to whom is my love in the Seed of life, that is over all.

"`I Received your letter with one from Dantzic: I have written something directed to you,
to the King of Poland, which you may translate into High Dutch,
and send to Friends there to give to the king; or you may print it,
after it be delivered in manuscript, which may be serviceable to other princes.
So in haste, with my love.
The Lord God Almighty over all give you dominion in his eternal power,
and in it over all preserve you, and keep you to his glory,
that you may answer that of God in all people.
Amen.`"

[.signed-section-signature]
George Fox.

[.signed-section-context-close]
London, the 13th of the 9th Month, 1677.

I continued yet in and about London some weeks, the parliament sitting again,
and Friends attending to get some redress of our sufferings,
which about this time were very great,
and heavy upon many Friends in divers parts of the nation;
being very unduly prosecuted upon the statutes made against Popish recusants;
though our persecutors could not but know that Friends were utterly against Popery;
having borne testimony against it in word and writing, and suffered under it.
But though many of the members of parliament in each house were kind to Friends,
and willing to do something for their ease, yet having much business,
they were hindered from doing the good they would,
so that the sufferings of Friends continued.
But that which added much to the grief and exercise of Friends, was,
that some who made a profession of the same truth with us,
being gone from the simplicity of the gospel into a fleshly liberty,
and labouring to draw others after them, opposed the order and discipline,
which God by his power had set up and established in his church;
and made a great noise and clamour against prescriptions;
whereby they easily drew after them such as were loosely inclined,
and desired a broader way than the path of truth to walk in.
Some also that were more simple, but young in truth, or weak in judgment,
were apt to be betrayed by them, not knowing the depths of Satan in these wiles;
for whose sake I was moved to write the following paper, for undeceiving the deceived,
and opening the understandings of the weak in this matter:--

"`All you that deny prescriptions without distinction,
may as well deny all the Scriptures,
which were given forth by the power and Spirit of God.
For do not they prescribe how men should walk towards God and man,
both in the Old Testament and in the New?
Yea, from the very first promise of Christ in Genesis,
what people ought to believe and trust in, and all along, till ye come to the prophets?
Did not the Lord prescribe to his people by the fathers, and then by his prophets?
Did he not prescribe to the people how they should walk,
though they turned against the prophets in the old covenant,
for declaring or prescribing to them the way, how they might walk to please God,
and keep in favour with him?
In the days of Christ, did not he prescribe and teach, how people should walk and believe?
And after him, did not the apostles prescribe to people how they might come to believe,
and receive the gospel and the kingdom of God,
directing to that which would give them the knowledge of God,
and how they should walk in the new covenant in the days of the gospel,
and by what way they should come to the holy city?
And did not the apostles send forth their decrees by faithful chosen men,
that had hazarded their lives for Christ`'s sake, to the churches,
by which they were established?
So you that deny prescriptions given forth by the power and Spirit of God,
do thereby oppose the Spirit that gave them forth in all the holy men of God.
Were there not some all along in the days of Moses, in the days of the prophets,
in the days of Christ, and in the days of his apostles,
who did withstand that which they gave forth from the Spirit of God?
And hath there not been the like since the days of the apostles?
How many have risen, since truth appeared,
to oppose the order which stands in the power and Spirit of God?
who are but in the same spirit which hath opposed the
Spirit of God all along from the beginning.
See, what names or titles the Spirit of God gave that opposing spirit in the old covenant,
and also in the new; which is the same now;
for after the Lord had given forth the old covenant,
there were some among themselves that opposed; these were worse than public enemies.
And likewise, in the days of the new covenant, in the gospel-times,
you may see what sort opposed Christ and the apostles,
after they came to some sight of the truth,
and how they turned against Christ and his apostles?
See what liberty they pleaded for, and ran into, in the apostles`' days,
who could not abide the cross, the yoke of Jesus.

"`We see the same rough and high spirit cries now for liberty,
which the power and Spirit of Christ cannot give--cries,
'`Imposition,`' and yet is imposing;--cries,
'`liberty of conscience,`' and yet is opposing liberty of conscience;
and cries against '`prescriptions,`' and yet is prescribing both in words and writing.
So with the everlasting power and Spirit of God this Spirit is fathomed; its rise,
beginning, and end; and it is judged.
This spirit cries, '`we must not judge conscience; we must not judge matters of faith;
and we must not judge spirits, nor religions,`' etc.
Yes; they that are in the pure Spirit and power of God, which the apostles were in,
judge of conscience, whether it be a seared conscience, or a tender conscience;
they judge of faith, whether it be a dead one, or a living one; they judge of religion,
whether it be vain, or pure and undefiled; they judge of spirits, and try them,
whether they be of God or not; they judge of hope, whether it be that of hypocrites,
or the true hope that purifies, even as God is pure; they judge of belief,
whether it be that which is born of God, and overcometh the world,
or that which runs into the spirit of the world, which lusts to envy,
and doth not overcome the world; they judge of worships, whether they be will-worships,
and the worship of the beast and dragon, or the worship of God in Spirit and in truth;
they judge of angels, whether they be fallen, or those that keep their habitation;
they judge the world, that grieves and quenches the Spirit, hates the light,
turns the grace of God into wantonness, and resists the Holy Ghost;
they judge of the hearts, ears, and lips, which are circumcised,
and which are uncircumcised; they judge of ministers, and apostles, and messengers,
whether they be of Satan or of Christ; they judge of differences in outward things,
in the church or elsewhere; yea,
the least member of the church hath power to judge of such things,
having the one true measure, and true weight to weigh things, and measure things withal,
without respect to persons.
This judgment is given, and all these things are done,
by the same power and Spirit the apostles were in.
Such also can judge of election and reprobation; who keep their habitation,
and who do not; who are Jews, and who are of the synagogue of Satan;
who are in the doctrine of Christ, and who are in the doctrines of devils;
who prescribes and declares things from the power and Spirit of God,
and who prescribes and declares things from a loose spirit,
to let all loose from under the yoke of Christ, the power of God,
into looseness and liberty.

"`These likewise can judge and discern,
who brings people into the possession of the gospel of light and life,
over death and darkness, and into the truth, where the devil cannot get in;
and who brings them into the possession of death and darkness,
out of the glorious liberty of the gospel, and of Jesus Christ, his faith, truth, Spirit,
light, and grace.
For there is no true liberty, but in that; and that liberty answers the grace, the truth,
the light, the Spirit, the faith, the gospel of Christ in every man and woman,
and is the yoke to the contrary in every man and woman.
That makes it rage, and swell, and puff up; for it is restless, unruly, out of patience,
and ready to curse his God, and that which reigns over him, because it hath not its will.
It works with all subtilty and evasion with its restless spirit,
to get in and defile the minds of the simple, and to make rapes upon the virgin minds.
But as they receive the heavenly wisdom,
by which all things were made (which wisdom is above that spirit),
through this wisdom they will be preserved over that spirit.

"`And Christ hath given judgment to his saints in his church, though he be judge of all;
and the saints, in the power and Spirit of God,
had and have power to judge of words and manners, of lives and conversations,
of growths and states, from a child to a father in the truth;
and to whom they are a savour of death, and to whom they are a savour of life;
who serve the Lord Jesus Christ and preach him,
and who preach themselves and serve themselves; and who talk of the light, of faith,
of the gospel, of hope, and of grace, and preach such things;
yet in their works and lives deny them all, and God and Christ,
and preach up liberty from that in themselves to that in others,
which should be under the yoke and cross of Christ, the power of God.
So the saints, in the power and Spirit of Christ, can discern and distinguish,
who serves God and Christ, and who serves him not;
and can put a distinction between the profane and the holy.
Bulk, such as have lost their eye-salve, and whose sight is grown dim,
lose this judgment, discerning, and distinction in the church of Christ;
and such come to be spewed out of Christ`'s mouth, except they repent; and if not,
they come to corrupt the earth, and burden it, that it vomits them out of it.

"`Therefore, all are exhorted to keep in the power and Spirit of Christ Jesus,
in the word of life, and the wisdom of God (which is above that which is below),
in which they may keep their heavenly understandings and discernings;
and so set the heavenly, spiritual judgment over that which is for judgment,
which dishonours God, and leads into loose and false liberty; out of the unity,
which stands in the heavenly Spirit,
which brings into conformity to the image of the Son of God, and his gospel,
the power of God (which was before the devil was),
and his truth (which the devil is out of), in which all are of one mind, heart, and soul,
and come to drink into one Spirit, being baptized into one Spirit, and so into one body,
of which Christ is the head; and so keep one fellowship and unity in the Spirit,
which is the bond of peace, the Prince of princes`' peace.
And they that cry so much against judging, and are afraid of judgment,
whether they be apostates, professors, or profane,
are the most judging with their censorious, false spirits, and judgment;
and yet they cannot bear the true judgment of the Spirit of God,
nor stand in his judgment.
This hath been manifest from the beginning, they having the false measures,
and the false weights;
for none have the true measure and true weight but they who keep in the light, power,
and Spirit of Christ.
And now there is a loose spirit, that cries for liberty, and against prescriptions,
and yet is prescribing ways, both by words and writings.
The same spirit cries against judging, and would not be judged,
and yet is judging with a wrong spirit.
This is given forth in reproof to that spirit.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 9th of the 4th Month, 1678.

When I had finished what service I had for the Lord at this time here,
I went towards Hertford; visiting Friends, and having several meetings in the way.
At Hertford I stayed some days, having much service for the Lord there,
both amongst Friends in their meetings,
and in conferences with such as having let in evil
surmisings and jealousies concerning Friends,
stood in opposition to the order of truth:
and in answering some books written against truth and Friends.
While I was here, it came upon me to write a few lines,
and send them abroad amongst Friends, as follows:--

[.salutation]
"`Dear Friends,`"

"`Let the holy Seed of life reign over death and the unholy seed in you all;
that in the holy Seed of the kingdom ye may all feel the everlasting holy peace with God,
through Christ Jesus, your Saviour, and sit down in Him, your life and glorious rest,
the holy rock and foundation,
that standeth sure over all from everlasting to everlasting,
in whom all the fulness of blessedness is;
so that ye may glory in Him that liveth for evermore, Amen! who is your eternal joy,
life, and happiness; through whom you have peace with God.
This holy Seed bruiseth the head of the serpent, and will outlive all his wrath and rage,
malice and envy; who was before he and it were,
and remains when he and it are gone into the fire that burns with brimstone.
The Seed, Christ, will reign; and so will ye, as ye do live and walk in Him,
sit down in Him, and build up one another in the love of God.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Hertford, the 10th of the 5th Month, 1678.

Next day a fresh exercise came upon me,
with respect to those unruly and disorderly spirits, that were gone out from us,
and were labouring to draw others after them into a false liberty.
In the sense I had of the hurt and mischief these might do, where they were given way to,
I was moved to write a few lines to warn Friends of them, as follows:--

[.salutation]
"`All Friends,

"`Keep in the tender life of the Lamb, over that unruly, puffed up, and swelling spirit,
whose work is for strife, contention, and division, under a pretence of conscience,
and drawing into looseness and false liberty, dangerous to the welfare of youth.
They that do encourage them, will be guilty of their destruction,
and set up a sturdy will, instead of conscience, in their rage and passion;
which will quench the universal Spirit in themselves, and in every man and woman: and so,
that spirit shall not have liberty in themselves, nor in others;
thus they shut up the kingdom of heaven in themselves, and also in others.
So a loose spirit getting up under a pretence of liberty of conscience;
or a stubborn will, making a profession of the words of truth in a form without power,
all looseness and vileness will be sheltered and covered under this pretence,
which is for eternal judgment: for that doth dishonour God.
Therefore, keep to the tender Spirit of God in all humility,
that in it you may know that ye are all members of one another,
and all have an office in the church of Christ.
All these living members know one another in the Spirit, and not in the flesh.
So here is no man ruling over the woman, as Adam did over Eve in the fall: but Christ,
the spiritual man, among and over his spiritual members,
which are edified in the heavenly love that is shed in their heart from God,
where all strife ceases.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Hertford, the 11th of the 5th Month, 1678.

I went from Hertford to a meeting at Rabley-Heath, and thence to Edward Crouch`'s,
of Stevenage.
Next day to Baldock, where I had a meeting that evening;
and after that had meetings at Hitchin and Ashwell.
Then passing through part of Bedfordshire, where I had a meeting or two,
I went to Huntingdon, in which county I stayed several days, having many meetings,
and much service amongst Friends; labouring to convince gainsayers,
and to confirm and strengthen Friends in the way and work of the Lord.
At Ives, in Huntingdonshire, George Whitehead came to me, and travelled with me,
in the work of the Lord, for five or six days in that county,
and in some part of Northamptonshire; and leaving me in Great Bowden in Leicestershire,
he went towards Westmorland.
I stayed longer in Leicestershire, visiting Friends at Saddington, Wigston, Knighton,
Leicester, Sileby, Swannington, and divers other places;
where I had very precious meetings, and good service amongst Friends and other people:
for there was great openness,
and many weighty and excellent truths did the Lord give me to deliver amongst them.

At Leicester I went to the jail to visit the Friends
that were in prison there for the testimony of Jesus,
with whom I spent some time;
encouraging them in the Lord to persevere steadfastly and faithfully in their testimony,
and not to be weary of suffering for his sake.
And when I had taken my leave of them, I spoke with the jailer,
desiring him to be kind to them, and let them have what liberty he could,
to visit their families sometimes.

I had a meeting or two in Warwickshire, and then went into Staffordshire,
where I had several sweet and opening meetings,
both for gathering into truth and establishing therein.
While I was in Staffordshire, I was moved to give forth the following paper:--

[.small-break]
'''

"`Dear Friends of the quarterly and monthly meetings everywhere: My desire is,
that ye may all strive to be of one mind in the Lord`'s power and truth,
which is peaceable, and into which strife and enmity cannot come;
also in the wisdom of God, which is pure, peaceable, and easy to be entreated,
which is above that which is below, that is earthly, devilish, and sensual;
and that with, and in this heavenly wisdom, you may be all ordered, and do what ye do,
to God`'s glory.
And, dear Friends, if there should happen at any time anything that tends to strife,
dispute, or contention in your monthly or quarterly meetings,
let it be referred to half a dozen, or such a like number, to debate and end,
out of your meetings, as it was at first,
that all your monthly and quarterly meetings may be kept peaceable.
And then they may inform the meeting what they have done;
that the weak and youth amongst you may not be hurt,
through hearing of strife or contention in your meetings,
where no strife or contention ought to be; but all to go on,
and determine things in one mind, in the power of God, the gospel order:
in which gospel of peace ye will preserve the peace of all your meetings.
If any man or woman have anything against any one, let them speak to one another,
and end it between themselves; if they cannot so decide,
let them take two or three to end it.
In case these determine it not, let it be laid before the church; and let half a dozen,
or such a number out of your monthly or quarterly meeting hear it, and finally end it,
without respect of persons.
Let all prejudice be laid aside and buried; also all shortness one towards another;
and let love, which is not puffed up, envies not, seeks not her own,
but bears all things, have the dominion in all your meetings;
for that doth edify the body, which Christ is the head of;
and this will rule over all sounding brass and tinkling cymbals.
This love will suffer long, and is kind; it will keep down that which would vaunt itself,
or be puffed up, or behave itself unseemly, or is easily provoked;
it hath a sway over all such fruits, as are not of the Spirit,
the fruit of which is love, etc.
And that with this Holy Spirit ye may all be baptized into one body,
and be made to drink into one Spirit; in which Spirit ye will have unity,
in which is the bond of the King of kings'`, and Lord of lords`' peace.
They that dwell in love, dwell in God; for God is love:
therefore let every one keep his habitation.
My love to you in Christ Jesus, the everlasting Seed, which is over all.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Staffordshire, the 20th of the 6th Month, 1678.

Out of Staffordshire I went to visit John Gratton^
footnote:[John Gratton was born about the year 1641.
He was first brought under religious conviction when he
was a shepherd boy about eleven years old,
but he remained in a halting stats till he attained to manhood,
after which he became more devoted in heart to the Lord.
He was brought into great grief on observing the
instability of some professed preachers of the gospel,
in times of persecution.
In 1670 he began to preach among the Baptists,
but soon left this people because they also flinched in the day of trial,
and becoming convinced of the soundness of the principles held by Friends,
and seeing their constancy under suffering, he joined them in 1671.
The third time he attended a Friends`' meeting,
he spoke under the constraining influence of the Divine Spirit;
and he soon became an able minister of Christ.
He often left his temporal concerns to make apostolic
visits to various parts of Great Britain and Ireland,
lie also suffered imprisonment for about five years and a half for the gospel`'s sake.
His residence was for many years at Monyash, in Derbyshire,
but in 1708 he removed to Needham, and resided with a daughter,
at whose house he died in 1711, aged 68--a minister about forty years.]
at Monyash in Derbyshire, with whom I tarried one night;
and went next day to William Shaw`'s of the Hill, in Yorkshire,
where I appointed a meeting to be on First-day following.
Many Friends out of Derbyshire, and from several meetings in Yorkshire, came,
and a precious, comfortable meeting it was;
wherein was opened the blessed state of man before he fell; the means by which he fell;
the miserable condition into which he fell; and the right way of coming out of it,
into a happy state, again by Christ, the promised Seed.

I spent about two weeks in Yorkshire,
travelling from place to place amongst Friends in the Lord`'s service;
and many heavenly meetings I had in that county.
Then visiting Robert Widders, at Kellet, in Lancashire, I passed to Arnside,
in Westmorland, where I had a precious, living meeting in the Lord`'s blessed power,
to the great satisfaction and comfort of Friends, who came from divers parts to it.
Next day I went to Swarthmore; and it being the meeting-day there,
I had a sweet opportunity with Friends, our hearts being opened in the love of God,
and his blessed life flowing amongst us.

I had not been long at Swarthmore,
ere a concern came upon me to visit the churches of Christ in London and elsewhere,
by an epistle, as follows:--

[.salutation]
"`Dear, Friends,

"`To whom is my love in the heavenly Seed, in whom all nations are blessed.
O, keep all in this Seed, in which ye are blessed,
and in which Abraham and all the faithful were blessed, without the deeds of the law;
for the promise was and is to, and with the Seed,
and not with the law of the first covenant.
In this Seed all nations, and ye, are blessed,
which bruiseth the head of the seed that brought the curse, and separated man from God;
this is the Seed which reconciles you to God,
this is the Seed in which ye are blessed both in temporals and spirituals;
through which ye have an inheritance among the sanctified, that cannot be defiled,
neither can any defiled thing enter into its possession;
for all defilements are out of this Seed.
This is that which leavens into a new lump, and bruises the head of the wicked seed,
which leavens into the old lump, upon which the Sun of Righteousness goes down and sets;
but it never goes down and sets to them that walk in the Seed,
in which all nations are blessed: by which Seed they are brought up to God,
which puts down that Seed which separated them from God;
so that there comes to be nothing between them and God.
Now, all my dear Friends, my desires are,
that ye may all be valiant in this heavenly Seed, for God and his truth upon the earth,
and spread it abroad, answering that of God in all;
that with it the minds of people may be turned towards the Lord,
that he may come to be known, and served, and worshipped;
and that ye may all be as the salt of the earth, to make the unseasoned savoury.
And in the name of Jesus keep your meetings, who are gathered into it,
in whose name ye have salvation; he being in the midst of you,
whose name is above every name under the whole heaven.
So ye have a Prophet, Bishop, Shepherd, Priest,
and Counsellor (above all the counsellors and priests, bishops, prophets,
and shepherds under the whole heaven) to exercise his offices among you,
in your meetings, that are gathered in his name.
For Christ`'s meeting and gathering is above all the
meetings and gatherings under the whole heaven;
and his body, his church, and he the head of it, is above all the bodies, churches,
and heads under the whole heaven.
And the faith that Christ is the author of, the worship that he hath set up,
and his fellowship in the gospel, are above all historical faiths,
and the faiths that men have made,
together with their worships and fellowships under the whole heaven.`"And now,
dear Friends, keep your men`'s and women`'s meetings in the power of God, the gospel,
the authority of them, which brings life and immortality to light in you;
and this gospel, the power of God, will preserve you in life, and in immortality,
that ye may see over him that hath darkened,
and kept from the knowledge of the things of God:
for it is he and his instruments which have darkened you from life and immortality,
that would throw down your men`'s and women`'s meetings,
and would darken you again from this life and immortality,
which the gospel hath brought to light, and will preserve you,
as your faith stands in this power, in which every one sees his work and service for God.
Every heir in the power of God, the gospel, hath right to this authority,
which is not of man, nor by man; which power of God is everlasting,
an everlasting order and fellowship; and in the gospel is everlasting joy, comfort,
and peace, which will outlast all those joys, comforts, and peaces,
that will have an end; and that spirit also, that opposes its order,
and the glorious fellowship, peace, and comfort in it.

"`And, dear Friends, my desire is, that ye may keep in the unity of the Spirit,
that baptizes you all into one body, of which Christ is the heavenly and spiritual Head;
so that ye may see and bear witness thereto, and all drink into the one Spirit;
which all people upon the earth are not likely to do, while they grieve, quench,
and rebel against it; nor to be baptized into one body,
and to keep the unity of the Spirit, which is the bond of peace, yea,
the King of kings`' and Lord of lords`' peace;
which it is the duty of all true Christians to keep, who are inwardly united to Christ.
My love to you all in the everlasting Seed.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 26th of the 7th Month, 1678.

There were about this time several Friends in prison for bearing testimony to the truth,
to whom I was moved to write a few lines, to comfort, strengthen,
and encourage them in their sufferings;
having a true sense of their sufferings upon my spirit, sympathizing with them therein.
That which I wrote was after this manner:--

[.salutation]
"`My Dear Friends,

"`Who are sufferers for the Lord Jesus`' sake, and for the testimony of his truth;
the Lord God Almighty with his power uphold and
support you in all your trials and sufferings,
and give you patience and content in his will,
that ye may stand valiant for Christ and his truth upon the earth,
over the persecuting and destroying spirit,
which makes to suffer in Christ (who bruises his head),
in whom ye have both election and salvation.
For his elect`'s sake the Lord hath done much from the foundation of the world;
as may be seen throughout the Scriptures of truth.
They that touch them touch the apple of God`'s eye; they are so tender to him;
and therefore it is good for all God`'s suffering children to trust in the Lord,
and to wait upon him: for they shall be as Mount Sion,
that cannot be removed from Christ, their rock and salvation,
who is the foundation of all the elect of God, of the prophets and the apostles,
and of God`'s people now, and to the end.
Glory to the Lord and the Lamb over all!
Remember my dear love to all Friends, and do not think the time long;
for all time is in the Father`'s hand, his power.
Therefore keep the word of patience, and exercise that gift;
and the Lord strengthen you in your sufferings, in his Holy Spirit of Faith. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 5th of the 12th Month, 1678.

I abode in the North at this time above a year,
having service for the Lord amongst Friends there,
and being much taken up in writing in answer to books published by adversaries;
and for opening the principles and doctrines of truth to the world,
that they might come to have a right understanding thereof, and be gathered thereunto.
Several epistles also to Friends I wrote in this time, on divers occasions;
one was to the Yearly Meeting of Friends held in London this year, 1679,
a copy of which here follows:--

[.salutation]
"`My Dear Friends And Brethren,

"`Who are assembled together in the name and power of the Lord Jesus Christ; grace,
mercy, and peace from God the Father, and from the Lord Jesus Christ,
fill all your hearts, and establish you in his grace, mercy, and peace upon Christ,
the holy, living Rock and Foundation, who is the First and Last,
and over all the rocks and foundations in the whole world;
a Rock and Foundation of life for all the living to build upon,
which stands sure in his heavenly, divine light, which is the life in Him,
by whom all things were made:
who is the precious stone laid in Zion (and not in the world),
which all the wise master-builders rejected,
who pretended to build people up to heaven with the words of the prophets,
and the law from Mount Sinai, but out of the life of both.
Such builders therefore could not receive the law of life from Christ,
the precious Stone laid in Sion, nor the word from heavenly Jerusalem.
But you, my dear Friends, that have received this law from heavenly Sion,
and the word from heavenly Jerusalem, in the new covenant,
where the life and substance is enjoyed,
you see the end and abolishing of the Jews`' law and ceremonies from Mount Sinai.
And therefore, my desire is, that you all may keep in the law of life and love,
which ye have in Christ Jesus, by which love the body is edified, knit,
and united together to Christ Jesus, the Head.
This love beareth all things, and fulfils the law; and it will preserve all in humility,
to be of one mind, heart, and soul;
so that all may come to drink into that one Spirit that doth baptize and circumcise them;
plunging down and cutting off the body of the sins of the flesh,
that is gotten up in man and woman by their transgressing of God`'s commands.
So that in this holy, pure Spirit,
all may serve and worship the pure God in Spirit and in truth,
which is over all the worships that are out of God`'s Spirit and his truth.
In this Spirit ye will all have a spiritual unity and fellowship,
over all the fellowships of the unclean spirits which are out of truth in the world.
By this holy Spirit all your hearts, minds, and souls, may be knit together to Christ,
from whence it comes; and by the grace and truth which came by Jesus Christ,
which all should be under the teachings of in the new covenant, and not under the law,
as the outward Jews were in the old covenant--by
this grace and truth in the new covenant,
all may be made God`'s free men and women, to serve God in the new life,
and in the new and living way; showing forth the fruits of the new heart and new spirit,
in the new covenant, over death and darkness; glory be unto the Lord for ever!

"`Now, Friends, in this grace and truth is your heavenly, gracious,
and true liberty to every spiritual mind,
that makes you free from him that is out of truth, where your bondage was;
also your liberty in the holy, divine, and precious faith,
which gives you victory over that which once separated you from God and Christ,
and by which faith ye have access to God again, through Jesus Christ.
So in this divine and holy faith, ye have divine, holy, and precious liberty, yea,
and victory over him that separated you from God:
and this faith is held in a pure conscience.
So the liberty in the Spirit of God,
is in that which baptizes and plunges down sin and iniquity,
and puts off the body of death and of the sins of the flesh,
that is gotten up by transgressing God`'s command.
And also the liberty of the gospel, which is sent from heaven by the Holy Ghost,
which is the power of God, which was, and is again to be, preached to all nations:
in this gospel (the power of God, which is over the power of Satan) is the true liberty,
and the gospel-fellowship and order.
So that the evil spirit or conscience, or false, dead faith,
and that which is ungracious and out of truth, and not in the Spirit of God,
nor in his gospel, nor in the divine faith, its liberty is in the darkness:
for all the true liberty is in the gospel, and in the truth that makes free;
in the faith, in the grace, and in Christ Jesus, who destroys the devil and his works,
that hath brought all mankind into bondage.
So in this heavenly, peaceable Spirit, and truth, and faith, which works by love,
and in the gospel of peace, and in Christ Jesus, is all the saints`' peace, and pure,
true, and holy liberty; in which they have salt, and sense, feeling, discerning,
and savour, yea, unity and fellowship one with another, and with the Son and the Father,
heavenly eternal fellowship.
So all being subject to the grace, and truth, to the faith,
and gospel (the power of God), and to his good Spirit; in this they distinguish all true,
pure, and holy liberty, from that which is false.
This will bring all to sit low: for patience runs the race,
and the Lamb must have the victory; and not the rough, unruly, and vain talkers,
unbaptized, uncircumcised, and unsanctified.
Such travel not in the way of regeneration, but in the way of unregeneration;
neither go they down into death with Christ by baptism;
and therefore such are not like to reign with him in his resurrection,
who are not buried with him in baptism.
Therefore, all must go downward into the death of Christ, and be crucified with him,
if they will arise, and follow him in the regeneration,
before they come to reign with him.

"`And, Friends, many may have precious openings;
but I desire all may be comprehended in that thing which doth open to them;
and that they may all keep in the daily cross; then they keep in the power,
that kills and crucifies that, which would lead them amongst the beasts and goats,
to leaven them into their rough, unruly spirit; that through the cross, the power of God,
that may be crucified, and they in the power may follow the Lamb.
For the power of God keeps all in order, subjection,
and humility--in that which is lovely and virtuous, decent, comely, temperate,
and moderate; so that their moderation appears to all men.
My desire is, that all your lights may shine, as from a city set upon a hill,
that cannot be hid; and that ye may be the salt of the earth, to salt and season it,
and make it savoury to God, and you all seasoned with it.
Then all your sacrifices will be a sweet savour to the Lord,
and ye will be as the lilies and roses, and garden of God,
which gives a sweet smell unto him; whose garden is preserved by his power, the hedge,
that hedges out all the unruly and unsavoury,
and the destroyers and hurters of the vines, buds, and plants, and God`'s tender blade,
which springs up from his Seed of life; who waters it with his heavenly water,
and word of life continually, that they may grow and be fruitful;
that so he may have a pleasant and fruitful garden.
Here all are kept fresh and green, being watered every moment with the everlasting,
holy water of life, from the Lord, the fountain.

"`My dear Friends, my desire is, that this heavenly Seed,
that bruises the head of the serpent, both within and without,
may be all your crown and life, and ye in him, one another`'s crown and joy,
to the praise of the Lord God over all, blessed for evermore!
This holy Seed will outlast and wear out all that which the evil seed,
since the fall of man, has brought forth and set up.
As every one hath received Christ Jesus the Lord,
so walk in him in the humility which he teaches; and shun the occasions of strife,
vain janglings, and disputings with men of corrupt minds, who are destitute of the truth:
for the truth is peaceable, and the gospel is a peaceable habitation in the power of God;
his wisdom is peaceable and gentle, and his kingdom stands in peace.
O, his glory shines over all his works! and in Christ Jesus, who is not of the world,
ye will have peace, yea, a peace that the world cannot take away:
for the peace which ye have from him, was before the world was,
and will be when it is gone.
This keeps all in that, which is weighty and substantial, over all chaff.
Glory to the Lord God over all for ever and ever! Amen.

"`And now, my dear Friends,
the Lord doth require more of you than he doth of other people;
because he hath committed more to you.
He requires the fruits of his Spirit, of the Light, of the Gospel, of the Grace,
and of the Truth;
for herein is he glorified (as Christ said) in your
bringing forth much fruit--fruits of righteousness,
holiness, godliness, virtue, truth, and purity;
so that ye may answer that which is of God in all people.
Be valiant for his everlasting, glorious gospel, in God`'s Holy Spirit and truth;
keeping in unity, and in the Holy Spirit, Light, and Life,
which is over death and darkness, and was before death and darkness were.
In this Spirit ye have the bond of peace, which cannot be broken,
except ye go from the Spirit; and then ye lose this unity and bond of peace,
which ye have from the Prince of Peace.

"`The world also expects more from Friends than from other people;
because you profess more.
Therefore you should be more just than others in your words and dealings,
and more righteous, holy, and pure in your lives and conversations;
so that your lives and conversations may preach.
For the world`'s tongues and mouths have preached long enough;
but their lives and conversations have denied
what their tongues have professed and declared.

"`And, dear Friends, strive to excel one another in virtue, that ye may grow in love,
that excellent way which unites all to Christ and God.
Stand up for God`'s glory, and mind that which concerns the Lord`'s honour,
that in nowise his power may be abused, or his name evil spoken of,
by any evil talkers or walkers: but that in all things God may be honoured,
and ye may glorify him in your bodies, souls, and spirits,
the little time ye have to live.
My love to you all in the holy Seed of Life, that reigns over all,
and is the First and Last; in whom ye all have life and salvation,
and your election and peace with God, through Jesus Christ,
who destroys him that hath been between you and God;
so that nothing may be between you and the Lord, but Christ Jesus.
Amen.

"`My life and love is to you all, and amongst you all.
The Lord God Almighty by his mighty power,
by which he hath preserved all his people unto thls day,
preserve and keep you all in his power, and peaceable, holy truth,
in unity and fellowship one with another, and with the Son and the lather.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 24th of the 3rd Month, 1679.

Divers other epistles and papers I wrote to Friends, during my stay in the North;
one was in a few lines, to encourage Friends to be bold and valiant for the Truth,
which the Lord had called them to bear witness to; it was thus:--

[.salutation]
"`Dear Friends,

"`All be valiant for the Lord`'s Truth upon the earth, which the serpent, Satan,
and the devil is out of; and in the truth keep him out,
in which you all have peace and life, and unity with God and his Son,
and one with another.
Let the love of God fill all your hearts,
that in it ye may build up and edify one another in the light, life, Holy Spirit,
and power of God, the glorious, comfortable gospel of Christ, the heavenly Man,
your Lord and Saviour;
who will fill all your vessels with his heavenly wine and water of life;
clothe you with his heavenly clothing, his fine linen, that never waxeth old;
and arm you with his heavenly weapons and armour,
that ye may stand faithful witnesses for God and his Son, who is come,
and hath given you an understanding to know Him, and ye are in him.
So walk in Him, in whom ye all have life and salvation, and peace with God.
My love to you all in the Lord Jesus Christ, in whom I have laboured; and God Almighty,
in his eternal power and wisdom, preserve you all to his glory.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 29th of the 10th Month, 1679.

The next day, having a sense upon me that some who had received the Truth,
and had openings thereof, for want of keeping low, had run out therefrom,
I was moved to give forth the following epistle,
as "`a warning and exhortation to all to dwell in humility:`"--

[.salutation]
"`My Dear Friends,

"`Whom the Lord in his tender mercies, hath visited with the dayspring from on high,
and hath opened you to confess and bow to his name; keep low in your minds,
and learn of Christ, who teacheth you humility, to keep in it; so that in nowise,
ye that are younger, be exalted, or puffed up, or conceited through your openings,
and by that means lose your conditions, by being carried up into presumption;
and then fall into despair, and so abuse the power of God.
For it was the apostles`' care, that none should abuse the power of the Lord God;
but in all things their faith was to stand therein,
that they all might be comprehended into the truth, which they spoke to others,
that they might not be preachers to others, and themselves cast-aways.
Therefore it doth concern you to be comprehended into that, which ye do preach to others,
and to keep low in it; then the God of Truth will exalt the humble in his truth, light,
grace, power, and Spirit, and in his wisdom to his glory.
Here all are kept in their measures of grace, light, faith, and the Spirit of Christ,
the heavenly and spiritual Man.
So let none quench the Spirit, or its motions, grieve it, or err from it;
but be led by it, which keeps all in their tents; which giveth an understanding,
how to serve, worship, and please the holy, pure God,
the Maker and Creator in Christ Jesus, and how to wait, speak,
and answer the Spirit of God in his people;
in which Holy Spirit is the holy unity and fellowship.
The Holy Spirit teacheth the holy, gentle, meek, and quiet lowly mind to answer the seed,
that Christ hath sown upon all grounds; and to answer the light, grace, and Spirit,
and the gospel in every creature, though they are gone from the Spirit, grace, light,
and gospel in the heart.
So by holy walking all may come to do it, as well as by holy preaching,
that God in all things may be glorified by you,
and that ye may bring forth fruits to his praise. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 30th of the 10th Month, 1079.

About the latter end of this year I was moved of the Lord to travel into the South again.
I set forward in the beginning of the first month, 1679-80;
and passing through part of Westmorland and Lancashire,
I visited Friends at several meetings, and came into Yorkshire.
Divers large and weighty meetings I had in Yorkshire, before I came to York.
When I came there it was the assize time;
and there being many Friends in prison for truth`'s sake, I put those,
that were at liberty, upon drawing up the sufferings of Friends in prison,
to lay before the judges; and I assisted them therein.
There were then in York many Friends from several parts of the county,
for the quarterly meeting was at that time; so that I had a brave opportunity among them.
Many weighty and serviceable things did the Lord open through me to the meeting,
relating to the inward state of man,
how man by faith in Christ comes to be grafted into him,
and made a member of his spiritual body; and also to the outward state of the church,
how each member ought to walk and act, according to his place in the body.
I spent several days in York, having divers meetings; and all was peaceable and well.
I went also to the castle, to visit Friends that were prisoners;
with whom I spent some time, encouraging and strengthening them in their testimony.

Then leaving York, I travelled southward, having meetings in many places amongst Friends,
till I came to Barton in Lincolnshire; where, on First-day,
I had a large and precious meeting.
Then turning into Nottinghamshire, I travelled through good part of that county,
in which I had several good meetings; and then passed into Derbyshire, Leicestershire,
and Warwickshire, having meetings all along as I went, till I came to Warwick;
there William Dewsbury came to me, and several other Friends,
and we had a little meeting in that town.
Then passing through Southam and Radway,
at each of which places I had a very good meeting,
I came to Nathaniel Ball`'s of North Newton in Oxfordshire,
and so to Banbury to a monthly meeting there.
And after I had visited Friends in the bordering parts of Oxfordshire, Gloucestershire,
and Northamptonshire, I passed to Richard Baker`'s^
footnote:[Richard Baker is described as a man of circumspect life,
and a pattern of good works.
He suffered cheerfully for Christ both the spoiling of
his goods and imprisonment of his body;
and would often say, "`If people did but know the pleasure of godliness,
they would not live in the earth as they did.`"
He was a zealous labourer, a vigilant watchman, a sharp reprover of evil,
an encourager of the good, and a faithful minister,
endeavouring to bring those he ministered to
into an inward exercise of spirit towards God,
and to a greater acquaintance with, and subjection to, the power of God.
Concerning this he wrote a treatise entitled,
_A Testimony to the Power of God, being Greater than the Power of Satan._
{footnote-paragraph-split}
He died in 1697,
having often said in his last sickness,
"`All is well,`" and testified that the power and strength of God was with him.]
of Biddlesdon in Buckinghamshire; and next day, being First-day,
I had a very large meeting in Biddlesdon, at an old abbey-house,
which a Friend rented and dwelt in.
Many Friends and people came to it out of Oxfordshire, Northamptonshire,
and the parts adjacent; and of good service it was.
After this, I visited Friends in those parts, having meetings at Lillingstone, Lovel,
and Bugbrooke.
Then going to Stony-Stratford, I went from thence into some parts of Bedfordshire,
till I came to Edward Chester`'s of Dunstable.
Passing on by Market Street, I had a meeting at Alban`'s;
and calling on Friends at Mims and Barnet, I came to the widow Hayley`'s, at Guttershedge,
in Hendon, Middlesex, on a Seventh-day night,
and had a very large and good meeting there the day following.

I passed thence to London on the Third-day following,
and went directly to the Peel-meeting at John Elson`'s;
and next morning to the meeting at Gracechurch Street, which was very large and quiet;
and Friends rejoiced in the Lord to see me.
The Yearly Meeting was the week following,
to which many Friends came out of most parts of the nation;
and a blessed opportunity the Lord gave us together;
wherein the ancient love was sweetly felt,
and the heavenly life flowed abundantly over all.
After the Yearly Meeting, I continued a month or five weeks in and about London,
labouring in the work of the Lord both in and out of meetings;
for besides the public testimony which the Lord gave me
to bear both to Friends and to the world in meetings,
I had much service upon me, with respect to Friends`' sufferings,
in seeking to get ease and liberty for them in this and other nations.
Much pains and time I spent, while in London,
in writing letters to Friends in divers parts of England, and in Scotland, Holland,
Barbadoes, and several parts of America.

After this I was moved of the Lord to visit Friends in some parts of Surrey and Sussex.
I went to Kingston by water, and tarried certain days; for while I was there,
the Lord laid it upon me to write both to the great Turk,
and the Dey of Algiers severally, to warn them, and the people under them,
to turn from their wickedness, fear the Lord, and do justly;
lest the judgments of God should come upon them, and destroy them without remedy.
To the Algerines I wrote more particularly,
concerning the cruelty they exercised towards Friends and others,
whom they held captives in Algiers.^
footnote:[There appear to have been at this time a number of Friends captured at Algiers.
In the early times of the Society many of its members were seafaring men; and to such,
of whatever religious profession,
it was no uncommon thing to be taken at sea by the Algerines or other _corsairs,_
who continually scoured the Mediterranean,
and ventured occasionally beyond its limits to make prize of merchant ships,
and consign their crews to slavery.
{footnote-paragraph-split}
Great care was exercised towards these captive Friends by the Society,
and efforts made for their redemption.
They are mentioned in the Yearly Meeting epistles of 1682-1687,
and in most of the succeeding ones.
In the epistle of 1698 it is stated,
"`Divers of our Friends who were captives at Mequinez,
and suffered great hardships there, are dead; and there yet remain five,
for whose ransom great endeavours have been used, but it is not yet effected.`"
The epistle of the following year states,
"`Earnest endeavours have again lately been used for the liberty of our Friends,
captives in Barbary, though not as yet obtained;
and there being at this time some negotiations on foot,
by the tenderness and care of the government,
for the redemption of all the English there; and though the persons in Barbary,
employed therein by Friends, do wait some time to see the effect of that,
yet we shall continue our further endeavours for their discharge,
and in the meantime take care to send them supplies for food,
they having little allowance in that country, of anything to support their bodies,
under the great severities of labour, and undeserved stripes,
that captives often endure.`"
{footnote-paragraph-split}
In the epistle of 1702 the conclusion of the Barbary captives is stated,
namely, that five Friends, being all who remained alive in that long and sore captivity,
_have been this year redeemed,_
whose ransom (including a Friend`'s son from Pennsylvania) cost
the Society upwards of 480. The redeemed tenderly and
gratefully acknowledged Friends`' love and care of them.]
When I had finished that service, and visited Friends in their meetings at Kingston,
I went further into the country, and had meetings amongst Friends at Worplesdon,
Guildford, Esher, Capel, PatchGate, Worminghurst, Bletchington, Horsham, Ifield, Reigate,
Gatton, etc., and so came back to Kingston again; and thence to Hammersmith.
And having spent some days in the service of truth amongst Friends at Hammersmith,
Battersea, Wandsworth, and thereabouts, I crossed over, by Kensington, to Hendon,
where I had a very good meeting on a First-day; and went thence to London.

When I had been about ten days in London,
I was drawn again to visit Friends in the country; and went to Edmonton,
to Christopher Taylor`'s, who kept a school for the educating of Friends`' children.
I had some service here amongst the youth; and then went towards Hertford,
visiting several Friends on the way.
At Hertford I met with John Story, and some others of his party;^
footnote:[A schism, of which Story and Wilkinson were at the head,
is frequently referred to in the writings of some of the early Friends.
It commenced and spread mostly in the north.
There were, however, those in London, Bristol, and some southern counties, who,
through ease and unwatchfulness, having lost their first love and the discerning spirit,
were deceived by a specious bait,
and became the cause of much exercise and trouble to their brethren.
{footnote-paragraph-split}
The ground of difference was alleged by them to be,
their objection to those meetings for regulating the affairs of the church,
exercising a salutary discipline over its members;
and more especially against the establishment of women`'s meetings,
which G. Fox and other Friends "`were moved to set up.`"
They stated, with a show of plausibility which gained some, chiefly the looser sort,
to their ranks, "`That such meetings were needless,
some years having been passed in peace and unity without them;
and that every individual ought to be guided by the Spirit, and left free to act;
that meetings for discipline were a form,
and the exercise of that discipline an infringement upon individual liberty.`"
Great endeavours were made for their enlightenment and restoration.
In 2d Month 1676, a meeting was held at Drawell, which lasted four days,
in which "`many Friends laboured much for their preservation,
but they were too far gone in a separate spirit to be reclaimed.`"
They, therefore, became out of unity with the body who, "`walking by the same rule,
minded the same thing.`"
They fell to jangling, and, after a while,
the best among them came to see how they had been deceived; and the rest,
after having had separate meetings,
are said to have "`vanished as snow in the fields.`"--See Sewell`'s _History,_
folio edition, pp. 583, 584.]
but the testimony of truth went over them, and kept them down,
so that the meeting was quiet.
It was on a First-day; and the next day being the men`'s and women`'s meeting for business,
I visited them also, and the rather,
because some in that place had let in a disesteem of them.
Wherefore I was moved to open the service of those meetings,
and the usefulness and benefit thereof to the church of Christ,
as the Lord opened the thing in me; and it was of good service to Friends.
I had a meeting also with some of those, that were gone into strife and contention,
to show them wherein they were wrong; and having cleared myself of them,
I left them to the Lord.
Then, after another public meeting in the town,
I returned towards London by Waltham Abbey,
where I had a public meeting on the First-day following;
and another with Friends in the evening.
Next day I went to Christopher Taylor`'s at Edmonton, and stayed there a day or two,
having some things upon me to write, which were for the service of truth.
When I had finished that service, I went to London by Shacklewell,
where was a school kept by Friends,
for the bringing up of young women that were Friends`' daughters.

I abode at London most part of this winter, having much service for the Lord there,
both in and out of meetings: for as it was a time of great suffering among Friends,
I was drawn in spirit to visit Friends`' meetings more frequently;
to encourage and strengthen them both by exhortation and example.
The parliament also was sitting, and Friends were diligent in waiting upon them,
to lay their grievances before them.
We received fresh accounts almost every day of the sad
sufferings Friends underwent in many parts of the nation.
In seeking relief for my suffering brethren I spent much time;
together with other Friends, who were freely given up to that service,
attending at the parliament-house for many days together,
and watching all opportunities to speak with such members of either house,
as would hear our just complaints.
And indeed, some of these were very courteous to us,
and appeared willing to help us if they could;
but the parliament being then earnest in examining the Popish plot,
and contriving ways to discover such as were Popishly affected,
our adversaries took advantages against us (because they knew we could not swear
nor fight) to expose us to those penalties that were made against Papists;
though they knew in their consciences that we were no Papists,
and had had experience of us, that we were no plotters.
Wherefore, to clear our innocency, and to stop the mouths of our adversaries,
I drew up a short paper, to be delivered to the parliament; as follows:--

[.small-break]
'''

"`It is our principle and testimony,
to deny and renounce all plots and plotters against the king, or any of his subjects;
for we have the Spirit of Christ, by which we have the mind of Christ,
who came to save men`'s lives, and not to destroy them.
We desire the safety of the king and of all his subjects.
Wherefore we declare, that we will endeavour, to our power,
to save and defend him and them,
by discovering all plots and plotters (which shall come to our
knowledge) that would destroy the king or his subjects.
This we do sincerely offer unto you.
But as to swearing and fighting, which in tenderness of conscience we cannot do,
ye know that we have suffered these many years for our conscientious refusal thereof.
And now that the Lord hath brought you together, we desire you to relieve us,
and free us from these sufferings; and that ye will not put upon us to do those things,
which we have suffered so much and so long already for not doing; for if you do,
you will make our sufferings and bonds stronger, instead of relieving us.`"

[.signed-section-signature]
G+++.+++ F.
