== Chapter X.

[.chapter-synopsis]
* 1681-1683.
* George Fox answers two envious books written abroad
* writes to magistrates to persuade them to moderation
* writes to the Quarterly Meetings
* attends the judges at Chambers, respecting a tithe-suit against himself and his wife
* George Fox had bound himself not to intermeddle with his wife's estate
* this is shown to the judges in court, at which they wonder
* his counsel thereon founds an argument in his favour
* he again writes against the spirit of strife and division in the church
* writes to the magistrates who had illegally condemned Friends upon ex-parte evidence
* writes two papers respecting the choice of sheriffs
* Friends are interrupted at Gracechurch Street Meeting by a civil and military force
* George Fox writes divers books and papers in support and defence of the Truth
* the Spirit of God directed to as the rule to distinguish between Truth and error, whereby the evil of persecution may be avoided
* an epistle to encourage Friends under their sufferings, both from the outward powers, and from false brethren
* the laws are now more strictly enforced against Dissenters
* an epistle to Friends, commending them to the power of God in themselves
* writes to Friends imprisoned at Denbigh, to console them in their sufferings, and exhorting them to faithfulness
* Friends are kept out of their meeting-houses, and fined for speaking
* a Friend is speedily restored from a sudden illness, in a remarkable manner, through the prayers of George Fox
* persecution is now hot, and George Fox writes to Friends not to risk the loss of other people's goods through their sufferings.

About this time I received two very envious books, written against Truth and Friends;
one of them by a doctor (so called) of Bremen, in Germany,
the other by a priest of Dantzic.
They were both full of gross falsehoods, and reproachful slanders.
I found it upon me to answer them both;
and that I might not be much interrupted therein by other business and company,
I went to Kingston-upon-Thames, where I wrote an answer to each of them;
and also to some other scandalous papers,
which had been printed and scattered about to misrepresent Friends.

While I was there I wrote also the following paper,
to persuade the magistrates to moderation towards Dissenters,
and take off their edge to persecution.
That it should have its full service, I directed it--

[.blurb]
=== "`To all the Rulers, Magistrates, and Law-makers in England, Scotland, and Ireland, from the highest to the lowest; and to all other Magistrates everywhere, in that which is called Christendom; desiring their health, peace, tranquillity, life, and salvation in Christ Jesus, the Lord of Glory, and Lamb of God, who takes away the sins of the world, who is the King of kings, and Lord of lords, to whom all power in heaven and in earth is given; and who will reward every man according to his words and works.

"`You that bear the name of Christian magistrates, my desire is,
that you may all be found in Christ; and not only have the name,
but be made partakers of his divine nature; that ye may be not only sayers,
but doers of the word; not only professors and talkers of Christ,
but letting him rule in your hearts by faith, and be walkers in Christ.
For as his great apostle saith, 'As every one hath received the Lord Jesus Christ,
so let him walk in him; for in him there is peace.'
If all that profess Christ, did walk in Christ, they would walk in peace,
and be in unity;
for the apostle exhorted the Christians in his day to keep the unity of the Spirit;
which is the bond of peace, yea, of Christ the King of kings' peace.
All Christians, who have the Scriptures, and are not in this Spirit of Christ,
are not in unity one with another; and so have broken this bond of peace,
which should knit and unite them together.
Likewise all that profess the truth of Christ, should live in it; for it is peaceable,
and the gospel is the gospel of peace; which, if all Christians lived in,
they would be at peace one with another, and in the glorious fellowship of the gospel.
And if all Christians kept in the fear of God, which is the beginning of the pure,
heavenly, peaceable, and gentle wisdom, which is easy to be entreated (above that wisdom,
which is earthly, sensual, devilish, and destroying),
there would be no difference and destroying about matters of religion.

"`I do declare the mighty day of the Lord is come and coming;
and the Lord God is come to teach his people himself by his Son, Heb. 1,
who bruises the serpent's head, that false teacher,
that led Adam and Eve from God their Teacher.
God will teach his people by his Son, who was the Teacher of Adam and Eve in paradise,
before they fell and disobeyed the Lord, forsook him, and followed the serpent;
whose head Christ bruises, and renews man and woman up again into the image of God,
which Adam and Eve were in before they fell:
glory and honour be to God through Jesus Christ,
who hath called us by his Son into his glorious image,
to serve and worship him in Spirit and truth;
which Holy Spirit and truth the devil is out of, and into which he cannot come.

"`I desire all Christian magistrates to take heed of persecuting any,
though they differ from you in matters of faith, worship, and religion.
For Christ saith,
'Let the tares and the wheat grow together till the harvest;'
and he forbade such as would be plucking up tares:
the reason was, 'lest they should pluck up the wheat also;' for Christ said,
it should be his angels' work, to separate the tares from the wheat.
Moreover, Christ said,
they should go into everlasting punishment that
did not visit him in prison in his members:
then what will become of them that cast him into prison,
where he is made manifest in his members!
O, lay these things to heart!
A day of judgment will come,
vengeance and recompense upon every one according to his works.

"`To those disciples who would have had fire to come down from
heaven to consume them that would not receive them,
Christ turned him about, rebuked them, and told them,
'they knew not what spirit they were of; for he came not to destroy men's lives,
but to save them.'

"`Therefore, let all magistrates and priests in that which is called Christendom,
consider who have destroyed men's lives since the apostles' days,
because they could not receive the religions, ways,
and worships which they have made and set up:
have they known what spirit they have been of?
Are they not all reproved by, and come under the judgment of Christ?
Therefore let all persecution be laid aside concerning religion; let love bear the sway,
to overcome evil and enemies; and let patience oversway passion in all,
that all may retain the heavenly reason,
and the pure understanding,--that your moderation in
true Christianity may be known to all men.
For have you not the Turks, Jews, Tartars, Indians, and atheists' eyes upon you,
and upon Christendom.
Therefore be in unity,
and let not the name of God and Christ be blasphemed amongst
them by means of any that bear the name of Christians.
So God may be glorified by all and in all, through Jesus Christ, who is over all,
who calls all to peace, and is blessed for ever.

"`I would have you to be as noble as the Bereans,
and search the Scriptures of Christ and the apostles.
Where did he or they give any command to imprison, banish, persecute, or put to death,
any that would not receive or conform to them,
or that were contrary-minded to them in religion,
or differed from them in matters of worship.

"`Again, I desire all Christian magistrates to search both Scriptures and Chronicles,
and see what was the end of all persecutors, and what judgments came upon them.
What came to Cain, who was the first persecutor for matters of faith and sacrifice?
Did not he become a vagabond and a fugitive in the earth?
What became of the old world, that grieved God, and Noah, a preacher of righteousness?
What became of Sodom, that vexed just Lot?
What became of Pharaoh,
that persecuted God's people in Egypt (though the more he persecuted
them the more they grew)? What became of Ahab and Jezebel,
that persecuted the Lord's prophets?
And what became of Haman, that would have destroyed the Jews?
What became of the Jews and Jerusalem, that persecuted Christ and the apostles?
What was the end of all these?
Are they not become vagabonds in the earth, and driven away from their native country?
Therefore I beseech you in the love and fear of God,
be so noble as to search both Scripture and history,
and let not your divine understanding be clouded.
What will become of the beast and whore spoken of in the Revelations,
with their false prophets, that have drunk the blood of the saints, martyrs,
and prophets of Jesus?
Must they not all go with the devil, who is a murderer, destroyer,
and adversary of mankind, into the lake of fire, that burns with brimstone?
And ye may be sure that spirit that stirs you up to persecution,
let it be in whomsoever it will, is not of Christ, and of his lamb-like nature;
who takes away the sins of the world, not the lives of men.

"`Paul was a persecutor, and a haler to prison,
before he was converted to Christianity; but never after.
And therefore, are not all in Saul's nature,
let them be of what name or profession soever, that are persecutors,
and unconverted into Paul's life of Christianity?
He said, the life that he lived after he was converted,
was 'by the faith of the Son of God;' and that he lived, yet not he,
but 'Christ lived in him,' who came to save men's lives, and not to destroy them.
This life should be the life of all Christians now,
which Paul in his converted state lived in.
And the apostle saith, 'The law is good if a man use it lawfully; knowing this,
that the law is not made for a righteous man, but for the lawless and disobedient,
for the ungodly, and for sinners, for unholy and profane,
for murderers of fathers and murderers of mothers, for man-slayers, for whoremongers,
for them that defile themselves with mankind, for men-stealers, for liars,
and for perjured persons,' 1 Tim. 1:8-10.
So the law, in its place, is good against such.
Again the apostle says,
'The law was added because of transgression,' Gal. 3:19.
Here all magistrates may see what the law in its place is good against;
what it was made for and against; and what evils, the apostle says, it takes hold of.
He does not say the law should be laid upon men that
differed from them in their religion and judgment,
nor upon righteous men.
So you may see in what condition the law is good, and what it was made against;
not against righteous men, against whom ye have nothing in their lives and conversations,
only because they differ from you in matters of religion; letting man-slayers,
whoremongers, perjured persons, ungodly, profane persons, liars, etc., go unpunished;
such do not use, nor execute the law lawfully, as the apostle says, 'The law is good,
if a man use it lawfully.'
Therefore it ought to be used lawfully; which law, the apostle says,
'is for the punishment of evildoers, and a praise for them that do well;' as may be seen,
Rom. 13.
So, as the apostle said, 'We do not break the law, nor make it void;
but we establish the law,' Rom. 3:31.

"`This is from him who desires the eternal good and salvation of you all in Christ Jesus.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston-upon-Thames, the 4th of the 1st Month, 1680-1.

After I had finished these services I returned to London, where I stayed about a month,
labouring amongst Friends in the work of the Lord, both in public meetings for worship,
and in those relating to the outward affairs of the church.
Then feeling my spirit drawn to visit Friends about Enfield, I went to Waxtham Abbey,
where I had a very precious meeting; and another at Flamstead Heath.
Having spent some time among Friends thereabouts,
and had divers good meetings at Edmonton, Enfield, Winchmore-Hill, and other places,
I came back to London a little before the Yearly Meeting, which was in the 3rd month,
1681.
It was a very precious time,
in which the glorious presence and power of the Lord was eminently felt and enjoyed.

[.offset]
Some time after the Yearly Meeting it came upon me to write the following epistle:--

[.blurb]
=== "`To the Men's and Women's Quarterly Meetings that are gathered in the name and power of Jesus.

"`Christ, the second Adam, who is both Head and Husband of his church, the Redeemer,
Purchaser, Saviour, Sanctifier,
and Reconciler of his sons and daughters (his church) to God, I say,
his presence (to wit, Christ's) feel among you, to exercise his prophetical office,
in opening you with his light, grace, truth, power, and Spirit;
and to exercise his office, as he is a Bishop, to oversee you with his light, grace,
power, and Spirit, that ye do not go astray from God.
And as Christ is a Shepherd, feel, see, and hear him exercising that office,
who laid down his life for his sheep, feeding them in his living pastures of life,
and making them to drink of his living, eternal springs.
Let Him rule and govern in your hearts, as he is King,
that his heavenly and spiritual government all may live under,
as true subjects of his righteous, peaceable kingdom, which stands in righteousness,
peace, joy in the Holy Ghost, over Satan and his power, and all unrighteousness.
So all ye subjects to Christ's kingdom of peace, if ye want wisdom, or knowledge, life,
or salvation, Christ is the treasure; feel Him the treasure among you.
And all, as ye have received Christ, walk in him, in whom ye have peace;
who bruises the head of the serpent, the author of all strife, distraction,
and confusion: yea, you have peace with God, and one with another,
though the trouble be from the world and the world's spirit.
Therefore, my dear Friends, brethren and sisters,
love one another with the love that is of God shed in your hearts;
that ye may bear the marks of Christ's disciples,
and it may appear that Christ is in you, and ye in Him;
so that God Almighty may be glorified among you.
Whatever ye do, let it be done in the name of Jesus, to the praise of God the Father,
keeping in unity in the Holy Spirit of God, which was before the unholy spirit was:
which Holy spirit is your bond of peace, yea,
the Holy King of kings' and Lord of lords' peace.
And in this holy, pure Spirit is your eternal unity and fellowship;
in which ye serve and worship the God of Truth, who is over all, blessed for ever, Amen.
So the Lord guide you all with his Word of patience, life, power, and wisdom,
in all your actions, lives, conversations, and meetings, to God's glory.
My love to you all in the Lord Jesus Christ, by whom all things were made,
and who is overall, the First and the Last.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 9th of the 4th Month, 1681.

About this time I had occasion to go to several
of the judges' chambers upon a suit about tithes.
For my wife and I and several other Friends,
were sued in Cartmel-Wapentake Court in Lancashire, for small tithes,
and we had demurred to the jurisdiction of that court.
Whereupon the plaintiff prosecuted us in the Exchequer Court at Westminster,
where they run us up to a writ of rebellion, for not answering the bill upon oath;
and got an order of court to the sergeant, to take me and my wife into custody.
This was a little before the Yearly Meeting,
at which time it was thought they would have taken me up;
and according to outward appearance, it was likely,
and very easy for him to have done it, lodging at the places where I used to do,
and being very public in meetings.
But the Lord's power was over them, and restrained them; so that they did not take me.
Yet understanding there was a warrant out against me,
as soon as the Yearly Meeting was over, I took William Mead with me,
and went to several of the judges' chambers to speak with them about it;
and to let them understand both the state of the case,
and the ground and reason of our refusing to pay tithes.
The first I went to was Judge Gregory,
to whom I tendered mine and my wife's answer to the plaintiff's bill;
in which was set forth, that she had lived three and forty years at Swarthmore,
and in all that time there had been no tithe paid or demanded: and an old man,
who had long been a tithe-gatherer, had made affidavit,
that he never gathered tithe at Swarthmore-Hall in Judge Fell's time, or since.
There were many particulars in our answer, but it would not be accepted without an oath.
I told the judge that both tithe and swearing among Christians came from the Pope,
and it was matter of conscience to us not to pay tithes, nor to swear;
for Christ bid his disciples, who had freely received, give freely;
and he commanded them "`not to swear at all.`"
The judge said, there was tithe paid in England before Popery was:
I asked him by what law or statute they were paid then; but he was silent.
Then I told him,
there were eight poor men brought up to London out of
the North about two hundred miles for small tithes,
and one of them had no family but himself and his wife,
and kept no living creature but a cat.
I asked him also, whether they could take a man and his wife,
and imprison them both for small tithes, and so destroy a family; and if they could,
I desired to know by what law: he did not answer me, but only said,
"`that was a hard case.`"
When I found there was no help to be had there, we left him,
and went to Judge Montague's chamber;
and with him I had much discourse concerning tithes.
Whereupon he sent for our adversary's attorney; and when he came I offered him our answer.
He said, if we would pay the charges of the court, and be bound to stand trial,
and abide the judgment of the court, we should not have the oath tendered to us.
I told him that they had brought those charges upon us,
by requiring us to put in our answer upon oath:
which they knew before we could not do for conscience' sake;
and as we could not pay any tithe nor swear,
so neither should we pay any of their charges.
Upon this he would not receive our answer.
So we went from thence to Judge Atkyns's chamber, and he being busy,
we gave our answers and our reasons against tithes and swearing to his clerk;
but neither could we find any encouragement from him to expect redress there.
Wherefore leaving him we went to one of the most noted counsellors,
and showed him the state of our case and our answers: he was very civil to us, and said,
"`this way of proceeding against us was somewhat like an inquisition.`"
A few days after, those eight poor Friends that were brought up so far out of the North,
appeared before the judges; and the Lord was with them, and his power was over the court,
so that the Friends were not committed to the Fleet.
Our cause was put off till the next term (called Michaelmas),
and then it was brought before the four judges again.
Then William Mead told the judges that I had engaged not to meddle with my wife's estate.
The judges could hardly believe that any man would do so:
whereupon he showed them the writing under my hand and seal, at which they wondered.
Then two of the judges and some of the lawyers stood up, and pleaded for me,
that I was not liable to the tithes: but the other two judges and divers lawyers,
pressed earnestly to have me sequestered; alleging that I was a public man.
At length they prevailed with one of the other two judges to join with them;
and then they granted a sequestration against me and my wife together.
Thereupon, by advice of counsel, we moved for a limitation, which was granted,
and that much defeated our adversary's design in suing out the sequestration;
for this limited the plaintiff to take no more than was proved.
One of the judges, Baron Weston, was very bitter,
and broke forth in a great rage against me in the open court; but shortly after he died.

After the Yearly Meeting, I tarried about a month in London; and then went into Sussex,
to visit Friends there,
amongst whom I had many large and very precious meetings in divers parts of that county.
Yet I spent not much time now in Sussex, but returned pretty soon to London,
whither I felt drawings in spirit; and had very good service for the Lord there,
both in public meetings and amongst Friends.
When I had tarried some time in London, I went to Edmonton; thence into Buckinghamshire,
where I visited Friends at several meetings in that county:
and then went by Henley to Reading, where I tarried several meetings.
I went no farther westward at this time than to Ore, where I had a very large meeting;
after which, striking through the edge of Oxfordshire,
I had a large and very precious meeting at Warborough,
in which the glory of the Lord shone over all.
Many Friends came to it out of Berkshire, Buckinghamshire, and Hampshire.
Thence I passed to Ilmore in the vale of Buckinghamshire,
where we had a glorious meeting; and the day following I returned to Mary Penington's,
visiting the men's and women's monthly meetings at Hunger-hill,
and some other meetings thereabouts; and then passed to Watford,
where was a marriage of two Friends, at which I was present.
A very large meeting we had on that occasion, and the Lord's power was over all.
I went from Watford to Longford in Middlesex, visiting Friends at Uxbridge in the way.
At Longford we had a large meeting on First-day,
and the presence of the Lord was preciously felt amongst us; blessed be his name!
I passed from Longford to Kingston, visiting Friends as I went, at Staines and Suneury.
At Kingston I abode with Friends two meetings,
wherein we were sweetly refreshed together in the Lord.
Passing thence towards London, I had a very precious meeting at Wandsworth:
then crossing over to Hammersmith, I had a good meeting there,
which was larger on account of a burial; and there being openness in the people,
I had a fine opportunity to open the way of truth amongst them.

[.offset]
After I was come to London, I was moved to write the following paper,
concerning that spirit which had led some, who professed truth, into strife and division,
and to oppose the way and work of the Lord:--

[.salutation]
"`Friends,

"`You that keep your habitations in the truth, that is over all,
see that it is the same spirit that leads the backsliders and apostates now,
from the spiritual fellowship and unity of God's people, and the church of Christ,
that led Adam and Eve from God, and the Jews from God and his law,
to rebel against his Spirit.
This spirit is the same that was in the world, which got into the Jews,
when they were gone from the Spirit of God;
and then they turned against God and his prophets, and against Christ and his apostles.
This spirit led them to be as bad as Pilate, or worse.
The enmity or adversary got within them against the truth, and them that walked in it,
and the Spirit of the Lord; so that they killed and destroyed the Just.
This was the spirit of the devil, the destroyer,
who sought not only to destroy the truth, but the order of it,
and them that walked in it,
when true Christianity was planted among the possessors of the light, grace, and truth,
and the holy gospel faith and Spirit, who enjoyed Christ in their hearts.
But when some began to err from the Spirit and faith, to hate the light,
disobey the gospel, turn the grace of God into wantonness,
walk despitefully against the Spirit of Grace, turn from the truth,
crucify to themselves Christ afresh, and put him to open shame; these were they,
that let in the spirit of the world; who held the form of godliness,
but denied the power thereof; and troubled the churches in the apostles' days.
When the spirit of Satan had got into such,
they were more troublesome to the church than the open persecutors that were without:
these got into the assemblies to deceive the hearts of the simple, having the good words,
fair speeches, and sheep's clothing.
Paul, Peter, John, Jude, and James had much to do with such,
to keep them from troubling the church of Christ;
for they are out of the light, power, and Spirit;
therefore the apostles of Christ exhorted the saints to keep to the Word of life within;
to the anointing; to the grace, truth, and Holy Spirit in their hearts.
This foul spirit will profess all the Scriptures in words; but by the Spirit of God,
which is holy, this spirit is tried, and its fruits.
So the apostates went from the power and Spirit of God, and turned against the prophets,
and the martyrs of Jesus; and became the whore, whose cup all nations drank of.
The dragon with his tail threw down many of the stars,
and would have devoured the woman with his flood; but the woman, the true church,
was preserved; for the gates of hell cannot prevail against her;
and then the dragon made war with her seed.
So the dragon, the whore, the beast, and false prophets,
all made war against the Lamb and the saints;
but the Lamb and the saints will overcome them all, and will have the victory.
And now the everlasting gospel is preached again to all nations, tongues, and peoples;
and many are gathered into the gospel, the power of God, are turned to the light,
which is the life in Christ, are grafted into him,
and are come to walk in the order of the new covenant of light and life,
in the gospel of peace and salvation.
The same spirit that opposed the apostles and the churches in their days, opposes now;
yea, it is the same that opposed Christ, and disdained him,
that disdaineth God's servants now.
The same that opposed the prophets, and rebelled against Moses,
opposes and rebels against God's servants and people now.
It is the same dark, blind, disobedient, faithless, wilful, jealous spirit,
that persecutes some with the hands, and others with the tongue.
It is the same spirit of enmity, the adversary and destroyer,
that tempted Adam and Eve to disobey God, and deceived them;
which deceived the Jews and tempted them,
and deceived all those that went from the church in the apostles' days.
And it is the same spirit that is now going about sometimes like a roaring lion,
sometimes like a twisting serpent to tempt, to deceive, and to devour,
in those who have fair speeches, good words, and sheep's clothing,
in a form of godliness, and under pretence of light and liberty,
but who deny the power thereof, and inwardly are ravening wolves;
and if it were possible, they would deceive the very elect.
But the elect are in the covenant of light and life, and in the power of God over them,
and in Christ, who will grind them to pieces;
and will slay all his enemies with his spiritual sword,
who will not have him to rule over, or in them.
In Christ all his people have rest and peace,
who is their sanctuary over all storms and tempests.
In Christ, the sanctuary, no deceiver nor destroyer can come;
for he is a place of sweet rest and safety.
Hallelujah! praise the Lord for his sanctuary. Amen.`"

[.signed-section-signature]
G+++.+++ F.

Sufferings continuing severe upon Friends at London, I found my service lay mostly there;
wherefore I went but little out of town, and not far;
being frequent at the most public meetings, to encourage Friends,
both by word and example, to stand fast in the testimony to which God had called them.
At other times I went about from house to house,
visiting Friends that had their goods taken away for their testimony to truth.
And because the wicked informers were grown very audacious,
by reason that they had too much countenance and encouragement from some justices, who,
trusting wholly to their information, proceeded against Friends without hearing them;
whereby many were made to suffer, not only contrary to right,
but even contrary to law also; I advised with some Friends about it;
and we drew up a paper,
which was delivered to most of the magistrates in and about the city;
which was as follows:--

"`Whereas informers have obtained warrants of some justices of peace,
who have convicted many of us without a hearing,
or once summoning us to appear before them;
by which proceedings many have had their goods seized and taken away,
being generally fined ten pounds each for an unknown speaker:
and some of those persons so fined, have not been at the meetings they were fined for;
and the speaker notwithstanding has himself been fined for the same meeting,
the same day the others were fined for the unknown speaker.
By this the justices may see the wickedness of these informers,
by whose false oaths we have been convicted for an unknown preacher,
when the preacher has been both known and fined.
Also in their swearing such persons to have been at such a meeting such a day,
when indeed they, whom they have so sworn against, have not been at that meeting.
By which proceedings several families of the king's
peaceable subjects are likely to be ruined,
if a speedy stop be not put thereunto.
Therefore we hope and desire, that you, the king's justices, for the time to come,
when any informers shall come to any of you with information against any of us,
will summon such as are accused to appear before you,
and hear us and our accusers face to face;
that none for the time to come may suffer for that they are not guilty of.
For Pilate the governor heard Christ and his accusers, face to face,
before he condemned him, John xix.
The council and chief priests heard Stephen and his accusers,
with the witnesses that were brought against him, face to face,
before they condemned him, Acts vii.
The Roman captain heard Paul and his accusers face to face, Acts xxiii.
Felix the governor heard Paul, and Ananias the high priest,
and the elders that accused Paul, face to face, Acts xxiv.
And when the high priests and chief of the Jews accused Paul to Festus,
he heard Paul and his accusers, and them that witnessed against him, face to face,
Acts xxv.
Doth the law of God, or did the Roman law, or doth the law of the land judge any man,
before he and his accusers, and they that witness against him, be heard face to face?`"

This somewhat moderated the justices; and after this several Friends,
that had been illegally prosecuted and fined, entered their appeals;
and upon trial were acquitted, and the informers cast:
which was a great discouragement to the informers, and some relief to Friends.

[.offset]
A little before the time for choosing new sheriffs for the city,
they who put up to be chosen desiring our Friends to give their voices for them,
I wrote a few lines, tending to discover what spirit they were of,
and how they stood affected to true liberty; and it was by way of inquiry, thus:--

"`Do any here in London, who stand to be chosen sheriffs, own that Christ,
that was crucified without the gates of Jerusalem, to be the light of the world,
that 'enlightens every man that cometh into the world' who saith, 'Believe in the light,
that ye may become children of light?'
Are any of you against persecuting people for their
religion and worship of God in Spirit and in truth, as Christ commandeth?
For Christ said, 'I am not of this world,
nor my kingdom;' therefore he doth not uphold his spiritual
worship and pure religion with worldly and carnal weapons.
Christ said, 'Swear not at all;' and his apostle James saith the same;
but will not you force us to swear, and so to break Christ's and his apostle's commands,
in putting oaths to us?
Christ saith to his apostles, 'Freely ye have received, freely give.'
Will not you force us to give tithes and maintenance to
such teachers as we know God hath not sent?
Shall we be free to serve and worship God, and keep his and his Son's commands,
if we give our voices freely for you?
For we are unwilling to give our voices for such as will imprison and persecute us,
and spoil our goods.`"

But whatever they were that stood to be chosen,
I observed heat and strife in the spirits of the people that were to choose;
wherefore I wrote a few lines to be spread amongst them, directed thus:--

[.blurb]
=== "`To the People who are choosing Sherifs in London.

"`People,--All keep in the gentle and peaceable wisdom of God,
which is above all that which is earthly, sensual, and devilish;
and live in that love of God that is not puffed up, nor is unseemly; which envieth not,
but beareth and endureth all things.
In this love ye will seek the good and peace of all, and the hurt of no man.
Keep out of all heats, and be not hot-headed; but be cool and gentle,
that your Christian moderation may appear to all men; for the Lord is at hand,
who beholds all men's words, thoughts, and actions,
and will reward every one according to his works; and what every man soweth,
that shall he reap.`"

[.small-break]
'''

Now I had some inclination to go into the country to a meeting,
but hearing that there would be a bustle at our meetings,
and feeling a great disquietness in people's
spirits in the city about choosing sheriff's,
it was upon me to stay in the city,
and go to the meeting in Gracechurch Street upon the First-day of the week,
William Penn went with me, and spoke; and while he was declaring the truth to the people,
a constable came in with his great staff, and bid him give over, and come down;
but he continued, declaring truth in the power of God.
After a while the constable drew back, and when William Penn had done, I stood up,
and declared to the people the everlasting gospel,
which was preached in the apostles' days, and to Abraham;
and which the church in the apostles' days received, and came to be heirs of.
This gospel, I declared, was sent from heaven by the Holy Ghost in the apostles' days,
and is so now; and was not of man, neither by man;
but by the revelation of the Holy Ghost.
And now this gospel is preached again (as John saw,
and said it should be) to all nations, tongues, and people;
and all people now are to hear Christ the prophet,
in this his gospel of the new covenant.
For as Moses said, 'Like unto me will God raise up a prophet,
and Him shall ye hear in all things;' so, said I, this prophet, Christ, is come,
and all the Jews in spirit, the true believing Christians in the light,
who have the law of God written in their hearts, and put into their minds,
are to hear Christ in his gospel, new testament, and new covenant,
which is the law of the spirit of life in Christ Jesus,
who bruises the serpent's head (which is the head of enmity),
and makes free from the law of sin and death.
I showed, that all whom Christ quickens and makes alive,
he makes to sit together in the heavenly places in himself.
So that they do not wander up and down, like the fool's eye, in the corners of the earth;
nor are their eyes abroad in the world,
to sit down in the world's invented seats of religion; but they sit together in Him,
as the saints did in the apostles' days.
So Christ was and is their treasure of wisdom, life, knowledge, and salvation.`"
As I was thus speaking, two constables came in with their great staves,
and bid me give over speaking, and come down; but, feeling the power of the Lord with me,
I spoke on therein, both to the constables and to the people.
To the constables I declared, "`that we were a peaceable people,
who meet to wait upon God, and worship him in Spirit and in truth;
and therefore they needed not to come with their staves amongst us,
who were met in a peaceable manner,
desiring and seeking the good and salvation of all people.`"
Then turning my speech to the people again, I declared what further was upon me to them;
and while I was speaking, the constables drew out towards the door;
and the soldiers stood with their muskets in the yard.
When I had done speaking, I kneeled down and prayed,
desiring the Lord to open the eyes and hearts of all people, both high and low,
that their minds might be turned to God by his Holy Spirit;
that he might be glorified in all and over all.
After prayer the meeting rose, and Friends passed away;
the constables being come in again, but without the soldiers; and indeed,
both they and the soldiers carried themselves civilly.
William Penn and I went into a room hard by, as we used to do,
and many Friends went with us; and lest the constables should think we would shun them,
a Friend went down and told them, that if they would have anything with us,
they might come where we were, if they pleased.
One of them came to us soon after, but without his staff; which he chose to do,
that he might not be observed; for he said,
the people told him he busied himself more than he needed.
We desired to see his warrant; and therein we found, that the informer was one Hilton,
a North-countryman, who was reputed to be a Baptist.
The constable was asked, whether he would arrest us by his warrant on that day;
it being the First-day of the week, which in their law was called the Lord's day;
he said, he thought he could not.
He told us also, that he had charged the informer to come along with him to the meeting,
but he had run away from him.
We showed the constable that both he and we were clear;
yet to free him from all fear of danger,
we were free to go to the alderman that granted the warrant.
Then a Friend that was present said,
he would go with the constable to speak with the alderman; which they did,
and came presently back again, the alderman being gone from home.
Seeing the constable in a strait, and finding him to be a tender man,
we bid him fix an hour to come to us again, or send for us, and we would come to him.
So he appointed five in the afternoon; but neither came, nor sent for us;
and a Friend meeting him afterwards in the evening, the constable told him,
he thought it would come to nothing, and therefore did not look after us.
So the Lord's power was over all; to him be the glory!

On the Fourth-day following, it was upon me to go to Gracechurch Street meeting again;
for I had heard that they would come to break it up that day.
The neighbours, it seems, were informed so;
a justice had granted a warrant for that purpose, and the constable told a Friend,
that Hilton the informer had been with him about it.
The constable would have had the informer to go with him to the meeting,
but he would not; but would have the constable to go without him;
whether that put the constable by, I know not; but he did not come.
I was in a travail of spirit in the power of God,
and was moved in it to go to the meeting; and the Lord's power chained all down.
Though they threatened to bring the red coats, none came, nor was there any disturbance;
but a glorious, powerful meeting it was, and very peaceable.
Glory, honour, and praises be to the Lord over all for ever. Amen!

During the time I thus abode at London, as I had leisure between meetings,
and from other public services, I wrote divers books and papers,
some of which were printed, and others spread about in manuscript.
Of these, one was directed "`To the bishops and others, that stirred up persecution;
to show them from the Holy Scriptures that they
did not walk therein according to the royal law,
'to love their neighbour as themselves,
and to do to others as they would be done unto.'`" Another was,
"`To all the several sorts of professed Christians, as well Protestants as Papists,
whose religion and worship stand in outward observances and ceremonies;
pressing them from those words of the apostle Paul to the Galatians, chap, v. ver.
2-4, 'Behold, I Paul say unto you, that if ye be circumcised,
Christ shall profit you nothing.
For I testify again to every man that is circumcised,
that he is a debtor to the whole law.
Christ is become of no effect unto you, whosoever of you are justified by the law;
ye are fallen from grace,' to consider whether they,
being gone back into legal observations and shadowy ceremonies (in upholding tithes,
offerings, first-fruits, priests' garments, outward altars, temples, lamps, lights, etc.,
and in observing days, months, times, years,
with many other things commanded by the law),
were not gone into the same state that the Galatians were running into;
and so were fallen from grace, and become debtors to do the whole law.`"
Another was, "`To direct and turn all people to the Spirit of God,
that they might thereby receive a right understanding,
and be able to distinguish between right and wrong, truth and error;
that under pretence of punishing evil-doers,
they might not themselves do evil in persecuting the righteous.`"
That paper, being short, is here inserted:--

"`The Spirit of God, which he hath poured upon all,
giveth an understanding to all that are led by it;
and to those who do not quench the motions of it,
it giveth knowledge and understanding to distinguish good from evil, light from darkness,
Christ from antichrist, the old testament or covenant from the new,
the old way from the new and living way; the sheep and lambs from the goats and wolves;
the worship of God, which Christ set up above sixteen hundred years ago,
from the dragon's and beast's worship;
and all them that worship the works of men's hands, and the will-worshippers,
from them that worship God in his Spirit and in his truth,
in which God's people worship him;
which worship is over all false worships and worshippers.
They who believe in the light, which is the life in Christ, become the children of light,
and are the lambs of Jesus.
These lambs follow the Lamb of God, that taketh away the sins of the world;
and they will not follow the hirelings, nor the strangers, to be led into strange ways,
doctrines, religions, worships, and churches; for the lambs of Christ follow Christ,
the Lamb of God, and know his heavenly voice.
They know also, that they who are without Christ are dogs and wolves, adulterers,
idolaters, liars, and unbelievers, who would devour the lambs;
but these are in the hand of the Lord, which is his power, that is over all.
Such do good in his power unto all; for they have the mind of Christ,
who would have all to come to the knowledge of the truth, and be saved.
They that do good to all, do hurt to none; for that spirit that doth hurt to any,
is not of God; but that spirit which doth good to all,
and especially to the household of faith, is of God.
Christ came not to destroy men's lives, but to save them:
it is the devil that is the destroyer of men's lives about religion, that corrupts men,
and makes them deaf and blind to the things of God, and to halt out of God's way.
They that obey the evil one and forsake the Lord, such the destroyer doth destroy;
but Christ destroys that destroyer; and in Christ all have life.`"

[.signed-section-signature]
G+++.+++ F.

I wrote another paper also concerning meditation, delight, exercise, and study;
showing from the Scriptures of truth, what the true Christians ought to meditate upon,
and to exercise their minds in; what they should take delight in,
and what they should study to do.
For in these things, not the profane and loose people only,
but even the great professors of religion are very much mistaken;
taking delight in earthly, fading, perishing things;
whereas they ought to meditate on heavenly things,
delight in the law of God after the inward man,
and exercise themselves to have always "`a conscience void of offence towards God,
and towards men,`" as the apostle Paul did.

As sufferings continued very sore and heavy upon Friends,
not only in the city but in most parts of the nation,
I drew up a paper to be presented to the king; setting forth our grievances,
and desiring redress from him in those particular cases
which I understood were in his power.
But not having relief from him,
it came upon me to write an epistle to Friends to encourage them in their sufferings,
that they might bear with patience the many exercises that were brought upon them,
both from the outward magistrates, and by false brethren and apostates,
whose wicked books and filthy slanders grieved the upright-hearted.
This epistle I wrote at Dalston,
whither I went to visit an ancient Friend that lay sick:--

[.small-break]
'''

"`Friends and brethren in Christ Jesus,
whom the Lord hath called and gathered into himself, in him abide;
for without him ye can do nothing, and through him ye can do all things.
He is your strength and support in all your trials, temptations, imprisonments,
and sufferings, who for Christ's sake are accounted as sheep for the slaughter:
in all these things we are more than conquerors, through Christ who hath loved us.
And therefore, Friends, though you suffer by the outward powers,
ye know that the prophets, Christ, and the apostles, suffered by the unconverted.
And though ye suffer by false brethren and false apostates for a time,
and by their filthy books and tongues; whose tongues indeed are become no slander,
let them speak, write, or print what they will;
for the sober people even of the world hardly regard it:
it is well they have manifested themselves to the world,
that their folly may proceed no farther.
Though, to the utmost of their power, they have showed their wicked intent,
to stir up the magistrates, professors, and profane against us,
and to speak evil of the way of truth, God's judgments will overtake them,
and come upon them, as sure as they have come upon those that are gone before them.
Let their pretence be ever so high, mark their end;
for they will fall like untimely figs,
and wither like the grass upon the top of the house.
Though they may seem to flourish, and make a boast and a noise for a time,
yet the Seed is on the head of such, and will grind them to powder;
which Seed bruises the serpent's head.
Therefore in this Seed, Christ, who is your sanctuary, rest, peace, and quiet habitation,
who is the First and the Last, and over all, in Him walk;
for the Lord taketh pleasure in his people that are faithful, that serve and worship him.
Therefore let the saints be joyful in glory; and the God of peace, 'the God of all grace,
who hath called us into his eternal glory by Jesus Christ,
after that ye have suffered a while, make you perfect, establish, strengthen, settle you.'
Cast all your care upon the Lord, for he careth for you.
And, dearly beloved, think it not strange concerning the fiery trial that is to try you,
as though some strange thing had happened unto you; for it is better,
if the will of God be so, that ye suffer for well-doing, than for evil-doing:
and rejoice, inasmuch as ye are made partakers of Christ's sufferings.
Wherefore let them that suffer according to the will of God,
commit the keeping of their souls to him in well-doing, as unto a faithful Creator;
for unto you is given, in the behalf of Christ, not only to believe in him,
but also to suffer for his sake.
So it is given, or is a gift from Christ, to suffer for his name; and therefore rejoice,
inasmuch as ye are made partakers of Christ's sufferings.
If ye be reproached, or evil spoken of for the name of Christ, happy are ye;
for the spirit of glory and of God resteth upon you: on their part he is evil spoken of,
but on your part he is glorified.
Therefore, if any suffer as Christians, let them not be ashamed;
but let them glorify God on this behalf, though now for a season ye are in sufferings,
and trials, and temptations, that the trial of your faith,
being much more precious than that of gold, which perishes, though it be tried with fire,
may be found unto praise, honour, and glory, who are kept by the power of God,
through faith, unto salvation.
Therefore mind your Keeper, wherever ye are, or what sufferings soever ye be in;
and mind the example of the apostle, how he suffered trouble as an evil-doer unto bonds.
But the Word of God is not bound, which is everlasting and endures for ever;
and they who are in that, which is not everlasting, and doth not endure for ever,
cannot bind the Word.
The apostle said, I endure all things for the elect's sake,
that they may also obtain the salvation, which is in Christ Jesus,
with eternal glory (mark, with eternal glory). And if we suffer with Christ,
we shall reign with Christ, who abide faithful.
Therefore strive not about words to no profit, but shun profane and vain babblings,
for they will increase unto more ungodliness; that ye may be vessels of honour,
sanctified and meet for Christ your Master's use, and prepared unto every good work.
Follow after righteousness, godliness, faith, love, patience, and meekness.
Fight the good fight of faith with your heavenly weapons;
which faith is victory (or gives victory) by which ye lay hold on eternal life,
and have access unto God, 'who will render to every man according to his deeds;
to them who, by patient continuing in well-doing, seek for glory, and honour,
and immortality, eternal life; but unto them that are contentious,
and do not obey the truth, but obey unrighteousness, indignation and wrath,
tribulation and anguish upon every soul of man that doeth evil; but glory, honour,
and peace to every man that worketh good.'
Christ said to his disciples, 'If the world hate you,
ye know that it hated me before it hated you.
If ye were of the world, the world would love its own;
but because ye are not of the world, but I have chosen you out of the world,
therefore the world hateth you.'
And, 'If they have persecuted me, they will also persecute you.'
And John, in his general epistle to the church, saith, 'Marvel not, my brethren,
if the world hate you.
We know that we have passed from death unto life, because we love the brethren.'
And Christ, in his prayer to his Father, saith of his followers,
'As thou hast sent me into the world, even so have I also sent them into the world;
and the glory which thou gavest me I have given them, that they may be one,
even as we are one.'
And, therefore, all ye that know God and Jesus Christ, whom to know is eternal life,
and are partakers of his glory, keep the testimony of Jesus,
and be valiant for his truth upon earth, that ye may be all settled upon Christ,
the rock and foundation.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Dalston, the 3rd of the 8th Month, 1682.

I made but little stay at Dalston, but returned to London,
where I continued most part of the winter,
labouring in the service of truth amongst Friends;
save that I was a little while at Kingston, in the 10th month of this year,
where I wrote a book, setting forth "`The state of the birth temporal,
and the birth spiritual; and the duty and state of a child, youth, young men, aged men,
and fathers in the truth,`" etc.
But I stayed not long at Kingston, for the heat of persecution still continuing,
I felt my service to be chiefly at London;
where our meetings were for the most part disturbed and broken up,
or Friends were forced to meet without doors,
being kept out of their meeting-houses by the officers.
Yet sometimes, beyond expectation, we got a quiet and peaceable meeting in the houses.
One time I intended to go a mile or two out of town, to visit a Friend that was not well;
but hearing that the king had sent to the mayor
to put the laws in execution against Dissenters,
and that the magistrates thereupon intended to nail up the meeting-house doors,
I had not freedom to go out of town,
but was moved to go to the meeting in Gracechurch Street;
and notwithstanding all the threats, a great meeting it was, and very quiet;
the glory of the Lord shone over all.

The same week I went to the meeting at the Peel in John's Street;
and the sessions were holden the same day at Hicks's-Hall.
I went to the Peel in the morning;
and William Mead being to appear at the sessions-
house for not going to the steeple-house worship,
came once or twice from Hicks's-Hall to me at the Peel;
which some ill-minded people observing, went and informed the justices at the bench,
that he was gone to a meeting at the Peel.
Whereupon the justices sent a messenger, to see if there was a meeting;
but this being in the forenoon, there was none; so the messenger,
when he had looked about, went back and told them.
Then others informed the justices that there would be one there in the afternoon;
whereupon they sent for the chief constable,
and asked him "`why he suffered a meeting to be at the Peel, so near him?`"
He told them, "`he did not know of any meeting there.`"
They asked him, "`how he could not know, and live so near it?`"
He said, "`he was never there in his life,
and did not know that there was a meeting there.`"
They would have persuaded him that he must needs know of it;
but he standing steadfast in the denial of it, they said,
"`they should take order to have it looked after in the afternoon.`"
But a multitude of business coming before them at the sessions, when dinner time came,
they hastened to it, without giving order,
and when they came to the bench again after dinner, the Lord put it out of their minds,
so that they sent no officer.
The meeting was quiet, beginning and ending in peace; and a blessed one we had,
the Lord's presence being preciously amongst us.
Many Friends had a concern upon their minds, when they saw me come into the meeting,
lest I should be taken; but I was freely given up to suffer, if it was the Lord's will,
before I went to the meeting;
and had nothing in my mind concerning it but the Lord's glory.
I do believe the Lord put it out of their minds,
that they should not send to break up our meeting that day.
Yet the First-day after, three or four justices (as I heard) came to the Peel,
and put Friends out of their meeting there, and kept them out;
and inquired for William Mead,^
footnote:[William Mead is often mentioned in these pages; and his trial,
along with William Penn, is alluded to in a previous note.
Of his life and ministry we have much less account than of most others of note in his day.
George Fox sometimes calls him his son, he having married Sarah,
a daughter of Judge Fell; George Fox's wife being her mother.
Before his joining Friends, William Mead appears to have been a captain in the army.
In his remarks in court on the term, _vi et armis,_ during his trial, he observes,
"`Time was when I had freedom to use a carnal weapon, and then I thought I feared no man;
but now I fear the living God, and dare not make use thereof, nor hurt any man.`"
He died in 1713, aged eighty-six.]
but he was not there.

That day I was moved to go to Gracechurch Street meeting;
and it was expected that the officers would come to break it up, or keep Friends out;
and many hundreds of people came to see what would be done to us.
But the officers came not; so we were in peace and quietness;
and many of the people that came to look on, stayed all the time; and a glorious,
precious meeting we had; for the Lord's presence was plentifully amongst us,
and his power came over all; glory to his name for ever, who is over all!

I had seen the mayor's printed speech for
putting the laws in execution against Dissenters;
and it was much in my mind that we should draw
up a paper to send to the mayor and aldermen,
to clear ourselves from being such, as those laws were made against;
and to set forth our peaceable behaviour both towards the king and the government.
Accordingly a paper was drawn up and signed, and delivered to the mayor;
copies of which were also delivered to the aldermen, and the bishop of London,
who generally took it kindly, and were civil to the Friends that delivered it.

[.offset]
About this time I was moved to write the few lines following to Friends:--

[.salutation]
"`Dear Friends,

"`Feel the power of God in you all, and over all,
and by it let your hearts be united to one another, and to the Lord God,
who hath gathered you to himself, by his power and Spirit,
to be a people to serve and worship him.
So you may all strive to excel one another in virtue,
and in that love that beareth all things, and edifieth the body of Christ,
the body of the second Adam.
For the body of old Adam in the fall is full of malice, envy, and vice.
Therefore you, that are called out of old Adam in the fall, and have put on Christ,
the second Adam, that never fell, walk in Him, the treasure of life, wisdom,
and knowledge, in whom ye have peace with God, who is the First and the Last,
the Beginning and the Ending.
So let all be gathered up to God, into Him who reconcileth all things in one,
both things in heaven and things on earth;
who is the faithful and true witness in male and female.
In Him sit down, who is above the subtle foxes in their holes,
and the fowls of the air in their nests; I say, sit down in Christ,
who hath no place among them to lay his head; He is your rest.
So in him is my love to you all.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 20th of the 11th Month, 1682.

[.offset]
Not long after this, I received an account by letter, from some Friends,
that were prisoners at Denbigh, in Wales,
that many Friends there were under great sufferings for
the testimony of a good conscience.
In the tender sense whereof I was moved, in the love of God,
to visit them with a few lines, as a word of consolation to them in their sufferings;
and of exhortation, to stand fast in the testimony committed to them,
after this manner:--

"`Dear suffering lambs for the name and command of Jesus; be valiant for his truth,
and faithful, and ye will feel the presence of Christ with you.
Look at Him, who suffered for you, who hath bought you, and will feed you; who saith,
'Be of good comfort, I have overcome the world;' who destroys the devil and his works,
and bruises the serpent's head.
I say, look at Christ, your sanctuary, in whom ye have rest and peace.
To you it is given not only to believe, but to suffer for his name's sake.
They that will live godly in Christ Jesus,
shall suffer persecution by the ungodly professors of Christ Jesus, who live out of him.
Therefore be valiant for God's truth upon the earth,
and look above that spirit that makes you suffer, up to Christ, who was before it was,
and will be when it is gone.
Consider all the prophets, Christ, and the apostles, who suffered, and were persecuted;
but they were never persecuted as true men, but as deceivers, and yet true.
Christ is the same to-day as he was yesterday;
a rock and foundation for your age and generation, for you to build upon.
I have written concerning you (since I heard your
letter) to Friends in Cheshire to visit you,
understanding that you belong to their quarterly meeting;
and therefore I desire that some Friends of your county would go,
and lay your suffering condition before the monthly or quarterly meeting in Cheshire.
I have written likewise to Richard Davies,^
footnote:[Richard Davies--some account of whose life, written by himself,
was published after his decease,
and a third edition of the volume in 1771--was
convinced of the truth about the year 1657.
He resided in Montgomeryshire;
and his life contains an interesting account of the first spreading of truth in Wales.
Richard Davies was a faithful minister of the gospel, endued with spiritual gifts,
and serviceable in the exercise thereof in the churches of Christ; sound in doctrine,
and exemplary in conversation.]
that some of that side may go and visit you, and see how your condition is.
My love is to you in the Lord, who is your alone support.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 27th of the 11th Month, 1682.

Now because the magistrates were many of them
unwilling to have fines laid upon meeting-houses,
they kept Friends out in many places,
setting officers and guards of soldiers at the doors and passages;
yet sometimes Friends were fined for speaking or praying, though it was abroad.
One First-day it was upon me to go to Devonshire-House meeting in the afternoon;
and because I had heard Friends were kept out there that
morning (as they were that day at most meetings about the city)
I went sooner, and got into the yard before the soldiers came to guard the passages;
but the constables were there before me, and stood in the door-way with their staves.
I asked them to let me go in; they said, "`they could not, nor durst not;
for they were commanded the contrary, and were sorry for it.`"
I told them I would not press upon them; so I stood by, and they were very civil.
I stood till I was weary, and then one gave me a stool to sit down on;
and after a while the power of the Lord began to spring up among Friends,
and one began to speak.
The constables soon forbade him, and said he should not speak; and he not stopping,
they began to be wroth.
But I gently laid my hand upon one of the constables, and wished him to let him alone;
the constable did so, and was quiet; and the man did not speak long.
After he had done, I was moved to stand up and speak; and in my declaration, I said,
"`they need not come against us with swords and staves, for we were a peaceable people;
and had nothing in our hearts but good-will to the king and magistrates,
and to all people upon the earth.
We did not meet, under pretence of religion, to plot and contrive against the government,
or to raise insurrections; but to worship God in Spirit and in truth.
We had Christ to be our Bishop, Priest, and Shepherd to feed us, and oversee us,
and he ruled in our hearts; so we could all sit in silence, enjoying our teacher;
so to Christ, their Bishop and Shepherd, I recommended them all.`"
I then sat down; and after a while I was moved to pray,
and the power of the Lord was over all; and the people, the constables, and soldiers,
put off their hats.
When the meeting was done, and Friends began to pass away, the constable put off his hat,
and desired the Lord to bless us; for the power of the Lord was over him and the people,
and kept them under.

After this I went up and down, visiting Friends at their houses,
who had their goods taken from them for worshipping God.
We took an account of what had been taken from them;
and some Friends met together about it,
and drew up the case of the sufferings of our Friends in writing,
and gave it to the justices at their petty sessions.
Whereupon they made aa order,
"`that the officers should not sell the goods of Friends which they had in their hands,
but keep them until the next sessions;`" which gave some discouragement to the informers,
and put a little stop to their proceedings.

Next First-day it was upon me to go to the meeting at the Savoy;
and by the time it was gathered the beadle came in; and after him the wild people,
like a sea; but the Lord's power chained them all.
The Spirit of the Lord went through and over all, and they were quiet,
and we had a glorious, peaceable meeting;
blessed be the Lord for his unspeakable goodness.
This was in the 12th month, 1682.

Ia the 1st month, 1683, I went to Kingston-Upon-Thames;
and it being then a time of persecution, as I went to the meeting,
I met the chief constable, who had been at the meeting-place,
and had set watchmen there to keep us out; yet he was pretty civil,
and the watchmen let Friends have a couple of forms out, to sit upon in the highway;
so we met together there, and a very precious meeting we had;
for the refreshing presence of the Lord was with us, in which we parted in peace.

Having visited and encouraged Friends there, I returned to London,
and went to the meeting at the Bull-and-Mouth,
where the constables with their watchmen kept a guard, to keep Friends out of the house.
So we met in the street; and when any Friend spoke,
the officers and watchmen made a great bustle to pull him down,
and take him into custody.
After some other Friends had spoken, it was upon me to speak; and I said,
"`Heaven is God's throne, and earth is his footstool;
and will ye not let us stand upon God's footstool to worship, and serve the living God?`"
While I spoke they were quiet; and after I had cleared myself,
we broke up our meeting in peace.
This was on the Sixth-day of the week.

On the First-day following I was moved to go to the meeting at Gracechurch Street.
When I came there, I found a guard set at the entrance in Lombard Street,
and another at the gate in Gracechurch Street, to keep Friends out of the meeting-place;
so we had to meet in the street.
After some time I got a chair, stood up on it, and spoke largely to the people,
opening the principles of truth to them,
and declaring many weighty truths concerning magistracy,
and concerning the Lord's prayer.`"
There were, besides Friends, a great multitude of people,
and amongst them many professors; all was very quiet; for the Lord's power was over all,
and in his time we broke up our meeting, and departed in peace.

The next day I went to Guildford in Surrey; and having visited Friends there,
passed to Worminghurst in Sussex, where I had a very blessed meeting among Friends,
free from disturbance.
While I was there, James Claypole, of London (who was there with his wife also),
was suddenly taken ill with so violent a fit, that he could neither stand nor lie; but,
through the extremity of pain, cried out.
When I heard it, I was much exercised in spirit for him; and went to him.
After I had spoken a few words to him, to turn his mind inward,
I was moved to lay my hand upon him, and prayed the Lord to rebuke his infirmity.
As I laid my hand on him, the Lord's power went through him;
and through faith in that power he had speedy ease, so that he quickly fell into a sleep.
When he awoke, he was so well,
that next day he rode with me five-and-twenty miles in a coach;
though he used formerly (as he said) to lie sometimes two weeks, sometimes a month,
in one of those fits.
But the Lord was entreated for him, and by his power soon gave him ease at this time;
blessed and praised be his holy name therefore!

After I had had some meetings in Sussex and Surrey, and had visited Friends thereaway,
I returned to London by Kingston, where I had a meeting on the 1st of the 2nd month,
being First-day.
We were kept out of the meeting-house by a constable and watchmen, as before,
and so were obliged to meet in the highway.
But it being the monthly meeting day, and many people being there,
the meeting was pretty large, and very quiet;
and the Lord's blessed presence was amongst us; blessed be his name for ever!

Being come to London, I went to the meeting at Wheeler Street, near Spitalfields,
which that day proved very large; and a glorious, blessed time it was;
for the Lord's power and truth were over all,
and many deep and weighty things were opened to the people, to their great satisfaction.

I tarried in and near London, visiting Friends' meetings,
and labouring in the service of the gospel, till the Yearly Meeting came on,
which began on the 28th of the 3rd month.
It was a time of great sufferings; and much concerned I was,
lest Friends that came up out of the country on the church's service,
should be taken and imprisoned at London.
But the Lord was with us; his power preserved us,
and gave us a sweet and blessed opportunity to wait upon him,
to be refreshed together in him,
and to perform his services for his truth and people for which we met.
As it was a time of great persecution,
and we understood that in most counties Friends were under great sufferings,
either by imprisonments or spoiling of goods, or both,
a concern was weightily upon me lest any Friends that were sufferers,
especially such as were traders and dealers in the world,
should hazard the losing of other men's goods or estates through their sufferings.
Wherefore, as the thing opened in me,
I drew up an epistle of caution to Friends in that case,
which I communicated to the Yearly Meeting;
and from thence it was sent forth among Friends throughout the nation;
a copy of which here follows:--

[.small-break]
'''

"`Dear Friends and brethren in the Lord Jesus Christ,
who is your only sanctuary in this day of storm and persecution, spoiling of goods,
and imprisonments!
Let every one's eye be unto him, who has all power in heaven and in earth given unto him;
so that none can touch a hair of your head, nor you, nor anything ye have,
except it be permitted or suffered in this day, to try his people,
whether their minds be with the Lord, or in outward things.
Dear Friends, take care that all your offerings be free, and of your own,
that has cost you something; so that ye may not offer of that which is another man's,
or that which ye are entrusted withal and not your own,
or fatherless' or widows' estates;
but all such things settle and establish in their places.
You may remember many years ago, in a time of great persecution, divers Friends,
who were traders, shop-keepers, and others, had the concerns of widows and fatherless,
and other people's estates in their hands.
And when a great suffering, persecution, and spoiling of goods came upon Friends,
especial care was taken that all might offer up to the
Lord in their sufferings what was really their own,
and not any other people's estates or goods which they had in their hands;
and that they might not offer up another body's,
but that which they had bought and paid for, or were able to pay for.
Afterwards several letters came out of the country to the meeting at London,
from Friends that had goods of the shopkeepers at London upon credit,
which they had not paid for; who wrote to their creditors whom they had their goods of,
entreating them to take their goods again.
And some Friends came to London themselves, and treated with their creditors,
letting them understand 'that they lay liable to have
all that they had taken from them;' and told them,
'they would not have any man to suffer by them:
neither would they by suffering offer up anything but what was really their own,
or what they were able to pay for.'
Upon which several took their goods again.
This wrought a very good savour in the hearts of many people,
when they saw such a righteous, just, and honest principle in Friends,
that would not make any suffer for their testimony;
but what they did suffer for the testimony of Jesus should be really and truly their own,
not other people's. In this they owed nothing to any, but love.
So in this every man and woman stands in the free offering, a free people,
whether it be spiritual or temporal, which is their own; and in that they wrong no man,
neither inwardly, nor outwardly.
Ornan said unto David,' I give thee the thrashing-floor, etc.,
and the oxen for burnt-offerings, and the thrashing instruments for wood,
and the wheat for the meat-offering; I give it all.'
But king David said unto Ornan, 'Nay, but I will verily buy it for the full price;
for I will not take that which is thine for the Lord,
nor offer burnt-offerings without cost,' 1 Chron. 21:22, etc.
So it should be his own; and so should it be every man's that offers.
You may see here that David would not accept of
another man's gift for an offering to the Lord;
he would not offer up that which cost him nothing; but what should be really his own,
Ps. 112:5. 'A good man will guide his affairs with discretion.'

"`Let this be read in your monthly and quarterly men's and women's meetings.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 2nd of the 4th Month, 1683.
