== Chapter XI.

[.chapter-synopsis]
* 1683-1685.
* A salutation of love to Friends, designed to stir up the pure mind
* an epistle to Friends commending them to Christ, the rock and sure foundation
* an epistle of counsel to Friends
* George Fox taken from a meeting and examined by a magistrate, but soon released
* writes an epistle to the faithful to beware of a seducing spirit
* after the Yearly Meeting sails for Holland, and lands at the Briel
* attends the Yearly Meeting at Amsterdam
* writes to Galenus Abrahams, a Mennonist or Baptist, who, seven years before, bid him "`keep his eyes off him,`" for he said "`they pierced him,`" but now he was become very loving and tender, as well as his family
* George Fox returns to England
* writes to the Duke of Holstein an able defence of women`'s preaching
* writes an epistle of counsel to Friends
* advises with, and assists them in, drawing up an account of sufferings, which is printed and spread amongst Parliament-men
* writes a caution to Friends to keep out of the world`'s spirit, etc.
* and a warning against pride and excess in apparel.

Some time after the Yearly Meeting I went down
to Kingston-Upon-Thames to visit Friends there;
and while I was there it came upon me to write
the following epistle to Friends in general,
as a salutation of love, and to stir up the pure mind in them:--

[.salutation]
"`Dear Friends And Brethren,

"`Who are turned from darkness to light, and from the power of Satan to God,
who are believers in the light, which is the life in Christ,
and are become children of the light and of the day;--who are grafted into Christ,
the second Adam, the Lord from heaven, and are gathered in the name of Jesus,
in whom ye have salvation, and not in any other name under the whole heaven.
For Christ Jesus saith, '`Where two or three are gathered together in my name,
there am I in the midst of them,`' Matt. 18:20.
So you being gathered in the name of Jesus,
he is in the midst of you, a Saviour, a Mediator, a Prophet, a Shepherd, a Bishop,
a Leader, a Counsellor, the Captain of your salvation, who bruises the serpent`'s head,
and destroys the devil and his works.
Therefore, brethren in Christ Jesus, exhort one another daily, while it is called today,
lest any of you be hardened through the deceitfulness of sin.
For you are made partakers of Christ,
if ye hold fast the beginning of your confidence steadfast to the end,
Heb. 3:14. Therefore hear Christ`'s voice, for he is in the midst of you a teacher.
Take heed, lest there be in any of you an evil heart of unbelief,
in departing from the living God,
as there is in too many in this day of provocation and temptation.
While it is today hear his voice, and let us consider one another,
to provoke unto love and to good works.
Let us hold fast the profession of our faith without wavering
(for he is faithful that hath promised and hath called you),
not forsaking the assembling of ourselves together, as the manner of some is;
(mark) as the manner of some is,
that did and do forsake the assembling of themselves together: but exhorting one another,
and so much the more as you see the day of light appearing.
For if we sin willfully, after we have received the knowledge of the truth,
there remains no more sacrifice for sins;
but a certain fearful looking for of judgment and fiery indignation,
which shall devour the adversaries, Heb. 10.
And therefore it is good not to forsake the assembling of ourselves together,
but exhort one another daily;
for Christ is in the midst of his people a teacher and a prophet, who saith,
'`Learn of me; the way, the truth, and the life.`'
We being many, are one body in Christ, gathered in his name,
and every one members one of another.
Having then gifts differing according to the grace that is given us,
whether they be prophecy, let us prophesy according to the proportion of faith;
and let those that minister, wait on their ministry; those that be teachers,
on their teaching; and him that exhorteth, on exhortation; he that giveth,
let him do it with simplicity; and he that ruleth, with diligence;
and he that showeth mercy, is to do it with cheerfulness.
Abhor that which is evil; cleave to that which is good.
Be kindly affectioned one towards another, with brotherly love,
in honour preferring one another.
Rejoice in hope; be patient in tribulations; be not overcome with evil,
but overcome evil with good; and, if it be possible, as much as lieth in you,
live peaceably with all men, Rom.
xii. This is and was the practice of the church of Christ.
And now the God of hope fill you with all joy and peace in believing,
that ye may abound in hope, through the power of the Holy Ghost.
I myself also am persuaded of you, my brethren, that ye also are full of goodness,
filled with all knowledge, and are able also to admonish one another,
Rom. 15:13-14. Here the church of Christ,
in which He was in the midst a teacher and the head of the church,
were and are able through him to admonish one another.
Let the peace of God rule in your hearts, to which ye are also called into one body,
to wit, of Christ.
Let the word of Christ dwell in you richly in all wisdom,
teaching and admonishing one another, etc, Col.
iii. Whatsoever ye do, in word or deed, do all in the name of the Lord Jesus Christ,
giving thanks to God and the Father by him: and above all things put on charity,
which is the bond of perfectness.
The apostle said to Timothy, '`Be not thou ashamed of the testimony of our Lord,
nor of me, his prisoner; but be thou partaker of the afflictions of the gospel,
according to the power of God, who hath saved us, and called us with a holy calling;
not according to our works, but according to his own purpose and grace,
which was given us in Christ Jesus before the world began,`' 2 Tim. 1:8-9.
It concerns every one not to be ashamed of the testimony of our Lord,
who hath called them by his grace; and not to be ashamed of any of Christ`'s prisoners,
and afflicted ones for Christ`'s and his gospel`'s sake, who abolishes death,
and brings life and immortality to light through his gospel:
you that believe in the light, know it.
Peter saith, in his general epistle to the church of Christ, '`As every man`' (mark,
every man) '`hath received the gift,
so minister the same one to another as good stewards of the manifold grace of God.
If any man speak, let him speak as the oracles of God, not of men; if any man minister,
let him do it as of the ability which God gives,
not of the ability of men`'s arts and sciences,
that God in all things may be glorified through Jesus Christ,`' etc.
For these gifts and grace come from Jesus into the hearts of the members of his church,
whom he is in the midst of.
And if any man suffer as a Christian, let him not be ashamed; but let him glorify God, etc.
Every true Christian hath the presence of Christ,
who hath all power in heaven and in earth given him, to support him with his power,
light, and life.
Christ saith to his believers, '`Beware of men,
for they will deliver you up to the councils,
and they will scourge you in the synagogues,
and you shall be brought before governors and kings for my name`'s sake,
for a testimony against them and the Gentiles.
But when they deliver you up, take no thought how or what ye shall speak;
for it shall be given you in the same hour what ye shall speak:
for it is not you that speak, but the Spirit of your Father that speaketh in you.
And ye shall be hated of all men for my name`'s sake: but he that endureth to the end,
shall be saved.
The disciple is not above his Master, nor the servant above his lord;
it is enough for the disciple that he be as his Master, and the servant as his lord:
for if they have called the master of the house Beelzebub,
what will they do to his servant.
Fear not them which kill the body, but are not able to kill the soul, etc.
A sparrow shall not fall to the ground without your heavenly Father, etc.
The hairs of your head are all numbered; ye are of more value than many sparrows.
Whosoever therefore shall confess me before men,
him will I confess also before my Father who is in heaven;
but whosoever shall deny me before men, him will I also deny before my Father,
who is in heaven.
And whosoever shall be ashamed of me and of my words,
of him shall the Son of Man be ashamed,`' etc. Matt. 10.
And again Christ saith,
'`Whosoever shall be ashamed of me and of my
words in this adulterous and sinful generation,
of him also shall the Son of Man be ashamed,
when he comes in the glory of his Father with his holy angels.`'
Mark 8:38. And Christ saith to his disciples, '`He that receiveth you receiveth me;
and he that receiveth me, receiveth him that sent me:
he that receiveth a prophet in the name of a prophet, shall receive a prophet`'s reward;
and he that receiveth a righteous man in the name of a righteous man,
shall receive a righteous man`'s reward.
And whosoever shall give to drink unto one of these little ones a cup of cold water only,
in the name of a disciple, verily I say unto you, he shall in no wise lose his reward.`'
Matt. 10:40-42. Here ye may see how Christ encourages his disciples,
and them that receive them.
And John saith, '`Among the chief rulers of the Jews many believed in Christ;
but because of the Pharisees, they did not confess him,
lest they should be put out of the synagogue,`' John 12:42.
Too many such believers there are now-a-days,
who dare not confess Christ, lest they should lose the favour of men.
But Christ encouraged the faithful disciples,
and told them they would put them out of their synagogues; yea,
that the time should come, that whosoever killed them would think they did God service:
And '`these things,`' said he, '`will they do unto you,
because they have not known the Father, nor me.
But these things have I told you, that when the time shall come,
ye may remember that I told you of them,`' John 16:2-4. Here ye may
see what Christ told his disciples should come to pass to them.
And Saul, before he was converted, compelled the Christians to blaspheme,
and made havoc of the church of Christ, Acts 8. and chap. 22. and 26.
And did not the beast in the Revelations compel both
small and great to worship him and his image?
And did not all worship it,
but they who had their names written in the Lamb`'s book of life?
Did not Nebuchadnezzar set up an image sixty cubits high, and six cubits broad?
And did not he cause a herald to cry aloud, '`It is commanded that all people, nations,
and languages fall down, and worship the golden image that Nebuchadnezzar hath set up:
and whoso falleth not down, and worshippeth,
shall the same hour be cast into the midst of the fiery furnace?`'
And were not Shadrach, Meshach, and Abednego, cast into the furnace? Dan. 3.
But God delivered them.
Therefore it is good to be faithful to God and his worship in Spirit and in truth.
The Jews agreed, that if any man should confess Christ,
he should be put out of their synagogue,
John 9:22. So it was for Christ`'s sake they
were excommunicated out of their synagogues.
But as it is written, '`Behold, I lay in Zion a stumbling-stone, and a rock of offence;
and whoso believes on him, shall not be ashamed.`'
So Christ is a stumbling-stone and a rock of offence to all the unbelievers in the light,
which is the life in Christ, whether they be Jews, Christians, or Gentiles.
The Jews believed Christ was to come, from the Scriptures;
and the Christians believe he is come, by the Scriptures;
but do not believe in the light, as Christ commands,
and so do not become children of light.
Therefore ye that are believers in the light, and are become children of light,
walk in Christ, your way, life, and salvation.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 5th Month, 1083.

[.offset]
Before I left Kingston, something further opened in me, which I was moved to write,
and send amongst Friends; as follows:--

[.salutation]
"`Dear Friends,

"`My love is to you all in the holy Seed, that reigns over all.
And my desire is, that every one, both male and female, may feel the Seed Christ in you,
which is heir of the promise of life eternal,
that ye may all grow up in Christ Jesus your head, and be built upon Him,
the rock and foundation that God hath laid,
which stands sure over all rocks and foundations in the world;--that
ye may eat and drink of this spiritual rock,
the spiritual water and food; so that ye may truly and inwardly say,
that your rock and foundation, your bread and water of life, is from heaven,
and your bread and water is sure; and that ye know his voice that feeds you,
and leads you into the pastures of life, which are always fresh and green.
In this, your affections are set on things that are above,
seeking that which comes down from above, where Christ sits at the right hand of God,
making intercession for you; who is your Mediator, making peace between God and you;
who is your heavenly Bishop to oversee you, that ye keep in his light, life, and power,
and do not go astray from his heavenly fold and pasture,
that He your Shepherd may feed you therein; who is your Prophet,
to open to you the fulfilling of the promises and prophecies,
himself being the substance; that ye may live in him, and he in you, yea,
and reign in your hearts, there to exercise his offices, his prophetical, priestly,
and kingly office, who is heavenly and spiritual;--that ye may know the three,
that bear witness in the earth, the Spirit, the Water, and the Blood,
which is the life of Christ, which cleanseth from all sin;
the Water that washes and refreshes you;
and the Spirit that baptizes and circumcises you, and leads you into all truth;
that ye may come all to drink into one Spirit, and keep the unity of the Spirit,
which is the bond of the heavenly peace.
So being led by the Spirit of God, ye are his sons and daughters,
and by his Spirit will come to know the three that bear witness in heaven, the Father,
the Word, and the Holy Ghost.
These are the three witnesses that are in heaven, that bear record of all things;
for he is God in heaven, and God in the earth.
Therefore I desire, that ye may all feel his love shed in your hearts,
and in it live (above the love of the world, which is enmity),
and in that you will keep in the excellent way.
For love edifies the body of Christ, builds his church up, and keeps out of the enmity,
for it is above it, and brings and keeps all in true humility, and in the true divinity;
to be courteous, kind, and tender one towards another,
and to show forth the nature of Christ,
and true Christianity in all your lives and conversations;
that the blessings of the Lord may rest upon you,
as ye all live in the seed of the gospel, the seed of the kingdom of God,
in which all nations are blessed.
In that ye will all have a care of God`'s glory.
There is the hill or mountain,
where the light shines to the answering the witness of God in all; and the salt,
that is a good savour to the witness of God in the hearts of all;
and that savour being kept in, the salt doth not come under the feet of men.
So my love to you all in Christ Jesus,
whom God hath given to be a sanctuary for all his people,
who is from above and not of this world, in whom you have life, peace, and salvation.
In Him God Almighty keep and preserve you all to his glory. Amen.
As you live in the peaceable truth of God, it keeps you under, and within,
his protection; but they that make a profession of the Scriptures of truth,
and yet live out of the truth, in the spirit of strife, unquietness, and discontent,
in a contriving, plotting, ravenous, destroying spirit, which is of the devil,
and not of God, that spirit is judged out of the truth, and to be of him,
in whom there is no truth, whose portion is in the lake, and in the fire that burns.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 27th of the 5th Month, 1683.

Having visited Friends at and about Kingston, I returned to London;
for it being a suffering time with Friends there,
I had not freedom to be long from the city.
I went to the meeting at the Peel,
which but a little before the justices and constables had broken up,
and had carried themselves very roughly; but that day it was in the house, and quiet;
and a glorious one it was, blessed be the Lord.

On the First-day following I went to the meeting at Gracechurch Street.
When I came there, I found three constables in the meetinghouse, who kept Friends out;
so we met in the court.
After I had been some time there, I stood up and spoke to the people,
and continued speaking some time.
Then one of the constables came, and took hold of my hand, and said, "`I must come down.`"
I desired him to be patient, and went on speaking to the people;
but after a little time he pulled me down, and had me into the meeting-house.
I asked them, if they were not weary of this work.
One of them said, "`indeed they were.`"
They let me go into the widow Foster`'s house, which joined to the meeting-house,
where I stayed, being hot.
When the meeting was ended, for one prayed after I was taken away,
the constables asked some Friends,
"`which of them would pass their words that I should appear,
if they should be questioned about me; but the Friends telling them,
they need not require that, for I was a man well known in the city,
to be one that would neither fly nor shrink; they went away,
and I heard no further of it.
The same week I was at the meeting at the Savoy, which used to be kept out and disturbed;
but that day it was within doors and peaceable; and a precious time it was.
The First-day after, it was upon me to go to the meeting at Westminster,
where there used to be great disturbances;
but there also the meeting was within doors that day, and very large.
The Lord`'s power was over all, and kept all quiet and still;
for though many loose spirits were there,
yet they were bound down by the power and Spirit of the Lord,
that they could not get up to make disturbance.

[.offset]
About this time I was moved to write the following epistle:--

[.salutation]
"`Friends And Brethren,

"`Who have received the peaceable truth,
let the fruits of its peaceableness and of your quiet spirit appear in all your meetings,
and in all your words and actions;
for he that inhabits eternity dwells with a humble heart, he gives grace to the humble,
and resisteth the proud.
Heaven is his throne, and the earth ye walk upon is his footstool; happy are ye,
that see and know him, that is invisible.
And now, Friends, let all things be done in your meetings, and otherwise, in love,
without strife or vainglory.
For love fulfils the law, love overcomes, and edifies the body of Christ.
There is neither self nor envy in love, neither is it puffed up;
but abides and bears all things.
See that this love of God have the sway in you all and over you all.
Christ saith, '`Blessed are the poor in spirit; for theirs is the kingdom of heaven.
Blessed are they that mourn; for they shall be comforted.
Blessed are the meek; for they shall inherit the earth.
Blessed are they that do hunger and thirst after righteousness; for they shall be filled.
Blessed are the merciful; for they shall obtain mercy.
Blessed are the pure in heart; for they shall see God.
Blessed are the peace-makers; for they shall be called the children of God.
Blessed are they that are persecuted for righteousness`' sake;
for theirs is the kingdom of heaven.
Blessed are ye, when men shall revile you, and persecute you,
and shall say all manner of evil against you falsely for my sake.
Rejoice and be exceeding glad; for great is your reward in heaven;
for so persecuted they the prophets which were before you.`'

"`Now Friends, here is a great deal in these words;
and all must be in these states and conditions, if they have these blessings.
The children of God are peace-makers, and strive to make peace in the truth;
and to live in peace with all men, if it be possible.
So live in peace and good-will to all men;
which good-will is both for their sanctification and salvation.
And, Friends, consider, the wisdom of God, which is from above, is pure, peaceable,
gentle, and easy to be entreated, full of mercy and good fruits,
without partiality and without hypocrisy.
Dear Friends, let this pure, peaceable, gentle wisdom, that is from above,
that is easy to be entreated, and is full of mercy and good fruits,
be exercised and practised in all the true churches of Christ,
so that wisdom may be justified of her children.
For the works of the flesh, or fleshly spirit, are hatred, variance, wrath, strife,
envyings, drunkenness, revellings, adultery, fornication, lasciviousness, uncleanness,
etc., and they which do such things shall not inherit the kingdom of God.
But the fruits of the Spirit of God are love, joy, peace, long-suffering, gentleness,
goodness, faith, meekness, temperance, etc.
So, dear Friends and brethren, strive to exceed one another,
and all people upon the earth, in humility, meekness, gentleness, temperance, love,
patience, pureness, and in mercy;
then ye will show forth the fruits of the Spirit of God,
and of his heavenly wisdom that is from above.
In this, wisdom will be justified of her children; ye will be the salt of the earth,
the light of the world set on a hill, that cannot be hid;
and your moderation will appear to all men.
Be ye just and righteous, faithful and true in all your words, dealings,
and conversations, so that ye may answer the truth in all people; for Christ saith,
his Father is glorified by such as bring forth fruits, when men do see their good works;
for he that doeth righteousness, is accepted with God.
And he that dwells in love, dwells in God; for love is his habitation.
Let that be the habitation of every one that hath received the truth; for if it be not,
such do not dwell in God, let them profess what they will.
Therefore my desire is, that all you who have received Christ, the Seed,
which bruises the serpent`'s head, may walk in Him, your sanctuary, life, and salvation,
your rest and peace. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 14th of the 6th Month, 1683.

I continued yet at London,
labouring in the work and service of the Lord both in and out of meetings;
sometimes visiting Friends in prison for the testimony of Jesus,
encouraging them in their sufferings,
and exhorting them to stand faithful and steadfast in the testimony,
which the Lord had committed to them to bear;
sometimes also visiting those that were sick and weak in body, or troubled in mind,
helping to bear up their spirits from sinking under their infirmities.
Sometimes our meetings were quiet and peaceable;
sometimes they were disturbed and broken up by the officers.
One First-day it was upon me to go to the meeting at the Savoy, which was large;
for many professors and sober people were there.
The Lord opened many precious, weighty things in me to the people,
which I declared amongst them, and "`directed them to the Spirit of God in themselves,
which the Lord had given them a measure of;
that all by the Spirit might understand the Scripture,
which were given forth from the Spirit of God; and that by the Spirit of God,
they might know God, and Christ whom God hath sent; whom to know is eternal life;
and that by the Spirit, they might all come into Christ,
and know Him to be their sanctuary, who destroys the devil, the destroyer, and his works,
and bruises the serpent`'s head.
For Christ was a sanctuary to them, to whom he was a Saviour,
whom he saved from the destroyer.
And Christ did baptize them with the Holy Ghost and with fire,
and did thoroughly purge his floor, and burn up their chaff with unquenchable fire;
that is, sin and corruption, which is got into man by transgression;
but Christ gathereth his wheat into his garner.
So all that are baptized with Christ`'s baptism, their wheat is in God`'s garner;
and no spoiler can get into God`'s garner to meddle with the wheat there,
though they may be permitted to meddle with the outward goods,`" etc.
As I was speaking in the power of the Lord,
and the people were greatly affected therewith, suddenly the constables,
with the rude people, came in like a sea.
One of the constables said to me, "`Come down;`" and he laid hands on me.
I asked him, "`Art thou a Christian? We are Christians.`"
He had hold of my hand, and was very fierce to pluck me down; but I stood still,
and spoke a few words to the people;
desiring of the Lord that the blessings of God might rest upon them all.
The constable still called upon me to come down, and at length plucked me down,
and bid another man with a staff take me, and carry me to prison.
That man led me to another officer`'s house, who was more civil;
and after a while they brought in four Friends more, whom they had taken.
I was very weary and in a great perspiration; and several Friends hearing where I was,
came to me in the constable`'s house; but I bid them all go their ways,
lest the constables and informers should stop them.
After a while the constables led us almost a mile to a justice, who was a fierce,
passionate man; who, after he had asked me my name,
and his clerk had taken it in writing,
upon the constable`'s informing him that "`I preached in
the meeting,`" said in an angry manner,
"`Do not you know, that it is contrary to the king`'s laws to preach in such conventicles,
contrary to the Liturgy of the Church of England?`"
There was present one Shad (a wicked informer,
who was said to have broken jail at Coventry,
and to have been burned in the hand at London), who hearing the justice speak so to me,
stepped up to him, and told him,
"`that he had convicted them on the Act of the 22nd of King Charles the Second.`"
"`What! you convict them?`"
said the justice; "`Yes,`" said Shad, "`I have convicted them,
and you must convict them too upon that Act.`"
With that the justice was angry with him, and said, "`You teach me! what are you?
I`'ll convict them of a riot.`"
The informer hearing that, and seeing the justice angry, went away in a fret;
so he was disappointed of his purpose.
I thought he would have sworn somebody against me, whereupon I said,
"`Let no man swear against me,
for it is my principle '`not to swear;`' and therefore I
would not have any man swear against me.`"
The justice thereupon asked me, "`If I did not preach in the meeting;`" I told him,
"`I confessed what God and Christ had done for my soul, and praised God;
and I thought I might have done that in the streets, and in all places, viz.,
praise God and confess Christ Jesus; and this I was not ashamed to confess.
Neither was this contrary to the Liturgy of the Church of England.`"
The justice said,
"`the laws were against such meetings as were contrary
to the Liturgy of the Church of England.`"
I said, "`I knew no such laws against our meetings;
but if he meant that Act that was made against such as met to plot, contrive,
and raise insurrections against the king, we were no such people,
but abhorred all such actions; and bore true love and good-will to the king,
and to all men upon the earth.`"
The justice then asked me, "`if I had been in orders;`" I told him,
"`No.`" Then he took his law-books and searched for laws against us;
bidding his clerk take the names of the rest in the mean time:
but when he could find no other law against us, the clerk swore the constable against us.
Some of the Friends bid the constable "`take heed what he swore, lest he were perjured;
for he took them in the entry, and not in the meeting.`"
Yet the constable, being an ill man, swore "`that they were in the meeting.`"
However, the justice said, "`seeing there was but one witness,
he would discharge the rest; but he would send me to Newgate, and I might preach there.`"
I asked him, "`If it stood with his conscience to send me to Newgate for praising God,
and for confessing Christ Jesus?`"
He cried, "`Conscience! conscience!`" but I felt my words touched his conscience.
He bid the constable take me away,
and he would make a mittimus to send me to prison when he had dined.
I told him, "`I desired his peace, and the good of his family,
and that they might be kept in the fear of the Lord;`" so I passed away.
And as we went the constable took some Friends`' word,
that I should come to his house the next morning by eight.
Accordingly I went with those Friends; and then the constable told us,
that he went to the justice for the mittimus after he had dined,
and he bid him come again after the evening service; which he did;
and then the justice told him he might let me go.
"`So,`" said the constable, "`you are discharged.`"
I blamed the constable for turning informer, and swearing against us;
and he said he would do so no more.
Next day the justice meeting with Gilbert Latey, asked him,
"`if he would pay twenty pounds for George Fox`'s fine.`"
He said, "`No.`" "`Then,`" said the justice, "`I am disappointed;
for being but a lodger I cannot come by his fine, and he having been brought before me,
and being of ability himself, I cannot lay his fine on any other.`"

[.small-break]
'''

After I was discharged, I went into the city.
The same week the sessions coming on, where many Friends were concerned,
some as prisoners, and some on trials of appeals upon the conventicle act,
I went to a Friend`'s house not far off,
that I might be in readiness to assist them with counsel, or otherwise,
as occasion should offer; and I found service in it.
But as my spirit was concerned on behalf of Friends,
with respect to their outward sufferings by the persecutors without;
so an exercise also came weightily upon me at this time,
in the sense I had of the mischievous working of that adulterated spirit, which,
being gone out from the heavenly unity,
and having drawn out some that professed truth
into enmity and opposition against Friends,
endeavoured to trouble the church of Christ with their janglings and contention.
And as a further discovery of the working of that seducing spirit,
and a warning to all Friends to beware of it,
I was moved to write the following epistle:--

[.blurb]
=== "`To all the elect, faithful, called, and chosen of God, the flock and heritage of God, who have been acquainted with the dealings of the Lord, and have kept your habitations in his life, power, and truth, being built upon the holy, heavenly rock and foundation, Christ Jesus, who was the foundation of the prophets and apostles; which foundation stands sure.

"`Many foundations have been laid since the apostles`' days,
by such as have gone from Christ, the true and sure Foundation;
but their foundations have proved rotten, and come to nought;
and they themselves have come to loss.
Many, since the day of Christ and the truth hath appeared in this nation,
have had some openings and sights, and come among us for a time;
and then gone out from us again; these have been the comers and goers,
like those in the apostles`' days.
Such had an outward profession of the truth, and have gone from the true foundation,
Christ Jesus, and so from the heavenly society and unity of the saints in light.
Then they set up foundations of their own; and having a form of godliness,
but out of the power thereof, out of the order thereof,
such have turned to janglings and vain disputings.
This sort of spirit you have been acquainted with,
who have kept your habitations in Christ Jesus, the First and the Last.
And you are not insensible of the scurrilous and filthy books of lies and defamations,
which have been spread abroad in this nation, and beyond the seas, against the faithful.
It is very well that the Lord hath suffered them to publish their own shame in print,
that truth`'s enemies may be discovered;
that their fruits and spirits have appeared and
manifested themselves both in print and otherwise.
And I do believe, that the Lord will yet suffer this spirit so to publish its fruits,
its shame and nakedness, to professor and profane, and to all sober, moderate,
and innocent people, that its shame and nakedness shall more fully appear.
Though for a time it hath been hid and covered
with the fig-leaves of an outward profession,
and sometimes with fawning and flattering words, as at other times,
it hath discovered itself by rough, lying, and defaming words;
yet the Lord God will blast all such vain talkers, that do not walk in the order of life,
truth, and the gospel.
Therefore, ye that are faithful,
stand fast in the liberty wherewith Christ hath made you free in his government.
It is upon his shoulders; he bears it up; of the increase of it, and of its peace,
there is no end.
For all quarrellers against his order and government are not in him, nor in his heavenly,
spiritual government and peace.
Therefore, ye faithful ones, who have stood the trial through many persecutions,
imprisonments, spoilings of goods;
you know that there is a crown of glory laid up for you.
You that suffer with Christ, shall reign with him in his kingdom of glory;
ye that die with Christ, shall live with him in eternal life,
in the world that hath no end, who have gone through the sufferings without, and within,
by false brethren, by comers and goers,
that have caused the way of truth to be evil spoken of,
and have been the persecutors of the faithful with their tongues;
and by printing and publishing their lying, defaming books against the faithful,
these have stirred up the magistrates and priests,
who were willing to get any occasion to speak evil of the right way,
and precious truth of Christ, by which his people are made free;
it would have been better for such had they never been born.
But God hath brought them to light, and their fruits and ravenous spirit are seen,
savoured, and known; who are become Judases, and sons of perdition,
to betray Christ now within (where he is made manifest) to the priests, magistrates,
and profane, as Judas betrayed Christ without to the priests and Pilate;
though some of the magistrates and sober people see their envy and folly,
and that they have more malice than matter against the faithful.
But the Lord will consume this Judas, or son of perdition.
The Lord will consume him with the Spirit of his mouth,
and destroy him with the brightness of his coming.
So let all the faithful look unto the Lord.
And let that wicked son of perdition know,
though he may be got as high as Judas without (who was
partaker of the ministry with the apostles),
'`the Lord will consume him with the Spirit of his mouth,
and destroy him with the brightness of his coming.`'
That is his portion.
The brightness of the Lord will destroy him, and the Spirit of his mouth will consume him.
And when he is destroyed and consumed,
there will not be a son of perdition to betray Christ in his people,
and his people that live and walk in Christ, who hath all power in heaven (mark,
in heaven) and in earth given to him;
and with his holy and glorious power he limits and orders;
so that nothing shall be done against his people,
but what is suffered for their trial and their good, neither by apostates,
persecutors with the tongue, Judases, sons of perdition to betray,
or the outward powers to imprison, or spoil goods;
all these are limited by Christ`'s power,
who hath all power in heaven and in earth given to him.
Every one`'s faith is to stand in him and his power, and rejoice in his power,
and see the increase of his righteous, holy, heavenly, spiritual, peaceable government,
in which the glorious, holy order of life is lived and walked in,
by all his sons and daughters.
In his Spirit is the holy unity and bond of peace;
though ye be absent in body one from another, yet all joying and rejoicing,
being present in his Spirit, and beholding in the same Spirit your spiritual order,
unity, and fellowship, and the steadfastness of your faith in Christ Jesus,
who is steadfast forever, the First and the Last, whose presence is among his people,
and who is their head.
Here is heavenly Zion known, and heavenly Jerusalem,
and the innumerable company of angels (which are
spirits) and the spirits of the just men made perfect.
Here is the general assembly, and a general, heavenly, holy,
and spiritual joy and rejoicing, lauding and praising the Lord God Almighty,
and the Lamb, that lives forevermore.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 14th of the 8th Month, 1683.

[.signed-section-context-close]
"`Read this in your assemblies amongst the faithful.`"

I tarried a little in London, visiting Friends and meetings,
and labouring in the work of the Lord there.
And being on a First-day at the Bull-and-Mouth, where the meeting had long been kept out,
it was that day in the house, peaceable and large;
the people were so affected with the truth,
and refreshed with the powerful presence of the Lord, that when it was ended,
they were loth to go away.

After some time, having several things upon me to write, I went to Kingston,
that I might be free from interruptions.
When I came there, I understood the officers had been very rude at the meeting,
abusing Friends, and had driven them out of the meeting-place,
and very abusive they continued to be for some time.
Whilst I was there I wrote a little book (printed soon after), entitled,
"`The Saints`' heavenly and spiritual worship, unity, and communion, etc.,
wherein is set forth what the true gospel worship is,
and in what the true unity and communion of the saints stands;
with a discovery of those that were gone from this holy unity and communion,
and were turned against the saints, that abode therein.`"

When I had finished the services for which I went thither, and had visited the Friends,
I returned to London, and visited most of the meetings in and about the city.
Afterwards I went to visit a Friend in Essex; and returning by Dalston,
made some stay at the widow Stot`'s, where I wrote an epistle to Friends,
which may be read amongst my other printed books.

I came from Dalston to London,
and next day was sent for in haste to my son Rous`'s at Kingston, whose daughter,
Margaret, lay very sick, and had a desire to see me.
I tarried now at Kingston about a week, and then returned to London;
where I continued for the most part of the winter and the spring following,
until the general meeting in 1684, save that I went once as far as Enfield,
to visit Friends thereabouts.
In this time I ceased not to labour in the work of the Lord, being frequent at meetings,
and visiting Friends that were prisoners, or that were sick;
and in writing books for the spreading of truth,
and opening the understandings of the people to receive it.^
footnote:[Frequent mention being made by George Fox of
his being engaged with his pen on behalf of the truth,
it may be well to apprize the reader that these volumes
contain only a very small portion of his writings.
Many others of his works were collected and printed in 1706, forming a large volume,
entitled, __Gospel Truth Demonstrated, in a collection of Doctrinal Books,
given forth by that faithful minister of Jesus Christ, George Fox, etc.__
This collection consists of above 1000 folio pages, comprising about 160 pieces,
the dates from 1653-1689.
{footnote-paragraph-split}
In addition to treatises
in explanation or defence of the principles and doctrines taught by George Fox,
this volume contains many others of a more extended character.
There are three addressed to the Jews;
and papers in behalf of the doctrine of the gospel, and against persecution,
to be delivered to the following rulers:--The Great Turk, the magistrates of Malta,
the Emperor of Austria, the Kings of France and Spain, the Pope,
and the Emperor of China.
And in 1688, Sultan Mahomet IV. having sent a defiance to the
Emperor Leopold in his Christian character,
threatening to ruin him, _and pursue his crucified God,_
George Fox wrote a Reply to this public document;
warning the Turk to fear the great God that made him and all things, and showing him,
out of their own Koran,
that the founder of their religion wrote more respectfully of Christ;
whom he then proceeds to set forth to the notice of the Sultan
by citations from the Scriptures.
{footnote-paragraph-split}
In the books and treatises forming the above collection,
the doctrine of our blessed Lord,
and these matters essential to salvation and true Christianity,
are plainly asserted and fully demonstrated according to the Scriptures.
For although he gave preference to the Holy Spirit (as all true spiritual Christians do),
yet his true love to, and sincere esteem of,
the Holy Scriptures (as being given by Divine inspiration), is clearly manifest: 1st,
In his frequent advice to Friends to keep to Scripture language, terms, words,
and doctrines, as taught by the Holy Ghost, in matters of faith, religion, controversy,
and conversation; and not to be imposed upon and drawn into unscriptural terms,
invented by men in their human wisdom.
2nd, In his great industry in searching the Scriptures, and frequently quoting, reciting,
aptly applying and opening the same in his writings, as appears in the above-named work.
He truly testified, both in his ministry and writings, of Christ Jesus, his power,
and coming, in the flesh and in the spirit.
He was both for the sacred history and mystery of Christ
revealed according to the Scripture testimonies of him,
respecting his sufferings without, the work of his power within,
and his kingdom and glory; and, under his guidance,
he faithfully warred against the spirit of Antichrist and persecution--
against the false church--the corruptions of the world,
its deceit and hypocrisy, under all professions.]

[.small-break]
'''

The Yearly meeting was in the 3rd month.
A blessed weighty one it was, wherein Friends were sweetly refreshed together;
for the Lord was with us, and opened his heavenly treasures amongst us.
And though it was a time of great difficulty and danger,
by reason of informers and persecuting magistrates,
yet the Lord was a defence and place of safety to his people.

Now had I drawings in Spirit to go into Holland, to visit the Seed of God there.
And as soon as the Yearly Meeting was over I prepared for my journey.
There went with me from London Alexander Parker, George Watts, and Nathaniel Brassey,
who also had drawings into that country.

We took coach the 31st of the 3rd month, 1684, and got to Colchester that night.
Next day being First-day, we went to the meeting there;
and though there was no notice given of my coming,
yet our being there was presently spread over the town,
and in several places in the country at seven and ten miles distance;
so that abundance of Friends came in doublehorsed, which made the meeting very large.
I had a concern and travail in my mind,
lest this great gathering should have stirred up the town,
and been more than the magistrates could well bear; but it was very quiet and peaceable,
and a glorious meeting we had,
to the settling and establishing of Friends both in town and country;
for the Lord`'s power was over all; blessed be his name forever!
Truly the Lord`'s power and presence was beyond words;
for I was but weak to go into a meeting,
and my face (by reason of a cold I had taken) was sore;
but God manifested his strength in us and with us, and all was well:
the Lord have the glory forevermore for his supporting power.
After the meeting,
I think above a hundred Friends of the town and country came to see me at John Furley`'s,
and very glad we were to see one another, and greatly refreshed together,
being tilled with the love and riches of the Lord; blessed be his name forever!
We tarried at Colchester two days more; which we spent in visiting Friends,
both at their meetings for business and at their houses.
Then early in the morning of Fourth-day we took coach for Harwich,
where we met William Bingley, and Samuel Waldenfield, who went over with us.
About eight at night we went on board the packet, Richard Gray master;
but by reason of contrary winds it was one in the morning before we sailed.
We had a very good passage;
and about five in the afternoon next day we landed at the Bkiel in Holland,
where we stayed that night.
Early next morning we went to Rotterdam, where we abode some days.
The day after we came to Rotterdam, one Wilbert Frouzen, a burgomaster,
and kinsman of Aarent Sunneman`'s, hearing I was there, invited me to his country house,
having a desire to speak with me about some business,
relating to Aarent Sunneman`'s daughters.
I took George Watts with me, and a brother of Aarent Sunneman`'s had us thither.
The burgomaster received us very kindly, and was very glad to see me;
and entering into discourse about his kinsman`'s daughters,
I found he was apprehensive that, their father being dead,
and having left them considerable portions,
they might be stolen and married to their disadvantage.
Wherefore I told him, "`that it was our principle and practice,
that none should marry amongst us unless they had a
certificate of the consent of their relations or guardians;
for it was our Christian care to watch over and
look after all young people that came among us;
especially those whose natural relations were dead.
And as for his kinsman`'s daughters,
we should take care that nothing should be offered to them but
what should be agreeable to truth and righteousness,
and that they might be preserved in the fear of God, according to their father`'s mind.`"
This seemed to give him great satisfaction.
While I was with him there came many great people to me,
and "`I exhorted them all to keep in the fear of God,
and to mind his good Spirit in them, to keep their minds to the Lord.`"
After I had stayed two or three hours, and had conversed with him on several things,
I took my leave of him, and he very kindly sent me to Rotterdam in his chariot.

Next day being First-day, we were at the meeting at Rotterdam, which was pretty large,
and declared to the people by an interpreter.
The day following Alderman Gaul came to speak with me,
with whom we had much discourse about religious matters; he seemed to be well satisfied,
and was very tender.
Several other persons of account had intended to come to speak with me that day,
but being hindered by extraordinary business (as I understood), they came not.

We went next day to Amsterdam, where we had a large and very precious meeting.
In the afternoon I was at another meeting with Friends there, about business.

There is a Yearly Meeting at Amsterdam for the Friends of Holland and Germany, etc.,
which begun now on the 8th of the 4th month,
and ended on the 12th. Here we had a fine opportunity of seeing Friends from many parts,
and of being refreshed together in the love of God.
After this meeting, before those that came out of the several provinces were gone,
we had a meeting with some particular Friends,
about the places and countries into which we who came out of
England in the work of the ministry were to travel;
and to inquire who among them were suitable persons to go along with us for interpreters.
When this was concluded on, William Bingley ^
footnote:[William Bingley became a minister among Friends while residing in Yorkshire,
and visited Ireland in 1675 and in 1682.
He settled in London as a stuff merchant when in the meridian of life;
and in 1684 accompanied Samuel Waldenfield on an
apostolic journey in Holland and the Netherlands.
He was one of the Friends who preached at the funeral of George Fox, in 1690;
and he appears to have paid religions visits to
different parts of Great Britain at various periods.
He died in London in 1714, aged sixty-four years.] and Samuel Waldenfield^
footnote:[Samuel Waldenfield, born at Edmondsbury, in Suffolk, in 1652,
was religiously inclined in his youth, and a hearer of the Independents.
But becoming convinced of the principles of truth, as held by Friends,
about the year 1670, he came forth a powerful preacher of the word of life; and,
with the Lord`'s blessing on his labours, many were convinced of the truth,
and turned from darkness to light, and from the power of Satan unto God,
and were as the seals of his ministry.
In 1684 he married, and settled in London,
continuing faithful and diligent in the work he was called unto;
and suffered for his testimony by imprisonment, etc.
His travels on gospel service, to the year 1700, were near 40,000 miles, which were also,
subsequently, very considerable.
Samuel Waldenfield is spoken of as being very considerate of the poor,
humble and merciful, and as an elder worthy of double honour.
He was a bright ornament to our religion in his conversation,
gaining great reputation to truth and Friends among rich and poor.
He was ill about two months before his decease,
during which time he uttered many expressions worthy of being noted.
He died in great peace in 1715.--See _Piety Promoted,_ vol. ii., pp. 218-252.]
took shipping for Friesland, with Jacob Claus, their interpreter.

Alexander Parker and George Watts remained with me.
We tarried a few days longer at Amsterdam, where I had further service.
Before I left I went to visit one Galenus Abrahams,
a teacher of chief note among the Mennonites, or Baptists.
I had been with him when I was in Holland about seven years before;
and William Penn and George Keith had disputes with him.
He was then very high and shy, so that he would not let me touch him,
nor look upon him (by his good will), but bid me "`Keep my eyes off him, for,`" he said,
"`they pierced him.`"
But now he was very loving and tender, and confessed in some measure to truth;
his wife also and daughter were tender and kind, and we parted from them very lovingly.

Feeling our spirits drawn towards Friesland, Alexander Parker, George Watts, and I,
having John Claus of Amsterdam with us for our interpreter, took shipping,
and having sailed nine or ten leagues, we left the ship and travelled through Friesland,
sometimes by boat, sometimes by waggon,
visiting Friends and tender people in the towns and villages where we came;
having one or two meetings in a day.
After we had been at Leuwarden, we passed by Franeker to Harxingen in West Friesland,
which was the furthest place we went to that way.
And having been six days from Amsterdam, and had very good service in that time,
visiting Friends and publishing truth amongst the people,
we took ship at Harlingen for Amsterdam on the 26th of 4th month,
and arrived there that night.
The First-day following we were at the meeting at Amsterdam,
which was very large and precious.
Many of the people were there, their teachers, and some great persons also.
They seemed very attentive; and a good opportunity we all had, one after another,
to declare the word of the Lord and open the way of truth amongst them,
John Claus interpreting for us.
I tarried next day at Amsterdam; but George Watts went to a burial at Haarlem,
attended by many hundreds of people, amongst whom he had a good opportunity,
and came back at night to us.

The day following we went by boat to Osan-Overton in Waterland, and thence,
in another small boat, about a league over a small river,
where we passed over and by a hundred bridges,
and so went to Lansmeer to a Friend`'s house whose name was Timon Peters;
where we had a very good meeting.
We returned to Amsterdam that night, and were at the meeting there next day.
Many were at this meeting besides Friends, and among the rest the great Baptist teacher,
Galenus, who was very attentive to the testimony of the truth, and when it was over,
came and got me by the hand very lovingly.

We went next day by boat to Alkmaar, about eight leagues from Amsterdam,
passing through Sardam, the great town of ship-carpenters,
and several other towns in the way.
At Alkmaar, which is a pretty city, we stayed,
and had a meeting next day at William Williams`'s. There were, besides Friends,
many very sober people at this meeting,
who were very attentive to the testimonies of truth,
that were borne both by Alexander Parker, George Watts, and myself,
John Claus being our interpreter.
This was on a sixth day, and on the seventh we returned to Amsterdam,
being willing to be at the meeting at Amsterdam on First-day,
because it was likely to be the last we should have there.
Accordingly we were at it, and a very large and open meeting it was.
Many great persons were at it, some earls, we were told, with their attendants,
out of Germany, who were very grave and sober,
and the everlasting gospel was preached unto them.

After this we took leave of the Friends of Amsterdam;
and next morning departed thence to Haarlem, where we had a meeting at a Friend`'s house,
whose name is Abraham Frondenberg.
Great numbers of people were at this meeting, and of great service it was.
After it a watchmaker of Amsterdam, who, with his wife, attended it,
desired to speak with me concerning religion.
I had much discourse with him, and both he and his wife were very low and tender,
received with gladness what I spoke to them,
and seemed well satisfied when they went away.

We went next day to Rotterdam, where we tarried two meetings;
and on the 16th of the 5th month went to the Briel, to take ship for England.

About four in the afternoon we went on board the packet, William Sherman master,
and set sail from the Briel.
But when we had gone over the Maese about a league,
we cast anchor at a place called the Pitt, because it is near to the sands,
where we stayed till about four next morning; when, having a pretty fair wind,
and the tide with us, we weighed anchor,
and by four next day were within five leagues of Harwich, over against Aldborough Castle;
but the wind falling short, and the tide being weak,
it was one in the afternoon before we came so near to Harwich
that boats could come to receive the passengers and goods.
There were on board about forty passengers in all; English, Scotch, Dutch, French,
Spanish, Flemish, and some Jews.

I spent a day with Friends at Harwich,
while Alexander Parker and George Watts went by water to visit Friends at Ipswich,
and returned at night.
Next morning early we all took coach for Colchester, and were at the meeting there,
which was large and peaceable; after it, we travelled to Witham,
and lodged there that night, Next day, William Mead meeting us on the way at Hare Street,
I went with him to his house, the other Friends going on for London.

Here, being weak with travel and continual exercise, I spent some time to rest myself,
and recover my health; visiting in the mean time the Friends in that part of the country,
as I was able to get abroad.^
footnote:[After returning from his last visit to Holland,
George Fox did not travel far from London,
his usual residence during the latter part of his life.
His health had been gradually declining for some years,
in consequence of his many and grievous imprisonments,
and the great fatigue of body and mind,
occasioned by his long travels for the promotion of the cause of truth,
and by his incessant labours in "`defence of the gospel`"
against the clamour and opposition of apostate brethren,
and the unfounded imputations of others,
decidedly hostile to the truth as it is in Jesus.
His solicitude, however, to promote the welfare of the Society,
and procure relief to his Friends under suffering, both at home and abroad,
remained undiminished.
In the course of his declining state, he wrote many epistles to his friends,
some of sympathy and consolation,
to encourage and strengthen them in their deep sufferings; others of counsel,
exhortation, and reproof,
"`stirring up the pure mind by way of remembrance,`"
and labouring to build them up in the most holy faith;
and, on all occasions, seeking not his own honour, but the honour of God only,
and the edification of his church and people.]

When I was a little recovered, I went to Enfield, visiting Friends there and thereabouts;
and so to Dalston to see the widow Stot; and thence to London,
some Friends being come over from New Jersey in America, about business,
which I was desired to be present at.

It was the latter end of the summer when I came to London,
where I stayed the winter following; saving that once or twice,
my wife being in town with me, I went with her to her son Rous`'s at Kingston.
And though my body was very weak; yet I was in continual service,
either in public meetings, when I was able to bear them,
or in particular business amongst Friends,
and visiting those that were sufferers for truth,
either by imprisonment or loss of goods.
Many things also in this time I wrote, some for the press,
and some for particular service; as letters to the King of Denmark and Duke of Holstein,
on behalf of Friends that were sufferers in their dominions; of the latter,
the following is a copy:--

[.blurb]
=== "`For the Duke of Holstein, whom I entreat, in the love of God, to read over this, which is sent in love to him.

"`I understand that formerly, by some evil-minded persons, it was reported to thee,
when Elizabeth Hendricks came to Frederickstadt to visit the people called Quakers,
that it was a scandal to the Christian religion,
that a woman should be suffered to preach in a
public assembly religiously gathered together, etc.
Upon which thou gave forth an order to the rulers of Frederickstadt,
'`to make the said people leave that place forthwith, or to send them away.`'
But the said rulers being Arminians, and they, or their fathers,
having come to live there, as a persecuted people in Holland,
not much above threescore years ago, made answer to the duke,
'`they were not willing to persecute others for conscience`' sake,
who had looked upon persecution on that account in their own case as antichristian,`' etc.
But after that, the people of God, in scorn called Quakers, wrote unto thee, O duke,
from Fredrickstadt; and since that time they have had their liberty,
and their meetings peaceable,
to serve and worship God almost these twenty years at Fredrickstadt, and thereabouts,
freely without any molestation;
which liberty they have acknowledged as a great favour and kindness from thee.

"`And now, O duke,
thou professing Christianity from the great and mighty name of Christ Jesus,
who is King of kings and Lord of lords,
and the Holy Scriptures of truth of the Old and New Testament,
do not you use many women`'s words in your service and
worship out of the Old and New Testament?
The apostle saith, '`Let your women keep silence in the churches`' and that,
'`he did not permit a woman to speak, but to be under obedience;
and if she will learn anything, to ask her husband at home;
for it is a shame for a woman to speak in the church.`'
And 1 Tim. 2:11,13. '`Women are to learn in silence and not suffered to teach,
nor to usurp authority over the man, but to be in silence.`'
1 Cor. 14:34. Now, here the duke may see,
what sort of women were to be in silence and in subjection,
whom the law commands to be silent, and not to usurp authority over the man,
nor to speak in the church; these were unruly women.
In the same chapter, he commands women '`not to plait or broider their hair,
nor to wear gold, pearls, or costly array.`'
These things were forbidden by the apostle; and such women, as wear such things,
are to learn in silence and to be subject, and not to usurp authority over the men;
for it is a shame for such to speak in the church.
But do not such women as these, that wear gold and silver, and pearls and gaudy apparel,
or costly array, and plait and broider their hair, speak in your church,
when your priest sets them to sing psalms?
Do not they speak when they sing psalms?
Consider this, O duke!
Yet you say, '`your women must keep silence in the church,
and must not speak in the church;`' but when they sing psalms in your churches,
are they then silent?
Though the apostle forbids such women before-mentioned to speak in the church,
yet in another place the apostle encourages the
good or holy women to be teachers of good things,
as in Tit. 2:4,8. The apostle said, '`I entreat thee, true yoke-fellow,
help those women which laboured with me in the gospel,
and with other my fellow-labourers, whose names are written in the book of life.`'
Here he owns these holy women, and encourages them,
which laboured with him in the gospel, and did not forbid them;
Phil. 4:2-3. He likewise commends Phoebe unto the church of the Romans,
calls her '`a servant unto the church of Cenchrea,`'
sends his epistle by her to the Romans from Corinth,
and desires the church at Rome to '`receive her in the Lord as becometh
saints:`' and to '`assist her in whatsoever business she had need of;
for she had been a succourer of many and of himself also.`'
And he said, '`Greet Priscilla and Aquila, my helpers in Christ Jesus,
who have for my life laid down their own necks; unto whom not only I give thanks,
but also all the churches of the Gentiles.`'
Now here the duke may see these were good, holy women,
whom the apostle did not forbid speaking, Rom. 16:1-4, but commended them.
And Priscilla and Aquila instructed and expounded unto
Apollos the way of God more perfectly,
Acts 18:26. So here Priscilla was an instructor as well as Aquila;
which holy women the apostle doth not forbid.
Neither did the apostle forbid Philip`'s four daughters, which were virgins, to prophesy.
Women might pray and prophesy in the church, 1 Cor. 11:5.

"`The apostles showed to the Jews the fulfilling of Joel`'s prophecy:
'`That in the last days God would pour of his Spirit upon all flesh,
and their sons and daughters, servants and handmaids,
should prophesy with the Spirit of God.`'
So the apostle encourages daughters and handmaids to prophesy as well as sons;
and if they do prophesy, they must speak to the church or people, Joel 2:28;
Acts 2:17-18. Did not Miriam the prophetess sing unto the Lord,
and all the women with her,
when the Lord had delivered the children of Israel from Pharaoh?
Did not she praise the Lord, and prophesy in the congregation of the children of Israel?
and was not this in the church?
Ex. 15:21. Moses and Aaron did not forbid her prophesying or speaking;
but Moses said,
'`Would God all the Lord`'s people were prophets!`'
and the Lord`'s people are women as well as men.
Deborah was a judge and a prophetess;
and do not you make use of Deborah`'s and Miriam`'s words in your service and worship?
See (Judg. 5:1-31) Deborah`'s large speech or song.
Barak did not forbid her, nor any of the Jewish priests.
Did not she make this speech or song in the congregation or church of Israel?
In the book of Ruth there are good speeches of those good women, which were not forbidden.
Hannah prayed in the temple before Eli, and the Lord answered her prayer.
See what a speech Hannah makes, and a praising of God before Eli the high priest,
who did not forbid her, 1 Sam. 2:1-10.
Josiah the king sent his priest,
with several others, to ask counsel of Huldah the prophetess,
who dwelt at Jerusalem in the college, 2 Kings 22:14;
2 Chron. 34:22. So here the king and his priests
did not despise the counsel of this prophetess;
and she prophesied to the congregation of Israel, as may be seen in these chapters.

"`And in Luke 1:41-55, see what a godly speech Elizabeth made to Mary,
and what a large godly speech Mary made also.
Mary said, '`that the Lord did regard the low estate of his handmaid,`' etc.
And do not you make use in your worship and service of
Mary`'s and Elizabeth`'s words from Luke 1:41-55,
in your churches, and yet forbid women`'s speaking in your churches?
Yet all sorts of women speak in your churches, when they sing, and say Amen.
In Luke 2 there was Anna the prophetess, a widow of about fourscore and four years;
who departed not from the temple, but served God with fasting and prayer night and day.
Did not she confess Christ Jesus in the temple, and give thanks to the Lord,
and '`speak of Christ to all that looked for redemption in Jerusalem?`'
Luke 2:36-38. So such holy women were not forbidden to speak in the church,
neither in the law nor gospel.
Was it not Mary Magdalene and other women that first
preached Christ`'s resurrection to the apostles?
The woman indeed (namely, Eve) was first in transgression;
and so they were women that first preached the resurrection of Christ Jesus;
for Christ said to Mary, etc., '`Go to my brethren, and say unto them,
I ascend unto my Father and to your Father,
and to my God and to your God,`' John 20:17. And Luke 24:10,
it was Mary Magdalene and Joanna, and Mary the mother of James,
and other women that were with them, who told the apostles,
'`that Christ was risen from the dead, and their words and these women`'s words,
were as idle tales to the apostles, and they believed them not,`' ibid.
ver. 11. And ver. 22, '`Certain women also of our company made us astonished,`' they said:
so here it may be seen,
that the women`'s preaching the resurrection of Christ did astonish the apostles.
Christ sent these women to preach his resurrection;
so it is no shame for such women to preach Christ Jesus;
neither are they to be silent when Christ sends them.
The apostle says, '`Every tongue shall confess to God,`' Rom. 14:11;
and '`Every tongue shall confess that Jesus Christ is Lord,
to the glory of God the Father,`' Phil. 2:11. So here it is clear,
that women must confess Christ as well as men, if every tongue must confess.
And the apostle saith, '`There is neither male nor female;
for ye are all one in Christ Jesus.`' Gal. 3:28.

"`And whereas it is said, '`Women must ask their husbands at home,`' etc.,
the duke knows very well virgins have no husbands, nor widows;
for Anna the prophetess was a widow; and if Christ be the husband,
men must ask counsel of him at home as well as women, before they teach.
And set the case, that a Turk`'s wife should be a Christian,
or a Papist`'s wife should be a Lutheran, or a Calvinist,
must they ask and learn of their husbands at home,
before they confess Christ Jesus in the congregation of the Lord?
Their counsel will be to them to turn Turks or Papists.

"`I entreat the duke to consider these things.
I entreat him to mind God`'s grace and truth in his heart that is come by Jesus;
that by his Spirit of Grace and truth he may come to
serve and worship God in his Spirit and truth;
so that he may serve the living eternal God that made him, in his generation,
and have his peace in Christ, that the world cannot take away.
And I do desire his good, peace, and prosperity in this world,
and his eternal comfort and happiness in the world that is everlasting. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, 26th of the 8th Month, 1684.

[.offset]
Besides the foregoing, I wrote also epistles to Friends;
of one of which the following is a copy:--

"`Friends and Brethren in the Lord Jesus Christ, in whom you have all life, peace,
and salvation; walk in Him, who is your heavenly Rock and Foundation, that stands sure,
who hath all power in heaven and earth given unto him.
So his power is over all.
Let your faith stand in his power, which is over all from everlasting to everlasting,
over the devil and his power; that in the holy, heavenly wisdom of God,
ye may be preserved and kept to God`'s glory, out of all snares and temptations;
so that God`'s wisdom may be justified of all his children in this day of his power,
and they all may be faithful, serving and worshipping God in his Spirit and truth,
and valiant for it upon the earth.
For, as the apostle saith, '`They that believe are entered into their rest,
and have ceased from their own works, as God did from his.`'
Now this rest is an eternal rest in Christ, the eternal Son of God,
in whom every true believer hath everlasting life in Christ Jesus,
their rest and everlasting day.
For Christ the Rest bruiseth the serpent`'s head, and through death destroyeth death,
and the devil, the power of death, and his works.
He is the Eternal Rest, that giveth eternal life to his sheep.
Christ fulfilleth the prophets, and all the figures, shadows, and ceremonies,
as in the Old Testament; and all the promises are yea and amen in Christ,
who was the Eternal Rest to all true believers in the apostles`' days, and ever since,
and is so now.
Christ is the beginning and the ending, the first and the last,
who is ascended above all principalities, powers, thrones, and dominions,
that he might fill all things.
For '`by Jesus Christ all things were made and created, whether they be things in heaven,
or things in the earth;`' and he is the Eternal Rest.
They that believe are entered into Christ, their Eternal Rest,
in whom they have eternal life and peace with God.
Wherefore I say again, in Him who is your Rest, live and abide; for in Him ye are happy,
and his blessings will rest upon you.
God Almighty keep and preserve you all, his true believers,
in Christ your Rest and Peace this day. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 18th of the 12th Month, 1684-5.

About a month after I got a little out of London, visiting Friends, at South Street,
Ford-Green, and Enfield, where I had meetings.
Afterwards I went to Waltham Abbey, and was at the meeting there on a First-day,
which was very large and peaceable.
Then returning through Enfield and Edmonton Side, I came back to London in the 3rd Month,
to advise with and assist Friends,
in laying their sufferings before the Parliament then sitting.
We drew up a short account thereof,
which we caused to be printed and spread among the Parliament-men.

The Yearly Meeting coming on,
I was much concerned for the Friends that came up to it out of the country,
lest they should meet with any trouble or disturbance in their passages up or down;
and the rather,
because about that time a great bustle arose in the
nation on the Duke of Monmouth`'s landing in the West.
But the Lord, according to his wonted goodness,
was graciously pleased to preserve Friends in safety,
gave us a blessed opportunity to meet together in peace and quietness,
and accompanied our meeting with his living, refreshing presence;
blessed forever be his holy name!

[.offset]
Now, considering the hurries that were in the nation, it came upon me,
at the close of this meeting, to write a few lines to Friends,
"`to caution all to keep out of the spirit of the world, in which the trouble is,
and to dwell in the peaceable truth;`" as follows:--

[.salutation]
"`Dear Friends And Brethren,

"`Whom the Lord hath called and chosen in Christ Jesus, your Life and Salvation,
in whom ye have all rest and peace with God; the Lord God by his mighty power,
which is over all, hath preserved and supported you to this day, to be a peculiar,
holy people to himself,
so that by his eternal Spirit and power ye might be all kept out of the world;
for in the world is trouble.
And now, in this great day of the Lord God Almighty,
he is shaking the heavens and the earth of outward professions,
their elements are in a heat, their sun and their moon are darkened, the stars falling,
and the mountains and hills shaking and tottering,
as it was among the Jews in the day of Christ`'s appearing.
Therefore, dear Friends and brethren, dwell in the Seed, Christ Jesus,
the Rock and Foundation, that cannot be shaken;
that ye may see with the light and Spirit of Christ,
that ye are as fixed stars in the firmament of God`'s power;
and in this his power and light, you will see over all the wandering stars,
the clouds without water, and trees without fruit.
That which may be shaken, will be shaken;
as will all they that are wandered from the firmament of God`'s power.

"`Dear Friends and brethren, you that are redeemed from the death and fall of Adam,
by Christ the second Adam, in Him ye have life, rest and peace; for Christ saith,
'`In me ye shall have peace; but in the world trouble.`'
And the apostle saith, '`They that believe, are entered into their rest,`' namely, Christ,
who hath overcome the world, who bruiseth the serpent`'s head,
destroys the devil and his works, and fulfils the types, figures,
and shadows of the Old Testament and the prophets; in whom the promises are yea and amen;
who is the first and the last, the beginning and the ending--the Eternal Rest.
So keep and walk in Christ, your Rest, every one that have received him.

"`And now, dear Friends and brethren, whatever bustlings and trouble,
tumults and outrages, quarrels and strife, arise in the world, keep out of them all;
concern not yourselves with them: but keep in the Lord`'s power and peaceable truth,
that is over all such things; in which power ye seek the peace and good of all men.
Live in the love which God hath shed abroad in your hearts through Christ Jesus;
in which nothing is able to separate you from God and Christ, neither outward sufferings,
persecutions, nor any outward thing, that is below and without;
nor to hinder or break your heavenly fellowship in the light, gospel,
and Spirit of Christ; nor your holy communion in the Holy Ghost,
that proceeds from the Father and the Son, and which leads you into all truth.
In this Holy Ghost, in which is your holy communion,
that proceeds from the Father and the Son,
you have fellowship with the Father and the Son, and one with another.
This is it which links and joins Christ`'s church or body together,
to Him the heavenly and spiritual head, and in unity in his Spirit,
which is the bond of peace, to all his church and living members,
in whom they have eternal rest and peace in Christ, and with God everlasting,
who is to be blessed and praised forever. Amen.

"`Dear Friends, forsake not the assembling of yourselves together,
who are gathered in the name of Jesus, who is your Prophet,
whom God hath raised up in the New Testament, to be heard in all things;
who opens to you, and no man can shut; and shuts, and no man can open;
who is your Priest, made higher than the heavens by the power of an endless life,
by whom you are made a royal priesthood, to offer up to God spiritual sacrifice;
who is the Bishop of your souls, to oversee you, that ye do not go astray from God;
who is the good Shepherd, that hath laid down his life for his sheep;
and they hear his voice, and follow him, and he gives them eternal life.

"`And now, dear Friends and brethren, abide in Christ, the vine,
that ye may bring forth fruit to the glory of God.
And as every one hath received Christ, walk in Him, who is not of the world,
that lies in wickedness;
so that ye may be preserved out of the vain fashions and customs of the world,
which satisfy the lust of the eye, the lust of the flesh, and the pride of life,
which are not of the Father, but of the world that passes away.
Whoever joins to that which is not of the Father, or encourages it,
draws the mind from God the Father, and the Lord Jesus Christ.
Therefore let Christ rule in your hearts, that your minds, souls,
and spirits may be kept out of the vanities of the world, in their words, ways,
and actions, that ye may be a peculiar people, zealous of good works,
serving the Lord through Jesus Christ, to the praise and glory of God;
that by the Word of his grace your words may be gracious,
and in your lives and conversations ye may show forth righteousness, holiness,
and godliness; that so God Almighty may be glorified in you all, and through you all,
who is above all, blessed and praised forever. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 11th of the 4th Month, 1685.

Several other letters also I wrote at this time to Friends in divers foreign countries,
from whom I had received letters about the affairs of truth.
Which when I had dispatched, the Yearly Meeting being over,
and country Friends for the most part being gone, I got a little way out of town;
being much spent with the heat of the weather, throngs in meetings,
and continual business.
I went at first to South Street, where I abode some days.
And among other services I had there,
a great sense entered me of the growth and increase of pride, vanity,
and excess in apparel; and that not only amongst the people of the world,
but too much also amongst some that came among us,
and seemed to make profession of the truth.
In the sense I had of the evil thereof, it came upon me to give forth the following,
as a reproof and check thereunto:--^
footnote:[Those Christians whose experience enters most deeply
into the spiritual nature of the gospel dispensation,
will find that it leads them into simplicity as regards their outward appearance.
The practice in the primitive church,
as regards "`outward adorning,`" is thus spoken of by Coleman,
in his _Antiquities of the Christian Church:_--
{footnote-paragraph-split}
Nothing may appear more purely a
matter of indifference than the fashion and colour of dress;
and yet, in the circumstances of the primitive Christians,
articles of that nature did acquire such an importance that they
gradually fell into a style of clothing peculiar to themselves.
Not that they affected any singularities in their personal appearance,
for their habiliments were made and worn in the ordinary fashion of the time and place;
and Christians, whether found in the high, the middle, or the lower ranks,
were accustomed to equip themselves in a manner suited to the
decencies of the state or profession to which they belonged;
but, looking to the moral influence of dress,
and desirous of avoiding everything that might minister to vanity,
or lead the wearer to forget, in attending to the outward man,
the ornament of a '`meek and quiet spirit,`' they studiously rejected
all finery as unbecoming the humility of their character,
and confined themselves to a suit of apparel,
remarkable not so much for the plainness of the
material as for the absence of all superfluous ornament.
Everything gaudy or sumptuous,
that partook of the costly stuffs or the crimson dyes
that suited the luxurious taste of the times,
was discountenanced by the spiritually minded followers of Christ.
The same simplicity reigned throughout their domestic establishments;
and even those of their number who were persons of rank and opulence,
chose to content themselves with such things as were
recommended by their utility rather than their elegance,
and calculated to answer the purposes of necessity and comfort,
rather than to gratify '`the lust of the eye, and the pride of life.`'
And however refined or exquisite the taste, which,
through education and the habits of society, any of them had acquired,
they learned to subject it to the higher principle of denying
themselves to everything that tended too much to captivate the senses,
and increase their love to a world, the fashion whereof, they thought,
was soon to pass away.`"
{footnote-paragraph-split}
The remarks of John Wesley on simplicity in dress are excellent,
but too long to be quoted here.
He says that "`following the fashions of the world is
directly at war with the spirit of the gospel.`"
See _Select Miscellanies,_ vol. v., p. 288,
for Wesley`'s views on this subject; also of T. A. Kempis, and others.]

[.small-break]
'''

"`The apostle Peter saith (in 1 Pet.
iii.) of the women`'s adorning; '`Let it not be (mark, let it not be;
this is a positive prohibition) that outward adorning of plaiting the hair,
and of wearing of gold, or of putting on of apparel;
but let it be the hidden man of the heart, in that which is not corruptible,
even the ornament of a meek and quiet spirit,
which is in the sight of God of great price;
for after this manner in the old time the holy women also, who trusted in God,
adorned themselves.`'

"`Here ye may see what is the ornament of the holy women,
which was in the sight of God of great price, and which the holy women,
who trusted in God, adorned themselves with.
But the unholy women, that trust not in God,
their ornament is not a meek and a quiet spirit;
they adorn themselves with plaiting the hair, putting on of apparel, and wearing of gold;
which is forbidden by the apostle in his general epistle to the church of Christ,
the true Christians.

"`And the apostle saith (1 Tim. 2:10-9), '`In like manner also,
that women adorn themselves in modest apparel, with shamefacedness and sobriety;
not with broidered hair, or gold, or pearls, or costly array,
but (which becometh women professing godliness) with good works.`'

"`Here ye may see what the women were not to adorn themselves with,
who professed godliness; they were not to adorn themselves with broidered hair, nor gold,
nor pearls, nor costly array;
for this was not looked upon to be modest apparel for holy women,
that professed godliness and good works.
But this adorning or apparel is for the immodest, unshamefaced, unsober women,
that profess not godliness, neither follow those good works that God commands.
Therefore it doth not become men and women who profess true Christianity and godliness,
to be adorned with gold, or chains, or pearls, or costly array; or with broidered hair;
for these things are for the last of the eye, the lust of the flesh,
and the pride of life, which are not of the Father.
All holy men and women are to mind that which is more precious than gold;
who are '`redeemed not with corruptible things, as silver and gold,
from your vain conversation; but with the precious blood of Christ,
as of a Lamb without blemish and without spot.
Therefore as obedient children to God,
not fashioning yourselves according to your former lusts in your ignorance;
but as he which hath called you is holy,
so be ye holy in all manner of conversation,`' 1 Pet. 1:14-15.

"`Christ saith, '`The life is more than meat,
and the body is more than raiment,`' Luke 12:23.

"`I read of a wise moral philosopher, who, meeting a woman with her neck and breast bare,
laid his hand upon her, and said, '`Woman, wilt thou sell this flesh?`'
and she replying, No; '`Then pray,`' said he,
'`shut up thy shop;`' (meaning her bare breasts
and neck.) So they were looked upon as harlots,
that went with their necks, breasts, and backs bare, and not modest people,
even among the moral heathens.
Therefore they that profess the knowledge of true Christianity,
should be ashamed of such things.
You may see a book written by the very Papists,
and another by Richard Baxter the Presbyterian, against bare breasts and bare backs.
They that were but in an outward profession, declared against such things;
therefore they who are in the possession of truth and true Christianity,
should be ashamed of such things.
Read, I pray you, the third of Isaiah,
and there see how that holy prophet was grieved with the foolish women`'s vain attire,
and how he was sent by the Lord to reprove them.
Envious, persecuting Jezebel`'s attired head and bravery,
like a painted harlot out of the truth, did not keep her from the judgments of God,
when the Lord stirred up Jehu against her.
Doth not pride go before a fall,
and a haughty mind before destruction`' God resisteth the proud,
and giveth grace to the humble.
Solomon saith,
'`The Lord will destroy the house of the proud,`' Prov. 15:25. '`For
the day of the Lord shall be upon every one that is proud and lofty,
etc., and he shall be brought low,`' Isa. 2:12, and Mal. 4.
Therefore take heed of calling the proud happy;
for '`the Lord will scatter the proud in the imaginations of their own hearts,
and exalt them of low degree.`'
And you may read in the Revelations (chap. 17:4, and 18:10),
of the false church, how she was outwardly decked, but full of abomination,
and came to a downfall at last.
Therefore it is good for all that profess the truth, to use this world as not abusing it;
for the fashion of this world passeth away; but the Word of the Lord endureth forever.
'`The Lord taketh pleasure in his people,
he will beautify the meek with salvation,`' Ps. 149:4.
All that know the truth as it is in Jesus,
are to be beautified and clothed with this salvation,
which salvation is a strong wall or a bulwark against that spirit,
that would lead you further into the fall from God,
into those things which the fallen man and woman delight in,
and beautify or adorn themselves with.
Therefore, all that profess the truth, be circumspect, sincere, and fervent,
following the Lord Jesus Christ, who is not of this world;
in whom ye have life and peace with God.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
South-street, the 24th of the 4th Month, 1685.
