== Chapter XII.

[.chapter-synopsis]
1685-1686.
* George Fox tarries in London, labouring in the service of Truth
* removes to Epping on account of his health
* writes an epistle to Friends
* returns to London
* writes a paper concerning order in the Church of God
* and a warning to backsliders
* assists in distributing money raised for sufferers by Friends in Ireland
* writes an epistle to the king of Poland, on behalf of Friends of Dantzic, who suffer imprisonment for conscience' sake
* a paper concerning judging
* looks diligently after Friends' sufferings in London, and obtains a general release of prisoners
* writes an epistle to Friends, many having been recently liberated from prison
* another on a similar occasion
* an epistle to Friends to keep in the unity in the Truth
* another to remind them of the evidence and seal they had received of their meetings for discipline having been set up in the power and spirit of God
* a paper concerning the state of the true Church
* a paper respecting the "`falling away`" foretold by the apostle Paul, 2 Thess. 2:3
* a paper showing how the Lord, in all ages, called the righteous out from amongst the wicked, before he destroyed the latter.

After I had been some weeks at South Street and Enfield,
in which time I had several meetings with Friends, I returned to London.
Amongst other services I found there,
one was to assist Friends in drawing up a testimony to clear our
Friends from being concerned in the late rebellion in the West,
and from all plots against the government: which was delivered to the chief justice,
who was then going down into the West with commission to try prisoners.

I tarried some time in London, visiting meetings,
and labouring among Friends in the service of truth.
But finding my health much impaired for want of fresh air,
I went to Charles Bathurst's country-house at Epping-Forest, where I stayed a few days.
While I was there it came upon me to write the following epistle to Friends:--

[.salutation]
"`Dear Friends,

"`Who are called, chosen, and faithful in this day of trial, temptations, and sufferings,
whom the Lord by his right hand hath upholden in all your sufferings
(and some to death) for the Lord and his truth's sake.
Christ saith, 'Be of good cheer, I have overcome the world; in me ye have peace;
but in the world ye have trouble.'
The children of the Seed, who are heirs of the kingdom, know this is true.
And though ye have trials by false brethren, Judases and sons of perdition,
that are got into the temple of God, and exalted above all that is called God,
whom the Lord will destroy with the breath of his mouth,
and the brightness of his coming: and though ye be tried by powers or principalities,
yet there is nothing able to separate you from the love of God,
which ye have in Christ Jesus.
In that love dwell, which bears all things and fulfils the law;
in which edify one another, and be courteous, kind, and humble;
for to such God giveth his grace plentifully, and such he teacheth.
And pray in the Holy Ghost, which proceeds from the Father and the Son;
in it keep your holy communion, and unity in the Spirit, the bond of peace,
which is the King of kings' heavenly peace.
In that you are all bound to good behaviour, to keep peace among yourselves,
to seek the peace of all men; and to show forth the heavenly, gentle,
and peaceable wisdom to-all, in righteousness and truth,
answering the good in all people in your lives and conversations (for
the Lord is glorified in your bringing forth spiritual fruit),
that ye may eye and behold the Lord in all your actions;
that his blessings ye may all feel to rest upon you.
Whether ye be the Lord's prisoners for his name and truth's sake, or at liberty,
in all things labour to be content, for that is a continual feast;
and let no trouble move you; then ye will be as Mount Sion, that cannot be removed.
In all things exercise the word of patience, which word will sanctify all things to you.
Study to be quiet, and do the Lord's business that he requires of you, and your own,
in truth and righteousness: and whatsoever ye do,
let it be done to the praise and glory of God in the name of Jesus Christ.
All they that make God's people suffer, make the Seed suffer in their own particulars,
and imprison the Just there.
Such will not visit the Seed in themselves, but cast it into prison in others,
and not visit it in prison.
You may read that Christ saith, such must go into everlasting punishment.
That is a sad punishment and prison.
All such as become apostates and backsliders, that crucify to themselves Christ afresh,
put him to open shame, and trample under feet the blood of the Son of God,
by which they were cleansed, and come to be unclean; such, grieve, vex, quench,
and rebel against, the Spirit of God in themselves;
and then rebel against them that walk in it.
Such are unfaithful to God and man,
and are enemies to every good work and service of God:
but their end will be according to their works; who are like unto the earth,
that hath often received rain, but brings forth briars and thorns,
which are to be rejected, and are for the fire.
Therefore, dear Friends, in all your sufferings feel the Lord's eternal arm and power,
which hath supported you to this day, and will to the end, as your faith stands in it,
and as you are settled upon the rock and foundation Christ Jesus, that cannot be removed;
in whom ye have life and peace with God.
The Lord God Almighty in him give you dominion, and preserve you all to his glory;
that in all your sufferings ye may feel his presence: and that,
when ye have finished your testimony, ye may receive the crown of glory,
which God hath laid up for them that fear and serve him.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 15th of the 7th Month, 1685.

Having spent about a week in the country, I returned to London;
where I continued about two months, visiting meetings,
and labouring to get relief for Friends from their sufferings,
which yet lay heavy upon them in many parts of the nation.
Several papers also I wrote relating to the service of truth,
one of which was concerning order in the church of God,
which some that were gone out of the unity of Friends much opposed.
It was as follows:--

"`Among all societies, families, or nations of people in the world,
there exists some sort of order.
There was the order of Aaron in the Old Testament;
and the order of Melchizedeck before that, after whose order Christ Jesus came;
and he did not despise that order.
God is a God of order in his whole creation, and in his church:
and all believers in the light, the life in Christ, that pass from death to life,
are in the order of the Holy Spirit, power, light, life, and government of Christ Jesus,
of the increase whereof there is no end.
This is a mystery to all those disorderly people,
who have written and printed so much against the order which the Lord'
s power and Spirit hath brought forth among his people.
And you that cry so much against order,
is it not manifest that you are gone into a land of darkness, and of the shadow of death,
into disorder, and where the light is as darkness?
Is not this your condition seen by all them that live and walk in the truth,
whose conversations are according to the gospel of life and salvation?

"`The devil, Satan, dragon, the first and second beast, the whore and false prophets,
and their worshippers and followers, are all out of the truth, abode not in it,
nor in the order of it; and the truth is over them all.
In Salem is God's tabernacle; and his tabernacle is in Shiloh;
these are far beyond the tabernacles of Ham (Ps. 76 and 78).

"`All the figures and shadows were and are comprehended in time;
but Christ the substance is the beginning and the ending.
And all trials, troubles, persecutions, and temptations, came up in time;
but the Lord's power which is everlasting, is over all such things; in which is safety.

"`The black world of darkness lieth in wickedness, and by its wisdom knoweth not God,
that made the world and all things therein;
for the god of the world and prince of the air ruleth in the
hearts of all that disobey the living God that made them.
So the God of this wicked world hath blinded the eyes of the infidels or heathen;
so that by their wisdom they know not the living God.

"`In the Old Testament the Lord said,
'With all thy offerings thou shalt offer salt,' Lev.
2:13. And Christ saith in his new covenant,
'Every one shall be salted with fire, and every sacrifice shall be salted with salt.
Salt is good; but if the salt have lost its saltness, wherewith will you season it?
Have salt in yourselves; and have peace one with another,' Mark 9:49-50.

"`We have received the earnest of the Spirit, which is the earnest of the inheritance,
that fadeth not away.
For God poureth out of his Spirit upon all flesh.
It is God's Spirit which is above our natural spirit, by which alone we do not know God;
for it is by the Spirit of God that we know the things of God.
And the Spirit of God doth witness to our souls and spirits,
that this Spirit of God is the earnest of an eternal inheritance.
'God opens his people's ears to discipline, and commands that they turn from iniquity.
If they obey and serve him,
they shall spend their days in prosperity and their years in pleasure;
but if they obey him not they shall perish by the sword,
and they shall die without knowledge,' Job 36:10-12. So the disobedient
that do not turn from their iniquity have not this prosperity and pleasure,
but die without the knowledge of God; and their ears are shut to this discipline,
which God opens to his people.`"

[.signed-section-signature]
G+++.+++ F.

When I had been about two months in London, I was sent for to my son Rous's at Kingston,
to visit a daughter of his, who at that time lay very sick; but recovered.
Whilst I stayed there I had several meetings with Friends; and returning by Hammersmith,
stayed the First-day meeting there, which was large and peaceable.
Having visited Friends thereabouts, I came back to London again,
being very intent upon the business of getting redress for suffering Friends.
In this and other services I continued at London, till the latter end of the 11th month;
save that I went to visit an ancient Friend at Bethnal-green,
with whom I tarried three or four days.
While I was there, I was much exercised in the sense of the enemy's working,
to draw from the holy way of truth into a false liberty,
and so into the world's ways and worships again.
And the example of the backsliding Jews coming before me,
I was moved to write the following as a warning to all such:--

[.small-break]
'''

"`You may see, when the Jews rebelled against the good Spirit of God,
which he gave to instruct them, they forsook him and his law, way, and worship,
and went a whoring after Balaam's ways, and became like the wild ass's colt,
snuffing up the wind, as in Jer. 2:24. And in Jer. 3,
see how Judah played the harlot under every green tree,
and upon every high mountain; and therefore the Lord divorced Judah,
as he had divorced Israel, when she forsook his way and followed the ways of the heathen.
Though the Lord had fed them to the full, yet they forsook him, 'they committed adultery,
and assembled themselves together in harlots' houses.'
Jer. 5:7. 'And with their whoredom they defiled the land, and committed,
adultery with stocks and stones.'
Jer. 3:9. Here you may see, when they forsook the living eternal God,
they followed the religions and worships of other nations,
whose gods were made of stocks and stones, which the Jews worshipped,
and committed adultery withal.
When they forsook the living God, and his way and worship,
they forsook the worship at the temple at Jerusalem,
and followed the heathen's worships in the mountains and fields;
so it was called adultery and whoredom to join with other religions and forsake God;
as in Jer. 13:27.

"`And now, if the children of New Jerusalem that is above, should forsake the worship,
that Christ in his New Testament set up (which is in
Spirit and in truth) and follow the worships of nations,
which men have set up, will not they that do so, commit adultery with them,
in forsaking God's worship, and Christ, the new and living way?

"`In Jer. 44, ye may see how the children of Judah provoked the Lord against them,
by worshipping the works of their own hands, and following the gods of the land of Egypt.
In this they committed adultery, forsaking the living God, their husband,
and his worship;
and there ye may see God's judgments pronounced against them to their destruction.
And what will become of those that forsake the worship in Spirit and in truth,
which Christ set up, and worship the works of their own hands in spiritual Egypt,
and follow spiritual Egypt's will-worship, which they invented?
may not this be called whoredom in them that forsake Christ, the new and living way,
and his pure religion, and his worship, that he hath set up?
And they that forsake the Lord's way, and his worship that he set up,
and follow the world's ways and worships that they set up, do not they,
whose way they follow, become at last their enemies?
as in Lam. 1.
See how the Jews forsook the Lord's way and worship,
and doted on their lovers (the Assyrians, etc.),
and with all their idols they were defiled;
and how they did not leave the whoredoms brought from Egypt,
and how they were polluted with the Babylonians' bed; as ye may read in Ezek. 23.
When they forsook the Lord, his way and worship,
and followed the way and worship of the heathen;
then it was said they went a whoring after other lovers,
and committed adultery with them.

"`Ye may see in Ezek. 16 the state of the Jews was likened unto that of their sister Sodom,
and how they had played the harlot with the Assyrians,
and committed fornication with the Egyptians,
and had increased their whoredoms in following their abominable idols.
And therefore the Lord carried away the two tribes that forsook him into Babylon;
as you may see in Ezek. 17:20. And they that forsake Christ, the new and living Way,
and the worship of God in Spirit and in truth, which Christ set up in his New Testament,
go into captivity in spiritual Babylon.

"`In Hosea ii., see how he discovers the whoredoms and idolatry of the Jews,
who forsook the Lord, and compares them to a harlot.
And in chap, viii., the destruction threatened against the Jews,
for their impiety and idolatry.
In chap. 9 also,
the distress and captivity of the Jews is threatened for their sins and idolatry.
And again they are reproved and threatened for their impiety and idolatry, Hos. 10.
This was for forsaking the Lord and his way,
and following the ways of their own inventions, and the ways of the heathen.

"`Doth not Isaiah say, 'That the Lord would visit Tyre,
and that she should commit fornication with all the kingdoms of the world upon the
face of the earth;' and therefore the Lord threatened destruction upon her,
chap, 23.
And in chap. 57 see how the Lord reproved the Jews for their whorish idolatry,
and said, 'Upon a high and lofty mountain hast thou set thy bed;
even thither wentest thou up to offer sacrifices.
Thou hast enlarged thy bed, and made a covenant with them; thou lovedst their bed,
where thou sawest it.'
This was a joining to the heathen's religions, altars, and sacrifices,
and a forsaking of the Lord's altar and sacrifices, which he commanded in the law;
and therefore that was committing whoredom with the heathen,
and going into their beds from the living God that made them.
And now in the New Testament God having 'poured his Spirit upon all
flesh,' that by his Spirit all might come to be 'a royal priesthood,
to offer up spiritual sacrifices to God by Jesus Christ;' all
that err from the Spirit of God and rebel against it,
are not like to offer spiritual sacrifices to God;
the sacrifice of such God doth not accept, no more than he did that of the heathens,
or of the Jews, who rebelled against his good Spirit, that he gave to instruct them.

"`And ye may see in the 17th, 18th, and 19th chapters of the Revelations,
the punishment of the great whore, Babylon, the mother of harlots;
and the victory of the Lamb, and how he calleth God's people out of Babylon;
for 'in her was found the blood of the prophets, and of the saints,
and of all that were slain upon the earth.'
There ye may read her judgment and her downfall.
This whore are they, that are whored from the Spirit of God,
and so from God and from his holy worship in spirit and in truth, from the pure,
undefiled religion, that keeps from the spots of the world,
and from the new and living way, Christ Jesus;
these are whored from the Spirit of God into false religions, ways, and worships,
and so have corrupted the earth with her abominations.
But her judgment and downfall are seen, over whom Christ hath the victory;
and the marriage of the Lamb is come, glory to the Lord for ever!
And God's pure religion, and pure worship in Spirit and in truth Christ hath set up,
as it was in the apostles' days. Hallelujah!`"

[.signed-section-signature]
G+++.+++ F.

I soon returned to London, but made no long stay there,
my body not being able to bear the closeness of the city long together.
While I was in town, besides the usual services of visiting Friends,
and looking after their sufferings to get them eased,
I assisted Friends of the city in distributing certain sums of money,
which our Friends of Ireland had charitably and very liberally raised,
and sent over for the relief of their brethren,
who suffered for the testimony of a good conscience;
which money was distributed amongst poor, suffering Friends in the several counties,
in proportion as we understood their need.

Before I left the city, I heard of a great doctor lately come from Poland;
whom I invited to my lodging, and had much discourse with him.
After I had informed myself by him of such things as I had a desire to know,
I wrote a letter to the King of Poland on behalf of Friends at Dantzic,
who had long been under grievous sufferings.
A copy whereof follows:--

[.alt]
=== "`To John the Third, King of Poland, great Duke of Lithuania, Russia, and Prussia, Defender of the city of Dantzic, etc. Concerning the innocent and afflicted people, in scorn called Quakers, who are now fed with bread and water in Bridewell of the aforesaid city, under close confinement, where their friends, wives, and children, are hardly suffered to come to see them,

[.salutation]
"`O King!

"`The magistrates of the city of Dantzic say, that it is thy order and command,
that these innocent and afflicted people should suffer such oppression.
Now this punishment is inflicted upon them only because
they come together in the name of Jesus Christ,
their Redeemer and Saviour, who died for their sins,
and is risen from the dead for their justification; who is their Prophet,
whom God hath raised up like unto Moses;
whom they ought to hear in all things in this day of the gospel and new covenant;
who went astray like scattered sheep,
but now are returned to the chief Shepherd and Bishop of their souls,
1 Pet. 2:25. 'Who has given his life for his sheep,
and they hear his voice and follow him who leads
them into his 'pastures of life,' John x.

"`Now, O King!
I understand that thou openly professest Christianity,
and the great and mighty name of Jesus Christ, who is King of kings, and Lord of lords,
to whom is given all power in heaven and in earth,
who rules all nations with a rod of iron.
Therefore, O king, it seems hard to us, that any who openly confess Christ Jesus (yea,
the magistrates of Dantzic do the same) should inflict
those punishments upon an innocent and harmless people,
by reason of their tender conscience,
only because they come together to serve and worship the Eternal God, who made them,
in Spirit and in truth; which worship Christ Jesus set up sixteen hundred years ago;
as we read in John 4:23-24.

"`I beseech the king, that he would consider, whether Christ in the New Testament,
ever gave such a command to his apostles, that they should shut up any in prison,
and feed them with bread and water,
who were not conformable in every particular to their religion, faith, and worship?
Where did the apostles exercise such things in the true church after Christ's ascension?
Is not this the doctrine of Christ and the apostles,
that his followers should 'love their enemies, and pray for them that hate them,
and persecute and despitefully use them?' Matt. 5.

"`Is it not a shame to Christendom among the Turks and others,
that one Christian should persecute another for the doctrine of faith,
worship, and religion?
They cannot prove that Christ ever gave them such a command,
whom they profess to be their Lord and Master.
For Christ says,
that his believers and followers should 'love one another,'
and by this they should be known to be his disciples.
And did not Christ reprove those who would have 'fire to come
down from heaven,' to destroy them who would not receive him?
and did not he tell them, 'they did not know what spirit they were of?'
Have all who have persecuted men, or taken away their lives,
because they would not receive their religion, known what spirit they were or are of?
Is it not good for all to know, by the Spirit of Christ, what spirit they are of?
For the apostle says, Rom. 8:9, 'If any man have not the Spirit of Christ,
he is none of his.'
And 2 Cor. 10:4, 'The weapons of our warfare are not carnal, but spiritual,' etc.
And 'We wrestle not against flesh and blood, but against spiritual wickedness,' etc.
Thus we see, that the fight of the first Christians,
and their weapons in the days of the apostles, were spiritual.

"`Now would not the king and the magistrates of
Dantzic think it contrary to their consciences,
if they should be forced by the Turk to his religion?
Would it not in like manner seem hard to the magistrates of Dantzic,
and contrary to their consciences,
if they should be forced to the religion of the King of Poland?
or to the King of Poland,
if he should be compelled to the religion of the magistrates of Dantzic?
And if they would not be subject thereunto,
that then they should be banished from their wives and families,
and out of their native country,
or otherwise be fed with bread and water under strict confinement?

"`Therefore we beseech the king with all Christian humility, and the magistrates,
that they would order their proceedings in this matter according to the royal law of God,
which is, 'to do unto others as they would have others do unto them,'
and 'to love their neighbour as themselves.'
For we have this charity, that we hope and believe,
that the King of Poland and his people, with the magistrates of Dantzic,
own the writings of the New Testament, as well as of the Old;
and therefore we beseech the king and magistrates to take heed,
that their work of imprisoning an innocent people,
for nothing but their meeting together, in tenderness of conscience,
to serve and worship God, their Creator,
may not be contrary and opposite to the royal law of God,
and to the glorious and everlasting gospel of truth.

"`We desire the king, in Christian love,
earnestly and weightily to consider these things,
and to give order to set the innocent prisoners, our friends, called Quakers,
at liberty from their strict confinement in Dantzie;
that they may have freedom to serve and worship the Living God in Spirit and in truth,
to go home to their habitations, and follow their trades and calling,
to maintain their wives, children, and families.
And we believe that the king, in doing such a noble, glorious, yea Christian work,
will not go unrewarded from the Great God who made him, whom we serve and worship,
who has the hearts of kings, and their lives and length of days in his hands.

"`From him who desires that the king and all his
ministers may be preserved in the fear of God,
and receive his Word of wisdom, by which all things were made and created;
that by it he may come to order all things to the glory of God,
which God has put under his hand:
that both he and they may enjoy the comforts and blessings of the Lord in this life,
and in that which is to come, life eternal.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 10th of the 3rd Mouth, commonly called May, 1684.

"`__Postscript.--__The king may please to consider,
that his and all men's consciences are the prerogative of God.`"

After this I went to Enfield, where, and in the country around,
several Friends had country-houses, amongst whom I tarried some time,
visiting and being visited by Friends, and having meetings with them.
Several things I wrote in this time, relating to the service of truth;
one was 'Concerning judging:' for some, who had departed from the truth,
were so afraid of its judgment,
that they made it much of their business to cry out against judging.
Wherefore I wrote a paper, proving by the Scriptures of truth,
that the church of Christ has power and ability to judge those that profess to be of it,
not only with respect to outward things relating to this world,
but with respect to religious matters also.
A copy of which follows:--

[.alt]
=== Concerning Judging.

"`'The natural man receiveth not the things of the Spirit of God,
for they are foolishness to him, neither can he know them,
because they are spiritually discerned;
but he that is spiritual judgeth all things (mark) all things;
yet he himself is judged of no man,' 1 Cor. 2:14-15. So
the natural man cannot judge of those things he receives not,
for they are foolishness to him; but he is comprehended by the spiritual man,
and his foolishness, and is judged, though he cannot judge the spiritual man.

"`'Do not ye judge them that are within?'
saith the apostle (this power the church had, and hath),
therefore put away from amongst yourselves that wicked person.'
Did not this wicked person, think you, profess and plead for liberty for his wickedness,
and his freedom, as he was a Christian, who was looked upon as a member of the church?

"`The apostle saith, 'For I verily, as absent in body, yet present in spirit,
have judged already, as though I were present,
concerning him that hath done this wicked deed,'
1 Cor. 5:12-3. Here the apostle judged,
though afar off, and set up judgment in the church against false liberty,
under what pretence soever it was.

"`And the apostle saith, 'Dare any of you, having a matter against a brother,
go to law before the unjust, and not before the saints?'
Here the saints, the church, are to judge of things amongst themselves,
and not for the unjust to judge of their matters.
'Do ye not know the saints shall judge the world?'
So the saints are to judge the unjust, and not the unjust to judge their matters.

"`And farther, the apostle saith, 'If the world shall be judged by you (to wit,
the saints), are you unworthy to judge the smallest matters amongst you?'

"`It is clear that the saints have a judgment given them of Christ,
by his power and Spirit, light and wisdom, to judge the world,
and not to carry their matters before the unjust,
but to judge of them amongst themselves; and if they carry them before the unjust,
they show their unworthiness of the saints' judgment.

"`Again, 'Know ye not that we shall judge angels?
(and angels are spirits) how much more things which pertain to this life?'

"`'If ye then have judgment of things pertaining to this life,
set them up to judge who are least esteemed in the church,' 1 Cor. 6:4.
Here it is clear the church of Christ has a judgment in the power and Spirit of God,
not only to judge in things that pertain to this life,
but are also to judge of things between brethren,
without brother going to law with brother before unbelievers; which was a fault,
and to be judged, if they did so.

"`But also the saints have a judgment to judge angels that kept not their habitations,
and the world.
As in Jude, 'He judged the angels that kept not their habitations, their first state.'
Did not he judge in divine matters here?
He judged the state of Cain, and Balaam, and Core,
and such Christians as were gotten into their steps, and were gone as far as they,
though they professed themselves Christians?
Here again he judged in divine matters; and of their states and beings,
who stood in the divine principle, and who were fallen from it.

"`The apostle saith, 'Try the spirits, and believe not every spirit,' 1 John iv.
Here again was a judgment in divine matters; and he judged such as went out from them;
these, whilst they were with them, had sight of things and openings;
but when they went from them they went from the anointing;
and therefore he exhorts the saints to keep to the anointing.
Such as went from them that had the anointing,
came to be the seducers and false prophets that went into the world.

"`John had a judgment to try sacrifices, and distinguished Cain's from Abel's; and,
by the Spirit of God, knew which God accepted, and which he did not accept,
1 John 3:12. Paul judged and tried such messengers and apostles,
and transformers of themselves like to the apostles of Christ;
and would have the church to try such, and have the same judgment that he had, 2 Cor. 11.

"`The apostle Peter judged Ananias and Sapphira, and the thoughts of Simon Magus,
who would have been a worker of miracles for money.
Was not all this judgment in divine matters?
And the apostle Paul judged the preachers of circumcision,
both in the Romans and Galatians.
For it was the faith and liberty of those preachers to preach up circumcision,
though it was a wrong faith.
Did not the apostle here again judge in divine matters?

"`James judged in matters of faith, and manifested the living faith from the dead one.
He also judged in matters of religion, the vain from the pure religion,
and distinguished them.

"`Paul judged of the false brethren, that would spy out the liberty of the true;
to whom he would give no place by subjection, no, not for an hour,
that the truth of the gospel might continue with the saints; as in Gal.
ii. Did not the apostle here judge in divine matters?
And he judged concerning the matters of the gospel when
some came to pervert them with another gospel,
and said, 'The gospel which I received is not of man, neither was I taught it,
but by the revelation of Jesus Christ,' Gal. 1:12. So here was a
judgment to distinguish the gospel of Christ from all other gospels,
which were accursed, which are after man, received and taught of man,
and not by the revelation of Jesus Christ, Gal. 1.
And he had a judgment to know, 'who made the gospel chargeable,
and who kept it without charge.'

"`He set up a judgment in the church that the believers should not be unequally yoked;
and to see when men had a communion in the light, and when they had it in the darkness;
when with Christ, and when with Baal; with the believer and unbeliever;
with the temple of God and with idols: as in 2 Cor. 6.
Did he not set up a clear judgment here in divine matters in the church?

"`And the apostle judged such libertines as through
their knowledge could sit at meat in the idol's temple;
who through their knowledge and liberty caused the weak brother to perish,
for whom Christ died.
These, it is like, did profess it was their faith and their liberty;
yet they did not keep in the unity of the true faith, but went about to destroy it,
1 Cor. 8.

"`Peter gives judgment upon the angels that sinned, and were cast down into hell;
upon the state of the old world, and of Sodom,
and the state of the false prophets then amongst them,
that could speak great swelling words of vanity; and whilst they promised them liberty,
they themselves were the servants of corruption.
And had not Peter here a judgment in divine matters?
These were such whose work was to bring into bondage,
and these were like the dog and sow that were washed;
which shows that they had been washed, but were turned into the mire again.
The apostle Paul had a judgment upon such as, with their fair words and men's wisdom,
deceived the hearts of the simple; and upon such as 'served not the Lord Jesus Christ,
but their own bellies, and were enemies to the cross of Christ.'
He had a judgment and discerning who lived in the cross of Christ, and who did not;
and exhorted all to live in the cress of Christ, the righteous power of God,
that slew all deceit, and the deeds of the old man, agreeably to Christ's words,
'He that will be my disciple, must take up his cross and follow me.'
Was not here a judgment again in divine matters, of such as walked in the divine power,
and such as did not?

"`Christ sets up a judgment in his seven churches,
and commends them that did keep in his judgment, and had tried them which said,
'they were apostles,' who might pretend they were sent of God and Christ, and were not;
but the church of Christ had found them liars.
Christ commended this judgment of the church of Ephesus,
because they had 'not borne with them that were evil,
but had tried those false apostles:' and Christ commends this church,
for they had 'hated the deeds of the Nicolaitanes,
which he also hated:' and had not these Nicolaitanes sprung from Nicolas,
one of the deacons?
and were not these become a sect of Christians?
though they might talk and preach of Christ, yet Christ hated their doctrine.

"`Christ saith to the church of Smyrna,
'I know the blasphemy of them which say they are Jews, and are not,
but are of the synagogue of Satan.'
So the church is to have a judgment upon these blasphemers,
and to distinguish the Jews in the Spirit from such as are not,
but of the synagogue of Satan.

"`To the church in Pergamos Christ saith, 'I have a few things against thee,
because thou hast there them that hold the doctrines of Balaam,' etc.,
and 'also them that hold the doctrine of the Nicolaitanes, which thing I hate.'
Now, these that held the doctrine of Balaam, and the doctrine of the Nicolaitanes,
were got into the church, and might look upon themselves to be high Christians,
and take great liberty to go into Balaam's doctrine, and Nicolas's doctrine,
which was hated by Christ;
but the church was to keep a spiritual and divine judgment upon the heads of all these.

"`To the church of Thyatira, saith Christ, 'I have a few things against thee,
because thou sufferest the woman Jezebel to teach, which seduces my people,' etc.
Here was a suffering, which should have been a judgment by Christ's Spirit,
upon that Jezebel, which was erred from his Spirit, and so from Christ.
Such as these were high preachers.
And is not the church to beware of suffering such now,
lest they come under the reproof of Christ,
for not passing judgment against the false teacher and seducer?

"`The church of Sardis 'had a name to live, but was dead,
and her works were not found perfect before God.'
There is a judgment to be set up in the church, to judge all imperfect works,
and such as would have a name, but not the nature; a name to live, but are dead.
All the members of Christ's church must be in Christ, living members,
and live to his name.
This church had a few names that had not defiled their garments, that did walk in white;
but such as have a name to live, but are dead, whilst they are in the dead state,
cannot walk in white, nor judge in divine matters.
'Behold,' saith Christ, 'I will make them of the synagogue of Satan,
which say they are Jews, and are not, but do lie; behold, I will make them to come,
and to worship before thy feet, and to know that I have loved thee,' Rev. 3:9.

"`And to the church of Laodicea, that was 'neither cold nor hot,' but lukewarm.;
'I would thou wert cold or hot: I will spew thee out of my mouth,
because thou saidst thou wast rich, and wanted nothing;' when thou wast 'wretched,
miserable, poor, blind, and naked.'
Now this was for want of living in the Power and Spirit of Christ.
These could talk of high experiences, and great enjoyments, but were naked, miserable,
and blind; so lived not in the power, and Spirit, the light, and righteousness of Christ,
by which they might be clothed, and have the eternal riches.
So the church of Christ had a spiritual judgment
given to them that are faithful in his power,
and Spirit, and light, to judge of temporal things, and the things of this life;
and to judge of eternal and divine things and states; of angels and wicked men,
and such as go from truth; and of the states of election and reprobation; yea,
and of the devils who are out of truth; these being in Christ Jesus,
who is the First and Last, from whom they have the eternal judgment, to judge eternal,
spiritual, and divine things; and in this Word of power and wisdom,
by which all things were made, and by which all things are upheld,
to order all things to God's glory, and to judge of all things in righteousness.

"`The apostle judged, and set up a judgment in the church, of gifts, of prophecies,
of mysteries, of faith, and of giving the body to be burned,
and of giving goods to the poor, and of speaking with tongues of men and angels;
that yet, if they had not love, all this was nothing,
but as a sounding brass and tinkling cymbal.
Therefore they are to be tried by the fruits of the good Spirit, which is love.
So here the apostle not only judged himself in divine things,
but set up a judgment in the church in those spiritual and divine matters.

"`The apostle James judges of fountains, and of fig-trees, of the wisdom from below,
and of the wisdom from above, and of the fruits of both, James iii.
And Paul judged in divine matters when he said, 'The Spirit spake expressly,
that in the latter times some should depart from the faith,' 1 Tim. 4.
And he judged in divine matters,
when he judged all those teachers that were high-minded,
and had got the form of godliness, but denied the power;
and termed them like unto Jannes and Jambres, who withstood Moses,
coming out of outward Egypt; as these with their form of godliness,
oppose Christ and his power, that brings them out of spiritual Egypt now.
Was not he a judge here in divine matters,
who judged such as had gotten the form of godliness, but denied the divine power?
2 Tim. 3.

"`When the apostle said, 'the priesthood of Aaron was changed, and the law was changed,
and the commandment disannulled, that gave them their tithes,
'did not he judge here in divine and spiritual matters?
and was not the law spiritual, which served till the Seed came?

"`Did not the apostle judge in divine and spiritual matters, in the sixth of the Hebrews,
where he saith, 'Let us go on to perfection,
not laying again the foundation of repentance from dead works, and of faith towards God,
and of the doctrine of baptisms, and of laying on of hands,
and of the resurrection of the dead, and of eternal judgment: and this will we do,
if God permit,' etc.
And does not the apostle judge here,
'that it was impossible for those who were once enlightened,
and tasted of the heavenly gift, and were partakers of the Holy Ghost,
and had tasted of the good word of God, and of the power of the world to come,
if they shall fall away, to renew them again unto repentance;
seeing they crucify to themselves the Son of God afresh, and put him to open shame?'
Heb. 6.
Were not these spiritual, eternal, and divine matters and states,
that the apostle judged of?
and have not the saints the same judgment given unto them in the same Spirit?
Have not the apostles and the church a spiritual judgment to judge of prophets,
mysteries, faith, apostles, angels, the world, and the devil?
And is not this judgment given them of God in divine matters,
besides the judgment given them in matters pertaining unto this life?

"`And had not they judgment to discern the true gospel from the false?
and all such as had a profession of the form, and did not live in the power?
and such as spoke the things of God, in the words that man's wisdom did teach?
which things of God were not to be spoken in the words which man's wisdom taught,
but in the words which the Holy Ghost taught.
Therefore did not the apostle exhort to know the power,
and that their faith might stand in the power of God?
for the kingdom of God stands not in word, but in power.

"`Had not all the prophets a divine judgment to judge in divine matters?
as Jeremiah, when he judged the prophets.
Ezekiel also judged all such as came with a pretence of the Word of the Lord,
using their tongues, and saying, 'Thus saith the Lord,
when the Lord never spoke unto them;' as in Jer. 23,
Ezek. 13, and many other places might be instanced.
Did not he judge Hananiah, who prophesied falsely?
and did not this Hananiah pretend to speak the Word of the Lord to the priests and people?
as in Jer. 28.

"`Did not Isaiah judge in divine matters, when he judged the watchmen and the shepherds? Isa. 56.
Did not Micah judge in divine and spiritual matters when he
said 'he was full of the power by the Spirit of the Lord,
and of judgment?'
Did not he judge of priests, prophets, and judges, though they would lean upon the Lord,
and say, 'Is not the Lord amongst us,
and no evil can come unto us;' yet did not he let them see their states and conditions,
and divide the precious from the vile? Mic. 3.
And so the rest of the prophets.
You may see they judged for God in his divine matters, 'who served him,
and who served him not; and who lived in truth, and who not;' and likewise the apostles.
And this divine, spiritual,
and heavenly judgment was given of God to his holy men and women.

"`They that judge in God's divine matters, must live in his divine Spirit, power,
and light now, as they did then;
which spiritual and divine judgment Christ has given to his church, the living stones,
and living members, that make up his spiritual household; to try Jews, apostles,
and prophets; to try faiths and religions, trees and fruits, shepherds and teachers;
and to try spirits.
So the living members have a living, divine judgment in the church of Christ,
which he is the Head of, the Judge of all.

"`Nay, the church has a power given them, which is farther than a judgment:
for what they 'bind on earth, is bound in heaven by the power of God:
and what they loose on earth, is loosed in heaven by the power of God.'
This power has Christ given to his living members, the church.`"

[.signed-section-signature]
G+++.+++ F. to Friends.

[.signed-section-context-close]
The 20th of the 12th Month, 1685-6.

I came back to London in the 1st month, 1686,
and set myself with all diligence to look after Friends' sufferings,
from which we had now some hopes of getting relief.
The sessions came on in the 2nd month at Hicks's Hall,
where many Friends had appeals to be tried; with whom I was from day to day,
to advise and see that no opportunity were slipped, nor advantage lost;
and they generally succeeded well.
Soon after also the king was pleased, upon our often laying our sufferings before him,
to give order for the "`releasing of all prisoners for conscience' sake;
that were in his power to discharge.`"
Whereby the prison-doors were opened, and many hundreds of Friends,
some of whom had been long in prison, were set at liberty.
Some of them, who had for many years been restrained in bonds,
came now up to the Yearly Meeting, which was in the 3rd month this year.
This caused great joy to Friends, to see our ancient, faithful brethren,
again at liberty in the Lord's work, after their long confinement.
And indeed a precious meeting we had;
the refreshing presence of the Lord appearing plentifully with us and amongst us.
After the meeting I was moved to write a few lines, to be sent amongst Friends:
the tenor whereof was thus:--

[.salutation]
"`Dear Friends,

"`My love is to you all in the holy Seed, Christ Jesus, that bruises the serpent's head,
and destroys the devil and his works;
and who hath all power in heaven and in earth given him.
Let every one's faith stand in Him, and in his power,
who is the author and finisher of your faith.
And now for you, who have been partakers of his power,
and are sensible of it in this day of his power, that is over darkness and its power;
by whose power the hearts of the king and rulers have been opened,
and your outward prison-doors set open for your liberty, my desires are,
that all may be preserved in humility and thankfulness,
in the sense of the mercies of the Lord; and live in the peaceable truth,
that is over all; that ye may answer God's grace, and his light and Spirit in all,
in a righteous, godly life and conversation.
Let none be lifted up by their outward liberty,
neither let any be cast down by suffering for Christ's sake;
but all live in the Seed (which is as wheat) which is not shaken,
nor blown away by the winds and storms, as the chaff is.
Which Seed of life none below can make higher or lower;
for the children of the Seed are the children of the everlasting,
unchangeable kingdom of Christ and God.
In Christ Jesus, whom God hath given you for a sanctuary, God Almighty keep you,
in whom ye have life everlasting, and wisdom from above, which is pure, peaceable,
gentle, and easy to be entreated, full of mercy and good fruits;
that all now may be exercised in,
and may practise this wisdom in holy lives and conversations;
so that this wisdom may be justified of all her children,
and they exercised and preserved in it in this day of the power of Christ,
in which all his people are made a willing people,
to serve and worship God in righteousness and holiness, in Spirit and in truth.

"`Let none abuse the power of the Lord, nor grieve his Spirit, by which you are sealed,
and kept to the day of salvation and redemption;
but always exercise yourselves to have 'a good conscience,
void of offence towards God and towards all men,' being exercised in holiness, godliness,
and righteousness; and in the truth, and in the love of it.
All study to be approved unto God in innocency, virtue, simplicity, and faithfulness,
labouring and studying to be quiet in the will of God.
'And whatsoever ye do in word or deed, do all in the name of the Lord Jesus;
giving thanks to God the Father by him that he who is over all,
may have the praise for all his mercies and blessings,
with which he hath refreshed his people,
and by his eternal arm and power hath kept and preserved them to this day;
glory to his name over all for ever. Amen!
Christ hath called you by his grace into one body, to him the holy Head;
therefore live in charity, and in the love of God,
which is the bond of perfectness in his body.
This love edifies the body of Christ; which body and all his members are knit together,
and increased with the increase of God, from whom they receive nourishment.
For by one Spirit we are all baptized into one body,
and have been made all to drink into one Spirit,
in which Spirit the body and all its members have fellowship with Christ, the Head,
and one with another.
The unity of this Holy Spirit is the bond of
peace of all the living members of Christ Jesus,
of which he is the spiritual Head, Rock, and Foundation.
In the midst of his church of living members,
Christ exercises his spiritual prophetical office,
to open to them the mysteries of his kingdom.
He is a spiritual Bishop to oversee them,
that they do not go astray from the living God that made them;
a Shepherd that feeds them with bread and water of life from heaven;
and none is able to pluck his sheep out of his hands.
He is a Priest that died for them, sanctifies them, and presents them to God;
who ruleth in their hearts by the divine faith, which he is the author and finisher of.
His living members praise God through Jesus Christ, in whom they have life and salvation,
who reconciles them to God,
that they can say they have 'peace with God through Jesus
Christ and so praise God through him that was dead,
and is alive again, who reigns over all, and liveth for evermore, blessed for ever;
Hallelujah. Amen!

"`Greet one another with a holy kiss of charity.
Love or charity beareth all things, believeth all things, hopeth all things,
endureth all things.
It envieth not, vaunteth not itself, is not puffed up, nor doth it behave itself unseemly.
It rejoices not in iniquity, but rejoices in the truth.
Charity is not easily provoked, and thinks no evil, but suffereth long and is kind.
Charity never faileth.
I say, greet one another with this holy kiss of charity, and peace be with you all,
that are in Christ Jesus, your life and salvation.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 30th of the 3rd Month, 1686.

I remained most part of this year in London,
save that sometimes I got out to Bethnal-Green for a night or two,
or as far as Enfield and thereabouts amongst Friends, and once or twice to Chiswick,
where an ancient Friend had set up a school for the educating of Friends' children;
in all which places I found service for the Lord.
At London, I spent my time amongst Friends,
either in public meetings (as the Lord drew me) or visiting those that were not well,
and in looking after the sufferings of Friends.
For though many were released out of prisons,
yet some remained prisoners still for tithes, etc.,
and sufferings of several sorts lay heavy on Friends in many places.
Yet inasmuch as many Friends, that had been prisoners, were now set at liberty,
I felt a concern upon me, that none might look too much at man,
but might eye the Lord therein, from whom deliverance comes.
Wherefore I wrote an epistle to them, as follows:--

[.salutation]
"`Friends,

"`The Lord, by his eternal power,
hath opened the heart of the king to open the prison doors,
by which-about fifteen or sixteen hundred are set at liberty,
and hath given a check to the informers;
so that in many places our meetings are pretty quiet.
My desires are, that both liberty and sufferings may be sanctified to his people,
that Friends may prize the mercies of the Lord in all things, and to him be thankful,
who stilleth the raging waves of the seas, allayeth the storms and tempests,
and maketh a calm.
Therefore it is good to trust in the Lord, and cast your care upon him,
who careth for you.
For when ye were in jails and prisons, the Lord did, by his eternal arm and power,
uphold you, and sanctified them to you (and unto some he made them as a sanctuary),
and tried his people as in a furnace of affliction,
both in prisons and spoiling of goods.
In all this the Lord was with his people,
and taught them to know that 'the earth is the Lord's,
and the fulness thereof;' and that He was in all places;
'who crowneth the year with his goodness,' Psal. 65.
Therefore let all God's people be diligent,
and careful to keep the camp of God holy, pure, and clean, and to serve God and Christ,
and one another in the glorious, peaceable gospel of life and salvation,
which glory shines over God's camp; and his great Prophet, Bishop, and Shepherd is among,
or in the midst of them, exercising his heavenly offices in them;
so that you his people may rejoice in Christ Jesus, through whom you have peace with God.
For he that destroyeth the devil and his work, and bruises the serpent's head,
is all God's people's heavenly Foundation and Rock to build upon;
which was the holy prophets' and apostles' Rock in days past,
and is now the Rock of our age; which Rock and Foundation of God standeth sure.
Upon this the Lord God establish all his people. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 25th of the 7th Month, 1686.

[.offset]
Divers other epistles and papers I wrote this year;
one of which was an exhortation "`to Friends to keep in unity in the truth,
in which there is no division nor separation;`" it was thus:--

[.salutation]
"`Dear Friends And Brethren In The Lord Jesus Christ,

"`In whom ye have all peace and life, and in whom there is no division, schism, rent,
strife, nor separation; for Christ is not divided:
there can be no separation in the truth, nor in the light, grace, faith, and Holy Ghost,
but unity, fellowship, and communion.
For the devil was the first that went out of the truth, separated from it,
and tempted man and woman to disobey God, and to go from the truth into a false liberty,
to do that which God forbade.
So it is the serpent now that leads men and women into a false liberty,
even the god of the world, from which man and woman must be separated by the truth;
that Christ the Truth may make them free, and then they are free indeed.
Then they are to stand fast in that liberty, in which Christ hath made them free,
and in Him there is no division, schism, rent, or separation; but peace, life,
and reconciliation to God, and to one another.
So in Christ, male and female are all one; for whether they be male or female,
Jew or Gentile, bond or free, they are all one in Christ.
And there can be no schism, rent, or division in Him;
nor in the worship of God in his Holy Spirit and truth;
nor in the pure and undefiled religion, that keeps from the spots of the world;
nor in the love of God that beareth and endureth all things;
nor in the Word of God's grace, for it is pure and endureth for ever.
Many, you see, have lost the Word of patience and the Word of wisdom, that is pure,
and peaceable, and gentle, and easy to be entreated:
then they run into the wisdom that is below, that is 'earthly, sensual,
and devilish,' and very uneasy to be entreated.
They go from the love of God that beareth all things, endureth all things,
thinketh no evil, and doth not behave itself unseemly: then they cannot bear,
but grow brittle, and are easily provoked, run into unseemly things, and are in that,
that vaunteth itself, are puffed up, rash, heady, high-minded, and fierce,
and become as sounding brass, or a tinkling cymbal;
but this is contrary to the nature of the love of God.
Therefore, dear Friends and brethren, dwell in the love of God;
for they who dwell in love, dwell in God, and God in them.
Keep in the Word of wisdom, that is gentle, pure, and peaceable,
and in the Word of patience, that endureth and beareth all things;
which Word of patience the devil, and the world,
and all his instruments can never wear out; it will wear them all out;
for it was before they were, and will be, when they are gone, the pure, holy Word of God,
by which all God's children are borne again, feed on the milk thereof,
and live and grow by it.
My desires are, that ye may all be of one heart, mind, soul, and spirit in Christ Jesus.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
Soon after this, finding those apostates,
whom the enemy had drawn out into division and separation from Friends,
continued their clamour and opposition against our monthly, quarterly,
and yearly meetings, it came upon me to write another short epistle to Friends,
to put them in mind of the "`evidence and seal they had
received in themselves by the Spirit of the Lord,
that those meetings were of the Lord,
and accepted by him,`" that so they might not be shaken by the adversaries.
I wrote as follows:--

[.salutation]
"`My Dear Friends In The Lord Jesus Christ!

"`All you, that are gathered in his holy name, know, that your meetings for worship,
your quarterly and other meetings are set up by the power and Spirit of the Lord God,
and witnessed by his Spirit and power in your hearts;
and by the Spirit and power of the Lord God they are established to you,
and in the power and Spirit of the Lord God you are established in them.
The Lord God hath with his Spirit sealed to you,
that your meetings are of his ordering and gathering, and he hath owned them,
by honouring you with his blessed presence in them;
and you have had great experience of his furnishing you with his wisdom, life, and power,
and heavenly riches from his treasure and fountain,
by which many thanks and praises have been returned in your meetings to his holy,
glorious name.
He hath sealed your meetings by his Spirit to you,
and that your gathering together hath been by the Lord, to Christ his Son,
and in his name; and not by man.
So the Lord hath the glory and praise of them and in them, who hath upheld you and them,
by the arm of his power, against all opposers and backsliders,
and their slanderous books and tongues.
For the Lord's power and Seed doth reign over them all,
in which he doth preserve his sons and daughters to his glory,
by his eternal arm and power, in his work and service,
as a willing people in the day of his power, without being weary or fainting,
but strong in the Lord, and valiant for his glorious name and precious truth,
and his pure religion; that ye may serve the Lord in Christ Jesus,
your Rock and Foundation, in your age and generation.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 3rd of 11th Month, 1686-7.

[.offset]
A little after it came upon me to write something
concerning the state of the true church,
and of the true members thereof, as follows:--

[.alt]
=== "`Concerning the Church of Christ being clothed with the Sun, and having the Moon under her feet.

"`They are living members, living stones, built up a spiritual household,
children of the promise, and of the Seed and flesh of Christ; and as the apostle saith,
'Flesh of his flesh, and bone of his bone.'
They are the good seed, the children of the everlasting kingdom written in heaven;
and have put on the Lord Jesus Christ.
They sit together in heavenly places in Christ,
are clothed with the Sun of Righteousness, Christ Jesus,
and have the moon under their feet, as Rev.
xii. So all changeable things, that are in the world, all changeable religions, worships,
ways, fellowships, churches, and teachers in the world, are as the moon;
for the moon changes, but the sun doth not change.
The Sun of Righteousness never changeth, nor goes down; but all the ways, religions,
worships, fellowships of the world, and the teachers thereof, change like the moon.
The true church, which Christ is the head of, which is in God, the Father,
is called 'the pillar and ground of truth,' whose conversation is in heaven;
this church is clothed with the Sun, Christ Jesus, her head, who doth not change,
and hath all changeable things under her feet.
These are the living members, born again of the immortal Seed, by the Word of God,
who feed upon the immortal milk, and live and grow by it.
Such are the new creatures in Christ Jesus, who makes all things new,
and sees the old things pass away.
His church and all his members, which are clothed with the Sun,
their worship is in Spirit, and in truth, which doth not change; which truth the devil,
the foul, unclean spirit, is out of,
and cannot get into this worship in Spirit and in truth.
Their religion is pure and undefiled before God, that keeps from the spots of the world,
etc., and their way is the new and living way, Christ Jesus.
So the church of Christ, that is clothed with the Sun,
that hath the moon and all changeable religions and ways under her feet,
hath an unchangeable worship, religion, and way, an unchangeable Rock and Foundation,
Christ Jesus, and an unchangeable High Priest; and so are children of the New Testament,
and in the everlasting Covenant of Light and Life.

"`Now all, that profess the Scriptures both of the New and Old Testament,
and are not in Christ Jesus, the apostle tells them, they are 'reprobates,
if Christ be not in them.'
Therefore these, that are not in Christ, cannot be clothed with Christ,
the Sun of Righteousness, that never changes.
They are under the changeable moon, in the world, in the changeable things,
changeable religions, ways, worships, teachers, rocks, and foundations.
But Christ, the Son of God, and Sun of Righteousness, doth not change;
in whom his people are gathered, and sit together in heavenly places in him,
clothed with Christ Jesus, the Sun, who is the mountain,
that filleth the whole earth with his divine power and light.
So all his people see him, and feel him both by sea and land.
He is in all places of the earth, felt and seen of all his.
And Christ Jesus saith to the outward professors, the Jews,
'I am from above,' ye are from below, 'ye are of this world.'
So their religions, worships, ways, teachers, faiths, beliefs,
and creeds are made by men, and are below, of this world that changeth like the moon.
You may see their religions, ways, worships, and teachers, are all changeable,
like the moon; but Christ, the Sun, with which the church is clothed, doth not change,
nor his church; for they are spiritually minded, and their way, worship,
and religion is spiritual, from Christ, who is from above, and not of this world.
Christ hath redeemed his people from the world, and its changeable rudiments, elements,
and old things, and from its changeable teachers, faiths, and beliefs.
For Christ is the author and finisher of his church's faith, who is from above,
and saith, 'Believe in the light,
that ye may become children of light:' and it is given them not only to believe,
but to suffer for his name.
So this faith and belief is above all faiths and beliefs, which change, like the moon.
God's people are a holy nation, a peculiar people, a spiritual household,
and royal priesthood, offering up spiritual sacrifice to God, by Jesus Christ;
and are zealous of righteous, godly, good works;
and their zeal is for that which is of God, against the evil which is not of God.

"`Christ took upon him the Seed of Abraham; he doth not say,
the corrupt seed of the Gentiles: so, according to the flesh,
he was of the holy seed of Abraham and of David;
and his holy body and blood was an offering and
a sacrifice for the sins of the whole world,
as a lamb without blemish, whose flesh saw no corruption.
By the one offering of himself in the New Testament or New Covenant,
he has put an end to all the offerings and
sacrifices amongst the Jews in the Old Testament.
Christ, the holy Seed, was crucified, dead, and buried, according to the flesh,
and raised again the third day; and his flesh saw no corruption.
Though he was crucified in the flesh, yet he was quickened again by the Spirit,
and is alive, and liveth for evermore;
he hath all power in heaven and in earth given to him, and reigneth over all;
and is the one Mediator between God and man, even the man Christ Jesus.
Christ said, 'He gave his flesh for the life of the world:' and the apostle says,
'His flesh saw no corruption:' so that which saw no
corruption he gave for the life of the corrupt world,
to bring them out of corruption.
Christ said again, 'He that eateth my flesh and drinketh my blood hath eternal life:
for my flesh is meat indeed, and my blood is drink indeed.
And he that eateth my flesh and drinketh my blood dwelleth in me, and I in him.'
He that eats not his flesh and-drinks not his blood, which is the life of the flesh,
hath not eternal life.
As the apostle saith, all died in Adam; then all are dead.
Now all coming spiritually to eat the flesh of Christ, the second Adam,
and drink his blood, his blood and flesh gives all the dead in Adam life,
and quickens them out of their sins and trespasses, in which they were dead;
so they come to sit together in heavenly places in Christ Jesus,
living members of the church of Christ, that he is the head of;
are clothed with the Sun of Righteousness, the Son of God, that never changes,
and have the changeable moon under their feet, and all changeable,
worldly things and inventions, and works of men's hands.
These see the people, how they change from one worship to another,
from one religion to another, from one way to another, and from one church to another;
and yet their hearts are not changed.
The letter of Scripture is read by the Christians like the Jews; but the mystery is hid:
they have the sheep's clothing, the outside, but are inwardly ravened from the Spirit,
which should bring them into the Lamb's and Sheep's nature.
The Scripture saith,
'All the uncircumcised must go down into the pit:' and
therefore all must be circumcised with the Spirit of God,
which puts off the body of death, and sins of the flesh,
that came into man and woman by their disobedience, and transgressing of God's commands.
I say, all must be circumcised with the Spirit,
which puts off the body of death and sins of the flesh, before they come up into Christ,
their Rest, that never fell, and be clothed with Him, the Sun of Righteousness.`"

[.signed-section-signature]
G+++.+++ F.

Towards the latter end of this year I went to Kingston to visit Friends there;
and stayed some time at my son Rous's. I wrote there a paper
concerning "`the falling away`" foretold by the apostle Paul,
2 Thess. 2:3, as follows:--

[.small-break]
'''

"`The apostle saith that there must be 'a falling away' first, before the wicked one,
that man of sin, the son of perdition, be revealed, which betrayeth Christ within,
as the son of perdition betrayed Christ without; and they that betray Christ within,
crucify to themselves Christ afresh, and put him to open shame.
Before the apostles died, this man of sin, the son of perdition, was revealed:
for they saw antichrist come, and false prophets, false apostles, and deceivers come,
having a form of godliness, but denying the power thereof.
They saw the wolves dressed in the sheep's clothing, and such as went in Cain's, Korah's,
and Balaam's way, and Jezebel's; and the whore of Babylon, the whore of confusion,
the mother of harlots, and such as were enemies to the cross of Christ,
that served not the Lord Jesus Christ, but their own bellies.
These Christ saw should come, and said, 'If it were possible,
they should deceive the elect;' and commanded his followers not to go after them.
The apostle said,
'Turn away from such;' and Christ and his apostles warned the church of Christ of such.
And now, in this day of Christ and his gospel,
after the long night of apostasy from the light, grace, truth, life,
and Spirit of Christ Jesus, the son of perdition, the wicked one, the man of sin,
is revealed again; and the inwardly ravening wolves in sheep's clothing,
and the spirit of Cain, Korah, Balaam, Jezebel, the antichrists, false prophets,
and false apostles, and such as are enemies to the cross of Christ,
who serve not the Lord Jesus, but their own bellies; and crucify Christ to themselves,
and put him to open shame.
This Spirit have we seen in this gospel-day of Christ;
but Christ will consume them with the Spirit of his mouth,
and destroy them with the brightness of his coming.
But God's people,
whom he hath chosen unto salvation in Christ from the
beginning,' through sanctification of the Spirit and
belief of the truth,' stand stedfast in Christ Jesus;
and are thankful to God, by and through his Son, their rock and salvation,
who is their happiness and eternal inheritance.

"`The apostle saith, 'Ye were as sheep going astray;
but are now returned to the Shepherd and Bishop of your souls.'
So when people are returned to Christ, their Shepherd, they know his voice,
and follow him; and are returned to the Bishop of their souls: then they believe in him,
and receive wisdom and understanding from him, who is from above, heavenly and spiritual.
Then they act like spiritual and holy men and women;
and come to be members of the church of Christ.
Then a spiritual care cometh upon the elders in Christ,
that all the members walk in Christ, in his light, grace, Spirit, and truth,
that they may adorn their profession of Christ;
and see that all walk in the order of the Holy Spirit,
and the everlasting gospel of peace, life, and salvation.
This order keeps out of confusion; for the gospel of peace, the power of God,
was before confusion was.
And all the heirs of the gospel are heirs of its order, and are in this gospel,
which brings life and immortality to light in them;
by which all may see their work and service in it, to look after the poor, widows,
and fatherless, and to see that nothing be lacking;
and that all honour the Lord in their lives and conversations.

"`When the whole house of Israel were in their graves and sepulchres,
and were called 'the scattered dry bones,' yet they could speak, and say,
'their bones were dry, their hope was lost,' or they were without hope,
'and they were cut off.'
They were alive outwardly, and could speak outwardly.
So that which is called Christendom may very well be called 'the scattered
dry bones,' and they may be said to be in their graves and sepulchres,
dead from the heavenly breath of life, the Spirit and Word of life,
that gathereth to God.
Though they can speak, and are alive outwardly,
yet they remain in the congregations or churches of the dead,
that want the virtue of life.
For the Jews, whom God poured his Spirit upon, and gave them his law,
when they rebelled against the Spirit of God, and turned from God and his law,
came to be dry scattered bones, and were turned into their graves and sepulchres.
So Christendom, that is turned from the grace, truth, and light of Christ,
and the Spirit, that God poureth upon all flesh, they are become the scattered dry bones,
are in their graves and sepulchres, and are the congregations or churches of the dead,
though they can speak, and are alive outwardly.

"`Christ saith, 'I am come that they might have life,
and that they might have it more abundantly.'
He gave his flesh for the life of the world.
And he saith, 'I am the resurrection and the life;' and, 'I am the way, the truth,
and the life; no man cometh unto the Father but by me.'
Christ is the quickening Spirit.
All being dead in Adam, are to be quickened and made alive by Christ, the second Adam.
And when they are quickened and made alive by him,
they meet together in the name of Jesus Christ their Saviour, who died for their sins,
and is risen for their justification; who was dead and is alive again,
and liveth for evermore.
All whom he hath quickened and made alive (even
all the living) meet in the name of Jesus,
who is alive, and He, their living Prophet, Shepherd, and Bishop,
is in the midst of them; and is their living Flock and Foundation,
and a living Mediator between them and the living God.
So the living praise the living God through Jesus Christ,
through whom they have peace with God.
All the living have rest in Christ, their life.
He is their sanctification, their righteousness, their treasure of wisdom, knowledge,
and understanding, which is spiritual and heavenly.
He is the spiritual tree and root, which all the believers in the light,
the life in Christ, that pass from the death in Adam to the life in Christ,
and overcome the world, and are born of God, are grafted into; even Christ,
the heavenly tree, which beareth all the spiritual branches or grafts.
These meet in his name, are gathered in him,
and sit together in heavenly places in Christ Jesus, their life,
who hath quickened and made them alive.
So all the living worship the living God in his Holy Spirit and truth,
in which they live and walk.
Into this worship, the foul, unclean spirit, the devil, cannot get;
for the Holy Spirit and truth is over him, and he is out of it.
This is the standing worship, which Christ set up in his new covenant.
And they that are quickened by Christ are the living stones, living members,
and spiritual household and church, or congregation of Christ,
who is the living head and husband.
They that are made alive by Christ are a living church, have a living head,
and are come from the congregations or churches of the dead in Adam,
where death and destruction talk of God, and of his prophets and apostles,
in their wisdom that is below, earthly and devilish; in the knowledge that is brutish,
and in the understanding that comes to naught.
For what they know is natural, by their natural tongues, arts, sciences;
in which they corrupt themselves.
This is the state of the dead in Adam: but the quickened,
they that are made alive by Christ, discern between the living and the dead.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston-upon-Thames, the 12th Month, 1636-7.

[.offset]
While I was at Kingston, I wrote also another paper, showing "`that the Lord,
in all ages, called the righteous out from amongst the wicked,
before he destroyed them;`" after this manner:--

"`Noah and his family were called into the ark,
before the old world was destroyed with the flood.
And all the faithful generation, that lived before, were taken away,
and died in the faith, before that flood of destruction came upon the wicked old world.

"`The Lord called Lot out of Sodom, before he destroyed and consumed it,
and the wicked there.

"`Christ said, 'It cannot be that a prophet perish out of Jerusalem:' and he said,
'O Jerusalem, Jerusalem, which killest the prophets,
and stonest them that are sent unto thee,
how often would I have gathered thy children together,
as a hen gathereth her brood under her wings! and ye
would not,' Luke 13:33-34. And he said to the Jews,
'Therefore also said the wisdom of God, I will send them prophets and apostles,
and some of them they shall slay and persecute; that the blood of all the prophets,
which was shed from the foundation of the world, may be required of this generation;
from the blood of Abel, unto the blood of Zacharias,
which perished between the altar and the temple.
Verily, I say unto you,
it shall be required of this generation,' Luke 11:49-51. And he said to the Jews,
'Behold your house is left unto you desolate,' Matt. 23:34, etc.
Christ told his disciples, that the temple at Jerusalem should be thrown down,
and there should not be one stone left upon another, that should not be thrown down,
Matt. 24:2. Also, that he must go to Jerusalem, and 'suffer many things of the Jews,
elders, and chief priests, and be killed,
and raised again the third day,' Matt. 16:21. And Christ said,
'When ye shall see Jerusalem compassed with armies,
then know the desolation thereof is nigh.'
He foretold, that the Jews should fall by the edge of the sword,
and should be led away 'captive into all nations;
and Jerusalem should be trodden down of the Gentiles,' Luke 21:20,24. Here you may see,
how Jerusalem was often warned by Christ, and how often he would have 'gathered them,
but they would not,' before they were scattered over or into all nations,
their houses left desolate, and their temple and Jerusalem besieged with armies,
destroyed, and thrown down.
And though the disciples and apostles of Christ did meet, with the elders and church,
at Jerusalem, after Christ was risen, yet Eusebius reports in his _Ecclesiastical History,_
that the Christians at Jerusalem had a vision,
or a revelation to depart out of Jerusalem.
Being forewarned also by Christ,
that when they should see Jerusalem compassed with armies, its desolation was nigh;
and that the temple should be thrown down, and not one stone left upon another;
it is said, that the Christians did depart out of bloody Jerusalem,
before it and the temple were destroyed by Titus, the emperor,
who besieged it with his armies.
He was of the Gentiles, and destroyed the temple and Jerusalem,
as Christ had fore-spoken to his disciples, because of the wickedness of the Jews,
and the innocent blood that they had shed in it.
So the Lord called his people out of bloody Jerusalem, before he destroyed it.
And it is said,
that Titus destroyed the temple and Jerusalem
about forty-two years after Christ was crucified,
and risen again; and that with so great a destruction,
that the Jews never built the city again, nor the temple (as Sodom was never built again,
nor the cities of the old world). But the Jews for above these thousand years have been,
and are a scattered people in all nations to this day;
and Christ (whom they crucified) and his doctrine, is preached, and set over them;
and the Gentiles, whom they hated, have received, and do receive him and his doctrine,
and praise God for it through Jesus Christ.
Amen.

"`God called his people out of Egypt,
after he had poured out his ten plagues upon the Egyptians;
when he had destroyed the first-born of Egypt,
then the Lord brought his people out of Egypt.
And after the Lord had clearly brought his people out, he destroyed Pharaoh,
and all his hosts and chariots.

"`John says, he heard a voice, saying, 'Come out of her, my people, (to wit,
out of Babylon, the false church), that ye be not partakers of her sins,
and that ye receive not of her plagues; for her sins have reached to heaven,
and God hath remembered her iniquities,' Rev. 18:4-5. Here
ye may see that God called his people out of spiritual Babylon,
before he destroyed her, and cast her down, to be utterly burnt with fire,
ver. 8, 9, 21.

"`Was not Nebuchadnezzar's empire thrown down and ended by Cyrus and Darius,
who were of the seed of the Medes,
before Cyrus and Darius gave forth their proclamation
for all the Jews to go into their own land,
out of Babylon's captivity?
And was there not a prophecy of Cyrus, 'that he should subdue nations,
and that the Lord would loose the loins of kings before him,
and break in pieces the gates of brass, and cut in sunder the bars of iron,
and open the two-leaved gates; and that the gates should not be shut?'
And the Lord said,
'This is for Jacob, my servant's sake, and for Israel mine elect,' Isa. 45.
Was not this fulfilled in Cyrus's and Darius's time?
For did not then the Jews go out of captivity into their own land,' Ezra 1:2-4;
6:1,12; Isa. 44:28; 45:13.
Was not this prophecy of Isaiah fulfilled
when the children of Israel came out of Babylon?
Were not the Assyrians, that carried away the ten tribes, subdued?
and the Babylonians, that carried away the two tribes,
were they not subdued in the days of Cyrus and Darius,
in whose days the 'loins of kings were loosed,
and the two-leaved gates of brass and iron were opened?'
and had not Israel and Jacob their liberty by them in their days,
to go into their own land?

"`And here in England, was it not observed,
that most of the honest and sober people were turned out of the army,
and their commissions, offices, and places taken from them,
because they could not join with others in their cruelty and persecuting?
And others laid down their commissions themselves,
and came out from amongst those persecutors,
before they were overthrown and brought to confusion.
All that are wise, see these things,
and learn by such examples and way-marks to shun such bogs.
The righteous are safe, that keep in Christ, their everlasting sanctuary,
that changes not; in whom they have rest and peace with God.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 29th of the 12th Month, 1686-7.
