== Chapter XIII.

[.chapter-synopsis]
* 1686-1687
* The first and the second Adam compared
* the two seeds distinguished
* George Fox is daily exercised in London in services relating to the church, visiting the sick or afflicted, and writing in defence of Truth, or refuting error
* true prayer distinguished from the practice of the Papists
* visits his son-in-law William Mead
* a distinction between the true offering, and sacrifice, and the false, under the old and new covenant
* a general toleration and liberty being now granted, George Fox writes a word of counsel and caution to Friends, to walk circumspectly in a time of liberty
* how redemption by Christ is known and witnessed
* repentance must precede the reception of the gospel, baptism, etc.
* a paper showing wherein God's people are to be like him
* the right way to Christ
* the kingdom of God is to be measurably known in this life
* George Fox is benefited by being three months in the country
* has much service in London again
* at Kingston writes a paper, showing how the Jews, by disobedience, lost the Holy City and the Holy Land, designed as a warning to Christians
* everlasting life through, and in, Christ, to be received and witnessed in this life
* the stone cut out of the mountain signifies the kingdom and power of Christ
* a miscellaneous paper, being a collection of Scripture passages respecting regeneration, sanctification, etc.

While I was at Kingston, one day, as I was meditating on the things of God,
some particular observations arose in my mind, concerning the first,
and the second or last Adam.
As that--

"`The first man Adam was made on the sixth day of the week; and Christ, the second Adam,
was crucified on the sixth day of the week.

"`The first Adam was betrayed by the serpent in the garden of Eden; Christ our Saviour,
the second Adam, was betrayed by Judas in a garden near Jerusalem.

"`Christ arose from the dead on the First-day of the week;
and they that believe on him are entered into Christ, their Rest;
the Christians meet together to worship God on the First-day of the week;
and on the First-day of the week it was that God said, 'Let there be light,
and there was light,' The Jews' rest was on the seventh-day of the week,
which was given to them as a sign of the eternal rest of the Lord, sanctifying them,
after they came out of the land of Egypt;
for before that time the Lord had not given to
man and woman his outward Sabbath-day to keep,
neither in the old world, nor after in Abraham's time, nor in Isaac's,
nor in Jacob's time; until the Jews came out of Egypt to Mount Sinai in the wilderness.
Then the Lord gave the law and his Sabbath, as a sign in the old covenant,
of Christ the Eternal Rest in the new covenant;
and they that believe do enter into Christ, their Rest.

"`Adam, the first man, is the root from whence we all spring naturally;
and Christ is called the last, or second Adam,
because he is the beginning and root of all that are spiritual.

"`The first Adam was made a living soul; and Christ, the last Adam,
is a quickening spirit.

"`Christ by the grace of God tasted death for every man,
that they night all come into favour with God; and that every tongue should confess,
that 'Jesus Christ is Lord, to the glory of God the Father.'`"

[.offset]
I wrote also a paper there, concerning the two seeds,
distinguishing the seed wherein the blessing is received,
from the seed which the curse remains upon.
Of which the following is a copy:--

"`The Lord said to Abraham,
'In thy seed shall all the nations of the earth be blessed,'
Gen. 22:18. 'And thy seed shall be as the stars of heaven,
and as the sand, which is upon the sea-shore, and as the dust of the earth,
that cannot be numbered,' chap. 13:16; 15:5; 22:17.
In this seed all nations and families of the earth are blessed;
but not in the seed of evil-doers and of falsehood,
nor in the seed of the adulterer and the whore, Isa. 1:4, and 57:3, 4;
'for the seed of the wicked shall be cut off,' saith the Lord,
Ps. 37:28. The Lord said to David,
'That his seed should endure for ever,' Ps. 89:36. And again it is said,
Ps. 102:28, 'The children of thy servants shall continue,
and their seed shall be established before thee.'
Here is a distinction between the two seeds; for the seed of evil-doers,
of the adulterer, and of the wicked, shall be cut off; and so it is not blessed.
But Christ bruises the head of the serpent, and his seed which he soweth in them,
that disobey and transgress God's command, and rebel against God's good Spirit.
This wicked seed of the serpent is cursed,
and is an enemy to the Seed in whom all are blessed;
but Christ bruises the head of this cursed seed of enmity,
and destroys the devil and his works; and in his seed are all blessed,
and all are in unity in this seed.
All the children of the seed are the children of the kingdom of God, and of Christ,
and are blessed with faithful Abraham.
Whoever are of the saving, divine, precious faith, are of Abraham,
walk in the steps of the seed and faith of Abraham, and are blessed with him, yea,
of all nations, and all the families of the earth.

"`And the Lord said to Abraham,
'Thy seed shall be a stranger in a land that is not theirs, and shall serve them;
and they shall afflict them four hundred years; and that nation whom they shall serve,
will I judge; and afterwards shall they (to wit,
God's seed) come out with great substance,' Gen. 15:13-14. Here ye may see,
that which afflicts God's seed, he will judge, and did judge;
for he destroyed the first-born of Pharaoh, and overthrew him and his host.

"`A holy man said, 'Except the Lord of Sabaoth had left us a seed or remnant,
we had been as Sodom,' etc., that is, destroyed.
But in the Seed, which destroys the devil and his works,
and bruises the head of the serpent and his seed,
are all nations and families of the earth blessed.

"`Christ, according to the flesh, was of Abraham and of David,
for he took not on him the nature of angels, but the seed of Abraham,
in which seed all nations and families of the earth are blessed.
So they that are of his seed, are of the generation of Christ; are 'flesh of his flesh,
and bone of his bone.'
Now, all nations and families of the earth must be in this holy Seed,
if they have the blessings and are blessed.
And 'out of the mouth of this Seed's seed shall not God's word depart;
' but shall remain and abide in the mouth of this Seed's seed,
in which they are blessed,
Isa. 59:21. So it is not the first-birth's talking of the words of Christ, the Seed,
in whose mouth the word of God doth not abide; that makes an outward profession,
like the Jews who killed and persecuted the prophets, and crucified Christ, the Seed,
and substance of the law and prophets, which the Jews professed in words,
but they denied Christ, the Seed and Life.
And all Christians (so called) that profess the Scriptures in words,
and are not in the Seed, Christ, are in the confusion, and are like the Jews; and so,
neither Jews nor Christians are blessed, except they be in Christ, the Seed of Life.

"`But though Christ is said to be of the Seed of David, and of Abraham,
as his generation is declared by Matthew and Luke;
yet Christ was not born of the will of the flesh, nor of the will of man, but of God.
For he was conceived by the Holy Ghost, born of the Virgin,
and supposed to be son of Joseph, but was the Son of God.
His name was called Jesus,
because he should 'save his people from their sins;' and Emmanuel, God with us.
Christ took not upon him the nature of angels,
but the seed of Abraham (as I said before) and so 'was
made of the seed of David according to the flesh;
and declared to be the Son of God with power, according to the Spirit of holiness,
by the resurrection from the dead,' Rom. 1:4.
So the generation of Christ is a mystery.
Christ saw his Seed or Word grow up in his disciples; and 'Christ in you,
the hope of glory,' tho apostle calls 'The mystery,
which hath been hid from ages and generations;
but now is made manifest to the saints,' or sanctified ones,
Col. 1:26-27. 'Whom we preach; warning every man,
and teaching every man in all wisdom,
that we may present every man perfect in Christ Jesus,' ver. 28.
For in Christ, the second Adam, all are made perfect and complete;
and in Adam in the fall, all are deformed and made imperfect;
so out of Christ all mankind are imperfect and deformed: let them paint,
and dress themselves with the sheep's clothing, and with the form of godliness,
of the prophets', and Christ's, and his apostles' words ever so much;
yet if Christ be not in them, they are incomplete, imperfect, deformed, reprobates.
But the apostle tells the church of Christ, 'Ye are complete in Christ,
which is the head of all principality and power,' Col. 2:
10 (for he hath all power in heaven and in earth given to him,
Matt. 28:18). So all the saints are made perfect and complete in Christ Jesus;
blessed be the Lord God over all for ever, through Jesus Christ.
Amen, Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 15th of the 1st Month, 1686-7.

Quickly after this I returned to London,
and continued there a month in the service of the Lord;
being daily exercised either in public meetings,
or more particular services relating to the church of Christ;
as visiting such as were sick or afflicted,
and writing books or papers for the spreading of truth, or refuting of error.
As it was a time of general liberty,
the Papists appeared more open in their worship than formerly:
and many unsettled people going to view them at it,
a great talk there was of their praying to saints, and by beads, etc.,
whereupon I wrote a short paper concerning prayer; as follows:--

[.small-break]
'''

"`Christ Jesus, when he taught his disciples to pray, said unto them, 'When ye pray, say,
Our Father, which art in heaven, hallowed be thy name,' etc.
Christ doth not say, that they should pray to Mary, the mother of Christ;
nor doth he say, that they should pray to angels, or to saints, that were dead.
Christ did not teach them to pray to the dead, nor for the dead:
neither did Christ or his apostles teach the believers to pray by beads,
nor to sing by outward organs; but the apostle said he would sing and pray in the Spirit;
'for the Spirit itself maketh intercession; and the Lord, that searcheth the heart,
knoweth the mind of the Spirit.'

"`To take counsel of the dead, was forbidden by the law of God;
they were to take counsel of the Lord.
And he hath given Christ in the new covenant, in his gospel-day,
to be a counsellor and a leader to all believers in his light.
Men are not to run to the dead for the living;
for the law and testimony of God forbids it.
Those Jews that refused the running waters of Shiloh,
the floods and waters of the Assyrians and Babylonians came over them,
and carried them into captivity; and they that refuse the waters of Christ,
are overflowed with the flood of the world, that lieth in wickedness.
They that asked counsel of stocks and stones, were in the spirit of error and whoredom;
they were gone a whoring from God.
Hos. 4:12. And they that joined themselves to Baal-Peor,
and ate the sacrifices of the dead, provoked the Lord's anger,
and brought the Lord's displeasure upon them, Ps. 106:28-29. So here ye may see,
the sacrifices of the dead were forbidden.
The living know that they shall die, but the dead know not anything,
neither have they any more a reward; for the memory of them is forgotten,
Ecc. 9:5. 'Woe to the rebellious children, saith the Lord, that take counsel,
but not of me; and that cover with a covering, but not of my Spirit,
that they may add sin to sin,'`" Isa. 30:1.

[.signed-section-signature]
G+++.+++ F.

When I had stayed about a month in London, I got out of town again;
for by reason of the many hardships I had undergone in imprisonments,
and other sufferings for truth's sake, my body was grown so infirm and weak,
that I could not bear the closeness of the city long together;
but was obliged to go a little into the country, for the benefit of the fresh air.
At this time I went with my son-in-law William Mead,
to his countryhouse called Gooses in Essex, where I stayed about two weeks;
and among other services I had there, I wrote the following paper:--

[.blurb]
=== "`A Distinction between the True Offering and Sacrifice, and the False, in the Old and New Covenant.

"`The Lord saith, 'He that sacrificeth to any God, save unto the Lord only,
he shall be utterly destroyed.'
Ex. 22:20. So no God is to be minded, nor sacrificed to, but the Lord God:
it is death to sacrifice to any other God, save the Lord.
The Lord saith also, 'Thou shalt not offer the blood of my sacrifice with leavened bread.'
Ex. 23:18. So that sour, heavy leaven, must not be offered with the Lord's sacrifice.
Again the Lord saith, 'Thou shalt not build an altar of hewn stone:
for if thou lift up thy tool upon it,
thou hast polluted it,' Ex. 20:25.
Therefore have a care of polluting the altar with your own tools,
you that profess to offer the spiritual sacrifice.

"`Jonah said, 'he would sacrifice unto the Lord with the voice of
thanksgiving,' when he was in the fish's belly;
and there he prayed unto the Lord, Jonah ii.
For Jonah in the whale's belly had no lambs, nor rams, nor outward sacrifices to offer.'

"`The Lord forbids his people to sacrifice with harlots,
Hos. 4:14. And the Lord forbids his people to offer sacrifice of the blind, lame,
sick, or that which was deformed, or had any blemish; as in Mal. 1 and many other places.
So they that offer spiritual sacrifice, must not offer the blind, lame, blemished,
or deformed sacrifice to God.`"

"`The scribe saith unto Christ, 'To love God with all the heart,
and with all the understanding, and with all the soul, and with all the strength,
and to love his neighbour as himself,
is more than all whole burnt-offerings and sacrifices,' Mark
12:33. And when Jesus saw that he answered discreetly,
he said unto him, 'Thou art not far from the kingdom of God,' v. 34. To love God,
and their neighbour as themselves,
was more than whole burnt-offerings and sacrifices in the time of the law;
therefore all offerings and sacrifices in the time of the gospel,
if there be not love to God, and to their neighbour as themselves, avail nothing.

"`David said, 'Let them sacrifice a sacrifice of thanksgiving,
and declare his works with rejoicing,' Ps. 107:22. These
are the sacrifices that the Lord requires of his people,
more than outward sacrifices.
David said, 'Let my prayer be set forth before thee, as incense;
and the lifting up of my hands,
as the evening sacrifice,' Ps. 141:2. Here David looks upon his prayer to the Lord,
and the lifting up of his hands to him, to be accepted with the Lord,
as much as the outward incense, and the outward evening sacrifice.
Again David says, 'The sacrifices of God are a broken spirit;
a broken and a contrite heart, O God,
thou wilt not despise,' Ps. 51:17. (See also Isa. 57:15; 66:2.)
These are the sacrifices that David said God would accept, and not despise;
which are beyond the unbroken spirit, and uncontrite heart,
with outward offerings and sacrifices.

"`The adversaries of the Jews would have joined
with them towards the building of the temple,
saying unto them, 'Let us build with you, for we seek your God, as ye do;
and we do sacrifice unto him.'
But the Jews refused them, and said, 'You have nothing to do with us,
to build a house unto our God,' Ezra 4:2-3. Here ye may see
that God's people refused their building with them,
and their sacrifice.
Solomon saith,
'The sacrifice of the wicked is an abomination to the
Lord,' Prov. 15:8. (See also Isa. 1:11; 66:3.)
Solomon also saith, 'Better is a dry morsel, and quietness therewith,
than a house full of sacrifices with strife,'
Prov. 17:1. Now let all people consider,
what good your house full of sacrifices doth with strife,
when a dry morsel and quietness therewith is better?
Consider, all people, if ye live in wickedness,
your sacrifice is an abomination to the Lord.

"`Again, Solomon speaking of the sacrifice of fools, saith,
'They consider not that they do evil,' Ecc. 5:1.
Fools are such as do not walk in the Spirit of God,
or begin in the Spirit, and end in the flesh, like the foolish Galatians;
for the Spirit of God is the Spirit of wisdom and understanding,
and cannot join with the sacrifices of the dead, nor of the fools,
nor of the wicked whose sacrifice is abominable; who grieve and quench the Spirit of God;
by which the spiritual and righteous offer up spiritual sacrifices,
acceptable to God by Jesus Christ.

"`The apostle Paul said, he was the 'minister of Jesus Christ to the Gentiles,
ministering the gospel of God, that the offering up of the Gentiles might be acceptable,
being sanctified by the Holy Ghost,' Rom. 15:16. So ye may see,
that all the acceptable offerings and sacrifices
to God must be sanctified by the Holy Ghost.
The same apostle saith to the Corinthians, 'Ye are bought with a price;
therefore glorify God in your body, and in your spirit,
which are God's,' 1 Cor. 6:20. And to the Romans, he saith, 'I beseech you, brethren,
by the mercies of God, that you present your bodies a living sacrifice, holy,
acceptable unto God,
which is your reasonable service,' Rom. 12:1.
This is the duty of all true Christians.

"`Peter also saith, in his general epistle to the church of Christ, 'Ye also,
as lively stones, are built up a spiritual house, a holy priesthood,
to offer up spiritual sacrifices,
acceptable to God by Jesus Christ,' 1 Pet. 2:5. So every man and
woman must come to the Spirit of God in their own hearts,
if they offer up spiritual sacrifices, acceptable to God by Jesus Christ.
For as Christ saith,
'Every sacrifice shall be salted with salt,'
Mark 9:49. And in the Old Testament ye may see,
all their outward offerings they were to season with salt, Lev. 2:13,
a type and figure of Christ, who gave himself for us, an offering and a sacrifice to God,
for a sweet-smelling savour,
Eph. 5:2. Therefore all his people must be
baptized with the Holy Ghost and with fire,
that they may be salted with fire, and every sacrifice salted with salt,
with the Spirit of grace, that is poured upon all;
so that they may offer up this spiritual sacrifice, acceptable to God by Jesus Christ.

"`Samuel said to king Saul,
'Hath the Lord as great delight in burnt-offerings and sacrifices,
as in obeying the voice of the Lord?
behold, to obey is better than sacrifice; and to hearken,
than the fat of rams,' 1 Sam. 15:22. So ye may see,
all offerings and sacrifices are nothing,
if there be not a hearkening to the Lord in his Spirit, and an obeying of his voice.
Christ told the Jews, that were outward sacrificers, that he would have mercy,
and not sacrifice; and bid them 'Go and learn what that meaneth,'`" Matt. 9:13.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 28th of the 2nd Month, 1687.

The beginning of the 3rd month I returned to London,
and continued there till after the Yearly Meeting, which began on the 16th of the same,
and was very large, Friends having more freedom to come up out of the counties to it,
by reason of the general toleration and liberty now granted.
The meeting lasted several days;
and at the close thereof it was upon me to write the following lines,
to be dispersed amongst Friends everywhere,
as--"`A word of counsel and caution to them to
walk circumspectly in this time of liberty:`"--

[.salutation]
"`Dear Friends And Brethren, In The Lord Jesus Christ,

"`The Lord, by his eternal arm and power, having supported you in all your sufferings,
and great spoiling of goods, and tedious imprisonments,
only for serving and worshipping the living God that made you;
who gave up wife and children, and goods, and suffered the spoil of them,
and imprisonment for his truth and name's sake;--the Lord,
by his infinite power and mercy,
having been pleased to open the king's heart towards you,
by which you are set at liberty from jails, and the spoilers of your goods are stopped,
whereby ye may follow your callings, confess Christ Jesus,
and call him Lord by the Holy Ghost, in your assemblies and meetings,
without being cast into jails, or having your goods spoiled;
a great concern lies upon me from the Lord to write unto you, dear brethren,
that none may abuse this liberty, nor the mercies of the Lord, but prize them;
for there is great danger in time of liberty, of getting up into ease, looseness,
and false liberty.
And now, seeing that ye have not the outward persecutors to war with in sufferings,
with the spiritual weapons keep down that which would not be subject to Christ; that He,
the Holy One, may reign in your hearts; that your lives, conversations, and words,
may preach righteousness and truth;
that ye may all show forth good ensamples of true believers in Christ, in virtue,
and holiness, answering that which may be known of God in all people,
that ye are the sons and daughters of God; standing fast in that righteous,
holy liberty in Christ, the just and holy One, that has made you free,
over the loose or false; shunning vain disputes,
and foolish questions of men of corrupt minds;
for the serpent was the first questioner of Eve, who drew her and Adam out of the truth.
Therefore as ye have received Christ, live and walk in Him,
who bruises the serpent's head, who is your safe sanctuary, in whom ye have election,
reconciliation, and peace with God.
Therefore live in the peace which ye have from Christ, which is not of this world;
be at peace one with another, and seek the peace of all men in Christ Jesus;
for blessed are the peacemakers.
Labour to exercise a good conscience towards God,
in obedience to him in what he requires;
and in doing to all men the thing that is just and honest;
in your conversations and words, giving no offence to Jew or Gentile,
nor to the church of God.
So ye may be as a city set on God's Sion-hill, which cannot be hid;
and may be lights to the dark world,
that they may see your good fruits and glorify your Father, which is in heaven;
for he is glorified in your bringing forth good fruits, as ye abide in Christ, the vine,
in this his day of life, power, and light, that shines over all.
Therefore all you that believe in the light, walk in the light, as children of the light,
and of Christ's everlasting day;
that in the light ye may have fellowship with the Father and the Son,
and one with another; keeping in the unity of his Holy Spirit,
in the bond of his holy peace, in his church that he is head of.
My desire is, that God's wisdom everywhere may be justified of her children,
and that it may be showed forth in meekness, and in the fear of the Lord in this his day.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

By that time the Yearly Meeting was over, I was very much wearied and spent; wherefore,
about a week after the meeting,
I got out of town to a Friend's house a little beyond Edmonton, where,
and at South Street, I abode some time, and had meetings amongst Friends there;
and at Winchmore-hill and Berry Street.
And having my mind continually exercised in the things of God,
the sense of his infinite goodness and mercy to mankind in visiting
them after they had transgressed and rebelled against him,
and providing a way and means for their return to him again, was very much upon me,
and in the opening of the Spirit of truth I wrote the following paper on that subject:--

[.small-break]
'''

"`God, who made all mankind, though they have transgressed his commands and laws,
rebelled against him, hated his light, grieved his Spirit,
and walked despitefully against his Spirit of grace; God, who is merciful,
would yet have all to be saved, and come to the knowledge of the truth.
All that come to the knowledge of the truth must know it in their inward parts; I say,
all that know and find the grace and truth which comes by Jesus,
do know and find it in their hearts.
And such find the hidden man of the heart, the pearl, the leaven,
the lost piece of silver, and the kingdom of heaven within.
For until they come to the light and truth in their hearts,
all are strangers to these things,--are in Adam, in the fall from the image of God,
and from his light, power, Spirit, and kingdom.
But Christ that never fell,
brings man and woman that follow him again to know these things, to know the truth,
and Him the Saviour, and brings them into his image, and his everlasting kingdom.

"`The devil, who is out of the truth, tempted man and woman to disobey God;
and so drew them into the fall from the truth.
It is the devil that hath stopped men's eyes, ears, and hearts from the truth,
who is called the god of the world; who hath blinded the eyes of infidels, or heathen.
But Christ, who bruises the serpent's head, and destroys the devil and his works,
doth open men's hearts, eyes, and ears.
He is their Saviour and Redeemer,
and giveth life eternal to his people that obey him and his truth.
Blessed be the Lord for ever through Jesus Christ, who hath tasted death for all men,
to bring them out of the death of Adam;
who is a propitiation for the sins of the whole world, and gave himself a ransom for all,
to be testified of in due time.
For as by Adam's transgression and disobedience death and condemnation came upon all,
so by Christ's obedience unto death justification of life is come upon all;
and he that believeth in Christ hath eternal life;
but he that doth not is condemned already.
But God would have all men to be saved,
and come unto the knowledge of the truth as it is in Jesus, who is their Saviour;
and in Him there is no condemnation.`"

[.signed-section-signature]
G+++.+++ F.

After I had been a while here, I went to a monthly meeting at Enfield,
and thence with some Friends to Hertford; where I stayed three or four days,
visiting Friends both at their public meetings on First-day,
and at their quarterly meetings of men and women;
and good service for the Lord I had amongst them.
Then passing to Waltham Abbey, I had a very good meeting with Friends there:
and next day went thence to another place, to compose a difference, which,
for want of a right understanding of each other, had happened between some Friends.
I returned; to Waltham that night;
and next day went with some Friends to William Mead's house, in Essex.

Here I stayed some weeks, yet was not idle, but often visited the meetings thereabouts;
as at Wanstead, Barking,
and at John Harding's. Between meeting and meeting I
wrote many things for the spreading of truth,
and for the opening of people's understandings to receive it.
One was a paper proving, from the Scriptures,
that people must repent before they can receive the gospel, and the Holy Spirit,
and the kingdom of God, or be baptized; after this manner:--

[.small-break]
'''

"`John the Baptist came preaching in the wilderness of Judea, saying, 'Repent ye:
for the kingdom of heaven is at hand,' Matt. 3:2.
And when John the Baptist was cast into prison,
Mark says, 'That Jesus came into Galilee, preaching the gospel of the kingdom of God,
and saying, The time is fulfilled, and the kingdom of God is at hand: Repent ye,
and believe the gospel,' Mark 1:14-15. Matthew also says,
'From that time Jesus began to preach, and to say, Repent,
for the kingdom of heaven is at hand,' Matt., 4:17.
And when Christ sent forth his twelve disciples, two and two,
they went out and preached that men should repent, Mark 6:12. Christ said to the Jews,
'Except ye repent,
ye shall all likewise perish,' Luke 13:3,5. When the
publicans and sinners came to hear Christ,
and the Pharisees and Scribes murmured saying,
'This man receiveth sinners and eateth with them,' Luke 15:1-2,
Christ reproved them by a parable, and then told them,
'Joy shall be in heaven over one sinner that repenteth,
more than over ninety and nine just persons which need no repentance,' ver. 7, adding,
'There is joy in the presence of the angels of God over one sinner that repenteth,' ver. 10.
Christ, after he was risen, said unto his disciples,
'That repentance and remission of sins should be preached in his name among all nations,
beginning at Jerusalem,' Luke 24:47. Peter said unto the Jews, 'Repent and be baptized,
every one of you, in the name of Jesus Christ, for the remission of sins;
and ye shall receive the gift of the Holy Ghost,' Acts 2:38. And Paul said,
'The times of this ignorance God winked at;
but now commandeth all men everywhere to repent,' Acts
17:30. Simon Magus was called to repentance,
if he had regarded it, Acts 8:22. And the apostle Paul preached at Damascus,
and at Jerusalem, and throughout all the coasts of Judea,
and then to the Gentiles (turning them from darkness to the light of Christ,
and from the power of Satan to God), that they should 'repent and turn to God,
and do works meet for repentance,' Acts 26:20.

"`Here ye may see that people must repent before they believe, and are baptized,
and before they receive the Holy Ghost, and the kingdom of God.
They must repent of their vain life and conversation before they receive the gospel,
be turned from darkness to the light of Christ, and from, the power of Satan unto God,
before they receive his Holy Spirit, and his gospel of life and salvation.
The Lord commands all men everywhere to repent, and do works meet for repentance.
They must show forth that their lives and conversations are changed,
and that they serve God in newness of life, with new tongues and new hearts.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 6th Month, 1687

[.offset]
Another short paper I wrote about the same time,
showing wherein God's people should be like unto him.
It was thus:--

"`God is righteous; and he would have his people to be righteous, and to do righteously.
God is holy; and he would have his people holy, and to do holily.
God is just; and he would have his people to be just, and to do justly to all.
God is light; and his children must walk in his light.
God is an eternal, infinite Spirit; and his children must walk in the Spirit.
God is merciful; and he would have his people to be merciful.
God's sun shines upon the good and the bad,
and he causes the rain to fall upon the evil and the good;
so should his people do good unto all.
God is love; and they that dwell in love dwell in God.
Love worketh no ill to his neighbour: therefore,
love is the fulfilling of the law,' Rom. 13:10. The apostle says,
'All the law is fulfilled in one word, even in this,
Thou shalt love thy neighbour as thyself,' Gal. 5:14. 'As the Father hath loved me,
so I have loved you:
continue ye in my love,' John 15:9. This should be the practice of all God's people.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 6th Month, 1687.

[.offset]
And because most people would confess, that God's people should be thus,
but few know how to come to this state;
therefore in the openings of the Spirit of truth I wrote another short paper,
directing to "`the right way and means, whereby people might come unto Christ,
and so be made like unto God.`"
Thus:--

"`Christ saith, 'I am the way, the truth, and the life; no man cometh unto the Father,
but by me,' John 14:6. And again, 'No man can come to me, except the Father,
which hath sent me, draw him,' John vL 44. Now,
what is the means by which God doth draw people to his Son, but by his Holy Spirit,
who 'poureth out of his Spirit upon all flesh.'
By this Holy Spirit,
the holy and righteous God doth draw people from their unrighteousness and unholiness,
to Christ, the righteous and holy One,
the great Prophet in his New Covenant and New Testament,
whom Moses in the Old Covenant and Testament said, God would raise up, like unto him,
and whom people should 'hear in all things: and they that would not hear him,
should be cut off.'
They that do not hear the Son of God, the great Prophet,
do not mind the drawing of the Father by his Holy Spirit to his Son;
but to them that mind the drawings of the good Spirit of the Father to his Son,
the Spirit giveth understanding to know God and Jesus Christ, which is eternal life.
Then they know that Jesus Christ is the way, the truth, and the life,
and that none can come unto God but by and through his Son,
who is their Shepherd to feed them in his pastures and springs of life;
and his sheep know his holy voice, in whom there was no sin,
and in whose mouth there was no guile; and a hireling they will not hear,
for he careth not for the sheep; for they are not the hireling's, but Christ's,
who hath laid down his life for his sheep.
He that robs and steals his neighbour's words, that climbeth up another way,
and entereth not by the door, is a thief and a robber;
but Christ is the door into his sheepfold, for his sheep to enter in by.
They know that Christ is the Bishop of their souls,
to see that they do not go astray from God, nor out of his pastures of life;
they know that Christ is their Mediator, and makes their peace with God;
and they know that Christ is their High-priest, made higher than the heavens,
and hath died for their sins, doth cleanse them with his blood,
is risen for their justification;
and is able to the utmost to save all that come to God by him.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 6th Month, 1687.

[.offset]
Before I left this place I wrote another paper, to show,
by many instances from the Holy Scriptures, that the kingdom of God,
which most people talk of at a distance, and refer altogether to another life,
is in some measure to be known and entered into in this life;
but that none can know an entrance thereinto, but such as are regenerated and born again.
Of that paper the following is a copy:--

"`Christ saith, 'Except a man be born again,
he cannot see the kingdom of God,' John 3:3. 'That which is born of the flesh,
is flesh; and that which is born of the Spirit is spirit,' ver. 6.
So, 'except a man be born of water and of the Spirit,
he cannot enter into the kingdom of God,' ver. 5.
And John, writing to the seven churches in Asia, calls himself their brother,
and companion in tribulation, and in the kingdom and patience of Jesus Christ, Rev. 1:9.
Here you may see, that John was in the kingdom; so he was born again:
for he not only saw the kingdom, but was in it.

"`And John saith, 'Behold, what manner of love the Father hath bestowed upon us,
that we should be called the sons of God; therefore the world knoweth us not,
because it knew him not,' 1 John 3:1. 'Beloved, now are we the sons of God,' ver. 2.
'If ye know that he is righteous,
ye know that every one that doeth righteousness is born
of him,' chap. 2:29. 'Whosoever is born of God,
doth not commit sin; for his seed remaineth in him, and he cannot sin,
because he is born of God,' chap. 3:9. Again John saith, 'Let us love one another;
for love is of God; and every one that loveth, is born of God, and knoweth God.
He that loveth not, knoweth not God;
for God is love,' chap. 4:7-8. 'Whosoever believeth that Jesus is the Christ,
is born of God,' chap. 5:1. And, 'Whosoever is born of God, overcometh the world;
and this is the victory that overcometh the world, even our faith,' ver. 4.
Were not these, that were born of God, in the kingdom of God?
And seeing, John says, every one that doeth righteousness, is born of God,
do not such see the kingdom of God that stands in righteousness, and enter into it?

"`Peter, in his first general epistle to the church of Christ, saith,
'As new-born babes desire the sincere milk of the Word,
that ye may grow thereby,' 1 Pet. 2:2. And
he tells them they were a chosen generation,
a royal priesthood, a holy nation, a peculiar people;
that they should show forth the praises of Him who had
called them out of darkness into his marvellous light, ver. 9.
And that, as lively stones, they were built up a spiritual house, a holy priesthood,
to offer up spiritual sacrifices, acceptable to God by Jesus Christ, ver. 5.
Did not these new-born babes, these lively stones, spiritual household,
royal priesthood, holy nation, and chosen generation,
who were called out of darkness into Christ's marvellous light, see,
and enter into his holy kingdom, being heirs of the same?
who were born again, not of corruptible seed, but of incorruptible, by the Word of God;
which liveth and abideth for ever,
1 Pet. 1:23. And had these not an entrance ministered to them
into the everlasting kingdom of our Lord and Saviour Jesus Christ?

"`James, in his general epistle to the church of Christ, says,
'Hath not God chosen the poor of this world, rich in faith, and heirs of the kingdom,
which he hath promised to them that love him?'
James 2:5. The apostle Paul says, 'God sent forth his Son, made of a woman, etc.,
to redeem them that were under the law; that we might receive the adoption of sons;
and because ye are sons, God hath sent forth the Spirit of his Son into your hearts,
crying, Abba, Father.
Wherefore thou art no more a servant, but a son; and if a son,
then an heir of God through Christ,' Gal. 4:4-7. The same apostle says,
'As many as are led by the Spirit of God,
they are the sons of God;' and tells the saints at Rome,
'Ye have received the spirit of adoption, whereby we cry, Abba, Father.
The Spirit itself beareth witness with our spirit, that we are the children of God;
and if children, then heirs; heirs of God, and joint-heirs with Christ;
if so be we suffer with him, that we may be also glorified together (namely,
with Christ),' Rom. 8:14-17. Now seeing they are
the sons of God that are led by the Spirit of God,
and the Spirit beareth witness unto their spirit, that they are the children of God,
and heirs of God, and joint-heirs with Christ,
are not all these children of God heirs of the righteous, glorious kingdom of God?
and do they not see it, and enter into it?

"`The Lord saith in Hosea 1:10, 'Where it was said unto them, Ye are not my people;
there it shall be said unto them, Ye are the sons of the living God.'
Did not this relate to the gospel-days of the new covenant?
see Rom. 9:26. And what the Lord said by the prophet Jeremiah, chap. 31:1,
the apostle applies to the gospel-days, and says, 'Be ye separate, saith the Lord,
and touch not the unclean thing; and I will receive you, and will be a Father unto you,
and ye shall be my sons and daughters, saith the Lord Almighty,
2 Cor. 6:18. Are not these the children that see,
and enter into the righteous kingdom of God, that separate from that which is unclean,
and touch it not?

"`The Lord saith also by Isaiah, 'I will say to the north, Give up; and to the south,
Keep not back; bring my sons from far, and my daughters from the ends of the earth?'
Isa. 43:6. Then does not he bring them to his kingdom of glory,
that stands in righteousness, and peace, and joy in the Holy Ghost?

"`The Lord said to Job, 'When the morning stars sang together,
and all the sons of God shouted for joy,' Job 38:7,
where did these sons of God shout for joy?
Was it not in his kingdom of glory?

"`Christ saith,
'The least in the kingdom of God is greater than
John,' Luke 7:28. And in chap. 16:16,
he says, 'The law and the prophets were until John: since that time (viz., since the law,
and the prophets, and John) the kingdom of God is preached,
and every man presseth into it.'

"`' The good seed are the children of the kingdom,'
Matt. 13:38. And 'the righteous shall shine forth,
as the sun, in the kingdom of their Father,' ver. 43.
Christ said unto his disciples,
'Unto you it is given to know the mysteries of the kingdom of God,'
Mark 4:11. And Christ lifted up his eyes upon his disciples,
and said, 'Blessed be ye poor:
for yours is the kingdom of God,' Luke 6:20.
And the apostles preached the kingdom of God.
These were born again; that saw and knew the kingdom of God, and preached it.

"`Christ said to his disciples, 'Pear not, little flock,
for it is your Father's good pleasure to give you the kingdom,' Luke 12:32. And,
'I appoint unto you a kingdom,' said Christ,
'as my Father hath appointed unto me,' chap. 22:29. The Lord said,
'He that overcometh, shall inherit all things: and I will be his God,
and he shall be my son,' Rev. 21:7. And John saith, 'I have written unto you,
young men, because ye are strong, and the Word of God abideth in you,
and ye have overcome the wicked one,' 1 John 2:14. And Christ, by whom are all things,
is said 'to bring many sons to glory,' Heb. 2:10.

"`Christ said, 'Woe unto you, scribes and Pharisees, hypocrites;
for ye shut up the kingdom of heaven against men; for ye neither go in yourselves,
neither suffer them that are entering, to go in,' Matt. 23:13. He also said,
'Woe unto you, lawyers; for you have taken away the key of knowledge;
ye enter not in yourselves;
and them that were entering in ye hindered,' Luke 11:52.
Christ gives unto his children the key of the kingdom,
his Spirit; but the scribes, and the Pharisees, and the lawyers, great professors,
who were erred from the Spirit,
like the great professors in our age that scoff at the Spirit,
and draw people from the Spirit of God within, these shut up the kingdom from men,
and draw people from the key of knowledge, and the key of the kingdom.
'For no man knows the things of God, but by the Spirit of God;
for the things of God are spiritually discerned.'
So the Spirit is the key, by which the kingdom of God, and the things of God,
are revealed and discerned, and known, according to 1 Cor. 2:10-11,13,14.
The apostle names some in his epistle to the Colossians, and says,
'These are my fellow-workers unto the kingdom of
God,' Col. 4:11. And he tells that church,
that 'God hath delivered us from the power of darkness,
and hath translated us into the kingdom of his dear Son,
' chap. 1:13. So ye may see these were born again,
that were translated into the kingdom of Christ,
and were fellow-workers unto the kingdom of God.

"`Christ exhorts his disciples to love and to do good,
that they might be the children of their Father, which is in heaven,
Matt. 5:45. He bids them be perfect, even as their Father which is in heaven,
is perfect; ver. 48.
The apostle saith to the church at Philippi, 'That ye may be blameless and harmless,
the sons of God, without rebuke, in the midst of a crooked and perverse nation,
amongst whom ye shine as lights in the world, holding forth the word of life,' etc.
Phil. 2:15-16. And writing to the church of the Thessalonians,
he puts them in mind how he had exhorted them that they would 'walk worthy of God,
who had called them into his kingdom and glory,' 1 Thess. 2:12.

"`The Lord had promised by the prophet Joel,
that he would 'pour out his Spirit upon all flesh,' and
that 'sons and daughters should prophesy,
old men should dream dreams,
and young men see visions,' Joel 2:28. Now the cause that sons and daughters,
handmaids, servants, young men, and old men, have not these heavenly visions, dreams,
and prophecies, is, because they are erred from the Spirit of God,
which he poureth upon them: but as many as are led by the Spirit of God,
are the sons of God.

"`John saith, Christ was the 'true light,
which lighteth every man that cometh into the world,' John 1:9;
and that 'As many as received him,
to them gave he power to become the sons of God;' ver 12, 'which were born, not of blood,
nor of the will of the flesh, nor of the will of man, but of God,' ver. 13.
Now, the reason why people do not become the sons of God,
is because they do not receive Christ.
The Jews, the great professors, who had the promises, prophecies, figures,
and shadows of him, would not receive him when he came.
And now the priests and high professors of Christ,
are so far from receiving the light of Christ, and believing in it,
that they hate the light, and scoff at it, calling it a natural conscience; and some,
Jack-in-the-lantern.
Such are not like to become the sons of God, nor to see the glorious kingdom of Christ,
which stands in righteousness, peace, and joy in the Holy Ghost.
For the light that shines in the heart,
gives 'the light of the knowledge of the glory of God in the face of Christ Jesus.'
They that do not receive Christ Jesus,
but hate his light (which is the life in him) and yet profess him in words,
neither know the children of the light, nor true fellowship in the light,
nor the kingdom of God, that stands in righteousness, peace, and joy in the Holy Ghost;
but by the light they are condemned.
'And this is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil.
For every one that doeth evil, hateth the light, neither cometh to the light,
lest his deeds should be reproved,' John 3:19-20. But the children of the light,
that walk in the light, come to heavenly Jerusalem, and to the city of the living God,
to the innumerable company of angels,
and to the general assembly and church of the firstborn, that are written in heaven,
and can sing Hallelujah!`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 2nd of the 7th Month, 1687.

Having been more than a quarter of a year in the country, I returned to London,
somewhat better in health than formerly, having received much benefit by the country air.
And it being now a time of general liberty, and great openness amongst the people,
I had much service for the Lord in the city; being almost daily at public meetings,
and frequently taken up in visiting Friends that were sick,
and in other services of the church.
I continued at London about three months; and then finding my strength much spent,
with continual labouring in the work of the Lord,
and my body much stopped for want of fresh air, I went down to my son Rous's,
by Kingston, where I abode some time, and visited Friends at Kingston.
While I was there, it came upon me to write a paper concerning the Jews,
showing "`how by their disobedience and rebellion, they lost the holy city and land.`"
By which example the professed Christians may see what they are to expect,
if they continue to disobey and provoke the Lord.
The copy here follows:--

[.small-break]
'''

"`The Lord gave the Jews in the Old Testament the land of Canaan,
and they built the temple at Jerusalem to worship in.
It was called 'the holy temple;' and Jerusalem was
called 'the holy city;' and Canaan 'the holy land.'
But when the Jews rebelled against the good Spirit, which God gave to instruct them,
rebelled against his law, set up idols and images, and defiled the land and the city,
the Lord sent his prophets to cry against them, to bring them back again to his Spirit,
and to his law, and so to God, to serve and worship him,
that they might not worship images and idols, the works of their own hands.
But instead of hearkening to God's prophets, they persecuted them,
and at last killed his Son Christ Jesus, and persecuted his apostles.
But Christ told the Jews, that both their city and temple should be laid waste,
and they should be scattered over all nations: and it was so.
Titus the Roman emperor came and took Jerusalem, and destroyed the city and temple;
which was a day of vengeance upon the Jews for all their idolatries and their wickedness,
and for the innocent blood they had shed, both in the city and country;
and they were driven out of their own city and land, and scattered over all nations.
The Jews have never had power to obtain the land since, nor to build Jerusalem,
nor the temple; but the Turk hath both the land of Canaan,
and that which is called 'the city of Jerusalem.'
Now, the Turk neither makes images, nor worships images;
and so it is a just hand of the Lord, that he should be over the persecuting,
idolatrous Jews, so that they cannot defile the land of Canaan now with images and idols,
for the Turk hath it, who neither makes images, nor idols, nor worships them.
The Jews must never hope, believe, nor expect,
that ever they shall go again into the land of Canaan,
to set up an outward worship at Jerusalem,
and there for their priests to offer outward sacrifices of rams, sheep, and heifers,
fee., for burnt-offerings; for Christ, the one offering,
hath offered himself once for all,
and by this one offering he hath perfected for ever them that are sanctified.
And Christ hath changed the priesthood of Aaron, that offered sacrifices,
that was made after the power of a carnal commandment;
but Christ was made after the power of an endless life, a Priest for ever, who is holy,
harmless, separate from sinners, and made higher than the heavens.
This is the Priest that gives power to all that receive him,
to become the sons and daughters of God; and Jerusalem that is above,
is the mother of all the sons and daughters of God, and is free;
but Jerusalem that is below, is in bondage with her children.
They that are the children of Jerusalem that is above,
do not look down at Jerusalem that is below; but they look at Jerusalem that is above,
which is their mother.
Christ said, 'Neither at outward Jerusalem, nor in the mountain of Samaria,
should God be worshipped; but God should be worshipped in Spirit and in truth;
for he is a Spirit, and such he seeks to worship him,' John iv.
This is the worship that Christ set up above sixteen hundred years ago;
and therefore the;
idolatrous Jews must never think to offer their outward offerings and sacrifices,
nor set up their outward worship at Jerusalem, in the holy land of Canaan more.
For Christ, by the offering up of himself once for all, for the sins of the whole world,
hath ended all the Jews' offerings, and changed the priesthood,
and the law by which it was made; and hath blotted out the hand-writing of ordinances,
which commanded both priests and offerings; and triumphed over them.
So he is the offering and sacrifice of all the children of the New Testament,
and New Covenant, and heavenly New Jerusalem, that is above.
He is their Prophet that openeth to them; their Shepherd that feeds them;
their Bishop that oversees them; and Priest that died for their sins,
and is risen for their justification;--who sanctifies and presents them to God.
He is the one Mediator between God and man, even the Man Christ Jesus.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 9th of the 10th Month, 1687.

After this I went to Guildford to visit Friends there, and stayed three days with them;
having a large and very good meeting there on First-day.
After which I came back to Kingston again, and tarried about two weeks longer,
visiting Friends, and having meetings amongst them,
both at their public meeting-house and in their families.
Many things I wrote while I was at Kingston; among which was the following:--

"`God So loved the world, that he gave his only begotten Son,
that whosoever believeth in him, shall not perish (mark, not perish),
but have everlasting life,' John 3:16. Again, he saith,
'He that believeth on the Son of God, hath (mark, hath) everlasting life,' ver. 36.
So these believers have everlasting life while they are upon the earth.
And 'He that believeth on Christ is not condemned; but he that believeth not,
is condemned already, and the wrath of God abideth on him.'
And, 'He that heareth Christ's word, and believeth on God that sent him, hath (mark,
hath) everlasting life, and shall not come into condemnation,
but is passed from death,' the death in the first Adam, 'unto life,' the life in Christ,
the second Adam, John 5:24. And that meat which Christ doth give,
endureth unto everlasting life, as in John 6:27. And the water that Christ doth give,
shall be in him that drinks it,
'a well of water springing up into everlasting
life,' John 4:14. Christ said to the Jews,
'Search the Scriptures, for in them ye think ye have eternal life;
and they are they which testify of me; and ye will not come to me,
that ye might have life,' John 5:39-40. Here
ye may see eternal life is to be found in Christ,
and not in the Scriptures, which testify of Him, the Life.
Christ's sheep that hear his voice, know and follow him; he gives them eternal life,
and they shall not perish, neither shall any pluck them out of his hand.
They shall not pluck Christ's sheep, to whom he hath given eternal life, out of his hand.
Christ said to Martha, 'I am the resurrection and the life; he that believeth in me,
though he were dead (mark, though he were dead) yet shall he live; (mark, live,
though he were dead); and whosoever liveth, and believeth in me, shall never die.
Believest thou this?
Martha said, Yea, Lord,' John 25:26. This is the true and substantial belief,
which they that believe, shall not perish, but have everlasting life.
John saith, 'This is the record, that God hath given to us eternal life;
and this life is in his Son,' 1 John 5:11. 'The life was manifested,
and we have seen it and bear witness, and show unto you that eternal life,
which was with the Father,
and was manifested unto us,' 1 John 1:2. So these were the believers,
that had eternal life in the Son of God, and showed it unto others.
'He that hath the Son hath life,' says John, 'and he that hath not the Son of God,
hath not life,' 1 John 5:12. Christ says, 'Every one that hath forsaken houses,
or brethren, or sisters, or father, or mother, or wife, or children, or lands,
for my name's sake, shall receive an hundred fold,
and shall inherit everlasting life,' Matt. 19{^
}29. The wicked that do not receive Christ,
shall go into everlasting punishment; but the righteous into eternal life.
The true servants of God have their fruits unto holiness,
and their end is everlasting life; for 'the wages of sin is death;
but the gift of God is eternal life, through Jesus Christ our Lord.'
Such have a building of God, a house not made with hands, eternal in the heavens.
Therefore I desire, that God's people may endure all things,
that they may obtain this salvation, which is in Christ Jesus, with eternal glory.
For Christ being made perfect,
became the Author of eternal salvation to all them that obey him.
This eternal salvation is above an external salvation;
for they come to receive an eternal inheritance,
and live in the possession of the everlasting gospel of joy, comfort, peace,
and salvation, having everlasting life in Christ Jesus.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 6th of the 11th Month, 1687.

[.offset]
Another paper I wrote there, concerning the Stone spoken of by Daniel, chap. 2,
which became a great mountain, and filled the whole earth; showing,
"`that thereby was set forth the kingdom and power of Christ:`"--

"`When Christ, the Stone, that became a great mountain, and filled the whole earth,
had broken to pieces the head of gold, and the breast of silver, and the belly of brass,
and the legs of iron, and the feet part iron part clay (which were the four monarchies,
to wit, the Babylonian and Mede, the Persian, the Grecian, and the Roman),
and had ended the outward Jews' typical kingdom; Daniel saith,
'In the days of these kings shall the God of heaven set up a kingdom,
which shall never be destroyed,' Dan. 2:44. Christ saith,
'All power is given unto me in heaven and in earth,' Matt. 28:18. And,
'My kingdom is not of this world,' John 18:36.
'Christ is the image of the invisible God,
the Firstborn of every creature.
For by him were all things created, that are in heaven, and that are in earth,
visible and invisible, whether they be thrones, or dominions, or principalities,
or powers; all things were created by him, and for him; and he is before all things,
and by him all things consist,' Col. 1:15-17. Here ye may see,
all things consist by Jesus Christ, and all things were created by Christ, and for him,
whether they be things in heaven, or things in earth, visible or invisible,
they were created by him and for him; yea, thrones, dominions, principalities,
and powers, these were all created by him and for him.
So Christ 'is King of kings and Lord of lords,' Rev. 19:16. And the 'Prince of
the kings of the earth,' chap. 1:5. Out of his mouth goeth a sharp sword,
with which he shall smite the nations, and he shall rule them with a rod of iron;
as the vessel of a potter, shall they be dashed in pieces, who do not obey Him,
the King of kings and Lord of lords.
This is Christ, who said, 'I am Alpha and Omega, the Beginning and the Ending,
the First and the Last;' so he is over all nations, and above them all.
We must understand this rod of iron, by which Christ rules the nations,
is a figurative speech of Christ, who is ascended into heaven,
and is at the right hand of God.
All power in heaven and in earth is given unto him,
and all things were created by him and for him; so then they are Christ's,
and he hath power over all things, for all are his.
So, as the Scripture saith, 'By me kings reign,
and princes decree justice,' Prov. 8:15. But if they abuse his power,
and do not do justice, as is decreed by Christ, the King of kings and Lord of lords,
the First and the Last, they must feel and know the weight of his rod of iron,
by which he will rule such as abuse his power.
That is decreed by Him, who hath all power in heaven and in earth given to him,
and rules in the kingdoms of men.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston, the 11th Month, 1687.

Several other things I wrote while at Kingston;
for my spirit being continually exercised towards God,
I had many precious openings of divine matters; and divers portions of Scripture,
both in the Old Testament and in the New, relating to a state of regeneration,
and sanctification, etc, were brought to my remembrance by the Holy Spirit;
some of which I committed to writing, as follows:--

"`They that touched the dead were unclean,
and were to be cleansed by the water of purification, Num.
xix. And they who touch the dead doctrines or faiths, and let them in, burden the pure,
defile, and make themselves unclean, until the spring of the water of the Word do arise,
and wash and cleanse them; for all the dead in Adam in the fall are unclean,
and they must be washed by Christ, in his blood, and water of life,
who quickens and makes alive.`"

"`A dwarf might not come near to offer upon God's altar;
but he might eat of the holy bread, that he might grow, Lev. 21:20, etc.
So the new-born babes may eat of the milk of the Word,
that they may grow thereby and increase.
He that had any blemish might not come near to offer upon God's altar;
neither might anything be offered upon God's altar that had any blemish, or was unclean,
Lev. 21.
And it is said, 'The ungodly shall not stand in the judgment,
nor sinners in the congregation of the righteous,' Ps. 1:5. But
'God standeth in the congregation of the mighty,'`" Ps. 82:1.

"`The camp of God was to be kept clean and holy.
That which was unclean, or defiled, was to be kept out of God's camp in the Old Testament.
And in the New Testament all that is defiled and
unclean must be kept out of God's kingdom,
the new and heavenly Jerusalem, that is from above.
All was to pass through the fire (even of those things that would bear the fire),
and to be purified by fire and water, before the people might come into God's camp, Num. 31.
So all must be circumcised and baptized with the Holy Ghost and with fire,
and be cleansed with the blood of Christ, and washed with the water of the Word,
before they come into the kingdom of God, and into heavenly Jerusalem.`"

"`The apostle Paul says,
'We know that if our earthly house of this tabernacle were dissolved,
we have a building of God, a house not made with hands, eternal in the heavens.
For in this we groan, earnestly desiring to be clothed upon with our house,
which is from heaven,
that mortality might be swallowed up of life,' 2 Cor. 5:1,2,4. Here is (we in
the earthly house of this tabernacle) which (we) are they that have received Christ,
and are become the sons of God, new creatures, and children of the light,
that believe in Christ's light; who have an eternal house in the heavens,
where mortality is swallowed up of life,
in which house from heaven they will not groan.`"

"`Peter said, 'I think it meet, as long as I am in this tabernacle,
to stir you up by putting you in remembrance,
knowing that shortly I must put off this my tabernacle,
even as our Lord Jesus Christ hath showed me,' 2 Pet. 1:13-14.
So Peter knew he must put off this tabernacle shortly;
but as long as he was in it he stirred up the saints to their duty in holiness,
that they might remember it after he was deceased.`"

"`The apostle Paul says, 'The first man is of the earth, earthly' (mark, earthly),
1 Cor. 15:47. 'And as we have borne the image of the earthly,
we shall also bear the image of the heavenly' (mark, the heavenly), ver. 69.
And, 'We have this treasure in earthen vessels,' etc.,
2 Cor. 4:7. 'And I live,' said he, 'yet not I,
but Christ liveth in me,' Gal. 2:20, who is the life of all God's people.`"

"`Christ said to the Jews, 'That the dead are raised, even Moses showed at the bush,
when he calleth the Lord the God of Abraham, and the God of Isaac, and the God of Jacob:
for he is not the God of the dead, but of the living;
for all live unto him,' Luke 20:37-38. So, 'None of us liveth to himself,
and no man dieth to himself; for whether we live, we live unto the Lord;
and whether we die, we die unto the Lord.
Whether we live, therefore, or die, we are the Lord's. For to this end Christ both died,
and rose, and revived,
that he might be Lord both of the dead and
living,' Rom. 14:7-9. For all died in Adam;
and Christ, by the grace of God, tasted death for every man,
that they might come out of the death in Adam, to the eternal life in Jesus Christ.
Who is also a quickening Spirit; for as in Adam all died,
even so in Christ shall all be made alive.
So Christ that died and rose again is Lord both of the living and of the dead:
for the living live to the Lord, and die in him, and are blessed.`"

"`All Christendom say they believe in God and in Christ,
and that they believe Moses and the prophets, and preach Christ, Moses, and the prophets:
so their words and writings are preached and printed; and ye say ye believe them.
But what life do ye live?
Are ye through the law dead to the law, that ye may live unto God?
Are ye crucified with Christ?
and doth Christ live in you?
Is the life that ye now live in the flesh by the faith of the Son of God;
and ye do not live, but Christ liveth in you, who gave himself for you?
Is this your present life?
for the just live by the faith which Christ is the author and finisher of: by which holy,
divine, and precious faith they have victory over that which is vile, unholy,
and not divine; and in this faith they please God, and have access to God and his Son,
who fulfilleth the law and the prophets.
For the law and the prophets were until John;
and since that the kingdom of God hath been preached, and men press into it:
and the least in the kingdom of God is greater than John,
though he was the greatest prophet born of a woman.
See whether ye are in the kingdom that stands in peace, and righteousness,
and joy in the Holy Ghost, or not.
Christ, 'who is the image of the invisible God, the firstborn of every creature,
was before any creature;
for by him were all things created that are in heaven and that are in earth,
visible or invisible, whether they be thrones or dominions, principalities or powers,
all things were created by him and for him; he was before all things,
and by him all things consist: and he is the head of the body, the church,
who is the beginning, the firstborn from the dead.'
So here ye may see that all things were made by Christ Jesus, and created for him,
and by him all things consist and have their being, who is the firstborn from the dead,
and dieth no more.
It pleased the Father that in him all fulness should dwell;
and by Christ to reconcile all things unto himself, whether they be things in heaven,
or things in the earth.
'In him are hid all the treasures of wisdom and knowledge,'
who is the head of all principality and power;
for 'all power in heaven and in earth is given to him,' the first-born of every creature,
and the firstborn from the dead, who liveth for evermore in his power over all;
the Lamb slain from the foundation of the world.
While the world's spirit rules in men's hearts, they do not know Christ,
nor the beginning nor ending of the work of God.
Christ was outwardly crucified and slain without
the gates of Jerusalem by the disobedient Jews;
and they that hate the light of Christ, disobey his gospel, quench his Spirit,
and are erred from his faith, crucify to themselves Christ afresh.'
So Adam and Eve, and their children that disobeyed God, did slay the Lamb;
and the blind Jews, that disobeyed God, crucified Christ Jesus;
and the outward Christians, that live and walk not in Christ, but in sin and evil,
though they make an outward profession of Christ,
yet crucify to themselves Christ afresh.
But as to Christ himself, he is 'ascended far above all principalities, thrones, powers,
and dominions,' so that they cannot put him to
death or crucify him any more as to himself:
but what the killers, crucifiers, and persecutors do now upon the earth,
is against Christ, as in themselves, and in his members; as Christ said to Saul,
'Why persecutest thou me,' Acts 9:4. For what is done
to his members Christ takes as done to himself,
Matt. 25:40,45. And they that did not visit Christ,
but persecuted him in his members, persecuted Christ in themselves first.`"

"`The serpent, that enemy to man and woman, the destroyer,
the god of the world and prince of the air, that ruleth in the hearts of the disobedient,
got in by disobedience.
But Christ bruises his head, breaks his power to pieces,
and destroys the devil and his works; and through death destroys death, and the devil,
the power of death.
So Christ, the light and life, hath all power in heaven and in earth,
and openeth the prison doors, and the eyes of the blind,
and takes captive him that hath led into captivity, and gives gifts unto men.
So Christ binds the strong man of sin, spoils his goods, and casts him out; hallelujah!
For the strong mail of sin is the god of the world, and his house is the whole world,
that lieth in wickedness.
And this god of the world hath kept his house, and his goods have been in peace,
until a stronger than he comes and binds and casts him out;
and then destroys him and his goods.
So Christ, the Son of God, who is stronger than the devil,
having destroyed the devil and his works, setteth up his own house.
All the believers in the light are the children of light,
are of the Son of God's spiritual house,
and the Son of God is over his house for evermore: glory to God in the highest,
through Jesus Christ. Amen.`"

"`God spoke by the mouth of all his holy prophets concerning Christ Jesus, his Son,
the Holy One: so they were holy men, and not unholy, that God spoke by.
Therefore all that name the name of the Lord Jesus Christ are to depart from iniquity.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston-upon-Thames, the 11th Month, 1687.
