== Chapter XIV.

[.chapter-synopsis]
* 1687-1690.
* George Fox continues to have service in London and the neighbourhood
* writes a paper respecting the gospel and the seed; being also an incentive to diligence
* a general epistle to Friends, forewarning them of an approaching storm
* Moses and Christ both faithful under their respective dispensations
* Christ is on his throne
* George Fox's health declining, he visits William Mead again for a few weeks
* the world's teachers, and the emptiness of their teaching
* those who turn people from the inward manifestation of Christ in the heart, remove them from the heavenly landmark, and bring a curse on themselves
* the prophets, apostles, and holy men of old, were husbandmen and tradesmen, unlike the world's teachers
* the vanity of being too much busied with, and spending the time in, hearing and telling news
* though still declining, George Fox attends at the Parliament-house many days on behalf of his Friends
* writes to Peter Hendricks, and to Friends at Dantzic, to strengthen and comfort them under their sufferings
* to the magistrates and priests of Dantzic, showing the evil of persecution, and persuading to Christian moderation
* an appendix to the Yearly Meeting's epistle
* an epistle to the Northern Yearly Meeting, to be held at York
* George Fox's health still impaired
* writes an epistle to Friends in Barbadoes
* to Friends in Pennsylvania and other parts of America
* to all that profess the Truth of God; being a warning to the young against the world's fashions, and to the old against going into the earthly things
* Christ is the "`Ensign,`" prophesied of by Isaiah
* an appendix to the Yearly Meeting's epistle
* an epistle to Friends in the ministry
* to Friends in the ministry gone to America
* to suffering Friends in Ireland
* death of George Fox in 1690
* epistle written with his hand and found scaled up
* some account of the interment.

I returned to London towards the latter end of the eleventh month, 1687,
visiting Friends in the way at Chiswick, and at Hammersmith, where I had two meetings,
one on a First-day, the other upon the occasion of a marriage there,
at which were many people of other denominations,
amongst whom I had a very seasonable opportunity of opening the way of truth.

Being come to London, I visited Friends`' meetings in and about the city,
as the Lord led me,
in whose service I continued labouring in the city until the middle of the first month,
1687-8. At which time I went down towards Enfield,
and visited Friends there and thereabouts, and at Babnet, Waltham Abbey,
and other places, where I had many meetings, and very good service;
in which I spent several weeks.
I then returned to London, where I continued labouring in the work of the gospel,
till after the Yearly Meeting,
which this year was about the beginning of the fourth month.
A precious meeting it was; and a very refreshing season Friends had together,
the Lord vouchsafing to honour our assemblies with his
living and glorious presence in a very plentiful manner.
At the conclusion of the meeting I felt a concern upon
my spirit to give forth the following paper,
to be dispersed amongst Friends:--

[.small-break]
'''

"`All you believers in the light, that are become children of the light,
walk as children of the light, and of the day of Christ; as a city set on a hill,
that cannot be hid.
Let your light shine, that people may see your good works, and glorify your Father,
which is in heaven.
For a good tree bringeth forth good fruit; therefore be ye trees of righteousness,
the planting of the Lord, having fruits unto holiness;
and then your end will be everlasting life.
Such are the wells and cisterns, that hold the living water,
which springs up in them to eternal life.
Ye may all drink water out of your own cisterns, running water out of your own wells;
and eat every one of his own fig-tree, and of his own vine:
having salt every one in yourselves, to season every one's sacrifice,
acceptable to God by Jesus Christ; and like unto the wise virgins,
that have oil in their lamps, follow the Lamb, and enter in with the bridegroom.
Now is the time to labour, while it is day (yea, the day of Christ),
to stir up every one's pure mind, and the gift of God that is in them;
and to improve your talents, that Christ hath bestowed upon you, that ye may profit;
and to walk every one according to the measure that Christ hath given you;
for '`the manifestation of the Spirit of God is given to every one to profit withal.`'

"`Consider what you have profited in spiritual and heavenly things,
with the heavenly Spirit of God.
Be not like the wicked and slothful, that hid his talent, from whom it was taken,
and he cast into utter darkness.
A dwarf, or one that had any blemish, was not to come nigh to offer upon God's altar;
therefore mind the word of wisdom,
to keep you out of that which will corrupt and blemish you;
and that ye may grow in grace, and in faith,
and in the knowledge of our Lord Jesus Christ: and feeding upon the milk of the word,
may grow by it, that ye may not be dwarfs;
and so offer your spiritual sacrifice upon God's holy altar.
For the field or vineyard of the slothful grows over with thorns and nettles,
and his walls go down.
Such are they that are not diligent in the Spirit of God, and the power,
which is the wall, a sure fence.
The Spirit of God will weed all thorns, thistles, and nettles,
out of the vineyard of the heart.
And you, that are keepers of others`' vineyards,
see that you keep your own vineyard clean with the Spirit and power of Christ.
Sanctify yourselves, and sanctify the Lord in your hearts,
that ye may be a holy people to the Lord, who saith, '`Be ye holy,
for I am holy:`' that ye may be the holy members of the church of Christ,
that is clothed with the sun, and hath the moon under her feet;
the changeable world with all her changeable worships, religions, churches, and teachers.
Be ye new and heavenly Jerusalem's children: for new and heavenly Jerusalem,
that is above, is the mother of all the children of light,
and that are born of the Spirit.
These are they that have been persecuted, and have suffered by the false church,
mystery Babylon, the mother of harlots.

"`And now, all heavenly Jerusalem's and Sion's children, that are from above,
labour in the gospel, the power of God, and the Seed, in which all nations,
and all the families of the earth are blessed: which Seed, Christ,
bruises the serpent's head, and destroys the devil and his works,
and overcomes the whore, the false church, the beast, and the false prophet.
He takes away the curse, and the veil that is spread over all nations,
and over all the families of the earth;
and brings the blessing upon all (if they will receive it) saying,
'`In thy seed shall all nations and all the families of the earth be blessed.`'
This is the gospel of God preached to Abraham, before Moses wrote his five books,
and was preached in the apostles`' days, and is now preached again;
which brings life and immortality to light; and is the gospel of peace, life,
and salvation, to every one that believes it.
So all nations, and all the families of the earth, must be in Christ, the Seed,
if they be blessed, and be partakers of the blessing in the Seed.

"`This gospel was revealed by Christ unto his apostles, who preached it;
which is not of man, nor from man.
Now, God and Christ hath revealed the same gospel unto me,
and many others in this age (I say, the gospel and the Seed,
in which all nations and families of the earth are blessed);
in which gospel I have laboured, and do labour, that all may come into this blessed Seed,
Christ, who bruises the head of the serpent, that in it they might have peace with God.
This everlasting gospel is preached again to them, that dwell upon the earth;
and they that believe it, and receive it, receive the blessing, the peace, joy,
and comfort of it; and the stability in it, and the life and immortality,
which it brings to light in them and to them.
Such can praise the everlasting God in his everlasting gospel.

"`And Friends, all seek the peace and good of all in Christ: for truth makes no Cains,
Korahs, Balaams, nor Judases;
for they come to be such that go out of the peaceable truth.
Therefore walk in the peaceable truth, and speak the truth in the love of it,
as it is in Jesus.`"

[.signed-section-signature]
G+++.+++ F.

Some time after the Yearly Meeting, I went to my son Mead's house, in Essex,
and abode there some weeks; often visiting Friends`' meetings near,
and sometimes at Barking.
After I had been a while there, I went to visit Friends at Waltham Abbey, Hoddesdon,
Enfield, South Street, Ford Green, and Winchmore Hill;
where I had several very serviceable meetings,
the Lord opening many deep and weighty things through me,
for informing the understandings of inquirers,
building up those that were gathered into the truth, and establishing them therein.

In the 7th month I returned to London,
having been near three months in the country for my health's sake,
which was very much impaired;
so that I was hardly able to stay in a meeting the whole time;
and often after a meeting had to lie down on a bed.
Yet did not my weakness of body take me off from the service of the Lord,
but I continued to labour in and out of meetings, in his work,
as he gave me opportunity and ability.

I had not been long in London before a great weight came upon me,
and a sight the Lord gave me of the great bustles and troubles, revolution and change,
which soon after came to pass.
In the sense whereof, and in the movings of the Spirit of the Lord,
I wrote "`A general epistle to Friends, to forewarn them of the approaching storm,
that they might all retire to the Lord, in whom safety is;`" as follows:--

[.small-break]
'''

"`My dear Friends and brethren everywhere, who have received the Lord Jesus Christ,
and to whom he has given power to become his sons and daughters;
in Him ye have life and peace, and in his everlasting kingdom,
that is established and cannot be shaken, but is over all the world,
and stands in his power, and in righteousness, and joy in the Holy Ghost,
into which no unrighteousness, nor the foul,
unclean spirit of the devil in his instruments can enter.
Therefore, dear Friends and brethren, every one in the faith of Jesus,
stand in His power, who has all power in heaven and in earth given to him,
and will '`rule the nations with his rod of iron, and dash them to pieces,
like a potter's vessel,`' that are not subject and obedient to his power;
whose voice will shake the heavens and the earth,
that that which may be shaken may be removed, and that which cannot be shaken may appear.
Stand in Him; and all things shall work together for good to them that love him;

"`And now, dear Friends and brethren, though these waves, and storms, and tempests,
be in the world, yet you may all appear the harmless and innocent lambs of Christ,
walking in his peaceable truth, keeping in the Word of power, wisdom, and patience;
and this Word will keep you in the day of trials and temptations,
that will come upon the whole world, to try them that dwell upon the earth.
For the Word of God was before the world, and all things were made by it;
it is a tried Word, which gave all God's people in all ages wisdom, power, and patience.
Therefore let your dwelling and walking be in Christ Jesus,
who is called the Word of God; and in his power, which is over all.
Set your affections on things that are above,
where Christ sits at the right hand of God (mark), on those things which are above,
where Christ sits; not on those things that are below, which will change, and pass away.
Blessed be the Lord God,
who by his eternal arm and power hath gathered a people to himself;
and hath preserved his, faithful to himself through many troubles, trials,
and temptations; his power and Seed, Christ, is over all,
and in Him ye have life and peace with God.
Therefore in Him all stand, and see your salvation, who is the First and Last, the Amen.
God Almighty preserve and keep you all in Him, your ark and sanctuary;
in Him you are safe over all floods, storms, and tempests; for He was before they were,
and will be when they are all gone.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 17th of the 8th Month, 1688.

About this time great exercise and weights came upon me (as had
usually done before the great revolutions and changes of government),
and my strength departed from me; so that I reeled, and was ready to fall,
as I went along the streets.
At length I could not go abroad at all, I was so weak, for some time,
till I felt the power of the Lord to spring over all,
and had received an assurance from him,
that he would preserve his faithful people to himself through all.

In the time that I kept within, I wrote a paper, showing, how
"`Moses, as a servant, was faithful in all his house, in the Old Testament; and Christ,
as a Son, is over his house, in the New Testament.`"

[.small-break]
'''

"`The house of Israel was called God's Vineyard, in Isa. 5:7,
and all the Israelites were called the house of Israel.
Israel signifies '`a prince with God,
and a prevailer with men,`' Gen. 32:28. When
Peter preached Christ to the house of Israel,
he said, '`Let all the house of Israel know assuredly, that God hath made the same Jesus,
whom ye have crucified,
both Lord and Christ,`' Acts 2:36.
So they were all called the house of Israel.
And it is said, '`Moses was faithful in all his house (to wit, this house of Israel),
as a servant, for a testimony of those things which were to be spoken after; but Christ,
as a son, over his own house, which house are we, if we hold fast the confidence,
and the rejoicing of the hope firm unto the end,`' Heb. 3:5-6. Here it is manifest,
that Moses was faithful in all his house, as a servant, viz., in the house of Israel,
in the Old Testament; but Christ Jesus, the Son of God,
is over his house in his New Testament and Covenant;
and all his true believers are of his house.
The apostle tells the Ephesians (who were the church of Christ),
'`They were fellow-citizens with the saints,
and of the household of God,`' Eph. 2:19. And the saints
are called '`the household of faith,`' Gal. 6:10. Peter in
his general epistle tells the church of Christ,
they were '`a chosen generation, a royal priesthood, a holy nation,
a peculiar people,`' 1 Pet. 2:9. And that as lively stones,
they were built up '`a spiritual house, an holy priesthood,
to offer up spiritual sacrifices, acceptable to God by Jesus Christ,`' ver. 5.
The apostle says to the church of Christ at Corinth,
'`If our earthly house of this tabernacle were dissolved, we have a building of God,
a house not made with hands,
eternal in the heavens,`' 2 Cor. 5:1. And Christ said to his disciples,
'`Let not your hearts be troubled; ye believe in God, believe also in me.
In my Father's house are many mansions (a mansion is a dwelling, or abiding place);
if it were not so, I would have told you; I go to prepare a place for you.
And if I go and prepare a place for you, I will come again, and receive you unto myself,
that where I am, there ye may be also,`' John 14:1-3. The Psalmist saith,
'`Those that be planted in the house of the Lord, shall flourish in the courts of our God;
they shall bring forth fruit in old age;
they shall be fat and flourishing,`' Ps. 92:13-14. Again,
'`Holiness becomes thine house, O Lord,
for ever,`' Ps. 93:5. Isaiah also said by way of prophecy,
'`It shall come to pass in the last days,
that the mountain of the Lord's house shall be established in the top of the mountains,
and shall be exalted above the hills,
and all nations shall flow unto it,`' Isa. 2:2. Is not that a great house?
Is not this mountain, Christ, who is over his house in the New Testament and New Covenant?
To this mountain and house all the children of the New
Testament and New Covenant flow in these latter days,
so that it is come to pass, which was prophesied of by Isaiah; for he said,
'`Many people shall go and say, Come ye, and let us go up to the mountain of the Lord,
to the house of the God of Jacob, and he will teach us of his ways,
and we will walk in his paths; for out of Zion shall go forth the law,
and the word of the Lord from Jerusalem.
And he shall judge among the nations, and shall rebuke many people;
and they shall beat their swords into ploughshares, and their spears into pruning-hooks;
nation shall not lift up sword against nation, neither shall they learn war any more.
O house of Jacob, come ye, and let us walk in the light of the Lord, ver.
3-5. Here ye may see, they that come to the mountain of the house of God,
and to God's teaching, must walk in the light of the Lord; yea, the house of Jacob.
Jacob signifies a supplanter; he supplanted profane Esau, who is hated,
and Jacob is loved.
Now these two births must be known within; and they that walk in the light of the Lord,
and come to Christ, the mountain of the house of the Lord,
established above all mountains and hills, break their swords into ploughshares,
and their spears into pruning-hooks; and in Christ, this mountain and house of the Lord,
there are no spears, nor swords to hurt one another withal.
Christ, the Son of God, is over his house and great family, the children of the light,
that believe in it, and walk in it, the children of the day of Christ,
his holy and royal priesthood, that offer up spiritual sacrifice to God by him.
All such are of Christ's (the spiritual man's) house, who are born of God,
and led by his Spirit; they are of the Lord of lords,
and King of kings`' house and family, which he is over;
and are of the household of the holy, divine, pure, and precious faith,
which Christ is the author and finisher of.
And they that are of the Son's house, are pure, righteous, and holy,
and can do nothing against the truth, but for it, in their words, lives,
and conversations; and so are a chosen generation, a holy nation, a peculiar people,
that they should show forth the praise of Him,
who hath called them out of darkness into his marvellous light.
These are Christ's lively stones, that build up a spiritual house, which He (Christ,
the spiritual man, the King; of kings, and Lord of lords) is over.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 10th Month, 1688.

Some time after this, my body continuing weak,
I went down with my son Mead to his house in Essex, where I stayed some weeks.
In which time I wrote many things relating to the service of truth,
of which somewhere printed soon after, others were spread abroad in manuscript;
and amongst other things, a few lines to this purpose:--

"`That while men are contending for thrones here below, Christ is on his throne,
and all his holy angels are about him; who is the Beginning and the Ending,
the First and the Last, over all.
And that the Lord will make way and room for himself,
and for them that are born of his Spirit, who are heavenly Jerusalem's children,
to come home to their free mother.`"

[.offset]
A few words also I wrote concerning the world's teachers,
and the emptiness of their teaching.
Which were thus:--

"`Doth not all that, which is called Christendom, live in talking of Christ's,
and of the apostles`' and prophets`' words, and the letter of the Scriptures?
And do not their priests minister the letter, with their own conceptions thereupon,
for money, though the Holy Scriptures were freely given forth from God and Christ,
and his prophets and apostles?
Yet the apostle says, '`The letter killeth;
but the Spirit giveth life,`' 2 Cor. 3:6. The ministers of
the New Testament are not ministers of the letter,
but of the Spirit; and they sow to the Spirit, and of the Spirit reap life eternal.
But people spending time about old authors, and talking of them,
and of the outward letter, this doth not feed their souls.
For talking of victuals and clothes, doth not clothe the body, nor feed it.
No more are their souls and spirits fed and clothed,
except they have the bread and water of life from heaven to feed them,
and the righteousness of Christ to clothe them.
Talking of outward things and spiritual things, and not having them,
may starve both their bodies and their souls.
Therefore, quench not the Spirit of God, which will lead to be diligent in all things.`"

[.offset]
With this I wrote another short paper, showing the hurt they did,
and the danger they run into,
who turned people from the inward manifestation of Christ in the heart:--

"`The Jews were commanded by the law of God,
'`Not to remove the outward land-mark,`' Duet. 19:14. They that did so,
or that caused the blind to wander, were cursed in the Old Covenant,
Duet. 27:17. In the New Covenant the apostle saith, '`Let him be accursed,
that preacheth any other gospel than that which he had preached,`' Gal. 1:8.
Now the gospel that he preached,
was '`The power of God unto salvation,
to everyone that believeth,`' Rom. 1:16. And
the gospel that was preached to Abraham was,
'`That in his seed all nations, and all the families of the earth should be blessed.`'
And in order to bring men to this blessed state,
God poureth out of his Spirit upon all flesh;
and Christ doth enlighten every one that cometh into the world; and the grace of God,
which bringeth salvation, hath appeared unto all men, and teacheth Christians,
the true believers in Christ; and God doth write his law in the true Christians`' hearts,
and putteth it in their minds, that they may '`all know the Lord,
from the greatest to the least;`' and he giveth his word in their hearts to obey and do,
and the anointing within them; so that they need not any man to teach them,
but as the anointing doth teach them.
Now all such as turn people from the Light, Spirit, Grace, Word, and Anointing within,
remove them from their heavenly landmark of their eternal inheritance,
and make them blind;
and cause the blind to wander from the living way to their eternal house in the heavens,
and from the new and heavenly Jerusalem.
So they are cursed, that cause the blind to wander out of their way,
and to remove them from their heavenly landmark.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
I wrote also a paper to show, by instances from the Scriptures,
that "`many of the holy men and prophets of God, and of the apostles of Christ,
were husbandmen and tradesmen;`" by which people might see how unlike to
them the world's teachers now are:--

"`Righteous Abel was a shepherd, '`a keeper of sheep,`' Gen. 4:2.
Noah was a husbandman; and he was a '`just man,
and perfect in his generation, and walked with God,`' Gen. 9:20; 6:9.
Abraham, the father of the faithful,
was a husbandman, and had great flocks of cattle;
and just Lot was a husbandman, and had great flocks and herds, Gen. 13.
Isaac also was a husbandman, and had great '`flocks and herds of cattle,
and great store of corn,`' Gen. 26:12,14. And the promise was with Isaac;
for the Lord said to Abraham,
'`In Isaac shall thy seed be called,`' Gen. 21:12. Jacob was a husbandman,
and his sons '`keepers of flocks of cattle,`' Gen. 66:32,34, and God loved Jacob.
Moses kept sheep, Ex. 3:1, and the Lord spake to him when he was keeping sheep, ver.
4, and sent him to Pharaoh, to bring God's people, or sheep, out of Egypt.
And by the hand and power of the Lord,
he and Aaron his brother brought them out of Egypt,
a land of anguish, bondage, darkness, and perplexity.
And Moses kept the Lord's people, or sheep, forty years in the wilderness;
a meek shepherd of God he was, and kept his great flock of sheep;
though some of them were scabbed with the leprosy of contention and murmuring,
and were destroyed in the wilderness.

"`David (though he afterwards came to be a king) was a
keeper of his father's sheep in the wilderness,
1 Sam. 17:15,28. And the Lord God called him from the sheepcotes to feed his sheep,
the house of Israel, and to defend them from the spiritual wolves, bears, and lions;
and he did it to purpose, who was a man after God's own heart.

"`Elisha was a ploughman, 1 Kings 19:19. He was called from the plough,
to teach God's people, the children of Israel,
to plough up the fallow ground of their hearts,
that they might bring forth seed and fruits to God, their Creator.

"`The word of the Lord came to Amos,
when he was among the herdsmen of Tekoa, Amos 1:1.
And Amaziah, the priest of Bethel, said to Amos,
'`Prophesy not again any more at Bethel; for it is the king's chapel,
and it is the king's court,`' chap. 7:13.
Then answered Amos, and said to Amaziah,
'`I was no prophet, neither was I a prophet's son; but I was a herdsman,
and a gatherer of sycamore-fruit; and the Lord took me, as I followed the flock.
And the Lord said unto me, Go, prophesy unto my people Israel,`' ver. 14,15.
Here ye may see, how the Lord made use of a poor man,
and how he called him from following the outward flock,
and from gathering outward fruits, to gather his fruits,
and to follow his people or flock, the children of Israel.

"`Christ called Peter and Andrew his brother, when they were fishing,
and casting their net into the sea (for they were fishers); '`and he said unto them,
Follow me, and I will make you fishers of men,`' Matt. 4:18-19.
Christ likewise called James and John his brother,
when they were '`in a ship, with Zebedee, their father, mending their nets;
and they immediately left the ship, and their father, and followed him,`' ver.
21, 22. He gave them power (a net that will hold, and not want mending),
and made them fishers of men,
to fish them out of the great sea, the world of wickedness.
We read, that when Peter, Thomas, Nathanael, the sons of Zebedee, and other disciples,
went a fishing together, and that night caught nothing,
in the morning Jesus appeared to them and said,
'`Cast the net on the right side of the ship, and ye shall find;`' and they did so,
and caught so great a multitude, that they were not able to draw them to shore.
When thereupon one of the other disciples said unto Peter,
'`It is the Lord,`' Peter hearing that it was the Lord,
'`girded his fisher's coat unto him,`' John 21:2-7. This was after Christ was risen.
So here ye may see,
Peter had not laid aside his fisher's coat all the
while that he had been preaching before Christ's

"`Jesus saw Matthew sitting at the receipt of custom, and he said unto him, Follow me;
and he arose and followed him,`' Matt. 9:9.
And Christ employed Matthew to gather his people,
that were scattered from God;
another manner of treasure than the outward custom of the Romans.
Luke was a physician, whom Christ made a physician spiritual;
which was better than outward.

"`Paul was a tent-maker; and being one of the same craft with Aquila and Priscilla,
he abode with them at Corinth,
and wrought (for by their occupation they were tent-makers), Acts 18:3.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 1st Month, 1688-9.

[.offset]
It was now a time of much talk;
and people busied their minds and spent their time too much in hearing and telling news.
To show them the vanity thereof, and to draw them from it, I wrote the following lines:--

"`In the low region, in the airy life, all news is uncertain; there nothing is stable;
but in the higher region, in the kingdom of Christ, there all things are stable and sure,
and the news always good and certain.
For Christ, who hath all power in heaven and in earth given unto him,
ruleth in the kingdoms of men; and he, who doth inherit the heathen,
and possess the utmost parts of the earth with his divine power and light,
rules all nations with his rod of iron, and dashes them to pieces like a potter's vessel,
the vessels of dishonour, and the leaky vessels, that will not hold his living water;
and he doth preserve his elect vessels of mercy and honour.
His power is certain, and changes not, by which he removes the mountains and hills,
and shakes the heavens and the earth.
Leaky, dishonourable vessels, the hills and mountains, and the old heavens and the earth,
are all to be shaken, and removed, and broken to pieces, though they do not see it,
nor him that doth it; but his elect and faithful both see it and know him, and his power,
that cannot be shaken, and which changeth not.`"
The 5th of the 1st Month, 1688-9.

[.signed-section-signature]
G+++.+++ F.

About the middle of the first month, 1688-9, I went to London,
the parliament then sitting, and engaged about the bill for indulgence.
Though I was weak in body, and not well able to stir about,
yet so great a concern was upon my spirit on behalf of truth and Friends,
that I attended continually for many days, with other Friends, at the parliament-house,
labouring with the members, that the thing might be done comprehensively and effectually.

In this, and other services, I continued till towards the end of the second month, when,
being much spent with continual labour,
I got out of town for a little while as far Southgate and thereabouts.
While I was there I wrote a letter to Peter Hendricks, a Friend at Amsterdam,
in which I enclosed an epistle to the Friends at Dantzic,
who at this time were under great persecution.
And as I wrote to encourage and strengthen them in their testimony,
and comfort them in their sufferings for the truth,
so also I wrote a paper to their persecutors, the magistrates of Dantzic,
laying before them the evil of persecution, and persuading them to Christian moderation,
and "`to do unto others in matters of religion as they would be done unto.`"
Which papers were as follows:--

[.blurb]
=== "`To Peter Hendricks at Amsterdam, and to Friends at Dantzic who are under persecution.

[.salutation]
"`Dear Friend P. H.

"`With my love to thee and thy wife, J. Claus, and J. Roeloffs,
and all the rest of Friends everywhere in Christ Jesus, who reigns over all.
I am glad to hear that Friends are well everywhere, except at Dantzic;
and that you were so diligent in spreading my papers to the strengthening of Friends.
I have lately printed the life of William Caton,
but have not made a collection of his books.
I think to send some of them to you, which you may translate and print, if you will;
they may be serviceable among Friends, especially them that knew him.^
footnote:[William Caton, whose service was much in Holland,
died at Amsterdam in 1665.
He was one of the earliest associates of George Fox,
being convinced by him in 1652,
and is often mentioned in the earlier part of this Journal.
He was not only a literary man, but zealous for religion;
and being of a courteous and affable disposition, was in general esteem.
When about fourteen years of age he went to
reside in Judge Fell's family at Swarthmore Hall,
as a companion for his son, sharing with him both in instruction and recreation.
He was very early inclined to religion, and, as he grew in years,
he advanced in godliness.
{footnote-paragraph-split}
After joining Friends,
he travelled considerably as a gospel minister,
and underwent many sufferings for Christ's sake.
At Maidstone, in 1654, he and another Friend were stripped,
their necks and arms put in the stocks, and, in that condition,
they were desperately whipped.
At Yarmouth he was, with seven other Friends,
taken from a religious meeting on the first day of the week,
and confined six mouths in prison.
{footnote-paragraph-split}
A valuable
collection of _Letters of Early Friends_ was met with at Swarthmore some years ago,
written nearly throughout by William Caton,
and appears to have been intended by him for publication.
It has a title page, dated Swarthmore, 23rd of 6th Month, 1659;
and a preface signed by himself, dated 7th of 2nd Month, 1660.
The life of Caton, George Fox mentions having been printed, was re-published in 1839,
by John Barclay, forming one of the _Select Series,_
to which the reader is referred for further particulars.]

"`Concerning the dear Friends at Dantzic,
whom the Lord hath supported by his eternal arm and power to this day;
I hope by the same arm and power he will support them,
and in it they will feel his blessed presence with them in all their sufferings;
who is over the cruelty of their persecutors,
who will hardly let them breathe outwardly or
inwardly in the common air of their native soil.
Which shows both their immorality, inhumanity, and unchristianity,
and that they want the counsel of a Gamaliel amongst them;
whose actions are below the law of God,
to '`do unto others as they would have others to do unto
them:`' God will not bless the doings of such.
I desire, however, that Friends may mind the Lord's power, that is over all;
be valiant for his truth, and keep upon their rock and foundation, Christ Jesus,
that stands sure in this time of the heat of persecution, which is so hot upon you,
that they will not suffer you to have so much as your houses to work and sleep in,
nor to meet, nor serve God in.
The Lord beholds all such actors and their actions.
Therefore look over all to Him,
who is able to deal with them and reward them according to their works.
God Almighty preserve you all in Christ Jesus, in whom you have rest, life, and peace.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Southgate, the 28th of the 2nd Mouth, 1680.

[.blurb]
=== "`To the Magistrates of Dantzic:--Christian Shroder, President of the Council, and Emanuel Dilger, N. Gadecken, and N. Fraterus, Deputies of the Council, and the rest of the Magistrates and Priests.

"`We have seen your order, and your breathing out persecution against that little flock,
the lambs of Christ, that live under your jurisdiction in the city of Dantzic;
and that you have imprisoned and banished two by
the hangman out of the government of your city;
and others you threatened to do the same to, with great punishment, if they return.
Likewise you threaten those with punishment they rent their houses of,
if they let them have them either to live in,
or meet in to serve and worship the Lord that made them.
Truly I am heartily sorry for both your magistrates and priests,
that go under the name of Christians, and show such immoral, inhuman,
and unchristian actions, below the royal law of God, which is,
to '`do to others as you would have them do unto you.`'
For would you think it was moral, human, or Christian, or according to the law of God,
if the king of Poland, who is of another religion than you,
should banish you out of your city by the hangman, and call you murderers of souls?
Could you say, but this was according to the law of God,
'`to do unto you as you have done unto others?`'
But if you say that you have the sword, the horn, and the power;
blessed be the Lord that hath shortened your sword, your power, and your horn,
that it reaches no further than your jurisdiction at Dantzic;
and you do not know how long God may suffer you to have your horn, your power,
and your sword.
We are sure you have not the mind nor the Spirit of Christ; and the apostle saith,
'`They that have not the Spirit of Christ are none of his,`' Rom. 8.
And Christ bids Peter '`put up his sword:`' they that draw the sword concerning him,
to defend him and his worship and faith, should perish with the sword.
Peter and the apostles never drew the outward sword after;
but said their weapons were spiritual, not carnal;
and they did not wrestle with flesh and blood.
Christ never gave any such command,
that they should banish any by the hangmen that were not of their religion,
and would not receive it.
Are not you worse than the Turks, who let many religions be in their country, yea,
Christians, and to meet peaceably?
Yea, the Turkish patroons let our Friends that were captives meet together at Algiers,
and said, '`it was good so to do.`'
You are worse than those barbarous people at Sallee who do not profess Christianity,
for you profess Christ in words, but in works deny him.
And did you ever find, either in Scripture or history,
that any persecutors prospered long?
You are worse than they are in the Mogul's country, who, they say,
permits sixty religions in his dominions: and many others might be mentioned,
all of whom you exceed in your cruelty and persecution of God's people,
only for meeting together in the name of Jesus, and serving and worshipping God,
their Creator.
No, they must not breathe their natural air, neither natural nor spiritual,
in your dominions.
I pray, where had you these commands from?
Neither from Christ nor his apostles.
Do not you profess the Scriptures of the New Testament to be your rule?
But, I pray you, what Scripture have you for this practice?
It is good for you to be humble, to do justly, and love mercy;
call home your banished ones, and love and cherish them: yea,
though they were your enemies, you are to obey the command of Christ, and love them.
I wonder how you and your wives and families can sleep quietly in your beds,
that do such cruel actions,
without thinking the '`Lord may do to you the
same!`' You cannot be without sense and feeling,
except you be given over to reprobation, and your consciences seared with a hot iron.
But Christian charity hopes that you are not all in that state;
but that there may be some relenting or consideration of your actions among some of you,
either according to the law of God, or his gospel.

"`From him that desires your temporal and eternal good and salvation, and not destruction.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Middlesex, the 28th of the 2nd Month, 1689.

"`Peter, thou mayest translate this into high Dutch, and send them; and you may print it,
if you will, and send it abroad;
and translate that part of the letter that is to Friends into high Dutch,
and send to them.`"

[.small-break]
'''

Having stayed in the country about three weeks,
I returned to London a little before the Yearly Meeting,
which was in the third month this year, and was a very solemn, weighty meeting; the Lord,
as formerly, visiting his people, and honouring the assembly with his glorious presence,
to the great satisfaction and comfort of Friends.
After the business was over,
it was upon me to add a few lines to the Epistle which went from the meeting to Friends,
after this manner:--

[.salutation]
"`Dear Friends And Brethren,`"

"`Who have known the Lord's eternal arm and power,
that hath preserved you upon the heavenly rock and foundation,
and hath built your house upon it; you have known many winds, tempests, and storms,
that have risen out of that sea where the beast rose;
and many raging storms that have risen by apostates of several sorts;
but the Seed that bruises the serpent's head, and is the foundation of God's people,
stands sure.
Dear Friends and brethren, though there be great shakings in the world,
the Lord's power is over all, and his kingdom cannot be shaken.
Therefore all ye children of God, children of the light, and heirs of his kingdom,
a joyful, peaceable habitation keep in;
keeping out of all the contentions and disputes about things below.
Lay hand on no man, nor nothing suddenly,
lest they should be puffed up with that which fades, and so come to loss:
but mind the Lord's power, that keeps open your heavenly eye,
to see things present and to come; and in that ye will see and handle the word of life.

"`Dear Friends everywhere, have power over your own spirits.
As God hath blessed you with his outward things, have a care of trusting in them,
or falling into difference one with another about these outward things that are below,
which will pass away.
But all live in the love of God, and in that live in peace with God, and one with another.
Follow the works of charity, and overcome evil with good to all;
for what good have all the tinklers done, with their cymbals and sounding brass?
They always bred confusion, and never did good in any age; tinkling with their cymbals,
and sounding with their brass, to draw out the simple to follow them.
Therefore, it is good for all the children of God to keep in their possession of life,
and in the love of God, that is everlasting.

"`As for all the tumults of the world, and the apostates from the truth,
the Lord's power is over them all, and Christ reigns; and the Lord saith,
'`No weapon that is formed against thee shall prosper,`' Isa. 54:17. Now, Friends,
you are not insensible how many weapons have been formed against us,
who are the sons and daughters of God;
and the Lord hath restrained them according to his promise; they have not prospered.
The Lord said, '`Every tongue that shall rise up in judgment against thee,
thou shalt condemn:`' so God hath given such a power to his children,
to condemn all the tongues that shall rise up in judgment against them,
and this is the heritage of the servants of the Lord; '`their righteousness is of me,
saith the Lord.`'
You are not insensible of the many tongues that have risen up against us in judgment,
yea, of apostates and profane.
But in and with the truth, the power of God, according to the promise of God,
'`Every tongue that riseth against thee, thou shalt condemn.`'
It is not one tongue only thou shalt condemn,
but '`every tongue that shall rise up in judgment against thee, thou shalt condemn.`'
The Lord giveth this power to his servants and children, to judge the evil tongues;
and he doth restrain the weapons formed against them,
so that they shall not prosper against his children that he hath begotten.
Praises and honour be to his holy name for ever! Amen.`"

[.signed-section-signature]
G+++.+++ F.

Soon after this, the Yearly Meeting began at York;
which because of the largeness of that county,
and for the conveniency of Friends in the northern parts,
had for some years been held there.
And inasmuch as there had been some hurt done in that place,
by some that were gone out of the unity of Friends,
it was upon me to write a few lines to that meeting,
"`to exhort them to keep in the pure, heavenly love, which brings into, and keeps in,
the true unity.`"
Which was thus:--

[.salutation]
"`Dear Friends And Brethren In Christ Jesus,`"

"`Whom the Lord by his eternal arm and power hath preserved to this day,
all walk in the power and Spirit of God, that is over all, in love and unity;
for love overcomes, builds up, and unites all the members of Christ to him the Head.
Love keeps out of all strife, and is of God.
Love, or charity, never fails, but keeps the mind above all outward things,
and strife about outward things.
It overcomes evil, and casts out all false fears.
It is of God, and unites all the hearts of his people together in the heavenly joy,
concord, and unity.
The God of love preserve you all, and establish you in Christ Jesus,
your life and salvation, in whom ye have all peace with God.
So walk in him, that ye may be ordered in his peaceable, heavenly wisdom,
to the glory of God, and the comfort one of another. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 27th of the 3rd Month, 1689.

Being much wearied and spent with many large meetings, and much business with Friends,
during the time of the Yearly Meeting, and finding my health much impaired thereby,
I went out of town with my daughter Rous, to their country-house near Kingston,
and tarried there most of the remaining part of the summer.
In which time I sometimes visited Friends at Kingston,
and wrote divers things for the service of truth and Friends.
One was an epistle to Friends in Barbadoes; as follows:--

[.blurb]
=== "`To all Friends in Barbadoes, that are convinced of God's truth.`'

"`My desires are that ye may live and walk in his peaceable truth,
and show forth that ye are children of the light and of the truth; for the heavenly,
gentle, and peaceable wisdom is justified of her children.
But debate, strife, wilfulness, and laying open one another's nakedness and weakness,
is not the practice of heavenly wisdom's children (but of Ham's),
nor from the Spirit of Christ; neither such as bite and tear one another;
that is from a devouring spirit, not from the Spirit of Jesus,
which covers that which is uncomely, and can forgive.
Now, my Friends, you profess that truth, which is beyond all the world's ways;
therefore see that you excel them in the heavenly, gentle wisdom,
that is easy to be entreated; for the wisdom of the world is not easy to be entreated;
and sometimes will not be entreated at all.
Pray see you excel the world in wisdom, in virtue, in kindness,
in love that is over hatred, in meekness and humility, in sobriety, civility,
and modesty, in temperance and patience, and in all morality and humanity,
which will not act anything below men or unmanly.
Show forth true Christianity,
and that ye are the converted and translated believers in Christ,
dwelling in the love of God, that beareth all things, endureth all things,
is not puffed up, and envies not.
For they that are out of this love of God and Christian charity, are nothing,
but as a tinkling cymbal and as sounding brass, and are discontented, murmurers,
and complainers, full of doubts, questions, and false jealousies.
Keep that spirit out of the camp of God; for do not you read in the Scriptures,
both of the New and Old Testament, that the end of such was misery?
Therefore, in the love of God, build up one another; for love edifies the body of Christ,
and he commands his believers to love enemies, and to love one another;
by this they are known to be the disciples of Christ.
But to live in envy, strife, and hatred, is a mark they are no disciples of Christ:
'`For he that loveth not his brother, abides in death; and whosoever hates his brother,
is a murderer: and ye know that no murderer hath eternal life abiding in him.
But they that love the brethren, are passed from death to life,`' 1 John 3:14-15. And,
'`If a man say, I love God, and hateth his brother, he is a liar:
for he that loveth not his brother whom he hath seen,
how can he love God whom he hath not seen?
And this commandment have we from God, that he who loveth God,
love his brother also,`' chap. 4:20-21. Therefore,
'`love one another;`' for love is of God, and hatred is of the devil;
and every one that loveth is born of God, and knows God.
All are children of God by creation;
therefore in that state they are to love their neighbours as themselves;
and to do unto all men as they would have them do unto them.
Secondly, God poureth his Spirit upon all flesh (or all men and women);
all that are led by the Spirit of God are the sons of God, heirs of God,
and joint-heirs with Christ; and are in fellowship in the everlasting gospel;
and in unity in the Spirit, the bond of peace.
They that go out of this unity, out of the bond of peace, and do not keep it,
break the King of kings`' peace; but they that keep in the unity,
and fellowship in the Spirit, and walk in the light, have fellowship one with another,
and with the Father and the Son.
It is not every one that talks of the light, of the word, of righteousness, of Christ,
and of God, but he that '`doeth the will of God.`'
Therefore, my Friends, strive to excel one another in love, in virtue,
in good life and conversation; and strive all to be of one mind, heart,
and judgment in the Spirit of God; for in Christ all are one, and are in peace with him.
The Lord God Almighty preserve you in him, your rock and foundation,
that is heavenly and stands sure; that ye may be valiant for the truth upon earth,
for the Lord and his glorious name; that ye may all serve him in your generation,
and in his new creation in Christ Jesus. Amen.

"`And now, that you are come into so much favour with the magistrates and powers,
that they let you serve the office of constable, etc.,
without swearing or taking any oaths, hereby Christ's doctrine and command,
and his apostle's is set up.
Therefore, I desire, that you may double your diligence in your offices,
in doing that which is just, and true, and righteous;
so that ye may excel and exceed all,
that are tied or bound by oaths to perform their offices;
and you can do it upon your Yea and Nay; so say, and so do;
according to Christ's doctrine and command.
For Adam and Eve, by disobeying the command of God, fell under condemnation;
and they that disobey the command of Christ, in taking oaths and swearing,
go into evil and fall into condemnation, Matt. 5; James 5.
My love in the Lord is to you all.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Kingston-upon-Thames, the 10th of the 5th Month, 1689.

I stayed at Kingston till the beginning of the seventh month,
where not only Friends came to visit me, but some considerable people of the world,
with whom I discoursed about the things of God.
Then leaving Kingston, I went to London by water, visiting Friends as I went,
and taking Hammersmith meeting in my way.
Having recovered some strength by being in the country, when I was come to London,
I went from meeting to meeting, labouring diligently in the work of the Lord,
and opening the divine mysteries of the heavenly things,
as God by his Spirit opened them in me.
But I found my body would not long bear the city; wherefore,
when I had travelled amongst Friends there about a month, I went to Tottenham-high-cross,
and thence to Edward Man's country-house near Winchmore-Hill, and to Enfield,
spending three weeks among Friends thereabouts; and had meetings at all those places.
Then, being a little refreshed with being in the country, I went back to London;
where I tarried, labouring in the work of the ministry,
till the middle of the ninth month;
at which time I went down with my son Mead to his house in Essex,
and abode there all the winter.
During which I stirred not much abroad, unless it were sometimes to the meeting,
to which that family belonged, which was about half a mile from thence;
but I had meetings often in the house with the family,
and those Friends that came thither.
Many things also I wrote, while I was there; some of which follow.
One was an epistle to the quarterly and yearly meetings of Friends in Pennsylvania,
New-England, Virginia, Maryland, the Jerseys, Carolina, and other plantations in America.
Which was thus:--

[.salutation]
"`Dear friends and brethren in the lord Jesus Christ,

"`Who, by believing in his light, are become children of his light and of his day;
my desires are, that you may all walk in the light and in the day,
and keep the feast of Christ, our passover, who is sacrificed for us,
not with old leaven, neither with the leaven of malice and wickedness;
but let all that be purged out, that ye may be a new lump,
keeping the feast of Christ our passover,
with the unleavened bread of sincerity and truth.
Let no leavened bread be found in your houses, nor in your meetings,
nor in the camp of God, or household of faith, which are the household of Christ;
but all that old leaven, which makes people's hearts sour, and bur n one against another,
must be purged out of the camp of God, and kept out.
For the feast of Christ, our passover, must be kept in the New Covenant,
with his heavenly, unleavened bread of life.
The Jews`' feast-in the Old Testament was kept with outward, unleavened bread; and now,
in the New Testament, in the gospel-day, our feast is to be kept with the heavenly,
unleavened bread of sincerity and truth.
Therefore, Friends, I desire you seriously to consider, and to keep this feast,
which the apostle directed the church of Christ to keep.
Do not you see Christendom, so called,
keep their feasts with the leavened bread of malice and wickedness?
which makes them so sour, and their hearts so burn one against another,
that they have destroyed, and do destroy one another about religion.
Therefore, all live in the love of God, which keeps above the love of the world;
so that none of your hearts may be choked or surfeited with these outward things,
or with the cares of the world, which will pass away;
but mind ye the world and the life that is without end, that ye may be heirs of it.
And Friends, you should strive to excel all, both professor and profane, in morality,
humanity, and Christianity, modesty, sobriety, and moderation, and in a good, godly,
righteous life and conversation, showing forth the fruits of the Spirit,
and that you are the children of the living God, children of the light, and of the day,
and not of the night.
And serve God in newness of life; for it is the life,
and a living and walking in the truth, that must answer the witness of God in all people;
that '`they, seeing your good works, may glorify our Father, which is in heaven.`'
Therefore be valiant for God's holy, pure truth, and spread it abroad,
among both professors and profane, and the Indians.
And you should write over once a year,
from all your yearly meetings to the yearly meeting here,
concerning your diligence in the truth, and of its spreading,
and of people's receiving it, both professors and profane, and the Indians;
and concerning the peace of the church of Christ amongst yourselves.
For, blessed be the Lord, truth gains ground in these parts,
and many are made very loving to Friends, and the Lord's power and seed is over all;
in which God Almighty keep all his people to his glory. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 28th of the 11th Month, 1689.

[.offset]
While I was in the city,
I had a concern upon my spirit with respect to a
twofold danger that attended some who professed truth:
one was of young people's running into the fashions of the world;
and the other was of old people's going into earthly things.
And that concern coming now again weightily upon me,
I was moved to give forth the following paper, as a reproof to such,
and an exhortation and warning to all Friends to beware of,
and keep out of those snares:--

[.blurb]
=== "`To all that profess the Truth of God.

"`My desires are, that you may walk in humility in it.
For when the Lord first called me forth, he let me see,
that young people grew up together in vanity and the fashions of the world;
and old people went downwards into the earth, raking it together;
and to both these I was to be a stranger.
And now, Friends, I see too many young people that profess the truth,
grow up into the fashions of the world, and too many parents indulge them;
and amongst the elder, some are going downwards, and raking after the earth.
Therefore take heed, that you are not making your graves, while you are alive outwardly,
and loading yourselves with thick clay (Hab. 2:6).
For if you have not power over the earthly spirit,
and that which leadeth into a vain mind, and the fashions of the world,
and into the earth, though you have often had the rain fall upon your fields,
you will but bring forth thistles, briars, and thorns, which are for the fire.
Such will become brittle, peevish, fretful spirits,
that will not abide the heavenly doctrine, the admonitions, exhortations,
and reproofs of the Holy Ghost, or heavenly Spirit of God;
which would bring you to be conformable to the death of Christ, and to his image,
that ye might have fellowship with him in his resurrection.
Therefore it is good for all to bow to the name of Jesus, their Saviour,
that all may confess him to the glory of God, the Father.
For I have had a concern upon me,
in a sense of the danger of young people's going into the fashions of the world,
and old people's going into earthly things,
and many going into a loose and false liberty,
till at last they go quite out into the spirit of the world, as some have done.
The house of such hath been built upon the sand on the sea-shore, not upon Christ,
the Rock, that they are so soon in the world again,
under a pretence of liberty of conscience.
But it is not a pure conscience, nor in the Spirit of God, nor in Christ Jesus;
for in the liberty in the Spirit there is the unity, which is the bond of peace;
and all are one in Christ Jesus, in whom is the true liberty:
and this is not of the world; for He is not of the world.
Therefore all are to stand fast in Him, as they have received Him;
for in Him there is peace, who is the Prince of Peace; but in the world there is trouble.
For the spirit of the world is a troublesome spirit;
but the Spirit of Christ is a peaceable Spirit;
in which God Almighty preserve all the faithful. Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 1st of the 2nd '`Month, 1690.

[.offset]
Another paper I wrote while I was here, "`concerning the Ensign,
which Isaiah prophesied the Lord should set up for the Gentiles,
which I showed was Christ.`"
Of which follows a copy:--

"`The Lord saith, '`They shall not hurt nor destroy in all my holy mountain;
for the earth shall be full of the knowledge of the Lord,
as the waters cover the sea,`' Isa. 11:9. '`
And in that day there shall be a root of Jesse,
which shall stand for an Ensign of the people; to it shall the Gentiles seek,
and his rest shall be glorious,`' ver. 10.
'`And he shall reign over the Gentiles,
and in him shall the Gentiles trust,`' Rom. 15:12.
This Ensign is Christ,
who was prophesied of by the prophet; which prophecy the apostle,
who was a minister to the Gentiles, showeth was fulfilled in the New Testament.
And in this day of Christ, Isaiah saith,
'`The Lord shall set his hand again the second time, to recover the remnant of his people,
which shall be left, from Assyria and from Egypt,`' etc.
And he shall set up an Ensign for the nations, and shall assemble the outcasts of Israel,
and gather together the dispersed of Judah from the four corners of the earth,`' ver.
11, 12. This is in the day of Christ, and his gospel of life and salvation,
which is preached to every creature under heaven;
who '`enlighteneth every man that cometh into the world,`' both Jews and Gentiles;
that by his heavenly, divine light, they may see Christ, their Ensign,
and Captain of their salvation; so Christ is one Ensign both to the Jews and Gentiles.
Isaiah saith, '`The Redeemer shall come to Sion,`' etc., Isa. 59:20. And,
'`This is my covenant with them, saith the Lord, my Spirit, that is upon thee (to wit,
Christ), and my words, which I have put in thy mouth, shall not depart out of thy mouth,
nor out of the mouth of thy seed, nor out of the mouth of thy seed's seed,
saith the Lord, from henceforth and for ever,`' ver. 21.
'`Arise, shine, for thy light is come,
and the glory of the Lord is risen upon thee,`' chap. 60:1.
'`And the Gentiles shall come to thy light,`' ver. 3.
'`And the abundance of the sea shall be converted unto thee,`' ver. 5 (the sea is the world).
'`The Lord shall be thy everlasting light,`' ver. 20.
And, '`Thou shalt call thy walls, Salvation, and thy gates, Praise,`' ver. 18.
And the Lord saith, '`I will make the place of my feet glorious,`' ver. 13.
'`Heaven is his throne,
and the earth is his footstool,`' chap. 66:1.
'`And he that puts his trust in me,
saith the Lord, shall possess the land,
and shall inherit my holy mountain,`' chap. 57:13. Which
mountain is established above all the mountains and hills,
Isa. 2:2. The Lord saith (speaking of Christ), '`I have put my Spirit upon him,
he shall bring forth judgment to the Gentiles,`' Isa. 42:1. And he saith of him,
'`I will give thee for a covenant of the people, for a light of the Gentiles;
to open the blind eyes, to bring out the prisoners from the prison,
and them that sit in darkness out of the prison-house.
I am the Lord, that is my name, and my glory will I not give to another,
neither my praise to graven images,`' ver. 6-8.
So Christ the Light is come, and the glory of the Lord is risen;
and the Gentiles are come to the light of Christ.
This prophecy of Isaiah concerning Christ, many of the Gentiles witness fulfilled,
that '`Salvation is come to the Gentiles,`' Rom. 11:11.
God gave his glory to his Son;
and Christ saith, '`The glory, which thou gavest me, I have given them (namely,
his believers and followers), that they may be one,
even as we are one,`' John 17:22.
Now here you may see,
the promises and prophecies are fulfilled in Christ Jesus,
whom God hath given for an Ensign both to the Jews and Gentiles,
and the Captain of their salvation;
and he doth enlighten every one that cometh into the world; that with his heavenly,
divine light, they might see Christ, the Lord from heaven, their Captain and Ensign,
and trust in Him, their Conqueror, who bruises the serpent's head,
and destroys the devil and his works; and Christ and his followers overcome the dragon,
beast, and false prophet.
Therefore all Jews, Gentiles, and Christians, that come to believe in Christ,
are to stand to their Ensign, Christ; who is also the Captain of their salvation,
above all ensigns and captains below; for he is from above;
therefore all are to trust in him; for he is certain and able to save to the utmost, etc.
He is the same Ensign and Captain to-day that he was yesterday, and so for ever,
the First and the Last, the Beginning and the Ending, the Lord of all lords,
and King of all kings upon the earth;
and there is nothing certain to be trusted in below Christ Jesus, who is from above.

"`You see in the Scriptures there were many ways and religions among the heathen,
as there were many sects among the Jews when Christ came;
and now there are many sects or religions among the Christians,
who believe from the Scriptures that '`he is come,`' as the Jews believed '`he was to come.`'
But they that close their eyes, and stop their ears to the Light of Christ,
are not like to see Christ, who hath enlightened them,
to be their Ensign and the Captain of their salvation,
that see not with the heavenly eye, nor hear with the heavenly ear,
to see and hear their heavenly Ensign and Captain of their salvation,
to convert and heal them; that they might follow him, and be of his holy camp,
his heavenly soldiers, to whom he gives spiritual arms and armour,
the helmet of salvation, the breastplate of righteousness, the armour of light,
and the shield of faith (which will quench all the fiery darts of Satan,
and give victory), and the sword of the Spirit, the Word of God, which shall cut,
hammer down, and bur n up all the strongholds of Satan.
Also he clothed his soldiers with fine linen, white and clean, his righteousness,
and shoeth them with the everlasting gospel of peace, the power of God;
which clothes and shoes will never wax old.
And all that are shod with the everlasting gospel, the power of God, will never wax old,
but will stand all storms and tempests in the world.
They that are shod with the gospel, the power of God, can in it tread upon serpents,
vipers, and scorpions, and all the venomous beasts upon the earth, and all the thorns,
briars, brambles, thistles, and sharp rocks and mountains, and never be hurt,
nor ever wear out their shoes; but their feet are always beautiful upon the mountains.
Moses, a captain, the servant of the Lord, said unto the people of Israel,
'`I have led you forty years in the wilderness; your clothes are not waxen old upon you,
and thy shoe is not waxen old upon thy foot,`' Duet.
29:5. Here ye may see the Jews in the Old Testament,
their clothes and their shoes did not wax old; so they who are Christ's followers,
whom he shoeth with his everlasting gospel of peace, clothes with his fine linen,
his righteousness, and arms with his arms and armour, are clothed, shod, and armed,
with that which will never decay, or wax old, never canker, or rust, corrupt,
or grow blunt.
Now, all (whether Christians, or Jews, or Gentiles) that hate the Light of Christ,
and close their eyes and stop their ears to it, are not like to see Christ, their Ensign,
and Captain of their salvation; but are blind.
As no outward captain would enlist a company of blind and deaf men,
and clothe and arm them with outward armour; so such as are blind and deaf,
whose eyes are closed, and ears stopped to the heavenly Light of Christ,
he is not likely to clothe them with his Cue linen,
and arm them with his heavenly and spiritual armour;
neither are they like to be heavenly and spiritually disciplined,
to see and know his holy, spiritual, living camp, nor to follow him, while they, are,
deaf and blind, and hate his Light, which is the Life in Christ,
For it is the Light that shines in the heart,
which gives the knowledge of the glory of God in the face of Christ Jesus;
who is the Ensign and Captain of men's salvation, and who hath brought,
and doth bring many sons unto glory; praises, honour,
and glory be unto the Lord over all, who liveth for ever.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Gooses, the 14th of the 2nd Month, 1690.

A week after this I returned to London;
and after a little stay there went to visit Friends at.
Kingston, where I stayed not long; but came back to London,
and remained there in the Lord's work till after the Yearly Meeting,
which was in the fourth month this year;
in which the wonted goodness of the Lord was witnessed, his blessed presence enjoyed,
and his heavenly power livingly felt, opening the hearts of his people unto him,
and his divine treasures of life and wisdom in and unto them;
whereby many useful and necessary things,
relating to the safety of Friends and to the honour and prosperity of truth,
were weightily treated of, and unanimously concluded.

[.offset]
After, the meeting I wrote the following paper to Friends,
to be added to the epistle which from the Yearly
Meeting was sent into the several counties:----

"`All Friends everywhere, that are alive to God through Jesus Christ,
and are living members of Christ, the holy Head, be still;
and stand still in the Lord's camp of holiness and righteousness;
and therein see the salvation of God, and your eternal life, rest, and peace.
In it you may feel and see the Lord's power is over all;
and how the Lord is at work in his power, ruling the nations with his rod of iron,
and breaking (in the nations) the old leaky vessels and cisterns to pieces,
like the potter's vessels, that will not hold his living water;
who are erred from his Spirit.

"`But blessed be the Lord God of heaven and earth, who,
by his eternal arm and power hath settled all his people upon the living,
holy rock and foundation, that stands sure; whom he hath drawn by his Spirit to his Son,
and gathered into the name of Jesus Christ, his only begotten Son,
full of grace and truth; who hath all power in heaven and in earth given to him;
whose name is above every name under the whole heaven;
and all his living members know there is no salvation
given by any other name than by the name of Jesus.
He, their salvation and their living head, is felt in the midst of them in his light,
life, Spirit, grace, and truth, and his word of patience, wisdom, and power;
who is his people's prophet, that God hath raised up in his New Testament and Covenant,
to open to them; and their living Shepherd, that hath purchased, redeemed,
and bought them with his precious blood.

"`Christ, the living One,
feeds his living sheep in his pastures of life and they know
their living Shepherd's voice with his living bread and water,
and follow him; and will not follow any of the world's hirelings, nor thieves,
nor robbers, nor climbers, that are without Christ, the door.
Christ's living children likewise know him, the bishop of their souls,
to oversee them with his heavenly and spiritual eye,
that they may be preserved in his fold of life, and go no more forth.
They also know Christ, their holy priest, that by the grace of God tasted death for them,
and for every man, and is a propitiation for their sins; and not for theirs only,
but for the sins of the whole world:
and by the one offering up of himself he hath
perfected for ever them that are sanctified.

"`Such a High-priest becomes Christ's sheep in his New Covenant and Testament,
who is holy, harmless, and separate from sinners, and is made higher than the heavens;
who is not made a priest after the order of Aaron, with his tithes, offerings, etc.,
but makes an end of all those things, having abolished them;
and is made a High-priest after the power of an endless life,
who ever liveth to make intercession for his people:
and is able to save to the uttermost all that come to God through him.
He is the one holy Mediator between God and man; who sanctifies his people, his church,
that he is head of, and presents them to God without spot, or wrinkle, or blemish,
or any such thing; and makes them a holy, royal priesthood, to offer up spiritual,
holy sacrifices, acceptable to God by Jesus Christ, who is King of all kings,
and Lord of all lords in the earth; so a holy, heavenly King,
who hath all power in heaven and in earth given to him,
and rules in all the hearts of his sheep and lambs, by his holy, divine, precious faith,
that is held in all the pure consciences of his people: of which holy faith Christ,
the holy One, is the author and finisher.
By this holy faith all the just live;
in which divine and precious faith all the just and holy ones have unity;
by it they quench all the fiery darts of Satan, have access to the pure God,
and in it please him.

"`Christ, who is set on the right hand of the throne of the Majesty in heaven,
in his New Testament and New Covenant,
is the minister of the sanctuary and true tabernacle which the Lord hath pitched,
and not man.
Therefore all the lambs and sheep of Christ must feel
this holy Minister in their temple and sanctuary,
who ministers spiritual, holy,
and heavenly things to them in their sanctuary and tabernacle.
For all the tabernacles and sanctuaries that are built or pitched by man,
men make ministers for them; and such ministers are of men and by men,
with their worldly sanctuaries and tabernacles of men's pitching, by men's hands.

"`And now, dear Friends and brethren everywhere that are of the flock of Christ;
Christ our passover is sacrificed for us.
Therefore let us all keep this heavenly feast of
our passover in his New Testament and Covenant,
not with old leaven, neither of malice nor wickedness; but let all that be purged out,
with the sour, old leavened bread, that all may become a new lump;
and so keep this heavenly feast of Christ, our heavenly Passover,
with the unleavened bread (mark, with the unleavened bread) of sincerity and truth.
My desires are,
that all the flock of Christ everywhere may keep this heavenly feast of Christ,
our heavenly passover, with his heavenly, unleavened bread of sincerity and truth.
Amen.`"

[.signed-section-signature]
G+++.+++ F.

I stayed in town three weeks or a month after the Yearly Meeting;
and then went to Tottenham-High-Cross, where was a meeting on First-day, which I was at;
and then went to Edward Man's house, at Ford-Green, near Winchmore-Hill;
and on the First-day following to the meeting at Enfield,
where the Lord gave me many precious openings to declare to the people.
Afterwards moving amongst Friends thereabouts, I visited the meetings at Chestnut,
"`Waltham Abbey, Enfield, Tottenham, and Winchmore-hill, frequently;
the Lord being with me, and opening many deep and weighty truths,
divine and heavenly mysteries to his people, through me, to their great refreshment,
and my joy.
After some time I went to Hertford, to visit Friends there;
and was at their meeting on a First-day.
And having something more particular upon me to the ancient Friends of that place,
I had a meeting with some of them the next day,
and imparted what the Lord had given me for them.
Then passing to Ware, I made a little stay amongst Friends there,
and was at their meeting.
After which, returning, amongst Friends about Edmonton side and Tottenham,
and taking meetings as I went, I came back to London the end of the seventh month.

I remained at London till the beginning of the ninth month,
being continually exercised in the work of the Lord, either in public meetings,
opening the way of truth to people, and building up and establishing Friends therein,
or in other services relating to the church of God.
For the parliament now sitting, and having a bill before them concerning oaths,
and another concerning clandestine marriages, several Friends attended the house,
to get those bills so worded, that they might not be hurtful to Friends.
In this service I also assisted, attending on the parliament,
and discoursing the matter with several of the members.

Having stayed more than a month in London, and much spent myself in these services,
I went to Tottenham; and some time after to Ford_Green;
at which places I continued several weeks, visiting Friends`' meetings round about there,
at Tottenham, Enfield, and Winchmore-Hill.
In this time several things came upon me to write;
one was "`an epistle to Friends in the ministry,`" as follows:--

"`All Friends in the ministry everywhere, to whom God hath given a gift of the ministry,
and who travel up and down in it, do not '`hide your talent,
nor put your light under a bushel,
nor cumber or entangle yourselves with the affairs of this world.`'
For the natural soldiers are not to cumber themselves with the world,
much less the soldiers of Christ, who are not of this world;
but are to mind the riches and glory of the world that is everlasting.
Therefore, stir up the gift of God in you, and improve it; do not sit down, Demas-like,
and embrace this present world, that will have an end; lest ye become idolaters.
Be valiant for God's truth upon the earth,
and spread it abroad in the day-light of Christ, you who have sought the kingdom of God,
and the righteousness thereof, and have received it, and preached it;
which '`stands in righteousness, and peace, and joy in the Holy Ghost.`'
As able ministers of the Spirit sow to the Spirit,
that of the Spirit ye may reap life everlasting.
Go on in the Spirit, ploughing with it in the purifying hope; and thrashing,
with the power and Spirit of God, the wheat out of the chaff of corruption,
in the same hope.
For he that looks back from the spiritual plough into the world,
is not fit for the spiritual and everlasting kingdom of God;
and is not like to press into it, as the faithful do.
Therefore you that are awakened to righteousness, and to the knowledge of the truth,
keep yourselves awakened in it; then the enemy cannot sow his tares in your field;
for truth and righteousness is over him, and before he was.
My desires are, that all may fulfil their ministry,
that the Lord Jesus Christ hath committed to them;
and then by the blood (or life) and testimony of Jesus
you will overcome the enemy that opposes it,
within and without.
All you that preach the truth, do it as it is in Jesus, in love:
and all that are believers in Jesus, and receivers of him,
he gives them power to become the sons of God, and joint-heirs with Christ;
whom he calleth brethren; and he gives them the water of life,
which shall be a well in them, springing up as a river to eternal life,
that they may water the spiritual plants of the living God.
So that all may be spiritual planters, and spiritual waterers;
and may see with the spiritual eye the everlasting, eternal God,
over all to give the increase, who is the infinite fountain.
My desires are, that you may be kept out of all the beggarly elements of the world,
which are below the spiritual region, to Christ the Head; and may hold Him,
who bruiseth the head of enmity, and was before it was;
that ye may all be united together in love, in your Head, Christ,
and be ordered by his heavenly, gentle, peaceable wisdom, to the glory of God.
For all that be in Christ, are in love, peace, and unity.
In Him they are strong, and in a full persuasion: and in Him,
who is the first and the last,
they are in a heavenly resolution and confidence for God's everlasting honour and glory.
Amen.

"`From him, who is translated into the kingdom of his dear Son, with all his saints,
a heavenly salutation.
Salute one another with a holy kiss of charity, that never faileth.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Ford-Green, the 25th of the 9th Month, 1690.

[.offset]
Another epistle I wrote soon after,
more particularly to the Friends in the ministry that were gone into America;
after this manner:--

"`Dear Friends and Brethren, Ministers, Exporters, and Admonishers,
that are gone into America and the islands thereaway.
Stir up the gift of God in you, and the pure mind, and improve your talents,
that ye may be the light of the world, a city set upon a hill, that cannot be hid.
Let your light shine among the Indians, the Blacks, and the Whites,
that ye may answer the truth in them, and bring them to the standard and ensign,
that God hath set up, Christ Jesus.
For from the rising of the sun to the going down of the same,
God's name shall be great among the Gentiles; and in every temple, or sanctified heart,
incense shall be offered up to God's name.
And have salt in yourselves, that ye may be the salt of the earth, that ye may salt it;
that it may be preserved from corruption and putrefaction;
so that all sacrifices offered up to the Lord may be seasoned,
and be a good savour to God.
All grow in the faith and grace of Christ, that ye may not be like dwarfs,
for a dwarf shall not come near to offer upon God's altar;
though he may eat of God's bread, that he may grow by it.
And Friends, be not negligent,
but keep up your negroes`' meetings and your family meetings;
and have meetings with the Indian kings, and their councils and subjects everywhere,
and with others.
Bring them all to the baptizing and circumcising Spirit, by which they may know God,
and serve and worship Him.
And all take heed of having your minds in earthly things, coveting and striving for them;
for to be carnally minded brings death, and covetousness is idolatry.
There is too much strife and contention about that idol,
which makes too many go out of the sense and fear of God;
so that some have lost morality, humanity, and true Christian charity.
O therefore, be awakened to righteousness, and keep awakened:
for the enemy soweth his tares, while men and women sleep in carelessness and security.
Therefore so many slothful ones go in their filthy rags, and have not the fine linen,
the righteousness of Christ; but are straggling,
and ploughing with their ox and their ass, in their woollen and linen garments,
mixed stuff, feeding upon torn food that dieth of itself,
and drinking of the dregs of their old bottle, and eating the sour, leavened bread,
which makes their hearts burn one against another.
But all are to keep the feast of Christ, our passover,
with the unleavened bread of sincerity and truth.
This unleavened bread of life from heaven, makes all hearts and souls glad and joyful,
lightsome and cheerful, to serve and love God,
and to love and serve one another in the peaceable truth,
and to keep in the unity of God's Spirit, which is the bond of peace.
In this love and peace, God Almighty keep and preserve all his people,
and make them valiant for his truth upon the earth, to spread it abroad in doctrine,
good life, and conversation. Amen.

"`All the members of Christ have need one of another.
For the foot hath need of the hand, and the hand of the foot;
the ear hath need of the eye, and the eye of the ear.
So that all the members are serviceable in the body, which Christ is the head of;
and the head sees their service.
Therefore, let none despise the least member.

"`Have a care to keep down that greedy, earthly mind,
that raveneth and coveteth after the riches and things of this world,
lest ye fall into the low region, like the Gentiles or heathen,
and so lose the kingdom of God, that is everlasting: but seek that first,
and God knows what things ye have need of; who takes care for all,
both in heaven and in the earth: thanks be unto God for his unspeakable gifts,
both temporal and spiritual.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Tottenham, the 11th of the 10th Month, 1690.

Not long after I returned to London, and was almost daily with Friends at meetings.
When I had been near two weeks in town,
the sense of the great hardships and sore sufferings
that Friends had been and were under in Ireland,^
footnote:[The sufferings of Friends in Ireland at this time were very great.
The havoc and spoil they underwent were enormous,
as related by the historians Sewell and Rutty, and more minutely by Besse,
in his _Collection of Sufferings,_ to which allusion has been made before,
and to which the reader is now finally referred.
The loss sustained by Friends from persecution in a
single year (1689) was estimated at 100,000,
many being deprived of all their substance.
Great numbers were immured years in prison, and many died there for Christ's sake.
Others, when there was a prospect of their being released,
because they could not satisfy the unjust demand of fees,
as having done no wrong (thus bravely, though passively,
asserting their Christian liberty), were either detained,
or stripped of their clothes and turned out.
{footnote-paragraph-split}
Surrounded as they were with perils on every hand,
they placed their confidence in Divine protection; and, in the worst times of trial,
when not in prison, they kept up their meetings for worship, as well as discipline;
collected at the latter the accounts of the sufferings of their members,
and took what care they could for their relief.]
coming with great weight upon me, I was moved to write the following epistle,
as a word of consolation unto them:--

"`Dear Friends and Brethren in the Lord Jesus Christ,
whom the Lord by his eternal arm and power hath upheld through your great sufferings,
exercises, trials, and hardships (more, I believe, than can be uttered),
up and down that nation, which I am very sensible of;
and the rest of the faithful Friends,
who have been partakers with you in your sufferings;
and who cannot but suffer with the Lord's people that suffer.
My confidence hath been in the Lord,
that he would and will support you in all your sufferings;
and that he would preserve all the faithful in his wisdom,
that they might give no just occasion to one nor other to make them suffer;
and if you did suffer wrongfully, or unjustly,
that the righteous God would assist and uphold you;
and reward them according to their works, that oppressed or wronged you.
And now my desire is unto the Lord, that in the same holy and heavenly wisdom,
ye may all be preserved to the end of your days, to the glory of God,
minding His supporting hand and power, who is God All-sufficient, to strengthen, help,
and refresh, in time of need.
Let none forget the Lord's mercies and kindnesses, which endure for ever;
but always live in the sense of them.
And truly, Friends, when I consider the thing, it is the great mercy of the Lord,
that ye have not been all swallowed up,
seeing with what spirits ye have been compassed about.
But the Lord carrieth his lambs in his arms,
and they are as tender to him as the apple of his eye;
and his power is his hedge about his vineyard of heavenly plants.
Therefore it is good for all his children,
to be given up to the Lord with their minds and souls, hearts and spirits,
who is a faithful keeper, that never slumbers nor sleeps;
but is able to preserve and keep you, and to save to the utmost;
and none can hurt so much as a hair of your heads, except he suffer it, to try you;
for he upholds all things, in heaven and in earth, by the Word of his power;
all things were made by Christ, and by Him all things consist (mark, consist),
whether they be visible, or invisible, etc.
So he hath power over all; for all power in heaven and in earth is given to him;
and to you that have received him,
he hath given power to become the sons and daughters of God; so living members of Christ,
the living head, grafted into Him, in whom ye have eternal life.
Christ, the Seed, reigns, and his power is over all; who bruises the serpent's head,
and destroys the devil and his works, and was before he was.
So all of you live and walk in Christ Jesus; that nothing may be between you and God,
but Christ, in whom ye have salvation, life, rest, and peace with God.

"`As for the affairs of truth in this land and abroad,
I hear that in Holland and Germany, and thereaway, Friends are in love, unity, and peace;
and in Jamaica, Barbadoes, Nevis, Antigua, Maryland, and New England, I hear nothing,
but Friends are in unity and peace.
The Lord preserve them all out of the world (in which there is trouble), in Christ Jesus,
in whom there is peace, life, love, and unity. Amen.
My love in the Lord Jesus Christ to all Friends everywhere in your land,
as though I named them.`"

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
London, the 10th of the 11th Month, 1690.

[.asterism]
'''

Thus, reader, thou hast had some account of the life and travels, labours, sufferings,
and manifold trials and exercises of this holy man of God,
from his youth to almost the time of his death, of which himself kept a journal;
out of which the foregoing sheets were transcribed.
It remains that an account be added of the time, place,
and manner of his death and burial, which were thus:--

The day after he had written the foregoing epistle to Friends in Ireland,
he went to the meeting at Gracechurch Street, which was large,
being the First-day of the week;
and the Lord enabled him to preach the truth fully and effectually,
opening many deep and weighty things with great power and clearness.
After which having prayed, and the meeting being ended, he went to Henry Goldney's,
in White-Hart-Court, near the meetinghouse; and some Friends going with him there,
he told them "`he thought he felt the cold strike to his heart,
as he came out of the meeting;`" "`yet,`" he added,
"`I am glad I was here: now I am clear, I am fully clear.`"
As soon as the Friends withdrew, he lay down upon a bed (as he sometimes used to do,
through weariness after meeting), but soon rose again;
and in a little time lay down again, complaining still of cold.
And his strength sensibly decaying, he was soon obliged to go into bed;
where he lay in much contentment and peace, and very sensible to the last.
And as, in the whole course of his life, his spirit, in the universal love of God,
was bent upon the exalting of truth and righteousness,
and the making known the way thereof to the nations and people afar of; so now,
in the time of his outward weakness, his mind was intent upon,
and (as it were) wholly taken up with that; and some particular Friends he sent for,
to whom he expressed his mind and desire for the spreading of Friends`' books,
and truth thereby in the world.
Divers Friends came to visit him in his illness; to some of whom he said, "`All is well;
the Seed of God reigns over all, and over death itself.
And though,`" said he, "`I am weak in body, yet the power of God is over all,
and the Seed reigns over all disorderly spirits.`"
Thus lying in a heavenly frame of mind, his spirit wholly exercised towards the Lord,
he grew weaker and weaker in his natural strength; and on the third day of the week,
between the hours of nine and ten in the evening, he quietly departed this life in peace,
and sweetly fell asleep in the Lord,
whose blessed truth he had livingly and powerfully
preached in the meeting but two days before.
Thus ended he his day in his faithful testimony,
in perfect love and unity with his brethren, and in peace and good-will to all men,
on the 13th of the 11th Month, 1690, being in the 67th year of his age.

After the death of George Fox, an epistle was found written with his own hand,
and left sealed up, with this superscription;
"`Not to be opened before the time;`" that is, not till after his decease.
When it was opened, it was found to be addressed to
"`Friends, and to all the Children of God, in all places in the world.`"
It was afterwards printed, and is inserted in the Appendix to this Journal.

On the day appointed for the interment of George Fox, a very great concourse of Friends,
and others, assembled at the meeting-house in White-Hart-Court, near Gracechurch Street,
about the middle of the day, to attend his body to the grave.
The meeting held about two hours with great and heavenly solemnity,
manifestly attended with the Lord's blessed presence and glorious power;
in which divers living testimonies were given,
from a lively remembrance and sense of the blessed
ministry of this dear and ancient servant of the Lord,
his early entering into the Lord's work at the breaking forth of this gospel-day,
his innocent life, long and great travels,
and unwearied labours of love in the everlasting gospel,
for the turning and gathering of many thousands
from darkness to the light of Christ Jesus,
the foundation of true faith; the manifold sufferings, afflictions, and oppositions,
which he met withal for his faithful testimony, both from his open adversaries,
and from false brethren; and his preservations, deliverances, and dominion in, out of,
and over them all, by the power of God; to whom the glory and honour always was by him,
and is, and always ought to be by all, ascribed.

After the meeting was ended, his body was borne by Friends,
and accompanied by very great numbers, to Friends`' burying-ground, near Bunhill-Fields;
where, after a solemn waiting upon the Lord, and several living testimonies borne,
recommending the company to the guidance and protection of that Divine Spirit and power,
by which this holy man of God had been raised up, furnished, supported, and preserved,
to the end of his day, his body was committed to the earth;
but his memorial shall remain, and be everlastingly blessed among the righteous.
