== Testimony of Margaret Fox

[.blurb]
=== Concerning Her Late Husband George Fox; With a Brief Account of Some of His Travels, Sufferings, and Hardships Endured for the Truth`'s Sake.

It having pleased Almighty God to take away my dear husband out of this evil,
troublesome world, who was not a man thereof, being chosen out of it;
who had his life and being in another region, and whose testimony was against the world,
that the deeds thereof were evil, and therefore the world hated him:
so I am now to give in my account and testimony for him,
whom the Lord hath taken unto his blessed kingdom and glory.
And it is before me from the Lord, and in my view, to give a relation,
and leave upon record the dealings of the Lord with us from the beginning.

He was the instrument in the hand of the Lord in this present age,
which he made use of to send forth into the world, to preach the everlasting gospel,
which had been hid from many ages and generations; the Lord revealed it unto him,
and made him open that new and living way, that leads to life eternal,
when he was but a youth, and a stripling.
And when he declared it in his own country of Leicestershire, and in Derbyshire,
Nottinghamshire, and Warwickshire,
his declaration being against the hireling priests and their practices,
it raised a great fury and opposition amongst the priests and people against him;
yet there were always some that owned him in several places;
but very few that stood firm to him when persecution came on him.
He and one other were put in prison at Derby, but the other declined,
and left him in prison there, where he continued almost a whole year;
and when he was released out of prison, he went on with his testimony abroad,
and was put in prison again at Nottingham; and there he continued a while,
and after was released again.

He then travelled on into Yorkshire, and passed up and down that great county,
and several received him, as William Dewsbury, Richard Farnsworth, Thomas Aldam,
and others, who all came to be faithful ministers of the Spirit for the Lord.
He continued in that country, and travelled through Holderness and the Wolds,
and abundance were convinced:
and several were brought to prison at York for their testimony to the truth,
both men and women: so that we heard of such a people that were risen,
and we did very much inquire after them.
And after a while he travelled up farther towards the Dales in Yorkshire, as Wensleydale,
and Sedbergh; and amongst the hills, dales, and mountains he came on,
and convinced many of the eternal Truth.

In the year 1652 it pleased the Lord to draw him towards us; so he came on from Sedbergh,
and so to Westmorland, as Firbank Chapel, where John Blakelin came With him;
and so on to Preston, Grayrigg, Keudal, Underbarrow, Podlbank, Cartmell, and Stavely;
and so on to Swarthmore, my dwelling-house,
whither he brought the blessed tidings of the everlasting gospel, which I,
and many hundreds in these parts, have cause to praise the Lord for.
My then husband, Thomas Fell, was not at home at that time,
but gone to the Welsh circuit, being one of the judges of assize;
and our house being a place open to entertain ministers and religious people at,
one of George Fox`'s friends brought him hither, where he stayed all night.
The next day being a lecture, or a fast-day, he went to Ulverstone steeple-house,
but came not in till people were gathered;
I and my children had been a long time there before.
And when they were singing before the sermon, he came in; and when they had done singing,
he stood np upon a seat or form, and desired that he might have liberty to speak;
and he that was in the pulpit said he might.
And the first words that he spoke were as followeth:
"`He is not a Jew that is one outward; neither is that circumcision which is outward:
but he is a Jew that is one inward; and that is circumcision which is of the heart.`"
And so he went on, and said, how that Christ was the Light of the world,
and lighteth every man that cometh into the world;
and that by this Light they might be gathered to God, etc.
I stood up in my pew and wondered at his doctrine; for I had never heard such before.
And then he went on, and opened the Scriptures, and said,
"`the Scriptures were the prophets`' words, and Christ`'s and the apostles`' words,
and what, as they spoke, they enjoyed and possessed,
and had it from the Lord:`" and said, "`then what had any to do with the Scriptures,
but as they came to the Spirit that gave them forth.
You will say, Christ saith this, and the apostles say this; but what canst thou say?
Art thou a child of Light, and hast thou walked in the Light, and what thou speakest,
is it inwardly from God?`"
etc. This opened me so, that it cut me to the heart;
and then I saw clearly we were all wrong.
So I sat down in my pew again, and cried bitterly: and I cried in my spirit to the Lord,
"`We are all thieves; we are all thieves; we have taken the Scriptures in words,
and know nothing of them in ourselves.`"
So that served me, that I cannot well tell what he spoke afterwards;
but he went on in declaring against the false prophets, and priests,
and deceivers of the people.
And there was one John Sawrey, a justice of peace, and a professor,
that bid the churchwarden take him away; and he laid his hands on him several times,
and took them off again, and let him alone; and then after a while he gave over,
and came to our house again that night.
And he spoke in the family amongst the servants, and they were all generally convinced;
as William Caton, Thomas Salthouse, Mary Askew, Anne Clayton, and several other servants.
And I was struck into such a sadness, I knew not what to do, my husband being from home.
I saw it was the truth, and I could not deny it; and I did as the apostle saith,
"`I received the truth in the love of it:`" and it was opened to me so clear,
that I had never a tittle in my heart against it;
but I desired the Lord that I might be kept in it; and then I desired no greater portion.

Then he went on to Dalton, Aldingham, Dendrum, and Ramside chapels and steeple-houses,
and several places up and down, and the people followed him mightily;
and abundance were convinced, and saw that what he spoke was truth,:
but the priests were all in a rage.
About two weeks after, James Nayler and Richard Farnsworth followed him,
and inquired him out, till they came to Swarthmore,
and there stayed a while with me at our house, and did me much good,
for I was under great heaviness and judgment.
But the power of the Lord entered upon me within about two weeks that he came;
and about three weeks`' end my husband came home; and many were in a mighty rage.
And a deal of the captains and great ones of the country went to,
meet my then husband as he was coming home,
and informed him "`that a great disaster was befallen amongst his family,
and that they were witches; and that they had taken us out of our religion;
and that he might either set them away, or all the country would be undone.`"
But no weapon formed against the Lord shall prosper, as you may see hereafter.

So my husband came home greatly offended:
and any may think what a condition I was like to be in,
that either I must displease my husband, or offend God;
for he was very much troubled with us all in the house and family,
they had so prepossessed him against us.
But James Nayler and Richard Farnsworth were both then at our house,
and I desired them to come and speak to him, and so they did, very moderately and wisely;
but he was at first displeased with them,
till they told him they came in love and good-will to his house.
And after that he had heard them speak a while, he was better satisfied;
and they offered as if they would go away; but I desired them to stay,
and not to go away yet, for George Fox will come this evening.
And I would have had my husband to have heard them all,
and satisfied himself farther about them;
because they had so prepossessed him against them of such dangerous, fearful things,
in his coming first home.
And then was he pretty moderate and quiet; and his dinner being ready, he went to it;
and I went in, and sat me down by him.
And whilst I was sitting, the power of the Lord seized upon me;
and he was struck with amazement, and knew not what to think; but was quiet and still.
And the children were all quiet and still, and grown sober,
and could not play on their music that they were learning:
and all these things made him quiet and still.

At night George Fox came: and after supper my husband was sitting in the parlour,
and I asked him, if George Fox might come in; and he said, Yes.
So George came in without any compliment, and walked into the room,
and began to speak presently; and the family, and James Nayler,
and Richard Farnsworth came all in: and he spoke very excellently as ever I heard him,
and opened Christ`'s and the apostles`' practices, which they were in, in their day.
And he opened the night of apostasy since the apostles`' days,
and laid open the priests and their practices in the apostasy;
that if all in England had been there,
I thought they could not have denied the truth of those things.
And so my husband came to see clearly the truth of what he spoke,
and was very quiet that night, said no more, and went to bed.
The next morning came Lampitt, priest of Ulverstone, and got my husband into the garden,
and spoke much to him there; but my husband had seen so much the night before,
that the priest got little entrance upon him.
And when the priest Lampitt was come into the house, George spoke sharply to him,
and asked him "`when God spoke to him, and called him to go and preach to the people?`"
but after a while the priest went away: this was on a sixth day of the week,
about the fifth month, 1652.
And at our house divers Friends were speaking one to another,
how there were several convinced hereaways; and we could not tell where to get a meeting:
my husband also being present, he overheard, and said of his own accord,
"`You may meet here,
if you will:`" and that was thirst meeting we had that he offered of his own accord.
And then notice was given that day and the next to Friends,
and there was a good large meeting the first day,
which was the first meeting that was at Swarthmore;
and so continued there a meeting from 1652 till 1690.
And my husband went that day to the steeple-house,
and none with him but his clerk and his groom that rode with him;
and the priest and people were all fearfully troubled: but praised be the Lord,
they never got their wills upon us to this day.

After a few weeks George went to Ulverstone steeple-house again,
and the said Justice Sawrey, with others, set the rude rabble upon him;
and they beat him so that he fell down as in a swoon,
and was sore bruised and blackened in his body, and on his head and arms.
Then my husband was not at home;
but when he came home he was displeased that they should do so;
and spoke to Justice Sawrey, and said it was against law to make riots.
And after that he was sore beat and stoned at Walney, till he fell down;
and also at Dalton was he sore beat and abused;
so that he had very hard usage in divers places in those parts.
And then when a meeting was settled there, he went again into Westmorland,
and settled meetings there; and there was a great convincement,
and abundance of brave ministers came out thereaways, as John Camm, John Audland,
Francis Howgill, Edward Burrough, Miles Halhead, and John Blakelin, with divers others.
He also went over the sands to Lancaster, and Yealand, and Kellet, where Robert Widders,
Richard Hubberthorn, and John Lawson, with many others, were convinced.
And about that time he was in those parts, many priests and professors rose up,
and falsely accused him of blasphemy, and did endeavour to take away his life;
and got people to swear at a sessions at Lancaster that he had spoken blasphemy.
But my then husband and Colonel West, having had some light and knowledge of the truth,
withstood the two persecuting justices, John Sawrey and Thompson, and brought him off,
and cleared him; for indeed he was innocent.
And after the sessions there was a great meeting in the town of Lancaster;
and many of the town`'s-people came in, and many were convinced.
And thus he was up and down about Lancaster, Yealand, Westmorland,
and some parts of Yorkshire, and our parts above one year;
in which time there were above twenty-four ministers brought forth,
that were ready to go with their testimony of the Eternal Truth unto the world;
and soon after Francis Howgill and John Camm went to speak to Oliver Cromwell.

In the year 1653, George`'s drawings were into Cumberland, by Millom, Lamplugh, Embleton,
and Brigham, Fardshaw, and Cockermouth,
where at or near Embleton he had a dispute with some priests, as Larkham and Benson;
but chiefly with John Wilkinson, a preacher at Embleton and Brigham,
who was afterwards convinced, and owned the Truth,
and was a serviceable minister both in England, Ireland, and Scotland.
Then he went to Coldbeck and several places, till he came to Carlisle,
and went to their steeple-house; there they beat and abused him,
and had him before the magistrates, who examined him,
and put him in prison in the common jail among the thieves.
At the assizes was one Anthony Pearson, who had been a justice of peace,
and was convinced at Appleby (when he was upon
the bench) by James Nayler and Francis Howgill,
who were then prisoners there, and brought before him;
so Anthony Pearson spoke to the justices at Carlisle, he being acquainted with them,
having married his wife out of Cumberland; and after a while they released him.
Afterwards he went into several parts of Cumberland, and many were convinced,
and owned the Truth; and he gathered and settled meetings there amongst them,
and up and down in several parts in the North.

In the year 1654, he went southward to his own country of Leicestershire,
visiting Friends.
And then Colonel Hacker sent him to Oliver Cromwell;
and after having been kept prisoner a while, he was brought before Oliver, and released.
He then stayed a while, visiting Friends in London, and the meetings therein;
and so passed westward to Bristol, and visited Friends there.
He afterwards went into Cornwall, where they put him in prison at Launceston,
and one Edward Pyot with him, where he had a bad, long imprisonment.
When he was released, he passed into many parts in that county of Cornwall,
and settled meetings there.
Then he travelled through many counties,
visiting Friends and settling meetings all along; and so came into the North,
and to Swarthmore, and to Cumberland.

And so for Scotland he passed in the year 1657, and there went with him Robert Widders,
James Lancaster, John Grave, and others.
He travelled through many places in that nation, as Douglas, Heads, Hamilton, Glasgow,
and to Edinburgh, where they took him,
and carried him before General Monk and the council, and examined him,
and asked him his business into that nation; who answered,
he came to visit the seed of God.
And after they had threatened him, and charged him to depart their nation of Scotland,
they let him go.
Then he went to Linlithgow, and Stirling, and Johnstone, and many places,
visiting the people; and several were convinced.
And after he had stayed a pretty while, and settled some meetings,
he returned into Northumberland, and into the bishopric of Durham,
visiting Friends and settling meetings as he went;
and then returned back again to Swarthmore, and stayed amongst Friends a while,
and so returned south again.
In 1658, Judge Fell died.

In 1660 he came out of the South into the North,
and had a great general meeting about Balby in Yorkshire; and so came on,
visiting Friends in many places, till he came to Swarthmore again.
And King Charles then being come in, the justices sent out warrants,
and took him at Swarthmore, charging him in their warrants,
that he drew away the king`'s liege people,
to the endangering the embroiling the nation in blood;
and sent him prisoner to Lancaster castle.
And I having a great family, and he being taken in my house,
I was moved of-the Lord to go to the king at Whitehall; and took with me a declaration,
and an information of our principles, and a long time, and much ado I had, to get to him.
But at last, when I got to him, I told him if he was guilty of those things,
I was guilty, for he was taken in my house; and I gave him the paper of our principles,
and desired that he would set him at liberty,
as he had promised that none should suffer for tender consciences;
and we were of tender consciences,
and desired nothing but the liberty of our consciences.
Then with much ado, after he had been kept prisoner near half a year at Lancaster,
we got a _habeas corpus_, and removed him to the king`'s bench, where he was released.
And then would I gladly have come home to my great family, but was bound in my spirit,
and could not have freedom to get away for a whole year.
The king had promised me several times that we should have our liberty,
but then the Monarchy-men rose;
and then came the great and general imprisonment of Friends the nation through;
and so could I not have freedom nor liberty to come home,
till we had got a general proclamation for all our Friends`' liberty.
Then I had freedom and peace to come home.

In 1663 he came North again, and to Swarthmore.
Then they sent out warrants, and took him again;
and had him to Holcrof before the justices, who tendered him the oath of allegiance,
and sent him prisoner to Lancaster castle.
And about a month after, the justices sent for me also out of my house,
and tendered me the oath, and sent me prisoner to Lancaster.
And the next assizes they again tendered the oath of allegiance and supremacy to us both,
and premunired me; but they had missed the date, and other things in the indictment,
and so it was quashed; but they tendered him the oath again,
and kept him prisoner a year and a half at Lancaster castle.
And then they sent him to Scarborough castle in Yorkshire,
where they kept him prisoner close under the soldiers much of a year and a half,
so that a '`Friend could scarcely have spoken to him; yet after that,
it pleased the Lord that he was released; but I continued in prison,
and a prisoner four years at that time; and an order was procured from the council,
whereby I was set at liberty.
And in that time I went down into Cornwall with my son and daughter Lower,
and came back by London to the Yearly Meeting; and there I met with him again;
and then he told me the time was drawing on towards our marriage,
but he might first go into Ireland.
And a little before this time was he prisoner in
his own country at Leicester for a while,
and then released.
So into Ireland he went, and I went into Kent and Sussex, and came back to London again;
and afterwards I went to the West, towards Bristol, in 1669,
and there I stayed till he came over from Ireland,
which was eleven years after my former husband`'s decease.
In Ireland he had had a great service for the Lord and his eternal truth,
amongst Friends and many people there, but escaped many dangers,
and times of being taken prisoner,
they having laid in wait aforehand for him in many places.
And then he being returned, at Bristol he declared his intentions of marriage;
and there also was our marriage solemnized.
Within ten days after I came homewards,
but my husband stayed up and down in the countries amongst Friends, visiting them.

Soon after I came home,
there came another order from the council to cast me into prison again;
and the sheriff of Lancashire sent his bailiff, and pulled me out of my own house,
and had me prisoner to Lancaster castle (upon the old premunire),
where I continued a whole year, and most part of that time was I sick and weakly;
my husband also was weak and sickly at that time.
After a while he recovered, and went about to get me out of prison,
and a discharge at last was got under the great seal; and so I was set at liberty.
Then I was to go up to London again, for my husband was intending for America.
He was full two years away, before he came back again into England;
and having arrived at Bristol, he came thence to London,
intending to come to the middle of the nation with me;
but when we came into some parts of Worcestershire, they got there information of him;
and one Justice Parker, by his warrant, sent him and my son Lower to Worcester jail.
The justices there tendered him the oath, and premunired him, but released my son Lower,
who stayed with him most of the time he was prisoner there.

After some time he fell sick, in a long, lingering sickness, and many times was very ill;
so they writ to me from London, that if I would see him alive, I might go to him;
which accordingly I did.
After I had tarried seventeen weeks with him at Worcester,
and no discharge likely to be obtained for him, I went up to London,
and wrote to the king an account of his long imprisonment,
and how he was taken in his travel homewards, and that he was weak and sick,
and not likely to live if they kept him long there.
I went with it to Whitehall myself, where I met with the king and gave him the paper;
and he said, I must go to the chancellor, he could do nothing in it.
Then I wrote also to the lord chancellor, and went to his house, gave him my paper,
and spoke to him, that the king had left it wholly to him;
and if he did not take pity and release him out of that prison,
I feared he would end his days there.
The Lord Chancellor Finch was a very tender man, and spoke to the judge,
who gave out an _habeas corpus_ presently.
When we got it we sent it down to Worcester, and they would not part with him at first,
but said he was premunired, and was not to go out on that manner.
Then we were forced to go to Judge North, and to the attorney general,
and we got another order, and sent down from them; and with much ado,
and great labour and industry of William Mead and other friends, we got him up to London,
where he appeared in '`Westminster Hall at the king`'s bench, before Judge Hale,
who was a very honest, tender man; and he knew they had imprisoned him but in envy.
So that which they had against him was read,
and our counsel pleaded that he was taken up in his travel and journey.
And there was but a little said till he was acquitted.
This was the last prison that he was in, being freed by the court of king`'s bench.

When he was at liberty he recovered again;
and then I was very desirous to go home with him, which we did.
This was the first time that he came to Swarthmore after we were married;
and he stayed here much of two years,
and then went to London again to the Yearly Meeting; and after a while went into Holland,
and some parts of Germany, where he stayed a pretty while,
and then returned to London again at the next Yearly Meeting.
And after he had stayed a while in and about London,
he came into the North to Swarthmore again, and stayed that time near two years;
and then he grew weakly, being troubled with pains and aches,
having had many sore and long travels, beatings, and hard imprisonments.
But after some time he rode to York,
and so passed on through Nottinghamshire and several counties, visiting Friends,
till he came to London to the Yearly Meeting, and stayed there, and thereaways,
till he finished his course, and laid down his head in peace.

And though the Lord had provided an outward habitation for him,
yet he was not willing to stay at it, because it was so remote and far from London,
where his service most lay.
And my concern for God, and his holy eternal truth, was then in the North,
where God had placed and sent me,
and likewise for the ordering and governing of my children and family;
so that we were very willing both of us, to live apart for some years upon God`'s account,
and his truth`'s service,
and to deny ourselves of that comfort which we might have had in being together,
for the sake and service of the Lord and his truth.
And if any took occasion, or judged hard of us because of that, the Lord will judge them;
for we were innocent.
And for my own part, I was willing to take many long journeys,
for taking away all occasion of evil thoughts;
and though I lived two hundred miles from London, yet have I been nine times there,
upon the Lord and his truth`'s account; and of all the times that I was at London,
this last time was most comfortable,
that the Lord was pleased to give me strength and ability to travel that great journey,
being seventy-six years of age, to see my dear husband,
who was better in his health and strength than many times I had seen him before.
I look upon it, that the Lord`'s special hand was in it, that I should go then,
for he lived but about half a year after I left him;
which makes me admire the wisdom and goodness of God,
in ordering my journey at that time.

And now he hath finished his course, and his testimony,
and is entered into his eternal rest and felicity.
I trust in the same powerful God, that his holy arm and power will carry me through,
whatever he hath yet for me to do; and that he will be my strength and support,
and the bearer up of my head unto the end, and in the end.
For I know his faithfulness and goodness, and I have experience of his love;
to whom be glory and powerful dominion forever.
Amen.

[.signed-section-signature]
M+++.+++ F.
