== Testimony of Some of the Author`'s Relations.

Neither days nor length of time with us can wear
out the memory of our dear and honoured father,
George Fox, whom the Lord hath taken to himself.
And though his earthly house of this tabernacle be dissolved, and mortality put off,
yet we believe he has a "`building with God eternally in the heavens,
and is entered into rest,`" as a reward to those great labours, bard sufferings,
and sore trials he patiently endured for God and his truth.
Of which truth he was made an able minister, and one,
if not the first promulgator of it in our age; who, though of no great literature,
nor seeming much learned, as to the outward (being hid from the wisdom of this world),
yet he had the tongue of the learned,
and could speak a word in due season to the conditions and capacities of most,
especially to them that were weary, and wanted soul`'s rest;
being deep in the divine mysteries of the kingdom of God.
And the word of life and salvation through him reached unto many souls,
whereby many were convinced of their great duty of inward retiring to wait upon God;
and as they became diligent in the performance of that service,
were also raised up to be preachers of the same
everlasting gospel of peace and glad tidings to others;
who are as seals to his ministry both in this and other nations,
and may possibly give a more full account thereof.
Howbeit we knowing his unwearied diligence, not sparing,
but spending himself in the work and service whereunto he was chosen and called of God,
could not but give this short testimony of his faithfulness therein,
and likewise of his tender love and care towards us; who,
as a tender father to his children (in which capacity we stood,
being so related unto him), never failed to give us his wholesome counsel and advice.
And not only so, but, as a father in Christ,
he took care of the whole family and household of faith,
which the Lord had made him an eminent overseer of,
and endued him with an excellent spirit of wisdom and understanding,
to propose and direct such helps and advantages to the well-ordering
and establishing of affairs and government in the church,
as now are found very serviceable thereunto;
and have greatly disappointed and prevented the false, loose,
and libertine spirit of some who, to their own confusion, have endeavoured,
by separation and division, to disturb the church`'s peace.
And although many of that sort have at sundry times shot their poisonous darts at him,
publicly in print, and privately other ways,
yet he has been always preserved by the heavenly power of God,
out of the reach of their envy,
and all perils and difficulties that attended on their account; who,
as a fixed star in the firmament of God`'s power, did constantly abide,
and held his integrity to the last, being of a sweet, savoury life;
and as to conversation, kept his garments clean: and though outwardly dead,
yet he liveth, and his memory is right precious unto us;
as it is and will be to all that abide in the love of truth,
and have not declined the way of it.
For he was one of the Lord`'s worthies, valiant for the truth upon earth,
not turning his back in the day of battle; but his bow still abiding in its strength, he,
through many hardships, brought gladness and refreshment to Israel`'s camp,
being assisted by the might of that power that always
put the armies of aliens and enemies to flight.
And now having finished his course,
he is removed from us into a glorious state of immortality and bliss,
and is gathered unto the Lord as a shock of corn in its full season,
and to that habitation of safety where the wicked cease
from troubling and the weary are at rest.

[.signed-section-signature]
John Rous, Margaret Rous

[.signed-section-signature]
William Mead, Sarah Mead

[.signed-section-signature]
Thomas Lower, Mary Lower

[.signed-section-signature]
William Ingram, Susanna Ingram

[.signed-section-signature]
Daniel Abraham, Rachel Abraham

[.signed-section-signature]
Abraham Morrice, Isabel Morrice
