== An Epistle by Way of Testimony

[.blurb]
=== To Friends And Brethren Of The Monthly And Quarterly Meetings In England, Wales, And Elsewhere, Concerning The Decease Of Our Faithful Brother, George Fox.

[.signed-section-context-open]
From our Second-day's Morning-Meeting in London, the 26th of the 11th Month, 1690.

Dear and truly beloved friends, brethren and sisters in Christ Jesus,
our blessed Lord and Saviour,
we sincerely and tenderly salute you all in his free and
tender love wherewith he hath graciously visited us,
and largely shed it abroad in our hearts and souls,
to our own unspeakable comfort and consolation,
and towards his whole heritage and royal offspring;
blessed be his pure and powerful name for evermore.
And our souls do truly and fervently desire, and breathe unto the God of all our mercies,
that you all may be preserved,
and kept truly faithful and diligent in his work and service,
according to your heavenly calling and endowments with his light, grace, and truth,
unto the end of your days;
as being livingly engaged thereby all your appointed time to serve him,
and to wait till your change come;
that none may neglect that true improvement of your times and talents,
that God has afforded you here, for your eternal advantage hereafter,
in that inheritance and life immortal that never fades away.
And that the whole flock and heritage of Christ Jesus,
which he has purchased and bought for himself with a price incorruptible,
may always be so preserved in his own pure love and life, as to grow, increase,
and prosper in the same; and thereby be kept in love, unity, and peace with one another,
as becomes his faithful and true followers,
is that which our very hearts and souls desire,
being often truly comforted and enlarged in the living sense
and feeling of the increase and aboundings thereof,
among faithful friends and brethren.

And, dear brethren and sisters, unto this our tender salutation we are concerned,
in brotherly love and true tender-heartedness,
to add and impart unto you some account of the
decease of our dear and elder brother in Christ,
namely, His and His church's true and faithful servant and minister, George Fox;
whom it hath pleased the Lord to take unto himself,
as he bath divers others of his faithful servants and ministers of late time;
who have faithfully served out their generation,
and finished their testimony and course with joy and peace.
Howbeit, O dear brethren and friends I that so many worthies in Israel,
and serviceable instruments in the Lord's hand,
an of late taken away and removed from us so soon one after another,
appears a dispensation that deeply and sorrowfully affects us,
and many more whose hearts are upright and tender towards God,
and one to another in the truth.
The consideration of the depth, weight,
and meaning thereof is very weighty upon our spirits,
though their precious life and testimony live with us, as being of that same body,
united to one head, even Christ Jesus; in which we still, and hope ever shall,
have secret comfort and union with them, whom the Lord has removed and taken to himself,
out of their earthly tabernacles and houses into their heavenly and everlasting mansions.

This, our said dear brother, George Fox, was enabled, by the Lord's power,
to preach the truth fully and effectually in our public meeting in White-Hart Court,
by Gracechurch Street, London, on the 11th day of this instant 11th month, 1690:
after which he said, "`I am glad I was here; now I am clear, I am fully clear.`"
Then he was the same day taken with some illness
or indisposition of body more than usual;
and continued weak in body for two days after, at our friend Henry Goldney's house,
in the same court, close by the meeting-house, in much contentment and peace,
and very sensible to the last.
In which time he mentioned divers Friends, and sent for some in particular;
to whom he expressed his mind for the spreading of Friends' books and truth in the world,
and through the nations thereof;
as his spirit in the Lord's love and power was
universally set and bent for truth and righteousness,
and the making known the way thereof to the nations and people afar off:
signifying also to some Friends, "`that all is well; and the Seed of God reigns over all,
and over death itself: that though he was weak in body,
yet that the power of God is over all,
and the Seed reigns over all disorderly spirits;`"
which were his wonted sensible expressions,
being in the living faith and sense thereof, which he kept to the end.
And on the 13th instant, between the ninth and tenth hour in the night,
he quietly departed this life in peace;
being two days after the Lord enabled him to publish and
preach the blessed truth in the meeting as aforesaid.
So that he clearly and evidently ended his days in his faithful testimony,
in perfect love and unity with his brethren, and peace and good-will to all men;
being about sixty and six years of age (as we understand) when he departed this life.

And on the 16th of this instant, being the day appointed for his funeral,
a very great concourse of Friends and people assembled
at our meeting-house in White-Hart Court aforesaid,
about the mid-day, in order to attend his body to our burying-place, near Bunhill-Fields,
to be interred, as Friends' last office of love and respect due on that account.
The meeting was held about two hours, with great and heavenly solemnity,
manifestly attended with the Lord's blessed power and presence;
and divers living testimonies given,
from a lively remembrance and sense of this his dear ancient servant,
his blessed ministry and testimony of the breaking forth of this gospel-day;
his innocent life, long and great travels, and labours of love in the everlasting gospel,
for the turning and gathering many thousands from darkness to the light of Christ Jesus,
the foundation of true faith; also of his manifold sufferings, afflictions,
and oppositions, which he met withal for his faithful testimony,
both from his open adversaries and false brethren; and his preservations, dominion,
and deliverances ont of them all by the power of God;
to whom the glory and honour was and is ascribed,
in raising up and preserving this his faithful
witness and minister to the end of his days;
whose blessed memorial will everlastingly remain.

He loved truth and righteousness,
and bore faithful testimony against deceit and falsehood, and the mystery of iniquity;
and often, of late time especially, warned Friends against covetousness,
earthly-mindedness, against getting into the earth, and into a brittle spirit;
and the younger sort, against looseness and pride of life, etc.

A few days before he died,
he had a great concern upon his mind concerning
some in whom the Lord's power was working,
to lead them into a ministry and testimony to his truth; who,
through their too much entangling themselves in the things of this world,
did make themselves unready to answer the call and leadings of the power of God,
and hurt the gift that was bestowed upon them,
and did not take that regard to their service and ministry as they ought;
and mentioned the apostle's exhortation to Timothy, to "`take heed to his ministry,
and to show himself approved,`" etc.:
and expressed his grief concerning such as preferred
their own business before the Lord's business,
and sought the advancing worldly concerns before the concerns of truth:
and concluded with a tender and fatherly exhortation to
all to whom God had imparted of his heavenly treasure,
that they would improve it faithfully, and be diligent in the Lord's work,
that the earth might be sown with the Seed of the kingdom,
and God's harvest might be minded by those whom
he had called and enabled to labour therein:
and that such would commit the care of their outward concerns to the Lord,
who would care for them, and give a blessing to them.
However, this is not mentioned to encourage any to run unsent,
or without being called of God.

Many are living witnesses that the Lord raised him up by his power,
to proclaim his mighty day to the nations,
and made him an effectual instrument in our day to turn many from darkness to light,
and from Satan's power to God; and freely to suffer and bear all reproaches,
and the manifold persecutions, buffetings, halings, stonings, imprisonments,
and cruelties, that were in the beginning, and for some time inflicted on him and others,
for the name of Christ Jesus.
He was in his testimony as a fixed star in the firmament of God's power,
where all that be truly wise, and that turn many to righteousness,
shall shine as the brightness of the firmament, and as the stars, for ever and ever.
He knew and preached the mystery of Christ revealed, the life and substance,
and the power of godliness, above all shadows and forms.
The Lord endued him with a hidden wisdom and life.
He loved peace, and earnestly laboured for universal love, unity, peace,
and good order in the churches of Christ; and wherever he met with the contrary,
it was his great grief and burthen.
He was greatly for the encouragement of faithful labourers in the Lord's work;
and it was a great offence and grief to him to have their testimony weakened,
or labours slighted, through prejudice in any professing truth.

And inasmuch as the Lord suffered him not to be
delivered up to the will of his enemies and persecutors,
who often heretofore breathed out cruelty against him, and designed his destruction;
but in his good pleasure so fairly and quietly took him away id his own time,
when his testimony was so blessedly finished, and his work accomplished:
this is all remarkable, and worthy of serious and due observation,
as being by a special and Divine Providence and wisdom of God;
to whom we ascribe the glory of all, and not unto man or creatures.
Though we must needs allow, and own, that good report and due esteem,
which faithful elders, ministers, and servants of God and Christ have by faith obtained,
to the praise of that blessed Power that upheld them in every age in their day;
many whereof are even of late taken away from the evil to come,
and are at rest in the Lord, out of the reach of all envy and persecution,
where the wicked cannot trouble them any more.

And we must patiently bear our parting with them,
and our loss and sorrow on that account, with respect to their unspeakable gain;
yet how can we avoid being deeply affected with sadness of spirit,
and brokenness of heart, under the sense and consideration of such loss and revolutions,
which we have cause to believe are ominous of calamities to the wicked world,
though of good to the righteous?
Did the death of plain upright Jacob, namely, Israel (who was as a prince of God),
so deeply affect both his own children and kindred,
as that they made a great and exceeding sore lamentation for him;
and even the Egyptians also, that they bewailed him seventy days?
and the death of Moses so deeply affect the children of Israel,
as that they "`did weep and mourn for him in the plain of Moab thirty days?`"
and the death of Stephen, that faithful martyr of Jesus, so deeply affect certain men,
fearing God, as "`that they made great lamentation for him?`"
and the apostle Paul, when taking his leave of the elders of the church of Ephesus,
and telling them, "`they should see his face no more?`"
If this did so deeply affect them, that they "`wept all abundantly,
sorrowing most of all for these words,
that they should see his face no more;`" with many more of this kind;
how then can we otherwise choose,
but be deeply affected with sorrow and sadness of heart,
though not as those who have no hope, when so many of our ancient, dear,
and faithful brethren, with whom we have had much sweet society,
are removed from us one after another?
(We pray God raise up and increase more such!) Yet must we all contentedly submit
to the good pleasure and wisdom of the Lord our God in all these things;
who taketh away, and none can hinder him, nor may any say unto him, What doest thou?
Yet we have cause to bless the Lord that he hath of late raised, and is raising up,
more to publish his name in the earth.
And we that yet remain have but a short time to stay after them that are gone;
but we shall be gone to them also.
The Lord God of life keep us all faithful in his holy truth, love, unity, and life,
to the end.
He hath a great work still to bring forth in the earth,
and great things to bring to pass,
in order to make way for truth and righteousness to take place therein;
and that his seed may come forth and be gathered,
and the power and kingdom of our God and of his Christ made
known and exalted in the earth unto the ends thereof.

Dear Friends and brethren, be faithful till death, that a crown of life you may obtain.
All dwell in the love of God in Christ Jesus, in union and peace in him;
to whom we tenderly commit you to keep and strengthen you, bless and preserve you,
to the end of your days.
In whose dear and tender love we remain,

[.signed-section-closing]
Your dear friends and brethren,

[.signed-section-signature]
Stephen Crisp, Nicholas Gates, Daniel Monro

[.signed-section-signature]
Geo. Whitehead, Francis Stamper, John Heywood

[.signed-section-signature]
Fra. Camfield, John Vaughton, George Bowles

[.signed-section-signature]
James Park, Gilbert Latey, William Robinson

[.signed-section-signature]
John Elson, Charles Marshall, William Bingley

[.signed-section-signature]
Peter Price, Rich. Needham, John Butcher

[.signed-section-signature]
John Field, James Martin, Benjamin Antrobus

[.signed-section-signature]
John Edridge

[.offset]
These names are since added, at the desire of the persons following:--

[.signed-section-signature]
Amb. Rigg, Sam. Goodaker, William Fallowfield.

P+++.+++ S.--Before his death he wrote a little paper, desiring all Friends, everywhere,
that used to write to him about the sufferings and
affairs of Friends in their several countries,
should henceforth write to their several correspondents in London,
to be communicated to the Second-day's meeting, to take care that they be answered.
