[#ellwood-testimony.style-blurb, short="Testimony of Thomas Ellwood"]
== Thomas Ellwood`'s Account of that Eminent and Honourable Servant of the Lord, George Fox.

[.offset]
__(It was Thomas Ellwood who first transcribed this Journal for the press.
See Note at p. 11, vol. ii.)__

This holy man was raised up by God in an extraordinary manner, for an extraordinary work,
even to awaken the sleeping world,
by proclaiming the mighty day of the Lord to the nations,
and publishing again the everlasting gospel to the inhabitants of the earth,
after the long and dismal night of apostasy and darkness.
For this work the Lord began to prepare him by many and
various trials and exercises from his very childhood;
and having fitted and furnished him for it, he called him into it very young,
and made him instrumental, by the effectual working of the Holy Ghost,
through his ministry, to call many others into the same work,
and to turn many thousands from darkness to the light of Christ,
and from the power of Satan unto God.

I knew him not till the year 1660;
from that time to the time of his death I knew him well, conversed with him often,
observed him much, loved him dearly, and honoured him truly;
and upon good experience can say, he was indeed a heavenly-minded man,
zealous for the name of the Lord, and preferred the honour of God before all things.
He was valiant for the truth, bold in asserting it, patient in suffering for it,
unwearied in labouring in it, steady in his testimony to it; immovable as a rock.
Deep he was in divine knowledge, clear in opening heavenly mysteries,
plain and powerful in preaching, fervent in prayer.
He was richly endued with heavenly wisdom, quick in discerning, sound in judgment,
able and ready in giving, discreet in keeping counsel; a lover of righteousness,
an encourager of virtue, justice, temperance, meekness, purity, chastity, modesty,
humility, charity, and self-denial in all, both by word and example.
Graceful he was in countenance, manly in personage, grave in gesture,
courteous in conversation, weighty in communication, instructive in discourse,
free from affectation in speech or carriage;
a severe reprover of hard and obstinate sinners;
a mild and gentle admonisher of such as were tender, and sensible of their failings;
not apt to resent personal wrongs; easy to forgive injuries; but zealously earnest,
where the honour of God, the prosperity of truth, the peace of the church,
were concerned; very tender, compassionate,
and pitiful he was to all that were under any sort of affliction; full of brotherly love,
full of fatherly care; for, indeed,
the care of the churches of Christ was daily upon him,
the prosperity and peace whereof he studiously sought.
Beloved he was of God; beloved of God`'s people;
and (which was not the least part of his honour) the common butt of all apostates`' envy;
whose good, notwithstanding, he earnestly sought.

He lived to see the desire of his soul,
the spreading of that blessed principle of divine light,
through many of the European nations,
and not a few of the American islands and provinces,
and the gathering many thousands into an establishment therein;
which the Lord vouchsafed him the honour to be the first effectual publisher of,
in this latter age of the world.
And having fought a good fight, finished his course, and kept the faith,
his righteous soul, freed from the earthly tabernacle,
in which he had led an exemplary life of holiness,
was translated into those heavenly mansions,
where Christ our Lord went to prepare a place for his;
there to possess that glorious crown of righteousness, which is laid up for,
and shall be given by the Lord the righteous judge to all them that love his appearance.

Ages to come and people yet unborn shall call him blessed,
and bless the Lord for raising him up.
And blessed shall we also be, if we so walk, as we had him fur an example;
for whom this Testimony lives in my heart,
"`He lived and died the Servant of the Lord.`"

[.signed-section-signature]
T+++.+++ E.
