[#gf-epistle, short="Epistle of George Fox"]
== An Epistle of George Fox's,

[.blurb]
=== Written with His Own Hand, and Left Sealed up with This Superscription, viz., "`Not to be Opened Before the Time;`" Which After His Decease Being Opened, Was Thought Meet To Be Printed, viz.:--

[.offset]
__"`For the Yearly and Second-day's Meeting in London,
and to all the Children of God in all places in the world.
By and from G. F.__

[.offset]
"`This for all the children of God everywhere, who are led by his Spirit,
and walk in his Light, in which they have life, unity, and fellowship with the Father,
and the Son, and one with another.

"`Keep all your meetings in the name of the Lord Jesus,
that be gathered in his name by his Light, Grace, Truth, Power, and Spirit;
by which you will feel his blessed and refreshing presence among you, and in you,
to your comfort, and God's glory.

"`And now, Friends, all your meetings, both men's and women's, monthly, quarterly,
and yearly, etc., were set up by the power, and Spirit, and wisdom of God;
and in them you know, that you have felt his power, and Spirit, and wisdom,
and blessed refreshing presence among you, and in you, to his praise and glory,
and your comfort; so that you have been 'a city set on a hill, that cannot be hid.'

"`And although many loose and unruly spirits have risen betimes to oppose you and them,
in print and other ways, you have seen how they have come to nought.
The Lord hath blasted them, brought their deeds to light,
and made them manifest to be trees without fruit, wells without water,
wandering stars from the firmament of God's power, and raging waves of the sea,
casting up their mire and dirt;
and many of them are like the dog turned to his old vomit, and the sow that was washed,
turned again to the mire.
This hath been the condition of many, God knoweth, and his people!

"`Therefore all stand steadfast in Christ Jesus, your Head, in whom you are all one,
male and female, and know His government,
of the increase of whose government and peace there shall be no end;
but there will be an end of the devil's, and of all that are out of Christ,
who oppose it and him, whose judgment doth not linger,
and their damnation doth not slumber.
Therefore in God and Christ's light, life, Spirit, and power, live and walk,
that is over all (and the seed of it) in love, in innocency, and simplicity.
In righteousness and holiness dwell, and in his power and Holy Ghost,
in which God's kingdom doth stand.
All children of New and Heavenly Jerusalem, that is from above, and is free,
with all her holy, spiritual children, to her keep your eyes.

"`As for this spirit of rebellion and opposition, that hath risen formerly and lately,
it is out of the kingdom of God and Heavenly Jerusalem;
and is for judgment and condemnation, with all its books, words, and works.
Therefore Friends are to live and walk in the power and Spirit of God, that is over it,
and in the Seed, that will braise and break it to pieces.
In which Seed you have joy and peace with God, and power and authority to judge it;
and your unity is in the power and Spirit of God, that doth judge it:
all God's witnesses in his tabernacle go out against it, and always have and will.

"`Let no man live to self, but to the Lord, as they will die in him;
and seek the peace of the church of Christ, and the peace of all men in him:
for 'blessed are the peace-makers.'
Dwell in the pure, peaceable, heavenly wisdom of God, that is gentle,
and easy to be entreated, that is full of mercy; all striving to be of one mind, heart,
soul, and judgment in Christ, having His mind and Spirit dwelling in you,
building up one another in the love of God, which doth edify the body of Christ,
his church, who is the holy Head thereof.
Glory to God through Christ, in this age and all other ages,
who is the Rock and Foundation, the Emmanuel, God with us, Amen, over all,
the Beginning and the Ending.
In Him live and walk, in whom you have life eternal; in whom you will feel me, and I you.

"`AU children of New Jerusalem, that descends from above, the holy city,
which the Lord and the Lamb is the light of, and is the temple;
in it they are born again of the Spirit; so Jerusalem that is above,
is the mother of them that are born of the Spirit.
They that come, and are come to heavenly Jerusalem, receive Christ;
and he giveth them power to become the sons of God,
and they are born again of the Spirit; so Jerusalem that is above is their mother.
Such come to heavenly Mount Sion, and the innumerable company of angels,
to the spirits of just men made perfect;
and to the church of the Living God written in heaven, and have the name of God,
and of the city of God, written upon them.
So here is a new mother, that bringeth forth a heavenly and spiritual generation.

"`There is no schism, no division, no contention, nor strife, in heavenly Jerusalem,
nor in the body of Christ, which is made up of living stones, a spiritual house.
Christ is not divided, for in Him there is peace.
Christ saith, 'In me you have peace.'
And He is from above, and not of this world; but in the world below, in the spirit of it,
there is trouble: therefore keep in Christ, and walk in Him.
Amen.

"`Jerusalem was the mother of all true Christians before the apostasy;
and since the outward Christians are broken into many sects, they have got many mothers:
but all they that are come out of the apostasy by the power and Spirit of Christ,
Jerusalem that is above, is their mother (and none below her),
who doth nourish all her spiritual children.`"

[.signed-section-signature]
G+++.+++ F.

[.offset]
+++[+++This epistle was read at the Yearly Meeting in London, 1691.]
