== The Appearance Of The Lord`'s Everlasting Truth,

[.blurb]
=== And Its Breaking Forth Again In His Eternal Power, In This Our Day And Age In England.

Wherein the Lord`'s mighty power and word of life hath been richly and freely preached,
to the gathering of many into reconciliation with God by it;
to the exaltation and glory of the great God,
through the bringing forth of the heavenly and spiritual fruits,
from such as have been gathered by his eternal light, power, and Spirit, unto himself.
And by the sowing to the Spirit in the hearts of people, life eternal hath been reaped;
that the flocks have been gathered, which have the milk of the word plenteously;
that the riches of the word have flourished, and mightily abounded;
and God`'s heavenly plough with his spiritual men hath gone on cheerfully,
to the overturning the fallow ground of the hearts,
that had not borne heavenly fruit to God.
And God`'s heavenly thrashers with his heavenly flail,
have with joy and delight thrashed out the chaff, and the corruptions,
that have been a-top of God`'s seed and wheat in man and woman.
And thus have they thrashed in hope, and are made partakers of their hope,
through which God`'s seed is come into his garner.

O! the unutterable glory,
and the inexpressible excellency of the everlasting glorious truth, gospel,
and word of life, that the infinite, invisible, and wise God (who is over all),
hath revealed and manifested I And how have the professors, priests,
and powers risen up in opposition against his children,
that are born of the immortal Seed by the word of God!
And, O! how great have the persecutions, and reproaches, and spoiling of goods been,
that have been executed upon them I But notwithstanding
these sufferings from such as have touched them,
and do touch them, which are as dear to God as the apple of his eye,
how hath the Lord manifested himself to stand by them, in overthrowing powers, priests,
and states I What changes have there been since 1644, and 1650,
and 1652 I How have the jails been filled since
then in this nation with the heirs of life,
God`'s chosen ones,
who had no helper in the earth but the Lord and his Christ I
So that truth`'s faithful witnesses were scarcely to be found,
but in jails and prisons, where the righteous were numbered among the transgressors;
who had neither staff nor bag from man, but the staff, the bread of life,
and the bag that holds the treasure, that waxes not old.
But the Lord Jesus Christ, that sent them forth,
was their exceeding great supporter and upholder by his eternal power and Spirit,
both then and now.

[.signed-section-signature]
G+++.+++ F.
