[short="Particulars of Various Editions"]
== Particulars of the Various Editions of George Fox`'s Journal, etc.

First Edition.::
--Printed for Thomas Northcott. Folio, 1694.

Second Edition.::
--(Generally so called, though not so stated on the title page).
Printed by J. Sowle, in White-Hart Court, in Gracious Street.
London, 2 vols. 8vo, 1709.

Third Edition.::
--Corrected; printed by Richardson and Clarke for Luke Hinde. Folio, 1765.

Fourth Edition.::
--Not known. In a _History of Norfolk,_ it is said Joseph Phipps was
appointed by Friends to abridge the contents and superintend the _Journal of George Fox._
This may have been the fourth edition.

Fifth Edition.::
--Printed by William Phillips, George Yard, Lombard Street,
London (from the first edition, printed for Northcott). 2 vols. 8vo, 1827.

Sixth Edition.::
--Leeds; printed by Anthony Pickard. 2 vols, royal 12mo, 1836.

Seventh Edition.::
--The present; now for the first time divided into chapters and supplied with table of contents,
and numerous notes, biographical and historical, etc., by Wilson Armistead.
Printed and stereotyped by W. G. Blackie and Co., Glasgow. In 2 vols. 8vo, 1852.

[.small-break]
'''

In addition to the above editions of this standard work of the Society of Friends,
several others have been issued at various times which are not enumerated in the count.
Amongst these may be mentioned one called the fifth edition corrected,
printed at Philadelphia in 1808, by Fry and Kammerer, for B. and T. Kite, 20,
North Third Street.
A stereotype edition has been subsequently printed in Philadelphia;
and the first volume of the _Friends`' Library,_
edited by William and Thomas Evans of the same city,
contains an excellent _Memoir of the Life, Travels, and Labours of George Fox._
This volume, a royal 8vo, printed at Philadelphia in 1837,
was reprinted in London in 12mo, in 1839, and again in 1850.
It was also printed in German in 1850.
Both the Memoir in the _Friends`' Library,_
and the Philadelphia stereotype edition of the Journal,
have had a wide circulation in North America.

Many abridged memoirs of George Fox have appeared at various times and in various forms.
_The Life of George Fox_ forms the first volume of Henry Tuke`'s
_Biographical Notices of Members of the Society of Friends,_
a 12mo, published in 1813, and a second edition in 1826.
The second volume of the same work, called _A Supplement to the Life of George Fox,_
containing a brief review of the doctrines and practices inculcated by him,
appeared in 1815, and a second edition in 1826.
The same, in French, was printed at Guernsey in 1824.

_A brief Memoir of George Fox,_ 12mo (supposed by Edward Backhouse),
was printed at Sunderland in 1842, and, with alterations,
was reprinted there in the following year.

In 1847, appeared _A Popular Life of George Fox,_
interspersed with remarks upon the imperfect reformation of the Anglican Church,
and the consequent spread of dissent; by Josiah Marsh, 8vo, 400 pp.,
published by Gilpin, London.
This '`Popular Life`' has been extensively circulated.
Compiled as it is by one not of the Society of Friends,
but a member of the Establishment,
it may be recommended as a fair estimate of the character of George Fox,
by an impartial hand.
Though the work is not quite free from inaccuracies,
the author`'s explanation of many of the most
distinguishing views of Friends is clear and striking;
and on many subjects the writer manifests a remarkable
appreciation of the principles promulgated by George Fox,
and believes them, illustrated as they were in his exemplary life,
calculated to be serviceable to many in his own communion,
in a day when the progress of opinions, tending to exalt outward forms,
draws even the thoughtful and well concerned off from a due
appreciation of the essential spirituality of the Christian religion.

A lengthy review of Marsh`'s _Popular Life of George Fox,_
appeared in the _Westminster and Foreign Quarterly Review_ of July 1847.
This was reprinted in a pamphlet of 72 pp.
12mo, and published by Gilpin, London, in 1848.

In addition to the foregoing, it may be stated, that a 12mo volume, entitled,
Selections from the Epistles of George Fox, was printed at York in 1825,
edited by Samuel Tuke.
A second edition of this, with additions (above 800 pp. 8vo),
was issued in London, in 1848.
These Epistles are not from the Journal, but from a large folio, published in 1698,
entitled, _A Collection of many Select and Christian Epistles,_ etc.

The Introduction to the _Selection of Epistles,_ by Samuel Tuke, is so excellent,
I cannot forbear giving an extract from it in conclusion.
In speaking of George Fox, he says,

[.small-break]
'''

"`The true knowledge of God, not as an intellectual speculation,
but as that which gives rest to the awakened conscience,
was the great object of his longing search from youth to manhood;
and in this search his almost constant companion was the Bible.
There he conversed with Patriarchs and Prophets, with the Lord Jesus and his Apostles,
till he became most intimately imbued with the contents of the Holy Scriptures.
But, though every word of Inspiration was precious to him,
his great desire was to know the mind of the Spirit--the true
harmony of the various parts of the divine records.
He conversed extensively with esteemed religious teachers of various classes,
but he found they were no physicians in his case.
More and more,
he was brought with child-like submissiveness to look to Christ as his only helper;
and thus, after a course of deep spiritual discipline,
his eye was opened more fully to see in the light of the Holy Spirit,
the character of his Saviour, and to rejoice in Him exceedingly.

"`Having partaken largely of the spiritual baptism of his Lord,
many divine truths were opened upon his mind with great clearness.
Unshackled from human ties, and from all the religious systems of men,
the great elements and characteristics of the Christian dispensation,
in its native simplicity and purity, rose gradually before him.
As he travelled onward in his experience,
he found that what was from time to time unfolded to
his mind was in the fullest harmony with Holy Writ.
Many things in the so-called religious world now appeared to him in a new light,
and grieved in spirit with its multiplied corruptions, he felt himself required,
by a divine impulse,
to proclaim to others the Truth which he had found to the blessedness of his own soul.
His great mission was not to found a sect, but to speak truth to all,
and to call all out of every untruth to the knowledge for themselves,
of Him who is the Truth.
The acknowledgment of Christ with the lip as a divine person,
and the talking about faith in Him, and of his various offices,
were prevalent enough in many circles;
but the true belief in Him with the heart unto righteousness--
the acceptance of Him as the only Lord of the soul,
and dependence upon Him for continual guidance by his Spirit--these
were things which appeared to George Fox sadly deficient in his day.

"`As the work of the Holy Spirit on the soul of
man is the great means by which it is stimulated,
and enabled to resist the world, the flesh, and the devil,
so had all these powers combined to stultify its authority,
and to give the name of Christianity to the dogmas or appointments of men,
or too much to limit divine power to the agency of the inspired letter which
the wisdom of man was so able to bend to its own purposes,
but which his unassisted wisdom was wholly unable truly to unfold.
He saw that the corruptions of the Christian Church had always
been indicated by the increase of dependence upon man,
in the work of religion--'`the priests of old time ruled by their means,
and the people loved to have it so.`'
These words appeared to him descriptive of a great human tendency,
forming part of those lusts of the flesh, against which the Holy Spirit ever warreth,
and he spake much of that divine light given to man,
by which the inward working of these lusts was manifested,
and of that inward warfare with the soul`'s enemies,
in which every one must be a soldier for himself,
under Christ his Captain--denouncing all those arts which he saw to be so prevalent,
by which man was persuaded that he could gain the crown,
without enlisting under the banner of the cross.
Man`'s alienation by nature from God, and his reluctance to come to Him in truth,
notwithstanding the drawings of his love, and the free offers of his mercy in Christ,
the propitiation for the sins of the world, were the basis of his appeals.
He was eminently a preacher of the free grace of God to all who repent, and who,
in subjection to his Spirit, truly come unto Christ.
The experimental work of the Spirit in bringing the
soul in living faith to Christ as its Lord and Saviour,
was indeed the great theme of his ministry;
it was that which he felt himself called to urge upon all,
that the foundation might be sound, and the superstructure solid.`"
