[quote.epigraph, , 2 Cor. 4:1-2]
____
Seeing we have this ministry, as we have received mercy, we faint not:
but have renounced the hidden things of dishonesty, not walking in craftiness,
nor handling the word of God deceitfully, not by the manifestation of truth,
commending ourselves to every man`'s conscience in the sight of God.
____

== A Warning to England, / And all that Profess themselves Christians;

[.heading-continuation-blurb]
"`Who have the Form, but deny the Power of Godliness, that they Sin no more,
lest a worse thing come to them.`"--By G. F.

[.heading-continuation-blurb]
"`As ye have received Christ Jesus, the Lord, so walk in him.`" Col. 2:6.
"`For, even our God is a consuming fire.`" Heb. 12:29.

And now, all you that do not walk as you have the apostles for examples,
and do walk as Christ walked, as in 1 John 2:6. If the Lord God Almighty,
who is the Creator of all, and the Lord Jesus Christ, by whom all things were made,
should deal with you, as you deal with him, who spend his creatures upon your lusts,
and devour them, and consume them immoderately: I say if the Lord God,
that created all and gives the increase of all, and upholds all by his word and power,
(for the earth is the Lord`'s, and the fulness thereof,) I say,
if the Lord God should restrain the earth from increasing,
and all other creatures which give your food, for three or four years,
what a condition would you be in, that destroy them so upon your lusts?
If the Lord God should bring a famine;
and stop (I say) the earth from yielding its increase to you,
that so destroy and consume his creatures upon your ungodly devouring lusts;
wasting so much vainly, which would nourish so many both in clothes and diet,
as are ready to famish, and starve for want?
Have not you seen how the Lord God hath brought the sword among you?
And are not you as proud and as vain, without his fear as you were,
though so many have been consumed by sword?
Then did not he bring the plague, and sweep, away many thousands thereby,
and scattered you out of your city of London?
And then after did not he bring the fire, to the astonishment of many?
And what if the Lord should hinder the earth from increasing,
how could you but say it were just with the Lord so to do,
and to bring a famine upon you, seeing that you do not repent, and amend your lives,
and fear and serve him that made you?
and all these good outward creatures he has given to you, and daily gives in his mercy,
that you might serve and fear him, and not to consume them upon your own lusts,
and has given you rain and fruitful seasons;
now what if the Lord should restrain his hand in those things from you,
that do so devour them and consume them, and waste them upon your lusts,
could you say any otherwise, but the Lord is just in so doing?
Seeing that you amend not your lives, ways, words, and doings;
and are such that feast and are feeding yourselves without all fear,
as you may see in Jude 12. and so are the clouds without water, and trees without fruit.
So, if God should send you clouds without water in them, and your trees without fruit;
remember the fig-tree that Christ cursed,
that did not bear fruit and think upon yourselves, and you are all as trees:
but see what fruits of righteousness, of Godliness, of virtue,
and of holiness you bear to God; for,
'`without holiness none shall see God:`' and therefore
take heed of promising yourselves liberty,
whilst yourselves are servants of uncleanness and corruptions,
as in 2 Peter 2. And when you destroy,
consume and devour God`'s good creatures upon your lusts, do you think of God?
Do not you feed without any fear of God?
And do not many live after that sort, as they did that said, '`let us eat and drink,
for tomorrow we shall die?`' as in 1 Cor. 15:42. And doth not the apostle say,
'`That every creature of God is good, and nothing ought to be refused,
if it be received with thanksgiving;
for God hath created them to be received with thanksgiving;
for it is sanctified by the word of God and prayer?`' And now,
when you destroy the creatures upon your lusts, with gluttony, greediness,
and drunkenness, you are not in a capacity then of praying or giving thanks,
but of cursing, swearing, damning, and murdering,
and all other evils you are subject to run into, and then often bring misery,
and many evils upon yourselves and families.

1 Tim. 4. Now, '`Every creature of God is good, +++[+++mark,]
and nothing ought to be refused,
if it be received with thanksgiving;`' for God created them to be received with thanksgiving.
And the thanksgiving must be given to him that created them;
and therefore you ought to receive no creature but with thanksgiving to the Creator,
and you ought to give him thanks that created all to his glory, and if you do not,
you are of them that feed without all fear of God, your and their Creator.
And they that take the creatures in God`'s fear with thanksgiving, will not destroy them,
nor consume them upon their own lusts,
and they are sensible of the goodness of the creatures,
and of the goodness of God that gave them.
And they that feed without the fear, and are the clouds without water,
and the trees without fruit, and devour, consume, destroy,
and waste the creatures of God upon their own lusts, destroy their bodies and souls,
their own families, wives and children, and bring themselves to rags and beggary.

And such are not sensible of the goodness of the creatures,
nor the goodness of the Creator; and from such God had no true thanks,
but his name is blasphemed by such daily: and though many may say,
that '`we say grace before meat and after;`' but you should live in grace,
and not turn from the grace of God into wantonness,
and walk despitefully against the spirit of grace; for the true giving of thanks to God,
is '`with the spirit of grace and supplication.`' Zach. 12:10, and Jude 14.

So they cannot truly give thanks to God, that turn the grace of God into wantonness,
and that walk despitefully against the spirit of grace;
and therefore '`quench not the spirit.`' 1 Thess. 5:19. And the Lord saith,
what hast thou to do to take my name into thy mouth, and hatest to be reformed?
And every one that names the name of Jesus, is to depart from iniquity; else,
Christ will bid such as do not depart from iniquity,
'`depart from him;`' this is a sad sentence, for the Saviour and Redeemer and Mediator,
to bid them '`depart from me ye workers of iniquity, for I know you not:`' so,
though you may say grace (as you call it,) with your lips, yet if you feed without fear,
and work iniquity, Christ will not own such.

And James saith, '`ye have lived in pleasures on the earth,
and in wantonness ye have nourished your hearts,
as in a day of slaughter,`' and so forth:
were not such to '`weep and howl?`' And therefore
do not you think this day will not come upon you,
that are found in these things: therefore be you warned in time.

And doth not the apostle command you, Eph. 5:16, '`to redeem the time,
for the days are evil.`' And therefore see how you can redeem your time that is past;
for does not the apostle tell you what the fruits of the flesh are,
and what the fruits of the spirit?
So see what fruits you bear, and of what sort.

And do not you read in Rom. 1. of such that gave themselves up to vile affections,
and were filled with unrighteousness, fornication, wickedness, covetousness,
full of envy and murder, debate and deceit, taking all things in the evil part,
whisperers, backbiters, haters of God, doers of wrong, proud boasters,
inventors of evil things, disobedient to parents, without understanding,
covenant-breakers, without natural affections, such as never cease from sin,
which men (though they knew the law of God,
how that they which commit such things are worthy of death,) not only do the same,
but have pleasure in them that do them.
Rom. 1. And therefore consider these things, all you who are found in these practises,
and amend, lest God`'s wrath and judgments break forth suddenly upon you,
ere ye be aware.
For, do not you know, that '`the unrighteous shall not inherit the kingdom of God?
Be not deceived, neither fornicators, nor adulterers, nor idolaters, nor wantons,
nor thieves, nor covetous, nor drunkards, nor extortioners, nor railers,
shall inherit the kingdom of God:`' therefore ye must forsake all these things,
if ye expect to inherit the kingdom of God, as you may see in 1 Cor. 4.
do not you read of some,
'`that in words professed God, but in their works denied him?`'
and have not they that professed themselves christians,
brought a great dishonour to christianity, yea, among the very Turks and heathen,
by their drunkenness, whoredoms, and uncleanness, cozening and cheating,
and cursing and swearing, thefts and murders;
so that amongst the Turks it has become a by-word, '`What!
Dost thou think I am a christian?`' Therefore,
oh! that that holy name (whose name is above every name,) by which you are called,
that you should walk so unworthy of it,
as to cause his holy name to be blasphemed! and knowing
there is no salvation by any other name under heaven,
but by the name of Jesus, oh! therefore, that every one that names his name,
would depart from iniquity, and might walk as he walked:
and let your moderation (ye that be called christians,) be known unto all men;
for the Lord is at hand, and sees all things,
and will render unto every man according to his works: and do not you know,
ye must give an account for every idle word?
And therefore, ought they not to be gracious, and seasoned with grace?

And whether, therefore, '`you eat or drink, or whatsoever you do,
do all to the glory of God.`' 1 Cor. 10:31. Now there is no waster, drunkard,
glutton, that can eat and drink to the glory of God; but to the dishonouring God,
devouring and destroying his creatures, and consuming them upon their lusts,
and feeding themselves without the fear of God: and if all christians did mind this,
'`whether they eat or drink,
that they do it to the praise and glory of God,`' there would be no drunkard,
no destroyer, no devourer, nor waster of God`'s creatures found in Christendom.

And likewise, '`whatsoever you do, do it to the praise and glory of God.`' +++[+++Mark,]
'`whatsoever you do:`' in this no christian would dishonour God;
in this they would always have the Lord before their eyes,
and his fear placed in their hearts.

And therefore, whether we live, we should live unto the Lord, and whether we die,
we should die unto the Lord:
so all that are true christians do live and die unto the Lord;
but '`they that live in pleasures, are dead whilst they live,`' as in 1 Tim. 5.

And consider ye what the prophet Hosea saith to the professing Jews,
that did not live according to the law of God, nor the prophets;
and may not the same be said unto you, that profess yourselves christians,
but live not according to the gospel?
'`Saith the Lord, I gave them corn, wine, and oil, and multitude of silver and gold, etc.
And therefore I will return, saith the Lord, and take away my corn in the time thereof;
and my wine in the season thereof; and I will recover my wool and my flax,
given to cover their shame.`'

And therefore, consider this, ye christians, '`what,`' I say,
'`if the Lord should stop the earth from increasing,`' for the Lord hath given you corn,
wine and oil, silver and gold, wool and flax,
which you consume and destroy upon your lusts, the lust of the eye,
the lust of the flesh, and the pride of life, which is not of the Father,
'`so that you should not have so much corn as to feed you,
and as much flax and wool as to cover your shame,`' think you,
would it not be just with the Lord so to do?
Let the witness of God in your consciences, and your daily practice,
and the scriptures answer and testify against you.

For truly, when I was in Lancaster prison,
I looked out of the bars of the window in the tower, and saw the angel of the Lord God,
with his drawn glistering sword, shaking it over this nation,
to execute God`'s vengeance, and the court was all as a flaming fire;
and this I saw before the beginning of the Dutch war, before the plague,
and before the fire: and now I say again, if God Almighty,
that created all for his glory, and gives the increase of all,
(for the earth is the Lord`'s, and the fulness thereof,) and, whether you eat or drink,
or whatsoever you do, you should do it to the praise and glory of God: and now,
if you do not, but consume the creatures of God upon your own lusts,
and with gluttony and drunkenness waste, and destroy them, and live wantonly, wickedly,
and in pleasures on the earth,
which is a mark that such are dead from God and Christ whilst they live: now, I say,
if God Almighty the Creator,
should stop the earth from increasing with cattle and other creatures,
and bring a famine upon you, how could any but say, the Lord is just in so doing?
For, look over Christendom, and see what voluptuousness, drunkenness, excess, rioting,
debauchery, oaths, cursing and swearing, that makes the land to mourn!
Do you think there was the like in Sodom and Gomorrah,
whom God set forth as examples of his wrath,
and such as suffered the vengeance of eternal fire, who followed strange flesh?
Therefore, dread all ye that defile yourselves, and follow after strange flesh; see Jude.
Though you may think ye sit as queens, and glorify yourselves in your pleasures,
and may say in your hearts, ye shall see no sorrow; but alas!
Woe and torment will follow: and therefore, before it be too late, repent,
and consider these things.

And remember Esau, that profane person, who for a morsel of meat sold his birthright,
and afterwards he would have inherited the blessing, but he was rejected;
for he found no place of repentance, though he sought it with tears: and therefore,
while ye have time, repent; for, know ye not, that all that forget God, and do wickedly,
he will turn into hell?
And therefore forsake your wickedness.

And do not you read,
that the Lord Jesus will show himself from heaven with his mighty angels in flaming fire,
rendering vengeance unto them that do not know God,
and which obey not the gospel of our Lord Jesus Christ, +++[+++mark,]
that do not obey the gospel of our Lord Jesus Christ; people may talk of it,
but not obey it;
'`who shall be punished with everlasting perdition from the presence of the Lord,
and from the glory of his power.`' Mark this sentence, and take it to heart,
as in 2 Thess. 1:7:8. And see the sad sentence upon the wicked,
in Matt. 24:51. and 25:41.

And was it not in all ages the sins of the people,
and their committing evil and wickedness in the sight of the Lord,
that brought the wrath, and the plagues, and the sword, and the famine upon them,
as you may read from Moses, in the time of the law,
to the days of Christ and after Christ?
And is it not the same that brings it upon them called christians now,
that make a profession of the new testament, as the Jews did of the old,
and live not according to it?
Oh England! consider these things; oh Christendom, (so called,) consider these things;
and walk honestly, as becomes the gospel, and not in gluttony and drunkenness,
in chambering and wantonness, neither in strife nor envy,
but put on the Lord Jesus Christ, and take no thought for the flesh,
to fulfill the lusts thereof. Rom. 13:13.

'`But unto them that are contentious, and disobey the truth, though they may talk of it,
shall be indignation and wrath,
tribulation and anguish will be upon the soul of
every man that doth evil:`' and therefore take heed,
lest (after the hardness of your hearts,
and your impenitency,) you heap unto yourselves '`wrath against the day of wrath,
and of the Revelation of the just judgment of God:`' take heed of this,
you that deny Revelation; you will find that you will feel it in the end,
if you amend not. Rom. 2.

And therefore, take heed of disobedience, and rebelling against the Lord`'s good spirit,
as in Neh. 9.
For unto them who are disobedient, Christ is a stone of stumbling,
and a rock of offence; and therefore it is not the professing,
but the obedient and believing, to whom he is elect and precious.

'`For behold, saith the Lord, the day cometh, that shall burn as an oven;
and all the proud, yea, and all that do wickedly, shall be as stubble;
and the day that cometh shall burn them up, saith the Lord of hosts,
and shall leave them neither root nor branch.`' Mal. 4.

Therefore consider, all ye that are proud, and do wickedly;
do ye think this day will not come upon you ere you be aware,
and neither leave you root nor branch?
What good will all your profession do you, if ye do wickedly, and are proud,
when ye are found but as chaff and stubble consumed by fire?
Therefore take these things to heart in your private chambers,
and see whether you be not as stubble or chaff:
'`but upon them that fear the name of the Lord, shall the Son of righteousness arise,
with healing in his wings;
and they shall grow up as calves in the stall.`' And therefore, my desire is,
that you may all repent, and amend your lives and doings, and turn to the Lord,
from all your evil ways, words, lives and conversations, and fear him, which to do,
is to depart from evil, that the wrath of God and the Lamb may not come upon you;
for I desire the good of all your souls, and the eternal welfare of all people.

And the apostle saith in 1 Cor. 10.
'`neither let us (to wit, the christians,) commit fornication,
as some of them (to wit, the Jews,) did, and fell in one day three and twenty thousand.`'

'`Neither be ye idolaters, (to wit, the christians,) as some of them were (to wit,
the Jews,) as it is written, the people sat down to eat and drink, and rose up to play.`'

Now, all these things came upon them, (to wit, the Jews,) for example,
and they were written to admonish us, that christians should not follow them.

And the prophet saith, Hab. 2:15. '`Woe unto him that giveth his neighbour drink,
that puttest thy bottle to him, and makest him drunk also,
that thou mayest look on his nakedness; thou art filled with shame for glory:
drink thou also, and let thy nakedness be uncovered;
the cup of the Lord`'s right hand shall be turned unto thee.`' Now consider this,
ye that profess yourselves christians, and live not the life of christianity,
whether ye be not found in these practises that the scriptures declare against.
Hag. 1:6.
'`Ye have sown much, and bring in little, ye eat, but ye are not satisfied;
ye drink, and are not filled; ye clothe you, but you are not warm;
and he that earneth wages, putteth it into a broken bag.`'

Now, is not this the condition of many called christians, that drink,
and are never filled; and eat, and are not satisfied; and earn, but waste their wages?

And in Amos 3:15. and 4:1.
'`I will smite, saith the Lord, the winter-house, and the summerhouse,
and the houses of ivory shall perish, and the great houses shall be consumed,
saith the Lord, hear this word, ye kine of Bastian, that are in the mountains of Samaria,
which oppress the poor, and destroy the needy; and they say unto their masters,
bring and let us drink.`' etc.

Now, consider this, ye that are found in such practises,
and see what judgment the Lord brought against such.

And in Hos. 4:18. there you may see how Ephraim`'s drunkenness stunk;
'`their drunkenness stinketh`', (saith the prophet,) '`they have committed whoredom.`'

And does not the nominal christians`' drunkenness stink, think ye,
together with other their uncleanness?

And in Prov. 20. it is said,
'`wine is a mocker, and strong drink is raging; and whosoever is deceived thereby is not wise.`'

So mark, ye unwise christians, that are found in this raging with this strong drink;
and do ye think that ye are wise, that are deceived with wine the mocker?

And in Prov. 4:14, to 18. '`Enter not into the way of the wicked,
and walk not in the way of evil men, and avoid it, and go not by it, but turn from it,
and pass by; for they cannot sleep except they do evil; and they cause some to fall;
for they eat the bread of wickedness,
and drink the wine of violence.`' Were not these things judged by the law of God?
And are they not judged by the gospel?
and do not you think that the Lord will make such to drink the wine of giddiness?
as in Ps. 60:3, etc.

And in Ps. 80:5. '`Thou hast fed them with the bread of tears,
and gave them tears to drink in a great measure.`' And do ye think that ye christians,
that feed yourselves without the fear of God,
and consume his good creatures upon your lusts, must not be fed with the bread of tears,
and have tears to drink from the hand of the Lord.

And in Isa. 56:12. '`Come ye,`' say they, to wit, the shepherds or the watchmen,
'`I will fetch wine, and we will fill ourselves with strong drink; and tomorrow,
shall be as this day,
and much more abundant.`' And were not these reproved by the prophets?
And are not such reproved now by the gospel?

And in Isa. 27:7-8. '`For all their tables are full of filthy vomitings.`' Now,
look into your houses of drunkenness, ye called christians,
and see what filthiness is there; and by such doings ye devour the creation,
and cause the drink of the thirsty to fail, which would do them good, which you destroy,
and do yourselves hurt withal.

And the prophet Isaiah saith, '`but they have erred because of wine,
and are out of the way by strong drink:
the priests and the prophets also have erred by strong drink;
they are swallowed up with wine, they are gone astray through strong drink;
they fail in vision, they stumble in judgment.`'

Come, try yourselves by these scriptures, ye that call yourselves christians,
and ye priests and prophets;
and see whether by strong drink ye have not stumbled in judgment, and erred in vision,
and are some of you swallowed up with wine?

And does not the prophet cry against the pride and the drunkenness of Ephraim?
And do not many now, that are called christians,
take a pleasure and pride in making others drunk?
And were not such threatened with judgments, and cried against them?
And are not such to be warned now, as then?

And now take heed lest this come upon you as is spoken of in Isa. 24
'`the earth shall be clean emptied, and utterly spoiled, the Lord hath spoken it;
because the inhabitants of the earth have transgressed his laws,
and changed his ordinances,
and broken his everlasting covenant; therefore the curse devours the earth,
and the habitations thereof: then the wine faileth,
and all that were of a merry heart do mourn; the mirth of tabrets ceaseth;
the voice of them that rejoice endeth; the joy of the harp ceaseth;
the earth lamenteth and fadeth away; the world is feeble and decayed;
the proud people of the earth are weakened; they shall not drink wine with mirth;
strong drink shall be bitter to them that drink it; the city of vanity is broken down;
every house is shut up, that no man cometh into it:
there is a cry for wine in the streets; all joy is darkened:
the mirth of the world is gone away:
surely this shall be in the midst of the earth among the people,
as the shaking of an olive tree, and as the grapes when the vintage is ended.`'

Now, consider these things, ye that profess yourselves christians,
and are the transgressors of the gospel, and the commands and law of Jesus,
as the Jews did, the law of God and his ordinances under the old covenant:
do ye think this curse and judgments will not come upon you,
that are found in these practises?

And in Isa. 5.
'`Woe unto them that rise up early to follow drunkenness,
and to them that continue until night, till wine doth inflame them; and the harp, viol,
timbrel and pipe, and wine are in their feasts, but they regard not the work of the Lord,
nor consider they the works of his hands:`' therefore, does not the Lord say,
'`he will lay his vineyard waste, and it shall bring forth briars and thorns.`'

And therefore take heed, ye christians, so called, that practise such things,
lest your vineyard be laid waste also.

And '`woe unto them,`' says the prophet, '`that are mighty to drink wine,
and to them that are strong to pour in strong drink;
which justify the wicked for a reward,
and take away the righteousness of the righteous from him; and call evil good,
and good evil.
Therefore, as the flaming fire devours the stubble,
and as the chaff is consumed of the flame, so their root shall be as rottenness,
and their bud shall rise up like dust,
because they have cast off the law of the Lord of hosts,
and contemned the word of the holy one of Israel:
therefore is the wrath of the Lord kindled against his people,
and he hath stretched out his hand upon them,`' etc.

And now consider ye this that profess yourselves christians,
and are found in these practises;
have not ye cast away the command and law of Jesus Christ,
and contemned his instructions, who says, '`be ye holy, as I am holy;
without which none shall see the Lord:`' and ye ought to walk as Christ walked;
and will not he render vengeance in flames of fire
against all such as obey not the gospel,
and walk not as becomes the gospel?

And did not the Lord bring his judgments upon the Jews for such actions?
And do you think he will clear you of such actions,
because ye make a profession of christianity, and the gospel?
Nay, nay, be not deceived:
God`'s wrath and righteous judgments will be revealed from
heaven against all ungodliness and unrighteousness of men?
And therefore amend and repent, lest these judgments come upon you at unawares:
when you and your priests are crying, '`peace,
peace,`' sudden destruction comes upon you, as it did upon Sodom, and the old world.

And you that be found out of the power of Godliness,
as the Jews were found out of the law of God;
do you think that the stone will not cry out of the wall,
and the beam out of the timber shall answer to it,
against you that delight in sin and wickedness?

'`This vision is plain, saith the Lord; he that runs may read it;
and the vision is for an appointed time, but at the last it shall speak.`' Hab.2.

Therefore while ye have time repent,
and give over pleading for your sin and body of death and wickedness to the grave;
for there is no repentance there; and as the tree falls, so it lies;
therefore cease to sin and break off your iniquities by repentance.
'`For the grave cannot confess to the Lord,
nor death cannot praise him and they that go down into the pit cannot hope for the truth;
but the living, the living shall confess thee, as I do this day;
the father to the children shall declare the truth,`' thus saith Hezekiah, Isa. 38:18-19.

And you may see these evil works and workers before-mentioned, to wit, drunkenness,
uncleanness, etc. are the works of such as go into hell; for the scripture saith,
all that forget God, and do wickedly, shall be turned into hell, as aforesaid;
and so into that which burns with fire and brimstone; and therefore saith the prophet,
hell hath enlarged herself, and opened her mouth without measure;
and their glory and their pomp, and he that rejoiceth among them shall descend into it. Isa. 5:14.
Therefore consider this, all ye drunkards and unclean persons,
that feed yourselves without fear,
and destroy and devour the creatures of God upon your lusts, lest hell swallow you up,
which has opened its mouth without measure; be sure it will,
except you speedily repent and amend your lives and doings, and turn unto the Lord.
Though you may call drunkenness and uncleanness, good-fellowship,
and call others fools that will not follow you into the same excess of riot,
yet it is the bad-fellowship; for the good-fellowship is in the good spirit of God,
which mortifies these evils, and the works of the flesh, which are manifest; as,
adultery, fornication, uncleanness, wantonness, envy, murder, drunkenness, gluttony, etc.
'`whereof I tell you (says the apostle) that they that do
such things shall not inherit the kingdom of God.`' Gal. 5.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Worcester Prison, this 1st of the 11th month, 1674.
