== For All the Bishops and Priests in Christendom,

[.heading-continuation-blurb]
To measure themselves by the scriptures of truth,
and see if they be not reproved by them,
and the Spirit from whence they came.

[.heading-continuation-blurb]
And to all that call themselves papists, bishops, ministers and teachers of the gospel;
and professors in Christendom (so called,)
that say they have not the same power and spirit the apostles had.--By G. F.

[.heading-continuation-blurb]
Read and try with patience, and be not offended at truth.

[quote.section-epigraph]
____
He that hath the form of Godliness, and denies the power thereof,
from such turn away. 2 Tim. 3:5.
____

[quote.section-epigraph]
____
Woe be unto thee that spoilest, and thou wast not spoiled, and dost wickedly,
and they did not wickedly against thee, when thou shalt cease to spoil,
then thou shalt be spoiled, etc. Isa. 33:1
____

[quote.section-epigraph]
____
Woe unto the rebellious children, saith the Lord, that take counsel, but not of me,
and cover with a covering, but not with my spirit,
that they may add sin unto sin. Isa. 30:1.
____

[quote.section-epigraph]
____
Let his habitation be void, and let no man dwell therein,
and let another take his office. Acts 1:20.
____

If you do own God, and Christ, the prophets and apostles,
that God chose and sent to speak, and which Christ chose and sent to preach,
and what they sent them to declare against, are those things to be held up?
And such teachers, which they marked out by their fruits, that we should know them by?
Are they not to be cried against in these our ages, as they did in their ages?

Such as were the sons of Eli, and Eli not restraining their sons,
but honoured his sons above God; therefore the Lord said, 1 Sam. 2:29, etc.
'`He would cut off his arm, and the arm of his father`'s house;
and this should be the sign unto him,
that he would cut off his sons in one day.`' So Eli the priest lost his two sons,
lost his life, lost the ark of God, and lost the priesthood;
and therefore saith the Lord '`I will stir up a faithful
priest that shall do according to my heart and mind,
(to wit, Samuel,) and all that is left in Eli`'s house shall
come and bow down to him for a piece of silver,
and a morsel of bread,`' etc.

Here was the judgments of God upon the unruly and unfaithful priests,
as in the first of Sam. 2.

And when Samuel was old, he made his sons judges over Israel,
and his sons walked not in his ways, but turned aside after lucre, and took rewards,
and perverted judgment, which grieved the good people, and Samuel,
which brought judgments afterwards upon them, as in 1 Sam. 1. and 8.
And Samuel said unto all Israel, in 1 Sam. 12:3, '`Behold, here I am,
bear record of me before the Lord; whose ox have I taken?
Or whose ass have I taken?
Or whom have I done wrong unto?
Or whom have I hurt?
Or of whose hand have I received any bribe to blind mine eyes therewith,
and I will restore it to you again?`' then they said, '`Thou hast done us no wrong,
nor hurt us, neither hast thou taken aught of any man`'s hands,`' etc.
Samuel said unto them, '`The Lord is witness against you,
and his anointed is witness this day,
that ye have found naught in my hands,`' and they answered, '`He is witness.`'

Now, can you priests of Christendom say, as Samuel said here in truth in his old age,
and the people say so of you, as they said here of Samuel, and cleared Samuel, saying,
'`Let the Lord be witness,`' come try yourselves by this scripture;
and by the prophets`' example.

'`And Gehazi, the servant of Elisha, went after Naaman for a reward,
and when he came to him, he asked him whether all was well, and he said to him,
all was well, then said Gehazi, my master Elisha hath sent me, saying,
behold there be come to me even now from Ephraim,
two young men of the children of the prophets, give them, I pray thee,
a talent of silver, and two changes of raiment; and gave him two talents of silver,
and two changes of raiment; and so Gehazi, laid them in his house,
and came and stood before Elisha, and Elisha said unto him, whence comest thou?
And he said, thy servant went no whither, and he said unto him,
went not my heart with thee, when the man turned again from his chariot to meet thee?
Is this a time to take money, and to receive garments, and olives, and vineyards,
and sheep and oxen, and men-servants, and maid-servants?
Then said Elisha to his servant Gehazi,
the leprosy therefore of Naaman shall cleave unto thee, and unto thy seed forever;
and he went out from his presence, a leper white as snow,`' mark ye priests this,
and whether the cause of this leprosy of Gehazi do not stick and remain upon
you who are of his spirit and will take by force from them you do nothing for.

Now Elisha had healed this Naaman of his leprosy,
and Naaman would have given Elisha a reward, and Elisha affirmed he would not receive it,
when Naaman would have constrained him to have received it, but Elisha refused it;
and Naaman would have given Elisha`'s servant something,
but Elisha would not suffer him to give his servant anything,
yet greedy covetous Gehazi his servant run after him with a lie in his mouth,
and received his rewards,
and received thereby the leprosy to himself and his seed forever.

And therefore take heed of Gehazi`'s leprosy in running after gifts and rewards,
ye papists and priests, and other teachers,
and mind also the nobleness of the spirit which was in Elisha,
who refused all Naaman`'s gifts and rewards,
and would not suffer his servant to take any neither, 2 Kings v. and in 2 Kings vi.
Such was the envy of some, that would have taken off Elisha`'s head,
but the Lord prevented them, as in 2 Kings vii.
and the unbelieving prince was trodden to death, according as Elisha prophesied to him.

And as Elisha went through Bethel, the children mocked him,
and two bears came out of the forest and tore in pieces two and forty of their children;
therefore take heed, all ye mockers and people,
how ye suffer your children and yourselves to mock the prophets of God,
who do what they do freely. 2 Kings 2:24.
And in Isa.
lvi. the Lord God sent him to cry against the watchmen, and the shepherds,
and were not these such as pretended to watch for people`'s souls, and to feed them,
think ye?

The Lord saith, which gathereth the scattered of Israel, '`yet will I gather to them,
those that are to be gathered to them,`' all ye beasts of the field come to devour,
yea all the beasts of the forest, +++[+++mark,]
their watchmen are all blind, +++[+++mark,]
all blind, strange watchmen to be all blind, they have no knowledge,
they are all dumb dogs, they cannot bark, they lie and sleep, and delight in sleeping,
and these greedy dogs can never have enough, and these shepherds cannot understand;
for they all look for their own way, every one for his gain from his quarter, and say,
'`come, I will bring wine, and we will fill ourselves with strong drink,
and tomorrow shall be as this day, and much more abundant,`' etc.

Now, are such watchmen and such shepherds as these to be held up,
or to be justified in our days, which the prophet cried against, he says,
'`they are all blind,`' and calls them '`all greedy dumb dogs,
who look for their own advantage,
and seek their gain from their quarter,`' and may not such be so called as do so now,
as you may see in Isa. 56.

And Isaiah saith, Isa. 4:1-2. '`Ho, every one that thirsteth come ye to the waters,
and ye that have no silver buy and eat, come, I say,
buy wine and milk without silver and without price,
wherefore do you lay out your silver and not for bread,
and your labour without being satisfied, hearken diligently unto me,
and eat that which is good, let your souls delight in fatness, incline your ears unto me,
hear, and your souls shall live:`' so the souls do not live without inclining the ears,
and coming unto the Lord, and hearing him.

Now these shepherds and blind watchmen,
which were called the greedy dumb dogs that could never have enough,
they were of another spirit than Isaiah was of,
who may get the form of the true prophets`' words,
but not in the power and spirit that they were in, as many are now.

And in Jer. 5. and in the latter part of the chapter,
'`shall I not visit for these things,`' saith the Lord,
'`shall not my soul be avenged of such a nation as this?
A horrible and filthy thing is committed in the land, the prophets prophesy falsely,
and the priests preach for hire, or bear rule by their means,
and my people love to have it so, what will ye do in the end thereof?`'

And now people consider, is not this a filthy horrible thing committed in the land now,
which Jeremiah the prophet cried against then?
And Jeremiah wept over such, and said, '`Oh!
That my head were waters, and my eyes a fountain of tears,
etc. for they bend their tongues like bows for lies,
but they have no courage for truth.`' Jer. 9.

And again, in Jer. 10:21. '`For the pastors are become beasts,
and have not sought the Lord, therefore have they no understanding,
and all the flocks of their pastures are scattered:`' measure yourselves therefore,
ye pastors of this age with those pastors, and try and see if you be out of their steps.

And in Jer. 13.
There you may see how the priests, and the false prophets,
and all the inhabitants of Jerusalem, and of the land,
how that they were filled with drunkenness,
etc. and how the Lord '`dashed them one against another;`'
and further see the false prophets in Jer. 14.
'`thus saith the Lord, the prophets`' prophecy lies in my name,
for I have not sent them, neither did I command them, neither did I speak to them,
but they prophesy unto you a false vision, and divination, and vanity,
and the deceitfulness of their own hearts, therefore, thus saith the Lord,
concerning the prophets that prophesy in my name, and I have not sent them;
yet they say sword and famine shall not be in the land,
by sword and famine shall those prophets be consumed,
and the people to whom these prophets do prophesy
shall be cast out into the streets of Jerusalem,
because of the famine and the sword, and there shall be none to bury them,
both they and their wives, and sons, and their daughters,
I will pour out their wickedness upon them;`' so see what
judgments came upon these flattering false prophets,
and the people that set them up, and do you think,
that they which hold up such in our days, can they and them escape the hand of the Lord?
Does not many now prophesy and preach in the name of the Lord,
that the Lord hath never sent, nor commanded, nor spoken to them?
Nay, do not they say in plain words there is no hearing of his voice nowadays,
how should he send them then, what can they preach or prophesy?
but a false vision, and a divination, and vanity and deceitfulness of their own hearts,
now as then: so the true must have a command and hear God`'s voice;
the true prophets and preachers that he sends, which deny such as Jeremiah did then.

When Pashur the son of Immer the priest, heard Jeremiah prophesy these things,
he smote Jeremiah the prophet,
and put him in the stocks that were in the high gate of Benjamin,
on the morrow Pashur brought Jeremiah out of the stocks, then said Jeremiah unto him,
'`the Lord hath not called thy name Pashur,
but Magor Missabib,`' which by interpretation is fear round about; '`and thou Pashur,
and all that dwelleth in thy house shall go into captivity,
and thou shalt come to Babylon, and there shalt thou die, and be buried,
and all thy friends to whom thou hast prophesied lies:`'
so there was the end of the false prophet and his friends,
see in Jer. 20. and take heed ye priests of Christendom of this,
that breed up your sons in the way of the false prophets,
who were strikers and persecutors of the true.

'`Woe be unto the pastors that destroy and scatter
the sheep of my pasture saith the Lord;
therefore, thus saith the Lord God of Israel unto the pastors that feed my people,
ye have scattered my flocks and thrust them out, and have not visited them;
behold I will visit you for the wickedness of your works, saith the Lord,
and I will gather the remnant of my sheep out of all countries,
whither I had driven them, and will bring them again to their fold,
and they shall grow and increase, and I will set up shepherds over them to feed them,
and they shall dread no more,`' etc.
So here, the Lord is the gatherer of his sheep unto his fold,
which the false shepherds have scattered and thrust them out of,
whom the Lord will visit; mark ye this, ye papists, priests, etc., of Christendom,
that are found in the work of the false, and give over eating the sour grapes,
and setting your teeth on edge against God`'s sheep, that are gathered into his fold.

And the Lord saith, '`I have seen the foolishness of the prophets of Samaria,
that prophesied in Baal, and caused my people to err;`' and further the Lord saith,
'`I have seen also in the prophets of Jerusalem, filthiness and adultery,
and walking in lies, they strengthen also the hands of the wicked,`' +++[+++mark,]
that none can return from his wickedness,
'`they are all unto me as Sodom,`' says the Lord,
those were sad prophets '`and the inhabitants thereof as Gomorrah;`' sad people,
sad professors.
So measure yourselves ye priests and shepherds, and people nowadays with these,
and try whether ye be in their steps or not?
Therefore, thus saith the Lord of hosts concerning the prophets,
'`I will feed them with wormwood, and will make them drink the water of gall,
for from the prophets of Jerusalem,
(which was the highest place of worship,) is wickedness gone forth into
all the land:`' now this is the food the Lord will feed them withal.
So mark, this is to be your food, who are found in their steps and practice,
you priests in Christendom.

Again, '`thus saith the Lord God of hosts,
hear not the words of the prophets that prophesy unto you, and teach you vanity,
and speak the vision of their own hearts,
and not from the mouth of the Lord;`' and here it is clear we are not to hear
such as do not speak out from the mouth of the Lord which is God`'s command;
and is it not said, that none hath any thing from the mouth of the Lord nowadays,
and there is no hearing of his voice?

Moreover the Lord saith, '`I have not sent these prophets, yet they ran,
I have not spoken to them, yet they prophesy, but if they had stood in my counsel,
and had declared my words to the people,
then they would have turned them from their evil way,
and the wickedness of their inventions.`'

And now here you may see what is the cause that people
are not turned from their evil ways,
and from their wicked inventions, because the prophets run and God never sent them,
and speak, and he never spoke to them, and stand not in the council of God.
Now might not those false prophets say,
'`we have the words of the Lord which Moses and the prophets spoke,`'
as you now say ye have the words that Christ and the apostles spoke,
yet not from the mouth of the Lord?
So would not the true prophets have reproved you,
who are found in the false prophets`' practice?

I have heard saith the Lord, what the prophets said that prophesy lies in my name,
saying I have dreamt a dream: mark, still they go in God`'s name, and use his name,
as all the false doth that God never sent nor spoke unto.

But saith the Lord, '`how long do the prophets delight to prophesy lies,
even prophesying of the deceit of their own hearts;
think they to cause my people to forget my name by their dreams,
which they tell every man to his neighbour as their forefathers have forgotten
my name?`' So it is but the deceit of their own hearts,
and a dream, if it be not from the mouth of the Lord,
though they may run and tell it in the name of the Lord;
'`but the prophet that hath a dream, let him tell his dream, and he that hath my word,
let him speak my word faithfully; what is the chaff to the wheat, saith the Lord?
Is not my word even like a fire, saith the Lord,
and like a hammer that breaketh the stone?
And therefore saith the Lord, behold I will come against the prophets that steal my word,
every one from his neighbour;`' +++[+++mark,]
that steal God`'s words, and therefore consider all you prophets and teachers,
that do not speak from the mouth of the Lord,
do not you steal God`'s words from your neighbour?
Will not the Lord come against you?
For do not you all steal his words that have not the word from the Lord`'s mouth?
then are not you all chaff?
'`Behold saith the Lord, I will come against the prophets which have sweet tongues,
and say, he saith it,`' (to wit, the Lord,) Oh!
Is not this deceit?
And are not many found in this practice?
Try yourselves though your tongues be never so sweet,
and let not means of lucre blind your eyes.

'`And behold, saith the Lord,
I will come against the prophets that prophesy false dreams, and to tell them,
and cause the people to err by their lies, and by their flatteries, and I sent them not,
saith the Lord, nor commanded them; therefore they bring no profit to this people,
saith the Lord.`' And therefore, it is clear those that God commands not, nor sends,
bring not profit to the people then, nor now;
but they feed the people up with flatteries and with lies, therefore examine yourselves,
and your fruits; for the wickedness of these false prophets, and priests and pastors,
and such as followed and held them up,
'`I will bring saith the Lord upon them an everlasting reproach and perpetual
shame that shall never be forgotten,`' as may be seen throughout Jer. 23.
And do you think, that ye that are found in their practises,
that these things are forgotten of the Lord, and that he will not visit you for the same?
And though the Lord sent unto them his prophets and servants rising up early,
but they would not hear, nor incline their ears to obey,
but inclined their ears after those false prophets, priests and pastors;
is it not so now? Jer. 25.
Examine yourselves by the scripture.

'`Then spake the priests and the prophets unto the princes,
that Jeremiah is worthy to die, and he told them,
if they put him to death they would bring innocent blood upon themselves,
and upon their city, and upon the inhabitants thereof;
for of a truth the Lord hath sent me unto you to speak all these words
in your ears;`' and this stopped them from putting him to death,
as you may see in Jer. 26.

And some of the elders said, that Micah prophesied in the days of Hezekiah,
and told him that Zion should be ploughed up like a field,
and Jerusalem should be as a heap,
and the mountains of the house should be as the high place of the forest,
but Hezekiah did not put him to death; and Uriah,
he prophesied against the city of Jerusalem, he prophesied to king Joachim,
and to all his men of power, and princes, and the king sought to slay him,
but Uriah heard it, and went into Egypt, but the king sent for him from thence,
and slew him;
but the hand of Ahikam was with Jeremiah that they
should not give him to the people to put him to death;
and have not many of the priests imprisoned,
and sought the life of many of God`'s prophets nowadays,
that have declared against you the like things?

And Hananiah a false prophet, which took the yoke off Jeremiah`'s neck,
and prophesied lies unto the people, then Jeremiah made him yokes of iron,
and Jeremiah said to Hananiah, hear now the words that the Lord hath sent unto thee,
thou makest these people to trust in a lie, therefore, thus saith the Lord,
I will cast thee off from the earth, this year thou shalt die,
because thou hast spoken rebelliously against the Lord: so Hananiah,
the false prophet died the same year, in the seventh month. Jer. 28.

Again, '`thus saith the Lord of hosts, the God of Israel,
let not your prophets and your soothsayers that be amongst you deceive you,
neither give ear to your dreams which ye dream;
for they prophesy to you a lie in my name;
I have not sent them saith the Lord.`' So their ears are to be unto the Lord,
and not to the dreams of their false prophets, nor their own.

And you may see what became of Shemaiah the false prophet,
who prophesied unto the captivity,
and sent letters in the name of the Lord to them in Babel;
thus saith the Lord +++[+++of Shemaiah,]
'`because he had prophesied unto you and I sent him not,
he hath caused you to trust in a lie, therefore, thus saith the Lord,
I will visit Shemaiah and his seed, he shall not have a man to dwell amongst his people,
neither shall he behold the good that I will do for my people saith the Lord,
because he hath spoken rebelliously against me, saith the Lord.`' Therefore,
see ye priests in Christendom,
how dangerous it is to speak lying words in the name of the Lord, and say,
thus saith the Lord, when the Lord never spoke unto them;
and go about to make him the father of their lies; but such you may see the end of,
which were reproved by the true prophet, Jer. 29.
and such shall not enjoy the good of the land,
though they may haul and pluck from people for a time.
And in Jer. 37:15. where the princes were angry with Jeremiah, and smote him,
and laid him in prison in the house of Jonathan, and put him in the dungeon:
and in the 28th verse, they desired that Jeremiah might be put to death;
for he weakens the hands of the people, then said Zedekiah, the king, behold,
he is in your hands; for the king can deny you nothing,
then took they Jeremiah and cast him into the dungeon of Melachia,
and they let him down with cords into the dungeon, and there was no water but mire;
so Jeremiah stuck fast in the mire, and Ebedinelech, the black-moor,
told the king that they had done evil in casting Jeremiah the prophet into the dungeon,
and he dieth for hunger;
and so here the black-moor had more mercy upon him than his own countrymen,
the professing priests and Jews,
and the king bid the black-moor take thirty men with him,
and take up Jeremiah before he died, and so he took old rags and clouts,
and bid Jeremiah put them under his armholes between the cords,
and so they drew Jeremiah out, as in Jer. 38.
and Jeremiah remained in prison till the children of Israel went into captivity to Babylon,
and Nebuchadnezzar`'s chief steward took Jeremiah in and said unto him,
'`that he loosed him this day from his chain that was on his hands,
and if it please thee to come with me unto Babel, come and I will look well unto thee,
but if not, tarry still, behold all the land is before thee,
whether it seemeth good and convenient for thee to go, thither go.`'

So here is seen the moderation of this heathen to the Lord`'s prophet,
and the fulfilling of the Lord`'s prophets`' sayings
upon all the false priests and prophets;
for he was bound in a chain to have gone to Babylon amongst the rest,
till he understood who he was;
and this chief steward of Nebuchadnezzar did say unto Jeremiah,
'`the Lord thy God hath pronounced this plague against this place,
and now the Lord hath brought it to pass, and done it according as he hath said,
because you have sinned against the Lord, and have not obeyed his voice,
therefore this thing is come upon you.`'

Now here you may see,
here this heathen could see the fulfilling of this word of the
Lord upon the rebellious professing Jews and Jerusalem,
for sinning against the Lord, and not obeying his voice;
and see how this heathen could believe in the Lord, and speak of the Lord,
which had not the scriptures, which was Nebuchadnezzar`'s chief steward, as in Jer.
xl. And have not many of the Lord`'s prophets found
more moderation and civility amongst the heathen,
than from the outside professing christians?

And in Lam. 2:14. where he speaks of the flattering prophets, and saith,
'`Thy prophets have looked out vain and foolish things for thee,
and they have not discovered thine iniquity to turn away thy captivity,
but have looked out for thee false prophecies and causes of banishment.`'
And so instead of discovering to people their iniquity,
which is the cause of captivity and banishment from the Lord,
you teach people to plead for their body of sin, and death, and iniquity to the grave,
when all is buried together, then for ten or twenty shillings give them a funeral sermon.

And in Lam. 4:13. '`For sins of her prophets, and the iniquity of her priests,
that have shed the blood of the just in the midst of her,
they have wandered as blind men in the streets,
and they are polluted with blood.`' See how Jeremiah laments over these poor people,
to whom the false priests and prophets were the cause of so much misery;
and was it not because of those false priests,
scribes and pharisees that destruction came upon
the Jews and Jerusalem in the days of Christ,
who would neither own him themselves, nor suffer others;
and is it not the same cause that brings misery upon all Christendom now,
even the sins and iniquities of the priests and people?

And in Jer. 12. there you may see how the false priests were like to
foxes that worried and destroyed the sheep and lambs;
'`son of man prophesy against the prophets of Israel,
that prophesy out of their own hearts,`' so it was not from the Lord,
'`thus saith the Lord God, woe unto the foolish prophets that follow their own spirits,
and have seen nothing, Oh Israel, thy prophets are like unto foxes in the waste places;
ye have not risen up in the gaps, neither made up the hedges of the house of Israel,
to stand in the battle in the day of the Lord.`' So is not this the mark now
of all the false prophets that follow their own spirits and see nothing,
who say, they have not the same spirit as the prophets and apostles had?
Is not this your confession both in old and new England, and other places?
And how can you make up the hedge, or stand in the gap,
and not be in that spirit and power that the prophets and apostles were in,
but rather make it wider?

But further, the Lord saith concerning the false prophets, '`They have seen vanity,
and lying divination, saying the Lord saith it, and the Lord hath not sent them,
and they have made others to hope that they would confirm the word of their prophecy:
have ye not seen a vain vision, and have not ye seen a lying divination,
and ye say the Lord saith it, when I have not spoken?
Therefore, thus saith the Lord God, because ye have spoken vanity and seen lies,
therefore behold, I am against you saith the Lord.`'

Now here we see such that the Lord hath not spoken to, and the Lord hath not sent them,
yet these false prophets or teachers would father their words upon the Lord,
and will they not do so now?
Saying the Lord saith it, and profess themselves that the Lord sent them,
when the Lord never spoke to them; but the Lord and his prophets are against all such?
And the Lord saith, '`My hand shall be upon the prophets that see vanity and divine lies,
they shall not be in the assemblies of my people,
etc. they shall know that he is Lord;`' and saith the Lord,
'`because they have deceived my people, saying peace, and there was no peace;
one builds up a wall, and behold, the other daubs it with untempered mortar,
and this wall shall fall; for there shall come a great shower,
and I will send hailstones that will cause it to fall,
and a stormy wind shall break it down, and when the wall has fallen, will it not be said,
where is the daubing wherewith ye have daubed it?`'
So God will destroy all these false prophets,
and their wall, and their daubings to the ground,
so that the foundation thereof shall be discovered, and it shall fall and be consumed,
and ye shall know that I am the Lord.

'`Thus saith the Lord, I will accomplish my wrath upon the wall,
and upon them that have daubed it with untempered mortar, and will say unto you,
the wall is no more, neither the daubers thereof (to wit,
the false prophets of Israel,) who prophesied upon Jerusalem,
and seeing visions of peace for it, and there is no peace saith the Lord.`'

So here is the end of the false prophets, and their daubing, and their wall,
who follow their own spirit, and see nothing, and such cannot temper the mortar:
for that is done by God`'s spirit, they must follow that, and they that do,
cry against such as Ezekiel declared against.

And so the son of man was to set his face against
all such as prophesied out of their own hearts,
and such as sowed pillows under the armholes,
that they might lie soft in their sins and wickedness,
and hunted the soul of God`'s people.
And saith the Lord, '`will ye pollute me amongst my people for handsful of barley,
and pieces of bread, to slay the souls of them that should not die,`' etc.

Wherefore thus saith the Lord God, '`Behold, I will have to do with your pillows,
wherewith ye have hunted the souls to make my people fly,
and I will tear them from your armholes,
and I will let the souls go,`' blessed be the Lord, for it is his own work,
which many witness, even the souls that ye hunt to make them fly;
here the Lord rescues the souls out of the snares of the false prophets,
to him be glory forever; '`your veils also will I tear,
and deliver my people out of your hand, and they shall be no more in your hands,
to be hunted, and ye shall know that I am the Lord,
because with your lies you have made the hearts of the righteous sad,
whom I have not made sad, and strengthened the hands of the wicked,
that he should not turn from his wicked way,
by promising him life;`' and this is the work of the false prophet,
that follows his own spirit, that hath not the spirit of God`'s prophets,
to make the heart of the righteous sad, and to strengthen the hands of the wicked,
that they should not turn from their wicked way, promising them life in it,
and teaching them to plead for sin as long as they live;
but the everlasting life is out of it, being turned from the way of the wicked;
and do not you priests nowadays promise them life, though you say,
they must carry their body of sin and death to the grave;
and so are worse than your forefathers, whom the Lord by his prophets declared against.

Therefore saith the Lord, '`Ye shall see no more vanity, nor divine divination,
for I will deliver my people out of your hands,
and ye shall know that I am the Lord.`' So it is the Lord that
delivers his people out of the hands of these false prophets,
that follow their own spirits, and teach for handsful of barley and pieces of bread,
a divination of their own brain, and say,
'`thus saith the Lord,`' when the Lord never spoke unto them, nor sent them;
and many can witness this deliverance of the Lord, blessed be his name forever.
Ezek. 13. Throughout.

And the Lord said also, '`Thou son of man,
the children of my people that talk of thee by the walls, and in the doors of the houses,
and speak one to another, every one to his brother, saying, come I pray you,
and hear what is the word that cometh from the Lord,
for they come unto thee as a people used to come, and my people set before thee,
and hear thy words, but they will not do them, for with their mouths they make Jests,^
footnote:[Heb.]
and their hearts go after their covetousness, and lo,
thou art to them as a jesting song of one that hath a pleasant voice, and can sing well,
for they hear thy words, but they do them not; and when this cometh to pass, for lo,
it will come, then they shall know a prophet hath been amongst them,
when the Lord hath brought his plagues and judgments
upon them,`' as in the aforegoing chapter. Ezekiel 33:31.
And is not this the condition of people now?
and are they not more forward to do the false prophets`' words than the true,
which he speaks from the Lord, and yet will say the good words, but not do them?
And have not you been often warned of this?

And Ezek. 14.
There ye may see the evil shepherds, which Ezekiel was to prophesy against,
'`Thus saith the Lord unto, the shepherds, woe be unto the shepherds of Israel,
that feed themselves; should not the shepherds feed the flocks?
Ye eat the fat, ye clothe ye with the wool, ye fill them that are fed,
but ye feed not the sheep; the weak have ye not strengthened,
the sick ye have not healed, neither have ye bound up the broken,
nor brought again that which was driven away, neither have ye sought that which was lost,
but with churlishness and with rigor have ye ruled them,
(mark here the false prophets`' evil works who left the true work)
and the sheep were scattered without a shepherd and when they were
dispersed they were devoured of all the beasts of the field;
my sheep wandered through all the mountains, and upon every high hill; yea,
my flocks were scattered throughout all the earth,
and none searched nor sought after them; therefore as I live, saith the Lord,
surely because my flock was spoiled,
and my sheep were devoured of all the beasts of the field, having no shepherd;
neither did my shepherds seek my flock, but fed themselves, and not the flock;
thus saith the Lord behold I come against the shepherds,
and I will require my sheep at their hands; +++[+++mark,]
and cause them to cease from feeding of the sheep,
neither shall the shepherds feed themselves any more, +++[+++mark, feed themselves,]
I will deliver my sheep from their mouths, +++[+++mark, from the shepherds`' mouths,]
and they shall no more devour them:`' so here is seen the
marks of those shepherds that devour God`'s people;
come try yourselves ye shepherds, nowadays are not these marks found upon you?

'`For thus saith the Lord, behold, I will search out my sheep, and seek them,
and I will deliver them out of all places where they
have been scattered in the cloudy and dark day,
seek them, and I will bring them out from among the people,
and feed them upon the mountains of Israel, and I will feed them in a good pasture,
in their own fold, and there they shall lie in a good fold, and in fat pasture,
and I will feed my sheep, and bring them to their rest, saith the Lord,
and I will seek that which was lost, and bring again that which was driven away,
and I will bind up that which was broken, and will strengthen the weak,
but I will destroy the fat and the strong,
and will feed them with judgment;`' and this is the Lord`'s work, by his power,
which many can witness, blessed be his name forever;
for the Lord doth judge betwixt sheep and goats: so the Lord is our shepherd,
and we shall not want; and the Lord saith to the false shepherds,
'`seeing it is a small thing unto you to eat up the good pasture,
but you must tread down with your feet the residue of your pasture,
and to have drank of the deep waters, but you must trouble the residue with your feet,
and my sheep eat that which ye have trodden with your feet,
and drink that which ye have fouled with your feet; therefore,
thus saith the Lord God unto them, behold I, even I, +++[+++mark,]
will judge between the fat sheep, and the lean sheep,
because ye have thrust with side and with shoulder,
and pushed all the weak with your horns, till ye have scattered them abroad; therefore,
I will save my sheep, says the Lord, and they shall no more be spoiled,
or a prey unto you; and I will judge betwixt sheep and sheep,
and I will set up a shepherd over them, and he shall feed them, even my servant David,
and he shall feed them, and he shall be their shepherd,
and I will be their God:`' here you may see the Lord God
is drawing and gathering his sheep to Christ Jesus,
the true shepherd, that lays down his life for his sheep; and this many do witness,
that have been scattered, and been made a prey upon by the mouth of the false shepherds,
that have fed themselves,
and have been wandering from mountain to mountain in this cloudy dark day;
but the Lord hath sought them that have been lost,
and bound them up that have been broken, and strengthened the weak,
and hath brought many to the one fold, into his pasture, to the one shepherd,
Christ Jesus, and is bringing others to him; therefore, try yourselves, ye pastors,
whether ye are not found in the steps of those false shepherds`' ways and steps,
which the true prophets cried against.

And Christ saith, '`none can come unto me,
except the Father draw him;`' and the truth of this we witness,
blessed be the Lord forever; '`and as a company of thieves wait for a man,
so the company of priests murder in the way by consent,
for their work is mischief.`' Was not this so in Hosea`'s days,
as you may see in Hosea 6:9. And was it not so in the days of Christ against him?
and is it not so now?
read in Matt. 27.
how early they got up in the morning to work mischief,
for when morning was come they rose up together,
the chief priests and elders to take counsel together to put Christ to death:
and hath not this spirit and practice been found amongst
ye priests and professors nowadays against Christ`'s followers?

And in Amos 7.
see what rage the high priest Amaziah, was in against Amos,
and informed king Jeroboam against him, saying that, '`Amos hath conspired against thee,
O king;`' and warned Amos to be gone into the land of Judah, and prophesy there,
and prophesy no more at Bethel, which was the king`'s chapel and court:
and then Amos the herdsman said to the priest Amaziah that, '`he was no prophet,
but a herdsman,
and a gatherer of figs.`' Here you may see the wrath and
rage of the high priest against the servant of God,
as they do nowadays.

And in Micah 2:11. '`If a man walking in the spirit of falsehood lie, saying,
I will prophesy unto thee of wine, and of strong drink,
he shall even be a prophet for this people.`' These
were the prophets that pleased people then,
and are they not them that do so now?
and such like prophets are not like to turn people to God more now than then.

And in Mic. 3.
see the chapter throughout, and measure yourselves by those priests and prophets,
and see if you be not found in their steps, '`they hatch good,`' saith the prophet,
and love the evil, they pluck off their skins from them,
and their flesh from their bones; they eat also the flesh of my people, +++[+++mark, men eat,]
they flea off their skins from them; and they break their bones, and chop them in pieces,
as for the pot, and as flesh within the cauldron, then shall they cry unto the Lord,
but I will not hear them; he will hide his face from them,
because they have done wickedly in their works.`' Now here
you may see these wicked workers could cry unto the Lord;
they had a profession then, as many in their practice do now.

But, '`thus saith the Lord concerning the prophets that deceive my people,
and bite them with their teeth, +++[+++mark,]
and cry peace, (this is a strange peace,) but if any man put not into their mouths,
+++[+++mark,]
into their mouths,
they prepare war against them;`' and have not we seen this scripture fulfilled,
and daily fulfilling among the priests of Christendom, so called?

'`Therefore, night shall be unto you for a vision,
and darkness shall be unto you for a divination,
and the sun shall go down over the prophets,
and the day shall be dark over them.`' +++[+++Mark,]
ye that are found in these steps; is not the sun gone down upon you all,
and doth not then dark night follow?
Read your condition, and try yourselves.

'`Then shall the seer be ashamed, and the soothsayer confounded, yea,
they shall cover their lips;
for they shall have no answer from God.`' And is
not this one of the doctrines of your faith,
that there is no hearing God`'s voice nowadays, nor no answer from God;
so that you may cover your lips and be ashamed, and say the sun has gone down upon you,
and your day is dark upon you: but Micah saith,
'`truly I am full of power by the spirit of the Lord; and of judgment, and of strength,
to declare unto Jacob his transgression, and unto Israel, his sin,`' etc.
And are not such things to be declared against now,
by them that are full of the power and spirit of God now in Christendom,
as he declared against then.

And saith he, '`they build up Zion with blood,
and Jerusalem with iniquity:`' and may it not be said,
that Christendom is built up with blood and persecution, and with iniquity?
Now is not your Zion and your Jerusalem all on heaps, and like a forest that is barren,
who plead for sin and imperfection to the grave?

'`The heads thereof judge for reward,`' saith Micah,
'`the priests thereof teach for hire, the prophets thereof prophesy for money,
yet will they lean upon the Lord and say, is not the Lord amongst us,
no evil can come upon us?
Therefore shall Zion for your sakes be ploughed up like a field,
and Jerusalem shall be an heap, and the mountain of the house,
as the high place of the forest.`' And now try yourselves, ye priests and prophets,
do not ye teach for hire, and prophesy for money?
and do not you think that your Zion must be turned up like a field with God`'s plough,
and your Jerusalem be as a heap,
and the mountain of your house like the high place of the forest barren,
you being found in the steps of those priests and prophets,
if you believe Micah to be a true prophet,
do not you think those things will come upon you, that he declared?

And in Zeph. 3:4. where he saith, '`her prophets are light and wicked persons,
her priests have polluted the sanctuary,
and they have wrested the law.`' Now measure yourselves with these,
and look into your actions, that profess yourselves ministers of the gospel,
and see if this lightness and wickedness be not found amongst you,
and that your sanctuaries are not corrupted?
And do not you plead for +++[+++term of life,]
a body of sin and death,
and cast the law of the spirit of life which is in Christ Jesus behind your backs,
which makes free from the law of sin and death.

And in Zach. 11. 17.
'`Oh idle shepherds that leave the flock, the sword shall be upon his arm,
and upon his right eye; his arm shall be clean dried up,
and his right eye shall be utterly darkened.`' See here is God`'s
judgments denounced upon the idle shepherds that leave their flocks.
And in the 8th verse, it is said, '`three shepherds did I also cut off in one month,
and my soul loathed them,
and their souls abhorred me.`' Here is the end of such shepherds as abhor the Lord,
and yet pretend to keep his sheep.
Now try yourselves, you priests of Christendom, see if your right eye be not darkened,
and your arm dried up, and then how can you see?

And in Mal. 2. the priests`' lips should have preserved knowledge,
and they should have sought it at the Lord`'s mouth; '`but now, O ye priests,
this commandment is for you, if ye will not hear it,
nor consider it in your hearts to give glory to my name, saith the Lord of hosts;
I will even send a curse upon you, and will curse your blessings, yea,
I have cursed them already;`' mark, because ye do not consider it in your hearts;
therefore, what are your blessings good for, if they be cursed?

'`Behold, saith the Lord, I will corrupt your seed, and cast dung upon your faces,
and you shall be like unto it;`' +++[+++mark,]
like unto dung, which the Lord will cast upon you; and therefore,
all ye priests consider this command, and take it to heart,
who have left the work of God, whose lips should have preserved knowledge,
if ye had sought his law from his mouth; but you say, nowadays,
there is no hearing his voice; then no receiving his law from his mouth, to wit,
the law of the spirit of life which is in Christ Jesus,
whom God hath made a priest higher than the heavens,
whom all people must seek their knowledge from, and salvation from,
for he is their treasure:
here ye may see what judgments came upon the Jews and their prophets, shepherds, priests,
and pastors; and what misery they brought the people into,
and what judgments God sent his prophets to denounce against them, and to disown them,
and what misery he brought them into, that spoke and run, and used their tongues,
and stole God`'s words from their neighbour, when the Lord never spoke to them,
nor sent them: and these were such as taught for hire, and for filthy lucre,
and handsful of barley, and for pieces of bread, and were the flatterers and daubers,
with untempered mortar; and filthy dreamers,
and followed the divination of their own hearts and brains,
and followed their own spirit, seeing nothing, and strengthen the hands of the wicked,
and saddened the righteous, seeking for their gain from their quarter,
where they have got their quarter, there they are seeking for their gain;
speaking peace to people whilst they put into their mouths, but if not,
they prepared war against them, and these turned against the Lords`' prophets,
and cast his law behind their backs, and cast off the Lord,
though they might get the form of words, of the law and of the prophets,
yet out of the life these were all judged, by the Lord,
and his prophets that spoke from the mouth of the Lord;
therefore such cannot be owned now that be found in their steps in Christendom,
and that are found in their practices,
if they own God and his prophets that declared against them,
as you may see in the prophets of the old testament,
and therefore try yourselves by these scriptures.

And now let us see in the new testament what sort
of preachers Christ and the apostles cried against,
and what sort they owned and sent forth.

Christ said, '`Woe unto the scribes and blind pharisees,
which made clean the outside of the platter, and appeared beautiful outwardly,
but inwardly were full of bribery, and excess, and dead men`'s bones,
and filthiness.`' Now these were high professors that had a beautiful outside,
and shined like a cup or a platter on the outside?
And did not many of these professors outstrip many of the
professors of Christ`'s words nowadays in the outside?

Again, Christ speaks to the multitude, and his disciples,
and tells them how they shall know the false teachers with their marks;
'`They bind heavy burden`'s, grievous to be born,
and lay them on men`'s shoulders,`' here is one mark,
but they themselves will not bear them with one of their little fingers;
they will not move that which they lay upon others, and that is contrary to the law;
'`for all their works they do to be seen of men, they make their phylacteries broad,
and make long the fringes of their garments;`' here is another mark,
(by their garments) and doing what they do to be seen,
which these in our days may try themselves by,
whether these marks be not found upon them.

'`They love the chiefest place in feasts,
and to have the chiefest place in the assemblies;`' here is another mark:
'`they love greetings in the market-place, and to be called of men,
rabbi or master.`' Here is another mark.

But saith Christ to his disciples, '`Be not ye called of men master or rabbi;
for one is your master, even Christ, and all you are brethren;
he that is the greatest among you let him be your servant.`'
Here is Christ`'s doctrine to his ministers, Matt. 23.
and the marks or tokens by which people may know the false; and therefore,
try yourselves, ye preachers, and priests in Christendom,
have ye not all these marks and badges, and to be cried against by the spirit?

And the false teachers were such as '`garnished the
sepulchres of the righteous,`' and said,
'`If we had been in the days of our forefathers, we would not have killed the prophets,
or have been partakers with our forefathers in the blood of the prophets;
so then be ye witnesses, saith Christ, unto yourselves,
that ye are the children of them that murdered the prophets.
Oh, generation of vipers!
How can you escape the damnation of hell,`' saith Christ?
And do not many say so now, that are found in the practise of their forefathers,
the scribes and pharisees?

And further, Christ saith, '`Wherefore, behold I send unto you prophets and wise men,
and scribes, and of them ye shall kill and crucify,
and of them ye shall scourge in your synagogues, and persecute from city to city;`' mark,
these were such as Christ should send amongst those professors,
and that was then to be fulfilled,
that upon you might come all the righteous blood that was shed upon the earth, etc.

Now have not many christians in profession,
but not in possession fulfilled these sayings of Christ upon his servants,
in scourging and persecuting, and putting them out of their synagogues in these our days.

And in Matt. 10. where Christ sent forth his disciples to preach, and said,
'`As ye go, preach, saying the kingdom of heaven is at hand;
heal the sick, cleanse the leprous,
cast out devils, freely you have received, freely give,
possess not gold or silver in your purses, nor take a scrip for your journey,
neither two coats, nor shoes, nor staff; for the workman is worthy of his meat;
and into what city or town ye shall come, enquire who is worthy in it,
and there abide till you go thence; and when ye come into an house, salute the same,
and if the house be worthy let your peace come upon it,
but if it be not worthy let your peace return to you again,
and whosoever will not receive you, nor hear your words; +++[+++mark]
nor hear your words, when you depart out of that house or city,
shake off the dust of your feet for a testimony against them; truly I say unto you,
it shall be more tolerable for Sodom and Gomorrah in the day of judgment,
than for that city,`' saith Christ.

'`Behold I send you, as sheep in the midst of wolves, be ye therefore wise as serpents,
and innocent as doves, beware of men, for they will deliver you up to the councils,
and will scourge you in their synagogues, +++[+++mark,]
in their synagogues; ye shall be brought before the governors and kings for my namesake,
in witness to them and to the Gentiles; but when they deliver you up, take no thought,
how or what you shall speak; for it shall be given you in that hour what ye shall say;
for it is not ye that speak,
but the spirit of the Father which speaketh in you.`'
Now mark how Christ sent forth his ministers,
here they were to give freely; for freely they had received of Christ,
and they were not to take gold or silver in their purses, nor scrips,
they were to enquire who was worthy in town or city, and what was set before them,
that they were to eat;
they were not to enquire what benefits or augmentations belonged to such a town or place,
and they were not to go to the magistrates for the bag and their staff,
but who was worthy; and they were to be as innocent as doves;
for they went amongst wolves as sheep: they were to be delivered up before councils,
and scourged in the synagogues; they were to be brought before rulers,
but they were not to take thought or study what to speak;
for it was the spirit of the Father spoke in them.
Now who amongst you in Christendom, goes on in this path of the disciples of Christ,
as you may see Matt. 16. and Mark 6. and Luke 9.
and obey the command of Christ herein.

And in Luke 10. where Christ appointed his seventy disciples,
and sent them out two and two before him, and he said unto them,
'`the harvest is great but the labourers are few, pray therefore,
the Lord of the harvest to send forth labourers into his harvest;`' +++[+++mark,]
pray for the Lord to send them forth, who is the Lord of the harvest;
so these were not to be sent forth by men, but by the Lord of the harvest;
and this was Christ`'s command for his disciples to pray,
and saith Christ to his seventy, '`go your ways,
behold I will send you forth as lambs amongst wolves;`' (mark,
these wolves,) ye professing Jews of the law, and the prophets;
'`carry neither bag nor scrip, neither salute any man by the way,
and into whatsoever house ye enter, say, peace to this house;
and if the son of peace be there, your peace shall rest upon it,
if not it shall turn to you again; and in that house abide,
eating and drinking such things as shall by them be set before you;
for the labourer is worthy of his meat;
go not from house to house.`' So you may see this was their wages,
a little meat and drink; but into whatsoever city ye shall enter, if they receive you,
eat such things as are set before you; heal the sick that are there, and say unto them,
the kingdom of God is come near unto you; but into whatsoever city ye shall enter,
if they will not receive you, go your ways out into the streets of the same city,
and say, +++[+++mark, they were to speak in the streets,]
even the very dust which cleaveth on us of your city, we wipe off against you;
notwithstanding know this, that the kingdom of God is come near unto you; +++[+++mark,]
is come near unto you;
for I say unto you that it shall be easier in that day for them of Sodom,
than for that city; he that heareth you, heareth me, saith Christ;
and he that despiseth you, despiseth me; and he that despiseth me,
despiseth him that sent me; and the seventy returned again from their preaching with joy,
saying, Lord even the devils are subject unto us through thy name, and Christ bid them,
rejoice not in that, but rather because their names were written in heaven;
'`and that same hour Jesus rejoiced in spirit and said, I confess unto thee, O Father,
Lord of heaven and earth, that thou hast hid these things from the wise and prudent,
and hast revealed them to babes, even so Father, because it so pleased thee;
then he turned to his disciples and said, all things are given me of my Father,
and no man knoweth who the Son is, but the Father, nor who the Father is, save the Son,
and he to whom the Son will reveal him; and he turned to his disciples and said,
blessed are the eyes which see what you see.`'

So here you may see how Christ sent forth the seventy disciples,
and how they came again with joy, and how his Father had revealed such things to babes,
and hid them from the wise and learned, and that '`no man knows the Son, but the Father,
and no one knows the Father, but the Son,
and him to whom the Son will reveal him:`' so it is clear
neither learned nor wise know the Father nor Son,
but by Revelation, as may be seen at large in Luke x. Therefore,
all ye teachers in Christendom, come and try yourselves by these scriptures,
and see whether you be not found out of the practice of Christ`'s disciples and ministers,
and disobedient to Christ`'s commands.

And now these seventy, as the twelve,
were not to enquire into what town or city they came,
where was the greatest benefice or augmentation,
and come and tell Christ they had gotten such things; but their joy was,
that he had given them power over the devil:
and Christ said in Luke 22:35. unto his disciples,
'`when I sent you without bag and scrip, and shoes, lacked you any thing?
and the disciples answered him, we lacked nothing.`'

So here you may see, though Christ sent forth his ministers without bag or scrip,
silver or gold, and commanded them to give freely, as they had received freely of him,
yet they wanted for nothing: therefore, consider all you that call yourselves ministers,
that say, ye have not heard the voice of Christ, are not you always in want,
though you have bag and scrip, silver and gold?
And will you go to any place, except there be a great parsonage, or some augmentation;
therefore, measure yourselves with such as Christ sent forth,
and see how unlike you are unto them?
and have not you laid away Christ`'s command, who saith, '`freely you have received,
freely give;`' and how can you receive freely from Christ,
when you never expect to hear his voice, or to be sent out by him?
Therefore, have not you given judgment against yourselves, that you are such as run,
and speak, and use your tongues, and follow your own spirits, and see nothing,
whom God or Christ never hath sent nor spoken unto;
and are not you like the inwardly ravening wolves,
spoken of in Matt. 7:24. that have the outside, the sheeps`' clothing,
the outside of the sheep, but not the life of the sheep;
and so are the thistles and the thorn trees, that bear neither grapes nor figs,
but deceive people with the sheep`'s outside, with which you cover the wolfish nature;
hath not this been seen in Christendom,
who say you have not the same power and spirit the apostles had?
Wherein we do believe you, for your fruits have declared it,
though you may have the outward words of the prophets and apostles,
and worry them that be in the life, as your forefathers did.

And in Matthew, Mark, Luke, and John, ye may see how it was the chief priest,
scribes and pharisees, that were the great professors, with their elders,
that were the chiefest against Christ our Saviour,
as may be seen in Matt. 27:26. and how that they
persuaded the common people against Christ,
and to ask Barabbas, and destroy Jesus; and the chief priests mocked him,
with the scribes and elders of the pharisees.

And in Mark 14.
where they led Jesus away to the high priest,
and how the high priest sought false witness against him, to put him to death.

And in Luke 23.
there you may see how vehemently the high priests and the scribes accused Jesus,
and it was the high priests that delivered Christ to Pilate, John 18:35.
And they were the informers against Jesus; and are not they so now?
Let town and country speak;
and Judas sold Christ for thirty pieces of silver to the chief priests,
and when they had crucified him, they gave large money to the soldiers to say,
'`that his disciples had stolen him away by night,`' as
in Matt. 28:13. So Judas was the first that sold Christ,
and Simon Magus was the second, who would have bought the gift of God,
to have got money by it, and he offered the apostles money to have got that gift;
but see Peter`'s answer, '`thy money perish with thee,
because thou thinkest the gift of God can be bought with money,
for I see thou art in the gall of bitterness, and bond of iniquity,`' etc.,
and therefore consider, all you that say ye have bought the gift,
and it cost your parents a great deal of money, and therefore,
you must have so much a year for it again;
do you think that you are not in the gall of bitterness, and bond of iniquity?
And do not you think that you and your money, and that ye have bought with it, and sell,
will perish together?
Read Acts 8:18. Now you cannot sell Christ, as Judas did, except it be in his members;
for he is risen, though you may sell his words, by which there is more gotten yearly,
with the parsonages, glebe-lands, augmentations, and other revenues,
than by any other trade whatsoever in Christendom;
and how many millions are gotten yearly in Christendom,
(let the arithmeticians cast it up,) by the prophets`',
Christ`'s and the apostles`' words, which they freely spoke forth,
and declared against such as taught for money, and for filthy lucre, and for means,
as you may see both in the old and new testament, how they declared against such;
and ought not such to be declared against now, by them that are in the same spirit?

And Paul in Acts 20:31. tells the elders of the church of Ephesus,
that '`by the space of three years I ceased not to
warn every one both night and day with tears,
(mark, for three years together he did warn these people at Ephesus,)
and I take God to record this day,
(says he,) that I am clear from the blood of all men; for I have kept nothing back,
but have shewed you all the counsel of God; take heed therefore unto yourselves,
and the flock which the Holy Ghost hath made you overseers of; feed the church of God,
which he hath purchased with his own blood;`' +++[+++mark,]
it is the Holy Ghost that made them overseers, and there was their succession;
so they were not made overseers by men;
and so with this Holy Ghost they did oversee and feed this flock, the church,
which Christ is the head of.

And now all you that pretend yourselves to be overseers, and yet say,
there is no having the Holy Ghost nowadays, as the apostles had,
so then you are no true overseers, neither can you feed the church of Christ; for mark,
it was the Holy Ghost that made them overseers;
and they that be the true overseers must succeed them in the Holy Ghost,
and be made overseers by it,
for the apostle said after his departure from the church at Ephesus,
where he had been for the space of three years,
'`grievous wolves should enter in among them,
not sparing the flock;`' and those wolves should come with the form of godliness,
and with the sheep`'s clothing, but inwardly ravened from the holy spirit of God;
but he '`commended them to God, and to the word of his grace,
which is able to build them up,
and to give them an inheritance amongst all them that are sanctified.`'

And Paul tells the Ephesians further, '`I have coveted no man`'s silver, nor gold,
nor apparel,`' though he had preached amongst them three years, as aforesaid;
'`ye know`' says he, '`that these hands have ministered unto my necessities,
and unto them that were with me.`'

And now ye old and new England professors and others, that say,
there was no need for Paul to have a settled maintenance,
because he travelled up and down;
so now here you may see where Paul was three years together,
and yet coveted no man`'s silver, nor gold, nor apparel; and moreover, said he,
'`ye know that these hands have ministered to my necessities,
and to them that were with me,
for the space of three years;`' for you never read
here that he sued any man for tithe or means,
he was not like, who laboured with his hands.

And further Paul saith, '`I have shewed unto you all things;`' mark,
how that so labouring he ought to support the weak,
not to destroy the weak through covetousness; and Paul saith,
'`remember the words of our Lord Jesus, how he said, it is a blessed thing to give,
rather than to receive:`' come ye priests and professors,
try yourselves with Paul`'s practice here, and with this scripture, Acts xx.
and try yourselves by Christ`'s command, which he gave to his ministers and messengers,
'`freely ye have received, freely give;`' you say the scripture is your rule,
come try yourselves by your rule; for if you will not try yourselves by it,
others will try you by it; do you freely give?
Do you covet no man`'s silver, gold or apparel?
Do ye labour with your own hands, to supply your own necessities and others?
He that was clear of the blood of all men,
and declared unto them the whole counsel of God, did this; yea,
for the space of three years to the church at Ephesus;
besides many other places that he speaks of, amongst whom he was a witness of Christ:
but let the jails and the jailers,
and the baliffs and sheriffs witness against you for them, whose goods you have taken,
that you never did any work for.

And in Acts 28:30. where Paul ye may see remained two full years in his hired house,
and received all that came in to him, preaching the kingdom of God,
and those things which concerned the Lord Jesus Christ,
with boldness of speech without let among the heathen Romans; I say, this was Paul,
that coveted no man`'s silver, nor gold, nor apparel,
which preached among the Gentiles at Rome, he had no monastery nor abbey,
nor great steeple-house to preach in then, nor set wages,
nor did he sue people for maintenance or tithe, to cast his hearers into prison,
because they would not give him such things, if you say he did,
let us see your proof for it in scripture.

And now if you should object and say, '`custom to whom custom,
and tribute to whom tribute;`' this did relate to the magistrates,
which were for the punishment of the evildoers,
and were for the praise of them that do well, such things we were never against,
paying for conscience sake; but this in Rom. 13.
is nothing to justify hirelings, and to oppose Christ`'s command, which is,
'`freely ye have received, freely give;`' for the apostle Paul saith in Rom. 16.
'`now I beseech you brethren, mark them diligently who cause divisions and offences,
contrary to the doctrine which ye have learned, and avoid them; +++[+++mark,]
for they are such as serve not the Lord Jesus Christ, but their own bellies,
and with fair speeches and flattering words deceive the hearts of the simple;`' come,
try yourselves, ye teachers by those scriptures; is it not you who make the division,
who have got the flattering and fair speeches, deceive the hearts of the simple,
who serve not the Lord Jesus Christ, but your own bellies?
Is it not your bellies that you serve with your great parsonages, and glebe-lands,
and augmentations, Easter reckonings, and midsummer dues?
For if you did serve the Lord Jesus Christ, then you would obey his command, which is,
'`freely you have received,
freely give,`' and not persecute and cast in prison such as will not put into your mouths;
and if your parsonages and rich benefices should be taken away,
then it would be seen how many servants Christ would have amongst you?

And Paul preached at Corinth a year and a half,
and taught the word of God among them freely.
Acts 18:11; 1 Cor. 1:9.

And Paul wrought with Priscilla and Aquila at Corinth,
who were of the same craft as Paul was of; for their craft was to make tents,
and he abode with them as aforesaid:
nevertheless Paul preached up and down in the Jews`' synagogues,
testifying to them that Jesus was the Christ;
and now compare your practice with Paul`'s and Priscilla`'s and Aquila`'s, ye priests;
for though he was a tradesman, yet he preached the gospel:
and this Priscilla and Aquila were both instructors of Apollos concerning Christ,
as in Acts 25. of whom Paul was a minister.

And often you priests have brought Ananias and Sapphira
his wife for proof for your maintenance,
against such as keep back your tithes,
because they kept away part of the price of their goods,
and laid it not down at the apostles`' feet,
which comparison or instance is an unequal weight or measure;
for Peter did not desire it, nor the apostles,
whilst it remained in their hands they might have kept it all,
and not have sold their goods; for the apostles did not desire it,
nor coveted any man`'s gold or silver,
but their wilful and wickedly lying against the Holy Ghost,
and their agreeing together in lying, brought the judgment of God upon them,
and this is nothing for your purpose; but take heed,
lest the same judgment overtake you for lying against the spirit of God in your consciences,
and doing that which you know you should not, and saying that which you are not,
as you may see in Acts v. And whereas you quote,
that the christians sold all their goods in the primitive time,
and brought in the price thereof, and laid it down at the apostles`' feet;
this was a voluntary act in them, it was not done by compulsion from the apostles,
nor by their desire, neither was it done altogether for the apostles`' use,
but for the supply of all such as were in necessity amongst them;
and tithes in the time of the law were not for the
priests`' and the Levites`' own use only,
but for the widows, strangers, poor, and fatherless.

And in Luke 5. '`Jesus entered into the ship which was Simon
Peter`'s and bid him thrust off a little from the land,
and Jesus sat down, and taught the people out of the ship; and when he had done speaking,
he said unto Simon, launch out into the deep, and let down your nets to make a draught,
and they enclosed a multitude of fish, though before they had been toiling all night,
and caught nothing; so that their net was ready to break,
and they beckoned to their partners which were in the ship,
that they should come to help them, who came, and they filled both their ships,
so that they began to sink.
Now when Simon Peter saw it, he fell down at Jesus`' feet, saying, Lord go from me,
I am a sinful man, for he was utterly astonished, and all that were with him,
for the draught of fish which they had taken, and so was also James and John,
the sons of Zebedee, which were partners with Simon, then Jesus said unto Simon,
fear not, from henceforth thou shalt catch men, and when they brought the fishes to land,
they forsook all and followed him,`' to wit, Jesus.
Here you may see what manner of men were Christ`'s disciples, fishermen,
etc. and Christ preached in Peter`'s ship,
and Peter the fisherman did catch many men according to Christ`'s words,
as when he converted three thousand at one sermon, as in Acts 2:41.

And the magistrates perceived that Peter and John were unlearned men,
and could not read letters, but they took knowledge they had been with Jesus,
who is the true teacher, as in Acts 4:13. If they had been in your days,
would not you have mocked at them, as the letter professing Jews did?
And do not you do the same to such now?
And Peter and the other disciples did abide with Christ: and after Jesus was risen,
there were together Simon Peter, and Thomas called Didimus, and Nathaniel of Cana,
in Galilee, and the sons of Zebedee, and two other of his disciples,
and Simon Peter said to them, I go a fishing, and they said unto him,
we go also with thee; and they went straightway and entered into a ship,
and that night caught they nothing, but when the morning was come,
Jesus stood on the shore, and the disciples knew not that it was Jesus,
and Jesus said unto them, sirs, have ye any meat, and they answered him no;
then he said unto them, cast out the net on the right side of the ship,
and ye shall find; so they cast out,
and they were not able to draw it for the multitude of fish; therefore,
said the disciple whom Jesus loved, it is the Lord;
and when Simon Peter heard that it was Jesus, he girt his fisher`'s coat unto him;
for he was naked, and cast himself into the sea,
but the other disciples came in the ship, for they were not far from land,
but about two hundred cubits, and they drew the net with fishes to land.`'

Now, you may see here the apostles what plain men they were,
and Peter was in his fisher`'s coat after Christ was risen,
who had been a preacher of Christ a great while from his conversion, for several years,
till Christ was crucified, who saw Christ`'s miracle before he was converted,
and now again after he was risen, as in John xxi.
And so Peter and John, and the other disciples,
who had been toiling all night before their conversion, and after Christ was risen,
but caught nothing, but at Christ`'s words they did, even to their astonishment;
and that might let them see the truth of Christ`'s words,
that a sparrow should not fall to the ground without the will of the Father,
so a fish could not be caught in the net without the will of Christ,
by whom all things were made.

But here you may see that Peter and John, and the sons of Zebedee,
they were fishermen before they were converted, and after Christ was risen,
and were partners, and went a fishing together, as in Luke v. and John xxi.
And would not such preachers and such disciples be odious nowadays to you priests,
as they were to the high priests, and pharisees, and council,
and the rulers who cast them in prison,
and commanded them to speak no more in the name of Jesus, as you may see in Acts iv.
and v. and consulted to slay them, but that Gamaliel moderated the priests and council;
and so when they had scourged the apostles they let them go:
so here was the fulfilling of Christ`'s words, who told them before,
that for his namesake they should be had before the rulers, and scourged.
And now consider, ye that are called ministers and priests, and others,
are ye found in the spirit of the apostles, or in the spirit of those that scourged?
And does not there want a Gamaliel amongst you to moderate you?
and did not the priests and rulers in New-England want a Gamaliel amongst them,
to moderate them, when they put our friends to death;
and have not the papists and protestants wanted a Gamaliel amongst them,
who have caused so many to suffer since the apostles`' days, and to say unto you,
'`if it be of God it shall stand, let these men alone,
lest ye be found fighters against God?`'

Again, consider ye priests and others, and measure yourselves,
who say the scripture is your rule, whether you be in the priests`' spirit,
and Saul`'s unconverted, with his packet of letters,
and from that spirit gave forth such commissions to your souls,
to haul and bind the true christians, and bring them to prison;
are not such persecutors of Christ`'s seed, Acts ix.
Why persecutest thou me?`' and after Saul was converted and became a Paul,
did not the unconverted priests and Jews seek to destroy him, and to stone him,
as may be seen in Acts 14.
though they were professors of the letter of the old testament,
as you are of the letter of the new.

And Paul said,
how the chief priests and elders could bear him witness how he persecuted the churches,
Acts 22. and Acts 23.
it may be seen how the high priests and others were vehement in accusing of him,
and in Acts 25. the high priests and chief of the Jews appeared against Paul;
and above forty men had bound themselves with an oath,
they would neither eat nor drink till they had destroyed him,
and this they told to the chief priests and the elders, and said unto them,
'`now therefore, ye (to wit, the chief priests and elders,
and the council,) signify to the chief captain,
that he bring him forth unto you tomorrow,
as though ye would know something more perfectly of Paul.`'
So see the design of the Jews and chief priests here to kill Paul,
which God did prevent;
for he had been in profession with them whilst he was a persecutor;
but now he was a professor of Christ, what a madness was in them against Paul,
as there was in him against others before his conversion:
and now see if you be not in the same spirit and way of madness,
that are professors of Christ, but without possession of him,
and like Saul and the chief priests, and not like converted Paul;
which of these ways are you in?
Does not your fruits bespeak you?
Measure yourselves, and try by the scripture, which you say is your rule,
which spirit you are guided by.

And in 1 Cor. 9. '`Who goeth a warfare at his own cost?
Who planteth a vineyard and eateth not of the fruit thereof?
Or who feedeth a flock,
and eateth not of the milk thereof?`' And '`thou shalt not
muzzle the mouth of the ox that treadeth out the corn, etc.
He that plougheth, plougheth in hope,
and he that thresheth in hope should be a partaker of his hope:
if we have sown unto you spiritual things, is it a great thing,
if we reap your carnal things, if others with you be partakers of this power,
are not we rather?
Nevertheless,`' saith the apostle, '`we have not used this power,
but suffered all things, that we might not hinder the gospel of Christ.`'

Now these are the scriptures ye priests bring for your maintenance; but come,
measure yourselves; how can you sow spiritual things, as the apostles did,
who say you have not the same spirit and power they had,
then can you reap their carnal things;
for the apostle had the spiritual flail to thresh God`'s wheat out of the chaff,
the corruptions, the body of death, and the body of sin,
which you plead for term of life;
and the apostles had the spirit to war the spiritual war,
but you that have not the same spirit they had, you cannot war the spiritual war;
and they had the spirit of God to plant God`'s vineyard,
and you that have not the same spirit they had, cannot plant such vineyards,
and therefore cannot eat the spiritual fruit; and the apostles with the Holy Ghost,
which made them all ministers and overseers, with it did feed the flock,
and these might eat of the milk; and the apostles did tread the corn out of the chaff,
that he said to some, they were elected before the world began,
but you that deny having the same spirit the apostles had, you cannot tread out the corn,
and eat of the milk of that flock, which the Holy Ghost oversees;
and the apostles had the heavenly plough to turn up the fallow ground,
that did not bear fruit unto God;
but though the apostles had this heavenly plough to plough withal,
the heavenly flail to thresh out the wheat, yet he told the church at Corinth,
he had not used his power amongst them,
though he had been there amongst them a year and six months.

And now ye that say ye have not the same power and Holy Ghost the apostles had;
look what carnal ploughs, flails, and vineyards and flocks ye have;
and do not you plough large furrows upon the righteous`' backs,
and your own ground lies fallow, full of thistles and briars, and your vineyards waste,
and you run to other vineyards, and have no fruit in your vineyards,
nor milk in your flocks, but what you lug out by laws;
and must not the mouth of the ox be muzzled that doth not tread out the corn?
But the apostle would not use his power (who did tread out
the corn) amongst them he had begotten and converted,
but you will use your power amongst them, ye have neither begotten, nor converted, yea,
and cast into prison, if they will not give you maintenance, so,
where did the apostles ever do so?
Measure yourselves.
and your practice by the scriptures, which you say is your rule?

And further the apostle saith, '`they that ministered about the holy things,
eat of the things of the temple;
and they which wait at the altar are partakers of the altar:
so also hath the Lord ordained that they which preach the gospel,
should live of the gospel; +++[+++mark]
what was it that the Lord ordained when he sent forth his disciples,
what is set before you that eat; for the workman is worthy of his meat;
and freely you have received, freely give,
this is Christ`'s first ordination to his ministers, but the apostle saith,
I have used none of these things, neither write I these things as before-mentioned,
that it should be so done unto me; for it is better for me to die,
than that any man should make my rejoicing vain; for though I preach the gospel,
I have nothing to rejoice of; for necessity is laid upon me,
and woe is unto me if I preach not the gospel; for if I do it willingly, I have a reward,
and that was not outward things, for he had denied them before;
but if I do it against my will, notwithstanding a dispensation is committed unto me,
what is my reward then?
Verily, that when I preach the gospel, I make the gospel of Christ free without charge,
that I abuse not my authority in the gospel.`' And now consider ye priests in Christendom,
and measure yourselves here with the apostle; have you nothing for preaching the gospel,
and yet woe unto you, if you do not preach the gospel?
And have you kept the gospel free without charge?
Is this your reward?
and have not you abused the authority of the gospel?
let your fruits speak, who say the scripture is your rule for your life and doctrine,
therefore try your life and doctrine by it,
and see if your gospel be free without charge, as Paul`'s was; and if it had been so,
then you had not spoiled people`'s goods, and cast them into prison unto death;
do not your deeds testify otherwise?

And the apostle saith, '`Though I am free from all men,
yet have I made myself servant unto all men, that I might win the more.`' See,
he did not make himself a master, but a servant; try yourselves by this,
and see whether this scripture be your rule or no, and whether you are not judged by it,
and Christ, and the apostles?

And in 2 Cor. 9. which is the scripture you priests use to bring to prove your maintenance by,
where the apostle speaks concerning ministering to the saints,
and where he thanks God for his unspeakable gift,
and this is nothing to serve for you to prove your forced maintenance by,
and to force a maintenance from people by; for the apostle says,
'`As every man is persuaded in his heart, so let him give, not grudgingly,
but of a cheerful heart,
for God loveth a cheerful giver;`' so here the church was left to their freedom;
but you dare neither trust God nor the church for your bellies;
but try yourselves and your practice by this scripture.

And again, in Phil. 4. you bring this where the apostle saith,
'`When I was in Thessalonica,
ye sent once and again for my necessity, not that I desired a gift,
but I desired the fruit, which may farther abound to your account;
now I have received all, and have plenty; I was even filled,
after that I had received of Epaphroditus that which came from you,
an odour that srnelleth sweet, a sacrifice acceptable and pleasant to God,
and my God shall fulfill all your necessities through his riches and glory in Jesus Christ.

Now measure yourselves by this scripture, ye priests of Christendom,
and see if ye be equal with the apostle, who did not desire a gift;
for this is nothing for your purpose to force a maintenance from people by;
he desired only the fruits of his vineyard which he had planted,
which was as a sweet smelling sacrifice to God;
for he learned to be full and to be hungry, and to be abased, and to abound,
and also to want, he had learned this lesson of Christ,
which ye have not yet learned at your schools,
and you are never like to learn it of Christ,
if ye say there is no hearing of his voice nowadays.

And in 1 Thes. 4. the apostle writes, and saith, '`That ye study to be quiet,
and to meddle with your own business, and to work with your own hands, as we command you,
and that you behave yourselves honestly towards them that be without,
and that nothing be lacking among you.`' And in 2 Thes.
'`We are persuaded of you through the Lord,
that ye both do and will do the things which we command you,
for ye yourselves know how that ye ought to follow us;
for we behaved not ourselves inordinately amongst you +++[+++mark]
neither did we eat any man`'s bread for nought; but we wrought with our hands,
and travelled night and day, because we would not be chargeable to any of you,
not but that we had authority,
but that we might make ourselves an example for you to follow us;
for even when we were with you, this we warned you of,
that if there were any that would not work, he should not eat;
for we heard that there are some that walk among you inordinately, and work not at all,
but are busybodies; therefore, they that are such we command +++[+++mark,]
and exhort by our Lord Jesus Christ, that they work with quietness,
and eat their own bread.`'

Come, all ye priests and teachers in Christendom, measure yourselves here,
and try yourselves whether ye observe the apostles`' command here,
and have him for your example, and whether ye be the successors of him in his example;
the apostle did choose to work day and night,
rather than he would be chargeable to the church; but are not you chargeable,
that throw in prison and spoil people`'s goods that ye do not preach to?
How dare you say the scripture is your rule, and that you are successors to the apostles,
when your lives and practice speak quite contrary?
And you are to study to be quiet, find with quietness to eat your own bread,
and not another man`'s, and especially them that ye do no work for;
for you would think it an unreasonable thing for
a tradesman to come unto you for money for his ware,
from whom you had no work, and force you to give him money for it,
or to throw you into prison?
And then is it not as strange for you to ask people for money,
that have had none of your ware, and if they will not give it you throw them into prison?
Is this your studying to be quiet, and labouring with your own hands,
and eating your own bread with quietness?
I think not; and doth not the apostle say, '`if any man obey not our sayings or command,
mark, +++[+++or note,]
him, and have,
no company with him that he may be ashamed;`' mark this all ye
that disobey Christ`'s and the apostle`'s command also.

In 1 Tim. 3:1. This is a true saying, '`if a man desire the office of a bishop,
he desires a good work:`' so now ye bishops and elders,
who say the scripture is your rule, come and be tried by this scripture,
you that desire this office, this good work.

[.numbered-group]
====

[.numbered]
_First._
A bishop must be unreprovable and blameless; are you so?

[.numbered]
_Secondly._
He must be the husband of one wife, watching, sober, modest, given to hospitality,
apt to teach: now mark, are ye found in these practises?
Let your fruits and the consciences of people speak.

[.numbered]
_Thirdly._
'`Not given to wine, no striker, +++[+++mark, no striker nor persecutor,]
not given to filthy lucre, but gentle, no flatterers, not covetous;`' so consider,
ye bishops in Christendom; are ye no strikers, not given to wine nor filthy lucre?
Are you gentle and not covetous, nor fighters?
let the country and your consciences, and your fruits speak,
and God and the scripture judge.

====

Further, a bishop must be one that can rule his own house honestly,
having children under obedience with all honesty; for if he cannot rule his own house,
how shall he take care for the church of God; he must not be a young scholar,
lest he be puffed up; he must also be well reported of them which are without,
lest he fall into rebuke and snare of the devil.

And now come try yourselves, ye bishops, by these scriptures;
do you rule your own house well?
Are your children under obedience with all honesty?
Look into your families; are you no fighters nor strikers?
Are you not covetous, and given to filthy lucre?
And if ye cannot rule your own house well, how can ye rule the church of God?
And let the prisons testifiy if ye priests and ministers be not covetous;
and are you and they of a good report without?
How can that be, when you take people`'s goods from them, and cast them into prison,
that doth not hear you?
And doth not this bring a bad report upon you?

And doth it not show that you are puffed up, and that you are fallen under rebuke,
and the snare of the devil; let your consciences, and your fruits, and the prisons,
and them that are without, and the scripture speak,
which you call your rule to be tried by, and God and Christ judge.

Likewise, deacons must be grave and honest, come,
let the deacons be tried by scripture also, not double-tongues,
(they must not be double-tongued, take notice) not given to wine nor filthy lucre,
(mark the deacons,) having the mystery of faith in a pure conscience;
likewise their wives must be honest, not evil-speakers,
but sober and faithful in all things; come, try your wives here, ye bishops and deacons.
And likewise, ye deacons, ye are to be the husband of one wife, as the bishops must,
to be the husband of one wife, and such as can rule their children well,
and their own household; so mark, and look into your households, and among your children,
and see how they are ruled: but you bishops, whether papists or others,
who not only tie yourselves from marriage, but also forbid it to priests and bishops,
how do you succeed the apostles or those primitive bishops therein?
Do not you do worse?
And is not that contrary to the apostle`'s doctrine,
who calls it the doctrine of devils to forbid marriage, 1 Tim. 4:1-3,
and doth not the apostle tell you,
you must hold the mystery of faith in a pure conscience; and is it not your principle,
that people must carry about them the body of death and sin to the grave?
then you cannot hold the mystery of faith in a pure conscience, which is the gift of God,
that purifies the heart, in pleading for that which doth defile it, term of life.

And the apostle saith, '`let them first be proved, (to wit,
bishops and deacons,) then let them minister, if they be found blameless.`'

Now ye bishops and deacons, are you blameless from filthy lucre, and from covetousness,
and no fighters or persecutors?
Are you blameless concerning your children, wives, and families?
Are you blameless to them that are without?
Are you blameless concerning your tongues?
Are you blameless in being apt to teach, and in watching, and sobriety, and hospitality,
and blameless of evil speaking, and not given to much wine,
and unreprovable in these things?
For the apostle saith, first you must be proved concerning these things,
and then to be approved if you are found blameless of these things,
else by the apostle`'s doctrine you are not to minister,
and ye that are found in these things, cannot be the successors to the apostles.

So let your houses, your families, your lives, your fruits, and the jails,
and the scriptures speak, and the people that are without, and God and Christ judge,
whether you are clear from these things which the apostle reproves.

And the apostle who desired others to follow him, as he followed Christ,
and mark them for their examples, who coveted no man`'s silver, gold, or apparel,
and eat no man`'s bread for nought; but can you priests say so,
that have taken goods from people, and cast them in prison,
and have done no work for them, and they had nothing from you;
is not this eating other`'s bread for nought?
but the apostle bids Timothy be an example unto them that believed, (that is,
to the church,) he was to be an example in word and in conversation,
and an example in love, and an example in spirit, and an example in pureness,
for in so doing he both saved himself and them that heard him.
1 Tim.
iv. So try yourselves here by the apostle`'s command, and see what example you give.

And in 1 Tim.
vi. the apostle saith to Timothy of such that think gain is godliness,
'`from such separate thyself;`' what think ye of this ye priests?
if ye had not gain, should people have any of your preaching?
And then is not your gain your godliness, and from such the man of God must be separated;
and is not this to measure religion by riches?
Try yourselves by this scripture.

But the apostle saith,
'`godliness is great gain,`' if a man be content with what he hath,
for nothing we brought into the world, and it is certain we shall carry nothing out,
and therefore, having food and raiment, let us therewith be content;
for they that will be rich in this world fall into temptation and snares,
and many foolish and noisome lusts, which drown men in perdition and destruction.

And now measure yourselves ye bishops and priests, and professors,
and see if you be not fallen into these temptations and snares, and many noisome lusts,
and drowned in perdition and destruction, who have disobeyed the command of Christ,
which is, '`freely ye have received,
freely give;`' so there is not to be a looking after gain then,
which the man of God is to separate himself from them that do:
'`for the desire of money is the root of all evil, which whilst some lusted after,
they erred from the faith, and pierced themselves through with many sorrows;
but thou man of God flee these things, and follow after righteousness, faith, love,
patience, and meekness,`' etc.

Now here you may see what the man of God must flee from, and what he must follow after;
but come measure yourselves you that teach for money, and are lovers of money,
and others, have you not got the root of all evil, that lust after it in your hearts;
and are not you pierced through with many sorrows?
and are not you erred from the faith that gives victory?
And say,
there is no victory from the body of sin and imperfection on this side the grave:
and are not you erred from the command of Christ, which saith,
'`freely you have received, freely give:`' come try yourselves by the scripture,
which you say is the rule, whether your actions be not found short of Christ`'s command,
and the apostle`'s doctrine and charge to Timothy, the man of God.

And in 2 Tim.
iii. the apostle tells Timothy, that in the last times perilous days should come,
that men should be lovers of their own selves, covetous, proud, boasters,
cursed speakers, disobedient to parents, unthankful, unholy, without natural affection,
truce-breakers, false accusers, intemperate, fierce despisers of them which are good,
+++[+++mark, fierce despisers of them which are good,]
traitors, heady, high-minded, lovers of pleasures more than lovers of God, +++[+++mark,]
having a form of godliness, but have denied the power thereof, therefore,
from such turn away, +++[+++mark,]
for of this sort are they which creep into houses, leading silly women captive,
laden with sins, and led away with divers lusts, ever learning,
but never able to come to the knowledge of the truth;
and as Jannes and Jambres withstood Moses, so do these resist the truth,
men of corrupt minds, reprobate concerning the faith; but they shall proceed no further,
for their madness shall be manifest to all, as their`'s was.

Now come ye priests and professors, and all others called christians,
measure yourselves and try yourselves by these scriptures;
are not you lovers of yourselves, and covetous, and proud boasters;
and are not the cursed speakers and disobedient to parents found among you?
And are not you unthankful and unholy,
and do not you plead for unholiness as long as you live,
and say there is no overcoming the body of sin here?
And hath not your covetousness appeared in spoiling people`'s goods?
And are not you to be turned away from, according to the apostle`'s doctrine?
and have not you been false accusers, and intemperate,
and fierce despisers of them which are good?
and without natural affection, when you imprison so many for your bellies,
and make so many fatherless and widows, such as you did no work for?
Is not this without natural affections, and have not you a shew of godliness,
and a profession of Christ`'s and the prophets`', and apostles`' words?
And have not you, and do not you deny the power and spirit of the Holy Ghost,
that the prophets and apostles were in?
and do not you keep people always learning, and leading of them,
that they may be always paying of you,
yet they are never able to come to the knowledge of the truth?
And is not this a sad learning, and a sad leading?
And are not you and your people laden with sins and divers lusts?
For do not you tell the people, that both you and them must carry the body of sin,
and death, and imperfections to the grave?
And are not you and your people laden with your body of sin?
and is not this a great load to carry all their life long to the grave,
and there to be buried altogether with it, where there is no repentance?
And do not you keep your people always learning, always under your teaching,
that they may be always paying, and resist the truth, like Jannes and Jambres,
that resisted Moses,
and are reprobates concerning the faith that should give victory over the load of sin?
And hath not, and is not your madness here seen, as Jannes`' and Jambres`' was?
And is not the apostle`'s doctrine to be obeyed now, as then,
who bid '`turn away from all such,`' though you may have a form of godliness,
yet deny the power thereof, as they did in the apostle`'s time;
for hath not the highmindedness appeared,
and your loving pleasures been manifest to them that be in the power of God,
and turn away from you?
try yourselves by the scripture, and let God and Christ judge.

And the apostle saith, 2 Tim.
iv. he chargeth Timothy to preach the word '`in season, and out of season.`' Come,
professors and priests, measure yourselves by this; in season, may be you will say,
is when the sun shines, and out of season, is when there is a storm;
but there is more need to look after the sheep when the storm is,
than when the sun shines; for when there is a storm, is there then not most need?
so try your practice by the scripture, but then Demas will forsake Paul,
and embrace the world; and have not many done like Demas herein?
Let that of God in your conscience speak, and God and Christ judge.

And the apostle bids Timothy '`fly from all youthful lusts,
and follow after righteousness, faith, love,
peace with all them that call on the name of the Lord with a pure heart.`' Come,
try yourselves by this scripture, and if you were found according to Paul`'s exhortation,
it would be well; but do ye own such people as call upon the Lord with a pure heart?
Do you believe there is any such people now, that call upon the Lord with a pure heart?
That is contrary to your principle and belief,
who say people must carry a body of sin and death to the grave:
we never read in the scriptures that ever Christ
or his apostles preached up such a doctrine,
that people must carry a body of sin and death, and imperfection to the grave;
but they preached up holiness, pureness and perfection; and bid them be perfect,
and to follow the apostles, and to walk as Christ walked.

And Paul writes to Titus of the qualifications of bishops and elders,
how that '`they must be unreprovable, the husband of one wife, having faithful children,
who are not slandered with riot; +++[+++mark,]
neither are disobedient; for a bishop must be unreprovable as God`'s steward,
not forward, +++[+++mark,]
not angry;`' try yourselves, '`not given to wine;`' prove yourselves, '`no striker,
nor persecutor;`' examine yourselves,
'`not given to filthy lucre;`' measure yourselves with your rule, the scripture,
and see whether you are not given to filthy lucre; '`for,`' said the apostle,
'`there are many disobedient and vain talkers,
chiefly they of the circumcision.`' Now this circumcision was a command of God;
this outward circumcision they cry up, and leave the circumcision of the heart;
but the apostle saith, '`whose mouths must be stopped, who subvert whole houses,
teaching things which they ought not, for filthy lucre`'s sake; one of themselves,
even one of their own prophets said, the Cretians are always liars, evil beasts,
slow-bellies; this witness is true, wherefore reprove them sharply,
that they may be found in the faith.`'

So ye see here, what and who must be reproved,
and how these lucre prophets can speak one against another, and call them liars,
evil beasts, and slow-bellies; and is it not the practice of such now,
that are found in these steps, and such now as teach for filthy lucre,
as can cry up outward commands and the letter,
and make a mock of the spirit`'s moving and leadings:
so we see these could cry up circumcision, an outward command, for filthy lucre`'s sake,
as many do now talk of the letter, but cannot endure to talk of the light,
and Christ being manifested within,
and will not come to that lest it should reprove them; but it is their condemnation;
for they profess they know God, but by works they deny him, and are abominable,
and to every good work reprobate, see Tit. 1. and examine yourselves by it.
And Paul bids him, '`above all things, show thyself an example in good works,
with uncorrupt doctrine, with gravity and integrity.`' So now, do you prove yours,
and see whether you are found such examples in such works and uncorrupt doctrine;
for as James saith, chap. 2.
'`as the body without the spirit is dead, even so faith without works is dead,`'
Now this faith purifies the heart and gives victory,
and without it people cannot please God; and this faith works by love.

So you that deny overcoming sin and evil,
and the body of sin and death on this side the grave,
have not this true faith which gives victory, and in 1 Pet. 5.
'`he writes to the elders who was also an elder,
that they should feed the flock of God, not by constraint, but willingly;
not for filthy lucre, but of a ready mind,
not as though ye were lords over God`'s heritage,
but that ye be examples to the flock.`' Now mark, and come and try yourselves,
ye priests and teachers of Christendom, and elders:
do not ye feed your flocks for filthy lucre`'s sake?
Where is there any amongst you, but they are as lords and masters over God`'s heritage;
yea, and have the title of lords and masters, though it be contrary to Christ`'s command,
as in Matt. 23. and in Luke 22:25.
So look in all your bishopricks, popedoms, and other jurisdictions,
and see if you do not feed your flocks for filthy lucre`'s sake,
and not willingly and freely, as Christ commands;
and see if you have not lost the example of the ministers and elders,
whom the Holy Ghost made overseers:
and is not the succession of all Christ`'s ministers to be in the Holy Ghost,
as the apostles were in, and try yourselves by the scripture,
as you see in 1 Pet. 2:3.

And in 2 Pet. 2. there you may see how Peter describes the false teachers and false prophets,
and how '`many shall follow their damnable ways,
by whom the way of truth shall be evil spoken of,
and through covetousness shall they with feigned words make merchandize of you,
whose judgment lingereth not,
and their damnation slumbereth not,`' he compareth them to the '`fallen angels,
whom God spared not, that had sinned, but cast them into hell,
and under the chains of darkness to be kept unto damnation;`' and compares them to Sodom,
and the old world that was destroyed, '`who walk after the flesh,
and the lusts of uncleanness, and as natural brute beasts,
etc. having eyes full of adultery, that cannot cease from sin, beguiling unstable souls;
they have hearts exercised with covetousness, etc. which forsaking the right way,
have gone astray, following the way of Balaam,
who loved the wages of unrighteousness;`' mark, and try yourselves by this scripture.
'`They are wells without water,
and clouds that are carried away with the tempest up and down,
to whom is reserved the blackness and darkness forever;
for in speaking the high swelling words of vanity,
they beguile with wantonness through the lusts of the flesh,
them that were clean escaped from them, who are wrapped in error,`' mark, in error,
a sad wrapping, promising themselves liberty, and are the servants of corruptions;
for of whomsoever man is overcome, even to the same is he in bondage,
but it had '`been better for them never to have known the
way of righteousness;`' but the proverb is come upon such,
'`the dog is turned to his vomit, and the sow that was washed,
to the wallowing in the mire again.`'

So come, try yourselves, ye teachers, by this chapter,
who say ye have not the same power and spirit the apostles had,
see if ye be not found in these practises,
who shall receive the wages of unrighteousness,
as they who count it pleasure to live deliciously for a season: spots they are,
and blots, delighting themselves in their deceivings, in feasting with you:
so ye may see these could creep amongst the church;
and such in their very works deny the Lord that bought them; as now many will say,
that Christ did not die for all men,
and what is this but to deny the Lord that hath bought all men?
Though all men do not live to him that believe it,
yet '`he tasted death for every man;`' and ye may see those false teachers and prophets,
they had high swelling words, and a profession,
but their life was quite contrary to Christ and the apostles:
so all you that profess the scripture to be your rule, come try yourselves by it,
and see whether you be found in the life and practice of the apostles,
or these false prophets, which they declared against; for the good words ye may get,
and the sheep`'s clothing, but out of the sheep`'s nature and life,
but try yourselves by 2 Pet.
ii. throughout, whether you walk in the apostles`' steps and doctrine,
or in the ways of such as they testified against.
And in 1 John ii.
there you may see how he describes the false prophets and antichrists, who said then,
'`they were come already,`' and therefore exhorted
the saints to keep to the anointing within them,
which they had received from God, and they needed not that any man should teach them,
but as the same anointing doth teach them, and as it did teach them,
they should continue in the Father and the Son, and these things have I written,
concerning them that seduce you: so seducers, deceivers, false prophets, and antichrists,
drew people from this anointing within, being gone out from it themselves,
though they might keep the sheep`'s clothing, and outside profession,
and the prophets`' Christ`'s and the apostles`' words, but resisted the Holy Ghost,
like the pharisees and chief priests; and then they might say, as you do now,
that they had not the same Holy Ghost as the prophets and apostles had.
And John saith, '`whosoever abideth in Christ sinneth not, neither can he,
because the seed of God remains in him;`' but do not you say,
they must sin while they live upon the earth,
and carry the body of sin and death to the grave;
and is not this contrary to John`'s doctrine; but John saith, '`he that hath this hope,
purifies himself as he is pure,`' but do not you say,
you cannot be pure on this side the grave,
and there is no overcoming of sin on this side the grave;
and is not this opposite to John`'s doctrine again;
so what is your profession of the scripture worth in that hope which doth not purify,
which is the hope that will perish?
And John saith, '`little children, let no man deceive you,
he that doth righteousness is righteous, even as he is righteous,`' mark, is righteous;
this was the present time, before they go to the grave: and do not you deceive people,
that say, they cannot be righteous,
but must have and carry that unrighteous body of death and sin to the grave.

And John saith, '`whosoever hates his brother is a man-slayer,
and no man-slayer hath eternal life abiding in him,
and he that hates his brother is in darkness, and walks in darkness,
and knows not whither he goes,
because that darkness hath blinded his eyes.`' And
do not you hate your brethren for whom Christ died,
when you persecute and cast them in prison to death, and spoil their goods; come,
try yourselves by the scriptures, and by 2 John iii.
for Christ that tasted death for all men, he gives a command to love one another,
and to love enemies; to love them which love one again, this was the pharisees`' love,
which they had in their outward profession without life; but come and try yourselves,
ye teachers and professors in Christendom, by that which you say is the rule,
and see if the scriptures will not find you to be men-slayers,
and that you have not eternal life abiding in you, as the saints had, that loved God,
Christ, and one another, and enemies.
And in the third epistle of John, he saith,
'`because that for his name`'s sake,`' to wit, Christ`'s,
'`they went forth and took nothing of the Gentiles;`' and now mark,
do not you take of others who are not of your church;
and the apostles that went forth for Christ`'s name`'s sake,
took nothing when they went forth among the Gentiles, but do not you take of them,
whom you call heretics, and deceivers, and deluded ones,
which may be walk more in the life of Christ than yourselves?
Do you not force them, or sue them that do not give you a maintenance?
The apostle saith,
'`they were not to eat with such as walk disorderly;`'
where did ever the prophets or apostles take maintenance,
or force them to give them a maintenance, as they called antichrists and deceivers,
and heretics, or deluded ones?
Let us see where the scripture gives you a rule for this:
and where did ever the Jews take tithe-pigs?
Were not swine unclean by the law?
Or tithe-geese, or tithe-foals?
And though the law gave tithes to the priests, yet the gospel saith,
'`freely you have received, freely give:`' And if you priests do say,
you are of the tribe of Levi, and if you are of the tribe of Levi,
how is it that you take of so many sorts of people to make priests of;
for the Levitical priests were all of one tribe, but yours of many;
but Christ who came of the tribe of Judah hath ended
that priesthood that came of Levi`'s tribe,
and the law by which they were made, and the commandment that first gave them tithes.

And the apostle saith,
'`look to yourselves that ye lose not the things which we have done,
but that we may receive a full reward; whosoever transgresseth,
and abideth not in the doctrine of Christ, hath not God;
he that continueth in the doctrine of Christ,
he hath both the Father and the Son,`' mark, hath them; '`if there come any among you,
and bringeth not this doctrine, receive him not into your houses,
neither bid him God speed; for he that biddeth him God speed,
is a partaker of his evil deeds;`' for how can he bid him God speed,
that is without the Father and the Son, and transgresseth,
and doth not abide in his doctrine,
though he may have a great profession of Christ and the apostle`'s words,
and yet hath not seen Son nor Father, which is the substance of all.

Therefore come ye priests and professors, try yourselves; have ye the Father and Son?
Do you abide in the doctrine of Christ, '`freely ye have received,
freely give?`' try yourselves by the scriptures, and the 2d epistle of John, and let God,
and Christ, and the scriptures judge.

And the apostle Peter saith,
'`through covetousness shall they with feigned words make merchandize of you,`' to wit,
the people.
Now consider how many sorts of religions there are,
and the priests and the teachers thereof, that have made merchandize of the people,
hath there been in Christendom since the apostles`' days, 2 Pet. 2:3.

'`But the merchants of the earth shall weep and wail over her, (to wit,
Babylon) for no man shall buy her ware any more.`' Rev. 18:11.

And Peter saith in 2 Pet. 3:3. '`first understanding
that there shall come in the last days mockers,
which shall walk after their ungodly lusts;`' and
have we not sufficiently experienced this,
both from the leaders and hearers, who have mocked at the spirit of God,
which should mortify their lusts,
and at the movings of the spirit of God and yet make a profession of the scriptures,
which no prophecy of it came in the old time by the will of man;
but holy men of God spake as they were moved by the Holy Ghost;
and you not being in the same moving of the same Holy Ghost,
professing the words that were given forth by it and mock at it,
where it is manifested in life and power,
and say there is no having the same Holy Ghost nowadays, as they had,
which Holy Ghost leads into all truth now, as it did in the apostle`'s days,
where it is received and not resisted, like your forefathers,
and none come into all truth but by it,
though they may have all the scriptures given forth from it, from Genesis to Revelations.

And Jude in his general epistle warns the church of deceivers,
and bids the saints '`earnestly to contend for the
faith which was once delivered to the saints;
for there were certain men crept in,
which were before of old ordained to this condemnation, ungodly men they are,
which turn the grace of our God into wantonness, denying God the only Lord,
and our Lord Jesus Christ,`' which are compared to
the '`angels that kept not their first state,
but left their own habitation, whom he hath reserved in everlasting darkness,
under chains, unto the great day;`' and they are compared unto Sodom and Gomorrah,
'`that followed strange flesh, that were set forth for an example,
and to suffer the vengeance of eternal fire;`' and are compared
to such as God had delivered out of Egypt,
'`whom God destroyed, that believed not;`' which are called '`filthy dreamers,
that defile the flesh, and despise government, and speak evil of dignities,
and speak evil of those things which they know not; whatsoever things they know,
they know naturally as brute beasts, without reason,
in those things they corrupt themselves.`'

Now consider ye elders, and teachers, and professors, you that say,
that neither yourselves nor others have the same spirit, and Holy Ghost,
and power that the apostles had now in your days; then is not what ye know,
ye know naturally?
And do not you in those things corrupt yourselves,
who plead for the body of sin and death to the grave do
not you plead in this for that which defiles your flesh,
and speak evil of that dignity which should work it down?
And have you not made a mock of the grace of God, which brings salvation,
which teacheth the saints, and hath appeared unto all men?
For faith and grace is not natural (which Christ
is the author of,) but is the gift of God;
and was it not,
and is it not well for the saints to contend for the faith
which Christ is the author and finisher of in them,
which is God`'s gift, and purifies their hearts, which brings them to have access to God?
Is it not good to contend for this faith, the work of Christ in their hearts,
seeing such that turn the grace of God into wantonness,
and in their works deny the only Lord and our Lord Jesus Christ,
though in words they may profess him, whose ways are like Sodom,
and the angels that left their first habitation, and to the children of Israel,
that after God had delivered them out of Egypt, believed not, whom God destroyed;
therefore it is good for the saints to contend for the faith and grace of God,
that comes by Jesus, which saves them, and brings their salvation,
seeing there is so many that turn the grace of God into wantonness,
and contend for their body of sin, and death, and imperfection to the grave,
and walk despitefully against the spirit of grace,
and seeing so many speak evil of those things they do not know,
and deny the power and spirit the apostles had, which would give them knowledge,
for what they know they know naturally as brute beasts, the worst sort of creatures;
now are not all your tongues natural, and learning natural?
Did they not begin at Babel?
And did not Pilate and the Jews set them a-top of Christ when they crucified him?
and hath not the beast and the whore (mentioned in the Revelations) power over the tongues,
that sits upon the waters?
And are not the tongues called waters?
But Christ is risen above them, and all natural things;
and may not a parrot be taught to speak any language?
And is not all what ye know, ye know naturally, that say,
you have not the same power and spirit of God, and Holy Ghost as the apostles had?
Pray you come, try yourselves, and measure yourselves by this scripture,
and see if you be not found in these practises, that Jude warns the church of;
for how can ye know spiritually, that deny the light that shines in the heart,
to give the knowledge of the glory of God in the face of Christ Jesus,
who mock at this light, and call it natural, and the Quakers`' idol.

And further the apostle saith, '`Woe be unto them,
for they have followed the way of Cain,
and are cast away by the deceit and error of Balaam`'s wages of unrighteousness;
these are spots in your feasts of charity, when they feast with you,
without all fear feeding themselves, clouds without water, carried about with winds,
corrupt trees without fruit, twice dead, and plucked up by the roots,
they are the raging waves of the sea,
foaming out their own shame (and have we not seen
you rage sufficiently?) they are wandering stars,
to whom is reserved the blackness of darkness forever; these are murmurers, complainers,
walkers after their own lusts, whose mouths speak high swelling words of vanity,
having men`'s persons in admiration because of advantage, (mark,
there is the ground of their preaching,) but beloved,
remember the words which were spoken before of the apostles,
and of our Lord Jesus Christ, how that they told you,
that there should be mockers in the last times,
which should walk after their ungodly lusts (these are makers of sects, fleshly,
having not the spirit) of some have a compassion, in putting a difference,
and others save with fear plucking them out of the fire,
and hating even the garments spotted by the flesh.`'

And now come ye professors and teachers, and try yourselves by these scriptures;
do not you plead for the body of death and sin to the grave?

And doth not that spot the flesh?
and have you not men`'s persons in admiration because of advantage?
and are not you wells without water, the living water,
and wandering stars from one thing to another, and trees without heavenly fruit,
that say you have not the same spirit and power the apostles had?
and are not some of you (I fear) twice dead and plucked up by the roots?
then you cannot grow; and have you not gone in Cain`'s way of persecuting,
and Balaam`'s way for the wages of unrighteousness, contrary to Christ`'s command,
'`freely you have received freely give?`' Pray try,
and see if you be not found in his error, and these evil practises.

And have not you gone in Core`'s way,
gainsaying the power and the spirit as the apostles were in?
And did not the same gainsay that in the apostles`' days?
And does not the apostle say, '`They that have the form of godliness, and not the power,
from such turn away?`' That is, they that have not the power, and spirit,
and Holy Ghost the apostles were in, turn away from such;
so try yourselves by these scriptures,
and see whether ye be found in the practice of the apostle,
or such as he cried against here,
having men`'s persons in admiration because of advantage, and makers of sects;
look how many sects there are amongst you in Christendom;
and what can you walk after else but your ungodly lusts, who say,
you have not the same spirit the apostles had to walk after,
who plead for your carrying your body of sin, and death, and imperfection to the grave.

And also another scripture ye bring in Mat.
xxviii.
'`go and teach all nations,`' etc.

Now consider, most sects will bring this; for papists, presbyterians, independents,
baptists, and others, will bring this scripture for their call, and say,
Christ bids his disciples, '`go, and teach all nations,`' etc.
But mark, do you go into all nations?
Hath Christ spoken to you, and bid ye go into all nations, as he bid the apostles?
If so, then you are disobedient;
how is it then that you settle down in great bishoprics and parsonages,
and are ready to jostle and thrust one another out for them;
but will you go any further than you may have a fat parsonage
or benefice provided by some magistrate or great person,
or have a law to compel people to give you a maintenance; the apostles trusted the Lord,
and went out without bag, etc. and freely as they had received, so did give freely,
but will you go any further than there is a fat benefice or parsonage?
And if this be your call, as you pretend, why do not you go among the Turks, Tartars,
Blacks, and Indians, and give unto them freely, as Christ gave himself freely,
who had power to lay down his life, and take it up again?
And he hath tasted death for every man freely,
and hath enlightened every man with his heavenly divine light freely;
and the grace of God which brings salvation, which appears unto all men, is given freely.
'`So, if any man lack wisdom, let him ask it of God, he gives unto all men freely,
and upbraideth no man,`' James 1:5. And so Christ bids his ministers give freely,
as they had received freely; so try yourselves by these scriptures,
all ye who neither obey Christ`'s command, nor do his work.
And '`thou believest there is a God, thou dost well,
the devils also believe and tremble,`' James 2:19.
and so thou mayest believe there is a Christ,
so did the devil, and thou dost well,
but see if the devil`'s belief doth not condemn thee,
but thou shouldst shew the works of thy faith and of thy belief,
that thy heart is purified, that thy faith be not dead;
for a dead faith will plead for a body of death and sin to the grave,
but the living faith, the gift of God, is the victory over it, and doth purify,
through which faith there is access to God, and in that faith thou wilt please God,
which the saints now contend for, which Christ is the author of.
And, '`He that saith he remaineth in Christ, ought even so to walk,
even as he walked.`' 1 John 2:6. '`And he that hath the Son hath life,
and he that hath him not, hath not life;
and he that believeth in the Son of God hath the witness
in himself,`' 1 John v. '`and he that hath the Son,
hath the Father.`' So this is more than an outward belief,
as the pharisees had of God and Christ to come, or others now, that say he is come,
and do not receive him freely into their hearts by faith.

And therefore, '`prove yourselves, examine yourselves, know you not your own selves,
how that Jesus Christ is in you except ye be reprobates.`'
So try and measure yourselves by the scriptures here,
whether you be in the life and spirit of the prophets, Christ and the apostles,
or in the spirit of the false prophets and teachers.
This is in love to you all, that you may not sin out your time.

And Paul saith, 2 Cor. 12:17. '`Did I make a gain of you, +++[+++or peel you]
by any of them whom I sent unto you?
I have desired Titus, and with him I have sent a brother, did Titus make a gain of you,
+++[+++or peel you]
of any thing?
Walked we not in the self-same spirit?
Walked we not in the same steps?`' Now come priests, try yourselves,
do not you make a gain of people yourselves, and by such as you send amongst them?
Do not you peel the people?
Do ye walk in the self-same spirit the apostles were in, and in the same steps?
Let your practice, and that of God in your consciences, and the people,
and the scriptures judge, for there is the succession. 2 Cor. 12:17-18.
And you may see in your own margin notes, such false teachers,
who under a pretence of preaching the truth, sought only to fill their bellies,
whereas the true teachers sought the people:
and now come try yourselves by your own marginal notes in the beginning of 2 Cor.
and see which of these steps you walk in, and whether you seek the people,
or to fill your bellies.
And in the marginal notes upon 2 Thee.
such as lived idly of other men`'s labours, were to be reproved sharply, whom,
if they did not obey Paul`'s admonitions and command,
they were to have no fellowship with them.
So see and try yourselves, ye priests and teachers, by your own marginal notes,
and see whether you are not such as live idly on other men`'s labour, and so,
are such as deserve not only to be reproved sharply, but to be such,
as with whom the true church is not to have fellowship.
And do not you think there are many Elymases now amongst you,
that seek to turn people from the true faith,
which Christ is the author and the finisher of, which purifies the hearts of people,
by which faith they are justified, and by which faith they have access to the pure God?
And will not Elymas plead for imperfection, and a body of sin and death to the grave,
think you?
And is not this seeking to turn people from the true faith, that gives them victory?
But you presbyterians, what is become of your directory that you made,
and persecuted us for not following your directory, and not giving you means?
And you independents, what is become of your church faith, which you made at Savoy,
in eleven day`'s time?
And persecuted us because we would not follow your church faith,
and give you maintenance, as many others have done since,
because we cannot follow their book worship, which we told you then, and do now,
the scripture is a better book than any you can make;
and the spirit of Christ is a better directory than yours,
who say you have not the same spirit they had, which gave forth scriptures,
and yet you will make books for people to worship by;
may not Christ`'s words be verified upon you?
'`If the blind lead the blind both shall fall into
the ditch.`' But Christ is the author of our faith,
and finisher, and not you; and the scripture is a better directory or creed,
than any of you all can make, and the spirit is a better directory and leader,
that gave the scriptures forth, than yours, which ye have often said,
ye have not the same spirit that gave forth the scriptures,
and yet will give forth directories, and creeds, and faiths, for other people,
and persecute them for not believing, and not joining to it, and not maintaining it,
and you that held it up.
Now the scriptures were given forth to be believed, fulfilled, and practised, and read;
and the church was charged by the Lord to read it,
as you may see in Col. 4:16. and 1 Thess. 5:27.
and the law and the prophets were to be read and fulfilled;
so we say, read them, and believe and practise them, and wait upon Christ,
who doth fulfill them, and by his Holy Ghost leads into all the truth of them;
and obey the spirit of God, by which ye may know the things of God.
And in Nehem.
xix. it is said,
'`Thou gavest them thy good spirit to instruct them.`'
But you may see how they rebelled against it,
and rebelled against his prophets that walked in his spirit.

And in Acts 7:51. you may see the stiff-necked
professors and uncircumcised in heart and ears,
always resisted the Holy Ghost, as your fathers did, so do ye;
and these were rebels against the Holy Ghost, who rebelled against the prophets,
rebelled against Christ, rebelled against the apostles, yea,
I say they rebelled against Christ who was conceived by the Holy Ghost;
and the apostles that were in the Holy Ghost,
they also rebelled against the church that had fellowship with them in the Holy Ghost,
they rebelled against the martyrs, and them that kept the testimony of Jesus,
the spirit of prophecy; and these rebels were of the beast, and the whore,
the false church, antichrist, and the false prophets,
deceivers and teachers that preach for filthy lucre, and for means,
that minded earthly things, and served not the Lord Jesus Christ, but their own bellies,
and preach people to themselves, or parties, and not to Christ,
but make a prey upon them.
And these rebels were they that always persecuted the true church, and the prophets,
and Christ, and the apostles, and the martyrs, and quenched the spirit,
and grieved and vexed it, both in themselves and others,
though they may get the form of godliness, but deny the power thereof;
and these that rebel against the Holy Ghost, and resist it,
are such as hate the divine and spiritual light of Christ,
and will not come to it in themselves, lest it should reprove them,
because their deeds are evil; and these that rebel against the spirit,
are such as turn from the grace of God into wantonness,
and walk despitefully against the spirit of grace;
and these that rebel against the spirit, say, that Christ the heavenly man,
hath not enlightened every man that cometh into the world with a heavenly light;
and these also say that the grace of God which brings salvation,
and which hath appeared unto all men, they say,
it is not sufficient to teach and to bring salvation to all,
and say it hath not appeared to every man, contrary to God and the scriptures, who say,
that his grace is sufficient; and these rebels say, that Christ hath not tasted death,
nor his blood shed for all men; and these are the makers of sects,
and bringers of people on heaps, that resist and rebel against the Holy Ghost,
in which holy spirit the saints fellowship is; and though the prophets,
Christ and the apostles testify against such as preach for filthy lucre, and for hire,
yet they that rebel against his spirit will have it, and compel people to pay it,
though it be contrary to God and his prophets, Christ and the apostles`' testimony;
and though Christ commanded his ministers or messengers '`freely ye have received,
freely give,`' yet such as rebel against the Holy Ghost,
and resist the good spirit of God, as all their forefathers did,
will force people to give it them, and they themselves will take it,
contrary to his command, and imprison and persecute them that will not give it them;
and hey that rebel against and resist the Holy Ghost,
though they may have all the form of godliness from Genesis to the Revelations,
they will never bring people to heaven, nor to God, nor Christ,
but like their forefathers, the pharisaical Jews, shut up the kingdom of heaven from men,
neither enter in themselves, nor suffer others;
and among them is found all the blood of the prophets, and Christ, and the apostles;
and the martyrs from the foundation of the world unto this day; and among such,
and by such was our Lord and Saviour slain;
and these are the great professors of God and Christ, prophets and the apostles,
and the scriptures with their lips, but their hearts are afar off from God and Christ:
and such as do resist the Holy Ghost, and rebel against it, they may well say,
they have not the same spirit and power the prophets and apostles had,
nor have heard God and Christ`'s voice;
and so if such will try themselves by the scripture, they may see,
neither scripture nor the spirit is their rule for their life and practice;
for they that rebel against the spirit of God, and resist the Holy Ghost,
rebel against God, his prophets, Christ Jesus and his apostles,
and his people to this day,
though they make a profession of the words given forth by the Holy Ghost,
and find fault with their forefathers for persecuting the prophets, Christ,
and the apostles, and the martyrs, yet they follow them in their persecuting spirit,
and are direct heirs to them, following them in their succession, the birth of the flesh,
that will persecute him that is born of the spirit,
making a profession of the scriptures given forth by the birth of the spirit,
and yet rebelling against the spirit, and resisting the Holy Ghost,
which moved all the holy men of God to speak forth the scriptures,
and the same Holy Ghost is the key to open them again;
and they that are in the Holy Ghost,
are in the succession to that spirit the apostles were in;
and they that are in the Holy Ghost, are in the succession to the church-fellowship,
that was in the primitive times, and are in the succession of praying in the Holy Ghost,
and comfort of it, and the succeeders of feeding the flock,
and the overseeing it in the Holy Ghost that the apostles were in;
and they that are the spiritual successors of the apostles,
are in the Holy Ghost that leads them into all truth,
as it led the apostles into all truth.

And in Ezek. 22:25. to the end,
that is a conspiracy of the prophets in the midst thereof,
like a roaring lion ravening the prey, they have devoured souls,
they have taken the riches and precious things,
they have made many widows in the midst thereof, (to wit,
Jerusalem,) her priests have broken my law, and have defiled my holy things,
they have put no difference betwixt the holy and the profane, the clean and the unclean,
etc. and I am profaned amongst them, her prophets have daubed with untempered mortar,
seeing vanity and divining lies, saying, thus saith the Lord,
when the Lord hath not spoken;
the people of the land have been violently oppressed by spoiling and robbing,
and they vexed the poor and the needy; yea, they vexed the poor against his right;
I sought for a man amongst them that should make up the hedge,
and stand in the gap before me for the land, that I should not destroy it,
but I found none.

Now consider this, ye priests, prophets, and professors in Christendom, try yourselves,
and see if you be not found in this spirit as these
priests and prophets were in under the law?
Have ye not broken the gospel and the command of Christ, as they broke the law?
Have you not made many widows and fatherless by casting in prison for your tithes?
Have not you said, thus saith the Lord, and the Lord never spoke to you?
Have not ye been like ravening lions for your prey?
Have not you vexed the poor and needy, and stranger by oppressing and spoiling?
And is not this contrary to the gospel and Christ`'s command, who saith,
'`freely ye have received,
freely give.`' So measure yourselves and your practice by this scripture.

And Christ saith John x. '`an hireling will flee because he is an hireling,
and cares not for the sheep.`' And hath not this been fulfilled
amongst the hirelings in this our age?
and Christ faith, the thief cometh not, but to steal, to kill, and to destroy,
but I am come that ye may have life, and have it more abundantly,
and all that come before me are thieves and robbers, but the sheep did not hear them,
+++[+++mark,]
did not hear them, and I am the door of the sheep, if by me any man enter in,
he shall be saved, and go in and out and find pasture and therefore,
come now and try yourselves by Christ`'s own words, who is the good shepherd,
and hath laid down his life for his sheep;
and therefore what say you of all them that have killed
and destroyed about religion since the apostles`' days,
and say they have not heard the voice of Christ?
do not these steal their words from their neighbours, and run, and God never sent them?
And are Christ`'s sheep to hear thieves and robbers?
And is it not Christ which lighteth every man that cometh into the world?
Is not he the door, and must not every one that entereth into his pasture,
enter in by the light, or else how can they see the door without the light,
which comes from him who is the life: for it is said,
'`the light which shines in the heart,
gives the knowledge of the glory of God in the face of Christ Jesus,
who is the door.`' So they cannot enter in to Christ the door,
but by the light that gives the knowledge; so try yourselves, all ye that say,
Christ hath not enlightened every man that cometh
into the world with a heavenly and divine light,
how you will come into the door without this light?
And whether you that deny it do not keep people yet in darkness, among the hirelings,
and thieves, and robbers,
and from the good shepherd that lays down his life for his sheep,
and are climbing up some other way?
But Christ`'s sheep hear his voice and follow him, who is the same today as yesterday,
and so forever, though you say there is no hearing his voice nowadays.

And the apostle saith, '`let no man condemn you in meats, or drinks,
or in respect of a holy-day, or new-moons, or sabbath-days,
which are but a shadow of things to come, but the body is of Christ.`' Now mark,
for people to jangle about such things, is but about shadows of things to come,
and that which the kingdom of God stands not in, but the body is of Christ;
so Christ and his body is to be minded, who is the substance of such things,
that were figures, types or shadows of him; and he is to be minded, who is the head,
and the substance, and life of all.

And further the apostle saith, '`let no man at his pleasure bear rule over you,
by humbleness of mind,
and worshipping of angels advancing himself into those things which he never saw,
rashly puffed up with his fleshly mind, and not holding the head,`' etc.

Now consider this, all ye that say, there is no hearing of God`'s voice nowadays,
nor Christ`'s voice, and you have not the same power and spirit the apostles had.

Therefore, come try yourselves by the scripture, which you say is your rule,
are not you they that bear rule with your pretended humbleness of mind,
advancing yourselves into Christ, the prophets`' and apostles`' words,
which you never saw in that spirit that gave them forth,
and rashly puffed up in your fleshly minds:
now consider whether people must own such as the apostle cried against in his day,
now in our days, I say, they that do hold Christ Jesus the head, to be their teacher,
and their prophet, and their shepherd, whether they must hold up such, yea, or nay?
And further the apostle saith,
'`if ye be dead with Christ from the ordinances of the world,
why as though ye live in the world are ye burdened with traditions?
Touch not, taste not, handle not, which all perish with the using,
after the commandments and doctrines of men,
which things indeed have a show of wisdom in a voluntary religion, etc.`' +++[+++mark,]
a voluntary religion, then it is not the religion that is pure, which James speaks of, etc.

Therefore, whether or no we must not follow the apostles here in our age,
as the saints were in their age, and not to touch, taste,
nor handle the doctrines of men, or commandments of men,
which will perish with the using,
though they may have a shew of wisdom in a voluntary religion;
them that be not dead with Christ may follow such traditions and ordinances of men,
and touch, taste and handle that which perisheth with the using;
but they that be dead and risen with Christ, cannot follow such things, as in Col.
2+++.+++ So try yourselves by this scripture whether you follow the apostles`' doctrine,
or such as he forbid.

And in 1 Tim.
iv. the apostle saith,
'`the spirit speaks expressly that some shall depart from the faith in the latter times,
and shall give heed to the spirit of error, and doctrines of devils,
which speak lies in hypocrisy, having their consciences seared as with an hot iron,
forbidding to marry, and commanding to abstain from meats,
which God hath created to be received with thanksgiving
of them that believe and know the truth;
for every creature of God is good, and ought not to be refused,
if it be received with thanksgiving,
for it is sanctified by the word of God and prayer.`'

Now come and try yourselves, all ye that forbid meats and marriages,
are not you these that the apostle prophesied of, and the spirit spoke of,
that are departed from the true faith that the apostles were in,
and are in the spirit of error, and doctrine of devils, which speak lies in hypocrisy,
having your consciences burned with an hot iron,
and are out of the belief and the truth that the apostles were in,
and so see not the end of God`'s creating of his creatures,
to be received with thanksgiving, who saith, every creature of God is good,
and nothing ought to be refused, if it be received with thanksgiving,
for it is sanctified by the word of God and prayer;
so not sanctified to you that forbid them,
neither do ye know the end of God`'s creating them.
So be not deceived, God is not mocked, for whatsoever a man soweth,
that shall he also reap, for he that soweth to the flesh,
shall of the flesh reap corruptions, but he that soweth to the spirit,
shall of the spirit reap life everlasting. Gal. 6:7-8.

Now come try yourselves all ye teachers in Christendom,
and look into your fields or vineyards, and see what you have there sown,
and see what a great crop of corruptions and all
manner of evils you may reap out of them;
for you saying you have not the same spirit, and plough, and flail,
and faith that the apostles had, then you cannot sow unto the spirit,
by which you might reap life eternal;
and though you may have all the scriptures from Genesis to the end of the Revelations,
if you have not the same spirit as they had that gave them forth,
you cannot sow to the spirit, neither are you successors of the prophets and apostles,
except you are in the spirit that gave forth the scriptures.
And the apostle saith '`let every man prove his own work,
and then shall he have rejoicing in himself only,
and not in another.`' So now try yourselves ye priests and teachers,
and prove your own work, and see what joy ye have in it;
to rejoice in another man`'s work, the prophets`' or apostles`',
is not to rejoice in your own work, the work that God hath wrought in you;
and if you come to this,
you must come to the light (as Christ said,) to see whether your works be wrought in God,
that ye may have joy in him, and in yourselves in his spirit.
Again the apostle saith,
'`let him that is taught in the word communicate unto him
that teacheth in all good things.`' Gal. 6:6.

Now is not this the scripture which you bring for your maintenance?
But what is this to prove your forced maintenance by, and to cast people in prison,
if they will not give you tithes, or midsummer-dues, Easter-reckonings, and the like;
this was spoken to them that were taught in the word,
not to them whom they did not teach, and to force from them: but you use to say,
why do not they come, and hear?
they may come if they will;
did the apostles force a maintenance from any that did not hear them, and say,
they might come if they would, and we have a law to compel it from you; if so,
where is it written in the scripture, which you say is the rule?
But in this your practice, have not you thrown away Christ`'s law and command,
who bids freely to give, as they had received.
But the apostle saith, '`he that is taught in the word,`' he doth not say,
he that is taught in the letter; John saith, '`in the beginning was the word,
and in him was life, and this life was the light of men,
and this is the true light that lighteth every man that
cometh into the world:`' and you that deny this light,
do not you deny the teaching of the word, and call the light natural?
and then in your account is not the word natural?
Therefore, how can you have the good things communicated to you,
which do not communicate the good and everlasting things to people;
and you see that the apostle would not receive of
them that he did teach the good word to,
but laboured with his hands, that he might keep the gospel without charge,
and show an example to all that succeeded him, neither would he use his power;
but have you not gone beyond this power, and abused it; try yourselves.
1 Cor.
ix. Gal.
vi. And in Luke viii.
'`and Joanna wife of Herod`'s steward, and Susannah, with many others,
which ministered unto Christ of their substance.`' Now this scripture,
which ye also bring, proves nothing for your forced maintenance, for what they did,
they did it freely;
for Christ never made a law to force people to give him and his disciples maintenance;
if you say he did, show where it is written.
Again,
Habakkuk saith in Hab. 2:9. '`Woe to him that coveteth
an evil covetousness to his house.`' And therefore,
take heed of this woe coming upon you,
all ye that covet an evil covetousness to your house, that ye may set your nests on high,
who have coveted and taken other people`'s goods that ye have done no work for,
be sure it will, except ye repent.
And in Amos vi.
is it not said, '`woe to them that chant, or sing to the sound of the viol,
and invent to themselves instruments of music like David, that drink wine in bowls,
and anoint themselves with the chief ointments,
but they are not grieved for the affliction of Joseph.`'
Now consider this ye priests and professors,
and others, and try your practice by this scripture,
and whether you are not found in these practises, and putting far away the evil day,
and approach the seat of iniquity?
And are not you them that stretch yourselves upon your beds?
And therefore see what judgments the Lord threatened should come upon such;
and do ye think the like judgments will not come upon you,
that are found in their practises: and therefore,
do not profess the scriptures to be your rule, except you walk in the spirit,
which was both leader and rule, to the holy men of God that gave it forth,
and according to their example that gave it forth in life and practice; for if ye do not,
ye are judged and reproved by the holy scripture, and the spirit of God and Christ,
by which they were given forth.

[.signed-section-signature]
G+++.+++ Fox.

[.signed-section-context-close]
Worcester Prison, the 11th month, 1674.
