== A Looking Glass for the Jews:

[.heading-continuation-blurb]
Wherein they may clearly see that the Messiah is come,
by the Prophets in the Old Testament,
(above sixteen hundred years since,) and the manifest testimonies since.

[.heading-continuation-blurb]
And also, they may see their own blindness and ignorance of their own Prophets,
and of the Messiah unto this day.

[.heading-continuation-blurb]
By which my desire is, they may turn to him, that their eyes may be opened,
that they may see him whom they have pierced.--By G. F.

Daniel was a man greatly beloved of God, who interpreted Nebuchadnezzar`'s dream:
and Nebuchadnezzar`'s dream concerned himself, and the whole monarchy,
(the head of gold,) and concerned the Persian monarchy,
(the breast of silver,) and concerned the Grecian monarchy,
(the belly and thighs of brass,) and concerned the Roman monarchy, (the legs of iron,
and the feet of iron and clay:) and the breaking of all
these to pieces as the chaff of the summer threshing-floor,
and the wind carrying them away, that no place for them was found:
and it was the stone that smote the image of gold, etc. and became a great mountain,
that filled the whole earth?
and is not this stone the Messiah?
For Daniel saith, '`whom ye do believe as a prophet and beloved of God,
in the days of these kings shall the God of heaven set up a kingdom,
which shall never be destroyed, Dan. 2:44. +++[+++mark,
in the days of these four monarchies,) and the kingdom shall not be left to other people,
but it shall break into pieces and consume all these kingdoms,
and it shall stand forever: the stone which was cut out of the mountain without hands,
it shall break into pieces the brass, and the clay and iron,
the silver and the gold monarchies.`' Now Nebuchadnezzar did say to Daniel,
'`of a truth his God was the God of truth, and the God of gods,
and the King of kings,`' etc.
So now, consider, was not Nebuchadnezzar beyond you in your belief?
And did not the Messiah come in the days of these four monarchies,
and set up his kingdom above sixteen hundred years since?
And are not those four monarchies dashed in pieces
by the stone which should come in their days?

Was not Daniel a true prophet, and Nebuchadnezzar`'s dream true upon the four monarchies?
And did not the God of truth reveal these secrets to him?
So if ye do believe that Daniel was a true prophet, and Nebuchadnezzar`'s dream true,
and God did reveal the secrets of it to Daniel, and the gold and silver, and brass,
and iron,
and clay monarchies were broken to pieces by the stone which should become a great mountain,
and should fill the whole earth; then you must believe that the Messiah is come. Dan. 2:44.
And did not Nebuchadnezzar,
in the vision of himself to be the tree which was hewn down,
confess to the God of heaven, and extol him, and lift up his eyes to heaven,
and bless and praise the Most High, and honour him that lived forever;
'`whose dominion is an everlasting dominion,
and his kingdom is from generation to generation.`' And mark that,
and see if ye see this kingdom that is everlasting,
and dominion from generation to generation:
and see if you can see this in your generation: and how can ye see this,
unless you come to this stone,
and this kingdom which God set up in the days of these four monarchies,
which should never have an end?
For you know, ye had a kingdom before those four monarchies, which had an end.

And Daniel in his vision, chap.
vii. 13. saw the kingdom of God, who saw one like the Son of man,
and there was given him dominion and glory, and a kingdom, that all people,
nations and languages should serve him; his dominion is an everlasting dominion,
and shall not pass away; and his kingdom shall not be destroyed.
Now you know yours passed away: and the saints should take this kingdom, (that is,
the sanctified ones.)

And Daniel heard one saint speak to another,
'`how long shall be the vision concerning the daily sacrifice,
and the transgression of desolation,
to give both the sanctuary and the host to be trodden under foot?
He said to me, unto two thousand three hundred days,
then shall the sanctuary be cleansed.`' Dan. 8:13-14. Now, do you cast up this time,
and number these days or years, and see what time yourselves be in. Dan. 8.

And in Dan. 9. while Gabriel the angel speaks to him,
and tells Daniel that '`he was greatly beloved,
and to give him skill and understanding,`' etc.
And says to him, '`seventy weeks were determined upon his people, and upon the holy city,
to finish the transgression, and to make an end of sin; +++[+++mark,]
and to bring in everlasting righteousness, and to seal up the vision and prophecy,
and to anoint the most holy; know therefore and understand,
that from the going forth of the commandment to restore
and build Jerusalem unto the Messiah,
the Prince, shall be seven weeks, and sixty-two weeks,`' etc.
'`And after sixty-two weeks the Messiah shall be cut off, but not for himself:
and the people of the Prince shall come and destroy the city, and sanctuary,`' etc.
'`And he shall confirm the covenant with many for one week,
and in the midst of the week he shall cause the sacrifice
and the oblation to cease,`' etc.
Now consider this, ye Jews, and number ye this time, the seventy weeks;
and whether your Jerusalem was not built according to that number,
and whether the Messiah did not come; and was not he cut off after the sixty-two weeks?
according to this time was not he cut off?
Did not you cut him off, but not for himself?
And did not the people of the Prince come and destroy your city,
and cause your offerings to cease?
Now number you this time: and whether one which was called the Messiah did not come,
according to these years, which you would not receive?
And Isaiah calls him a Prince: But when he came,
he did confirm his new covenant with many, and when he had offered up himself,
he caused your offering to cease once for all.

And Dan.
xii. '`From the time that the daily sacrifice shall be taken away,
and the abomination that maketh desolate set up,
shall be one thousand two hundred and ninety days; blessed is he that waiteth,
and cometh to the thousand three hundred and five and thirty
days.`' Now number ye this time when it began,
and when it ended; and see that you may be partakers of this blessing.
So I desire that you would see and number the time to the Messiah, the Prince,
after the threescore and two weeks:
and whether ye did not cut off one in that time that was called the Messiah,
who was born of a virgin, called the Virgin Mary, according to Isaiah the prophet,
who saith, Isaiah vii.
'`The Lord himself shall give you a sign; behold a virgin shall conceive, and bear a son,
and shall call his name Immanuel.
Now number you the time in Dan.
ix. unto Messiah the Prince, and see whether or no a virgin had not a child, a son,
whose name was called Immanuel.
And also the saying of Isaiah the prophet came upon you, '`go tell this people,
hearing indeed, but understand not; and seeing indeed, but perceive not;
make the heart of this people fat, and make their ears heavy, and shut their eyes;
lest they see with their eyes, and hear with their ears,
and understand with their hearts,
and be converted and be healed.`' Isa. 6:10-9. And was not this your condition,
when this virgin had a child, and when the Messiah came to you,
according to Daniel`'s number, which was the sign the Lord gave you,
a virgin should have a son, and his name should be called Immanuel, God with us;
then you would not understand this with your hearts, nor see with your eyes,
nor hear with your ears; but were shut up unconverted and unhealed to this day.

'`Then said I, O Lord, how long?
then said he, till the city be wasted without inhabitant, and the houses without man,
and the land be utterly destroyed: the Lord shall remove men far away,
and there shall be a great forsaking in the midst of the
land.`' Isa. 6:11-12. Do ye not see this come upon you:
'`but in it shall be a tenth, and it shall return, and shall be eaten, as an elm tree,
or as an oak, whose substance is in them, when they cast their leaves;
so the holy seed shall be the substance thereof.`' So when you have cast off your show,
your outside leaves, you may see this tenth, and this holy seed,
the substance of your figures and shadows.

'`For to us a child is born, unto us a son is given,
and the government shall be upon his shoulders, and his name shall be called wonderful,
counsellor, the mighty God, the everlasting Father, the Prince of peace;
of the increase of his government and peace there shall be no end,
upon the throne of David and his kingdom, to ordain it,
and establish it with judgment and with justice, from henceforth and forever:
the zeal of the Lord of Hosts will perform this.`' Isa. 9:6-7.

Now consider this prophecy of Isaiah; whether this child was not born of the virgin,
this son given, and came according to Daniel`'s number, and Isa.
xi. '`there shall come forth a rod out of the stem of Jesse,
and a branch shall grow out of his roots, and the spirit of the Lord shall rest upon him,
the spirit of wisdom and understanding, the spirit of counsel and might,
and the spirit of knowledge, and of the fear of the Lord;
and he shall make him of quick understanding in the fear of the Lord:
and he shall not judge after the sight of his eyes,
neither reprove after the hearing of his ears;
but with righteousness shall he judge the poor,
and reprove with equity for the meek of the earth;
and he shall smite the earth with the rod of his mouth;
and righteousness shall be the girdle of his loins,
and faithfulness the girdle of his reins, etc.
And this root of Jesse shall stand as an ensign to the people,
to it shall the Gentiles seek, and his rest shall be glorious.`' Now consider, ye Jews;
is not this the Messiah spoken of, according to Daniel`'s number?
Who was of the seed of David?
And now is he our people`'s ensign; and we, whom ye call Gentiles, have sought,
and found; and his rest is glorious to us.

And consider, in Isa.
xxix.
'`The Lord hath poured upon you the spirit of deep slumber, and hath closed your eye,
your prophets and your rulers, your seers hath he covered.`' Was not this so,
when the virgin had a child, the Messiah, the Immanuel,
when that sign was brought forth among you, according to Daniel`'s number?
And was not the vision and the book, and the law and the prophets a sealed book to you,
which spake of Christ to you, that when the Messiah came, you did wonder,
and stagger like drunken men, but not with wine or strong drink:
and though you cannot rightly read the book of the law and the prophets,
it being sealed up; yet you then and now draw nigh to the Lord with your lips,
and your mouths do honour him, but have removed your hearts far from him:
therefore the Lord said, '`behold,
I will proceed to do a marvellous work among this people, a marvellous work and a wonder;
for the wisdom of the wise men shall perish,
and the understanding of your prudent men shall be
hid.`' And hath not this been seen among you,
concerning the Messiah?
That sign, that a virgin should have a son; and therefore he calls you in Isa.
xxx. '`rebellious children;`' when he says, '`woe to you rebellious children,
saith the Lord, that take counsel but not of me; that cover with a covering,
but not of my spirit, that they may add sin to sin.`' For,
had you been covered with the spirit, you would have seen the sign that God gave you,
the virgin having a son, the Immanuel,
who came according to Daniel`'s number '`and therefore,`' says Isaiah, '`saith the Lord,
write it before them in a table, and note it in a book,
that it may be for a time to come, forever and ever; for this is a rebellious people,
lying children,
that will not hear the law of the Lord.`' Isa. 30:1,8,9.
So here you may see what they were in Isaiah`'s days,
and the rest of the prophets`'; and you may see what you were in Moses`' days,
rid the rest of the Judges; and what you were when the Messiah came:
for did you not say to the seers, '`see not;`' to the prophets,
'`prophesy not to us right things, speak to us smooth things,
prophesy deceit:`' so you may see how you were against the prophets,
and how you were all along from Moses to the Messiah.

And Isa.
xxxii.
'`behold, a king shall reign in righteousness,`' etc.
And is not this spoken of the Messiah?
'`A man shall be as a hiding place from the wind, and a covert from the tempest,
as rivers of water in a dry place, and as the shadow of a great rock in a weary land.
And the eyes of them that see, shall not be dim;
and the ears of them that hear shall hearken:`' and this is witnessed by thousands,
though you have ears and hear not, and eyes that see it not.

And Isa.
xxxv.
where it speaks largely of the Messiah, '`who hath made the wilderness a solitary place,
glad, and hath confirmed the weak hands and feeble knees,
and made the fearful heart strong, and opened the blind eyes and deaf ears,
and made the lame man to leap, the tongue of the dumb to sing,
and the wilderness and the desert water streams, and her parched land to become a pool,
and thirsty land springs of water:`' we who own the Messiah, the Immanuel,
the Son of the virgin, the sign to you whose heads are weak, and knees feeble,
and land parched thirsty, wanting the springs that be heavenly,
and whose tongues are dumb, concerning the Messiah being come,
having not the tongue of the learned to know the
times and seasons to be in the Father`'s hand.
And Isaiah tells you of a way, that shall be called the '`way of holiness,
which shall be for those, the wayfaring men, though fools, shall not err therein,
and the redeemed shall walk in it,
and the ransomed of the Lord.`' Now are not your eyes blind to this way,
and your ears deaf from hearing it, this way of holiness,
where the unclean shall not walk over it?
Mark, is not this the way, the Messiah?
And in Isa.
xlii.
where he saith, '`behold my servant whom I uphold, my elect in whom my soul delighteth;
I have put my spirit upon him;
he shall bring forth judgment to the Gentiles.`' And this the Gentiles witness,
though your eyes are blind and cannot see this elect, this servant,
in whom God`'s soul delighteth, and hath put his spirit upon him,
who hath brought forth judgment to the Gentiles: '`A bruised reed he shall not break,
and the smoking flax shall he not quench; he shall bring forth judgment to truth;
he shall not fail nor be discouraged, till he hath set judgment in the earth,
and the isles shall wait for his law,`' etc. and many have received his law,
though you Jews have had the law, and the prophets have spoke of him that was to come,
who is come; you have shut your eyes and stopped your ears,
and have not received his law, though you read in the law and the prophets of him:
'`but I the Lord, have called thee in righteousness, and I will hold thine hand;
I will keep thee; I will give thee for a covenant of the people,
for a light of the Gentiles:`' Is not this the Messiah?
Is not this the Immanuel that is born of the virgin?
Yes, the Gentiles received this light and covenant, many thousands,
and witness both the promise of God, and the prophecies fulfilled.
And further he saith, '`the Lord saith, that he will open the eyes of the blind,
to bring the prisoners from the prison,
and them that sit in darkness out of the prison-house: I am the Lord, that is my name,
and my glory will I not give to another,
neither my praise to graven images:`' '`behold,`' saith he,
'`the former things are come to pass, and new things do I declare;
before they spring forth I tell you of them: sing unto the Lord a new song,
and his praise to the ends of the earth,`' etc.
And you may see further; '`the isles and the inhabitants thereof shall give glory to God,
and declare his praise in the isles.`'

So consider now, you whose eyes are blind, and are yet prisoners in prison,
and sit in darkness, and do not behold the new thing that the prophet declared, yea,
declared them before they sprung forth; and you who know not this new song,
cannot sing it to the Lord; but who knows the Messiah, knows this new song,
knows new things: many islands can declare his praise,
whom the Messiah hath brought out of darkness, the prison-house,
and opened the blind eyes, whom the Lord hath given for a covenant of the people,
for a light to the Gentiles, and to be his salvation to the ends of the earth;
now ye know ye had the old covenant before.
And the Lord says further, '`I will bring the blind by a way they know not;
I will lead them into paths which they have not known;
I will make darkness light before them, and crooked things straight;
these will I do,`' etc.
'`Hear ye deaf, and look ye blind, that ye may see; seeing many things,
but thou observest not; opening thine ears, but hearest not; is not this thy condition?
Behold, thus saith the Lord, which maketh a way in the sea,
and a path in the mighty waters,`' etc.
'`Remember ye not the former things, neither consider the things of old,
because I will make a new thing, and now it shall spring forth, and ye shall not know it;
the beasts of the field shall honor me,`' etc.
Now consider how ye have not truly minded the old things, nor the new thing.

And Isa.
1+++.+++ Doth not he there speak of the Messiah, of the Son of man who was not rebellious:
'`He that turned not away his back, but said, I gave my back to the smiter,
and my cheek to them that plucked off the hair,
and hid not my face from shame and spitting?`' And was not this the Immanuel,
born of a virgin, who came among you, according to the number of Daniel, the Messiah?
Did not you spit upon him?
Did not you whip and scourge him?
And did he turn his back from you smiters, whose eyes were blinded;
'`But the Lord had given him the tongue of the learned,
that he should know how to speak a word in season to him that is weary.`' etc.
He further saith, '`The Lord God will help me, therefore shall I not be confounded,
therefore I have set my face as a flint: behold the Lord will help me,
who is he that will condemn me?
lo, they all shall wax old as a garment, and the moth shall eat them up.`'

And now ye that will not receive the Messiah, the Immanuel, born of the virgin,
according to Daniel`'s number,
that little stone that hath dashed to pieces the four monarchies,
and is become a great mountain, and filled the whole earth;
and will not this stone fall upon your heads, and grind you to powder?
And are not you waxed old like a garment?
And have not the moths eaten up many of you?
And doth not Isaiah say in the 52d and 53d chapters,
'`Behold my servant shall deal prudently; he shall be exalted and be very high:
as many were astonished at thee; his visage was marred more than any man`'s,
and his form more than the sons of men.`'

And was not the Messiah served so with you Jews, when he came amongst you,
above sixteen hundred years since, were not you astonished at him?
Was not his visage marred?
But saith Isaiah, '`he shall sprinkle many nations.`' This we see,
though you whose eyes are blind cannot see;
the Lord hath made bare his holy arm in the face of all the nations;
and all the ends of the earth shall see the salvation of our God.
Is not this the Immanuel, born of a virgin, according to Isaiah`'s prophecy,
and Daniel`'s number; though seeing you see not, and hearing hear not;
close your eyes and stop your ears?
But Isaiah saith, Isa. 53:1-2. who hath believed our report?
To whom is the arm of the Lord revealed?
He shall grow up before him, as a tender plant, and as a root out of a dry ground;
he hath no form nor comeliness, and when we see him, there is no beauty,
that we should desire him.

And so is not this he that was born of a virgin, the Messiah;
that when he came among you, and to this day,
you could never see any form or comeliness or beauty, but spit upon him,
and buffeted him, and put your crown of thorns on him; yea,
says '`he was despised and rejected of men:`' and did not you despise him?
Did not you fulfill the prophets`' words?
'`He was a man of sorrows, and acquainted with grief, and we have hid our faces from him;
he was despised, and we esteemed him not.`' And did not you hide your faces from him,
and despise him when he came?
Did not you fulfill Isaiah`'s prophecy here concerning the Immanuel,
who was born of a virgin?
And saith Isaiah, '`but he was wounded for our transgression,
he was bruised for our iniquities, the chastisement of our peace was upon him,
and with his stripes we are healed; all we like sheep have gone astray,
and have turned every one to his own way,
and the Lord hath laid on him the iniquities of us all.`' All you
Jews everywhere have gone astray after your own way,
till you turned to the Immanuel, that was born of a virgin, that was the Messiah,
that came according to Daniel`'s number: '`he was oppressed, he was afflicted,
yet he opened not his mouth; he was brought as a lamb to the slaughter;
and as a sheep before the shearers is dumb,
so he opened not his mouth.`' And was it not you Jews that did oppress him,
and afflict him, and brought him as a lamb to your slaughter,
as a sheep before her shearer is dumb;
were not you the people that did thus deal with the
Messiah above sixteen hundred years since?
'`He was taken from prison and judgment, and who shall declare his generation?
For he was cut off from the land of the living;
for the transgression of the people was he stricken.`'

Now consider this you Jews;
was it not you that did take him from prison and judgment
and were not your forefathers and Pilate his judges,
who was cut off for the transgression, and was stricken for the people?
And you will never come out of your transgression, but through him, the Messiah,
the Immanuel, horn of the virgin.
'`He made his grave with the wicked, and with the rich in his death,
because he had done no violence, neither was deceit found in his mouth:
it pleased the Lord to bruise him, and to put him to grief,
when thou shalt make his soul an offering for sin; he shall see his seed;
he shall prolong his days; the pleasure of the Lord shall prosper in his hand.`'

Now here you may see, you Jews, here was an offering for sin,
who made his soul an offering for sin, and ended your offerings for sin;
this is beyond all your offerings, and this is the offering that pleased the Lord;
this was he that was born of the virgin;
this was the Messiah that Daniel numbers the years of the time when he should come,
and who came in your forefathers`' days, above sixteen hundred years since,
and made his soul an offering for sin;
and he did see his seed in the days of his disciples and apostles, and now;
and the pleasure of the Lord did prosper in his hand, and doth.
Isaiah saith, '`he shall see the travail of his soul, and be satisfied;
by his knowledge shall my righteous servant justify many,
for he shall hear their iniquity.`'

Now you that do not believe in him, though he was an offering for your sin,
how can you be justified?
Or how can you believe in Moses or any of the prophets that testified of him,
that do not believe in him?
And therefore, saith the Lord, '`I will divide him a portion with the great,
and he shall divide the spoil with the strong,
because he hath poured out his soul unto death; he was numbered with the transgressors;
he bore the sins of many,
and made intercession for the transgressors.`' Now
you that do not believe that he bore your sins,
though he was numbered with the transgressors;
and you that do not believe that it is he that you crucified,
who is the Son of the virgin, that must make intercession for you,
you neither believe in the prophets nor in the Messiah, nor ever can come to God,
but by him that makes intercession for you, and bears your sins.

Doth not Isaiah complain in chapter iii.
how his '`name was blasphemed every day?`' And did
not you blaspheme against his son when he came?
'`But my people shall know my name in that day, that I am he that speaketh;
behold it is I.`' Now here was a day to come,
and happy were those of you that did behold the day when it came; yea,
the day of the Messiah, and do behold it now.
'`And how beautiful upon the mountains are the feet of him that publisheth peace,
that bringeth glad tidings of good, that publisheth salvation, that saith to Zion,
thy God reigneth.`'

In Isa.
lv. '`Ho, every one that thirsteth, come ye to the waters; come he that hath no money,
come, buy and eat; yea, come buy wine and milk without money and without price, etc.
Incline your ears, and come to me; hear, and your souls shall live,
and I will make an everlasting covenant with you, the sure mercies of David:
behold I have given him, a witness to the people, a leader and commander to the people:
behold thou shalt call a nation thou knowest not; nations that know not thee,
shall run to thee, because of the Lord thy God.`'

Now mark, ye Jews; this everlasting covenant which God would make;
you had the first covenant that spoke of this witness which God gives, and this leader,
and this commander to the people, that should call a nation,
and nations should run unto him; is not this the Messiah and Immanuel,
that was born of a virgin, according to Isaiah and Daniel`'s prophecy;
whom you hid your faces from, were ashamed of, and spit upon.
And in Isa.
lxii.
'`The Gentiles shall see thy righteousness, and all kings thy glory,
and thou shalt be called by a new name, which the mouth of the Lord shall name.`'

And is not this brightness, and salvation, and this righteousness, and glory,
that the Gentiles and all kings shall see, and this new name which the Lord shall name;
is not this the Messiah, the Prince?
'`And thou shalt be a crown of glory in the hand of the Lord,
a royal diadem in the hand of thy God.`' And in chapter lxv.
Isaiah saith, '`the Lord saith, I was sought of them that asked not for me,
I was found of them that sought me not.`' And were not these
the Gentiles which the Messiah was promised to,
who have received him?
Many have received him; so the Lord saith; '`behold me, behold me,
to a nation that was not called by my name:`' but concerning you Jews, he saith,
'`I have spread out my hands all the day to a rebellious people,
who walked in a way that was not good, after their own thoughts,
a people that provoked me to anger continually to my face,`' etc.

So you may read your rebellion, how you provoked him,
from Moses throughout all the prophets, until you came to the Messiah, whom you spit at:
and see how other nations have received the Messiah, and run after him;
and so when you call, the Lord shall not answer, because that you reject his Son.
And doth not Jeremy say, '`as a cage was full of birds,
so were your houses full of deceit; and therefore repent and turn.`' And in Jeremy xxxi.
'`behold the day has come, saith the Lord,
that I will make a new covenant with the house of Israel, and with the house of Judah;
not according to the covenant that I made with their fathers,
in the day that I took them by the hand, to bring them out of the land of Egypt,
which my covenant they broke, though I was a husband to them,
saith the Lord.`' Here you (may see you forsook your husband) that broke the covenant.
But here is a new covenant, which is not according to the old:
and now this new covenant you have not received, and will not receive: for as he said,
'`I will give him for a covenant, that is the Messiah,
he that was born of a virgin.`' '`But this is the covenant
that I will make with the house of Israel after those days.`'

Now here are the days of the old covenant; here are the days of the new,
'`saith the Lord, I will put my laws in their hearts,
and write them in your inward parts; and I will be their God,
and they shall be my people; and they shall not teach every man their neighbour,
and every man his brother, saying, know the Lord, for they shall all know me,
from the least of them, to the greatest of them, saith the Lord.`'

And it is said in Isa.
liv. '`All thy children shall be taught of the Lord,
and great shall be the peace of thy children;
in righteousness shalt thou be established,`' etc.
So consider, you will never own the new covenant, until you own the Messiah is come.
In Jeremy xxxii.
'`I will make an everlasting covenant with them, that I will not turn away from them,
to do them good; but I will put my fear in their hearts,
that they shall not depart from me so now this is
the new covenant which you must all receive,
if you come to be God`'s people, and he your God;
and to have the one heart and the one way, it must be in this everlasting covenant.

And you that crucify the Messiah, did not God raise him up the third day,
that he might live in his sight?
So if ever you live to God, it is through him; for in Hosea vi.
'`After two days he will revive us; in the third day he will raise us up,
and we shall live in his sight.`' And was not this a prophecy of the work of the Messiah,
whom you crucified.
'`For the Lord desired mercy of you and not sacrifice,
and the knowledge of God rather than burnt offerings, but you, like men,
have transgressed the covenant, and dealt treacherously against me,
saith the Lord.`' Micah saith, in the 4th chapter,
'`that in the last days the mountain of the Lord`'s
house shall be established on the top of the mountains,
and shall be exalted above the hills, and people shall flow unto it,
and many nations shall come and say,
come and let us go up to the mountain of the house of the Lord,
to the house of the God of Jacob, and he will teach us of his ways,
and we will walk in his paths,`' etc.
Now, ye Jews, consider this; is not this the new covenant,
where many nations now come to be taught of God?
And God doth teach them his ways to walk in; and he shall judge among the people,
and judge many strong nations, etc.
And is not this in the days of the Messiah, which many witness.

And Micah v. '`but thou Bethlehem Ephratath,
though thou be little among the thousands of Judah,
yet out of thee shall come forth to me, that is to be a ruler in Israel,
whose goings forth have been from of old, from everlasting;
and he shall stand and feed in the strength of the Lord,
in the majesty of the name of the Lord his God;
for now he shall be great to the ends of the earth.`' etc.
And now ye Jews,
was it not here prophesied that the Messiah should come out of Bethlehem of Judah,
to be a ruler; and this is the Son that the virgin bore, the Immanuel: and when she,
Mary the virgin, had brought forth, who was advised by the angel what to call her Son,
to wit, Jesus; all Jerusalem was on an uproar; look back you Jews:
and did not Herod your king, who was troubled also,
gather all the chief priests and scribes of the people,
and demanded of them where the Messiah should be born?
And they said to him, '`in Bethlehem Judah;`' so saith the prophet.
Mic. v. '`For thou Bethlehem in the land of Judah,
though thou be the least among the thousands of Judah,
yet out of thee shall come forth to me, that is to be a ruler in Israel,
whose goings forth have been from of old, from everlasting:
and he shall stand and feed in the strength of the Lord,
in the majesty of the name of the Lord his God;
for now he shall be great to the ends of the earth.`' etc.
And now ye Jews was it not here written,
that the Messiah should come out of Bethlehem of Judah, to be a ruler?
And this is the Son that the virgin bore, the Immanuel.

And did not Herod in his envy seek the destruction of this Messiah?
And therefore not killing him,
that it might be fulfilled which was spoken by Jeremy the prophet, ch.
xxxi.
when he had killed the children from such an age: '`thus saith the Lord,
a voice was heard in Ramah, lamentation and bitter weeping;
Rachel weeping for her children, and would not be comforted,
because they were not.`' And the Messiah was carried down into Egypt,
when Herod sought his life, that it might be fulfilled which was spoken of him;
'`out of Egypt have I called my Son.`' Hos.
xi. So here you may see it is clear, how the Messiah was born in Bethlehem;
now number you according to the prophecy:
a virgin had a child and called his name Immanuel; whether was he not born in Bethlehem,
according to Daniel`'s number, and the prophets`' prophecy of him?

And in Psal.
ii. '`why do the heathen rage, and the people imagine a vain thing;
the kings of the earth set themselves,
and the rulers take counsel together against the Lord, and against his anointed.`'

Is not this the Messiah?
And was not this fulfilled amongst you when he came?
And to this day do not ye rage against him?
But further he saith in the same psalm, '`thou art my Son, this day have I begotten thee,
therefore kiss the Son, lest he be angry,
and ye perish from the way when his wrath is kindled but a little,
blessed are all they that trust in him,`' in this Son.
And again he saith, in Psal.
xvi. '`I have set the Lord always before me, because he is at my right hand,
and I shall not be moved; and therefore my heart is glad, and my glory rejoiceth:
my flesh also shall rest in hope, for thou wilt not leave my soul in hell,
neither wilt thou suffer thy holy one to see corruption.`'

Now is not this the Messiah, the Immanuel, born of the virgin,
that sign that God gave to you, who wrought signs and miracles among you,
though you despised him, and wondered at, and crucified, and buried,
who rose the third day, and did not see corruption; but God raised him up,
who is at his right hand: and did not your priests give the soldiers large money,
that watched his sepulchre where he was laid, to say,
that the disciples stole him away by night?
And did not you crucify him between two thieves?
And was not he named among transgressors?
Read Isaiah before: and when ye crucified him, did not ye Jews say,
'`He trusted in the Lord, that he would deliver him, seeing he loveth him.`' Psalm xxii.
And in Wisd.
ii. did not you fulfill the sayings there: '`He maketh his boast that God is his Father,
let us see if his words be true, let us prove what will happen in the end of him;
for if the just man be the Son of God,
he will help him and deliver him from the hand of his enemy;
let us condemn him with a shameful death.`' And this you did when ye crucified the Messiah:
as it is said in Psalm xxxi.
'`into thy hand I commit my spirit,`' etc.
And in Psalm xxxiv.
'`He keepeth all his bones not one of them is broken:
so this was fulfilled upon the Messiah,
not a bone of him was broken;`' though ye broke the thieves`' legs,
yet had not power to break his bones: therefore it is said in Psalm xl.
'`sacrifice and offerings thou didst not desire; mine ears hast thou opened;
burnt-offerings and sin-offerings hast thou not required: +++[+++mark, ye Jews,]
then said I, lo, I come, in the volume of the book, it is written of me,
I delight to do thy will, O my God;
yea thy law is within my heart.`' Is not this the Messiah, the Immanuel,
whom ye crucified?
In the volume of the law and prophets it was written of him;
you must never expect to see any other.
And so in Isa.
xxxvi.
'`I have trodden the wine-press alone.`'

So if you Jews did mind, Hosea vi.
'`the Lord desired mercy and not sacrifice,
the knowledge of God more than burnt-offerings.`'
And when this sign was brought forth among you,
that this virgin had a child, Immanuel;
'`then did the Lord confirm his covenant with an oath, which he made with Abraham,
Isaac and Jacob, concerning the Messiah,`' Psalm cv.
And Psalm cx.
'`the Lord said to my Lord, sit that on my right hand,
till I make thine enemies thy footstool, etc.
The Lord hath sworn and will not repent;
thou art a priest forever after the order of Melchizedek:`' and is not this the Messiah,
the Immanuel, which came among you, according to Daniel`'s number?
And in Psalm cxviii.
'`the stone which the builders refused is become the head-stone of the corner;
this is the Lord`'s doing, it is marvellous in our eyes.`'

And is not this the Immanuel, which was born of a virgin, the Messiah,
which came to you according to Daniel`'s prophecy above sixteen hundred years ago,
whom you Jews, that were the pretended builders of people up to heaven,
refused and rejected?
And therefore, were not your cities,
your houses and religion all thrown down by the storm of Titus,
and you blown over all nations?
And in Psalm cxxxii.
for thy servant David`'s sake, turn not away the face of thine anointed:
the Lord hath sworn in truth to David, he will not turn from it,
of the fruit of thy body will I set upon thy throne,
there will I make the horn of David to bud; I have ordained a light for mine anointed.`'

Now you Jews, doth not this speak of the Messiah?
And was not he to come of the seed of David and Abraham, as God had promised and sworn?
And see in Daniel, if he did not come according to the angel Gabriel`'s number.
And in Isa.
viii.
'`He shall be for a sanctuary, for a stone of stumbling,
for a rock of offence to both the houses of Israel, for a gin,
for a snare to the inhabitants of Jerusalem; and many among them shall stumble and fall,
and be broken, and be snared, and taken; bind up the testimony,
seal the law among my disciples.`' Is not this spoken of the Messiah?
and were not you the people that stumbled and, fell?
was not he a rock of offence for both the houses of Israel?
He was no sanctuary to you that stuck in your outward sanctuary.
And did not many thousands among you Jews wait for the Messiah,
and receive him at that time when he came?
And many of his disciples which believed on him, and received him,
among whom the law and testimony was bound up and sealed among them;
and you stumbled at him, this stone:
is not this the stone that Daniel interpreted in Nebuchadnezzar`'s dream,
that should dash to pieces the four monarchies, and become a great mountain,
and fill the whole earth, which should set up a kingdom that should never have an end;
and your kingdoms had an end, and is ended.
Was not he a priest forever after the order of Melchizedek?
But your priests died, and had an end; and though you crucified him, yet he is risen,
and is at the right hand of God, and is a priest forever,
who ever liveth to save to the utmost, and makes intercession,
who is not after the order of Aaron, but after the order of Melchizedek.

And it is said of the Redeemer, Isa.
lxi. '`he shall put on righteousness as a breast-plate,
and an helmet of salvation upon his head;
and he shall put on the garment of vengeance for clothing,
and he was clad with zeal as a cloak; and the Redeemer shall come to Zion, and,
to them that turn from transgression in Jacob, saith the Lord.
As for me, this is my covenant, saith the Lord, my spirit that is upon thee,
and my words that I have put in thy mouth, shall not depart out of the mouth of thy seed,
nor out of the mouth of thy seed`'s seed, saith the Lord,
from henceforth and forever.`' So many did witness this fulfilled when the Messiah came,
according to the prophets, to you Jews: many received him; but you Jews,
that turned not from your transgressions (but lived in your blindness,) stumbled,
and darkness covered you, gross darkness!

But in Isa.
lx. '`the Gentiles shall come to his light.`' This prophecy many of the Gentiles witness,
that are come to his light.
For it is said, '`a little one shall become a thousand, a small one a strong nation;
I the Lord will hasten it in his time.`' Is not this the branch of the Lord`'s own planting?
and many are witnesses of it, though you cannot see it this day, and see his kingdom.
'`The gates are open day and night, that men may bring to thee the force of the Gentiles,
and that their kings may be brought,
+++[+++though you blind Jews cannot see it and they shall call thee the city of the Lord,
the zeal of the Holy One of Israel, he who is the joy of many generations.
Thou shalt suck the milk of the Gentiles;`' signifying that the Gentiles have a breast.

And in Isa.
lxi. '`the spirit of the Lord is upon me,
he hath anointed me to preach good tidings to the meek;
he hath sent me to bind up the broken heart, to proclaim liberty to the captives,
and the opening of the prison to them that are bound.`' etc.
And was not this fulfilled when he came, according to Daniel`'s prophecy?
And did not he open the book among your people, and tell you, it was fulfilled,
in one of your synagogues at Nazareth, when one of you delivered him the book of Isaiah?
then you did wonder at him, at the gracious words for a time;
but you were quickly changed, and thrust him out of your city,
to throw him down the brow of your hill.

Isa.
lxvi.
Where he saith, '`heaven is my throne, earth is my footstool;
where is the house that ye will build to me?
Where is the place of my rest?`'

And you that look so much at your outward temple, did not the Messiah tell you,
'`that it should be thrown down,
and not one stone left upon another in that generation?`' And was it not done by Titus?
And have you built it since?

And doth not the Lord say, '`All these things have my hands made,
and all these things have been, saith the Lord; but to this man will I look,
even to him that is poor, and of a contrite spirit,
and trembleth at my word.`' And in Jeremiah xxxi.
'`this is the covenant that I will make with the house of Israel, after those days,
saith the Lord, I will put my law in their inward parts, and write them in their hearts,
and I will be their God, and they shall be my people:
they shall teach no more every man his neighbour, and every man his brother, saying,
know the Lord; for they shall all know me, from the greatest to the least of them,
saith the Lord; for I will forgive their iniquities,
and their sins I will remember no more.`' And now mark,
this is a covenant after these days: you had the old covenant before,
where ye were teaching one another his brother, etc. and where ye were writing the laws,
the laws written on tables of stone; but here the Lord is the writer,
in the new covenant, to write them in your hearts: so, as you receive this covenant,
and come into this covenant, your sins and iniquities will be forgiven,
and be remembered no more.
So God saith, '`I will give him for a covenant,`' meaning his Messiah,
he that is born of a virgin, that you crucified: if you receive not him,
do you think your sins and iniquities will not be remembered?

And how can you, or dare you, take the title to be called God`'s people?
For, '`they shall be my people, and I will be their God, that come into this covenant,
which God giveth, which is the new covenant,`' for you had the old before.

Read Jer xxxi.
'`and I will give them one heart,`' Ezek.
xi. '`and I will put a new spirit within them;
I will take away the stony heart out of their flesh,
and I will give them a heart of flesh.`' Now they that believed in the Messiah,
are witnesses of this; yea,
those Jews that believed in him above one thousand six hundred years since,
witnessed this new spirit, this one heart, this heart of flesh, and this new covenant;
but you that did not, and do not believe, witness the stony heart and old spirit,
pouring about the old covenant, and stumbling at the new,
and are breakers of the old too, and despisers of the new covenant,
and of God`'s oath concerning it.

And again, the Lord saith in Ezek.
xviii.
'`cast away from you all your transgressions, whereby ye have transgressed,
and make you a new heart and a new spirit: for why will ye die, ye house of Israel?
For I have no pleasure in the death of him that dieth, saith the Lord,
wherefore return and live ye.`' Now here you Jews may see,
that without turning from transgression you do not live, neither have you a new heart,
nor a new spirit, and not turning you die.
And the Lord saith, '`he hath no pleasure in it, and in your death.`' Ezek.
xxxiv.
'`I will set up one shepherd, saith the Lord, and he shall feed them,
and he shall be your shepherd: I the Lord will be your God, and my servant David,
a prince; and I will make with them a covenant of peace.`'

And is not this one shepherd, that the Lord will set up, the Immanuel,
born of the virgin, which came according to the prophecy of Isaiah,
and according to Daniel`'s number?
And when he was come, did not he say, that he was the '`true shepherd,
that laid down his life for his sheep?`' And is not
he the covenant of peace spoken of by Ezekiel?
Did not he come of the seed of David?
and did not, and do not you yet reject this shepherd, this feeder,
and his covenant of peace, and this seed of David?
And therefore what evil seed are ye run into?

And Ezekiel in the 36th chapter, saith the Lord, '`I will sprinkle clean water upon you,
and ye shall be clean, etc.
And I will give you a new heart, and a new spirit I will put within you,
and take away your stony heart, etc.
And I will open your graves, and I will bring you out of your graves,
and put my spirit in you.
Moreover, I will make a covenant of peace with you,
which shall be an everlasting covenant,
and I will set my sanctuary in the midst of them forevermore;
my tabernacle also shall be with them, and I will be their God,
and they shall be my people, and David shall be their prince forever.`'

This you must know was the Messiah, the seed of David, for David was dead long before:
but you must be come out of your graves of sin and wickedness, and your own traditions,
and come out of the old covenant, and come into the new; if ye know this seed of David,
the Messiah, you must come out of the seed of transgression and rebellion,
blindness and darkness, and see yourselves in the graves, and your bones scattered,
before you be gathered to this one shepherd,
that God sets over his people in the new covenant.
Read the 36th and 37th of Ezekiel.

Micah iv.
'`In the last days it shall come to pass,
that the mountain of the house of the Lord shall be established on the top of the mountains,
and it shall be exalted above the hills; and many nations shall come, and say,
come let us go up to the mountain of the Lord, to the house of the God of Jacob,
and he will teach us of his ways, and we will walk in paths;
for the law shall go forth of Zion,
and the word of the Lord from Jerusalem.`' Now you that did not
receive the Messiah have not lost these last days of God`'s teaching,
and neglecting these last days of God`'s teaching, which many are come to, and can say,
'`he doth teach them of his ways, and they walk in his paths.`'

And this kingdom that should come to the daughter of Jerusalem,
many in the time when the Messiah came did both receive him as king,
and were heirs of his kingdom; and so there are many at this day:
but you that rejected the Messiah, rejected both king and kingdom,
and God`'s teaching on his mountain.
Mic. iv.
And so the saying of Habakkuk 1:5, is come upon you, '`behold ye among the heathen,
and hearken and wonder; for I work a work in your days which ye will not believe,
though it be told you;`' for ye would not believe Jeremy the prophet,
nor the other prophets, nor the Son, the Messiah, the Immanuel, born of the virgin;
though they that did believe in him, the just, shall live by his faith.
So you may see in Habakkuk 2:4, for the vision was for an appointed time,
and in the end it did speak, the vision or the sign, as you may read in Daniel,
and Isaiah.

And Zach.
xii. 10, where the Lord saith, '`I will pour upon the house of David,
and upon the inhabitants of Jerusalem, the spirit of grace and of supplication,
and they shall look upon him whom they have pierced, and they shall mourn for him,
as one mourneth for his son, his only son; and they shall be in bitterness for him,
as one that is in bitterness for his first born.`' And now mark, ye Jews,
what him is it that ye have pierced?
Is it not the Immanuel, born of a virgin, the Messiah,
which came according to Daniel`'s number of years?
They that did believe in him did mourn bitterly, and were pricked in their hearts;
so you may look back above one thousand six hundred years since;
they came to be the learners of him:
and you that stand still in your blindness and hardness of heart, and have not mourned,
and do not believe in him that you have pierced,
you cannot witness the spirit of grace and supplication upon you yet,
as they had that did look upon him that they had pierced. Mal. 3.
'`And behold, saith the Lord, I will send my messenger,
and he shall prepare the way before me:
and the Lord whom ye seek shall suddenly come to his temple, etc.
But who shall abide the day of his coming?
For he shall sit as a refiner`'s fire,`' etc. Mal. 4:5.
'`Behold, I will send you Elias the prophet before the coming
of the great and terrible day of the Lord:
and he shall turn the hearts of the fathers to the children,
and the hearts of the children to the fathers;
lest I come and smite the earth with a curse.`' And when this Elias did come,
did not ye do to him what ye listed?
And so, did not he come before the Messiah, and prepare the way before him?
For ye did believe that John Baptist was a prophet, some of you; and some said,
that he was a devil: for did not Isaiah prophesy of him in the 40th chapter,
and the 3d verse?
'`The voice of one crying in the wilderness, prepare the way of the Lord,
make his paths straight; every valley shall be filled,
and every mountain and hill shall be brought low, and the crooked shall be made straight,
and the rough ways smooth,
and all flesh shall see the salvation of God.`' Now was not this John,
the son of Zachariah, that Isaiah prophesied of?
Did not John here fulfill Isaiah`'s prophecy, the forerunner of Christ?
So, if you will neither believe the prophet Isaiah, nor John the prophet,
nor the Messiah, the Immanuel, born of a virgin,
which came according to the number of the angel to Daniel,
but your crooked paths are not made straight,
nor your rough spirit and mind is not made smooth,
and your mountain of sin is not brought low;
and therefore how were ye like to see the salvation of God when he came;
but you hid your faces from him, and so fulfilled Isaiah`'s prophecy.
But when God had given you a temple, when the Messiah came,
he found in the temple such as sold oxen, sheep, and doves;
and money changers sitting there, which should have been a house of prayer:
and so was not here the Psalm fulfilled? Ps. 69:9.
'`The zeal of my Father`'s house hath eaten me up.`'

Zach.
ix. 9. '`Rejoice greatly, O daughter of Zion, shout, O daughter of Jerusalem: behold,
thy king cometh to thee; he is just, and having salvation; lowly, and riding upon an ass,
upon a colt, the foal of an ass.`' Now consider, did not he come so into your Jerusalem,
this Immanuel, this Messiah?
And did not many of your daughters rejoice, and cried Hosanna?
But your priests that were blind, and the rest of the scribes and pharisees and Jews,
railed at him, and blasphemed against him.
'`But he is he that speaks peace to the heathen, and his dominion is from sea to sea,
and from the river to the ends of the earth.
And as for thee also, in the blood of thy covenant,
I have sent forth thy prisoners out of the pit wherein is no water.`' Zach.
ix. 10, 11.

And in Zach.
xi. 12, 13. '`And I said to them, if ye think good, give me my price; if not, forbear:
so ye weighed to me my price thirty pieces of silver; and the Lord said to me,
cast it to the potter, a goodly price that I was prized at by them;
so I cast them to the potter in the house of the Lord.`' And did
not your high priest give Judas thirty pieces of silver,
to betray the Messiah?
So was not this prophecy fulfilled upon you, as David says in Ps. 41:9, '`yea,
may own familiar friend, that did eat of my bread,
hath lifted up his heel against me:`' was not this fulfilled in your Judas?

Also, David saith, in Ps. 69:21-23, '`They gave me gall for my meat,
in my thirst they gave me vinegar to drink: let their table become a snare before them,
and their posterity a ruin: let their eyes be darkened, that they see not;
make their joints continually shake; let their habitation be desolate,
and let none dwell in their tents.`' Now, consider when the Messiah was come,
and when ye crucified him, did not ye give him vinegar and gall to drink?
And was not your table become a snare and a trap to you, and your eyes blinded,
and your habitations desolate, which ye had at Jerusalem in David`'s time?
So how can you say,
that that was not the Messiah in all these prophecies
you have so fulfilled upon the Messiah?
And in Ps. 109:8, etc.
'`let his days be few; let another take his office:`' this was spoken of Judas,
to whom your chief priests gave thirty pieces of silver,
that he might betray the Messiah into your hands '`let another
take his office;`' so another disciple of Jesus,
the Messiah, the Lord, was put in his room: so this was fulfilled, Ps. 22:16-17,
'`for dogs have compassed me; the assembly of the wicked have enclosed me;
they pierced my hands and my feet; they parted my garments among them,
and cast lots upon my vesture.`' and now, ye Jews,
did not ye often assemble together to crucify him?
and when you did crucify him, did not you pierce his hands and feet?
and did not you part his garments among you, the Messiah, when they crucified him?
and did not your soldiers cast lots upon his vesture?
and doth not Moses say, in Deut.
xviii.
'`the Lord thy God will raise up a prophet in the midst of thee, of thy brethren,
like to me, to him shall ye hearken.`' And further he saith,
'`I will raise them up a prophet of their brethren, like to thee,
and I will put my words in his mouth,
and he shall speak to them all that I shall command him; and it shall come to pass,
that whosoever shall not hearken to my words that he shall speak in my name,
I will require it of him.`' Now this prophet, like to Moses, was the Messiah,
which was the sign born of a virgin, according to the prophecy of Isaiah:
and Daniel numbered the years to the Messiah, and the time that he should be cut off,
should make his soul a sacrifice, according to the prophet;
'`and there rose not a prophet since in Israel, like to Moses,
whom the Lord knew face to face,`' as it is said in Deut.
xxxiv.
So this prophet that God has raised up; like Moses,
whom the people should hear in all things, was not Joshua, but the Messiah,
whom you would not, nor did not hear; and so not hearing him, you hear not the prophets.
And God said to Abraham,
'`in thy seed shall all the families of the earth be blessed.`' Gen.
xii. And Gen.
xviii.
'`All the nations of the earth shall be blessed in Abraham`'s seed;
and I know he will command his children and his household after him,
and they shall keep the way of the Lord to do justice and judgment.`' And in Gen.
xxii.
'`The Lord said to Abraham, by my self have I sworn, because thou hast done this thing,
and hast not withheld thine only son; that in blessing I will bless thee,
and in multiplying I will multiply thee as the stars of heaven,
and in thy seed shall all nations of the earth be blessed.`'
And so was not Abraham`'s offering up his only son Isaac,
a type of the Messiah`'s making his soul an offering,
the Messiah`'s making his soul a sacrifice for the sins of men,
who according to the flesh was of the seed of Abraham, who was the son of God,
a sign and wonder to you to this day, that a virgin should have a child?
And did not Jacob say on his deathbed, Gen. 49:10-11,
when he called his sons together, he said to Judah, when he prophesied to them all;
'`Judah, thou art he whom thy brethren shall praise;
thy hand shall be on the neck of thine enemies;
thy father`'s children shall bow down before thee;
the sceptre shall not depart from Judah,
nor a law-giver from between his feet till Shilo come,
and unto him shall the gathering be of the people?`' And now consider,
did not the sceptre continue in Judah till Shilo, the Messiah came?
But is not the sceptre departed from Judah above sixteen hundred years since,
after you had crucified the Messiah?
And are not your walls and city of Jerusalem broken down, trodden under foot,
and you scattered over all nations?
And so is not your sceptre gone?
So consider these things, how long it is since you lost your sceptre:
it should not depart till Shilo came; and he came, and is come,
and you would not hearken to him, being a stiff-necked people.

Is it not clear that the Messiah came of the seed of David and of Abraham,
according to the prophets, who was born of a virgin, though you were rebellious,
as you may see from Moses through the prophets to the Messiah;
though some of you in all ages did believe, yet for the generality of you,
what a stiff-necked people you were, that your eyes were blinded,
your table was made a snare, and you stuck in the old covenant, and opposed the new:
and were not your backs often therefore bowed down; yea,
and under all the governments of the world now:
and so Isaiah`'s prophecy is come upon you, saying,
'`go tell this people.`' Isa. 6:9. '`hearing ye hear not, seeing ye see not,
and do not perceive; for the heart of this people is waxed gross,
and their ears are dull of hearing; and their eyes have they closed,
lest they should see with their eyes, and hear with their ears,
and understand with their hearts, and should be converted,
and I should heal them;`' this is a sad condition: you would not receive the Immanuel,
born of a virgin; and therefore, was not the salvation sent to the Gentiles,
that the Gentiles might glorify God for his mercy through the Messiah?
'`For this cause I will confess thee among the Gentiles,
and sing to thy name.`' Ps. 18:49. And again he saith, '`rejoice ye Gentiles,
with his people.`' Now those Jews that were the believers in the Messiah,
the Gentiles can rejoice withal.
And Psalm cxvii.
'`praise the Lord ye Gentiles, and laud him all ye people.`' And again Isaiah saith,
'`there shall be a root of Jesse, and he shall rise to reign over the Gentiles,
in him the Gentiles shall trust.`' Now this is the Messiah that was born of a virgin,
whom ye crucified, who is risen, in whom the Gentiles rejoice and trust,
who is their salvation; read Isa. 11:10. And so it was said before to you;
'`like to me, (saith Moses,) will God raise up a prophet of your brethren,
him shall ye hear in all things, whatsoever he shall say to you;
and that soul that will not hear this prophet,
shall be destroyed from among the people.`' So was not the Messiah of the seed of David,
and of Abraham; and when God had raised up, and brought him forth,
you would not hear him, neither before ye crucified him, nor now when he is risen,
who came according to Daniel`'s prophecy: and so in this you neither hear God, nor Moses,
nor the prophets, nor the angel, nor the Son, the Messiah;
and so in this you neither keep the law, nor the prophets, nor the old covenant,
nor the new, though you often spoke fair with your mouths, but your hearts were far off.

Is not that come to pass which the Messiah spoke to you,
that you should be led away captive, and many should fall by the edge of the sword,
and Jerusalem should be compassed with armies, and you should be led captive,
into all nations, and Jerusalem shall be trodden down,
(read in Daniel ix.) and was not Jerusalem built and standing till Messiah, the Prince?
and when he came, was not he cut off?
And after did not Titus, the prince of the people,
come to destroy your city and sanctuary; therefore was not this the true Messiah,
the Immanuel, born of a virgin, and the prophet, that you should hear in all things;
and they that did hear him, and do hear him,
do witness the prophecy of Joel to be fulfilled;
'`the Lord is pouring out of his spirit upon all flesh, his sons, his daughters,
his old men, his young men, servants, handmaids these are the days of the Messiah;
for he says,
in those days I will pour out my spirit:`' so by the spirit of God they can praise God,
sons, daughters, old men, young men, servants, handmaids; through the Messiah,
the Immanuel, who was born of a virgin, whom you crucified, and is risen,
and is at the right hand of God, who is our prophet, and shepherd, and covenant of peace,
through him we can praise God, hallelujah forever and ever, amen.

And you that despise him, despise your salvation,
and lie under the judgment of the prophets and the Son, as you may see in the scriptures;
and therefore, it is time for you to repent, and turn to him.

[.postscript]
====

[.blurb]
A Postscript.

[.small-break]
'''

Not a bone of the Pascal-Lamb shall be broken. Num. 9:12.
And was not this a type of the Pascal-Lamb, the Messiah,
of whom you had not power to break a bone,
although you broke the bones of the two thieves that were crucified on each side of him.

And in Deut.
viii.
there you may see how the Lord in the wilderness humbled your fathers to reprove them,
and to know what was in their hearts, whether they would keep his commandments or no;
therefore he humbled them, and made them to hunger, and fed them with manna,
which they knew not, neither did their fathers know it, that he might teach them,
that man liveth not by bread only,
but by every word that proceedeth out of the mouth of the Lord doth a man live;
yet how soon did your forefathers forget the Lord, and lusted after Egypt`'s flesh-pots,
as ye may read in the books of Moses, how your forefathers murmured against the Lord,
and turned against him, and his prophets, and his Son, the Messiah;
against whom you stand in rebellion to this day.

Psalm viii.
And was not this fulfilled when the Messiah rode into Jerusalem upon the foal of an ass?
'`out of the mouths of babes and sucklings hast thou ordained strength.`'

And did not the Messiah say these words when you put him to death?
Psalm xxxi.
'`into thy hand I commend my spirit: and thou hast brought my soul out of the grave,
thou hast revived me from them that go down into the pit, sing praises unto the Lord,
ye his saints.`' So the saints can sing praises unto the Lord,
that know the resurrection of the Messiah, whose grave you watched; yet he rose,
and all your watchmen were struck: but your priests taught them to lie, and to say,
'`his disciples stole him away:`' in which lie, and graves of sin and unbelief you lie,
that do not believe the Messiah is come, and is risen. Ps. 30:3.

And was not this the doctrine of the Messiah to your forefathers,
'`that the meek men should possess the earth,
and have their delight in the multitude of peace;
but the wicked practiseth against the just,
and gnashes his teeth against him.`' And was not this the
practice of your forefathers against the Messiah? Ps. 37:12.

And in Psalm lxxviii.
'`I will open my mouth in parables;
I will declare high sentences of old.`' And did not the Messiah fulfill these sayings,
and declare the high sentences of old, and speak in parables when he came?

And in Psalm lxxxii.
where it is said, '`I have said ye are God`'s,
and ye all are children of the Most High.`' And did not your forefathers
persecute and put to death the Messiah for saying,
'`He was the Son of God?`'

And in Psalm xci.
'`He shall give his angels charge over thee, to keep thee in all thy ways;
they shall bear thee in their hands,
that thou hurt not thy foot against a stone.`' And was not
the Messiah tried and tempted by Satan and you in your days,
wherein that scripture was fulfilled upon him, when Satan tempted him,
and perverted those words?

And in Psalm cx.
where it is said, '`the Lord said unto my Lord, sit thou on my right hand,
until I make thy enemies thy footstool.`' Is not this the Messiah, and the Immanuel,
born of a virgin, spoken of Esaiah, which came and said to your forefathers,
above sixteen hundred years since, '`if David in spirit called the Messiah Lord,
how was he his son?`' which neither your forefathers nor you ever answered?

Also, '`the Lord swore, and will not repent; thou art a priest forever,
after the order of Melchizedek.`' Now was not this the Messiah,
who came not after the order of Aaron, which had a beginning of days, and end of life;
but He, the Messiah, is a priest forever, after the order of Melchizedek,
is without beginning of days, or end of life.

And is not the prophecy of Isa. 5.
fulfilled upon you, where he saith, '`the vineyard is laid waste,
and you which were the keepers of it, who stoned the servants, and had killed the son,
the heir;
and now are you and your vineyard laid waste?`' And did not the Messiah when he came,
show you the fulfilling of the prophecy in this?
And so is not your sun and moon darkened, and your stars fallen,
as you may read in the prophets?
And the marvellous work the Lord hath done upon you and a wonder?
For the wisdom of your wise men is perished;
for the Lord hath covered you with the spirit of slumber, and hath shut up your eyes;
and the vision is become unto you as the words of a sealed book,
so that you can neither read the book of the prophets, nor of the law,
that speak of the Messiah, being out of the spirit:
though you come near unto the Lord with your mouths, and honour him with your lips,
but have removed your hearts far from him;
and your fear towards him is taught by the precepts of men;
and this did Isaiah foresee and prophesy of; and this did the Messiah see,
and find amongst you when he came.

And in Isa. 54. it is said,
'`all thy children shall he taught of the Lord.`'
And did not the Messiah when he came,
show the fulfilling of this prophecy,
so that many thousands are witnesses of God`'s teaching,
and his establishing of them in peace?

And was not the saying of Jeremiah the prophet fulfilled. Jer. 7.
'`Is this house become a den of thieves, whereupon my name is called before your eyes?
behold I see it saith the Lord.`' And was not this fulfilled in the days of the Messiah,
above sixteen hundred years since?
And did not the Lord say, '`therefore, I will cast you out of my sight,
as I have cast out your brethren before you?`'

And in Hosea 6.
did not the Lord say, '`He desired mercy, and not sacrifice;
and the knowledge of God more than burnt-offerings:
but ye like men have transgressed the covenant, and therefore,
have ye trespassed against me; and as thieves wait for a man,
so doth the company of priests murder in the way by consent;
for they work mischief.`' Now was not this fulfilled in the days of the Messiah?
were not the priests the most mischievous against him?
did they not gather together in troops to work mischief against him,
and to put him to death?
and had you had mercy, and the knowledge of God,
you would have received the Messiah when he came, the Son born of a virgin?

And again, in 2 Esdras i. 30. '`the Lord gathered you,
as a hen gathereth her chicken under her wings: but now what shall I do for you?
I will cast you out of my sight.`' And would not
the Messiah have gathered you when he came,
and you would not?
So that your house is become a desolation, and you cast forth.

And in the sayings of the wisdom of Solomon ii.
'`He checks us for offending against the law;
he makes his boast to have the knowledge of God; he calls himself the Son of God:
he is made to reprove our thoughts; it grieves us also to look upon him;
for his life is not like other men`'s, his ways are of another fashion:
let us examine him with rebukes and torments, that we may know his meekness,
and prove his patience;
let us condemn him to a shameful death.`' And did not you Jews fulfill all this?
And are not these sayings verified by you concerning the Messiah?

And you sons of Adam, who are called Jews, what do you think of the saying in Esdras?
chap. 7. '`The bride shall appear, and he shall come forth and be seen,
that now is under the earth: for my Son Jesus shall appear with those that be with him,
and they that remain shall rejoice within four hundred years;
and after these same years shall my Son Christ die.`' So do ye think he spake truth?
And what Jesus was this, the anointed,
that was prophesied of should die after the four hundred years?

[.signed-section-signature]
G+++.+++ F.

====
