== A Small Treatise Concerning Swearing / In the Old Time of the Law, with It`'s Use:

[.heading-continuation-blurb]
And an end put to it in the Gospel by Jesus Christ:
who forbiddeth all swearing, and sets up Yea and Nay instead thereof.--By G. F.

Concerning swearing by the name of the Lord before the law, and in the law; its time,
use, and service, which was to continue until Christ came, who fulfils the law, and says,
'`swear not at all,`' and sets up yea and nay instead of it.

And how all false and vain swearing was forbidden by the law,
and all swearing is forbidden by Christ, yea, the oath of the Lord,
which was to end differences.

And how Christ performs God`'s oath, and commands yea, yea, and nay, nay, instead of it.

And to end the trespasses and differences in his church,
he sets up two or three witnesses: Christ saith,
'`out of the mouth of two or three witnesses every
word shall be established.`' Matt. 18:16.

And the apostle saith, 2 Cor. 12:1,
'`in the mouth of two or three witnesses every word shall be established.`'

And the apostle James, who forbids swearing, says, '`so speak ye,
and so do ye.`' James v. and James 2:12.

Wherein all may plainly see that they that were to swear, it was to the Lord,
and perform their oath to him; and as for false oaths that they did swear,
they were forbidden by the Lord in his law;
and this oath that they were to perform to the Lord, was the oath that Christ forbid.

For before the law you may see Abraham said to his servant,
'`I will make thee to swear by the Lord, the God of heaven,
and the God of the earth.`' Gen.
xxiv.

So this swearing was not by any book, or any creature, but by the Lord, etc.
And this was the oath which was to be performed to the Lord,
which Christ speaks of and forbid, as was commanded in the law, and not to swear falsely.

And in the time of the law you may see in Ex. 22:11,
when there was any matter of difference amongst the
children of Israel about outward things,
then the oath of the Lord should be between them;
and this oath was to end the difference:
so still you may see it was the oath of the Lord, it was not an oath by the book,
or by any creature.

And this oath was not to be commonly taken,
for that was a '`taking God`'s name in vain,`' (as christians do
now,) they were not to swear by the Lord but upon great occasions.

Levit. 5. '`For if a soul sin, and hear the voice of swearing, and is a witness,
whether he hath seen or known of it, if he do not utter it,
then he shall bear his iniquity.`' So you may see here, how that no man was to swear,
but upon special occasion; whosoever did hear any swearing, if he did not discover it,
he was to bear his iniquity: and therefore consider,
all ye that profess yourselves christians, and the gospel,
what a great iniquity you are in by swearing, and others that hear it,
and do not discover it, for such things were to be punished by the law of God.

And now do ye think that the gospel gives you liberty to belch out so many oaths?
Oh no!
For Christ forbids in his gospel,
the '`true swearing by the Lord,`' which was to be performed to him,
and to be taken but upon urgent business to end controversies in the old time of the law:
that is the oath that Christ ends, and sets up yea and nay above it and the law;
and Christ forbid, much more the vain and false swearing.
And do ye think that the Jews do not hiss at you,
that call yourselves christians in gospel times,
that belch out so many oaths in your needless talk,
when their law punishes all common swearers,
and those that hear swearing and do not discover it, must bear their iniquity;
for this is taking God`'s name in vain, and using swearing,
or oaths in those places which God did not command them, but upon special occasions,
for his service, and to end controversies, etc.,
was this oath commanded to be performed to the Lord, which oath, as I said before,
Christ ends and forbids.
'`For if a soul swear, pronouncing with his lips to do good or evil,
whatsoever it be that a man shall pronounce with an oath, and it be hid from him,
when he knoweth of it, then he shall be guilty in one of these,
he shall confess that he hath sinned in that thing,
and he shall bring his trespass-offering unto the Lord for his sins,`' etc.
Levit.
v.

So now,
if there was any offering to be offered for the trespass
in swearing needlessly in the old time of the law,
is not Christ the offering that has ended all offerings for trespasses,
and is an offering for man`'s sins and trespasses to be looked at, and obeyed above all?
Not that man should trespass more in swearing,
and say Christ is offered up for his trespass, and presume thereby to add sin unto sin.

So Christ ends all swearing,
and is the offering that is offered up to the Lord
for all true christians for their sins.
And in Levit.
xix. '`ye shall not swear by my name falsely,
neither shall ye profane the name of thy God, I am the Lord.`'

So you may see here, swearing falsely was forbidden by the law of God,
and swearing idly is a profaning the name of the Lord;
for God did not give his oath to his people to swear idly in their customary talk,
nor falsely, but to be performed to the Lord upon special occasions;
and that is the oath, as I said before, Christ forbid and ends.

And in Numb.
xxx. '`if a man did swear an oath, and bound his soul to the Lord with a bond,
he was not to break it,
but he shall do according to all that hath proceeded
out of his mouth,`' either vows or oaths.
So here you may see they were to perform their oath unto the Lord;
which oath of the Lord bound their souls as with a bond;
and this was the oath which '`Christ, the oath of God,
came to fulfill,`' and forbids amongst the Jews,
which had this oath to perform to the Lord.

And so Christ is the oath of God,
by which all souls of men and women are bound to perform
what proceeds out of their mouths at yea and nay,
without swearing, and not to break their word which proceeds out of their mouths.

And in Deut. 6.
'`it is said, thou shalt fear the Lord thy God, and swear by his name,`' mark,
by his name, not by the four books of Moses, not by any other name,
but '`by the name of the Lord;`' not by any creature, but by the name of the Lord:
this was the true oath which was to be performed to the Lord in the old time,
(which as I said before,) this is the oath which Christ forbids, and ends.

And in Deut. 10. '`thou shalt fear the Lord thy God, and him shalt thou serve,
and to him shalt thou cleave,
and swear by his name:`' so not by any other name under the whole heaven, or book,
but by the name of God, and perform their oath to him:
but this was his people`'s swearing; but God swore by himself concerning his Son,
who brings people from under the law that commands swearing,
who ends both law and swearing: and so what people do now,
must be done in the name of Jesus, at yea and nay;
and they know that there is no salvation by any other name under the whole heaven,
but by the name of Jesus, who does fulfill the oath of God to him and us, that God swore,
and ends and forbids the oath that men swore unto God under the law in the old time:
and now commands yea and nay to be spoken in lieu of an oath,
for whatsoever is more than that, is evil.

And the apostle saith, Col. 3:17. '`whatsoever ye do in word or in deed,
do all in the name of Jesus Christ.`' etc.

Now mark, this comprehends all that ever a man does or says in word or deed,
'`it must be done in the name of Jesus, whose name is above every name.`'

And in Joshua 2.
It may be seen how Rahab the harlot, said unto the spies, '`now therefore I pray you,
swear unto me by the Lord.`' So you may see though she was of another nation,
and a harlot, yet the spies did swear unto her by the Lord, according to her desire,
'`and this oath was to be performed unto the Lord:`' she
did not tie them to swear to her by the books of Moses,
nor desire it, nor by their own customary oaths of her country, but by the Lord,
which was to be performed to the Lord: and this is the oath that Christ ends,
and sets up yea and nay instead of it.

And in Joshua 23. it is said,
'`that ye come not amongst those nations, that remain among you,
neither make mention of the name of their gods,
nor cause to swear by them:`' here you may see it
was forbidden to swear by the gods of other nations,
but only to swear by the name of the Lord which was the true oath that Christ ends.

So this one oath by the Lord,
that people was to swear by his name in the time of the law,
it was a type of that oath that the Lord swore concerning his Son,
who ends and forbids this true oath in the old time of the law,
who comes to fulfill the law, and gathers people into his own name above every name,
where salvation is; and commands them, let their '`yea be yea, and nay, nay,
for whatsoever is more is evil.`'

And in 1 Sam.
xix. when Saul swore, it was by the Lord, not by books nor creatures.

And in 1 Sam.
xxiv.
David when he swore unto Saul, it was by the Lord, and not by books nor creatures,
nor by the gods of other nations;
and this was the true oath which was to be performed to the Lord in the old law,
which Christ forbids and ends.

And in 1 Sam.
xxx. '`the young man of Egypt that was servant to Amalek; who said unto David,
swear unto me by God, that thou wilt not kill me, nor deliver me unto my master.`' etc.

And so here you may see though they were of other nations,
it was in vain to put any oath to the Jews but the oath of the Lord,
which was to be performed to the Lord in the old law, which Christ forbids, and ends,
and his apostle James. James 5:12.

And Joab, 2 Sam.
xix. when he '`swore to David it was by the Lord.`'

And in 1 Kings when David swore to Bathsheba, '`that Solomon should reign after him,
it was by the Lord,
and when David swore that Shimei should not die,`' it was by the Lord,
as you may see in 1 Kings ii.

And when Solomon swore, it was by the Lord; and when he made Shimei to swear,
it was by the Lord, though he broke it, which was to have been performed to the Lord.

And Solomon saith in 1 Kings viii.
'`if a man trespass against his neighbour,
and he require an oath of him to cause him to swear,
and the oath come before the altar in this house: then hear thou in heaven,
and judge thy servants,
and condemn the wicked.`' So here you may see the use of the true oath,
and swearing by the Lord, and it was to come before his altar in his house; which house,
and oath, and altar, and law, has Christ ended and fulfilled;
and all these before mentioned did not swear by books or creatures, or any other name,
but by the Lord in the old time, which '`was to be performed to the Lord.`'

So this oath and swearing was to end the trespass; and '`Christ comes to end trespasses,
and swearing,`' and the oath, and to blot out our sins and trespasses,
and sets up yea and nay instead of the true oath which was to be performed to the Lord,
and '`whatsoever is more is evil.`'

And in 2 Chron.
xv. '`And they swore unto the Lord with a loud voice and all Judah rejoiced
at the oath which they had sworn with all their hearts.`' etc.

So here you may see again that swearing was by the Lord, and to the Lord,
and not by any books or creatures, but only to the Lord, and '`to be performed to him,
(which, as I said before,) this is the oath which Christ forbids and ends.`'

And '`Nebuchadnezzar made Zedekiah swear by God,`'
for he knew that that was the oath he was to take,
and not force him to swear by his own god or idols, as you may see.
2 Chron.
xxxvi.

So this was the true oath to swear by the Lord, though he did not perform it,
which Christ ends.

And in Nehem.
xiii.
'`he made the people to swear by God,`' which was the true oath,
and not to swear by the books of the prophets, or Moses, or any other creatures or name,
but '`by the living God,
which according to the law of God was to be performed,`' which Christ ends,
as I said before.

And David saith, '`he that sweareth to his own hurt, and changeth not,`' Psal.
xv. and Psal.
xxxvi.
'`and the king shall rejoice in God,
every one that sweareth by him shall glory:`' here
you may see the swearing was by the Lord,
'`who is above all the gods of the earth,`' and above all creatures;
so not to swear by books or creatures, but by the Lord,
when there was occasion for the deciding of strife; and though it be to his own hurt,
yet was he to swear to the Lord, that is just and true,
and perform it to the Lord by the command of the Lord, in his law in the old time;
but this law of oaths, Christ ends and forbids.

And in Isa.
xlv. it is said, '`I have sworn by myself,
and the word is gone out of my mouth in righteousness, and shall not return,
that unto me every knee shall bow, and every tongue shall swear.`'

Now in the time of the law, they were to swear by the Lord,
but Christ Jesus that saith '`swear not at all,`' who is the oath of God;
and when he came, he fulfilled God`'s oath,
who saith '`swear not at all;`' and God`'s word and, oath did not return,
but was fulfilled in Christ, that saith '`swear not at all.`'

So as it is said in Isaiah, aforesaid, '`every knee shall bow,
and every tongue shall swear;`' but the apostle that preached Christ Jesus and his gospel,
saith in Rom.
xiii.
it is written, '`as I live saith the Lord, every knee shall bow to me,
and every tongue shall confess to God.`'

Now mark, it is not here, '`every tongue shall swear,`' as it is written in Isaiah,
they were to swear in the old time of the law,
but in the time of the gospel they shall confess; for if the apostle had said,
every tongue shall swear to him, he had contradicted Christ`'s words,
who said '`swear not at all,`' but '`every tongue
shall confess to God;`' so swear not by God,
and perform their oath to the Lord now in the time of the gospel.

So Christ performed God`'s oath, and took away the oath of God amongst men,
that they were to swear by the Lord, and set up yea and nay instead of it.

And in Phil.
to the same purpose, '`that at the name of Jesus every knee shall bow,
of things in heaven, and things in earth, and under the earth,
and that every tongue shall confess that Christ Jesus is Lord,
to the glory of God the Father.`'

So the oath of God, that he swore by himself, concerning Christ Jesus,
who ends the oath of God amongst men,
(to bind them and tie them up to God,) Christ Jesus ends,
and so every tongue comes to confess Jesus Christ, the oath of God,
who brings men up to God; so that '`at the name of Jesus every knee should bow,
of things in heaven, and things in earth,`' etc.

So the prophet saith every tongue shall swear;
but Christ that is greater than the prophet, says,
'`swear not all:`' and the apostles that preached him,
say every tongue shall confess him and his gospel:
so it was swearing to the Lord in the old time of the law,
but confessing to the Lord in the time of the gospel, as you may see in the scriptures.

And in Isa.
xlviii, '`Hear this, O house of Jacob, which are called by the name of Israel,
and are come out of the waters of Judah, which swear by the name of the Lord,
and make mention of the God of Israel, but not in truth nor in righteousness.`'

So you may see all such swearing, and mentioning of God, '`not in truth,
nor righteousness,`' was declared against in the time of the law and prophets.

So Christ did not come to fulfill any false thing,
but the true types and shadows and figures of him;
and the oath that they were to swear by the Lord,
and perform it in truth and righteousness;
and this was the oath that Christ told the Jews,
'`it was said by them in the old time they were to perform to the Lord,
but I say unto you swear not at all:`' so here was the old time and the new time,
the old time in the law and prophets that commanded swearing,
and the new time in Christ and his gospel, that commands not to swear.

And again, Isaiah saith, in chap. 65:16.
'`he who blesses himself in the earth, shall bless himself in the God of truth,
and he that sweareth in the earth, shall swear by the God of truth.`'

So you may see here they were to swear still by the
God of truth in the old time of the law and prophets,
and not to swear by any creatures or books, or any other thing but by the God of truth,
and perform their oath to him, according to the law and prophets, which,
as I said before, was the old time, but Christ in his time and gospel says,
'`swear not at all,`' which was the new time, and doctrine;
to preach down the sacrifices, and altars, and oaths,
and he it is that brings men up to God,
and to a farther righteousness than that of the law: and as Jeremiah saith, Jer. 5.
'`though they say the Lord liveth, yet surely they swear falsely:
those were they that had the form of the law and prophets, but were out of the power,
and truth, and righteousness; which were forbidden, and looked upon as false swearers,
because their hearts were gone from the Lord.

So you may see it was a weighty thing to swear by the Lord,
and to perform their oath to the Lord; which this weighty oath, Christ the substance,
comes to end, who is the oath of God, and says, '`swear not at all.`'

So the righteousness of Christ excels and exceeds the righteousness of the law and prophets,
and of their swearing.

And again, Jeremiah saith in the same chap.
'`how shall I pardon thee for this, thy children have forsaken me, to wit, the Lord,
and have sworn by them that are no gods.`'

So you may see here to swear by other gods, and to forsake the Lord,
it is a question how it shall be pardoned: so the oath which was to be sworn,
was only by the Lord, and not by other gods.

Now look in Christendom, and see what abundance of pettish, frivolous, foolish,
idle oaths there are amongst them, who are commanded by Christ not to swear at all, no,
not the time oath;
and in the time of the law it was a question by the prophet of their pardon,
that did not swear by the Lord; and therefore what will become of you,
that call yourselves christians, that swear so vainly, when your master Christ,
forbids all swearing.

And in Jer.
vii. and ix.
there he reproves them for swearing falsely, and walking after other gods.

So you may see, false swearers were reproved in the time of the law and prophets,
that was done before Christ came, who came to fulfill the true oath,
that was to be performed to God: Christ, I say did end that,
and did perform the oath of God and fulfill it.

And in Jer.
xii. '`the Lord said he would have compassion of his people,
and bring every man to his heritage,
etc. if they will diligently learn the ways of my people,
and swear by my name the Lord liveth, as they had taught my people to swear by Baal.`'

So you may see here one cause of Israel`'s captivity,
was going from God`'s ways and swearing by Baal,
that they lost their inheritances and their land,
and therefore if they would come to learn God`'s ways, and swear by the name of the Lord,
that he lived, and leave swearing by Baal, they should inherit their land again.

So you may see here they were not to swear by books, or Baal, nor by any creature,
nor any other name that would perish, but by the Lord that liveth;
and this was the true oath,
which was to be performed to the Lord in the old time of the law and prophets,
but Christ in his time of the gospel, saith, '`swear not at all.`'

And again, in Jer.
xxiii.
'`because of swearing the land mourns;`' may it not be much more said of Christendom,
because of swearing Christendom mourns; because Christ forbids all manner of swearing,
though in the time of the law and prophets, they encouraged all true swearing,
and forbid vain and false; but Christ forbids all swearing, true, vain, and false.

And in Jer.
xxviii.
you may see Zedekiah`'s oath to Jeremiah was, '`as the Lord lived,
he would not put him to death;`' so his oath was not by any creature nor books,
nor by Baal, nor the gods of other nations, but was the true oath,
according to the law and prophets, which was as Christ called it in the old time,
'`to be performed to the Lord;`' but in his new time of the gospel, he saith,
'`swear not at all;`' and this was the new thing brought to pass,
which made the Jew`'s ears to tingle; and this is he that said, behold,
'`I make all things new:`' so swearing was in the old time of the law;
but confessing is in the time of Christ and his gospel: here is one new thing.

And in Hosea iv.
by '`swearing, and, lying, and stealing, and committing adultery, they break out,
and blood toucheth blood,`' etc.

Such swearing as this, the law and the prophets were against: oh ye, therefore,
that profess the everlasting gospel of the Lord Jesus Christ,
let not such things be found against you in Christendom, '`lest blood touch blood.`'

For such before mentioned were commanded '`not to go to Bethaven,
nor swear the Lord liveth,`' etc.

And in Hosea x. '`they have spoken words, swearing falsely, in making a covenant;
thus judgment springs up as hemlock in the furrows of the field.`'

So here you may see the effect of this false swearing,
and see if a great crop of this hemlock may not be
found in Christendom amongst the false swearers?
and yet commanded by Christ '`not to swear at all.`'

And in Amos viii.
'`they that swear by the sin of Samaria, and say thy God, O Dan, liveth,
and the manner of Beersheba liveth, even they shall fall and not rise up again.`'

Now ye may see the sad judgment of God,
that is upon them that swear by any thing but by the Lord,
to whom they were to perform their oath, which oath Christ ends by his command:
therefore,
what think you will become of all you that swear
by so many things in all Christendom and in the world;
for if '`they shall fall and not rise up again, that swear by the sin of Samaria,
and the manner of Beersheba,`' which was forbidden by God in the law and prophets:
therefore, I say,
what will become of you Christendom that swear by so many
things when Christ in his gospel commands you,
'`not to swear at all;`' judge yourselves.

And in Zeph. 1. it is said,
'`them that worship the host of heaven, upon the house-tops,
and them that worship and swear by the Lord, and by Malcham.`'

So here are the false worshippers,
that would worship and '`swear by the Lord and Malcham,`'
which were reproved by the law and prophets,
for they were to '`swear only by the Lord, and worship and serve him only,
and not the host of heaven,`' the true oath to the Lord, and perform it,
which oath Christ ends.

And therefore, you christians,
consider how many sorts of things you swear by in Christendom,
and by books and creatures; which if you were as the true Jews,
you must only '`swear by the Lord, and perform it to him,
in truth and righteousness,`' in which you swear,
and therefore are not you reproved by the law and prophets;
for Christ is a farther righteousness than the law and prophets; he says,
'`swear not at all,`' and Christ is called the '`Lord our righteousness.`'

And do not you christians like unto those false Jews spoken of here in Zephania,
that '`swear by the Lord and Malcham,`' do not you
pretend to be the professors and followers of Christ,
that saith '`swear not at all,`' and yet are you not found swearing not by the Lord,
but by a book, and many other things,
in which you are forbidden '`not to swear at all;`' so you
are neither true to the command of the Lord in the law,
nor to Christ.

And in Zach. 5.
'`this is the curse that goeth forth over the face of the whole earth;
for everyone that stealeth shall be cut off as on this side, according to it,
and every one that sweareth, shall be cut off as on that side, according to it.
I will bring it forth, saith the Lord of hosts,
and it shall enter into the house of the thief,
and into the house of him that sweareth falsely by my name:
and it shall remain in the midst of his house,
and shall consume it with the timber thereof and the stones thereof.`'

Now consider this, all ye christians in Christendom,
do you think the Lord will not perform what he hath said,
and it must '`go over the face of the earth, and every one that stealeth,
and every one that swears falsely.`'

Therefore, look unto yourselves, how this curse of the Lord,
how it will consume you that swear, and forswear?
Seeing Christ has commanded '`swear not at all:`' and therefore,
as you love your eternal good, and your souls, and Christ Jesus, and God,
lay away all manner of swearing and forswearing, and stealing, as he commands you,
that the blessings may come into your houses, and not the curse,
for '`God will be a swift witness against the swearer, against the adulterer,
and against the false-swearer, etc. and will come near to you to judgment.`' Mal.
iii.

So you may see all false swearers,
and vain swearers were judged in the time of the law and prophets, and true swearers,
and performers of their oaths to the Lord, were justified,
which was in the old time of the law and prophets;
but in the '`new time of Christ,`' the new thing brought forth, he saith in his time,
'`swear not at all;`' which makes the professing Jews, and such like,
'`their ears to tingle.`'

So You may see clearly by the law and the prophets,
all swearers and swearing by the creatures, by the gods,
and all common vain swearing was forbidden,
and that '`they were only to swear by the Lord, and perform their oath unto him:`' nay,
if they used the form of the law to swear by the Lord, and did not swear truly,
in `'truth and righteousness,`' it was forbidden, and not accepted,
except it were in truth and righteousness;
and that oath which was to be sworn in truth and righteousness according to the law,
Christ the righteousness of God, that fulfils the righteousness of the law,
forbids that oath, who performs and fulfils the oath of God, and saith,
'`swear not at all.`'

And Christ saith in Matt. 5.
'`ye have heard that it hath been said by them of old time,
thou shalt not forswear thyself, but shalt perform unto the Lord thine oaths;
but I say unto you, swear not at all:`' +++[+++mark, not at all.]
Now these words of Christ relate to the oaths that they were to perform to the Lord,
for forswearing and vain swearing was forbidden by the law and prophets;
so Christ`'s words cannot relate only to people that forswear themselves,
('`not to swear at all,`') but also to such as were to perform their oaths to the Lord,
and swear by the Lord; as in the old time was commanded;
'`not to forswear themselves,`' but to '`perform their oath
to the Lord;`" as you may see in the old time,
in Exod. 20. and Levit. 19. and Deut. 5.

And now you may see in the new time, i. e. gospel time, Christ saith,
'`but I say unto you, swear not at all:`' and what you, were these?
Was it not to the multitude of the Jews and his disciples
that were Jews that he taught upon the mountain:
now by the law of God and the prophets, in their old time,
they '`were not to forswear themselves,
but to perform their oath to the Lord:`' now in Christ`'s new time, he saith,
'`swear not at all.`'

So the pharisees and Jews did not then '`discern the times and seasons that were
in their father`'s hands;`' as multitudes of christians do not now,
Matt.
xvi. Acts i.

And Christ goes on and says, '`swear not neither by heaven, for it is God`'s throne;
nor by the earth for it is his footstool: neither by Jerusalem,
for it is the city of the great King: neither shalt thou swear by thy head,
because thou canst not make one hair white, or black; but let your communication be yea,
yea, nay, nay; for whatsoever is more than these cometh of evil.`'

So as Christ Jesus forbid swearing at all,
which relates to the true oath that was to be sworn to by the Lord,
according to the law in the old time; I say Christ, that doth fulfill the oath of God,
then he comes and saith,
(farther relating to those other oaths which he particularizes,) '`neither by heaven,
nor by the earth, nor by Jerusalem, nor by the head,
etc. and when he hath forbidden the true oath, and all those other oaths;
then he teaches them what they shall say instead of an oath, to wit, yea, yea, nay, nay,
and whatsoever is more than these cometh of evil.`'

Now in the old Bible it is, '`but your communication shall be yea, yea, nay, nay,
for whatsoever is added more than these,
it cometh of evil:`' this Christ speaks in respect of swearing; yea,
of that '`oath which was to be performed to the Lord,`' as well as all the other oaths;
and he is to be believed and obeyed; for plainer words than these,
cannot be in the scriptures: and this cannot be meant,
that Christ forbids '`swearing only in communication,`'
for that was forbidden in the time of the law;
and if the oath that was commanded to be performed to the Lord was forbidden by Christ;
then much more all vain and other oaths, which both law and gospel forbids.

And Christ saith in Matt.
xxiii.
'`woe unto you blind guides, which say, whosoever shall swear by the temple,
it is nothing; but whosoever shall swear by the gold of the temple, is a debtor:
ye fools and blind; for whether is greater, the gold,
or the temple that sanctifies the gold?`'

'`And whosoever shall swear by the altar, it is nothing;
but whosoever shall swear by the gift that is upon it, he is guilty: ye fools and blind;
for whether is greater, the gift, or the altar that sanctifies the gift?
Whoso, therefore, shall swear by the altar, sweareth by it, and by all things thereon;
and whoso sweareth by the temple, sweareth by it, and him that dwells therein;
and he that sweareth by heaven, sweareth by the throne of God,
and him that sitteth thereon.`'

So all the swearing of these fools and blind guides, that guided people to swear so,
were not blessed by Christ in their doings;
but he cried '`woe against them;`' and these were
the Jews that were to '`swear only to the Lord,
and perform their oath by the Lord;`' and what do
ye think do not all them that swear by the book,
swear by them that gave forth the book, to wit, '`God and the prophets,
Christ and his apostles,`' that gave forth the book, and the things therein contained.

For swearing by Baal, and swearing by the temple, or by the gold of the temple;
or swearing by the altar, or by the gift that was offered thereon;
or swearing by the heavens, or by the earth; or swearing by the head,
these were all inventions of the Jews, and practised by the blind guides, and heathen,
who swore by their gods, inventions of their own;
for the law of God commanded to '`swear by the Lord,
and by his name,`' and not by any other gods or books, or creatures, or heaven, or earth,
or head, or altar, or temple, as ye may see in many scriptures before quoted;
where the Lord saith, '`ye shall swear by my name,`' and perform the oath to the Lord,
which Christ speaks of, when he saith,
'`swear not at all;`' and what do ye think he mentioned that oath for,
which was to be performed to the Lord, if it were not to forbid it?
He that was the oath of the Lord,
and a farther righteousness than the righteousness of the law;
for Christ did not come to fulfill those vain and
frivolous oaths that men commanded and practised,
but the oath that God had commanded,
and cried woe against them that were in the practice
of those oaths which God never commanded,
nor led into them: and so you may see all along it was the command of the Lord,
and by his law and prophets, that people were to swear by the Lord,
and perform their oath unto him,
which was the true oath and swearing which Christ forbid, much more all other oaths.

And so then whatever men swear by, if it be by Baal,
are they not to perform their oath to their Baal?
And if they swear by the book, are they not to perform their oath to the book,
or the contents of it?
And if they swear by the altars, or the gift on the altar,
are they not to perform their oath to the altar?
And the gift on the altar?
And if they swear by the temple, are they not to perform their oath to the temple?
And if they swear by heaven or earth, are they not to perform their oath to heaven,
or to the earth?
And if they swear by their head, are they not to perform their oath to their head?

So are not all people, whatsoever they swear by,
to perform their oath unto it that they swear by?
Though all those that swear by any thing but the Lord, were judged both by God,
and his law, and prophets;
and Christ Jesus cried woe against those blind guides and fools,
that taught to swear by other things as aforesaid;
but the oath which was to be performed unto the Lord,
(and men were not to forswear themselves in,) was the true oath of God,
as God commands by his law, which was the oath that Christ forbids, and says,
'`swear not at all,`' and sets up yea, yea:, and nay, nay, instead thereof.

And the apostle James followed Christ in his doctrine, and saith,
who writes to the twelve tribes, which were the Jews that were to '`swear by the Lord,
and perform their oaths to him,`' he saith to them; '`above all things my brethren,
swear not, neither by heaven, nor by the earth:`' it seems these were customary oaths;
(now he comes farther with his word,) '`neither by
any other oath:`' so all oaths are concluded here,
the true, the false, and the vain, but '`let your yea be yea, and your nay, nay,
least you fall into condemnation.`'

So this is agreeable to Christ`'s words, '`yea, yea, and nay, nay,
and whatsoever is more than these, cometh of evil,`' saith Christ,
'`and least ye fall into condemnation,`' saith the apostle.

So though swearing was lawful in the time of the law, as other things and offerings,
but in time of the gospel is forbidden;
and if they swear they go into evil and fall into condemnation;
and therefore the way to shun evil and condemnation, is to keep to yea and nay,
and not to swear at all, as Christ and the apostle commands; for the apostle saith,
'`neither by heaven, nor earth, nor any other oath:`' (mark,
any other oath:) so see what a stress the apostle lays upon it, and Christ,
to keep people from swearing, and out of the evil and condemnation;
though swearing as I said before, was lawful in the old time of the law,
being performed unto the Lord amongst men, for it ended the strife and did not begin it;
but Christ who comes to perform the oath of God, who swore by himself,
he ends the oath that men were to swear by the Lord, and sets up yea, yea, nay, nay,
instead thereof: Christ commands this to the multitude, and his disciples;
and the apostle to the twelve tribes which were to '`swear by the Lord,
and perform their oath to the Lord,`' as in James v. and Mat.
v.

And therefore, as I said before, keep out of the evil and condemnation,
and be obedient to Christ`'s command, and the apostles`' doctrine, not to swear at all,
nor any oath, and keep to yea, yea, nay, nay, in all your communications, and so say,
and so do; not so swear, and so do,
'`as they that shall be judged according to the law of liberty.`' James 2:12.

Now Christ sets up an order in the church, amongst the christians who deny the true oath,
and forbids the swearing which was to be performed to the Lord,
for the ending of differences and trespasses, as you may see in Levit.
xix. and this is Christ`'s order.

Moreover, saith he, '`if thy brother shall trespass against thee,
go and tell him his fault betwixt thee and him alone, and if he shall hear thee,
thou hast gained thy brother: but if he will not hear thee,
then take with thee one or two more,
that in the mouth of two or three witnesses every word may be established.`'

So Christ doth not say, in the mouth of two or three swearers,
which he had forbidden before;
but '`in the mouth of two or three witnesses
everything shall be established,`' in his church,
which he is head of, as in Mat.
xxviii.

So this was the order that Christ set up in the church, that forbids swearing,
to end differences, and trespasses amongst the christians.

And the apostle saith to the church, Gal.
xiii.
in the mouth '`of two or three witnesses shall every word be established.`'

And so we never read in all the scriptures of the New Testament,
that people were commanded to swear, but forbidden.

And Christ saith, in Luke xxiv.
to them that were his ministers, and received their ordination from him to preach freely,
as they had received freely, he told them,
they were witnesses of these things that he suffered.

And when they chose another disciple, and cast lots, the '`Lord gave the lot to Matthias,
to be a witness of his resurrection,`' Acts i. and in Acts '`the apostles were
witnesses that God had raised Jesus from the dead:`' and in Acts iii.
and xv.
he speaking to the Jews that had killed the '`Prince of life,
whereof we are witnesses,`' saith he, and in Acts v. and xxxii.
speaking of Christ, the apostle said, '`we are his witnesses of these things,
and so also is the Holy Ghost whom God hath given
to them that obey him:`' and in Acts xiii.
'`but God hath raised him from the dead,`' (to wit,
Christ,) and '`he was seen many days of them which came up with
him from Galilee to Jerusalem,`' who are his witnesses to the people:
and in Acts xxvi.
Paul in his confession, said,
'`I continued unto this day witnessing unto small and great;`'
and we are witnesses of all things which he did,
(to wit, both in Jewry and Jerusalem,) whom they slew and hanged on a tree:
so these were chosen witnesses of God and Christ.
Acts xix.

And so here you may see the ministers of Christ were not made by an oath,
which were preachers and witnesses of his birth, sufferings, death and resurrection;
so they were not swearers of it, or confessors of it upon oath,
but witnesses of the truth of it in the truth.

And so Christ witnessed a good confession before Pontius Pilate,
and did not swear a good confession, for he denied swearing, who was God`'s oath.

And the apostle speaks to Timothy,
in 2 Tim. 2:2. '`and the things thou hast heard of me amongst many witnesses,
the same commit thou unto faithful men,
who shall be able to instruct others also:`' he doth not
say the things thou hast heard amongst many swearers,
but witnesses: the same commit unto faithful men, but not upon oath,
men that shall so say, and so do.

And whereas, the apostle saith, '`against an elder, receive not an accusation,
but before two or three witnesses;`' so he doth not say before two or three swearers. 1 Tim. 5:19.

So here was the practice of the church according to Christ`'s command,
to witness the truth, who denied swearing;
and here was the practice of his ministers to be witnesses to the truth without swearing,
and what was to be committed to the faithful men, was without an oath,
and concerning accusations and trespasses, it was by two or three witnesses,
and not two or three swearers.

And when the Jews stoned Stephen to death, the witnesses laid down their clothes;
it doth not say they swore, but witnessed against him. Acts 7:58.

And when they put Christ to death,
there came '`two false witnesses when the high priest had examined Christ,
whether he was the Christ the Son of God; and Jesus said unto him thou hast said:
nevertheless, I say unto you,
hereafter ye shall see the Son of man sitting at the right hand of God,
and coming in the clouds; then the high priest rent his clothes, and said,
he hath spoken blasphemy, what need have we of farther witnesses?`'

So these murdering Jews that crucified Christ, and martyred Stephen,
we do not read they received witness against them upon oath.

And the apostle saith, 1 Tim. 2:7. '`I speak the truth in Christ and lie not:
a teacher of the Gentiles in faith and verity,`' so he doth not say, I swear the truth.

And the apostle saith, '`speak every man truth to his neighbour; and put away lying,
for we are members one of another.`' Eph.
4+++.+++ Not every man to swear the truth with his neighbour.

So if all christians in Christendom, so called, would so say, and so do,
and '`speak the truth as it is in Jesus,
who is the truth,`' and every man speak truth with his neighbour,
this would shew that they that profess themselves christians,
'`were members one of another,`' and that Christ was their head,
and this would ease them of many idle words, and of all oaths,
if they obeyed Christ`'s command, and the apostle`'s doctrine, in keeping yea, yea, nay,
nay, in all their communications.

And now if you say that the apostle speaks of swearing in Heb.
vi. mark what was his end in it; '`for when God made a promise to Abraham,
because he could not swear by a greater, he swore by himself,`' etc.
For '`men verily swore by the greater, and an oath for confirmation,
is to them an end of strife.`'

So this oath of God was a confirmation to them, and an end of strife to them, not to us;
for witnesses end the strife in the time of the gospel,
as oaths did in the time of the law; (so not the beginning of strife,
as oaths are now,) and men swore by the Lord which was the greater,
and were to perform their oath to him, which Christ ends.

And so the apostle brings this but as a similitude,
'`wherein God willing more abundantly to shew unto the heirs of promise,
the immutability of his counsel, confirmed it by an oath,`' etc.

And in Heb.
vii. where you may see the priests were made without an oath, but Christ with an oath,
that said of him, '`the Lord swore, and will not repent, thou art a priest forever,
after the order of Melchizedek.`' So he is made a
surety of a better testament than the first;
so the Old Testament has the old things, the New Testament has the new things,
as a new priest, the new blood, the new and living way, Christ,
who was made with an oath, who ends the oath, that men of God swore by, to bind them,
and tie their souls up to God: so Christ is the way up to God,
that says '`swear not at all,`' and let your yea be yea, and nay, nay; and the apostles,
and martyrs, and all the faithful followed him in his doctrine, who dare not swear,
because Christ and the apostle hath forbidden it, who cannot call him Lord,
unless they do as he commands, and says to them.

But now if you say Abraham swore, Christ saith, '`before Abraham was,
I am;`' and he says, '`swear not at all.`'

And if you say Jacob and Joseph swore; Christ reigns over the house of Joseph and Jacob,
who saith, '`swear not at all,`'

And if you say Moses, the servant of God,
and the priests did swear in the time of the law, and old covenant,
Christ ends the first priesthood, and is the Son of God, and is above Moses, the servant;
and his New Testament, is a greater testament than Moses`', or the law,
and a '`better surety than the blood of bulls and goats,`' who
offered up his '`own blood himself once for all;`' he says,
'`swear not at all,`' who redeems people by his blood up to God,
and they have faith in him, and it, and not in the blood of bulls and goats.

And now if you say, that the prophets swore in the time of the law, in the Old Testament,
I say, Christ, who ends the prophets and the law in his New Testament, says,
'`swear not at all.`'

And now if you say the angel swore, '`I bring forth my first begotten into the world,
saith the Lord, let all the angels worship him,`' that says, '`swear not at all;`' and,
'`learn of me,`' saith Christ,
'`I am the way,`' and '`this is my beloved Son,`' saith God,
'`hear ye him in whom I am well pleased,`' who fulfils the oath of God,
and in him God performs his oath,
whose righteousness is beyond that of the law of swearing, who is the glory of Israel,
if they will receive him; and the light of the Gentiles, to whom God never gave an oath;
but to the Jews, unto whom he gave the rest of the types;
and therefore should all the converted Jews and Gentiles hear him, the oath of God,
and the law, and the prophets in the old time, and all the promises of him,
who '`is set up from everlasting to everlasting, the first and last,
the amen;`' and therefore all Christians, mind Christ`'s words,
and hear and obey him that God hath sent, and believe that he is he that God hath sent,
and obey his commands,
for God hath performed his oath in him who came to fulfill the oath of God,
that he gave to men in the Old Testament, who saith in his New Testament,
'`swear not at all,`' but let your '`yea be yea, and nay, nay,
and whatsoever is more than this cometh of evil.`'

And so the apostles were made '`able ministers of Christ, and of the New Testament,
and not of the letter;`' of the prophets and the
law in the Old Testament in which there was swearing;
for '`the letter killeth, but the spirit giveth life.`'

'`But if the ministration of the law written and engraven in stone was glorious,
so that the children of Israel could not steadfastly behold the face of Moses,
for the glory of his countenance, which glory was to be done away, +++[+++mark,]
that glory was to be done away;`' and do you think
that swearing and oaths were not to be done away?
If that glory was to be done away by Christ,
how shall not the ministration of the spirit be glorious?
For if the '`ministration of condemnation be glorious,`' much more
doth the '`ministration of righteousness exceed in glory.`'

Now were not oaths and offerings,
and all those figurative things in this ministration of condemnation?

For even that which was made glorious had no glory in this respect,
by reason of the '`glory that excelleth,`' etc. as you may
read in 2 Cor. 2:3. so '`Christ takes away the first,
that he may establish the second:`' so he takes away those
oaths and offerings commanded of God in the first testament,
and established in the second and New Testament in the gospel, the power of God;
before the devil was, and will be when he is gone: where there is no swearing,
but yea and nay,
and out '`of the mouth of two or three witnesses shall
everything be established,`' saith he that forbids swearing;
and he is to be believed, and heard, and obeyed, and built upon;
and there is '`no other foundation to be laid,`' and he is the
'`chief corner-stone,`' and the builders are not to reject him.

Now we, the people of God, called Quakers, cannot swear at all,
because Christ forbids it, and saith, '`let your yea be yea, and nay, nay,
and whatsoever is more than this cometh of evil;`' and the
apostle James likewise exhorts not to swear at all,
`'but to keep to yea, yea, nay, nay; least we fall into condemnation.`'

So we, knowing that if we should swear contrary to our Lord and Saviour`'s command,
and the apostle James`' exhortation, we should fall into evil and condemnation,
and no man is able to redeem us out of that sin and evil, and condemnation.

And therefore we do declare to all the magistrates upon the face of the earth,
that if we be found breaking our yea, yea, and nay, nay, in testifying the truth,
when we are called before them,
then let us suffer the same punishment as perjured persons.

So we desire that our testimony may be taken in truth and righteousness,
without swearing, according to the command of Christ and the apostle.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, this 29th day of the 8th month, 1675.
