== Primitive Ordination and Succession / of Bishops, Deacons, Pastors and Teachers in the Church of Christ.

[.heading-continuation-blurb]
How Christ ordained his twelve Apostles, and seventy Disciples.

[.heading-continuation-blurb]
How He would be with them to the end of the World,
and in them. What was the maintenance He ordained for them.

[.heading-continuation-blurb]
How Christ chose and ordained Pastors, Teachers,
Prophets and Evangelists in the Church.

[.heading-continuation-blurb]
And the primitive ordination of Bishops, and Deacons, and Elders in the Church.

[.heading-continuation-blurb]
Also, who they are that do succeed them in their ordination, succession, possession,
doctrine and practice; in their preaching, praying,
singing and maintenance, and who not.--By G. F.

Leave off all your bustling, and come to Christ,
and see how his apostles were ordained and sent forth: Christ saith in Matt. 28.
'`go therefore and teach all nations.`' etc.
Now here was the command of Christ after he was risen:
so they were not to sit down in benefices, but they were to go and teach all nations;
the nation of Esau, and the Egyptians, Hams and Tartars, Barbarians, Scythians, etc.

These did not reason, (what shall I do with my wife and children,
or how shall I do for a maintenance?) when Christ
commanded them to go and teach all nations;
here was the love of God and Christ to all the world: and again Mark xvi.
Christ said unto his disciples, '`go ye into all the world,
and preach the gospel to every creature;`' (mark,
to every creature the gospel of salvation was to
be preached;) here Christ makes no sects,
nor leaves out some part of the world; but as he tasted death for every man,
and was an offering for the sins of the whole world, so he sent his disciples,
which he ordained to preach the gospel, into all nations; and he saith,
'`lo I am with you always, even to the end of the world;`' and Christ says,
'`if you were of the world, the world would love its own,
but because you are not of the world, but I have chosen you out of the world,
therefore the world hates you:`' so these were the chosen disciples of Christ,
which he sent forth into the world. John 15.
And Christ saith, '`I have given them the words which thou gavest me,
and they have received them, and have known surely that I came out from thee,
they have believed that thou didst send me, John xvii.
and the glory thou gavest me, I have given them, and that they may be one,
even as we are one, I in them, and they in me, that they may be made perfect in one.`'

So here you may see that Christ is in his apostles, that he sends forth into all nations,
and he will send them the Comforter, which shall lead them into all truth,
who is the spirit of truth, and this Comforter will teach you all things, saith Christ,
and bring all things to your remembrance, whatsoever I have said to you. John 13.
And further Christ saith, John 25.
'`I have chosen you and ordained you, that you should go and bring forth fruit,
and that your fruits should remain.`' etc.

So here you may see how Christ chose and ordained his ministers,
and how he would be with them, and in them, and how he had chosen them out of the world,
and they were not of the world, as he was not of the world, and therefore,
the world did hate these that were chosen and ordained, and sent forth by Christ,
and were not like a company of worldlings, seeking for great fat benefices,
and to agree with nations, or countries, or parishes, for so much a year,
and to haul people into courts, and cast them into prison,
if they would not give them maintenance, or earthly things.

And when Christ sent forth his seventy disciples by two and two into every city,
and town, and place, as in Luke x. He said to them, '`go your ways, behold,
I send you forth as lambs among wolves,
(so here is Christ`'s sending and command,) carry neither purse, nor scrip, nor shoes,
and salute no man by the way, and into what house ye enter, first say,
peace be unto this house, etc. and in the same house remain,
eating and drinking such things as they set before you;
for the workman is worthy of his meat, etc. and into what city ye enter,
and they receive you,
eat such things as they set before you:`' and when those seventy returned again to Christ,
etc. in the same hour Jesus rejoiced in Spirit and said, '`I thank thee O Father,
Lord of heaven and earth, that thou hast hid these things from the wise and prudent,
and hast revealed them unto babes, even so Father.`' etc. Luke 10:21.
'`And no man knoweth who the Son is, but the Father, and who the Father is,
but the Son,
and him to whom the Son will reveal him:`' and Jesus said privily to his disciples,
'`blessed are the eyes which see these things.`'

So here you may see how Christ sent forth his seventy disciples,
and how he thanked his Father which had revealed him and these things unto babes;
and how the Son had revealed these things unto his disciples;
so these did Christ choose and ordain, and they went forth in the Revelation of the Son:
and likewise, when Christ had sent forth his twelve disciples before, he said to them,
'`as ye go, preach, saying, the kingdom of heaven is at hand,
etc. and freely you have received, freely give, provide neither gold, nor silver,
nor brass in your purses, nor scrips for your journey, nor staffs, nor two coats,
nor shoes for your journey, etc. and into whatsoever city or town ye shall enter,
enquire who is worthy, and there abide till ye go thence, etc.
And whosoever will not receive you, nor hear your words,
when you depart out of that house or city, shake off the dust of your feet.`' etc.
So these were not to agree for a benefice with the heads of the town,
and if they would not pay them, then cast them into prison.

And also ye may see the same ordination and sending forth of Christ`'s ministers,
in Mark vi.
and +++[+++mark,]
whosoever would not hear Christ`'s apostles`' and disciples`' preaching,
they were to shake the dust off their feet against them,
they were not to summon them to courts, and cast them into prison,
because they would not hear them; for says Christ, '`he that heareth you, heareth me,
and he that despiseth you, despiseth me, and he that despiseth me,
despiseth him that sent me.`' Luke x. And Christ saith in Luke 22:35. unto his disciples,
'`when I sent you without purse, scrip and shoes, lacked you any thing?
and they said, nay.`'

Now you may plainly see here Christ`'s ministers, both before he was crucified and after,
when he was risen,
the manner of Christ`'s ordaining and choosing and sending forth his ministers;
and before he was crucified, he asked his ministers that he did send forth freely,
whether they lacked for any thing, and their answer was to Christ, they wanted nothing.

Now try yourselves you ministers in our days by Christ`'s words and his ministers then,
who are sent forth in the wills of men, whether ye can give the same answer,
that ye want for nothing, and that you go forth freely, as they did?
and Christ saith, '`I will be with you,
and he that is with you shall be in you:`' now they
that follow the apostles in their succession,
they must be in the same power and Holy Ghost that the apostles were in,
and not to succeed them in the form, as the false prophets did the true,
and antichrist doth the true Christ, who got the true Christ`'s words;
but to succeed the apostles in the same Holy Ghost and power, and life that they were in,
that is the right succession, and so in their inheritance and possession;
for any worldly man will tell you,
it signifies nothing to have only the writings of an estate, and not to possess it:
and therefore to succeed the apostles aright,
is to succeed them in the same power and Holy Ghost they were in,
and to have Christ with them and in them; for Christ saith, Matt. 21:16.
'`out of the mouths of babes and sucklings
hast thou ordained strength;`' and Psalm viii.

So you may see here how Christ ordained babes and sucklings to preach his name freely,
as they had received freely;
and you know the babes and sucklings are not fit to be sent to schools,
but these were taught of Christ,
and ordained of him to speak and to confess Christ Jesus freely, as they had received;
and he ordained strength out of the mouths of these babes and sucklings: yea,
such strength, as the devil, nor all his ministers,
nor all the professors of the world were able to gainsay,
but it convinced the gainsayers; so they need not lie at schools many years,
whom Christ ordains and sends forth:
and when they chose another disciple in the room of Judas,
to be a witness with the apostles of Christ`'s resurrection,
the Lord gave them Matthias by lot;
Acts i. And the apostle Paul saith in Eph. 3:7. '`how that by Revelation
he had made known to him the mystery whereof he was made a minister,
according to the gift of the grace of God given to him by the effectual
working of his power.`' And again the apostle saith,
'`that the gospel which was preached to every creature under heaven, whereof I, Paul,
am made a minister, according to the dispensation of God, which was given unto me,
which hath been hid from ages and generations, but now is manifested to his saints,
etc. which mystery is Christ in you, the hope of glory, whom we preach, (to wit,
the apostles and ministers of Christ,) warning every man, and teaching every man,
in all wisdom, that we may present every man perfect in Christ Jesus.`'

Here you may see Paul`'s ordination, and how he and the apostles received their ministry,
and what he preached, Col. 4:18. And again the apostle saith,
when Christ ascended up on high, he led captivity captive, and gave gifts unto men,
and he gave some apostles, some prophets, some evangelists, and some pastors,
and teachers, for the perfecting of the saints, for the work of the ministry,
for the edifying of the body of Christ: so this gift of Christ made them ministers,
and you that deny perfection, deny the work of Christ`'s ministers, as you may see.
Ephes. 4. And the apostle says, '`we speak the wisdom of God in a mystery,
even the hidden wisdom of God, ordained before the world to our glory:`'
so here you may see what he preached. 1 Cor. 2:6. And in Gal. 1.
'`Paul, an apostle, (not of men, neither by man, but by Jesus Christ,
and God the Father, who raised him from the dead.) I certify you, brethren,
that the gospel which is preached by me, is not after man;
for I neither received it of man, neither was I taught it,
but by the revelation of Jesus Christ.`'

So here you may see how the apostle was ordained, and from whom,
he received his gospel and what he preached, and how that he was an apostle, not of man,
nor by man; and the gospel which he preached was not after man: and the apostle saith,
in Acts 10:42, '`he hath commanded us (to wit, Christ,) to preach unto the people,
and to testify that it was he who was ordained of God to be the judge of quick and dead:`'
here you may see it was Christ who commanded his ministers and his disciples to preach;
and in Mark 3.
he ordained twelve, that they should be with him,
that he might send them forth to preach; mark,
here is Christ`'s ordination and his sending forth.

So all along you may see how Christ ordained his ministers and disciples,
and the seventy, and his pastors, prophets, evangelists and teachers,
and he will be with them to the end of the world, and he will be in them,
and they shall be in him, and they shall have his Holy Ghost to lead them into all truth.

Now here is a possession, and they that do succeed them in the possession,
must be such as possess Christ in them, and his Holy Ghost,
and the same power and spirit that the apostles did possess,
they must possess the same wisdom (in measure,) which was ordained before the world was,
and the same mystery hid from ages and generations,
and the same gift from him that is ascended, up on high,
and the same gospel which is not after man, neither is it received of man, or by man;
this they must possess, if they be the successors of the apostles; for any false prophet,
or apostle, or messenger of Satan, antichrist, or wolves, may get the sheep`'s clothing,
the outside, the form of godliness, and deny the power thereof,
such are not the successors of the apostles in their inheritance and possession.

Now the apostles in this possession, they that did succeed them in it,
were called elders, and they ordained decrees by the Holy Ghost, as in Acts xvi.
to the churches that were established in the faith;
and they ordained elders in every church; they that were in possession of the Holy Ghost,
ordained others that were in the Holy Ghost. Acts 14. and 20.
Take heed, therefore, unto yourselves, and unto all the flock of God,
over which the Holy Ghost hath made you overseers, to feed the Church of God,
which he hath purchased with his own blood; mark,
here you may see the ordination of overseers or elders,
and what they were to oversee withal, and feed withal; the Holy Ghost.

Now they that do succeed them in their eldership or oversight,
their succession must be in the possession of the same Holy Ghost,
else they are no successors of the apostles, nor the elders, nor overseers,
though they are in the form of godliness without the power thereof,
which are to be turned away from: and in 1 Pet. 5.
he that is an elder, writes to the elders,
who was a witness of the sufferings of Christ,
and also a partaker of the glory that should be revealed: '`feed the flock of God,
(saith he,) which is amongst you, take the oversight thereof, not by constraint,
but willingly, not for filthy lucre but of ready mind;
neither as lords over God`'s heritage,
but being examples to the flock.`' Now here you may
see further of the ordination of elders,
and the counsel of an elder to them that were partakers of the glory,
and witnesses of the sufferings of Christ,
they should feed and take the oversight willingly, and not for filthy lucre,
not being lords over God`'s heritage; but examples to the flock.
Now they that are as lords, and are ill examples, and will be overseers for filthy lucre,
are not succeeders of the apostles, neither in their possession, nor example,
nor command.

So all they that say they have not the same power and Holy Ghost the apostles had,
do not succeed the apostles in their possession; and all they who deny,
that any people should expect the same power and Holy Ghost the apostles had,
deny their possession, and are no succeeders of them:
and all they that deny the light that shines in the heart,
to give them the knowledge of the glory of God in
the face of Christ Jesus nowadays in people;
and all they that deny the anointing within to teach,
and the word of God in the heart and mouth to obey and do,
which was the word of faith the apostle preached,
they are not in the succession of the apostles, nor in the doctrine that they preached,
nor in the possession and practice they lived in.

And all they that deny that Christ was an offering for the sins of the whole world,
and that he doth enlighten every man that cometh into the world,
with the light which is the life in the word,
and forbid people from believing in this light, and say,
that God doth not write his law in people`'s hearts now, nor put it into their minds now;
all such, I say,
do not follow the apostles in their succession of their life and power they were in,
for they have denied their doctrine, and that which all good christians do possess.

And all such as say, that the grace of God hath not appeared to all men to teach them,
and bring them salvation,
and that the manifestation of the spirit is not given to every man to profit withal,
and that God doth not give his Holy Ghost to them that rebel against it,
and that Christ hath not sent his Holy Ghost to lead his ministers now into all truth,
which Holy Ghost shall reprove the world of sin,
etc. they that deny this are not the successors of the apostles,
in their possession of their life and power in the Holy Ghost;
but are deniers of their doctrine, though they may get a form of words,
but deny the power thereof, such are to be turned away from.

So you may see how Christ hath ordained his ministers,
for he himself was made after the order of Melchizedek, and not after the order of Aaron,
(though Aaron was made after an order) and so they were ordained to offer sacrifices,
as in Heb. 7:8. which priesthood Christ hath ended, and their order,
who ordained his disciples and elders, as you may see before:
and all that do succeed them must be in the same grace, in the same light and Holy Ghost,
and power, and the same law of life, and of the spirit, and the same anointing within,
and the same word of faith in the heart and mouth,
and the same gift from Christ that is ascended up on high,
and Christ within according to his promise, that he would dwell in them,
and as the apostle saith,
'`it pleased the Father to reveal his Son in me,`' and so he preached him in others:
and all apostles, pastors, evangelists, teachers, elders, overseers,
etc. that do not follow the apostles in the possession of this before-mentioned,
and are not inheriters of this, then they must needs be apostates,
and do not follow the apostles in the possession and practice,
though they may get the form, and not in the same power, but deny it;
they are not the succeeders of the apostles; but are to be turned away from;
for none do succeed the apostles, evangelists, and pastors, elders, overseers,
and teachers, who succeed them in Christ,
and in the same power and Holy Ghost that they were in, who gave forth the scriptures:
and in Acts 19:13. then certain of the vagabond Jews, exorcists,
took upon them to call over them which had evil spirits, in the name of the Lord Jesus,
saying, '`we adjure you by Jesus,
whom Paul preacheth;`' and there were seven sons of one Sceva, a Jew,
and chief of the priests, which did so, and the evil spirit answered and said,
'`Jesus I know, and Paul I know, but who are ye?
And the man in whom the evil spirit was, leaped on them and overcame them,
and prevailed against them so that they fled out of the house, naked and wounded,
and this was known to all the Jews and Greeks also dwelling at Ephesus:
and fear fell on them all, and the name of the Lord Jesus was magnified,`' etc.

Now it is clear that those did not succeed in the ordination of the apostles,
in the possession of their power, life and Holy Ghost, though they had the form of words,
and used the name of the Lord Jesus Christ: and you may clearly see,
that it is not the saying the form of Christ`'s and the apostles`' words,
and such as can hold them in their memories,
that doth bring them to succeed the apostles, and so to plead their ordination,
because they can speak Christ`'s and the apostles`' words,
this doth not prove their succession in the ordination of Christ nor the apostles;
for it says, they fled away naked,
they wanted the power and Holy Ghost the apostles were in: and so are not all naked,
though they have the form of Christ`'s and the apostles`' words, as these were?
Let them be priests or professors, if they be not in the same Holy Ghost,
and power the apostles were in; they are naked.

And may not this be an example to all Christendom to take heed
how they use the form of Christ`'s and the apostles`' words,
without they be in the same fear of God, and power, and Holy Ghost the apostles were in:
to it is clear, none do succeed the apostles in the same ordination and succession,
but such as do succeed them in the same power and Holy Ghost the apostles were in;
for can naked men, with the form of Christ`'s and the apostles`' words,
convert any men or women to Christ or God?
That be not in the same power and Holy Ghost the apostles were in,
which power clothes them:
and are not all naked men liable to be wounded by the evil spirit,
and flee from the evil spirit wounded, like this priest`'s sons,
that are not in the same power and Holy Ghost the apostles were in?
And therefore is not this a fearful warning to all Christendom,
to take heed how they take upon them,
or use any way the form of Christ`'s or the apostles`' words,
without being in the same life and power, and Holy Ghost the apostles were in,
least the evil spirit get power over them, as it did over this priest and his seven sons.

And are not all vagabonds from the apostles`' power and inheritance,
that are not in the same power and Holy Ghost the apostles were in,
though they may talk and have the form of Christ`'s and the apostles`' words,
as common vagabonds and wanderers may talk of other men`'s possessions:
and did Simon Magus continue in the succession of the apostles, though he was convinced?
And did not he go out of the succession of the apostles,
when he thought the gift of God was to be purchased with money?
Did not Peter tell him, he was in the gall of bitterness, and bond of iniquity,
though he was a professor of Christ, and a believer as many are now?
So you may see, that he did not succeed the apostles in the life, and Holy Ghost,
and power, and you may clearly see the succession to the apostles is in the life,
and power, and Holy Ghost that they were in.

And do not you think that there are many Simon Maguses nowadays, in Christendom,
in their gall of bitterness, and bond of iniquity,
that think the gift of God can be bought and sold for money?
And are there not many nowadays, that do buy and sell the gospel, as they call it,
to people for money?
And you cannot say,
that these succeed the apostles in their possession in the life and power;
but Simon Magus in his gall of bitterness and bond of iniquity.

And do you think, Diotrephes, that John reproves, followed the apostle with his prating,
in the possession, and in the succession of the power and Holy Ghost,
as in the third epistle of John.

And the apostle saith, 1 Cor. 4:19. '`but I will come to you shortly,
if the Lord will, and I will know not the speech of them that are puffed up,
but the power; for the kingdom of God is not in word,
but in power:`' So here it is clear, the knowledge, ordination,
and succession must be in power, and they that do succeed the apostles,
in their possession and ordination in the gospel, which is the power of God,
must be in the same power of God, the gospel, which brings life and immortality to light;
for all that have the form of godliness and deny the power thereof, deny the gospel,
for the gospel is the power of God:
so they must succeed them in the possession of this
power that brings life and immortality to light,
that shines over the devil, that hath darkened them; for the gospel, the power of God,
is called the everlasting gospel,
and therefore the succession must be in the everlasting gospel, and power of God;
and therefore, to succeed them in the form without the power and Holy Ghost,
is no succession to the apostles in their ordination;
but a succession of the false apostles, that got the form and denied the power,
'`from such`' saith the apostle, (that was in the succession of the life, and power,
and ordination by Christ,) '`turn away:`' and the apostle saith, 1 C or.
xviii.
'`for the preaching of the cross, (to wit, of Christ,) is to them that perish,
foolishness; but unto us which are saved, (to wit,
the true apostles and christians,) it is the power of God.`'

Now they that do succeed the apostles, and true christians in the cross of Christ,
it is in the power of God that crucifies them from the world:
it is not to succeed the apostles with wooden, stone, silver or brass crosses;
for these would have been foolish things to the apostles; for you cannot say,
that you succeed the apostles with your wooden, stone, brass and silver crosses,
except you say, these your inventions of stone, wood, brass,
and other such like made outward crosses, are the power of God.

And the apostle saith, we speak the wisdom, God in a mystery,
which wisdom we speak among them that are perfect; yet not the wisdom of this world,
nor of the princes of this world,
which cometh to naught so all that do succeed the apostles in their ordination and succession,
it must be in this wisdom of God, which is pure and gentle from above,
and easy to be entreated,
it must be in the possession of this wisdom (which will abide and not
come to naught,) which they spake amongst them that were perfect:
and it is not to succeed the apostles,
to get Christ`'s and the apostles`' words to talk of them in man`'s wisdom,
that comes to naught: and the apostle saith,
'`my speech was not with the enticing words of man`'s wisdom;
but in the demonstration of the spirit, and of power.`'

And now all preachers that do succeed the apostles,
it must be in the same demonstration of the spirit and power;
for they do not succeed the apostles,
whose speech and preaching is only with the enticing words of man`'s wisdom:
and the apostle saith, '`that your faith should not stand in the wisdom of men,
but in the power of God:`' so whose faith doth stand in the wisdom of men,
and not in the same power and wisdom of God the apostles were in,
do not succeed the apostles in their ordination and succession; and the apostle saith,
'`God hath revealed unto us by his spirit the deep things of God,
and we have not received the spirit of the world, but the spirit which is of God,
that we might know the things that are freely given to us of God, +++[+++mark freely,]
which things also we speak, not in the words which man`'s wisdom teacheth,
but which the Holy Ghost teacheth,`' etc. and, saith he, '`we have the mind of Christ.`'

So now all that do succeed the apostles, must be in the spirit of God,
that reveals the deep things of God to them,
and by which spirit they know the deep things of God, given forth freely unto them,
that they may give them forth freely again to others,
according to the ordination and command of Christ;
and they must succeed them in the same speech,
not to speak the things of God in the words which man`'s wisdom doth teach,
but in those words which the Holy Ghost doth teach:
and now they that speak the words of Christ and the apostles in man`'s wisdom,
and not freely, and have not the mind of Christ, that deny the spirit of Revelation,
but speak the apostles`' words by the spirit of the world,
that knows not the things of God,
such do not follow the apostles in their succession of the spirit of God,
nor in their ordination by the spirit of God:
and likewise all such that teach for filthy lucre, '`and serve not the Lord Jesus Christ,
but their own bellies,`' and are covetous teachers, and are '`heady, high-minded,
lovers of pleasures more than lovers of God, and are strikers, and persecutors,
and think that gain is godliness,`' such do not follow
the apostles in their succession and ordination;
for the apostles declared against such: freely as they had received,
freely they were commanded to give, and did so.
And they that follow not the apostles in this their example, and Christ in his command,
are not followers and succeeders to Christ and the apostles, in the same life,
power and doctrine.
Now for the trial of bishops and deacons,
that pretend to follow the apostles in their succession; '`a bishop must be blameless,
the husband of one wife, vigilant, sober, of good behaviour, given to hospitality,
apt to teach, not given to wine, no striker, not greedy of filthy lucre, but patient,
not a brawler, not covetous, one that can rule well his own house,
having his children in subjection with all gravity, not a novice,
lest he be lifted up with pride, and fall into condemnation of the devil: moreover,
he must have a good report of them that are without,
lest he fall into reproach and the snare of the devil.`' 1 Tim. 3. and in Tit. 1.
'`A bishop must be blameless, as the steward of God, not self-willed, nor soon angry,
not given to wine, no striker, not given to filthy lucre; but a lover of hospitality,
a lover of good men, sober, just, holy, temperate, holding fast the faithful word,
etc. for there are many unruly and vain talkers,`' etc.

Now here you may see the ordination of bishops;
and if they do not succeed in these steps and precepts as the apostles have laid down,
they do not succeed the apostles; for if he be of ill behaviour,
not given to hospitality, nor apt to teach freely,
(as they did,) and if he be given to wine, and a striker, and greedy of filthy lucre,
and not patient, but a brawler, and covetous, and not the husband of one wife,
and cannot rule his own house well,
and hath not his children in subjection and in gravity, and is a novice,
and puffed up in pride, and hath an ill report from them without, and self-willed,
and soon angry, not sober, just, holy and temperate, etc.
Such follow not, nor succeed the apostles in their ordination and succession,
nor in their life and power of the Holy Ghost, but were reproved by them: now likewise,
concerning deacons, if they be not grave, and if they be double-tongued,
or given to much wine, or if greedy of filthy lucre,
if their wives be not grave and sober, but slanderous,
they are such as do not follow the apostles in their ordinations and succession;
therefore, the apostle says, first they must be proved,
and then let them use the office of a deacon, etc. being found blameless:
and likewise the apostle saith, they must hold the mystery of faith in a pure conscience;
(mark in a pure conscience,) and faith is a mystery;
and therefore all such that are not qualified according
to the apostles doctrine to Timothy and Titus,
do not follow and succeed the apostles in their spiritual succession and ordination:
and moreover the apostle saith, '`follow us, as we follow Christ,
and walk as ye have us for an example;`' and they coveted no man`'s gold, nor silver,
nor apparel, and said, '`although he preached the gospel, ye had nothing to glory of;
and what is my reward?
(says he,) verily, that when I preach the gospel,
that I make the gospel of Christ without charge.`' 1 Cor. 9.

And now you that do not follow the apostle in these things, both in example and life,
and to keep the gospel without charge,
you do not follow the apostles in the spiritual succession and ordination,
neither are you to be followed, but as you follow Christ,
and the example of the apostles.

And all such that forbid to marry, and command to abstain from meats,
such are not the succeeders of the apostles in their ordination,
and possession of the heavenly power and spirit; but such are speakers of lies,
and are such as are departed from the faith, giving heed to seducing spirits,
and doctrine of devils, speaking lies in hypocrisy,
having their consciences seared as with an hot iron.
1 Tim.
iv. And in Rom.
viii.
'`if the spirit of him that raised up Jesus from the dead dwelleth in you,
he that raised up Jesus shall quicken your mortal
bodies by his spirit that dwelleth in you:
for as many as are led by the spirit of God, are the sons of God;
but ye have received the spirit of adoption, whereby we cry Abba Father,
which spirit itself beareth witness with our spirits, that we are the children of God;
for the law of the spirit of life, in Christ Jesus,
hath made me free from the law of sin and death,`' saith the apostle.

Now here was the possession of the apostles, and all true christians,
and all that follow them in their succession, and heavenly possession,
must be led by the spirit of God,
and to have the same spirit to bear witness with their spirits,
that they are the sons of God; yea the same spirit that raised up Jesus from the dead,
to dwell in them, and to quicken their mortal bodies:
so the succession must be in this same spirit,
and in the law of the spirit of life in Christ Jesus,
which makes free from the law of sin and death,
and then there will be the fruits of the spirit to
shew forth their succession to the apostles,
that they do succeed them in the same spirit,
in the law of the spirit of life that is in Christ Jesus,
that doth make them free men and women from the law of sin and death:
so all the succeeders of the apostles in the spirit, can cry Abba Father.
And the apostle saith, in Rom. 10. '`how shall he preach except he be sent?
etc. And the word is nigh thee in the heart and mouth,
and this is the word of faith which we preach,`' which were sent (to wit,
the apostles,) to preach it.

So all that succeed the apostles,
they must be sent of Christ in the same power and spirit,
that the apostles were sent from God and Christ,
and freely give as they have received from him freely, and preach the same word of faith,
which is nigh in men and women, even in their mouths and heart to obey it and do it;
for if people go not in the same power and spirit as the apostles were in,
and preach the same, they are not succeeders of them in their possession.
Now Christ said, '`I am come in my Father`'s name and you received me not:
if another shall come in his own name, him you will receive.`' John v.

And now is it not clearly seen to this day, that the prophets and apostles,
that came in the name of the Lord and of Christ, such were always hated;
and they would not receive them: and by sad experience we have found it in our age,
who have been moved by the Lord,
and gone in the name of the Lord to speak to priests and professors,
many of which you have imprisoned and beat; but if any have come in their own name,
such are received by you.

And if Paul had been an apostle by men, or of men,
or had received his gospel and ordination by men or from men,
men would not have called him a '`ring-leader, and a pestilent fellow,`' etc.
And the apostle said, '`they were able ministers of the New Testament, not of the letter,
but of the spirit; for the letter killeth,
but the spirit giveth life.`' So all that follow
the apostles in their ordination and succession,
must be ministers of the spirit, and of the New Testament, yea,
of the spirit that giveth life, and not of the letter that killeth:
now they that are ministers, but not of the same spirit that giveth life,
and of the New Testament that the apostles were in,
do not follow them in their ordination and succession, though they may have the letter.
And the apostle saith, '`we all with open face,
beholding as in a glass the glory of the Lord,
are changed into the same image from glory to glory,
even by the spirit of the Lord.`' 2 Cor. 3:13.
'`And we having the same spirit of faith,`' etc.

Now here was the apostles`' possession, and all that follow them in their possession,
ordination, and succession, must behold the same glory as they all did,
and know the same changing from glory to glory, even by the spirit of the Lord,
and they must be in the same spirit of faith, else they do not follow the apostles,
and true christians in their ordination and succession.
And the apostles saith, 2 Cor.
vi. '`in all things approving ourselves as the ministers of God in much patience,
in afflictions, in necessities, in distresses, in stripes, in imprisonments, in tumults,
in labours, in watchings, in fastings, by pureness, by knowledge, by long suffering,
by kindness, by the Holy Ghost, by love unfeigned, by the word of truth,
by the power of God, by the armour of righteousness,`' etc.
Now all, you that follow the apostles in their succession,
you must approve yourselves as the ministers of Christ, by your patience,
by your pureness, by your long suffering, by knowledge, by kindness, by love unfeigned,
by the word of truth, by the power of God, by the armour of righteousness,
and by the Holy Ghost: but now if you say,
you have not the same Holy Ghost as the apostles had, then you cannot approve yourselves,
neither can you follow them in the same ordination
and succession as the apostles were in:
and you that be the strikers, and imprisoners, and afflicters of people for religion,
you do not follow the apostles in their ordination and succession, that were stripped,
imprisoned, and afflicted.

And the apostle saith, '`ye are the temples of the living God; as God hath said,
I will dwell in them, and walk in them, and I will be their God,
and they shall be my people, and I will be a father unto you,
and you shall be my sons and daughters,
saith the Lord God Almighty;`' now here was the possession
of the apostles and true church:
now all that follow the apostles in their ordination, and succession,
and possession in the true church,
they must follow them in their sonship and daughtership,
and must be such as God dwells in, and walks in, if not,
and they will not have him to dwell in them, and walk in them,
and so to be the sons and daughters of God,
then they do not succeed the apostles and true church in their possession:
and the apostle saith, Gal.
iii. '`for ye are all the children of God by faith in Christ Jesus;
for as many of you as have been baptized into Christ,
have put on Christ:`' so all that follow the apostles and the true church in their succession,
must be in the same light and power, and faith in Jesus Christ,
which Jesus Christ hath been the author of, and all must look to him for it,
and so all children of God in this faith, that brings them to have access to God,
and victory over that which separates from God.

So all must succeed in this one faith, and they that are baptized into Christ,
must put him on; not make a profession of him without them, and not put him on;
if they do, they do not follow the apostle, and the true church in their succession.

And the apostle saith, Gal. 5.
'`because ye are sons, God hath sent forth the spirit of his Son into your hearts,
crying Abba Father:`' +++[+++mark,]
into your hearts: now all that do succeed the apostle and true church here,
it must be in the same power and spirit they were in, that they may cry Abba Father:
and the apostle, in Gal. 5. saith,
'`walk in the spirit and ye shall not fulfill the
lusts of the flesh:`' and again he saith,
'`if we live in the spirit, let us also walk in the spirit;`' mark,
(us the apostles and the true church,
and true christians:) now if ye do not walk in the same
spirit as the apostles and true church were in,
then ye do not succeed the apostles and true church in their succession, and ordination,
and possession that they were in; but do fulfill the lusts of your flesh:
now the apostle saith, '`the fruits of the spirit are love, joy, peace, meekness,
long-suffering, temperance, etc. against which there is no law,`' etc.
Now if you do not walk in the spirit,
you do not succeed the apostles in their ordination by the spirit,
neither do you succeed them in the fruits of the spirit;
but are in the fruits of the flesh, adultery, fornication, uncleanness, lasciviousness,
idolatry, witchcraft, hatred, variance, emulation, wrath, strife, sedition, heresy,
envyings, murders, drunkenness, revilings, and such like.
And the apostle tells you plainly, that they that do such things,
shall not inherit the kingdom of God, and therefore, look all Christendom,
at your fruits, and see whom you do succeed; and the apostle saith, Gal.
vi. '`for he that soweth to the flesh shall of the flesh reap corruption;
but he that soweth to the spirit, shall of the spirit reap life everlasting.`'

Now no man can sow to the spirit; but such as be in the same spirit of God and Christ,
that the apostles were in, and they that be not in the same spirit that they were in,
are not their succeeding seedsmen in their ordination by the Holy Ghost,
then such sow to the flesh, and of the flesh they reap corruptions,
and not everlasting life; mark this all you seedsmen,
what a crop you may reap of corruptions, that are sown to the flesh,
who have not sown in the same power and holy spirit as the apostles sowed withal, and to:
and the apostle speaking to the Ephesians of his knowledge in the mystery of Christ,
which in other ages was not made known unto the sons of men,
as it is now revealed unto his holy apostles and prophets, by the spirit:
now you that do not succeed the apostles in this spirit of revelation,
you do not know the mystery of Christ as the holy prophets and apostles did,
though you may have the form: and the apostle saith,
in Eph. 2:18. '`for through him both have an access by one spirit to the Father,
and in whom ye also are built together an habitation for God, through the spirit.`'

So all you that do follow the apostles and the true church in their succession,
it must be in the same spirit of intercession, that gives access to the Father,
and by the same spirit built together for an habitation of God.

And all you that deny having the same spirit the apostles had,
how can you be built together an habitation for God, or have access to the Father:
and the apostle saith, '`finally,
my brethren be strong in the Lord and in the power of his might;
put on the whole armour of God,
that ye may be able to stand against the wiles of the devil;
for we wrestle not against flesh and blood,
but against principalities and rulers of darkness, etc.
And take unto you the helmet of salvation, and sword of the spirit,
which is the word of God.`' And now mark,
they that follow the apostles in their succession and ordination in the true church,
they must be in the same power and might, and the same helmet of salvation,
and shield of faith, and their feet must be shod with the same gospel of peace,
and their loins must be girded with the same girdle of truth,
and the same breastplate of righteousness,
and they must have the same sword of the spirit, which is the word of God,
with which they must not wrestle with flesh and blood, but spiritual wickedness, etc.

Now you that are not in the same power of the same spirit, nor the same faith, truth,
righteousness, gospel, salvation, and armour of God,
you are not the successors of the apostles in their weapons, in their armour,
in their wrestling, who wrestle with flesh and blood;
neither are you able to stand against the wiles of Satan:
and the apostle saith, 2 Cor. 10:4.
'`we do not war after the flesh;
for the weapons of our warfare are not carnal but spiritual,
mighty through God to the plucking down of strong holds,`' etc.

Now all that follow the apostles in their succession, and possession, and ordination,
their weapons must not be carnal, and they must not wrestle after the flesh, if they do,
they are no ministers in the succession of the apostles in their war and their weapons:
and the apostle saith, 1 Cor. 12.
'`for by one spirit are we all baptized into one body,
whether we be Jews or Gentiles, whether bond or free,
and have been all made to drink into one spirit;`' +++[+++mark,]
here is the one baptism, and here is the one spirit,
and here is drinking into one spirit through several sorts of people;
these followed the apostles in their succession; and therefore,
all that follows the apostles in their succession, must be baptized by the same spirit,
as the apostles and true church were baptized withal, and drink into the same spirit;
and they that say, they have not the same spirit the apostles had,
cannot be baptized into the same body they were baptized into,
neither can they have the same union, in drinking in the same spirit they drank in,
though they may have the letter, they cannot succeed them in their baptism in the spirit,
and drinking in the spirit, if they have it not, and do not look for it, (to wit,
the spirit of Christ,) nowadays: and the apostle saith, 1 Tim.
iv. '`be thou an example of the believers, in word, in conversation, in charity,
in spirit, in faith, and purity.`' Now all the succeeders of Timothy and the apostle,
must be in the same example, in the same word, in the same conversation, charity, spirit,
faith and purity; and they that are not in the same spirit,
they cannot be in the same faith, word, conversation, charity, and purity,
and then such do not succeed the apostles, nor Timothy: and in 1 Pet.
'`ye also as living stones are built up a spiritual household, +++[+++mark, are built up,]
and an holy priesthood, to offer up spiritual sacrifices,
acceptable to God by Jesus Christ.`' Now all that follow the apostles
and the true church in their succession and possession of the spirit,
they must be the spiritual household and living stones,
offering up spiritual sacrifices acceptable to God by Jesus Christ.
And you that say, you have not the same spirit the apostles had,
and the church in the primitive times, you are not the successors of the apostles,
and you cannot be the living stones nor spiritual house, nor an holy priesthood,
neither can you offer up spiritual sacrifices to God, acceptable through Jesus Christ,
not being in the same spirit the apostles and true church were in.

[.blurb]
=== Concerning the Succession in the Fellowship.

'`If we say, (saith the apostle,) that we have fellowship with him, (to wit,
Christ and God,) and walk in darkness, we lie, and do not the truth;
but if we walk in the light, as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ cleanseth us from all sin.`'

Now all that do succeed the apostles and true church
in the fellowship it must be by walking in the light,
as he is in the light, and there they shall know cleansing by the blood of Christ,
but all such as hate the light of Christ, and call it of the devil or an idol,
such do not succeed the apostles and the true church,
though they may get the form of words, and say they have fellowship with him,
but walking in the darkness, and hating the light, the apostle tells you,
they lie and do not the truth, as you may see in 1 John; and the apostle saith,
'`for your fellowship is in the gospel.`' Eph.
i.

So all that follow the apostles and true church in their succession,
it must be in the same gospel, the power of God, and not in a form of godliness,
and denying the power of the gospel, that is a denying a succession in their fellowship:
and in another place he speaks of keeping the unity of the spirit,
which is the bond of peace:
so all that do not follow the apostles and true church in this unity of the spirit,
they want the bond of peace, yea, the bond of the Prince of princes`' peace;
and they that do follow the apostles and true church,
it must be in the same spirit that they were in,
and so in the same unity and bond of peace.

[.blurb]
=== Concerning Singing and Praying in the Spirit in the Succession of the Apostles.

The apostle saith, Eph. 6:18.
'`praying always with all prayer and supplication in the spirit:`'
now they must be in the same spirit the apostles and true church were in,
if they do succeed them in the spirit of prayer,
or else is it not like the pharisees`' babbling, and such as ask, and receive not?
And the apostle saith, Rom. 8.
'`likewise the spirit helpeth our infirmities;
for we know not what we should pray for as we ought,
but the spirit itself makes intercession for us,`' etc.
So all that do succeed the apostles in their prayer, it is not using a company of words,
and making prayers, but it must be in the same spirit which helps the infirmity,
and makes intercession; for without this spirit the apostles were in,
we know not what we should pray for as we ought; so therefore, the spirit is the helper,
and makes intercession; and therefore,
they that have not the same spirit the apostles had,
want the helper that should make intercession,
and are not in the succession of the apostles and the true church.
And again the apostle saith, 1 Cor.
xiv. '`I will pray with the spirit, and I will pray with the understanding also;
I will sing with the spirit, and I will sing with the understanding also,
when thou blessest with the spirit,`' etc.

And therefore all that do pray, and sing, and bless,
and not in the same spirit the apostles were in, and the true church,
they are not the succeeders of the apostles in their spiritual praying, singing,
and blessing, neither can they pray with the understanding, nor sing,
nor bless with the understanding, as the apostles and the true church did,
if they be not in the same spirit they were in, that gave forth the scriptures.
And the apostle saith, '`let the word of God dwell in you in all wisdom,
etc. teaching and admonishing one another in psalms, and hymns, and spiritual songs,
singing with grace in your hearts to the Lord.`' Col.
iii.

Now they that do succeed the apostles in this teaching and admonishing in psalms, hymns,
and spiritual songs,
they must succeed them in the word of Christ dwelling in their hearts,
and in the same spirit,
and same grace in the heart that the apostle and true church were in;
for they cannot succeed them in the letter,
in the form without the power in their possession:
and the apostle bids them pray without ceasing, and quench not the spirit,
and despise not prophesying: and they that do despise prophecy, and quench the spirit,
do not follow the apostles in their succession and ordination, and comfort,
and edification, who said, '`they may all prophesy one by one.`'

And so all that grieves, and quencheth, and vexeth the spirit of God,
and rebelleth against his spirit, and resisteth the Holy Ghost,
and hates the light of Christ,
doth not follow the apostles in their succession and possession: and the apostle saith,
'`but ye beloved, build up yourselves in your most holy faith,
praying in the Holy Ghost:`' so all that do succeed
the apostles and the true church in their praying,
it must be in the Holy Ghost, and succeed them in their building,
it must be in the holy faith, which Christ is the author of,
and they that are not in the same Holy Ghost and faith,
do not succeed the apostles in their building, and in their praying:
and the apostle saith, in 1 Thess. 2:10. '`ye are witnesses and God also, how holily,
and justly,
and unblameable we behaved ourselves among you that
believe:`' so they that do succeed the apostles,
must succeed them in that holy, and just, and unblameable life: and Christ saith,
in John iv.
'`they that worship the Father must worship him in spirit
and truth:`' now none can succeed the apostles in this worship
that Christ set up above sixteen hundred years since;
but who are in the same spirit and truth the devil is out of, that the apostles were in:
and so it is clear; all that do succeed the apostles in their succession, and ordination,
and possession, it must he in the same power and spirit: and saith the Lord,
'`I have ordained thee a prophet to the nations,
before I formed thee in the belly I knew thee.`' Jer. 1:5. And a multitude
of the like things concerning the succession of the apostles,
and the true church, of sanctification, justification, and perfection, and the like,
might be declared, and the apostle saith,
'`he that hath an ear let him hear what the spirit saith to the
churches:`' John speaks this seven times in the Revelation;
but if people have not the same power and spirit nowadays as the apostles had,
then they cannot hear what the spirit saith.

Now the apostle saith, 1 Cor.
xiv. '`if any thing be revealed to another that sits by, let the first hold his peace;
for you may all prophesy one by one, that all may learn, and all may he comforted;
for the spirit of the prophets is subject to the prophets: now all that deny prophecy,
and speaking one by one, deny the way by which the church may learn and be comforted,
and deny the subjection of the spirit of the prophets,
and such are not the succeeders in the same power and spirit the apostles were in:
and the apostle saith, 1 Cor.
xiv. '`except you utter by the tongue, words easy to be understood,
how shall it be known what is spoken; for ye shall speak in the air, therefore,
if I know not the meaning of the voice, I shall be unto him that speaketh as a barbarian,
and he shall be a barbarian unto me.`' And therefore all ye that speak, and preach,
and pray in an unknown tongue, or bless, the apostle telleth you, ye are as barbarians,
and speak to the air, and so you do not follow him in his succession; so therefore,
all that follow the apostles and the true church, in their succession, ordination,
and possession; either in preaching, praying, or singing, fellowship, or worship,
they must succeed them in the same power and spirit the apostles were in.

And the apostle saith, Gal.
vi. '`as many desire to make fair show in the flesh,`' and in Rom.
15:18. '`for I will not dare to speak of those things,
which Christ hath not wrought by me, to make the Gentiles obedient,
by word or deed.`' Now consider, do you follow the apostles in this succession,
dare you speak of things which Christ hath not wrought by you,
and bring people to be obedient by word or deed?
And is not this to make a fair show in the flesh
of that which Christ hath not wrought by you?
Then you are not succeeders to the apostles and true church: and the apostle saith,
in 2 Cor. 10:15. '`not boasting of things without our measure,`' that is,
of other men`'s labours, etc.
'`but according to the measure of the rule, which God hath distributed unto us,`' etc.
Now consider, do any follow the apostles in their succession;
but who follow them in the rule, to wit, of the spirit?
and do such follow the apostles in their rule, that boast of men`'s labours, to wit,
the prophets`', Christ`'s and the apostles`' words, and deny their rule of the spirit?
And did not the Corinthians make a great profession of Christ,
and looked upon themselves to be great gifted men?
and did not the apostle tell them, they were reprobates if they knew not Christ in them,
for all they might make a profession of Christ without them?
and so, is it not needful for all christians to try themselves,
whether they be in the faith, and prove, and know their own selves,
that Christ is in them, except they be reprobates;
and so reprobates may make a profession of Christ without them,
which do not follow the apostles in the succession, who preached Christ within,
the hope of glory, who said, '`the life that I now live in the flesh,
is by the faith of the Son of God, and I live, yet not I,
but Christ that liveth in me.`' Gal. 2:23.

So now, who follow the apostles in this their possession, succession, and ordination,
must follow them in the possession of this faith of the Son of God,
and in this life in him: and the apostle saith,
in Gal. 4:10-9. '`but now after that ye have known God, or rather, are known of God,
how turn ye again to the weak and beggarly elements,
whereunto ye desire again to be in bondage, ye observe days, and months, and times,
and years, I am afraid of you, least I have bestowed upon you labour in vain.`'

Now consider this, you that observe days, months, times, and years,
which he calls beggarly elements, and bondage upon such that went into such things,
he was afraid he had bestowed his labour in vain.
Now you that do observe these things, and follow these things, the apostle reproves,
do not you succeed them that went in bondage,
and are not succeeders to the apostles nor true church:
and in 1 John 5:12,20. '`he that hath the Son hath life,
and he that hath not the Son hath not life, and we know that the Son of God is come,
and hath given to us an understanding, that we may know him that is true,
and we are in him that is true, even in his Son Jesus Christ,
this is the true God and eternal life.`'

Now here you may see their possession, and what the apostles and the saints did possess,
and they did confess Christ was come without them and within them, and they were in him:
so all that follow the apostles and true church in their possession, and succession,
must have this confession, that Christ is come, and hath given them an understanding,
and to be in them, and to have the Son if they have life,
signifying that all the professors of the Son of God, if they have not the Son of God,
they have not life,
then they cannot succeed the apostles and the true church in the same life, possession,
and confession from the same faith, and so are no true witnesses.

Now who follow the apostles in the succession and ordination, are faithful witnesses;
and in Luke 24:48. Christ says to his disciples,
'`ye are witnesses of these things;`' and Acts 1:8. '`but ye
shall receive power after the Holy Ghost is come upon you,
and ye shall be witnesses unto me in all Judea, and Jerusalem, and Samaria,
and to the utmost parts of the earth.`'

Now mark, these were the faithful and true witnesses in the power and Holy Ghost,
that witnessed in Judea, Jerusalem, and Samaria, and to the utmost parts of the earth,
to Christ: nor can any succeed the apostles and be true witnesses,
but in the same power and Holy Ghost;
and in Acts 2:32-33. '`this Jesus hath God raised up, whereof we all are witnesses;
therefore, being by the right hand of God exalted,
and having received of the Father the promise of the Holy Ghost,
he hath shed forth this which we now see and hear,`' etc.
and in Acts 3:15. '`ye have killed the Prince of life,
whom God hath raised from the dead,
whereof we are witnesses;`' now all these were faithful witnesses:
and Acts 5:32. '`we are his witnesses of these things, (to wit,
Christ,) and so is also the Holy Ghost,
whom God hath given to them that obey him:`' mark then,
those that do disobey God and Christ, receive not this Holy Ghost,
and then they cannot succeed the apostles in the same Holy Ghost,
as faithful witnesses of Christ.
And Acts 10:39. '`we are witnesses of these things which he did, (to wit,
Christ,) both in the land of the Jews, and at Jerusalem,
whom they slew and hanged on a tree,`' etc.
And Acts 13:30. '`but God hath raised him from the dead,
and he was seen many days of them who came up with him from Galilee unto Jerusalem,
and we are his witnesses unto the people,
and we declare unto you glad tidings.`' And Acts 20:23.
'`save that the Holy Ghost witnesseth in every city,
saying, that bonds and afflictions abide me,`' (to wit,
him that preached Christ.) And Acts 26:22. '`having therefore obtained help from God,
I continue unto this day, witnessing both unto small and great,
saying no other things than those which the prophets and Moses did say should come,
that Christ should suffer and rise from the dead,
and should show light unto the Gentiles.`'

Now here you may see his faithful witnesses in the Holy Ghost, witnessed to all,
small or great, freely; and you that deny having the Holy Ghost the apostle`'s were in,
and the light of Christ, which he enlightens every one that comes into the world withal,
which he shows to the people and to the Gentiles,
you are no true witnesses nor succeeders to the apostles,
that call his light (that he hath showed to us Gentiles, which shines in our hearts,
to give us the knowledge of the glory of God in the face of Jesus Christ) of the devil,
and the Quakers`' new Christ, and natural;
you are no succeeders of the apostles in the power, light, and spirit,
nor true witnesses, but their opposers.
And the apostle saith, 1 Thess. 2:10. '`ye are witnesses and God also, how holily,
justly, and unblamable we behaved ourselves amongst you that believed.`'

Now we cannot witness that you walk so holily, justly, and unblamably in Christ,
we who are the true believers: and can you say, that God is your witness of your holy,
just, and unblamable life, as the apostles did?
And if you cannot, you do not succeed them in their possession and succession;
and the apostle saying before, '`that the Holy Ghost witnessed in every city, saying,
bonds and afflictions abide me.`' Now you that do persecute, and afflict,
and bring into your bonds and prisons, and say,
you have not the same Holy Ghost the apostles had,
and yet afflict them that be in the Holy Ghost,
ye are not the succeeders of the apostles in their ordination and succession.
And the apostle saith, 1 Tim. 4:14.
'`neglect not the gift that is in thee,`'
etc. and he was to hold the faith in a good conscience, 1 Tim. 1:19.
and he calls him his son in the faith, 1 Tim. 1:2.
And in 1 Tim. 6:11-12. '`but thou, O man of God,
follow righteousness, godliness, and faith, love, patience, meekness;
fight the good fight of faith, lay hold on eternal life, whereunto thou art also called,
and hast professed a good profession before many witnesses;
and hold fast the form of sound words, which thou hast heard of me in faith and love,
which is in Christ Jesus, +++[+++mark,]
in faith he had heard,`' and in love, which is in Christ Jesus;
this form of sound words he was to hold fast, which he had heard in faith,
etc. which Christ is the author of. 2 Tim. 1:13.
So they that be not in the same sound words,
which is heard in faith and love in Christ Jesus,
do not succeed the apostles in their possession nor ordination:
and in 2 Tim. 1:14. '`that good thing which was committed unto thee,
keep by the Holy Ghost, which dwelleth in us:`' +++[+++mark,]
keep by the Holy Ghost that dwelleth in us:
and in 2 Tim. 2:2. '`and all the things thou hast heard of me amongst many witnesses,
the same commit thou unto faithful men, who shall be able to teach others also.`'

Now mark, these followed the apostles in the succession in the Holy Ghost,
in the faith in the good things, which they dwelt in and committed unto faithful men,
which mystery of the faith is held in a pure conscience;
so none can succeed the apostles nor Timothy, nor these faithful men, but in the,
same faith, and in the same gift of prophecy, and in the good thing,
kept by the Holy Ghost dwelling in them:
now they that be not in the same faith and Holy Ghost,
and in the same good thing the apostle Timothy and those faithful men were in,
do not succeed the apostles and them, though they get the form of godliness;
and the apostle and Timothy did not commit those things to faithful men, to teach them,
and make a trade of them; for they that do make a trade of them are unfaithful men,
and do not succeed the apostles and Timothy,
but are succeeders of such as resist the Holy Ghost and disobeyers of God;
for the apostle saith,
'`he gives the Holy Ghost to them that obey him:`' and the apostle saith, 2 Tim. 3:5.
'`having a form of godliness but denying the power thereof,
from such turn away:`' now to have a form of Christ`'s words, the apostles`' words,
or Timothy`'s words, or these faithful men`'s words,
and deny the power and the Holy Ghost that led them to speak them forth,
they are to be turned away from, and are no succeeders of the apostles:
and the apostle saith, Heb.
xii. '`wherefore seeing we also are compassed about with so great a cloud of witnesses,
let us lay aside every weight, and the sin that doth so easily beset us,
and let us run with patience the race that is set before us,
looking unto Jesus the author and finisher of our faith,`' etc.

So you may see it is not any man, nor writings, nor words,
that is the author of people`'s faith, but Jesus Christ, and all must look unto him,
the author and finisher of their faith for it, if they do succeed,
this cloud of witnesses, which faith is the gift of God,
and brings us to have access to God, in which God is pleased: and the apostle saith,
1 John, '`that which was from the beginning, +++[+++mark, the beginning, to wit, Christ,]
which we have heard, +++[+++mark, they have heard that which was from the beginning,]
which we have seen with our eyes, +++[+++mark,
they had seen with their eyes that which was from the beginning,]
which we have looked upon, and our hands have handled of the word of life,
which was from the beginning; for the life was manifest, and we have seen it,
and bear witness, and show it unto you, that eternal life which was with the Father,
and was manifest unto us, that which we have seen and heard, declare we unto you,
that ye, (to wit, the church,) also may have fellowship with us, who had seen, heard,
looked upon and handled the word of life,
and truly our fellowship is with the Father and with the Son Jesus Christ;
and these things I write unto you, that your joy may be full.`'

And now mark, he that hath not the Son hath not life, and he that hath the Son hath life;
and therefore, consider all ye teachers and churches in Christendom,
where is your fellowship, have you heard that which was from the beginning?
Have you seen, looked upon, and handled, and so bear witness to what you have seen,
heard and handled?
And do you declare that to your churches which you have heard, seen and handled,
as the apostles did?
If not, you do not succeed the apostles in their hearing, in their handling,
in their looking, and seeing, and witnessing, and declaring to others:
for will not the worldling`'s reason teach you in your common courts,
that if a company of witnesses come to bear witness before a judge,
the judge asketh them, whether they have seen, heard, or looked upon the man;
if they say, no, they have never heard, nor looked upon him,
nor do not expect ever to see him while on this side the grave;
what do you think the judge will say to these witnesses, that will come to witness for,
or against a man they have never seen, nor heard, nor looked upon,
nor ever expect to see: but you may say, the witnesses heard others say so of him;
and will this please the judge?
Let worldly reason judge: so consider, if you never heard God`'s voice,
nor seen his shape,
as you may see in John v. Christ the judge did not accept of such as the Jews,
that were sayers of what the prophets and Moses said and did; for saith he,
'`the Father himself, which hath sent me, beareth witness of me,
but ye have neither heard his voice at any time,
nor seen his shape;`' then these were not,
nor are the true or faithful witnesses of God nor Christ.

And in Jer. 23:21. '`I have not sent these prophets, yet they ran,
I have not spoken to them, yet they prophesy:`' and ver. 30, 31.
'`therefore behold I am against the prophets, saith the Lord,
that steal my words every one from his neighbour: behold I am against the prophets,
saith the Lord, that use their tongues, and say,
he saith it;`' and ver. 16. '`thus saith the Lord of hosts,
hearken not unto the prophets, nor unto the words of the prophets that prophesy unto you,
they make you vain, they speak a vision of their own heart,
and not from the mouth of the Lord:`' and in Ezek xiii.
'`woe unto the prophets that follow their own spirit, and that see nothing,
I have not sent them, saith the Lord, and they say, the Lord saith it,
albeit I have not spoken to them; I am against you, saith the Lord,
because with lies you make the hearts of the righteous sad, whom I have not made sad, etc.
I will deliver my people out of your hand, and you shall know that I am the Lord,`' etc.

And now consider these were not the succeeders of the true prophets,
though they used their tongues,
and spake and ran with a divination of their own brains and studies,
the Lord was against such, though they might say, thus saith the Lord,
and get the words of their neighbour prophets.
So though you may say, thus saith Christ, and thus say the apostles,
and be such as run and God never sends, nor Christ, and have neither heard God`'s voice,
nor seen his shape, and the Lord nor Christ have not spoken to you, and say,
you have not the Holy Ghost as the apostles had, and so follow your own spirits,
and see nothing; and do not all, who say they have not the same spirit the apostles had,
follow their own spirits, and see nothing,
and so are succeeders of these false prophets which God reproved,
and not the true prophets nor apostles?
'`And how can you preach, except you be sent?`' saith the apostle;
for whom Christ sends they be in the Holy Ghost, and none can call him Lord,
but by the Holy Ghost.

And Christ saith, '`that he may abide with you forever, to wit, the Comforter,
the Holy Ghost, John 14:16. even the spirit of truth,
that shall lead you into all truth,`' and he should dwell in them,
and should be with them; and also Christ saith,
he would be with them and in them to the end of the world.

And now, therefore, how can you be faithful witnesses to God and Christ the judge,
by using your tongues, and saying, he saith it, or by getting the form of godliness,
and denying the power and the Holy Ghost, to wit, the witness; and by your running,
and God never sent you; and though you say, he saith it, and hath never spoken to you;
yea though you may be ministers of the letter from Genesis to Revelations, and say,
he or they say it, and yet never hear his voice, or see his shape at any time;
then how at any time can you be true witnesses,
except you were in the same power and Holy Ghost the prophets and the apostles were in?

'`He that hath the Son of God, hath life, and he that hath not the Son of God,
hath not life;`' then how can he be a witness of the life that he hath not seen, heard,
nor handled?
And if Christ be not in him, he is a reprobate,
and then how can reprobates be faithful witnesses of him,
though they may talk of him by the letter he is come,
as the Jews by the letter talked he was to come?

And therefore, they that have the Son of God they have life, they see it, they hear it,
they handle it, they look upon it, that life that was in the beginning, and can say,
the Son of God is come, and hath given us an understanding, and we know him that is true,
and are in him that is true, and so are faithful witnesses,
succeeders of the apostles and the true church,
and can declare what their eyes have seen, and their hands have handled,
and what they have heard, and what they have looked upon,
and bear witness and show to others that eternal life, which was with the Father,
and manifest unto us and in us, and can both witness and declare this to others freely,
as they have received freely from God, that others may have fellowship with them,
and can say truly,
'`our fellowship is with the Father and with the
Son,`' and this we declare and witness to:
I say, all that succeed the apostles and the true church, it must be in this hearing,
sight, handling, witnessing and declaring of this possession, of this life,
Christ that was in the apostles and the true church, else they are no succeeders to them,
nor in their possession: for all the false witnesses against the prophets,
Christ and the apostles, they might profess the scriptures, and the beast, whore,
antichrist, Satan`'s messengers and false apostles, they might profess Christ in words;
but they that have him not, have not life, and so are no true hearers, seers,
witnesses nor succeeders, neither can they call Jesus Lord,
except they be in the Holy Ghost the apostles were in,
neither can they witness as they did without the Holy Ghost,
neither can they build up one another,
except they be in the same Holy Ghost the apostles and true church were in,
praying in the Holy Ghost, building up one another in the most holy faith.

So all true succession is in this building in the
Holy Ghost and holy faith that they were in;
and if they be not in this, they are pluckers down, and scatterers from the head,
lo here, lo there, lo there Christ without them, and not within them,
and so no succeeders to the apostles, nor true Church, but to such,
against whom the cry is, lo here, lo there, which Christ commands not to follow.

And in 2 Cor. 2:17. '`for we are not as many which corrupt the word of God,
but as of sincerity,
but as of God in the sight of God speak we in Christ.`' And in 2 Pet. 2:3. '`and
through covetousness shall they with feigned words make merchandise of you,`' etc.

Now consider,
such as these did not follow the apostles in their succession nor ordination,
nor any that be in feigned words, who through covetousness make merchandise of God`'s,
Christ`'s, the prophets`' and apostles`' words, and of people.

And none follow the apostles in their succession and ordination, but such as be of God,
and in the sight of God speak the truth in sincerity in Christ Jesus.

So all they that teach '`for filthy lucre, and serve not the Lord Jesus Christ,
but their own bellies,
and by good words and fair speeches deceive the hearts of
the simple,`' Rom. 6:8. all such follow not the apostles,
and true church in their succession, but are reproved by them.

And in Numb.
xxviii.
you may see how God ordained his law in Mount Sinai,
and that his people should walk in it,
which law commanded their offerings and the priests to offer and attend upon their service.

But Christ Jesus, who ends the law and the offerings, and the priests,
by offering up himself once for all, he ordained his disciples to preach,
and commands them, freely as they had received of him, so freely to give.

And therefore, they that follow the apostles in their ordination and in their succession,
must give freely, as they have received freely.

And Christ commands his disciples not to swear at all,
but keep to yea and nay in their communication, and to bless, and curse not.

And the apostle that kept in the ordination of Christ and his command,
forbid swearing and cursing, and set up yea and nay, as Christ commanded.

Now all them that swear and curse, do not follow the apostles in their succession,
nor ordination, nor qualification.

And Christ forbids his ministers from being called gracious lords, as the Gentiles were,
or for being called of men master, as the pharisees were.

And therefore, they that follow the apostles in Christ`'s ordination,
and the succession of the apostles, must keep his commands;
for such ministers that do plead for such titles, and to be called of men masters,
and gracious lords, succeed the pharisees and the Gentiles,
and not Christ nor the apostles.

And therefore none can succeed the apostles,
but in the same power of God and Holy Ghost that they were in,
who gave forth the scriptures, and they must receive Christ, and live in him,
who is the rock of ages, and so to know him,
to be with them and in them to the end of their age, and so to the end of the world,
who is the rock and foundation of all the righteous in their ages;
and they that do succeed the apostles, must succeed them in their work and foundation.

So in the light, in the life, and in the power of Christ Jesus, and in him,
and he in them, who is the first and last;
here is all the true succession and succeeders, who walk and live in Christ Jesus,
and he in them, who is first and last.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 10th of the 9th month, 1675.
