== Possession above Profession;

[.heading-continuation-blurb]
Being a Discourse,
in which it may be clearly seen that many that make a Profession of Christ in the Flesh,
and deny him in his Light,
which he enlighteneth every man that cometh into the world withal,
(which Light is the Life in the Word,)
and speak evil against it, are such as possess him not,
but persecute his Light and Life as the Jews,
that persecuted him in the days of his Flesh.

[.heading-continuation-blurb]
And how that many Turks and Heathens will own his Divine Light more than many of them,
that make a Profession of Christ in the Flesh.

[.heading-continuation-blurb]
And likewise, how that all such as profess Christ Jesus has bought them,
are to be governed and ordered by him, their owner;
for the worldling`'s reason will say,
'`that which he hath bought and paid for, is his own to order and govern,`' etc.--By G. F.

Now all christians that confess Christ come in the flesh, in words,
and yet do not obey him, they have not the comfort of him.

For ye christians that do confess Christ to be come in the flesh,
and yet will not own his light,
that he doth enlighten every man that cometh into the world with, to be a heavenly,
divine, and saving light for every one to believe in,
it is but a fleshly profession of Christ come in the flesh, and not a spiritual.
('`For none can call him Lord,
but by the Holy Ghost,`') nor is it a knowing of him who is the mystery;
for Christ is a mystery; and this mystery is known and seen only by his light;
and such know Christ no more by the letter of the apostles,
than the Jews knew him by the letter of the prophets, and Moses, or as Saul;
for when he was Paul, he knew him by revelation; and Peter knew him by revelation;
and so the heavenly spiritual man is known by the '`revelation
of his light and spirit,`' and the revelation of the faith
(that is the gift of God,) which Christ is the author of;
and Mary knew him by revelation, and Simeon knew him by revelation,
and the shepherds knew Christ by revelation through the angel of the Lord, as in Luke ii.
and Joseph knew him by revelation: and so, that which does reveal the Son of God,
is the light and spirit of God: to know him to be the Christ, as he was man,
and as he was God; I say, to know Christ, the spiritual and heavenly man,
and his heavenly flesh and blood, that is meat indeed and drink indeed to the saints,
which who eats of, lives forever, and lives by the Son as he lives by the Father,
who was promised and prophesied of to come, who came according to God`'s promise,
and the prophets, '`who suffered, and was crucified and buried,
and the third day rose again, and remains in the heavens, till all things be restored;
who is ascended far above all principalities, powers, thrones, and dominions,
that he might fill all things, who is the head of his church,`' that neither powers,
thrones, principalities, nor dominions, can pluck out of his throne,
and crucify him again, though they may crucify him to themselves afresh,
and persecute him in his members.

So his heavenly flesh is the saints`' daily food and bread from heaven;
and they that deny the heavenly man, Christ Jesus,
that died and suffered without the gates of Jerusalem, above sixteen hundred years since,
his sufferings, death and '`resurrection, deny their own food,
and their own heavenly bread, and him that offered up himself for their sin,
and had power to lay down his life, and to take it up again.`'

For it was Christ that died, and is risen, and is at the right hand of God,
the heavenly and spiritual man; and it is Christ Jesus,
who makes intercession for the saints.

So there is one Mediator between God and man, the man Christ Jesus,
the heavenly and spiritual man, the heavenly and spiritual bishop,
the heavenly and spiritual counsellor, and the heavenly and spiritual '`shepherd, priest,
teacher, and leader.`'

And now all you that do profess Christ in words,
and have a profession of him in the flesh, and deny him in his light, in his divinity,
'`which enlighteneth every man that cometh into the world,`' hear what Christ saith,
'`believe in the light;`' and John, speaking of Christ, saith, '`in him was life,
and this life was the light of men; and the light shined in the darkness,
and the darkness comprehended it not;`' and '`that was the true
light which lighteth every man that cometh into the world;
and he was in the world, and the world was made by him, and the world knew him not;
he came to his own, and his own received him not; but as many as received him,
to them he gave power to become the sons of God,
even to them that believed on his name.`'

So it is clear the world was made by him, and yet the world knew him not,
neither can the world know, but by revelation in the light.
And his own, the Jews, that he came to, they received him not;
for they stopped their ears and eyes to the light; but as many as received him,
'`to them he gave power;`' so that here is a distinction betwixt the world,
and '`his own,
and them that received him;`' for he gave them such power as to become the sons of God,
'`them which believed in his name:`' and what is his name?
the '`Light, the word Jesus; the Saviour, Christ, the anointed of God,
conceived by the Holy Ghost,`' etc.

And now, all you that do make a profession of Christ in the flesh,
and do not believe in him as the heavenly light,
that enlighteneth man that cometh into the world;
how can you believe in the man Christ Jesus, who is a mystery,
except (as I said,) you do believe in the light (as Christ commands,) that doth enlighten, etc.
(which light manifests him,) and so become children of the light:
and it is clear by Christ`'s words, there are none children of the light,
but by believing in the light.

So the rest are children of darkness,
though they may make a profession of Christ in the flesh, and after the flesh.

And not to believe in the light (which is the life in Christ, the word,
which was in the beginning) what does this differ from the
'`devil`'s believing and trembling?`' I say,
those who do not believe in the divine light of Christ, as he is God,
which light is the life in the word, which is God, (that is called life in him,
and the light as it is in people that be in darkness.)

And you say, this divine, spiritual, heavenly light of Christ is not saving:
then why does Christ say, '`believe in the light;
that ye may become children of the light; and he that believes, is saved,
and he that does not, is condemned already; and I will give him for a covenant of light,
and he shall be my salvation to the ends of the earth,
said God?`' so this covenant of light is saving then.

Now the Jews, and the Turk, and heathen, and Indians,
that do not nor will not profess and own Christ in the flesh, to be the Saviour;
if one come to speak to them of their evil deeds and words, and ask them,
if there is not something in them that tells them, they should not speak and do so,
or so wickedly?
(for the light of Christ troubles and condemns them if they
do evil,) here they will confess to the light of Christ,
though they know not what it is which is the life in the word, and light in them,
that shines in their darkness, and their darkness comprehends it not,
and so do not obey it, nor believe in it,
but hate it (many of them,) because it will reprove them,
and because their deeds are evil; and this is according to Christ`'s words,
'`this is the condemnation, that light is come into the world,
and men love darkness rather than light, because their deeds are evil.`'

For, every one that doth evil, +++[+++mark,]
it is not some, but every one that doth, (that is,) acteth evil, hateth the light,
neither cometh to the light, least his deeds should be reproved: now he cannot say,
'`it is not there, nor within him,
nor that he hath it not,`' when he will not come to it;
but men will not come to this divine and spiritual light,
least that they should be reproved by it.

Now, Christ makes a distinction betwixt him that loves, and him that hates it;
'`for he that doth truth,`' saith he, '`cometh to the light,
that his deeds may be manifest that they are wrought in God.`'

Now, they that hate the light, and will not come to it,
they are such as do not the truth, then they do the evil,
yet make a profession of Christ in the flesh, that he is come,
as the Jews did he was to come; and so with your darkness,
you cannot comprehend the light, though it shines there, yea, in your darkness.

But the darkness (you say) is within you: yet you will not have this divine,
heavenly light of Christ to be within you:
Oh! can such gross darkness comprehend this divine, heavenly light,
which is the '`life in the word, and the true light,
that enlighteneth every man that cometh into the world;`' and the prophet saith,
'`whom God hath given for a covenant of light,
and to be his salvation to the ends of the earth;`' believe in the light.

And now, the children of darkness, that cannot comprehend the light, (which is the life,
in Christ the word,) but hate the light, whose deeds be evil,
and will not come to the light, because it will reprove them; this is their condemnation,
(Turks, Jews,
heathen and apostate christians,) that believe not in the
light (which is the life in the word,) as Christ commands.

And now mind this, you professors that be in darkness,
and therein cannot comprehend this divine, spiritual, saving, heavenly light,
which is the life in the spiritual word,
but with your darkness are wrangling and jangling,
and are raging like the waves of the sea, foaming out your shame against it;
consider that some of you call this divine, spiritual light,
(which is the life in the word,) natural, carnal, and of the devil, the light of nature,
the Quakers`' idol, a '`will o`' the wisp,`' and a new Christ;
and many such blasphemous speeches you have published against the true light,
'`which enlighteneth every man that cometh into the
world,`' which light is the life in the word Christ;
'`for in him was life,`' speaking of the word which was in the beginning,
'`and the life was the light of men.`'

Now, by this true light, all false lights, false christs, and you, are comprehended,
and seen, and judged, even by this divine, heavenly light, which is the life in the word,
which Christ, the Saviour, and heavenly, spiritual man,
enlightens every man that cometh into the world withal, and says,
'`believe in the light.`' And so now, you that cannot comprehend this light,
which is the life, and make a profession of Christ in the flesh,
and yet deny his divine light, and blaspheme against it, and will not own it,
but hate it, and spit at it,
and call it the '`light of the devil;`' you are like the pharisees and chief priests,
and the Jews, that cried out,
'`the temple of the Lord,`' and yet persecuted Christ`'s spiritual worship:
you make a profession of Christ in his flesh, and will not own his light,
which enlightens every man, which is the life in him,
you are as bad or worse than the Jews, Turks, or Indians;
for they will confess to that light which does condemn evil in them,
but you make a profession of Christ in the flesh, yet deny his light,
which is life in him; and the Jews, Turks, and Indians,
will confess to the light that does reprove them, though they will not obey it;
yet this divine, heavenly light will make every tongue to confess,
though you that do make a profession of Christ in the flesh,
will not confess to this divine light of Christ, so far as Jew, Turk, and heathens;
and they will not give this heavenly light, which is life in Christ,
such blasphemous names as you do.

So you, in your profession of Christ in the flesh, are darker to his light than the Jews,
Turks, Indians or heathens, yea, such as do not profess him come in the flesh:
but you and they all must be made to confess to this heavenly,
divine light (which is life in him,) to your condemnation that hate it,
and blaspheme against it.
and will not come to it, because ye do not the truth,
and so will not turn at the reproofs of it, and believe in it,
that ye might become children of the light.
And now, they that are turned at the reproofs of it, and are turned from the evil,
and come to do the truth, they believe in the light, as Christ commands,
and love the light, and bring their deeds to the light,
that with the light they may see their deeds wrought in God; and so,
believing in the light, become children of the light: but all you that hate the light,
'`you hate the life in Christ, and you, do not see how your works are wrought.`'

And all you, that be the haters of this light and life,
and have given so many blasphemous names to it;
though you make '`a profession of Christ in the flesh, and call him Lord, and say,
you have preached him in the streets;`' I must tell you,
'`you are not grafted into Christ; for none are grafted into Christ,
but by believing in the light;`' for you do hate
the light which Christ commands you to believe in,
which is the life in himself.

And I tell you, they that believe in the light,
(which is the life in him,) as Christ commands, are grafted into Christ, their way,
their truth, their life, their rock and foundation, their shepherd, their bishop,
and their priest, who is made higher than the heavens, who is first and last.

And all you that are the haters of this divine, spiritual light,
which is the life in Christ, and will not come to it, are the doers of evil,
and not of truth; and calling this light, which is the life in Christ,
the Quakers`' new christ, and their idol, and a natural created light, and of the devil,
you do wickedly.

I tell you, you are persecuting the life of Christ Jesus,
though ye are the professors of him in the flesh;
for you are the persecutors of him in his light, and life, and spirit now in our age;
you will not behold his glory.

Like as the Jews were blind, and stopped their eyes and ears against the light of Christ,
and persecuted him in their day in the flesh, and put him to death in the flesh,
and crucified him without the gates of Jerusalem, yet he arose again the third day,
and is ascended above all principalities, thrones and dominions,
and remains in the heavens until the restitution of all things; him, I say,
you cannot crucify any more, nor put to death in the flesh any more;
but you may and do crucify him to yourselves afresh, and persecute him in his members,
yet death has no more dominion over him;
for he is ascended far above the reach of all the powers of the earth, who was dead,
and is alive, and lives forevermore.

But as the Jews persecuted him, and cried, '`crucify him, crucify him,`' in the flesh;
so you professors of Christ in the flesh, persecute Christ in the spirit, in his light,
and in his life, who cannot reach to crucify him in his flesh any more,
but to yourselves and in his members.

And now, as the Jews cried, '`crucify him, away with him,`' in the flesh;
so you that do profess him in the flesh, do not you cry,
'`away with the light which enlightens every man that cometh
into the world,`' which is the life of Christ?
And you spit at the life and light of Christ, as the Jews spit at him in the flesh,
and cry, '`away with this light,
away with this life,`' which is '`in the word:`'
so you professors of Christ in the flesh,
do fight against Christ in his light and life, as the Jews did against him in his flesh.

Again, as the Jews hated Christ in the flesh,
you that profess him in the flesh hate this divine light, which is the life in him;
and cry, '`away with this light; and call it natural, and of the devil,
and the Quakers`' idol, and new christ, which is the life in Christ,
and this you cry away withal;`' and some of you have cursed it,
and in your darkness have called it a '`dark light,`' and '`dim light,`'
and '`beggarly scrap,`' and ye make a profession of him in the flesh.

And Christ Jesus is not known as he is God in his divinity, nor in his flesh,
as he was manifest, but by this his divine heavenly light, which we own and believe in,
as he commands, who are children of the light;
which name or title Christ bestowed upon us before
you professors nicknamed us with the name of Quakers,
in the year 1650, which name one Bennet, at Darby, gave us, when he cast us into prison:
and as it is said, '`young men, you are strong, you have overcome the wicked one;
fathers, you have known him from the beginning;`' that is,
you have known him in his divinity, you have known him in the promise,
and in the prophets,
you have known him in his birth and '`conception
by the Holy Ghost,`' ye have known him in his '`life,
preaching,
and miracles,`' and the '`contradiction and blasphemies of sinners
against him;`' so you have known him in his sufferings,
and have fellowship with him; you have known him in his death and passion,
as he was crucified without the gates at Jerusalem, and buried,
('`who saw the travail of his soul,
and was satisfied;`') you have known him in his death, burial, and suffering,
who lay three days and nights in the sepulchre, (or heart of the earth.
Matt. 12:40) you have known him again in his resurrection,
who is ascended above all principalities, powers, thrones, and dominions,
and remains in the heavens till all things be restored; and restoring, by his light,
power, spirit, grace, and faith, who is before all, and above all, first and last,
and has made us sit together in the heavenly places in Christ Jesus,
where our bread is sure, and our water is sure, whose flesh is meat indeed,
and whose blood is drink indeed.
And we that do believe in the light of Christ, which is the life in him,
cannot deny the flesh of Christ, our heavenly bread, who remains in the heavens.
I say,
that Jesus Christ that died without the gates of
Jerusalem above sixteen hundred years since,
who hath enlightened us with his heavenly divine light, which is the life in himself,
through which light we are grafted into Christ, the heavenly spiritual man,
who hath saved, redeemed, and purchased and bought us with his precious blood,
the blood of the heavenly man, the second Adam,
who does cleanse and sanctify us with his blood, the blood of the new covenant,
Christ Jesus: so I say, he that bought us, and purchased us,
and hath given a price for us, to wit, his heavenly and precious blood,
we believing in the light, as he has commanded, which is the life in him,
and he hath sealed us, Christ, the heavenly man hath set his heavenly seal upon us:
so here is his heavenly mark upon us, his sheep, and we are his that has purchased us,
and given a price for us, to wit, his heavenly blood; we are not our own,
and are not to live to ourselves, nor to order ourselves, but to live unto him,
and be ordered, ruled, and governed by him,
of the increase of whose government there is no end; and so to be counselled by him,
and led by him, and taught by him, as he is our heavenly prophet, and to be fed by him,
our '`heavenly shepherd,`' in his heavenly pasture and fold; and to be overseen by him,
as he is our '`heavenly bishop,`' that we his sheep
do not go astray out of his heavenly pasture,
that are come in by him,
the '`heavenly door;`' who is our '`heavenly priest,`' that offered up himself for us,
and ends all the outward typical offerings, that were offered up for sin,
as well as the other; and '`he offered himself up to God once for all, for our sins,
a sweet-smelling sacrifice;`' wherefore '`the offerings
of bulls and goats thou wouldst not,
but a body hast thou prepared me to do thy will,
O God;`' so God prepared him a body to do his will,
and with his body he did fulfill his will, according to all his prophets and promises,
whose flesh saw no corruption, which is the heavenly bread, and his blood,
which purchases, which is not corruptible;
for the blood of bulls and goats was corruptible,
but this precious blood of Christ is incorruptible, that cleanseth from corruption: so,
by his precious blood are we cleansed from all sin; he is a priest,
made higher than the heavens,
a '`heavenly priest,`' and a '`heavenly spiritual man,`' offered up himself first for us,
and offers us, and cleanses, and washes, and sanctifies us with his blood,
he who is without spot or wrinkle, to make us without spot or wrinkle,
that he may present us pure and clean, without spot or wrinkle, up to the eternal, pure,
holy, uncorruptible, infinite God, who is a consuming fire to the wicked,
who dwells in glory, and inhabits eternity.

Now, all you that profess Christ come in the flesh, and say, '`he has purchased you,
and paid a price for you;`' what!
For you to live to yourselves, and serve yourselves, and do your own wills,
and to hate his light,
which is the '`life in him,`' and blaspheme against it with many blasphemous words,
as '`natural,`' and '`of the devil,`' etc.?

Now, if you were in the sense of Christ`'s purchasing of you, and paying a price for you,
to wit, his blood; and every one as in a sense of that, you the earthly,
that have pierced the heavenly man, would not then hate his light, which is his life,
but believe in it, that you might be sealed with his heavenly seal, as we are,
and have his heavenly mark, that he sets upon his sheep.

But see if you have not the beast`'s mark in your forehead, and outward profession,
who are without the light and life of Christ,
and the spirit and power the apostles were in;
and if that you will not maintain with your right hand, in which the beast`'s mark is,
with all your strength and power, in obedience to the beast, the dragon`'s power,
(the devil,) to persecute the light and life of the Lamb,
and such as have his mark and seal.

For the beast, the dragon`'s power, and his mark in your forehead and right hand,
is easily seen, both in the notion and strength,
and in your obedience and conformity to the dark power, and in your blind zeal,
without knowledge, by them who are in that power, and spirit, and light,
which is the life in Christ, which the apostles were in,
who had the true knowledge and true zeal, that wrestled not with flesh and blood,
but with spiritual weapons against the rulers of darkness and spiritual wickednesses;
but the blind zeal wrestles with carnal weapons, against flesh and blood,
with the beast`'s mark in their forehead and right hand,
and with the dark power`'s strength in a notion and outside profession,
without the power and spirit of the prophets, Christ and the apostles,
and such do not know what spirit they are of,
neither have they rule over their own spirits;
but are like unto a city whose walls are broken down, that is on heaps: and pray,
you Christendom, see whether your walls are not broken down?
And if you lie not all on heaps?
And the cause and reason is, because you have not rule over your own spirits,
and are all in heaps about your professions and religions.
But as I said before, if you were in the sense that Christ has purchased you,
you would all live to him, not to yourselves, and you would serve him,
and not yourselves, and the world, and your lusts and pleasures;
but serve him who is heavenly, and not this world,
in whom you might have peace as we have: for common reason teaches this,
'`that if a man buy a horse, or sheep, or other cattle, and give or pay a price for them,
the horse and cattle are at his own use, and service, and command that has bought them,
and to be ordered and fed by him; and his oxen shall know his crib who has bought them,
and his ass will know him as owner, who has bought him, and paid a price for him;
and he that has bought his sheep, and sets his own mark upon them,
and orders his pastures for them,
would not lose them after he has bought them;`' this
the common reason of every selfish man understands.
But Christ our spiritual heavenly man has purchased us with his blood,
and paid a price for us his sheep, and has sealed us, and set his mark upon us,
so that we are his, and not our own,
and are at his ordering and disposing by his heavenly power;
and he orders us heavenly milk; and wine and honey, and heavenly bread and water,
and the heavenly clothing, the fine linen that he clothes us with,
and feeds us in his heavenly pastures of life, his lambs and his sheep;
and so we are to live to Christ, the heavenly man, and to serve him, and to do his will,
and so know his doctrine; and so here we know our master`'s crib, and know our owner,
and his heavenly voice that has purchased us, and paid a price for us,
our heavenly owner, who has paid the heavenly price for us;
and not like such that are worse than the common ox and ass, that know not their owner,
nor their master`'s crib.

So, the Lord give all people understanding, that they may believe in his light,
and in his light see their owner, and his crib, and him that has purchased them, to wit,
the heavenly man, Christ Jesus, the light of the world.
And is it not fit, ye earthly men, think you,
that the heavenly man should have them which he purchases, and has paid a price for,
at his service, and to be at his ordering and rule, and to live to him,
and to do his will, and to have them at his heavenly command and order,
seeing that which you purchase with your money, as goods, and cattle, and such like,
ye will have at your command and ordering, or you will give judgment,
'`Whose else are they?
For we have purchased them with our money,`' say you; so whatever you buy,
you will say it is ours, and they are our own; for we bought them:
and if they be at your service and at your own ordering,
and shall not dispose of themselves, then consider,
hath Christ purchased you with his blood?
Hath he bought you, and paid a price for you?
Then are not you to be ordered by him, and his power, and spirit,
and light in your hearts, and grace there?
Whose are you?
Are you not his,
if he hath bought you and paid a price for you must you dispose of yourselves,
or serve yourselves, or him?
Must you live to yourselves or him?
Must you go do what you will yourselves, or by his power and command?
Shall thy ox, or ass, or sheep go when and where they will, or be at the master`'s power?
But if you make a profession of Christ, that has purchased you, and hate his light,
and do evil, and will not come to truth, and quench the spirit, and vex it,
and grieve it, and rebel against it, and walk despitefully against the spirit of grace,
and turn it into wantonness, and despise prophecy and revelation,
by which Christ is known, that has purchased you: poor people!
You remain in the dark; and to such Christ will say,
'`I know you not;`' and how should ye know him,
who hate the light that gives the knowledge of him?
For such they are that Christ knows, who believe in his light, and are grafted into him,
the life, and become children of the light, and turn from darkness, and do the truth,
and walk in the spirit, and neither grieve nor rebel against it,
and in it is their fellowship and in the spirit of revelation,
which reveals the things of God to them, and Christ to them, who is the spiritual man,
through which they keep the testimony of Jesus, which is the spirit of prophecy,
and so of Christ`'s, the heavenly man`'s sheep,
who by his spirit know his spiritual and heavenly voice, and walking in the spirit,
follow the spiritual and heavenly man Christ Jesus,
who has purchased them with his heavenly blood, and feeds them with his heavenly flesh,
the bread from heaven; and this I and they witness, who are within his heavenly fold,
and have his heavenly seal and mark from the heavenly Father,
and wish all you knew the same.

[.blurb]
=== Some queries to you that make a boast of your profession of Christ in the flesh, and yet deny him in his light, which is the life in the word.

Seeing Christ that was crucified, the same is risen, and remains in the heavens,
and is ascended far above all principalities, powers, thrones and dominions,
etc. and since John saith in the Revelations,
'`that the beast with his horns should make war with the Lamb,
but the Lamb should overcome him; for he is King of kings, and Lord of lords,`' etc.
Rev. 17. And again, in Rev. 19. '`the beast and the kings of the earth,
and their armies shall gather together to make War
against him that sat on the white horse,`' etc.

Now I query this of you: how do those make war against Christ, the Lamb of God,
seeing he is risen?
Did they make war against him in his flesh, as the Jews did,
or against him in his light and life, and in his spirit, as he was in his people,
seeing that he was ascended far above all principalities and powers, after he was risen?
Therefore, I would know of you, how the beast and his followers make war with the Lamb,
if it be not against his light, and against his life,
and against his spirit in his people, by calling him in his light, and life, and spirit,
natural, and of the devil, and a false christ, etc.?
If they cannot war against Christ in the flesh,
and if you confess that he is ascended far above all principalities and powers,
etc. then do not such war against him in his life, and spirit, and light,
which Christ commands all to believe in?
And if they be not warriors against him in his flesh,
then are not they warriors against him in his light, life and spirit?
And then are not you the warriors against him, that hate his light,
which is the life in the word, and call it of the devil, and a false christ, and an idol,
etc.?
And do not you think, that the heavenly warrior, the Lamb, will overcome you,
who is King of kings, and Lord of lords, and will take the beast and false prophet,
and cast him into the lake of fire and brimstone, etc.?

Again it is said, '`the dragon was wroth with the woman, and made war with her seed,
that kept the commands of God, that have the testimony of Jesus.`' +++[+++mark, have it,]
Rev.
xii. And also, it is said, in Rev.
xiii.
'`the beast that opened his mouth in blasphemy against God,
to blaspheme his name and his tabernacle, and them that dwell in heaven,
and power was given unto him to make war with the saints,`' etc.
Now was not this war against them, the saints, the sanctified ones,
that lived in the light, and believed in the light, and were children of the light,
and were grafted into Christ by belief in the light, which was the life in the word,
who have the testimony of Jesus, the spirit of prophecy, etc.
Was not this war against them, because Christ was in them by his light and life,
spirit and power?
And so do not such war against him now,
that have but the form and outward profession of Christ`'s and the apostles`' words,
against the believers in the light, which is the life in Christ the word,
and blaspheme against it?
And is not that from the spirit of the beast, and not from the spirit of Christ,
to say they have not the same spirit and power Christ and the apostles had?
But indeed, how should you, that will not believe in his light,
with which he enlightens every man that cometh into the world?
Is not this the cause of so many heaps and heads amongst people in the whole world,
because they do not believe in Christ the true light,
that lighteth every man that cometh into the world,
by which they might become the children of light, and grafted into Christ their life,
and so see him, and hold to him their head, and keep the testimony of Jesus?
And did not Christ say to that great professor Saul, and doth he not say to such,
'`why persecutest thou me?
It is hard for thee to kick against the pricks:`' and further, does not Christ say,
I was in prison, and hungry, and sick, and naked, etc.
Was this a persecuting Christ that died at Jerusalem in his flesh?
Or was it a persecuting Christ as he was manifest in his members by his light, and life,
and power, and spirit, which were the possessors of Christ?
And if their persecution was against Christ in his light and life,
which they persecuted the believers in,
and such as were the possessors of Christ in his spirit; then I say again,
are not you the same persecutors, that blaspheme against his light,
and persecute his members that confess to it, and believe in it?
So consider Christ`'s words to Saul, while he was persecuting him,
he '`kicked against that which pricked him,`' he
was kicking against that which pricked him,
whilst he persecuted Christ in his members: so see if you can tell,
what it was he kicked against?
And what that was that made Judas confess he had sinned in betraying the innocent blood?
Was it not that which condemned him, that will make every tongue to confess?
And do not all they crucify Christ to themselves afresh and put him to open shame,
that live not in the life, and the same power and spirit that the apostles lived in,
and believe not in the light, which is the life in Christ the word,
and so not grafted into him, because of unbelief in Christ the light and life?
And are not all the believers in the light, which is the life in Christ grafted into him,
members of his body, and of his flesh, and of his bones, yea or nay?
And so they that persecute Christ`'s members, do not they persecute him?
And are not all such unbelievers, that persecute the believers in the light,
which Christ commanded people to believe in?
For, where did any believers in the light, that were children of the light,
and grafted into Christ, persecute one another?
Or where did ever the prophets or apostles, or any christians in the apostles`' days,
call the light of Christ, which enlightens every one that comes into the world,
(which is the life in the world,) and which Christ commands to believe in, of the devil,
an idol, and natural, and a new christ, etc.
Let us see where it is written in the scriptures, you that call and say,
'`the scripture is your rule, for what you do, and preach,
and speak?`' Are not all they that do not believe in the light of Christ condemned,
by the light of Christ, though they make a profession of him in the flesh?
Or are any saved but who believe in the light?
And do not they come out of condemnation that believe in the light,
and so become children of the light, and grafted into Christ,
where there is no condemnation?
Consider these things.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, this 18th of the 8th month, 1675.

[.blurb]
=== Something by way of Query to, and Expostulation with you that love and expect Earthly Honour.

Doth not Christ say, '`I receive not honour from men?`'

Now, if the King of kings, and Lord of lords, the great Prophet,
and the great and heavenly bishop and shepherd,
that sent out all his ambassadors and disciples, and bid them,
'`go into all nations and preach the King of king`'s and Lord of
lord`'s glorious gospel;`' if he did not receive honour from men,
then whether his ambassadors or apostles receive honour from men in all,
or any of those nations that they went into with his message?
For does not Christ say to the great professing Jews, and scribes, pharisees,
and chief priests, and the like, '`How can ye believe, which seek honour one of another,
and seek not the honour which comes from God only?`' Mark Christ`'s question,
and see how you can answer him in it; for Jesus Christ saith to the Jews,
which were great professors of Moses and the prophets, '`I honour my Father,
and ye do dishonour me.`' John 8:49.

And now, do not all that speak evil of his light, which is the life in him,
dishonour him in his light and life,
as the Jews did dishonour him in the days of his flesh,
though they may be as high-professors in the letter, that Christ is come, as the scribes,
(the writers,) and the pharisees,
and chief priests (the readers and expounders of the law and prophets,) were,
that he was to come?

And had not the Jews the scriptures of Moses and the prophets, the scribes,
(the writers,) pharisees, and chief priests and other priests,
(these readers and expounders of the law and prophets,) had not
these the scriptures that testified that Christ was to come,
and yet they knew not Christ, the word of God, when he was come?

Did not Christ say to the Jews, '`he that is of God heareth God`'s words; ye therefore,
hear them not, because you are not of God?`' John 8:47. Now,
might not the Jews say to Christ, as the professors will now say to us,
do not we read the law and the prophets every sabbath-day in our synagogues and temple?
and are not they the words of God?
But may not Christ answer you again, and say unto you,
that you have not the same spiritual ear as his prophets and apostles had,
to hear God`'s words; but those ears of yours are stopped like the pharisees`' scribes`',
and high priests`', and Jews`', who had outward ears and eyes, but heard not,
nor saw they Christ wanting the spiritual?
And is it not said, '`he that hath an ear,
let him hear what the spirit saith unto the churches?`'

And did not Christ say to Pilate in his examination,
'`for this cause I came into the world, to bear witness unto the truth;
every one that is of the truth, heareth my voice?`' So then,
it is not every one that speaks the words of truth, of Moses and the prophets,
Christ and the apostles; but every one that is of the truth;
he must be of the truth if he hears Christ`'s voice; for, does he not tell you plainly,
'`it is not every one that says Lord, Lord, shall enter into the kingdom;
but he that doth his will shall know his doctrine?`' Likewise, doth not Christ say,
'`every one that doth truth cometh to the light that with its deeds may be manifest
that they are wrought in God?`' And therefore they that do not the truth,
though they may talk of it from Genesis to the Revelations,
if they come not to the light,
their works cannot be manifest to them that they are wrought in God,
neither can they see how their works are wrought.
For doth not the apostle say,
'`that which makes manifest is light?`' And doth not Christ say,
'`every one that doth evil hates the light, neither cometh to the light,
least his deeds should be reproved?`' And if every one that doth evil hates the light,
do not such hate Christ, the life and the salvation, the covenant of light?
And are not these the haters of light, and the doers of evil, that say,
'`the light which is the life in Christ, is natural, and of the devil,
and the Quakers`' idol, and a new christ,`' etc.? And so,
neither come to the light themselves, nor suffer others to come to the light,
least their deeds should be reproved: wherefore it was the Jews, scribes, pharisees,
sadducees, and high-priests, that did the evil, and hated the light,
and would not come to the light, least their deeds should be reproved?
And may not this be also truly said of many in Christendom,
of the great professors of the letter of Christ and the apostles,
'`that he is come,`' as of the great professors of the letter, the Jews,
'`that he was to come?`'

Now, such as hate the light, and will not come to the light, who do evil,
because it will reprove them, and let them see their evil deeds;
how should such do the truth, and be of the truth, and hear Christ`'s voice, as he saith,
'`My sheep hear my voice?`'

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, this 20th of the 8th month, 1675.
