== To All Magistrates and People in Christendom,

[.heading-continuation-blurb]
And elsewhere to turn from the Persecuting Mind,
that destroys people`'s bodies and estates for not conforming to your religion and worship.

[.heading-continuation-blurb]
And that you may receive the Mind of Christ, as the Apostles did,
who came to save Men`'s Lives, and not to destroy them;
and to rebuke them that would destroy Men`'s Lives and estates.--By G. F.

You do not read in the old world that either Adam, Seth, Enoch,
or any of those famous fathers, that did succeed each other unto Noah,
did force or compel any to their religion or way of worshipping God; though it is said,
'`Noah was grieved with the unrighteous conversation of the old world,
who grieved God and his spirit which strove with them;`' but it doth not say,
'`it strove with them, with carnal weapons, or jails, or imprisonments.`'

And though Noah was a preacher of righteousness,
we do not read he forced or compelled any, or had any such command from God.

And after the Lord God had destroyed the old ungodly world, for their ungodliness;
who grieved him and his spirit.

So their destruction came by resisting the spirit of the Lord,
and going from it into ungodliness; and God was just in overthrowing of them,
whose spirit had striven with them long, yet he saved just Noah.

And after that he had destroyed the old world, and saved Noah and his family;
we do not read that ever either Noah, or any of them that succeeded him, into Abraham,
did force or compel any to their religion, or the worshipping of their God.

Also, Abraham, Isaac, and Jacob, that did succeed each other;
we never read that they did compel or force any to serve or worship God,
or compel them to their ways.

And after, when the children of Israel went into Egypt,
we do not read that Pharaoh did compel them to his religion, or worship,
though he did oppress them several ways.

And when the Lord sent Moses to call them out of Egypt, Pharaoh, and Jannes,
and Jambres withstood Moses and Aaron, and resisted Moses;
yet we do not read they offered to compel them to their religion, and worship,
and the Egyptian church; but they compelled them to work.

And do we not read that Abraham or Isaac, when they went into Egypt,
or Abimelech`'s country, that either Pharaoh, or Abimelech,
did compel them to conform to their religion, way, and worship.

And likewise Lot, who sojourned in Sodom,
we do not read that he compelled any to his way, or religion,
or that the Sodomites compelled him to their way;
though he was vexed with their filthy conversation.

And likewise, when the children of Israel came out of Egypt, and received the law of God,
they did not compel or force other nations to serve their God;
but other nations came to them, and when their males were circumcised,
they might eat of their sacrifices.

So look along from Moses to Joshua, and the Judges, and all the prophets, and the kings,
wherever ye can find that they did compel any nation to serve and worship their God.

Now, the Jews, when they were taken captive, we read that Nebuchadnezzar compelled them:
but the Jews distinguished what sacrifices they were to offer, and what not,
and what was called holy, and what unholy.

But you do not read that they forced other nations,
to offer a sacrifice to God upon his altar by their law, and imprison them,
and spoil their goods if they would not,
or that they forced other nations to come and worship in their temple,
or did force them to bring in their tithes, or yearly offerings;
though they took tax or tribute of them.

And we see after the kings in Maccabees, how several of the Jews suffered by the heathen,
because they would not conform to their worship:
but we do not read that the Jews compelled other nations to come to their worship,
after they had conquered them, and made them tributaries.

Neither do we read,
that ever any of the high priests or Levites did cast any into prison,
because they did not bring in their tithes into the storehouses,
but it was a curse that remained upon them, as in Malachi, if they did not.

And after Christ came and sent forth his disciples amongst the Jews,
and bid them not go in the way of the Gentiles, and told them,
when he gave them their commission, and sent them out to preach the gospel,
'`freely you have received, freely give.`'

But he said unto them, '`whatsoever they set before you, that eat;
for the workman is worthy of his meat,`' etc.

Now, they did not compel any to hear them, nor to give them meat.
And Christ did not compel any to hear him, or any to communicate to him;
who is the Lord and master.

And after Christ was risen, who gave a larger commission to his disciples,
and bid them go into all nations, and preach the gospel: Christ who had died for all men,
and was a propitiation for the sins of the whole world, after he had died and was risen,
bids them go into all nations, '`and preach the gospel to every creature.`'

Now, these apostles and ambassadors, were not to compel any to hear them,
or to give them maintenance; and if they would not hear them, nor set before them meat;
Christ gave them no such commission to cast them in prison,
and compel them to give them maintenance; but Christ said unto them,
'`he that believeth is saved, and he that doth not is condemned already.`'

And that was punishment enough to them that would not receive their message.

And they that received them, received him that sent them,
and they that received a prophet, received a prophet`'s reward.

And they that would not receive them,
they should shake off the dust of their feet as a witness against them:
and that was punishment enough.

And if any would not hear his brother, as concerning practice in the church,
he might take one or two more of the church, and if he would not hear them,
then they were to tell it to the church; and if he would not hear the church,
then he should be to them as a heathen, and as a publican;
and so was cut off from being a member of Christ`'s heavenly body,
he being the heavenly head, and that was punishment enough,
they did not cast them into prison.

And Christ told his disciples, when he did send them forth as sheep amongst wolves,
(so the nations that were settled in their own way and religions,
were like wolves to them,) Christ told his disciples,
'`they should be brought before kings and rulers, and hauled before magistrates,
and put out of their synagogues, and whipped and scourged for his names`' sake.`'

And you may consider, that these were either heathens or Jews, that were these whippers,
and scourgers, and persecutors.

But Christ bid his disciples take no thought what to say,
when they were brought before them,
for it was the spirit of the Father that spoke in them,
and it should be given unto them at that present hour.

So these disciples of Christ were not to study beforehand,
what to preach and say to the kings, rulers, and magistrates,
when they were brought before them.

Now these heathens and Jews, did whip, scourge, and imprison Christ and his disciples,
and they bore it patiently.

But where did ever Christ or his disciples, whip, scourge, or imprison any,
or the true church in the apostles`' days, for not hearing of them,
and not giving them maintenance, or spoil their goods?

But the true christians suffered the spoiling of their goods,
as the apostle speaks of to the Hebrews, that were the hearers of Christ, who told them,
'`that God had spoken to their fathers by the prophets,`' but now in these last days,
he had spoken unto us by his Son, etc.

So mark, God had spoken to us, that is, his church, by his Son, who is the head of it.

For God was in Christ reconciling the world unto himself,
who was the first speaker to Adam and Eve in paradise,
and was the speaker again to them that heard, and believed in his Son, and is now.

And now these christians that God was their speaker unto by his Son,
which suffered the spoiling of their goods joyfully, and were gazing-stocks:
now they that gazed at them, and that had spoiled their goods, were the Jews,
and the Gentiles, that followed their old professions, and their ways.

Yet these true christians that heard the Son,
we do not read that they spoiled either Jews`' or Gentiles`' goods,
or made them gazing-stocks.

For John the divine, saith in his revelations, '`that the beast compelled all,
both small and great to worship him, and to receive his mark.`'

So we do not read that Christ, or John, or the apostles compelled any, but the beast.

And he saith, '`that the beast that did compel,
received his power from the dragon;`' so did not receive it from God and Christ.

And he saith, '`all worshipped the beast,
but those who had their names written in the Lamb`'s book of life,
before the foundation of the world.`'

And therefore, let all that go under the name of christians and Jews, consider this;
and others that make a profession of God and Christ, consider these things,
and lay them to heart, and do unto all men, as you would have them do unto you;
for you would not have another man compel you to that religion,
which is contrary to yours, and therefore, do not you so unto them;
but mind the royal law of liberty, which law is holy, just, pure, good, and righteous,
and answers that of God in all, and gives liberty to the spirit of God in all.

And does not the apostle tell you,
every man must stand and fall to his own master so the apostle gave liberty here,
that every one must stand or fall to him that was their master;
for he that was servant of sin committed it, and the wages of it was death,
and he that was the servant of God unto righteousness, and the fruits unto holiness,
and their end everlasting life.

And does not the apostle say, that Christ was the author and finisher of faith,
and whatsoever was not of faith is sin?
And therefore must not all be left to their faith, which Christ is the author of?
And the mystery of faith is held in a pure conscience,
then must not their consciences be free for Christ,
and at liberty for the mystery of faith which is held in it, which faith,
Christ the spiritual and heavenly man is the author and finisher of,
who was persecuted by the Jews, and they delivered him to the Gentiles.

So, see what liberty he had amongst them, who suffered the contradictions of sinners.

And Christ was buffetted, and spit upon, and struck, and smitten, and mocked,
and a crown of thorns put on his head, and reviled and blasphemed,
yet did he not revenge himself, who had all power in heaven and in earth given unto him;
did he or his disciples whip, buffet, scourge or imprison, or crown any with thorns?
But preached and proffered unto them the crown of life, and glory.

And so, follow ye Christ and the apostles`' examples, both in life,
practice and doctrine; which is every true christian`'s duty.

And doth not the apostle say, '`that they had not power over any man`'s faith,
but Jesus Christ was the author and finisher of it,
and in it they were to have their liberty, and what was not of faith was sin?`'

So they did not say, they had power to make them believe this or that,
or to force them to a faith;
but they were to look unto Jesus the author and finisher of their faith;
and God opened Lydia`'s heart, and she believed.

So the heart must be opened by the Lord, if they be true believers,
by his light and spirit.

And the gospel which is preached to every creature, which is the power of God;
are not all to have their liberty in this gospel, which gospel was sent from,
heaven by the Holy Ghost?

So in this gospel are not all to have their liberty in the power of God?

And they were not compelled to receive it: for if they did not receive the gospel,
nor obey it, the wrath of God was revealed upon them from heaven.

And if the world did not receive the gospel,
which Christ sent his disciples into all nations to preach,
then God would judge the world by the man Christ Jesus,
according to the gospel the power of God, which had been preached to them;
and God would render vengeance in flames of fire,
unto all them that did not receive and obey the gospel?
And that was punishment enough.

And you may read in the Revelations, what John the divine tells you,
what became of the dragon, that gave power to the beast, that compelled to worship,
and the whore that drank the blood of the saints, and made war with them,
doth not he tell you, '`that they shall be cast into the lake of fire,
that burns with brimstone`', and that the whore`'s flesh shall be burnt? Rev. 13:4.
xvii.
6.

And doth not Christ tell you, that he is the seedsman,
and '`after the good seed was sown, the enemy sowed his tares,
and they that had that sight as to discern the tares from the wheat,
and saw both come up, went to the Lord,
and would have had a license from him to go and pluck up the tares,
but the Lord`'s answer was no, lest they plucked up the wheat also,
but let them both grow together till the harvest
and the harvest is the end of the world:`' and then,
saith Christ, '`I will send my angels, who shall gather the wheat into the garner,
and the tares into bundles, and cast them into the fire to be burnt.`'

So you may see Christ gave no commission to men, to gather the wheat or the tares,
but it was the angels`' work to gather the wheat into the garner,
and the tares into bundles for the fire.

And therefore, they that go to gather either, have no commission from Christ;
for he gave them a caution, '`lest ye also gather the wheat with the tares,
and lest their zeal should blind them.`'

So men are to mind their duty, which is to love mercy and to do justly,
and to walk humbly with God: and not to take the angels`' work upon them,
and go to reaping before the time, which is the end of the world.

And likewise when Christ sent forth some of his disciples to prepare for him,
and some would not receive them; Lord,
(said they,) '`shall we command fire to come down from heaven to consume them,
as Elias the prophet did?`'

Christ turned about, and rebuked his disciples, and told them,
they did not know of what spirit they were of: and told them,
'`he did not come to destroy men`'s lives, but to save them.`'

So ye may see here, the disciples of Christ had a zeal,
and would have had fire to have come down from heaven,
to have consumed them that would not receive Christ:
these disciples would have been plucking up tares, but Christ rebuked them,
and stopped them; and told them, '`they did not know of what spirit they were of,
that would have commanded fire to come down from heaven,
to have consumed them that would not receive him.`'

And now do all you that have persecuted, imprisoned,
and spoiled the goods of the people of God in Christendom,
because they would not conform to your religion, know what spirit you are of yourselves?
And they that do not know what spirit they are of themselves, must be in the blind zeal,
and will be doing that which Christ rebukes;
and they that do not know what spirit they are of themselves,
are not like to watch for people`'s souls.

And people are not like to trust their bodies,
much less their souls into the hand of such,
that know not what spirit they are of themselves.

And therefore, consider what spirit ye and they have been of, that have persecuted,
put to death, spoiled the goods,
and imprisoned such as would not conform to your way and worship;
and yet call yourselves christians, and ministers of Christ.

I say, Christ who rebuked his disciples,
who would have had fire to come down from heaven, upon them that would not receive him,
will rebuke you also.

And as Christ told his disciples,
'`they did not know what spirit they were of;`' neither
do ye know what spirit ye have been of:
and +++[+++mark,]
there were more in the apostles`' desire,
to have fire come down from heaven to consume them that would not receive the substance,
the Lord of glory, than for you to force, imprison, persecute, banish, or put to death,
or spoil the goods of such as will not receive your way, and worship, and religion,
that you have set up.
So, how can you but expect a greater rebuke to come upon you,
that persecute and destroy such as will not receive your forms of religion and worship,
when they were rebuked that would have fire to come
down to destroy them that would not receive Christ,
the substance and the life?

For they were told by Christ,
'`they did not know what spirit they were of,`' and
that '`he came not to destroy men`'s lives,
but to save them.`'

And therefore,
consider how many men`'s lives have been destroyed since the apostles`' days,
by those that profess themselves christians in Christendom,
because they would not receive their religions and ways; they that have done so,
have not known of what spirit they are of, nor followed the mind of Christ,
to save men`'s lives; and do not know what spirit they are of,
that would destroy men`'s lives.

So weigh and consider this, all people in the whole world, that profess God and Christ,
now in this the day of your visitation.

G+++.+++ F.
