== The People of God, in Scorn Called Quakers, / Their Love to All Mankind Asserted

[.heading-continuation-blurb]
For as God`'s love through Christ hath been shed abroad in our hearts,
we cannot but in the same love desire the eternal good,
and the Salvation of all mankind, and would have them repent,
and turn to Jesus Christ, whom God hath given in his love to be their Way,
Leader and Captain of their Salvation, and hath tasted death for every man,
and hath bought them with a price, therefore,
that they all might serve and live to him, and glorify God with their bodies,
souls and spirits, which are the Lord`'s that he hath made,
and Christ`'s, who hath redeemed and bought them.--By G. F.

It hath often been said, '`that the people of God in scorn called Quakers,
love none but themselves.`'

To this I answer, such are mistaken in their judgment,
and I fear it is their own conditions, for we love God that created all things,
and his Son, by whom all things were made, who was conceived by the Holy Ghost,
born of a virgin, who made a good confession before Pontius Pilate,
who was crucified without the gates at Jerusalem, and rose the third day,
and sits at the right hand of God;
by whom God will judge the world according to the gospel, that is,
according to the invisible power which is preached to every creature.

Secondly.
We love all men and women, simply as they are men and women,
and as they are God`'s workmanship,
and so as brethren and children of Adam and Eve by generation.

Thirdly.
We love them all as they come to be the sons of God by adoption, and can say,
Abba Father, in the heavenly brotherly fellowship,
and we are commanded to do good unto all, especially to the household of faith:
for Christ commands us to love one another, and not so only, but to love enemies,
and it is a mark by which his were known to be his disciples,
viz. by their loving each other.

And we are to pray for enemies, and our persecutors,
by the command of Christ and the apostles.

'`For God hath made of one blood all mankind to dwell
upon the face of the earth.`' Acts 17:26.

'`And the earth is the Lord`'s and the fulness thereof.`'

And the Lord saith in Job xxxi.
'`all under the heavens is mine,`' who hath created all to his glory;
and the Lord saith unto Ezekiel, '`say unto them, as I live saith the Lord God;
I desire not the death of the wicked, but that the wicked turn from his way and live;
turn you, turn you, from your evil ways, for why will you die, oh,
ye house of Israel,`' saith the Lord; here ye may see God`'s mind,
and his love to people, which all his people is to be in,
who would have people turn from their wicked ways and live. Ezek. 33:11.

And further, the Lord saith, '`I desire not the death of him that dieth, cause therefore,
one another to turn and live;`' see here the love of God to mankind,
who would have them to turn and live. Ezek. 18:23.
And so he would have all that is called Christendom,
to turn to the new covenant and live, which is our desire also.

And further he saith, '`have I any desire that the wicked should die, saith the Lord God?
Or shall he not live,
if he turn from his ways?`' Here ye may see what the Lord`'s desire is,
and his goodness to wicked mankind, in the same chapter.
And in Isa. 1:18. '`come now and let us reason together,
(saith the Lord,) though your sins were as crimson, they shall be made white as snow,
though they were as red as scarlet, they shall be as wool,
if you be willing and obedient, ye shall at the good things of the land,
but if you refuse and be rebellious, ye shall be devoured with the sword;
for the mouth of the Lord hath spoken it:`' Here
you may see the love of God to man and woman,
who would reason with man, and have him to obey and consent,
and shows him the good in obeying, and shows him the judgments in disobeying. Isa. 19:20.

And in Isa. 45:22. '`look unto me, and ye shall be saved, saith the Lord,
all ye ends of the earth, for I am God,
and there is no other,`' So all ye ends of the earth must look unto the Lord for salvation.

And Isaiah saith, '`cease you from man whose breath is in his nostrils,
for wherein is he to be accounted of?`' Isa. 2:22. And therefore,
all ye ends of the earth must look unto the Lord for salvation,
these are the words of the Lord to the ends of the earth, and to all people upon it.

And thus saith the Lord, '`I will give thee for a light to the Gentiles,
that thou mayest be my salvation unto the end of
the world,`' (speaking of Christ,) as in Isa. 49:6.

Who is the salvation to the end of the world?
Christ Jesus, the covenant of light, which prophecy of Isaiah was fulfilled in Christ,
of whom it is said in John i. '`in him was life, and the life was the light of men,
and the light shined in the darkness, and the darkness comprehended it not,
and John said he was not that light, but was sent to bear witness of the light,
and that was the true light which lighteth every man that cometh into the world,
he was in the world, and the world was made by him,
and the world knew him not,`' (to wit,) Christ the light,
that lighteth every man that cometh into the world,
and '`grace and truth cometh by Jesus Christ, as the law came by Moses,
for the grace of God which bringeth salvation unto all men hath appeared,`' +++[+++mark,]
unto all men hath appeared this grace of God which bringeth salvation.

Here is the general love of God to mankind, which teacheth us to live soberly,
etc. saith the apostle to the true christians,
and that we should deny ungodliness and worldly lusts, and live soberly and righteously,
and godly in this present world.

So this grace of God, which hath appeared unto all men, was their teacher, how to live,
and walk to God and man, and what to deny; I say, how to live and walk to God,
which brought their salvation,
and to look for the blessed hope and the appearing of the glory of the mighty God,
and our Saviour Jesus Christ,
'`who gave himself for us that he might redeem us from all iniquity,
and purify unto himself a peculiar people,
zealous of good works.`' So here is the love of God in Christ unto all mankind,
Titus 2:14, to the end, which we are witnesses of, and we desire all might obey it,
and not turn from it into wantonness.

And John saith of Christ, '`behold the Lamb of God,
that takes away the sins of the world.`' So all the
world is to look unto the Lamb of God,
which takes away their sins, as you may see in John ii.
and not to plead for sin to the grave, but for the Lamb that takes it away.

'`For God so loved the world, that he gave his only begotten Son,
that whosoever believeth in him should not perish,
but have everlasting life:`' so here God so loved the world,
that he gave his only begotten Son into the world,
that he that believeth in the Son hath everlasting life,
and he that believeth not in the Son of God, shall not have life,
but the wrath of God abideth on him:
now here is God`'s love to be seen whether men believe and obey, or not,
and the wrath of God abideth upon him that doth not believe, as in John iii.

And Jesus Christ saith, '`while ye have the light, believe in the light,
for I am come a light into the world,
that whosoever believes in me should not abide in darkness,
but have the light of life:`' now here Christ teacheth how men should believe,
and what to believe in, to wit, the light, as in John xii.
which we do, and would have all people to believe in, '`Christ the light.`'

And again, Jesus saith, '`I am the light of the world,
he that followeth me shall not walk in darkness,
but shall have the light of life.`' So he who is the heavenly man, the Son of God,
is the light of the world, and enlighteneth every man that comes into the world,
and bids them believe in the light, whom God hath given for a light,
and to be his salvation to the ends of the earth.
And when Christ said, he was the light of the world, the pharisees were offended at him;
as many fair sayers, and bad doers are now offended at the believers in the light,
and such as are become the children of it, that bear witness to it. John 8:12.

And in Luke 2:28, to 31. when Simeon took Jesus in his arms, and said, '`now, Lord,
let thy servant depart in peace, for mine eyes have seen thy salvation,
which thou preparest before the face of all people, (mark, all people;
here is no sect,) a light to be revealed to the Gentiles, and the glory of thy people,
Israel,`' (mark,) a light to be revealed to the Gentiles.

Christ is revealed to the Gentiles, who is their light to enlighten them.
Luke ii.
By which light people see their sins, and by which light people see their Saviour,
Christ, that saves them from their sins, and died for their sins,
and rose again for their justification.

And see,
Christ`'s own words in John 6:51. '`I am the living bread which came down from heaven,
if any man eat this bread, he shall live forever; and the bread that I will give,
is my flesh, which I will give for the life of the world.`' Mark,
his flesh for the life of the world; and they must eat it, if they will live forever;
and here is the love of God in Christ Jesus to the world;
who gives his flesh for the life of the world,
and they must eat him who is the bread of life that came down from heaven, if they live:
so it is not only talking, but it is feeding and eating, (John vi.) that is required,
if you will have life.

Now, Christ doth not say, he would give his flesh for the life of some of the world;
but in Luke 3:6. saith,
'`all flesh shall see the salvation of God;`' and they that see their salvation,
Christ Jesus, they must come to the light that comes from him, which gives the knowledge;
but if they hate this light, it does condemn them, as in John iii.

And in Rom. 5:6. '`for (when we were yet without
strength,) in due time Christ died for the ungodly;
for when we were enemies we were reconciled to God by the death of his
Son.`' Rom. 5:10. And therefore people should die with Christ to sin,
and have their old man crucified with him, that their old man might be destroyed;
that henceforth they should not serve sin, and remain enemies.
Here you may see Christ died for the ungodly, and for enemies,
and not that they should live in ungodliness, but live to him that died for them:
'`for Christ died, and rose again,
and ascended that he might be Lord both of the dead and of the living:`' therefore,
none are to live to themselves, but unto the Lord;
and this should be all true christian`'s living and dying in the Lord. Rom. 14.

'`For as in Adam all died, even so in Christ all be made alive.`' 1 Cor 15:22.
Here is God`'s love to all mankind, who are made alive by Christ Jesus;
for as it is written, the first Adam was made a living soul,
the second Adam a quickening spirit; the first Adam was of the earth earthly,
the second Adam the Lord from heaven.`'

And the apostle saith, in 2 Cor. 5:14-15.
'`for '`the love of Christ constrains us because we thus judge,
that if one died for all, then were all dead, and he died for all, (to wit, Christ,
saith the apostle,) that they which live should not henceforth live unto themselves,
+++[+++mark, not live unto themselves,]
but live unto him (to wit, Christ,) who died for them,
and rose again:`' here is the love of God to mankind in Christ Jesus,
which we bear witness to, who died for all, for sinners and enemies,
that henceforth they should not live unto themselves, but unto Christ,
that died for them.

And in Col. 1:23, to the end, the apostle saith to the saints,
'`if ye continue grounded and established in faith,
and not be moved away from the hope of the gospel, whereof ye have heard,
which hath been preached to every creature under heaven.`' Mark 16:15.

And the apostle saith,
'`the gospel of Christ is the power of God unto salvation to every one that believeth,
to the Jew first, and also to the Grecian,`' as in Rom. 1:16. So mark,
this gospel is preached to every creature under heaven,
this joyful news and glad tidings: so here the apostle makes no sects;
here is God`'s love in the gospel of Christ Jesus to every creature under heaven,
and the apostles preach Christ Jesus and his gospel, '`admonishing every man,
and teaching every man, +++[+++mark, every man,]
in all wisdom,
that we may present every man perfect in Christ Jesus;`'
and this we desire all people may come to witness with us.

Now all the imperfection is out of Christ Jesus, in the devil, and Adam in the fall;
and the perfection is in Christ Jesus, that never fell:
here was their general ministry in the love of God in Christ Jesus, and so is ours,
and to present all perfect in Christ.

For, '`Christ also hath once suffered for sins, the just for the unjust,
that he might bring us unto God,`' +++[+++mark, that he might bring us unto God,]
and '`Christ was put to death concerning the flesh,
(not as he was God,) but was quickened in the spirit.`' 1 Pet.
3:18. '`And he is the reconciliation for our sins,
(to wit, Christ,) and not for our sins only,
but for the sins of the whole world;`' +++[+++mark, for the sins of the whole world,]
'`and he that saith he abideth in Christ,
ought even so to walk as he walketh.`' 1 John 2:2. For he hath left us an example,
not only to talk of him, but to walk after him, and follow him.

And the apostle saith,
'`therefore we labour and suffer reproach because we trust in the living God,
which is the Saviour of all men, especially of those that believe; these things,
(saith he to Timothy,) command and teach,`' 1 Tim.
4:10-11. which we do by the same power and spirit.

And the apostle saith, in Heb. 2:9. '`but we see Jesus crowned with glory and honour,
which was made a little lower than the angels, for the sufferings of death,
that he by God`'s grace should taste death for every man,
that he might destroy through death him that hath the power of death,
that is the devil.`' Heb. 2:14. So here is the love of God in giving his Son,
who tasted death for all men, who said, '`he had power to lay down his life;
and power to take it up again.`' And they that say
Christ did not taste death for every man,
are the sect-makers and sectaries amongst people, and are contrary to the apostles`',
Christ`'s and his prophets`' doctrine.

And in 1 Pet. 2:17. Peter saith to the christians, '`honour all men,
love the brotherhood, fear God,
honour the king:`' for God hath honoured all men in giving his Son, a light,
and to be his salvation to the ends of the earth, and to enlighten all men:
and his grace hath appeared to all men, which bringeth salvation,
and he hath died for all men, and tasted death for all men;
and God desires not the death of any man, but would have them to turn to him:
if God hath so honoured all men, in giving his Son to be a Mediator, and a Redeemer,
and purchaser with his blood of men and women out of sin and evil,
we are to honour all men as men, because they are God`'s creation and workmanship,
who made them in his image, though they lost it;
and all they that are renewed into it again, are renewed by Jesus Christ;
so we are to have all men in esteem, and honour all men,
and not to curse nor hate any man; and we are to love the brotherhood,
such as are disciples and learners of Christ Jesus, and followers of him,
who are in the brotherly fellowship, which is in the Holy Ghost,
which the apostles were in; and the fellowship is in the spirit, and the unity,
which is the bond of peace, yea, even the bond of the Prince of princes`' peace,
which is the duty of every true christian to keep, as also to fear God,
and honour the king; now none can honour the king, but who fear God;
they that fear God must depart from sin and evil;
for they that do not depart from sin and evil, do not fear God,
which doth keep their hearts clean, and is the beginning of God`'s wisdom from above;
and they that do not depart from evil, but live in it, dishonour both God and the king,
and their own bodies, which are God`'s workmanship, and so dishonour God their Creator,
and Christ their Saviour and Redeemer.

And the apostle saith, in 1 Tim. 2:12. '`I exhort, therefore, that first of all,
supplications, prayers, intercessions and giving of thanks be made for all men,`' +++[+++mark,
for all men.]
So here in their prayers, and supplications and intercessions they are to make no sect,
but that all men must be prayed for; and prayers, supplications, and intercessions,
and thanks must be made for kings and for all that are in authority; +++[+++mark,
for all that be in authority:]
again, here is no sect made, but an universal, general prayer,
'`that we may lead a quiet and a peaceable life under
them in all godliness and honesty;`' +++[+++mark,
in all godliness and honesty;]
for this is good and acceptable in the sight of God our Saviour,
who wills '`that all men should be saved,
and come to the knowledge of the truth,`' and that is by the light of Christ Jesus,
that shines in the heart; mark, this is God`'s will and mind,
that '`all men should be saved, and come to the knowledge of the truth;
for there is one God, and one Mediator betwixt God and man,
which is the man Christ Jesus;`' +++[+++mark, the man Christ Jesus,]
'`who gave a ransom for all men, to be testified in due time;`' +++[+++mark, for all men,
to be testified in due time:]
again, here is no sect made, nor any excluded,
therefore as he gave himself a ransom for all men; and the will of God is,
that all men should be saved, and come to the knowledge of the truth; and therefore,
prayers, and supplications, and intercessions,
and giving of thanks must be made for all men, and for kings,
and all that be in authority, that we may lead.
a quiet and a peaceable life under them in all godliness and honesty, Amen.

'`And they that have the mind of Christ do this,
and know the common faith and the common salvation.`' Jude iii.
And this common faith and common salvation the saints were earnestly to contend for,
which Christ their Saviour is the author of,
which we do contend for this day against all opposers.

And all that have the mind of Christ, own this; for the apostle said,
'`we have the mind of Christ;`' we the church, disciples and true christians;
and also the apostle saith,
'`let the same mind be in you as was in Christ Jesus;`'
and then the same mind will own his words and doctrine,
that he spake, and as the apostles did and spake. Phil. 2:5.
1 Cor. 2:16.

But all you that say, Christ hath not tasted death for every man,
and hath not given himself a ransom for all men; and say,
that he hath not enlightened every man that cometh into the world,
the heavenly man with his heavenly light,
the spiritual man with his divine and spiritual light;
and that his grace hath not appeared to all men, which brings salvation,
which is the saints`' teacher; and that Christ hath not died for all men,
and is not a propitiation for the sins of the whole world, but for the saints only,
or the world of believers, as you call them; you are the makers of sects and schisms,
and in your vain thoughts imagine Christ died only for your own sects,
and that God hath ordained of old the greatest part of mankind for hell;
you are of another mind than the apostles, who said, '`Christ died for all,
and tasted death for every man, and would have all men to be saved,
and come to the knowledge of the truth,`' and therefore,
supplications and prayers must be made for all men;
and you must love enemies as well as friends;
and the Lord desires not the death of the sinner, but rather that he might turn and live;
and Christ is the Saviour of all men, especially of them that believe:
you are of another mind and spirit than the prophets, and Christ,
and the apostles were of, that say, Christ did not die for all men,
and tasted death for every man, and gave himself a ransom for all men:
and God would have all men to be saved, and come to the knowledge of the truth;
and the manifestation of the spirit of God is given to every man to profit withal,
(1 Cor. 12:7) mark, every man; and you that are against this, are the sect-makers,
and have not the mind of the apostle;
and this doctrine of Christ and the apostles we preach and teach,
and bear witness unto against all the opposers and sect-makers whatsoever.

And the apostle saith, '`but he that understandeth according to sobriety,
as God hath dealt to every man the measure of faith;`' +++[+++mark,
as God hath dealt to every man the measure of faith,]
so he is the dealer; for it is his gift; for faith is the gift of God,
which Christ is the author of, and not man, by which every man should walk,
by that faith which God hath dealt to him by Christ Jesus, the author and finisher. Rom. 12:3.
'`For of him (to wit, God,) and through him, and for him are all things;
to him he glory forever, amen.`' Rom.
xi.

So your directory and church-faith, as you call it, may lie and mould,
for we understand according to sobriety,
that as God hath dealt to every man the measure of faith, his gift, so he is to walk by,
in which he pleases God through Christ Jesus, whom all christians must look unto, Jesus,
who is the author of their faith, and finisher of it, who is the author of ours,
glory to God forever: and the wise man`'s eye is in his head, Christ Jesus,
who is the head of all, who bruises the serpent`'s head, that led men from God,
and hath been between men and God; and he that doth this, leads man again to God (to wit,
Christ,) who is the true baptizer, who baptizes with fire and with the Holy Ghost,
whose fan is in his hand, and he will cleanse his floor, the floor of your hearts,
and will gather his wheat into his garner,
but will burn up the chaff with unquenchable fire; and they that know this baptizer,
(to wit, Christ,) are the true christians, and will never plead for the chaff;
their body of death and sin to the grave;
for when Christ sets fire in your hearts and minds,
that never shall be quenched till the chaff is burnt up;
such will not plead for the chaff, but for Christ and his baptism, which we own,
and would have all people come to.
For in the time of the law things were to pass through the fire and water,
to be made clean; so you must pass through Christ`'s fire and water,
which purifies and washes, before you will be clean to enter into his holy kingdom,
and know his baptism,
as in Luke 3:16-17. For Simon Magus may go into the outward water,
and yet not come to Christ`'s baptism, and think he can buy the gift of God for money,
which was judged by the apostle, and by all that be in the same spirit.

And this is the one baptism, '`for by one spirit we,
(the true church,) are all baptized into one body, whether we be Jews or Gentiles,
bond or free,
and have been all made to drink into one spirit:`'
and for want of this spirit`'s baptizing of you,
and you drinking into it, there are so many bodies and sects in Christendom,
and so many baptisms and ways, and so do not drink all into one spirit,
in which the unity and fellowship and the bond of the Prince of princes`' peace is,
which we say all true christians are bound to keep,
and then they will seek the good of all men, and the peace of all men;
let them be of several sects formerly,
yet by one spirit they are all baptized into one body,
as they come to the spirit then they drink into one spirit,
then here is fellowship in the one spirit. 1 Cor. 12:13.

So all christians are to endeavour to keep the unity of the spirit in the bond of peace.

Here is one body, and one spirit, even as ye are called into one hope of your vocation;
'`there is one Lord, one faith, one baptism, and one God, and one Father of all,
which is above all, and through all, +++[+++mark,]
and in you all,`' Phil.
iv. know him there searching your hearts, and find him there trying your reins;
incline your ears, and give ear to him there,
who will render to every one of you according to
your words and works whether they be good or evil.

And therefore, quench not, nor vex, nor grieve his good spirit,
nor rebel against the good spirit which God hath given to you to instruct you,
and to profit withal, Neh.
ix. nor turn the grace of God into wantonness, which would teach you,
and bring your salvation; neither walk despitefully against the spirit of grace;
neither despise prophecy, which is an office in the church;
neither hate the light of Christ,
(lest it be your condemnation,) which you should believe in, and become children of.

And in 1 Cor. 8:6. '`unto us, (to wit, the christians,) there is but one God,
which is the Father, of whom are all things, +++[+++mark, all things,]
and we in him, +++[+++mark in him,]
(to wit, the Father, of whom are all things,) and one Lord Jesus Christ,
by whom are all things, +++[+++mark by whom are all things,]
and we by him, (to wit,
by Christ,) of whom is named the whole family in heaven and earth,
and so that Christ may dwell in your hearts by faith,
and that you may be strengthened by his spirit in your inward man.`' Ephes.
iii.

And do not resist the Holy Ghost, as the outside professing Jews did,
and the stiff-necked and uncircumcised in hearts and ears,
as it is to be feared too many of those called christians do now, Acts 7:51.
for they that do resist the Holy Ghost,
resist that in which they should have fellowship, and pray in;
and they that resist the Holy Ghost,
resist that which Christ sends to lead the saints into all truth by,
and shews them things to come, and '`takes of mine,
(says Christ,) and gives unto you;`' and they that resist this, resist their leader,
and their minister, and their reprover; and this '`Comforter, the spirit of truth,
shall reprove the world of sin, and of their righteousness,`' which is not Christ`'s,
and of their judgment, which is not of the Holy Ghost, John 14:16-17.
and therefore must the world leave their sin,
righteousness and judgment, and turn at the reproof of the Holy Ghost,
which Christ prayed unto the Father that he would send,
and should abide with his disciples forever; and he did, and hath sent him,
the Holy Ghost, the Comforter, that leads into all truth,
in which Holy Ghost is our fellowship, which fellowship we would have all,
that are called christians, to come into with us.

And see what the apostles saith to the Colossians, he tells them, Col. 2:10-11.
'`they were complete in Christ,
the head of all principalities and powers,
in whom also ye are circumcised with the circumcision made without hands,
by putting off the sinful body of the flesh,
by the circumcision of Christ;`' which we are witnesses of, and would have all come to,
which they must do, before they go to the grave, or never.

Now this was so amongst the true christians;
but all you that plead for the sinful body of the flesh to the grave,
deny the circumcision of Christ.

And further, the apostle saith, '`seeing ye have put off the old man with his works,
and have put on the new man,
which is renewed in knowledge after the image of him (to wit, God,) that created him;
where is neither Greek, nor Jew, circumcision, or uncircumcision, Barbarian, Scythian,
bond, nor free, but Christ is all, and in all.`' Col. 3:10-9. Mark this,
you called christians; for this is a high state.

So all they that plead for the old man with his works to the grave,
are of another mind and spirit than the apostles were in, and preach another doctrine,
and there you may see these true christians had put
off the old man before they went to the grave,
and put on the new,
and were renewed in knowledge after the image of God that created them;
and this work must all the true christians know whilst they be upon the earth,
which we witness, and desire all might come to know and do the same.

And the apostle James in his general epistle to the church, speaking of the tongue,
that unruly member, which is full of deadly poison, '`therewith bless we God,
even the Father, therewith curse we men, which are made after the similitude of God.`'

And now all Christendom consider this, if you bless God,
and curse men that are made after the similitude of God,
or curse his works and his workmanship,
and curse that which he hath made and created after his own similitude;
and therefore that evil tongue and unruly member, that is full of poison,
you must have power over and bridle, else your religion is vain; for it must not do so,
to curse the Creator`'s workmanship after his own image;
for that proceeds from the wisdom below, and not from that which is above,
as you may see in James iii.
and therefore you must love, and honour, and pray for all men, and not curse them;
seeing Christ hath tasted death for all men, therefore, bless and curse not,
and obey his doctrine who is the Saviour of all men, and especially of them that believe,
who would have all men to be saved, and to come to the knowledge of the truth, to wit,
Christ, who is the way, the truth, and the life.

And as Peter saith, '`I perceive God is no respecter of persons, but in every nation,
he that feareth God and worketh righteousness is accepted of him.`' Acts 10:34-35.
So God being no respecter of persons,
but accepts all that fear him and work righteousness; therefore,
all people are to fear God, and depart from evil, and from all unrighteousness,
if they be accepted of God; and their not fearing God, and not working righteousness,
is that which maketh them unacceptable with him.

And Peter further saith, '`ye know the word that God hath sent to the children of Israel,
preaching peace by Jesus Christ, who is Lord of all;`' +++[+++mark, of all:]
so there is no peace with God, but by Jesus Christ.

And, '`the gospel,
which is preached to every creature under heaven;`'
and Christ`'s ministers were to go into all nations,
to preach the gospel of Christ; then the gospel was preached to the stock of Ham,
the stock of Ishmael, and the stock of Esau.
For, '`Christ died for all men,
and tasted death for every man;`' and here is God`'s love, in sending his Son,
that died for all men; and God`'s and Christ`'s love,
in sending his ministers to preach the gospel to all men,
that they might know the heavenly riches,
and their inheritance of the same by Christ Jesus;
for God`'s heavenly sun hath shined upon the just and the unjust, for their eternal good,
as the natural Son doth for their outward good; and doth enlighten all,
that all might believe in the light, and through it receive God`'s love and favour,
and they that do not are condemned by it;
and the wrath of God abides upon them that reject his love: so we,
and all that have the mind of Christ,
our love is unto all men for their outward and eternal good,
though we are hated by them for it, as their forefathers hated the prophets, Christ,
and the apostles for their love and good will towards them.

And are not a great part in Christendom saying with Pilate, that crucified Christ,
'`what is truth?`' John 18:38. Though they are bred up at schools,
and think themselves as wise men as Pilate was,
who understood the Jews`' law and the Romans`', and had his Latin, Greek, and Hebrew,
to set over Christ when he was crucified; but Christ is risen a-top of it,
and the truth is Christ, that doth enlighten you,
and you must find it in your inward parts: and Christ saith, '`I am the way, the truth,
and the life;`' but the wise professing Jews would not receive him,
nor believe in him then, though they had the scriptures;
and they confessed he was to come, as the professors now, who profess he is come,
yet will not believe in the light, but with literal learned Pilate say,
'`what is truth?`' Though Christ saith, '`I am the way, the truth, and the life,
and no man comes to the Father but by me;`' and yet people that call themselves christians,
will say, '`there are so many sects in the world, we know not which to follow;
oh! that we did know the truth:`' to which we say, have you been learning all this while,
and do not yet know the truth?
Indeed there are teachers that have the form of godliness, and deny the power,
that are always teaching, that they may be always paying of them,
and leading people that are never able to come to the knowledge of the truth, (to wit,
Christ, the way, the truth, and the life.) For, '`to know God and Jesus Christ,
is eternal life;`' but to talk of God and Jesus Christ is not eternal life;
and that which gives people the knowledge of the glory of God in the face of Jesus Christ,
is the light that shines in their hearts, which Christ hath enlightened them withal;
and here is the love of God in Christ Jesus to them all, to enlighten them all;
and here is our love to all mankind,
in desiring and inviting them to turn from the darkness to the light,
and to believe in the light, that they may become children of the light,
and so to look unto Jesus Christ, the author and finisher of their faith,
who hath died for their sins, and is risen again for their justification,
and sitteth at the right hand of God; for by him, to wit, Christ,
all things in heaven and in earth are reconciled in one;
and God was in Christ reconciling the world unto himself:
and so we cannot but in love beseech all to receive Christ Jesus, the light, the life,
and truth, that by him you may be reconciled unto God, who will lead you out of old Adam,
and destroy the devil and his works, who hath separated you from God;
and as every one hath received Christ Jesus, so walk in him,
who is the new and living way, who is over all the old and dead ways,
who is the rock of ages, and the foundation of many generations,
and is our rock and our foundation in this our age and generation,
who bruises the serpent`'s head, who is the first and last,
who is the love of God to mankind; glory to God forever.

G+++.+++ F.
