[.style-blurb, short="Concerning Revelation, Prophecy, Measure, and Rule"]
== Concerning Revelation, Prophecy, Measure, and Rule; and the Inspiration and Sufficiency of the Spirit.

[.heading-continuation-blurb]
So the letter-professing and learned Christians and Jews must do God`'s Will,
if they will know Christ`'s Doctrine;
and that must be done by the same Spirit as the Apostles were in,
that through it they may mortify the deeds of the flesh,
and take up the Cross daily, and follow Christ (and deny themselves,)
who reveals the Father to them,
if they will know Him or his Doctrine, that did the Will of God.--By G. F.

Now unto all you that cry so much against revelation,
that go under the name of christians,
hear what Christ Jesus saith in Matt. 11:27. and in Luke 10:22.
'`all things are given unto me of my Father:
no man knoweth the Son, but the Father; neither knoweth any man the Father but the Son,
and he to whom the Son will reveal him.`'

Now here it is clear by Christ`'s own words, you that deny revelation,
know not the Son nor the Father; for '`no man knoweth the Son but the Father, +++[+++mark,
no man,]
neither knoweth any man the Father, but the Son,
and he to whom the Son revealeth him.`' So it is clear the
Son must reveal himself and his Father to people,
if they know them, and they are not known but by revelation;
and they that deny revelation, deny that which reveals both Son and Father.

And therefore, take heed you wicked ones, that deny revelation;
for it is said in Job 20:27. '`the heaven shall reveal his iniquity,
and the earth shall rise up against him.`' And therefore, take heed,
lest the heaven reveal your iniquity, and the earth rise up against you,
that deny revelation.

And it is said in Jer. 33:6. '`behold, saith the Lord, I will give it health,
(to wit, Jerusalem,) and amendment, and I will cure them,
and will reveal unto them the abundance of peace and truth.`' Now this amendment,
and this health, and this abundance of peace and truth hath the Lord revealed,
and given unto us, blessed be his name forever;
and you will want it that deny revelation.

And you that deny God`'s revelation, deprive yourselves of this peace and truth,
amendment and health,
though you have the form of godliness and deny the power and spirit that should reveal.

And Nebuchadnezzar, he did not deny revelation, though a heathen;
but acknowledges Daniel`'s revelation, and acknowledged the God of truth,
and that He was the revealer of secrets; and are not you darker than Nebuchadnezzar,
that profess yourselves christians, and you deny revelations nowadays,
and are them that would limit the Son and God, and say,
that '`there is no revelation to be looked for nowadays;`'
then there is no looking for the knowledge of God nowadays:
for there is no knowledge of him but as the Son reveals him,
who is the same today as yesterday, and so forever; and is known by revelation now,
as formerly, which we witness.

And the apostle Paul, did not preach Christ until the Son was revealed in him, Gal. 1:15-16.
where he saith,
'`it pleased God to separate him from his mother`'s womb, and call him by his grace,
to reveal his Son in him, that he might preach him.`' So all you that deny revelation,
you preach before the Son of God be revealed in you to preach him.
And so, '`he that hath not the Son, hath not life,`' saith the apostle John.
And '`know you not how that Jesus Christ is in you, except ye be reprobates,`' says Paul;
and bids them '`examine themselves,`' in 2 Cor.
xiii.
and this revelation we witness.

And whereas, you may object and say, '`secret things belong to the Lord,
but the things revealed belong to us,`' etc.

But you must see what thing is revealed to you, and to your children;
for was not the law revealed to Moses?
And did not the Jews by the spirit of God understand it, and knew it so?
And the Lord revealed himself to David, 2 Sam. 7:27.
and the Lord revealed himself to Samuel,
as in 1 Sam. 3:21. and God is the same, and changes not.

And in Isa. 40:5. he saith, '`the glory of the Lord shall be revealed,
and all flesh shall see it together, the mouth of the Lord hath spoken it.`' +++[+++Mark,]
all flesh shall see this revelation.
And you that deny revelation, how can you see this glory of the Lord without revelation,
which the mouth of the Lord hath spoken?
+++[+++mark,]
'`The glory of the Lord shall be revealed;`' it was to come:
and they that see this glory of the Lord, must know it by revelation,
as the Lord hath spoken, and which we witness.

And in Isa. 53:1. '`Who hath believed our report?
And to whom is the arm of the Lord revealed?`' Now, can any know the arm of the Lord,
and believe that report of him, but as it is revealed; and as it is revealed,
they will know the powerful arm of the Lord, which we witness.

And in John 12:38. where was the fulfilling of the prophet Isaiah`'s prophecy,
who said, '`Lord who hath believed our report?`' Therefore, it is said,
'`he hath blinded their eyes, and hardened their hearts.`' And therefore,
are not your hearts hardened, and your eyes blinded,
that deny the revelation of the Son of God?
And your belief is but like the pharisees in the letter,
that stand against the revelation of the Son of God, who is the foundation,
and the rock of this age, as of the former ages.

And in Isa. 56:1. '`thus saith the Lord, keep ye judgment, and do justice,
for my salvation is at hand to come, and my righteousness to be revealed;`' +++[+++mark,
to be revealed.]
Now, can any know God`'s salvation, or his righteousness,
but by the revelation of the Son?
(Christ saith, '`they cannot,`') and they that do know salvation,
and the righteousness revealed must keep judgment and do justice; and they that do not,
will deny revelation, and true judgment and justice.

And Christ saith,
in Matt. 10:26. '`there is nothing covered that shall not be revealed,
nor hid that shall not be known.`' Now,
are not all things covered and hidden unto you until they be revealed?
+++[+++mark, revealed.]
And how do you know any thing, but by revelation?
For, are not all things covered and hidden from you, before they are revealed?
And herein we witness Christ hath the glory, who reveals himself and the Father:
and they that deny revelation, know nothing as they ought to know,
but follow their own spirits, and see nothing.

And doth not the apostle say, in 1 Cor. 2:9. '`the things which eye hath not seen,
nor ear heard, neither came it into man`'s heart,
which God hath prepared for them that love him;
but God hath revealed them unto us by his spirit.`' Therefore,
can ye know any thing of the things of God,
which God hath prepared for them that love him,
which can neither be seen nor heard but by the revelation of God`'s spirit?

And the apostle (moreover) saith, '`the things of God knoweth no man,
but the spirit of God.`' +++[+++Mark,]
no man knoweth the things of God, but by the spirit of God, which was in the apostles,
which revealed the things of God to them,
which now also must reveal the things of God to people, if they know them,
which we witness.

And are not ye the ministers of the letter only,
that deny the revelation of the spirit of God, that the apostles were in,
to be expected nowadays?
therefore, you will never know the things of God, but by his spirit of revelation,
no man of you all.

See 1 Cor. 2:10,11,14. '`For the natural man perceives not the things of God,
they are foolishness to him, neither can he know them,
because they are spiritually discerned.`' And +++[+++mark,]
that spiritual discerning must be with the spirit that reveals them,
which was that the apostle was in, and we witness; and you say, '`ye have it not,
and it must not be looked for nowadays.`'

And Christ saith, in Matt. 11:25-26. and in Luke 10:21. '`I thank thee, O Father,
Lord God of heaven and earth, because thou hast hid these things from the wise,
learned men of understanding, and hast revealed them unto babes,
even so Father because it so pleaseth thee.`' Is it not so now?
Is not the revelation of the Son hidden from the wise, and the learned,
and men of understanding?
And do not many of them make a mock at it?
But Jesus rejoiced in spirit, and thanks God for this revelation, as you may see in Luke,
which he had revealed to babes, who were the learners of him; and he doth the same still,
though it is hid from your eyes:
and we and many babes can praise God for this revelation of his Son in us,
though many of you make a mock at it.

And in Matt. 16:16-17. Peter said, '`thou art the Christ, the Son of the living God:
Jesus answered and said unto him, blessed art thou Simon the son of Jona,
for flesh and blood hath not revealed this unto thee,
but my Father which is in heaven.`' +++[+++Mark,]
flesh and blood had not revealed, that Jesus Christ was the Son of God, unto Peter,
but the Father, which is in heaven.

And you that deny revelation nowadays, can any of you know Jesus Christ,
the Son of the living God, without the Son or the Father reveal him, which is in heaven?
Nay, and if you say yea, are not you such, that are thieves and robbers,
and climb up another way than by the door Christ?
For Christ tells you, no man knows the Father, but by revelation,
and is not all your talking of Christ, but imagination,
and the revelation of flesh and blood,
that deny the revelation of the Son of God by his spirit.

And in Luke 2:26. Simeon was a just man, and waited for the consolation of Israel,
and the Holy Ghost was upon him, and the revelation was given him of the Holy Ghost,
that he should not see death before he had seen the Lord Jesus Christ,
which revelation was fulfilled in the same chapter.

And now can any see the Lord Jesus Christ, but by the revelation of the Holy Ghost?
Or can any call him Lord, but by the Holy Ghost.

Now the pharisees had the scriptures of the Old Testament, as you have of the new.
These wise learned men, that had their Hebrew, Greek, and Latin,
who made a great talk that Christ was to come then, as you do now, that he is come,
but it is clear, as Christ saith, neither you nor any others can know him,
but by revelation, as Peter, and Paul, and Simeon knew him by revelation,
and the rest of the disciples, whom Christ calls babes.
Nay, further, in Luke 2:32. Simeon saith, speaking of Christ,
that '`he was a light to be revealed to the Gentiles, and the glory of my people,
Israel.`'

And now mark, all ye that stumble so much about Christ, the light,
which lighteth every one that cometh into the world, who is the glory of Israel;
it seems Christ the light is not revealed to you, your darkness cannot comprehend it,
which we witness and believe in, and see this glory of Israel,
and so are become children of the light:
and so you are they that stumble at the light at noonday, and at revelation,
for all your learning and knowledge of tongues, wisdom, and understanding;
this light to be revealed to the Gentiles you stumble at, which is revealed, we witness,
blessed be the Lord forever, to wit, Christ Jesus, the light,
which lighteth every man that cometh into the world.

And you may see Christ was revealed to old Hannah the prophetess,
when she was eighty-four years old, and she confessed Christ,
'`and spake of him to all that looked for redemption in Jerusalem.`'

And in Luke 17:30. '`In the day when the Son of man shall be revealed (to wit,)
from heaven.`' And in 2 Thess. 1:7-8. '`when the Lord Jesus Christ shall
be revealed from heaven with his mighty angels in flaming fire,
rendering vengeance unto them that know not God,
and which obey not the gospel of our Lord Jesus Christ,
which shall be punished with everlasting perdition from the presence of the Lord,
and from the glory of his power, when he shall come to be glorified in his saints,
and to be made marvellous in all them that believe.`' Now you that deny revelation,
and say revelation is ceased, and must not be looked for nowadays, consider this,
the revelation of Jesus from heaven in flaming fire,
rendering vengeance upon all them that know not God, and obey not his gospel,
the power of God: and Christ tells you, that you do not know God nor the Son,
but by revelation, therefore, consider what a condition you are in;
for in the days of Christ in his flesh, he was known by revelation;
and after his resurrection and coming again, it is by revelation that he is known,
as you may read, 2 Thes. 1. and Luke 17.
And the apostle saith, in Rom. 1:17.
'`the righteousness of God is revealed from faith to faith,
as it is written, the just shall live by faith;
for the wrath of God is revealed from heaven against
all ungodliness and unrighteousness of men,
which hold the truth in unrighteousness.`' Now you that deny revelation,
and say that revelation is ceased nowadays, you cannot know the righteousness of God,
which is revealed from faith to faith;
neither can you know the true faith by which the just lives, but by revelation,
then you are not like to preach it, which we witness.

And do not you think ye must know the wrath of God,
revealed from heaven against all ungodliness and unrighteousness of men,
who hold the truth in unrighteousness?
And what do you hold the truth of the prophets and Christ, and the apostles in,
but in unrighteousness?
Who say, you have not the same power and spirit which the prophets and apostles had,
be sure this revelation of his wrath will come upon you.

And in Rom. 8:18. '`I count the afflictions of this present time are
not worthy of the glory which shall be revealed in us:`' now mark,
this glory was to be revealed, which was not then revealed, but it shall be revealed,
therefore, can you be partakers of any of this glory, but by revelation?
For the fervent desire of the creature waiteth when the Son of God should be revealed.
Now mark, doth any know this state of the Son of God, but by the revelation of God?
If you say you do, you know it by another spirit and way than the apostles did,
which cannot be the true birth, but the birth born of the flesh,
which will persecute him that is born of the spirit, which we have felt sufficiently of.

And in 1 Cor. 3:13. hear you that deny revelation, what the apostle saith,
'`every man`'s work shall be made manifest; for the day shall declare it,
because it shall be revealed by fire,
and the fire shall try every man`'s work of what sort it
is;`' and do you think you can deny this revelation by fire?
That will try every man`'s work of what sort it is:
this day and revelation by fire is not yet come to you that deny revelation,
(for your works are not so tried,) which day will come.

And 1 Cor. 14:29-30. '`let the prophets speak, two or three, and let the other judge,
and if any thing be revealed to another that sitteth by,
let the first hold his peace.`' Now this was the order in the church of Christ.
Now you that deny revelation, which is an office here in the church,
that people should speak, or preach,
or prophesy one after another what was revealed unto them,
as the apostle did and exhorted to, another should hold his peace,
this would be counted disorder among you that deny revelation:
so you speak and preach that which was revealed to others, and not to yourselves,
so are not you as those who used their tongues, and said,
'`thus saith the Lord,`' whom the Lord never spoke unto, but reproves such.

And the apostle saith,
in Gal. 3:23. '`but before faith came we were kept under the law,
and shut up unto the faith which should afterwards be revealed.`' Mark,
you that deny revelation nowadays, are not you shut up?
Can you have any true faith, but by the revelation of Christ,
who is the author and finisher of faith?
For doth not the apostle say, that they themselves were shut up under the law,
and unto the faith which should be afterwards revealed, and who reveals this faith?
Is it not Christ, who is the author and finisher of it?
Therefore hath any one any true faith but by revelation,
according to the apostle`'s doctrine?
Which we witness to the glory of Christ.

And the apostle saith in Eph. 3:3,5. '`that God
by revelation hath shewed this mystery unto me,
which in other ages was not opened unto the sons of men,
as it is now revealed unto the holy apostles and
prophets by the spirit.`' Here you may see again,
that which was revealed to the prophets and apostles by the spirit of God, they declared,
which was not opened to the sons of men before,
but opened by the revelation of the spirit to them;
here the apostle owneth Christ`'s words,
that the Father and the Son are known by revelation.
And you that deny revelation nowadays, follow your own spirits, and see nothing,
like the false prophets of old,
and follow not the spirit that revealed that mystery to the apostles, nor Christ,
who doth reveal himself and the Father.

And in 2 Thess. 2:3-4. it is said, '`and that man of sin be revealed,
even the son of perdition, that exalts himself above all that is called God,
and sits in the temple of God: and now ye know what withholdeth,
that he might be revealed in his time,
and then shall the wicked man be revealed whom the
Lord shall consume with the spirit of his mouth,
and shall destroy with the brightness of his coming.`' Now here the apostle tells them,
this revelation was to come, and this destruction upon this son of perdition,
that sat in the temple of God, and exalts himself above all that is called God;
what temple of God is this, think you?
Look within where this man of sin sits: are not the saints the temples of God,
which own revelation?
But doth not he sit in your temples, and make you deny this revelation?
The son of perdition that sits in your temple,
and makes you deny the revelation of the son of God there,
and exalts himself above all that is called God, and his revelation in you,
and tells you it is ceased, and you must look for no such thing in your age,
and letteth here until he be taken out of the way.
And can any one know this man of sin, the son of perdition,
(that is exalted above all that is called God,
and sits in his temple,) but by the revelation of God`'s spirit, as the apostle was in?
For the apostle saith, '`that which may be known of God,
is manifest in them.`' Rom. 1:19.

And the apostle saith, then shall the wicked man be revealed,
whom God shall consume with the spirit of his mouth,
and shall abolish with the brightness of his coming.
Do you think that this man of sin in you,
will let you own this revelation of God to consume him?
Nay, the apostle saith, '`let no man deceive you by any means;
for that day shall not come except there be a departing first,
and that man of sin be revealed, the son of perdition.`'

So you that deny any revelation to be nowadays, do not you deceive people of that day,
and revelation of the son of perdition, and the revelation of the Son of God?
But that day of revelation is come, blessed be the Lord that he is revealed,
and you are discovered that deny revelation: so it is plain, by the apostle`'s words,
that you can neither know the things of God, nor Christ, nor the man of sin,
but by revelation, and consider what condition you are in, that say,
there is no revelation to be looked for nowadays.

And Peter saith, 1 Pet. 1:5.
'`ye are kept by the power of God through faith unto salvation,
which is ready to be revealed in the last time.`' Now, consider, ye that deny revelation;
do not you deny the faith and salvation to them that
are kept by the power of God through faith,
which was to be revealed in the last time?
Doth any know faith or salvation, but by revelation, as it is revealed in this our age,
to as many as wait for his appearance?
And the apostle, speaking of Christ, and of some searching the scriptures,
when or what time the spirit which testified of Christ, which was in them,
should declare the sufferings that should come unto Christ,
and the glory which should follow, unto whom it was revealed that not unto themselves,
but unto us, (to wit,) the apostles, mark here, this was known by revelation,
and can any know it, think you, without revelation of the same spirit,
(to wit,) Christ and his glory, as in 1 Pet. 1:11-5. as it was revealed to them.

And in 1 Pet. 4:13. '`but rejoice, inasmuch,
as ye are partakers of Christ`'s sufferings, that when his glory shall be revealed,
ye may be glad and rejoice.`' Now mark, ye that deny revelation,
here is the glory of Christ, which should be revealed,
which should glad and rejoice the saints, and you that deny revelation,
deny that glory of Christ that glads and rejoiceth the saints,
that is to be revealed to them.

And in 1 Pet. 5:1, '`the elders which are amongst you, I beseech,
who am also an elder, and a witness of the sufferings of Christ,
and also a partaker of the glory that shall be revealed,`' +++[+++mark,]
that shall be revealed, it was not then, so here was a revelation of glory to come.
And you that deny revelation to yourselves and others nowadays,
deny the saints of their glory that comes by revelation, which the saints then,
and we now, do witness, blessed be the Lord forever.
And your denial of revelation is little worth, if ye deny God, and Christ,
and the scriptures, and the things of God which are not known,
but by revelation of that spirit the apostles were in, and this we are witnesses of.

And Amos 3:7. '`surely the Lord God will do nothing,
but he revealeth his secrets to his servants the
prophets.`' And ye that deny revelation nowadays,
what will ye deny that God hath any servants or prophets nowadays?
It seems that you are none of his servants nor prophets
that have none of God`'s secrets revealed unto you,
and deny revelation; but his servants must tell you,
that God is the same that ever he was,
and there is a God in heaven that doth reveal secrets,
as you may see in Daniel`'s confession, and the apostles`'.

And the apostle saith, Rom. 2:5.
'`thou after thy hardness and impenitent heart
heapest up unto thyself wrath against the day of wrath,
and revelation of the righteous judgments of God.`'
This revelation of the righteous judgments of God,
that day you will know that deny revelation;
and that day you must know by revelation and judgment.

And the apostle saith,
in Rom. 16:25. '`now to him that is of power to establish
you according to my gospel and preaching of Jesus Christ,
by the revelation of the mystery,
which was kept secret since the world began.`' Now you that deny revelation, what,
will ye make people believe that ye shall know the mystery of Christ and his gospel,
(which hath been kept secret since the world began) without revelation?
Which the apostle Peter saith, 1 Pet. 1:12. '`this mystery was known by revelation,
which gospel is the power of God,
and came down from heaven.`' Rom. 1:16. which is according to Christ`'s words,
'`no man knoweth the Father but the Son, and he to whom the Son reveals him.`'

And ye may see in 1 Cor. 14:26. '`when the church came together,
such as had a doctrine, a tongue or revelation, or interpretation,
let all things be done unto edifying.`' So this was
and is the practice and order in the church of Christ,
which he is the head of, (to wit, revelation,) which we witness, though some deny it.

And the apostle saith to the Galatians, Gal. 1:11-12. '`now I certify you brethren,
that the gospel which was preached by me was not after Man,
for neither received I it of man, +++[+++mark,]
neither was I taught it,
but by the revelation of Jesus Christ.`' Now all you that deny revelation nowadays,
do not you deny the same gospel which the apostle preached, which gospel he saith,
'`is the power of God.`' Rom. 1.
And then is not your gospel after man?
And have not you been taught it, and received it of man, that is,
not taught it by the revelation of Jesus Christ; for the gospel being the power of God,
can any receive it but by the revelation of Jesus Christ and do not they preach themselves,
and not the gospel, that deny the revelation of the gospel of Jesus Christ nowadays?
And the apostle was learnt as well as any of you before he was converted,
but he counted all that as dross and dung to the
excellency of Christ which was revealed in him;
so they that preach Christ`'s gospel to others, that have it by revelation,
Christ hath the glory, though they may be persecuted by them that deny revelation,
and have what they have from man.

And the apostle saith to the Ephesians, Eph. 1:17.
that the God of our Lord Jesus Christ,
the Father of glory might give unto you the spirit of wisdom and revelation,
through the knowledge of him, that the eyes of your understandings might be enlightened,
that ye may know what is the hope of his calling,
and what is the riches of his glorious inheritance in his saints.
Now here all you that deny revelation, may see what the apostle prays for,
'`the spirit of wisdom, and of revelation,
that their eyes might be opened by this spirit of wisdom and of
revelation;`' and are not all your eyes shut that deny revelation,
and see not the hope of Christ`'s calling,
nor what is the riches of his glorious inheritance in his saints; but mark,
who might give people this spirit of wisdom and revelation,
the God of our Lord Jesus Christ, the Father of glory?
To him was the church, and now is to look unto for the spirit of wisdom and revelation,
by which their eyes are enlightened, by which they know the hope of their calling,
and the riches of Christ`'s glorious inheritance in his saints.
And you that deny the spirit of wisdom and revelation
now in your time to yourselves and others,
are far off from praying for this spirit of wisdom and revelation,
as the apostle was to open your hearers`' eyes and understandings, and your own:
so in denying revelation,
you keep both your own and theirs shut from that glory the saints did and do enjoy.

And in 1 Pet. 1:13. in his general epistle,
'`wherefore gird up the loins of your minds, be sober,
and trust perfectly in the grace that is to be brought
unto you at the revelation of Jesus Christ:`' +++[+++mark,]
this the saints were to do then, and so they are now to do the same,
to have the loins of their minds girded up, and to be sober,
and to trust perfectly on the grace that is brought
unto them by the revelation of Jesus Christ.
So all that know this grace,
they know how they received it by the revelation of Jesus Christ;
for grace and truth comes by Jesus Christ, as the law did by Moses:
and this is the grace that brings salvation, and which hath appeared to all men,
and taught the saints, though many there be that turn this grace of God into wantonness,
and walk despitefully against the spirit of grace,
and set up a heap of teachers after their own lusts, from whence wars arise,
and then say revelation is ceased in their day and time; but such,
the loins of their minds are neither girded up, neither are they sober,
nor trust perfectly on the grace that is brought by the revelation of Jesus,
which the saints then, and we now do witness, blessed he his name forever.
Here you may see by the apostle, that you do not know the grace of Christ and his gospel,
but by revelation.
And Peter further speaks, that Christ was revealed unto them,
and the gospel which they preached by the Holy Ghost, was sent down from heaven, +++[+++mark,]
was sent down from heaven; and therefore, where have you your gospel now,
that deny revelation, and say it is ceased.

And in Rev. 1. '`the revelation of Jesus Christ,
which God gave unto John,`' as you may see at large what the revelations are in his book,
but you see nothing of them that deny the spirit of revelation now in your days;
and Christ saith, '`he opens and no man shuts, and he shuts and no man can open:
and no man in heaven, nor in the earth, nor under the earth was able to open the book,
neither to look thereon, which made John to weep;`' but it was said unto him,
'`behold the lion which is of the tribe of Judah,
the root of David hath obtained to open the book,
and to loose the seals thereof.`' Therefore,
all look unto him who opens the book of the law and the prophets,
and the book of conscience, and the book of life;
that you may see your names written therein; and reveals grace, faith, the gospel,
himself and the Father, and his glory, and the things of God by his spirit;
so he is worthy to be waited upon,
(who reveals by his spirit,) and not upon them who deny revelation: and likewise,
who reveals unto you the man of sin, the son of perdition, who sits in the temple of God,
above all that is called God, whom he (to wit, Christ,) will destroy; and also,
he reveals his wrath, judgments and indignation upon all the disobedient,
and such as hold the truth in unrighteousness, and not in the spirit of revelation,
that the apostles were in;
and such as hold the truth in unrighteousness may plead for the body of sin and death,
and the old man with his imperfections to the grave, where there is no repentance,
where they and he may be buried in the lake together.

In 1 Sam. 3:7. '`Now Samuel yet did not know the Lord,
neither yet was the word of the Lord revealed to him,
and the Lord revealed himself to Samuel,`' ver. 21. So can you know the word of the Lord,
or the Lord, but as the Lord reveals it?
Or can you know the Father or the Son, but by revelation. Luke 10:22.

And in Isa. 40:5. '`the glory of the Lord shall be revealed,
all flesh shall see it together.`' Now can any see the glory of the Lord,
but by revelation?
'`Who hath believed our report,
and to whom is the arm of the Lord revealed.`' Now doth any know the arm of the Lord,
or believe the report of Christ, but by revelation, Isa. 53:1.
and John 12:38. '`for my salvation is near to come,
and my righteousness to be revealed.`' Now doth any know God`'s salvation,
and his righteousness, but as it is revealed, Isa. 56:1. and Christ saith,
'`there is nothing covered that shall not be revealed,
nor hid that shall not be known,`' etc.
So are not you all covered and the things of God hid from you that deny revelation? Matt. 10:26.
And in Luke '`the thoughts of the heart are revealed by Christ.`'
And Rom. 1:17. '`therein is the righteousness of God revealed from faith
to faith;`' so ye neither know God`'s righteousness nor faith,
but by revelation.
And in Luke 2:35. '`the thoughts of the heart are revealed
by Christ.`' And in Luke 17:30. '`when the Son of man
shall be revealed.`' And in Rom. 8:18. the apostle said,
'`he reckoned all sufferings as nothing to the glory which should be revealed
in them.`' And in 1 Cor. 2:10. '`and that which ear hath not heard,
nor eye hath not seen, God hath revealed unto the apostles,
the deep things of God:`' so the things of God are not known,
but as they are revealed by his spirit;
and if any thing be revealed to another that sits by, let the first hold his peace:
so the man of sin and the wicked one is not known, but as he is revealed;
so you do not know the word of faith, the light, the glory of the Lord,
the arm of the Lord, salvation, the righteousness of God, the things of God, the Son,
nor the Father, the wrath of God, your own thoughts, nor the man of sin,
the wicked one in your temple, but as they are revealed,
you do not know the grace of God, but by revelation, 1 Pet. 1:13.
nor you do not know the mystery
which was kept secret since the world began,
but by revelation, Rom. 16:25. neither do you know the righteous judgments of God,
but by revelation, Rom. 2:5. and though the Jews had the scriptures,
yet they knew not Christ the word.

And the gospel the apostle did not receive of man, nor by man,
but by the revelation of Jesus Christ. Gal. 1:12.

Now can you, or any man know this gospel the power of God,
that brings life and immortality to light, but by divine revelation?
And do not you that deny revelation, deny the coming of our Lord Jesus Christ;
for Christ saith, '`when the Son of man shall be revealed,
that the world should be doing as in the days of Noah,
etc. and when Lot went out of Sodom.`' Luke 17:30. And saith the apostle,
'`when the Lord Jesus shall be revealed from heaven
with his mighty angels in flaming fire,
taking vengeance upon all them that know not God,
and that obey not the gospel of our Lord Jesus Christ,
when he shall come to be glorified in his saints.`' And here again,
you that deny revelation, do not you deny the Lord Jesus,
his being revealed from heaven with his mighty angels, and glorified in his saints,
and are such that know not God, that he will take vengeance upon in flaming fire;
for how can you know God and Christ, but by revelation, seeing Christ tells you,
ye cannot know him nor his Father, but by revelation. 2 Thess. 1:7-8.

[.signed-section-signature]
G+++.+++ F.

[.blurb]
=== Now concerning such as deny prophecies in these days, and say it is ceased nowadays.

Now in the time of the prophets,
they that were in the form and not in the power did forbid the prophets to prophesy,
who said unto the seers, '`see not,`' and to the prophets,
'`prophesy not unto us right things,`' Isa. 30:10. '`but speak flattering
things unto us:`' and there are too many of those speakers nowadays,
that cannot abide true prophecy, that will run and speak, and the Lord never sent them,
as you may see in Jer.
xiv. and such as prophesy right things they cannot abide.

And in Amos 2:12. '`ye (to wit,
professing Israel,) commanded the prophets not to prophesy;`' but professing
christians which are of the same spirit without the profession,
say it is ceased.
And in Joel 2:28. saith the Lord, '`I will pour out my spirit upon all flesh,
(it doth not say upon some,) and your sons and your daughters shall prophesy, +++[+++mark,
shall, this was to come to pass,]
and your old men shall dream dreams, and your young men shall see visions;
and also upon the servants,
and upon the hand-maids in those days will I pour out my spirit,
saith the Lord.`' So mark, here is servants, hand-maids, young men, old men,
sons and daughters; the Lord hath promised he would pour out of his spirit upon them;
and are not all these to enjoy those promises, yea, verily,
God is faithful that hath promised it; for his promises are yea, and amen in Christ.
And was not this a fulfilling of (in Acts 2:17) to wit, the prophecy of Joel,
where the apostle saith, '`in the last days saith the Lord,
I will pour out my spirit upon all flesh, and your sons and daughters shall prophesy,
and your young men shall see visions, and your old men shall dream dreams,
and on my servants and hand-maids will I pour out of my spirit in those days,
and they shall prophesy.`' Now mark, ye that say prophecy is ceased in your days;
is not the last days the christian`'s days, (to wit,) the days of Christ?
Is not he the '`first and the last, the same today as yesterday,
and forever.`' God`'s servants and his hand-maids, that have his spirit poured upon them,
they will prophesy; and they that have God`'s spirit poured upon them,
sons and daughters will prophesy this spiritual prophecy;
and the young men and old men that have God`'s spirit poured upon them,
they have their heavenly visions and heavenly dreams, and this we witnesss,
though neither your young men, nor old men, servants, nor hand-maids, sons,
nor daughters, nor yourselves, that say, prophecy is ceased,
and the same spirit is not to be looked for now as the apostles had,
then you may say faith and grace is ceased, nor none of these have visions or dreams,
nor prophecies; so do not you keep your people in darkness,
being-in the darkness yourselves?
But the apostle saith,
'`they shall prophesy;`' and Philip had four daughters which did prophesy, Acts 21:9.
that were virgins, though your virgins do not,
but those virgins which witness God`'s spirit, do, though you may be all amazed,
and mock at it like the Jews. Acts 2:11-12.

And the apostle saith in Rom. 12:6. '`seeing then,
that we have gifts that are differing according to the grace, +++[+++mark,]
according to the grace that is given unto us, whether we have prophecy,
let us prophesy according to the proportion of faith.`'
So here the apostles doth not forbid it,
and say it is ceased, as you do, but encourageth it in the church,
'`let us wait on the office,
he that teacheth on teaching,`' that is according to the grace
given to them '`as God hath dealt to every man a measure of faith.`'

And the apostle saith, in 1 Cor. 13:19. '`And we prophesy in part,
and when that which is perfect is come,
then that which is in part shall be abolished;`' so here he was
encouraging the church to grow up unto a further degree,
both in knowledge and prophecy; but if there were that love among you,
which he speaks of in this chapter, then those things would be owned in their places,
and the fulfilling thereof waited for, and their prophesying in part owned,
which is denied by you in your day,
therefore you are not like to grow up to a perfect state, who deny that.

And the apostle saith, 1 Cor. 1:24,29,31. Follow after love,
and covet spiritual gifts, but rather that ye may prophesy; but if all prophesy,
and there come in one that believeth not, and unlearned, he is rebuked of all men,
and is judged of all, and the secrets of his heart are made manifest,
and will fall down and worship God, and say,
'`God is in you of a truth.`' Now see this office of prophecy in the church,
the effect of it, '`Let the prophets speak one or two, and let others judge;
for ye may all prophesy one by one, that all may learn,
and all may be comforted;`' you that say, prophecy is ceased nowadays amongst you,
then this learning, and this comforting is ceased among you,
and this manifesting the secrets of men`'s hearts is ceased among you,
and this falling down and worshipping God, and saying God is in you of a truth,
this is ceased among you that say prophecy is ceased;
for this is the work and effect of prophecy in the church of Christ,
which is the same today as yesterday, and so forever;
but he that prophesies speaks to men for exhortation, and to edification,
and for comfort.
Now you that say prophecy has ceased in your church nowadays,
this edifying and speaking to men; and this exhortation and comfort is ceased;
'`but he that prophesieth,`' saith the apostle, '`edifies the church;
for greater is he that prophesieth, than he that speaketh with divers tongues,
wherefore brethren covet to prophesy;`' so you that say prophecy is ceased nowadays,
the edification is ceased then,
and that is ceased which is greater than speaking with divers tongues,
etc. and that is ceased also which the brethren, the church, were to covet after,
(to wit,) prophecy; therefore, how can you say,
that you are either the true church or true ministry, that say prophecy is ceased,
which was for the comforting and edification of the true church?

And you may see in Rev. 11:9. how the kindreds
and tongues were against the two witnesses that prophesied,
and when they had killed them, they made merry over them,
and sent their gifts one to another, but they rose again to their torment;
and so doth not the testimony of Jesus, the spirit of prophecy torment you now?
And in 1 Cor. 11:4. '`Every man praying or prophesying with his head covered,
dishonours his head, and every woman praying or prophesying with her head uncovered,
dishonours her head.`' So you may see,
here were men and women prophesying and praying in the church,
and Hannah was a prophetess, and Huldah,
and Miriam and Debora were prophetesses in the time of the law,
therefore the apostle saith, 1 Thess. 5:20.
'`Despise not prophesying.`' And do not you despise it in others,
that say it is ceased?
And may you not as well deny prayer as prophecy, and say, prayer is ceased,
as you say prophecy is ceased; for the apostle joins them together.

And in Rev. 19:10. '`For the testimony of Jesus
is the spirit of prophecy,`' saith John the divine,
mark, all you that are called christians in the whole world,
and say prophecy is ceased in your day, and none must look for prophecy in your day;
(mark well,) is not the testimony of Jesus then ceased, the spirit of prophecy?
And you have not the testimony of Jesus;
for the testimony of Jesus is the spirit of prophecy, and so if prophecy be ceased,
then the testimony of Jesus is ceased among you,
who live in an outside profession of the saints`' words;
but did not all worship the beast, and drink the whore`'s cup,
but those who kept the faith, and testimony of Jesus,
whose names were written in the book of the lamb
which was slain from the foundation of the world?

And in Hosea 9:7. '`The prophet is a fool,
and the spiritual man is mad.`' Thus did the professing Jews esteem the Lord`'s prophets,
and thus do the professing christians now account the spiritual men mad,
and the prophet a fool.
And in Prov. 31:1. '`The words of king Lemuel,
the prophecy that his mother taught him; what, my son; what, the son of my womb,
and what, the son of my desires; give not thy strength unto women,
nor thy ways which is to destroy kings.`' Here is
the prophecy which his mother taught him;
and is not this prophecy to be learned of such as can teach it?

And the apostle saith, in 1 Tim. 4:14. '`Despise not the gift that is in thee,
which was given thee by prophecy.`' +++[+++Mark,]
Here was a gift given to him by prophecy.
Now you that deny prophecy, and say it has ceased, what then, is the gift ceased to you?
Then how can you follow the practice of the holy men of God?

And in 2 Pet. 1:19. '`But we also have a more sure word of prophecy,
to which ye do well that ye take heed,
as unto a light that shines in a dark place until the day dawn,
and the day-star arise in your hearts:
for the prophecy came not in the old time by the will of man;
but holy men of God spoke as they were moved by the Holy Ghost: so first know this,
that no prophecy of the scripture is of any private
interpretation or motion.`' So now mark,
you that say '`prophecy is ceased,`' then you may
say that spirit that gave forth the scriptures,
that Holy Ghost which moved them to speak them forth is ceased;
and you make a profession of them in the will of man,
and your own private motions of that which came not by the will of man;
and then you and your people know not of this sure word of prophecy,
which they do well that take heed unto, as unto a light that shines in a dark place,
until the day dawn, and the day-star arise in their hearts.
Now, they do well that take heed unto this light that shines in a dark place,
which is the sure word of prophecy.
Now you may say, that say prophecy is ceased,
'`how long must we take heed unto it?`' the apostle and we tell you,
'`until the day dawn, and the day-star arise in your hearts,
so long you must take heed unto it.`' Now, you do not do well,
that do not take heed unto this sure word of prophecy; for they that do so, do well;
and they that do not, do ill.

And now people consider, though it is the principle of your teachers to say,
prophecy is ceased in your days; do you ever think to come to the day-dawning,
and the day-star arising in your hearts,
except ye do first take heed to this most sure word of prophecy,
as unto a light that shines in the dark place, +++[+++mark,]
take heed unto it, until the day dawn, and the day-star arise in your hearts.

And it is said in 1 Cor. 12:10. speaking of the several gifts in the church,
to one the working of miracles, and to another prophesy,
and to another the discerning of spirits; but all these gifts were from the one spirit,
and the manifestation of the spirit of God was given to every man to profit withal;
so no man can profit,
but in the same spirit in which the holy men of God gave forth the scriptures,
which you have said you have not the same, by which the several gifts flowed from,
so not the same gifts, nor gift of prophecy in your church.

Now you may say, the law and the prophets were until John, which is true:
but we tell you there were prophets after John, as well as before,
as in Acts 19:6. when the Holy Ghost came upon them, they prophesied.

And the apostle saith, 1 Tim. 1:18. '`this commandment commit I unto thee,
son Timothy, according to the prophecies that went before on thee,
that thou by them should fight a good fight,`' +++[+++mark,]
should fight a good fight, according to the prophecies which went before on him,
having faith and a good conscience, which some have put away,
and concerning faith have made shipwreck; and such may say, prophecy is ceased,
and a good conscience too; and that faith is ceased that works by love,
which purifies the heart, and gives victory over the body of sin,
(which they plead for to the grave,) amongst them that were amongst the apostles:
and then ye may sat, '`revelation is ceased, and grace is ceased, that brings salvation,
and the knowledge of God and Christ (which is by revelation,) is ceased.`'
But the revelation of the wrath and judgments of God such will feel,
which is to be revealed from heaven against all that hold the truth in unrighteousness,
and not in the spirit of revelation, that gave it forth.

And the prophets, apostles,
and Christ himself did not suffer by their persecutors as true prophets,
but were persecuted by them as false prophets:
though the persecutors then might get the words of the true prophets,
as they have done since the apostles`' days,
that persecuted them that kept the testimony of Jesus, the spirit of prophecy,
and had the true revelation of Jesus, they persecuted them as false prophets,
as their forefathers did the prophets, Christ and the apostles; and so they do now,
who have not been in the life and spirit of the prophets, Christ nor the apostles,
nor in their power; so they were not in the spirit that gave forth scriptures,
that persecuted Christ and his apostles, neither are they now that do persecute.

And they that turned against Moses and, the prophets were transgressors of the law of God.
So here you may see, that birth that is born of the flesh,
persecuted that birth that is born of the spirit,
which had the revelation of the Son of God, and kept the testimony of Jesus.
And are not you of the same birth, that say,
'`you have not the same spirit as Christ and the apostles had;`' then are not you,
by your own judgment and rule, none of his?

Now you that say, prophecy is ceased, the apostle tells you,
'`that greater is he that prophesieth,
than he that speaketh with tongues.`' So then the greater is ceased among you.

And the apostle tells the church, '`but he that prophesieth,
speaketh unto men to edification, and to exhortation, and to comfort.`' Now,
you that call yourselves apostles and teachers, and say, prophecy is ceased,
then edification, exhortation and instruction is ceased amongst you.

And the apostle saith, that '`prophesying serveth not for them that believe not,
but for them that believe.`' So may not you as well say, believing is ceased,
as the service of God is ceased.

And again, the apostle saith, '`ye may all prophesy one by one, that all may learn,
and all may be comforted.`' So if prophecy be ceased among you,
then this learning is ceased, and this comforting is ceased.

And again, the apostle saith, '`wherefore brethren,
covet to prophesy.`' Now you are of another mind, that say, it is ceased in your church,
as you may see in 1 Cor.
xiv. the chapter throughout; for if any man be ignorant let him be ignorant.

And also, the apostle bids the Thessalonians,
'`quench not the spirit,`' and you tell us,
'`that you have not the same spirit as they had in the primitive times:`'
then you may say,
'`how can you quench it, when you have it not?`'
then with what do you read the scriptures,
but follow your own spirits, like the false prophets, and see nothing?

And the apostle bids the Thessalonians,
'`despise not prophesying.`' But you do not only despise it, but you deny it,
for any such thing as prophecy to be in your church in your day;
so you deny the true edification, and comfort, and learning,
which was and is in the church of Christ,
as you may see in 1 Thes. 5. and in 1 Cor. 14. etc.

[.signed-section-signature]
G+++.+++ F.

[.blurb]
=== And now concerning them which deny Inspiration nowadays.

In Job 32:8. '`surely there is a spirit in man,
but the inspiration of the Almighty giveth understanding.`' +++[+++Mark,]
the inspiration of the Almighty giveth understanding.

Now all you that deny the inspiration of the Almighty, in these your days,
to give you understanding; then pray you, what understanding have you?
Is it not that which must come to naught?
For it is written, '`I will destroy the wisdom of the wise,
and will cast away the understanding of the prudent.`' 1 Cor. 1:19, etc.

And in 2 Tim. 3:16. '`for all scriptures is given by inspiration of God,
and is profitable,`' etc.
'`that the man of God may be made perfect in all good works;`' not the men of the world,
for they deny perfection.

Now if all holy scripture be given forth by inspiration of God,
how can ye know the scriptures that say, inspiration is ceased?`'

'`For the natural man perceiveth not the things of God;
for they are foolishness to him.`' And so was not the prophets`' and apostles`'
words foolishness to the natural men in their natural profession?

And is it not so now to you christians, with all your tongues and languages, that say,
inspiration has ceased, and yet,
'`no man knows the things of God but by the spirit of God.`' So
as the scriptures were given forth by the inspiration of God,
so they are known again by the same spirit.
And therefore, Christ saith, '`I will send you the spirit of truth,
he shall lead you into all truth,
and he shall bring to your memory the things that I have spoken,
and he shall shew you things to come,`' and so make them prophets;
'`and he shall take of mine,
and give unto you.`' So by this the apostles did know the scriptures,
though they were unlearned men, many of them, outwardly:
for the Holy Ghost led them into the truth of the prophets and holy men of God,
which spake forth scriptures as they were moved by the Holy Ghost,
and sheaved the fulfilling of them by Christ;
and it brought to their memories what Christ had spoken to them,
which after they did record it, as you may see in the four evangelists.
So the scriptures, which were given forth by divine inspiration of God,
is known again by divine inspiration of God.
And they that deny divine inspiration of God nowadays, know not the scriptures,
that were given forth by inspiration,
and therefore they are all in heaps about them and are not
like to know them but by that spirit that gave them forth,
that key that will open them,
and that tongue of the learned and without it they cannot read the book,
though they have all the languages upon the earth,
but have not the spirit of inspiration nowadays, as they confess;
then they had better be still, and wait upon the Lord for it;
else they will be found of the number of them that run, and the Lord never sent them,
and speak when the Lord never spoke unto them, (and come under the reproof of God,
and his prophets, and the scriptures,) but know none of God`'s inspiration;
for they that have inspiration,
have the power and spirit they had which gave forth the scriptures:
and they that have the form of godliness,
and deny the power and spirit as the apostles were in, are to be turned away from;
for the apostle saith, turn away from such; for they keep people always learning,
and never able to come to the knowledge of the truth.
Seeing the scriptures were given forth by divine inspiration, and are the things of God,
they are not known again but by inspiration of the Holy Ghost,
which leads into all truth.
And the inspiration of the Almighty gives the understanding;
and you that deny inspiration, deny this heavenly understanding.
And you that have all the scriptures, from Genesis to the Revelations,
yet you know them not with your natural spirit of understanding,
nor by all the tongues and languages since Babel;
for none know them but by the spirit of inspiration that gave them forth.

[.signed-section-signature]
G+++.+++ F.

[.blurb]
=== Now concerning the Measure of the Spirit, as God hath dealt to every man.

In Rom. 17:3. it is written, '`for I say, through the grace that is given unto me,
to every one that is among you,
that no man presume to understand above that which is meet to understand,
that he understand according to sobriety,
as God hath dealt to every man the measure of faith.`' So you may see here,
that the apostle himself, and he would have the church,
not to presume to understand any further,
but as God hath dealt to every man the measure of faith; if they did,
they did presume above their measure: so,
to understand as God hath dealt to every man the measure of faith,
this keeps every man in the faith and in the grace, in their measure.
But you that have not the same faith, which works by love,
which Christ is the author and finisher of,
and walk despitefully against the spirit of grace, and turn from it into wantonness,
are in the presumption, that would understand without the faith, and the grace and light.
You go beside the apostle`'s doctrine, and the measure of faith,
the measure of which God hath dealt to every man.
So every man must look at the grace and faith which
God hath dealt to him through Christ Jesus,
who is the author of it and finisher, and understand and walk by it,
which was the practice of the true church, and exhortation of the true ministers.

And the apostle saith, in 2 Cor. 10. how the '`weapons of their warfare were not carnal,
but mighty through God to cast down strong holds, casting down the imaginations,
and every high thing that is exalted against the knowledge of God,
and bringing into captivity every high thought, to the obedience of Christ,`' etc.
Now, here was the spiritual warfare, and the spiritual weapons; '`for,`' saith he,
'`we dare not make ourselves of the number,
nor compare ourselves to them who praise themselves;`' but they
understand not that they measure themselves with themselves:
this was a wrong measure and understanding,
which the apostle durst not make himself of the number of such as did so,
who kept to his own measure,
neither can they who keep to the measure which God hath distributed to them.
But do not you now measure yourselves by yourselves, and praise yourselves,
who own not the measure, and do not come to the measure that God hath distributed?
And do not you say, '`that God doth not distribute immediately now,
as he did in the apostles`' days?`'

And further, the apostle saith, '`but we will not rejoice in things without our measure,
but according to the measure of the rule,
wherewith God had distributed unto us a measure to reach even unto you.`' So here the
apostles kept their joy within the measure of the rule that God had distributed to them:
for he saith,
'`for we stretch not ourselves beyond our measure.`' So here again
he kept within the measure God had distributed to them;
and likewise, would have the church to do the same.

And further, the apostle saith, '`not boasting of things which are without our measure,
that is, of other men`'s labours; and we hope when your faith shall increase,
to be magnified by you, according to our rule, abundantly.`' Nov,
see here what was the apostle`'s rule, which they stretched not beyond,
and did not boast out of it, nor did boast of other men`'s labours;
but this measure and this rule was that which God had distributed unto them:
and you that have gone from this rule and measure,
are not you boasting of other men`'s labours; (to wit,) of the prophets and apostles,
and call that your rule, and praising yourselves and measuring yourselves,
and stretching yourselves besides that measure and
rule which God hath distributed to them,
and which the apostle was in, and exhorted others unto;
and also are boasting of things besides this measure and rule which
God doth distribute to his church and to the apostles:
so by this measure and rule they were to walk, which God had distributed to them,
then and now, by which measure and rule they knew the scriptures and the things of God,
which rule and measure God had distributed to them.

And further, the apostle saith,
that '`they did not rejoice or boast in other men`'s lines,
or in things made ready to our hand,`' or prepared already.
So here you may see,
the apostles kept to the rule and line that God had distributed to them.
Now, do not you rejoice and boast in other men`'s lines nowadays; that is,
in things made ready to your hands, and prepared already, and say,
'`that is your rule,`' (to wit,) '`the prophets`', Christ`'s and the apostles`' words,
which are other men`'s labours and lines, which they suffered for,
for speaking forth the apostles`', prophets`' and holy men`'s labours,
which you rejoice and boast in, which are other men`'s lines,
prepared already to your hands.

And are not you against the measure of the light, of the grace,
of the spirit of the faith now, which we witness, with the apostles?
And you persecute such a measure of the rule which God hath distributed,
which we rejoice in and walk by,
with which we know you are boasting in other men`'s labours,
that are made ready to your hands: but let him that rejoiceth, rejoice in the Lord,
who distributes this measure; for, not he that praises himself,
and looks on things after the outward appearance, is allowed;
but he whom the Lord praises, that walks according to the measure of the rule,
as God hath distributed to him; in this God hath the glory out of all hearts:
and the vain rejoicer, and boaster, and comparers of themselves with themselves,
which are not wise, and will boast of other men`'s labours and lines,
and works made ready to their hands, that is kept down;
for that boast and joy is not of the Lord, neither he that praises himself; I say,
that is kept down by the measure of the rule which God distributes;
in which measure and rule God hath his praise.

And the apostle saith 2 Cor. 12:6-7. '`lest any
man should think of me above that he seeth in me,
or heareth of me, lest I should be exalted above measure,`' etc.

Now here you see the humility the apostle was in; he would have people, or the church,
not to think of him above what they see in him, (to wit,) his measure,
though he saw things not fit to be uttered;
and when the messenger of Satan was sent to buffet him, and he besought the Lord thrice,
the Lord`'s answer was to him, '`my grace is sufficient for thee,
and my power and strength is made perfect in weakness:`' and in this strength,
power and grace did the apostle rejoice, and in his infirmities.

And the apostle saith in Eph. 4:7. '`but to every one of us is given grace
according to the measure of the gift of Christ.`' And by this measure of grace,
the gift of Christ, they did walk, and so must all true christians,
by which they must walk, if they will grow in grace;
and if they grow up to the measure of the stature of the fulness of Christ,
they must grow in grace.

And in Gal. 6:14. the apostle saith, '`God forbid I should rejoice,
but in the cross of our Lord Jesus Christ, whereby the world is crucified unto me,
and I unto the world;
for in Christ neither circumcision nor uncircumcision availeth any thing,
but a new creature; and as many as walk according to this rule, peace be upon them,
and mercy upon the Israel of God.`'

[.signed-section-signature]
G+++.+++ F.

[.blurb]
=== Concerning the Rule.

Now mark, you professors of the letters, that say,
'`the scripture is your rule;`' was not circumcision of the letter of the scripture?
And yet the apostle saith, it avails nothing, but a new creature:
and that which the apostle rejoiced in, was the cross of Christ,
in which he was crucified to the world, and the world to him.
And is not the cross of Christ the power of God?
and as many as walk according to this rule, and rejoice in it,
(to wit,) the cross of Christ, and the new creature?
I say, as many as walk according to this rule, peace be upon them, and mercy,
and upon the Israel of God.
For the apostle saith,
'`the cross of Christ is the power of God;`' so that the rule of
the new creature in Christ he sets forth to be the rule.
And you that have the form of godliness, and deny the power thereof,
and the having the spirit that gave it forth now in your days, and call it your rule,
and yet walk quite contrary to it, are to be turned away from;
yet not turn away from the scriptures, but from you, that walk contrary to them,
and the spirit that gave them forth.

And the apostle saith in Phil. 3:16. nevertheless, in that whereunto we are come,
let us proceed by one rule, that we may mind one thing;
for he had told them with weeping of such as were enemies to the cross of Christ,
whose end is damnation, whose God is their belly, and glory in their shame,
who mind earthly things.

Now were not they enemies to the rule then, which was the cross of Christ,
the power of God?
and what was this rule they were to walk by?
Was it not that which God had distributed to them, the spirit of God?
For these, whose belly was their God, and gloried in their shame,
and minded earthly things, whose end was damnation; these were a kind of christians,
which it is to be feared there are too many such now,
which were enemies to the cross of Christ, which is the power of God,
which were to be turned away from: and was not the grace of God,
which God said should be sufficient for Paul,
and his strength made perfect in his weakness;
was not this grace and strength a sufficient rule for Paul?

And doth not the apostle say,
'`let Christ rule in your hearts by faith who shall rule all nations with
a rod of iron?`' So is not he a sufficient rule in the heart by faith,
and a sufficient rule to rule all nations, Rev. 12:5. yea,
and sufficient to rule the heathen. Rev. 19:15.

And doth not Christ say, '`I will send you the spirit of truth,
which shall lead you into all truth,
and bring to your remembrance the words I have spoken unto you?`'

Is not this spirit a sufficient rule, that leads into all truth?

And in Neh.
ix. the Lord gave his good spirit to the people, '`his good spirit to instruct them,
and they rebelled against it.`'

And were not they reproved for so doing?
and was not that a sufficient rule?
And are not they the sons of God that are led by the spirit of God?
and is not that a sufficient rule to lead and guide?

And the Lord saith, '`he that hath the Son, hath life.`'

And is not here a sufficient rule?

And John said, '`these things I have written unto you, concerning them that deceive you;
but the anointing which you have received of him, dwelleth in you;
and you need not that any man teach you,
but as the same anointing teacheth you all things, and is true, and is no lie.`'

And is not this a sufficient rule, this teacher, that people might see the deceivers,
and shun them?

And the Lord saith, '`I will put my laws in your minds, and write them in your hearts;
and I will be their God, and they shall be my people;
and they shall not teach every man his neighbour, and every man his brother, saying,
know the Lord; for all shall know me,
from the least of them to the greatest of them;`' and is not this
law and new covenant a sufficient rule to know God by?
And was not the Holy Ghost a sufficient rule,
that led Moses and the prophets to give forth the scriptures?
And was not the Holy Ghost a sufficient rule,
that led the disciples and apostles of Jesus Christ into all truth;
and see the fulfilling of the law and, prophets in Christ,
and brought to their memories the words that Christ spoke, and afterwards to record them?
and is not the same Holy Ghost a sufficient rule for all christians now to know God,
and Christ, and the scriptures, and lead them all into the truth of them;
in which Holy Ghost they must pray and have their fellowship,
seeing no man knows the things of God without the spirit of God,
which searcheth all things, and they are spiritually discerned,
and the natural man perceives them not, they are foolishness to him;
and how can they be his rule, when they are foolishness to him, as in 1 Cor.
ii.

And what rule had Abel, and Enoch, and Noah, and Abraham, Isaac and Jacob, and Moses,
before scriptures were given forth?
Did not they walk by faith, which was the gift of God, yea, and to be perfect?
Was not Abraham commanded to walk before him, and be perfect,
which perfection you cannot attain unto by walking in the oldness of the letter,
for you must serve God in the newness of life, and not in the oldness of the letter, Rom. 7:6.
'`for the letter killeth,
but the spirit giveth life.`' 2 Cor. 3:6. And so,
was not that faith a sufficient rule for all the old fathers to walk by?
And must not we walk in the steps of the faith of our father Abraham? Rom. 4:12.

And the apostle saith, '`but he is a Jew who is one within,
and the circumcision is of the heart, in the spirit, and not in the letter,
whose praise is not of men, but of God.`'

So, is not he a christian who is one within, in the heart (and not in the letter,) only,
whose praise is of God, and not of men, seeing that many may have the form of godliness,
but deny the power thereof, which are to be turned away from:
and may not such say they are christians, as the Jews said they were Jews, and were not,
but the synagogue of Satan?

And the apostle said, '`henceforth, know we no man after the flesh, yea,
though we have known Christ after the flesh,
yet henceforth know we him so no more.`' 2 Cor. 5:16.

And their fellowship stood in the spirit,
and they were to know Christ and one another in the spirit,
and to keep the unity of the spirit, which is the bond of peace, yea,
even of the Prince of princes`' peace:
but they that deny the having of that spirit the apostles were in, know not Christ,
nor the fellowship of the saints, nor the Prince of princes`' peace.

And the apostle saith,
in Rom. 15:18. '`for I dare not speak of any
thing which Christ hath not wrought by me,
to make the Gentiles obedient by word and deed.`' Now mark,
did not he keep to the measure of the rule which Christ had wrought in him?

Now come, all ye priests and professors in Christendom,
and try yourselves by the scriptures, which you say is your rule;
how dare you speak anything, to make people obedient in word and deed,
that Christ hath not wrought in you or by you?
Are not you boasting of other men`'s lines and labours,
that other men have made ready for your hands?
Do not you want the fear of God in your hearts, as was in the apostles,
who durst not speak anything but what Christ had wrought
by them to make people obedient by word and deed?
Ought not the apostle here to be your example?
And then Christ would have the glory of that which he works by you in people, and in you,
and your own wills would be laid in the dust.
And therefore, is not all that which you speak to people,
that which Christ hath not wrought in you and by you, like the false prophets,
using your tongues, and the false apostles boast of other men`'s lines.

And the apostle saith, in Rom. 3:24. '`and we are justified freely by his grace,
through the redemption that is in Christ Jesus.`'

And in Rom. 4:12,16. '`but unto them also that walk in the steps of
the faith of our father Abraham:`' and is not this a rule sufficient?

And in Rom. 8:1-2. '`now there is no condemnation to them who are in Christ Jesus,
who walk not after the flesh, but after the spirit; for the law of the spirit of life,
which is in Christ Jesus, hath made me free from the law of sin and death.`'

Now, is not this spirit a sufficient rule to walk by?
But you that say it is not the rule, do not you remain under condemnation,
under the law of sin and death, pleading for it,
and not for freedom by the law of the spirit in Christ on this side the grave.

And further, the apostle saith, '`but if ye mortify the deeds of the flesh by the spirit,
ye shall live.`' Therefore is not this spirit a sufficient rule to walk by?

And in 2 Cor. 5. the apostle saith,
'`for we walk by faith, and not by sight.`' +++[+++Mark, not by sight.]
The church was not to walk by sight, but by faith, which Christ is the author of;
and is not this sufficient?
And they who walk by faith, walk in the steps of the faith of our father Abraham,
his faith, which was before scriptures were written?
And is not this a sufficient rule for all the faithful,
which is testified of in the scripture, and was before scripture was written;
and which scripture is to be believed, and fulfilled, and practised, etc.

And Eph. 2:8. '`by grace are ye saved, through faith, and not of yourselves,
it is the gift of God.`' So is not that sufficient to walk by, which saves?

And in 1 John 1:7. '`If we walk in the light, as he is in the light,
we have fellowship one with another, and the blood of Jesus Christ, the Son of God,
cleanses us from all sin.`'

So is not this light sufficient to preserve the fellowship, by walking in it?
And is there any cleansing from all sin by the blood of Jesus Christ,
but first they must walk in the light?
There may be a talking of the blood of Christ,
and yet a pleading for the body of sin and death, and imperfections to the grave;
so that only talking of the blood of Christ will do them but little good,
and pleading for their body of sin and death, and imperfections to the grave,
that there they may be all buried in the pit together, where there is no repentance,
and give a man ten or twenty shillings to preach them a funeral sermon:
and as it is in Heb. 9:27. '`it is appointed unto men, that they should once die,
and after that come to judgment.`' And therefore, consider and mark this,
and quench not the spirit which God hath given you to profit withal;
and do not resist the Holy Ghost, which Christ hath sent to lead you into all truth,
and to reprove you; and hate not the light which Christ hath enlightened you withal,
that you may believe in it, and walk in it, that you may become children of the light,
lest it be your condemnation: for is not the light sufficient to lead you, and guide you,
and rule you,
and to give you the knowledge of the glory of God in the face of Christ Jesus?
And is not that the treasure which the saints had in their earthen vessels,
that the excellency of the power might be of God, and not of us. 2 Cor. 4.
And rebel not against the spirit, which God hath given you to instruct you,
and to know the things of God by,
and that in the spirit you may have fellowship with the saints:
for if you rebel against his good spirit, what are all your fellowships good for?
And is not God`'s spirit sufficient?
Doth not Christ say, '`it is the spirit of the Father,
that speaks in you?`' And is not that sufficient to rule and to guide,
and to serve and worship God in, in spirit and truth?

And did not the apostle say,
in Rom. 1:9. that he '`served God in the spirit.`'
And is it not the duty of all christians,
to serve God in the spirit?
and is not that a sufficient rule that will teach them to know how to serve God, (to wit,
his holy spirit,) by which spirit they may know God, and Christ, and the scriptures,
and know one another in the spirit, and in it have fellowship,
and so keep the unity of the spirit, in the bond of peace, yea,
the bond of the Prince of princes`', King of kings`', and Lord of lords`' peace,
which none can take away from them?

And doth not Christ say, '`they that worship the Father,
must worship him in spirit and in truth?`' And is not that a sufficient rule,
to worship him in, the grace of God, which brings salvation, which teacheth the saints?
Is not this a sufficient rule to teach and to establish the heart, and season thy words,
and bring salvation?

And the apostle saith, Rom. 8:26.
'`likewise the spirit also helpeth
our infirmities.`' So is not this spirit sufficient,
that helps people`'s infirmities?
'`And the spirit itself makes intercession.`'

And in Gal. 5:16. '`I say, walk in the spirit,
and ye shall not fulfill the lusts of the flesh.`'

And is not this a sufficient rule for people to walk by?

And the apostle saith, in Gal. 2:19-20. '`for I through the law am dead to the law,
that I might live unto God; I am crucified with Christ, nevertheless I live, yet not I,
but Christ liveth in me; and the life that I now live in the flesh,
I live by the faith of the Son of God, who loved me, and gave himself for me.`' +++[+++Mark,]
This should be every christian`'s life and living.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Worcester-Prison, the 9th day of the 11th month, 1676.

[.signed-section-context-close]
For obeying the command of Christ, and the apostle James`'s doctrine,
who says, '`swear not at all.`' Matt. 5. Jam. 5.
