== The Beginning of Tithes in the Law / and Ending of Tithes in the Gospel

[.heading-continuation-blurb]
The Law and the Commandment of the Lord concerning payment of tithes,
to whom, and how they were to be disposed, viz.
to the Levitical Priesthood in the Old Testament,
and how Christ is come to end that Priesthood, Law,
and Commandment, by which he took the tithes and Offerings.--By G. F.

All the tithes of the land, whether of the seed of the land,
or of the fruits of the trees, are the Lord`'s, they are holy unto the Lord.

And concerning the tenths of the herds, or of the flock,
even of whatsoever passeth under the rod,
'`the tenth shall be holy unto the Lord.`' Lev. 27:40, to the end.

'`Behold, I have taken your brethren the Levites, from among the children of Israel,
to you they are given as a gift from the Lord,
to do the service of the tabernacle of the congregation: therefore,
thou and thy sons with thee shall keep your priest`'s office,
for everything of the altar; and within the veil ye shall serve:
I have given your priest`'s office unto you, as a service of gift;
and I have given to thee, the charge of the heave-offerings,
and thou shalt keep the charge of the altar and the sanctuary,
and thou shalt keep the charge of the tabernacle for the congregation,
and for all the services of the tabernacle. Num. 18:6-7.
and the Levites shall be mine, I am the Lord.`' Num. 3:45.

'`And behold,
I have given the children of Levi all the tenths in Israel for an inheritance,
for their services which they serve, even the service of the tabernacle.`'^
footnote:[Christ has discharged them of this charge.]

Neither must the children of Israel come nigh the tabernacle of the congregation,
least they bear sin and die.

But the Levites shall do the service of the tabernacle of the congregation,
and they shall bear their iniquity,
this shall be a statute forever among your generations,
that among the children of Israel they have no inheritance, (to wit, the Levites.)

But the tithes of the children of Israel,
which they offered an heave-offering unto the Lord,
I have given to the Levites to inherit,
for they have no other inheritance among the children of Israel.

And the Lord said unto Moses, '`thus speak unto the Levites,
when ye take of the children of Israel`'s tithes,
which I have given you from them for your inheritance,
when ye shall offer an heave-offering of it for the Lord,
even a tenth part of the tithe.`'

'`And this your heave-offering shall be reckoned to you,
as the corn of the threshing-floor,`' etc.

'`And thus you also shall offer an heave-offering unto the Lord,
of all your tithes which ye receive of the children of Israel,
and ye shall give thereof the Lord`'s heave-offering to Aaron the priest.`'
Numb. 18.

'`The place which the Lord your God shall choose
out of all your tribes to put his name there,
even unto his habitation shall he seek, and thither shalt thou come,
and thither shall you bring your offerings and sacrifices,
and your tithes and heave-offerings of your hands,`' etc.

'`And there you shall eat before the Lord your God,
and ye shall rejoice in all that you put your hands unto, ye and your households,
wherein the Lord thy God hath blessed thee.
For ye are not as yet come to the rest, etc.--But when ye go over Jordan,
and dwell in the land which the Lord your God giveth you to inherit,
and he giveth you rest from all your enemies round about you,
so that ye dwell in safety.--Then there shall be a place which
the Lord your God shall choose to cause his name to dwell there,
thither shall ye bring your offerings, sacrifices, tithes,
and your heave-offerings of your hands, etc. unto the Lord.
--And ye shall rejoice before the Lord, ye and your sons, and your daughters,
and your men-servants and maid-servants, and Levi that is within your gates;
forasmuch as he hath no part nor inheritance with you his brethren.
The Lord is his inheritance according as the Lord promised him;
for the Lord separated the tribe of Levi, to bear the ark of the covenant of the Lord,
and to stand before the Lord, to minister unto him, and to bless in his name.`'
Deut 12. Deut 10:8-9.

'`And thou mayest not eat within thy gates the tithes of thy corn, or of the wine,
or of the oil, or of the firstling of thy had, or of thy flock.
But thou shalt eat them before the Lord thy God,
in the place which the Lord thy God shall choose, thou and thy son, and thy daughter,
and thy man-servant, and thy maid-servant, and the Levite that is within thy gates,
and thou shalt rejoice before the Lord thy God,
in all thou puttest thy hands unto.`' Duet. 12:17,26.

'`And take heed to thyself that thou forsake not the Levite, etc.
And thou must eat flesh within thy gates, or what thou desirest:
only the holy things which thou hast, and thy vows, thou shalt take,
and go unto the place which the Lord thy God shall choose,
observe and hear all these words which I command thee.`'

And in Deut. 14.
'`Thou shalt truly tithe all the increase of thy seed year by year,
and thou shalt eat it before the Lord thy God,
in the place which he shall choose to place his name there, the tithe of thy corn,
of thy wine, of thy oil, and the firstlings of thy herds, and of thy flocks,
that thou mayest learn to fear the Lord thy God always.--And
if the way be too long for thee,
so that thou art not able to carry it; or if the place be too far from thee,
which the Lord thy God shall choose, and set his name there;
when the Lord thy God hath blessed thee.^
footnote:[Here was their own choice in laying out their tithe-money.]
Then thou shalt turn it into money, and bind up the money in thy hand,
and shalt go unto the place which the Lord thy God shall choose.--And
thou shalt bestow that money for whatsoever thy soul desireth after,
for oxen, or for sheep, or for wine, or for strong drink,
or for whatsoever thy soul desires; and thou shalt eat it before the Lord thy God,
and thou shalt rejoice, thou and thy household.
And the Levite that is within thy gates, thou shalt not forsake him,
for he hath no part nor inheritance with thee.--At the end of three
years thou shalt bring forth all the tithe of thine increase,
the same year thou shalt lay it up within thy gates.--And the Levite, and the stranger,
and the fatherless, and the widow, which are within thy gates, shall come;
and shall eat and be satisfied, that the Lord thy God may bless thee,
in all the works of thy hands which thou dost.`' Duet. 14:22, to the end.

And also, in Deut. 26.
'`When thou hast made an end of tithing all, the tithes of the increase, the third year,
which is the year of tithing, and hast given it unto the Levite, the stranger,
the fatherless, and the widow, that they may eat within thy gates and be filled.
Then thou shalt say before the Lord thy God,
I have brought away the hallowed things out of my house,
and also given them unto the Levite, and unto the stranger, to the fatherless,
and to the widow, according to thy commandments, which thou hast commanded me,`' etc.
Here you may see the laws and the commandments of God concerning tithes,
and who they were to. Duet. 26:12-13.

And you may see how that the tithes were to be brought
to the chambers of the house of God at Jerusalem. Neh. 10:37-38.

And in 2 Chron. 31:11. how the chambers for the tithes,
were in the house of the Lord,
which was the place the Lord had chosen according to Moses.

And in Mal. 3. it was called a robbing of God and the whole nation,
when they did not bring in their tithes into the storehouse,
that there might be meat in his house, so it was a wronging of Levi, the stranger,
the widow, the fatherless, from their right, for the tithes of the land were the Lord`'s,
and for Levi, the widow, stranger, and fatherless, and so if they did not bring them in,
they robbed God in his tithes and offerings,
and walked contrary to the law and command of God, therefore, says he,
ye are cursed with a curse, for ye have robbed me, even this whole nation.

And the apostle saith,
'`cursed is every one that continueth not in all things which is written
in the book of the law to do them.`' Gal. 3:10. and Duet. 27:26.
'`But no man is justified by the works of the law in the sight of God,
for the just shall live by faith; for as many as are of the works of the law,
are under the curse.`' Gal. 3:11.

And Christ has redeemed us from under the curse of the law,
so they are not under that curse that do not pay tithes now.
And the apostle saith, '`that no than is justified by the works of the law,
but by the faith of Christ Jesus, even as we have believed in Christ Jesus,
that we might be justified by the faith of Christ,
and not by the works of the law:`' and the apostle saith,
'`by the works of the law no flesh shall be justified in the sight
of God:`' therefore you are not justified by the law,
of tithes and offerings, nor outward circumcision in the sight of God. Gal. 2:8.

And Christ cried, '`woe unto you scribes and pharisees hypocrites, ye pay tithe of mint,
anise, and cumin, and have omitted the weighty matters of the law, judgment, mercy,
and faith, these things ye ought to have done,
and not to have left the other undone.`' Mat. 23:23. and Luke 11:42.

And in Gen. 14:20. '`when Melchizedek, king of Salem, brought forth bread and wine,
he was the priest of the most high God, and he blessed Abraham,
and Abraham gave him the tenths of all that he had taken
in the spoil,`' as also ye may see in Heb. 7:4.

Now did ever Abraham pay tithes to Melchizedek after this time?
Or did he ever pay Melchizedek tithes before of his own yearly increase?
But now of the spoil of the war?

And did ever any of the kings or judges pay the tenths of their spoil of the wars afterwards?

'`And Jacob vowed a vow, saying, if God will be with me,
and keep me in this way that I go, and will give me bread to eat, and raiment to put on;
so I come again to my father`'s house in peace, then shall the Lord be my God:
and this stone which I have set up for a pillar, shall be God`'s house,
and of all that thou shalt give me, I will surely give the tenth unto thee.`'

Now where did ever Jacob pay tithes?
Or the children of Israel in Egypt?
Until they came out of Egypt and received his law,
for this was only Jacob`'s condition and free vow, not a command from God,
as you may see in Gen. 28:20-22.

And in Heb. 7.
when Abraham returned from the slaughter of the kings, Melchizedek, king of Salem,
priest of the most high God, met him and blessed him,
to whom also Abraham gave the tenths of all the spoils,
so this was not of the increase of his personal estate,
neither did other kings or judges, (as I said before,) follow this example,
to give the tenth of their spoils that they had gotten in war.
Neither did Abraham lay this as a command of God, upon his own family to pay tithes,
either of their personal estates, or of the wars to Melchizedek afterwards.
Neither do we read that Jacob, or his children, did pay tithes,
till after they came out of Egypt, as before it is said, by the law of God:
but the apostle saith, as I may so say, '`Levi, also, who received tithes,
paid tithes in Abraham, for he was yet in the loins of his father,
when Melchizedek met him who received the tithes: and as for Melchizedek,
his descent is not counted from them:`' so here the
apostle goes to cut off Levi who received tithes,
and his priesthood, and place it upon Levi, as paying tithes,
(in Abraham.) For the apostle saith, '`verily they that were of the sons of Levi,
who receive the office of the priesthood,
have a commandment to take tithes of the people according to the law,
that is of their brethren,
though they came out of the loins of Abraham,`' so here
is the law and commandment to take tithes of their brethren,
and not of them that was not their brethren.

And the apostle saith, '`if perfection were by the Levitical priesthood,
for under it the people received the law,
what further need was there that another priest should arise, (to wit,
Christ,) after the order of Melchizedek, and not after the order of Aaron,
who had a law and a commandment to take tithes.`' For the apostle saith,
the priesthood being changed, there is made of necessity a change also of the law,
for there is a disannulling of the commandment going before,
and so the priesthood changed, and the law changed by which he was made,
and the commandment disannulled that gave him his tithes; for it is evident,
that our Lord Jesus Christ sprang out of Judah, of which tribe,
Moses speaks nothing concerning the priesthood, and Christ is made a priest,
not after the order of Aaron: and yet it is far more evident,
for that after the similitude of Melchizedek, there arises another priest, (to wit,
Christ,) who is made not after the law of a carnal commandment,
(as the other priests were that took tithes,) but after the power of an endless life,
for this law of the carnal commandment, commanded all these carnal things, tithes,
offerings, to be given to Levi`'s priesthood: and therefore the apostle saith,
'`the law is changed by which the priesthood was made,
and the priesthood is changed:`' and the apostle saith,
'`there is a disannulling the commandment going before,
for the weakness and unprofitableness thereof;`' so here the apostle
notes both the weakness and unprofitableness of that law of tithes.
Moreover, he saith, '`the law made nothing perfect,
but the bringing in of a better hope did, (to wit,
Christ,) by the which we draw nigh unto God,
now Christ our high priest was made with an oath,
but the priesthood under the law was made without an oath,`'
and so Christ performs God`'s oath and fulfils it,
and so ends oaths and swearing, and forbids them.

For the Lord swore, and will not repent,
thou art a priest forever after the order of Melchizedek, to wit; Christ,
by so much was Jesus made a surety of a better testament than the Old Testament,
because Christ continueth ever, he hath an unchangeable priesthood,
and the Levites`' priesthood is changed, and their law and command:
so the apostle did not intend here that people should
hold up Aaron`'s priesthood and tithes,
but he shews a change of the law by which the priesthood was made,
and a change of the priesthood, and a disannulling the command,
and setting up Christ and his priesthood that is unchangeable;
and shewing the unprofitableness, and the weakness of the law, and the commandment,
and the first priesthood, and how it made nothing perfect;
but the gospel brought people to Christ the better hope,
which purified them as he is pure, through which they drew nigh to God.

Now all the tithes by the law of God and his commandment,
the children of Israel were to pay to the Levites,
and the Levites were to offer up the tenths of the heave-offerings to the Lord.
But Christ Jesus, it is said of him, '`lo I come to do thy will O God,
to take away the first, +++[+++mark,]
that I may establish the second,
by the which will we are sanctified through the offering
of the body of Jesus once for all,
once for all their offerings.`' So he has ended all the offerings,
by offering up his own body, to wit, the offering of tithes, and all other offerings;
and these offerers the priests; and so he has taken away the first priesthood, his law,
and command, and his tithes, he has taken away his altar, and temple, his tabernacle,
his sanctuary, and all his offices and services; and all the Levitical priests,
offices and services,
for the first priesthood had his tithes for his service at the tabernacle, altar,
sanctuary, and keeping the charge of all holy things:
but all these things Christ has taken away, and has taken away his priesthood,
and so has taken away his tithes, his maintenance,
and taken away his offices and offerings, and his charge, and he hath discharged him,
and so has changed his law, and disannulled his commandment,
and so all is fallen to the ground,
for God will have no pleasure in these offerings which were offered by the law;
but Christ is come, as in the volume of the book it is written of him,
'`to do the will of God, he taketh away the first, that he may establish the second;
first priesthood, first covenant, with all his tithes and offerings.`'

For Christ, after he had offered one sacrifice for sins,
forever sat down at the right hand of God,
so this one sacrifice has ended both sacrifices and sacrificers.

And also the tithes, their sacrifices, offerings, and maintenance in the time of the law,
which made none perfect,
'`for by one offering of Christ he hath perfected
forever them that are sanctified,`' +++[+++mark, forever.] Heb. 10.

And the Levites or priests, that took the tithes for the services,
these stood daily offering, oftentimes, the same sacrifices,
which can never take away sins; but Christ,
after he had offered up one sacrifice for sins forever,
sat down at the right hand of God,
who by this offering ended the first priest and his daily sacrifices. Heb. 9:19.
And Moses sprinkled the book and the people with blood:
but how much more shall the blood of Christ, through the eternal spirit,
offer up himself without spot to God, purge your consciences from dead works,
to serve the living God.
So Christ is the Mediator of the New Testament,
and redeems from under the transgression of the first, and ends it,
and sprinkles the consciences and the hearts of his people with his blood,
and ends the blood of the sacrifices which was offered and shed,
which the people were sprinkled withal.
And the Levites had the tenths for their service; but Christ`'s blood which was shed,
is the blood of the New Testament, which ends the blood of bulls and goats,
and the Old Testament, which were sprinkled with their blood,
and with which blood of Jesus the hearts and consciences
of people are sprinkled from their dead works,
to serve the living God.
And the apostle saith, '`the first covenant had ordinances of divine services,
and a worldly sanctuary made with hands;`' and he saith,
while the first tabernacle was standing, the holiest of all was not yet made manifest;
but Christ being come, is an high priest of good things,
by a greater and more perfect tabernacle, not made with hands, that is to say,
not of this building of Aaron`'s and Levi`'s law, first covenant, first testament,
with their carnal ordinances, worldly sanctuary, tithes, heave-offerings,
etc. nor outward temple at Jerusalem, where they brought their tithes unto.
So this worldly sanctuary, worldly temple, carnal ordinances,
and the outward city Jerusalem, where they brought their tithes unto,
and the priest that had the tithes for their service,
and had no other inheritance in the land; all this Christ came to end,
who is not of this building that was made with hands, nor after the order of Aaron,
but of a more perfect tabernacle.
And so the first covenant waxeth old and decays, and is ready to vanish away:
and so he is the Mediator of the New Testament, and so he ends the old with the covenant,
and their carnal ordinances and sanctuary, their altar,
and the priests of Levi and Aaron, and their order,
and all their tithes which was their maintenance.
So tithes are not their maintenance now from God; for the law by which they were made,
is taken away; so their office and service is taken away,
for which tithes was given them; for the tribe of Levi,
which had no portion in the land by the law and command of God,
but the tithes for his service.
Now the law, and service, and priesthood, and tithes, and offerings, and covenant,
and order, and sanctuary, and tabernacle and testimony being taken away,
and command that gave them the tithes and offerings,
they may labour and buy a portion of land, for there is no tithes for them;
and the apostle saith, '`he that will not work, must not eat.`'

Now in the time of the law, and command of God for tithes,
Levi the priest was not to eat it at all, nor to put it in his own particular barn,
but the people were to carry it up to Jerusalem, which was the place the Lord did choose,
and there the high priest was to offer up his heave-offerings of it, his tenth,
and the Levite must not eat all the tithes himself, but the widows, fatherless,
strangers, and the persons that gave it him, as you may see in Duet. 12:18.

For they were not to eat it within their gates,
but they were to eat at the place where the Lord did choose, and rejoice before the Lord,
their sons and daughters, and maid-servants, and men-servants, and the strangers,
and the fatherless, and widow, that is within thy gates shall come,
and shall eat and be satisfied, that the Lord thy God may bless thee,
so all these must eat of the tithes with Levi,
(which had no part nor inheritance with the children of Israel,) but as I said before,
Christ has ended and changed the Levitical priesthood, and his law that commanded tithes,
and the high priest`'s heave-offering of them,
by the offering up of himself once for all,
he has ended both the offerings and priest`'s services,
so Levi has no law to take tithes and wages, seeing he has no service for them;
blessed be God who has sent his son, which is over the household of God,
the household of faith, and of the Jews in spirit,
as Moses was over the household of the outward Jews, with their tithes and offerings,
and carnal ordinances, and outward temples, which all are put down by Christ,
who remains a priest forever, not after the order of Aaron,
but after the order of Melchizedek.

And they were blessed that brought their tithes to the place which God had chosen,
and did eat them there with Levi, and the sons, and daughters, men-servants,
maid-servants, strangers, fatherless, and widows, as in Deut. 14.

And they were cursed that did not, for they that did not,
robbed God and the whole nation, as in Mal. 3. as it is said before.

And the apostle saith,
'`cursed is every one that continueth not in all things which are
written in the book of the law to do them;`' so you that take tithes,
pretending the law and a command in scripture, and do not carry them to Jerusalem;
and if it had been too far for you to carry it thither, to turn into money;
the place which the Lord God had chosen, which was the place of offering,
where the high priest must have his heave-offering out of them, and the widows,
strangers, fatherless, sons, and daughters, men-servants, and maid-servants,
and them that gave them, all might eat and praise the Lord together.
Now if you have not continued in all these things written in the book of the law,
and done them according to the law; if you have not,
cursed is every one that continues not in all things
which is written in the book of the law to do them.
But they that be of faith, are blessed with faithful Abraham, not as Levi,
that payed tithes in Abraham, which after had a law,
for the apostle cuts off the outward circumcision in Abraham,
and so the law of tithes to Levi in Abraham,
for the promise that Abraham should be heir of the world,
was not to Abraham and his seed through the law, but through the righteousness of faith,
and faith was reckoned to Abraham for righteousness, when he was in uncircumcision,
and not in circumcision.
Here the apostle cuts off, not only the Levitical priesthood and his law,
but the circumcision and his law. Rom. 4.

And the apostle saith,
'`for as many as are of the works of the law are under the curse.`'
Gal. 3:16.
But Christ has redeemed us from under the curse of the law,
being made a curse for us;
that the blessings of Abraham might come upon the Gentiles through Jesus Christ,
that we might receive the promise of the spirit through faith.

All these outward things, tithes, offerings, and other shadows in the first covenant,
held up by carnal ordinances,
imposed on the Jews until the time of reformation by Christ;
so their law is called a school-master, and it served till the seed came;
and a child differs nothing from a servant, but is under tutors and governors,
until the time appointed of the Father; +++[+++mark,]
then they were not always to be there in that state; even so we, when we were children,
were in bondage under the elements of the world; now these outward things,
the apostle calls them, Gal.
iv. the world`'s elements; but when the fulness of their time was come,
God sent forth his Son made of a woman, made under the law,
to redeem them that were under the law, that we might receive the adoption of sons;
and because ye are sons +++[+++mark,]
God hath sent forth the spirit of his Son into your hearts, crying Abba Father,
wherefore thou art no more a servant but a son, and if a son,
then an heir of God through Christ; so all that witness this,
witness the time of his Father`'s appointing, and the fulness of his time is come,
and the time of reformation;
and they are redeemed out of bondage from under the world`'s elements,
and they are redeemed from under the law, priest, tithes, and offerings,
by him that is made under the law, and so from under the curse,
by him that became a curse for us, and can say,
'`Christ is the end of the law for righteousness sake, to every one that believes.`'

So all the faithful walk in the steps of that faith of our father Abraham,
which he had before he was circumcised;
for the promise that he should be heir of the world, was not to Abraham,
or to his seed through the law, but through the righteousness of faith;
and here the apostle cuts off the law of circumcision,
and also the law by which the priest Levi was made,
and received his tithes and offerings,
and so the justification is in the faith of Christ,
and not by the works of the law that held up circumcision,
nor the law by which the Levitical priesthood was made, and all his services, tithes,
and maintenances for the priest and his services and maintenance, tithes and law,
is put down and changed by Christ, who remains a priest forever;
who had a better sacrifice than all those in the first covenant;
but Christ is entered by his own blood into the holy place, that is not made with hands,
as the Levites`' chief priest did, which were but figures of the true,
but Christ the substance, is entered into heaven itself,
having obtained eternal redemption for us,
and now to appear in the presence of God for us,
wherefore he is able to save them to the utmost, that come unto God by him;
seeing he ever lives to make intercession for them;
for such an high priest became us believers and true christians, who is holy, harmless,
undefiled, separate from sinners, and is made higher than the heavens;
so we need not daily those high priests that were made by the law,
who offered up sacrifices for their own sins, and then for the people,
who had tithes for their wages and maintenance;
for Christ offered up himself once for all, and ended all outward offering;
the law made high priests, who have infirmities,
but the word of an oath which was since the law, maketh the Son,
who is consecrated and perfected forevermore. Heb. 7:28.
Now of things which were spoken, this is the sum;
we have such an high priest, (to wit, Christ,) who has ended Aaron`'s priesthood,
and his tithes, law, and offerings,
who is set on the right hand of the throne of the majesty in the heavens.
And is a minister of the sanctuary,
and of the true tabernacle which the Lord hath pitched, and not man.
And so hath obtained a more excellent ministry than that of Moses and Levi,
by how much more also he is the Mediator of a better covenant than the first,
which is established upon better promises, glory to God forever.

And whereas you do allege what Christ said to the pharisees in Luke 11:42. which saith,
'`woe be unto you pharisees, for ye tithe mint and rue, and all manner of herbs,
and pass over judgment and the love of God, these ought you to have done,
and not to leave the other undone;`' to which I say,
these things was before Christ was offered up,
and the tenths of tenths was a heave-offering,
and Christ bid them go offer to the priest for their cleansing,
for he did not come to break the law, but to fulfill every jot and tittle of it;
but when Christ was offered up once for all the offerings,
then the high priests`' offerings and Levi`'s tithe of mint and rue, etc. was ended.
And they that preached the gospel, said the Levitical priesthood was changed,
and the law was changed, by which he was made,
and the command was disannulled that gave him his tithes for his services and offerings;
and Christ was preached, and set up the unchangeable priest,
and so Christ the Priest by offering up himself,
has ended the first priesthood and his offerings; then Christ said to his apostles,
ministers, and messengers, '`freely ye have received,
freely give,`' so people may keep their tithe of mint, and their rue,
and other herbs and things to themselves,
for Christ has taken away the law that gave them:
for the apostle was to go without bag or scrip; therefore,
they were not to take people`'s mints and herbs,
as the Levitical priesthood did by the law; but Christ has changed this law and him,
and put down his office; therefore, Levi has no power to take them of people,
and therefore, people may keep them to themselves;
for where there is no law there is no transgression for not paying of them;
but Christ remains an unchangeable Priest forever, who by the offering up himself,
has ended all their offerings, and all people must come to God by him,
who is consecrated a new and living way. Heb. 10.

So Christ has ended old Levi`'s priesthood, with his old wages,
his old tithes and offerings, and his old altars; and his old temple,
and his old carnal ordinances, and his old offerings, and his old washings,
and old tabernacle made with hands, and his old testament,
which is sprinkled with the blood of bulls and goats, and his old covenant,
and the old worldly sanctuary, and the old shadows and sacrifices: Christ, I say,
has ended all these things by the one offering and sacrificing of himself once for all,
and is set down at the right hand of God above them all, and over them all;
and none comes to God but through him, and by him,
and Christ hath appeared to put away sin, by the sacrificing of himself;
and after Christ had offered one sacrifice for sins,
he forever sat down at the right hand of God,
so he hath ended the Levitical priesthood that offered up for their own sins,
and then for the sins of the people;
so Christ I say has ended their work and their service;
so likewise he has ended the tithes which was for their wages.
And every one`'s faith is to stand in Christ the author of it, and to live by it,
and walk by it, if they be justified, and come into the heirship with faithful Abraham.

And after Christ was risen, he said unto his disciples, Luke xxiv.
'`while I was yet with you, I told you,
that all things must be fulfilled which were written in the law of Moses,
and in the prophets,
and in the psalms concerning me;`' so the law and the prophets are fulfilled in Christ,
and he is the end of them; who is the first and the last, the beginning and the ending,
the amen.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 1st day of the 7th month, 1676.

[.blurb]
=== Postscript.

'`Unto the tribes of Levi, Moses gave no inheritance,
the Lord God of Israel was their inheritance,
as he said unto them,`' in Num. 18:20-21.

'`And behold I have given the children of Levi, all the tenths in Israel,
for an inheritance for their service,
even the service of the tabernacle of the congregation:`'
so the eleven tribes had the land by lot,
as in Joshua, 13. 14.

So the law served, and the priests did their service about the tabernacle,
till Christ came and was offered up.

For when the fulness of time was come, God sent forth his.
Son, made of a woman, and made under the law, to redeem them that were under the law,
that they might receive the adoption of sons, which many witness at this day.

And so Christ has ended the Levitical priesthood, and his service,
and has taken away the first priesthood, that he may establish the second,
who is made higher than the heavens,
who hath not entered into the worldly sanctuary or tabernacle,
but into the holy place by his own blood.

'`And has ended the first covenant, and has made the first old,
and it was ready to vanish away, in the days of the apostles.`' Heb. 8.

And so Christ Jesus the heavenly priest,
hath discharged Levi of his services at the altar, tabernacle, and temple,
and of his outward ark, and of all his offerings and sacrifices,
and his heave-offerings of his tithes, which he was to shake to and fro, east, west,
north, and south, which was a type of Christ`'s offering up himself,
once for all their offerings.

And so Christ having discharged him of his offices, and taken away his temple, altar,
tabernacle, sanctuary, blood of bulls and goats, and tithes,
the priest`'s wages and portion for his service,
and his offerings which he was to feed upon,
which had no lot nor inheritance in the land.

Now he may take himself a plantation, or buy himself land,
for Christ has taken away his offerings and his law,
and the command that gave him his tithes, for he must expect no more tithes.

So now God has no work for him at outward tabernacles, nor to offer outward sacrifices;
for he has no law nor power from God to take wages, to wit, tithes,
for any such services.

For Christ has offered up himself once for all their offerings, and is a priest,
not after the order of Aaron, but after the order of Melchizedek.
So Levi was to have no portion but the tenths of Israel.

Now Christ has ended this Levitical priesthood and his tenths, for his service,
which he served in it by the law, till the seed Christ came,
which in the fulness of time,
that God sent forth his Son which was the time of reformation out of those things,
and a time to take away the first, to establish the second, the everlasting priest,
and the everlasting covenant.

And he took away the circumcision in the flesh,
and he established the circumcision in the spirit.

And so if Levi should plead for the tenths of Israel now, he is an usurper of authority,
for he has no law nor command from God, for so doing.

And Christ has died for all, and enlightened all men;
that all might believe in the light, and become children of the light.

And his gospel of salvation is preached unto all men, and to every creature under heaven;
and the grace of God has appeared to all men, which is the true christian`'s teacher.

And so all the believers in the light, are the children of the light,
and are grafted into Christ that died for them,
and eats the flesh and drinks the blood of the heavenly man,
and so feeds upon Christ Jesus their sacrifice.

And so all the circumcised in heart, men and women, feed upon the sacrifice;
and are the royal priesthood, offering up spiritual sacrifices.

And God has made us (to wit, the true church,) kings and priests;
and has redeemed us from the earth, so to reign over the devil and the earth,
and so to offer up spiritual sacrifices.

And these priests that God has made, offers up no earthly sacrifices, therefore,
they will not have earthly tithes, for they see the Levitical priesthood taken away,
that took them, which was the first.

And they do see Christ, the second established, a priest forever,
made higher than the heavens, who is over all from everlasting to everlasting,
the first and last.

[.signed-section-signature]
G+++.+++ F.
