== The Spiritual Man Christ Jesus

[.heading-continuation-blurb]
The Blessed Seed, Light of Life, Purger of Conscience,
Healer of Nations, and Restorer of Mankind.

[.heading-continuation-blurb]
How all Nations are blessed in the Seed Christ Jesus,
that bruiseth the Head of the Serpent and his Seed that brought the Curse;
and something further, how all men and women in Adam,
in the Transgression, their Spirits are dark,
and how Christ the Spiritual Man enlightens their Spirits (their Candles,)
and how that no meat that goes into the belly defiles the man;
and how Christ is the Purger of the Soul, Conscience, and Heart,
and Mind, of all those evil things that have gotten into man and woman by Transgression,
who bruises the Head of the Serpent, and makes all things clean to man,
and brings him to the blessed state as he was in at the beginning. --By G. F.

The Lord said unto Abraham; '`because thou hast obeyed my voice,
all nations of the earth shall be blessed in thy seed.`' Gen. 22:16.

Now this was the promise of God to Abraham, of whom Christ came according to the flesh.

So the promise was not to seeds, as many, but unto one seed which is Christ;
which seed bruises the head of the serpent.

And so all people and nations must be in this seed,
as they have been in the seed of the serpent, which brought the curse, woe, and misery,
and darkness upon mankind, if they have the blessing and promise.

For as the apostle said, '`every one which hath received Christ, which was the seed,
they must walk in him.`'

For Abraham had obeyed God, first in forsaking his father`'s house and native country,
ways, religions, and worships of idolatry: and he obeyed God in that,
and in offering up his only son; and in many other things as God commanded him,
as you may see in Genesis.

And God said unto him, '`walk before me,
and be thou perfect:`' and so must all nations of people,
forsake all their native country, religions, and ways which they have made,
and idolatries, and come into the seed before they can be perfect:
for the cry is amongst them, and hath been,
there is no perfection here on this side the grave.

But I say nay, the perfection is in the seed, which brought Abraham to obey,
which the promise is unto, in which all nations are blest, in whom the perfection is.

And so all nations must walk in this seed before God, if they will be perfect and,
blessed; which seed bruises the head of the devil, that made man and woman imperfect.

In which seed all know their election before the world began, and their foundation.

And this is the seed which all the prophets gave testimony of,
and the apostle preached it.
(Christ Jesus.)

And now if all the world and Christendom have all
the words given forth from the seed in Abraham,
the prophets, and David, and all the apostles, and have not the seed,
they have but the sheep`'s clothing, the outside, the wool,
and are feeding upon the words.

But Christ saith, except you eat my flesh, and drink my blood, ye have no life in you:
for the wool is but the outside and clothing of the sheep; it is not flesh and blood.

And therefore, Christ saith, '`except you eat my flesh, and drink my blood,
you have no life in you;`' and his flesh and blood is not wool, the outside,
the sheep`'s clothing.

So they may have all the words of Christ, and the prophets and apostles,
and yet feed upon the dust like the serpent, have the sheep`'s clothing,
but have no life in them; except they eat the flesh of Christ, and drink his blood,
who came down from heaven.

For as Christ said, '`search the scriptures, for they do testify of me,
but you will not come unto me that you might have life.`'

So Christ is not the writings, but the thing which the writings testifies of,
nor flesh and blood is not wool nor clothing.

Now all people are dark, as they are in Adam in the transgression,
and dead from that image, righteousness, and holiness, that he was made in.

And David said, '`the Lord had enlightened his candle,`' and the spirit of man is called,
'`the candle of the Lord;`' and whilst man is in his natural state,
he knows not the things of God, though the natural man with his natural spirit,
may know the things in themselves that be natural, but he cannot know the things of God,
but as the Lord enlightens his candle.

For as natural men and women in the night cannot see what is in their houses,
without a candle which they light at a natural fire,
which gives light to the natural eye:
so man`'s spirit is lighted by God and Christ`'s divine light and fire,
by which they see with the heavenly eye what is in their house and inward parts.

For all the household of Adam in the transgression are dark, both in their minds, spirit,
and soul.

And they that follow their own spirits, see nothing;
now every man that cometh into the world, being enlightened by Christ,
which is called the light of the world; and the light that enlightens every man,
and man`'s mind, soul and spirit, being turned to this light,
this divine light of the spiritual and heavenly man, enlightens his spirit, his candle;
then with this divine, heavenly light, which has enlightened his spirit, mind, and soul,
he finds the pearl in his own field, and then he keeps close to the Lord,
and in his counsel,
and goes and sells all that he has gathered with his own spirit in the darkness,
and in Adam in the fall, that he may purchase this field, and the pearl in it;
and the candle being lighted, he sees the leaven which has lain within him,
to leaven him up into the new living lump; and he sees the seed of the kingdom within.

For the parable of the woman that lost the piece of silver,
after she had lighted her candle at Christ`'s divine light, her mind, spirit and soul,
being turned to the divine light of Christ, she swept her own house with God`'s besom,
his power, and threw out the rubbage which was come in by transgression;
and so with this divine light found the divine silver, or treasure, in her own house.

So the natural man with his natural spirit, knows the things of the natural man,
and knows not the things of God; but his spirit being enlightened,
which is the candle of the Lord, with this divine light,
it gives him the knowledge of the divine and heavenly things, and of his kingdom,
and the world that has no end.

So here is no more saying, '`lo here, or lo there is the kingdom,
as they do that hate his light; for they that hate the divine light of Christ,
hate that which should light their candle, their spirit.`'

And therefore, as it is said,
'`how oft is the candle of the wicked put out,`' for when they turn from the light,
and disobey the truth, as Adam, and the Jews, and those called christians,
they follow their own spirits, their candle being put out, and see nothing;
but one cries, lo here, and another cries, lo there, in the dark; and one says,
lo here is Christ the way; and another cries, there is the way; but all in the dark.

But none sees Christ, or sees the way, or sees the word, but whose minds, and spirits,
and souls are turned to the divine light of Christ, which enlightens their spirits,
their candle, and then they see Christ the way, the truth, and the life,
and the light gives them the knowledge that shines in their hearts,
that has enlightened their spirits.

Now disobedience, and loving the darkness rather than the light, puts out this candle,
and so the candle of the wicked is often put out.

But they that love the light which enlightens their souls, minds, and spirits,
it gives them the knowledge of the glory of God in the face of Christ Jesus;
so that they come to see Christ, who is the mystery, and follow him,
and be his disciples.

Now in the days of Christ there was a pharisee bid him to dinner,
Matt. 15. and Mark 7.
and the pharisee wondered at Christ`'s disciples eating with unwashed hands.

But Christ said, '`ye fools, did not he that made that which is without,
make that which is within also; therefore,
give alms of all those things which ye have.`' Mark 7:18.
'`for behold all things, are clean unto you.`'

And in Mark 7.
Christ spoke unto the people this parable, '`there is nothing from without a man,
that entering into him can defile him; but the things which come out of him,
those are they that defile the man.`'

And again, Christ said unto his disciples, '`What are ye without understanding also?
Do ye not know, that whatsoever thing from without, entereth into a man,
it cannot defile him.`'

'`Because it entereth not into his heart, but into the belly,
and goeth out into the draught, which is the purging of all meats.`'

'`But that which cometh out of the man, that defileth the man, for from within,
even out of the hearts of men, proceed evil thoughts, adulteries, fornications, murders,
thefts, covetousness, wickedness, deceit, lasciviousness, an evil eye, backbiting,
blasphemy, pride, foolishness.
All these evil things come from within, and defile the man,`' which are the evil things,
the sins which Christ purgeth.

And John the Baptist said, '`I indeed baptize you with water unto repentance;
but Christ that cometh after me, is mightier than I,
whose shoes I am not worthy to unloose, +++[+++or bear,]
he shall baptize you with the Holy Ghost, and with fire, whose fan is in his hand,
and he will thoroughly purge his flour, and gather his wheat into his garner,
and burn up the chaff with unquenchable fire.`'

So Christ is the purger of the heart, mind, soul, spirit, and conscience,
and the body inwardly; for Christ is mightier than John, in his conception, birth,
and power, and miracles.

And the draught purgeth all meats that goeth into the mouth, and so into the belly,
and so into the draught: and so whatsoever goeth into the mouth, doth not defile the man,
for he that is holy and pure, made that without, and made that within;
and all that he made was good and blessed.

And who may abide the day of his coming, and '`who shall stand when he appeareth,
for he is like a refiner`'s fire, and like fullers`' soap, and he shall sit as a refiner,
and purify of the sons of Levi, and purge +++[+++mark, purge,]
them as gold and silver, that they may offer an offering in righteousness.`' Mal. 3:3.

And in Heb. 9:14. '`Christ with his blood purge your consciencies
from dead works to serve the living God;`' so he is the purger
of the heart and conscience with his blood.

And in Heb. 1:3. '`when Christ by himself had purged our sins,
sat down at the right hand of God;`' so it is Christ that purgeth away our sins,
which are within.

'`And every branch, (saith Christ,) he purgeth,
that it may bring forth more fruit.`' John xv.

So Christ is the purger of the conscience and heart, soul and spirit, with his blood,
and purgeth away our sins.

And so they that look at Christ,
will not plead for a purgatory to purge them after death,
nor plead for a body of sin and death to the grave.

And Christ is the purger of the branches that is grafted into him,
'`that they may bring forth more fruit.`'

Now there is that which purgeth all meats,
through which the creature is not defiled by them;
so that the creature is not defiled by meats, for the draught purges them.

Now that which comes out of a man, defiles him, as is before mentioned,
and all these evil things has come into man by the fall and transgression;
for it was not in him in the beginning before the fall, when God made him in his image;
and therefore it is come into man and woman by transgression which has defiled them.

And now to have all these evil things purged out of man,
which has got into them by transgression, which has defiled his heart, his soul,
his mind, his conscience, his spirit; that which purges this out of him,
is the blood of Christ, who by his blood and fiery baptism hath purged out our sins,
and sanctifies us.

So they that be without understanding, pharisee-like,
know not that which purges all meats; and also know not Christ,
and is without the understanding of him who purges with his blood, the mind, heart, soul,
spirit, and conscience, with his blood, through which they come to serve the living God.

And all they that plead for a purgatory when they are dead, to purge them;
and they that plead for a body of death and sin to the grave, and forbid meats,
as if they should defile them, that goes into the belly, and so into the draught,
the purger that purges all meats, they are as blind as the Jews, chief priests,
and pharisees, and are as ignorant of him that purges the conscience, to wit,
Christ Jesus, the seed in whom all nations are blest,
and therein sanctified and reconciled to God, all things in heaven,
and all things in the earth, and receives his blessing and promise in the seed,
and sees all things is blest and clean to them, as they were in the beginning,
by Christ Jesus.

G+++.+++ F.

The 7th month, 1676.
