[.style-blurb, short="Christ`'s Parable of Dives and Lazarus"]
== Christ`'s Parable of Dives and Lazarus, for all called Christians, and others, to consider.

All people in Christendom, and elsewhere,
consider in your lifetime the parable of Christ, concerning the rich man,
and Lazarus the beggar.

For Christ saith, '`there was a certain rich man,
who was clothed in purple and fine linen, and fared sumptuously every day.`'

'`And there was a certain beggar named Lazarus, who lay at his gates, (to wit,
at the rich man`'s,) full of sores;
and desiring to be fed with the crumbs which fell from the rich man`'s table, (to wit,
the poor man Lazarus,) moreover, the dogs came and licked the sores of the poor man.`'

'`And it came to pass that the beggar died,
and was carried by the angels into Abraham`'s bosom.`'

'`The rich man also died, and was buried; and in hell he lifted up his eyes,
being in torment, and seeth Abraham afar off, and Lazarus in his bosom:
and the rich man cried, and said, father Abraham, have mercy on me, and send Lazarus,
(to wit, the beggar,) that he may dip the tip of his finger in water, and cool my tongue,
(to wit, the rich man`'s,) for I am tormented in this flame.
But Abraham said to the rich man, son,
remember that thou in thy lifetime received thy good things, and hadst thy pleasure;
and likewise Lazarus the beggar, the evil things, but now he is comforted,
and thou art tormented.`'

'`And besides all this, between us and you there is a great gulf fixed, (to wit,
Abraham and the beggar,
and the rich man in hell,) so that they who would pass from hence to you cannot,
neither can they pass to us, that would come from thence,`' (to wit,
the rich man that hath lived in pleasures upon the earth.)

'`Then he said, (to wit, the rich man in hell,) I pray thee, therefore, father,
that thou wouldst send him to my father`'s house, for I have five brethren,
that he may testify unto them, lest they also come into this place of torment.`'

'`And Abraham said unto the rich man in hell, they have Moses and the prophets,
let them hear them,`' (to wit, while they be upon the earth.)

And the rich man in hell said, '`my father Abraham,
but if one went unto them from the dead, they will repent; and Abraham said unto him,
if they hear not Moses, nor the prophets, neither will they be persuaded,
though one come from the dead.`' Luke xvi.

Nor now they that will not hear Christ and his gospel;
and if they will not hear Christ and his gospel,
they will not hear one that cometh from the dead:
so the christians in profession without possession,
are like the Jews that would not hear Moses and the prophets, nor one come from the dead.

But the Jews did seek to put Lazarus to death,
(whom Christ had raised from the dead,) because by reason of Lazarus,
much people were turned unto Christ, and did believe on him,
that Christ had raised him from the dead.
They were as mad against Christ and his miracles, as they are now against his light,
which is his life in the word.

Now all ye great and rich men upon the earth, that fare sumptuously every day,
of what sort soever, Jews, Heathens, Turks, or Christians,
consider the parable of Christ on the rich man, who had not compassion on poor Lazarus;
and the rich man`'s kindred nor himself regarded not the law, nor the prophets,
neither would they regard one if he came from the dead,
to tell them of the misery that this rich man was in, when he was in hell.

Now you that are called christians, and others, that fare sumptuously every day,
that be the rich men, do you regard the poor Lazaruses?
Do you regard the life and practice of the law and prophets?
And do you regard the life of christianity,
and the life and practice as Christ and the apostles command?

But, have you not slighted God`'s messengers and prophets, and servants, sons,
and daughters, and hand-maids,
that have been moved of the Lord God to warn you in your lifetime,
of the torment and misery of hell fire that this
hard-hearted rich man fell into when he was dead.

And such as have exhorted you who are alive, and would have turned you to the Lord,
you have prisoned, persecuted and banished:
and do you not think that your end will be like this rich man`'s, when he died,
who went into hell fire?
And poor Lazarus, whom he had not compassion on, went into heaven.

And do you not think, that all these poor Lazaruses, that you have persecuted,
and do persecute, that when they die, they will not be carried into Abraham`'s bosom?
When in hell you are tormented, that you will cry like this rich man in hell,
to Abraham to send one of his poor Lazaruses to dip the tip of his finger in water,
to cool your tongues, which are scorched with the flames of hell fire?

But then consider what Abraham`'s answer will be to you,
you who have received the good things in your lifetime, and had your pleasure,
and the poor Lazaruses the evil things.

But Abraham tells you, though he calls you sons,
'`there is a great gulf betwixt you and him; and he cannot come to you,
neither can you come to him.`'

And Abraham will say unto you, '`remember,
how in your lifetime you fared sumptuously every day, and received the good things,
and likewise the poor Lazaruses the evil things from you,
who had no comfort amongst you.`'

But now the poor Lazaruses are comforted in Abraham`'s bosom, after they are dead,
and after you are dead, you are tormented in hell fire, for all your purple coats,
and gorgeous apparel, and your faring sumptuously every day.

And therefore, all ye hard-hearted rich men, be warned,
and mind the law and the prophets, and Christ and the apostles,
and walk as they commanded; and mind the poor Lazaruses, and not talk only,
if you will escape hell fire: and this you must mind in your lifetime,
or else when ye are dead ye must go to hell fire, and there be tormented,
as the rich man was when he was dead, and could not come out to Abraham,
nor Abraham to him.

And do not you think that he was a jolly fellow, while he was upon the earth,
with his dogs and his sumptuous fare, and apparel of purple and fine linen.

Now this parable Christ spoke to the covetous pharisees, which justified themselves,
and derided Christ.

And therefore, consider, all ye rich men that are called christians,
and others that do fare sumptuously every day, and are clothed in purple and fine linen,
that deride the life that is in Christ,
which lighteth every man that comes into the world; do you regard the poor Lazaruses,
the poor beggars that lie in your gates full of sores?

And do you consider whither ye must go when ye die?
Do you think upon this rich man where he is?
And where poor Lazarus is?
You that receive the good things in your lifetime, remember now while you are alive,
and do not eat and drink without the fear of God, to make yourselves wanton,
lest you be lifted up, and regard not the poor,
and look loftily and disdainfully upon your fellow creatures that be in misery,
lest the time come that you come into torment with the rich man,
when they are comforted in Abraham`'s bosom.

For you hear what Christ said in his parable, and what Abraham saith:
Abraham tells the rich man that is tormented in hell,
that '`there is a great gulf fixed between the rich man in hell, and Lazarus and Abraham:
so that they who would pass from Abraham to the rich man in hell cannot,
neither can they from hell pass unto Abraham, that would come from thence.`'

So this doth manifest, that when the wicked die they go to hell;
so there is no purgatory, nor middle place, as some imagine:
and they in hell cannot pass to Abraham, nor Abraham to them,
so there is no prayers that will get them out of hell fire.

And therefore, consider ye this, that fare sumptuously every day,
and are clothed in your purple and fine linen, and regard not the poor,
lest the day of your visitation do pass over your heads,
and you do continue in your wickedness and die in your sins;
for the wicked must be turned into hell, and all that forget God.

For this rich man in hell cried unto Abraham to have mercy upon him,
and for him to send poor Lazarus that he might dip
the tip of his finger in water to cool his tongue;
for he was tormented in the flame in hell fire.

Now Abraham could shew him no mercy, that was in hell fire, nor Lazarus,
they could not comfort this rich man with as much water
as they could take up on the tip of their finger;
so there was no comfort to be shown to him.

And though Abraham called him son, this was a parable to the Jews,
who professed themselves children of Abraham, and did not do the works of Abraham.

So this parable may stand to them that profess themselves christians,
and do not the works of christianity.

And when they be in hell, what good will all their riches, and their sumptuous fare,
and their fine linen and purple do them?
When they live without mercy and compassion in their lifetime,
and without the fear of God, and go to hell fire, and be in torment when they die.

And therefore,
for them to see the poor despised beggar Lazarus in happiness in Abraham`'s bosom,
and a great gulf fixed between them in hell, and the poor that be in Abraham`'s bosom,
that Abraham and the beggar cannot pass to them in hell,
neither can they pass to them in heaven.

And therefore, what doth all your pleasures and sumptuous fare and apparel avail you,
whose dogs have more compassion upon the poor than you in your lifetime.

Abraham tells you the reason, how that there is a great gulf fixed between you and them,
as aforesaid: and therefore remember this in your lifetime, and be warned, and repent,
and while you have time prize it: this is the day of your visitation,
who live in pleasures and fulness, and wantonness, despising the poor,
and persecuting the just and innocent; and comforting yourselves with your pleasures,
and things of this world: and nourishing your hearts, as in a day of slaughter,
and living wantonly upon the earth.

And live neither according to the law of Moses, nor the prophets;
nor according to the gospel of Christ Jesus,
though they all tell you what misery will be your end, yet you will not hear them,
nor obey them.

And therefore, if you will not hear neither the gospel, the law, nor the prophets,
then hear what the rich man in hell saith to you in his torment, as in Luke xvi.

For neither Abraham nor Lazarus could help him, nor comfort him, nor show him any mercy,
who had shown no mercy in his lifetime.

So you may see plainly by Christ`'s own words, here is no purgatory or middle place;
but when the wicked die they go to hell, and the just are carried into Abraham`'s bosom.
with the angels.

And when this rich man could get no hope of any comfort in hell from Abraham and Lazarus,
he was so tormented, that he desired Abraham that he would send to his father`'s house;
for he had five brethren, that they might testify unto them,
lest they should come into that place of torment, to wit, hell.

And Abraham told the rich man in hell, '`that they had Moses and the prophets,
let them hear them.`'

So now you have Christ to hear, and his apostles,
and if you do not hear Christ`'s voice that speaks from heaven,
and follow him who is the way to God, the truth and the life.

Then consider and see if your way be not the rich man`'s to hell,
to his place of torment: but is it not your principle to say,
that there is no hearing Christ`'s voice whilst you are alive here upon the earth?

Oh therefore be warned, and be serious, and consider your latter end,
and now you have time prize it, lest you say, you had time, when it is past.

For if you do not prize your time whilst you are upon the earth, Christ tells you,
you must go to hell: nay, though you call Christ Lord,
and say you have preached in the streets, yet if you be found workers of iniquity;
though you may have preached Christ`'s death and resurrection,
and prophesied in his name, yet, if ye be found workers of iniquity,
Christ will say unto you, '`depart from me, I know ye not;
go ye cursed into everlasting punishment, prepared for the devil and his angels.`'

And though you may say as many prayers, as the babbling pharisees did three times a day,
and call Christ Lord, and do not the things which he commands, he tells you,
'`ye shall not enter into the kingdom of God.`'

For Christ tells you, it is those that '`do the will of his Father, which is in heaven,
that enter into the kingdom of God.`'

And therefore, do not vex, nor quench, nor grieve the spirit of God,
which is given unto you, to instruct you to shun the ways of sin and evil, and pleasures,
which lead to hell.

And do not hate the light which Christ hath enlightened you withal,
that shines in your dark hearts, which would give you the knowledge of your lost state,
and of your sins, and of Christ that saves you from your sins.

And do not walk despitefully against the spirit of grace, nor turn it into wantonness;
which grace of God that brings salvation, hath appeared unto all men, to teach them,
and to bring them salvation.

I say, to teach you to live soberly, and godly, and to deny all unrighteousness,
and ungodliness, which leads to hell.

And if you do hate the light, and quench his spirit,
and walk despitefully against the spirit of grace, and turn it into wantonness,
God and Christ will be clear of you, when you are condemned to hell fire, and in it roar.

For, what could God do more for you, who sent his Son to die for you, and sent his grace,
which hath appeared to all men to teach them, and bring their and your salvation;
and poured out of his spirit upon all flesh;
and his Son hath enlightened every man that cometh into the world;
and he bids them '`believe in the light, that they may become children of the light.`'

And sent his apostles and disciples into all nations,
to preach the gospel unto every creature freely, as they had received it freely;
and yet you do hate his light, and quench his spirit, and resist it,
and turn his grace into wantonness,
and not obey his gospel but persecute his free messengers of it,
and so do not the thing which God and Christ commands;
but live in pleasure and wantonness, and despise the poor, and persecute the just;
how can you expect any other end, but this rich man`'s in hell?

And acknowledge that God and Christ were just and merciful all your lifetime to you,
before he gave you up to your heart`'s lusts, which you walked after,
who resisted his grace and spirit, and his servants and messengers, that admonished you,
within and without.

Now if any should imagine, that by giving means unto priests,
that they can pray your souls out of purgatory, or middle place,
Abraham and Christ tell you no such thing; but tell you, you cannot come to Abraham,
nor Abraham unto you, when you are dead, and in hell.

And therefore, be warned in your lifetime, for there is no repentance in the grave,
it must be in your lifetime, and before you go to the grave: for,
'`as the tree falls so it lies,`' therefore, consider this while you be alive.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 7th month, 1676.
