== A Testimony

[.heading-continuation-blurb]
For all Masters of Ships, and Seamen to read over;
and to see whether you be in the true faith that the true
Christians and Holy Men of God were in, and if you be not,
then turn to the Lord Jesus Christ, who is the author and finisher of the Holy,
Divine, and Precious Faith; and then by this faith your hearts may be purified,
and with your hearts you may believe,
and with your mouths ye may make confession unto Salvation. Rom. 10.

[.heading-continuation-blurb]
And Christ saith, '`every one that is of the truth, heareth his voice,`' John 18:37.
And now every one that is not of the truth heareth not his voice,
and say, there is no hearing of it nowadays.

[.heading-continuation-blurb]
And here you may see how Christ called Fishermen and Seamen to be his disciples,
as followeth; and how Christ commanded the winds, and they obeyed him;
and how that the Lord God holds the winds in his fist, and raises a storm,
and makes a calm, so that all are to serve and fear him.

[.heading-continuation-blurb]
'`Quench not the Spirit, despise not Prophesying;
prove all things, hold fast that which is good.`' 1 Thess. 19:20-21.

[.heading-continuation-blurb]
Those who quench the Spirit, and despise Prophesying are not like to prove all things,
nor hold fast that which is good.--By G. F.

'`After that John was put in prison,
Jesus came into Galilee preaching the gospel of the kingdom of God, and saying,
the time is fulfilled, and the kingdom of God is at hand, repent ye,
and believe the gospel.`' Mark 1.

From that time Jesus began to preach, and to say, '`repent;
for the kingdom of heaven is at hand.`'

'`And Jesus walking by the sea of Galilee, saw two brethren, Simon, called Peter,
and Andrew his brother casting a net into the sea, (for they were fishers.)`'

And Jesus said unto them, '`follow me,
and I will make you fishers of men,`' and they straightway
left their nets and followed him.

'`And Jesus going on from thence, he saw two brethren, James the son of Zebedee,
and John his brother, in a ship with Zebedee their father, mending their nets,
and he called them.`'

'`And immediately they left the ship and their father,
and followed Jesus.`' Matt. 4:17, to 22. Mark 1:15, to 20.

Now here all ye seamen and fishermen, and all people may see,
these four disciples of Christ their call, and what trades they were of, fishermen,
and seamen; these and such were more like to follow Jesus then, and now,
than the high priests that had the tithes, and such as have great benefices.

But Christ is the same today, as he was yesterday, and so forever; for it was not many,
mighty and rich, but the poor that received the gospel.

'`And when Jesus was entered into a ship, his disciples followed him, and behold!
There arose a great tempest in the sea, insomuch that the ship was covered with waves;
but Jesus was asleep.`'

'`And his disciples came to him and awoke him, saying Lord save us, we perish.`' Mark,
in the time of a storm these fishermen came to Christ, and so should all seamen do now.
'`And he said to them, why are ye fearful, O ye of little faith?
Then he arose and rebuked the winds, and the sea, and there was a great calm.`'

'`But the men marvelled, saying, what manner of man is this,
that even the winds and the sea obey him.`'

Now all ye seamen and fishermen, let your eyes be to Christ,
and your faith in him that hath all power in heaven and in earth given to him,
and he can still the storms, and tempests, and waves of the sea, and make it calm.

And so Christ it is that saves you from perishing outwardly, and eternally,
as you may see, Matt. 8:23, to 27. and Mark 4:36, to 41. and Luke 8:22-25.

For both the winds and the sea do obey Christ, by whom they were made; therefore,
fear God, and let your faith stand in him, who is the author and finisher of it.

'`And Jesus began to teach by the seaside,
and there was gathered unto him a great multitude, so that he entered into a ship,
and there sat in the sea, (to wit,
in the ship,) and the whole multitude was by the sea on the land,`'
as you may see, Matt. 13. Mark 4:1.
'`and he taught them many things by parables,`' etc.

Now would not many say, that it was not a consecrated place to teach the word of God in;
but I must tell you, Christ consecrates and makes all things and places holy.

Now Peter, who was a fisherman, Christ said unto him,
and the rest of his company of fishermen, that he would make them fishers of men,
and bid them follow him, which they did.

And you may see in Acts 2.
how Peter the fisherman, by one sermon that he preached, converted three thousand souls,
as you may see from the 14th verse to the 41st, the beginning and end of his sermon.

And now all ye seamen and fishermen, consider this call of Christ,
who is the same today as yesterday, and so forever to you, if you will hear his voice;
for he stands at the door of your hearts and knocks, and if any will hear my voice,
saith Christ, and open his door, (to wit, of his heart, by joining to his grace, light,
power, and spirit,) '`I will come in and sup with him,
and he with me.`' Rev. 3:21. And so the sheep
of Christ hear his voice and follow him.
John 10. for Peter the fisherman said to the Jews,
how that in the last days '`God would pour out his spirit upon all flesh,
and your sons and daughters, shall prophesy, and your young men shall see visions,
and your old men shall dream dreams; and on my servants,
and on my hand-maids I will pour out in those days of my spirit,
and they shall prophesy saith the Lord,`' etc.

And now if God hath poured out of his spirit upon all flesh, and you grieve it,
and quench it, and vex it; then how can ye prophesy,
or have any of God`'s dreams or visions, or believe, or receive this fisherman`'s sermon,
who was a disciple of Christ?

And again, in Matt. 14:24. '`and Jesus constrained his disciples to go into a ship,
and to go before him, etc.
But the ship was now in the midst of the sea tossed with waves; for the wind was contrary.
And in the fourth watch of the night, Jesus went unto them walking on the sea;
and when the disciples saw him walk on the sea, they were troubled, saying,
it is a spirit, and they cried out for fear; but Jesus spake unto them, saying,
be of good cheer, it is I, be not afraid: and Peter answered him, and said, Lord,
if it be thou, bid me come unto thee on the water, and he said, come;
and when Peter was come down out of the ship, he walked on the water to go to Jesus:
but when he saw the wind boisterous, he was afraid; and beginning to sink, he cried,
saying, Lord, save me: and immediately Jesus stretched forth his hand and caught him,
and said unto him, O thou of little faith, wherefore didst thou doubt?
And when they were come into the ship, the wind ceased: then they that were in the ship,
worshipped him, saying, of a truth, thou art the Son of God.`'

And now here all seamen and others, you may see it is Christ that saves,
and stills the boisterous winds and waves, and makes them to cease; and therefore,
ye are not to doubt, but be steadfast in faith in all storms and tempests,
and see and feel Jesus to lay hold upon you, as he did upon Peter,
to save you from sinking in time of storms, who stills the waves of the sea,
who is the same today, as he was yesterday, and so forever: a rock of your age,
and a foundation of your generation, as was of former ages, as you may see,
Matt. 14:22, to 33. and John 6:17, to 21.

And again in Mark 6:47, to 51. there you seamen may see,
'`when Christ`'s disciples entered the ship, they had forgotten to take bread,
neither had they in the ship with them, more than one loaf.`'

'`And Christ charged them, saying, take heed of the leaven of the pharisees,
and of the leaven of Herod.`'

'`And the disciples reasoned among themselves, saying, it is because we have no bread.`'

'`And when Jesus knew it, he said unto them, why reason ye because ye have not bread?
perceive ye not, neither understand?
Have ye your hearts yet hardened, having eyes, and see ye not?
and having ears, and hear ye not?`'

'`For do you not remember, when I broke the five loaves among five thousand,
how many baskets full of fragments took ye up?
and they said, twelve.`'

'`And when the seven (to wit, loaves,) among four thousand,
how many baskets full of fragments took ye up?
and they said, seven.
And Jesus said unto his disciples, how is it that ye do not understand?`'

Now consider ye seamen, and fishermen, and others, that are not disciples of Christ;
for sometimes in your ships you have been in scarcity of bread;
and now here was Christ and his disciples which had but one loaf in the ship,
and Christ convinced them that they had enough, by his former miracles.

And therefore, they that have Christ, they have enough,
they have by whom all things were made, who gives the increase,
as you may see by his miracles.

And therefore, it is good for every one to see with the pure eye,
and hear with the pure ear,
so that they may perceive and understand with the pure heart what Christ did and doth do,
and what he is able to do in all necessities,
and to take heed of Herod`'s and the fair-sayer`'s leaven, which are not the doers,
but resist Christ, who doth not only say, but doth the will of his Father,
and so do all them that follow him.
Mark 8:13, to 21. Matt. 16:6, to 12.

And again, Christ saw two ships standing by the lake,
but the fishermen were gone out of them, and were washing their nets:
and he entered into one of the ships which was Simon`'s,
and prayed him that he would thrust out a little from the land.
And he sat down and taught the people out of the ship.
Now when he had left speaking, he said unto Simon, launch out into the deep,
and let down your nets for a draught.

'`And Simon answered and said unto him, Master, we have toiled all night,
and have taken nothing; nevertheless at thy word I will let down the net.`'

'`And when they had let down the net, they enclosed a great multitude of fishes,
and their net brake; and they beckoned unto their partners which were in the other ship,
that they should come and help them; and they came and filled both the ships,
so that they began to sink: and when Simon Peter saw it, he fell down at Jesus`'s knees,
saying, depart from me; for I am a sinful man, O Lord.`'

'`For Peter was astonished,
and all they that were with him at the draught of fishes which they had taken;
and so was also James and John, the sons of Zebedee, which were partners with Simon:
and Jesus said unto Simon, fear not, from henceforth thou shalt catch men.
And when they had brought their ships to land, they forsook all, and followed Jesus.`'

Now here all you seamen, and fishermen, and others,
may see that you may toil all night to catch outward fish with the nets,
and take nothing.

And you that call yourselves fishers of men,
you may toil all the night and catch not a man in God`'s net to him,
except it be with the power of Christ; and therefore know his voice, and obey it,
and follow him, by whom all things were made.

And so there is not a sparrow that falls to the ground, nor a fish in a fisherman`'s net,
but by the will of the Father.

And therefore, all ye fishermen and others, are to stand in the will of God,
who gives the increase, and fills the nets and the ships;
and therefore let him have the praise and follow him.

And here you may see the fishermen, and seamen; James and John, and Peter and Andrew,
were fishermen, and seamen, and partners together in ships,
and preachers of Christ Jesus, and caught a multitude of outward fish,
and a multitude of men, which they fished out of the great sea of the world,
by the command and power of Christ.
Luke 5:2, to 11. and Matt. 8:18.

'`And after Christ was risen,
he showed himself again to his disciples at the sea of Tiberius;
on this wise he showed himself, there were together Simon Peter, and Thomas,
called Didimus, and Nathaniel of Canaan in Galilee, and the sons of Zebedee,
and two other of his disciples.`'

'`Simon Peter said unto them, I go a fishing, they say unto him, we also go with thee:
they went forth and entered into a ship immediately, and that night they caught nothing;
but when the morning was come, Jesus stood on the shore,
but the disciples knew not that it was Jesus: then Jesus said unto them, children,
have ye any meat?
And they answered him, no; and he said unto them,
cast the net on the right side of the ship and ye shall find, and they cast therefore;
and now they were not able to draw it for the multitude of fishes: therefore,
that disciple whom Jesus loved, said unto Peter, it is the Lord.
Now when Simon Peter heard that it was the Lord, he girt his fisher`'s coat unto him,
(for he was naked,) and did cast himself into the sea,
and the other disciples came in a little ship, (for they were not far from land,
but as it were two hundred cubits,) dragging the net with fishes:
as soon then as they were come to the land, they saw a fire of coals there,
and fish laid thereon, and bread; and Jesus said unto them,
bring of the fish which ye have now caught,
and Simon Peter went up and drew the net to the land, full of great fishes, etc.
And Jesus said unto them, come and dine, etc.
And Jesus then cometh and taketh bread, and giveth them, and fish likewise, etc.
And this was now the third time that Jesus showed himself
after he was risen from the dead.`' John 21:2, to 14.

And now, all ye fishermen, and seamen, and others,
consider what kind of disciples and ministers the Lord Jesus Christ chose;
and you may see that Peter and the rest,
though they had been disciples of Christ Jesus for some years,
and such that Christ hath sent forth to preach before he was crucified,
and after that he was risen, Christ appeared the third time unto them;
and Peter had his fisher`'s coat, and the disciples who were fishermen, and seamen,
they were partners together in a ship.

And now, was this a fit coat, think you, to preach the gospel in, and to meet Christ in,
and to dine with him in?
I say, yes, as good as any of the canonical garments.

And consider, ye fishermen, and seamen, and others,
how all these disciples had been fishing all the night, but had caught nothing.

But when the morning was come, and they saw Jesus, after he was risen,
at his command they cast in the net, and drew it full of fish to the shore:
so it is by the will of God and Christ that every one doth catch, who made all things,
and upholds all things by his word and power, and fills all,
and knows what all have need of; for as Christ saith,
a sparrow shall not fall to the ground without the will of the
Father;`' so a fish cannot be caught in the net without his will.

And likewise, you fishermen, and seamen, and others, may see, that Jesus,
by whom all things were made, had provided these fishermen and seamen,
who were his disciples, a fire, and fish upon it, and bread upon the land,
when they had been fishing in the sea.

And therefore, you may see, how that Christ who upholds all things,
and hath all power given unto him, provides for his disciples, and seamen, and fishermen;
for he gave them both fish in the sea, and fish +++[+++and bread,]
upon the land, whom he sent forth, and gave commission to preach, and said,
'`freely ye have received, freely give.`'

So here you may all see, how the disciples of Christ were encouraged to trust in him,
and that their minds might be carried over all distrust
of carnal things and outward victuals.

And now, ye fishermen, and seamen, and all others,
may see Christ`'s words fulfilled unto his disciples, who said unto them, '`follow me,
and I will make you fishers of men;`' for Peter in
one draught caught three thousand in God`'s net;
and ye may read Peter`'s two general epistles which he freely gave forth.

And also, ye may see John the fisherman, a disciple of Christ, his evangelists,
his general epistle, and his two epistles, and his revelations: come, ye seamen,
and fishermen, and others, and see what ye can say for Christ, that is the same today,
as yesterday, and so forever; and come, let us see what nets ye have,
if it be the power of God, that will pluck them out of the sea of wickedness.

And if the seamen had taken Paul`'s counsel, when he said, '`sirs,
I perceive that this voyage will be for hurt, and much damage;
not only of the lading and ship, but also of our lives: but neither the centurion,
nor the master believed Paul`'s words;
but his words came to pass,`' as you see in Acts xxvii.
But the Lord preserved Paul, and their lives.

And so you may see it is not the seaman`'s skill, but the Lord`'s power,
which all are to have faith in, and to obey him, by whom they are saved and preserved.

And James, one of the fishermen, and an apostle of Christ,
in his general epistle to the twelve tribes, saith, '`behold,
we put bits in the horses`' mouths, that they may obey us,
and we turn about their whole body: behold also the ships, which though they be so great,
and are driven of fierce winds, yet are they turned about with a very small helm,
whithersoever the governor listeth; even so the tongue is a little member,
and boasteth great things: behold how great a matter a little fire kindleth;
and the tongue is a fire, a world of iniquity,`' etc.

And now mark, all ye seamen, and all ye bridlers of horses,
and all others that tame other creatures,
see that you can bridle and tame your own tongues,
and turn about your tongues in your passion, as soon as you do your horses;
and as soon as you do your great ships, when you turn them about:
so see that you can so soon turn your tongues when the fierce winds of passion are up;
and tame your tongues, lest that unruly member defile your whole bodies,
and '`set on fire the course of nature, and it is set on fire of hell.`' Jam.
iii. For can you tame serpents, and all kinds of beasts, and of birds,
and things in the sea, and not tame your tongue,
that unruly member that is full of deadly poison?
Bridle it, I say, with God`'s bridle, (his power.)

'`For the tongue of the just is as choice silver;
and the tongue of the wise is health.`' Prov. 10:20. and 12:18.
'`the tongue of the wise useth knowledge aright;
and a wholesome tongue is a tree of life.`' Prov. 15:2,4. And,
'`in a virtuous woman`'s tongue is the law of kindness.`' Prov. 31:16.

And Paul, an apostle of Jesus Christ, who made tents with Priscilla and Aquila,
and wrought with his bands, that he might not be chargeable to others,
and he did not only maintain himself, but he also helped others with his labour,
who had received his gospel, not from man, but by the revelation of Jesus Christ,
which he preached freely, as he received of Christ freely, after Christ was risen;
for Christ had given his command to his twelve disciples before he was crucified,
'`freely as they had received, freely give.`' And now, consider Matthew,
who was called from his custom, and Luke, who was a physician, and John the fisherman,
and Peter, and the rest who were disciples of Christ;
did not they give forth all their evangelists and epistles freely,
as they had preached freely?

And did not Paul, the apostle of Christ, who was a tent-maker, who said of the Jews,
'`five times I received forty stripes save one; thrice was I beaten with rods;
once was I stoned; thrice I suffered shipwreck;
a night and a day I have been in the deep, in journeying often, in perils of water,
in perils of robbers, in perils of my own countrymen, in perils by the heathen,
in perils in the city, in perils in the wilderness, in perils in the sea,
in perils among false brethren; in weariness and painfulness, in watching often,
in hunger and in thirst, in fastings often,
in cold and nakedness,`' etc. as you may see in 2 Cor. 11:24, to 27.

And this, you see, was the condition of Paul, an apostle of Jesus Christ,
that made tents, besides all his imprisonments.

Now did not this apostle preach freely,
who saith '`he laboured with his hands that he might be an example to others
that followed him;`' so you may see that he did not sit down in a great benefice:
and did not he give forth all his epistles freely?
And did not he give forth his epistle to the Romans,
and his two epistles to the Corinthians, and his epistle to the Galatians,
and his epistle to the Ephesians, and his epistle to the Philippians,
and his epistle to the Colossians, and his two epistles to the Thessalonians freely?
And saith, '`I charge you by the Lord,
that this epistle be read unto all the holy brethren,`'
as in 1 Thess. 5:27. And Paul`'s two epistles to Timothy,
and one epistle to Titus, and his epistle to Philemon, and his epistle to the Hebrews,
and how that God in these last days hath spoken to us (the true church,) by his Son,
whom he hath appointed heir of all things, by whom also he made the world.

Now consider all people, did not all the holy prophets,
and all the holy men of God give forth all their books freely, from Adam to Christ,
to be read, believed, practised and fulfilled?
And did not all the holy apostles,
and all the holy evangelists give forth all their evangelists, epistles,
and revelations freely?
And to be read, believed, and practised?
or did they give them forth freely, that men after them should make a trade of them,
and to have so much a year for preaching of them, which they prophesied,
and preached freely, and gave forth freely.

And the apostle doth not say,
'`preach his epistles,`' but '`read them,`' as in Col. 4:16. 1 Thess. 5:27.
And likewise the Lord said,
'`thou shalt read my law to all Israel in their hearing.`' Deut. 31.
And Isaiah saith, '`seek ye out of the book of the Lord and read,`' etc.
And Jeremiah sent Baruch to read his book or roll.
Jer. 36:4-6, etc.
So both the old and New Testament were given forth to be read, and believed,
and to be obeyed, and fulfilled,
as you may see in Ezra 4:18. Neh. 8:3. Jer. 29:19. Eph.
3:4-5. Matt. 1:22. Luke 4:16. Mark 13:21. and 14:49.
John 19:24,28,36. Acts 1:16.

Now is there more money got by any one thing, than by preaching of the scriptures,
and some old authors with them?
Let it be cast up in all nations in Christendom,
and see how much their revenues comes to yearly,
of such that do not obey Christ`'s doctrines, who saith, '`freely ye have received,
freely give;`' nor follow the apostle Paul`'s example,
'`to keep the gospel without charge.`' And the apostle saith, 1 Tim. 1:19.
where he exhorts Timothy,
'`to hold fast his faith and a good conscience, which some having put away,
(concerning faith,) they have made shipwreck.`' Now consider this ye seamen, and others,
when your ships are wrecked what condition you are in, you are fallen to pieces,
you are broken, and many times in the sea; so that ye have great distress.
And when you have made shipwreck of faith and a good conscience, then where are you,
but split in the sea of the world, and the waves of the world go over your heads,
that you have no victory: and therefore consider what condition all the world is in,
that say, they have not victory on this side the grave;
and they that must have a purgatory when they are dead:
have they not made shipwreck of faith and a good conscience, and are split in the world,
the sea?
have not faith, nor victory out of it, and over it on this side the grave;
when as the apostle saith, '`the holy and precious divine faith,
which Christ Jesus is the author and finisher of,
it purifies their hearts;`' and by it they are justified, and in it they please God;
which faith is their victory, by which they have access to God,
over the world and out of its sea.

And in Jer. 16. there you may see, when the Jews transgressed the law of God,
and became worse than their forefathers, how they were then as in a sea: for '`behold,
I will send for many fishers, saith the Lord, and they shall fish them;
and I will send for many hunters, and they shall hunt them from every mountain,
and from every hill, and out of the holes of the rocks.`'

So here you may see, men are called fish, and men are called fishers, and then consider,
where is the fish, and where is the sea?
Is not the sea the world which lies in transgression,
and rebellion against the spirit of God?
(and such as make shipwreck of faith and a good conscience,) are they not in it? Jer. 16:17.

But saith the prophet, '`thou art (to wit, the Lord,) of purer eyes than to behold evil,
that canst not look on iniquity:
wherefore lookest thou upon them that deal treacherously,
and boldest thy tongue when the wicked devoureth the man, that is more righteous than he,
and makest men as the fishes of the sea,
and as the creeping things that have no rule over them:
they take up all of them with the angle, they catch them in their nets,
and gather them in their drags; therefore, they rejoice and are glad; therefore,
they sacrifice unto their net, and burn incense unto their drag, and because by them,
their portion is fat, and their meat plenteous,`' etc.
Here is the wicked men`'s fishing, and the wicked men`'s sacrifice,
which is not to be followed.

And in Jonah 2.
there you may see Jonah`'s prayer, and the steadfastness of his faith, which he had,
and prayed to the Lord God out of the fish`'s belly. Jonah 2. throughout.

And you may see the cause of Jonah`'s being cast into the sea,
how that it was for his disobedience; for when the Lord commanded him to go to Nineveh,
to preach repentance to it, he fled away, and went to Joppa, and found a ship,
and so paid the fare thereof, and went down into it, to go from thence to Tarshish,
from the presence of the Lord; '`but the Lord sent out a great wind in the sea,
and there was a mighty tempest in the sea, so that the ship was like to be broken:
and then the mariners were afraid, and cast lots,
and the lot fell upon Jonah to be cast into the sea;
and when they had cast him into the sea, it ceased from raging.`'

And now all ye mariners, and seamen, and fishermen and others,
whose faith stands not in God, and Christ Jesus the author of it,
when ye have storms and great winds, and tempests in the sea; then do not you say,
that some witch or ill-tongued people have bewitched your ship, and raised that wind,
or some ill-tongued body hath raised this storm and tempest.

And let New England professors see if they be not guilty of this;
and whether or no they have not sometimes cast some poor simple people into the sea,
on pretence of being witches: and so let them and you see that hold such things,
and believe such things, if you be not in disobedience to the power,
spirit and faith of God, and in the sin of witchcraft yourselves.

For you may see, it was the Lord that sent out the wind,
and raised that mighty storm in the sea, and not your witches or ill-tongued people,
as you vainly imagine,
as you may see in Jonah 1:4. For if you were in the true saving faith,
which Christ Jesus is the author of, that faith gives you victory over the devil,
the head of all your witches, and brings you to have access to God, who makes a storm,
and makes a calm.

For, '`lo, he that formed the mountains, and created the winds, (mark,
the winds,) and declareth unto man what is his thoughts,
this is the Lord,`' that created the winds, not your witches. Amos 4:13.

And, '`it is the Lord, who layeth the beams of his chamber in the waters,
who makes the clouds his chariots,
who walketh upon the wings of the winds.`' Ps. 104:3.

And the Lord commandeth and raiseth up the stormy wind,
which lifteth up the waves thereof, and not your witches nor ill-tongued people.

And David saith, '`They that go down to the sea in ships,
that do business in great waters; these see the works of the Lord,
and his wonders in the deep: for he commandeth and raiseth the stormy wind,
which lifteth up the waves thereof: they mount up to the heaven,
they go down again to the depths; their soul is melted because of trouble:
they reel to and fro, and stagger like a drunken man, and are at their wits ends;
then they cry unto the Lord in their trouble,
and he bringeth them out of their distresses.
He maketh the storm a calm, so that the waves thereof are still; then are they glad,
because they be quiet; so he bringeth them unto their desired haven.
O that men would praise the Lord, for his goodness,
and for his wonderful works to the children of men.`' Psalm cvii.

So ye may see it is the Lord that commands and raiseth the winds and the storms,
and allays them again, and not the witches, or ill-tongued people;
and that brings men to their desired haven, both outward and inward.

And again, David saith, '`He (to wit, the Lord,)
causeth the vapours to ascend from the ends of the earth;
he maketh lightnings for the rain,
he bringeth the wind out of his treasure.`' Ps. 105:7.

And now mark all ye seamen, when ye have wind that maketh a storm in the sea,
the Lord hath brought it out of his treasure:
but the disobedient and rebellious against God`'s power, spirit and faith,
and enemies to his truth and people say, when a storm or wind is raised in the sea,
some witch, or some ill-tongued people have raised it;
and those are erred from the true faith as David was in, who said,
'`whatsoever the Lord pleaseth, that does he, in heaven, and in the earth,
and in the sea, and all deep places.`' Ps. 105:7.

And '`God causes the winds to blow, and the waters to flow.`' Ps. 147:18.

And David saith, '`fire, and rain, and snow, and waters,
and winds fulfill God`'s word.`' Ps. 148:8.

And now if the witches raise the storms and the winds,
then the winds and storms must fulfill your witches`' and ill-tongued people`'s words;
but the storms and the winds fulfill God`'s word; and he raiseth up a storm or a wind,
that walks upon the wings of the wind.
And your witches cannot come into God`'s treasure, to fetch his wind out there,
for they be out of his power.
Nay, have not some of your faithless seamen, and you that think so,
pretended to buy winds?
oh! darkness and ignorance, and a shame to christianity!
You are like to the clouds and winds without rain, and wells without water,
and trees without fruit, as you may see in Prov. 25:14. and in Jude.

'`Who hath gathered the winds in his fist?
Who hath bound the waters in his garment?
Who hath established all the ends of the earth?
What is his name, and what is his Son`'s name,
if thou canst tell?`' Prov. 30:4. Who with thy dark spirit imagines,
that the witches can fetch or pluck the wind out of God`'s fist.
Oh! abominable!
It is much if the Lord doth not let his wind fly at you, and raise a storm against you,
who are erred from the faith of the holy men of God:
for Christ commandeth the winds and they obey him. Luke 8:25.

And where do you read in all the scriptures, that the witches raised winds,
or that any seamen did go to buy winds of them?
Let us see the chapter and verse for it; either among the people of God,
or among the heathen; and if you cannot, stop your mouths,
and of such practices be ashamed, for dishonouring christianity,
who are contrary both to the law and gospel: and turn to the Lord,
who walks upon the wings of the wind, and holds the winds in his fist,
and can let them fly out in blasts to terrify the wicked;
but the just live by the faith in God and Christ, who is the author of it;
who makes the storm a calm, and commands the winds,
and brings them out of his treasure at his pleasure: and the righteous know,
that the stormy winds obey and fulfill God`'s word.

And so the righteous can praise the Lord that created the winds,
and all things in the heaven and in the earth, and in the sea; and renews man by Christ,
into his image, and gives him dominion over all; praise and glory,
honour and thanks be unto the Lord, who is over all, from everlasting to everlasting.

And all the faithful know,
that '`a sparrow shall not fall to the ground without
the will of the Father,`' much more a man,
who is of greater value than many sparrows.

And therefore be not faithless, but believe in Christ the light,
who commands the winds and storms; by whom all things were made, and are upheld,
by his word and power. Heb. 1.
'`the law of thy mouth is better unto me than thousands of gold and silver.`'
Ps. 119:72.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore in Lancashire, the 28th of the 8th month, 1676.

[.blurb]
=== Concerning how the World is called the Sea.

And God will dry up Babylon`'s sea, and make her springs dry;
for God brought them like a sea over the Jews, when they transgressed his law,
and went from the Lord their rock and salvation.

And again it is said, '`the sea shall come upon Babylon,
and she shall be covered with the multitude of her waves.`'
So when the Medes and Persians came upon Babylon,
then the sea came over them, and the Jews had their liberty. Jer. 15:42.

So spiritual Babylon is the mother of harlots, she sits upon the waters,
which are nations, people, and tongues; but God will dry up her waters,
which have overflown since the apostles`' days, who hath persecuted the people of God:
and out of her sea hath risen the great storms of persecution,
and the beast which rose out of the sea, with his storms of persecution.
And it is the power of darkness, which keeps the people in spiritual Egypt,
Sodom and Babylon, in this sea.

'`But in Christ`'s peaceable kingdom, and on his holy mountain,
the wolf shall dwell with the lamb, and the leopard shall lie down with the kid,
and the calf, and the young lion, and the fatling together,
and a little child shall lead them.`'

'`And the cow and the bear shall feed, their young ones shall lie down together;
and the lion shall eat straw like an ox.`'

'`And the suckling child shall play on the hole of the asp;
and the weaned child shall put his hand on the cockatrice den.`'

'`They shall not hurt, nor destroy in all my holy mountain;
for the earth shall be full of the knowledge of the Lord, as the waters cover the sea.`'

'`And in that day there shall be a root of Jesse,
which shall stand up for an ensign of the people; to it shall the Gentiles seek,
and his rest shall be glorious.`'

And this is Christ who sets up his ensign for the nations,
and shall assemble the outcasts of Israel,
and gather together the dispersed of Judah from the four corners of the earth.

So he gathers them with his power, spirit and light,
and his ensign is not set up for the Jews, or a nation only,
but for all nations in general;
'`who enlightens every man that comes into the world,`'
that with his light they may see him and his ensign,
Christ the heavenly and spiritual man.

So the gathering of all nations is unto him,
by his heavenly light which he enlightens them withal.

'`And the Lord shall utterly destroy the tongue of the Egyptian sea,
and with his mighty wind shall he shake his hand over the river,
and shall smite it in the seven streams, in the perfection of it;
and men shall go over dry-shod.`' Isa.
xi.

And the Lord will destroy in this mountain,
the face of the covering that is cast over all people,
and the veil that is spread over all nations, +++[+++mark, all nations,]
not a nation: that all people may see the salvation of God,
with the light which comes from Christ their Saviour; and if they do not believe in it,
it will be their condemnation.

And this covering must be taken off all people before
the knowledge of the Lord covers the earth,
as the waters cover the sea.

For the beast had his power from the dragon,
and the whore is erred from Christ the truth: and Egypt in the spirit,
and the spiritual Egyptians will say, '`who is God, or his Son the light,
that they should obey him?`' (like the old Egyptian.)
And Christ was crucified in spiritual Sodom and Egypt.

So here the Jews, scribes, pharisees, and high priests,
who crucified Christ without the gates of Jerusalem, are called spiritual Egypt,
and Sodom, who were the greatest professors in the world.
But Christ is the ensign set up to the nations, who stilleth mystery Babylon`'s sea;
and after Babylon is fallen, and the seas dried up, then the new heaven,
and the new earth is seen; for the first heaven and first earth were passed away,
and then there was no more sea.
So when the first heavens and the first earth are passed away, then the new earth,
and the new heavens are seen; and here is seen the holy city, New Jerusalem,
prepared as a bride for her husband Christ.

And here is the first and last seen, their husband Christ;
and-the marriage of the Lamb is come.

'`And the force of the Gentiles shall come to his light,
and abundance of the sea shall be converted unto Christ.`' Isa. 60.

So here is abundance of the world, which is called the sea,
that shall be converted to Christ Jesus; for the Gentiles are the nations,
and the Gentiles shall come to Christ`'s light; the sea the world:
for nations and tongues are waters.

And the sea saith, wisdom is not in me. Job 28.
Now the wisdom that is pure, is from above the sea, and them that fear God receive it.

'`And he shall pass through the sea with afflictions,
and shall smite the waves of the sea, and all the deeps of the rivers shall be dried up:
and the pride of Assyria shall be brought down,
and the sceptre of Egypt shall depart away.`'

And Christ`'s sceptre shall be set up, his sceptre is a sceptre of righteousness. Zech. 10:11.

'`Thus saith the Lord, which maketh a way in the sea, and the path in the mighty waters,
that his people may pass, glory to his name forever.`' Isa. 63.

And the Lord saith, '`When I came, was there no man?
When I called, was there none to answer?
Is my hand shortened at all, that I cannot redeem, or have I no power, to deliver?
Behold,
at my rebuke I dry up the sea.`' And here the great power of God and Christ is seen.
Isa. 1. The wicked are compared to a troubled sea, when it cannot rest,
whose waters cast up mire and dirt; their waters are foul.

'`There is no peace to the wicked, saith my God; for they are always roaring,
and wallowing, and making a noise.`' Isa. 1:57.

And the cruel people that have no mercy, their voice roars like a sea,
as in Jer. 6:23. This sea, this merciless cruel people, which is like a roaring sea,
was to come over the Jews for disobeying the Lord:
and therefore for all people to believe in the light,
that Christ hath enlightened you withal, and walk in the light,
that you may see Christ the rock, and build upon him, who is sure against all weathers.

And Christ will bruise the head of the serpent; for the Lord with his sore,
and great and strong sword shall punish the leviathan the piercing serpent,
even leviathan that crooked serpent, which makes the world (both men and women,) crooked.

And he shall slay the dragon that is in the sea, +++[+++mark, in the sea,]
for his habitation is in the wicked like a roaring sea,
and they plead for him and his sin till they go to the grave,
and not for Christ that bruiseth his head;
and the Lord that destroys him with his great sword.

But they that plead for Christ, '`can sing unto the Lord of his vineyard;
for the Lord doth keep it,`' and will water it every moment, lest any hurt it:
'`I will keep it night and day, saith the Lord;`' glory to his name forever,
who is the keeper of his people, and this we witness who are his vineyard,
as in Isaiah 27.

[.signed-section-signature]
G+++.+++ F.
