[.style-blurb, short="Concerning Christ the Spiritual Head over His Church"]
== Concerning Christ the Spiritual and Holy Head over his Holy Church, and his Church`'s steadfastness, and confidence, and unity and oneness in him. By G. F.

Christ prayed for his church, and said, '`for their sakes I sanctify myself,
that they also may be sanctified through the truth; neither do I pray for these alone,
but for them also who shall believe on me through their word.`'

And Christ further said, '`I have given them thy word,
and the world hateth them because they are not of the world,
even as I am not of the world.`'

And further, he saith, '`that they all may be one, as thou Father art in me,
and I in thee, that they also may be one in us, (to wit,
the Father and the Son,) that the world may believe that thou hast sent me.`'

So here was Christ`'s prayer, that his church might be kept in oneness,
in the Father and in the Son.

And further, Christ said, '`the glory which thou gavest me, I have given them,
that they may be one, even as we are one.`'

Now here is a heavenly oneness in the heavenly unity.

And further, Christ saith, '`I in them, and thou in me,
that they may be made perfect in one, and that the world may know that thou hast sent me,
and hast loved them as thou hast loved me.`'

So here Christ`'s desire is to the Father,
that the world might know that God loves his Church as he loves Christ,
and that they may be perfect in one.

And further, Christ said, '`Father, I will that they also whom that hast given me,
be with me where I am, that they may behold my glory, which thou gavest me;
for thou lovedst me before the foundation of the world.`'

And further, Christ said, '`I have declared unto them thy name, and will declare it,
that the love wherewith thou hast loved me may be in them, and I in them.`'

Now, this is the perfect love and perfect oneness,
in the perfect unity with the Father and the Son, and with his church;
and this oneness is that which convinces the world,
that the world may know that God hath sent his Son, by the love, and unity,
and oneness that is amongst the saints, the church,
and they in the Son and in the Father, as you may see in John 17.
more at large.

And as God said unto Abraham, '`in thy seed shall all nations be blessed.`'

So all nations are blessed in the seed, which is Christ; and they that are in the seed,
are his church, and inherit this blessing:
for Christ took not upon him the nature of angels, but the seed of Abraham,
who bruises the head of the serpent that brought the curse.

And Jacob said on his deathbed, when he called his sons together,
and told them what should come to pass in the last days;
'`the sceptre shall not depart from Judah, nor the law-giver from between his feet,
until Shiloh come; and unto him shall the gathering of the people be.`'

Now Shiloh, the peaceable Saviour, Christ Jesus, is come,
and unto him must be the gathering of all nations;
for there is no salvation given by any other name under heaven, but by the name of Jesus,
whose name is above every name.

And you may see Caiaphas, the high priest`'s prophecy, concerning Christ;
he told the Jews, they knew nothing at all, nor considered,
that it was expedient for us that one man should die for the people,
and that the whole nation perish not:`' and this spake he not of himself,
but being high priest that year, he prophesied that Jesus should die for that nation,
and not for that nation only, but that he should gather together in one +++[+++mark,]
the children of God, who were scattered abroad.

Mark, Christ gathers into one them that are scattered abroad,
he who is the head of the church.

For, as Moses said, '`like unto me will God raise up a prophet, him shall you hear.`'

So all are to hear him, and believe in him for life and salvation.

Now Christ, who was the holy offering and sacrifice, hath tasted death for every man:
so every man may have comfort here, if he believe in the light,
which is the life in the word, which lighteth every man that cometh into the world.

And he is a '`propitiation for the sins of the whole world,`' and not only for the saints,
the churches.

And '`God so loved the world, that he gave his only begotten Son into the world,
that whosoever believeth in him should not perish, but have everlasting life.`'

And God said, '`this is my beloved son, hear ye him.`'

And Christ said, '`learn of me, I am the way, the truth, and the life,
and no man cometh to the Father, but by me.`'

And Christ said,
'`believe in the light;`' who enlightens all with the heavenly divine light,
which is the life in the word; and they that believe in the light,
become children of the light, and so are all grafted into Christ, and so are one in him,
and in the Father: so the church is one in Christ, the head;
and they that believe in the light, are born of God,
and are passed from the death into the life, Christ the head of the church,
who destroys the devil, the power of death.

So they that believe have the witness in themselves; and after they believe,
they are sealed with the spirit of promise,
and can set to their seals that God is true in his Son, and in all his prophets, figures,
and shadows, and types of him, who is the substance of them all.

So they that are grafted into Christ, are living members,
who are born again not of corruptible seed, built up a spiritual household,
a holy priesthood, offering up spiritual sacrifices acceptable to God by Jesus Christ.

So these are the living members of the living head, Christ Jesus,
who is the head of the church, that believe in him, and have everlasting life.

And so the world knows not these living members, as it did not know the head,
as Christ said.

And so the believers in the light, which is the life in Christ,
are one in the eternal life; for as, it is said, '`he that believeth in the Son of God,
shall not perish, but hath eternal life.`'

And you may see how the believers were added to the church, in Acts ii.

And so as the apostle said to the Ephesians, to the saints which are at Ephesus,
and to the faithful in Christ Jesus: so he calls them saints, and said,
blessed be the God and Father of our Lord Jesus Christ,
who hath blessed us with all spiritual blessings in heavenly places in Christ Jesus;
according as he hath chosen us in him before the foundation of the world,
that we should be holy, and without blame before him in love, Ephes. 1.
And he told them further, '`even we, which were dead in sins,
hath he quickened together with Christ, by grace are we saved;
and hath quickened us up together,
and made us to sit together in heavenly places in Christ Jesus.`'

Now, this church sat together in the heavenly places in Christ Jesus, after he was risen;
so these were one in him, and in the Father, in the power of God and the spirit. Ephes. 2.

And Christ hath abolished in his flesh the enmity, the law of commandments,
contained in ordinances, to make in himself of twain one new man; so making peace,
that he might reconcile both (to wit, the Jews and Gentiles,)
unto God in one body with the cross, having slain the enmity thereby;
for through him we have access by one spirit unto the Father.

So Jews and Gentiles are one here in Christ, and no more strangers and foreigners,
but fellow-citizens with the saints of the household of God,
and are built upon the foundation of the prophets and apostles,
Christ Jesus being the corner-stone, etc.

So being built in him, in whom all the building fitly framed together,
groweth up a holy temple in the Lord, in whom you also are built together, +++[+++mark, are,]
for a habitation of God through the spirit.

So all such know what is the fellowship of the mystery from the beginning of the world,
that hath been hid in God, who created all things by Jesus Christ,;
to him be glory in the church through Jesus Christ, throughout all ages,
world without end.

So this church is to keep the unity of the spirit in the bond of peace;
for there is one body, and one spirit,
even as you are called into one hope of your calling, and one Lord, one faith,
and one baptism.
So one God and Father of all, who is above all, and over all, and in you all;
but unto every one of us is given grace, according to the measure of the gift of Christ.

So the church, which Christ is the head of, are one body,
and their unity is in the one spirit, and they have but one Lord Jesus Christ,
who is the author of their one faith and baptism, who is their one baptizer.

And they have but one God and Father, who is above them all, and in them all; for,
as he says, '`I will dwell in you, and walk in you, and ye shall be my people,
and I will be your God;`' for your bodies are the temples of the living God.

And Christ who is ascended up on high, far above all heavens,
that he might fill all things; so he fills all things though he is far above the heavens,
and fills his church with his heavenly and spiritual presence.

And he gives his gifts to men, for the perfecting of the saints,
and for the work of the ministry, and for the edifying of the body of Christ,
till they all come to the unity of the faith, which Jesus is the author of,
and to the knowledge of the Son of God, and unto a perfect man,
and unto the measure of the stature and fulness of Christ.

And so the church is to grow up in Christ in all things, who is the head,
and unto Christ the whole body is fitly joined together, and compacted,
by that which every joint supplies,
according to the effectual working in the measure of every part,
making increase of the body unto the edifying itself in love.
Ephes. 3. 4.

And Christ is the head of the church, and Saviour of the body;
so Christ also loved his church, and gave himself also for it,
that he might sanctify and cleanse it, with the washing of water by the word,
that he might present it to himself a glorious church, not having spot or wrinkle,
or any such thing, but that it should be holy and unblemished.

For the apostle said, '`for we are many members, yet one body,
and of his flesh and of his bone.`'

And the apostle speaks figuratively,
'`for this cause shall a man (said he,) forsake father
and mother and cleave unto his wife,
this is a great mystery, but I speak concerning Christ and his church.`'

And therefore the church is to walk in love, as Christ hath loved it,
and hath given himself for it,
an offering and a sacrifice to God of a sweet smelling savour;
and to have no fellowship with the unfruitful workers of darkness,
but rather to reprove them, as you may see in Ephes. 5.

And Paul writes to the church of the Romans and tells them,
that they were called of Christ Jesus, and said, '`they were beloved of God,
and called to be saints;`' and told them,
that the '`gospel was the power of God unto salvation,
unto every one that believed,`' and exhorts them to '`walk in the faith of Abraham;`'
and how God would justify the circumcision and the uncircumcision by the one faith,
which Christ was the author of, which brought them into unity, and said,
as we are many members in one body, and all members have not the same office,
so we being many are one body in Christ, and every one members one of another in Christ.
Rom. 12.

So every member was to think soberly,
according as God had dealt to every man the measure of faith,
which Christ the head of the body is the author of,
and in the holy faith is the unity in the body.

And he further said,
'`that ye may with one heart and mouth glorify God the Father of our Lord Jesus Christ,
wherefore receive you one another,
as Christ also hath received us to the glory of God.`' Rom. 15.

So here it was the work of the Holy Ghost to keep the church in this one mind,
to the one God, in one body, and in the unity of the one faith and spirit; for he saith,
'`he that hath not the spirit of Christ, is none of his.`'

And the apostle said unto the church of God at Corinth,
'`unto them that are sanctified in Christ Jesus, called to be saints,
with all that in every place call on the name of Jesus Christ our Lord,
both theirs and ours.`'

So ye may see what holy titles the holy apostles gave to the church,
as sanctified in Christ Jesus, and called to be saints, and tells them,
'`that they were called in Christ Jesus, who of God is made unto us wisdom,
righteousness, sanctification and redemption;`' and tells them,
'`that the preaching of the cross of Christ to them that perished was foolishness,
but to us (said he,) that are saved, it is the power of God.`'

And the apostle tells the Corinthians,
'`that he was called to be an apostle through the
will of God;`' so not through the will of men;
and he tells them further, that they knew,
'`that the unrighteous should not inherit the kingdom of God, neither fornicators,
nor idolators, nor drunkards, revilers, extortioners,
etc. should inherit the kingdom of God; and such were some of you, +++[+++mark, were,]
but ye are washed, but ye are sanctified,
but ye are justified in the name of the Lord Jesus Christ,
and by the spirit of our God.`'

Mark, '`are washed, are sanctified, are justified;`' then it was not to do, but was done;
and said, '`the body is not for fornication, but for the Lord, and the Lord for the body,
for know ye not that your bodies are members of Christ,
and are not to be joined to harlots; but he that is joined to the Lord is one spirit;
for your bodies are the temples of the Holy Ghost, which is in you,
which you have of God, and ye are not your own; for ye are bought with a price,
therefore glorify God in your bodies, +++[+++mark, in your bodies,]
and in your spirits, which are God`'s.`' 1 Cor. 6.

So here this church had received the Holy Ghost, according to Christ`'s promise,
and they were to obey and do these things in it.

And the apostle said, '`the cup which we bless,
is it not the communion of the blood of Christ?
and the bread which we break, is it not the communion of the body of Christ?
I speak this to wise men to judge what I say, for we being many are one bread,
and one body; for we are all partakers of that one bread;`' +++[+++mark,]
we, the church, are one bread, and we the church, are one body,
which Christ the heavenly man is the head of; and we, the church,
are all partakers of this one bread, who gives his bread unto his church. 1 Cor. 10:15-17.

And he further said,
'`the manifestation of the spirit is given to every man to profit withal;
and though there is diversities of gifts and operations, yet the same God,
etc. which works all in all; for as the body is one, (to wit,
of Christ,) and he hath many members, and all the members of the one body being many,
are one body, so also is Christ; for by one spirit are we all baptized into one body,
whether we be Jews or Gentiles; bond or free;
and have been all made to drink into one spirit;`' so the body is not one member,
but many.

So the foot, the hand, the eye, the ear, etc.
The prophets, the apostles, the teachers, evangelists, exhorters, reprovers, rebukers,
ministers, instructers, etc. all one, from one spirit in the body;
and God hath set the members every one of them in the body as he pleaseth;
'`and now are we many members, yet but one body,`' said the apostle.

So God hath tempered the body together, that there may be no schism in the body,
but that all the members should have care one of another, that if one member suffer,
all the members suffer with it; and if one member be honoured, all,
the members rejoice with it.

'`Now ye are (saith the apostle,) the body of Christ,
and members in particular,`' etc. as you may see 1 Cor.
xii. throughout; what a heavenly unity,
agreement and oneness there is in the body of Christ, which he is the heavenly head of.

And the apostle further said to the church of Corinth,
'`that he was an apostle to the church of Christ by the will of God,
and Timothy his brother;`' and he directs his epistle to the church of God,
which is at Corinth, and to all the saints in Achaia.

So here he gives them holy titles, the church of God, and saints,
and he an apostle of Jesus Christ by the will of God; and tells them,
'`that they are temples of the living God; for God hath said, I will dwell in them,
and walk in them; and I will be their God,
and they shall be my people:`' and he further tells them,
'`there was no agreement betwixt the temple of God and idols,
nor concord betwixt Christ and Belial, nor betwixt believers and infidels;
wherefore come out from amongst them, and be ye separate, and touch no unclean thing,
and I will receive you, and I will be a father unto you,
and ye shall be my sons and daughters, saith the Lord God Almighty.`' 2 Cor. 6.

So here you may see how purely and soberly the church of Christ were to live and walk,
and to honour their pure holy head.

And the apostle writes to the Galatians, saying, '`he was an apostle not of man,
nor by man, but by Jesus Christ, and God the Father,
who raised him from the dead,`' and he certified them,
'`that the gospel which was preached by him, was not after men;
for I neither received it of men, nor was I taught it,
but by the revelation of Jesus Christ:
and he exhorts and encourageth them to the faith of Christ,
and tells them of Jerusalem below, which is in bondage with her children,
but Jerusalem which is from above, is free, which is the mother of us all, to wit,
the true church, which Christ is the head of: and he tells them,
'`that neither circumcision, nor uncircumcision availed any thing,
but a new creature;`' and he gloried in nothing, but in the cross of Christ,
by which he was crucified to the world, and the world to him;
'`and he that walked according to that rule, peace be upon him, and the Israel of God,
for all the law is fulfilled in one word, even in this,
thou shalt love thy neighbour as thyself,`' as you may see in Gal. 4. 5. 6.

And the apostle writes to the Philippians,
'`to all the saints in Christ Jesus which are in Philippi,
etc. that he had joy of their fellowship in the gospel;`' and here he calls them saints,
as much as to say sanctified ones.

And he said,
'`let your conversation be as becomes the gospel of Christ;`' and he told them,
'`it was God that wrought in them,
both to will and to do of his good pleasure;`' and they
were to do '`all things without murmuring and disputing,
that ye may be blameless and harmless, the sons of God without rebuke,
in the midst of a crooked and perverse generation,
amongst whom ye shine as lights in the world, holding forth the word of life.`' etc.

And further he said, '`our conversation is in heaven, from whom we look for our Saviour,
our Lord Jesus Christ, who shall change our vile body,
that it may be fashioned like unto his glorious body, according to his working,
whereby he is able to subdue all things unto himself.`'

And he desires them '`to help those women also, which laboured with him in the gospel;
for they were members of one body;`' and said '`salute
every saint in Christ Jesus,`' +++[+++mark, in Christ Jesus,]
for they that be out of him cannot be saints.

And Paul writes to the Colossians, '`Paul an apostle by the will of God,
and Timothy our brother, to all the saints and faithful brethren in Christ Jesus,
which are in Colosse.`' Now mark, what holy,
heavenly titles are here given to the church,
to all the faithful brethren in Christ Jesus, +++[+++mark, in Christ Jesus,]
and Paul an apostle by the will of God, so not by the will of man.

And the apostle gives thanks to God the Father,
'`which hath made us meet to be partakers of the inheritance with the saints in light,
who hath delivered us from the power of darkness,
and hath translated us into the kingdom of his dear Son;`' mark,
they were translated into the kingdom of his dear Son,
that were delivered from the power of darkness,
'`in whom we have redemption through his blood, and forgiveness of sins,
who is the image of the invisible God, the first-born of every creature;
for by him were all things created that are in heaven and in earth,
visible and invisible, thrones, dominions, principalities, and powers,
all things were created by him, and for him; he is the beginning of all things,
and by him all things consist; he is the head of the body, the church,
who is the beginning, the first-born of the dead,
that in all things he might have the preeminence; for it pleased the Father,
that in him should all fulness dwell.`'

So you may see how Christ is exalted by his saints and members here,
whom he hath sanctified, who in the body of his flesh, through death, presents you,
to wit, his church, holy and unblamable in his sight.

And the apostle said, '`I now rejoice in my sufferings for you,
and fill up that which is behind of the afflictions of Christ in my flesh,
for his body`'s sake, which is his church, warning and teaching every man in all wisdom,
that I may present every man perfect in Christ Jesus.`' Col. 1.

And the apostle said, '`if ye be risen with Christ,
then seek those things that are above, where Christ sits at the right hand of God;
for ye are dead, and your life is hid with Christ in God;
seeing that ye have put off the old man with his deeds, and have put on the new man,
which is renewed in knowledge, after the image of him that hath created him,
where there is no Greek nor Jew, circumcision nor uncircumcision, barbarian, Scythian,
bond or free, but Christ is all and in all.`'

So here is a heavenly unity, where Christ is all and in all,
and here is a perfect oneness; '`therefore,`' said he, '`whatsoever ye do,
either in word or deed, do it all in the name of Christ Jesus,
giving thanks unto God the Father, by him.`' Col. 3.

And he exhorts them to stand perfect and complete in all the will of God.
Col. 4.

And Paul writes to the church of the Thessalonians, saying,
'`to the church of the Thessalonians, which is in God,
the Father of our Lord Jesus Christ.`' This he tells them, these titles he gave them,
that the church was in God the Father, and in our Lord Jesus Christ,
both in his first and second epistles,
and said '`the very God of peace sanctify you wholly;`' and he prayed God,
'`that their whole spirit, soul and body,
might be preserved blameless,`' and how '`that they were taught of God to love one another,
and said, the Lord make you to increase and abound in love one to another,
and towards all men,
even as we do towards you;`' and that '`they might be established in holiness,
unblamable before God,
etc. and that every one of you should know how to
possess his vessel in sanctification and honour;
for God hath called us, not unto uncleanness, but unto holiness;
for God hath given unto us his holy spirit,`' as you may see, 1 Thes. 3. 4. 5.

And you may see how the apostle, in his epistles to Timothy and Titus,
exhorts the churches to holiness and pureness, and said, '`Paul,
an apostle of Jesus Christ, by the commandment of God our Saviour, and Lord Jesus Christ,
who is our hope.`'

So Christ was their hope.

And '`Paul, an apostle by the will of God,
according to the promise of life which is in Christ
Jesus;`' now would you not say these were high titles?

And to Titus, Paul wrote, and said, '`Paul,
a servant of God and an apostle of Jesus Christ, according to the faith of God`'s elect,
and the acknowledgment of the truth, which is after godliness, in hope of eternal life,
which God that cannot lie, promised before the world began,`' as in Tit. 1.

Now, would not the christians say, were not these high titles?
But I tell you, none but what appertained to them,
and what to the church belongs now in the same light, spirit and power.

And Paul wrote to the church of the Hebrews, and said, '`God, who at sundry times,
and after divers manners, spoke in times past to the fathers by the prophets,
hath in these last days spoken unto us by his Son,
whom he hath appointed heir of all things, by whom also he made the worlds,
who being the brightness of his glory, and the express image of his substance,
upholding all things by the word of his power; when he had by himself purged our sins,
sat down on the right hand of the majesty on high,`' mark, when he had purged our sins,
sat down on the right hand of the majesty on high. Heb. 1:3.
Now these did not plead for sin to the grave,
as the pretended christians do now, nor for a purgatory to purge them after death,
but he that is the purger of sins is the head of his church.

For God who hath spoken to us, to wit, his church, by his Son,
who was the speaker to Adam and Eve in paradise,
and was the speaker by his Son to the church in the primitive times,
is the speaker to his church now.

But since the apostles`' days, that the whole world has worshipped the beast,
and drank the whore`'s cup, they have gone from this speaker;
but now his church is come and coming out of the wilderness, which is the bride,
the wife of Christ the Lamb.

And so Christ is the speaker again unto his church, and who should speak unto his wife,
his church, but himself?
Being members of his body, of his flesh, and of his bone, and they are in him,
and he in them, according to his promise and prayer.

And you may see how the apostle exalts the Lord Jesus Christ,
and shows how he is the substance of all the figures and shadows,
and hath ended them all, who is come in the volume of God`'s book to do his will,
and takes away the first priesthood, and covenant and offerings,
and establisheth the second: and they that are members of him and his body,
are in the second covenant.

And so, he that is come to do the will of God, by which will we are sanctified, to wit,
the church, by the offering up the body of Jesus once for all;
so by the one offering he hath perfected forever them that are sanctified,
as you may see, Heb. 10. and he is the high priest over the house of God;
and is the new and living way for all his believers to walk in.

And you may see, in Heb. 12.
how the apostle tells the church then, '`they were to come to Mount Zion,
and to the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels,
and to the general assembly and church of the first-born, which are written in heaven;
and to God the judge of all, and the spirits of just men made perfect,
and to Jesus the Mediator of the new covenant, and to the blood of sprinkling,`' etc.

Now further, the apostle told the church of the Hebrews,
'`that they were come;`' and said unto them, '`the God of peace,
that brought again from the dead our Lord Jesus Christ, that great shepherd of his sheep,
through the blood of the everlasting covenant, make you perfect in every good work,
to do his will.`'

So here you may see, who are the sheep, and who is the shepherd;
and how the shepherd Christ Jesus makes his church, his sheep perfect.

And you may see how James,
in his general epistle encourages the church to purity and to righteousness.

And how Peter in his first epistle encourages the church, and calls them '`the elect,
according to the fore-knowledge of God the Father,
through the sanctification of the spirit unto obedience,
and the sprinkling of the blood of Jesus Christ;`' and said unto them,
seeing ye have purified your souls in obeying the truth,
through the spirit ye are to love one another with a pure heart fervently,
and being born again, not of corruptible seed, but of incorruptible, of the word of God,
which lives and abides forever.

And further, he said, '`ye are a chosen generation, a holy priesthood, a peculiar people,
that ye should shew forth the praise of him who hath called you
out of darkness into his marvellous light:`' and he tells them,
'`they as living stones, are built up together a spiritual household, an holy priesthood,
to offer spiritual sacrifices, acceptable to God by Jesus Christ.`'

Now here you may see, what heavenly and holy titles the apostle gave to those holy ones;
for he calls them a spiritual house, and an holy and royal priesthood,
and a chosen generation, a holy nation, mark, a nation, a peculiar people.

Which the christians since the apostles`' days have lost,
both the spirit and nature of this primitive church, and therefore,
they must not bear the titles, for they are gone astray from Christ;
but they who are returned to Christ the shepherd and bishop of their souls,
are his sheep, and he is the head of them, and have the same titles,
and the same spirit and nature, as they had in the primitive times;
for the head is the same, and the body is the same, glory to God forever.

And you may see how the apostle Peter writes to them
who have obtained the like precious faith with us,
through the righteousness of God, and our Saviour Jesus Christ, and encourages them,
'`to add to their faith virtue, and to virtue knowledge, and to knowledge temperance,
to temperance patience and brotherly kindness,`' etc.

And said, '`if these things be in you, and abound,
it will make you that ye shall neither be barren nor unfruitful
in the knowledge of our Lord Jesus Christ.`'

And John in his first epistle declares, what he had seen from the beginning,
which they had seen, handled, heard and looked upon, of the word of life.

And so that which was manifest unto him, he bore witness of to the church, and to others;
for he said, '`the life was manifest, and we have seen it, and bear witness,
and have shewed it unto you, that eternal life which was with the Father,
and was manifest unto us; and that which we have heard and seen, declare we unto you,
that you also may have fellowship with us, and truly our fellowship is with the Father,
and with his Son Jesus Christ.`'

'`And these things write I unto you,
that your joy might be full;`' so that the church`'s joy might be full, and said,
'`if we walk in the light, as he is in the light, we have fellowship one with another,
and the blood of Jesus Christ cleanseth us from all sin.`'

Now here is their oneness and their fellowship, as they walk in the light:
and here is the cleansing from all sin seen.

And John in his second epistle writes to the '`elect lady and her children,
whom he loved in the truth; and not he only, but all those that knew the truth,
for the truth`'s sake, which dwelleth in us,
and shall be in us forever:`' and here was a resolution and a confidence,
and he rejoiced greatly, that '`he had found of her children walking in the truth.`'

So here was their unity in their walking in the heavenly truth,
which the devil the author of all enmity is out of.

And he writes in his third epistle to Gaius,
and rejoiced greatly when the brethren certified of the truth that was in him,
and of his walking in the truth, and he said,
'`he had no greater joy than to hear of his children walking
in the truth.`' Now here was the saints joy and unity,
their walking in the truth.

And Jude the servant of Jesus Christ, and brother of James,
writes to them that are '`sanctified by God the Father,
and preserved in Christ Jesus;`' these he exhorts to '`contend for faith,
which Jesus is the author of, and to build up themselves in the most holy faith,
praying in the Holy Ghost,
and to keep themselves in the love of God;`' and
to shun all those evils mentioned in that epistle.

Now Jude told them, they were sanctified and preserved in Christ Jesus,
and they were to contend for the faith, which was delivered unto the saints,
the sanctified ones; and doth not Christ deliver it,
who is the author and finisher of it?
So all the church, the saints are to contend for that faith which saves,
which Christ is the author and finisher of.

And you may see how John exalts Christ in his writings to the seven churches, and said,
'`I, John, who am your brother, and companion in tribulations;
and in the kingdom and patience of Jesus Christ,
was in the Isle of Patmos for the word of God and testimony of Jesus.`'

So John said he was in the kingdom, mark, in the kingdom and patience of Jesus Christ,
who was God`'s faithful witness, etc. who hath loved us and washed us from our sins,
in his own blood, and made us kings and priests unto God the Father,
to whom be glory and dominion forever and ever.

Now they were made kings and priests, and washed,
and John was in the kingdom whilst they were upon the earth, as you may see.
Rev. 1.

And you may see what John said,
'`that Christ walks in the midst of the seven golden candlesticks;`' that is,
in the midst of the seven churches;
there he walks that is ascended above all that he might fill all.`'

So he who is the head of the church, walks in the midst of the churches,
though he is ascended above all.

Again he said, '`he stands at the door and knocks,
and if any man will hear his voice and open the door, he will come in to him,
and sup with him, and he with me,`' as you may see. Rev. 3.

So Christ is the head of his church, and he walks in his church, and he feeds his church,
as he is a shepherd; and opens to his church, as he is a prophet;
and oversees his church, as he is a bishop; and sanctifies and offers up his church,
as he is a priest; and he commands his church, as he is a captain and commander,
he commands and leads his church; and as he is a heavenly counsellor,
he counsels his church; and purifies his church, as he is a purifier;
and baptizeth his church, as he is a baptizer; and as he is a Mediator,
he makes their peace betwixt them and God, and gives them one faith,
who is the author and finisher of it, by which he rules in their hearts.

And as the priests in the time of the law entered within the wail,
and made intercession for the house of the Jews;
but Christ who is over the household of faith, is entered into heaven,
and is the Mediator betwixt God and man: so Christ opens, and no man can shut;
and he shuts, and no man can open; and he that hath the Son of God, he hath life;
and he that hath not the Son of God, he hath not life, so no living members;
neither hath he the head of the church, that hath not the Son.

And the apostle said, '`he is not a Jew that is one outward,
but he is a Jew that is one inward: and circumcision is that of the heart,
and in the spirit, and not in the letter.`'

So he is a christian that is one inward, that is, baptized by one spirit into one body,
and that is in the same spirit, and power,
and faith that the apostle and primitive church were in;
and he that hath not the spirit of Christ is none of his.

And the Lord promised, he would give his people one heart to do his commandments,
as in 2 Chron. 30:12.

And the Lord said, '`I will give them one heart and one way,
that they may fear me forever, and I will make an everlasting covenant with them,
and I will put my fear in their hearts.`' Jer. 32. 39.

So this one heart, and one way, is the new covenant Christ Jesus.

And so all his people are of one heart in the one head, in the one faith,
in the one spirit, in the one grace that teacheth and brings the salvation,
in the one word that reconciles them to God, which is in their hearts, and mouths,
and in the one heavenly divine light, which is the life,
by which they are grafted into Christ, having one Lord Jesus Christ,
by whom are all things, and one Lord God and Father of all, who is over all.

And in Ezek. 11:19. the Lord said, '`I will give them one heart,
and I will put a new spirit within them,
and take away the stony heart out of their flesh.`'

So these are the children of the new covenant, that have this new spirit,
and in it they are all of one heart; and so as the apostle said,
'`They are members one of another, all baptized into one body,
which Christ is the head of.`'

And the apostle said, '`The multitude of them that believed were of one heart,
and of one soul.`' This was the true church who believed in the light,
and became children of the light,
and so were grafted into Christ the heavenly root and head that bears them.

And the apostle said to the Philippians, '`That ye stand fast in one spirit, (to wit,
the church the body of Christ,) with one mind striving
together for the faith of the gospel;
+++[+++mark,]
all striving together in the unity of the spirit,
for the faith of the gospel,`' which Christ is the author of;
which gospel brought life and immortality to light,
and the faith in it preserved them in life and immortality.

So here the church was to strive for unity, but it was in the spirit.
And the apostle said, '`fulfill ye my joy, that ye be like-minded, having the same love,
being of one accord, and being of one mind.`'

So the saints were to be in one mind, and one love, as in Phil. 2:2.

And Peter in his general epistle, 1 Pet. 3:8. said to the church of Christ,
'`Finally brethren, be ye all of one mind,`' that is all the church, the holy nation,
'`having compassion one of another, and love as brethren; be pitiful and courteous.`'

And the apostle said to the Romans, '`rejoice with them that rejoice,
and weep with them that weep; be of the same mind one towards another;
mind not high things, but condescend to men of low estate;
be not wise in thy own conceit.`'

So here he exhorts the church to unity, and to shun that which would hinder it. Rom. 12:15-17.

And the apostle said, '`that ye may with one mind and one mouth glorify God,
even the Father of our Lord Jesus Christ.`' Rom. 15:6.

And the apostle further said to the Corinthians, '`I beseech you brethren,
by the name of our Lord Jesus Christ, that ye all speak the same thing,
that there be no division amongst you, that ye be perfectly joined together,
in the same mind, in the same judgment. 1 Cor. 1:10.

So here the church was to have one mind, and one judgment,
perfectly joined together in the same thing, which church Christ is the head of,
and they are the members of his body.

And the apostle said to the church of Corinth, '`finally, brethren farewell, be perfect,
be of good comfort, be of one mind, and live in peace.`' 2 Cor. 13:11.

So here the church was to be perfect, and of one mind, and then the love of God,
and his peace would be with them.

Now to Abraham and his seed were the promises made, not unto seeds as of many,
but as one, '`to thy seed,`' which is Christ.

And so the apostle tells the church,
'`ye are all the children of God by faith in Christ Jesus;
for as many of you as have been baptized into Christ, have put on Christ,
(this one seed,) for there is neither Jew nor Greek, bond nor free, male nor female,
but ye are all one in Christ Jesus.`' Gal. 3:16,28.

And so through him, to wit, Christ, '`we have access by one spirit unto the Father,
who hath raised Christ from the dead,
and set him on his right hand in the heavenly places, far above all principalities,
powers, might, and dominion, and every name that is named, not only in this world,
but also in that which is to come, and hath put all things under his feet,
and given him to be the head over all things, to the church which is his body,
the fulness of him that filleth all in all.`' Ephes. 1.

So here is seen the great power of Christ,
who has all power in heaven and earth given to him, who is the heavenly head,
that is the ruler and orderer of his church, the living members, the true believers,
that are grafted into him.

And God the Father loveth the Son, and hath given all things into his hand,
and he that believeth in the Son of God, hath everlasting life, mark, hath it;
and he that believeth not in the Son, shall not see life,
but the wrath of God abides upon him. John 3:36.

And Christ saith, '`verily I say unto you, he that heareth my word,
and believeth on him that sent me, hath everlasting life,
and shall not come into condemnation, but is past from death to life.`' John 5:24.

Now this is and was their belief in the light, that were the children of the light,
and born of God, which are the living members of the living head,
that have this everlasting life.

And Jesus said, '`I am the bread of life, he that cometh to me shall never hunger,
and he that cometh to me shall never thirst.`' And again Christ said,
'`verily I say unto you, he that believeth on me hath everlasting life.`'

And Christ further said, '`he that believeth on me, as the, scriptures have said,
out of his belly shall flow rivers of living water.`' John 7:38.

Now these believers were more than formal historical believers; for the devil believed,
and the Jews believed, but they did not believe in Christ the light:
for the Jews`' belief was but an historical belief,
and the devil`'s belief did not graft him into Christ:
and wicked men will say they believe, but they and the devil have not eternal life,
nor the Jews; for Christ hath destroyed death, and the devil the power of it;
neither have the Jews eternal life, nor any wicked men by an historical belief,
except they believe in Christ the light, who is the life.

But the true belief is that which passeth from death to life,
by which belief they are grafted into Christ; and every true believer hath eternal life,
and he shall not perish, but have everlasting life, as God hath said.

Now Christ is the heavenly, living, spiritual head of these his heavenly, living,
spiritual members: and he that sanctifieth, and they that are sanctified are all of one,
for which cause he is not ashamed to call them brethren, saying,
'`I will declare thy name unto my brethren,
in the midst of the church will I sing praise unto thee.`'

So here you may see the unity and the love that is betwixt Christ and his church,
which is his body, which he is the head of.

And the apostle said, '`but we have the mind of Christ,`' (we the church,) the, body,
the living members, the household of faith, which faith Christ is the author of,
the holy nation that are baptized by one spirit into one body,
which Christ is the head of, and so they have the Son of God,
and they that have him have life eternal, and this life is in his Son,
as you may see in 1 John 5:11, to the end.

So here you may see the heavenly unity and agreement betwixt the heavenly man,
and his heavenly members, which he prayed for, and the apostles exhorted to,
which the saints did and do enjoy, that perfect oneness in the Father and in the Son,
and the heavenly, spiritual fellowship with the Son, and with the Father in his light,
grace, and truth, and heavenly spirit and glorious gospel.

And therefore, this may encourage all to keep in this heavenly oneness and agreement,
which they have in the heavenly man Christ Jesus, and one with another,
who reconciles in one, both things in heaven, and things in earth,
and he is the living head of his church, that be the living members,
the true believers born of God, which have overcome the world, and are grafted into him.

Now this is the church, which is the pillar and ground of truth,
which the gates of hell cannot prevail against;
for Christ who is the head of his church hath power over death and hell,
and the devil the power of death,
and by his power casts him and it into the lake of fire.

Glory be to God and the Lamb, who is over all from everlasting to everlasting,
blessed forever.

Now Adam and Eve disobeying the command of God which he taught them,
by that they lost the image of God, and righteousness and holiness,
and the power which God had given them,
and in it had set them over all the works of his hands; so he came into misery,
death and darkness.

And this death reigned from Adam till Moses, and the Lord gave his law by Moses,
and the Lord poured out his spirit upon the house of Israel,
that they might understand his law, which is spiritual:
now the Jews erred from this spirit that God had poured upon them,
and then they erred from his law, and then they erred from cleanness, and holiness,
and righteousness, purity and uprightness, and perfection, and so there came rents,
schisms and divisions amongst them,
when they went from the spirit of God and God`'s holy law, and then they broke to pieces,
and into sects one against another, but all against the prophets and Christ;
but such as kept in the spirit of God, and in his law.

Such believed in Christ, and received Christ when he came.

The law came by Moses to the Jews, so grace and truth is come by Jesus Christ; and God,
who said he would '`pour out his spirit in the last days
upon all flesh,`' which days are the days of Christ,
and he having tasted death for every man,
and was an offering for the sins of the whole world;
and the apostles were sent by Christ to preach the gospel,
which was preached in every creature under heaven:
and Christ doth enlighten every man that comes into
the world with the life which is in the word,
and saith, '`believe in the light.`'

So now all christians, and the world that do not believe in the light,
that they may become children of the light,
nor receive the gospel which is the power of God in every creature under heaven,
if they do not receive the power and the light which enlightens all,
and the grace of God which brings salvation,
that hath appeared unto all men to teach them.

I say, if they do not receive this light, and this grace, and this spirit,
which God hath poured upon all flesh, the world, christians, and Jews,
though they may make a profession of God and Christ, yet if they receive not his light,
his spirit, his grace and gospel, but do err from the spirit of grace,
and abuse his power, they are all in confusion and rents,
and divisions one amongst another, being erred and rent from the gospel,
and from the light, and from the power and spirit of God,
and so from the church and Christ the head thereof,
and are not like to come into unity and concord;
but as they believe in the light and walk in the light, and in the spirit,
and their faith standing in the gospel the power of God,
and in the grace to teach them and bring their salvation; for in the grace, light, power,
and spirit, and truth are all united into Christ,
and to the Father in the perfect oneness.

[.blurb]
=== Now concerning Schisms and Errors amongst the Christians

[.numbered-group]
====

_First,_ you presbyterians and other sects, that say you have not the same Holy Ghost,
and spirit, and power as the apostles and primitive church had;
and the papists manifest by their fruits,
they have not the same power and Holy Ghost as the primitive church had; it is,
because you are erred from it;
for you that be erred from the same Holy Ghost the apostles were in,
which led them into all truth, and which reproved the world of their sin, righteousness,
and judgment, then how can you have the same spirit they had?

Now the reason why you have not the same grace, light, and spirit, is, first,
because you hate the divine light, which is the life in Christ,
which he commands you to believe in, and so to become children of light.

And so you hate that which should unite you to Christ the head,
and to make you members of his body, and to graft you into Christ by belief.

So hating the light you are erred from the body, and are not of the body of Christ,
of his true church.

[.numbered]
_Secondly,_ you turning not at the reproof of the Holy Ghost, which is for your sin,
and for your righteousness, and judgment, and unbelief,
you cannot be lead into all truth, so no ministers of the truth,
and so are in no true substantial, standing comfort,
seeing all the true comfort is in the Holy Ghost, which is the true comforter,
and takes of Christ, and gives unto them that are led by the Holy Ghost.

So by this you cannot receive any thing from Christ, as you say, now from heaven;
for how should you, if you will not turn at the reproofs of the Holy Ghost,
which proceeds from the Father and the Son; for it takes of Christ,
and gives unto them that are led by him, as is aforesaid.

[.numbered]
_Thirdly,_ you say, there is no assurance of salvation on this side the grave;
we grant that you have none, but the church of Christ hath assurance,
though you have not; and what is the reason you have not?
Because ye turn the grace of God into wantonness,
and walk despitefully against the spirit of grace: and some of you say,
the grace of God is not sufficient to teach, and bring their salvation,
and therefore they dare not trust in it, the grace of God which taught the saints,
and brought their salvation, and taught them to deny ungodliness and worldly lusts,
and established their hearts.

====

And this grace (God said to Paul,) was sufficient;
and this grace the apostle exhorted the church unto, which the true church knew then,
it was sufficient to teach them, and to bring their salvation;
and the true church knows it so to be now.

And now you will not come to this grace of God, which comes by Jesus,
and then how can you come into the covenant of grace,
and to have assurance of your salvation, which this grace brings,
which was the teacher of the church in the primitive times,
and is the teacher of the church now, which is coming out of the wilderness,
and from under the worship of the beast and dragon,
and are coming out of Babylon and confusion?
They know this grace of God is sufficient to teach them, and to bring their salvation,
who are the spouse of Christ the bride, from whence this grace and truth comes,
as it did in the apostles`' days.

So God pouring out his spirit upon all flesh, if all flesh err from this spirit,
they err from God and his way, and his church, and Christ the head of it;
and then how can they see Christ their salvation, when they err from his spirit?

And you that say, you have not the same spirit of Christ, as the apostles had,
the apostle tells you, '`that they that have not the spirit of Christ,
are none of his;`' and so manifest yourselves to be none of Christ`'s,
and to be but christians in words, but not in the spirit.

For the Jews in the letter and outward circumcision were looked upon to be no Jews;
therefore, how can you be looked upon to be true christians,
that are not in the same spirit of Christ, as the apostles were in, seeing he tells you,
'`that he that hath not the spirit of Christ is none
of his?`' For these may have the praise of men,
but what praise of God have they?
For God hath his praise of all them that walk in his spirit.

And so now it is clear, you being erred from the grace, and from the spirit,
and from the gospel, and from the living, pure, divine faith,
which Christ is the author of; therefore, you make faiths.

And being erred from the spirit, as I said before, you are erred from the body of Christ;
'`for by one spirit are all the church baptized into one body,
and so are all made to drink into one spirit;`' and this is their spiritual unity.

But now you being erred from this spirit,
and from this baptism that plungeth down sin and corruption, and imperfection,
you do plead for sin, and its body, and imperfection to the grave;
but the church of Christ is to be perfect, and never pleaded for any such thing;
but what can you plead for else, that are unbaptized with the spirit,
and not circumcised in your hearts therewith?

And so being erred from this faith that gives the victory,
and from the spirit that doth baptize,
and from the light which Christ commands to believe in;
and from the grace which brings salvation; and from the gospel,
which brings life and immortality to light: and from the faith, which is the victory,
which brings to build upon Christ the sure foundation;
and likewise erred from the Holy Ghost, which led the true church into all truth,
and reproves the world of sin, etc.
So in this you are erred from the body of Christ, his church,
and from him the living head, and front God and his way; though without this light,
faith, grace, spirit, gospel, and Holy Ghost,
you may make a profession of the scriptures, and of the prophets`' and apostles`' words,
and have many churches amongst you in the world, and in Christendom.

And so there you have many heads and many bodies which you call churches,
both in Christendom and in the world,
being erred and rent from that which leads into the true church,
which Christ is the head of.
And now, as it sometimes happens and falls out,
that when some of your church members forsake you, and go to other churches,
then you cry error, and heresy, and schism; when alas! you are all in the error,
and schismatics, teaching the insufficiency of the light,
and of the grace and of the spirit to lead into all truth:
and confess that you yourselves are not in the same
spirit or Holy Ghost the apostles were in;
and then are you not all in schisms and rents from the spiritual body and head:
and therefore, when one plucks members from one church to another,
you do but pluck from one schism to another, and from one error to another.

For all, both Turks, papists, and all other sects in the world,
until they do turn at the reproofs of the Holy Ghost, and at the reproofs of the light,
and believe in it, there is no coming to be grafted into Christ the head, but by belief:
and no coming into all the truth of the prophets`', Christ`'s, and the apostles`' words,
but by being led by the same Holy Ghost, that gave them forth.

But if any turn to the grace and Holy Ghost that doth reprove them of their sin,
righteousness and judgment, and come to believe in the light,
and so to be children of the light,
and leave those churches that be erred from the light and spirit,
then all the sects will rise against them,
though they do differ one amongst another in their error and schism,
being rent from the body of Christ, and from him the head; and erred from the spirit,
grace and truth, which came from him and by him; for John truly said,
and called the false church,
'`the mother of harlots:`' now these harlots doth harlot from the light, from the grace,
from the faith and true church, and Christ the head and husband of his church.

And John, said this '`mother of harlots sits upon the beast,
and the beast rose out of the earth,
and the dragon that is out of the truth gave his power to the beast.`'

So the beast is from the earth, and the devil is out of the truth,
and the mother of harlots is harlotted from the power as the apostles were in;
so she has corrupted the earth, and is the abomination of the earth,
and so would plead for corruptions, she and her harlots to the grave;
for how can they plead for pureness, and perfection,
being erred from the spirit that mortifies?

But Christ Jesus`'s everlasting gospel is preached again,
that was preached in the apostles`' days,
which bringeth life and immortality to light in people,
who have been darkened by the whore, beast and dragon, that are out of the truth.

So they come from under the beast`'s worship, and the dragon`'s,
and cannot touch the whore`'s unclean cup, that are whored from the spirit, light, grace,
and truth, and faith the apostles and the true church were in.

And that is the faith, that is the victory, and the belief in the light,
by which they are children of light, and overcome the world,
and are passed from death to life, and so are grafted into Christ the heavenly head,
and so are members of the body, as the church in the primitive times were,
and have the same head, and the same Holy Ghost,
and the same spirit of truth that leads into all truth, of the prophets`', Christ`'s,
and the apostles`' words, which were given forth by the Holy Ghost:
and so such have the comfort of Christ, and of the Holy Ghost,
and the comfort of all the scriptures given forth from the Holy Ghost,
and the comfort of the Father and the Son; and sing praises and glory and honour,
over all unto him, that lives and reigns forever and ever.

And much might be written, of the state of the true church,
and of the state of the false, which is gotten up since the apostles`' days.

But the church that was and is, is in the head that was and is, in the power, and grace,
and spirit, and faith, and belief, which was, and is,
by which the church is united together in one, with Christ the one holy, and heavenly,
and spiritual head, (and over the heads of the beast, and dragon,
and whore,) to whom alone belongs all holy praises, glory and honour over all,
from everlasting to everlasting.
Amen.

And the saints had, and have, both assurance and confidence; for David saith, '`O,
thou God of our salvation, who art the confidence of all the ends of the earth,
and of them that are afar off upon the sea.`' Ps. 65:5.

And Solomon said, '`in the fear of the Lord is strong confidence,
and his children have a place of refuge.`' Prov. 14:26.

Now they that be out of the fear of God, and in the evil, undeparted from it,
are not like to enjoy this confidence.

And the Lord said, '`the work of righteousness shall be peace,
and the effect of righteousness, quietness and assurance forever.`' Isa. 32:17.

Now they that have this peace, and quietness, and assurance, forever,
must be in this work.

And Paul preached the kingdom of God,
and teaching those things which concern the Lord Jesus Christ, with all confidence. Acts 28:31.

And the apostle said,
'`that in Christ Jesus our Lord we have boldness and access with confidence,
by the faith of him,`' (to wit, Christ.) Eph. 3:11-12.

So here the saints hath both boldness and confidence, and access to God,
through Jesus Christ.

And the apostle speaks to the Colossians, '`that their hearts might be comforted,
being knit together in love,
and unto all riches of a full assurance,`' (mark,) a full assurance of understanding,
to the acknowledgement of the mystery of God the Father, and of Christ. Col. 2:2.

And Christ, as a Son, is over his own house; whose house we are of; (to wit,
the true church,) if we hold fast the confidence,
and the rejoicing of the hope firm unto the end. Heb. 3:6.

So these had a confidence, and they were to hold it fast.
And he desired,
'`that every one of the church do shew forth the same diligence
unto a full assurance of hope to the end.`' Heb. 3:14-6.

'`Therefore,`' said he, '`let us draw nigh with a pure heart, in full assurance of faith,
having our hearts sprinkled from an evil conscience,
and our bodies washed with clean water: cast not therefore away your confidence,
which hath great recompence of reward.`' Heb. 10:22,35.

So here the church was to be in full assurance and confidence, in the Lord Jesus Christ,
through that faith they had from him.

And John said to the church, '`these things I write unto you,
that you believe in the name of the Son of God, that ye may know,
that ye have eternal life: and this is the confidence, that we have in him,
that if we ask any thing according to his will, he heareth us; and we know we are of God,
and the whole world lieth in wickedness: and we know that the Son of God is come,
and hath given us an understanding, that we may know him that is true;
and we are in him that is true; and this is the true God and eternal life.`' 1 John v.

So here was a confidence, and an assurance, and a knowledge that the church then had,
and now have, in the same belief in the light, who are become children of light,
and in the same belief, and same spirit.

For, as the apostle said, '`with the heart man believeth unto righteousness,
and with the mouth confession is made unto salvation.`' Rom. 10.

So if there be but this belief in the heart, there will be confession with the mouth.

So you may see, the saints had assurance, and confidence in their faith,
and in their salvation, Christ Jesus; and they were exhorted to an assurance,
and confidence, and boldness in Christ Jesus, the life and their salvation,
and to rejoice in him, their head, in whom they had victory,
who made them more than conquerors.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Marshgrange, the 9th of the 3d month, 1676.
