[.style-blurb, short="To all the Kings, Princes, and Governers"]
== To all the Kings, Princes, and Governors in the whole world: and all that profess themselves Christians, and others, to read and consider.

[.heading-continuation-blurb]
This was upon me from the Lord to write unto you.--By G. F.

And the word of the Lord is to you, that God is come,
and coming to teach his people himself, by his Son Christ Jesus.

For the Lord God that made all things in six days, and man and woman in his image,
and placed them in paradise; God Almighty was their teacher, their guide,
and their orderer, who did teach them what to do, and what to leave undone;
and as long as they kept under God`'s teaching, they were happy,
and kept in the image and likeness of God, and in his righteousness and holiness,
and in the paradise of God.

But when they forsook God`'s teaching, and disobeyed God`'s command,
and hearkened unto the serpent`'s teaching, and obeyed his command, they lost the image,
and righteousness, and holiness, and likeness of God, and were driven out of paradise,
and so came into darkness, and the fall and fell into sin and misery,
and into the imperfect and corrupt state.

And so death reigned from Adam to Moses, and so as by the offence of one, (to wit,
Adam,) came judgment upon all men to condemnation.

Even so by the righteousness of Christ,
the free gift is come upon all men to justification of life.

And so death reigned from Adam till Moses, and the law and the prophets were until John.

And now Christ being come, the seed of the woman to bruise the serpent`'s head, he saith,
'`learn of me, I am the way, the truth, and the life,
and no man comes to the Father but by me.`'

So here you may see Christ is the teacher again, who is the way to God,
who bruises the head of the serpent, the false teacher, that led Adam and Eve from God,
and is the head of all false teachers.

'`And God so loved the world, that he gave his only begotten Son into the world,
that whosoever believeth in him, shall not perish, but have everlasting life.`'

And moreover, God saith, '`this is my beloved Son, in whom I am well pleased,
hear ye him.`'

So here all people are to believe in, and hear the Son, and learn of him.

And the apostle saith to the Hebrews, '`God, who at sundry times, and in divers manners,
spoke in times past to the fathers by the prophets,
hath in these last days spoken unto us by his Son,
whom he hath appointed heir of all things,
by whom also he hath made the worlds.`' Heb. 1:2.

So here you may see that God, who was the first speaker in paradise to Adam and Eve,
was the speaker again to the apostles, and the church in the primitive times,
by Christ Jesus, who '`renews man up into the image of God, and righteousness,
and holiness,`' as man was in, before he fell.

So the same God, I say, is the speaker now in these days, by Christ his Son,
to his people, as he was in the apostles`' days; and he renews us up in the image of God,
and righteousness, and holiness, as they were in before they fell.

And this is my message to you all.

That God, who was the first teacher and speaker to Adam and Eve in paradise,
and was the speaker and teacher to the apostles and church in the primitive times,
is now come to teach his people himself by his Son, if ye will hear him, as in Heb. 7.

And as the apostle saith, '`refuse not him that speaketh from heaven,
for if they escape not that refused him that spake on earth,
much more shall not we escape if we turn away from
him that speaks from heaven.`' Heb. 12:25.

[.discourse-part]
_Object._
But now you may object, and say, how shall we hear him?
And where, and when?

[.discourse-part]
_Answer._
God poured out his spirit upon the house of Israel, to whom he gave his law,
which was holy, just, and good; that by God`'s spirit that was poured upon them,
they might understand his law, and hear his voice; as in Ezek. 39:29.

And Moses said, '`like unto me will God raise up a prophet,
him shall ye hear in all things.`'

'`And it shall come to pass that every soul that will not hear
that prophet shall be destroyed from amongst the people.`'

And this prophet is Christ Jesus, as you may see, in Acts 3:24. to the end,
whom God hath raised up.

And in Joel 2. and Acts 2.
they said, '`how that God would pour out of his spirit in the last days, upon all flesh.`'

So that now this spirit God hath poured out, and is pouring out upon all flesh,
(so God doth not here respect some flesh, and leave out others,
or make a sect,) but pours out his spirit upon all flesh, to wit, Jews and Gentiles;
for he had poured out his spirit upon the house of Israel in the former times;
but now in the last days, or day of Christ, the christian days,
'`he has poured out his spirit upon all flesh.`'

That with, and by this spirit, all flesh might see the salvation of God,
and by this spirit they might all hear God and Christ, his Son, by whom God speaks,
who is the alone first and last true teacher and speaker.

And as John saith, '`in the beginning was the word, and the word was with God,
and all things were made by him,
and without him was there not any thing made that was made, and in him was life, (to wit,
the word,) and the life was the light of men,`' and that '`was the true
light which lighteth every man that cometh into the world,`' to wit,
the life that is in the word, which was before any thing was made.

So this light which is the life in the word, is not natural nor created.
And Christ saith, '`believe in the light,
that ye may become children of the light.`' John 12:36.

And so by belief in the spiritual, heavenly and divine light,
which is the life in Christ the word, which was in the beginning,
by which all things were made: they came and come to be grafted into Christ,
the heavenly root that bears them, and so become children of the light.

So here you may see Christ Jesus, the second Adam, the Lord from heaven,
who is the light of the world, and lightens every man that cometh into the world, saith,
'`believe in the light,
that you may become children of the light;`' and this is the heavenly,
divine light that doth let you see all your sins that you have acted or committed,
and all your evil words or thoughts that you have ungodlily thought or spoken;
and so the same light which lets you see all your sins,
will also let you see your Saviour Christ Jesus,
from whence the light doth come to save you from your sins.

And if you do evil, and hate this light, and will not come to it,
because it doth reprove you, this light will be your condemnation.
John 3.

For the apostle saith, '`whatsoever doth reprove and make manifest, is light.`'

And Christ was an offering for the sins of the whole world,
therefore all are to look unto him.

And he '`is a propitiation for the sins of the whole world,
and hath tasted death for every man;`' as in Heb. 2:9. and 1 John 2:2.

'`And the grace of God that brings salvation, hath appeared to all men,
teaching us (to wit, the true christians,) that denying ungodliness and worldly lusts,
we should live soberly and godly in this present world.`' Tit. 2:11-12.

Now this was and is all the true christians`' teacher,
the grace of God which brings their salvation, which hath appeared unto all men.

So if all men have and know salvation, it is brought to them by this grace of God,
their teacher; which grace brought salvation to the church in the primitive times,
and which grace brings the salvation to the true church now in our times.

[.discourse-part]
_Object._
Now if you should enquire, or ask from whence comes this grace?

[.discourse-part]
_Answer._
The law came by Moses to the Jews, the house of Israel,
upon whom God poured out of his spirit that they might understand his law.

But this grace of God and truth comes by Jesus Christ, which hath appeared unto all men,
to teach them and bring their salvation.

Now such as turn it into wantonness,
and walk despitefully against the grace their teacher,
unto such it does not bring their salvation, but woe is pronounced against such,
as you may read in Jude.

For such as turn the grace of God into wantonness, deny the Lord that bought them,
and deny the grace of God their teacher, which should bring their salvation.

And '`Christ, who has tasted death for every man,
and was an offering for the sins of the whole world,
has enlightened every man that cometh into the world;`'
so his light hath appeared unto all,
that they might come to it, and believe in the light;
and his grace hath appeared unto all men, to teach them, and bring their salvation.

Now whilst Christ was with his disciples,
he sent them first to preach salvation to the lost sheep of the house of Israel,
and not to go into the way of the Gentiles; and when he gave them his commission,
he said unto them, '`freely you have received, freely give.`'

And after Christ was risen from the dead, he gave his disciples a larger commission,
and bid them then '`go into all nations,
and preach the gospel to every creature under heaven.`'

So God having poured out his spirit upon all flesh,
that by the spirit they might understand his gospel,
and by his light which enlightens all men, they might see it;
and by his grace which hath appeared unto all men,
they might receive his gospel which was sent down from heaven, as Peter says,
and so not from men.

And the apostle said, '`God would judge the world according to his gospel,
by the man Christ Jesus;`' that is according to the invisible power,
the everlasting gospel which is preached to every creature under heaven,
according as they receive it and obey it; or do not receive it, but disobey it.

And so this everlasting gospel being preached again, and received again,
as it was in the apostles`' days, which brings life and immortality to light,
by which we see over the devil that has darkened us from this life and immortality,
who led Adam and Eve into the fall from the image of God.

And so the glorious fellowship of the gospel, and salvation is known again,
and received and obeyed by us, the people of God, called Quakers,
who know his voice that shakes the heavens and the earth, that that may appear,
and that has appeared that cannot be shaken.

And so all people upon the face of the earth, must come to the spirit,
that God has poured upon all flesh, and know the spirit in their hearts,
and the truth there, that by this spirit they may be baptized and circumcised;
which circumcision of the spirit will cut off sin and death, and imperfection,
which has gotten into them by disobedience and transgression;
and that they may worship and serve God in the spirit and in the truth;
and this spirit and truth must be in every man`'s and woman`'s heart.

And this is the worship that Christ,
the spiritual and heavenly man set up above sixteen hundred years ago,
when he put down the worship at the mountain, where Jacob`'s well was, and at Jerusalem,
where the temple was.

Now in this, the standing, perfect, and catholic worship in the spirit, and in the truth,
which the devil is out of, must God the Father be worshipped.

Now Christ, after he was risen, he sent the Holy Ghost, according to his promise,
which should lead the disciples into all truth; and he said,
'`it should reprove the world of sin, of righteousness, and of judgment.`'

So all the world have a judgment, and a righteousness; but the spirit of truth,
(which leads the true christians into all truth, to Christ, from whence it comes,
their Lord and righteousness,) reproves the world for their sin, for their judgment,
and for their righteousness.

So all the world must turn from their righteousness, their judgment, and their sin,
which they are reproved of, if they will be led by the spirit of truth,
which is the true christian`'s leader and guide into all truth.

And this is the spirit of truth that shows the true christians things to come;
and this is the spirit which Christ saith, '`shall glorify me; for it shall take of mine,
and show it unto you,`' to wit, the christians.

And this spirit of truth doth all the true christians
witness which proceeds from the Father and the Son;
and this spirit of truth leads us out of all error into all truth, all such as are led,
and guided, and taught by it, up to God from whence it comes.

And so up to his teaching, for it was God that taught Abraham, Isaac, Jacob, and Moses,
and all the prophets, and is not God the same?
And doth not Moses say,
'`would to God that all the Lord`'s people were prophets;`' and he rebuked
him that would have him to forbid them that were prophesying in the camp,
as in Numb. 11.

And does not Isaiah say, '`all thy children shall be taught of the Lord,
and great shall be the peace of thy children.`' Isaiah liv.

And does not Christ Jesus say, '`no man cometh to me except the Father,
which hath sent me, draw him,`' and I will raise him up at the last day.

And further Christ saith, it is written in the prophets,
'`they shall be all taught of God;`' every man therefore that hath heard,
and that hath learned of the Father, cometh to me.

And doth not Jeremiah say by way of prophecy, speaking of the new covenant,
'`I will put my laws in their inward parts, and write them in their hearts,
and I will be their God, and they shall be my people,
and they shall teach no more every man his neighbour, and every man his brother, saying,
know the Lord, for they shall all know me from the least of them,
to the greatest of them, saith the Lord; for I will forgive them their iniquities,
and I will remember their sins no more.`' Jer. 31:34.

'`And I will give them a heart to know me, that I am the Lord,
and they shall be my people, and I will be their God,
for they shall turn unto me with their whole hearts.`' Jer. 24.

And in Jer. 30:22. '`ye shall be my people, and I will be your God.`'

And in Heb. 8.
doth not the apostle show there the fulfilling the old covenant, saying,
'`they shall wax old as a garment,`' and preacheth up the new covenant?
And are not these the days that are the christian days, the days of the new covenant,
wherein all shall know the Lord.

Now let all Christendom, which professes the new covenant, Christ Jesus,
examine themselves; has God written his law in your hearts?
Hath he put it into your minds?
That you can say God is your God, and you are his people,
and that you need not to teach every man his neighbour, and every man his brother,
saying '`know the Lord,`' and that you do all know God,
from the greatest to the least of you.

So if you know this, you are under God`'s teachings and his work,
who is at work in your hearts.

And can you say as the christians did in the apostles`' days,
we know the Son of God is come,
and has given us an understanding that we may know him that is true,
and we are in him that is true, even in his Son Jesus Christ;
and whosoever believeth that Jesus is the Christ, is born of God;
and he that believeth on the Son of God, hath the witness in himself;
and he that hath the Son of God, hath life; and he that hath not the Son of God,
hath not life?

Come now all you that are called christians, try your belief; are you born of God?
Have you the witness in yourselves?
Have you the Son of God?
Then ye have life: do ye know that ye are of God?
Do ye know the Son of God is come?
Has he given you an understanding?
Do ye know him that is true; to wit, Christ?
And are you in him that is true?
read 1 John v.

For the apostle said, '`after they believed, they were sealed with the spirit of promise,
and they could set to their seal (that the spirit
had sealed them with,) that God was true in his prophets,
and in his Son, and in all his promises.`'

And does not the Lord say, '`that he hath given Christ for a witness and a leader,
and a commander to the people?`' Now, is not he come?
And is he not God`'s true and faithful witness?
And is he your leader and commander?
Examine yourselves. Isa. 55.

All that call yourselves christians, are not you to follow his leading by his power,
light, and spirit, and grace, and gospel, and obey his commands?

And does not God say, '`I will give him for a light to the Gentiles,
that he may be my salvation to the ends of the earth?`'

So he that is the light to the Gentiles, is God`'s salvation to the ends of the earth.

So with the light as I said before, you may see your sins,
and with the light you may see Christ your salvation.

And Christ is he that says to the prisoners,
'`go forth; and to them that are in darkness, show yourselves;`'
and so he is the feeder of them that hunger and thirst,
and the preserver, and leads them; even by the springs of water shall he guide them;
as in Jer. 49.

So now Christ is come, and you that are called christians will confess him;
but how does he exercise his offices in you, or amongst you?

His office, as he is a counsellor; do you hear his voice from heaven,
concerning your heavenly state: his office,
as he is a leader to lead you out of sin and evil, and to rule in your hearts by faith,
as a commander: his office, as he is a shepherd, are you his sheep?
And do ye hear his voice?
For Christ saith, '`I am the good shepherd, and give my life for the sheep:`' and again,
'`I am the good shepherd, and know my sheep, and I am known of mine.`'

And '`he calleth his sheep by name, and leadeth them out;
and when he hath put forth his sheep, he goeth before them; and his sheep follow him,
for they know his voice.`'

Now consider, doth Christ exercise this office of a shepherd amongst you?
Do you follow him?
Do ye know his voice?
And doth he lead you in and out into his pastures of life?
Or do ye know the voice of the hireling and stranger, and follow them?
Which his sheep will not.

And likewise, how doth Christ exercise his office, as he is a bishop to oversee you,
who is the heavenly and spiritual man, with his heavenly spirit, light, and grace,
and the head of his church.

And how does Christ exercise his office, as he is a priest amongst you,
who has died for you?
Do ye feel his blood sprinkling your hearts, and his pure water washing you,
and he sanctifying of you, that he may present you holy, without spot or wrinkle,
and without blemish to God.

And how do ye feel Christ exercising his office as a prophet amongst you?
Do you hear him in all things?
Doth he reveal the Father to you?
For none knows him nor the Father, but by revelation?
Doth he open the book of conscience to you?
And the book of the law, and the book of the prophets, and the book of parables,
and the book of life?
That you may see your names written in the book of life, and Christ,
the end of the law and the prophets, and the sum and substance of all,
who is the '`rock of ages,`' your rock in this age to build upon,
who is the foundation of many generations,
and the foundation of the prophets and the apostles,
and your foundation now to build upon.

And how doth he exercise his kingly office amongst you, or in you?
Doth he rule in your hearts by faith?
As he did in the church in the primitive times:
so is Christ the heavenly and spiritual man your ruler, by his power, and faith,
and spirit, and grace in your hearts.

And doth not the apostle bid the church in his days,
to '`look unto Jesus the author and finisher of their
faith:`' and now must people look any where else,
but to Jesus the heavenly and spiritual man,
to be the author and finisher of their faith.
Is there any faith that will save, but that which Jesus is the author of?
Who purifies their hearts, and gives them access to God;
or can they please God in any other faith, but this which Jesus Christ is the author of?
And is not this the faith that all the saints are to contend for?
Which is holy, precious, pure, and divine,
which Christ the holy and spiritual man is the author of;
and is not this the one faith which they have from the one Lord?
Who is the one baptizer with his one baptism, into one body, by one spirit,
who thoroughly purgeth the floor of men and women`'s hearts,
and '`burns up the chaff with unquenchable fire,
and gathers his wheat into his garner:`' and so are not
all the true christians to walk in the steps of this faith?
Which is the faith of Abraham, which is the gift of God;
and '`Jesus is the author of it,`' in which faith they have all unity.

And is not this the faith that works by love?

And doth not the apostle tell the church of the Corinthians, that if they had not love,
all their prophesying and their speaking, '`though with the tongues of men and angels,
yet if they had not charity, (or love,) it was but as sounding brass,
and tinkling cymbals.`'

And now let Christendom see and examine themselves,
whether they have had love one to another, who have the tongues,
and can speak and understand history and languages with them;
yet if ye have not this love and charity,
are ye not as sounding brass and tinkling cymbals:
though ye may have all the scriptures from Genesis to the Revelations;
yet being out of this love, ye are but as sounding brass, and as tinkling cymbals.

And doth not the apostle say to the church of the Galatians,
'`he that is born of the flesh, persecutes him that was born of the spirit;`' and mark,
is it not even so now?

Doth not he that is born of the flesh,
succeed his forefathers in persecution of him that succeeds in the birth of the spirit,
in the spiritual wisdom, in the spiritual way, and in the spiritual worship;
in the spiritual praying, and in the spiritual baptism, and spiritual circumcision;
and walking in the spirit, and living in the spiritual fellowship,
the spirit that leads all the sons of God, that keep the testimony of Jesus,
the spirit of prophecy; that keep the precious, divine, and holy faith,
which Jesus is the author and finisher of, who is led by this spirit of truth:
that Christ promised before his resurrection he would send after his resurrection,
which leads his disciples, his learners into all truth:
are not these the children of the free woman, '`Jerusalem that is above,
the mother of us all?`' and are not these them that
are persecuted by the birth of the flesh?

So these true christians and sons of God, that are led by the spirit of God,
cannot own any mother below, but Jerusalem that is from above.

So let Christendom see whether they have not been of that
birth that persecutes him that is born of the spirit,
and gone contrary to Christ`'s commands, who says,
'`love one another,`' and '`love your enemies;`' and let their teachers
see whether they have not gone contrary to Christ`'s commands,
who said, '`freely ye have received, freely give;`' and when they had returned back,
and had done their message, Christ asked them, '`whether they lacked any thing?
and they told him no.`'

And the apostle Paul that was converted after Christ was risen; he said,
'`he coveted no man`'s silver or gold, nor apparel, but laboured with his own hands,
that he might keep the gospel without charge,`' and therein was his glory.

And now have ye succeeded the apostles in their heavenly birth,
and in obedience to his command and example aforesaid?

And Moses said, '`would all the Lord`'s people were prophets,`' who was a judge,
a captain, and a leader.

And I would to God that all the kings and rulers of the earth were of his mind.

And does not the apostle say, '`that God would pour out his spirit upon all flesh,
and his sons and daughters should prophesy, and the old men should dream dreams,
and the young men should see visions,`' etc.

Now, what is the matter?
seeing God doth '`pour out his spirit upon all flesh,`'
that your sons and daughters do not prophesy,
and that your old men and young men,
and hand-maids and servants have not their dreams and the visions of God.
Is it not because that you vex, and quench, and grieve the spirit of God,
and rebel against it in your hearts, and so comes to be the birth of the flesh,
and persecutes him that is born and led by the spirit?

And doth not Christ say, '`as ye would that men should do unto you,
do ye also to them likewise?`' And christians,
if '`they love them only that love them again, what thanks was this?`' for sinners do so;
or '`do good unto them that do good unto you again?`' Sinners did so: but Christ says,
'`you must love your enemies, and do good unto them that hate you.`' Luke vi.

And doth not James tell you, that if you fulfill the royal law,
according to the scripture, '`thou shalt love thy neighbour as thyself?`'
Jam. 2:8.

Now if you love your neighbour as yourselves, ye will not persecute about religion.

And let all nations in Christendom, and elsewhere, consider this;
let no neighbour sect in Christendom (as there is many,) persecute, kill, or banish,
prison, or spoil the goods of his neighbour sect about religion,
because he will not be of his religion, and of his faith: for the apostle tells you,
'`they themselves had not power over the saints`' faith:`' for '`if you do unto all
men as you would have them do unto you,`' which is Christ`'s and the apostles`' doctrine,
you would not have any to banish, prison, kill, or spoil your goods,
concerning your religion; then pray see you do not so unto others,
and see if you can keep this royal law: for would you have the Turks, or Tartars,
or Jews to kill, or imprison, or spoil your goods about your religion?
You say no; then do not you do so to them, nor to one another that are called Christians,
that may differ from you in your religion?
For you would not be so served yourselves,
seeing that the conformity lies to the image of God, to which all must be conformable;
and in that the true uniformity lies;
and unto his righteousness and holiness as man was in before he fell:
and this is Christ`'s and God`'s work to create them anew,
and renew them again into his image:
and '`God is the rewarder of all them that diligently seek him,
and he will judge every man according to his works.`' Rev. 20:13.

And behold, saith Christ, '`I come quickly, and my reward is with me,
to give every man as his works shall be.`' Rev. 22.

And Christ saith, '`the Son of man shall come in the glory of his Father with his angels,
and then he shall reward every man according to his works.`'

And the apostle tells the church of the Corinthians,
'`every man shall receive his reward according to his own labour.`'
1 Cor. 3.

And the apostle said concerning Alexander the copper-smith, which did him much evil,
'`the Lord reward him according to his works.`' 2 Tim. 4.

And Christ saith, '`let the tares and the wheat grow together, until the harvest,
which is the end of the world,
lest they pluck up the good seed with the bad;`' after he had sown the good seed,
and the wicked one came and sowed the tares; for Christ is the good seedsman,
and the devil is the wicked seedsman.

And he tells them the '`harvest is the end of the world;`' and
then he will send his angels to sever the wheat from the tares.

And Christ reproved the servant, '`whose Lord had forgiven him his debt,
who would not forgive his fellow servant.`'

And do not you often say in the Lord`'s prayer,
'`forgive us as we do forgive them that trespass against
us?`' And so you ask the Lord to forgive you your trespasses,
no more but as you do forgive others that have trespassed against you.

And then consider, all you that do not forgive, whether you can expect any forgiveness.

So Christ hath enlightened all, and his grace hath appeared unto all men,
and he hath promised to pour out his spirit upon all flesh,
and '`his gospel is preached to every creature,`'
and he '`hath tasted death for every man.`'

It is he that will reward every man according to his works.

And there is a day, '`when God will judge the secrets of all men by Jesus Christ,
according to the gospel which is preached to every creature under heaven.`' Rom. 2:16.

And '`he hath appointed a day in the which he will judge the world in righteousness,
by the man Christ Jesus, whom he hath ordained,
whereof he hath given assurance to all men,
in that he hath raised Christ from the dead.`' Acts. 17.

And Christ shall judge the quick and the dead at his appearing.

So all judgment is committed unto the Son; and Christ saith, '`judge not,
lest ye be judged;`' for with what judgment ye judge, ye shall be judged;
and with what measure you meet, it shall be met to you.

So '`let the beam be plucked out of your own eyes,
before ye go to pluck the mote out of your brother`'s
eye;`' for ye are all brethren in Adam.

And James tells you, '`you must not speak evil one of another;
for he that speaketh evil of his brother, and judges his brother, speaks evil of the law,
and judges the law:`' but if thou judgest the law, thou art not a doer of the law,
but a judge.

And James saith, '`behold the judge standeth before the door.`'

Mark, what judge is this?
and what door is this? James 4:11,5,9.

Here you may see, Christ is the judge of every man, according to his works;
and if ye hate his light, and turn his grace into wantonness, and quench his spirit,
and rebel against the Holy Ghost, as the Jews did;
though you may make a profession of the scripture,
and not walk in the life that gave them forth, yet God and Christ will judge you,
and reward you according to your works, (and every man,) whether they be good or evil.

So let all christians give over the work of persecution,
and cast forth that birth that is born of the flesh, which will persecute;
for he must not be heir with him that is born of the spirit.

And therefore, as the apostle saith, '`cast forth the bond-woman and her son,
for he must not inherit the kingdom, and the world that hath no end.`' Gal. 4:30.

I say, the kingdom of God, that stands in righteousness and joy in the Holy Ghost;
they that are led by the Holy Ghost, inherits this.

And this first birth of the flesh you must cast forth by the spirit of God.

For Christ tells you, '`you must be born again,
before ye can enter into the kingdom of God.`'

And of this birth I fear many that profess themselves christians,
are as ignorant of as Nicodemus.

But '`turn at my reproof,`' saith the Lord,
and behold I will pour out my spirit upon you, and I will make known my words unto you.`'

Now.if you will turn at the reproofs of God`'s spirit, ye will come to know his words,
and know this birth of the spirit. Prov. 1:22.

And did not Moses say, '`that God was the God of the spirits of all flesh.`' Numb.
xvi. And did not the apostle say, '`that in God we live, move, and have our being,
as some of you poets have also said.`'

And in Numb. 27.
again, did not Moses call the Lord, '`the God of the spirits of all flesh.`'

And so is not all your eyes to look up unto the Lord God, the creator of all,
and the life of all; that gives breath unto all, that in him they may live, and move,
and have their being.

And the Lord is not slack concerning his promise, but is long suffering towards us,
not willing that any should perish, but that all should come to repentance. 2 Pet. 2.

For Christ also hath once suffered for sin, the just for the unjust,
that he might bring us to God; mark, that Christ might bring us to God,
'`being put to death in the flesh, but quickened in the spirit;`' by which, to wit,
the spirit; Christ also went and preached unto the spirits in prison,
which sometimes were disobedient,
when once the long suffering of God waited in the days of Noah,
whilst the '`ark was preparing, wherein few, that is, eight souls were saved.`'
1 Pet. 3. and the rest were drowned.

And now consider, has not the long suffering of God waited upon Christendom,
and all others;
and do ye think that Christ now by his spirit does not preach to the disobedient,
and the spirits in prison; and consider, all that are disobedient to the spirit of God,
are not your spirits in prison?

And was not the old world overthrown by water,
and they perished for their rebellion and disobedience to God?
And do ye not think, that by the same word and power,
that the heavens and earth which are now, are kept in store,
reserved unto fire against the day of judgment, and perdition of ungodly men.

So be not ignorant of this one thing,
'`that one day is with the Lord as a thousand years,
and a thousand years as one day:`' and therefore
as the Lord destroyed the old ungodly world by water,
so will he destroy the ungodly world in the lake of fire.

And so here ye may see Christ by his spirit was a preacher to the spirits in prison,
in the days of Noah to the old world;
and now he is a preacher by his spirit unto the spirits that are in prison,
in you that disobey it.

For does not James tell you, '`that the judge stands at the door;`' What door is this?
Is it not the door of your hearts, minds, and souls?

And does not John say to the seven churches, seven times, '`he that hath an ear,
let him hear what the spirit saith to the churches?`'
And was not this the spirit of Christ,
whom John saw walking in the midst of the seven golden candlesticks,
which are the seven churches?

And does not John the divine say of the Son of God,
'`that he stands at the door and knocks?`' and saith
'`if any man will hear my voice and open the door,
I will come into him, and sup with him, and he with me.`' Rev. 3.

So what door is this that Christ knocks at?
Is it not the door of your hearts, minds, and souls?
and therefore, do not you stop your ears, and close your eyes, like the pharisees,
but hear Christ`'s voice, by turning at the reproofs of his spirit and his light;
and then he which hath enlightened you '`will come in, and sup with you,
and you with him.`'

And Christ tells Pilate, when he was examining him,
'`for this cause came I into the world, that I should bear witness unto the truth,
and every one that is of the truth heareth my voice; mark this,
every one of you christians, every one of you that is of the truth,
heareth Christ`'s voice; but you that are not of the truth, heareth not his voice,
and will say there is no hearing of his voice nowadays.

And Pilate, the governor, said unto Christ,
'`what is truth?`' And I fear that there is too many that are called christians,
that crucify Christ to themselves afresh, that may say, as Pilate did,
'`what is truth?`' so much are they strangers to it.
John 18.

And therefore, as the apostle saith to the Corinthians, '`examine yourselves,
whether ye be in the faith,`' to wit,
that faith '`which Jesus Christ is the author and finisher of,`' which is holy, divine,
and precious, and prove your own selves.
Know you not your own selves, how that Jesus Christ is in you,
except ye be reprobates?`' 2 Cor. 13.
So examine and prove yourselves.

Now if you do say, with what, and how shall we examine and prove ourselves?
The apostle tells you, '`God who commanded the light to shine out of darkness,
hath shined into our hearts,
to give the light of the knowledge of the glory of God in the face of Christ Jesus;
but we have this treasure in earthen vessels,`' that
the excellency of the '`power may be of God,
and not of us.`'

So this light that shines in your hearts,
will give you the knowledge if you will come to it;
and they that doth truth will come to it, that with the light he may see his works,
how they are wrought in God;
and it will give them the knowledge of the glory of God in the face of Christ Jesus,
where he hath received the light, which is the life in him, the word.
2 Cor. 4. and Job 1:4. and Job 3:21.

And the Lord God has promised and hath fulfilled, and is fulfilling his promise:
'`I will give them one heart, and I will put a new spirit within them,
and I will take away the stony heart out of their flesh,
and they shall walk in my statutes, and keep my ordinances, and do them;
and they shall be my people, and I will be their God.`' Ezek. 11.

And in Ezek. 18.
'`cast away from you your transgressions,
and make you a new heart and a new spirit,`' etc.

'`And I will put my spirit in you, and ye shall live,`' saith the Lord;
'`and I will sprinkle clean water upon you,
and ye shall be clean from all your filthiness,
and from all your idols I will cleanse you: a new heart also will I give you,
and a new spirit will I put within you,
and I will take away the stony heart out of your flesh,
and I will give you a heart of flesh.`' Ezek. 36:37.

And now, consider, ye christians, do ye witness this spirit?
And this new heart, which all the true christians doth.

And the Lord said, '`that his sheep hath been scattered,
and they have wandered through all mountains, and from mountain to hill;
and he will seek his sheep, and I will feed them in a good pasture,`' saith the Lord,
'`and cause them to lie down, and I will set one shepherd over them,
and he shall feed them, and he shall be their shepherd.`' Ezek. 34.

And is not this Christ, who is the only feeder of his sheep?

And does not Solomon acknowledge,
'`how God taught Israel the good way wherein they should walk.`'
2 Chron. 6.

And does not David say, '`the Lord is my shepherd, I shall not want,
he maketh me to lie down in green pastures,
he maketh me to lie down beside the still rivers; he restoreth my soul,
and leadeth me in the paths of righteousness for his name`'s sake?`'

Now, can you say so, that are called christians,
and acknowledge David`'s teacher as he did, and that the Lord is your shepherd,
and that you do not want?

And David said, '`O, God thou hast taught me from my youth,
and hitherto have declared thy wondrous works.`' Psalm 17.

I have not departed from thy judgments, for thou hast taught me;
'`how sweet are thy words unto my taste, yea,
sweeter than the honeycomb to my mouth.`' Ps. 119:102.

Now, ye christians, consider this, here David acknowledged God`'s teaching,
and how sweet his words were to him: but are God`'s words so sweet unto you?
And do you hear God and Christ`'s voice?

And in Prov. 4:11. '`I have taught thee in the way of wisdom,
I have led thee in the right path.`'

And the Lord said, '`I have taught Ephraim also to go;
and when Israel was a child I loved him, and called my Son out of Egypt,
taking them by their arms, but they knew not that I healed them.`' Hos. 11:1,3.

And so ye may see here how they acknowledged the Lord`'s teaching.

And the apostle said, '`I neither received the gospel of man, neither was I taught it,
but by the revelation of Jesus Christ.`' Gal. 1.

Here the apostle acknowledgeth, both how he was taught it, and how he received the gospel.

And the apostle tells the church, as touching brotherly love,
'`ye need not that I write unto you,`' for ye yourselves
are taught of God '`to love one another.`' 1 Thess. 4:9.

Mark, here the church of the Thessalonians were under God`'s teaching,
and so let all that call and count themselves christians,
see if they be under God and Christ`'s teaching, who is love,
and teaches them to '`love one another,`' for it is the
wicked one that teacheth them to hate one another;
and John tells you, '`he that loveth not his brother is not of God.`'

And the apostle bids them '`hold fast the word as they had been taught,
that they may be able with sound doctrine to exhort and convince the gainsayers,
not to persecute the gainsayers.`' Tit. 1:9.

And John tells the church in his general epistle,
'`the anointing which ye have received of him, abideth in you;
and ye need not that any man teach you,
but as the same anointing teacheth you all things, and is true, and is no lie;
and even as it hath taught you, ye shall abide in him:
and these things I have written unto you concerning them that seduce you.`' 1 John 2:27.

And now, let all that are called christians,
see if they are not seduced from this ANOINTING WITHIN,
which the true church received from the holy one,
and whether they are not seduced from this teacher
which John did direct the true church unto.

And you may see how the Lord taught Moses and Aaron,
and what words they should speak to Pharaoh. Exod. 4.

But Moses said, '`like unto me will God raise up a prophet,
him shall ye hear in all things:`' now consider, all ye christians,
whether do ye believe that God hath raised up this prophet Christ Jesus?
And if so, whether do ye hear him?
Who remains in the heavens till all things be restored.
And consider how he doth restore, and by what?
For such were restored that sat in the heavenly places in Christ Jesus.

And David saith, '`O, how I love thy law, it is my meditation all the day:
through thy commandments, thou hast made me wiser than my enemies;
I have more understanding than all my teachers, thy testimonies are my meditation:
I understand more than the ancients, because I kept thy precept.`' Ps. 119:99.

Now consider, who was David`'s teacher that he did thus profit?

'`Thus saith the Lord, thy redeemer, the holy one of Israel, I am the Lord thy God,
which teaches thee to profit,
which leadeth thee by the way thou shouldst go.`' Hab. 48:17.

So here you may see God is both the leader and teacher,
that teacheth his people to profit.

And therefore all ye christians consider, how is Christ your leader and teacher?
For we must tell you, the Lord God doth not change, nor his Son,
and he is come to teach his children himself, who teaches them to profit,
'`and the manifestation of the spirit of God is given
to every man to profit withal.`' 1 Cor. 12:7.

And the Lord said to David,
'`I will instruct thee and teach thee in the way thou shouldst go;
I will guide thee with my eye, and therefore be glad in the Lord,
and rejoice ye righteous,
and shout for joy all ye that are upright in heart.`' Psalm xxxii.

Now here you may see the Lord God was the instructor and the teacher in his own way,
and guides his people with his eye, which is spiritual.

And David said, '`Good and upright is the Lord,
and therefore will he teach sinners in the way, the meek will he guide in judgment,
and the meek will he teach his way; what man is he that feareth the Lord,
him shall he teach in the way that he shall choose;
his soul shall dwell at ease and his seed shall inherit the earth;
the secrets of the Lord are with them that fear him,
and he will spew them his covenant.`'

And David desired God`'s teaching, and said, '`He was the God of his salvation,
and on him he would wait all the day.`'

And therefore, oh, that men, called christians, would come to this meekness,
and the fear of God, that they might come under this teaching,
and under the guidance of his spirit, and have his secrets revealed to them.

And ye may see that God is not the teacher only of his people,
but he will teach sinners if they will hearken to him. Psalm 25.

And David said, '`though my father and mother should forsake me,
yet the Lord will take me up; and teach me thy way, O Lord,
and lead me in a plain path.`' Psalm 27.

And here again you may see how David doth exalt the Lord`'s teaching.

And again, David desired the Lord to teach him to do his will,
'`for thou art my God, and thy spirit is good, lead me into the land of uprightness.`'
Psalm. 43.

So here you may see David delighted in God`'s teaching, and set it forth upon record,
that all God`'s people might do the same.

And again: '`thus saith God the Lord, he that created the heavens,
and stretched them out, and spread forth the earth,
and that which cometh out of it he that giveth breath to the people in it,
and spirit to them that walk therein: I, the Lord, have called thee in righteousness,
and will hold thy hand and keep thee, and will give thee for a covenant of the people,
and for a light to the Gentiles, to open the blind eyes,
and to bring the prisoners out from the prison, and them that sat in darkness,
out of the prison-house.`' Isa. 42.

Now hear, O Christendom, this is Christ Jesus,
whom God hath given for a covenant of the people, and a light to the Gentiles,
who has opened our blind eyes, and has brought us prisoners from the prison,
and brought us that sat in darkness, out of the prison-house;
glory and praise can we sing unto the Lord through Jesus Christ,
and say that there is no salvation by any other name under the whole heaven,
but by the name of Jesus.

And the Lord saith, '`I will pour water upon him that is thirsty,
and floods upon the dry ground; and I will pour my spirit upon thy seed,
and my blessing upon thy offspring, and they shall spring up as amongst the grass,
as willows by the water-courses.`' Isa. 4:4.

And these heavenly eternal riches do we witness, and all do,
that are under God and Christ`'s teaching.

But we fear that this prophecy is come to pass upon many in Christendom, as in Isa. 29.
'`the Lord hath poured out upon you the spirit of deep slumber, and has closed your eyes;
the prophets, and the rulers, and the seers, has he covered,
and the vision of all is become unto you as the words of a book that is sealed.`'

And what was the cause they could not read the book?
'`Because they drew nigh unto the Lord with their lips,
but their hearts were far off him; and they honoured him with their lips,
but have removed their hearts far from me,`' saith the Lord,
'`and their fear towards me is taught by the precepts of men.`'

And these were such as rebelled against God`'s spirit, that was poured out upon them.

And therefore, would the Lord proceed to do a marvellous work amongst such people;
for the wisdom of their wise shall perish,
and the understanding of the prudent shall be hid.

And therefore, you may see what David says: and the Lord says,
`'the sacrifices of God are a broken spirit, a broken and a contrite heart, O, God,
thou wilt not despise.`'

Now let us see if all that profess themselves christians,
have this sacrifice which God will not despise. Psalm 51.

And the Lord saith, '`say unto them that are of a fearful heart, be strong, fear not;
behold your God will come with vengeance, he will come with a recompence,
he will come and save you;
then the eyes of the blind shall be opened and the ears of the deaf shall be unstopped;
then shall the lame leap as a hart, and the tongue of the dumb shall sing.`' Isa. 35.

So all christians that can witness the Lord is come to '`dwell in them,
and walk in them,`' and their bodies are the temples of God; their blind eyes are opened,
and their deaf ears are unstopped, and the lame does leap,
and the tongue of the dumb is loosed, and sings praises to God:
for he makes waters in the wilderness, and streams in the desert,
and springs in the parched ground; and such know God`'s high way,
and it is called the way of holiness, the unclean shall not pass over it.`'

Here is the holy way to God, Christ Jesus, who bruises the serpent`'s head,
that has separated betwixt man and God, and made him and his way unholy;
and so through Christ, man comes again to God.

And hear what the Lord saith, in Isaiah, to such as will not hear when the Lord calls,
and choose their own ways, and forsake the Lord`'s: '`I also will choose their delusion,
and will bring their fear upon them, because when I called, none did answer,
and when I spoke, none did hear; but they did evil before mine eyes,
and chose that in which I delighted not.`'

And therefore let all that are called christians, consider this,
that say there is no hearing God, nor Christ`'s voice now,
for he has poured his spirit upon you, that ye might understand it, and hear it.

And Christ tells you after he was risen, that he stands at the door and knocks,
and if any man will hear his voice, he will come in and sup with them, and they with him.

Now God and Christ calls, but ye will not answer;
and if he speak to you by his power and spirit, ye will not hear, nor follow Christ,
which is the way to God, but choose your own ways; therefore,
what can ye expect but delusion. Isa. 46.

And now, those that would not hear when God spoke to them, nor answer when he called,
'`they cast them out that trembled at God`'s word, from amongst them,
and hated them for the Lord`'s name sake;`' and then said unto them,
let the Lord be glorified: but saith the Lord, he shall appear to your joy, to wit,
those that trembled at his word, but they shall be ashamed.

But whom shall the Lord and his Christ teach knowledge?
And whom shall he make to understand doctrine?
Them that are weaned from the milk, and drawn from the breast.`' Isa. 28.

Now let all christians consider what milk and what breasts this is,
seeing the babes that are born again of the immortal seed,
'`feeds upon the sincere milk of the word.`'

And the Lord saith unto Jeremiah, '`behold the days come,
I will make a new covenant with the house of Israel and Judah, not according to the old,
that I made with their fathers in the day I brought them out of Egypt,
which covenant they broke:
but this is the new covenant that I will make with them,`' saith the Lord.
'`I will put my laws in their inward parts, and write them in their hearts,
and I will be their God, and they shall be my people;
and they shall teach no more every man his neighbour, and every man his brother; saying,
know the Lord, for they shall all know me,
from the least of them unto the greatest.`' Jer. 31.

So now all the christians that do profess the days of this new covenant, Christ Jesus:
hath God written his laws in your hearts, and put them in your inward parts,
and your minds?
Do not ye need to teach every man his neighbour, and his brother?
Saying, '`know the Lord:`' do ye all know the Lord,
from the least to the greatest of you, by Christ Jesus the new covenant?
So that the knowledge of the Lord doth cover the earth, as the waters does the sea,
that it shall be the uppermost in you: are ye in this high, and glorious,
and everlasting covenant?
And can say that God is your God, and ye are his people?
and you do see the end of the old covenant, and its days, which was to the outward Jews;
and they are the true Jews which are the true christians in spirit,
'`that serves God in the newness of the spirit,
and not in the oldness of the letter.`' Rom. 7:6. and 2. 28, 29.

And in Mic. 4. where the Lord saith, '`many nations shall come and say, come,
let us go up to the mountain of the Lord, the house of the God of Jacob,
and he shall teach us of his ways, and we will walk in his paths,
and they shall sit every man under his vine, and under his fig-tree,
and none shall make them afraid, the mouth of the Lord of hosts hath spoken it.`'

And now you may see, here are nations that will come under God`'s teaching,
who teacheth them his way and path to walk in; and they that are under God`'s teaching,
do sit under Christ the vine, and are grafted into him,
and they that abide in him will bring forth fruit.

And let all of Christendom take heed lest the saying of Hosea the prophet,
do not come upon them.

'`Upon whom the day of visitation will come, and the day of recompence will come,
that say the prophet is a fool,`' and the spiritual man mad;
and say '`there are no prophets nor spiritual men
now in their days;`' as you may see in Hosea ix.

And these are such as quench the spirit;
for though the Lord poured out his spirit upon the house of Israel, and it is said,
'`he gave them his good spirit to instruct them,
yet they rebelled against it.`' Neh. 9:20.

And Stephen said to the high-priest and council of the Jews, in his examination,
'`ye stiff-necked and uncircumcised in heart and ears,
ye do always resist the Holy Ghost, as your forefathers did, so do ye.`' Acts 9:51.

And therefore, let all christians take heed of resisting the Holy Ghost,
which reproves them of their sin, righteousness, and judgment; which Holy Ghost,
the Comforter, the Father doth send in Christ`'s name,
which did teach the apostles and the saints all things,
and brought to their remembrance whatsoever Christ had declared unto them,
which Holy Ghost did come according to Christ`'s promise, as in Acts ii.

And Christ said to his disciples,
when they should be called before magistrates for his name`'s sake, he bade them,
'`take no thought what to answer,
for the Holy Ghost shall teach you in the same hour what ye ought to say.`'

So here the Holy Ghost was their teacher. Luke 20.

But you may see often the prophets and Christ speaks to the Jews,
'`how they stopped their ears, and closed their eyes, and would not see with their eyes,
nor hear with their ears, lest they should be converted, and he should heal them;
and such rebelled against the good spirit, that God gave them to instruct them,
and resisted the Holy Ghost:`' and it is well if too many of you, called christians,
do not so now: but some there are that say, they have not the same Holy Ghost and power,
as the apostles had; then they cannot pray in the same Holy Ghost,
nor have the same comfort and fellowship in the Holy Ghost, as they had,
nor be led into all truth.

And it is said in Isa. 26:9. '`with my soul have I desired thee in the night, to wit,
the Lord; yea, with my spirit within me will I seek thee early:
for when thy judgments are in the earth,
the inhabitants of the world will learn righteousness.`'

So my desire is,
that all christians were of this spirit and mind and if all flesh
will not obey this good spirit which strives with them all,
when his judgments are come into the earth, that will make them to learn righteousness.

For, '`lo, he that formed the mountains, and created the winds,
and declareth unto man what is his thoughts, that maketh the morning darkness,
and treadeth upon the high places of the earth,
the Lord of hosts is his name.`' Amos 4:30.

Surely this might convince all men, that God is a God at hand,
that sheweth unto them their thoughts by his good spirit.

And God strove with the old world, his spirit, and they grieved him,
but at last he overthrew them: and God strove with the Jews by his spirit,
which he had given them to instruct them, but they rebelled against it,
so as at last he overthrew them also.

And now God hath sent '`his Son to die for all,`'
and his gospel is preached to all nations,
and every creature under heaven; and Christ hath enlightened all with the light,
which is the life in the word, which was in the beginning,
and God hath poured out his spirit upon all flesh:
'`and the grace of God which brings salvation, hath appeared unto all men,
to teach them,`' and bring their salvation.

And now, if christians and others do hate the divine light of Christ,
and quench his spirit, and turn his grace into wantonness,
and walk despitefully against it, and resist the Holy Ghost,
which reproves them of their sin, righteousness, and judgment,
which is the leader of Christ`'s disciples into all truth, and teacher, and comforter.

I say, let all Christendom take heed lest God Almighty overthrow them,
as he did Sodom and the old world, and the Jews, and mingle them amongst the heathens,
as he did them; for such as have the form of godliness, and deny the power thereof,
are to be turned away from, by all God`'s people.

And also it is said in Mich.
vi. '`he, to wit, the Lord, hath shewed thee, O man, what is good,
and what the Lord requireth of thee, to do justly, and love mercy,
and to walk humbly with thy God.`'

Now let all Christendom consider this, high and low,
what God Almighty hath shewed unto you, and what he requires of you.
First, he hath shewed you what is good, that ye might shun the evil:
here God is your teacher and shower of what is good.
Secondly, what God doth require of you, after he hath shown you the good, to wit,
to do justly, to love mercy and walk humbly with God.

Here God shewed man his duty, both to God and man, and how to walk before God and man;
here God is your teacher by his spirit, if ye will hear his voice,
and hearken unto him who shows you this.

Now the Jews made a great profession of the scriptures in the Old Testament,
and said God was their Father, but Christ told them, if God was their Father,
they would love him, for he proceeded from the Father.

And further, Christ said unto them, '`he that is of God heareth God`'s words;
ye therefore, are not of God, because ye hear them not.`'

And therefore, says Christ to the Jews, '`ye are of your father, the devil,
and the lust of your father ye will do; +++[+++mark, ye will do,]
for the devil was a murderer from the beginning, and abode not in the truth,
because there was no truth in him;`' when he speaks a lie, he speaks of his own;
for he is a liar and the father of it.

Now these Jews that were erred from the spirit, and rebelled against it,
which God had poured upon them, could profess the scriptures,
and that God was their Father; but Christ said, '`ye are of your Father the devil,
who was a murderer, and his lusts ye will do;`' and they did it,
for they murdered Christ.
John 8:42, to 48.

And therefore, let all Christendom take heed,
lest they err from this spirit which God hath poured upon all flesh;
then they go from the spirit of truth, and do the devil`'s lusts, like the Jews,
that crucified Christ without the gates,
and they come to crucify to themselves Christ afresh,
and then persecute and murder his saints, where he is manifest.

And the apostle saith, in Acts 3.
'`that Moses truly said unto the fathers,
a prophet shall the Lord your God raise up unto you of your brethren like unto me,
him shall ye hear in all things; whatsoever he shall say unto you;
and it shall come to pass that every soul that will not
hear that prophet shall be destroyed from amongst the people.`'

And further, the apostle saith, '`that all the prophets from Samuel,
and those that followed after, as many as have spoken of him,
likewise foretold of these days, to wit, the days of Christ.`' Acts 3.

And so '`Moses as a servant, was faithful in his house;`' but Christ, as a Son,
is over his house, whose house we are,
says the apostle to the church in the primitive times.

Wherefore, as the Holy Ghost saith, '`today, if ye will hear his voice,
harden not your hearts.`' Heb. 3.

But you may see whose voice we must hear, the voice of Christ, the voice of this prophet,
whom God hath raised up, and not man; Christ the Son of God, who is over his household,
and they that do not hear his voice, hardens their hearts, and therefore,
the Holy Ghost saith unto you,
'`whilst it is called today hear his voice,`' and therefore,
ye must not put it off till tomorrow, for ye may be dead before tomorrow.

'`And they that despised Moses`'s law, died without mercy, under two or three witnesses;
how much sorer punishment suppose ye, shall they be thought worthy of,
who have trodden under foot the Son of God and counted
the blood of the covenant wherewith he was sanctified,
an unholy thing, and have dealt despitefully unto the spirit of grace,`'
as in Heb. 10.

Oh! therefore, all ye called christians, take heed,
do not despite unto the spirit of grace, but let it be your teacher to season your words,
and establish your hearts, and it will bring your salvation.

For the true church, in the primitive times,
entered into the holiest by the blood of Jesus, by the new and living way;
and Christ was their high priest over the household of God,
which all true christians were then, and are now, that were the true church.

And the apostle told them, '`that they were come to Mount Zion,
and unto the city of the living God, and to the heavenly Jerusalem,
and to an innumerable company of angels, and to the general assembly,
the church of the first born, written in heaven, and to God the judge of all,
and the spirits of just men made perfect, and to Jesus the Mediator of the new covenant,
and to the blood of sprinkling,`' etc.

'`So if they did not escape, that refused him that spoke on earth,
much less shall we escape says he, if we refuse him, to wit,
Christ that speaks from heaven.`'

So you may see here what the true church was to come to in the primitive times,
and whom they were to hear, the prophet whom God had raised up;
and this was after Christ was risen.

And now let Christendom examine themselves, and see '`if they be come to Mount Zion,
and to the heavenly Jerusalem,
and to the innumerable company of angels,`' and to the general
assembly and church of the first born written in heaven,
and to the spirits of just men made perfect, and to Jesus the Mediator,
and to the blood of sprinkling;`' and that they do not turn
away from hearing Christ that speaks from heaven. Heb. 12.
'`For he stands at the door and knocks.`' Rev. 3.

And the apostle saith, '`such an high priest became us (to wit, Christ,) who is holy,
harmless, undefiled, separate from sinners, and is made higher than the heavens.`'
Heb. 7.

Now this is the priest and prophet which is over God`'s house, and becomes it;
and all the true christians that hear Christ`'s voice, are his house;
so the true christian`'s high priest is holy, harmless; he will do none hurt, but good;
he is undefiled, for he leads out of defilement; he is separate from sinners,
for no guile nor sin is found in his mouth; he is made higher than the heavens,
and higher than Aaron`'s priesthood, and higher than all the priesthoods made at schools;
and '`he remains in the heavens,
until all things be restored,`' and he is restoring by his light, spirit and power,
up unto himself:
and they that are restored '`sits in the heavenly places in Christ Jesus.`' Eph. 2:6.

So God was the teacher of Adam and Eve in paradise,
and as long as they kept under his teaching they were happy.

The serpent was the false and second teacher, and Adam and Eve hearkening unto him,
and forsaking God`'s teaching, they lost paradise, and became unhappy.

And God said, the seed of the woman shall bruise the serpent`'s head,
who is the head of all false teachers.

And so as the apostle said, '`God at sundry times,
and in divers manners spoke unto our fathers by the prophets;
but in these last days he hath spoken unto us by his Son.`'

So God spoke to the prophets before the flood, and after the flood,
and in the time of the law;
but now in these last days (the christian days,)
'`he hath spoken unto us by his Son:`' us,
the church, the true christians; so he is the speaker now to all the true christians.

And so Christ, '`by whom all things were made, he was the first,
and he is the last;`' and he is the Quakers`' first speaker, and the last;
for God hath spoken unto us by his Son, that God, who was the speaker unto,
and teacher of Adam and Eve in paradise before they fell:
and the serpent that was the false teacher and speaker, Christ bruises the head of him,
and through death destroyed him the power of death, to wit, the devil.

And I say again, God hath spoken unto us by his Son,
who renews us up in the image and likeness of God, in righteousness, and holiness,
as Adam and Eve were in, before they fell.

So the same God that was the speaker unto Adam and Eve in paradise,
has spoken unto us by his Son, who was the speaker to the church in the primitive times;
glory to God forever.

And all must hear him, and believe in him, and follow him, in the life.

And therefore, hearken to his voice,
and take heed ye be not found in the spirit of deep slumber, as the Jews were in;
and have eyes, and see not, and ears, and hear not;
and that your outward things and inventions be not a snare and a trap to you,
like unto the Jews`' table, whose table was made a snare, and a trap,
and a stumbling block, and a recompence unto them: though they talked of God and Christ,
yet they did not receive him when he came.
And you, called christians, talk much of Christ, and that he is come,
but if ye have him not, ye have not life; and if he be not in you, ye are reprobates.

And therefore; '`quench not the spirit of God, nor hate his light,
but believe in it,`' as Christ commands, and mind what the righteousness faith speaks;
'`the word is nigh thee, even in thy heart, and in thy mouth, to obey it, and do it;
and that is the word of faith which we preach,`' saith the apostle.

Now if all Christendom had continued in this word of faith in their hearts and mouths,
the apostle preached and obeyed it, and done it, they had been all reconciled to God,
and to the scriptures, and one to another.

'`And the holy men of God gave forth scriptures,
as they were moved by the Holy Ghost;`' and Christ saith,
'`it is the Holy Ghost that leads into all truth.`'

So none can be led into all truth but by the same Holy Ghost that spake forth scriptures,
and such come to sit under God and Christ`'s teaching.

And Christ has ended the worldly sanctuary, and the tabernacle made with hands,
as you may see in the Hebrews.

And Stephen told the Jews that much adored the outward temple: Solomon says,
he built an house, '`howbeit,
the Most High dwells not in temples made with hands,`' as saith the prophet. Isa. 46.
'`Thus saith the Lord, heaven is my throne, and earth is my footstool;
where is the house that ye built unto me?
Where is the place of my rest?
For all those things hath my hand made, and all those things have been,`' saith the Lord;
'`but to this man will I look, even to him that is poor, and of a contrite spirit,
and trembles at my word.`'

And Solomon, that built the temple, said, '`behold,
the heaven of heavens cannot contain thee,
much less this house that I have built.`' 2 Chron. 6. and Acts 7.

And the apostle Paul saith, Acts 17.
'`God that made the world, and all things therein,
seeing that he is Lord of heaven and earth, dwelleth not in temples made with hands,
neither is he worshipped with men`'s hands, as though he needed any thing:
seeing he giveth to all life and breath, and all things; and hath made of one blood,
all nations of men to dwell upon the face of the earth,`' etc.

And the apostle saith, in 1 Cor. 6.
'`what, know ye not that your bodies are the temples of the Holy Ghost,
which is in you, which ye have of God, and ye are not your own.`'

And in 2 Cor. 6. '`for ye are the temple of the living God,`'
as God hath said, I will dwell in them,
and walk in them, and I will be their God, and they shall be my people;
for ye are bought with a price, to wit, the blood of Christ,
therefore glorify God in your bodies, and with your souls.`'

And now this is every true christian`'s duty,
that are sensible of the price that Christ has paid for them,
and are come under God and Christ`'s spiritual and heavenly teaching;
and know that they are not their own, but Christ`'s that has bought them,
'`to glorify God in their bodies and spirits,
which are God`'s,`' who gave them for that end to glorify him withal.

'`And no man can say that Jesus is the Lord, who was conceived by the Holy Ghost,
(but by the Holy Ghost.`') 1 Cor. 12.

'`And let every man that nameth the name of Christ,
depart from iniquity.`' 2 Tim. 2:19.

So let all that are called christians, first see that they are in the Holy Ghost,
and that they do not resist it, and that they call Jesus Lord; that is,
call him Lord with, and in the spirit of truth, that leads them into all truth.

Secondly, Let every one mark, the command is general;
'`let every one that names the name of Christ,
depart from iniquity:`' and when they have departed from iniquity,
then let them name the name of Christ,
and then they will not take God and Christ`'s name in vain, but know him their teacher,
'`that makes an end of sin, and doth finish transgression,
and makes reconciliation for iniquity, and brings in everlasting righteousness,
who is the way to the Father, and is the prophet that is to be heard in all things.`'

For Malachi saith, '`behold, the day cometh that shall burn as an oven,
and all the proud, and they that do wickedly, shall be as stubble;
and the day that cometh shall burn them up,`' saith the Lord of hosts,
'`that it shall leave them neither root nor branch.`'

'`But unto you that fear my name, shall the Son of righteousness arise,
with healing under his wings;
and ye shall go forth and grow up as calves of the stall,`' etc.

And therefore, let all Christendom consider this day that will burn as an oven,
and all the proud and the wicked shall be as stubble burnt up,
and not be left neither root nor branch.

And therefore, let humility throw down pride, and virtue wickedness,
and come into the fear of God, and dread the name of the Lord,
that the Son of righteousness may shine upon you, and heal you,
that you may grow up within God`'s power and spirit, as the calves do in the stalls,
and so be fed of Christ your shepherd.

For as the prophet saith, '`the ox knoweth his owner, and the ass his master`'s crib,
but my people does not know me.`' So in this, your ox and your ass condemns you,
and you are more ignorant in your generations than the ox and ass;
for they know their feeders, but you know not God and Christ your feeder,
who took care for man, and made all things ready for man, before be created them;
for you know, '`the sixth day God made man,`' as in Gen. 1.

And so the Lord that made the heavens and the earth, and all things therein,
he took care for man both in temporal and spiritual things,
who was Adam and Eve`'s teacher in paradise; and now God has spoken unto us by his Son,
who bruises the head of the serpent, that led Adam and Eve from God,
and renews man up in the image of God, as man was in before he fell;
and not up into that only,
but up into '`the measure and stature of him`' that never fell,
in whom the saints '`sits down in the heavenly places, in Christ Jesus,
who is their rock and foundation, that standeth sure;`' the amen,
and the head of his church, whom God speaks by; and all are to hear him, and follow him,
if they will have life and salvation, who has given his flesh for the life of the world.

'`For whoso eateth my flesh, and drinketh my blood, (saith Christ,) hath life eternal,
and dwelleth in me, and I in him; as the living Father hath sent me,
and I live by the Father; so he that eateth me, even he shall live by me;
for I am the living bread, which came down from heaven.`' John 6.

So all must eat, and feed on this bread, that comes down from heaven, if they will live.

So it is not a professing what the prophets, Christ, and the apostles said, and did,
and a persecuting one another about their words; but eating this heavenly bread,
if ye have life; and this is all the true christians`' food,
which they must feed upon if they have life.

So here, all may see, it is Christ that gives you food, and life eternal;
and has prepared life eternal for you: and he is come, as in the volume of God`'s book;
'`for burnt offerings, and sacrifices, thou wouldst not;
but a body hath God prepared him, to do his will.`' Heb. 10.
And, that he might take away the first priesthood, covenant, altar, and temple,
sanctuary, and testament, and establish the second; and ends all the prophets, types,
and figures, and shadows of him: and so,
through the offering up of the body of Jesus once for all the offerings,
he perfects forever, all them that are sanctified.

So here is the prophet to open, the bishop to oversee, and shepherd to feed,
and king to rule in their hearts by faith:
and he takes away the old way that was amongst the Jews,
and establishes the new and living way; by whom God has spoken unto us, his true church,
who was the first speaker, and is the everlasting speaker.

So the Lord is the teacher of his people by his Son; glory and honour, thanks and praise,
be unto him; for he is worthy of all, who is over all, from everlasting, to everlasting.

So here you may see God is the teacher, who hath poured out of his spirit upon all flesh;
but if they harden their hearts, and close their eyes, that they will not see,
and stop their ears that they will not hear, and quench his spirit,
though Christ stands at the door of their hearts and knocks;
but if they will not open to him, nor hear his voice,
they refuse and neglect their salvation, and their destruction is of themselves.

For Christ hath enlightened all, that they might see, and poured out his spirit upon all,
that they might understand and obey: and the apostle says, '`he has tasted death for all,
and is a propitiation for the sins of the whole world; and the gospel,
which is the power of God,
is preached to every creature under heaven;`' so that all are left without excuse,
and God is just and righteous in his judging of the world,
for all hath had a visitation by God`'s light, grace, spirit, and gospel.

And the prophet saith, '`like unto me will God raise up a prophet,
him shall you hear in all things;`' so here you are all invited to hear the Son,
and you are invited to come '`freely, without money,
and without price:`' and when the Son of God was come,
and God had sent him into the world, he said '`whosoever believeth in me,
he shall not perish, but have everlasting life:`' and God said, '`this is my beloved Son,
in whom I am well pleased, hear ye him.`'

So here God invites all to come, and hear his Son; and Christ saith,
'`learn of me;`' and tells you, '`he is the way, the truth, and the life;
and no man comes to the Father, but by him:`' and he invites you also to come, and saith,
'`all that be weary and heavy laden,
he calls to them to come unto him;`' for his burden is light, and his yoke is easy,
that they might find rest to their souls.

And the apostle exhorts you to come unto Christ,
and bids you '`look unto him who is the author and
finisher of your faith:`' and Christ tells you,
'`that all power in heaven and earth is given unto
him;`' and he would have all the world,
and every creature to have a visitation of his gospel;
and therefore did he send his disciples unto all nations to preach it:
he who enlightens all with his heavenly light, to see it, and receive it;
and God who has poured his spirit upon all flesh, by which they might understand it:
so here are all left without excuse;
and what could God and Christ have done more for the world than they have done?

But if you will have none of God and Christ`'s teaching, but follow your own ways,
and refuse him the way, the truth, and the life:
how can you expect but to be judged in righteousness?

And Christ saith, '`he that will be my disciple,
must take up his cross daily and follow me;`' and this was
before he was crucified upon the outward cross;
and '`the cross of Christ is the power of God.`' 1 Cor. 1:18. Though
it be '`foolishness to them that perish,`' and the preaching of it;
'`but to us that are saved, it is the power of God.`'

And the apostle tells you, '`the gospel is the power of God,`' as you may see in Rom.
'`unto salvation, unto every one that believes.`'

So here the prophets and the apostles invites you to come to God and Christ;
and also God and Christ invites you, and the '`spirit saith, come: and the bride saith,
come; and let him that heareth Christ, say come; (that is,
invite others,) and let him that thirsteth, come; and whosoever will,
let him take the water of life freely.`'

So what could God and Christ himself, and his prophets and apostles, and his church,
that are his hearers and learners say more unto you.

So if you will not hear God and Christ`'s speaking unto you by his Son,
who gives you freely of the water of life, and spiritual food from heaven:
and you have all these invitations to hear,
and be taught of him who is your free teacher and feeder;
how can ye expect any thing but the judgments of God, if ye reject him?

And therefore, this is an invitation to you all, and a warning unto you all,
and a testimony unto you all, high and low, that are called christians,
who now have time to prize it, lest you pass away your time, and it will be too late;
and when time is past, you may say you had time.

And therefore, cease from man, whose breath is in his nostrils;
for wherein is he to be accounted of?
'`But look unto me all ye ends of the earth, and be saved,`' saith the Lord.

For John says, '`the nations of them that are saved,
shall walk in the light of God and the Lamb,`' and the kings
of the earth shall bring their glory and honour to it,
to wit, '`the heavenly Jerusalem, and the gates of it shall not be shut at all by day,
for there is no night there, for the Lord God and the Lamb is the light thereof.`'

And so, as I have said often before, he is the teacher by his Son,
and therefore hear ye him, and do not be like Adam and Eve, who hearkened to the serpent,
and forsook God`'s teaching; but what have they gotten by it, but woe and misery,
and so lost his image, and the paradise of God.

And therefore, now Christ being come to bruise the serpent`'s head,
and to reconcile and redeem man and woman again to God, out of that misery; I say,
to bruise the head of the serpent, who is the head of enmity, the Belial,
who leads men without God`'s yoke, and the dragon, the devourer of mankind:
so Christ has bruised the head of this serpent and in him is man`'s peace.

So I say, hear God, who speaks now by his Son, who reconciles to God,
all things in heaven, and things in earth: so here God,
who is now the speaker again by his Son, that was the first speaker to Adam,
in his image, in paradise, who is the creator of all, and over all,
from everlasting to everlasting; and if ye will not hear him,
consider what became of the house of Israel, that God poured out his spirit upon,
they rebelled against it; and now God has poured out his spirit upon all flesh;
and if ye will not turn to the spirit, and hear God and his Son,
but hearken to the serpent, and follow him,
how can you expect but to be cast into the lake of fire,
(with the serpent,) that burns forever.

And therefore, '`whilst it is called today, hear his voice,
and harden not your hearts,`' and not only hear, but obey;
for it is the obedient to Christ that shall eat the fat of the heavenly land,
and inherit substance.`'

And so the Lord God, who is the Creator of all, and gives life and breath to all,
that takes care for all, and is over all his works,
who was and is the speaker by his Son, to the christians, the first and the last,
direct you all, for all are to incline their ear and hear him, that their souls may live.

[.signed-section-context-close]
The 5th day of the 10th month, 1676.
