[#ch17.style-blurb, short="The Spirit of Man the Candle of the Lord"]
== The Spirit of Man the Candle of the Lord: the Candle of the Wicked often put out.

[.heading-continuation-blurb]
How the Lord enlightens the Spirit of Man, which is the Candle of the Lord;
and who are the Candlesticks, and how Christ walks in the midst of his Candlesticks;
and how the Candle of the Wicked is often put out.--By G. F.

Solomon saith, Prov. 20:27. '`the spirit of man is the candle of the Lord,
searching all the inward parts of the belly.`'

And David saith, Psalm 18, 28. '`thou wilt light my candle;
the Lord my God will enlighten my darkness.`'

So it was, and is, the Lord God that lighteth man`'s spirit, which is his candle.

And in Ezek. 13:3. saith Ezekiel, '`thus saith the Lord,
woe unto the foolish prophets, that follow their own spirit and have seen nothing.`'

And these were them that seduced the people, '`for handfuls of barley,
and pieces of bread;`' and daubed with untempered mortar,
that stood not in the counsel of God, to hear his voice, and receive his word.
So their spirits were not enlightened, as David`'s and Ezekiel`'s were;
for their candle was put out, and so they followed their own spirits, and saw nothing;
for they forsook the Lord, that should have enlightened their spirits, their candles.

And so all people that follow not the Lord, and hear not his voice,
nor stand in his counsel, that should enlighten them, they follow their own spirits,
and see nothing; for the apostle saith, '`the things of God knoweth no man,
but the spirit of God; and the natural man receives not the things of the spirit;
for they are foolishness to him, neither can he know them,
because they are spiritually discerned.`' So man`'s
spirit which is the candle of the Lord,
it must be enlightened by the spirit and light of the Lord,
that he may discern his things, and then his spirit reveals the things of God unto him;
for the apostle said, '`God had revealed unto them the things of God, by his spirit;
for the spirit searcheth all things, yea,
the deep things of God.`' So here the apostles`' spirits were enlightened;
for Christ hath enlightened their candle.
1 Cor. 2.

And Job said, '`Oh, that I were as in months passed,
as in the days when God preserved me, when his candle shined upon my head,
and when by his light I walked through darkness: as I was in the days of my youth,
when the secrets of God were upon my tabernacle,`' etc.

Here Job when he was in misery,
and the Lord had suffered the evil to come upon him to try him,
how he remembers the light, by which he walked through darkness,
and by which he saw the secrets of God formerly, which were upon his tabernacle.

And this was seen by God`'s light and candle, which he lighted his spirit with;
without which light no man sees God`'s secrets, nor walks through darkness,
as in Job 29:2.

And Solomon saith, '`fret not thyself because of evil men,
neither be thou envious at the wicked; for the candle of the wicked shall be put out:
my son, fear thou the Lord and the king,
and meddle not with them that are given to change.`' Prov. 24:19-20.

These had their candles lighted that were not to fret, because of evil men,
nor to be envious at the wicked; for when people go out of the fear of God,
and meddle with them that are given to change, then their candle goes out;
for they go from the Lord that lights their candle;
and they go from the sparks of God`'s fire, that should light their candle.

So it is by joining to the wicked, and going from the spirit of God,
and so out of the fear of God, that their candle goes out.

And Solomon, speaking of the virtuous woman, and of her diligence, Prov. 31. saith,
'`her candle goeth not out by night:`' and further
saith '`strength and honour is her clothing,
who opens her mouth in wisdom,
and in her tongue is the law of kindness.`' Now what wisdom is this, and law of kindness,
which brought her not to eat the bread of idleness?
And what strength and honour was this, that was her clothing,
whose candle went not out by night?

For they that love not this virtue, and the wisdom, and live not in this law of kindness,
are not clothed in this strength and honour,: for such are the wicked,
and such their candle goes out when the night comes.

And therefore, they that keep their eyes to the Lord, who enlightens their candle,
and then they keeping their eyes to him, their candle will not go out by night,
but shine over all darkness; for he and his light was before darkness was,
that lights man`'s spirit, as it did David`'s.

But they that go from the wisdom of God, and from virtue, and so from his strength,
they go from God and his light, who enlightens their spirits his candle;
and so comes the wicked`'s candle to be put out, and they go into darkness,
and know not whither they go.

And the Lord sent his prophets, rising up early, to tell Judah and the king,
'`how that he would bring Nebuchadnezzar upon them,`'
because of their transgression of God`'s law,
and forsaking the Lord; and would bring their land into desolation;
and that he would take away the light of their candle,`' etc. Jer. 25:10.

And all this was, because of their grieving of the Lord, and turning from the Lord,
that the light of their candle should be taken away;
the light which lightens their spirits, which is the candle;
and then their house becomes full of darkness, and so become natural men,
which know not the things of God; and then they may follow their own spirits,
like the foolish prophets, and see nothing of the things of God.

And David, when he transgressed and grieved the Lord, he desired the Lord,
that '`he would not take from him his holy spirit,
nor cast him from his presence;`' for the spirit of God,
and light of God was that which lighted David`'s spirit,
by which he saw his transgressions, and by which he turned to the Lord,
and the Lord did forgive him, and removed his sins as far from him,
'`as the east is from the west,`' as you may see in Ps. 51:11.

So it is the Lord that doth enlighten man`'s spirit, his candle with his heavenly fire,
his light, yea, all such as obey him.

And so it is the Lord that opens the eye to see, and the ear to hear;
and it is the Lord that opens the lips and the mouth to shew forth his praise.

And in Ezek. 39:29. it is said,
'`I have poured out my spirit upon the house of Israel,
saith the Lord God.`' And here all may see,
that by the spirit of God their spirit the candle was enlightened,
to know the law and things of God by the spirit of God.

But when Israel rebelled against God`'s good spirit, which he gave them, as in Neh.
ix. and followed the foolish prophets, that followed their own spirits, and saw nothing,
then their candle went out;
for they went from the spirit of God that should light their spirits, their candle,
and so became wicked in their spirits and minds, and so their candle went out,
they being gone from God, and the light of his spirit, who had enlightened them;
and then how could their candle but go out, when they turned their backs from God,
who did enlighten them by his good spirit:
for the Lord had bestowed a multitude of his mercies and kindness upon them,
and in his love and pity he redeemed them; and bore,
and carried them all the days of old, but they rebelled against him,
and vexed his holy spirit; and therefore, he turned, to be their enemy,
as you may see in Isa. 43.
And so they became wicked, and their candle went out from God`'s light;
and how often had the Lord mercy, and called them back again,
but they rebelled against him?
And so, as it is said, '`how often doth the candle of the wicked go out?`'

So here you may see that God poured out of his spirit upon the house of Israel;
and the house of Israel could not say, but they had God`'s good spirit,
by which they might come to know God`'s good things, and do them,
their candle being lighted by it though '`they rebelled against it,`' as in Neh.
ix. '`that he gave them his good spirit, but they rebelled against it.`'

And in Isa. 63:10. '`they rebelled against, and vexed the good spirit of the Lord,
and therefore, the Lord turned to be their enemy,`' etc.

And so when Christ Jesus came, the Jews were in rebellion against this good spirit,
and resisted Christ Jesus that was conceived by the Holy Ghost;
and so resisted Christ Jesus that came to take away their sins;
but they cleaved to their sins, and chose a murderer before him,
and that brought destruction upon them all; for, turning from the spirit of God,
they turned from Christ their Saviour,
and so the Lord turned down their city and priesthood,
and scattered them over all nations.

And it is said, in Joel 2.
and in Acts '`that the Lord poured out of his spirit upon all flesh,`'
+++[+++mark, upon all flesh,] that is upon Jews and Gentiles,
(for it is said before,) '`that he had poured his spirit upon the house of Israel,
and they rebelled against it;`' but now it is said,
'`the Lord poured out his spirit upon all flesh.`'

For Joel said, '`it shall come to pass afterward,
that I will pour out of my spirit upon all flesh, and sons and daughters shall prophesy,
and old men shall dream dreams, and young men shall see visions; yea,
on every servant and hand-maid will the Lord pour out his spirit.`'

And after Christ was risen that the Holy Ghost fell upon the apostles,
which Christ had promised that he would send, which should lead them into all truth;
and that in it they should believe; and it should reprove the world of their unbelief,
etc. as you may see in Acts. 2. and John 15.

So there is no flesh dare say, but the Lord hath poured out of his good spirit upon them,
except they will give the prophets and the apostles the lie,
and speak against the promise of God and Christ,
and against the spirit of God in their own consciences,
which spirit he hath poured upon all flesh; and all that do rebel against this spirit,
and say, that God hath not poured out of his spirit upon all flesh, they give Christ,
and the prophets, and the apostles the lie, and deny Christ`'s promise,
and speak against that which God hath spoken and performed,
and are the wicked whose candle is put out, and does not shine,
by erring from this spirit.

And so now all flesh, Jews, Gentiles, and christians, that rebel against this spirit,
that God hath poured out upon all their flesh, those sons and daughters do not prophesy;
for their candle is gone out, they cannot prophesy;
and those old men that rebel against this spirit, that God has given them,
have none of the dreams of God; for their candle is gone out by night,
which was lighted by God`'s spirit.

And all the servants and hand-maids that rebel against God`'s spirit,
that is poured upon their hearts and spirits, their candle is gone out,
so that they have no visions of God, and so are become rebellers against God`'s spirit,
in the gospel and christian times,
as the house of Israel did when God poured out of his spirit upon their house,
and so turned their backs upon the Lord, and became wicked,
and then their candle went out; and there all such follow their own spirits,
and see nothing of the things of God; for the natural men perceives them not;
for they are foolishness unto them.
For when their spirits become wicked, either Jews or christians,
they go from God`'s spirit which would keep them in his fear, who lights their spirits,
which is the candle of the Lord: for God lighted David`'s candle, his spirit,
that he saw the state of the Jews, and beyond all their figures and shadows,
to Christ Jesus, and called him Lord: so that made him a prophet, and a seer,
that he saw afar off; and so all the prophets of God,
whose candles or spirits God hath lighted by his spirit and light,
so that they saw Christ Jesus, who was to come to end their law, with all their types,
figures, and shadows.

But the foolish prophets that followed their own spirits, and saw nothing,
but deceived the people for handfuls of barley, and pieces of bread,
which the Lord sent his true prophets to cry against,
whose candles he had lighted by his spirit,
with which they saw the false and foolish prophets, and the Jews that followed them,
that followed their own spirits, who followed them into wickedness,
and so became wicked like them, and so the wicked`'s candle went out,
and though often the Lord brought them back again, and lighted their candle,
yet they turned from the Lord, and followed the imaginations of their own hearts,
and then the candle of the wicked went out, when they rebelled against his spirit,
by which he enlightened them.

And Christ said to his disciples, whom he had enlightened, their spirits, their candles,
'`ye are the light of the world a city set on a hill, that cannot be hid;
neither do men light a candle and put it under a bushel, but on a candlestick,
that it may give light to all that are in the house; let, therefore,
your light so shine before men, that they may see your good works,
and glorify your Father which is in heaven.`' Matt. 5:16.

So here Christ calls his disciples, the light of the world,
whose spirits he had enlightened, their candle; and so they were as a city set on a hill,
in God`'s power, that could not he hid.
So men outwardly do not put their candle,
after they have lighted it to see to do their work by, under a bushel;
for that will hide it, and will not suffer it to give light to the house;
but when the outward candle is lighted by some outward fire,
if a man would set that candle under a bushel, and not set it on a candlestick,
they would think he was mad; for, if so,
people could not see what is in the outward house,
because it doth not give light to all that are in the outward house, to work,
and do their affairs and business by, or to see what is in the house.

And so Christ, who is the light,
who enlightens every man that comes into the world with his divine light,
which is called, the life in the word, which was in the beginning,
who is the light of the world; which is not a natural light, or a created light,
but a spiritual, heavenly, and a divine light,
which enlightens every man`'s spirit that comes into the world, his candle; for,
the spirit of man, is the candle of the Lord, and the candlestick is every man`'s body,
mind, soul, and conscience, that with this spirit their candle being lighted,
and set up in its candlestick, they may see all that is in the house;
and with this light they may see Christ that died for them, and is risen for them:
so come by this light, which is life in the word, to be grafted into Christ the word,
which was in the beginning, which lives and abides, and endures forever.
And so to do the work of God, and to see and believe in the son of God.
So this light must shine, that others may see your good works done in the light,
and wrought in God, and that they may glorify your Father which is in heaven.
And such let their light shine before men.
But they that hate the light, and will not come to it, because it reproves them,
and do not believe in it, they do not let the light, which is the life in Christ,
shine before men, though it is in them to condemn them,
and to let them see all their evil deeds, thoughts, and evil words,
and is as under a bushel; but they will not come to it,
though it is in them shining in their darkness, but love the darkness rather than it,
because it will reprove them, to wit, the light, which would enlighten their spirits,
their candle.

So this light of Christ, which enlightens every man that comes into the world,
is not natural, but enlightens man`'s natural spirit, which is the candle;
and they that love the light, love that which lights their candle, their spirit.

And so Christ saith, '`This is the condemnation, that light is come into the world,
but men love darkness rather than light; for every one that doth evil hates the light,
neither cometh to it, lest his deeds should be reproved.`' So he hates the light,
which is the life in Christ, which should enlighten his spirit or candle;
so they do hate that which should enlighten their candle,
and so are like the scribes and pharisees, and Jews and chief priests,
that stopped their ears, and closed their eyes, and would not see with their eyes,
nor hear with their ears, neither Christ without them,
nor his light nor spirit within them; neither with their inward eye nor ear, nor outward,
as to obey him; for they were like the ancient Jews their forefathers,
'`whom God gave his good spirit unto, but they rebelled against it,
and so against his prophets.`' And so their children rebelled against his Son,
who enlightened them; and hated his light his life, and did evil;
and so the candle of such wicked ones is often put out;
for they follow their own spirits and see nothing of God`'s, nor Christ`'s things;
but they follow their own heart`'s lusts, so as they come to be drowned, at last,
in perdition.

And in Mark 4.
Christ there speaking in parables, said, '`how that the cares of the world,
and the deceitfulness of riches, and the lusts of other things,
chokes the word or good seed,
and they become unfruitful in whom it was sown,`'
and these were such that were called '`thorny ground,
that the word was sown in.
And the good ground in which the word was sown, and it took good root in them,
are they that hear it, and receive it, and bring forth fruit, some thirty, some sixty,
and some an hundred-fold in this life.`'

And he further said unto them, '`is a candle brought to be set under a bushel,
or under a bed, or to be set on a candlestick;
for there is nothing hid that shall not be manifest;
neither is there any thing kept secret, but that it shall come abroad;
if any man hath an ear to hear, let him hear?`'

So the ear that hears this must be opened with the light of Christ,
that hath enlightened his spirit, his candle,
by which he sees and hears what Christ hath spoken,
and is the good ground and brings forth fruit, thirty, sixty, an hundred-fold.

So his light doth shine before men, and they do see his good works,
and glorify their Father which is in heaven.

But after they be enlightened, and the word sown in their hearts,
if the '`cares of the world, and the deceitfulness of riches,
and the lusts of other things,`' enter into them, this chokes them,
and turns their minds and spirits from the light of Christ,
and so they become unfruitful,
not bringing forth fruit from this heavenly light and seed;
so they follow their own imaginations of their hearts, and not Christ,
who enlightens their spirits, their candle, and so their candle goes out,
and the secret things of God are not manifest to them.

But they that follow Christ, that doth enlighten their spirits, their candle,
with his spiritual and heavenly light, Christ saith, '`they shall not walk in darkness,
but shall have the light of life.`'

But they that hate the light, and will not come to it,
and love darkness rather than light, though they be enlightened with it,
they have it to condemn them,
who will not let it have a place in their hearts to guide them, and to believe in it.

And so this light of Christ, which enlightens their spirits,
manifests all secret and hidden things to men and women;
so then they must needs come abroad, when they are known and seen.

So this candle after it is lighted, it is not to be put under a bushel or bed.
Now this is a parable; for you will say,
it is madness for an outward man to put his outward candle,
which he hath lighted to do his work by, at an outward fire, under a bushel or bed,
you will say, he is out of his wits.

And therefore, then, what bushel, or what bed is this,
after Christ hath enlightened your candle, with his divine and spiritual light?
What bed or bushel are you thrusting your candle under, after he has enlightened it?
are not you them that hate the light, and would not have it seen like the pharisees,
that loved not Christ, the light, which shined,
that you will not let it stand in your candlesticks, up in your house, your hearts,
to give light to all that are in the house,
that you may see what you are doing in your house,
and what evil company you keep in your house, in your hearts all your lifetime?
For there is nothing secret, but the light will discover it;
nor nothing hidden there in your house, your hearts, but the light will manifest it:
and there is nothing (to the believers in the light of God,) of the things of God,
hidden or secret, since the foundation of the world, but the light will reveal it,
or manifest it to them, that they may preach it to others,
that they may preach it on the housetop. Luke 8:16.

Now, '`every one that doth evil, he hates the light,`' which hath enlightened his candle,
'`and will not come to the light,
because the light will reprove him,`' and this light is his condemnation;
for he deserves it: and then, it may be, he may say it is not sufficient,
that loves darkness rather than light.

But Christ saith, '`he that believeth and followeth me, and loveth the light,
shall not walk in darkness, nor come into condemnation;
and he shall see his deeds wrought in God.`' John 8:12.

'`And he that believeth in Christ that doth enlighten him,`' his spirit, his candle,
'`shall be saved; and he that doth not believe in Christ, the light,
is condemned already; and the candle of the wicked is put out.`'

And again, Christ saith, in Luke xi.
where he reproves the Jews,
'`no man when he hath lighted a candle puts it in a secret place, nor under a bushel,
but on a candlestick, that they who come in may see the light.`'

'`The light of the body,`' says he '`is the eye, therefore, when thy eye is single,
thy body is full of light; but, when thy eye is evil, thy body is full of darkness;
take heed, therefore, that the light which is in thee be not darkness;
if thy whole body be full of light, having no part dark,
thy whole body shall be full of light,
as when the bright shining of a candle doth give thee light.`' Luke 11:34-36.

Now these Jews and pharisees were erred from the spirit of God,
which he had poured upon the house of Israel,
which spirit of God would have lighted their candles, their spirits;
and their light should have shined, and been up in their candlesticks,
and not under a bushel, or in a secret place: nevertheless, these priests, scribes,
and pharisees, which were erred from the spirit that God had poured upon them,
and made a profession of the law and prophets without his spirit,
what a bed and bushel had they put their light under,
and yet would make a profession of God, and Christ to come,
but were erred from the spirit that God had poured upon them, and turned against Christ,
who came to enlighten them, and every man, and therefore their eyes were not single,
but evil against Christ, who came to enlighten their spirits, their candle;
and they blasphemed against him: how, therefore,
could their bodies but be full of darkness, and their eyes not single?

And therefore, all you that profess yourselves christians,
upon whom God hath poured out his spirit, and upon all flesh:
and Christ hath enlightened every man that comes into the world, to wit, their spirits,
their candles, with his light, which is the life in the word,
by which all things were made; and you call his light, which is the life in Christ,
the word, '`a natural, created and dim light,
and of the devil and antichrist;`' and some call it,
'`a created and insufficient light:`' are not here your eyes evil against the light,
that should light your spirits, your candle, which light is the life in Christ the word?
And then how can your bodies but be full of darkness,
which have such evil and not single eyes in you?
Who are found in the same spirit and path, as the Jews were,
in your vain janglings and disputes against the light of Christ,
as the Jews of old about the prophet`'s words, and against Christ;
so are you jangling about Christ`'s and the apostle`'s words, and are against the light,
which is the life in Christ; following your own spirits, and see nothing, natural men,
that perceive not the things of God, which to you are foolishness.

So that which you call light, (how could Christ but say as he does,) '`take heed,
therefore, lest that light which is in you be darkness,`' who reject the light of Christ,
pharisee and Jew-like, which should light your candles, your spirits,
that you may see Christ your Saviour, your way, truth, and life.

Now the single eye that receives the light of Christ,
who lighteth his spirit with his light, which is the light, which is the life;
and the candle being set up in its stick, which gives light to all in the house or body,
so that the whole body comes to be full of light,
as a bright shining candle shines in an outward house,
so his bright shining light and life shines in man`'s body, whose eye is single,
so that his body is full of light, which lights his candle;
which light gives him '`the knowledge of the glory of God
in the face of Christ Jesus,`' that lighteth him.
2 Cor. 4.

And Christ saith, in his parable to the murmuring scribes and pharisees,
that murmured against him because he received sinners,
'`what woman having ten pieces of silver, if she hath lost one piece,
doth not light a candle, and sweep the house,
and seek diligently till she find it?`' Luke 15:8.

This woman lights her candle at an outward fire, and she sweeps her house,
when her candle is lighted, with an outward besom,
and diligently seeks till she finds it, '`and when she hath found it she rejoices,
and calls her neighbours together,
and tells them that she hath found her piece of silver.`'

Now this is a parable, but is not God`'s silver lost in man and woman`'s foul house,
since they fell; and in the Jew`'s house since they erred from the spirit of God?
And must not every man and woman light their candle at God`'s and Christ`'s spirit,
light, and fire?
'`Who is a consuming fire to the wicked;`' and '`who shall sit as a refiner`'s fire,
and burn up the chaff with unquenchable fire.`'

So must not every man and woman`'s spirit, which is their candle, being lighted;
must not they after their candle is lighted at Christ`'s light and fire,
with which he burns up the chaff, forsake the evil and cleave to the good spirit,
and believe in the light, as Christ commands, and bring their deeds to the light,
and so sweep the house with God`'s besom, with his power and spirit;
and then they find the pearl hid in their own field,
the leaven in the three pecks of meal;
and the seed of the kingdom like unto a grain of mustard seed.
And then they sell all that they have gotten since man was driven into the earth,
and fallen from the image of God, to purchase the field;
for there is nothing will purchase the field,
but parting with all that man and woman have gotten and stored up,
since they fell from the image of God in paradise.

And so, all your houses are dark and foul,
and you cannot find God`'s silver till your candles be lighted,
by believing in the light, which Christ lights your spirits, your candles withal.

And then, when your candle is lighted by Christ`'s heavenly light and fire,
you will see what a blasphemous spirit you have entertained in your house,
and have been married to, that has brought you to call the light,
which is the life in Christ, natural and created, Jack with a lantern, the devil,
antichrist, the Quakers`' idol, etc.
And with these blasphemous words have blasphemed against the heavenly divine light,
which is the life in Christ the word; by which all things were made,
'`which lighteth every man that cometh into the world;
which light there was a man sent from God to bear witness of, whose name was John,
that all men through him might believe.`' John 1.

And he said,
'`he was not that light,`' though he was the greatest prophet born of a woman:
but he said, '`that was the true light,
which lighteth every man that cometh into the world;`' and the world was made by him,
though they knew him not, therefore they were dark.
'`And he came to his own,`' to wit, the Jews,
'`and they received him not,`' they were so dark also; and this was true,
the Jews received him not, but persecuted them that did receive him, and therefore,
they were blind, and they thought they were in the light, because they could say,
'`they were of Abraham;`' but well might Christ say to them,
'`if that light that is in you be darkness,
how great is that darkness?`' That would not receive Christ the light,
who had erred from God`'s spirit, which he had poured upon their house.

And so Christ is the true light, that lighteth every man`'s candle, every man`'s spirit,
(which is dark and natural,) though they hate it.

And so now, may it not be said of the christians, as it was said of the Jews,
who would neither see with their eyes, nor hear with their ears, who were wilful,
Christ came to his own,
and they '`would not receive him;`' what him would they not receive?
they would not receive the true light,
that lighteth every man that cometh into the world,
every man`'s candle and spirit which is dark and natural, and know not the things of God;
but those spirits and candles that are lighted believe in the light,
and they know the things of God that are revealed to them by the spirit,
and become children of light.

And so you called christians, that will not receive him, to wit, Christ the light,
who are called after the name christians,
and yet will not receive him that lighteth every man that cometh into the world;
and you will have none of Christ`'s light, nor believe in it,
which is the life in the word, but follow your own spirits and see nothing;
natural men that see not the things of God, whose candles are put out;
but as many as believe in his light, and receive him,
'`to them he gives power to become the sons of God.`'

And this light shines in your darkness, and your darkness comprehends it not,
who do the evil, and love the darkness rather than the light; and therefore,
the light is your condemnation, and you will find it sufficient to condemn you,
though you say it is not sufficient, by believing in it to save you.

And so you called Christians, and Jews,
that have spoken so much evil against Christ and his light, the light in the word,
by which all things were made;
and do neither believe John the greatest prophet born of a woman, what he witnessed,
and bore witness to, nor Christ the light; though it may shine in your darkness,
yet you loving the darkness more than the light, and hating the light,
you cannot comprehend the light with your darkness; and this will be your condemnation,
which would have enlightened your candles, your spirits, that you might see your sins,
and see your Saviour, him who enlightens you.

Now Aaron, the high priest, lighted the seven lamps in the candlesticks,
that stood in the tabernacle,
(a perfect number,) as in Num. 8:2-3. And the candlesticks were made of pure gold;
and Aaron had the charge of these candlesticks, and of the lamps to light them:
and he was to cause the lamps to burn always in the tabernacle of the congregation,
without the veil, as in Ex. 26:20.

And Aaron, the high priest, who was anointed to that office, was to dress the lamps,
which was a type of Christ our high priest, whom God hath anointed with the Holy Ghost,
who lights with his everlasting light, (not natural;
for that they had before,) the lamps or spirits of men,
with his everlasting light and fire, without the veil, that they see over all veils,
and the bright shining of their lights is to to be
seen abroad to the election before the world began.
So this everlasting light and fire must shine and burn in every one`'s tabernacle;
and their lamps and spirits being lighted,
then the sweet pure incense is offered up to the heavenly God,
in his pure heavenly fire from his altar, the pure heart that sees God,
which Aaron`'s incense was a type of, as in Exodus xxx.

And Aaron made the candlesticks of pure beaten gold, a metal wherein is no dross:
so man must be moulded and purified, and all the filth in mind, soul, and spirit,
must be beaten, tempered, and hammered down,
before he is a fit candlestick to stand in the tabernacle of God.

And the apostle, in Hebrews, comes to show the end of all those offerings,
and candlesticks, and tables, and golden censers, and arks,
and all those things that were held up by the law and first covenant,
as may be seen in Heb. 9. throughout, and other places.
And how Christ came as in the volume of the book, to do the will of God, and he said,
'`lo, I come to do thy will, oh God, to take away the first covenant, law,
and priesthood, that I may establish the second:`' blessed be his name forever,
as you may see in Heb. 10:9.

And so Christ is our high priest, that gives light and fire to the lamps,
and lights the candles, the spirits of men, with his heavenly divine light and fire,
so that their lamps may burn always in the tabernacle or temples,
whose bodies are the temples of God:
for Aaron lighted the outward lamps and dressed them, and the candlesticks:
but Christ lights the inward and dresses them.
And Aaron`'s seven lamps which were outward, were a type of the seven lamps of fire,
which burn before the throne of God, which seven lamps are the seven spirits of God. Rev. 4:5.

And John said, '`he beheld in the midst of the throne, and in the midst of the elders,
etc. stood a lamb as it had been slain, having seven horns and seven eyes,
which are the seven spirits of God,
sent forth into all the world.`' A perfect number of lamps, of eyes, of spirits,
of stars, and trumpets, and vials; this hath Christ our high priest,
who ends Aaron`'s trumpets, candlesticks, lamps, horns, and altars;
for here is heavenly lamps to burn, heavenly eyes to see,
and heavenly horns to push and throw down all his enemies,
and to make them his footstool, and to stand upon them in his glorious power.

And they be his enemies that resist his holy spirit, and turn his grace into wantonness,
and hate his light; so he in his light, grace, and spirit, comes over them,
and they go into darkness, and the light of the candle shall shine no more in them,
nor the voice of the bridegroom nor bride shall be heard any more in them;
for down Babylon is thrown, and judged.

And John saith, in his revelations, '`I saw seven golden candlesticks;
in the midst of the seven golden candlesticks one like the Son of man,
clothed in a garment down to the foot, girt about his paps with a golden girdle,
his head and his hair were like wool, as white as snow, his eyes were as a flame of fire,
and his feet like unto fine brass, as if they burnt in a furnace,`' etc.

'`And unto the angel of the church of Ephesus write these things, saith he,`' to wit,
Christ, '`that holdeth the seven stars in his right hand,
who walketh in the midst of the seven golden candlesticks: I am he who lives forever,
who was dead; but behold, I am alive forevermore,
and have the keys of hell and death.`' Rev. 1. 2.

Now they whose candles are lighted by Christ`'s heavenly divine light and fire,
can see where Christ walks, who was dead, and is alive, and lives forevermore:
for he walks in the midst of the seven golden candlesticks,
and the seven golden candlesticks are the seven churches,
Christ hath lighted their candles, their spirit, and their lamps,
that they might burn and shine always.

So now, here is an end of all Aaron`'s lamps and candlesticks,
and outward oil and tabernacle, for they were worldly, made with men`'s hands;
his golden candlesticks were a type of these golden candlesticks the churches,
which are his people, '`his living members, the believers born of God, living stones,
the household of faith, a holy people elect and precious,
built up together a spiritual household.`'

And these are the churches, and he that holds the seven stars,
which are the seven angels, in his right hand,
is Christ that was dead and is alive again, and lives forevermore;
and is first and last, and the head of his church;
and he walketh in the midst of his seven golden candlesticks, that is,
in the midst of his churches, his people: and they whose candles,
whose spirits he has lighted with his holy and divine light and fire,
see him walk in the midst of his seven golden churches, and there exercising his offices,
as he is a king to rule in their hearts, and as he is a priest,
who offered up himself for them,
and who offers his people to God without spot or blemish, and as he is a prophet,
he opens to his churches, and they hear him the spiritual man,
what he saith to the churches.

Now all the false churches, who will not own him in his light,
that lighteth every man`'s spirit or candle,
(that believe in it,) it is their condemnation.

And they that do believe in the light which Christ hath enlightened them withal,
are children of the light, and so members of the true church which Christ is the head of.

Now they that do evil and hate the light, which should enlighten their candle,
their spirit, (like the Jews, scribes, and pharisees, and chief priests, christians,
or others,) and set up churches, and have elders and members like the pharisees,
and they cannot see Christ walk in the midst of their churches,
that do believe in Christ the light, which lighteth every man that cometh into the world;
for, how can they that hate his light, which should enlighten their spirits,
their candles; therefore, they cannot be called the golden candlesticks,
that are made up of the beaten gold that is tried in the fire.

And so revelation is a mystery to them, though John had been a fisherman,
and one that could not read the letters,
but you did not read that the seven golden candlesticks,
which were the seven churches did tell John, that what he wrote was mysteries to them,
and that they did not understand it;
for Christ had enlightened their candles that they might see;
and he walked in the midst of these seven churches, and therefore, they that do not see,
do not believe in Christ, who lighteth their spirits, their minds, and hearts,
and understandings; so cannot be grafted into Christ the life,
but by belief in Christ the light.

For Christ said,
'`he that hath an ear let him hear what the spirit saith to the churches;`' and you
that have not the same spiritual ear cannot hear what the spirit saith to the churches:
and you that say you have not the same spirit as the apostles and the churches had;
and say, that the spirit does not speak nowadays, as it did in the apostles`' days,
your ears are stopped,
and you are not like to hear what the spirit saith to the churches.

But Christ who was the beginning and the ending, the first and last,
and the same yesterday, today, and forever; who is the heavenly and spiritual man,
does walk in the midst of his golden candlesticks, glory to God forever,
and he is known and seen to walk now in the midst of his churches,
'`the general assembly written in heaven,`' which are called the heavenly Jerusalem,
who are the living members of him the living head;
and the living shepherd that feeds with his living bread, his churches,
his people in the living pastures of life, who walks in the midst of his sheep,
his church, and his sheep hear his voice, and follow him,
and will not follow any of the flying hirelings, nor climbing thieves,
that will not come in at the door by the light that
Christ hath enlightened every man withal.

And also, Christ stands at the door and knocks, and therefore, Christ is nigh,
when he stands at the door of your hearts and knocks with his power, light, and grace:
for Christ saith, '`behold, (that is to say, take notice, if you will regard,
and will not be like the chief priests and pharisees, that will not regard,) behold,
(says he,) I stand at the door and knock, if any man +++[+++mark, it is general,]
hear my voice, and open the door, I will come in to him, and I will sup with him,
and he with me.`' Rev. 3:20.

Now you say, and teach, (that call Christ the light,
that enlightens every man that comes into the world,
a natural light,) that there is no hearing Christ`'s voice nowadays, and that is strange,
cannot you hear his voice, he stands and knocks at the door of your hearts?
What will you be just like your forefathers the pharisees
and Jews! '`Have ears and hear not,
eyes and will not see, and hearts and will not perceive,`' I believe,
if a man should knock at your door, and tell you of a benefice of a thousand a year,
you could open your doors soon enough, the doors of your ears, minds,
and spirits would be quickly enough open to that, to hear such an one:
but Christ knocks at your door, and you say and tell people,
there is no hearing his voice nowadays; no hearing of his voice that saith,
'`freely you have received, freely give.`' Oh! this cuts self; it is no wonder,
if you will not hear his voice: but how can you sup with Christ, and he with you,
the heavenly supper, except you hear his voice, and open the door of your hearts,
and minds, and souls, and let him in, by turning from the darkness to the light,
and from the power of Satan unto God?

And how can you say, you are ministers of Christ, and yet say,
there is no hearing of his voice, when he stands at the door and knocks?

But are you not such, as run when God never sent you,
and speak when God and Christ never spoke unto you, and yet you talk of faith, and grace,
and the spirit?
And what a strange doctrine is this, that there is no hearing of Christ by his grace,
which should teach them, and bring their salvation; and by his spirit,
which he hath poured upon all flesh;
and by his light with which he hath enlightened every one that cometh into the world,
and bids them believe in the light!
May it not well be said, the candle of you wicked is put out, who are dark indeed,
and cannot see?

And how can any such be ministers of Christ, that own not Christ`'s light,
that lighteth every man that cometh into the world; who lights their candles,
their spirits, by believing in him the light, and so they become children of light;
who see the things of Christ the heavenly and spiritual man, and of his kingdom.

And we know that the Jews were against John, and said,
'`he had a devil,`' that came for a witness, to bear witness of the light, and said,
'`that was the true light that lighteth every one that cometh into the world,
that through him every man might believe.`' And so it is not strange
that such as profess themselves to be preachers of Christ,
and christians should say now,
that the true light which lighteth every man that cometh into the world, is of the devil,
and the Quakers`' idol, and natural and a corrupt conscience, and the like;
but Christ saith,
'`believe in the light while you have it,`' showing that
people have the light before they can believe in it;
and therefore he exhorts them, '`to believe in the light,
that they may become children of the light;`' so
their candle is lighted that believe in it:
and such are they that preach Christ`'s holy kingdom, that see it, and know it,
and preach the Lord Jesus Christ, and not themselves, and warn people to repentance,
and newness of life, and turn them from darkness to light,
and from the power of Satan to God: and so the light enlightens their candles,
their spirits, and they come to be children of the light,
and of the everlasting day of Christ.
And all that will not own Christ and his light,
that enlightens every man that comes into the world, but give bad names to his light,
which is the life in him, are natural men that know not the things of God,
and follow their own spirits, like the foolish prophets, and see nothing;
and lead people after them into death and darkness for means,
as they did in the days of the Jews: and do the evil, and hate the light,
and will not come to it, because it will reprove them of their evil deeds;
such Christ enlightens, but it will be their condemnation;
for they put darkness for light, and evil for good, and they are the wicked,
whose candle is put out.

And in Rev. 18:23. where John speaks of the fall of Babylon, and saith,
'`that the light of a candle shall shine no more at all in her, (to wit,
Babylon,) and the voice of the bridegroom, and of the bride,
shall be heard no more at all in her; this is mystery Babylon the mother of all harlots,
and all nations have drank of her cup, which sat upon the beast,
which all the world have worshipped, and made war with the saints;
and all the blood of the martyrs, prophets,
and saints is found in her.`' And this mystery Babylon is not seen,
but by them whose candle is lighted by believing in the light of Christ:
for all the persecution of God`'s people is found in her and the beast, yea,
'`in her was found the blood of all the prophets,
and of all the saints that were slain upon the earth;`' mark, in this mystery Babylon,
mother of harlots.
And this is the spirit of the beast and the whore, that is whored from God and Christ,
and his faith, and spirit, and grace, and truth;
yet will have a profession of the prophets`' words, Jew-like,
and Christ`'s and the apostles`' words,
and yet are out of the power and spirit that they were in,
and persecute them that be in the same power and spirit,
which the prophets and apostles were in.
So all the persecution of the prophets, and saints, and holy men and women of God,
and the blood of all the saints is found in her: and though she may reach to heaven,
yet she must fall, and when she is fallen, the marriage of the Lamb is known,
and the saints sing hallelujah.
And it is said, '`the light of a candle shall shine no more at all in her,`' to wit,
mystery Babylon,
'`nor the voice of the bridegroom and of the bride
shall be heard no more at all in her.`'

Now, these prophets and saints, who were married to Christ Jesus,
have called and warned the whore, beast, and her company;
for did not John prophesy to tongues and nations?
and is not the gospel preached to all nations, tongues, and people,
which have been the waters which the whore sat upon?
and Christ has called them by his grace, light, power, and spirit to repentance;
but they would not repent: and has not the loud voice gone forth,
'`fear God and give glory to him, and worship not the beast,
but worship God that made heaven and earth;`' but they repented not: for it is said,
'`when the fourth vial was poured out, men were scorched with great heat,
and they blasphemed, and repented not to give glory to God.
And when the fifth angel poured out his vial upon the seat of the beast,
which the beast and the whore sat upon, mystery Babylon,
the beast`'s kingdom was full of darkness, and they gnawed their tongues for pain,
and blasphemed the God of heaven, because of their pains and sores,
and they repented not.`' So went willfully on to destruction, the beast, whore,
and its worshippers. Rev. 16:10-9.

Now, if they did not repent, they grieved God`'s good spirit,
which called them to repentance, like the old world,
and so the beast that all the world worships,
and the whore that drinks the blood of the saints, and all the nations drink of her cup,
who sits upon the waters, which are nations, tongues, and people.
So this beast, and whore, and their followers, are in the unrepented state;
and such are they that hate the light,
which Christ hath lighted all that come into the world withal; and lighted them,
the whore, and beast, and their worshippers,
by which light they might see their evil deeds,
and the abomination of their filthiness and persecution; but they hate it, and therefore,
they are condemned with it, and go into the fire with the devil and his angels,
that are out of the truth.
And the light of the candle shall shine no more in Babylon,
which has enlightened their spirits, that they might see their deeds and repent;
but they repent not of their evil deeds; so they turned not to the light,
which would have lighted their candle, and made it shine; but they hating it,
and turning from it, this light of the candle, shall shine no more in Babylon,
but be her condemnation, and then is the candle of the wicked put out.

And then how can they hear the voice of the bridegroom, or the bride, the wife of Christ,
his church, that is married to him, when they will not hear the voice of his light,
that would let them see their evil deeds and repent.

But the saints in light that walk in that light, have fellowship in it, and with the Son,
and with the Father, and they shall sing hallelujah, Rev.
xix. '`and they shall say, true and righteous are the judgments of the great God,
that hath judged the great whore,
that hath corrupted the earth:`' for Christ has died for all men,
and all men have been and are enlightened by Christ,
but they will not believe in it and repent:
and the gospel of peace has been preached to all nations, but they will not receive it;
and therefore, the light is their condemnation that hate it,
which should enlighten their spirits, and so they grow dark;
so the light of a candle shall shine no more in Babylon, but be her condemnation,
though it be the just man`'s path, which is as a '`shining light,
which shines more and more to the perfect day.`'

And you may see, when that the plagues and woes were poured upon the wicked,
in Rev. 9:20-21. '`yet repented not they of the works of their hands,
that they should not worship devils, and idols of gold, and silver, and brass, and stone,
and wood, which neither could see, nor hear, nor speak, nor walk.`'

And is there not too many of these found among christians,
besides what is found in the world, that worship such things,
that do not repent and turn from them.
Neither repented they of their murders, nor of their sorceries,
nor of their fornications, nor of their thefts,
as too many of those called christians do not now.

So these were enlightened by Christ to see their evil deeds,
or else how could they be admonished to repent, or change, or turn from them;
and therefore are they warned not to worship such things, nor follow such evils,
but to believe in the light, and become children of the light,
and so to worship God in the spirit and truth, which the devil is out of,
and the beast and the whore that is a-top of him.
And therefore, if they do not repent, God is just in bringing all his woes, judgments,
and plagues upon them, and judging them by the man Christ Jesus, according to the gospel,
the power of God, which is preached to every creature under heaven;
and according to the light which Christ hath enlightened them, and every man withal;
and according to the grace of God which appeared unto all men, to teach them,
and to bring their salvation; but they walked despitefully against the spirit of grace,
and turned it into lasciviousness.

So the righteous God, king over all the earth,
is just in his judgments upon all such rebels.
And in Rev. 2:20. there you may see how God and Christ gave Jezebel,
who called herself a prophetess, who was a teacher,
and seduced his servants to eat things sacrificed to idols;
God gave this Jezebel a space to repent of her fornications, and she repented not.

Now, this Jezebel might preach the prophets`', Christ`'s, and the apostles`' words,
from Genesis to the Revelations, and Christ`'s death and resurrection,
but in the unrepentant state.

Now she was enlightened to see what she was to repent of, and turn from,
so she had her space, her time, her visitation,
as all men have before God brings his judgments upon them;
and their candle is lighted by the light of Christ,
that they may see what they should do, and what they should not do: and therefore,
God does reward every one according to their works; and they that hate the light,
their candle is put out, by joining to the evil, and doing evil,
and not coming to the light to light their candle with, but hating it,
and erring from God`'s spirit, which would keep it lighted,
which light would manifest their evil deeds, and reprove them for it; therefore,
the light is their condemnation, which light they should have believed in,
and become children of.

And therefore, saith God, concerning Jezebel, who does not repent, '`behold,`' that is,
take notice, '`I will cast her into a bed,
and them that commit adultery with her into great tribulation, except they repent;
and I will kill her children with death, and all the churches shall know that I am he,
who searcheth the reins and hearts;
and I will give to every one of you according to your works.`'

So there is a light in all people, which Christ enlightens them withal,
that will let them see whether their works be good, or whether they be evil;
so that Christ who is the righteousness of God,
and will judge the world in righteousness,
he will judge them according to the light which lets
them see whatsoever they have done or spoken;
so that every tongue shall confess, that he is true and just in his judgments,
and will judge with equity, and not condemn man for that which he hath not,
but for that which he hath, and hath not obeyed, nor been faithful to it.

And they that believe in the light, as Christ commands, their spirits,
their candle is enlightened, and they become children of the light,
and are grafted into Christ, who is the first and last,
and see him walk in the midst of his churches, who is the head of them,
which the unrepentant and haters of the light, and errers and,
strayers from the spirit are not like; for the true church is come to Mount Zion,
the city of the living God, the heavenly Jerusalem,
and to an innumerable company of angels, to the general assembly,
the church of the first born, and to God, the judge of all,
and the spirits of just men made perfect, and to Jesus, the Mediator of the new covenant,
and to the blood of sprinkling, that speaks better things than that of Abel:
for the blood of Abel cried for vengeance against Cain,
but the blood of Christ cleanses from all sin, and justifies.

And so the saints, the church that are in this new covenant, and come to Jesus,
the Mediator of it, betwixt them and God, they see him walk in the midst of his churches,
his general assembly, exercising his offices, as a shepherd to feed them,
and a counsellor to counsel them, and a bishop to oversee them,
and as a prophet to open to them, whom they do hear,
and as a priest that offered up himself for them;
and offers them up to God without spot or wrinkle,
and as a king to rule them in their hearts by faith.

And all they that quench, vex and grieve the spirit of God, and rebel against it,
and resist the Holy Ghost, that are erred from the spirit of God;
and likewise all they that turn the grace of God,
which has appeared unto all men to teach them, and bring their salvation into wantonness,
and walk despitefully against it.

And also, all they that are haters of the light, which is the life in Christ the word,
which is the true light, that lighteth every man that comes into the world;
and all they that err from the faith, and make shipwreck of it and a good conscience,
are in the unrepented state, unconverted, untranslated, and unregenerated;
and Christ stands at the doors of such and knocks, and saith unto them,
'`behold (that is to say, take notice,) if any man will open unto me, (to wit,
any man of you all,) and hear my voice, I will come in to him, and sup with him,
and he shall sup with me.`'

Now, there is no man opens to Christ and hears his voice, but he joins to the spirit,
grace, faith, and light, and truth in the inward parts;
and turns at the reproof of the Holy Ghost, which Christ hath sent; and with the grace,
light, truth, and spirit, they let in Christ into their hearts:
for Christ is in his saints, and dwells in his saints, and they are reprobates,
that Christ is not in: therefore, examine yourselves,
though you may make a profession from Genesis to the Revelations, of Christ`'s,
and his prophets`', and apostles`' words; yet, if Christ be not in you,
you are reprobates.

So he stands at your doors and knocks; so you cannot say, but that Christ does visit you,
when he stands at your doors and knocks, and tells, if any man hear his voice,
and open the door, he will come in to you, and sup with you;
so you are all left without excuse in the day that he judges you,
and none can plead ignorance, but they have been warned; yea,
none of the house of Adam in the fall, for Christ hath enlightened them all,
and his grace has appeared unto them all,
and he has poured out of his spirit upon all flesh.
For the first man Adam was made of the earth, earthly,
the second man is the Lord from heaven: the first man was made a living soul,
the second man is a quickening spirit.

Now all being in the fall of Adam,
and Adam and his whole house being fallen from the image of God into sin and darkness,
Christ the second Adam died for them all, and enlightens them all,
and the grace of God which bringeth salvation, hath appeared to them all;
and God hath poured out his spirit upon all flesh, and Christ is a quickening spirit.

All they that believe in the light, their spirits, their candle is enlightened,
and they know Christ a quickening spirit, this spiritual heavenly man:
and they that do not believe in the light, but hate it, and grieve the spirit,
and turn his grace into wantonness, and walk despitefully against it,
the candles of those wicked are put out.

And here Christ is just and true in his judgments upon the world,
who judges them in equity, according to the spirit that is poured upon all,
and the grace which hath appeared unto all,
and the light of Christ which has enlightened all; and Christ died for all,
and what could God have done more, (for the ungodly world,) who is just and righteous,
and true in all his judgments?
All that walk in the spirit, and believe in the light, and in his grace,
it teacheth them, and brings their salvation, and they that follow Christ,
from whence the grace comes, in the belief in his light, have everlasting life;
and here is God`'s love to the world; that whosoever believes on him shall not perish,
but have everlasting life; for they that perish, perish for not believing in the Son,
whom God has sent in his love, who enlightens them all with a true and saving light,
which is the life in him the word; and bids them believe in the light,
that they may be grafted into him the root.

And so they that are not grafted into Christ, it is because of unbelief;
and though christians may say, they believe in Christ, and the Jews may say,
they believe in God, and the Messiah to come, yet if they do not believe in the light,
as Christ has commanded,
which is the life in the word by which all things were made and created,
they are not grafted into Christ the life.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 2d of the 4th Month, 1677.
