[.style-blurb, short="A Testimony concerning the Blood of the Old Covenant"]
== A Testimony concerning the Blood of the Old Covenant, and the Blood of the New Covenant, etc.--By G. F.

Moses took the blood of the oxen and calves that were offered for sacrifices,
burnt-offerings and peace-offerings, and sprinkled it upon the altar,
and upon the people, and said unto them,
'`behold the blood of the covenant which the Lord hath made with you:`' so the life
of the beasts and other creatures (which is blood,) was the blood of the old covenant.

And after Moses had sprinkled the people, he sprinkled the tabernacle,
and the vessels of the ministry, he sprinkled Aaron and his sons,
and he sprinkled the books of the Old Testament;
so the first testament and covenant was dedicated
with the blood of beasts and other creatures,
which was the life of beasts and other creatures;
and almost all things were by the law of Moses, purged with blood,
which was the life of beasts.
And without shedding of blood there was no remission of sin.
And, (as I said before,) when Moses had sprinkled the books of the Old Testament,
and the people with the blood, (which was the life of beasts,) he said,
'`this is the blood of the covenant and testament which God hath enjoined
to you.`' So the blood of the old covenant and the Old Testament,
was the life of the clean beasts without blemish,
(as I said before,) for is not the blood the life?
And it is not possible that the blood, the life of bulls, goats,
or other creatures in the old covenant should take away sin.
But in the new covenant it is written,
'`forasmuch as we are not redeemed with corruptible things, nor with silver, nor gold,
from our vain conversations, or tradition of our forefathers,
but with the precious blood of Christ, a Lamb without blemish or spot,
which Lamb was foreordained,
before the foundation of the world,`' and was manifested in the apostles`' time and days,
which he calls the last times.
Silver and gold are corruptible things, which cannot redeem from corruption,
nor the blood of bulls, goats, or other creatures, which will corrupt,
but the blood of the Lamb, which was ordained before the foundation of the world,
and manifested in the last times, in the new covenant; this precious blood of the Lamb,
without spot or blemish, Christ Jesus, doth not corrupt,
for it doth redeem from the traditions of our forefathers, the Jews in the old covenant,
and the corruptible blood of bulls, goats, and other creatures,
that could not take away sin.
And so, by the blood of the Lamb Christ Jesus,
the saints are redeemed from their vain conversation and corruptible life,
to a conversation in heaven, and incorruptible life.

And as Moses in the old covenant sprinkled the people with the blood, the life of beasts;
so Christ our high priest sprinkles the hearts and consciences
of his people in the new covenant with his blood,
his life, '`from their dead works,
that they may serve the living God in newness of life:`' and as
the blood of the old covenant was the life of the beasts,
so the blood of the everlasting covenant is the life of Christ the Lamb,
ordained before the foundation of the world, who is the great shepherd of his sheep,
through the blood of his everlasting covenant '`he makes
his saints perfect in every good work to do his will,
working in them that which is well pleasing in his sight.`'

So it is clear, the blood of the everlasting new covenant is the life of Christ Jesus;
and the, blood of the old covenant was the life of the beasts,
and the bodies of those beasts in the old covenant were burnt without the Jews`' camp,
and the blood was brought into the sanctuary by the high priest,
as an atonement for the sins of the priests and people; wherefore, Jesus also,
that he might sanctify his people with his own blood,
suffered without the gates of Jerusalem: let us go, therefore, unto him, (to wit,
Christ,) without the Jews`' camp, bearing Christ`'s reproach, who was reproached,
who sanctifies with his blood, his life, which dedicates the new covenant;
so that all may come to Jesus the Mediator of the new covenant,
and his blood of sprinkling, that speaketh better things than that of Abel,
or of the blood of bulls and goats, the life of beasts; for Christ being a high priest,
and of a more perfect tabernacle than that which was made with hands in the old covenant,
did not enter into the holy place made with hands, by the blood of bulls, goats,
and calves, as the priests of the old covenant did.
But Christ, the Lamb of God, ordained before the foundation of the world,
which was manifested in time, by his own blood, his life,
entered once into the holy place, into heaven itself,
(now to appear in the presence of God for us,) having obtained eternal redemption for us:
so it is the blood, the life of Christ in the new covenant, that cleanseth from all sin,
who through the eternal spirit offered himself without spot to God,
to purge our consciences from dead works, to serve the living God:
for this cause he is the Mediator of the New Testament.

And so Christ was once offered for sin, who tasted death for every man;
so he takes away the first covenant, that he may establish the second,
and by one offering he hath perfected forever them that are sanctified;
so it is by the blood of Christ, by which all his peoples`' sins are washed away,
who did and do confess, that Christ hath redeemed them to God by his blood,
and their garments were made white with the blood of the Lamb.

So the blood of the old covenant was the life of the beasts and other creatures;
and the blood of the new covenant is the life of Christ Jesus, who saith,
'`except ye eat my flesh, and drink my blood, ye have no life in you.`' John 6:53.

So the blood of the new covenant is not according to the old;
and so with this blood of the new covenant must every one feel their hearts sprinkled,
if they have life; and in this new covenant they shall all know the Lord, etc.
And by this blood of Jesus, his life in the new covenant, they are justified,
in whom we have redemption and the forgiveness of sins;
and Christ hath purchased his church with his own blood, his life,
and their faith doth stand in his blood, which is the life of the Lamb.
Therefore, the apostle saith, '`if ye walk in the light, as he is in the light,
then have ye fellowship one with another, and the blood of Christ Jesus, his Son,
cleanses from all sin.`'

So it is not the blood of bulls, goats, or the blood of other creatures,
which was the blood of the old covenant, nor their outward washings in it,
that takes away sin; but the blood of the new covenant,
which is the blood of the Lamb without blemish, Christ Jesus, the blood of the Lamb,
the life of the Lamb, with which Christ, the high priest sanctifies,
cleanses and redeems; and he washes with his own life, his blood; yea,
he sprinkles the altar of their hearts,
that they may offer a sacrifice of praise to God continually, that is,
the fruits of our lips giving thanks to his name.

So you are bought and purchased with the blood of Christ, the life of Christ,
who has died for you, and risen for your justification, that all might live to him,
and not to themselves, and glorify him in body, soul and spirit, which are his,
who hath purchased you with his blood, his life;
so worthy is the Lamb to receive glory and honour,
who hath redeemed us to God by his blood, and hath washed us from our sins by his blood,
and our garments are made white by the blood of the Lamb.
So the saints do overcome by the blood, the life of the Lamb, who was dead,
and is alive again, and lives forevermore.

So the blood of the old covenant was the life of lambs and beasts without blemish,
by which all things were cleansed and sprinkled withal, yea,
the tabernacle and the vessels, priests and people with the blood,
the life of the clean beasts without blemish, in the old covenant, and Old Testament;
but the blood of the new covenant, and of the New Testament,
his blood is the life of the Lamb, Christ Jesus, the Son of God without blemish, spot,
sin, or guile; a Lamb prepared before the foundation of the world was:
so it is by the life, the blood of this spotless Lamb,
that all his people are sanctified and redeemed to God, and sprinkled and washed,
their hearts, consciences, tabernacles, vessels and altar in the tabernacle,
and the fat or grossness consumed by his fire on the altar,
by which they come to be a royal priesthood,
offering up spiritual sacrifices to God through Jesus Christ.

So the blood of the new and everlasting covenant is the life of Christ,
which all the believers in the light are to walk in, and to be cleansed by,
giving all honour and glory to God, and the Lamb,
who hath redeemed us to God by his blood.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 7th of the 12th month, 1678.

And whereas,
many lies and false reports have been cast upon us by both priests and professors,
that we do slight, deny, and undervalue, the blood of Jesus,
who do value and esteem it more than any of them;
for how can they value or esteem the blood of Christ that plead for sin a term of life,
which makes for the popish doctrine of purgatory when they are dead, who are not washed,
and their garments made white, nor cleansed from all sin,
and redeemed to God by the blood of the Lamb,
from their vain conversations and the tradition of their forefathers,
neither have they so much faith in the blood of Christ the Lamb,
ordained before the foundation of the world, that it will so wash them, and cleanse them,
and redeem them, or make them as clean as their father Adam,
and mother Eve was before they fell,
and that they might come to sit together in heavenly
places in Christ Jesus that never fell.

And it may be seen, it was the life of the clean beasts from Abel`'s time,
that was offered and accepted of by God to cleanse withal, and therefore,
they were not to eat the blood, for the blood,
the life of the beasts was offered to God for an atonement upon his altar:
so it is clear it was the blood,
the life of the beasts which God required to make
atonement with upon his altar for their souls:
for the Lord saith,
'`the life of all flesh is the blood,`' and whosoever did eat it was to be cut off;
for the life of all flesh, the blood,
was to be offered upon his altar to make atonement for their soul, as the Lord required.

Thus the first covenant was dedicated with the blood, which was the life of all flesh:
but the new and second covenant is dedicated with the blood, the life of Christ Jesus,
which is the alone atonement unto God, by which all his people are washed, sanctified,
cleansed, and redeemed to God;
so that their faith and testimony stands in the blood of the Lamb,
the life of Christ Jesus, foreordained before the world was, a Lamb without blemish,
guile, spot, or sin, which cleanses from all spots and sin,
and washes and makes clean the garments.
And Christ abolishes both the blood of beasts, and the altar,
and all the traditions in the law, and their offerings and sacrifices before the law,
by the offering up of himself once in the end of the world,
a Lamb ordained before the foundation of the world,
therefore must every one`'s faith and testimony stand in him and his blood.
And who are the true witnesses of this,
but they only that have drunk of the blood of Christ, and eaten of his flesh,
which he gives for the life of the world, not such as talk of it only?

'`In the beginning was the word, and the word was with God, and the word was God;
the same was in the beginning with God; all things were made by him,
and without him was not any thing made that was made;
and the word was made flesh and dwelt amongst us,
and we beheld his glory as the glory of the only
begotten of the Father.`' And Christ said,
'`I have glorified thee on earth, I have finished thy work which thou gavest me to do:
and now, O Father, glorify thou me with thy own self,
with the glory which I had with thee before the world was,
for thou lovedst me before the foundation of the world.`' John xvii.
So Christ, a Lamb, without spot or blemish,
who redeems us from our vain conversations and traditions of our forefathers, the Jews,
'`who verily was ordained before the foundation of the world,
but was manifested in these last times,`' etc. 1 Pet. 1:19-20.
'`who hath put an end to all the Jews`'
offerings and sacrifices,`' as the apostle saith;
for in the end of the world he hath appeared, (to wit,
Christ,) to put away sin with the sacrifice of himself.
For if the blood of bulls and goats, which is their life,
and the ashes of a heifer sprinkling the unclean,
sanctifieth to the purifying of the flesh in the old covenant,
how much more shall the blood of Christ, his life,
who hath through the eternal spirit offered himself without spot to God,
'`purge your consciences from dead works, to serve the living God;`' so for this cause,
he is the Mediator of the New Testament, which is dedicated with his blood, his life:
'`so Jesus Christ was surely of a better testament
than that of the Jews.`' Heb. 7:22.
'`For he, by the grace of God, tasted death for every man.`' Heb. 2.
and lighteth every man that cometh into the world; and saith,
'`I am the light of the world, and he that follows me shall not abide in darkness,
but shall have the light of life.`' And the apostle told the Ephesians,
that he was '`to make all men see what is the fellowship of the mystery,
which since the beginning of the world hath been hid in God,
who created all things by Jesus Christ.`' Ephes. 3.
'`And he that hath the Son of God, hath life, and he that hath not the Son of God,
hath not life.`'

Here it is clear Christ is the first and the last, the beginning and ending,
and over all in the glory that he had with the Father before the world began; therefore,
let your faith stand in Christ, and his blood, his life, by which ye are washed,
sanctified, purged, cleansed and redeemed to God, that God, through Christ your Mediator,
may have the glory in all your hearts.

The blood of the clean beasts, which was the life of the beasts,
with it did the high priest enter once a year into the holy place made with hands,
to make an atonement for himself and the people of the Jews in the old covenant;
but Christ, our high priest entered into heaven by his own blood, his own life,
to make an atonement for us; he tasted death for every man,
and was a propitiation for the sins of the whole world, who was dead, and is alive again,
and lives forevermore; so he ever liveth to make intercession for his people,
and so his people have boldness to enter into the holiest, to wit, into heaven,
by the blood, the life of Jesus, by a new and living way,
which is consecrated for us through the veil, that is to say, his flesh;
glory to God forever, through Jesus the Saviour, and Christ the anointed of God.

[.signed-section-signature]
G+++.+++ F.
