[#ch19.style-blurb, short="Christians in Name, Without the Nature of it"]
== A Demonstration to the Christians in Name, Without the Nature of it.

[.heading-continuation-blurb]
How they hinder the Conversion of the Jews.
With an exhortation to them to come into the true Nature and Life of Christianity,
which the Apostles and Primitive Christians were in, who converted many of the Jews.

[.heading-continuation-blurb]
Which Nature and Life of Christianity is herein declared of according to the Scriptures,
and by which alone the Jews may now be convinced and converted also.--By G. F.

The usual saying of the Jews is, '`when the Messiah is come,
he will make all things new,`' according to Isa. 43.
which also is testified unto in 2 Cor. 5:17. and Rev. 21:5.

But the Jews say, '`most of Christendom (so called,) are in the old things,
like the heathens, as their life and practice doth demonstrate, whose conversations,
many of them, are like unto Sodom and Egypt.`'

And therefore they say, '`how do the christians think we should turn to them,
whose conversations, many of them, are in cursing, swearing, drunkenness,
and uncleanness, which the law of Moses forbids, and the prophets; by which law of God,
we Jews are not to swear by the creatures, but by the Lord;
though many of our forefathers did swear by the temple and other things,
yet it was when they were degenerated from the law of God,
and then some of them swore by Baal, and other heathenish gods,
all which was forbidden by the law of God and his prophets: and therefore,
seeing many of them that call themselves christians, swear wickedly, and vainly,
and by creatures, and books, the Old and New Testament, which the law of God forbids;
and therefore, as our prophets say, when the Messiah is come,
he will make all things new in the new covenant, which is not according to the old:
and if, therefore, we now should turn to you christians,
we should turn again but into the practice of those old things which our law forbids;
for the new covenant, which God promised to make, doth exceed the old: and therefore,
if we should turn to you christians,
and practise those things which the heathens do below the old covenant,
we should bring ourselves under the judgment of the law of God and the prophets,
and beneath what was commanded in our law.`'

And therefore, all christians are to lay away all swearing and oaths,
as Christ commanded, and cursing, drunkenness, fornication and uncleanness:
for all christians`' conversations should preach, as well as their tongues, a new life,
and a new heart in the new covenant.

For, Christ said, '`except your righteousness (to wit, the christians,
in the new covenant,) doth exceed the righteousness of the
scribes and pharisees;`' (in the old covenant,) Christ,
the Messiah saith, '`ye shall in no wise enter the kingdom of God.`'

But, if the christians`' unrighteousness and ungodliness, their swearing, cursing,
whoring, and profaneness, etc. loth exceed the transgressing Jews,
and many of the heathens, how can they then think to enter into the kingdom of God,
seeing if they do enter into the kingdom of God their righteousness
must exceed the righteousness of the scribes and pharisees,
the Jews in the old covenant.

And therefore, this is a great stumbling to the Jews, which profess the old covenant,
and hold that the Messiah is not come,
because they seeing the bad lives and conversations of the christians,
who profess the Messiah is come,
and that they are children of the new covenant and
yet live in the old nature and old things,
like the heathen, as they manifest in their lives and conversations,
below the Jews law in the old covenant.

For they should show forth a new life, and a new spirit, according as God hath promised,
and as the Jews believe, that when the Messiah is come, he would make all things new,
as in Jer. 31. and Ezek. 11:19.
It is said, '`I will give them one heart,
and I will put a new spirit within them, and take away the stony heart.`'

But do not we see this stony heart, and old spirit, in most of them called christians?

'`And therefore, if the Messiah be come, as you profess,
you are in the transgression of the new covenant,
as our forefathers were of the old covenant;
and you cannot find fault with us,`' say the Jews.

And in Ezek. 18:31. they were commanded '`to cast away their transgressions,
that they might have a new heart and a new spirit; for why will you die, saith the Lord?
For I have no pleasure, saith he, in the death of him that dieth.`'

And therefore, if the Jews remain in this old transgressing heart and spirit,
in the death, from Christ the life, in which God hath no pleasure;
should not the christians, which profess the new covenant,
cast away their transgressions, swearing, whoring, lying, and drunkenness, theft, murder,
and all uncleanness; that they might put off the old man with his deeds,
and put on the new man, and so have a new heart and spirit, and a new life,
serving God in the new and living way,
manifesting that they are children of the new covenant, and not of the old,
and so shew forth the fruits of the Messiah`'s being come,
and of their being in the new covenant in their lives and conversations:
for the apostle said,
'`their conversation was in heaven.`' And now let
Christendom see where their conversation is now,
and hath been these many hundred years.

And also, in Ezek. 36.
he there speaks of the blessings of the kingdom of Christ, by way of prophecy,
where the Lord saith, '`he will make in them a new heart,
and put his spirit within his people, and give them a heart of flesh,
and sprinkle clean water upon them, that they may be cleansed from their filthiness,
and from their idols, and take away the stony heart,`' etc.

And now let all which profess christianity consider;
how do they think to convert the Jews with their stony heart,
from one stony heart to another, and from one old spirit to another old spirit?
Nay, if they he converted, it must be from the old to the new,
from the old covenant to the new and living way.

And do you think the Jews can be converted to images, and idols?
They will tell you, '`the law of God throughout the Old Testament forbids them,
and their prophets, and their forefathers;
making and worshipping images brought all those dreadful judgments upon them,
and upon all their forefathers,
because they went a whoring after images.`' And now to see what
multitudes of images and idols are set up amongst christians,
that profess the new covenant, and that the Messiah is come,
who will make all things new.

And the owners and receivers of this new covenant,
their righteousness was to exceed the righteousness of the professors of the old covenant;
and yet to see so many of those called christians to make molten images, and idols,
which is below the law of Moses, and forbidden: therefore, do the Jews say,
'`how do you think we should be converted unto you.`'

Wherefore, it is good for all who profess christianity, to lay away all images and idols,
and making of them, or bowing before them, and mind the image of God,
which Christ in his new covenant renews his people up into,
that you may show forth the effects of the new heart and new spirit,
being wrought in you; and that you do abhor images and idols,
showing forth that you are cleansed from them,
and that your hearts are sprinkled with the pure water by the word;
and that you are not grievers nor quenchers of the pure spirit of God,
nor rebellers against this new spirit, nor haters of the light,
which Christ doth enlighten you and every one that cometh into the world withal;
for if you do, and quench this spirit, would you have people to be converted to darkness,
and the old spirit, and stony heart, that thus grieves the new: and therefore,
as the apostle saith, '`forsake the evil,
and cleave to the good,`' all you who are called christians.

And that all who profess themselves christians may
come to wear the badge or livery of Christ,
the heavenly man, and to have your old filthy garments put off,
and to be clothed with the new garment, the righteousness of Christ:
for all are clothed with the filthy garments, that are covered with the old spirit,
whilst they are in transgression of the new covenant of light and life.

And they that seek to convert, or bring people to them,
whilst they are in that old spirit, and old heart,
and to be covered with that old filthy garment, they bring them but into woe,
where themselves are: for the prophet Isaiah saith, '`woe unto them that are covered,
but not with my spirit, saith the Lord.`'

And they that are the true converts to Christ and God, they have the new spirit,
new heart, and new mind, and walk in the new way, in the new and everlasting covenant,
and their garments are made white with the blood of the life of the spotless Lamb,
ordained before the foundation of the world.
And these are the children of the new covenant,
and do shew forth in their lives and conversations the fruits of the new covenant.

And Jeremiah speaks of the new covenant after this wise,
'`behold this is the new covenant that I will make with
the house of Israel after those days,`' etc. and therefore,
he saith, '`behold the day is come,
that I will make a new covenant;`' and so bids them behold,
or take notice of his prophecy.
So this was after the days of the old covenant had done its service;
for the law served till Christ the seed came.
And so when this new covenant came, the old was to be abolished, which did wax old,
and was to decay and vanish away; so Christ came with his new covenant,
to take away the first, that he might establish the second covenant.

And now in the new covenant the Lord saith, '`I will put my law in your inward parts,
and I will write them in your hearts; I will be your God, and ye shall be my people:
and they shall not need to teach every man his neighbour, and brother, to say,
know the Lord; for they shall all know me, from the least to the greatest of them,
saith the Lord; for I will be merciful to their iniquity,
etc. and I will remember their sins no more.`'

And now, consider this, all ye that profess yourselves christians, how the Jews will say,
'`they do not see these fruits amongst you called christians,
who profess the new covenant to be come,
because your lives do not show forth this new spiritual law,
written in your hearts and inward parts; but like people running into sin and iniquity,
and drinking it up as the ox drinketh up the water,`'
which the Jews`' forefathers were reproved for.
And many teachers and professors plead for sin and a body of death to the grave,
which is contrary to the law of God; for the old covenant commanded people to be holy:
and the Lord commanded father Abraham, saying, '`walk before me, and be thou perfect.`'

And therefore, how can you think to convert the Jews,
that plead for a body of sin and death, that profess the new covenant,
that takes away sin and iniquity?

And as for the papists; the Jews say, '`they tell them, they must have a purgatory,
when they are dead, to cleanse them in;
and set up nunneries and monasteries for men and women, that vow chastity, to live in:
and this (the Jews will tell them,) they have no precedent for,
in their old covenant or law.`' And they are not in the
practice of them that gave forth the new covenant;
they neither preached, nor left upon record,
any thing of a purgatory for people to be cleansed in after they are dead:
for the blood of the old covenant, that was the life of clean beasts and creatures,
did cleanse in the time of the law: but Christ, who makes all things new,
in his new covenant, a Lamb ordained before the corruptible world was,
or man was corrupted; he with his blood (his life,) cleanses from all sin,
and makes an end of sin, and finishes transgression,
and brings in everlasting righteousness, according to Daniel`'s prophecy, who said,
'`this is the work of the Messiah.`'

And now, the Jews not seeing this new work,
and new life and conversation amongst those who profess Christ and the new covenant,
instead of converting them,
it rather hardens than softens them to their conversion to Christ,
by the ungodly and unrighteous lives of the christians, who on the contrary,
should exceed them in godliness, righteousness, and holiness, and in virtue, temperance,
and soberness, and purity in life and conversation;
and that would be the way to win them, and convert the Jews,
and make them believe the Messiah is come, and hath made all things new.
For to see the fruits of the new covenant, from a new heart and a new spirit,
and you walking in the new and living way,
where God and Christ hath pleasure in them that so walk and live;
this would preach to the Jews: and if they could not be won by the preaching of the word,
yet they might, by seeing the good and new life; for the apostle said,
'`follow us as we follow Christ;`' and every one that receives Christ, is to walk in him,
who was without sin and guile.

And the Jews say, '`in our old covenant we had our law in tables of stone, and in books;
but in the new covenant, in the days of the Messiah, God writes his law in their hearts,
and puts it in their inward parts; and shall no more teach every man his neighbour,
and every man his brother, saying, know the Lord: for all shall know him,
from the least unto the greatest,`' etc.

And now, the Jews may tell the christians, '`if you were in this new covenant,
then why do you set up so many schools and colleges to make priests in,
and to learn so many languages, and then to give them such titles, as bachelors,
and masters of arts, and doctors of divinity?
and then you say, when they have learned Latin, Greek, and Hebrew,
they have the original; which was not so accounted amongst us Jews in the old covenant;
for Moses told us, the many languages began at Babel; and therefore,
we cannot set up Latin and Greek to be the original:
for Moses gives a relation from the beginning of things of the old world,
all along to Noah`'s time, and to the time of the law,
and he no where speaks that the tongues are the original; for if that were so,
then they had no original before Babel.`'

And as for Hebrew, the Jews say, it was their natural mother speech:
and yet many of the Jews, that could speak natural Hebrew, Christ told them,
'`they neither knew the scripture nor the power of God; for they persecuted him,
and the prophets, and apostles.`'

And then these, your priests, when they have served a time at the schools,
and learned their natural languages and arts,
are they not called ministers of the new covenant?
But do they show forth the effects of the new spirit, and the new heart,
and the fruits of the new and living way, and new covenant?
If not, how are they like to convert the Jews, for the apostle saith,
in the new covenant, '`who is a wise man endued with knowledge amongst you,
let him show out of a good conversation his works with meekness,
and of wisdom from above, which is pure, gentle, and easy to be entreated,
full of mercy and good fruits, without partiality and hypocrisy;
and the fruits of righteousness is sown in peace of them that make peace.`'

And the Jews may tell you, that the Romans who understood Latin and Greek,
persecuted them; and they never looked upon their natural tongue to be the original.

But concerning your priests, when they have learned their lessons, and their arts,
and natural languages, are they not all sworn?
Is not this contrary to the Jews in the old covenant?
For the apostle said,
'`the priests in the old time were not made by an oath,`'
as Heb. 7:21. But Christ was made by an oath,
who fulfils, finishes, and abolishes all oaths and swearing,
and commands '`not to swear at all,`' which is his doctrine in the new covenant,
and the practice of the new heart and new spirit, in the new covenant,
and new and living way; as you may see James walked in it, and said, '`above all things,
my brethren, swear not, etc. lest ye fall into condemnation:`' and Christ saith,
'`whatsoever is more than yea, yea, nay, nay,
cometh of evil.`' So they go into evil and condemnation that swear in the new covenant,
according to the doctrine of Christ and the apostle James,
though swearing was not forbidden in the old covenant, but commanded:
but the new covenant is not according to the old, and therefore,
forbidden in the new covenant of light, life, and grace,
in the days of the gospel of glad tidings.

And are not the priests, after they have learned their lessons, and the natural tongues,
and arts at schools, hired to preach?

And may not the Jews tell you,
that was the transgression of their forefathers in the old covenant,
that the priests preached for hire, and the prophets divined for money.
And this was reproved by the prophet of God in the old covenant.
And through the covetous priests, prophets, and teachers,
the Jews were brought into misery, as the true prophets testified of and against such.
For by the law of God, the Jews may tell you,
the Levites and priests were to have no lot of the land, and therefore,
they had the tenths given unto them for their inheritance,
and for the maintenance of the widows and fatherless, and that was their portion:
so out of tithes they had their maintenance;
and they were to carry in their tithes to one place, which the Lord did choose, (to wit,
Jerusalem.)

Now, you priests, that profess the new covenant, that have learned your lessons,
and natural tongues and arts, that take tithes, and have your several tithe-barns,
and are hired to preach, and many of you have estates of land besides,
and yet do not maintain the poor widows and fatherless; may not the Jews tell you,
that ye are not like to convert them whilst you are
found below the practice of their priests,
under the old covenant,
which were forbidden by the law of God to have any lot or portion in the land,
and were not to have all the tithes themselves neither,
but the widows and fatherless were to be maintained out of them also?
And therefore, how do you christians, that profess the new covenant,
think to convert the Jews, whilst ye practice things below the old covenant?
But they that do profess the new covenant, they have a new spirit and a new heart,
and a new and living way, not according to the old.
So as Christ said, when he sent forth his disciples to preach,
'`freely you have received, freely give:`' nay, they were not to carry bag, staff,
or scrip with them.
So the new covenant is not according to the old; for he changed the first priesthood,
and ended the commandment that gave tithes.

And though the Jews had schools in the time of the law and old covenant;
yet in the new covenant, Christ who ascended up on high,
gives gifts unto men for the work of the ministry.
So all true ministers, and gifted men,
have them from Christ (that is ascended on high,) in the new covenant,
and preach them forth freely, as they have received them freely, as he commands them,
which freely gives unto them, to all his disciples, and learners,
and followers of him in the new covenant.

And therefore, all that profess themselves christians,
should take up the cross of Christ, and deny themselves in all things,
whether it be in the practices of the heathen,
or in the things abolished in the old covenant by Christ, and follow him.

But I would not have any to think, that I deny,
or am against schools for the teaching of children the natural tongues and arts,
whereby they may do natural things; for all natural tongues and languages upon the earth,
make no more than natural men; and the natural man knows not the things of God.
And therefore, all must come to the spiritual school of Christ,
if they will learn or know the spiritual things of Christ;
and so of him freely to receive them, and freely to give them forth,
if his learners will keep under his command.

And the Jews may say, the christians have many altars and candlesticks,
and some of them have wax candles burning in them all day and night in their temples;
for which they have no command from God.
And this is contrary to our law of God in the old covenant; for they say,
'`thus did our forefathers, when they forsook the Lord,
they built many temples and altars,
but the Lord appointed them one altar to offer their sacrifices on,
and one temple.`' Joshua 22:16. to the end.
And they may confess, when the Messiah is come, all those outward things will be ended,
according to the prophets, that God will make a new covenant, not according to the old,
and that God will raise up a prophet like Moses, whom they must hear.

And now you that profess christianity,
through your degeneration from that spirit and power the apostles were in,
you have rather put the Jews back from coming to christianity,
than helped them forward by your lives and practices.
For in the days of the new covenant, Christ, the high priest,
enlightens the candle which is the spirit in man, in his temple, his body;
if you do not put it out by your evil works, and wicked ungodly lives and conversations:
for in the old covenant,
it was Aaron and his sons which were to light the
outward lamp or candle in the outward tabernacle.

And do ye think, that ye can convert the Jews from their outward tithes, temple,
lamps and candles, to your outward lamps and candles;
who were forbidden from making images, to your outward images and idols;
and their swearing by the Lord, to your swearing by the creatures?
Who hardly speak without swearing in all your communications.
And do you think to convert them from their observing of days,
which God did command them, to your observing of saints`' days?
And is not this to bring them out of one outward form into another?
And had you not better have observed the life of Christ, and spirit of Christ,
and all the lives of his saints, and their conversations, how they lived,
and how they walked?
For it is not the talking as they talk, that makes you converts,
nor to bring others to talk as you talk, that will make them converts;
but as every one hath received Christ, in his new covenant, in their new mind or heart,
with their new spirit, they are to walk in him, the new and living way,
which the old heart and old spirit, in the old covenant and old nature,
cannot endure to hear talk of the new, and then they had better never profess it;
for that makes others, Jews, and heathens, to blaspheme Christ that you do profess,
seeing you do not possess him whom you do profess; but possess the old spirit,
and the old stony heart, that is in the Jews and heathens.
And so if you be not in the new spirit, and new heart, and new and living way,
in the new covenant, you will but bring people, Jews, or others,
from one stony heart to another, and from one old way to another:
and if they will not conform to your old way,
then your old stony heart will be ready to stone them to death,
as the Jews in their old stony heart were to stone Christ and his followers.

For they that would convert either Jews or Gentiles, must be in the new covenant,
not in the old, and have the new heart and new spirit,
and be in the new and living way themselves, else they cannot bring others unto it:
it is true, they may bring into the words of the new covenant, as the Jews,
who compassed sea and land to make proselytes, did,
and brought them to say the words of the old covenant; but Christ told them,
'`they made them but two-fold more the children of hell than before.`'

And therefore, all Christendom, and them that do profess christianity,
must examine themselves, and see whether they have this new heart and spirit,
and that they are in the new and living way, in the new covenant,
as the apostles and church, in the apostles`' days were in.

For false apostles, Satan`'s ministers and messengers, and the whore,
the false church and Jezabel, deceivers and false prophets, wolves in sheep`'s clothing,
and the dogs, the apostles bade beware of, and such as had the form of godliness,
but denied the power; all these may get the words of the new covenant.

And are such like to convert the Jews, or rather worry the lambs,
who manifest an old spirit, and an old heart, and walk in the old ways,
below the old covenant and new?
And such may beat people into the form of the words of the new covenant,
and so make them two-fold more the children of hell than they were before, like the Jews.

And therefore, that which must convert people to God and Christ,
whether Jews or Gentiles, it must be the same life, power, spirit, light,
and grace that converted the apostles and primitive christians in their days,
which brought them to a new life of righteousness and holiness, yea,
and brought them to have their conversation in heaven, as the apostle said;
so this conversation is above the old, earthly, sensual wisdom, and devilish and unclean,
corrupt and profane cursing and swearing, whoredom, murder, and theft,
which is the fruit of the old spirit, and the old stony heart, and image-makers,
and swearers, and is above tithe-paying, and the outward temple.

And the apostle saith plainly,
'`they that act such things cannot enter into the kingdom of God.`'

Therefore, they that are converted into the new covenant of grace, light, and life,
over darkness and death, and the power of it, have a new spirit and a new heart,
and walk in the new and living way, in the new covenant;
and such do spew forth the fruits of their conversation in the word, life,
and conversation.

And again, the apostles saith to the christians in his time,
that were getting up into a form of godliness, and a profession of Christ in words,
he bid them '`examine themselves whether they were in the faith.`'

So, all that profess themselves christians, should examine themselves now,
whether they be in the faith that Christ Jesus was the author and finisher of,
that one faith that purifies their hearts, and gives them victory,
by which they have access to God, in which faith they please God:
for it is not a professing the words of the new covenant, with the old heart and spirit,
or serving God with their lips, that makes a true christian; for Christ saith,
'`it is not every one that saith, Lord, Lord, shall enter into the kingdom of God:
but he that doth his will,`' etc.
And the apostle saith plainly to the church, '`he that hath not the spirit of Christ,
is none of his;`' and then they are none of his sheep;
for they are not like to hear his voice without his spirit.

And therefore, all that profess themselves christians are to examine themselves,
whether they have this spirit of Christ, and if not, they are none of Christ`'s;
and what then is your profession worth, without the possession of this spirit?
For you can neither serve nor worship God aright, nor know the scripture,
without the spirit of Christ.
And therefore, all your services are good for nothing,
that be without the spirit of Christ;
for God abhorred such that served him with their lips in the old covenant,
(that could make a profession,) when their hearts were far from him.

[.numbered-group]
====

[.numbered]
_First,_ And therefore all that profess themselves christians must examine themselves,
whether they be in that one faith that the apostles speaks of,
which Jesus Christ is the author and finisher of; and if they be not in this faith,
but are erred from it, they have no victory nor access to God,
neither can they please God.
For this was the examination the apostle put the christians upon in his days;
and this is the examination that all christians should be put upon now in these days;
for that is and was the catholic, universal, divine, precious, and holy faith,
which all that profess christianity, are to examine themselves,
whether they be in that or no.
And the apostle did not put them to examine themselves, whether they profess it or no,
but whether they were in it.

[.numbered]
And _secondly,_ They are to examine and prove themselves,
whether they have the spirit of Christ, yea or nay, all that do profess Christ:
for if they have not the spirit of Christ (the apostle saith in plain
words,) '`they are none of Christ`'s.`' So the apostle doth not say,
examine yourselves, whether you do profess Christ; but '`examine and prove yourselves,
whether ye have the spirit of Christ, yea or nay.`' For antichrist, and false prophets,
and false apostles, and wolves in sheep`'s clothing, may profess Christ,
that are not of Christ`'s flock, nor his sheep.
Therefore, the main thing is, to examine '`whether ye have the spirit of Christ;
and if ye have the spirit of Christ, then ye are his;
and if ye have not the spirit of Christ,
then ye are none of his;`' though you may profess all Christ`'s
and the apostles`' words in all the languages,
Hebrew, Greek or Latin, your profession with and in your own spirits,
is good for nothing, if you have not the spirit of Christ Jesus;
'`for such are none of Christ`'s followers, that are without his spirit,
who follow their own spirit, and see nothing, as the prophet saith.
And all they that are baptized by one spirit into one body,
and are made to drink into one spirit,
in which spirit they have unity and fellowship:`' these all have the spirit of Christ.

[.numbered]
And _thirdly,_ the apostle tells the christians in his day, '`no man can call Jesus Lord,
but by the Holy Ghost.`' Now, let all that call themselves christians examine themselves,
whether they have this same Holy Ghost that the apostles had,
which proceeded from the Father and the Son,
and that have received this from the Father and the Son,
which led the holy men of God to give and speak forth the holy scriptures,
as they were moved by the Holy Ghost; which Holy Ghost leads into all truth, yea,
even the same Holy Ghost that moved all the holy men of God to give forth the scriptures,
by which Holy Ghost the holy men of God foresaw the coming of Christ,
and prophesied of him; and by which Holy Ghost the apostle saw Christ was come,
and fulfilled the prophets,
by which Holy Ghost they called him Lord in truth and righteousness.
And now, if no man can call Jesus Lord, but by the Holy Ghost, as the apostle teaches,
and positively declares; then all you who call yourselves christians,
calling Jesus Lord without this Holy Ghost, as the apostles were in,
and many of your teachers, both papists and protestants, say,
'`you have not the same Holy Ghost the apostles had;`' then it
is impossible for you with the unclean Holy Ghost to call him Lord.
And all such callers of him Lord, Lord, with their unclean ghost,
and not in the Holy Ghost, will be found workers of iniquity,
and not to be able to enter into the kingdom of God; for unto such Christ will say,
'`depart, I know you not.`' And therefore, let all christians examine themselves,
whether they have this same Holy Ghost, seeing none can call him Lord,
but by the Holy Ghost; and none can be led into all truth, but by the Holy Ghost;
but are led into all untruth by their unclean ghost,
though they may make a profession of the scriptures from Genesis to the Revelations;
and that profession with the lips, is not accepted with the Lord,
no more than it was among the backsliding Jews, without the Holy Ghost,
which leads into all truth, by which they may call Jesus Lord, who fulfils all the types,
and shadows, and figures, and the law, and the old covenant.

[.numbered]
And _fourthly,_ the apostle said to the christians in his days,
examine and prove your own selves; know you not your own selves,
bow that Jesus Christ is in you, except you be reprobates?
Now this was the duty then of all that profess themselves christians,
to examine and prove themselves.
And this is the duty of all that profess themselves christians now,
to examine and prove themselves, whether Jesus Christ be in them and if not,
they are reprobates, according to the apostles`' doctrine.

====

And now for christians and their teachers to say,
'`they own the birth of Christ,`' and go about to prove
the birth of Christ without them by the scriptures,
and his sufferings, and his resurrection, etc. and to say,
'`they will prove this by the scriptures;`' this
is already proved by such in whom Christ was revealed;
and it was preached by them, and since printed: for the apostle said,
'`it hath pleased the Father to reveal his Son in me,
that I might preach him.`' And again he said, I live, yet not I,
but Christ that lives in me: for the apostle saw then, that wolves, false apostles,
Satan`'s messengers, false prophets, and false teachers, might get the form of godliness,
and the profession of Christ Jesus in words, in their days; and so much more such may,
since the apostle`'s days: and therefore,
he would have the true christians then to examine and prove, and know their own selves,
'`whether Jesus Christ was in them, or not; for if not,
they were reprobates.`' And so it is requisite for all that
call themselves christians now to come to this proof,
and examination, and knowledge, '`whether Jesus Christ be in them, or not;
and if not they are reprobates:`' seeing wolves, false apostles, false prophets,
and such as go in Cain`'s, Cora`'s and Balaam`'s way, and Satan`'s messengers,
and reprobates may profess Christ.

Therefore, what is their and the reprobates profession with the lips good for,
though they may profess the scriptures from Genesis to the Revelations,
and may talk of the apostles`' preaching of him, the new covenant?
So as long as Christ the Son of God is known not in them, they have not life.

Therefore,
this is the examination and proof that all that call
themselves christians should come to,
'`whether Christ, which they profess in words, be in them, yea or nay; and if not,
they are reprobates.`' And then their profession of the
words of the new covenant is no more accepted with the Lord,
than the Jews was in the old covenant, that served God with their lips,
who were reprobated from the old covenant, as those christians are from the new,
that know not Christ in them.
Therefore,
let all that profess themselves christians examine themselves of all these things afore-mentioned.

[.numbered-group]
====

[.numbered]
_First,_ Whether they be in that one catholic, holy, divine, and precious faith,
which Jesus Christ is the author of, and that they be not erred from that?
For if they be not, they need not make new faiths.

[.numbered]
_Secondly,_ Whether they have the spirit of Christ?
and if not, they are none of Christ`'s.

[.numbered]
_Thirdly,_ If they have not the Holy Ghost, they cannot call Jesus Lord,
seeing the apostle saith, '`no man can call Jesus Lord,
but by the Holy Ghost;`' neither can they call Jesus Lord, nor be led into all truth,
if they have not the Holy Ghost; neither have they the comfort of the Holy Ghost,
neither can they pray in the Holy Ghost, as the apostles did: and therefore,
how can all your prayers, worships, and services be accepted,
if you have not this Holy Ghost, and have not this spirit,
seeing without it ye cannot call him Lord, and are none of his?

[.numbered]
_Fourthly,_ Examine yourselves, and prove yourselves; and know you not,
that if Jesus Christ be not in you, you are reprobates?
And then do you think that God and Christ will accept the reprobates religion, worship,
and prayers, that have not this spirit, and this Holy Ghost,
and are erred from the true faith, and in whom Christ is not?

[.numbered]
_Fifthly,_ Examine yourselves, whether you be of the circumcision in spirit,
that serve and worship God in his spirit and truth,
and are not of the circumcision of the letter, but of the circumcision of the spirit,
by which the body of death and the sins of the flesh are put off,
that are come upon nun and woman by transgression.
For Adam and Eve had not this body of death and sin
before they transgressed the command of God.
For if ye be of this circumcision in the spirit, which all christians should be in,
and which the apostles were in,
then the body of death and the sins of the flesh
will be put off by the circumcision of the spirit;
and then there will be no pleading for a body of death and sin to the grave,
and a purgatory when they are dead; if they be of this circumcision in the spirit,
and worship and serve God in the spirit,
as the apostle and the true church in the primitive times did.

[.numbered]
_Sixthly,_ Examine yourselves, all that profess yourselves christians,
whether you do discern the Lord`'s body, and if not,
ye eat and drink damnation to yourselves.
So, let all that call themselves christians examine, from the teacher to the hearer,
whether they do discern the Lord`'s body; and they that do discern it,
may come to eat his flesh and drink his blood, which he gave for the life of the world,
which is not outward bread and wine;
neither can any make outward bread and wine his body.

And therefore, let all Christendom examine, whether they do discern the Lord`'s body;
for they must discern it before they can eat this heavenly bread, that gives them life.
John 6.

[.numbered]
_Seventhly,_ Let all that call themselves christians examine themselves,
whether they are come to the baptism of Christ, with fire and the Holy Ghost,
who thoroughly purges his floor, and burns up the chaff with unquenchable fire,
who baptizes with one spirit into one body,
and plunges down the corruptions that are gotten up by transgression.
So Christ is the minister of this baptism and circumcision,
who plunges down sin and the body of death, chaff and corruption,
and thoroughly purges the floor,
(the heart of man) and burns up the chaff with unquenchable fire.

====

So this is the one baptism, into one body, with one spirit,
by which all may come to drink into this one spirit, and not into the many.
And such as are come to this baptism of Christ,
cannot plead for a body of sin and death to the grave,
nor for a purgatory to purge them in after they are dead: for the baptism of Christ,
which he ministers, is sufficient to purge thoroughly the heart, mind, body,
and soul of every man and woman.
For many would reign with Christ, but few come to be baptized into his death,
and to drink of his cup, which they must do before they can come to reign with him.
For the apostle saith, '`they that are Christ`'s, have crucified the flesh,
with the affections and lusts thereof.`'

And therefore, let all that profess themselves christians examine,
whether they have crucified the flesh, and those affections and lusts thereof,
for the apostle tells the christians, '`God forbid that I should glory in any thing,
save in the cross of Christ, by whom the world is crucified unto me,
and I unto the world.`'

Then they that have not crucified the flesh, with the affections and lusts thereof,
are not Christ`'s: and therefore, let them consider, whose they are then,
with their flesh, and affections, and lusts, thereof, uncrucified. Gal. 5:24. 6:4.

And therefore, let every one prove himself, and his own work;
for if a man think himself to be something, when he is nothing, he deceives himself:
so it is not a profession of the prophets`', Christ`'s, and the apostles`' words,
and a profession of baptism, that serves the turn,
but they must have the same spirit of Christ which the apostles had,
if they be Christ`'s; and the same one faith that the apostles were in, if ye please God,
and would have access to him; and the same Holy Ghost that the apostles had,
if you call Jesus Lord; and Christ must be in you, if you be not reprobates:
and if you do serve God, and worship him, it must be in the spirit,
that puts off the body of death, and the sins of the flesh,
which is the circumcision of the spirit in the new covenant.

And therefore, know ye not all that profess yourselves christians,
that '`so many as are baptized into Christ Jesus,
are baptized into his death?`' And therefore, examine yourselves;
are ye baptized into the death of Christ, and buried with Christ by baptism into death?
And therefore, examine again, have you been buried with Christ by baptism unto death?
Now this is a farther thing than outward water,
that '`like as Christ was raised up from the dead by the glory of the Father,
even so we also should walk in newness of life.`'

And now, can any christians walk in newness of life,
until their old man and his life be buried by baptism into death?
For must not all Christendom be planted into the likeness of Christ`'s death,
if they be planted into the likeness of his resurrection?
Therefore, examine yourselves, where, and how you are planted:
for ye are not like to be planted with Christ in his resurrection,
except ye are planted into his death: therefore, examine yourselves,
that you may come into the virtue, and life of true christianity.
For the apostle said to the true christians, '`knowing this,
that our old man is crucified with Christ,`' etc.
And now all ye that profess yourselves christians, come, and search, and examine,
is your old man alive, and not crucified?
Then how can ye serve God and Christ in newness of life?
For your old man must be crucified, if the new man be renewed,
which is after the image of God, etc.
And can the old unmortified man be a true christian in his old life,
with his profession of the words of the prophets, Christ, and the apostles,
from Genesis to the Revelations?
nay, the apostle tells the christians,
'`he must be put off and crucified;`' so he is no good christian then:
for it is the new man that is the christian, that walks in newness of life,
and serves God in his new and living way, in his new covenant,
that hath the new heart and new spirit.

From him that loves the purity and virtue of all true christianity,
and all that receive Christ, and walk in him.

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
The 28th of the 2d month, 1679.
