== Election and Reprobation

[.heading-continuation-blurb]
Clearly Discovered,
and the ignorance of many concerning Election and Reprobation of persons,
Manifested.

[.heading-continuation-blurb]
Something for the information of all concerning Election and Reprobation;
and unto such as hold opinions and teach,
that God hath ordained a great part of men and women to Reprobation,
Condemnation, and Hell, without any cause or fault at all in the creature less or more;
for God hath ordained some to a Reprobation and Condemnation from the foundation of the world,
say they: and so hold a Reprobation of some persons to all eternity; and for it, bring Jude iv.
who speaks of such as were ordained of old to Condemnation, and saith,
there were certain men crept in unawares,
which were of old ordained to this Condemnation, ungodly men,
turning the grace of our God into lasciviousness, and denying the Lord God,
and our Lord Jesus Christ.--By G. F.

Now this scripture of Jude`'s doth prove,
that there was a fault and a cause in these men for this condemnation,
for they were ungodly men, that turned the grace of God into lasciviousness;
which grace of God hath appeared unto all men, to teach them,
and to bring their salvation.

Now, if this grace and favour of God did so appear unto these and all men, to teach them,
and bring their salvation;
and these ungodly men turned from this grace into lasciviousness,
and so denied the Lord Jesus Christ, that bought them, by whom this grace and truth came;
and to deny the only Lord God, the Creator of all,
and who gives life and breath unto all, and would have all men to be saved,
and to come to the knowledge of the truth, and desires not the death of a sinner,
neither hath he pleasure in him that dies, but rather that they would turn, and repent,
and live to God, who sent his Son to taste death for every man.

And they that thus deny God, and his Son, who hath bought them with his blood,
which was shed for all men; here must needs be a great fault,
and a cause wherefore God and Christ does judge and
condemn these ungodly men in truth and righteousness.

For you may see in the old translation, it is not said, Jude 1:4.
'`ordained of old to this condemnation;`' but it is said,
'`written of old to this condemnation:`' and writings
were since the creation of the world.

For the apostle saith, '`God saved the people of the Jews, that came out of Egypt;
and yet after destroyed them that did not believe, which murmured, complained,
and rebelled against God and his law, and grieved his good spirit,
which God had given to them to instruct them, and quenched it, and vexed it.`'

And these people, that God had so saved, and brought out of Egypt,
they were of Jacob`'s stock, which was of the election, not of the stock of Esau,
that was of the reprobation, as you call it; nor of the stock of Cain,
for all his stock was drowned in the old world, for grieving God`'s good spirit,
and corrupting the earth, and filling it with violence.

So here was a cause for the Lord God to judge and condemn these ungodly men,
both before the flood and after, in the time of the law,
to condemn such as grieved his spirit, and rebelled against it,
and did not believe in him, after he had saved them.

And so, likewise, in the New Testament, wherein Christ tasted death for every man,
and his grace hath appeared to all men, to teach them, and bring their salvation;
if such deny Christ that hath bought them, and the only God the Creator of them,
that sent his Son to save them, that they might have life through him;
and to enlighten every man that cometh into the world, which light was the life in him,
the word, by whom all things were made and created; and he saith, '`believe in the light,
that ye may come to be the children of the light.`'

Now, if people will not believe in the light, but hate it,
and turn from this grace of God into wantonness and lasciviousness,
and deny God and Christ, which have done all this for them,
and walk despitefully against the spirit of grace,
that would have brought their salvation:
is it not just with the Lord to judge such ungodly men,
and condemn them in their reprobation?
And so doth not this condemnation stand just upon the ungodly, and unbelievers,
and turners of his grace into lasciviousness, and walking despitefully against it,
and quenching, and vexing, and rebelling against the spirit of God,
both in the old covenant and the new, that deny God, and the Lord Jesus Christ.

So, is not God and Christ just in condemning and judging the world in righteousness,
according to his light, truth, grace, and spirit, that is poured out upon all flesh.
And the saints said, Rev. 14:2.
'`that God was just in judging the whore,`' that whored from it,
(as in the Revelations.)

So it is clear, the ordination, as you call it, to condemnation and judgment,
is upon man`'s disobedience and rebellion against God`'s good spirit,
and his unbelief in God and Christ.

For this condemnation comes not upon them that believe, and that obey the spirit of God,
either in the times of the law, or of the gospel, nor before the flood:
for the angels that kept not their first state, but left their habitation,
that brought the everlasting chain upon them, and condemnation.
So both Jews and christians, not keeping their habitations in the old and new covenant,
have come under the condemnation.
And Adam and Eve, keeping not their habitation,
brought condemnation upon themselves and all mankind:
even so by the righteousness of one, (to wit,
Christ,) the free gift of God came upon all men unto justification of life.

Now then, where is your condemnation and reprobation before the world began?
(seeing the first condemnation came upon man after Adam and Eve fell,
which was the first fault or cause,) so not without a fault or a cause in man.
For by disobedience, unbelief, and rebellion against God`'s good spirit and command,
and turning his grace into lasciviousness, and by denying the Lord God, that made them;
and the Lord Jesus Christ, who died for them, and bought them;
doth not this condemnation then come upon mankind under the new covenant,
as it did upon them written of old, in the old covenant?

And did not Sodom and Gomorrah,
by giving themselves over to lasciviousness and fornication,
and going after strange flesh, bring the just judgment and condemnation of God upon them,
whom God set forth for examples, to suffer the vengeance of eternal fire?

And so those ungodly men,
whom the apostle calls '`filthy dreamers,`' that did rise up in the gospel-times,
which went in Cain`'s way, and ran greedily after the error of Balaam for rewards;
and in the gainsaying, that it was Cora`'s way;
which were spots in the feasts of the christian`'s charity;
which went under the name of christians, that were the mockers,
and walked after their ungodly lusts, yet could speak high-swelling words,
having men`'s persons in admiration because of advantage.

So it seems they would be teachers,
though they were like unto the raging waves of the sea, and trees without fruit,
and wells without water, and were twice dead, and plucked up by the roots.
Now such as these did trouble the church in the apostles`' days,
and were a great grief unto them then,
(and to the true believers,) which he calls '`wandering stars, sensual,
having not the spirit.`'

Now, how should they have the spirit of God to be their guide,
when they were erred from it, and were turned to be mockers,
walking after their ungodly lusts, and not after the spirit?
But it is clear, that these once had the spirit; else, how could they err from it,
like Balaam?

And also, it is manifest, they could not be twice dead, except they were once alive:
but these were such as admired men`'s persons, and by that they got advantage;
for they ran greedily after rewards, like Balaam, in the apostles`' days,
as Balaam did in his days; and like Cora, who gainsaid the law in the old covenant;
so did these Coras and Balaams (called christians,)
who had troubled both the church and the apostles,
gainsaid the truth in the new covenant, who had been once dead, and were made alive,
and then were dead again, so could not grow,
written of old to condemnation in the new covenant, as well as in the old.

And then they were not like to have any water in their wells, nor fruit,
but as wandering stars, not fixed; and at last came to be like the raging, foaming sea,
casting up nothing but mire and dirt.
Yet these nominal christians would be sacrificers, like Cain,
and yet killers of such as were in Abel`'s faith in the field, which is the world,
where they admired men`'s persons because of advantage;
and here was the beginning and ground of admiring men`'s persons, because of advantage,
and here is the antiquity, and beginning, and rise of such as went in Cain`'s way,
Cora`'s and Balaam`'s way, amongst the christians, from Christ, the new and living way;
and yet would be preachers of the gospel, without the guidance of the spirit,
being erred from it, and dead men, and wandering stars, nay, twice dead,
and wells without water, and trees without fruit;
came to be preachers with their high-swelling words of vanity,
and admiring men`'s persons because of advantage, and yet fruitless trees:
and was not here fault and cause enough in these men for their condemnation and reprobation?
For Cain did hear the voice of God, and so did Balaam, and had the spirit of God,
and Cora was brought out of Egypt, and saved from Pharaoh, and came through the red sea.
For Cain was made alive, that heard the voice of God, and Balaam, and Cora,
and then they came to die again;
they must needs then be called fruitless trees twice dead, and wells without water,
and wandering stars, and to have erred from the spirit of God,
which would have fixed them.

Then Cain was wroth against Abel, the true sacrificer, and slew him.
And Balaam, when he erred from the spirit, and would fain have gotten Balak`'s reward,
to have cursed the children of Israel, but the Lord restrained him; and after,
Balaam taught Balak to lay stumbling-blocks before them.
And Cora gainsaid the law of God in the old covenant, though he had been saved,
and the Lord brought him out of Egypt.

Now these ungodly men, that went under the name of christians in the apostles`' days,
which went in Cain`'s, Cora`'s and Balaam`'s way, which have gainsaid the gospel,
and hated the light of Christ, and rebelled against the spirit,
and walked despitefully against the spirit of grace,
which the apostle said was for condemnation, which he saw creeping up,
and arising then in their day:
and was not here fault and cause enough in them for their condemnation?
Have not these been of the race of these men,
that have been teachers since the apostles`' days,
which he said then were for condemnation?
for, have they not gone in Cain`'s and Cora`'s way?
gainsaying the light of Christ,
with which he enlightens every man that cometh into the world,
and the gospel that is preached to every creature, and killed the true sacrificers,
that have been in Abel`'s faith:
and are not these the men that preach and hold a reprobation of persons,
and that God hath ordained the greatest part of mankind for hell and damnation?
But are they not found in the reprobation themselves,
and so under the condemnation written of old,
as by their fruits we may try and find them?

For do not you say, you have not the same power and Holy Ghost the apostles had?
and then are you not such as are sensual, not having the spirit,
and not in the spirit the apostles were in, as you have and do confess?
and then are you not the wells without water, trees without fruit, the wandering stars,
not fixed, and like the raging waves of the sea, casting up mire and dirt;
and caused all people that have followed you, to wander, and to he fruitless trees,
and wells without water, like yourselves?
And have you not hereby brought yourselves under the condemnation,
and into the reprobation, which the light and spirit the apostles were in,
gave judgment upon such then?

Secondly, Also, are you not gone into Cain`'s way, who once heard the voice of God,
and became vagabonds from the faith of Abel, and the voice of God; and now say,
there is no hearing the voice of God nowadays; as Cain, and the prophets,
and the apostles did?
and so are not you grown darker now, than old Cain,
who have killed and persecuted so many upon the account of sacrifice, religion, church,
and worship, that have been in the faith of Abel, since the apostles`' days?

And some of you may plead, that you have suffered for your sacrifice,
and have been killed or persecuted for your religion.
But that doth not demonstrate you to be in the true faith,
as long as you kill and persecute others for their faith and religion,
when you are uppermost; for that is not according to the true faith of Christ,
to make any to suffer death, or to persecute them for their religion, church, or worship,
that be contrary to them: for Christ rebuked such as would have men`'s lives destroyed,
that would not receive him, and said unto them,
'`they did not know what spirit they were of;`' and
'`he came not to destroy men`'s lives,
but to save them.`'

And the apostles said, '`their weapons were spiritual, and not carnal;
and they wrestled not with flesh and blood.`'

And Christ said unto them, '`let the tares and the wheat grow together till the harvest,
which was the end of the world,
and then he would send his angels to sever the wheat from the tares.`'

And so it is clear, those that have taken away men`'s lives,
and kill and persecute upon the account of religion, they have gone in Cain`'s way,
and not in the way of Christ nor the apostles;
and so are the men that were written of old for condemnation,
who have not kept their habitation in the faith, and spirit, and power of God,
that works by love, as the apostles were in; and therefore,
here is cause and fault enough in you for this condemnation written of old.

And likewise, such christians that go in Balaam`'s way,
which the apostles saw in those days rising up,
who have erred from the spirit that the apostles were in,
and yet may make a profession from the words of the New Testament and Old,
in their high-swelling words of vanity,
and yet run greedily after the error of Balaam for rewards,
and seek for hire for their prophesying or preaching, and do admire men`'s persons,
that they may get the most advantage by, and honour them with cap and knee,
and give them all other flattering titles;
and were not these them that were written of old for judgment and condemnation,
that were found in these practices?

For would not Balaam have destroyed the Jews, and cursed them,
but that the Lord restrained him?
and he shewed unto Balak the way how to destroy the Israelites,
as by the stumbling-blocks, he laid in their way, afterwards appeared.
And have not many of your prophets and teachers, that have gone in the way of Balaam,
destroyed many people upon the account of their rewards, hire, and maintenance,
and cast them into prisons till death,
for which they have neither law nor command from Christ nor his disciples,
and so are worse than your forefathers, Balaam and Simon Magus?

So have not many of them been worse than Balaam in such practices,
who have gone in the way of Balaam for their rewards, wages and hire,
and not in the way of Christ Jesus, who said, '`freely you have received, freely give?`'

Neither have they gone in the way of the apostles, '`who did not covet any man`'s silver,
gold nor apparel, but laboured with their hands for their own necessities,
that they might be examples to all that followed them,`' as in Acts 2. and 2 Thes. 3.

So, I say, have not all you covetous hirelings,
who are so greedy after your gifts and rewards,
and admire men`'s persons where you can get the most advantage: and go in Balaam`'s way,
and are erred from the spirit of Christ, which the apostles were in,
(I say,) are not you the men in the reprobation from Christ and the apostles,
and written of old for condemnation?
Have not your fruits declared it?
Who are found fruitless trees, and the wells without water,
and like the raging waves of the sea, casting up mire and dirt against the righteous;
and are the wandering stars,
who are wandered from that spirit and power the apostles were in;
and is here not cause and fault enough in you for your condemnation,
as it is written of old?

And how should ye be settled, or have any fruit on your trees, or water in your wells,
but be sensual, and so be in the reprobation, and under the condemnation,
not having the spirit of Christ and the apostles were in.

And also, have you not gone in the way of Cora, who gainsaid the law?
But these that were called christians, who went in Cora`'s way, gainsaid the gospel, yea,
gainsaid the spirit of Christ that was in the apostles.
But do not you gainsay that '`Christ died for all men,`' who tasted death for every man?
And do not you gainsay, '`that the grace of God, which hath appeared unto all men,
is sufficient to teach them, and to bring their salvation?`' And likewise,
do not you gainsay the light of Christ, which is the life in the word,
by which all things were made and created,
by which Christ lighteth every man that comes into the world; and '`believe in the light,
that ye may become the children of the light?`'

Now do not all such gainsay this light, and this grace of Christ,
which enlightens all men, and hath appeared unto all men;
and Christ who tasted death for every man; and the gospel,
preached to and in every creature that is under heaven?
And as Cora gainsaid Moses and the law of God in the old covenant, so have you,
(like Cora,) gainsaid Christ`'s light and grace, and spirit poured upon all men,
in the new covenant.

And then are you not in the reprobation from the doctrine of Christ and the apostles,
in the new covenant, and so written of old for condemnation,
though you may swell as high as Cora in your words of vanity,
and be clouds without water, carried about with the wind, and what you know,
you know but naturally, as brute beasts; and how should it be otherwise,
when you are erred from the spirit that the apostles were in?

And so, let the teachers in Christendom measure themselves and their fruits,
whether they have not gone in Cain`'s, Cora`'s, and Balaam`'s way,
in their killing about religion and worship, and for hire, gifts,
and rewards for their prophesying and preaching, and gainsaying the doctrine of Christ,
who said, '`freely you have received, freely give;`' and are preaching up reprobation,
and condemnation of persons: but let them see, if it be not their own conditions,
being found in the steps and spirit of them which the apostles said,
were written of old to condemnation,
who have not kept to that power and spirit the apostles and primitive christians were in;
so that which they have judged upon others,
let them see if they be not fallen under the same judgment themselves,
and cause and fault enough in them for it.
For you may see all along the marks, and steps, and fruits of them, which were ordained,
as you call it, to reprobation, was of such as were written of old for condemnation,
which is come upon mankind for disobeying the Lord, and not believing in him; yea,
and that from the beginning, and also in the law and gospel,
and grieving and vexing of his good spirit, and rebelling against it,
and hating the light of Christ, and erring from the faith,
and walking despitefully against the spirit of grace,
and disobeying the gospel of Christ, and denying the Lord their Creator,
and the Lord Jesus Christ, that hath bought them;
hath not this been the cause and fault of reprobation, judgment, and condemnation,
that hath come upon man and woman, both in the time of the law and gospel,
and since the fall?

[.blurb]
=== Now concerning your Doctrine.

'`That God hath ordained the greatest part of men and women for reprobation,
and condemnation, and for hell.`'

You that have preached this, are in the reprobation yourselves, and not in the election,
as hath been proved before; who are found in Cain`'s, Cora`'s, and Balaam`'s way,
written of old to condemnation.

For if God hath ordained the greatest part of mankind for hell,
according to your false doctrine, then how did God send his Son?
'`Who so loved the world, that he gave his only begotten Son into the world,
that whosoever believeth on him, should not perish,
but have everlasting life.`' And Christ lighteth every man that cometh into the world,
with his light, which is the life in himself, the word; and saith,
'`believe in the light;`' and saith, '`he that believes, is saved;
and shall not come into condemnation; and he that believes not, is condemned already.`'

So it is clear, for want of men`'s believing in the light,
the light is their condemnation; so they are all enlightened,
that they might all believe and be saved through Christ Jesus,
and then where is ordination for condemnation?
For is it not for not believing in the light (which is the life in Christ,
as Christ commands,) that they are condemned?
And Christ sends his disciples, and gives them power, and his Holy Ghost,
into all nations, to preach the gospel to every creature under heaven.

Now is not this glad tidings and joyful news of salvation to every creature under heaven,
this gospel of salvation?
Then where are those creatures or persons that are foreordained for condemnation,
as you talk of?
For is it not because they would not receive and believe the everlasting gospel of salvation,
the good news and glad tidings to every creature under heaven, that they perish?
They did not go and say, as you that are in the error, have said and talked,
and so go and tell the nations,
that God had foreordained the greatest part of them for hell and condemnation:
that is not the gospel of salvation the apostles preached to every creature; who said,
'`they that believe, are saved; and they that do not,
are condemned already.`' So it is clear, that it is unbelief that brings condemnation.

But the message of Christ and the gospel, that they have to preach,
was glad tidings and good news of salvation come to every creature under heaven,
by Christ Jesus, whose blood was shed, and he tasted death for every man,
that was dead in old Adam; so he tasted death for them all, and enlightens them all,
and his gospel is preached to them all, of light, life, and salvation;
and it is their condemnation that do not receive it, and believe in it.

And also the grace of God, which brings salvation, +++[+++mark, brings salvation,]
this grace and favour of God has appeared unto all men.
Now if God had foreordained such a number of persons (as
you say and preach,) for reprobation and condemnation,
how doth this grace and favour then appear to all men: and how can it then be said,
'`Christ tasted death for every man?`' For by the offence of Adam and Eve,
did not sin and condemnation enter into the world, and judgment come upon all men,
for that all had sinned?
And so by the righteousness of Christ the free gift
came upon all men to justification of life;
and then, where is foreordination of persons to condemnation,
seeing all were in condemnation?
For by the righteousness of Christ the free gift
came upon all men to justification of life.
And so, is not the condemnation and the judgment come, for not receiving Christ,
and believing in him?
And did not the first condemnation come upon Adam and Eve for not believing,
and disobeying God?

For if the grace and favor of God to all mankind hath appeared unto them,
which will bring their salvation;
this doth not shew that '`God hath foreordained men
to reprobation,`' but '`would have all to be saved,
and to come to the knowledge of the truth.`' And
then where comes in men`'s reprobation and condemnation,
but by turning from this grace of God into lasciviousness,
and walking despitefully against it?

So it is clear God`'s love is to all mankind, in his grace, and in his Son,
and in his gospel, and in the light of Christ, which is the life in him, the word;
and in the death of his Son, who tasted death for every man; and so,
that their reprobation and destruction is of themselves,
who hear not the voice of God and Christ, but grieve his spirit, and hate his light,
and walk despitefully against the spirit of grace, and deny God the Creator,
and the Lord Jesus Christ, by whom all things were created,
who tasted death for every man: such as do not believe in him, but deny him,
are in the reprobation, and worthy of condemnation,
and there is cause and fault enough in them for it.

So if you do say, '`that Cain was reprobated.`' I say,
his stock was drowned in the old world, and therefore tell us not of Cain.

And if you do say, that Esau and Ishmael`'s stock, and the Egyptians were reprobated.
Then tell not us of these stocks, for we are not of Esau`'s, nor Ishmael`'s,
nor of the Egyptians`' stocks, the sons of Ham; for are not we of Japhet`'s stock,
if you will derive the genealogies of people?
And was it not promised that Japhet should dwell in the tents of Shem,
if Shem was of the elect?
and therefore, tell not us of your doctrine of election and reprobation of persons,
and of certain stocks of people.

But come, look back again, and turn over a gospel-leaf,
does not Christ bid his disciples go into all nations and preach the gospel
of good news and glad tidings of salvation to every creature under heaven?
And do you think that they passed by the nations of Esau, and of Ishmael,
and of the Egyptians, and Babylon, and said, and preached unto them,
that God had foreordained them to reprobation, condemnation, and hell?
Were not all these creatures and men?
and hath not Christ tasted death for every man, and so for these as well as others?
And his gospel was preached to every creature under heaven, of comfort and salvation,
and so to these as well as others.

And he who enlightens every man that cometh into the world,
enlightens these as well as others: and his grace which hath appeared unto all men,
hath appeared unto all these as well as others;
and if they did not believe in it and receive it, it was to be a witness against them,
and they were worthy of the judgment and condemnation;
else how will God judge the world in righteousness, according to the gospel,
the power of God, if that the gospel be not preached to,
or in every creature under heaven; and that Christ hath not tasted death for every man,
which were dead in old Adam, that they might believe and be turned unto God?
but the light of the gospel, which enlightens every man that cometh into the world:
and the grace of God in the gospel, which bringeth salvation, hath appeared unto all:
and God hath poured out of his spirit upon all flesh in his new covenant,
so that all flesh might see the salvation of God.

Now, if they deny this grace, this light, this gospel,
and Christ who tasted death for them; and they that say,
'`that Christ hath not shed his blood, and tasted death for every man;
and doth not enlighten every man that cometh into the world, with the true light,
which is the life in him, that people might believe in him:`' and say,
'`that the grace of God that brings salvation hath not appeared unto all men;`' and
that '`it is not sufficient to teach and to bring their salvation:`' and say,
'`that God doth not pour out his spirit upon all
flesh in the day of his new covenant:`' and say,
'`that the apostles were not to preach the gospel unto,
or in every creature under heaven, but unto some only,
and the other were foreordained unto reprobation,
written of old to condemnation;`' such are in the reprobation themselves,
and under the condemnation, and are the sect-makers.

And now, if you say, (that preach up,
that the greatest part of mankind are foreordained
for condemnation,) that the word came unto Jacob,
and the statutes unto Israel: which is true, and the like was not to other nations.
And what must be inferred from this?
'`That the gospel in the new covenant must not be preached
to all nations.`' For we know that the word came to Jacob,
and the statutes to Israel,
and that the children of Israel received the statutes and the law, and the old covenant;
and Jacob was called so, as he was a supplanter of profane Esau, and was called Israel,
as a prince with God, and a prevailer with men.

So the nation of these children of Israel, the Jews, they had the types, figures,
and shadows, given unto them in the old covenant.
And the law served till Christ Jesus, who came in the new,
and did abolish them in the old.
So that all nations need not hold the figures and shadows,
but only that particular nation of the Jews,
which were figures and shadows of the substance, Christ,
that came of the seed of Abraham, which was to be preached to all nations,
so that all nations might be partakers of the substance,
which that one nation had the figures and types of,
and held up by the law in the old covenant; but Christ the substance in the new covenant,
is promised both to Jews and Gentiles.

So that if any that are called christians,
will make themselves a peculiar sect from these words to Jacob,
and hold that all are foreordained to condemnation but themselves,
because the word came to Jacob, and the statutes to Israel,
which the like was not to other nations;
and ground their conceit of their election only upon these words;
these show their great blindness and ignorance;
because the Jewish nation in the old covenant (and not other
nations,) held the figures and types of Christ the substance,
the new covenant, which is to all nations his gospel, his light, and his grace, yea,
his death, which he hath tasted for every man.

Now Jacob clears this thing himself, saying, '`the sceptre shall not depart from Judah,
nor the law-giver from between his feet, until Shiloh come;
and unto him shall the gathering of the people be.`'

So that now people must be gathered by the light, grace, truth, spirit,
and gospel of Christ Jesus, unto Christ Jesus, the Shiloh, the peaceable Saviour.
For doth not the Lord say to Abraham,
'`in thy seed shall all nations be blessed?`' +++[+++mark, all nations be blessed.]
And did not the Lord say the same to Isaac,
'`that in his seed should all nations be blessed?`'
and did not the Lord say also unto Jacob,
'`in thy seed shall all the families of the earth be blessed.`' Gen. 28?

Now how can all nations and all the families of the
earth be blessed in the seed of Abraham,
Isaac, and Jacob; if God hath foreordained, without any fault or cause,
such a number of persons to reprobation and condemnation, as you say and preach?

But are not you that teach this doctrine under the condemnation
and reprobation from the word and promise of God,
and doctrine of the old and new covenant, who said, that all nations,
and all the families upon the earth should be blessed, +++[+++mark,]
blessed in the seed of Abraham and Isaac, which seed is Christ?
And how are they blessed, if foreordained to condemnation or reprobation,
according to your dark doctrine?

But doth not men`'s reprobation and condemnation
come from not believing in the light Christ,
and not obeying the gospel, and receiving this blessing from Christ,
who hath tasted death for them, and shed his blood for every man,
and so from him cometh the justification to life?

And condemnation is come upon all men in old Adam for their disobedience and unbelief;
so Christ enlightening all men, that come into the world,
by the light which is the life in himself, the word, by which all things were made,
that was before Adam was; so that all might believe in the light, and receive it,
and receive this grace and gospel, that is preached unto all; and not grieve this spirit,
that is poured upon all flesh; but with this spirit mortify the flesh,
with its affections and lusts, that lead them from God; and believing in his light,
and walking in his grace and spirit, and in his gospel,
and so believing in Christ and God, which sent him,
'`which is eternal life to know God and Jesus Christ,
and receive the blessings that come by him;`' but not believing in this,
but hating the light, which they should believe in, and quenching the spirit,
that is poured upon all flesh; and walking despitefully against the spirit of grace,
that hath appeared unto all men; and denying the Lord Jesus Christ, that bought them,
and that he tasted death for every man, and the gospel preached to every creature;
thence comes their condemnation and reprobation;
and is not there cause and fault enough in themselves, for denying God and Christ Jesus,
in whom all nations are blessed; who destroys the devil and his works,
(that have brought the curse, death,
and darkness upon all nations,) and who brings both light and life,
blessings and salvation, and justification of life upon all men.

But if men do not believe in the light,
then is their condemnation and God will judge the world in righteousness,
by Christ Jesus, who hath enlightened them all, and tasted death for them all,
and hath sent his apostles to teach and preach this good news (the
gospel of salvation,) to every creature under heaven;
for God would have all to be saved, and come to the knowledge of the truth.
So God hath not ordained nor willed their destruction, neither desires he their death;
but their destruction is of themselves, when they go out of his will, from his grace,
spirit, light, truth, and gospel, the power of God, and follow their own wills,
so their destruction is of themselves, and their condemnation is just;
and God will judge the world in righteousness by
Christ Jesus the heavenly and spiritual man,
according to his spirit that he hath poured upon all flesh,
and according to the light that he hath enlightened
every man that cometh into the world withal,
which is the life in Christ; and according to the grace of God, that brings salvation,
and hath appeared unto all men: which they that do go from the light, and hate it,
and from the grace, and walk despitefully against the spirit of grace,
and disobey the gospel preached to every creature, and rebel against the spirit,
and follow their own wills and spirits, such go from the will of God, and do their own;
and such go into reprobation, and are under condemnation, and so will not, and do not,
receive the blessings in Christ Jesus, but the judgment and condemnation of Christ,
who will judge the world in righteousness;
and there is fault and cause enough in themselves for it.

And again, you bring another scripture for your proof, as you think,
wherein it is said as followeth; '`for this purpose have I raised up Pharaoh,
that I might make my power known in thee,
that my name might be declared throughout all the earth.`'

But this is nothing to prove that the Egyptian nation is reprobated.
For is not God`'s power known in his bringing his Jews in spirit out of spiritual Egypt,
Sodom, and Babylon for God raised up outward Pharaoh,
and hardened him against the outward Jews,
who would not let them go to worship God in the wilderness,
till the first birth of Egypt was slain.

And must not the first birth in spiritual Egypt and Babylon be slain before
the Jew in spirit come out of spiritual Egypt and Babylon,
to worship God in the spirit and in the truth;
and there you may read the reprobation in yourselves,
and not find fault with Pharaoh without you.

For doth not the apostle say, '`that Christ was crucified in spiritual Sodom,
and Egypt?`' And was not Christ crucified without
the gates of outward Jerusalem by the Jews,
which were of Jacob`'s stock, the election, as you call it,
and were the greatest professors upon the earth?
And is not outward Jerusalem here, and those that crucified Christ,
called Sodom and Egypt, and so in the reprobation and condemnation for not believing?
And are not both Jews and Gentiles concluded under sin and in unbelief,
that he might have mercy upon all?
That is, upon the Jews and Gentiles, +++[+++mark, upon all,]
and where then is your predestination or foreordination to condemnation?
Seeing that all are concluded in unbelief, that God might have mercy upon all;
then doth not the condemnation come upon them that despise this mercy,
and believe not in Christ Jesus?

For the Jews were not grafted in because of unbelief; but the Gentiles, and the Jews too,
that did believe, were grafted into Christ by their belief in the light,
which is the life in Christ. Rom. 11.

And is not the election according to grace?
So if it be by the grace of God, which brings salvation, that hath appeared to all men,
then the election is no more of works of the law, in the old covenant, but of grace,
that comes by Jesus, in the new covenant, in whom the election is.

And now, they that walk despitefully against the spirit of grace,
and turn it into lasciviousness,
they walk despitefully against that which should call them into Christ,
by whom the grace comes.
So is not that then their condemnation, and not their election or predestination?

For the apostle saith, '`it is not he that willeth, nor he that runneth,
but God that showeth mercy; and he hath concluded them all in unbelief,
that he might have mercy upon all.`' So then,
all that will leave their willing and running, and look at the mercies of God,
and believe, Rom. 9:16. and Rom. 11:31. and believe in the grace,
they receive their election.

For the grace of God, which bringeth salvation, hath appeared unto all men.
Therefore, all men are to mind this grace of God, to call them, and to teach them,
and to bring their salvation;
and by it they may know the election of grace in the new covenant of light and life.

But if they walk despitefully against the spirit of grace, that is poured upon all flesh,
they go into reprobation and condemnation, from the election;
and then God is just in judging them, according to his mercy upon all,
and his grace that hath appeared unto all, that would teach all,
and bring their salvation.
So the election is of grace in the new covenant.
And they that receive the grace, and walk not despitefully against the spirit of grace,
receive the election.

And again, you bring for your proof of your part of election and reprobation,
this scripture: '`Jacob have I loved, and Esau have I hated;
and the elder shall serve the younger.`'

Now if the election stood only in Jacob, was not Paul of Jacob`'s stock,
and the Jews of Jacob`'s stock, who were concluded under sin and unbelief;
as well as the Gentiles, that God might have mercy upon all?

But was not Esau a worker, by which works he thought to have got the blessing?
And were not the Jews workers?
And did not they think to have got the blessing by it in the new covenant?
But does not the apostle tell the Jews,
that the purpose of God according to the election stands not in works, but by grace,
which hath appeared unto all men?`' see Rom. 9:11-12. and Rom. 11:5. 6.

But, as I said before, was not the gospel preached to the nation of Esau, and Ishmael,
and Egypt?
And did not Ishmael and Esau come into the covenant of circumcision?
and must not they come into the new covenant of circumcision in the spirit,
the substance of that type?
Yes truly, if they believe.

And was not God`'s mercy upon the house of Ishmael and Esau, as well as upon the Jews?
Else how comes his mercy upon all?

Now the apostle tells the Romans of Esau and Jacob,
and the elder serving the younger then amongst the Romans;
and were the Romans of Jacob`'s stock, or Esau`'s stock?

But doth not the apostle say, '`we Jews of Jacob`'s stock,
by nature were children of wrath as well as others?`' And were
not all Jews and Gentiles concluded under sin and unbelief,
and so were vessels that held the wrath as well as others?
so then were they not all children of wrath by nature, and in the reprobation,
and under condemnation, and dead in Adam, that God might have mercy upon all,
in Christ Jesus, who tasted death for all, and brings justification of life upon all?

And are not you finding fault with Ishmael, and Esau, and Cain?
And were not Cain, Ishmael, and Esau your elder brothers?
And Esau a man of the field, a hunter?
And are not the nature of these the first birth in you all,
of reprobation to condemnation?
And why are you finding fault with Cain, Ishmael, and Esau, without you?
Are not these the elder nature in you, of killing of Abel, and mocking of Isaac,
and would slay Jacob?
so must not this first birth of reprobation, be slain with the sword of the spirit?

For doth not Christ say, '`ye must be born again,
before ye can see or enter the kingdom of God?`'

So see if Cain be a vagabond in you;
so the apostle tells the church of a Cain in John`'s first epistle, the third chapter;
and told the Hebrews of Esau, and bid them, '`take heed,
lest there were any fornicator or profane person amongst them like Esau,
who for a mess of pottage sold his birthright.`' Heb. 12.

And the apostle bids the Galatians, '`cast forth the bondwoman and her son;
for he should not be the heir with the son of the freewoman.`' Gal. 4.

Now it is known that Cain, and Esau, and the bondwoman, and her son Ishmael,
were dead long ago, before the apostle spoke forth this.

But were the Galatians of Ishmael`'s stock?
or were the Hebrews of Esau`'s stock?
or were they not of the nature of Ishmael, and Cain, and Esau, both among the Jews,
Galatians, and Romans, which nature of reprobation must be cast out,
so that the election might stand in the seed of grace, and not in works of the law,
in the old covenant, nor Esau`'s.

And so in this, God`'s mercy, and grace, and gospel was shown, and preached,
and appeared unto all, even the nation of Ishmael, Esau, and the Egyptian nation also,
as well as to the Jews, or others.

For doth not the Lord call Egypt his people?
and saith, '`blessed be Egypt, my people, Assyria,`' etc. Isa. 9.

And were not many of the Egyptians turned to christianity before the Turk got up?

But if you say Esau is hated, and Cain was a vagabond,
and Ishmael was cast out with his mother, and so are in the reprobation.

But do not you love the nature of that first birth
of Cain that murderer in you that envies his brother?
And that scoffing nature of Ishmael, that scoffed at the good seed Isaac?
And the profane nature of Esau, that would destroy Jacob the second birth?
Do not you love this more than the second birth, the seed of the promise?
And is not that nature yet which is hated of God in you, as the wild, profane, murdering,
and scoffing birth without was, which must be cast out of yourselves,
before you know the election in Christ Jesus, and the reprobation in the first birth?
'`For he that is in Christ, is a new creature;`' so the old creature is not in Christ;
and so the new creature in Christ Jesus crucifies the affections, and lusts,
and nature of Ishmael, Esau, Cain, Sodom, Egypt, and Babylon, that is spiritual,
and dashes that whore`'s brat against the living stone, that whore`'s brat,
that hath whored from the image and spirit of God, that hath brought it forth;
but does not dash the outward births nor outward creatures of the children of Ishmael,
Esau, Sodom, or Egypt, as persons; but the Egyptian spirit,
and the scoffing nature of Ishmael, and the murdering spirit of Cain,
that is got into persons, yea,
even into Jews and christians (so called,) who talk against the persons of Cain, Ishmael,
Esau, Egypt, Sodom, and Babylon, as being reprobated without them,
when as the spirit and nature of reprobation of all these lives within themselves,
which is the elder, the first birth, and he must not rule, this reprobation,
nor be heir of the seed of the promise; but the election obtains it,
which lies in the grace and mercy of God in Christ Jesus.

For God hath made all nations of men of one flesh, blood and mould,
and would have them all to repent, and live to Christ; for they all died in Adam,
and their minds are reprobated from God; but the election is in Christ, his grace:
and so it lies in the two seeds, and not in persons,
as the apostle plainly sets forth and discovers, who speaks of the nature of Cain,
Ishmael, and Esau to be in the Jews and Gentiles long after they were dead,
which must be cast out.

And Christ told Nicodemus, a ruler among the Jews (and was not he of Jacob`'s stock,
of the election; and not of Esau`'s, of the reprobation,
as you call them?) '`that a man must be born again,
before he can either see or enter into the kingdom of God.`'

So the children of Jacob, the election, must be born again,
before they can enter the kingdom of God.
So must the children of Esau, and Israel, and Babylon, and Egypt, and christians too,
before they can either see or enter into the kingdom of God.

And did not the prophet tell the Jews, they were as Sodom and Gomorrah?
and Christ was crucified in Sodom and Egypt.
So the Jews were turned into the nature of Sodom and Egypt, though not into the persons,
and so were become like reprobate silver and dross,
when they went from God`'s spirit and his law; so are christians,
which are gone from the law of life, which is in Christ Jesus, in the new covenant,
and the grace, light, and truth, that comes by Jesus, and the spirit,
that is poured upon all flesh; they are all as reprobate silver,
and make a great noise about reprobation,
when they themselves are found in the nature of it.

Therefore, all were better to be still,
and look upon the mercy of God in Christ Jesus unto all,
and receive the light that enlightens every man that cometh into the world;
and for all to receive the grace of God, which hath appeared unto them all,
which will teach them and bring their salvation,
that they might know the election of grace, and the reprobation out of the grace.

For the apostle saith, speaking of Moses, '`I will have mercy on whom I will have mercy;
and I will have compassion, on whom I will have compassion.`'

Now this saying of Moses,
in Exodus 33:19. the apostle brings upon the occasion of the Jews making a calf,
and their saying,
'`these were the gods that brought them out of Egypt:`'
and were not they then gone into the reprobation from God,
for not believing in God?
And yet they were children of Jacob,
(the election,) for which many of them were destroyed; read Exodus xxii.

And was not this after God had saved them, and brought them out of Egypt?
Was not this through their unbelief of God, which had saved them,
that thus brought their condemnation and destruction?

And so, is it not through unbelief in the grace and the light of Christ,
that is the cause now of people`'s condemnation and reprobation,
and not of their election in the grace?

And so, let all that profess christianity, teacher and hearer, examine themselves,
whether they be in that faith which Christ is the author and finisher of,
that purifies their hearts, and gives victory over the world, and the devil,
and their sins, that do separate them from God their Creator;
by which faith they have again access to God, and in which faith they please God,
which is the faith of God`'s elect.

And see if they be not reprobated from this one, precious, holy, divine, purifying,
justifying faith, which the saints do and did in the primitive times contend for,
which Christ was and is the author and finisher of, and hath the glory of,
and no man else whatsoever: in which faith all the saints have unity,
which gives them victory and access to God, and in which they all please God.

And again, let all Christendom examine and prove themselves, both hearers and preachers,
whether Christ be in them, yea or nay?
And if Christ be not in them, for all their preaching of Christ in words,
and the others hearing of Christ in words, yet the apostle tells them,
they are reprobates.

So let none put the reprobation so far off them, as Cain, or Cora, or Sodom, or Egypt,
or Ishmael, or Esau, or Babylon; and say they are reprobates:
but see if the nature of these be cast out of themselves,
and see if they be in the elect seed Christ Jesus, who bruises down the serpent`'s head,
the head of reprobation;
so that they may see the reprobation stands in the evil seed since the world began;
and the election stands in the good seed Christ Jesus, which was before the world began:
and the promise is unto the seed, which is one, and not many.
And so feel that one seed in you, Christ Jesus, the heir of the promise,
and then you will not be reprobates, that all may praise God through Jesus Christ.

And Jacob is called a supplanter, and Esau, a worker; is he not?
And do you think he did not work hard, and willed hard, and run hard,
when he went a hunting, and so lost the blessing?
But Jacob tarried at home with his mother, without any willing, or running, or working,
he got the blessing.
So the election is not of him who runs or wills, but of grace:
and then must not every one tarry at home with the grace in their hearts and mouths,
with their mother Jerusalem from above, if they do obtain the election of grace;
'`for by grace they are called and saved.`' And so here the elder, the first birth,
came to serve the younger in the grace, in the election, and profane Esau comes under;
yet as a man, Esau had a blessing from his father.
He that hath an ear, let him hear.
And Israel and Esau were both circumcised in the old covenant, a type of the new.

But if you despise your birthright for your earthly and outward bread and pottage,
and this world`'s wages and wealth, and choose that, and go from the grace,
you will be profane, and be baptized into profane Esau`'s nature,
and bear the badge of Edom, and not Christ`'s in whom is the election.

For all that walk despitefully against the spirit of grace,
go into Esau`'s and Ishmael`'s nature, and will despise that birthright of election;
they cannot say but they had grace, and had a birthright as well as Esau.
For the grace of God, which brings salvation, hath appeared unto all men:
so his mercy is upon all, and his Son has tasted death for every man.

And so, no man can say but he had a birthright, through this grace;
but if they turn it into lasciviousness,
and walk despitefully against the spirit of grace, they go into condemnation, like Esau,
who despised his birthright, manifesting he had one.

For Ishmael and Esau had the covenant of circumcision, in the flesh, as is said before,
a type of the new covenant and circumcision in the spirit.
And the gospel was preached to them, being preached to every creature under heaven.

And Cain had his day of visitation; for the Lord told him, '`if he did well,
he should be accepted; and if not,
sin lay at his door:`' so there was a promise of God to Cain,
if he had believed it and received it; so his destruction was of himself.
And so was the old world`'s, for grieving God`'s good spirit,
and not receiving righteous Noah`'s preaching, who was a preacher of righteousness;
and therefore, their destruction and condemnation came upon themselves,
for going from the spirit of God in themselves,
and not regarding this righteous preacher Noah.

And all the Jews going from God`'s good spirit,
which he had given to instruct them in the old covenant, and rebelling against it,
and transgressing his law, and his old covenant, and going from God,
and not regarding him nor his prophets, that were preachers of righteousness.
So all their destruction and condemnation came upon themselves;
God did not desire the death of any of those ungodly sinners,
but rather that they had repented, and returned, and lived;
for he hath no pleasure in the death of them that die;
but he hath pleasure in them that walk and live in his spirit, and hear his voice,
and believe, and obey him, and do as he commands,
and serve him in the new and living way, and worship him in the spirit and truth,
which the devil and death is out of.

So now God hath poured out of his spirit upon all flesh, in his new covenant, yea,
his daughters, hand-maids, and servants,
and hath enlightened them all by the life in Christ the word,
by which all things were made; and his grace hath appeared unto all men,
that will bring their salvation; yea, and his gospel is preached to,
and in every creature under heaven.

Now all men and women, that do grieve, vex, and quench this spirit,
and will not be led by it, and hate the light, which is the life in Christ,
and will not believe in it, and walk despitefully against the spirit of grace,
and turn it into wantonness; all such,
their destruction and condemnation is of themselves,
who walk despitefully against that which should bring their salvation,
and hate that which they should believe in, and be saved by,
and vex and quench the spirit, which they should walk in, and be led by.

So God is just in condemning and judging according to his light and gospel,
which is preached unto every creature;
and they not receiving the comfortable glad tidings of the gospel of salvation,
the pure God and the spotless Lamb`'s judgment is just upon them,
who judges in righteousness and equity, according to his gospel,
the power of God preached to them, and in every creature.
And according to his grace, which hath appeared unto all men, to teach them,
and bring their salvation; and according to his spirit,
that he hath poured out upon all flesh: and they that walk contrary to these gifts,
and will not receive them, but despise them which come from God and Christ,
God and Christ will judge them in righteousness,
and their destruction and condemnation is of themselves;
for '`God desires not the death of a sinner, but that he might repent, return,
and live:`' neither (as I said before,) hath he pleasure in him that dies,
but would have all to come to the knowledge of the truth and be saved.
God`'s pleasure is in them that live in the covenant of light, life, and grace,
over death and darkness, and so serve God in the new and living way,
and worship God in the spirit and in the truth, which the devil, the power of death,
is out of: here in this new and living way,
God hath pleasure in his people that live and walk in it; glory be to his name forever.

And Isaac said unto Esau, '`by the sword thou shalt live, and shalt serve thy brother,
(to wit, Jacob, the younger,) and it shall come to pass,
when thou shalt have the dominion, that thou shalt break Jacob`'s yoke from off thy neck.
So Esau hated Jacob; and Esau said, he would slay Jacob;
but his words were told to Rebecca,`' etc.

And now consider, Esau, this first birth, he lives by his carnal weapons, his sword,
this rough man of the field, and worldly man, and profane person`'s nature in you all,
yea, Jews, Gentiles, and christians,
though you may find fault with profane Esau without you.
But Jacob, the second birth, will tell you,
that Esau the first birth`'s nature is within you, that will kill him;
though it be not the person of Esau, Ishmael, and Cain;
but there is the spirit and nature of murdering Cain, that is within you,
that is wroth at Abel, and will murder him, to wit, the second birth,
whose sacrifice God accepts, and not the first birth, Cain`'s.

And also, that there is the spirit and nature of Ishmael within you,
though not the person, that will scoff at the seed of the promise.

And also, that there is the spirit and nature of profane Esau within you,
though not his person, that is a worker, wilier, runner, and hunter,
that will say in his heart, he will kill Jacob, the second birth; that is,
the rough nature, the rough man Esau, in the field, a worldling,
that hath his carnal weapon, and he lives by his sword.

And so the spirit and nature of Cain, Esau, and Ishmael within you,
will find fault with the persons of Esau, Cain, and Ishmael without you, yea, and Cora,
Pharaoh, and Babylon; and say,
they are persons ordained for reprobation and condemnation;
when it is the same spirit and nature in themselves that speak it,
which is written of old for reprobation and condemnation, both in Jews and christians,
and in all in the first birth; '`for until they be born again,
they can neither see the kingdom of God, nor enter into it,`' as Christ said.

And this was a wonder to old Nicodemus, that ruler and professor,
that was of Jacob`'s stock according to the flesh.

But Isaac`'s prophecy to Esau, how that '`the time should come,
that Esau should break Jacob`'s yoke from off his,
neck;`' the yoke of Jacob the second birth, the yoke of God`'s beloved Jacob,
in whom the election stood, and in whose seed all the families of the earth were blessed.

So it seems that the yoke of this seed,
which all the families of the earth are blessed in, in which seed stands the election,
which seed is the beloved of God, the second birth, was a yoke a-top of the profane,
rough, first birth Esau, the hunter, the wilier, the runner, the worker,
the man of the field, of the world, who lived by his carnal weapon, his sword;
it was a yoke upon the neck of this first, profane, rough birth,
that despised his birthright for his mess of pottage, and bread of fainting Esau,
who had been willing, and running, and was weary in the world, the field,
which is the path of the first birth; and so his mind was not upon the Lord,
who renews strength, nor the grace; but despised his birthright,
(manifesting he had one,) as this profane birth does in all.

And was not this a sad thing, when smooth, plain Jacob, the second birth`'s yoke,
(in whose seed all nations are blessed,) is broken off; the profane, rough Esau,
the first birth`'s neck?
then profane, rough Esau hath his liberty, and will serve no longer the second birth,
the election, and will plead for his profane liberty, with his carnal sword,
and his willing, and hunting, and running in his rough nature, the first birth,
the man of the field, the world; yet would he be heir,
and have the election and blessings; but it is only in talk, and not in possession.

And so did not this first birth, or nature of rough Esau, get up in the Jews,
when they turned against this seed in Moses and the prophets, yea, and Christ Jesus too,
and his apostles?
was not profane, rough Esau`'s nature, and Esau`'s sword,
and the rough birth manifest in the Jews?
And had not they gotten old Jacob`'s yoke off their neck, who was a smooth, plain,
and perfect man, the beloved and elect?
And were not they turned hunters with their sword for the blood of the prophets, Christ,
and the apostles?
And was not Esau then got at liberty in them, and the seed in bondage,
which is heir of the promise and the election, which hath it by grace?

And did not Christ tell one of Jacob`'s stock, Nicodemus, '`that man must be born again,
before he could see the kingdom of God,
and enter into it;`' which made the Esau`'s nature in him to gaze and wonder,
and made the rest of the Jews to gaze and wonder.

And therefore, doth not the apostle often say to them,
'`ye gazers and wonderers,`' when the seed`'s yoke (in which all
the families of the earth are blessed,) was broken off their neck,
in which the election is; and the seed was entered into persons, which brought the curse,
and which made them children of wrath by nature, as well as others?

And now, all ye that are called christians,
who do hold reprobation in the persons of Esau, Ishmael, Cain, Cora,
and the children of Egypt, Sodom, and Babylon;
and every sect in Christendom look upon themselves to be in the election, and it may be,
other persons to be in the reprobation, that are not of their sect;
when as the spirit and nature of all these are found in themselves,
and the first birth`'s nature of Esau, and the rest of those whom you call reprobates,
who have broken off the second birth, Jacob and his seed,
(in which all nations are blessed,) his yoke off your neck.
For do not you appear in the rough nature of Esau, and the murdering,
man-slaying nature of Cain,
and the scoffing nature of Ishmael against faithful Abel`'s offering, and Isaac,
the seed of the promise, and Jacob, the perfect plain man, beloved of God,
in whose seed all the families of the earth are blessed, as men and women,
(though not the spirit of Cain, Ishmael, Esau, Babylon, Egypt, and Sodom,
which is in you, and so in the reprobation, and for condemnation, and to be cast forth?
For it is not to be heir with the seed of the freewomen.)

And now Jacob, the election`'s yoke,
(the seed in which all nations are blessed,) being broken off your neck,
and you at liberty with your rough, profane hands and sword,
and willing and running in Cain`'s spirit, persecuting, murdering,
and scoffing the faithful Abel`'s, and the heirs of the promise,
and the plain smooth man, the second birth, Jacob, whom God loveth,
who tarries at home with the Lord, and Jerusalem, which is above, his mother,
who is in the election; whom you hate, scoff and would kill, Esau-like.
And how can this birth talk of ordination to condemnation, and reprobation,
which itself is in the birth of reprobation,
(and under condemnation,) and yet preacheth up reprobation and condemnation of others,
when in their spirits and nature they are found in
the reprobation and condemnation of Cain,
Ishmael, Esau, Egypt, Sodom, and Babylon, which despises (Esau-like,) the birthright,
in the grace of God in the new covenant, which hath appeared unto all men,
and is sufficient to teach them, and bring their salvation; and hates the light,
which is the life in Christ, the word, by whom all things were made,
which all should believe in; and denies that the gospel of salvation is preached to,
and in every creature under the whole heaven,
and quenches and grieves the spirit which God poureth upon all flesh,
to lead and instruct them; and denies that the Lord Jesus Christ hath shed his blood,
and tasted death for every man: but saith,
'`he hath foreordained the greatest part of mankind to reprobation and
condemnation.`' But this is that spirit and nature that is in the reprobation,
and under the condemnation, that doth so preach and teach.

So this first birth, nature, and spirit of Esau,
that hath broken the second birth`'s yoke off their neck,
hath gotten up since the time of the apostles and primitive church,
and hath been at liberty in Christendom.

And this rough first birth, that hath made a profession of the New Testament in words,
as the first birth did of the old, before the days of the apostles,
with their rough hands and hunting spirit, and with their carnal weapons,
they have maintained their church, ways, and worships, with their reprobate spirit,
nature, and weapons, which are written of old for condemnation.
But the second birth will arise, the seed of the promise, the election,
and bring its righteous, just, pure yoke over the profane spirit and nature of rough,
profane Esau, the first birth`'s neck, and scoffing wild Ishmael; and wrathful,
murdering Cain`'s nature must be a vagabond,
and the first birth of Egypt must be slain in you all;
and the Babylon`'s brat of confusion,
which the whore hath brought forth in you must be
dashed to pieces against the living stone:
and the plain, smooth, and perfect, and beloved Jacob, the seed of the promise,
must be the Lord, in which all nations are blessed;
and the Jew in the spirit must come forth,
and serve and worship God in spirit and in truth: he that hath an ear, let him hear.

And this seed, in which all nations are blessed, doth preach,
that all nations are blessed in it; and that that is cursed, and in the reprobation,
which curses this seed; and that that seed is blessed that blesses this seed,
in which the election is.

So if all nations be blessed in this seed of Abraham, Isaac, and Jacob,
as men and persons, in which seed the election is, the second birth;
then the reprobation and condemnation stands in the profane, rough, first birth,
with all his works, and carnal weapons, and willings, and runnings,
with which he maintains his will-worship.
For this second birth, this seed is it, in which all nations are blessed:
then this seed doth not say,
that '`some nations are foreordained to condemnation,`'
as the condemned and reprobate seed doth say.

For it is God that doth say,
'`all the families of the earth are blessed in the seed of Abraham, Isaac, and Jacob,`'

And without this seed they are not blessed.
In this seed they are all blessed; and out of this seed they are not blessed,
but are in the seed of reprobation and condemnation, and in the unbelief;
and not in the seed Christ Jesus.

And this seed, in which all nations are blessed,
in which the election is before the world began,
(for the reprobation and condemnation is in the evil seed since the world began,) this
seed doth see how the condemnation is come upon all mankind by the fall of Adam;
and how that the justification of life is come upon
all men by this one seed Christ Jesus,
where it is received; and how that Christ hath shed his blood,
and tasted death for every man; and so makes no sects:
and how he enlightens every man that cometh into the world with the life in himself,
the word, by which all things were made, that they might believe in it,
and have life in him.

And this seed doth see how the grace of God, which brings salvation,
hath appeared unto all men to teach them that receive it,
and how that all have been concluded under sin, and in unbelief,
that God might have mercy upon all:
and their condemnation is for not believing in this seed Christ Jesus.

And how is the blind, first birth of Esau like to see, or hold forth,
'`that all nations are blessed in Isaac, and all the families of the earth in Jacob;
and that the grace of God, which brings salvation, hath appeared unto all, to teach them,
and bring their salvation; so that all might dwell in tents, and tarry at home,
and see their election, in the grace, and God pours out of his spirit upon all flesh;
and the seed Christ Jesus.
hath tasted death for every man;`' scoffing Ishmael
will scoff at this doctrine of the seed;
and envious Cain will be wroth, and his countenance will fall,
against the sacrifice of it;
and profane Esau will lift up his sword and rough hands against it, and cry,
God hath foreordained a great number of men to reprobation;
and so would pluck them down into hell with him; when it is that spirit, nature,
and first birth in themselves that is for reprobation and condemnation,
for not believing in the light, and receiving the blessing that is in his seed.

Now this seed`'s weapons (in which all nations are blessed,
which brings the justification of life upon all men, and enlightens all men,
and through him God pours out of his spirit upon all men,
and his grace appears unto all men, etc. and this seed hath shed his blood,
and tasted death for every man,) his weapons and armour are spiritual,
and they do not wrestle with flesh and blood that be in it, nor with the persons of Cain,
Ishmael, Esau, Cora, Sodom, and Egypt, nor with the persons of Babylon,
but with the nature and spirit of these, and the rulers of darkness in people.

For those outward carnal weapons, are the first birth of Pharaohs, Cains, Ishmaels,
Esaus, Sodom, Babylon, and Egypt, and the whore, which hath whored from this seed,
which are in the reprobation and condemnation, with their carnal weapons,
with which they maintain their ways, religions, and will-worships,
which be in the reprobation and under condemnation.

So each seed and birth hath its weapons and armour, ways, religions, and worships,
by which they maintain them, both that which is in the reprobation and condemnation,
and that which is in the election, and that seed which is in the election,
in which all nations and families are blessed,
which brings the justification of life upon all men, in which the election is,
before the world began; bruises the head of the first birth, the serpent,
the world`'s god, with all his carnal weapons,
by which the first birth maintains its religions, ways, and will-worships; I say,
this seed, the first birth, the head of it is bruised by the seed Christ Jesus.

And this seed, in which all nations are blessed,
doth not destroy any man`'s life upon the account of religion and worship;
but saves men`'s lives, and destroys the evil seed of reprobation and condemnation.
And this seed`'s weapons and armour are spiritual,
by which spiritual weapons and armour this seed defends its religion, ways, and worship,
and church, and wrestles not with flesh and blood;
for his armour and weapons are spiritual.

But the first birth in the reprobation, his weapons and armour are carnal,
and wrestles with flesh and blood about his religion, ways, and worship,
instead of spiritual wickedness and rulers of darkness; and saith and teacheth,
that God hath foreordained the greatest part of men and women for reprobation,
condemnation, and hell; and that which says so is the blind, rough,
profane seed in the reprobation and unbelief, and so under condemnation,
and hath despised its own birthright, in the grace of God, that brings salvation,
and hath appeared unto all men, who hath been willing and running in his first birth,
Esau-like, I say, hath despised his birthright in the grace of God,
and so doth not believe and receive the seed in which all nations are blessed;
but instead of it, receive that evil seed in which his condemnation is.
And that rough man of the field will hunt, wander, will, and run,
and not return till he faint,
and then despise his birthright for outward things and means;
and so relies not in the grace of God, which appears unto all men,
which men must not despise; for if they do, they will faint,
and not have their strength renewed; and then they cannot be heirs of grace,
nor partakers of the blessing in the seed, in which all nations are blessed;
so all nations are blessed in this seed, if they will receive it;
and Christ hath tasted death for them all, and so brought justification of life unto all,
if they will believe it, and not condemnation, who hath enlightened all,
and his grace hath appeared unto all, that they might believe, and be heirs of grace,
in which the election is.
And so here is God`'s mercy upon all,
though they were concluded in unbelief in the first birth.

And Christ enlightens all with the life in himself, and saith, '`believe in the light;
and they that do not,
are condemned already:`' and so they lay under the
condemnation and in reprobation because of unbelief;
for '`he that believeth, shall not come into condemnation.`'

For was not Adam and Eve condemned for not believing in God`'s teaching, and obeying it?
And Cain, and Cora, and the old world, and the Sodomites, who neither regarded God,
nor just Lot; and the Jews, who neither regarded God nor his prophets?
And so are not the christians under the same condemnation written of old,
that live not unto Christ, who hath died for them,
and walk not in him in whom all nations are blessed,
and walk nor stand not in the grace which hath appeared unto all,
which will teach and bring their salvation, as the primitive christians did,
and walk not after the spirit, which God hath poured upon all men;
but walk after their own spirits, and Cain`'s, and Esau`'s, and Ishmael`'s, and Cora`'s,
and Sodom`'s, and Egypt`'s, and Babylon`'s nature and spirit,
which leads them into confusion, reprobation and condemnation;
and believe not in the light, as Christ commands,
with which he enlightens every man that cometh into the world,
which is the life in himself; and are not they, therefore,
condemned with the light which they should believe in,
who have not kept in the same light, and grace, and spirit,
and power as the apostles were in; so not in their habitation, nor succession,
nor election; but have succeeded in the reprobation and condemnation,
and therefore are blind, who have held up reprobation in persons,
and not of the first birth, and seed in them.

And therefore, all men being enlightened by Christ, who hath tasted death for all men;
and God`'s grace hath appeared unto all men, to teach, and bring their salvation;
and he hath poured his spirit upon all flesh, and so his mercies are upon all;
and therefore must all believe in this light, if they will be grafted into Christ Jesus,
and receive the grace and the spirit, in their own hearts, at home,
if they will come to the election in Christ, from whence this grace, light,
truth and spirit comes; and so to know their election before the world began,
and the seed in whom all nations are blessed;
and the seed Christ to bruise the head of that seed of reprobation,
and separation of man and woman from God,
by which man and woman hath come into reprobation,
and under condemnation since the world began, written of old.

So in this seed Christ Jesus, is the election and the blessing, who is the amen,
the first and the last, and over all, hallelujah, blessed forever; glory to the Lord God,
amen, hallelujah.

[.signed-section-signature]
G+++.+++ F.

[.blurb]
=== Postscript.

The Jews which were of Jacob`'s stock, they said unto Christ,
that Abraham was their father.
And Christ told them, '`if they were of Abraham,
they would do the works of Abraham.`' And Christ said to these Jews,
'`that they sought to kill him, who had told them the truth which he had heard of God;
this did not Abraham.`' And also Christ told them, '`that his word had no place in them;
and that they were of their father the devil,
and the lusts of their father they would do?`' and said, '`because I tell ye the truth,
ye believe me not; and if they did not believe that he was the Son of God,
and the Christ, they should die in their sins.`'

So it is clear, the Jews, which were of Jacob`'s stock,
and could plead that Abraham was their father,
yet the serpent had begotten his bad birth in them, and blinded them,
that they were in the reprobate seed of murder, disobedience, and unbelief,
and should die in their sins, reprobation and condemnation,
if they did not believe in Christ, for all their outward profession of Moses,
and the prophets, and the law, and God and Christ to come,
who pretended to be the vineyard keepers and dressers, but had no fruits,
and killed his servants, and stoned them that he sent to look for fruits,
and at last killed the heir, and did not believe in him; and therefore,
the vineyard was taken from them, and they scattered over all nations in their unbelief,
reprobation, and condemnation.

And Christ several times cries,
'`woe unto the scribes and pharisees,`' and calls them '`blind guides;`'
and how that '`they shut up the kingdom of heaven against men,
and would neither go in themselves, nor suffer them that would, to go in;
and they were of them that killed the prophets;`' and he called them,
'`a generation of serpents and vipers; and that they should kill, and crucify,
and persecute the prophets and wise men, that he would send among them,
that upon them might come all the righteous blood that was shed from Abel,`' etc.

Now were not these Jews found in Cain`'s, Ishmael`'s, Esau`'s, Pharaoh`'s, Cora`'s,
Sodom`'s, Babylon`'s, and Egypt`'s nature, though they were of Jacob`'s stock,
and great professors without possession?
But in the reprobation, and unbelief, and condemnation: for did not Christ say unto them,
'`how can ye escape the damnation of hell?`' and did not Christ weep over Jerusalem,
which called themselves children of Jacob; but were turned to be children of the serpent,
in the reprobate seed, when he said, '`oh, Jerusalem,
Jerusalem! thou that killest the prophets, and stonest them that are sent unto thee;
how often would I have gathered thy children together,
as a hen gathereth her chickens under her wings, and ye would not; behold,
your houses are left unto you desolate?`' So these
must needs be empty and desolate houses,
that would neither receive Christ nor his prophets.

Now all you that profess christianity, that be in this first birth of persecution;
and if you do profess all the scriptures of the New Testament,
yet if you be not in the same Holy Ghost the apostles were in, ye cannot call Jesus Lord.
And if you have not the same spirit of Christ, as the apostles had, they tell you,
'`that you are none of Christ`'s.`' And if you be not in that one faith,
that Jesus Christ is the author and finisher of, and if Christ be not in you,
you are reprobates; then your houses must needs be desolate,
that profess the new covenant of Christ the substance,
as the Jews were that professed the old,
and so in the reprobation and under the condemnation.

So it is not an outward profession; for reprobates may do that:
but a profession of Christ, in whom the election is,
and so a possession of the seed of Abraham, Isaac, and Jacob,
in whom all nations are blessed.
And so it is not an outward profession of all the
words of the new covenant in the serpent`'s seed,
and possess the serpent`'s murdering persecuting spirit,
in the same seed and spirit as the Jews made a profession in words of the Old Testament,
which leads into reprobation and condemnation, from Christ in whom is the election,
who was before the reprobation and condemnation of fallen angels and men;
glory to the Lord God forever.

But the Lord hath promised, '`that he will destroy the covering of all people,
and the veil that is spread over all nations: and in that day they shall say,
the Lord is our God, and we have waited for him, and he will save us,
and we shall be joyful in his salvation.`' Isa. 24.

And is not this the day of the possession of the new covenant of light and life?
And Christ bruises the head of the serpent, and through death destroyeth the devil,
the power of death.
And so that all might believe in Christ, and come to God by him,
so that all might praise the Lord, who gives them breath and life, in his grace, light,
and spirit, that he gives them; which if they hate his light,
and rebel against his spirit, and walk despitefully against the spirit of grace,
then they turn into reprobation, and are under condemnation: for '`he that believeth,
is saved; and he that believeth not, is condemned; and he that believes,
overcomes the world, and the world`'s god, and is born of God, a child of light,
and enters into his rest, and ceases from his own works,
as God did from his.`' So it is unbelief that keeps out of Christ the rest,
and in the condemnation and reprobation, from the salvation.

And why was the earth, or land of Canaan emptied, and the curse devoured the earth,
and its inhabitants the Jews?
Was it not because they transgressed the laws and ordinances,
and broke the covenant of God? Isa. 9.

And did not Christ say to the Jews, which were of the children of Jacob,
'`that they were of an adulterous generation, that looked for signs,
and there should be no sign shewed to them;
but as Jonah was three days and three nights in the whale`'s belly,
so the Son of man should be three days and three
nights in the heart of the earth?`' and Christ said,
'`the men of Nineveh should rise up in judgment against
this generation to condemn it,`' (to wit, the Jews.)
And were not they of Jacob`'s stock,
of whom you hold the election as to persons?

And again, Christ saith,
'`the queen of the south shall rise up in judgment against this generation,`'
(to wit, of the Jews,)
to condemn it, which was of the stock of Jacob; who would not hear Christ,
as she did Solomon; nor repent at Christ`'s preaching, as Nineveh did at Jonah`'s,
though Christ was a greater than Jonah or Solomon.

And did not Christ upbraid the cities of the Jews, because they did not repent,
where most of his mighty works were done?
And did not he cry, '`woe unto thee Bethsaida, woe unto thee Chorazin;
for if the mighty works had been done in Tyre and Sidon, which have been done in thee,
they would have repented long ago in sackcloth and ashes:
and it shall be more tolerable in the day of judgment for Tyre and Sidon,
than for the great professing Jews,
which were of Jacob`'s stock?`' and did not Christ say to Capernaum,
'`though they were exalted to heaven, they should be brought down to hell;
for if the mighty works had been done in Sodom, which have been done in thee,
it would have remained until this day.`' And Christ saith,
it shall be more tolerable for the land of Sodom in the day of judgment,
than for Capernaum.

Then where is your election and reprobation of persons, if these of Jacob`'s stock be so,
as Christ saith, and I hope you will believe him?

And therefore,
then what was and is the Jews`' and christians`' profession of the scriptures worth,
without possession of God and his Son Christ,
(and yet live in an unrepented state,) but for judgment?
And therefore, it concerns all to turn unto the Lord,
with his light that enlightens all people; and with his grace,
that hath appeared unto all men, to teach them, and bring their salvation;
and with his spirit, that he pours upon all flesh, to lead them unto the Lord,
that they may serve and worship him, and be professors of Christ,
and enjoyers of the Lord, and so have the comfort of God and Christ,
and of the scriptures.
This is the desire of him who desires the eternal good and salvation of all people.

[.signed-section-signature]
G+++.+++ F.

For Adam and Eve, for disobeying the voice of the Lord came into condemnation,
and so condemnation came upon all men; the Jews,
for disobeying the voice and command of the Lord,
came under condemnation and reprobation: the christians,
(so called,) for disobeying the voice and command of Christ, who speaks from heaven;
and for not believing and receiving of him, come under judgment and condemnation,
and are in the reprobation.

[.blurb]
=== If God hath ordained the greatest part of men and women for Hell and Condemnation, as many of the Priests and Professors say and preach; then let them consider these scriptures as follow.

Matt. 28:18, to the end.
And Jesus spake to his disciples, saying, '`all power in heaven and earth is given to me;
go ye, therefore, teach all nations, (not some nations, but all nations,) baptizing,
(that is to say; dipping or plunging them,) into the name of the Father, Son,
and Holy Ghost,
teaching them to observe all things whatsoever I have commanded
you.`' Now death having passed over all men,
and all were concluded under sin, and all died in Adam,
so that condemnation must come upon all men,
so that all were baptized or plunged into death, sin, and evil,
by disobedience to God`'s command and ordinance; therefore, all nations,
and every creature under heaven, must be taught to observe whatsoever Christ commands,
and be baptized into the name of the Father, and into the name of the Son,
and into the name of the Holy Ghost; so salvation was preached to all mankind,
and condemnation was preached to none,
but such as did not believe in the light and gospel.

And in Mark 16:15. Christ saith to his disciples,
'`go ye into all the world, +++[+++mark, all,]
and preach the gospel to every creature.`' So,
here the gospel of salvation was preached to every creature.
'`He that believeth, is saved; but he that believeth not, is condemned:`'
so unbelief is the cause of condemnation;
and so they were not to preach the gospel of salvation to a part of the world,
or some creatures only; but to all the world, and to every creature under heaven,
the gospel of salvation; here was God`'s love to mankind:
and that repentance and remission of sins should
be preached to all nations in the name of Jesus?
And they were first to begin at Jerusalem,
so was the command of Christ unto his disciples,
and from thence to preach the gospel of glad tidings to every creature,
and to all nations, and not to preach condemnation; for that they were in before,
in old Adam, and after; not believing, they remained in condemnation, as Christ saith;
'`he that believes, is saved; he that doth not,
is condemned already:`' and he further saith, '`they that do not believe in the light,
but do evil, and hate it, this is the condemnation, that light is come into the world,
and men loved darkness rather than light, because their deeds were evil.`' John 3:19.

And the apostle saith, 1 Tim.
'`I exhort that supplications, prayers, intercession,
and giving of thanks be made for all men;`' and the apostle gives a reason for it,
'`that God would have all men to be saved,
and come to the knowledge of the truth.`' So here he would have all men to be prayed for:
now it being the will of God, that all men should be saved,
and come to the knowledge of the truth; then their destruction is of themselves,
who will not come to Christ, that they might have life.

And further, the apostle saith, there is one God, and one Mediator between God and men,
the man Christ Jesus, who gave himself a ransom for all, +++[+++mark, for all,]
to be testified in due time:
and though many do not believe that Christ gave himself a ransom for all,
yet in due time they may come to believe the apostle`'s testimony.

And further, the apostle saith in Titus 2.
'`the grace of God, that bringeth salvation, hath appeared to all men, teaching us,
etc. and by the grace of God, Christ should taste death for every man, +++[+++mark, every man,]
for all died in Adam, therefore Christ tasted death for all that died,
and gave himself a ransom for all, that all might believe in him,
and come to life.`' Heb. 2.

And the apostle John saith, 1 John 2.
'`how that Jesus Christ the righteous is a propitiation for our sins,
and not for our sins only, but for the sins of the whole world,`' +++[+++mark,
the whole world,]
that is, all the world, that Christ is a propitiation for the sins of.
Then how can ye say, that he hath ordained any for death and damnation?
For their condemnation is of themselves, for not believing.

And the apostle saith, in Acts 2.
'`this is that was spoken by Joel the prophet, it shall come to pass in the last days,
saith God,
I will pour out of my spirit upon all flesh.`' Now
this the apostle Peter spoke to the professing Jews,
of which some were amazed, and some were mocking.
And these last days are the days of the new covenant,
whereby sons and daughters shall prophesy, and young men shall see visions,
and old men shall dream dreams, and servants and hand-maids shall prophesy.
So it is the spirit of God, which he pours out upon all flesh, +++[+++mark, all flesh,]
men and women, by which sons and daughters, and young men and old men,
and servants and hand-maids come to prophesy, and have their dreams and visions:
so it is not by schools, and colleges, but by the spirit of God.

And in John i. he saith, that was the true light,
which lighteth every man that cometh into the world (to wit,
Christ,) and the world was made by him; and in him was life,
and this life was the light of men.

So it is called the life in Christ, the word, by whom all things were made,
and the light of men, yea, the true light,
which lighteth every man that cometh into the world.

And Christ saith, '`believe in the light, while you have it,
that you may become the children of the light.`'

And here is God`'s great love to mankind, who so loved the world,
that he gave his only begotten Son into the world, that whosoever did believe in him,
they should not perish, but have everlasting life.

And John said, '`he came for a witness to bear witness of this light, (to wit,
the true light,
which is the life in Christ,) which lighteth every man that cometh into the world.`'

And most of the teachers that are bred up at schools and colleges, and others,
they do come for witnesses, and bear witness against this true light, the life in Christ,
which lighteth every man that cometh into the world.
But those are false witnesses, and come not from God, if John was a true witness,
who was sent from God to bear witness to this true light,
that all through him might believe.

And now, all they that say, '`that this light is not sufficient,`' then they may say,
that Christ bid them believe in an insufficient light: but they that say so,
say and preach falsely; for Christ saith, '`by believing in the light,
they shall become children of the light.`'

And now you that say,
'`the grace of God which hath appeared unto all men,`'
is not a sufficient grace for all men;
but God told the apostle, '`his grace was sufficient;`' and it is strange,
that that which will bring people`'s salvation, and will teach them, is not sufficient.

And in Acts 3.
the apostle saith, in his preaching to the Jews:
'`a prophet shall the Lord your God raise up unto you, like unto Moses,
him shall you hear in all things, whatsoever he shall say unto you;
and it shall come to pass, that every soul, +++[+++mark, every soul,]
which will not hear that prophet, shall be destroyed from among the people.`'

So it is their own willfulness, that will not hear this prophet, in his own light,
grace and spirit, that brings their own destruction.

And Christ saith, in the sixteenth chapter of John, to his disciples;
'`He would send the Comforter to them, the Holy Ghost;
and this Holy Ghost should guide them into all truth; and the same spirit,
that did comfort, and guide, and lead all the believers into all truth;
he would reprove the world of sin, of righteousness,
and of judgment.`' Is not this sufficient to lead the world,
which reproveth them of their sin, because they do not believe in Christ,
and will not leave their own righteousness, and come to Christ for righteousness;
and reprove them of judgment, because the Prince of the world is judged; yea,
and through death Christ destroys the devil, the power of death,
and the world will not believe it.
So their condemnation is, because of their unbelief: but the Lord has promised,
in his holy mountain, to make unto all people a feast of fat things, a feast of wines, etc.
+++[+++mark, unto all people,]
and that '`the Lord would destroy in this mountain
the face of the covering cast over all people,
+++[+++mark, all people,]
and the veil that is spread over all nations,`' +++[+++mark, all nations.]
Isa. 25.

And also, the Lord saith, '`the earth shall be full of the knowledge of the Lord;
and the knowledge of the Lord shall cover the earth, as the waters cover the sea;
see Isa. 11:10-9.

This is the day of Christ, the Holy One; for he saith,
'`in that day there shall be a root of Jesse,
which shall stand for an ensign of the people, yea, an ensign for the nations,
and to it shall the Gentiles seek, and his rest shall be glorious.`'

Now, the covering cast over all people, and the veil cast over all nations,
the Lord is destroying, and the earth shall be full of his knowledge, and not only full,
but covered with the knowledge of the Lord, as the water doth cover the sea,
the prophecy of Isaiah, in chap. 40.
comes to be fulfilled, and the preaching of Zachariah, Luke 3.
'`every valley shall be filled, +++[+++mark, every valley,]
and every mountain and hill shall be brought low, (mark, every mountain, etc.)
and the crooked shall be made straight, and the rough shall be made smooth,
and all flesh shall see the salvation of God.`'

And doth not Daniel say, '`this stone, cut out of the mountain without hands,
smote the image of gold, silver, brass, iron, and clay, and brake them all to pieces,
that they became like the chaff of the threshing-floor, and the wind blowed them away,
that there was no place found for them?`' and this precious and elect stone,
Christ Jesus, that smote this image, became a great mountain, and filled the whole earth;
so this stone was without the handy work of man, and breaks the image to pieces,
that the wind drives them away, so that there is no place found for them in the earth;
and this glorious stone fills the whole earth.

Now, if the earth be filled with this stone, there is nothing wanting;
for God`'s promise was,
that '`the seed of the woman should bruise the serpent`'s
head,`' who is the god of the world,
that lies in wickedness; and all is concluded under sin; and all sin is of the devil;
for he sinned from the beginning: '`for this purpose the Son of God was manifested,
that he might destroy the works of the devil.`' 1 John iii.

And, as I said before, Christ, who through death, destroyed death, the devil,
who had the power of death, Heb. 2:14. and tasted death for every man,
and gave himself a ransom for all: and so, as the apostle saith to the Romans,
'`that God might have mercy upon all through Jesus Christ: for the apostle saith,
all have sinned, +++[+++mark, all,]
and judgment came upon all to condemnation; even so, by the righteousness of one,
the free gift came upon all men unto justification of life.`' Rom. 5.

So it is clear, as death passed over all men, and all have sinned,
Christ is a propitiation for the sins of the whole world, and not for the saints only;
and he tasted death for every man, and gave himself a ransom for all.
So is not that a devilish doctrine, that saith,
'`by the offence of one, condemnation and judgment came upon all men.`'
So that condemnation cometh by the transgression and offence;
but the apostle saith, as I said before, '`even so, by the righteousness of one, (to wit,
Christ Jesus,) the free gift came upon all men unto justification of life.`'

And Christ saith, in Mark 13:37. '`what I say unto you, I say unto all, watch.`'

Now, this doth manifest, that there was something of God, of his spirit, light,
and grace in them; else how could they watch against the enemy,
and wait for the appearance of Christ, who saith, '`my reward is with me,
to give every man as his works shall be,`' +++[+++mark, every man.] Rev. 22.

And Isaiah saith, Isa. 18:3. '`all ye inhabitants of the world,
and dwellers on the earth, see ye; when he lifteth up an ensign on the mountains,
and when he bloweth a trumpet, hear ye: the Lord hath prepared his throne in the heavens,
and his kingdom ruleth over all.`' Ps. 103:19.

And David saith, '`the Lord is good to all, (mark, to all,)
and his tender mercies are over all his
works;`' and '`all thy works praise thee, O Lord.`' Ps. 145:9.

Now, how can you say,
that the Lord hath ordained the greatest part of men and women for hell and condemnation;
when the Lord saith, '`he hath no pleasure in the death of a sinner,
he desireth not the death of a sinner, but that he would repent,
and turn to him and live.`'

So the Lord is good unto all, and his tender mercies are over all his works.

And in Micah 2:3. he saith, '`hear all ye people, hearken, O earth,
and all that is in it, and let the Lord be a witness against you,
the Lord from his holy temple,`' +++[+++mark, all people, and all that is in the earth.]
This doth manifest that there is something of God in all people,
by which they are to hear the Lord.

'`And Christ became the author of eternal salvation, to all that obey him.`' Heb. 5:9.

So it is clear, that it is disobedience and unbelief that brings condemnation.

And the apostle saith, '`praise the Lord, all ye Gentiles, and laud him,
all ye people.`' Rom. 15.

And David saith, '`praise the Lord, all ye nations; praise him, all ye people.`'

So here was no preaching by these of ordination of
people to condemnation before the world began;
but they are under condemnation that preach that doctrine;
and they are not like David and Paul, who preached,
that all nations and all people might praise the Lord;
this manifests that there is something of God in them.

For Peter saith, '`I perceive that God is no respecter of persons, (to wit,
of the Jews or Gentiles,) but in every nation,
he that feareth God and worketh righteousness,
he is accepted of him.`' So that it is not he that talks of righteousness,
but he that works righteousness, that is accepted. Acts 10:34-35.

And the apostle preached peace by Jesus Christ, who was Lord of all,
both of Jews and Gentiles; for Christ is Lord of the dead, as well as the living;
for he hath all power in heaven and earth given unto him.

For Moses confessed, Duet. 10:14. and said, '`behold the heaven,
and the heaven of heavens is the Lord thy God`'s, and the earth,
with all that therein is.`' So here it is clear that the
Lord has an eye over all his works in his tender mercies;
and, (as Christ saith,) '`not a sparrow shall fall to the ground without his will.`'

And the apostle saith, '`though there are diversities of opinions,
but it is the same God which worketh all in all.`'

Now, if people neglect this work and worker, and follow their own works,
then they come to condemnation.

And Christ hath set up his kingdom above sixteen hundred years since, and he must reign,
till he hath put all his enemies under his feet;
and he hath put all things under his feet in the general,
though as yet all things be not subdued unto him in the hearts of men;
but when all things shall be subdued unto him, then shall God be all in all, etc.

And again, the apostle saith to the Ephesians,
'`how that Christ is ascended far above all principalities, powers, and might,
and dominion; and every name that is named, not only in this world,
but also in that which is to come, '`and hath put all things under his feet,
and gave him to be the head over all things,
etc. and the fulness of him that filleth all in all.`'

And the apostle saith, '`there is neither Greek nor Jew, circumcision,
nor uncircumcision, barbarian, Scythian, bond, nor free,
but Christ is all and in all.`' Col. 3:11.

So mark, Christ is all, and in all these; the apostle tells you so.

And also, the apostle saith, '`for the love of Christ constraineth us;
because we thus judge, that if one died for all, then we are all dead;
and that he died for all, that they which live,
should not henceforth live unto themselves, but unto Christ, which died for them,
and rose again.`' 2 Cor. 5:14-15.

And the apostle saith in Heb. 10.
speaking of Christ, who saith, '`I come to do thy will, O God;
to take away the first covenant, that he might establish the second covenant;
by the which will we are sanctified,
through the offering of the body of Jesus Christ once for all.`' Mark,
once for all sacrifices, who ends them, and once for all the sins of the whole world,
who makes an end of sin, and finishes transgression,
and brings in everlasting righteousness, as in Daniel ix.

And the apostle saith, in Heb. 8.
speaking of the new covenant, '`that the Lord would put his laws in their minds,
and write them in their hearts, etc. and I will be to them a God,
and they shall be to me a people; and they shall not teach every man his neighbour,
to say know the Lord; for all shall know the Lord,
from the least to the greatest.`' Mark this; it is the days of the new covenant.

And in Acts 17.
the apostle saith, '`that God made the world, and all things therein,
and is Lord of heaven and earth, and dwells not in temples made with hands;
but your bodies are the temples of the Lord,`' as he tells the Corinthians:
'`and God is not worshipped with men`'s hands, who gives life, and breath,
and all things;
and hath made of one blood all nations of men to dwell on
all the face of the earth;`' and commandeth all men,
everywhere, to repent, because he hath appointed a day,
in the which he will judge the world in righteousness by Christ Jesus,
whom he hath ordained, whereof he hath given assurance unto all men;
(or offered faith,) in that he hath raised Christ from the dead.
So it is clear here, the Lord would have none to perish.
If by one offence, or the transgression of one, death reigned,
and had the authority upon all men, for all had sinned,
and so judgment came upon all men to condemnation; even so by the righteousness of one,
to wit, Christ, the free gift came upon all men to the justification of life.

So here was the first condemnation, and here is the free gift of righteousness,
(Christ,) that taketh away this condemnation; and they that do not believe in the light,
as Christ hath taught, are condemned with the light;
and they that do believe in the light, and are become children of the light, are saved,
as Christ hath taught.
For the Lord saith, '`look unto me, all ye ends of the earth, and be ye saved;
for I am God, and there is none else.`' Isa. 45:2.

For the Lord saith, '`I have sworn by myself,
and the word is gone out of my mouth in righteousness, and shall not return;
that unto me shall every knee bow, and every tongue confess, that Jesus Christ is Lord,
to the glory of God the Father.`' Phil. 2:11. Isa. 45:23.

And Daniel 7:13-14. speaking of Christ`'s kingdom; '`there was given unto him dominion,
and glory, and a kingdom,
that all nations and languages shall serve and worship him.`' Mark, serve Christ;
that must be in his light, grace, spirit, and truth, which is poured upon all,
and hath appeared unto all, and enlightens all;
and Christ`'s dominion is an everlasting dominion, which shall not pass away,
and his kingdom shall not be destroyed. Micha 4. 7. Luke 1:33. Daniel 2:34.

And David saith,
'`sing unto the Lord all the earth;`' then there is something in all the earth,
that giveth them a sense of the Lord: '`for the Lord visits the earth, and waters it,
and greatly enriches it with the river of God, which is full of water.`' Ps. 65:9.

And again, David saith, '`make a joyful noise unto God, all ye lands;
he ruleth by his power forever, his eyes behold the nations,
etc. all the earth shall worship thee, and shall sing unto thee.`' Psalm lxvi.
This must be in the spirit and truth, in the new covenant,
which is poured out upon all flesh.

And again, David saith, '`O God, let all people praise thee; oh!
Let the nations be glad and sing for joy; for thou shalt judge thy people righteously,
and govern the nations upon the earth, and all the ends of the earth shall fear God.`'

And do not you think,
that these prophecies and promises are to be fulfilled in the days of the new covenant?

And again, it is said, '`all the ends of the earth shall see the salvation of our God,
and make a joyful noise to the Lord; all the earth makes a loud noise,
and rejoice with singing.`'

Here is not some of the earth, but all the earth in this heavenly harmony:
and must not this be fulfilled in the days of the new covenant?

'`The Lord reigns, let the earth rejoice;
let the multitude of isles be glad thereof before the Lord;
for he cometh to judge the world with righteousness.`' Psalm 97. and 98. 3. 4.

And the apostle saith,
and shews the fulfilling of the prophecies of Isaiah concerning Christ, saying,
'`I have set thee to be a light to the Gentiles;`' in another place,
to enlighten the Gentiles;
that thou shouldst be my salvation to the ends of
the earth.`' Acts 13:47. Lam. 49:6.

So he that is the light, that lighteth every one that cometh into the world,
he is the salvation to them that believe in it, and therefore, Jude calls it,
'`the common salvation.`' And the apostle saith,
'`the gospel of salvation is preached to every creature under heaven.`'

And in the old covenant the Lord poured his spirit upon the house of Israel.
And in Ezek. 39. this was in the old covenant, to instruct them;
but in the new covenant God pours out of his spirit upon all flesh, as in Joel ii. Acts 2:17.
'`that all flesh might see the salvation of God.`' Luke 3:6.

And the first Adam was made a living soul,
and he died by eating of that which God forbid him, and so all died in Adam;
and the last Adam, Christ Jesus, was made a quickening spirit;
and it is he that quickens them that be dead in sins and trespasses,
and makes them alive; and his grace, which brings salvation, hath appeared to all men,
for them to believe in; and he doth enlighten every man that cometh into the world;
and he saith, '`I am the living bread, which came down from heaven;
if any man eat of this bread, he shall live forever; and the bread that I will give,
is my flesh,
which I will give for the life of the world.`' And
this made the professing Jews to stumble,
so it doth the christians without life:
for Christ doth not say that he will give his flesh for the life of the saints only,
but for the life of the world: for, by eating of that which God forbade, came death;
and by eating of that which Christ gives and commands, comes life:
so they remain in the death for want of believing and eating,
who came into death by disobeying and eating.

And the Lord said, '`I have no pleasure in the death of a sinner that dieth,
but that he might turn and live.`' And again the Lord saith,
'`have I any pleasure at all, that the wicked should die,
and not that he should turn from his evil ways and live?`'
This the Lord said to the Jews in the old covenant.
Ezek.
xviii.
And hath not he said much more in the new covenant?
For doth not Peter say, in his 2d epistle, chap.
iii. '`the Lord is not willing that any should perish,
but that all should come to repentance:`' +++[+++mark, all.]
So how dare any say,
that God willeth and ordaineth the greatest part of men and women for hell and condemnation,
and willeth it so to be.
And the apostle exhorted Timothy to instruct those that did oppose themselves, if God,
peradventure, would give them repentance, to the acknowledging of the truth,
that they might be recovered out of the snare of the devil,
that took them captive at his will, etc.
So here was a possibility.

And also, Christ sent his disciples to preach repentance;
and Christ upbraided the cities, because they repented not.
Matt. 11. Mark 6:12.

And the apostle said, '`they preached repentance at Damascus, and at Jerusalem,
and throughout all the coasts of Judea, and then to the Gentiles,
that they should repent and turn to God,
and do works meet for repentance.`' So he testified and preached repentance,
both to Jews and Greeks, that they might have faith in the Lord Jesus Christ.
Acts 10. 16.

And the Lord gave Jezabel a space to repent, but she repented not. Rev. 2.

And God poured out his plagues upon the worshippers of idols,
and the works of their hands, and for their theft, murder, fornication, and sorcery,
but they repented not. Rev. 11.

And the Lord poured out of his vials of wrath upon the beast and his worshippers,
which had shed the blood of the saints, and they repented not to give glory to God:
so here was a warning for them to repent. Rev. 16.

And Christ doth encourage to repentance; '`for he saith,
that joy shall be in heaven over one sinner that repenteth,
more than over ninety-nine just persons, that need no repentance.`' Luke 15:7.

And the apostle saith to the Romans, '`there is no difference between the Jews,
and the Gentiles, and the Greeks; for the same Lord is over all,
and rich unto all that calleth upon him.`' But the apostle saith,
'`how should they call upon him whom they have not heard or believed?`'
But the apostle answers his own question again,
and saith, '`have they not all heard?
Yes, verily; but they have not all obeyed; for their sound went out into all the earth,
and their words unto the ends of the world.`' Rom. 10.

So you may see the disobedience of Adam, the disobedience of the Jews,
and the disobedience of the christians that grieved the Lord, his prophets,
and his apostles, and brought misery upon themselves.

And the apostle speaking of the unconverted estate both of Jews and Gentiles,
how that '`they were all gone out of the way; and there was none that did good,
no not one; +++[+++mark all,]
that God might have mercy upon all.`' +++[+++mark, upon all.]
And is not the God of truth the God of the Jews, and the God of the Gentiles?
So the righteousness of God, which is by the faith of Christ Jesus, unto all,
and upon all them that believe?
For there is no difference; for all have sinned,
and come short of the glory of God in their unconverted estate;
for the apostle preached Christ the hope of glory to the saints;
and they warned every man, and teaching every man,
etc. that they might present every man perfect in Christ Jesus, Col. 1:28.
for they were imperfect, in old Adam, in transgression,
though Adam was perfect before transgression;
so it was the work of the ministers of Christ to
bring every man out of the transgression of old Adam,
where they were imperfect, and to present them perfect in Christ Jesus.
So if God had willed and ordained the condemnation of some men before the world began,
it was in vain for the apostle to warn every man to repent, and teach every man,
that they might present them perfect in Christ Jesus; and the apostle said,
that he witnessed both to small and great, saying,
'`no other things than those which the prophets and Moses did say,
should come,`' speaking of Christ in his general doctrine.
Acts 6.
And Christ said to his disciples, '`behold, (or take notice,) I give unto you power,
to tread upon serpents and scorpions, and over all the power of the enemy,
and nothing by any means shall hurt you.`' Luke 10:19. And Christ
the Son of man is come to save that which was lost. Matt. 18:11.
He that hath an ear, let him hear.
So it seems here was something lost, by the fall of man.
And the Samaritans said unto the woman, '`now we believe, not because of thy saying,
for we have heard him ourselves, (to wit, Christ,)
and know that this is indeed the Christ,
the Saviour of the world.`' And Jesus himself testified,
that a prophet had no honour in his own country.
And Christ saith, '`I came not to judge the world, but to save the world;
I am come a light into the world, and whosoever believeth in me,
shall not abide in darkness.`' John 12:47. And John saith,
'`we have seen and do testify,
that the Father hath sent the Son to be a Saviour of the world.`' 1 John 4:14.
And '`whosoever shall confess that Jesus is the Son of God,
dwelleth in him, and he in God.`' +++[+++mark, whosoever.]

And the apostle saith, '`we trust in the living God, who is the Saviour of all men,
especially of them that believe; these things command and teach,`' etc. 1 Tim. 4:10.

And the apostle saith, how that '`Christ hath made peace by the blood of his cross,
and by him to reconcile all things to himself, I say, whether they be things in earth,
or things in heaven.`' And the apostle saith,
'`that the gospel was preached to every creature under heaven, whereof,
I Paul am made a minister.`' Col. 1:20,23.

Where are the ministers nowadays,
that have the gospel which is preached to every creature under heaven,
in which gospel the saints are to be settled and grounded,
and be not removed from this gospel which is preached to every creature under heaven?
those that say,
that God hath ordained the greatest part of men and women for hell and condemnation,
have not this gospel to preach to such creatures.

And the apostle saith, '`that Christ might reconcile both Jews and Gentiles unto God,
in one body, by the cross, having slain the enmity,
and so preached peace unto them which were afar off, and to them that are nigh,
and to make in himself of twain one new man, and so making peace,
that through one Christ we both (to wit,
Jews and Gentiles,) have an access by one spirit unto the Father.`' Eph. 2:16-17.

And Christ saith, '`behold, (or take notice,) I make all things new,`' Rev. 21. and 2 Cor. 4.
the apostle saith, '`old things are passed away, behold all things are become new,
and all things are of God, who hath reconciled us to God, through Jesus Christ,
and hath given to us the ministry of reconciliation, (to wit,) that God was in Christ,
reconciling the world to himself, not imputing their transgressions to them;
for Christ was made to be sin for us, who knew no sin,
that we might be made the righteousness of God in him.`'
So Christ gave himself to purchase and redeem man,
and so is a purchaser and a redeemer, and gave himself a ransom for all.

And the apostle saith, '`if the casting away of the Jews be the reconciling of the world,
what shall receiving of them be, but life from the dead.`'
Rom. 11. He that hath an ear to hear, let him hear.
And again, doth not the apostle say, '`in due time Christ died for the ungodly?`' Rom. 5.
so he did not die for the saints only.

And again, doth not the apostle say, '`when we were sinners,
Christ died for us?`' and so it is clear, Christ did not die for the elect only.
And the apostle saith, '`I will, therefore, that men pray everywhere,
lifting up holy hands without wrath and doubting.`'

So if men must pray everywhere, it must be in the spirit,
as the apostle exhorteth in another place, to pray in the spirit;
and they must be holy hands that must be lifted up to the Holy God; not bloody hands,
nor fists of wickedness.

And the grace of God, which brings salvation, having appeared to all men,
which teaches them how to live, and what to deny;
and Christ lightening every man that cometh into the world, saith,
'`believe in the light while ye have it:`' and God
poured out of his spirit upon all flesh,
so that in this spirit men might pray, and serve,
and worship the God of truth in spirit and in truth.

They that make sects, are the breeders of enmity; but God and Christ makes no sects,
neither doth his grace, which brings salvation, that hath appeared to all men;
neither doth his light and life, with which he enlightens all; neither doth his spirit,
which he pours upon all flesh; neither doth Christ in his death,
who tasted death for every man, and gave himself a ransom for all.

The Son of God was manifest to destroy the works of the devil, the destroyer. 1 John 3:8.

The Son of man is not come to destroy men`'s lives, but to save them. Luke 9:56.

So they that deny the Lord that bought them, bring upon themselves swift destruction. 2 Pet. 2:1.

[.signed-section-signature]
G+++.+++ F.
