== A Distinction Between the New Covenant and the Old

[.heading-continuation-blurb]
And how that in the Old Covenant,
the Jews`' Priests`' Lips were to Preserve the Jews`' People`'s Knowledge:

[.heading-continuation-blurb]
But in the New and Everlasting Covenant,
Christ the High Priest, is the treasure of Wisdom and Knowledge,
and he filleth the Earth with the Knowledge of the Lord God;
and the Earth being full of the Knowledge of the Lord God,
then there is no want of it in the Earth.
And Christ the High Priest,
he doth not only fill the Earth with the Knowledge of the Lord God,
but covereth the Earth with the Knowledge of the Lord, as the Waters do the Sea;
so the Earth shall not be seen.
So then it may be seen that the Substance in the New Covenant,
is far beyond the Figure in the Old Covenant.

[.heading-continuation-blurb]
Read, hear, perceive, and understand, receive and possess.--By G. F.

It is written in the prophecies of Isaiah, (ch. 11.)
where speaking of the peaceable kingdom of Christ, that was to come, he saith,
'`they shall not hurt, nor destroy in all my holy mountain;
for the earth shall be full of the knowledge of the Lord,
as the waters cover the sea.`' So this was a prophecy of that day to come;
it was not in the days of Isaiah.

But mark, '`in that day (when the earth shall be full of the knowledge of the Lord,
as the waters cover the sea.`') In that day there shall be a root of Jesse,
which shall stand for an ensign of the people, to it (to wit,
this ensign,) shall the Gentiles seek, and their rest shall be glorious.
Now many of the Gentiles have found this glorious rest, and this ensign;
and to this ensign do the people gather, and cannot forsake it;
and all the warriors in the world cannot pluck down this ensign,
nor take it from the people with their carnal weapons.

Now this is the day of Christ in his new covenant of light, life, and grace,
in which the '`earth shall be full of the knowledge of the Lord,
as the waters do cover the sea.`' +++[+++Mark,]
'`The earth shall be full of the knowledge of the Lord.`' So then the earth is not empty,
when it is '`full of the knowledge of the Lord,`' And '`the knowledge
of the Lord shall cover the earth;`' it shall not only be full of it,
but it shall cover the earth, so as the earth shall not be seen.
'`As the waters do cover the sea,`' that when you
are in the sea you cannot see any land or earth;
so shall the knowledge of the Lord be in the new covenant.

For the Lord saith, '`I will write my laws in their hearts, and put them in their minds,
that they shall not need to say unto one another, know the Lord,
for all shall know me from the greatest unto the least.
And they shall not need every man to teach his neighbour, saying, know the Lord.`'

Now mark, if there be no need to say one unto another, or unto their neighbour,
'`know the Lord,`' (for the earth shall be full of the knowledge of the Lord;
and the knowledge of the Lord shall cover the earth,
as the waters do the sea,`' in the new covenant of light, life, and grace;
so that the earth cannot be seen,) then there is no need of the
priests`' or teachers`' lips to preserve the people`'s knowledge;
for that was only used in the old covenant under Moses: and whilst he was read,
the people were under the veil.
And, therefore, Christ abolished the first priesthood with his veil,
who had the tithes for his work and service,
whose '`lips were to preserve the people`'s knowledge;`' that was the people of the Jews,
that particular nation.
But Christ in the new covenant is the treasure of wisdom and knowledge;
so that in this day of Christ,
the root of Jesse shall stand up as an ensign for the people;
and the Gentiles shall seek it, to wit, the nations, which many have found.

And God hath given Christ for a new covenant to the Jews, not according to the old,
and for a covenant of light, to enlighten the Gentiles also,
who is God`'s salvation to the ends of the earth: that so in this day of Christ,
(and salvation,) who is a high priest, holy and harmless, and separate from sinners,
made higher than the heavens, who is the treasure of wisdom and knowledge;
he takes away the veil of Moses,
and takes away the veil and covering that hath been spread over all nations.

So it is Christ that fills the earth with knowledge,
and that the '`knowledge of the Lord shall cover the earth,
as the waters do the sea;`' so that in this knowledge,
to know God and Christ Jesus whom he hath sent, is eternal life.

So this high priest, Christ Jesus, his work is beyond the Jews`' high priests,
whose '`lips were to preserve the Jewish nation`'s knowledge;`'
for Christ the treasure of wisdom and knowledge,
fills the whole earth with knowledge; '`and covers the earth with the knowledge of God,
as the waters cover the sea,`' in his day of the new covenant.
And are not these the days of the new covenant, and the gospel,
which is not according to the old?
and then what will all you priests (that are made at schools
and colleges,) and bishops do in this day,
with all your fat bishoprics and parsonages,
when that people need not be taught by you the knowledge of the Lord?
Nor need the people send their children to schools and colleges, to learn there the arts,
and how to teach people the knowledge of the Lord,
when '`the earth shall be full of the knowledge of the Lord,`' and covered with it,
as the waters do cover the sea, in the days of this new covenant:
so then there will be no need of your teachings.
And if you come to receive this day in your time,
then would not you forsake your fat benefices and parsonages,
and return unto people their tithes,
and confess that Christ who is the treasure of wisdom and knowledge, in the new covenant,
saith, '`freely you have received,
freely give;`' and this commandment of the Lord of lords is not to be broken; and say,
there is no need in the new covenant to teach people to know the Lord, no,
not '`from the least to the greatest of them.`'
For God hath written his law in their hearts,
and put it in their minds, in the days of this new covenant; and they are God`'s people,
and he is their God, and they all know him from the greatest to the least of them:
So that this new covenant is not according to the Jews`' old covenant,
amongst that particular nation of the Jews, who had a tribe of priests and Levites,
whose '`lips were to preserve the people`'s knowledge,`'
for which they had their tithes.
But Christ is come in his new covenant, and hath taken away the first covenant,
and abolished it, and disannulled the commandment that gave him his tithes;
and establishes the second and everlasting covenant, where all shall be taught of God,
and saith to them that declared this new covenant, and preached his gospel,
'`freely you have received,
freely give;`' and they were to go and declare this without bag or staff.

So in the new covenant they had no need of purse, silver, bag, or staff;
for they that preached the gospel, lived of the gospel.
So the gospel of life and salvation is good news and glad tidings,
being preached to and in every creature under heaven; and the grace of God,
which bringeth salvation, hath appeared unto all men to teach them:
and Christ doth enlighten every man that cometh into the world, with the life in him,
the word, by which all things were made to believe in, and to give them knowledge.
So this high priest is he,
that filleth and '`covereth the earth with the knowledge of the Lord,
as the waters cover the sea,`' so that the earth shall not be seen;
and so he both '`gives and preserves the people`'s
knowledge.`' And in these days of Christ,
in his new covenant, God poureth out his spirit upon all flesh, to instruct, teach,
and lead them, by which spirit '`sons and daughters may prophesy,
and the old men may dream dreams, and the young men, and hand-maids,
and servants may see visions,`' by the spirit which God hath poured upon them,
and hath given them a spiritual knowledge,
and which spirit reveals the things of God unto them, and leads them into all truth.
For in the old covenant the Lord poured out his spirit upon the house of Israel,
and gave them of his good spirit to instruct them, though they rebelled against it;
but in his new covenant, which is not according to the old,
he pours out of his spirit not only upon the Jews, but upon all flesh of other nations,
as well as the Jews, that all flesh may see the glory of God, and see their salvation.
For the Lord saith, in Isa. 49:26. '`all flesh shall know, that I, the Lord,
am thy Saviour and Redeemer, the mighty one of Jacob.`' And again,
in Isa. 40:5. the Lord saith, '`every valley shall be exalted,
and every mountain and hill shall be laid low, and the crooked shall be made straight,
and the rough plain; and the glory of the Lord shall be revealed,
all flesh shall see it together,
for the mouth of the Lord hath spoken it.`' And is
not this the gospel-day of Christ in his new covenant?
And must it not be fulfilled?
But your mountains and hills must be laid down,
and your crooked ways and natures must be made straight, smooth, and plain,
before this glory of the Lord be revealed, and that all flesh come to see it.

And in Luke 3:6. it is said, where he speaks of the fulfilling of Isa. 40.
how '`all flesh shall see the salvation of God.`' Again, Isa. 66:18,26.
the Lord saith, '`all flesh, shall come to worship before me:
and the Lord saith, it shall come to pass, that I will gather all nations and tongues,
and they shall come and see my glory,
and I will set him for a sign among them,`' speaking of Christ.
And the Lord saith, '`his people`'s wilderness shall be like Eden,
and their desert as the garden of the Lord.`' Isa. 51:3.
And are not these the days Of the new covenant,
and to be fulfilled?

[.signed-section-signature]
G+++.+++ F.

[.signed-section-context-close]
Swarthmore, the 4th month, 1679.
