[#ch22.style-blurb, short="A Warning to Beware of Covetousness"]
== A Warning to all that profess Christianity, and others, to beware of Covetousness, which is Idolatry.--By G. F.

All people that do profess Christ, and christianity, this is a warning to you all,
to take heed of covetousness;
for covetousness was forbidden both in the Old Testament and the New,
and by the law of God, and by Christ and his apostles.

For the apostle saith, '`covetousness is idolatry;`' and both to the rulers, priests,
teachers, and people in the Old and New Testament,
that idolatrous practise was forbidden.

And Christ saith, '`it is one of those evils that defiles a man, that comes out of him.`'

And the Lord said in his law, and ten commandments,
'`thou shalt not covet thy neighbour`'s house,
thou shalt not covet thy neighbour`'s wife, nor his man-servant, nor his maid-servant,
nor his ox, nor his ass, nor any thing that is thy neighbour`'s.`'

Now, if this covetous spirit be kept down, then the idolator is kept down,
and that idol out of the heart.

Also, theft and stealing was forbidden in the old covenant, and so it is in the new;
and all are to labour in the thing that is good.

Likewise, adultery was forbidden in the old covenant, and so it is in the new; yea,
and more than outward adultery: for,
'`he that looks after a woman to lust after her,`' in the new covenant, Christ saith,
'`he hath committed adultery with her already in his heart.`'

And '`bearing false witness against his neighbour,`' was forbidden in the old covenant,
and so it is in the new?
For all are to speak truth to their neighbour, and lie not.

And the Lord saith, in the Old Testament, '`thou shalt not kill.`'

The apostle saith, in the new covenant, '`they did not wrestle with flesh and blood;
and their weapons were not carnal,
but spiritual;`' and Christ forbids wrath in the new covenant, etc.

And Samuel, who was a judge and a prophet, who judged Israel, 1 Sara.
xii. 3. Samuel said, '`I am old and gray-headed,
and I have walked before you from my childhood unto this day;
whose ox or ass have I taken?
Or whom have I defrauded or oppressed?
Or of whose hand have I received any bribe to blind my eyes
therewith?`' And the children of Israel answered and said,
'`thou hast not defrauded nor oppressed any of us,
neither hast thou received ought at any man`'s hand.`' etc.

Now here was a prophet, and a priest, and a judge,
clear from that idolatry of covetousness;
and hath not he outstripped many of them which now call themselves prophets and priests,
judges and teachers, that profess the new covenant?

And David said, '`incline my heart unto thy testimonies,
and not to covetousness.`' Ps. 119:36.

So, if the hearts of all who profess christianity,
were inclined to the testimony of Jesus, the spirit of prophecy,
that would keep down the earthly spirit of covetousness, which is idolatry.

And as Solomon saith, in Prov. 28:16. '`he that hateth covetousness,
shall prolong his days.`' Then he that loveth covetousness, which is idolatry,
shall not prolong his days.

And Jeremiah cried out against the Jews in the old covenant, and said,
'`from the greatest to the least of them, the prophet and the priest,
every one of them was given to covetousness,
and to deal falsely.`' Jer. 6:13. and Isa. 56:11.

And yet, these priests and prophets, from the greatest to the least of them,
could make a profession of the old covenant.

And let the priests, and prophets, and people, that profess the new covenant,
see if they be not given to this idolatry of covetousness,
which was hated and forbidden of God and Christ, and his people, prophets, and apostles.

And Jeremiah further cries out against the Jew, in Jer. 22:17. and said unto them,
'`thine eyes and thy heart are for thy covetousness, and for shedding of innocent blood,
and for oppression, and for violence.`'

Now this was the Jews condition in the old covenant, when they forsook God,
and his law and spirit.

And now, let all who profess themselves christians, in whom Christ doth not reign,
which are not guided by the spirit of God, as the prophets and apostles were,
search and try themselves, if the fruits of their eyes and hearts,
and the fruits of the spirit that was in the Jews, doth not appear,
and is manifest in them, a spirit that lusts to do violence and oppression,
and a spirit of covetousness, and of persecution, and of shedding innocent blood,
which was forbidden by God and his prophets in the old covenant,
and by Christ and his apostles in the new covenant,
and by them abhorred and cried out against.
But what was the end of the Jews which followed after that wicked spirit,
and went from the Lord?

And do those called christians, think in their profession of the new covenant,
that they must have liberty in these evil things now,
which were forbidden in the time of the old law and covenant?
No, no; they are much more forbidden in the new.

And the Lord said unto Ezekiel,
'`that the Jews would come and sit before him as the Lord`'s people,
and they would hear his words, but they will not do them;
and with their mouths they would show much love,
but their hearts went after their covetousness.`' Ezek. 33:31.

Now will not the priests and professors of Christendom,
hear and say the words of the new covenant and gospel,
and appear to show much zeal and love for the words of the New Testament,
but they will not do them nor practice them;
for their hearts and eyes go after their covetousness, which is idolatry.

For have not you, that profess the new covenant in words,
done as they that professed the old in words, even coveted goods, fields, houses,
and taken by violence, and oppressed a man in his heritage, and devised iniquity,
and wrought evil upon your beds, and in the morning-light have practised it,
because you had power in your bands?

And was not woe pronounced against such, that professed the old covenant,
and yet walked contrary to it; and much more against all such,
as are found in these practises now, who profess the new.
Micha ii.

And Habakkuk cries, '`woe to him that covets an evil covetousness to his house,
that he may set his nest on high,
that he may be delivered from the power of the evil,`' etc. Hab. 2:9.
he tells them, '`the stone shall cry out of the wall,
and the beam of the timber shall answer it against them.`'

And therefore, let such covetous persons, that profess christianity, hearken and hear,
if the stones out of the very wall do not cry out against you,
and the beam of the timber does not answer it?

And Christ saith, in Mark 7.
'`that which cometh out of the man from within his heart, defileth the man,
(to wit,) evil thoughts, adultery, fornication, murder, theft, covetousness, wickedness,
deceit, blasphemies, pride, foolishness,
and an evil eye:`' now these are the evils that defile men, which the devil, the serpent,
who is out of the truth, hath wrought in man`'s heart, both in Adam and Eve,
and the Jews, and the christians that go from God, and disobey his voice and command:
for neither God nor Christ wrought any of these evil things in man in the beginning,
nor since, who is the author of all good.
And therefore,
these evil things must be purged out of man by Christ`'s blood and baptism,
and by the mortification and circumcision of the spirit of God.

And Christ said unto them, (to wit, the Jews,) '`take heed and beware of covetousness;
for a man`'s life consists not in the abundance of
the things which he doth possess.`' Luke 12:15.

Oh! that all that are called christians, and all people,
would consider this blessed doctrine of Christ the heavenly man;
and that they might come to understand and know what their life doth consist in;
then they would take heed and beware of covetousness, which is idolatry.

And the apostle Paul, who had the care of the churches upon him,
he writes to the Corinthians,
'`not to keep company with any man that is called a brother, that is a fornicator,
or covetous, or idolater, or railer, or a drunkard,
or an extortioner;`' with such an one they were not so much as to eat:
for such as professed christianity, and followed such practises,
the saints were neither to eat nor keep company with;
for they shamed their profession of christianity.

So here the apostles and saints, the true church, had a judgment given them,
and did judge out the covetous idolaters, fornicators, drunkards, railers,
etc. from having any fellowship with the saints, the true church,
not as much as to eat with them, nor to keep company with them of that spirit:
for he saith, '`neither fornicators, nor thieves, nor drunkards, nor covetous idolaters,
railers, nor extortioners, etc. shall inherit the kingdom of God.`'

And the apostle told the Corinthians, that '`such were some of them,
but they were washed, sanctified, and justified from these things,
in the name of the Lord Jesus Christ,
and by the spirit of God.`' So these were washed from their fornication, covetousness,
idolatry, drunkenness, railing, and extortion, and justified in the name of Jesus,
and by the spirit of God.

So the apostle here doth not speak of the fornicators, and covetous idolaters,
and extortioners of the world, which were without; for God judgeth such.
But the saints, the apostles,
and the true church were to judge them that practised such things within the church,
showing the true Christian`'s church had a power;
and not to keep company nor to eat with such, professing Christ,
that were of such practises,
knowing that the unrighteous should not inherit the kingdom of God, nor drunkards,
nor fornicators, thieves, railers, extortioners, nor covetous idolaters;
they that lived in these evils, were not like to inherit the kingdom of God;
for they were defiled, unwashed, and not sanctified nor justified, etc.
So that if the saints did keep company, or did eat with such unwashed, unsanctified,
unjustified persons, or have fellowship with them,
they took the members of Christ and joined them to an harlot;
for he that is joined to an harlot, is one body; '`for two,`' saith he,
'`shall be one flesh.`' And therefore, the saints`' bodies are members of Christ;
God forbid they should be joined to harlots,
or that they should make them members of an harlot.
'`And he that is joined to the Lord,
is one spirit:`' And the saints`' bodies are the temples of the Holy Ghost,
which proceeds from God and Christ, and being bought with a price, the blood of Christ,
and washed, and sanctified,
and justified in the name of Jesus Christ by the spirit of God,
they are to glorify God in their bodies, souls, and spirits, which are God`'s,
which he hath given to them to glorify him withal; glory to his name forever.

And therefore, all this old leaven of fornication, adultery, theft, covetousness,
idolatry, drunkenness, revelling, extortion, and all unrighteousness, envy, malice,
and wickedness, must be purged out,
which is the world`'s god the serpent hath wrought in, that they may be a new lump,
and keep the feast of unleavened bread of sincerity and truth: for Christ, our passover,
is sacrificed for us, as you may see in 1 Cor. 5. 6.
the practice of the church in the apostles`' days, and which should be so now,
to keep this heavenly passover with unleavened bread of sincerity and truth.

And further, the apostle tells the church of Corinth, in 2 Cor. 6.
and explains himself with a great care of the church,
that they must not be unequally yoked together with unbelievers.
So this is an unequal yoke, to yoke believers and unbelievers together;
and giveth his reason, and saith,
'`what fellowship hath righteousness with unrighteousness?
And what communion hath light with darkness?
And what concord hath Christ with Belial?
Or what part hath a believer with an infidel?
And what agreement hath the temple of God with idols?`'

Now, they that go contrary to the apostle`'s doctrine in these things,
have lost their sense, and sight, and feeling; for here is no fellowship, nor unity,
nor concord; here is no agreement, nor part with such aforementioned,
that are out of the truth;
but they are unequally yoked with such who are the temples of the living God,
that join with them; they in whom God doth dwell and walk, and he is their God,
and they are his people.

'`Wherefore, come out from amongst them, and be ye separate, saith the Lord,
and touch not the unclean thing, and I will receive you, and I will be a father unto you,
and ye shall be my sons and daughters, saith God Almighty.`' Here you may see,
what the saints, the sons and daughters of God, are to forsake, and not to touch,
nor make agreement with, nor be yoked to, but be separated from,
that the Lord God Almighty may receive them.

And again, the apostle writes to the Ephesians 4:25. '`that they should put away lying,
and every man speak the truth to his neighbour; for they are members one of another:
and him that had stolen, steal no more; but let him labour,
working with his hands the thing that is good.
And let no corrupt communication proceed out of your mouths, but that which is good,
tending to edification, which may minister grace to the hearers: and all filthiness,
foolish talking and jesting, which was not convenient,
was to be put away.`' And the saints, the church of Christ,
was not to have any fellowship with such things, the unfruitful works of darkness,
but rather reprove them.
'`And fornication, and all uncleanness, and covetousness,
let it not be once named amongst you, as becometh saints.
For this you know, (to wit, the saints, the church of Christ,) that no whoremonger,
nor unclean person, nor covetous man, which is an idolater, +++[+++mark, covetous,
that is an idolater,]
hath any inheritance in the kingdom of Christ and
of God.`' Here the church of Christ had their knowledge,
and had their judgment to judge out these things,
that kept people out of the kingdom of God.
And now mark, '`if a covetous man be an idolater,`' as the apostle saith,
then all '`covetous men are idolaters, and shall not inherit the kingdom of God.`'

And now, let all those that are called priests, teachers, ministers,
and prophets in Christendom, see if their fruits do not declare them to be covetous,
and so idolaters,
who preach Christ and the apostles`' (and seem to have a zeal for their) words;
but how many of them will preach without tithes and hire?
And if people will not give it unto them, then to spoil their goods,
and cast them into prison, yea, till death, as many have been,
because they would not hold up and feed that idolatrous spirit of covetousness in them.
When as the apostle commands the church, not '`so much as to have fellowship,
nor company, nor to eat with a covetous person, which is an idolater.`'

And now, if the saints, the true church of Christ, must not eat,
nor keep company with such, then how must they hear them,
or be compelled or forced to hear such?
And knowing that Christ said to his ministers,
whom he sent forth '`freely they had received,
freely they were to give;`' and they were '`neither to provide silver nor gold,
nor bag nor scrip; but to enquire who was worthy of their message;
and what was set before them, that they were to eat; and such as were unworthy,
that would not receive them and their message,
they were to shake the dust off their feet,
which should be a witness against them at the day of judgment.`'
And the apostles did not cast those unworthy ones,
that would not receive them, and set meat before them, into prison,
as some of your ministers do the people of God, because they cannot uphold your covetous,
idolatrous spirit, in giving you tithes and hire.

And now, all you that will not preach Christ`'s and the apostles`' words,
nor pray amongst people, or give them psalms to sing, and sing among them,
and baptize children, (as you call it,) or sprinkle them,
without the tenths of people`'s increase of their labours,
and without the tenths of the increase of their cattle and goods,
and have set wages by the year for these things; are not you the covetous idolaters?
Yea, and cast people into prison, and spoil their goods,
and excommunicate them whom you do none of these works for,
neither have they set you at work, nor hired you to do any of these things for them:
for do not most people, everywhere, generally hire you,
and agree with you for so much in the year?
Or do not you make friends with great persons, to put you into fat benefices?
And instead of enquiring where the worthy people are, are not your priests enquiring,
where is the greatest benefices, and most tithes and incomes?
And then, when you are settled, do not you spoil the goods, and cast into prison,
such as never hired you nor hear you?
and is not this contrary to the general command of Christ to his disciples,
both to the twelve and the seventy?
'`Freely you have received, freely give,`' etc.
So is it not manifest here,
that you are covetous idolaters that the apostle speaks against,
'`that shall not enter into the kingdom of God.`'

For Peter in his 2d general epistle, 2 Pet.
ii. speaks of the false prophets and false teachers,
and how '`many should follow their pernicious ways,
by reason of whom the way of truth should be evil
spoken of;`' which truth the apostles preached freely,
as they had received freely, according to the command of Christ.
And these false prophets and teachers through covetousness
should with feigned words make merchandize of people.
For how often have the teachers changed their places and ways?
the apostle compares such with the old world, and Sodom,
and fallen angels that kept not their habitation.
And therefore, let the teachers in Christendom,
who cast into prison and spoil people`'s goods for their bellies,
examine and see if they be not the men.

And also, the apostle writes to Timothy, in 2 Tim.
iii. of such '`covetous proud boasters, and false accusers,
and fierce despisers of them that were good, and which were heady,
high-minded lovers of pleasures more than lovers of God; that had the form of godliness,
(which was the form of christianity,) but denied the power thereof; from such the saints,
(the true church,) were to turn away.`' For he likened them to Jannes and Jambres,
that withstood Moses, who were men of corrupt minds, and did resist the truth,
and were reprobate concerning the true faith;
these led such captive who were laden with sins, and led about with divers lusts,
'`always learning,
and were never able to come to the knowledge of truth;`' and how should they,
being destitute thereof themselves, and men of corrupt minds,
bring any into the truth and the faith, when they are out of the true faith themselves,
and tell people,
'`they must carry a body of sin and death to the grave with them;`' and others say,
'`they must have a purgatory when they are dead:`' and such
are reprobate from the apostle`'s doctrine and faith,
which is the victory, and in the damnable heresy.
But the apostles exhorted the saints, '`to walk in the light,
and the blood of Jesus Christ should cleanse them from all sin.`'

And the apostle told the church, '`that they were washed, cleansed, sanctified,
and justified,`' etc. and this was whilst they were upon the earth.
And he tells the Ephesians, the saints, '`you that were sometimes darkness,
now are you light in the Lord.`'

And the apostle writes to Timothy, 1 Tim. 5.
'`having, food and raiment, let us therewith be content;
and godliness with contentment is great gain: but they that will be rich,
fall into temptations and snares, and into many foolish and hurtful lusts,
which drown men in destruction and perdition:
for the love of money is the root of all evil, which while some coveted after,
they have erred from the faith, and pierced themselves through with many sorrows.
But thou, O man of God, flee these things, and follow after righteousness, godliness,
faith, love, patience, meekness.
This is the man of God`'s path, and to flee covetousness, and the love of money,
and such as make gain their godliness; for such are destitute of the truth:
and this should be the practice of all true Christians now.

And do not the men of the world, with the covetous priests and teachers, and others,
fly after riches and money, instead of flying from it?
And after gain supposing it to be godliness?
And is not this a mark, that such have erred from the true faith,
and are fallen into hurtful lusts, which drown them in destruction and perdition,
by falling into a temptation Hath not the root of
this evil been manifest by the teachers of the world,
and other people?
The priests and teachers by destroying people for their bellies;
and the people by coveting and encroaching other people`'s goods,
and so destroy their own and others too: the teachers and others showing,
that they are erred from the faith which Christ is the author and finisher of, who saith,
'`freely you have received, freely give;
and beware of covetousness.`' For the apostle saith, '`a bishop must not be a striker,
nor greedy of filthy lucre, nor a brawler, nor covetous;
but he must hold fast the faithful word, and be blameless:`' and such bishops and elders,
teachers and deacons, were Timothy and Titus to ordain,
as you may see, in 1 Tim. 3. and Titus 1.
And they were to hold the mystery of faith in a pure conscience:
and therefore, how can any bishops and teachers,
elders or deacons be the succeeders of them, that the apostles, and Timothy,
and Titus ordained, that are strikers, persecutors, covetous and greedy of filthy lucre,
yea, and cast people into prison whom they do not oversee, nor teach, nor preach to?
Are not such erred from the faith, the evil beasts and slow-bellies,
that suppose gain to be godliness, that serve not the Lord Jesus Christ,
but their own bellies, which the apostle bid Titus,
'`rebuke sharply.`' And now you may see such as coveted to be rich,
and were persecutors and strikers, and greedy of filthy lucre,
such Timothy and Titus were, not to ordain bishops and teachers, elders and deacons;
for such were erred from the faith;
then they were not like to hold the mystery of faith in a pure conscience,
which Christ is the author and finisher of, who saith, '`freely you have received,
freely give.`' For the apostle, in Acts xx.
saith, '`that he was pure from the blood of all men;`' he took the church to record,
'`that he had coveted no man`'s silver, gold, nor apparel;`' and said,
'`that the church knew themselves, that his hands had ministered unto his necessities,
and them that were with him.`' Now here was a clear free minister of Christ.
And now let the bishops, priests, and teachers, etc. in Christendom,
try themselves and their practice by the scripture, and the apostle`'s example,
and the command of Christ, who saith, '`freely you have received,
freely give.`' Can you say, that you have coveted no man`'s silver, gold, nor apparel,
either of your own people, nor others, whom you have not preached to?
Can you say, you are clear from the blood of all men, as the apostle said,
and call the christians to record?
If you do say you are; will not the jails testify against you, and the courts,
and your own hearts and consciences also will witness against you?
And how many have been persecuted and prisoned by you till death,
for not giving you money and tithes, whom you do not work for?
What persecuting and hauling before courts have you made?
You cannot call the christians to record, '`that you are clear from the blood of all men,
that you covet no man`'s silver, gold, nor apparel,
and that you labour with your hands for your own necessities and others,
and that you are not greedy of filthy lucre, and are not strikers and persecutors,
nor are they that covet after money and the riches of this world;
and that you do not give freely,`' as Christ commands,
manifesting that you have not received freely from him;
but that you are erred from the faith of Christ,
(by which the apostles lived,) and from the conversation
of the saints in the primitive times.
For the apostle saith to the church, '`let your conversation be without covetousness,
and be content with such things as you have.`' And the Lord saith,
'`I will never leave thee, nor forsake thee.`' Heb. 13:5. and Josh. 1:5. And so,
this should be the conversation of all that profess Christ Jesus,
and then they would covet after the best gifts, and not after the earthly things,
and follow after love and charity.

And the apostle saith, be ye followers of me, even as I am also of Christ.
And so it is clear the church of the true christians is not to follow any teacher,
but as he followeth Christ in his life, faith, practise, and doctrine.
And if they make a profession of the form of godliness, without the power, and spirit,
and truth, they were to turn away from them, and not to follow them:
but as every one hath received Christ Jesus, so walk in him in humility.

G+++.+++ F.

The 5th month, 1679.
