== The Man Christ Jesus the Head of the Church

[.heading-continuation-blurb]
And true Mediator, in opposition to the Papist Head, their Pope:
Prayers to, and for the Dead, their Shaved Crowns, and Saints`' Relics,
and Purgatory, disproved to be Christian or Judaic,
consequently Heathenish or Pagan, by Scripture Testimony.--By G. F.

Where did ever any, (or where is there any proof,
that either in the old world to the flood,
or from the flood to the coming of the children of Israel out of Egypt,
or from their coming out of Egypt unto Christ,
and from Christ all the apostles`' days,) pray unto the dead, or to saints and angels,
as in this night of apostacy since the apostles`' days,
as the apostates from christianity, called papists do?
Or where did ever any go to graves for dead men`'s bones, or holy relics,
(as they are called,) in all those ages aforementioned, and say,
there was virtue in them to work miracles by, as the papists say they have done,
in the apostacy since the apostles`' days.

And where did ever any, either in the old world, or since,
in the prophets`' and apostles`' days, pray to any saint?
Or make any saint a mediator, (but only Christ Jesus,) as the papists in the apostacy do.

For doth not the Lord say in his law, '`whosoever touches the dead body of a dead man,
and purifieth not himself, and defileth the tabernacle of the Lord,
that soul shall be cut off from Israel,
because the water of separation was not sprinkled upon him?
And if a man died in a tent,
all that came into the tent and all that was in the tent was unclean seven days; yea,
every open vessel that was not covered was unclean, Numb. 1.
and whosoever touched a dead man that was slain with the sword in the field;
or a bone of a man, or a grave, shall be unclean seven days.
And the water of purification was to go upon them:`' now seven is perfect;
so the perfection was to go upon them before they were made clean again.

And Moses, when the children of Israel had been at battle with the Midianites;
he bid them, '`abide without the camp seven days: and whosoever touched any slain,
they were to purify themselves, and to purify their raiments,`' as in Numb. 31.
Yea, all their gold and silver, brass, iron, tin, and lead,
which they had taken from the unclean heathen, they were to make it go through the fire,
and then it should be clean; and it must be purified by '`water of separation;
for that which could not abide to go through the fire must go through the water.`'

And saith the Lord, '`ye shall wash your clothes, and after seven days ye shall be clean,
and then come into the Lord`'s camp.`'

Now if the war in the old covenant was to be so holy and clean,
and all the people were to be so holy and clean; then what is,
the spiritual war in the new covenant?
Must not perfection go upon every one, before they can be clean,
to enter into God`'s camp?
Must not their inward clothing be washed, as they washed the outward?
And must not they pass through the fire of his baptism, and holy water of his word,
before they can come into the camp of God, and to his tabernacle?
For the seventh day was a day of washing and of purifying in the old covenant, yea,
himself and his clothes.
And if he did not wash himself and his clothes, if he touched a, grave,
or a dead man`'s bone, or been in a tent where a dead man lay,
or had been in the war where dead men were; if he purified not himself,
he was to be cut off from the congregation;
because he had defiled the tabernacle of the Lord,
and the water of separation had not been sprinkled upon him.

And therefore, if they were to be so clean and holy in the old covenant,
with these outward washings; much more ought they to be clean in the new covenant,
with the heavenly washings, with the holy water of the word;
and if they be not washed with this water of the word, and the blood of Jesus,
are they not cut off from the holy and clean congregation,
and from God`'s tabernacle spiritually in the new covenant?
For God set his outward tabernacle in his congregation, in the old covenant. Lev. 26:11.
But God sets the heavenly tabernacle amongst his holy and clean congregation,
in the new covenant, that he hath congregated together with his spirit.
And therefore, all they now that run to graves for dead men`'s bones,
and call them relics, and pretend to do miracles by them;
are they not below the law of God in the old covenant, and defilers of that tabernacle,
and cut off from the congregation of the old covenant?
And then much more far off the congregation of the new covenant;
though in words they may profess it.

And the Lord saith, '`every leper, and every one that hath an issue,
or is defiled by the dead, whether male or female, shall be put out of his camp,
that they should not defile his camp,`'

Num. 5:3. as Miriam was put out seven days for her leprosy and disobedience.
For, saith the Lord, '`I will dwell in the midst of you.`'

So see what a care of holiness and cleanness was to be in the camp of the old covenant;
much more in the new, of inward leprosies and issues, who are defiled by dead Adam,
they must be purified by the water of the word, and the blood of Jesus the second Adam,
before they can come into his holy camp.
And who have been in the spiritual war, with the spiritual wickedness,
if that they have touched the dead, or his bone, or his grave, they are defiled,
till they be purified by the water of the living word, which was before the dead was,
or his bone or grave either: for the Lord saith, '`touch not the unclean thing,
and I will receive you.`'
2 Cor. 6:17.
And David saith, '`the heavens are the Lord`'s,
but the earth he hath given to the children of men.
The dead praise not the Lord,
neither any that go down into silence.`' Ps. 115:16-17.
Then why should any ask counsel of the dead,
and pray unto the dead, if they praise not the Lord?
Again, '`David saith, the slain that lie in the grave God remembereth no more,
they are cut off from his hand.`' Ps. 88:5.

And therefore, how can the dead be mediators?
And are not they dead in sins and trespasses,
that run to the graves for dead men`'s bones, and call them holy relics?

And again, David saith,
'`they that join themselves to Baal Peor eat the sacrifices of the dead;
and the dead praise not the Lord.`' Ps. 106:28.

So here you may see they that joined to Baal Peor, did not join to the Lord,
nor sacrifice to him, but such were dead from the Lord,
and did eat the sacrifices of the dead.
And are not all they that profess themselves christians in the new covenant as dead,
that either pray or offer to the dead?
Nay. Are they not worse and more dark than they,
because they profess a higher and greater thing, than they in the old covenant?

And David said, '`thou shalt guide me with thy counsel,
and after receive me into glory.`' Ps. 73:24.

So here you may see, all must be guided by God`'s counsel,
if they will be received into glory; and not be guided by the counsel of the dead,
but by the counsel of the living God: but such as forget the works of the Lord,
they wait not for his counsel to be guided by it.
Ps. 106:13. And Isaiah saith, '`let the counsel of the Holy One of Israel draw nigh,
and come that we may know it.`' Isa. 5:19.

And so, these waited for counsel from God, and not from the dead.
And did not the apostate Jews in the days of Isaiah,
seek unto wizards and familiar spirits, that peeped and muttered?
And were not all those judged in the old law?
And are they not much more in the days of the gospel, the power of God?
For does not Isaiah say, '`when they shall say unto you,
ask counsel of them that have familiar spirits, and unto wizards that peep and mutter:
then make them this answer,
is there a people any where that asketh not counsel of their God,
should men run to the dead from the living.`'

And therefore, he saith further, '`to the law and to the testimony,
if they speak not according to this word,
it is because there is no light or morning in them.`' Isa. 8.

Now here it may be seen, there were some that taught this doctrine to seek after,
and unto wizards and familiar spirits; and therefore,
the prophet thought strange for the living to seek to the dead; and therefore,
such were dark, and had no morning in them,
that were gone both from the law and testimony.

And hath not God given Christ to be a counsellor, and are not all to ask counsel of him,
and so not of any dead saint?

And the Lord said, his people asked counsel of their stocks,
and their staff hath declared to them, and burn incense upon hills under oaks,
and sacrifice with harlots, the spirit of whoredom having caused them to err.
And this was when they were gone a whoring from God in the old covenant;
and these were the people that were gone from the counsel of the Lord,
and from true understanding; therefore, the Lord said they should fall.

And hath not the spirit of whoredom caused them to err,
that ask counsel of painted pieces of wood and images?
And that pray before the dead pictures and images?
But such as do so now, know not the thoughts of the Lord,
neither understand they his counsel, no more than the apostate Jews did of old.
Hosea 4:11, to 14.

And Christ counselled the Laodiceans, saying,
'`I counsel thee to buy of me gold tried in the fire,`' etc. Rev. 3:18.
And therefore, all are to take and ask Christ`'s counsel for this gold.
And Paul said unto the church,
'`he had declared unto them all the counsel of God.`' Acts 20:27. And never
did the apostle in all the counsel of God (that he had declared,) say,
that it was the '`counsel of God,`' that they should set up images, or pray to saints,
or go to the graves of the saints for their bones,
or set up any saint to be a mediator after they are deceased; or set up crosses,
that they should bow before them, or to the images of saints, or pray to the dead;
or that the priests or ministers of Christ should shave their heads:
he declared no such counsel from God, in all his epistles and preachings.

And in Jer. 49:20. he exhorted them there to hear the counsel of the Lord;
and the Lord saith, '`woe unto the rebellious children that take counsel, but not of me;
that cover with a covering, but not of my spirit,
that they may add sin to sin.`' Isa. 30:31.

So these are rebellious children, that take not counsel of the Lord,
and cover not with his spirit; such go down to Egypt for strength, and not to the Lord;
and therefore, woe proceeds against them in the old covenant,
much more in the new covenant, that take not counsel of Christ,
whom God hath given for a counsellor, '`the Prince of peace.`' Isa. 9:6.

But there were people in the old covenant, that professed it, and lived not in it.
And so there is now a people that profess the new covenant, and yet live not in it,
that set at naught God`'s and Christ`'s counsel,
'`and would none of his reproof.`' Prov. 1:30. For the Lord saith,
'`they would have none of my counsel,
they despised all my reproof.`' And these are such as hate knowledge,
and choose not the fear of the Lord; and therefore,
shall they eat the fruit of their own ways, and be filled with their own devices,
and so not with the treasure of life.

And Judah, when they kept in the fear of the Lord,
they gathered themselves together to ask counsel of the Lord in the days of Jehoshaphat,
and the Lord was their counsellor.
So they did not go to ask counsel of the witch to raise up dead Samuel, as Saul did,
when he had disobeyed the Lord.
So Saul that disobeyed, and went to the witch to ask counsel of the dead,
and not of the Lord, he had no victory: but these that asked counsel of the Lord,
they had the victory. 2 Chron. 20:4.

And you may see they asked counsel of the Lord,
whether their way was to be prosperous or no. Judges 20:23.
So they did not go to ask counsel of the dead.

And Christ saith, '`whatsoever things ye shall ask in prayer, believing,
ye shall receive.`' But they must ask of God through him. Matt. 21:22.

And Christ saith, '`whatsoever ye shall ask in my name, that I will do,
that the Father may be glorified in the Son; and if you shall ask any thing in my name,
I will do it.`' John 14:13.

So here it is clear, that all the true christians must ask in Christ`'s name;
and he hath taught so, and exhorted to it, and not in any saint`'s name, or angel.

And Christ exhorts again, saying, '`ask, and it shall be given you;
and every one that asketh receiveth.`' Matt.
vii. And Martha`'s faith was so firm, that she said,
'`she knew whatsoever Christ did ask of God, he would give it.`' John 11:22.

So here you may see, Christ was the counsellor,
in whose name people were to ask in the new covenant;
and God`'s people in the old covenant were forbidden using enchantments,
or observing of times; and were forbidden having regard to wizards,
or seeking after familiar spirits,
'`for I am the Lord your God;`' and him they were to seek unto,
(saith the Lord.) And likewise in the old covenant the Lord
forbids his people from making any cuttings in the flesh,
or prints, or marks upon them for the dead. Lev. 19:28.
'`for they were to be an holy people`' in the old covenant,
so much more in the new.

And the Lord said, '`ye shall not make baldness upon your heads,
nor make any cuttings in your flesh.`'

Now the Lord did forbid his people from doing these things in the old covenant,
so much more in the new.
And therefore, all you that shave your heads, and make them bald,
and make cuttings in your flesh with whips or otherwise,
are not you judged by the law of God, to be out of the practice of the old covenant?
And so, short of the new, in the practice of the heathen,
and not in the practice of the old covenant nor new?

Object.
And now if any of you should object,
that Paul did shave his head after he was a christian. Acts 21.

Answer.
The cause of that act of his, was this, viz. there was a report amongst the Jews,
that he taught against the law of Moses, and was against circumcision; and therefore,
James and the elders did advise Paul, saying unto him, '`purify thyself,
and shave thy head,`' and the rest that were with him,
that they might seem to walk orderly according to the law of Moses:
and this they desired him to do, that they might say,
'`here is four men which have a vow upon them.`'
And Paul did so, with the rest that were with him; and they that were with him,
entered into the temple to signify the accomplishment of the days of purification,
until an offering should be offered for every one of them,
and then the apostle standing up amongst them,
pleading his cause when they were offering up an offering for him,
against whom he said they had nothing except for this one vow,
touching the resurrection of the dead, touching which, said the apostle,
'`I am called in question of you this day.`' Acts 24:21.

So, though the apostle did condescend to the Jews,
to shave his head, and purify himself. Acts 21:24.
and Num. 6:13,18. Yet when they came to offer an offering for him,
he was made to trample down all that he did in that thing,
and to preach Christ the resurrection, who was the offering once for all.

And his so yielding to their weakness, was the means of his being taken prisoner,
and like to have been killed also, by his persecutors, the Jews;
and so he was tossed up and down, till he was brought prisoner to Rome.
But the command of the Lord was, '`that they should not shave their heads,
but only pole them;`' and therefore there is an express
command of God against shaving of their heads. Ezek. 44:20.

Now Paul shaving of his head under a vow,
was according to the Nazarites shaving of their heads under a vow. Acts 18:18.
For all the days of their separation,
there was '`no razor to come upon their heads,`'
neither were they to come near any dead body,
no, not so much as their father or mother, sister or brother;
for the '`consecration of his God was upon his head;`' and if a man died suddenly by him,
he defiled his head of consecration;
and then he was to shave his head in the seventh day of his cleansing.

And again, Numb. 6.
'`the Nazarite shall shave his head at the door of the tabernacle of the congregation,
and shall take the hair of his head of his separation, and shall put it into the fire,
which is under the sacrifice of his peace-offering.`'
So this was the law of God to the Nazarites,
who were under a vow '`to shave their heads,`' else by the law of God,
the priests were not to shave their heads, as may be seen in Ezek. 44.

So, for priests to shave their heads, is neither a gospel command, nor law of God,
except such as were under a vow, as aforesaid.

But do all the priests, and others, that shave their heads now,
do it as under the vow of the Nazarites?
And do they not come near any dead, let them be ever so near a kin?
And when they shave their heads,
do they shave them at the '`door of the tabernacle
of the congregation,`' the place of shaving?
and do they burn their hair under the sacrifice of the peace-offering?
And if so, do not they deny Christ come in the flesh,
who hath '`offered up himself once for all?`' Who cleanses with his blood,
and washes with the water of his word; with which they must be cleansed,
before they can come into his tabernacle and congregation.

So shaving of heads, to priests and others, and making bald their heads,
was forbidden by the law of God,
except it was such as were under the vow before-mentioned, and the Nazarites:
and when they did shave their heads for their separation,
they were to burn it under the sacrifice of the peace-offering, as aforesaid.
And this shaving of these Nazarites, and those under this vow,
it was to be done before the '`door of the tabernacle
of the congregation,`' and not in a private house.
So this was the cause of the shaving of heads; else the law of God was against it,
by which the priests were not to shave their heads. Ezek. 44:20.

And the Lord commanded Moses
'`to take the Levites from amongst the children of Israel, and cleanse them;`'
and they were to '`shave their flesh, and wash their clothes.`'
And when they were cleansed,
they offered a young bullock for a meat-offering, and another bullock for a sin-offering;
and then Aaron offered the Levites before the Lord,
for an '`offering for the children of Israel,
that they might execute the service of the Lord.`' So here you may see,
all the Levites must be washed and cleansed,
and they must offer up for themselves before they could be offered up to the Lord;
and then they might offer the clean offerings for the people.

So they were not fit for the service of the Lord, till they were cleansed, Num. 8:6.
And so the Levites were separated from the children of Israel,
and the Lord said, '`they are mine.`' And now this Levitical priesthood being changed,
and the law also, by which they were made, with all its services, and shavings,
and washings, and sprinklings, and the commandment disannulled that gave him his tithes,
by Christ Jesus:
and so the Levitical priesthood is not to be followed by the true christians;
but Christ is to be followed, who came not after the order of Aaron,
but of the tribe of Judah, who is to be followed and heard in all things.

Now, making baldness on the head, was a judgment to some,
as you may see in Micah 1:16.
For the Lord saith,
'`I will turn your feasts into mourning, and your songs into lamentation,
and I will bring sackcloth upon your loins,
and baldness upon every head.`' So that baldness
was the judgment which the Lord brought upon them, Amos 8:10.
'`and they shall cast dust upon their heads, and wallow themselves in ashes;
and they shall make themselves utterly bald.`' Ezek. 27:30-31. and 7. 17, 18.
'`All hands shall be feeble, and all knees shall be weak as water:
they shall gird themselves with sackcloth, and horror shall cover them,
and shame shall be upon all faces,
and baldness shall be upon all their heads.`' And
in Jer. 68:37. '`every head shall be bald,
and every beard shall be clipped, and upon all hands shall be cuttings,
and upon all loins sackcloth,`' etc.
So here their baldness was a judgment upon them, there was so great a lamentation.
And in Isa. 22:12. '`in that day did the Lord of hosts call to weeping, to mourning,
to baldness, and to girding with sackcloth.`' And again,
in Isa. 15:2. was not misery the cause of their baldness there?
And in Isa. 3:24. when he had reckoned up the vanities of the children of Israel,
and reproved them; he told them, that '`instead of well-set hair,
they should have baldness, and instead of a stomacher, a girdle of sackcloth,`' etc.
And in Job 1:20. when he was in his trials, sufferings, and misery,
he '`rent his mantle and shaved his head,`' etc.

So this manner of shaving heads, was sometimes as a judgment,
and sometimes through trials and troubles,
etc. and also there was another case and example of the women`'s shaving their heads:
when a young woman who was not of the Jews, was taken captive, if a man did marry her,
she was to '`shave her head, and pare her nails, etc. and put off her captive raiment,
and bewail her father and mother a whole month,`'
and then a Jew in the old covenant might marry her. Duet. 21:12-13.

Now, concerning the law of cleansing of lepers, they that were to be cleansed,
were to wash their clothes, and shave off all their hair,
and wash themselves in water, Lev. 14:8-9.
'`on the seventh day he shall shave all the hair off his head,
and his beard, and his eye-brows; even all his hair he shall shave off,
and shall wash his clothes, and his flesh he shall wash in water and shall be clean,
and the eighth day the priest shall offer two lambs without blemish for him.`'
So here you may see the ground of the lepers`' shaving of their heads,
etc. in the old covenant: but you may see by the law of God,
they were not to make baldness upon their heads, Lev. 21:5.
and x. 27. saying in express words,
'`ye shall not make baldness upon your heads,
nor cuttings in your flesh.`' And in Ezek. 64:20. there it was said,
'`the priests were not to shave their heads.`' So here was an express
command of God against the priest`'s shaving of their heads;
though in some cases, as aforesaid, there was the use of shaving in the old covenant.
But where did ever Christ, who sent forth the apostles, give a command,
that they should shave their heads?
Or where did ever the apostles, after Christ, give any such command in the church?
Let us see an order for it from Christ and his apostles, you that plead antiquity,
and then it will be seen how far short your practice
of shaving reaches to the apostles`' days.

And, as concerning asking counsel of the dead:
they were not to make themselves bald for the dead, nor defile themselves with the dead.
Levit. 21. And the sons of Aaron were expressly forbidden,
'`they shall not make baldness upon their heads,`' as aforesaid, Levit. 21.
For whatsoever they touched, that was unclean,
they were to wash themselves and to purify themselves.
And the Lord said, '`ye are the children of the Lord your God,
ye shall not cut yourselves, nor make baldness betwixt your eyes for the dead,
for thou art an holy people unto the Lord thy God,
for I have chosen thee to be a peculiar people unto the Lord thy God,
above all nations that are upon the earth.`' Duet. 14:1-2.

And the high priest was not to go to any dead body to defile himself,
neither to his father nor his mother;
neither was he to uncover his head or rent his clothes. Lev. 21:10-11.
And generally throughout all the scriptures,
it may be seen how people were to pray unto the Lord, and not to any saint;
for they were commanded to '`pray unto the Lord for the peace of
the city.`' Jer. 24:7. And in Job 33:26. there it is said,
'`pray unto the Lord,`' etc.

And a multitude of scriptures might be brought both in the Old and New Testament,
how that people were to '`pray unto the Lord,
and hearken unto his voice;`' and no where in all the scriptures can it be found,
that they were required to pray unto any, but God and Christ, in whose name alone,
whatsoever his people asked, it should be given unto them.

And in Prov. 21:16. ye may see, there were congregations of the dead;
'`for,`' saith he,
'`the man that wandereth out of the way of understanding shall remain in the congregation
of the dead.`' And these that remain in the congregation of the dead,
are wandered both out of the way of the old covenant, and the new,
and from the light and spirit of Christ,
which gives the knowledge and understanding of Christ, their way to God.
And these congregations of the dead can offer but
the unsalted and unsavory sacrifice to the dead.
And in Ecc. 9:5-6. it is said, '`for the living know that they shall die,
but the dead know not anything, neither have they any more reward;
for the memory of them is forgotten; also, their love, and their hatred,
and their envy is now perished;
neither have they any more a portion forever in any thing that is done
under the sun.`' Then what good do your prayers to them do for the dead,
if they know not anything, and have no more a portion forever,
in any thing that is done under the sun?

And doth not the angel say,
'`why seek ye the living amongst the dead?`' So the
living is not to be sought for amongst the dead.
And did not the angel say,
'`he is risen,`' to them that so sought Christ Luke
24:5. And Christ is a judge of the quick and dead,
who saith, '`come unto me,
that ye may have life.`' So people are not to seek to the dead, but to Christ,
who is '`alive and lives forevermore.`' 2 Tim.
4:1. and Rev. 1:18. And doth not the Lord say,
'`look unto me, all ye ends of the earth,
and be saved.`' So they are not then to look unto the dead to he saved, but to Christ.
And '`none comes to the Son, but whom the Father draws.`' And, '`God so loved the world,
that he gave his only begotten Son into the world,
that whosoever believeth in him should not perish, but have everlasting life.`'

And ye may see how the Jews, after they went from the covenant of God,
and disobeyed his commands, then they made a covenant with death,
and were at an agreement with hell, like the apostate christians,
who are gone out of the new covenant of light, life, and grace.
And then like the Jews that forsook the old covenant, they make lies their refuge,
and under falsehood do they hide themselves,
making covenants with the pope and his substitutes, for the pardon of their sins, past,
present, and to come;
who thereby endeavour to make void Christ`'s pardon and forgiveness.
But your covenant with death shalt be disannulled,
and your agreement with hell shall not stand;
when the overflowing scourge shall pass through, then shall ye be trodden down by it,
as the rebellious Jews were of old.

And they that have made a covenant with death, and an agreement with hell,
in the time of the new covenant, or old, they can offer and sacrifice nothing,
but what they have out of hell and death, to that which they have made a covenant withal.
And are not all the enchanters, sorcerers, and charmers, forbidden by the old covenant?
And were not the astrologers, star-gazers, and monthly prognosticators,
reckoned amongst them?
see Isa. 47:12-13. Where the Lord saith,
'`thou art wearied in the multitude of thy counsels;
let now the astrologers and star-gazers,
the monthly prognosticators stand up and save thee from these things,
that shall come upon thee: behold, they shall be stubble, the fire shall burn them,
they shall not deliver themselves from the power of the flame.`'

Therefore, God`'s people are not to trust in such things,
nor follow such things in the time of the old covenant nor new.
And what could all the Egyptians or Babylonian sorcerers
do to Pharaoh or to Nebuchadnezzar`'s dream?
Did not God bring all their counsels to naught?
And therefore, all astrologers, sorcerers, enchanters,
and witches were forbidden all along, as may be seen in the scriptures;
and makers of images and idols, or the likeness of any thing in heaven or in earth;
all those things are forbidden by the Lord God to be made, served, bowed to,
or worshipped; for these were the practises of the heathen, and not of the people of God,
in the old covenant nor in the new.
For God will '`frustrate the tokens of the liars, and make the diviners mad,
and turneth the wisdom of the wise backward, and maketh their knowledge foolishness:
yet God confirmeth the word of his servants,
and performeth the counsel of his messengers.`' Isa.
44:25-26. And the Lord God saith,
'`ye shall not use enchantment, nor observe times.`' Lev. 19:26,31,
and 37. '`But ye shall observe my statutes, saith the Lord:
for they that observe lying vanities,
forsake their own mercy.`' Jonah 2:8. And the apostle forbids`' '`observing of days,
months, and times,`' Gal. 4:11. and said, '`he was afraid of them,
lest he had bestowed his labours of such in vain.`' And Christ tells the Jews,
that were in the observation of such things, Luke 17:20.
'`the kingdom of God comes not with observation.`'

So they that be in such things, and look to find the kingdom of God in these things,
cannot receive it.

And ye may see, that they who forsook the Lord, and observed times, used enchantments,
and dealt with familiar spirits and wizards; and such, at the last,
sacrificed their children in the fire,
and wrought much wickedness in the sight of the Lord, and provoked him to anger.
And these run into the making of graven images and idols to worship,
and bowed down to them, and the gods of their own making, like the heathen,
who forsook God and his covenant.
2 Kings 21.

And there was not to be found amongst God`'s people
in the old covenant any that used divination,
or an enchanter, or a witch, or an observer of times, or a charmer,
or consulter with familiar spirits, or a wizard, or necromancer,
or such an one as made his son or daughter to pass through the fire;
for all these things were forbidden by the Lord;
and all these things are an abomination to the Lord:
'`and because of these abominations the Lord thy
God hath driven them out from before thee;
for these nations, that thou shalt possess, hearkened unto observers of times,
and diviners.
But as for thee, the Lord thy God hath not suffered thee so to do;
thou shalt be perfect with the Lord thy God.
For the Lord thy God will raise up a prophet unto thee out of the midst of thee,
and unto him shall they hearken,`' (speaking of Christ in the new covenant,
like Moses in the old,) and in this prophet (that God raises up,) Christ Jesus,
he will put words in his mouth,
and he shall speak unto his people in the new covenant all that God commands him,
as Moses did in the old: who was faithful in his house in the old covenant,
as Christ is faithful in his house in the new:
'`and whosoever will not hearken unto my words, saith the Lord, which he (to wit,
Christ,) shall speak in my name,
I will require it of him:`' as Moses did speak from
the mouth of the Lord in the old covenant;
and those that did not hearken unto his words, and obey them in the old covenant,
the Lord required it of them.`' Deut. 18.

And God`'s people were forbidden by the Lord in the old covenant, saying,
'`ye shall not print any marks upon your bodies,
for it was the works of the heathen.`' Levit. 19.
And as the Lord`'s people were forbidden in the old
covenant to serve any of the gods of the nations,
and their manner of living, ways, worships and religions;
so surely much more are they forbidden in the new covenant,
under Christ the great prophet, as you may see throughout the scriptures.

And you may see the express command of God against images, likenesses, and figures.
Deut. 4. The Lord commanded Moses in the old covenant,
to teach the Jews his statutes and judgments, that they might do them;
and bid them take heed unto themselves, saying,
'`you saw no manner of similitude in that day when the Lord spoke unto you in Horeb,
out of the midst of the fire:`' therefore, they seeing no similitude that day,
'`thou shalt not make any graven image, nor the similitude of any figure,
likeness of male or female, or the likeness of any beast of the earth:
or the likeness of any winged fowl in the air;
or the likeness of any creeping thing on the ground;
or the likeness of any fish in the waters.`'

And thus you may see,
that they were forbidden making any likeness of any thing in heaven or earth,
lest at the last they should come to worship the host of heaven.

And here you may see, they were not only forbidden the worshipping of such things,
but the making the likeness of them by the express command of God.
But oh! how full of these images and likenesses are the houses of these called christians,
which were forbidden in the old covenant?
So that it is become a trade amongst such christians to make such things,
which the Jews in the old covenant were forbidden;
which they in the new covenant should much more forbear to do, by applying their minds,
ears, and eyes to Christ, the great prophet, and hearken unto him,
who renews them up into the image of God.

Now concerning purification, purging, and cleansing:
if the Lord had intended a purgatory after people are dead to purge them in.
which the scripture no where speaks of,
what needed all these purifications in the time of the law? Num. 19:9.
2 Chron. 13:19. Neh. 12:45. Lev. 8:15. Num. 8:21. Lev. 12:4.
and many other scriptures might be instanced concerning purification and purifying.

And in Malachi 3:3. '`he shall sit as a purifier, and a refiner by fire,
purging the sons of Levi: and is like a refiner`'s fire, and fuller`'s soap.`' Now,
is not this refining and purging of people to be whilst they are upon the earth?
But when they are dead, and gone into purgatory?
God and his people do not say so.

And you that talk of a purgatory to purge and refine you in after you are dead,
have not you forgotten all these scriptures,
how that Christ by himself hath purged our sins? Heb. 1:3.
'`and he his own self bore our sins in his own body on the tree,
that we being dead to sin, should live unto righteousness.`' Mark,
those lived unto righteousness, which were dead unto sin:
and so the apostle did not teach people to look for a purgatory, when they were dead. 1 Pet. 1:24.
And how can it be said, that you are dead to sin,
and that Christ bore your sins in his own body on the tree,
when that you look for a purgatory to be cleansed in after you are dead?
And the apostle told the saints, whilst they were upon the earth,
'`you have purified your souls, in obeying the truth,
through the spirit.`' 1 Pet. 1:22. So these true
christians need not look for a purgatory.
And John saith, '`if we walk in the light, as he is in the light,
then have we fellowship one with another,
and the blood of Jesus Christ his Son cleanses us from all sin.`' So mark,
he was the cleanser from all sin: so they needed not a purgatory.
And they that are not cleansed from all sin, are they that do not walk in the light,
as Christ is in the light;
and such in their darkness may imagine a purgatory to cleanse them in,
and Christ hath appeared to put away sin by the sacrifice of himself.
And the apostle saith, '`it is appointed unto men once to die,
and after this to come to judgment.`' Heb. 9:27. So he doth not say,
they are appointed for purgatory, but for judgment.

And the apostle saith in his general epistle, to the christians in his day;
'`forasmuch as ye know, that ye are not redeemed with corruptible things,
neither with silver and gold, from your vain conversation,
but with the precious blood of Jesus Christ.`' 1 Pet. 1:18.

Now consider this, you that plead antiquity, and that pretend to pardon people`'s sins,
and give them indulgences for their sins for corruptible things, as silver and gold,
have not you made the blood of Christ of no effect?
And made people to believe a lie, that buy your pardons and indulgences for their sins?
And then tell them of a purgatory when they are dead,
and keep them in their vain conversation, when they are living:
and so out of the catholic faith,
and the true knowledge of the true christians in the primitive times,
who knew that they were not redeemed with corruptible things, as silver and gold,
but with the precious blood of Christ Jesus.

And did not Christ say to the believing thief,
'`this day thou shalt be with me in paradise?`' and you will belie the scriptures,
if you say, that it was a purgatory.
And Christ saith, that '`he purgeth,`' every branch that beareth fruit,
that it may bring forth more fruit; and that branch which doth not bear fruit,
he takes it away; so Christ is the purger.
And he said to his disciples, that they were clean through his word:
so not through a purgatory, after they were dead. John 15.

And as John the Baptist declares, how that Christ should come after him; and saith,
'`he shall baptize you with fire, and the Holy Ghost;
and he shall thoroughly purge the floor, and burn up the chaff with unquenchable fire,
and gather the wheat into his garner.`'

Now all you that plead for a purgatory to be purged and purified in,
do not you deny the baptism of Christ to purge you with his fire and Holy Ghost?
And to purge out the old leaven of the old Adam and the devil,
who hath got in by transgression since Adam fell?
For all this purging, purifying, washing, and cleansing is to Adam and Eve,
and their sons and daughters,
since they fell from the image of righteousness and holiness,
that God Almighty made them in.
So Christ the second Adam, that never fell, nor sinned, who had no guile in his mouth,
is the purger and cleanser of all his people with his blood and baptism,
and circumciser with his spirit, in putting off the body of death, and sins of the flesh,
which are gotten up into man and woman by transgression:
for they had not this body of death and sin before they fell,
when God Almighty made them in his image and likeness.

And so it is the blood of Christ that '`purges the conscience from dead works,
to serve the living God.`' Heb. 9:14. So no purgatory: for it is the blood of Christ,
that cleanses from all sin.

But if you have forgotten this purger, and so have invented another, to wit, a purgatory,
you must not plead your antiquity from the apostles for that;
but from the false conceptions of your apostatized bishops and popes,
and through your long continuance in your blindness, who have wanted the true knowledge,
and temperance, and patience, and godliness, and true brotherly-kindness,
to your fellow creatures, and the true love that Christ taught to his disciples,
to '`love all men.`'

This catholic love you have wanted; and therefore, have you massacred, killed,
and persecuted so many upon the account of religion,
and have forgotten that which should purge away your sins, to wit, the blood of Christ.
And therefore, have you imagined a purgatory after death,
and taught this for a doctrine amongst people instead of the blood of Christ Jesus:
read 2 Pet. 1. to 6.
And therefore,
come to that which will purify your hearts from your double-mindedness,
and take the apostle James`'s advice,
in James 4:1 to 8. '`that your minds may be single to Christ.`' For the apostle saith,
'`Christ, who gave himself for us, that he might redeem us from all iniquity, +++[+++mark,
from all iniquity,]
and purify unto himself a peculiar people, zealous of good works.`'

And the apostle exhorts Titus; '`these things speak and teach,
exhort and rebuke with all authority.`' So he was to rebuke
all such that taught a doctrine contrary to this.
So no man`'s iniquity or sin (it is clear,) can be pardoned by men`'s indulgences,
neither can any man be redeemed from them by any gold or silver,
or any other corruptible thing: and they that think they can,
do set up another pardoner and forgiver, than God and Christ Jesus;
which is an antichrist, as you may see, 2 Thess. 2:4. and are to be rebuked:
for the Lord saith,
'`I will pardon all their iniquities.`' Jer. 30:8.
And '`Christ hath washed us from our sins,
in his own blood.`' Rev. 1:5,9. And '`their garments
were made white in the blood of the Lamb. Rev. 7:14.
And the saints overcame by the blood of the
Lamb.`' Rev. 12:11. And the apostle tells the Ephesians,
through what they had redemption, which was through the blood of Christ Jesus. Eph. 1:7.
And doth not he tell the Colossians the same?
Who saith, '`in whom we have redemption through his blood,
even the forgiveness of our sins.`' Col. 1:14. So away with all the pope`'s forgiveness,
and selling of pardons, and purgatories.

Yea, the apostle tells the Ephesians, '`you who sometimes were afar off,
are now made nigh by the blood of Christ.`'

So it is the blood of Christ, that made nigh the saints then,
and makes nigh the saints to God now: which blood doth redeem, and wash, and cleanse,
and purify from all sin.
And Christ having abolished in his flesh the enmity, even the law of commandments,
containing ordinances, and so broken down the partition-wall betwixt Jews and Gentiles,
to make to himself of both Jews and Gentiles, (of these twain,) one new man:
so making peace, that he might reconcile them unto God,
in one body through the blood of his cross; to reconcile all things unto himself,
whether things in heaven, or things in earth; having slain the enmity thereby,
Eph. 2:14, to the end.
And the gospel of peace was preached to them that were afar off, and them that were nigh;
and Christ the foundation for Jews and Gentiles to build upon;
who was the prophets`' and apostles`' foundation, the chief corner-stone in God`'s house.
And so you may see, it is said, '`who hath reconciled us unto himself, by Jesus Christ:
and God was in Christ, reconciling the world unto himself,
not imputing their transgressions unto them.`' 2 Cor. 5:18-19. So it is clear,
here was no purgatory after death, spoken of to wash, purify or cleanse people in,
but it was through Christ Jesus only.

And all that look for a purgatory after they are dead,
are not of that true catholic faith, which the apostles were in,
and true church in the primitive times; which true faith Jesus is the author of.
For they that receive the end of this catholic faith,
receive the salvation of their souls. 1 Pet. 1:9.

So here is no purgatory; and where a purgatory is pleaded for,
the end of this faith is not received.
And faith is the victory over that which separated man from God:
by which faith he hath access to God, and by it pleases God.
And it is faith that sanctifies. Acts 26:18.
So they need not have a purgatory, that be in this catholic faith:
and they that tell people of a purgatory, are out of the sanctifying and saving faith.
And the saints`' hearts were purified by faith;
and this was the doctrine the apostle preached, to the primitive christians`' church. Acts 15:9.
And they that tell people of a purgatory to purge them in,
are erred from this catholic purifying faith.
And the just shall and do live by this purifying, sanctifying faith. Heb. 1:4.
and Rom. 1:17. And this faith which
Christ is the author and finisher of,
did justify and purify the church then, and the saints now:
by which faith being justified, they had peace with God, this divine, holy,
and precious catholic faith.
So they that imagine a purgatory to cleanse them in, and thereby,
or therein expect to be cleansed, purged, or justified, are out of this catholic faith:
for the apostle saith, '`being justified by faith,
we have peace with God through our Lord Jesus Christ.`'

And so by faith, God`'s people stood, and they walked by faith, and not by sight:
and they lived by the faith of the Son of God,
which faith the Son of God was the author and finisher of; this holy, precious, divine,
purifying, sanctifying, justifying, saving, catholic faith,
by which they had access to God, and in which they pleased God,
through which faith they had victory over that which displeased him;
so they need no pope`'s imagined purgatory.

And by this faith did Abel offer: and by this faith was Enoch translated:
and by this faith did Noah build the ark, by which he and his family were saved:
and by this faith did Abraham forsake his country, and country religion,
and followed and obeyed the Lord, from whom he received the blessing:
and by this faith was Moses preserved, when he was hid three months by his parents:
and by this faith did Moses forsake the pleasures of Egypt,
and refuse to be called the son of Pharaoh`'s daughter:
and by this faith were the three children preserved
in persecuting Nebuchadnezzar`'s flaming furnace:
and by this faith was Daniel preserved in the lion`'s den,
and their mouths closed from devouring him.
So faith is that which resists the devil, and it is the shield of God`'s children,
and the weapon of the elect, which were elected before the world was;
which faith gives them victory over the world.
So they that preach up or believe a purgatory,
are erred from this catholic faith in Christ, who was and is the saints purger.

And John tells the church in his general epistle, 1 John 5:4.
'`this is the victory that overcometh the world,
even your faith.`' So if there be no overcoming of the world,
then there is no witnessing of this faith.
And whosoever preaches,
that though persons fall short of overcoming the world in this life,
yet they may have a purgatory when they are dead, they are erred from the catholic faith;
for there is but this living, purifying, justifying, holy faith,
which Christ is the author and finisher of;
which is the victory of all God`'s elect people, before the foundation of the world,
and gives them the victory over the world.
And therefore, the apostle Peter saith to the church, in his first general epistle. 1 Pet. 1:5.
They were '`kept by the power of
God through faith unto salvation.`' So this divine,
holy, purifying, precious, catholic faith, which Christ was,
and is the author and finisher of, was the saints keeper, through the power of God,
by which they had access to God, and in which they pleased God: and in which divine,
and holy precious catholic faith all the saints have unity.
And this is the one true catholic faith; so not many. Eph. 4:5.
And this was the one faith, which the saints were to contend for,
as in Jude is spoken of: and this is the faith, which all the elect of God do preach,
and hold forth to all the world; and that they must look unto Jesus,
the author and finisher of. Heb. 12:2.

And now concerning the true headship of the church: Christ Jesus,
who died for the sins of the world, and tasted death for every man,
is risen from the dead, and set on the '`right hand of God in the heavenly places,
far above all principalities and powers, might and dominions,
and every name that is named, not only in this world, but also in that which is to come:
and hath put all things under his feet,
and gave himself to be head over all things to his church, which is his body,
the fulness of him, that filleth all,
and in all.`' Eph. 1:20. So ye may see Christ is the head of his church.
And never did Christ set up any of the apostles to
be the head of the church upon the earth,
but he called them servants and friends,
and they called themselves apostles and servants, as may be seen in their epistles:
and Christ said unto them, '`he that will be greatest amongst you,
let him be servant unto all.`'

And so, you that set up any man to be pope or chief head of the church,
and persecute others, because they will not believe it;
have you not been like a monstrous body without a head, till you have made one?
And how often goes this off your body, till you have made another?
But by this doth it not plainly appear that you are erred from the one, true,
and everlasting head, Christ Jesus,
who is the author and finisher of the true catholic faith,
who was the head of his church in the apostles`' days, to the primitive christians,
after he was crucified, and risen from the dead; so he is still to all true christians:
'`who was dead, and is alive, and lives forevermore,`' who saith,
'`I am alpha and omega, the first and last:`' which is the present head of the church,
and which was, and which is to come in flames of fire, upon all that do not obey him:
and with reward of life eternal to them that obey him, and believe in him. Rev. 1:18.

And the apostle tells the Ephesians, that Christ is the head of the church,
and Saviour of the body.
And Christ so loveth his church, and gave himself for it;
and the church is to be subject to Christ its head, who both died for it,
and shed his blood for it, and redeemed it, and sanctified it,
and purchased it with his blood; and cleanses it,
and washes it with the washing of the water of the word, that he might present it to God,
a glorious church without spot or wrinkle, that it should be holy and without blemish,
and Christ cherishes and nourishes his church with his heavenly and spiritual nourishment,
and heavenly cherishment; so that his church comes to be members of his body,
'`and flesh of his flesh, and bone of his bone.`' Ephes. 5.

And the apostle writes the same to the Colossians, and tells them,
that by Christ all things were created, '`that are in heaven and in earth,
visible and invisible, whether they be thrones or dominions,
principalities or powers,`' all things were created for him and by him, to wit, Christ,
who is the image of the invisible God, the first born of every creature,
and he is before all things, and by him all things consist,
and he is the head of the body, the church: who is the first begotten, from the dead;
'`that in all things he might have the preeminence:
for it pleased the Father that in him should all fulness dwell.`' Col. 1:15,19.
So you may see how clearly the apostle did exalt Christ above all,
and to be the head of the church: and not himself, nor Peter,
nor any other of the apostles.
And they did '`warn and teach every man in all wisdom,
that they might present every man perfect in Christ Jesus.`' So here you may see,
they presented them to their head: and therefore,
they exhorted the saints to be established, and rooted, and built up in Christ,
as they had been taught, and bid them beware,
lest any man should spoil them through philosophy or vain deceit,
after the traditions of men, and rudiments of the world, and not after Christ:
for in Christ dwells the fulness of divinity, who is the head;
and all the saints are to be complete in him, their head,
as the saints were in the apostles`' days.

And the apostle writes to the Ephesians, '`to grow up in Christ in all things,
who is the head:`' so that nothing was to be betwixt them and Christ,
from whom the whole body is fitly jointed together,
and compact by that which every joint supplieth,
according to the effectual working of the measure in every man,
making increase of the body, to the edifying itself in love.
So that the saints are to '`grow up unto the measure of
the stature of the fulness of Christ,`' their head,
and not to be tossed to and fro, and carried about with every windy doctrine,
by the cunning craftiness of men, who lay in wait to deceive.

And therefore,
the apostle exhorts the church to let no man beguile
them of their reward in a voluntary humility,
and worshipping of angels, intruding into these things, which they had never seen,
vainly puffed up in a fleshly mind, not holding the head, Christ Jesus,
from which all the body by joints and bands,
have nourishment ministered from Christ their head, and knit together,
increaseth with the increase of God.
So there was many then who would beguile them from their living head, Christ Jesus;
as there is many now since the apostles`' days, that have set up a pope to be head, etc.
But the apostle set up Christ to be head of the church.
For the apostle had labour and travel enough to bring people to Christ, the head;
who were to '`go into all nations,`' to preach the gospel of Christ,
that they might believe in Christ their head.

And when the apostle said to the Colossians, '`let no man judge you in meats or drinks,
or in respect of an holy day, or new moons, or sabbath day;
which were shadows of good things to come: but the body is of Christ,
who is the substance of all the shadows.`' And so you may see what sort they were,
that did not hold Christ the head,
and would beguile people of the reward they had from him their head.
And therefore, saith he,
'`if ye were dead with Christ from the rudiments of the world:`' they were not to touch,
taste nor handle the ordinances, doctrines or commandments of men,
though they had never such a show of will-worship; for these neglected the body,
and did not hold Christ the head.

And therefore, they that do not hold Christ the head of the church,
have lost their reward from him, and do neglect the body, and are in the doctrines,
ordinances, and commands of men, and the rudiments of the world;
and so in the rudiments of the world they are alive, and not dead with Christ from them;
and such may make heads of their own for their bodies, when they have none upon them,
as the papists do; and when one is dead, may make another, and may persecute, prison,
and kill such as cannot own him to be the head of their church;
and then set all their body on persecuting as long
as (that) their head stands upon their body,
as history and chronicles do testify.
Yea, they evidence the bloody works of this head, (that the body hath made,
and set upon it,) and the fruits of this bloody, persecuting body.
It was never the works of the true head,
nor true church to persecute any that owned Christ their heavenly and spiritual head;
for Christ the true head of his church, said, that '`he came not to destroy men`'s lives,
but to save them;`' and he rebuked such as would have men`'s lives destroyed,
and told them,
'`they knew not what spirit they are of;`' and likewise
gave command to his church the true christians,
(which he was head of,) that they should love one another, and love enemies;
and his church confessed, that their weapons were spiritual,
and their faith was their shield, which Christ was the author of.
So he gave them this spiritual weapon, and the sword of the spirit,
which was the word of God; and their armour was their light;
and their helmet was salvation,
and they were shod with the preparation of the gospel of peace, etc.

So these were the weapons of the true christian church,
that held Christ to be their head; but the apostate church, called christian,
(that is without a head, till they have made one,) their weapons are carnal,
and not spiritual.

And they must all come to the true light,
which Christ doth enlighten every one that cometh into the world withal;
which is the life in Christ; and believe in it, if they come to the true head,
and be grafted into him.
For '`both he that sanctifieth, and they that are sanctified,
are all of one;`' for which cause he is not ashamed to call them brethren, saying,
'`I will declare thy name unto my brethren,
in the midst of the church will I sing praise to thee.`' Heb. 2:11-12.

And likewise, they must come to the grace and truth, which comes by Jesus Christ,
in their hearts and inward parts, if they will come to Christ the head.

And also, they must come to the spirit of God within, and the anointing within,
and let Christ dwell in their hearts, and the word of God to hammer down, cut down,
and burn up that which hath separated from God and Christ,
which they are apostatized into, if they will come to Christ their head,
who will reconcile them to God.

And give over making of faiths,
and look unto Jesus the author and finisher of the true faith.
And give over making of ways, and come to Christ the new and living way,
which the true christians were in, in the apostles`' days.
And give over making of heads, and come to the light of Christ,
which will turn people to Christ their head,
and give them the knowledge of him their head. 2 Cor. 4. Eph. 1:22.

And give over making of religions,
and come to the religion which is pure and undefiled before God,
which will keep them from the spots of the world;
and then they will be ashamed of that imaginary doctrine of a purgatory,
(to cleanse or purge them in, when they are dead,) and of all the heads and likenesses,
and images they have made.

And give over making of worships,
and come to the worship that Christ set up above sixteen hundred years ago,
in the spirit and in the truth:
and so lay away their own worships with all their carnal weapons,
by which they have persecuted in this night of apostacy,
and come to take up Christ`'s spiritual weapons.

And give over making of ministers at schools and colleges, by natural arts, tongues,
etc. and come to Christ, who is ascended on high,
and gives gifts unto men for the work of the ministry, etc.

[.blurb]
=== Now Concerning Mediators.

You in the apostacy,
who look that Mary and other saints should be mediators for you to Christ or God;
this is not catholic doctrine,
neither is it from such as do hold Christ the head of the church;
but from such as have apostatized from him.

For the apostle saith, Heb. 8:6. speaking or Christ, he is the Mediator: and,
Christ is the Mediator of the New Testament;
and the saints were come to Jesus the Mediator of the new covenant:
and this was the '`general assembly of the church of the first born written in heaven,
who was come to God the judge of all,
and to the spirit of just men made perfect;`' and
(as it was said before,) to Jesus the Mediator. Heb. 12:24.
For God would have all men to be saved,
and to come to the knowledge of the truth: '`For there is one God,
and one Mediator betwixt God and men, the man Christ Jesus,
who gave himself a ransom for all, to be testified in due time.`'
1 Tim. 2. to 6.

Now it is clear, there is but one Mediator betwixt God and men, the man Christ Jesus,
who is head of his church; and whosoever hath set up,
or do set up other mediators betwixt God and man, than the man Christ Jesus,
are in the apostacy from the apostles`' doctrine, and follow their own doctrines,
and not the apostolical doctrine; for he is the one Mediator betwixt God and man,
the one eternal, living God, creator of all, and Christ Jesus, by whom were all things,
who gave himself a ransom for all men; he is the alone one Mediator betwixt God and man,
who is the only head of his church, and his church do testify him so to be,
that are come to Jesus, their Mediator; who hath made their peace betwixt them and God,
and so hath received him; who is come, and hath given them an understanding to know him;
and they that have him, have life everlasting.

G+++.+++ F.

The 10th month, 1678.

=== Postscript.

And there is one faith, which Christ is the author and finisher of,
which all must look unto Jesus for this saving, holy, precious, and divine faith,
which purifieth the heart, and is the victory; in which they have access to God,
in which faith they do please God.
And this is the catholic faith, which we are of.

And Christ is the head of his church,
that be gathered out of the whole world into his name;
and he is in the midst of them a prophet, and a priest, and a shepherd, and a bishop,
and a counsellor, and a king to rule in the hearts of his church,
and to exercise those offices in his church.

And Christ set up one worship in the spirit and in the truth,
for all the children in the new covenant, which be Jerusalem,
(that is from above,) her children`'s worship.
For outward Jerusalem was in Canaan, and at the temple,
where the outward Jews did worship in the old covenant, which worship Christ abolished,
when he set up the worship in his new covenant, in spirit and in the truth for Jerusalem,
which is above, and her children.

And there is but one cross which crucifieth people to the world,
which cross of Christ is the power of God.

And the apostles in their days, did exalt Christ in the church, the Interceder,
to make intercession for the saints to God; who said,
'`that Christ ever liveth to make intercession for his people,
and he is able to save them to the utmost, that come to God by him.`' So,
none of the deceased saints did mediate, or intercede,
or make intercession for the living saints;
though the saints were to pray one for another, while they were living upon the earth.
And the prayers of the saints availeth much while they are living;
but when they are deceased, and fallen asleep, to pray to them,
either to be mediators or interceders, or to make intercession to them,
it is neither catholic faith, nor catholic doctrine; but an invention,
as praying for the dead to deliver them out of purgatory.
For Christ is the foundation of God`'s holy house of living stones,
and the rock which his house is built upon;
which rock the gates of hell cannot prevail against:
'`For the foundation of God standeth sure.`'

[.the-end]
End of Vol. 5.
